### ISSUE TITLE
Bots - Engineer bots will always attempt to turn on the Reactor after being dismissed from Turn Off order

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2369] opened 2020-02-27 00:21 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Engineer bots will always attempt to turn on the Reactor after being dismissed from Turn Off order. Sometimes I am trying to keep the reactor off so I can get the engineer to repair the junction box grid first to prevent overload or to prevent wasting fuel while we repair leaks during a major incident, but the moment I tell them to do something else, they'll flip it back on when they can.

**Version**
~0.9.7.1

**Comment by itchyOwl** [comment] 2020-04-13 13:55
This is not a bug, but we might have to consider how the engineer should behave here.

**Comment by itchyOwl** [comment] 2020-04-13 14:50
I changed the behavior in Regalis11/Barotrauma-development@52b86e6 so that the "turn off" option now sets the priority of the order to 0 when it's done. So the bot should now continue doing other stuff as long as the reactor stays off. So there should not be a reason to dismiss the bot. It does not fully address the issue, though, because if you order the bot to something else, they will probably continue operating the reactor if you don't remember to order them to power it off again.

**Comment by Rokvach** [comment] 2020-04-13 18:45
Didn't notice any issues with this, closing.

**Closed by Rokvach** 2020-04-13 18:45 UTC
Labels: Code, Design
