### ISSUE TITLE
Bots should report when they spot an enemy

### ISSUE THREAD

**Issue by jewbuscuslebone** [Regalis11/Barotrauma#4401] opened 2020-11-28 04:58 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
it would be sick if bots on guns yelled a brief description of what the enemy is when they see it, im sure that it would keep immersion and give understandable information.

**Steps To Reproduce**
adding dialogue based on the enemy type.
**Version**
N/A

**Additional information**
thank you

**Comment by itchyOwl** [comment] 2020-12-01 13:57
I think it might be a good idea.

**Comment by itchyOwl** [comment] 2020-12-08 16:16
Implemented in Regalis11/Barotrauma-development@c69735d.

**Comment by Regalis11** [comment] 2020-12-09 08:30
The dialog lines use the untranslated SpeciesName, I suppose we should be using DisplayName instead

**Comment by Xeavas** [comment] 2020-12-11 16:23
[0.1200.0.0] - Bots will say `unidentified` if >1 creature types are present
![unidentified](https://user-images.githubusercontent.com/72674994/101928011-0f5f9e00-3c10-11eb-933e-6e8b617580e7.jpg)

**Comment by Regalis11** [comment] 2020-12-11 16:41
@itchyOwl Not sure if the above is caused by multiple targets or an actual unidentified target, but in any case I think the dialog line could be reworded to make it more obvious it's intended to mean the character doesn't know what the target is (e.g. "got a new target, but I'm not sure what it is"). Now it sounds like the game failed to find the name of the creature.

**Comment by Rokvach** [comment] 2020-12-11 17:14
Moving back to todo

**Comment by itchyOwl** [comment] 2020-12-14 12:10
I suspect that it works as it should: if there's a target that the player hasn't yet encountered, the bot says "New target: unidentified!" or "I've got an unidentified target!". I aimed for brevity and clarity used in the military language, but I guess I didn't get it quite right there, as it can be misunderstood for a bug.

Changed the texts in Regalis11/Barotrauma-develeopment@398ff2f.

**Comment by Rokvach** [comment] 2020-12-14 14:10
Tested, working correctly. Closing.

**Closed by Rokvach** 2020-12-14 14:10 UTC
Labels: Code, Design, Feature request
