### ISSUE TITLE
AI Crash 

### ISSUE THREAD

**Issue by muskaeragon** [Regalis11/Barotrauma#5709] opened 2021-05-06 14:25 UTC
Please fix the problem with AI. When the intelligence of friendly NPCs is disabled and an event occurs at the station (for example, an attack by clowns), the AI cannot perform the action and the game crashes. I`m not using any mods.

**Comment by muskaeragon** [comment] 2021-05-06 14:27
Action plan
1) Start the station
2) Register in the console 
 disablecrewai
3) Find the event associated with the NPC attack (for example)
4) Expect an error in the console and crash

**Comment by itchyOwl** [comment] 2021-05-12 13:05
Fixed in Regalis11/Barotrauma-development@0d3f299.

Steps to repro:
1. "disablecrewai"
2. "triggerevent clownrelations1" (for example, might be good to test it with some other events too)
3. click through the event

**Comment by muskaeragon** [comment] 2021-05-12 16:35
This certainly improves the situation, but the problem will remain the same if one of the players decides to activate the event while the AI is disabled. (Don't ask why you should disable AI intelligence during the game at all). In any case, I have now made such steps:
1) disablecrewai
2) use examine on an event bot
3) Exception: The object reference is not set to an instance of the object. (Exception System.NullReferenceException)
Target Site: Void Update(One-time)
Stack Trace:
in Barotrauma.Combat operations.Update(One deltatim) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\EventActions\CombatAction. cs: line 65
in Barotrauma. eventAction.A subgroup.Update(One deltatim) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\EventActions\eventAction. cs: line 96
in Barotrauma.Conversation.Update(One deltatim) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\EventActions\ConversationAction. cs: line 274
in Barotrauma. eventAction.A subgroup.Update(One deltatim) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\EventActions\eventAction. cs: line 96
in Barotrauma.BinaryOptionAction.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\EventActions\BinaryOptionAction. cs: line 107
in Barotrauma.Event scenario.Update(One deltatim) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\ScriptedEvent. cs: line 213
in Barotrauma.EventManager.Update(One deltatim) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\EventManager. cs: line 657
in Barotrauma.Game session.Update(One deltatim) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession. cs: line 601
in Barotrauma.Game screen.Update(Double deltatim) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen. cs: line 167
in Barotrauma.GameMain.Update(GameTime GameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain. cs: line 969
in Microsoft.Xna. Framework. Game.DoUpdate(GameTime GameTime) in <DEV>\Libraries\MonoGame.\Src Framework\Monogamy.Framework\Game. cs: line 656
in Microsoft.Xna. Framework. Game.Check the box () in <DEV>\Libraries\MonoGame.\Src Framework\Monogamy.Framework\Game.cs: line 500
in Microsoft. Xna. Framework.SdlGamePlatform. RunLoop () in <DEV>\Libraries\MonoGame.\Src Framework\Monogamy.Framework\SDL\SDLGamePlatform. cs:line 92
in Microsoft.Xna. Framework. Game. Run (GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.\Src Framework\Monogamy.\Game.cs framework:line 397
in Microsoft.Xna. Framework. Game. Run () in <DEV>\Libraries\MonoGame.\Src Framework\Monogamy.\Game.cs framework: line 367
in Barotrauma.Program.Main (string[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program. cs: line 58

**Comment by itchyOwl** [comment] 2021-05-14 08:14
I believe that exception is caused by the same method. So the previous fix should handle that too. Note that the fixes are not yet in the game. You can test it in the next unstable release.

**Comment by Rokvach** [comment] 2021-05-26 08:06
Tested, working correctly. Closing.

**Closed by Rokvach** 2021-05-26 08:06 UTC
Labels: Bug, Code, Crash, Low prio
