### ISSUE TITLE
Particles draw behind items outside hulls (drawontop or not)

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#12111] opened 2023-06-02 11:48 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

~~After adding Drawontop to a Particleemitter, the particle did not in fact draw on top of items/walls/characters.~~

**Particles in general appear behind objects when outside hulls, drawontop or not**

It's supposed to be one of the properties you can edit:
https://github.com/Regalis11/Barotrauma/blob/6acac1d143d647ef10250364fe1e71039142539c/Barotrauma/BarotraumaClient/ClientSource/Particles/ParticleEmitter.cs#LL97C6-L97C6

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/bc5e676b-544f-4266-a9bf-41bc33b5010b)

_Dead Fleshgun sprite spawning a bunch of drawontop particles, all behind._
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/d6ddaf1f-5117-486c-8399-c69d797daf0a)

```xml

        <StatusEffect type="OnDeath" target="This">
          <Sound file="Content/Map/Thalamus/Sounds/CARRIER_organs1.ogg" range="2000" selectionmode="Random" />
          <ParticleEmitter particle="organeruption" particleamount="50" scalemin="0.5" scalemax="1" velocitymin="100" velocitymax="500" anglemin="0" anglemax="360" distancemin="-50" distancemax="-50" drawontop="true"/>
          <ParticleEmitter particle="heavygib" particleamount="1" scalemin="1" scalemax="2" velocitymin="0" velocitymax="0" anglemin="0" anglemax="360" distancemin="-50" distancemax="-50" drawontop="true"/>
          <ParticleEmitter particle="gib" particleamount="10" scalemin="1" scalemax="2" velocitymin="100" velocitymax="300" anglemin="0" anglemax="360" drawontop="true" />
          <ParticleEmitter particle="bloodsplash" particleamount="5" velocitymin="100" velocitymax="300" anglemin="0" anglemax="360" scalemin="1" scalemax="2" drawontop="true" />
          <ParticleEmitter particle="whitegoosplash" particleamount="5" velocitymin="100" velocitymax="300" anglemin="0" anglemax="360" scalemin="0.5" scalemax="1" drawontop="true" />
        </StatusEffect>
```

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by ubertpendragon** [comment] 2023-06-02 12:02
Although in the picture the grey chunks aren't using Drawontop, but there are "blood" particles that do 

`          <ParticleEmitter particle="heavygib" drawontop="true" particleamount="1" scalemin="1" scalemax="1" velocitymin="0" velocitymax="0" anglemin="0" anglemax="360" />`

So this isnt totally related to Drawontop

**Comment by Regalis11** [comment] 2023-06-02 12:19
The issue here seemed to be that the particles ignored the "DrawOnTop" value configured in the emitter, and just used the value defined in the particle prefab itself.

**Comment by ubertpendragon** [comment] 2023-06-02 12:22
Sorry for butchering the ticket but it seems ALL the particles appear behind, drawontop or not

**Comment by Regalis11** [comment] 2023-06-02 12:24
Hmm, in that case I think I need to take another look at this. Thanks for the clarification!

**Comment by Regalis11** [comment] 2023-06-21 07:53
@ubertpendragon I could not actually reproduce that. It seems to work correctly if the particle is configured to draw on top, but not when only the emitter is (which seems to be the case in your example xml - neither the heavygib or organeruption particle prefab are configured to draw on top).

**Comment by ubertpendragon** [comment] 2023-06-23 12:19
Simply put vanilla organs in and outside a hull and destroy them

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/169bfb5d-6353-476b-94f3-3d21e211c540)

In the hull, particles will appear in front of the organ, out of the hull the particles will appear behind the organ

Adding `drawontop="true"` doesn't affect this whatsoever

**Comment by Regalis11** [comment] 2023-06-29 17:02
As said, you need to edit the particle prefab, not the emitter. The particles ignored the "DrawOnTop" value configured in the emitter, and just used the value defined in the particle prefab itself.

**Comment by itchyOwl** [comment] 2023-06-30 10:32
Confirm as been fixed in https://github.com/Regalis11/Barotrauma-development/pull/4275. Closing the ticket.

**Closed by itchyOwl** 2023-06-30 10:32 UTC
Labels: Bug, Code, Low prio
