### ISSUE TITLE
Got the Naval Architect achievement after only 3 hours.

### ISSUE THREAD

**Issue by lCaptainBob** [Regalis11/Barotrauma#6406] opened 2021-08-06 01:58 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

I only have 3 hours of game time yet got the Naval Architect achievement.
I only spent about 5 minutes on the ship editor, my playtime so far has consisted of the mechanic tutorial and a couple of hours AFK on that tutorial and on the main menu.

It happened on Windows 10, on the beta steam version if that matters.

https://steamcommunity.com/profiles/76561198074685687/stats/appid/602960/achievements
![image](https://user-images.githubusercontent.com/88520262/128444340-d0be44bc-ab74-4eb9-9635-4da6f90e6a2c.png)

**Comment by Kin-gchris** [comment] 2021-09-17 15:43
This happened to me as well on linux

**Comment by S-K-Tiger** [comment] 2021-09-19 12:54
![BugOvervieuw](https://user-images.githubusercontent.com/55139409/133927965-4bb3796b-9e2e-4b4d-9462-291d780320b9.png)
I didn't even open the editor the second time I booted up the game. I just opened the game, went to settings to get linked to this Github repo and closed the game afterwards. Now I have the achievement twice despite having played the game for only 21 minutes total.
Workshop items (8 total) only include submarines and item assemblies.
- App ID: 602960
- Build ID: 7332103
- Installed content updated: Sep 19, 2021 at 10:46 AM

**Comment by Regalis11** [comment] 2022-11-10 11:58
Attempted to fix this in https://github.com/Regalis11/Barotrauma-development/commit/4f131186fd25b79a7df5ca789e73697170f31667 (link to our private repo). Just a guess at what could potentially be causing this, since I haven't been able to find a way to reproduce the issue myself.

**Comment by Rokvach** [comment] 2023-01-02 11:00
No steps to repro and no reports of it being an issue still since the latest patch release, seems to be working correctly. Closing.

**Closed by Rokvach** 2023-01-02 11:00 UTC
Labels: Bug, Code, Steam, Unstable
