### ISSUE TITLE
Soundcard switching on server/host kicks other players

### ISSUE THREAD

**Issue by EiboThieme** [Regalis11/Barotrauma#6039] opened 2021-06-11 18:28 UTC
- [ X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Switching soundcard on the machine starting the campaign server kicks other players from  campaign

**Steps To Reproduce**
Start server, switch soundcard in settings to another card, some players are kicked.

**Version**
(How do you even learn the version?) Date is June 11, 2021, playing via Steam on Windows 10.

**Additional information**
It might be it is just players not in the same local network which get kicked out, in my case it is switching from onboard hd audio to bluetooth headset. It takes a long while to switch, after which some other players are disconnected.

**Comment by Regalis11** [comment] 2022-05-19 07:14
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7981

**Closed by Regalis11** 2022-05-19 07:14 UTC
Labels: Bug, Code, Networking
