### ISSUE TITLE
Unequipping handheld sonar causes it to drop from inventory sometimes

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#1308] opened 2019-03-19 14:45 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When exploring alien ruins, I find myself dropping my handheld sonar nearly everytime I remove it from hands.

**Steps To Reproduce**
While diving, use the handheld sonar and then put it away.

**Version**
0.8.9.6 steam closed alpha. On multiplayer dedicated server with pretty shoddy latency.

**Additional information**

**Comment by Regalis11** [comment] 2019-03-19 14:50
Could be related to #768. How do you unequip items, by double clicking or using the button above the slot?

**Comment by thegrb93** [comment] 2019-03-19 14:55
Button above slot

**Comment by NilanthAnimosus** [comment] 2019-03-19 14:55
I don't know why but I suffer this a lot and it doesn't matter what I've tried, if I unequip first then equip another item or equip it without having unequipped my last item - the handheld sonar, its specifically the handheld sonar and not many other tools that sure love to drop.

When diving, the handheld sonar is dropped almost every time I've actually swam outside, a good 7/7 or so. my speeders, cutters, stun batons, everything else I've equipped generally hasn't flown out of my inventory, its usually even on a slot 5-7.

and I'll always never notice it having vanished, as if I look up to my character and thats when it sneaks away haha, with my eyes off the inventory

**Comment by thegrb93** [comment] 2019-03-19 14:56
Handheld sonar seems to be the only thing affected so idk if related to https://github.com/Regalis11/Barotrauma/issues/768

**Comment by Regalis11** [comment] 2019-05-23 13:09
Another attempt to fix this: 5c06210. I'm pretty confident it's fixed now: we found out that it's easy to reproduce by moving items around in the inventory while inside a sub that's moving fast. Haven't been able to reproduce it anymore after 5c06210.

**Comment by Rokvach** [comment] 2019-05-23 18:41
I couldn't reproduce this with my previous method of testing the issue, so I can only assume that it is fixed now, closing.

**Closed by Rokvach** 2019-05-23 18:41 UTC
Labels: Bug, Code, Needs testing, Networking-related
