### ISSUE TITLE
Problems with drop shadows and FPS in Barotrauma (ver. 0.18.15.1)| 23.08.22 |

### ISSUE THREAD

**Issue by IClaimerI** [Regalis11/Barotrauma#9754] opened 2022-08-23 18:19 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The appearance of obscure shadows that block the view. The appearance of obscure shadows that block the view also has problems with the frame rate when opponents swim up to you fps drops to 5-10 frames per second and this is a problem not only for me but even for my friend with a computer on RTX.

### Reproduction steps

![n0yxQloGqc8](https://user-images.githubusercontent.com/111908896/186234081-d681f158-8c51-4762-a661-820509fb85ec.jpg)
![iT7w52TI5BQ](https://user-images.githubusercontent.com/111908896/186234094-2a839b91-5e70-4aaf-815b-ec15ddd68a4f.jpg)

### Bug prevalence

Happens every time I play

### Version

0.18.15.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-08-24 06:10
Thank you for the report! I actually doubt this is caused by the shadows - they don't interact with characters in any way, so it shouldn't be possible that they cause a framerate drop specifically when a monster swims up to you. I would suspect it's the monsters themselves that are causing the framerate drop, not the shadows.

In any case, this is something we need to investigate. If possible, it might give us some more clues on what's causing this if you enabled the in-game performance statistics view and sent us a screenshot of what you see when the framerate drops. You can enable it by opening the debug console with F3 and entering "showperf". Thanks, and sorry for the inconvenience!

**Comment by IClaimerI** [comment] 2022-08-24 13:25
Thank you for answering my problem! I probably formulated the text incorrectly, and therefore my arguments were not particularly clear. 

So let me deal with the first statement, namely, the physics of shadows. I found an explanation for this on the Internet, it seems there is a gap between textures and because of this such defects occur and this is considered the norm, although it greatly hinders the construction of the project and the placement of guns. The second question about fps, you correctly noted about considering the problem with monsters, because it is because of them that the frame rate drops so much, but not of the physics of shadows.

**Comment by Krzeszny** [comment] 2022-08-27 06:50
@IClaimerI have you just reported 2 different, unrelated issues in one report? If so, that would explain the misunderstanding and please never report unrelated issues in the same ticket. Each ticket on GitHub is supposed to be 1 issue.

What I understood is this:
1. Shadows aren't rendered properly, as seen in the first screenshots
2. Monsters cause fps drops

**Comment by Regalis11** [comment] 2022-09-05 06:43
I think we can close this: there is an existing ticket about the LOS issues https://github.com/Regalis11/Barotrauma/issues/6000 and  plenty of tickets about poor performance.

**Closed by Regalis11** 2022-09-05 06:43 UTC
Labels: Need more info, Code, Performance
