### ISSUE TITLE
Unstable - Dedicated Server crash in EnemyAIController.UpdateAttack

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#2054] opened 2020-01-25 20:20 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
It appears to have crashed in about two separate locations, all I think would crash on these line numbers is something that shouldn't be null in my opinion.

**Steps To Reproduce**
Unknown, was running campaign, 2nd round failed to finish on 2-3 tries due to creatures. Game also crashed in mission. It occurs mid round during creature attacks, often with players firing on them.

**Version**
Unstable - 0.9.701.0 dedicated server (Windows)

**Additional information**

The three crash reports, noting this was in DEBUG in visual studio but still wrote crash reports instead of giving me helpful information, I have since made attempts at a temporary patch for crashing to creature attacks until a fix can be made for further testing on other issues (Like net sync).

the two different error stacks I noted (Line numbers 702 and 651:

```csharp
Exception: Object reference not set to an instance of an object.
Target site: Void UpdateAttack(Single)
Stack trace: 
   at Barotrauma.EnemyAIController.UpdateAttack(Single deltaTime) in F:\Github Sources\BT-FA\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\EnemyAIController.cs:line 702
   at Barotrauma.EnemyAIController.Update(Single deltaTime) in F:\Github Sources\BT-FA\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\EnemyAIController.cs:line 347
   at Barotrauma.AICharacter.Update(Single deltaTime, Camera cam) in F:\Github Sources\BT-FA\Barotrauma\BarotraumaShared\SharedSource\Characters\AICharacter.cs:line 80
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in F:\Github Sources\BT-FA\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 1973
   at Barotrauma.GameScreen.Update(Double deltaTime) in F:\Github Sources\BT-FA\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 160
   at Barotrauma.GameMain.Run() in F:\Github Sources\BT-FA\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 340
   at Barotrauma.Program.Main(String[] args) in F:\Github Sources\BT-FA\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 38
```

```csharp
Exception: Object reference not set to an instance of an object.
Target site: Void UpdateAttack(Single)
Stack trace: 
   at Barotrauma.EnemyAIController.UpdateAttack(Single deltaTime) in F:\Github Sources\BT-FA\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\EnemyAIController.cs:line 651
   at Barotrauma.EnemyAIController.Update(Single deltaTime) in F:\Github Sources\BT-FA\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\EnemyAIController.cs:line 347
   at Barotrauma.AICharacter.Update(Single deltaTime, Camera cam) in F:\Github Sources\BT-FA\Barotrauma\BarotraumaShared\SharedSource\Characters\AICharacter.cs:line 80
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in F:\Github Sources\BT-FA\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 1973
   at Barotrauma.GameScreen.Update(Double deltaTime) in F:\Github Sources\BT-FA\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 160
   at Barotrauma.GameMain.Run() in F:\Github Sources\BT-FA\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 340
   at Barotrauma.Program.Main(String[] args) in F:\Github Sources\BT-FA\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 38
```

[servercrashreport.log](https://github.com/Regalis11/Barotrauma/files/4112727/servercrashreport.log)

[servercrashreport (2).log](https://github.com/Regalis11/Barotrauma/files/4112728/servercrashreport.2.log)

[servercrashreport (3).log](https://github.com/Regalis11/Barotrauma/files/4112729/servercrashreport.3.log)

**Comment by NilanthAnimosus** [comment] 2020-01-25 23:15
I had patched it by additional null checks and "If null, Return" sort of code, Nothing fancy or great. and the game didn't crash. But I saw this in my console and cannot confirm its not a result of getting past the above (Without fully checking the proper causes) or a completely new bug sadly.

![image](https://user-images.githubusercontent.com/29177976/73128504-5167fd00-3fc8-11ea-81d9-e3a126b820ce.png)

![image](https://user-images.githubusercontent.com/29177976/73128452-89bb0b80-3fc7-11ea-958d-779b336ad4da.png)

**Comment by Kaillera** [comment] 2020-01-26 10:04
I do believe it has something to do with Threshers, as we got these error during the fight against them on Nilanth's server in these cases he posted. Also as a bonus: Thresher mission for multiplayer campaign loves to crash players out once you drive the sub through the first spawning threshold or right before you meet the swarm.

Duplicate of #2019.

**Comment by NilanthAnimosus** [comment] 2020-01-26 10:29
Oh, strange, didn't see any "Related issues" propping it, but it is the same as 2019 but has one extra place it crashes.

The errors/logs are server side mind you. never saw the duplicate. will leave this open though for now.

**Comment by Regalis11** [comment] 2020-01-26 11:19
Duplicate of #2019. Thanks for the extra info though, this might make the issue easier to repro.

**Closed by Regalis11** 2020-01-26 11:19 UTC
