### ISSUE TITLE
Explosives crushes server

### ISSUE THREAD

**Issue by MatiP911** [Regalis11/Barotrauma#9745] opened 2022-08-22 14:23 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While playing with my friend, in cave we stumbled upon dozens enemies. We tried to lure them into explosive, that we have previously placed. The thing is, that ice spike was perfect place for it. Once detonated, the server crushes. After some time i tried to reproduce result on my own, to be certain that, that bug isn't one time problem. And server crushes every time. I saw another closed issue with the same problem, but no info how to recreate. And hardly anyone checks comments on closed issued. So i created new one. #9542
![SharedScreenshot](https://user-images.githubusercontent.com/64082311/185943731-5cee6d0a-acb7-46ef-81e9-1f86a6fa8730.jpg)
 

### Reproduction steps

1.Start server (didn't test in singleplayer);
2.Get detonator, some explosive, wire, button, screwdriver, diving suit;
3. Swim next to some ice spike;
4. Place detonator on any kind of ice, (be sure to not let it swim away);
5. Wire it up to button;
6. Congrats, you successfully created server crushing device;

### Bug prevalence

Just once

### Version

0.18.15.1

### Which operating system did you encounter this bug on?

Windows

**Comment by NilanthAnimosus** [comment] 2022-08-22 16:38
Duplicate of #9645 which has been fixed in https://github.com/Regalis11/Barotrauma-development/commit/5c46460ffbf0f0a2e8dca34e0254b47fbbbd4cf9 (Current unstable / next version of the game).

**Closed by NilanthAnimosus** 2022-08-22 16:38 UTC
