### ISSUE TITLE
Prisoners won't get out of the cell

### ISSUE THREAD

**Issue by JerryDelsey** [Regalis11/Barotrauma#12043] opened 2023-05-21 12:14 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I had a mission in a separatist outpost : free coalition members from jail. I opened cells, but they won't climb up and get out ; they look stuck walking around the ladder

### Reproduction steps

1. Have a coalition mission to free their people from a separatist jail
2. Actually do the mission and go to the target outpost and open cells
3. The NPCs should get out and maybe trigger an alert but they won't

### Bug prevalence

Happens every now and then

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-05-21 12:32
Thank you for the report!

Did you take their handcuffs off? Bots can't climb ladders when their hands are cuffed.

**Comment by JerryDelsey** [comment] 2023-05-21 12:34
I feel so silly I didn't think someone would put anybody in jail and keeping handcuffs on them.... sorry :')

**Comment by Regalis11** [comment] 2023-05-21 12:40
>I didn't think someone would put anybody in jail and keeping handcuffs on them

That is a good point actually. :D I'm not even sure why we made them handcuffed in the first place, could be we just reused the prisoners from escort missions.

**Comment by Regalis11** [comment] 2023-05-22 17:54
Removed the handcuffs from the prisoners in https://github.com/Regalis11/Barotrauma-development/commit/79e507a14b1bd343ca13bf4dcfc5fbddcee8a3fd (commit in our private repository)

**Comment by Jasontti** [comment] 2023-06-09 13:31
Tested, but had hard time to get consistently the mission to trigger.
Most reliable way was to "unlockmission jailbreak_x" and "save & quit", then reload.
(These issues could be caused by spawning in the missions and might need more organic way to encounter them."
Coalition mission was completed succesfully, but had minor problems with pathfinding
Sootmans escape completed on level start with no input from player.
Separatists mission threw an error:
```
Could not find human prefab "prisonerseparatists" from "abandonedoutpostnpcs".
Couldn't spawn character for mission: character prefab "prisonerseparatists" not found in the NPC set "abandonedoutpostnpcs".
Couldn't spawn a human character for abandoned outpost mission: human prefab "prisonerseparatists" not found
Could not find human prefab "prisonerseparatists" from "abandonedoutpostnpcs".
Couldn't spawn character for mission: character prefab "prisonerseparatists" not found in the NPC set "abandonedoutpostnpcs".
Couldn't spawn a human character for abandoned outpost mission: human prefab "prisonerseparatists" not found
```

**Comment by Regalis11** [comment] 2023-06-10 10:50
I recommend using `triggerevent missionevent_jailbreak_coalition/missionevent_jailbreak_separatists/missionevent_jailbreak_sootman` instead. Note that these events require your reputation to be above a certain threshold (30 for the coalition/separatist jailbreak missions, 50 for the sootman one). Using `unlockmission` will unlock it in the current outpost, requires a save and reload, and may not work properly if the current location isn't suitable for the mission.

**Comment by Regalis11** [comment] 2023-06-10 10:52
Fixed the "`character prefab "prisonerseparatists" not found in the NPC set "abandonedoutpostnpcs"`" error in https://github.com/Regalis11/Barotrauma-development/commit/8573bde

**Comment by Jasontti** [comment] 2023-06-12 13:15
`Fixed the "character prefab "prisonerseparatists"` This works.

Sootman doesn't want to go for ship or follow player, goes to sit on chair.
Similar to Sootman jailbreak_separatists and coalition prisoners 
Subra follows for a while and flees when ambush arrives, but doesn't default to following when danger is gone.

Jailbreak Sootman and Rescue Subra mission saves.
[Save jailbreak sootman.zip](https://github.com/Regalis11/Barotrauma/files/11723420/Save.jailbreak.sootman.zip)

**Comment by Regalis11** [comment] 2023-06-12 14:32
There seemed to be a pretty severe issue in the Sootman event, see https://github.com/Regalis11/Barotrauma-development/pull/4296

The rest I could not repro, I think the issue was that you didn't order them the follow? We should probably make it more obvious you can do that though, you're not the first one who hasn't realized that's an option.

**Comment by Regalis11** [comment] 2023-06-29 10:13
Reopened because the bots were now able to get out of the cells on their own. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8189ebb13d40898f165c8d05f8b20d8400178f96

**Comment by Jasontti** [comment] 2023-06-30 08:04
Tested.
No issues with wiring logic or doing actual missions found.
Closing.

**Closed by Jasontti** 2023-06-30 08:04 UTC
Labels: Bug, Design
