### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by SomeRandomNoobKekeke** [Regalis11/Barotrauma#12838] opened 2023-10-19 08:50 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I was running "quickstart->main menu" many times and game slowly consumed all RAM and crashed without a report

Why? i was testing one mod, but i also was able to reproduce it without any mods

Quickstarting bigger biomes with bigger subs seems to consume RAM faster

### Reproduction steps

repeat few times 
  quickstart Berilia 100 wastesbasic
  return to main menu

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Single player

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by SomeRandomNoobKekeke** [comment] 2023-10-20 06:45
I don't know if this is helpful, but i did some memory snapshots on debug barotrauma
1 snapshot is when i just opened game
2 snapshot after 1 "quickstart Dugong 0 coldcavernsbasic"
3 snapshot after 18 more "quickstart Dugong 0 coldcavernsbasic"

[200MB too big for github](https://drive.google.com/file/d/1NuEe4Dfz_tcdZQpAfN5zdvkCjXNe-xZV/view)

**Comment by Regalis11** [comment] 2023-11-02 07:37
Potential duplicate of https://github.com/Regalis11/Barotrauma/issues/9285?

**Comment by Rokvach** [comment] 2023-11-17 10:49
Tested with the memory leak fixes and compared memory usage with and without the fixes. Also tested that the "topLeftButtonGroup" resizes correctly on resolution changes. 

Couldn't find any issues, can be merged and closed. 

With memory leak fixes
==================================

Quickstart Berilia 100 wastesbasic

1.   Main menu - 995 MB    || Round loaded - 2 117 MB
2.   Main menu - 1 674 MB || Round loaded - 2 198 MB
3.   Main menu - 1 799 MB || Round loaded - 2 261 MB
4.   Main menu - 1 850 MB || Round loaded - 2 537 MB
5.   Main menu - 1 768 MB || Round loaded - 2 490 MB
6.   Main menu - 2 039 MB || Round loaded - 2 522 MB
7.   Main menu - 2 076 MB || Round loaded - 2 168 MB
8.   Main menu - 1 914 MB || Round loaded - 2 300 MB
9.   Main menu - 1 951 MB || Round loaded - 2 636 MB
10. Main menu - 2 215 MB || Round loaded - 2 350 MB

11. Main menu - 1 968 MB || Round loaded - 2 890 MB
12. Main menu - 2 415 MB || Round loaded - 2 425 MB
13. Main menu - 2 078 MB || Round loaded - 2 378 MB
14. Main menu - 2 066 MB || Round loaded - 2 396 MB
15. Main menu - 2 056 MB || Round loaded - 2 530 MB
16. Main menu - 2 172 MB || Round loaded - 2 996 MB
17. Main menu - 2 428 MB || Round loaded - 2 788 MB
18. Main menu - 2 375 MB || Round loaded - 2 924 MB
19. Main menu - 2 421 MB || Round loaded - 2 650 MB
20. Main menu - 2 604 MB || Round loaded - 2 707 MB

Without memory leak fixes
==================================

Quickstart Berilia 100 wastesbasic

1.   Main menu - 1 029 MB || Round loaded - 2 135 MB
2.   Main menu - 1 840 MB || Round loaded - 2 556 MB
3.   Main menu - 2 245 MB || Round loaded - 2 808 MB
4.   Main menu - 2 518 MB || Round loaded - 2 970 MB
5.   Main menu - 3 107 MB || Round loaded - 3 794 MB
6.   Main menu - 3 471 MB || Round loaded - 4 278 MB
7.   Main menu - 4 218 MB || Round loaded - 4 565 MB
8.   Main menu - 4 501 MB || Round loaded - 5 184 MB
9.   Main menu - 5 160 MB || Round loaded - 5 518 MB
10. Main menu - 5 541 MB || Round loaded - 5 562 MB

11. Main menu - 5 585 MB || Round loaded - 6 130 MB
12. Main menu - 6 054 MB || Round loaded - 6 231 MB
13. Main menu - 6 258 MB || Round loaded - 7 038 MB
14. Main menu - 6 951 MB || Round loaded - 6 963 MB
15. Main menu - 7 000 MB || Round loaded - 7 663 MB
16. Main menu - 7 610 MB || Round loaded - 8 247 MB
17. Main menu - 7 605 MB || Round loaded - 8 425 MB
18. Main menu - 8 407 MB || Round loaded - 8 702 MB
19. Main menu - 8 633 MB || Round loaded - 9 216 MB
20. Main menu - 9 106 MB || Round loaded - 9 924 MB

**Closed** 2023-11-17 10:50 UTC
Labels: Code, Performance
