### ISSUE TITLE
Assistants can't take more than 4 talents in Rows 1 and 2

### ISSUE THREAD

**Issue by jaimeflores** [Regalis11/Barotrauma#13162] opened 2023-12-14 17:17 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Basically title.  We were screwing around over lunch with the new Assistant talents to try them out.  We enabled cheats so we could just give ourselves a ton of experience to pick leveling order for theorycrafting purposes.  When we tried to put in all the talents, the game would not let us put in the last points in row 1 and row 2, it would not let us--even when we had 20+ levels worth of available points.

### Reproduction steps

1.) Start a sandbox game as an Assistant.
2.) Turn on the reactor (so you don't die of running out of Oxygen 😄).
3.) Enable cheats.
4.) Use `giveexperience 400000 <name here>`
5.) Try selecting all the talents in Row 1 and Row 2 in any order.
6.) You should end up with two talents in row that cannot be activated.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Other

### -

I tested this in self-hosted Multiplayer since I only ever play Multiplayer, but I'm willing to bet it happens in all of the modes.

### Version

v1.2.6.0 (Winter Update)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-12-14 17:19
Duplicate of https://github.com/Regalis11/Barotrauma/issues/13138

We've implemented a fix for this, but it unfortunately didn't make it in time for the update. We're hoping to hotfix this soon though. Sorry for the inconvenience!

**Closed by Regalis11** 2023-12-14 17:19 UTC

**Comment by jaimeflores** [comment] 2023-12-14 17:21
Ah, that's why I couldn't find it in the list--it was already closed, and I forgot to check without the filter.  Thanks for the quick follow-up!
