### ISSUE TITLE
[Unstable] No item interaction animations in sub-editor.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#9510] opened 2022-07-02 17:23 UTC
- Build Unstable 0.18.13.0 Windows
- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

###Description
Characters don't seem to have any item animations when interacting with periscope/chair/bed in sub editor test mode.
Seems like the same symptoms as #8580 or #9097 ?

### Reproduction steps
- Load submarine with periscopes/chairs/beds
- Test mode
- Try to sit in any chairs or order a bot to man the guns
- Character will walk over to the target position, but no IK animations happen

**Comment by Regalis11** [comment] 2022-07-03 10:15
I'm afraid I couldn't find a way to reproduce this. Did you notice it happening in some specific submarine, or does it seem to happen consistently everywhere?

https://user-images.githubusercontent.com/14351070/177035198-18cb48ef-32ed-44e6-8bee-eff0da0ceaca.mp4

**Comment by Ek-Videogames** [comment] 2022-07-12 00:29
@Regalis11
Here's the issue reproduced in current unstable v0.18.14.0
[ItemInteractBugSub.sub.txt](https://github.com/Regalis11/Barotrauma/files/9088392/ItemInteractBugSub.sub.txt)

**Comment by Regalis11** [comment] 2022-07-13 08:39
Still couldn't repro. :/ Are you using some kind of mods?

https://user-images.githubusercontent.com/14351070/178689911-ac4ee0e6-c848-4394-983e-234d92ddc934.mp4

**Comment by Ek-Videogames** [comment] 2022-07-13 20:25
> I was about to say fixed in build v0.18.15.0 by one of the other Inverse-Kinematics tweaks, but nope only for the specific example sub file. If I load the old file it works, but recreating the submarine again on a fresh save the issue persists.
> 
> ![image](https://user-images.githubusercontent.com/55356135/178819562-f5f2cc22-c449-47c6-a74c-bdb86c17fcf6.png)
> `(Only mod is the name of the content package the game self-generated)`
> 
> https://user-images.githubusercontent.com/55356135/178822986-f2980d6e-ab68-44c0-986b-4b25ec797803.mp4
> 
> [ItemInteractBugSub2.sub.txt](https://github.com/Regalis11/Barotrauma/files/9105512/ItemInteractBugSub2.sub.txt)

@Regalis11 
### Edit & Additional Information:
After once again loading the first 'ItemInteractBugSub' file to test - it stopped working again, however because I loaded it at two different times - I still have the "autosaved" file from when it was working, and it seems the working version works consistently while the broken one doesn't when initially loaded. 

So now I have two seemingly-identical submarine files one of which has the bug behavior still and one which doesn't. 
That means time for file comparison!!!

[ItemInteractBugSub Broke.txt](https://github.com/Regalis11/Barotrauma/files/9105723/ItemInteractBugSub.Broke.txt)
[ItemInteractBugSub Fixed.txt](https://github.com/Regalis11/Barotrauma/files/9105722/ItemInteractBugSub.Fixed.txt)

I already converted the sub files to plaintext, but if you need the encapsulated versions for any other info or testing [here is a zip with the 2 files](https://github.com/Regalis11/Barotrauma/files/9105714/ItemInteractBugSub1.differences.zip)

- **It appears the problem is - something is causing the item prefabs to be loaded without any IK targets in their `<controller/>` component. Which I did suspect might be the issue but I don't know this could happen.**
- Now, looking at older submarine files pre v0.18 - It seems like none of them contain IK targets in their `<controller/>` component either. So I'm guessing saving the whole `<controller/>` item prefab into the sub file was added recently as one of the fixes to other item animation problems, and now any items that now lack it - either because of a bug when loading prefab or because of loading in an older submarine file now the game is looking expecting them to have IK targets.
- Perhaps the `<upgrade/>` logic can be applicable here in the case of older submarine files, although something else would need to be done to solve the cases where submarines created on current-build are still lacking IK targets in the item.

**Comment by NilanthAnimosus** [comment] 2022-07-19 00:40
Tested on 0.18.15.0 using no mods.

the fixed submarine does indeed work fine, and the broken one does have no animations (you still use the item fine, but your limbs do not get positioned anywhere) - noting the UI changes:

https://i.gyazo.com/1ec76ec325b29efceb07fbb20e2cc6f5.mp4

Using "Reset to prefab" in the submarine editor fixes the issue for any item that seems to be missing this key data - but this does hold a strong question for certain version submarines as it is inherent to a submarine save file on whatever version it was possible to create this..

**Comment by Regalis11** [comment] 2023-03-10 10:42
We're cleaning up some low-prio/unreproducible/irrelevant/outdated tickets from the issue tracker, and this is one of the tickets we chose to axe. Closing.

**Closed by Regalis11** 2023-03-10 10:42 UTC
Labels: Bug, Code, Low prio
