### ISSUE TITLE
Banlist doesn't save when banning someone from a server

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#4033] opened 2020-10-08 08:35 UTC
I'm not fully sure if banning yourself has changed recently or if banning is broken

Reproduction steps:
1. Host a dedicated server
2. Join your dedicated server
3. Ban your character using `ban <name>` in the dedicated server console
4. Check bannedplayers.txt from Barotrauma/Data and notice that its empty
5. Notice that you can freely join back to the server like nothing happened on your "banned" client

**Comment by Regalis11** [comment] 2020-10-08 11:32
Could not reproduce, the banlist seems to save as expected. Banning localhost shouldn't be possible in any case, so I'm not sure if there's an issue here

**Comment by Regalis11** [comment] 2020-11-12 14:03
No known steps to repro, closing

**Closed by Regalis11** 2020-11-12 14:03 UTC
Labels: Bug, Code, Need more info
