### ISSUE TITLE
On joining a multiplayer campaign, all events (shots, explosions, sounds, deaths) that took place since the round started are dis/played

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#6259] opened 2021-07-06 13:26 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
On joining an ongoing campaign, all sounds, visual explosions, mounted sub gun shots, deaths, and probably more, that have taken place recently, should be displayed or played almost at the same time.
I couldn't find an open issue describing this bug, which is surprising, based on how common it is.
It happens on every server, modded or vanilla.
3 random examples:
https://user-images.githubusercontent.com/10529134/124606922-a79fc780-de6d-11eb-8f99-8a2088548fec.mp4
https://user-images.githubusercontent.com/10529134/124606958-b1292f80-de6d-11eb-9e26-9956a5aae91d.mp4
https://user-images.githubusercontent.com/10529134/124607037-bedeb500-de6d-11eb-81c6-5fa6c11d7989.mp4

**Steps To Reproduce**
Join a multiplayer campaign during a round, after any kind of action.

**Version**
Any since last year, including v0.14.6.0

**Additional information**
I don't recall one time when I didn't encounter this issue.

**Comment by Regalis11** [comment] 2023-03-10 12:24
We're cleaning up some low-prio/unreproducible/irrelevant/outdated tickets from the issue tracker, and this is one of the tickets we chose to axe. Since this is just a minor visual oddity, it doesn't seem important to address. It's also worth noting we've fixed the sounds playing since this ticket was created. Closing.

**Closed by Regalis11** 2023-03-10 12:24 UTC
Labels: Bug, Code
