### ISSUE TITLE
[0.9.902] Crash - Void Update(Single)

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2588] opened 2020-04-09 12:13 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Single Player Campaign - Started a Wreck Salvage mission. Crashed into this:
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/4456040/crashreport.log)

Didn't persist after the game restarted.

**Version**
0.9.902

**Comment by Regalis11** [comment] 2020-04-12 16:04
Wasn't able to reproduce this, but I added some null checks to hopefully prevent the game from crashing when this occurs https://github.com/Regalis11/Barotrauma-development/commit/3dc246c.

**Comment by Rokvach** [comment] 2020-04-12 16:31
No reported cases of this happening since 902 and we've mainly been testing the wreck salvage missions. So closing.

**Closed by Rokvach** 2020-04-12 16:31 UTC
Labels: Bug, Code, Crash
