### ISSUE TITLE
This event dialogue won't advance

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#7691] opened 2021-12-09 23:00 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![Capture](https://user-images.githubusercontent.com/5086682/145489069-6a2e4197-bb8f-4ab6-a30e-7640675b413f.PNG)

When I chose the no pay option, it wouldn't close. My team probably selected no before me too.

**Version**
0.15.19.0

**Comment by Regalis11** [comment] 2021-12-10 13:02
Couldn't repro :/
![image](https://user-images.githubusercontent.com/14351070/145578183-6618a8ee-6e94-4f8d-ba16-300b871ccfe2.png)

**Comment by Regalis11** [comment] 2022-01-12 09:55
No known steps to repro, closing

**Comment by Regalis11** [comment] 2022-01-14 07:46
Got another report about this, so I guess it wasn't just some kind of a weird one-off bug: https://github.com/regalis11/barotrauma/issues/8031

Reopening

**Comment by Kaillera** [comment] 2022-05-19 15:08
I may have found the reason for this bug. In multiplayer, it is possible for the event to fire off to two players at the same time. One of the player will get stuck with the dialogue.

**Comment by Regalis11** [comment] 2022-07-01 08:12
Possibly caused by the same issue as #9497, addressed in https://github.com/Regalis11/Barotrauma-development/commit/5a6854f0c481fd8a485f7786c30210564927081c

**Comment by NilanthAnimosus** [comment] 2022-07-26 08:40
Tested in 0.19.0.0 - Works correctly, closing.

**Closed by NilanthAnimosus** 2022-07-26 08:40 UTC
Labels: Bug, Code, Networking, Unstable
