### ISSUE TITLE
Medfabricator dialogue missing in Medical Tutorial

### ISSUE THREAD

**Issue by thymol-blue** [Regalis11/Barotrauma#11097] opened 2023-01-30 07:08 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://user-images.githubusercontent.com/53154853/215410157-e13d6427-f36b-45f8-abec-75bc3313af0a.png)

It appears that some dialogue is missing in the Medical Tutorial.

### Reproduction steps

1. Play tutorial.
2. Select the medical tutorial.
3. See missing text.

### Bug prevalence

Happens every now and then

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-01-30 08:09
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10751

**Closed by Regalis11** 2023-01-30 08:09 UTC
