### ISSUE TITLE
Can't complete mission between Topol and Adrogeos Linea

### ISSUE THREAD

**Issue by ElConradoX** [Regalis11/Barotrauma#10227] opened 2022-11-04 06:04 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://user-images.githubusercontent.com/29005543/199900844-c85542f3-fcd4-4bcd-91a3-133e89e45c05.png)

Chose to go from Topol to Adrogeos Linea in The Great Sea. There are no outposts in these areas.

Attempting to select Topol to complete the mission and clicking on Start does nothing.

We are unable to continue the campaign, as going back to the lobby forces us to restart the mission from the beginning.

### Reproduction steps

1. Play a multiplayer campaign.
2. Reach Topol in The Great Sea.
3. Select Androgeos Linea as next destination.
4. There are no other routes from Androgeos Lina except back to Topol.
5. Start the mission and reach Androgeos Linea.

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
No error messages or crashes.
```

**Comment by Regalis11** [comment] 2022-11-04 06:43
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10131

We unfortunately haven't found a way to reproduce this, but if you have this save still available, posting it in that ticket would help us a lot in diagnosing this. Thank you and sorry for the inconvenience!

**Closed by Regalis11** 2022-11-04 06:43 UTC
