### ISSUE TITLE
[Factions] Hostile faction vessels are either incredibly rare or don't spawn

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11136] opened 2023-02-02 22:14 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Throughout the entirety of Season 1 and 2 of the testing sessions, we never experienced a single hostile vessel attacking us. For the vast majority of gameplay, we were at -100 reputation for the Separatists (season 1) and the Coalition (season 2). We were never randomly attacked by either side as the code suggests we should've. 

![image](https://user-images.githubusercontent.com/105495756/216460995-81d50dff-7c78-4452-95c8-4f1cee2086ff.png)
_Figure 1. Reference in the code of these mission types existing._

### Bug prevalence

Just once

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Jade-Harleyy** [comment] 2023-02-03 08:48
Upon further testing, I was able to get an ambush missions to spawn by following these steps:
1. Create a new campaign with the 'hard' preset.
2. Enter the following commands: `enablecheats` `setreputation coalition -100` `setreputation separatists -100`.
3. Open the map and select any destination, then undock from the starting outpost.
4. Use the `freecam` command to check if there is an enemy submarine in the level.
5. If not, redock to the starting outpost and repeat steps 3 through 5.

Image of spawned Coalition submarine:
![image](https://user-images.githubusercontent.com/67431770/216552890-f07c82f1-d1c5-41cd-945b-799fb27c3593.png)

Image of the mission text and Coalition submarine on sonar:
![image](https://user-images.githubusercontent.com/67431770/216554092-d97258e8-ac48-40c9-80ca-87aa435e24ad.png)

**Comment by JeroonBosch** [comment] 2023-02-07 08:48
Temporarily set minprobability="0.5" and tested it. Spawned a hostile Separatist sub on the 2nd route I tried at a 2-passageway distance, so seems to work as intended. The route I took was between two Coalition stations though, so players may find that odd.

**Comment by Regalis11** [comment] 2023-02-07 10:45
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/efccf55fb854d03fd86a55a3fd53b3ae1e1eac39: now the attacks don't happen in connections between outposts that belong to another faction (i.e. you're safe from separatist attacks when traveling from a coalition outpost to another, or vice versa).

**Comment by JeroonBosch** [comment] 2023-02-08 13:33
Tested with minprobability="1" to ensure submarines spawning and separatist reputation of -100.
Submarine always spawned if it wasn't between coalition outposts,
Submarine never spawned if it was between coalition outposts.
Working correctly now as far as I can see. Closing, can be merged

**Closed by JeroonBosch** 2023-02-08 13:33 UTC
Labels: Bug, Code, Severe
