### ISSUE TITLE
when server rubberbands used items (i.e., shooting a gun) are not "lost"

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#10278] opened 2022-11-07 18:40 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

when rubberbands/desyncs happen, used ammo is lost even though nothing appears to happen. though maybe it's just fired in a totally different and useless direction because of stun resetting aim.

it's hard to tell since client side the ammo's just gone (no tracers for things that happened a couple seconds ago! - would making tracers linger be a good thing?)

occured infrequently over many versions of baro

### Reproduction steps

1. shoot shotgun (consumes ammo), hit target
2. server rubberband
3. target HP restored, ammo is still "lost"

### Bug prevalence

Happens every now and then

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-01-09 08:38
Caused by https://github.com/Regalis11/Barotrauma/issues/10878, closing as a duplicate

**Closed by Regalis11** 2023-01-09 08:38 UTC
Labels: Bug, Needs testing, Code, Networking
