### ISSUE TITLE
Yet another relay power bug

### ISSUE THREAD

**Issue by CRedinger** [Regalis11/Barotrauma#4609] opened 2021-01-01 08:33 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.
It may likely be related to some of the other relay issues, but I could not be certain.

**Description**
Relays seem to be pulling more power than they should.

**Steps To Reproduce**
- Wire reactor to a pair of batteries power_in.
- Wire both batteries power_out to a relay power_in.
- Wire the relay power_out to 2 oxygen generators.
- Set reactor to produce 4000 kw and batteries to 20% charge rate.
- View the unchanging battery charge, indicating 4000kw is being used by 2x 1000kw devices.

**Version**
v0.11.0.10
Windows

**Additional information**

The relay should be limiting power draw, but is instead doubling it in certain circumstances. 

I tested several wiring variations and found the following:

2x Batteries > junction box > 2x O2 generators
Works as expected. O2 gens give a load of 2000kw and batteries are drained for 2000kw. 

2x Batteries > junction box > relay > 2x O2 generators
The relay lists power as 1000kw and load as 2000kw (expected), but batteries are still drained for 2000kw.

2x Batteries > relay > 2x O2 generators
The relay lists power as 1000kw and load as 2000kw (expected), but batteries are drained for 4000kw.

**Comment by Regalis11** [comment] 2021-01-07 12:52
Duplicate of Regalis11/Barotrauma#3238

**Closed by Regalis11** 2021-01-07 12:52 UTC
Labels: Bug, Code
