### ISSUE TITLE
Option for toggling graphics...

### ISSUE THREAD

**Issue by diebaeterz** [Regalis11/Barotrauma#1878] opened 2019-11-14 04:40 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Game runs the worst when lots of water particle present especially when the water is murky and there is water current present. Already put particle and light to the 0.

**Steps To Reproduce**
Play on a map when there is no current or any particles in the water, no considerable lag is present. Play on a map with many particles in water or in water current, lags so much.
Also when the reactor powers down and up again repeatedly, the sonar lights up multiple times causing lag. Maybe add a delay before the sonar starts pinging.

**Version**
Latest version 0.9.4.0
Vanilla 0.9

**Additional information**
Minor issue only. Still playable.

**Comment by Regalis11** [comment] 2019-11-17 20:47
The sonar ping issue has been fixed for the next update (v0.9.5.0).

I'm not sure if the performance issue is actually caused by particles or currents, because the "water particles" you see everywhere in the water aren't actually particles, but a texture overlay. Every level has the same number of those texture overlays, so the "murkiness" of the water shouldn't make a difference performance-wise.

Do the performance issues happen exclusively when using the sonar, or everywhere? The extra lines that indicate water currents on the sonar could explain the performance hit, but I'm not sure how it could have an effect when not using the sonar display.

**Comment by diebaeterz** [comment] 2019-11-18 00:58
The lag happens everywhere especially in levels with water currents. With sonar on or off, the sub moving or not moving, the lag is everywhere. Could it be the water physics? I mean the current pushing the sub? Have to test is out more as I dont have any more details regarding this. Well, play it the way it is until i find the source. May as well close this.

**Comment by Regalis11** [comment] 2019-11-18 09:50
It could potentially be related to the currents, we need to do some testing and measure what exactly is causing it. But in any case, I think we can close this; the issue tracker is intended for bugs, while this is not technically bug, but a part of the continuous optimization process. Thanks for the report, we'll take a closer look into the currents!

**Closed by Regalis11** 2019-11-18 09:50 UTC
Labels: Code, Feature request, Need more info
