### ISSUE TITLE
[Unstable] Some issues with storage container-like items

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#12285] opened 2023-07-04 22:59 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

1. When switching to a sub with item transfer option enabled, storage containers, tool belts, seed bags, artifact cases etc. will get dropped in front of the cabinet instead of being placed in their dedicated storage slots:
![image](https://github.com/Regalis11/Barotrauma/assets/115734437/7f52dba2-1a0c-4fb4-947d-dc1b0816029a)
2. When sorting alphabetically, if there are storage containers, toolbelts etc. in the dedicated slots it will leave empty slots in the main storage space:

https://github.com/Regalis11/Barotrauma/assets/115734437/1496839c-3d74-46ab-a0dc-e04d92ffc4fe

### Reproduction steps

1. Switch to a different submarine with item transfer enabled with storage containers, toolbelts etc. on board
2. Click sort button in cabinet filled with some items and storage containers, toolbelts etc. in their dedicated slots

### Bug prevalence

Happens every now and then

### Version

Other

### -

v1.1.3.0

### Which operating system did you encounter this bug on?

Windows

**Comment by AdamH-Daedalic** [comment] 2023-07-24 13:19
Unable to reproduce. 
Neither of the issues above are occurring when swapping subs and transferring items, nor when sorting items in cabinates.
Closing

**Closed by AdamH-Daedalic** 2023-07-24 13:19 UTC
Labels: Bug, Code
