### ISSUE TITLE
Placing components from hand slots places the whole stack at once

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#5112] opened 2021-02-20 22:38 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Title

**Steps To Reproduce**
Have a stack of components in your inventory
Switch the stack from the inventory to one hand or both
Place down the component - the whole stack gets placed down

**Version**
v0.12.0.3 Windows 20H2

**Comment by Regalis11** [comment] 2021-02-22 09:00
Duplicate of https://github.com/Regalis11/Barotrauma/issues/4955

**Closed by Regalis11** 2021-02-22 09:00 UTC

**Comment by Krzeszny** [comment] 2021-02-22 14:15
> Duplicate of #4955

It's not the same. My report isn't about picking things up. It's about placing them down, regardless of the hand slot stack bug.

**Comment by Bertaz** [comment] 2021-02-22 18:42
> [...] Placing them from hand slots is bugged.

Fixed in [Regalis11/Barotrauma-development@3e8d25f](https://github.com/Regalis11/Barotrauma-development/commit/3e8d25f99e39f0dad1a3d4adc200f417eb4ed013) as hand slots can no longer stack items

_See https://github.com/Regalis11/Barotrauma/issues/4955#issuecomment-779124903_
