### ISSUE TITLE
[0.1000.0.0] Merchant will not remove Opium/Morphine/Fentanyl from inventory after Player sold it to them.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2923] opened 2020-05-29 23:28 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Merchant will not remove Opium/Morphine/Fentanyl from inventory after Player sold it to them.

**Version**
0.1000.0.0

**Comment by ekqvist** [comment] 2020-06-05 10:29
Seems to be working just fine now as of Regalis11/Barotrauma-development@7882dea. Probably got fixed as a side effect of some other fix.

**Comment by Rokvach** [comment] 2020-06-09 14:17
Confirmed working, closing.

**Closed by Rokvach** 2020-06-09 14:17 UTC
Labels: Bug, Code
