### ISSUE TITLE
0.18.1.0 Host freezes game when changing sound output device

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#9165] opened 2022-05-18 20:34 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I was hosting our game via client. When I changed the sound output device between speakers to headset the whole game froze for ~8 secs.

### Reproduction steps

1. While hosting a session via client: change sound output device
2. game freezes for ~8secs until the sound output device is changed

### Bug prevalence

Happens every time I play

### Version

0.18.1.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-05-19 07:14
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7981

**Closed by Regalis11** 2022-05-19 07:14 UTC
