### ISSUE TITLE
Cargo capacity shown may not reflect actual cargo capacity

### ISSUE THREAD

**Issue by Orum** [Regalis11/Barotrauma#8588] opened 2022-03-23 11:04 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When purchasing a submarine, when first switching to it, or when first loading it, the cargo capacity that is shown on the shipyard screen does not reflect the submarine's actual cargo capacity.  For example, here it is from the shipyard screen: ![shipyard screen](https://files.catbox.moe/tlyy15.webp)
However, after the sub is purchased and has been loaded at least one time previously (i.e. purchase & switch, then leave, then dock, or purchase & switch, save & quit, then save & quit again, and finally load back in), the value is shown correctly on the submarine switch terminal: ![switch terminal](https://files.catbox.moe/4mk4kd.webp)
I'm fairly certain this occurs because the entirety of the cargo capacity on this submarine is provided by the 'drone', and none of it is in the main sub.

**Steps To Reproduce**
Create a sub & drone (or modify a vanilla one) to have some cargo capacity in its drone.  Go to the shipyard screen, note its capacity, then purchase the sub.  Go to the submarine switch terminal, and note that the capacity will be the same incorrect value as what was shown on the shipyard.  Switch to the sub if you didn't already when purchasing it, then save & quit.

Load the save, and go to the submarine switch terminal again.  Note that the capacity will still show the erroneous value, as this is the first time the sub has been loaded.  Save and quit again.

Load the save again, and go to the submarine switch terminal again.  The terminal should now show the correct value.

**Version**
v0.16.7.0 Linux

**Additional information**
Though technically the cargo capacity would be accurate if the drone is lost, as the drone comes with the sub when purchased, I feel the capacity shown should reflect what the drone can carry as well.

**Comment by Regalis11** [comment] 2022-03-24 09:39
Duplicate of https://github.com/Regalis11/Barotrauma/issues/8235

**Closed by Regalis11** 2022-03-24 09:39 UTC
Labels: Bug, Code
