### ISSUE TITLE
AI characters can't reload the coilgun

### ISSUE THREAD

**Issue by DaGangsta** [Regalis11/Barotrauma#10797] opened 2022-12-22 19:04 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

So, this has happend ever since the holiday update as far as I know. The issue is really simple, AI characters can't reload the coilgun (and yes it's only the coilgun everything else works.) The AI just seem to be stuck in the periscope and aren't  reloading when there is no ammo. That's it.

### Reproduction steps

1. Start a singleplayer campaign 
2. Empty the coilgun by just shooting the coilgun until the ammo box is empty
3. Order one of the AI's to operate one of the coilguns on the ship (I use Typhon 2 but I think any sub works)
4. See if they reload it or not (They should say "Can't reload the coilgun" or something like that

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by TheMinerBoy** [comment] 2022-12-22 19:20
Just wanted to pop in and say that it doesn't happen with the Dugong or the Typhon. It is likely just an issue with the Typhon 2.

**Comment by DaGangsta** [comment] 2022-12-23 08:29
Update: The issue seems to be not only the coilguns, but the weapon slot the're in. Specifically slot 2 and slot 3, the issue is still happening when I use flak canons instead of coilguns.

**Comment by Regalis11** [comment] 2022-12-23 11:11
Potential duplicate of https://github.com/Regalis11/Barotrauma/issues/10697

**Comment by DaGangsta** [comment] 2022-12-23 14:44
Yeah I think that that is the issue now that I think about it, I was able to make it work with racks

**Comment by Regalis11** [comment] 2022-12-23 15:07
Thank you for the extra info! In that case it does seem like this is the same issue as https://github.com/Regalis11/Barotrauma/issues/10697, closing as a duplicate

**Closed by Regalis11** 2022-12-23 15:07 UTC
