### ISSUE TITLE
Lobby issue, connecting to friendly lobby ("blank" lobby screen)

### ISSUE THREAD

**Issue by JoneKone** [Regalis11/Barotrauma#5585] opened 2021-04-23 23:07 UTC
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![20210423213327_1](https://user-images.githubusercontent.com/1114115/115937392-8f402380-a4a0-11eb-8965-65ea77f21551.jpg)
All boxes are empty. The connected friends can see me in lobby but i cannot see them or hear them.
(It was trickered by host loading (Event Horizon) sub I got disconnected it didn't want to load the sub, then after reconnecting this happened.

**Steps To Reproduce**
On a ready server 4 players, load multiple ships and use new submarine large view window then the host loads a new ship (Event Horizon) get disconnected then reconnect.

**Version**
v0.13.0.11

**Additional information**
I restarted multiple times, no effect, then deleted all the submarines, the game was complaining about missing sub files and after verifying data about thirdy files where downloaded and then connecting to the server worked.  This event is not fresh on my memory while writing this issue and it is higly possible I'm remembering some parts wrong, how ever it did happen as the screenshot shows and my friends did see me in the lobby while I saw this.

(Linux) user.

**Comment by JoneKone** [comment] 2021-04-24 21:26
![20210424223016_1](https://user-images.githubusercontent.com/1114115/115973305-a3495b00-a55c-11eb-9533-cc14e2fcc388.jpg)
![20210424222931_1](https://user-images.githubusercontent.com/1114115/115973307-a47a8800-a55c-11eb-941c-96041353b54e.jpg)

It seems to happen when I get disconnected and the game tries to reconnect then I force disconnect from reconnect window. Reconnect to the server after this and pau blank screen. So player got DC'd from the server and the name list suddenly appeared.

**Comment by Regalis11** [comment] 2021-04-26 07:20
Duplicate of https://github.com/Regalis11/Barotrauma/issues/4137

**Closed by Regalis11** 2021-04-26 07:20 UTC
