### ISSUE TITLE
Instant Death Bug

### ISSUE THREAD

**Issue by Menthus123** [Regalis11/Barotrauma#1745] opened 2019-07-07 22:14 UTC
- [✓] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When starting a mission(Both "Killing a Hammerhead" and "Terminate a Swarm" are the only two I've tested so far) traveling between Hyldemoer(The starting destination) and Molovsk Habitation Outpost(The ending destination), the game assumes the crew and sub have died. In addition to that, a seemingly random error pops up before returning you to the last outpost you were at.

**Steps To Reproduce**
1. Start multiplayer server
2. Choose Dugong sub(Don't know if this issue occurs with other subs)
3. Use oMvMNBIh as the seed, just in case.
4. All other server settings are default.
5. Go to the Hyldemoer Military Outpost if you aren't already there.
6. Click on Molovsk Habitation Outpost, and choose either the "Killing a Hammerhead" or "Terminate a Swarm" mission if they're available.
7. Once you start, the game should consider the sub and crew dead, give an error, and return you to the outpost.

**Version**
I'm running version v0.9.0.7  of the game on Windows.

**Comment by Regalis11** [comment] 2019-07-12 10:49
Unfortunately I wasn't able to reproduce this. That level seed doesn't seem to generate a map with a location called "Hyldemoer Military Outpost". 

If you still happen to have the save file where this issue occurred, or if you remember what the error message was, those would help a lot in diagnosing and fixing this.

**Comment by Rokvach** [comment] 2019-07-20 22:28
This sounds really similar to the "Level equality check failed" error, where the sub loads up and the end screen pops up immediately leading the player back to lobby.

I've had it before during our testing rounds and it seemed to only happen for me in that round, rejoining the server and trying to spectate only resulted in the same behavior where it switched to the game, showed the sub leaving and end round window popping up saying that the mission has failed and you return to the lobby, while others are playing the round without any issues. 

More about it in here
https://trello.com/c/iplY0quj/198-level-equality-check-failed-errors-in-multiplayer

**Comment by Regalis11** [comment] 2019-07-25 10:13
Yeah, this could be caused by the "level equality check" problem (or some other type of networking issue). Since we don't have a way to reproduce this and don't know what the error message was, I don't think we can verify whether this has been fixed or not. Closing this for now, but if we get any more info on this we can reopen it (or mark as a duplicate if it's caused by something we already have a ticket about).

**Closed by Regalis11** 2019-07-25 10:13 UTC
Labels: Bug, Code, High prio, Need more info
