### ISSUE TITLE
Interaction Interface issue

### ISSUE THREAD

**Issue by SGT-Shorty** [Regalis11/Barotrauma#10368] opened 2022-11-13 02:27 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Interacting with an object by talking or touching (Watching a captain look at the map, you can choose to remove the revolver or help him out) 
It constantly loops until you say one of the 'Bye' options. 
completing trees didn't stop it, as I could keep opening the strange crate on my ship as much as I liked, and it would keep rolling for what came out of it without fail.
It seems that any interaction that ended in a result would loop it back to a part of the conversation, and you could try it again, or stop the interaction with the 'Bye' option.

### Reproduction steps

1. Start a campaign with random events.
2. Continue through the interaction until you reach the end of it.
It should restart the interaction back to a certain portion.

### Bug prevalence

Happens every time I play

### Version

0.20.5.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-11-13 10:55
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10320

**Closed by Regalis11** 2022-11-13 10:55 UTC
