### ISSUE TITLE
Crash when trying to filter mission/sandbox/campaign

### ISSUE THREAD

**Issue by cookins** [Regalis11/Barotrauma#2718] opened 2020-04-26 17:37 UTC
**Description**
Game crashed when was switching filters in lobby right on part Mission/Sandbox/Campaign. Not seems that other filters having same issue. Tried almost 10 times. 

**Steps To Reproduce**
from game menu right in server browser then switching filters and here it is.

**Version**
0.9.9.0 on Windows 10 Pro

**Additional information**
here two logs files with same crash.
[crashreport (6).log](https://github.com/Regalis11/Barotrauma/files/4536063/crashreport.6.log)
[crashreport (8).log](https://github.com/Regalis11/Barotrauma/files/4536064/crashreport.8.log)

**Comment by Regalis11** [comment] 2020-04-26 17:49
Duplicate of #2677

This happens due when trying to filter servers in the server list based on game mode. We've got a hotfix coming for this issue soon, but for now it should be possible to work around it by not trying to filter the server list. Sorry for the trouble!

**Closed by Regalis11** 2020-04-26 17:49 UTC
