### ISSUE TITLE
0.10.2.0: Bizzare error dump when picking up metal crate

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#3293] opened 2020-07-03 21:57 UTC
The metal crate does not appear to contain anything but i get console output whenever someone tries to pick it up. It would briefly appear in someone's inventory, the error would dump, and then it would be back on the ground where it started. Think the metal crate might originate from an outpost but unsure what the crew bought.

![2020-07-03-164837_482x185_scrot](https://user-images.githubusercontent.com/47284081/86498987-31462200-bd4e-11ea-88b0-8a5ec35860e9.png)
(repeated attempts to pick up the crate)
![2020-07-03-164954_214x290_scrot](https://user-images.githubusercontent.com/47284081/86498988-31deb880-bd4e-11ea-8d96-042920804f9f.png)

The round would later go on to [crash due to another strange issue](https://github.com/Regalis11/Barotrauma/issues/3294).

**Comment by Regalis11** [comment] 2020-11-09 18:59
I'm pretty sure this was a case of entity IDs getting mixed up: the log file in #3294 seems to imply that as well (trying to read an update for a ruin decal, which there should be no updates for). 

Since there's no reliable way to reproduce this specific error, and since there's been so many fixes to these ID issues (maybe most importantly the readonly IDs introduced in the latest unstable), I think we can close this and keep an eye out for any new ID mismatch errors.

**Closed by Regalis11** 2020-11-09 18:59 UTC
Labels: Bug, Code, Networking
