### ISSUE TITLE
Crash/close after start.

### ISSUE THREAD

**Issue by camer5** [Regalis11/Barotrauma#13197] opened 2023-12-19 01:35 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

So i start the game from steam or files in administrator and after the intro things then it gets to loading fully loads then if i press nothing or even if i do it closes/crashes. the reason i put that it may just close is because whenever i look through the files or anything i cannot find a crash log anywhere. im on windows 10 ryzen 7 3000 ish 64bit 32gb of ram and a 3070 on its newest graphics driver update and i have deleted the game uninstalled the mods deleted all the folders including the mod folder and the game folder itself and done folder validating and nothing seems to work. it just seems to say nah after a while? i am also on newest update too. oh and its downloaded on d drive if that matters.

### Reproduction steps

start game in anyway

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens outside single player or multiplayer game modes (e.g. game launches on startup, something broken in the main menu)

### Version

v1.2.6.0 (Winter Update)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
i cant find any to post them?
```

**Comment by Udsahn** [comment] 2023-12-19 01:42
Sounds like the same exact thing that happened to me once the update rolled out. Does it freeze a bit before the crash to you like it does me? (The mouse is input is completely unresponsive before the crash)

Might be similar to #13173.

Try to see if it does this when not connected to the internet or with steam in offline mode. I know multiplayer features will be disabled, but this was the only way I found to prevent it from crashing on me after the update.

**Comment by Regalis11** [comment] 2023-12-19 08:19
Seems to be a duplicate of https://github.com/Regalis11/Barotrauma/issues/13173.

We still haven't been able to diagnose this, but there are some suggestions for things you could try in the ticket (and if you give those a try and let us know whether it helped, it would also be very valuable to us in diagnosing the issue). Thank you and sorry for the inconvenience!

**Closed by Regalis11** 2023-12-19 08:19 UTC

**Comment by camer5** [comment] 2023-12-19 18:55
> Sounds like the same exact thing that happened to me once the update rolled out. Does it freeze a bit before the crash to you like it does me? (The mouse is input is completely unresponsive before the crash)
> 
> Might be similar to #13173.
> 
> Try to see if it does this when not connected to the internet or with steam in offline mode. I know multiplayer features will be disabled, but this was the only way I found to prevent it from crashing on me after the update.

it does freeze a tad like maybe like a second but unlike your post on the bug thing it does this litterally every time i cannot start the game basically i have managed to get to the main menu once or twice but even then after like a milisecond it dies. i will try and disconnect myself from my internet and se if this does anything
