### ISSUE TITLE
WiFi / chat length different SP / MP

### ISSUE THREAD

**Issue by ralfbiedert** [Regalis11/Barotrauma#3659] opened 2020-08-29 15:00 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When designing and running a sub in the editor or SP the effective WiFi / chat length is different than in MP:

**WiFi component sending message in editor / SP:**
![xx](https://user-images.githubusercontent.com/301288/91639675-92216c00-ea18-11ea-8db4-3b4e568c2a4c.png)

**WiFi component sending same message in MP:**
![yy](https://user-images.githubusercontent.com/301288/91639677-9483c600-ea18-11ea-9225-9b19af46a019.png)

**Steps To Reproduce**
- Have WiFi component that sends long message on channel 1
- Alternatively, use attached sub, type ".ice" in SP vs MP

[Elysium VI.i.sub.zip](https://github.com/Regalis11/Barotrauma/files/5145377/Elysium.VI.i.sub.zip)

**Version**
0.10.4.0

**Additional information**
-

**Comment by Regalis11** [comment] 2020-09-28 12:38
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/cefb8ad0ea33d8146f6212347c64a3085c510cd8

**Comment by Rokvach** [comment] 2020-10-02 09:37
I wasn't able to test this as the WiFi component didn't respond to the .ice message in the test sub. Moving back to todo as there might be something wrong with the WiFi component.

**Comment by ralfbiedert** [comment] 2020-10-02 13:48
Interesting. Maybe it's because the sub was created before WiFi channels landed? I think the default is `0` now, while previously it was `1`, which is what the components of that revision are listening on.

**Comment by Regalis11** [comment] 2020-10-05 09:21
@Rokvach there's a switch below the terminal that you need to press for the signals to go through. You also need to make sure your headset is set to channel 1.

**Comment by Rokvach** [comment] 2020-10-05 09:51
Thanks! I tried to look for a switch on my first test run and clicked couple I found but seems I missed that one.

1. Should the terminal text also be the same length as the new chat max length? 
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/21ccb6af-92f6-4020-9211-371cd516ff46)

2. Also chat message length seems to be shorter now in singleplayer, I assume this is intentional?
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/06f4c68e-2aed-4074-95f7-f47625a2123a)

3. I'm unable to get the message to show up in multiplayer when I have the switch on and I'm on channel 1. Tested in singleplayer prior and it did work there. 

4. In multiplayer, if I type .ice in the terminal it shows the message twice and after that no matter how many times I type .ice it doesn't show the message anymore
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/116757ad-560f-4809-bd7a-59ff7d0c448e)

**Comment by Regalis11** [comment] 2020-10-05 11:33
1. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/77b77f0cf52aa4707bd5380fb9564f6a4ed55ac9
2. This happens because the maximum length of the memory component's output is now shorter (200 characters).
3. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c4e4d53

**Comment by Rokvach** [comment] 2020-10-05 12:53
Tested, everything else works correctly except #4. Moving back to Todo.

**Comment by Regalis11** [comment] 2023-03-10 13:15
We're cleaning up some low-prio/unreproducible/irrelevant/outdated tickets from the issue tracker, and this is one of the tickets we chose to axe. The only remaining issue here seems to be a weird edge case relating to a complex circuit, one which we haven't gotten any other reports about.

**Closed by Regalis11** 2023-03-10 13:15 UTC
Labels: Bug, Code, Low prio
