### ISSUE TITLE
Sub Editor - Assembly wiring isn't aligned to the parts properly

### ISSUE THREAD

**Issue by BeardyMike** [Regalis11/Barotrauma#13256] opened 2024-01-03 22:48 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

https://github.com/Regalis11/Barotrauma/assets/42244545/05cb551e-2fc6-4f2d-817e-2df90eda8c0d

https://github.com/Regalis11/Barotrauma/assets/42244545/60e338e5-b679-4b9f-a3f3-449dd705f4b1

When making an Assembly in the sub editor, then placing that new assembly, the wiring isn't being placed properly. it shifted way off in the wrong direction.

### Reproduction steps

place a few wire-able items, 
wire them together with a few extra wire "nodes", 
make an assembly from them. 
place the new assembly.

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Single player

### Version

v1.2.7.0 (Winter Update hotfix)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2024-01-04 08:07
Duplicate of https://github.com/Regalis11/Barotrauma/issues/13216

**Closed by Regalis11** 2024-01-04 08:07 UTC
