### ISSUE TITLE
Bots shooting in random directions at an enemy in a cave

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#7369] opened 2021-11-18 15:47 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Multiplayer - Dedicated Server

So we were entering a cave to mine some Uranium for a mission. We had a bot with a SMG followed us. There was a ice block between us and the Spineling. Once the bot entered it's range where it would detect and shoot at the Spineling, the bot would just randomly fire it's smg at random directions, hitting players too.

After that, I decided to test the problem again and spawn a spineling, but this time with clear line of sight to the enemy, the bot is still firing at random directions until the spineling got closer to it, and then it will shoot directly at it.

**Version**
0.,15.15.0

**Comment by itchyOwl** [comment] 2021-11-24 09:00
Seems to be multiplayer only issue

**Comment by itchyOwl** [comment] 2021-11-24 09:18
The type of enemy doesn't matter, but it's possible that the issue is somehow related to the ice blocks or caves in general.

**Comment by NilanthAnimosus** [comment] 2022-06-28 08:21
Been testing this on version 0.18.12.0, replicated it somewhat but with erratic/50% of the time results - I spawn spinelings which dart around a lot and keep a distance on seed mhaDpYjx using Azimuth with a dedicated server on nest mission mode which generates a cave with decent geometry.

I outfitted some AI, godmoded the lot and had them follow the human player, freecammed and teleported them inside to begin testing, I found sometimes corpses would perhaps trigger this as well as the creatures darting around level geometry as if for X time without a clear shot but initially having a good aim, they will continue to fire in erattic directions, perhaps the direction they are simply facing at the time.

![image](https://user-images.githubusercontent.com/29177976/176130216-e2b9d8aa-8111-4c2c-9cee-4771b1c71273.png)

Larger view of that area:

![image](https://user-images.githubusercontent.com/29177976/176130423-787f7b58-c26b-454f-a3e4-4b125e9c8b9c.png)


The above images is one such case of this, a spineling has darted around the ice and the AI continued shooting in an erratic direction. clearly they do not have line of sight and this is the only spineling alive in the area from all my other spawns while I tried to capture an image of this.

**Comment by NilanthAnimosus** [comment] 2022-06-28 09:18
Further debugging has revealed when the AI is shooting without a clear target - The shoot input is set via AIObjectiveGoTo in UseScooter - the AI is suppost to have a scooter and if not return, but then it is set while they have an SMG active, implying this order is done before the AIObjectiveCombat order changes the weapon to an SMG perhaps, though im not sure if the orders can work like this it would explain a lot if they are attempting to travel (They are on follow orders then lose sight of the target) with an SMG in their hands.

**Comment by itchyOwl** [comment] 2022-07-20 09:39
Nice digging! Did you manage to repro it in single player or is it mp only?

**Comment by NilanthAnimosus** [comment] 2022-07-20 11:03
I can't recall but I believe for AI issues I generally test in single player as I am not sure how well the debugai information is accurate to a clients perspective, and figure they generally should mimic the same behavior between the two. I'm sure there are probably multiplayer-specific issues that exist  but I would check for those after failing to find them in single player.

so although I cannot be 100% certain now, I definitely believe this was tested in single player back then.

**Comment by Regalis11** [comment] 2022-10-25 11:52
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2edfb25b9b866e60d5e9a18327b46d3cb0419bf7

**Comment by NilanthAnimosus** [comment] 2022-10-26 08:51
Tested against bugfixes commit https://github.com/Regalis11/Barotrauma-development/commit/e176d08351da8d12043ea5020c9227d120dd502b, no issues found, closing.

**Closed by NilanthAnimosus** 2022-10-26 08:51 UTC
Labels: Bug, Code, Networking
