### ISSUE TITLE
Tab menu duplicates and offsets, and loses all functionality.

### ISSUE THREAD

**Issue by SeaverBeaver** [Regalis11/Barotrauma#9043] opened 2022-05-02 16:53 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Whenever a player joins a server, leaves a server, spawns in, and upon docking/undocking and level transitions, the Tab menu breaks and loses all of its functionality. This happens in vanilla games,and seems to only happen to the host, but may happen to the other players when one of the things mentioned above happens. This is particularly problematic when docking at an outpost, as the host cannot access the wallet or transfer money. The Tab menu seems to fix itself after an indeterminate amount of time, roughly 5 minutes.

**Steps To Reproduce**
Host a server, have another player join.
Dock at an outpost, open the tab menu and try to interact with it.

**Version**
Release Build, (Urban Expanses Hotfix)

**Additional information**
https://user-images.githubusercontent.com/95244788/166290070-d121bc7d-8ca2-41ca-9f05-c44f5920201d.PNG
[https://user-images.githubusercontent.com/95244788/166290070-d121bc7d-8ca2-41ca-9f05-c44f5920201d.PNG](url)
(2 links in case Github decides to not.)

**Comment by Regalis11** [comment] 2022-05-03 09:54
Duplicate of https://github.com/Regalis11/Barotrauma/issues/2961

This report gave me some more clues on what could be causing this, more details in the older ticket

**Closed by Regalis11** 2022-05-03 09:54 UTC
Labels: Bug, Code
