### ISSUE TITLE
NPC Crewmembers equipping o2 gear unessescarily

### ISSUE THREAD

**Issue by KingkumaArt** [Regalis11/Barotrauma#6853] opened 2021-10-08 00:15 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
NPC crewmembers, especially on large subs, tend to equip o2 gear if the air quality reaches a certain (est. 50%) threshold, and never takes them off, using up all the o2 tanks on the sub quite quickly. In addition, if the o2 gen  malfuncions, the entire crew puts one one, even if it could be easily fixed by the mechanic doing his job. This can get very annoying once you've aquired oxygenite tanks. Suggested fixes (in case lowering the threshold is a bad idea) are to make "clean-up" duty npcs refill low or empty o2 tanks. In addition, having an option to restrict NPC crew from using oxygenite tanks and wasting them would also be rather useful, even if this bug gets fixed.

**Steps To Reproduce**
Equip a large submarine (berila or kastrull should probably suffice) and hire a good few crew. Wait a while.

**Version**
Steam Stable

**Additional information**
The one NPC who tends to do this by far the most often has the "Crazy" trait, I'm not sure if that has anything to do about it or not. In addition, it seems highly mobile crew such as mechanics and electricians are by far the worst offenders, possibly indicating a cause of this triggering when they enter a room with already low o2 quality.

**Comment by Regalis11** [comment] 2021-10-11 18:52
Thank you for the report!

I'm afraid I couldn't reproduce this though. The threshold when the bots equip diving gear is 30%, and based on a quick test, it seems to be working correctly. They also take their masks off when the oxygen level goes back above 40%. This may be a tad much on the cautious side since you don't need a mask at 30% yet, but we've found that it's better to make the bots a bit too cautious than careless: there can be situations where dropping down to 30% means it won't take long until everyone starts to suffocate.

I wonder if in your situation the oxygen level happened to be permanently somewhere between 30%-40%, which would explain why the bots opt to always wear a mask or suit. If that's the case, you may have a bit too large crew for the submarine, and might want to reduce the size or purchase some upgrades for the oxygen generator.

**Comment by Regalis11** [comment] 2021-11-19 09:11
No known steps to repro, closing

**Closed by Regalis11** 2021-11-19 09:11 UTC
Labels: Bug, Need more info, Code
