### ISSUE TITLE
Thalamus Crashes Single Player Game

### ISSUE THREAD

**Issue by WampusWarder** [Regalis11/Barotrauma#3958] opened 2020-09-30 21:44 UTC
[crashreport (3).log](https://github.com/Regalis11/Barotrauma/files/5308333/crashreport.3.log)
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/5308334/crashreport.2.log)
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/5308335/crashreport.log)

- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The bug is a crash in single player I am going to a outpost with no missions active. In my path is a Thalamus. I am in a Dugong so my ship is very weak so it gets destroyed but after awhile the game crashes. It's never at the start of the engagement but it seems to trigger more when I am being hit by the red terminal cell but I'm not sure. Also I have crewmembers that are doing things but once the ship is breached they go to get a diving suit. I'm not sure if the tasks have anything to do with it.

**Steps To Reproduce**
Find a Thalamus in a Dugong
Try to fight it with crewmates on both guns and one on reactor
See if getting hit by a lot of cells is what causes it

**Version**
0.10.5.1 (ReleaseWindows, branch release, revision 9e259b2148)

**Additional information**
I'm pretty sure its not clients side, my graphics card doesn't stress at all, it's single player, and I have no mods installed. Anyway I'm really enjoying the game keep doing what you do best and I will support it. :)

**Comment by Regalis11** [comment] 2020-10-01 06:22
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3896

**Closed by Regalis11** 2020-10-01 06:22 UTC
Labels: Bug, Code, Crash, Duplicate
