### ISSUE TITLE
Audio Output Device Can't Be Changed

### ISSUE THREAD

**Issue by Patrick228** [Regalis11/Barotrauma#1752] opened 2019-07-12 02:53 UTC
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Changing audio device via system menu or audio drivers has no impact on the audio device used by the game. Unplugging the audio device used by the game (and leaving another plugged in) results in no audio, even after the initial device is re-plugged.

**Version**
0.9.1.0 Windows 10

**Comment by rico6822** [comment] 2019-07-24 16:32
Could adding into options menu option to search for audio devices solve partially this issue by not having to restart the game?

**Comment by juanjp600** [comment] 2020-06-16 15:38
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/fe0c6a8e3409cd345a3b902734e2e3d71b18a7a9

**Comment by Rokvach** [comment] 2020-06-22 04:41
Works without any issues with a USB headset and headphones which plugs in with the audio jack. 

If you re-plug the USB headset in to the PC while the game is running you will have to re-select the device in order for it to recognize it. This can't be done if you only have a single audio device plugged in to the PC as you can't re-select it as there's no other option to switch audio to, so this still forces the player to restart the game. 

Removing a audio device from the PC while the game is running still keeps the audio device selected rather than revert to another device which is available on the PC, this is however a good decision as you wouldn't want the game to switch to your speakers in the middle of the night when you accidentally unplug your headset. But I feel like there needs to be a "None" option to address this issue as well as the other issue I mentioned earlier. 

@juanjp600

**Comment by juanjp600** [comment] 2020-06-22 14:22
First two problems should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/85a454cbf714be3dd9d7723b1efafdef56e9e466, https://github.com/Regalis11/Barotrauma-development/commit/8e7cc1ffc9f5b355cbb86584e810fe0b2e470a63 and https://github.com/Regalis11/Barotrauma-development/commit/eccc0e964482d7b5bc1d84aa6279061d65b8b668. I haven't been able to replicate the third problem, but I suspect it's also been addressed.

**Comment by Rokvach** [comment] 2020-06-23 03:35
Wasn't able to reproduce the crash either so seems to be fixed as well. 

Is it possible to detect a device that has been plugged while the game is running without having to re-open the settings? 

Other than that there wasn't any new issues, so this can be merged.

**Comment by Rokvach** [comment] 2020-06-23 11:20
We can always add the feature in later if it causes some confusion, closing the ticket as all the major issues has been fixed and is working correctly.

**Closed by Rokvach** 2020-06-23 11:20 UTC
Labels: Bug, Code
