### ISSUE TITLE
Barotrauma crash après plusieurs minutes/heures

### ISSUE THREAD

**Issue by Cakanr** [Regalis11/Barotrauma#6092] opened 2021-06-17 03:47 UTC
Bonjour/Bonsoir

- Description
 Après une séance de jeu allant de d'un dizaine de minutes à quelque heures, le jeu crash, et à plus de chance de crash avec un retour window, et après le crash si je vérifie il me dis que 3 fichiers sont manquant et me les re-valide à chaque fois, mais sans la vérification des fichiers je peux quand même jouer.

- Steps To Reproduce
Aucune idée, ça surviens plus souvent pendant un retour window ou pendant le changement de niveau mais parfois sans raison particulière en plein jeu.

- Version
v0.13.3.11
- Additional information
Pas de contenu additionnel venant du workshop.
Crash report : 
 Barotrauma Client crash report (generated on 17/06/2021 00:20:44)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

1E784E57B83E4AD2C454A781377E1373

Game version 0.13.3.11 (ReleaseWindows, branch release, revision 7096536cf1)
Graphics mode: 1920x1080 (Fullscreen)
VSync ON
Language: French
Selected content packages: Vanilla 0.9
Level seed: Thasus Linea
Loaded submarine: Dugong (59C50CCD94815DA2FB80166B2E0B6962)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)

System info:
    Operating system: Microsoft Windows NT 10.0.19042.0 64 bit
    GPU name: NVIDIA GeForce GTX 960M
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,7777778}
    GPU status: Normal

Exception: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: L’instance de périphérique GPU a été suspendue. Utilisez GetDeviceRemovedReason pour déterminer l’action appropriée.
 (SharpDX.SharpDXException)
Device removed reason: HRESULT = 0x887A0006
Target site: Void CheckError()
Stack trace: 
   at SharpDX.Result.CheckError()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 1017
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 511
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59

Last debug messages:
[17/06/2021 00:09:35] EagleGold
[17/06/2021 00:09:35] Homeopathie
[17/06/2021 00:09:33] Task count: 0
[17/06/2021 00:09:30] Generating an outpost for the start of the level... (Location: Thasus Linea, level type: Outpost)
[17/06/2021 00:09:19] EagleGold
[17/06/2021 00:09:19] Homeopathie
[16/06/2021 23:49:50] EagleGold
[16/06/2021 23:49:50] Homeopathie
[16/06/2021 23:49:46] Task count: 0
[16/06/2021 23:49:42] Generating an outpost for the end of the level... (Location: Topol, level type: LocationConnection)
[16/06/2021 23:49:30] EagleGold
[16/06/2021 23:49:30] Homeopathie
[16/06/2021 23:48:52] EagleGold
[16/06/2021 23:48:52] Homeopathie
[16/06/2021 23:48:46] Task count: 0
[16/06/2021 23:48:41] Generating an outpost for the end of the level... (Location: Station Seosu, level type: LocationConnection)
[16/06/2021 23:48:27] EagleGold
[16/06/2021 23:48:27] Homeopathie
[16/06/2021 23:48:26] WARNING: Could not determine reputation change for faction "Enfants du saint patron des clowns" (faction was not present at the start of the round).
[16/06/2021 23:48:26] WARNING: Could not determine reputation change for faction "L'Église de la Nouvelle Enveloppe" (faction was not present at the start of the round).
[16/06/2021 23:48:26] WARNING: Could not determine reputation change for faction "Séparatistes joviens" (faction was not present at the start of the round).
[16/06/2021 23:48:26] WARNING: Could not determine reputation change for faction "Coalition d'Europe" (faction was not present at the start of the round).
[16/06/2021 23:14:48] EagleGold
[16/06/2021 23:14:48] Homeopathie
[16/06/2021 23:14:41] Task count: 0
[16/06/2021 23:13:05] OpenAL Soft on Microphone sur casque (Arctis 7 Chat) 52
[16/06/2021 23:12:54] OpenAL Soft on Microphone sur casque (Arctis 7 Chat) 52
[16/06/2021 23:12:51] Lobby created!
[16/06/2021 23:11:41] OpenAL Soft on Microphone sur casque (Arctis 7 Chat) 52
[16/06/2021 23:11:30] (Msg) SDR RelayNetworkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[16/06/2021 23:11:30] (Msg) Ping location: ams=17+1,lhr=24+2/22+1,fra=22+2,par=30+3/28+1,vie=35+3/33+1,sto=37+3/37+1,sto2=37+3/37+1,waw=40+4/38+1,mad=41+4,iad=103+10/104+1,sgp=169+16/170+16,gru=230+23/247+1
[16/06/2021 23:11:30] (Msg) Ping measurement completed
[16/06/2021 23:11:30] (Debug) Destroying relay 'sof#4 (139.45.193.10:27018)' because initial_ping_timeout
[16/06/2021 23:11:30] (Debug) Destroying relay 'eat#21 (155.133.235.18:27035)' because initial_ping_timeout
[16/06/2021 23:11:28] (Verbose) Communications with routing cluster 'syd' established.
[16/06/2021 23:11:27] (Debug) Destroying relay 'syd#90 (103.10.125.154:27050)' because initial_ping_timeout
[16/06/2021 23:11:27] (Debug) Destroying relay 'sof#3 (139.45.193.10:27017)' because initial_ping_timeout
[16/06/2021 23:11:27] (Debug) Destroying relay 'eat#45 (155.133.235.34:27021)' because initial_ping_timeout
[16/06/2021 23:11:25] (Verbose) Communications with routing cluster 'tyo' established.
[16/06/2021 23:11:25] (Verbose) Communications with routing cluster 'tyo1' established.
[16/06/2021 23:11:25] (Warning) SteamNetworkingSockets lock held for 6.0ms.  (Performance warning.)  ServiceThread,RecvUDPPacket(x2)
This is usually a symptom of a general performance problem such as thread starvation.
[16/06/2021 23:11:25] (Verbose) Communications with routing cluster 'sgp' established.
[16/06/2021 23:11:25] (Verbose) Communications with routing cluster 'sea' established.
[16/06/2021 23:11:25] (Verbose) Communications with routing cluster 'scl' established.
[16/06/2021 23:11:25] (Verbose) Communications with routing cluster 'lim' established.
[16/06/2021 23:11:25] (Verbose) Communications with routing cluster 'maa' established.
[16/06/2021 23:11:25] (Verbose) Communications with routing cluster 'jnb' established.
[16/06/2021 23:11:25] (Verbose) Communications with routing cluster 'eze' established.
[16/06/2021 23:11:25] (Verbose) Communications with routing cluster 'lax' established.
[16/06/2021 23:11:25] (Verbose) Communications with routing cluster 'sto2' established.
[16/06/2021 23:11:25] (Verbose) Communications with routing cluster 'waw' established.
[16/06/2021 23:11:25] (Verbose) Communications with routing cluster 'vie' established.
[16/06/2021 23:11:25] (Verbose) Communications with routing cluster 'sto' established.
[16/06/2021 23:11:25] (Verbose) Communications with routing cluster 'gru' established.
[16/06/2021 23:11:25] (Verbose) Communications with routing cluster 'ord' established.
[16/06/2021 23:11:25] (Verbose) Communications with routing cluster 'hkg' established.
[16/06/2021 23:11:25] (Verbose) Communications with routing cluster 'iad' established.
[16/06/2021 23:11:25] (Verbose) Communications with routing cluster 'dxb' established.
[16/06/2021 23:11:25] (Verbose) Communications with routing cluster 'mad' established.
[16/06/2021 23:11:25] (Verbose) Communications with routing cluster 'dfw' established.
[16/06/2021 23:11:25] (Verbose) Communications with routing cluster 'bom' established.
[16/06/2021 23:11:25] (Verbose) Communications with routing cluster 'par' established.
[16/06/2021 23:11:25] (Verbose) Communications with routing cluster 'lhr' established.
[16/06/2021 23:11:25] (Verbose) Communications with routing cluster 'atl' established.
[16/06/2021 23:11:25] (Verbose) Communications with routing cluster 'fra' established.
[16/06/2021 23:11:25] (Verbose) Communications with routing cluster 'ams' established.
[16/06/2021 23:11:25] (Msg) SDR RelayNetworkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[16/06/2021 23:11:25] (Msg) Performing ping measurement
[16/06/2021 23:11:25] (Msg) Got SDR network config.  Loaded revision 319 OK
[16/06/2021 23:11:15] Attempting to open ALC device "OpenAL Soft on Casque pour téléphone (Arctis 7 Chat)"
[16/06/2021 23:11:14] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[16/06/2021 23:11:13] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[16/06/2021 23:11:12] Logged in as Homeopathie (SteamID STEAM_1:1:125562676)

**Comment by ekqvist** [comment] 2021-06-17 07:28
Duplicate of #1833

**Closed by ekqvist** 2021-06-17 07:28 UTC

**Comment by Cakanr** [comment] 2021-06-17 17:46
Okay, merci, et désolé je suis assez mauvais pour trouvé ce que je cherche dans les bug report généralement, merci et bien à vous :)

**Comment by ekqvist** [comment] 2021-06-17 20:08
No problem. Thanks for reporting it anyway!

**Comment by Cakanr** [comment] 2021-06-18 01:36
Salut, j'ai toujours le problème, même après avoir MàJ les drivers :/
