### ISSUE TITLE
[0.9.903] Updating Published Item > Failed to update Workshop item on game restart

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2595] opened 2020-04-09 19:20 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When updating a published item and restarting the game:
![](https://cdn.discordapp.com/attachments/668819422919524352/697884909590675486/Capture.PNG)
![](https://cdn.discordapp.com/attachments/668819422919524352/697885445194907809/Capture.PNG)

I don't think it should stay red from then on?

**Version**
0.9.903

**Comment by Regalis11** [comment] 2020-04-12 16:13
This is not exactly a duplicate of #2570, but since it's related to the same issue and mentioned in that ticket, I think we can close this one and keep the old one

**Closed by Regalis11** 2020-04-12 16:13 UTC
Labels: Bug, Code
