### ISSUE TITLE
[Unstable 0.10.1.0] Missions ending at 'Natural formation' cannot proceed to destination

### ISSUE THREAD

**Issue by josephrdean** [Regalis11/Barotrauma#3276] opened 2020-07-02 23:58 UTC
- [Yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you accept a mission whose target location is 'Natural formation,' you will not be able to progress via the campaign map once you reach that location. The button to 'Enter {area name}' will appear, you can see the campaign map, but when you select a new destination the list of available missions (which is always none) will only briefly appear on the MouseUp event. This prevents you from selecting a new destination and you are forced to return to the station you departed from.

**Steps To Reproduce**
Reach a station, accept a mission at a location 'Natural formation'
Complete the mission objective
Move to the target destination and attempt to select a new destination. You will not be able to.
You are forced to return to your origin to complete the mission

**Version**
Windows 0.10.1.0

**Additional information**
You can sort of 'work around this' by intentionally selecting 'No mission' when moving to such a destination on the new campaign map if you're forced to traverse through such a node.

**Comment by Regalis11** [comment] 2020-07-03 08:38
I'm afraid I wasn't able to reproduce this in either single player or multiplayer campaign.

**Comment by Rokvach** [comment] 2020-07-03 09:56
I haven't been able to reproduce this either, I've tested this with all of the mission types and on each I have successfully entered the natural formation after completing the objectives and selected the next destination.

**Comment by Rokvach** [comment] 2020-07-03 23:31
Players who does not have permissions to use the enter location button can't enter inhabited locations but they can however enter outposts as anyone can dock the sub. I believe this report was a cause of the user not having the correct permissions and that there might of not been a player active at the time who did have the permissions to do it.

**Comment by Rokvach** [comment] 2020-07-05 09:16
Closing as I believe this was caused by human error

**Closed by Rokvach** 2020-07-05 09:16 UTC
Labels: Bug, Code
