### ISSUE TITLE
Purchased supplies are not delivered to submarine in multiplayer

### ISSUE THREAD

**Issue by A2ur3** [Regalis11/Barotrauma#12541] opened 2023-08-22 08:02 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Expected behavior: All purchased supplies will be delivered to my submarine when leave an outpost
Actual behavior: Only part of supplies even no supplies are delivered
The submarine has correct spawnpoint for cargo.
This situation happens frequently which makes the game almost unplayable.

### Reproduction steps

Not sure how to reproduce it, but we highly doubt it is caused by multiple players purchasing supplies from merchants.
Sometimes server log shows that one player purchase something twice even though they did not.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by gynther** [comment] 2023-08-22 08:34
This has happened to us as well, but not as often as to be totally crippling. but its definately happening.

**Comment by NilanthAnimosus** [comment] 2023-08-22 08:55
Thanks for the report!

Is there any extra information regarding this? Perhaps mods used (IE. are you using lua for barotrauma?) or a general idea of the types of supplies you may have tried to purchase, if multiple players were doing purchasing perhaps. Any rough guesses might be helpful here as I think we've had this possibly reported before but couldn't reproduce the issue.

**Comment by A2ur3** [comment] 2023-08-22 13:00
> Thanks for the report!
> 
> Is there any extra information regarding this? Perhaps mods used (IE. are you using lua for barotrauma?) or a general idea of the types of supplies you may have tried to purchase, if multiple players were doing purchasing perhaps. Any rough guesses might be helpful here as I think we've had this possibly reported before but couldn't reproduce the issue.

server is heavy modded. We use lua for barotrauma, cs for barotrauma, performance fix, neurotrauma, item io framework etc
I don't think the types of supplies is relevant to the bug. According today's server log, I purchased medical officer's outfit x1 and medical starter crate x3 then another player purchased FPGA circuit x1. At last none of them were delivered.
I also notice some strange phenomenon at shop interface: sometimes it flickers like doing a refresh and sometimes if I want to change how many one supply I'd like to buy, the number will change back.
![20230822205648](https://github.com/Regalis11/Barotrauma/assets/64390906/248edf5e-537a-4f13-8f97-07ea561734a2)
![20230822205655](https://github.com/Regalis11/Barotrauma/assets/64390906/d770bf29-f6f3-4d2d-9eeb-ee18e8e11ad1)
Here's a strange picture where rickrick142 purchase something x0 for 0 mark

**Comment by A2ur3** [comment] 2023-08-24 13:32
> Hm, been thinking what could be the cause here. Is it possible we could get your save and even better if its copied during the round it occurs on? Perhaps a modlist too in as zip?
> 
> I've tried a number of things without encountering any issues so far, but if I could get similar conditions to what you were doing it could reveal a few things potentially as it appears the server is indeed receiving the purchases you intended, but your not getting some or all of the items.

I am not the host, but I will try to let him back up the save before next time it happens. We had this problem happened again today, but sadly we didn't do a backup and the second time we bought something all supplies were delivered

**Comment by Clossaloak** [comment] 2023-09-29 06:40
It's affecting me too but it can be fixed/caused by restarting the mission. I'm in version 1.0.21.0 and unmodded.

**Comment by BlackMoons** [comment] 2023-09-29 22:34
Having same problem randomly. Using dedicated server, LUA, multiplayer crew manager, dynamic europa and a few other mods.

Only 1 person is buying supplies as others don't even have a salary. Might be other people adding items to the purchasers list however.

Not confirmed, but I feel like when I went back to the station that didn't deliver all the supplies, bought stuff and left, that I got some of my missing supplies delivered with the 2nd batch?

Seems to happen most often when buying insane number of supplies (From multiple vendors?), making it REALLY hard to notice some are missing until its too late to restart. Like 10000mk+ worth. 

Had a few other people report this bug on the barotrauma discord as well.

**Comment by Regalis11** [comment] 2023-10-09 19:14
Potentially addressed in https://github.com/Regalis11/Barotrauma-development/pull/4496 (PR in our private repo)

**Comment by BlackMoons** [comment] 2023-10-09 19:46
BTW, I can confirm that sometimes the game will put your supply's into 'cargo mission' crates (And onboard NPC's like an escort mission make comments about you removing those mission crates from shelfs). I believe the supplies then get deleted with the crates if you don't take them out before end of round.

**Comment by A2ur3** [comment] 2023-10-10 18:23
![QQ图片20231011022308](https://github.com/Regalis11/Barotrauma/assets/64390906/91dc85a4-ee8f-40cb-af66-062db059112a)
![QQ图片20231011022313](https://github.com/Regalis11/Barotrauma/assets/64390906/614e682d-f0a4-46c0-ba3a-7be2be673a06)
WHY?

**Comment by NilanthAnimosus** [comment] 2023-10-18 13:38
Tested against Release/traitor-update commit https://github.com/Regalis11/Barotrauma-development/commit/f774a4eba80f567f9852f23991ce87b92bb8a3c9

Confirmed to be an issue where purchased supplies can end up in cargo crates, I've definitely confirmed it occuring where theres more cargo crates attempted than a submarines storage allows (Though it could be in general)

another note - its known that one can potentially cancel a store purchase and refund the money, which I think is being looked into (Or might be fixed, but I don't personally recall).

To repro:

[Store Test 2.zip](https://github.com/Regalis11/Barotrauma/files/13027365/Store.Test.2.zip)

Load the save above or (Which is the same as the save above which is at step 4):

1. Fresh MP campaign with barsuk (Max 4 crates)
2. Unlock cargo missions, I used cargomeditems and cargomedemergency on the same location and choose that location
3. Purchase all medical items (Both medical and generic stores for this)
4. Start next mission and check the cargo, a lot of it will for some reason be in the crates on the crate shelf instead of the floor crates.

**Comment by Regalis11** [comment] 2023-10-18 14:38
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/950653843ccf0c05ccc21d95bf3c522afc3a59f6

**Comment by A2ur3** [comment] 2023-10-18 14:56
I do not think purchased supplies are delivered into cargo crates. We bought many things and in my memory there is even no hint  indicating cargo have been delivered.

**Comment by Jasontti** [comment] 2023-10-31 08:12
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4560/commits/950653843ccf0c05ccc21d95bf3c522afc3a59f6

Used steps provided by Nilanth.
Tested with most of the cargo missions and different purchasable items.
Also tested in single player campaign.

No issues found
Closing ticket

**Closed by Jasontti** 2023-10-31 08:12 UTC
Labels: Bug, Code, Networking
