### ISSUE TITLE
Upgrading Diving Suits with an Oxygen Tank in the Suit to be Upgraded Destroys the Tank

### ISSUE THREAD

**Issue by gerakis** [Regalis11/Barotrauma#7580] opened 2021-12-02 17:16 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When using a diving suit or a combat suit as a crafting ingredient, if the suit has a tank inside it already, the tank will disappear on completion of the new suit. It does not drop on the floor or go into the new suit. The new suit will have no tank inside it.

**Steps To Reproduce**
Make a combat diving suit, slipsuit or an abyss suit using a diving suit or combat diving suit that has an oxygen tank inside it. Upon completion of the new suit the oxygen tank will vanish from existence.

**Version**
v0.15.13.0 Windows 10 x64

**Additional information**
This was on the Humpback submarine in singleplayer if it matters.

**Comment by Regalis11** [comment] 2021-12-02 17:35
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7219

**Closed by Regalis11** 2021-12-02 17:35 UTC
