### ISSUE TITLE
Recycled Fuel Not Stacking When Made

### ISSUE THREAD

**Issue by Minukelsus** [Regalis11/Barotrauma#7116] opened 2021-11-01 10:39 UTC
- [Y] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I'm on the Remora -Deep Diving Class. I was the Captain when I tried this out. Not sure if that's worth mentioning. I was recycling a fuel rod but noticed the rods wouldn't stack. They just disappeared. They didn't transport into the crate I was carrying, onto my character or onto the floor.

**How to Replicate**
Put a bunch of Empty Fuel Rod and Uranium into the input slot. Select "Fuel Rod (Recycle). Once crafted it turns into a "Fuel Rod - Good Quality". Do not remove once made. Now make another "Fuel Rod (Recycle)" Once made, the resources will be used up but no new fuel rod will be made. It won't be stacked onto the existing, crafted fuel rod, it won't be in your inventory, a crate you're carrying or onto your character that has empty slots in the toolbelt or the toolbelt your character wears.

**What Update and OS I'm Using**
This is in the "Among The Ancients" update.
Running on Windows 10

**Additional information**
Once crafting a recycled fuel rod of good quality, you must remove them one by one so you can stack them on one another in your inventory or container which seems safe to do. Never tested it with the "Thorium Fuel Rod (Recycle)" but I'm going to assume it would do the same thing.

**Comment by Regalis11** [comment] 2021-11-03 13:38
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7014

**Closed by Regalis11** 2021-11-03 13:38 UTC
Labels: Bug, Code
