### ISSUE TITLE
Tutorial message pops up repeatedly

### ISSUE THREAD

**Issue by feli0605** [Regalis11/Barotrauma#11571] opened 2023-03-17 03:14 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

During the mechanics tutorial, it gives me the message "aquire the wrench" over and over

### Reproduction steps

1. Start mechanics tutorial
2. during the first wrench repair, fail once and get lacerated
3. continue as normally
4. when you get to the aquire a wrench part, it should show up repeatedly

### Bug prevalence

Just once

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment] 2023-03-28 10:59
Thanks for the report! I'm a bit confused about the prevalence: does it happen every time or just occasionally/once? Is there any way to make it happen? If not, it can be difficult to fix.

**Comment by feli0605** [comment] 2023-03-28 11:01
im not sure :/ can you send me back my report so i can read it again? its
been a while since i made it

**Comment by Regalis11** [comment] 2023-03-30 11:16
@feli0605 Here's a link to the issue report https://github.com/regalis11/barotrauma/issues/11571

I gave this a test, but unfortunately couldn't reproduce the issue. The tutorial seems to continue with no issues after getting electrocuted. I'm also not quite sure what you mean by "acquire a wrench part" - there isn't a part in the mechanic tutorial where you need to acquire a wrench (you already spawn with one, and need to equip it in order to repair the pump).

**Comment by Regalis11** [comment] 2023-04-18 09:42
Fixed in https://github.com/Regalis11/Barotrauma-development/pull/4128

**Closed by Regalis11** 2023-04-18 09:42 UTC
Labels: Bug, Code
