### ISSUE TITLE
Error loading a new round on an unmodded server.

### ISSUE THREAD

**Issue by GamePlayer-PL** [Regalis11/Barotrauma#6148] opened 2021-06-22 16:24 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The error/bug happened on unmodded public server when loading a new round. Every player (without host) get disconnected by this error.

**Version**
Game version: 0.14.6.0 | Platform: Linux

**Additional information - Error code**
```
Unauthorized multithreaded access to RandSync.Server
   at System.Environment.get_StackTrace()
   at Barotrauma.Rand.CheckRandThreadSafety(RandSync sync) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Utils/Rand.cs:line 47
   at Barotrauma.Rand.Range(Single minimum, Single maximum, RandSync sync) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Utils/Rand.cs:line 56
   at Barotrauma.PirateMission.GetRandomDifficultyModifiedElement(XElement parentElement, Single levelDifficulty, Single randomnessModifier) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Events/Missions/PirateMission.cs:line 142
   at Barotrauma.PirateMission.SetDifficulty(Single difficulty) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Events/Missions/PirateMission.cs:line 102
   at Barotrauma.PirateMission..ctor(MissionPrefab prefab, Location[] locations, Submarine sub) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Events/Missions/PirateMission.cs:line 90
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Barotrauma.MissionPrefab.Instantiate(Location[] locations, Submarine sub) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Events/Missions/MissionPrefab.cs:line 381
   at Barotrauma.Location.InstantiateLoadedMissions(Map map) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Map/Map/Location.cs:line 621
   at Barotrauma.Map.LoadState(XElement element, Boolean showNotifications) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Map/Map/Map.cs:line 1102
   at Barotrauma.MultiPlayerCampaign.Load(XElement element) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameSession/GameModes/MultiPlayerCampaign.cs:line 146
   at Barotrauma.MultiPlayerCampaign.LoadState(String filePath) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GameSession/GameModes/MultiPlayerCampaign.cs:line 907
   at Barotrauma.Networking.GameClient.OnFileReceived(FileTransferIn transfer) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Networking/GameClient.cs:line 2626
   at Barotrauma.Networking.FileReceiver.ReadMessage(IReadMessage inc) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Networking/FileTransfer/FileReceiver.cs:line 379
   at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Networking/GameClient.cs:line 944
   at Barotrauma.Networking.SteamP2PClientPeer.Update(Single deltaTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Networking/Primitives/Peers/SteamP2PClientPeer.cs:line 243
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Networking/GameClient.cs:line 632
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 986
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/SDL/SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 59
```

**Comment by Regalis11** [comment] 2021-07-06 10:58
Duplicate of https://github.com/Regalis11/Barotrauma/issues/6184

**Closed by Regalis11** 2021-07-06 10:58 UTC
Labels: Bug, Code
