### ISSUE TITLE
Server crashes after players kill a thalamus brain with a plasma cutter and diving knives.

### ISSUE THREAD

**Issue by CMihaiR** [Regalis11/Barotrauma#12503] opened 2023-08-15 12:21 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The multiplayer server crashed after 2 players killed a thalamus brain using a plasma cutter and a diving knife, respectively. All users were immediately disconnected from the server, and the message "The server has been shut down" appeared. The server was running barotrauma Unstable V1.1.7.0 and no mods, server - side nor client side. 
The biome this happened in is the Europan Ridge. The missions for the round were "Killing a hammerhead matriarch" and "Crawler Nest". The submarine that was used was a Dugong. The Thalamus wreck was a selkie shuttle wreck.

### Reproduction steps

1. Start up a multiplayer server.
2. Have 2+ people join said server.
3. Start a campaign and select "Dugong".
4. Progress to the Europan Ridge.
5. Encounter a Thalamus.
6. Kill the Thalamus brain using a Plasma Cutter and/or a diving knife.
7. Observe as the server crashes.

Please note that the game is still running in order after the server crashes.

### Bug prevalence

Just once

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

Other

### -

Unstable V1.1.7.0

### Which operating system did you encounter this bug on?

Windows

**Comment by CMihaiR** [comment] 2023-08-15 15:45
Hello and thanks for the quick reply. There would be no inconvenience in sending the crash report your way, but i did not find it after a quick look in the game's files. Where might the crash report be saved?

**Comment by CMihaiR** [comment] 2023-08-17 10:40
Hello, I have returned, unfortunately, my friend (and myself, through sharescreen) looked through his Barotrauma folder, and there was no crash report to be found, server or otherwise. The console also does not display any error messages when the server is booted back up after the incident.

**Comment by Regalis11** [comment] 2023-08-21 12:10
I think I may have run into this myself, and created a new ticket about the issue (not realizing this older one is most likely the same bug). Closing as a duplicate of https://github.com/Regalis11/Barotrauma/issues/12536

**Closed by Regalis11** 2023-08-21 12:10 UTC
