### ISSUE TITLE
Issues with leaving a sub behind

### ISSUE THREAD

**Issue by ekqvist** [Regalis11/Barotrauma#3330] opened 2020-07-09 10:24 UTC
**Description**
There are issues with the prompts regarding leaving subs behind sometimes missing and other times appearing incorrectly. There are also issues with the player being unable to replace the subs they have left behind in specific circumstances.

**Steps To Reproduce**
1. Start a singleplayer campaign with a submarine that has a shuttle attached, e.g. the Remora
2. Leave the starting outpost
3. Undock the shuttle
4. Dock back to the starting outpost with the main submarine
5. **Notice** that there is no prompt for leaving a sub behind
6. Go to the Sub Upgrade NPC and open the repairs tab
7. **Notice** that the option for replacing lost shuttles is disabled
8. Leave the outpost again
9. **Notice** that you now get the prompt for leaving subs behind
10. Dock back to the starting outpost with the main submarine
11. **Notice** that there is no prompt again for leaving a sub behind
12. Go to the Sub Upgrade NPC and open the repairs tab again
13. **Notice** that the option for replacing lost shuttles is now available
14. Pay the NPC to replace the shuttles
15. Leave the outpost again
16. **Notice** that you still get the prompt for leaving subs behind

After this, you correctly won't get prompts anymore for leaving the outpost.

**Version**
0.10.3.0
Windows

**Additional information**
You are able to replace missing shuttles at the end outpost of the level immediately after docking for the first time, but not at the start outpost. However, I believe that the same prompt issues prompt still remain. I did not test this behavior in multiplayer.

**Comment by ekqvist** [comment] 2020-07-10 14:19
It seems that the root cause of this is that the shuttle is positioned incorrectly in the outpost level if it's undocked from the main sub but close enough to the location the player is entering that it's not considered to be left behind.

1. Leave the outpost
2. Undock the shuttle right after loading into the next level
3. Redock to the outpost
4. Use the main sub's nav terminal to find the shuttle located far away from the main sub

The shuttle cannot be replaced because it wasn't considered to be left behind. You will also get the prompt for leaving subs behind because the shuttle is now far enough from the main sub.

**Comment by ekqvist** [comment] 2020-07-14 10:52
The issues were a bit different than what I initially thought so I'll detail them below with steps to reproduce the specific issues.

---

You would get no prompt for leaving subs behind when entering an outpost. This should be fixed in Regalis11/Barotrauma-development@79e2da0.

Steps to repro:
1. Start a campaign with the Remora.
2. Leave the starting outpost.
3. Power up the main sub, undock the drone, and navigate it to at least 50 meters away from the sub for it to be considered 'left behind' when re-entering the outpost.
4. Dock back to the outpost to see that you get a confimation prompt for entering the outpost but there is no mention for leaving a sub behind.

Note that the docking prompt was disabled for the end outpost in Regalis11/Barotrauma-development@c6e3d19 for Regalis11/Barotrauma-development#2103. So, this fix likely still needs to be redone for docking to the end outpost in the `dev` branch.

---

Subs that were supposed to be 'left behind' were incorrectly loaded into the next level. This should be fixed in Regalis11/Barotrauma-development@de6d5aa.

This happened because the subs are loaded in before the next level is initialized and therefore the level seed check in LinkedSubmarine.Load() would return true, as the seed for the level where the sub was left was still compared to the previous level instead of the next one.

Steps to repro:
1. Start a campaign with the Remora.
2. Leave the starting outpost.
3. Power up the main sub, undock the drone, and navigate it to at least 50 meters away from the sub for it to be considered 'left behind' when re-entering the outpost.
4. Dock back to the outpost.
5. Access the nav terminal to see that the linked sub is loaded in, but positioned far away from the sub.
6. Try to leave the starting outpost again to see that you will get the 'leaving sub behind' prompt after hitting 'Start'.

---

Subs undocked from the main sub but close enough to the location the player is entering/leaving to not be considered as 'left behind' were place incorrectly in the next level. This should be fixed in Regalis11/Barotrauma-development@3f89797.

This happened because the subs are first loaded in and positioned. Then the level itself is initialized. Then the main sub and subs connected to it are placed at the start of the level. However, the undocked subs were not repositioned correctly to retain their relative position to the main sub.

Steps to repro:
1. Start a campaign with the Remora.
2. Leave the starting outpost.
3. Power up the main sub and undock the drone but don't move it so it stays close to the main sub.
4. Dock back to the outpost.
5. Access the nav terminal to see that the drone is loaded in, but positioned far away from the sub.
6. Try to leave the starting outpost again to see that you will get the 'leaving sub behind' prompt after hitting 'Start'.

**Comment by Rokvach** [comment] 2020-09-21 06:44
Seems like this caused some level equality check failed errors in multiplayer (Already mentioned on QA Slack channel)

Reproduction steps
1. Host server
2. Select Remora and start a campaign round
3. In outpost level undock the Remora drone and move it downwards a bit, needs to be quite far from the sub so its considered left behind
4. Press button to leave the outpost, select destination and start a new round

You will receive a level equality check failed each time you try to launch the campaign save

**Comment by Rokvach** [comment] 2020-09-21 07:39
Attached sub positioned itself inside the main sub when I didn't move it past the "gone missing" range and redocked to a outpost, once I entered the outpost the attached sub was positioned like this

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/c760dcee-0e1c-46fa-88f6-5d6358e8ad7d)

**Comment by Regalis11** [comment] 2020-09-21 08:26
1st issue fixed in https://github.com/Regalis11/Barotrauma-development/commit/bddbe98960e05983fc014505bff36cb0054e2222

**Comment by ekqvist** [comment] 2020-11-18 14:09
I tried reproducing the 2nd issue with the steps provided, but I couldn't. Not in SP or MP. I don't know if this has been fixed at some point by some other changes, or if there are additional steps needed to reproduce it. Moving back to QA.

**Comment by Rokvach** [comment] 2020-12-02 10:40
I wasn't able to reproduce the issue either now, seems like something's changed since then. Closing as this seems to be working correctly.

**Closed by Rokvach** 2020-12-02 10:40 UTC
Labels: Bug, Code
