### ISSUE TITLE
Scale="anynumber" or Size="n,n" Does not affect sprite size in <wearable>

### ISSUE THREAD

**Issue by Showdoze** [Regalis11/Barotrauma#5458] opened 2021-04-07 19:30 UTC
**Description**
In a process of making custom wearable suits/helmets/backpack found out that i have no way to manually set scale of actual |wearable| sprite size, parameter "inherittexturescale=true/false only sets the scale to a fixed size (which is not the size i need), while "scale="n" doesn't have any effect (same with size="n,n").

i'm not sure if it's a bug or wearable sprites use different parameter than "scale" or "size" to fine tune the scale

attaching screenshots for more clear picture of the issue
![Bugreport_complete](https://user-images.githubusercontent.com/74479084/113923026-b6d09400-97f0-11eb-8c7e-9facca1984b7.jpg)

**Steps To Reproduce**
Change "scale="" to any number under |wearable| |sprite scale=""| section.

**Version**
0.12.0

**Comment by Regalis11** [comment] 2021-04-12 15:51
Looks like there was no way to change the scale of the sprites: we use the "inherit" functionality pretty much exclusively in the vanilla clothes so I suppose we never needed to modify the scale so far.

Added a scale parameter in https://github.com/Regalis11/Barotrauma-development/commit/45eeb9ae5d93041dbb3b9d58618e47f4efb90ca4 (not included in the public builds yet)

**Comment by Showdoze** [comment] 2021-04-13 15:08
Thank you alot, i will see once the public version is going to be out

**Comment by Rokvach** [comment] 2021-04-13 20:03
Looks like this isn't going to be included in the next update, but should be there when we release a new Unstable build after the update goes live

**Comment by Rokvach** [comment] 2021-06-04 11:58
This can be tested in Unstable

**Comment by Udrakan** [comment] 2021-06-05 22:26
Tested, seems to work as intended.
![image](https://user-images.githubusercontent.com/59519434/120906950-da338600-c65d-11eb-98e3-e9f53ccb81fa.png)

**Comment by Rokvach** [comment] 2021-06-06 00:04
Closing.

**Closed by Rokvach** 2021-06-06 00:04 UTC
Labels: Code, Modding
