### ISSUE TITLE
Piezo crystal doesn't play a sound when exploding

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#11814] opened 2023-04-13 21:21 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Explosion sounds are under "OnUse" and never play (maybe electrical discharge sound above takes priority? idk)

![image](https://user-images.githubusercontent.com/73229309/231885496-6753d114-0670-4d3e-957a-4c09551b114f.png)

I assume they should be under "OnBroken"

### Version

v1.0.9.0

**Comment by Regalis11** [comment] 2023-04-14 07:52
Could not reproduce, the sound seems to play just fine:
![image](https://user-images.githubusercontent.com/14351070/231980513-2888530b-a5b5-4f42-b179-5d3f3482f7eb.png)

**Comment by ubertpendragon** [comment] 2023-04-14 09:38
It plays it when discharching (barely hearable as discharge coil sound overlaps) but not when destroyed

Is the explosion supposed to be played when destroyed?

**Comment by Regalis11** [comment] 2023-04-14 10:03
Ah, right, I read this a bit too hastily! I thing the explosion sounds were meant to play simultaneously with the electrical discharge sound, but I added explosion sounds to destroying the crystal now too (https://github.com/Regalis11/Barotrauma-development/commit/0b5403c41358d967122eeb11811f4c8fe21e36fd).

**Comment by ubertpendragon** [comment] 2023-04-14 10:11
sorry for being nitpicky I just thought it was oddly quiet

**Comment by Jasontti** [comment] 2023-05-31 07:37
Tested and works. Closing ticket.

**Closed by Jasontti** 2023-05-31 07:37 UTC
Labels: Bug
