### ISSUE TITLE
Engine visual AI range maxes out at 1% engine speed

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#13158] opened 2023-12-14 14:12 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Engine visual AI range scales from 1000 to 4000, but it goes to 4000 immediately if the engine force is 1%
Only when the engine is completely shut down (no power) it goes back to 1000

`    <aitarget minsightrange="1000" maxsightrange="4000" soundrange="6000" fadeouttime="5"/>`

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/46cf28ed-2a0c-4ba5-be63-99984721ba76)

### Reproduction steps

1. Pick Barsuk
2. Go forward very slowly on nav console
3. `disablecrewai` `debugdraw` `aitargets` in console
4. watch the very big AI radius of engine

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

**Comment by Regalis11** [comment] 2023-12-14 14:18
Duplicate of https://github.com/Regalis11/Barotrauma/issues/12971

**Closed by Regalis11** 2023-12-14 14:18 UTC
