### ISSUE TITLE
Modding: Game crash on Item with both PowerContainer and Body

### ISSUE THREAD

**Issue by UzricRash** [Regalis11/Barotrauma#6036] opened 2021-06-11 15:30 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If an item has physics (i.e. Body tag) and a PowerContainer tag, the game crashes on mission start.

**Steps To Reproduce**
1. Create a new item with both Body and PowerContainer tags.
2. Place the game in the world in the sub editor.
3. Click test, instant crash to desktop.

**Version**
Windows 0.13.3.11.

**Additional information**
[Crashlog.](https://pastebin.com/Y5CWF5Qw)

**Comment by Regalis11** [comment] 2021-06-15 09:18
This doesn't seem to be caused by the Body, but because the item doesn't have a ConnectionPanel component. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1a530c501b762b42f2a50ef34e99d96c824c0458

**Comment by Rokvach** [comment] 2021-06-23 06:41
Tested, working correctly. Closing.

**Closed by Rokvach** 2021-06-23 06:41 UTC
Labels: Bug, Code, Crash, Modding
