### ISSUE TITLE
[0.1002.0.0] Discharge coil scale resets when loading ship

### ISSUE THREAD

**Issue by Camper125Lv** [Regalis11/Barotrauma#3040] opened 2020-06-09 17:21 UTC
**Description**
Loading ship always resets discharge coil scale.

**Steps To Reproduce**
Load ship in game or editor with discharge coild that isn't 0.5 scaled.

**Version**
0.1002.0.0 (Windows).

**Comment by Regalis11** [comment] 2020-06-09 17:42
Duplicate of #3026

**Closed by Regalis11** 2020-06-09 17:42 UTC
