### ISSUE TITLE
Unstable - Submarine Editor - Terminals' Welcome message remains despite being cleared

### ISSUE THREAD

**Issue by Ecchi-Ki-Senpai** [Regalis11/Barotrauma#5244] opened 2021-03-14 16:02 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Terminals' Welcome message clears itself when pressing the Test submarine button. However, it stills shows up in game and cannot be deleted

**Steps To Reproduce**
See video

**Version**
v.0.1300.0.2

**Additional information**
The only workaround I know is to delete the terminal and place a new one

https://user-images.githubusercontent.com/55001203/111075308-cbee2780-84bd-11eb-92ac-97c05d978ca8.mp4

**Comment by Regalis11** [comment] 2021-03-18 09:25
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/51ddb3004d4f59cc9536a769e86ceb9b8387dc16

**Comment by misgnosia** [comment] 2021-03-23 15:22
Would also be nice to just have a clear terminal command for the f3 console, it really sucks that a few racial slurs are saved into my multilplayer campaign indelibly because of random trolls

**Comment by ubertpendragon** [comment] 2021-03-25 17:25
Reproduced as per video, first message was cleared

**Comment by Rokvach** [comment] 2021-03-26 14:10
Tested, wasn't able to reproduce in the latest Unstable build by using the same exact steps as shown in the video

**Comment by Ecchi-Ki-Senpai** [comment] 2021-03-30 17:39
Tested in v0.1300.0.4
Unable to reproduce the bug

**Comment by Rokvach** [comment] 2021-03-31 02:39
Closing

**Closed by Rokvach** 2021-03-31 02:39 UTC
Labels: Bug, Code, Need more info
