### ISSUE TITLE
[Unstable] Fall off ladder when attempting to open hatch.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#9655] opened 2022-07-28 21:57 UTC
- Build Unstable 0.19.0.0 Windows
- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### Description
In almost every submarine there are vertical ladders with hatches, it seems now there is difficulty in opening them as an input to 'interact' with the hatch to open it is now interpreted by the game as "let go of the ladder".
Possibly caused by changes to item interaction, or new default keybind behavior.

### Reproduction steps
- Ladder with hatch above.
- Begin climbing ladder.
- Try to open the hatch and your character will instead let go of the ladder.
(Holding 'up' to keep climbing the ladder will stop you from falling off immedeately, but the game still eats the input and the hatch does not open.)
- When standing on the ground below the hatch you can open it as normal.

**Comment by MaaiG** [comment] 2022-07-29 11:07
[Harbinger?](https://github.com/Regalis11/Barotrauma/discussions/7568#discussioncomment-2969491) :)

**Comment by Regalis11** [comment] 2022-08-15 13:51
I could not reproduce this. LMB (the default key to interact with hatches/doors) doesn't make you let go off the ladders. Are you using some kind of non-default keybinds by any chance?

**Comment by Regalis11** [comment] 2022-09-07 07:21
No known steps to repro, closing

**Closed by Regalis11** 2022-09-07 07:21 UTC
Labels: Bug, Need more info, Code
