### ISSUE TITLE
Sub Editor crash log

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#3347] opened 2020-07-10 16:17 UTC
**Description**
Crashed when moving O2 bottle from small O2 shelf into asset UI. Can't reproduce reliably.

**Version**
Unstable

**Additional information**
Crashlog
[crashreport (6).log](https://github.com/Regalis11/Barotrauma/files/4904237/crashreport.6.log)

**Comment by Regalis11** [comment] 2020-07-13 10:42
Could not find a way to reproduce, but I added some measures in https://github.com/Regalis11/Barotrauma-development/commit/28cb443fb9e001d9a7e417116b501345de5ec9d9 that should prevent this from crashing the game.

**Comment by Rokvach** [comment] 2020-09-09 08:51
I haven't encountered any issues while using the sub editor, nor heard any feedback from the community that they'd come across a issue with it. I will just close this ticket as it seems to be working correctly, we can re-open it if the issue resurfaces. Closing.

**Closed by Rokvach** 2020-09-09 08:51 UTC
Labels: Bug, Code, Crash, Needs testing
