### ISSUE TITLE
Linked fabricators keep pulling from cabinet

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10262] opened 2022-11-05 22:48 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When using a fabricator linked to a container, itll keep pulling twice as much material into the input, even when the proper materials are already in, cluttering it.

### Reproduction steps

1.Link a fabricator to a cabinet
2.Attempt to craft something with more than required items in the cabinet
3.Notice it pulling too much material, even when not needed (For example, a railgun shell takes 1 steel and 1 iron, when having those materials in the input though, itll take another 1 steel and iron out of the container its linked to)

### Bug prevalence

Happens every time I play

### Version

Faction test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-11-07 08:38
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10235

**Closed by Regalis11** 2022-11-07 08:38 UTC
