### ISSUE TITLE
Orca Waypoints - Bots have issues repairing/reaching items at the far end of most rooms

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2979] opened 2020-06-05 12:03 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots have issues repairing/reaching items at the far end of most rooms on the Orca. The waypoints stops before the far end, making them confused and loopy at the last waypoint possible.

**Version**
<0.1001.0

**Additional information**
Most of the vanilla sub suffers from the same problem here and there.

**Comment by itchyOwl** [comment] 2020-07-09 08:52
Fixing leaks is tricky and there are issues, but the waypoints stopping before the far end shouldn't cause issues, because the bots can continue their movement without the waypoints.

What do you mean by bots being "confused and loopy"? I'm pretty sure this issue is caused by something else than waypoints, although making the waypoint network more detailed might help the bots to navigate (it's on the todo list to test how to improve this).

**Comment by Kaillera** [comment] 2020-07-09 11:27
They would just run back and forth on the last few waypoints because there was no waypoint leading to the broken items since it was too far from the last waypoint possible

**Comment by itchyOwl** [comment] 2020-09-03 19:17
Possibly fixed in Regalis11/Barotrauma-development@45026e1. The cause for the looping was that SteeringAvoid was unnecessarily called when the character was not swimming. This happened only when the path was dirty, at the end of the paths. I didn't find anything wrong in the waypoints.

**Comment by Rokvach** [comment] 2020-09-07 10:54
Tested, didn't notice any issues.Closing.

**Closed by Rokvach** 2020-09-07 10:54 UTC
Labels: Bug, Code
