### ISSUE TITLE
Crash at start up

### ISSUE THREAD

**Issue by MattJHar** [Regalis11/Barotrauma#6759] opened 2021-09-26 19:57 UTC
Barotrauma Client crash report (generated on 26/09/2021 8:53:15 PM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

48CA930394E1A7E117E5C694DE9CAF28

Game version 0.14.9.1 (ReleaseWindows, branch release, revision df0088ca33)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9, Shipwrecks Extended, Meaningful Upgrades, [ENV] Beacons Extended
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19043.0 64 bit
    GPU name: NVIDIA GeForce RTX 2070 SUPER
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: One or more errors occurred. (Could not find a part of the path 'D:\FastSteamGames\steamapps\common\Barotrauma\Mods\Let Me Choose ! I.T.A\.copying'.) (System.AggregateException)
Target site: Void ThrowIfExceptional(Boolean)
Stack trace: 
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Barotrauma.GameMain.<>c.<Load>b__98_0(Task task) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 475
   at Barotrauma.TaskPool.<>c__DisplayClass6_0.<Add>b__0(Task t, Object obj) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\TaskPool.cs:line 60
   at Barotrauma.TaskPool.Update() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\TaskPool.cs:line 77
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 995
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59

InnerException: Could not find a part of the path 'D:\FastSteamGames\steamapps\common\Barotrauma\Mods\Let Me Choose ! I.T.A\.copying'.
Target site: Microsoft.Win32.SafeHandles.SafeFileHandle ValidateFileHandle(Microsoft.Win32.SafeHandles.SafeFileHandle)
Stack trace: 
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Barotrauma.Steam.SteamManager.CopyWorkShopItemAsync(Nullable`1 itemOrNull, ContentPackage contentPackage, String newContentPackagePath, String metaDataFilePath) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\SteamManager.cs:line 0
   at Barotrauma.Steam.SteamManager.AutoUpdateWorkshopItemsAsync() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\SteamManager.cs:line 1600
Last debug messages:
[26/09/2021 8:53:15 PM] Cannot create directory "Mods\Let Me Choose ! I.T.A": modifying the contents of this folder/using this extension is not allowed.
[26/09/2021 8:53:11 PM] Attempting to open ALC device "OpenAL Soft on Speakers (High Definition Audio Device)"
[26/09/2021 8:53:10 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[26/09/2021 8:53:10 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[26/09/2021 8:53:08 PM] Logged in as Tasty Muffin (SteamID STEAM_1:0:38704865)

**Comment by Regalis11** [comment] 2021-09-27 07:15
Duplicate of https://github.com/Regalis11/Barotrauma/issues/6691

**Closed by Regalis11** 2021-09-27 07:15 UTC
