### ISSUE TITLE
alien ruins' artifact holders always spawn empty

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#9153] opened 2022-05-16 21:42 UTC
~~Please use the other report form to report issues. This old template is only here until we've replaced the bug report links in the game.~~ shut up

**Description**
unless you have a salvage the artifact mission, every artifact holder in alien ruins will spawn empty, unsure if this is intended

i believe it would make more sense if it had an artifact in it most of the time, if not always
 and it wouldn't change the balance that much.

**Version**
v0.18.1

**Comment by Regalis11** [comment] 2022-05-17 07:36
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7233

**Closed by Regalis11** 2022-05-17 07:36 UTC
