### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Sergeypay** [Regalis11/Barotrauma#5488] opened 2021-04-09 16:56 UTC
Barotrauma Client crash report (generated on 09.04.2021 19:49:37)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

32AA46FAB36BEE9386335D0F440A6AF3

Game version 0.12.0.3 (ReleaseWindows, branch release, revision ea245a2f34)
Graphics mode: 1280x720 (Windowed)
VSync OFF
Language: Russian
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.ServerListScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19042.0 64 bit
    GPU name: NVIDIA NVS 4200M
    Display mode: {Width:1600 Height:900 Format:Color AspectRatio:1,7777778}
    GPU status: Normal

Exception: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Экземпляр устройства GPU приостановлен. Для определения соответствующего действия используйте GetDeviceRemovedReason.
 (SharpDX.SharpDXException)
Device removed reason: HRESULT = 0x887A0006
Target site: Void CheckError()
Stack trace: 
   at SharpDX.Result.CheckError()
   at Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\Texture2D.DirectX.cs:line 410
   at Microsoft.Xna.Framework.Graphics.Texture2D.PlatformSetData[T](Int32 level, T[] data, Int32 startIndex, Int32 elementCount) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\Texture2D.DirectX.cs:line 87
   at Microsoft.Xna.Framework.Graphics.Texture2D.SetData[T](T[] data) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\Texture2D.cs:line 205
   at Barotrauma.ScalableFont.DynamicRenderAtlas(GraphicsDevice gd, UInt32 character, Int32 texDims, UInt32 baseChar) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Fonts\ScalableFont.cs:line 344
   at Barotrauma.ScalableFont.MeasureString(String text, Boolean removeExtraSpacing) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Fonts\ScalableFont.cs:line 525
   at Barotrauma.ToolBox.LimitString(String str, ScalableFont font, Int32 maxWidth) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Utils\ToolBox.cs:line 213
   at Barotrauma.ServerListScreen.<>c__DisplayClass106_0.<UpdateServerInfo>b__1() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\ServerListScreen.cs:line 1853
   at Barotrauma.RectTransform.RecalculateAbsoluteSize() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\RectTransform.cs:line 489
   at Barotrauma.RectTransform.RecalculateAll(Boolean resize, Boolean scale, Boolean withChildren) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\RectTransform.cs:line 514
   at Barotrauma.GUILayoutGroup.Recalculate() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUILayoutGroup.cs:line 161
   at Barotrauma.ServerListScreen.UpdateServerInfo(ServerInfo serverInfo) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\ServerListScreen.cs:line 1977
   at Barotrauma.ServerListScreen.AddToServerList(ServerInfo serverInfo) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\ServerListScreen.cs:line 1810
   at Barotrauma.Steam.SteamManager.<>c__DisplayClass16_1.<GetServers>b__9() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\SteamManager.cs:line 345
   at Barotrauma.CrossThread.RequestExecutionOnMainThread(TaskDelegate deleg) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Utils\CrossThread.cs:line 61
   at Barotrauma.Steam.SteamManager.<>c__DisplayClass16_1.<GetServers>b__7(Task t) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\SteamManager.cs:line 346
   at Barotrauma.TaskPool.<>c__DisplayClass6_0.<Add>b__0(Task t, Object obj) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\TaskPool.cs:line 60
   at Barotrauma.TaskPool.Update() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\TaskPool.cs:line 77
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 961
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59

Last debug messages:
[09.04.2021 19:49:33] LobbyMatchList:  LobbiesMatching: 0
[09.04.2021 19:49:33] LobbyMatchList:  LobbiesMatching: 0
[09.04.2021 19:49:33] SteamAPICallCompleted:   AsyncCall: 16692521287216360042
   Callback: 510
 ParamCount: 4
[09.04.2021 19:49:32] LobbyMatchList:  LobbiesMatching: 13
[09.04.2021 19:49:32] LobbyMatchList:  LobbiesMatching: 13
[09.04.2021 19:49:32] SteamAPICallCompleted:   AsyncCall: 13133578336733012839
   Callback: 510
 ParamCount: 4
[09.04.2021 19:49:32] LobbyMatchList:  LobbiesMatching: 50
[09.04.2021 19:49:32] LobbyMatchList:  LobbiesMatching: 50
[09.04.2021 19:49:32] SteamAPICallCompleted:   AsyncCall: 6436440592579543580
   Callback: 510
 ParamCount: 4
[09.04.2021 19:49:22] LobbyMatchList:  LobbiesMatching: 0
[09.04.2021 19:49:22] LobbyMatchList:  LobbiesMatching: 0
[09.04.2021 19:49:22] SteamAPICallCompleted:   AsyncCall: 900357331907401592
   Callback: 510
 ParamCount: 4
[09.04.2021 19:49:08] LobbyMatchList:  LobbiesMatching: 12
[09.04.2021 19:49:08] LobbyMatchList:  LobbiesMatching: 12
[09.04.2021 19:49:08] SteamAPICallCompleted:   AsyncCall: 11202947412199980987
   Callback: 510
 ParamCount: 4
[09.04.2021 19:49:08] LobbyMatchList:  LobbiesMatching: 50
[09.04.2021 19:49:07] LobbyMatchList:  LobbiesMatching: 50
[09.04.2021 19:49:07] SteamAPICallCompleted:   AsyncCall: 1843276875832677410
   Callback: 510
 ParamCount: 4
[09.04.2021 19:47:16] (Msg) SDR RelayNetworkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[09.04.2021 19:47:16] (Msg) Ping location: waw=24+2,vie=39+3/35+2,fra=36+3,sof=36+3,sto=39+3,sto2=39+3,ams=48+4/43+3,par=62+6/45+3,lhr=62+6/50+3,iad=127+12/121+3,sgp=186+18/187+18,gru=267+26/265+3
[09.04.2021 19:47:16] (Msg) Ping measurement completed
[09.04.2021 19:47:14] (Verbose) Communications with routing cluster 'syd' established.
[09.04.2021 19:47:14] (Debug) Destroying relay 'syd#82 (103.10.125.154:27042)' because initial_ping_timeout
[09.04.2021 19:47:11] (Debug) Destroying relay 'syd#106 (103.10.125.154:27066)' because initial_ping_timeout
[09.04.2021 19:47:09] (Verbose) Communications with routing cluster 'tyo' established.
[09.04.2021 19:47:09] (Verbose) Communications with routing cluster 'tyo1' established.
[09.04.2021 19:47:09] (Verbose) Communications with routing cluster 'sea' established.
[09.04.2021 19:47:09] (Verbose) Communications with routing cluster 'sgp' established.
[09.04.2021 19:47:09] (Verbose) Communications with routing cluster 'scl' established.
[09.04.2021 19:47:09] (Verbose) Communications with routing cluster 'eze' established.
[09.04.2021 19:47:09] (Verbose) Communications with routing cluster 'gru' established.
[09.04.2021 19:47:09] (Verbose) Communications with routing cluster 'maa' established.
[09.04.2021 19:47:09] (Verbose) Communications with routing cluster 'lim' established.
[09.04.2021 19:47:09] (Verbose) Communications with routing cluster 'jnb' established.
[09.04.2021 19:47:09] (Verbose) Communications with routing cluster 'dxb' established.
[09.04.2021 19:47:09] (Verbose) Communications with routing cluster 'hkg' established.
[09.04.2021 19:47:09] (Verbose) Communications with routing cluster 'lax' established.
[09.04.2021 19:47:09] (Verbose) Communications with routing cluster 'eat' established.
[09.04.2021 19:47:09] (Verbose) Communications with routing cluster 'bom' established.
[09.04.2021 19:47:09] (Verbose) Communications with routing cluster 'ord' established.
[09.04.2021 19:47:09] (Verbose) Communications with routing cluster 'sto2' established.
[09.04.2021 19:47:09] (Verbose) Communications with routing cluster 'vie' established.
[09.04.2021 19:47:09] (Verbose) Communications with routing cluster 'sto' established.
[09.04.2021 19:47:09] (Verbose) Communications with routing cluster 'sof' established.
[09.04.2021 19:47:09] (Verbose) Communications with routing cluster 'waw' established.
[09.04.2021 19:47:09] (Verbose) Communications with routing cluster 'iad' established.
[09.04.2021 19:47:09] (Verbose) Communications with routing cluster 'dfw' established.
[09.04.2021 19:47:09] (Verbose) Communications with routing cluster 'atl' established.
[09.04.2021 19:47:08] (Warning) SteamNetworkingSockets lock held for 7.2ms.  (Performance warning).  ServiceThread,RecvUDPPacket
[09.04.2021 19:47:08] (Verbose) Communications with routing cluster 'ams' established.
[09.04.2021 19:47:08] (Warning) SteamNetworkingSockets lock held for 68.1ms.  (Performance warning).  ServiceThread,RecvUDPPacket(x4)
[09.04.2021 19:47:08] (Verbose) Communications with routing cluster 'par' established.
[09.04.2021 19:47:08] (Verbose) Communications with routing cluster 'mad' established.
[09.04.2021 19:47:08] (Verbose) Communications with routing cluster 'lhr' established.
[09.04.2021 19:47:08] (Verbose) Communications with routing cluster 'fra' established.
[09.04.2021 19:47:08] (Warning) SteamNetworkingSockets lock held for 833.7ms.  (Performance warning).  ServiceThread,CSDRHTTPRequest::Think,OnNetworkConfigFetchCompleted,SetNetworkConfig,OpenRawUDPSocketInternal(x10),SendUDPacket(x10)
[09.04.2021 19:47:08] (Msg) SDR RelayNetworkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[09.04.2021 19:47:08] (Msg) Performing ping measurement
[09.04.2021 19:47:08] (Msg) Got SDR network config.  Loaded revision 316 OK
[09.04.2021 19:47:07] (Warning) SteamNetworkingSockets lock held for 107.4ms.  (Performance warning).  ServiceThread,CSDRHTTPRequest::Think,OnNetworkConfigFetchCompleted,BeginFetchNetworkConfig
[09.04.2021 19:47:07] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[09.04.2021 19:44:57] Attempting to open ALC device "OpenAL Soft on Динамики (High Definition Audio Device)"
[09.04.2021 19:44:44] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[09.04.2021 19:44:43] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[09.04.2021 19:44:34] Logged in as Sergeyplay [gc] (SteamID STEAM_1:0:503140558)

What i need to do? help :)

**Comment by Regalis11** [comment] 2021-04-12 11:30
We have an existing ticket about the same issue (https://github.com/Regalis11/Barotrauma/issues/1833), so I'll close this one.

Unfortunately this is a very generic error that can happen due to a lot of reasons, and unfortunately we haven't figured out a reliable way to fix it. It can however be caused by outdated GPU drivers, and some players have been able to get rid of it by updating the drivers, so I recommend giving that a shot 1st!

**Closed by Regalis11** 2021-04-12 11:30 UTC
