### ISSUE TITLE
[Factions] Players without a headset hear players with a headset talking with the radio high-pass filter effect when they speak over the radio

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11061] opened 2023-01-28 03:38 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

A bit of a complicated title, hopefully I can clear this up!

If a player removes their headset, they shouldn't be able to hear other players on the radio. However, players who speak over the radio have a high-pass filter effect to simulate talking over a radio. This high-pass filter still plays to players who do not have their headset on if another player who IS wearing their headset is talking over the radio near the player without the headset. 

This essentially turns local chat into normal chat and radio chat into high-pass filter normal chat (for players without their headset on).

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-01-28 09:50
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10761

**Closed by Regalis11** 2023-01-28 09:50 UTC
