### ISSUE TITLE
Crash to menu: Exception thrown while reading segment EntityEvent (ID is taken)

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#11935] opened 2023-05-01 13:32 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I'm attaching two error messages.

I joined a server and besides getting lots of warnings and errors, there were 2 errors after which my game crashed to the main menu.

Mods used:
![Barotrauma_2JL1lQny5M](https://user-images.githubusercontent.com/10529134/235456370-25cccfe1-d789-40f1-9319-dbcc03db6b2e.png)
![Barotrauma_m3Pwign1aZ](https://user-images.githubusercontent.com/10529134/235456378-fc7b19f8-267b-4bbb-9cab-3b0d8ddd5ca5.png)
![Barotrauma_aa13OCxURo](https://user-images.githubusercontent.com/10529134/235456388-8da09908-cfff-4de0-bf17-9bd211209bc7.png)
![Barotrauma_Y3Qku9n4wa](https://user-images.githubusercontent.com/10529134/235456394-44fde24b-2606-4555-9b0b-955692584edf.png)
![Barotrauma_x5sRsIX6nq](https://user-images.githubusercontent.com/10529134/235456403-e31b706c-b3c9-4a5e-a451-3bc2ec634de5.png)
![Barotrauma_YJO3IoOuIe](https://user-images.githubusercontent.com/10529134/235456407-9d347705-ada1-435f-83f6-981b7248fb7e.png)

### Reproduction steps

Not tested: spawn a lot of Walker Drones from EK Armory 1.x.x.x and do something with drone beacons. The sub I joined on the second try had lots of broken Walker Drones.

### Bug prevalence

Just once

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Failed to spawn character Ekdronerallybeacon {ID 636 is taken by Ekdronerallybeacon}
   at Barotrauma.Entity..ctor(Submarine submarine, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Entity.cs:line 119
   at Barotrauma.Character..ctor(Submarine submarine, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 1237
   at Barotrauma.Character..ctor(CharacterPrefab prefab, Vector2 position, String seed, CharacterInfo characterInfo, UInt16 id, Boolean isRemotePlayer, RagdollParams ragdollParams, Boolean spawnInitialItems) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 1240
   at Barotrauma.Character.Create(CharacterPrefab prefab, Vector2 position, String seed, CharacterInfo characterInfo, UInt16 id, Boolean isRemotePlayer, Boolean hasAi, Boolean createNetworkEvent, RagdollParams ragdoll, Boolean spawnInitialItems) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 1231
   at Barotrauma.Character.ReadSpawnData(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\CharacterNetworking.cs:line 556


Error while reading a message from server. 
Exception thrown while reading segment EntityEvent at position 32.
Inner exception: ID 636 is taken by Ekdronerallybeacon
   at Barotrauma.Entity..ctor(Submarine submarine, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Entity.cs:line 119
   at Barotrauma.Character..ctor(Submarine submarine, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 1237
   at Barotrauma.Character..ctor(CharacterPrefab prefab, Vector2 position, String seed, CharacterInfo characterInfo, UInt16 id, Boolean isRemotePlayer, RagdollParams ragdollParams, Boolean spawnInitialItems) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 1240
   at Barotrauma.Character.Create(CharacterPrefab prefab, Vector2 position, String seed, CharacterInfo characterInfo, UInt16 id, Boolean isRemotePlayer, Boolean hasAi, Boolean createNetworkEvent, RagdollParams ragdoll, Boolean spawnInitialItems) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 1231
   at Barotrauma.Character.ReadSpawnData(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\CharacterNetworking.cs:line 556
   at Barotrauma.EntitySpawner.ClientEventRead(IReadMessage message, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\EntitySpawner.cs:line 13
   at Barotrauma.Networking.ClientEntityEventManager.Read(ServerNetSegment type, IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\NetEntityEvent\ClientEntityEventManager.cs:line 220
   at Barotrauma.Networking.GameClient.<>c__DisplayClass116_0.<ReadIngameUpdate>b__0(ServerNetSegment segment, IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2122
   at Barotrauma.Networking.SegmentTableReader`1.Read(IReadMessage msg, SegmentDataReader segmentDataReader, ExceptionHandler exceptionHandler) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SegmentTable.cs:line 296
```

**Comment by Regalis11** [comment] 2023-05-02 08:55
Thank you for the report!

Seeing that this is from a heavily modded game (including source code mods), it seems probable that this is an issue caused by some of the mods. I think we're going to need more clear steps to reproduce the issue. 

> I joined a server and besides getting lots of warnings and errors

These warnings and errors might also be helpful in diagnosing the issue.

**Comment by Krzeszny** [comment] 2023-05-06 15:29
> These warnings and errors might also be helpful in diagnosing the issue.

I'll keep that in mind next time.

**Comment by Regalis11** [comment] 2023-06-15 16:02
No known steps to repro, closing.

**Closed by Regalis11** 2023-06-15 16:02 UTC
Labels: Bug, Need more info, Modding
