### ISSUE TITLE
[Unstable 0.17.3.0] Performance issues in multiplayer when attacking outpost NPC's

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8577] opened 2022-03-23 00:27 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In the attached screenshot, each update spike represents a stun baton hit to a outpost NPC. The issue worsens when there's more NPC's or other players involved and can lead to the game running very choppy for a period of time.

**Steps To Reproduce**
Load up a multiplayer campaign, equip yourself with a stun baton and whack NPC's on the station

**Version**
Unstable 0.17.3.0

**Additional information**
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/2d5b0cdb-0123-4d65-b20c-0b94f3b2399f)

**Comment by Regalis11** [comment] 2022-03-25 16:23
Potentially related/duplicate: https://github.com/Regalis11/Barotrauma/issues/8264

**Comment by cshingle** [comment] 2022-03-25 22:36
I have seen this issue in stable.
What I did was enable destructible stations in the server lobby and then just put a railgun round into the station when docked. The frame rate tanks to single digits.

**Comment by Regalis11** [comment] 2022-03-26 13:04
The cause to this was pretty unexpected: attacking the NPCs causes your reputation to drop, which makes the server send a campaign state update to the clients, which would cause the upgrade store UI to refresh (even if you're not viewing it). Addressed in https://github.com/Regalis11/Barotrauma-development/commit/a29e0ccb0c8415093de62c5f57a63a79d96dd7c6, although I think this still needs further looking into: sending this much data whenever someone's reputation drops seems overkill and could most likely still cause issues especially if someone is doing continuous damage and causing the reputation to drop continuously.

**Closed** 2022-03-31 10:00 UTC
Labels: Bug, Code, Performance
