### ISSUE TITLE
Clients disconnecting while get a "magazine" style item from completing missions in multiplayer

### ISSUE THREAD

**Issue by AndyLonly** [Regalis11/Barotrauma#12103] opened 2023-05-30 13:25 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Getting kicked back to the server lists when you get a "magazine" style item from completing missions(give by talent)

The issue was reported by WartedEMS and then tested by [plastichyena](https://github.com/plastichyena) and [CC](https://github.com/Dynamiteside) to locate the exact trigger mechanism from [mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2891792017)

### Reproduction steps

1. Start Multiplayer campaign
2. Acquire a talent that can give any type of magazine aka. a container for bullets that isnt an itemcontainer from completing missions
```xml
 <CharacterAbilityPutItem itemidentifier="[any type of magazine]" amount="1"/> 
```
3. Complete a mission(Depends on talent trigger conditions,In our case it is Kill a random (not mission spawned) monster and complete a mission)
4. Disconnected

We tested it with the [Maddened Black Sea Armory](https://steamcommunity.com/sharedfiles/filedetails/?id=2891792017)

From [CC](https://github.com/Dynamiteside)
> yee tried letting it spawn smg_magazine and it crashed too so i guess its a magazine spawning
as another reference this also happens when you change the blooddonor talent from doctor from antibloodloss2 aka. bloodbag to smgmagazine

From [plastichyena](https://github.com/plastichyena)
> it shows it won't crash(actually disconnected) if I had killed nothing
but when I killed something even with console in range, it happens
https://www.youtube.com/watch?v=tJRLHmD_22g
crash itself will happen in 11:35
### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Error while reading a message from server.
Exception thrown while reading segment EntityEvent at position 32.
Inner exception: Failed to read inventory state - Barotrauma.Items.Components.IdCard in item idcard" is not an itemContainer.
   at Barotrauma.Item.ClientEventRead(IReadMessage msg, Single sending Time) in
<DEV>/Barotrauma/BarotraumaClient/ClientSource/Items/Item.cs:line 1414
   at Barotrauma.Networking.ClientEntityEventManager.Read(ServerNetSegment type, IReadMessage msg, Single sending Time) in
<DEV>/Barotrauma/BarotraumaClient/ClientSource/Networking/NetEntityEvent/ClientEntityEventManager.cs:line 220
   at Barotrauma.Networking.GameClient.<>cDisplayClass119_0.<ReadIngameUpdate>b0(ServerNetSegmont segment, IReadMessage inc) in
<DEV>/Barotrauma/BarotraumaClient/ClientSource/Networking/GameClient.cs:line 2142
   at Barotrauma.Networking.SegmentTableReader`1.Read(IReadMessage msg, SegmentDataReader segmentDataReader, ExceptionHandler exceptionHandler) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Utils/SegmentTable.cs:line 296
```

**Comment by Regalis11** [comment] 2023-06-27 12:20
Thank you for the report, and sorry for taking so long to get back to this!

I unfortunately could not reproduce the issue. I tested changing "bloodbag" to "smgmagazine" in the "Blood donor" talent, and I didn't encounter any errors - the magazine spawns normally in the character's inventory. I'm not sure if I understood the reproduction steps correctly though:

> Acquire a talent that can give any type of magazine aka. a container for bullets that isnt an itemcontainer

SMG magazine _is_ an ItemContainer (it contains bullets). Should I be using some other type of item for testing this? I couldn't find any items with the id smg_magazine, or any magazines that didn't have an ItemContainer component from the mod either.

**Comment by AndyLonly** [comment] 2023-06-27 13:13
SMG magazines should work.
In our test, we only have transport missions and used the `killmonsters` on consolo to kill monsters when we met them midway and complete the round.

Hope this will help you

**Comment by AndyLonly** [comment] 2023-07-29 18:29
If you can, please use the mod like us, and use the pilot talent identifier="deadeyebw"
I currently have to disable the talent effect 
```xml
<AbilityGroupEffect abilityeffecttype="OnAnyMissionCompleted">
   <Abilities>
      <CharacterAbilityPutItem itemidentifier="SG_ammo" amount="1"/>
   </Abilities>
</AbilityGroupEffect>
```

**Comment by NilanthAnimosus** [comment] 2023-09-04 08:58
I've given this another look and I've also been unable to reproduce the issue using the mod, and I've tried changing the itemidentifier to the SMG magazine with no luck, including trying three different game versions.

Are you using any other mods? Lua or some other factor that might be at play here? I cannot seem to reproduce this using this mod alone and a dedicated server at least.

**Comment by Regalis11** [comment] 2023-11-07 09:41
No known steps to repro, closing

**Closed by Regalis11** 2023-11-07 09:41 UTC
Labels: Bug, Need more info, Code, Networking, Modding
