### ISSUE TITLE
Bots do not unequip diving suits when they are no longer needed.

### ISSUE THREAD

**Issue by WrillWasTaken** [Regalis11/Barotrauma#7822] opened 2021-12-17 09:38 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots will equip diving suits when they are needed, but they will not take them off until they run low on oxygen, often in a station, losing the suits forever unless you take the time to collect them.

**Steps To Reproduce**
Simply play some rounds of missions or campaign, and you will likely notice bots wearing suits when not needed.
**Version**
Windows, V0.15.22.1

**Additional information**
I'm not reliably able to advance in my campaign because of this issue, I can't craft any combat or abyss suits because they will often be lost within a few rounds on a station by the bots.

**Comment by WrillWasTaken** [comment] 2021-12-17 10:09
Sorry, there was a typo, bots seemingly only equip suits when needed, but do not unequip them.

**Comment by itchyOwl** [comment] 2022-01-03 11:11
They don't unequip the suits when they are currently following an order, only when they are in idle. They used to, but IIRC that caused various issues. So I suspect it's not a bug. Let's revisit the behavior anyway and see if it can be improved.

**Comment by itchyOwl** [comment] 2022-01-14 13:47
Noticed that the bots didn't take the suits off when they were on idle and had an active objective (e.g. ordered to fix things when there's nothing to fix). Not intentional and fixed in Regalis11/Barotrauma-development@9d43d80.

**Comment by itchyOwl** [comment] 2022-02-01 09:30
The previous fix wasn't enough. The behavior should be fixed in Regalis11/Barotrauma-development@55f8fb2: The bots should take the suits off when they are no longer needed, unless they have an active order to prepare for an expedition.

**Comment by itchyOwl** [comment] 2022-02-01 09:38
Oh, and if the bots end inside an outpost regradless with wearing the suit and then drop it, the suit is not lost. It will be transported to your cargo room!

> often in a station, losing the suits forever unless you take the time to collect them.

**Comment by Rokvach** [comment] 2022-02-01 13:57
Tested, working correctly. Closing.

**Closed by Rokvach** 2022-02-01 13:57 UTC
Labels: Code, Design
