### ISSUE TITLE
Couldn't dismiss dialog, stuck on passageway 

### ISSUE THREAD

**Issue by ralfbiedert** [Regalis11/Barotrauma#11993] opened 2023-05-11 20:38 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In a MP session, when talking to the administrator about opening the first passageway I selected to not give anything. As a result the dialog got stuck:

![Screenshot_3](https://github.com/Regalis11/Barotrauma/assets/301288/0f003ea3-3bf8-4d33-a2ea-fcb32f95db83)

IIRC the dialog vanished eventually (either because I walked far away, or someone else interacted with the NPC?), but I was unable to engage in other dialogs for the rest of the round. 

In particular I tried talking to another NPC in the Husk questline on the same station. Her dialog popped up, but I was unable to give her eggs from my inventory (I could click the yellow text label in her dialog but it had no effect). Another player on my server whom I gave the eggs thereafter was able to do it.

### Reproduction steps

I only had this once so far and don't really know how to reproduce it. 

### Bug prevalence

Just once

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-05-12 07:28
Thank you for the report!

I gave this a test, but unfortunately couldn't reproduce the issue. So this probably requires some specific circumstances to occur (maybe some other event interfering with this one or smth). We'll keep an eye out for this and see if we can figure it out.

**Comment by Regalis11** [comment] 2023-05-27 10:07
No known steps to repro, closing

**Closed by Regalis11** 2023-05-27 10:07 UTC
Labels: Bug, Need more info, Design
