### ISSUE TITLE
Healing dialog consume whole stack of Anaparalyzant

### ISSUE THREAD

**Issue by LemADEC** [Regalis11/Barotrauma#7912] opened 2021-12-23 17:58 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
While inside the healing menu, clicking the Anaparalyzant icon will consume the whole stack instead of just 1 from it.

**Steps To Reproduce**
1- Paralysis effect on your character
2- Have a full stack of 8x Anaparalyzant in your inventory
3- Open the healing dialog with H key
4- Click the Anaparalyzant icon
=> only 1 should be consumed, down to 7
Practically, the whole stack is gone

**Version**
0.15.22 Windows, no mods

**Additional information**
Issue was observed twice in multiplayer campaign with only me and 3 bots in-game.
Issue couldn't be reproduced in the editor, not sure why.

**Comment by Regalis11** [comment] 2022-01-04 08:58
Thank you for the report!

I unfortunately couldn't find a way to reproduce the issue. Do you remember how exactly you were trying to apply the anaparalyzant? By double-clicking on the item in your inventory, or by clicking the "suggested treatment" icon...?

**Comment by LemADEC** [comment] 2022-01-04 22:00
I was clicking on a "suggested treatment" icon.

**Comment by Regalis11** [comment] 2022-01-20 08:03
Hmm, still no luck. :/

https://user-images.githubusercontent.com/14351070/150297626-f18e556e-8018-4094-932c-80d2ba5b0087.mp4

**Comment by LemADEC** [comment] 2022-01-20 23:00
I've never tried on another player, issue was always when trying to heal myself.  
Also, it was always under stress conditions, so I may have hold the button longer than usual which might be part of the issue?

**Comment by Regalis11** [comment] 2022-02-04 11:01
I'm sorry to say, but I still couldn't get it to happen. I guess there's the chance this was caused by some kind of a networking problem that's difficult to reproduce. :/

https://user-images.githubusercontent.com/14351070/152518075-53b06dd0-fb0f-4b89-ba34-bc1417d12d24.mp4

**Comment by Regalis11** [comment] 2022-03-15 13:23
No known steps to repro, closing

**Closed by Regalis11** 2022-03-15 13:23 UTC
Labels: Bug, Need more info, Code
