### ISSUE TITLE
[Unstable] Deconstructing stolen items in a station produces resources not marked as stolen

### ISSUE THREAD

**Issue by StruggleDuck** [Regalis11/Barotrauma#6899] opened 2021-10-12 13:28 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
when in a station, if you steal items that can be deconstructed into materials, upon deconstructing the item, the resources it will provide will be marked as not stolen. 

**Steps To Reproduce**
when at a station, steal any item that will provide materials when deconstructed, then deconstruct the item.

**Version**
It happened in the latest unstable build, but I am unsure if it also can happen in the current stable build.

**Comment by Regalis11** [comment] 2021-10-19 12:34
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/75b415ddd767c899f7cad7aafb258f67fb2d37c5

**Comment by Rokvach** [comment] 2021-11-11 15:10
Tested, working correctly. Closing.

**Comment by Next-Door-Tech** [comment] 2022-07-14 19:37
As of v0.18.15.0 (current Steam stable build on macOS Intel), this issue is (still?) occurring. I only started playing recently so IDK if it was never fixed on stable or it's recently broken again. Description and reproduction identical to the above.

**Comment by NilanthAnimosus** [comment] 2022-07-18 09:40
Tested in 0.18.15.0 - Can confirm this is an issue again. I quickly in a campaign deconstructed a screwdriver and got none-stolen iron back in the same round I stole it in (without departing or anything like that)

**Comment by Regalis11** [comment] 2022-07-18 10:22
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ff7d2f2caaf0cae19cf23ea891decd3b4f84648b

**Comment by NilanthAnimosus** [comment] 2022-07-22 04:46
Tested in 0.19.0.0 - works correctly, but see notes:

If you deconstruct a stolen item nobody saw inside an outside (in sight of people) - picking up the deconstructed output will alert everyone to stealing again (Sort of like double stealing). don't think this is a major issue but worthwhile note on the new behavior. They now just magically know the remains of an item was their item.

**Comment by Regalis11** [comment] 2022-07-22 10:20
That's basically the point of marking the deconstruction output as stolen: even though it's somewhat unrealistic that the NPCs know where the materials came from, it prevents farming money by stealing items and selling the materials back to the outpost. So seems to be working as intended, closing

**Closed by Regalis11** 2022-07-22 10:20 UTC
Labels: Code, Design, Unstable
