### ISSUE TITLE
Disconnect during campaign loading screen. Can no longer load save.

### ISSUE THREAD

**Issue by space-lizard** [Regalis11/Barotrauma#4511] opened 2020-12-13 13:01 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
While playing a singleplayer campaign, the game crashed during a loading screen after docking with an outpost.
Attempting to load the save game fails, with the console reporting the following:
![20201213123550_1](https://user-images.githubusercontent.com/75935815/102012123-6a90ae00-3d40-11eb-98b1-5ce050020ad6.png)

**Steps To Reproduce**
Unfortunately, I have no idea what combination of factors caused this to occur.
The only thing I can think of is that in docking with the destination I completed a cargo transport mission.
The campaign was entirely singleplayer
The only mods loaded were custom submarines.

**Version**
Version 0.10.0.9
Windows 10

**Additional information**
[Crash report](https://github.com/Regalis11/Barotrauma/files/5684601/crashreport.6.log)

Under the assumption that the issue may be a bug with the location, I attempted to edit the save file to place the submarine somewhere else.
However, doing so caused the game to report it could not decompress the save.
The only part of the file changed was the 'currentlocation' property of the 'map' node.

**Comment by Regalis11** [comment] 2021-01-11 07:51
Removing the crash tag, because this doesn't seem to be a crash (the game just returns to the main menu)

**Comment by Regalis11** [comment] 2021-01-13 17:35
Potential duplicate of #4581

**Comment by Rokvach** [comment] 2021-01-14 08:25
Tested the duplicate tickets about this issue and didn't spot any issues, closing this one as well.

**Closed by Rokvach** 2021-01-14 08:25 UTC
Labels: Bug, Code
