### ISSUE TITLE
Killing a Matriarch crashes the game

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#10199] opened 2022-10-31 12:40 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When a Matriarch is killed, the game crashes

### Reproduction steps

1. start a singleplayer game
2. spawn a matriarch
3. kill it via any means (experienced first with coilguns)
4. watch the game crash when it dies

### Bug prevalence

Happens every time I play

### Version

0.20.0.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 10/31/2022 23:27:22)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


CF121C94D13F01CFA90FC9F4FB013714


Game version 0.20.0.0 (UnstableWindows, branch dev, revision 69b079928e)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla
Level seed: no level loaded
Loaded submarine: Dugong (F9EBE2F02EE9EDFFB975972EEA27534B)
Selected screen: Barotrauma.GameScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce GT 1030
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void Control(Single, Barotrauma.Camera)
Stack trace: 
   at Barotrauma.Character.Control(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2083
   at Barotrauma.Character.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 3124
   at Barotrauma.AICharacter.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AICharacter.cs:line 72
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2917
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 192
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 859
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58


Last debug messages:
[10/31/2022 23:27:16] teleportsub cursor
[10/31/2022 23:27:12] teleportsub cursor
[10/31/2022 23:27:06] power
[10/31/2022 23:27:02] fixitems
[10/31/2022 23:26:52] Submarine movement locked.
[10/31/2022 23:26:52] lock
[10/31/2022 23:26:47] Enemy AI disabled
[10/31/2022 23:26:47] disableenemyai
[10/31/2022 23:26:43] Crew AI disabled
[10/31/2022 23:26:43] disablecrewai
[10/31/2022 23:26:39] spawn Hammerheadmatriarch cursor
[10/31/2022 23:26:31] freecamera
[10/31/2022 23:24:54] Attempting to open ALC device "OpenAL Soft on Speakers (Realtek High Definition Audio)"
[10/31/2022 23:24:52] Logged in as skylervyk (SteamID STEAM_1:1:219998336)
```

**Comment by Regalis11** [comment] 2022-10-31 15:47
Seems to be a duplicate of https://github.com/Regalis11/Barotrauma/issues/10171 (happened when any character with no inventory, in this case a hammerhead spawn, was present)

**Closed by Regalis11** 2022-10-31 15:47 UTC
Labels: Bug, Code, Crash
