### ISSUE TITLE
Crash grabbing a head

### ISSUE THREAD

**Issue by anarkopsykotik** [Regalis11/Barotrauma#10707] opened 2022-12-14 01:46 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

After shooting at some wreck with a flak gun, I think I blew up a corpse so hard a head glitched through the hull and entered the submarine. When I picked it up with grab, I crashed and then everyone else on the server also crashed. The mission was then stuck and we had to restart the server (it's a dedicated server).

### Reproduction steps

Blow up a corpse hard enough a head come through the hull
Pick it up
Crash

### Bug prevalence

Happens every now and then

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 12/04/2022 02:03:00)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


0DC439F0B0CA5A5A6693500952309D61


Game version 0.19.14.0 (ReleaseWindows, branch release, revision 0daf5b87bd)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla, 32x Stack, CombinableAmmoBoxes (Vanilla ONLY), oClockRadar / Sonar [Alt Appearance], Super Mining Sonar - Alternate Color, Headsight, [DS] Skilled Crew, [DS] Gather Resources Quickly, Beacons Extended, Stations from beyond, Shipwrecks Extended, Deep Sea Alcohol, Improved Husks, Merged talent trees, Standard diving dress, Apo-4A "Saber", R-278 «Dugong», DugongCustom, battery ajuster, autoReactor1, TestOrca, 11 ARC, Orca3, compact 11 ARC, autoOpeningDoor, testDoor, autoOpeningHatch
Level seed: Mehen Linea
Loaded submarine: R-278 «Dugong» [ENG] (7162FB223A9FF189794CE613C9B6A761)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)


System info:
    Operating system: Microsoft Windows NT 10.0.17763.0 64 bit
    GPU name: AMD Radeon RX 6600 XT
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void Flip()
Stack trace: 
   at Barotrauma.HumanoidAnimController.Flip() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\HumanoidAnimController.cs:line 1820
   at Barotrauma.HumanoidAnimController.DragCharacter(Character target, Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\HumanoidAnimController.cs:line 1528
   at Barotrauma.HumanoidAnimController.UpdateAnim(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\HumanoidAnimController.cs:line 381
   at Barotrauma.Character.UpdateAnimAll(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2817
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 264
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 855
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58



Barotrauma Client crash report (generated on 12/11/2022 01:37:34)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


7CB1A1D8EDB459DBB8FE6B7A40525156


Game version 0.19.14.0 (ReleaseWindows, branch master, revision c624ec6568)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla, 32x Stack, CombinableAmmoBoxes (Vanilla ONLY), oClockRadar / Sonar [Alt Appearance], Super Mining Sonar - Alternate Color, Headsight, [DS] Skilled Crew, [DS] Gather Resources Quickly, Beacons Extended, Stations from beyond, Shipwrecks Extended, Deep Sea Alcohol, Improved Husks, Merged talent trees, Standard diving dress, Apo-4A "Saber", "Sleipnir" Class Science Submarine, R-278 «Dugong», Item Drop Key, DugongCustom, battery ajuster, autoReactor1, TestOrca, 11 ARC, Orca3, compact 11 ARC, autoOpeningDoor, testDoor, autoOpeningHatch
Level seed: Borvo MensaArnthor
Loaded submarine: R-278 «Dugong» [ENG] (BB03F3F7B08FA7016A5ED1AC19D1477D)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)


System info:
    Operating system: Microsoft Windows NT 10.0.17763.0 64 bit
    GPU name: AMD Radeon RX 6600 XT
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void Flip()
Stack trace: 
   at Barotrauma.HumanoidAnimController.Flip()
   at Barotrauma.HumanoidAnimController.DragCharacter(Character target, Single deltaTime)
   at Barotrauma.HumanoidAnimController.UpdateAnim(Single deltaTime)
   at Barotrauma.Character.UpdateAnimAll(Single deltaTime)
   at Barotrauma.GameScreen.Update(Double deltaTime)
   at Barotrauma.GameMain.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args)



Barotrauma Client crash report (generated on 12/09/2022 01:04:26)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


0DC439F0B0CA5A5A6693500952309D61


Game version 0.19.14.0 (ReleaseWindows, branch release, revision 0daf5b87bd)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla, 32x Stack, CombinableAmmoBoxes (Vanilla ONLY), oClockRadar / Sonar [Alt Appearance], Super Mining Sonar - Alternate Color, Headsight, [DS] Skilled Crew, [DS] Gather Resources Quickly, Beacons Extended, Stations from beyond, Shipwrecks Extended, Deep Sea Alcohol, Improved Husks, Merged talent trees, Standard diving dress, Apo-4A "Saber", "Sleipnir" Class Science Submarine, R-278 «Dugong», DugongCustom, battery ajuster, autoReactor1, TestOrca, 11 ARC, Orca3, compact 11 ARC, autoOpeningDoor, testDoor, autoOpeningHatch
Level seed: Asterius LineaDagrun
Loaded submarine: R-278 «Dugong» [ENG] (858D8E0328338341AEB4694992FC1406)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)


System info:
    Operating system: Microsoft Windows NT 10.0.17763.0 64 bit
    GPU name: AMD Radeon RX 6600 XT
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void Flip()
Stack trace: 
   at Barotrauma.HumanoidAnimController.Flip() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\HumanoidAnimController.cs:line 1820
   at Barotrauma.HumanoidAnimController.DragCharacter(Character target, Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\HumanoidAnimController.cs:line 1528
   at Barotrauma.HumanoidAnimController.UpdateAnim(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\HumanoidAnimController.cs:line 381
   at Barotrauma.Character.UpdateAnimAll(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2817
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 264
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 855
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
```

**Comment by Regalis11** [comment] 2022-12-14 07:35
Thank you for the report!

It seems this is caused by the mod "[Headsight](https://steamcommunity.com/sharedfiles/filedetails/?id=2893794930)", which makes the head the character's main limb. Can be reproduced easily by enabling that mod, grabbing a severed head (which is not possible in the vanilla game), and making your character flip from left to right or vice versa.

Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c63cde50104e5cd242db5c11b7c46f8d5e103460

**Comment by NilanthAnimosus** [comment] 2023-01-09 13:41
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/f2a71f9b7c694ad3b5c28abf0e8d51906f87a843, no issues found, closing.

**Closed by NilanthAnimosus** 2023-01-09 13:41 UTC
Labels: Bug, Code, Crash, Modding
