### ISSUE TITLE
Crashing when pressing Tab while changing lights with a screwdriver

### ISSUE THREAD

**Issue by sxlverc** [Regalis11/Barotrauma#11591] opened 2023-03-18 20:34 UTC
Basically what it says in the Title, when someone is editing RGBA codes of lights and presses tab to switch to the next input field the game pretty much just crashes, ive attached a very short clip of it down below

https://user-images.githubusercontent.com/98109806/226137315-4ba0086d-a4be-4387-a130-727c5ef92626.mp4

**Comment by Regalis11** [comment] 2023-03-18 20:45
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11563

**Closed by Regalis11** 2023-03-18 20:45 UTC
