### ISSUE TITLE
[unstable] endoutpostmid crashes the game

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#12551] opened 2023-08-24 20:49 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Loading endoutpostmid  (the second end level) crashes the game, both in campaign and leveleditor

[crashreport (9).log](https://github.com/Regalis11/Barotrauma/files/12433210/crashreport.9.log)

[crashreport (10).log](https://github.com/Regalis11/Barotrauma/files/12433211/crashreport.10.log)

### Version

v1.1.8.0  (unstable)

**Comment by Regalis11** [comment] 2023-08-25 06:45
Could not reproduce. Steps to repro pls?

**Comment by Regalis11** [comment] 2023-08-25 07:32
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/edd44ede0dbf1add7d24d17cbc72349820a3cf2b

**Comment by Rokvach** [comment] 2023-09-04 09:43
Tested, working correctly. Can be merged and closed.

**Closed by Rokvach** 2023-09-04 09:43 UTC
Labels: Bug, Code, Crash, Severe
