### ISSUE TITLE
(Unstable audio input) when headphones are unplugged the game doesn´t reconnect it

### ISSUE THREAD

**Issue by Damjdu** [Regalis11/Barotrauma#12024] opened 2023-05-17 11:19 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I am experiencing unstable audio input on my PC with my headphones. The issue resolves itself quickly, but Barotrauma detects it and switches back to the default audio output, which is my PC speaker, and it is also not functioning properly.

It is extremely frustrating to have to go into the settings during a game and change it back. Additionally, the audio settings still indicate that my headphones are selected as the audio output, even though they are not functioning properly.

I would appreciate it if the audio output remained set for the device without Barotrauma's audio system automatically switching it to the default option.

Is there a solution, like changing a small part of the Barotrauma files?

Temporarily resolving like this:

- Going to settings
- Audio & Voice Chat.
- Change to your default output.
- Change back to Headset output.
- Apply

![For issue 2](https://github.com/Regalis11/Barotrauma/assets/88905360/cf54f909-86ed-46b9-b623-ae3c18bef6aa)
![For issue 3](https://github.com/Regalis11/Barotrauma/assets/88905360/0911083e-4eac-4475-a183-858da9cf2381)

Full log here:
![Error log Barotrauma](https://github.com/Regalis11/Barotrauma/assets/88905360/6b8460c6-6887-4ff0-be6d-aff7a8b4d7d7)

### Reproduction steps

1. Plug in an audio device (audio cable to my headphone in my case).
2. Start game.
3. Wait until you are on the main menu (optional go to some random multiplayer round).
4. Unplug your audio device.
5. Plug in again.
6. the audio device doesn´t give the sound anymore

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Playback device has been disconnected. You can select another available device in the settings.
```

**Comment by Regalis11** [comment] 2023-05-17 11:52
Duplicate of https://github.com/Regalis11/Barotrauma/issues/8796

**Closed by Regalis11** 2023-05-17 11:52 UTC
