### ISSUE TITLE
Game crashes whenever I try to control a creature (Not the first try)

### ISSUE THREAD

**Issue by MrDudeTheNetZet** [Regalis11/Barotrauma#6647] opened 2021-09-14 17:02 UTC
Barotrauma Client crash report (generated on 14.09.2021 19:49:03)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

48CA930394E1A7E117E5C694DE9CAF28

Game version 0.14.9.1 (ReleaseWindows, branch release, revision df0088ca33)
Graphics mode: 1366x768 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9, Aurora 3.5  (REMASTER), Destroyer-Class SSN Sambooni, EK Reliant Mk-V, SMS Olympus, C.S.S Palestar, Tiny baby man v0.2, EK NurseShark Mk-I, Discovery, Eel Mk2 (Stage 1), Eel Mk2 (Stage 2), Eel Mk2 (Stage 5 Prototype), Sirenia, Krigare, Barathrum, I-401, Tereshenko 204, Charon MK3
Level seed: TopolKennet Linea
Loaded submarine: Humpback (DAEF6FEB55A432979DE70BEF9958F99D)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19042.0 64 bit
    GPU name: NVIDIA GeForce GT 740M
    Display mode: {Width:1366 Height:768 Format:Color AspectRatio:1,7786459}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Barotrauma.Submarine <GetLeavingSub>g__GetLeavingSubAtEnd|85_4(System.Collections.Generic.IEnumerable`1[Barotrauma.Character])
Stack trace: 
   at Barotrauma.CampaignMode.<GetLeavingSub>g__GetLeavingSubAtEnd|85_4(IEnumerable`1 leavingPlayers) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameModes\CampaignMode.cs:line 520
   at Barotrauma.CampaignMode.GetLeavingSub() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameModes\CampaignMode.cs:line 0
   at Barotrauma.CampaignMode.GetAvailableTransition(LevelData& nextLevel, Submarine& leavingSub) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameModes\CampaignMode.cs:line 382
   at Barotrauma.CampaignMode.Draw(SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\CampaignMode.cs:line 115
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\GameScreen.cs:line 99
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 1038
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[14.09.2021 19:49:03] control charybdis
[14.09.2021 19:48:51] spawn charybdis cursor
[14.09.2021 19:44:49] freecam
[14.09.2021 19:43:46] freecam
[14.09.2021 19:42:22] kill
[14.09.2021 19:41:28] Lighting disabled
[14.09.2021 19:41:28] lights
[14.09.2021 19:41:27] freecam
[14.09.2021 19:41:24] Steam achievements have been disabled during this play session.
[14.09.2021 19:41:24] Enabled cheat commands.
[14.09.2021 19:41:24] enablecheats
[14.09.2021 19:40:02] Generating an outpost for the start of the level... (Location: Topol, level type: LocationConnection)
[14.09.2021 19:37:44] (Verbose) Communications with routing cluster 'sto2' established.
[14.09.2021 19:37:44] (Msg) SDR RelayNetworkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[14.09.2021 19:37:44] (Msg) Ping location: waw=25+2,fra=33+3,vie=53+5/34+2,sto=35+3,sto2=/35+3,ams=37+3,lhr=37+3,par=48+4/42+3,mad=60+6,iad=101+10,sgp=245+24/214+16,gru=239+23/242+11
[14.09.2021 19:37:44] (Msg) Ping measurement completed
[14.09.2021 19:37:44] (Debug) Destroying relay 'sof#2 (139.45.193.10:27016)' because initial_ping_timeout
[14.09.2021 19:37:44] (Debug) Destroying relay 'sto2#65 (155.133.252.36:27025)' because initial_ping_timeout
[14.09.2021 19:37:44] (Debug) Destroying relay 'eat#59 (155.133.235.34:27035)' because initial_ping_timeout
[14.09.2021 19:37:41] (Debug) Destroying relay 'sto2#96 (155.133.252.36:27056)' because initial_ping_timeout
[14.09.2021 19:37:41] (Debug) Destroying relay 'sof#5 (139.45.193.10:27019)' because initial_ping_timeout
[14.09.2021 19:37:41] (Debug) Destroying relay 'eat#28 (155.133.235.18:27042)' because initial_ping_timeout
[14.09.2021 19:37:39] (Verbose) Communications with routing cluster 'syd' established.
[14.09.2021 19:37:39] (Verbose) Communications with routing cluster 'tyo' established.
[14.09.2021 19:37:39] (Verbose) Communications with routing cluster 'tyo1' established.
[14.09.2021 19:37:39] (Verbose) Communications with routing cluster 'sgp' established.
[14.09.2021 19:37:39] (Verbose) Communications with routing cluster 'sea' established.
[14.09.2021 19:37:39] (Verbose) Communications with routing cluster 'scl' established.
[14.09.2021 19:37:39] (Verbose) Communications with routing cluster 'lim' established.
[14.09.2021 19:37:39] (Verbose) Communications with routing cluster 'jnb' established.
[14.09.2021 19:37:39] (Verbose) Communications with routing cluster 'maa' established.
[14.09.2021 19:37:39] (Verbose) Communications with routing cluster 'eze' established.
[14.09.2021 19:37:39] (Verbose) Communications with routing cluster 'hkg' established.
[14.09.2021 19:37:39] (Verbose) Communications with routing cluster 'lax' established.
[14.09.2021 19:37:39] (Verbose) Communications with routing cluster 'vie' established.
[14.09.2021 19:37:39] (Verbose) Communications with routing cluster 'gru' established.
[14.09.2021 19:37:39] (Verbose) Communications with routing cluster 'sto' established.
[14.09.2021 19:37:39] (Verbose) Communications with routing cluster 'waw' established.
[14.09.2021 19:37:39] (Verbose) Communications with routing cluster 'ord' established.
[14.09.2021 19:37:39] (Verbose) Communications with routing cluster 'iad' established.
[14.09.2021 19:37:39] (Verbose) Communications with routing cluster 'bom' established.
[14.09.2021 19:37:39] (Verbose) Communications with routing cluster 'mad' established.
[14.09.2021 19:37:39] (Verbose) Communications with routing cluster 'par' established.
[14.09.2021 19:37:39] (Verbose) Communications with routing cluster 'dxb' established.
[14.09.2021 19:37:39] (Verbose) Communications with routing cluster 'dfw' established.
[14.09.2021 19:37:39] (Verbose) Communications with routing cluster 'lhr' established.
[14.09.2021 19:37:39] (Verbose) Communications with routing cluster 'atl' established.
[14.09.2021 19:37:39] (Verbose) Communications with routing cluster 'ams' established.
[14.09.2021 19:37:39] (Verbose) Communications with routing cluster 'fra' established.
[14.09.2021 19:37:38] (Msg) SDR RelayNetworkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[14.09.2021 19:37:38] (Msg) Performing ping measurement
[14.09.2021 19:37:38] (Msg) Got SDR network config.  Loaded revision 330 OK
[14.09.2021 19:37:38] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[14.09.2021 19:37:16] Attempting to open ALC device "OpenAL Soft on Speaker/HP (Realtek High Definition Audio)"
[14.09.2021 19:37:14] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[14.09.2021 19:37:14] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[14.09.2021 19:37:10] Logged in as mrpeperosc (SteamID STEAM_1:1:445107981)

**Comment by Regalis11** [comment] 2021-09-15 10:03
Duplicate of https://github.com/Regalis11/Barotrauma/issues/6482

**Closed by Regalis11** 2021-09-15 10:03 UTC
