### ISSUE TITLE
[13.0.11] Bleeding wounds after finishing a campaign persist

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#5562] opened 2021-04-22 13:33 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
After finishing a campaign I loaded my save again and got the new campaign map.
Just seconds later 2 of my bots died from bleeding wounds that they got at the end of the previous campaign.

Expected: Critical conditions are removed when starting into the new campaign run, or confusion occurs.

**Comment by Regalis11** [comment] 2021-04-22 14:07
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/05cb60363ea1301f96113a31dee66b0b9f6a5f2c

**Comment by Rokvach** [comment] 2021-04-27 08:19
Tested, wasn't able to reproduce, seems to be working correctly. Closing.

**Closed by Rokvach** 2021-04-27 08:19 UTC
Labels: Bug, Code
