### ISSUE TITLE
Aiming when crouching leans you body backwards

### ISSUE THREAD

**Issue by Abkim27** [Regalis11/Barotrauma#12202] opened 2023-06-20 15:13 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Aiming while crouching slowly leans your torso backwards.

### Reproduction steps

1.Crouch
2.Aim
3.Wait

### Bug prevalence

Happens every now and then

### Version

v1.0.20.1

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment] 2023-07-10 11:42
No known steps to repro, closing

**Comment by Jasontti** [comment] 2023-07-13 09:09
Bug is present in public unstable (tested on linux) and current traitor-update build, tested with linux and windows.

Reproduction steps
1.Crouch
2.Aim (Tested with revolver and riot shotgun)
3.Wait

**Comment by Regalis11** [comment] 2023-07-13 10:22
I think the reason why I couldn't repro this was that I didn't wait long enough, and expected the effect to be more noticeable. Addressed in https://github.com/Regalis11/Barotrauma-development/commit/2c71287ba921824b66a5f91024a4bc021a50b1b7

**Comment by Jasontti** [comment] 2023-07-26 11:56
Tested.
Feet are getting scooted slowly apart. No issues with not keeping back straight.
![image](https://github.com/Regalis11/Barotrauma/assets/8488224/568b0203-859c-4f99-9ca8-e90da692286c)

**Comment by itchyOwl** [comment] 2023-10-11 10:50
I've seen (and fought with) similar issues before. The poses and animations rely on physics forces and pull positions. Consequentally, there's no guarantee of any pose being stable. If it's not an issue in practice, I'd just ignore it. If it's still a real issue, we could try adjusting the pose further.

**Closed** 2023-10-27 08:43 UTC
Labels: Bug, Low prio
