### ISSUE TITLE
crahs report

### ISSUE THREAD

**Issue by pastabase1** [Regalis11/Barotrauma#8919] opened 2022-04-22 19:55 UTC
The game has some mods but I uninstalled them to see if it solved it and nothing,

Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19043.0 64 bit
    GPU name: AMD Radeon HD 7450
    Display mode: {Width:1600 Height:1200 Format:Color AspectRatio:1,3333334}
    GPU status: Normal

Exception: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: La instancia de dispositivo de GPU se ha suspendido. Use GetDeviceRemovedReason para averiguar cuál es la acción adecuada.
 (SharpDX.SharpDXException)
Device removed reason: HRESULT = 0x887A0006
Target site: Void CheckError()
Stack trace: 
   at SharpDX.Result.CheckError()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 1017
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 511
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59

Last debug messages:
[22-04-2022 15:52:54] Generating an outpost for the start of the level... (Location: Ciudad de Sontu, level type: LocationConnection)
[22-04-2022 15:37:29] Overriding an affliction or a buff with the identifier 'concussion' using the file 'C:/Users/ropto/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2648774153/Characters/Human/Afflictions.xml'
[22-04-2022 15:37:29] Overriding an affliction or a buff with the identifier 'nausea' using the file 'C:/Users/ropto/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2648774153/Characters/Human/Afflictions.xml'
[22-04-2022 15:36:52] Attempting to open ALC device "OpenAL Soft on Altavoces (Realtek High Definition Audio)"
[22-04-2022 15:36:49] Logged in as pasta base (SteamID STEAM_1:0:217652039)

**Comment by Regalis11** [comment] 2022-04-23 08:31
Duplicate of https://github.com/Regalis11/Barotrauma/issues/1833

**Closed by Regalis11** 2022-04-23 08:31 UTC
