### ISSUE TITLE
Dragging item into fabricator/deconstructor causes crash

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#6556] opened 2021-09-03 16:54 UTC
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
[crashreport (27).log](https://github.com/Regalis11/Barotrauma/files/7107424/crashreport.27.log)
[crashreport (28).log](https://github.com/Regalis11/Barotrauma/files/7107426/crashreport.28.log)

**Steps To Reproduce**
Drag and drop an item into a fabricator/deconstructor

**Version**
windows v0.15.1.0 unstable

**Comment by Regalis11** [comment] 2021-09-05 13:21
Seems to be caused by the same bug as https://github.com/Regalis11/Barotrauma/issues/6549

**Comment by Rokvach** [comment] 2021-09-06 07:34
Tested, wasn't able to reproduce the issue, seems to be working correctly. Closing.

**Closed by Rokvach** 2021-09-06 07:34 UTC
Labels: Bug, Code, Crash
