### ISSUE TITLE
game crashes during submarine editing with using wires.

### ISSUE THREAD

**Issue by wizwarioo** [Regalis11/Barotrauma#4994] opened 2021-02-05 06:31 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Tried to transfer a wire from 1 object to another object I wanted to use instead, game freaks out and creates 2 of the same wire and crashes when I stick the wire in.

**Steps To Reproduce**
remove wiring from an object(alarm) to another object(emergency light) hook the wire onto a socket, yet somehow having a copy of the wire that I moved over, game crashes from confusion.

**Version**
v0.11.0.10

**Additional information**

Crash file I got.

Barotrauma Client crash report (generated on 2/4/2021 10:44:53 PM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

47BDC83F092CDFE5B755C0308161F31E

Game version 0.11.0.10 (ReleaseWindows, branch release, revision dc7157029e)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: Beluga (DACB4CCFD2C77A8AF6541CAA080E2E33)
Selected screen: Barotrauma.SubEditorScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19042.0 64 bit
    GPU name: NVIDIA GeForce GTX 1080
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') (System.ArgumentOutOfRangeException)
Target site: Void ThrowArgumentOutOfRange_IndexException()
Stack trace: 
   at Barotrauma.Items.Components.Wire.UpdateEditing(List`1 wires) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\Signal\Wire.cs:line 288
   at Barotrauma.SubEditorScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SubEditorScreen.cs:line 4007
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 924
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59

Last debug messages:
[2/4/2021 9:21:19 PM] (Msg) SDR RelayNetworkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[2/4/2021 9:21:19 PM] (Msg) Ping location: ord=13+1,iad=21+2,atl=27+2,dfw=31+3,sea=52+5,eat=60+6/57+5,lax=70+7/59+1,lhr=94+9,sto=95+9,fra=106+10/107+2,gru=152+15/158+2,sgp=271+27/248+3
[2/4/2021 9:21:19 PM] (Msg) Ping measurement completed
[2/4/2021 9:21:15 PM] (Verbose) Communications with routing cluster 'sgp' established.
[2/4/2021 9:21:15 PM] (Verbose) Communications with routing cluster 'syd' established.
[2/4/2021 9:21:15 PM] (Verbose) Communications with routing cluster 'waw' established.
[2/4/2021 9:21:15 PM] (Verbose) Communications with routing cluster 'tyo1' established.
[2/4/2021 9:21:15 PM] (Verbose) Communications with routing cluster 'tyo' established.
[2/4/2021 9:21:15 PM] (Verbose) Communications with routing cluster 'maa' established.
[2/4/2021 9:21:15 PM] (Verbose) Communications with routing cluster 'jnb' established.
[2/4/2021 9:21:15 PM] (Verbose) Communications with routing cluster 'scl' established.
[2/4/2021 9:21:15 PM] (Verbose) Communications with routing cluster 'sof' established.
[2/4/2021 9:21:15 PM] (Verbose) Communications with routing cluster 'sto2' established.
[2/4/2021 9:21:15 PM] (Verbose) Communications with routing cluster 'vie' established.
[2/4/2021 9:21:15 PM] (Verbose) Communications with routing cluster 'sto' established.
[2/4/2021 9:21:15 PM] (Verbose) Communications with routing cluster 'sea' established.
[2/4/2021 9:21:15 PM] (Verbose) Communications with routing cluster 'lim' established.
[2/4/2021 9:21:15 PM] (Verbose) Communications with routing cluster 'hkg' established.
[2/4/2021 9:21:15 PM] (Verbose) Communications with routing cluster 'mad' established.
[2/4/2021 9:21:15 PM] (Verbose) Communications with routing cluster 'bom' established.
[2/4/2021 9:21:15 PM] (Verbose) Communications with routing cluster 'lux' established.
[2/4/2021 9:21:15 PM] (Verbose) Communications with routing cluster 'dxb' established.
[2/4/2021 9:21:15 PM] (Verbose) Communications with routing cluster 'par' established.
[2/4/2021 9:21:15 PM] (Verbose) Communications with routing cluster 'lhr' established.
[2/4/2021 9:21:15 PM] (Verbose) Communications with routing cluster 'eze' established.
[2/4/2021 9:21:15 PM] (Verbose) Communications with routing cluster 'lax' established.
[2/4/2021 9:21:15 PM] (Verbose) Communications with routing cluster 'gru' established.
[2/4/2021 9:21:15 PM] (Msg) Relay iad#20 (162.254.192.66:27034) is going offline in 218 seconds
[2/4/2021 9:21:15 PM] (Verbose) Communications with routing cluster 'iad' established.
[2/4/2021 9:21:15 PM] (Verbose) Communications with routing cluster 'ord' established.
[2/4/2021 9:21:15 PM] (Verbose) Communications with routing cluster 'fra' established.
[2/4/2021 9:21:15 PM] (Verbose) Communications with routing cluster 'ams' established.
[2/4/2021 9:21:15 PM] (Verbose) Communications with routing cluster 'eat' established.
[2/4/2021 9:21:15 PM] (Verbose) Communications with routing cluster 'dfw' established.
[2/4/2021 9:21:15 PM] (Verbose) Communications with routing cluster 'atl' established.
[2/4/2021 9:21:15 PM] (Msg) SDR RelayNetworkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[2/4/2021 9:21:15 PM] (Msg) Performing ping measurement
[2/4/2021 9:21:15 PM] (Msg) Got SDR network config.  Loaded revision 296 OK
[2/4/2021 9:21:15 PM] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[2/4/2021 9:21:08 PM] Attempting to open ALC device "OpenAL Soft on Speakers (2- Yeti Stereo Microphone)"
[2/4/2021 9:21:07 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[2/4/2021 9:21:07 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[2/4/2021 9:21:05 PM] Logged in as WizWarioo (SteamID STEAM_1:1:25315566)

**Comment by Regalis11** [comment] 2021-02-05 09:38
Duplicate of https://github.com/Regalis11/Barotrauma/issues/4536

**Closed by Regalis11** 2021-02-05 09:38 UTC
