### ISSUE TITLE
Pathfinding Bug (reproduceable in Berilia Reactor Room)

### ISSUE THREAD

**Issue by gerakis** [Regalis11/Barotrauma#7933] opened 2021-12-25 01:35 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Vanilla Berilia has a pathfinding bug in the reactor room, on the left side of the bilge tank. If you damage the wall just below the platform, the bots all get stuck on the ladder somehow. This only happens if the bots approach through the right hand door. If they come through the hatch in the ceiling they can still reach it.

**Steps To Reproduce**
Set some bots to "Fix Leaks." Plasma cutter the left wall of the bilge in the reactor room of the Berilia. Watch the bots get stuck.

**Version**
0.15.22 Windows, no mods, singleplayer campaign

**Additional information**
https://youtu.be/tYTU2EhA6EI

I was able to fix it in the sub editor by moving the lower ladder point up 2 squares. Like this: 

![fixed pathfinding](https://user-images.githubusercontent.com/16128947/147375614-efc4cb2f-71be-4a86-a101-588c7ae57cf8.png)

**Comment by MaaiG** [comment] 2021-12-28 18:34
> This only happens if the bots approach through the right hand door.

Incorrect. Problem with the `Generator waypoints`! `Generator waypoints` sets paths without regard to the environment.
If you remove all way points and use the `generator waupoints`, it will make the same errors.

Here’s the right:
![Image 001_21-27](https://user-images.githubusercontent.com/93348499/147596389-b8586544-3067-4674-916c-0128788b052f.png)

**Comment by itchyOwl** [comment] 2022-01-03 11:02
I don't see anything wrong with those waypoints. Could be in the fix leaks logic. I'll try to repro and diagnose it.

**Comment by MaaiG** [comment] 2022-01-03 14:59
IMHO:
1. Maybe, Inside the submarine, the "stair" points shall be higher than the usual "horizontal" points of the path. They shall not be low at the floor. It seems that bots cannot use the "stairs" points low above ground.
![Image 001_17-34](https://user-images.githubusercontent.com/93348499/147943730-58ad144e-9982-4b6e-a5a1-d7c2ecaf3126.png)

2. Paths sometimes overlap. Perhaps the dots should always appear at a distance from each other and not closer than a certain distance.
![Image 001_17-36](https://user-images.githubusercontent.com/93348499/147943956-c48083c2-6ef6-49a7-bcd3-35a7b3c1df87.png)

3. Sometimes the crossing routes do not connect and sometimes a "ladder" point is created inside a floor or ceiling:
![Image 001_17-49](https://user-images.githubusercontent.com/93348499/147944614-bd61648a-82df-401e-8190-6e5efd2ea060.png)

4. Path points do not bypass the engine propeller
![Image 001_17-28](https://user-images.githubusercontent.com/93348499/147944037-bb5270dc-9a1c-4d3a-a547-b501370bc3c1.png). Yes, [this is happening] (https://github.com/Regalis11/Barotrauma/issues/7969#issuecomment-1003973319)

5. Path is built via hitbox
![Image 001_17-29](https://user-images.githubusercontent.com/93348499/147944189-7c783f9f-feaa-4bb3-ae3e-1bdbce2e673b.png)

**Comment by itchyOwl** [comment] 2022-01-05 08:44
The waypoint generator is not perfect, but inside the sub it should create paths that don't need to be manually adjusted. There can be some corner cases. Outside the sub it's not as good, and the issues referred above are known.

In any case, this issue was not caused by waypoints. Instead it was some custom logic added to solve another edge case (bots letting go of the ladders too soon). Fixed in Regalis11/Barotrauma-development@9aec29b.

**Comment by Rokvach** [comment] 2022-01-20 10:09
Tested, working correctly. Closing.

**Closed by Rokvach** 2022-01-20 10:09 UTC
Labels: Bug, Code
