### ISSUE TITLE
[0.11.0.7] Multiplayer? - Added wire line is incorrectly displayed

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4353] opened 2020-11-20 01:39 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I rewired status monitor, and navigation terminal a few level backs, and all of a sudden we see a wire line stretched straight out from the relay connecting to the battery behind the reactor.

[HoloTwitchWire.zip](https://github.com/Regalis11/Barotrauma/files/5570706/HoloTwitchWire.zip)
![Capture1](https://user-images.githubusercontent.com/5086682/99745183-28f54600-2aa7-11eb-9e90-5962f14b78af.PNG)

**Version**
0.11.0.7

**Comment by Regalis11** [comment] 2020-11-20 11:01
Even though I'm not 100% sure how exactly the nodes ended up like this, I managed to repro it as follows:
1. Wire two devices: make sure you're facing left when connecting the wire to the 2nd device (meaning that the wire is mirrored horizontally while you place it)
2. Start a new round by leaving/entering an outpost

If that was the cause, should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/62fe80cda1e5c9d0dadeb7be79c7832ef0fb9b6f

**Comment by Rokvach** [comment] 2020-11-20 12:13
Tested, wasn't able to reproduce the issue. Working correctly. Closing.

**Closed by Rokvach** 2020-11-20 12:13 UTC
Labels: Bug, Code
