### ISSUE TITLE
[Bug] Ability to duplicate and/or generate free power with batteries and relays

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#4139] opened 2020-10-27 06:16 UTC
**Description :**

**Duplication of power :** 
You can duplicate power by wiring them from reactor to relay to batteries then into the main power grid, this will result in some amount of power duplication (example provided below with reactor maxoutput 500 and the setup in azimuth).
Example name : Powerdupe

**Generation of power from basically thin air :**
with some charge in the battery, you can loop it to a relay back into itself charging it while somehow producing extra energy that can be tapped by a separate battery. Using default sub editor values for both batteries and relays, and afterwards adding 100 initial charge to them and maxing out its recharge speed to 100%, with 4x5 arrays into another battery every array and further wired into a Junction box, you can effectively power the azimuth without any external power source. 
Example name : bruh

**Additional information**
Tested in [0.10.6.2]
[2 Test Examples.zip](https://github.com/Regalis11/Barotrauma/files/5443286/2.Test.Examples.zip)

**Comment by Regalis11** [comment] 2020-10-27 08:03
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3238

**Closed by Regalis11** 2020-10-27 08:03 UTC
