### ISSUE TITLE
Wrong Job assignment in MP

### ISSUE THREAD

**Issue by Hegny** [Regalis11/Barotrauma#11999] opened 2023-05-12 09:36 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

In Multiplayer Missions players are assigned random roles at the beginning of the round, despite their selection in Lobby. In some cases only part of the team get random roles. In some rounds all roles assigned as chosen. If I check it alone or with 1-2 players, everything looks OK, as soon as 6 or more people are playing, this bug happens.

Game version 1.0131 and 1.0132
Windows
Dedicated Server
no mods

### Reproduction steps

1. Start Multiplayer Missions on a dedicated server
2. Get 5-6 players
3. Choose roles
4. Start the game

### Bug prevalence

Happens regularly

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Lepestochek** [comment] 2023-05-13 03:45
Have you considered job limit? Captain, security and medics can have only 2 active crewmembers each.

**Comment by Hegny** [comment] 2023-05-13 08:16
The problem is completely solved by disabling (commenting out) **charInfoRateLimiter** in **ServerSource/Networking/GameServer.cs**

string 3632
`
//if (charInfoRateLimiter.IsLimitReached(sender)) { return; }`

It looks like limits are too low or not resetting

**Comment by Regalis11** [comment] 2023-05-13 09:50
Thank you for the report!

@Hegny I'm not actually quite convinced the rate limiter is the issue. In the mission mode, that method is only called once when the round starts, so it shouldn't be possible for the limits to be exceeded (unless you're restarting the rounds more than 5 times in 10 seconds). I would've personally guessed it has to do with the job limits instead. But I'll do some more debugging and see if I can verify where the issue is!

**Comment by Hegny** [comment] 2023-05-13 10:06
> Have you considered job limit? Captain, security and medics can have only 2 spawned crewmembers each.

It is definitely no a job limit. Having one captain, one medic ant 2 securities in the lobby, and all jobs messed at round start. I described above: commenting one line of the code solved the problem - we do not get it anymore.

**Comment by Regalis11** [comment] 2023-05-13 13:01
I gave this a test with 6 clients, and unfortunately I couldn't reproduce the issue. I verified that the IsLimitReached is only called once per each client when the round starts, which doesn't trigger the rate limiter. 

However, it's curious that the issue happens with 5-6 players: the rate limit is 5, so 5 or more requests would cause it to trigger. There must be some connection here, but I'm not entirely sure what, since the rate limiter should be per client, and the number of clients shouldn't make a difference. To double-check, you aren't using any mods or source code modifications by any chance (you mentioned you're not using mods, but checked the "happened while using mods" checkbox)? Do you see any warnings or errors in the server window when you start a round? If the rate limiter triggers, the server should display a warning in both the window and the server log.

**Comment by Hegny** [comment] 2023-05-13 15:52
@Regalis11 
Originally we encountered this bug on our source-code modified server.
However, right after that I have newly install clean vanilla server and this bug was there.
There were no errors in server log. To trace the bug I was adding Log to different parts of the code and found, that when this happens, the following part of **AssignJobs** function is working (GameServer.cs)  see the last ELSE statement: 


           //give random jobs to rest of the clients
            foreach (Client c in unassigned)
            {
                //find all jobs that are still available
                var remainingJobs = jobList.FindAll(jp => assignedClientCount[jp] < jp.MaxNumber && c.Karma >= jp.MinKarma);

                //all jobs taken, give a random job
                if (remainingJobs.Count == 0)
                {
                    DebugConsole.ThrowError("Failed to assign a suitable job for \"" + c.Name + "\" (all jobs already have the maximum numbers of players). Assigning a random job...");
                    int jobIndex = Rand.Range(0, jobList.Count);
                    int skips = 0;
                    while (c.Karma < jobList[jobIndex].MinKarma)
                    {
                        jobIndex++;
                        skips++;
                        if (jobIndex >= jobList.Count) { jobIndex -= jobList.Count; }
                        if (skips >= jobList.Count) { break; }
                    }
                    c.AssignedJob =
                        c.JobPreferences.FirstOrDefault(jp => jp.Prefab == jobList[jobIndex]) ??
                        new JobVariant(jobList[jobIndex], 0);
                    assignedClientCount[c.AssignedJob.Prefab]++;
                }
                //if one of the client's preferences is still available, give them that job
                else if (c.JobPreferences.Any(jp => remainingJobs.Contains(jp.Prefab)))
                {
                    foreach (JobVariant preferredJob in c.JobPreferences)
                    {
                        c.AssignedJob = preferredJob;
                        assignedClientCount[preferredJob.Prefab]++;
                        break;
                    }
                }
                else //none of the client's preferred jobs available, choose a random job
                {
                   //Hegny:   THIS PART OF THE CODE IS EXECUTED
                    c.AssignedJob = new JobVariant(remainingJobs[Rand.Range(0, remainingJobs.Count)], 0);
                    assignedClientCount[c.AssignedJob.Prefab]++;
                }
            }

So it looks like the server didn't have a preferred job for the client.
In some round it happened to all of the players (except required min job), in some round only to some clients.
The first round after starting the server was always OK.

It looks like, but I am not sure, that if the player got a proper job, played the round and didn't change it, he got a proper (the same) job again. If he changed his preference, there was a high chance he will get a random job. So it looks like server do not update character some times.

It might be related to the following issue:
in the debug (only) console we quite often have the error:
`Error when writing character spawn data for "XXX": status data caused the length of the message to exceed 255 bytes (197 + 61)`
however, since last two years this is a "normal" error which did not cause any problems before. Can it be, that the character data is trying to update again if this error happens?

Any way, as I mentioned above, disabling the **charInfoRateLimiter** solves the problem entirely.

**Comment by Regalis11** [comment] 2023-05-13 17:08
Thank you for the extra info! It does seem like the server isn't aware of the client's job preferences for some reason.

> The first round after starting the server was always OK.

This could be a valuable piece of information, I didn't test starting multiple rounds which might be why I was unable to reproduce the issue. I'll give it another test!

**Comment by NilanthAnimosus** [comment] 2023-06-12 10:31
Tested against 1.0.13.2,

I used 6 clients, without any permissions against a windows dedicated server on mission mode (Cargo) starting and ending rounds.

Clients had: 1 captain, 2 security, 2 medical, 1 mechanic. After 6 rounds nothing occurred, started changing up the roles after the 6th and around the 12th-16th start no issues occurred despite I had been swapping the roles up each restart (Inverting the security and medical, mechanic to engineer and assistant, captain as spectator or not, etc.). I even tried rejoining the game for one of the clients and that didn't cause job assignment issues either.

I made sure there was no spam immunity on the clients or other things that could effect it, but the only reasonable thing that could explain this is if the jobs were all taken and maxed out (Which a mod could do, and vanilla at this version had 2 max medics/security and 1 max captain).

If you still encounter this on your modified server, you could try adding some logging there to determine how many or what job preferences they actually had chosen (If any), and maybe what jobs remained.

As a note, to exceed the charInfoRateLimiter individual clients would have to change their job preferences 5+ times within 10 seconds on game starts only (not lobby changes to your job/appearance/name and such). given I had the limiter active without issues I don't think there is an issue of it not resetting as job preferences were changing fine.

**Comment by Krzeszny** [comment] 2023-09-28 22:06
Still an issue. I picked a medic as my only preference but became an engineer for no reason:
![image](https://github.com/Regalis11/Barotrauma/assets/10529134/3b5f6cc8-151e-41bd-8dda-6c9a395848b4)

The only installed mod that changes jobs is Neurotrauma.
![Barotrauma_PGZJcvoHUa](https://github.com/Regalis11/Barotrauma/assets/10529134/b3994791-80eb-4bc6-9f7e-e8e978ad0cc2)

**Comment by Rokvach** [comment] 2023-11-07 10:18
Tested with the new "debugjobassignment" command and didn't see any issues with the assignment of jobs, also made sure that karma doesn't have a factor in the assignment of jobs anymore. 

Working correctly, can be merged and closed.

**Closed by Rokvach** 2023-11-07 10:18 UTC
Labels: Bug, Need more info, Code, Networking
