### ISSUE TITLE
[0.1001.0.0] Bots don't take off their diving masks or diving suits when situatuion has cleard out.

### ISSUE THREAD

**Issue by Camper125Lv** [Regalis11/Barotrauma#3011] opened 2020-06-08 11:29 UTC
**Description**
Bots don't take off their diving masks or diving suits when situatuion has cleard out. Also they wear diving masks with diving suits.

**Steps To Reproduce**
Flood the sub with bots then unflud it.

**Additional information**
Would be nice if they put on their gear back on when after removing diving gear.

**Comment by Regalis11** [comment] 2020-06-08 11:40
Duplicate of #2859

**Closed by Regalis11** 2020-06-08 11:40 UTC
