### ISSUE TITLE
Bots fires railgun shells on wreck corpses with red names

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4901] opened 2021-01-25 21:46 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots fires railgun shells on wreck corpses with red names.
![Capture](https://user-images.githubusercontent.com/5086682/105770158-d1eb7180-5f2c-11eb-9b81-424ceb797939.PNG)

**Version**
~0.12.0.0

**Comment by Rokvach** [comment] 2021-01-26 12:13
Tested, only way I managed to cause bots to shoot at the wreck corpse was if they were alive. I tested every other way possible, also tested with other dead creatures and they just don't target them. 

It shouldn't be possible for a wreck corpse to have health or be alive when its spawned in. Also I don't think husk infections work on them either, I did try by giving a wreck corpse a husk infection but the bots didn't care to target it even then as it was already dead. 

So can't reproduce the issue.

**Comment by itchyOwl** [comment] 2021-01-26 13:06
And bots should ignore all dead characters.

**Comment by Kaillera** [comment] 2021-01-26 13:35
I've had this happened a few times, but it only happens once per round at most. I think it happens when there is a enemy in the wreck, but only when they can't swim out. Drive up to a wreck with a submarine with a bottom Railgun. Immediately pull out a wreck corpse when there are monsters in the wrecks.

I wonder if what's happening is that it acquired a monster but it couldn't see it, so it just fires at the corpse because it's considered an enemy, and the target it was locking on is alive.

**Comment by itchyOwl** [comment] 2021-01-26 14:07
I think it could be possible that the bot is targeting a monster that's behind the corpse, possibly inside the wreck. Corpses are probably not considered friendly, so the bots shouldn't avoid shooting at them. I'll try to repro it.

**Comment by itchyOwl** [comment] 2021-01-28 14:39
Can't repro.

**Comment by itchyOwl** [comment] 2021-01-29 04:04
I did two changes that might affect this:
- Bots no more aim at monsters that are inside a submarine. This could cause situations where the bots won't shoot targets that they should be able to see, because they are technically inside a hull. If this is an issue, then we probably need to make an early raycast to check if there's a wall between the target or not. Or just revert to how it was before. The issue with that, however, is that bots will actually target monsters through the walls, although they won't shoot them.
- The corpses are now in the "FriendlyNPC" team.

So, I'll consider this done. QA can test my changes quickly and close the ticket after that.

**Comment by mrjpjr** [comment] 2021-01-29 10:22
This happens to me most consistently in Wreck 1.
I agree that it is likely a case of the bots tracking a creature inside and shooting when the corpse passes in the path of the gun.

**Comment by Rokvach** [comment] 2021-03-08 09:12
There hasn't been any new sightings of this happening in Unstable and nothing else weird either. Working correctly. closing.

**Closed by Rokvach** 2021-03-08 09:12 UTC
Labels: Bug, Code, Low prio, Needs testing
