### ISSUE TITLE
CustomInterface null reference exception

### ISSUE THREAD

**Issue by evilfactory** [Regalis11/Barotrauma#10943] opened 2023-01-15 17:12 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

While in a modded round i got kicked back to the server list, it seems there's some kind of null reference exception in the custom interface component.
![firefox_eWfx4weBr0](https://user-images.githubusercontent.com/36804725/212555892-43794799-92f4-4268-bb40-75bf28a44445.png)
and here's another variant of the error that i found
![Discord_WZuoz7iYK9](https://user-images.githubusercontent.com/36804725/212556076-0a9ae6b4-9f7c-4922-a621-61de8aceccf6.png)

### Reproduction steps

One potential way to reproduce the error could be using the custom interfaces in this mod https://steamcommunity.com/sharedfiles/filedetails/?id=2616577901

### Bug prevalence

Happens every now and then

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-01-16 10:01
Couldn't find a way to reproduce this, but added a null check in https://github.com/Regalis11/Barotrauma-development/commit/50e5c16b1718dc438f299f1cc6cc51d84d86f2ae that should prevent the exception.

**Comment by NilanthAnimosus** [comment] 2023-01-19 17:50
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/5a99225d052af0d1e71cccb9a84aaa87656abe1b

I went back to 0.20.16.1 and reproduced the issue reliably with a campaign save using the above mod. The above fixes indeed resolve the problem.

![image](https://user-images.githubusercontent.com/29177976/213521431-e96762fa-52e2-4e34-9de6-01ef1b34076d.png)
![image](https://user-images.githubusercontent.com/29177976/213521455-37b3c534-1ad7-4e24-88cb-8e2e08d8b5d2.png)

I am not entirely sure if there is another issue at play here that may be harmless now (Unnecessary syncing from the server? zero elements in list?) as with no signals what are we syncing exactly?

**Comment by Regalis11** [comment] 2023-01-20 10:57
It seems that was caused by the tapes: the server always created a network event for CustomInterface components to make sure the state of the UI elements is in sync, even if the component has no interactable UI elements. I don't think it caused any actual issues, aside from causing the server to send an unnecessary event to the clients, but fixed it anyway in https://github.com/Regalis11/Barotrauma-development/commit/8f2c699f613c5642ec46346133a2e6f9b95388e0

**Comment by NilanthAnimosus** [comment] 2023-01-23 17:09
Tested against Fix/bugfixes-2 commit https://github.com/Regalis11/Barotrauma-development/commit/f501efb0b2c1b8ee8f8c243b3e88f50853f94db0, working correctly, closing

**Closed by NilanthAnimosus** 2023-01-23 17:09 UTC
Labels: Bug, Code, Modding, Unstable
