### ISSUE TITLE
Client times out at the start of a round (expected old event)

### ISSUE THREAD

**Issue by MrTeco** [Regalis11/Barotrauma#2474] opened 2020-03-20 19:59 UTC
![image](https://user-images.githubusercontent.com/59005337/77201860-8dfa3580-6aed-11ea-86bf-8e3cc7139aa1.png)
Every time a round starts on my server I get kicked and join again, requiring me to click spectate to take control over my body again.

**Comment by thegrb93** [comment] 2020-03-20 22:00
Seems to happen with clients that have slower computers/internet. Those of us with beefcake computers never get the issue.

**Comment by MrTeco** [comment] 2020-03-20 22:12
Then why does it happen on my server only? my hard drive is good enough and I never had slow loading issues anywhere else.

**Comment by thegrb93** [comment] 2020-03-20 22:15
>Harddrive

That's why

**Comment by Regalis11** [comment] 2020-03-21 09:48
Yeah, this sometimes happens in the current public version if the client takes much longer to load the round than the server. We've done some improvements to this in the Unstable version, and the fixes will be included in the next patch: https://trello.com/c/mNtTgUch/286-disconnect-when-a-round-starts-excessive-desync-expected-old-event

**Comment by MrTeco** [comment] 2020-03-21 18:09
![image](https://user-images.githubusercontent.com/59005337/77233400-6ebfde80-6ba7-11ea-9809-86179f8c2a5a.png)
not my problem, as I said

**Comment by Regalis11** [comment] 2020-03-22 17:59
An SSD doesn't unfortunately help much with this issue if the server is running on the same computer, because it means the server is also able to start the round faster, giving the clients less time to catch up. The SSD/HDD is also not the only thing that affects loading times; the speed of the level generation for example depends mainly on the CPU.

But in any case, I'm sorry for the inconvenience. We should be getting the patch out soon and hopefully get rid of this issue.

**Comment by Rokvach** [comment] 2020-03-23 07:45
No issues, closing.

**Closed by Rokvach** 2020-03-23 07:45 UTC
Labels: Bug, Code, Networking

**Comment by thegrb93** [comment] 2020-04-19 04:02
This is back again in 0.9.9.0

https://streamable.com/upqrki

**Comment by Regalis11** [comment] 2020-04-20 06:52
@thegrb93 That seems to be a different issue ("missing entity", not a timeout caused by receiving an event taking an excessive amount of time). We have a ticket about the "missing entity" error here: https://github.com/Regalis11/Barotrauma/issues/2382
