### ISSUE TITLE
InnerClothes+OuterClothes makes wearable invisible

### ISSUE THREAD

**Issue by mcbanekenney** [Regalis11/Barotrauma#8145] opened 2022-01-31 23:52 UTC
- [✓] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you set a uniform's slots to "Any,InnerClothes+OuterClothes", the clothing becomes invisible when worn.

**Steps To Reproduce**
Take a security uniform, set the wearable slots to "Any,InnerClothes+OuterClothes", clothing should become invisible when equipped.

**Version**
v0.15.23.0, Windows 10

**Additional information**
Attempting to create a heavy uniform that takes up your OuterClothes slot as well as your uniform slot, as well as making a diving suit that works like they did in the pre-alpha Legacy builds of the game

**Comment by Regalis11** [comment] 2022-02-02 12:18
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/42028fabd7524c20a7381695bbff5b9608ff1e60

**Comment by Rokvach** [comment] 2022-02-09 22:08
This hasn't caused any issues to the vanilla gameplay, I think I'm just going to close it. We can always re-open this ticket if it still does happen once the patch is out. Closing.

**Comment by Rokvach** [comment] 2022-03-15 12:01
Tested, a security officer will spawn naked with their uniform moved to their inventory, you can't place the uniform to the uniform slot but instead on the diving suit slot where it then gets mirrored to the uniform slot and is shown properly, is this the intended behavior?

**Comment by Rokvach** [comment] 2022-03-16 16:56
Closing.

**Closed by Rokvach** 2022-03-16 16:56 UTC
Labels: Bug, Code, Modding
