### ISSUE TITLE
'Mod hash calculation did not match expected hash' after changing the name of a mod to another language

### ISSUE THREAD

**Issue by AndyLonly** [Regalis11/Barotrauma#12034] opened 2023-05-19 17:10 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Mods hash calculation did not match expected hash therefore the mod cannot be enabled

### Reproduction steps

1. Set your steam client (presumably your account's display language is also required) and the game to Simplified Chinese
2. Start game
3. Upload a new mod, using Simplified Chinese in the name and description, and use Simplified Chinese for the name in the filelist
4. Update the mod, using English in the mod's name and description
5. Open the settings and try to enable the mod (not the local copy)

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by NilanthAnimosus** [comment] 2023-05-29 14:17
Tested on 1.0.13.2

I've tried both with and without setting the steam language to simplified Chinese and uploading in simplified Chinese initially then changing the name and description to English on updating following the provided steps.

I tried uploading it in simplified chinese, and then updating it with file changes (for a different hash) alongside the change to english, and couldn't reproduce the issue still.

I can't seem to reproduce this and may need more info/insight into whats occuring here, such as is it a core mod or if there is any other steps you might be taking, is it an LUA mod or such (and thus no XML content files)?

**Comment by AndyLonly** [comment] 2023-05-29 23:16
Sorry, this is additional information
You need to add simplified Chinese to the description of the workshop
![image](https://github.com/Regalis11/Barotrauma/assets/15814794/4e04441d-09de-4683-9ed5-ec89066ca3f3)

I tested both Lua mod and non-Lua mod and both reproduce
![image](https://github.com/Regalis11/Barotrauma/assets/15814794/06920725-5eda-432e-8c83-c13e2bbd86ad)

**Comment by Regalis11** [comment] 2023-05-30 06:22
@AndyLonly thank you for the clarification! It seems changing the title of the mod in some specific language in Steam is the key here.

It seems the issue can be reproduced as easily as this:
1. Change your Steam language to something else (I tested with Spanish, but any language will most likely do)
2. Publish a mod
3. In the publish page, open "show in steam", change the title of the mod in Spanish
4. Publish an update to the mod
5. Hash mismatch

**Comment by Regalis11** [comment] 2023-05-30 07:28
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/215636a1e1d594c2d91a5b6a6d2967925f0282ba

**Closed** 2023-05-31 11:16 UTC
Labels: Bug, Code, Severe, Modding
