### ISSUE TITLE
Chat broken for most of the players.

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5718] opened 2021-05-08 01:07 UTC
- [ yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I had husk infection, about 60%~ on (the phase where you can't chat anymore). When i got healed, i still couldn't talk, that's an issue itself, but after the round ended, i still couldn't chat, i killed myself and respawned next round as a new character, still unable to chat i left and rejoined the server, i was able to chat, but no one could read me, except 1 person. Then another person tried to chat, i was able to see it, but himself and every other person was unable to see the message, i have no more information on how this happened, the issue continued even in the lobby. Voice chat was not affected by any of this.

**Version**
v0.1300.3.11 Windows

**Additional information**
Here's the multiplayer save and the server logs where this whole thing happened

[Neon_and_The_Bois_and_nothing_but_clown_inc._2021-05-07_2337_3.txt](https://github.com/Regalis11/Barotrauma/files/6444877/Neon_and_The_Bois_and_nothing_but_clown_inc._2021-05-07_2337_3.txt)
[Neon_and_The_Bois_and_nothing_but_clown_inc._2021-05-07_2355.txt](https://github.com/Regalis11/Barotrauma/files/6444878/Neon_and_The_Bois_and_nothing_but_clown_inc._2021-05-07_2355.txt)
[Neon_and_The_Bois_and_nothing_but_clown_inc._2021-05-07_2355_2.txt](https://github.com/Regalis11/Barotrauma/files/6444879/Neon_and_The_Bois_and_nothing_but_clown_inc._2021-05-07_2355_2.txt)
[Neon_and_The_Bois_and_nothing_but_clown_inc._2021-05-08_0002 (1).txt](https://github.com/Regalis11/Barotrauma/files/6444880/Neon_and_The_Bois_and_nothing_but_clown_inc._2021-05-08_0002.1.txt)
[Neon_and_The_Bois_and_nothing_but_clown_inc._2021-05-08_0002.txt](https://github.com/Regalis11/Barotrauma/files/6444881/Neon_and_The_Bois_and_nothing_but_clown_inc._2021-05-08_0002.txt)
[Neon_and_The_Bois_and_nothing_but_clown_inc._2021-05-08_0009.txt](https://github.com/Regalis11/Barotrauma/files/6444882/Neon_and_The_Bois_and_nothing_but_clown_inc._2021-05-08_0009.txt)
[Neon_and_The_Bois_and_nothing_but_clown_inc._2021-05-08_0009_2.txt](https://github.com/Regalis11/Barotrauma/files/6444883/Neon_and_The_Bois_and_nothing_but_clown_inc._2021-05-08_0009_2.txt)
[Neon_and_The_Bois_and_nothing_but_clown_inc._2021-05-08_0045.txt](https://github.com/Regalis11/Barotrauma/files/6444884/Neon_and_The_Bois_and_nothing_but_clown_inc._2021-05-08_0045.txt)
[Neon_and_The_Bois_and_nothing_but_clown_inc._2021-05-08_0054.txt](https://github.com/Regalis11/Barotrauma/files/6444885/Neon_and_The_Bois_and_nothing_but_clown_inc._2021-05-08_0054.txt)
[Neon_and_The_Bois_and_nothing_but_clown_inc._2021-05-08_0107.txt](https://github.com/Regalis11/Barotrauma/files/6444886/Neon_and_The_Bois_and_nothing_but_clown_inc._2021-05-08_0107.txt)
[Neon_and_The_Bois_and_nothing_but_clown_inc._2021-05-08_0119.txt](https://github.com/Regalis11/Barotrauma/files/6444887/Neon_and_The_Bois_and_nothing_but_clown_inc._2021-05-08_0119.txt)
[The Bois.zip](https://github.com/Regalis11/Barotrauma/files/6444889/The.Bois.zip)

**Comment by Regalis11** [comment] 2021-12-14 14:14
I suspect this might've had something to do with https://github.com/Regalis11/Barotrauma/issues/7683 and https://github.com/Regalis11/Barotrauma/issues/7689, but hard to say for sure

**Comment by Regalis11** [comment] 2022-01-14 11:39
Suspecting this is a duplicate of the previously mentioned tickets, moving to QA (let's see if we run in to this again)

**Comment by Rokvach** [comment] 2022-01-18 09:17
This issue has been fixed already and is working without issues. So closing.

**Closed by Rokvach** 2022-01-18 09:17 UTC
Labels: Bug, Needs testing, Code, Networking
