### ISSUE TITLE
Dead character re-spawned on game load

### ISSUE THREAD

**Issue by CaptChairForce** [Regalis11/Barotrauma#2845] opened 2020-05-16 03:11 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
My captain had died during the a campaign mission. I docked at a location, saved the game and exited. When I came back and loaded my save, the captain was back on the crew but with no clothing or equipment and could not open any doors on the submarine.

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Windows 10, using the latest version of the game for 15 May 2020 (Windows/Linux/Mac).

**Additional information**
Single Player Campaign on casual mode.

**Comment by Regalis11** [comment] 2020-05-26 10:22
Duplicate of #2261

**Closed by Regalis11** 2020-05-26 10:22 UTC
Labels: Bug, Code
