### ISSUE TITLE
auto door audio glitch

### ISSUE THREAD

**Issue by thatloudpack** [Regalis11/Barotrauma#8378] opened 2022-02-25 20:33 UTC
when standing above some motion sensors you get the open and close audio of doors even though they are not moving

https://user-images.githubusercontent.com/100177152/155798941-5a77d076-ada7-4b13-b5ae-ea7ced5669f6.mp4

**Comment by Regalis11** [comment] 2022-03-01 12:41
I could not reproduce this in vanilla subs - which submarine is this? Could it be that the doors have been wired in a way that continuously toggles them when you're standing near the sensors?

**Comment by cshingle** [comment] 2022-03-03 21:47
@thatloudpack Are you sure this is an audio glitch and not sub design issue where the motion sensor is picking up movement though the floor? Doors tend to act this way when wired directly without a delay component on the closing signal.

**Comment by Regalis11** [comment] 2022-04-12 11:00
No known steps to repro (and more likely to be an issue with the sub itself), closing

**Closed by Regalis11** 2022-04-12 11:00 UTC
Labels: Bug, Need more info
