### ISSUE TITLE
Loot regenerates every time you leave and re-enter an abandoned outpost

### ISSUE THREAD

**Issue by MrFriJet** [Regalis11/Barotrauma#10059] opened 2022-10-11 23:08 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

After completing a surprise mission to exterminate eggs at an outpost. After killing all the enemies and sailing away from the outpost to receive a reward, I decided to look into it again. And he was surprised that there were no enemies on it, and loot appeared in all the boxes.

### Reproduction steps

Mission from a single company to clear the outpost from raptor eggs.

### Bug prevalence

Just once

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-10-12 06:47
Thank you for the report! I'm not entirely sure I understand the issue. Do you mean the problem was that monsters didn't reappear in the abandoned monster when you re-entered it?

**Comment by MrFriJet** [comment] 2022-10-13 07:41
The problem is that after completing the egg destruction mission, you can endlessly farm resources. Sailing and swimming to the outpost cleared of monsters. Loot is generated anew, but monsters are not.

**Comment by Regalis11** [comment] 2022-12-08 14:10
Thank you for the report!

I unfortunately couldn't find a way to reproduce the issue. Tested by first looting items from the outpost:
![image](https://user-images.githubusercontent.com/14351070/206467161-d231b2cc-bf93-4b23-bca4-e0698bd6af08.png)

After leaving and returning to the outpost, the cabinet I'd looted is still empty:
![image](https://user-images.githubusercontent.com/14351070/206467437-ba1df547-e2e8-4eed-b9d9-68c885887e22.png)

**Comment by Regalis11** [comment] 2023-04-11 08:05
No known steps to repro, closing

**Closed by Regalis11** 2023-04-11 08:05 UTC
Labels: Bug, Need more info, Code
