### ISSUE TITLE
Crew menu interact box prevents shooting weapons

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#6535] opened 2021-08-31 17:32 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When the crew menu is open, you can't shoot weapons when aiming at the upper left side of the screen

**Steps To Reproduce**
1. Press C to open crew menu
2. Grab a gun
3. Aim gun in the upper-left corner
4. Aiming reticle turns into a hand cursor
5. Can't shoot

![image](https://user-images.githubusercontent.com/73229309/131549097-08d48290-3951-475e-bd62-3c6210bfeaef.png)

You can't shoot in this entire area of the screen, even if there's no crew to click on

**Comment by ekqvist** [comment] 2021-08-31 21:25
Duplicate of #6521

**Closed** 2021-08-31 21:26 UTC
Labels: Bug, Duplicate, Code

**Comment by ubertpendragon** [comment] 2021-08-31 22:53
woopsie didn't see
