### ISSUE TITLE
Shuttle cannot dock

### ISSUE THREAD

**Issue by Polalmb** [Regalis11/Barotrauma#1747] opened 2019-07-10 06:50 UTC
[cattus vastator.zip](https://github.com/Regalis11/Barotrauma/files/3376086/cattus.vastator.zip)

[ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
A sub i have been working on for two days cannot have its shuttle re dock with the sub
 docking port as when i get close to the sub in the shuttle no option to dock appears at all. I have moved the dock around, lowered it, raised it and nothing. I have had several people on the offcial discord check this out too and no one can figure out why the shuttle will not dock, its not the shuttle at fault either as several new shuttles have been made in an attempt to get a dock and all have failed, even pulling shuttles from other subs that will fit do not get the option to dock even though the option to undock is always present and working when needed

**Steps To Reproduce**
not sure if its reproduceable

**Version**
0.9.0.7

**Additional information**

**Comment by Regalis11** [comment] 2019-07-11 12:34
This seems to be caused by a flaw in the way the game determines the orientation of the docking ports. The port in the submarine is above the center of the submarine, so the game interprets it as being a port you dock to from the above. I'll need to change the logic a bit to fix that for the next patch, but for the time being, you could work around the issue by moving the port a little lower, something like this:

![sdgsdfg45](https://user-images.githubusercontent.com/14351070/61051288-57faa280-a3f1-11e9-8b3a-72d002dd916e.png)

**Comment by Regalis11** [comment] 2019-07-11 13:13
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5098fa552d0b62b6ca87c9272c7d3623cb4d40fd (private repo)

**Comment by Rokvach** [comment] 2019-08-08 21:37
Tested, working correctly. Closing.

**Closed by Rokvach** 2019-08-08 21:37 UTC
Labels: Bug, Code
