### ISSUE TITLE
Booted to menu with an error when attempting to spectate during a Campaign.

### ISSUE THREAD

**Issue by Potato-Masher** [Regalis11/Barotrauma#3636] opened 2020-08-26 01:04 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Attempted to spectate after connecting, results in a freeze frame of the sub followed by being sent to the main menu with an error in the console. Log included.

**Version**
Windows v0.10.4.0

**Additional information**
[crashreport_object.log](https://github.com/Regalis11/Barotrauma/files/5126959/crashreport_object.log)

**Comment by Regalis11** [comment] 2020-08-26 10:34
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3019

**Closed by Regalis11** 2020-08-26 10:34 UTC
