### ISSUE TITLE
[0.15.15.0] Multiplayer CTD after leaving the outpost (Collection was modified in Submarine.GetEntities)

### ISSUE THREAD

**Issue by taurviz** [Regalis11/Barotrauma#7373] opened 2021-11-18 16:40 UTC
**Description**
I got a CTD during MP when leaving the outpost. Details in crashreport log generated.

[crashreport.log](https://github.com/Regalis11/Barotrauma/files/7564850/crashreport.log)
**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using 
Windows 10 Home x64

**Additional information**

**Comment by Rokvach** [comment] 2022-04-27 08:46
The crash hasn't appeared in GA since we released the hotfix Unstable build to the community, previously the crash was seen fairly commonly. I also wasn't able to reproduce the issue with the provided steps, so working correctly. Closing.

**Closed by Rokvach** 2022-04-27 08:46 UTC
Labels: Bug, Code, Crash, Unstable
