### ISSUE TITLE
Parts of main menu UI invisible until a visible part has been interacted with

### ISSUE THREAD

**Issue by maxrothman** [Regalis11/Barotrauma#5722] opened 2021-05-08 22:41 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

https://user-images.githubusercontent.com/2607086/117555333-540b2c00-b02c-11eb-92a1-403fad3a955c.mov

**Steps To Reproduce**
- Launch the game. This happens consistently on my computer.

**Version**
- Barotrauma: v0.13.3.11 (ReleaseMac, branch release, revision 7096536cf1)
- OS: MacOS 10.15.7
- Hardward: Macbook Pro (Retina, 15-inch, Mid 2015)
- Graphics: Intel Iris Pro 1536 MB

**Comment by juanjp600** [comment] 2021-06-22 01:56
Duplicate of #5597

**Closed by juanjp600** 2021-06-22 01:56 UTC
Labels: Bug, Code, Mac only
