### ISSUE TITLE
Copying object/items in the Sub Editor doesn't copy it's contents when you paste it

### ISSUE THREAD

**Issue by EricPfau** [Regalis11/Barotrauma#4166] opened 2020-10-30 02:14 UTC
- [Y] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Copy pasting an item in the sub editor does not copy its contents over.

**Steps To Reproduce**
Place any container. Put any object in that container. Try to copy and paste the container. Observe that the pasted container has an empty inventory.

**Version**
10.6.2

**Additional information**
This bug was already reported but the topic was closed. The issue has not been fixed.
https://github.com/Regalis11/Barotrauma/issues/4080

**Comment by 3e849f2e5c** [comment] 2020-10-30 09:20
Duplicate of #4080

I can assure you this is the same issue and it has been fixed and tested but it was left out of the update because of how late it was discovered and fixed in the development life cycle. It it included on the current unstable version however.

**Closed by 3e849f2e5c** 2020-10-30 09:20 UTC
