### ISSUE TITLE
Crash when pressing 'CLOSE' in the 'LEAVING FROM COLONY' menu

### ISSUE THREAD

**Issue by stamparkour** [Regalis11/Barotrauma#5815] opened 2021-05-16 23:07 UTC
Don't know if this was reported before.

**Steps To Reproduce**
I don't really know, but I was clicking the close button on a menu that said something like "HUMPBACK IS LEAVINNG FROM VERSAS CITY." Maybe I clicked the close button really quickly or something. I had a transport mission at the starting colony

**Version**
Windows,  0.13.3.11

**Additional information**
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/6490205/crashreport.log)

**Comment by ekqvist** [comment] 2021-05-18 09:54
Unfortunately, I wasn't able to reproduce the issue. Is this the only time you have encountered this issue or have you faced it before? The crash seemed to have something to do with the command interface logic. I added a small failsafe in Regalis11/Barotrauma-development@8153b35 to prevent the game from crashing in this specific scenario and instead just disable the command interface, but I'm still unsure what the root cause is.

**Comment by stamparkour** [comment] 2021-05-24 14:14
this is the only time I faced this crash.

**Comment by ekqvist** [comment] 2021-06-07 08:12
No steps to reproduce and hasn't been encountered since. Closing.

**Closed by ekqvist** 2021-06-07 08:12 UTC
Labels: Bug, Code, Crash, Need more info
