### ISSUE TITLE
Cannot run multiplayer campaign in dedicated server (Again)

### ISSUE THREAD

**Issue by Neouni** [Regalis11/Barotrauma#1811] opened 2019-09-09 14:17 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

Basically, see 1564 as it's an exact replica of what is still happening.

On a freshly setup server it throws the error.
While it still generates the file but still complains heavily.
Have not tried to run the campagin while that console gets flooded with errors.

(After switching back to mission the players will be slightly desynced and can't see new players that joined in the lobby but can still see them in the game, but that is a totally different desync issue.)

#1521
#1564
#1576

**Comment by Regalis11** [comment] 2019-09-10 19:31
It seems the issue wasn't resolved after all, or a similar issue is caused by something else as well. I unfortunately haven't been able to reproduce this after the fixes in v0.9.0.7. 

If possible, could you provide us with some extra info to make diagnosing this easier; Which version of the game are you using, and on which operating system? By dedicated server, do you mean the dedicated server executable that comes included with the game, or the separate dedicated server app you can install via SteamCMD?

>"While it still generates the file but still complains heavily."
Which file does it generate and where? Is the error message exactly the same as in #1564, "File transfer failed(Wrong file extension ""!(Expected .save))"?

These details might give us some more clues as to what is causing this. Sorry for the trouble!

**Comment by Regalis11** [comment] 2019-09-11 09:25
Ah, managed to reproduce this now! It happens because the server uses the provided campaign save name as-is, without the required ".save" file extension. You should be able to work around the problem by adding that extension manually, i.e. when setting up the campaign through the server console, enter something like "MyCampaign.save" as the name of the save file.

**Comment by Regalis11** [comment] 2019-09-11 09:34
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6c93b03 (private repo)

**Comment by Rokvach** [comment] 2019-10-26 17:05
Seems to be working correctly now, closing.

**Closed by Rokvach** 2019-10-26 17:05 UTC
Labels: Bug, Code, High prio
