### ISSUE TITLE
[0.9.903] Missing Entities

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2599] opened 2020-04-10 00:13 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Happens anywhere from round start. spectating mid round, kicked mid round, and rejoining mid round.
[Serverlogs.zip](https://github.com/Regalis11/Barotrauma/files/4459186/Serverlogs.zip)

**Version**
0.9.903

**Comment by Regalis11** [comment] 2020-04-12 15:42
Duplicate of #2382

**Closed by Regalis11** 2020-04-12 15:42 UTC
