### ISSUE TITLE
Barotrauma makes my screen driver glitch out.

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#548] opened 2018-07-30 16:57 UTC
This technical issue caused me to stop playing barotrauma until this gets fixed. My screen driver on my PC is becoming glitchy or it's even taking minor damage, while i'm launching the game. Since I was trained to know how to fix screen driver if it had to get broken I came out of it, but I think now everybody knows how to do that and maybe that's the reason less people play barotrauma over time.

**Comment by rico6822** [comment] 2018-07-30 19:16
Well I basically launch my game using Windows 7 and every time I check my GPU due to my computer suspicious behaviour my screen driver is receiving greater chance to break the game and it was always receiving it, after playing barotrauma. I have judged the game to be damaging my screen driver. I'm fixing that by restarting the driver.

**Comment by Regalis11** [comment] 2018-07-30 19:24
I still don't understand, how do you determine that the "screen driver is receiving greater chance to break"? What kind of suspicious behavior do you mean?

**Comment by rico6822** [comment] 2018-07-30 19:34
Simply after I play barotrauma and I go watch something on youtube or in google graphics my screen breaks various amount of time later after that or even holds it to the next day.

**Comment by thegrb93** [comment] 2018-08-01 16:39
I think it's a problem with your computer.

**Comment by NilanthAnimosus** [comment] 2018-08-03 02:46
This sounds more like your GPU is failing than a fault of barotrauma, and eventually would simply start to fail on other things.

That or you are experiencing screen tearing. the description (The depth of it) you have provided literally gives us absolutely nothing to work with, or to understand your problem.

this is akin to saying "It is damaging my graphics" "Because I know it is" "Google told me" without telling us the symptoms, how it looks, what its doing, you have not told us what you know, this is extremely unhelpful to leave out any actual detail.

If I am to understand what you have said though, the game keeps its visual on your computers/laptops monitor even after it is gone/closed, either in the gpu visibly or literally as a form of screen image burn in. it also requires restarting the driver to correct than simply not running the game for awhile so not a literal image burn in but staying in the graphics memory as a frame long after the games closed (??).

Please could you at least describe the visible glitching in more detail, what you search on google, perhaps even the threads you have read - something to help us understand what it could be.

For now though, out of hundreds of players, I have heard of nobody having graphical glitches with barotrauma, it is likely confined to your computer and its hardware, or is even just your computers hardware failing I am afraid.

The only thing that could be suggested is to update your graphics hardware and see if the graphical glitching goes away, if its a laptop perhaps giving it a clean in case it is a form of overheating too.

**Comment by Regalis11** [comment] 2018-08-06 13:56
I have to agree with NilanthAnimosus, it sounds like an issue with your GPU, not the game. It might be possible that your GPU is starting to fail and the amount of strain caused by Barotrauma makes the problem worse, but even in that case it's a problem with your hardware.

Without further information I don't think I can do anything about this, so I'm closing it for now. If you can provide some more information that could help diagnosing the cause I'll reopen it.

**Closed by Regalis11** 2018-08-06 13:56 UTC
Labels: Graphics-related, bug, need more info
