### ISSUE TITLE
Visual Bug

### ISSUE THREAD

**Issue by VincentVanetti** [Regalis11/Barotrauma#10807] opened 2022-12-24 07:25 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

visual bug 
![Barotrauma_svimvOeL9U](https://user-images.githubusercontent.com/121333087/209425189-a07614dd-9f90-4fa7-8cf9-a0e1cd343e2b.png)

### Bug prevalence

Just once

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-12-25 12:12
Seems to be a duplicate of https://github.com/Regalis11/Barotrauma/issues/10580, I'll reopen that one and close this

**Closed by Regalis11** 2022-12-25 12:12 UTC
