### ISSUE TITLE
[0.9.8.0] Bots - Does not fight back intruders when attacked despite carrying weapons

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2493] opened 2020-03-26 13:32 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots does not fight back intruders when attacked despite carrying weapons on their inventory for self defense. They will flee from them even if they were continuously bitten until death.

**Version**
0.9.8.0

**Comment by itchyOwl** [comment] 2020-04-14 16:58
Can't reproduce. Which weapons did the bots have? Did they have any orders?

**Comment by Kaillera** [comment] 2020-04-14 17:43
Any orders other than fight hostiles. I usually have them a stun baton and any military weapons. This was during 0.9.8 though.

**Comment by itchyOwl** [comment] 2020-04-14 18:47
Ah, probably doesn't apply on the current version. There was a bad issue that was slipped in the release build of 0.9.8.0. Please inform us if this happens in the unstable/next release.

**Comment by Rokvach** [comment] 2020-04-14 20:33
I haven't noticed any issues of bots not fighting back in my tests, closing.

**Closed by Rokvach** 2020-04-14 20:33 UTC
Labels: Bug, Code, Need more info
