### ISSUE TITLE
Another Weapon Holder Layering Issue

### ISSUE THREAD

**Issue by mrjpjr** [Regalis11/Barotrauma#2724] opened 2020-04-27 15:17 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If the weapon holder's sprite depth is set to 0.840 or lower, any item in the weapon holder appears behind it.

**Steps To Reproduce**
1) Place a weapon holder with a weapon in it.
2) Change the sprite depth of the weapon holder to a value of 0.840 or less (for example 0.8, 0.750) 

**Version**
0.991 Unstable (Release windows, branch release, revision 1968ab79f)
Windows 10

**Additional information**
preview image:
https://cdn.discordapp.com/attachments/587647684794515468/704317776822796379/unknown.png

**Comment by Regalis11** [comment] 2020-07-09 11:10
Seems to have been caused by the same bug as https://github.com/Regalis11/Barotrauma/issues/3254, should be fixed now

**Comment by Rokvach** [comment] 2020-07-09 11:59
No issues, closing.

**Closed by Rokvach** 2020-07-09 11:59 UTC
Labels: Bug, Code
