### ISSUE TITLE
Inventary overlapping

### ISSUE THREAD

**Issue by Is0ndr** [Regalis11/Barotrauma#12463] opened 2023-08-03 17:53 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Inventory of my charachter always overlaps inventory of body\bot im grabbing
![baroscreenshot](https://github.com/Regalis11/Barotrauma/assets/141358160/c79cba99-6d23-488e-8399-cdfb26f710ce)

### Reproduction steps

works everywhere. in multiplayer/singleplayer. no matter which crew charachter im playin`

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by FaIIanor** [comment] 2023-08-06 12:12
This might probably happend if you have a small monitor or low resolution

**Comment by Regalis11** [comment] 2023-08-06 13:05
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11482

**Closed by Regalis11** 2023-08-06 13:05 UTC
