### ISSUE TITLE
Escorted NPCs will try to swim to exit when we are attacked

### ISSUE THREAD

**Issue by Mabons** [Regalis11/Barotrauma#13266] opened 2024-01-05 11:00 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This has happened several times now, with various NPC escort types (Clown, Coalition, Husk etc.).

Essentially, as soon as we are attacked and a hull breached, the NPCs correctly find a diving suit to put on, but 1 (and AFAIK only ever 1) will exit via airlock and start to swim to the exit outpost. Curiously, as we were using Barsuk, we could scoop them up into the airlock and get them back onboard, and they would go back to normal.

### Reproduction steps

1. Have escort mission
2. Recieve hull breach from creature attack(may also happen if captain is clumsy and hits something but I didn't have opportunity to see this yet)
3. Observe Escorted NPCs behaviour

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.2.7.0 (Winter Update hotfix)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2024-01-05 11:45
Duplicate of https://github.com/Regalis11/Barotrauma/issues/13187

**Closed by Regalis11** 2024-01-05 11:45 UTC
