### ISSUE TITLE
Bug with new parametr for turrets (Auto operate)

### ISSUE THREAD

**Issue by NamelessCaptain** [Regalis11/Barotrauma#11717] opened 2023-04-02 13:44 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

During the creation of the submarine, I decided to use the parameter Auto operate for the turrets . And hapened next : turrets can shoot without energy (if they work themselves), but if you try it yourself, then everything works fine .

### Reproduction steps

Turrets shoot without energy only when the parameter Auto operate is working , that is , they do not check whether there is energy or not . If you shoot through a periscope , then they check it

### Bug prevalence

Just once

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-04-02 15:53
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11507

**Closed by Regalis11** 2023-04-02 15:53 UTC
