### ISSUE TITLE
Wacky Ragdoll While Playing Harmonica

### ISSUE THREAD

**Issue by Lithosagym** [Regalis11/Barotrauma#3279] opened 2020-07-03 02:11 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
A Harmonica is held with one hand and played with two hands, and so when you ragdoll and try playing it, the other hand tries to hold the harmonica which causes some wacky and funny ragdoll physics.

**Steps To Reproduce**
Play a harmonica and ragdoll while still holding the buttons for playing it.

**Version**
Windows
0.10.1.0

**Comment by Regalis11** [comment] 2020-07-03 10:56
Could not reproduce. Holding RMB seems to do nothing while you're ragdolled.

**Comment by Rokvach** [comment] 2020-07-03 11:11
You need to be holding both LMB and RMB when ragdolling as in playing the instrument

The same can be done with any instrument as it tries to play the instrument playing animation while your character ragdolls. If I remember right it can also be done when unconscious, but I might be wrong on that one. @Regalis11

**Comment by Regalis11** [comment] 2020-07-03 13:19
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a321811d7f3c3a1cf154d2d1d2ad32a23bea6858

**Comment by Rokvach** [comment] 2020-07-03 15:16
Confirmed working, closing.

**Closed by Rokvach** 2020-07-03 15:16 UTC
Labels: Bug, Code
