### ISSUE TITLE
A terrible bug

### ISSUE THREAD

**Issue by David2583** [Regalis11/Barotrauma#2768] opened 2020-05-04 19:36 UTC
When I start a new campaign load saves or open servers Barotrauma crashes that's why I can't play

[crashreport (11).log](https://github.com/Regalis11/Barotrauma/files/4576976/crashreport.11.log)

This bug was detected on version 0.9.9.1 on Windows

**Comment by Regalis11** [comment] 2020-05-05 06:46
Duplicate of #2747

It seems the game fails to open an audio device for some reason, and crashes when it tries to play the water ambience sounds. Do you have some kind of audio device (headset, speakers) connected? If not, connecting one should get rid of this error. But in any case, we need to also make sure the game doesn't crash even if there is no audio device present.

**Closed by Regalis11** 2020-05-05 06:46 UTC
