### ISSUE TITLE
[0.1000.0.0] Putting Railgun Shells on top of the top docking port hatch, and then opening it causes them to vanish

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2926] opened 2020-05-30 00:19 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Putting Railgun Shells on top of the top docking port hatch, and then opening it causes them to vanish.

![Capture](https://user-images.githubusercontent.com/5086682/83314666-8d66d500-a1e9-11ea-9ddf-4414826b6feb.PNG)
![Capture](https://user-images.githubusercontent.com/5086682/83314681-a1123b80-a1e9-11ea-862f-9c5c63e09235.PNG)

**Version**
0.1000.0.0

**Comment by mrjpjr** [comment] 2020-05-30 11:22
I encountered something similar to this, in one of the release versions, where I had items from the wreck (ammo boxes, railgun shells) right above the docking hatch. When I docked, they all disappeared.

**Comment by Regalis11** [comment] 2020-08-25 10:18
Could not reproduce, opening the hatch doesn't seem to have any effect on the shells.

**Comment by Regalis11** [comment] 2020-10-26 16:44
No known steps to repro, closing

**Closed by Regalis11** 2020-10-26 16:44 UTC
Labels: Bug, Code, Need more info
