### ISSUE TITLE
Many Devices Appear Damaged or Smoking In Multiplayer But Are Actually Fine

### ISSUE THREAD

**Issue by gerakis** [Regalis11/Barotrauma#7652] opened 2021-12-06 22:10 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Many devices like junction boxes, supercapacitors ect look like they are smoking and very badly damaged, but cannot be repaired and seem to be working just fine. According to the people on the server I was on, its because now that its possible to repair to 140% it causes people who dont have that talent to see the devices as broken. The people with the talent don't see anything wrong.

**Steps To Reproduce**
Just play a multiplayer round for a while, you will see it. Ive seen it a ton. Ive never seen this in single player.

**Version**
V0.15.13.0 Windows 10 x64

**Additional information**
This might be the same bug as #7085 and #7436, but their devices seemed to actually be broken. These devices were totally fine and working. Also according to the players it had nothing to do with buying the durability upgrades.

I took a video of it:
https://youtu.be/YLlXnbibhTk

**Comment by Regalis11** [comment] 2021-12-07 09:10
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7085

**Closed by Regalis11** 2021-12-07 09:10 UTC
