### ISSUE TITLE
Monsters not randomly spawning in levels

### ISSUE THREAD

**Issue by aeondez** [Regalis11/Barotrauma#6137] opened 2021-06-21 04:30 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Monsters not randomly spawning in levels. 

**Steps To Reproduce**
Try playing it, and note that you will not see any monsters outside the monsters for certain missions such as nests or defeat hammerheads, etc (and ballast flora, since I guess those aren't monsters?) We still get monsters for beacon stations as well. After 10+ missions, it seems really odd, even with ~15% difficulty that there are no randomly spawning monsters like there should be.

**Version**
0.14.6.0 (Windows)

**Additional information**
I attached my save file. We are using a few mods, but none affect monsters as far as I can tell.

Modlist:
AeonBeaconStations
Shipwrecks Extended
Meaningful CPR
Some custom subs (all built by me except the R-29 Hammerhead)

[Public.zip](https://github.com/Regalis11/Barotrauma/files/6684016/Public.zip)

**Comment by Regalis11** [comment] 2021-07-08 10:25
Seems to be caused by the same issue as https://github.com/regalis11/barotrauma/issues/6271

**Comment by Regalis11** [comment] 2021-07-08 10:44
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/588af7d08afd7586fc4f4366f6b63a6269581d9e

**Comment by Rokvach** [comment] 2021-07-27 10:06
Tested, working correctly. Closing.

**Closed by Rokvach** 2021-07-27 10:06 UTC
Labels: Bug, Code, Modding
