### ISSUE TITLE
Creatures sometimes kill instantly because of no attack delay (keywords: instakill, Mudraptor, Crawler)

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#7640] opened 2021-12-05 23:05 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Affected monsters: _at least_ Crawlers, Baby Crawlers, Mudraptors
https://cdn.discordapp.com/attachments/897564625271394374/904785968891035688/Mudraptor_Stronk1.mp4

**Version**
v0.15.13 and before but not in old versions(?)

**Comment by Regalis11** [comment] 2021-12-06 12:06
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7151

**Closed by Regalis11** 2021-12-06 12:06 UTC
