### ISSUE TITLE
[Unstable 0.1500.1.0] Crash always(as for me) when fabricate item

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#6598] opened 2021-09-06 09:15 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
i've tried many times, game always crash as long as clicking create button in the submarine.
![bug19](https://user-images.githubusercontent.com/73634685/132192314-81f4a195-dc8a-4d32-bc51-462a3e56ee17.png)

**CrashReport**
```
Game version 0.1500.1.0 (UnstableWindows, branch dev, revision 888c5e3298)
Graphics mode: 1366x768 (Windowed)
VSync ON
Language: Simplified Chinese
Selected content packages: Vanilla 0.9
Level seed: The BucketSet
Loaded submarine: Berilia (881339543AFE5264F6D01D8B1EE4DC7A)
Selected screen: Barotrauma.GameScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.19042.0 64 bit
    GPU name: Intel(R) UHD Graphics 620
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void OnItemContained(Barotrauma.Item)
Stack trace: 
   at Barotrauma.Items.Components.ItemContainer.OnItemContained(Item containedItem) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\ItemContainer.cs:line 292
   at Barotrauma.ItemInventory.TryPutItem(Item item, Character user, IEnumerable`1 allowedSlots, Boolean createNetworkEvent, Boolean ignoreCondition) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\ItemInventory.cs:line 105
   at Barotrauma.Items.Components.Fabricator.<>c__DisplayClass83_0.<MoveIngredientsToInputContainer>b__0(RequiredItem requiredItem) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Machines\Fabricator.cs:line 551
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.Items.Components.Fabricator.MoveIngredientsToInputContainer(FabricationRecipe targetItem) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Machines\Fabricator.cs:line 521
   at Barotrauma.Items.Components.Fabricator.StartFabricating(FabricationRecipe selectedItem, Character user, Boolean addToServerLog) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Machines\Fabricator.cs:line 189
   at Barotrauma.Items.Components.Fabricator.StartButtonClicked(GUIButton button, Object obj) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\Machines\Fabricator.cs:line 608
   at Barotrauma.GUIButton.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 262
   at Barotrauma.GUIComponent.UpdateAuto(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIComponent.cs:line 459
   at Barotrauma.GUI.<>c__DisplayClass158_0.<Update>b__0(GUIComponent c) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1246
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1246
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 1002
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59
```

**Comment by Regalis11** [comment] 2021-09-06 09:15
Duplicate of https://github.com/Regalis11/Barotrauma/issues/6549

**Closed by Regalis11** 2021-09-06 09:15 UTC
