### ISSUE TITLE
Killed Players Don't Disappear From The List in The Corner- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1982] opened 2020-01-11 05:55 UTC
Having them to disappear would hint everyone that that player is dead as well as it would explain why that player won't reply. I mean, this just damages suspense.

I'm talking about the list that causes profiles of characters in there to turn red and than disappear through vertical collapse if a character gets killed. 

If a dead player gets found dead it is still on the list. If the player respawns a new character won't appear on the list to avoid duplicating (duplicating itself hints death). Respawning also doesn't reset player's skills.

In single player mode it still has to happen as the player can simply switch between characters to check on them and if that would be implemented in there too I guess the player would nervously switch between crew during dangerous situations just to check if they are still alive.

**Comment by hubismal** [comment] 2020-01-11 16:53
just another heads up, this is a duplicate of something already requested i'm pretty sure, although it might have been closed in the mass-feature-request-closing of '19

**Comment by Regalis11** [comment] 2020-01-15 08:03
We're removing the crew list altogether and replacing it with a new type of a command interface, so this is not needed.

**Closed by Regalis11** 2020-01-15 08:03 UTC
