### ISSUE TITLE
[Unstable] Drunken Sailor uses the wrong affliction

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10404] opened 2022-11-15 00:33 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Drunken Sailor replaces "drunk" with "drunknodebuffs", but uses "drunk" as a condition to apply resistances

```xml
        <CharacterAbilityModifyAffliction afflictionidentifiers="drunk" replacewith="drunknodebuffs" />
      </FallbackAbilities>
    </AbilityGroupEffect>
    <AbilityGroupInterval>
      <Conditions>
        <AbilityConditionHasAffliction afflictionidentifier="drunk"/>
      </Conditions>
      <Abilities>
        <CharacterAbilityModifyResistance resistanceid="stun" resistance="0.75"/>
        <CharacterAbilityModifyResistance resistanceid="nausea" resistance="1"/>
      </Abilities>
    </AbilityGroupInterval>
```

Could also be a side effect of https://github.com/Regalis11/Barotrauma/issues/10403

### Version

0.20.6.0 (Unstable)

**Comment by 3e849f2e5c** [comment] 2022-11-15 11:23
Was unable to reproduce, the resistance seems to still apply correctly when using drunk as the identifier

**Comment by ubertpendragon** [comment] 2022-11-15 11:53
If you gave yourself Drunk via console you'll get the effects as it doesn't turn "Drunk" into "drunknodebuffs"

I tested with `resistanceid="stun" resistance="0.1"/>`, if you drink Rum you don't benefit from the effect, if you use console it works

Both resistance values also need to be changed, related to 
https://github.com/Regalis11/Barotrauma/issues/10403

**Comment by 3e849f2e5c** [comment] 2022-11-15 12:58
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b2be5127e20b3691e971a0cf8bbfe036f0a7b15d

**Comment by Rokvach** [comment] 2022-11-23 13:11
Tested, working correctly. Closing.

**Closed by Rokvach** 2022-11-23 13:11 UTC
Labels: Bug, Code, Unstable
