### ISSUE TITLE
Crash when a bot was welding (TextManager.HandleVariableCapitalization)

### ISSUE THREAD

**Issue by chawley9** [Regalis11/Barotrauma#3998] opened 2020-10-04 19:14 UTC
No mods installed.
on a mission to kill two hammerheads.
half way through the mission, not found the hammerheads yet, bumped into a wall and the game crashed.

Barotrauma Client crash report (generated on 04/10/2020 20:12:21)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

6F558E05A9FD96EA104348A23A5B582A

Game version 0.10.5.1 (ReleaseWindows, branch release, revision 9e259b2148)
Graphics mode: 1920x1080 (Fullscreen)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: AnnwnMolovsk
Loaded submarine: HMS Endeavor Mk IV (C08B83E166F4A501DA43605386D3A9A0)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19041.0 64 bit
    GPU name: NVIDIA GeForce GTX 1070 Ti
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: System.String HandleVariableCapitalization(System.String, System.String, System.String)
Stack trace: 
   at Barotrauma.TextManager.HandleVariableCapitalization(String text, String variableTag, String variableValue) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\TextManager.cs:line 370
   at Barotrauma.TextManager.GetWithVariable(String textTag, String variableTag, String variableValue, Boolean formatCapitals, Boolean returnNull, String fallBackTag) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\TextManager.cs:line 332
   at Barotrauma.Items.Components.RepairTool.AIOperate(Single deltaTime, Character character, AIObjectiveOperateItem objective) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Holdable\RepairTool.cs:line 0
   at Barotrauma.AIObjectiveOperateItem.Act(Single deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjectiveOperateItem.cs:line 249
   at Barotrauma.AIObjective.TryComplete(Single deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjective.cs:line 130
   at Barotrauma.AIObjective.TryComplete(Single deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjective.cs:line 130
   at Barotrauma.HumanAIController.Update(Single deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\HumanAIController.cs:line 231
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2230
   at Barotrauma.GameScreen.Update(Double deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 171
   at Barotrauma.GameMain.Update(GameTime gameTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 921
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[04/10/2020 20:05:44] Generating an outpost for the start of the level... (Location: Annwn Fortification, level type: LocationConnection)
[04/10/2020 20:05:43] Generating an outpost for the end of the level... (Location: Molovsk Habitation Outpost, level type: LocationConnection)
[04/10/2020 20:00:46] Generating an outpost for the end of the level... (Location: The city of Skadi's Cauldron, level type: LocationConnection)
[04/10/2020 20:00:45] Generating an outpost for the start of the level... (Location: Pastonia, level type: LocationConnection)
[04/10/2020 20:00:34] Transitioning to PastoniaSkadi's Cauldron (current location: Pastonia, selected location: The city of Skadi's Cauldron, leaving sub: HMS Endeavor Mk IV, at start: True, at end: False, transition type: LeaveLocation)
[04/10/2020 19:54:02] Generating an outpost for the start of the level... (Location: Pastonia, level type: Outpost)
[04/10/2020 19:53:52] Transitioning to Pastonia (current location: The city of Shinkonai, selected location: Pastonia, leaving sub: HMS Endeavor Mk IV, at start: False, at end: True, transition type: ProgressToNextLocation)
[04/10/2020 19:34:48] Generating an outpost for the end of the level... (Location: Pastonia, level type: LocationConnection)
[04/10/2020 19:34:47] Generating an outpost for the start of the level... (Location: The city of Shinkonai, level type: LocationConnection)
[04/10/2020 19:34:34] Transitioning to ShinkonaiPastonia (current location: The city of Shinkonai, selected location: Pastonia, leaving sub: HMS Endeavor Mk IV, at start: True, at end: False, transition type: LeaveLocation)
[04/10/2020 19:27:53] Generating an outpost for the start of the level... (Location: The city of Shinkonai, level type: Outpost)
[04/10/2020 19:17:08] (Msg) RelayNetWorkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[04/10/2020 19:17:08] (Msg) Ping location: lhr=7+0,ams=12+1/12+0,par=14+1,fra=20+2/18+1,lux=25+2/19+1,vie=31+3/28+1,mad=29+2,sto2=38+3/31+0,sto=34+3/32+0,iad=79+7,sgp=161+16/162+16,gru=218+21/223+7
[04/10/2020 19:17:08] (Msg) Ping measurement completed
[04/10/2020 19:17:07] (Verbose) Communications with routing cluster 'sto2' established.
[04/10/2020 19:17:07] (Debug) Destroying relay 'sto2#172 (155.133.252.38:27040)' because initial_ping_timeout
[04/10/2020 19:17:04] (Debug) Destroying relay 'sto2#28 (155.133.252.35:27042)' because initial_ping_timeout
[04/10/2020 19:17:04] (Verbose) Communications with routing cluster 'ord' established.
[04/10/2020 19:17:04] (Debug) Destroying relay 'ord#109 (162.254.193.73:27039)' because initial_ping_timeout
[04/10/2020 19:17:02] (Verbose) Communications with routing cluster 'syd' established.
[04/10/2020 19:17:02] (Verbose) Communications with routing cluster 'tyo1' established.
[04/10/2020 19:17:02] (Verbose) Communications with routing cluster 'tyo' established.
[04/10/2020 19:17:02] (Verbose) Communications with routing cluster 'sgp' established.
[04/10/2020 19:17:02] (Verbose) Communications with routing cluster 'sea' established.
[04/10/2020 19:17:02] (Verbose) Communications with routing cluster 'scl' established.
[04/10/2020 19:17:02] (Verbose) Communications with routing cluster 'lim' established.
[04/10/2020 19:17:02] (Verbose) Communications with routing cluster 'hkg' established.
[04/10/2020 19:17:02] (Verbose) Communications with routing cluster 'maa' established.
[04/10/2020 19:17:02] (Verbose) Communications with routing cluster 'waw' established.
[04/10/2020 19:17:02] (Verbose) Communications with routing cluster 'lax' established.
[04/10/2020 19:17:02] (Verbose) Communications with routing cluster 'sto' established.
[04/10/2020 19:17:02] (Verbose) Communications with routing cluster 'vie' established.
[04/10/2020 19:17:02] (Verbose) Communications with routing cluster 'gru' established.
[04/10/2020 19:17:02] (Verbose) Communications with routing cluster 'okc' established.
[04/10/2020 19:17:02] (Verbose) Communications with routing cluster 'jnb' established.
[04/10/2020 19:17:02] (Verbose) Communications with routing cluster 'eat' established.
[04/10/2020 19:17:02] (Verbose) Communications with routing cluster 'bom' established.
[04/10/2020 19:17:02] (Verbose) Communications with routing cluster 'mad' established.
[04/10/2020 19:17:02] (Verbose) Communications with routing cluster 'dxb' established.
[04/10/2020 19:17:02] (Verbose) Communications with routing cluster 'lux' established.
[04/10/2020 19:17:02] (Verbose) Communications with routing cluster 'par' established.
[04/10/2020 19:17:02] (Verbose) Communications with routing cluster 'lhr' established.
[04/10/2020 19:17:02] (Verbose) Communications with routing cluster 'atl' established.
[04/10/2020 19:17:02] (Verbose) Communications with routing cluster 'iad' established.
[04/10/2020 19:17:02] (Verbose) Communications with routing cluster 'fra' established.
[04/10/2020 19:17:02] (Verbose) Communications with routing cluster 'ams' established.
[04/10/2020 19:17:02] (Msg) RelayNetWorkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[04/10/2020 19:17:02] (Msg) Performing ping measurement
[04/10/2020 19:17:02] (Msg) Got SDR network config.  Loaded revision 282 OK
[04/10/2020 19:17:01] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[04/10/2020 19:16:49] Attempting to open ALC device "OpenAL Soft on Speakers (High Definition Audio Device)"
[04/10/2020 19:16:47] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[04/10/2020 19:16:47] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[04/10/2020 19:16:44] Logged in as Chawley (SteamID STEAM_1:0:44690007)

**Comment by Regalis11** [comment] 2020-10-05 07:37
I wasn't able to reproduce this, but I suspect it happened when a bot repaired a wall in a room that doesn't have a name configured. If that was the cause, should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/1347a78002101a0ed00656332692d6ea47c93696

**Comment by Rokvach** [comment] 2020-10-08 08:23
Tested by removing room names from hulls and asking a bot to fix leaks in those rooms, didn't cause any issues. So if the issue was caused by it then this should be working correctly. Closing.

**Closed by Rokvach** 2020-10-08 08:23 UTC
Labels: Bug, Code, Crash
