### ISSUE TITLE
Hotbar interrupting using tools and weapons when moused over

### ISSUE THREAD

**Issue by PokkeTigrex** [Regalis11/Barotrauma#12115] opened 2023-06-04 01:54 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Using tools/weapons while hovering over the hotbar interrupts it. This is the same bug I reported in the early access (#6908) that had been fixed, but something in the recent updates must have reverted it or broke it again, primarily affecting hotbar elements this time around.

### Reproduction steps

Use something like a scooter or welder and "shoot" with it, then mouse over the hotbar.

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment] 2023-06-07 15:03
Repro steps confirmed.

**Comment by Regalis11** [comment] 2023-06-29 16:18
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1be9eaaf46f38148db21087f2e844818fc1fbfa7

Seems to have been caused by the fix for https://github.com/Regalis11/Barotrauma/issues/11134, which was intended to prevent accidentally triggering flares by clicking on the inventory.

**Comment by itchyOwl** [comment] 2023-08-08 12:16
Tested: seems to fixed now. Didn't re-test that #11134: QA should do that.

**Closed** 2023-08-14 07:29 UTC
Labels: Bug, Code
