### ISSUE TITLE
Headset-to-WiFi Voice Activation Inconsistent

### ISSUE THREAD

**Issue by BluntTongs** [Regalis11/Barotrauma#1700] opened 2019-06-23 02:30 UTC
**Description**
Headsets appear to behave differently in different game modes when it comes to how they interact with WiFi components - mostly relevant for voice-activation functionality. For example, in a Combat mission, the headsets a crewmember spawns in with function perfectly with a regex-enabled voice-activated mechanism, as do any headsets pre-placed on the submarine at the beginning of the round, but headsets crafted at a Fabricator during the round notably _do not_ enable this mechanism. 
This quirk is demonstrated in [this locally-hosted Combat mode video.](https://www.youtube.com/watch?v=aIBW1oP3Xa8&feature=youtu.be) (More information in the description.)

On the opposing side, any game mode _excluding_ Combat (and including Campaign) has the headsets you spawn in with lacking in this functionality. Headsets that are manufactured during the round(s) work as expected, as showcased in the above video near the end. Headsets that have been pre-placed on the sub at round start also work as anticipated, making them consistent throughout gameplay.
These quirks are demonstrated in [this locally-hosted Sandbox video.](https://www.youtube.com/watch?v=PWM5WONYHlY&feature=youtu.be)
As an aside, another user reported that they were unable to _receive_ messages from Memory Components via WiFi chat linkage in _Single Player_, although they could broadcast and the command go through just fine.

**Steps To Reproduce**

1. Begin a locally hosted multiplayer Sandbox round on a submarine with at least one pre-placed headset, a deconstructor, a fabricator, and a mechanism with voice functionality, e.g. a WiFi component set to channel 1 --> regex `Signal_in` with the expression `[Bb]atten.*` , Output `1`, False Output empty --> Signal Check Component `Signal_in`, Output `0`, False Output empty, Target Signal `1` --> Any custom door or hatch's `Set_state`. This will, upon speaking the phrase "Batten" into the headset, close any **already open** door that the Signal Check Component is connected to.
2. Attempt to communicate to sub using the "Batten" voice command using the "stock" headset that your character spawns in with. Ensure you're speaking using r; and that the door you're testing on is already toggled opened. Note results; does the door close?
3. Remove battery from "stock" headset, drop "stock" headset on ground, and pick up your pre-placed headset you set down in the sub editor. Insert battery into pre-placed headset, equip headset, and attempt "Batten" command again, as before. Note results.
4. Remove battery from pre-placed headset and deconstruct headset. Use components from old headset to construct a new headset at the fabricator. Insert battery into manufactured headset and equip, once again attempting the "Batten" command. Note results.
5. Repeat steps 1-4 in the Combat gamemode as either Renegade or Coalition and, again, note results from each test. Ideally every result should be congruent with what I've gathered. If necessary, also test in Campaign or any non-Combat mission.

**Version**
Barotrauma v0.9.0.6
Windows 7 Ultimate

**Comment by Regalis11** [comment] 2019-09-17 12:32
Looks like this got fixed as a side-effect of https://github.com/Regalis11/Barotrauma-development/commit/910351b6

Seems to be working in the current release version, should be verified by QA

**Comment by Rokvach** [comment] 2019-10-11 19:32
Headset-to-Wifi confirmed working correctly. Closing.

**Closed by Rokvach** 2019-10-11 19:32 UTC
Labels: Bug, Code
