### ISSUE TITLE
Railgun drains supercapacitors it is not directly connected to, only via another railgun.

### ISSUE THREAD

**Issue by esirprus** [Regalis11/Barotrauma#9195] opened 2022-05-22 14:15 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://user-images.githubusercontent.com/44423036/169699295-8cbbb6fd-ce8e-4b91-8eb0-5eb61b8b67f8.png)
See turret A, when it fire, both two supercapacitor simultaneous energy supply, this seems strange. Turret B C D E and their supercapacitor working properly.

### Reproduction steps

[supercapacitor bug.zip](https://github.com/Regalis11/Barotrauma/files/8749614/supercapacitor.bug.zip)
Use this to check what I say!

### Bug prevalence

Happens every time I play

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by mygamingaccount** [comment] 2022-05-22 15:24
## Railgun drains supercapacitor it is not directly connected to, only via another railgun

I wonder if you can extend the zig-zag pattern over more railguns and capacitors.

**Comment by esirprus** [comment] 2022-05-22 23:15
> ## Railgun drains supercapacitors it is not directly connected to, only via another railgun
> I wonder if you can extend the zig-zag pattern over more railguns and capacitors.

yes the zig-zag pattern seems have the same problem.
![image](https://user-images.githubusercontent.com/44423036/169720219-cf0cb514-191e-4a5d-b7fa-7eaa3fb170f6.png)

**Comment by Regalis11** [comment] 2022-05-23 07:15
Duplicate of https://github.com/Regalis11/Barotrauma/issues/9194

**Closed by Regalis11** 2022-05-23 07:15 UTC
