### ISSUE TITLE
UI conflict with razer cortex overlay

### ISSUE THREAD

**Issue by 123oro321** [Regalis11/Barotrauma#9337] opened 2022-06-14 18:35 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Today when i booted the game i found out the main menu looked like this:
![image](https://user-images.githubusercontent.com/22895196/173663044-372077a9-a8f5-46f8-9c76-d80db268070f.png)
After some tinkering i discovered that the razer cortex overlay (recently updated) causes the problem, simply disabling it restarting the game makes it alright.
Honestly it's not too bothering and i managed to fix it quickly, but others should be made aware of it as they may not find the root of the problem as i did.

### Reproduction steps

1. Install razer cortex and enable the overly.
2. Boot the game.

### Bug prevalence

Just once

### Version

0.17.16.0

### Which operating system did you encounter this bug on?

Windows

**Comment by MaaiG** [comment] 2022-06-14 19:34
> [x] I have searched the issue tracker to check if the issue has already been reported.

https://github.com/Regalis11/Barotrauma/issues?q=razer+cortex 😛

**Comment by ekqvist** [comment] 2022-06-14 21:58
Duplicate of #9213. There should be a fix coming for this issue in the next update.

**Closed by ekqvist** 2022-06-14 21:58 UTC
