### ISSUE TITLE
Kastrull drone still creating AI/bot blackhole

### ISSUE THREAD

**Issue by dennzil** [Regalis11/Barotrauma#5716] opened 2021-05-07 11:18 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Previous bug of bots hanging around in the drone has reappeared. Tried leaving drone in a mission then repurchasing but they still go down the ladder. Bots can repair electrical items in drone but when tasked with repair mechanical devices they run back and forth around the ladder.

**Steps To Reproduce**
Use Kastrull sub
Put crew members on fix mechanical or general and wait for a component to need maintenance in the drone.

**Version**
Embrace the Abyss, windows 10

![kastrull drone bot pathfinding](https://user-images.githubusercontent.com/83429207/117441998-19bb6500-af2e-11eb-8188-7861ebc497cd.jpg)

**Comment by dennzil** [comment] 2021-05-07 19:00
I have just looked at the drone in submarine editor, somehow the lower pump deteriorated even though i think its set not to deteriorate.

The bots and I couldn't get to the pump to repair it without cutting through the shuttle wall, repairing it then welding the hull back up.

**Comment by the1eyedduck** [comment] 2021-06-04 01:04
After some testing (done in #5962), the problem was docking waypoint of the drone.

**Comment by itchyOwl** [comment] 2021-06-04 09:05
Tested both in the master branch (release version) and latest bugfixes. Can't repro. There's obviously an invalid waypoint (ID 155, marked red) in the picture shown in #5962, but the vanilla done doesn't have that:

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/3bec3453-299f-4047-92b5-c421fcedc62a)

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/437611e9-89d0-4176-a2b6-f1b7c018b29b)

When I marked the hulls as to be avoided, like suggested in #5962, I managed to get the bot stuck in the ladders. There's actually at least two things that can cause this. One happens occasionally and is yet unsolved. Another was caused by bots not being allowed to pass through those hulls in the idle state (didn't happen e.g. when the bot was following the player). This should be fixed in Regalis11/Barotrauma-development@22d9503 (pushed to dev, because it requires testing).

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/7b64b368-9362-475c-8a48-71b6b9261b82)

**Comment by the1eyedduck** [comment] 2021-06-04 09:13
the 1 mark in red is the original waypoint, just move to the side to show how low it is compare to the 1 i added in as a fix, i only tested in unstable so far

**Comment by Regalis11** [comment] 2021-06-04 09:54
> When I marked the hulls as to be avoided, like suggested in #5962, I managed to get the bot stuck in the ladders. There's actually at least two things that can cause this. One happens occasionally and is yet unsolved. 

The 2nd issue should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/1f4f87df4507bc9ea85a50a65e3a35a98e39b0ce

**Comment by itchyOwl** [comment] 2021-06-04 10:16
Ok, so you mean that it should be just rised a bit? I don't see how that would make any difference, as it's linked to the door (and the ladder) anyway. Please test it again in the unstable _after_ the next update, where those issues mentioned above should be fixed.

**Comment by Rokvach** [comment] 2021-06-07 08:00
Tested, I didn't spot any issues. Closing.

**Closed by Rokvach** 2021-06-07 08:00 UTC
Labels: Bug, Code
