### ISSUE TITLE
Russian translation for medic: English "or" instead of Russian "или"

### ISSUE THREAD

**Issue by SoNickRND** [Regalis11/Barotrauma#7294] opened 2021-11-13 14:27 UTC
Captain says in Russian:
"Мне требуется бинт, эластичный бинт, морфин or фентанил!"
Notice, there is an "or", it's not a Russian conjunction, but English. 
Russian one is "или".

**Comment by kubalakowski** [comment] 2021-11-14 19:03
I've also noticed it in polish version

I guess this is the cause

https://github.com/Regalis11/Barotrauma/blob/a49decc2edcf440c6a9f5dd3e1e08cda9bd8b790/Barotrauma/BarotraumaShared/SharedSource/Characters/AI/Objectives/AIObjectiveRescue.cs#L324

**Comment by Regalis11** [comment] 2021-11-15 10:50
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f41b1d60721b7982b83b52cb6a96efa7d1f09d91

**Comment by Rokvach** [comment] 2021-12-10 10:04
Will need to do another test on this once we get the localizations, but for now there wasn't any issues at least

**Comment by Rokvach** [comment] 2021-12-12 21:28
Tested, working correctly. Closing.

**Closed by Rokvach** 2021-12-12 21:28 UTC
Labels: Bug, Localization
