### ISSUE TITLE
[0.10.502~503] Workshop item not updating

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3760] opened 2020-09-07 17:59 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
So I was trying to update my custom submarine in 0.10.502~503, but I noticed that the file aren't updating. The custom sub is still the same one from 0.10.4. Not sure if it's a unstable problem.

**Version**
0.10.502~503

**Comment by Rokvach** [comment] 2020-09-28 14:02
No issues, closing.

**Closed by Rokvach** 2020-09-28 14:02 UTC
Labels: Bug, Code, Modding

**Comment by TheLizardman** [comment] 2021-01-04 21:40
I've run into this issue when attempting to update a Workshop sub. Refreshed the sub file using the workshop menu in Baro, I was subsequently made aware that nothing had changed with the file on the Workshop.

 I saw on the Undertow Discord that the issue was potentially was the sub being updated from the Workshop on returning to main menu and then being used as the file for upload to Steam. I can confirm this is what appears to have happened. Workaround was copying the sub file before returning to the main menu, then deleting the refreshed sub file when it appeared. Rename copied file to original name, then Workshop upload was the correct file.

It seems to be an intermittent bug as I uploaded prior versions of the sub to the workshop with no issue.

This is on v0.11.0.10

**Comment by Vaniloth** [comment] 2022-03-30 01:33
I'm writing this to confirm that this problem is still present.
I had no idea my sub wasn't being updated until a friend brought me into their game and showed me my wildly outdated sub.
I made 9 revisions after the initial publish (all made between March 9th, and March 26th, 2022), and not a single revision made it to the workshop.  I can view the revision notes and it's clear that even the contents of the first revision did not make it to the workshop.
The workaround is to delete all the contents of the item you're trying to publish, and manually re-add every item.  I figured the refresh button would do that for me, but using that button, or my expectations for that button, is what led my sub to become publicly outdated.
If the refresh button isn't supposed to grab the latest version of the files I'm uploading, please add some clarification in the game interface for what that button does.

Version v0.16.7.0
