### ISSUE TITLE
If you shoot an enemy and it does damage to a Slapstick Expert Clown you will get stunned

### ISSUE THREAD

**Issue by Bugfinder1** [Regalis11/Barotrauma#9464] opened 2022-06-26 17:11 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If you shoot lets say a spineling with any weapon, and it does damage to an assistant with the slapstick expert talent, your character will get stunned

### Reproduction steps

1.Start a game with an assistant and any other character
2.Give your assistant slapstick expert talent
3.Spawn a Spineling, or a moloch,
4.Ragdoll the assistant using console commands 
5.Shoot the enemy
6.Observe how your character gets stunned for "doing damage" to the clown

### Bug prevalence

Happens every now and then

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-06-27 10:39
Thank you for the report!

I'm afraid I could not reproduce this, although I'm not entirely sure I understood the steps to repro correctly. Do you mean that I need to first attack the spineling, and then have the spineling attack the assistant, or the other way around? The description you gave seems to suggest the former, and the steps to repro the latter? I gave both of those a test, but could not get this to happen.

**Comment by Bugfinder1** [comment] 2022-06-27 16:24
I meant that firstly you need to attack a spineling and then have the spineling attack the assistant, This happend to me when i was playing multiplayer with 14 people, so it might be just server lag counting it as my damage, well thanks for the reply.

**Comment by Regalis11** [comment] 2022-07-13 08:33
No known steps to repro, closing

**Closed by Regalis11** 2022-07-13 08:33 UTC
Labels: Bug, Need more info, Code
