### ISSUE TITLE
Bots - Stuck in Find Safety state when out of ammunition during a current Fight Intruders

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2786] opened 2020-05-07 14:48 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots get stuck in Find Safety state when out of ammunition during a current Fight Intruders. They won't switch to melee weapons. Requires to be reassigned to continue the fight.

**Version**
0.9.9.1

**Comment by ekqvist** [comment] 2020-09-10 12:25
I think this might have been fixed as a part of something else. I tried testing it on the `human-ai` branch by giving a bot a revolver with 1 round and a diving knife. They seemed to switch to the knife and continue fighting after firing the round.

**Comment by Kaillera** [comment] 2020-09-10 12:29
I gave a mechanic a revolver. When he was done with the revolver, but the target isn't dead yet, he tries to weld the target with a welding tool instead for a good while. Then he decides to go for a SMG in the armory in Dugong. I wonder if Plasma Cutter and Welding Tool should actually be considered as weapon at this point, since the only thing they can actually kill are hammerhead spawns.

**Comment by itchyOwl** [comment] 2020-09-17 08:55
Plasma Cutter and Welding Tool are given the priority 10, whereas revolver has 70, so both repair tools should already be treated as very low prio improvised tools for defending. Anything lower than 30 should result in the bot to try find a better weapon, if it's in offensive (fighting intruders). If the bot runs out of ammunition it should try to get more ammunition, unless it has a high priority weapon OR it's close to the target, in which case it's not allowed to disengage. The bug here seems to be: why the bot fails to equip the revolver that's already in the inventory? In this case, it shouldn't matter whether the enemy is close or not.

I think it would be best to test this on human-ai branch (not included in the latest unstable), because there's probably some changes that affect this behavior too.

**Comment by itchyOwl** [comment] 2020-09-17 08:56
I suppose the revolver was not empty? If it was, that could explain the behavior.

**Comment by Kaillera** [comment] 2020-09-17 10:44
I did said he was done with the revolver (I counted the shots that time). It looks like it was the no disengage rule.

**Comment by itchyOwl** [comment] 2020-09-21 15:43
In that case, I think this is not a bug. It's intentional that bots keep fighting in melee, when first engaged, instead of disengaging and going to find ammunition. Personally I think that's the most reasonable thing to do for the bots, although in some cases it's probably better to seek better weapons/find more ammo.

**Comment by Rokvach** [comment] 2020-09-23 09:44
No issues, closing.

**Closed by Rokvach** 2020-09-23 09:44 UTC
Labels: Bug, Code
