### ISSUE TITLE
Kastrull with bots

### ISSUE THREAD

**Issue by gabepombo1** [Regalis11/Barotrauma#7716] opened 2021-12-11 05:11 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**

On the Kastrull, bots close the door behind them when they repair the drone's components. This makes the drone undock.

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

Wait until a bot repairs a component on the Kastrull.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

Latest version. Windows 10.

**Additional information**

**Comment by Regalis11** [comment] 2021-12-11 10:38
Duplicate of https://github.com/Regalis11/Barotrauma/issues/6928

**Closed by Regalis11** 2021-12-11 10:38 UTC
