### ISSUE TITLE
All players kicked when player respawns

### ISSUE THREAD

**Issue by LiamWttn** [Regalis11/Barotrauma#9012] opened 2022-04-28 12:08 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When a player everyone is kicked back to the lobby. We have narrowed it down to being caused by electrical engineer talent "Remote Monitor"

**Steps To Reproduce**
Load into Multiplayer game with one player as electrical engineer
Give "Remote Monitor" talent to electrical engineer
Kill a player
Player respawn with penalty

**Version**
Barotrauma v0.17.12.0 (ReleaseWindows. branch release, revision, revision 29711300777)

**Additional information**
[Add any other context about the problem here.]
[Thrivin_2022-04-28_2105.txt](https://github.com/Regalis11/Barotrauma/files/8582534/Thrivin_2022-04-28_2105.txt)
[event_error_log_server_LiamWttn_1153_AM.log](https://github.com/Regalis11/Barotrauma/files/8582538/event_error_log_server_LiamWttn_1153_AM.log)
[Thrivin_2022-04-28_2153_3.txt](https://github.com/Regalis11/Barotrauma/files/8582539/Thrivin_2022-04-28_2153_3.txt)

**Comment by Regalis11** [comment] 2022-04-28 15:25
Duplicate of https://github.com/Regalis11/Barotrauma/issues/8879

**Closed by Regalis11** 2022-04-28 15:25 UTC
