### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by Shadow-Of-Cat** [Regalis11/Barotrauma#2691] opened 2020-04-24 15:37 UTC
My friend has crashes during multiplayer/singleplayer game. Tho me and my other friend don't.
The only thing i noticed, that game loaded with not 1050 geforce but 630 intel on a laptop, guess that's the problem here. In all other games 1050 is the main one, now we are trying to fix this in invidia control panel. 
On the other laptop game also started with integrated graphics card, but didn't crash (550 intel).

UPD:
Works fine for 10 min after changing starting videocard to 1050 via control panel.

Gonna test later today for more time.

[crashreport_4.log](https://github.com/Regalis11/Barotrauma/files/4529565/crashreport_4.log)

**Comment by Shadow-Of-Cat** [comment] 2020-04-25 13:45
UPD2:
No crashes for 2 hours

**Comment by Regalis11** [comment] 2020-04-25 14:03
Duplicate of #1833

**Closed by Regalis11** 2020-04-25 14:03 UTC
