### ISSUE TITLE
Spectator Lock (Supposedly fixed a year ago)

### ISSUE THREAD

**Issue by vibechecker628** [Regalis11/Barotrauma#9717] opened 2022-08-15 23:58 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This issue occurs with and without mods, but when playing barotrauma with my friends in a campaign, as we do, one of us died. The only problem was, station after station, they couldn't respawn, only spectate. Rejoining, re-launching the lobby, and restarting steam did not fix this issue, neither did using respawnnow, because it consider the dead player 'spectating', not waiting to spawn. They had no option aside from spectating.

When we disabled spectating, the bug was slightly fixed, instead cloning the remaining members and making a new character that had no money or talents. We then forced clients into the characters with items, killed the clones, and the member who was originally dead respawned, but every outpost we went to, the same clone process happened, and the member who originally died lost all their XP and items.
![image](https://user-images.githubusercontent.com/111323219/184755674-9ab9f10e-f201-4f4a-967c-99ab7334d4d9.png)

### Reproduction steps

Start a multiplayer campaign, with or without mods (to my knowledge, no mod patches or affects it)
Have another player join mid-session, or die during the session.
Dock at another station, or re-load, and observe them in the player tab. They will not respawn, and just display as spectator.

### Bug prevalence

Happens every time I play

### Version

Other

### -

v0.18.15.1

### Which operating system did you encounter this bug on?

Windows

**Comment by NilanthAnimosus** [comment] 2022-08-16 05:30
It may be helpful to have the campaign save/files for this (Default location on windows is C:\Users\username\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\Multiplayer)

Assuming the player in question has not in their lobby/character info checked the spectator switch, I am not sure where to begin to reproduce this issue or what might exactly be the root cause. I've looked into a number of possible related issues and tried to test this in a few ways (but no specific repro or known cause is mentioned).

Could really use more information, such as a save file, reproduction steps, what does the player suffering the issue see in the server lobby (A character info? spectating checked? job preferences?). any information would be helpful for this.

**Comment by vibechecker628** [comment] 2022-08-16 19:18
Hey Nilanth! So sadly, we deleted the save files, I didn't think of the fact they'd be useful for reproducing or analyzing the issue on a more technical level (I know, it seems obvious now). Thankfully, I don't have all bad news. This is what they see when actually spectating (image attached). They also said that the only option in the lobby was to spectate, and that they could see the information of their new character, but not their old one. (Assuming that meant job preferences and the new stats).

Before you suggest just not clicking spectate and instead waiting in the lobby, we tried that, but waiting in the lobby had no effect different from spectating, and in fact, when he disabled spectating while they were just waiting in the lobby, they continued to wait and weren't forced into the game even at that point.

As for the reproduction steps, I'm really not sure beyond what I said. I'm going to do a gamefile integrity check and get back to you, maybe it has something to do with that? 
![image](https://user-images.githubusercontent.com/111323219/184963302-1830e304-48f9-4ba2-acdf-a455fb33e5a2.png)

**Comment by NilanthAnimosus** [comment] 2022-08-17 02:38
Yeah not too sure, If its still occurring feel free to upload a zipped save file of it on any new campaign and exit the station before saving and exiting (where they still do not spawn or where you have gotten them to spawn with nothing) - at least we could see what the game is saving for their characters if anything. If I had to make any suggestions it would be to just in case try renaming the config_player.xml file in their game directory (Quickly accessible in steam via right clicking in library -> manage -> browse local files).

I don't strictly think that would work, but it would definitely reset their games settings, job preferences and any other information a validation wouldn't - I cannot imagine any other causes unless their using another operating system or other factor that makes a difference.

You could also upload your serversettings.xml (Minus any password of course) of the host just to make any tests on this as close as possible to the same conditions that might have caused.

**Comment by Regalis11** [comment] 2023-01-16 17:51
Potentially the same issue as https://github.com/Regalis11/Barotrauma/issues/10857

**Comment by Rokvach** [comment] 2023-02-13 10:25
There's been a lot of fixes closely related to this issue and no mentions of this happening again so I would assume that this issue is fixed and working correctly. Closing.

**Closed by Rokvach** 2023-02-13 10:25 UTC
Labels: Bug, Need more info, Needs testing, Code, Networking
