### ISSUE TITLE
Phantom wall on Dugong status monitor

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#11532] opened 2023-03-14 21:05 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This image shows a wall that doesn't exist appearing on the Status Monitor of a Dugong.
![image](https://user-images.githubusercontent.com/67431770/225136053-e897f8c3-e2c2-49c2-9c2f-78e7dbfcff67.png)

### Bug prevalence

Happens every time I play

### Version

v1.0.7.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment] 2023-03-28 09:13
I'd guess its probably fixably by adjusting the hulls.

**Comment by Regalis11** [comment] 2023-07-20 14:51
I'm afraid I could not reproduce the issue. On a fresh save, and after saving and quitting, the extra wall doesn't seem to show up:
![image](https://github.com/Regalis11/Barotrauma/assets/14351070/3c1db216-59da-4900-9bec-c03f8502f6f0)

**Comment by Regalis11** [comment] 2023-08-23 11:15
No steps to repro, closing

**Closed by Regalis11** 2023-08-23 11:15 UTC
Labels: Bug, Need more info, Low prio
