### ISSUE TITLE
Broke electricity logic

### ISSUE THREAD

**Issue by Instant2116** [Regalis11/Barotrauma#8944] opened 2022-04-24 01:37 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Fabricator don't work if swap for some time powering via relay component and then swap back to standard wire (WARNING: DO NOT WORK IN SUB EDIT MOD)

**Steps To Reproduce**
start company or host a server (WARNING: DO NOT WORK IN SUB EDIT MOD), 
1. add relay component near fabricator, 
2. wire power from junction box to relay component and from relay component to fabricator, 
4. disconnect fabricator from junction box, 
5. try to fabricate
6. disconnect  relay component and connect standard wire from junction box
7. try to fabricate

**Version**
v0.17.12.0 (latest update on 20 apr 2022). Windows

**Additional information**
![20220424043118_1](https://user-images.githubusercontent.com/46164525/164951887-f506884f-ced5-4e53-8c6b-ef336ee5ac04.jpg)
![20220424043110_1](https://user-images.githubusercontent.com/46164525/164951889-68e41861-1da0-46e2-90ce-6f99500c0671.jpg)

**Comment by Regalis11** [comment] 2022-04-25 07:05
Duplicate of https://github.com/Regalis11/Barotrauma/issues/8873

**Closed by Regalis11** 2022-04-25 07:05 UTC
