### ISSUE TITLE
Creatures attack provocative targets when feigning death

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#11727] opened 2023-04-03 07:48 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Same as #10375 and potentially the same as #11391?, but enemies attack diving suits and other such provocative items while feigning death from the "Non-Threatening" talent.

The creatures attempt an attack, and while it does not harm the character, they are essentially forced to wait for someone else to deal with the threat before they can stop ragdolling, since the enemies pretty much never lose aggro.

https://user-images.githubusercontent.com/37850646/229444780-bee48c5d-08db-4084-aa73-ac7bba41cc41.mp4

### Reproduction steps

1. Wear a diving suit or hold other provocative item
2. Have the talent and ragdoll for 2 seconds
3. Enemies attack your suit

### Bug prevalence

Just once

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by ubertpendragon** [comment] 2023-04-04 00:30
They attack inanimate provocatives in general and never seem stop as seen here. 
 
https://user-images.githubusercontent.com/73229309/229655648-d1a7cc19-c918-4497-a8a6-b7cbc695bdf8.mp4

Enemies will lock onto the nearest provocative and keep going at it even when they should give up on attacking it

**Comment by itchyOwl** [comment] 2023-05-09 12:16
Addressed monsters targeting provocative items until they run out by making them able to destroy the items in Regalis11/Barotrauma-development@802a6f5. The monsters are not locked to targeting the nearest provocative, but they have a high priority for it. Didn't want to change the priorities right now.

The original ticket is a duplicate of #11391.

**Comment by Vykn** [comment] 2023-05-09 12:27
> Addressed monsters targeting provocative items until they run out by making them able to destroy the items

So... the creatures will be able to destroy diving suits? While that's pretty funny, I don't think the assistant will appreciate their suit being gobbled up while they're playing dead underwater.

**Comment by itchyOwl** [comment] 2023-05-12 06:58
No, with provocative items I meant only flares, glowsticks, and flashlights. Not all items with the "provocative" tag. My bad.

**Comment by Regalis11** [comment] 2023-05-30 08:43
Tested this, and I think it's working as intended. Monsters don't attack provocative items when they're in your inventory, and can destroy flares, glowsticks and flashlights (losing interest them after they're broken).

One thing I'm not sure about is the selection of provocative items this applies to. It doesn't affect things like handheld sonar beacons and handheld sonars, so the monsters will still keep attacking them indefinitely. I'm also not sure whether it'd be a good idea to make those destructible - there's no way to repair them, and I could imagine it being confusing to find an impossible-to-repair, useless tool. Also applies to flashlights. I also think it's unintuitive for modders that they basically need to make an item destructible if it's provocative to prevent buggy monster AI behavior.

I would personally consider making the monsters lose interest in the items after a while instead.

**Comment by itchyOwl** [comment] 2023-05-30 09:17
Hmm, yeah it should be a thing. Need to debug it, but I suspect the priority reduction is either too low or that it somehow resets.

Anyway, I don't see it very problematic if the monsters are able to destroy items that are not inside an inventory. Yet it might not be suitable for all items.

**Comment by itchyOwl** [comment] 2023-05-30 11:37
It was indeed bugged. Fixed in https://github.com/Regalis11/Barotrauma-development/pull/4215/commits/be5e651993fa1b34ed6212f3137be31e3a85417f . I don't think I remembered that it should have behaved like that. Reverted the changes to the flashlight, but decided to keep them on flares and glowsticks.

**Closed** 2023-05-31 07:33 UTC
Labels: Bug, Duplicate, Code
