### ISSUE TITLE
Users disconnected from each other on Daylight Savings Time fall back

### ISSUE THREAD

**Issue by TrevorPegg** [Regalis11/Barotrauma#10263] opened 2022-11-06 06:12 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Playing the game 11/6/2022 we were playing as time crossed from 1:59 to what would be 2:00 am but due to daylight savings time it reverted to 1:00 instead. At the time this happened we all players disconnected from each other at the same time with no error message.

Players could not repair and trying to rejoin on the host player it no longer showed any players in the game.

### Reproduction steps

1. Start a multiplayer campaign.
2. Have game running as time falls back for daylight savings time.

### Bug prevalence

Happens every now and then

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-03-10 10:44
We're cleaning up some low-prio/unreproducible/irrelevant/outdated tickets from the issue tracker, and this is one of the tickets we chose to axe. Since this can only happen once per year, at a very specific time, in specific areas of the world, it's probably not worth the trouble to change all the timing logic in the game to take it into account. Closing.

**Closed by Regalis11** 2023-03-10 10:44 UTC
Labels: Bug, Code, Networking
