### ISSUE TITLE
Bots do not fire ship mounted weaponry

### ISSUE THREAD

**Issue by Ghostwish-debug** [Regalis11/Barotrauma#2737] opened 2020-04-29 04:09 UTC
- [Y ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
This issue has been reported before, and supposedly fixed:
https://github.com/Regalis11/Barotrauma/issues/946
However, in many subs (the latest being the Eel off the steam workshop) where the guns work, are loaded, and powered, and I the human captain was able to fire them, the bots do not fire the guns.

**Steps To Reproduce**
Start a new campaign. Pick your coffin- er, sub.
Assign a bot to a weapon (Fire at will)
Bring an enemy within range of said weapon.
Submit a ticket on github.

**Version**
0.9.9.0 on Windows 10 64 bit

**Additional information**
At least they still fix the hull.

**Comment by Regalis11** [comment] 2020-04-29 07:22
Duplicate of #2695. We've got a fix coming up for this very soon, sorry for the inconvenience!

**Closed by Regalis11** 2020-04-29 07:22 UTC
