### ISSUE TITLE
Portable Pump Attach

### ISSUE THREAD

**Issue by linax3-genuine** [Regalis11/Barotrauma#7637] opened 2021-12-05 20:15 UTC
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
it appears that only the mechanic can properly reattach portable pumps.
if done by another, it fails and gives error message when trying to reattach:
too many of this item type placed on this submarine x/0

**Steps To Reproduce**
create 2 portable pumps;
attach 2 portable pumps;
detach 1 portable pump;
try to reattach 1 portable pump with non-mechanic;
maybe, an error message: too many of this item type placed on this submarine 1/0;

**Version**
v0.15.13.0.
windows

**Additional information**
done some draining and wiring, humpback submarine, inserted fulgurium batteries, tried all other crew professions, only mechanic works properly; singleplayer campaign; docked to station.

**Comment by MaaiG** [comment] 2021-12-05 23:16
I haven’t been able to install no one portble pumps (submarine editor)!
![Image 001_02-13 (1) (1) (1) (1) (1) (1)](https://user-images.githubusercontent.com/93348499/144767924-1c2bdd85-57a4-4a44-99c9-40a1b707edce.png)

**Comment by Rokvach** [comment] 2021-12-06 15:25
I encountered the issue of not being able to install portable pumps as well in singleplayer round where I spawned in a portable pump and tried to place it on a wall.

**Comment by M61Dev** [comment] 2021-12-07 14:31
It is intentional that only the Mechanic with the Let It Drain talent can place the pumps, because otherwise you could place as many pumps in a submarine as you wanted, which would trivialize the game (among other things). 

However, the item message is misleading and looks like a programming error. For this reason, I changed the logic to display a special message when you try to place a pump without the talent in https://github.com/Regalis11/Barotrauma-development/commit/2e521d0e4a7ee6004fee3913b4ed7f087f3c3aef

**Comment by linax3-genuine** [comment] 2021-12-07 20:53
interesting. that needs less-ambiguous design.
you should allow all to attach them and tie them(the restriction) to the submarine, as the design intention seems to be.
its the single item that does not conform to the item usage mechanics (i cant think of another).

ill have to wait and see this new message, maybe its good enough.

other than that, the restriction is nonsense, but i understand the need for it, for such an overpowered item.

im new here and i see this "close with comment" button. i donk know who is to decide and close those issues.
i think this is resolved for now, with the mentioned change.

**Comment by Regalis11** [comment] 2021-12-08 14:18
> im new here and i see this "close with comment" button. i donk know who is to decide and close those issues.

We generally keep the issues open until @Rokvach has tested and verified that the fix is working as intended. :) So no need to close it yourself.

**Comment by Rokvach** [comment] 2022-01-04 11:44
Tested, working correctly. Closing.

**Closed by Rokvach** 2022-01-04 11:44 UTC
Labels: Code, Design
