### ISSUE TITLE
[Linux] Barotrauma failing to launch, having to edit config.

### ISSUE THREAD

**Issue by LatekVo** [Regalis11/Barotrauma#9868] opened 2022-09-14 19:28 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While launching Barotrauma, certain Linux systems may encounter following error:

`Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.`

This can be easily fixed by modifying `Barotrauma.runtimeconfig.json` to contain following line: 

`"System.Globalization.Invariant": true` in the `configProperties` section. 

While the exception is thrown by the steam API (see trace in the bottom section of the report), it can be easily detected beforehand, and neccesary changes could be applied before the error is thrown.

### Reproduction steps

1. Start the game.

### Bug prevalence

Happens every time I play

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Linux

### Relevant error messages and crash reports

```shell
stdout /w Trace:

[S_API] SteamAPI_Init(): Loaded '/home/xxx/.local/share/Steam/linux64/steamclient.so' OK.
Setting breakpad minidump AppID = 6xxxx0
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  7xxxxxxxxxxxxx0 [API loaded no]
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CompareInfo..cctor()
   at System.String.StartsWith(System.String, System.StringComparison)
   at Barotrauma.Steam.SteamManager.SteamIDStringToUInt64(System.String)
   at Barotrauma.Steam.SteamManager.SteamIDUInt64ToString(UInt64)
   at Barotrauma.Steam.SteamManager.InitializeProjectSpecific()
   at Barotrauma.Steam.SteamManager.Initialize()
   at Barotrauma.Program.Main(System.String[])
[1]    4657 IOT instruction (core dumped)  ./Barotrauma
```

**Comment by LatekVo** [comment] 2022-09-14 19:29
Also please note that while this error may seem like a Steam issue, i didn't encounter it in any other game than Barotrauma.

**Comment by Regalis11** [comment] 2022-09-15 06:23
Thank you for the report!

We've actually got a fix for this coming up in the next update. Closing as a duplicate of https://github.com/Regalis11/Barotrauma/issues/8858

**Closed by Regalis11** 2022-09-15 06:23 UTC
