### ISSUE TITLE
Circuit Box corruption.

### ISSUE THREAD

**Issue by TheActualRealBob** [Regalis11/Barotrauma#12501] opened 2023-08-14 17:53 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I was Making a Door system, I'll attach a image file of the Circuit Box setup.
It was fully wired, But corrupts the save file upon loading.
![image](https://github.com/Regalis11/Barotrauma/assets/118665154/f3423d5d-2770-4bbb-81c8-0d31b59b27e6)
(That wiring crashes the game)

### Reproduction steps

1. Make a cube segmented in 3 with 2 custom doors.
2. Add 2 Circuit Boxes.
3. Wire on up with RegEx such as in this image
![image](https://github.com/Regalis11/Barotrauma/assets/118665154/f7ad92d5-73f9-4df2-9f60-55c86696aee7)
4. Load the sub via the sub editor.
5. Watch the game crash.

(Specs: Intel i5, Intel iRISx, 8GB Of ram, Windows 11, Full HD 1980x1080)

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Other

### -

Sub editor (Maybe During other Loading sequences aswell)

### Version

Unstable (v1.1.3.0)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 08/14/2023 19:41:11)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

42FB385E45F04FB97344D5EE26850647

Game version 1.1.7.0 (UnstableWindows, branch release/very-unstable-1.1, revision 7246678857)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla (ED75340), Increased Electrical Hazards (BDD19AF), Bobs goofy Conversation(s) (70C4660), Lua For Barotrauma (4F663F9), Type VII-C U-Boat 'Monarch' (C8B1E00), Wreck Corpses (39617D4), What the fuck am i doing (310F6CC), Unnamed (AFE0661), The start of Something (9817F27), DEATH LAZER (FD96B2D), Mk. 0 ''Suicide pod'' Life-Pod (393BD9A), WIP thingy (8E239C6), Testing thing No. 1 (0C84816), TSOS Terrorist box version (627E32D), Unnamed testing box (B368E8A), Electrical test (7DADDBF), Radiation is scary (FE56A7A), Crew Barrack Prefab (D6C6D9A), Door console and shit (BE8936C), Door but easier (80D2488)
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.SubEditorScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.22621.0 64 bit
    GPU name: Intel(R) Iris(R) Xe Graphics
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Failed to find item with ID 32 for CircuitBoxWire with ID 6 (System.Exception)
Target site: Barotrauma.CircuitBoxWire LoadFromXML(Barotrauma.ContentXElement, Barotrauma.Items.Components.CircuitBox)
Stack trace: 
   at Barotrauma.CircuitBoxWire.LoadFromXML(ContentXElement element, CircuitBox circuitBox) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CircuitBox\CircuitBoxWire.cs:line 77
   at Barotrauma.Items.Components.CircuitBox.OnMapLoaded() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Signal\CircuitBox.cs:line 179
   at Barotrauma.Item.OnMapLoaded() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 3885
   at Barotrauma.MapEntity.MapLoaded(List`1 entities, Boolean updateHulls) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 814
   at Barotrauma.Submarine..ctor(SubmarineInfo info, Boolean showErrorMessages, Func`2 loadEntities, IdRemap linkedRemap) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Submarine.cs:line 1616
   at Barotrauma.Submarine.Load(SubmarineInfo info, Boolean unloadPrevious, IdRemap linkedRemap) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Submarine.cs:line 1684
   at Barotrauma.SubEditorScreen.LoadAutoSave(Object userData) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SubEditorScreen.cs:line 3452
   at Barotrauma.SubEditorScreen.<>c__DisplayClass134_0.<CreateLoadScreen>b__11(GUIComponent button, Object o) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SubEditorScreen.cs:line 3354
   at Barotrauma.GUIDropDown.SelectItem(GUIComponent component, Object obj) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIDropDown.cs:line 333
   at Barotrauma.GUIListBox.Select(Int32 childIndex, Force force, AutoScroll autoScroll, TakeKeyBoardFocus takeKeyBoardFocus, PlaySelectSound playSelectSound) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 1068
   at Barotrauma.GUIListBox.UpdateChildrenRect() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 788
   at Barotrauma.GUIListBox.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 908
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1244
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 876
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[08/14/2023 19:40:47] Attempting to open ALC device "OpenAL Soft on Speaker (Realtek(R) Audio)"
[08/14/2023 19:40:45] Logged in as The Real bob (SteamID STEAM_1:1:583739225)
```

**Comment by 3e849f2e5c** [comment] 2023-08-15 09:15
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a444ef44f297f6964f863b7025f5f8e6553b8b99

**Comment by Jasontti** [comment] 2023-08-15 13:49
Caused it to happen again.

Got 3 different errors with same circuit box
And after reproing it 2 times it doesn't crash again.

![image.png](https://images.zenhubusercontent.com/6463874172183936f90966a8/3aa317bc-400c-433a-9ae3-69bcefffad9b)

![image.png](https://images.zenhubusercontent.com/6463874172183936f90966a8/ca318036-1a61-4f33-9c01-ade62a21f30e)

![image.png](https://images.zenhubusercontent.com/6463874172183936f90966a8/6b3089e3-1ed2-4aeb-b9fa-047b05a40aee)

```
Unhandled exception. System.Exception: Failed to find item with ID 729 for CircuitBoxNode with ID 0
   at Barotrauma.CircuitBoxNode.LoadFromXML(ContentXElement element, CircuitBox circuitBox) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/CircuitBox/CircuitBoxNode.cs:line 39
   at Barotrauma.Items.Components.CircuitBox.OnMapLoaded() in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Signal/CircuitBox.cs:line 176
   at Barotrauma.Item.OnMapLoaded() in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/Items/Item.cs:line 3880
   at Barotrauma.MapEntity.MapLoaded(List`1 entities, Boolean updateHulls) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/Map/MapEntity.cs:line 818
   at Barotrauma.Submarine..ctor(SubmarineInfo info, Boolean showErrorMessages, Func`2 loadEntities, IdRemap linkedRemap) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/Map/Submarine.cs:line 1616
   at Barotrauma.GameSession.StartRound(LevelData levelData, Boolean mirrorLevel, SubmarineInfo startOutpost, SubmarineInfo endOutpost) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/GameSession/GameSession.cs:line 426
   at Barotrauma.SubEditorScreen.TestSubmarine(GUIButton button, Object obj) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/Screens/SubEditorScreen.cs:line 1062
   at Barotrauma.GUIButton.Update(Single deltaTime) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/GUI/GUIButton.cs:line 263
   at Barotrauma.GUIComponent.UpdateAuto(Single deltaTime) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/GUI/GUIComponent.cs:line 455
   at Barotrauma.GUI.Update(Single deltaTime) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/GUI/GUI.cs:line 1244
   at Barotrauma.GameMain.Update(GameTime gameTime) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 876
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in /home/joonas/dev/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in /home/joonas/dev/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in /home/joonas/dev/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/SDL/SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in /home/joonas/dev/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in /home/joonas/dev/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 58
../baro-script.sh: line 28: 26053 Aborted                 ./Barotrauma/bin/$2Linux/net6.0/Barotrauma
```

```
Failed to load the submarine. The submarine file might be corrupted. {Failed to find item with ID 729 for CircuitBoxNode with ID 0}
   at Barotrauma.CircuitBoxNode.LoadFromXML(ContentXElement element, CircuitBox circuitBox) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/CircuitBox/CircuitBoxNode.cs:line 39
   at Barotrauma.Items.Components.CircuitBox.OnMapLoaded() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Signal/CircuitBox.cs:line 176
   at Barotrauma.Item.OnMapLoaded() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Items/Item.cs:line 3880
   at Barotrauma.MapEntity.MapLoaded(List`1 entities, Boolean updateHulls) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Map/MapEntity.cs:line 818
   at Barotrauma.Submarine..ctor(SubmarineInfo info, Boolean showErrorMessages, Func`2 loadEntities, IdRemap linkedRemap) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Map/Submarine.cs:line 1616
   at Barotrauma.SubEditorScreen.LoadSub(SubmarineInfo info, Boolean checkIdConflicts) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Screens/SubEditorScreen.cs:line 3597
```

```
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Barotrauma.CircuitBoxNode..ctor(UInt16 id, Item item, Vector2 position, CircuitBox circuitBox) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/CircuitBox/CircuitBoxNode.cs:line 19
   at Barotrauma.CircuitBoxNode.LoadFromXML(ContentXElement element, CircuitBox circuitBox) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/CircuitBox/CircuitBoxNode.cs:line 42
   at Barotrauma.Items.Components.CircuitBox.OnMapLoaded() in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Signal/CircuitBox.cs:line 176
   at Barotrauma.Item.OnMapLoaded() in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/Items/Item.cs:line 3880
   at Barotrauma.MapEntity.MapLoaded(List`1 entities, Boolean updateHulls) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/Map/MapEntity.cs:line 818
   at Barotrauma.Submarine..ctor(SubmarineInfo info, Boolean showErrorMessages, Func`2 loadEntities, IdRemap linkedRemap) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/Map/Submarine.cs:line 1616
   at Barotrauma.GameSession.StartRound(LevelData levelData, Boolean mirrorLevel, SubmarineInfo startOutpost, SubmarineInfo endOutpost) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/GameSession/GameSession.cs:line 426
   at Barotrauma.SubEditorScreen.TestSubmarine(GUIButton button, Object obj) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/Screens/SubEditorScreen.cs:line 1062
   at Barotrauma.GUIButton.Update(Single deltaTime) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/GUI/GUIButton.cs:line 263
   at Barotrauma.GUIComponent.UpdateAuto(Single deltaTime) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/GUI/GUIComponent.cs:line 455
   at Barotrauma.GUI.Update(Single deltaTime) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/GUI/GUI.cs:line 1244
   at Barotrauma.GameMain.Update(GameTime gameTime) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 876
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in /home/joonas/dev/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in /home/joonas/dev/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in /home/joonas/dev/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/SDL/SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in /home/joonas/dev/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in /home/joonas/dev/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 58
../baro-script.sh: line 28: 26532 Aborted                 ./Barotrauma/bin/$2Linux/net6.0/Barotrauma
```

**Comment by Jasontti** [comment] 2023-08-17 06:00
Could not reproduce anymore.

**Closed by Jasontti** 2023-08-17 06:00 UTC
Labels: Bug, Code, Crash
