### ISSUE TITLE
Card in hidden vent

### ISSUE THREAD

**Issue by Randy624** [Regalis11/Barotrauma#12638] opened 2023-09-08 04:29 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Card in hidden vent don't open weapon safe deposit at SecurityModule_01_Abandoned.
![2023-09-08_07-24-16](https://github.com/Regalis11/Barotrauma/assets/108170820/96eb801f-26ce-482b-8da9-521704f21ebc)
![2023-09-08_07-24-54](https://github.com/Regalis11/Barotrauma/assets/108170820/7e24ff26-6865-4790-981f-1843401659e2)

### Reproduction steps

1. take card
2. suck it

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-09-08 06:32
Duplicate of https://github.com/Regalis11/Barotrauma/issues/12487

**Closed by Regalis11** 2023-09-08 06:32 UTC
