### ISSUE TITLE
[Factions] Outpost docking ports at mission ends commonly found floating

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10650] opened 2022-12-03 00:41 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Ever since 100.8.0.0, it seems like the majority of outpost docking hatches are detached from any rocks and float in the ocean. Whilst not a constant issue, it happens regularly enough to be predictable. 

Image below for reference, along with the seed.

![image](https://user-images.githubusercontent.com/105495756/205413572-6c74c923-47ad-4558-828c-bf551fbe94a8.png)
![image](https://user-images.githubusercontent.com/105495756/205413578-e2b887e9-2213-497a-8b1a-b96ad354ae1b.png) (Belus LineaVersas)

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by ubertpendragon** [comment] 2022-12-03 03:26
Isn't it possible to spawn the outposts atop the flat ceiling? 

Lineas already generate a big stretch of flat ceiling

**Comment by Regalis11** [comment] 2022-12-07 14:43
This doesn't seem specific to the faction branch, nor a new issue. The outposts are placed low enough to leave horizontal space for the submarine to dock, which seems to be what caused the placement in that screenshot too.

I gave this a quick test but couldn't find any levels with unusual outpost placement. There's also not enough information in the report to generate that same level since the whole output of the command isn't visible in the screenshot.

**Comment by Wheatley1001** [comment] 2023-01-28 04:36
Unsure if these images help but we found another instance of this issue in 100.17.0.0. No freecam screenshot because I don't want to brick player's achievements for the session, but seed and navigation terminal imaging is included.

![image](https://user-images.githubusercontent.com/105495756/215242192-5f60d4c8-2374-4b74-ba03-58fd59d35e7e.png)
![image](https://user-images.githubusercontent.com/105495756/215242194-c4da00ae-4aa9-48f1-b8be-f1532c12339b.png)

**Comment by Wheatley1001** [comment] 2023-02-23 21:26
Still showing up in 1.0.2.0, freecam image and level seed attached.

![image](https://user-images.githubusercontent.com/105495756/221033934-0f58812e-6fb7-4b80-bd66-3609cadf1535.png)
![image](https://user-images.githubusercontent.com/105495756/221033950-186dc4c3-2fe4-4d24-9b97-b0de733dab0d.png)

**Comment by Regalis11** [comment] 2023-02-24 08:21
Thank you for the extra info! I'm afraid I still haven't been able to find a level where this occurs (a save file might help?). There is not enough information in the screenshots to generate the same level, as I don't know the biome, size or level generation parameters used there.

It also seems the "showseed" command doesn't output all the information when executed by a client in multiplayer, fixed that in https://github.com/Regalis11/Barotrauma-development/commit/247a3612ae0631a11f430eae926ebd95e7bb6db8.

**Comment by Wheatley1001** [comment] 2023-03-01 20:48
A save file you asked for, a save file you shall get (along with the image and seed, of course~)!
![image](https://user-images.githubusercontent.com/105495756/222259529-3906a0a0-3338-480b-a529-24a0bc90fd0a.png)
![image](https://user-images.githubusercontent.com/105495756/222259544-450030d8-96df-4261-88b8-92c50d3eef4b.png)
[Floating Outpost Instance 1.zip](https://github.com/Regalis11/Barotrauma/files/10865148/Floating.Outpost.Instance.1.zip)
_Instance 1 of Floating Outpost._

![image](https://user-images.githubusercontent.com/105495756/222260755-6358592a-28f8-44f8-b428-e66e81042c4a.png)
![image](https://user-images.githubusercontent.com/105495756/222260781-1081db49-dd7b-4748-bd0e-b6e733b89032.png)
[Floating Outpost Instance 2.zip](https://github.com/Regalis11/Barotrauma/files/10865162/Floating.Outpost.Instance.2.zip)
_Instance 2 of Floating Outpost._

Now, Instance 2 gets interesting. You see, the docking hatch itself was clearly for a Separatist outpost (see the graffiti and separatist imagery). However, the outpost we actually entered was one owned by the Coalition. I have a save file attached for that, too (because that outpost _also_ had bugs relating to hidden items, but that's for another ticket).

[Coalition Outpost with a Separatist Dock.zip](https://github.com/Regalis11/Barotrauma/files/10865176/Coalition.Outpost.with.a.Separatist.Dock.zip)

**Comment by NilanthAnimosus** [comment] 2023-08-22 08:57
Tested against Release/traitor-update commit https://github.com/Regalis11/Barotrauma-development/commit/bfc61bdccee7567cee8afe3a0a471d562c2d1196 and version 1.0.10.0

can reproduce using the saves on 1.0.10.0 but not the current code (Likely due to level generator changes):

![image](https://github.com/Regalis11/Barotrauma/assets/29177976/fbccd21e-e7c0-4cd1-ad9a-7a455598a408)

**Comment by Rokvach** [comment] 2023-10-31 10:28
The first level I loaded up in this PR has a floating outpost

Level editor

Level type: 
Coldcavernsadvanced

Seed:
vYfPznke

Submarine:
Berilia

![image](https://github.com/Regalis11/Barotrauma/assets/7299826/0f64ee95-c5cd-4dba-98e3-1520b06cbca9)

**Comment by Regalis11** [comment] 2023-11-01 07:35
Addressed in https://github.com/Regalis11/Barotrauma-development/pull/4495/commits/e29ab87e249e8e36e440e0f8088e55d0d95d2f27

**Comment by Rokvach** [comment] 2023-11-09 11:02
Not enough room to dock a sub into this outpost

Level editor
Seed: VaAuRFNv
Sub: Berilia
Level type: coldcavernstransition

![image](https://github.com/Regalis11/Barotrauma/assets/7299826/33d7f38b-2027-4560-b30e-5120227fe9a0)

**Comment by Rokvach** [comment] 2023-11-16 12:46
Tested, didn't find any further issues, can be merged and closed.

**Closed** 2023-11-16 13:11 UTC
Labels: Bug, Code
