### ISSUE TITLE
friend keep disconnecting when starting the new round

### ISSUE THREAD

**Issue by jalwintan** [Regalis11/Barotrauma#6953] opened 2021-10-18 15:28 UTC
**Description**
when starting the new round or end the round, my friend will disconnecting from the server and they need to spend time to rejoin back and sometime they are not able to join back until i need to back to the server list and restart the game only able to join back. 
i got found the the serverlog and saw there have the error_log for the client and i no sure is the issues or not but some of them did not have the report. i also found that if the person havent sart in th game(still in revival states or just joinning the server) they will not face this problem when end/start the round.

**Version**
game version v0.14.9.1 (ReleaseWindows,branch release,revision df0088ca33)

[event_error_log_server_Van Play_1247 PM.log](https://github.com/Regalis11/Barotrauma/files/7366361/event_error_log_server_Van.Play_1247.PM.log)

**Comment by Regalis11** [comment] 2021-11-03 15:13
Duplicate of https://github.com/Regalis11/Barotrauma/issues/6265

**Closed by Regalis11** 2021-11-03 15:13 UTC
