### ISSUE TITLE
Game crashes on startup after most recent update

### ISSUE THREAD

**Issue by standersson** [Regalis11/Barotrauma#2689] opened 2020-04-24 12:16 UTC
- [ X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Starting up the game sometimes results in an instant crash. Otherwise, it gives me enough time to try to look at open games before it crashes.

**Steps To Reproduce**
Start the game. Select the option to give currently open games.

**Version**
Windows 10

**Additional information**
"Oops! Barotrauma just crashed.
A crash report ("crashreport(14).log") was saved in the root folder of the game. The error was not sent to the developers........."

Barotrauma Client crash report (generated on 2020/04/24 21:07:19)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

B88397013C2378C4A99C3E19DEBEE54F

Game version 0.9.9.0 (ReleaseWindows, branch release, revision 0534150c8)
Graphics mode: 1920x1080 (Fullscreen)
VSync ON
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.ServerListScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.17763.0 64 bit
    GPU name: Intel(R) UHD Graphics 620
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void FilterServers()
Stack trace: 
   at Barotrauma.ServerListScreen.FilterServers()
   at Barotrauma.ServerListScreen.<>c__DisplayClass70_0.<CreateUI>b__26(GUITickBox tickBox)
   at Barotrauma.GUITickBox.set_Selected(Boolean value)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime)
   at Barotrauma.GameMain.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Barotrauma.Program.Main(String[] args)

Last debug messages:
[2020/04/24 21:07:00] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[2020/04/24 21:07:00] Content package load order: Vanilla 0.9
[2020/04/24 21:07:00] Content package load order: Vanilla 0.9
[2020/04/24 21:06:57] Attempting to open ALC device "OpenAL Soft"
[2020/04/24 21:06:56] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[2020/04/24 21:06:56] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[2020/04/24 21:06:55] Logged in as XXX (SteamID STEAMXXXXXXXX)

**Comment by victor443** [comment] 2020-04-25 00:59
what should I do about it?

**Comment by Regalis11** [comment] 2020-04-25 13:59
Duplicate of #2567 

This happens due when trying to filter servers in the server list based on game mode. We've got a hotfix coming for this issue soon, but for now it should be possible to work around it by not trying to filter the server list. Sorry for the trouble!

**Closed by Regalis11** 2020-04-25 13:59 UTC
