### ISSUE TITLE
Inventory flickers when you get stunned

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8808] opened 2022-04-13 20:22 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If your character gets stunned the whole inventory starts to flicker

Noticed in multiplayer

**Steps To Reproduce**
Fight some outpost guards and notice that inventory starts to flicker when they stun you

**Version**
0.17.9.0
Branch: bugfixes

**Comment by ekqvist** [comment] 2022-04-14 06:44
Couldn't reproduce. I tried hitting the guards until they started attacking me with the stun batons. After a few hits, when I got fully stunned, the inventory bar was disabled correctly and didn't flicker. Tested both in singleplayer and in multiplayer.

**Comment by Rokvach** [comment] 2022-04-29 12:48
I still notice this happening quite often, might be a compination of handcuffs + stunning?

**Comment by Rokvach** [comment] 2022-05-25 08:47
The flickering is quite annoying to look at when it happens so I'd hope we would find a way to fix this

**Comment by ekqvist** [comment] 2022-05-25 09:56
Ok, I'll try to have another look at it. I didn't try the above yet. But if you find a sure way to reproduce it, please write it down.

**Comment by ekqvist** [comment] 2022-06-06 09:56
The only way I can reproduce this in some way is if guards attack me with stun guns and/or stun batons and manage to cause very small amounts of the stun effect which will pass quickly and then get inflicted again. But then it still seems to reflect the character state, with the inventory being disabled when the character is stunned.

So, I'm not entirely sure what to do with this if that's the only issue. If there's something else, I'll need more precise steps to reproduce the issue.

Moving back to Bugfixes for now.

**Comment by Regalis11** [comment] 2022-09-27 18:59
No known steps to repro, closing

**Closed by Regalis11** 2022-09-27 18:59 UTC
Labels: Bug, Need more info, Code, Low prio
