### ISSUE TITLE
I'm getting this error when entering the game

### ISSUE THREAD

**Issue by yekkta** [Regalis11/Barotrauma#8910] opened 2022-04-22 12:50 UTC
Coroutine Barotrauma.SinglePlayerCampaign+<DoLoadInitialLevel>d__16 threw an exception: Object reference not set to an instance of an object.
   at Barotrauma.XMLExtensions.GetChildElements(XContainer container, String name, StringComparison comparisonMethod) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Serialization\XMLExtensions.cs:line 924
   at Barotrauma.HumanPrefab.GiveItems(Character character, Submarine submarine, RandSync randSync, Boolean createNetworkEvents) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\HumanPrefab.cs:line 157
   at Barotrauma.OutpostGenerator.SpawnNPCs(Location location, Submarine outpost) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Outposts\OutpostGenerator.cs:line 1597
   at Barotrauma.Level.SpawnNPCs() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\Level.cs:line 4210
   at Barotrauma.GameSession.InitializeLevel(Level level) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 581
   at Barotrauma.GameSession.StartRound(LevelData levelData, Boolean mirrorLevel, SubmarineInfo startOutpost, SubmarineInfo endOutpost) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 432
   at Barotrauma.SinglePlayerCampaign.DoLoadInitialLevel(LevelData level, Boolean mirror)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\SinglePlayerCampaign.cs:line 264
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 197
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 255

**Comment by Regalis11** [comment] 2022-04-22 14:35
Duplicate of https://github.com/Regalis11/Barotrauma/issues/8887

**Closed by Regalis11** 2022-04-22 14:35 UTC
