### ISSUE TITLE
Creature Nest enemies (typically Tiger Threshers) sometimes spawn in walls

### ISSUE THREAD

**Issue by Wheatley1002** [Regalis11/Barotrauma#10973] opened 2023-01-19 10:47 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### Key Information
Game mode: Campaign
Game type: Multiplayer
Campaign save version: Started in 100.13.0.0, issue occurred in version 100.13.0.0 (ISSUE HAS OCCURRED IN PREVIOUS STABLE BUILDS)
Server type: Steam P2P

### Issue Report
Sometimes during Creature Nest missions (majority of instances are Tiger Threshers, but I cannot say for certain it's limited to them), the creature which protects the nest will have an instance of it spawn in the wall. For example, if it's a Tiger Thresher nest, one of the instances of Tiger Thresher sometimes spawns inside the wall and cannot be touched. 

Whilst in practice, this doesn't cause mission-related issues, it's still something I want to bring up. 

![image](https://user-images.githubusercontent.com/120612589/213422383-d511a637-277b-4dd4-a6e7-163720fb6910.png)
_Figure 1. Image of Tiger Thresher stuck in the wall._

### Bug prevalence

Happens every now and then

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-01-19 14:00
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10026

**Closed by Regalis11** 2023-01-19 14:00 UTC
