### ISSUE TITLE
Label Text does not respect case/uppercase for certain words

### ISSUE THREAD

**Issue by bavarianblacksmith** [Regalis11/Barotrauma#4371] opened 2020-11-22 05:43 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Certain words like "LOAD" or "load" get printed out as "Load". I'm not sure why this happens. People in the discord have said the bug affects other words as well.

**Steps To Reproduce**
Spawn label with all uppercase or lowercase "load".

**Version**
v10.6.2 Windows

**Additional information**
None

**Comment by 3e849f2e5c** [comment] 2020-11-23 06:10
This is caused by localization, anything you input into a text display checks if it matches a tag in the localization file and there's a tag for a lot of generic words

**Comment by 3e849f2e5c** [comment] 2020-11-23 06:38
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7b26a9ad3a98ed0a306739810090e511cd6e47b3 by adding a checkbox to skip localization into the item label.

**Comment by bavarianblacksmith** [comment] 2020-11-24 03:56
Sweet, ty.

**Comment by Jlobblet** [comment] 2020-12-11 23:28
Tested, working correctly.
![image](https://user-images.githubusercontent.com/37539527/101964222-914bc900-3c08-11eb-993b-978a30781056.png)

**Comment by Rokvach** [comment] 2020-12-11 23:30
Closing

**Closed by Rokvach** 2020-12-11 23:30 UTC
Labels: Bug, Code
