### ISSUE TITLE
Traveling Tradesman (Captain Talent) Sometimes Doesn't Give Extra Sales

### ISSUE THREAD

**Issue by gerakis** [Regalis11/Barotrauma#9791] opened 2022-08-29 15:53 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Occasionally the extra sales from traveling tradesman does not work. I checked all 3 shops. I'm not sure what causes it but I can link a save file where it happened. This bug only happens sometimes.

https://mega.nz/file/OVMCiSgY#CVLp5Wu6yfxsg73HWHZ7d9DUDPAm1EdlcouVaqrJ9FE

### Reproduction steps

Load up my save file for a single player campaign and check the shops.

### Bug prevalence

Happens every now and then

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by gerakis** [comment] 2022-08-29 15:57
Please note this is different than my other bug report about traveling tradesman. I decided to split it into 2 issues because they are probably unrelated bugs. I just happened to notice them around the same time.

**Comment by Regalis11** [comment] 2022-08-30 06:56
Seems like a duplicate of https://github.com/Regalis11/Barotrauma/issues/9720

**Closed by Regalis11** 2022-08-30 06:56 UTC
Labels: Bug, Code
