### ISSUE TITLE
Multiplayer Campaign not functioning after update

### ISSUE THREAD

**Issue by Dekkar1218** [Regalis11/Barotrauma#1651] opened 2019-06-15 08:04 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Ran like 10-14 Missions in campaign on 0.9.0.4 , once update for 0.6 hit, after first mission, second mission kicks everyone saying something about a missing event (usually something random, like one time it said we were all missing crawler data or something - next time said alien door)

**Steps To Reproduce**
Run a campaign using any sub, try to get past the first 2 missions without an error and people getting booted.

**Version**
0.9.0.6

**Additional information**
Will post additonal when I run another campaign , when the server crashs it kills the console window so dont have time to look at what happend.

**Comment by Regalis11** [comment] 2019-06-15 09:12
Duplicate of #1603

**Closed by Regalis11** 2019-06-15 09:12 UTC
