### ISSUE TITLE
Stuck in floor from rewiring electrocution

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2073] opened 2020-01-30 13:19 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Player gets stuck in the floor when they get electrocuted for rewiring. Cannot climb ladders, and ragdolling does not fix it either. Will revert back to normal when the wire is unequipped.

**Steps To Reproduce**
Add a wire to any machines and get electrocuted.

**Version**
0.9.701
Windows

**Additional information**
https://www.youtube.com/watch?v=4u52bQYUjU8

**Comment by Regalis11** [comment] 2020-02-06 11:44
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ed208ed81704af2d232100fc3b3c9240e21872a7

**Comment by Rokvach** [comment] 2020-02-06 23:15
Couldn't reproduce this, so seems to be working correctly. Closing.

**Closed by Rokvach** 2020-02-06 23:15 UTC
Labels: Bug, Code
