### ISSUE TITLE
Spam attack by barotrauma

### ISSUE THREAD

**Issue by Magos-crawler** [Regalis11/Barotrauma#9404] opened 2022-06-18 12:56 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This error appeared after modding refactor, shows after every my action (no mods enabled and no mods maked). No idea how to fix it, there is no path or something helpful, just spam.
One error:
![3423523](https://user-images.githubusercontent.com/78676550/174437748-a2e05c6d-e43c-4bd4-8e03-6c724c1a5db3.png)
More error:
![Screenshot_9](https://user-images.githubusercontent.com/78676550/174438036-593b3f41-eeaf-43ea-ba06-a9df35470574.png)

### Reproduction steps

1. Install mods
2. Make modding refactor
3. Enjoy errors and console opening every second

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Failed to load "": Name is null or empty:    at Barotrauma.ContentPackage.AssertCondition(Boolean condition, String errorMsg) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentPackage\ContentPackage.cs:line 183
   at Barotrauma.ContentPackage..ctor(XDocument doc, String path) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentPackage\ContentPackage.cs:line 60
   at Barotrauma.RegularPackage..ctor(XDocument doc, String path) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentPackage\RegularPackage.cs:line 10
   at Barotrauma.ContentPackage.TryLoad(String path) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentPackage\ContentPackage.cs:line 140
```

**Comment by Ek-Videogames** [comment] 2022-06-19 04:38
PS - More read errors like this should probably print a file path in the future, that will allow better error reporting and file submissions.

**Comment by Regalis11** [comment] 2022-06-19 10:33
Duplicate of https://github.com/Regalis11/Barotrauma/issues/8864

**Closed by Regalis11** 2022-06-19 10:33 UTC
