### ISSUE TITLE
Edges of docking hatch not solid?

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#2477] opened 2020-03-21 00:42 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Not sure if this is a problem with custom subs, but I've seen it a lot lately. Players/Monsters can enter the sides of a docking hatch.

https://streamable.com/rv435

**Version**
Windows 0.9.7.1

**Comment by Kaillera** [comment] 2020-03-21 08:43
The gap created by the two docking ports are because they're extending outward from the sub a bit too much. Usually solved by pulling them inward will tighten the space.

However yes, they can swim through them and get in.

**Comment by Regalis11** [comment] 2020-04-16 10:26
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e28b2dfc4570b1c0fce884d0bfcaf4047406990c

**Comment by Rokvach** [comment] 2020-04-17 04:02
Wasn't able to reproduce, working correctly. Closing.

**Closed by Rokvach** 2020-04-17 04:02 UTC
Labels: Bug, Code
