### ISSUE TITLE
A null reference exception on starting a multiplayer round

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#4459] opened 2020-12-10 06:46 UTC
Reported by Videogames. I wasn't able to reproduce the issue.

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/4fe654a7-c7c4-4d92-92eb-8dceb98577e2)

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/382d8eb3-6642-4cbf-814c-4c9bdf4576c0)

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/60391633-8e33-4735-90bb-65d930e36098)

Supposing that the line numbers are correct, I don't understand how GameSession could be null there, since a new instance is created just above the line that crashes. Could it be that the property setter somehow fails? I can't see how that could happen though.

**Comment by Regalis11** [comment] 2020-12-10 08:53
I think you misread the stack trace, GameSession is not null there because the exception got thrown from line 365 in the GameSession.StartRound method. There doesn't seem to be anything that could throw that exception on that line in v0.11.0.9 though, do you know which game version this error appeared in?

**Comment by itchyOwl** [comment] 2020-12-17 09:35
Yeah, you are right. Initially I thought there was something weird with the line numbers but when I took another look, I probably somehow misread the lines there. I don't have more information than this, need to ask Videogames and/or wait for further reports.

It was reported to be on stable v0.11.0.9.

**Comment by Regalis11** [comment] 2021-01-19 14:08
Duplicate of https://github.com/Regalis11/Barotrauma/issues/4581

**Closed by Regalis11** 2021-01-19 14:08 UTC
Labels: Bug, Code, Crash, Need more info, Needs testing
