### ISSUE TITLE
bigbrother event gets dialogue stuck if you try to skip it

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#10391] opened 2022-11-14 18:00 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The "bigbrother" event gets stuck if you select the following option:

![image](https://user-images.githubusercontent.com/29177976/201732567-d82004cf-d0c6-4257-ab0b-2486aed463e3.png)

### Reproduction steps

Start/Load a campaign
Reach a station
use command Triggerevent bigbrother
Select "I'd rather not get involved"

Dialogue window will not close and E also does not close it.

### Bug prevalence

Happens every time I play

### Version

0.20.6.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-11-14 19:13
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10294

**Closed by Regalis11** 2022-11-14 19:13 UTC
Labels: Bug, Code
