### ISSUE TITLE
Overflowing health bar in higher resolutions

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#3596] opened 2020-08-18 14:22 UTC
2560x1440: ![healthbar.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/c6ffcfeb-d977-4cb1-95b2-09a9acfcd2d6)

**Comment by itchyOwl** [comment] 2020-08-19 09:12
Seems to be fixed on the bugfixes branch.

**Comment by Regalis11** [comment] 2020-08-19 09:20
Duplicate of Regalis11/Barotrauma-development#1653

**Closed by Regalis11** 2020-08-19 09:20 UTC
Labels: Bug, Code, Low prio
