### ISSUE TITLE
Switch item deconstructs into incorrect amount of plastic

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#9942] opened 2022-09-25 20:46 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Deconstructing the switch item yields 1 plastic, however the xml files indicate that it should deconstruct into 2 plastic.

### Reproduction steps

1. deconstruct a switch
2. observe that the output is 1x plastic + 1x copper, when it is expected to be 2x plastic + 1x copper.

### Bug prevalence

Happens every time I play

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-09-26 07:08
Duplicate of https://github.com/regalis11/barotrauma/issues/9721

**Closed by Regalis11** 2022-09-26 07:08 UTC
