### ISSUE TITLE
[Dev Version] Local chat is now global chat

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#1291] opened 2019-03-19 00:31 UTC
Using the local chat, in sub vs sub renegade and coalition can communicate from far distances.

**Comment by NilanthAnimosus** [comment] 2019-03-19 07:39
can confirm, all local chat messages are map wide and even cross-team in sub versus sub. its not just far distances, its literally opposite ports distances of over 1000 meters.

Radio chats work as intended, and voice chat far exceeds radio chat distance.

**Comment by Regalis11** [comment] 2019-03-19 09:40
Fixed in bfa6a09

**Closed by Regalis11** 2019-03-19 09:40 UTC
Labels: Networking-related, bug
