### ISSUE TITLE
allseeingeye is STILL breaking talent points

### ISSUE THREAD

**Issue by doornydew** [Regalis11/Barotrauma#7416] opened 2021-11-20 16:21 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
allseeingeye is still breaking the talent points, this was supposed to be fixed in the latest unstable, but it is not.

**Steps To Reproduce**
get "allseeingeye" then see how it shows how you can select 3 other talents, but have no points, but cant buy them either.

**Version**
v0.15.15.0 (unstable)

**Additional information**

**Comment by Regalis11** [comment] 2021-11-21 13:54
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7111

**Closed by Regalis11** 2021-11-21 13:54 UTC
