### ISSUE TITLE
[Unstable] After a level transition, all items displayed as part of other items glow

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#12238] opened 2023-06-27 22:37 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Specifically after transitioning between levels, all items within a tool (like a harpoon gun and welding tool) which are visible, will fully begin glowing, even shining through walls. 
![image](https://github.com/Regalis11/Barotrauma/assets/104232152/396eb36d-25d6-443c-8fcd-0e2df5d600af)
![image](https://github.com/Regalis11/Barotrauma/assets/104232152/60dec51e-fba1-4a2a-bb95-42d49cc06fdf)
![image](https://github.com/Regalis11/Barotrauma/assets/104232152/d40f69fc-ea08-4556-b362-425be9397acb)

### Reproduction steps

1.Have items with visible items inside on your sub
2.Transition between levels
3.The contained item will now begin glowing inexplicably next round

### Bug prevalence

Happens every time I play

### Version

Other

### -

v1.1.1.0 (Unstable Traitors)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-06-28 06:40
Duplicate of https://github.com/Regalis11/Barotrauma/issues/12014

**Closed by Regalis11** 2023-06-28 06:40 UTC
