### ISSUE TITLE
[BUG] "toogle_state"-inputs of "lamps & light components" seem to not work properly (at least when toogled by switches/buttons)...

### ISSUE THREAD

**Issue by DerEchteSpatz** [Regalis11/Barotrauma#1922] opened 2019-11-29 14:06 UTC
**Description**
When I am trying to toogle the state of "light components" or "lamps" by "buttons" or "switches" ON, those lights stay dead (i.e. they stay OFF, no matter how often you click the button/switch) but, for example, "sirens" DO get Activated properly...

**Steps To Reproduce**
I have taken the time to create a small vessel in order to make the problem clear. You can download it in the workshop (links included at the end) and compare the different wirings with each other, directly.
There, you can see that sirens get activated by "toogle_state" when switched ON by a button/switch, but not the lights/lamps (all three connected to the same button/switch).
If you use the setups with "set_state" instead, all three do work, properly.

**Version**
v0.9.5.1 of Barotrauma on a Win 7 64bit machine.

**Additional information**
Workshop-Link:
https://steamcommunity.com/sharedfiles/filedetails/?id=1923096003

**Comment by FamiliarBreakfast** [comment] 2019-11-29 19:38
I noticed this bug only seems to occur on subs made _after_ the bug first appeared. Lightswitches in older subs on the toggle lines work fine, but doing the same on new subs doesn't.

**Comment by rav2n** [comment] 2019-11-30 02:46
This error is present on older submarines. It's all about the new mechanics.

**Comment by Regalis11** [comment] 2019-12-03 10:13
Thank you for the test sub, this was very helpful in testing the issue! Should be fixed now in https://github.com/Regalis11/Barotrauma-development/commit/4e20c32a (private repo), and the fix will be included in the next patch.

One thing to point out though, the lights on the left (the ones connected to the "toggle" buttons/switches) are working as intended. They are are receiving a continuous signal to the "toggle_state" input, which means they get constantly toggled on and off.

**Comment by DerEchteSpatz** [comment] 2019-12-17 16:51
I think this can be closed now. The problem has been solved by the patch today.

**Closed** 2019-12-17 16:51 UTC
Labels: Bug, Code
