### ISSUE TITLE
Hulls "Hidden in game" does nothing: still appear on monitor, still affected by lighting

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#7379] opened 2021-11-18 21:24 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The "hidden in-game" option for Hulls does nothing.
Hidden Hulls still appear on the status monitor
Hidden Hulls are still affected by "draw behind subs" lighting

Hidden Hulls affected by draw behind subs lighting; the hull stays dark
![image](https://user-images.githubusercontent.com/73229309/142498634-a5820954-33f6-407e-881b-b10590c122c1.png)

Also see https://github.com/Regalis11/Barotrauma/issues/5837 for draw behind subs shenanigans

**Comment by Regalis11** [comment] 2021-11-19 09:00
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9f5f272280c8f066bd1b1855146aea339c4683bb

**Comment by MaaiG** [comment] 2021-11-19 10:55
Thx! I had the same problem)) when I making a mini-shuttle! ))

**Comment by ubertpendragon** [comment] 2021-12-07 15:14
Both status monitor and lighting fixed

Note that characters are not lit and need another source of lighting to match the background depending on light settings
![image](https://user-images.githubusercontent.com/73229309/145055292-1f620a5f-f187-4405-bf5e-ab862e463c71.png)

**Comment by Rokvach** [comment] 2021-12-08 11:56
The character not matching the lighting within the hidden hull seems to be caused by external light sources coming into the hull, can be tested by setting the Dugong's command rooms hull to be hidden ingame and then moving the top coilguns light around

Coilgun light pointing at the room
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/3ac5e013-1a3b-442f-bc68-33c62cb8260c)

Away from the room
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/415dfa2c-9f66-4648-ac8d-af66606cd61b)

**Comment by Rokvach** [comment] 2021-12-08 12:05
I don't see that above as an issue, or rather it is a very niche issue as there is no known use cases as to why you would like to hide a hull. We can adjust it later on if someone happens to come up with a proper use case for using hidden hulls and still sees the above lighting as a issue. But for now at least closing this as the original issue has been fixed.

**Closed by Rokvach** 2021-12-08 12:05 UTC
Labels: Bug, Code, Low prio
