### ISSUE TITLE
[Unstable] Bots have trouble with Return to Sub from cave

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#8132] opened 2022-01-30 16:50 UTC
**Description**
![image](https://user-images.githubusercontent.com/59519434/151708938-4270be2f-e3bc-470e-b7b6-c7b3228002ab.png)

Bots in the cave are trying to push to the ceiling when return to sub is issued
**Version**
Unstable

**Comment by ekqvist** [comment] 2022-02-09 11:09
It seems that this doesn't happen consistently.

Sometimes characters seem to navigate away from inside the cave correctly but will stay at the waypoint outside of the cave instead of returning to the sub from there. Sometimes they start swimming towards a wall briefly before they start using the pathfinding. I didn't manage to reproduce the issue of them continuously just swimming against walls inside a cave yet.

But I will keep debugging this since there seem to be some oddities with it.

**Comment by ekqvist** [comment] 2022-02-09 13:56
I tried to improve the return behavior in Regalis11/Barotrauma-development@849d55c by simplifying the objective logic a bit. The objective used to create separate sub-objectives for first navigating out of the cave and then navigating to the sub. Now it only creates a single sub-objective for that as the HumanAIController controls whether we should use pathing or just move directly towards the target.

**Comment by Rokvach** [comment] 2022-02-09 15:32
I didn't spot any issues with any of the caves I tested, seems to be working correctly. Closing.

**Closed by Rokvach** 2022-02-09 15:31 UTC
Labels: Bug, Needs testing, Code
