### ISSUE TITLE
[0.10.2.0] Spectating - Missing Entity Kick, Error while reading a network event

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3308] opened 2020-07-05 16:22 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
[test.txt](https://github.com/Regalis11/Barotrauma/files/4875237/test.txt)

**Version**
0.10.2.0

**Comment by Regalis11** [comment] 2020-07-06 08:19
Duplicate of #2382

**Closed by Regalis11** 2020-07-06 08:19 UTC
Labels: Bug, Code, Networking
