### ISSUE TITLE
Game FPS Drop 

### ISSUE THREAD

**Issue by RavenWintergale** [Regalis11/Barotrauma#8708] opened 2022-04-03 23:55 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Hello, my problem is the following: I start my multiplayer game with 40 to 30 FPS, but when the submarine starts to move or interact with other creatures or objects on the map my fps drops to 5 to 1 FPS. I tried several options, install and uninstall the game several times but it didn't fix this problem. I attach a file of the data at the time of the FPS drop problem. Greetings! 

**Version**
Game Version : 0.16.7.0  S.O : Windows 10 Pro (Version 21H2)

**Additional information**
(https://user-images.githubusercontent.com/102929797/161454026-a58224b6-3adc-4da1-b36f-4c24c4789bf7.png)

**Comment by RavenWintergale** [comment] 2022-04-03 23:58
PD : I forgot to mention that before the last updates I was playing multiplayer normally, without presenting any FPS problem (my FPS was 50 to 60)

**Comment by Regalis11** [comment] 2022-04-04 09:51
Duplicate of https://github.com/Regalis11/Barotrauma/issues/8510

**Closed by Regalis11** 2022-04-04 09:51 UTC
