### ISSUE TITLE
Motion Detector glitches, outputting 0s and 1s alternatively while standing right next to it

### ISSUE THREAD

**Issue by NaturalBornCamper** [Regalis11/Barotrauma#11329] opened 2023-02-23 21:40 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Wired a simple Motion Detector to a Text Display and watched the value change constantly between 0 and 1 as I'm standing right next to it. Here is the [savefile](https://www.dropbox.com/s/uyppqpk1dfuvogy/Bob_bugged_motion_sensor.save?dl=0).

https://user-images.githubusercontent.com/1697306/221036122-fc60285d-b2d9-411d-8e44-c6d0b5d2c2a2.mp4

### Reproduction steps

1. Load game
2. Go next to motion sensor as in the video
3. Watch the Text Display go crazy

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-02-24 07:33
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11146

**Closed by Regalis11** 2023-02-24 07:33 UTC

**Comment by NaturalBornCamper** [comment] 2023-02-24 17:56
Ah thanks a million and my bad for not finding it! I searched "is:open" so the duplicate issue didn't show up ;)
