### ISSUE TITLE
[Unstable] Lighting a nitroglycerin shipment on fire crashes the game without updating the crash log

### ISSUE THREAD

**Issue by TheMinerBoy** [Regalis11/Barotrauma#10937] opened 2023-01-14 21:44 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

So I was doing the prisoner transport + handle with care mission in the save when I ran into some ballast flora in the rear ballast. I put a fire extinguisher on the ground near the ballast tank, drained it, and used a flamer on the ballast flora. Unfortunately, it caught the edge of the hatch on fire, so I grabbed the fire extinguisher off the ground, tried to aim it, and .... the game crashed. I went to look at the crashreport.log file in the main Barotrauma directory, but it wasn't updated. 

I don't know if this is a fundamental bug or if the explosion was simply too big for the game to handle. It would have been nice to witness my dumb death either way, though.

### Reproduction steps

1. Get a "Handle with Care" mission involving nitroglycerin
2. Use a flamer to start a fire under the crates
3. Game crashes
### Bug prevalence

Happens every time I play

### Version

0.21.1.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
I did not get a crash report somehow
```

**Comment by Regalis11** [comment] 2023-01-16 08:43
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10902

**Closed by Regalis11** 2023-01-16 08:43 UTC
