### ISSUE TITLE
[Unstable] Green gas depletes all oxygen tanks in exosuit

### ISSUE THREAD

**Issue by soledad630** [Regalis11/Barotrauma#10715] opened 2022-12-14 14:17 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The green gas that depletes oxygen from suit oxygen tanks will deplete oxygen tanks inside the storage slots in exosuits as well.

### Reproduction steps

1. Make and equip an exosuit.
2. Put in a stack of oxygen tanks in exosuit storage slots.
3. Take exosuit into green gas caves.

### Bug prevalence

Happens every now and then

### Version

0.20.14.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-12-14 14:24
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10423

**Closed by Regalis11** 2022-12-14 14:24 UTC
