### ISSUE TITLE
NPCs do not fire their gun at the target or player

### ISSUE THREAD

**Issue by Hanfalk** [Regalis11/Barotrauma#11548] opened 2023-03-15 16:25 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

NPCs do not fire or shoot back at the player, only in Melee ranges, and stand there aiming instead until you get close enough to trigger them. When you leave their range, they will keep aiming again and do nothing.

Before 1.0 release, the NPCs could shoot and fight with no issues at all, but right now, the AI is broken to the point it will just stand there. If they have any form of ranged weapon, they will use it instead of any melee weapon. There are Guards with Stun-Batons standing with a Tranq Gun or Revolver in their hands, aiming at the player or foe, but do not do anything.
This opens up a game-breaking element for Barotrauma where it sucks out the fun in firefights in Outposts with AI acting like this. Worse yet, your own designated Bots to kill or attack creatures onboard the Submarine, making the bot crew useless for self-defense.

### Reproduction steps

**Note:**
The best results are in City Outposts or Bandit Outposts where the majority have firearms to test with.

1. Start up any game, Multiplayer or Singleplayer, and always the same results.
2. Pick starting values of High Supplies (makes this easier to replicate to save time). Played on low Supplies and hard difficulty, same results anyway.
3. Order your own Crew (Bots) back to the sub.
4. Arm yourself with weapons, ammo, and some medication.
5. Go up to the station and find any guards, and shoot them at a distance.
6. Observe their action and reactions.
7. If the Guard had a Tranq Gun, it will either fire or just stand there aiming at you. Any firearm such as a Revolver, SMG, Riot Shotgun (etc), it will just stand there aiming at you.
8. Approach the target aiming at you. Watch and hear the shooting at close ranges.

### Bug prevalence

Happens every time I play

### Version

v1.0.7.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-03-15 16:26
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11497

**Closed by Regalis11** 2023-03-15 16:26 UTC
