### ISSUE TITLE
(Unstable Version) Bought Items Sometimes Appear In Floor Of Sub

### ISSUE THREAD

**Issue by KermTheFerg** [Regalis11/Barotrauma#3372] opened 2020-07-16 02:57 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

Like the Title Says, for some reason bought items in crates will sometimes be spawned stuck inside of the sub's floors. This hasn't happened with singular items only crates. I believe it is due to an excess amount of crates in the cargo area. This happened with the Azimuth.

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

Buy multiple crates worth of items, leave the crates in the cargo, buy more crates and they will possibly be stuck in the floor.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

This happened within the unstable version of the game in the campaign mode.

**Additional information**

We don't know if this is consistent to a certain extent. It happened twice, we moved the empty crates off the ship and the crate spawned fine.

**Comment by Regalis11** [comment] 2020-07-16 06:39
Duplicate of #3023

**Closed by Regalis11** 2020-07-16 06:39 UTC
