### ISSUE TITLE
Level generation: the target outpos is sometimes positioned too close to the level walls

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#3595] opened 2020-08-18 14:15 UTC
Sometimes the target outpost is positioned so that it's difficult or even impossible to dock to the outpost, because the level walls are too close in the left. The case pictured below is not the worst, because here it's possible to dock, if you are really careful.

![target_outpost_position.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/1801f7cb-32b0-485b-81ff-468e6051e633)

![target_outpost_position2.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/aac3a9ed-c2e7-4ce9-a29c-b40f8d40a5d8)

**Comment by Regalis11** [comment] 2020-08-19 09:23
If anyone finds a seed where there's not enough room to dock, please post it here

**Comment by itchyOwl** [comment] 2020-08-19 10:55
As you probably noticed, the seed for the given case can be seen in the upper image.

**Comment by Regalis11** [comment] 2020-08-19 12:44
I mean a level where the walls prevent the sub from docking. This example case doesn't seem that bad to me, there's plenty of room if you approach from the left.

**Comment by itchyOwl** [comment] 2020-08-20 08:17
It depends on the sub size. I'd say it would be safer to add such a margin that submarines always can dock, no matter what the size is.

**Comment by Regalis11** [comment] 2020-08-21 07:21
The level generation should already take the size of the sub into account and place the outpost in a way that there's enough room to dock. That's probably not working correctly, but I've not run into a level where docking isn't possible so far, so a seed would be very helpful in fixing this.

**Comment by itchyOwl** [comment] 2020-08-24 09:04
So let's post any seeds of those occasions here. I've encountered many cases, but they are relatively rare, so it might take time to solve this one.

**Comment by ezjamsen** [comment] 2020-08-26 11:44
Erlangshen
Wolstone

**Comment by Regalis11** [comment] 2020-08-26 11:51
@ezjamsen Could not reproduce. How are you generating those levels (level editor, outpost level encountered in the campaign)?

![eeeeeee3456](https://user-images.githubusercontent.com/14351070/91300233-9d239480-e7ab-11ea-9895-43236c1e1dea.png)

**Comment by ezjamsen** [comment] 2020-08-26 11:52
Outpost level during campaign. Recording campaign seeds and will include those as I encounter more problems. The issue seems to be fairly common, I produced those two seeds in a 5 minute period of play

**Comment by Regalis11** [comment] 2020-08-26 11:53
Could you send the save file?

**Comment by Regalis11** [comment] 2020-08-26 13:15
Looks like that was a different issue, the the outpost overlapped the sub, not the sub with the level walls. Fixed that one in 1b2fdf3

**Comment by Regalis11** [comment] 2020-10-20 09:19
No known steps to repro, closing

**Closed by Regalis11** 2020-10-20 09:19 UTC
Labels: Bug, Code, Need more info
