### ISSUE TITLE
AI suffocation in mining outpost

### ISSUE THREAD

**Issue by Testingforfree** [Regalis11/Barotrauma#7743] opened 2021-12-13 08:48 UTC
There is a possibility for a room to generate in the mining outpost mines that does not have a vent

AI may idle in room and deplete oxygen, AI will continue to use oxygen canister until critical but may not vacate room and suffocate.

**Comment by ekqvist** [comment] 2021-12-13 09:03
Duplicate of #7662

**Closed by ekqvist** 2021-12-13 09:03 UTC
