### ISSUE TITLE
Pump, Fabricator and Deconstructor bug

### ISSUE THREAD

**Issue by RagingTuna** [Regalis11/Barotrauma#7940] opened 2021-12-26 22:25 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Non-Ballast pumps, deconstructor, fabricator, and some lights do not function. Trying to craft or recycle an item yields the "insufficient power" message. The reactor still outputs the same amount of power as it would in a ship without the bug. pumps say they are powered when looked at, but will not pump out water.

**Steps To Reproduce**
On the Humpback, I unlocked the "Bounty Hunter" perk for the captain, then left the game paused for a few hours to run some errands. I came back, and the fabricator and deconstructor no longer functioned, and the light near them was off. I started another mission after that, and after coming back into the ship from EVAing I found that the water in the bottom of my boat wasn't draining.

**Version**
Windows 10 on the latest update currently available, the "Holiday Update and Greetings"

**Additional information**
 It's my first time putting in a bug report, so I'm sorry if I'm not much help.

**Comment by gerakis** [comment] 2021-12-27 00:54
Were you daisy chaining relays to power them? There is currently a bug involving daisy chained relays. I tried reporting that bug but they just marked it as a duplicate of some other completely unrelated bug. Not too cool. It takes a while to test these bugs out and report them. I wish they wouldn't just delete the report after reading for 30 seconds.

**Comment by RagingTuna** [comment] 2021-12-27 17:23
Hey, thanks for getting back to me! I hadn't done any wiring work on the
sub yet. the issue didn't resolve itself after restarting the app or
computer, but when I came back the next day however, the problem had
magically resolved itself. I'm starting to wonder if it might be on my end,
and thanks for the quick response :)

**Comment by Regalis11** [comment] 2022-01-04 12:06
This may be a dumb question, but I wonder if the devices or some of the junction boxes that supply power to them might've been broken? 

@gerakis
Sorry about that, I did read through the [report](https://github.com/Regalis11/Barotrauma/issues/7864) a bit too hastily and thought it was a duplicate. I've now reopened the ticket.

**Comment by RagingTuna** [comment] 2022-01-04 18:05
All of the junction boxes were fine, I repaired them each individually as I
checked them for wiring shenanigans but the issue persisted. Sorry for late
response, btw.

**Comment by Regalis11** [comment] 2022-02-04 10:19
No known steps to repro, closing

**Closed by Regalis11** 2022-02-04 10:19 UTC
Labels: Bug, Need more info, Code
