### ISSUE TITLE
[Factions] Assault rifle recycle fabrication is named identically

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10507] opened 2022-11-21 20:09 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Very simply, another nitpick, the recipe for recycling assault rifle magazines is identical to the regular name of magazine fabrication 
![Uploading image.png…]()

### Reproduction steps

1.Check the magazine names on a fabricator

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-11-22 07:46
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10486

**Closed by Regalis11** 2022-11-22 07:46 UTC
