### ISSUE TITLE
when steam interface is using non-english, Updating steam workshop mod description will override english one

### ISSUE THREAD

**Issue by AzureNocte** [Regalis11/Barotrauma#11890] opened 2023-04-22 22:31 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

A little complicated to explain, the thing happened is that when I update a barotrauma mod on steam, if I'm using non-english language interface of steam, and the mod has different language despcrition(says it has both english, finnish, russian description), it will show the language which steam is using(non english) by default and override the mod english description , not the corrisponding language.

And it seems this problem is not related to the language setting of barotrauma.

### Reproduction steps

1. create a mod, edit its title and description covering different languages on steam(like english and finnish)
2. go to steam setting- interface, use a non english language(like finnish)
3. open barotrauma, enter mods, it shows the language steam is using(finnish)
4. update the mod, go back to steam workshop, find that english description overriden.

### Bug prevalence

Happens regularly

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-04-23 07:38
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11105

**Closed by Regalis11** 2023-04-23 07:38 UTC
