### ISSUE TITLE
Can't spectate in a server with a started round

### ISSUE THREAD

**Issue by Coalyou123** [Regalis11/Barotrauma#3392] opened 2020-07-19 00:30 UTC
[crashreport_object.log](https://github.com/Regalis11/Barotrauma/files/4943028/crashreport_object.log)

**Comment by Regalis11** [comment] 2020-08-20 11:31
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3019

**Closed by Regalis11** 2020-08-20 11:31 UTC
Labels: Bug, Code, Networking
