### ISSUE TITLE
[0.9.801] Missing Entity / ExcessiveDesyncOldEvent

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2446] opened 2020-03-16 18:06 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Still suffering from Missing Entity at start of round in campaign once we start buying more stuff / get closer to center.
[ServerLogs.zip](https://github.com/Regalis11/Barotrauma/files/4339669/ServerLogs.zip)

Also, still seen some players getting ExcessiveDesyncOldEvent at the start of round. Saw it happened to one player during the round too.

**Version**
0.9.801

**Comment by Regalis11** [comment] 2020-03-17 08:33
Duplicate of #2382

**Closed by Regalis11** 2020-03-17 08:33 UTC
