### ISSUE TITLE
Microphone Bug

### ISSUE THREAD

**Issue by VelonacepsCalyxEggs** [Regalis11/Barotrauma#1284] opened 2019-03-16 10:28 UTC
**Description**
Then im joining a server I m having a problem with mic. it says *Error* cant find suitable capture
![image](https://user-images.githubusercontent.com/48419312/54473912-47457180-47ef-11e9-8889-869aa7f65b2c.png)
I have tried to fix it in option but. no

**Version**
Windows, Barotrauma 1.0

**Additional information**
nothing here

**Comment by VelonacepsCalyxEggs** [comment] 2019-03-16 10:33
I found why

**Comment by VelonacepsCalyxEggs** [comment] 2019-03-16 10:33
Maybe the problem is that the "microphone" written in Russian

**Comment by VelonacepsCalyxEggs** [comment] 2019-03-16 10:33
that was a problem. make barotrauma support kirrilitsa

**Comment by NilanthAnimosus** [comment] 2019-03-16 11:51
This issue has been fixed for the next version from soft-locking the game when no valid microphone is found. the game should support in theory whatever the local operating system has for its microphone input.

This shouldn't be an issue from your localization or russian keyboard layout.

If you have no plugged in microphone or your microphone is turned off, despite game settings, it will likely throw up this dialogue box.

if its active, but turned off in the game it should remove it I believe.

**Comment by CommanderMark** [comment] 2019-03-16 15:18
Duplicate of #1262.

> that was a problem. make barotrauma support kirrilitsa

I don't think a Russian keyboard is the issue here.

**Comment by AbominationBanisher** [comment] 2019-03-16 16:08
> Duplicate of #1262.
> 
> > that was a problem. make barotrauma support kirrilitsa
> 
> I don't think a Russian keyboard is the issue here.

I have a russian keyboard and this happens to me if I enable mic, so this might be the case actually.

**Comment by Regalis11** [comment] 2019-03-17 18:26
How do you know it's caused by the russian keyboard? I can't really think of any reason why it would have an effect.

**Comment by AbominationBanisher** [comment] 2019-03-18 20:07
> How do you know it's caused by the russian keyboard? I can't really think of any reason why it would have an effect.

Just pointing out a coincidence. Might not be the cause. Might be the cause.

**Comment by NilanthAnimosus** [comment] 2019-03-19 08:04
it was in theory fixed by commit 7df1543d7cedb417c73e1297adfc342f4ecd96f6 and the code for said fix was not released or part of version 0.8.9.5, which was when this git issue was written as the current version, so issue #1262 which was fixed by commit 7df1543d7cedb417c73e1297adfc342f4ecd96f6 in theory should have corrected this problem.

coincidence isn't really worth much unless there is no other causes that are likely to be thus a need to come up with likely scenarios, we do have a very likely culprit though as we had a fix for it, if it continues to occur though beyond the current steam update 0.8.9.6 (19th march 2019) please respond back to this issue that it still occurs in the latest steam copy.

**Closed** 2019-03-23 19:05 UTC
Labels: bug, need more info
