### ISSUE TITLE
Power desync after disconnecting and reconnecting devices

### ISSUE THREAD

**Issue by mygamingaccount** [Regalis11/Barotrauma#8967] opened 2022-04-25 13:43 UTC
**Description**
Disconnecting the power_in from devices causes the device to no longer work even after reconnecting, however appears to work on the client side.

**Steps To Reproduce**
Exhibit A:
Disconnect oxygen generator from the power grid then reconnect
Client side effects of the O2 generator appear (sound is heard, vent fans rotate) but ship O2 quickly runs out causing teammates to pass out

Exhibit B:
Disconnect and reconnect Winterhalter science bay bilge pump
Client side the water seems to be pumped out and the bilge is dry
Walking near the diving suits in the seemingly dry bilge you will observe O2 loss as if underwater
Ship buoyancy is affected and the ship is sinking
Cut the glass wall to the airlock which has a working pump
Water now rubberbands, level jumps up and down until it is pumped out server side.

Exhibit C:
Disconnect fabricator and reconnect
Attempting to fabricate: "Insufficient power"

**Version**
Host was running on Windows. All clients observed the issue independent of platform.
V0.17.12.0

**Comment by Regalis11** [comment] 2022-04-26 08:18
Duplicate of https://github.com/regalis11/barotrauma/issues/8873

**Closed by Regalis11** 2022-04-26 08:18 UTC
