### ISSUE TITLE
Watchman not spawning at outpost on singleplayer campaign

### ISSUE THREAD

**Issue by MelonnMan** [Regalis11/Barotrauma#5905] opened 2021-05-28 03:22 UTC
After completing a mission on my singleplayer campaign, I docked the sub and the game crashed as I loaded the outpost. I tried to load the save twice after and again, the game crashed due to: Could not find human prefab "watchman" from "outpostnpcs1".

The following crash reports will provide what I hope is enough information to solve the issue.
[crashreport (6).log](https://github.com/Regalis11/Barotrauma/files/6557915/crashreport.6.log)
[crashreport (7).log](https://github.com/Regalis11/Barotrauma/files/6557916/crashreport.7.log)
[crashreport (8).log](https://github.com/Regalis11/Barotrauma/files/6557917/crashreport.8.log)

If any information was left out/needed, I will certainly attempt to aid in any way possible.

**Comment by Regalis11** [comment] 2021-05-28 08:58
This seems to happen because the game can't find the "watchman" human prefab. I'd guess this is caused by the modifications the installed mods do the human prefabs (probably the "Normal Health Outposts NPCs" mod).

I added some null checks that should prevent this from crashing the game: https://github.com/Regalis11/Barotrauma-development/commit/9a3c0f8ac9cc8c8f996f4779ba64f79b202a4e27

**Comment by Rokvach** [comment] 2021-06-07 07:39
Tested, working correctly. Closing.

**Closed by Rokvach** 2021-06-07 07:39 UTC
Labels: Bug, Code, Crash, Modding
