### ISSUE TITLE
0.9.9.0 Double clicking to move items sometimes fails

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#2680] opened 2020-04-24 01:17 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Double click items in menus now sometimes fails.
https://streamable.com/1rzads

**Version**
0.9.9.0

**Comment by Regalis11** [comment] 2020-04-28 09:09
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/fe4e98f760a8aacb3be5600db7cdd78f04836e4c

**Comment by thegrb93** [comment] 2020-05-02 03:31
0.9.9.1 still a little jank sometimes. https://streamable.com/px50g0

**Comment by thegrb93** [comment] 2020-05-02 03:39
Nvm it's behaving the same as before the patch so I'm assuming it's not in it.

**Comment by Rokvach** [comment] 2020-05-04 11:47
Wasn't able to reproduce, seems to be working correctly. Closing.

**Closed by Rokvach** 2020-05-04 11:47 UTC
Labels: Bug, Code

**Comment by thegrb93** [comment] 2020-05-04 17:06
@Rokvach what version? It's definitely not working in 0.9.9.1. Seems to get worse the more players are in the server.

**Comment by Rokvach** [comment] 2020-05-05 06:33
Coming with the next patch, no ETA.

**Comment by thegrb93** [comment] 2020-05-05 08:28
Ok cool
