### ISSUE TITLE
Disconnected from multiplayer campaign (missing entity Barotrauma.Waypoint)

### ISSUE THREAD

**Issue by MudraptorSeks** [Regalis11/Barotrauma#8501] opened 2022-03-10 18:20 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![unknown](https://user-images.githubusercontent.com/87497640/157728601-771bb4df-6e45-4a46-9d57-88ee41fdc2af.png)
it used to happen to both of my friends, but replacing the sub in the save with a fresh copy of the sub fixed it for one friend, but the other is still kicked (see chat)

**Steps To Reproduce**
honestly not sure, it's weirdly specific, possibly an issue with the save or characterdata itself, or maybe the submarine: [https://drive.google.com/drive/folders/1Ns8vRoAom4YHeu0cu4JGvVLoXK_kC98P?usp=sharing](url)

**Version**
most recent unstable at time of posting, windows 10

**Additional information**
please i really want to fix this, i just want to FOR ONCE finish multiplayer campaign
if this happens to be a duplicate of a post i didn't see, please at least tell me how i should fix it

**Comment by Ek-Videogames** [comment] 2022-03-12 15:57
This is a longstanding catastrophic packet loss enigma.

I'm pretty sure the devs added a new kind of log `"event_error_log"` to help try to figure out what causes it, so including that would also be good.

**Comment by MudraptorSeks** [comment] 2022-03-12 16:00
I see. 
I'll try to find this log

**Comment by Regalis11** [comment] 2022-03-14 09:24
Thank you for the report! This is indeed [a known issue](https://trello.com/c/jw4XTxUA/258-players-disconnecting-with-an-entity-not-found-error-in-multiplayer), and unfortunately something that can be caused by various different reasons (some of which we still haven't been able to figure out and fix).

If you can find those event_error_log files (instructions in the link above), that would help us a lot in diagnosing the issue. Thanks and sorry for the trouble!

> This is a longstanding catastrophic packet loss enigma.

What makes you think this is caused by packet loss? I can't think of how that could be the cause: the client wouldn't be processing this network event if it hadn't received all the previous ones. Previously all these "missing entity" errors have been caused by either the clients reading some received packet incorrectly or a discrepancy in the loaded entities (e.g. clients loading an incorrect shuttle or generating outposts incorrectly).

**Comment by Regalis11** [comment] 2022-04-20 17:39
Duplicate of https://github.com/Regalis11/Barotrauma/issues/6265

**Closed by Regalis11** 2022-04-20 17:39 UTC
Labels: Bug, Code, Networking
