### ISSUE TITLE
[Unstable] Running two dedicated servers on the same ip address causes one of them to have ? as ping on the server list

### ISSUE THREAD

**Issue by evilfactory** [Regalis11/Barotrauma#9967] opened 2022-09-30 21:06 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Running two dedicated servers on the same IP Address causes one of them to have "?" as ping on the server browser, i believe this is caused by this dictionary
https://github.com/Regalis11/Barotrauma/blob/dev/Barotrauma/BarotraumaClient/ClientSource/Networking/ServerList/PingUtils.cs#L17
not accounting for different ports.

### Reproduction steps

1. Host two dedicated servers on the same IP Address, but different ports.
2. Look at the server list and see that one of them will have "?" as ping.

### Bug prevalence

Happens every time I play

### Version

0.19.8.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by mygamingaccount** [comment] 2022-09-30 22:22
Sorry for your work ending in the PRgatory

**Comment by evilfactory** [comment] 2022-10-01 00:00
> Sorry for your work ending in the PRgatory

Didn't know they were already reworking the server list code, so it pretty much became obsolete 😕

**Comment by Regalis11** [comment] 2022-10-01 09:52
Duplicate of https://github.com/Regalis11/Barotrauma/issues/6412

Also, thank you for the PR, even though we didn't end up using it. I don't think the way the issue was addressed is ideal, because determining if we've already pinged the address based on the ServerInfo instance instead of the IP will lead to pinging the same IPs multiple times.

**Closed by Regalis11** 2022-10-01 09:52 UTC
