### ISSUE TITLE
Characters using Controllers like Hospital beds are sometimes in an incorrect position

### ISSUE THREAD

**Issue by Working-Joe** [Regalis11/Barotrauma#8936] opened 2022-04-23 21:46 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Characters using controllers like chairs or beds are fairly often in the wrong position.

For instance, using hospital beds occasionally gives rise to _The 2011 plank event_
![image](https://user-images.githubusercontent.com/50582661/164946815-a76a4063-ad0b-45a5-8fed-6abd8f5227a8.png)

It might be related to flipping these items. Controllers flipped upside down have always been broken. leading to poses such as 
 _Ascension_ 
![image](https://user-images.githubusercontent.com/50582661/164946762-bab1e25c-a648-4017-93be-0844b79f33a9.png)

However, the plank pose occurs on both (horizontally) flipped and unflipped beds. Reloading the sub seems to fix it, but the next load it is broken again. It can be broken on one bed while being fixed on another, both in the same orientation.

**Steps to reproduce**
- Place a few hospital beds
- Flip a few (optional)
- Laugh at this funny pose

**Version**
Unstable V0.17.13.0 Hotfix

**Comment by Mannatwo** [comment] 2022-05-22 17:30
i second this
also happens with chairs, so i am assuming its generalizable to all controllers
seems like flipped chairs alternate between working as intended and not applying the flip to the controller offsets when entering test mode in the sub editor

**Comment by Regalis11** [comment] 2022-05-25 09:26
The 1st bug seems to have been caused by the same issue as https://github.com/regalis11/barotrauma/issues/9097

Disabled vertical flipping of beds in https://github.com/Regalis11/Barotrauma-development/commit/de8f10e68be6857b55705f849fa3b6c527332522

**Comment by Working-Joe** [comment] 2022-05-25 10:30
Thanks for fixing this!

Apologies for making a problem out of this minor thing, but would it be possible to disallow interacting with vertically flipped beds instead? It's common to use flipped interactable items as decorations (set to be non-interactable). I'd almost rather have the borked pose with vertically flipped beds. :) As long as horizontally flipped beds are alright.

**Comment by Regalis11** [comment] 2022-06-02 09:41
Actually yeah, that's a better way to address this! Changed in https://github.com/Regalis11/Barotrauma-development/commit/2472c1571bc94e00907c72f95de2b950382410fb

**Comment by Wheatley1001** [comment] 2022-06-03 17:12
This issue still persists with the regular bunk (you can still interact with the bunk which is flipped vertically).
![image](https://user-images.githubusercontent.com/105495756/171912921-886af2e3-99a6-4cc6-9783-6d82bb75b526.png)
Also unsure if this relates to this specific issue, but the Military Bunk causes players to shake sometimes when you interact with it.

**Comment by Rokvach** [comment] 2022-06-06 01:41
You can still sleep in a upside-down bed if you rotate it 180 instead of just flip it
![image](https://user-images.githubusercontent.com/7299826/172080862-37bbaa02-772f-4e89-a512-c0bd969855f1.png)

**Comment by Regalis11** [comment] 2022-06-06 07:44
@Wheatley1001 fixed in https://github.com/Regalis11/Barotrauma-development/commit/5188de48fe6342b75fe72fbb0414ef5a4663298e

@Rokvach I'd consider that a separate issue

**Comment by Rokvach** [comment] 2022-06-10 07:43
Tested, working correctly. Closing.

**Closed by Rokvach** 2022-06-10 07:43 UTC
Labels: Bug, Code
