### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by JazunOwO** [Regalis11/Barotrauma#9167] opened 2022-05-19 00:43 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

tried auto downloading neurotrauma from the workshop

disabled analytics so just thought I'd pop in and shove it here

### Reproduction steps

no idea

### Bug prevalence

Just once

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 19/05/2022 01:39:20)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


095A39E9025803C60F024FFA1049DA7B


Game version 0.17.15.0 (ReleaseWindows, branch release, revision 62bb4ecab3)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.ModDownloadScreen
SteamManager initialized
Client (Round hadn't been started)


System info:
    Operating system: Microsoft Windows NT 10.0.22000.0 64 bit
    GPU name: NVIDIA GeForce GTX 1650 SUPER
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.
 (SharpDX.SharpDXException)
Device removed reason: HRESULT = 0x887A0007
Target site: Void CheckError()
Stack trace: 
   at SharpDX.Result.CheckError()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 1017
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 511
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59


Last debug messages:
[19/05/2022 01:38:16] Hash calculation for content package "Neurotrauma" didn't match expected hash (4D7F1CFE1ADF9A15BCD152924A029C22 != 182319FC8B53C6E1C92F0A7A475C9363)
[19/05/2022 01:38:15] Attempting to open ALC device "OpenAL Soft on Headphones (Realtek(R) Audio)"
[19/05/2022 01:38:12] Logged in as Jazun (SteamID STEAM_1:1:451896504)
```

**Comment by Regalis11** [comment] 2022-05-19 07:15
Duplicate of https://github.com/Regalis11/Barotrauma/issues/1833

**Closed by Regalis11** 2022-05-19 07:15 UTC
