### ISSUE TITLE
the mission "jailbreak_sootman" can't be finished on mod submarine

### ISSUE THREAD

**Issue by CurvasProximos** [Regalis11/Barotrauma#11878] opened 2023-04-21 01:48 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

(as I understand it, the game cannot always find the necessary coordinate on the mod submarine to move the NPC to a given location)
The NPC stands still and does not go to the submarine
he burned the outpost manager 12 minutes ago and refuses to go to the submarine, and because of God's regime, I can't stun him and drag him there by force
(the only mod we use is the submarine itself: The old Orca 2 ->(https://steamcommunity.com/sharedfiles/filedetails/?id=2716328719) modified in the submarine editor)
![image](https://user-images.githubusercontent.com/101333283/233517966-f8d2e377-bbaf-4fd6-ba6a-fa6c5c15e402.png)
((when you change the submarine to a vanilla one, then everything works if the city was generated differently))

### Reproduction steps

create a server
Dock on a mod-submarine in the right city
Find the right NPC in the city
and finish the dialogue with him
He runs away and sets fire to the manager
It costs an infinite amount of time

### Bug prevalence

Happens every time I play

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-04-21 08:27
Thank you for the report! It seems the issue here is that the waypoints aren't set up properly in this sub, and there's no way for the bots to navigate from the sub's airlock to the command room. 

Here's one hatch without a waypoint, but there could be more issues elsewhere too:
![image](https://user-images.githubusercontent.com/14351070/233585707-fdb6e08d-57b3-45bb-a782-0214a11992ba.png)

In any case, the mission shouldn't get stuck like this regardless of the submarine. I did some changes in https://github.com/Regalis11/Barotrauma-development/commit/598e3404d5fb2aa6cf641a7be1edb5d84d1e3586 (commit in our private repository) to make this a little more robust: now, if the NPC fails to find a way to the submarine, it'll start following the player instead.

**Comment by CurvasProximos** [comment] 2023-04-21 09:37
Yes, thank you, I have already corrected the routes in my editor. The main thing is that other players do not have a similar problem. I hope your edits and my report will help others not to face this. All the best)

**Comment by Regalis11** [comment] 2023-04-21 09:59
Thank you for taking the time to close this, but we'll keep it open until we've tested the fix internally and verified it's working as intended

**Comment by CurvasProximos** [comment] 2023-04-21 10:15
@Regalis11 oops. Sorry. if it doesn't bother you, I'm not sure, but I may have found another error, but I described it in a comment in an already open "discussion", if I may say so. Please take a look, if it's not too much trouble. Well, or I can create a separate theme, although you already have a lot of them) https://github.com/Regalis11/Barotrauma/issues/11725

**Comment by Regalis11** [comment] 2023-04-21 10:17
> I may have found another error, but I described it in a comment in an already open "discussion", if I may say so. Please take a look, if it's not too much trouble. 

Thanks! I don't understand the comment, but I've linked the issue to the Russian localization team, and hopefully they will. :)

**Comment by CurvasProximos** [comment] 2023-04-21 10:20
AHAHAHA. I was talking about my comment that I left there, I thought it was possible since they do it. I'm sorry that I don't know English well)))

**Comment by Rokvach** [comment] 2023-06-01 08:37
Tested, working correctly, closing.

**Closed** 2023-06-01 08:41 UTC
Labels: Bug
