### ISSUE TITLE
Linked Submarine on Kastrull not Respawning

### ISSUE THREAD

**Issue by littlelegz** [Regalis11/Barotrauma#4640] opened 2021-01-05 06:26 UTC
**Description**
Gamemode: Campaign
Submarine: Kastrull (Attack)

Not modded

I've been playing the campaign with some friends and on one occasion we lost power in the drone, and were forced to dock while not having the drone docked to our submarine. After docking our submarine to an outpost, I attempted to replace lost shuttles, but was then given an error reading:

"Failed to load a linked submarine (empty XML element). The save file may be corrupted."

I have attempted to switch off and back onto the Kastrull, but this error persists. 

**Steps to reproduce:**
Not sure but here's my best guess.
Attempt docking the Kastrull without the drone being docked to the submarine. 
This was performed after a salvage artifact mission leading us to an alien ruins. Drone runs out of battery and is stuck to the top of our submarine when we dock.

**Version** 
v0.10.0.9

**OS**
Windows

**Comment by Regalis11** [comment] 2021-01-05 13:59
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3459

**Closed by Regalis11** 2021-01-05 13:59 UTC
Labels: Bug, Code
