### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by 456gr** [Regalis11/Barotrauma#9648] opened 2022-07-27 05:38 UTC
Good afternoon, today I was trying to finish my submarine and ran into a problem: 2 large motors that stood on top of each other create a water wall with strong pressure, so it is not possible to move around the submarine, and even if they are removed, the wall does not disappear and the character cannot get out of it, how do I solve this problem?

**Comment by pakvg85** [comment] 2022-07-27 06:06
1. Do not ever again name your issue report like this.

**Comment by 456gr** [comment] 2022-07-27 12:08
> 1. Никогда больше не называйте свой отчет о проблеме так.

What should I call it then? and do you know something about my problem?

**Comment by Krzeszny** [comment] 2022-07-27 13:30
I can't imagine what your issue is. Can you first of all, **use the template**? And secondly, please provide screenshots or even a video.

**Comment by pakvg85** [comment] 2022-07-27 14:07
> What should I call it then?

Here is the bug report template: https://github.com/Regalis11/Barotrauma/issues/new?assignees=&labels=&template=bug_report.yml.
Even before creating a bug report, spend some time and try to find already existing issue reports by keywords (it is not a big deal if you fail to find it, at least you tried).
If not found any - start creating your bug report. Fill the "Title" field with something that is short and make sense - that will show devs and other users that you have spent time on it.
Next fill the "What happened?" field - describe your problem and what do you expect the game to act. I highly recommend to attach a video of screen recording (I use MovAvi Video Suite -> Screen recording tool) - this will also show that you spent some time for your bug report.
Next fill "Reproduction steps" and other fields.

>  and do you know something about my problem?

I didn't bother myself understanding your plain text without video attached :-)

**Comment by NilanthAnimosus** [comment] 2022-07-28 05:03
I honestly only have a vauge understanding of the problem here, it sounds like motor means submarine engines, and they maybe generate a water force and you get trapped into it somehow?

but then you remove them (huh?) - this part then makes this cease to make sense. If there isn't enough information to reproduce or know what the issue is about / what the problem exactly is its unlikely to ever be fixed or looked into.

**Comment by Krzeszny** [comment] 2022-08-01 14:34
> Here is the bug report template: https://github.com/Regalis11/Barotrauma/issues/new?assignees=&labels=&template=bug_report.yml

I'm very curious HOW you've managed to skip using the template.

That aside, if you want the issue to get fixed, you should upload here the submarine that's not working (either as a file or send a link to its Workshop page).

> I didn't bother myself understanding your plain text without video attached :-)

You're expecting me to understand your explanation of some rare bug, something you saw on your screen, without providing enough details. A video showing how to reproduce the issue (or what causes it) would be very helpful, but it would be even more helpful if you shared the bugged submarine's save file.

>and even if they are removed, the wall does not disappear and the character cannot get out of it, how do I solve this problem?

What is the wall?

**Comment by Regalis11** [comment] 2022-08-15 06:52
Insufficient information to address the issue, closing

**Closed by Regalis11** 2022-08-15 06:52 UTC
Labels: Need more info
