### ISSUE TITLE
Can't Craft in Multiplayer

### ISSUE THREAD

**Issue by BigMike3180** [Regalis11/Barotrauma#10244] opened 2022-11-05 02:12 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

After extensive testing, I have narrowed the problem down to being unable to craft in multiplayer only. Me and my friends are using a custom sub and discovered today that we cant craft anything in the fabricator either on board the sub or on the station.  We tried moving the sub and save to another friend's PC where he was able to host the custom sub and we could craft just fine. I launched a single-player campaign where I could craft on both the custom sub and any random sub. I tried hosting a different vanilla sub and still, no one could craft. It is only multiplayer sessions that I host where no one can craft, I made sure the custom subn we were using was the only mod I had active and all my friends had no active mods. I even tried restarting the game, restarting my computer, and even reinstalling the game to a new drive, and still nothing. After also trying Steam's verify integrity of game cache we determined that 3 files fail to validate and get redownloaded every launch (irrelevant to the problem I believe, but wanted to let you know). Last week during our play session (I was hosting) the game would crash randomly a few minutes in. They could possibly be related? I will include some saved screenshots from the crash reports generated that night. Sorry they aren't .txt files I think these two screenshots are all that's left from reinstalling. Crash Reports: https://imgur.com/a/Pw6YY2l    It could be an issue with the game but given the problems I wouldn't be at all surprised if it was an issue unique to my PC. 

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
No error messages or crash reports except the steam validation.
```

**Comment by Regalis11** [comment] 2022-11-05 11:30
Thank you for the report!

I unfortunately wasn't able to reproduce the issue. Since it doesn't seem like this happens for all players, there must be some specific circumstances in which it occurs, but I wasn't able to figure out what it could be.

How exactly are you unable to craft? Are you unable to select a recipe, unable to start the fabrication, does the fabrication never finish, or does nothing come out of the fabricator when it finishes...?

Thanks and sorry for the inconvenience!

**Comment by BigMike3180** [comment] 2022-11-05 17:49
We are able to put the resource in the fabricator and are able to hit the craft button after selecting the recipe but after that, it does nothing and doesn't craft.

**Comment by Regalis11** [comment] 2022-12-05 10:13
No known steps to repro, closing

**Closed by Regalis11** 2022-12-05 10:13 UTC
Labels: Bug, Need more info, Code, Networking
