### ISSUE TITLE
Linux: Can't use additional mouse buttons for controls

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [Regalis11/Barotrauma#9038] opened 2022-05-02 06:38 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

On Windows, I was able to assign `MOUSE4` and `MOUSE5` to control local and radio chat. This was extremely helpful.

**Steps To Reproduce**

On Linux:

* open Settings-Controls
* click on "Push-to-talk" or "Local Voice Chat"
* attempt to bind Mouse4 or Mouse5
  * Observe it fails (does nothing)
* (optional): attempt to bind Mouse1 or Mouse2
  * Observe it succeeds

**Version**

0.17.15.0 (ReleaseLinux, branch release, revision 62bb4ecab3)

**Additional information**

It _might_ be a regression bug; I'm not 100% certain, though, as I do not have any computer with either Microsoft Windows or Barotrauma v0.15 at this time.

**Comment by Regalis11** [comment] 2022-05-02 07:49
Duplicate of https://github.com/Regalis11/Barotrauma/issues/6305

**Closed by Regalis11** 2022-05-02 07:49 UTC
