### ISSUE TITLE
Opening the server browser causes a crash

### ISSUE THREAD

**Issue by Cyana-ir** [Regalis11/Barotrauma#10743] opened 2022-12-17 02:54 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When I tried to open Server Browser to check the language filter  from "changelog.txt" ,it just crashed without crashreport....
I have seen same problem on discord, but there seemed no issues reported.

### Reproduction steps

1.Start the game
2.click the "SEVER BROWSER"
3. Getting in and it crashed

### Bug prevalence

Happens every time I play

### Version

0.21.0.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Unfortunately,crashreport.txt not exist.
```

**Comment by Cyana-ir** [comment] 2022-12-18 03:05
![IA6M6E$28H2ZM9 `J7@(%I7](https://user-images.githubusercontent.com/106088471/208279219-be10ee0b-2d64-470b-8e2c-9dacb693292b.png)

After enable verbose logging, I tried again. this picture was last frame before crashing

**Comment by Jade-Harleyy** [comment] 2022-12-18 03:46
I also had an issue similar to this one: #10271

**Comment by Regalis11** [comment] 2022-12-18 09:32
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10271

**Closed by Regalis11** 2022-12-18 09:32 UTC
Labels: Bug, Need more info, Code, Crash
