### ISSUE TITLE
the auto injector bugs while deconstructing an empty exploding coilgun ammunition

### ISSUE THREAD

**Issue by uyemeb** [Regalis11/Barotrauma#7312] opened 2021-11-14 19:33 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
when you deconstruct an empty exploding coilgun ammunition the fake explosion triggers the auto injector and makes the game lag very hard as the bug happens

**Steps To Reproduce**
as you see in the video have a auto injector headset with morphine and get blasted my deconstructing an empty exploding coilgun ammunition

**Version**
v0.15.13.0 windows

**Additional information**
idk why the explosion is 5 feet away from the deconstructor i guess its just built different
you can get saved from the bug by getting killed by someone

https://user-images.githubusercontent.com/43451345/141695653-e00c956c-197e-4974-8caf-6582ed75f1ed.mp4

**Comment by Regalis11** [comment] 2021-11-15 09:13
Even though this isn't strictly a duplicate of https://github.com/Regalis11/Barotrauma/issues/6613, it happens as a consequence of the ammo box exploding client-side, so I'll close this one

**Closed by Regalis11** 2021-11-15 09:13 UTC
