### ISSUE TITLE
Blurred on load

### ISSUE THREAD

**Issue by Flubbergrub** [Regalis11/Barotrauma#9302] opened 2022-06-10 01:06 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When loading up the game the loading screen in fine the after it goes to where you would select like campaign or whatever it becomes a mostly all black screen with unreadable text and you cant select anything besides the privacy policy, you cant read it but it opens the tab. 
All files are verified no mods nothing just base game

### Reproduction steps

Load up game.
Press any key to continue 
Nothing

### Bug prevalence

Happens every time I play

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
No messages
```

**Comment by Regalis11** [comment] 2022-06-10 07:30
Are you using Razer Cortex or some similar 3rd party "game optimization" software? Those seem to cause issues in the currentp public version, but we've got a fix coming up in the next update https://github.com/Regalis11/Barotrauma/issues/9213

**Comment by Regalis11** [comment] 2022-06-13 16:30
Closing as a duplicate of https://github.com/Regalis11/Barotrauma/issues/9213

**Closed by Regalis11** 2022-06-13 16:30 UTC
Labels: Bug, Need more info, Code
