### ISSUE TITLE
AI can sometimes get stuck on doors when tasked to cleanup items just behind a closed door

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#9592] opened 2022-07-18 09:29 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I had numerous AI's set to cleanup items while testing other things, every single AI with the order got stuck at the exact same points twice until another AI opened the door (on a different objective) letting them free.

https://i.gyazo.com/049afd3bc138526e143f38137b9ca9af.mp4

### Reproduction steps

not sure yet, highly likely by using diving suits (and other cleanup items) extremely close to the other side of doors?

### Bug prevalence

Happens every now and then

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Ek-Videogames** [comment] 2022-07-18 13:13
Does it happen because items are close to the door - like in the corners of a room? Resulting in the AI 'skipping' the door node.

Or is the item further away and crew just aren't opening doors.

**Comment by Regalis11** [comment] 2022-07-18 15:18
Would also be useful to know which submarine this happened in, or any other details that might make this easier to reproduce

**Comment by NilanthAnimosus** [comment] 2022-07-18 16:03
was either a typhon 2 or dugong, as these were two of the submarines I was testing AI against for welding tasks. there was an empty fuel rod under the reactor and a diving suit near the door, I am not sure which they were targeting, they also got stuck on the door to the right, and in the mp4 you can see diving suits near the edges of the doors on the opposite sides almost inside the door.

I hadn't yet re-tested by dropping items yet, but I theorize it is based on items being incredibly close to the doors on certain submarines at least.

**Comment by NilanthAnimosus** [comment] 2022-07-26 07:58
Re-Tested in 0.19.0.0 for better reproduction using a Barsuk submarine. it seems the AI will sometimes drop their suits directly inside of a door they are crossing as it is open, when the door closes the AI seems unable to get to the diving suit (or other item) at that point.

As a note this also should occur in single player. which would be much easier to diagnose as you can see where the item truly is instead of client-side assumed position.

I've managed to reproduce this in multiplayer just by taking out of lockers then dropping diving suits inside open doors and closing them, but often to sporadic effect (It does not always occur and the item will shift left/right at times as expected).

sometimes they will get stuck inside the door, or is stuck server side while moving to the sides client side (And in one case I had it alternating sides every so often in multiplayer):

https://i.gyazo.com/48cf8d6bc8808711e742181cd66cd1e8.mp4

for barsuk, I got it stuck on three separate doors, so I'm not sure its submarine specific but the oxygen gen room door, the door to the reactor and command room door all managed to get the AI stuck with a few drop attempts of the diving suit.

I have also noticed: If a client gets a diving suit stuck inside of a door, the client also cannot interact with it from either side of said door, the door must be opened to get at the item in question which the AI doesn't do (Assumedly because it has reached a close enough position, despite the fact it cannot actually interact with the item?)

**Comment by itchyOwl** [comment] 2023-03-27 11:55
Posting these here:
![image](https://user-images.githubusercontent.com/5370738/227933968-0dd81e09-dd6f-41a6-84dd-596e88b533a4.png)
![image](https://user-images.githubusercontent.com/5370738/227934017-3b28477a-779f-4631-8cb3-742d67f69378.png)

I think it affects any get item objective, but can probably be reproduced most easily with the cleanup order.

**Comment by itchyOwl** [comment] 2023-04-14 12:03
Can't repro. Dropping an item behind the door and telling a bot to clean it up doesn't work: the bot pathes (correctly) to the first node after the door.

If anyone manages to repro it, please report the steps here.

**Comment by itchyOwl** [comment] 2023-04-14 12:09
Can be tricky to repro without the fixes to the item finding made in https://github.com/Regalis11/Barotrauma-development/pull/4116.

**Comment by itchyOwl** [comment] 2023-05-03 10:54
Haven't been able to repro, but just pushed a commit that might affect this: Regalis11/Barotrauma-development@4215b81.

**Comment by Regalis11** [comment] 2023-06-30 11:32
No known steps to repro, closing

**Closed by Regalis11** 2023-06-30 11:32 UTC
Labels: Bug, Need more info, Needs testing, Code
