### ISSUE TITLE
Logbook not saving

### ISSUE THREAD

**Issue by Demonicturttle** [Regalis11/Barotrauma#11539] opened 2023-03-15 09:38 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I would have made this sooner had I realized their was a bug report option.
I host a server, sketchy seas I have a log book that I make notes on so I can go back to it every day and recall some important events or information from previous days.

well for some reason when I shut down the server and turn it back on the next day or whenever I start hosting again the last 2 or more entrees have been deleted, its gotten so frustrating to the point I barely use the loglog book anymore. 

### Reproduction steps

1 start a multiplayer game
2 get a logbook some how be it in built into a ship or from a wreck just get one
3 write in it several entrees not lines but entrees
4 (optional) sign your work, your masterpiece
5 close the logbook, put it away either in your tool-bag or safe
6 shut down the server by saving and quitting to send you back to the lobby to disconnect 
7 start up the server
8 find your logbook and look in horror at all those hours of word crafting GONE

### Bug prevalence

Happens regularly

### Version

v1.0.7.0

### Which operating system did you encounter this bug on?

Windows

**Comment by NilanthAnimosus** [comment] 2023-05-29 10:41
Unable to reproduce on the 1.0.16.0, could you provide a save file or other information that might be causing this (If it still occurs in the current version)?

**Comment by Regalis11** [comment] 2023-06-30 11:23
No known steps to repro, closing

**Closed by Regalis11** 2023-06-30 11:23 UTC
Labels: Bug, Need more info, Code
