### ISSUE TITLE
Save crash and wont appear on the "load save" menu

### ISSUE THREAD

**Issue by Tomes1805** [Regalis11/Barotrauma#7836] opened 2021-12-17 16:43 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
(Sorry for bad english) We loaded a multiplayer campaign with 4 four people, we spawned on a colony as we stopped here on our previous, then according to our host he got sent back to the lobby with a error message he cant remember, and we noticed that the save file doesn't appear anymore on the game but is still on the multiplayer file. 
**Steps To Reproduce**
Loading a trip to another station

**Version**
0.15.22.1 on Windows

**Additional information**
We were using 3 mods that added submarines and suits and tried to reinstall the game without mod with not effect
[gamede_CharacterData.zip](https://github.com/Regalis11/Barotrauma/files/7736559/gamede_CharacterData.zip)

**Comment by Regalis11** [comment] 2022-01-05 11:37
Hmm, it seems that the save file has gotten corrupted somehow (as if it was cut in the middle, with the last parts of the xml file missing), which prevents the server from loading it.

Without knowing what the error message was, it's very hard for us to diagnose this, but I think we need to do some debugging and try to make saving more robust to ensure this can't happen no matter what kind of errors occur when saving.

I'm sorry for the inconvenience, and for not being able to offer you more help with this for the time being. :/

May be related to or a duplicate of https://github.com/Regalis11/Barotrauma/issues/7629.

**Comment by Regalis11** [comment] 2022-01-05 12:39
Possibly fixed in Regalis11/Barotrauma-development@40b43de. Doesn't fix the error that caused the save file to be corrupted (because we don't know what it was), but should prevent the game from proceeding with the saving if an error occurs at any point during the saving.

**Comment by Rokvach** [comment] 2022-02-07 11:52
No steps to reproduce and there hasn't been any new issues caused by the fix nor sightings of the issue itself, closing as it seems to be working.

**Closed by Rokvach** 2022-02-07 11:52 UTC
Labels: Bug, Code
