### ISSUE TITLE
The number of "owned" items in store is miscalculate if the items taken into inventory.

### ISSUE THREAD

**Issue by pavel4win** [Regalis11/Barotrauma#13281] opened 2024-01-08 11:00 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The number of "owned" items in store become incorrect if items are taken from cabinet into inventory.

I already create same issue 
https://github.com/Regalis11/Barotrauma/issues/12712

I'm not sure if this is the same error and I found an exact way to reproduce this error, so I created a new issue to get your attention immediately.

### Reproduction steps

1. Create a new game without mods with Camel uboat. (Uboat does not matter I think)
2. go with captain to the merchant, look at the number of masks on your boat in the “owned” column of the merchant. (there are 8 and that's true)
3. collect all the masks in your engineer bot inventory. And keep him on the boat.
4. with captain bot at merchant, look at the number of masks on your boat in the “owned” column of the merchant. (now there are 16 and it is not true).
5. Put all the masks in any closet and check their number with the merchant. There are 8 again.
6. collect all the masks in your engineer inventory. (now there are 16 again).
7. Save and then load the game. The number of masks on your boat in the “owned” column of the merchant is again 8. But if you only return the engineer with masks to the ship, the number will be 16 again. 
Thus, when someone takes an item into inventory, the "owned" number is distorted.

I noticed a feature.
If the bot with masks goes over from the boat to the station, then the number of “owned” items becomes correct.​
The most likely reason. Items in the inventory are counted twice while the character is inside the boat

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.7.0 (Winter Update hotfix)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2024-01-08 15:22
Duplicate of https://github.com/Regalis11/Barotrauma/issues/13060. Thank you for the reproduction steps though, this should help us finally get to the bottom of this issue!

**Closed by Regalis11** 2024-01-08 15:22 UTC

**Comment by pavel4win** [comment] 2024-01-17 13:25
after update 1.2.7.0 the error disappeared
after update 1.2.8.0 the error appeared again
reproduction steps is the same

**Comment by Regalis11** [comment] 2024-01-17 13:34
The fix is not yet included in any public update.
