### ISSUE TITLE
[0.9.9.0] Multiplayer(?) - Repairing is literally suicide

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2507] opened 2020-03-27 22:55 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Crew members are dying trying to repair the sub's damage systems. Can suffer up to 33% of your HP on One fail. Not sure if it's multiplayer only problem.

**Version**
0.9.9.0

**Comment by Regalis11** [comment] 2020-03-29 11:23
Duplicate of #2530, but the new one contains more information so I'll close this one instead.

**Closed by Regalis11** 2020-03-29 11:23 UTC
Labels: Bug, Design
