### ISSUE TITLE
badvibrations2 softlock in singleplayer

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#12891] opened 2023-10-22 21:16 UTC
### What happened?

In bad vibrations part 2, you collect an artifact from a ruin. Upon picking up the artifact, you get an event with several options. If the player insists on attempting to discard the item, they will be paralysed. Unfortunately the event dialogue does not disappear after being paralysed, which means that the player can't switch characters, causing a softlock and the character eventually running out of oxygen and dying.

### Reproduction steps

1. Head to an outpost in singleplayer campaign and trigger the badvibrations event
2. Go to the marked ruin and find the artifact
3. Pick the artifact up and choose the dialogue options about dropping the artifact
4. Observe that the event does not complete; the "You close your eyes. This seems like as good a place as any to have a nap..." text does not appear and it is impossible to switch to a different character.

### Version

v1.1.18.1 (Treacherous Tides)

**Comment by Regalis11** [comment] 2023-10-23 07:34
Duplicate of https://github.com/Regalis11/Barotrauma/issues/12869

**Closed by Regalis11** 2023-10-23 07:34 UTC
