### ISSUE TITLE
One of the lines in the medic tutorial is bugged

### ISSUE THREAD

**Issue by Mayflower404** [Regalis11/Barotrauma#11008] opened 2023-01-22 02:35 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

After giving the NPC Naloxone, their line reads "tutorial.roles.medicalinstructor.medfabrictor3". 

### Reproduction steps

1. Start the first tutorial option in the menu
2. Progress to the section where you choose a role to learn about
3. Choose the medic, and go along the tutorial
4. Give the NPC Naloxone, and you should see the bugged line. 
![image](https://user-images.githubusercontent.com/101680591/213897986-6837fbdc-c72e-45be-8cb4-9170afda25cf.png)

### Bug prevalence

Just once

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-01-23 09:10
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10751

**Closed by Regalis11** 2023-01-23 09:10 UTC
