### ISSUE TITLE
[0.10.0 RC1] This outpost had over 6 missions to give

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3260] opened 2020-07-01 04:37 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
This outpost had over 6 missions to give.

![Capture](https://user-images.githubusercontent.com/5086682/86203943-45163c00-bb34-11ea-8035-8d4b42750768.PNG)

[Save.zip](https://github.com/Regalis11/Barotrauma/files/4855705/Save.zip)

**Version**
0.10.0 RC1

**Comment by Regalis11** [comment] 2020-07-01 11:33
Could not reproduce: there seem to be no missions available in the save file, and the outpost manager offers only 2 missions.

**Comment by Rokvach** [comment] 2020-07-01 11:56
As missions change each time the save is loaded its going to be a bit difficult to reproduce this other than just keep creating outposts until one appears. Doesn't seem to be that rare of a issue.

**Comment by Regalis11** [comment] 2020-07-01 17:05
Found a way to repro this now: there was a bug that caused active events to carry over between the levels, so if you waited for the events to activate in the outpost, left and re-entered, you'd be able to unlock x2 the normal amount of missions.

Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/24b44fea8be67e394a3d47781755e48f18e6b51f

**Comment by Rokvach** [comment] 2020-07-02 07:37
Wasn't able to reproduce, looks to be working correctly. Closing.

**Closed by Rokvach** 2020-07-02 07:37 UTC
Labels: Bug, Code
