### ISSUE TITLE
Relay Component: The power-out entry work just like a junction box

### ISSUE THREAD

**Issue by Pol-CHEVILLON** [Regalis11/Barotrauma#12696] opened 2023-09-20 19:42 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

As written on the title, on the relay component, if we connect an energy inlet to the "energy-out" point, the energy will be shared on all the cables connected to this point.
This can pose a problem in the design of a circuit breaker between two energy-producing grids (and where we would need to circulate the energy of one source or the other through the component)

An example of the problem in simplification (Pay no attention to the modded generator next to it as well as the modded junction box, the bug also works without mod. If necessary, I can reform a 100% vanilla set)
![image](https://github.com/Regalis11/Barotrauma/assets/82041799/c76a9b99-1bcb-4245-9973-80273825f407)

Another example of the system mounted in bulk, but showing the concern that I lack. (here, whether the component relay is activated or not, the ennergy passes from the docking port to the junction box)
![image](https://github.com/Regalis11/Barotrauma/assets/82041799/1a0c2f25-c390-4306-8eb3-b8dd488c9471)

### Reproduction steps

1. Get a Submarine
2. place a generator (or watever can produce or share ennergy) and a statut monitor (or watever can require ennergy)
3. place between a relay component
4. Connect the component generating the energy and the one requesting it to the “Energy output” point of the relay component
5. turn ON the ennergie! the statut monitor will be powered.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-09-21 06:49
Duplicate of https://github.com/Regalis11/Barotrauma/issues/9194

**Closed by Regalis11** 2023-09-21 06:49 UTC

**Comment by Ek-Videogames** [comment] 2023-09-24 15:53
Oh that's why the electrical grid keeps exploding!?
I though this problem was exclusive to batteries/supercapacitors output.
