### ISSUE TITLE
Campaign Afflictions Removed & Full Heal upon Retry After Reaching Outpost

### ISSUE THREAD

**Issue by sheknal** [Regalis11/Barotrauma#4099] opened 2020-10-18 12:15 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported. But I'm partially blind so I probably didn't look hard-enough.

**Description**
In the campaign, if you take any-form of damage, no-matter how fatal. As-long as you go to and enter an outpost and press retry, you will be healed of all wounds; all afflictions will be cured.

**Steps To Reproduce**
Take any-amount of damage (don't die, however) progress towards the outpost, dock. Wait patiently, and whenever you want: you can press retry and all of your wounds will be healed. This makes every medical item completely pointless as-long-as you can reach the outpost in time.

**Version**
V0.10.5.1, Windows.

**Additional information**
In my scenario, I was exploring a wreckage or whatever, when I was molested by everything that lived in the ocean. After getting addicted to every drug on the submarine, and entering intensive care: I commandeered my vessel towards the outpost. There, I docked my vessel; then I was attacked by the inhabitants. Inhabitants of whom shrugged off my bullets; ate my explosives. These super-soldiers who probably consume Anabolic Steroids for breakfast, lunch; dinner promptly broke every bone in my body and arrested me. After I pressed the retry button, I realized all of my wounds have been healed. To test that this wasn't because I had almost every affliction; because I was on the verge of death, I jumped down a ladder, broke my legs and restarted. And what-do-you-know? I was fully healed.

**Comment by Regalis11** [comment] 2020-10-19 07:22
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3955

**Closed by Regalis11** 2020-10-19 07:22 UTC
