### ISSUE TITLE
bug around lights

### ISSUE THREAD

**Issue by war3scv** [Regalis11/Barotrauma#11505] opened 2023-03-14 08:01 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

bug around lights include but may not limited to, can't turn off light of turret in sub editor(turn off save reload and light still on), light of lamp disappear in editor after restart, need toggle every lamp's "is on" to bring it back. 

### Reproduction steps

turn off light in sub editor save and reload.

### Bug prevalence

Happens regularly

### Version

v1.0.7.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-03-14 09:05
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10704

**Closed by Regalis11** 2023-03-14 09:05 UTC
