### ISSUE TITLE
in game 

### ISSUE THREAD

**Issue by Matiz753** [Regalis11/Barotrauma#2690] opened 2020-04-24 14:45 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

Barotrauma Client crash report (generated on 2020-04-24 16:38:10)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

B88397013C2378C4A99C3E19DEBEE54F

Game version 0.9.9.0 (ReleaseWindows, branch release, revision 0534150c8)
Graphics mode: 1366x768 (Fullscreen)
VSync ON
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.ServerListScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.18363.0 64 bit
    GPU name: NVIDIA GeForce GTX 1050 Ti
    Display mode: {Width:1366 Height:768 Format:Color AspectRatio:1,7786459}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void FilterServers()
Stack trace: 
   at Barotrauma.ServerListScreen.FilterServers()
   at Barotrauma.ServerListScreen.UpdateServerInfo(ServerInfo serverInfo)
   at Barotrauma.ServerListScreen.AddToServerList(ServerInfo serverInfo)
   at Barotrauma.Steam.SteamManager.<>c__DisplayClass16_2.<GetServers>b__10()
   at Barotrauma.CrossThread.RequestExecutionOnMainThread(TaskDelegate deleg)
   at Barotrauma.Steam.SteamManager.<>c__DisplayClass16_2.<GetServers>b__8(Task`1 t)
   at Barotrauma.TaskPool.<>c__DisplayClass5_0`1.<Add>b__0(Task t, Object obj)
   at Barotrauma.TaskPool.Update()
   at Barotrauma.GameMain.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Barotrauma.Program.Main(String[] args)

Last debug messages:
[2020-04-24 16:37:41] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[2020-04-24 16:37:40] Content package load order: Vanilla 0.9
[2020-04-24 16:37:40] Content package load order: Vanilla 0.9
[2020-04-24 16:37:38] Attempting to open ALC device "OpenAL Soft"
[2020-04-24 16:37:37] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[2020-04-24 16:37:36] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[2020-04-24 16:37:35] Logged in as Matiz753 (SteamID STEAM_1:1:63261529)

**Comment by Regalis11** [comment] 2020-04-25 13:59
Duplicate of #2567

This happens due when trying to filter servers in the server list based on game mode. We've got a hotfix coming for this issue soon, but for now it should be possible to work around it by not trying to filter the server list. Sorry for the trouble!

**Closed by Regalis11** 2020-04-25 13:59 UTC
