### ISSUE TITLE
Crash on dedicated: Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by m3nda** [Regalis11/Barotrauma#4112] opened 2020-10-21 02:02 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

Somewhat similar to #3469 

**Description**
During heated battle with Thalamus server crashed

**Steps To Reproduce**
Tried to reproduce it, but couldn't 

**Version**
Game version 0.10.5.1 (ReleaseLinux, branch release, revision 9e259b2148)
Debian 10
Dedicated server - moded (from workshop)

**Additional information**
[servercrashreport (6).log](https://github.com/Regalis11/Barotrauma/files/5412770/servercrashreport.6.log)

**Comment by itchyOwl** [comment] 2020-10-21 09:00
According to the crash report, it's caused by the local bodies collection being modified while enumerating:
![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/9545f033-8b73-474e-a748-d8d346815369)

 For the code that throws this error, see: https://referencesource.microsoft.com/#mscorlib/system/collections/generic/list.cs,aa7e01fcb80a917e. I don't see how this could be possible unless the code block is accessed from different threads. We use multithreading in the physics code, but it shouldn't affect the raycasts, right?

The second line in the stack trace doesn't make any sense:
![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/bf7ef30c-c691-482c-be2f-d561e053eed5)

**Comment by Regalis11** [comment] 2020-10-21 10:03
Duplicate of #3896.

@itchyOwl this happened because the RepairTool would use a list returned by Submarine.PickBodies, and when using the tool resulted in an explosion, Submarine.PickBodies would get called by the explosion, resulting in the "bodies" list being modified while the RepairTool is enumerating it.

**Closed by Regalis11** 2020-10-21 10:03 UTC
Labels: Bug, Code, Crash, Help wanted
