### ISSUE TITLE
Recycling an SMG magazine spawns one extra ammunition

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#8356] opened 2022-02-23 20:09 UTC
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Recycling an SMG magazine spawns one extra ammunition and drops it on the ground. The round can't be used, but it can be picked up.

**Version**
0.16.6.1. release (or any after adding the recipe for recycling the magazines)

**Additional information**
Fabricating a new SMG magazine doesn't do the same.

**Comment by Regalis11** [comment] 2022-03-14 10:59
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/60b01e6fd5dc98c13770671caa20575055431183

**Comment by Rokvach** [comment] 2022-03-18 13:29
Tested, every other time you recycle a SMG magazine (even a full one) it will spawn a extra SMG magazine which drops in front of the fabricator.

**Comment by Regalis11** [comment] 2022-03-18 14:09
Not a bug, happened as a result of the "Munitions Expertise" talent

**Comment by Rokvach** [comment] 2022-03-20 21:53
Working correctly, closing.

**Closed by Rokvach** 2022-03-20 21:53 UTC
Labels: Bug, Code, Low prio
