### ISSUE TITLE
[Issue][Audio] The "MUTE" option is not working properly.

### ISSUE THREAD

**Issue by Ant1V1RU5** [Regalis11/Barotrauma#2579] opened 2020-04-07 06:32 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When certain conditions are met, the "MUTE" option does not work properly and let people speak trought

**Steps To Reproduce**
If an user speak / make noise before being muted and then continue to do so without interruption, the issue appear and stay as long as the muted user is transmitting even a minimal amount of noise.

This issue is extremely noticeable when a player is using Voice Detection with a noisy background.

**Version**
Current version 0.9.8.0 on Windows updated.

**Additional information**
Issue found and reported by Cory Corrigodone (TacticalRice#1626) on the official Barotrauma Discord.

**Comment by Regalis11** [comment] 2020-04-07 07:50
Duplicate of #2574. Thank you for the extra details, it didn't occur to me transmitting continuously could have an effect on this, but looks like it did and was simple to fix. :)

**Closed by Regalis11** 2020-04-07 07:50 UTC
Labels: Bug, Code, Networking
