### ISSUE TITLE
The interface closes when sitting down to use the device

### ISSUE THREAD

**Issue by AnalogKnight** [Regalis11/Barotrauma#9996] opened 2022-10-06 14:54 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When I sit down and use a device (such as a terminal), the interface closes as soon as my character touches water. Even if the water only touched the character's feet, or even a few drops of water leaking from the drain.

### Reproduction steps

1. Sit down and use the navigation terminal
2. In contact with water, such as the hull above the character was slightly damaged, leaking a small amount of water.
3. The interface of the navigation terminal closes immediately, as if the character was being washed away by water when standing, even if the water was very low.

### Bug prevalence

Happens every time I play

### Version

0.19.10.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-10-07 08:07
Thank you for the report! I'm afraid I could not reproduce this: the character seems entirely capable at sitting the chair in a flooded room:
![image](https://user-images.githubusercontent.com/14351070/194504616-88d9dcb3-892b-4a71-b622-89c6ae36795b.png)

**Comment by AnalogKnight** [comment] 2022-10-07 12:15
> Thank you for the report! I'm afraid I could not reproduce this: the character seems entirely capable at sitting the chair in a flooded room: ![image](https://user-images.githubusercontent.com/14351070/194504616-88d9dcb3-892b-4a71-b622-89c6ae36795b.png)

Thanks for your response. I had this problem with Camel, and I haven't tried other subs for now as the navigation terminals of other official subs don't seem to have seats. I will add a chairs on other subs using the subs editor to verify this problem.

**Comment by Regalis11** [comment] 2022-10-09 15:01
I gave this a test in Barsuk too now, but couldn't spot anything unusual .:/


https://user-images.githubusercontent.com/14351070/194764020-3cd83899-fce7-4e65-b3bf-7842bdde7b00.mp4

The character does get pushed off the chair when the force of the water is strong enough to push the character, but that doesn't seem to happen until there's quite a lot of water in the hull (about the height of the character's shoulder).

**Comment by Regalis11** [comment] 2022-11-08 15:28
No known steps to repro, closing

**Closed by Regalis11** 2022-11-08 15:28 UTC
Labels: Bug, Need more info, Code
