### ISSUE TITLE
R-29 Big Rig Pathfinding Error in Bots

### ISSUE THREAD

**Issue by gerakis** [Regalis11/Barotrauma#9783] opened 2022-08-28 19:01 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If the belly of the R-29 Big Rig gets damaged, bots set to repair leaks cant seem to path over and repair it properly. They just run back and forth over the top. Its repeatable and happens every time. This sub I'm testing on is completely vanilla.

Check youtube video for demonstration. 
https://youtu.be/ioK_UiwlL0Y

### Reproduction steps

In singleplayer, buy the R-29 Big Rig
Set at least one bot to repair leaks
Walk along the bottom of the cargo bay shooting your plasma cutter at the floor
Bots will all freak out and run back and forth.

### Bug prevalence

Happens every time I play

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-08-29 07:16
Duplicate of https://github.com/Regalis11/Barotrauma/issues/9186

**Closed by Regalis11** 2022-08-29 07:16 UTC
Labels: Bug, Code
