### ISSUE TITLE
при переходе на следующую локацию вылетает игра (barotrauma)

### ISSUE THREAD

**Issue by Frizit** [Regalis11/Barotrauma#5375] opened 2021-03-29 16:34 UTC
Barotrauma Client crash report (generated on 29.03.2021 16:32:52)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

32AA46FAB36BEE9386335D0F440A6AF3

Game version 0.12.0.3 (ReleaseWindows, branch release, revision ea245a2f34)
Graphics mode: 1366x768 (BorderlessWindowed)
VSync ON
Language: Russian
Selected content packages: Vanilla 0.9
Level seed: SeracGortyna Flexus
Loaded submarine: Humpback (79568DB056E2F945385FAD3E99F12755)
Selected screen: Barotrauma.RoundSummaryScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19041.0 64 bit
    GPU name: Intel(R) HD Graphics
    Display mode: {Width:1366 Height:768 Format:Color AspectRatio:1,7786459}
    GPU status: Normal

Exception: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Экземпляр устройства GPU приостановлен. Для определения соответствующего действия используйте GetDeviceRemovedReason.
 (SharpDX.SharpDXException)
Device removed reason: HRESULT = 0x887A0005
Target site: Void CheckError()
Stack trace: 
   at SharpDX.Result.CheckError()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 1017
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 511
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59

Last debug messages:
[29.03.2021 16:32:22] Transitioning to SeracGortyna Flexus (current location: Serac, selected location: Жилой аванпост Gortyna Flexus, leaving sub: Humpback, at start: True, at end: False, transition type: LeaveLocation)
[29.03.2021 16:29:34] Generating an outpost for the start of the level... (Location: Serac, level type: Outpost)
[29.03.2021 16:29:09] Transitioning to Serac (current location: Serac, selected location: Phineus Linea, leaving sub: Humpback, at start: True, at end: False, transition type: ReturnToPreviousLocation)
[29.03.2021 16:28:30] Generating an outpost for the start of the level... (Location: Phineus Linea, level type: LocationConnection)
[29.03.2021 16:26:49] Generating an outpost for the start of the level... (Location: Phineus Linea, level type: LocationConnection)
[29.03.2021 16:26:12] LobbyMatchList:  LobbiesMatching: 0
[29.03.2021 16:26:12] LobbyMatchList:  LobbiesMatching: 0
[29.03.2021 16:26:12] SteamAPICallCompleted:   AsyncCall: 14323504062403906620
   Callback: 510
 ParamCount: 4
[29.03.2021 16:26:11] PersonaStateChange:      SteamID: 76561198977241463
 ChangeFlags: 64
[29.03.2021 16:26:11] PersonaStateChange:      SteamID: 76561198417197085
 ChangeFlags: 64
[29.03.2021 16:26:11] PersonaStateChange:      SteamID: 76561198408556810
 ChangeFlags: 64
[29.03.2021 16:26:11] PersonaStateChange:      SteamID: 76561198080940461
 ChangeFlags: 64
[29.03.2021 16:26:11] LobbyMatchList:  LobbiesMatching: 37
[29.03.2021 16:26:11] LobbyMatchList:  LobbiesMatching: 37
[29.03.2021 16:26:11] SteamAPICallCompleted:   AsyncCall: 16326232356871265243
   Callback: 510
 ParamCount: 4
[29.03.2021 16:26:11] PersonaStateChange:      SteamID: 76561198948964943
 ChangeFlags: 64
[29.03.2021 16:26:05] PersonaStateChange:      SteamID: 76561198977241463
 ChangeFlags: 1089
[29.03.2021 16:26:05] PersonaStateChange:      SteamID: 76561198417197085
 ChangeFlags: 1089
[29.03.2021 16:26:05] PersonaStateChange:      SteamID: 76561198408556810
 ChangeFlags: 1089
[29.03.2021 16:26:05] PersonaStateChange:      SteamID: 76561198080940461
 ChangeFlags: 1089
[29.03.2021 16:26:05] PersonaStateChange:      SteamID: 76561198948964943
 ChangeFlags: 1089
[29.03.2021 16:26:05] LobbyMatchList:  LobbiesMatching: 50
[29.03.2021 16:26:05] LobbyMatchList:  LobbiesMatching: 50
[29.03.2021 16:26:05] SteamAPICallCompleted:   AsyncCall: 10033538676452830965
   Callback: 510
 ParamCount: 4
[29.03.2021 16:25:35] (Msg) SDR RelayNetworkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[29.03.2021 16:25:35] (Msg) Ping location: sto=29+2,sto2=32+3/30+2,ams=38+3,par=39+3,lhr=43+4/43+3,fra=66+6/45+3,waw=52+5/49+2,vie=51+5,mad=74+7/58+3,iad=114+11/115+3,sgp=201+20/202+20,gru=230+23
[29.03.2021 16:25:35] (Msg) Ping measurement completed
[29.03.2021 16:25:32] (Verbose) Communications with routing cluster 'maa' established.
[29.03.2021 16:25:32] (Verbose) Communications with routing cluster 'iad' established.
[29.03.2021 16:25:32] (Debug) Destroying relay 'maa#23 (155.133.232.98:27037)' because initial_ping_timeout
[29.03.2021 16:25:32] (Debug) Destroying relay 'iad#171 (162.254.192.83:27017)' because initial_ping_timeout
[29.03.2021 16:25:31] (Verbose) Communications with routing cluster 'tyo' established.
[29.03.2021 16:25:31] (Verbose) Communications with routing cluster 'tyo1' established.
[29.03.2021 16:25:31] (Verbose) Communications with routing cluster 'hkg' established.
[29.03.2021 16:25:30] (Verbose) Communications with routing cluster 'syd' established.
[29.03.2021 16:25:30] (Verbose) Communications with routing cluster 'sgp' established.
[29.03.2021 16:25:30] (Verbose) Communications with routing cluster 'sea' established.
[29.03.2021 16:25:30] (Verbose) Communications with routing cluster 'scl' established.
[29.03.2021 16:25:30] (Verbose) Communications with routing cluster 'lim' established.
[29.03.2021 16:25:30] (Verbose) Communications with routing cluster 'jnb' established.
[29.03.2021 16:25:30] (Verbose) Communications with routing cluster 'eze' established.
[29.03.2021 16:25:30] (Verbose) Communications with routing cluster 'sof' established.
[29.03.2021 16:25:30] (Verbose) Communications with routing cluster 'lax' established.
[29.03.2021 16:25:30] (Verbose) Communications with routing cluster 'gru' established.
[29.03.2021 16:25:30] (Verbose) Communications with routing cluster 'waw' established.
[29.03.2021 16:25:29] (Verbose) Communications with routing cluster 'ord' established.
[29.03.2021 16:25:29] (Verbose) Communications with routing cluster 'vie' established.
[29.03.2021 16:25:29] (Verbose) Communications with routing cluster 'sto' established.
[29.03.2021 16:25:29] (Verbose) Communications with routing cluster 'sto2' established.
[29.03.2021 16:25:29] (Verbose) Communications with routing cluster 'eat' established.
[29.03.2021 16:25:29] (Verbose) Communications with routing cluster 'dxb' established.
[29.03.2021 16:25:29] (Verbose) Communications with routing cluster 'bom' established.
[29.03.2021 16:25:29] (Verbose) Communications with routing cluster 'dfw' established.
[29.03.2021 16:25:29] (Verbose) Communications with routing cluster 'mad' established.
[29.03.2021 16:25:29] (Verbose) Communications with routing cluster 'atl' established.
[29.03.2021 16:25:29] (Verbose) Communications with routing cluster 'lhr' established.
[29.03.2021 16:25:29] (Verbose) Communications with routing cluster 'par' established.
[29.03.2021 16:25:29] (Verbose) Communications with routing cluster 'fra' established.
[29.03.2021 16:25:29] (Verbose) Communications with routing cluster 'ams' established.
[29.03.2021 16:25:29] (Msg) SDR RelayNetworkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[29.03.2021 16:25:29] (Msg) Performing ping measurement
[29.03.2021 16:25:29] (Msg) Got SDR network config.  Loaded revision 315 OK
[29.03.2021 16:25:29] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[29.03.2021 16:25:29] (Warning) Waited 2.2ms for SteamNetworkingSockets lock [ServiceThread]
[29.03.2021 16:25:29] (Warning) SteamNetworkingSockets lock held for 5.5ms.  (Performance warning).  HTTPRequestCompleted_t
[29.03.2021 16:24:53] Attempting to open ALC device "OpenAL Soft on Наушники (2- High Definition Audio Device)"
[29.03.2021 16:24:49] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[29.03.2021 16:24:47] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[29.03.2021 16:24:42] Logged in as СОНИК (SteamID STEAM_1:0:509679254)

**Comment by Regalis11** [comment] 2021-03-29 16:45
Duplicate of https://github.com/Regalis11/Barotrauma/issues/1833

**Closed by Regalis11** 2021-03-29 16:45 UTC
