### ISSUE TITLE
Sonar window dissapear and then I can't control my sonar

### ISSUE THREAD

**Issue by pavel4win** [Regalis11/Barotrauma#11167] opened 2023-02-06 11:46 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This happened more than once, I can’t say for sure under what conditions. It seems that before I changed the screen resolution and the windowed mode/full screen mode, The sonar control window disappears and it is not possible to switch the sonar mode anymore. I am attached a link with a screenshot

[https://disk.yandex.ru/i/DLMKMJ3k99861w](url)
![2023-02-06_14-35-08](https://user-images.githubusercontent.com/47295383/216963187-c8babdb1-876d-4404-bdfc-3a0bb957ef3f.png)

### Bug prevalence

Happens every now and then

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by pavel4win** [comment] 2023-02-07 05:31
Today this bug manifested again.
Last night, everything was fine with the sonar interface, and then,
during the mission in the company, I didn't complete the mission, because sleep time  is come.
I paused the game and minimized the game window, then switch my computer to sleep mode.
in the morning I woke up the computer, maximize the game window and found that the sonar window was missing.
![image](https://user-images.githubusercontent.com/47295383/217156667-42e95c1f-5abc-4129-a970-ed9dd05d27e1.png)
![image](https://user-images.githubusercontent.com/47295383/217156712-65a5c4a6-decd-4e7e-b06f-cecbeb3ea0ed.png)

**Comment by pavel4win** [comment] 2023-03-10 21:54
Today again get this error. Defenitely it is happen after I changed screen resolution to 1280*800 full screen

**Comment by Regalis11** [comment] 2023-03-12 09:28
I'm afraid I still haven't been able to reproduce the issue. Changing the resolution and display mode did not seem to cause any issues at my end.

**Comment by David-Murray** [comment] 2023-03-13 18:59
I've also had this issue, in the new 1.0 patch, changed from border window to fullscreen.

**Comment by antiaircraft** [comment] 2023-04-17 20:00
It seems I can reproduce this consistently in a singleplayer save on 1.0.9.0. If I: 

1. Load into a game.
2. Toggle vertical sync in the graphics settings.
3. Hit apply.

Then the sonar control panel disappears until I load into another area.

However, I am unable to reproduce the issue in a fresh save, even using the Camel from the screenshots in this bug report. The save that does present the issue is with an Orca 2 in the Hydrothermal Wastes, and I'm attaching it in case it's useful: [HALP.zip](https://github.com/Regalis11/Barotrauma/files/11255231/HALP.zip)

Of note, while it should be currently vanilla, this save did briefly have some mods enabled that I was trying out. The mods aren't supposed to alter the save innately, and no objects from those mods should remain in the game, but I'm wondering if they might have altered the save in some way that causes this issue.

For reference, the mods that were loaded earlier in the save:
* [Lua For Barotrauma](https://steamcommunity.com/workshop/filedetails/?id=2559634234) (with Client-side Lua enabled, I purged and verified the game files to remove it for the clean & unmodded save tests)
* [Makeshift Containers](https://steamcommunity.com/sharedfiles/filedetails/?id=2955462544)
* [Real Sonar LITE](https://steamcommunity.com/sharedfiles/filedetails/?id=2938034581)
* [Storage Icons](https://steamcommunity.com/sharedfiles/filedetails/?id=2920200449)

**Comment by Regalis11** [comment] 2023-04-19 09:52
Thank you for the extra info, I was able to get this to happen at my end now too! It seems the key to reproducing this was that the nav terminal needs to have a mineral scanner.

**Comment by Regalis11** [comment] 2023-04-19 09:54
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/633d01e69e6c75f2825d46945e8c182b6c551406 (commit in our private repo)

**Comment by lewri** [comment] 2023-05-27 13:46
I've still got this in v1.0.13.2. is there currently a workaround until the patch comes out?

**Comment by Regalis11** [comment] 2023-05-27 13:53
@lewri This is issue seems to be caused specifically by changing the resolution mid-round: a workaround would be to change the resolution in the main menu before loading in to the campaign. The fix is not yet included in the public build, but potentially coming in the next patch!

**Comment by lewri** [comment] 2023-05-27 13:58
> @lewri This is issue seems to be caused specifically by changing the resolution mid-round: a workaround would be to change the resolution in the main menu before loading in to the campaign. The fix is not yet included in the public build, but potentially coming in the next patch!

I think this is highly likely yes. I toggled vsync on and off, not a direct resolution setting but certainly is related. If I see it again outside of a resolution change I'll report it on a new issue.

**Comment by Rokvach** [comment] 2023-06-01 07:28
Tested, working correctly. Closing.

**Closed by Rokvach** 2023-06-01 07:28 UTC
Labels: Bug, Code
