### ISSUE TITLE
Autopilot

### ISSUE THREAD

**Issue by Chaos456456** [Regalis11/Barotrauma#943] opened 2018-11-28 19:38 UTC
When i use autopilot my ship stop and dont move and when i turn off autopilot my ship can swim

**Comment by Regalis11** [comment] 2018-11-28 21:12
Does this happen regardless of what you've set as the destination of the autopilot? If you set it to "maintain position" or if you're still at the starting location and select it as the destination, the sub shouldn't move.

**Comment by Chaos456456** [comment] 2018-11-28 21:20
It does when i select to some point(not maintain position).

**Comment by Chaos456456** [comment] 2018-11-28 21:30
I saw this problem in Air mar 3, but i not cheked another ships(i saw this promblem in multiplayer and singlepayer)

**Comment by Chaos456456** [comment] 2018-11-28 21:36
Also i saw sometimes when i turn autopilot to end point my ship is trying to move through the rocks and stoped.

**Comment by rico6822** [comment] 2018-12-06 10:21
I think it's because if you get too far from waypoints between 2 entrances of the level the A.I. of autopilot cannot find a waypoint responsible for dodging a rock, because it's non-existent, so it targets closest waypoint ignoring any obstacle. Possibly if you get too far from them autopilot truly stops completely like you said.

**Comment by Regalis11** [comment] 2019-05-20 13:36
I think this may have been caused by the bugs fixed in 05384a74 and 38e80eae. The pathfinder would assign a very high cost to path nodes that are underwater, and the total cost of the path would get so high that it would fail to find a path at all.

**Closed by Regalis11** 2019-05-20 13:36 UTC
Labels: Bug, Code
