### ISSUE TITLE
Shuttle shell A20 appears to be cut off

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#10821] opened 2022-12-26 05:15 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

bottom edge seems like it's clipped

![image](https://user-images.githubusercontent.com/5103517/209504438-3ce5e57b-e759-48fa-847d-198402ccfab6.png)
![image](https://user-images.githubusercontent.com/5103517/209504467-de837761-aecd-4e8a-b439-0743a90a09eb.png)

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-01-02 14:03
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/f6de70b2f5320ed917c4d50fd92714d6fdb5fd9f. Can't spot any issues, moving to QA

**Comment by Regalis11** [comment] 2023-01-10 16:10
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4a048fd11f900715435cce43f0cab8eb16501915. Note that I pushed this to bugfixes instead of wip-fixes, because the issue is not specific to the wip branch and it's better to keep the changes in dev/bugfixes to avoid conflicts.

**Comment by JeroonBosch** [comment] 2023-01-18 09:45
No issues found, closing

**Closed by JeroonBosch** 2023-01-18 09:45 UTC
Labels: Bug, Art
