### ISSUE TITLE
Unstable - "Error while reading a message from server"

### ISSUE THREAD

**Issue by Flotilla-zz** [Regalis11/Barotrauma#3422] opened 2020-07-28 06:11 UTC
**Description** Joined a campaign server with a game in progress, loaded into spectate mode, and while objects were still spawning in, was booted to the main menu.

**Steps To Reproduce** I joined the server three times; the boot to main menu occurred every time.

**Version** Latest unstable build as of 7/28/2020

**Additional information** 
[crashreport_object.log](https://github.com/Regalis11/Barotrauma/files/4986282/crashreport_object.log)
![20200728020002_1](https://user-images.githubusercontent.com/3611705/88625679-38bfc900-d077-11ea-958d-a31b479cdfbe.jpg)

**Comment by goalaleo** [comment] 2020-07-31 18:13
I got a similar error when trying to spectate a round that had already started
[crashreport_object.log](https://github.com/Regalis11/Barotrauma/files/5008415/crashreport_object.log)

Version 10.4.0

**Comment by Ruzihm** [comment] 2020-08-13 00:16
Got this in 10.4.0 as well

[crashreport_object.log](https://github.com/Regalis11/Barotrauma/files/5066499/crashreport_object.log)

**Comment by Kaillera** [comment] 2020-08-15 17:55
[Crash Report.txt](https://github.com/Regalis11/Barotrauma/files/5079223/Crash.Report.txt)
[FLCampaign.zip](https://github.com/Regalis11/Barotrauma/files/5079224/FLCampaign.zip)

Upon loading this save, will delete all the bots I have hired once it "Error while reading a message from server".

**Comment by Kaillera** [comment] 2020-08-16 01:44
[crashreport_object.log](https://github.com/Regalis11/Barotrauma/files/5079834/crashreport_object.log)
According to my friend, his server seems to crash due to having too many items on the floor.

**Comment by Regalis11** [comment] 2020-08-18 12:20
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3019

**Closed by Regalis11** 2020-08-18 12:20 UTC
Labels: Bug, Code, Networking
