### ISSUE TITLE
[0.1002.0] Our crew should not spawn in the Outpost by default

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3077] opened 2020-06-12 13:29 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I believe that our crew should not spawn in the Outpost by default. If we docked to a location that we have severely low reputation with, you'll be sniped by the outpost first thing. I fear that especially in multiplayer, the crew would get sniped by the outpost when the players are still at the loading screen.

**Version**
0.1002.0

**Comment by Regalis11** [comment] 2020-06-13 12:56
Duplicate of #2949

**Closed by Regalis11** 2020-06-13 12:56 UTC
