### ISSUE TITLE
Crash report - host clicked "Disconnect" when in lobby

### ISSUE THREAD

**Issue by ArtemSokolov** [Regalis11/Barotrauma#4133] opened 2020-10-25 05:49 UTC
Barotrauma Client crash report (generated on 10/25/2020 12:05:38 AM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

6F558E05A9FD96EA104348A23A5B582A

Game version 0.10.5.1 (ReleaseWindows, branch release, revision 9e259b2148)
Graphics mode: 1600x900 (Windowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9, USS Dumpster Fire (SSN-421), Rucksack 2.0
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.NetLobbyScreen
SteamManager initialized
Client (Round hadn't been started)

System info:
    Operating system: Microsoft Windows NT 10.0.19041.0 64 bit
    GPU name: NVIDIA GeForce GTX 1070 Ti
    Display mode: {Width:2560 Height:1080 Format:Color AspectRatio:2.3703704}
    GPU status: Normal

Exception: One or more errors occurred. (Cannot access a closed pipe.) (System.AggregateException)
Target site: Boolean Wait(Int32, System.Threading.CancellationToken)
Stack trace: 
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at Barotrauma.Networking.ChildServerRelay.ReadIncomingMsgs() in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 102
   at Barotrauma.Networking.ChildServerRelay.UpdateRead() in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 143
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()

InnerException: Cannot access a closed pipe.
Target site: Void CheckReadOperations()
Stack trace: 
   at System.IO.Pipes.PipeStream.CheckReadOperations()
   at System.IO.Pipes.PipeStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.<>c.<BeginReadInternal>b__43_0(Object <p0>)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at System.IO.Stream.EndRead(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)

**Comment by Regalis11** [comment] 2020-10-26 11:54
Duplicate of Regalis11/Barotrauma#3847

**Closed by Regalis11** 2020-10-26 11:54 UTC
Labels: Bug, Code, Crash
