### ISSUE TITLE
Crashing in Startup

### ISSUE THREAD

**Issue by LittleOrangeBottle** [Regalis11/Barotrauma#1517] opened 2019-06-05 21:52 UTC
Won't launch the game and crashes immediately. Have tried multiple fixes.

Windows 7. .NET framework is latest.

Barotrauma Client crash report (generated on 6/5/2019 2:37:38 PM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

84D97A22415E79CF8C19BAAC1D6B11B5

Game version 0.9.0.4
Graphics mode: 1920x1080 (BorderlessWindowed)
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized

System info:
Operating system: Microsoft Windows NT 6.1.7601 Service Pack 1 64 bit
Game not initialized

Exception: Object reference not set to an instance of an object.
Target site: Void Dispose(Boolean)
Stack trace: 
at Microsoft.Xna.Framework.Graphics.Effect.Dispose(Boolean disposing)
at Microsoft.Xna.Framework.Graphics.GraphicsResource.Dispose()
at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Dispose(Boolean disposing)
at Microsoft.Xna.Framework.GraphicsDeviceManager.Dispose(Boolean disposing)
at Microsoft.Xna.Framework.Game.Dispose(Boolean disposing)
at Microsoft.Xna.Framework.Game.Dispose()
at Barotrauma.Program.Main() in E:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\Program.cs:line 84

Last debug messages:
[6/5/2019 2:37:34 PM] Unknown SharpDX exception code (887A0005)
[6/5/2019 2:37:34 PM] SharpDX exception caught. (HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown, 887A0005). Attempting to fix...
[6/5/2019 2:37:34 PM] Loading texture "Content/Effects/waterbump.png" failed! {HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown}
at SharpDX.Result.CheckError()
at SharpDX.Direct3D11.DeviceContext.MapSubresource(Resource resourceRef, Int32 subresource, MapMode mapType, MapFlags mapFlags)
at SharpDX.Direct3D11.DeviceContext.MapSubresource(Texture2D resource, Int32 mipSlice, Int32 arraySlice, MapMode mode, MapFlags flags, DataStream& stream)
at SharpDX.Direct3D11.DeviceContext.MapSubresource(Resource resource, Int32 subresource, MapMode mode, MapFlags flags, DataStream& stream)
at Microsoft.Xna.Framework.Graphics.Texture2D.PlatformGetData[T](Int32 level, Int32 arraySlice, Rectangle rect, T[] data, Int32 startIndex, Int32 elementCount)
at Microsoft.Xna.Framework.Graphics.Texture2D.GetData[T](T[] data)
at Barotrauma.TextureLoader.PreMultiplyAlpha(Texture2D& texture) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\Utils\TextureLoader.cs:line 102
at Barotrauma.TextureLoader.FromFile(String path, Boolean preMultiplyAlpha) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\Utils\TextureLoader.cs:line 68

**Comment by thegrb93** [comment] 2019-06-05 21:58
Same as https://github.com/Regalis11/Barotrauma/issues/1515

**Comment by HeatedWafflez** [comment] 2019-06-05 23:22
Same kind of crash report for me as well, hoping for a fix since it seems there's a very few bunch who happen to fall victim to this unfortunate bug.

**Comment by LittleOrangeBottle** [comment] 2019-06-06 01:49
@HeatedWafflez  https://www.microsoft.com/en-ca/download/details.aspx?id=36805 downloading this helped my buddy.

**Comment by Regalis11** [comment] 2019-06-10 16:27
Duplicate of #1515

**Closed by Regalis11** 2019-06-10 16:27 UTC
