### ISSUE TITLE
[v0.1100.0.0 (unstable)] - Ballast flora permanently jams hatch open even after its killed

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#4151] opened 2020-10-28 15:39 UTC
**Description**
Ballast flora will permanently jam the hatch to ballast open since you're unable to plasma cut it to free it, even after its killed.

**Steps To Reproduce**
1) spawn ballast flora
2) open the hatch topside of it (using dugong)
3) attack it with flame thrower

**Version**
[v0.1100.0.0 (unstable)]

**Edit**
It seems to be able to permanently jam open doors too (picture below)

**Additional information**
![OpenJam](https://user-images.githubusercontent.com/72674994/97459469-c6f96300-1976-11eb-9db1-dbddcc9c4e93.jpg)
![doorjam2](https://user-images.githubusercontent.com/72674994/97463333-99aeb400-197a-11eb-9e58-5ff285f2b6eb.jpg)

**Comment by Udrakan** [comment] 2020-10-28 15:56
Can confirm this happening to me on Typhon 2
https://cdn.discordapp.com/attachments/668819422919524352/771016296506720356/bfbug1.gif

**Comment by 3e849f2e5c** [comment] 2020-10-28 16:17
Possibly fixed in https://github.com/Regalis11/Barotrauma-development/commit/168ecdd7ad199e2b8a451b60e58a9193b2910da4 happened because the ballast flora closed and stuck the door at the same time and opening/closing doors has animation delay the door won't update the door state while it's stuck

**Comment by Rokvach** [comment] 2020-10-29 08:34
Tested, wasn't able to reproduce anymore, working correctly. Closing.

**Closed by Rokvach** 2020-10-29 08:34 UTC
Labels: Bug, Code
