### ISSUE TITLE
Unstable - 'Activate a Beacon' mission does not count as activating a beacon in map meta.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#5260] opened 2021-03-15 23:39 UTC
If a path node has a beacon on it already & the game decides to also assign an 'activate a beacon' specific paid mission, accepting it and completing the mission successfully does not actually count as the beacon on that path being activated.

Accept Mission -> Activate beacon -> Finish Level -> Campaign map shows beacon as inactive still.

**Comment by Regalis11** [comment] 2021-03-16 08:44
I'm afraid I could not reproduce this.

**Comment by Rokvach** [comment] 2021-03-17 12:58
Afaik beacon missions are only side missions now, so can't see how to reproduce this issue anymore or that this is a issue. Closing

**Closed by Rokvach** 2021-03-17 12:58 UTC
Labels: Bug, Code, Need more info, Needs testing
