### ISSUE TITLE
Failed to create OpenAL buffer for non-streamed sound: Invalid value

### ISSUE THREAD

**Issue by Sheeeeep222** [Regalis11/Barotrauma#4430] opened 2020-12-04 17:18 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Regardless of the mode, if you play with difficulty level 50% or higher, it will crash.

**Steps To Reproduce**
1. Launch the game
2. Host a local server
3. Set the difficulty to 50% or higher in any game mode
4. Round start
5. Crash

**Version**
v0.10.6.2  

MacOS11.0.1 Big Sur

**Additional information**

Computer specs
[Macbook Pro]
Processor : 2.4 GHz Quad Core Intel Core i5 
Memory : 8 GB 2133 MHz LPDDR3
Graphics : Intel Iris Plus Graphics 655 1536 MB

Crash Report
[crashreport (11).log](https://github.com/Regalis11/Barotrauma/files/5644194/crashreport.11.log)

**Comment by itchyOwl** [comment] 2020-12-10 06:23
Edited the title, because according to the crash log, it's an audio related issue.

**Comment by Regalis11** [comment] 2021-01-11 17:37
Seems to be a duplicate of https://github.com/Regalis11/Barotrauma/issues/4504

**Closed by Regalis11** 2021-01-11 17:37 UTC
Labels: Bug, Code, Crash, Medium Prio
