### ISSUE TITLE
Object reference not set to an instance of an object. (System.NullReferenceException)

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#5266] opened 2021-03-17 16:41 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.
I don't know how to search for a specific stack trace.

**Description**
```
Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void Act(Single)
Stack trace: 
   at Barotrauma.AIObjectiveIdle.Act(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjectiveIdle.cs:line 159
   at Barotrauma.HumanAIController.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\HumanAIController.cs:line 267
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2384
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 172
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 925
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

```
**Steps To Reproduce**
???

**Version**
v0.12.0.3 Windows 20H2 64-bit

**Additional information**
I wasn't doing anything specific. All the characters in my singleplayer campaign but the one I controlled had orders to stand still.
[crashreport (3).log](https://github.com/Regalis11/Barotrauma/files/6158094/crashreport.3.log)

**Comment by Krzeszny** [comment] 2021-03-18 20:37
Another crash, about the same stack trace
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/6167060/crashreport.log)

**Comment by itchyOwl** [comment] 2021-03-19 13:00
I wonder if the line numbers can be right. There's just a property accessor to "PathSteering" at the line 159, so it can't crash there.

Does it happen randomly or are there specific circumstances where it happens?

**Comment by Krzeszny** [comment] 2021-03-21 20:22
> I wonder if the line numbers can be right. There's just a property accessor to "PathSteering" at the line 159, so it can't crash there.
> 
> Does it happen randomly or are there specific circumstances where it happens?

I have a suspicion. The pumps in one of my ballast tanks weren't tagged as "pump,ballast". But I'm not sure. It's been happening absolutely randomly from my point of view.

**Comment by diegoyocys** [comment] 2021-03-22 22:11
[crashreport (60).log](https://github.com/Regalis11/Barotrauma/files/6185529/crashreport.60.log)

similar report. exeption the same, target site NOT the same. crash reason different and nothing specific causes it, nearly at the bottom of report it says "WARNING: 400 buffer(s) were generated. No more sound buffers will be generated." I dont know if this is somehow the cause, just as some other crashes says: Failed to generate stream buffers,

note: I am on Mac

**Comment by itchyOwl** [comment] 2021-03-23 08:33
Exception: Object reference not set to an instance of an object. (System.NullReferenceException) is a common exception that happens when there's a missing reference in the code. The latter report is not related to this issue, because the stack trace is completely different. @juanjp600 would you take care of it?

**Comment by itchyOwl** [comment] 2021-03-24 10:22
Yeah, the initial issue is not fixed. Haven't been able to reproduce or spot the issue, let's keep the eyes open!

**Comment by shootybangman** [comment] 2021-03-30 13:37
I got this same error. I was making a submarine, I hit test, and it had same the exception as this report. I looked at the stack trace and it looked like it had something to do with the submarine itself and the position where it was placed. At the time, I had another submarine placed inside of the one I was building around, and the submarine I was building around was null, it didn't have anything in it. So it looked like I was making a new submarine altogether, but there _was_ another submarine entity inside of the one I was building. So when I hit the test button, nothing even happened and it just crashed. My hypothosis is that either it didn't like that the 2 submarine entities I put next to each other, so they collided, or that I put my spawnpoint too low and the sub want flying out of the water.

**Comment by itchyOwl** [comment] 2021-03-31 08:47
Seems like the subBody (SubmarineBody) was null for some reason.

Again: it's completely separate issue, caused by a different code. Just the exception is the same.

Anyway, thanks for the crash report, we are looking into it!

**Comment by Krzeszny** [comment] 2021-04-30 23:16
I got another one
```Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: TransitionType GetAvailableTransition(Barotrauma.LevelData ByRef, Barotrauma.Submarine ByRef)
Stack trace: 
   at Barotrauma.CampaignMode.GetAvailableTransition(LevelData& nextLevel, Submarine& leavingSub) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameModes\CampaignMode.cs:line 370
   at Barotrauma.CampaignMode.Draw(SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\CampaignMode.cs:line 115
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\GameScreen.cs:line 99
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 1026
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58```
[crashreport (4).log](https://github.com/Regalis11/Barotrauma/files/6408446/crashreport.4.log)

**Comment by Krzeszny** [comment] 2021-05-21 14:31
Another one (bites the dust) and RIP my several-hour-long mission

```Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void UpdateFollow(Single)
Stack trace: 
   at Barotrauma.EnemyAIController.UpdateFollow(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\EnemyAIController.cs:line 2069
   at Barotrauma.EnemyAIController.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\EnemyAIController.cs:line 715
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2418
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 204
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 947
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

**Comment by itchyOwl** [comment] 2021-05-24 08:07
Thanks for reporting. However, all these exceptions would use a separate ticket, because they are not related to each other in any way.

**Comment by itchyOwl** [comment] 2021-05-24 09:05
Regarding the latest report: the line numbers don't seem to be correct this time either. I wonder what's going on there. I read through the UpdateFollow method using `#nullable enable`, but I couldn't spot anything that could throw a null reference exception there.

**Comment by Krzeszny** [comment] 2021-05-25 18:05
> Thanks for reporting. However, all these exceptions would use a separate ticket, because they are not related to each other in any way.

Would it help if I were to create separate tickets for all the reports right now?
Also, can you teach me how to tell if exceptions are related to one another?

**Comment by itchyOwl** [comment] 2021-05-26 11:43
On how to read the logs: If the stack trace points to the same lines in the code, it's the same issue. Otherwise it's not. It's just like reference to a text book: if there's a grammar error in line 91 of page 1 and another in line 108 of page 10, they are not related even though the error would be of the same type (like a punctuation error).

So if there's an exception in line 2069, method Barotrauma.EnemyAIController.UpdateFollow(Single deltaTime), in file <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\EnemyAIController.cs, it's not the same as an exception in line 370, method Barotrauma.CampaignMode.GetAvailableTransition(LevelData& nextLevel, Submarine& leavingSub), of <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameModes\CampaignMode.cs. You only need to check the first line of the stack trace to find that out.

But yeah, it might be a good idea to create separate tickets for the different issues. It would help if you could give a description about what was happening and what did you do in the game. In the ideal case, you could provide the steps for reproducing the issue (how to make it happen) that we could just follow and cause the crash. When we can do that, it won't usually take more than a couple of minutes to fix it.

Exceptions are usually easy to fix, if we can just spot where it happens in the code. But with these reports the lines don't make any sense. It's not your fault, but we haven't found the reason why it sometimes happens.

Thanks for helping us out!

**Comment by itchyOwl** [comment] 2021-09-03 08:00
I'll close this ticket, because it doesn't describe any single issue. Please create new tickets for the issues, if they remain unfixed.

**Closed by itchyOwl** 2021-09-03 08:00 UTC
Labels: Bug, Need more info, Needs testing, Code
