### ISSUE TITLE
Including ':' in prefab name crashes the game on linux.

### ISSUE THREAD

**Issue by LatekVo** [Regalis11/Barotrauma#9784] opened 2022-08-28 22:51 UTC
Edit: This, initial entry is incorrect, further info in comments.

### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Trying to save an incomplete prefab while in the submarine editor causes a crash.
More info in the "reproduction steps" section.

### Reproduction steps

1. Build an array of 2 or more modules (addition, deletion, multiplication)
2. Connect all of them together using wires.
3. Select all but one of the objects.
4. Save the selected objects as a prefab.

This is where the game crashes, it's repeatable.

### Bug prevalence

Happens every now and then

### Version

Other

### -

Native linux build. Command: "prime-run gamemoderun %command%"

### Which operating system did you encounter this bug on?

Linux

### Relevant error messages and crash reports

```shell
﻿Barotrauma Client crash report (generated on 08/29/2022 00:29:11)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


AA0FABA7B021621B9FF337EF2D2E272F


Game version 0.18.15.1 (ReleaseLinux, branch hf, revision 91a05f31ff)
Graphics mode: 1920x1080 (Fullscreen)
VSync OFF
Language: English
Selected content packages: Vanilla, XXXX
Level seed: no level loaded
Loaded submarine: XXXX (XXXX)
Selected screen: Barotrauma.SubEditorScreen
SteamManager initialized


System info:
    Operating system: Unix X.X.X.X 64 bit
    GPU name: 
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: Could not find a part of the path '/storage/SteamLibrary/steamapps/common/Barotrauma/LocalMods/Mod: Configurable Osicllator/Mod: Configurable Osicllator.xml'. (System.IO.DirectoryNotFoundException)
Target site: Void ThrowExceptionForIoErrno(ErrorInfo, System.String, Boolean, System.Func`2[Interop+ErrorInfo,Interop+ErrorInfo])
Stack trace: 
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.Xml.XmlWriterSettings.CreateWriter(String outputFileName)
   at System.Xml.XmlWriter.Create(String outputFileName, XmlWriterSettings settings)
   at System.Xml.Linq.XDocument.Save(String fileName, SaveOptions options)
   at Barotrauma.IO.SafeXML.SaveSafe(XDocument doc, String path, SaveOptions saveOptions, Boolean throwExceptions) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SafeIO.cs:line 115
   at Barotrauma.SubEditorScreen.<>c__DisplayClass130_0.<SaveAssembly>g__Save|0() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SubEditorScreen.cs:line 3012
   at Barotrauma.SubEditorScreen.SaveAssembly(GUIButton button, Object obj) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SubEditorScreen.cs:line 3022
   at Barotrauma.GUIButton.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 263
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1167
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 898
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59


Last debug messages:
[08/29/2022 00:24:32] Attempting to open ALC device "Built-in Audio Analog Stereo"
[08/29/2022 00:24:12] Logged in as XXXXX (SteamID STEAM_1:0:XXXXXXXXX)
```

**Comment by Regalis11** [comment] 2022-08-29 09:32
Thank you for the report!

I'm afraid I could not reproduce the issue. The error message seems to indicate the game is somehow failing to find the directory it's trying to save the item assembly into, so I don't think this is related to one of the objects being unselected, but some other factor that I couldn't figure out myself.

**Comment by LatekVo** [comment] 2022-08-29 13:51
I found the real issue, the problem was that i was testing it wrong.
The issue is just including "Mod: XXX" in the prefab name. This may be just a linux issue as well.

**Comment by Regalis11** [comment] 2022-08-30 09:32
Thanks, that seemed to have been the problem! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/88d64abee88bf3c0482253fe4a5d817e33e6ff1d

**Comment by LatekVo** [comment] 2022-08-30 14:16
Great, closing now.

**Comment by Rokvach** [comment] 2022-09-30 06:28
Tested, working correctly. Closing.

**Closed by Rokvach** 2022-09-30 06:28 UTC
Labels: Bug, Linux only, Code, Crash, Unstable
