### ISSUE TITLE
Crash reports in the steam version do not indicate line numbers

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1285] opened 2019-03-16 16:13 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Upon reading a crash report (Related to the game crashing with modded xml files, somewhere in updateattack() for enemy AI controllers but unknown as to any other details) I noticed it was both windows and had no line numbers, upon forcing the game to crash by removing one of the key required content items to induce one in my own steam copy of barotrauma - I also saw no line numbers.

**Steps To Reproduce**
Crash the game on the steam release version that is provided in the steam files.

**Version**
0.8.9.5 steam closed alpha

**Additional information**
I believe the necessary files to provide more information on a crash are absent, such as the .pdb files, which could be included in the executable itself I believe in some form of project settings or to be included in the download.

Without the extra debug information, crash information (This is an induced crash and is nothing to fix) only states this level of detail:

```csharp
Exception: Object reference not set to an instance of an object.
Target site: Void Draw(Microsoft.Xna.Framework.Graphics.SpriteBatch, Microsoft.Xna.Framework.Graphics.GraphicsDevice, Single)
Stack trace: 
   at Barotrauma.LoadingScreen.Draw(SpriteBatch spriteBatch, GraphicsDevice graphics, Single deltaTime)
   at Barotrauma.GameMain.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at MonoGame.Framework.WinFormsGameWindow.TickOnIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at MonoGame.Framework.WinFormsGameWindow.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Barotrauma.Program.Main()
```

**Comment by Regalis11** [comment] 2019-03-19 19:14
Should be fixed now, this way caused by SteamPipe's build scripts automatically stripping out all .pdb files.

**Closed by Regalis11** 2019-03-19 19:14 UTC
Labels: bug
