### ISSUE TITLE
Problem with Typhon

### ISSUE THREAD

**Issue by TRAVNIKexe** [Regalis11/Barotrauma#11760] opened 2023-04-06 15:45 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Good afternoon! I bought Typhon today, and I understood why other players complained about it. You screwed up with the location of the gyroscopes. They should be slightly lower so that the bots can reach them. Now, at the command to stand behind the gun, they say that it is impossible to get to the gyroscopes and they have to be placed manually. Please fix it as soon as possible, because many people have already become disillusioned with this submarine, despite its potential. Thank you for your attention! Hope you fix this as soon as possible!

### Reproduction steps

1. Start campain 
2. Buy Typhon

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by AshEdwardsDesign** [comment] 2023-04-08 11:44
Already reported on #11552

**Comment by Regalis11** [comment] 2023-04-09 09:44
Duplicate of #11552

**Closed by Regalis11** 2023-04-09 09:44 UTC
Labels: Bug, Duplicate, Code
