### ISSUE TITLE
Error When Attempting to Output Audio to Monitor

### ISSUE THREAD

**Issue by IronEleven** [Regalis11/Barotrauma#12089] opened 2023-05-28 01:56 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

My current audio setup involves using the speaker port on my monitor.  When attempting to start Barotrauma with the monitor selected as my default audio device, audio cuts out after a brief moment on the opening logo videos.

### Reproduction steps

1. Start Barotrauma with a monitor selected as a default audio device in windows (Exact configuration: Speakers connected to a Pixio PX277 Prime connected via DisplayPort to an AMD Radeon RX 6700 XT)
2. Switch audio devices
3. Switch back to monitor (Sound now works but additional console errors appeared)

### Bug prevalence

Happens Every Time I Play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Attempting to open ALC device "OpenAL Soft on 5 - Pixio PX277P (2- AMD High Definition Audio Device)"
Playback device has been disconnected. You can select another available device in the settings.
Attempting to open ALC device "<disconnected>"
WASAPI playback device init failed: HRESULT 0x80004005
ALC device initialization attempt #1 failed: device is null (error code Invalid value)
Switching to default device...
WASAPI capture open failed: HRESULT 0x80004005 (1)
alcCaptureOpenDevice failed: exception thrown (Device init failed: 0x80004005)
Alc.CaptureOpenDevice attempt 1 failed: error code 40964
WASAPI capture open failed: HRESULT 0x80004005 (1)
alcCaptureOpenDevice failed: exception thrown (Device init failed: 0x80004005)
Alc.CaptureOpenDevice attempt 2 failed: error code 40964
Attempting to open ALC device "OpenAL Soft on Speakers (Sound Blaster Play! 3)"
Attempting to open ALC device "OpenAL Soft on 5 - Pixio PX277P (2- AMD High Definition Audio Device)"
Playback device has been disconnected. You can select another available device in the settings.
Attempting to open ALC device "<disconnected>"
WASAPI playback device init failed: HRESULT 0x80004005
ALC device initialization attempt #1 failed: device is null (error code Invalid value)
Switching to default device...
```

**Comment by Jasontti** [comment] 2023-08-24 13:14
Tested, could not reproduce.
Used HDMI audio out and switched between outputs, restarted between, no issues or errors.

**Comment by Regalis11** [comment] 2023-09-05 10:11
No known steps to repro, closing

**Closed by Regalis11** 2023-09-05 10:11 UTC
Labels: Bug, Need more info, Code
