### ISSUE TITLE
Cursor got stuck as a grasping/fist graphic

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#2227] opened 2020-02-09 00:27 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![image](https://user-images.githubusercontent.com/29177976/74093870-0376ed00-4ad0-11ea-89b8-9ea3d89e238c.png)

https://i.gyazo.com/cbdcb69d8a73438aacb1c3b615009ae2.mp4

Insanity-inducing minor bug for the OCD. - I dont recall how it was caused, only that it persisted when clicking, dragging items, getting on/off turret controllers, even going to the lobby screen and the games main menu.

**Steps To Reproduce**
Unknown.

**Version**
0.9.705.0 Unstable windows - client.

**Comment by Regalis11** [comment] 2020-02-09 15:14
By looking through the code, I only found one way to make this occur: if dragging a wire in the wiring interface is interrupted by any other reason than letting go of the left mouse button (e.g. electrocution, getting killed, ending the round...), the cursor would get stuck to the grab case.

Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bab0f967c07cb3495b61eea2f5b4f56b4ab160b2

**Comment by NilanthAnimosus** [comment] 2020-02-09 16:23
I honestly do not remember opening a wiring interface, im sure I was playing with items, but I did at one single point open the wiring for a medical fab that wasn't crafting at round start (Known issue - just click craft button again) but I cancelled ripping the wire out and escaped/walked off from the actual UI.

It could be that as the cause, but then I'd have to have no noticed for a very long time perhaps.

**Comment by Rokvach** [comment] 2020-02-09 21:16
Tested, couldn't reproduce the issue, closing.

**Closed by Rokvach** 2020-02-09 21:16 UTC
Labels: Bug, Code
