### ISSUE TITLE
Forward section(s) of Separatist Sub not repairable

### ISSUE THREAD

**Issue by Agent-Delta** [Regalis11/Barotrauma#11550] opened 2023-03-15 18:25 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Yesterday (March 14th) my friends and I were continuing through our multiplayer campaign, started some months ago. Our reputation with the Separatists was already at Hostile (-80) and we were attacked by a Separatist sub during our first full round in game version 1.07. We sunk their sub, but they were above us and therefore landed on top of us as they sank, pinning us to the sea floor. After finishing off the remaining Separatist sailors, we began repairing their sub just so we could move it off of our sub and get away. After repairing nearly everything and getting power restored to all critical systems, we found there were leaks at the front of the Separatist sub that we could not fix, meaning water was constantly flooding at least part of the sub.

![20230314224524_1](https://user-images.githubusercontent.com/126107030/225402015-92e05645-951a-4aa3-83b0-5c7c19799c6d.jpg)

We spent about 15 minutes just trying to repair these 2 remaining leaks but could not fix them from either inside or outside the sub. There were parts (what appeared to be exterior structure pieces) on the outside of the sub at roughly the shown areas that looked broken, but we could not fix them with welding tools or anything else.

Eventually, we were able to confine the water to the two rooms shown on the status monitor in the picture. This was just enough to allow the sub to move upwards with the help of our sub ALSO pushing up on it, i.e. we finally got free and ultimately arrived at Boeotia Macula. The above picture was taken just after getting our ship free (shown on the left holding a wreck logbook marker) and allowing the Separatist sub to settle on the sea floor.

Maybe non-player subs are supposed to function differently, but we were obviously expecting to be able to repair all parts of the hull and stop all leaks. Fortunately, this did not doom our round to failure and actually turned out to be an entertaining challenge for us, but it was still somewhat frustrating to deal with.

NOTE: the only mod on the server is [this one](https://steamcommunity.com/sharedfiles/filedetails/?id=2910964157), for craftable/placeable ammunition shelves. Very unlikely to be interfering here but noted for transparency's sake.

### Reproduction steps

1. Spawn this model of Separatist sub in open water
2. Destroy front part of sub with explosive flak shells (I believe this is what we were using at the time)
3. Take note of leaks on Separatist sub's status monitor
4. Attempt to fix all leaks

### Bug prevalence

Just once

### Version

v1.0.7.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-03-15 18:29
Duplicate of https://github.com/Regalis11/Barotrauma/issues/9319

**Closed by Regalis11** 2023-03-15 18:29 UTC
