### ISSUE TITLE
Sootman not setting outpost on fire or returning to submarine

### ISSUE THREAD

**Issue by StruggleDuck** [Regalis11/Barotrauma#11383] opened 2023-02-27 17:15 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

After freeing sootman, he just stood around and didn't do anything, preventing us from proceeding. There was also another jailbreak mission happening simultaneously, which could have caused the issue. Another side note is that after enough time passed, the prisoners used all the oxygen in their cell and suffocated. 

![image-17](https://user-images.githubusercontent.com/92034548/221632887-77ebe8f5-9688-4c1e-932a-deb39abef398.png)
![image-10](https://user-images.githubusercontent.com/92034548/221632910-52aff966-35af-4ba3-b71f-f9c28333694a.png)

### Reproduction steps

Have both jailbreak missions at the same outpost?

### Bug prevalence

Just once

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-02-27 18:47
Thank you for the report!

I unfortunately couldn't find a way to reproduce this. I think it could be that it only happens in specific outposts - perhaps the NPC couldn't find the way to the correct module or the sub? If you still have the save file, it _might_ give us some more clues for diagnosing this.
https://user-images.githubusercontent.com/14351070/221654825-0a6f39e1-69f5-4a71-bc0e-6ef238c9fdf4.mp4

**Comment by StruggleDuck** [comment] 2023-02-27 19:08
Right now, I only have access to a save file from 2 days ago, and I do not know what stage of the mission line it is. I will be certain to upload a more up to date save file when I have access to my main computer. 
[TERRORIST.LIFESTYLE.zip](https://github.com/Regalis11/Barotrauma/files/10843146/TERRORIST.LIFESTYLE.zip)

**Comment by Regalis11** [comment] 2023-02-27 20:28
Thanks! 

I suspect the important part in reproducing the issue is testing it in the same outpost (with the same layout and same waypoints), so this will most likely help. I'll give it another test tomorrow!

**Comment by Regalis11** [comment] 2023-03-12 09:48
No known steps to repro, closing

**Closed by Regalis11** 2023-03-12 09:48 UTC
Labels: Bug, Need more info, Code
