### ISSUE TITLE
Artifact spawned inside terrain (save included)

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#3421] opened 2020-07-27 22:59 UTC
**Description**
![image](https://user-images.githubusercontent.com/59519434/88599950-56883080-d06d-11ea-88ef-3c11f5e9c37e.png)
Load the save and look to the right of the ruin. Artifact spawn point is inside terrain
![image](https://user-images.githubusercontent.com/59519434/88600001-79b2e000-d06d-11ea-8182-b065d19d088c.png)
![image](https://user-images.githubusercontent.com/59519434/88600103-b252b980-d06d-11ea-9820-1f228b0328b9.png)

SAVE:
[Save_6.zip](https://github.com/Regalis11/Barotrauma/files/4985010/Save_6.zip)

**Steps To Reproduce**
Load save
Check artifact inside the terrain to the right of ruins

**Version**
Unstable

**Additional information**

**Comment by Regalis11** [comment] 2020-07-28 10:35
Duplicate of #2731

**Closed by Regalis11** 2020-07-28 10:35 UTC
