### ISSUE TITLE
40964 Error - suitable capture device not found

### ISSUE THREAD

**Issue by SKEPPLamp** [Regalis11/Barotrauma#11631] opened 2023-03-21 23:22 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Cannot use voice chat in game. When I try to enable Push-to-Talk in settings the error in the title appears.
The microphone itself does appear as a device in the drop-down menu, regardless the game claims that a suitable device could not be found, and as such does not work in multiplayer.

I have tried:
>turning "Allow apps to access your microphone" on (already was)
>disabling "Allow applications to take exclusive control of this device"
>closing other apps that may be taking microphone priority
>reinstalling the game
>using VoiceMeeter, but that simply resulted in Barotrauma not recognising both my speakers and microphone, despite everything else (Windows sounds, other games, etc.) working correctly

Windows, audio, etc., drivers are on their latest version
microphone also doesn't have any non-English characters (unless brackets count as non-English?)

microphone device name: Microphone Array (Realtek(R) Audio)
-that's a built-in laptop mic
operating system and language: Windows 10 Home 22H2, English UK

screenshot of console error messages attached:
![tmuNKtD](https://user-images.githubusercontent.com/128552875/226761387-a940cedc-c6b7-4ad8-a896-e43388b139ab.png)

### Reproduction steps

>go into settings on game start-up
>40964 error appears

can make error appear repeatedly by:
>go into audio settings
>select push-to-talk from drop-down menu (it moves itself back to disabled after closing the settings menu)
>apply
>close settings window
>go back into settings
>40964 error appears

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-03-22 02:40
Duplicate of https://github.com/regalis11/barotrauma/issues/4461

**Closed by Regalis11** 2023-03-22 02:40 UTC
