### ISSUE TITLE
Bot AI problem

### ISSUE THREAD

**Issue by SavaAlienFish** [Regalis11/Barotrauma#11768] opened 2023-04-07 20:12 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Bots are not able to get to the weapon periscopes on Typhon submarine for some reason. Even if they stand right next to them they say in the chat that they cant get to the periscopes.
i understand why can it happen with mod submarines but how does it appear with a vanilla one. how can i fix this? this makes playing on Typhon in campaign basically impossible.

### Reproduction steps

1. Buy the submarine typhon in campaigh
2. Try to command bots to use any weapon on the submarine

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by AshEdwardsDesign** [comment] 2023-04-08 11:42
Already reported on #11552

**Comment by Regalis11** [comment] 2023-04-09 09:44
Duplicate of #11552

**Closed by Regalis11** 2023-04-09 09:44 UTC
Labels: Bug, Duplicate, Code
