### ISSUE TITLE
Bots get stuck on the stairs on the Typhon boat (1)

### ISSUE THREAD

**Issue by Maugly1** [Regalis11/Barotrauma#12193] opened 2023-06-19 15:57 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

On the Typhon boat (1), the bots get stuck on the stairs leading to the engine and oxygen system. However, some (not all) bots can follow a player there on command.
This happened after the update on 06/15/2023, it was fine before that.
![2023-06-19_18-48-24](https://github.com/Regalis11/Barotrauma/assets/137092033/898b6d8e-acf9-42e8-b1fe-1e0eefb6e235)

### Reproduction steps

1. Launch a single-user campaign
2. Start the mission using the Typhon boat
3. Break something in the back compartment to speed up the error or just wait for the bots to go there themselves
4. Watch the bots get stuck on the stairs

### Bug prevalence

Happens every time I play

### Version

v1.0.20.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-06-19 16:10
Duplicate of https://github.com/Regalis11/Barotrauma/issues/12183

**Closed by Regalis11** 2023-06-19 16:10 UTC
