### ISSUE TITLE
Cargo Mission - Partial delivery always rewards 1 crate only

### ISSUE THREAD

**Issue by survaaki** [Regalis11/Barotrauma#6516] opened 2021-08-29 05:15 UTC
- [X ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When completing a cargo mission, it rewards for a single crate delivery only. This is the case with partial deliveries  (ie, 8/10 crates delivered by Dugong). I have not confirmed it applies to full deliveries

**Steps To Reproduce**
Complete a cargo mission for more than 8 crates in a Dugong.

**Version**
0.14.9.0 Windows

**Additional information**
Undertow Games Discord #baro-tech-support
https://discord.com/channels/103209684680323072/587647684794515468/880541246031007784
Has screenshots

**Comment by Regalis11** [comment] 2021-08-29 11:43
Thank you for the report!

I'm afraid I couldn't find a way to reproduce this. I tried completing the exact same mission, with 8 crates on board:
![image](https://user-images.githubusercontent.com/14351070/131249109-f506dea0-2a08-4027-877b-f2a88aef9ba5.png)

And got rewarded for delivering all 8 crates:
![image](https://user-images.githubusercontent.com/14351070/131249115-281f8095-8f5d-46f2-99da-aa09a2e73df2.png)

So I'd guess this issue only happens in some specific circumstances, and just doing a partial delivery isn't enough to get it to occur. Let's keep an eye out for this and see if we can figure out a way to repro it.

**Comment by PetMudstone** [comment] 2021-08-30 19:00
I experienced this bug too, but I haven't been able to consistently reproduce it. See [here](https://discord.com/channels/103209684680323072/157565009726144513/881659081365024778) and [here](https://discord.com/channels/103209684680323072/157565009726144513/881667564571361320) for successful reproductions.

**Comment by war-wizard** [comment] 2021-09-02 01:43
As far as I can tell this bug is only happening in multiplayer, both self hosted server and dedicated server.

I've tried debugging a bit and found out that CargoMission is recalculating the reward at the end of mission for some reason, but since all slots in cargo are occupied, it ends up setting it to one crate.

So, a workaround for the bug is to simply take all of the crates from shelves before ending the round.

**Comment by war-wizard** [comment] 2021-09-02 03:53
Figured out the bug.

GetReward is recalculating the reward because the current location changed before End() is called for missions (which only happens in multiplayer, not in singleplayer).

A simple check to stop GetReward from doing the calculation of the reward if we are not at the location of the mission is enough to fix the bug.

**Comment by Regalis11** [comment] 2021-09-06 15:20
@war-wizard Thank you for the help! Pushed a fix in https://github.com/Regalis11/Barotrauma-development/commit/4af7d3c25d37be0e89eb9d09a18d1a69f72a6f58

**Comment by war-wizard** [comment] 2021-09-06 18:50
@Regalis11 no problem, glad to be of help

Just in case anyone gets here through google:

**The workaround for this bug is to drop all crates off the shelves before docking / ending the round**

**Comment by NotZang** [comment] 2021-09-15 02:40
I hope this fix is applied soon. I just now found this and learned the workaround.

**Comment by Rokvach** [comment] 2021-09-16 09:52
Tested, working correctly. Closing.

**Closed by Rokvach** 2021-09-16 09:52 UTC
Labels: Bug, Code
