### ISSUE TITLE
Endless increasing burns after geting hit by hot(?) water from a Volcano.

### ISSUE THREAD

**Issue by roidal** [Regalis11/Barotrauma#2003] opened 2020-01-16 14:10 UTC
The burn-damage received by a character after geting close to a vulcano increases slowly until the character dies, even if geting away from the vulcano.

**Comment by hubismal** [comment] 2020-01-18 07:15
is this not just the radiation sickness status effect?

**Comment by NilanthAnimosus** [comment] 2020-01-18 22:21
radiation sickness is hidden below a value of 10, but takes effect beyond 0 at a rate of 0.25 burn affliction / second.

However, this is stated as caused by a volcano (Does not cause it) instead of a reactor explosion / nuclear shell / nuclear depth charge or radiotoxin, and radiotoxin would cause more than 10 radiation sickness (Most of these likely would unless far enough away to be caught by the very outer blast).

**Comment by roidal** [comment] 2020-01-19 13:39
Looks like this bug can not be only triggered by vulcanos but also from "normal" burn-damage.

**Comment by Regalis11** [comment] 2020-01-20 19:58
Just gave this a test, but I wasn't able to make either volcanoes, fires or plasma cutters do continuous damage to the characters. My guess would also be that you somehow managed to get radiation sickness from somewhere. If this happens again, could you try and check your status with the Health Scanner HUD and make sure you don't have any other afflictions that could be causing the damage.

**Comment by roidal** [comment] 2020-01-20 20:42
I did and it was burn-damage only; no radiation sickness.
It is very rar (i saw it only 3 times until now).

**Comment by roidal** [comment] 2020-01-21 08:35
PS: In all three cases it was water involved.
The first 2 times i was diving outside when getting the first burndamage, which then continued to get more. The third time it was inside the ship, a grenade (or UEX/C-4 block) was exploding dealing burndamage while water was flooding the room because of breached outer wall.

**Comment by Kaillera** [comment] 2020-05-07 13:15
So I was able to get this in singleplayer.

![](https://cdn.discordapp.com/attachments/157565009726144513/707941354486890563/Capture.PNG)
![](https://cdn.discordapp.com/attachments/157565009726144513/707941996232179792/Capture.PNG)

I was able to come back alive with a steroid and two doses of morphine. However coming back to the sub, character's legs are constantly getting burnt with no end.

**Comment by Regalis11** [comment] 2020-05-11 09:48
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/fa8adf82390c2f26e4637af7330917f2e4b9cbc3

**Comment by Rokvach** [comment] 2020-05-13 11:35
Tested in dev, which should have the latest changes from bugfixes merged.

Volcanoes doesn't seem to be doing any damage to the crew or submarine, I did teleport my submarine in godmode on top of a active volcano, but even then if I went for a swim or turned off godmode the volcano didn't cause any damage.  @Regalis11

**Comment by Regalis11** [comment] 2020-05-13 13:02
Ah, the maximum distance was defined in sim units when it should've been in display units, so the character/sub had to be very close to the center of the trigger to be affected. Should be fixed now in 3b5f9a6

**Comment by Rokvach** [comment] 2020-05-13 13:14
Seems to be working correctly. Closing.

**Closed by Rokvach** 2020-05-13 13:14 UTC
Labels: Bug, Code
