### ISSUE TITLE
Storage containers saved as assemblies do not keep items

### ISSUE THREAD

**Issue by Momiro** [Regalis11/Barotrauma#4157] opened 2020-10-29 18:34 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When saving a storage locker, container, or cabinet filled with items as an assembly, and then placing it, the storage container is spawned empty. This is an issue specific to this release, as it was not happening yesterday.
EDIT: It seems like duplicating storage containers already placed within the submarine editor is broken too. When filling a storage, and then copying it, by ctrl+click and drag, the duplicated container spawns empty.

**Steps To Reproduce**
Explained in issue description.

**Version**
0.10.6.2

**Comment by EricPfau** [comment] 2020-10-29 20:49
Oh my god I hope they hotfix this FAST. From a sub designer perspective this is terrible. You also can't copy paste items with inventories in them.

**Comment by 3e849f2e5c** [comment] 2020-10-29 21:20
Duplicate of #4080

This fix is included on the unstable version already <https://barotraumagame.com/announcements/barotrauma-tester-version-made-public/>

**Closed by 3e849f2e5c** 2020-10-29 21:20 UTC

**Comment by EricPfau** [comment] 2020-10-30 02:15
Issue https://github.com/Regalis11/Barotrauma/issues/4080 was reported 15 days ago and was closed. The issue still exists.

**Comment by EricPfau** [comment] 2020-10-30 02:17
![image](https://user-images.githubusercontent.com/73270156/97652322-75afa900-1a34-11eb-8460-dd0c41f351cb.png)

**Comment by Rokvach** [comment] 2020-10-30 07:52
This fix didn't make it in to the update, can be tested in Unstable.
