### ISSUE TITLE
Turret lights don't save state

### ISSUE THREAD

**Issue by BlackMoons** [Regalis11/Barotrauma#13024] opened 2023-11-14 15:12 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Turret lights don't save state. If you toggle 'is on' in the editor, save, then load your save they are turned on again. Also searchlights. 

### Reproduction steps

Place a turret, ie coilgun, toggle 'is on' to off for its light component. 

Save sub. Reload sub. Observe 'is on' is now on again.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-11-14 15:58
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10704

**Closed by Regalis11** 2023-11-14 15:58 UTC
