### ISSUE TITLE
TextBox might crash editor

### ISSUE THREAD

**Issue by Konfuz** [Regalis11/Barotrauma#6005] opened 2021-06-09 14:10 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Encountered an Editor crash, see stacktrace below. I was using several mods had a larger submarine loaded and at the time the bug occured I was changing the direction of a thruster.   

**Steps To Reproduce**
First get a consenting person of the opposite gender... I havent been able to reproduce so far, will update you if so. 

**Version**
Linux  64 Bit
0.13.3.11

**Additional information**
```
Exception: Index and length must refer to a location within the string. (Parameter 'length') (System.ArgumentOutOfRangeException)
Target site: System.String Substring(Int32, Int32)
Stack trace: 
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Barotrauma.GUITextBox.CalculateSelection() in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GUI/GUITextBox.cs:line 881
   at Barotrauma.GUITextBox.Update(Single deltaTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GUI/GUITextBox.cs:line 503
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GUI/GUI.cs:line 1232
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 974
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/SDL/SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 59
   ```
While I cannot say what caused the bug in the first place, I believe that GUITextBox could handle the exception more gracefully and just log a warning instead of ruining my work in the editor since the last save =)

**Comment by Regalis11** [comment] 2021-06-09 14:35
Thank you for the report! We encountered this same crash some time ago and it should now be fixed, but the fix hasn't been publicly released yet (will be included in the next update though). Closing as a duplicate of https://github.com/Regalis11/Barotrauma/issues/5651.

Sorry for the inconvenience!

**Closed by Regalis11** 2021-06-09 14:35 UTC
Labels: Bug, Code, Crash
