### ISSUE TITLE
[Unstable] You can directional ping toward the center of the sub to make passive sonar see stuff around the nav terminal

### ISSUE THREAD

**Issue by GoodDays13** [Regalis11/Barotrauma#10422] opened 2022-11-17 00:50 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

You can ping toward the center of the sub, from the nav terminal to where the sonar tool origin is, which then makes it so the passive sonar sees the nav terminal as making a loud noise. This is kinda partially caused by the idea to make the sound come from the nav terminal instead of where it is centered in the interface.
![image](https://user-images.githubusercontent.com/42877449/202324520-d22dd887-ffa9-4ea4-a384-ac2a4628c17f.png)

### Reproduction steps

quickstart with something like Orca2.
Get the nav terminal near something like a wall.
Find out where the Nav terminal is in comparison to where the sonar origin is.
![image](https://user-images.githubusercontent.com/42877449/202325213-0005f6e6-021c-4f2e-819c-2bb2c867b731.png)
Ping away from the nav terminal so the sound the nav terminal makes goes toward where the sonar detects and then immediately turn off active sonar.
![image](https://user-images.githubusercontent.com/42877449/202325408-71a56b65-d4d1-4184-a5cb-117570be6f1b.png)

### Bug prevalence

Happens every now and then

### Version

0.20.6.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by GoodDays13** [comment] 2022-11-17 00:56
This seems related to #10291. It is kind of the same issue but applies mainly to the sub that is sending out the pings instead. And with the fix for that issue, it made it only happen when pointing at the center.

**Comment by GoodDays13** [comment] 2022-11-20 22:09
I think the fix for this one introduced some weird things, like how because the sound comes from a different place you can see it bounce off the floor in front of you if you do something like this
![image](https://user-images.githubusercontent.com/42877449/202928822-bf8f86de-071a-47a2-b3bd-f27c0afe8a81.png)
![image](https://user-images.githubusercontent.com/42877449/202928827-0be61d7b-8e57-4391-9ca5-134de1cb5880.png)

And I think a subs sonar can bounce off the sub that sent it out making it visible from any direction again
![image](https://user-images.githubusercontent.com/42877449/202928758-68937620-1b93-474d-a124-004b2d675f17.png)
![image](https://user-images.githubusercontent.com/42877449/202928913-f1cb271d-339c-48e3-a86b-9dc61fe43aa0.png)

**Comment by Rokvach** [comment] 2022-11-21 00:03
Moving to Team1

**Comment by Regalis11** [comment] 2022-11-21 10:04
Addressed the 2nd issue in https://github.com/Regalis11/Barotrauma-development/commit/e02dba5a3db3e74e37dcb15c71f87a61d3613aa8 by requiring the sonar to be inside the sector of the directional ping again. Even though I'd argue that's not exactly realistic (the sonar should be able to pic up the reflected sounds even if the directional ping isn't pointing directly at it), I agree that it feels like a bug that you can see the directional pings even if they're pointing at a different direction.

**Comment by GoodDays13** [comment] 2022-11-21 12:53
> I could not reproduce the 1st issue; I suspect there's some other sound that's being reflected in that screenshot.

When I got the pic I made sure to have active turned off for a bit and the blinking faded away. I pinged the directional sonar down and switched to passive. My guess is that because the ai target cone comes from the nav terminal instead of where the sonar is centered it bounces off the area below it that isn't covered by the sonar. But if you changed the way it reveals, it may not be reproduceable anymore.

I still personally believe that either sonar should be moved to the nav terminal or the sound it makes moved to be in sync with the sonar because it not being like that will only cause more problems and confusion in the future.

**Comment by GoodDays13** [comment] 2022-11-22 23:25
Video example of the first issue
https://streamable.com/uj5pbu

**Comment by NilanthAnimosus** [comment] 2022-11-29 09:49
Not sure what to think here, The issue is still present (things visible near the navigation terminal on directional when nothing is emitting sound there other than the navigation terminal itself) but its so weak I am not even sure I consider it much of an issue given it...legitimately is emitting a noise and all that realistically cannot be in one direction only.

https://gyazo.com/f6fc7023b5f7001e0f923bf190699c34

![image](https://user-images.githubusercontent.com/29177976/204494492-b842d340-25cb-4c6b-8bb3-51e68182b849.png)

My reactor reveals more than the nav terminal does, the above video example seems the same with how subtle it is, and it requires you to turn off active sonar (does not appear when its active and directional).

Just to emphasize the green navigation terminal, orange reactor, and red direction of directional sonar. nothing else in the image I think is capable of emitting any sounds either).

Not sure if this means more tweaks/fixing is required, or if its worth fixing further.

**Comment by Regalis11** [comment] 2022-11-29 11:58
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/30724589cb48a4045d7c8721f6dfaa885b6cbe4f

**Comment by Regalis11** [comment] 2022-11-29 13:21
Pushed some further fixes in https://github.com/Regalis11/Barotrauma-development/commit/499bc8badcdb732d6a35e68a037ca99417d8c2f1 (also relates to #10291)

**Closed** 2022-12-07 10:22 UTC
Labels: Bug, Code, Unstable
