### ISSUE TITLE
[EVENT EDITOR][UNSTABLE] Speakertag conversations persist despite end option getting selected

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#5007] opened 2021-02-07 23:25 UTC
**Description**
ToggleEnding doesn't seem to work for speakertag type conversations (the ones where you have to interact with NPC). The conversation stays available even after selecting an option and even after the event moves forward. This is the simplest setup to reproduce it:
![image](https://user-images.githubusercontent.com/59519434/107162365-cc693f00-69a2-11eb-96b4-6f0f7c9ea2d5.png)

Expected behaviour:
1. Spawn NPC with a tag
2. Give it speakertag conversation with 1 option, that has toggleconversationend=true (red rectangle around it)
3. Player selects the option
4. Conversation is done, speakertag disappears, WaitAction happens, END conversation window appears

Observed behaviour:
1. Spawn NPC with a tag
2. Give it speakertag conversation with 1 option, that has toggleconversationend=true (red rectangle around it)
3. Player selects the option
4. Conversation is still available after selecting the option, WaitAction happens, END conversation window appears
Here you can see that I can keep re-interacting with the NPC despite selecting the end option everytime
![eventbug2](https://user-images.githubusercontent.com/59519434/107162578-93ca6500-69a4-11eb-81a4-1de94ce786f8.gif)
**Steps To Reproduce**
Here is event project file with everything vanilla for easy testing
[SpeakertagPersistsBug.zip](https://github.com/Regalis11/Barotrauma/files/5940345/SpeakertagPersistsBug.zip)
1. Load it in event editor
2. Save, agree to test the event in outpost
3. Talk to the NPC
4. After talking to it, see that you can keep talking to it over and over, despite the option being "toggle end"

**Version**
Unstable

**Additional information**
It prevents me from using any speakertag features for the events, which are very useful because they have the ability to use InvokerTag for interacting player.

**Comment by Udrakan** [comment] 2021-03-30 00:43
![image](https://user-images.githubusercontent.com/59519434/112916884-b9046580-9101-11eb-9272-871c62cd4715.png)
maybe this helps

**Comment by 3e849f2e5c** [comment] 2022-02-24 11:56
This seems to have been fixed somewhere along the line, was unable to reproduce in singleplayer and multiplayer with 2 clients

**Comment by Rokvach** [comment] 2022-02-25 10:54
Closing

**Closed by Rokvach** 2022-02-25 10:54 UTC
Labels: Bug, Code
