### ISSUE TITLE
Force open the campaign map, risking the save file becoming unplayable in campaign mode.

### ISSUE THREAD

**Issue by Zirc0n** [Regalis11/Barotrauma#8640] opened 2022-03-28 01:00 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.
(It most likely had been reported before, however not as explicitly, or I am just blind.)

**Description**
Force opens the campaign map, and if fiddled with pumps correctly, can force the save to be unplayable, risking losing it.

**Steps To Reproduce**
https://youtu.be/TgJhKuCYXPU

Short version, rewire both wires from toggle_docking in navigation terminal into current_velocity_x/y pin.

Longer version (to actually break the save file):
The reactor is turned on and the pumps are set to -100 in order to make the sub go always upwards before any navigation input could be done. And whilst yes, one can rewire the horizontal velocity_x into pumps and then set the sub to move backwards for infinite -100 upward effect, or even just manually setting it to go up, it might have more backlashes during actual spawning, as by default the sub is set to autopilot, annulling the effect.

Therefore pump's manual -100, on another hand, would be non-fixable because there is no time to rewire it, the sub will go straight up and dock back. As soon as the server is loaded, the campaign map will appear again straight away, and everything will start over, deeming the save unplayable and risking losing all the progress.

**Version**
0.16.7.0 Latest.
MacOS

**Additional information**
None.

**Comment by Regalis11** [comment] 2022-03-28 07:16
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7772

**Closed by Regalis11** 2022-03-28 07:16 UTC
