### ISSUE TITLE
All oxygen tanks in the Exosuit inventory will lose oxygen when passing through the gas vents in the cave

### ISSUE THREAD

**Issue by AnalogKnight** [Regalis11/Barotrauma#10871] opened 2023-01-04 10:59 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I think this is because the Exosuit is still a "diving suit", but it has inventory compared to other wetsuits.
Oxygen tanks in the player's inventory are not affected when passing through gas vents. But all oxygen tanks in the Exosuit will be deprived of oxygen, even those that are not equipped.

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-01-04 11:00
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10423

**Closed by Regalis11** 2023-01-04 11:00 UTC
