### ISSUE TITLE
Map not showing up 60m from destination (formation)

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5410] opened 2021-04-01 16:25 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Nor the map or the button to enter the formation showed up when i was in the range needed for them to show up, so i simply could not leave that level. The map did show up when i approached the starting location.

**Version**
v.0.1300.0.5 (no hotfix) Windows

**Additional information**
Here's a save in a level where this issue happened.
[the doodoopisser.zip](https://github.com/Regalis11/Barotrauma/files/6244967/the.doodoopisser.zip)

**Comment by ekqvist** [comment] 2021-04-06 14:06
There seems to be an issue with the attached save and the original .save file has already been deleted. LePiromano promised to send another one if they can reproduce the issue again. I'll try to do a few test runs to see if I can reproduce the issue myself.

**Comment by ekqvist** [comment] 2021-04-07 09:05
Can't seem to be able to reproduce the issue. I would guess that there's some sort of an issue with `GetAvailableTransition()` not being able to get the correct `TransitionType` in some very rare cases because the visibility of the end round button and the map rely on that. If there's a save/level where this consistently happens, it would greatly help in diagnosing the issue.

**Comment by Regalis11** [comment] 2021-04-07 12:00
This happened during internal testing with this save file (didn't test if it can be reproduced with the save yet):
[Partikkelihuntti.zip](https://github.com/Regalis11/Barotrauma/files/6271352/Partikkelihuntti.zip)

**Comment by ekqvist** [comment] 2021-04-07 13:26
The issue was that when the game checked for the sub leaving the level, it 1) calculated the distance to the start of the "exit tunnel" instead of the "exit position" and 2) also allowed beacon stations to be the "leaving sub". The first issue should be fixed in Regalis11/Barotrauma-development@5d52402. The second issue should be addressed by requiring the "leaving sub" team ID to match the leaving players' team ID in Regalis11/Barotrauma-development@79913fc.

**Comment by Rokvach** [comment] 2021-04-10 23:25
Tested, working correctly. Closing.

**Closed by Rokvach** 2021-04-10 23:25 UTC
Labels: Bug, Code
