### ISSUE TITLE
Specific headphones crashing all players but the host

### ISSUE THREAD

**Issue by IsakuReplicant832** [Regalis11/Barotrauma#9210] opened 2022-05-26 02:01 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

My friend's headphones are **JBL tune 750btnc**'s and the sound card they don't know, we found out that if the headphones run out of charge and disconnect or disconnects normally in a multiplayer game, everyone will but the host of the game will either disconnect or crash, **this may be an isolated case** as we found that anything relating to messing with audio in Barotrauma will usually cause problems, especially when modded, like microphones & headphones/headsets being unplugged, disconnected, or both. 
_And yes, we did test this with and without mods, with said friend being the host and not._

### Reproduction steps

1. Have JBL tune 750btnc's connected and working in Barotrauma.
2. As host start a multiplayer game with or without mods.
a2. As player join a multiplayer game with players.
4. Have players join, load in, play ect.
(If the game has been going for a few checkpoints that will probably increase the chances of something different going wrong when heavily modded or a combination.)
5. Disconnect or let the charge run out of JBL tune 750btnc's.

### Bug prevalence

Happens regularly

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-05-26 16:34
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7981

**Closed by Regalis11** 2022-05-26 16:34 UTC
