### ISSUE TITLE
Sub Editor Shell Part Depth Not Adjustable

### ISSUE THREAD

**Issue by Kirfkin** [Regalis11/Barotrauma#11758] opened 2023-04-06 00:37 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The issue is purely aesthetic, and therefore minor. It theoretically happens regularly in the sub editor, and has an impact on how I must design the subs aesthetically (but not functionally). I consider this bug minor.

If you place a submarine shell piece which displays the outer most view (e.g. in front of the player, or most prow and stern pieces such as Tail Fin E P1/P2/P3 or Bow G Top/Center/Bottom) then you cannot properly adjust the sprite depth of these pieces. Thus, if any item overlaps one of these offending pieces, you cannot set the sprite depth below 0.501 or else the piece will render in front of (e.g. it is not obscured by the hull piece). It is therefore impossible to have some items nearby these pieces render in front of the characters.

This is especially problematic when attempting to use protective barriers or rails, for example to "secure" an engine. As engines are commonly towards the rear of the submarine, the likelihood of encountering this issue is slightly elevated.

Please see the following images:

1. Default (or similar) sprite depths.
![image](https://user-images.githubusercontent.com/15023742/230242328-99ebded0-21e2-4223-a78d-7f4b8798e3bc.png)
The guard rail renders behind the offending piece, with depth set to 0.550. The fin piece is set to 0.010

2. Same depth, but with a character sprite.
![image](https://user-images.githubusercontent.com/15023742/230242614-fa7bf669-9702-4bf9-a945-4fd7b863840d.png)
The character is standing in front of the guard rail, but behind the shell tail piece.

3. The rail is now set to 0.450, and the shell piece remains at 0.010 for sprite depths.
![image](https://user-images.githubusercontent.com/15023742/230242751-a91cec43-913c-4681-9805-bdcb327fcf8e.png)
The rail renders in front of the tail piece. Were I to bring a character over, the character would render behind both the rail and the tail piece.

The expected behavior is that I could adjust the guard rail to below 0.500 sprite depth and have it render behind the hull piece when the hull piece is set to 0.010 sprite depth.

Note **(Not /directly/ related to the bug, but indirectly related, desired behavior)**: I was experimenting; and it's likely with the platform I would not use this style anyway as if the character were walking on the ground, they would be in front of the platform but behind the rails. It would be great if it were possible to link the items together such that if the character is on the platform they are behind the rail, but otherwise in front of it. I understand that this additional bit is much more complex, and more of a desired behavior and not a bug. It is how I discovered this behavior, though.

### Reproduction steps

1. Open the submarine editor.
2. Place down a hull piece such as such as Tail Fin E P1/P2/P3 or Bow G Top/Center/Bottom.
3. Place down another decorative sprite, such as "Protective Barrier" where the sprites partially overlap.
4. Change the hull piece depth to anything, or leave it at 0.010. It does not matter.
5. Change the other sprite to have a sprite depth of 0.500 or below.
6. Note that the decorative sprite will render in front of the hull piece.

### Bug prevalence

Happens regularly

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-04-06 06:55
Duplicate of https://github.com/Regalis11/Barotrauma/issues/8061

**Closed by Regalis11** 2023-04-06 06:55 UTC

**Comment by Kirfkin** [comment] 2023-04-07 01:50
Apologies, I didn't see that one in my search.
