### ISSUE TITLE
Drone won't rise on ladder

### ISSUE THREAD

**Issue by MrPokk** [Regalis11/Barotrauma#12231] opened 2023-06-26 15:11 UTC
### Disclaimers

- [ ] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The lack of ability to use a protective drone to move along stairs makes it difficult to play

P.s:Can't climb vertical stairs

### Reproduction steps

1.Start game test
2.Spaw drone
3.Play with the drone
4.You drop down the stairs

### Bug prevalence

Happens every time I play

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-06-27 06:44
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11793

**Closed by Regalis11** 2023-06-27 06:44 UTC
