### ISSUE TITLE
Game crashed when unchecking sandbox from server browser

### ISSUE THREAD

**Issue by menker186** [Regalis11/Barotrauma#2728] opened 2020-04-28 01:12 UTC
game crashed when i was in server browser and unchecked 'sandbox', i run the game fine but i had a few mods enabled (only subs)

Barotrauma Client crash report (generated on 4/27/2020 9:08:09 PM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

B88397013C2378C4A99C3E19DEBEE54F

Game version 0.9.9.0 (ReleaseWindows, branch release, revision 0534150c8)
Graphics mode: 1600x900 (Fullscreen)
VSync OFF
Selected content packages: Vanilla 0.9, Atolla, Cyclops Mk-II, Mining Station A, Research Station A, RUSALKA 1, Ulysses, [EMS] Prometheus Station
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.ServerListScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.18362.0 64 bit
    GPU name: Intel(R) HD Graphics
    Display mode: {Width:1440 Height:900 Format:Color AspectRatio:1.6}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void FilterServers()
Stack trace: 
   at Barotrauma.ServerListScreen.FilterServers()
   at Barotrauma.ServerListScreen.<>c__DisplayClass70_0.<CreateUI>b__26(GUITickBox tickBox)
   at Barotrauma.GUITickBox.set_Selected(Boolean value)
   at Barotrauma.GUITickBox.Update(Single deltaTime)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime)
   at Barotrauma.GameMain.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Barotrauma.Program.Main(String[] args)

Last debug messages:
[4/27/2020 9:07:40 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[4/27/2020 9:07:40 PM] Content package load order: Vanilla 0.9  |  Atolla  |  Cyclops Mk-II  |  Mining Station A  |  Research Station A  |  RUSALKA 1  |  Ulysses  |  [EMS] Prometheus Station
[4/27/2020 9:07:39 PM] Content package load order: Vanilla 0.9  |  Atolla  |  Cyclops Mk-II  |  Mining Station A  |  Research Station A  |  RUSALKA 1  |  Ulysses  |  [EMS] Prometheus Station
[4/27/2020 9:07:35 PM] Attempting to open ALC device "OpenAL Soft"
[4/27/2020 9:07:34 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[4/27/2020 9:07:33 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[4/27/2020 9:07:32 PM] Logged in as menkire (SteamID STEAM_1:1:70114095)

**Comment by ekqvist** [comment] 2020-04-28 07:47
Duplicate of #2677

**Closed by ekqvist** 2020-04-28 07:47 UTC
