### ISSUE TITLE
Searchlight - mispositioning of the light source

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#7598] opened 2021-12-03 20:51 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
1. Wrong offset of the light on the Y-axis.
2. Offset of the light when "Range" is modified.

**Steps To Reproduce**
![Image 001_22-57 (1) (1)](https://user-images.githubusercontent.com/93348499/144669959-ebc14b54-ce21-4839-a428-f52bc654e03a.png)

**Version**
v0.15.13.0, Vanilla 0.9 (Windows 10-x64).

**Additional information**
v0.15.22.1, Vanilla 0.9 (Windows 10-x64).
![Image 001_15-41](https://user-images.githubusercontent.com/93348499/147886093-fec3d57b-b17a-4865-b467-a6a80f2cca83.png)

**Comment by Regalis11** [comment] 2022-07-01 08:23
Could no longer reproduce most of these in the latest version.

The only issue that still seems to remain is the "wrong offset of the light on the Y-axis". I wouldn't actually even consider that a bug: the light is not offset, it's just that the gradient at the beginning of the "light cone" becomes more noticeable when the range of the light is increased.

**Comment by MaaiG** [comment] 2022-07-01 10:20
Okay, thanks a lot!

**Comment by NilanthAnimosus** [comment] 2022-07-28 01:34
Tested in 0.19.0.0, works correctly, closing.

Notes: I am unable to reproduce any of the issues with the light source itself (Other than the gradient when the range is very large, though that is capped to 2048 by default)

I have noticed when you use "mirror Y" you slightly offset the graphic and light source (so they are not centered on the stand when facing up/down only) of the spotlight compared to the fixture but the light is coming from the lens/light emitting part in the correct position relative to the spotlight's minor offset from the fixture/stand.

**Closed by NilanthAnimosus** 2022-07-28 01:34 UTC
Labels: Bug, Code, Low prio, Unstable
