### ISSUE TITLE
Crash Mid-Game (Failed to set muffled buffer data for non-streamed audio)

### ISSUE THREAD

**Issue by Dathomerian554** [Regalis11/Barotrauma#12717] opened 2023-09-25 07:36 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This issue seems similar to #9581, but the crash report is different ("Regular buffer" compared to "Muffled buffer").  Anyway, I was fighting some good old fractal guardians, and the game suddenly crashed (I can't recall whether I had yet killed them or if I had already finished).  

### Reproduction steps

1. Open Barotrauama
2. Start Game
3. Steer Ship
4. Fight Monsters
5. Game Crash

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

Unstable (v1.1.14.0)

### Which operating system did you encounter this bug on?

MacOS

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 09/25/2023 01:06:21)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

0772CE4E771BF74EE37FE88949569EB4

Game version 1.1.14.0 (ReleaseMac, branch release/traitor-update, revision 34847c2916)
Graphics mode: 1440x900 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla (01A97A9)
Level seed: The Eye of Europa57
Loaded submarine: Kastrull (5A0F58FFA2C21C1FBFF8C80B87371C79)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Unix 13.5.2 64 bit
    GPU name: 
    Display mode: {Width:1440 Height:900 Format:Color AspectRatio:1.6}
    GPU status: Normal

Exception: Failed to set muffled buffer data for non-streamed audio! Invalid operation (System.Exception)
Target site: Void FillAlBuffers()
Stack trace: 
   at Barotrauma.Sounds.OggSound.FillAlBuffers() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sounds\OggSound.cs:line 156
   at Barotrauma.Sounds.SoundChannel..ctor(Sound sound, Single gain, Nullable`1 position, Single freqMult, Single near, Single far, String category, Boolean muffle) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sounds\SoundChannel.cs:line 505
   at Barotrauma.Sounds.Sound.Play(Single gain, Single range, Single freqMult, Vector2 position, Boolean muffle) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sounds\Sound.cs:line 94
   at Barotrauma.SoundPlayer.PlaySound(Sound sound, Vector2 position, Nullable`1 volume, Nullable`1 range, Nullable`1 freqMult, Hull hullGuess, Boolean ignoreMuffling) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sounds\SoundPlayer.cs:line 503
   at Barotrauma.Character.PlaySound(SoundType soundType, Single soundIntervalFactor, Single maxInterval) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\Character.cs:line 1132
   at Barotrauma.Character.UpdateProjSpecific(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\Character.cs:line 713
   at Barotrauma.Character.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 3105
   at Barotrauma.AICharacter.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AICharacter.cs:line 76
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 3097
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 185
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 851
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[09/25/2023 00:36:39] Generating an outpost for the start of the level... (Location: The Eye of Europa, level type: Outpost)
[09/25/2023 00:36:39] Level identifier: endlocationoutpost
[09/24/2023 23:49:06] Generating an outpost for the start of the level... (Location: The Eye of Europa, level type: Outpost)
[09/24/2023 23:49:06] Level identifier: endlocationoutpost
[09/24/2023 23:48:31] Transitioning to The Eye of Europa57 (current location: Castalia Macula, selected location: The Eye of Europa, leaving sub: Kastrull, at start: False, at end: True, transition type: ProgressToNextLocation)
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:29] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:28] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:27] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:27] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:27] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:27] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:27] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:27] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:27] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:27] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:27] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:27] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:27] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:27] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:27] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:27] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:27] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:27] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:27] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:27] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:27] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:27] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:27] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:27] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:27] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:27] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:27] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:27] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:27] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:27] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:27] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:27] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:27] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:27] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:27] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:27] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:27] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:27] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:27] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:27] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:27] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:27] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:27] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:27] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:27] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:27] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:26] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:25] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:24] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:24] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:24] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:24] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:24] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:24] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:24] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:24] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:24] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:24] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:24] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:24] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:24] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:24] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:24] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:24] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:24] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:24] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:24] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:24] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:24] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:24] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:24] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:24] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:24] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:24] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:24] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:24] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:24] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:24] Error with a Return objective: no suitable return target found
[09/24/2023 18:14:24] Error with a Return objective: no suitable return target found
```

**Comment by Regalis11** [comment] 2023-09-25 08:18
Closing as a duplicate of https://github.com/Regalis11/Barotrauma/issues/9581 (seems to be the same underlying issue, even though the sound in this case was muffled)

**Closed by Regalis11** 2023-09-25 08:18 UTC
