### ISSUE TITLE
[0.9.1001.0] Bots restart reactor to on a few moments after ordered to turn it off.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2854] opened 2020-05-17 18:09 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots restart reactor to on a few moments after ordered to turn it off.

**Version**
0.9.1001.0

**Comment by Regalis11** [comment] 2020-05-17 18:17
Duplicate of #2825

**Closed by Regalis11** 2020-05-17 18:17 UTC
