### ISSUE TITLE
Consistant steamp2p disconnects after undocking

### ISSUE THREAD

**Issue by Ataxio** [Regalis11/Barotrauma#8925] opened 2022-04-23 01:21 UTC
Screen captures of the log output.

[1]https://steamuserimages-a.akamaihd.net/ugc/1852677807208908535/86D293C2B1A28BAE6884509D335DDB81351D1B82/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false](steam://openurl/https://steamuserimages-a.akamaihd.net/ugc/1852677807208908535/86D293C2B1A28BAE6884509D335DDB81351D1B82/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false

[2](https://steamuserimages-a.akamaihd.net/ugc/1852677807208909298/14E56442FE58A99EFA682CC601FD647D750B42B3/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false](steam://openurl/https://steamuserimages-a.akamaihd.net/ugc/1852677807208909298/14E56442FE58A99EFA682CC601FD647D750B42B3/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false)

This happens each time we undock, and most times when docking but not always. Only clients are kicked but the host always remains. It seems to be induced by longer term game play & having a ton of items on board. We are not running any mods beyond the modded sub i've created. It's not very complex, but I highly suspect this bug is induced by having many items. The linked container on our fabricator is nearly full of storage boxes which are also nearly full. Same thing with our medical fab.

The bug slowly seems to creep in and appear after putting maybe 20 hours into a save & accumulating more and more stuff. Prior to that we are able to dock & undock normally and I never get kicked. The moment we started really hoarding is when it seems to have appeared. We experienced the same issue on our previous play through of the game about a year ago.

**Comment by Regalis11** [comment] 2022-04-23 08:33
Duplicate of https://github.com/regalis11/barotrauma/issues/8899

**Closed by Regalis11** 2022-04-23 08:33 UTC
