### ISSUE TITLE
Items deleting randomly in sub editor.

### ISSUE THREAD

**Issue by ARTANIS8000** [Regalis11/Barotrauma#12469] opened 2023-08-04 19:37 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When deleting items in the sub editor, there have been a few times where another item gets deleted randomly. This seems to happen mainly to inside walls and shell pieces but it happens often enough to other small items that it can become a common nuisance when creating a sub. I have not been able to replicate this bug consistently, but it happens more often when deleting groups of items.

### Reproduction steps

1. Open Sub Editor
2. Delete items in editor
3. Watch a random item disappear

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Other

### -

Sub Editor

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by VaelophisNyx** [comment] 2023-08-05 22:24
this is a known issue, one moment

**Comment by VaelophisNyx** [comment] 2023-08-05 22:25
see #11538

**Comment by Regalis11** [comment] 2023-08-06 13:04
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11538

**Closed by Regalis11** 2023-08-06 13:04 UTC
