### ISSUE TITLE
[Feature request] Prevent equipping of handcuffs via quick select l

### ISSUE THREAD

**Issue by OverwatchVoice** [Regalis11/Barotrauma#1879] opened 2019-11-14 13:41 UTC
Prevent handcuffs from being equipped by the 0-9 keys
to prevent accidental self-cuffing that happens way more often than it should.

**Comment by Regalis11** [comment] 2019-11-17 18:50
Duplicate of #1509

**Closed by Regalis11** 2019-11-17 18:50 UTC

**Comment by OverwatchVoice** [comment] 2019-11-18 17:21
Sorry, didn't notice it.
