### ISSUE TITLE
Artifact spawned inside of a rock

### ISSUE THREAD

**Issue by Hauptmann24** [Regalis11/Barotrauma#3414] opened 2020-07-26 06:38 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Artifact spawned inside of a rock

![2020-07-26 01_30_46-Barotrauma](https://user-images.githubusercontent.com/10015869/88473127-10519680-cee0-11ea-8d93-570d0eff18b6.png)

**Steps To Reproduce**
Unknown. First one discovered seems to be an issue with the map gen.

**Version**
Barotrauma v9.10.0 (ReleaseWindows, branch release, revision 2876b0a66)

**Additional information**
It may be a one time issue. Haven't seen the issue in 7 or so Artifact missions. Keep up the good work. Love the game.

**Comment by Regalis11** [comment] 2020-07-27 06:55
Duplicate of #2731

**Closed by Regalis11** 2020-07-27 06:55 UTC
