### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by 2923086610** [Regalis11/Barotrauma#4031] opened 2020-10-08 01:29 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

How can I solve this problem
Barotrauma Client crash report (generated on 2020/10/7 21:02:50)

Barotrauma seems to have crashed. Sorry for the inconvenience!

6F558E05A9FD96EA104348A23A5B582A

Game version 0.10.5.1 (ReleaseWindows, branch release, revision 9e259b2148)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized

System info:
Operating system: Microsoft Windows NT 10.0.16299.0 64 bit
GPU name: NVIDIA GeForce GTX 1050
Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
GPU status: Normal

Exception: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: GPU 设备实例已经暂停。使用 GetDeviceRemovedReason 以确定相应的措施。
(SharpDX.SharpDXException)
Device removed reason: HRESULT = 0x887A0020
Target site: Void CheckError()
Stack trace:
at SharpDX.Result.CheckError()
at SharpDX.DXGI.SwapChain.Present(Int32 syncInterval, PresentFlags flags)
at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 1010
at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Present() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.cs:line 601
at Microsoft.Xna.Framework.SdlGamePlatform.Present() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 245
at Microsoft.Xna.Framework.Game.EndDraw() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 523
at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
at Microsoft.Xna.Framework.Game.Tick() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 511
at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
at Microsoft.Xna.Framework.Game.Run() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
at Barotrauma.Program.Main(String[] args) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59

Last debug messages:
[2020/10/7 21:02:50] Attempting to open ALC device "OpenAL Soft on 扬声器 (Realtek High Definition Audio)"
[2020/10/7 21:02:49] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[2020/10/7 21:02:48] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[2020/10/7 21:02:48] Logged in as 2923086610 (SteamID STEAM_1:1:567967535

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**

**Comment by 2923086610** [comment] 2020-10-08 01:40
[Uploading crashreport (15).log…]()

**Comment by Regalis11** [comment] 2020-10-08 08:41
Duplicate of https://github.com/Regalis11/Barotrauma/issues/1833.

I'm afraid we still haven't managed to find a reliable way to fix this. Does it happen every time you launch the game or just occasionally? What kind of a GPU do you have? Are your graphics drivers up to date?

**Closed by Regalis11** 2020-10-08 08:41 UTC

**Comment by 2923086610** [comment] 2020-10-08 09:05
My GPU is gtx1050
My graphics driver is up to date
I can't get into the game at all, because the game will collapse when I open it
