### ISSUE TITLE
[status monitor] [unstable] item finder offset thing whens witching from unlinked to linked view

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6670] opened 2021-09-17 19:44 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
item ping positions aren't updated when switching between linked and unlinked view of status monitor or vice versa

![image](https://user-images.githubusercontent.com/5103517/133844317-0172f94f-3371-4967-bb76-d12dc2324881.png)

**Steps To Reproduce**
1. open unlinked status monitor
2. search for an item
3. close status monitor
4. open linked view w/ nav terminal
5. items pings are offset

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**

**Comment by Regalis11** [comment] 2021-09-18 10:59
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9434a575eed0cc6228f43b6ce1f41108fe88755a

**Comment by Lithosagym** [comment] 2021-10-05 04:32
Tested, confirmed fixed (It's not actively updating, so you just need to search again for accurate locations.)

**Comment by Rokvach** [comment] 2021-10-05 07:26
Closing.

**Closed by Rokvach** 2021-10-05 07:26 UTC
Labels: Bug, Code

**Comment by Wheatley1001** [comment] 2023-01-29 22:42
Unsure if the cause is the same, but this issue has resurfaced in 100.17.0.0. When searching for the Red Wire item on the item finder, the pings showed two locations outside of the submarine. The items were on the submarine in reality, the pings were simply offset for some reason. I am unsure what caused this issue in 100.17.0.0.

![image](https://user-images.githubusercontent.com/105495756/215355648-0b120a7a-5356-488b-b8ad-9f1f673631b6.png)
