### ISSUE TITLE
No light-emitting texture appears on the open lamp as it should

### ISSUE THREAD

**Issue by RobotV1** [Regalis11/Barotrauma#11154] opened 2023-02-04 18:06 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In the previous version, the lights that were turned on had glowing textures on them and its looked like the color of the body of the lamp turned into the color of the light. But now(v0.21.6.0), the body of the lamp never changes its color, even if the lamp has been turned on.

This diagram shows the changes between the previous version and now of the emergency lamp. The blue emergency lamps in the picture are all turned on. Note that all lamps have the problem, even the lamps on mechanical devices are no exception.
![light_texture](https://user-images.githubusercontent.com/20885536/216782319-5cc1b6b2-8e4c-4a58-a8b1-df54e352fe58.png)

### Reproduction steps

Observe any open lamp in game. Especially obvious for lights that are not white.

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by EugeneKzxc** [comment] 2023-02-05 00:21
light component on switch doesnt work correctly.
Lamp which needs power can toggle on without power wire while it connected to oscillator with square signal.

![2023-02-05_03-16-42](https://user-images.githubusercontent.com/75340409/216795183-1e44a442-9cc9-4652-b6d7-8c31a9915628.png)
![2023-02-05_03-15-03](https://user-images.githubusercontent.com/75340409/216795184-05105612-23fa-463a-990d-3765b9a92fc9.png)
![2023-02-05_03-07-17](https://user-images.githubusercontent.com/75340409/216795185-6de7e0e7-9b0b-4076-ae92-a6b4aaf91559.png)
![2023-02-05_03-06-57](https://user-images.githubusercontent.com/75340409/216795186-a23ae2a8-ac52-4821-bfa6-6a56348feb32.png)

**Comment by Regalis11** [comment] 2023-02-05 10:33
Thank you for the report!

This is most likely caused by the same issue as https://github.com/Regalis11/Barotrauma/issues/11108. I unfortunately couldn't get this to happen though (or might be misunderstanding the issue somehow). I placed two blue emergency lights in the sub and they seem to be working correctly:
![image](https://user-images.githubusercontent.com/14351070/216813716-4260f022-be95-409a-9829-725b6d47db64.png)

I assume you have done some kind of modifications to the settings of the light? + Is lighting actually enabled in that pic on the right? To me it looks like it's not, in which case the light wouldn't be visible.

**Comment by EugeneKzxc** [comment] 2023-02-05 14:02
I have not been able to replicate this problem on standard submarines. For some reason, the problem only appears on my own submarine on all light components. I tried to copy one of the light components from humpback and it works correctly only outside of my submarine, but if you place it inside, its texture stops glowing, although the light around it remains. The test was conducted without mods and any third-party settings.

**Comment by RobotV1** [comment] 2023-02-06 16:06
> Thank you for the report!
> 
> This is most likely caused by the same issue as #11108. I unfortunately couldn't get this to happen though (or might be misunderstanding the issue somehow). I placed two blue emergency lights in the sub and they seem to be working correctly: ![image](https://user-images.githubusercontent.com/14351070/216813716-4260f022-be95-409a-9829-725b6d47db64.png)
> 
> I assume you have done some kind of modifications to the settings of the light? + Is lighting actually enabled in that pic on the right? To me it looks like it's not, in which case the light wouldn't be visible.

The situation in the picture looks like the light from the lamp illuminates itself, making it look like the texture has changed. If the emergency lamp is adjusted to a range close to 0, or if a strong light source is placed near it (e.g. RGBA = 255, 255, 255, 255), the phenomenon I have described will be clearly observed.

**Comment by RobotV1** [comment] 2023-02-06 16:16
This issue has little to no effect on the standard submarine, but it can significantly affect the indicator and decorative lights in some player designs - which often rely entirely on their texture changes to distinguish between being turned on and off.

**Comment by Rokvach** [comment] 2023-02-09 13:08
Tested, working correctly. Closing.

**Closed by Rokvach** 2023-02-09 13:08 UTC
Labels: Bug, Code

**Comment by Ek-Videogames** [comment] 2023-02-10 20:12
> This issue has little to no effect on the standard submarine, but it can significantly affect the indicator and decorative lights in some player designs - which often rely entirely on their texture changes to distinguish between being turned on and off.

IIRC the dugong uses colored light components for it's battery charging system, which requires distinguishing color as opposed to an 'on/off' state.
