### ISSUE TITLE
[Crash] Crashing trying to adjust values in Signal Component in Sub Editor.

### ISSUE THREAD

**Issue by nessinby** [Regalis11/Barotrauma#9657] opened 2022-07-29 01:37 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://user-images.githubusercontent.com/4097846/181663857-360d4b7e-81c7-4344-8d29-45c1aa85577d.png)

Crashing trying to adjust values in Signal Component in Sub Editor.

Adding a Target Signal of 1 (unsure if it's other values) to the Signal Check Component section of multiple Signal Check Component causes the game to crash upon either hitting enter or clicking off of the component to confirm the operation.

I had been getting this bug every time, up until I clicked the component, clicked the box, unclicked the component, and then typed it in in an attempt to replicate the issue. Now it's not happening.

Happened while modifying multiple components, and pretty sure it happened before with a single component as well. 

The component is fresh, although I spent some time wiring it up prior to attempting to modify it's values.

Also happened a few times earlier today and the past few days as well, while modifying components in general. Although less consistently.

### Reproduction steps

1. Start the game
2. Load into the sub editor
3. Load into a sub or outpost
4. Place down multiple Signal Check Components
6. Select said Signal Check Components all at once
7. Go to the Signal Check Component category of the Signal Check Component's properties, and click on the Target Signal field
8. Type in a number
9. Confirm the dialog either by clicking off of the component, or pressing Enter.
10. Crash.

### Bug prevalence

Happens every time I play

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 7/28/2022 9:23:00 PM)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


A3E1BD9914304826B1774DE813786E1D


Game version 0.18.15.0 (ReleaseWindows, branch release, revision a7b22109e9)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla, Halcyon-Cruiser_A1, Halcyon-Cruiser_A2, Halcyon-Cruiser_A3, Halcyon-Cruiser_A4, Halcyon-Cruiser_A5, Halcyon-Cruiser_A6_Expera, Halcyon-Cruiser_A6_LOut-B, Halcyon-Cruiser_A7, Halcyon-Cruiser_A8, AutoDoorImproved, BotanyWindow, Bunk Room Smol, Bunk With Drawers, Deco_Hang, Deco_PowerCables, Doors with Bildge Override, Diving Suits x3 Wired, Diving Suits x4 Wired, EssentalSupplies, Halcyon-Cruiser_A8Experamental, Looping Pulse Repeater, Motion Detector Door, Quick n simple Battery Setup, Velocity Based Recharging Electrical System, TestingBed, Suit_Glowy, FullyAutomatic Airlock Doors, Halcyon-Cruiser_A9
Level seed: no level loaded
Loaded submarine: TestingBed (07BDB158616291AFEC4927D565251CF3)
Selected screen: Barotrauma.SubEditorScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce RTX 3070
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: Type provided must be an Enum. (Parameter 'enumType') (System.ArgumentException)
Target site: System.RuntimeType ValidateRuntimeType(System.Type)
Stack trace: 
   at System.Enum.ValidateRuntimeType(Type enumType)
   at System.Enum.TryParse(Type enumType, String value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at Barotrauma.SerializableEntityEditor.MultiSetProperties(SerializableProperty property, Object parentObject, Object value) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Serialization\SerializableEntityEditor.cs:line 1451
   at Barotrauma.SerializableEntityEditor.SetPropertyValue(SerializableProperty property, Object entity, Object value) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Serialization\SerializableEntityEditor.cs:line 1351
   at Barotrauma.SerializableEntityEditor.<>c__DisplayClass29_0.<CreateStringField>g__OnApply|3(GUITextBox textBox) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Serialization\SerializableEntityEditor.cs:line 707
   at Barotrauma.SerializableEntityEditor.<>c__DisplayClass29_0.<CreateStringField>b__1(GUITextBox textBox, Keys keys) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Serialization\SerializableEntityEditor.cs:line 691
   at Barotrauma.GUITextBox.Deselect() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBox.cs:line 385
   at Barotrauma.GUITextBox.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBox.cs:line 477
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1229
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 898
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59


Last debug messages:
[7/28/2022 9:22:26 PM] Attempting to open ALC device "OpenAL Soft on Headset Earphone (HyperX Virtual Surround Sound)"
[7/28/2022 9:22:24 PM] Logged in as Nessy (SteamID STEAM_1:1:30891041)
```

**Comment by nessinby** [comment] 2022-07-29 01:42
Edit: It definitely happens while modifying a single component. Seems to crash most consistently when you re-select a different component.

**Comment by pakvg85** [comment] 2022-07-29 07:27
There are already created several issues about this crash. I do not quite understand why the devs still have not rolled out the bugfix for this. In general, why do bugfixes are rolled so rarely?
Btw, the fix itself is one line of code.
![изображение](https://user-images.githubusercontent.com/45126308/181707037-b914df02-03d8-4470-90a6-9a19d57537c7.png)

**Comment by MaaiG** [comment] 2022-07-29 10:41
> why do bugfixes are rolled so rarely?

Apparently, the game is focused on the network component and the so-called "stable release" provides the most stable joint game. In particular, this bug is a bug of submarine editor and interferes only with those who play submarine editor.
_Зависит от того какую версию игры вы используете. Так называемая "стабильная версия" больше "распространена") Очевидно, в стиме есть доступ к нестабильной ветке, - похоже в ней [ошибка исправлена](https://github.com/Regalis11/Barotrauma/issues/9629#issuecomment-1197987758)._

**Comment by juanjp600** [comment] 2022-08-03 19:16
Duplicate of #9512, fix is in our QA pipeline

**Closed by juanjp600** 2022-08-03 19:16 UTC
