### ISSUE TITLE
Crew lost when continuing multiplayer campaign

### ISSUE THREAD

**Issue by Radivarig** [Regalis11/Barotrauma#3644] opened 2020-08-26 21:26 UTC
**Description**
I'm playing a multiplayer with 1 more person, we hire a crew, play few quests, pump their levels and go offline. When we return, sometimes they just disappear.

**Steps To Reproduce**
Not sure.. play multiplayer then disconnect and try to reconnect.

**Version**
On steam options: current content build "5351048"

**Comment by Regalis11** [comment] 2020-08-27 13:12
Most likely a duplicate of #3614

**Closed by Regalis11** 2020-08-27 13:12 UTC
Labels: Bug, Code, Networking
