### ISSUE TITLE
Barotrauma crashes on launch or at random

### ISSUE THREAD

**Issue by Jazzdogg** [Regalis11/Barotrauma#2478] opened 2020-03-21 08:28 UTC
**Description**
Hi there. I've just bought Barotrauma but it keeps crashing at launch or if I skip the videos quickly, I can play for awhile and then it randomly crashes.

**Steps To Reproduce**
It randomly crashes

**Version**
Log posted below contains that info.

**Additional information**
Barotrauma Client crash report (generated on 21/03/2020 7:21:28 PM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

30C54684AA148E0CE8B2F75522B1FE39

Game version 0.9.7.1 (ReleaseWindows, branch release, revision 6ec75fa2a)
Graphics mode: 1920x1080 (Fullscreen)
VSync ON
Selected content packages: Vanilla 0.9
Level seed: nLoZLLtza
Loaded submarine: Dugong_Tutorial (E327F30A352B4F0D1A97A7F95059767F)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 6.2.9200.0 64 bit
    GPU name: AMD Radeon RX 5700 XT
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.
 (SharpDX.SharpDXException)
Device removed reason: HRESULT = 0x887A0007
Target site: Void CheckError()
Stack trace: 
   at SharpDX.Result.CheckError()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 1017
   at Microsoft.Xna.Framework.Game.Tick() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 511
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 42

Last debug messages:
[21/03/2020 7:17:46 PM] OpenAL Soft on Internal Digital Microphone (Apple Audio Device) 63
[21/03/2020 7:17:46 PM] OpenAL Soft on Headset Microphone (Apple Audio Device) 54
[21/03/2020 7:17:27 PM] OpenAL Soft on Internal Digital Microphone (Apple Audio Device) 63
[21/03/2020 7:17:27 PM] OpenAL Soft on Headset Microphone (Apple Audio Device) 54
[21/03/2020 7:17:18 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[21/03/2020 7:17:18 PM] Content package load order: Vanilla 0.9
[21/03/2020 7:17:16 PM] Attempting to open ALC device "OpenAL Soft"
[21/03/2020 7:17:16 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[21/03/2020 7:17:15 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[21/03/2020 7:17:15 PM] Logged in as Jazzdogg (SteamID STEAM_1:0:20836421)

**Comment by Jazzdogg** [comment] 2020-03-21 08:31
Not sure if its important info - I am playing on an eGPU setup.

**Comment by Regalis11** [comment] 2020-03-21 09:42
Duplicate of #1833

**Closed by Regalis11** 2020-03-21 09:42 UTC
