### ISSUE TITLE
Remora, despite being a deep diver, cannot dive through the weakest of upwards currents

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#5454] opened 2021-04-07 16:26 UTC
**Description**
Same save as #5452 #5453
[BigIron2.zip](https://github.com/Regalis11/Barotrauma/files/6273080/BigIron2.zip)
Remora, and as I've heard but not tested Kastrull [(Undertow Discord link)](https://discord.com/channels/103209684680323072/668819422919524352/829379888003809341) cannot overcome the weakest form of upwards pushing current, making player wait for long periods or flood parts of his own submarine, which feels annoying after purchasing the last tier of submarine and on top of that being called a deep diver, yet not being able to dive through these, while they could overcome the currents with other submarines, even Dugong.

**Steps To Reproduce**
-load the save
-try to overcome a weak current

**Version**
Unstable

**Additional information**
Related problem with the new respawning mechanic is that the weak shuttles like hemulen get completely out of control and carried away far due to the currents.

**Comment by Regalis11** [comment] 2021-04-08 07:24
Duplicate of https://github.com/Regalis11/Barotrauma/issues/4602

**Closed by Regalis11** 2021-04-08 07:24 UTC
