### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by Melolatius** [Regalis11/Barotrauma#2794] opened 2020-05-08 22:11 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I repaired a pump and out of the sudden, I crashed

**Steps To Reproduce**
-/-

**Version**
Windows 10
![grafik](https://user-images.githubusercontent.com/63376072/81453379-b4515e80-9189-11ea-9c74-c8f3198dd5ec.png)

**Additional information**
[crashreport (25).log](https://github.com/Regalis11/Barotrauma/files/4601948/crashreport.25.log)
[crashreport (24).log](https://github.com/Regalis11/Barotrauma/files/4601949/crashreport.24.log)

**Comment by Regalis11** [comment] 2020-05-09 17:21
Duplicate of #2699

**Closed by Regalis11** 2020-05-09 17:21 UTC
Labels: Bug, Code, Crash
