### ISSUE TITLE
Crash reports

### ISSUE THREAD

**Issue by Terrymeowish** [Regalis11/Barotrauma#8734] opened 2022-04-05 20:57 UTC
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Tonight me and 1 of our friends got disconnected from our game with a crash report, our 2 other friends (one of them is the host) did not. It happened again later in the night where another one of our friends also disconnected, the host still did not.

**Version**
v0.16.7.0 Windows 10home (friends) and Windows 11home (me)

**Additional information**
Added both crash reports below in attachments.
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/8421772/crashreport.2.log)
[crashreport (3).log](https://github.com/Regalis11/Barotrauma/files/8421774/crashreport.3.log)

**Comment by Regalis11** [comment] 2022-04-06 07:39
Duplicate of https://github.com/Regalis11/Barotrauma/issues/6445 and https://github.com/Regalis11/Barotrauma/issues/7973

**Closed by Regalis11** 2022-04-06 07:39 UTC
Labels: Bug, Code, Crash
