### ISSUE TITLE
UI starts flickering in multiplayer when you fall unconscious

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#7362] opened 2021-11-18 10:32 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I remember that we have already once fixed this previously, but if you get stunned by a security guard in this case they used a stun baton your inventory + portrait + report buttons starts to flicker

**Steps To Reproduce**
Have a security guard as part of your crew and attack one of your crew members so the security guard aggroes on you and starts beating you with a stun baton. I think this should be able to be tested with outpost guards as well.

**Version**
0.15.15.0
Branch: dev
Build: Release
Commit: https://github.com/Regalis11/Barotrauma-development/commit/743f92a76bb5cf5ed1fae5d7b9c2f11a5a44eaab

**Additional information**
none

**Comment by Regalis11** [comment] 2022-04-20 17:25
Duplicate of https://github.com/regalis11/barotrauma/issues/8808

**Closed by Regalis11** 2022-04-20 17:25 UTC
Labels: Bug, Code
