### ISSUE TITLE
Sonar Beacon names get reset during level transitions

### ISSUE THREAD

**Issue by Blartibus** [Regalis11/Barotrauma#6129] opened 2021-06-20 16:12 UTC
This issue has existed for a long time now, and I figured it was about time to get it patched.

How this bug works is, if you have a renamed sonar beacon in a player's inventory when you go through a level transition, the beacon's name will always reset to "Sonar Beacon" at the start of the next round, no matter what it was named before. This does not appear to happen if the beacon is inside of a container when the sub goes through the level transition. 

In the "Thunder Under the Ice" update, the default names for sonar beacons were changed to be "1", but even that will revert to the name "Sonar Beacon" if they are carried through the level transition. 

 This bug has been around for as long as I've played Barotrauma (around 1 year), but it still persists in v0.14.6.0. 

I'm running Windows 8, and have witnessed the bug in singleplayer, and I've also observed it in campaigns hosted by a machine running Windows 10.

I'd appreciate it if y'all could patch this. I've been renaming my sonar beacon at the start of every level for several months, now, and it's been pretty tedious. 
Thanks!

**Comment by Regalis11** [comment] 2021-07-05 11:02
Thank you for the report! 

I'm afraid I could not reproduce the issue:
Here's a sonar beacon in the character's inventory during the first round, and it shows "Sonar Beacon" as the name as opposed to "1":
![image](https://user-images.githubusercontent.com/14351070/124461219-07786e80-dd99-11eb-8518-99d61d03b184.png)

I changed it to another value:
![image](https://user-images.githubusercontent.com/14351070/124461266-14955d80-dd99-11eb-8d0d-50ce241acf54.png)

And here's what it looks like when I depart from the outpost:
![image](https://user-images.githubusercontent.com/14351070/124461657-91c0d280-dd99-11eb-870d-4336fbc8020e.png)

Are you using some kind of mods that might modify the beacons somehow?

**Comment by Blartibus** [comment] 2021-07-05 20:21
My bad, apparently it only happens on multiplayer servers. Did a quick host, and after renaming my sonar beacon "Blart" on an outpost, after the level transition, it had reset to the default "Sonar Beacon." 
![20210705151554_1](https://user-images.githubusercontent.com/38506019/124515227-83c47f00-dda4-11eb-9ee7-227ffbee3e42.jpg)
![20210705151618_1](https://user-images.githubusercontent.com/38506019/124515232-8626d900-dda4-11eb-8731-cb028276ab18.jpg)
my mistake, I don't normally keep a sonar beacon on my person in singleplayer.

**Comment by Regalis11** [comment] 2022-02-04 11:39
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f706d03dce4ccd60c32b819227a8a590eb4198a5

**Comment by Rokvach** [comment] 2022-02-07 13:08
Tested, working correctly. Closing.

**Closed by Rokvach** 2022-02-07 13:08 UTC
Labels: Bug, Code, Networking
