### ISSUE TITLE
Game crash when a texture's origin has a negative number

### ISSUE THREAD

**Issue by UzricRash** [Regalis11/Barotrauma#6012] opened 2021-06-10 07:13 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Crash to dekstop when a modded item with a texture's `origin` has a negative number in the serializable vector2.
A better alternative would be to clamp the value and print a console error message.

**Steps To Reproduce**
1. Create a new item with a sprite or any other component that loads a texture.
2. Set the texture origin to -1.0,-1.0.
3. Crash to desktop as soon as the mod is loaded.

**Version**
Windows 0.13.3.11.

**Additional information**
I assume the error would be here:
https://github.com/Regalis11/Barotrauma/blob/master/Barotrauma/BarotraumaClient/ClientSource/Sprite/Sprite.cs

**Comment by Regalis11** [comment] 2021-06-10 07:36
I'm afraid I could not reproduce this: negative sprite origins seem to be working fine, and in fact some vanilla sprites already use negative origins. I'd suspect this was caused by something else than the origin. Would it be possible to post the crash report here? Thanks and sorry for the inconvenience!

**Comment by UzricRash** [comment] 2021-06-10 08:25
Indeed, you're right. I just tested somewhere else and negative origins work right.
So something else must have been, it just so happened to crash at the same time I modified the origin.

Relevant section of crash log:

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void CalculateLightVertices(System.Collections.Generic.List`1[Microsoft.Xna.Framework.Vector2])
Stack trace: 
   at Barotrauma.Lights.LightSource.CalculateLightVertices(List`1 rayCastHits) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\Lights\LightSource.cs:line 953
   at Barotrauma.Lights.LightSource.DrawLightVolume(SpriteBatch spriteBatch, BasicEffect lightEffect, Matrix transform) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\Lights\LightSource.cs:line 1282
   at Barotrauma.Lights.LightManager.RenderLightMap(GraphicsDevice graphics, SpriteBatch spriteBatch, Camera cam, RenderTarget2D backgroundObstructor) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\Lights\LightManager.cs:line 342
   at Barotrauma.GameScreen.DrawMap(GraphicsDevice graphics, SpriteBatch spriteBatch, Double deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\GameScreen.cs:line 188
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\GameScreen.cs:line 122
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 1026
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58


[Full crashlog](https://pastebin.com/YPWxQqMQ)

**Comment by Regalis11** [comment] 2021-07-08 12:14
Thank you! I still wasn't able to find a way to reproduce this, but I added a null check that should prevent this from crashing the game any longer. https://github.com/Regalis11/Barotrauma-development/commit/7d06226bc2a1d998ad01731a2f9f01b25fae5b1e

**Comment by Rokvach** [comment] 2021-08-02 07:14
No known steps to reproduce, I will keep this open until the end of the Unstable testing period and see if anyone happens to encounter it.

**Comment by Rokvach** [comment] 2021-08-16 19:16
As there's no known steps to reproduce this and no encounters to this issue during the Unstable testing period, I will be closing this ticket. This ticket can be opened again if the issue resurfaces. Closing.

**Closed by Rokvach** 2021-08-16 19:16 UTC
Labels: Bug, Code, Crash, Modding
