### ISSUE TITLE
Crew skills keep being reset

### ISSUE THREAD

**Issue by Sevaaas1** [Regalis11/Barotrauma#7114] opened 2021-11-01 06:57 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In Campaign mode, after completing a round and docking at the Outposts, all of the Crew skills are reset to default levels

**Steps To Reproduce**
In my case, it was like this
1. Be Assistant.
2. Have 2 talents, Clown college and Water Prankster
3. Get Weapons skill up to level 40 crafting Harpoons on the Fabricator
4. Finish the mission, all crew skills will be reset

**Version**
Game Version: v.015.12.0, Windows

**Comment by Regalis11** [comment] 2021-11-01 07:33
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7002

**Closed by Regalis11** 2021-11-01 07:33 UTC
