### ISSUE TITLE
0.1002.0.0 (Unstable): Outposts NPCs That Hate You Don't Attack on Sight

### ISSUE THREAD

**Issue by Jlobblet** [Regalis11/Barotrauma#3038] opened 2020-06-09 17:17 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you enter an outpost with a very negative reputation (-80 to -100), the NPCs aboard don't attack you.

**Steps To Reproduce**
1. Start a new campaign.
2. Get reputation to -80 or below.
3. Undock and redock to the outpost.

**Version**
Version 0.1002.0.0 (Unstable).
Windows 10 version 1903.

**Comment by Rokvach** [comment] 2020-06-09 17:21
Only happens on multiplayer

**Comment by Regalis11** [comment] 2020-06-10 07:44
Could not reproduce. How did you get the reputation below -80? Running the "setlocationreputation" command client-side?

**Comment by Rokvach** [comment] 2020-06-10 07:50
We killed everyone in the outpost, then undocked and came back @Regalis11

**Comment by Regalis11** [comment] 2020-06-14 14:29
I was still unable to reproduce this. Are you sure the reputation was below -80?

**Comment by Regalis11** [comment] 2020-06-14 14:51
There were some issues in the way bots react to damage done by them that should now be fixed:
- Grenades or explosives didn't cause a reputation loss, which should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/c17d949287a09a7c4182da9e0c0a78f7487d8d99
- Poisons didn't cause a reputation loss, fixed in https://github.com/Regalis11/Barotrauma-development/commit/789c442b3f62276bf30e84884f8d8ec03830e053

I wonder if the issue could be that the reputation didn't actually drop low enough, not that the NPCs didn't react to the low reputation?

**Comment by Jlobblet** [comment] 2020-06-14 22:30
The reputation was reported to be -100 on both the end round screen and `DebugDraw`, and tested in multiplayer. I'll try to reproduce this issue again.

**Comment by Jlobblet** [comment] 2020-06-15 16:07
Appears to be fixed on 0.1003.0.0 - was attacked on sight at an outpost with -100 reputation (after leaving the airlock module).

**Comment by Rokvach** [comment] 2020-06-15 16:15
Closing.

**Closed by Rokvach** 2020-06-15 16:15 UTC
Labels: Bug, Code, Need more info, Needs testing, Networking
