### ISSUE TITLE
[0.9.7.1] Infinity electric experience.

### ISSUE THREAD

**Issue by MyNameIsEpic** [Regalis11/Barotrauma#2406] opened 2020-03-08 16:25 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The shuttle navigator is infinitely broken when flooded. Because of what you can repair it endlessly.

Tested on submarine: Typhon.

**Steps To Reproduce**
Just flood shuttle and open/close repairing menu when progress is underway.

**Version**
Windows
Game version: 0.9.7.1 Silky Smooth

**Additional information**
Video: https://www.youtube.com/watch?v=xlPeQT7auqk

**Comment by Regalis11** [comment] 2020-03-09 10:36
Duplicate of #2389

**Closed by Regalis11** 2020-03-09 10:36 UTC
