### ISSUE TITLE
[0.10.3.0] Outpost Guards do not retaliate against Mugger NPC

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3326] opened 2020-07-08 15:24 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Spawned in as a fresh medic and I ran into the mugger event. Muggers missed me and slashed the guards but all the guards do were run away instead. I couldn't punch the muggers.

**Version**
0.10.3.0

**Comment by itchyOwl** [comment] 2020-07-09 08:07
It's intentional that NPCs or bots won't retaliate against each other, because currently we know that when an NPC/bot hits a friendly NPC/bot, it's always accidental. Retaliating on that would easily cause a mayhem.

But I'm not sure how the security should react in this case. @ezjamsen ?

What do you mean that you couldn't punch the muggers? Were you not able to hit them because of the guards were in the way or did the hits miss by some other reason? Accidentally hitting the other NPC's is another design issue that needs addressing (#3134)

Which event was it? I can't find any events with the word "mugger". There's an event with "smugglers" though.

**Comment by danielasteljoki** [comment] 2020-07-09 08:34
@itchyOwl There are events where we spawn hostile NPCs that attack the player (huskcultambush for one). They are the aggressor in that case so outpost security should treat them as such.

**Comment by Kaillera** [comment] 2020-07-09 11:28
I do literally mean punch. We can't retaliate with no actual weapons.

**Comment by itchyOwl** [comment] 2020-07-09 11:46
Oh, ok. Need to make the guards target those then. Though it might be easy to just avoid those guys and let the security handle them.

**Comment by itchyOwl** [comment] 2020-07-09 15:43
Changed in Regalis11/Barotrauma-development@369b718 (dev). Besides security, also witnesses should now react when they see violence. The reactions towards combat actions can be defined in OutpostEvents.xml.

Please say if there's anything weird going on. The logic is now a bit convoluted, so I wouldn't wonder if there were issues caused by the changes.

**Comment by Rokvach** [comment] 2020-07-13 07:26
Working correctly, closing.

**Closed by Rokvach** 2020-07-13 07:26 UTC
Labels: Code, Design
