### ISSUE TITLE
Crash everytime at the same spot

### ISSUE THREAD

**Issue by Vindicatif** [Regalis11/Barotrauma#5257] opened 2021-03-15 21:17 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The game is crashing each time at (more or less) the same spot, between the two locations i'm travelling. The game is not that modded, only two or three subs mod and never had any problem with it.

There i'm putting the crash report that ive got the last time i played.
[crashreport (14).log](https://github.com/Regalis11/Barotrauma/files/6144581/crashreport.14.log)
[crashreport (12).log](https://github.com/Regalis11/Barotrauma/files/6144583/crashreport.12.log)
[crashreport (13).log](https://github.com/Regalis11/Barotrauma/files/6144584/crashreport.13.log)

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
i'm playing on mac os 10.13.6

**Additional information**
don't hesitate to ask me more if you need details, i don't really know what to say.

**Comment by Regalis11** [comment] 2021-03-16 07:38
Duplicate of https://github.com/Regalis11/Barotrauma/issues/4504

**Closed by Regalis11** 2021-03-16 07:38 UTC
