### ISSUE TITLE
Attempting to change name crashes game.

### ISSUE THREAD

**Issue by lukemac58** [Regalis11/Barotrauma#1852] opened 2019-11-03 16:58 UTC
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Launch works fine but whilst on a server attempting to change my name causes a crash.

**Steps To Reproduce**

Launch > Join server > Attempt to change name > crash report + crash

**Version**

Windows, most recent version.

**Additional information**
[BT crash.txt](https://github.com/Regalis11/Barotrauma/files/3801815/BT.crash.txt)

Also attempting to change my name on the server browser causes a crash and crash report too
[BT crash 2.txt](https://github.com/Regalis11/Barotrauma/files/3801833/BT.crash.2.txt)

**Comment by Regalis11** [comment] 2019-11-04 09:46
Are you trying to paste text into the textbox? There's a known issue in the current public version; if you paste or cut text, or use Ctrl+Z to modify the text, the highlighted area on the textbox doesn't get updated, causing a crash if you type in something to the box at that point. The issue will be fixed in the next patch, but for now you may be able to work around the issue by typing in the new name manually.

**Comment by lukemac58** [comment] 2019-11-04 20:44
It appears to just happen manually

**Comment by itchyOwl** [comment] 2019-11-12 15:25
Tested on 0.9.4.0, 0.9.5.0 and the latest dev, as a host and a client, in the lobby and in the server browser. Alas, could not reproduce the issue: changing the name works as it should. However the crash is very real: it seems that the caret index was invalid.

**Comment by itchyOwl** [comment] 2019-11-12 15:28
Could you provide the exact steps how did it happen? Which names did you use? You said that you wrote the text manually, right? Which version (exactly) were you on? The version of the game can be seen in the main menu, at the bottom left of the screen.

**Comment by Rokvach** [comment] 2019-11-22 09:12
Haven't been able to reproduce it, nor heard anyone else having this issue. Might of been caused by the Ctrl + A or Ctrl + Backspace keyboard shortcuts which previously caused crashes. Moving this to Done.

**Closed** 2019-11-27 12:15 UTC
Labels: Bug, Code
