### ISSUE TITLE
The game is somehow compiling in the E Drive?

### ISSUE THREAD

**Issue by TheHellFireo** [Regalis11/Barotrauma#1713] opened 2019-06-27 13:06 UTC
This is an issue of @fidelis#5400 in discord.
For some reason, he can't get the game to run and crashes when starting the game
Crashlog
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/3334831/crashreport.log)
and a picture he provided when he removed the E drive (USB)
![](https://cdn.discordapp.com/attachments/587647684794515468/593788028997075010/unknown.png)

**Comment by Regalis11** [comment] 2019-06-27 13:46
I don't think the drive has anything to do with the error, those are just file paths in the .pbd file that allow us to get a better idea of where in the code the exception occurred. 

For some reason the game fails to parse XML files: "Couldn't load xml document "config.xml"! {A(z) „System.Net.ServicePointManager” típus típusinicializálója kivételt váltott ki.}". I need to take a closer look at this to figure out what's causing it.

**Comment by EdusFF** [comment] 2019-07-17 12:01
Tried with system language set to Magyar / Hungarian, couldn't reproduce so doesn't seem to be language-related

**Comment by Rokvach** [comment] 2019-07-17 12:14
The conversation started back in 27.6.2018 on the baro-support Discord channel. 

Fidelis's game crashed on the loading screen when the "Press any key to continue" came up, the crash  didn't give any crash report. This was Fidelis's first time trying to launch the game and a total re-install didn't help the issue.

Fidelis did mention that hes hard drive was running out of space he only had 9 gb free and was planning to factory reset it. There hasn't been any confirmation if the factory reset helped the issue or not, but my speculation is that Barotrauma just didn't have enough space to work with which led to the crashing. 

The error above is a result where Fidelis tried to run Barotrauma outside of the Steam directory in a separate drive entirely, to test for possible fixes to the first crashing. 

@EdusFF

**Comment by Rokvach** [comment] 2019-07-20 23:55
I think this issue was caused because of the users PC and not by the game itself, Fidelis doesn't appear to have any issues playing the game after the hard drive wipe. 

Closing this.

**Closed by Rokvach** 2019-07-20 23:55 UTC
Labels: Bug, Code, Crash, Need more info
