### ISSUE TITLE
Character stretching - Because use the handcuffs.

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#9652] opened 2022-07-27 16:41 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

1. Character stretches:

https://user-images.githubusercontent.com/93348499/181301272-4f0dc7a8-45ea-40a0-839e-3df210a6e0d0.mp4

### Reproduction steps

1. Put the handcuffs in the inventory
2. Go to Character №2
3. Take his hand
4. Cuff yourself
5. Step aside a bit
6. Switch to Character №2
7. Stand far away
8. Switch to Character №1
9. Move in the opposite direction. 

### Bug prevalence

Happens every time I play

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-09-01 10:57
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/8e3c02780bacf9e7ec377a5462928e86b9993214 alongside some other oddities seen in the video

**Comment by NilanthAnimosus** [comment] 2022-09-07 10:55
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/553dc482307ed1776adba4f56ec07c1972f258af

Unable to reproduce the original issues seen in the video and all ragdoll issues seemed fixed, however:

I am finding it extremely difficult to drag characters whom are handcuffed now, sometimes walking to the side giving no movement at all unless I change my direction then its a snail pace.

Handcuffing oneself while grabbing an AI - Then using that AI to walk away, and re-grab the first character who cuffed themselves the animation felt off with a good distance to hands:

![image](https://user-images.githubusercontent.com/29177976/188858402-6b7cc287-4df0-4376-ad33-2d699083b0ef.png)
![image](https://user-images.githubusercontent.com/29177976/188858665-c8fb6e91-34aa-49ad-9551-6653badf3c57.png)

- I feel like handcuffing yourself while grabbing onto another should immediately release the grab in general. as while handcuffed you cannot grab others normally nor check their health.

**Comment by MaaiG** [comment] 2022-09-07 11:27
I got the impression that the character always leads another character by grabbing him with both hands. It looks strange ))
![Image 001_14-25](https://user-images.githubusercontent.com/93348499/188867464-beb01823-ab2b-43f4-9535-ae12eda91b73.png)

**Comment by Rokvach** [comment] 2022-09-07 11:42
I noticed that in multiplayer if you grab outpost NPC's by accessing their health interface they will spaz out, this doesn't seem to happen in singleplayer

Somewhat unrelated but you can also use H to grab service NPC's which you shouldn't be able to in multiplayer

Video:
https://www.youtube.com/watch?v=gmjnHNwTkNQ

**Comment by Regalis11** [comment] 2022-09-07 12:31
All of the mentioned issues (aside from being able to grab service NPCs) addressed in https://github.com/Regalis11/Barotrauma-development/commit/f06e3ef5d4e0d2067fbcb5e4ad82cc6264159a1a

**Comment by NilanthAnimosus** [comment] 2022-09-19 09:23
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/68d02ff7ba62555e380a24ff29b99b8a05450339, no issues found, closing.

**Closed by NilanthAnimosus** 2022-09-19 09:23 UTC
Labels: Bug, Code, Unstable
