### ISSUE TITLE
Game crashes when trying to load/enter a cave scene

### ISSUE THREAD

**Issue by Greatchairman** [Regalis11/Barotrauma#7921] opened 2021-12-24 05:53 UTC
- [√] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The game crashed when trying to load a cave scene after docking, I tried to load the autosave a few times but it still wouldn't load and crashed. I downloaded a fair amount of mods, but they worked perfectly and didn't crash before this. I don't know anything about the code, but if there's anything I can help or that I need to test, please let me know, thanks :).

**Steps To Reproduce**
I observed a fire in the reactor cabin just before I was about to dock (less than a second I guess). I don't understand the code, but that's what happens before the crash, so hopefully that's helpful.

**Version**
The newest version on Windows.

**Additional information**
Crashreport attached.
[crashreport (15).log](https://github.com/Regalis11/Barotrauma/files/7772836/crashreport.15.log)

**Comment by Regalis11** [comment] 2021-12-29 15:43
This seems to happen when a mod doesn't configure the red "you are here" indicator for the status monitor. It should be possible to work around the issue by disabling the "oClockRadar_Alt" mod for now. Sorry for the inconvenience!

Duplicate of https://github.com/regalis11/barotrauma/issues/7794

**Closed by Regalis11** 2021-12-29 15:43 UTC
