### ISSUE TITLE
Several issues about pet behaviors and suggestions

### ISSUE THREAD

**Issue by Raven-233486** [Regalis11/Barotrauma#11800] opened 2023-04-11 17:52 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

First problem, maybe like issue #11514 , But my one is slightly different, When I arrived at a hostile outpost and docked, my pet would become hostile as well.
Second problem, about modding, is when I labeled the pet as "Humanoid = true", the pet's behavior became strange. 
  (1)It seems it is ordered to follow itself, and continuously move to try to keep a distance from itself.
  (2)If I write "can eat = true" with "humanoid = true", the pet will try to eat but it cant eat. It actually hold the body but it cant eat, so there must be some mistakes cause if it is designed as cant eat why it can act this holding action?
Third problem, pets can not be identified by motion sensors (for example like the auto door).
Forth problem, is there is always a situation where the pet is hungry but it does not eat the food just right ahead of it.

Suggestions (irrelated with above):
I hope you can add a function that characters can be set to follow an arbitrary item (tag).

### Reproduction steps

Just as what I wrote above

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-04-12 13:13
Thank you for the report!

> First problem, maybe like issue https://github.com/Regalis11/Barotrauma/issues/11514 , But my one is slightly different, When I arrived at a hostile outpost and docked, my pet would become hostile as well.

This seems to be the same issue as https://github.com/Regalis11/Barotrauma/issues/11514

> (1)It seems it is ordered to follow itself, and continuously move to try to keep a distance from itself.

I'm afraid I could not reproduce the issue. I tested it by just changing "IsHumanoid" to true on the vanilla orange boy pet, and it seems able to follow targets with no issues (aside from the animations being messed up due to the humanoid animations not being properly configured).

> (2)If I write "can eat = true" with "humanoid = true", the pet will try to eat but it cant eat. It actually hold the body but it cant eat, so there must be some mistakes cause if it is designed as cant eat why it can act this holding action?

I'm afraid I could not reproduce this issue either. I tested with the same modified orange boy, and it seems to be able to eat:

https://user-images.githubusercontent.com/14351070/231467475-bccc59de-4f82-4f69-84b9-8b42d28874d4.mp4

> Third problem, pets can not be identified by motion sensors (for example like the auto door).

You need to set the "target" value of the motion detector to include pets. In general, the motion detectors in vanilla subs are set to ignore pets, because having the pets wander around the sub opening doors often caused problems - causing them to open doors you want to keep closed, and preventing you from putting the pet away in a safe room when you want to keep it out of the way.
![image](https://user-images.githubusercontent.com/14351070/231468443-91af28c3-f1db-444c-acec-b8c275c99a51.png)


> Forth problem, is there is always a situation where the pet is hungry but it does not eat the food just right ahead of it.

To me this seems like the same issue as (2), or maybe rather a consequence of that issue.

**Comment by Raven-233486** [comment] 2023-04-12 23:17
You may have misunderstood my problem with modding.
I mean pet ate the dead body, not pet food at (2).

**Comment by Raven-233486** [comment] 2023-04-18 03:43
> 

About (1) situation, you can reproduce it by following steps:
I. have two pets that written "humanoid" and "CanEat"
II. Then these two pets will trying to follow each other

About (2) situation, I used F3 control panel to control the pet, and I found that [G] was used both on "grab" and "eat", so maybe it is a kind of key conflict? So that pet cant eat with "humanoid"?
And I test again, it shown that pets with "humanoid" cant eat even pet food

**Comment by Regalis11** [comment] 2023-04-20 08:06
Thanks for the extra info!

1. Would you mind sharing your custom pet here? I wonder if the issue is somewhere in the configuration, since orange boy seemed to work with no issues when I changed it to a humanoid.
2. It's not a key conflict, the ability for humanoid characters to eat other characters is actually just something we haven't implemented.

**Comment by Regalis11** [comment] 2023-05-27 10:08
No known steps to repro, closing

**Closed by Regalis11** 2023-05-27 10:08 UTC
Labels: Bug, Need more info, Modding
