### ISSUE TITLE
Gazer rage effect too "strong" (in an artistic way)

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5761] opened 2021-05-12 01:44 UTC
- [ yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The particles the monsters emmit when being observed by a watcher has an incredibly strong colour, bug or art design problem?

**Version**
Unstable v0.1400.0.0 Windows

**Additional information**
![image](https://user-images.githubusercontent.com/55637865/117905952-64c8d580-b2aa-11eb-9cfd-8f8be6940e33.png)
(thanks for adding the aggresive watcher spawns btw :D)

**Comment by Regalis11** [comment] 2021-05-12 07:45
Caused by the same bug as https://github.com/regalis11/barotrauma/issues/5752, fixed in https://github.com/Regalis11/Barotrauma-development/commit/5fc43eb6ccc7fbc825312d7fc68ffe61e38ce64c

**Comment by Rokvach** [comment] 2021-05-18 09:01
Tested, no issues. Closing.

**Closed by Rokvach** 2021-05-18 09:01 UTC
Labels: Bug, Code
