### ISSUE TITLE
Crash in GUITextBox.CalculateCaretPos: Index was outside the bounds of the array. (System.IndexOutOfRangeException)

### ISSUE THREAD

**Issue by pavel4win** [Regalis11/Barotrauma#12967] opened 2023-11-03 10:04 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

It happen when I open search tab in navigator window and click left mouse button on search string.

[crashreport (32).log](https://github.com/Regalis11/Barotrauma/files/13248883/crashreport.32.log)

### Reproduction steps

Before I do it, I change language from rus to eng and back from eng to rus.
may be it is cause?

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-11-06 11:39
Thank you for the report! I think I found a way to reproduce this reliably, it seems to happen when changing the language causes the text to become shorter, and the previous caret position to be past the end of the new text.

Steps to repro:
1. Go to a status monitor
2. Open the item finder, search for something whose name is longer in English than in Russian (Broad-spectrum Antibiotics seemed to be one example)
3. Choose the textbox
4. Switch to Russian
5. Choose the textbox, press Ctrl+A

Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/c8cb87d9c61979acb7d5ab2ff81f4fbcf9cf2c8d

**Comment by Rokvach** [comment] 2023-11-22 12:47
Tested, looks like we've already handled the null exception on the Unstable build, so I compared this to the current stable version and I was able to cause the crash there using the above repro steps, in Unstable the selection area doesn't update correctly when going from longer text to shorter text so that is something this PR fixes. 

Working correctly, can be merged and closed.

**Closed** 2023-11-24 11:34 UTC
Labels: Bug, Code, Crash
