### ISSUE TITLE
Jovian radiation advances when you exit to server lobby

### ISSUE THREAD

**Issue by gabepombo1** [Regalis11/Barotrauma#7680] opened 2021-12-09 07:58 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

Jovian radiation advances when you exit to server lobby.

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

Try to leave to server lobby with jovian radiation on. I am 20-25 rounds deep.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

Latest version. Windows 10.

**Additional information**

**Comment by Regalis11** [comment] 2021-12-09 08:47
Thank you for the report!

I'm afraid I could not find a way to reproduce this though. How exactly, or at what point, are you returning to the lobby? In an outpost level, during a mission, at the end of the mission...? How do you see that the radiation has progressed when you continue the campaign (since it shouldn't be visible until you get to the map screen at the end of the mission)?

**Comment by gabepombo1** [comment] 2021-12-09 19:14
I found that it happens when you are docked at an outpost. So you can check
the map before leaving the lobby and then after you join back. Also, the
faction reputation just randomly goes down sometimes when you leave from
the outpost. It's strange because it does not happen every time, but when
it does happen, we didn't even get a chance to climb aboard the station.
So, I know it's not because I interacted with something that I should not
have.

**Comment by Regalis11** [comment] 2022-02-04 10:54
No known steps to repro, closing

**Closed by Regalis11** 2022-02-04 10:54 UTC
Labels: Bug, Need more info, Code, Networking
