### ISSUE TITLE
Server kick: event id 45732, entity id 8657

### ISSUE THREAD

**Issue by thefatall** [Regalis11/Barotrauma#8909] opened 2022-04-22 12:02 UTC
**Description**
After the update every time somebody respawns in shuttle, server kicks every player with following error:
Missing item Wrench, sub: Hemulen, event id 45732, entity id 8657.

**Steps To Reproduce**
When shuttle respawn timer ends, server kicks everyone, including me (host).

**Version**
The bug has occured in v0.17.12.0 (Urban Expanses update). 

**Additional information**
We use Winterhalter sub and already on fourth biome in our multiplayer campaign. Shuttle respawn timer set to 5 minutes. No major mods installed.

![211](https://user-images.githubusercontent.com/104205116/164710041-5a826c76-655e-46cd-8f69-d78390d3b893.png)

**Comment by Regalis11** [comment] 2022-04-22 12:33
Duplicate of https://github.com/Regalis11/Barotrauma/issues/6265

**Closed by Regalis11** 2022-04-22 12:33 UTC
