### ISSUE TITLE
Editor grid and in-game palcement grid are 50% misaligned in both axes

### ISSUE THREAD

**Issue by nomnivore1** [Regalis11/Barotrauma#12815] opened 2023-10-15 04:01 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

editor grid and in-game placement grid do not match. the grid lines are in identical positions, but editor placement snaps to the centers of grid squares while in-game placement snaps to the corners. This means that building something in the editor such that players can add to it in game requires building everything off-grid. 

### Reproduction steps

1. open editor and place a grid of components (I used relays), allowing grid snapping to position them on the placement grid
2. "test" the submarine and attempt to place additional components on the same grid
3. observe that the components placed in gameplay snap to the corners of the grid, out of alignment with the relays placed in the editor. 
![image2](https://github.com/Regalis11/Barotrauma/assets/48558380/72a61c0e-8919-463d-b66a-6671f90fd6b7)
![image](https://github.com/Regalis11/Barotrauma/assets/48558380/d11481d3-bc74-4bb4-b339-9a4fb85fc6a6)

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Other

### -

Have not tested if the grid aligns correctly in multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-10-15 14:06
Duplicate of https://github.com/Regalis11/Barotrauma/issues/12257

**Closed by Regalis11** 2023-10-15 14:06 UTC
