### ISSUE TITLE
beacon station transudcer signal pin wiring optional

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5789] opened 2021-05-13 19:36 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
data_out on the transducer doesn't actually have to be connected to the sonar monitor's transducer in
having the wire just lead into the transducer but not being wired to any pin seems to be ok

**Steps To Reproduce**
1. load into a beacon station in mission
2. have a disconnected wire from transducer -> sonar monitor's transducer in (might also be optional)
3. mission success??

**Version**
14

**Additional information**

**Comment by Tsunder** [comment] 2021-05-13 19:42
related to #4278

**Comment by Regalis11** [comment] 2021-05-14 07:31
Duplicate of https://github.com/Regalis11/Barotrauma/issues/4278

**Closed by Regalis11** 2021-05-14 07:31 UTC
