### ISSUE TITLE
black and pixled screen

### ISSUE THREAD

**Issue by Simon242908** [Regalis11/Barotrauma#9253] opened 2022-06-03 18:21 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![obrázek_2022-06-03_201808403](https://user-images.githubusercontent.com/106835100/171923045-91a8fdf3-5160-4760-8c61-08ddb0abbfb0.png)

Hello,
i have cracked Barotrauma but its worked normally and now i see just this. It is a normal menu cuz its works but its all black and pixled (the picture) can u help me somehow? And yes, i have online fix but again it worked normally aswell.

### Reproduction steps

1.  Strat the game as Admin
2. "loading"
3. the picture thing

### Bug prevalence

Happens every time I play

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
none
```

**Comment by Regalis11** [comment] 2022-06-05 11:59
Duplicate of https://github.com/Regalis11/Barotrauma/issues/9213

**Closed by Regalis11** 2022-06-05 11:59 UTC
