### ISSUE TITLE
Spam  in the server list

### ISSUE THREAD

**Issue by Frizit** [Regalis11/Barotrauma#12096] opened 2023-05-29 14:25 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![20230529170833_1](https://github.com/Regalis11/Barotrauma/assets/81575392/5d1d5cb7-100a-49c9-bccf-38f04d11aae8)

### Reproduction steps

1. enter the game.
2. go to the list of servers.

### Bug prevalence

Just once

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-05-29 14:37
Duplicate of https://github.com/Regalis11/Barotrauma/issues/9768

**Closed by Regalis11** 2023-05-29 14:37 UTC
