### ISSUE TITLE
Saved the game while grabbing Psilotoad in hands causes it become invisible.

### ISSUE THREAD

**Issue by pavel4win** [Regalis11/Barotrauma#12554] opened 2023-08-25 09:46 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I saved the game while holding Psilotoad in my hands. 
After restoring the game, Psilotoad remained in my hands but became invisible. 
I decided so because when I picked up in both hands ethanol the ethanol began to gradually lose the percentage of integrity. But at the same time, I did not find Psilotoad on the ship.
After that, I once again save and restored the game, but I could not find the toad anywhere. The pet disappeared.
In the same game, strange things happen to my Psilotoad. Sometimes it starts crawling to the left, ignoring food, if she is picked up and taken to the right, she immediately starts crawling to the left until she hits the left wall and so on.
As if the pet had a jammed left arrow

Later I realized that the ethanol was decreasing because I pressed the right mouse button.
Only the second error remains. 
The pet moves in one direction, ignoring the food. This only happens at the station.

### Reproduction steps

I do not know exactly
1. Hatch Psilotoad 
2. grab it with G key
3. Press ESC and choose "Save and quit"
4. Press "Continue campaign"
5. Fill inventory with things and then take ethanol in both hands.
6. See as ethanol slowly decreasing as if Psilotoad eats ethanol in your hands

### Bug prevalence

Just once

### Single player or multiplayer?

Multiplayer hosted using a dedicated server

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Jasontti** [comment] 2023-08-28 06:11
Could not reproduce.
Tested in MP, but psilotoad spawns normally in sub after campaign load.

**Comment by Regalis11** [comment] 2023-09-21 12:02
No knowns steps to repro, closing

**Closed by Regalis11** 2023-09-21 12:02 UTC
Labels: Need more info
