### ISSUE TITLE
[Unstable 0.1400] Bots and seeds cleanup

### ISSUE THREAD

**Issue by Bozhdynsky** [Regalis11/Barotrauma#5796] opened 2021-05-14 21:46 UTC
In recent Unstable version 0.1400 bots do an endless cleaup cycle. They pick up seeds, for example Vine, and just go to a hatch or a ladder and just stand there turning both ways. Even those bots that were not asked to do any cleanup will still pick up seeds and get stuck in the same way.

**Comment by Bozhdynsky** [comment] 2021-05-15 13:32
The sub was a custom, so there may have been a waypoint issue, doubtful as they are freely travelling all around the boat. There may be an issue with a lack of specific place to place the seed. But there should be no issue when all crewmen pickup the seeds (from deconstructing fertilizer) when only an assistant was tasked with a 'cleanup duty'.

**Comment by itchyOwl** [comment] 2021-05-17 06:47
Thanks for reporting. Could you embed or link the submarine here?

**Comment by Bozhdynsky** [comment] 2021-05-17 07:25
[https://github.com/Bozhdynsky/Dorudon/blob/4be6ef39bb144ea1f319e7b26eddb715fb98086d/Dorudon.sub](url)
Doe this work?

**Comment by itchyOwl** [comment] 2021-05-19 08:12
It doesn't. You could just drop the file here.

**Comment by Bozhdynsky** [comment] 2021-05-19 09:04
https://github.com/Bozhdynsky/Dorudon/blob/4be6ef39bb144ea1f319e7b26eddb715fb98086d/Dorudon.sub
You can copy the link, it does work.

**Comment by itchyOwl** [comment] 2021-05-20 07:41
Nice, didn't know that. I got it. Another way to do it would have been to zip it.

**Comment by itchyOwl** [comment] 2021-05-20 13:11
I don't think there's anything wrong in the sub.

I tested spawning all the possible seed variations and ordering a bot to clean them up. Everything seemed to work correctly until I picked a seedback the bot was trying to put the seeds into, which resulted the bot to continue following me ad infinitum.

Fixed this issue in Regalis11/Barotrauma-development@5fa5440.

Maybe that happened in your case too: the bot was trying to put the seeds into a bag that was moved somewhere it couldn't anymore access to?

**Comment by itchyOwl** [comment] 2021-05-24 15:29
I'll move this to QA, because I think it's solved.

**Comment by Lithosagym** [comment] 2021-06-03 03:54
Tested, AI going into a loop when the seed bag moves confirmed fixed, they just drop their held seed when the seed bag changes position then continue to successfully put seeds into the seed bag.

**Comment by Rokvach** [comment] 2021-06-03 10:08
Closing

**Closed by Rokvach** 2021-06-03 10:08 UTC
Labels: Bug, Code
