### ISSUE TITLE
[1.0] Iron Helmet layering issue with Headset

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11336] opened 2023-02-23 22:48 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Whilst certainly on the goofy side, this is problematic as the headset strap is masked by the helmet whilst the headset itself is not.

![image](https://user-images.githubusercontent.com/105495756/221047735-5c0b3676-c958-4937-9ade-2327757f83be.png)

### Reproduction steps

To reproduce this issue, the order in which the items are equipped are important. Unfortunately this issue happened last Saturday (18/02/23) and since I'm reporting it on Thursday (23/02/23), I forgot the order. It's either:
1. Equip Iron Helmet
2. Equip Headset
3. Observe layering issue
OR
1. Equip Headest
2. Equip Iron Helmet
3. Observe layering issue

### Bug prevalence

Happens every time I play

### Version

Other

### -

1.0.2.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-02-24 10:06
> as the headset strap is masked by the helmet whilst the headset itself is not.

What headset strap?

**Comment by Regalis11** [comment] 2023-02-24 10:43
Fixed the draw order issue in https://github.com/Regalis11/Barotrauma-development/commit/3b0d0a03ba3273b9154982a4fbc19f635d0c791c. 

Could not reproduce the issue with the strap: as far as I can see, there's no strap in the sprite.

**Comment by Rokvach** [comment] 2023-04-11 12:38
Tested, working correctly. Closing.

**Closed by Rokvach** 2023-04-11 12:38 UTC
Labels: Bug, Low prio
