### ISSUE TITLE
[0.12.0.1] Diving Suit holder does not refill Oxygen Tank if the Tank is Empty.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4933] opened 2021-01-29 00:49 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Diving Suit holder does not refill Oxygen Tank if the Tank is Empty. Does not affect Oxygen Shelf.

**Version**
0.12.0.1

**Comment by Benzin73** [comment] 2021-01-30 11:49
Ibe noticed this as well. The problem is o2 tank shelves and suit holders now need power. And the vanilla subs dont have power connections to them. You connect a wire from a power source (junction box), to its power_in port.

However, most subs have a lot of diving suit holders and o2 tank shelves, and will certainly not have enough free ports in their junction boxes so we can wire them ourselves in game. 
I think the vanilla subs need to be altered to include connections so those shelves & suit holders are allready powered, or aditional junction boxes, or we need to be able to place new junction boxes in game. Otherwise, this new (and very cool) feature will not work unless every player mods the sub in the sub editor to power those o2 systems.

**Comment by Regalis11** [comment] 2021-02-01 09:07
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5ce2a3a3596f8c275262b28c28e59ac12046c272

**Comment by Rokvach** [comment] 2021-02-01 09:16
Tested, no issues, closing.

**Closed by Rokvach** 2021-02-01 09:16 UTC
Labels: Bug, Medium Prio
