### ISSUE TITLE
Navigation, Sonar and Status Terminal/Monitor have their "box" slightly off

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#4102] opened 2020-10-18 18:07 UTC
More evident when you try to select/interact with it in person or highlighted in sub editor.
![](https://cdn.discordapp.com/attachments/668819422919524352/767237402200113162/Thing.jpg)

**Comment by Regalis11** [comment] 2020-10-19 07:42
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3195

**Closed by Regalis11** 2020-10-19 07:42 UTC
