### ISSUE TITLE
Players are joining my server and getting permission to start the round despite me being their as the host

### ISSUE THREAD

**Issue by xzero314** [Regalis11/Barotrauma#11123] opened 2023-02-02 00:08 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Basically title. Random players are joining and can start the game despite me being their as the host with perms

### Bug prevalence

Happens regularly

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-02-02 16:43
Thank you for the report!

I unfortunately could not find a way to reproduce the issue. If you could provide us a bit more details, it might help us diagnose the problem:

1. Do you have the "start when players are ready" setting enabled? That could explain this, especially if the "x% need to be ready" setting is set very low. Or do you know if the other players actually see the "start" button, as opposed to just the "ready to start" checkbox?

2. Does this apply to some specific game mode, or all of them?

3. Is this a dedicated server or are you hosting directly from the main menu?

4. Do you know if the players get a notification of being given permissions? Or does it seem like they are able to start the round despite seemingly having no permissions?

**Comment by xzero314** [comment] 2023-02-02 17:10
I do not have start when players are ready enabled.I can only say for certain this happens during campaign. Its happened in multiple instances with a full lobby and it happened one time with just one other person in my lobby. I asked the one person and they said they could see the start game button I as host normally have and they pressed it.Hosting from main menu unmodded.Based on the time the one guy alone joined there is no sign of permissions being handed out. Players are just naturally able to press start game when joining the lobby.Sent from my iPhoneOn Feb 2, 2023, at 8:44 AM, Joonas Rikkonen ***@***.***> wrote:﻿
Thank you for the report!
I unfortunately could not find a way to reproduce the issue. If you could provide us a bit more details, it might help us diagnose the problem:


Do you have the "start when players are ready" setting enabled? That could explain this, especially if the "x% need to be ready" setting is set very low. Or do you know if the other players actually see the "start" button, as opposed to just the "ready to start" checkbox?


Does this apply to some specific game mode, or all of them?


Is this a dedicated server or are you hosting directly from the main menu?


Do you know if the players get a notification of being given permissions? Or does it seem like they are able to start the round despite seemingly having no permissions?

**Comment by DuckY-Y** [comment] 2023-02-03 10:14
This has been quite annoying the last couple of weeks.

**Comment by Regalis11** [comment] 2023-02-03 13:29
@DuckY-Y Weeks? Do you mean this was an issue even before this week's pre-patch? I would've though that this was caused by some of the changes in the patch that made it easier to manage a campaign without a host, but if it's been an issue for longer, the cause must be somewhere else.

**Comment by Regalis11** [comment] 2023-02-03 13:44
I think I `might` have been able to reproduce this now. When joining a server that has already started a campaign, any client will see these buttons here, and is allowed to press "continue":
![image](https://user-images.githubusercontent.com/14351070/216618086-7ca09223-3d82-454c-b743-49f131837699.png)

Is this what you meant, not the "start" button at the bottom-right corner of the screen?

**Comment by xzero314** [comment] 2023-02-03 15:26
I am pretty certain you have solved this. I cannot speak for the other individual you have ccd but this has been a very recent thing on my end. I have not joined a server as a player this patch, only host. So i think you are correct that is the continue button clients may pressSent from my iPhoneOn Feb 3, 2023, at 5:44 AM, Joonas Rikkonen ***@***.***> wrote:﻿
I think I might have been able to reproduce this now. When joining a server that has already started a campaign, any client will see these buttons here, and is allowed to press "continue":

Is this what you meant, not the "start" button at the bottom-right corner of the screen?

**Comment by DuckY-Y** [comment] 2023-02-07 09:00
> @DuckY-Y Weeks? Do you mean this was an issue even before this week's pre-patch? I would've though that this was caused by some of the changes in the patch that made it easier to manage a campaign without a host, but if it's been an issue for longer, the cause must be somewhere else.

In the campaign I'm in, we've had this issue occur like 2.5 weeks before I commented that.

**Comment by Rokvach** [comment] 2023-02-07 12:18
Tested, didn't notice any issues with this after the fix, can be merged and closed.

**Closed** 2023-02-07 13:07 UTC
Labels: Bug, Code, Networking
