### ISSUE TITLE
Infinite mudraptor eggs, money, and dead miner

### ISSUE THREAD

**Issue by Dreadknight-Cassandra** [Regalis11/Barotrauma#10379] opened 2022-11-14 06:46 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Arrived at mining station, got the event of a man drinking alone due to mudraptor attacks in the mine after finding eggs. Got the issue of dialogue repeating that has been reported. Went to the mine section, examined the dead body, got caught in an infinite loop of dialogues I could not break of checking the body. Both selecting "search his pockets" and "Leave the body alone" cause a dialogue from earlier to play, leading back to that choice, and spawning another identical dead body and a mudraptor egg. Every time "Search his pockets" is selected, cash is awarded (We make 30k marks before we have to leave). There was no way to walk away from the dialogue, the map could be called up but not moved around.

### Reproduction steps

1. Arrive at mining outpost
2. Get event of a man drinking alone
3. Proceed down dialogue options until you are informed of dead person's body in the mine
4. Go to mine
5. Interact with dead body
![20221113192721_1](https://user-images.githubusercontent.com/118158571/201593018-50baf859-9fca-475a-9559-de8ad415f44a.jpg)

### Bug prevalence

Just once

### Version

0.20.5.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-11-14 08:14
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10320

**Closed by Regalis11** 2022-11-14 08:14 UTC
