### ISSUE TITLE
Server crash when a mechanic hits an electric engineer that has the electrochemist talent.

### ISSUE THREAD

**Issue by UzricRash** [Regalis11/Barotrauma#7229] opened 2021-11-09 08:17 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When a mechanic hits in melee an engineer that has the electrochemist talent there is a chance that a server crash happens.
I don't know what talents the mechanic has but since it's chance based I think a mechanic talent is involved.
Also the mechanic used a wrench but I ignore if it's relevant or not.

**Steps To Reproduce**
1. Create a server.
2. Spawn a mechanic and an engineer.
3. Give the engineer the electrochemist perk.
4. Give the mechanic every perk (unknown if relevant).
5. Have the mechanic hit the engineer a bunch of times with a wrench (weapon unknown if relevant). Make sure to wait 10 seconds between hits to reload the electrochemist talent effect.

**Version**
Linux Dedicated Server 0.15.13.0.

**Additional information**
In 6-48 hours I will give logs and better reproduction steps.

**Comment by Regalis11** [comment] 2021-11-09 09:10
Thank you for the report! I'm afraid I couldn't get this to occur myself. I suspect it may have been caused by some specific combination of talents? If you could send us a crash report, it'd help us a lot in diagnosing this!

Thanks and sorry for the trouble!

**Comment by UzricRash** [comment] 2021-11-09 15:46
Crash log here: [Pastebin](https://pastebin.com/qWkPfq01)
More relevant files (involved talent trees' screenshots, crashlog, lastsession.txt which is a tee'd output for the whole session, save.save and chars.xml) here: [Filebin](https://filebin.net/9i3gylool9cen3t8)
In the save above the crashes happen with Engineer Uzric Rash when hit by Mechanic Kibu (and Mechanic Grotnur for the tests, character copied from Kibu).

**Comment by Regalis11** [comment] 2021-11-10 09:47
Thank you! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e590f72f

**Comment by JoneKone** [comment] 2021-11-23 21:05
https://p.ip.fi/COxV

Experienced same crash. On our dedi server. (lua by evilfactory server.)

0.15.13.0.

**Comment by Rokvach** [comment] 2021-11-29 12:44
Tested, working correctly. Closing.

**Closed by Rokvach** 2021-11-29 12:44 UTC
Labels: Bug, Code, Crash
