### ISSUE TITLE
Stuck in Freecam when round started in Listen Server, but not in Dedicated Server?

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2074] opened 2020-01-30 15:47 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Going to New Nanhui with "Killing a Moloch" on this save while hosting the server via in game, I get stuck in freecam mode, with nothing spawning in and unable to end round. When I load the save on Dedicated server, I can play it just fine.

**Steps To Reproduce**
Host a server in the game
Load up campaign save
Select New Nanhui Military Outpost as destination
Select Killing a Moloch as the mission
Start

**Version**
0.9.701~0.9702
Windows
[New Nanhui Stuck.zip](https://github.com/Regalis11/Barotrauma/files/4134841/New.Nanhui.Stuck.zip)

**Comment by Kaillera** [comment] 2020-01-30 22:15
This still happens on 0.9.702 but not in this save file. Happens in other spots of the game.

**Comment by Kaillera** [comment] 2020-02-04 19:27
Still happens on 0.9.703. Even at the start of a mission round.

**Comment by Regalis11** [comment] 2020-02-05 19:19
I'm able to reproduce this consistently in v0.9.701.0. It seems to happen because ChildServerRelay used to time out if loading the round took more than 15 seconds, which was supposedly fixed in https://github.com/Regalis11/Barotrauma-development/commit/d5eb3a6f. 

I think this might still be somehow related to ChildServerRelay. @juanjp600 any ideas? Even if it isn't related, I think we should make clients react to the server's ChildServerRelay shutting down instead of letting it get stuck to this kind of "limbo".

**Comment by Regalis11** [comment] 2020-02-21 12:07
Should be fixed in the latest Unstable build with the ChildServerRelay improvements

**Comment by Rokvach** [comment] 2020-02-27 07:46
I wasn't able to reproduce this issue, so seems to be working correctly. Closing.

**Closed by Rokvach** 2020-02-27 07:46 UTC
Labels: Bug, Code, Networking
