### ISSUE TITLE
Character ragdoll becomes tangled when dragged out of the submarine using a rope

### ISSUE THREAD

**Issue by Emanthealmighty** [Regalis11/Barotrauma#7639] opened 2021-12-05 22:35 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When a character is dragged out of a submarine or any sort of hull through the use of a rope, each of the character's limbs curl on themselves and spin wildly. The rope which was attached to the character also snaps.

**Steps To Reproduce**
1. Spawn a "fractalguardian" (the one with the harpoon gun).
2. Shoot a human who is inside the submarine and pull it out.
3. Once the human is pulled outside of the submarine, their ragdoll will spaz out and the harpoon's rope will break.

**Version**
v.0.15.13.0

**Comment by Regalis11** [comment] 2021-12-07 09:55
Duplicate of https://github.com/Regalis11/Barotrauma/issues/6922

**Closed by Regalis11** 2021-12-07 09:55 UTC
