### ISSUE TITLE
Move wire between components in play mode

### ISSUE THREAD

**Issue by r-barnes** [Regalis11/Barotrauma#5960] opened 2021-06-03 03:28 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
During play mode I'd like to disconnect a wire from a component/object and reconnect it to a different component. However, I can't figure out how to get myself to a state where I'm holding the wire again... it looks like I have to rerun the whole thing.

**Steps To Reproduce**
Run wire between A and B. Try to move wire from B to C; fail.

**Version**
Linux - most recent Steam version.

**Additional information**
N/A

**Comment by Regalis11** [comment] 2021-06-03 07:43
Thank you for the report! This is actually not a bug, but intentional: it used to be possible to rewire things by only disconnecting one end of the wire, but we changed it so that you need to disconnect both ends. The intention was to make it a little more difficult for griefers to mess with the sub's built-in wiring by only allowing the wiring to be altered if you have access to the devices at both ends of the wire. This is not the first time this wiring problem has come up though, so I think we could consider changing it.

We generally only use the issue tracker for bug reports, while feature requests or suggestions on changing some existing features should go in the [GitHub Discussions](https://github.com/Regalis11/Barotrauma/discussions), so I'll close this ticket.

**Closed by Regalis11** 2021-06-03 07:43 UTC
