### ISSUE TITLE
Wire Wont Remove from Diagram-Mode Gui Box

### ISSUE THREAD

**Issue by Dopamin3** [Regalis11/Barotrauma#7765] opened 2021-12-14 18:00 UTC
- [Yes ] I have searched the issue tracker to check if the issue has already been reported.

I am in a default sub, the Berillia. There is a specific wire connecting a water detector and a signal check circuit, this wire, when removed from both sides, cannot be removed from the GUI box, onto the hotbar. Every other signal check component I have encountered on the sub, you can remove the blue wire onto the hotbar.

The signal check circuit is located in the LOWER AIRLOCK on the bottom of the boat, to the pump on the inside door.

I have documented it here:
https://www.twitch.tv/videos/1233165682
TimeStamp:
5:34:50

Steam Current Version, etc.

**Comment by Dopamin3** [comment] 2021-12-14 20:17
**Update**

Happening to other things wired in the sub as well. Doing a couple relays and the wires wont pull off the box onto the hotbar. It's in a different area of the sub.

**Comment by Regalis11** [comment] 2021-12-15 10:29
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7486

**Closed by Regalis11** 2021-12-15 10:29 UTC
