### ISSUE TITLE
Unable to load into campaign round in multiplayer

### ISSUE THREAD

**Issue by Infortnut** [Regalis11/Barotrauma#11600] opened 2023-03-19 15:12 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Attempting to load into a campaign round on another player's host causes the game to get stuck at the loading screen.

The problem occurs only for me (the rest of the players connect successfully) and only on one submarine. (We use a custom submarine, on which a lot of objects have accumulated during the campaign - 9500 + -)

However, the problem does not appear if I am the host of the game.
There are no problems entering the server lobby.

The loading screen does not freeze completely:
1. The sound of the game remains.
2. Loading screen animation works.
3. When the server shuts down, I get a window with the appropriate notification (but I still can't exit the loading screen).
4. I hear the sound of messages from the in-game chat.

The body of the character successfully appears on the submarine (and dies after a while).

If I try to reconnect to the server and enter observation, I get kicked out of the server with the error "coroutine "MultiplayerCampaign.DoInitialCameraTransition" has failed".
![2133213231](https://user-images.githubusercontent.com/61143599/226184670-a23ac43e-cea8-40c2-a60a-016f83c1b12b.PNG)

There is a suggestion that this may be due to the large difference in round loading time between me and the rest of the players - I always load longer than others.

### Reproduction steps

1. Connect to the server lobby.
2. Wait until the round starts.

At this point, an error occurs.
Campaign save file attached. 
[campaign.zip](https://github.com/Regalis11/Barotrauma/files/11011449/campaign.zip)

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
The game does not generate error messages or crash reports when I join a round with other players.

When I connect in watch mode, I get kicked out of the server with this error:
"coroutine "MultiplayerCampaign.DoInitialCameraTransition" has failed".
```

**Comment by Regalis11** [comment] 2023-03-19 16:46
Duplicate of https://github.com/regalis11/barotrauma/issues/11454

**Closed by Regalis11** 2023-03-19 16:46 UTC
