### ISSUE TITLE
(Unstable) Failed to Read event entity "Pirate Lord"!

### ISSUE THREAD

**Issue by Drkriegerr** [Regalis11/Barotrauma#6002] opened 2021-06-09 02:46 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Failed to read event for entity "Pirate Lord"! {Index was outside the bounds of the array.}
   at Barotrauma.Character.ClientRead(ServerNetObject type, IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\CharacterNetworking.cs:line 0
   at Barotrauma.Networking.ClientEntityEventManager.Read(ServerNetObject type, IReadMessage msg, Single sendingTime, List`1 entities) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\NetEntityEvent\ClientEntityEventManager.cs:line 239
Appears 1-2 times per pirate mission, Usually appears when Im nearing the pirate sighting, then if the pirate ship isnt there, it will happen again when I do come across them.

**Steps To Reproduce**
Seems to happen for me pretty consistently, I am running quite a few mods though. The last game crashed although that usually doesnt happen from this error. I believe the crash was probably due to tons of enemies being on screen and lots of gunfire, I will include crash log at the end of this report.

**Version**
Game version 0.1400.3.0 (ReleaseWindows, branch release, revision 2006eac9ac)

**Additional information**
Crash log, though I dont believe this is due to this error, it includes all the mods I had on at the time:
Barotrauma Dedicated Server crash report (generated on 6/8/2021 10:26:49 PM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

Game version 0.1400.3.0 (ReleaseWindows, branch release, revision 2006eac9ac)
Language: English
Selected content packages: Vanilla 0.9, Shipwrecks Extended, Underwater Sledge, T.I.T.A.N. power suit, [ENV] Beacons Extended, Seated Operators, Malborasek with Sound, MoreHeadgear, TC Instruments, OxyGear, Jukebox, Waistpack, Thalassophobia, TC Meme Horns, TC Guns, TC Fortunate son speaker, More Alarm Sounds, Meaningful Upgrades, Meaningful CPR, BetterGlass, EK Gunnery, EK Utilities, EK Armory, EK Dockyard
Level seed: MQaspkfj
Loaded submarine: 1TUnstable (34E894F0266E2189AAB5A0BC7417F719)
Selected screen: Barotrauma.GameScreen
Server (Round had started)

System info:
    Operating system: Microsoft Windows NT 6.2.9200.0 64 bit

Exception: Sequence contains no elements (System.InvalidOperationException)
Target site: Void ThrowNoElementsException()
Stack trace: 
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Barotrauma.ShipCommandManager.UpdateCommandDecision(Single timeSinceLastUpdate) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\ShipCommandManager.cs:line 245
   at Barotrauma.ShipCommandManager.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\ShipCommandManager.cs:line 94
   at Barotrauma.HumanAIController.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\HumanAIController.cs:line 429
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2572
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 217
   at Barotrauma.GameMain.Run() in <DEV>\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 358
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 59

Last debug messages:
   6/8/2021 10:26:49 PM - [6/8/2021 10:26:49 PM]
  Saving banlist
   6/8/2021 10:26:49 PM - [6/8/2021 10:26:49 PM]
  Pirate Elite launched Coilgun (projectile: Piercing Coilgun Bolt)
   6/8/2021 10:26:48 PM - [6/8/2021 10:26:48 PM]
  Inner wall breached by Annette Palmieri
   6/8/2021 10:26:48 PM - [6/8/2021 10:26:48 PM]
  Alan Wheeling: Leak in upper fore side!
   6/8/2021 10:26:48 PM - [6/8/2021 10:26:48 PM]
  Annette Palmieri launched Coilgun B (projectile: Piercing Coilgun Bolt)
   6/8/2021 10:26:48 PM - [6/8/2021 10:26:48 PM]
  Pirate Elite launched Coilgun (projectile: Piercing Coilgun Bolt)
   6/8/2021 10:26:48 PM - [6/8/2021 10:26:48 PM]
  Omari Gallagher launched Pulse Laser (projectile: Pulse Laser Bolt)
   6/8/2021 10:26:48 PM - [6/8/2021 10:26:48 PM]
  Annette Palmieri launched Coilgun B (projectile: Piercing Coilgun Bolt)
   6/8/2021 10:26:48 PM - [6/8/2021 10:26:48 PM]
  Pirate Elite launched Coilgun (projectile: Piercing Coilgun Bolt)
   6/8/2021 10:26:48 PM - [6/8/2021 10:26:48 PM]
  Annette Palmieri launched Coilgun B (projectile: Piercing Coilgun Bolt)
   6/8/2021 10:26:48 PM - [6/8/2021 10:26:48 PM]
  Inner wall breached by Pirate Elite
   6/8/2021 10:26:48 PM - [6/8/2021 10:26:48 PM]
  Pirate Elite launched Coilgun (projectile: Piercing Coilgun Bolt)
   6/8/2021 10:26:47 PM - [6/8/2021 10:26:47 PM]
  Annette Palmieri launched Coilgun B (projectile: Piercing Coilgun Bolt)
   6/8/2021 10:26:47 PM - [6/8/2021 10:26:47 PM]
  Pirate Elite launched Coilgun (projectile: Piercing Coilgun Bolt)

**Comment by Regalis11** [comment] 2021-06-09 07:31
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e5501a918a1c9a85ce894ca932cedc485967735b and https://github.com/Regalis11/Barotrauma-development/commit/ff1421cc1e4a6ae780d428b29f961c56d99d320d

**Comment by Rokvach** [comment] 2021-06-14 06:04
Tested, wasn't able to reproduce. Seems to be working correctly, closing.

**Closed by Rokvach** 2021-06-14 06:04 UTC
Labels: Bug, Code, Networking
