### ISSUE TITLE
[0.1400.0.0] ammuntion boxes in coilgun loaders are little offset.

### ISSUE THREAD

**Issue by Lefttroll** [Regalis11/Barotrauma#5764] opened 2021-05-12 03:51 UTC
- [x] I have searched the issue tracker to check and issue has already been reported by EKVideogames in his ticket-report.

**Description**
ammunition boxes are little offset from center of coilgun loader

**Steps To Reproduce**
1. install barotrauma
2. get unstable version
3. go in sub-editor
4. spawn coilgun loader
5. load it with any ammo box

**Version**
[0.1400.0.0] Unstable, Windows 10 pro.

**Additional information**
Screenshot of problem itself:
![Barotrauma_TI0gXf9Cq5](https://user-images.githubusercontent.com/42521948/117915643-61573d80-b2ee-11eb-8915-c91530337090.png)

**Comment by Regalis11** [comment] 2021-05-12 08:09
I'm afraid I could not reproduce this
![image](https://user-images.githubusercontent.com/14351070/117941105-747c0480-b312-11eb-88d6-75852138591a.png)

**Comment by Lefttroll** [comment] 2021-05-12 12:04
[Catfish.zip](https://github.com/Regalis11/Barotrauma/files/6465966/Catfish.zip)
@Regalis11 this is affected by bug submarine, i hope it gonna help you with finding a problem! (sorry for long answer)

**Comment by LePiromano** [comment] 2021-05-12 23:48
happened to me on the humpback
![image](https://user-images.githubusercontent.com/55637865/118057939-63a7af00-b363-11eb-88d8-f90043d41741.png)

**Comment by Regalis11** [comment] 2021-05-14 07:15
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f6363a1f5de715446cf42684ad2032f6aa6a4666

**Closed** 2021-05-14 13:30 UTC
Labels: Bug, Code
