### ISSUE TITLE
Disconnect with Error while reading a message from server ('Index was out of range' in MultiplayerCampaign.ClientRead)

### ISSUE THREAD

**Issue by SilenceLurker** [Regalis11/Barotrauma#10570] opened 2022-11-26 14:16 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When I connect my friend's Server by Steam ,game always report Unable to establish P2P connection and can get a warnning in Debug console : **WARNING: Tried to restore enabled packages multiple times/without performing a backup**
Sometime I can connect for a moment and then I can get this Error report:
`
Error while reading a message from server, {Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')}
at Barotrauma.MultiplayerCampaign.ClientRead(IReadMessage msg) in
<DEV>\Barotrauma(BarotraumaClient\ClientSource\GameSession\GameModes\MultiPlayerCampaign.cs:line 699
at Barotrauma.Networking.GameClient.ReadLobbyUpdate(lReadMessage inc) in
<DEV>\BarotraumalBarotraumaClient\ClientSourcelNetworking\GameClient.cs:line 2007
at Barotrauma.Networking.GameClient.ReadDataMessage(lReadMessage inc) in
<DEV>\BarotraumalBarotraumaClient\ClientsNetworking\GameClient.cs:line 624
at Barotrauma.Networking.SteamP2PClientPeer.Update(Single deltaTime) in
<DEV>\BarotraumalBarotraumaClient\ClientSourcelNetworking\Primitives\Peers\SteamP2pClientPeer.cs:line 260
at Barotrauma.Networking.GameClient.Update(Single deltaTime) in
<DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 477
`

### Bug prevalence

Happens every now and then

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-12-05 11:48
Duplicate of https://github.com/Regalis11/Barotrauma/issues/9926

**Closed by Regalis11** 2022-12-05 11:48 UTC
