### ISSUE TITLE
Camel issues round 2

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9814] opened 2022-09-02 18:14 UTC
- [x] Ducts can't drain water (hulling/detector problem)
Since the water detectors use Signal_Out and the hull goes below the detector, the hulls can't be fully drained. Either resize the hulls like other subs or rewire detectors to Water_%

![image](https://user-images.githubusercontent.com/73229309/188212192-a4bcad7b-a9ee-4d5f-8a1c-dc982c48aadc.png)
How it is done:
![image](https://user-images.githubusercontent.com/73229309/188212809-bd27e965-cad2-48f6-a97d-0f18cc2d7184.png)

- [x] AND component missing a false output (pump doesnt turn off)

![image](https://user-images.githubusercontent.com/73229309/188844184-fd558e1a-242b-46e7-a916-059898cec8b6.png)

- [x] No auto-doors
Camel doesn't have a single auto-closing door for some reason, while every other sub has

- [x] Fabrication hull linked to cargo hull
![image](https://user-images.githubusercontent.com/73229309/188213650-27fd5543-2172-4de6-9cff-920fcbf3dad4.png)

**Comment by mygamingaccount** [comment] 2022-09-04 08:09
There's a battery on board but it's connected to an O2 generator and a charging dock.

Those are the things I would specifically want to avoid to be powered by a battery.

**Comment by Regalis11** [comment] 2022-09-05 06:37
Fixed the hulls in https://github.com/Regalis11/Barotrauma-development/commit/0ee56ee582fe0ec509cb4cfce17b96768c2338e7

**Comment by Solbusaur** [comment] 2022-09-06 17:20
Docking port needs a platform approximately one-human-length beneath it like other subs for easier hatch fixing/rewiring.

Monsters are commonly stuck between the two humps and can't be fired on by the guns, leading to constant leaking until someone volunteers to go outside and terminate the clingers by hand. I would check the box "Ignore AI Target" for that whole middle section.

A lot of the background walls could use some texture offsets. It doesn't look right when the "Skirting board" part of the texture doesn't make contact with the floor. Also not all the walls are equal in height such as in engineering.
![image](https://user-images.githubusercontent.com/63509011/188697139-c2ac98da-a4f7-427c-8356-62bb0616b115.png)
![image](https://user-images.githubusercontent.com/63509011/188697298-0caa543e-a1fe-4711-b01d-3d1c09e0203e.png)

Also not a fan of the airlock section. The hatch is oversized, theres 2 vents in a room that isn't visited often, the cabinet is clipping into the walls, the motion detector is triggered by everything and the little stair piece looks very very off. I would swap the junction box and the cabinet around because the junction box can fit in there nicely. I would also remove the weirdly scaled stair thing and just make it a regular wall and cap. If the stair is necessary, I would place a stair case here instead of a ladder.
![image](https://user-images.githubusercontent.com/63509011/188697878-779dbf28-3e9f-4a92-9800-206c141abe3e.png)
Suggestion 1.
![image](https://user-images.githubusercontent.com/63509011/188699259-8ab2f045-03f9-45e0-bd1d-83c819d97d97.png)
Suggestion 2.
![image](https://user-images.githubusercontent.com/63509011/188699303-b85585a7-465f-41f4-8303-6d617dbbc5a0.png)

**Comment by Solbusaur** [comment] 2022-09-06 17:25
Hulls in the cargo containers can be simplified, as well as the top inside walls being removed
![image](https://user-images.githubusercontent.com/63509011/188700303-aa8bd6bd-2e8a-47ca-8983-15c249af8295.png)
![image](https://user-images.githubusercontent.com/63509011/188700648-f36ba9e9-b171-45b2-aa5b-041c0fae3672.png)

**Comment by JeroonBosch** [comment] 2022-09-08 06:31
> No auto-doors
This is as designed, auto-doors are not a must - it's designed to handle flooding (very) poorly, which compensates for it's otherwise significant strengths: low cost, high cargo space, decent gun coverage. 

> Hulls in the cargo containers can be simplified, as well as the top inside walls being removed
Part of the hull is outside the submarine on your screenshot

**Comment by Solbusaur** [comment] 2022-09-13 00:05
> Part of the hull is outside the submarine on your screenshot

A few of the other submarines do it, I figured we could let it slide :)
![image](https://user-images.githubusercontent.com/63509011/189779426-5c60a72c-01e4-431d-8d6d-d9b2c8916c05.png)

**Comment by Dillon17** [comment] 2022-09-17 06:20
docking port isn't connected to power so the sub can't be powered while docked
![Screenshot (64)](https://user-images.githubusercontent.com/113755543/190843503-0b2590a4-f96b-46e4-b590-88ab1aef4231.png)

**Comment by Regalis11** [comment] 2022-09-23 06:00
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/07b7c6381f9baf697e95f331e65568e1b98fd775

**Comment by Rokvach** [comment] 2022-09-28 09:51
Tested, no issues. Closing.

**Closed by Rokvach** 2022-09-28 09:51 UTC
Labels: Bug, Design, Unstable
