### ISSUE TITLE
[v0.10.6.2] Unstable - Crash when/after trying to drag delete items in container while having an item selected.

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#4103] opened 2020-10-19 05:43 UTC
Description :
Game will crash when you attempt to drag delete (ctrl + lmb) items in a container while having an item already selected.
Found in Sub-Editor 

Steps to Reproduce : 
Spawn a large steel cabinet, fill it with items, drag delete and let go of lmb or ctrl and it'll crash.

![Bug1](https://user-images.githubusercontent.com/72674994/96405010-e07c0b80-120e-11eb-88cb-cb825974b0de.png)
![Bug2](https://user-images.githubusercontent.com/72674994/96405024-e8d44680-120e-11eb-843b-9edb13a50a3b.png)

Version : [v0.10.6.2]
Additional Information : 
```
Exception: An item with the same key has already been added. Key: Barotrauma.InventorySlotItem (System.ArgumentException)
Target site: Void ThrowAddingDuplicateWithKeyArgumentException[T](T)
Stack trace: 
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Barotrauma.AddOrDeleteCommand.MergeInto(AddOrDeleteCommand master)
   at Barotrauma.SubEditorScreen.Update(Double deltaTime)
   at Barotrauma.GameMain.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Barotrauma.Program.Main(String[] args)
```

**Comment by Rokvach** [comment] 2020-10-19 08:19
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bb1b2bffd463b8dfb45234032c07f0eac4f3a497

Tested, wasn't able to reproduce the issue after the fix. Working correctly. Closing.

**Closed** 2020-10-19 08:19 UTC
Labels: Bug, Code, Crash

**Comment by 3e849f2e5c** [comment] 2020-10-19 08:21
This was caused because the bulk item command buffer is shared between deletions and additions and when the buffer was flushed it would try to merge together addition with deletion commands in this scenario. Fixed by differentiating when the buffer is used by deletions or additions and flushing the buffer when the usage changes before allowing the other to access it.
