### ISSUE TITLE
game freeze when opening server browser

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6511] opened 2021-08-28 21:25 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Game lags/ freezes for several seconds when opening the server browser and loading servers.

**Steps To Reproduce**
0. start barotrauma
1. open server browser

**Version**
0.14.9 and 0.15.000

**Additional information**
can't even alt tab QQ

**Comment by Regalis11** [comment] 2021-08-30 07:33
Happens when the game calculates the MD5 hashes of the content packages to check compatibility with the servers. Let's look into re-enabling caching the hashes after the modding refactor (https://github.com/Regalis11/Barotrauma-development/issues/2433) is done.

**Comment by soma99** [comment] 2021-10-15 10:20
Isn't this freezing problem caused by the main thread being used for the calculation? Wouldn't it be solved by giving the hash calculation to another thread?

**Comment by Calyxman** [comment] 2022-02-15 20:53
Regalis, the link you give here is dead.
https://github.com/Regalis11/Barotrauma-development/issues/2433
Leads to a 404. Why include it?

**Comment by Rokvach** [comment] 2022-04-07 20:50
Doesn't lag anymore, closing.

**Closed by Rokvach** 2022-04-07 20:50 UTC
Labels: Code, Performance, Low prio

**Comment by Kinrany** [comment] 2022-07-25 00:43
I'm having this problem, and this is the most recent related issue I could find. While the game is running, it gets worse every time I open the server browser.

Barotrauma: v0.18.15.0
OS: macOS Monterey 12.1, M1 chip
