### ISSUE TITLE
Crash to Desktop during a Round

### ISSUE THREAD

**Issue by Hanfalk** [Regalis11/Barotrauma#10128] opened 2022-10-20 11:59 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Hey, I have been currently experiencing crashes with Barotrauma for at least 3 days or more after the major expansion update.
All the crashes happen "mid-round", and I do not know when it crashes or not.

Running the games with no mods has no issues, but any mods that are quality-of-life content, such as LUA have given me only headaches.
I have reduced the mods to a minimum where it does not affect the game at all, but still crashes. And I have noticed that it is random for some people. Some can play with mods just fine, while others like me have crashes every time.
And the weirdest part of all time is that it affects Singeplayer and Multiplayer.

The weirdest part is that when the game crashes, I do not get a single crash.log until like yesterday (I just checked before writing this).
So here is the crash.log if anyone knows how to solve this! I would appreciate the help. :people_hugging: 

> Barotrauma Dedicated Server crash report (generated on 10/19/2022 23:53:49)
> 
> 
> Barotrauma seems to have crashed. Sorry for the inconvenience! 
> 
> 
> Game version 0.19.11.0 (ReleaseWindows, branch master, revision 8fef89a255)
> Language: English
> Selected content packages: Vanilla, Lua For Barotrauma, DynamicEuropa, BetterFabricatorUI, BetterHealthUI, Deep Containers
> Level seed: SeracMinos Linea
> Loaded submarine: Dugong (0B6D2044E576F1138E0230F109D98D39)
> Selected screen: Barotrauma.GameScreen
> Server (Round had started)
> 
> 
> System info:
>     Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
> 
> 
> Exception: Collection was modified; enumeration operation may not execute. (System.InvalidOperationException)
> Target site: Void ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
> Stack trace: 
>    at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
>    at Barotrauma.Networking.GameServer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Networking\GameServer.cs:line 592
>    at Barotrauma.GameMain.Run() in <DEV>\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 345
>    at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 87

This was the mods & load-order 3 days ago.
> > Mods & Load Order:
> > Lua For Barotrauma
> > CsForBarotrauma
> > Barotrauma Audio Overhaul (have placed it on top, no changes whatsoever)
> > Lua Audio Overhaul
> > Performance Fix
> > Lua O'Clock Radar (Jade Harley)
> > BetterHealthUi

> > BetterFabricatorUi
> > Deep Containers

Later on, I removed all the mods (yesterday) except Lua For Barotrauma, BetterHealthUi, BetterFabricatorUi, and Deep Containers for QoL features. And I still crash.

I have installed and re-installed mods three times, done a clean wipe of AppData, Workshop, and the main folder for Barotrauma with Verifying files as the last resort, and I am currently out of options to fix it myself atm.

### Reproduction steps

1 Start up the game

2 Add a few mods, such as the ones I have used. You can test with any mods such as Sound Overhaul, or try out with Lua by installing it (instructions in the Workshop). Any mods break the game. Deep Containers is a "chance" on when it crashes, but other mods are a guarantee on it always crashes during a round.

3 Play the round for a little bit, wait or let the game run without pausing, or progress halfway into the map (I am unsure if it is related to a creature spawning or anything in the world, but my crashes have always been from within 5 minutes to a maximum of 20 minutes during a round).

Mods I would recommend using to test as a baseline:
> > Lua For Barotrauma
> > BetterHealthUi
> > BetterFabricatorUi
> > Barotrauma Audio Overhaul (can be removed to then only test Lua)

Mods - Optional
> > Lua Audio Overhaul (if only testing Lua, remove this due to you are not using Barotrauma Audio Overhaul.)
> > Deep Containers

4 If it crashes, you get the error I had (to desktop).

Mods & Load Order:
> > Lua For Barotrauma
> > CsForBarotrauma
> > Barotrauma Audio Overhaul (have placed it on top, no changes whatsoever)
> > Lua Audio Overhaul
> > Performance Fix
> > Lua O'Clock Radar (Jade Harley)
> > BetterHealthUi
> > BetterFabricatorUi
> > Deep Containers

Note:
I have used a lot of mods in the past, and everything has been working great, this is just my first time having this much trouble.

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Dedicated Server crash report (generated on 10/19/2022 23:53:49)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


Game version 0.19.11.0 (ReleaseWindows, branch master, revision 8fef89a255)
Language: English
Selected content packages: Vanilla, Lua For Barotrauma, DynamicEuropa, BetterFabricatorUI, BetterHealthUI, Deep Containers
Level seed: SeracMinos Linea
Loaded submarine: Dugong (0B6D2044E576F1138E0230F109D98D39)
Selected screen: Barotrauma.GameScreen
Server (Round had started)


System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit


Exception: Collection was modified; enumeration operation may not execute. (System.InvalidOperationException)
Target site: Void ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
Stack trace: 
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Barotrauma.Networking.GameServer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Networking\GameServer.cs:line 592
   at Barotrauma.GameMain.Run() in <DEV>\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 345
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 87
```

**Comment by Regalis11** [comment] 2022-10-20 12:02
Duplicate of https://github.com/Regalis11/Barotrauma/issues/9298

**Closed by Regalis11** 2022-10-20 12:02 UTC
