### ISSUE TITLE
Incorrect hull breach of docking port

### ISSUE THREAD

**Issue by G-M-twostay** [Regalis11/Barotrauma#12091] opened 2023-05-28 15:21 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Undock and redocking a drone shows a hull breach at the docking port(not hatch, this is the horizonal one) of the drone. However, I didn't find any actual hull breach as there was no leak and using welding tool shows that all walls are full health. In addition, suppose both my drone and my sub has 2 docking ports/hatches, then if I use the other docking hatch of drone to dock to the other docking hatch of my sub(the docking ports are used for drone spawning), it will also show a hull breach at the docking port. In addition, it shows that my drone is docked to the docking port instead of the docking hatch.

This also happens with the vanillia remora.

### Reproduction steps

1. Open remora.
2. Click the test button.
3. Let bots turn on reactor.
4. go to drone control terminal.
5. undock the drone.
6. then dock the drone.
7. go to status monitor and find a hull breach.

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-05-28 15:36
Thank you for the report!

I unfortunately couldn't find a way to reproduce the issue. There seem to be no breaches displayed on the status monitor after docking:
![image](https://github.com/Regalis11/Barotrauma/assets/14351070/9c13945d-b850-4ad8-a70d-a612effe1dba)

I wonder if there could've been some damage to the drone or the submarine that's incorrectly displayed as a breach? Did you test this in the submarine editor the way you described, or did it occur during normal gameplay?

**Comment by G-M-twostay** [comment] 2023-05-29 02:21
![image](https://github.com/Regalis11/Barotrauma/assets/43040891/3b454a98-3f43-4918-a2af-f0a6f090aba8)
![image](https://github.com/Regalis11/Barotrauma/assets/43040891/14f38207-7f09-43a0-a00c-877bc0d939c7)

It first happened to me on my custom sub in campaign, then I went to the sub editor to test it. After also asking on the discord for help and didn't arrive at any conclusion, I went to the remora in sub editor and test it in the editor. What I did was that once the sub is powered, I go to drone terminal and click undock, then immediately click dock. This removes the chance that bad piloting by me let the drone crash into main sub. I also went out of the sub and try welding from outside, but none of the walls are displayed as damaged. Typing "fixwalls" in f3 commands also doesn't fix this issue. I retried today and still got the same result.

On my custom sub this is a random event, it happens 90% of the times I conduct the above procedure. On remora it always happens.

Just a guess, but how is hull breach calculated? If it were indicated based on water, then could it be the fact that when docking/undocking thru docking port, the door sometimes opens to fast and water will flow in for a short moment?

**Comment by Regalis11** [comment] 2023-06-03 09:20
Thank you for the extra info! I didn't realize you meant the red "hull breach" text (actually I didn't even remember that was a thing), not the red "blobs" that indicate the leaks on the status monitor. I'll take another look at this!

> Just a guess, but how is hull breach calculated? If it were indicated based on water, then could it be the fact that when docking/undocking thru docking port, the door sometimes opens to fast and water will flow in for a short moment?

It's not based on gaps, but water: the game counts the gaps in the hull leading from outside to inside.

**Comment by Regalis11** [comment] 2023-06-03 09:26
Managed to repro this now (looks like it does always happen in Remora, I just didn't look at the "hull breach" text). Fixed in https://github.com/Regalis11/Barotrauma-development/commit/351c280854336c394957db4d0a466bede1e96593 (commit in our private repo)

**Comment by G-M-twostay** [comment] 2023-06-03 13:48
Thank you. Also can you provide some sense on how this happened? I have a general idea on how the code works.

**Comment by Regalis11** [comment] 2023-06-05 07:34
Thank you for taking the time to close this, but we'll keep it open until we've tested the fix internally and verified it's working properly with no negative side-effects. :)

> Also can you provide some sense on how this happened?

The nav terminal calculated the number of gaps connected to the hull, and it seems docking the shuttle sometimes generated one unnecessary gap between the ports. This gap was fully inside a hull, and didn't do anything, but still counted as a breach on the nav terminal.

**Closed** 2023-06-07 12:22 UTC
Labels: Bug, Code, Low prio
