### ISSUE TITLE
Distant turrets (IE. shuttles) from main submarine do not update player cursor info/rotation while spectating

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#12022] opened 2023-05-17 06:54 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Noticed this testing another PR but seems unrelated to the PR's changes (specifically Fix/cursor-pos-desync commit https://github.com/Regalis11/Barotrauma-development/commit/74ee94dcf899573cb998fc87fffd0bbc995531e1).

It appears spectators do not update distant submarines turret rotation from the main sub (Possibly due to not being send cursor coordinates from the distant players?), despite they are things they may be spectating like shuttles where you may expect to see smoother updates of things.

This is specifically effecting spectates, not controllers of the turret or the main submarines turrets.

https://github.com/Regalis11/Barotrauma-development/assets/29177976/111f4bab-e83e-4e42-a9cc-257dbda8628d

### Reproduction steps

1. Host a server
2. Select sandbox
3. Choose submarine with shuttle and a turret attached to it via remote control.
4. At least one player must be a spectator (Preferably not the host)
5. move the shuttle at least 200m+ away from the main submarine
6. Note the turret only rotates if a player fires it when spectating it.

### Bug prevalence

Happens every now and then

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-05-22 17:41
The issue is actually the distance from the spectator to the character using the turret: the server doesn't send information about characters (or the positions of their cursors) to clients who are very far away from the character.

**Comment by Regalis11** [comment] 2023-05-26 16:20
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8fe84849b091b5f8f669340380e0ee7962515e19

Note that this didn't just affect spectators, but also clients controlling a character that's far away from the character operating the turret. For example, characters inside the far-away drone wouldn't see the turret move.

**Comment by NilanthAnimosus** [comment] 2023-06-01 12:01
Tested against Fix/misc-fixes-may25 commit https://github.com/Regalis11/Barotrauma-development/commit/460dcd1e2a4f1a832b19b061a8c000ce1151e3b9

Noted this works now, but there is a very notable (and very visible) delay in the updates of the cursor position for those far away players.

is it intentional to be between 1/2 second to 1 second delays? its enough that the turret can be firing its bullets in totally different (But correct) directions to the turret and causes jolts of movement and no movement that is highly noticeable.

**Comment by Regalis11** [comment] 2023-06-01 14:09
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/07c6c251f8b6f7c6a2bc72a0354a801492ef3e91

**Closed** 2023-06-01 15:14 UTC
Labels: Bug, Code, Networking
