### ISSUE TITLE
Missing conversion from float to Int causes crash.

### ISSUE THREAD

**Issue by DoomOfMax97** [Regalis11/Barotrauma#6162] opened 2021-06-23 23:29 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Missing conversion from float to Int when calling System.Math.Sign(..), in the Function EmitParticles(..) in Gap.cs.
While I used a mod/mods, this crash seems to be caused by the base game.
Mods used:
[Project-705k Lyra](https://steamcommunity.com/sharedfiles/filedetails/?id=2445826783)
[Defibrillator](https://steamcommunity.com/sharedfiles/filedetails/?id=2414505475)

**Steps To Reproduce**
I crashed the submarine "Project-705k Lyra v1.01.00" a bunch of times at high speed,
I was able to trigger the error twice within 10-15 mins.

**Version**
Game version 0.14.6.0 (ReleaseWindows, branch release, revision 12d7084c07)
Operating system: Microsoft Windows NT 10.0.19042.0 64 bit

**Additional information**
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/6705333/crashreport.2.log)
`Exception: Function does not accept floating point Not-a-Number values. (System.ArithmeticException)
Target site: Int32 Sign(Single)
Stack trace: 
   at System.Math.Sign(Single value)
   at Barotrauma.Gap.EmitParticles(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\Gap.cs:line 138
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 550
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 270
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 962
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59`

**Comment by DoomOfMax97** [comment] 2021-06-29 02:04
After adding this bit before the line (pos.X += Math.Sign(flowForce.X;):
`if (float.IsNaN(flowForce.X))
{
         flowForce.X = 0;
         SoundPlayer.PlayUISound(GUISoundType.RadioMessage);
} `

I get this error (probably caused by an under- or overflow, or a stuck loop) after a while (maybe like ~1min?):

`Exception: Index was outside the bounds of the array. (System.IndexOutOfRangeException)
Target site: Void UpdateWaterFlowSounds(Single)
Stack trace: 
   at Barotrauma.SoundPlayer.UpdateWaterFlowSounds(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sounds\SoundPlayer.cs:line 562
   at Barotrauma.SoundPlayer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sounds\SoundPlayer.cs:line 436
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 868
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 654
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59`

**Comment by DoomOfMax97** [comment] 2021-06-29 23:10
For context:
![image](https://user-images.githubusercontent.com/5787957/123878737-f914f780-d93f-11eb-9fbd-d466d4b5c492.png)

**Comment by DoomOfMax97** [comment] 2021-06-29 23:25
(Some) values in Gap.cs at the time of the crash:
pos = Vector2
 DebugDisplayString = {string} "-51475,5  114752"
 X = {float} -51475.5
 Y = {float} 114752
this.ConnectedWall.Prefab.DecorativeSprites = List<DecorativeSprite>
$exception = {ArithmeticException} System.ArithmeticException: Function does not accept floating point Not-a-Number values.\r\n   at System.Math.Sign(Single value)\r\n   at Barotrauma.Gap.EmitParticles(Single deltaTime) in N:\Barotrauma-master\Barotrauma\BarotraumaClient\ClientSource\Map\Gap.cs:line 139\r\n   at Barotrauma.Gap.Update(Single deltaTime, Camera cam) in N:\Barotrauma-master\Barotrauma\BarotraumaShared\SharedSource\Map\Gap.cs:line 330\r\n   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in N:\Barotrauma-master\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 550\r\n   at Barotrauma.GameScreen.Update(Double deltaTime) in N:\Barotrauma-master\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 270\r\n   at Barotrauma.GameMain.Update(GameTime gameTime) in N:\Barotrauma-master\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 966\r\n   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in N:\Barotrauma-master\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Ga…
this = Gap
 base = MapEntity
 ConnectedDoor = {Door} null
 ConnectedWall = {Structure} {Bodies: Count = 1}
  Bodies = {List<Body>} Count = 1
  base = MapEntity
  BodyHeight = {float} 208
  BodyOffset = {Vector2} 0  0
  BodyRotation = {float} 0
  BodyWidth = {float} 47.5
  CastShadow = {bool} true
  CrushDepth = {float} 3500
  DefaultRect = {Rectangle} -1525  -48  98  208
  DrawBelowWater = {bool} true
  DrawDamageEffect = {bool} true
  DrawOverWater = {bool} false
  DropShadowOffset = {Vector2} 0  0
  HasBody = {bool} true
  HasDamage = {bool} false
  Health = {float} 0
  Indestructible = {bool} false
  IsHorizontal = {bool} false
  IsPlatform = {bool} false
  MaxHealth = {float} 0
  Name = {string} "Heavy Door"
  NoAITarget = {bool} false
  Prefab = StructurePrefab
  Rect = {Rectangle} -51525  114952  98  208
  Scale = {float} 0.5
  SectionCount = {int} 3
  Sections = {WallSection[]} WallSection[3]
  SelectableInEditor = {bool} true
  SerializableProperties = {Dictionary<string, SerializableProperty>} Count = 66
  SpecialTag = {string} ""
  Sprite = {Sprite} Content/Map/Outposts/Art/TunnelWalls.png: {X:4 Y:1627 Width:197 Height:417}
  SpriteColor = {Color} 255  255  255  255
  SpriteEffects = {SpriteEffects} None
  StairDirection = {Direction} None
  Tags = {HashSet<string>} Count = 2
  TextureOffset = {Vector2} 0  0
  TextureScale = {Vector2} 1  1
  UseDropShadow = {bool} false
  bodyDebugDimensions = {List<Vector2>} Count = 1
  convexHulls = {List<ConvexHull>} Count = 0
  crushDepth = {float} 3500
  defaultRect = {Rectangle} -1525  -48  98  208
  maxHealth = {float} 0
  scale = {float} 0.5
  spriteAnimState = {Dictionary<DecorativeSprite, DecorativeSprite.State>} Count = 0
  spriteColor = {Color} 255  255  255  255
  textureOffset = {Vector2} 0  0
  textureScale = {Vector2} 1  1
 DisableHullRechecks = {bool} false
 FlowTargetHull = Hull
 IsHorizontal = {bool} true
 IsRoomToRoom = {bool} true
 LerpedFlowForce = {Vector2} NaN  0
 Name = {string} "Gap"
 Open = {float} NaN
 PassAmbientLight = {bool} false
 Rect = {Rectangle} -51509  114770  67  36
 SelectableInEditor = {bool} false
 Size = {float} 36
 connectedDoor = {Door} null
 flowForce = {Vector2} NaN  0
 flowTargetHull = Hull
 higherSurface = {float} 114713.844
 lerpedFlowForce = {Vector2} NaN  0
 lowerSurface = {float} 114712
 open = {float} NaN
 openedTimer = {float} -90.9549484
 outsideColliderRaycastTimer = {float} -91.955162
 outsideCollisionBlocker = Body
 particleTimer = {float} 0
deltaTime = {float} 0.0166666675
hull1 = Hull
 base = MapEntity
 AmbientLight = {Color} 0  0  0  0
 AvoidStaying = {bool} false
 BackgroundSections = {List<BackgroundSection>} Count = 84
 BallastFlora = {BallastFloraBehavior} null
 CeilingHeight = {float} 208.007813
 ConnectedGaps = {List<Gap>} Count = 5
  [0] = Gap
  [1] = Gap
  [2] = Gap
  [3] = Gap
  [4] = Gap
 DisplayName = {string} "Engine room"
 DrawBelowWater = {bool} false
 DrawOverWater = {bool} true
 DrawSurface = {float} 114712
 FakeFireSources = {List<DummyFireSource>} Count = 0
 FireSources = {List<FireSource>} Count = 0
 ForceAsWetRoom = {bool} false
 IsWetRoom = {bool} false
 LethalPressure = {float} 0
 Linkable = {bool} true
 Name = {string} "Hull"
 OriginalAmbientLight = {Color?} null
 OutpostModuleTags = {HashSet<string>} Count = 0
 Oxygen = {float} 21503.6094
 OxygenPercentage = {float} 99.9981842
 Pressure = {float} 114712
 Rect = {Rectangle} -51536  115048  64  336
 RoomName = {string} "roomname.engineroom"
 SelectableInEditor = {bool} false
 SerializableProperties = {Dictionary<string, SerializableProperty>} Count = 63
 Size = {Vector2} 64  336
 SupportsPaintedColors = {bool} true
 Surface = {float} 114712
 Visible = {bool} true
 Volume = {float} 21504
 WaterPercentage = {float} 0
 WaterVolume = {float} 0
 WaveVel = {float[]} float[3]
 WaveY = {float[]} float[3]
 WorldSurface = {float} 95029.7266
 adjacentHulls = {HashSet<Hull>} Count = 0
 ambientLight = {Color} 0  0  0  0
 avoidStaying = {bool} false
 decals = {List<Decal>} Count = 0
 dirtiedVolume = {float} 0
 drawSurface = {float} 114712
 isWetRoom = {bool} false
 lastAmbientLightEditTime = {double} 0
 leftDelta = {float[]} float[3]
 lethalPressure = {float} 0
 minimumPaintAmountToDraw = {float} 0.00833333284
 moduleTags = {HashSet<string>} Count = 0
 networkUpdatePending = {bool} false
 networkUpdateTimer = {float} 0
 oxygen = {float} 21503.6094
 paintAmount = {float} 0
 pendingDecalUpdates = {HashSet<Decal>} Count = 0
 pendingSectionUpdates = {HashSet<int>} Count = 0
 pressure = {float} 114712
 properties = {Dictionary<string, SerializableProperty>} Count = 63
 remoteBackgroundSections = {List<BackgroundSection>} Count = 0
 remoteDecals = {List<Hull.RemoteDecal>} Count = 0
 remoteFireSources = {List<Vector3>} null
 remoteOxygenPercentage = {float} 99.6078415
 remoteWaterVolume = {float} 0
 rightDelta = {float[]} float[3]
 roomName = {string} "roomname.engineroom"
 serverUpdateDelay = {float} -91.955162
 submergedSections = {List<BackgroundSection>} Count = 0
 surface = {float} 114712
 update = {bool} false
 waterVolume = {float} 0
 waveVel = {float[]} float[3]
 waveY = {float[]} float[3]
 xBackgroundMax = {int} 4
 yBackgroundMax = {int} 21
hull2 = Hull
 base = MapEntity
 AmbientLight = {Color} 0  0  0  0
 AvoidStaying = {bool} false
 BackgroundSections = {List<BackgroundSection>} Count = 1188
 BallastFlora = {BallastFloraBehavior} null
 CeilingHeight = {float} 533.044434
 ConnectedGaps = {List<Gap>} Count = 8
 DisplayName = {string} "Reactor room"
 DrawBelowWater = {bool} false
 DrawOverWater = {bool} true
 DrawSurface = {float} 114713.844
 FakeFireSources = {List<DummyFireSource>} Count = 0
 FireSources = {List<FireSource>} Count = 0
 ForceAsWetRoom = {bool} false
 IsWetRoom = {bool} false
 LethalPressure = {float} 0
 Linkable = {bool} true
 Name = {string} "Hull"
 OriginalAmbientLight = {Color?} null
 OutpostModuleTags = {HashSet<string>} Count = 0
 Oxygen = {float} 304122.5
 OxygenPercentage = {float} 99.9981918
 Pressure = {float} 114718.031
 Rect = {Rectangle} -51472  115288  528  576
 RoomName = {string} "roomname.reactorroom"
 SelectableInEditor = {bool} false
 SerializableProperties = {Dictionary<string, SerializableProperty>} Count = 63
 Size = {Vector2} 528  576
 SupportsPaintedColors = {bool} true
 Surface = {float} 114713.844
 Visible = {bool} true
 Volume = {float} 304128
 WaterPercentage = {float} 1.04730618
 WaterVolume = {float} 3185.15161
 WaveVel = {float[]} float[18]
 WaveY = {float[]} float[18]
 WorldSurface = {float} 95031.5703
 adjacentHulls = {HashSet<Hull>} Count = 6
 ambientLight = {Color} 0  0  0  0
 avoidStaying = {bool} false
 decals = {List<Decal>} Count = 0
 dirtiedVolume = {float} 0
 drawSurface = {float} 114713.844
 isWetRoom = {bool} false
 lastAmbientLightEditTime = {double} 0
 leftDelta = {float[]} float[18]
 lethalPressure = {float} 0
 minimumPaintAmountToDraw = {float} 0.000589225558
 moduleTags = {HashSet<string>} Count = 0
 networkUpdatePending = {bool} false
 networkUpdateTimer = {float} 0
 oxygen = {float} 304122.5
 paintAmount = {float} 0
 pendingDecalUpdates = {HashSet<Decal>} Count = 0
 pendingSectionUpdates = {HashSet<int>} Count = 0
 pressure = {float} 114718.031
 properties = {Dictionary<string, SerializableProperty>} Count = 63
 remoteBackgroundSections = {List<BackgroundSection>} Count = 0
 remoteDecals = {List<Hull.RemoteDecal>} Count = 0
 remoteFireSources = {List<Vector3>} null
 remoteOxygenPercentage = {float} 100
 remoteWaterVolume = {float} 0
 rightDelta = {float[]} float[18]
 roomName = {string} "roomname.reactorroom"
 serverUpdateDelay = {float} -91.955162
 submergedSections = {List<BackgroundSection>} Count = 0
 surface = {float} 114713.844
 update = {bool} true
 waterVolume = {float} 3185.15161
 waveVel = {float[]} float[18]
 waveY = {float[]} float[18]
 xBackgroundMax = {int} 33
 yBackgroundMax = {int} 36
particleAmountMultiplier = {float} 0
pos = {Vector2} -51475,5  114752

**Comment by DoomOfMax97** [comment] 2021-06-29 23:33
The crash can reliably be reproduced by shooting at the wall in the blue circle, then water will flow through the thing where the red arrow is pointing at, then after a few seconds the game will crash.
![Crash2](https://user-images.githubusercontent.com/5787957/123880517-1eefcb80-d943-11eb-810a-2d94400ce89c.jpg)

**Comment by DoomOfMax97** [comment] 2021-06-30 17:15
Update: The issue was a heavy door with 0 max hp.

**Comment by Regalis11** [comment] 2021-07-05 17:07
Thank you for a very detailed report, this info made the issue really quick to diagnose. The problem was this line in Structure.cs that calculates how "open" the gap is based on the health of the structure:

`float gapOpen = (damage / MaxHealth - LeakThreshold) * (1.0f / (1.0f - LeakThreshold));`

A maximum health of 0 would lead to the Open-value being set to NaN, which would lead to the crash when the game tries to spawn particles from the gap. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/55b4337b8167cf59d34eb27cfa5a2966e1fd4e4d

**Comment by DoomOfMax97** [comment] 2021-07-06 14:07
Nice, glad I could help :)

**Comment by Rokvach** [comment] 2021-07-28 10:35
Tested, wasn't able to reproduce. Seems to be working correctly. Closing.

**Closed by Rokvach** 2021-07-28 10:35 UTC
Labels: Bug, Code, Crash
