### ISSUE TITLE
Bots - Crewmates suffocate in diving suits while trying to reach objectives

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#3333] opened 2020-07-09 14:57 UTC
**Description**
I have recorded a couple of instances with debugai where bots suffocate in their diving suits while trying to do some other objectives.

Here: https://medal.tv/clips/28199575/d1337omjlgEH
-bot on top right has rescue (100) obejctive, but nobody is in need of rescue
-bot on bottom left tries to repairitem (69) but he wont go and fix it, he twitches in 1 place
-conditions: O2 in cabinets all over the place, suits both in locker and on ground
In this clip:https://medal.tv/clips/28198432/d1337Xr7lMEJ
-bot collapses at 0:48
-Im not sure what the bot is trying to accomplish, unfortunately, but he suffocates in the suit
-conditions: same, except only suits in diving suit locker (no suits on ground)

**Steps To Reproduce**
-spawn with Orca with bots
-cause explosion 300 300 300 300 on different hull pieces
-order all bots to repair leaks
-observe their behaviour
**Version**
Unstable
**Additional information**
It's a major pain in the ass in the campaign to use cheats every time bot decides to suffocate in the suit. Sometimes it all works properly and they will drop or return the suit, but a lot of times, they just plomp on the ground unconcious.

**Comment by CurePindal** [comment] 2020-07-10 16:18
(Multiplayer campaign, 0.10.4 unstable)
Just had a bot suffocating in a diving suit without any danger around any longer. 
Sub was fixed for a couple of minutes. Bot was still wearing the suit and suffocated when the suit oxy ran out

**Comment by Rokvach** [comment] 2020-08-05 09:39
Tested this a bit further on the dev branch which should have more AI fixes. The issue wasn't as simple to reproduce as it was on the current stable version of the game. But I was still able to suffocate all of my bots

Repro steps:
1. Tell engineer to turn off the reactor
2- Use Explosion 100 100 100 100 on every cabinet which contains oxygen tanks
3. Use water command to flood all the rooms
4. Let rooms drain and check if bots returns the diving suits
5. Repeat until their suits are close to running out of oxygen
6. Notice that they wont take their suits off if the room contains water, even tho they are suffocating to the suits, looks like the room has to be at certain % drained before they decide to take their suits off. In my test the room was around 50% flooded and the bot didn't take hes suit off.

**Comment by itchyOwl** [comment] 2020-08-06 09:07
Should be fixed in Regalis11/Barotrauma-development@4e21f52.

**Comment by Rokvach** [comment] 2020-08-06 09:53
Tested, wasn't able to reproduce the issue anymore. Working correctly. Closing.

**Comment by Udrakan** [comment] 2021-06-10 22:39
Requesting a re-open. This keeps happening to me and this time I managed to record it.
I'm using 1 mod - ITA. The captain job or human is not modified. Diving suit or containers are not modified:

https://user-images.githubusercontent.com/59519434/121605888-7938f300-ca4d-11eb-9977-ec3a683c035c.mp4

![image](https://user-images.githubusercontent.com/59519434/121605909-80f89780-ca4d-11eb-9656-0b6e8dfe04b9.png)

**Comment by Rokvach** [comment] 2021-06-10 22:42
Re-opening and moving to Misc

**Comment by itchyOwl** [comment] 2021-07-06 10:29
Found and fixed two edge cases:
- Bots incorrectly prioritized the find safety objective when they needed diving gear but didn't need a suit and when they had a suit instead of a mask (e.g. low oxygen, no water/breach). Fixed in Regalis/Barotrauma-development@b86d79a.
- Bots got stuck dropping and picking up a diving suit when the suit didn't have any oxygen left and if no other diving gear could be found. Fixed in Regalis/Barotrauma-development@ccbf829. To repro this, you'll need to have more than 0% oxygen and less than 30% oxygen in the room and no other diving gear in the sub that can be used.

I don't think I managed to reproduce the same issue as in the video, because in the video it seems that the bot suffocates while wearing a suit and standing near the diving gear cabinet, which should have plenty of oxygen sources to be used. Having an active wait command shouldn't affect the find safety objective, and I couldn't find any issues with it.

So, we'll need more testing for this.

**Comment by tim-win** [comment] 2021-07-20 17:45
Easy bug reproduction in the latest version by putting a suit on a bot, and giving them the "wait" command. The bot will eat through any oxygen tanks in their inventory and then suffocate in their suit, regardless of whether they are near oxygen sources or _hanging around in an oxygen filled sub_.

I regularly lose bots by setting 2-3 on wait during a complex multi-bot action in single player, and whichever one was wearing a suit eventually suffocates when his 8 stack of o2 cans run out (despite being sitting at the helm, in engineering, walking around a colony, etc).

**Comment by itchyOwl** [comment] 2021-08-02 08:37
I probably didn't test the wait order properly. Thanks for the steps. Easy to reproduce and fix an obvious logic error. Should be fixed in Regalis11/Barotrauma-development@3b47f46.

**Comment by Rokvach** [comment] 2021-08-04 07:15
Tested, working correctly. Closing.

**Closed by Rokvach** 2021-08-04 07:15 UTC
Labels: Bug, Code
