### ISSUE TITLE
Multiplayer Spineling crash

### ISSUE THREAD

**Issue by dumbabbler** [Regalis11/Barotrauma#10828] opened 2022-12-26 21:02 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When getting close to a Spineling, the server crashes

### Reproduction steps

1. Start a multiplayer campain
2. Select a spineling mission or an area with spinelings
3. Drive close to the Spinelings (e.g. to fight them)
4. Crash

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Dedicated Server crash report (generated on 12/26/2022 21:36:52)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


Game version 0.20.16.1 (ReleaseWindows, branch release, revision 33a42adf77)
Language: English
Selected content packages: Vanilla
Level seed: Sarpedon LineaUdaeus Linea
Loaded submarine: Dugong (218994F4246FDAAD0F27D3B67912D407)
Selected screen: Barotrauma.GameScreen
Server (Round had started)


System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit


Exception: Component event creation failed: Projectile.ValidateEventData returned false (System.Exception)
Target site: Void CreateServerEvent[T](T, IEventData)
Stack trace: 
   at Barotrauma.Item.CreateServerEvent[T](T ic, IEventData extraData) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Items\Item.cs:line 381
   at Barotrauma.Items.Components.Projectile.Shoot(Character user, Vector2 weaponPos, Vector2 spawnPos, Single rotation, List`1 ignoredBodies, Boolean createNetworkEvent, Single damageMultiplier, Single launchImpulseModifier) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Projectile.cs:line 355
   at Barotrauma.StatusEffect.<>c__DisplayClass104_6.<Apply>b__8(Item newItem) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\StatusEffects\StatusEffect.cs:line 1861
   at Barotrauma.EntitySpawner.Update(Boolean createNetworkEvents) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\EntitySpawner.cs:line 422
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 611
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 256
   at Barotrauma.GameMain.Run() in <DEV>\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 325
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 78


Last debug messages:
   12/26/2022 21:36:52 - [12/26/2022 21:36:52]
  Saving banlist
   12/26/2022 21:36:49 - [12/26/2022 21:36:49]
  maklotz launched Pulse Laser (projectile: Pulse Laser Bolt)
   12/26/2022 21:36:49 - [12/26/2022 21:36:49]
  Mudraptor attacked by maklotz. Deep tissue injury: 40 Stun: 0.5
   12/26/2022 21:36:49 - [12/26/2022 21:36:49]
  Mudraptor has died (Cause of death: Deep tissue injury)
   12/26/2022 21:36:48 - [12/26/2022 21:36:48]
  maklotz launched Pulse Laser (projectile: Pulse Laser Bolt)
   12/26/2022 21:36:48 - [12/26/2022 21:36:48]
  Mudraptor attacked by maklotz. Deep tissue injury: 22 Stun: 0.5
   12/26/2022 21:36:47 - [12/26/2022 21:36:47]
  maklotz launched Pulse Laser (projectile: Pulse Laser Bolt)
   12/26/2022 21:36:47 - [12/26/2022 21:36:47]
  Mudraptor attacked by maklotz. Deep tissue injury: 22 Stun: 0.5
   12/26/2022 21:36:45 - [12/26/2022 21:36:45]
  Outer wall breached by Mudraptor
   12/26/2022 21:36:44 - [12/26/2022 21:36:44]
  Scotty picked up Oxygen Tank
   12/26/2022 21:36:13 - [12/26/2022 21:36:13]
  Scotty set the value "LightColor" of the item "Emergency Light" to "255,0,21,133".
   12/26/2022 21:36:11 - [12/26/2022 21:36:11]
  Scotty set the value "LightColor" of the item "Emergency Light" to "255,0,21,133".
   12/26/2022 21:35:58 - [12/26/2022 21:35:58]
  Scotty set the value "LightColor" of the item "Emergency Light" to "255,199,21,133".
   12/26/2022 21:35:55 - [12/26/2022 21:35:55]
  Scotty set the value "LightColor" of the item "Emergency Light" to "255,199,21,0".
```

**Comment by Regalis11** [comment] 2022-12-27 12:31
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10826

**Closed by Regalis11** 2022-12-27 12:31 UTC
