### ISSUE TITLE
[0.1003.0] Purchasing upgrades, Marks refunded.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3098] opened 2020-06-15 13:50 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
This was in Multiplayer.
I was purchased some Fuel Consumption upgrades. Went to sell stuff to the merchants so that I can make some money back. Went to purchase more Fuel Consumption upgrades. Everytime I purchased, The Marks number went down for a split second and went back up. Infact I get more Marks every time.

Once I bought even more upgrades, this was showing up on the dedicated console:
![Capture](https://user-images.githubusercontent.com/5086682/84665562-f63e9480-aeed-11ea-8ab3-3048cf9ace6d.PNG)

**Version**
0.1003.0

**Comment by 3e849f2e5c** [comment] 2020-06-16 10:11
This is less caused by the upgrades and more caused by the store's netcode. Currently in multiplayer the server will keep selling already sold items every campaign message which is the main thing used to sync data between the client and the server in campaign. I think I've fixed this particular issue in https://github.com/Regalis11/Barotrauma-development/commit/416f7bde38afef2c6ccba986a35ce56f5de0922b but I'm not too familiar with the store's code.

Steps to reproduce:
1. Sell items to the store at least worth X
2. Buy an upgrade worth less than X
3. The server processes the transaction but also attempts to sell the items again giving you more credits than what you spent.

**Comment by Rokvach** [comment] 2020-06-22 03:03
Tested, wasn't able to reproduce, seems to be working correctly. Closing.

**Closed by Rokvach** 2020-06-22 03:03 UTC
Labels: Bug, Code, Networking
