### ISSUE TITLE
Server crash with System.NullReferenceException at Barotrauma.Items.Components.RangedWeapon.get_TransformedBarrelPos()

### ISSUE THREAD

**Issue by Paragonid** [Regalis11/Barotrauma#7078] opened 2021-10-29 18:33 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Local vanilla server crashed with an exception "Object reference not set to an instance of an object. (System.NullReferenceException)" during a campaign mission at Barotrauma.Items.Components.RangedWeapon.get_TransformedBarrelPos() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Holdable\RangedWeapon.cs:line 78.

**Steps To Reproduce**
Unknown

**Version**
0.15.12.0 (ReleaseWindows, branch release, revision 575e12eab6)
Microsoft Windows NT 10.0.19042.0 64 bit

**Additional information**
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/7444215/crashreport.log)

**Comment by Regalis11** [comment] 2021-11-01 08:15
Duplicate of https://github.com/regalis11/barotrauma/issues/7020

**Closed by Regalis11** 2021-11-01 08:15 UTC
Labels: Bug, Code, Crash
