### ISSUE TITLE
Absurdly large clientpermissions.xml file causing server crash on players connection

### ISSUE THREAD

**Issue by IConnC** [Regalis11/Barotrauma#8962] opened 2022-04-25 01:01 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The bug is specifically an error trying to join a dedicated server. Upon investigation I found out that the clientpermissions.xml file was 25 mb large (Attached Below). It seemed that every player listed in clientpermissions.xml had around 1244942 lines of permissions all of which were duplicates.

**Steps To Reproduce**
I have no clue what caused this but I didn't know where else to put this bug. I am able to provide logs if desired.

**Version**
This issue happened on a Linux Dedicated Server installation on version 0.17.12.0

**Additional information**
[bannedplayers.txt](https://github.com/Regalis11/Barotrauma/files/8550903/bannedplayers.txt)
[clientpermissions.txt](https://github.com/Regalis11/Barotrauma/files/8550904/clientpermissions.txt)
[forbiddenwordlist.txt](https://github.com/Regalis11/Barotrauma/files/8550905/forbiddenwordlist.txt)
[karmasettings.txt](https://github.com/Regalis11/Barotrauma/files/8550906/karmasettings.txt)
[permissionpresets.txt](https://github.com/Regalis11/Barotrauma/files/8550907/permissionpresets.txt)
[latest.log](https://github.com/Regalis11/Barotrauma/files/8550908/latest.log)

**Comment by Regalis11** [comment] 2022-04-25 07:07
Duplicate of https://github.com/Regalis11/Barotrauma/issues/8933

**Closed by Regalis11** 2022-04-25 07:07 UTC
