### ISSUE TITLE
Missing secondary confirmation for button "server lobby".

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#9977] opened 2022-10-04 07:43 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This happened repeatedly.
When we finished missions at late night and one of the admins wants to quit the game for rest. He might misclick the "server lobby" button which causes all the progress being wasted.

### Reproduction steps

1. Start a multiplayer campaign.
2. Click the "server lobby" in ESC menu
3. No warning or confirmation dialog is shown. The game session ends immediately.

### Bug prevalence

Happens every time I play

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-10-09 15:12
Thank you for the report! I'm afraid I could not find a way to reproduce this. The confirmation prompt seems to always pop up when clicking "server lobby", regardless of the game mode:
![image](https://user-images.githubusercontent.com/14351070/194764514-2e5ba1a9-f544-49c7-ad72-89296b78711b.png)

So I think this requires some more specific situation to occur, but I wasn't able to figure out what that could be yet.

**Comment by BiffW** [comment] 2022-10-09 15:19
> Thank you for the report! I'm afraid I could not find a way to reproduce this. The confirmation prompt seems to always pop up when clicking "server lobby", regardless of the game mode: ![image](https://user-images.githubusercontent.com/14351070/194764514-2e5ba1a9-f544-49c7-ad72-89296b78711b.png)
> 
> So I think this requires some more specific situation to occur, but I wasn't able to figure out what that could be yet.

I remember there was a period of time there's no secondary confirmation for this button. Is it added in 0.19? If so, you can close this issue. Thank you.

**Comment by Regalis11** [comment] 2022-10-09 16:49
This prompt should have been there in v0.18 as well, although it could be there was some issue in that version that prevented it from showing in some situation. Regardless, since the prompt seems to be working with no issues in 0.19, I think we can close this and reopen if we find a way to get the issue to occur.

**Closed by Regalis11** 2022-10-09 16:49 UTC
Labels: Bug, Need more info, Code
