### ISSUE TITLE
[Factions] Infinite marks glitch when you have the Mailman talent and view a cargo mission on the map

### ISSUE THREAD

**Issue by Traumatic-apricot** [Regalis11/Barotrauma#11210] opened 2023-02-11 05:43 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

after a long series of events on a station where any could be the issue i got on my sub to leave opened the map (no marks given) then selected Arnthor mine. i then hear the marks gain sound and see that 150 have been given to me but with no messages in chat of anything happing i just go back to the map and then i get another 150mk i can keep going in the map and i have gotten from 1k to 10k so i think it is inf.
save file: [bug moment.zip](https://github.com/Regalis11/Barotrauma/files/10712715/bug.moment.zip)
images showing duped money:
![20230211151145_1](https://user-images.githubusercontent.com/123396519/218242197-21184900-5529-4038-a2dc-0d7966cfce66.jpg)
![image](https://user-images.githubusercontent.com/123396519/218242170-b124fdd8-bc05-4b24-a9fa-d374e2aa1f2d.png)
![20230211153109_1](https://user-images.githubusercontent.com/123396519/218242180-0388249f-756c-4c63-bd39-6524e8680d1c.jpg)
![20230211151236_1](https://user-images.githubusercontent.com/123396519/218242183-84aae479-6bc1-40ec-9b40-b58d3fe495b9.jpg)
![20230211151149_1](https://user-images.githubusercontent.com/123396519/218242184-5e3992f4-fc07-4255-9ac1-7bdb74a140dd.jpg)
Now the rep steps witch are gonna be long

### Reproduction steps

1. load savefile
2.  go on the station talk to victoria and have her join the crew
3. then talk to the jestmaster and get to the point where he asks you to get him a special clown mask 
4. get all missions from the manager
5. buy some ship upgrades and all of the railgun shells they have along with two crew members and a large amount of crafting resources 
6. go on the ship open the map switch it to the mine and get inf marks by then closing and opening the map you can do this as quick as you would like
7. check you marks in the infotab (sorry for the long Reproduction its just bad timing to get this when i did this much at a station)

### Bug prevalence

Just once

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
nope sorry for long report
```

**Comment by Traumatic-apricot** [comment] 2023-02-11 10:44
a few notes on this issue it still happens hafter you have moved outposts and after a full game restart

**Comment by Regalis11** [comment] 2023-02-11 11:36
Thank you for the report! 
It seems this is caused by the combination of the cargo missions and the Mailman talent. When you select a connection with a cargo mission, the game calculates the final reward for the mission, taking any talent bonuses into account, but it seems this is currently bugged in a way that triggers the Mailman talent and causes you to get the 150 mk bonus from completing a cargo mission.

**Comment by Regalis11** [comment] 2023-02-11 11:51
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/fd43e410503f5b1ce2af4cb214748bb4c4d1ce71 (link to our private repo)

**Comment by Regalis11** [comment] 2023-02-11 11:57
Also noticed another issue while testing that save: it seems missions that are available from the destination location to some other location are listed "outpost missions" in the campaign map's mission selection. Fixed that in https://github.com/Regalis11/Barotrauma-development/commit/8807eead4cbb62eddb5910929f25108a30b63bb7

**Comment by Rokvach** [comment] 2023-02-14 10:15
Tested, working correctly. Can be merged and closed.

**Closed by Rokvach** 2023-02-14 10:15 UTC
Labels: Bug, Code, Severe
