### ISSUE TITLE
Atan component highly inconsistent

### ISSUE THREAD

**Issue by box-admiral** [Regalis11/Barotrauma#2268] opened 2020-02-12 01:21 UTC
I am attempting to use an atan component (specifically, the atan2 function of the component) to aim a railgun using motion sensors. Two decision tree arrays that are confirmed to work through text displays provides an integer value to the x and y input pins of the atan component. The resulting value is... very often nothing. No value is provided on a text display connected directly to the output of the atan component. I have occasionally seen output, but which has been plagued with inconsistent results.

This leads me to believe there is at least one problem with the atan component and potentially other similar components - when supplying a differing X value while keeping the Y value the same, the output of the atan component did not change. This seems like the atan component does not recalculate unless the Y component changes. Whether other multiple-input components also have this issue I do not know. I also do not know why sometimes there was a complete lack of output from the component in some cases. Sorry to have so little information.

**Comment by Regalis11** [comment] 2020-03-31 10:51
Are you sending a continuous signal to both of the inputs? Both of the connections need to receive a signal: if you just output a value to signal_in_y once and then modify the x value, the component will output nothing.

**Comment by BxFS** [comment] 2020-09-10 03:56
I've been working on a similar motion sensor aimed coilgun, and encountered similar problems: atan2 works perfectly for one gun, but any tinkering breaks it, not even copy-pasting which breaks the atan component and makes the output null. Interestingly, switching x and y for the atan component makes it start outputting again, albeit not exactly the angle I need. I also confirmed the signal to both inputs are continuous signals of integers with indicator lights and displays.

**Comment by KalinaWildfire** [comment] 2020-10-16 14:03
The "issue" with ATAN is that this component resets its inputs to NaN on each Update() call. ATAN only outputs upon receiving a signal_y. So this is where signal order matters to produce any signal even if inputs are continuous.

Here's an example,
The update order is as follow: mem, atan, mem
This is what happens:  mem X output> atan Update() > Atan resets both inputs to NaN > mem y outputs > Atan cannot produce an output cuz it's missing an input (one being NaN). This cycle repeats (note that x_input CANNOT produce an output. It needs a Y input). see how we are stuck in an infinite NaN loop?

However, if update order is as follow: mem, mem, atan, then we DO NOT have this issue

In practice: you can't keep track of every order ID but this simply means you always put the ATAN AT THE VERY END of the entire circuit responsible for the input.

**Comment by Regalis11** [comment] 2020-10-26 11:30
Thank you for the extra info, I was finally able to repro and fix this! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/52ec7ef9a027cc10c7145801d318435840f30a22

**Comment by Udrakan** [comment] 2020-10-31 13:48
I tried simple setup, seems to work as intended for a couple values.
![image](https://user-images.githubusercontent.com/59519434/97780920-09de5500-1b88-11eb-98ad-a31148382075.png)

**Comment by Working-Joe** [comment] 2020-10-31 13:49
Tried all possible update orders, works very consistently now :)
![image](https://user-images.githubusercontent.com/50582661/97780945-32664f00-1b88-11eb-83cc-27f0f0a4f1d0.png)

**Comment by Rokvach** [comment] 2020-10-31 14:36
Closing.

**Closed by Rokvach** 2020-10-31 14:36 UTC
Labels: Bug, Code
