### ISSUE TITLE
Just crush report

### ISSUE THREAD

**Issue by pavel4win** [Regalis11/Barotrauma#11742] opened 2023-04-04 09:05 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

While I rewiring my submarine game crashes

### Reproduction steps

I do not know exactly why.
I just mount motion detector in door and attach wire to it and the game crashes

[crashreport (5).log](https://github.com/Regalis11/Barotrauma/files/11146654/crashreport.5.log)

### Bug prevalence

Just once

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by pavel4win** [comment] 2023-04-04 09:52
[crashreport (6).log](https://github.com/Regalis11/Barotrauma/files/11147134/crashreport.6.log)

**Comment by Regalis11** [comment] 2023-04-04 10:22
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11563

**Closed by Regalis11** 2023-04-04 10:22 UTC
