### ISSUE TITLE
Remora Drone has a wall that prevents draining the engine compartment.

### ISSUE THREAD

**Issue by PokkeTigrex** [Regalis11/Barotrauma#10945] opened 2023-01-15 21:42 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Same as #8138, but that's been a year with no response. The Remora drone has a engine compartment that cannot drain once water gets into it, as there's no pump in it. Draining it requires a plasma cutter to remove the wall between the compartment and ballast to drain it, and frequently causes the drone to instantly sink when undocked. A simple removal of the wall or a additional pump would make it much less of an issue of needing to cut that wall every time.

![image](https://user-images.githubusercontent.com/85914375/212568726-347bdb35-3b6e-42e6-82cb-ae11eac716c0.png)

### Reproduction steps

Look at the remora drone in the sub editor, how is it supposed to drain that engine room without breaking the wall?

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-01-16 09:38
Duplicate of https://github.com/Regalis11/Barotrauma/issues/8138

**Closed by Regalis11** 2023-01-16 09:38 UTC
