### ISSUE TITLE
Incorrect quality stat type for revolver

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#9568] opened 2022-07-14 12:42 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Quality level does not affect revolver's damage as expected. Because in the weapon.xml it is "StrikingSpeedMultiplier" which increases melee damage instead of "FirepowerMultiplier".

### Reproduction steps

1.start sub editor
2.spawn a high quality revolver and a low quality one
3.shoot something with 2 pistols and compare their damage (suggest equip a health scanner for clearer values)

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-07-14 13:06
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e89993457a8d66ee6040bcbe25b8c9c18dabd3ef

**Comment by NilanthAnimosus** [comment] 2022-07-22 14:41
Tested in 0.19.0.0, working correctly.

Examined other weapons and items incase of any other incorrect stat types.

Grenade launcher uses "FirepowerMultiplier" over "ExplosionDamage" or "ExplosionRadius" - does this have a positive effect on this type of weapon?

Stun Gun - Does FirepowerMultiplier actually effect stun-based damages?

**Comment by Regalis11** [comment] 2022-08-16 18:01
Nice catch! The grenade launcher was indeed bugged, should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/44e85372ceb839fb09b0452896bfc0a619bfac77.

Stun gun should work: FirepowerMultiplier multiplies the strength of the afflictions caused by the weapon, including stun.

**Comment by NilanthAnimosus** [comment] 2022-08-22 22:36
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/bb09d83d99ad00711a0eb53b06788895d76d0ec1, works correctly, but have a curiosity,

Is stun baton only intended to have striking speed multiplier, and not power? given it uses incremental and not progressive stun alongside a small amount of stun afflictions. meanwhile it already attacks at a fair rate (with a reload of 0.95) and could be dual wielded on top?

no other items have anything to question for their quality multipliers now, and grenade launchers quality does effect how much explosion damage and range the weapon produces now correctly ingame.

**Comment by Regalis11** [comment] 2022-08-23 12:27
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4f148588a763c27075e4491cb9225540da95f3b8

**Comment by NilanthAnimosus** [comment] 2022-08-23 13:25
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/f82a333e436d97a8051448f960194e41892e9be5.

With the new changes to the stun baton quality bonus, in game there is no discernable difference to the player for the striking power, both taking two hits regardless of battery used. Perhaps the speed is a better bonus in this case than the striking power due to this. Though perhaps the movement speed and other negatives of the higher stun is a benefit, its quite difficult to notice on the targets I used when within striking range.

**Comment by Regalis11** [comment] 2022-08-23 14:12
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/e60e6d9edc955ac3baf6576361f65cc64a8b3cfe

**Comment by Regalis11** [comment] 2022-08-23 14:36
Turns out there was a bug here: the StrikingPowerMultiplier only affected the afflictions defined in the MeleeWeapon's Attack, but not the ones defined in StatusEffects. In the case of stun batons, the Attack only causes a bit of blunt trauma and a very brief stun, but the "actual" stun is done in StatusEffects which check the type of battery in the baton and reduce it's condition.

Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e623c1cf213c079924dc990cccede8d18d5de0e0

**Comment by NilanthAnimosus** [comment] 2022-08-30 11:35
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/bbf791095b76d136daa9aa4b2301354e9431b77e, no further issues found, closing.

Notes: the only combination of stun baton capable of a one-hit stun is +3 (max) quality with a Fulgurium battery cell. Otherwise its generally 2 hits for various combinations, with a zero quality baton with a regular battery taking 3 hits.

**Closed by NilanthAnimosus** 2022-08-30 11:35 UTC
Labels: Bug, Design, Unstable
