### ISSUE TITLE
You can communicate at 2 stage of husk

### ISSUE THREAD

**Issue by Abkim27** [Regalis11/Barotrauma#9706] opened 2022-08-13 16:45 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

After having text, that says "You can't do any sound", you still can communicate through text and micro

### Reproduction steps

1 Get bitten by husk
2 Wait until 2 stage
3 Try to say something 

### Bug prevalence

Happens every time I play

### Version

Other

### -

0.18.15.1

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment] 2022-08-15 14:11
I'm afraid I could not reproduce this. Did this happen in single player or multiplayer? What do you mean by communicating through micro?

**Comment by Abkim27** [comment] 2022-08-15 14:47
Communicating throug microphone. In multiplayer, after i got husk infection, on 2 stage i still could communicate with other people through ingame microphone

**Comment by NilanthAnimosus** [comment] 2022-08-16 06:33
Tested on 0.18.15.1 - I was able to get speech bubbles to appear for mic chat when the player could no longer talk anymore, however this is when local/radio chat turns blue (where only spectators will see it) and a second client cannot hear the microphone chat (local or radio) in my own tests. I assume by communicating through microphone in this case is referring to the speech icons above the players head when they can no longer actually communicate.

**Comment by Abkim27** [comment] 2022-08-16 08:50
There is a message to 2 stage "You sense somehing in mouth, but when you try to scream you make no sound", but after that message i could talk with others, even give orders to bots

**Comment by Regalis11** [comment] 2022-09-07 07:22
No known steps to repro, closing

**Closed by Regalis11** 2022-09-07 07:22 UTC
Labels: Bug, Need more info, Code
