### ISSUE TITLE
[1.0.4] Clipping through terrain and getting stuck + Corpse glitching through terrain

### ISSUE THREAD

**Issue by StruggleDuck** [Regalis11/Barotrauma#11357] opened 2023-02-25 00:15 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While attempting to grab a corpse that had fallen outside of a wreck onto the terrain below, I encountered bugs. the first bug involved the corpse falling through the terrain, and as a byproduct of that happening, the corpse was no longer interactable. 

### POV 1 (Host): 
![Duckpov1](https://user-images.githubusercontent.com/92034548/221323074-763064a5-009b-4057-a971-9b451ed6030d.png)
_(sorry about the low res, the only image I had from my POV that showed the corpse in the terrain was from a windows screenshot notification from a later screenshot)_

### POV 2 (Paul):
![Paul pov1](https://user-images.githubusercontent.com/92034548/221323220-57fb2cf3-3f34-4eaf-b551-14e853b282c2.jpg)
![paulpov2](https://user-images.githubusercontent.com/92034548/221323226-ecb040e5-190b-4a39-8ba5-61725fd6152b.jpg)

### POV 1 (Host): 
![Duck pov2](https://user-images.githubusercontent.com/92034548/221323550-d4d0f357-3f35-44bb-bedd-7f08adb63566.png)
![Duck pov3](https://user-images.githubusercontent.com/92034548/221323570-3af5c0c0-53df-422c-ba12-07fb3eb0c33e.png)

### POV 2 (Paul):

![paulpov3](https://user-images.githubusercontent.com/92034548/221323592-8db5b719-85fa-43eb-a624-a7dae84da91d.jpg)

The second bug that I encountered was after attempting to grab the other corpse that had fallen onto the terrain, I accidentally got stuck. I was entirely unable to move except for the direction I was facing. When moving forward, I slowly moved further and further into the terrain, and eventually I was even unable to move forward as well. the only way I was able to get out was using the teleport command. 

### POV 1 (Host):
![image](https://user-images.githubusercontent.com/92034548/221323668-90db6145-357b-472f-bb79-fb92b38772d0.png)
![image](https://user-images.githubusercontent.com/92034548/221323698-964557b4-a58d-4b0e-941f-136a1f16d937.png)

### POV 2 (Paul):
![20230225014758_1](https://user-images.githubusercontent.com/92034548/221323776-b4189cbf-f46c-4beb-a992-fa7638effbab.jpg)
![20230225014823_1](https://user-images.githubusercontent.com/92034548/221323781-087db7c1-91db-4be6-bfc5-9ed4926d96da.jpg)
![20230225014845_1](https://user-images.githubusercontent.com/92034548/221323787-4316f06c-779d-4ca3-b789-a7d58b1097e6.jpg)

Both bugs happened at the back left side of the wreck that was a part of the salvage mission we were doing. I will attach the save file below.
[TERRORIST LIFESTYLE.zip](https://github.com/Regalis11/Barotrauma/files/10829865/TERRORIST.LIFESTYLE.zip)

### Reproduction steps

1. Load campaign file
2. Go to the bottom left side of the wreck outlined in the salvage mission
3. attempt to swim into the terrain
4. ???
5. profit!

### Bug prevalence

Just once

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by StruggleDuck** [comment] 2023-03-26 23:06
I think I figured out what causes this bug. I was able to replicate it in a different level, and I believe it is caused by the terrain overlapping with the broken shell pieces of the wreck. I showcased this in a quick video that I will link below: 

[Showcase of bug](https://youtu.be/1Ui5OAeXvLQ)

**Comment by itchyOwl** [comment] 2023-03-28 08:44
Irc we had a bit similar issues back in the days when we first implemented the wrecks, but @Regalis11 did some fixes to it. Possibly related?

**Comment by Regalis11** [comment] 2023-04-03 14:41
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/25a5558bb7ac96e564df9ee74b5e8f8bc515eda1

**Comment by Rokvach** [comment] 2023-04-17 11:54
I was still able to reproduce this with the included save

1. Go to the mission wreck
2. Use explosion command to break the bottom walls of the wreck
3. Swim against the level wall until you glitch through it
![image](https://user-images.githubusercontent.com/7299826/232475930-1887c3e2-253c-4b62-aa41-66b9945424cb.png)

**Comment by Regalis11** [comment] 2023-04-17 12:06
Couldn't repro:
https://user-images.githubusercontent.com/14351070/232479333-c2edaeb0-52d9-4d6d-aab5-e96ab89d9bf2.mp4

**Comment by Rokvach** [comment] 2023-04-17 13:54
Tested again on commit  https://github.com/Regalis11/Barotrauma-development/commit/c29927723e46a9c31ef5e969973fa3e1cfdcc1c6 (private repo). Working correctly, closing.

**Comment by Regalis11** [comment] 2023-04-19 08:11
Seems like this caused some new issues: the "collision blocker" seems to be active on docking ports, preventing characters from passing from the sub to the outpost.

**Closed** 2023-04-26 15:18 UTC
Labels: Bug, Code
