### ISSUE TITLE
Opening the Tab menu after controlling Aliens crashes

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2796] opened 2020-05-09 16:42 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Opening the Tab menu after controlling Aliens crashes
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/4604125/crashreport.log)

**Version**
0.9.9.1

**Comment by Regalis11** [comment] 2020-05-10 16:50
Duplicate of #2699

**Closed by Regalis11** 2020-05-10 16:50 UTC
