### ISSUE TITLE
Memory component bypasses gunnery skill for ship weapons.

### ISSUE THREAD

**Issue by Billdozer9000** [Regalis11/Barotrauma#11794] opened 2023-04-10 04:00 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Outputting the position_out from the periscope to a memory component, then outputting the information from the memory component to the position_in on the ship mounted weaponry results in very good aiming even with bad gunnery skill.
I have only tried this in the sub editor.
I have only tried this with the coilgun.
The periscope still seems to work properly otherwise.

### Reproduction steps

Take a periscope position_out > Memory component > Coilgun position_in. Test with various crew members.
I put 2 coilguns side by side to test them. One with a direct signal and one routed through a memory component. This allowed me to see very clearly the difference between the performance of each gun.

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-04-10 09:33
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11513

**Closed by Regalis11** 2023-04-10 09:33 UTC
