### ISSUE TITLE
Unstable - purchased items are removed from stock twice

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#3049] opened 2020-06-09 20:23 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Purchased items are removed from stock twice at least in multiplayer (didn't test SP yet).

**Steps To Reproduce**
1. Buy a headset
2. Exit outpost
3. Re-enter outpost
4. There's now 2 less headsets for sale

**Version**
v0.1002.0.0

**Additional information**
![6784567567](https://user-images.githubusercontent.com/14351070/84195953-1b737300-aaa8-11ea-8d87-0d6b70290888.png)

**Comment by ekqvist** [comment] 2020-06-10 09:13
Can't reproduce with the same steps in SP, so seems to be a MP-only issue

**Comment by Regalis11** [comment] 2020-06-10 10:48
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/3c4d79a0ee8613a9024c4819fc25444f1148a949

**Comment by Rokvach** [comment] 2020-06-15 05:41
Couldn't reproduce, working correctly. Closing.

**Closed by Rokvach** 2020-06-15 05:41 UTC
Labels: Bug, Code, Networking
