### ISSUE TITLE
[0.9.9.0] Bots - Electrocuted out of existence

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2641] opened 2020-04-17 00:33 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When Bots get electrocuted for repairing things, rarely their entire body disappears where they were electrocuted. They're frozen in place with only the tools on hand visible, and unable to move or get up.

**Version**
0.9.9.0

**Comment by Regalis11** [comment] 2020-07-09 11:50
Haven't been able to reproduce this or seen this occur: have you seen it happen in multiplayer, single player or both?

**Comment by Kaillera** [comment] 2020-07-09 12:00
Singleplayer

**Comment by Regalis11** [comment] 2020-07-10 10:17
Alright, thanks for the clarification! It may have been caused by simple physics, so I think we can close this and reopen if the issue resurfaces.

**Closed by Regalis11** 2020-07-10 10:17 UTC
Labels: Bug, Code, Need more info
