### ISSUE TITLE
Broken rotation values for mirrored objects

### ISSUE THREAD

**Issue by NOODLESwastaken** [Regalis11/Barotrauma#5821] opened 2021-05-17 18:04 UTC
[X] I have searched the issue tracker to check if the issue has already been reported.

So i've been making this custom reactor room lately and i have run into a serious progress halting issue.
https://cdn.discordapp.com/attachments/220881718666723328/843906834066047016/unknown.png
This is how the reactor is supposed to look like. ^
https://cdn.discordapp.com/attachments/220881718666723328/843906904320901190/unknown.png
This is how it becomes when i test run the submarine. ^
https://cdn.discordapp.com/attachments/220881718666723328/843907060952989706/unknown.png
And it stays like that after returning to the editor. ^
It only happens on mirrored objects which get rotated.
How to reproduce:
1- mirror any rotatable object
2- rotate it.
3- test (if this issue doesnt occur try again, or re open the save then test)

**Comment by Regalis11** [comment] 2021-05-17 18:06
Duplicate of https://github.com/Regalis11/Barotrauma/issues/5144

**Closed by Regalis11** 2021-05-17 18:06 UTC
