### ISSUE TITLE
macOS no audio input

### ISSUE THREAD

**Issue by mlooney** [Regalis11/Barotrauma#10724] opened 2022-12-15 03:03 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

microphone should work.

### Reproduction steps

be on macOS, try to use the microphone (wired)

### Bug prevalence

Happens every time I play

### Version

0.20.15.0

### Which operating system did you encounter this bug on?

MacOS

### Relevant error messages and crash reports

```shell
Zero input from microphone. tried turning mic permissions on & off to no avail. tried multiple devices, deleted config_player.xml and so on. 620+ hours in and it's worked fine (mostly) until the 2022 holiday update.
```

**Comment by Regalis11** [comment] 2022-12-15 10:23
Duplicate of https://github.com/Regalis11/Barotrauma/issues/5650. It might help us diagnose this if you let us know you macOS version and which kind of mic you're using in that old ticket! Thanks and sorry for the inconvenience!

**Closed by Regalis11** 2022-12-15 10:23 UTC

**Comment by mlooney** [comment] 2022-12-15 20:00
his issue seems to be the opposite, full signal at all times. I get no sensitivity in that screen at all (and no audio otherwise as well) I'm using an 2020 m1 Mac on  Ventura 13.1.  Again, worked flawlessly until this release.  I also use the same mic for various other apps on a daily basis without issue. the macOS audio input control panel shows that it is registering levels while the game is open as well.

**Comment by mlooney** [comment] 2022-12-16 16:59
in case someone runs into this in future, the fix was to uninstall the game, remove microphone permission from the list of apps requesting access, reinstall the game.  next launch it will ask for microphone permission, allow it, and voila, fixed.
