### ISSUE TITLE
Gun light state reset every round.

### ISSUE THREAD

**Issue by G-M-twostay** [Regalis11/Barotrauma#12057] opened 2023-05-23 08:03 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I don't know if this is intended behavior, but if you turn off the gun light one round, then select mission or dock at outpost, the gun light will turn back on automatically. This is different from light components and lamps, which keep their state.

### Reproduction steps

1. connect a button's singal_out to the turret's toggle_light and a light component's toggl_state.
2. set the light component to is_on.
3. click the button. you should notice that both the light component and the turret's search light turns off.
4. dock at outpost or select mission and leave. 
5. the light component will still be off. However, the gun light will be back on.

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-05-23 08:16
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10704

**Closed by Regalis11** 2023-05-23 08:16 UTC
