### ISSUE TITLE
Motion detector - random flickering on crafted or spawned in detectors

### ISSUE THREAD

**Issue by MarcB95** [Regalis11/Barotrauma#11146] opened 2023-02-03 19:03 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Non-native motion detectors behave very erratically. Below is a side by side comparison with a detached detector from the sub itself (left) and the spawned in detector (right) using identical detector settings:
![3214312](https://user-images.githubusercontent.com/122530244/216684003-0f038027-8015-4b71-b6d2-511888fc12bc.gif)
It stays at 1 while the character is in motion and starts flickering when standing still. It will settle on 0 after a few seconds. Moving or turning the character makes it start flickering again.

### Reproduction steps

1) play campaign or mission with at least: 2x text display, 2x cable, 1x motion detector, 1x wrench, 1x screwdriver
2) place the detector on the wall
3) place a text display underneath and connect the detector output to 'set text'
4) set the detectors false output to 0
5) detach any motion detector from the sub itself
6) repeat step 3
7) stand or move between both detectors

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-02-06 10:18
I'm fairly sure this is caused by the "minimum velocity" setting of the detector. The setting defaults to 0.01 m/s, but has most likely been increased on the pre-placed detector in the sub editor.

**Comment by Regalis11** [comment] 2023-02-06 10:32
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/0ae547072a7dea88b532d4fa2ebd0aec708aacfb by increasing the default value from 0.01 to 0.1.

**Comment by Rokvach** [comment] 2023-02-07 13:40
Tested, no issues. Closing.

**Closed** 2023-02-07 13:40 UTC
Labels: Code
