### ISSUE TITLE
Multiplayer Bug With Players Using the Same WiFi Connection

### ISSUE THREAD

**Issue by Ludaneon** [Regalis11/Barotrauma#7316] opened 2021-11-15 00:48 UTC
- [ ✓] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Whilst playing in a public multiplayer server with my brother on the same WiFi connection, at random times I will become him. My screen abruptly moves to where he is in the map and I take over him and he is made a spectator. When I type in the chat, it is in his name. When he types, it is also in his name. I totally become his character and can play the rest of the mission that way. My original body just stands there and there is no way to get back to it.

**Steps To Reproduce**
Play multiplayer with others on the same WiFi connection is my thinking of what causes the bug. It doesn't happen every time, but it happened twice in a few hours period.

**Version**
v0.15.13.0, Windows 10

**Additional information**

**Comment by Regalis11** [comment] 2021-11-16 13:01
Duplicate of Regalis11/Barotrauma#5405

**Closed by Regalis11** 2021-11-16 13:01 UTC
Labels: Bug, Code, Networking
