### ISSUE TITLE
Game got crashed, every time.

### ISSUE THREAD

**Issue by MSERFM** [Regalis11/Barotrauma#12710] opened 2023-09-23 06:01 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

**Game issue

I Have Big problem bro.....

I Have game reinstall every time repeat again, and too game crashed or server host crashed won`t  work again.

So let me can't join people multiplayer, didn`t working, got error conlose command every time.

Error host server won`t start.
Host Server Won`t running Or Let me can`t join anyone people, 
Error other all game other very issue..
Why error all problem so much
Here Proof : 
Screenshot Link : https://steamcommunity.com/sharedfiles/filedetails/?id=3038687696
Screen shot # 2 link : https://steamcommunity.com/sharedfiles/filedetails/?id=3039885147
Screenshot # 3 Link   : https://steamcommunity.com/sharedfiles/filedetails/?id=3039884500
Screenshot #4 Link: https://steamcommunity.com/sharedfiles/filedetails/?id=3039885595
Screenshot #5 Link : https://steamcommunity.com/sharedfiles/filedetails/?id=3039885876

### Reproduction steps

1. Add more Mod.
2. Start Server host
3. Create Camping
4. Loading
5. Got crashed game again
6. Open Barotrauma again
7. Clicked Start on Server Host he won`t start server, error that is all.**

im very sorry sir, i`m bad english.
 

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Host Server

### -

Other.

### Version

v1.0.21.0

### -

idk

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 09/23/2023 08:36:39)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

9F5E3061E92D485CB02263313B29506B

Game version 1.0.21.0 (ReleaseWindows, branch release/summer-patch-hotfix, revision adb80ccd6e)
Graphics mode: 1280x1024 (FullScreen)
VSync OFF
Language: English
Selected content packages: Vanilla (65E9331), EK Armory (9E02A9D), EK Utilities (A203BCB), Improved Husks (C13E3C5), EK Gunnery (BEBF24C), EK Dockyard (ED5F770), DynamicEuropa (954D388), Lua For Barotrauma (7ACA3F4), SIN Beacon Stations (94D0EA4), Stations from beyond (06603E4), ADV Beacon Stations (DC4226B), SOFA'S WRECKS (8751CE1), 32x Stack (6262D38), NT Cybernetics (E874CF1), NT Surgery Plus (7E2F7A3), Neurotrauma (F35E20B), NT Pharmacy (D75EE32), Genes+Revived (1F8362E), Enhanced Armaments Neurotrauma Patch (A5754DA), Dont Open Debug Console On Errors (CC8C3BA), Real Sonar (New Update) (773EDE2), Real Sonar - EK Dockyard Patch (2492AC9), Real Sonar - Soundproofing Gel (A0AC27D), Robotrauma (CE6AAA4), Extract It! Neurotrauma Patch (90CDA0D), Robo-Trauma - Neurotrauma patch (5FEF260), ExtraXP (C662BBB), Real Sonar Medical Item Recipes Patch for Neurotrauma (9EEDBFB), Malachite (D37E67C), Lua Editor (F6A052E), Improved  Stun (2BE3C39), Enhanced Armaments + FFE Neurotrauma Patch (2D55499), Some metal (58FF60F), BaroCraftables+ (2B18C79), Lua Linker (A3ECE31), EuropaWar (C846D4E), Parallel Talents Plus (DC68072), SFB with DE (43EDF95)
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.NetLobbyScreen
SteamManager initialized
Client (Round hadn't been started)

System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit
    GPU name: NVIDIA GeForce GT 630
    Display mode: {Width:1280 Height:1024 Format:Color AspectRatio:1.25}
    GPU status: Normal

Exception: ChildServerRelay readTask did not run to completion: status was WaitingForActivation. (System.Exception)
Target site: Barotrauma.Option`1[System.Int32] ReadIncomingMsgs()
Stack trace: 
   at Barotrauma.Networking.ChildServerRelay.ReadIncomingMsgs() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 155
   at Barotrauma.Networking.ChildServerRelay.<UpdateRead>g__readBytes|43_0(Span`1 readTo) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 183
   at Barotrauma.Networking.ChildServerRelay.UpdateRead() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 175
   at System.Threading.Thread.StartCallback()

Last debug messages:
[09/23/2023 08:36:39] WARNING: Tried to restore enabled packages multiple times/without performing a backup
[09/23/2023 08:17:13] WARNING: Tried to restore enabled packages multiple times/without performing a backup
[09/23/2023 08:17:13] uaCsSetup.cs:line 271
[09/23/2023 08:17:13] Sharp.Interpreter.Execution.VM.Processor.Processing_Loop(Int32 instructionPtr) in B:\programming\c#\Barotrauma\Libraries\moonsharp\MoonSharp.Interpreter\Execution\VM\Processor\Processor_InstructionLoop.cs:line 222
   --- End of inner exception stack trace ---
   at MoonSharp.Interpreter.Execution.VM.Processor.Processing_Loop(Int32 instructionPtr) in B:\programming\c#\Barotrauma\Libraries\moonsharp\MoonSharp.Interpreter\Execution\VM\Processor\Processor_InstructionLoop.cs:line 307
   at MoonSharp.Interpreter.Execution.VM.Processor.Call(DynValue function, DynValue[] args) in B:\programming\c#\Barotrauma\Libraries\moonsharp\MoonSharp.Interpreter\Execution\VM\Processor\Processor.cs:line 99
   at MoonSharp.Interpreter.Script.Call(DynValue function, DynValue[] args) in B:\programming\c#\Barotrauma\Libraries\moonsharp\MoonSharp.Interpreter\Script.cs:line 474
   at Barotrauma.LuaCsSetup.CallLuaFunction(Object function, Object[] args) in B:\programming\c#\Barotrauma\Barotrauma\BarotraumaShared\SharedSource\LuaCs\L
[09/23/2023 08:17:13] uma\Libraries\moonsharp\MoonSharp.Interpreter\Interop\StandardDescriptors\ReflectionMemberDescriptors\MethodMemberDescriptor.cs:line 198
   at MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor.<>c__DisplayClass33_0.<GetCallback>b__0(ScriptExecutionContext context, CallbackArguments args) in B:\programming\c#\Barotrauma\Libraries\moonsharp\MoonSharp.Interpreter\Interop\StandardDescriptors\ReflectionMemberDescriptors\OverloadedMethodMemberDescriptor.cs:line 426
   at MoonSharp.Interpreter.Interop.BasicDescriptors.DispatchingUserDataDescriptor.Index(Script script, Object obj, DynValue index, Boolean isDirectIndexing) in B:\programming\c#\Barotrauma\Libraries\moonsharp\MoonSharp.Interpreter\Interop\BasicDescriptors\DispatchingUserDataDescriptor.cs:line 250
   at MoonSharp.Interpreter.Execution.VM.Processor.ExecIndex(Instruction i, Int32 instructionPtr) in B:\programming\c#\Barotrauma\Libraries\moonsharp\MoonSharp.Interpreter\Execution\VM\Processor\Processor_InstructionLoop.cs:line 1292
   at Moon
[09/23/2023 08:17:12] [SV LUA ERROR] C:/Users/Siiph/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Lua/Scripts/helperfunctions.lua:(294,4-55): The given key 'eyedrop' was not present in the dictionary.: MoonSharp.Interpreter.NetRuntimeException: The given key 'eyedrop' was not present in the dictionary.
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'eyedrop' was not present in the dictionary.
   at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNotFoundException(TKey key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
   at Barotrauma.PrefabCollection`1.get_Item(Identifier identifier) in B:\programming\c#\Barotrauma\Barotrauma\BarotraumaShared\SharedSource\Prefabs\PrefabCollection.cs:line 263
   at lambda_method82(Closure , Object , Object[] )
   at MoonSharp.Interpreter.Interop.MethodMemberDescriptor.Execute(Script script, Object obj, ScriptExecutionContext context, CallbackArguments args) in B:\programming\c#\Barotra
[09/23/2023 08:17:12] uaCsSetup.cs:line 271
[09/23/2023 08:17:12] Sharp.Interpreter.Execution.VM.Processor.Processing_Loop(Int32 instructionPtr) in B:\programming\c#\Barotrauma\Libraries\moonsharp\MoonSharp.Interpreter\Execution\VM\Processor\Processor_InstructionLoop.cs:line 222
   --- End of inner exception stack trace ---
   at MoonSharp.Interpreter.Execution.VM.Processor.Processing_Loop(Int32 instructionPtr) in B:\programming\c#\Barotrauma\Libraries\moonsharp\MoonSharp.Interpreter\Execution\VM\Processor\Processor_InstructionLoop.cs:line 307
   at MoonSharp.Interpreter.Execution.VM.Processor.Call(DynValue function, DynValue[] args) in B:\programming\c#\Barotrauma\Libraries\moonsharp\MoonSharp.Interpreter\Execution\VM\Processor\Processor.cs:line 99
   at MoonSharp.Interpreter.Script.Call(DynValue function, DynValue[] args) in B:\programming\c#\Barotrauma\Libraries\moonsharp\MoonSharp.Interpreter\Script.cs:line 474
   at Barotrauma.LuaCsSetup.CallLuaFunction(Object function, Object[] args) in B:\programming\c#\Barotrauma\Barotrauma\BarotraumaShared\SharedSource\LuaCs\L
[09/23/2023 08:17:12] uma\Libraries\moonsharp\MoonSharp.Interpreter\Interop\StandardDescriptors\ReflectionMemberDescriptors\MethodMemberDescriptor.cs:line 198
   at MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor.<>c__DisplayClass33_0.<GetCallback>b__0(ScriptExecutionContext context, CallbackArguments args) in B:\programming\c#\Barotrauma\Libraries\moonsharp\MoonSharp.Interpreter\Interop\StandardDescriptors\ReflectionMemberDescriptors\OverloadedMethodMemberDescriptor.cs:line 426
   at MoonSharp.Interpreter.Interop.BasicDescriptors.DispatchingUserDataDescriptor.Index(Script script, Object obj, DynValue index, Boolean isDirectIndexing) in B:\programming\c#\Barotrauma\Libraries\moonsharp\MoonSharp.Interpreter\Interop\BasicDescriptors\DispatchingUserDataDescriptor.cs:line 250
   at MoonSharp.Interpreter.Execution.VM.Processor.ExecIndex(Instruction i, Int32 instructionPtr) in B:\programming\c#\Barotrauma\Libraries\moonsharp\MoonSharp.Interpreter\Execution\VM\Processor\Processor_InstructionLoop.cs:line 1292
   at Moon
[09/23/2023 08:17:12] [SV LUA ERROR] C:/Users/Siiph/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Lua/Scripts/helperfunctions.lua:(294,4-55): The given key 'eyedrop' was not present in the dictionary.: MoonSharp.Interpreter.NetRuntimeException: The given key 'eyedrop' was not present in the dictionary.
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'eyedrop' was not present in the dictionary.
   at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNotFoundException(TKey key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
   at Barotrauma.PrefabCollection`1.get_Item(Identifier identifier) in B:\programming\c#\Barotrauma\Barotrauma\BarotraumaShared\SharedSource\Prefabs\PrefabCollection.cs:line 263
   at lambda_method82(Closure , Object , Object[] )
   at MoonSharp.Interpreter.Interop.MethodMemberDescriptor.Execute(Script script, Object obj, ScriptExecutionContext context, CallbackArguments args) in B:\programming\c#\Barotra
[09/23/2023 08:17:11] uaCsSetup.cs:line 271
[09/23/2023 08:17:11] Sharp.Interpreter.Execution.VM.Processor.Processing_Loop(Int32 instructionPtr) in B:\programming\c#\Barotrauma\Libraries\moonsharp\MoonSharp.Interpreter\Execution\VM\Processor\Processor_InstructionLoop.cs:line 222
   --- End of inner exception stack trace ---
   at MoonSharp.Interpreter.Execution.VM.Processor.Processing_Loop(Int32 instructionPtr) in B:\programming\c#\Barotrauma\Libraries\moonsharp\MoonSharp.Interpreter\Execution\VM\Processor\Processor_InstructionLoop.cs:line 307
   at MoonSharp.Interpreter.Execution.VM.Processor.Call(DynValue function, DynValue[] args) in B:\programming\c#\Barotrauma\Libraries\moonsharp\MoonSharp.Interpreter\Execution\VM\Processor\Processor.cs:line 99
   at MoonSharp.Interpreter.Script.Call(DynValue function, DynValue[] args) in B:\programming\c#\Barotrauma\Libraries\moonsharp\MoonSharp.Interpreter\Script.cs:line 474
   at Barotrauma.LuaCsSetup.CallLuaFunction(Object function, Object[] args) in B:\programming\c#\Barotrauma\Barotrauma\BarotraumaShared\SharedSource\LuaCs\L
[09/23/2023 08:17:09] uma\Libraries\moonsharp\MoonSharp.Interpreter\Interop\StandardDescriptors\ReflectionMemberDescriptors\MethodMemberDescriptor.cs:line 198
   at MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor.<>c__DisplayClass33_0.<GetCallback>b__0(ScriptExecutionContext context, CallbackArguments args) in B:\programming\c#\Barotrauma\Libraries\moonsharp\MoonSharp.Interpreter\Interop\StandardDescriptors\ReflectionMemberDescriptors\OverloadedMethodMemberDescriptor.cs:line 426
   at MoonSharp.Interpreter.Interop.BasicDescriptors.DispatchingUserDataDescriptor.Index(Script script, Object obj, DynValue index, Boolean isDirectIndexing) in B:\programming\c#\Barotrauma\Libraries\moonsharp\MoonSharp.Interpreter\Interop\BasicDescriptors\DispatchingUserDataDescriptor.cs:line 250
   at MoonSharp.Interpreter.Execution.VM.Processor.ExecIndex(Instruction i, Int32 instructionPtr) in B:\programming\c#\Barotrauma\Libraries\moonsharp\MoonSharp.Interpreter\Execution\VM\Processor\Processor_InstructionLoop.cs:line 1292
   at Moon
[09/23/2023 08:17:05] [SV LUA ERROR] C:/Users/Siiph/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Lua/Scripts/helperfunctions.lua:(294,4-55): The given key 'eyedrop' was not present in the dictionary.: MoonSharp.Interpreter.NetRuntimeException: The given key 'eyedrop' was not present in the dictionary.
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'eyedrop' was not present in the dictionary.
   at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNotFoundException(TKey key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
   at Barotrauma.PrefabCollection`1.get_Item(Identifier identifier) in B:\programming\c#\Barotrauma\Barotrauma\BarotraumaShared\SharedSource\Prefabs\PrefabCollection.cs:line 263
   at lambda_method82(Closure , Object , Object[] )
   at MoonSharp.Interpreter.Interop.MethodMemberDescriptor.Execute(Script script, Object obj, ScriptExecutionContext context, CallbackArguments args) in B:\programming\c#\Barotra
[09/23/2023 08:15:49] WARNING: Potential error in item variant "screwdriverhardened": the base item "screwdriver" requires x2 "iron" to fabricate. The variant only overrides the required item, not the amount, resulting in a requirement of x2 "screwdriver". Specify the amount in the variant to fix this.
[09/23/2023 08:15:49] WARNING: Potential error in item variant "screwdriverdementonite": the base item "screwdriver" requires x2 "iron" to fabricate. The variant only overrides the required item, not the amount, resulting in a requirement of x2 "screwdriver". Specify the amount in the variant to fix this.
[09/23/2023 08:15:43] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Hamo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2948488019/UI/augmentUI.png, size: 1008x214)
[09/23/2023 08:15:43] Overriding an affliction or a buff with the identifier 'burn' using the file 'C:/Users/Hamo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2948488019/Afflictions/Afflictions.xml'
[09/23/2023 08:15:43] WARNING: Potential error in item variant "screwdriverhardened": the base item "screwdriver" requires x2 "iron" to fabricate. The variant only overrides the required item, not the amount, resulting in a requirement of x2 "screwdriver". Specify the amount in the variant to fix this.
[09/23/2023 08:15:43] WARNING: Potential error in item variant "screwdriverdementonite": the base item "screwdriver" requires x2 "iron" to fabricate. The variant only overrides the required item, not the amount, resulting in a requirement of x2 "screwdriver". Specify the amount in the variant to fix this.
[09/23/2023 08:15:43] WARNING: Potential error in item variant "screwdriverdementonite": the base item "screwdriver" requires x2 "iron" to fabricate. The variant only overrides the required item, not the amount, resulting in a requirement of x2 "screwdriver". Specify the amount in the variant to fix this.
[09/23/2023 08:15:43] WARNING: Potential error in item variant "screwdriverhardened": the base item "screwdriver" requires x2 "iron" to fabricate. The variant only overrides the required item, not the amount, resulting in a requirement of x2 "screwdriver". Specify the amount in the variant to fix this.
[09/23/2023 08:15:42] Overriding an affliction or a buff with the identifier 'burn' using the file 'C:/Users/Hamo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2951934198/XML/Afflictions.xml'
[09/23/2023 08:15:42] WARNING: Potential error in item variant "screwdriverdementonite": the base item "screwdriver" requires x2 "iron" to fabricate. The variant only overrides the required item, not the amount, resulting in a requirement of x2 "screwdriver". Specify the amount in the variant to fix this.
[09/23/2023 08:15:42] WARNING: Potential error in item variant "screwdriverhardened": the base item "screwdriver" requires x2 "iron" to fabricate. The variant only overrides the required item, not the amount, resulting in a requirement of x2 "screwdriver". Specify the amount in the variant to fix this.
[09/23/2023 08:15:42] WARNING: Potential error in item variant "screwdriverhardened": the base item "screwdriver" requires x2 "iron" to fabricate. The variant only overrides the required item, not the amount, resulting in a requirement of x2 "screwdriver". Specify the amount in the variant to fix this.
[09/23/2023 08:15:42] WARNING: Potential error in item variant "screwdriverdementonite": the base item "screwdriver" requires x2 "iron" to fabricate. The variant only overrides the required item, not the amount, resulting in a requirement of x2 "screwdriver". Specify the amount in the variant to fix this.
[09/23/2023 08:15:41] Overriding an affliction or a buff with the identifier 'incrementalstun' using the file 'C:/Users/Hamo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/3005836987/XMl/Med/Afflictions.xml'
[09/23/2023 08:15:41] Overriding an affliction or a buff with the identifier 'stun' using the file 'C:/Users/Hamo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/3005836987/XMl/Med/Afflictions.xml'
[09/23/2023 08:15:39] WARNING: Unrecognized element in affliction "eyeball" (StatusEffect)
[09/23/2023 08:15:39] WARNING: Unrecognized element in affliction "eyeball" (StatusEffect)
[09/23/2023 08:15:26] WARNING: Potential error in item variant "screwdriverdementonite": the base item "screwdriver" requires x2 "iron" to fabricate. The variant only overrides the required item, not the amount, resulting in a requirement of x2 "screwdriver". Specify the amount in the variant to fix this.
[09/23/2023 08:15:26] WARNING: Potential error in item variant "screwdriverhardened": the base item "screwdriver" requires x2 "iron" to fabricate. The variant only overrides the required item, not the amount, resulting in a requirement of x2 "screwdriver". Specify the amount in the variant to fix this.
[09/23/2023 08:15:23] Overriding an affliction or a buff with the identifier 'combatstimulant' using the file 'C:/Users/Hamo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[09/23/2023 08:15:23] Overriding an affliction or a buff with the identifier 'implacable' using the file 'C:/Users/Hamo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[09/23/2023 08:15:23] Overriding an affliction or a buff with the identifier 'concussion' using the file 'C:/Users/Hamo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[09/23/2023 08:15:23] Overriding an affliction or a buff with the identifier 'radiationsickness' using the file 'C:/Users/Hamo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[09/23/2023 08:15:23] Overriding an affliction or a buff with the identifier 'drunk' using the file 'C:/Users/Hamo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[09/23/2023 08:15:23] Overriding an affliction or a buff with the identifier 'invertcontrols' using the file 'C:/Users/Hamo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[09/23/2023 08:15:23] Overriding an affliction or a buff with the identifier 'chemwithdrawal' using the file 'C:/Users/Hamo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[09/23/2023 08:15:23] Overriding an affliction or a buff with the identifier 'chemaddiction' using the file 'C:/Users/Hamo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[09/23/2023 08:15:23] Overriding an affliction or a buff with the identifier 'opiatewithdrawal' using the file 'C:/Users/Hamo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[09/23/2023 08:15:23] Overriding an affliction or a buff with the identifier 'opiateoverdose' using the file 'C:/Users/Hamo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[09/23/2023 08:15:23] Overriding an affliction or a buff with the identifier 'opiateaddiction' using the file 'C:/Users/Hamo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[09/23/2023 08:15:23] Overriding an affliction or a buff with the identifier 'acidburn' using the file 'C:/Users/Hamo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[09/23/2023 08:15:23] Overriding an affliction or a buff with the identifier 'burn' using the file 'C:/Users/Hamo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[09/23/2023 08:15:23] Overriding an affliction or a buff with the identifier 'explosiondamage' using the file 'C:/Users/Hamo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[09/23/2023 08:15:23] Overriding an affliction or a buff with the identifier 'organdamage' using the file 'C:/Users/Hamo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[09/23/2023 08:15:23] Overriding an affliction or a buff with the identifier 'gunshotwound' using the file 'C:/Users/Hamo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[09/23/2023 08:15:23] Overriding an affliction or a buff with the identifier 'bitewounds' using the file 'C:/Users/Hamo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[09/23/2023 08:15:23] Overriding an affliction or a buff with the identifier 'lacerations' using the file 'C:/Users/Hamo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[09/23/2023 08:15:23] Overriding an affliction or a buff with the identifier 'blunttrauma' using the file 'C:/Users/Hamo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[09/23/2023 08:15:23] Overriding an affliction or a buff with the identifier 'internaldamage' using the file 'C:/Users/Hamo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[09/23/2023 08:15:23] Overriding an affliction or a buff with the identifier 'bleedingnonstop' using the file 'C:/Users/Hamo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[09/23/2023 08:15:23] Overriding an affliction or a buff with the identifier 'bleeding' using the file 'C:/Users/Hamo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[09/23/2023 08:15:23] Overriding an affliction or a buff with the identifier 'sufforinpoisoning' using the file 'C:/Users/Hamo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[09/23/2023 08:15:23] Overriding an affliction or a buff with the identifier 'cyanidepoisoning' using the file 'C:/Users/Hamo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[09/23/2023 08:15:23] Overriding an affliction or a buff with the identifier 'morbusinepoisoning' using the file 'C:/Users/Hamo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[09/23/2023 08:15:23] Overriding an affliction or a buff with the identifier 'bloodloss' using the file 'C:/Users/Hamo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[09/23/2023 08:15:23] Overriding an affliction or a buff with the identifier 'oxygenlow' using the file 'C:/Users/Hamo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[09/23/2023 08:14:51] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Hamo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2532991202/UI/DE-IconsAtlas.png, size: 1365x1365)
[09/23/2023 08:14:30] Overriding an affliction or a buff with the identifier 'huskinfection' using the file 'C:/Users/Hamo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2085783214/Afflictions.xml'
[09/23/2023 08:11:52] Attempting to open ALC device "OpenAL Soft on Speakers (4- USB Audio Device)"
[09/23/2023 08:11:39] Logged in as Hamo (SteamID STEAM_1:0:570942151)
```

**Comment by Regalis11** [comment] 2023-09-23 13:28
Thank you for the report!

It seems that there are several different issues here:
- The crash report you've attached to the post (an exception in `Sharp.Interpreter.Execution.VM.Processor.Processing_Loop`) This error seems to be coming from the [Cs For Barotrauma](https://steamcommunity.com/workshop/filedetails/?id=2795927223) mod, so unfortunately there's not much we can do to address it.
- [Invalid sound type in item "respawndivingsuit"](https://steamcommunity.com/sharedfiles/filedetails/?id=3039885147). This also seems to be an issue in one of the mods you're using, so it needs to be addressed by the author of the mod.
- [Failed to start dedicatedserver.exe, the requested operation requires elevation](https://steamcommunity.com/sharedfiles/filedetails/?id=3038687696). This seems to suggest that your system doesn't have permissions to run the server executable. This is also most likely caused by mods, since the Cs For Barotrauma mod replaces the vanilla server excutable. It might be possible to address the issue by editing the permissions of the executable, [as instructed here for example](https://www.drivereasy.com/knowledge/fix-requested-operation-requires-elevation-error-windows-solved/#m1).

**Comment by MSERFM** [comment] 2023-09-23 20:29
@regalis11, uh removed mod now, normal.
when join people server.
so got error.
https://steamcommunity.com/sharedfiles/filedetails/?id=3040154138

**Comment by MSERFM** [comment] 2023-09-23 20:56
https://steamcommunity.com/sharedfiles/filedetails/?id=3040166816

**Comment by Regalis11** [comment] 2023-09-24 08:54
The error does seem to indicate that some mods are still enabled, because the clients are trying to download some mods from the server. :/ I wonder if this could have something to do with the Lua mod - since it replaces the executable, I'm not entirely sure if it can be fully disabled from the "Mods" menu.

I would also suggest verifying the integrity of the game files as described here: https://help.steampowered.com/en/faqs/view/0C48-FCBD-DA71-93EB

**Comment by MSERFM** [comment] 2023-09-24 20:11
> The error does seem to indicate that some mods are still enabled, because the clients are trying to download some mods from the server. :/ I wonder if this could have something to do with the Lua mod - since it replaces the executable, I'm not entirely sure if it can be fully disabled from the "Mods" menu.
> 
> I would also suggest verifying the integrity of the game files as described here: https://help.steampowered.com/en/faqs/view/0C48-FCBD-DA71-93EB

i have already disabled alreaedy, and removed mod bro

got problem bro

**Comment by Regalis11** [comment] 2023-09-25 07:13
I'm sorry to hear that didn't help. :/ To be clear, does the error actually happen the moment people join the server? The error message seems to about loading locations, so to me that sounds like something that shouldn't happen until you load a campaign save. Are you trying to load a save that was made with the mods installed? That could cause issues - a save created while using mods might not work in the vanilla game.

**Comment by MSERFM** [comment] 2023-09-25 12:32
Yeah, You`re correct.
Yes camping saving mod installed old  ( 2023-09-23 ) 

Junction Box Fire ( Glilch ) won`t reapir or won`t hurt human, got crashed game forever now.

reinstalled - ( 2023-09-24 whitout mod )

Let me join him he server own people 
He started spamming loading location error. 

maybe game issue, vanilla game.

**Comment by MSERFM** [comment] 2023-09-25 12:40
very very bug mod issue or game issue.

**Comment by Regalis11** [comment] 2023-09-25 12:57
To clarify, does the game crash to desktop? If it does, could you post the crash report?

Or do you get the error message that says "error loading store info" or "Error while reading CharacterInfo received from the server" when you try to load that previous campaign round? If that's what's happening, it could be that the modded campaign save simply isn't compatible with the vanilla game.

**Comment by MSERFM** [comment] 2023-09-25 22:08
> or "Error while reading CharacterInfo received from the server" when you try to load that previous campaign round? If that's what's happening, it could be that the modded campaign save simply isn't compatible with the vanilla game.

Error loading store info merchanic both.

**Comment by Regalis11** [comment] 2023-09-26 06:39
It sounds like the modded campaign is not compatible with the vanilla game, so I'm afraid you might need to start a new campaign if you can't get those mods to work. :/

**Comment by MSERFM** [comment] 2023-09-26 09:22
So, please how to reset barotrauma bro.

**Comment by MSERFM** [comment] 2023-09-26 09:23
i want to game reset all.

**Comment by Regalis11** [comment] 2023-09-26 09:43
It should be possible to reset the game by disabling the mods, and reinstalling it or verifying file integrity.

I am still not entirely sure what exactly the issue is. Could you please explain what exactly you're attempting to do? Are you trying load an existing campaign save, or does the same error happen when you start a new campaign too? Does this error pop up for you, or for someone else trying to join your server?

**Comment by MSERFM** [comment] 2023-09-26 18:54
Yes Create camping new, got error location loading.

And other server join, got error again.

**Comment by MSERFM** [comment] 2023-09-28 22:02
> It should be possible to reset the game by disabling the mods, and reinstalling it or verifying file integrity.
> 
> I am still not entirely sure what exactly the issue is. Could you please explain what exactly you're attempting to do? Are you trying load an existing campaign save, or does the same error happen when you start a new campaign too? Does this error pop up for you, or for someone else trying to join your server?


never mind thank you so much, fixed worked. 
 
So But one question
I have add mod real sonar only

making host server
Friend joined me
Friend left 1 sec only
Friend hes said https://steamuserimages-a.akamaihd.net/ugc/2103800944331744999/2B598297A86350E19C4F85BAB218F9739A7FF483/ 

people let`s won`t join me

**Comment by MSERFM** [comment] 2023-09-28 22:03
i think download mod issue.

**Comment by Regalis11** [comment] 2023-09-29 06:29
Great to hear you were able to fix it! :)

The "mismatched vanilla package" error in your screenshot means the vanilla content does not match between the client and the server. It could be that your friend has done some modifications to the game files (intentionally or accidentally). Verifying file integrity will probably fix the issue if that's the case.

Anyway, since it seems like the original issue has been resolved, I'll close the ticket.

**Closed by Regalis11** 2023-09-29 06:29 UTC
Labels: Bug, Need more info, Modding
