### ISSUE TITLE
Exploding Ammo sometimes explodes in a deconstructor

### ISSUE THREAD

**Issue by GainDeveloper** [Regalis11/Barotrauma#6613] opened 2021-09-08 09:39 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Ammunition cases for the ships weapons explode when placed in the deconstructor. These will initially hurt the player and then heal them to full health.

**Steps To Reproduce**
- Host multiplayer game.
- Place coil gun ammunition in deconstructor.
- Start deconstructor and stand by it.
- When the ammo explodes you'll initially take damage and then heal to full health.

**Version**
v0.14.9.0 rev 6f88f3dc8c Windows Steam

**Additional information**

**Comment by Regalis11** [comment] 2021-09-08 14:29
I'm afraid I could not reproduce this in either the current public version or the latest unstable version. Are you using some kind of mods?

**Comment by LePiromano** [comment] 2021-09-08 16:48
> I'm afraid I could not reproduce this in either the current public version or the latest unstable version. Are you using some kind of mods?

Exploding ammo sometimes explodes for unknown reasons when put into a deconstructor, maybe in his case the ammo exploded but he desync'd and his health went back to normal, the real bug here is that exploding ammo sometimes blows up in the deconstructor

**Comment by Regalis11** [comment] 2021-11-15 09:20
Found a way to repro this now: looks like it only happened with empty boxes. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/34c570b2747b8428c224badb156323b8cbc76850

**Comment by Rokvach** [comment] 2021-11-15 11:02
Tested, working correctly. Closing.

**Closed by Rokvach** 2021-11-15 11:02 UTC
Labels: Bug, Code
