### ISSUE TITLE
Guardians stunlock causing unfair and frustrating deaths

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#12291] opened 2023-07-05 19:50 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Guardians are relatively human-sized enemies intended to be fought with small arms. They're one of the most challenging creatures to fight, which is good, because most enemies are a breeze to kill with late-game gear.

However, guardians have the most frustrating tendency to occasionally give the player absolutely zero chance at fighting back by repeatedly using high stun melee attacks. I probably don't need to say it, but being well prepared for an engagement and just being completely immobilized while your health bar is whittled away is one of the most frustrating experiences.

This occurs randomly, but happens most often when the Guardian enters its low health emergency phase, where it usually spams melee attacks.
Fighting guardians is no fun when half the time you're just laying there, waiting to wake up. Maybe if they consistently stunlock you, that would be permissible (taking combat stim or using hyperzine to counteract might be a way to reduce stun, though requiring expensive drugs to combat stunlocking every time one goes into a ruin would be a little annoying), it's just that whether you kill the guardian or whether it kills you often just comes down to whether it decides to start spamming out melee attacks or not.

Attached is an example of this happening to me. I got about half a second of consciousness to use a medical item, but it didn't change much. 

https://github.com/Regalis11/Barotrauma/assets/37850646/2ef4f4fa-1223-47ce-af43-8036e70de352

Ideally, the outcome of a fight should depend on the preparedness and skill of the player, not whether the enemy decides to stunlock or not. Some stun is good, but when the enemy is attacking so rapidly that the player is completely unable to act, then that just leads to frustration.

This particular instance happened in unstable version 1.3.3.0, but has been happening for as long as I can remember.

### Reproduction steps

1. enter a ruins
2. find a guardian and engage it in melee combat. fighting in small rooms and when the guardian is at low health increases the chance of it happening
3. get stunlocked

May require several attempts

### Bug prevalence

Happens every now and then

### Version

v1.0.21.0

### -

1.1.3.0 unstable. (not sure why unstable isn't in the Version options)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-07-11 15:19
Thank you for the report! I unfortunately couldn't find a way to reproduce this. The only stun attack the fractal guardians seem to have is the 0.2 second stun on the melee attack, which should not be enough to stunlock a character. The harpoon attack also seems to cause a very brief 0.3 second stun.

I tested it in a couple of different scenarios, with the 1st and 2nd guardian variant at different amounts of health, but I could not get the character to get stunned at all, excluding the brief "microstuns" when receiving damage:

https://github.com/Regalis11/Barotrauma/assets/14351070/c0a12fb1-697a-452d-87f6-c83079e17572

**Comment by Vykn** [comment] 2023-07-13 04:04
After spending an hour or so testing, I have a few conclusions, but am still not quite sure what's going on fully.

Previously, I didn't realise that all of the attacks only had a small amount of intended stun; I assumed that they had multiple melee attacks, and one of them just had a large amount of stun. So this lead me to testing whether the guardian was hitting multiple times and thus stacking the stun, but found that each attack only corresponded to a single hit. (My methodology for this was to make the attacks cause 1 of a specific affliction, so I could check with the health scanner to see how many attacks were done - this is why some of the below clips have the guardian causing deep tissue and gunshot damage)
The only conclusion that I can think of is that the amount of applied stun is just sometimes much higher than it's supposed to be.

From my testing: The harpoon attack always seems to do the correct amount of stun (well, a very small amount of stun at the least - I can't measure to an accuracy of one tenth of a second) but the melee attack occasionally just does much more than the intended amount. It doesn't happen super often; every ~1 in 10 melee attacks would cause the target to become knocked out for a second or two. I couldn't tell if there was any pattern (i.e. I'm not sure if the increased stun was more likely to happen in a sequence of attacks, rather than just happening randomly). The stunlocking (as shown in the original ticket above and also in some clips below) occurs when this increased stun happens multiple times in a row.

I did not find any difference between different sized rooms, as I suggested above. I think that the experience of smaller rooms = more stunlock arose out of the fact that only the melee attacks cause a large stun, and so in smaller rooms, a guardian is more likely to be in melee range.
The increase in stunlocking in the low health "emergency" is likely caused by the guardian receiving an amount of vigor, which increases the power of the melee attack (and so the stun), rather than any AI changes.

The video you linked was a little difficult to assess (the low framerate and rapid moving of the camera, and it is also difficult to see if your character is stunned because the main indication is the disappearance of the hotbar, which is cropped out), but for a notable section of it, the guardian is not even attacking, and only does a few melee attacks. (I briefly touch on the strange passive behaviour below)
During my testing, a majority of the guardians' melee attacks were doing small amounts of stun, but I did not find much trouble in getting the guardian to cause large amounts of stun. And while complete stunlocking was not by any means common, it was not incredibly rare to see.

Below are some clips from my testing

1) Guardian doing several high-stun attacks in a row, causing a near stunlock

https://github.com/Regalis11/Barotrauma/assets/37850646/599947a2-07ae-4677-9bd6-834aae635798


2) Guardian doing several high-stun attacks in a row, (would have caused a deadly stunlock if I didn't have enough defense to tank the attacks)

https://github.com/Regalis11/Barotrauma/assets/37850646/a05337c7-4189-48c0-a183-8e6e62598eaf


3) More stunlocking

https://github.com/Regalis11/Barotrauma/assets/37850646/11ccb56e-18c3-4bad-af85-388ae0805b84


4) Guardian doing a high-stun attack and just leaving mid fight

https://github.com/Regalis11/Barotrauma/assets/37850646/f5898bee-55f1-40e4-8339-00ebf5bd58d4

The 4th final clip shows the guardian seemingly losing interest mid-fight. I experienced this very infrequently (and I believe this happened in your clip) but it's a little odd.

I hope this added information and testing helps

**Comment by Vykn** [comment] 2023-07-13 04:36
Ok so I did some more testing and found out the cause.

I just tried to get the high-stun attacks to occur when in the open ocean, but was unsuccessful, so it had to have something to do being inside (since it occurs inside both ruins and water-filled submarines).

What tipped me off was the comical behaviour that occurs when out of water;

https://github.com/Regalis11/Barotrauma/assets/37850646/b21f1911-8265-4faa-a2df-5c30776c6591

I recalled that when impacting walls at high speeds, characters are stunned (for the case when the submarine crashes at high speeds and people go flying). So to test it, I created a tiny box to see if the impact with the walls was causing the issue.

https://github.com/Regalis11/Barotrauma/assets/37850646/c722b6de-1107-4700-9ead-ffe7de96b2f1

So, I believe that the issue has nothing to do with the guardians' attacks, but instead with how much they launch characters, and if they are close to a wall and impact with enough force, they will be stunned for a very long time.

**Comment by Regalis11** [comment] 2023-09-22 12:25
Could not reproduce in the latest unstable. I suspect this was caused by the same issue as https://github.com/Regalis11/Barotrauma/issues/12577 (impact damage from the guardian's weapon causing a stun)

**Comment by Jasontti** [comment] 2023-09-28 14:36
Tested in latest traitor-update revision: 34b31dd764

Was able to be be stunlocked in closed environment.
I wiggled cursor to see when stun was applied.

https://github.com/Regalis11/Barotrauma/assets/8488224/3b4f9555-9248-46ad-85c5-ef3893c452e6

**Comment by Regalis11** [comment] 2023-10-02 08:51
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/19c3bc8b4b04bde30628a6768bac40bd0bce8b1f

**Comment by Jasontti** [comment] 2023-10-23 08:56
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4488/commits/2b575c97307f8d5c9de8d14e5e9b1142e4f17ed5

Created same test setup as previously and i was able to fight guardian without getting stunlocked.

No issues found
Closing ticket

**Closed by Jasontti** 2023-10-23 08:56 UTC
Labels: Design, Balance
