### ISSUE TITLE
Don't even know what to call this bug.

### ISSUE THREAD

**Issue by CryIz** [Regalis11/Barotrauma#313] opened 2018-03-04 21:18 UTC
(Native resolution: 1920x1080)

Resolution: 1920x1080
https://cdn.discordapp.com/attachments/380630218039361536/419855355036565519/unknown.png

Resolution: 1280x720 (1920x1080)
https://cdn.discordapp.com/attachments/380630218039361536/419855846357467140/unknown.png

I don't know what to point out...
Video card: NVIDIA GeForce 940MX
Processor: Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz

P.S. one screenshot is made with mod and the other in vanilla, but the effect is the same.
P. S. S. I long could not understand why well see all beings as someone very close can not to notice them.

**Comment by CryIz** [comment] 2018-03-04 21:28
1920x1080
https://cdn.discordapp.com/attachments/380630218039361536/419853030515671056/unknown.png

1280x720 (1920x1080)
https://cdn.discordapp.com/attachments/380630218039361536/419853738497277952/unknown.png

**Comment by Regalis11** [comment] 2018-03-05 09:46
Which version is this, v0.8.0.4 or the latest version in the repo? It could have been caused by the changes in da7ea77 but the edges of the LOS area look like it's using the older v0.8.0.4 version of the rendering code with the new LOS shader.

**Comment by CryIz** [comment] 2018-03-05 12:44
This v0.8.0.4.
I tested it with a modification for the server, and with BTE, and vanilla.

**Comment by Regalis11** [comment] 2018-12-03 19:20
Haven't found a way to reproduce the issue or gotten any other reports of this, I'll close this for now and reopen if the problem reappears.

**Closed** 2018-12-04 19:32 UTC
Labels: Graphics-related, bug, need more info
