### ISSUE TITLE
Outpost claimed by wrong faction on Multiplayer Clients

### ISSUE THREAD

**Issue by UserC2** [Regalis11/Barotrauma#12495] opened 2023-08-13 02:51 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

* An outpost is claimed by a faction (in my case, the Europa Coalition)
* The outpost icon shows it belongs to the Europa Coalition
* **On the client's map,** hovering over the outpost shows it belongs to the Jovian Separatists (incorrect)
* **On the host's map,** hovering over the outpost shows it belongs to the Europa Coalition (correct)

Also see #11331

### Reproduction steps

1. Play a multiplayer game (with at least one client) until a new outpost forms from an empty junction.
2. On the client, hover over the exclamation point beside the newly formed outpost.
3. The message displayed will show a different faction than the one owning the outpost.

### Bug prevalence

Just once

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-08-28 10:27
Should be addressed in https://github.com/Regalis11/Barotrauma-development/commit/5e4da7f2b3a31b02375f3b1c7800ce83390953f7 (commit in our private repo).

Note for testing: this seems to happen randomly when the location changes to a Separatist one. Reproducible by jumping around locations until you get a location to be claimed by the Separatists.

**Comment by Jasontti** [comment] 2024-01-18 08:41
Could not reproduce those errors.

Outposts are shown correctly for host and client.

Closing ticket

**Closed by Jasontti** 2024-01-18 08:41 UTC
Labels: Bug, Code, Networking, Testing branch
