### ISSUE TITLE
Gamecrash when selecting two hulls and naming them

### ISSUE THREAD

**Issue by Melolatius** [Regalis11/Barotrauma#4572] opened 2020-12-19 23:52 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
So, I was naming several hulls with the same name and thought that I would save time if I select them all and enter the roomname. I did this, and then the game crashed

**Steps To Reproduce**
Place two hulls
Select them (CTRL+LMB)
Enter a name (I had one saved and just pasted it with CTRL+V

**Version**
Windows 10
![grafik](https://user-images.githubusercontent.com/63376072/102701991-a60a0b80-425d-11eb-8454-f8c5f49c9e10.png)

**Additional information**
Crashreport
[crashreport (39).log](https://github.com/Regalis11/Barotrauma/files/5720302/crashreport.39.log)
[crashreport (40).log](https://github.com/Regalis11/Barotrauma/files/5720301/crashreport.40.log)

**Comment by 3e849f2e5c** [comment] 2020-12-20 20:03
This happens because the default name of a hull is not an empty string but a null pointer, to work around this make sure all selected hulls already have a name set

**Comment by 3e849f2e5c** [comment] 2021-01-04 08:24
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c149384548afb988177d38ad7d90dbfc2c38322b

**Comment by Rokvach** [comment] 2021-01-11 09:53
Tested, wasn't able to reproduce. Working correctly. Closing.

**Closed by Rokvach** 2021-01-11 09:53 UTC
Labels: Bug, Code, Crash
