### ISSUE TITLE
Purchased item doesn't appear in Multiplayer save upon loading

### ISSUE THREAD

**Issue by gaogzs** [Regalis11/Barotrauma#7861] opened 2021-12-19 15:47 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Purchased item doesn't appear in Multiplayer save upon loading

**Steps To Reproduce**
Play a multiplayer campaign as the host, let your friend disconnect halfway. Proceed to the next station yourself, buy something and start a new run. Quit to the main menu, restart the server and enter the save while your friend has connected, and you'll see the items you purchased do not appear, there is no "item delivered" notification either, however, the new crew you hired would still appear, but without their equipment.[save file](https://drive.google.com/file/d/16g5pK_dUOhEzSotX4pxglhn2ixAQ5ILN/view?usp=sharing)

**Version**
0.15.22.1 Windows

**Additional information**

**Comment by atlas-callisto** [comment] 2021-12-19 17:57
Might be related to #7853 perhaps?

**Comment by Regalis11** [comment] 2022-01-04 13:15
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7853

**Closed by Regalis11** 2022-01-04 13:15 UTC
