### ISSUE TITLE
Body Swap on Rejoin. Also Cloned Character? And someone else is controlling my inventory somehow.

### ISSUE THREAD

**Issue by gerakis** [Regalis11/Barotrauma#7796] opened 2021-12-16 08:38 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When host of server returns us all to lobby and restarts the game, I end up controlling someone elses character. Only im also controlling my old character, or its mirroring my movements or something? Weve got a big problem here. Ive attached a video to better explain because I dont know exactly whats going on. On top of that someone else is changing my inventory around.

**Steps To Reproduce**
In multiplayer, join a game. Have the host return to lobby. Then start the game again. You will be controlling some new character and someone else will be controlling your old one. Your old character will be standing next to your new body and be copying your movements. Someone else will be controlling you inventory. Its bizarre. Something has gone terribly wrong here.

**Version**
0.15.21.0 Windows 10 x64

**Additional information**
https://youtu.be/Z2lOICn6-2U

That is not me moving my inventory around in the video.

**Comment by Kaillera** [comment] 2021-12-16 12:54
I usually find this is like some sort of memory leak. I usually close my server entirely and/or restart Barotrauma, and then reboot it to get it sort out for another while before it happens again.

**Comment by Regalis11** [comment] 2021-12-17 13:47
Duplicate of https://github.com/Regalis11/Barotrauma/issues/6678

**Closed by Regalis11** 2021-12-17 13:47 UTC
Labels: Bug, Code, Networking
