### ISSUE TITLE
Bug Crash Report

### ISSUE THREAD

**Issue by SeijiRyu** [Regalis11/Barotrauma#2939] opened 2020-05-31 09:38 UTC
Here is the crash report that keeps happening on my game, really frustrating.

__________________________________________________________________________________________

Barotrauma Client crash report (generated on 31/05/2020 16:35:35)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

023CCD07C102F6331CAD29D2EADB01E0

Game version 0.9.9.1 (ReleaseWindows, branch release, revision 1968ab79f)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: SkaaniTopol
Loaded submarine: Dugong (A4CDC47861570A757C168EEC1BCD3CB9)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)

System info:
    Operating system: Microsoft Windows NT 10.0.18363.0 64 bit
    GPU name: Intel(R) UHD Graphics 630
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.
 (SharpDX.SharpDXException)
Device removed reason: HRESULT = 0x887A0006
Target site: Void CheckError()
Stack trace: 
   at SharpDX.Result.CheckError()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent()
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Barotrauma.Program.Main(String[] args)
_____________________________________________________________________________________________________

Any solution to fix this problem? Or just need to wait for next patch of the game?

**Comment by Regalis11** [comment] 2020-05-31 12:36
Duplicate of #1833

**Closed by Regalis11** 2020-05-31 12:36 UTC
