### ISSUE TITLE
Tandem Fire while no one else is alive crashes game

### ISSUE THREAD

**Issue by Liberation546** [Regalis11/Barotrauma#7468] opened 2021-11-24 05:35 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When operating a periscope while no other crewmembers are alive, and you have the talent Tandem Fire, the game crashes.

**Steps To Reproduce**
- Start a game in a submarine with a turret
- Kill every crewmember besides yourself
- Learn Tandem Fire through console commands
- Attempt to operate the periscope

**Version**
Windows v0.15.13.0

**Additional information**
Tested in singleplayer with Humpback, no mods.

**Comment by Regalis11** [comment] 2021-11-24 07:28
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7378

**Closed by Regalis11** 2021-11-24 07:28 UTC
