### ISSUE TITLE
[Unstable 0.15.19.0] Attempted to add an order with no target entity to CrewManager!

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#7690] opened 2021-12-09 22:14 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
This happened in multiplayer campaign

We were doing a VIP Transport mission when suddenly during a Mudraptor encounter the console was spammed with the following error message 5 times

```
Attempted to add an order with no target entity to CrewManager!
   at System.Environment.get_StackTrace()
   at Barotrauma.CrewManager.AddOrder(Order order, Nullable`1 fadeOutTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\CrewManager.cs:line 50
   at Barotrauma.Networking.ChatMessage.ClientRead(IReadMessage msg) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\ChatMessage.cs:line 103
   at Barotrauma.Networking.GameClient.ReadIngameUpdate(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2295
   at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 770
   at Barotrauma.Networking.SteamP2PClientPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2PClientPeer.cs:line 237
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 641
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 960
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59
```

**Steps To Reproduce**
No known repro steps

**Version**
Unstable 0.15.19.0

**Comment by ekqvist** [comment] 2021-12-13 09:48
Unable to reproduce the issue. But I improved the error handling (Regalis11/Barotrauma-development@c604888) in hopes of resolving this at some point if it occurs again. I made it into a warning instead of an error so you shouldn't get spammed with it as badly. I also included the order name into the message and made Game Analytics also log the error when possible.

**Comment by JoneKone** [comment] 2022-01-09 00:01
```
Attempted to add an order with no target entity to CrewManager!
   at System.Environment.get_StackTrace()
   at Barotrauma.CrewManager.AddOrder(Order order, Nullable`1 fadeOutTime) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameSession/CrewManager.cs:line 50
   at Barotrauma.Networking.ChatMessage.ClientRead(IReadMessage msg) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Networking/ChatMessage.cs:line 103
   at Barotrauma.Networking.GameClient.ReadIngameUpdate(IReadMessage inc) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Networking/GameClient.cs:line 2296
   at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Networking/GameClient.cs:line 770
   at Barotrauma.Networking.LidgrenClientPeer.HandleDataMessage(NetIncomingMessage inc) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Networking/Primitives/Peers/LidgrenClientPeer.cs:line 137
   at Barotrauma.Networking.LidgrenClientPeer.Update(Single deltaTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Networking/Primitives/Peers/LidgrenClientPeer.cs:line 105
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Networking/GameClient.cs:line 641
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 962
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/SDL/SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 59
```

No idea what trickered it

**Comment by ekqvist** [comment] 2022-01-10 08:32
Thanks for the report. However, I've still been unable to reproduce the issue. I have included the order name in the message, but this change isn't included in the current build yet so this will have to wait for now.

**Comment by Rokvach** [comment] 2022-04-29 12:49
There hasn't been any sightings in GA about this, so should we just close it?

**Comment by ekqvist** [comment] 2022-05-01 20:56
I would say it's fine if we close this. There also haven't been reports of this in a while. We can always reopen there's another report or we see it resurface through GA.

**Closed by ekqvist** 2022-05-01 20:56 UTC
Labels: Bug, Code, Waiting
