### ISSUE TITLE
[Unstable] Infinite experience on docking to a station, can't go back to lobby

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#6875] opened 2021-10-09 12:55 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I joined the server, watching it unfold in spectator mode. When they docked, what you see in the video started:
https://youtu.be/HAqha7lwiJA
It happened when docking to the other station.
Trying to revert to server lobby was just giving experience and didn't work.

**Steps To Reproduce**
Unknown. More info:
They were finishing 2 missions, to transport explosive cargo and destroy a mudraptor nest.
I joined the server with a game already going. I remember that yesterday the host closed the server when I was carrying a duffle bag with valuable things.
After we restarted that mission it was fine for a while but after a few missions it happened again.

**Version**
v0.1500.6.0

**Read my comments below**
`temp` folder:
https://drive.google.com/drive/folders/1-VMrdhOb_f-XEkz7mi0B74Ee-gBklnJa?usp=sharing
My log file:
https://drive.google.com/file/d/1-gIWMFUIp-AM5OwNqlEw9ycuWrLZGRqB/view?usp=sharing
Host's log file:
https://drive.google.com/file/d/1-oa_cw7yYyKbmgclGistRdIv4lHi202C/view?usp=sharing

**Comment by Krzeszny** [comment] 2021-10-09 13:06
After the host went back to the main menu and started the last mission again, I lost all points and traits (left with 0/500)

**Comment by Krzeszny** [comment] 2021-10-09 18:05
It happened again. When this bug started happening, my character started to reset each time I joined that server and respawned.

**Comment by Regalis11** [comment] 2021-10-11 07:14
Duplicate of https://github.com/Regalis11/Barotrauma/issues/6806

**Closed by Regalis11** 2021-10-11 07:14 UTC
