### ISSUE TITLE
Hash generated by the published mod is sometimes always different because of some formatting issues

### ISSUE THREAD

**Issue by evilfactory** [Regalis11/Barotrauma#8915] opened 2022-04-22 14:58 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
For example, if i have in the mod, the following file
```xml
<Items>
</Items>
```
it will get converted into this when publishing the mod:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Items></Items>
```

causing what i assume, the hash miss match errors

**Steps To Reproduce**
1) Make a mod with the example i mentioned earlier
2) Publish it on workshop
3) Watch you get Hash Calculation errors in your console

**Version**
v0.17.12.0 Windows 10

**Additional information**
This is a shot in the dark to try explain why these hash calculation errors happen
![image](https://user-images.githubusercontent.com/36804725/164740403-6ba8a5bf-6d1e-4e09-a261-cfd70757d7e9.png)

**Comment by Regalis11** [comment] 2022-04-22 16:17
Duplicate of https://github.com/Regalis11/Barotrauma/issues/8874

**Closed by Regalis11** 2022-04-22 16:17 UTC
