### ISSUE TITLE
Low performance

### ISSUE THREAD

**Issue by meltdown1910** [Regalis11/Barotrauma#8975] opened 2022-04-26 03:45 UTC
- [* ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
There are a large number of players complaining about their poor performance within the outposts. Personally, I am totally stuck in the outposts, my fps drops to 5 fps. in unplayable

**Steps To Reproduce**
I just start the game and the outpost lags

**Version**
V 0.17.12.0
Windows 10 Pro

**Additional information**
I tried to decrease the graphic quality but there is no change

AMD FX-8800P Radeon R7 Processor, 12 Compute Cores 4C+8G 2.10 GHz
Installed RAM 16.0 GB (15.0 GB usable)
System type 64-bit operating system, x64 processor

**Comment by Chotat0** [comment] 2022-04-26 04:12
Same problem here but it happens when anything fills with water. Even when drained fully, singleplayer, no bots, no enemies, the FPS doesn't come back up above 5.

Specs: Windows 7 Ultimate
AMD FX 8350 Black Edition @ 4.0ghz (not overclocked)
24gb DDR3 Hyper X Fury RAM, 2 sets both in dual channel.
MSI RTX 2070 Super (Not overclocked)
Asrock Extreme 3 mini ITX motherboard
AOC 144hz monitor

**Comment by Regalis11** [comment] 2022-04-26 08:22
Duplicate of https://github.com/Regalis11/Barotrauma/issues/8961

**Closed by Regalis11** 2022-04-26 08:22 UTC
