### ISSUE TITLE
Higher quality stun guns with Fulgurium Stun Gun Darts stun for less with Beat Cop

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#11795] opened 2023-04-10 16:07 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I've only modified the stun afflictions to show up on the health scanner for visibility.
Masterwork Stun Guns loaded with Fulgurium Stun Gun Darts seem to inflict less stun with the talent Beat Cop.
Security Officer without any talents:
![image](https://user-images.githubusercontent.com/115734437/230938902-e5cdeb4c-c0c7-43b8-9028-354a30f425d4.png)
Security Officer with the talent Beat Cop:
![image](https://user-images.githubusercontent.com/115734437/230938920-8b441653-e59e-4e56-a166-e246d6a2df6f.png)
It looks like at normal quality the talent effect works as intended but quality bonus + talent bonus doesn't work right.
Occurs on both stable and unstable build.

### Reproduction steps

1. (optional) modify stun afflictions to appear on health scanner
2. Use masterwork stun gun loaded with fulgurium darts on target
3. Take Beat Cop talent and repeat step 2
4. Compare the stun duration before and after Beat Cop

### Bug prevalence

Happens regularly

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Udrakan** [comment] 2023-04-11 00:24
Good catch! I've played a stun cop a lot recently and wish this gets fixed relatively soon.

**Comment by Regalis11** [comment] 2023-04-11 07:21
Thank you for the report!

I'm afraid I could not find a way to reproduce this. In both cases, the darts seem to cause a 30 second stun (which is the maximum). 

Beat Cop + Masterwork Stun Gun + Fulgurium Dart:
![image](https://user-images.githubusercontent.com/14351070/231085749-c4690591-e012-4a01-908b-6effc929e077.png)

**Comment by HawkinsThe71st** [comment] 2023-04-11 08:41
I tried it out on some other creatures, I guess it doesn't matter for creatures with lower health since the inflicted stun is enough to max out the affliction in both cases
Without Beat Cop:

https://user-images.githubusercontent.com/115734437/231103004-7b802aaf-bb53-4b55-b132-2090bf8b7e73.mp4

With Beat Cop:

https://user-images.githubusercontent.com/115734437/231103832-a684bd85-b644-4d23-a7a7-a2049308d98d.mp4

**Comment by Regalis11** [comment] 2023-04-11 10:25
Ah, yeah, looks like I needed to attack a tougher monster to reproduce this! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2bb53a72f3220b24303fe6a0134aacbb6efc1db4

> Fixed CharacterAbilityModifyAffliction not working properly when applying a max strength affliction on something that has damage modifiers. E.g. you couldn't apply a maximum stun to mudraptors with the Beat Cop talent and high-quality stun guns - the strength would get clamped to max in CharacterAbilityModifyAffliction, and the stun resistances applied after that

**Comment by Jasontti** [comment] 2023-05-30 10:05
Got error in testing.
Seems to only happen with human targets and with beat cop talent.
Stun gun and dart quality is irrelevant.
Being in or out of the sub does not matter.

Steps to reproduce:
1. Start round
2. Get normal stun gun and normal stun gun darts
3. Give talent "Beat cop" to player character
4. Shoot another human and wait for them to get stunned

`Attempted to set an affliction to an invalid strength (Infinity)
   at System.Environment.get_StackTrace()
   at Barotrauma.Affliction.set_Strength(Single value) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\Afflictions\Affliction.cs:line 38
   at Barotrauma.HumanAIController.OnAttacked(Character attacker, AttackResult attackResult) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\HumanAIController.cs:line 1220
   at Barotrauma.Character.DamageLimb(Vector2 worldPosition, Limb hitLimb, IEnumerable`1 afflictions, Single stun, Boolean playSound, Single attackImpulse, Character attacker, Single damageMultiplier, Boolean allowStacking, Single penetration, Boolean shouldImplode) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 4132
   at Barotrauma.StatusEffect.Apply(Single deltaTime, Entity entity, IReadOnlyList`1 targets, Nullable`1 worldPosition) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\StatusEffects\StatusEffect.cs:line 1678
   at Barotrauma.StatusEffect.Apply(ActionType type, Single deltaTime, Entity entity, ISerializableEntity target, Nullable`1 worldPosition) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\StatusEffects\StatusEffect.cs:line 1391
   at Barotrauma.Affliction.ApplyStatusEffect(ActionType type, StatusEffect statusEffect, Single deltaTime, CharacterHealth characterHealth, Limb targetLimb) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\Afflictions\Affliction.cs:line 475
   at Barotrauma.Affliction.Update(CharacterHealth characterHealth, Limb targetLimb, Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\Afflictions\Affliction.cs:line 436
   at Barotrauma.CharacterHealth.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\CharacterHealth.cs:line 828
   at Barotrauma.Character.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 3166
   at Barotrauma.AICharacter.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AICharacter.cs:line 38
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 3016
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 186
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 885
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58`

**Comment by Jasontti** [comment] 2023-05-30 12:18
Stun effect is not applying correctly when using masterwork stun gun, fulgurium dart and beat cop talent.
Stun strength is same with normal and masterwork quality of weapons. Beat cop talent has little to no effect.

![stungun fulgd normal beatc](https://github.com/Regalis11/Barotrauma/assets/8488224/1a054bd1-4d94-4090-9c80-1bfa2fb821ab)
![stungun fulgd masterw beatc](https://github.com/Regalis11/Barotrauma/assets/8488224/d8497cb7-a8ed-4273-ac18-5f2de657c541)

**Comment by Jasontti** [comment] 2023-05-31 06:23
Tested and issue was fixed in https://github.com/Regalis11/Barotrauma-development/pull/4122/commits/019e66326ec670a31dcb9db771f165db3b78035e
Closing ticket.

**Closed by Jasontti** 2023-05-31 06:23 UTC
Labels: Bug, Code
