### ISSUE TITLE
[0.9.903] Dead Thalamus Organs Blocking Projectiles

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2598] opened 2020-04-09 23:54 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
It's hard to combat cells inside a Thalamus because dead organs also blocks projectiles.

**Version**
~0.9.903

**Comment by itchyOwl** [comment] 2020-04-13 08:13
This was a confirmed issue in the earlier unstable builds, but now it should have been fixed. Can you specify the context where it happens? I can't reproduce it anymore.

**Comment by Kaillera** [comment] 2020-04-13 10:38
Trying to shoot cells pursuing you in the middle of hallways that previously had live organs.

**Comment by Regalis11** [comment] 2020-04-13 14:05
I was able to repro this simply by trying to fire at something through the organ's collider. The previous fix (https://github.com/Regalis11/Barotrauma-development/commit/37a3158) did prevent the hit effects from being applied to the item, but wouldn't prevent the collider from blocking the raycast, meaning that the projectile would hit the organ and do nothing.

Should be fixed now in https://github.com/Regalis11/Barotrauma-development/commit/37a3158

**Comment by Rokvach** [comment] 2020-04-13 15:22
No issues, closing.

**Closed by Rokvach** 2020-04-13 15:22 UTC
Labels: Bug, Code
