### ISSUE TITLE
Bots taking a long time to determine lowest path cost

### ISSUE THREAD

**Issue by ReconDoge** [Regalis11/Barotrauma#7788] opened 2021-12-15 22:48 UTC
It would seem that after the update, bots are stopping randomly on their path to calculate something called 'path cost', which makes them take periodic 5-10 seconds pauses when moving to their destination. In custom subs, this issue is very pronounced and bots sometimes end up staring at a door for 20 seconds at a time without moving anywhere. 

To reproduce:
1. Use the humpback and enable debugai.
2. Tell a bot to move to a location from one side of the sub to another by either instructing them to operate or fix something.
3. They will sometimes suddenly stop when moving, only to resume after a lower path cost has been determined, but often this takes a while.

Version: Windows V0.15.21.0

**Comment by Ek-Videogames** [comment] 2021-12-17 19:48
The delay can get **_very long_** on vanilla subs if you order bots to cleanup items - and then drop an item on the floor somewhere in the submarine.

**Comment by itchyOwl** [comment] 2022-01-03 09:35
I'd suspect the delay comes from seeking a valid item/target, not the pathing, which is an intentional performance optimization. If that's the case, it could be that we need to adjust the amount of items being checked per each frame. Pathing happens after a valid target has been found, so it can _appear_ that calculating the path would be the cause of it. I'll look into it.

**Comment by itchyOwl** [comment] 2022-01-04 11:50
I did some testing, but the only issue I could find was that the bots sometimes halted next to a door for a couple (max 3) seconds when they shouldn't. Fixed that in Regalis11/Barotrauma-development@7191185.

**Comment by Rokvach** [comment] 2022-01-20 10:15
Tested, working correctly. Closing.

**Closed by Rokvach** 2022-01-20 10:15 UTC
Labels: Bug, Needs testing, Code
