### ISSUE TITLE
Just bought the game, game wil not start, crashes when watching the first video intro. (added some mods, removed some,tried launching,and crash over and over cant even start the game to remove all the mods to be able to fix the crash *BRICKED my game)

### ISSUE THREAD

**Issue by STOLKAH** [Regalis11/Barotrauma#3519] opened 2020-08-07 02:06 UTC
Barotrauma Client crash report (generated on 8/6/2020 9:56:35 PM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

EFAC70B2719BEBECDF0597D16251FCBE

Game version 0.10.4.0 (ReleaseWindows, branch release, revision 20132d25fb)
Graphics mode: 2560x1440 (Fullscreen)
VSync OFF
Language: English
Selected content packages: Vanilla 0.9, U-1211, Jotunn, BUNGO'S REVENGE - MK8, Nautilus, EK Reliant Mk-V, Meaningful Upgrades, SMS Olympus, Hagel, Sentinel, [KSMC]-Kimsun, Mule-Class, EuroCurrency, Sherpa, Vengeful_Spirit_Mk_4.0, XanMonsters, Huskmod, Shipwrecks Extended, GunLights, Advanced Lifepod, VisualVarietyPack, XanMonsters2, Deep Sea Alcohol, Balalaika, Project PAKETA Mk.One, Scavenger Uno, Let Me Choose !, USSF NR-1 'Nerwin', Unlimited Headset Batteries, Super Mining Sonar, Lightsaber, Bayan, Sea Monk, K-4  H.O.M.I.E.  shuttle v2.26, SeaBovine MkII, Doomslayer(InfiniteOxygen), Improved Divesuits, overwhelming fires, Medic Bag, Uylsses 2.06 improved, Svarog, [BP] Smart Systems Pack, VapeMod, The Bell (Extended), Russian Guitar, EK Utilities, EK Armory, EK Utility ITA Comp Patch, EK Armory ITA Comp Patch, Colonial Marines, Instrumental Music Mod, Vengeance, Sweet Pea, Cyclops Mk-II, ALIEN - XENOMORPH-Fix, IntoTheAbyss, Hydroponics, Hydroponics Patched
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.18363.0 64 bit
    GPU name: NVIDIA GeForce GTX 1060 6GB
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: One or more errors occurred. (Object reference not set to an instance of an object.) (System.AggregateException)
Target site: Void ThrowIfExceptional(Boolean)
Stack trace: 
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Barotrauma.GameMain.<>c__DisplayClass97_0.<Load>b__2(Task task) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 467
   at Barotrauma.TaskPool.<>c__DisplayClass5_0.<Add>b__0(Task t, Object obj) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Utils\TaskPool.cs:line 52
   at Barotrauma.TaskPool.Update() in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Utils\TaskPool.cs:line 69
   at Barotrauma.GameMain.Update(GameTime gameTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 999
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59

InnerException: Object reference not set to an instance of an object.
Target site: Void Init()
Stack trace: 
   at Barotrauma.LocationType.Init() in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Map\Map\LocationType.cs:line 210
   at Barotrauma.GameSettings.RefreshContentPackageItems(IEnumerable`1 files) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\GameSettings.cs:line 439
   at Barotrauma.GameSettings.DeselectContentPackage(ContentPackage contentPackage) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\GameSettings.cs:line 345
   at Barotrauma.Steam.SteamManager.RemoveMods(Func`2 predicate, Boolean delete) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Networking\SteamManager.cs:line 1244
   at Barotrauma.Steam.SteamManager.AutoUpdateWorkshopItemsAsync() in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Networking\SteamManager.cs:line 1430
Last debug messages:
[8/6/2020 9:56:35 PM] Loading additional location types from file 'Mods/XanMonsters2/Map/LocationTypes.xml'
[8/6/2020 9:56:35 PM] Loading additional location types from file 'Mods/XanMonsters/Map/LocationTypes.xml'
[8/6/2020 9:56:35 PM] Error in  in location type Mine - could not find a job with the identifier "assistant".
[8/6/2020 9:56:35 PM] Couldn't find a job prefab with the given identifier: assistant
[8/6/2020 9:56:35 PM] Error in  in location type Mine - could not find a job with the identifier "mechanic".
[8/6/2020 9:56:35 PM] Couldn't find a job prefab with the given identifier: mechanic
[8/6/2020 9:56:35 PM] Error in  in location type Mine - could not find a job with the identifier "engineer".
[8/6/2020 9:56:35 PM] Couldn't find a job prefab with the given identifier: engineer
[8/6/2020 9:56:35 PM] Error in  in location type Research - could not find a job with the identifier "captain".
[8/6/2020 9:56:35 PM] Couldn't find a job prefab with the given identifier: captain
[8/6/2020 9:56:35 PM] Error in  in location type Research - could not find a job with the identifier "securityofficer".
[8/6/2020 9:56:35 PM] Couldn't find a job prefab with the given identifier: securityofficer
[8/6/2020 9:56:35 PM] Error in  in location type Research - could not find a job with the identifier "assistant".
[8/6/2020 9:56:35 PM] Couldn't find a job prefab with the given identifier: assistant
[8/6/2020 9:56:35 PM] Error in  in location type Research - could not find a job with the identifier "medicaldoctor".
[8/6/2020 9:56:35 PM] Couldn't find a job prefab with the given identifier: medicaldoctor
[8/6/2020 9:56:35 PM] Error in  in location type Research - could not find a job with the identifier "mechanic".
[8/6/2020 9:56:35 PM] Couldn't find a job prefab with the given identifier: mechanic
[8/6/2020 9:56:35 PM] Error in  in location type Research - could not find a job with the identifier "engineer".
[8/6/2020 9:56:35 PM] Couldn't find a job prefab with the given identifier: engineer
[8/6/2020 9:56:35 PM] Error in  in location type Military - could not find a job with the identifier "medicaldoctor".
[8/6/2020 9:56:35 PM] Couldn't find a job prefab with the given identifier: medicaldoctor
[8/6/2020 9:56:35 PM] Error in  in location type Military - could not find a job with the identifier "mechanic".
[8/6/2020 9:56:35 PM] Couldn't find a job prefab with the given identifier: mechanic
[8/6/2020 9:56:35 PM] Error in  in location type Military - could not find a job with the identifier "engineer".
[8/6/2020 9:56:35 PM] Couldn't find a job prefab with the given identifier: engineer
[8/6/2020 9:56:35 PM] Error in  in location type Military - could not find a job with the identifier "assistant".
[8/6/2020 9:56:35 PM] Couldn't find a job prefab with the given identifier: assistant
[8/6/2020 9:56:35 PM] Error in  in location type Military - could not find a job with the identifier "captain".
[8/6/2020 9:56:35 PM] Couldn't find a job prefab with the given identifier: captain
[8/6/2020 9:56:35 PM] Error in  in location type Military - could not find a job with the identifier "securityofficer".
[8/6/2020 9:56:35 PM] Couldn't find a job prefab with the given identifier: securityofficer
[8/6/2020 9:56:35 PM] Error in  in location type Outpost - could not find a job with the identifier "captain".
[8/6/2020 9:56:35 PM] Couldn't find a job prefab with the given identifier: captain
[8/6/2020 9:56:35 PM] Error in  in location type Outpost - could not find a job with the identifier "securityofficer".
[8/6/2020 9:56:35 PM] Couldn't find a job prefab with the given identifier: securityofficer
[8/6/2020 9:56:35 PM] Error in  in location type Outpost - could not find a job with the identifier "medicaldoctor".
[8/6/2020 9:56:35 PM] Couldn't find a job prefab with the given identifier: medicaldoctor
[8/6/2020 9:56:35 PM] Error in  in location type Outpost - could not find a job with the identifier "mechanic".
[8/6/2020 9:56:35 PM] Couldn't find a job prefab with the given identifier: mechanic
[8/6/2020 9:56:35 PM] Error in  in location type Outpost - could not find a job with the identifier "engineer".
[8/6/2020 9:56:35 PM] Couldn't find a job prefab with the given identifier: engineer
[8/6/2020 9:56:35 PM] Error in  in location type Outpost - could not find a job with the identifier "assistant".
[8/6/2020 9:56:35 PM] Couldn't find a job prefab with the given identifier: assistant
[8/6/2020 9:56:35 PM] Error in  in location type City - could not find a job with the identifier "captain".
[8/6/2020 9:56:35 PM] Couldn't find a job prefab with the given identifier: captain
[8/6/2020 9:56:35 PM] Error in  in location type City - could not find a job with the identifier "securityofficer".
[8/6/2020 9:56:35 PM] Couldn't find a job prefab with the given identifier: securityofficer
[8/6/2020 9:56:35 PM] Error in  in location type City - could not find a job with the identifier "medicaldoctor".
[8/6/2020 9:56:35 PM] Couldn't find a job prefab with the given identifier: medicaldoctor
[8/6/2020 9:56:35 PM] Error in  in location type City - could not find a job with the identifier "mechanic".
[8/6/2020 9:56:35 PM] Couldn't find a job prefab with the given identifier: mechanic
[8/6/2020 9:56:35 PM] Error in  in location type City - could not find a job with the identifier "engineer".
[8/6/2020 9:56:35 PM] Couldn't find a job prefab with the given identifier: engineer
[8/6/2020 9:56:35 PM] Error in  in location type City - could not find a job with the identifier "assistant".
[8/6/2020 9:56:35 PM] Couldn't find a job prefab with the given identifier: assistant
[8/6/2020 9:56:35 PM] Content package load order: Vanilla 0.9  |  U-1211  |  Jotunn  |  BUNGO'S REVENGE - MK8  |  Nautilus  |  EK Reliant Mk-V  |  Meaningful Upgrades  |  SMS Olympus  |  Hagel  |  Sentinel  |  [KSMC]-Kimsun  |  Mule-Class  |  EuroCurrency  |  Sherpa  |  Vengeful_Spirit_Mk_4.0  |  XanMonsters  |  Huskmod  |  Shipwrecks Extended  |  GunLights  |  Advanced Lifepod  |  VisualVarietyPack  |  XanMonsters2  |  Deep Sea Alcohol  |  Balalaika  |  Project PAKETA Mk.One  |  Scavenger Uno  |  Let Me Choose !  |  USSF NR-1 'Nerwin'  |  Unlimited Headset Batteries  |  Super Mining Sonar  |  Lightsaber  |  Bayan  |  Sea Monk  |  K-4  H.O.M.I.E.  shuttle v2.26  |  SeaBovine MkII  |  Doomslayer(InfiniteOxygen)  |  Improved Divesuits  |  overwhelming fires  |  Medic Bag  |  Uylsses 2.06 improved  |  Svarog  |  [BP] Smart Systems Pack  |  VapeMod  |  The Bell (Extended)  |  Russian Guitar  |  EK Utilities  |  EK Armory  |  EK Utility ITA Comp Patch  |  EK Armory ITA Comp Patch  |  Colonial Marines  |  Instrumental Music Mod  |  Vengeance  |  Sweet Pea  |  Cyclops Mk-II  |  ALIEN - XENOMORPH-Fix  |  IntoTheAbyss  |  Hydroponics  |  Hydroponics Patched
[8/6/2020 9:56:31 PM] Overriding the ui styles with 'Mods/IntoTheAbyss/Content/UI/style_ita.xml'
[8/6/2020 9:56:31 PM] Overriding the ui styles with 'Mods/GUN. THEM. DOWN !/GTD/Content/UI/style.xml'
[8/6/2020 9:56:31 PM] Attempting to open ALC device "OpenAL Soft on Speakers (Realtek(R) Audio)"
[8/6/2020 9:56:31 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean, Unknown
[8/6/2020 9:56:31 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[8/6/2020 9:56:30 PM] Logged in as STOLKAH (SteamID STEAM_1:0:5179521)

**Comment by hubismal** [comment] 2020-08-07 02:39
have you tried verifying your files

**Comment by Alakazoo1232** [comment] 2020-08-07 11:34
I had the same error message show up when I unsubscribed the Into The Abyss mod to play vanilla. I fixed it by re-subscribing to the mod and disabling it in-game instead.

**Comment by juanjp600** [comment] 2020-08-18 12:04
Duplicate of #3500

**Closed by juanjp600** 2020-08-18 12:04 UTC
Labels: Bug, Code, Crash
