### ISSUE TITLE
Crash on launch (SteamManager.InstallWorkshopItem())

### ISSUE THREAD

**Issue by Stupitar** [Regalis11/Barotrauma#5042] opened 2021-02-12 15:26 UTC
[crashreport (84).log](https://github.com/Regalis11/Barotrauma/files/5972689/crashreport.84.log)
game crashes while loading
v 0.12.0.2
macOS 11.2.1

**Comment by juanjp600** [comment] 2021-04-14 18:51
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/a9772d9e85a47debbf13092dd06082d5982ea7f4

**Comment by Rokvach** [comment] 2021-05-25 08:21
There hasn't been any sightings to this crash nor issues caused by the fix. Seems to be working correctly, closing.

**Closed by Rokvach** 2021-05-25 08:21 UTC
Labels: Bug, Code, Crash
