### ISSUE TITLE
Make it possible to attach items to level walls

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#4295] opened 2020-11-12 18:32 UTC

**Comment by Regalis11** [comment] 2020-11-12 18:33
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/e01ff29642f3f50f98e82223408fc1fef0a6cd16

**Comment by Rokvach** [comment] 2020-11-13 10:50
You can place a item really far inside the wall but you aren't able to interact with it 
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/bc63680a-879b-4a99-98f3-35d91b138ebd)

**Comment by Regalis11** [comment] 2020-11-13 12:00
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2e39645fc05d2e9d92004f26b7e99204fbba6967

**Comment by Xeavas** [comment] 2020-11-13 17:41
[0.1100.0.6] - Working as intended, no issues. 👍

**Comment by Rokvach** [comment] 2020-11-13 18:54
Closing.

**Closed by Rokvach** 2020-11-13 18:54 UTC
Labels: Code, Feature request, Needs testing
