### ISSUE TITLE
Multiplayer: disconnects every time host switch maps

### ISSUE THREAD

**Issue by DeeCeptor** [Regalis11/Barotrauma#5591] opened 2021-04-24 05:35 UTC
In multiplayer, when the host switches the map (from city to ocean), it disconnects several players from the lobby.

We are using passworded lobby. This bug has been present for several months, and is still present 4/23/2021

**Comment by Regalis11** [comment] 2021-04-26 07:24
Thank you for the report! Do you remember what the error message says (if there's any) when the players disconnect? Or would it be possible to provide us a screenshot of the error?

**Comment by Regalis11** [comment] 2021-05-05 08:20
Most likely a duplicate of https://github.com/Regalis11/Barotrauma/issues/5702, closing this one

**Closed by Regalis11** 2021-05-05 08:20 UTC
Labels: Bug, Code, Need more info, Networking
