### ISSUE TITLE
Lamp - wrong illumination

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#8044] opened 2022-01-15 23:03 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Lamp - wrong illumination

**Steps To Reproduce**
- See additional information!
- Set range 100
- Not repeated in other places!?

https://user-images.githubusercontent.com/93348499/149640316-9fadee3d-135e-4ece-acff-8205fdae1211.mp4

**Version**
v0.15.23.0, Vanilla 0.9 (Windows 10-x64).

**Additional information**
Sub file: [_Lamp_Test-1.zip](https://github.com/Regalis11/Barotrauma/files/7876066/_Lamp_Test-1.zip)

![Image 001_02-10](https://user-images.githubusercontent.com/93348499/149640611-b6b903ef-127f-4f8a-8757-2eac857b65bc.png)

**Comment by Regalis11** [comment] 2022-01-17 08:04
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3366

**Closed by Regalis11** 2022-01-17 08:04 UTC
