### ISSUE TITLE
AIs/bots get stuck between on Humpback's stairs (on a ledge)

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#11217] opened 2023-02-12 00:26 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?
Bots periodically get stuck in that spot between floors. The only way to unstuck them is to deal stun damage. You can't drag them off.
![Barotrauma_SwfeppdW1e](https://user-images.githubusercontent.com/10529134/218286767-c9a991c8-88fa-410a-a9b3-46a0e586d8b2.png)

### Reproduction steps

Play for about 30 minutes

### Bug prevalence

Happens regularly

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by BiffW** [comment] 2023-02-12 12:32
Same issue happens on Winterhalter sometimes.

**Comment by Regalis11** [comment] 2023-02-12 15:23
Duplicate of https://github.com/Regalis11/Barotrauma/issues/2296

**Closed by Regalis11** 2023-02-12 15:23 UTC
