### ISSUE TITLE
Outpost Glitch

### ISSUE THREAD

**Issue by ndevenney1002** [Regalis11/Barotrauma#9007] opened 2022-04-27 23:11 UTC
- [ Yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The wiring in one of the large outposts isn't set up correctly so none of the machines 

**Steps To Reproduce**
Its just one of the complexes isn't wired correctly

**Version**
Current Patch Windows

**Comment by Regalis11** [comment] 2022-04-28 07:24
Duplicate of https://github.com/Regalis11/Barotrauma/issues/8884

**Closed by Regalis11** 2022-04-28 07:24 UTC
