### ISSUE TITLE
Dedicated server don't show it's mods list in Server Browser

### ISSUE THREAD

**Issue by pavel4win** [Regalis11/Barotrauma#11453] opened 2023-03-04 16:52 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

OS of my server is Windows 7
I load DS through SteamCMD, forwarded ports 27015 & 27016
Manually copy mods (installed on my client machine) in folder 
c:\Users\MyName\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\WorkshopMods\Installed
Then I add "regularpackages" section in file 
"config_player.xml" in DS folder.
All right, my server appears in ServerBrowser
Buy list of mods is empty, and nobody exept me can connect.
I can connect to it, bacause "regularpackages" section on my client is same as on server.
But this information not shares in server browser!
Players can not join my server at all,
because they do not see the list of mods installed on it.
Does it means that a dedicated server can only be used with vanilla content?
How I can solve this problem?
If a dedicated server really has such limitations.
Is it possible to use a GUI server as a dedicated server?
Can I start the GUI server, and connect to it from another computer?
Can I somehow start the server with GUI
on the first computer and then, log in using the same Steam account on the second computer and play on my server?
Or I have only to buy two copies of Barotrauma on two different Steam accounts, first for GUI server, second for gameplay?

### Reproduction steps

1. Start dedicated server with some mods
2. Find this server in Server Browser in game
3. Look for it's mod list, it is empty.

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-03-05 13:55
Thank you for the report!

The dedicated server should support mods exactly the same way servers hosted from in-game do. It's hard to tell what the issue is here, but I would suspect the config file is somehow misconfigured. What kind of error messages do the clients get when they try to connect? Are you sure the mods are properly enabled (i.e. when you join the server yourself, do you see the modded content in the game)? 

What kind of mods are they? It's worth noting that mods that only contain submarines or shuttles aren't listed in the server browser - only mods that you need to download and enable to be able to join the server are, but submarines and shuttles can be just downloaded as needed after you've joined the server.

> Is it possible to use a GUI server as a dedicated server?
> Can I start the GUI server, and connect to it from another computer?

Yes: actually hosting from in-game just launches the dedicated server executable (which the game then connects to automatically), so in a sense you can run the server using a GUI just by selecting "host server" from in-game.

> Can I somehow start the server with GUI on the first computer and then, log in using the same Steam account on the second computer and play on my server?
> Or I have only to buy two copies of Barotrauma on two different Steam accounts, first for GUI server, second for gameplay?

If you host from in-game, you need a Steam account for each client, but dedicated servers can be hosted using SteamCMD without the need for a separate account.

**Comment by pavel4win** [comment] 2023-03-06 06:38
I sent to you configuration files of my server, and logs of my server.
So you can see the list of mods.
Mods are activated but not all.
The BetterHealthUI mod didn't work. The treatment interface has remained the same.
After I executed in the console of my client "cl_reloadlua"
The treatment interface has changed, i.e. BetterHealthUI works.
The Stations From Beyond and DynamicEuropa mods seem to work fine.

I am not able to see the errors of other players who tried to join
I can only say that while playing on the server
in the logs there were messages that the player was connected,
and a few seconds later that player disconnected.
When I tried to join myself, with an empty mod list,
the server offered to download the missing mods,
When I agreed, when loading mods, the progress bar did not move.

Just now I tried to start my server and connect to it.
I succeeded. The list of mods from the server obviously has been received and the mods have been loaded.
For some reason, 2 mods were reloaded.
Enhanced Armament and
Super Mining Sonar + oClock Sonar
Even though I already have them installed.
The rest of mods appear to be working fine.

I've noticed bugs in the server browser.
1. The server description has been truncated in the server browser. Only part of the description is displayed.
I'm attaching a screenshot.
2. Almost all servers in the server list are marked as Dedicated
do not display the list of mods in the server browser.
instead it says "unknown" in the mod list.

![2023-03-06_08-18-50](https://user-images.githubusercontent.com/47295383/223036574-b2288471-c15c-4f18-aedd-bcb1a019782a.png)

[logs.zip](https://github.com/Regalis11/Barotrauma/files/10895034/logs.zip)

[configs.zip](https://github.com/Regalis11/Barotrauma/files/10895038/configs.zip)

**Comment by Regalis11** [comment] 2023-03-06 08:41
Thank you for the clarification! 

I think the issue here is that if you're using Lua for Barotrauma, you cannot use DedicatedServer.exe. The vanilla server executable does not support Lua mods, you need to instead use the modified server executable provided by the mod. BetterHealthUI does not seem to contain any content files the supported by the vanilla game (only C# scripts), so listing it in the content package list is up to the mod.

**Comment by pavel4win** [comment] 2023-03-06 12:05
Of course, I downloaded LUA and installed it manually
to my dedicated server. According to the instructions described here:
https://evilfactory.github.io/LuaCsForBarotrauma/lua-docs/manual/installing-lua-for-barotrauma-manually/
So I don't have a vanilla one, but a LUA dedicated server.
LUA is running on my Dedicated Server.
The main problem is that the list of server mods is not displayed in Server Brower
and (maybe) players can't join me. Although I'm not sure about the last. I'll try to find a friend who will check this assumption. And then I will write to you.
I understand that you already have a lot of work. So don't give my problems the highest priority. I'll let you know if I find valuable information.

**Comment by pavel4win** [comment] 2023-03-06 12:27
Is it possible that the list of mods used by the server is stored in some separate file other than config_player.xml?
And Dedicated Server simply does not have this file?
And the file must be copied from my client to server manually?

**Comment by Regalis11** [comment] 2023-03-06 12:54
It seems Lua for Barotrauma includes it's own config file, stored in the mod folder. Did you edit that, not the one inside the game folder?

To me it seems like the underlying issue here might be something in the mod itself. The vanilla game does not list Lua mods in the list of mods, because they only contain file types that aren't used by the vanilla game. So it might be that it's an issue that should be addressed in the mod.

**Comment by pavel4win** [comment] 2023-03-06 23:15
Today I created the server on my computer,  using a graphical interface.
I started Lua server of course.
I played for about 6 hours.
The recording can be viewed here
https://www.twitch.tv/pavel4win
During this time, players tried to connect to me about eight times.
And the players never succeeded.
Why it may be? How it can be? Unbelievable.
I sent to you logs and settings of my server.

[20230306ServerLogs.zip](https://github.com/Regalis11/Barotrauma/files/10903775/20230306ServerLogs.zip)
[AloneSetting.zip](https://github.com/Regalis11/Barotrauma/files/10903777/AloneSetting.zip)

**Comment by pavel4win** [comment] 2023-03-07 18:45
Today I played for three hours, recorded on twitch.
During this time, two players were able to join me.
At first one joined, played a little, then disconnected.
Perhaps he was thrown away. On disconnected on its own.
Then another joined, with him we completed the mission and docked.
At the end of the mission, he disconnected by time out.
Maybe he just disconnected on his own because I told him I was going to stop playing.
If interested, I can send the logs of this game.
Today I will transfer to a dedicated server all the settings and the save files of my server.
My DS is on a separate computer.
Since now, will play on DS.
Because I have a slow computer, streaming through OBS slows down a lot.
Here is a triple load: server, client and streaming software.
I'll see if players can join me on a dedicated server.
Let me know if you are interested in the logs.

**Comment by Regalis11** [comment] 2023-03-07 19:36
Thanks for the extra info!

I think I was able to reproduce this at my end now. It does seem like this was caused by `dedicated-server-rule-retrieval-reliability`. Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/78afd2bf404607af3d3badc6689325ffadccf875

> Fix (or rather a workaround) to dedicated servers' content package info getting truncated to 255 bytes, causing the lengths of the name, hash and id arrays to not match, which made the clients display the server's packages as "unknown". Now we list each package separately. 

Although, I'm not completely sure if the inability to the connect to the server is a separate issue or caused by the same bug. I think the important thing in diagnosing this would be the exact error message when the clients disconnect, so if you somehow manage to figure out what it is, that'd most likely help us a lot in diagnosing the problem. Thanks and sorry for the trouble!

**Comment by pavel4win** [comment] 2023-03-08 07:32
give me advice how can I get
" exact error message when the clients disconnect"
where can I found the error description? In the server log? on in the system log?

**Comment by Regalis11** [comment] 2023-03-08 08:01
The client who disconnects should get some kind of an error popup and/or possibly an error message in the debug console. Although, I ofc understand it might be impossible for you to get the information from a client who failed to connect. :/

**Comment by pavel4win** [comment] 2023-03-09 18:23
Today I played on my dedicated server
A player tried to join me
He tried to join twice
First, I must explain how my server is arranged.
I have two computers. The computers are on the local network 192.168.1.xx
Router address 192.168.1.1
First computer
Intel Core i3-2100 / ram 16 gb / disk SSD / windows 7 sp1 / IP 192.168.1.128
Barotrauma dedicated server installed on the first computer
Second computer
Intel Core i3-2100 / ram 16 gb / disk SSD / windows 10 / IP 192.168.1.191
Video Radeon RX580 8Gb
On the second computer I play.
Since I don't have a static IP
I rented a linux server Ubuntu 20.04 LTS (ENG) for $2 per month.
Server IP address 194.87.94.145
Domain goodsite.online
I CAN connect to my server in local network on address 192.168.1.128 AND through the internet on address 194.87.94.145
Both methods works fine.
On the linux server I installed OpenVPN server IP 10.8.0.1/16
I forwarded ports 27015 and 27016 to computer 192.168.1.128 so my server can be seen from the internet. I don't know how to configure iptables so I found a solution on the internet. Possibly suboptimal. Here is my iptables settings file:
-------------------------------------------------- ----------------------------
# Reset firewall settings
iptables -F
iptables -X
iptables -t nat -F
iptables -t nat -X

#Allow forwarding via tunnel
iptables -I INPUT -i tun0 -j ACCEPT
iptables -I FORWARD -i tun0 -j ACCEPT
iptables -I OUTPUT -o tun0 -j ACCEPT
iptables -I FORWARD -o tun0 -j ACCEPT

# Allow connections initiated by us from outside
iptables -A INPUT -i eth0 -m state --state ESTABLISHED,RELATED -j ACCEPT

# Allow SSH connections
iptables -A INPUT -i eth0 -p tcp --dport 22 -j ACCEPT

# Allow transit connections initiated by us from the outside
iptables -A FORWARD -i eth0 -o tun0 -m state --state ESTABLISHED,RELATED -j ACCEPT

# allow internet http and https protocols
iptables -A FORWARD -i eth0 -p tcp --dport 80 -j ACCEPT
iptables -A FORWARD -i eth0 -p tcp --dport 443 -j ACCEPT

# allow nat
iptables -t nat -A POSTROUTING -j MASQUERADE

# input 27015 tcp & udp
iptables -A INPUT -i eth0 -p tcp --dport 27015 -j ACCEPT
iptables -A INPUT -i eth0 -p tcp --dport 27016 -j ACCEPT
iptables -A INPUT -i eth0 -p udp --dport 27015 -j ACCEPT
iptables -A INPUT -i eth0 -p udp --dport 27016 -j ACCEPT

# forward 27015 tcp & udp
iptables -A FORWARD -i eth0 -p tcp --dport 27015 -j ACCEPT
iptables -A FORWARD -i eth0 -p tcp --dport 27016 -j ACCEPT
iptables -A FORWARD -i eth0 -p udp --dport 27015 -j ACCEPT
iptables -A FORWARD -i eth0 -p udp --dport 27016 -j ACCEPT

# Forward 27015 port to server tcp & udp
iptables -t nat -A PREROUTING -d 194.87.94.145 -p udp --dport 27015 -j DNAT --to-destination 10.8.0.10:27015
iptables -t nat -A POSTROUTING -d 10.8.0.10 -p udp --dport 27015 -j SNAT --to-source 194.87.94.145

iptables -t nat -A PREROUTING -d 194.87.94.145 -p tcp --dport 27015 -j DNAT --to-destination 10.8.0.10:27015
iptables -t nat -A POSTROUTING -d 10.8.0.10 -p tcp --dport 27015 -j SNAT --to-source 194.87.94.145

# Forward 27016 port to server tcp & udp
iptables -t nat -A PREROUTING -d 194.87.94.145 -p udp --dport 27016 -j DNAT --to-destination 10.8.0.10:27016
iptables -t nat -A POSTROUTING -d 10.8.0.10 -p udp --dport 27016 -j SNAT --to-source 194.87.94.145

iptables -t nat -A PREROUTING -d 194.87.94.145 -p tcp --dport 27016 -j DNAT --to-destination 10.8.0.10:27016
iptables -t nat -A POSTROUTING -d 10.8.0.10 -p tcp --dport 27016 -j SNAT --to-source 194.87.94.145
-------------------------------------------------- ----------------------------
I don't like that fact the dedicated server barotrauma thinks that any joining client has an IP address of 10.8.0.1
But so far I haven't found a better way to set it up.
Perhaps you can advise me how to properly configure port forwarding.
Both of my computers have the OpenVPN client installed.
The gateway to the internet is 10.8.0.1
When the player tring to join, I saw error messages in the server console:
The first time he tried to join, the message was:
------------------------------------------------
[[03/09/2023 19:13:00]
  Игрок Aniaolol присоединился к серверу.
[[03/09/2023 19:13:00]
  Saving client permissions
Failed to send message to 10.8.0.1:60115: Dropped
… this message repeated 55 times …
Failed to send message to 10.8.0.1:60115: Dropped
[[03/09/2023 19:13:02]
Игрок Aniaolol покидает сервер.
------------------------------------------------
The second time he tried to join, the message was:
[[03/09/2023 19:15:14]
  Игрок Aniaolol присоединился к серверу.
[03/09/2023 19:15:14]
  Saving client permissions
Failed to send message to 10.8.0.1:34737: Dropped
… this message repeated many times …
Failed to send message to 10.8.0.1:34737: Dropped
[[03/09/2023 19:15:16]
Игрок Aniaolol покидает сервер.
------------------------------------------------
There were no more attempts to connect to me.
I was surprised that both times different ports were specified. Or is it because of NAT?
When I finished the game, dock, and disconnected from the server, the following message appeared in the console:
03/09/2023 19:39:34]
  Round ended.
Failed to send message to 192.168.1.191:65012: Dropped
Failed to send message to 192.168.1.191:65012: Dropped
Failed to send message to 192.168.1.191:65012: Dropped
Failed to send message to 192.168.1.191:65012: Dropped
Failed to send message to 192.168.1.191:65012: Dropped
Failed to send message to 192.168.1.191:65012: Dropped
Failed to send message to 192.168.1.191:65012: Dropped
Failed to send message to 192.168.1.191:65012: Dropped
[03/09/2023 19:40:00]
  Поль Казански покидает сервер.
And there was again different port.

That is all, sorry for so many chars.
Also sent to you today's server log

[AloneInTheAbyss twitch.tvpavel4win today at 1500 GMT._2023-03-09_1920.zip](https://github.com/Regalis11/Barotrauma/files/10934812/AloneInTheAbyss.twitch.tvpavel4win.today.at.1500.GMT._2023-03-09_1920.zip)

**Comment by pavel4win** [comment] 2023-03-10 04:22
I'm surprised that error messages are not written to the server's log file. 
They are written only to the server console. 
It may be possible to set up a more detailed log mode when all errors are written to a file? 
Then I won't have to look for them in the server console.

**Comment by pavel4win** [comment] 2023-03-13 18:28
When I run port forwarding through my VPN server,
then my dedicated server appears normally in the server browser.
I easily join it at my server external ip address 194.87.94.145
And By domain name goodsite.online
And by my internal ip address 192.168.1.128
And by selecting it in the list of servers in the server browser.
But besides me, no one can join him.
Every time when someone tries to join the message appears:
Failed to send message to 10.8.0.1:xxxx: Dropped
The port specified after the colon is different each time.
The port number is in the range between 1000 and 65535
Firewall in my Windows 7 on the dedicated server is completely off
There is no Firewall on my linux VPN server.

Yesterday I tried to disable the VPN on my dedicated server.
And perform port forwarding on my router as written in your instructions.
As a result, my server does not appear in the server browser at all.
Also I could not connect to it using the ip-address issued to my router by the provider.
Help me please.
My computer is too slow and I can not perfectly play and host the server at the same time.
Also, I want to maintain a 24/7 dedicated server. But I can not.
if you don't have time, please, advice me someone who could help.

Here screenshot my router "virtual server page" records 15, 16 is
for barotrauma port forwarding

![2023-03-13_21-04-29](https://user-images.githubusercontent.com/47295383/224793225-c512bd67-30fa-4814-99e5-079381a8ec4b.png)

**Comment by arousle** [comment] 2023-04-22 21:04
>Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/78afd2bf404607af3d3badc6689325ffadccf875
> 
> > Fix (or rather a workaround) to dedicated servers' content package info getting truncated to 255 bytes, causing the lengths of the name, hash and id arrays to not match, which made the clients display the server's packages as "unknown". Now we list each package separately.

Apologies for asking, but has the workaround mentioned here made it into the current public release yet (since it's been a while since then)? I'm asking because I just ran into this issue myself so I'm interested in seeing it resolved, and I can't tell if the workaround has been merged since I don't have read access to the private repo. Thanks!

**Comment by Rokvach** [comment] 2023-04-27 08:27
Tested, working correctly. Can be merged and closed.

**Closed** 2023-04-27 08:34 UTC
Labels: Bug, Code, Networking, Modding
