### ISSUE TITLE
[Question] Pets and Hostility

### ISSUE THREAD

**Issue by Neko-LoverDisc** [Regalis11/Barotrauma#4364] opened 2020-11-21 16:01 UTC
I've noticed that pets [in my case orange boy] seem to be particularly hostile at times. when I had orange boy, it attacked multiple people even when well fed and happy. Also pets were fighting with each other and I had to run across the sub with orange boy as Cthulhu tried to kill him. Is this intended behavior, or is it a bug? If it isn't a bug, how do I stop it? The players did nothing to it and the second it was in their sight for the first time (not subsequent times), it usually attacked them without warning. The pet was well fed and played with, because I did nothing but play with it and feed it for over 15 minutes.

**Comment by ezjamsen** [comment] 2020-11-24 21:07
This is a bug, however it's a great one so we'll fix it, and then implement aggression properly as part of general creature behavior. 

Let's say that hunger or general mistreatment will create a small but accumulating chance of the creature snapping and going rogue. @itchyOwl any thoughts?

**Comment by Neko-LoverDisc** [comment] 2020-11-24 22:43
If I can comment about it, I'd say that also pets defending their owners (which should be in the game, if its not a bug) shouldn't be trigger by accidentally getting burned by someones welder. Also, I believe that if pets for example, get hit by a welder, they shouldn't immediately go all aggressive due to the fact it could've been a complete accident, especially if a crewmate is frantically swinging around their welder in attempts to find that one breach

**Comment by ezjamsen** [comment] 2020-11-25 09:13
Pets defending their owner is a pretty nice idea too. We can consider that as well.

**Comment by itchyOwl** [comment] 2020-11-25 12:38
Pets are defending the owner when they have the ai target "owner" and state "protect" defined in the ai block, as I think there should be. There's no logic for handling how much damage is done or anything. This is something that has been handled in the human ai and it has proven to be quite complicated. I wouldn't want to introduce same complexity here. However, I think we could categorically check that the offender is not a friendly. But that would make the pets not target any crew member, regardless if they do damage to the owner. Another thing to consider might be a simple threshold, like if the damage is less than 1 hp, then just ignore the attacker.

What comes to the pets attacking even when they are happy, I think @juanjp600 knows the best how it should work. If the issue is due to the reactions to the damage, adding the threshold might fix it.

**Comment by ezjamsen** [comment] 2020-11-25 12:41
By the way, are you able to find this ticket in zenhub?

**Comment by juanjp600** [comment] 2020-11-25 17:20
I implemented something to address this: https://github.com/Regalis11/Barotrauma-development/commit/7e661b06b6ed1a5dac06e8f1a88f54188663d403

Currently it's set up so pets will tolerate up to 5 damage before defending their owners, which should be enough to stop any minor welding-related accidents from enraging them.

**Comment by itchyOwl** [comment] 2020-11-26 10:09
I tested it and fixed a few things. But I think it now works as it should. Reminder: when testing that this doesn't break anything, remember to also test how the bots (both npcs and crew members) react to attacks.

**Comment by Regalis11** [comment] 2020-11-29 16:08
Should this be moved to QA?

**Comment by Rokvach** [comment] 2021-01-13 09:56
Tested, I was only able to cause the pets to aggro when I attacked their owner with something else than a welder or a plasma cutter. The pets forgot about me when I docked back to the outpost, so seems to be working correctly. Closing.

**Closed by Rokvach** 2021-01-13 09:56 UTC
Labels: Bug, Code
