### ISSUE TITLE
Copy-paste/clipboard jank

### ISSUE THREAD

**Issue by Veritius** [Regalis11/Barotrauma#4548] opened 2020-12-17 10:55 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When using the in-game clipboard with the sub editor, CTRL+C and CTRL+V don't work all the time. Sometimes I have to press it multiple times. It's extremely irritating (and maybe damaging my keyboard every time I press paste really hard in a futile attempt to get it to work

**Steps To Reproduce**
Honestly, no idea. I can provide system information and game files if needed.

**Version**
![image](https://user-images.githubusercontent.com/45957058/102483800-5a1e6180-40b9-11eb-8a27-72735b81ccea.png)

**Comment by 3e849f2e5c** [comment] 2020-12-18 10:59
This is most likely caused by keyboard focus subscription, when you edit a property on the right hand menu the entire panel takes keyboard focus and prevents global keybinds from being used until it is destroyed upon deselecting an item

**Comment by Veritius** [comment] 2021-01-25 23:18
That, @3e849f2e5c is exactly what happens.
I just didn't know how to describe it.

**Comment by 3e849f2e5c** [comment] 2021-02-25 17:00
Managed to find one case, if you use Mirror X or Mirror Y buttons the keybinds will stop working until you select a text box and deselect or when the property HUD is destroyed

**Comment by Regalis11** [comment] 2021-03-18 16:29
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3ec3d1644cf1d3580ce01cfc1dbaa155ef2a7428

**Comment by Rokvach** [comment] 2021-03-18 20:13
There's still some very strange things going on when copying things, especially if you change what you copy

I recorded a video about this, sadly I couldn't get my keystrokes on it so it needs a bit of explanation as to what is going on

1. At the start I copied the coilgun loader with Ctrl + C
2. I tried to Ctrl + V it outside the sub but it only showed up on the third time I pressed Ctrl + V (I rotated the mouse to show all the times I tried to paste it)
3. After successfully pasting it I selected the structure wall and copied it
4. When I went to paste the wall it pasted the previously copied coilgun loader instead
5. Cut the video at this time, but if I tried to copy the structure wall again and paste, it would of worked just fine. So its just the first time trying to copy it where it fails. 

https://www.youtube.com/watch?v=c8oSpsU0T2E

**Comment by Regalis11** [comment] 2021-03-19 09:18
I'm afraid I couldn't reproduce the issue by following those steps.

**Comment by Rokvach** [comment] 2021-03-19 09:42
Here's another video which shows keystrokes, for some reason it was even harder to copy and paste this time, had to double select the pieces before it actually copied them

https://www.youtube.com/watch?v=inXQoShPZRk

**Comment by Rokvach** [comment] 2021-05-12 10:20
Oh wow the copy pasting feels so responsive now, its like night and day. Working correctly, closing.

**Closed by Rokvach** 2021-05-12 10:20 UTC
Labels: Bug, Code
