### ISSUE TITLE
Artifact mission bug

### ISSUE THREAD

**Issue by lilSxulless** [Regalis11/Barotrauma#2732] opened 2020-04-28 17:21 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Alright, so I had this mission to bring the artifact. So I went for the artifact, but the signal was out of the place and when I went to the signal there was no artifact nor a temple.

**Steps To Reproduce**
I just started the game and got the first mission. If this will help this is my world seed: ZKCYWss0
I started the mission in Alkonost station and went to Meltwater station with this artifact mission.

**Version**
v0.9.9.0 steam version

**Additional information**
Not much but I ended up with 2 atmospere artifacts and I don't know what to do with them. Wish you could add selling option to the shop.

![image](https://user-images.githubusercontent.com/61995222/80517025-b266ee80-8984-11ea-9af2-f7c80951f9c6.png)

**Comment by Regalis11** [comment] 2020-07-09 11:11
Caused by the same issue as https://github.com/Regalis11/Barotrauma/issues/3141, closing

**Closed by Regalis11** 2020-07-09 11:11 UTC
Labels: Bug, Code
