### ISSUE TITLE
Wreck1 Cargo Buttons requires id_card to press

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2778] opened 2020-05-07 11:31 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Wreck1 Cargo Buttons requires id_card to press

**Version**
0.9.9.1

**Comment by Regalis11** [comment] 2020-05-07 13:31
Not sure if this is by design or an oversight, but added the bug tag for now.

Ping @daniaste

**Comment by danielasteljoki** [comment] 2020-05-07 13:40
Not a bug, except if they don't work with the cards found on the wreck.

**Comment by Kaillera** [comment] 2020-05-07 14:42
@daniaste they don't work with wreck_id

**Comment by danielasteljoki** [comment] 2020-05-07 16:04
Ok, sounds like an oversight. I'll take a look.

**Comment by danielasteljoki** [comment] 2020-05-15 06:24
Should work with idcards found on board the wreck now.

**Comment by Rokvach** [comment] 2020-05-16 11:46
No issues, closing.

**Closed by Rokvach** 2020-05-16 11:46 UTC
Labels: Bug, Design
