### ISSUE TITLE
Crash report: Exception: Function does not accept floating point Not-a-Number values.

### ISSUE THREAD

**Issue by pavel4win** [Regalis11/Barotrauma#12759] opened 2023-10-04 23:37 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

This happened in the single player campaign. During the mission.
There are started a fire in junction boxes.
I ordered the bots to put out the fire.
They grabbed fire extinguishers and then the game crashed.

crash report is here
[crashreport (23).log](https://github.com/Regalis11/Barotrauma/files/12810879/crashreport.23.log)

### Reproduction steps

Really, I do not know.

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-10-05 07:31
Thank you for the report! I couldn't think of a way to reproduce this either, but I added some error checks that should prevent this from crashing the game anymore, and log some extra information to GameAnalytics that might help us diagnose the issue. Commit in our private repo: https://github.com/Regalis11/Barotrauma-development/commit/aa30285a616ae9373a3d063c225d4c68ed7ce4c2

**Comment by pavel4win** [comment] 2023-10-06 08:16
Thank you for you attention.
Please, can you advise me where I can get a detailed manual on electrics in Barotrauma. I wonder what happens if power from several sources is supplied to one input? And why ship batteries works even if not connected? And similar tricks. So I need full manual, as full as  possible.

**Comment by Regalis11** [comment] 2023-10-09 07:48
There is no official manua I'm afraid, but there are most likely plenty of online tutorials and youtube videos where you can learn the ins and outs of the system.

>I wonder what happens if power from several sources is supplied to one input? 

Devices connected to the same input are considered part of the same electrical grid, so the device will pull power from all of the power sources.

> And why ship batteries works even if not connected?

I'm not sure what you mean by this, batteries should not work if they're not connected.

**Comment by SomeRandomNoobKekeke** [comment] 2023-10-09 15:23
well, i ran into i believe same crash with same error while trying to burn cultist nest with a flamer
I have a save file where i can reproduce it like 1/10 times with only perfomance fix as mod
I couldn't reproduce it on pure vanila, i guess either it's caused by perfomance fix or linked to some specific fps
[potato quality evidence](https://www.youtube.com/watch?v=maVET2gjE28)

**Comment by Regalis11** [comment] 2023-10-09 19:06
Unfortunately the performance fix mods is known to cause various kinds of issues, because of the way it modifies the update rates of various things (despite some of these things relying on them being updated every frame). I'm afraid there's not much we can do to address these kinds of issues in mods - the developer of the mod would need to solve them themselves if they want to modify the update rates the way they do in the mod.

**Comment by pavel4win** [comment] 2023-10-25 04:21
The same crash again, and again during junction box under fire.

[crashreport (24).log](https://github.com/Regalis11/Barotrauma/files/13161288/crashreport.24.log)

**Comment by Regalis11** [comment] 2023-10-25 06:25
> It is good idea to disable performance fix while performance is acceptable.

I would say it's a good idea to disable it in any case because it breaks the game. 🙃

**Comment by Regalis11** [comment] 2023-10-25 09:26
Anyhow, I did a bit of debugging on performance fix, and I think I found a way to address this in the vanilla code. Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/f77dd7e7f51534a099d110bfd71e8d25a1fcc435 (commit in our private repo)

**Comment by pavel4win** [comment] 2023-10-25 11:18
Alas, I have old slow computer, i3-2100 3 Ghz. Without performance fix in the middle of the game campaign, performance drops to several frames per second. Without performance fix , I wouldn’t have been able to finish the game at all.
Slightly deviating from the topic.
I would like to draw your attention to one bug in the gameplay.

https://github.com/Regalis11/Barotrauma/discussions/12911

**Comment by pavel4win** [comment] 2023-10-25 12:23
There's something strange about fires. My oxygen generator is turned off. The team wears diving suits. This means that the fire must go out very quickly, because there is no oxygen.
However, the fire quickly spreads and engulfs the submarine.

**Comment by MinecrackTyler** [comment] 2023-10-28 21:52
I had the same error when lowering the range on a lamp in the sub editor. Held the down arrow too long and it went into the negatives or something I guess, crashing the game.
[crashreport (4).log](https://github.com/Regalis11/Barotrauma/files/13196778/crashreport.4.log)

**Comment by pavel4win** [comment] 2023-10-29 08:53
> There is no official manua I'm afraid, but there are most likely plenty of online tutorials and youtube videos where you can learn the ins and outs of the system.
> 
> > I wonder what happens if power from several sources is supplied to one input?
> 
> Devices connected to the same input are considered part of the same electrical grid, so the device will pull power from all of the power sources.
> 
> > And why ship batteries works even if not connected?
> 
> I'm not sure what you mean by this, batteries should not work if they're not connected.

I assumed that the battery would only work as a backup power source if its “power out” connector is connected to the junction box.

As a result of experiments, I was convinced that electricity can be supplied to the ship's network through the "power in" connector.
so that the battery provides backup power to the vessel, there is no need to connect the “power out” connector to the junction box.

**Closed** 2023-11-24 16:15 UTC
Labels: Bug, Code, Crash
