### ISSUE TITLE
Players are still forced into Captain role even if you hired a Bot Captain

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4118] opened 2020-10-22 03:41 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Players are still forced into Captain role even if you hired a Bot Captain already, unless you pick Assistant.

**Version**
~0.10.6.3

**Additional information**
TBH no one likes the forced roles either. I hope we can have a toggle that allows players to play whatever they like, even if there's multiple of it.

**Comment by Momiro** [comment] 2020-10-28 03:29
I've noticed this as well, in legacy there was a server modification that let you set minimum jobs, and could set it to 0. I have also tried selecting assistant, and the bot captain is spawned, but the next player to join becomes captain.

**Comment by ezjamsen** [comment] 2021-01-04 07:46
I think we could at least test having an option to override role assignment, with basic check to make sure there's only one captain (randomly pick one of the players who made that role their first  choice, give the rest their second choice). It will allow for some pretty messed up crew configurations such as subs with 5 medics and a captain, but if it's a low effort server option, then I see no harm in at least testing and reviewing it.

**Comment by itchyOwl** [comment] 2021-01-29 14:33
It's because clients get their jobs assigned first and then all the bots in a second pass. Might require a bit of refactoring to change that. Didn't yet have time to look into it more.

**Comment by itchyOwl** [comment] 2021-02-01 09:03
Actually I'm not quite sure how to reproduce the issue. I don't think you can choose the roles for the bots in the lobby. So I suppose it was in the campaign that you hired a bot to be your captain? 

You can't start the campaign without a captain, but it seems that if you load a game the captain is not forced. So even if you'd start the game so that one of the clients is the captain and then continue without that client, no one should be forced as captain.

**Comment by Regalis11** [comment] 2021-05-27 14:29
No know steps to repro, closing

**Closed by Regalis11** 2021-05-27 14:29 UTC
Labels: Bug, Code, Design, Low prio, Need more info, Networking
