### ISSUE TITLE
Wearing bandolier makes toolbelt invisible

### ISSUE THREAD

**Issue by Smau35** [Regalis11/Barotrauma#11471] opened 2023-03-08 09:02 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When wearing bandolier your toolbelt becomes invisible if your wearing one
![image](https://user-images.githubusercontent.com/86321358/223669207-1a199918-6d1e-4f31-8daf-e8d8da44f558.png)

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-03-08 09:24
That's a safety harness, not a bandolier. Closing as a duplicate of https://github.com/Regalis11/Barotrauma/issues/11107

**Closed by Regalis11** 2023-03-08 09:24 UTC
