### ISSUE TITLE
0.1001.0.0 (Unstable) Bot becomes braindead after loading a save

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#2989] opened 2020-06-06 12:51 UTC
**Description**
Bot doesn't respond to any orders and only stands in 1 place. It responds to orders properly with chat responses, but doesn't do anything. Bot doesn't even respond to getting hurt. Dragging him does not wake him up. In Debugdraw, he has the proper task assigned and it looks like hes trying to do it.
-happened to character that I was controling almost all the time (when I switched to another)
-happened to character that I was almost never controling
-happened on Dugong
-happened on custom sub
-fixed by reloading the save, but sometimes have to reload twice

**Steps To Reproduce**
It's hard to reproduce, but when the bug happens, it's right after loading a saved game. Order bots to do tasks and see if one of them just stands in 1 place.

**Version**
0.1001.0.0 (Unstable)

**Comment by Regalis11** [comment] 2020-06-08 06:20
Is there a chance you might've switched the character during the "intro" where the camera pans to the controlled character? If so, https://github.com/Regalis11/Barotrauma-development/commit/4327a824af15f1284be84d48df9b4cadfa36cdcf should fix this.

**Comment by Rokvach** [comment] 2020-06-08 08:12
If it was caused by what Regalis mentioned then its working correctly now.

**Comment by Rokvach** [comment] 2020-06-08 11:16
Confirmed to be the case, closing as its working correctly. Can be reopened if it happens again on the next Unstable.

**Closed by Rokvach** 2020-06-08 11:16 UTC
Labels: Bug, Code
