### ISSUE TITLE
two perks stuck

### ISSUE THREAD

**Issue by SoNickRND** [Regalis11/Barotrauma#8627] opened 2022-03-26 18:34 UTC
- [х] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Somehow I have Weapons Engineer branch unlocked with one of two perks not selected, and can't select another perk in Physicist.

**Steps To Reproduce**
Have no idea.

**Version**
0.16.7.0
![Bara_Безымянный](https://user-images.githubusercontent.com/125238/160252676-9fd334d3-2d26-4f9c-afdd-c3e8f87063ca.png)

**Comment by SoNickRND** [comment] 2022-03-26 19:26
Here is save file
[Сохранение - копия (2).zip](https://github.com/Regalis11/Barotrauma/files/8356210/-.2.zip)

**Comment by cshingle** [comment] 2022-03-26 20:49
This has been an issue for a while. If you unlock the thermal googles (I forgot what the perk is called) It burns up some of your unlock (slots) when it unlocks the additional 3 perks above it and you can't finish out another tree. 
This really makes it a noob trap. Experienced players will unlock it last for no penalty because they already unlocked the rest of the trees where new players will not be aware of that it will prevent them from getting more perks latter in the game.

**Steps To Reproduce**
Start a campaign as an engineer, Use commands to give yourself just enough xp to unlock 12 perks, but pick the thermal googles perk before finishing out the other trees.

**Comment by Regalis11** [comment] 2022-03-27 09:52
Duplicate of https://github.com/Regalis11/Barotrauma/issues/8128

**Closed by Regalis11** 2022-03-27 09:52 UTC
