### ISSUE TITLE
Crash upon attempting to host

### ISSUE THREAD

**Issue by MudraptorSeks** [Regalis11/Barotrauma#8205] opened 2022-02-06 23:54 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
It is likely something on my end, because it worked fine for other people. when hosting a server, it says "connecting to [server name]" and then crashes.

**Steps To Reproduce**
Hosting a server of any kind results in a crash for me.

**Version**
This has been happening to me for quite a while. many versions covered, stable and unstable, starting almost a year and a half ago. It's probably my fault.

**Additional information**
I can't remember the first time this happened, but here is a crash report. 
[crashreport (24).log](https://github.com/Regalis11/Barotrauma/files/8011470/crashreport.24.log)

**Comment by Regalis11** [comment] 2022-02-07 08:17
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7783

**Closed by Regalis11** 2022-02-07 08:17 UTC

**Comment by MudraptorSeks** [comment] 2022-02-07 11:27
Uhhh wait
It may be a duplicate but there's still something wrong! Even all this time later 

So how do I fix it?
