### ISSUE TITLE
When you select the number of items to fabricate, sometimes a different value is used due to network latency

### ISSUE THREAD

**Issue by mygamingaccount** [Regalis11/Barotrauma#12279] opened 2023-07-04 00:33 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

https://github.com/Regalis11/Barotrauma/assets/68995233/3c356615-7ba3-41ff-a38b-10506a04dc05

### Reproduction steps

- Select the item to fabricate
- Move the "Amount" slider to the opposite end
- Click "Fabricate"

Due to network latency sometimes a different number will be selected.

### Bug prevalence

Happens every now and then

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment] 2023-07-04 07:09
Thank you for the report!

> Due to network latency sometimes a different number will be selected.

I doubt it's actually caused by latency, because the clients communicate turning on the fabricator in the same message as the amount they want to fabricate.

**Comment by giists** [comment] 2023-07-04 07:43
Repro steps confirmed.

**Comment by Regalis11** [comment] 2023-07-04 09:05
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e06fa2671904ab2567ad37ea2855e223039bf06f

**Comment by giists** [comment] 2023-07-26 08:57
Issue fixed, closing.

**Closed by giists** 2023-07-26 08:57 UTC
Labels: Bug, Code, Networking
