### ISSUE TITLE
[0.10.4.0] Joining a round sometimes all the players will be ragdolls and lots of desync.

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#3471] opened 2020-08-02 23:21 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

Rejoining seems to fix it sometimes. Other times you'll get 'Update from entity that doesn't exist' errors.

https://streamable.com/tn98nu

**Comment by Regalis11** [comment] 2020-08-17 07:26
Most likely a duplicate of https://github.com/Regalis11/Barotrauma/issues/3117

**Closed by Regalis11** 2020-08-17 07:26 UTC
