### ISSUE TITLE
[1300.0.x] Helm bot moves away from its target

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#5561] opened 2021-04-22 12:11 UTC
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When I give a bot the order to move to the endpoint the bot actually starts to move away from the end point once it gets close to it.

Expected: Bot stays around his ordered point (move to end point/ move to entry point) and stays close to it.

**Comment by Regalis11** [comment] 2021-04-22 16:45
I'm afraid I couldn't reproduce this (tested with Dugong and Humpback in single player). Does it happen in some specific sub? Was it a one-time occurrence or something that happens consistently?

**Comment by Regalis11** [comment] 2021-04-22 16:56
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3b8d422afdf252872944c1b4bf58528996108d1f

**Comment by Rokvach** [comment] 2021-05-03 06:36
Tested, working correctly. closing.

**Closed by Rokvach** 2021-05-03 06:36 UTC
Labels: Bug, Code
