### ISSUE TITLE
Random crashing

### ISSUE THREAD

**Issue by doct0rMATT** [Regalis11/Barotrauma#2762] opened 2020-05-02 22:50 UTC
![Screenshot (17)](https://user-images.githubusercontent.com/64712093/80894036-8c6c8180-8cd7-11ea-8bc9-212b715a4946.png)

**Description**
The game just crashes at random moments. It's happened 6 times playing with my friends in the space of 3 hours. I tried switiching my computer off and on again but no difference.

**Steps To Reproduce**
No particular steps, it happened randomly.

**Version**
v 09.9.1 on Windows 10

**Additional information**
I recently reformatted my computer recently so it's technically as good as new.

**Comment by Regalis11** [comment] 2020-05-03 11:21
Could you please send us the crash report?

**Comment by doct0rMATT** [comment] 2020-05-09 20:30
Hi there!

Here are the crash reports you needed. I got another two crashes (7) and (8) today 5 minutes in game with some friends.

Have a nice evening,

Matt
________________________________

**Comment by doct0rMATT** [comment] 2020-05-09 22:46
Hi again Joonas,

I had previously sent you a big chunk of crash reports, I'm sending you this extra one.

I reinstalled the game, tried it on lower graphic settings online but still crashed.

On this particular report (12) I'm playing single player, yet still crash 5 minutes in...

Any help would be much appreciated.

All the best,
Matthew

________________________________

**Comment by Regalis11** [comment] 2020-05-10 16:59
Hi again!

I'm afraid we didn't receive any of the crash reports you sent us. Where exactly did you send them? If it was attached to the email you sent as a reply to the notification from github, I don't think it came through. You should instead send it as an attachment in the issue report you created (https://github.com/Regalis11/Barotrauma/issues/2762) or email it directly to us using the address contact@barotraumagame.com.

Sorry for the trouble and thanks for the help!

**Comment by Regalis11** [comment] 2020-05-18 09:18
Received the crash reports via email, and this seems to be a duplicate of #1833

**Closed by Regalis11** 2020-05-18 09:18 UTC
Labels: Bug, Code, Crash, Need more info
