### ISSUE TITLE
Crewlist low res

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#4030] opened 2020-10-07 23:53 UTC
[Issue]
![image](https://user-images.githubusercontent.com/47284081/95399671-37710f00-08f8-11eb-987d-6825bfc37361.png)

**Comment by ekqvist** [comment] 2020-10-08 08:39
Can you tell which resolution this is on?

**Comment by someone972** [comment] 2020-10-08 09:08
Will have to wait for hubismal to give all the details, but here's some testing of my own in case it's useful.

Did a bit of testing on 0.10.5.1, I wasn't able to reproduce it completely. At 800x600 which is the lowest my monitor will go, the name Dorsey got shortened to "Do..." (could certainly make better use of the available space, since the bar extends far beyond that point). I'm guessing this was taken on a resolution close to 800 pixels high, based on the height of the boxes. At 1280x800, mine are 35 px tall where they are 36 px tall in hubismal's image. At 1280x800, I could see "Dorsey H...". Maybe hubismal is on unstable build though, I did not test on that.
![ResolutionTest](https://user-images.githubusercontent.com/1829181/95438365-6cd72600-0913-11eb-9cab-3658496f4376.png)

**Comment by hubismal** [comment] 2020-10-08 14:47
![image](https://user-images.githubusercontent.com/47284081/95474920-30d4ad00-0975-11eb-87ca-d5aa82157d3e.png)
720p screen masterrace

**Comment by Rokvach** [comment] 2021-11-17 15:31
Tested, working correctly. Closing.

**Closed by Rokvach** 2021-11-17 15:31 UTC
Labels: Bug, Code, Low prio
