### ISSUE TITLE
"target" rotation type for ranged creature attacks no longer rotates the spawned projectile item to go towards the targeted entity.

### ISSUE THREAD

**Issue by Emanthealmighty** [Regalis11/Barotrauma#11172] opened 2023-02-06 18:17 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Not sure exactly when this broke, but using "[target](https://github.com/Regalis11/Barotrauma/blob/48c66adcdcb50d28d1b735218f5dbc10b9a971da/Barotrauma/BarotraumaShared/SharedSource/StatusEffects/StatusEffect.cs#L1813)" as the rotation type of a spawned projectile from a character attack would cause the projectile to be shot towards the entity that the character AI is currently targeting no matter the angle of the limb/character that is firing it. Now what seems to happen is that projectiles spawned with the rotationtype "target" are always fired to the right.

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment] 2023-02-15 10:48
After a bit of debugging and testing, I think it's working as intended. However, if the TargetType is something else than "UseTarget", this doesn't probably work as intende, because the direction from the spawn position to the target is miscalculated (because the target is something else). Are you sure you used "UseTarget" _and_ didn't have any rotation offset in the spawn item definition? Of the vanilla monsters, Guardian repair bot and Cyborg worm make use of this feature.

**Comment by Regalis11** [comment] 2023-06-30 11:25
No known steps to repro, closing

**Closed by Regalis11** 2023-06-30 11:25 UTC
Labels: Bug, Need more info, Code, Modding
