### ISSUE TITLE
(UNSTABLE) Tutorial loop in singleplayer

### ISSUE THREAD

**Issue by DutchChrisis** [Regalis11/Barotrauma#10361] opened 2022-11-12 21:34 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While starting in singleplayer with the preset set on easy, the Jovian radiation off and using a Orca as starter sub.

From the NPC coming up to the PC the loop begins. Here a few sceens of the setup and start of it.
![BAROTRAUMA VERSION](https://user-images.githubusercontent.com/105824356/201495308-9fe50352-1567-49a0-81f8-076c67a6365d.png)
![BAROTRAUMA settings](https://user-images.githubusercontent.com/105824356/201495317-5b3fa9c4-7467-412b-8187-bf0ccd60fc09.png)
![BAROTRAUMA SUB and mapseed](https://user-images.githubusercontent.com/105824356/201495326-7d709a5c-5a05-4dc6-b33e-24bb33780a7c.png)
![BAROTRAUMA LOOP](https://user-images.githubusercontent.com/105824356/201495332-696ad07b-3ebf-41ca-b45b-22294681a411.png)
![BAROTRAUMA LOOP part 2](https://user-images.githubusercontent.com/105824356/201495334-7dfe6ceb-1d2a-4a2b-be49-7f0617740d71.png)

I hope this helps u guys :)

### Bug prevalence

Happens every time I play

### Version

0.20.5.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Momonii** [comment] 2022-11-13 01:01
Also happening to me. Default settings, no mods, using Dugong.

**Comment by Razatop** [comment] 2022-11-13 06:31
Same here.

**Comment by Regalis11** [comment] 2022-11-13 11:01
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10320

**Closed by Regalis11** 2022-11-13 11:01 UTC
