### ISSUE TITLE
closing baro after a crash report closes my text editor

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#9583] opened 2022-07-16 22:31 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When the game generates a crashlog, pressing "OK" opens the file in my text editor.

the game is still "running" in steam and i have to press "stop" to re-launch the game.

however, pressing stop closes my text editor (which has things open other than the crash log)

### Reproduction steps

1. crash barotrauma (easy)
2. text editor gets opened
3. tell steam to "stop" barotrauma
4. text editor gets closed

### Bug prevalence

Happens regularly

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-07-19 15:08
I'm afraid I could not reproduce this: Steam doesn't show the game as running after it's crashed so I can't stop it from Steam. I suspect this has something to do with how exactly it crashed - in my testing I used a debug-only console command that forces the game to crash. Do you have some other method that you use to that can be used to reliably reproduce this?

**Comment by Tsunder** [comment] 2022-07-20 17:35
Previously (when I reported) it was while editing components #9512 , where it'd show the with "barotrauma has crashed, crashlog (N).log was made" dialogue.

Now I've reproduced that crash (I'm still on stable 0.18.15) but there's no crash dialogue opening I'm not sure why (only major difference is i have screen recorder open...).

**Comment by Tsunder** [comment] 2022-07-20 17:45
managed to get crash dialogue + file to open by crashing the editor on an existing sub (instead of placing components in the void and editing)

however, barotrauma is now correctly showing as stopped anyway. 

further testing:
- if text editor was not open when baro crashed, the editor opens, and baro is considered by steam running post-crash until editor is closed.
- if editor was already opened when baro crashed, steam doesn't consider the editor as part of baro's exec

**Comment by NilanthAnimosus** [comment] 2022-08-17 14:33
Is there a specific text editor you are using with this to open the text files by default other than windows notepad? it hasn't been specified and that could have (in some peculiar way) been relevant as windows notepad by default opens a new process and cannot be open pre-emptively to change this behavior? just curious as this could be a steam problem or a game issue with how it opens the text file with windows and knowing if its notepad++, ultraedit or other editor might help.

**Comment by Tsunder** [comment] 2022-08-19 22:07
my text editor/the one that opens up here is sublime text (supports multiple text docs per window, similar to notepad++ , atom, etc)

**Comment by Regalis11** [comment] 2023-03-10 10:43
We're cleaning up some low-prio/unreproducible/irrelevant/outdated tickets from the issue tracker, and this is one of the tickets we chose to axe. Closing.

**Closed by Regalis11** 2023-03-10 10:43 UTC
Labels: Bug, Code, Low prio
