### ISSUE TITLE
Could not return back from a "dead end" location

### ISSUE THREAD

**Issue by Rparvitn** [Regalis11/Barotrauma#12045] opened 2023-05-21 17:33 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When we reached the dead end(it was uninhabited)
![изображение](https://github.com/Regalis11/Barotrauma/assets/97904411/8eea728f-24f3-4c9a-a6b1-9a95c0ab8a33)
We pressed the map and tried to choose next point behind us, but nothing happened. Then we swam towards start location, but when we pressed dock button submarine docked, but nothing else changed. We docked and undocked several times, and finally we restarted the sail and docked to start normally, abandoning the tasks.

### Reproduction steps

Steps we did described above

### Bug prevalence

Just once

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-05-22 06:28
Thank you for the report! 

Could you please provide us the save file this happened in (or the map seed) so we can try reproducing the issue? Sorry for the inconvenience!

**Comment by Rparvitn** [comment] 2023-05-22 14:00
> Thank you for the report!
> 
> Could you please provide us the save file this happened in (or the map seed) so we can try reproducing the issue? Sorry for the inconvenience!

[Save.zip](https://github.com/Regalis11/Barotrauma/files/11531791/Save.zip)

**Comment by Rparvitn** [comment] 2023-05-26 09:53
Should I give any more info?

**Comment by Regalis11** [comment] 2023-05-26 10:55
@Rparvitn we haven't yet had time to look into this, but I think we'll probably be able to reproduce the issue with that save file. Thanks!

**Comment by Regalis11** [comment] 2023-05-26 12:44
I gave the save a test now, but unfortunately still could not reproduce the issue. I'm not completely sure I fully understood the steps though:

Do you mean you were in the level leading from Belenos Mensa to Thera Macula, the one circled in green here? Or were you in Belenos Mensa, the abandoned outpost? Were trying to dock back to Belenos Mensa, and choose Ana as the destination (the route circled in red)?

![image](https://github.com/Regalis11/Barotrauma/assets/14351070/0d47ed6d-e6a6-411a-aa8e-5b411b58db0a)

**Comment by Rparvitn** [comment] 2023-05-26 13:21
I meant green one. Also, at the end of dead end wasn't an outpost, so we couldnt dock there. The only option we had is a map button above, but it haven't worked, and then we returned all the way back to start station but couldn't finish the mission

**Comment by Regalis11** [comment] 2023-05-26 13:57
Thank you for the clarification! I tested changing that location into an "empty" location with no outpost, but still couldn't reproduce the issue. I was able to select the previous location as the destination with no issues:

https://github.com/Regalis11/Barotrauma/assets/14351070/f0d70dc3-8ee1-4ee0-a51d-b065ccb68651

I'm not sure if I'm doing something wrong / differently than you here, or if it could be some weird networking issue or something that's difficult to reproduce afterwards.

**Comment by z0grim** [comment] 2023-06-24 12:28
Hi All,

I have a similar issue with dead-ends, not an exact match, in my game the end was already empty. We assumed we'd go there, complete a task, kill an abyss creature and turn around.
But when reaching the "end line" changing the way back did not result in an "end game". Pressing start had no effect.
![20230624133731_1](https://github.com/Regalis11/Barotrauma/assets/4379324/f5d0c260-4620-42a2-b09e-2696c927e240)
We tried navigating back to the original station, we could "dock", but "end game" did not occur, and we were docked in the stub city, that's put inside the mission map, not the city itself. We could also walk onboard, but it was empty.
![20230624135055_1](https://github.com/Regalis11/Barotrauma/assets/4379324/29c7cee7-cd96-4cd3-9e68-d8935604bd09)

We had this situation play out 2 times from this same save. We plan to give it a 3rd try, without touching the "end line" and just dock back inside after we're done with our tasks.

Platform: win10
Multiplayer game
Custom sub
Save game:
[stuck_deadend.zip](https://github.com/Regalis11/Barotrauma/files/11856944/stuck_deadend.zip)

**Comment by Regalis11** [comment] 2023-06-25 12:05
@z0grim Thank you, I was able to reproduce the issue now, and I think I was able to finally fix it. 

Commit in our private repo https://github.com/Regalis11/Barotrauma-development/commit/a32e8dc114b1ff80eeee3debea89390b7a086c09:

> Fixed trying to return from an empty deadend location sometimes not working. We only allowed returning if the location we were at was the last one in SelectedConnection.Locations (or the 1st one if the level is mirrored) - but we can't do that, SelectedConnection.Locations isn't in any particular order. I also don't see why this check is necessary (probably a leftover from some earlier point): if we're at the end of the level, and selected some connection, starting a new round should always just load that connection.

**Comment by Jasontti** [comment] 2023-06-29 07:52
Tested.
Fresh save with 2 different dead end locations and was able to select previous location.
Closing ticket.

**Closed** 2023-06-30 06:38 UTC
Labels: Bug, Code
