### ISSUE TITLE
Gun eaten by hatch

### ISSUE THREAD

**Issue by Orheden425** [Regalis11/Barotrauma#9697] opened 2022-08-11 12:25 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

So i had too many items and needed to drop something for a couple of seconds and i chose my smg i dropped it on a hatch and after some seconds i had space in my inventory again i looked for it and it was nowhere to be found, i also went to a station to look if it's still there by using the submarine sell function at one of the traders and it wasn't there so it was just gone. Btw i also looked in the ballast that was under the hatch and it wasn't there.

### Reproduction steps

1. Get an item
2. Drop the item on a hatch (shouldn't matter which one)
3. Done, congratulations you lost your item :).
[learning experience (1).zip](https://github.com/Regalis11/Barotrauma/files/9308580/learning.experience.1.zip)

### Bug prevalence

Happens every time I play

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by NilanthAnimosus** [comment] 2022-08-16 06:57
Tested on 0.18.15.1, Notes: the zip file needed to be renamed to .save (It is not actually a zip file, and caused errors as I kept trying to figure out how to use the save in this case).

I could find no issues with placing a number of SMG's on hatches (ballast tanks, the bottom airlock, between the docking hatches of the submarine and outside and one inside the outside over that hatch). Amusingly it kept not just every assault rifle on the submarine, it also kept the one on top of the upper docking hatch of the humpback that was technically outside.

I would like to add that if an AI sees an item on the ground (Like an smg though almost any item really) there is a good chance they will pick it up and do a cleanup items order automatically without any orders such as the assistant whom had none set in the save.

Otherwise (even with the provided save file and thus the same submarine) I couldn't reproduce any issues with this after trying a few other items on the hatches.

**Comment by Orheden425** [comment] 2022-08-16 09:40
(Github can take .save files i belive so i had to change it to .zip) For the bug i was using humpback and was to the ballast to the right and i dropped it in the corner, none of my npc's had the task to clean up items and none of them went to where i dropped the items (they dissapeared immediately ). I also checked their inventory and other loot containers. But after trying to recreate it again now i couldn't do it for some reason so i have no idea why they dissapeared anymore could have been some errors maybe. I also don't think it was me not looking hard enough/good enoguh because the smg isn't that small so it should be pretty easy to see it contrary to the smg magazine that i also dropped.

**Comment by Orheden425** [comment] 2022-08-16 09:46
I tested the submarine sell feature by dropping a weapon on the floor and it did not show which i didn't know so the smg could have just become invisble as i've seen numerous crewmates becoming invisble so it could have been that but still unsure what could've caused the smg and smg mag to dissapear

**Comment by Regalis11** [comment] 2022-11-08 15:29
No known steps to repro, closing

**Closed by Regalis11** 2022-11-08 15:29 UTC
Labels: Bug, Need more info, Code
