### ISSUE TITLE
The mission popu-up is shown too early

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#3611] opened 2020-08-21 14:29 UTC
I guess the popup should be shown when the mission briefing/status interface is closed ![mission_ui_too_early.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/359d87ca-d90c-4936-b2ab-a521efafb648)

**Comment by Regalis11** [comment] 2020-08-24 06:57
Fixed in fa71b03b

**Comment by Regalis11** [comment] 2020-08-24 07:38
This should've been fixed in https://github.com/Regalis11/Barotrauma-development/commit/fa71b03b. Which version did this occur in? I couldn't reproduce it in either the bugfixes or dev branch.

**Comment by itchyOwl** [comment] 2020-08-24 09:01
Can't repro on dev or release. But it happens on dev before the bug-fixes merge (75db5c2) on 20th August.

**Comment by Regalis11** [comment] 2020-08-24 09:46
Moving to Review/QA in that case

**Comment by Rokvach** [comment] 2020-08-31 06:20
Couldn't spot any issues with this, closing.

**Closed by Rokvach** 2020-08-31 06:20 UTC
Labels: Bug, Code, Low prio
