### ISSUE TITLE
Can't maximize the game window after hosting a server and minimizing the game once

### ISSUE THREAD

**Issue by akariaon** [Regalis11/Barotrauma#11394] opened 2023-02-28 08:33 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Whenever I host the server, then minimize the game by pressing the Windows button and try to open the game back, it doesn't open, until I click maybe 20-30 times (the count is random every time), and I can always hear the Windows warning sound, although there's no warning window popping up.

### Reproduction steps

1. Host a server
2. Minimize the game
3. Try clicking on the game icon, and it won't maximize, until you try a bunch of times.

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-02-28 08:59
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3584

**Closed by Regalis11** 2023-02-28 08:59 UTC
