### ISSUE TITLE
Corrupted MD5 hash cache causes crash on startup

### ISSUE THREAD

**Issue by juanjp600** [Regalis11/Barotrauma#3122] opened 2020-06-17 16:57 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If the game crashes while it's saving the MD5 hash cache, it'll corrupt the file and make the game unable to start in subsequent runs.

**Steps To Reproduce**
- Prevent access to `Data/hashcache.txt` while the game is writing to it (error report seems to suggest this can happen when the dedicated server and the client are running concurrently)
- Try relaunching the game after the crash.

**Version**
v0.9.10.0

**Additional information**

https://steamcommunity.com/app/602960/discussions/1/1869497355995369888/#c2447091901849628549

```Barotrauma Client crash report (generated on 6/16/2020 11:26:34 PM)


Barotrauma seems to have crashed. Sorry for the inconvenience!


D841E710F9AD33CA9ECDCA0C318B244F


Game version 0.9.10.0 (ReleaseMac, branch release, revision 2876b0a66b)
Graphics mode: 1440x900 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized


System info:
Operating system: Unix 17.7.0.0 64 bit
Game not initialized


Exception: Input string was not in a correct format. (System.FormatException)
Target site: Void ThrowOverflowOrFormatException(ParsingStatus, System.TypeCode)
Stack trace:
at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
at Barotrauma.Md5Hash.LoadCache() in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/Map/Md5Hash.cs:line 32
at Barotrauma.GameMain..ctor(String[] args) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 217
at Barotrauma.Program.Main(String[] args) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 57


Last debug messages:
[6/16/2020 11:26:34 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[6/16/2020 11:26:34 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[6/16/2020 11:26:33 PM] Logged in as hazza049 (SteamID STEAM_1:1:149148749)
```

**Comment by juanjp600** [comment] 2020-06-17 16:59
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/b6f1503dc8b6540adc73e83b7682479934b0f5f9 and https://github.com/Regalis11/Barotrauma-development/commit/8adbe19737ca07049476436a1b7f63767a97c009

**Comment by Rokvach** [comment] 2020-07-13 10:03
Needs clearer reproduction steps

**Comment by juanjp600** [comment] 2020-07-13 12:43
Launching a server from the "Host Server" menu several times should serve as a decent test.

**Comment by Rokvach** [comment] 2020-07-13 13:39
Didn't encounter any issues while I launched the server and closed it as fast as I could for around 15-20 times. Seems to be working, closing.

**Closed by Rokvach** 2020-07-13 13:39 UTC
Labels: Bug, Code, Crash
