### ISSUE TITLE
fruits break when falling (when just grown)

### ISSUE THREAD

**Issue by maskochnik** [Regalis11/Barotrauma#12425] opened 2023-07-27 13:45 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

when the fruit grows and falls, it sometimes immediately breaks when falling also with mutated

### Reproduction steps

1 I planted a plant 2 waited until it fully grows and bears fruit 3 the fruit falls and breaks in 50/50 cases

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### -

no

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
no
```

**Comment by LewdM3at** [comment] 2023-07-28 08:52
If I understand this correctly, that's working as intended? Fruits take fall damage when they fall down. You can either put planters a little bit inside of the floors to minimize the fall distance, or have some water level on the floor to cushion the fall. I've heard that works but can't confirm as of now. I'm still testing this "myself"

**Comment by ubertpendragon** [comment] 2023-07-28 12:26
Your planters are probably way too high

All fruits survived the fall
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/e616eec1-2d35-49be-bb0d-02d5c7f6d435)

**Comment by VaelophisNyx** [comment] 2023-07-31 16:01
will say that this is probably the most annoying part of farming that puts most players off of it, for sure.

**Comment by itchyOwl** [comment] 2023-08-02 10:09
QA: need to confirm if there's actually any issues here.

**Comment by Jasontti** [comment] 2023-08-07 06:05
Tested in current unstable.
Fruit breaks when falling from normal highest grow height. Raptor bane break more easily (row 3 and up) than pomegrenade (row 4 and up).

![image](https://github.com/Regalis11/Barotrauma/assets/8488224/0337db63-b194-4cd6-9ee6-74008b26275f)

**Comment by Regalis11** [comment] 2023-08-16 14:14
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9c59f40e1d76c701cded422f6bb38cea0886404a

**Comment by Jasontti** [comment] 2023-08-24 06:08
Tested.
Normal fruits now survive normal farming heights, still gets destroyed when falling from great heights or thrown.
Closing ticket.

**Closed by Jasontti** 2023-08-24 06:08 UTC
Labels: Bug, Design
