### ISSUE TITLE
Ballast Flora Bug (at least in Single Player)

### ISSUE THREAD

**Issue by Minukelsus** [Regalis11/Barotrauma#9229] opened 2022-05-31 03:39 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Seen in the bug reports that someone also reported this in April. I just now experienced this and I may have Insight on what might have happened. Here is my Report.

I've destroyed ballast flora many times and know how to take care of them. In this case, I'm at an outpost and I can't even destroy it. I've used a flame thrower, incindium grenades, no water in the ballast, plasma cutter for minutes at a time on the same spot on the flora along the walls and on the pump itself. The ballast flora on the pump itselfs health bar didn't even go down.

Other things I tried was paying the sub upgrade person to fix the sub even though I'm sure it wouldn't fix it. It didn't. I started a round so I could see if maybe I can't damage the ballast at a station and only during missions. That didn't work. I redocked and tried switching subs then back again and that didn't reset the condition of the sub or the ballast flora. I've came to the conclusion that this is a bug that won't ever go away and that the sub is doomed.

How all this happened is most likely me playing the game, getting ballast flora, damaging it a bit but then realising that I suddenly need to leave. I decide to head to the outpost and deal with the ballast flora in the safety of the outpost so my sub doesn't get attacked or sink or raise uncontrollably. I arrived at the outpost, saved and quit and left to do life stuff. Came back, loaded the game up and came back to indestructible ballast flora.

### Reproduction steps

1. Infect sub with ballast flora during mission.
2. Dock at station without killing ballast flora
3. Save and quit the game completely.
4. Load up the game again and end up with indestructible flora.

If you have done any a bit of damage to the flora without killing it then follow these steps, you'll notice that when you log back on, the health will be at the level you damaged it to without the ballast flora healing. It's health will be locked.

### Bug prevalence

Just once

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-05-31 06:55
Duplicate of https://github.com/Regalis11/Barotrauma/issues/9024

**Closed by Regalis11** 2022-05-31 06:55 UTC
