### ISSUE TITLE
Game Crashes When It Opens (TaskPool)

### ISSUE THREAD

**Issue by Minukelsus** [Regalis11/Barotrauma#3500] opened 2020-08-05 04:21 UTC
**DESCRIPTION**
Hello and thanks for taking the time to read this. Whenever I press "Play" or even "Run as Administrator" for Barotrauma, the game loads up to the first cut scene for half a second then the game kicks you out to the desktop screen and says that the game has crashed.

**STEPS TO REPRODUCE**
What I think may have caused it is that I went into Steam Workshop bit in the game and deleted all the mods (because i thought maybe that's what was causing me to freeze in the game a lot). Went into multiplayer and all the servers were grayed out. I couldn't even join them. I quit the game, verified the integrity of the game files and nothing was found. Loaded game back up but it crashes about a second into loading the game up and gave a crash report.

**VERSION**
I'm on version 0.10.4.0
I'm using Windows 10

**ADDITIONAL INFORMATION (SOLUTION)**
I also managed to find a solution to the problem. When you delete the game, you have to delete EVERYTHING. Don't just uninstall the game. Actually go to where the folder is located and delete the Barotrauma folder itself for a fresh, clean install. Surprisingly when it finished installing, the save files for single player at least (not tested multiplayer yet) are still there. The saves must have been saved to the Steam Cloud thing or whatever.

Anyway, attached to this will be the crash report in case you're interested.
[crashreport.txt](https://github.com/Regalis11/Barotrauma/files/5026113/crashreport.txt)

**Comment by rico6822** [comment] 2020-08-05 05:06
Deal with it. I guess this is never going to be absolutely fixed judging by how many times developers already tried to.

**Comment by itchyOwl** [comment] 2020-08-11 10:50
There are and can be multiple issues that cause crashing when the game launches. We can and should address all issues that are due to our code. However, if the issue is due to hardware/driver issues, there's only so much that we can do. This issue, however, seems to be due to a bug in our code. There's already a couple of reports of the same issue. We'll look into it. Thanks for reporting!

**Comment by juanjp600** [comment] 2020-08-18 12:03
Potentially fixed in https://github.com/Regalis11/Barotrauma-development/pull/2122/commits/537e6ab3caaad90281ba8c54afa7279ab353d206

**Comment by Rokvach** [comment] 2020-09-03 10:46
Tested, wasn't able to reproduce the issue, seems to be working correctly. Closing.

**Closed by Rokvach** 2020-09-03 10:46 UTC
Labels: Bug, Code, Crash
