### ISSUE TITLE
Changes to job titles using the language file are inconsistent and switch back to default

### ISSUE THREAD

**Issue by malcomshot** [Regalis11/Barotrauma#10104] opened 2022-10-17 15:43 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I used a Text xml to edit the english translation so that the various job titles would be customized to my mod
`<jobname.captain>Ex-Shuttle Pilot</jobname.captain>
  <jobdescription.captain>I saw a few crawlers floating around sometimes.. we'll be fiiiine.</jobdescription.captain>
  <jobname.engineer>Fuck-up Engineer</jobname.engineer>
  <jobdescription.engineer>Engineers are the backbone of a submarine's crew, complementing a mechanic's mechanical engineering skill with their knowledge of electrical engineering. This one was rather bad at his job.</jobdescription.engineer>
  <jobname.mechanic>Scrapper</jobname.mechanic>
  <jobdescription.mechanic>Blessed with a nose attuned by the heavens.. to find wrecks and other junk.</jobdescription.mechanic>
  <jobname.securityofficer>Ruffian</jobname.securityofficer>
  <jobdescription.securityofficer>Always helps to have a big guy around to watch your back.</jobdescription.securityofficer>
  <jobname.medicaldoctor>Addict</jobname.medicaldoctor>
  <jobdescription.medicaldoctor>Keep an eye on this one, or keep him drugged up. Wouldn't want him to sneak off at the next station with all your fuel rods and morphine</jobdescription.medicaldoctor>
  <jobname.assistant>Clown</jobname.assistant>
  <jobdescription.assistant>You've met with a terrible fate...</jobdescription.assistant>`
It works, but very inconsistently. Often times half the jobs are back to vanilla and I haven't really been able to track down any specific order to it. It seems to switch around as I go through the menus.

### Reproduction steps

1. Create an infotexts language translation file for a mod
2. Edit the names of all job fields
3. Add it to the filelist.xml
4. Launch the game/active the mod
5. Go into menus where job selection is available or otherwise shown
6. Many times it will be set back to default

### Bug prevalence

Happens regularly

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Nothing threw an error, and the mod list in settings shows it as white.
```

**Comment by Regalis11** [comment] 2022-10-17 16:06
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10074. Unfortunately texts can't be overridden at the moment, these will just get treated as alternative versions of the same text from which the game will pick a random one.

**Closed by Regalis11** 2022-10-17 16:06 UTC

**Comment by malcomshot** [comment] 2022-10-17 16:28
Shouldn't this remain open until that's fixed then? Is there plans to add overriding to texts?
