### ISSUE TITLE
laser shots frequently invisible in multiplayer

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6151] opened 2021-06-22 21:40 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
pulse laser's particles/graphics are invisible often in multiplayer
 when shooting long range (out of visual sight, 20+m)
the beam thing just doesn't appear

**Steps To Reproduce**
shoot at subs in PVP pewpew

**Version**
0.14.6

**Additional information**
video sometime maybe

**Comment by Regalis11** [comment] 2021-07-05 13:09
I'd suspect this is caused by the same issue as https://github.com/regalis11/barotrauma/issues/6136

**Comment by Rokvach** [comment] 2021-08-24 08:09
Tested, working correctly. Closing.

**Closed by Rokvach** 2021-08-24 08:09 UTC
Labels: Bug, Code, Networking
