### ISSUE TITLE
Unstable - Inventory items are replaced by random items in the next rounds of multiplayer campaign

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2042] opened 2020-01-24 10:02 UTC
- [Yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When starting the next rounds in multiplayer campaign, there's a chance player's inventory items are replaced by:

Black Wire
Alien Button
Alien Generator
Alien Light Component
Floor Component
Probably others...

Sometimes the items will revert back to normal at the next round.

**Steps To Reproduce**
Play Campaign with multiple players to get higher chance of triggering. Load up about a full kit of repair and diving set per person. Play through until the next station and start the next round. It should happen sooner or later.

**Version**
0.9.700~0.9.702
Windows

**Additional information**
If you're able to drop the transformed items, it should revert back to normal in the next round. If it becomes a alien item and it vanishes from your inventory without dropping, I think the whole item vanishes.

**Comment by NilanthAnimosus** [comment] 2020-01-25 03:16
I debugged this somewhat and gave a reproducible save to juan - although I consider my debugging sort of a failure as I can't discern the cause I have at least finally found the potential break in the networking.

The entity ID's do not match when the server has already written the character inventory. the ID for my captains pipe server-side was oddly that of an alien button client-side before the client had received any events, I had managed a campaign save file that 100% reproduced the issue that I kept reloading to test it on.

I tried everything I could think of at first, to find it was never written server-side, but always received client-side. turning my brain to mush over some 3-5 hours, I spotted it by accident after having breakpointed every part of code I could.

After events are synced and the round has started - the client and servers ID's will be a perfect match.

But before this, they are infact miss matched, So I assume something changes the entity ID's at some point,  but the character inventory appears capable of being updated before these ID's change. It also appears the incorrect item is still in the inventory somehow by the time you get control of your character as you never see it "Added" later, while you do see an additional alien button. an inventory update will remove this, placing it in a locker will push it out of the locker but permanently shift the button to inside the submarine.

I spotted this by debugging the eventstosync themselves in the serverentityeventmanager. the client had long since been disconnected, and I had the bright idea to run dumpids, the client had an ID of 5218 for the alien button without receiving a single event, this also was the ID for my captains pipe server side. 

Save File (leave as loaded, Left route, no mission):
[save files.zip](https://github.com/Regalis11/Barotrauma/files/4111582/save.files.zip)

Images:

![image](https://user-images.githubusercontent.com/29177976/73115658-f5966900-3f20-11ea-8b68-2669411533c4.png)

![image](https://user-images.githubusercontent.com/29177976/73115621-8d478780-3f20-11ea-89a0-414dbb48d91c.png)

![image](https://user-images.githubusercontent.com/29177976/73115627-989ab300-3f20-11ea-916e-5aa580884e94.png)

![image](https://user-images.githubusercontent.com/29177976/73115624-92a4d200-3f20-11ea-9607-cb3a14fbff2e.png)

**Comment by NilanthAnimosus** [comment] 2020-01-25 07:40
I had another thought as well regarding previous campaign errors that (Very rarely) occured involving a missing alien structure or such at round start, I don't suppose these could be related to the above, but instead of a more benign swap such as inventory sorting, it is applying to say an entity deletion? It couldn't be applying to other kinds of events?

**Comment by Regalis11** [comment] 2020-01-25 16:47
Thank you so much for the save file, I was able to repro this now! It seems to happen because the client receives an inventory state update for the character before the spawn event for the Captain's Pipe. So what happens is basically

1. Server sends an inventory state update, which includes the IDs of the items in the inventory.
2. The pipe doesn't exist client-side yet, but the Alien Button happens to have the same ID that the server has assigned to the pipe. So, the client puts the Alien Button in the inventory.
3. Server spawns the Captain's Pipe, forcing it's ID to the one in the save file, which in this case causes it to take up the ID of the Alien Button.

I think this might also be causing the "missing alien item/structure" errors, possibly in conjunction with the bug mentioned in #2025.

**Comment by Regalis11** [comment] 2020-01-25 17:14
Should be fixed by https://github.com/Regalis11/Barotrauma-development/commit/f019607ed1d8dd83e46ae09d69ba5d7946073093 (private repo)

**Comment by Kaillera** [comment] 2020-01-30 22:20
Still happening in 0.9.702.

**Comment by Rokvach** [comment] 2020-01-31 11:26
@Regalis11 ping

**Comment by Rokvach** [comment] 2020-02-05 12:22
No encounters in 703 so far

**Comment by juanjp600** [comment] 2020-02-05 16:21
Can be replicated in 703, fixed in https://github.com/Regalis11/Barotrauma-development/commit/97877fd14909b1cd66844cf79de1adcd38abb261

**Comment by Kaillera** [comment] 2020-02-06 03:55
@juanjp600 so today in multiplayer campaign, sometimes our items turn into minerals.

**Comment by juanjp600** [comment] 2020-02-06 17:23
@Kaillera It sounds very similar to the case that was fixed in the mentioned commit, I suspect it may have already been fixed

**Comment by NilanthAnimosus** [comment] 2020-02-06 17:36
Juan, is that fix per chance server-side only and not requiring changes to the client?

If so you could DM me through discord the differences and I could try to implement them to check if its fixed before the next version perhaps.

**Comment by juanjp600** [comment] 2020-02-06 17:58
Unfortunately the fixes are client-side, as there are no issues with the server itself in this case.

**Comment by NilanthAnimosus** [comment] 2020-02-07 00:23
Fair enough and that's fine.

**Comment by Rokvach** [comment] 2020-02-07 20:48
Tested, working correctly. Closing.

**Closed by Rokvach** 2020-02-07 20:48 UTC
Labels: Bug, Code, High prio, Networking, Waiting
