### ISSUE TITLE
[0.9.705] Players getting excessive desync kicked at the start of rounds

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2254] opened 2020-02-11 10:04 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Players are getting excessive desync kick at the start of round.

**Version**
0.9.705

**Additional information**
I haven't seen it happened Mission Mode yet. In Campaign Mode, it seems to happen in the starting-early rounds when large amount of store purchases, and auto fill are happening (though it even happens on a small sub like Orca). It could also be the new level generation since it only in for the first biome in this version. I don't know if it's related to the ping from the host. I live half way across the world from the host when I saw this, but it was happening to a few players except me.

Also since players aren't booted to the server list, if they remained in the lobby and come back into the game they get #2076 and need to rejoin the server from the lobby to fix.

**Comment by Regalis11** [comment] 2020-02-11 11:28
I'm guessing this happens because of the longer loading times. https://github.com/Regalis11/Barotrauma-development/pull/1398 should remedy this once we merge it.

**Comment by Rokvach** [comment] 2020-02-11 21:09
This was working, but I assume this one was also just reverted? @Regalis11

**Comment by Regalis11** [comment] 2020-02-11 21:37
Yeah, this is what the startround-fixes branch was intended to remedy, but we had to revert it because it caused some side-effects that we don't have time to test and fix for the next update. So moving back to todo

**Comment by Rokvach** [comment] 2020-02-28 13:47
No issues spotted while testing, when this was part of the Unstable build there wasn't any desync issues at the start of the rounds and the issues there was has been fixed. Closing.

**Closed by Rokvach** 2020-02-28 13:47 UTC
Labels: Bug, Code, High prio, Networking
