### ISSUE TITLE
Multiplayer Campaign file corrupted after entering a station

### ISSUE THREAD

**Issue by MaximeHemion** [Regalis11/Barotrauma#3510] opened 2020-08-05 20:03 UTC
Our multiplayer campaign save is now unplayable. It happened when we entered a station.

It may be that something inside the station map is not instanciated correctly. Crash happens 100% of the time. The submarine used is a custom one from editor.

CC error log & save game (.gz == .save)

![barotrauma-error](https://user-images.githubusercontent.com/11932332/89458490-65569d80-d767-11ea-848d-2c08145b66de.png)

[THECAMPAIGN.gz](https://github.com/Regalis11/Barotrauma/files/5030908/THECAMPAIGN.gz)

**Comment by Regalis11** [comment] 2020-08-18 07:41
Duplicate of #3459

**Closed by Regalis11** 2020-08-18 07:41 UTC
Labels: Bug, Code
