### ISSUE TITLE
10 second delay for chained relays to receive power even in trivial wiring setups

### ISSUE THREAD

**Issue by JohannesMP** [Regalis11/Barotrauma#5813] opened 2021-05-16 22:05 UTC
# Description
In the sub editor I'm using a test scene to experiment with how various components function. After running into some odd behavior while trying to create a more complex system I've narrowed down an interesting repro case.

The setup has a full battery, feeding into a primary relay which forwards the power to a secondary relay. Both relays have a lamp attached to their power output, and all components have `Is On` enabled where applicable.

With default power values for all components, it takes about 10 seconds from when I hit 'Test' to when the lights actually receive power.

Here is a video capture of this in action:

https://user-images.githubusercontent.com/662874/118415075-18401a00-b65d-11eb-89f5-1b669adf30b9.mp4

# Steps To Reproduce
## Setup
![image](https://user-images.githubusercontent.com/662874/118414847-c4810100-b65b-11eb-926e-66b5aca23c9c.png)
- A **battery** connected to a **primary relay** that feeds into a **secondary relay**, both of which have a **lamp** attached to their power output.
- Sub file: [TEST_RelayBug3.sub.zip](https://github.com/Regalis11/Barotrauma/files/6490187/TEST_RelayBug3.sub.zip)

## Component Settings
- Battery is default
![image](https://user-images.githubusercontent.com/662874/118412538-76fe9700-b64f-11eb-82ad-418be1edea29.png)
- Relays are default, except `Is On` is enabled
![image](https://user-images.githubusercontent.com/662874/118412564-8e3d8480-b64f-11eb-945b-32f65c998c1d.png)
- Lamps are default except range and color adjusted, and `Is On` is enabled:
![image](https://user-images.githubusercontent.com/662874/118415216-01e68e00-b65e-11eb-8f1a-be965017c3d4.png)

## Wiring Setup
- The first relay receives `POWER_IN` from the battery, and sends `POWER_OUT` to the `POWER_IN` of the secondary relay.
- Both relays also send their `POWER_OUT` to the `POWER_IN` of a lamp.
![image](https://user-images.githubusercontent.com/662874/118415122-63f2c380-b65d-11eb-9b28-fe9d999c4400.png)

# Expected Behavior
When Test mode starts I would expect
- The Battery begins draining immediately.
-The two lamps light up immediately.
- The primary relay to display a 'Load' value of 10kW (2 lamps * 5kW Power Consumption each) and a 'Power' value of 10kW as well (or very quickly increasing to meet that amount)
- The secondary relay to display a 'Load' value of 5kW and a 'Power' value of 5kW as well (or very quickly increasing to meet that amount)

# Observed Behavior
When Test mode starts I observe:
- The Battery does not begin draining for about 10 seconds
- The two lamps remain dark for about 10 seconds
- The primary relay always displays a 'Load' value of 10kW, and a 'Power' value of 0 for about 10 seconds at which point it increase until it is at 10kW.
- The secondary relay always displays a 'Load' value of 5kW, and a 'Power' value of 0 for about 10 seconds at which point it increase until it is at 5kW.

# Version
v0.13.3.11 (Release Windows, branch release, revision 7096536c11) on Steam.

# Additional information

If I use a switch to disable the relays via their `SET_STATE` input, the lights will only turn on after 10 seconds of time have passed with the relays being turned on. 

So for example if the switch defaults to off, I can start Test mode, wait however long I want, turn the switch on for 4 seconds, turn it off again for 20 seconds, and then if I turn it on again the lights will turn on after another 6 seconds have passed - with the switch having been in the 'on' position for about 10 seconds total.

Capture:

https://user-images.githubusercontent.com/662874/118415681-ae297400-b660-11eb-8eae-c1f435a81714.mp4

---------------

If I add a third lamp (green) directly to the battery, not connected to the relays at all:
![image](https://user-images.githubusercontent.com/662874/118414781-6a803b80-b65b-11eb-8edc-c112081c82e3.png)
Then both that third lamp and the first relay's lamp (red) will turn on immediately, without a 10 second delay. The secondary relay's lamp (blue) however will still take about 10 seconds.

Capture:

https://user-images.githubusercontent.com/662874/118414794-753ad080-b65b-11eb-9fc3-05899185ed5a.mp4

# Disclaimer

To be clear, I am not looking for tips on how to avoid this issue. I am simply trying to understand the behavior I observed which in my opinion goes against the mental model that the notion of a 'relay' would bring with it.

It is would be reasonable to expect  that a relay effectively just bridges a connection when enabled, and that power would flow immediately with no delay.

This 10 second delay is very unintuitive.

**Comment by JohannesMP** [comment] 2021-05-16 22:29
More weirdness and an even more simplified use case:
- Two relays in sequence, with a lamp on each
- Both lamps will turn on after 10 seconds
![image](https://user-images.githubusercontent.com/662874/118414604-70295180-b65a-11eb-8141-cc23ce292539.png)

However if I then add a 3rd lamp directly to the battery, not connected to the relays at all:
![image](https://user-images.githubusercontent.com/662874/118414781-6a803b80-b65b-11eb-8edc-c112081c82e3.png)

Then both that 3rd lamp and the first relay's lamp will turn on immediately:
https://user-images.githubusercontent.com/662874/118414794-753ad080-b65b-11eb-9fc3-05899185ed5a.mp4

**Comment by JohannesMP** [comment] 2021-05-16 22:51
ignomen on the Undertow Games discord explained this as follows: 

![image](https://user-images.githubusercontent.com/662874/118415316-7faa9980-b65e-11eb-8cb1-3daadea054cd.png)

**Comment by Ek-Videogames** [comment] 2021-05-24 16:55
Oddly I've been observing this 'booting up' effect even with batteries outputting directly to grid, and in some other systems. 
So possible its not an issue unique to the weird method that relays use.

**Comment by cshingle** [comment] 2022-02-03 01:09
@Regalis11 this one seems to be a duplicate of #7864 that happens to predate it. Hopefully you can soon close both of these.

**Comment by Regalis11** [comment] 2022-02-08 10:10
@cshingle This is not a duplicate, the other ticket is about the fluctuations in the grid after the initial "delay".

**Comment by Rokvach** [comment] 2022-03-09 11:59
Tested, working correctly. Closing.

**Closed by Rokvach** 2022-03-09 11:59 UTC
Labels: Bug, Code

**Comment by JohannesMP** [comment] 2022-03-13 23:59
@Rokvach I am unsure what you tested, but at the time of me writing this, I have verified that this issue persists in `Barotrauma v0.16.7.0 (ReleaseWindows, branch release, revision aa4c852c2c)`, using the file provided in the original issue `TEST_RelayBug3.sub`.

Specifically I am referring to these two specific test cases:

--------

### Test Case 1
- Load `TEST_RelayBug3` in editor
    - Note how the red `Lamp` is wired directly into the `Battery`'s `POWER_OUT` via a `Relay Component`
    - Note how the blue `Lamp` is wired directly into the `Relay Component` of the red `Lamp`, via its own `Relay Component`
- Start 'Test' mode

**Expected**:
- The red and blue `Lamps` _both_` turn on immediately, due to being directly connected to the battery.

**Observed**:
- The red and blue `Lamps` _both_ take 10 seconds to turn on

### Test Case 2
- Load `TEST_RelayBug3` in editor
- Use wiring mode to add a wire from the `Battery`'s `POWER_OUT` to the green Lamp's  `POWER`
- Start 'Test' mode

**Expected**:
- The green lamp turns on immediately, due to being directly connected to the battery
- Based on what we observed in Test Case 1, we'd expect the same thing to happen - a 10 second delay for both red and blue lights

**Observed**:
- The green lamp turns on immediately.
- The red lamp now turns on immediately, despite none of its wiring having changed, with the blue Lamp still being delayed.
- At the 10 second mark when the blue lamp turns on, the red lamp actually flickers off for a moment, as if its state is reset.

So wiring up the green lamp will bypass the 10 second delay for the red lamp, except when the 10 second delay occurs the red lamp still acts as if it was turned on for the first time, as observed by it clicking and 'fading in' at the same time as the blue lamp does.

--------

@Rokvach can you verify that both of these test cases I described are working as intended when you repeat them? Including the red light flickering off for a split second and playing its "turn on" animation at the 10 second mark, despite having been on as expected with the green Lamp connected?

I am very doubtful that this issue should be marked as closed. This behavior is confusing and more importantly very inconsistent with the wiring concepts that the game presents to the player.

If all of this is expected, please mark the issue as "Working as Intended" and I'll create a feature request issue instead of a bug.

**Comment by Rokvach** [comment] 2022-03-14 04:44
v0.16.7.0 doesn't have the new power rework changes, you can test this issue on the v0.17.0.0 Unstable build which you can find on Steam betas, if you want to still verify that its working. We have a PowerTestSub with the same testbed and other power related tests that the power rework fixes.

**Comment by JohannesMP** [comment] 2022-03-14 09:50
@Rokvach Gotcha! Specifying that you were testing v0.17.0.0 when marking the issue as closed would have been useful to include :) Maybe a "Fix in future version" issue tag.
