### ISSUE TITLE
Explosions dislodging projectiles, even with 0 force

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#11342] opened 2023-02-24 01:41 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

For some reason, projectiles can get dislodged from walls they're stuck on by explosion components, even if the explosion has no force. Also see

Projectile falling off

https://user-images.githubusercontent.com/73229309/221071041-c883979f-69cc-4a74-9c6f-1850df3ffd99.mp4

The XML (reskinned)

```xml

  <Item name="Piezojectile" identifier="Piezojectile" category="Weapon" maxstacksize="1" interactthroughwalls="true" cargocontaineridentifier="metalcrate" tags="mediumitem,harpoonammo" Scale="0.5" impactsoundtag="impact_metal_light" health="50" damagedbyexplosions="false" damagedbyprojectiles="false" damagedbymeleeweapons="true" damagedbyrepairtools="true" sonarsize="20">
    <Sprite texture="Content/Items/Weapons/weapons_new.png" sourcerect="262,363,172,14" depth="0.55" origin="0.5,0.5" />
    <Body width="160" height="50" radius="25" density="25" />
    <LightComponent range="200.0" lightcolor="30,180,255,150" IsOn="true" castshadows="false" allowingameediting="false" pulseamount="0.5" pulsefrequency="0.5" Flicker="0.2" Flickerspeed="0.5"/>
    <Projectile characterusable="false" launchimpulse="5" sticktocharacters="false" sticktoitems="true" sticktostructures="true" sticktodoors="true">
      <Attack structuredamage="15" itemdamage="15" targetforce="20" severlimbsprobability="0">
      </Attack>
	  <!-- remove if not stuck -->
      <StatusEffect type="OnNotContained" target="This" Snapped="true" delay="3" condition="-100" checkconditionalalways="true">
        <Conditional IsStuckToTarget="false" />
      </StatusEffect>
      <StatusEffect type="OnBroken" target="This" Snapped="true">
		<Remove />
        <particleemitter particle="brownchunks" drawontop="true" particleamount="40" velocitymin="100" velocitymax="500" anglemin="0" anglemax="360" scalemin="0.1" scalemax="0.4" />
      </StatusEffect>
      <StatusEffect type="OnActive" target="This" lifetime="0.5">
        <ParticleEmitter particle="ammotrailwater" copyentityangle="true" anglemin="0" anglemax="0" particleamount="10" velocitymin="-10" velocitymax="-100" scalemin="0.5" scalemax="1" />
      </StatusEffect>
    </Projectile>
    <ElectricalDischarger duration="0.2" outdoorsonly="false" powerconsumption="0" range="600" rangemultiplierinwalls="1">
      <Attack targetimpulse="50">
        <Affliction identifier="stun" strength="2"/>
        <Affliction identifier="burn" strength="5"/>
      </Attack>
      <StatusEffect type="OnUse">
        <sound file="Content/Items/Weapons/WEAPONS_electricalDischarge1.ogg" range="2000" selectionmode="random" />
        <sound file="Content/Items/Weapons/WEAPONS_electricalDischarge2.ogg" range="2000" />
        <ParticleEmitter particle="risingbubbles" anglemin="0" anglemax="360" particleamount="50" velocitymin="50" velocitymax="100" scalemin="1" scalemax="2" />
        <Explosion range="2000.0" camerashake="3" stun="0" force="0.0" flames="false" shockwave="false" sparks="True" underwaterbubble="false" />
      </StatusEffect>
    </ElectricalDischarger>
    <ItemComponent>
      <!-- when the component activates, apply extra load to nearby items and deactive the component -->
      <StatusEffect type="OnUse" target="NearbyItems" targettags="junctionbox" range="800.0" setvalue="true" stackable="false" extraload="1000" />
      <StatusEffect type="OnActive" target="This" IsActive="false" delay="5" />
	  <!-- trigger -->
      <StatusEffect type="Always" target="UseTarget,This" stackable="false" delay="20">
        <Conditional targetitemcomponent="Projectile" IsStuckToTarget="True" />
		<Use />
      </StatusEffect>
	  <!-- scale up -->
      <StatusEffect type="OnNotContained" target="This" Scale="0.0">
        <ParticleEmitter particle="ElectricShock" distancemin="0" distancemax="70" particlespersecond="2.0" particleamount="5" emitinterval="2.1" scalemin="0.1" scalemax="0.1" copyentityangle="true" />
	  </StatusEffect>
    </ItemComponent>
  </Item>
```

### Reproduction steps

1. Load Piezojectile into a harpoon
2. Shoot at the bottom of a ship
3. Wait for discharge

### Version

Factions

**Comment by Regalis11** [comment] 2023-02-24 08:42
I'm afraid I could not reproduce this. I also could not use the provided XML as-is, since the projectiles aren't pickable or stackable (= I can't place them in the harpoon gun). After making them pickable and setting the stack size to 8, here's the result:

https://user-images.githubusercontent.com/14351070/221132127-eb7ffdfe-df97-42bb-9820-3972957ef38b.mp4

**Comment by ubertpendragon** [comment] 2023-02-24 12:53
Sorry wrong game version, this is happening on factions build

This mostly happens to projectiles that are suck with a certain angle
The harpoon on the left is stuck but gets dislodged on the first zap
![image](https://user-images.githubusercontent.com/73229309/221183406-4010a066-673a-4c85-a162-e48c2eaaf880.png)

**Comment by Regalis11** [comment] 2023-02-27 11:58
Seems to be caused by the same issue as https://github.com/Regalis11/Barotrauma/issues/11343 - it's not actually the explosion that's dislodging them, they get dislodged because the StatusEffect that triggers the EDC also relaunches the projectile.

**Comment by Regalis11** [comment] 2023-03-01 16:03
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/34dc7371e842ba468a514f19c0f178875e68aace

**Comment by Rokvach** [comment] 2023-04-13 08:35
Tested, working correctly. Closing.

**Closed by Rokvach** 2023-04-13 08:35 UTC
Labels: Bug, Code, Modding
