### ISSUE TITLE
Bots can detach modded items without the required item

### ISSUE THREAD

**Issue by ricky122122** [Regalis11/Barotrauma#10428] opened 2022-11-17 22:39 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I made some vanilla items detachable and bots when repairing trigger the detach and sometimes fully detach the item from the wall the required item to detach it is crowbar and the bots are holding a wrench and screwdriver

### Reproduction steps

edit a vanilla item and add       <Body width="154" height="160" density="40" />
      <Holdable selectkey="Select" pickkey="Use" slots="RightHand+LeftHand" msg="[E] Detach (Crowbar)" PickingTime="10.0" aimpos="35,-10" handle1="0,0" attachable="true" attachedbydefault="true" aimable="true">
        <RequiredItem identifier="crowbar" type="Equipped" />
        <StatusEffect type="OnActive" target="Character" SpeedMultiplier="0.75" setvalue="true" />
      </Holdable>
      this will make it detachable and only by a crowbar that is equipped
      then start a game up with bots and set them to repair and emp something you will then see the bot trigger the detach for a frame this can cause them to detach the item in certain circumstances 

### Bug prevalence

Happens every now and then

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-11-18 09:19
Thank you for the report!

I unfortunately couldn't reproduce the problem. What kind of modifications did you do to the item to make it attachable? I'd suspect the problem is the item isn't set to be attached by default, which means you or the bots can pick the items up without needing any tool.

**Comment by ricky122122** [comment] 2022-11-18 19:32
oh sorry it musive gotten deleted when i put it in the post 
[holdable.txt](https://github.com/Regalis11/Barotrauma/files/10044299/holdable.txt)

**Comment by ricky122122** [comment] 2022-11-18 21:07
it doesn't happen every time they repair something but it happens often enough that I caught it a few times in a few minutes

https://user-images.githubusercontent.com/111702225/202802534-a8e46e36-4c9f-42aa-a14e-a9cc03079332.mp4

**Comment by Regalis11** [comment] 2022-11-21 08:47
Thank you for the extra info! Could you post the whole xml of the item though? I don't see anything wrong in that snippet, but I suspect the problem might be somewhere else (perhaps something to do with how the item overrides the base item, if it's a variant of some other item).

**Comment by ricky122122** [comment] 2022-11-21 18:51
[Electricity Override.txt](https://github.com/Regalis11/Barotrauma/files/10059704/Electricity.Override.txt)
here is the whole xml for all my overridden electrical components the first item is the junction box but this happens for sure with super capacitor's and most likely all the others

**Comment by mkaito** [comment] 2023-01-11 18:20
I've seen this happen while using ricky's mod. Can I help provide additional data?

**Comment by Nathan8489** [comment] 2023-03-25 03:55
After reviewing the source code, it seems that the AI crew bypasses the `RequiredItem` with when attempting to repair an item.
https://github.com/Regalis11/Barotrauma/blob/b0adfc7f7ca60a919bebe0eecff49e80b8dfd467/Barotrauma/BarotraumaShared/SharedSource/Characters/AI/Objectives/AIObjectiveRepairItem.cs#L188-L189

the `Item.TryInteract` function will attempts to interact with every components of an item, which includes both the `Holdable` and `Pickable` component.

**Comment by Regalis11** [comment] 2023-04-20 17:06
Finally got back to diagnosing this. @Nathan8489 you're absolutely right, that seemed to be the cause behind the issue, thank you for pointing me in the right direction!

Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/8942d7890385ca0662b5925ca0f81186b0dd3b52 (commit in our private repo)

**Closed** 2023-06-29 07:47 UTC
Labels: Bug, Code, Modding
