### ISSUE TITLE
Crashing when joining Multiplayer Lobby

### ISSUE THREAD

**Issue by M3M3M31S73R** [Regalis11/Barotrauma#11866] opened 2023-04-18 19:50 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When my friend tries to join my lobby, he crashes with the report I've put below, though when my other friend tries to join my lobby everything is fine. I can also join his lobbies just fine without any incident 

### Reproduction steps

1. Host a multiplayer Lobby
2. Have my friend try to join
3. He crashes

### Bug prevalence

Happens every time I play

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
https://cdn.discordapp.com/attachments/815667720472231957/1097547748217196665/image.png
```

**Comment by Regalis11** [comment] 2023-04-19 07:08
[You have already reported the issue](https://github.com/Regalis11/Barotrauma/issues/11862). This is a duplicate of https://github.com/Regalis11/Barotrauma/issues/11789. We've got a fix coming up for this in a future patch, but for now it's possible to work around the issue by disabling the mods that are causing the error. Sorry for the inconvenience!

**Closed by Regalis11** 2023-04-19 07:08 UTC
