### ISSUE TITLE
Crash on launch - HELP

### ISSUE THREAD

**Issue by Dregz** [Regalis11/Barotrauma#9865] opened 2022-09-13 10:11 UTC
**Disclaimers**
 I have searched the issue tracker to check if the issue has already been reported.
My issue happened while playing a fresh install (no mods).

**What happened?**
When launching the game, it crashes instantly (before a window opens)

**Reproduction steps**
Install the game (on any hard drive)
Launch
Crash

**Bug prevalence**
It happens every time I launch

**Version**
0.18.15.1

**Which operating system did you encounter this bug on?**
Windows

**Relevant error messages and crash reports**
```
Barotrauma Client crash report (generated on 13/09/2022 20:04:54)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


116B6C514DB831BB68D5A8F96ACE87C4


Game version 0.18.15.1 (ReleaseWindows, branch hf, revision 91a05f31ff)
Graphics mode: 3840x2160 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: None
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce GTX 1080
    Display mode: {Width:3840 Height:2160 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: PresentationParameters.DeviceWindowHandle must not be null. (System.ArgumentException)
Target site: Void PlatformReset()
Stack trace: 
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformReset() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 483
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Reset() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.cs:line 616
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Reset(PresentationParameters presentationParameters) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.cs:line 632
   at Microsoft.Xna.Framework.GraphicsDeviceManager.ApplyChanges() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\GraphicsDeviceManager.cs:line 328
   at Barotrauma.GameMain.SetWindowMode(WindowMode windowMode) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 347
   at Barotrauma.GameMain.ApplyGraphicsSettings(Boolean recalculateFontsAndStyles) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 324
   at Barotrauma.GameSettings.SetCurrentConfig(Config& newConfig) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Settings\GameSettings.cs:line 494
   at Barotrauma.GameMain.<ApplyGraphicsSettings>g__updateConfig|110_0() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 293
   at Barotrauma.GameMain.ApplyGraphicsSettings(Boolean recalculateFontsAndStyles) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 305
   at Barotrauma.GameMain.LoadContent() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 398
   at Microsoft.Xna.Framework.Game.Initialize() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 553
   at Barotrauma.GameMain.Initialize() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 375
   at Microsoft.Xna.Framework.Game.DoInitialize() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 685
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 382
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59


Last debug messages:
[13/09/2022 20:04:54] Logged in as Dregz (SteamID STEAM_1:0:34031366)
```

**Comment by Regalis11** [comment] 2022-10-09 17:01
Duplicate of https://github.com/Regalis11/Barotrauma/issues/6292

**Closed by Regalis11** 2022-10-09 17:01 UTC
