### ISSUE TITLE
Game Crashes on steam launch (0x8876017C, D3DERR_OUTOFVIDEOMEMORY)

### ISSUE THREAD

**Issue by SmileyWiley7** [Regalis11/Barotrauma#10438] opened 2022-11-19 03:45 UTC
I've reinstalled my graphics drivers, insured my DirectX is up to date, made sure windows is up to date, tried force running in windowed borderless mode, turning off my antivirus during install, and even updating java to see if that had anything to do with it. Nothing has worked, is there anything that can be done to help the game launch? Below is the crash report, thanks for your time.

Barotrauma Client crash report (generated on 11/18/2022 20:34:28)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

0DC439F0B0CA5A5A6693500952309D61

Game version 0.19.14.0 (ReleaseWindows, branch release, revision 0daf5b87bd)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: None
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit
    GPU name: NVIDIA GeForce GTX 1050 Ti
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: HRESULT: [0x8876017C], Module: [Unknown], ApiCode: [Unknown/Unknown], Message: Unknown (SharpDX.SharpDXException)
Target site: Void CheckError()
Stack trace: 
   at SharpDX.Result.CheckError()
   at SharpDX.DXGI.SwapChain.Present(Int32 syncInterval, PresentFlags flags)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 1010
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Present() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.cs:line 600
   at Microsoft.Xna.Framework.SdlGamePlatform.Present() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 250
   at Microsoft.Xna.Framework.Game.EndDraw() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 522
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 667
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[11/18/2022 20:34:28] Attempting to open ALC device "OpenAL Soft on Speakers (Realtek High Definition Audio)"
[11/18/2022 20:34:26] Logged in as Smiley Wiley (SteamID STEAM_1:0:68924143)

**Comment by Regalis11** [comment] 2022-12-01 12:48
Thank you for the report!

This error code (0x8876017C) seems to be D3DERR_OUTOFVIDEOMEMORY, meaning that your graphics card seems to have run out of memory. Which graphics card do you have? Does it meet the game's minimum requirements (at least 2 GB video memory)?

Thanks and sorry for the inconvenience!

**Comment by SmileyWiley7** [comment] 2022-12-03 17:49
Hi Regalis,

Thank you for looking into my ticket. I am currently running a NVIDIA GeForce GTX 1050 Ti, with 15.87 GB of Ram.

**Comment by Regalis11** [comment] 2023-06-30 12:37
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7055

**Closed by Regalis11** 2023-06-30 12:37 UTC
Labels: Bug, Need more info, Code, Crash
