### ISSUE TITLE
Platforms become invisible

### ISSUE THREAD

**Issue by FarrunDragon** [Regalis11/Barotrauma#8763] opened 2022-04-10 16:11 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In outposts (old model) platforms can disappear, while collision is still in effect.

[**Steps] To Reproduce**
Enter outpost, head to reactor room

**Version**
Windows, Unstable V0.17.8.0

![image](https://user-images.githubusercontent.com/50345634/162628775-79b198b3-d22e-4dee-be81-f7cda03fcfd8.png)

**Comment by Regalis11** [comment] 2022-04-11 11:48
Probably related: https://github.com/Regalis11/Barotrauma-development/issues/3251 (ticket about a similar issue in our private repo)

**Comment by juanjp600** [comment] 2022-04-11 16:01
Potentially fixed in https://github.com/Regalis11/Barotrauma-development/commit/7d614b861a1f7aef0d2527fe5175f18fbf8d087b

**Comment by Rokvach** [comment] 2022-04-11 17:31
I wasn't able to reproduce this issue anymore, seems to be working correctly. Closing.

**Closed by Rokvach** 2022-04-11 17:31 UTC
Labels: Bug, Code
