### ISSUE TITLE
Button vanishing after outside sub placement

### ISSUE THREAD

**Issue by SumNutz** [Regalis11/Barotrauma#2881] opened 2020-05-22 21:55 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
placing down a button item outside the sub makes it vanish and impossible to recover

**Steps To Reproduce**
(tested in typhon 2, captain, multiplayer, campaign) take a button item (or make it), equip it to activate grid to place it down and place it on a structure outside a hull (in this case, in the bottom docking port)

**Version**
Windows 10, stable build 0.9.9.1

**Additional information**
maybe all placeable wiring items suffer the same (Eg.: Relay, SGN Component)

**Comment by Regalis11** [comment] 2020-05-23 08:56
Thanks for the report! We actually had another report about this same issue and fixed the issue just recently. The fix is not included in the public version yet, but coming up in the next update.

Closing as a duplicate of #2065

**Closed by Regalis11** 2020-05-23 08:56 UTC
