### ISSUE TITLE
Bank balance mismatch effecting client connected to a mulplayer server

### ISSUE THREAD

**Issue by gerbilOFdoom** [Regalis11/Barotrauma#8993] opened 2022-04-27 05:33 UTC
- [x ] I have searched the issue tracker to check if the issue has already been reported. -- Appears to be nothing related to this bug

**Description**
One player on my server experienced an issue where, from their perspective, the group's bank balance showed 8,134. The rest of our crew showed a bank balance of 134. I believe this is the amount of mk we had as total income during the course of this game save. Player was able to put in a balance transfer request of this full amount, which the crew could approve, but that would not result in an actual transfer. I suspect this is an issue with how bank balances are updated for each client, or some bug effecting that for this particular player.

**Steps To Reproduce**
Unknown, have not witnessed since. Not sure whether the player was there from the start of the server or joined in part way through.

**Version**
Steam mainline version as of 26 APR 2022. Unknown which OS.

**Additional information**
Regrettably, I have no additional information at this time. Chose to make the report with what information I have so this is documented rather than waiting to see if it occurs again.

**Comment by 3e849f2e5c** [comment] 2022-04-28 18:20
This sounds like some outpost service is causing the client to add money into the bank on their screen, need to figure out which one it is

**Comment by 3e849f2e5c** [comment] 2022-04-28 21:10
Only case I could find in the code where the client adds money into the bank was during the mission rewards distribution but I don't think that could have been it, Fixed regardless in https://github.com/Regalis11/Barotrauma-development/commit/3a4456726662900ac180f6b3163bd931e113f637 while waiting to see if someone can find steps to reproduce it

**Comment by Rokvach** [comment] 2022-06-07 20:30
I haven't noticed this happening since the fix, either a rare issue or the fix is working correctly, going to close this ticket regardless, can be re-opened if the issue does resurface. Closing.

**Closed by Rokvach** 2022-06-07 20:30 UTC
Labels: Bug, Code, Networking
