### ISSUE TITLE
Dangerous Pressure Warning on Nav Terminal when sub can withstand it

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4895] opened 2021-01-25 15:37 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
[Save 0.zip](https://github.com/Regalis11/Barotrauma/files/5867619/Save.0.zip)
[KailleraMapMod.zip](https://github.com/Regalis11/Barotrauma/files/5867622/KailleraMapMod.zip)

I was driving through Sharpitor Linea (North of the current outpost), and my navigation terminal was flashing the Dangerous Pressure warnings. My submarine was getting warnings at 3500m when the submarine can withstand up to 4418m. Drives just fine.

**Version**
0.12.0.0

**Comment by Jlobblet** [comment] 2021-01-25 15:57
This appears to be caused by
https://github.com/Regalis11/Barotrauma/blob/c2e181ee6dd5799196cf0ea45fafe14e8b58ddbf/Barotrauma/BarotraumaShared/SharedSource/Map/Submarine.cs#L252-L259
which only accounts for the Level's crush depth, not the submarine's.
I suggest changing this to 
```c#
public bool AtDamageDepth
{
    get 
    {
        if (Level.Loaded == null || subBody == null) { return false; }
        return
            RealWorldDepth > Level.Loaded.RealWorldCrushDepth
            && RealWorldDepth > RealWorldCrushDepth; 
    }
}
```
which reflects how UpdateDepthDamage works in 
https://github.com/Regalis11/Barotrauma/blob/c2e181ee6dd5799196cf0ea45fafe14e8b58ddbf/Barotrauma/BarotraumaShared/SharedSource/Map/SubmarineBody.cs#L446

**Comment by Regalis11** [comment] 2021-01-26 07:37
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e4d6726cff684424d9c0178ef8a109a10c1e674a

**Comment by Rokvach** [comment] 2021-01-26 08:38
Tested, working correctly. Closing.

**Closed by Rokvach** 2021-01-26 08:38 UTC
Labels: Bug, Code
