### ISSUE TITLE
Shooting Harpoon at Enemies In Broken Hull OBLITERATES the Submarine

### ISSUE THREAD

**Issue by DraaGulFireclaw** [Regalis11/Barotrauma#4440] opened 2020-12-06 05:54 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Enemy crawlers broke into the hull. They are "stuck" in small holes inside the hull. Fellow crew member (actual player, multiplayer) shoots at the crawler with a harpoon gun. Crawler dies. Submarine is immediately destroyed. ALL hull breaks in an instant, literally the entire submarine's hull breaks. Crawler's corpse spasms around.

This happened two times. First time crawler was stuck in the narrow docking port of the Humpback. Second time the crawler was inside the front ballast tank's broken hull.

**Steps To Reproduce**
It can be reproduced, most likely, by getting small enemies stuck in narrow spaces of the submarine (docking port worked in one instance, too), and killing them with a harpoon gun.

**Version**
Game Version: 0.10.6.2
Operating System: Windows 10

**Additional information**
None.

**Comment by Regalis11** [comment] 2020-12-06 17:12
Most likely caused by the same issue as https://github.com/Regalis11/Barotrauma/issues/4368, possibly fixed in https://github.com/Regalis11/Barotrauma-development/commit/35412240cc720c362a85a56a290c8b000b001dbb

**Comment by Rokvach** [comment] 2020-12-11 09:50
Closed the other ticket already so closing this one as well

**Closed by Rokvach** 2020-12-11 09:50 UTC
Labels: Bug, Code
