### ISSUE TITLE
Turrets not working properly on dedicated servers.

### ISSUE THREAD

**Issue by LordZZT** [Regalis11/Barotrauma#232] opened 2018-01-19 22:39 UTC
When playing with some submarines on a dedicated server (linux or windows) turrets do not fire torpedos in the correct direction.

![example 1](https://user-images.githubusercontent.com/3058885/35174990-744dff86-fd26-11e7-855e-a400f3b8b002.png)
![example 2](https://user-images.githubusercontent.com/3058885/35174991-7465168a-fd26-11e7-8ea3-dbfa0cad9b2b.png)

[Stateless MkIX.zip](https://github.com/Regalis11/Barotrauma/files/1648095/Stateless.MkIX.zip)

**Comment by NilanthAnimosus** [comment] 2018-01-20 12:33
This is an issue where the dedicated servers timing was operating at a different speed to the clients in version 0.7.0.1, this should be fixed from commit 1aa654a 's changes (For the next version).

**Comment by NilanthAnimosus** [comment] 2018-03-06 15:21
I think this needs to be reopened. testing on the dedicated shows this is still a problem.

Im not sure what the rotation values should be, but they seem to be using values like 0 - 6, the turret always seems to fire top-left.

The dedicated timing would have explained the turrets rotation becoming desynced and firing at a different arc, but this issue appears to be that the arc is limited to a very specific angle.

**Comment by Regalis11** [comment] 2018-03-06 15:40
Does that happen consistently on all subs or on some specific ones? I couldn't reproduce it on any of the vanilla subs.

**Comment by NilanthAnimosus** [comment] 2018-03-06 16:14
This is me running the vanilla dedicated server on commit 2880ca3adbeb61712c3217f304759d6600fef031

It's the most compatible with my unmodified vanilla 0.8.0.4 networking-wise, I cant connect to my visual studio copy from a standard game or a compiled once as the hash is incorrect for me and constantly replace the content files on run.

![image](http://puu.sh/zBQVw/ffa1870bcf.jpg)

I don't think this occurs on all submarines, But its hard to tell, the dedicated server was not allowing me (I could use other commands, and I added them!) the usage of lights, and my screen is too dark to see the trajectory of the railgun rounds (I actually cannot see in the ocean anymore, my screens a little darker).

I'll give it a quick further testing though. Its quite possible the item rect's solved this somehow (?)

**Comment by NilanthAnimosus** [comment] 2018-03-06 16:39
I cherry picked commit 840d9e05399e488ce61205138e73992479f564ab

And that commit actually fixed this issue. You can close this regalis.

**Closed** 2018-03-06 18:13 UTC
Labels: bug
