### ISSUE TITLE
Honkmother Quest Issues

### ISSUE THREAD

**Issue by Dathomerian554** [Regalis11/Barotrauma#12683] opened 2023-09-18 05:35 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I understand this issue was already addressed in #12464, however it was marked as fixed and I'm still having the issue.  I do not see any verification that the quest has been completed when I bonk an abyssal creature (dead or alive).  Note that I have not ended a mission after to check for the next quest line because I don't want to leave a known abyss creature without finishing the quest.  I have looked at old articles on what the completed quest looks like, and it shows a notification bubble confirming it is finished.  If this confirmation has been removed, then I guess there is no bug.  

### Reproduction steps

1. I talk to the Jestmaster with the clown mask.  
2. The Jestmaster gives me a new task of bonking an abyssal creature with a toy hammer.  
3. I bonk the abyss creature, nothing happens.  

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

MacOS

**Comment by Dathomerian554** [comment] 2023-09-18 06:07
I just realized maybe the fix will only be implemented in the next game update.  If so, I apologize.

**Comment by Regalis11** [comment] 2023-09-18 07:07
Yep, the fix has been implemented but the fix unfortunately hasn't made it to the public version yet. :/ Sorry for the inconvenience!

Closing as a duplicate of https://github.com/Regalis11/Barotrauma/issues/12464

**Closed by Regalis11** 2023-09-18 07:07 UTC
