### ISSUE TITLE
Water flow sound plays in the main menu

### ISSUE THREAD

**Issue by SuperBot-548** [Regalis11/Barotrauma#4050] opened 2020-10-10 13:30 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Found such a glitch, when you exit the server, the sound of water flow is stored in the main menu. 

**Steps To Reproduce**
Go to the server, damage the submarine, the sound of a stream of water will be heard and disconnect from the server, the sound will remain in the menu.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**

**Comment by Regalis11** [comment] 2020-10-12 10:48
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a936fcc59c4d98b4db6fd52038f546bce9791534

**Comment by Xeavas** [comment] 2020-10-13 17:26
Doesn't seem to play water flow sound in the menu, however, water flow sound will become either a persistent audio loop or absolutely no water flow noise at all. No direct way to replicate other than I was playing around with azmiuth's airlock in sub editor test mode.

Elaboration on audio bugs : The audio bugs seemed persistent across completely different instances (i.e bug occured in sub editor test mode, you create a new SP campaign and the bug is still there)

**Comment by someone972** [comment] 2020-10-13 18:23
Did a capture of the issue, the video is available here: [https://youtu.be/9kOptzdYQ4I](https://youtu.be/9kOptzdYQ4I)
It appears that the X and Y of the position the water flowing sounds are being set to is going off into weird ranges, and when they get far enough away from the sub the sound appears to go mute. Hopefully this helps narrow it down. You can check the camera position vs sound position in the video. At the end I go back to sub editor and launch it again, and the positions stay all out of wack. I was unable to reproduce the sound fading out like this in the previous unstable. 

Note: The log produced below is from a custom exe build, I'm happy to add additional logging if needed to help triage.
[DebugConsoleLog_Client_2020-10-13 11_57_21.7847.log.zip](https://github.com/Regalis11/Barotrauma/files/5373293/DebugConsoleLog_Client_2020-10-13.11_57_21.7847.log.zip)

**Comment by someone972** [comment] 2020-10-14 07:31
Note: the issues which I collected the logs for has been fixed in #4078 and #4079, which were merged to the private repo.

**Comment by Rokvach** [comment] 2020-10-14 09:16
Tested, working correctly. Closing.

**Closed by Rokvach** 2020-10-14 09:16 UTC
Labels: Bug, Code
