### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by Verdun192** [Regalis11/Barotrauma#5013] opened 2021-02-08 19:32 UTC
I can't give too much info, we were using a modded submarine and then the game just crashed.
It doesn't appear to be in relation to the submarine but what do I know.
[crashreport_object.log](https://github.com/Regalis11/Barotrauma/files/5946338/crashreport_object.log)

**Comment by Regalis11** [comment] 2021-02-09 07:33
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3927

**Closed by Regalis11** 2021-02-09 07:33 UTC
