### ISSUE TITLE
Ruin not connected to level waypoints + cave waypoint clipping

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#7554] opened 2021-11-30 10:05 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Steps To Reproduce**
1. Load up level editor
2. Select level type coldcavernsmaze
3. Use seed VvdU5qjD

**Version**
0.15.16.0
Branch: dev
Build: Release
Commit: https://github.com/Regalis11/Barotrauma-development/commit/e92810c8e23b1f989a32b4feb8a895d511946875

**Additional information**
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/163d9222-c467-4ce4-98af-79501f433355)
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/ecf01639-afa1-4256-af84-ed4293435c20)

On the same level there's also a slight waypoint level clipping on one of the paths leading to a cave
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/1c261abd-fbce-4c5d-aeaa-a4170a6947fb)

**Comment by Regalis11** [comment] 2021-11-30 10:08
Duplicate of https://github.com/Regalis11/Barotrauma-development/issues/2867

**Closed by Regalis11** 2021-11-30 10:08 UTC
Labels: Bug, Code
