### ISSUE TITLE
Linux Mutiplayer Loading Error on Some Servers

### ISSUE THREAD

**Issue by 14536781456145306134508610346872457245** [Regalis11/Barotrauma#11468] opened 2023-03-06 23:50 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Error in ClientRead. Owned submarine index was out of bounds. Index: 18, submarines: 

when joining some servers (the top ones for example: the traitor server)

### Reproduction steps

Start game
Join mutiplayer
Join a few other random servers
some servers have this error while some does not, all joined servers are not modded.

System: ArchLinux everything latest - Plasma KDE + xorg, steam latest, no compatibility tool used, native Linux.

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Linux

### Relevant error messages and crash reports

```shell
Error in ClientRead. Owned submarine index was out of bounds. Index: 18, submarines:
```

**Comment by Regalis11** [comment] 2023-03-07 07:57
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11454

**Closed by Regalis11** 2023-03-07 07:57 UTC

**Comment by 14536781456145306134508610346872457245** [comment] 2023-03-07 23:25
I believe this is different for a few reasons:
1. My system is Linux and on windows i have no problem with the same servers | this is Linux's bug
2. the other issue have differ Index number in the errors, mine what ever which server or which way i join it only shows the Index: 18

can someone just confirm and recheck this.

**Comment by Regalis11** [comment] 2023-03-08 07:58
1. Those linked issues happen when starting a round takes too long: I doubt it's actually an OS-specific issue. I would suspect the round just takes a little longer to start on your Linux system.
2. The index depends on which submarine you've chosen and which submarines you have available, so it can vary even though the underlying issue is the same.

**Comment by 14536781456145306134508610346872457245** [comment] 2023-03-12 22:08
Now linux is completely broken
you can't even join multiplayer games on almost 90% of the servers
If you are a real; developer you should check and verify that linux even works [ArchLinux]
