### ISSUE TITLE
Mantis broken latest update

### ISSUE THREAD

**Issue by MrTeco** [Regalis11/Barotrauma#3875] opened 2020-09-22 15:13 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The Mantis animations and physics don't work, the Mantis body parts don't move properly and the character sprite is flying up and down, and the Mantis appears on floors below or above the current floor when doing this. (This is inside of the submarine, don't know if their swimming is fine)

**Steps To Reproduce**
Once in-game, spawn a mantis inside of the submarine. Or look at it in the character editor.

**Version**
Barotrauma v0.10.5.1

**Comment by itchyOwl** [comment] 2020-09-23 07:18
Probably caused by Regalis11/Barotrauma-development@f9c4ccc. A workaround is to set the HeadAngle to NaN, which can't be done in the editor. Moreover using NaN means you can't set the angle. Should we make the fix optional, as it can potentially break user made content too?

**Comment by itchyOwl** [comment] 2020-10-12 13:28
Fixed in Regalis11/Barotrauma-development@64bf519

**Comment by Rokvach** [comment] 2020-10-13 07:25
No issues, closing.

**Closed by Rokvach** 2020-10-13 07:25 UTC
Labels: Bug, Code, Low prio
