### ISSUE TITLE
[Dev Version] AI problems

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#1268] opened 2019-03-11 19:15 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Alright, two problems. First of all, when fixing leaks or doing basically anything else bots gets stuck on the ladders for a good five minutes. Second of all, bots outright don't follow my orders sometimes, I tell them to operate the reactor they don't even go near it. I tell them to fix leaks they don't do nothing. It's a nightmare.

**Steps To Reproduce**
Load up a game of steam barotrauma, and try to beat a campaign level by yourself, using bots.

**Additional information**
big fatty chunky peanut butter slimy ranchy raunchy chungus poo

**Comment by VelonacepsCalyxEggs** [comment] 2019-03-11 19:42
same problem

**Comment by Regalis11** [comment] 2019-03-11 19:51
The AI still has quite a lot of issues in the latest version, but the fixes in the human-ai that we just merged today should take care of most of the problems. Still a lot of work to do, but it's a pretty huge improvement - we'll try to get a patch out soon to make the bots a little less stupid. :)

Anyway, this is pretty much a duplicate of #1034, so I think this one can be closed.

**Closed by Regalis11** 2019-03-11 19:51 UTC

**Comment by AbominationBanisher** [comment] 2019-03-11 22:20
Yeah, just posted again not only because I forgot of my previous post, but the new ladder bug was quite shloppy.

**Comment by itchyOwl** [comment] 2019-03-12 07:12
If any of the issues manifests after the update is rolled out, please report. And if you really want to help, run the game with debugdraw enabled and take a shot/video, so it's easier to fix. In the latest update, the debugmode has information about the ai states (or objectives) besides path finding, so it makes it a bit easier to see what actually causes the issue(s).
