### ISSUE TITLE
Unable to see what's going on beyond 500m of controlled character via Turret/Camera

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4317] opened 2020-11-15 00:23 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
So using drones beyond a certain range (about 500m?) is ineffective because the players are unable to see any characters/creatures. Bots don't have this issues I don't think at least.

https://www.twitch.tv/videos/803252690?t=01h26m49s

**Version**
~0.1100.0.6

**Additional information**
Unable to provide support fire because everything is invisible.

You also see freaky stuff like this where suits are being dropped in the drone, but it's showing up outside.
https://www.twitch.tv/videos/803252690?t=01h32m50s

**Comment by Regalis11** [comment] 2020-11-16 07:51
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9b281fdbcaa621967cd84969a1c5c8e1e546e9a3

**Comment by Rokvach** [comment] 2020-11-17 10:13
Noticing something strange while testing this with Remora's drone, when the drone is undocked from the main sub any creature you kill with the drones coilgun wont die, you will see the creatures health go down and suddenly jump back to max health again.

Repro steps:
1. Start a multiplayer mission with Remora selected
2. Undock Remora drone
3. Spawn a crawler in front of the drone and shoot it
4. Notice that you aren't able to kill the crawler

On my test the drone was barely off the main sub ~20-50m away.

**Comment by Kaillera** [comment] 2020-11-17 10:24
I can confirm Rokvach's bug. This existed even before Regalis' fix. This happens when there is no player or clients at the battle scene around like 200m from the character position controlling the drone.

**Comment by Regalis11** [comment] 2020-11-17 10:44
Could not reproduce. Tested by taking the drone 60 meters away from the sub, and I could kill crawlers with no issues:
![image](https://user-images.githubusercontent.com/14351070/99380433-a025b100-28d2-11eb-8daf-bc2bbf931356.png)

 Which branch did you test this on?

**Comment by Kaillera** [comment] 2020-11-17 10:48
It'll be more apparent if you go further

**Comment by Rokvach** [comment] 2020-11-17 10:49
I was testing this on the release branch, you could try aiming the body in slow bursts and see if there's a difference there

**Comment by Regalis11** [comment] 2020-11-17 11:10
Still no luck. Increased the wifi range and teleported the sub all the way to the end of the level with the drone still at the start, and still no issues here. Also testing in the release branch.
![image](https://user-images.githubusercontent.com/14351070/99383227-3c9d8280-28d6-11eb-95e6-678769766b58.png)

**Comment by Rokvach** [comment] 2020-11-17 12:43
And you are on multiplayer? Just checking. I did have some bots running around the sub as well, but doubt that's anything different

**Comment by Regalis11** [comment] 2020-11-17 13:00
Yep, I did all of the testing in multiplayer. I'll give it another try with some bots and simulated latency

**Comment by Rokvach** [comment] 2020-11-20 15:59
This might not be related to just drones, I was watching a stream where the server host was having the same issue whilst being inside a cave, they were doing a mudraptor nest mission and whilst he was trying to kill the mudraptors the mudraptors health kept jumping back to full health, using a revolver to try and kill it. They were able to kill them after switching to melee or when firing rapidly with a SMG.

**Comment by Regalis11** [comment] 2020-11-21 12:41
Think I managed to diagnose it now. It happened because the "simple physics mode" (in which the ragdoll is disabled, and only the main collider is active) was enabled server-side when the monster was far away from all players. Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/92f5243fc528ade42e85449434e04c5a2102e630

**Comment by Rokvach** [comment] 2020-11-21 13:06
Tested, I wasn't able to reproduce the issue anymore with the same method as I used previously, I even noticed a improvement of the health bar feeling much more responsive than it has prior to this fix. Closing.

**Closed by Rokvach** 2020-11-21 13:06 UTC
Labels: Bug, Code, Networking
