### ISSUE TITLE
"OnNotContained" statusEffect on coilgun bolts doesn't remove them when they fall out of a coilgun ammo box due to desync

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#2996] opened 2020-06-06 23:07 UTC
Coilgun bolts and other bullets from magazine-items (SMG round, etc) drop onto the floor when you deconstruct a coilgun ammo box or SMG mag that is still full.

There is a status effect to remove them when they are not contained, but it does not seem to recognize them as being no longer contained when they pop out of the deconstructor onto the floor. So coilgun bolts and SMG rounds just kind of accumulate on the floor of engineering.

**Comment by Regalis11** [comment] 2020-06-08 16:35
Could not reproduce

**Comment by Regalis11** [comment] 2020-07-09 10:10
No known steps to reproduce, closing for now

**Closed by Regalis11** 2020-07-09 10:10 UTC
Labels: Bug, Code, Need more info

**Comment by EricPfau** [comment] 2020-10-30 02:42
Still a problem as of 10.6.2. Can be reproduced by joining a dedicated server, deconstructing an empty SMG magazine, and watching the bullet drop to the floor.
