### ISSUE TITLE
Game crashing when I load a campaign

### ISSUE THREAD

**Issue by CodeGamerECA** [Regalis11/Barotrauma#5145] opened 2021-02-23 18:01 UTC
As soon as the campaign loads and it asks me to press any button, the game crashes.

This bug happened both in singleplayer and multiplayer in the campaign mode. On the singleplayer campaigns, as soon as I pressed a button when the game asked me to, the game crahsed, and on the online campaign, the game crashed when the campaign finished loading and I started spectating other players, but I am only including the singleplayer crash reports from the 2 campaigns I created.

Mac version
[crashreport (7).log](https://github.com/Regalis11/Barotrauma/files/6030952/crashreport.7.log)
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/6030958/crashreport.2.log)
[crashreport (3).log](https://github.com/Regalis11/Barotrauma/files/6030959/crashreport.3.log)

**Comment by Regalis11** [comment] 2021-02-25 09:29
Duplicate of https://github.com/Regalis11/Barotrauma/issues/4504

**Closed by Regalis11** 2021-02-25 09:29 UTC
