### ISSUE TITLE
[0.1003.0] Multiplayer - Placing down electrical components rubberbands back into inventory

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3120] opened 2020-06-17 09:00 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you're placing down electrical components (relays, Not, And, etc), the component will rubberbands back into your inventory. The only workaround is to put the affected component back into a cabinet or crate, and then take it out and place it down again.

**Version**
0.1003.0

**Comment by Regalis11** [comment] 2020-06-17 09:18
I wasn't able to reproduce this by doing the following:
1. Spawn an AND component in the character's inventory with the "spawnitem command"
2. Place it on a wall

1. Purchase AND components
2. Start a new round and get the components from the cargo room
3. Place them on a wall

**Comment by Kaillera** [comment] 2020-06-17 11:28
Dedicated server and had 3 players. Not sure if that'll do it.

**Comment by Udrakan** [comment] 2020-06-17 22:28
I noticed this a lot in multiplayer. Especially when moving fast and the placement grid jiggling.

**Comment by Kaillera** [comment] 2020-07-09 13:26
https://youtu.be/SGtPCyqW--A

**Comment by Regalis11** [comment] 2020-08-28 10:52
I think I found the cause now and fixed it in https://github.com/Regalis11/Barotrauma-development/commit/fdecabb2c2ff04bb9e133daf983c0f10b7a3fd52.

Steps to repro:
1. Set simulated latency very high (something like 0.5 s)
2. Equip the component and attach it immediately. 
3. If you attach the item faster than the latency, it should jump back to the inventory.

This happened because the server wouldn't send an inventory update when the item is attached and removed from the inventory; if the client received the update that confirms the item being equipped _after_ attaching the item, it'd jump back to the inventory client-side.

**Comment by Rokvach** [comment] 2020-08-31 04:37
Tested, working correctly. Closing.

**Closed by Rokvach** 2020-08-31 04:37 UTC
Labels: Bug, Code, Networking
