### ISSUE TITLE
[0.1001.0] Busted reactor after 2 fuel consumption upgrades

### ISSUE THREAD

**Issue by Camper125Lv** [Regalis11/Barotrauma#3006] opened 2020-06-07 20:09 UTC
**Description**
After 2 fuel consumption upgrades at the same time reactor showed this error in console, reactor was unwired and it's fuel rod input window was moved to center. It still kinda works tho.

**Steps To Reproduce**
I tried it a few time, no luck.  [So here is my save](https://www.dropbox.com/s/h67y5pfndorf288/Save%201.save?dl=0).
Also i am using transperent diving suit helmet mod, gun lights and MMDTDACharacters (don't judge).

**Pictures Of Error**
![deadreactor](https://user-images.githubusercontent.com/32136089/83978670-c140a980-a911-11ea-8d24-e0f5c83b4c9b.png)
![deadreactor2](https://user-images.githubusercontent.com/32136089/83978678-d0bff280-a911-11ea-93ac-fdcdfc656a44.png)

**Comment by Camper125Lv** [comment] 2020-06-07 20:31
Reactor is also not producing any power despite saying otherwise.

**Comment by Regalis11** [comment] 2020-06-07 20:56
Fixed in 8e0c58a

(Duplicate of a ticket we have in our private repo: https://github.com/Regalis11/Barotrauma-development/issues/1939)

**Comment by Camper125Lv** [comment] 2020-06-07 21:01
Both links are 404 but sure, ok.

**Closed** 2020-06-07 21:05 UTC
Labels: Bug, Code, Duplicate
