### ISSUE TITLE
bug when selecting campaign mission crashes the game

### ISSUE THREAD

**Issue by LUISDASARTIMANHAS** [Regalis11/Barotrauma#11281] opened 2023-02-19 13:53 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I was playing my first time and when I went to select a campaign mission it loaded but when I started the mission it simply crashed and closed the game and now whenever I do that the game crashes and exits

![image](https://user-images.githubusercontent.com/75493473/219951780-dc434c46-cbfd-426b-b528-f33a806f4089.png)
[crashreport (4).log](https://github.com/Regalis11/Barotrauma/files/10777016/crashreport.4.log)
[crashreport (3).log](https://github.com/Regalis11/Barotrauma/files/10777017/crashreport.3.log)
[servercrashreport (2).log](https://github.com/Regalis11/Barotrauma/files/10777018/servercrashreport.2.log)
[servercrashreport.log](https://github.com/Regalis11/Barotrauma/files/10777019/servercrashreport.log)
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/10777020/crashreport.2.log)
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/10777021/crashreport.log)

### Reproduction steps

1- start the game
2-I created a new game
3-I did the tutorial
4- I bought things at the store and talked to the captain
5-I selected a mission
6-locking and closing the game

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by LUISDASARTIMANHAS** [comment] 2023-02-19 13:54
this also includes servers

**Comment by Regalis11** [comment] 2023-02-19 14:03
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10540

**Closed by Regalis11** 2023-02-19 14:03 UTC

**Comment by LUISDASARTIMANHAS** [comment] 2023-02-19 17:07
the game runs smoothly
the drivers are in the latest version V12 or direct X12
GPU stress found but only on loading screens

**Comment by LUISDASARTIMANHAS** [comment] 2023-02-19 17:08
still the error cannot be resolved
