### ISSUE TITLE
[Unstable] [Modded] Game crashes if a character turns into a husk while a monster is targeting it

### ISSUE THREAD

**Issue by Emanthealmighty** [Regalis11/Barotrauma#4726] opened 2021-01-12 19:55 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When a character turns into a modded husk (even if it is a perfect unedited copy of the human husk) while it is being attacked by a monster, the game will crash.

**Steps To Reproduce**
1) Enable a mod that overrides the humanhusk
2) Spawn as a human and give yourself the husk infection affliction with enough strength to start turning you into a husk right away.
3) Spawn a monster near yourself so that it starts attacking you.
4) Wait for your death. Once you die you will turn into a husk and the game will crash.

**Version**
v0.1200.0.1 - Unstable Branch. OS: Windows 10.

**Comment by Regalis11** [comment] 2021-01-13 13:23
Could not reproduce. Tested this by creating a mod that only overrides Humanhusk with a copy of the vanilla Humanhusk files, and everything seemed to work correctly. I wonder if this could be related to the files that you use to override the character? Could you post the crash report or the files you're using?

**Comment by Emanthealmighty** [comment] 2021-01-13 14:07
[Crash report](https://github.com/Regalis11/Barotrauma/files/5809023/crashreport.109.log)

[Mod used](https://drive.google.com/drive/folders/1NuN3WUjUd7n_aXJVGQAPEqiMmf8dyMx1?usp=sharing)

When doing the same thing but with the mod disabled, the game doesn't crash.

**Comment by Regalis11** [comment] 2021-01-14 08:22
Thanks, managed to reproduce it now. Seems to be the same issue as https://github.com/Regalis11/Barotrauma/issues/4561, closing as a duplicate.

**Closed by Regalis11** 2021-01-14 08:22 UTC
Labels: Bug, Code, Crash, Modding, Need more info
