### ISSUE TITLE
Bots don't replenish Exosuit o2

### ISSUE THREAD

**Issue by ThePinkPyjama** [Regalis11/Barotrauma#10273] opened 2022-11-07 01:25 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I had a bot equip the Exosuit (super cool btw) and after a few minutes their oxygen tank ran out. Instead of swapping tanks, they complained about it until they nearly died. I was able to manually swap the tank with no issue, and I can personally use it just fine. It may also be worth noting that it consumes o2 while onboard the sub, which I assume is intentional.

### Bug prevalence

Just once

### Version

0.20.3.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-11-07 10:43
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2aa5263187367403e48b850471a2f1a1f3c3bfd1

**Comment by Rokvach** [comment] 2022-11-30 10:24
Bot doesn't place the oxygen tank to the oxygen tank slot replasing the empty one but rather just places it in the suits inventory

![image](https://user-images.githubusercontent.com/7299826/204771466-a775d317-206f-4f06-9d45-d5758dab94cb.png)

**Comment by Regalis11** [comment] 2022-11-30 14:07
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c833f3f0245b182044304a7988514bf6775f5689

**Comment by NilanthAnimosus** [comment] 2022-12-13 13:28
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/c74b9de1ded83ed269a2a470b9a849e9eda8aeaf

Tested on MP campaign with bots, singleplayer yielded the same results, for some reason I couldn't get them to actually change their tank:

Multiplayer:

![image](https://user-images.githubusercontent.com/29177976/207328145-291ea0d4-17d7-4c14-9cb9-6ab0cf37621f.png)

![image](https://user-images.githubusercontent.com/29177976/207328311-e6bd3587-290c-42bd-8462-3dffccf1d148.png)

Single player:

![image](https://user-images.githubusercontent.com/29177976/207332828-2acefc06-915d-48b3-a4f8-65b41fbe5093.png)

**Comment by Regalis11** [comment] 2022-12-13 14:02
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3db8eeab8adf6222929fede52ad3c105e2a50f86

**Comment by itchyOwl** [comment] 2022-12-13 17:54
Seems to work correctly now, but requires extensive testing on bots, and not just on diving suits, because the changes can potentially break something else.

**Comment by NilanthAnimosus** [comment] 2023-01-12 14:14
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/c74b9de1ded83ed269a2a470b9a849e9eda8aeaf

Bots using exotanks now swap tanks correctly (as well as diving suits and such) - could not find issues here.

Bots do not change the batteries on exosuits, which prevents all movement when empty now as opposed to a huge slowdown, bots have no text callout for this if empty, and even if having spare batteries do not attempt to change them stranding the AI silently (and given the speed of these suits) possibly off-camera.

However they will not pickup a diving suit to use or change tank if it is at 0%, and unless following a player with a diving suit will make no attempt to change the tank over taking the suit off once it reaches 0% on a submarine (IE. during prepare for EVA order). I am aware this is likely the mechanic to prevent suffocation from unnecessarily wearing the diving suit however they should during the prepare for EVA order prefer to change the tank and keep them replenshed.

Its  also notable if a submarine does not have wired diving suit containers, and the tanks end up empty in them (or no tank inserted) a bot will never be able to use these suits or view them as valid / recharge them and such. so something should likely be done here but not sure if it should be classed as a separate issue.

I also encountered problems with AI's not getting ammunition for their ranged weapons under find weapon, or attempting to take ranged weapons with ammo available in the submarine for empty weapons (though probably would take too much performance to check for that, so I doubt that was a bug) - I found it hard to tell if this was caused by changes from this PR or just how it always has been when double checking what I think could have been effected by these changes.

**Comment by itchyOwl** [comment] 2023-01-12 14:54
Created a separate ticket about bots not being able to change the batteries here: #10917

**Comment by itchyOwl** [comment] 2023-01-12 16:12
I don't think those findings are related to this ticket or any recent changes. Rather, it's how the AI currently works. I'll see if there's any easy ways to improve it in this regard without causing a ton of side effects.

**Comment by NilanthAnimosus** [comment] 2023-01-13 09:23
Closing as there are new tickets for the previously mentioned issues (and in the case of the find weapon mentioned issue, its just not implemented/intended for that order and could be looked into later as a new order or updating the previous, but is not actually a bug).

**Closed by NilanthAnimosus** 2023-01-13 09:23 UTC
Labels: Bug, Code, Unstable
