### ISSUE TITLE
custom beacon station bug

### ISSUE THREAD

**Issue by tiba666** [Regalis11/Barotrauma#5267] opened 2021-03-17 19:52 UTC
if you make a custom beacon station with no reactor.  the game times out when trying to start the game there no places there tell me the beacon station need a reactor .  the way i solve it atm is place an invisble reactor

![Udklip](https://user-images.githubusercontent.com/519338/111529233-30c9ac00-8762-11eb-97a9-ebe67addac13.PNG)

they why i design it was you had to recharge the battery array on the beacon staion though the docking port

step to reproduce the error make a beaconstaion with out a reactor.   

version 0.12.0.3

**Comment by Regalis11** [comment] 2021-03-18 08:24
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5ecfce228fa50ca71098d87c533c538fcc7de384

**Comment by Udrakan** [comment] 2021-04-11 13:16
Seems bugged
STR:

- Replace the default beacon with this one:
[BeaconStation1.zip](https://github.com/Regalis11/Barotrauma/files/6291834/BeaconStation1.zip)

- Start a campaign
- Start a level that has a beacon in it
- You should get this crash: 
[crashreport (165).log](https://github.com/Regalis11/Barotrauma/files/6291836/crashreport.165.log)
-Start the game again, try to load the same save, you will get a console error
![image](https://user-images.githubusercontent.com/59519434/114305560-e7f2e200-9ad8-11eb-8474-bb2b7c4ec4d7.png)

**Comment by Rokvach** [comment] 2021-04-11 13:28
Moving back to Misc

**Comment by Regalis11** [comment] 2021-04-12 08:13
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4e0ff0de0325ec69b65965cad5c5d2366ce349e1

**Comment by Rokvach** [comment] 2021-04-12 08:24
Tested by using the above provided steps. Wasn't able to reproduce, seems to be working correctly now. Closing.

**Closed by Rokvach** 2021-04-12 08:24 UTC
Labels: Bug, Code, Modding
