### ISSUE TITLE
Text SkillName.Engineer not found

### ISSUE THREAD

**Issue by Kegsey** [Regalis11/Barotrauma#7099] opened 2021-10-30 22:13 UTC
- [ X] I have searched the issue tracker to check if the issue has already been reported.

**Description**

The console keeps flashing up with the error, "Text SkillName.Engineer not found"; causing a skill called SkillName.Engineer to get points whenever any action occurs;

**Steps To Reproduce**

This bug started occurring after my mechanical engineering skill hit 100; I don't have the patience to do it again so apologies if it's not the cause.

I had the mechanic job type.

Mechanical Engineering was raised using the book which the clown drops.

**Version**

Windows

**Additional information**

It's an entirely vanilla play through.

**Comment by M61Dev** [comment] 2021-10-31 16:33
I'm unable to reproduce this

**Comment by Kegsey** [comment] 2021-11-01 18:57
This happened in Multiplayer as a mechanic;
As I previously stated it happened as soon as I hit level 100 in the mechanics skill.

Whenever I raise ANY level it pops up with said message in the console, "Text SkillName.Engineer not found"; it also does it each time I hit an enemy as well.

Would getting the save file or any file from the game help?

We've two other people with 100 mechanic skill and the issue is only unique with me levelling up.

**Comment by Kegsey** [comment] 2021-11-01 19:08
Okay so after reading the logs it seem like a couple of people have a unique skill called "engineering" in the logs here.

-<Character name="Cain" missionscompletedsincedeath="0" personality="Broken English" ragdoll="" startitemsgiven="false" facialhaircolor="199,125,82,255" haircolor="161,88,55,255" skincolor="252,225,198,255" faceattachmentindex="0" moustacheindex="0" beardindex="0" hairindex="6" headspriteid="7" additionaltalentpoints="0" unlockedtalents="tinkerer,scrounger,miner,cannedheat,safetyfirst,hullfixer,pyromaniac" experiencepoints="14136" salary="2969" race="None" gender="Male" speciesname="human" originalname="Cain">


-<job name="Mechanic" identifier="mechanic">

<skill identifier="mechanical" level="100"/>

<skill identifier="electrical" level="78.850525"/>

<skill identifier="weapons" level="43.54378"/>

<skill identifier="medical" level="33.450405"/>

<skill identifier="helm" level="21.727182"/>

**<skill identifier="engineering" level="10"/>**

</job>

I have emboldened the error that isn't meant to be there.

**Comment by Kegsey** [comment] 2021-11-01 19:10
I'm sure someone with a tech savvy brain will be able to figure out what's happening here

**Comment by Kegsey** [comment] 2021-11-02 00:34
Just another note, sorry if this gives you hella notifications;

The problem ceased to exist by removing the "engineering" row and reloading the save; though weirdly enough for a single round afterwards we had issues repairing any and all electronics and mechanisms on the shuttle, but it may be unrelated as we had just upgraded the ship too.

**Comment by Regalis11** [comment] 2021-11-02 09:22
I found one issue that could've potentially caused this: the "bomb scare" outpost event gave the characters "engineering" xp, when it should've been "electrical". However, the error message caused by that was "Text SkillName.Engineering not found", not "Text SkillName.Engineer not found".

Potentially fixed in https://github.com/Regalis11/Barotrauma-development/commit/e4d3e54c8cada8dd1aaa462863e081a33e3e19c1

**Comment by Rokvach** [comment] 2021-11-02 10:19
Tested, no issues. Closing.

**Closed by Rokvach** 2021-11-02 10:19 UTC
Labels: Bug, Code
