### ISSUE TITLE
Circuit signal models do not update on wire/signal removal

### ISSUE THREAD

**Issue by CatchFire1101** [Regalis11/Barotrauma#1668] opened 2019-06-17 18:38 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Circuit models, including power signals, numeric signals, and color array signals are not updated on wire removal or signal loss through relay opening.  Seems current mechanic is for signal input lines to "float" at last input until updated by new active signal.

**Steps To Reproduce**
To demonstrate with power signals directly:
1) Wire a lamp component power pin to an active power source.
2) Wire lamp component toggle_state to a button.  Turn on the lamp with button.
3) Remove the power wire from the lamp.  Lamp will remain illuminated even though no power source.

To demonstrate with power signals through relay:
1) Wire a relay signal_in_1 pin to an active power source.  Power the relay power pin.
2) Wire a button (button1) to relay toggle_state pin.
3) Wire a relay signal_out_1 to a lamp power pin.
4) Wire lamp component toggle_state to a button (button2).  Turn on the lamp with button2.
5) Press button1 to close relay and connect power source to lamp.  Lamp will illuminate.
6) Press button1 to open relay and disconnect power source to lamp.  Lamp will remain illuminated even though no power source.

The same persistence of signals through removed connections can be demonstrated for numeric and color array signals in similar fashion.

**Version**
v0.9.0.6
Windows

**Additional information**
While numeric and color array signal persistence on signal loss is less obviously logically inconsistent, it does create some odd scenarios.

For example, if a mem component signal_store pin is enabled with a logical 1, but that logical 1 signal is then removed via relay or physical wire removal, the mem component will continue to store new data even through the signal_store pin is floating (undriven).

If the numeric/color array signal persistence is a design decision and not to be changed, I would kindly request a double-pole, double-throw (DPDT) relay configuration in reverse polarity (selector).  This would allow players to easily drive signals between two values (turn things on/off with relays, make flashing lights by selecting between two color arrays with an oscillator, and many other applications).

I have attached a diagram of DPDT relay for reference.  If you consider adding it, a pre-emptive thanks!

![DPDT](https://user-images.githubusercontent.com/51864763/59627745-33662000-90fc-11e9-881f-92839a59f330.png)

**Comment by Regalis11** [comment] 2019-06-18 13:20
I unfortunately wasn't able to reproduce this (see https://youtu.be/SXDnfZSFZDA). Does it happen in multiplayer, single player or both?

**Comment by CatchFire1101** [comment] 2019-06-18 14:14
Interesting.  It appears to only have this behavior if you use a junction box to distribute power, and power signals update correctly if wired directly to a power source (battery/shuttlebattery).

The difference between my setup and yours is my power distribution test setup is shuttle battery->junctionbox->lamp.  I was able to recreate this phenomenon using a junction box to distribute power, both in sandbox on a local server and campaign (single player both).

**Comment by Regalis11** [comment] 2019-09-16 14:51
I'm sorry but I still haven't been able to reproduce this. Even if I add a junction box between the battery and the lamp, the lamp goes dark as soon as the power wire is disconnected.

I wasn't able to reproduce the relay issue either. With your setup the lamp does not turn on in the first place, because the signal connections don't pass power through. When I instead connect the lamp to the power_out connection of the relay, it seems to work as expected: the lamp turns off as soon as the relay is opened (or the power source disconnected).

I may be misunderstanding your setup somehow, but with this information I'm afraid I can't reproduce the problem. Please let me know if you have any further details that might help us diagnosing it (e.g. a short video clip or a submarine file showing the setup). I'll close this for now, but I'll reopen it if we manage to find a way to reproduce the bug.

**Closed by Regalis11** 2019-09-16 14:51 UTC
Labels: Bug, Code
