### ISSUE TITLE
A Locked Connection Was Selected

### ISSUE THREAD

**Issue by cshingle** [Regalis11/Barotrauma#8988] opened 2022-04-26 23:10 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.
This old issue seems to have a similar stack trace, but they where using mods. The server I was on had no mods, just a custom sub.
#5949

**Description**
I got the attached console errors when the game round started. The new round loaded fine and nothing obvious broke. Other people on the server didn't get this error.
![20220426172444_1](https://user-images.githubusercontent.com/2231937/165407000-d50fd98e-8650-473b-91aa-3a5ae2c81d2b.jpg)
![20220426172446_1](https://user-images.githubusercontent.com/2231937/165407005-8e9f53f5-ee2c-4138-a1af-53cc8c61db86.jpg)

**Steps To Reproduce**
I don't know how repeatable this is. I had just joined @Kaileris's server and waited for him to start the round.

**Version**
V0.17.14.0 Linux (new unstable)

**Additional information**

**Comment by JamesTheAwesomeDude** [comment] 2022-04-27 05:15
Can you upload a copy of the affected submarine? It _looks like_ an issue with the sub, though (per the other issues' suggestion that it could be to do with changing biomes) if you can **replicate it with a vanilla sub and then upload the savefile** that'd be even better.

(ZIP it first otherwise Github will reject the attachment)

**Comment by Regalis11** [comment] 2022-04-27 15:31
Duplicate of https://github.com/Regalis11/Barotrauma/issues/5949

**Closed by Regalis11** 2022-04-27 15:31 UTC
