### ISSUE TITLE
Research stations in bandit outposts

### ISSUE THREAD

**Issue by Rparvitn** [Regalis11/Barotrauma#12046] opened 2023-05-21 17:42 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I tried to research Unidentified Genetic Material at pirate outpost, but there was no wire in it. I connected it to junction box connected to outpost reactor. After repairing everything this was the only box that looked still damaged, but it was impossible to fix it. Also the gene research station did not require repair, but wasn't repaired before. Reactor load was at 1 KW, and gene research station haven't worked.

### Reproduction steps

1.Start a campaing
2.Try to use gene research station on pirate outpost

### Bug prevalence

Just once

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-05-22 17:36
Thank you for the report!

I unfortunately could not find a way to reproduce the issue. I tested repairing the power grid and the reactor in an abandoned outpost, and was able to use the research station.

![image](https://github.com/Regalis11/Barotrauma/assets/14351070/704af326-aaa4-4a62-8854-047f492be6a1)

I would suspect there was still a broken junction box or missing wiring somewhere. If you have the level seed or a save file where this occurs, we could give it a test and see if we can figure out where the issue is. Sorry for the inconvenience!

**Comment by Regalis11** [comment] 2023-05-24 09:57
Thank you for the extra info, I got the issue to occur now. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8b8464d73d6326e480a8115f9c2550c71a9a804b (commit in our private repository)

**Comment by Jasontti** [comment] 2023-06-09 13:18
Tested and research table works now abandoned outpost.
Closing ticket.

**Closed by Jasontti** 2023-06-09 13:18 UTC
Labels: Bug, Low prio
