### ISSUE TITLE
Can't use tools on MAC

### ISSUE THREAD

**Issue by Lutschfruchtbonbon** [Regalis11/Barotrauma#3468] opened 2020-08-02 19:10 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
No way hat I configure in the settings, I'm not able to use tools (eg. the welding tool in the tutorial)

**Steps To Reproduce**
using the oxygen mask and the welding tool in the tutorial, swimming to the hull breach, aiming to the breach, then trying to use the welding tool - nothing happens, neither with the new control setting, nor with the legacy control setting.

**Version**
Steam v0.10.4.0 Mac OS 10.15.5

**Additional information**
by now, unable to do anything in the game.

**Comment by Regalis11** [comment] 2020-08-17 07:24
Just to make sure, are you aware that you need to hold the aim key (RMB by default) while pressing LMB? Does anything happen when you try to aim? What kind of a mouse are you using?

**Comment by Regalis11** [comment] 2020-09-15 09:45
I'm afraid there's not much we can do about this without further info, closing.

**Comment by aantn** [comment] 2021-08-08 18:22
I have the same issue. The problem is that Macbooks have only a single button on the trackpad and right clicks are simulated by clicking with two fingers at the same time. Therefore right clicking and left clicking simultaneously isn't possible.

**Comment by aantn** [comment] 2021-08-09 05:49
I've mapped one of the clicks to CAPS LOCK to work around this. In short, this is solvable with better defaults on Macbooks.

**Closed** 2022-06-16 11:53 UTC
Labels: Bug, Code, Mac only
