### ISSUE TITLE
[Factions] Throwing anything that splats crashes the game

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10926] opened 2023-01-13 20:53 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Throwing any splattering item (pomegrenade, green and blue paint) crashes the game.

### Reproduction steps

1. Get green or blue paint
2. Throw green paint
3. Game crashes

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 01/13/2023 20:48:05)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

F2A4E9FB5834DDC5D686B6501AEF0813

Game version 100.13.0.0 (UnstableWindows, branch feature/fullrelease-testing, revision ca43dc3c6d)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla, Fury, LETOHSS, Rex Malleus-Caput, SS HOTEL V.2, STVR, The Honked Mother, Typhon3, RVTS-Class, Sirens Violin, Sailor 4, The Schism, Mazara, Tadpole Trader, Medusa, [RH] Barrisk Campaign, [RH] Bivot Tier 3 Campaign
Level seed: Nome75
Loaded submarine: Barsuk (1FFEC558B440675312287B00F5F0AECA)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)

System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit
    GPU name: NVIDIA GeForce RTX 2070
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Pipe is broken. (System.IO.IOException)
Target site: Void WriteCore(System.ReadOnlySpan`1[System.Byte])
Stack trace: 
   at System.IO.Pipes.PipeStream.WriteCore(ReadOnlySpan`1 buffer)
   at Barotrauma.Networking.ChildServerRelay.<UpdateWrite>g__writeMsg|44_0(WriteStatus writeStatus, Byte[] msg) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 265
   at Barotrauma.Networking.ChildServerRelay.UpdateWrite() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 281


Last debug messages:
[01/13/2023 20:39:59] Asriel
[01/13/2023 20:39:59] CaithLoki
[01/13/2023 20:39:59] fent
[01/13/2023 20:39:59] Rehex
[01/13/2023 20:39:59] Vyk
[01/13/2023 20:39:59] Hawkins
[01/13/2023 20:39:59] Gears
[01/13/2023 20:39:59] hUbert
[01/13/2023 20:39:59] Jade Harley
[01/13/2023 20:39:59] bain
[01/13/2023 20:39:59] 3e849f2e5c
[01/13/2023 20:39:59] Skyline_Robot
[01/13/2023 20:39:59] Wheatley1001
[01/13/2023 20:39:58] Asriel
[01/13/2023 20:39:58] CaithLoki
[01/13/2023 20:39:58] fent
[01/13/2023 20:39:58] Rehex
[01/13/2023 20:39:58] Vyk
[01/13/2023 20:39:58] Hawkins
[01/13/2023 20:39:58] Gears
[01/13/2023 20:39:58] hUbert
[01/13/2023 20:39:58] Jade Harley
[01/13/2023 20:39:58] bain
[01/13/2023 20:39:58] 3e849f2e5c
[01/13/2023 20:39:58] Skyline_Robot
[01/13/2023 20:39:58] Wheatley1001
[01/13/2023 20:39:57] Asriel
[01/13/2023 20:39:57] CaithLoki
[01/13/2023 20:39:57] fent
[01/13/2023 20:39:57] Rehex
[01/13/2023 20:39:57] Vyk
[01/13/2023 20:39:57] Hawkins
[01/13/2023 20:39:57] Gears
[01/13/2023 20:39:57] hUbert
[01/13/2023 20:39:57] Jade Harley
[01/13/2023 20:39:57] bain
[01/13/2023 20:39:57] 3e849f2e5c
[01/13/2023 20:39:57] Skyline_Robot
[01/13/2023 20:39:57] Wheatley1001
[01/13/2023 20:39:56] Asriel
[01/13/2023 20:39:56] CaithLoki
[01/13/2023 20:39:56] fent
[01/13/2023 20:39:56] Rehex
[01/13/2023 20:39:56] Vyk
[01/13/2023 20:39:56] Hawkins
[01/13/2023 20:39:56] Gears
[01/13/2023 20:39:56] hUbert
[01/13/2023 20:39:56] Jade Harley
[01/13/2023 20:39:56] bain
[01/13/2023 20:39:56] 3e849f2e5c
[01/13/2023 20:39:56] Skyline_Robot
[01/13/2023 20:39:56] Wheatley1001
[01/13/2023 20:39:56] Asriel
[01/13/2023 20:39:55] Rehex
[01/13/2023 20:39:55] Vyk
[01/13/2023 20:39:55] Hawkins
[01/13/2023 20:39:55] Gears
[01/13/2023 20:39:55] hUbert
[01/13/2023 20:39:55] Jade Harley
[01/13/2023 20:39:55] bain
[01/13/2023 20:39:55] 3e849f2e5c
[01/13/2023 20:39:55] Skyline_Robot
[01/13/2023 20:39:55] Wheatley1001
[01/13/2023 20:39:55] Jade Harley
[01/13/2023 20:39:55] bain
[01/13/2023 20:39:55] 3e849f2e5c
[01/13/2023 20:39:55] Skyline_Robot
[01/13/2023 20:39:55] Wheatley1001
[01/13/2023 20:39:52] Received STARTGAMEFINALIZE packet. Round init status: Started
[01/13/2023 20:39:52] Task count: 0
[01/13/2023 20:39:52] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[01/13/2023 20:39:50] Generating an outpost for the start of the level... (Location: Nome, level type: Outpost)
[01/13/2023 20:39:50] Level identifier: outpostlevel
[01/13/2023 20:39:41] Asriel
[01/13/2023 20:39:41] CaithLoki
[01/13/2023 20:39:41] fent
[01/13/2023 20:39:41] Rehex
[01/13/2023 20:39:41] Vyk
[01/13/2023 20:39:41] Hawkins
[01/13/2023 20:39:41] Gears
[01/13/2023 20:39:41] hUbert
[01/13/2023 20:39:41] Jade Harley
[01/13/2023 20:39:41] bain
[01/13/2023 20:39:41] 3e849f2e5c
[01/13/2023 20:39:41] Skyline_Robot
[01/13/2023 20:39:41] Wheatley1001
[01/13/2023 20:39:40] Asriel
[01/13/2023 20:39:40] CaithLoki
[01/13/2023 20:39:40] fent
[01/13/2023 20:39:40] Vyk
[01/13/2023 20:39:40] Hawkins
[01/13/2023 20:39:40] Gears
[01/13/2023 20:39:40] hUbert
[01/13/2023 20:39:40] Jade Harley
[01/13/2023 20:39:40] bain
[01/13/2023 20:39:40] 3e849f2e5c
[01/13/2023 20:39:40] Skyline_Robot
[01/13/2023 20:39:40] Wheatley1001
[01/13/2023 20:39:40] Rehex
[01/13/2023 20:39:40] Asriel
[01/13/2023 20:39:40] CaithLoki
[01/13/2023 20:39:40] fent
[01/13/2023 20:39:40] Vyk
[01/13/2023 20:39:40] Hawkins
[01/13/2023 20:39:40] Gears
[01/13/2023 20:39:40] hUbert
[01/13/2023 20:39:40] Jade Harley
[01/13/2023 20:39:40] bain
[01/13/2023 20:39:40] 3e849f2e5c
[01/13/2023 20:39:40] Skyline_Robot
[01/13/2023 20:39:40] Wheatley1001
[01/13/2023 20:39:40] Rehex
[01/13/2023 20:39:40] Asriel
[01/13/2023 20:39:40] CaithLoki
[01/13/2023 20:39:40] fent
[01/13/2023 20:39:40] Rehex
[01/13/2023 20:39:40] Vyk
[01/13/2023 20:39:40] Hawkins
[01/13/2023 20:39:40] Gears
[01/13/2023 20:39:40] hUbert
[01/13/2023 20:39:40] Jade Harley
[01/13/2023 20:39:40] bain
[01/13/2023 20:39:40] 3e849f2e5c
[01/13/2023 20:39:40] Skyline_Robot
[01/13/2023 20:39:40] Wheatley1001
[01/13/2023 20:39:40] Asriel
[01/13/2023 20:39:40] CaithLoki
[01/13/2023 20:39:40] fent
[01/13/2023 20:39:40] Rehex
[01/13/2023 20:39:40] Vyk
[01/13/2023 20:39:40] Hawkins
[01/13/2023 20:39:40] Gears
[01/13/2023 20:39:40] hUbert
[01/13/2023 20:39:40] Jade Harley
[01/13/2023 20:39:40] bain
[01/13/2023 20:39:40] 3e849f2e5c
[01/13/2023 20:39:40] Skyline_Robot
[01/13/2023 20:39:40] Wheatley1001
[01/13/2023 20:39:40] Asriel
[01/13/2023 20:39:40] CaithLoki
[01/13/2023 20:39:40] fent
[01/13/2023 20:39:40] Rehex
[01/13/2023 20:39:40] Vyk
[01/13/2023 20:39:40] Hawkins
[01/13/2023 20:39:40] Gears
[01/13/2023 20:39:40] hUbert
[01/13/2023 20:39:40] Jade Harley
[01/13/2023 20:39:40] bain
[01/13/2023 20:39:40] 3e849f2e5c
[01/13/2023 20:39:40] Skyline_Robot
[01/13/2023 20:39:40] Wheatley1001
[01/13/2023 20:39:40] Asriel
[01/13/2023 20:39:40] CaithLoki
[01/13/2023 20:39:40] fent
[01/13/2023 20:39:40] Rehex
[01/13/2023 20:39:40] Vyk
[01/13/2023 20:39:40] Hawkins
[01/13/2023 20:39:40] Gears
[01/13/2023 20:39:40] hUbert
[01/13/2023 20:39:40] Jade Harley
[01/13/2023 20:39:40] bain
[01/13/2023 20:39:40] 3e849f2e5c
[01/13/2023 20:39:40] Skyline_Robot
[01/13/2023 20:39:40] Wheatley1001
[01/13/2023 20:39:39] Asriel
[01/13/2023 20:39:39] CaithLoki
[01/13/2023 20:39:39] fent
[01/13/2023 20:39:39] Rehex
[01/13/2023 20:39:39] Vyk
[01/13/2023 20:39:39] Hawkins
[01/13/2023 20:39:39] Gears
[01/13/2023 20:39:39] hUbert
[01/13/2023 20:39:39] Jade Harley
[01/13/2023 20:39:39] bain
[01/13/2023 20:39:39] 3e849f2e5c
[01/13/2023 20:39:39] Skyline_Robot
[01/13/2023 20:39:39] Wheatley1001
[01/13/2023 20:39:39] Asriel
[01/13/2023 20:39:39] CaithLoki
[01/13/2023 20:39:39] fent
[01/13/2023 20:39:39] Rehex
[01/13/2023 20:39:39] Vyk
[01/13/2023 20:39:39] Hawkins
[01/13/2023 20:39:39] Gears
[01/13/2023 20:39:39] hUbert
[01/13/2023 20:39:39] Jade Harley
[01/13/2023 20:39:39] bain
[01/13/2023 20:39:39] 3e849f2e5c
[01/13/2023 20:39:39] Skyline_Robot
[01/13/2023 20:39:39] Wheatley1001
[01/13/2023 20:39:38] Asriel
[01/13/2023 20:39:38] CaithLoki
[01/13/2023 20:39:38] fent
[01/13/2023 20:39:38] Rehex
[01/13/2023 20:39:38] Vyk
[01/13/2023 20:39:38] Hawkins
[01/13/2023 20:39:38] Gears
[01/13/2023 20:39:38] hUbert
[01/13/2023 20:39:38] Jade Harley
[01/13/2023 20:39:38] bain
[01/13/2023 20:39:38] 3e849f2e5c
[01/13/2023 20:39:38] Skyline_Robot
[01/13/2023 20:39:38] Wheatley1001
[01/13/2023 20:39:38] Asriel
[01/13/2023 20:39:38] CaithLoki
[01/13/2023 20:39:38] fent
[01/13/2023 20:39:38] Rehex
[01/13/2023 20:39:38] Vyk
[01/13/2023 20:39:38] Hawkins
[01/13/2023 20:39:38] Gears
[01/13/2023 20:39:38] hUbert
[01/13/2023 20:39:38] Jade Harley
[01/13/2023 20:39:38] bain
[01/13/2023 20:39:38] 3e849f2e5c
[01/13/2023 20:39:38] Skyline_Robot
[01/13/2023 20:39:38] Wheatley1001
[01/13/2023 20:27:32] WARNING: Received a potentially invalid ENTITY_POSITION message.Entity identifier does not match (server entity is smallcrawleregg, client entity is pulselaserbolt). Ignoring the message...
[01/13/2023 20:21:28] Asriel
[01/13/2023 20:21:28] CaithLoki
[01/13/2023 20:21:28] fent
[01/13/2023 20:21:28] Rehex
[01/13/2023 20:21:28] Vyk
[01/13/2023 20:21:28] Hawkins
[01/13/2023 20:21:28] Gears
[01/13/2023 20:21:28] hUbert
[01/13/2023 20:21:28] Jade Harley
[01/13/2023 20:21:28] bain
[01/13/2023 20:21:28] 3e849f2e5c
[01/13/2023 20:21:28] Skyline_Robot
[01/13/2023 20:21:28] Wheatley1001
[01/13/2023 20:14:17] Asriel
[01/13/2023 20:14:17] CaithLoki
[01/13/2023 20:14:17] fent
[01/13/2023 20:14:17] Rehex
[01/13/2023 20:14:17] Vyk
[01/13/2023 20:14:17] Hawkins
[01/13/2023 20:14:17] Gears
[01/13/2023 20:14:17] hUbert
[01/13/2023 20:14:17] LazyTurtle
[01/13/2023 20:14:17] Jade Harley
[01/13/2023 20:14:17] bain
[01/13/2023 20:14:17] 3e849f2e5c
[01/13/2023 20:14:17] Skyline_Robot
[01/13/2023 20:14:17] Wheatley1001
[01/13/2023 20:14:17] Asriel
[01/13/2023 20:14:17] CaithLoki
[01/13/2023 20:14:17] fent
[01/13/2023 20:14:17] Rehex
[01/13/2023 20:14:17] Vyk
[01/13/2023 20:14:17] Hawkins
[01/13/2023 20:14:17] Gears
[01/13/2023 20:14:17] hUbert
[01/13/2023 20:14:17] LazyTurtle
[01/13/2023 20:14:17] Jade Harley
[01/13/2023 20:14:17] bain
[01/13/2023 20:14:17] 3e849f2e5c
[01/13/2023 20:14:17] Skyline_Robot
[01/13/2023 20:14:17] Wheatley1001
[01/13/2023 20:14:16] Asriel
[01/13/2023 20:14:16] CaithLoki
[01/13/2023 20:14:16] fent
[01/13/2023 20:14:16] Rehex
[01/13/2023 20:14:16] Vyk
[01/13/2023 20:14:16] Hawkins
[01/13/2023 20:14:16] Gears
[01/13/2023 20:14:16] hUbert
[01/13/2023 20:14:16] LazyTurtle
[01/13/2023 20:14:16] Jade Harley
[01/13/2023 20:14:16] bain
[01/13/2023 20:14:16] 3e849f2e5c
[01/13/2023 20:14:16] Skyline_Robot
[01/13/2023 20:14:16] Wheatley1001
[01/13/2023 20:14:15] Server running slowly (57 updates/s)!
[01/13/2023 20:14:14] Asriel
[01/13/2023 20:14:14] CaithLoki
[01/13/2023 20:14:14] fent
[01/13/2023 20:14:14] Rehex
[01/13/2023 20:14:14] Vyk
[01/13/2023 20:14:14] Hawkins
[01/13/2023 20:14:14] Gears
[01/13/2023 20:14:14] hUbert
[01/13/2023 20:14:14] LazyTurtle
[01/13/2023 20:14:14] Jade Harley
[01/13/2023 20:14:14] bain
[01/13/2023 20:14:14] 3e849f2e5c
[01/13/2023 20:14:14] Skyline_Robot
[01/13/2023 20:14:14] Wheatley1001
[01/13/2023 20:14:14] Asriel
[01/13/2023 20:14:14] CaithLoki
[01/13/2023 20:14:14] fent
[01/13/2023 20:14:14] Rehex
[01/13/2023 20:14:14] Vyk
[01/13/2023 20:14:14] Hawkins
[01/13/2023 20:14:14] Gears
[01/13/2023 20:14:14] hUbert
[01/13/2023 20:14:14] LazyTurtle
[01/13/2023 20:14:14] Jade Harley
[01/13/2023 20:14:14] bain
[01/13/2023 20:14:14] 3e849f2e5c
[01/13/2023 20:14:14] Skyline_Robot
```

**Comment by Regalis11** [comment] 2023-01-14 10:30
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10902

**Closed by Regalis11** 2023-01-14 10:31 UTC
Labels: Bug, Code, Crash
