### ISSUE TITLE
Changelog messed up after switching resolution

### ISSUE THREAD

**Issue by JoneKone** [Regalis11/Barotrauma#4008] opened 2020-10-05 11:10 UTC
ChangeLog on 1440p monitor seems to mess up.
![Screenshot from 2020-10-05 14-08-44](https://user-images.githubusercontent.com/1114115/95072820-79416000-0714-11eb-9362-6662d0e32d86.png)

**Comment by someone972** [comment] 2020-10-05 13:18
Interestingly, on my 1440p monitor this is displaying properly. Was there anything you did to get it to show up like that, or does it show up immediately after starting the game?

![image](https://user-images.githubusercontent.com/1829181/95084183-c274be00-06da-11eb-8caf-ae1d65c71407.png)

**Comment by someone972** [comment] 2020-10-06 05:22
For what it's worth, I tested this on Ubuntu 20.04 and was unable to reproduce. My friend was also unable to reproduce on his linux box. Not sure what is different between mine and JoneKone.

**Comment by JoneKone** [comment] 2020-10-06 09:36
Maybe it's related to the issue when I have to change my resolution after the game start's in 1080p on another screen and i have to go windowed to get it to 1440p and then back to borderless windowed, so it works proper.

**Comment by someone972** [comment] 2020-10-06 15:12
Ah, yeah. That's the bit that I was missing. I'm now able to reproduce this, seems the changelog only gets built once and doesn't update when you change the resolution.

**Comment by Regalis11** [comment] 2020-10-27 09:41
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/103cf54d3d2188732797be6c660094f4798843d1

**Comment by Rokvach** [comment] 2020-10-27 10:14
Tested, working correctly. Closing.

**Closed by Rokvach** 2020-10-27 10:14 UTC
Labels: Bug, Code, Low prio

**Comment by JoneKone** [comment] 2020-11-03 04:51
Ok i'm hesitant to reopen this, but it's not working on latest steam build. Also i don't see the commit, it seems to 404 on me. Soo I can't really test it.
![Screenshot from 2020-11-03 06-44-45](https://user-images.githubusercontent.com/1114115/97950848-e3473680-1da0-11eb-8cee-596f6b5bf409.png)
