### ISSUE TITLE
Paint, blood and damage decals after removal with cleaner are restored in campaign mode on the next round

### ISSUE THREAD

**Issue by Arthuriada** [Regalis11/Barotrauma#3936] opened 2020-09-28 08:54 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.
Familliar issue #3853 been closed

**Description**
Paint, blood and damage decals after removal with cleaner are restored in campaign mode on the next round. Cleaner makes them transparent, but next round they all are back and full opaque.

**Steps To Reproduce**
Start new multiplayer campaign on Dugong
Throw pain on doors
Clean it
Undock
Decals stay where they have been

**Version**
Windows 10. Ver 0.10.5.1

**Comment by Arthuriada** [comment] 2020-09-28 08:56
You can clean rhem again, and dock the station. Decals would be restored again.

As an override solution, is there some way to remove these decals totally?

**Comment by Regalis11** [comment] 2020-09-28 09:54
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a88de87f92eaf221d88a312fc0cad7ea78117b45. The problem was that the decals would revert back to full opacity when saving and reloading the sub. However, if you fully clean them (i.e. keep cleaning until they disappear completely), they should stay gone.

**Comment by Arthuriada** [comment] 2020-09-28 10:52
Just tested, cannot confirm that. Used 2 packs of ethanol.

Screenshot and savegame files attached. Blood and explosion sprite stays.

![20200928134221_1](https://user-images.githubusercontent.com/72010768/94423537-76cd8c00-0191-11eb-80b6-36e0e81d2ea0.jpg)

[Артуриада.zip](https://github.com/Regalis11/Barotrauma/files/5291686/default.zip)

**Comment by Rokvach** [comment] 2020-10-08 10:03
I was still able to reproduce this in the latest Unstable build

Steps I used: 
1. Start a multiplayer campaign
2. Spawn in a pomegranade
3. Throw it
4. Clean the decal
5. Undock from outpost
6. Notice that the decal is still there

**Comment by Regalis11** [comment] 2020-10-08 14:28
Looks like decal syncing was still broken in multiplayer: the decals would only be cleaned client-side, so when the round ended and the server saved the sub, they'd reappear because they've never been cleaned server-side.

Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e71039fadd8f4c4c6d190cb155d9fc8e24057817

**Comment by Rokvach** [comment] 2020-10-09 11:09
Tested, wasn't able to reproduce the issue, seems to be working correctly. Closing.

**Closed by Rokvach** 2020-10-09 11:09 UTC
Labels: Bug, Code, Networking
