### ISSUE TITLE
[Factions] Multiple heart of gold events at abandoned outpost

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10365] opened 2022-11-12 22:31 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

After coming upon an abandoned outpost, ive found multiple of the heart of gold events, although it seems that going through one seems to have broken the other, leaving the other passive npc to just stand around without being interactible. Might be a result of the currently broken events. (In this image there is one of the event characters dead on the ground, plus the other one which i discovered afterwards)
![image](https://user-images.githubusercontent.com/104232152/201497145-55ec18bb-1f72-4ade-8246-d79b3bef6246.png)

### Reproduction steps

1.Try coming upon a pirate outpost until the event may happen multiple times at once.

### Bug prevalence

Happens every now and then

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by BiffW** [comment] 2022-11-13 00:24
Same with Aunt Doris. I met her in a colony and another her showed up. I recruited them and now I have 2 Aunt Doris in my crew.

**Comment by Regalis11** [comment] 2022-11-13 10:59
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10320

**Closed by Regalis11** 2022-11-13 10:59 UTC
