### ISSUE TITLE
[0.10.6.2] Crash to Desktop in MP Campaign

### ISSUE THREAD

**Issue by derpmcgerp1080p** [Regalis11/Barotrauma#4176] opened 2020-10-31 02:15 UTC
Description
When playing the campaign in MP, the game will C2D randomly. 

Steps To Reproduce
Unsure. Seems to happen randomly. Happened first when stealing an Egg from a research station. Second time, toolkit was stolen from a trashcan.

Version
v.0.10.6.2

Operating System
Windows

Bug Report
Attached
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/5468395/crashreport.2.log)

**Comment by Regalis11** [comment] 2020-11-02 11:19
I suspect this was caused by a disconnect when the store view was open. The disconnect probably occurred because the server crashed due to Regalis11/Barotrauma#4125. Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/d53ba81b74fedb756354e3d03729f157c03bfc19

**Comment by Rokvach** [comment] 2020-11-04 10:22
No issues, closing.

**Closed by Rokvach** 2020-11-04 10:22 UTC
Labels: Bug, Code, Crash
