### ISSUE TITLE
Players with the same IP change characters when one disconnects

### ISSUE THREAD

**Issue by illsurvive5** [Regalis11/Barotrauma#5405] opened 2021-04-01 01:40 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
An issue that I haven't been able to find anything on yet. We have two players in our Multiplayer campaign that live together and have the same IP endpoint. They can both join the game fine and play without issue. We will refer to them as player1 and player2 for simplicity. 
When they are both in the game and player2 leaves the game, player1 takes over player2's character and player1's character just stops moving. We exited to the lobby and checked the character's data in the CampaignName_CharacterData.xml and it seems that player2's data overwrote player1's. We have been able to reproduce this consistently by having the two players with the same IP in the same campaign and having one of them leave. The two players who experienced this are on the Windows version of the game purchased via steam. The server is running Ubuntu 18.04 using linux game server. The only work around we have found is killing one of the players before they leave.  

**Steps To Reproduce**
Have two players with the same IP endpoint be in a game. Have one of those player disconnect.
**Version**
Players: Windows v0.12.0.3 | Windows 10
Server: LinuxGSM - Barotrauma - Version v21.2.2 | Ubuntu 18.04

**Additional information**
Our only work around has been to execute one of the players before they disconnect. This has been detrimental to crew moral.

**Comment by Rokvach** [comment] 2021-04-01 07:31
Easy to repro by just trying to play multiplayer campaign with two clients

**Comment by Regalis11** [comment] 2021-11-16 13:03
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/709359151a7314435f53c47cd918562dc770188f

**Comment by Regalis11** [comment] 2021-11-16 13:03
Actually, this seems to be a duplicate of https://github.com/Regalis11/Barotrauma/issues/4798, closing

**Closed by Regalis11** 2021-11-16 13:03 UTC
Labels: Bug, Code, Networking
