### ISSUE TITLE
Cannot "examine" research station and research table

### ISSUE THREAD

**Issue by Hinny** [Regalis11/Barotrauma#8068] opened 2022-01-20 15:43 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I cannot examine research station and research table with (!) in research outpost in single player campaign.

I believe this behavior is unintentional. If it is intentional (for instance, I don't meet a specific criteria) I think it is confusing to not get any feedback at all.

I have come across this twice in my single player campaign.

**Steps To Reproduce**
1. Travel to research outpost
2. Walk to research station or research table with a (!)
3. Try to interact with them. Neither use, aim or select does anything.

**Version**
v 0.15.23.0 Windows PC

**Additional information**
I have remapped my keyboard controls

![image](https://user-images.githubusercontent.com/7380773/150371090-dd90fda4-6b36-4a1c-9d77-c90f7ffcb82d.png)
![image](https://user-images.githubusercontent.com/7380773/150371112-1295c351-26b3-4d90-9dd5-e7a019292da3.png)

**Comment by Regalis11** [comment] 2022-01-21 07:48
Thank you for the report! I'm afraid I couldn't reproduce this though, examining seems to work correctly even if I rebind it to Enter. 
![image](https://user-images.githubusercontent.com/14351070/150487093-88818a3a-7ab9-4f11-95a8-cb6176bf677f.png)

This might be a long shot, but could you send a screenshot of your keybinds? I'm wondering if some other keybind could be interfering with this action somehow.

**Comment by Hinny** [comment] 2022-01-21 13:57
![image](https://user-images.githubusercontent.com/7380773/150539219-a0c2e716-e723-49e4-b7b4-f0f7b9e3cb66.png)
![image](https://user-images.githubusercontent.com/7380773/150539233-15928f36-ed30-4678-bdfb-d2b4ca6955e4.png)

I got a new event that I couldn't interact with
![image](https://user-images.githubusercontent.com/7380773/150539289-888aface-12b0-4efe-8df3-12ced7c15cb8.png)

**Comment by Hinny** [comment] 2022-01-27 22:30
Encountered the same problem again later in the same campaign
![image](https://user-images.githubusercontent.com/7380773/151454337-5ad4d718-af9a-41d5-a839-e404b67e144a.png)

**Comment by Regalis11** [comment] 2022-02-04 10:13
Hmm, I'm sorry to say but I still had no luck in reproducing this, even after setting my keybinds to match yours exactly. :/ But we'll keep an eye out for this and hope we can find a way to get this to occur.

![image](https://user-images.githubusercontent.com/14351070/152511528-3d52f988-c9f0-4309-992f-388f3e508a3e.png)

**Comment by Regalis11** [comment] 2022-05-17 07:15
Steps to repro in https://github.com/regalis11/barotrauma/issues/9152

**Comment by Regalis11** [comment] 2022-05-17 07:55
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/88033b156c1ebbd4989806e6717f8b87a35fc46e

**Comment by Hinny** [comment] 2022-05-17 08:00
Nice! Thanks!

**Comment by Rokvach** [comment] 2022-05-24 07:09
Tested, working correctly. Closing.

**Closed by Rokvach** 2022-05-24 07:09 UTC
Labels: Bug, Code
