### ISSUE TITLE
Shuttle doors not staying open when out of power

### ISSUE THREAD

**Issue by EdusFF** [Regalis11/Barotrauma#1552] opened 2019-06-08 16:32 UTC
Operating System:
Linux

Hardware:
Manjaro, 16 GB RAM, GTX 970

Message Body:
When you respawn on a shuttle and try to open the doors when the power is out they will not stay open and you have to constantly spam them

**Comment by NilanthAnimosus** [comment] 2019-06-09 10:53
are you sure this is not related due to the timer running out on the respawn shuttle? For the power to have ran out that should take some time - which then I assume the transport duration will have ran out.

the code is set to cause a closing of the respawn shuttle doors every 0.5 seconds - which honestly I think is impossible to get out of for the default shuttles because their hatch buttons are not even accessibly near the hatch you want to open making it a senselessly prolongued death of waiting in the shuttle struggling for nothing.

it also does several other things, but I think it shouldn't have such a short timer for closing the doors and undocking and such.

The default shuttle transport duration on servers was also far too low, and I witnessed over 90% of all shuttle respawn crews (Whom almost always had no helm skill too!) in public multiplayer in the last few days all die to the combination of the two.

**Comment by Regalis11** [comment] 2019-06-10 09:48
Yeah, as Nilanth said I'm pretty sure this is caused by the shuttle return timer.

**Comment by NilanthAnimosus** [comment] 2019-06-10 11:50
I don't suppose the "auto closing doors" could be changed to a value between 1.5 and 4 seconds? the undocking and such could remain the same as the shuttle (given these) given the fact the respawn shuttle virtually never manages to make a return - I've not seen a successful return of a respawn shuttle for over a full year now and its a brutal pain to anyone trying to exit.

Its especially bad with these new shuttle designs - its possible to get inside with the 0.5 second time (just swim down and keep opening around every 0.4th of a second approximately, and you'l manage to get in eventually) - getting out often sticks to a ladder or is otherwise generally much more difficult. I am just not sure anymore to the purpose of the 0.5 second door closing functionality on it being so short.

I've simply seen enough irritated players to feel it could use such a tweak, my rampant screaming of "Get out the timers running out!" also fell on way too many deaf ears and opening a shuttle door early is likely to get players banned in most servers.

**Closed** 2019-06-27 09:21 UTC
Labels: Bug, Code
