### ISSUE TITLE
Skills Reset on Mission Completion.

### ISSUE THREAD

**Issue by sargashC** [Regalis11/Barotrauma#7129] opened 2021-11-02 00:33 UTC
- [ X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When a mission is completed all of my skills get reset as if I am spawning in for the first time. I am not dying, I am not losing connection, everyone in the campaign does not have their skills reset.

**Steps To Reproduce**
I'm not really sure how to make it happen, or why, but it is. Just finish a mission (Or even just dock) and when everything reloads all of my skills are reset.

**Version**
Windows, most recent stable edition of Barotrauma

**Additional information**
I'm not dying, and I don't have a reapers Tax.

**Comment by ekqvist** [comment] 2021-11-02 06:53
Hi! This should now be fixed in the Unstable version of the game. This issue is a duplicate of #7002.

**Closed by ekqvist** 2021-11-02 06:53 UTC
