### ISSUE TITLE
Select matching objects crash

### ISSUE THREAD

**Issue by i-Existed** [Regalis11/Barotrauma#4114] opened 2020-10-21 10:33 UTC
I have searched the issue tracker to check if the issue has already been reported.

**Description**
The game crashes when using the "Select matching objects" feature on the Kastrull and Remora in the submarine editor.

**Steps To Reproduce**
Go to the submarine editor, load up the Kastrull/Remora submarine, use Shift + Right Click on any object, and click "Select matching objects".

**Version**
v0.10.5.1 Windows
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/5415219/crashreport.log)
[crashreport (4).log](https://github.com/Regalis11/Barotrauma/files/5415221/crashreport.4.log)

**Comment by ekqvist** [comment] 2020-10-21 10:36
Duplicate of #3914. Fixed in the next update.

**Closed by ekqvist** 2020-10-21 10:36 UTC
