### ISSUE TITLE
Health UI feature request

### ISSUE THREAD

**Issue by uyemeb** [Regalis11/Barotrauma#7323] opened 2021-11-15 10:34 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Could you make it so the health UI quick use buttons can use items from a medics uniform, a toolbelt or a medic uniforms in your inventory and not only from your item slots since it defeats the purpose of the quick use by making you do it manually anyways
![2021-11-15 13_32_59-Window](https://user-images.githubusercontent.com/43451345/141766630-805a0e33-0090-45e0-a2c5-9ff4f2488147.png)

**Comment by Regalis11** [comment] 2021-11-15 10:44
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7194

**Closed by Regalis11** 2021-11-15 10:44 UTC
