### ISSUE TITLE
Crashed when clicking the Disconnect button from Server lobby

### ISSUE THREAD

**Issue by cshingle** [Regalis11/Barotrauma#9995] opened 2022-10-06 03:41 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

The game crashed to desktop when I clicked the disconnect button from my own server (Hosted via Steam P2P). This happened to me maybe twice out of several attempts to re-create it.

### Reproduction steps

1. Start a private server
2. Adjust some settings
3. Click disconnect in the lower left corner
4. Crash to desktop

### Bug prevalence

Happens every now and then

### Version

0.19.10.0

### Which operating system did you encounter this bug on?

Linux

### Relevant error messages and crash reports

```shell
﻿Barotrauma Client crash report (generated on 10/05/2022 22:24:48)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


0ED07C7BB473C9782E2A41FC02118851


Game version 0.19.10.0 (ReleaseLinux, branch release, revision 811fb37ab3)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla, Europa Depths Vanilla Monsters, Europa Depths Equipment, Europa Depths Events, Europa Depths Npcs, Europa Depths Items, D-7 Dromedary
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.NetLobbyScreen
SteamManager initialized
Client (Round hadn't been started)


System info:
    Operating system: Unix 5.15.0.48 64 bit
    GPU name: 
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: One or more errors occurred. (Operation canceled) (System.AggregateException)
Target site: Void ThrowIfExceptional(Boolean)
Stack trace: 
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Barotrauma.Networking.ChildServerRelay.ReadIncomingMsgs() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 111
   at Barotrauma.Networking.ChildServerRelay.<UpdateRead>g__readBytes|40_0(Span`1 readTo) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 163
   at Barotrauma.Networking.ChildServerRelay.UpdateRead() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 155


InnerException: Operation canceled
Target site: Void MoveNext()
Stack trace: 
   at System.IO.Pipes.PipeStream.ReadAsyncCore(Memory`1 destination, CancellationToken cancellationToken)
Last debug messages:
[10/05/2022 22:24:48] WARNING: Tried to restore enabled packages multiple times/without performing a backup
[10/05/2022 22:24:07] MaximumMoneyTransferRequest
[10/05/2022 22:24:07] KarmaEnabled
[10/05/2022 22:24:07] KickVoteRequiredRatio
[10/05/2022 22:24:07] ModeSelectionMode
[10/05/2022 22:24:07] SubSelectionMode
[10/05/2022 22:24:07] DestructibleOutposts
[10/05/2022 22:24:07] AllowLinkingWifiToChat
[10/05/2022 22:24:07] AllowVoteKick
[10/05/2022 22:24:07] LosMode
[10/05/2022 22:24:07] PlayStyle
[10/05/2022 22:15:48] Lobby created!
[10/05/2022 22:10:09] Attempting to open ALC device "Starship/Matisse HD Audio Controller Analog Stereo"
[10/05/2022 22:10:08] Logged in as zig158 (SteamID STEAM_1:1:39219991)
```

**Comment by esirprus** [comment] 2022-10-06 08:06
[ .... ] Starting btserver: Applying steamclient.so sdk64 -- remove old file fix: Barotraum[ INFO ] Starting btserver: Applying steamclient.so sdk64 -- remove old file fix: Barotraum[  OK  ] Starting btserver: Applying steamclient.so sdk64 -- remove old file fix: Barotrauma
[  OK  ] Starting btserver: Applying steamclient.so sdk64 hardlink fix: Barotrauma
[ .... ] Starting btserver: Applying steamclient.so sdk32 -- remove old file fix: Barotraum[ INFO ] Starting btserver: Applying steamclient.so sdk32 -- remove old file fix: Barotraum[  OK  ] Starting btserver: Applying steamclient.so sdk32 -- remove old file fix: Barotrauma
[  OK  ] Starting btserver: Applying steamclient.so sdk32 link fix: Barotrauma
[ .... ] Starting btserver: Serverno server running on /tmp/tmux-1000/default
[ FAIL ] Starting btserver: Unable to start Server

**Comment by Techbane** [comment] 2022-10-06 08:42
Can confirm, am also getting this as of the update; on Mint 19.3 specifically. Don't even need to adjust any settings, just select Host Server, click Start, then click Disconnect and Yes.

The "Oops! Barotrauma just crashed" popup window also says "The error was not sent to the developers because user statistics have been disabled", despite that they are enabled. Just to be sure I went back in, disabled, re-enabled and confirmed, then triggered the crash again and it still says it.

**Comment by WrillWasTaken** [comment] 2022-10-06 10:35
Experienced possibly the same issue on windows when hosting after the update. Attempted to close server using disconnect button and crashed.

**Comment by WrillWasTaken** [comment] 2022-10-10 21:50
Just experienced this issue.
[crashreport (101).log](https://github.com/Regalis11/Barotrauma/files/9749453/crashreport.101.log)

**Comment by Rokvach** [comment] 2022-10-18 10:09
Tested on Linux and still crashes when leaving server
![image](https://user-images.githubusercontent.com/7299826/196401932-4727dbf8-908d-4a56-b864-92d7b4e3b31f.png)

**Comment by Regalis11** [comment] 2022-10-20 08:11
Should be retested after https://github.com/Regalis11/Barotrauma-development/pull/3603 has been merged

**Comment by Techbane** [comment] 2022-10-20 18:56
Still getting it on Mint 19.3 and it still won't autosubmit the crashreport for some reason. It looks pretty similar to the one above, but just in case:
```
﻿Barotrauma Client crash report (generated on 10/20/2022 11:44:18)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


11D783E09CC127D1BA37BC9FF6FBF709


Game version 0.19.14.0 (ReleaseLinux, branch release, revision 0daf5b87bd)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla, Yonoa, Azimuth 1.01, Humpback DX
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.NetLobbyScreen
SteamManager initialized
Client (Round hadn't been started)


System info:
    Operating system: Unix 5.4.0.124 64 bit
    GPU name: 
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: One or more errors occurred. (Operation canceled) (System.AggregateException)
Target site: Void ThrowIfExceptional(Boolean)
Stack trace: 
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Barotrauma.Networking.ChildServerRelay.ReadIncomingMsgs() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 111
   at Barotrauma.Networking.ChildServerRelay.<UpdateRead>g__readBytes|40_0(Span`1 readTo) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 168
   at Barotrauma.Networking.ChildServerRelay.UpdateRead() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 160
   at System.Threading.Thread.StartCallback()


InnerException: Operation canceled
Target site: Void MoveNext()
Stack trace: 
   at System.IO.Pipes.PipeStream.ReadAsyncCore(Memory`1 destination, CancellationToken cancellationToken)
Last debug messages:
[10/20/2022 11:44:17] WARNING: Tried to restore enabled packages multiple times/without performing a backup
[10/20/2022 11:44:07] Lobby created!
[10/20/2022 11:43:24] Attempting to open ALC device "Family 17h (Models 00h-0fh) HD Audio Controller Analog Stereo"
[10/20/2022 11:43:18] Logged in as Techbane (SteamID STEAM_1:0:9729555)
```

**Comment by Rokvach** [comment] 2022-12-07 09:36
There hasn't been any sightings of this in GA since the PR was merged, considering how common this was previously I'd say that the fix is working correctly, closing.

**Closed by Rokvach** 2022-12-07 09:36 UTC
Labels: Bug, Needs testing, Linux only, Code, Crash, Networking, Unstable
