### ISSUE TITLE
0.10.2.0: Server crash after a bizzare round

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#3294] opened 2020-07-03 21:59 UTC
Prefaced by [this issue](https://github.com/Regalis11/Barotrauma/issues/3293) in the same campaign round, the server would later go on to crash seemingly at random while doing an artifact mission. The artifact seemed to lack a conventional cave-to-ruin entrance. One player had previously experienced a laying-down desync in the outpost.
[consoleOutput.txt](https://github.com/Regalis11/Barotrauma/files/4871624/consoleOutput.txt)
[crashreport_object.log](https://github.com/Regalis11/Barotrauma/files/4871628/crashreport_object.log)

**Comment by Regalis11** [comment] 2020-11-09 18:59
I'm pretty sure this was a case of entity IDs getting mixed up: the log file seems to imply that as well (trying to read an update for a ruin decal, which there should be no updates for). 

Since there's no reliable way to reproduce this specific error, and since there's been so many fixes to these ID issues (maybe most importantly the readonly IDs introduced in the latest unstable), I think we can close this and keep an eye out for any new ID mismatch errors.

**Closed by Regalis11** 2020-11-09 18:59 UTC
Labels: Bug, Code, Networking
