### ISSUE TITLE
string oopsie in tutorial

### ISSUE THREAD

**Issue by leetie** [Regalis11/Barotrauma#10892] opened 2023-01-08 02:43 UTC
this happens in the next event after fabricating naloxone

![20230107214102_1](https://user-images.githubusercontent.com/59420931/211178159-6e1924a6-e9c9-4185-ac2e-40d128c9a836.jpg)

**Comment by Regalis11** [comment] 2023-01-08 18:36
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10751

**Closed by Regalis11** 2023-01-08 18:36 UTC
