### ISSUE TITLE
Game crashes whilst finishing a mission on singleplayer campaign mode

### ISSUE THREAD

**Issue by Zeroicedragon** [Regalis11/Barotrauma#1529] opened 2019-06-07 10:13 UTC
**Description**
When ending a mission, or entering an outpost, the game crashes

**Steps To Reproduce**
- Start a mission on singleplayer campaign mode
- Get to the end of the level
- Click on "Enter [Station name]"

**Version**
Windows 10 Enterprise version 1809 [Build: 17763.529]
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/3265453/crashreport.log)
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/3265447/crashreport.2.log)
[crashreport (3).log](https://github.com/Regalis11/Barotrauma/files/3265448/crashreport.3.log)
[crashreport (4).log](https://github.com/Regalis11/Barotrauma/files/3265449/crashreport.4.log)

**Comment by Zeroicedragon** [comment] 2019-06-08 07:12
Based on this other crash report I seem to notice that this happens everytime I use commands, though I'm not sure, so; the commands I use the most are:
- Fixitems
- Fixwalls
- Fixhulls
- Oxygen
- Air
- Killmonsters
- los
- Freecam

[crashreport (5).log](https://github.com/Regalis11/Barotrauma/files/3268287/crashreport.5.log)

**Comment by itchyOwl** [comment] 2019-06-10 06:35
The first log is not related to this issue.

**Comment by Zeroicedragon** [comment] 2019-06-10 06:53
This is indeed true, though, I cannot remember why my game crashed that time, thank you for pointing it out, my bad.

**Comment by Zeroicedragon** [comment] 2019-06-10 07:32
I remember now; I was checking some ruins and then switched to a character that was in the submarine (Singleplayer campaign) But that issue has already been addressed. (This is another crash report of the same type as the first one, though, I will not post more updates on this issue regarding changing characters)

[crashreport (6).log](https://github.com/Regalis11/Barotrauma/files/3271013/crashreport.6.log)

**Comment by itchyOwl** [comment] 2019-06-10 07:44
So does this happen always or just sometimes? I couldn't reproduce the issue by the steps you provided. I even tried the same map seed and the same console commands.

Is that a custom sub you are using?

**Comment by Zeroicedragon** [comment] 2019-06-10 07:56
It happens sometimes; I was trying to recreate the crash, but I got that other one instead; I will further try to recreate the issue (It's 3 AM so I will try tomorrow), I do have to point out that I take some time whilst finishing the mission (30 Minutes up to 1 hour and a half) And I stored a "shipping" crate (I do not remember if the crate had items inside) and a depth charge in the constructor) I no longer have said submarine just a replica that I did after reinstalling and verifying the game files.

Another thing to point out is that I collected minerals from the terrain; Deconstructed them and stored them.

**Comment by itchyOwl** [comment] 2019-06-11 13:50
I added some null checks, but it's difficult to say what's happening there, since the lines in the crash log don't make any sense, for some reason.

**Comment by Zeroicedragon** [comment] 2019-06-12 06:01
It might be a crash error on my side then, I tried replicating the crash and yes, it seems to be related to all of the above; I will place both submarines (The drone and the Remora) if it helps clarify something; After the first or second update to the game I will see if the crash still happens, if not, then this crash might be related to another thing, thank you for trying to fix this.

[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/3279766/crashreport.2.log)
[Submarines.zip](https://github.com/Regalis11/Barotrauma/files/3279767/Submarines.zip)

**Comment by Zeroicedragon** [comment] 2019-06-12 06:13
The map seed (Or campaign seed) is nKbSr2aK The mission is Killing a Hammerhead (I didn't buy anything)

**Comment by Zeroicedragon** [comment] 2019-06-13 03:40
Update 5: Tests show that Alien trinkets and resources may not be the cause of the issue; I need to test Alien blood, and monster drops placed in the submarine inventory; Outside of that everything seems stable; I will test with the Save Name "Save" instead of "Save 0" on further tests as I belive that might be responsible for it.

Here's an image of the items I left in the submarine inventory after collecting and deconstructing some.

![Test](https://user-images.githubusercontent.com/51478199/59402166-4af38080-8d6b-11e9-98ff-b587764ef4e0.png)

**Comment by itchyOwl** [comment] 2019-06-13 11:31
Still cannot reproduce.

I followed the steps using clean 0.9.0.4. release build:
- Created a new game with the map seed nKbSr2aK on the Remora MK II sub, provided above. Defined the save name as "Save".
- Finished the mission by using "killmonsters" cheat.
- Navigated the sub to the outpost and docked it.
- Spawned some alien items where I can get the materials in the picture (nasonovartifact, alienpowercell, alien pistol)
- Deconstructed the items and put the ingredients into containers.
- Entered the outpost and spoke to the watchman.
- Succesfully completed the round.
- Started a new round.
- Exitted the game.
- Load the game.

No crash.

**Comment by Zeroicedragon** [comment] 2019-06-13 23:36
This seems problematic; I must mention that my Barotrauma directory is on a partition outside of my windows directory; This might be the cause, I honestly don't know at this point what else could be causing this strange crash, I will try to replicate it further, whilst playing normally and taking notes of what I do.

**Comment by Zeroicedragon** [comment] 2019-06-15 03:41
Update; Played on 0.9.0.6, I did a pretty much everything that I tried before, there was no crash, so I think that it's fixed, thank you so much for your patience and help.

**Comment by itchyOwl** [comment] 2019-06-15 11:52
Might be the null checks that I blindly added. I suspect that there's an issue with the crash log writer that sometimes gives incorrect lines, which makes debugging a nightmare. Hopefully it's fixed now. Closing.

**Closed by itchyOwl** 2019-06-15 11:52 UTC
Labels: Bug, Code, Crash, Help wanted, Need more info, Needs testing
