### ISSUE TITLE
[Art] Pomegrenade extract uses the same icon as Fentanyl

### ISSUE THREAD

**Issue by someone972** [Regalis11/Barotrauma#4094] opened 2020-10-16 18:03 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Pomegrenade extract uses the same icon as Fentanyl. This makes it hard to find at a glance. Should probably have it's own icon, since +F seems to be 'F' for Fentanyl.

![image](https://user-images.githubusercontent.com/1829181/96293086-7150ae00-0fa7-11eb-9e17-f2f046c39ad6.png)

**Version**
v0.10.5.1

**Comment by ekqvist** [comment] 2020-10-16 23:37
Duplicate of #3858. Already fixed on Unstable, will be fixed in the next Stable update.

**Closed** 2020-10-16 23:38 UTC
Labels: Art, Bug, Duplicate
