### ISSUE TITLE
Crash.

### ISSUE THREAD

**Issue by KEKALKA** [Regalis11/Barotrauma#3467] opened 2020-08-02 18:46 UTC
Game crashed while me and my friend was defeating swarm with that message in a console. My friend was a host.
![image](https://user-images.githubusercontent.com/69120155/89129724-dec17680-d542-11ea-88ee-bece3ae5150b.png)
-
[crashreport_object.log](https://github.com/Regalis11/Barotrauma/files/5012601/crashreport_object.log)
-

It seems that crash occured on killing one of a crawlers.

Version is 0.10.4.0 stable.

**Additional information**
I didn't relaunched the game and connected to my friend again. And all I could see is ragdolls, every crew member was just lying ragdolls, though I saw them use items - welder, harmonica, etc. Same thing with the creatures - I could see, a crawler for example, only when it's dead.
And there's a host's screenshot when I was killed later.
![image](https://user-images.githubusercontent.com/69120155/89129900-4c21d700-d544-11ea-8830-35b5c8e5b245.png)

**Comment by quantus** [comment] 2020-08-05 16:41
I think I've also hit this same issue. Here is my very similar crashreport: [crashreport_object.log](https://github.com/Regalis11/Barotrauma/files/5029826/crashreport_object.log)
 The crash happened on all the connected clients, except the host, who was able to continue playing.

I think the "laying ragdolls" issue is some separate issue, and I've also seen it several times. Usually restarting the game has fixed that issue in my case.

**Comment by Regalis11** [comment] 2020-08-17 09:14
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3019

**Closed by Regalis11** 2020-08-17 09:14 UTC
Labels: Bug, Code, Crash, Networking
