### ISSUE TITLE
"Ph.D in Nuclear Physics" talent unavailable

### ISSUE THREAD

**Issue by Terrymeowish** [Regalis11/Barotrauma#8817] opened 2022-04-14 18:35 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I have been playing an electrical engineer for our campaign with friends, I have filled up my entire talent tree except for the Ph.D in Nuclear Physics talent. I was planning on going for that talent before filling in the Weapons Engineer branch, but the talent was unavailable to me, I couldn't tick it, then it made me put in all 4 talents of the Weapons Engineer branch before allowing me to press the Confirm button. I have leveled up 6 more times since, but it did not let me gain any talent points, thus getting the Ph.D in Nuclear Physics talent remains unobtainable for me.

**Steps To Reproduce**
I chose the talents in this order: Just A Scratch, Remote Monitor, Co-Author, College Athletics, Electrochemist, All-Seeing Eye. After this I wanted to choose Ph.D in Nuclear Physics, but couldn't and was forced to use my 1 talent point on the Military Applications, Arms Dealer, Castle Doctrine and Nuclear Option talents before the game would let me click the Confirm button to spend my single talent point.

**Version**
V0.16.7.0 Windows 11Home

**Comment by cshingle** [comment] 2022-04-14 20:55
This is most likely a duplicate these, and I believe is fixed in Unstable.
#8507
#8128
#8627

**Comment by Regalis11** [comment] 2022-04-15 08:41
Duplicate of https://github.com/Regalis11/Barotrauma/issues/8128

**Closed by Regalis11** 2022-04-15 08:41 UTC
