### ISSUE TITLE
Inability to auto reload SMG

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#10287] opened 2022-11-08 10:33 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

When holding the SMG in hands, press the digital key to select the magazine in own inventory, it will not be reloaded.
Before unstable version it was working fine.

### Bug prevalence

Happens every now and then

### Version

0.20.3.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-11-08 11:24
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10248

**Closed by Regalis11** 2022-11-08 11:24 UTC
