### ISSUE TITLE
Crash when encountering Thalamus

### ISSUE THREAD

**Issue by frrunkis** [Regalis11/Barotrauma#4095] opened 2020-10-17 02:01 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
This has happened to me several times.  Its not when i have only encountered a thalamus but when I am snared by one, but even more specifically when the little red things that explode start showing up on my sub.  Im not sure that it has specifically to do with the little red things but if i see them i expect a crash to come and it always has in single player.  I don't believe that I have seen that scenario in multiplayer.  I have been snared by a thalamus in multiplayer but did not see any of the red exploding things.
 
**Steps To Reproduce**
Navigate sub over the top of a thalamus ship and get snared.  In higher level areas at least, after getting snared the little red exploding things will show up in the sub and the game will crash

**Version**
v0.10.5.1

**Additional information**
Barotrauma Client crash report (generated on 10/16/2020 6:37:53 PM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

6F558E05A9FD96EA104348A23A5B582A

Game version 0.10.5.1 (ReleaseWindows, branch release, revision 9e259b2148)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: Gortyna FlexusHarmonia Linea
Loaded submarine: Typhon2 (F72FD6A4680E10273062C2E6D3A5A8DE)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19041.0 64 bit
    GPU name: NVIDIA GeForce GTX 1080
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Collection was modified; enumeration operation may not execute. (System.InvalidOperationException)
Target site: Void ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
Stack trace: 
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Barotrauma.Items.Components.RepairTool.Repair(Vector2 rayStart, Vector2 rayEnd, Single deltaTime, Character user, Single degreeOfSuccess, List`1 ignoredBodies) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Holdable\RepairTool.cs:line 297
   at Barotrauma.Items.Components.RepairTool.Use(Single deltaTime, Character character) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Holdable\RepairTool.cs:line 244
   at Barotrauma.Item.Use(Single deltaTime, Character character, Limb targetLimb) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 2055
   at Barotrauma.Character.Control(Single deltaTime, Camera cam) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 1475
   at Barotrauma.Character.Update(Single deltaTime, Camera cam) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2409
   at Barotrauma.AICharacter.Update(Single deltaTime, Camera cam) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\AICharacter.cs:line 86
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2228
   at Barotrauma.GameScreen.Update(Double deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 179
   at Barotrauma.GameMain.Update(GameTime gameTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 921
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59

Last debug messages:
[10/16/2020 6:20:01 PM] Generating an outpost for the start of the level... (Location: Gortyna Flexus Research Center, level type: LocationConnection)
[10/16/2020 6:20:00 PM] Generating an outpost for the end of the level... (Location: Harmonia Linea, level type: LocationConnection)
[10/16/2020 6:19:30 PM] (Msg) RelayNetWorkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[10/16/2020 6:19:30 PM] (Msg) Ping location: sea=25+2,eat=30+3/30+2,lax=47+4/48+2,okc=74+7/69+2,ord=75+7/70+2,iad=97+9/88+2,atl=88+8/89+2,tyo=153+15/120+2,tyo1=153+15/120+2,fra=182+18/172+2,sgp=218+21/201+2,gru=218+21/217+2
[10/16/2020 6:19:30 PM] (Msg) Ping measurement completed
[10/16/2020 6:19:29 PM] (Debug) Destroying relay 'sof#2 (139.45.193.10:27016)' because initial_ping_timeout
[10/16/2020 6:19:27 PM] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/SZTORM_Thunderbolt_Mk._II.sub, size: 600x341)
[10/16/2020 6:19:26 PM] (Debug) Destroying relay 'sof#4 (139.45.193.10:27018)' because initial_ping_timeout
[10/16/2020 6:19:25 PM] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/Athenaegis-D.sub, size: 1042x552)
[10/16/2020 6:19:23 PM] (Debug) Destroying relay 'sof#1 (139.45.193.10:27015)' because initial_ping_timeout
[10/16/2020 6:19:21 PM] (Debug) Destroying relay 'sof#3 (139.45.193.10:27017)' because initial_ping_timeout
[10/16/2020 6:19:18 PM] (Verbose) Communications with routing cluster 'waw' established.
[10/16/2020 6:19:18 PM] (Verbose) Communications with routing cluster 'sgp' established.
[10/16/2020 6:19:18 PM] (Verbose) Communications with routing cluster 'vie' established.
[10/16/2020 6:19:18 PM] (Verbose) Communications with routing cluster 'sto2' established.
[10/16/2020 6:19:18 PM] (Verbose) Communications with routing cluster 'syd' established.
[10/16/2020 6:19:18 PM] (Verbose) Communications with routing cluster 'sto' established.
[10/16/2020 6:19:18 PM] (Verbose) Communications with routing cluster 'tyo1' established.
[10/16/2020 6:19:18 PM] (Verbose) Communications with routing cluster 'tyo' established.
[10/16/2020 6:19:18 PM] (Verbose) Communications with routing cluster 'jnb' established.
[10/16/2020 6:19:18 PM] (Verbose) Communications with routing cluster 'maa' established.
[10/16/2020 6:19:18 PM] (Verbose) Communications with routing cluster 'dxb' established.
[10/16/2020 6:19:18 PM] (Verbose) Communications with routing cluster 'scl' established.
[10/16/2020 6:19:18 PM] (Verbose) Communications with routing cluster 'mad' established.
[10/16/2020 6:19:18 PM] (Verbose) Communications with routing cluster 'lux' established.
[10/16/2020 6:19:18 PM] (Verbose) Communications with routing cluster 'par' established.
[10/16/2020 6:19:18 PM] (Verbose) Communications with routing cluster 'bom' established.
[10/16/2020 6:19:18 PM] (Verbose) Communications with routing cluster 'lhr' established.
[10/16/2020 6:19:18 PM] (Verbose) Communications with routing cluster 'lim' established.
[10/16/2020 6:19:18 PM] (Verbose) Communications with routing cluster 'gru' established.
[10/16/2020 6:19:18 PM] (Verbose) Communications with routing cluster 'sea' established.
[10/16/2020 6:19:18 PM] (Verbose) Communications with routing cluster 'hkg' established.
[10/16/2020 6:19:18 PM] (Verbose) Communications with routing cluster 'ord' established.
[10/16/2020 6:19:18 PM] (Verbose) Communications with routing cluster 'fra' established.
[10/16/2020 6:19:18 PM] (Verbose) Communications with routing cluster 'okc' established.
[10/16/2020 6:19:18 PM] (Verbose) Communications with routing cluster 'ams' established.
[10/16/2020 6:19:18 PM] (Verbose) Communications with routing cluster 'lax' established.
[10/16/2020 6:19:18 PM] (Verbose) Communications with routing cluster 'iad' established.
[10/16/2020 6:19:18 PM] (Verbose) Communications with routing cluster 'atl' established.
[10/16/2020 6:19:18 PM] (Verbose) Communications with routing cluster 'eat' established.
[10/16/2020 6:19:18 PM] (Msg) RelayNetWorkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[10/16/2020 6:19:18 PM] (Msg) Performing ping measurement
[10/16/2020 6:19:18 PM] (Msg) Got SDR network config.  Loaded revision 283 OK
[10/16/2020 6:19:18 PM] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[10/16/2020 6:19:08 PM] Attempting to open ALC device "OpenAL Soft on Speakers (Realtek High Definition Audio)"
[10/16/2020 6:19:06 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[10/16/2020 6:19:06 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[10/16/2020 6:19:05 PM] Logged in as Frrunkis (SteamID STEAM_1:1:128272568)

**Comment by ekqvist** [comment] 2020-10-18 21:54
Duplicate of #3896. Fixed in the next update. Sorry for the inconvenience.

**Closed** 2020-10-18 21:54 UTC
Labels: Bug, Code, Crash, Duplicate
