### ISSUE TITLE
doors / horizontal gaps can't fully drain a room

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#7539] opened 2021-11-29 16:14 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
A door (side to side) gap can't fully drain a room. the rate of water flow to the less filled hull reduces severely when the filled hull's water level is very low, to the point that it stops draining at <1 water.

while this doesn't have much buoyancy effects, it causes water% of water detectors to go mad because of #6252 

**Steps To Reproduce**
1. add water to a hull
2. drain it to the side (i.e., open a door
3. wait
4. water stops at <1 water

**Version**
0.15.13 stable

**Additional information**
It also angers sub builders who use water%

Potential fixes be round water up for purpose of side-to-side horizontal gap flow? and/or set a minimum flow rate? or water detector to ignore <1 water?

pic: remaining water after "draining" a room out the side: 
![image](https://user-images.githubusercontent.com/5103517/143903023-71e3192b-ed84-405a-b3a1-9de2b81e6019.png)

**Comment by TBenz4Sportsball** [comment] 2021-11-29 16:16
As the angry sub builder in question, I can confirm that this bug makes the game metaphorically unplayable.

**Comment by Regalis11** [comment] 2021-11-29 17:39
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/0769aead8904d84ec9a8244d00fc66e7154d6020

**Comment by Rokvach** [comment] 2021-12-10 09:31
I was still able to reproduce this with the new Orca 2 sub, I used the water command to flood this room and then drained it to the room next to it and the flood alarm in command just keeps beeping even though seemingly there isn't any water anywhere

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/f9d4cb5f-8cac-46bd-a0da-6a7926ba15b5)

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/950f74d1-8caf-4db2-8a62-eee44ee93eeb)

**Comment by Regalis11** [comment] 2021-12-10 12:45
Seemed to happen because Orca uses the "output" pin instead of "water_%", and my change only affected the latter. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2dd3ab8dbae8e2afe62376bbfc81724867a1e312

**Comment by Rokvach** [comment] 2021-12-10 14:04
Tested, working correctly. Closing.

**Closed by Rokvach** 2021-12-10 14:04 UTC
Labels: Code
