### ISSUE TITLE
Item animations aren't working

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8641] opened 2022-03-28 08:17 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you try to sit on a chair or sleep on a bed the actual sitting or laying down animations aren't working. 

**Steps To Reproduce**
Load up singleplayer and try and sit on one of the office chairs at the outpost

**Version**
0.17.4.0
Branch: dev
Commit: https://github.com/Regalis11/Barotrauma-development/commit/1cdfe4f8297cc382e987b333cce81a46ba9a9900

**Comment by Regalis11** [comment] 2022-03-28 08:23
Caused by the changes done to address https://github.com/regalis11/barotrauma/issues/8580, closing this one

**Closed by Regalis11** 2022-03-28 08:23 UTC
Labels: Bug, Code
