### ISSUE TITLE
Artifact spawning issue

### ISSUE THREAD

**Issue by aeondez** [Regalis11/Barotrauma#11466] opened 2023-03-06 21:37 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Artifacts do not appear to be spawning outside of salvage missions.

in alienitems.xml, artifacts have 2 preferred containers, wrecksecarmcab and ruintreasure

However, there is no container called ruintreasure. There is a container called artifactholder, but it doesn't have the ruintreasure tag which I think is what it was supposed to be.

Not sure if this is an issue with incorrect tagging, extremely low probability, or both.

Semi-related, artifact storage containers make artifacts trivial to deal with, assuming I could find any.

### Reproduction steps

1. Start a multiplayer session
2. Look for artifacts on any mission that is not a salvage mission.
3. I cannot seem to find any.

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Udrakan** [comment] 2023-03-06 22:53
It always feels so disappointing getting to the artifact room in the ruins and seeing the holder empty. It might be a design choice, but it doesn't feel good.

**Comment by dakkhuza** [comment] 2023-03-07 03:47
according to the tags, artifacts are also supposed to spawn in wrecks rarely but I've never seen this happen. I suspect something is broken as they have similar spawn chances to unique weapons.

**Comment by Regalis11** [comment] 2023-03-07 07:15
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7233

**Closed by Regalis11** 2023-03-07 07:15 UTC
