### ISSUE TITLE
Bloody Business's extra alien blood drop doesn't appear to be working

### ISSUE THREAD

**Issue by PokkeTigrex** [Regalis11/Barotrauma#10173] opened 2022-10-27 22:34 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Medic's Bloody Business talent doesn't give any extra alien blood off creatures.
The other part of the talent, reducing psychosis given from alien blood, appears to be working correctly however.
Could also be WIP.

### Reproduction steps

Get the skill as a medic, go kill any creatures that's considered a large monster, from crawlers and mudraptors, up to hammerheads extra blood won't drop.

### Bug prevalence

Happens every time I play

### Version

Other

### -

0.20.0.0

### Which operating system did you encounter this bug on?

Windows

**Comment by 3e849f2e5c** [comment] 2022-10-28 04:18
> from crawlers and mudraptors, up to hammerheads extra blood won't drop.

The talent specifies anything slightly larger than a mudraptor "large" so crawlers and mudraptors are too small but I was unable to reproduce hammerheads not dropping blood

**Comment by PokkeTigrex** [comment] 2022-10-28 12:38
If the talent is only active for creatures like hammerheads, hammerheads should be dropping two alien blood. They are only dropping one, the one they spawn with.
![image](https://user-images.githubusercontent.com/85914375/198587997-f7748560-929a-421a-8162-96e6fa333a24.png)

In comparison to having no talents:
![image](https://user-images.githubusercontent.com/85914375/198588629-881a9893-a56f-4428-9cab-683fe1983183.png)

**Comment by 3e849f2e5c** [comment] 2022-10-28 12:51
Unable to reproduce

https://user-images.githubusercontent.com/39580303/198590951-a7a38318-cee3-4344-b5d9-644cd7840bf8.mp4

**Comment by 3e849f2e5c** [comment] 2022-10-28 12:56
Managed to find the cause, turns out that the Gene Harvester talent is marking the creature as looted first so Bloody Business will never activate if both of them are active which always in normal means

Fixed in https://github.com/Regalis11/Barotrauma-development/commit/adfaf9a337f689043a569a3ae24dc217b18ecf9d

**Comment by NilanthAnimosus** [comment] 2022-11-30 16:03
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/2b57faa07493e732f98261ead832ba904168f57b, no issues found, closing.

**Closed by NilanthAnimosus** 2022-11-30 16:03 UTC
Labels: Bug, Code, Design, Unstable
