### ISSUE TITLE
Crash after I Change Speaker Settings in Windows

### ISSUE THREAD

**Issue by Lynx1980** [Regalis11/Barotrauma#5797] opened 2021-05-15 05:36 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

//**Description**
    Crash, Freeze after start Campain

//**Steps To Reproduce**
-Install the Game
- I absolved the first Tutorial.
-Restart the Game
-Remove any Mods from the Game
-Start first Time a Kampain with radiotation checkbox
-In the Loading Screen (
   go on the Windows Desktop
   changeing Sounddriver Settings from 7.1 Soundchannels to Stereo
 get a disconect message from the game, no (soundcard anmore)
in the Game after finish loadin, go in options an reconect with the sound source
Sound works again,
1, 2 Secound, freeze...
 

//**Version**
  Game version 0.13.3.11 (ReleaseWindows, branch release, revision 7096536cf1)
  Windows 10

**Additional information**
Im using an A/D USB 3D Headphone from Sennhiser 3D G4ME1
Driverversion 8.1.1.215
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/6482649/crashreport.log)

Barotrauma Client crash report (generated on 15/05/2021 06:57:01)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

1E784E57B83E4AD2C454A781377E1373

Game version 0.13.3.11 (ReleaseWindows, branch release, revision 7096536cf1)
Graphics mode: 1920x1200 (BorderlessWindowed)
VSync ON
Language: German
Selected content packages: Vanilla 0.9
Level seed: Pastonia
Loaded submarine: Dugong (8290AB05BF6409D9037CCC1FEEAB9377)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19042.0 64 bit
    GPU name: Radeon (TM) RX 480 Graphics
    Display mode: {Width:1920 Height:1200 Format:Color AspectRatio:1.6}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Microsoft.Xna.Framework.Vector2 get_DrawPosition()
Stack trace: 
   at Barotrauma.Character.get_DrawPosition() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 776
   at Barotrauma.Lights.LightManager.<RenderLightMap>g__DrawHalo|49_0(Character character, <>c__DisplayClass49_0& ) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\Lights\LightManager.cs:line 377
   at Barotrauma.Lights.LightManager.RenderLightMap(GraphicsDevice graphics, SpriteBatch spriteBatch, Camera cam, RenderTarget2D backgroundObstructor) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\Lights\LightManager.cs:line 347
   at Barotrauma.GameScreen.DrawMap(GraphicsDevice graphics, SpriteBatch spriteBatch, Double deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\GameScreen.cs:line 188
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\GameScreen.cs:line 122
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 1026
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[15/05/2021 06:57:01] Attempted to access a potentially removed ragdoll. Character: Edison Malone, id: 1301, removed: True, ragdoll removed: True
   at System.Environment.get_StackTrace()
   at Barotrauma.Ragdoll.get_Limbs() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\Ragdoll.cs:line 63
   at Barotrauma.Ragdoll.get_HasMultipleLimbsOfSameType() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\Ragdoll.cs:line 77
   at Barotrauma.Ragdoll.GetLimb(LimbType limbType, Boolean excludeSevered) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\Ragdoll.cs:line 1738
   at Barotrauma.Ragdoll.get_MainLimb() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\Ragdoll.cs:line 218
   at Barotrauma.Character.get_DrawPosition() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 776
   at Barotrauma.Lights.LightManager.<RenderLightMap>g__DrawHalo|49_0(Character character, <>c__DisplayClass49_0& ) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\Lights\LightManager.cs:line 364
   at Barotrauma.Lights.LightManager.RenderLightMap(GraphicsDevice graphics, SpriteBatch spriteBatch, Camera cam, RenderTarget2D backgroundObstructor) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\Lights\LightManager.cs:line 347
   at Barotrauma.GameScreen.DrawMap(GraphicsDevice graphics, SpriteBatch spriteBatch, Double deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\GameScreen.cs:line 191
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\GameScreen.cs:line 124
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 1031
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 667
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 511
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59
[15/05/2021 06:56:55] Attempted to access a potentially removed character. Character: Edison Malone, id: 1301, removed: True. AnimController.Collider == null
   at System.Environment.get_StackTrace()
   at Barotrauma.Character.get_SimPosition() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 752
   at Barotrauma.Character.get_Position() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 769
   at Barotrauma.Entity.get_WorldPosition() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Entity.cs:line 58
   at Barotrauma.CameraTransition.Update(ISpatialEntity targetEntity, Camera cam)+MoveNext() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CameraTransition.cs:line 84
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 218
   at Barotrauma.CoroutineManager.Update(Single unscaledDeltaTime, Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 259
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 979
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59
[15/05/2021 06:56:36] Attempting to open ALC device "OpenAL Soft on Speakers (4- Sennheiser 3D G4ME1)"
[15/05/2021 06:56:28] OpenAL Soft on Microphone (4- Sennheiser 3D G4ME1) 50
[15/05/2021 06:56:16] Generating an outpost for the start of the level... (Location: Pastonia City, level type: Outpost)
[15/05/2021 06:55:20] Playback device has been disconnected. You can select another available device in the settings.
[15/05/2021 06:54:51] Generating an outpost for the start of the level... (Location: Pastonia City, level type: Outpost)
[15/05/2021 06:50:30] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Workshop/2483903852.png, size: 1466x640)
[15/05/2021 06:50:30] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Workshop/2484652363.png, size: 1399x1399)
[15/05/2021 06:50:29] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Workshop/2482877728.png, size: 800x450)
[15/05/2021 06:50:29] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Workshop/2484388832.png, size: 601x338)
[15/05/2021 06:50:29] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Workshop/2485278594.png, size: 600x242)
[15/05/2021 06:50:29] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Workshop/2483236185.png, size: 750x750)
[15/05/2021 06:50:29] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Workshop/2483097245.png, size: 486x509)
[15/05/2021 06:50:29] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Workshop/2484751523.png, size: 77x78)
[15/05/2021 06:50:29] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Workshop/2485758502.png, size: 229x112)
[15/05/2021 06:50:23] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Workshop/2108010462.png, size: 1540x866)
[15/05/2021 06:50:23] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Workshop/2127575896.png, size: 1540x866)
[15/05/2021 06:49:57] OpenAL Soft on Microphone (4- Sennheiser 3D G4ME1) 50
[15/05/2021 06:49:57] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[15/05/2021 06:49:53] OpenAL Soft on Microphone (4- Sennheiser 3D G4ME1) 50
[15/05/2021 06:49:33] Content/Characters/Watcher/Watcher.xml
[15/05/2021 06:49:33] Content/Characters/Tigerthresher/Tigerthresher.xml
[15/05/2021 06:49:33] Content/Characters/Terminalcell/Terminalcell.xml
[15/05/2021 06:49:33] Content/Characters/Spineling/Spineling.xml
[15/05/2021 06:49:33] Content/Characters/Psilotoad/Psilotoad.xml
[15/05/2021 06:49:33] Content/Characters/Peanut/Peanut.xml
[15/05/2021 06:49:33] Content/Characters/Orangeboy/Orangeboy.xml
[15/05/2021 06:49:33] Content/Characters/Mudraptor_unarmored/Mudraptor_unarmored.xml
[15/05/2021 06:49:33] Content/Characters/Mudraptor/Mudraptor.xml
[15/05/2021 06:49:33] Content/Characters/Molochblack/Molochblack.xml
[15/05/2021 06:49:33] Content/Characters/Molochbaby/Molochbaby.xml
[15/05/2021 06:49:33] Content/Characters/Moloch/Moloch.xml
[15/05/2021 06:49:33] Content/Characters/Mantis/Mantis.xml
[15/05/2021 06:49:33] Content/Characters/Leucocyte/Leucocyte.xml
[15/05/2021 06:49:33] Content/Characters/Legacywatcher/Legacywatcher.xml
[15/05/2021 06:49:33] Content/Characters/Legacytigerthresher/Legacytigerthresher.xml
[15/05/2021 06:49:33] Content/Characters/Legacymoloch/Legacymoloch.xml
[15/05/2021 06:49:33] Content/Characters/Legacyhusk/Legacyhusk.xml
[15/05/2021 06:49:33] Content/Characters/Legacyendworm/Legacyendworm.xml
[15/05/2021 06:49:33] Content/Characters/Legacycrawler/Legacycrawler.xml
[15/05/2021 06:49:33] Content/Characters/Legacycharybdis/Legacycharybdis.xml
[15/05/2021 06:49:33] Content/Characters/Husk/Husk.xml
[15/05/2021 06:49:33] Content/Characters/Humanhusk/Humanhusk.xml
[15/05/2021 06:49:33] Content/Characters/Human/Human.xml
[15/05/2021 06:49:33] Content/Characters/Hammerheadspawn/Hammerheadspawn.xml
[15/05/2021 06:49:33] Content/Characters/Hammerheadmatriarch/Hammerheadmatriarch.xml
[15/05/2021 06:49:33] Content/Characters/Hammerheadgold/Hammerheadgold.xml
[15/05/2021 06:49:33] Content/Characters/Hammerhead/Hammerhead.xml
[15/05/2021 06:49:33] Content/Characters/Fractalguardian2/Fractalguardian2.xml
[15/05/2021 06:49:33] Content/Characters/Fractalguardian/Fractalguardian.xml
[15/05/2021 06:49:33] Content/Characters/Endworm/Endworm.xml
[15/05/2021 06:49:33] Content/Characters/Crawlerhusk/Crawlerhusk.xml
[15/05/2021 06:49:33] Content/Characters/Crawler/Crawler.xml
[15/05/2021 06:49:33] Content/Characters/Coelanth/Coelanth.xml
[15/05/2021 06:49:33] Content/Characters/Charybdisold/Charybdisold.xml
[15/05/2021 06:49:33] Content/Characters/Charybdis/Charybdis.xml
[15/05/2021 06:49:33] Content/Characters/Carrier/Carrier.xml
[15/05/2021 06:49:33] Content/Characters/Bonethresher/Bonethresher.xml
[15/05/2021 06:49:33] Content/Characters/Balloon/Balloon.xml
[15/05/2021 06:49:32] Trying to spawn Content/Characters/Human/Human.xml
[15/05/2021 06:47:15] (Msg) SDR RelayNetworkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[15/05/2021 06:47:15] (Msg) Ping location: fra=31+3,vie=37+3,ams=44+4/37+3,par=58+5/40+3,lhr=43+4,waw=49+4/46+3,sto=67+6/50+3,sto2=59+5/51+3,mad=66+6/62+3,iad=123+12/117+3,sgp=265+26/227+19,gru=232+23
[15/05/2021 06:47:15] (Msg) Ping measurement completed
[15/05/2021 06:47:14] (Debug) Destroying relay 'sof#1 (139.45.193.10:27015)' because initial_ping_timeout
[15/05/2021 06:47:11] (Debug) Destroying relay 'sof#2 (139.45.193.10:27016)' because initial_ping_timeout
[15/05/2021 06:47:09] (Debug) Destroying relay 'sof#3 (139.45.193.10:27017)' because initial_ping_timeout
[15/05/2021 06:47:06] (Debug) Destroying relay 'sof#4 (139.45.193.10:27018)' because initial_ping_timeout
[15/05/2021 06:47:04] (Verbose) Communications with routing cluster 'syd' established.
[15/05/2021 06:47:04] (Verbose) Communications with routing cluster 'tyo' established.
[15/05/2021 06:47:04] (Verbose) Communications with routing cluster 'tyo1' established.
[15/05/2021 06:47:04] (Verbose) Communications with routing cluster 'sgp' established.
[15/05/2021 06:47:04] (Verbose) Communications with routing cluster 'lim' established.
[15/05/2021 06:47:04] (Verbose) Communications with routing cluster 'sea' established.
[15/05/2021 06:47:04] (Verbose) Communications with routing cluster 'scl' established.
[15/05/2021 06:47:04] (Verbose) Communications with routing cluster 'jnb' established.
[15/05/2021 06:47:04] (Verbose) Communications with routing cluster 'maa' established.
[15/05/2021 06:47:04] (Verbose) Communications with routing cluster 'hkg' established.
[15/05/2021 06:47:04] (Msg) Cluster 'lax' has a selection penalty of 3ms for load balancing purposes.  (As per lax#45 (162.254.195.86:27021)).
[15/05/2021 06:47:04] (Verbose) Communications with routing cluster 'lax' established.
[15/05/2021 06:47:04] (Verbose) Communications with routing cluster 'sto2' established.
[15/05/2021 06:47:04] (Verbose) Communications with routing cluster 'eze' established.
[15/05/2021 06:47:04] (Verbose) Communications with routing cluster 'sto' established.
[15/05/2021 06:47:04] (Verbose) Communications with routing cluster 'waw' established.
[15/05/2021 06:47:04] (Verbose) Communications with routing cluster 'ord' established.
[15/05/2021 06:47:04] (Verbose) Communications with routing cluster 'vie' established.
[15/05/2021 06:47:04] (Verbose) Communications with routing cluster 'gru' established.
[15/05/2021 06:47:04] (Verbose) Communications with routing cluster 'iad' established.
[15/05/2021 06:47:04] (Verbose) Communications with routing cluster 'eat' established.
[15/05/2021 06:47:04] (Verbose) Communications with routing cluster 'dfw' established.
[15/05/2021 06:47:04] (Verbose) Communications with routing cluster 'bom' established.
[15/05/2021 06:47:04] (Verbose) Communications with routing cluster 'mad' established.
[15/05/2021 06:47:04] (Verbose) Communications with routing cluster 'par' established.
[15/05/2021 06:47:04] (Verbose) Communications with routing cluster 'dxb' established.
[15/05/2021 06:47:04] (Verbose) Communications with routing cluster 'lhr' established.
[15/05/2021 06:47:04] (Verbose) Communications with routing cluster 'atl' established.
[15/05/2021 06:47:03] (Verbose) Communications with routing cluster 'ams' established.
[15/05/2021 06:47:03] (Verbose) Communications with routing cluster 'fra' established.
[15/05/2021 06:47:03] (Msg) SDR RelayNetworkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[15/05/2021 06:47:03] (Msg) Performing ping measurement
[15/05/2021 06:47:03] (Msg) Got SDR network config.  Loaded revision 319 OK
[15/05/2021 06:47:03] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[15/05/2021 06:46:56] Attempting to open ALC device "OpenAL Soft on Speakers (4- Sennheiser 3D G4ME1)"
[15/05/2021 06:46:56] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[15/05/2021 06:46:55] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[15/05/2021 06:46:54] Logged in as Lynx(GER) (SteamID STEAM_1:0:41384924)

**Comment by Regalis11** [comment] 2021-05-17 07:42
Potentially fixed in https://github.com/Regalis11/Barotrauma-development/commit/97b0b323e2b97740e5237856d7ac56cebf7eecdd

**Comment by Rokvach** [comment] 2021-06-04 10:24
There hasn't been any similar crashes since the fix nor new issues caused by the fix, seems to be working correctly. Closing.

**Closed by Rokvach** 2021-06-04 10:24 UTC
Labels: Bug, Code, Crash
