### ISSUE TITLE
Unable to rename items

### ISSUE THREAD

**Issue by KalimullinGleb** [Regalis11/Barotrauma#10628] opened 2022-12-01 16:50 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Since Hoist The Sails update vanilla items ceased to be renamable. I tried creating text files, fixing a new name and description through xml code directly, even tag system from EnglishNew wasnt working. 
Sonetimes the item does get a new name but when i restart the game it recieves its vanilla name back.

### Reproduction steps

I tried renaming vanilla weapons. Firts i tried doing it via overriding Item xml file, but it wasnt working at all(worked before HTS). Then i tried creating a separate text file and using it, neither did this help. I tried using tags from EnglishNew text file, but they seem to work unconsistantly, sometimes changing names and descriptions but failing to do so when i restart the game even tho i havent changed anything.

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Console doesnt show any error messages, hash calculation also reveals nothing not working.
```

**Comment by Regalis11** [comment] 2022-12-03 12:01
Duplicate of https://github.com/Regalis11/Barotrauma/issues/8450

**Closed by Regalis11** 2022-12-03 12:01 UTC
