### ISSUE TITLE
Characters "Dancing" on Unstable

### ISSUE THREAD

**Issue by ParadoxSong** [Regalis11/Barotrauma#6431] opened 2021-08-16 23:06 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Unstable: Characters "dancing" which if you press H for heal show them momentarily collapsing and allowing you to perform CPR, before standing back up.

**Steps To Reproduce**
Multiplayer. Always occurs within a round though not immediately. Can't be seen happening to yourself.

**Version**
Unstable v0.1400.8.0 revision 4c9bd0bacf

**Additional information**
Multiplayer specific and harmless, just ruins the mood.

**Comment by Regalis11** [comment] 2021-08-17 08:16
I'm afraid I couldn't reproduce this, pressing H seems to have no effect.

**Comment by Rokvach** [comment] 2021-08-17 10:05
I noticed this in the outpost couple times on multiplayer, they move around similarly as if a player periodically presses spacebar which leads to them dancing, on my encounter only two of the bots were doing it but they corrected themselves overtime. No idea as to how to reproduce it other than just load up outposts until you see NPC's behaving strangely.

**Comment by ParadoxSong** [comment] 2021-08-17 10:16
Ah, to be clear, H doesnt cause it but simply reveals CPR is allowed every
other tick while they're dancing. We've only ever seen it occur during a
round, and probably only while the sub was moving(but I can't confirm
that), but it did occur to NPCs. The behaviour can be temporarily stopped
by long pressing spacebar or aiming with at least shotguns, but someone
would have to tell you your dancing since it's not visible to you.

**Comment by Regalis11** [comment] 2021-08-17 13:14
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b4f342a4b22790929e1379aab473411c93227574

**Comment by Rokvach** [comment] 2021-08-20 07:39
I haven't noticed this happening after the fix, seems to be working correctly. Closing.

**Closed by Rokvach** 2021-08-20 07:39 UTC
Labels: Bug, Code, Networking
