### ISSUE TITLE
Unstable - Medicine don't work

### ISSUE THREAD

**Issue by Abkim27** [Regalis11/Barotrauma#8460] opened 2022-03-06 08:34 UTC
**Description**
Healing medicine don't work

**Steps To Reproduce**
1 Punch someone
2 Give morphine

**Version**
v0.17.0.0

**Comment by cshingle** [comment] 2022-03-08 15:37
This looks like it may be a duplicate of #8409

**Comment by Abkim27** [comment] 2022-03-08 16:39
Oh, seems like, but it don't work without 100 medical skill

**Closed** 2022-03-08 16:40 UTC
