### ISSUE TITLE
Storage containers can be put inside storage containers

### ISSUE THREAD

**Issue by Sebanik** [Regalis11/Barotrauma#10136] opened 2022-10-22 08:43 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I expected for this to not be real, it does not make any sense
![image](https://user-images.githubusercontent.com/116428993/197329900-53cab927-0e8f-4988-9719-d3b8cfb29882.png)

### Reproduction steps

1. start any game or campaign
2. get 2 or more storage containers 
3. Put a storage container inside the other (storage containers can be filled up by other items regardless)
4. see the weirdness and unexplainable storage container inside of a storage container

(you can probably have infinite space like this because its possible to do this infinitely. e.g. storage container inside of a storage container inside of another storage container and so on.)

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
There are no reports of any issues it just think it works as it should but i still find it weird and you probably do as well
```

**Comment by Regalis11** [comment] 2022-10-22 08:59
I'm afraid I could not reproduce this issue. Are you using some kind of mods? Where did you get the storage containers - I'm wondering if there could be some outdated/modified ones in the submarine you're using?

**Comment by ubertpendragon** [comment] 2022-10-22 17:21
Isn't that just https://github.com/Regalis11/Barotrauma/issues/10003

**Comment by Sebanik** [comment] 2022-10-23 07:08
Oh, im sorry Regalis its maybe because that campaign is pretty old and if i
make a new campaign now it probably wont work sorry for wasting your time

so 22. 10. 2022 v 10:59 odesílatel Joonas Rikkonen ***@***.***>
napsal:

**Comment by Regalis11** [comment] 2022-11-08 15:26
Most likely a duplicate of https://github.com/Regalis11/Barotrauma/issues/10003

**Closed by Regalis11** 2022-11-08 15:26 UTC
Labels: Bug, Need more info, Code
