### ISSUE TITLE
hired AI crew doesn't persist across save games in multiplayer campaign

### ISSUE THREAD

**Issue by seannybgoode** [Regalis11/Barotrauma#3626] opened 2020-08-25 07:52 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
hired AI crew doesn't persist across save games in multiplayer campaign

**Steps To Reproduce**
- start a multiplayer server
- hire a crew
- leave/save the game
- exit barotrauma completely
- start the game and rehost your server
- load your save
- note that the AI crew you hired is gone

**Version**
0.10.4.0

**Additional information**
crew seems to persist if the game is left running, but not if the game is exited to desktop, will update with new/additional steps if we find this is not the case

**Comment by Regalis11** [comment] 2020-08-25 08:13
Duplicate of #3346. This happens whenever you quit the game on the round after you've hired the characters. Until we release the next patch with the fix, it should be possible to work around the issue by leaving and re-entering the outpost after you've done the hiring.

**Closed by Regalis11** 2020-08-25 08:13 UTC
