### ISSUE TITLE
Players spawn with wrong jobs

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#5453] opened 2021-04-07 16:18 UTC
**Description**
After starting campaign, first mission, 3 of us kept getting wrong jobs. One of us was always captain, so it adhered to the mincount I think, but it was a person without any captain preference while somebody else had it as priority and the 3rd guy had wrong job too. During campaign, as people kept joining mid-rounds, job preferrence was correct.

**Steps To Reproduce**
-start new steam P2P hosted campaign
-everyone selects their job priority, one of the player picks captain as no.1
-see if they get the job they want

**Version**
Unstable

**Comment by Regalis11** [comment] 2021-04-08 13:14
Potentially related: https://github.com/Regalis11/Barotrauma/issues/4118

**Comment by ekqvist** [comment] 2021-04-08 14:59
Also related to #5127 (especially the comment in the issue)

**Comment by Regalis11** [comment] 2021-04-08 15:16
Okay, finally figured out the issue! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6da29ecb3841d2d5e3fd0fe7b44dfc266b2358c1

**Comment by Regalis11** [comment] 2021-04-08 15:16
On a closer look this is a duplicate of https://github.com/Regalis11/Barotrauma/issues/5127, closing this one

**Closed by Regalis11** 2021-04-08 15:16 UTC
Labels: Bug, Code, Networking
