### ISSUE TITLE
Freezes

### ISSUE THREAD

**Issue by 3no100u2no200** [Regalis11/Barotrauma#9136] opened 2022-05-14 16:51 UTC
The game freezes hardly. At first freezes appears,but on a small vessels with a small crew onboard fps dropped down up to 25 or even 12 on port. But from period of the game on winterhalter submarine with 12 crewmembers onboard it appears nearly impossible to make something after docking on a station- FPS drops down to 4-6.
Operation system: Windows 10
Game is launching from a steam server.
![BT](https://user-images.githubusercontent.com/70072265/168441075-8a19e835-21fe-4f21-b295-07f2bca6b38d.png)

**Comment by Regalis11** [comment] 2022-05-16 05:52
Duplicate of https://github.com/Regalis11/Barotrauma/issues/8961

**Closed by Regalis11** 2022-05-16 05:52 UTC
