### ISSUE TITLE
Diving suit disappearing

### ISSUE THREAD

**Issue by FLundin** [Regalis11/Barotrauma#3633] opened 2020-08-25 17:19 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Diving suit disappearing while wearing it

**Steps To Reproduce**
Single player campaign. I was collecting an Faraday artifact and were on my way back to my sub when the diving suit disappeared from my inventory

**Version**
v0.10.4.0 Win10

**Additional information**
I have it recorded plus 10 more mins before the incident. but my internet is really slow on uploading so let me know if you are interested in the full 10 min and ill try to figure something out. I can stream it over discord if you contact me.

![ezgif-2-20d26d0d7f20](https://user-images.githubusercontent.com/16923987/91206671-cab70200-e707-11ea-94ed-e3f69c7e1d98.gif)

**Comment by Regalis11** [comment] 2020-10-08 08:45
I assume this was a one-time occurrence, not something that happens frequently? If it was a one-time thing, I'm afraid there may not be much we can do about it unless we manage to figure out the exact conditions that caused it to occur. But let's keep this open for a while longer in case we stumble upon this or find a way to reproduce it.

**Comment by itchyOwl** [comment] 2020-10-21 09:07
Could be caused by bots taking the suit that they shouldn't be able to interact with. It hasn't ever happened on me, but I just found that it was possible in some cases (if they were containing/decontaining the item).

**Comment by itchyOwl** [comment] 2020-10-21 09:08
Removed the networking label, as it's reported to happen in single player campaign.

**Comment by FLundin** [comment] 2020-10-31 16:10
Well I have the 10 min video, cant upload it as it will take me a entire day but I can stream. i can rewatch it myself first to try to see if there is anything but i think what itchyowl said could be so. the AI could have taken the suit off me somehow thinking it was still in the locker

**Comment by FLundin** [comment] 2020-10-31 16:21
Ok so I got something (As this was during the bots can not change their oxygen bottle bug time) I encountered a bot that was walking back and forth in the same location (characteristic behavior when they had a oxygen bottle bug issue that was about to happen) so i stunned the bot with the stun baton, as I was about to go outside i decided to keep the bots suit instead of getting my own ( just fitting the suit with a new bottle) and then i went for a mining/artifact extraction expedition. So around 2 mins after i did the action of taking the suit off the bot, (been outside mining,) the bug occurred.

**Comment by itchyOwl** [comment] 2020-11-11 16:24
Sounds like it could be the bot then. Let's keep the ticket open for a while and if we get no more reports about this, we can close it later.

**Comment by Rokvach** [comment] 2020-12-14 10:13
Haven't seen this happening nor mentioned anywhere else, seems to be working. Closing.

**Closed by Rokvach** 2020-12-14 10:13 UTC
Labels: Bug, Code, Needs testing

**Comment by VineFynn** [comment] 2022-03-23 10:29
Had a friend report the same problem, AI took his diving suit off of him after reporting that it needed one.
