### ISSUE TITLE
Weird collision box at endgame (single player)

### ISSUE THREAD

**Issue by lukjackson** [Regalis11/Barotrauma#12200] opened 2023-06-20 08:42 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

As starting the last stage in endgame, where i need to destroy plylon and kill jove, I found that my submarine have weird invisible floor appear of nowhere, which block entrances (hatch), ladder unusable. The invisible floor is indestructable and appear to be a long flat piece of horizontal wall.

Here is the save file and the video
[Europa 0 - Copy.zip](https://github.com/Regalis11/Barotrauma/files/11797778/Europa.0.-.Copy.zip)

https://github.com/Regalis11/Barotrauma/assets/74778693/e2b2b962-95bf-4656-ada3-2ca7b2599d60

### Reproduction steps

1. Dive to endgame
2. start
3. done

### Bug prevalence

Just once

### Version

v1.0.20.1

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
no error debug
```

**Comment by BRSaura** [comment] 2023-06-29 21:36
Exact same issue here, looks like the floor is pass through if you ragdoll, like a platform, but it's stuck to the ship, neither teleporting it or moving will move the collision floor, and bots get stuck permanently.

**Comment by giists** [comment] 2023-07-03 09:30
Reproduction steps confirmed.

**Comment by Regalis11** [comment] 2023-07-04 13:13
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/642d0ec5d80287c9f5bb4c1260dff1d8d821298a (commit in our private repo)

**Comment by giists** [comment] 2023-07-25 08:14
No more issues, closing.

**Closed by giists** 2023-07-25 08:14 UTC
Labels: Bug, Code
