### ISSUE TITLE
Sudden Savefile Crashing

### ISSUE THREAD

**Issue by Mattoz7** [Regalis11/Barotrauma#3559] opened 2020-08-14 03:13 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The bug crashed my savefile completely after I tried to reenter a colony.

**Steps To Reproduce**
I realised I forgot to buy something, but had already started a mission. I didn't know going back in the colony would automatically fail the mission, so I went to click retry in the hopes it would reset before I went into the colony and try and do the mission without what I needed, and then my game crashed, and the savefile has become unplayable.

**Version**
I'm using windows 10, and Game version 0.10.4.0 (ReleaseWindows, branch release, revision 20132d25fb)

**Additional information**
N/A

**Comment by Mattoz7** [comment] 2020-08-14 03:13
I have a crash report, where do I put it?

**Comment by itchyOwl** [comment] 2020-08-14 08:26
Thanks for reporting! Upload it here as an attachment. Without it, it might be difficult/next to impossible to know what's going on.

**Comment by Mattoz7** [comment] 2020-08-14 19:53
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/5076889/crashreport.log)

Let me know if I have attached it correctly! This is my first time ever using GitHub, so I'm not 100% what I am doing! I just really, really want to see Barotrauma succeed! Thank you.

**Comment by Regalis11** [comment] 2020-08-17 09:07
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a57a05d545cf0e90fb0ccf1d86bc5186e0d55732

**Comment by Regalis11** [comment] 2020-08-17 09:11
Oh, and looks like there was already an existing ticket about this. Closing as a duplicate of #3494

**Closed by Regalis11** 2020-08-17 09:11 UTC
Labels: Bug, Code, Crash
