### ISSUE TITLE
Rope snaps when ragdolled in multiplayer while won't snap in singleplayer

### ISSUE THREAD

**Issue by iridescent-lightning** [Regalis11/Barotrauma#11897] opened 2023-04-23 12:42 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The rope isn't supposed to snap even when the user is ragdolled.

### Reproduction steps

1. Start a multiplayer
2. Shoot harpoon.
3. Into ragdolled mode.
4. Watch the rope snaps.

### Bug prevalence

Happens every time I play

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
none
```

**Comment by itchyOwl** [comment] 2023-04-24 06:40
Duplicate of #11726?

**Comment by Regalis11** [comment] 2023-04-24 09:12
Does not seem to be the same issue as https://github.com/Regalis11/Barotrauma/issues/11726. Looks like this happens because the rope is set to snap when the user stops aiming, and apparently it's possible to aim while ragdolled client-side but not server-side.

**Comment by Rokvach** [comment] 2023-05-23 11:36
Tested, working correctly. Can be merged and closed.

**Closed** 2023-05-23 11:50 UTC
Labels: Bug, Code, Networking
