### ISSUE TITLE
Power issues on Orca2

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#8486] opened 2022-03-08 15:10 UTC
Orca2 can't handle the power load. Didn't do that (at least not as much) before the power-rework. Possibly affects other subs too.

Steps:
1. Turn the reactor and the sonar on.
2. Wait.
3. If all the systems work ok, set the autopilot to navigate to the destination or try steering manually.

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/5a5c1a67-39cf-4bcd-ac62-a3db393b3548)

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/66a5c872-6be1-455e-8902-24945c9209a4)

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/4659bbcd-4acd-422e-afc7-8475124def4e)

Version 0.17 (dev)

**Comment by Tsunder** [comment] 2022-03-09 20:30
in the images provided, this is due ot the reactor only having 1 Fuel Rod (1 uranium, 80 heat) worth of fuel, which is only sufficient to sustain a turbine rate of max 80-85% reactor max.

however, I believe it's been mentioned before that the orca2 has a notably weak reactor compared to other subs, due to having battery chargers.

+ all vanilla subs got their baseline loads increased from having diving lockers/o2 tank shelves getting wired up.

**Comment by Tsunder** [comment] 2022-03-09 20:32
re: images: 3rd image shows reactor fissioning at a surprisingly low rate (near optiomal/minimal temperature, visually) for automatic control

**Comment by Torca2001** [comment] 2022-03-10 10:55
Haha oops forgot I touched the auto reactor and wasn't meant to leave that in the PR,
Line 290 [Reactor.cs](https://github.com/Regalis11/Barotrauma/blob/dev/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Machines/Reactor.cs#L290) in Shared Source
`UpdateAutoTemp(10.0f, deltaTime * 2f);`
Revert this line back to
`UpdateAutoTemp(2.0f, deltaTime);`
The issue is caused by the auto reactor responding too quickly.

**Comment by itchyOwl** [comment] 2022-03-10 14:56
All the vanilla subs should function with one fuel rod. Similar issues on Dugong too. Turning the batteries off fixes it, unlike on Orca2.

**Comment by itchyOwl** [comment] 2022-03-10 15:07
Tested reverting that. Seems to help a bit, but doesn't get rid of the issue entirely. Why did you multily deltaTime in the first place? I'm not familar with the code here, but it doesn't seem a correct thing to do.

**Comment by Tsunder** [comment] 2022-03-10 18:40
> All the vanilla subs should function with one fuel rod. 

They do function with 1 fuel rod... until load exceeds 85% of reactor max, at which the 1U will drop effective output to around ${math}.

Exceeding that 85% is very possible lately with wired up o2 refillers and supercap changes. On the case of orca2, that's 7 * (10+30) = 280, which is an additional 8% of reactor max.

besides, 2k / 3.3k is still about 60% voltage, enough for minimal voltage on everything, so I think there's something else causing the brownouting in the screenshots. 


me doing max forward thrust (manual mode) w/ 1U: 2k power / 3.7k load = 0.54 voltage, no brownouts...
but if one were to use the ballasts as well (i.e., ascend/descend), worth 900 load ( 25%) that can hit > 4k momentarily, which is >= 2x the 2k power from 1U at max fission/turbine, causing complete brownout.

![image](https://user-images.githubusercontent.com/5103517/157729959-db9d8b4d-d555-45a8-9e23-1a2d6d4d1806.png)




Part of the apparent power weakness I think is that in all(?) vanilla subs, supercaps and batteries require charging at the start, which can put a great strain on the grid. It would be more stable to set batteries/supercaps to be fully/near charged at start.

In the orca2 for example, the 2 supercaps start empty and are set to recharge at 400 each, which is 800 extra load (22% reactor max)


---

I notice the dugong and humpback got slight increases in reactor max (perhaps compensating for the +200 load from o2 fillers, and a little extra for supercap changes?), perhaps the orca and azimuth should too?

**Comment by Tsunder** [comment] 2022-03-10 18:56
orca2 peaked at 4.3k load (without supercap/battery/fab going...) with full thrust + ballast pumps, which is 1.22x reactor max

battery: +1000
supercap: +2000
fabs: +1100
potential: +4100
overall: 8400 potential max load on a 3.5k reactor sub 

Not to mention increased power loads from damaged engines/pumps xd

**Comment by Torca2001** [comment] 2022-03-10 22:26
> Tested reverting that. Seems to help a bit, but doesn't get rid of the issue entirely. Why did you multiply deltaTime in the first place? I'm not familar with the code here, but it doesn't seem a correct thing to do.

That function has two arguments one being speed and other being delta time, when I was messing with it I found adjusting the speed doesnt really affect auto reactor that much, and only found it to move the fission rate quicker if you messed with delta time.
I was trying to slightly buff the auto reactor since I had increased the update rate of power calculations from 5 ups to 60, this meant that the reactor no longer had the 0.2s delay between load changes to adjust its output and hence the auto reactor has a hard time responding to changes at all.

**Comment by Regalis11** [comment] 2022-03-14 10:07
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/229d5447bcc8cd442e28963102c32a8afa8f19ea

**Comment by Tsunder** [comment] 2022-03-17 18:02
At which point one would turn on the batteries!

I understood it was the intended gameplay as the humpback's
description mentions the backup battery array.

Previously already somewhat possible by turning the fabs on. (+1.1k
total load on a 2.8k reactor (~40% reactor max))

**Comment by itchyOwl** [comment] 2022-03-18 09:43
No, I disagree. I think all the subs should work with the default settings _without stressing the systems_. And that's how they did work before the power refactor.

**Comment by Regalis11** [comment] 2022-03-18 13:55
Adjusted Humpback in https://github.com/Regalis11/Barotrauma-development/commit/d3e2490af3ac79c835543f0095fdc1ebe9860777

**Comment by Rokvach** [comment] 2022-03-31 09:10
Tested, no issues, closing.

**Closed by Rokvach** 2022-03-31 09:10 UTC
Labels: Bug, Code
