### ISSUE TITLE
Sporadic Mission Equality Check failed on docking to ports while having a mission

### ISSUE THREAD

**Issue by FantasticChimni** [Regalis11/Barotrauma#3819] opened 2020-09-13 03:02 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Whenever we would dock with a mission, any number from 1 to all of the non-host participants on the server would disconnect from the server with the pictured error log. This did not happen without a mission, and did not crash everyone, all the time. This never happened when undocking, only when docking to a station while currently on a mission. Have not tested going to a natural formation with a mission. We have also completed missions with no crash, thought it was fixed, then crashed the next round. Every player & Host have validated game files twice through the session. Disconnect still occurred.

We have used the current setup on the same save file 5+ times before now with no issues. Two of our players live in the same house with the same IP address, either one, or both would crash when this is happening. 

**Steps To Reproduce**
Have crew on station, accept mission, undock with mission, either complete mission and dock in destination, or redock at issuing station. any number of non-host participants crash from the server with the attached picture error.

**Version**
Host & Clients both on Win10 Home
Barotrauma v0.10.4.0, current stable on steam

**Additional information**
https://i.imgur.com/mvnaWYl.png
Picture of error on players console

**Comment by Regalis11** [comment] 2022-09-19 09:56
Potentially related to or caused by https://github.com/regalis11/barotrauma/issues/9881

**Comment by Rokvach** [comment] 2022-09-27 10:05
Closing as there was no issues on the related ticket

**Closed by Rokvach** 2022-09-27 10:05 UTC
Labels: Bug, Needs testing, Code, Networking, Medium Prio, Unstable
