### ISSUE TITLE
Crash after assigning repairs to mechanic on workshop submarine

### ISSUE THREAD

**Issue by NRGunne** [Regalis11/Barotrauma#4174] opened 2020-10-30 18:18 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
After a recent update some time after beginning a mission with assigning at least one AI-mechanic to repair mechanical systems I always get a crash with a report (see three attached files). It happens on the steam workshop submarine "Flashlight Fish". If I don't assign an AI-mechanic to repairs the crash doesn't happen.

**Steps To Reproduce**
1. Board the submarine and begin a mission.
2. Assign at least one mechanic to repair mechanical systems.
3. Wait some time until the mechanic begin repairs (considering the crash reports the crash may relate to deconstructor or fabricator).

**Version**
I got the crash on version "0.10.6.2 (ReleaseWindows, branch release, revision d0702df35e)".

**Additional information**
https://steamcommunity.com/sharedfiles/filedetails/?id=2266482549
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/5466875/crashreport.log)
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/5466876/crashreport.2.log)
[crashreport (3).log](https://github.com/Regalis11/Barotrauma/files/5466874/crashreport.3.log)

**Comment by NRGunne** [comment] 2020-10-30 18:25
#4160 may be related (after I checked the stack trace)

**Comment by Regalis11** [comment] 2020-11-02 11:20
Yep, seems to have been caused by the same bug as https://github.com/Regalis11/Barotrauma/issues/4160. Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/37c86a770d5e46c91bc63522aa4cab482ea890a0

**Comment by Rokvach** [comment] 2020-11-02 12:10
Already tested, working correctly. Closing.

**Closed by Rokvach** 2020-11-02 12:10 UTC
Labels: Bug, Code, Crash
