### ISSUE TITLE
Sonar Hitbox Below Actual Sprite

### ISSUE THREAD

**Issue by B1G-FUNGUS** [Regalis11/Barotrauma#5916] opened 2021-05-28 19:18 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The sonar monitor's hitbox (maybe that's the wrong technical term, but area where you click to access it) is slightly lower then the actual sprite. The same bug exists for both the sonar monitor and navigation terminal.
![image](https://user-images.githubusercontent.com/80074584/120032193-acd83f80-bfae-11eb-8c8c-862f990d870d.png)

**Steps To Reproduce**
Go into the sub builder and place down a sonar monitor, and clicking on it will show the bugged hitbox. This can also be demonstrated in game, as clicking on an item below the sonar monitor will sometimes open the monitor up. Usually this isn't very noticeable, but sometimes it does get in the way. 

**Version**
Barotrauma v0.13.3.11 (ReleaseLinux, branch release, revision 7096536cf1)
(Image in case I made a mistake typing it out)
![2021-05-28_115810](https://user-images.githubusercontent.com/80074584/120030188-ff642c80-bfab-11eb-88c7-d6802f104c2c.png)

**Comment by Tsunder** [comment] 2021-05-28 19:31
i look forward to every other ship's sprite positions breaking

**Comment by Regalis11** [comment] 2021-05-31 06:56
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3195

**Closed by Regalis11** 2021-05-31 06:56 UTC

**Comment by B1G-FUNGUS** [comment] 2021-06-01 04:35
Sorry, thought I had done a good enough search, but I guess not. Will do better in the future!
