### ISSUE TITLE
[0.15.9.0] Outpost Ladder Character Looping Nonsense

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#6973] opened 2021-10-21 11:08 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Outpost NPC and Crew Members are just going up and down the ladder in this outpost.
[OutpostLadderSave.zip](https://github.com/Regalis11/Barotrauma/files/7388433/OutpostLadderSave.zip)

![OutpostLadder](https://user-images.githubusercontent.com/5086682/138267707-2426f423-a9b5-4aad-b32a-c9fb1d04c93e.gif)

**Steps To Reproduce**
Load the save provided and observe the shaft above the main hall in the outpost after a bit.

**Version**
0.15.9.0

**Comment by itchyOwl** [comment] 2021-11-01 10:53
Fixed in Regalis11/Barotrauma-development@cf1b117. Caused by two old issues in the code that made the bot accept a new path while climbing the ladders. The waypoint generation changes might have affected it, since the issue only seems to happen in vertical hallways, which now have more(?) waypoints than they used to.

**Comment by Rokvach** [comment] 2021-11-01 13:37
Tested, working correctly. Closing.

**Closed by Rokvach** 2021-11-01 13:37 UTC
Labels: Bug, Code
