### ISSUE TITLE
Cannot Launch Barotrauma

### ISSUE THREAD

**Issue by StoneHeartSteamUser** [Regalis11/Barotrauma#340] opened 2018-03-24 18:43 UTC
[UPDATE]
I Updated the game Opened The Newest "Launcher" it opened
I selected Vanilla 8V Content Pack Pressed Start
Then "BaroTrauma.Exe Is Not Responding" 
The Update Seemed To Break The Game
Because it Worked In The Earlier Verison.

**Comment by StoneHeartSteamUser** [comment] 2018-03-26 13:36
SomeOne Please Help me.

**Comment by Regalis11** [comment] 2018-03-26 13:39
Have you tried redownloading the game from the official website or launching Barotrauma.exe directly (instead of using the launcher)?

**Comment by StoneHeartSteamUser** [comment] 2018-03-26 21:51
Yes Now It Dosen't even Open....

**Comment by StoneHeartSteamUser** [comment] 2018-03-26 21:54
It was working fine before i updated it.

**Comment by juanjp600** [comment] 2018-03-26 22:40
May be caused by mismatching .NET Framework version configurations for the libraries we're using, I'll see what happens if I switch them all to the same version.

**Comment by StoneHeartSteamUser** [comment] 2018-03-27 00:32
Alright im a lil dusty with coding give me a list on what files to delete. Ill let you know if it works once i get the list.

**Comment by StoneHeartSteamUser** [comment] 2018-03-27 00:33
Also Links To What I Need Please.

**Comment by juanjp600** [comment] 2018-03-27 00:50
.NET Framework 4.0: https://www.microsoft.com/en-US/Download/details.aspx?id=17718
.NET Framework 4.5: https://www.microsoft.com/en-us/download/details.aspx?id=30653

4.5 should be the only version you need. If the game continues to fail to open, I've already pushed an attempted fix for the next update. Sorry for the inconvenience.

**Comment by StoneHeartSteamUser** [comment] 2018-03-27 02:26
Its Fine This Game Is Old And Ive Loved It Ever Since It Was Play Able I Would Pay Around 25$ For a Game Like This But Any Way Thank You For Your Time And Keep Up The Great Work Id Love To See More Games Like This!

**Comment by StoneHeartSteamUser** [comment] 2018-03-27 11:14
Just tryed it and my computer says i already have it ive now downloaded 3.5 just incase im getting ready to launch it now.

**Comment by StoneHeartSteamUser** [comment] 2018-03-27 11:50
I got it updated now It doesn't work anymore.
I think my computer didn't download the source code of the update can I have a link to download the codes of the update?

**Comment by Regalis11** [comment] 2018-05-24 19:17
Duplicate of #422 I think?

**Closed by Regalis11** 2018-05-24 19:17 UTC
Labels: bug
