### ISSUE TITLE
[Factions] Players get error message when trying to join servers mid-round which disconnects them from the server

### ISSUE THREAD

**Issue by Wheatley1002** [Regalis11/Barotrauma#10971] opened 2023-01-19 10:31 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### Key Information
Game mode: Campaign
Game type: Multiplayer
Campaign save version: Started in 100.13.0.0, issue occurred in version 100.13.0.0
Server type: Steam P2P

### Issue Report
Players attempting to join the game whilst a round is in process are met with an error message and are disconnected from the server. This error does not appear if they join mid-transition (like from round end to the next area). 

![image](https://user-images.githubusercontent.com/120612589/213419225-41970e30-c289-45dc-86cf-17be922e02a4.png)
_Figure 1. Error message_

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-01-19 11:01
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10872, fixed in v100.14.0.0

**Closed by Regalis11** 2023-01-19 11:01 UTC
