### ISSUE TITLE
Rechoosing Paths from Natural Formations to Natural Formations removes Hired Crew.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3614] opened 2020-08-22 19:33 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you're at a Natural Formation and you hit the Enter Location button at the top at the start of the level to repick the route, it deletes all Hired Crew members.

**Steps To Reproduce**
1. Get to a Natural Formation.
2. At the start of the level, Press Enter Location.
3. Choose another location preferably to another Natural Formation.
4. Close the server, restart it, and reload the save.

**Version**
0.10.4.0

**Comment by Regalis11** [comment] 2020-08-27 13:08
Could not reproduce

**Comment by Regalis11** [comment] 2020-08-27 14:45
Here are the steps that I used to repro this:
1. Enter a level between two natural formations
2. Quit and reload the save (returning to the lobby and pressing "continue campaign" is enough)
3. While initializing the round, the server will save the game and cause the save to get messed up: the sub is registered as being _in_ a natural formation level, even though they can't be entered.
4. Quit and reload again. The game should load an outpost level with no outpost and force you to the map view. The bots are also gone now.

**Comment by Kaillera** [comment] 2020-08-27 14:47
That sounds a lot like what happened yes.

**Comment by Kaillera** [comment] 2020-08-27 15:04
Actually now that I think about it as well, there are times when you reload saves from a crash starting the next level or gameover in the level, sometimes you're put back into the outpost, which I think causes the same issues.

**Comment by Regalis11** [comment] 2020-08-28 08:51
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a810d782696688a80633c002183df577cd30902a

**Comment by Rokvach** [comment] 2020-09-07 11:31
Wasn't able to reproduce the issue, looks to be working correctly. Closing.

**Closed by Rokvach** 2020-09-07 11:31 UTC
Labels: Bug, Code
