### ISSUE TITLE
Missing entity Barotrauma.Hull mass kick

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#2683] opened 2020-04-24 02:13 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Reactor was overloading and bunch of people got kicked.
https://streamable.com/g6lwk0

**Version**
0.9.9.0

**Comment by thegrb93** [comment] 2020-04-24 02:21
For some reason throughout that whole round, that same entity id was kicking people.

**Comment by Regalis11** [comment] 2020-04-25 14:08
Potentially fixed in https://github.com/Regalis11/Barotrauma-development/commit/90634d22e45cc0ae15430005e36a65fb9c6ac279

**Comment by Rokvach** [comment] 2020-04-27 10:23
Unstable tests shows that this should be working correctly now, there might still be some desyncs but a lot less frequently and not in a mass desync level as the current stable version has them. Closing.

**Closed by Rokvach** 2020-04-27 10:23 UTC
Labels: Bug, Code, Needs testing, Networking

**Comment by charliefoxtwo** [comment] 2020-08-17 05:07
Just had this same issue earlier today. We tried the same mission twice and received the error both times. After this I was unable to continue the campaign in the currently lobby. I rehosted, and after choosing a different mission in the campaign all of my AI crew members disappeared. Not really sure what the root cause is, but this doesn't appear to be fixed and there might be something deeper going on here.
