### ISSUE TITLE
Character forced to ragdoll in multiplayer

### ISSUE THREAD

**Issue by BarSuka** [Regalis11/Barotrauma#12494] opened 2023-08-12 20:24 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

1.When I enter the station, almost all NPCs  are on their knees and shaking. You can't talk to them, but you can trade or heal them. 2.When docking at a large colony, my character stands still and cannot move two meters because he is pulled back to the spawn point. 
3.And when undocking from the station, my character starts ragdolling and cannot interact with anything. This begins either immediately after undocking, or after an electric shock when repairing / hitting a door, etc.

### Reproduction steps

1. Start multiplayer campaing
2. Spawn at start station
3. Done (First part)
4. Undock from station
5. Done (Third part)
6. If everything is still fine, dock to the colony
7. Done (First&second part)

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted using a dedicated server

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-08-13 09:57
Thank you for the report! We haven't encountered this bug ourselves, so I think it must require some specific circumstances to occur (just starting an MP campaign round in a fresh install does not seem to cause this). To be sure, you're not using any kind of mods?

**Comment by BarSuka** [comment] 2023-08-13 13:59
No. no mods installed. And it looks like the bug only appears in multiplayer. It didn't happen in singleplayer.

**Comment by Vykn** [comment] 2023-08-14 08:19
#12276 
Same issue.

**Comment by Regalis11** [comment] 2023-08-14 12:12
Duplicate of https://github.com/Regalis11/Barotrauma/issues/12276

**Closed by Regalis11** 2023-08-14 12:12 UTC
Labels: Bug, Need more info, Code, Networking
