### ISSUE TITLE
Minimum sized gaps only gap up/down, can't gap side/side

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6964] opened 2021-10-20 08:49 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
a minimum sized gap (1 grid snap, 16 x 16 units) only gaps hulls that are above/below, and can not connect gaps left/right

**Steps To Reproduce**
1. make a minimal sized gap

**Version**
0.1500.9, 0.14.9, and before

**Additional information**
There is some other similar issues with i think gaps of minimum width or height with similar behaviour.

**Comment by Regalis11** [comment] 2021-10-21 07:13
Duplicate of https://github.com/Regalis11/Barotrauma/issues/5247

**Closed by Regalis11** 2021-10-21 07:13 UTC
