### ISSUE TITLE
Junction fire at the start of the round

### ISSUE THREAD

**Issue by the1eyedduck** [Regalis11/Barotrauma#5957] opened 2021-06-01 22:54 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Sometime when start a new level in nature formation, junction box will start breaking from overvoltage and create fire, usually with sub with poor junction like typhon2 or some custom subs.

**Steps To Reproduce**
start/load into a nature formation, there is a chance (maybe it's something to do with high power useage before load into new level?) and junction will start breaking from over voltage.

**Version**
0.1400.2.0
**Additional information**
Likely cause from the previous unstable patch to reactor "Reset reactor fission rate, turbine output and temperature to optimal levels at the start of a round. Prevents the reactor from catching fire at the start of a round if it was being operated at a high fission rate at the end of the previous round."

**Comment by dmeff** [comment] 2021-06-11 21:07
I've found this too

**Comment by gerbilOFdoom** [comment] 2021-11-04 19:46
I can confirm I've had this issue, except in my case the reactor exploded. I loaded into the game to a respawn menu, and apparently the others in my game had loaded in before me. I suspect the game runs in the background while the loading screens are visible, while components of the ship are still in a state of limbo. My reactor is controlled by a circuit network, so heat output may have been set to 100 at the exact moment of transition, causing this bug to become more apparent as the circuit network was unable to drop the output to 0 as it does in normal function for quite some time during the transition. 

An easy fix might be to give all sub components, with HP, immunity while load screens are active after a level transition, and/or to disable their function entirely during that time. Better fix might be to pause the game world from running while everything gets loaded in for the server.

**Comment by gerbilOFdoom** [comment] 2021-11-05 05:13
https://github.com/Regalis11/Barotrauma/blob/a49decc2edcf440c6a9f5dd3e1e08cda9bd8b790/Barotrauma/BarotraumaShared/SharedSource/Map/Submarine.cs#L1132

If we look here, the sub's power is run during the loading sequence to ensure power systems have already run 600? time steps forward before loading is done. This code runs all powered items, but ignores the signal components that may instead run those items. 

Unless these 600 steps account for a minimal amount of time (under a second), this would likely be enough to blow up a few components. Assuming this is the cause of the issue, it might be resolved by wrapping the following code around the line at the link, which will (I believe) set the condition of whatever was "warmed up" back to what it was before the item was updated, thus preventing degradation. 

@Regalis11 does this look like a workable solution to you? I also wrote out everything needed to also perform an Update on all relevant signal components before I thought to simply retain the condition outside of the update process, but haven't included it because it is a downright silly solution that may best be resolved by simply making all Signal components extend a stub interface that identifies them as signal components, thus allowing a simple check around the lines I've linked to.

```
float oldCondition = item.Condition;
https://github.com/Regalis11/Barotrauma/blob/a49decc2edcf440c6a9f5dd3e1e08cda9bd8b790/Barotrauma/BarotraumaShared/SharedSource/Map/Submarine.cs#L1140
item.Condition = oldCondition;
```

**Comment by Regalis11** [comment] 2021-11-09 17:43
@gerbilOFdoom Thank you for taking the time to investigate this! It didn't even occur to me that the "warm start" logic could've been the cause, but now that you mentioned it, I'm pretty sure that's where the problem is. 

The proposed solution would probably fix the majority of issues, but I think it has some flaws: if the reactor is controlled by some custom circuit, running those power updates wouldn't achieve the intended effect of starting the sub "already powered up", and the reactor might still be in an invalid state at the end of those updates (e.g. output set too high). Some powered items might also for example have status effects that react to overloads somehow, even if we manually prevented the items from breaking.

I'll take a closer look at this tomorrow and try to figure out a more robust solution to this. I think the simplest way to go might be to get rid of this warm start logic altogether and make sure all the necessary power-related values are saved at the end of the round so the state of the power grid would stay unchanged between rounds without the need for "warming it up" like this.

**Comment by Regalis11** [comment] 2021-11-10 09:26
Hopefully fixed in https://github.com/Regalis11/Barotrauma-development/commit/d1fc12946e443269e422b51909c8079e4cbc24b9

**Comment by Rokvach** [comment] 2021-12-09 10:59
I haven't seen this happening since the fix was introduced to the Unstable, also this hasn't caused any new issue so I think this is working correctly. Closing.

**Closed by Rokvach** 2021-12-09 10:59 UTC
Labels: Bug, Code
