### ISSUE TITLE
Doors/hatches with itegrated buttons hard to interact with when they are closed and you are outside in the water

### ISSUE THREAD

**Issue by Maunaator** [Regalis11/Barotrauma#5043] opened 2021-02-12 15:55 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When using doors or hatches with integrated buttons as outter airlock doors they are hard to interact with when they are closed and you are outside in the water.

![screen](https://user-images.githubusercontent.com/78967619/107781278-64bf4500-6d50-11eb-9fbe-d8365a21ac6f.png)

Here on the left the door could only be toggled by "hugging" it and searching for a spot. On the right it preferably gives interaction with the ladder (as in the picture) and then you need to hug the hatch to be able to toggle it.

**Steps To Reproduce**
Try it on provided sub or make such airlock. Tweak autopilot untill ballast steadies otherwise the sub presses you against the hatch and it gives the interaction easily. When you close the door/hatch interupt the interaction highlight from that before atempting to open the door/hatch. 

[Neptune_test.zip](https://github.com/Regalis11/Barotrauma/files/5972740/Neptune_test.zip)

**Aditional Information**
A workaraund is to add a button on top of the integrated one on the problematic side that toggles the door, but that kinda defeats the purpose of the integrated buttons.

![screen2](https://user-images.githubusercontent.com/78967619/107790340-575b8800-6d5b-11eb-93b6-a6a53c195090.png)

I´d prefer if the integrated button panel was given higher interaction priority and from farther away.

These doors work well with bots and that is why I am using them rather than a airlock with doors with seperate buttons.

**Version**
v.0.12.0.2 / Windows 10

**Comment by Regalis11** [comment] 2021-02-14 12:43
Duplicate of https://github.com/Regalis11/Barotrauma/issues/2684

**Closed by Regalis11** 2021-02-14 12:43 UTC
