### ISSUE TITLE
"Save and Quit" button saves your character mid round

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5774] opened 2021-05-12 22:55 UTC
- [yes ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The save and quit button we have in campaign saves the mid-round stats of all characters, meaning that if you save and quit as your whole crew is unconscious, instead of spawning with the stats they had at the start of the round (like everything else), they'll spawn unconscious and you can no longer use that save without editing it from the code or cheating.

**Steps To Reproduce**
Make 1 or more characters unconscious, save and quit, open save (This happened to me in singleplayer but i believe it happens in multiplayer too).

**Version**
Unstable v0.1400.0.0 Windows

**Comment by Regalis11** [comment] 2021-05-13 13:41
This is not a bug nor something new to the latest unstable build: you can save mid-round in outpost levels. However, I don't think we considered the implications of saving when your crew is unconscious or lethally injured: that's definitely something we need to address somehow.

**Comment by ezjamsen** [comment] 2021-06-08 08:56
Let's add a warning before saving when all crew are in bad shape, letting the player know that they are potentially going to create a very difficult situation for themselves. This is such an edge case that more action than this is probably not worth the work required.

**Comment by Regalis11** [comment] 2023-03-10 10:03
We're cleaning up some low-prio/unreproducible/irrelevant/outdated tickets from the issue tracker, and this is one of the tickets we chose to axe. Closing.

**Closed by Regalis11** 2023-03-10 10:03 UTC
Labels: Code, Design
