### ISSUE TITLE
[0.10.503] Multiplayer(?) - Fabricator pulling and dropping materials for the last items being created in the previous round

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3779] opened 2020-09-08 22:59 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Not sure if it's Multiplayer specific but, Fabricators are pulling and dropping materials on the ground for the last items that were crafting in the previous round.

**Steps To Reproduce**
I'm not sure if linked cabinets are neccessary but my setup has it currently.
Load linked cabinet with several Bandages and Elastins.
Craft Plastiseal.
Half way to finishing that plastiseal. dock to outpost/enter next level.
You should see a finished plastiseal in the fabricator, and as well as a set of bandage and elastin on the floor at the fabricator.

**Version**
0.10.503

**Comment by Regalis11** [comment] 2020-09-09 07:51
Does not seem to be multiplayer-specific: this happens when the fabricator is linked to a container that has materials for fabricating the item. The cause was that the Fabricator component would be loaded from the save before the ItemContainer component, meaning that the fabrication would start and pull the materials from the linked container because the input inventory is still empty at that point, and after that the input inventory would be loaded and the item that was supposed to be inside it would drop because the slot was already taken.

Fixed in https://github.com/Regalis11/Barotrauma-development/commit/fcfeabf20528d2b253e8283bf788ea75acb8d87f

**Comment by Rokvach** [comment] 2020-09-09 08:23
Tested, working correctly. Closing.

**Closed by Rokvach** 2020-09-09 08:23 UTC
Labels: Bug, Code
