### ISSUE TITLE
Unable to unlink hull objects

### ISSUE THREAD

**Issue by j-morlen** [Regalis11/Barotrauma#3755] opened 2020-09-07 14:27 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Cannot un-link hull objects after being linked.

**Steps To Reproduce**
Link hull object and attempt to unlink by repeating process or using 'Space+Right-click' method.

**Version**
v0.10.4.0 (Windows)

**Additional information**
I have searched the issue tracker and there is a closed ticket saying the solution is to right-click, however that does not work. I have consulted the discord's #baro-subs channel on how to un-link but with no resolution. For example, the attached picture is what happens when I do 'Space+Right-click'
![unknown](https://user-images.githubusercontent.com/70903258/92397242-5acb5300-f0db-11ea-8907-f18381bc017d.png)

**Comment by EtiamNullam** [comment] 2020-09-08 02:46
Looks like the problem is that you can link the same pair of hulls multiple times (by pressing `space+left mouse button`) so when you want to unlink you have to press `space+right mouse button` the same amount of times you linked it in the first place.

**Comment by Regalis11** [comment] 2020-09-08 08:31
Linking the hulls to each other multiple times was the only way I was able to reproduce this, so I suspect that was the cause. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d13b23920ef307d433c9e3d63ca08165e596d6c8

**Comment by Rokvach** [comment] 2020-09-09 08:41
Tested, working correctly. Closing.

**Closed by Rokvach** 2020-09-09 08:41 UTC
Labels: Bug, Code
