### ISSUE TITLE
[0.1400.5.0] adding switch to turret hardpoint SET_light allows hardpoint to be selected when empty

### ISSUE THREAD

**Issue by LordFrith** [Regalis11/Barotrauma#6067] opened 2021-06-15 01:58 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

i have submarine where weapon turret lights are controlled by an on/off switch

if a switch is connected to Turret Hardpoint Base SET_Light then the empty hardpoint shows up in turret order UI, bots can be ordered onto empty periscope base/hardpoint base

**Steps To Reproduce**

open dugong in subeditor, add a switch and wire it to empty hardpoint  SET_light

start test level. the empty hardpoint will now show in the orders menu (operate weapons)

**Version**
unstable [0.1400.5.0], windows 10

**Additional information**

**Comment by ekqvist** [comment] 2021-06-15 10:00
Should be fixed with Regalis11/Barotrauma-development@778d922. Committed to the dev branch for now.

But basically, the bug would happen because when we look for order targets, we look for turrets with items with controller components that are connected to them. The blank periscope doesn't have a controller component, but if something like a switch is wired to the hardpoint, it would cause the hardpoint to appear in the order target selection and the bots naturally wouldn't know what to do with the order.

**Comment by ekqvist** [comment] 2021-06-15 10:01
Also, thank you very much for the detailed report, @LordFrith! The issue was easy to reproduce with the steps you provided.

**Comment by Rokvach** [comment] 2021-06-22 06:53
Tested, working correctly. Closing.

**Closed by Rokvach** 2021-06-22 06:53 UTC
Labels: Bug, Code
