### ISSUE TITLE
NRE in RangedWeapon

### ISSUE THREAD

**Issue by MattNies** [Regalis11/Barotrauma#7136] opened 2021-11-02 05:53 UTC
https://github.com/Regalis11/Barotrauma/blob/a52a23f8c24a6fa5562057124664c58212437e58/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Holdable/RangedWeapon.cs#L78

[crashreport.log](https://github.com/Regalis11/Barotrauma/files/7458150/crashreport.log)

**Comment by Regalis11** [comment] 2021-11-02 08:04
Duplicate of #7020

**Closed by Regalis11** 2021-11-02 08:04 UTC
