### ISSUE TITLE
Tried to open submarine status pda outside of sub, swimmng. Not sure if that was a reason.

### ISSUE THREAD

**Issue by SoNickRND** [Regalis11/Barotrauma#7674] opened 2021-12-08 14:13 UTC
Sorry for stub report.

Tried to open sub remote status pda outside of sub, swimmng. Not sure if that was a reason.

![baro_610ee0dc1d835cf74919e737c603fc44](https://user-images.githubusercontent.com/125238/145222505-af12df25-e070-444f-afdb-7af988973881.jpg
[crashreport_2021-12-08.log](https://github.com/Regalis11/Barotrauma/files/7676572/crashreport_2021-12-08.log)
)

**Comment by Regalis11** [comment] 2021-12-08 14:51
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7279, fixed in the unstable version (and the fix is coming up soon to the public version)

**Closed by Regalis11** 2021-12-08 14:51 UTC
