### ISSUE TITLE
No sounds or visible effects are created when another player fires a revolver in multiplayer

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#295] opened 2018-02-27 05:18 UTC
Version 0.8.0.4 (Vanilla)

when firing the revolver in multiplyer no audible sound, flash or effect is displayed to other clients as a client. not sure on how it works with the host.

**Comment by Regalis11** [comment] 2018-02-28 12:11
The effects seem to work every now and then (still very unreliably). I'm pretty sure this is caused by the revolver round removal message arriving to the clients before they've processed the input for firing the revolver. A dirty (but easy) workaround would be to delay removing projectiles for a second or so at the server's side, but I'll try to think of a more robust solution because this same problem (network events and inputs not being processed in the correct order) could potentially cause other bugs as well.

**Comment by NilanthAnimosus** [comment] 2018-02-28 13:28
If events are not being processed in the correct order that might be the cause of object header problems with husks that I've found the best fix is often to simply delay character deletions under the end of a round. that sounds like a fairly significant problem for the entity spawner if it so much as spawns a new character before its removed one etc

**Comment by Regalis11** [comment] 2018-02-28 13:44
Network events are processed in the correct order, so things like spawning a new character before another one is removed should not happen. The character inputs however are not tied to the event system.

**Comment by Regalis11** [comment] 2018-11-05 10:57
May have been fixed by 224e923

**Comment by Rokvach** [comment] 2019-07-20 23:27
This issue has already been fixed, closing.

**Closed by Rokvach** 2019-07-20 23:27 UTC
Labels: Bug, Code, Networking-related
