### ISSUE TITLE
Banning a player bans all players

### ISSUE THREAD

**Issue by OverwatchVoice** [Regalis11/Barotrauma#4060] opened 2020-10-11 20:09 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When a player has been banned, it bans all other players on the server as well. The banlist, however, only has the entry for the single person that was the target of the ban. Kicking people does _not_ have the same effect.

**Steps To Reproduce**
Self-explanatory

**Version**
Barotrauma ver. 0.10.5.1    Win10 build 1903

**Comment by Regalis11** [comment] 2020-10-12 10:19
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3895

**Closed by Regalis11** 2020-10-12 10:19 UTC
Labels: Bug, Code, Networking
