### ISSUE TITLE
Crashing on respawn, leaving outpost, arriving at outpost.

### ISSUE THREAD

**Issue by BarotramIIbugz** [Regalis11/Barotrauma#12731] opened 2023-09-29 14:56 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Every time I am on a hosted server, my game crashes on the loading screen of a transition. I still had this issue when I played multiplayer in the early access of Barotrauma. I also hear no audio whenever i am spectating a submarine but it could be a separate issue.

I have selected the version as the current one as it is still happening but I included 2 crash reports in order of date.

### Reproduction steps

1.Join a server via in-game menu
2.Respawn via shuttle and complete a mission
3.Game freezes for 2 minutes till I force quite the game
4.Crash report is displayed

### Bug prevalence

Every multiplayer game

### Single player or multiplayer?
Multiplayer hosted in-game

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

MAC OS

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 09/23/2023 18:02:58)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

289C10B7FC6DEE30FF3944E48BC96FCD

Game version 1.0.21.0 (ReleaseMac, branch release/summer-patch-hotfix, revision adb80ccd6e)
Graphics mode: 1440x900 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla (65E9331)
Level seed: Tectamus Linea
Loaded submarine: R-29 (DA86E7FDB37034CE2B9E12B2A4DC0B97)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)

System info:
    Operating system: Unix 13.0.0 64 bit
    GPU name: 
    Display mode: {Width:1440 Height:900 Format:Color AspectRatio:1.6}
    GPU status: Normal

Exception: Failed to set muffled buffer data for non-streamed audio! Invalid operation (System.Exception)
Target site: Void FillBuffers()
Stack trace: 
   at Barotrauma.Sounds.OggSound.FillBuffers() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sounds\OggSound.cs:line 121
   at Barotrauma.Sounds.SoundChannel..ctor(Sound sound, Single gain, Nullable`1 position, Single freqMult, Single near, Single far, String category, Boolean muffle) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sounds\SoundChannel.cs:line 86
   at Barotrauma.Sounds.Sound.Play(Nullable`1 position, Single gain, Single freqMult, Boolean muffle) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sounds\Sound.cs:line 101
   at Barotrauma.Items.Components.ItemComponent.PlaySound(ItemSound itemSound, Vector2 position) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\ItemComponent.cs:line 385
   at Barotrauma.Items.Components.ItemComponent.PlaySound(ActionType type, Character user) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\ItemComponent.cs:line 342
   at Barotrauma.Item.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 2075
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 610
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 248
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 884
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[09/23/2023 18:02:58] Received STARTGAMEFINALIZE packet. Round init status: Started
[09/23/2023 18:02:58]  -13: QueryServerRules (GetServers, meep, 118.137.170.145), WaitingForActivation
[09/23/2023 18:02:58]  -12: QueryServerRules (GetServers, 民主团结富强友爱, 106.75.178.138), WaitingForActivation
[09/23/2023 18:02:58]  -11: QueryServerRules (GetServers, 불면증 클럽, 39.123.76.62), WaitingForActivation
[09/23/2023 18:02:58]  -10: QueryServerRules (GetServers, 仓鼠易沉船2F| 精神创伤战役  | q群567922285, 43.248.187.233), WaitingForActivation
[09/23/2023 18:02:58]  -9: QueryServerRules (GetServers, Nightly Campaign - https://discord.gg/R6kMnFyKTw, 172.218.56.71), WaitingForActivation
[09/23/2023 18:02:58]  -8: QueryServerRules (GetServers, RJ Barotrauma, 24.144.52.117), WaitingForActivation
[09/23/2023 18:02:58]  -7: QueryServerRules (GetServers, [HC] «Ванильная травма», 149.154.69.186), WaitingForActivation
[09/23/2023 18:02:58]  -6: QueryServerRules (GetServers, My rickity ruckus, 176.57.153.91), WaitingForActivation
[09/23/2023 18:02:58]  -5: QueryServerRules (GetServers, Server, 78.46.46.54), WaitingForActivation
[09/23/2023 18:02:58]  -4: QueryServerRules (GetServers, Barodrama (EN), 88.99.97.43), WaitingForActivation
[09/23/2023 18:02:58]  -3: QueryServerRules (GetServers, [GER] KSE - Koalitionsstreitkräfte Europa, 176.9.124.189), WaitingForActivation
[09/23/2023 18:02:58]  -2: QueryServerRules (GetServers, AdminLounge Barotrauma Server, 188.68.36.99), WaitingForActivation
[09/23/2023 18:02:58]  -1: QueryServerRules (GetServers, Cola Serb, 147.189.174.114), WaitingForActivation
[09/23/2023 18:02:58]  -0: LobbyQuery.RequestAsync (1), WaitingForActivation
[09/23/2023 18:02:58] Task count: 14
[09/23/2023 18:02:58] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[09/23/2023 18:02:45] Generating an outpost for the start of the level... (Location: Tectamus Linea, level type: Outpost)
[09/23/2023 18:02:45] Level identifier: outpostlevel
[09/23/2023 18:02:24] Potato PC
[09/23/2023 18:02:24] Carver Jackson is a twat
[09/23/2023 18:02:24] hansmario818
[09/23/2023 18:02:24] Snekulous
[09/23/2023 18:02:24] Emir
[09/23/2023 18:02:24] W  A  T  E  R
[09/23/2023 18:02:24] Movingchicken
[09/23/2023 18:02:24] Dell
[09/23/2023 18:02:22] Potato PC
[09/23/2023 18:02:22] hansmario818
[09/23/2023 18:02:22] Snekulous
[09/23/2023 18:02:22] Emir
[09/23/2023 18:02:22] W  A  T  E  R
[09/23/2023 18:02:22] Movingchicken
[09/23/2023 18:02:22] Dell
[09/23/2023 18:02:22] Carver Jackson is a twat
[09/23/2023 18:02:22] Potato PC
[09/23/2023 18:02:22] Carver Jackson is a twat
[09/23/2023 18:02:22] hansmario818
[09/23/2023 18:02:22] Snekulous
[09/23/2023 18:02:22] Emir
[09/23/2023 18:02:22] W  A  T  E  R
[09/23/2023 18:02:22] Movingchicken
[09/23/2023 18:02:22] Dell
[09/23/2023 18:02:04] Potato PC
[09/23/2023 18:02:04] Carver Jackson is a twat
[09/23/2023 18:02:04] hansmario818
[09/23/2023 18:02:04] Snekulous
[09/23/2023 18:02:04] Emir
[09/23/2023 18:02:04] W  A  T  E  R
[09/23/2023 18:02:04] Movingchicken
[09/23/2023 18:02:04] Dell
[09/23/2023 18:02:04] Potato PC
[09/23/2023 18:02:04] Carver Jackson is a twat
[09/23/2023 18:02:04] hansmario818
[09/23/2023 18:02:04] Snekulous
[09/23/2023 18:02:04] Emir
[09/23/2023 18:02:04] W  A  T  E  R
[09/23/2023 18:02:04] Movingchicken
[09/23/2023 18:02:04] Dell
[09/23/2023 18:02:04] Potato PC
[09/23/2023 18:02:04] Carver Jackson is a twat
[09/23/2023 18:02:04] hansmario818
[09/23/2023 18:02:04] Snekulous
[09/23/2023 18:02:04] Emir
[09/23/2023 18:02:04] W  A  T  E  R
[09/23/2023 18:02:04] Movingchicken
[09/23/2023 18:02:04] Dell
[09/23/2023 18:01:47] Potato PC
[09/23/2023 18:01:47] Carver Jackson is a twat
[09/23/2023 18:01:47] hansmario818
[09/23/2023 18:01:47] Snekulous
[09/23/2023 18:01:47] Emir
[09/23/2023 18:01:47] W  A  T  E  R
[09/23/2023 18:01:47] Movingchicken
[09/23/2023 18:01:47] Dell
[09/23/2023 18:01:32] Potato PC
[09/23/2023 18:01:32] hansmario818
[09/23/2023 18:01:32] Snekulous
[09/23/2023 18:01:32] Emir
[09/23/2023 18:01:32] Graybeard
[09/23/2023 18:01:32] W  A  T  E  R
[09/23/2023 18:01:32] Movingchicken
[09/23/2023 18:01:32] Dell
[09/23/2023 18:01:32] Carver Jackson is a twat
[09/23/2023 18:01:30] Potato PC
[09/23/2023 18:01:30] Carver Jackson is a twat
[09/23/2023 18:01:30] hansmario818
[09/23/2023 18:01:30] Snekulous
[09/23/2023 18:01:30] Emir
[09/23/2023 18:01:30] Graybeard
[09/23/2023 18:01:30] W  A  T  E  R
[09/23/2023 18:01:30] Movingchicken
[09/23/2023 18:01:30] Dell
[09/23/2023 18:01:30] Potato PC
[09/23/2023 18:01:30] Carver Jackson is a twat
[09/23/2023 18:01:30] hansmario818
[09/23/2023 18:01:30] Snekulous
[09/23/2023 18:01:30] Emir
[09/23/2023 18:01:30] Graybeard
[09/23/2023 18:01:30] W  A  T  E  R
[09/23/2023 18:01:30] Movingchicken
[09/23/2023 18:01:30] Dell
[09/23/2023 18:01:30] Potato PC
[09/23/2023 18:01:30] Carver Jackson is a twat
[09/23/2023 18:01:30] hansmario818
[09/23/2023 18:01:30] Snekulous
[09/23/2023 18:01:30] Emir
[09/23/2023 18:01:30] Graybeard
[09/23/2023 18:01:30] W  A  T  E  R
[09/23/2023 18:01:30] Movingchicken
[09/23/2023 18:01:30] Dell
[09/23/2023 17:59:32] Potato PC
[09/23/2023 17:59:29] Carver Jackson is a twat
[09/23/2023 17:59:28] Snekulous
[09/23/2023 17:59:28] hansmario818
[09/23/2023 17:59:27] Emir
[09/23/2023 17:59:27] Graybeard
[09/23/2023 17:59:27] W  A  T  E  R
[09/23/2023 17:59:27] Movingchicken
[09/23/2023 17:59:27] Dell
[09/23/2023 17:59:27] Emir
[09/23/2023 17:59:24] Graybeard
[09/23/2023 17:59:24] W  A  T  E  R
[09/23/2023 17:59:24] Movingchicken
[09/23/2023 17:59:24] Dell
[09/23/2023 17:59:22] Received STARTGAMEFINALIZE packet. Round init status: Started
[09/23/2023 17:59:17]  -13: QueryServerRules (GetServers, meep, 118.137.170.145), WaitingForActivation
[09/23/2023 17:59:17]  -12: QueryServerRules (GetServers, 民主团结富强友爱, 106.75.178.138), WaitingForActivation
[09/23/2023 17:59:17]  -11: QueryServerRules (GetServers, 불면증 클럽, 39.123.76.62), WaitingForActivation
[09/23/2023 17:59:17]  -10: QueryServerRules (GetServers, 仓鼠易沉船2F| 精神创伤战役  | q群567922285, 43.248.187.233), WaitingForActivation
[09/23/2023 17:59:17]  -9: QueryServerRules (GetServers, Nightly Campaign - https://discord.gg/R6kMnFyKTw, 172.218.56.71), WaitingForActivation
[09/23/2023 17:59:17]  -8: QueryServerRules (GetServers, RJ Barotrauma, 24.144.52.117), WaitingForActivation
[09/23/2023 17:59:17]  -7: QueryServerRules (GetServers, [HC] «Ванильная травма», 149.154.69.186), WaitingForActivation
[09/23/2023 17:59:17]  -6: QueryServerRules (GetServers, My rickity ruckus, 176.57.153.91), WaitingForActivation
[09/23/2023 17:59:17]  -5: QueryServerRules (GetServers, Server, 78.46.46.54), WaitingForActivation
[09/23/2023 17:59:17]  -4: QueryServerRules (GetServers, Barodrama (EN), 88.99.97.43), WaitingForActivation
[09/23/2023 17:59:17]  -3: QueryServerRules (GetServers, [GER] KSE - Koalitionsstreitkräfte Europa, 176.9.124.189), WaitingForActivation
[09/23/2023 17:59:17]  -2: QueryServerRules (GetServers, AdminLounge Barotrauma Server, 188.68.36.99), WaitingForActivation
[09/23/2023 17:59:17]  -1: QueryServerRules (GetServers, Cola Serb, 147.189.174.114), WaitingForActivation
[09/23/2023 17:59:17]  -0: LobbyQuery.RequestAsync (1), WaitingForActivation
[09/23/2023 17:59:17] Task count: 14
[09/23/2023 17:59:06] Generating an outpost for the end of the level... (Location: Tectamus Linea, level type: LocationConnection)
[09/23/2023 17:59:04] Generating an outpost for the start of the level... (Location: Hadal Crevasse Outpost, level type: LocationConnection)
[09/23/2023 17:58:59] Level identifier: plateaubasic
[09/23/2023 17:53:59] WARNING: 400 buffer(s) were generated. No more sound buffers will be generated.
[09/23/2023 17:53:21] Attempting to open ALC device "External Headphones"
[09/23/2023 17:53:16] Logged in as Potato PC (SteamID STEAM_1:0:557805996)


Barotrauma Client crash report (generated on 10/20/2022 11:56:29)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


9F82B2BF55EC642195B8B6D9025CC132


Game version 0.19.11.0 (ReleaseMac, branch release, revision 45964c6e22)
Graphics mode: 1440x900 (Fullscreen)
VSync ON
Language: English
Selected content packages: Vanilla
Level seed: Maughanasilly FossaTormsdale Linea
Loaded submarine: Azimuth (1127C32725D0AEC3A658BACB7FBCA0E9)
Selected screen: Barotrauma.GameScreen
SteamManager initialized


System info:
    Operating system: Unix 10.15.7 64 bit
    GPU name: 
    Display mode: {Width:1440 Height:900 Format:Color AspectRatio:1.6}
    GPU status: Normal


Exception: Failed to set regular buffer data for non-streamed audio! Invalid operation (System.Exception)
Target site: Void FillBuffers()
Stack trace: 
   at Barotrauma.Sounds.OggSound.FillBuffers() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sounds\OggSound.cs:line 108
   at Barotrauma.Sounds.SoundChannel..ctor(Sound sound, Single gain, Nullable`1 position, Single freqMult, Single near, Single far, String category, Boolean muffle) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sounds\SoundChannel.cs:line 88
   at Barotrauma.Sounds.Sound.Play(Single gain, Single range, Single freqMult, Vector2 position, Boolean muffle) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sounds\Sound.cs:line 94
   at Barotrauma.SoundPlayer.PlaySound(Sound sound, Vector2 position, Nullable`1 volume, Nullable`1 range, Nullable`1 freqMult, Hull hullGuess, Boolean ignoreMuffling) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sounds\SoundPlayer.cs:line 484
   at Barotrauma.Character.PlaySound(SoundType soundType, Single soundIntervalFactor, Single maxInterval) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\Character.cs:line 1093
   at Barotrauma.Character.OnAttackedProjSpecific(Character attacker, AttackResult attackResult, Single stun) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\Character.cs:line 444
   at Barotrauma.Character.DamageLimb(Vector2 worldPosition, Limb hitLimb, IEnumerable`1 afflictions, Single stun, Boolean playSound, Single attackImpulse, Character attacker, Single damageMultiplier, Boolean allowStacking, Single penetration, Boolean shouldImplode) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 3985
   at Barotrauma.Character.ApplyAttack(Character attacker, Vector2 worldPosition, Attack attack, Single deltaTime, Boolean playSound, Limb targetLimb, Single penetration) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 3777
   at Barotrauma.Attack.DoDamageToLimb(Character attacker, Limb targetLimb, Vector2 worldPosition, Single deltaTime, Boolean playSound, PhysicsBody sourceBody, Limb sourceLimb) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Attack.cs:line 557
   at Barotrauma.Limb.ExecuteAttack(IDamageable damageTarget, Limb targetLimb, AttackResult& attackResult) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Limb.cs:line 1109
   at Barotrauma.Limb.UpdateAttack(Single deltaTime, Vector2 attackSimPos, IDamageable damageTarget, AttackResult& attackResult, Single distance, Limb targetLimb) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Limb.cs:line 1025
   at Barotrauma.EnemyAIController.UpdateLimbAttack(Single deltaTime, Limb attackingLimb, Vector2 attackSimPos, Single distance, Limb targetLimb) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\EnemyAIController.cs:line 2121
   at Barotrauma.EnemyAIController.UpdateAttack(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\EnemyAIController.cs:line 1879
   at Barotrauma.EnemyAIController.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\EnemyAIController.cs:line 441
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2870
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 192
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 855
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58


Last debug messages:
[10/20/2022 11:46:54] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
[10/20/2022 11:46:38] Could not find a suitable module for the location type LocationType (None). Module flag: Airlock.
[10/20/2022 11:46:37] Generating an outpost for the start of the level... (Location: Maughanasilly Fossa, level type: LocationConnection)
[10/20/2022 11:46:37] Level identifier: ridgebasic
[10/20/2022 11:22:34] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
[10/20/2022 11:22:21] Could not find a suitable module for the location type LocationType (None). Module flag: Airlock.
[10/20/2022 11:22:20] Generating an outpost for the start of the level... (Location: Maughanasilly Fossa, level type: LocationConnection)
[10/20/2022 11:22:20] Level identifier: ridgebasic
[10/20/2022 11:19:31] Generating an outpost for the end of the level... (Location: Sarpedon Linea Outpost, level type: LocationConnection)
[10/20/2022 11:19:30] Loading a pre-selected outpost for the start of the level...
[10/20/2022 11:19:30] Level identifier: coldcavernstutorial
[10/20/2022 11:18:51] WARNING: 400 buffer(s) were generated. No more sound buffers will be generated.
[10/20/2022 11:18:25] Attempting to open ALC device "External Headphones"
[10/20/2022 11:18:22] Logged in as Potato PC (SteamID STEAM_1:0:557805996)
```

**Comment by Regalis11** [comment] 2023-09-30 08:43
Thank you for the report!

It seems we've already gotten a report about the same issue https://github.com/Regalis11/Barotrauma/issues/9581. Since it seems to be coming up somewhat frequently, I'll bump it up in priority. Sorry for the inconvenience!

Closing as a duplicate of https://github.com/Regalis11/Barotrauma/issues/9581

**Closed by Regalis11** 2023-09-30 08:43 UTC
