### ISSUE TITLE
Gaps slow down the flow of water

### ISSUE THREAD

**Issue by FalcoGer** [Regalis11/Barotrauma#9928] opened 2022-09-24 11:23 UTC
I have made a submarine. due to the curved bow, I need to use multiple hulls to define the ballast room. But even with the whole forward section of the room gone, the room is still not flooded.
Someone on discord suggested that the hull areas need to be aligned with the damage areas in the floor, but that made the throughput of the water even worse.

A single 100% damaged tile overpowers a normal ballast pump and floods the room and puts it on high pressure. But if the leak is on the other side of a gap, the room can not be flooded completely.

I believe this is a bug as a same sized hole in a single hull room would instantly flood it to 100%.

Here you can see 5 damaged hull sections, and yet there is still air.

![grafik](https://user-images.githubusercontent.com/16250196/192094732-fe31f317-8966-428c-9bde-db2cceef31e3.png)

Two damaged hull sections, and the room is barely half filled.

![grafik](https://user-images.githubusercontent.com/16250196/192094759-2092fb1a-00be-471b-a313-3f402708cbd1.png)

A single hole in a one hull room floods it and puts it on high pressure in about 5 seconds.

![grafik](https://user-images.githubusercontent.com/16250196/192094805-34ed6f69-af79-48d7-93fc-c924649dd9bb.png)

The actual layout of the hulls and the gaps.

![grafik](https://user-images.githubusercontent.com/16250196/192094902-7dc1df63-b270-4864-85b6-5ad502f05676.png)

**Comment by FalcoGer** [comment] 2022-09-24 11:30
as it is flooding you can see the throughput gradient. this makes no logical sense at all.
![grafik](https://user-images.githubusercontent.com/16250196/192095495-4768cfd7-80e6-44f8-bbdd-2d689766a7b2.png)

**Comment by FalcoGer** [comment] 2022-09-24 11:44
here is the same room, one hole, and it floods while 5 holes on the other side of "gaps". can not flood this room.
![grafik](https://user-images.githubusercontent.com/16250196/192096168-8a0517f3-752f-40dd-8f5d-7a6b010f08f8.png)

**Comment by Regalis11** [comment] 2022-09-25 10:46
Duplicate of https://github.com/Regalis11/Barotrauma/issues/9544

**Closed by Regalis11** 2022-09-25 10:46 UTC
