### ISSUE TITLE
[0.9.9.0] Multiplayer - Unable to spectate games mid-round (Campaign only?). Missing Entities.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2659] opened 2020-04-18 15:55 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Players are hardly ever able to spectate in this version of the game after the round has started. They're constantly being kicked for missing entities. Not sure if it's Campaign only issue.

**Version**
0.9.9.0

**Comment by Regalis11** [comment] 2020-04-19 10:21
Duplicate of #2382 and #2599

**Closed by Regalis11** 2020-04-19 10:21 UTC
