### ISSUE TITLE
[Unstable] The changed artifact case has visual issues

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#11524] opened 2023-03-14 16:31 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

https://user-images.githubusercontent.com/104232152/225072858-5fb23264-3e46-4638-b654-ecfd40ce4e43.mp4

Scaled up a lot here, for making the issues easily visible with compression, but the holes and fans on the artifact case are not only slightly misalligned when sitting still, letting you see through it, but they also visibly disconnect and shift as you begin to move with it in hand, making the holes ever so more visible.
Also it just has holes in the inventory sprite, which doesnt seem right
![image](https://user-images.githubusercontent.com/104232152/225077893-29d59a6f-f81d-4876-abae-0388642c2a3f.png)

### Reproduction steps

1.Put down an artifact and insert batteries
2.Closely look at the sprite as you move around with it and notice the gaps and missalignments

### Bug prevalence

Happens every time I play

### Version

Unstable (v1.1.2.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment] 2023-03-28 09:10
So the issue is also present with a normally scaled item, right?

**Comment by Rehexr** [comment] 2023-03-28 09:49
Yes, try running around with it, you can see that even on normal scale the spinning vents will noticably lag behind

**Comment by Regalis11** [comment] 2023-03-30 06:29
The jitter/shifting didn't seem to be an issue specific to the artifact transport case, but all moving items with decorative sprites. I don't think there's been any movable vanilla item with decorative sprites before, which is probably why we've never noticed the issue before. Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/d2068579beaac06abc689c63e761fd0a0b7e92ca

Also added a background behind the fans and added the fans to the inventory icon in https://github.com/Regalis11/Barotrauma-development/commit/08f8a3933a42c8622189c98219aaa46f56ca5418

**Comment by AdamH-Daedalic** [comment] 2023-06-21 11:53
Unable to reproduce. Not observing any jittering or shifting of the sprite when running/moving with the case in-hand. Player tried a variety of other erratic movements to thoroughly test the case and could not spot any movement of the fans. Closing.

**Closed by AdamH-Daedalic** 2023-06-21 11:53 UTC
Labels: Bug
