### ISSUE TITLE
Crash right before moving to next location

### ISSUE THREAD

**Issue by 32435343547** [Regalis11/Barotrauma#7363] opened 2021-11-18 12:38 UTC
Barotrauma Client crash report (generated on 18.11.2021 13:33:47)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

53369B525C73F08AF404DBAF116B0ADA

Game version 0.15.13.0 (ReleaseWindows, branch release, revision 4e66dd7b5d)
Graphics mode: 2560x1440 (Fullscreen)
VSync ON
Language: German
Selected content packages: Vanilla 0.9
Level seed: ArgadnelArgadnel
Loaded submarine: Dugong (B256871C1D7C5E05CDABC806742611B6)
Selected screen: Barotrauma.RoundSummaryScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19043.0 64 bit
    GPU name: NVIDIA GeForce GTX 1080
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1,7777778}
    GPU status: Normal

Exception: Collection was modified; enumeration operation may not execute. (System.InvalidOperationException)
Target site: Void ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
Stack trace: 
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Barotrauma.GUI.DrawMessages(SpriteBatch spriteBatch, Camera cam) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1666
   at Barotrauma.GUI.Draw(Camera cam, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 635
   at Barotrauma.RoundSummaryScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\RoundSummaryScreen.cs:line 55
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 1062
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 511
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 61

Last debug messages:
[18.11.2021 13:33:41] Generating an outpost for the end of the level... (Location: Abbaufeld Argadnel, level type: LocationConnection)
[18.11.2021 13:33:28] Transitioning to ArgadnelArgadnel (current location: Argadnel, selected location: Abbaufeld Argadnel, leaving sub: Dugong, at start: False, at end: True, transition type: ProgressToNextEmptyLocation)
[18.11.2021 12:38:43] Generating an outpost for the start of the level... (Location: Argadnel, level type: LocationConnection)
[18.11.2021 12:07:55] Generating an outpost for the start of the level... (Location: Argadnel, level type: LocationConnection)
[18.11.2021 11:53:30] Generating an outpost for the start of the level... (Location: Argadnel, level type: LocationConnection)
[18.11.2021 11:30:58] Generating an outpost for the start of the level... (Location: Argadnel, level type: LocationConnection)
[18.11.2021 11:29:58] (Msg) SDR RelayNetworkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[18.11.2021 11:29:58] (Msg) Ping location: ams=23+2,fra=25+2,sto2=27+2,sto=32+3/27+2,par=28+2,lhr=29+2/28+2,waw=34+3,vie=39+3/37+2,mad=45+4/47+2,iad=109+10/104+2,sgp=192+19/193+19,gru=204+20
[18.11.2021 11:29:58] (Msg) Ping measurement completed
[18.11.2021 11:29:55] (Verbose) Communications with routing cluster 'seo' established.
[18.11.2021 11:29:55] (Verbose) Communications with routing cluster 'tyo1' established.
[18.11.2021 11:29:55] (Verbose) Communications with routing cluster 'syd' established.
[18.11.2021 11:29:55] (Verbose) Communications with routing cluster 'tyo' established.
[18.11.2021 11:29:55] (Verbose) Communications with routing cluster 'sgp' established.
[18.11.2021 11:29:55] (Verbose) Communications with routing cluster 'scl' established.
[18.11.2021 11:29:55] (Verbose) Communications with routing cluster 'sea' established.
[18.11.2021 11:29:55] (Verbose) Communications with routing cluster 'lim' established.
[18.11.2021 11:29:55] (Verbose) Communications with routing cluster 'hkg' established.
[18.11.2021 11:29:55] (Verbose) Communications with routing cluster 'maa' established.
[18.11.2021 11:29:55] (Verbose) Communications with routing cluster 'jnb' established.
[18.11.2021 11:29:55] (Verbose) Communications with routing cluster 'eze' established.
[18.11.2021 11:29:55] (Verbose) Communications with routing cluster 'waw' established.
[18.11.2021 11:29:55] (Verbose) Communications with routing cluster 'vie' established.
[18.11.2021 11:29:55] (Verbose) Communications with routing cluster 'lax' established.
[18.11.2021 11:29:55] (Verbose) Communications with routing cluster 'ord' established.
[18.11.2021 11:29:55] (Verbose) Communications with routing cluster 'sto' established.
[18.11.2021 11:29:55] (Verbose) Communications with routing cluster 'sto2' established.
[18.11.2021 11:29:55] (Verbose) Communications with routing cluster 'gru' established.
[18.11.2021 11:29:55] (Verbose) Communications with routing cluster 'mad' established.
[18.11.2021 11:29:55] (Verbose) Communications with routing cluster 'par' established.
[18.11.2021 11:29:55] (Verbose) Communications with routing cluster 'dxb' established.
[18.11.2021 11:29:55] (Verbose) Communications with routing cluster 'iad' established.
[18.11.2021 11:29:55] (Verbose) Communications with routing cluster 'dfw' established.
[18.11.2021 11:29:55] (Verbose) Communications with routing cluster 'bom' established.
[18.11.2021 11:29:55] (Verbose) Communications with routing cluster 'lhr' established.
[18.11.2021 11:29:55] (Verbose) Communications with routing cluster 'atl' established.
[18.11.2021 11:29:55] (Verbose) Communications with routing cluster 'fra' established.
[18.11.2021 11:29:55] (Verbose) Communications with routing cluster 'ams' established.
[18.11.2021 11:29:55] (Msg) SDR RelayNetworkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[18.11.2021 11:29:55] (Msg) Performing ping measurement
[18.11.2021 11:29:55] (Msg) Got SDR network config.  Loaded revision 351 OK
[18.11.2021 11:29:55] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[18.11.2021 11:29:47] Attempting to open ALC device "OpenAL Soft on Lautsprecher (3- Logitech G935/G933s Gaming Headset)"
[18.11.2021 11:29:46] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[18.11.2021 11:29:46] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[18.11.2021 11:29:44] Logged in as Sonntagsspieler :smile: (SteamID STEAM_1:1:39909378)

**Comment by kento10** [comment] 2021-11-19 01:39
This bug also leads into a no available level transition after second save load that is fixed into the original bug.

**Comment by Regalis11** [comment] 2021-12-14 13:59
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/10c9f516fafe0e816df3f9468a171a169cb7e2e1.

> Fixed a race condition that caused a crash when GUI messages were cleared at the end of the round while drawing them at the same time. 

A race condition like this is probably next to impossible to reproduce reliably, but let's keep an eye out for this and consider it fixed if we don't run into the issue in a while.

**Comment by Rokvach** [comment] 2022-01-28 09:53
There hasn't been any sightings of this issue happening since the start of Unstable testing, this seems to be working correctly, closing.

**Closed by Rokvach** 2022-01-28 09:53 UTC
Labels: Bug, Needs testing, Code, Crash
