### ISSUE TITLE
All new modules separate integers with a comma.

### ISSUE THREAD

**Issue by NicolaruS** [Regalis11/Barotrauma#1909] opened 2019-11-27 19:04 UTC
Periscopes, searchlights, guns, etc. in the game separate integers with a dot, and all new modules separate integers with a comma.
Sorry for google translate, my English is very bad.

**Comment by Regalis11** [comment] 2019-11-28 09:12
Sorry, but I'm not sure I understand what you mean. What do you mean by modules and separating integers (do you mean decimal numbers?)?

**Comment by rav2n** [comment] 2019-11-28 14:28
He says dots are used to separate decimals in old devices, while commas are used in recently added ones(sin, cos, rounding components...). This makes it impossible to use them in the same logic circuit at the same time.

**Comment by Regalis11** [comment] 2019-11-28 15:40
Ah, I see, thank you for the clarification! I believe this may have something to do with the number format your Windows is using (which determines which symbol is used as the decimal separator). However, when I tried reproducing this with both Russian and Finnish (which uses comma) number format, I couldn't spot any issues:
![4567234](https://user-images.githubusercontent.com/14351070/69818597-bf30bc00-1205-11ea-9b6e-218f8a378da0.png)

The rounding components should not even display the decimal separator, just the integer part. Could you please give some more details on what kind of a circuit this problem appears in?

**Comment by NicolaruS** [comment] 2019-11-28 17:53
![Безымянный](https://user-images.githubusercontent.com/58271380/69825667-1c863680-1221-11ea-9650-4d8384904d1c.png)

**Comment by Regalis11** [comment] 2019-11-28 18:23
I think I'm missing something here, what's the problem in the picture? The only display that shows a comma is the one that's getting the signal directly from the memory component. Does the value on the display not match the value the memory component is set to send?

**Comment by NicolaruS** [comment] 2019-11-28 18:57
I use a comma everything works, if I use a period then no. When you connect the periscope does not work.

**Comment by NicolaruS** [comment] 2019-11-28 18:59
if integers are separated by a comma in the number then the sine gives the result if a point then no

**Comment by NicolaruS** [comment] 2019-11-28 19:05
"Does the value on the display not match the value the memory component is set to send?"
 Yes, it is.

**Comment by Regalis11** [comment] 2019-11-28 19:17
Thank you for the extra info, I figured out the issue now! I assumed the components were outputting the values in the wrong format, but it was the other way around: they required the input to be in the wrong format.

Looks like this was already fixed in our private repo https://github.com/Regalis11/Barotrauma-development/commit/1b77d961 but the fix didn't make it in time to the update. Will be fixed in the next update though! 

Before the update is out, I'm afraid the only way to work around the issue is changing the regional format (not the language, just the regional format) of your Windows installation to something that uses dot as the decimal separator, for example English. Sorry for the trouble!

**Comment by Rokvach** [comment] 2019-11-29 08:49
Tested, moving this to Done.

**Comment by DerEchteSpatz** [comment] 2019-11-29 14:24
@ Regalis11
Can you make the new decimal separation system (point or comma) an option in the setting?
For example "Project Zomboid" lets you choose similiar settings, directly in its settings menu, if you want to have the temperature degree in Celsius or Fahrenheit. I would like to have such an option too, for Barotrauma, without the need to change something on my operating system...

Although I live in a country where decimal numbers are separated by a comma (and not by a point), I am used to doing it by POINT on PC, since the statistics software I am used to work on, does use the international setting only. So it would be really awkward for me.

**Comment by Regalis11** [comment] 2019-11-30 15:14
@DerEchteSpatz I'm sorry, but I don't think we will be adding the option to select the separator. It would lead to many complications, especially if players are using different separators in multiplayer. For instance, handling circuits that parse decimal numbers would get extremely complicated, even more so if the users can input values to the circuit mid-round.

>I would like to have such an option too, for Barotrauma, without the need to change something on my operating system...
The operating system settings should not affect which separator is used (dot should always be used everywhere); the new components being affected is a bug.

**Comment by Regalis11** [comment] 2019-11-30 15:15
@NicolaruS thank you for taking the time to close this, but we'll close it ourselves when we've reviewed it at our end.

**Closed** 2019-12-12 09:20 UTC
Labels: Bug, Code
