### ISSUE TITLE
Crash when launching modded multiplayer game

### ISSUE THREAD

**Issue by kz2wd** [Regalis11/Barotrauma#9963] opened 2022-09-30 17:03 UTC
The file used to work, but it no longer does. Also, I can launch the game alone, but my friends can't join. When I leave the game, I also get an error message.

Here is my crashreport :

[crashreport.log](https://github.com/Regalis11/Barotrauma/files/9686410/crashreport.log)

Text version :

Barotrauma Client crash report (generated on 30/09/2022 18:53:18)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

116B6C514DB831BB68D5A8F96ACE87C4

Game version 0.18.15.1 (ReleaseWindows, branch hf, revision 91a05f31ff)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla, Meaningful CPR, Meaningful Upgrades, oClockRadar / Sonar [Alt Appearance], Talent Gear Found In Wrecks, All The Talent Trees, Submarine Weapon Sound Makeover, MoreMissionsMod, Backpacks - No Encumbrance
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.NetLobbyScreen
SteamManager initialized
Client (Round hadn't been started)

System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce RTX 3070 Ti
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1,7777778}
    GPU status: Normal

Exception: One or more errors occurred. (Cannot access a closed pipe.) (System.AggregateException)
Target site: Boolean Wait(Int32, System.Threading.CancellationToken)
Stack trace: 
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at Barotrauma.Networking.ChildServerRelay.ReadIncomingMsgs() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 124
   at Barotrauma.Networking.ChildServerRelay.<UpdateRead>g__readBytes|40_0(Span`1 readTo) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 172
   at Barotrauma.Networking.ChildServerRelay.UpdateRead() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 183
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()

InnerException: Cannot access a closed pipe.
Target site: Void CheckReadOperations()
Stack trace: 
   at System.IO.Pipes.PipeStream.CheckReadOperations()
   at System.IO.Pipes.PipeStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.<>c.<BeginReadInternal>b__43_0(Object <p0>)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at System.IO.Stream.EndRead(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
Last debug messages:
[30/09/2022 18:53:18] WARNING: Tried to restore enabled packages multiple times/without performing a backup
[30/09/2022 18:53:18] Error while reading a message from server. {Exception has been thrown by the target of an invocation.}
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at Barotrauma.MissionPrefab.Instantiate(Location[] locations, Submarine sub) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\Missions\MissionPrefab.cs:line 365
   at Barotrauma.Location.InstantiateLoadedMissions(Map map) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Location.cs:line 859
   at Barotrauma.Map.LoadState(XElement element, Boolean showNotifications) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Map.cs:line 1216
   at Barotrauma.MultiPlayerCampaign.Load(XElement element) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameModes\MultiPlayerCampaign.cs:line 195
   at Barotrauma.MultiPlayerCampaign.LoadState(String filePath) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\MultiPlayerCampaign.cs:line 1075
   at Barotrauma.Networking.GameClient.OnFileReceived(FileTransferIn transfer) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2686
   at Barotrauma.Networking.FileReceiver.ReadMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\FileTransfer\FileReceiver.cs:line 325
   at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 980
   at Barotrauma.Networking.SteamP2POwnerPeer.HandleDataMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2POwnerPeer.cs:line 0
   at Barotrauma.Networking.SteamP2POwnerPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2POwnerPeer.cs:line 235
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 634

Inner exception: Object reference not set to an instance of an object.
   at Barotrauma.CargoMission.GetReward(Submarine sub) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\Missions\CargoMission.cs:line 221
   at Barotrauma.Mission..ctor(MissionPrefab prefab, Location[] locations, Submarine sub) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\Missions\Mission.cs:line 159
   at Barotrauma.CargoMission..ctor(MissionPrefab prefab, Location[] locations, Submarine sub) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\Missions\CargoMission.cs:line 44
[30/09/2022 18:49:16] Lobby created!
[30/09/2022 18:48:08] WARNING: Tried to restore enabled packages multiple times/without performing a backup
[30/09/2022 18:47:48] Lobby created!
[30/09/2022 18:47:38] LobbyMatchList:  LobbiesMatching: 0
[30/09/2022 18:47:38] LobbyMatchList:  LobbiesMatching: 0
[30/09/2022 18:47:38] SteamAPICallCompleted:   AsyncCall: 4658269346119877488
   Callback: 510
 ParamCount: 4
[30/09/2022 18:47:38] LobbyMatchList:  LobbiesMatching: 16
[30/09/2022 18:47:38] LobbyMatchList:  LobbiesMatching: 16
[30/09/2022 18:47:38] SteamAPICallCompleted:   AsyncCall: 3134829071082346015
   Callback: 510
 ParamCount: 4
[30/09/2022 18:47:37] LobbyMatchList:  LobbiesMatching: 50
[30/09/2022 18:47:37] LobbyMatchList:  LobbiesMatching: 50
[30/09/2022 18:47:37] SteamAPICallCompleted:   AsyncCall: 8515793254689433521
   Callback: 510
 ParamCount: 4
[30/09/2022 18:47:37] LobbyMatchList:  LobbiesMatching: 50
[30/09/2022 18:47:37] LobbyMatchList:  LobbiesMatching: 50
[30/09/2022 18:47:37] SteamAPICallCompleted:   AsyncCall: 12982384686560411290
   Callback: 510
 ParamCount: 4
[30/09/2022 18:47:37] AvatarImageLoaded:    SteamID: 76561198362617558
     Image: 125
      Wide: 184
      Tall: 184
[30/09/2022 18:46:47] WARNING: Tried to restore enabled packages multiple times/without performing a backup
[30/09/2022 18:44:45] Lobby created!
[30/09/2022 18:44:34] LobbyMatchList:  LobbiesMatching: 0
[30/09/2022 18:44:34] LobbyMatchList:  LobbiesMatching: 0
[30/09/2022 18:44:34] SteamAPICallCompleted:   AsyncCall: 8256107916402796006
   Callback: 510
 ParamCount: 4
[30/09/2022 18:44:33] LobbyMatchList:  LobbiesMatching: 16
[30/09/2022 18:44:33] LobbyMatchList:  LobbiesMatching: 16
[30/09/2022 18:44:33] SteamAPICallCompleted:   AsyncCall: 10681894280044081507
   Callback: 510
 ParamCount: 4
[30/09/2022 18:44:33] LobbyMatchList:  LobbiesMatching: 50
[30/09/2022 18:44:33] LobbyMatchList:  LobbiesMatching: 50
[30/09/2022 18:44:33] SteamAPICallCompleted:   AsyncCall: 13191937074343027081
   Callback: 510
 ParamCount: 4
[30/09/2022 18:44:33] LobbyMatchList:  LobbiesMatching: 50
[30/09/2022 18:44:33] LobbyMatchList:  LobbiesMatching: 50
[30/09/2022 18:44:33] SteamAPICallCompleted:   AsyncCall: 9252341225679071750
   Callback: 510
 ParamCount: 4
[30/09/2022 18:44:33] AvatarImageLoaded:    SteamID: 76561198123145865
     Image: 121
      Wide: 184
      Tall: 184
[30/09/2022 18:44:32] AvatarImageLoaded:    SteamID: 76561198060069357
     Image: 119
      Wide: 184
      Tall: 184
[30/09/2022 18:44:32] AvatarImageLoaded:    SteamID: 76561198049238887
     Image: 116
      Wide: 184
      Tall: 184
[30/09/2022 18:44:32] AvatarImageLoaded:    SteamID: 76561198018635709
     Image: 114
      Wide: 184
      Tall: 184
[30/09/2022 18:44:32] AvatarImageLoaded:    SteamID: 76561198272521986
     Image: 124
      Wide: 184
      Tall: 184
[30/09/2022 18:44:32] AvatarImageLoaded:    SteamID: 76561198163491789
     Image: 123
      Wide: 184
      Tall: 184
[30/09/2022 18:44:32] AvatarImageLoaded:    SteamID: 76561198153224818
     Image: 122
      Wide: 184
      Tall: 184
[30/09/2022 18:44:32] AvatarImageLoaded:    SteamID: 76561198113665202
     Image: 120
      Wide: 184
      Tall: 184
[30/09/2022 18:44:32] AvatarImageLoaded:    SteamID: 76561198059690010
     Image: 118
      Wide: 184
      Tall: 184
[30/09/2022 18:44:32] AvatarImageLoaded:    SteamID: 76561198056832319
     Image: 117
      Wide: 184
      Tall: 184
[30/09/2022 18:44:32] AvatarImageLoaded:    SteamID: 76561198042206996
     Image: 115
      Wide: 184
      Tall: 184
[30/09/2022 18:44:32] SteamRelayNetworkStatus:                      Avail: Current
 PingMeasurementInProgress: 1
        AvailNetworkConfig: Current
             AvailAnyRelay: Current
                  DebugMsg: System.Byte[]
[30/09/2022 18:42:01] WARNING: Tried to restore enabled packages multiple times/without performing a backup
[30/09/2022 18:41:39] Lobby created!
[30/09/2022 18:37:22] Attempting to open ALC device "OpenAL Soft on Haut-parleurs (2- Logitech PRO X Wireless Gaming Headset)"
[30/09/2022 18:37:17] Logged in as Sunn (SteamID STEAM_1:0:111339579)

**Comment by Regalis11** [comment] 2022-10-01 10:02
Thank you for the report! Based on the crash report, it seems initializing some type of cargo mission is failing for some reason. We have gotten a similar report through the debug analytics players can enable, and recently implemented a fix that might address that issue (commit in our private repo https://github.com/Regalis11/Barotrauma-development/commit/00a821ca29a724e601ed394daef4983d28680158). However, we aren't sure how to reproduce the issue, so we can't be sure whether it's fully fixed or not.

> The file used to work, but it no longer does.

Do you mean a campaign save file? If you have a save where this occurs consistently, it'd help us a lot in diagnosing this if you could send it to us here. Note that you need to .zip the file first, since github doesn't allow attaching files with the .save file extension.

Thank you and sorry for the inconvenience!

**Comment by Regalis11** [comment] 2023-03-16 08:52
No steps to repro, closing

**Closed by Regalis11** 2023-03-16 08:52 UTC
Labels: Bug, Need more info, Code, Crash, Modding
