### ISSUE TITLE
Physics bug on character's arm when grabbing a dead moloch

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#9658] opened 2022-07-29 02:16 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Didn't play myself but noticed on video:

https://www.youtube.com/watch?v=ngxObzzqPQ8

At 2:46 character gibs of a humanoid are acting incorrectly. I don't know if operating system matters. I blindly guess it was windows.

### Reproduction steps

Probably creature has to be dead. Something will have to make them both shake. Maybe just grabbing moloch can really make them shake so hard.

### Bug prevalence

Happens every now and then

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by NilanthAnimosus** [comment] 2022-08-16 09:14
Thanks for the report!

This is more a case of the characters ragdoll trying to stretch out to the Moloch's dead body, instead of the more expected case of the character being dragged towards the Moloch.

**Comment by NilanthAnimosus** [comment] 2022-09-02 10:13
Tested this myself for a bit on the dev branch (commit https://github.com/Regalis11/Barotrauma-development/commit/43f8fa72a0165cb6b17cb970f7236fe2b54438e1) and found its multiplayer exclusive (does not occur in single player) and appears to be related to syncing of the bodies position between client and server.

I have a theory on this, if the server controls whether its too far away to grab and to let go, so if the position of the body gets far enough from the player while grabbed it can begin stretching the ragdoll.

in some cases the ragdoll can move differently to the server when it appears to be sinking/rising (from collisions pushing it away) and severing. but reliably reproducing this seems extremely difficult, not sure repro steps can be made for this issue or if its worth addressing given it seems to be related to dead character position syncing.

**Comment by Regalis11** [comment] 2023-01-10 11:28
Fixed in https://github.com/Regalis11/Barotrauma-development/pull/3850/commits/c557503dee79e359ff6cd2440a6e7d2d10bb651a

**Comment by Rokvach** [comment] 2023-01-12 14:22
You can keep the creature grabbed even though they aren't anywhere near your character, for example Endworms fall quite fast while dead so if you grab one and wait for a bit you can see that you still have access to the creatures inventory even though it isn't anywhere near you anymore.

There is couple ways to address this.
A. Drag the player character with the creature if they are grabbing it (more fun)
B. Ungrab if the creatures grab range is certain distance away from the player character

**Comment by Rokvach** [comment] 2023-01-12 14:29
Moving to Team1

**Comment by Regalis11** [comment] 2023-01-13 09:08
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ee0e9a43113267d207faacaacf3ee18c10d7933b

**Comment by Rokvach** [comment] 2023-01-13 15:03
Tested, working correctly. Can be merged and closed.

**Closed** 2023-01-13 17:24 UTC
Labels: Bug, Code, Networking
