### ISSUE TITLE
"Sabotage" option never dissappears after being selected a traitor

### ISSUE THREAD

**Issue by OverwatchVoice** [Regalis11/Barotrauma#1903] opened 2019-11-23 05:49 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The option to Sabotage installations as a traitor remains after respawning or starting a new round,and dissappears only after disconnecting. The button isn't functional, however.

**Steps To Reproduce**
Self-explanatory

**Version**
0.9.5.1.

**Comment by Regalis11** [comment] 2019-11-25 07:55
I unfortunately wasn't able to get the sabotage option to appear after a respawn, got to do some more debugging to figure out how exactly it can occur. 

The issue when restarting a round should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/d28a60a544e597e8feb92628caaf0f8b9ce97f44 (private repo)

**Comment by OverwatchVoice** [comment] 2019-11-25 12:49
I think it was in a dedicated server I was hosting myself.

**Comment by Rokvach** [comment] 2019-12-01 12:04
At least working correctly on SteamP2P hosted servers

**Comment by Rokvach** [comment] 2020-01-07 07:48
Seems to be working as intended on dedicated side as well, moving to Done.

**Comment by OverwatchVoice** [comment] 2020-01-07 12:40
Oh, sorry, I never got a message that you were waiting for me to answer.

**Closed** 2020-01-07 12:40 UTC
Labels: Bug, Code
