### ISSUE TITLE
Suggestion: Medical doctors bots should not treat husks when character wear Zealot Robes or have husk gens

### ISSUE THREAD

**Issue by zelda0079** [Regalis11/Barotrauma#12586] opened 2023-08-30 02:49 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Suggestion: Medical doctors bots should not treat husks when character wear Zealot Robes or have husk gens

### Reproduction steps

1. Wear Zealot Robes (tested) or have husk gens(I didn't test).
2. Get other Afflictions.
3. Medical doctors bots treat you.
4. The bot also treat the husk.

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Single player

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by NilanthAnimosus** [comment] 2023-09-08 07:06
Thanks for the report!

I Gave this a test on the current unstable and found no issues with the zealot robes, husk genes and husk symbiosis effects. As a note cultist robes do not protect against husk infections (And are not intended to) - only their aggression which the doctor did correctly treat in that case.

Gave a quick check afterwards on the current stable, and found the same result.

Could you have been using any mods related to husks in some form?

**Comment by zelda0079** [comment] 2023-09-17 18:16
> Thanks for the report!
> 
> I gave this a test on the current unstable and found no issues with the zealot robes, husk genes and husk symbiosis effects.
> 
> As a note cultist robes (I know you mentioned zealot though) do not protect against husk infections (And are not intended to) - only their aggression which the doctor did correctly treat in that case.
> 
> Gave a quick check afterwards on the current stable, and found the same result with zealot robes and husk genes.
> 
> Could you have been using any mods related to husks, medical, afflictions, clothing overriding and other such in some form? The ability for doctors to ignore them is based on tags with both the items and afflictions.

Yes, my mod list

Lua For Barotrauma
CsForBarotrauma
Performance Fix
Dont Open Debug Console On Errors
BetterHealthUI
BetterFabricatorUI
Bots operate fabricators
Storage Icons
Sort Container UI
Larger Deconstructor
Faster Deconstructor
搬砲彈 2
Combinable Ammo Revived (NOW WORKS WITH ALL AMMO)
大腰包 big toolbelt
Item IO Framework
Forked EuropaWar
Dynamic Europa - Fast Paced 1.0 patch
DynamicEuropa
天賦增強 - Talent Enhancement[CN-EN-RU-FRN]
Pet Lives Matter!
**[EA-HI]Animated Barotrauma Lite** clothing overriding
better NPC suits (Animated Barotrauma Lite)
[BOS]Box-青果盒 (單人改版)
Hotbar Holdable Guns
**Enable Husk voice** husks overriding

**Comment by NilanthAnimosus** [comment] 2023-10-09 09:46
upon investigating, I believe this is caused by the mod "Enable Husk voice husks overriding" missing the IgnoreTreatmentIfAfflictedBy tag "husktransformimmunitytemporary".

Left a message for the mod and closing the ticket as completed.

**Closed by NilanthAnimosus** 2023-10-09 09:46 UTC
Labels: Bug, Need more info, Design
