### ISSUE TITLE
Have no servers in the search bar and click on Player

### ISSUE THREAD

**Issue by cjds** [Regalis11/Barotrauma#1783] opened 2019-08-11 04:19 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Game crashes but stays "running" which forces me to kill Steam

**Steps To Reproduce**
Have no servers in the search bar and click on Player

**Version**

```
Exception: Failed to compare two elements in the array.
Target site: Void Sort(T[], Int32, Int32, System.Collections.Generic.IComparer`1[T])
Stack trace: 
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Comparison`1 comparison)
   at Barotrauma.RectTransform.SortChildren(Comparison`1 comparison) in D:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\GUI\RectTransform.cs:line 602
   at Barotrauma.ServerListScreen.SortList(GUIButton button, Object obj) in D:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\Screens\ServerListScreen.cs:line 382
   at Barotrauma.GUIButton.Update(Single deltaTime) in D:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\GUI\GUIButton.cs:line 217
   at Barotrauma.GUI.<>c__DisplayClass112_0.<Update>b__0(GUIComponent c) in D:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\GUI\GUI.cs:line 649
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime) in D:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\GUI\GUI.cs:line 650
   at Barotrauma.GameMain.Update(GameTime gameTime) in D:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\GameMain.cs:line 735
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in C:\Users\Admin\Desktop\Repos\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in C:\Users\Admin\Desktop\Repos\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in C:\Users\Admin\Desktop\Repos\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\Admin\Desktop\Repos\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Barotrauma.Program.Main(String[] args) in D:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\Program.cs:line 61
```

**Comment by ekqvist** [comment] 2019-12-05 09:39
I managed to reproduce this by going back all the way to the v0.9.1.0 build. However, I cannot reproduce it on the current build or other more recent builds. It should be fixed now.

I'll keep it open until it has been reviewed internally and we'll close it after that.

**Closed** 2019-12-12 09:21 UTC
Labels: Bug, Code, Crash
