### ISSUE TITLE
Docking Port has ability to suck power out of `Power_In` slots

### ISSUE THREAD

**Issue by PanmanS** [Regalis11/Barotrauma#10882] opened 2023-01-06 07:05 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

While using [Mechtrauma](https://steamcommunity.com/sharedfiles/filedetails/?id=2890754956) mod and trying to convert it to use mod items, i've spotted that docking port able to use power even from slots it shouldnt be able (like `Power_In` of batteries). More over it causes load to double up cause it is also connected to grid. 

here's load without docking port being connected to batteries
![image](https://user-images.githubusercontent.com/42521948/210947733-24488037-fa49-4eec-876c-a28a59b6d6a4.png)

here's load with docking port being connected to batteries
![image](https://user-images.githubusercontent.com/42521948/210947795-2a2a2e69-331d-45b8-915c-27224d4da993.png)

wiring of docking port
![image](https://user-images.githubusercontent.com/42521948/210948048-2bf4911f-aabc-486e-8ced-611bc364ee11.png)

### Reproduction steps

1. install [Mechtrauma](https://steamcommunity.com/sharedfiles/filedetails/?id=2890754956), [Lua for Barotrauma](https://steamcommunity.com/sharedfiles/filedetails/?id=2559634234) and [Cs For Barotrauma](https://steamcommunity.com/sharedfiles/filedetails/?id=2795927223) for mod to function
2. download and open this submarine [Barsuk_Mechtrauma.zip](https://github.com/Regalis11/Barotrauma/files/10357994/Barsuk_Mechtrauma.zip)
3. launch test run, enable sonar and point arrow on console to upper-right corner
4. look at junction box load values 
5. disconnect docking port from batteries
6. look at junction box load values again

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-01-06 09:45
Duplicate of #9194

**Closed by Regalis11** 2023-01-06 09:45 UTC
