### ISSUE TITLE
[0.9.702] New characters in campaign spawned with no loadout, except for id card.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2086] opened 2020-01-30 22:25 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I think this may be related to #2042 , but new characters that were made on the new round had no loadout except for their id card. Some existing characters reported that they had the loadout spawned on them instead.

**Version**
0.9.702
Windows

**Comment by Rokvach** [comment] 2020-01-31 11:25
I have a hunch that this was due to not leaving the server when the server was restarted.

As this issue happened to me yesterday when I joined the server, I didn't have the time to pick my class preferences as the server restarted and when I reconnected no matter which class I chose it didn't change my name on the lobby player list to match that classes color. When spawning in to the campaign round I found myself with only a ID card in my inventory, which did state what I was a Mechanic which was the class I tried to select in the lobby.

So one thing I would like to see tested is:
- Join a ongoing campaign server while they are in a lobby
- Have class preferences empty
- Have the server host to restart the server
- Stay on the server and reconnect once the server comes back online
- Try and pick a class
- Start round and see what happens

**Comment by Regalis11** [comment] 2020-01-31 13:27
I think I may have figured out what's causing this:

I "fixed" #2042 by making the clients delay reading the inventory updates events until they've received all the item spawn/removal events created before the server wrote the inventory update (= the client waited until all the items that might've been spawned in the inventory exist before updating the inventory). The problem was that if the clients never received those events, for example because the round was ended, the coroutine would keep running indefinitely and potentially trigger at some point during the next round (which might've caused the state of the inventory to get even more messed up).

Can be reproduced by doing the following:
1. Set a breakpoint at line 1293 in ClientSource/Items/Inventory.cs (the loop in SyncItemsAfterDelay that waits for the events to be received).
2. As soon as the breakpoint is hit, end the round in the server console.
3. Remove the breakpoint and resume the client
4. The round should now end and SyncItemsAfterDelay should still be running.
5. Start a new round

If that was the cause for this, https://github.com/Regalis11/Barotrauma-development/commit/06d3482204ec4f267c666f6b4f5d9b5038b8924e should fix it.

**Comment by Rokvach** [comment] 2020-02-05 12:20
We didn't encounter this in the latest Unstable build (703), but keeping it open still if something does come up.

**Comment by Rokvach** [comment] 2020-02-07 20:48
Seems to be fixed, closing.

**Closed by Rokvach** 2020-02-07 20:48 UTC
Labels: Bug, Code, Networking, Waiting
