### ISSUE TITLE
Character skills and trait reset when starting new round in multiplayer campaign (and maybe docking as well)

### ISSUE THREAD

**Issue by LethalJam** [Regalis11/Barotrauma#7843] opened 2021-12-17 22:52 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When starting a new round in a multiplayer campaign (and maybe docking as well), my character skills and trait reset. 
This started happening after playing the campaign for multiple hours and during several sessions.

**Steps To Reproduce**
We had just docked to an outpost. Then we bought a new submarine (Orca 2). We tried switching in the dockyard terminal but nothing happened. Then we read you might need to undock and dock to get it. So we did that (just undocking and docking to the same station without selecting any missions). After that we still couldn't switch. And at that point I looked at my skills and noticed they had all reset. After that I read some books to regain some skills but when we undocked for a new mission my skills reset once again.

**Version**
v0.15.21.0 using Windows 10

**Additional information**
[Saves.zip](https://github.com/Regalis11/Barotrauma/files/7738150/Saves.zip)

I guess I can just say that switching submarines is very confusing and I'm not sure if the switching issue I described is also a bug or if it's intended. I should also stress that it is only MY character out of 3 players whos skills reset. I was the host of the game. I attached my save files in case they are useful to you.

**Comment by zkxs** [comment] 2021-12-18 17:25
Might be a duplicate of #7791?

**Comment by LethalJam** [comment] 2021-12-19 01:59
Character's have a random trait that is listed under the name and role:
![image](https://user-images.githubusercontent.com/174756/146660915-b3f3e89b-da92-417a-8f19-96236f69c815.png)
This also resets in addition to the skills.

**Comment by thebuttsatisfier** [comment] 2021-12-19 18:15
Also confirming my crew's skills began resetting each time we docked approx 36 hours ago.

**Comment by Regalis11** [comment] 2022-01-03 08:53
Fixed in Duplicate of https://github.com/Regalis11/Barotrauma/issues/7755

**Closed by Regalis11** 2022-01-03 08:53 UTC
