### ISSUE TITLE
command "follow" and "incorrect routing of bots" in Barotrauma [added playback steps]

### ISSUE THREAD

**Issue by StranDead1** [Regalis11/Barotrauma#7266] opened 2021-11-11 10:50 UTC
- [No ] I have searched the issue tracker to check if the issue has already been reported.

command "follow" and "incorrect routing of bots" in Barotrauma

In a single company (I didn't check in multiplayer), there is a bug in which a character tied to you starts floating back, for no apparent reason. It is impossible to stop the character. Re-linking the character to yourself does not help, and the "stay put" command does not work either. As a result, the character either returns to the submarine, burying himself in the skin of the submarine, OR the character swims away to a secluded corner of the caves. There is also a "docking hatch" breakage bug, with this bug the character exits the submarine and swims back without doing anything. At least brew the passages with a welding machine or call the guards to shoot him like a madman and dangerous to the korobl. You can solve this if you just throw everything - fix everything yourself. But I'm the captain! I have to sit in the control room at the scanner and pick my nose! and not running around the submarine in an attempt to calm the crazy bots.
and also from "annoying". Watering can. Watering at a rate of 1 drop of water per minute. And as a result, you stand like a fool and water your beds instead of promoting the company. Of course, this is solved in multiplayer, the distribution of responsibilities. But in the company you can only rely on bots, and they can't take care of the beds, craft things or even banal replace cartridges in both!

Windows 10

steps to reproduce
1. link two characters to each other through the "follow" command (the captain and any other)
2. for the captain, swim out of the submarine and swim into the caves (you will already notice incorrect movements that alternate from cave to cave)
3. switch to the bot that is tied to the captain. 
4. sail away from the captain into the depths of the cave (watch as the captain, tied to you, swims to the submarine)

I attach a link to the video on YouTube, the "follow" bug is shown there
https://youtu.be/rUfAbRN8DaM

**Comment by ekqvist** [comment] 2021-12-03 12:02
Unfortunately, I couldn't reproduce the issues you described with the "Follow" and "Wait" orders. It seems that the AI-controlled character follow the orders correctly. Of course, it's possible there's been an issue that has already been fixed.

But when you play Character A, give a "Follow" order to character B, and then switch to control Character B, it is intentional that Character A will start swimming away, as they usually default to the "Find Safety" objective when they are outside.

So, only Character B (which you now control) is ordered to follow Character A (which the AI now controls), they aren't "linked" to follow each other.

The bug with bots having trouble fixing docking hatches sounds like #7232. If so, it should be fixed.

**Comment by Rokvach** [comment] 2021-12-03 15:36
I don't see any issues here, closing.

**Closed by Rokvach** 2021-12-03 15:36 UTC
Labels: Bug, Needs testing, Code
