### ISSUE TITLE
Unloading of every single item, inventory dropped, and NPC disappearance after wreck salvage mission

### ISSUE THREAD

**Issue by MageShooter** [Regalis11/Barotrauma#4460] opened 2020-12-10 08:25 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
This is a weird one. In a multiplayer campaign game, after we successfully completed a wreck salvaging mission, both of our characters were completely stripped of their inventories - uniforms, headsets, IDs, radios, hotbar, everything - and said items were lying on the floor in front of our characters. On top of it, every single item that held items - diving masks with O2 tanks, batteries in headsets, harpoons in the harpoon gun, toolbelts - were also unloaded and on the floor. Our NPCs had also seemingly vanished (though we caught one last message from one on the chat box).

Furthermore, even after getting re-equipped, both host and guest were running into issues such as invisible doors or doors closing extremely quickly. Trying to repair devices led to the character shuffling over to the device but ultimately not fixing it.

**Steps To Reproduce**
I'm not sure what could have caused it, so I'll get as specific as I can here for possible issues.
1. At mission start, the crew consisted of 3 players and 2 bots on the Dugong going from a military outpost to a natural formation in the Cold Caverns.
2. Two pets were hatched from eggs and subsequently murdered (one of the crew's a monster).
3. One player left mid-mission, leaving 2 players and 2 bots.
4. The sub "entered" the natural formation with the target logbook and the mission was passed successfully.
5. Upon loading the next zone, the above happened.

**Version**
This happened in game version v0.11.0.9. The OS of the host system and one other player was Windows 10 and the OS of another was Windows 8.1. Should it matter, this is happening between the host and the Windows 8.1 player.

**Additional information**
To my knowledge, no mods are being used. When I try to reload the campaign solo, everything is fine - inventory not dropped, bots present - but when my friend is with me when the campaign is reloaded, it consistently happens. We both tried verifying the game cache's integrity, but the issue persisted. We haven't yet tried to make it to another outpost with conditions as they are.

If it would help to visualize the matter, I have a video of trying to reload the save both as a [duo](https://drive.google.com/file/d/10ESxYYao6nXrLR8LB2nLi9eAdg46IWuM/view?usp=sharing) and [solo](https://drive.google.com/file/d/1onFnoxOjSVfPgc6tLjOfb2RVMJwSVcJC/view?usp=sharing).

**Comment by Kaillera** [comment] 2020-12-10 12:22
Rokvach and me encountered this at one point in Unstable, but I never saw it again since. All of our items just dropped onto the floor, and some things weren't operable or registering to the server. Restarting the server fixes it.

**Comment by MageShooter** [comment] 2020-12-10 18:32
Restarting didn't seem to fix it for us last night. When we encountered it, we first tried quitting to lobby and reloading the save, but it happened again. After that, we tried quitting out of the game entirely then starting the server and reloading the campaign again and it happened then, too (that was when we tried to verify the file integrity). Did you restart the server in a specific way so that I can try it later to see if it works for us?

**Comment by Kaillera** [comment] 2020-12-10 23:09
> Restarting didn't seem to fix it for us last night. When we encountered it, we first tried quitting to lobby and reloading the save, but it happened again. After that, we tried quitting out of the game entirely then starting the server and reloading the campaign again and it happened then, too (that was when we tried to verify the file integrity). Did you restart the server in a specific way so that I can try it later to see if it works for us?

We only closed down the server and restarted it.

**Comment by MageShooter** [comment] 2020-12-11 05:36
We haven't had any luck so far with restarting the server to fix it. We've closed out to the lobby and reloaded, closed to the main menu (shutting down the server entirely) and reloaded, and I've even tried commands like restart and close to shut it down before reloading but that hasn't worked for us, either. I tried having him join in the middle of me going solo (with bots) as I just parked us back at the beginning again (to load a new zone), but when he loaded into the next zone, it started doing it again. I'm not sure if the save has gone corrupt or if there's some sort of player count shenanigans going on, but clearly it doesn't want us playing this save as a duo again for some reason.

This hasn't persisted into a new campaign we're going to be working over (yet), so it's definitely something to do with that save in particular for some reason.

**Comment by Regalis11** [comment] 2020-12-11 09:24
Would it be possible to send us the save file? It might give us some more clues to help diagnose this. Note that the file needs to be zipped first to attach it to a comment in the issue tracker, because github doesn't allow attaching the .save file type.

**Comment by MageShooter** [comment] 2020-12-11 10:27
Sure thing. This should be the save and - in case it might help - I included the character data file, too. Hope this'll help.
[Bugged Save Files.zip](https://github.com/Regalis11/Barotrauma/files/5678571/Bugged.Save.Files.zip)

**Comment by PJB3005** [comment] 2020-12-11 23:47
[Barotrauma.zip](https://github.com/Regalis11/Barotrauma/files/5682095/Barotrauma.zip)

We just ran into this as well on our campaign (MP). Did a moloch kill mission to natural formation then went to a station from there. When we got there everything was FUBAR'd as described here.

**Comment by Nanatu** [comment] 2020-12-13 05:01
Same just happened to me and a friend playing multiplayer.
https://www.twitch.tv/videos/835553729 Timestamp, 2:30:00 or so.
Mission was kill a crawler swarm, I can get the save file uploaded later on if requested.

**Comment by Coryf88** [comment] 2020-12-17 14:52
A Logbook's `msg0` containing more than 1015 characters results in this issue occurring.

**Comment by xrabohrok** [comment] 2020-12-21 15:30
To build on @Coryf88 's development, this issue _can_ be bypassed by opening up the save file in your favorite XML text editor and searching for `log`, you'll know you found the right one if you find a terminal a bunch of lore looking text.  You can then just delete most of the content and the game will load normally again.

Conversely, the issue can be reproduced by overloading a log's text field.

**Comment by Regalis11** [comment] 2021-01-04 09:37
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4865150

**Comment by Rokvach** [comment] 2021-01-04 12:47
Tested by using a dedicated server and writing really long messages to the logbook and then switching levels, as well as looting the logbook from wrecks which had a really long message. Didn't encounter the issue in each test so this seems to be working correctly now. Closing.

**Closed by Rokvach** 2021-01-04 12:47 UTC
Labels: Bug, Code, High prio, Networking

**Comment by Jlobblet** [comment] 2021-02-07 19:12
Just encountered this again on the discord. v0.11.0.10. Modded save file. Deleting logbook from the CharacterData fixed the issue.
[Struggling.zip](https://github.com/Regalis11/Barotrauma/files/5939786/Struggling.zip)

**Comment by Jlobblet** [comment] 2021-02-07 23:45
Coincidentally just fixed another one. [ADAS.zip](https://github.com/Regalis11/Barotrauma/files/5940432/ADAS.zip). This has the same logbook text as the other one (Meltwater expedition, `terminalwelcomemsg.kastrulldiary1`). Makes me think this is the issue.
