### ISSUE TITLE
Crawlers can clip through the Azimuth's window on the command deck.

### ISSUE THREAD

**Issue by dion-perez** [Regalis11/Barotrauma#3957] opened 2020-09-30 18:54 UTC
- [ *] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When Captaining the sub on the command deck of the Azimuth, crawlers can get stuck in the north east corner of the submarine. If the sub is moving at a decent speed North East, and a crawler is stuck against the window, they will often clip through the window directly into the command deck and attack the player. This is definitely without a hull breach or any water otherwise coming into the command deck itself.

**Steps To Reproduce**
Have a crawler stuck on the Azimuth's window, then accelerate North East at a decent pace. The crawler will generally clip through the window directly into the command section of the Azimuth.

**Version**
Latest game version, windows.

**Comment by Regalis11** [comment] 2020-10-08 13:27
Even though this is about a specific sub, this is a general issue that affects other subs as well, so marking as a duplicate of https://github.com/Regalis11/Barotrauma/issues/3938

**Closed by Regalis11** 2020-10-08 13:27 UTC
Labels: Bug, Code
