### ISSUE TITLE
Tiger Treshers from "Kill swarm" mission spawned inside ground

### ISSUE THREAD

**Issue by DamnedTaube** [Regalis11/Barotrauma#11807] opened 2023-04-12 17:35 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

some Tiger Treshers from a "Kill Tresher Swarm" mission spawned inside a ground.
![image](https://user-images.githubusercontent.com/25986192/231537116-717aea59-4615-42e2-adad-caf810b10b83.png)

Structure above them is a Thalamus submarine (_if that might affect it somehow)_
Biome is The Great Sea.

### Reproduction steps

Dunno how to reproduce this error.

### Bug prevalence

Just once

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-04-12 18:50
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11162

**Closed by Regalis11** 2023-04-12 18:50 UTC
