### ISSUE TITLE
Incorrect scaling and offset sprites.

### ISSUE THREAD

**Issue by rav2n** [Regalis11/Barotrauma#1838] opened 2019-10-24 21:26 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
After the update, the following items are not displayed correctly on submarines made before to the current version:

Searchlight, Camera, Water Detector - the scale was 0.5 became 0.16
Shuttle Battery - was 0.5 became 0.2

Battery, Supercapacitor - the disappearance of the sprite, regardless of the depth of the sprite

Vent Connector A4, A7, Vent Large Pipe Bend A1 - sprite capture offset

**Steps To Reproduce**
Download any submarine builded before the patch 0.9.4.0 and check these items

**Version**
v0.9.4.0

**Additional information**
Problems arise only on already made submarines. When using of these items in the current version of the error is not observed.
![099](https://user-images.githubusercontent.com/29980468/67526645-e273c300-f6bd-11e9-910f-5e782ae4bd09.jpg)
![098](https://user-images.githubusercontent.com/29980468/67526661-ee5f8500-f6bd-11e9-91cd-a246cabc4c68.jpg)
![097](https://user-images.githubusercontent.com/29980468/67526673-f4edfc80-f6bd-11e9-9323-b7cdc4aa73fd.jpg)
![096](https://user-images.githubusercontent.com/29980468/67526688-fb7c7400-f6bd-11e9-84df-8e88d3fb233a.jpg)
![095](https://user-images.githubusercontent.com/29980468/67526703-020aeb80-f6be-11e9-968f-216db102bc24.jpg)

**Comment by Regalis11** [comment] 2019-10-25 08:25
I unfortunately wasn't able to reproduce the issue with the searchlight, camera, water detector, batteries or the supercapacitor; the items in the couple of submarines I tested (Svarog, Ex_Scrapper_MK_1, Ulysses, Apollo, EK_Coseus_Mk-II) seem to be working fine.

Are you using some kind of mods? Could you send the sub files in question, since they don't seem to be available in the workshop?

In any case, if you want to fix this in your own subs yourself before we get a fix out, the console command "resetselected" is very useful: it resets all the selected items/structures to match the values of the item prefab. 

![56yes5ry](https://user-images.githubusercontent.com/14351070/67554397-994c5f00-f70f-11e9-8465-2fe62036f9b9.png)

![eeeeeeasdg](https://user-images.githubusercontent.com/14351070/67554515-ddd7fa80-f70f-11e9-9bbf-cfbba851cf0f.png)

![asdgfdtshrth](https://user-images.githubusercontent.com/14351070/67555021-d533f400-f710-11e9-8ff3-41e2d79cb494.png)

**Comment by rav2n** [comment] 2019-10-25 11:51
I also thought that it was my problem. But I am aware of at least two more such cases.
In my case, the mods are not used or turned off. Although I modify the sprite files for ballons and tools (I like the old ones), I also use a modified Russian localization file (vanilla russian still leaves much to be desired). But this option is excluded, because I use two copies of the game to create submarines and the copy that is in the Steam directory has never been modified, and the error is reproduced in both copies.
Also, the other owner of such an error has no mods.
I will attach the submarines.



https://steamcommunity.com/sharedfiles/filedetails/?id=1892506214

[Svarog-dev.zip](https://github.com/Regalis11/Barotrauma/files/3771830/Svarog-dev.zip)
[OLD_MSV_Arioso.zip](https://github.com/Regalis11/Barotrauma/files/3771874/OLD_MSV_Arioso.zip)
[Arietta_dEuropa_NO_WORK.zip] (https://github.com/Regalis11/Barotrauma/files/3771877/Arietta_dEuropa_NO_WORK.zip)

**Comment by rav2n** [comment] 2019-10-25 12:17
By trial, we found out that the error is reproduced on submarines which were edited in the previous version v0.9.3.3

**Comment by rav2n** [comment] 2019-10-25 19:27
Also affected motion sensor

**Comment by Regalis11** [comment] 2019-10-28 21:59
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/d71c69142e27b8d52be3620d6c38205ce880d885 (private repo)

**Comment by Rokvach** [comment] 2019-11-04 12:57
This has been fixed and is working correctly, closing.

**Closed by Rokvach** 2019-11-04 12:57 UTC
Labels: Bug, Code
