### ISSUE TITLE
wrong localization used for scan ruin mission dialogue

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#10036] opened 2022-10-09 20:12 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

"I play Barotrauma in Latin Spanish but whenever the mission to scan the ruins appears, it appears in Russian"

https://www.reddit.com/r/Barotrauma/comments/xybzxk/i_play_barotrauma_in_latin_spanish_but_whenever/

![image](https://user-images.githubusercontent.com/5103517/194777492-01c41b2c-8f0a-4966-a1e0-dad855b191ff.png)

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by MaaiG** [comment] 2022-10-09 20:58
@Tsunder, where did you see Russian? :)
This is Polish.
![194777492-01c41b2c-8f0a-4966-a1e0-dad855b191ff](https://user-images.githubusercontent.com/93348499/194778698-9f591043-422e-4b16-82ae-39f9e8c0dabf.png)
The Russian text looks like this ;):
`«Запрос из научного отдела. Требуется составить карту ближайших руин. Естественно, за вознаграждение»`

The problem is aggravated by the fact that the Russian text is placed in the Polish localization!
The Russian localization contains Chinese text:
`<eventtext.missionevent_scanruin.c1>“科学家们提出一个请求。需要测绘附近的一个遗迹。当然，是有偿的。”</eventtext.missionevent_scanruin.c1>`
...etc.

**Comment by MaaiG** [comment] 2022-10-09 21:13
@Tsunder, where did you see Russian? :)))
This is Polish.
![194777492-01c41b2c-8f0a-4966-a1e0-dad855b191ff](https://user-images.githubusercontent.com/93348499/194778698-9f591043-422e-4b16-82ae-39f9e8c0dabf.png)

The Russian text looks like this ;):
`«Запрос из научного отдела. Требуется составить карту ближайших руин. Естественно, за вознаграждение»`
Russian alphabet = [Cyrillic alphabet](https://es.wikipedia.org/wiki/Alfabeto_cir%C3%ADlico). :)

The problem is aggravated by the fact that the Russian text is placed in the Polish localization!
The Russian localization contains Chinese text:
`<eventtext.missionevent_scanruin.c1>“科学家们提出一个请求。需要测绘附近的一个遗迹。当然，是有偿的。”</eventtext.missionevent_scanruin.c1>`
...etc.

**Comment by Regalis11** [comment] 2022-10-10 06:29
Looks like this line was displayed in an incorrect language in almost all the languages: it seems something had gone wrong in the sheet the translators add the translations to (all texts were shifted to an incorrect column). Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5d687693caba520efaf1ad5d0ee6c2c946a51c3b

**Comment by Rokvach** [comment] 2022-10-13 13:14
Tested, no issues. Closing.

**Closed by Rokvach** 2022-10-13 13:14 UTC
Labels: Bug, Code
