### ISSUE TITLE
Bugged Artifact Location

### ISSUE THREAD

**Issue by actiongirth** [Regalis11/Barotrauma#3776] opened 2020-09-08 21:06 UTC
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
On the mission "salvaging an artifact" it would seem the artifact spawned inside a cave wall

**Steps To Reproduce**
its probably got something to do with the level generation but I wouldnt know

**Version**
Current steam version, Windows

**Additional information**
https://ibb.co/wQd5Lbz
I love this game but its gonna give me an aneurysm

**Comment by Regalis11** [comment] 2020-09-09 06:31
Duplicate of https://github.com/Regalis11/Barotrauma/issues/2731

**Closed by Regalis11** 2020-09-09 06:31 UTC
