### ISSUE TITLE
Bonethresher eats/doesn't ignore engine

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5816] opened 2021-05-16 23:32 UTC
- [yeah] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When using a fast and thin sub such as the humpback, bonethreshers will target the engine if you're going to the right horizontally, and will make no attempts to target other places, so they'll stick to the engine, won't damage the hull, and die.

**Version**
Unstable v0.1400.0.0 (probably happens on stable too) Windows

**Comment by itchyOwl** [comment] 2021-05-26 09:52
Actually they do target the walls: ![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/f0f77f37-cc04-4379-829f-12229355b9a3)

It's intentional that Bonethreshers don't avoid the engine, unlike some other monsters. But that's not causing the issue.

The problem is not in targeting but reaching the target.

There's a margin added to the actual distance depending on what direction and how fast the target is moving because executing the attack takes some time to reach the target. Previously, when there was no margin, some creatures would just bite the water there and fail to reach the target when it moved. Without adding any margin, this would happen for example to Crawlers that start the attack much farther than they can actually hit the target.

In some cases, however, the calculated margin is too big, completely preventing the creature to reach a moving target. Such seems to be the case with Bonethreshers, which wouldn't actually need any margin, as their attacks should hit the target when they start. I think the same bug might have caused issues with other monsters too while chasing a moving target. Good that you noticed it!

I made some adjustments on the margin calculation what should fix the issue: Regalis11/Barotrauma-development@1c8c306.

**Comment by Rokvach** [comment] 2021-06-04 10:26
Tested, working correctly. Closing.

**Closed by Rokvach** 2021-06-04 10:26 UTC
Labels: Bug, Code
