### ISSUE TITLE
Mechanics Training Crash in Same Location

### ISSUE THREAD

**Issue by Teal302** [Regalis11/Barotrauma#6737] opened 2021-09-25 00:05 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I have tried completing the Mechanics Training course three times. Each time, it crashes after you are given more free reign and are supposed to repair the engine, when I try to repair the pump that is the closest to the engine, the game crashes. I have tried verifying the game cache, reinstalling the game, and restarting my computer, and the same thing keeps happening.

**Steps To Reproduce**
Try to play the Mechanics Training course and see what happens at that step.

**Version**
Current version, Windows.

**Additional information**
Barotrauma Client crash report (generated on 9/24/2021 7:59:49 PM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

48CA930394E1A7E117E5C694DE9CAF28

Game version 0.14.9.1 (ReleaseWindows, branch release, revision df0088ca33)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: nLoZLLtza
Loaded submarine: Dugong_Tutorial (8C7AD2F97BC9E420E76518CB2FE7E33D)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19042.0 64 bit
    GPU name: Intel(R) HD Graphics 4600
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.
 (SharpDX.SharpDXException)
Device removed reason: HRESULT = 0x887A0006
Target site: Void CheckError()
Stack trace: 
   at SharpDX.Result.CheckError()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 1017
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 511
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59

Last debug messages:
[9/24/2021 7:54:25 PM] Generating an outpost for the end of the level... (Location: Bramerton Station, level type: LocationConnection)
[9/24/2021 7:54:22 PM] Loading a pre-selected outpost for the start of the level...
[9/24/2021 7:54:00 PM] (Msg) SDR RelayNetworkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[9/24/2021 7:54:00 PM] (Msg) Ping location: atl=2+0,iad=16+1/15+0,dfw=19+1,ord=26+2/21+0,lax=48+4,sea=63+6/67+0,eat=/67+1,par=97+9/92+0,lhr=96+9/99+0,fra=102+10/100+0,gru=139+13/132+0,sgp=236+23/232+4
[9/24/2021 7:54:00 PM] (Msg) Ping measurement completed
[9/24/2021 7:54:00 PM] (Debug) Destroying relay 'sof#2 (139.45.193.10:27016)' because initial_ping_timeout
[9/24/2021 7:53:59 PM] (Debug) Destroying relay 'eat#30 (155.133.235.18:27044)' because initial_ping_timeout
[9/24/2021 7:53:57 PM] (Debug) Destroying relay 'sof#5 (139.45.193.10:27019)' because initial_ping_timeout
[9/24/2021 7:53:57 PM] (Debug) Destroying relay 'eat#18 (155.133.235.18:27032)' because initial_ping_timeout
[9/24/2021 7:53:55 PM] (Verbose) Communications with routing cluster 'sgp' established.
[9/24/2021 7:53:55 PM] (Verbose) Communications with routing cluster 'syd' established.
[9/24/2021 7:53:55 PM] (Verbose) Communications with routing cluster 'jnb' established.
[9/24/2021 7:53:55 PM] (Verbose) Communications with routing cluster 'tyo' established.
[9/24/2021 7:53:55 PM] (Verbose) Communications with routing cluster 'tyo1' established.
[9/24/2021 7:53:55 PM] (Verbose) Communications with routing cluster 'maa' established.
[9/24/2021 7:53:55 PM] (Verbose) Communications with routing cluster 'waw' established.
[9/24/2021 7:53:55 PM] (Verbose) Communications with routing cluster 'vie' established.
[9/24/2021 7:53:55 PM] (Verbose) Communications with routing cluster 'sto2' established.
[9/24/2021 7:53:55 PM] (Verbose) Communications with routing cluster 'sto' established.
[9/24/2021 7:53:54 PM] (Verbose) Communications with routing cluster 'sea' established.
[9/24/2021 7:53:54 PM] (Verbose) Communications with routing cluster 'bom' established.
[9/24/2021 7:53:54 PM] (Verbose) Communications with routing cluster 'scl' established.
[9/24/2021 7:53:54 PM] (Verbose) Communications with routing cluster 'lim' established.
[9/24/2021 7:53:54 PM] (Verbose) Communications with routing cluster 'mad' established.
[9/24/2021 7:53:54 PM] (Verbose) Communications with routing cluster 'dxb' established.
[9/24/2021 7:53:54 PM] (Verbose) Communications with routing cluster 'hkg' established.
[9/24/2021 7:53:54 PM] (Verbose) Communications with routing cluster 'par' established.
[9/24/2021 7:53:54 PM] (Verbose) Communications with routing cluster 'lhr' established.
[9/24/2021 7:53:54 PM] (Verbose) Communications with routing cluster 'eze' established.
[9/24/2021 7:53:54 PM] (Verbose) Communications with routing cluster 'lax' established.
[9/24/2021 7:53:54 PM] (Verbose) Communications with routing cluster 'gru' established.
[9/24/2021 7:53:54 PM] (Verbose) Communications with routing cluster 'ord' established.
[9/24/2021 7:53:54 PM] (Verbose) Communications with routing cluster 'iad' established.
[9/24/2021 7:53:54 PM] (Verbose) Communications with routing cluster 'fra' established.
[9/24/2021 7:53:54 PM] (Verbose) Communications with routing cluster 'ams' established.
[9/24/2021 7:53:54 PM] (Verbose) Communications with routing cluster 'dfw' established.
[9/24/2021 7:53:54 PM] (Verbose) Communications with routing cluster 'atl' established.
[9/24/2021 7:53:54 PM] (Msg) SDR RelayNetworkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[9/24/2021 7:53:54 PM] (Msg) Performing ping measurement
[9/24/2021 7:53:54 PM] (Msg) Got SDR network config.  Loaded revision 333 OK
[9/24/2021 7:53:54 PM] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[9/24/2021 7:53:44 PM] Attempting to open ALC device "OpenAL Soft on Speakers (Realtek High Definition Audio)"
[9/24/2021 7:53:43 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[9/24/2021 7:53:43 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[9/24/2021 7:53:42 PM] Logged in as Teal (SteamID STEAM_1:0:40146974)

**Comment by Regalis11** [comment] 2021-11-08 15:44
Duplicate of https://github.com/Regalis11/Barotrauma/issues/1833

**Closed by Regalis11** 2021-11-08 15:44 UTC
Labels: Bug, Code, Crash
