### ISSUE TITLE
[Unstable 0.17.10.0] Performance issue with out of control fires inside new cities

### ISSUE THREAD

**Issue by Crazydance15** [Regalis11/Barotrauma#8833] opened 2022-04-17 05:37 UTC
Cities look great especially with their large open spaces. However if the player causes a fire in one of the larger rooms in a city it can VERY quickly send one's computer back to the desktop screen.
I'm sure you can imagine.....

**Comment by Regalis11** [comment] 2022-04-20 17:50
Probably related: https://github.com/Regalis11/Barotrauma/issues/8264 (I suspect this is caused by a large number of bots trying to find paths at the same time)

**Comment by Rokvach** [comment] 2022-05-04 11:36
Tested, I didn't find any issues with this, can be merged.

**Comment by Rokvach** [comment] 2022-05-05 06:26
Closing.

**Closed by Rokvach** 2022-05-05 06:26 UTC
Labels: Code, Performance
