### ISSUE TITLE
Reactor catches on fire when there's an empty fuel rod and a non-empty one

### ISSUE THREAD

**Issue by Neko-LoverDisc** [Regalis11/Barotrauma#4391] opened 2020-11-26 16:44 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If a empty fuel rod is in the reactor at the same time as a full fuel rod, docking to a station will catch the reactor on fire

**Steps To Reproduce**
1. Have a full fuel rod in the reactor
2. Put a completely depleted fuel rod in the reactor alongside the full one
3. Dock to a station
4. Run down to the reactor room before your sub blows up

**Version**
Unstable, Linux

**Additional information**

**Comment by Regalis11** [comment] 2020-11-29 15:14
I'm afraid I wasn't able to reproduce this: the empty fuel rod doesn't seem to have any effect. I suspect that this had nothing to do with the empty fuel rod, but rather the power the submarine receives from the outpost. If the reactor was running at the "normal" rate and suddenly the sub started receiving all it's power from the outpost, it could've lead to overheating. 

However, this shouldn't normally happen: if automatic temperature control was on, the reactor should've turned down the fission rate to compensate for the extra power, and if it wasn't, the reactor should've been powered off at the start of the round.

Which submarine were you using? This could maybe be explained by some kind of a custom reactor control circuit failing to take the power received from the outpost into account.

**Comment by dylanstrategie** [comment] 2020-11-30 10:21
To add to the report, I had an incident very similar to this once that might be related since it seems to be caused by the reactor behaving improperly while outpost power is being routed

I was in a MP Campaign mission, docked to an Outpost after a mission. This was multiplayer so people were running around doing their outpost things, meanwhile I was fabricating a batch of gear on the ship. Suddenly, I heard and saw a fire. Our reactor actually caught on fire and I had to put it out before it exploded. This was with a default sub afaik, probably one of the power hungry ones.

Maybe the reactor isn't properly accounting for the outpost's "free power" ? And attempting to compensate for power draw on the ship, getting it wrong, and if the reactor has already been damaged during the mission this might be enough to critically damage it and start an engine fire before it turns back off.

I also noticed on the same vein that the reactor often seems to use up fuel rods while at dock as long as you're using stuff on the ship. Obviously it's best to turn off the reactor since the outpost gives you free power but the game doesn't do this by default. But this might indicate that the ship reactor is improperly turning on while docked to compensate for power draw, and damaging itself once the outpost reactor compensates.

**Comment by Neko-LoverDisc** [comment] 2020-11-30 13:13
I was using the Dugong, if that can help solve any of this, because docking to a station and then having a random chance of your reactor catching on fire sucks

**Comment by Coryf88** [comment] 2020-12-13 23:51
I was able to replicate it using a Thorium Fuel Rod and charging batteries at 75%. I don't know if its caused by a high battery recharge rate or just a high power draw when docking.

**Steps To Reproduce**
1. Use the Humpback sub. (I haven't tested others)
2. Turn the reactor off and put only a Thorium Fuel Rod in it.
3. Turn the battery backup on, and set the recharge rate to 0%.
4. Wait for batteries to drain. (Doesn't need to be completely, just enough so they are still charging when docking)
5. Turn the battery backup off and set the recharge rate of the batteries to 75%.
6. Turn the reactor on, manually correct the fission rate and turbine output, and enable automatic control.
7. Dock to the station.
8. Notice the reactor is on fire.

**Comment by Regalis11** [comment] 2021-07-09 08:53
Could not reproduce anymore with the above steps, may have been fixed in https://github.com/Regalis11/Barotrauma-development/commit/1de27efb

**Comment by Rokvach** [comment] 2021-08-04 08:28
Tested, no issues. Closing.

**Closed by Rokvach** 2021-08-04 08:28 UTC
Labels: Bug, Code, Medium Prio
