### ISSUE TITLE
Server Browser Crash

### ISSUE THREAD

**Issue by ConnorsSilverpaws** [Regalis11/Barotrauma#2700] opened 2020-04-25 07:52 UTC
**Description**
Client crashes at the server browser when attempting to uncheck the Sandbox button.

**Steps To Reproduce**
1. Load game
2. Server Browser
3. Uncheck "Sandbox" or "Mission" or "Campaign"

**Version**
Game version 0.9.9.0
OS: Windows 10 64bit

**Additional information**
Also tried checking other boxes beforehand, but crashes on unchecking those three independently.
[crashreport (35).log](https://github.com/Regalis11/Barotrauma/files/4532576/crashreport.35.log)
[crashreport (36).log](https://github.com/Regalis11/Barotrauma/files/4532577/crashreport.36.log)
[crashreport (37).log](https://github.com/Regalis11/Barotrauma/files/4532578/crashreport.37.log)

**Comment by Regalis11** [comment] 2020-04-25 13:59
Duplicate of #2567

This happens due when trying to filter servers in the server list based on game mode. We've got a hotfix coming for this issue soon, but for now it should be possible to work around it by not trying to filter the server list. Sorry for the trouble!

**Closed by Regalis11** 2020-04-25 13:59 UTC
