### ISSUE TITLE
The "items assembly" is kept and paste with offset.

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#9234] opened 2022-05-31 18:22 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Once the "item assembly" is created, it is stored without preview and when you try to insert the items assembly it is inserted not at the center of the cursor but with a strong offset relative to the cursor. And no preview (not visible) "item assembly".

### Reproduction steps

1. Start "Sub editor"
2. Save something as "item assembly"
3. Open tab "ItemAssembly"
**4. Your "item assembly" without previews!**
5. Select it and try to insert
**6. Your "items assembly" will be far from the cross mouse cursor! Sometimes it’s too far!**
https://user-images.githubusercontent.com/93348499/171258982-71b81942-9234-423b-ae43-8104dcd00838.mp4

### Bug prevalence

Happens every time I play

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-06-01 07:56
Duplicate of https://github.com/regalis11/barotrauma/issues/8737

**Closed by Regalis11** 2022-06-01 07:56 UTC
