### ISSUE TITLE
Places bots get stuck on Remora

### ISSUE THREAD

**Issue by Smau35** [Regalis11/Barotrauma#8248] opened 2022-02-12 15:33 UTC
Bots get stuck on Remoras docking port ladders if they are ordered to follow down to the ladders on the left
![Näyttökuva (1047)](https://user-images.githubusercontent.com/86321358/153717377-ab4fe486-2b18-40ed-a4aa-606a19ec765b.png)
The bots also can get stuck on the reactor room ladder platform when they jump down which could probably be fixed by increasing the size of the platform to the left
![Näyttökuva (1050)](https://user-images.githubusercontent.com/86321358/153717499-f665cf09-a1ac-46ee-9706-9f9590bacf5c.png)

**Version**
v0.15.23.0

**Comment by itchyOwl** [comment] 2022-04-07 08:25
I don't think those waypoint should be the issue there. There's a visibility check between the waypoints when the bots evaluate the paths. And those waypoints are not inside the walls or floors, even though they are close. The ladder issue might been caused by AI bugs, which have recently been addressed in unstable. Getting stuck on the floor corners is probably duplicate of #2296?

**Comment by itchyOwl** [comment] 2023-01-23 11:47
Can't repro. Possibly fixed? Stucking on corners (#2296) is unrelated to bots: players can also get stuck.

**Comment by Rokvach** [comment] 2023-02-13 10:35
Bots and even players getting stuck on the corners of a wall is a old and known issue which doesn't need to be tested here, so just needs a checkup on the actual AI issues.

**Comment by NilanthAnimosus** [comment] 2023-02-14 13:09
Tested against Dev commit https://github.com/Regalis11/Barotrauma-development/commit/25a97c596fd53131e14f5671ca49cc2d2c84b4c0

Of the previous issues (with the exception of getting stuck on walls) the AI no longer seems to get stuck on the ladders unable to get off them.

the issue with corners is still there, though as noted above this would effect other submarines and players in general.

There was a minor AI issue that was hard to reproduce involving the ladders but in a different way:

This case was partially reproducible by having them seek a path to the command room and teleporting them (repeatedly until they got stuck) roughly in the red circled area:
![image](https://user-images.githubusercontent.com/29177976/218745724-3e1888e2-0dea-455e-b918-535ccceb8597.png)

as well as this case which the pathfinding is slightly different (Could not reproduce though) for an AI stuck at the ladders trying to head down, while the pathfinding seems to indicate heading right then down:
![image](https://user-images.githubusercontent.com/29177976/218747913-14004b6d-ad3f-4ae9-8ee9-bf01d9fe8a16.png)

**Comment by AzureNocte** [comment] 2023-03-10 23:05
I've encountered this issue too, when bots are trying to fix the upper hatch, they will just wander around near ladder

**Comment by itchyOwl** [comment] 2023-05-03 10:52
Managed to repro and debug it: ![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/3da70090-256f-43ef-a543-433d54634459)

Here the bot is unable to release from the ladders, because there's another ladder just next to them, which they can't yet reach. Fixed in Regalis11/Barotrauma-development@d40b9eb.

**Closed** 2023-05-29 08:30 UTC
Labels: Bug, Code
