### ISSUE TITLE
Unstable - Crawlers spawn inside the sub during the beacon mission

### ISSUE THREAD

**Issue by Mikolaj1900G** [Regalis11/Barotrauma#4241] opened 2020-11-06 22:15 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
During the new beacon mission, a swarm of crawlers spawned inside my sub's airlock when they usually spawn somewhere near the structure.

**Steps To Reproduce**
Swim close to the station (Like in the attached screenshot) and power up the station's beacon. The crawlers spawned inside the sub.

**Version**
Unstable 0.1100.0.4 Windows

**Additional information**
![beacon crawlers1](https://user-images.githubusercontent.com/57800630/98419698-e6367580-2085-11eb-85e7-11f054086b6d.png)
![beacon crawlers2](https://user-images.githubusercontent.com/57800630/98419702-e767a280-2085-11eb-850f-8c2c52272e02.png)

**Comment by Regalis11** [comment] 2020-11-07 13:45
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1137974a26a4bb2224eaa92122400c8bd608c034

**Comment by Xeavas** [comment] 2020-11-11 19:18
[0.1100.0.5] - Unable to replicate 👍

**Comment by Rokvach** [comment] 2020-11-11 21:19
Closing.

**Comment by lesliev** [comment] 2022-01-01 09:21
This just happened to us tonight, in Barotrauma build 7896730. We had just entered a station when we got a notification our sub was under attack and when we got back it was chock full of crawlers with one of our NPC teammates dead despite two other NPC security officers doing their best to defend. Steam says "installed content updated Dec 22, 2021".

**Comment by lesliev** [comment] 2022-01-01 09:23
Seems it's happened on multiple occations for others too, 3 months back:
https://www.reddit.com/r/Barotrauma/comments/q7q5u9/sonar_beacon_spawns_monsters_inside_submarine/

**Comment by Orum** [comment] 2023-02-14 02:11
This happened to us the other day, though not crawlers.  Husks spawned on our sub immediately after activating a beacon.

**Comment by Regalis11** [comment] 2023-03-09 10:44
Save for testing this:
[Save 18.zip](https://github.com/Regalis11/Barotrauma/files/10930538/Save.18.zip)

Steps to repro:
1. Load the save (I tested in version v1.0.7.0)
2. Enable debugdraw
3. Park the submarine exactly at the waypoint above the beacon station (that waypoint is also used as a spawnpoint)
![image](https://user-images.githubusercontent.com/14351070/224000694-24244b9e-a31c-4d29-b987-05b41b2a2e1d.png)

5. Restore the beacon station

**Comment by AdamH-Daedalic** [comment] 2023-06-30 08:36
Tested against the fix/beacon-spawn-inside-sub branch 

This issue still reproduces fairly regularly when following the repro steps provided above and using the Save 18 savedata. It appears to reproduce most often when the waypoint is located in the lower portion/decks of the submarine, allowing more of the submarine to be above it, which is where the monsters seem to spawn. 

<img width="1684" alt="Spawninsub" src="https://github.com/Regalis11/Barotrauma/assets/135589009/75dd1616-843a-43c2-b30d-83ef13ef0dd8">

**Comment by Regalis11** [comment] 2023-06-30 09:54
Hopefully fixed for good now: https://github.com/Regalis11/Barotrauma-development/pull/4076/commits/9f5f37029d37c4734bf4d3d8088d46927d21e857

**Comment by AdamH-Daedalic** [comment] 2023-07-03 12:52
Unable to reproduce the issue. After activating the beacon and parking the sub at the waypoint location, no monsters spawn inside the sub, only outside the sub at varying distances each attempt. Closing

**Closed by AdamH-Daedalic** 2023-07-03 12:52 UTC
Labels: Bug, Code
