### ISSUE TITLE
Crash on round start as client (An issue with doors?)

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#291] opened 2018-02-26 09:33 UTC
Version 0.8.0.4 (Vanilla code)

Barotrauma Client crash report (generated on 26/02/2018 09:28:48)

Barotrauma seems to have crashed. Sorry for the inconvenience! 
If you'd like to help fix the bug that caused the crash, please send this file to the developers on the Undertow Games forums.

Game version 0.8.0.4
Graphics mode: 1920x1080 (BorderlessWindowed)
Selected content package: Vanilla 0.8
Level seed: UOqP5D6U
Loaded submarine: VIS Varuna XEC-2 (008C203BE4FFD06D873ECDC3201A86A3)
Selected screen: Barotrauma.GameScreen
Client (Round had started)

System info:
    Operating system: Microsoft Windows NT 6.1.7601 Service Pack 1 64 bit
    GPU name: NVIDIA GeForce GTX 970
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.777778}
    GPU status: Normal

Exception: Value cannot be null.
Parameter name: source
Target site: System.Collections.Generic.IEnumerable`1[TResult] Select[TSource,TResult](System.Collections.Generic.IEnumerable`1[TSource], System.Func`2[TSource,TResult])
Stack trace: 
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Barotrauma.Items.Components.Door.PushCharactersAway() in E:\Barotrauma\Barotrauma\BarotraumaShared\Source\Items\Components\Door.cs:line 365
   at Barotrauma.Items.Components.Door.Update(Single deltaTime, Camera cam) in E:\Barotrauma\Barotrauma\BarotraumaShared\Source\Items\Components\Door.cs:line 274
   at Barotrauma.Item.Update(Single deltaTime, Camera cam) in E:\Barotrauma\Barotrauma\BarotraumaShared\Source\Items\Item.cs:line 825
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in E:\Barotrauma\Barotrauma\BarotraumaShared\Source\Map\MapEntity.cs:line 317
   at Barotrauma.GameScreen.Update(Double deltaTime) in E:\Barotrauma\Barotrauma\BarotraumaShared\Source\Screens\GameScreen.cs:line 121
   at Barotrauma.GameMain.Update(GameTime gameTime) in E:\Barotrauma\Barotrauma\BarotraumaClient\Source\GameMain.cs:line 414
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at MonoGame.Framework.WinFormsGameWindow.RunLoop()
   at MonoGame.Framework.WinFormsGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Barotrauma.Program.Main() in E:\Barotrauma\Barotrauma\BarotraumaClient\Source\Program.cs:line 41

Last debug messages:
   26/02/2018 09:28:47 - Error loading item - item prefab "Heat Absorber" not found.
   26/02/2018 09:28:47 - Error loading item - item prefab "Heat Absorber" not found.
   26/02/2018 09:28:47 - Error loading item - item prefab "Heat Absorber" not found.
   26/02/2018 09:28:47 - Error loading item - item prefab "Heat Absorber" not found.
   26/02/2018 09:28:47 - Error loading item - item prefab "Heat Absorber" not found.
   26/02/2018 09:26:55 - Writing object data to "crashreport_object.bin", please send this file to us at http://github.com/Regalis11/Barotrauma/issues
   26/02/2018 09:26:55 -  - NULL
   26/02/2018 09:26:55 -  - NULL
   26/02/2018 09:26:55 -  - NULL
   26/02/2018 09:26:55 -  - Matt Parker
   26/02/2018 09:26:55 -  - Barotrauma.EntitySpawner
   26/02/2018 09:26:55 - Previous object was 8 bits long (1 bytes)
   26/02/2018 09:26:55 - Previous object type: ENTITY_EVENT
   26/02/2018 09:26:55 - Error while reading update from server (unknown object header "67"!)
   26/02/2018 09:26:55 - READING CHARACTER SPAWN DATA
   26/02/2018 09:25:00 - READING CHARACTER SPAWN DATA

**Comment by Regalis11** [comment] 2018-02-26 12:03
Seems to be caused by the Limbs-field being null (the same problem as #278)

**Comment by Regalis11** [comment] 2018-02-27 15:18
Closing this, as it appears to be the same one as #278

**Closed by Regalis11** 2018-02-27 15:18 UTC
Labels: bug
