### ISSUE TITLE
No tooltips in cabinet UI when you open fabricator.

### ISSUE THREAD

**Issue by N58** [Regalis11/Barotrauma#5170] opened 2021-03-02 21:37 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.
(hope it's not duplicate)

**Description**
When I open fabricator that is linked to Large Steel Cabinet, I want to get something from cabinet but when I hover on for example Storage Container, then there is no tooltip. When I open this cabinet it works fine on cabinet and on fabricator. That's really annoying thing.

**Steps To Reproduce**
1. Place cabinet and fabricator.
2. Link fabricator to cabinet.
3. Open fabricator and hover on some item in cabinet UI.

**Version**
Windows 10
v0.12.0.3, stable

**Additional information**
Just fix it as fast as you can. That's annoying bug!

**Comment by 3e849f2e5c** [comment] 2021-03-03 12:57
Duplicate of #5008

**Closed by 3e849f2e5c** 2021-03-03 12:57 UTC
