### ISSUE TITLE
[0.9.7] Multiplayer - Crazy FPS Drop, Desync, Massive Explosion Out of Nowhere ETC...

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2353] opened 2020-02-22 23:11 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
[Barotrauma.zip](https://github.com/Regalis11/Barotrauma/files/4240358/Barotrauma.zip)

Server event lagging behind very badly
Massive FPS Drop
Player Desync
Massive Explosion out of nowhere
Game Freezes

**Steps To Reproduce**
Choose Skaani Habitational Outpost or some other neighboring locations going toward the center in multiplayer.

**Version**
0.9.7

**Additional Informations**
Also a weird quirk the round before starting this one when we were at the end station. We noticed our middle ballast pumps decided to stop pumping, despite there being power and is on. We had to turn them off and on for it to be functional again. Not sure if it was a warning call to this problem.

We also have a cargo box docked to a cargo box, which is docked to the main sub. Not sure if that messed up the level generation either.

**Comment by Kaillera** [comment] 2020-02-22 23:15
[The Aeche (III).zip](https://github.com/Regalis11/Barotrauma/files/4240380/The.Aeche.III.zip)

Sub file here.

**Comment by Rokvach** [comment] 2020-02-22 23:34
Seems to be 100% reproducible, not sure about the cause could be level generation. There's always a massive explosion when the round starts and everything freezes up. After a while if you are lucky your character will spawn in but the fps will be at 15. 

You spawn at the destination outpost.

Flying around the level using freecamera shows that the whole level generation is just broken

Submarine walls will be fully damaged even if you buy a repair from lobby, so something does actually explode. 

![brokenlevel.jpg](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/d616abdd-585f-4868-8996-4886c4b1ee3a)

**Comment by Kaillera** [comment] 2020-02-23 17:16
I found out how to reproduce this problem in singleplayer with the same sub.

I have Cargo 2 (Shuttle) docked to Cargo 1 (Shuttle) from underneath, and is docked to the Main Sub. Starting the next round caused the problem mentioned above.

**Comment by Kaillera** [comment] 2020-02-23 23:53
apparently when my shuttles aren't docked at the original hatches, it also sets it off.

**Comment by juanjp600** [comment] 2020-02-24 14:35
Mapgen for this case should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/24589a37698f15ca2ddf99504b8a70dcab8aab03; there is still something wrong with the positioning of the sub that causes one of the shuttles to be placed really far down the map, crippling the server

**Comment by juanjp600** [comment] 2020-02-24 19:02
Docked sub positions are now corrected in https://github.com/Regalis11/Barotrauma-development/commit/962e3fb90e6895da2c486cb2d0238fb7c53f4f70, fixing the major performance issues in this case. Some bugs remain, but the save seem to be playable again.

**Comment by Rokvach** [comment] 2020-02-25 11:30
Couldn't reproduce the issue, so seems to be working correctly. Closing.

**Closed by Rokvach** 2020-02-25 11:30 UTC
Labels: Bug, Code, Crash
