### ISSUE TITLE
Wrecked sub ID card claiming task/mission or just nice little price in marks for sell.

### ISSUE THREAD

**Issue by Stallfighter** [Regalis11/Barotrauma#4419] opened 2020-12-01 01:18 UTC
- [+] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I suggest to add some kind of reward for finding dead crew IDs inside wrecked subs, because they are akin dogtags in Europe undersea world. A special task would be nice, but temporarily you can add some actual price to wreck ID cards.

**Comment by ezjamsen** [comment] 2020-12-01 13:19
Nice idea. Let's see about creating some new mission objectives with this in mind.

**Comment by linax3-genuine** [comment] 2021-12-04 20:06
i retrieve the bodies, too. i think someone cares for them(as it says on duffle bags). this should be true for non-mission wrecks, too. missions should pay rep+marks from the related factions. for non-mission - just reputation.
probably a bodybag item would be needed, as the game does not like to keep bodies around.

**Comment by Regalis11** [comment] 2022-03-24 13:19
Duplicate of https://github.com/regalis11/barotrauma/issues/3451

**Closed by Regalis11** 2022-03-24 13:19 UTC
Labels: Feature request, Design
