### ISSUE TITLE
Add a way to randomize your appearance in the lobby

### ISSUE THREAD

**Issue by EdusFF** [Regalis11/Barotrauma#1881] opened 2019-11-15 13:19 UTC
Allow the player to randomize his / her character's appearance inside the lobby by adding a 'randomize' button to the UI

**Comment by Regalis11** [comment] 2019-11-17 18:51
Duplicate of https://github.com/Regalis11/Barotrauma-development/issues/1022

**Closed by Regalis11** 2019-11-17 18:51 UTC
Labels: Code, Feature request
