### ISSUE TITLE
Upgrading module durability negatively impacts repairs

### ISSUE THREAD

**Issue by Aurani** [Regalis11/Barotrauma#7085] opened 2021-10-30 00:18 UTC
- [x ] I have searched the issue tracker to check if the issue has already been reported.

Upgrading durability of onboard devices (junction boxes, etc.) lowers the threshold for repairing them as low as ~40% condition before you can attempt repairs. This leads to a variety of issues as penalties build up such as with the navigation console that just gets more and more glitchy and unresponsive and you can't do anything about it since you can't repair it until its severely damaged.

**Comment by Ek-Videogames** [comment] 2021-11-01 15:46
Expected behavior: 
Repair threshold acts as a percentage not a health value ?

**Comment by Regalis11** [comment] 2021-11-02 15:51
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c2ecd279d2e90719686bb7bde16780d7f0bb8706

**Comment by Ek-Videogames** [comment] 2021-11-08 04:08
Something also important to take note of:
Items appear 'damaged' after the upgrade is applied because they retain their old condition value when the maxhealth is increased. Items should probably 'repair' up to the equivalent percent of damage they were at relative to the new maxhealth to avoid this? Is this accounted for in the fix implementation?

**Comment by Jvisti** [comment] 2021-11-17 01:36
Sorry to be a bother but I can't for the life of me find clear information on this matter. Is this fix implemented only in the unstable version so far?

**Comment by Rokvach** [comment] 2021-11-29 12:52
Tested, working correctly. Closing.

**Closed by Rokvach** 2021-11-29 12:52 UTC
Labels: Bug, Code, Design
