### ISSUE TITLE
Having more talent points than talents stops you from spending any talent points.

### ISSUE THREAD

**Issue by WrillWasTaken** [Regalis11/Barotrauma#7827] opened 2021-12-17 13:01 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Having more talent points than talents remaining makes you completely unable to gain any new talents.

**Steps To Reproduce**
Get 13 talent points. Try spend them all.

**Version**
Windows, V0.15.22.1

**Additional information**
A simple fix might be to allow players to apply their talent points without spending all of them in one go.

**Comment by Regalis11** [comment] 2021-12-17 13:32
I'm afraid I couldn't reproduce this. Got 13 talent points:
![image](https://user-images.githubusercontent.com/14351070/146552146-8267bce4-014a-4d14-be99-32dcbbb1e739.png)
And I was able to spend all of them with no issues:
![image](https://user-images.githubusercontent.com/14351070/146552212-7dbb7ecb-cd3e-443e-822c-908961ae6180.png)

**Comment by WrillWasTaken** [comment] 2021-12-17 13:33
Huh. Let me try reproduce it again.

**Comment by WrillWasTaken** [comment] 2021-12-17 13:36
That's strange, I can't seem to reproduce this issue.

**Comment by Regalis11** [comment] 2022-01-07 11:59
No known steps to repro, closing

**Closed by Regalis11** 2022-01-07 11:59 UTC
Labels: Bug, Need more info, Code
