### ISSUE TITLE
Multiplayer - Nest Mission Entity ID's Scramble

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4326] opened 2020-11-15 23:06 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
https://www.twitch.tv/videos/804257031
From: 2:04:00 to 2:53:30
So we picked up Tiger Thresher Nest Mission at an outpost and recovered our lost drone. Started the mission and played it out. We lost the drone in the level again and then server lobbied to save scum because our situation was bad/waste of time. We restarted the level and found our drone missing, and decided to redock the station to recover the drone. We did tried to do the same Tiger Thresher Nest Mission again.

From 2:54:00 to 3:34:00
Upon loading the Tiger Thresher Nest Mission again, we received errors in the console about the thresher egg ID.
[dump.txt](https://github.com/Regalis11/Barotrauma/files/5543293/dump.txt)

One of our crew member (Topsen) had his entire inventory replaced by thresher eggs and dropped them on the floor (His point of view https://www.twitch.tv/videos/804263160?t=02h50m24s). We redocked the outpost, and those eggs reconverted back to his items. We went back into the level and received the same errors again, but this time the eggs seem to have replaced other things in the level, which turned out to have replaced the Ores in the level next to the eggs @ 3:32:40.

**Version**
0.1100.0.6

**Comment by Regalis11** [comment] 2020-11-16 11:07
Looks like this can be reproduced quite easily:
1. Start a nest mission
2. Return back to the outpost without completing the mission
3. Select the mission again

Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/466dd60490fc4d3a7d638f66435d46b458a95ebc

**Comment by ekqvist** [comment] 2020-11-16 13:23
Same issue for the mineral missions should be fixed in Regalis11/Barotrauma-development@b8ccc82

**Comment by Rokvach** [comment] 2020-11-19 09:28
This seems to be working correctly now. Closing.

**Closed by Rokvach** 2020-11-19 09:28 UTC
Labels: Bug, Code, Networking
