### ISSUE TITLE
[0.9.9.1] Uploading mods as Core Content Packages doesn't work.

### ISSUE THREAD

**Issue by HalfdeadKiller** [Regalis11/Barotrauma#2798] opened 2020-05-10 16:51 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Currently in order to upload a core content package the filelist must contain pretty much all of Vanilla 0.9.xml, with edits to the paths as required for modifying the core content. However the in game uploader doesn't read the vanilla path's and just throws an error about requiring certain things defined, even though they are defined in the filelist.xml.

Edit: Specifically it requires the Game.exe and DedicatedServer.exe defined.

Also minor annoyance, the in game uploader deletes comments in filelist.xml. This isn't too big of a deal but makes organizing edits slightly difficult without having an external filelist.txt to copy from.

**Steps To Reproduce**
Make a core content package, edit the path of an item, and try to upload.

**Version**
Barotrauma 0.9.9.1 - Windows 10

**Additional information**
Ignore the random None filetypes, those are tests of XML Patching and stuff.
In game uploader.
![image](https://user-images.githubusercontent.com/16188887/81505412-89aff480-92b4-11ea-8d94-353463f4bf96.png)

Actual filelist.xml I'm trying to upload.
![image](https://user-images.githubusercontent.com/16188887/81505417-946a8980-92b4-11ea-9250-c96b1be721cc.png)

**Comment by Ant1V1RU5** [comment] 2020-05-10 16:57
I can relate to this.

**Comment by Regalis11** [comment] 2020-05-10 17:25
TODO note:
Seems to have been caused by https://github.com/Regalis11/Barotrauma-development/pull/1310: SteamWorkshopScreen.RefreshCreateItemFileList seems to ignore the files defined in the content package altogether and just includes what's inside the mod folder.

**Comment by juanjp600** [comment] 2020-05-12 13:01
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/566afa695b8bf292874246c038c295e4c06765e7; numerous changes were needed, so this should be tested extensively.

**Comment by Regalis11** [comment] 2020-05-12 13:33
Spotted a couple of issues:
1. Created a core package that's just a copy of the vanilla content package with just a filelist.xml referencing vanilla content.
2. Selected that package.
3. Published it in the Workshop.
4. When I went back to the game settings, the Vanilla package was selected instead of the mod.

After that, when I relaunched the game I got a notification about the package getting updated, which probably shouldn't happen?

**Comment by juanjp600** [comment] 2020-05-12 17:24
@Regalis11 Both issues should now be fixed in https://github.com/Regalis11/Barotrauma-development/commit/84a6cf96b2a4335ce1dd82244c7a08b31051fbfe.

**Comment by Rokvach** [comment] 2020-05-19 12:51
Tested in current Unstable

I tried publishing BTE and then turned Vanilla in to a core mod and tried to publish that as well, but the game just straight up closes without any crash report on both tries. @juanjp600

**Comment by Rokvach** [comment] 2020-05-19 13:14
Same happens if I create a core mod which just contains a filelist.xml which references all the vanilla content, the game just closes without any prior warnings.

**Comment by Rokvach** [comment] 2020-05-19 13:16
Update: Seems like the issue only happens when trying to publish a core mod from Unstable.

**Comment by juanjp600** [comment] 2020-05-19 19:15
Unstable-related crash should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/5b405ee36ca1166efeb7f974e5ccffe1949c6d6d

**Comment by Rokvach** [comment] 2020-05-19 20:07
Wasn't able to reproduce the issue anymore, working correctly. Closing.

**Closed by Rokvach** 2020-05-19 20:07 UTC
Labels: Bug, Code, Modding
