### ISSUE TITLE
Item Assembly with non-standard parameters dont work properly

### ISSUE THREAD

**Issue by PanmanS** [Regalis11/Barotrauma#11992] opened 2023-05-11 20:29 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In very short, some parameters in assemblies simply dont apply when placed in editor. Use assembly in reproduction page to test it!

### Reproduction steps

![image](https://github.com/Regalis11/Barotrauma/assets/42521948/81bf11ac-e1c3-4540-a621-2906dfc20ff6)
1. download assembly [All_Doors_Welded.zip](https://github.com/Regalis11/Barotrauma/files/11456093/All_Doors_Welded.zip)
2. launch sub editor
3. try to put it down
4. observe lack of welding

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-05-12 08:29
Could not reproduce. Looking at your screenshot, the doors are clearly welded. Also tested this myself and everything seems to be working correctly:
![image](https://github.com/Regalis11/Barotrauma/assets/14351070/9f956623-6c16-4a3b-95c6-cf309195cad5)

**Comment by PanmanS** [comment] 2023-05-12 12:35
my man im gonna cry, im on a streak of "user moment"

But here's another way that might introduce this behavior:
1. launch test or quickstart dugong
2. weld one of the door
3. force-enter sub editor via subeditor command
4. save welded door as assembly
5. load different sub
6. try to place it

**Comment by PanmanS** [comment] 2023-05-12 12:43
also

Doors will be welded during the spawn, but if you copy them, they will become unwelded
or if you gonna run the test, they will lose welded status
And after leaving the editor they will also lose their stuckness.

**Comment by PanmanS** [comment] 2023-05-12 12:54
https://youtu.be/6NJBt_OsaJo

**Comment by Regalis11** [comment] 2023-05-14 17:31
Thanks for the extra info! It seems copypasting was the issue: the values of properties that can't be edited in the sub editor didn't carry over to the copy. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/77773d31ac7a8fc6ceea3d4c21f4973e2c492ee9 (commit in our private repo)

**Comment by Jasontti** [comment] 2023-06-06 08:24
Tested and works. Copy & paste, saving to assembly and between testing.
Closing ticket.

**Closed by Jasontti** 2023-06-06 08:24 UTC
Labels: Bug, Code
