### ISSUE TITLE
Weird (hardware?) graphics bug 

### ISSUE THREAD

**Issue by XxBarotraumaBugReporterxX** [Regalis11/Barotrauma#8966] opened 2022-04-25 10:24 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
You can see it in the video although it was longer and the big squares flickered. But before the squares the screen went black and back up and then the squares 

**Steps To Reproduce**
Damn i have no idea, sorry, i would've recorded the last 15 seconds with GeForce overlay but it only recorded the last 4 since i think what happened is that it bugged the graphics card so it bugged the graphic card's overlay

**Version**
0.17.12.0 on windows 10 family

**Additional information**
My GeForce overlay stopped working after the crash, rebooting it will probably make it work

[crashreport.log](https://github.com/Regalis11/Barotrauma/files/8553615/crashreport.log)

https://user-images.githubusercontent.com/104356694/165069752-42f10f8f-7d31-4f2f-bdd1-5dd2c42d3b00.mp4

**Comment by XxBarotraumaBugReporterxX** [comment] 2022-04-25 10:25
Playing with loads and loads of mods does that i guess

**Comment by Regalis11** [comment] 2022-06-06 18:21
Possibly related to https://github.com/Regalis11/Barotrauma/issues/9213

**Comment by NilanthAnimosus** [comment] 2022-08-03 09:19
Not even sure where/how to test this or what to do with it, I am noting the game version is 0.17.12.0 and there are mods running that also change the games code I believe

Specifically from the crash report looks like clientside LUA exists (?):
[25/04/2022 11:59:31] Performance Fix: Executing init.lua
[25/04/2022 11:59:31] Neurotrauma: Executing init.lua
[25/04/2022 11:59:31] Neurotrauma Cybernetics: Executing init.lua
[25/04/2022 11:59:30] Lua! Version 2c1329fa3

So its very unlikely I could even replicate the condition the executable was in for that version when this happened though I don't strictly think its related to the GPU issues.

I translated the error, and its "The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action." - which implies the drivers crashed or the GPU was effectively removed for the RTX 3090. the cortex issue was a blendstate error involving certain software, If its a similar issue I don't think its the same software/problem or related to cortex in general - and although perhaps related to geforce overlay I imagine many people use geforce overlay (myself included).

**Comment by Rokvach** [comment] 2022-09-12 15:07
This issue is most likely caused by the users hardware or even some software that isn't compatible enough with baro, as its hard to tell what causes this and even harder to think how to reproduce it I think its just better to close this ticket. Closing.

**Closed by Rokvach** 2022-09-12 15:07 UTC
Labels: Bug, Needs testing, Code
