### ISSUE TITLE
Game crashed when start

### ISSUE THREAD

**Issue by mihudan** [Regalis11/Barotrauma#7795] opened 2021-12-16 08:25 UTC
Barotrauma Client crash report (generated on 12/16/2021 4:23:16 PM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

C4161C5B0C1FBD8D2ABA8510772A7EB5

Game version 0.15.21.0 (ReleaseMac, branch release, revision 31b8ac03f4)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: Traditional Chinese
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized

System info:
    Operating system: Unix 21.1.0.0 64 bit
    GPU name: 
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: The type initializer for 'GameAnalyticsSDK.Net.Logging.GALogger' threw an exception. (System.TypeInitializationException)
Target site: Void D(System.String)
Stack trace: 
   at GameAnalyticsSDK.Net.Logging.GALogger.D(String format) in <DEV>/Libraries/GameAnalytics/GA-SDK-MONO-SHARED/Logging/GALogger.cs:line 143
   at GameAnalyticsSDK.Net.GameAnalytics.OnQuit() in <DEV>/Libraries/GameAnalytics/GA-SDK-MONO-SHARED/GameAnalytics.cs:line 737
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

InnerException: The type initializer for 'GameAnalyticsSDK.Net.Device.GADevice' threw an exception.
Target site: Void .ctor()
Stack trace: 
   at GameAnalyticsSDK.Net.Logging.GALogger..ctor() in <DEV>/Libraries/GameAnalytics/GA-SDK-MONO-SHARED/Logging/GALogger.cs:line 88
   at GameAnalyticsSDK.Net.Logging.GALogger..cctor() in <DEV>/Libraries/GameAnalytics/GA-SDK-MONO-SHARED/Logging/GALogger.cs:line 20
Last debug messages:
[12/16/2021 4:23:16 PM] Initializing GameAnalytics failed. Disabling user statistics... {Exception has been thrown by the target of an invocation.}
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Barotrauma.GameAnalyticsManager.Implementation.<>c__DisplayClass34_0`2.<Call>b__0(T1 arg1, T2 arg2) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameAnalytics/GameAnalyticsManager.cs:line 114
   at Barotrauma.GameAnalyticsManager.Implementation.Initialize(String gameKey, String secretKey) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameAnalytics/GameAnalyticsManager.cs:line 39
   at Barotrauma.GameAnalyticsManager.InitKeys() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameAnalytics/GameAnalyticsKeys.cs:line 11
   at Barotrauma.GameAnalyticsManager.Init() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameAnalytics/GameAnalyticsManager.cs:line 352

Inner exception: The type initializer for 'GameAnalyticsSDK.Net.Device.GADevice' threw an exception.
   at GameAnalyticsSDK.Net.GameAnalytics.Initialize(String gameKey, String gameSecret) in <DEV>/Libraries/GameAnalytics/GA-SDK-MONO-SHARED/GameAnalytics.cs:line 238
[12/16/2021 4:23:07 PM] Attempting to open ALC device
[12/16/2021 4:23:06 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[12/16/2021 4:23:05 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[12/16/2021 4:23:04 PM] Logged in as
) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 59

InnerException: The type initializer for 'GameAnalyticsSDK.Net.Logging.GALogger' threw an exception.
Target site: Void D(System.String)
Stack trace: 
   at GameAnalyticsSDK.Net.Logging.GALogger.D(String format) in <DEV>/Libraries/GameAnalytics/GA-SDK-MONO-SHARED/Logging/GALogger.cs:line 143
   at GameAnalyticsSDK.Net.GameAnalytics.OnQuit() in <DEV>/Libraries/GameAnalytics/GA-SDK-MONO-SHARED/GameAnalytics.cs:line 737
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
Last debug messages:
[12/16/2021 4:23:16 PM] Initializing GameAnalytics failed. Disabling user statistics... {Exception has been thrown by the target of an invocation.}
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Barotrauma.GameAnalyticsManager.Implementation.<>c__DisplayClass34_0`2.<Call>b__0(T1 arg1, T2 arg2) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameAnalytics/GameAnalyticsManager.cs:line 114
   at Barotrauma.GameAnalyticsManager.Implementation.Initialize(String gameKey, String secretKey) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameAnalytics/GameAnalyticsManager.cs:line 39
   at Barotrauma.GameAnalyticsManager.InitKeys() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameAnalytics/GameAnalyticsKeys.cs:line 11
   at Barotrauma.GameAnalyticsManager.Init() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameAnalytics/GameAnalyticsManager.cs:line 352

Inner exception: The type initializer for 'GameAnalyticsSDK.Net.Device.GADevice' threw an exception.
   at GameAnalyticsSDK.Net.GameAnalytics.Initialize(String gameKey, String gameSecret) in <DEV>/Libraries/GameAnalytics/GA-SDK-MONO-SHARED/GameAnalytics.cs:line 238
[12/16/2021 4:23:07 PM] Attempting to open ALC device
[12/16/2021 4:23:06 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[12/16/2021 4:23:05 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[12/16/2021 4:23:04 PM] Logged in as

**Comment by ekqvist** [comment] 2021-12-16 09:53
Potential duplicate of #7780

**Comment by Regalis11** [comment] 2021-12-16 15:33
Duplicate of #7780

**Closed by Regalis11** 2021-12-16 15:33 UTC
Labels: Bug, Code, Crash, Mac only
