### ISSUE TITLE
Can't load my single player save!!

### ISSUE THREAD

**Issue by EngineerGamingX** [Regalis11/Barotrauma#6365] opened 2021-07-25 09:57 UTC
Description
 Can't load my single player save and i don't know the reason .

   Version
v0.14.6.0  Windows

   Additional information
  My mod list and my ship.
 GunLights Remade
 Craftable Ammo Updated
 Meaningful Drunkness
 Shipwrecks Extended
 Brighter Lights
 [ENV] Beacons Extended
 
Ship R-29 Hammerhead - RFR

 And i just  docked at abonded outpost

Sorry for my english .

![Ekran Alıntısı](https://user-images.githubusercontent.com/87930520/126895167-d7482113-cbec-497a-9cf8-76772ae09d1b.PNG)

**Comment by Jlobblet** [comment] 2021-07-26 09:51
#6187

**Comment by ekqvist** [comment] 2021-07-26 13:01
Yeah, this seems like a duplicate of #6187.

Quoting @Regalis11 from the first issue:
> Seems to happen when some of thalamus organs in the wreck have been placed outside the wreck's hulls. Fixed in Regalis11/Barotrauma-development@07e5682

Closing.

**Closed by ekqvist** 2021-07-26 13:01 UTC
