### ISSUE TITLE
[Factions] Two talents with same name

### ISSUE THREAD

**Issue by StruggleDuck** [Regalis11/Barotrauma#11290] opened 2023-02-20 06:54 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Simple issue, while using the "givetalent" console command, I noticed that there was actually two talents with the name mechanic. One was the one unlocked by mechanics which gives the recipie for exosuits, and the other being the specialization talent for assistants. This makes it impossible to give someone the "MECHanic" talent, as it automatically gives them the assistant talent.

Simple fix could be just renaming MECHanic talent to MECH-anic or renaming the specialization talents for assistant (example name: "Mechanic Specialization" )

### Reproduction steps

1. Press f3
2. Enable cheats
3. Try to give yourself the "MECHanic" talent using "givetalent" command

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-02-20 08:12
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11179

**Closed by Regalis11** 2023-02-20 08:12 UTC
