### ISSUE TITLE
Unstable - Winterhalter description

### ISSUE THREAD

**Issue by brjc** [Regalis11/Barotrauma#8342] opened 2022-02-22 17:18 UTC
The Winterhalter has issues by design with the electrical system (which is itself a questionable choice and makes it largely unusable in single player).

While most subs mention their drawbacks in the sub shop description though, the Winterhalter doesn't mention anything about its horrible power system.

![image](https://user-images.githubusercontent.com/99811302/155184004-47a7bc53-a271-4b95-810e-3af65a98ebd5.png)

**Comment by brjc** [comment] 2022-02-22 17:19
Compare to Humpback's description which specifically calls out power issues:
![image](https://user-images.githubusercontent.com/99811302/155184283-4d2380c6-38c7-474b-926b-1d3ba171106d.png)

**Comment by brjc** [comment] 2022-02-22 17:20
And Orca's power & weapon issues:
![image](https://user-images.githubusercontent.com/99811302/155184468-75f83916-30e5-4166-8ff8-9a61ad723111.png)

**Comment by Regalis11** [comment] 2022-02-23 08:22
What power issues are you referring to?

**Comment by brjc** [comment] 2022-02-23 12:51
Sorry if I was unclear, I guess the power & engine combo is what I was referring to yes. Specifically how it leads to massive junction box failure & fires if used as-is.

**Comment by Regalis11** [comment] 2022-04-12 10:59
Closing as a duplicate of https://github.com/Regalis11/Barotrauma/issues/8786

**Closed by Regalis11** 2022-04-12 10:59 UTC
Labels: Design
