### ISSUE TITLE
[Unstable 0.1400] Duffel bag trader delete

### ISSUE THREAD

**Issue by Bozhdynsky** [Regalis11/Barotrauma#5801] opened 2021-05-15 13:28 UTC
Had two duffel bags filled with loot for sale. When I interacted with a trader and 'emptied' one of the bags during sale it was deleted. They are hard to come by, outside of murder, and very handy in wreck looting/scooping.

**Comment by ekqvist** [comment] 2021-05-18 09:14
Unfortunately, I couldn't reproduce the issue either in singleplayer or multiplayer. Which game mode were you playing when the issue occurred? I tried spawning a duffel bag and filling it with items and selling all of the contained items, but the duffel bag remained in my inventory. Does this happen consistently for you?

**Comment by Bozhdynsky** [comment] 2021-05-18 09:25
Singleplayer and I'm pretty sure that two more disapeared on their own.

**Comment by ekqvist** [comment] 2021-05-18 09:38
To clarify, did the duffel bags disappear immediately after you sold all the contained items at the outpost store?

**Comment by Bozhdynsky** [comment] 2021-05-18 09:40
Not everything, sold some portion but that portion must have cleared one bag and upon finishing the transaction the items were gone but so was one of the bags, the other bag still had some items.

**Comment by ekqvist** [comment] 2021-06-07 08:13
No steps to reproduce and hasn't been encountered since. Closing.

**Closed by ekqvist** 2021-06-07 08:13 UTC
Labels: Bug, Code, Need more info
