### ISSUE TITLE
Game crash with DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved

### ISSUE THREAD

**Issue by extremecodetv** [Regalis11/Barotrauma#1826] opened 2019-10-06 08:45 UTC
**Description**

Game in main menu loads gpu in 100%, then game crash and also it can crash all soft or operating system

**Steps To Reproduce**
Just launch game ¯\\_(ツ)_/¯

**Version**
v0.9.3.3 

**Additional information**
GPU: RTX 2060
GPU Driver version: 436.48
Windows 10 version: 1903

Log files included:

- https://gist.github.com/extremecodetv/eb0532acdf83a62a25be259c1773d0d1
- https://gist.github.com/extremecodetv/618688d4ba77293403613d449e6398e1

There are no problems with hardware. Problem exists only with this game
Reinstallation of Windows or gpu driver did not give any results.

**Comment by extremecodetv** [comment] 2019-10-06 09:24
Temporary fix

Go to your control panel, click on Hardware & Sound > Power settings (for category view) or Control Panel > Power options (for icon view) Select "Change Plan Settings" next to whatever plan you have selected. 

Click on "Change Advanced Power Settings" Expand "PCI Express" > "Link State Power Management" and change that setting to "Off". 

Restart Windows, then Launch Game and in video settings enable VSync

gpu loading without vsync
![image](https://user-images.githubusercontent.com/16631907/66266915-7daf1080-e855-11e9-89c1-0b6ce1179381.png)

gpu loading with vsync
![image](https://user-images.githubusercontent.com/16631907/66266934-a7683780-e855-11e9-93bf-0c3410b10d20.png)

**Comment by kazimierz3000** [comment] 2019-11-04 17:16
I've followed the temporary fix guide to to avail, are there any other known solutions to this bug?

**Comment by Regalis11** [comment] 2020-01-20 20:03
We've added the option to restrict the framerate even when VSync is off to hopefully fix this in the next update: Regalis11/Barotrauma-development@b081cb9 (private repo). Unfortunately at the moment before the update comes out, the only option might be too keep playing with VSync on; otherwise the game will let the GPU render as fast as it can, which can lead to this error.

**Comment by Rokvach** [comment] 2020-01-21 11:40
Tested, my GPU doesn't scream in pain anymore when I disable VSync, but I do feel that it would be better to have a slider which you can use to adjust the maximum framerate from 30 to 500 for example, otherwise working as intended @Regalis11

**Comment by Regalis11** [comment] 2020-01-21 16:53
I'm not sure if that's necessary, personally I feeling changing the maximum framerate from the default one (200) is such an advanced and rarely needed option that having it as a setting in the config file might be enough.

**Comment by Rokvach** [comment] 2020-01-22 11:42
Yeah maybe a config file setting will be enough, moving this to Done as it is working as intended.

**Closed** 2020-02-04 12:11 UTC
Labels: Bug, Code, Crash, High prio
