### ISSUE TITLE
Emergency Siren and Alarm Buzzer state not synching on toggle_state

### ISSUE THREAD

**Issue by CatchFire1101** [Regalis11/Barotrauma#1658] opened 2019-06-15 21:58 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Emergency Siren and Buzzer components states are not synched across all players if the toggle_state pin is used to activate/de-activate them.  Only the player who pushes the button connected to the alarm/buzzer will hear them turn on/off; items will remain off and silent for all other players.

**Steps To Reproduce**
Start a server with at least two players.  Wire a button output to either an alarm buzzer or emergency siren toggle_state input.  If the button is pressed, only the player who pressed the button will hear the alarm, other members of the server will not.

**Version**
v0.9.0.6
Windows

**Additional information**
Both components function correctly and synch state across all players if the set_state input is used (i.e. wired to a memory module whose value is changed from 0 to 1).  This appears to be specifically related to use of the toggle_state functionality.

Also note have confirmed it does not matter if the circuit is pre-fabricated in the sub editor, or wired in-game; results are the same.

All testing was done in campaign mode.

**Comment by Rokvach** [comment] 2019-11-28 00:23
@Regalis11 Is this still an issue?

**Comment by Regalis11** [comment] 2019-11-29 09:48
Most likely yes, we haven't done anything to address this yet.

**Comment by Regalis11** [comment] 2020-03-16 12:53
Duplicate of #1821 (I know this is an older ticket, but the new one has more info so closing this one instead)

**Closed by Regalis11** 2020-03-16 12:53 UTC
Labels: Bug, Code, Networking
