### ISSUE TITLE
Singleplayer Campaign with mods keeps crashing after latest patch (LevelResource.CreateTriggerBody)

### ISSUE THREAD

**Issue by Joebuscus** [Regalis11/Barotrauma#12167] opened 2023-06-16 04:38 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

After the latest patch, every time I join my singleplayer campaign it crashes after a few seconds without fail. I don't know why this is happening. This only happened after yesterday's patch. Most likely some mod, though I don't know why the problem is so bad to the point of crashing the entire game. I tried removing mods that clogged up the console/crash log, but it was no use.

### Reproduction steps

Happens after 3 seconds of me loading into the game. I guess you could download the mods listed in the crash report and try them for yourself if you really want to.

### Bug prevalence

Happens every time I play

### Version

v1.0.20.1

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 06/15/2023 23:36:59)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

A7679365F7B53B9A50A18A7FFA2618E4

Game version 1.0.20.1 (ReleaseWindows, branch release/1.0-patch-2, revision 0eeadb0384)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla (07FDF38), Lua For Barotrauma (C737992), CsForBarotrauma (09E517F), Enhanced Armaments (F0EF0C5), EK Utilities (A203BCB), DynamicEuropa (1790E40), Improved Husks (194B58E), SOFA'S CREATURES (5F49447), Creatures of the Depth (DFEA30A), Meaningful Upgrades (C34F603), Beacons Extended (F054ADA), Shipwrecks Extended (17A736B), Wreck Locator (CFABD6F), BetterHealthUI (5C86226), Oxygen Reloader (902EDD2), Storage Icons (868D7A5), 32x Stack (6262D38), Performance Fix (E5AC66F)
Level seed: Malcam's Cauldron49Anid82
Loaded submarine: Typhon2 (ED0C8A40C65537787C94D927EECD1ED8)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.22621.0 64 bit
    GPU name: NVIDIA GeForce GTX 1060 3GB
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void CreateTriggerBody()
Stack trace: 
   at Barotrauma.Items.Components.LevelResource.CreateTriggerBody() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Holdable\LevelResource.cs:line 138
   at Barotrauma.Items.Components.LevelResource.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Holdable\LevelResource.cs:line 110
   at Barotrauma.Item.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 2069
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 643
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 248
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 884
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[06/15/2023 23:36:57] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
[06/15/2023 23:36:40] Error while loading character health: affliction "radio" not found.
[06/15/2023 23:36:40] Error loading item - item prefab "Walkie Talkie" (identifier "ek_security_radio") not found.
[06/15/2023 23:36:29] Level identifier: greatseabasic
[06/15/2023 23:36:25] Error loading item - item prefab "Klazomoxeride" (identifier "klazomoxeride") not found.
[06/15/2023 23:36:25] Error loading item - item prefab "Klazomoxeride" (identifier "klazomoxeride") not found.
[06/15/2023 23:36:25] Error loading item - item prefab "Klazomoxeride" (identifier "klazomoxeride") not found.
[06/15/2023 23:36:25] Error loading item - item prefab "Klazomoxeride" (identifier "klazomoxeride") not found.
[06/15/2023 23:36:24] Error loading item - item prefab "Klazomoxeride" (identifier "klazomoxeride") not found.
[06/15/2023 23:36:24] Error loading item - item prefab "Klazomoxeride" (identifier "klazomoxeride") not found.
[06/15/2023 23:36:24] Error loading item - item prefab "Klazomoxeride" (identifier "klazomoxeride") not found.
[06/15/2023 23:36:24] Error loading item - item prefab "Klazomoxeride" (identifier "klazomoxeride") not found.
[06/15/2023 23:36:24] Error loading item - item prefab "Klazomoxeride" (identifier "klazomoxeride") not found.
[06/15/2023 23:36:24] Error loading item - item prefab "Klazomoxeride" (identifier "klazomoxeride") not found.
[06/15/2023 23:36:24] Error loading item - item prefab "Klazomoxeride" (identifier "klazomoxeride") not found.
[06/15/2023 23:36:23] Error loading item - item prefab "Klazomoxeride" (identifier "klazomoxeride") not found.
[06/15/2023 23:36:23] Error loading item - item prefab "Klazomoxeride" (identifier "klazomoxeride") not found.
[06/15/2023 23:36:23] Error loading item - item prefab "Klazomoxeride" (identifier "klazomoxeride") not found.
[06/15/2023 23:36:23] Error loading item - item prefab "Klazomoxeride" (identifier "klazomoxeride") not found.
[06/15/2023 23:36:23] Error loading item - item prefab "Klazomoxeride" (identifier "klazomoxeride") not found.
[06/15/2023 23:36:23] Error loading item - item prefab "Klazomoxeride" (identifier "klazomoxeride") not found.
[06/15/2023 23:36:23] Error loading item - item prefab "Klazomoxeride" (identifier "klazomoxeride") not found.
[06/15/2023 23:36:23] Error loading item - item prefab "Klazomoxeride" (identifier "klazomoxeride") not found.
[06/15/2023 23:36:22] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/ANAEV/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2764968387/Jobgear/highperfhazmat.png, size: 757x258)
[06/15/2023 23:36:13] WARNING: Potentially invalid damage modifier in "Utility Mk-I Hardsuit, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[06/15/2023 23:36:13] WARNING: Potentially invalid damage modifier in "Utility Mk-I Hardsuit, Wearable". Could not find any afflictions with the identifier "contamination". Did you mean to use an affliction type instead?
[06/15/2023 23:36:13] WARNING: Potentially invalid damage modifier in "Utility Mk-I Hardsuit, Wearable". Could not find any afflictions with the identifier "glowing". Did you mean to use an affliction type instead?
[06/15/2023 23:36:13] WARNING: Potentially invalid damage modifier in "Utility Mk-I Hardsuit, Wearable". Could not find any afflictions with the identifier "exposure". Did you mean to use an affliction type instead?
[06/15/2023 23:36:13] WARNING: Potentially invalid damage modifier in "Utility Mk-I Hardsuit, Wearable". Could not find any afflictions with the identifier "radiation". Did you mean to use an affliction type instead?
[06/15/2023 23:34:20] Overriding an affliction or a buff with the identifier 'huskinfection' using the file 'C:/Users/ANAEV/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2085783214/Afflictions.xml'
[06/15/2023 23:34:15] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/ANAEV/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2532991202/UI/DE-IconsAtlas.png, size: 1365x1365)
[06/15/2023 23:33:43] Attempting to open ALC device "OpenAL Soft on Speaker/Headphone (Realtek(R) Audio)"
[06/15/2023 23:33:41] Logged in as Joebuscus (SteamID STEAM_1:0:170462832)
```

**Comment by BitoGx** [comment] 2023-06-16 08:40
I also had the same issue, from what i see we have different mod list except Shipwrecks Extended (17A736B), Beacons Extended (F054ADA), and DynamicEuropa (1790E40).

and here are my crash report
````
Barotrauma Client crash report (generated on 06/16/2023 16:16:36)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

A7679365F7B53B9A50A18A7FFA2618E4

Game version 1.0.20.1 (ReleaseWindows, branch release/1.0-patch-2, revision 0eeadb0384)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla (07FDF38), Alicorn2 Stealth Light Cruiser (3C5FCE1), [VH] The Iroh (B1D86C8), Shipwrecks Extended (17A736B), Beacons Extended (F054ADA), Combinable Ammo Revived (NOW WORKS WITH ALL AMMO) (54ACC9F), Stations from beyond (EF4F189), DynamicEuropa (1790E40), EuropaWaifu++ Non-xpath Version (85A32E7), DynamicEuropa EW++ Non-Xpath (958484A)
Level seed: Yelland Linea101Attis120
Loaded submarine: Alicorn2+ (6E9F4F4C8DCE4FDAE7838A538C4A093E)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.22621.0 64 bit
    GPU name: NVIDIA GeForce GTX 1050
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void CreateTriggerBody()
Stack trace: 
   at Barotrauma.Items.Components.LevelResource.CreateTriggerBody() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Holdable\LevelResource.cs:line 138
   at Barotrauma.Items.Components.LevelResource.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Holdable\LevelResource.cs:line 118
   at Barotrauma.Item.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 2069
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 643
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 248
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 884
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[06/16/2023 16:16:35] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
[06/16/2023 16:16:26] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/BitoGx/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2532991202/Items/Pirates/ExosuitParts.png, size: 164x113)
[06/16/2023 16:16:21] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/BitoGx/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2948283083/Items/weeaboo.png, size: 427x42)
[06/16/2023 16:16:12] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/BitoGx/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2948283083/Items/RebelPosters2.png, size: 820x229)
[06/16/2023 16:16:09] Generating an outpost for the end of the level... (Location: Attis Deposit, level type: LocationConnection)
[06/16/2023 16:16:07] Generating an outpost for the start of the level... (Location: Yelland Linea Sick Bay, level type: LocationConnection)
[06/16/2023 16:16:05] Level identifier: coldcavernsadvanced
[06/16/2023 16:16:01] Creating hulls between docking ports failed. The upper docking port seems to be very far from any hulls in the upper submarine.
[06/16/2023 16:14:53] Loading a pre-selected outpost for the start of the level...
[06/16/2023 16:14:52] Level identifier: outpostlevel
[06/16/2023 16:14:52] Creating hulls between docking ports failed. The upper docking port seems to be very far from any hulls in the upper submarine.
[06/16/2023 16:14:49] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/BitoGx/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2948283083/Items/Posters.png, size: 655x851)
[06/16/2023 16:08:34] Trying to spawn human
[06/16/2023 16:05:40] Overriding an affliction or a buff with the identifier 'concussion' using the file 'C:/Users/BitoGx/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2948283083/Characters/Human/Afflictions.xml'
[06/16/2023 16:05:40] Overriding an affliction or a buff with the identifier 'nausea' using the file 'C:/Users/BitoGx/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2948283083/Characters/Human/Afflictions.xml'
[06/16/2023 16:05:40] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/BitoGx/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2948283083/UI/titleText.png, size: 1161x1024)
[06/16/2023 16:05:32] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/BitoGx/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2532991202/UI/DE-IconsAtlas.png, size: 1365x1365)
[06/16/2023 16:04:46] Attempting to open ALC device "OpenAL Soft on Speakers (Realtek High Definition Audio)"
[06/16/2023 16:04:41] Logged in as BitoGx (SteamID STEAM_1:0:54432745)

````

**Comment by Regalis11** [comment] 2023-06-16 09:53
It seems that at least one cause for this issue is the "Strange Pirate Vessel" mission in the Dynamic Europa mod. Can be reproduced by enabling that mod, unlocking the mission pirate_piezo and starting a round. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ad792ea76195bce940e4b19da463d7dd57190038 (commit in our private repo)

**Comment by Regalis11** [comment] 2023-06-18 13:31
Thank you for taking the time to close this, but we'll keep it open until we've tested the fix internally and verified it works properly. :)

**Comment by NilanthAnimosus** [comment] 2023-06-20 06:01
Tested against Fix/levelresource-createtriggerbody-nullref commit https://github.com/Regalis11/Barotrauma-development/commit/ad792ea76195bce940e4b19da463d7dd57190038, no issues found, ready to merge.

Testing notes:
Was unable to reproduce on traitor-update branch using a piezo crystal on player or vanilla pirate submarines via sub editing changes in. Downloaded dynamic europa mod and added back the leveltrigger to the custom piezo crystal it uses in modded mission pirate_piezo which crashed the game, the fix does not.

**Closed** 2023-06-20 07:53 UTC
Labels: Bug, Code, Crash, Severe
