### ISSUE TITLE
[0.9.708] Crash everytime I click "Server browser" in menu or "Join" from steam friendlist

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#2299] opened 2020-02-13 22:31 UTC
[crashreport (60).log](https://github.com/Regalis11/Barotrauma/files/4201633/crashreport.60.log)
**I've tried**
-verifying the game twice
-restarting steam
-going to "Offline mode" in steam friends list.
-restarting my PC

**Steps To Reproduce**
To me, it happens every time I click Server browser or try to join friend from steam.
**Version**
[0.9.708] Unstable

**Comment by Regalis11** [comment] 2020-02-14 08:21
I'm glad you caught this! It seems to be caused by the game failing to read the "connect" value that's used to join the server one of your Steam friends is playing on.

Partially fixed this in https://github.com/Regalis11/Barotrauma-development/commit/5062a5a70c5d5dee8e4d58744616c37106bf4ead: now instead of crashing, the game will just not allow you to join that server through the friends list. Still need to look into this in more detail and figure out why exactly it's failing to read the value.

**Comment by Regalis11** [comment] 2020-02-15 22:29
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/57bc712

**Comment by Rokvach** [comment] 2020-02-16 21:12
This hasn't come up since the fix and we've had quite a good number of players playing the Unstable. So I'm just going to close this.

**Closed by Rokvach** 2020-02-16 21:12 UTC
Labels: Bug, Code, Crash, High prio
