### ISSUE TITLE
Weird behaviour when picking up items when holding 2 containers

### ISSUE THREAD

**Issue by soledad630** [Regalis11/Barotrauma#10716] opened 2022-12-14 14:43 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

As far as I can remember, usually when transferring items from other containers into 2 storage containers holded by hand, items go into right hand container first then the left hand one when the former is filled. 

Right now when holding 2 empty storage containers and picking up a stack of item from containers, 1 single item will always go to the left hand container and the rest of the stack goes to the right hand. Then picking up items without leaving the interaction interface from the same storage will always go to left hand container. But if you exit external storage interface first then go back and pick up other items, they always go into right hand container.

I am yet to do more tests about more combinations of actions but so far the above stated has been observed repeatedly when looting wrecks and when tested in a storage cabinet on my own sub. 

### Reproduction steps

1. Put a stack of stackable item in a cabinet/wreck cabinet. Put some more items in the same cabinet.
2. Take 2 storage containers by hand, make sure they are empty.
3. Pick up the stackable item stack from the cabinet.
4. Do NOT exit the interface, pick up the rest of the item, observe their destination.
5. Repeat 1-4, but this time exit the interface first before picking up the rest of the item during step 4.

### Bug prevalence

Happens regularly

### Version

0.20.14.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-12-14 16:25
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/46cb21ce917aba74aabd142baca07c0ebedd990c

**Comment by Rokvach** [comment] 2023-01-11 12:25
I was still able to reproduce the stack issue, 1 item was transferred to the left storage container while the rest to the right. 

I don't think the next is much of an issue. 
When picking items one by one after picking up the stack like in the repro steps it doesn't place them all into the same storage container but instead goes left > right > left > right etc for each of the items picked up.

**Comment by Regalis11** [comment] 2023-01-11 14:38
That seemed to happen because, as described in the commit message, I made the item go in the container that's the "least full" (as measured by the indicator below the slot). The 1st item would go in the right hand slot, but after that the left hand slot is more full and the second item would go there. After that they're considered to be just as full, and the rest of the items go in the right hand slot.

Addressed in https://github.com/Regalis11/Barotrauma-development/commit/38d64acb2a39a7fa781cab06f4f7bbf57cb77126 by preferring the container that has a non-full stack of items we can add the item to.

**Comment by Rokvach** [comment] 2023-01-17 10:49
Tested, working correctly. Closing.

**Closed by Rokvach** 2023-01-17 10:49 UTC
Labels: Bug, Code
