### ISSUE TITLE
The game should trigger a warning if a mod doesn't comply to cross-platform standards

### ISSUE THREAD

**Issue by FamiliarBreakfast** [Regalis11/Barotrauma#4540] opened 2020-12-16 01:20 UTC
I am ready to bore a hole through my head with how many times i've seen '/' and '\' used interchangeably, or completely inconsistent capitalization. These sorts of mistakes cause enough errors for anyone who isn't playing on windows. A little reminder might make some people consider those whose choice of OS is not so tolerant. Or atleast drive up enough attention to get the developer to do something. 

The main issues I see are:
- People ignoring case-sensitivity. This is the real kicker.
- Paths starting with "C:/...", which can also cause issues on windows as well.
- As mentioned before '\' instead of '/'
- And a reverse, attempting to use a folder named COM, which doesn't work on Windows. 
- Using a full path instead of a Barotrauma root path.

**Comment by mygamingaccount** [comment] 2020-12-18 17:35
While I understand the frustration, and I agree that it would be the best if everyone was just pedantic, realistically it is not such a huge issue if you use **case insensitive** mount options for your Barotrauma directory.

To do this on the ext4 filesystem, you need a fairly recent kernel (>5.2). Use`chattr +F` to enable the `casefold` option of directories you wish be case-insensitive.

**Comment by mygamingaccount** [comment] 2020-12-18 18:55
Does using `\\` instead of `/` even cause issues?? Even the **ExampleMod** made by the devs even uses `\\` in the file paths

**Comment by FamiliarBreakfast** [comment] 2020-12-31 20:28
> Does it cause any issues if you use `\` instead of `/`?? Even the **ExampleMod** made by the devs even uses `\` in the file paths

Absolutely. It certainly isn't BTs fault, \ and / are **completely different.** Also, not all filesystems support caseinsensitivity.

**Comment by Regalis11** [comment] 2021-01-13 17:40
Closing this as a duplicate of https://github.com/Regalis11/Barotrauma/issues/4692 (even though this is an earlier ticket, the new one has more information now)

**Closed by Regalis11** 2021-01-13 17:40 UTC
Labels: Code, Modding
