### ISSUE TITLE
[0.1000.0.0] Crawler/Mudraptors - Collider velocity invalid, resetting the ragdoll. Invalid ragdoll physics. Ragdoll freezed to prevent crashes.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2925] opened 2020-05-30 00:07 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Constantly crawlers and mudraptors are opening the console up to spit out these messages when they are right up against the submarine:

Collider velocity invalid, resetting the ragdoll.
Invalid ragdoll physics. Ragdoll freezed to prevent crashes.

**Version**
0.1000.0.0

**Comment by hubismal** [comment] 2020-05-30 14:34
This is related to crawlers and mudraptors phasing through the docking port when it happens, I think.

**Comment by Regalis11** [comment] 2020-05-31 14:23
I suspect this was caused by them phasing through doors/hatches as well. If that was the case, https://github.com/Regalis11/Barotrauma-development/commit/ecfc998661ec26ed1cc153291232e1d3645a82f5 should fix it

**Comment by Rokvach** [comment] 2020-06-02 07:47
Haven't seen this happening while playing rounds on multiplayer and singleplayer, closing.

**Closed by Rokvach** 2020-06-02 07:47 UTC
Labels: Bug, Code, Needs testing
