### ISSUE TITLE
[Variants] Doesn't use mod load order when there's duplicates but rather uses a variant that the game loads first

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#4750] opened 2021-01-14 08:51 UTC
If multiple mods adds in the same variant the game only uses the variant that is loaded first rather than what is defined first in the mod load order, I can see this happening quite easily, for example creating a smaller size of a existing creature you could easily just call it MolochSmall and someone else can do the same. The game does however throw errors at the player that there is duplicate variants but players usually tend to use mods regardless if they throw errors or not and I think player should be able to affect which is being used with the load order.

**Comment by juanjp600** [comment] 2021-12-03 01:54
If I'm reading this correctly, #7555 is a duplicate of this ticket but that one is more detailed, so if there are no objections I think I may close this.

**Closed** 2022-02-09 10:38 UTC
Labels: Code, Modding
