### ISSUE TITLE
Crash in AI Handler(?)

### ISSUE THREAD

**Issue by MystLeissa** [Regalis11/Barotrauma#1825] opened 2019-10-05 20:07 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**

Game Crashed to Desktop while Mining Ores.

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

Unknown - Supposedly AI-based

**Version**
Which version of the game did the bug happen in. You can see the version number at the bottom left corner of the main menu, and in a file called "Version.txt" inside the game folder.
Also, please include the operating system you're using (Windows/Linux/Mac).

barotrauma closed alpha (steam variant), Windows 10

**Possibly Related Mods**

I had a job mod that modifies the default AI Priorities - it's not public due to override tags being used and it's never caused problems before but it was loaded at the time and it overrides several objects as well (none of which SEEM related) - In any case there were no "console" errors as would be expected normally of malformed XML.

**Additional information**

Crash Log:

Barotrauma Client crash report (generated on 10/5/2019 3:54:51 PM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

956D47387A2BF1DCBBC0CC9D961FD2B3

Game version 0.9.400.0
Graphics mode: 1600x900 (BorderlessWindowed)
Selected content packages: Vanilla 0.9, NyschPackage
Level seed: OshanFalga
Loaded submarine: Orca-midpack (83FCFCE1DA78C1557C686403E50674C1)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 6.2.9200.0 64 bit
    GPU name: Radeon RX 570 Series
    Display mode: {Width:1600 Height:900 Format:Color AspectRatio:1.777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object.
Target site: Boolean IsValidTarget(Barotrauma.Character, Barotrauma.Character)
Stack trace: 
   at Barotrauma.AIObjectiveRescueAll.IsValidTarget(Character target, Character character) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\Characters\AI\Objectives\AIObjectiveRescueAll.cs:line 54
   at Barotrauma.AIObjectiveLoop`1.AddTarget(T target) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\Characters\AI\Objectives\AIObjectiveLoop.cs:line 29
   at Barotrauma.HumanAIController.<>c__DisplayClass60_0`2.<AddTargets>b__0(HumanAIController humanAI) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\Characters\AI\HumanAIController.cs:line 684
   at Barotrauma.HumanAIController.DoForEachCrewMember(Character character, Action`1 action) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\Characters\AI\HumanAIController.cs:line 595
   at Barotrauma.HumanAIController.AddTargets[T1,T2](Character caller, T2 target) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\Characters\AI\HumanAIController.cs:line 679
   at Barotrauma.HumanAIController.ReportProblems() in E:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\Characters\AI\HumanAIController.cs:line 348
   at Barotrauma.HumanAIController.Update(Single deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\Characters\AI\HumanAIController.cs:line 145
   at Barotrauma.AICharacter.Update(Single deltaTime, Camera cam) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\Characters\AICharacter.cs:line 80
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\Characters\Character.cs:line 2023
   at Barotrauma.GameScreen.Update(Double deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\Screens\GameScreen.cs:line 126
   at Barotrauma.GameMain.Update(GameTime gameTime) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\GameMain.cs:line 806
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in D:\Repos\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in D:\Repos\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in D:\Repos\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in D:\Repos\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Barotrauma.Program.Main(String[] args) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\Program.cs:line 41

Last debug messages:
[10/5/2019 3:26:29 PM] Overriding the job 'assistant' with another defined in 'Mods\NyschPackage\Jobs.xml'
[10/5/2019 3:26:29 PM] Overriding the job 'medicaldoctor' with another defined in 'Mods\NyschPackage\Jobs.xml'
[10/5/2019 3:26:29 PM] Overriding the job 'securityofficer' with another defined in 'Mods\NyschPackage\Jobs.xml'
[10/5/2019 3:26:29 PM] Overriding the job 'mechanic' with another defined in 'Mods\NyschPackage\Jobs.xml'
[10/5/2019 3:26:29 PM] Overriding the job 'engineer' with another defined in 'Mods\NyschPackage\Jobs.xml'
[10/5/2019 3:26:29 PM] Overriding the job 'captain' with another defined in 'Mods\NyschPackage\Jobs.xml'
[10/5/2019 3:26:29 PM] Overriding an existing map entity with the identifier 'chloralhydrate' using the file 'Mods\NyschPackage\NyschItems.xml'.
[10/5/2019 3:26:29 PM] Overriding an existing map entity with the identifier 'tonicliquid' using the file 'Mods\NyschPackage\NyschItems.xml'.
[10/5/2019 3:26:29 PM] Overriding an existing map entity with the identifier 'antibloodloss1' using the file 'Mods\NyschPackage\NyschItems.xml'.
[10/5/2019 3:26:29 PM] Overriding an existing map entity with the identifier 'antibleeding1' using the file 'Mods\NyschPackage\NyschItems.xml'.
[10/5/2019 3:26:29 PM] Overriding an existing map entity with the identifier 'watchmanclothes' using the file 'Mods\NyschPackage\NyschItems.xml'.
[10/5/2019 3:26:29 PM] Overriding an existing map entity with the identifier 'handheldsonar' using the file 'Mods\NyschPackage\NyschItems.xml'.
[10/5/2019 3:26:29 PM] Overriding an existing map entity with the identifier 'oxygentank' using the file 'Mods\NyschPackage\NyschItems.xml'.
[10/5/2019 3:26:29 PM] Overriding an existing map entity with the identifier 'oxygentankshelf2' using the file 'Mods\NyschPackage\NyschItems.xml'.
[10/5/2019 3:26:29 PM] Overriding an existing map entity with the identifier 'oxygentankshelf' using the file 'Mods\NyschPackage\NyschItems.xml'.
[10/5/2019 3:26:29 PM] Overriding an existing map entity with the identifier 'divingsuit' using the file 'Mods\NyschPackage\NyschItems.xml'.
[10/5/2019 3:26:29 PM] Overriding an existing map entity with the identifier 'divingmask' using the file 'Mods\NyschPackage\NyschItems.xml'.
[10/5/2019 3:26:29 PM] Overriding an existing map entity with the identifier 'clowncostume' using the file 'Mods\NyschPackage\NyschItems.xml'.
[10/5/2019 3:26:29 PM] Overriding an existing map entity with the identifier 'clownmask' using the file 'Mods\NyschPackage\NyschItems.xml'.
[10/5/2019 3:26:29 PM] Overriding an existing map entity with the identifier 'captainsuniform' using the file 'Mods\NyschPackage\NyschItems.xml'.
[10/5/2019 3:26:29 PM] Overriding an existing map entity with the identifier 'captainscap' using the file 'Mods\NyschPackage\NyschItems.xml'.
[10/5/2019 3:26:29 PM] Overriding an existing map entity with the identifier 'assistantclothes' using the file 'Mods\NyschPackage\NyschItems.xml'.
[10/5/2019 3:26:29 PM] Overriding an existing map entity with the identifier 'divingsuitlocker2' using the file 'Mods\NyschPackage\NyschItems.xml'.
[10/5/2019 3:26:29 PM] Overriding an existing map entity with the identifier 'divingsuitlocker' using the file 'Mods\NyschPackage\NyschItems.xml'.
[10/5/2019 3:26:29 PM] Overriding an existing map entity with the identifier 'thoriumfuelrod' using the file 'Mods\NyschPackage\NyschItems.xml'.
[10/5/2019 3:26:29 PM] Overriding an existing map entity with the identifier 'fulguriumfuelrod' using the file 'Mods\NyschPackage\NyschItems.xml'.
[10/5/2019 3:26:29 PM] Overriding an existing map entity with the identifier 'fuelrod' using the file 'Mods\NyschPackage\NyschItems.xml'.
[10/5/2019 3:26:29 PM] Overriding an existing map entity with the identifier 'toxcabinet' using the file 'Mods\NyschPackage\NyschItems.xml'.
[10/5/2019 3:26:24 PM] Overriding all sounds with Mods\NyschPackage\sounds.xml
[10/5/2019 3:26:21 PM] Logged in as Nysch (SteamID STEAM_1:0:53830463)

**Comment by MystLeissa** [comment] 2019-10-05 20:09
Also just noticed that the Crash Logs reference a drive/directory path that doesn't exist - my Game is on D:\Steam3 under the applicable steam folders...this is quite odd as i don't even HAVE an E: drive.

**Comment by MystLeissa** [comment] 2019-10-05 20:23
here's a link to my mod pack - it should contain everything that was in-use during the crash: https://www.dropbox.com/s/hn55q7tbzcn48q5/NyschPackage.7z?dl=0

**Comment by Regalis11** [comment] 2019-10-06 12:40
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/98609bb52d075dc7e82a554c23972238cad553ce (private repo).

It seems that this was not caused by your mod, it was simply a bug in the AI code that caused an exception to be thrown if a character outside the sub is executing the "rescue" order. And the file paths in the crash log are actually paths of the files on the computer the game was compiled on, so it's normal that they may not match paths on your computer.

But in any case, thanks for a very informative report, this should be fixed for the next patch!

**Comment by Rokvach** [comment] 2019-10-18 17:38
Tested, working correctly now. Closing.

**Closed by Rokvach** 2019-10-18 17:38 UTC
Labels: Bug, Code, Crash
