### ISSUE TITLE
The Defense Bot refuses to attack Bandits or Pirates - Even if they attack the owner

### ISSUE THREAD

**Issue by Wheatley1002** [Regalis11/Barotrauma#10763] opened 2022-12-19 01:22 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The Defense Bot will not acknowledge the Bandits or Pirates as threats even if they are actively attacking the player or owner of the Defense Bot. Additionally, Bandits and Pirates will ignore the Defense Bot. They treat each other as neutral entities.

As a result, the Defense Bot attacks exclusively hostile creatures.

### Bug prevalence

Happens every time I play

### Version

0.20.15.0

### Which operating system did you encounter this bug on?

MacOS

**Comment by itchyOwl** [comment] 2022-12-20 10:35
Fixed in Regalis11/Barotrauma-development@3f89e34 and Regalis11/Barotrauma-development@488da45.

Both changes require extensive testing on all encounters.

**Comment by Rokvach** [comment] 2023-01-09 15:29
So far I've noticed that the Defense Bot doesn't react to bandits turned hostile based on event outcome

**Comment by Regalis11** [comment] 2023-01-13 11:31
Tested, doesn't seem to be working if the attacker is in a friendly team (e.g. outpost security or an NPC turned hostile by an event, for example in the event `huskcultambush`). 

I think the problem is the `Character.IsFriendly` check in the Protect AIState: characters in a friendly team are ignored even if they're actively attacking the owner.

**Comment by itchyOwl** [comment] 2023-01-16 09:04
Fixed in Regalis11/Barotrauma-development@1bbf421. Please do a quick screening on various encounters too (e.g. security vs. player, security vs. monster, bandits vs monsters, monsters vs defensebot, bandits vs player, bandits vs defensebot).

> I think the problem is the Character.IsFriendly check in the Protect AIState: characters in a friendly team are ignored even if they're actively attacking the owner.

We can't use the trigger to attack here, because the reaction is based on changing the targeting tags, which would cause the defense bot to attack all the humans and pets. That's why I added the "hostile" targeting tag earlier, but it didn't take the instigators into account.

**Comment by Regalis11** [comment] 2023-01-17 10:34
> security vs. player, security vs. monster, bandits vs monsters, monsters vs defensebot, bandits vs player, bandits vs defensebot
Tested all of these and couldn't spot any issues. 

I did notice something in the code though that makes my wonder if this works correctly in all cases: it seems pets consider all instigators hostile, and instigators are considered to be friendly with each other. Those don't seem like assumptions that are always correct:
- Should a pet consider an instigator hostile, even if the instigator is e.g. a character from the crew attacking a hostile NPC?
- Should instigators consider each other friendly, even if they're attacking each other?

I couldn't find a situation where this would've caused problems, but I can't really see `why` it doesn't cause problems. Maybe there's some other part of the AI code that handles checking what the instigator is actually targeting?

**Comment by itchyOwl** [comment] 2023-01-17 12:07
Addressed in Regalis11/Barotrauma-development@f41b14b.

**Comment by Regalis11** [comment] 2023-01-17 12:28
Something still seems to be off here. The defense bot seems to get "stuck" easily: after it's fired a few shots, it'll just stay in place and aim at the target without firing. Steps to repro:
1. Spawn a defencebot in an outpost
2. Play with it to make you its owner
3. `triggerevent huskcultambush`
4. When the cultists attack you, the bot only fires a couple of times
![image](https://user-images.githubusercontent.com/14351070/212899249-876574e0-4c4d-422e-9e3f-f92e7bd96388.png)

**Comment by itchyOwl** [comment] 2023-01-20 11:15
Yeah it was now totally broken. I don't think I tested it properly. Hopefully now fixed (in Regalis11/Barotrauma-development@c438188).

**Comment by Rokvach** [comment] 2023-01-25 10:41
- [ ] I noticed that the defense bot doesn't tend to follow the instigators for example in the `huskcultambush` event, it rather stays in the same spot and only shoots if the instigator is really close to the bot, so you need to bring the instigators to the defense bot if you want the bot to help you.
- [ ] I also noticed that the bot doesn't seem to attack outpost guards at all if they aggro on you but just follows you around instead.

**Comment by itchyOwl** [comment] 2023-01-25 11:37
> I noticed that the defense bot doesn't tend to follow the instigators for example in the huskcultambush event, it rather stays in the same spot and only shoots if the instigator is really close to the bot, so you need to bring the instigators to the defense bot if you want the bot to help you.

The defencebot does this regardless of the enemy when it's inside the sub. Works a bit like a sentry gun. Or did you notice a difference on other enemies?

**Comment by itchyOwl** [comment] 2023-01-25 13:40
> I also noticed that the bot doesn't seem to attack outpost guards at all if they aggro on you but just follows you around instead.

Fixed in [PR #3897](https://github.com/Regalis11/Barotrauma-development/pull/3897)

**Comment by Rokvach** [comment] 2023-01-25 14:36
Closing this ticket, the defense bot needs a closer look at later when there's a bit more time, so better to write a new ticket then than keep this open.

**Closed by Rokvach** 2023-01-25 14:36 UTC
Labels: Bug, Code
