### ISSUE TITLE
Atmos creating Alien Cell disables Deconstructor cancel button.

### ISSUE THREAD

**Issue by Jamessy22** [Regalis11/Barotrauma#9982] opened 2022-10-05 08:38 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Minor bug, as in the title: when Atmos Machine triggers and transforms an item into Alien Power Cell, it's impossible to cancel further deconstruction - presumably the check for non-deconstructible items applies erroneously on cancellation.

Note: whilst this is minor, it can be annoying - especially if a major artifact awaits in the queue (or is spawned into it). Also, hopefully fairly easy to fix :)

![atmos](https://user-images.githubusercontent.com/114238002/194017882-53fb9553-a842-419b-9ce2-d5441e2a66fb.png)

### Reproduction steps

1. Dump a bunch of artifacts into deconstructor.
2. Activate deconstructor by a medic with Atmos Machine.
3. When Alien Cell spawns, observe inability to cancel.

### Bug prevalence

Happens every now and then

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-10-05 15:57
Duplicate of https://github.com/Regalis11/Barotrauma/issues/9907, should be fixed in the update that just went out :)

**Closed by Regalis11** 2022-10-05 15:57 UTC
