### ISSUE TITLE
Multiplayer - Client Ghost Damage when crashing into walls/spires

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4992] opened 2021-02-05 01:16 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Sometimes when crashing into level walls and spires, your sub may not be actually damaged enough to leak, but the clients might think it is. The damage is visible to the clients, but is not there on the server. Welding the walls on the client shows no repair, but is repaired otherwise.

**Version**
~0.12.0.2

**Comment by Regalis11** [comment] 2021-02-05 08:46
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8eca427c724178fb9155266325c2d3a03a1f5a6b

**Comment by Rokvach** [comment] 2021-02-24 15:56
Tested, haven't been able to reproduce this. Seems to be working correctly. Closing.

**Closed by Rokvach** 2021-02-24 15:56 UTC
Labels: Bug, Code, Medium Prio, Networking
