### ISSUE TITLE
Tutorials reset after game crash

### ISSUE THREAD

**Issue by duskull007** [Regalis11/Barotrauma#4533] opened 2020-12-15 01:01 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Game crashed in main menu after accepting an invite to lobby. Before the crash I had completed the mechanic, engineer, and medical doctor training and had left in the middle of security officer training. After the crash, all trainings are now locked again except for mechanic.

**Steps To Reproduce**
Honestly no idea, and it's a lot of effort to complete all trainings again
**Version**
v0.10.0.9, windows 10

**Comment by KimmoKari** [comment] 2021-01-18 08:55
Can you @Rokvach try to repro this ?

**Comment by ekqvist** [comment] 2021-03-05 09:32
Apologies for the late reply. Unfortunately, I can't reproduce the issue. Even after crashing the game, the tutorial progress seems to load correctly.

**Comment by Rokvach** [comment] 2021-03-08 12:14
This is the only instance I've heard about this happening

**Comment by ekqvist** [comment] 2021-03-22 13:20
Can't reproduce and hasn't come up since, closing for now.

**Closed by ekqvist** 2021-03-22 13:20 UTC
Labels: Bug, Code, Medium Prio, Need more info
