### ISSUE TITLE
fractal guardian's steam cannon does blunt force noises

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#6894] opened 2021-10-11 20:10 UTC
- [yea] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you/something is getting atacked by the fractal guardian's steam cannon, it plays the same noise as when you get hit with a blunt force weapon, i don't think it should be like that.

https://user-images.githubusercontent.com/55637865/136849829-4d319b04-327a-4890-87de-5318f4c3db89.mp4

**Version**
unstable v0.15.6.0

**Comment by itchyOwl** [comment] 2021-10-12 12:34
Fixed in Regalis11/Barotrauma-development@928c8b8. Caused by the ranged attacks monsters use to trigger the shooting.

**Closed as completed** 2021-10-14 09:23 UTC
Labels: Bug, Code
