### ISSUE TITLE
Players can float in place after destroying the ground beneath their feet

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#11314] opened 2023-02-22 16:58 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Aslong as you dont move, if you destroy a piece of shell below your feet, your character will float in place, only dropping down the second you start walking again.

https://user-images.githubusercontent.com/104232152/220700431-41579228-2530-40cc-87f8-b8ec761333ce.mp4

### Reproduction steps

1.Plasma cut a piece of shell beneath your feet
2.Notice that after being destroyed, you will continue to stand midair
(Only continute to fall down after moving left or right)

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-02-22 17:25
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10558

**Closed by Regalis11** 2023-02-22 17:25 UTC
