### ISSUE TITLE
Respawn Shuttle Locked Me in, Before I Ever Left It White Docking- Bug

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#628] opened 2018-08-10 10:57 UTC
I was in respawn shuttle and I docked. I left normally shuttle, but before I left it it locked behind me 10 seconds, before it had to leave automatically by itself and pulled me in, even when 75% of my body was already on the board of regular submarine.

**Comment by thegrb93** [comment] 2018-08-10 11:33
It would be nice if the shuttle waited until the timer. I've gotten stuck on it before as well.

**Comment by rico6822** [comment] 2018-08-10 15:02
I think the range of when it starts to leave by itself should be set to 1 meter of player's range instead of 0,25 meter or something like that.

**Comment by Rokvach** [comment] 2019-07-20 23:37
This issue was by design, improvements should be coming in the next patch. Closing this issue as it should be solved.

**Closed by Rokvach** 2019-07-20 23:37 UTC
Labels: Bug, Code
