### ISSUE TITLE
Ballast Pumps are bugged when rewiring power output

### ISSUE THREAD

**Issue by Erars** [Regalis11/Barotrauma#3952] opened 2020-09-30 12:13 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Rewiring the Ballast Pumps or Pumps in general power output to a new Junction box causes the Pumps to bug out.  As you can see on the gif.  
![ballastfail](https://user-images.githubusercontent.com/62313026/94683438-70b8e600-031e-11eb-8100-077a5585ef41.gif)

**Steps To Reproduce**
On the Humpback default sub.  Unwire and rewire the original pumps power output to a new junction box or a relay, and try controlling the sub through the monitor.   

**Version**
v0.10.5.1 Release version

**Comment by Regalis11** [comment] 2020-09-30 13:18
I'm afraid I wasn't able to reproduce this. Tested by doing the following:
1. Start a new single player campaign with Dugong
2. Remove the power wire from the pump in the ballast tank under the navigation terminal
3. Run a new wire from the power connection of another junction box to the power input of the pump

Seems to be working with no issues.

**Comment by Erars** [comment] 2020-09-30 13:26
Try the Humpback. make sure you are hosting a server. First   Unwire the power output of both ballast Pumps, and the wires connecting the junction box to the ballast Pumps.  Then rewire them back.   Then go to monitor and the bug should appear when trying to move.

**Comment by thegrb93** [comment] 2020-09-30 13:48
I've seen this happen a lot. Don't know how to reproduce though, hopefully Erars' method works.

**Comment by Erars** [comment] 2020-09-30 13:55
New more accurate reproduction step:  Do not start anything, do not start the reactor, NO BOTS for fair bug testing.  First unwire the ballast pump power output from the junction box --> Then go to that pump that u unwired and unwire and collect the wire of that Pump and the wire should be in ur inventory. --> Next wire the Pump with your wire in your inventory and then bring the wire to the junction box ---> Go to monitor and monitor the Pumps by moving down.

**Comment by alkaid7205** [comment] 2020-09-30 16:18
I've seen this happen a lot as well.
Steps to reproduce [video](https://imgur.com/RRkgQt9)

The problem is fixed after starting/finishing the round.

**Comment by someone972** [comment] 2020-10-03 20:40
This looks similar to behavior I was seeing when wiring battery -> JB -> relay -> JB -> light (which I've since discovered does not work well). The second junction box would constantly build up to overvoltage level and then snap back to the actual load value. Seems to be the same sort of behavior that the ballast pump is showing, but might not be directly related.

**Comment by Regalis11** [comment] 2020-11-07 13:47
Seems to be the same issue as #3121, fixed in Regalis11/Barotrauma-development@0059175

**Closed by Regalis11** 2020-11-07 13:47 UTC
Labels: Bug, Code, Networking
