### ISSUE TITLE
Stunning is broken

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#5606] opened 2021-04-25 03:45 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Chloral Hydrate, stun baton, stun dart are all broken and don't stun

**Comment by Tsunder** [comment] 2021-04-25 07:10
Chloral Hydrate: appears to only deliver net 82 incremental stun before dropping. (single dose)

rest seem to work as expected based on their item entry (multiple hits for stun baton, stun dart has delayed effect)

**Comment by Regalis11** [comment] 2021-04-26 08:01
Stunning items have been nerfed quite a bit and take a couple of hits to have an effect due to the incremental stun. All of these items seem to be working as intended, closing.

**Closed by Regalis11** 2021-04-26 08:01 UTC
