### ISSUE TITLE
Bot self defense is too aggressive against crew members

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3840] opened 2020-09-16 00:30 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I just witnessed bot crew members being too aggressive against other crew members when they accidentally receive a stray shot from a gun or a piercing coil bolt hitting them when dealing with an ongoing mudraptor threat.

Scenario 1:
Bot A was defending the sub shooting piercing coil ammo towards the door that was being attacked. Bot B happened to be behind another layer of door beyond that welding an ongoing leak, but was hit by a bolt. Immediately Bot B ran up to the gunnery room that Bot A was in and shot him to death completely. Even if he was healed, he would return to finish the job.

Scenario 2:
I was shooting a mudraptor climbing up my bottom docking port. I accidently had a stray shot went upward and hit Bot A because I was shooting from a ladder and was climbing up a bit to get distance, making the gun pointed up. The bot immediately dumped all his SMG ammo on me and left after I was unconcious. Bot B healed me. Bot A decided to return with more SMG ammo and kept shooting me to death. Rinse and repeated with Bot B healing me.

I think maybe having them check if there was a hostile target within 5~10 meters of them when they received damage to ignore getting shot and just flee might be a good behaviour.

**Version**
0.10.5.0

**Additional Information**
I like to equip all my bots with SMG.

**Comment by itchyOwl** [comment] 2020-09-18 16:28
Bot's shouldn't retaliate if they are in the same team and accidentally shoot each other. So it's a bug.

**Comment by itchyOwl** [comment] 2020-09-22 17:48
Didn't read the description well. I thought the bots shot at each other in purpose. That shouldn't happen and I just tested that it doesn't.

So if you accidentally shot a crew member and it shot back, it's not a bug. But you are right: the context should matter. I'd say, if there are enemies on the same submarine, it should be enough for them to not take the offensive on you. We could check the distance or the visible hulls instead, but I'm afraid that that would leave some corner cases where they still start shooting at you.

**Comment by itchyOwl** [comment] 2020-09-22 18:06
I tested it a bit, and it seems that just checking the submarine might lead into weird situations too. So let's try the visible hulls.

**Comment by itchyOwl** [comment] 2020-09-22 18:35
Addressed in Regalis11/Barotrauma-development@46afb81.

**Comment by Rokvach** [comment] 2020-09-24 07:48
Tested, working correctly. Closing.

**Closed by Rokvach** 2020-09-24 07:48 UTC
Labels: Code
