### ISSUE TITLE
Can't enter a certain station 

### ISSUE THREAD

**Issue by BruhMomento0** [Regalis11/Barotrauma#10772] opened 2022-12-19 12:51 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [x] My issue happened while using mods.

### What happened?

When I dock at the colony the error messages will appear then it starts the game at uninhabited location, I tried to dock for 3 rounds, restart the game and dock again, it still persists, so I can't proceed the game further 

not sure if this is a duplicate of #10457

(Note: I tried to dock again after writing this report to dump the error message but somehow it got fixed, a screenshot is all I got)

![image](https://user-images.githubusercontent.com/66198490/208422359-17ea15a3-2b7e-48c2-b3f2-f6cd9a137d14.png)
![image](https://user-images.githubusercontent.com/66198490/208425533-4551b625-4d63-47dd-bcc5-1f20bf17165e.png)
![image](https://user-images.githubusercontent.com/66198490/208429205-6bf42744-21c4-4417-934d-828426c7b25e.png)

### Bug prevalence

Just once

### Version

0.20.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-01-16 17:39
Thank you for the report, and sorry for taking so long to respond!

Do you by any chance still have this save file available? If you could attach it here, it'd help us a lot in diagnosing the issue. Thanks and sorry for the inconvenience!

**Comment by Regalis11** [comment] 2023-01-16 18:48
While trying to diagnose this, I accidentally found a way to repro https://github.com/Regalis11/Barotrauma/issues/5949. These 2 issues might be related, need to do some more digging!

**Comment by BruhMomento0** [comment] 2023-01-16 20:24
after knowing that togglecampaignteleport command exists, so I have tried and found how to reproduce modifying without modifying the save file

Steps to repro:

1. NEW GAME with map seed: Bruh2
2. Teleport to ARGIOPE LINEA (Uninhabitat before Colony at the end of the first biome)
3. Travel normally and dock at SARPEDON LINER (Colony at the end of the first biome)

**Comment by Regalis11** [comment] 2023-01-19 18:40
Thank you for the extra info! It looks like you are using mods? No wonder I couldn't reproduce the issue in the vanilla game. But after enabling Barotraumatic, I got it to happen in that save. Thanks, this should be much easier to diagnose and fix now!

**Comment by BruhMomento0** [comment] 2023-01-19 22:26
Sorry! I did actually run mod when reported that but it wasn't Barotraumatic, It was Lua for Barotrauma and Performant Fix only.
The error I reported was before I installed Barotraumatic to play with friends.

Barotraumatic and all Barotraumatic related mods was subbed at (29/Dec/2022)
![image](https://user-images.githubusercontent.com/66198490/213574749-bdae76bc-8744-4437-b050-7273bf0b53a1.png)

**Comment by Regalis11** [comment] 2023-01-20 07:49
On a closer look, it seem this can happen in the vanilla game too. It seemed to happen when you return to the empty location at the beginning of the level, which causes the map to pop up, and then close the map and continue to the end of the level. The mods only made this more likely to happen, because they seem to modify the level generation parameters in a way that makes the map always pop up at the beginning of the round.

Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2c5c8814ece96ec40043be105f0b8d3773b7ffb4 (commit in our private repository)

**Closed** 2023-01-25 12:22 UTC
Labels: Bug, Code, Modding
