### ISSUE TITLE
[Bug] Light sprites do not follow the rotation of their physics items

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#2256] opened 2020-02-11 19:28 UTC
**v0.9.6.0 - v0.9.705.0**

### Issue:
Light sprites attached to rotating items, I.E. pickable items and physics projectiles, do not follow the rotation or mirroring correctly of their parent body.

**Steps to reproduce:**

- Place an overlay <sprite/> as part of a light component on a holdable/pickable/throwable item
- Walking around or swimming with the item, mirroring character while holding it, dropping the item on an uneven surface such as the outer shell of a submarine. Physics movement & mirroring etc.

**Additional info:**
This seems to apply regardless of if the item is loose on the floor or being held & aimed/swung by a character.

**Comment by Regalis11** [comment] 2020-03-16 05:36
Sorry for the super late reply! I unfortunately wasn't able to reproduce this. I tested it by adding the nav terminal's light component to a stun baton:

```
  <Item name="" identifier="stunbaton" category="Equipment" Tags="smallitem,weapon" Scale="0.5" cargocontaineridentifier="metalcrate" impactsoundtag="impact_metal_light">
    <PreferredContainer primary="armcab" minamount="0" maxamount="2" spawnprobability="1"/>
    <Upgrade gameversion="0.9.2.0" scale="0.5"/>
    <Price locationtype="Military" buyprice="100" />
    <Price locationtype="City" buyprice="200" />
    <Price locationtype="Outpost" buyprice="500" />
    <Deconstruct time="10">
      <Item identifier="steel" />
      <Item identifier="plastic" />
    </Deconstruct>
    <Fabricate suitablefabricators="fabricator" requiredtime="10">
      <RequiredSkill identifier="weapons" level="30" />
      <RequiredItem identifier="steel" />
      <RequiredItem identifier="plastic" />
    </Fabricate>
    <InventoryIcon texture="Content/Items/InventoryIconAtlas.png" sourcerect="770,0,58,64" origin="0.5,0.5" />
    <Sprite texture="weapons_new.png" sourcerect="1,407,191,63" depth="0.55" origin="0.4954025,0.7936202" />
    <Body width="170" height="30" density="30" />
    <LightComponent range="100.0" lightcolor="255,255,255,0" powerconsumption="0" IsOn="true" castshadows="false" allowingameediting="false">
      <sprite texture="Content/Items/Command/navigatorLights.png" depth="0.025" origin="0.367,0.38" alpha="1.0" />
    </LightComponent>...
```

And it seems to work as expected:
![baton](https://user-images.githubusercontent.com/14351070/76725912-58092a00-6758-11ea-99d3-c6d6dda6de84.png)

I wonder if the issue could be somewhere in your item's config file. Do you happen to still have an xml file I could test?

**Comment by hubismal** [comment] 2020-04-14 06:41
Here's an even later reply. @Regalis11 your example has the light color value of the lightcomponent set to 255, 255, 255, 0. Setting the alpha 0 to 255 like someone would expect leads to EK's problem and some very interesting results.
![2020-04-14-013959_319x201_scrot](https://user-images.githubusercontent.com/47284081/79193775-ebce2480-7df0-11ea-82e4-db64e0a35d86.png)
Requesting that this be reopened since the 255 value behaviour probably isn't intended(?)

**Comment by Regalis11** [comment] 2020-04-15 10:18
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7d06e7e

**Comment by Rokvach** [comment] 2020-06-01 03:25
This doesn't really affect normal gameplay and hasn't caused any issues for normal gameplay, haven't got any modders to test this so I will just close this, we can re-open if something comes up. Closing.

**Closed by Rokvach** 2020-06-01 03:25 UTC
Labels: Bug, Code, Low prio, Modding
