### ISSUE TITLE
Commendation Medals reward w/ FULL HOTBAR

### ISSUE THREAD

**Issue by Dopamin3** [Regalis11/Barotrauma#7576] opened 2021-12-02 13:47 UTC
For Captains, if hotbar is full, on Mission Completion the rewards are not received for the skills Trusted Captain, and Esteemed Captain

Current Steam Windows Version

**Comment by Regalis11** [comment] 2021-12-02 14:06
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/91ab3a555dce269ec5b80448b14e86bfadc28000

**Comment by Rokvach** [comment] 2021-12-10 09:49
This seems to be more broken now, you will only get commendation medals if you have a toolbelt equipped, if you don't have a toolbelt you will not get any medals

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/e58dc257-d78e-4109-a915-3d3da324a2ae)

**Comment by Dopamin3** [comment] 2021-12-10 10:46
Is that how it is now? I usually have empty slots in my toolbelt... not
always on the hotbar since i'm usually picking stuff up a bit before
docking.

Also, i think the scan missions were bugged, and are now fixed.. as i didnt
realize i had to have the scanners for turn in.

**Comment by Regalis11** [comment] 2021-12-10 12:19
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1e646ce52b1a9df521cc467339c112694ebf78e7

**Comment by Rokvach** [comment] 2021-12-10 14:02
Only ways I wasn't able to get the medals was if I just didn't have any inventory to put it, so if my inventory and handslots were full and toolbelt was full the medals wouldn't spawn. If we want to handle this we could do it the same way as we've done elsewhere where we just drop the items next to the player but I'm not sure if thats really necessary here.

**Comment by Rokvach** [comment] 2021-12-10 14:08
This is now working correctly, if you have a empty slot in your inventory, hand slots or toolbelt the medals will be placed there, however if all of those are occupied the medals wont be spawned, but I think its very rare that you will have every slot taken especially the hand slots so I think the issue is so minor that we can close this. Closing.

**Closed by Rokvach** 2021-12-10 14:08 UTC
Labels: Bug, Code

**Comment by Dopamin3** [comment] 2021-12-10 14:10
It would probably make sense to just have them overflow into the players
hands, or onto the ground.

Into the hands would actually be pretty neat, as it would resolve any
issues with the metals being stolen as they dropped onto the floor of the
station.

I know I've had suitcases get stolen before, lol.

**Comment by Dopamin3** [comment] 2021-12-10 14:11
Thanks!

**Comment by Dopamin3** [comment] 2021-12-10 14:12
I have noticed that sometimes items aren't delivered after purchasing at
the trader. I'm wondering if that is intended? Or should I bug report it?
