### ISSUE TITLE
More Texts in "Texts" xml file- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#678] opened 2018-08-14 08:42 UTC
It's lacking lines like "Active sonar" or "Press [Crew Orders] for crew orders".

**Comment by Regalis11** [comment] 2018-08-14 08:44
Duplicate of #80

**Closed by Regalis11** 2018-08-14 08:44 UTC
Labels: duplicate

**Comment by rico6822** [comment] 2018-08-14 08:56
Another example:

English "Reward: 500 credits" should be in Polish "Nagroda: 500 kredytów" not "Nagroda: 500 kredyty".

I can only translate one "Credits" to "Kredyty", because same translation is sharing 2 different spots requiring different translations.

**Comment by NilanthAnimosus** [comment] 2018-08-14 09:05
You may want to add more flaws you find with translation to issue #80 as this is a closed duplicate, so they can be worked on with the main issue.
