### ISSUE TITLE
[Feedback] Mission molochs are so weak, minimal BOT crew on stock dugong can kill it without any losses with basic ammo

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#5395] opened 2021-03-30 19:38 UTC
**Description**
The title, here is a save with these conditions
-in level
-moloch mission, moloch is close to start to make things faster
-stock dugong, no purchases, basic crew, basic ammo
[Save 33.zip](https://github.com/Regalis11/Barotrauma/files/6231748/Save.33.zip)

**Steps To Reproduce**
-get submarine near the moloch
-send NPCs to their stations
-freecamera + los command
-observe them killing the moloch after some time

**Version**
Unstable

**Comment by itchyOwl** [comment] 2021-04-06 07:43
I kind of agree that they might be a bit weak for the mission. And actually they should be slightly stronger overall in the latest unstable version.

The issue is that molochs are not intended as primarily aggressive beasts. And unless we boost them, we can't just crank up the health for the mission variant, because it would be odd if the health/strength difference between a normal moloch and the mission variant would be too significant. That being said, the health is now 1500 when it used to be 1150 (normal Moloch 1000->1250).

I think the mission is not intended to be very difficult, but I thought it's possible that the mission spawns the black variation instead of the regular. Looking in the code this doesn't happen. I'll change that right away. @ezjamsen, please comment if you disagree.

**Comment by itchyOwl** [comment] 2021-04-06 09:04
For some reason black molochs were configured to do _less_ structural damage than regular molochs. Fixed that in Regalis11/Barotrauma-development@ed4cb17.

Boosted the structural damage slightly for both molochs in Regalis11/Barotrauma-development@a649ea6.

Added the black moloch mission variants, mentioned above, in Regalis11/Barotrauma-development@6bbb3aa.

While testing the mission variants, I noticed that they have difficulties in registering the attacks. I increased the attack and damage ranges to overcome this.

So I'd consider this done. Moving to QA.

**Comment by Udrakan** [comment] 2021-04-06 22:35
Did you talk with Chad about what I've sent him? There are ways to balance molochs in a way where they aren't agressive, but still are menacing. Consider what I've done in ITA (we talked about this a lot with Chad):
-minimal to no structure damage
-blunt damage to crew in radius around impact site
-leave the sub be if unprovoked
-highly resistant to coilgun fire, but die to a nuke (this gives the feeling of acquiring a "big gun" that can kill "big monster" and everybody knows killing big monsters with big guns is fun).

Just changing HP or structural damage is boring for balance imo. Either you end up with a bulletsponge or an unfair enemy that kills you every time. Thats why making moloch have "normal" HP but changing resistance to coilgun and having it deal "different" type of damage (to crew, not to hull like most other monsters) feels so good.

I saw some attack explosion related to molochs on git a while back, did you decide to get rid of it due to difficulty maybe? I've been tweaking molochs around for ages with this - they can feel both menacing and at the same time not be agressive, which is what it feels like you want to accomplish for them.

**Comment by Udrakan** [comment] 2021-04-06 23:02
Also, instead of flooding you and repeatedly attacking a stationary flooded target in crisis, zero/minimal structure damage makes molochs push the submarine away and many a times it happened that it pushed us far enough away in the mod to stop pursuing, which seems like what you might be looking for (pushing you out of its territoriy, not pursuing, not dunking on a sub in crisis...)

**Comment by itchyOwl** [comment] 2021-04-07 07:51
We've been talking with Chad, but not recently. I don't recall whether or not he mentioned your ideas last time when we discussed. Possibly.

Chad had an idea to use area of effect damage that would stun and hit the crew inside the sub, and explosions kind of suit this well. So we did test a relatively big area of effect range with stunning and damaging the crew. It certainly was effective, but also had a number of issues. For example those effects apply to all targets inside the range. We can now filter out targets that are outside the submarine, but we'd also have to filter out targets that are inside other submarines than the one that is hit. Moreover I really didn't feel that the stunning and damaging the crew due to the hit was plausible. Due to issues like that we nerfed the range quite a lot and reworked the impacts to the submarine instead. The effect is now different and not nearly as impactful as it was, but I think it's in general more balanced now.

The idea with Molochs it that they are provoked by noise. It's not clearly enough communicated though. We've now adjusted the sounds to make it better, but I think we could do better there. Or just drop that and make them neutral unless attacked. Although that would make it preferable for the player to just ignore them. I'm not sure we want to encourage that. Currently going pass them silently requires that you turn off the sonar, which I think is more fun (They can attack the sub even when the sonar is off if they are close enough).

I agree with the resistance to coilgun damage and being suspectible to railgun damage. And that's kind of what we've been trying to do: you'll have to break the armor with railgun before you can easily hit it with the coilgun (or just keep firing with the railgun). There's been changes to how railgun work now: instead of piecing it now explodes. There's also been adjustments on nukes. Shooting with nukes should be an effective way to kill Molochs. I wonder what was your implementation? I think the issue with just adding protection against damage x and resistance for damage y is that we'd have to communicate that somehow.

I agree that just changing the hp or the damage is not often enough. And I'm not saying it's enough here either. But I think there was room for improvement there too.

Pushing is intentional and Moloch should do that too. I don't see how that relates to the structural damage, as the creature can do both at the same time.

But I'd be happy to test your work, if you wish to post it here or give a link to the mod.

**Comment by Udrakan** [comment] 2021-04-09 20:24
I've done the explosion stunning and blunt forcing the crew in the mod, but you've tested it already, thank you. I agree fully with your last post and think that disabling sonar to get past moloch would definetly be better than attack when provoked only.

**Comment by Rokvach** [comment] 2021-04-10 23:24
Tested, no issues. Closing.

**Closed by Rokvach** 2021-04-10 23:24 UTC
Labels: Design
