### ISSUE TITLE
[Unstable(?)] Crash when starting 'clownrelations1' event

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#9704] opened 2022-08-13 04:11 UTC
- Build Unstable 0.19.0.0 Windows
(Although it might also be possible on current v0.18 stable)
- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### Description
Was playing through campaign on unstable-branch in search of bugs, 
minding my own business and then managed to find a crash somehow by touching the toolbox that starts the clown horn quest.

### Reproduction steps
- No clue, just did some missions and then arrived at a city outpost.
- The event toolbox spawned in the starting 'hub' of the station and then clicking it crashed the game.

### Stack trace

> Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
> Target site: Void SetBackgroundIcon(Barotrauma.Sprite)
> Stack trace: 
>    at Barotrauma.GUIMessageBox.SetBackgroundIcon(Sprite icon) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIMessageBox.cs:line 474
>    at Barotrauma.ConversationAction.CreateDialog(String text, Character speaker, IEnumerable`1 options, Int32[] closingOptions, String spriteIdentifier, ConversationAction actionInstance, Nullable`1 actionId, Boolean fadeToBlack, DialogTypes dialogType, Boolean continueConversation) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Events\EventActions\ConversationAction.cs:line 117
>    at Barotrauma.ConversationAction.ShowDialog(Character speaker, Character targetCharacter) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Events\EventActions\ConversationAction.cs:line 45
>    at Barotrauma.ConversationAction.TryStartConversation(Character speaker, Character targetCharacter) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\EventActions\ConversationAction.cs:line 374
>    at Barotrauma.ConversationAction.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\EventActions\ConversationAction.cs:line 210
>    at Barotrauma.ConversationAction.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\EventActions\ConversationAction.cs:line 210
>    at Barotrauma.ScriptedEvent.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\ScriptedEvent.cs:line 216
>    at Barotrauma.EventManager.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\EventManager.cs:line 733
>    at Barotrauma.GameSession.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 713
>    at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 150
>    at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 874
>    at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
>    at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
>    at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
>    at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
>    at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
>    at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

### Debug log ( I assure you there's nothing interesting here )

> Last debug messages:
> [8/13/2022 12:00:13 AM] Generating an outpost for the start of the level... (Location: Serac, level type: Outpost)
> [8/13/2022 12:00:13 AM] Level identifier: outpostlevel
> [8/13/2022 12:00:02 AM] Transitioning to Serac (current location: Asmundur Habitation Outpost, selected location: Serac, leaving sub: EK_Skipper_Mk-V, at start: False, at end: True, transition type: ProgressToNextLocation)
> [8/12/2022 11:49:56 PM] Generating an outpost for the end of the level... (Location: Serac, level type: LocationConnection)
> [8/12/2022 11:49:56 PM] Generating an outpost for the start of the level... (Location: Asmundur Habitation Outpost, level type: LocationConnection)
> [8/12/2022 11:49:55 PM] Level identifier: coldcavernsbasic
> [8/12/2022 11:49:44 PM] Transitioning to AsmundurSerac (current location: Asmundur Habitation Outpost, selected location: Serac, leaving sub: EK_Skipper_Mk-V, at start: True, at end: False, transition type: LeaveLocation)
> [8/12/2022 11:48:08 PM] Generating an outpost for the start of the level... (Location: Asmundur Habitation Outpost, level type: Outpost)
> [8/12/2022 11:48:08 PM] Level identifier: outpostlevel
> [8/12/2022 11:47:57 PM] Transitioning to Asmundur (current location: Asmundur Habitation Outpost, selected location: Seosu, leaving sub: EK_Skipper_Mk-V, at start: True, at end: False, transition type: ReturnToPreviousLocation)
> [8/12/2022 11:47:38 PM] Generating an outpost for the start of the level... (Location: Seosu, level type: LocationConnection)
> [8/12/2022 11:47:37 PM] Generating an outpost for the end of the level... (Location: Asmundur Habitation Outpost, level type: LocationConnection)
> [8/12/2022 11:47:37 PM] Level identifier: coldcavernsbasic
> [8/12/2022 11:47:25 PM] Transitioning to SeosuAsmundur (current location: Asmundur Habitation Outpost, selected location: Seosu, leaving sub: EK_Skipper_Mk-V, at start: True, at end: False, transition type: LeaveLocation)
> [8/12/2022 11:26:00 PM] Unlocked mission "Getting rid of Mudraptors" in the location "Asmundur Habitation Outpost".
> [8/12/2022 11:25:57 PM] Unlocked mission "Killing a large Crawler" in the location "Asmundur Habitation Outpost".
> [8/12/2022 11:25:54 PM] Unlocked mission "Explosive cargo" in the location "Asmundur Habitation Outpost".
> [8/12/2022 11:24:51 PM] Generating an outpost for the start of the level... (Location: Asmundur Habitation Outpost, level type: Outpost)
> [8/12/2022 11:24:51 PM] Level identifier: outpostlevel
> [8/12/2022 11:24:40 PM] Transitioning to Asmundur (current location: Newellstead Prospecting Outpost, selected location: Asmundur Habitation Outpost, leaving sub: EK_Skipper_Mk-V, at start: False, at end: True, transition type: ProgressToNextLocation)
> [8/12/2022 11:15:46 PM] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
> [8/12/2022 11:15:42 PM] Generating an outpost for the start of the level... (Location: Asmundur Habitation Outpost, level type: LocationConnection)
> [8/12/2022 11:15:41 PM] Generating an outpost for the end of the level... (Location: Newellstead Prospecting Outpost, level type: LocationConnection)
> [8/12/2022 11:15:41 PM] Level identifier: coldcavernsadvanced
> [8/12/2022 11:15:30 PM] Transitioning to AsmundurNewellstead (current location: Newellstead Prospecting Outpost, selected location: Asmundur Habitation Outpost, leaving sub: EK_Skipper_Mk-V, at start: True, at end: False, transition type: LeaveLocation)
> [8/12/2022 11:05:11 PM] Unlocked mission "Terminate a Swarm" in the location "Newellstead Prospecting Outpost".
> [8/12/2022 11:05:08 PM] Unlocked mission "Personnel Transport" in the location "Newellstead Prospecting Outpost".
> [8/12/2022 11:05:05 PM] Unlocked mission "Giant Spineling" in the location "Newellstead Prospecting Outpost".
> [8/12/2022 11:04:27 PM] Generating an outpost for the start of the level... (Location: Newellstead Prospecting Outpost, level type: Outpost)
> [8/12/2022 11:04:27 PM] Level identifier: outpostlevel
> [8/12/2022 11:04:16 PM] Transitioning to Newellstead (current location: Pastonia Habitation Outpost, selected location: Newellstead Prospecting Outpost, leaving sub: EK_Skipper_Mk-V, at start: False, at end: True, transition type: ProgressToNextLocation)
> [8/12/2022 11:00:54 PM] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
> [8/12/2022 11:00:50 PM] Generating an outpost for the end of the level... (Location: Newellstead Prospecting Outpost, level type: LocationConnection)
> [8/12/2022 11:00:49 PM] Generating an outpost for the start of the level... (Location: Pastonia Habitation Outpost, level type: LocationConnection)
> [8/12/2022 11:00:49 PM] Level identifier: coldcavernsadvanced
> [8/12/2022 11:00:38 PM] Transitioning to PastoniaNewellstead (current location: Pastonia Habitation Outpost, selected location: Newellstead Prospecting Outpost, leaving sub: EK_Skipper_Mk-V, at start: True, at end: False, transition type: LeaveLocation)
> [8/12/2022 10:52:39 PM] Unlocked mission "Personnel Transport" in the location "Pastonia Habitation Outpost".
> [8/12/2022 10:52:36 PM] Unlocked mission "Killing Hammerheads" in the location "Pastonia Habitation Outpost".
> [8/12/2022 10:52:34 PM] Unlocked mission "Mining pyromorphite" in the location "Pastonia Habitation Outpost".
> [8/12/2022 10:51:12 PM] Generating an outpost for the start of the level... (Location: Pastonia Habitation Outpost, level type: Outpost)
> [8/12/2022 10:51:12 PM] Level identifier: outpostlevel
> [8/12/2022 10:51:02 PM] Transitioning to Pastonia (current location: Riville Habitation Outpost, selected location: Pastonia Habitation Outpost, leaving sub: EK_Skipper_Mk-V, at start: False, at end: True, transition type: ProgressToNextLocation)
> [8/12/2022 10:45:11 PM] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
> [8/12/2022 10:45:07 PM] Generating an outpost for the end of the level... (Location: Pastonia Habitation Outpost, level type: LocationConnection)
> [8/12/2022 10:45:06 PM] Generating an outpost for the start of the level... (Location: Riville Habitation Outpost, level type: LocationConnection)
> [8/12/2022 10:45:06 PM] Level identifier: coldcavernsadvanced
> [8/12/2022 10:44:55 PM] Transitioning to RivillePastonia (current location: Riville Habitation Outpost, selected location: Pastonia Habitation Outpost, leaving sub: EK_Skipper_Mk-V, at start: True, at end: False, transition type: LeaveLocation)
> [8/12/2022 10:42:48 PM] Unlocked mission "Personnel Transport" in the location "Riville Habitation Outpost".
> [8/12/2022 10:42:45 PM] Unlocked mission "Terminate a Swarm" in the location "Riville Habitation Outpost".
> [8/12/2022 10:42:43 PM] Unlocked mission "Mining uranium" in the location "Riville Habitation Outpost".
> [8/12/2022 10:39:22 PM] Generating an outpost for the start of the level... (Location: Riville Habitation Outpost, level type: Outpost)
> [8/12/2022 10:39:22 PM] Level identifier: outpostlevel
> [8/12/2022 10:39:12 PM] Transitioning to Riville (current location: Asmundur, selected location: Riville Habitation Outpost, leaving sub: EK_Skipper_Mk-V, at start: False, at end: True, transition type: ProgressToNextLocation)
> [8/12/2022 10:14:03 PM] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
> [8/12/2022 10:13:58 PM] Could not find a suitable module for the location type LocationType (None). Module flag: Airlock.
> [8/12/2022 10:13:57 PM] Generating an outpost for the end of the level... (Location: Asmundur, level type: LocationConnection)
> [8/12/2022 10:13:57 PM] Level identifier: coldcavernsadvanced
> [8/12/2022 10:13:46 PM] Transitioning to RivilleAsmundur (current location: Asmundur, selected location: Riville Habitation Outpost, leaving sub: EK_Skipper_Mk-V, at start: False, at end: True, transition type: ProgressToNextEmptyLocation)
> [8/12/2022 9:58:40 PM] Generating an outpost for the start of the level... (Location: Seosu, level type: LocationConnection)
> [8/12/2022 9:58:40 PM] Level identifier: coldcavernsbasic
> [8/12/2022 9:58:29 PM] Transitioning to SeosuAsmundur (current location: Seosu, selected location: Asmundur, leaving sub: EK_Skipper_Mk-V, at start: True, at end: False, transition type: LeaveLocation)
> [8/12/2022 9:44:33 PM] Unlocked mission "Personnel Transport" in the location "Seosu".
> [8/12/2022 9:44:30 PM] Unlocked mission "Medical item transport" in the location "Seosu".
> [8/12/2022 9:44:25 PM] Unlocked mission "Killing Hammerheads" in the location "Seosu".
> [8/12/2022 9:43:50 PM] Generating an outpost for the start of the level... (Location: Seosu, level type: Outpost)
> [8/12/2022 9:43:50 PM] Level identifier: outpostlevel
> [8/12/2022 9:43:40 PM] Transitioning to Seosu (current location: Agave Linea Outpost, selected location: Seosu, leaving sub: EK_Skipper_Mk-V, at start: False, at end: True, transition type: ProgressToNextLocation)
> [8/12/2022 9:40:53 PM] Generating an outpost for the end of the level... (Location: Seosu, level type: LocationConnection)
> [8/12/2022 9:40:53 PM] Generating an outpost for the start of the level... (Location: Agave Linea Outpost, level type: LocationConnection)
> [8/12/2022 9:40:53 PM] Level identifier: coldcavernsbasic
> [8/12/2022 9:40:42 PM] Transitioning to Agave LineaSeosu (current location: Agave Linea Outpost, selected location: Seosu, leaving sub: EK_Skipper_Mk-V, at start: True, at end: False, transition type: LeaveLocation)
> [8/12/2022 9:28:03 PM] Unlocked mission "Personnel Transport" in the location "Agave Linea Outpost".
> [8/12/2022 9:28:00 PM] Unlocked mission "Getting rid of Mudraptors" in the location "Agave Linea Outpost".
> [8/12/2022 9:27:56 PM] Unlocked mission "Chemical shipment" in the location "Agave Linea Outpost".
> [8/12/2022 9:16:42 PM] Generating an outpost for the start of the level... (Location: Agave Linea Outpost, level type: Outpost)
> [8/12/2022 9:16:42 PM] Level identifier: outpostlevel
> [8/12/2022 9:11:28 PM] Attempting to open ALC device "OpenAL Soft on Speakers (High Definition Audio Device)"
> [8/12/2022 9:11:27 PM] Logged in as Videogames (SteamID STEAM_1:1:49409891)

**Comment by Regalis11** [comment] 2022-08-15 07:00
Duplicate of https://github.com/Regalis11/Barotrauma/issues/9686

**Closed by Regalis11** 2022-08-15 07:00 UTC
