### ISSUE TITLE
Players given "Low on Fuel" warning when purchasing a new sub despite accepting item transfer and having several fuel rods on the previous sub

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11063] opened 2023-01-28 04:11 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If you have several fuel rods on your submarine and you go to purchase a new submarine whilst enabling transfer items, you will still get the low fuel warning when trying to leave the station. 
![image](https://user-images.githubusercontent.com/105495756/215241341-a218a31f-4b96-4f35-9ba6-cc08f02aec59.png)

### Bug prevalence

Just once

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by DuckY-Y** [comment] 2023-01-28 20:11
Had this too on a multiplayer server

**Comment by itchyOwl** [comment] 2023-02-21 09:54
You wrote that it was a new submarine that you purchased? Which sub was it? The Low fuel tag is added when the sub is saved, so it could be an issue with the sub.

**Comment by DuckY-Y** [comment] 2023-02-21 11:05
I had this pop-up appear in a multiplayer session, in my case I was switching to a custom submarine, my own, one that has auto-fill on.

This pop-up also appeared while trying to switch to a locally saved submarine as client.
[Local sub selection in multi](https://github.com/Regalis11/Barotrauma/issues/11011)

**Comment by Regalis11** [comment] 2023-02-21 12:09
> You wrote that it was a new submarine that you purchased? Which sub was it? The Low fuel tag is added when the sub is saved, so it could be an issue with the sub.

Doesn't seem to matter, this seems to happen with vanilla subs as well (I tested switching from Barsuk to Dugong and vice versa, the warning is shown in both cases).

I'm not entirely sure if this is a bug or working as intended: I guess the issue here is that the warning is shown if there's no pre-placed rods in the sub, even if you currently have lots of them and opted to transfer. I guess technically the warning is correct (there are no rods in the sub now, but there will be after the transfer), but it still seems very misleading.

**Comment by itchyOwl** [comment] 2023-02-22 07:59
Could be an oversight, if we don't take the items in the current sub into account _and_ have opted to transfer the items. Also possible that there was a techical reason for it. I'll look into it at some point.

**Comment by itchyOwl** [comment] 2023-06-02 08:24
Fixed in Regalis11/Barotrauma-development@09cd035. We now also check the current sub, when transferring the items. The items in the player inventories still don't count. Wasn't sure if they should.

**Comment by Jasontti** [comment] 2023-06-21 07:09
Tested.
Switching sub and taking items works with new sub and one from storage.
Warning is properly given when switching subs an NOT transferring items.
Closing ticket.

**Closed by Jasontti** 2023-06-21 07:09 UTC
Labels: Bug, Code, Design, Low prio
