### ISSUE TITLE
AI won't shoot turrets when more than 1 is wired to periscope

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#8998] opened 2022-04-27 11:35 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you have multiple turrets wired to the same periscope, bots cannot shoot the turret sometimes.

It seems that **both turrets need line of sight** on the target. 
The bot refuses to shoot the red turret unless green turret (which is "deactivated") has a line of sight on the target.

This also causes issues when using turrets on shuttles over wifi

![TurretAIBug](https://user-images.githubusercontent.com/73229309/165509783-6fbec8d5-c3a6-4ecd-ba75-8f09e9fea393.jpg)

[Turretbug.zip](https://github.com/Regalis11/Barotrauma/files/8571600/Turretbug.zip)

Also see #8370

**Comment by Regalis11** [comment] 2022-04-27 11:57
Duplicate of https://github.com/Regalis11/Barotrauma/issues/8370

**Closed by Regalis11** 2022-04-27 11:57 UTC
