### ISSUE TITLE
Modded skills don't get added to the skill dictionary when using SetSkillLevel

### ISSUE THREAD

**Issue by Mannatwo** [Regalis11/Barotrauma#8834] opened 2022-04-17 11:25 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In CharacterInfo.SetSkillLevel, attempting to add a skill with an identifier previously unknown to the character info, the line
Job.Skills.Add(new Skill(skillIdentifier, level));
adds the new skill to the skill list that has been converted from the proper skill dictionary, rendering the line of code ineffectual in actually adding the skill to the character info object.
This issue is not present in the method Job.IncreaseSkillLevel.

**Steps To Reproduce**
- start a game
- use the "setskill" command for any non-vanilla skill identifier
- open the tab menu
- witness the absence of the supposedly added skill

**Version**
v0.16.7.0, Windows

**Additional information**
This issue is especially present in multiplayer, because the server periodically uses the SetSkillLevel method to update the clients skills instead of directly using the IncreaseSkillLevel method.
Fixing this issue would greatly improve the ability for mods to add their own skills, since right now, attempting to do so causes constant popups when gaining any sort of skill when the character has at least one level in the modded skill.

**Comment by Regalis11** [comment] 2022-04-19 10:49
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a51fe730ba3213880f0480c17f5d8daf4e046fda

**Comment by Rokvach** [comment] 2022-04-27 09:45
Tested, wasn't able to reproduce the issue, seems to be working correctly. Closing.

**Closed by Rokvach** 2022-04-27 09:45 UTC
Labels: Bug, Code, Modding, Medium Prio
