### ISSUE TITLE
AI can't climb into the engine room in Typhon

### ISSUE THREAD

**Issue by SirKnight123** [Regalis11/Barotrauma#12183] opened 2023-06-18 07:53 UTC
The AI can not climb the ladder into the engine room in the Typhon 1

**Comment by Regalis11** [comment] 2023-06-18 09:00
Thank you for the report! I unfortunately couldn't reproduce the issue:

https://github.com/Regalis11/Barotrauma/assets/14351070/7cbba053-cc3f-4fcc-bd63-54834f140c56

Are you using an unmodified, up-to-date version of the sub? And not using any mods?

**Comment by SirKnight123** [comment] 2023-06-18 12:57
No, I played vanilla. I think it's an issue with the sub itself (prob. the
AI pathfinding)

2023-06-18, sk 12:00, Joonas Rikkonen ***@***.***> rašė:

**Comment by eliw00d** [comment] 2023-06-20 21:53
I have this same exact issue! All the AI crewmembers just sit on the ladder and do a little dance. Would a save game help debug it? Or what can be provided to help? Same as @SirKnight123, I am playing on vanilla.

**Comment by Regalis11** [comment] 2023-06-21 06:47
A save file would most likely help! Also, if you know some way to get the bug to happen consistently (like, if the bots always get stuck when they're going to repair the engine or a leak in some specific spot), that'd also help us a lot in diagnosing the bug.

**Comment by itchyOwl** [comment] 2023-06-21 09:34
A save file would help to identify the issue. Or a screenshot that shows the waypoints. Please use the "debugai" console command. The waypoints should look like this 
![image](https://github.com/Regalis11/Barotrauma/assets/5370738/c2402cc9-f904-4e8d-8f43-ac3144109890)

If they don't, the sub is an older version. Unfortunately there's currently no (easy) way to "update" the sub to the latest version. Purchasing a new sub or starting a new campaign should fix it.

**Comment by NilanthAnimosus** [comment] 2023-06-21 13:08
Took a look at version 1.0.13.1's typhon, and it appears (when examined in 1.0.20.1) it has waypoint issues, the version of the typhon in 1.0.20.1 appears to not have these waypoint issues, so it appears to be a case of old submarines, unfortunately there isn't any simple way I can think of to update/fix an old submarine in a multiplayer campaign (Potentially save editor or such?).

![image](https://github.com/Regalis11/Barotrauma/assets/29177976/e76589f8-1172-40f5-bbca-0954fdf838f9)

Closing as the issue is fixed in the newer versions of the submarines, it is not possible at this time to update old submarines in game. but in the newer version if you purchaser and switch to another submarine that will work too.

**Closed by NilanthAnimosus** 2023-06-21 13:08 UTC
Labels: Bug, Need more info
