### ISSUE TITLE
Herja turret motion detector issues

### ISSUE THREAD

**Issue by WhySmau** [Regalis11/Barotrauma#8233] opened 2022-02-11 11:41 UTC
Herjas rear hardpoints motion detector goes to the light of the bottom right hardpoint and the bottom right hardpoint doesnt have a motion detector for it

![Näyttökuva (1017)](https://user-images.githubusercontent.com/86321358/153585266-aebb5d6a-a8c7-4433-b1b1-42fb8d106b90.png)

![Näyttökuva (1018)](https://user-images.githubusercontent.com/86321358/153585274-7133c83b-6ffd-4128-8c91-8036290fddf6.png)

**Version**
v0.16.3.0

**Comment by Regalis11** [comment] 2022-02-14 10:35
Duplicate of https://github.com/Regalis11/Barotrauma/issues/8220

**Closed by Regalis11** 2022-02-14 10:35 UTC
