### ISSUE TITLE
Dialog duplicated in the "occupational hazards" event

### ISSUE THREAD

**Issue by Bocharik** [Regalis11/Barotrauma#12008] opened 2023-05-14 09:58 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Dialog duplicated when go to Station
![image](https://github.com/Regalis11/Barotrauma/assets/95054751/fe56b465-d263-420b-bc53-a676d56661f2)

### Reproduction steps

1.Go to a Station
2.Trigger event
3.Event duplicated

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-05-14 16:13
Thank you for the report!

This seems to be the event "occupational hazards" (can be triggered using the console command `triggerevent occupationalhazards`). I gave it a test, but unfortunately couldn't get the texts to duplicate. It seems you're running a heavily modded game, I wonder if some of those might be modifying the events in some way?

**Comment by Regalis11** [comment] 2023-05-29 19:14
No known steps to repro (and could potentially be caused by mods), closing

**Closed by Regalis11** 2023-05-29 19:14 UTC
Labels: Bug, Need more info
