### ISSUE TITLE
I cant load into the data(multi)

### ISSUE THREAD

**Issue by Natsumi2024** [Regalis11/Barotrauma#12201] opened 2023-06-20 09:35 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I cant load the game after change the submarine to herja.(nothing happen after the 'waitinf for loading')

### Reproduction steps

1.multiplayer campaign 2.change the submarine to herja and exchange items from the old submarine 3. save and leave 4. restart server 5. stuck on'waiting for loading'

### Bug prevalence

Just once

### Version

v1.0.20.1

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
cant load into game data, no any error message
```

**Comment by Regalis11** [comment] 2023-06-20 10:07
Thank you for the report!

Would it be possible to send us the save file so we can give it a try and see if we can reproduce and diagnose the issue? Thanks and sorry for the inconvenience!

**Comment by Natsumi2024** [comment] 2023-06-20 12:35
https://drive.google.com/drive/folders/1r4hlozP0GVWBdI2a5eZ40WGcZZk_rMUJ?usp=sharing

**Comment by NilanthAnimosus** [comment] 2023-06-21 03:43
Thanks for the save - Tested on 1.0.20.1

An upcoming hotfix is coming that should fix this issue #12170

Notes:
After recreating your loaded mods as close as I could get it:
![image](https://github.com/Regalis11/Barotrauma/assets/29177976/7e08f8e7-a2ef-4108-bb7b-8994975d9893)

appears to be this error:
![image](https://github.com/Regalis11/Barotrauma/assets/29177976/64677e87-c27a-42f6-9352-7c39ff2a26b9)

It may be worthy of note however that hosting via steamP2P the server doesn't inform the clients of the failure to load the campaign save it seems:
![image](https://github.com/Regalis11/Barotrauma/assets/29177976/40a99c66-2216-445f-b94c-b6d211e41483)

**Comment by Regalis11** [comment] 2023-06-21 06:20
Duplicate of https://github.com/Regalis11/Barotrauma/issues/12170

**Closed by Regalis11** 2023-06-21 06:20 UTC
Labels: Bug, Duplicate, Code

**Comment by Natsumi2024** [comment] 2023-06-21 09:26
Thanks a lot
