### ISSUE TITLE
New Watcher's effects "too aggressive"

### ISSUE THREAD

**Issue by gringlebop** [Regalis11/Barotrauma#4167] opened 2020-10-30 02:31 UTC
- [Yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Watcher's screen distortion, nausea, and psychosis applies while inside of the submarine at an incredible rate

**Steps To Reproduce**
Tested in a non-dedicated server and in submarine editor by spawning watcher at bottom/top of a vanilla Humpback, results inconsistent with either the slow climb or near-instant unplayable screen distortion. All were done inside the submarine.

**Version**
v0.10.6.2, Unactivated Windows 10 OS (NOT pirated)

**Additional information**
Personal opinion here, are the effects meant to be so drastic while inside the submarine? Severe nausea and heavy psychosis within a minute of one showing up is a little extreme, but its the first iteration, mabye some fine tuning will fix it?
![yesa](https://user-images.githubusercontent.com/73678381/97653087-2c079400-1a1d-11eb-92e8-69b6b9a66897.png)
Image Info: Fullscreen image, looking away from watcher which resides in the top right of the image,.
Image Info, 10/30/2020: The massive screen distortion and effects with it occurred within 5-15 seconds, applying itself to maximum near instantly. Apologies for not mentioning earlier.

**Comment by ezjamsen** [comment] 2020-10-30 09:40
In my opinion the effect is about right, but the watcher does not appear to disengage and swim away without being attacked by the player, which can make its attack a bit more severe over time than intended. @itchyOwl Could we have it retreat after it's stared at the sub for some period of time?

**Comment by itchyOwl** [comment] 2020-10-30 15:24
I think the issue might be because there's two stages in the affliction of which the second is much more severe and intense. It increases rapidly, but wears down quickly too. This later stage shouldn't happen while inside a sub, but it's range based so it can happen if the watcher is just behind the wall and the player is on the other side. I think we should look into preventing this first. And if we still want to make it retreat, we can do it. Personally I don't think it should retreat.

**Comment by itchyOwl** [comment] 2020-11-11 17:24
Addressed in Regalis11/Barotrauma-development@9c49bd9. The severe states (>50% and >60%, there's actually a transition "state" between the light and the severe affliction "states") shouldn't anymore trigger inside the submarine.

**Comment by Xeavas** [comment] 2020-11-13 17:17
[0.1100.0.6] - Working correctly, `Watcher's Gaze` doesn't go above >50% in submarine (but does so outside as intended). 👍

**Comment by Rokvach** [comment] 2020-11-13 17:24
Closing.

**Closed by Rokvach** 2020-11-13 17:24 UTC
Labels: Code, Design, Feature request
