### ISSUE TITLE
Cigar use: No "Psychosis Resistance" icon on buff list.

### ISSUE THREAD

**Issue by Dopamin3** [Regalis11/Barotrauma#7575] opened 2021-12-02 13:28 UTC
Use a Cigar, Right Click + Left Click.

On buff tab, Nothing pops up. No icon. There should be a spider-webbed shield icon indicating psychosis resistance buff. 

The pipe works fine, has buff icon. 

Version:
Steam Windows Version, Current as of 12-2-2021 8:28am EST

**Comment by Regalis11** [comment] 2021-12-02 13:36
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7166

**Closed by Regalis11** 2021-12-02 13:36 UTC
