### ISSUE TITLE
"Oops! Barotrauma just crashed"

### ISSUE THREAD

**Issue by Decy12** [Regalis11/Barotrauma#5021] opened 2021-02-10 08:49 UTC
Barotrauma crashes as soon as it starts up.

Installed OpenAL and same message pops up.

Before OpenAL:
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/5956853/crashreport.log)

After OpenAL:
[crashreport (8).log](https://github.com/Regalis11/Barotrauma/files/5956856/crashreport.8.log)

**Comment by Regalis11** [comment] 2021-02-10 09:29
Duplicate of https://github.com/Regalis11/Barotrauma/issues/1833

**Closed by Regalis11** 2021-02-10 09:29 UTC

**Comment by theDisSent** [comment] 2026-01-25 15:26
Greetings GitHuber, I got an usual bug from Barotrauma and don't know what to do. At the first one I just rebooted my PC to factory resets. So I installed all my games and decided launch Barotrauma and it's just stop at 80% okay. I followed some guides like change smth in files for example start it as admin, uninstall and install back, to verify integrity of game files in steam and etc. So in the end I got "Oops! Barotrauma just crashed" and crashreport.

[crashreport.log](https://github.com/user-attachments/files/24846510/crashreport.log)

[crashreport (6).log](https://github.com/user-attachments/files/24846512/crashreport.6.log)

If somebody knows what to do with this please help.
I really love Barotrauma I've played more than 1k hrs.
