### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by chawley9** [Regalis11/Barotrauma#3977] opened 2020-10-01 18:25 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When i get grappled by the derelict ship and go in to destroy the organs and such to release my ship. Crashes.
No Mods being used.

**Steps To Reproduce**
so it was in a ship of my own making, not especially complicated, and got grappled by the derelict ship and was pulled in, left my ship and the crew to sort itself out whilst i went into the other ship to try and get released.

during this a lot of damage and creatures entered my ship and the game crashed.
there was a lot going on ha.

Please see below for the crash report.

Barotrauma Client crash report (generated on 01/10/2020 19:21:31)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

6F558E05A9FD96EA104348A23A5B582A

Game version 0.10.5.1 (ReleaseWindows, branch release, revision 9e259b2148)
Graphics mode: 1920x1080 (Fullscreen)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: AnnwnMolovsk
Loaded submarine: HMS Endeavor Mk IV (F8B1A566F3CD42F503E88922E6206C17)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19041.0 64 bit
    GPU name: NVIDIA GeForce GTX 1070 Ti
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Collection was modified; enumeration operation may not execute. (System.InvalidOperationException)
Target site: Void ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
Stack trace: 
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Barotrauma.Items.Components.RepairTool.Repair(Vector2 rayStart, Vector2 rayEnd, Single deltaTime, Character user, Single degreeOfSuccess, List`1 ignoredBodies) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Holdable\RepairTool.cs:line 297
   at Barotrauma.Items.Components.RepairTool.Use(Single deltaTime, Character character) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Holdable\RepairTool.cs:line 244
   at Barotrauma.Item.Use(Single deltaTime, Character character, Limb targetLimb) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 2055
   at Barotrauma.AIObjectiveCombat.Attack(Single deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjectiveCombat.cs:line 888
   at Barotrauma.AIObjectiveCombat.Act(Single deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjectiveCombat.cs:line 220
   at Barotrauma.HumanAIController.Update(Single deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\HumanAIController.cs:line 232
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2228
   at Barotrauma.GameScreen.Update(Double deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 179
   at Barotrauma.GameMain.Update(GameTime gameTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 921
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59

Last debug messages:
[01/10/2020 19:02:35] Generating an outpost for the start of the level... (Location: Annwn Fortification, level type: LocationConnection)
[01/10/2020 19:02:33] Generating an outpost for the end of the level... (Location: Molovsk Habitation Outpost, level type: LocationConnection)
[01/10/2020 19:01:11] (Msg) RelayNetWorkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[01/10/2020 19:01:11] (Msg) Ping location: lhr=7+0,ams=13+1/12+0,par=14+1,fra=19+1,lux=24+2/19+1,vie=30+3/30+1,mad=30+3,sto=33+3/32+0,sto2=38+3/32+0,iad=80+8,sgp=161+16/162+16,gru=209+20
[01/10/2020 19:01:11] (Msg) Ping measurement completed
[01/10/2020 19:01:09] (Verbose) Communications with routing cluster 'sea' established.
[01/10/2020 19:01:09] (Debug) Destroying relay 'sea#108 (205.196.6.148:27030)' because initial_ping_timeout
[01/10/2020 19:01:07] (Verbose) Communications with routing cluster 'syd' established.
[01/10/2020 19:01:07] (Verbose) Communications with routing cluster 'tyo1' established.
[01/10/2020 19:01:07] (Verbose) Communications with routing cluster 'tyo' established.
[01/10/2020 19:01:07] (Verbose) Communications with routing cluster 'sgp' established.
[01/10/2020 19:01:07] (Verbose) Communications with routing cluster 'scl' established.
[01/10/2020 19:01:07] (Verbose) Communications with routing cluster 'lim' established.
[01/10/2020 19:01:07] (Verbose) Communications with routing cluster 'maa' established.
[01/10/2020 19:01:07] (Verbose) Communications with routing cluster 'waw' established.
[01/10/2020 19:01:07] (Verbose) Communications with routing cluster 'sto2' established.
[01/10/2020 19:01:07] (Verbose) Communications with routing cluster 'lax' established.
[01/10/2020 19:01:07] (Verbose) Communications with routing cluster 'sto' established.
[01/10/2020 19:01:07] (Verbose) Communications with routing cluster 'vie' established.
[01/10/2020 19:01:06] (Verbose) Communications with routing cluster 'okc' established.
[01/10/2020 19:01:06] (Verbose) Communications with routing cluster 'hkg' established.
[01/10/2020 19:01:06] (Verbose) Communications with routing cluster 'gru' established.
[01/10/2020 19:01:06] (Verbose) Communications with routing cluster 'ord' established.
[01/10/2020 19:01:06] (Verbose) Communications with routing cluster 'jnb' established.
[01/10/2020 19:01:06] (Verbose) Communications with routing cluster 'eat' established.
[01/10/2020 19:01:06] (Verbose) Communications with routing cluster 'bom' established.
[01/10/2020 19:01:06] (Verbose) Communications with routing cluster 'mad' established.
[01/10/2020 19:01:06] (Verbose) Communications with routing cluster 'lux' established.
[01/10/2020 19:01:06] (Verbose) Communications with routing cluster 'dxb' established.
[01/10/2020 19:01:06] (Verbose) Communications with routing cluster 'par' established.
[01/10/2020 19:01:06] (Verbose) Communications with routing cluster 'lhr' established.
[01/10/2020 19:01:06] (Verbose) Communications with routing cluster 'atl' established.
[01/10/2020 19:01:06] (Verbose) Communications with routing cluster 'iad' established.
[01/10/2020 19:01:06] (Verbose) Communications with routing cluster 'fra' established.
[01/10/2020 19:01:06] (Verbose) Communications with routing cluster 'ams' established.
[01/10/2020 19:01:06] (Msg) RelayNetWorkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[01/10/2020 19:01:06] (Msg) Performing ping measurement
[01/10/2020 19:01:06] (Msg) Got SDR network config.  Loaded revision 281 OK
[01/10/2020 19:01:06] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[01/10/2020 19:00:55] Attempting to open ALC device "OpenAL Soft on Speakers (High Definition Audio Device)"
[01/10/2020 19:00:54] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[01/10/2020 19:00:53] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[01/10/2020 19:00:51] Logged in as Chawley (SteamID STEAM_1:0:44690007)

**Comment by Regalis11** [comment] 2020-10-04 09:50
Duplicate of #3896

**Closed by Regalis11** 2020-10-04 09:50 UTC
