### ISSUE TITLE
[1.0] Medal isn't in Misc category in shops

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11405] opened 2023-03-01 20:51 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When trying to purchase medals at an outpost merchant, they were unable to be found using categories. They can only be found by searching manually. 
Save file associated: 
[Coalition Outpost with a Separatist Dock.zip](https://github.com/Regalis11/Barotrauma/files/10865209/Coalition.Outpost.with.a.Separatist.Dock.zip)

![image](https://user-images.githubusercontent.com/105495756/222261922-1c313333-b6e4-4a0f-b7e3-ab05b7964802.png)
_Figure 1. Misc category in alphabetical order missing the Medal item._

![image](https://user-images.githubusercontent.com/105495756/222261960-8d6e5249-3367-4c98-8174-149a5754e8f0.png)
_Figure 2. Medal located after searching for it (it is not within the special deals section, just for clarification),_

### Bug prevalence

Just once

### Version

Other

### -

1.0.4.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-03-02 09:42
The medals are in the "Equipment" category, not "Misc".

> they were unable to be found using categories
I couldn't reproduce the issue. They seem to be listed in both the "All" tab and "Equipment".
![image](https://user-images.githubusercontent.com/14351070/222390942-69ada239-c5fb-4710-b722-3f0cb5ee3abb.png)

**Comment by Wheatley1002** [comment] 2023-03-02 09:51
I only looked for them under the "Misc" category because that's where the skill books are (and I remember them being in the misc category, but that could be a false memory or an older build), so I believed they would be in the same category since they have similar functions of giving players benefits upon consumption. 
I didn't check the equipment category because I didn't think it would be there since equipment has gear and similar items. It didn't fit my description of equipment (which I recognise is a user issue rather than a game issue).

**Comment by Regalis11** [comment] 2023-03-02 15:46
Okay, thanks for the clarification! I wasn't sure if you meant that they weren't listed in any of the categories. Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/249a2cf

**Comment by Rokvach** [comment] 2023-04-04 14:26
Tested, working correctly. Closing.

**Closed by Rokvach** 2023-04-04 14:26 UTC
Labels: Bug
