### ISSUE TITLE
Editing output fields of multiple electrical items crashes game.

### ISSUE THREAD

**Issue by soeinfach** [Regalis11/Barotrauma#9570] opened 2022-07-14 20:52 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When I attempt to edit the stats of multiple items, the game crashes since the last update to v0.18.15.0 (Anniversary fix, Linux version). A similar issue was reported recently, but was described to only happen now and then. I've never had this problem before, since the update it happens consistently.

### Reproduction steps

1. Open the editor and place three greater components.
2. Select all items and enter a custom value in the output field.

### Bug prevalence

Happens every time I play

### Version

Other

### -

0.18.15.0

### Which operating system did you encounter this bug on?

Linux

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 14.07.2022 22:09:39)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


AEDAA4108E89C50919DE68958C747E35


Game version 0.18.15.0 (ReleaseLinux, branch release, revision a7b22109e9)
Graphics mode: 1680x1050 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla
Level seed: no level loaded
Loaded submarine: Test (E2FAEBB92EEF8D8DD79DED149A6D2D35)
Selected screen: Barotrauma.SubEditorScreen


System info:
    Operating system: Unix 4.15.0.169 64 bit
    GPU name: 
    Display mode: {Width:1680 Height:1050 Format:Color AspectRatio:1,6}
    GPU status: Normal


Exception: Type provided must be an Enum. (Parameter 'enumType') (System.ArgumentException)
Target site: System.RuntimeType ValidateRuntimeType(System.Type)
Stack trace: 
   at System.Enum.ValidateRuntimeType(Type enumType)
   at System.Enum.TryParse(Type enumType, String value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at Barotrauma.SerializableEntityEditor.MultiSetProperties(SerializableProperty property, Object parentObject, Object value) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Serialization/SerializableEntityEditor.cs:line 1451
   at Barotrauma.SerializableEntityEditor.SetPropertyValue(SerializableProperty property, Object entity, Object value) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Serialization/SerializableEntityEditor.cs:line 1351
   at Barotrauma.SerializableEntityEditor.<>c__DisplayClass29_0.<CreateStringField>g__OnApply|3(GUITextBox textBox) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Serialization/SerializableEntityEditor.cs:line 707
   at Barotrauma.SerializableEntityEditor.<>c__DisplayClass29_0.<CreateStringField>b__6(GUITextBox box, String text) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Serialization/SerializableEntityEditor.cs:line 692
   at Barotrauma.GUITextBox.Update(Single deltaTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GUI/GUITextBox.cs:line 477
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GUI/GUI.cs:line 1167
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 898
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/SDL/SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 59
```

**Comment by soeinfach** [comment] 2022-07-14 21:41
Edit: Specifically, editing the output/false output fields of electrical components triggers this, also editing text fields for displays and labels when selecting multiple ones.

**Comment by Regalis11** [comment] 2022-07-15 07:02
Duplicate of https://github.com/Regalis11/Barotrauma/issues/9512

**Closed by Regalis11** 2022-07-15 07:02 UTC
