### ISSUE TITLE
Bots - Doesn't use knife after stun baton runs out of battery

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3694] opened 2020-09-03 11:43 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots usually tries to knife targets after they're stunned. Once the battery runs out, they're stuck clobbering target with the weak stun baton instead of knife.

**Version**
0.10.4~0.10.501

**Comment by ekqvist** [comment] 2020-09-10 07:50
Here are the full steps to reproduce the issue:

1. Give a bot a stun baton and a diving knife
2. Order the bot to fight intruders
3. Spawn a husk on the sub
4. Watch the bot stun the husk and then switch to the knife to kill the stunned husk
5. Take the battery out of the baton or make sure there's no charge left in the contained battery
6. Spawn another husk on the sub
7. Watch as the bot keeps on hitting the husk with the baton instead of switching to the knife for better damage

The priority of the stun baton wasn't correctly reduced when there's no charge left. This should be fixed in Regalis11/Barotrauma-development@2e71dde. After the fix, bots should immediately switch to the knife if there's no charge left in their stun baton battery.

**Comment by Rokvach** [comment] 2020-09-10 09:04
I tested this by turning on character godmode and attacking a NPC on the outpost and waited for the guards to attack me, once they used all of their charge in the batons they switched to knifes, so working as intended, closing.

**Closed by Rokvach** 2020-09-10 09:04 UTC
Labels: Bug, Code
