### ISSUE TITLE
Alt Tabbing on fullscreen keeps game minimized

### ISSUE THREAD

**Issue by MiggyGZA** [Regalis11/Barotrauma#11678] opened 2023-03-27 16:37 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While fullscreen in a lobby or in-game, alt tabbing and trying to reopen the game does not work - requires many many clicks to reopen the game

### Reproduction steps

1: Set game to fullscreen
2: Create a lobby, or enter a game
3: Alt-Tab out of game
4: issue

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-03-28 16:20
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3584

**Closed by Regalis11** 2023-03-28 16:20 UTC
Labels: Needs testing
