### ISSUE TITLE
swapping items with worn equipment bug

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6310] opened 2021-07-14 15:38 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
swapping an item from a cabinet to the player's worn equipment slots has the item fall to the ground instead of being worn

**Steps To Reproduce**
0. multiplayer
1. swap an item in a cabinet with the player's head slot

**Version**
0.14.6.0

**Additional information**
perhaps similar to #6037 

https://user-images.githubusercontent.com/5103517/125650544-eebac6d3-c252-4eb7-9250-4496c28b3216.mp4

**Comment by Regalis11** [comment] 2021-07-15 09:21
I'm afraid I could not reproduce this:

https://user-images.githubusercontent.com/14351070/125763762-46f04d3e-6615-4613-aeda-06ca50f552e4.mp4

Which submarine is that clip from? I wonder if it could have something to do with the way those secure cabinets have been configured.

**Comment by Tsunder** [comment] 2021-07-15 16:52
this was on the Forsaken, not on the workshop (yet) afaik, i'll try to replicate it/grab the sub

the cabinet in question was placed on the ceiling and rotated 90 degrees. (roughly the position of the yellow emergency lights)

**Comment by Tsunder** [comment] 2021-07-15 16:59
got the sub, attached.
- did not happen in test mode
- happened in multiplayer
- didn't test single player
[Forsaken.zip](https://github.com/Regalis11/Barotrauma/files/6824947/Forsaken.zip)

**Comment by Regalis11** [comment] 2021-07-19 13:32
Thank you, managed to repro and fix it now! It seems the issue had to do with the cabinet being so far above the player: 

https://github.com/Regalis11/Barotrauma-development/commit/060383b4d16aaf80232dd4217a2ef3a2ca11efc1
> Happened because the item got first dropped from the container, and when the server tried to move it to the client's inventory, it was sometimes too far to interact with (as the distance was measured to the item, not the container).

**Comment by Rokvach** [comment] 2021-07-27 07:59
Tested, I wasn't able to reproduce the issue. Seems to be working correctly. Closing.

**Closed by Rokvach** 2021-07-27 07:59 UTC
Labels: Bug, Code, Networking
