### ISSUE TITLE
Could not start campaign on dedicated server.

### ISSUE THREAD

**Issue by DutchChrisis** [Regalis11/Barotrauma#9166] opened 2022-05-18 22:05 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Coroutine Barotrauma.Networking.GameClient+<StartGame>d__97 threw an exception: Attempted to start a campaign round when a campaign was not active.
at Barotrauma.Networking.GameClient.StartGame(IReadMessage inc)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 0
at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 197
at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 255Coroutine Barotrauma.Networking.GameClient+<StartGame>d__97 threw an exception: Attempted to start a campaign round when a campaign was not active.
at Barotrauma.Networking.GameClient.StartGame(IReadMessage inc)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 0
at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 197
at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 255

Im no programmer and i did every step on the wiki to set the server and config files up like they should ( i hope)
The server booted up correctly i clicked on campaign and then start until i got this report.

### Bug prevalence

Happens every time I play

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-05-19 13:46
Thank you for the report!

I'm afraid I can't think off the top of my head what could be causing this. Could you give some more details on how exactly this happens (the reproduction steps): are you hosting directly from the game or using the dedicated server executable? If the latter, do you see any errors in the server window? What kind of mods are you using? By clicking on campaign, do you mean you selected "campaign" from the game mode list or that you actually tried to start the campaign with the "new game" button?

**Comment by DutchChrisis** [comment] 2022-05-20 18:15
This was what i think mostly a loop from the Dedicated server exe window. As far as i know the server had no mods yet. I also have a screenshot included from the client who joined that server and got that error as shown.

Generating an outpost for the start of the level... (Location: Erlangshen Outpost, level type: LocationConnection)
Generating an outpost for the end of the level... (Location type: LocationType (Abandoned), level type: LocationConnection)
WARNING: Entity events have been created during level generation. Events should not be created until the round is fully initialized.
Coroutine Barotrauma.Networking.GameServer+<StartGame>d__84 threw an exception: Object reference not set to an instance of an object.
   at Barotrauma.CampaignMode.AddExtraMissions(LevelData levelData) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameModes\CampaignMode.cs:line 366
   at Barotrauma.GameSession.InitializeLevel(Level level) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 578
   at Barotrauma.GameSession.StartRound(LevelData levelData, Boolean mirrorLevel, SubmarineInfo startOutpost, SubmarineInfo endOutpost) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 439
   at Barotrauma.GameSession.StartRound(String levelSeed, Nullable`1 difficulty, LevelGenerationParams levelGenerationParams) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 357
   at Barotrauma.Networking.GameServer.StartGame(SubmarineInfo selectedSub, SubmarineInfo selectedShuttle, GameModePreset selectedMode, CampaignSettings settings)+MoveNext() in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Networking\GameServer.cs:line 2161
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 197
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 255
Failed to initiate file transfer (file "" not found).
   at System.Environment.get_StackTrace()
   at Barotrauma.Networking.FileSender.StartTransfer(NetworkConnection recipient, FileTransferType fileType, String filePath) in E:\Barotrauma-development\Barotrauma\BarotraumaServer\ServerSource\Networking\FileTransfer\FileSender.cs:line 152
   at Barotrauma.Networking.GameServer.ClientWrite(Client c) in E:\Barotrauma-development\Barotrauma\BarotraumaServer\ServerSource\Networking\GameServer.cs:line 1564
   at Barotrauma.Networking.GameServer.Update(Single deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaServer\ServerSource\Networking\GameServer.cs:line 597
   at Barotrauma.GameMain.Run() in E:\Barotrauma-development\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 329
   at Barotrauma.Program.Main(String[] args) in E:\Barotrauma-development\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 75
Failed to initiate file transfer (file "" not found).
   at System.Environment.get_StackTrace()
   at Barotrauma.Networking.FileSender.StartTransfer(NetworkConnection recipient, FileTransferType fileType, String filePath) in E:\Barotrauma-development\Barotrauma\BarotraumaServer\ServerSource\Networking\FileTransfer\FileSender.cs:line 152
   at Barotrauma.Networking.GameServer.ClientWrite(Client c) in E:\Barotrauma-development\Barotrauma\BarotraumaServer\ServerSource\Networking\GameServer.cs:line 1564
   at Barotrauma.Networking.GameServer.Update(Single deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaServer\ServerSource\Networking\GameServer.cs:line 597
   at Barotrauma.GameMain.Run() in E:\Barotrauma-development\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 329
   at Barotrauma.Program.Main(String[] args) in E:\Barotrauma-development\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 75
WARNING: Running slowly (54 updates/s)!
![Error Baro](https://user-images.githubusercontent.com/105824356/169588422-353e3ca4-e6dc-4695-80a5-b8be511c054e.png)

**Comment by DutchChrisis** [comment] 2022-05-20 18:17
sidenote: The client could not click start or select anything so the campaign could only be started by me and not anybody else.

**Comment by Regalis11** [comment] 2022-06-29 08:36
Addressed the issue @NilanthAnimosus described in https://github.com/Regalis11/Barotrauma-development/commit/43ce23b9d31347b989e5b5ceb543049cd8f35560. I'm not sure if that was what caused the initial issue either, but it seems likely.

> Additionally noticed later: Appears the server can be started with GameModeIdentifier="multiplayercampaign" without any preset set (That is having serversettings PresetName="")

As for this, it's not a bug: the `PresetName` attribute in the `CampaignSettings` element in `serversettings.xml` is actually the name of the campaign settings preset (i.e. easy/normal/hard), and leaving it empty should not cause any issues (it'll just use the settings explicitly defined in the `CampaignSettings` element instead of a preset).

**Comment by NilanthAnimosus** [comment] 2022-07-26 07:24
Tested in 0.19.0.0 - working correctly, closing.

**Closed by NilanthAnimosus** 2022-07-26 07:24 UTC
Labels: Bug, Code, Networking, Unstable
