### ISSUE TITLE
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.

### ISSUE THREAD

**Issue by dogunbound** [Regalis11/Barotrauma#9063] opened 2022-05-04 02:49 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
```[dogunbound@DogBigRig Barotrauma]$ ./Barotrauma
[S_API] SteamAPI_Init(): Loaded '/home/dogunbound/.local/share/Steam/linux64/steamclient.so' OK.
Setting breakpad minidump AppID = 602960
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198118637081 [API loaded no]
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CompareInfo..cctor()
   at System.String.StartsWith(System.String, System.StringComparison)
   at Barotrauma.Steam.SteamManager.SteamIDStringToUInt64(System.String)
   at Barotrauma.Steam.SteamManager.SteamIDUInt64ToString(UInt64)
   at Barotrauma.Steam.SteamManager.InitializeProjectSpecific()
   at Barotrauma.Steam.SteamManager.Initialize()
   at Barotrauma.Program.Main(System.String[])
Aborted (core dumped)
```

**Steps To Reproduce**
launch game from staem on linux

**Version**
I don't know the game version since I downloaded it from steam

System info:
```[dogunbound@DogBigRig ~]$ neofetch
                   -`                    dogunbound@DogBigRig 
                  .o+`                   -------------------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Kernel: 5.17.5-zen1-1-zen 
               `+oooooo:                 Uptime: 1 day, 7 hours, 19 mins 
               -+oooooo+:                Packages: 943 (pacman) 
             `/:-:++oooo+:               Shell: bash 5.1.16 
            `/++++/+++++++:              Resolution: 2560x1440 
           `/++++++++++++++:             DE: Plasma 5.24.5 
          `/+++ooooooooooooo/`           WM: KWin 
         ./ooosssso++osssssso+`          Theme: [Plasma], Breeze [GTK2/3] 
        .oossssso-````/ossssss+`         Icons: [Plasma], Papirus-Dark [GTK2/3] 
       -osssssso.      :ssssssso.        Terminal: konsole 
      :osssssss/        osssso+++.       Terminal Font: Source Code Pro 10 
     /ossssssss/        +ssssooo/-       CPU: 12th Gen Intel i7-12700K (20) @ 5.000GHz 
   `/ossssso+/:-        -:/+osssso+-     GPU: NVIDIA GeForce GTX 1060 6GB 
  `+sso+:-`                 `.-/+oso:    Memory: 8068MiB / 31837MiB 
 `++:.                           `-/+/
 .`                                 `/                           
                                                                 


[dogunbound@DogBigRig ~]$ 
```
```[dogunbound@DogBigRig ~]$ steam --version
steam.sh[102012]: Running Steam on arch rolling 64-bit
steam.sh[102012]: STEAM_RUNTIME is enabled automatically
setup.sh[102086]: Steam runtime environment up-to-date!
steam.sh[102012]: Steam client's requirements are satisfied```

**Additional information**
Current workaround:
add this line to your .bashrc and launch the game from the terminal:
`export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1`

**Comment by EgorIII** [comment] 2022-05-04 05:16
duplicate of https://github.com/Regalis11/Barotrauma/issues/8858
if you dont want to read that, you can still launch linux native but without steam overlay:
`export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1 && ~/.local/share/Steam/steamapps/common/Barotrauma/Barotrauma &`

**Closed** 2022-05-04 06:00 UTC

**Comment by AtFreezingPoint** [comment] 2022-05-09 02:11
Same setup, same issue.
