### ISSUE TITLE
Grenade explosive animation plays twice

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2186] opened 2020-02-06 22:20 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you throw a grenade, pick it up before it explodes, and throw it again, the animation plays twice after a short delay inbetween both. Only the first one deals damage/status

**Version**
0.9.703

**Comment by Regalis11** [comment] 2020-02-07 10:26
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2a0a0a0e211954c5c34535fb5935a32458dec1b0

**Comment by Rokvach** [comment] 2020-02-08 11:58
Grenades doesn't always cause a explosion when thrown now, tested in multiplayer.

Repro: 

- Just toss around grenades and see if there is an effect or not

**Comment by Rokvach** [comment] 2020-02-08 12:01
Also should EMP grenades disappear after usage? @Regalis11

**Comment by Regalis11** [comment] 2020-02-08 12:52
Should be fixed now https://github.com/Regalis11/Barotrauma-development/commit/059face00da288f55b2b23028f3840894ce2ef3e. I also made EMP grenades disappear after they explode.

**Comment by Rokvach** [comment] 2020-02-09 20:24
A grenade thrown twice does double the damage and gives double the afflictions than a grenade thrown once @Regalis11

**Comment by Regalis11** [comment] 2020-02-09 21:07
Wasn't able to repro (tested with frag grenades in both single player and multiplayer). Frag grenades seem to take about 90% of the character's health when detonated directly at the character's feet, regardless if they're thrown once or twice. 

The damage depends on your distance from the explosion (applied separately to each limb, so an explosion near your head generally does more damage than one near your legs), so could it be that the results you got were caused by differences in distance from the grenade?

**Comment by Rokvach** [comment] 2020-02-09 21:36
I tested based on wall damage, throwing the same grenade twice caused a lot more wall damage than throwing the grenade once. The affliction part I estimated by looking the amount of damage it did to bots who were near it and how many afflictions it added to my characters limbs. When thrown once the bots health bar dropped to half a health, while when thrown twice anyone near the grenade died.

**Comment by Regalis11** [comment] 2020-02-09 23:27
Did some more testing, and I thought I got it to happen the other way around (throwing once completely blasted through the floor, and then throwing twice in the exact same spot barely damaged the floor). After a bit more testing I noticed the first big explosion was caused by a ton of oxygen and welding fuel tanks around the grenade. I wonder if that could've been what happened in your case too?

**Comment by Rokvach** [comment] 2020-02-10 07:43
I forgot take oxy tanks in to consideration.. I was tossing the grenades in front of Dugongs diving suit cabinets so of course the results would be different depending where the grenade landed :D

So there might not be an issue after all

**Comment by Rokvach** [comment] 2020-02-11 04:38
No issues,  closing.

**Closed by Rokvach** 2020-02-11 04:38 UTC
Labels: Bug, Code
