### ISSUE TITLE
Helm skill does not boost engines if not directly connected to engine.

### ISSUE THREAD

**Issue by BlackMoons** [Regalis11/Barotrauma#8517] opened 2022-03-13 01:31 UTC
Helm skill does not boost engine output (Horizontal speed) if there is any logic between the helm unit and the engine.

**Comment by Regalis11** [comment] 2022-03-15 13:03
Thank you for the report! Which game version did this happen in, and which components did you try specifically? I couldn't reproduce this with relays in v0.17.0.0

**Comment by Regalis11** [comment] 2022-03-16 13:36
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/268072f4b4ceb97d07ea81acb7ec455e77a3aae9

**Comment by Rokvach** [comment] 2022-04-13 11:11
Tested, working correctly. Closing.

**Closed by Rokvach** 2022-04-13 11:11 UTC
Labels: Bug, Code
