### ISSUE TITLE
Dialogue is bugged. Unable to end dialogue

### ISSUE THREAD

**Issue by Freelor** [Regalis11/Barotrauma#10367] opened 2022-11-13 02:20 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I am using the unstable branch, started a new game and during the first dialogue tutorial i cant't get it to close out after finishing the dialogue. It loops back to saying the same thing again. I also tried skipping the tutorial and the moment talked to someone the same thing happened

### Reproduction steps

Start a new game with tutorial enabled.
Wait for tutorial dialogue to start. 
Click through dialogue
Watch as it opens the same dialoge in loop

Start game without tutorial
Go to a port where a quest giver or npc automatically speaks to the player
Dialogue does the same loop

### Bug prevalence

Happens every time I play

### Version

0.20.5.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
NA
```

**Comment by Razatop** [comment] 2022-11-13 06:30
Yuppers same here.

**Comment by Feldoe16** [comment] 2022-11-13 10:10
Same for me but if you save and quit after the first round of dialogue you can get out of it. BUT then you cant complete the first tutorial because you are supposed to just buy one fuel rod and welding fuel. All other tutorials until the final tutorial dialogue function properly maybe except to give your crew the order to operate a turret. (Only resolves when you give the Captain that order). The final dialogue again is bugged same as the first dialogue but even here you can save and quit and then resolve the dialogue.

**Comment by Regalis11** [comment] 2022-11-13 10:55
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10320

**Closed by Regalis11** 2022-11-13 10:55 UTC
