### ISSUE TITLE
Corrupted save file after shuttle and drone "rebuy"

### ISSUE THREAD

**Issue by Centorios** [Regalis11/Barotrauma#7629] opened 2021-12-05 04:12 UTC
**Description**
Our multiplayer campaign got corrupted after buying the shuttle and drone "repair", after launching the mission the game crashes for all the member in the lobby

**Steps To Reproduce**
lose your shuttle &/or drone and buy it again from the maintenance vendor

**Version**
Windows 10 20H3 (compilation 19042.1348)

**Game related data**
Game version 0.15.13.0 (ReleaseWindows, branch release, revision 4e66dd7b5d)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: Corick LineaPelagon Linea

**Additional information**
I solved this decompressing the campaign save with the decompressor and going to the submarine editor.
It seems that both the drone and the shuttle were position defaulted to the center of the submarine instead of their corresponding hatches, causing some kind of physics collision crash.
The problem got solved after i moved both things to their correct position and attaching them correctly.
After that i replaced the sub file in the decompressed campaign,then compressed everything back (problem solved)
(there was no relevant information inside the logs)
![image](https://user-images.githubusercontent.com/69221552/144733009-de307d59-2cef-46d8-86b0-8b3ad00fc74b.png)

**Comment by Ek-Videogames** [comment] 2021-12-05 11:43
I recall having a similar issue, almost like if a sub with multiple shuttles 'abandons' one and then some time later purchases it back - sometimes the game does not seem to know what docking port it used to be assigned to.

**Comment by Regalis11** [comment] 2021-12-07 11:56
I'm afraid I couldn't reproduce this with the vanilla subs. Do you still happen to have any of the crash reports available, or the save file where this occurred?

**Comment by Centorios** [comment] 2021-12-07 18:58
The save file was edited, i can attach the crash reports but i didnt find anything valuable.
I can try to reproduce it and then attach the new corrupted save file
What do you mean by vanilla subs..? every "vanilla" sub in the list or just labeled by the tag 0.9 Vanilla
because we were using piraña mark 2 shuttle (which is labeled as vanilla) but i dont have the workshop mod installed, a frined of mine just shared the .sub file and everything worked fine
[ServerLogs.zip](https://github.com/Regalis11/Barotrauma/files/7670870/ServerLogs.zip)

**Comment by Centorios** [comment] 2021-12-07 19:02
forgot to mention that we are using a vanilla modified version of the R-29

**Comment by Centorios** [comment] 2021-12-07 19:32
i tried replicating the bug but it didn't work, sadly i had to do it copying the working savefile because i cant return when the save was bugged (i didn't download the shuttle workshop file either to be more accurate)
[ServerLogs&savefile.zip](https://github.com/Regalis11/Barotrauma/files/7671084/ServerLogs.savefile.zip)

**Comment by Centorios** [comment] 2021-12-07 19:35
![shuttle](https://user-images.githubusercontent.com/69221552/145094331-85128979-9911-4e9f-8011-ddb17da21c69.png)
![drone](https://user-images.githubusercontent.com/69221552/145094336-c7411c56-771b-433f-b31d-03a352bf5d27.png)
Im trying to be as helpful as possible, maybe I screwed up fixing it by myself :S

**Comment by Centorios** [comment] 2021-12-07 19:36
[Cachalote 2.0.zip](https://github.com/Regalis11/Barotrauma/files/7671128/Cachalote.2.0.zip)
sub file (copied from the save file)

**Comment by Regalis11** [comment] 2022-05-02 08:52
No known steps to repro, closing

**Closed by Regalis11** 2022-05-02 08:52 UTC
Labels: Bug, Need more info, Code, Crash
