### ISSUE TITLE
[Unstable] Terminal's signal_in does not work.

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#7423] opened 2021-11-20 20:50 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Signals inputted with the signal_in pin of the Terminal do not appear on the terminal window.

**Steps To Reproduce**
1. Wire a button to the signal_in pin of the terminal.
2. Press the button, and view the terminal window.
3. View the terminal window.

**Version**
Windows v0.15.15.0

**Additional information**
Video demonstration:
https://user-images.githubusercontent.com/67431770/142740552-f779fd07-4234-4c76-a2e8-4a16471b2c7d.mp4

**Comment by MaaiG** [comment] 2021-11-20 23:07
v0.15.13.0 -  It was working fine.

**Comment by Jade-Harleyy** [comment] 2021-11-21 00:15
After further testing, it appears the signal_out pin is nonfunctional as well.

**Comment by Regalis11** [comment] 2021-11-21 13:52
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7388

**Closed by Regalis11** 2021-11-21 13:52 UTC
