### ISSUE TITLE
Barotrauma Client crash report (generated on 03/29/2023 14:47:34) 

### ISSUE THREAD

**Issue by IfromTurkey55** [Regalis11/Barotrauma#11694] opened 2023-03-29 11:53 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

ı cant use the fabricator again :(

### Reproduction steps

[crashreport (30).log](https://github.com/Regalis11/Barotrauma/files/11100468/crashreport.30.log)

### Bug prevalence

Happens regularly

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
ı send this issiue before and its was fixed but its happend again :(
```

**Comment by Regalis11** [comment] 2023-03-29 11:57
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11657. As mentioned in the previous report, you're missing a mod that's required by one of the mods you have installed.

> "M10 All-In-Pack + EuropaWaifu++ Patch" depends on a package with name or ID "M10" that is not currently installed.

**Closed by Regalis11** 2023-03-29 11:57 UTC

**Comment by IfromTurkey55** [comment] 2023-03-29 11:58
Thx my comrade but… which mod ı need to downland?
Windows için Posta<https://go.microsoft.com/fwlink/?LinkId=550986> ile gönderildi

Kimden: Joonas ***@***.***>
Gönderilme: 29 Mart 2023 Çarşamba 14:57
Kime: ***@***.***>
Bilgi: ***@***.***>; ***@***.***>
Konu: Re: [Regalis11/Barotrauma] Barotrauma Client crash report (generated on 03/29/2023 14:47:34) (Issue #11694)


Duplicate of #11657<https://github.com/Regalis11/Barotrauma/issues/11657>. As mentioned in the previous report, you're missing a mod that's required by one of the mods you have installed.

"M10 All-In-Pack + EuropaWaifu++ Patch" depends on a package with name or ID "M10" that is not currently installed.
