### ISSUE TITLE
Can't pick back up artifact after dropping it

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#2449] opened 2020-03-17 05:50 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Steps To Reproduce**
Drop the artifact in multiplayer and you can't pick it up again

**Version**
Windows 0.9.7.1

**Additional information**
https://streamable.com/isx58

**Comment by Kaillera** [comment] 2020-03-17 09:22
Location desync. The artifact is actually somewhere else, and you need to pick up the false artifact and bring it to the true location before it stays in your hand.

**Comment by thegrb93** [comment] 2020-03-17 14:45
Shouldn't the server transmit the true location after forcing it out of my hands? I've seen this issue happen for other items as well, but the artifact it seems the artifact gets it the worst.

**Comment by Regalis11** [comment] 2020-03-18 07:46
Duplicate of #2177

**Closed by Regalis11** 2020-03-18 07:46 UTC

**Comment by thegrb93** [comment] 2020-05-01 04:35
I'm getting reports of this occurring again for artifacts in 0.9.9.1
