### ISSUE TITLE
MP sync of Battery Charge Rates

### ISSUE THREAD

**Issue by Eskandaer** [Regalis11/Barotrauma#2489] opened 2020-03-26 07:11 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Battery charge rates adjusted through signals/wiring seem to have desync issues in multiplayer.  Rates do not appear the same across each client -- takes 15-30 seconds to catch up between clients.

**Steps To Reproduce**
Place battery with wiring that carry signals to change battery charge rate.  In multiplayer with two clients, have one client change charge rate through wiring; other client will likely not see the change in rate for a while.

**Version**
9.7.x
Windows 10

**Additional information**

**Comment by Regalis11** [comment] 2020-11-09 18:54
I'd suspect this was caused by the same bug as #2894: when a client connected the 2nd end of a wire to a device other than a junction box, it would sometimes not register server-side, which could cause symptoms like this.

Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/0059175a6b264fa17ed31e59db653b52c5b45e0d

**Comment by Rokvach** [comment] 2020-11-10 12:03
No issues, closing.

**Closed by Rokvach** 2020-11-10 12:03 UTC
Labels: Bug, Code, Networking
