### ISSUE TITLE
Multiplayer - Wifi signal still gets sent to item even though wire is unplugged from the item.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3742] opened 2020-09-06 23:08 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Wifi signal still gets sent to item even though wire is unplugged from the item in multiplayer.

**Steps To Reproduce**
Use Kastrul in Multiplayer.
Use the Shuttle Terminal and thrust engine/adjust ballast of Kastrul Drone.
Go into the Kastrul Drone.
Unhook the Engine and/or Ballast set force/target level wire.
Try to manually set the thrust/pump speed. For some reasons the wifi signal will still keep overriding them.

**Version**
0.10.4

**Comment by Kaillera** [comment] 2020-09-07 01:46
Actually it seems navigation terminal velocity y signal also aren't disabled completely when you unhook the wire in multiplayer.

**Comment by Regalis11** [comment] 2020-09-07 06:42
I wasn't able to reproduce this. When the engine/pump is in this "desynced" state, do you see the wire being disconnected client-side and is the "automatic control" light on?

**Comment by Kaillera** [comment] 2020-09-07 10:36
[2020-09-07 06-34-52.zip](https://github.com/Regalis11/Barotrauma/files/5182607/2020-09-07.06-34-52.zip)

Here you go.

**Comment by Regalis11** [comment] 2020-09-14 13:15
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3816. Closing this older ticket instead because the newer one has more detailed info and steps to repro.

**Closed by Regalis11** 2020-09-14 13:15 UTC
Labels: Bug, Code, Need more info, Networking
