### ISSUE TITLE
Submarine file corrupted

### ISSUE THREAD

**Issue by Edstar206** [Regalis11/Barotrauma#11751] opened 2023-04-04 22:59 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Started off on my first very own submarine project... After loading it up and doing a little more work I got a warning for an object that was far away from the submarine. This turned out to be a door that somehow bugged into existense a long way away from the submarine. It was somehow impossible to delete.

I gave up after several attempts and saved anyway thinking I'd fix it later, this turned out to be a mistake as the save file is now corrupted. The next day after trying and
 failing to load it I somehow got a soft crash which then immediately made the log show up. (note that on the logs loading the sub isn't the last action)

I really hope to continue work on this thing... I wasn't lacking in ambition and the submarine is quite large, spanning almost nine decks on the front. Can you help me somehow uncorrupt the file? Thanks in advance.
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/11153815/crashreport.log)
I can't send the .sub file here or publish it in the workshop, let me know and I'll send it by mail.

### Reproduction steps

Honestly no idea why that undeletable door showed up, though I know random weird spawns when using copy-paste is a thing?

### Bug prevalence

Just once

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Edstar206** [comment] 2023-04-04 23:05
Update: after searching more on this I of course stumble on that same issue in another tread.
#10591
This thread also mentions using a .zip file so here for the sub so here it is
[EdstarSub.zip](https://github.com/Regalis11/Barotrauma/files/11153850/EdstarSub.zip)

**Comment by Regalis11** [comment] 2023-04-05 11:44
Thank you for the report! It does seem like this is the same bug as #10591.

I removed the item with the duplicate identifier from the submarine file so you can continue working on it: 
[ProjectTwo.zip](https://github.com/Regalis11/Barotrauma/files/11158271/ProjectTwo.zip)

Sorry for the inconvenience! I'll close this ticket as a duplicate of #10591 and continue working on the issue on that older ticket.

**Closed by Regalis11** 2023-04-05 11:44 UTC
Labels: Bug, Code

**Comment by Edstar206** [comment] 2023-04-05 19:57
Would like to mention that both in private and professional life this is the best triple A service I've ever had on already an excellent game!

I've tested the file and everything seems to work just fine now, thank you so much for getting back to me on such short notice.
