### ISSUE TITLE
[unstable 0.17.8.0] Main sub position is briefly displayed incorrectly on the respawn shuttle

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#8777] opened 2022-04-11 08:17 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
On the respawn shuttle, the nav terminal displayed an incorrect position of the main sub for a while

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
0.17.8.0

**Additional information**
happened on official test server

https://user-images.githubusercontent.com/5103517/162694322-c730b46e-5074-4dd8-b72d-e3bcdb754e9b.mp4

**Comment by ekqvist** [comment] 2022-04-14 10:03
Thanks for the report! Unfortunately, I tried reproducing it several times in different games modes using different settings, but I was unable to reproduce the issue.

Have you encountered this issue consistently? Are there any other steps that could help reproduce the issue?

**Comment by Tsunder** [comment] 2022-04-14 14:48
i've only spawned in shuttle on the test server once, so IDK.

the circumstance it seems the main sub just did a beacon station, and this was first time I joined the server (first character/first time spawning).

**Comment by ekqvist** [comment] 2022-06-06 11:02
Still been unable to reproduce the issue. Even joining the server later with another client once the sub is away from the start position. The sub still seems to be immediately displayed where it is.

**Comment by Regalis11** [comment] 2022-09-07 07:22
No known steps to repro, closing

**Closed by Regalis11** 2022-09-07 07:22 UTC
Labels: Bug, Need more info, Code, Networking
