### ISSUE TITLE
Scaled coilguns have their barrel offset wrong, but only if they're at 0 degrees rotation

### ISSUE THREAD

**Issue by GophTheGreat** [Regalis11/Barotrauma#3888] opened 2020-09-23 04:48 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Shrinking or enlarging a coilgun causes its barrel to no longer line up with its body properly. The effect is further pronounced the further from default you scale the guns. This effect is remedied by permanently changing the rotation to at least 1. If you were to set the rotation to 1 temporarily the barrels will align, but the alignment will not persist between save/loads of the ship if the rotation is subsequently set back to 0.

**Steps To Reproduce**
1. Make coilgun
2. Shrink coilgun to 0.4 or enlarge to 0.6
3. What the fuck?

**Version**
0.10.5.0

**Additional information**
https://i.imgur.com/eCVg8fv.png

I am currently working around  this by setting my guns to 360 rotation. 

![image](https://user-images.githubusercontent.com/13459026/93968023-3d65ce00-fd04-11ea-8522-104074ddbab3.png)

**Comment by Regalis11** [comment] 2020-09-23 07:17
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3764

**Closed by Regalis11** 2020-09-23 07:17 UTC
