### ISSUE TITLE
[0.11.0.9] Loose wires at the end of round disappears from end connection point.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4408] opened 2020-11-30 00:33 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Loose power wires at the end of round disappears from end connection point. The beginning point will still be attached to whatever it was.

**Steps To Reproduce**
1. Start Campaign.
2. Unwire a wire during a level.
3. Enter an outpost with the wire loose.
4. Look at object wire. Wire should no longer be connected to it.
5. Look at where it was connected to for the loose wire.

**Version**
~0.11.0.9

**Comment by Regalis11** [comment] 2020-12-08 10:25
I'm afraid I wasn't able to reproduce this. Tested by unwiring a bunch of things in vanilla subs: lamps, electrical components, pumps, but couldn't get the loose wires to disappear.

![image](https://user-images.githubusercontent.com/14351070/101471741-5586da00-3950-11eb-98ef-9a3698fc34a7.png)

Is there some specific submarine and device where you can get this to happen consistently?

**Comment by Kaillera** [comment] 2020-12-08 18:41
Updated Ticket

This turns out to be a problem caused by Ballast Flora.

**Comment by Regalis11** [comment] 2020-12-09 10:32
Still no luck I'm afraid. Tested by doing the following:
1. Infect humpack's right ballast pump
2. Let the ballast flora grow until it bursts out from the walls
3. Unwire the pump's power wire
4. Destroy the ballast flora
5. Enter the next level: the wiring still seems to be correct

Is there some specific submarine and device where you can get this to happen consistently?

**Comment by Kaillera** [comment] 2020-12-09 20:34
I did it on the Humpback in Singleplayer:
https://youtu.be/VeYthRsaUF0

**Comment by Kaillera** [comment] 2020-12-11 09:43
Turns out not ballast flora related. I had it happened on electrical components I unwired temporarily for a round.

**Comment by JJRcop** [comment] 2020-12-13 05:53
In a round I had unwired lights to save power since we were low on fuel, and left the wires dangling on the junction boxes. When we got back and the sub got saved then loaded again, the wires were still there on the junction boxes, but you could not connect them back to power.

They would actually stay there permanently even if you took them out on the other end

**Comment by Regalis11** [comment] 2020-12-18 09:43
Unfortunately I still couldn't get this to happen. :/ I tried following the exact steps in the video and disconnecting wires in a bunch of different items, but no luck.

I'll keep an eye out for this and see if I run into it. And if anyone has a save file where this occurs, it could be of some use in diagnosing the problem (assuming the issue happens when the game is trying to load the disconnected wires, not when it's saving them).

**Comment by mrjpjr** [comment] 2021-01-20 12:53
Still occurs in 12.0.3

**Description**
https://streamable.com/8hkjya

**Additional Info**
Save file of sub in video:
[Unhooking (wiring) bug SP save.zip](https://github.com/Regalis11/Barotrauma/files/5842497/Unhooking.wiring.bug.SP.save.zip)

**Steps I took**
Unhook wire from hatch pin (wire comes from a component)
Start new round

**Comment by Kaillera** [comment] 2021-01-20 15:10
Unwire during non outpost level and then transition to a new level.

**Comment by mrjpjr** [comment] 2021-01-20 15:54
I unwired at an Outpost, then transitioned to a mission level.

**Comment by Rokvach** [comment] 2021-01-21 13:42
Still an issue, moving to misc todo

**Comment by Regalis11** [comment] 2021-01-21 14:27
Hmm, I must still be doing something wrong because I still couldn't get this to happen. I downloaded the provided save file and did the following:
1. Disconnected the wire from the hatch's "toggle_state" connection (is this the one I should disconnect?)
2. Docked with the outpost (Gangpo City).
3. The loose wire is still there.
4. Undocked from Gangpo (heading towards Kenneth Linea)
5. The loose wire is still there.

**Comment by Regalis11** [comment] 2021-01-21 15:06
Think I finally managed to repro and fix this (https://github.com/Regalis11/Barotrauma-development/commit/0717f3bc2ace64505c7aab6618158bdb88a00001). It's related to the ID remapping logic, and I don't think there's a reliable way to reproduce it, but the save above seems to be working correctly now.

**Comment by Rokvach** [comment] 2021-02-03 09:41
No encounters yet

**Comment by Rokvach** [comment] 2021-02-05 09:59
There hasn't been any sightings of this happening since the fix was introduced. I think this is working correctly, closing.

**Closed by Rokvach** 2021-02-05 09:59 UTC
Labels: Bug, Code, Medium Prio
