### ISSUE TITLE
Black Screen on Launch, no Solutions are Working

### ISSUE THREAD

**Issue by SomeR4ndomGuy** [Regalis11/Barotrauma#7600] opened 2021-12-04 01:30 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Game black screens right after launch. Causes both monitors to go black. The game will sometimes get to the main menu but will reach a max of 3-4 FPS.

**Steps To Reproduce**
Unknown, started after shutting down the game and my computer for the night.

**Version**
v0.15.12.0 on Windows 10.

**Additional information**
I've tried every solution I could find on the steam forums and online, nothing has worked. The game would run perfectly fine less than 24 hours before the issue started.
[crashreport (4).log](https://github.com/Regalis11/Barotrauma/files/7653094/crashreport.4.log)

**Comment by Regalis11** [comment] 2021-12-06 12:12
Duplicate of https://github.com/Regalis11/Barotrauma/issues/1833

**Closed by Regalis11** 2021-12-06 12:12 UTC
