### ISSUE TITLE
Monsters not spawning (mostly vanilla)

### ISSUE THREAD

**Issue by darkkai64** [Regalis11/Barotrauma#6144] opened 2021-06-22 02:39 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
No monsters are spawning in multiplayer most of the rounds. Some rounds have monsters, but the majority do not.

**Steps To Reproduce**
Play a multiplayer mission

**Version**
Under the ice, on Windows 10

**Additional information**
Modlist: Some custom submarines, wrecks and sonar beacons. Previous versions had no effect on monster spawn rate

**Comment by ekqvist** [comment] 2021-06-22 08:22
Duplicate of #6137

**Closed by ekqvist** 2021-06-22 08:22 UTC
