### ISSUE TITLE
Pulse beam cutting off

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5755] opened 2021-05-11 17:50 UTC
- [ yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I fire the pulse beam, i see the laser, but it cuts off between the end of the barrel to 2 meters away for a reason i am yet unable to find, it has something to do with the submarine being flooded.

**Version**
Unstable v0.1400.0.0 Windows

**Comment by Regalis11** [comment] 2021-05-12 08:53
I'm afraid I couldn't find a way to reproduce this. Tested with Dugong, with the whole submarine flooded.

Does this happen in some specific submarine?

**Comment by LePiromano** [comment] 2021-05-12 18:04
> Does this happen in some specific submarine?

Happens to me in the humpback, for some reason, mostly happens in the abyss.

**Comment by Regalis11** [comment] 2021-05-20 07:33
I still haven't been able to get this to happen, but ran into a similar issue when testing destroying ice shards with a handheld raycast weapon (https://github.com/regalis11/barotrauma/issues/5613). I suspect this was caused by the same bug, should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/f514705f43210a3100cd40650a8bba944d9c8cca

**Comment by Rokvach** [comment] 2021-05-20 12:04
I believe its related as well, closing as it should be working correctly now.

**Closed by Rokvach** 2021-05-20 12:04 UTC
Labels: Bug, Code
