### ISSUE TITLE
Game crash on start up.

### ISSUE THREAD

**Issue by gachfixo** [Regalis11/Barotrauma#8120] opened 2022-01-29 11:07 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When i try to launch the game, it doesn't even open and after roughly 30 seconds a crash report comes up,
i tried launching it as administrator too but it didn't fix it.

**Steps To Reproduce**
1.Launch the game.
**Version**
Windows, game version - v0.15.23.0

**Additional information**
Bug report-Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: System.Collections.Generic.IEnumerable`1[Barotrauma.ContentFile] GetFilesOfType(Barotrauma.ContentType, Boolean)
Stack trace: 
   at Barotrauma.GameMain.GetFilesOfType(ContentType type, Boolean searchAllContentPackages) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 659
   at Barotrauma.GameSettings.RefreshContentPackageItems(IEnumerable`1 files) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSettings.cs:line 620
   at Barotrauma.GameSettings.SelectCorePackage(ContentPackage contentPackage, Boolean forceReloadAll) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSettings.cs:line 350
   at Barotrauma.GameSettings.AutoSelectCorePackage(IEnumerable`1 toRemove) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSettings.cs:line 356
   at Barotrauma.GameSettings.SortContentPackages(Boolean refreshAll) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSettings.cs:line 473
   at Barotrauma.ContentPackage.SortContentPackages[T](Func`2 order, Boolean refreshAll, GameSettings config) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\ContentPackage.cs:line 827
   at Barotrauma.GameSettings.LoadContentPackages(XDocument doc) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSettings.cs:line 1383
   at Barotrauma.GameSettings.LoadPlayerConfigInternal() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSettings.cs:line 865
   at Barotrauma.GameSettings.LoadPlayerConfig() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSettings.cs:line 835
   at Barotrauma.GameSettings..ctor() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSettings.cs:line 785
   at Barotrauma.GameMain..ctor(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 222
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 57

Last debug messages:
(all of these loop roughly 30 times)
[29.01.2022 11:35:31] Loading texture "Content/UI/TalentsIcons1.png" failed! {Object reference not set to an instance of an object.}
   at Barotrauma.TextureLoader.FromStream(Stream stream, String path, Boolean compress, Boolean mipmap) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Utils\TextureLoader.cs:line 241
[29.01.2022 11:35:21] Loading texture "Content/UI/TalentsIcons2.png" failed! {Object reference not set to an instance of an object.}
   at Barotrauma.TextureLoader.FromStream(Stream stream, String path, Boolean compress, Boolean mipmap) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Utils\TextureLoader.cs:line 241
[29.01.2022 11:35:04] Loading texture "Content/UI/MainIconsAtlas.png" failed! {Object reference not set to an instance of an object.}
   at Barotrauma.TextureLoader.FromStream(Stream stream, String path, Boolean compress, Boolean mipmap) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Utils\TextureLoader.cs:line 208
[29.01.2022 11:35:04] Loading texture "Content/UI/CommandUIAtlas.png" failed! {Object reference not set to an instance of an object.}
   at Barotrauma.TextureLoader.FromStream(Stream stream, String path, Boolean compress, Boolean mipmap) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Utils\TextureLoader.cs:line 208
[29.01.2022 11:35:04] Loading texture "Content/UI/MainIconsAtlas.png" failed! {Object reference not set to an instance of an object.}
   at Barotrauma.TextureLoader.FromStream(Stream stream, String path, Boolean compress, Boolean mipmap) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Utils\TextureLoader.cs:line 208
[29.01.2022 11:35:03] Loading texture "Content/UI/CommandUIAtlas.png" failed! {Object reference not set to an instance of an object.}
   at Barotrauma.TextureLoader.FromStream(Stream stream, String path, Boolean compress, Boolean mipmap) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Utils\TextureLoader.cs:line 208
[29.01.2022 11:35:03] Loading texture "Content/UI/MainIconsAtlas.png" failed! {Object reference not set to an instance of an object.}
   at Barotrauma.TextureLoader.FromStream(Stream stream, String path, Boolean compress, Boolean mipmap) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Utils\TextureLoader.cs:line 208
[29.01.2022 11:35:03] Loading texture "Content/UI/CommandUIAtlas.png" failed! {Object reference not set to an instance of an object.}
   at Barotrauma.TextureLoader.FromStream(Stream stream, String path, Boolean compress, Boolean mipmap) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Utils\TextureLoader.cs:line 208
[29.01.2022 11:35:03] Loading texture "Content/UI/MainIconsAtlas.png" failed! {Object reference not set to an instance of an object.}
   at Barotrauma.TextureLoader.FromStream(Stream stream, String path, Boolean compress, Boolean mipmap) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Utils\TextureLoader.cs:line 208
[29.01.2022 11:35:03] Loading texture "Content/UI/CommandUIAtlas.png" failed! {Object reference not set to an instance of an object.}
   at Barotrauma.TextureLoader.FromStream(Stream stream, String path, Boolean compress, Boolean mipmap) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Utils\TextureLoader.cs:line 208
[29.01.2022 11:35:03] Loading texture "Content/UI/MainIconsAtlas.png" failed! {Object reference not set to an instance of an object.}
   at Barotrauma.TextureLoader.FromStream(Stream stream, String path, Boolean compress, Boolean mipmap) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Utils\TextureLoader.cs:line 208
[29.01.2022 11:35:03] Loading texture "Content/UI/CommandUIAtlas.png" failed! {Object reference not set to an instance of an object.}
   at Barotrauma.TextureLoader.FromStream(Stream stream, String path, Boolean compress, Boolean mipmap) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Utils\TextureLoader.cs:line 208
[29.01.2022 11:35:03] Loading texture "Content/UI/MainIconsAtlas.png" failed! {Object reference not set to an instance of an object.}
   at Barotrauma.TextureLoader.FromStream(Stream stream, String path, Boolean compress, Boolean mipmap) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Utils\TextureLoader.cs:line 208
[29.01.2022 11:34:52] Loading texture "Content/UI/WeaponUI.png" failed! {Object reference not set to an instance of an object.}
   at Barotrauma.TextureLoader.FromStream(Stream stream, String path, Boolean compress, Boolean mipmap) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Utils\TextureLoader.cs:line 208
[29.01.2022 11:34:52] Loading texture "Content/UI/WeaponUI.png" failed! {Object reference not set to an instance of an object.}
   at Barotrauma.TextureLoader.FromStream(Stream stream, String path, Boolean compress, Boolean mipmap) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Utils\TextureLoader.cs:line 208
[29.01.2022 11:34:52] Loading texture "Content/UI/WeaponUI.png" failed! {Object reference not set to an instance of an object.}
   at Barotrauma.TextureLoader.FromStream(Stream stream, String path, Boolean compress, Boolean mipmap) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Utils\TextureLoader.cs:line 208
[29.01.2022 11:34:51] Loading texture "Content/UI/WeaponUI.png" failed! {Object reference not set to an instance of an object.}
   at Barotrauma.TextureLoader.FromStream(Stream stream, String path, Boolean compress, Boolean mipmap) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Utils\TextureLoader.cs:line 208
[29.01.2022 11:34:51] Loading texture "Content/UI/WeaponUI.png" failed! {Object reference not set to an instance of an object.}
   at Barotrauma.TextureLoader.FromStream(Stream stream, String path, Boolean compress, Boolean mipmap) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Utils\TextureLoader.cs:line 208

**Comment by Regalis11** [comment] 2022-01-31 08:28
Duplicate of https://github.com/Regalis11/Barotrauma/issues/8099

**Closed by Regalis11** 2022-01-31 08:28 UTC
