### ISSUE TITLE
[Minor Issue][Misleading name] The "Medium Steel Cabinet" name confuse new players.

### ISSUE THREAD

**Issue by Ant1V1RU5** [Regalis11/Barotrauma#2627] opened 2020-04-13 18:48 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Today, on Izzi280 Twitch stream, new players were confused a lot when they were instructed to place some delivery metal crate in the "Medium Steel Cabinet" during the Handle with Care and Explosive Cargo missions.

As new player are really important to the grotwh of both our community and the game, such misleading item name can generate confusion and / or frustation.

Multiple players on the Official Barotrauma Discord agreed that the "Medium Steel Cabinet" should be renamed as "Crate Holder" or "Crate Locker" or with a better name to help new players understand what it does

**Version**
Current version 0.9.8.0 - Updated Windows

**Additional information**
The streamer and his friends semmed to like the game, as they have planned multiple gaming sessions.

**Comment by Regalis11** [comment] 2020-04-14 07:55
Duplicate of #2335

**Closed by Regalis11** 2020-04-14 07:55 UTC
