### ISSUE TITLE
Excellent Morale and High Morale flicker once a player dies

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10490] opened 2022-11-20 22:50 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

After the death of a crew member, the High Morale and Excellent Morale icons played what can only be described as "musical chairs" which one another. The High Morale would appear on screen, get replaced by the Excellent Morale icon, and then get replaced by nothing. Each would swap positions at intervals of ~2 seconds. This has continued ever since.

![image](https://user-images.githubusercontent.com/105495756/202923526-11b2b767-8228-4b68-af5d-368e4f0aa305.png)
![image](https://user-images.githubusercontent.com/105495756/202923531-75667e89-98ba-426a-8afc-ba61930ea64d.png)

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by 3e849f2e5c** [comment] 2022-11-21 13:51
I couldn't actually reproduce this in a dev environment but I have a feeling it's because client and server disagree whether or not someone has died during the round so the client was trying to apply excellent morale while the server was correctly applying high morale which removed excellent morale when the afflictions synced from the server

**Comment by 3e849f2e5c** [comment] 2022-12-07 14:05
Potentially fixed in https://github.com/Regalis11/Barotrauma-development/commit/2a364c2b6d2fe9e153a3d0f42612b0805eeac2e0

**Comment by NilanthAnimosus** [comment] 2022-12-09 15:37
Tested against talent-fixes-7 commit https://github.com/Regalis11/Barotrauma-development/commit/9eb527b16fa464005755a4f5740234e34035ba54 no issues found, closing.

**Closed by NilanthAnimosus** 2022-12-09 15:37 UTC
Labels: Bug, Need more info, Code
