### ISSUE TITLE
Modding: Crash with the exception: The given key 'huskmutantacidsplash' was not present in the dictionary

### ISSUE THREAD

**Issue by pavel4win** [Regalis11/Barotrauma#12471] opened 2023-08-05 15:17 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

network game crashes

### Reproduction steps

I do not know exactly.
It was game on dedicated server with 2 clients. Both of us crashes

[crashreport (18).log](https://github.com/Regalis11/Barotrauma/files/12267558/crashreport.18.log)

### Bug prevalence

Just once

### Single player or multiplayer?

Multiplayer hosted using a dedicated server

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment] 2023-08-11 07:22
The issue seems to be caused by a missing particle prefab in a mod. The line numbers in the crash log are wrong (again), but the exception thrown is this:

Exception: The given key 'huskmutantacidsplash' was not present in the dictionary. (System.Collections.Generic.KeyNotFoundException).

The game shouldn't crash when some content is missing, sounless it's caused by the Lua mods, it's something we should try to fix. There's no clear steps to repro this, and I don't think this is something we should use much time digging into. However, let's keep the ticket open, in case we'll get more information about the issue.

**Comment by Regalis11** [comment] 2023-08-14 10:14
Ran into this while testing https://github.com/Regalis11/Barotrauma/issues/11998. Can be reproduced by adding the xml in the ticket to e.g. weapons.xml, and trying to fire a "otfx.shotgunshell.dragonbreath" with the riot shotgun.

**Comment by Regalis11** [comment] 2023-08-14 10:14
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e8c7d81265b29937a30ba5208e8780d2247bbb73

**Comment by Rokvach** [comment] 2023-08-16 11:20
Tested, working correctly. Can be merged and closed.

**Closed by Rokvach** 2023-08-16 11:20 UTC
Labels: Bug, Code, Crash, Modding
