### ISSUE TITLE
SpawnItem and NearbyItems seemingly nonfunctional when combined in StatusEffects

### ISSUE THREAD

**Issue by WrillWasTaken** [Regalis11/Barotrauma#12937] opened 2023-10-28 17:00 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

StatusEffects set to target NearbyItems and spawn an item using SpawnItem appear to always spawn the item on the entity executing the StatusEffect? I first noticed this with the following code:

	<Item identifier="selfdeletingitem" name="if you can see this call 1-800-coder" noninteractable="true" >
		<Sprite texture="containers.png" sourcerect="0,0,2,2" depth="0.55" origin="0.5,0.5" />
		<ItemComponent characterusable="False">
			<StatusEffect type="OnSpawn" delay="0.1" target="This">
				<Remove />
			</StatusEffect>
		</ItemComponent>
	</Item>

	<Item identifier="henk" variantof="selfdeletingitem">
		<ItemComponent characterusable="False">
			<StatusEffect type="OnSpawn" delay="0.1" target="This">
				<Remove />
			</StatusEffect>
			<StatusEffect type="OnSpawn" target="NearbyItems" targettags="vent" range="750">
				<SpawnItem identifier="bananapeel" SpawnPosition="This" />
			</StatusEffect>
		</ItemComponent>
	</Item>

and then went on to test it by duplicating the piezo crystal and adding this to it

      <StatusEffect type="OnActive" target="NearbyItems" targettags="junctionbox" range="3000.0" setvalue="true" stackable="false" delay="0.95" extraload="500">
				<SpawnItem identifier="bikehorn" SpawnPosition="This"/>
	  </StatusEffect>

and noticed that the bikehorns always spawn on the piezo crystal.
![image](https://github.com/Regalis11/Barotrauma/assets/86113712/8d3321f1-4e84-4294-b895-078df814ad41)

even though the junction boxes were targeted by the statuseffect and received the extra load as expected.
![image](https://github.com/Regalis11/Barotrauma/assets/86113712/5bb483be-b445-4abe-a314-35fb65a53a81)

### Reproduction steps

1. Run StatusEffect with target of NearbyItems and a SpawnItem component inside. 
2. Watch as the item spawns on the entity executing the StatusEffect and not the target.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Other

### -

Quickstart dugong

### Version

v1.1.18.1 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-10-29 08:36
This is not a bug: [as mentioned in the modding documentation](https://regalis11.github.io/BaroModDoc/Misc/StatusEffect.html), "This" refers to the entity executing the effect.

**Comment by WrillWasTaken** [comment] 2023-10-29 10:46
> This is not a bug: [as mentioned in the modding documentation](https://regalis11.github.io/BaroModDoc/Misc/StatusEffect.html), "This" refers to the entity executing the effect.

Untrue. Documentation says "This" On SpawnPosition refers to the target.
![image](https://github.com/Regalis11/Barotrauma/assets/86113712/cd000a3c-5f05-4a6e-bb97-314452e1538c)

**Comment by Regalis11** [comment] 2023-10-29 11:16
Oh, sorry, you're right! I read this too hastily and got the TargetType and the SpawnPositionType mixed up. Reopening.

**Comment by Regalis11** [comment] 2023-10-30 10:14
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/e3565570e010927098cbb2992135bbc3f738cae2 (commit in our private repo)

**Closed** 2024-01-19 10:12 UTC
Labels: Bug, Code, Modding, Testing branch
