### ISSUE TITLE
[0.10.501] Deleting a singleplayer save hides all the other saves until the menu is reloaded

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3699] opened 2020-09-03 13:07 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Deleting a singleplayer save hides all the other singleplayer saves until the menu is reloaded.
![Capture](https://user-images.githubusercontent.com/5086682/92118879-0b2c1500-edc5-11ea-8c4d-5b528fbccaba.PNG)
![Capture2](https://user-images.githubusercontent.com/5086682/92118888-0bc4ab80-edc5-11ea-92fd-9136d518f81a.PNG)

**Version**
0.10.501

**Comment by Regalis11** [comment] 2020-09-03 13:18
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/864766630d6f40429f17d6edfefc2c56bee5b433

**Comment by Rokvach** [comment] 2020-09-04 06:01
Tested, wasn't able to reproduce the issue. Seems to be working correctly. Closing.

**Closed by Rokvach** 2020-09-04 06:01 UTC
Labels: Bug, Code
