### ISSUE TITLE
[Unstable] Sub Editor "(charger to weapon) link don't work"

### ISSUE THREAD

**Issue by Cocrane34** [Regalis11/Barotrauma#10742] opened 2022-12-17 01:35 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In sub editor, with the unstable V0.21.0.0 version of the game.
Link between charger and weapon, also between storage don't actually work.

When you press space, and then the object you want to link, there is no link.
Link that's already existed are working, but are not deletable, because the game doesn't seem to detect the key combination, maybe.

I don't have changed the commands of editor mode (i don't know how to do that's anyway.) I also checked the game files with steam,  it found two missing files, but that didn't solve the problem.

"please tell us what you expected should have happened": The link between a Pulse laser charger and a Pulse laser turret should work.

good luck !

### Reproduction steps

1. start submarine editor.
2. take a submarine, for the record, i was editing the vanilla Humpback.
3. Try to link any object with another.

### Bug prevalence

Happens every time I play

### Version

0.21.0.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-12-20 09:43
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/13ee9f93ccd87abb780240c4ce3558bfbb13ec47

**Comment by hypnosundermoon** [comment] 2023-01-03 01:34
> Fixed in https://github.com/Regalis11/Barotrauma-development/commit/13ee9f93ccd87abb780240c4ce3558bfbb13ec47
does the bug fixed? the link seem not exist.

**Comment by Wheatley1002** [comment] 2023-01-08 05:46
>  does the bug fixed? the link seem not exist.

Is the bug fixed? Yes.
The link is to a private repository only the devs can access; it's for internal stuff. What this means for us (players) is that we need to wait for the next unstable build, 0.21.1.0, for the issue to be potentially merged into the build. We don't have immediate access to the fix, but the bug is fixed. 
This is done to ensure that there are no unintended bugs caused by the fix, as rushing a fix into the main build may have unforeseen issues with something else. It's unfortunate but all we can do at the moment is wait for the next patch and see if this specific issue was included with it :)

**Comment by Regalis11** [comment] 2023-01-27 12:18
Addressed in https://github.com/Regalis11/Barotrauma-development/pull/3813, closing

**Closed by Regalis11** 2023-01-27 12:18 UTC
Labels: Bug, Code
