### ISSUE TITLE
Save Corrupted during gameplay (saved submarine is empty, the submarine file may be corrupted)

### ISSUE THREAD

**Issue by SircoGeji** [Regalis11/Barotrauma#12811] opened 2023-10-14 21:33 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Can no longer load save, game instantly throws an error and crashes.
Had some mods, list of which will attach next. Tried to reinstall game without mods, but throws the same error.
![baro_error](https://github.com/Regalis11/Barotrauma/assets/69348839/32a1d972-cefd-4096-b13a-36f428072aa0)

Installed mods:
* ADV Beacon Stations
* BAROTRAUMA - RIGHT VERSION
* Cheeki Breeki Accordion
* EK Mods for 1.x.x.x.x
* oClockRadar _Alt
* Wreck Locator
* Attack Submarine Mineral Scanner Upgrade

Attaching corrupted save file:
[Multiplayer.zip](https://github.com/Regalis11/Barotrauma/files/12908067/Multiplayer.zip)

Do you have an option to get stable save? Fine if without mods.

### Reproduction steps

1. Start a multiplayer game
2. Sub won't load (error shown as above)

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Error message as above
```

**Comment by Regalis11** [comment] 2023-10-15 14:08
Duplicate of https://github.com/Regalis11/Barotrauma/issues/12104

**Closed by Regalis11** 2023-10-15 14:08 UTC
