### ISSUE TITLE
Mineral Scanner on Transport Sub's Navigational Terminal Not Working.

### ISSUE THREAD

**Issue by Viperspider** [Regalis11/Barotrauma#10018] opened 2022-10-07 21:26 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I am using a custom Tier 1 Transport Sub. I updated my navigational terminal to include a mineral scanner, since this was mentioned in the change log as a QoL improvement. Even after purchasing the upgrade in the Outpost my mineral scanner does not work.
I verified this because as part of a mining quest I parked right over a quartz deposit and the scanner detected nothing. On the trips in between no minerals have been spotted, which is possible but unlikely.

### Reproduction steps

1. Start any campaign.
2. Use a Scout/Transport sub.
3. Try to use the mineral scanner in the navigation terminal.

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
None.
```

**Comment by ekqvist** [comment] 2022-10-28 08:44
Playing with Camel, the mineral scanner seems to show the minerals within the sonar range when active sonar and mineral scanner are turned on:

![image](https://user-images.githubusercontent.com/16864465/198544727-7275bb32-d637-4342-adbc-94514111a13c.png)

I also tried one level with an active mineral mission. The mission resources were indicated with the red mission marker.

**Comment by ekqvist** [comment] 2022-10-28 08:46
Might be that the amount of resources is fairly low (and some of them can be found further down in the abyss) and you won't necessarily spot them unless you move close enough to the walls where they are placed.

**Comment by ekqvist** [comment] 2022-10-28 11:40
@Viperspider Unfortunately, it seems that I'm either unable to reproduce your issue or then I have misunderstood it. If you can provide any additional information, that'd be helpful.

**Comment by Viperspider** [comment] 2022-10-28 12:54
Hi,If the issue reoccurs for me I will take video footage of it and post it as a reply to this ticket. It is inconsistent, sometimes the mineral scanner works fine and other times I see nothing, including the time where I had a specific quest to mine minerals on the "surface" which I was hovering right over but the scanner did not detect.Since it's an intermittent problem I think you can consider this issue closed until I provide further evidence.Apologies for the inconvenience caused.Best Regards,Shane.On 28 Oct 2022 12:41, Kasperi Ekqvist ***@***.***> wrote:
@Viperspider Unfortunately, it seems that I'm either unable to reproduce your issue or then I have misunderstood it. If you can provide any additional information, that'd be helpful.

**Comment by ekqvist** [comment] 2022-10-31 08:36
If you encounter this issue again and can send me the save file where this happens, it would be even better! Then it would be easy for me to reproduce and debug.

**Comment by Viperspider** [comment] 2022-10-31 11:49
Will do, thank you!In the session I played last night all seemed to go well. Random minerals were plentiful in every voyage so maybe it was a once-off.Best Regards,Shane.On 31 Oct 2022 08:37, Kasperi Ekqvist ***@***.***> wrote:
If you encounter this issue again and can send me the save file where this happens, it would be even better! Then it would be easy for me to reproduce and debug.

**Comment by Regalis11** [comment] 2023-02-16 08:58
No known steps to repro, closing

**Closed by Regalis11** 2023-02-16 08:58 UTC
Labels: Bug, Need more info, Code, Design
