### ISSUE TITLE
A crash in the sub editor

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#5399] opened 2021-03-31 08:50 UTC
"I was making a submarine, I hit test and"..."I looked at the stack trace and it looked like it had something to do with the submarine itself and the position where it was placed. At the time, I had another submarine placed inside of the one I was building around, and the submarine I was building around was null, it didn't have anything in it. So it looked like I was making a new submarine altogether, but there was another submarine entity inside of the one I was building. So when I hit the test button, nothing even happened and it just crashed. My hypothosis is that either the game didn't like that the 2 submarine entities were put inside of each other, so they collided. Or that I put my spawnpoint too low, my character clipped into the sub, and it want flying out of the water."

crashlog: https://github.com/Regalis11/Barotrauma/files/6229456/crashreport.log

**Comment by Regalis11** [comment] 2021-03-31 09:17
Duplicate of https://github.com/regalis11/barotrauma/issues/5082, it's also no longer possible to repro this because the sub editor doesn't allow going into the test mode if the sub doesn't have hulls.

**Closed by Regalis11** 2021-03-31 09:17 UTC
Labels: Bug, Code, Crash
