### ISSUE TITLE
Can you do something about this GUI overlap?

### ISSUE THREAD

**Issue by Xyvyrianeth** [Regalis11/Barotrauma#8444] opened 2022-03-03 21:01 UTC
![image](https://user-images.githubusercontent.com/25062300/156645961-36b9a43a-ec10-4db3-954d-ea9b4cd56b94.png)

**Description**
Often, when you have side-by-side GUIs, they'll overlap and make each other really hard to use.

**Steps To Reproduce**
The issue I think that's causing this is that GUIs seem to remember where they were placed when they're accessed directly and won't move after that.

Examples of what I mean:
- [Fabricator and Deconstructor](https://youtu.be/DVtS0ErhKm4)
- [Linking 1 locker](https://youtu.be/vm_b2svqmk4)
- [Linking 2 lockers](https://youtu.be/hxO8_U9UKSg)

**Version**
v0.16.7.0

**Additional information**
GUIs being draggable would be a huge help.

**Comment by Regalis11** [comment] 2022-03-04 07:15
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7610 and https://github.com/Regalis11/Barotrauma/issues/4332

We've got a fix coming up for this in the next update. :)

**Closed by Regalis11** 2022-03-04 07:15 UTC
