### ISSUE TITLE
AI Glitching When Repairing Drones

### ISSUE THREAD

**Issue by mathijs98** [Regalis11/Barotrauma#7559] opened 2021-11-30 21:10 UTC
so i have looked on the internet, i have looked here, i have even looked in Discord but no where is it mentioned that AI glitches out when you undock and redock a drone. i have seen people mention that Kastrull and Remora's drones are glitched with AI pathfinding and even though they are for the most part very glitchy (such as AI sometimes glitching out without the player even touching the drone) i figured out a way to fix it however like i said above, the moment i undock and redock the drone and destroy the drones innards with for example an EMP grenade the AI start to glitch all around the ship such as not being able to pathfind down stairs or walking in walls that are towards the direction of the drone.

you can easily test the difference. 
Normal (pick Kastrull/Remora, go down to the drone, drop an EMP grenade, let the engineers fix it (sometimes still glitches out))
Glitched (pick Kastrull/Remora, undock and redock the drone, drop an EMP grenade, watch the engineers glitch out)

v0.15.13.0 (ReleaseWindows, branch release, revision 4e66dd7b5d)

**Comment by Regalis11** [comment] 2021-12-01 09:04
Potentially related ticket: https://github.com/Regalis11/Barotrauma/issues/5242

**Comment by Regalis11** [comment] 2021-12-10 08:00
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7274

**Closed by Regalis11** 2021-12-10 08:00 UTC
Labels: Bug, Code
