### ISSUE TITLE
Welding Fuel Tanks Sometimes Lose some Percentage of fuel on docking/ undocking/ changing maps

### ISSUE THREAD

**Issue by gerakis** [Regalis11/Barotrauma#7932] opened 2021-12-25 01:01 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Sometimes when changing maps fuel tanks lose a chunk of their remaining fuel and become no longer full. The tanks were kept in a storage locker. Nobody used them as its single player, and there is no way to use an entire stack at exactly the same percentage like this as far as I know.

**Steps To Reproduce**
I'm not sure what causes it and it doesnt always happen so im hoping something in the code jumps out at you as the cause. These tanks were stolen from the previous station if it matters. Ive only seen this in single player. The station I stole them on was Hyperenor Linea, right before traveling to the next biome.

My theory is that somehow that stations fuel tanks were set to maximum of like 180/180 fuel (or whatever) while the default for subs is 200/200 or something like that. As soon as you leave the station it starts to judge the tanks by the standards of the sub, and so considers them as 180/200, so partially consumed. I havent looked at the code at all so this theory could be very wrong.

**Version**
0.15.22 Windows, no mods, singleplayer campaign

**Additional information**
![fuel tanks reduced by some fraction](https://user-images.githubusercontent.com/16128947/147375217-2a1ada28-0c09-410f-a2b9-e0e3ce39ec17.png)

**Comment by Oukido** [comment] 2021-12-25 21:35
Was there a fire near the locker by any chance? Fires can do this. Also the oxygen tanks in the plasmacutters are partially consumed.

**Comment by gerakis** [comment] 2021-12-27 00:47
I tested Oukido's fire theory. Fire causes the entire tanks to blow up and be completetly empty, not 20% drained. I tried a short lived fire but they still just blew up almost instantly.

I also tried a water-lithium explosion both in the cabinet and outside. The cabinets in question seem to be waterproof, and if dropped outside the cabinet the explosion seems to not effect tanks inside the cabinet.

Based on the results I think fire and explosions did not cause this. Some kind of bug did. It was a good theory though.

**Comment by Regalis11** [comment] 2022-01-05 10:30
I suspect this was caused by fire or explosions as well. It takes 10 seconds for a fire to explode a 100% condition tank, so it could be possible a short-lived fire caused this. Explosions do also damage tanks (excluding explosions from lithium or other water-sensitive materials or other tanks: we specifically excluded them to prevent "chained explosions" that destroy all the nearby tanks), so that could be another explanation.

It could be a bug as well though, but I can't think of what could've caused it off the top of my head. In any case, we'll keep this open for a bit longer and see if we can figure out if it was a bug or not.

**Comment by Regalis11** [comment] 2022-02-04 10:19
No known steps to repro, closing

**Closed by Regalis11** 2022-02-04 10:19 UTC
Labels: Bug, Need more info, Code
