### ISSUE TITLE
Bug in engineer leveling

### ISSUE THREAD

**Issue by PiatraAlatyr** [Regalis11/Barotrauma#9335] opened 2022-06-14 12:19 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While playing on the server, I noticed that if an engineer gets a talent point, he can unlock the entire central branch, regardless of the progression. If you choose the last perk, then it unlocks all the talents of the middle branch. The effect lasts until the end of the mission, then resets and there is only 1 effect available for your current level. For example, if the branch was completely empty and you activated the last talent, then on the next mission you will receive the first talent in this branch, and the rest will be canceled
![Снимок экрана (1883)](https://user-images.githubusercontent.com/36773134/173575458-ac82d166-2cd9-4b81-870b-447e44e08704.png)
.

### Reproduction steps

1. Log into the server as an engineer (maybe it works in single player too)
2. Get a talent point
3. Invest it in the last perk of the central branch

### Bug prevalence

Happens every time I play

### Version

0.18.9.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-06-16 08:25
I'm afraid I could not reproduce this.
![image](https://user-images.githubusercontent.com/14351070/174026802-938edd16-1fc0-49d2-83b9-4a9a32ac44c9.png)

The "All-seeing Eye" talent should unlock the entire Electrician tree, but I could not find a way to unlock it without unlocking the previous talent tiers from the tree first.

**Comment by esirprus** [comment] 2022-07-07 09:20
I have a test here: unlock "All-seeing eyes" for Engineer A in the sub editor, then give Engineer B some experience to level up, you can find that Engineer B can directly choose to unlock the last "All-seeing eyes" talent and it is . You can find that Engineer B has the option to unlock the last "All-seeing eyes" talent in the middle talent tree. And it really works.
After testing in the editor, open a single player game and notice that your engineer will have a similar situation.
In multiplayer game, if there are other engineers with "All-seeing eyes", the bug is same as single player mode, otherwise the situation in this issue will occur.

![image](https://user-images.githubusercontent.com/44423036/177737748-6c891e08-3825-43b1-98f8-1ec5e04ed87f.png) 
![image](https://user-images.githubusercontent.com/44423036/177738135-3b4631af-ff31-4cd6-b30e-8d8387f45a0e.png)

**Comment by esirprus** [comment] 2022-07-31 09:29
@Regalis11
I'm sorry to bother you, but I thought this extra information I've provided would be helpful in solving this problem.

**Comment by esirprus** [comment] 2022-09-09 07:24
still can reproduce in v0.18.15.1

**Comment by Regalis11** [comment] 2022-10-17 08:10
This talent has been removed as a part of the upcoming talent overhaul (ticket in our private repo), closing.

**Closed by Regalis11** 2022-10-17 08:10 UTC
Labels: Bug, Code, Waiting
