### ISSUE TITLE
Capn Hognose and Mopy Jack

### ISSUE THREAD

**Issue by Ozymandias187** [Regalis11/Barotrauma#11039] opened 2023-01-26 20:05 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I just found the Mopy Jack quest from Captain Hognose. When I got to the dialogue after I asked how Hognose survived it piped in dialogue from the crawler hybrid quest instead, the text about finding the crawler in the tank and it looking at you with blue eyes. After I hit 'continue' Hognose continued with the next stage of dialogue talking about Mopy Jack being here and wanting to hire me to kill it. It was a single player campaign driving WinterHalter, talked to him with Artie Doolittle all clowned out in a city colony that unlocks the Thermal Wastes.

### Bug prevalence

Just once

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
No error messages popped up, the quest got activated as normal after the rest of the dialogue displayed.
```

**Comment by Regalis11** [comment] 2023-02-01 19:01
Thank you for the report! This seems to have already been reported and should be fixed in the patch that just went out yesterday.

Closing as a duplicate of https://github.com/regalis11/barotrauma/issues/10791

**Closed by Regalis11** 2023-02-01 19:01 UTC
