### ISSUE TITLE
Wreck Events won't happen when Submarine drives by Wrecks.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2761] opened 2020-05-02 16:43 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
TC_One and me have been noticing strange lack of spawn for wrecks under certain conditions. When you drive by a wreck with the submarine, the enemies that should spawn in the wreck won't appear. If you swim or teleport yourself to the wreck when the submarine is still decently far away from the wreck (about 200m) the enemies in the wreck would populate.

**Steps To Reproduce**
Start a new campaign with just "1" as the Seed, using the Orca
Choose Astypalaea linea as your destination with No Mission.
There should be a wreck relatively close to the start and a crawler event in it

Test 1:
- Teleport a Crew to the wreck. You should see a crawler spawn

Test 2:
- Get your sub close to the destination and wait for it to get to the wreck normally (no cheats)
- Stop your sub, take a diving suit and get a character into the wreck
- No crawler spawns, even thought the event manager thinks it should

Test 3:
- Park your sub 200m away from the wreck.
- Swim the rest of your way to the wreck. Crawler should spawn.

**Version**
0.9.9.1

**Comment by RusChosen** [comment] 2020-05-02 16:48
It's TC_One here and I'd like to add that "Test 3" doesn't always result in a spawn in my computer either. Only the Test 1 gives a solid 100% monster spawn in my experience.

**Comment by RusChosen** [comment] 2020-05-03 13:00
Did a bit more testing and now I've found out that the bug will only happen if another sub (not necessarily a main sub) is close to the wreck.
I've tried Test 3 with ranges 200+ meters and it seems that it started to give me more or less solid spawns.
Then, I've tried Test 3 but was deploying a character via a shuttle. No spawns.

And the last thing that is very important:
Without restarting the level I took a shuttle 200m away from the wreck, took the scooter and went back to the wreck. Monsters **did spawn!** So whatever is causing it is tied to a submarine hull being too close to the wreck. Nothing to do with % of main path travelled, neither it is tied to mainpath events that did or did not happen.

**Comment by Regalis11** [comment] 2020-05-03 13:34
Duplicate of #2270

**Comment by Kaillera** [comment] 2020-05-03 14:06
Pretty sure this is different than #2270

**Comment by jeffercize** [comment] 2020-05-08 15:28
So I believe this bug is being caused by the monsterevent code I believe that checks if there are any sub too close to the spawn position which is important for the mainpath monsters, but then for wrecks, caves, and ruins it also checks if the sub is close enough to spawn (to prevent unneeded spawning). The issue I imagine is from checking against both a minimum and maximum range, meaning the sub needs to be in that sweet spot to spawn. As a solution I simply made it not check minimum range for ruin, wreck, and cave monster events by changing it to an if else, moving the foreach (submarine etc.) to and else of the if(spawnPosType == Level.PositionType.Ruin etc.) I attached the file. With this monsterevent code monster will spawn everytime, regardless of if you teleport, or approach naturally.

**Comment by Regalis11** [comment] 2020-05-09 13:28
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/62a4b7ad57a36be9ada4fba808717596a0ea3e84

**Comment by Kaillera** [comment] 2020-05-18 13:35
[0.9.1001.0] So far there has been almost always an encounter in wrecks. I likey.

**Comment by Rokvach** [comment] 2020-05-18 13:50
Closing

**Closed by Rokvach** 2020-05-18 13:50 UTC
Labels: Bug, Code
