### ISSUE TITLE
Game crashes when i add an empty text field to the favorites of the Serverbrowser.

### ISSUE THREAD

**Issue by Okamisan111** [Regalis11/Barotrauma#1954] opened 2019-12-24 08:59 UTC
The game crashes when i add an empty text field to the favorites of the Serverbrowser.

Not really an important Issue, but worth to mention.

**Comment by Regalis11** [comment] 2020-01-04 14:02
Fixed for the next update (v0.9.7.0)

**Comment by Rokvach** [comment] 2020-01-08 12:07
Which branch was this fixed in? I tested both dev and bugfixes and both of them crashes @Regalis11

**Comment by Rokvach** [comment] 2020-01-09 10:28
Moved back to To-Do as I couldn't find where the fix was made

**Comment by Regalis11** [comment] 2020-01-21 20:34
I think I misunderstood what this report is about, and assumed it was fixed already. What I did was adding a server with an empty name (both by manually adding it to the xml and forcing a real server's name to an empty string client-side), but I'm guessing that's not what the issue was. @Rokvach How can I repro this?

**Comment by Rokvach** [comment] 2020-01-21 21:30
Seems like it has been resolved, the crash occurred if you clicked the Favorite button on the Direct Join window while the field was empty, tested in dev just now and it doesn't crash the game anymore and further on in the UI branch the field is disabled until there is something written on the field, so this is working as intended now. Moving to Done.

**Closed** 2020-02-04 12:08 UTC
Labels: Bug, Code, Crash
