### ISSUE TITLE
Wrecked railgun able to be installed on Kastrull drone hardpoint

### ISSUE THREAD

**Issue by aeondez** [Regalis11/Barotrauma#10435] opened 2022-11-18 22:46 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Wrecked railgun is allowed to be installed on small hardpoints.

### Reproduction steps

1. Start a campaign
2. Get enough money to mount a wrecked railgun on a hardpoint. (I used the Kastrull drone hardpoint, specifically)
3. Shoot the wrecked railgun from your small hardpoint.
4. Check to see if the issue exists.
5. File a bug report.

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
no crash, N/A
```

**Comment by Regalis11** [comment] 2022-11-23 15:08
Thank you for the report!

Could not reproduce in the latest unstable build, seems to have been fixed.

**Comment by Rokvach** [comment] 2022-11-28 14:00
Tested, no issues. Closing.

**Closed by Rokvach** 2022-11-28 14:00 UTC
Labels: Bug, Needs testing, Code, Unstable
