### ISSUE TITLE
Sootman rescue hath no self-preservation

### ISSUE THREAD

**Issue by Hamburgian** [Regalis11/Barotrauma#12485] opened 2023-08-09 18:17 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

when rescuing sootman in a jailbreak mission, he prioritizes trying to make a fire over searching for a diving suit to avoid being crushed by the pressure. I've tried to give him a diving suit but he just takes it off.

### Reproduction steps

(the coalition is hostile to me and my crew in this situation)
1. use ship artilleries to make outpost go boom boom, (it makes dealing with the outpost security easier) 
2. prep to go into outpost (2 diving suits, one for me and one for sootman)
3. go to area where sootman is locked
4. open door and interact with him
5. watch as he skedaddles off and swims into his doom, not even caring about the pressure
6. he dies
7. mission fail
8. retry mission and go back to step 1

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by AdamH-Daedalic** [comment] 2023-08-11 14:17
Reproduced on v1.0.21.0

Following the original steps above I managed to reproduce this issue once, with other attempts yielding different results. As the video below shows, he ignored the diving suit that I had brought along and swam through the flooded outpost until he found a large opening and then just swam out into the abyss. In other attempts, he darted off and set his fires and then went to the sub as expected, other times he perished in the fire. 

He rarely seems to path directly to any of his objectives, frequently running/swimming back and forth from room to room without any sense of direction before eventually going to where he wants to go. The save file attached should drop the player at the outpost ready to begin the rescue with a sub loaded with ammo to flood the base and take out the security.

Save file:
[Sootman Jailbreak.zip](https://github.com/Regalis11/Barotrauma/files/12322207/Sootman.Jailbreak.zip)

https://github.com/Regalis11/Barotrauma/assets/135589009/7eda92d5-7c79-40da-a819-36fafc0ed61f

**Comment by ubertpendragon** [comment] 2023-08-12 23:30
I must note here that outposts (normal or abandoned) are not designed to be broken and flooded whatsoever. 

The only pump is in the docking module, as for objectives you can casually tear through any outpost with submarine guns

In MP, "destructible outposts" is an option that is off by default.
In SP such an option doesnt exist.

**Comment by Hamburgian** [comment] 2023-08-13 02:02
> I must note here that outposts (normal or abandoned) are not designed to be broken and flooded whatsoever.

yeah well mini nukes and explosive flak shells are the closest I can get to being able to one-shot outpost security officers so they don't shoot me into oblivion first, and those 2 things just so happen to bust the outpost open too. 

If the outpost security wasn't so hard to kill with their 4x health, using handheld weapons and guns might seem more intriguing.

**Comment by itchyOwl** [comment] 2023-08-14 06:01
To me it seems that Soothman isn't able to return back to the outpost using the gaps on the wall. I've actually implemented that behavior in https://github.com/Regalis11/Barotrauma-development/pull/4235, which is coming in the next update. Could you test if you can repro the issue there?

**Comment by AdamH-Daedalic** [comment] 2023-08-14 15:09
Tested in release/traitor-update against the previously mentioned changes. Unable to reproduce the original issue. 

Sootman no longer swims out into the abyss via any of the hull breaches made by the player when attacking the outpost. He still ignores the diving suit provided by the player but he will seek out a diving mask if the player doesn't drop one of them nearby. Each time he correctly navigates to the sub after starting his new fire and the mission completes correctly. 

Closing this as fixed.

**Closed by AdamH-Daedalic** 2023-08-14 15:09 UTC
Labels: Bug, Needs testing, Code
