### ISSUE TITLE
Auto-Injector Headset not applying syringe effects when activated

### ISSUE THREAD

**Issue by ooohsenpai** [Regalis11/Barotrauma#11782] opened 2023-04-08 21:00 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Auto-Injector Headset with morphine inside seems to use it when PC or bot gets to half health (morphine dissapears), but no healing is applied.

### Reproduction steps

1. Start a mission 
2. Wear a Auto-Injector Headset with morphine inside (you or to a bot)
3. Get to half health
4. Watch at the headset consuming morphine
5. Now watch at character's health not restoring at all
6. Think about how you have got scammed by your own headset

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-04-09 09:45
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10389

**Closed by Regalis11** 2023-04-09 09:45 UTC
