### ISSUE TITLE
Error starting mission.

### ISSUE THREAD

**Issue by NicolaruS** [Regalis11/Barotrauma#5064] opened 2021-02-14 19:23 UTC
When starting a mission, the game tries to spawn a creature that is not in the game files - "swarmcrawler".
![изображение](https://user-images.githubusercontent.com/58271380/107886764-2aea6c00-6f13-11eb-9dd3-4d5be67a9cc9.png)

**Comment by Regalis11** [comment] 2021-02-16 14:21
I was unable to reproduce this: the creature is present in the game files in Content/Characters/Variants/Swarmcrawler.xml and seems to spawn with no issues.

Are you using some kind of mods?

**Comment by NicolaruS** [comment] 2021-02-16 17:11
![изображение](https://user-images.githubusercontent.com/58271380/108096887-8727ca00-7092-11eb-9f14-d07148871f65.png)
We played with the mod to add new creatures.
"Survivator Play Creatures"

**Comment by Regalis11** [comment] 2021-02-17 13:56
I'm afraid I still couldn't reproduce this. Tested by installing that mod and starting a crawler swarm mission in multiplayer. Is that the only mod you're using?

**Comment by NicolaruS** [comment] 2021-02-17 18:41
full list of mods: 
![6545334242 — копия](https://user-images.githubusercontent.com/58271380/108251763-e2c48700-7168-11eb-8dc0-10359d18b30a.png)

**Comment by NicolaruS** [comment] 2021-02-17 18:43
we did not make any changes to vanilla monsters.

**Comment by NicolaruS** [comment] 2021-02-17 18:49
Could it be that when you start a random event from the mod "Survivator Play Creatures" , you cannot specify files from the folder "variants"?
![213434345657 — копия](https://user-images.githubusercontent.com/58271380/108252761-0e943c80-716a-11eb-9d89-bac387344400.png)

**Comment by NicolaruS** [comment] 2021-02-17 19:40
![108096887-8727ca00-7092-11eb-9f14-d07148871f65](https://user-images.githubusercontent.com/58271380/108258031-a6952480-7170-11eb-94ac-61ba733408fb.png)
But there is no such file "ragdolls" in the "variants" folder?

**Comment by NicolaruS** [comment] 2021-02-18 17:57
Was able to reproduce this error in the game, the error was caused by an event in the "randomevents" file referencing the creature file in the "variants" folder.

**Comment by NicolaruS** [comment] 2021-02-18 17:59
In order to reproduce the event in a single player game, I used a mod specially made by me 
[Bugrandomevents.zip](https://github.com/Regalis11/Barotrauma/files/6004848/Bugrandomevents.zip)

**Comment by NicolaruS** [comment] 2021-02-18 18:21
![изображение](https://user-images.githubusercontent.com/58271380/108402909-2c77a500-722f-11eb-8c18-adaf0f7ff915.png)

**Comment by Regalis11** [comment] 2021-04-09 09:17
Thank you, finally got around to testing this. Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/0303d23c2490cd7730ed11d868da9fa58b00389a

Can be reproduced in the vanilla game as follows:
1. Modify the random events to spawn swarm crawlers instead of the normal ones (e.g. open randomevents.xml and find and replace "crawler" with "swarmcrawler").
2. Start a multiplayer round of any kind

**Comment by Rokvach** [comment] 2021-04-09 10:15
Tested, wasn't able to reproduce by using the steps provided above. Seems to be working correctly. Closing.

**Closed by Rokvach** 2021-04-09 10:15 UTC
Labels: Bug, Medium Prio
