### ISSUE TITLE
Bots - Doesn't use firearms from a long distance on a hostile in the sub.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2784] opened 2020-05-07 14:34 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
For some reasons bots must be next to hostile targets before they attempt to open fire.

**Version**
0.9.9.1

**Comment by Regalis11** [comment] 2020-05-08 12:01
I unfortunatel wasn't able to reproduce this:
![45673467](https://user-images.githubusercontent.com/14351070/81403671-9a3d5f00-913c-11ea-9c29-852fab6d7c69.png)

Does this happen in some specific sub or with some specific weapon?

**Comment by Kaillera** [comment] 2020-05-08 14:09
> I unfortunatel wasn't able to reproduce this:
> ![45673467](https://user-images.githubusercontent.com/14351070/81403671-9a3d5f00-913c-11ea-9c29-852fab6d7c69.png)
> 
> Does this happen in some specific sub or with some specific weapon?

I think it may be due to small hulls and multi hulled room. The bots doesn't enemies cross hulls.

**Comment by Regalis11** [comment] 2020-05-09 13:29
Yeah, that could explain it. Thanks for the extra info, I'll do some more testing with a multi-hull setup!

**Comment by Regalis11** [comment] 2020-05-11 12:14
Yep, that was the case. The combat objective required the character to be inside the same hull as the target to attack. Thanks for the help, should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/e10a846707f335918f0f099d4c5802fe56b8e274

**Comment by Kaillera** [comment] 2020-05-11 14:06
We might see bots attempts at shooting through floors and ceilings?

**Comment by Kaillera** [comment] 2020-05-13 18:25
[0.9.10.0]
Bot is having issue locating the target in the shuttle. When the target at least enters the gap between the two port, then it opened fire.
![Capture](https://user-images.githubusercontent.com/5086682/81849997-59bb5800-9525-11ea-83f3-d6f5d7f555b8.PNG)
![Capture](https://user-images.githubusercontent.com/5086682/81850194-a737c500-9525-11ea-9b0f-f26167cc087a.PNG)

**Comment by Rokvach** [comment] 2020-05-13 18:32
Long distance shooting seems to be working, but should the shuttle issue be a separate issue ticket @Regalis11 ?

**Comment by Regalis11** [comment] 2020-05-14 07:09
I think that sounds like a pathfinding issue

**Comment by Rokvach** [comment] 2020-05-16 11:39
The original issue this ticket brought up has been already fixed, I think the shuttle issue should be a separate one. Closing.

**Closed by Rokvach** 2020-05-16 11:39 UTC
Labels: Bug, Code
