### ISSUE TITLE
[Unstable] Talent descriptions contain unlocalised names

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#8598] opened 2022-03-24 00:17 UTC
**Description**
Some skill names display this:
![image](https://user-images.githubusercontent.com/59519434/159817289-471cbea3-5605-4edf-a31d-2259f58cd9c3.png)

**Comment by Regalis11** [comment] 2022-03-24 09:26
Duplicate of https://github.com/Regalis11/Barotrauma/issues/8574

**Closed by Regalis11** 2022-03-24 09:26 UTC
Labels: Bug, Code
