### ISSUE TITLE
Combining of Circuit Box and Wifi Component Corrupts Save File

### ISSUE THREAD

**Issue by Kspdude** [Regalis11/Barotrauma#12929] opened 2023-10-27 02:34 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

It was discovered in my multiplayer campaign that by equipping the circuit box and wifi component in both hands at the same time (Circuit box first, then wifi component), they would combine. Then, after docking at the station and completing the mission, the game instantly crashed and shot out errors relating to circuit box positions or something of the sort. The savefile was then corrupted and can not be opened any longer. 

### Reproduction steps

1. Start multiplayer campaign.
2. Spawn wifi component and circuit box.
3. Combine by equipping in both hands.
4. Dock at endpoint station
5. Observe crash and corruption.

### Bug prevalence

Just once

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.1.18.1 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
https://imgur.com/y4JQHNL

I know this isn't really how this box is supposed to be used, but I didn't think to grab the errors, and it doesn't seem to have generated a crash report. My apologies :(
```

**Comment by Regalis11** [comment] 2023-10-27 05:37
Thank you for the report!

Would it be possible to send us the crash report and the save file? Those would help us a lot in diagnosing the issue (and we can also most likely edit the save file to make it load again). You can attach them here in the github, although the latter needs to be .zipped because github doesn't support attachments with the .save file extension. Thanks and sorry for the inconvenience!

**Comment by Kspdude** [comment] 2023-10-27 12:09
Of course! Thanks so much for the quick reply, I can send the save file.
However, I've searched repeatedly and it doesn't seem to have generated a
crash report despite a pop up saying it has, as I can't find it anywhere.
Am I missing something?

**Comment by Jasontti** [comment] 2023-10-27 12:54
Hello,
Server log files are saved in ServerLogs folder in main folder of Barotrauma.
Easiest to find them is in steam right click Barotrauma > manage > browse local files.

**Comment by Kspdude** [comment] 2023-10-27 19:58
[save file.zip](https://github.com/Regalis11/Barotrauma/files/13192684/save.file.zip)
Here is the save file. 

It's worth noting that there are multiple circuit boxes on the sub, and the problem was/is in a player inventory. I have no idea if this means that the save itself will be fine with just that person's inventory removed or what, but after the first crash the save file would crash the lobby and return to the main menu upon attempting to load.

As far as the crash report goes, I scanned the server logs and found nothing. Very strange.

Final note, I had sent the save file as well to my Baro friend who is decent with save editing and he was able to delete the problem box in question and restore the save. I haven't been able to recreate the issue in a new campaign following the steps that led to the crashing of the first one, but it's possible this was just a one time freakout and there isn't necessarily a game breaking bug like I first thought. But what do I know? haha, you guys are the experts.

**Comment by Regalis11** [comment] 2023-11-13 12:27
Closing as a duplicate of https://github.com/Regalis11/Barotrauma/issues/12999 since that one has a bit more information on the issue

**Comment by juanjp600** [comment] 2023-11-14 21:54
Reopening this, it seems like a separate but related bug. Here are my repro steps:
- Start a brand new campaign
- Take control of the captain
- Drop everything in your inventory
- Spawn a wrench in the inventory
- Spawn 64 FPGA circuits in the inventory
- Spawn a WiFi component in the inventory
- Spawn a circuit box in the inventory
- Place the circuit box
- Configure the circuit box as follows:
  - ![image](https://github.com/Regalis11/Barotrauma/assets/8607119/dc8bd40e-6b9c-40a2-af70-a3355a6ee92a)
- Detach the circuit box
- Drag the WiFi component into the circuit box
- Pick up the wire that falls out of the circuit box
- Without dropping any items, leave the outpost

**Comment by 3e849f2e5c** [comment] 2023-11-17 13:21
Seems to be fixed after https://github.com/Regalis11/Barotrauma-development/pull/4670/commits/df6368338ada284cd7a611d62019c18baaaa58e0

**Comment by Jasontti** [comment] 2023-11-22 07:40
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4520/commits/af084fa81dbebe9eb9d1ad64565b0587063073b0

Inserting components to circuitboxes still work as Juan described.
Save file was not corrupted, but got error message when loading into round.

```
Circuit box error: failed to find an item in the container Circuit Box. Items: 0,  Slot: 16, StackIndex: 0
Failed to find item with ID ItemSlotIndexPair { Slot = 16, StackIndex = 0 } for CircuitBoxNode with ID 0
Failed to load CircuitBoxWire with ID 0, missing "From" or "To" connection.
Circuit box error: failed to find an item in the container Circuit Box. Items: 0,  Slot: 6, StackIndex: 0
Failed to find item with ID ItemSlotIndexPair { Slot = 6, StackIndex = 0 } for CircuitBoxWire with ID 1
```

**Comment by Jasontti** [comment] 2023-11-23 07:49
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4520/commits/3b58963d9b30a9cd7969c14d0c96acd4e6601085

Could not insert components in to circuitbox with previous methods.

No other issues found
Closing ticket

**Closed by Jasontti** 2023-11-23 07:49 UTC
Labels: Bug, Code, Crash, Severe
