### ISSUE TITLE
Bots accidently welding doors when trying to fix leaks

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3911] opened 2020-09-25 21:45 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots can accidently weld doors that are in front of leaks.

**Version**
~0.10.5.1

**Comment by Kaillera** [comment] 2020-09-25 21:46
They should probably be able to detect when they're welding doors when they first attempt to fix leaks behind one. If they do they should open the door.

**Comment by LuCKySoZ** [comment] 2020-09-27 05:22
A misplaced waypoint (no waypoint on the door itself) can cause this. The AI only sees a door if the waypoint tell's there's a door there

**Comment by Kaillera** [comment] 2020-09-27 05:54
Nah it happens on subs like Dugong

**Comment by Regalis11** [comment] 2020-09-28 08:01
Duplicate of https://github.com/Regalis11/Barotrauma-development/issues/2001

**Comment by Regalis11** [comment] 2020-09-28 08:03
Nvm, noticed the earlier ticket is in our private repo, marking that as a duplicate instead

**Comment by itchyOwl** [comment] 2020-09-28 13:47
Should be fixed in Regalis11/Barotrauma-development@adf4a18.

**Comment by Rokvach** [comment] 2020-10-08 08:05
No sightings of this happening, seems to be working correctly. Closing.

**Closed by Rokvach** 2020-10-08 08:05 UTC
Labels: Bug, Code
