### ISSUE TITLE
Enabling wayland result in crash

### ISSUE THREAD

**Issue by jsamr** [Regalis11/Barotrauma#2633] opened 2020-04-15 17:57 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Explicitly setting `SDL_VIDEODRIVER=wayland` env before launching the game result in a crash.

**Steps To Reproduce**
Within a session under wayland display manager, launch the game with `SDL_VIDEODRIVER=wayland` environment variable, for example within steam with custom launch option `SDL_VIDEODRIVER=wayland %command%`.

**Log**
<details>
<summary>Crash report</summary>
<kbd>
ls Barotrauma Client crash report (generated on 04/15/2020 14:38:24)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

F9E5E1DC7C72DC41AFAD92633FB9FE26

Game version 0.9.8.0 (ReleaseLinux, branch release, revision edb4de8c31)
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized

System info:
    Operating system: Unix 5.4.31.1 64 bit
    Game not initialized

Exception: Failed to create graphics device! (Microsoft.Xna.Framework.Graphics.NoSuitableGraphicsDeviceException)
Target site: Void CreateDevice()
Stack trace: 
   at Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice() in /home/joonas/Barotrauma/Libraries/MonoGame.Framework/Src/MonoGame.Framework/GraphicsDeviceManager.cs:line 122
   at Microsoft.Xna.Framework.GraphicsDeviceManager.ApplyChanges() in /home/joonas/Barotrauma/Libraries/MonoGame.Framework/Src/MonoGame.Framework/GraphicsDeviceManager.cs:line 305
   at Barotrauma.GameMain..ctor(String[] args) in /home/joonas/Barotrauma/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 188
   at Barotrauma.Program.Main(String[] args) in /home/joonas/Barotrauma/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 56

InnerException: Object reference not set to an instance of an object.
Target site: System.String GetString(MonoGame.OpenGL.StringName)
Stack trace: 
   at MonoGame.OpenGL.GL.GetString(StringName name) in /home/joonas/Barotrauma/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Graphics/OpenGL.cs:line 1384
   at MonoGame.OpenGL.GL.LoadExtensions() in /home/joonas/Barotrauma/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Graphics/OpenGL.cs:line 1303
   at MonoGame.OpenGL.GL.LoadEntryPoints() in /home/joonas/Barotrauma/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Graphics/OpenGL.cs:line 1285
   at MonoGame.OpenGL.GraphicsContext..ctor(IWindowInfo info) in /home/joonas/Barotrauma/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Graphics/GraphicsContext.SDL.cs:line 49
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformSetup() in /home/joonas/Barotrauma/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Graphics/GraphicsDevice.OpenGL.cs:line 249
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Setup() in /home/joonas/Barotrauma/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Graphics/GraphicsDevice.cs:line 247
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice..ctor(GraphicsAdapter adapter, GraphicsProfile graphicsProfile, PresentationParameters presentationParameters) in /home/joonas/Barotrauma/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Graphics/GraphicsDevice.cs:line 223
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice..ctor(GraphicsDeviceInformation gdi) in /home/joonas/Barotrauma/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Graphics/GraphicsDevice.cs:line 189
   at Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice(GraphicsDeviceInformation gdi) in /home/joonas/Barotrauma/Libraries/MonoGame.Framework/Src/MonoGame.Framework/GraphicsDeviceManager.cs:line 131
   at Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice() in /home/joonas/Barotrauma/Libraries/MonoGame.Framework/Src/MonoGame.Framework/GraphicsDeviceManager.cs:line 114
Last debug messages:
[04/15/2020 14:38:24] Logged in as XXXXXX
</kbd>
</details>

**Version**

- Barotrauma v0.9.8.0, ReleaseLinux, branch release, revision edb4de8c31
- Graphical setup: amdgpu kernel module, mesa@20.0.4-1, vulkan-radeon and lib32-vulkan-radeon@20.0.4-1
- Manjaro (see bellow)
<pre>
~ ❯ neofetch 
██████████████████  ████████   jsamr@jsamr-nuc
██████████████████  ████████   ---------------
██████████████████  ████████   OS: Manjaro Linux x86_64
██████████████████  ████████   Host: NUC8i7HVK J71485-504
████████            ████████   Kernel: 5.4.31-1-MANJARO
████████  ████████  ████████   Uptime: 2 hours, 35 mins
████████  ████████  ████████   Packages: 1666 (pacman)
████████  ████████  ████████   Shell: zsh 5.8
████████  ████████  ████████   Resolution: 1920x1080
████████  ████████  ████████   WM: sway
████████  ████████  ████████   Theme: Adapta-Nokto-Maia [GTK2/3]
████████  ████████  ████████   Icons: Papirus-Adapta-Nokto-Maia [GTK2
████████  ████████  ████████   Terminal: alacritty
████████  ████████  ████████   CPU: Intel i7-8809G (8) @ 4.200GHz
                               GPU: Intel HD Graphics 630
                               GPU: AMD ATI Radeon RX Vega M GH
                               Memory: 4833MiB / 32037MiB
</pre>

**Additional information**

**Comment by aurtzy** [comment] 2022-07-03 10:03
It looks like this is fixed with a later version of SDL2! I tested this with version 2.0.22 in particular, and haven't noticed any issues so far.

For Arch-based systems (currently on EndeavourOS), make sure the `sdl2` [package](https://archlinux.org/packages/extra/x86_64/sdl2/) is installed and it should work with the following environment variables:
`SDL_DYNAMIC_API=/usr/lib/libSDL2-2.0.so.0 SDL_VIDEODRIVER=wayland %command%`

**Comment by chayleaf** [comment] 2023-02-13 11:35
In my case on NixOS the game occasionally shuts down when using wayland using env vars like above. Sometimes it does it after entering main menu, sometimes after entering the game itself (i.e the part where there's gameplay). It doesn't leave a crash log, and there's nothing printed to stdout/stderr, so I'm not sure what causes it, nor can I reliably reproduce it (but it does crash if I restart the game a few times).

**Closed** 2023-04-25 14:47 UTC
Labels: Bug, Linux only, Code, Low prio
