### ISSUE TITLE
kicked when respawning with a uranium bar

### ISSUE THREAD

**Issue by guillermohurtadodm** [Regalis11/Barotrauma#8895] opened 2022-04-21 19:21 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When respawning with the electricist class with the uranium bar the game ckicked us inmediatly

**Steps To Reproduce**
![Barotrauma_kick](https://user-images.githubusercontent.com/71341303/164539071-b4fe9094-65c2-41ca-be1a-d803fb21bcf4.png)
(the image is from the second time this happened, it seems to reference another object)
I think that just diying and attempting to respawn will repeat the outcome

**Version**
v0.17.12.0 in Windows10

**Additional information**
An error appears after the mission fails saying that I had there was an update for an object that didnt exist and it seemed to be the uranium bar

**Comment by cshingle** [comment] 2022-04-21 21:19
This issue is pretty confusing, but it sounds to me like he is running into the MISSING ENTITY error #6265

**Comment by Regalis11** [comment] 2022-04-22 12:58
Duplicate of https://github.com/Regalis11/Barotrauma/issues/8879

**Closed by Regalis11** 2022-04-22 12:58 UTC
