### ISSUE TITLE
Single Player - **IDEA** Multiple saves of a single game w/ crash report

### ISSUE THREAD

**Issue by DDusktv** [Regalis11/Barotrauma#7304] opened 2021-11-14 05:54 UTC
- [Y] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The bug that occurred is attached.

It looks like it was an issue with loading the new port. Unfortunately, as there is no backlog of saved files in single-player mode, I can't just load another save, so I fear this campaign will be lost.

If there were a save file for each time the game is saved, as you have in the multiplayer Server files, I would be able to delete the newest save file with the bug, report it to you and continue gaming with a previous save & port choice.

With only one game save file, my only options are to report the bug, hope for a fix, and potentially lose the invested time into the single-player game.

Please know my mates and I go on dives every Sunday morning and we love it, please keep up the amazing work!

Hope to hear from you soon!

Cheers,
DD

**Steps To Reproduce**
Attached

**Version**
v 0.15.13.0

**Additional information**
Add any other context about the problem here
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/7533249/crashreport.2.log)
.

**Comment by Regalis11** [comment] 2021-11-15 10:53
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7285

**Closed by Regalis11** 2021-11-15 10:53 UTC
