### ISSUE TITLE
AI welding range is significantly shorter than players'

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#6258] opened 2021-07-06 10:54 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.
The same cause as issue #6089 but it's not just Kastrull and I believe I clarified the cause.

**Description**
Even if a wall is within players' welding range (which seems a bit OP), AI won't weld it
https://user-images.githubusercontent.com/10529134/124588307-ef682400-de58-11eb-9c93-6b49d44d5423.mp4
Screenshot from Kastrull:
![Barotrauma_cxC9RNjvu6](https://user-images.githubusercontent.com/10529134/124588330-f727c880-de58-11eb-8883-c6425baa8f6d.png)

**Steps To Reproduce**
1. Cut through a wall that's too far above for AI to reach

**Version**
v0.14.6.0

**Additional information:**
This issue is NOT caused by waypoints. I tried moving the waypoints up.

**Comment by Regalis11** [comment] 2021-07-06 14:25
Duplicate of https://github.com/regalis11/barotrauma/issues/6089

**Closed by Regalis11** 2021-07-06 14:25 UTC
