### ISSUE TITLE
(Unstable) Placed electrical items and wires appear in front of characters.

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#2315] opened 2020-02-15 23:40 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Title says it all
**Steps To Reproduce**
-Start a round as Electrical Engineer variant
-Place components on wall and wire them up
-Walk past them
-Observe sprite depths

EDIT: 
-Start a CAMPAIGN round
-Place components
-Finish a mission and start another
-Now the sprite depths should be wrong
**Version**
Unstable .7

**Comment by Regalis11** [comment] 2020-02-19 09:51
I unfortunately wasn't able to reproduce this with components fabricated mid-round, ones spawned as extra cargo or ones spawned through the console.
![signalcomp](https://user-images.githubusercontent.com/14351070/74822635-baac0900-5305-11ea-8c27-dd13f5f10ff7.png)

**Comment by Kaillera** [comment] 2020-02-19 10:01
It will move to the front the round after.

**Comment by Udrakan** [comment] 2020-02-19 12:21
Oh so thats why buttons appear round after when you place them and they sink below.

**Comment by Kaillera** [comment] 2020-02-19 13:47
#2065 

A different issue related to that.

**Comment by Udrakan** [comment] 2020-02-19 19:48
![bug17spritedepth](https://user-images.githubusercontent.com/59519434/74869956-34211700-5359-11ea-85f4-138669ad8361.png)
This is what it looks like round after placing the items

**Comment by Regalis11** [comment] 2020-02-20 10:05
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/97e7ea0499a31e1d69a8917b11dabcb106ac6b16.

Steps to reproduce:
1. Start a **multiplayer** campaign round.
2. Place components.
3. End the round and start a new one.

**Comment by Rokvach** [comment] 2020-02-25 11:43
Couldn't reproduce so seems to be working, closing.

**Closed by Rokvach** 2020-02-25 11:43 UTC
Labels: Bug, Code
