### ISSUE TITLE
0.1000.0.0 (Unstable): Switching to Current Sub Causes Automatically Generated Items to Disappear

### ISSUE THREAD

**Issue by Jlobblet** [Regalis11/Barotrauma#2902] opened 2020-05-29 15:58 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Items in cabinets that were generated automatically (randomly) via tags such as `engcab` disappear from their cabinets.

**Steps To Reproduce**
1. Start a new campaign, with any sub that has randomly filled storage containers.  
2. At the Submarine Delivery Service terminal, switch the the currently selected submarine.  
3. Check one of the containers that should have automatically generated items in it.

**Version**
Version 0.1000.0.0 (Unstable).
Windows 10 version 1903.

**Comment by Regalis11** [comment] 2020-06-07 14:14
Being able to switch to the current submarine was a bug that has now been fixed, moving this to QA

**Comment by Rokvach** [comment] 2020-06-08 08:18
Unable to reproduce the issue, seems to be working correctly. Closing.

**Closed by Rokvach** 2020-06-08 08:18 UTC
Labels: Bug, Code
