### ISSUE TITLE
sub editor deleting structures

### ISSUE THREAD

**Issue by Demonicturttle** [Regalis11/Barotrauma#11538] opened 2023-03-15 09:31 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

im building a large station but sometimes or every time I delete one item several others off screen delete with it despite not having been selected, its happened to often to be a coincidence. I know its not the part count because the structure count is under 300 item count is under 3000 walls are under 140 and lights are at 109, shadow casting lights are at 49.

this station is big yes and bigger then anything ive made so far but its count on things ive placed is a 3rd of the amount of my largest sub and I had no issues making it

### Reproduction steps

1 try placing several things down in the sub editor 
2 next try deleting a few things
3 if it doesnt work try deleting a group of things in one spot
4 if that doesnt work try loading up a built sub and repeating 2 and 3
5 if that doesnt work then idk

### Bug prevalence

Happens regularly

### Version

v1.0.7.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Torvald118** [comment] 2023-04-06 09:19
### Same

I agree, sometimes unselected items are deleted spontaneously when I delete items that i want to delete. I am building large station too and it is a real pain when you're done with one section, and the rest of the station off-screen is half-way deleted because of bug. I had no any linked groups or something like that.

I could not find the reason why is it happening. What did I do wrong?

Timecode 1:33 Youtube: https://youtu.be/bw9fPD-10-U

Windows 10 Pro
v1.0.8.0
April 6, 2023

**Comment by Torvald118** [comment] 2023-04-16 21:34
### UPD

To continue making the station I have
1. Formatted new disk
2. Reinstalled Windows and formatted disk with all my games
3. Downloaded Barotrauma again
4. Uploaded my map back from the Steam Workshop, created local copy.
5. 
![image](https://user-images.githubusercontent.com/61289060/232342348-af695e3a-64c5-4a6f-a63d-792c40891372.png)
6. All files verified
![image](https://user-images.githubusercontent.com/61289060/232342153-09c0fa6f-af19-4060-8ffb-6fa96040d046.png)
7. Had this: https://youtu.be/kt0LZcOwFtI

OS: Windows 10 Pro
Version: v1.0.9.0
April 16, 2023

My map: 
[Zvezda IV.zip](https://github.com/Regalis11/Barotrauma/files/11244685/Zvezda.IV.zip)

**Comment by Regalis11** [comment] 2023-05-08 17:42
Thank you for the videos and extra info! Something I noticed on the video was that you delete things using the context menu that opens by right-clicking. I personally never use that and just hit Delete instead, which could be why I've never ran into this myself or managed to reproduce the issue. I'll give the context menu a test and see if I can reproduce the problem!

**Comment by Regalis11** [comment] 2023-05-09 14:28
I _think_ I found at least one way to get this to happen now. It's hard to reproduce reliably, but it's possible to get it to happen by doing the following:

1. Put some resizeable structure (like a background wall) in a position where it's corner is behind with some item
2. Move your cursor to that corner, which should highlight the item
3. Resize the structure
4. The item should now appear to become unhighlighted, but it's actually still in a list of highlighted entities, and will get removed if you delete selected items using the context menu.

Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/7ac553336359049ff997c81f577b7c3ee1483ab5 (commit in our private repository)

**Comment by UEAdmiral** [comment] 2023-07-04 06:41
I've been experiencing this issue while editing a sub today. Currently on v1.0.21.0, revision adb80ccd6e. 

Can confirm I delete things primarily via context menu, and *mostly* (entirely?) what I'm seeing happen is horizontal and vertical walls vanish / are deleted regardless of whether I have selected them or interacted with them during the edit session. 

I'm working on a large project that I had largely completed previously, so I'm not necessarily noticing things disappearing on me because I've been working in select areas and not paying so much attention to the rest of the sub. One does tend to notice when the floor is missing during a test, however!

**Comment by giists** [comment] 2023-07-04 10:40
Seems to be working as it's supposed to. Closing.

**Closed by giists** 2023-07-04 10:40 UTC
Labels: Bug, Code
