### ISSUE TITLE
Docking to a station crashes the game

### ISSUE THREAD

**Issue by TheGoo-ooo** [Regalis11/Barotrauma#1585] opened 2019-06-10 16:52 UTC
**Description**
A the end of a round, in spectator mode (unconfirmed), try docking the submarine. Player models will disapear, lights will shut off and you will be forced to log out and back into the game. Losing the current game.

**Steps To Reproduce**
Most of those steps might not be required to reproduce, but as it is, I have no more information. Every details that might be required to reproduce the bug are provided, logs included.
- Start a salvaging artifact mission
- Send a diving crew to salvage the artifact in the target location
- Get the diving crew infected with the husk on their way back to the ship
- Salvage an artifact, but do not get any messages about going back to base when the artifact is on board (might be an artifact that is not part of the mission). Artifact description: A static rectangle with a rotating rectangle behind it. It floats in the air (unconfirmed) and spawn water (unconfirmed)
- Put the artifact in the ballasts
- Pack the infected crew in a bedroom and weld them off to protect the rest of the crew.
- Enjoy their shout of despair and cries (confirmed).
- Watch them being eaten alive as one transforms.
- Notice a message box pop up: "Cheats activated"
- Go to a station (the one on the right of the map in our case)
- Get intercepted by an endworlm
- Lose most of your crew
- Disable your sonar to not excite it more than it already is
- Die as the captian (you are now in spectator mode)
- Endworm stops attacking the ship (Sonar or not, it went away)
- See your second in charge take over the ship with the few lasting survivors and drive back home
- Watch the ship dock with a horizontal speed that might be too quick to dock.
- Ship bumbs the dock (unconfirmed)
- Game instantly crashes: Player models disapear, lights go off, logs appear
![BT_Docking_Crash_logs](https://user-images.githubusercontent.com/23033543/59211287-ce687280-8baf-11e9-9973-3797d5fa321a.png)

**Version**
Barotrauma v0.9, vanilla (no mods), windows.

**Additional information**
**public server** with a lot of people. It went well, but the crash at the very end really broke the mood. It should be fixed quickly as it might impact the player base quite a lot in critical situations.

**Comment by Regalis11** [comment] 2019-06-10 16:55
Duplicate of #1518, fixed in bea7b58

**Closed by Regalis11** 2019-06-10 16:55 UTC
