### ISSUE TITLE
Lag Issue after Update

### ISSUE THREAD

**Issue by ArdynArden** [Regalis11/Barotrauma#8582] opened 2022-03-23 04:19 UTC
I saw that some screen shots were requested for this issue. So... Here are some screen shots...

![image](https://user-images.githubusercontent.com/71915972/159623031-9d925c45-0ce4-4578-9f66-3fe606cf1130.png)
![image](https://user-images.githubusercontent.com/71915972/159623089-85fb1433-076b-455b-b02c-b9221b020bbc.png)
![image](https://user-images.githubusercontent.com/71915972/159623095-0896e101-92f3-4766-a849-6f13bbb59f6e.png)

It got really bad here:
![image](https://user-images.githubusercontent.com/71915972/159623145-60b247e1-2f5d-48ec-9b2a-69157b6e63f6.png)

**Comment by Regalis11** [comment] 2022-03-24 09:28
Thank you for the help! We only keep one ticket per issue in the issue tracker though, so I'll close this as a duplicate of https://github.com/Regalis11/Barotrauma/issues/8510

**Closed by Regalis11** 2022-03-24 09:28 UTC
