### ISSUE TITLE
Player unable to unlock upper tier perks on server

### ISSUE THREAD

**Issue by DaviesDesmond** [Regalis11/Barotrauma#11632] opened 2023-03-22 00:27 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

One of the players in a campaign I am hosting has been unable to get skills past the first tier. They thought they had to unlock all the skills on the first tier before moving onto the second, so did not mention it originally. They are playing mechanic.

No other players (I think we have 6 or 7 others) in the server are having the problem, including the other mechanic.

I am happy to provide more details, but don't know what is relevant.

### Bug prevalence

Just once

### Version

Other

### -

started sometime in January 2023

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-03-22 18:40
Thank you for the report! I wasn't able to reproduce the issue at my end, so I suspect it requires some more specific circumstances to occur. Something that might help us diagnose the issue is if you could send us the campaign save (including the character data file saved in the same folder)! Thanks and sorry for the inconvenience.

**Comment by DaviesDesmond** [comment] 2023-03-22 18:53
[Save.zip](https://github.com/Regalis11/Barotrauma/files/11043678/Save.zip)
here is the save! it is sobriqu83's character that is having problems.
Reviewing the save, I realized I was incorrect above, our other mechanic has not played enough to get a third point, so I don't know if they are having the same issue.

Thanks

**Comment by Regalis11** [comment] 2023-04-05 14:44
Thank you for the save! I unfortunately still couldn't reproduce the issue. In the save, the character doesn't have any spare talent points, so they cannot unlock any talents from any tier. But after gaining enough experience to get a point, I seem to be able to unlock talents from the 2nd tier with no issues:
![image](https://user-images.githubusercontent.com/14351070/230117009-7756bed6-fa76-4e28-8190-4778aca3e6a8.png)

**Comment by Regalis11** [comment] 2023-05-02 09:23
No known steps to repro, closing

**Closed by Regalis11** 2023-05-02 09:23 UTC
Labels: Bug, Need more info, Code
