### ISSUE TITLE
Crash when clicking Multiplayer menu

### ISSUE THREAD

**Issue by kitrosomyl** [Regalis11/Barotrauma#1751] opened 2019-07-11 09:45 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

[crashreport.log](https://github.com/Regalis11/Barotrauma/files/3381333/crashreport.log)
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/3381334/crashreport.2.log)

**Description**
Sometimes happens when clicking Multiplayer menu but has not occured after freshly launching the game - usually after going through other menus first

**Version**
Game version 0.9.1.0

**Comment by Regalis11** [comment] 2019-07-11 12:03
It seems that something went wrong when trying to sort the server list, but unfortunately I can't figure out what based on the crash reports. Do you by any chance remember what property you had sorted the list based on (e.g. name, compatibility, player count...)?

**Comment by kitrosomyl** [comment] 2019-07-12 00:19
Not sure what server filters i'd used, if any. It happened 3 times in a row yesterday but today I can't seem to reproduce it at all!

**Comment by Rokvach** [comment] 2019-07-13 11:28
Tested, seems to crash if you have one of the columns set to sort, I had Players set to sort by highest player count, after that I spammed the Scan Servers button every time right before it finished to fully load the list and on the third time the game crashed resulting in the same crash report. 

My suggestion would be to not allow spamming the Scan Servers button, so if you hit it you would need to wait for ~5-10 seconds before you can scan the list again.

@Regalis11

**Comment by SagaciousZed** [comment] 2019-07-13 20:20
I've had this happen sorting by ping.

**Comment by Regalis11** [comment] 2019-07-17 07:44
@Rokvach Did you include https://github.com/Regalis11/Barotrauma-development/commit/db4af0b0dc2cac0c05d776c71f8161714e3a07ea when testing, and if so, could you post the crash report?

**Comment by Rokvach** [comment] 2019-07-17 08:11
It does seem that the issue has been fixed now as I couldn't reproduce it with the latest fixes. Closing.

**Closed by Rokvach** 2019-07-17 08:11 UTC
Labels: Bug, Code, Crash
