### ISSUE TITLE
Sending text from radio to wifi in MP

### ISSUE THREAD

**Issue by bavarianblacksmith** [Regalis11/Barotrauma#3337] opened 2020-07-09 22:34 UTC
- [X ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In MP, cannot send a text radio message to wifi.

Works in SP with both the default headset and a headset set to "link to chat". Wifi components are also marked "link to chat".

**Steps To Reproduce**
[In MP] Hook wifi (out)(channel 1) > terminal (in)

**Version**
0.9.10, Windows 10.

**Additional information**
NA

**Comment by Regalis11** [comment] 2020-07-10 07:51
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3172, fixed in the Unstable branch

**Closed by Regalis11** 2020-07-10 07:51 UTC
