### ISSUE TITLE
[MASSIVE BUG] - Banning any player on dedicated server bans all players permanantly

### ISSUE THREAD

**Issue by EricPfau** [Regalis11/Barotrauma#4163] opened 2020-10-30 01:55 UTC
- [Y ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Banning anyone in a dedicated server, bans all players even admins, and no one can join. Can only be fixed by deleting entry from ban list manually

**Steps To Reproduce**
Ban any player while running a dedicated server and every player will be banned and kicked.

**Version**
10.6.2 - Stable

**Comment by EricPfau** [comment] 2020-10-30 01:56
Game is currently unplayable with this bug, shutting down our dedicated server until this is fixed. Utterly unplayable. I know this is a duplicate, but the problem still exists.

**Comment by EricPfau** [comment] 2020-10-30 03:17
Feel free to ask me and I can demonstrate this via video if needed.

**Comment by Regalis11** [comment] 2020-10-30 11:35
Damn, looks like my guess on what was causing this (#3895) was wrong. Thank you for the report!

I'm afraid I still wasn't able to reproduce the bug though, so some more info would be much appreciated. Are you hosting using the DedicatedServer.exe included with the game, or with the separate server application that's installed via SteamCMD? How exactly are you banning the players (console commands, via the UI as a client who has the permission to ban people)?

**Comment by EricPfau** [comment] 2020-10-30 23:16
I will do some more thorough testing and get back to you on this one. Currently it was via SteamCMD, via ingame ui, and people over the internet. Let me test a few scenarios (running dedicatedserver.exe, commands etc..) and I will give you a thorough summary of our findings.

**Comment by TheWeebsters** [comment] 2020-10-31 03:54
I am having the same issue, was streaming the game today and went to ban someone that was killing for no reason. I banned him and the rest of the people in the server got banned as well. I was running the server via powershell and banned him using the in game UI. 
![unknown](https://user-images.githubusercontent.com/73730093/97770602-bf24f480-1b17-11eb-8462-34b6b6274502.png) I will do my best to provide anymore information. I can also attach a twitch clip of it happening.

**Comment by EricPfau** [comment] 2020-10-31 21:05
Further testing was performed. Results shown below.
Version: Stable 0.10.6.2


*Server running on external computer using SteamCMD server.*

1. From the game lobby, banned a player using the in game UI as an Admin rank(Left-click on player name then hit Ban).
Results: The player and myself were both banned. Ban message displayed to both of us. Player was over internet and not local connection. Neither of us can rejoin server and ban list had to be deleted to fix.

2. From the game lobby, banned a player using the debug console (F3 then typed ban "PLAYERNAME").
Result: The player and myself were both banned. Ban messages SLIGHTLY different see screenshots below.


*Server running using in game Hosting p2p*

1. From game lobby, ban using UI as Admin Rank.
Result: Only the banned player was banned and kicked

2. From game lobby, ban player using debug console.
Result: Only the banned player was banned and kicked


*Server running using dedicatedserver.exe on local computer.*

1. From game lobby, ban using UI as Admin rank.
Result: Both myself and player were banned and kicked from game. Player was over internet and not local to host machine.

2. From game lobby, ban player using debug console.
Result: Both myself and player were banned and kicked from game. Player was over internet and not local to host machine.


*Conclusion*
Problem only appears on dedicatedserver.exe and SteamCMD server. P2P works as intended without issue.

**Comment by EricPfau** [comment] 2020-10-31 21:06
![Banned](https://user-images.githubusercontent.com/73270156/97790007-731b9380-1b9b-11eb-9976-8af3f2d0f074.png)
![bandebug](https://user-images.githubusercontent.com/73270156/97790009-74e55700-1b9b-11eb-9c9c-9bc0064d8d59.PNG)

**Comment by juanjp600** [comment] 2020-11-02 13:37
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/caf810b98991fad3e4ad841fbdaafb1aab8e170f

**Comment by Rokvach** [comment] 2020-11-02 13:41
Tested, working correctly. Closing.

**Closed by Rokvach** 2020-11-02 13:41 UTC
Labels: Bug, Code, Networking
