### ISSUE TITLE
(unstable) bot traps you in chat with begining quest in singleplayer

### ISSUE THREAD

**Issue by sroxl** [Regalis11/Barotrauma#10359] opened 2022-11-12 21:20 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

it seams like the bot in single player wont stop giving you the get supplies quest

### Reproduction steps

1 start single player
2 bot talks to you and traps you in chat

### Bug prevalence

Happens every time I play

### Version

0.20.5.0 (Unstable)

### -

n/a

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
no crash to report
```

**Comment by Regalis11** [comment] 2022-11-13 11:02
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10320

**Closed by Regalis11** 2022-11-13 11:02 UTC
