### ISSUE TITLE
[Crash Report] Anti-Virus - 12 Avril 2020 - 16h30

### ISSUE THREAD

**Issue by Ant1V1RU5** [Regalis11/Barotrauma#2621] opened 2020-04-12 14:36 UTC
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/4466479/crashreport.log)

**Comment by Regalis11** [comment] 2020-04-13 11:44
Duplicate of #2533

**Closed by Regalis11** 2020-04-13 11:44 UTC
