### ISSUE TITLE
research station broken cannot fix

### ISSUE THREAD

**Issue by L2PGaming** [Regalis11/Barotrauma#9053] opened 2022-05-03 06:49 UTC
i have a research station on my sub. it got damaged from an explosive and it cannot be repaired with any tools. in addition when i tell bots to fix things on the sub they spam me every 10-20 seconds with cant find tools to do the repairs  message. its creating some lag.

**Comment by Regalis11** [comment] 2022-05-03 07:16
I'm afraid I could not reproduce this in the vanilla subs. I wonder if the repair tool has been configured incorrectly for the research station in your sub? You might want to check that the "equipped required" field under "repairable" has been set to "screwdriver".
![image](https://user-images.githubusercontent.com/14351070/166416635-dce74ddc-390e-4fdc-b9b9-185664b2c088.png)

**Comment by L2PGaming** [comment] 2022-05-03 13:52
its a workshop sub dreadnaught 2.2 says vanilla i dont know how to check equipped required field
![image](https://user-images.githubusercontent.com/104820060/166464573-cba60190-0689-4d17-a173-6f10f149f9af.png) 
![image](https://user-images.githubusercontent.com/104820060/166465397-395a10fc-3736-4f44-b29b-cd0bced97fae.png)
![image](https://user-images.githubusercontent.com/104820060/166465968-0be3a391-7964-4794-8d9e-402250465255.png)

**Comment by Regalis11** [comment] 2022-05-04 08:20
> You can edit a sub in an existing save, but it's extremely difficult to do so

Not necessarily: it should be possible to switch to the submarine editor using the console command `editsubs`, change the value, and then go back in-game using the command `game`.

**Comment by Regalis11** [comment] 2022-05-04 08:21
Anyhow, I'll close this since it appears to be an issue with a custom sub.

**Closed by Regalis11** 2022-05-04 08:21 UTC
Labels: Bug, Need more info, Code
