### ISSUE TITLE
[0.13.0.11] Main menu half obscured on initial load

### ISSUE THREAD

**Issue by Ziechael** [Regalis11/Barotrauma#5597] opened 2021-04-24 12:14 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Since the update, when I first load the game the main menu is obscured from above 'customize'. My mouse cursor disappears behind the background that area too.
If I enter the sub editor etc and then return to the main menu the issue is resolved.

**Steps To Reproduce**
This has happened consistently every time I load the game since the latest update (Embrace the Abyss)

**Version**
v0.13.0.11 (ReleaseMac, branch release, revision 840b932557) - Automatic updates enabled in steam
Mac OS 10.14.6

**Additional information**
<img width="1680" alt="Screen Shot 2021-04-24 at 12 55 19 PM" src="https://user-images.githubusercontent.com/11630410/115958343-fdb3ce80-a4fe-11eb-95e3-55fe1f1b50f2.png">

**Comment by juanjp600** [comment] 2022-11-14 16:50
I've had trouble reproducing this issue locally. However, I did find something that seemed incorrect in our viewport handling cod. This should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/95d74739769ed1544156a8d697834160102f2669

**Comment by Rokvach** [comment] 2022-12-01 09:15
I haven't spotted anything out of the ordinary after the fix so this seems to be working correctly, closing.

**Closed by Rokvach** 2022-12-01 09:15 UTC
Labels: Bug, Code, Mac only, Unstable

**Comment by Wheatley1001** [comment] 2023-03-13 21:14
Hello everyone! This issue seems to have resurfaced in 1.0.7.0 in an unusual way. I'm documenting another user's experience.

The device they use is a 2019 Macbook Pro, running Catalina. Its resolution is 3072x1920. Loading the game produces the following images, with content outside of the bottom left square flickering constantly. Additionally, entering the submarine editor causes other weird visual artifacting.

![image](https://user-images.githubusercontent.com/105495756/224833498-cd050b4d-61df-422a-b63e-a42c9a022926.png)
![image](https://user-images.githubusercontent.com/105495756/224833559-8e3f9fb5-5e27-48f2-ab94-e0bb1a0b995d.png)
![image](https://user-images.githubusercontent.com/105495756/224833576-a4b005b3-2717-48da-9c2b-485b9ca35d21.png)
![image](https://user-images.githubusercontent.com/105495756/224833614-84f567dd-0e44-415c-9255-8c75530cc991.png)
![image](https://user-images.githubusercontent.com/105495756/224833636-c727daec-fff4-425f-8cb5-f61f455dbb2e.png)
![image](https://user-images.githubusercontent.com/105495756/224833654-bdcebb8f-ee7a-48c5-b1b4-e24c3aaaf971.png)
