### ISSUE TITLE
Crash when joining servers (this platform does not support packet information for dual-mode sockets)

### ISSUE THREAD

**Issue by aur3l14no** [Regalis11/Barotrauma#6190] opened 2021-06-27 08:59 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I'm on the latest version of Barotrauma on mac, and whenever I join the server it displays the usual "Joining [Insert Servername]," waits 8-10 seconds, and just completely crashes. Every time. Any fix for this?

(same as https://www.reddit.com/r/Barotrauma/comments/hbsv36/game_crashes_upon_joining_server_mac/)

**Version**
Mac.

**Additional information**
I tried local dedicated server and public servers. Same problem!

**Comment by chips5k** [comment] 2021-06-27 10:35
Having similar issue - i am running a dedicated server on ubuntu via https://linuxgsm.com/lgsm/btserver/ and anyone on a mac crashes after about 8-10 seconds of the connecting popup.

Connections from non mac machines work fine however - e.g my windows machine connects with no issues.

Let me know if i can provide any additional info.

**Comment by aur3l14no** [comment] 2021-06-27 13:16
> Note when Mac users host the game, other mac users are able to join - not sure if that helps with debugging, so thought i would mention.

How did you host the game on Mac? Was it a dedicated server?

**Comment by chips5k** [comment] 2021-06-27 23:22
> > Note when Mac users host the game, other mac users are able to join - not sure if that helps with debugging, so thought i would mention.
> 
> How did you host the game on Mac? Was it a dedicated server?

nope not dedicated. Just created it in game via the host options and then invited friends.

**Comment by chips5k** [comment] 2021-06-27 23:24
There is a chance its caused by this: 
![Screen_Shot_2021-06-27_at_8 59 00_pm](https://user-images.githubusercontent.com/419273/123562507-7894b080-d7f2-11eb-8640-c3109b45b45c.png)

I noticed that in the background after i exited.... i will confirm soon if perhaps that was the issue

**Comment by aur3l14no** [comment] 2021-06-28 05:45
I don't think hosting in-game have this problem whether it's pc -> mac or mac -> pc. For me it's a dedicate-server-exclusive issue.

I want to use dedicated server instead of in-game hosting because when I run dedicated server (with hole-punching), I get around <40 ping but sometimes 400+ with in-game hosting (steamP2P takes care of hole-punching but it turns out unreliable for me).

Also I gave Barotrauma that permission but the problem still rises.

**Comment by chips5k** [comment] 2021-06-28 05:48
ah nps good to know its not the permission issue

**Comment by jesse-savary** [comment] 2021-06-29 00:50
Started hacking away at Barotrauma locally to try and fix this issue. You can prevent your client from crashing by changing `usedualmodesockets` to `false` inside `config_player.xml`

The exception that is thrown is: ```
Unhandled exception. System.PlatformNotSupportedException: This platform does not support packet information for dual-mode sockets.  If packet information is not required, use Socket.Receive.  If packet information is required set Socket.DualMode to false.
```

Disabling DualMode does not allow MacOS to connect but at least you won't crash out entirely.

**Comment by BurningMadness** [comment] 2021-11-29 13:26
Has anyone found a workaround yet ? (That allow connection)

**Comment by nirnx** [comment] 2022-01-21 00:43
Hello, 

I did a little investigation and as mentioned above `usedualmodesockets` setting to `false` is not crashing Barotrauma but the connection to the server is not working because Barotrauma is listening on a socket using ipv6 instead of ipv4

tcpdump
```
01:34:40.620169 IP 10.10.10.10.27015 > 20.20.20.20.58091: UDP, length 67
01:34:40.620369 IP 20.20.20.20 > 10.10.10.10: ICMP 172.27.1.20 udp port 58091 unreachable, length 36
```

lsof
`Barotraum 12734 username  267u  IPv6 0x1fa79f30e84ad7a9      0t0  UDP *:58091`

**Comment by left0077** [comment] 2022-05-02 15:18
I change the Lidgren to [lastest version](https://github.com/lidgren/lidgren-network-gen3/tree/master/Lidgren.Network). And it works well.

**Comment by NamesAreAPain** [comment] 2022-05-06 02:39
@left0077 The repo you linked isn't cross compatible with the version that Barotrauma is using. It has no UseDualModeSockets property, which the configuration for Barotrauma calls the setter of. What exactly did you do to get it working?

**Comment by left0077** [comment] 2022-05-06 05:34
@NamesAreAPain I add the `public bool UseDualModeSockets` function in `NetPeerConfiguration.cs` like [this](https://github.com/Regalis11/Barotrauma/blob/c454c4e2d53aa63b954aa21e5ddbe6be1349c3f1/Libraries/Lidgren.Network/NetPeerConfiguration.cs#L145). And  change ` m_configuration.DualStack` to `m_configuration.UseDualModeSockets` in [this line](https://github.com/lidgren/lidgren-network-gen3/blob/f99b006d9af8a9a230ba7c5ce0320fc727ebae0c/Lidgren.Network/NetPeer.Internal.cs#L135). After build I get `Lidgren.NetStandard.dll` and `Lidgren.NetStandard.pdb`. I copy these files to the Steam version Barotrauma folder. These are my build files: [Lidgren.NetStandard.zip](https://github.com/Regalis11/Barotrauma/files/8637761/Lidgren.NetStandard.zip).
All test based on M1 mac with ipv4 network.

**Comment by Riking27** [comment] 2022-05-07 02:19
@left0077 These build files worked for me on OSX 11! Thanks!
@Regalis11 This might be the fix.

**Comment by ghost1656** [comment] 2022-05-09 11:40
@left0077 Do you know where I can find the NetPeerConfiguration.cs file? It is not in any of the Barotrauma files on my Mac.

**Comment by Regalis11** [comment] 2023-04-13 13:39
Finally got around to fixing this. Should be addressed in https://github.com/Regalis11/Barotrauma-development/commit/48a963d569839525e2ad974fb3c2bbfc2a8c093d (commit in our private repo)

**Closed** 2023-06-20 16:09 UTC
Labels: Bug, Code, Networking, Mac only
