### ISSUE TITLE
[Unstable 0.15.18.0] Attached harpoons vanish when bot/player heals

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#7656] opened 2021-12-07 07:57 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Once the affliction caused by the attached harpoon gets healed the harpoon vanishes, I'd expect the harpoon to either drop to the ground or be placed on the inventory of the attached character

**Steps To Reproduce**
Shoot a bot and wait for them to heal, notice that the harpoon vanishes

**Version**
Unstable 0.15.18.0

**Comment by Regalis11** [comment] 2021-12-07 10:02
I couldn't find a way to repro this. I can't think of how it could be possible either: the projectile should know nothing about the character's afflictions. So I suspect this was caused by something else that just happened to coincide with the healing, but I couldn't figure out what.

**Comment by Regalis11** [comment] 2022-01-18 08:54
No known steps to repro, closing

**Closed by Regalis11** 2022-01-18 08:54 UTC
Labels: Bug, Need more info, Code, Low prio
