### ISSUE TITLE
Object reference not set to an instance of an object. (System.NullReferenceException)

### ISSUE THREAD

**Issue by Caeures** [Regalis11/Barotrauma#7677] opened 2021-12-08 17:05 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.
```
Game version 0.15.13.0 (ReleaseWindows, branch release, revision 4e66dd7b5d)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: Traditional Chinese
Selected content packages: Vanilla 0.9, Pet Mudraptor, TransparentDivingHelmet, GunLights Remade, 100x Stack, BaroPlus, EuropaWaifu+BetterHuman and anime sound, VisualVarietyPack, New Wrecks For Barotrauma, Survivator Play Creatures, Unicorn, Hoplophilia, Lootbelt, [AP] Sakala, Shipwrecks Extended, CrouchHarder, Matilda, [BOS]中文优化, Cat, ALIEN - XENOMORPH, EK Dockyard, EK Utilities, Coufsure, AR5S A.I.Standard, Peregrine, Humpback Caeures Mod. A1, [AP] Bohr, Evaporator, PlagueRat, Apo-4A Saber, [VH] The Iroh, UAV TYPE-Peace, Apo-3A Dagger, [AI] Desert Fox, Pirates of the European , Jörmungandr, combine city RP  City 15 V4.7, DisconnectKillAndStunRemover, HL-250, Europa Clock, The Boxer, Timid's Beacon Stations, Backpacks, MMDTDACharacters, [ENV] Beacons Extended, 遺物袋補丁, R27 voyager 远行者, Polyp, Shreksophone, EuropaWaifu, SIN Beacon Stations, U-3506, 登陆艇, 小雀, Vanilla A40 (Thick2.0), Mining Laser, Universal Elevator Test Track, oClockRadar_Alt, Bots load railgun, “信念”级 轻型潜艇 [Faith-class], CV Quasar-I, Iron Coffin v4, [PB]Egregore, Vanilla A40, Semipalatinsk, FIR Female New Face, Anime Poster Pack, [BOS]Box-青果盒, 蓝色空间, AetheR Class 117, Music from beyond, EBIKKO Mk-III, Posters, 疫鼠, Yangtze-31 1.0.0, A-36 Setembrino, Мощь 11 стволов, IMC BEACON A-27, EK_Berith_Mk-II, Warhammer - Commissar outfit, Warhammer - Cadian armor, Warhammer - Bolt Pistol, Sweet Pea, I-69, Ulysses, [CN] Destroyer-Class SSN (carry drone), Ussr, The Stoick, Project 941 'Akula', No Role Balance, Krakenjäger, Gawr Gura, Bigger Railgun Racks, Albifrons, abyss
Level seed: TaraYelland Linea
Loaded submarine: 小雀-II型4.12 (BF39152DB7D14E55D09AECCA250E6D17)
Selected screen: Barotrauma.GameScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.19041.0 64 bit
    GPU name: NVIDIA GeForce GTX 1060
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Microsoft.Xna.Framework.Vector2 GetSteeringVelocity(Microsoft.Xna.Framework.Vector2, Single)
Stack trace: 
   at Barotrauma.Items.Components.Steering.GetSteeringVelocity(Vector2 worldPosition, Single slowdownAmount) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Machines\Steering.cs:line 694
   at Barotrauma.Items.Components.Steering.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Machines\Steering.cs:line 384
   at Barotrauma.Item.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 1662
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 567
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 264
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 981
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 60
```

**Description**
Everytime I fight with pirate ship in this map with close range will crash.

**Steps To Reproduce**
I not really sure how to repoduce, but I've try several time. Once I encounter pirate ship with close range, the game will crash. It never happened before.

**Version**

Game version 0.15.13.0 (ReleaseWindows, branch release, revision 4e66dd7b5d)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: Traditional Chinese

System info:
    Operating system: Microsoft Windows NT 10.0.19041.0 64 bit
    GPU name: NVIDIA GeForce GTX 1060
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

**Additional information**

**Comment by Regalis11** [comment] 2021-12-08 17:31
Thank you for the report!

Looking at the crash report, this seems to be caused by the bots trying to use a navigation terminal that's not controlling any submarine (possibly a terminal that's been wired incorrectly?). I think it's probably caused by one of the mods you're using, so if you can figure out which of those mods the pirate sub you encountered was from, disabling that mod might help you work around the problem for now.

Fixed the issue in https://github.com/Regalis11/Barotrauma-development/commit/ee50ed0298eca23627a4c65e402c909e27965152 ()

**Comment by Caeures** [comment] 2021-12-08 17:48
Yes, you are right.
I've dismount this mod " Pirates of the European" , and everythings are fine. I think that modded Kastrull is the problem.
Thanks for your answer.

**Comment by Rokvach** [comment] 2022-01-04 12:04
Tested, working correctly. Closing.

**Closed by Rokvach** 2022-01-04 12:04 UTC
Labels: Bug, Code, Crash, Modding
