### ISSUE TITLE
Crash Report [unstable]

### ISSUE THREAD

**Issue by NyarlathotepZERO** [Regalis11/Barotrauma#4258] opened 2020-11-08 23:36 UTC
Crash occurred just as I had finished killing a bunch of crawlers with the gunner on the belly cannon. The precise moment it happened was when I rapidly used the shortcut key to move down through the list of NPC to get back to the captain, passing by the medic. (order was: gunner>medic>captain).

Medic was tasked with welding leaks, not sure if that had anything to do with it though.

Sub edit is nothing huge, mainly cost, addition of medfab and deconstructor, additional storage etc. Can give a complete list if needed.

[crashreport.log](https://github.com/Regalis11/Barotrauma/files/5507358/crashreport.log)

**Comment by itchyOwl** [comment] 2020-11-09 10:23
The crass was due to a null reference exception in the latching behavior (crawlers). I couldn't reproduce the issue, but I added some null checks and refactored the code (Regalis11/Barotrauma-development@3e8bab5). The crash might be caused by the changes in Regalis11/Barotrauma-development@5e22366.

**Comment by Rokvach** [comment] 2020-11-11 14:20
No issues, closing.

**Closed by Rokvach** 2020-11-11 14:20 UTC
Labels: Bug, Code, Crash
