### ISSUE TITLE
After crash  I see "Submarine equality check failed". And this error too

### ISSUE THREAD

**Issue by dawideka1221** [Regalis11/Barotrauma#6176] opened 2021-06-25 16:57 UTC

**Comment by Regalis11** [comment] 2021-07-05 10:30
This seems to be a duplicate of https://github.com/Regalis11/Barotrauma/issues/6159

**Comment by Regalis11** [comment] 2021-07-05 10:44
Nvm, the previous ticket was closed, reopening this one

**Comment by Regalis11** [comment] 2021-11-15 13:09
Possibly fixed in Regalis11/Barotrauma-development@269ca20

**Comment by Rokvach** [comment] 2021-11-29 12:38
There hasn't been any encounters to this still happening in the Unstable build, seems to be working correctly. Closing.

**Closed by Rokvach** 2021-11-29 12:38 UTC
Labels: Bug, Needs testing, Code, Networking
