### ISSUE TITLE
Water splash - parasite copy

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#9643] opened 2022-07-25 18:52 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Water spatter from the character’s feet near the ladder is duplicated at below level.
![20220725_214020 mp4_snapshot_00 21 242](https://user-images.githubusercontent.com/93348499/180851839-43813f0b-79f4-4b0b-bfdd-37a3e1d55731.jpg)

### Reproduction steps

1. Start editor
2. Use my test chamber: [_Test-Parasite water splash.zip](https://github.com/Regalis11/Barotrauma/files/9184014/_Test-Parasite.water.splash.zip)
3. Do the same as in the video
4. Standing next to the ladder keep the key `arrow down`
5. The ladder is a mandatory condition!

https://user-images.githubusercontent.com/93348499/180854700-ef5b74a4-31e7-4fd2-a267-6a39b2e18392.mp4

### Bug prevalence

Happens every time I play

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by NilanthAnimosus** [comment] 2022-07-28 12:25
Tested this quickly, it appears it occurs because the hull is extremely close to the hatch - enough so that the feet of the character can touch the next hull just sliding down the ladder (with their feet)

![image](https://user-images.githubusercontent.com/29177976/181504387-f5080c37-dacf-49a4-8d6c-f587f13be0ae.png)

curiously, the splash occurs when entering and exiting the hull - and not around the water level of the hull, perhaps because of the information related to the character that is in water in the current hull?

**Comment by MaaiG** [comment] 2022-07-28 13:09
> Personally, I don't think this hull should be so high that it is almost past the hatch itself between the two hulls, but this configuration does "work" in the sense that water transfers between the hulls when the hatch opens and such.

You mean hull should be like this?
![Image 001_15-31](https://user-images.githubusercontent.com/93348499/181509292-58bdcdb2-a84c-4879-bcf3-af35d9630cb3.png)

These are vanilla submarines:
![Image 001_15-50](https://user-images.githubusercontent.com/93348499/181509526-4363a064-614e-4e2a-bd15-9b7edd86066f.png)

This is done so that all the water from the compartment is pumped out if the pump is operated by a water detector!
1. Pump - power is off if it does not work!
2. The pump is activated when a signal is received from the water detector!

If the hull is lower, there will be more water in the compartment!
You can try this: 
[_Test-Parasite water splash V2.zip](https://github.com/Regalis11/Barotrauma/files/9209890/_Test-Parasite.water.splash.V2.zip)

https://user-images.githubusercontent.com/93348499/181512773-d58aa4f1-b766-40cd-9d1b-abce8ba82465.mp4

**Comment by NilanthAnimosus** [comment] 2022-07-28 13:26
I still consider it to be a bug that the splash is duplicated when the character is not touching the water itself in the other hull simply from a few pixels of a foot touching the very top of the hull.

but character ragdolls do slightly pass through other objects at high speeds (like the foot moving on the ladder passing through by a few pixels to touch that hull) and was more an observation on why this is occuring, its not strictly tied to the ladder but the fact the ragdoll manages to touch the other hull at the same time.

**Comment by MaaiG** [comment] 2022-07-28 13:53
> character ragdolls do slightly pass through other objects at high speeds

😁 [Yea, very high speed!](https://github.com/Regalis11/Barotrauma/issues/7635)!

> And yes, this is probably an issue on some (or most) vanilla submarine designs.

I think it’s a pressing need now.
The problem is that water fills the walls inside the housing! Water fills the entire area of the housing.
![Image 002_16-43](https://user-images.githubusercontent.com/93348499/181521858-b2ec53ee-d5c8-48aa-8349-41529d44b722.png)

**Comment by NilanthAnimosus** [comment] 2022-07-28 15:05
On one hand if their not touching enough - then its essentially going to make gaps flood the interior like it is the ocean, on the other hand it would be too complicated of a matter (to my understanding) to fix this issue by making hull's reactive to the size of the room based on any combination of wall/floor pieces, shapes and sizes.

its also complicated to have any none-rectangular hulls and likely not worth it vs the code complexity and performance it might require. I think its been discussed in the past.

Fixing the issue of splashes when a character intersects two hulls but the water on only one is a more ideal solution I think. and you should design the submarine where you want your hulls to go. this issue may be fixed at some point when the developers have time but in the meantime there is no strictly wrong way about setting up the hull's.

**Comment by MaaiG** [comment] 2022-07-29 19:19
@NilanthAnimosus Similar effect but different situation! Maybe this is another bug.

Water drainage through a twinned hatch that opens in different directions:
![Image 001_21-48](https://user-images.githubusercontent.com/93348499/181825285-d138acd6-93e3-4018-8c2b-e599f82eb96f.png)
Splash upwards when draining water - double hatch.
![Image 001_21-54](https://user-images.githubusercontent.com/93348499/181828915-6708ed16-f1c5-4429-b35f-fb2506a0fff7.png)
Teat chamber: [_Test-DoubleH splash.zip](https://github.com/Regalis11/Barotrauma/files/9222721/_Test-DoubleH.splash.zip)

**Comment by Regalis11** [comment] 2022-08-18 09:07
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0b86adbd1228c63584c474d04bf888119221949e

The splash particles are created when a limb leaves or enters water. In this case, the feet entered the hull below, making them leave water, which caused water particles to be emitted at the surface of the water `in the limb's current hull`.

**Comment by Rokvach** [comment] 2022-08-24 21:44
Tested, wasn't able to reproduce the issue after the fix, working correctly. Closing.

**Closed by Rokvach** 2022-08-24 21:44 UTC
Labels: Bug, Code, Unstable
