### ISSUE TITLE
Outpost Nuclear Reactor cannot hold Volatile Fulgarium Fuel Rods

### ISSUE THREAD

**Issue by Thutmose** [Regalis11/Barotrauma#7332] opened 2021-11-16 04:04 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Volatile Fulgarium Fuel Rods cannot be placed inside the second (larger normally) type of reactor

**Steps To Reproduce**
Place one of those reactors in a ship in the sub editor, and then attempt to place a Volatile Fulgarium Fuel Rod inside it, you get a sad noise instead of placing. Then also try pressing the Test button and placing from there, same sad noise.

**Version**
v0.15.13.0 (ReleaseWindows, branch release, revision 4e66dd7b5d)

**Additional information**
I was attempting to build a different design of reactor room, centered around a resized (and lowered power output) outpost reactor. When testing safety with volatile rods, I was unable to place them inside.

I tested with the below setup, consisting of the reactor, some buttons/levers, and oxygen so the room lasted long enough to sink during testing.

![wikiimage](https://user-images.githubusercontent.com/2363472/141900880-af5133c1-cbec-4619-9e4a-ba417c27f7ba.png)

**Comment by Regalis11** [comment] 2021-11-16 08:48
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7193

**Closed by Regalis11** 2021-11-16 08:48 UTC

**Comment by Thutmose** [comment] 2021-11-16 14:21
Ahh, I see, the search I did didn't include closed issues...
