### ISSUE TITLE
some problems

### ISSUE THREAD

**Issue by HawkingHan** [Regalis11/Barotrauma#6437] opened 2021-08-18 13:05 UTC
-站点里应该有医疗工作台
-紧急避险时借用前哨站潜水服或者氧气瓶不应视为偷窃
-局内修改电路会导致电路暂时运行失误（我在Berilia上将四个电池的能源输入和输出对调，刚连到总接线盒上，而且连线与充电速率完全一样时，会先出现两个电池充电两个电池放电的情况，两两一组轮流充电放电，但是在完全充满一次后四电池恢复同步）

**Comment by Regalis11** [comment] 2021-08-19 08:19
Hello and thank you for the report! Unfortunately no-one in the development team speaks Chinese, so I had to rely on Google Translate.

The first two points are closer to feature requests than bug reports imo, and we generally only use the issue tracker for bug reports. I'm unfortunately not entirely sure I understood the 3rd issue because the translation is a bit clunky, but I believe it may be a duplicate of (or related to) the following issue reports: 
https://github.com/Regalis11/Barotrauma/issues/3566
https://github.com/Regalis11/Barotrauma/issues/4571

**Closed by Regalis11** 2021-08-19 08:19 UTC
