### ISSUE TITLE
[0.9.7.1] Modded - Crashed during session, but no one else did.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2375] opened 2020-02-28 22:13 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Was playing normally and all of a sudden crashed. No one else in the server crashed. May have been right before monsters were going to spawn.
[crashreport (4).log](https://github.com/Regalis11/Barotrauma/files/4269330/crashreport.4.log)

**Version**
0.9.7.1

**Comment by Regalis11** [comment] 2020-03-01 14:42
Based on the crash report, this seemed to be caused by highlighted sub inventory slots being modified while in the process of drawing a sub inventory. I could not find a way to reproduce the issue, but added a fix in https://github.com/Regalis11/Barotrauma-development/commit/e9995f8c20af9de3d10ec5863453420332ed596e that should prevent the game from crashing when this occurs.

**Comment by Rokvach** [comment] 2020-03-22 11:54
Closing as there is no clear way of testing this and there hasn't been any new sightings on the Unstable builds.

**Closed by Rokvach** 2020-03-22 11:54 UTC
Labels: Bug, Code, Crash
