### ISSUE TITLE
Relays still fry instantly based on the junctions behind them not power transferred

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#301] opened 2018-03-01 12:57 UTC
version 0.8.0.4

I was confused noticing this in multiplayer, as a player whom has severe issues seeing in the dark anymore as my screen is a little darker than most. then I realized the subs power was on, but I couldn't see.

I checked the relays and - they were all fried, and only connected to relays. so I hopped onto hosting a server using unmodified 0.8.0.4 and dewiring a relay so it only had input power from a junction and no output power (Before it was 5 wires, in this case it was a relay on the W-Class Schonhardt von Stuggart)

And it immediately burned out once it hit 1000 where it should have been transferring nothing at all.

I believe this needs to be looked into further in some form, its definately not behaving as intended otherwise the general rule now is a relay cannot connect to the main grid.

**Comment by Regalis11** [comment] 2018-03-05 10:45
I think this is now fixed. The framerate issues mentioned in your comment e15fad6 are caused by lighting recalculations caused by opening/closing the doors, should not related to the power transfer system.

**Closed by Regalis11** 2018-03-05 10:45 UTC
Labels: bug
