### ISSUE TITLE
[0.1002.0.0] Chairs

### ISSUE THREAD

**Issue by rav2n** [Regalis11/Barotrauma#3031] opened 2020-06-09 16:15 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you try to interact with the terminal or with the periscope, the character gets up from the chair. It would be logical if this did not happen and you could interact with the devices while sitting.

**Version**
0.1002.0.0

**Comment by Regalis11** [comment] 2020-06-09 16:33
Duplicate of #3027 and #1933

**Closed by Regalis11** 2020-06-09 16:33 UTC
