### ISSUE TITLE
Crashes after taking artefact after restart

### ISSUE THREAD

**Issue by BIshounen** [Regalis11/Barotrauma#2843] opened 2020-05-15 19:28 UTC
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/4636737/crashreport.2.log)
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Game crashes after taking artefact after restarting a mission

**Steps To Reproduce**

1. Started an artefact mission (single player)
1. Got an artefact (thermal artefact) in ruins
1. Got it to sub
1. Burned alive because of it
1. Restarted mission
1. Go to artefact holder
1. No flames now (maybe no artefact in holder too)
1. Clicking on artefact holder 100% crashes a game

**Version**
0.9.9.1 Win7 x64

**Additional information**
log and savegame attached
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/4636775/crashreport.2.log)
[Save 0.zip](https://github.com/Regalis11/Barotrauma/files/4636779/Save.0.zip)

**Comment by Regalis11** [comment] 2020-05-17 13:12
Couldn't find a way to reproduce this or diagnose the underlying issue, but I added some checks in https://github.com/Regalis11/Barotrauma-development/commit/ecb5c20f20def6b2efdbb1b315873efa6e3b8601 that should prevent the game from crashing and just log an error when this occurs.

**Comment by Regalis11** [comment] 2020-05-17 16:33
Oh, and looks like there's already a similar ticket in the issue tracker. Closing as a duplicate of #2727

**Closed by Regalis11** 2020-05-17 16:33 UTC
Labels: Bug, Code, Crash
