### ISSUE TITLE
Strange Crash I can't make sense of

### ISSUE THREAD

**Issue by Richiebattags** [Regalis11/Barotrauma#2872] opened 2020-05-20 20:18 UTC
I looked and didnt see another crash report matching this. After being in game a fair couple of minutes I get this crash report, same every time. It just started happening today and all files are verified and up to date. I attached all three just in case there is a slight difference, but I dont see one.
[crashreport (5).log](https://github.com/Regalis11/Barotrauma/files/4659069/crashreport.5.log)
[crashreport (6).log](https://github.com/Regalis11/Barotrauma/files/4659070/crashreport.6.log)
[crashreport (7).log](https://github.com/Regalis11/Barotrauma/files/4659071/crashreport.7.log)

**Comment by Regalis11** [comment] 2020-05-21 08:04
These crash logs could've been caused by a particle that has no sprites defined in the particle config file, in particular some particle effect emitted by some kind of a repair tool.

I would guess that one of the mods you have installed is causing this, as we haven't gotten any similar reports from the vanilla game. 

We've added some extra checks to prevent invalid particle configs from crashing the game, but they're not included in the public version yet, so for the time being I'd recommend disabling some of the mods and seeing if that helps.

There's also another similar ticket in the tracker (#2830): that seemed to happen in a slightly different way but the underlying cause appears to be the same, so I think we can close this one.

**Closed** 2020-05-21 08:04 UTC
Labels: Bug, Code, Crash, Duplicate
