### ISSUE TITLE
[Bug] config.xml reset every time update rolls around

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1206] opened 2019-03-03 23:36 UTC
Self explanitory title. On Linux at least (probably on Windows too), config.xml is wiped and reset. 

At the moment this could just be because there are new settings added frequently to the game. But it would be nice if it didn't reset since the resolution is usually bigger than my screen (720p pleb) and I have to manually change it in config.xml.

**Comment by CommanderMark** [comment] 2019-03-03 23:39
Starting from the current Steam release this was fixed.

Duplicate of #1086.

**Comment by hubismal** [comment] 2019-03-03 23:48
I searched up config like an idiot instead of settings. This might've happened because I was downgraded instead of upgraded lol.

**Closed** 2019-03-04 09:17 UTC
