### ISSUE TITLE
[Unstable] Can't put "Large" Items in deconstructor or storage

### ISSUE THREAD

**Issue by RagingFlames** [Regalis11/Barotrauma#10846] opened 2022-12-31 16:45 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I'm playing unstable on a multiplayer server with some steam friends. We noticed that we couldn't deconstruct Hydroxyapatite in our ships deconstructor.

https://user-images.githubusercontent.com/28068199/210150216-1c315185-a8a2-4520-b46e-23fe9673669d.mp4

We later found that this problem extends to a bunch of other items too. Most ore, the text display, and the input terminal can't be put in the deconstructor or any storage container.

### Reproduction steps

1. Start a multiplayer campaign
2. Go find some Hydroxyapatite 
3. Put it in the deconstructor
4. Watch it pop out

### Bug prevalence

Happens every time I play

### Version

0.21.0.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-01-02 10:57
Thank you for the report!

I unfortunately couldn't find a way to reproduce the issue:

https://user-images.githubusercontent.com/14351070/210222172-fb0ff969-5d4f-4ff8-b677-8b9f8a242208.mp4

Hydroxyapatite is not a large item in the sense of having the tag "largeitem" - it has the tag "smallitem" and should be containable in cabinets, deconstructors and whatnot. So I think the issue must be somewhere else, perhaps some kind of a networking issue, but I could not figure out a way to get it to occur.

**Comment by RagingFlames** [comment] 2023-01-02 16:30
Is there some way I can get additional log data (Or are there logs saved somewhere already?) that would help?

**Comment by Regalis11** [comment] 2023-01-02 19:53
I'm not entirely sure if any logs could help us diagnose this, but the server logs `might` give us some more clues on what's happening here. Those should be located in a folder called ServerLogs inside the game's installation folder (although only for the player who was hosting the server). If you could send us a log file of a round where this happened, that'd be much appreciated! Or if it occurs consistently in some specific save file, that save file could also be useful.

Thanks and sorry for the inconvenience!

**Comment by Regalis11** [comment] 2023-01-02 19:59
...Actually, now I was able to reproduce this myself too! I think I must've been testing this in an incorrect branch earlier, as it doesn't seem to happen in our internal dev branch. So I don't think those log files are needed for diagnosing this. 
![image](https://user-images.githubusercontent.com/14351070/210273828-d432ffad-b203-472f-b96b-f99ee0c7cebe.png)

**Comment by RagingFlames** [comment] 2023-01-02 20:23
The "Detach from wall" text sort of reminds me of another problem we were having that may or may not be related. 
I was trying to wire up another text display in the humpback but the game kept forcing me to stop holding the item. It wouldn't be forced out of my inventory or anything, but in order to place it on the wall I had to spam the number key corresponding to that item, and spam click to put it on the wall. 
I'd be happy to file a separate issue if you think that's different (And I can make it happen again)

**Comment by Regalis11** [comment] 2023-01-02 20:30
That's most likely related: this seems to happen because the server incorrectly assumes the item is attached to a wall, and denies detaching it without a tool. No need to create a separate issue, I'll look into that as well while addressing this one (could be that it's another symptom of the same underlying bug).

**Comment by RagingFlames** [comment] 2023-01-02 20:42
Roger that. Let me know if you require anything else on my end.

**Comment by Regalis11** [comment] 2023-01-03 08:52
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8fffe74813c60445aca460e6fbbbc131c426a39a

**Closed** 2023-01-05 12:19 UTC
Labels: Bug, Code, Networking, Severe
