### ISSUE TITLE
Weird frozen seeds display shelf texture

### ISSUE THREAD

**Issue by KB0MB4** [Regalis11/Barotrauma#4972] opened 2021-02-04 00:27 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Noticed wierd texture in sub editor on unstable on frozen seeds display shelf texture
![1244214142](https://user-images.githubusercontent.com/20744282/106826651-61fd8980-6698-11eb-9c65-8fc05b6b35f7.png)

**Steps To Reproduce**
load sub editor, look for  frozen seeds display shelf

**Version**
0.12.0.1 on windows 10

**Additional information**
didnt reloaded sprites or something

**Comment by Xeavas** [comment] 2021-02-04 07:49
Refer to : #4945

**Comment by Regalis11** [comment] 2021-02-04 08:02
Duplicate of https://github.com/Regalis11/Barotrauma/issues/4945

**Closed by Regalis11** 2021-02-04 08:02 UTC
