### ISSUE TITLE
Disconnects when leaving the outpost

### ISSUE THREAD

**Issue by leonard84** [Regalis11/Barotrauma#8635] opened 2022-03-27 13:03 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In my current MP campaign, all clients experience a disconnect when we leave the outpost for a new map.
For the host I see the disconnect messages as soon as the map is loaded, for the clients it takes a while longer for them to discover that they have disconnected.

I then have to save&exit to lobby so all can re-join, when they load directly into the new map it works without problems. Interestingly, docking at an outpost works as well, only undocking/starting a new map triggers the disconnects.

**Steps To Reproduce**
I think it started with the new update.

I'm not sure, what is causing this but we play with a 32 Stack mod, and have a lot of items.
From the way Barotrauma saves items in inventory I assume that it doesn't have a stack count, but instead tracks each item individually. So this might be an explanation, but it can't be the whole story, because it works after restarting the round.

**Version**
Windows 10
Barotrauma BuildId 8276043

**Additional information**
Mods: 
[GunLights Remade](https://steamcommunity.com/sharedfiles/filedetails/?id=2498918103),
[oClockRadar / Sonar [Alt Appearance] ](https://steamcommunity.com/sharedfiles/filedetails/?id=2651492771)
Custom 32 Stack mod, created with [Mod Generator](https://github.com/Jlobblet/Barotrauma-Mod-Generator), increasing the stack size for resources only.
Modified Kastrull submarine

**Comment by Regalis11** [comment] 2022-03-28 07:15
Thank you for the report!

What kind of error message(s) the clients get when they disconnect?

**Comment by W4nT4n** [comment] 2022-04-06 19:56
![image](https://user-images.githubusercontent.com/35399316/162060043-8c63e602-08e5-4fd8-b339-745148b030eb.png)

**Comment by timeye37** [comment] 2022-04-06 20:07
[crashreport_20220406.txt](https://github.com/Regalis11/Barotrauma/files/8430192/crashreport_20220406.txt)
One of today's crash reports.

**Comment by blepsula** [comment] 2022-04-08 21:57
Wow, I have exactly the same issue, and still haven't found how to fix it.

**Comment by leonard84** [comment] 2022-04-09 14:06
This also happens when transitioning waypoints.

**Comment by Jamini** [comment] 2022-04-12 04:43
I think I found the cause of this issue!

After extensive testing, it appears that this occurs when a Client in a MP game finishes loading all assets before the server does. If the gap between the server and client load is too large, the client disconnects.

I can reliably reproduce this crash on my machine when running fully vanilla game with myself (on the Linux distribution) and any number of windows users. Due to the added delay loading textures and shaders I'm normally significantly slower to load than the other people in our campaign.



At a colony this is not an issue, as there are significantly fewer assets. Clients connected to my local server still load significantly sooner than I do.
On a travel map with no missions loaded, I can occasionally load fast enough for client connections to join.
On a full mission map (with 1-2 objectives) I can consistently get other players to disconnect on join.



A potential fix would be increasing the timeout for Clients connected to servers, or adding a heartbeat feature that lets clients know the host is still loading.

**Comment by ThatClassyWhiteD** [comment] 2022-04-21 01:00
Can confirm that this is still an issue. Playing MP with two friends, host remains in the game when leaving an outpost, but the other two players remain stuck in the loading screen, unable to play. Host must return to the lobby, and other players must leave the server and rejoin in order to keep playing.

**Comment by Regalis11** [comment] 2022-05-02 10:57
Hard to say if this has been fixed without knowing what the error message was, but if it was the "SteamP2P connection timed out" one mentioned above, this is most likely a duplicate of https://github.com/Regalis11/Barotrauma/issues/8899 and should be fixed in the latest hotfix.

**Closed by Regalis11** 2022-05-02 10:57 UTC
Labels: Bug, Code, Networking
