### ISSUE TITLE
Crash when going into test mode with a shuttle without hulls

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#4475] opened 2020-12-11 19:19 UTC
**Description**
Game will throw an exception and crash if you link a shuttle without hulls to a docking port and launch it in test mode.

**Steps To Reproduce**
Use provided Example and launch test mode through submarine editor.

[Docking Crash Example.zip](https://github.com/Regalis11/Barotrauma/files/5681162/Docking.Crash.Example.zip)

**Version**
[0.1200.0.0]

**Additional information**
```
Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void SetPosition(Microsoft.Xna.Framework.Vector2, System.Collections.Generic.List`1[Barotrauma.Submarine])
Stack trace: 
   at Barotrauma.Submarine.SetPosition(Vector2 position, List`1 checkd) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Submarine.cs:line 1131
   at Barotrauma.LinkedSubmarine.OnMapLoaded() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\LinkedSubmarine.cs:line 245
   at Barotrauma.MapEntity.MapLoaded(List`1 entities, Boolean updateHulls) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 685
   at Barotrauma.Submarine..ctor(SubmarineInfo info, Boolean showWarningMessages, Func`2 loadEntities, IdRemap linkedRemap) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Submarine.cs:line 1389
   at Barotrauma.GameSession.StartRound(LevelData levelData, Boolean mirrorLevel, SubmarineInfo startOutpost, SubmarineInfo endOutpost) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 306
   at Barotrauma.SubEditorScreen.TestSubmarine(GUIButton button, Object obj) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SubEditorScreen.cs:line 843
   at Barotrauma.GUIButton.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 262
   at Barotrauma.GUIComponent.UpdateAuto(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIComponent.cs:line 451
   at Barotrauma.GUI.<>c__DisplayClass143_0.<Update>b__0(GUIComponent c) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1223
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1223
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 951
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
```

**Comment by Regalis11** [comment] 2021-03-25 09:00
Duplicate of https://github.com/Regalis11/Barotrauma/issues/5082

**Closed by Regalis11** 2021-03-25 09:00 UTC
Labels: Bug, Code, Crash, Low prio
