### ISSUE TITLE
Crash While Repairing and Attacking 

### ISSUE THREAD

**Issue by Vyse777** [Regalis11/Barotrauma#4002] opened 2020-10-05 00:14 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
**Short:** The game crashed while using a welding tool to repair and attack "Terminal Cells" that boarded my sub.

**Long:** While being attacked and overwhelmed by multiple things at once (an average day in my adventures in this game thus far :P), I was being bombarded by "Terminal Cells" (as described by [this](https://barotrauma.gamepedia.com/Terminal_Cells) site), as well as the awesome arm things that penetrate the ship and keep you locked to a salvaged ship.
The red cells entered my ship by destroying large amounts of my top hull, then penetrated some of the flooring. So I sprang to action and started killing them and repairing my ship with the repair tool/welding tool. While simultaneously repairing a floor portion of the sub and attacking the enemy Terminal Cells at the same time the game crashed with the stack trace below

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

1. Ensure multiple enemies are attacking the ship (and/or repairing [I had a AI character repairing as well]) at the same time.
2. Repair the sub and attack an enemy with the welding tool at the same time
3. Crash

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).
Game version 0.10.5.1
OS: Windows 10

**Additional information**
**Crash report:**
Barotrauma Client crash report (generated on 10/4/2020 4:41:04 PM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

6F558E05A9FD96EA104348A23A5B582A

Game version 0.10.5.1 (ReleaseWindows, branch release, revision 9e259b2148)
Graphics mode: 2560x1440 (Fullscreen)
VSync OFF
Language: English
Selected content packages: Vanilla 0.9
Level seed: The BucketAylesbury
Loaded submarine: Dugong (29BAAD62DA41DF9275371A71E1110F3B)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19041.0 64 bit
    GPU name: NVIDIA GeForce RTX 2080 SUPER
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Collection was modified; enumeration operation may not execute. (System.InvalidOperationException)
Target site: Void ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
Stack trace: 
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Barotrauma.Items.Components.RepairTool.Repair(Vector2 rayStart, Vector2 rayEnd, Single deltaTime, Character user, Single degreeOfSuccess, List`1 ignoredBodies) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Holdable\RepairTool.cs:line 297
   at Barotrauma.Items.Components.RepairTool.Use(Single deltaTime, Character character) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Holdable\RepairTool.cs:line 244
   at Barotrauma.Item.Use(Single deltaTime, Character character, Limb targetLimb) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 2055
   at Barotrauma.Character.Control(Single deltaTime, Camera cam) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 1475
   at Barotrauma.Character.Update(Single deltaTime, Camera cam) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2409
   at Barotrauma.AICharacter.Update(Single deltaTime, Camera cam) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\AICharacter.cs:line 86
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2228
   at Barotrauma.GameScreen.Update(Double deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 179
   at Barotrauma.GameMain.Update(GameTime gameTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 921
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59

Hope this helps. If you have any questions please let me know.

I have a few years of experience writing code in C# so I cloned the repo and started investigating as well!

**Comment by Regalis11** [comment] 2020-10-05 07:00
Duplicate of #3896

**Closed by Regalis11** 2020-10-05 07:00 UTC
