### ISSUE TITLE
Game crashes while loading

### ISSUE THREAD

**Issue by juan11486** [Regalis11/Barotrauma#5443] opened 2021-04-06 20:27 UTC
**Description**
Game crashes while loading, after leaving a colony.

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Windows.
Game version 0.12.0.3 (ReleaseWindows, branch release, revision ea245a2f34)
[crashreport (5).log](https://github.com/Regalis11/Barotrauma/files/6267395/crashreport.5.log)

**Comment by Regalis11** [comment] 2021-04-07 07:26
Duplicate of https://github.com/Regalis11/Barotrauma/issues/1833

**Closed by Regalis11** 2021-04-07 07:26 UTC
