### ISSUE TITLE
Game crashed upon clicking "Sandbox" in Join Game menu, crash log below

### ISSUE THREAD

**Issue by BileGH** [Regalis11/Barotrauma#2698] opened 2020-04-25 06:07 UTC
```
Barotrauma Client crash report (generated on 4/25/20 09:04:44)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


B88397013C2378C4A99C3E19DEBEE54F


Game version 0.9.9.0 (ReleaseWindows, branch release, revision 0534150c8)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.ServerListScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.17763.0 64 bit
    GPU name: NVIDIA GeForce GTX 970M
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void FilterServers()
Stack trace: 
   at Barotrauma.ServerListScreen.FilterServers()
   at Barotrauma.ServerListScreen.<>c__DisplayClass70_0.<CreateUI>b__26(GUITickBox tickBox)
   at Barotrauma.GUITickBox.set_Selected(Boolean value)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime)
   at Barotrauma.GameMain.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Barotrauma.Program.Main(String[] args)


Last debug messages:
[4/25/20 09:03:52] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[4/25/20 09:03:52] Content package load order: Vanilla 0.9
[4/25/20 09:03:51] Content package load order: Vanilla 0.9
[4/25/20 09:03:48] Attempting to open ALC device "OpenAL Soft"
[4/25/20 09:03:47] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[4/25/20 09:03:47] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[4/25/20 09:03:44] Logged in as cheems (SteamID STEAM_1:0:192456633)
```

**Comment by Regalis11** [comment] 2020-04-25 14:00
Duplicate of #2567

This happens due when trying to filter servers in the server list based on game mode. We've got a hotfix coming for this issue soon, but for now it should be possible to work around it by not trying to filter the server list. Sorry for the trouble!

**Closed by Regalis11** 2020-04-25 14:00 UTC

**Comment by BileGH** [comment] 2020-04-27 13:58
Thank you
