### ISSUE TITLE
Searchlight on/off in its setting does nothing

### ISSUE THREAD

**Issue by Psyduckdeluxe** [Regalis11/Barotrauma#12473] opened 2023-08-05 21:20 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Guy in discord made me aware of this.
He was trying to get a search light to start in an off state.

I double checked  and its the same for me.

### Reproduction steps

Place a search light (i used 0 power consumption)  tick its "is on" check box to be off.
start testing mode and search light will still be on.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-08-06 13:08
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10704 (the searchlight is implemented using a turret component, so the same issue applies here)

**Closed by Regalis11** 2023-08-06 13:08 UTC
