### ISSUE TITLE
Multiple HuskAffliction Species Spawn if Multiple HuskAfflictions Active

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#4674] opened 2021-01-08 18:03 UTC
If a player has multiple husk afflictions past the 75pct threshhold, dying will trigger all of them to spawn their huskspecies. so if you have huskinfection > 80 and say STEM infection (or any modded affliction of type huskinfection) > 80, dying will spawn them both (a humanhusk and a humanstem will spawn. one of them will be "naked" without the original human's transferred items). The game should probably remove the excess characters that spawn (the ones without the transferred items).

**Comment by Rokvach** [comment] 2021-01-08 18:14
I saw this happen yesterday as well whilst testing another human husk related issue, but didn't think to report it as I used commands to achieve it rather than normal vanilla play.

**Comment by Regalis11** [comment] 2021-01-11 07:26
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9b649fd48eba1e70b3c4cf32b7a11716f74156b3

**Comment by hubismal** [comment] 2021-01-19 02:24
This seems to not be fixed in the latest unstable. Dying with multiple "genetic meltdowns" gives this error:
```
[01/18/2021 20:19:22] Attempted to access a potentially removed ragdoll. Character: Willie Fleig, id: 106, remo
ved: True, ragdoll removed: True
   at System.Environment.get_StackTrace()
   at Barotrauma.Ragdoll.get_Limbs() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Animation/Rag
doll.cs:line 63
   at Barotrauma.Ragdoll.get_HasMultipleLimbsOfSameType() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Cha
racters/Animation/Ragdoll.cs:line 77
   at Barotrauma.Ragdoll.GetLimb(LimbType limbType, Boolean excludeSevered) in <DEV>/Barotrauma/BarotraumaShare
d/SharedSource/Characters/Animation/Ragdoll.cs:line 1710
   at Barotrauma.StatusEffect.ApplyProjSpecific(Single deltaTime, Entity entity,
 IEnumerable`1 targets, Hull currentHull, Vector2 worldPosition, Boolean playSound) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/StatusEffects/StatusEffect.cs:line 80
   at Barotrauma.StatusEffect.Apply(Single deltaTime, Entity entity, IEnumerable`1 targets, Nullable`1 worldPosition) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/StatusEffects/StatusEffect.cs:line 1211
   at Barotrauma.DelayedEffect.Update(Single deltaTime) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/StatusEffects/DelayedEffect.cs:line 151
   at Barotrauma.StatusEffect.UpdateAll(Single deltaTime) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/StatusEffects/StatusEffect.cs:line 1257
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Screens/GameScreen.cs:line 185
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 929
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/SDL/SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 58
```
One ragdoll spawns properly, but another one spawns without anything on it.
I tried to put on a health scanner to further assess the situation and was met with a crash:
```
Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void DrawCharacterInfo(Microsoft.Xna.Framework.Graphics.SpriteBatch, Barotrauma.Character, Single)
Stack trace: 
   at Barotrauma.Items.Components.StatusHUD.DrawCharacterInfo(SpriteBatch spriteBatch, Character target, Single
 alpha) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Items/Components/StatusHUD.cs:line 158
   at Barotrauma.Items.Components.StatusHUD.DrawHUD(SpriteBatch spriteBatch, Character character) in <DEV>/Baro
trauma/BarotraumaClient/ClientSource/Items/Components/StatusHUD.cs:line 139
   at Barotrauma.CharacterHUD.Draw(SpriteBatch spriteBatch, Character character, Camera cam) in <DEV>/Barotraum
a/BarotraumaClient/ClientSource/Characters/CharacterHUD.cs:line 373
   at Barotrauma.Character.DrawHUD(SpriteBatch spriteBatch, Camera cam, Boolean drawHealth) in <DEV>/Barotrauma
/BarotraumaClient/ClientSource/Characters/Character.cs:line 683
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>/B
arotrauma/BarotraumaClient/ClientSource/Screens/GameScreen.cs:line 127
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs
:line 1006
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame
.Framework/Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:
line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Fram
ework/SDL/SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>/Libraries/MonoGame.Framework/Src/M
onoGame.Framework/Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:l
ine 367
   at Barotrauma.Program.Main(String[] args) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 
58
```
I will try to look into this further.

**Comment by Rokvach** [comment] 2021-01-19 09:39
Moving back to misc todo

**Comment by Regalis11** [comment] 2021-01-19 12:27
1st issue fixed in https://github.com/Regalis11/Barotrauma-development/commit/c484e9a960e4b505a2c4763d54fb9c8a48287e99

The second issue seems to happen because the Gummy character has a status effect that sets the IsDead property of the character directly, which causes a lot of crucial things to be bypassed (setting cause of death, creating network events, dropping items and removing the character from the crew). In this case the problem was that health scanner assumed the cause of death must be set if the character is dead.

You should instead kill the character with an affliction (which I think is the intention behind the 99999 strength internal damage affliction in the same status effect)?

In any case, I modified the IsDead property so that it can no longer be set by status effects: https://github.com/Regalis11/Barotrauma-development/commit/d7b9de0b33d7568b1083324da08f6215a2e689bf

**Comment by hubismal** [comment] 2021-01-19 23:20
Requesting changing IsDead so that its "set" method automatically uses the Kill method if set's "value" equals true. (so IsDead="true" would automatically run Kill method instead of just setting the value).

My mod (and a lot of other mods that were inspired by mine) are going to be terribly broken if characters can no longer be brought back to life by using IsDead="false".

**Comment by Regalis11** [comment] 2021-01-20 11:49
Setting it directly to false isn't safe either, because that also bypasses many things: for example, severed limbs will stay severed (which can cause problems with the ragdoll animations), the character doesn't get readded to the crew, the light sources on the limbs stay disabled, AI targets don't reactivate...

Anyhow, I reallowed setting the property, and made it call Kill or Revive methods to make sure the killing/revival is done properly. https://github.com/Regalis11/Barotrauma-development/commit/86dccfb99dda04dffe06a6b495995f2ee51e690b

**Comment by Rokvach** [comment] 2021-01-26 01:11
This hasn't caused any issues, so seems to be working. Closing.

**Closed by Rokvach** 2021-01-26 01:11 UTC
Labels: Bug, Code, Low prio, Modding

**Comment by Emanthealmighty** [comment] 2021-01-30 15:57
This issue seems to be still relevant in the current unstable build of the game. (v.0.12.0.1)
I'm using the standard husk infection and a modded one that both target humans. Both of them simply just turn the human into a different character. 

After both of the afflictions have reached over 75% strength, when the human dies, two "husks" will spawn instead of one.
