### ISSUE TITLE
More missions than there should be

### ISSUE THREAD

**Issue by Imasleep3590** [Regalis11/Barotrauma#10398] opened 2022-11-14 21:58 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I expeced there to be no change.

### Reproduction steps

I'M NOT SURE IF THIS WORKS

1. Load singleplayer
2. Get missions
3. Save and quit
4. Open submarine editor
5. Test
6. Load back game

### Bug prevalence

Just once

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-12-08 13:55
Duplicate of https://github.com/regalis11/barotrauma/issues/10192

**Closed by Regalis11** 2022-12-08 13:55 UTC
Labels: Bug, Code
