### ISSUE TITLE
[Unstable] Error message on launching the game regarding Server info

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9726] opened 2022-08-19 17:15 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

After launching the game, multiple error messages appeared regarding old server descriptions.

Probably due to `{Input string was not in a correct format.}`

![image](https://user-images.githubusercontent.com/73229309/185672101-3c29eea7-c21b-462f-bd4c-03ae45786ae0.png)

Error in <ServerInfo ServerName="Kaileris' 50L1-TUD3 Campaign" ServerMessage="No griefing please.&#xA;&#xA;Respawn is OFF to prevent MISSING_ENTITY Error in this version of the game." IP="65.93.139.155" Port="27015" QueryPort="" GameMode="multiplayercampaign" GameVersion="0.17.12.0" MaxPlayers="10" PlayStyle="Serious" UsingWhiteList="False" TraitorsEnabled="No" SubSelectionMode="Manual" ModeSelectionMode="Manual" VoipEnabled="True" KarmaEnabled="True" FriendlyFireEnabled="True" HasPassword="True" />!  {Input string was not in a correct format.}
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at Barotrauma.XMLExtensions.GetAttributeInt(XElement element, String name, Int32 defaultValue) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Serialization\XMLExtensions.cs:line 337

### Bug prevalence

Happens every time I play

### Version

Other

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-08-22 08:07
Partially addressed in https://github.com/Regalis11/Barotrauma-development/commit/5a559e8c623cadb9357bda7614d1b7a0d9409315

Seems to have been caused by the QueryPort attribute: parsing it as an int fails when the value is empty. There is still something off here though, we never seem to serialize the QueryPort to XML.

**Comment by Regalis11** [comment] 2022-09-08 10:10
Seems to have been fixed in [serverlist-cleanup](https://github.com/Regalis11/Barotrauma-development/tree/feature/serverlist-cleanup)

**Comment by Rokvach** [comment] 2022-09-14 05:06
Tested, working correctly. Closing.

**Closed by Rokvach** 2022-09-14 05:06 UTC
Labels: Bug, Code
