### ISSUE TITLE
Kastrull Drone docking waypoint

### ISSUE THREAD

**Issue by the1eyedduck** [Regalis11/Barotrauma#5962] opened 2021-06-03 13:42 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
An incorrect docking waypoint in kastrull drone make AI unable to leave

**Steps To Reproduce**
tag all kastrull drone hull as avoid staying (force AI to leave), save and link the updated drone to kastrull, get NPC follow you down the drone and dismiss them while they inside. The AI will get stuck on the docking port.
go back to drone and move docking waypoint slight upward (until waypoint turn from green to blue after save and load), save it and link it back to kastrull then do the same as above, but this time AI able to pathway as normal

TL;DR: kastrull drone docking waypoint need to move up slightly or AI will get stuck/wont be able to get out of the drone

**Version**
0.1400.2.0

**Additional information**
Bots get stuck
![Kastrull bot stuck in ladder](https://user-images.githubusercontent.com/74727878/120654589-0c04eb00-c4ac-11eb-9b89-812be0021ba5.png)
Move waypoint slightly upward
![Kastrull drone breaking point](https://user-images.githubusercontent.com/74727878/120654616-11623580-c4ac-11eb-9839-75e4528c17f8.png)
and here is the fixed drone after testing

[KastrullDrone TEST2.zip](https://github.com/Regalis11/Barotrauma/files/6592013/KastrullDrone.TEST2.zip)

Also please set both kastrull and remora drone hull to avoid staying.

**Comment by Regalis11** [comment] 2021-06-03 17:26
Duplicate of https://github.com/regalis11/barotrauma/issues/5716

**Closed by Regalis11** 2021-06-03 17:26 UTC
