### ISSUE TITLE
Autopilot set to go to a position with "maintain position" stops working when the UI is closed

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#5335] opened 2021-03-26 19:46 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I set a target for the autopilot to go to, but when I exit the UI, the autopilot stops following that marker.
I wasn't paying attention to when it happens.

**Steps To Reproduce**
Not sure

**Version**
v0.12.0.3 Windows 20H2

**Additional information**
https://youtu.be/0rN5NTKrojk

**Comment by Regalis11** [comment] 2021-03-27 15:51
I'm afraid I couldn't reproduce this. I wonder if it could have something to do with the custom sub you're using: does it have some kind of automatized steering/autopilot logic?

**Comment by Krzeszny** [comment] 2021-03-27 18:31
> I'm afraid I couldn't reproduce this with the vanilla subs. I wonder if it could have something to do with the custom sub you're using: does it have some kind of automatized steering/autopilot logic?

Sorry, I failed to mention that it uses this https://steamcommunity.com/sharedfiles/filedetails/?id=2176229983
And the lower mid is a ballast tank, too. I could send you a save but I'd have to remove modded things from it. Do you want it?

**Comment by Regalis11** [comment] 2021-03-28 14:04
Ah, thank you for the extra info! In that case this is most likely a duplicate of https://github.com/regalis11/barotrauma/issues/5090, and should be fixed in the next update (+ the fix is already included in the current unstable version).

**Comment by Rokvach** [comment] 2021-03-28 15:23
The referenced ticket has already been tested, closing this one as well

**Closed by Rokvach** 2021-03-28 15:23 UTC
Labels: Bug, Code, Needs testing
