### ISSUE TITLE
Linked Submarines - When docking and if the location the main submarine is docked to clips into the location, any linked submarines will be offset from the main sub incorrectly.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4639] opened 2021-01-04 22:29 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When docking and if the location the main submarine is docked to clips into the location, any linked submarines will be offset from the main sub incorrectly. This includes clipping via shells touching each other, or even external weapons like coilguns/railguns.

![Capture](https://user-images.githubusercontent.com/5086682/103586814-e1d6df00-4eb3-11eb-94a4-2771e9507233.PNG)

**Steps To Reproduce**
1. Load Kastrull_Wrecked in sub editor or find it in a level (or any main submarines that have a shuttle and a outpost invasive top)
2. Link [Dandelion](https://steamcommunity.com/sharedfiles/filedetails/?id=2312353651) to bottom right docking port.
3. Test Sub / Dock submarine to Wrecked Kastrull.

**Version**
~0.1200.0.1

**Additional information**
This happened to my past subs before the outpost update and most of the time I (Or other sub creators) end up just redoing the top of the sub to fit the outposts better.

**Comment by NilanthAnimosus** [comment] 2022-07-10 23:57
Tested against unstable 0.18.14.0 - I am unable to reproduce this following the steps provided, the hull of the dandelion intersects with the Kastrul wreck as its docked so that is the same, I linked it in the sub editor (Loading the kastrul wreck and then proceeding to add the dandelion as a shuttle) and even when undocking and re-docking the position of the shuttle is correct.

![image](https://user-images.githubusercontent.com/29177976/178166924-a155696f-2308-46ef-9831-0e453b270223.png)

Given the time and version this issue was created - it is possible this bug has been fixed by other changes to docking logic since then though no specific changes are mentioned. Closing as it no longer seems to be an issue.

**Closed by NilanthAnimosus** 2022-07-10 23:57 UTC
Labels: Bug, Needs testing, Code, Medium Prio
