### ISSUE TITLE
Skill Check Outpost Event should probably have RNG to success with lower than required skill level

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3737] opened 2020-09-05 22:29 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Skill Check Outpost Event should probably have RNG to success with lower than required skill level.

Looking at the current Giving Direction event for instance, you need 50 helm to succeed this event, which gives you 5 more helm. It feel it's a little awkward to get more of something you don't get much out of with 50 helm already. If a engineer somehow to manage to figure out the map with 5 helm and get to level 10, that's actually a good reward.

I suggest probably having 4 kinds of outcomes like in D&D style that can be influenced with skills? Critical Fail, Fail, Success, and Critical Success.

Example: Giving Directions
Critical Fail - You made yourself out to the Captain as an imbecile as go through the map with him. You annoyed him to the point that he threatens you with his Revolver to get out of his sight. (Makes Captain hostile to Player. Don't Chase?).
Fail - You both couldn't figure it out, but at least you got some insights on nearby locations you should watch out for. +1 Helm.
Success - You both found a way to the location, but in your mind you have believe there might've been a better way. +2 Helm.
Critical Success - Same as the current success in Barotrauma ~0.10.502. +5 Helm.

This can be applied to all outpost events really, to make them less static and predictable.

Another Example: Sound in the Vent
Critical Fail - 3 Mudraptors or Crawlers but very little delay, and Bite Wound on the hand.
Fail - 3 Mudraptors or Crawlers, normal delay.
Success - 1 Mudraptor or Crawler, normal delay +1 Weapons.
Critical Success - No Aliens. You killed the alien in the vent with your ingenius ideas. (Plays alien death sound). +2 Weapons. +Alien Blood or Mudraptor Egg?

**Version**
~0.10.502

**Comment by SioxGWolf** [comment] 2020-09-06 19:06
They are already RNG based, but I get what your meaning, you want better ranges of RNG, you want to improve the RNG! I cannot disagree. I think most of the effort will be coding in the 5 different results.... which at times could lead to 5 different results in certain situations. Some RNGs are not based on skill, and pure chance, but ones based on skill, should give some bigger leeway, and more ranges of what could happen. Also in that situation, there are two different skill checks you can do, the sound in the vent, for example, has one skill check that can be passed by a mechanic, and they just find some loot or get hurt, meanwhile security with weapons peers in with a flash, and we know the rest. I am sure if you look through all the possibilities and start writing alternatives, you could help speed along with the effort, considerably, but ask someone with more expertise then me. I am just a verberose supporter of the change.

**Comment by Regalis11** [comment] 2020-11-18 12:49
Implemented in Implemented in https://github.com/Regalis11/Barotrauma-development/commit/0b3f390ce47954fea440a0de4c69a7d4f8e52f8c. Closing because we have a ticket in the private repo (https://github.com/regalis11/barotrauma-development/issues/2197) that's already been tested and confirmed working.

**Closed by Regalis11** 2020-11-18 12:49 UTC
Labels: Code, Design, Feature request
