### ISSUE TITLE
Player time-outs on launching multiplayer campaign savefile

### ISSUE THREAD

**Issue by FLundin** [Regalis11/Barotrauma#4183] opened 2020-10-31 16:51 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When selecting a previous campaign savefile to load, up on loading players fail to load and gets kicked off the server.

**Steps To Reproduce**
Its hard to determine the factors in this but, me and my friends speculate it have to do with:
1. Host have a bad upline
2. clients have a bad connection/downline from the host
3. Large save files
4. Savefiles containing more than one owned sub
5. amount of players downloading the savefile form the server the same time

**Version**
since you published the new campaign map until v0.10.6.2 Win 10

**Additional information**
Back before the new campaign map update, you had a system that allowed players to preload the savefile and players, depending on their download speed and your upload speed in conjunction with the size of the savefile allowed you to wait for them to load the file completely (using the "ready" button to signal that they were done) before launching the game. This new system have cause issues where i had to abandon campaigns multiple times with friends because players could not all join in the same time.

Solution to this could be to:
1. bring back the preloading of savefiles in the lobby
2. Allow the players to see all players loading % (maybe like this game https://i.imgur.com/vXIQA7j.jpg) and have a system that do not launch untill all is ready or have a host controlled start button.
3. Make the game and clients/server host less sensitive to long loading times.

**Comment by codethenpizza** [comment] 2020-12-10 20:55
Have same on version 0.11.0.9 (mac os)

**Comment by Regalis11** [comment] 2021-05-05 08:21
Possibly a duplicate of https://github.com/Regalis11/Barotrauma/issues/5702. It's hard to say for sure without knowing what kind of an error message the clients get when they disconnect, but if it was "Error while starting the round (did not receive STARTGAMEFINALIZE message from the server). Stopping the round...", this should now be fixed.

**Comment by Rokvach** [comment] 2021-05-25 08:29
Tested, there hasn't been any sightings of this happening during the Unstable period, seems to be working correctly. Closing.

**Closed by Rokvach** 2021-05-25 08:29 UTC
Labels: Bug, Code, Medium Prio, Networking
