### ISSUE TITLE
Crash when trying to heal crew member

### ISSUE THREAD

**Issue by PaszaVonPomiot** [Regalis11/Barotrauma#2797] opened 2020-05-10 16:40 UTC
- [ x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Two separate crashes, both while trying to heal other unconcious person with some medicine.

**Steps To Reproduce**
Start bleeding, get unconcious, select another crew member and try to use blood pack or other medicine on unconcious person.

**Version**
W10

**Additional information**
No mods. Single Player. No mission. The same map.

Logs:
```
Barotrauma Client crash report (generated on 2020-05-03 19:05:16)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


023CCD07C102F6331CAD29D2EADB01E0


Game version 0.9.9.1 (ReleaseWindows, branch release, revision 1968ab79f)
Graphics mode: 1920x1080 (Fullscreen)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: TaraMilda
Loaded submarine: Dugong (A381731D102CD24A97C2ED88CC80A4FC)
Selected screen: Barotrauma.GameScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.14393.0 64 bit
    GPU name: NVIDIA GeForce GTX 1070
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void GiveTreatment(Single)
Stack trace: 
   at Barotrauma.AIObjectiveRescue.GiveTreatment(Single deltaTime)
   at Barotrauma.AIObjectiveRescue.Act(Single deltaTime)
   at Barotrauma.AIObjective.TryComplete(Single deltaTime)
   at Barotrauma.HumanAIController.Update(Single deltaTime)
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam)
   at Barotrauma.GameScreen.Update(Double deltaTime)
   at Barotrauma.GameMain.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Barotrauma.Program.Main(String[] args)


Last debug messages:
[2020-05-03 16:36:46] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[2020-05-03 16:36:46] Content package load order: Vanilla 0.9
[2020-05-03 16:36:45] Content package load order: Vanilla 0.9
[2020-05-03 16:36:42] Attempting to open ALC device "OpenAL Soft"
[2020-05-03 16:36:40] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[2020-05-03 16:36:40] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
```

```
Barotrauma Client crash report (generated on 2020-05-10 18:26:38)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


023CCD07C102F6331CAD29D2EADB01E0


Game version 0.9.9.1 (ReleaseWindows, branch release, revision 1968ab79f)
Graphics mode: 1920x1080 (Fullscreen)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: TaraMilda
Loaded submarine: Dugong (7E7527AF38338A6F0F596E16E4089770)
Selected screen: Barotrauma.GameScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.14393.0 64 bit
    GPU name: NVIDIA GeForce GTX 1070
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void GiveTreatment(Single)
Stack trace: 
   at Barotrauma.AIObjectiveRescue.GiveTreatment(Single deltaTime)
   at Barotrauma.AIObjectiveRescue.Act(Single deltaTime)
   at Barotrauma.AIObjective.TryComplete(Single deltaTime)
   at Barotrauma.HumanAIController.Update(Single deltaTime)
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam)
   at Barotrauma.GameScreen.Update(Double deltaTime)
   at Barotrauma.GameMain.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Barotrauma.Program.Main(String[] args)


Last debug messages:
[2020-05-10 17:50:01] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[2020-05-10 17:50:01] Content package load order: Vanilla 0.9
[2020-05-10 17:50:01] Content package load order: Vanilla 0.9
[2020-05-10 17:49:58] Attempting to open ALC device "OpenAL Soft"
[2020-05-10 17:49:56] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[2020-05-10 17:49:55] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
```

**Comment by Regalis11** [comment] 2020-05-11 08:13
I unfortunately wasn't able to reproduce this. The crash report seems to suggest that the crash happened in the part of code that makes a bot treat characters, so it could be that it wasn't actually caused by you trying to treat the character.

I added some extra null checks to fix/diagnose this in https://github.com/Regalis11/Barotrauma-development/commit/b194cf39eb9a4760cc42dd1cb7a35cbf1191055c.

**Comment by PaszaVonPomiot** [comment] 2020-05-11 09:47
Oh yes - I remember that me and bot were trying to heal crew member at the same time.
I tried to reproduce it on purpose but crash didn't happen this time.

**Comment by Rokvach** [comment] 2020-05-25 14:53
This hasn't been sighted during Unstable testing, as there is no clear way to reproduce this I will just close the ticket and re-open it if the issue re-surfaces later on. Closing.

**Closed by Rokvach** 2020-05-25 14:53 UTC
Labels: Bug, Code, Crash, Need more info, Needs testing
