### ISSUE TITLE
0.15.13.0 - Suddenly taking off the MK-1 diving suit inside a beacon [Multiplayer]

### ISSUE THREAD

**Issue by taurviz** [Regalis11/Barotrauma#7485] opened 2021-11-25 17:30 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Me and my friends were wearing a MK-1 armor while repairing a beacon.
I saw my character suddenly taking off the diving suit and I was injured.
My friend saw his character taking off the diving suit and he was injured.
But in my friend's vision, my character was wearing the diving suit.
The same thing happened on my side, I saw his charcter was wearing the diving suit.

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.
Wear a MK-1 armor and go inside a beacon station, it happens randomly.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).
Windows 10 x64

**Additional information**

**Comment by Regalis11** [comment] 2021-11-26 09:54
Duplicate of https://github.com/Regalis11/Barotrauma/issues/6403

**Closed by Regalis11** 2021-11-26 09:54 UTC
