### ISSUE TITLE
Persistent Content Package Error

### ISSUE THREAD

**Issue by pelmeniboiler** [Regalis11/Barotrauma#9037] opened 2022-05-02 03:43 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Whenever I start the game, open content packages settings, or try to upload a mod, the console opens with this error:

```
Failed to load "": Name is null or empty: at Barotrauma.ContentPackage.AssertCondition(Boolean condition, String errorMsg) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentPackage\ContentPackage.cs:line 191 at Barotrauma.ContentPackage..ctor(XDocument doc, String path) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentPackage\ContentPackage.cs:line 70
at Barotrauma.RegularPackage..ctor(XDocument doc, String path) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentPackage\RegularPackage.cs:line 10
at Barotrauma.ContentPackage.TryLoad(String path) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentPackage\ContentPackage.cs:line 137 
```

**Steps To Reproduce**
After uploading a mod to the workshop, I encountered an error in trying to update it, this error persisted no matter how many times I verified gamefiles or reinstalled the game.

**Version**
v0.17.15.0, branch release, revision 62bb4ecab3 
Windows 10 x64

**Additional information**
It seems to be loading a content package that has no name, I have unsubscribed from every workshop content package I was subscribed to and removed them from my harddisks and reinstalled the game fresh on a new drive, but the workshop items continue to show up in settings. Hope this helps.

**Comment by Regalis11** [comment] 2022-05-02 07:44
Duplicate of https://github.com/Regalis11/Barotrauma/issues/8864

**Closed by Regalis11** 2022-05-02 07:44 UTC
