### ISSUE TITLE
Round summary screen clips off at lowest resolution

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#3166] opened 2020-06-20 21:53 UTC
Self explanatory. On the lowest resolution, the topmost text clips off the screen.

**Comment by Regalis11** [comment] 2020-06-22 12:36
Could not reproduce:
![5467rshgt](https://user-images.githubusercontent.com/14351070/85288090-e1d63b00-b49d-11ea-9f9f-395ddc5b9f27.png)

**Comment by hubismal** [comment] 2020-06-25 15:32
On Resolution 1024 x 576

![2020-06-25-103025_1083x646_scrot](https://user-images.githubusercontent.com/47284081/85750023-f6e5e080-b6ce-11ea-915d-eab899fea5ea.png)

**Comment by Regalis11** [comment] 2020-06-26 07:41
I didn't remember that was the smallest resolution we support, the smallest on I get in the settings is 1024x768. Thanks for the extra info, should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/91b0d1f9bef3851fdeec84566317f267050055c5

**Comment by Rokvach** [comment] 2020-06-29 08:45
No issues, closing.

**Closed by Rokvach** 2020-06-29 08:45 UTC
Labels: Bug, Code
