### ISSUE TITLE
AI does not properly open two nearby located doors

### ISSUE THREAD

**Issue by pakvg85** [Regalis11/Barotrauma#9638] opened 2022-07-25 08:19 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Situation: there are two doors that are placed nearby. A bot opens first door, then almost immediately tries to open second door. The problem is - when the bot is opening the second door, he has not yet fully passed through the first door. This could cause incorrect behavior if the second door's logic results in closing the first door.
Example: https://www.youtube.com/watch?v=WpQyH1VJI00
Test submarine: [Test Sub.zip](https://github.com/Regalis11/Barotrauma/files/9179288/Test.Sub.zip)

What I expect: the bot should not try to press second door's buttons until he fully passes through the first door.

I decided to separate this issue from #9600 just to make it easier. I will create a pull request for this a bit later.

### Reproduction steps

1. In sub editor place 2 doors near each other.
2. Place buttons and logic components so there will be a button that in the same time opens second door and closes first door.
3. Place 2 bots so they will be separated by 2 doors.
4. Command a bot to follow another bot.

### Bug prevalence

Happens every time I play

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by MaaiG** [comment] 2022-07-25 09:56
I have a similar problem. A custom submarine.
The bot opens the door but not goes forward as the next door is closed.
The next door should open when the first closes.
But the bot opens the first door and just stands.
The bot must approach the locked door but it does not! Apparently 
 the bot expects the second door to open, at a great distance from it.
It seems to me the problem is at what distance the bots open the door or at what distance they expect the path to open.

**Comment by pakvg85** [comment] 2022-07-26 04:17
Could you attach your custom sub here in a zip file?

**Comment by MaaiG** [comment] 2022-07-28 20:45
> Could you attach your custom sub here in a zip file?

You want to test the door!? The idea is simple: the ballast door opens in front of the character automatically if there is no water (If water - manual mode) and is a primitive gateway (as simple as possible for AI). But 90% of the time the bots don’t know how to use it 😔.
So, that is a partial copy of the circuit (there is nothing superfluous): [_Test-doors.zip](https://github.com/Regalis11/Barotrauma/files/9214021/_Test-doors.zip)

**Comment by itchyOwl** [comment] 2023-01-26 14:06
Fixed in Regalis11/Barotrauma-development@7320dbdad51d0426b1b4857c68d523f556835d66

**Comment by Regalis11** [comment] 2023-01-27 17:13
Tested, I was no longer able to repro the issue in the test sub provided in the ticket. 

Also tested a slightly different setup: here opening the door on the left forces the door on the right to close, meaning the bot can only get through the doors if they wait until they're past the right one before trying to open the left one:
![image](https://user-images.githubusercontent.com/14351070/215151074-86b8638f-b6e1-40c6-99d9-a373ac0f0693.png)

Seems to work with no issues there too, closing.

**Closed by Regalis11** 2023-01-27 17:13 UTC
Labels: Bug, Code

**Comment by pakvg85** [comment] 2023-01-28 11:17
thank you for not forgetting the older tickets! looking forward to check it on stable version :-)
