### ISSUE TITLE
Barotrauma crashed after clicking the diving suit cabinet

### ISSUE THREAD

**Issue by Aldous13** [Regalis11/Barotrauma#11280] opened 2023-02-19 05:40 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Without adding a new mode or changing the game settings, any action of clicking on the diving suit cabinet after opening the submarine editor today will crash the Barotrauma. Why?

The error log is as follows：

### Reproduction steps

1、Open rhe submarine editor
2、Load the official submarine
3、Click on the diving suit cabinet
4、Game crash

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 02/19/2023 13:32:05)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

18B4B1F1463515508F0783BBFA6953EC

Game version 0.21.6.0 (ReleaseWindows, branch release, revision 480a2279e0)
Graphics mode: 1920x1080 (Fullscreen)
VSync ON
Language: Simplified Chinese
Selected content packages: Vanilla, BaroTraumatic, Improved Husks, Barotraumatic Creature Pack, [SH]Barotraumatic中文补丁(最新生物包汉化), [EA-HI]木卫二萌化计划, 搬炮弹, 潜水服套装, [调停者]小型穿梭艇, 潜水服柜, 信号灯, 32x Stack (with Vanilatic Ballance Armory), R-278 «Dugong» [CN]汉化版, Gene Splicer+ CN, Backpacks, SOFA'S CREATURES, 深渊基因 Abyss Gene, backpack中文补丁, More Artifacts (AOCS), 更多海盗船, Lovecraft Polyp, Pirates of the European /扩展与更强的海盗船, Hidden Deep Monsters, project shipwrecks, CatGene_Patch_EWBH-Huskmod, 无限工具, More Artifacts 中文补丁, VBA原版扩展武器包 (CN), Wreck Locator 沉船定位器, [BOS]Wrecks, 【判律者】小型穿梭艇
Level seed: no level loaded
Loaded submarine: Azimuth (25AE622445B2A2D7075B90A31582C5AD)
Selected screen: Barotrauma.SubEditorScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce GTX 1060
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Boolean MatchesItem(Barotrauma.ItemPrefab)
Stack trace: 
   at Barotrauma.RelatedItem.MatchesItem(ItemPrefab itemPrefab) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\RelatedItem.cs:line 124
   at Barotrauma.Items.Components.ItemContainer.SlotRestrictions.<>c__DisplayClass4_0.<MatchesItem>b__0(RelatedItem c) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\ItemContainer.cs:line 48
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Barotrauma.Items.Components.ItemContainer.SlotRestrictions.MatchesItem(ItemPrefab itemPrefab) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\ItemContainer.cs:line 48
   at Barotrauma.Items.Components.ItemContainer.<>c__DisplayClass196_0.<CanBeContained>b__0(SlotRestrictions s) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\ItemContainer.cs:line 418
   at System.Linq.ImmutableArrayExtensions.Any[T](ImmutableArray`1 immutableArray, Func`2 predicate)
   at Barotrauma.Items.Components.ItemContainer.CanBeContained(ItemPrefab itemPrefab) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\ItemContainer.cs:line 418
   at Barotrauma.Item.<>c__DisplayClass47_0.<CreateEditingHUD>b__2(ItemPrefab ip) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 778
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Immutable.ImmutableHashSet`1.Union(IEnumerable`1 other, MutationInput origin)
   at System.Collections.Immutable.ImmutableHashSet`1.Union(IEnumerable`1 items, Boolean avoidWithComparer)
   at Barotrauma.Item.CreateEditingHUD(Boolean inGame) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 755
   at Barotrauma.Item.UpdateEditing(Camera cam, Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 691
   at Barotrauma.MapEntity.UpdateEditor(Camera cam, Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\MapEntity.cs:line 885
   at Barotrauma.SubEditorScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SubEditorScreen.cs:line 5684
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 882
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[02/19/2023 13:31:54] Error while loading component of the type Barotrauma.Items.Components.Fabricator. {Object reference not set to an instance of an object.}
   at Barotrauma.FabricationRecipe.RequiredItemByTag.<get_ItemPrefabs>b__5_0(ItemPrefab p) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\ItemPrefab.cs:line 139
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Barotrauma.Items.Components.Fabricator..ctor(Item item, ContentXElement element) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Machines\Fabricator.cs:line 123
[02/19/2023 13:29:45] WARNING: Entity "xandepthchargeshell" has no name!
[02/19/2023 13:29:44] WARNING: Entity "geneticmaterialpsilotoad_unresearched2" has no name!
[02/19/2023 13:29:44] WARNING: Entity "artmod_termorifle" has no name!
[02/19/2023 13:29:44] WARNING: Entity "geneticmaterialpsilotoad_unresearched3" has no name!
[02/19/2023 13:29:44] WARNING: Entity "geneticmaterialfractalguardian_unresearched3" has no name!
[02/19/2023 13:29:44] WARNING: Entity "geneticmaterialpsilotoad_unresearched" has no name!
[02/19/2023 13:29:44] WARNING: Entity "geneticmaterialhammerheadgold_unresearched3" has no name!
[02/19/2023 13:29:44] WARNING: Entity "geneticmaterialfractalguardian_unresearched2" has no name!
[02/19/2023 13:29:44] WARNING: Entity "3Dprinter_EAHI" has no name!
[02/19/2023 13:29:44] WARNING: Entity "suicidevest" has no name!
[02/19/2023 13:29:44] WARNING: Entity "geneticmaterialfractalguardian_unresearched" has no name!
[02/19/2023 13:29:44] WARNING: Entity "geneticmaterialwatcher_unresearched" has no name!
[02/19/2023 13:29:44] WARNING: Entity "geneticmaterialhammerheadgold_unresearched2" has no name!
[02/19/2023 13:29:44] WARNING: Entity "geneticmaterialwatcher_unresearched2" has no name!
[02/19/2023 13:29:44] WARNING: Entity "geneticmaterialwatcher_unresearched3" has no name!
[02/19/2023 13:29:44] WARNING: Entity "raining" has no name!
[02/19/2023 13:29:44] WARNING: Entity "geneticmaterialhammerheadgold_unresearched" has no name!
[02/19/2023 13:29:44] WARNING: Entity "raining" has no name!
[02/19/2023 13:29:44] WARNING: Entity "suicidevest" has no name!
[02/19/2023 13:29:44] WARNING: Entity "artmod_termorifle" has no name!
[02/19/2023 13:29:43] WARNING: Entity "xandepthchargeshell" has no name!
[02/19/2023 13:29:43] WARNING: Entity "3Dprinter_EAHI" has no name!
[02/19/2023 13:29:38] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Mechrevo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2809175631/Content/Particles/Particle_teleport1.png, size: 1645x510)
[02/19/2023 13:29:38] Overriding an affliction or a buff with the identifier 'nausea' using the file 'C:/Users/Mechrevo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2809175631/Content/Afflictions.xml'
[02/19/2023 13:29:38] Overriding an affliction or a buff with the identifier 'concussion' using the file 'C:/Users/Mechrevo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2809175631/Content/Afflictions.xml'
[02/19/2023 13:28:25] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Mechrevo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776026770/Afflictions/health+.png, size: 127x128)
[02/19/2023 13:28:25] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Mechrevo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776026770/Afflictions/health.png, size: 127x128)
[02/19/2023 13:28:25] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Mechrevo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776026770/Afflictions/fastrepair.png, size: 127x128)
[02/19/2023 13:28:25] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Mechrevo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776026770/Afflictions/swimboost.png, size: 127x128)
[02/19/2023 13:28:25] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Mechrevo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776026770/Afflictions/bluesyringe.png, size: 127x128)
[02/19/2023 13:28:25] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Mechrevo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776026770/Afflictions/redsyringe.png, size: 127x128)
[02/19/2023 13:28:25] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Mechrevo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776026770/Afflictions/Stunresist.png, size: 127x128)
[02/19/2023 13:28:25] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Mechrevo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776026770/Afflictions/Bleedresist.png, size: 127x128)
[02/19/2023 13:28:25] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Mechrevo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776026770/Afflictions/soulles.png, size: 1349x640)
[02/19/2023 13:28:25] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Mechrevo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776026770/Afflictions/test1.png, size: 126x128)
[02/19/2023 13:28:25] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Mechrevo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776026770/Afflictions/Fireresist.png, size: 127x128)
[02/19/2023 13:28:25] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Mechrevo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776026770/Afflictions/test2.png, size: 159x167)
[02/19/2023 13:28:25] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Mechrevo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776026770/Particles/aliengrenadeflash.png, size: 400x1814)
[02/19/2023 13:28:25] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Mechrevo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776026770/Particles/artmod_artbloodexplode.png, size: 658x861)
[02/19/2023 13:28:25] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Mechrevo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776026770/Particles/artmod_artexplosion.png, size: 2629x2605)
[02/19/2023 13:28:24] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Mechrevo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776026770/Particles/confetti.png, size: 1169x1114)
[02/19/2023 13:28:23] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Mechrevo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776026770/Particles/electrobolt4.png, size: 30x13)
[02/19/2023 13:28:23] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Mechrevo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776026770/Particles/electrobolt3.png, size: 30x20)
[02/19/2023 13:28:23] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Mechrevo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776026770/Particles/electrobolt2.png, size: 30x13)
[02/19/2023 13:28:23] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Mechrevo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776026770/Particles/electrobolt1.png, size: 30x16)
[02/19/2023 13:28:23] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Mechrevo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776026770/Particles/biotracer.png, size: 1000x325)
[02/19/2023 13:28:23] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Mechrevo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776026770/Particles/doorweld.png, size: 102x12)
[02/19/2023 13:28:20] Item " (identifier: pirateclotheshard)" has no sprite!
[02/19/2023 13:28:20] Item "海盗服装 (identifier: pirateclothes)" has no sprite!
[02/19/2023 13:28:20] Item " (identifier: pirateclothesnovice)" has no sprite!
[02/19/2023 13:28:20] Item "海盗防弹衣 (identifier: piratebodyarmor)" has no sprite!
[02/19/2023 13:28:16] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Mechrevo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2831987252/Items/Herbs/contaminationv1.png, size: 129x128)
[02/19/2023 13:28:16] WARNING: Unrecognized element in affliction "cytokine" (Affliction)
[02/19/2023 13:28:16] WARNING: Unrecognized element in affliction "cytokine" (Affliction)
[02/19/2023 13:28:15] Overriding an affliction or a buff with the identifier 'watchersgaze' using the file 'C:/Users/Mechrevo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2831987252/Afflictions/VANAfflictions.xml'
[02/19/2023 13:28:13] Overriding an affliction or a buff with the identifier 'huskinfection' using the file 'C:/Users/Mechrevo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2085783214/Afflictions.xml'
[02/19/2023 13:28:12] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Mechrevo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2518816103/Text/Barotraumatic.png, size: 1516x265)
[02/19/2023 13:27:24] Attempting to open ALC device "OpenAL Soft on 扬声器 (Realtek(R) Audio)"
[02/19/2023 13:27:15] Logged in as 悲願唄 (SteamID STEAM_1:1:160575787)
```

**Comment by Regalis11** [comment] 2023-02-20 08:48
Seems to be caused by the Gene Splicer+ mod, closing as a duplicate of https://github.com/Regalis11/Barotrauma/issues/11127

**Closed by Regalis11** 2023-02-20 08:48 UTC
