### ISSUE TITLE
Gamecrash after setting multiple greater than components false output to 0

### ISSUE THREAD

**Issue by Melolatius** [Regalis11/Barotrauma#9576] opened 2022-07-15 11:30 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

After placing multiple greater than components and selecting them all, I noticed that the game always crashes when you change their false output/output valie.

### Reproduction steps

1. Go into the editor
2. Place multiple greater than components (for me it were 5)
3. Select them all by SHIFT+clicking
4. Set their false output to 0 / Set their output to 0
5. Game crash
[crashreport (21).log](https://github.com/Regalis11/Barotrauma/files/9120405/crashreport.21.log)
[crashreport (22).log](https://github.com/Regalis11/Barotrauma/files/9120406/crashreport.22.log)
[crashreport (23).log](https://github.com/Regalis11/Barotrauma/files/9120407/crashreport.23.log)

### Bug prevalence

Happens every time I play

### Version

Other

### -

v0.18.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-07-15 13:50
Duplicate of https://github.com/Regalis11/Barotrauma/issues/9512

**Closed by Regalis11** 2022-07-15 13:50 UTC
