### ISSUE TITLE
Crash when hovering the cursor over the outpost icon on the map

### ISSUE THREAD

**Issue by lingerstrike** [Regalis11/Barotrauma#11508] opened 2023-03-14 11:11 UTC
### Disclaimers

- [ ] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

When opening the map and pointing at the outpost, the game breaks

### Bug prevalence

Happens every time I play

### Version

v1.0.7.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 03/14/2023 18:05:30)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

35B85F62D7B9D401E74CE519DDE94DB4

Game version 1.0.7.0 (ReleaseWindows, branch master, revision fa6b6a590f)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync OFF
Language: Russian
Selected content packages: Vanilla, Azov (James Balls), BaroTraumatic, Barotraumatic Creature Pack, Improved Husks, Lua For Barotrauma, MoreMissionsMod, Duffle Bag 2.0, Backpack & WaistBelt - Balanced, Headsight, Neurotrauma, Neurotrauma Cybernetics, Storage Icons, NeuroEyes [fix], Dont Open Debug Console On Errors, Submarine Weapon Sound Makeover, Ogryzok, Frith's Biomes, Stations from beyond, Northumberland and Ogryzok, CsForBarotrauma, BetterHealthUI, ЗигоПлав, Northumberland with OguzOK
Level seed: Chandelle Crevasse80
Loaded submarine: Barsuk (89937A74FF3F968733813208DD44694E)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit
    GPU name: NVIDIA GeForce GTX 1050 Ti
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Boolean CanHaveCampaignInteraction(InteractionType)
Stack trace: 
   at Barotrauma.OutpostGenerationParams.CanHaveCampaignInteraction(InteractionType interactionType) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Outposts\OutpostGenerationParams.cs:line 331
   at Barotrauma.Location.<>c__DisplayClass164_0.<CanHaveCampaignInteraction>b__0(OutpostGenerationParams p) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Location.cs:line 1398
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Barotrauma.Location.CanHaveCampaignInteraction(InteractionType interactionType) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Location.cs:line 1396
   at Barotrauma.Location.CanHaveSubsForSale() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Location.cs:line 1377
   at Barotrauma.Map.CreateLocationInfoOverlay(Location location) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\Map\Map.cs:line 393
   at Barotrauma.Map.Update(CampaignMode campaign, Single deltaTime, GUICustomComponent mapContainer) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\Map\Map.cs:line 557
   at Barotrauma.CampaignUI.UpdateMap(Single deltaTime, GUICustomComponent mapContainer) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\CampaignUI.cs:line 179
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1247
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 916
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[03/14/2023 18:05:30] Could not find human prefab "repairnpc" from "outpostnpcs1".
[03/14/2023 18:05:25] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/14/2023 18:05:13] 
/// Running Neurotrauma V A1.8.4h1 ///
--------------------------------------------
+ Cybernetics V A1.2.3h2

[03/14/2023 18:05:12] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/ПК/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2518816103/Items/BTheadsets.png, size: 337x261)
[03/14/2023 18:05:12] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/ПК/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2831987252/Items/Herbs/Statin.png, size: 37x69)
[03/14/2023 18:05:10] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/14/2023 18:05:10] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/14/2023 18:05:10] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/14/2023 18:05:09] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/14/2023 18:05:09] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/14/2023 18:05:09] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/14/2023 18:05:09] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/14/2023 18:05:09] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/14/2023 18:05:09] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/14/2023 18:05:08] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/14/2023 18:05:08] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/14/2023 18:05:08] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/14/2023 18:05:08] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/14/2023 18:05:08] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/14/2023 18:05:08] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/14/2023 18:05:08] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/14/2023 18:05:08] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/14/2023 18:05:08] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/14/2023 18:05:08] Could not find human prefab "repairnpc" from "outpostnpcs1".
[03/14/2023 18:05:07] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/14/2023 18:05:07] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/14/2023 18:05:06] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/14/2023 18:04:47] Generating an outpost for the start of the level... (Location: Жилой аванпост Chandelle Crevasse, level type: Outpost)
[03/14/2023 18:04:46] Level identifier: coldcavernsoutpostlevel
[03/14/2023 18:04:32] WARNING: Affliction "wasteinfection" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[03/14/2023 18:04:22] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/14/2023 18:04:22] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/14/2023 18:04:22] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/14/2023 18:04:22] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/14/2023 18:04:22] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/14/2023 18:04:22] Could not find human prefab "repairnpc" from "outpostnpcs1".
[03/14/2023 18:04:22] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/14/2023 18:04:22] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/14/2023 18:04:22] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/14/2023 18:04:22] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/14/2023 18:04:22] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/14/2023 18:04:22] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/14/2023 18:04:22] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/14/2023 18:04:22] Could not find human prefab "repairnpc" from "outpostnpcs1".
[03/14/2023 18:04:22] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/14/2023 18:04:22] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/14/2023 18:04:22] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/14/2023 18:04:22] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/14/2023 18:04:22] Could not find human prefab "repairnpc" from "outpostnpcs1".
[03/14/2023 18:04:22] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/14/2023 18:04:22] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/14/2023 18:04:22] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/14/2023 18:04:22] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/14/2023 18:04:22] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/14/2023 18:04:22] Could not find human prefab "repairnpc" from "outpostnpcs1".
[03/14/2023 18:04:22] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/14/2023 18:04:22] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/14/2023 18:04:22] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/14/2023 18:04:22] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/14/2023 18:04:22] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/14/2023 18:04:22] Could not find human prefab "repairnpc" from "outpostnpcs1".
[03/14/2023 18:04:22]  - init.lua (Took 0.00052ms)
[03/14/2023 18:04:22] Checking if NeuroEyes is enabled...
[03/14/2023 18:04:22] NeuroEyes Fixed (With Husk Mod Compatability) 1.0
[03/14/2023 18:04:22]  - init.lua (Took 0.03793ms)
[03/14/2023 18:04:21] Performance Fix 1.0.11
[03/14/2023 18:04:21]  - patch.lua (Took 0.01852ms)
[03/14/2023 18:04:21] Dont Open Debug Console On Errors 1.0.2
[03/14/2023 18:04:21]  - init.lua (Took 0.00948ms)
[03/14/2023 18:04:21] NeuroEyes [fix] enabled.
[03/14/2023 18:04:21] Checking if NeuroEyes [fix] is enabled...
[03/14/2023 18:04:21] NeuroEyes [fix] 1.0.8
[03/14/2023 18:04:21]  - init.lua (Took 0.19155ms)
[03/14/2023 18:04:21] Storage Icons 0.8
[03/14/2023 18:04:21]  - init.lua (Took 0.09625ms)
[03/14/2023 18:04:21] Neurotrauma Cybernetics A1.2.3h2
[03/14/2023 18:04:21]  - init.lua (Took 0.13121ms)
[03/14/2023 18:04:21] Neurotrauma A1.8.4h1
[03/14/2023 18:04:19] Using LuaSetup.lua from the content package.
[03/14/2023 18:04:19] Took 6792ms to compile and run Cs Scripts.
[03/14/2023 18:04:18] BetterHealthUIMod..ctor
[03/14/2023 18:04:12] Added BetterHealthUI 1.0.10 to Cs compilation. (Forced)
[03/14/2023 18:04:11] Cs! Version fa6b6a590f
[03/14/2023 18:04:11] Lua! Version fa6b6a590f
[03/14/2023 18:02:07] WARNING: Potential error in item variant "screwdriverdementonite": the base item "screwdriver" requires x2 "iron" to fabricate. The variant only overrides the required item, not the amount, resulting in a requirement of x2 "screwdriver". Specify the amount in the variant to fix this.
[03/14/2023 18:02:07] WARNING: Potential error in item variant "screwdriverhardened": the base item "screwdriver" requires x2 "iron" to fabricate. The variant only overrides the required item, not the amount, resulting in a requirement of x2 "screwdriver". Specify the amount in the variant to fix this.
[03/14/2023 18:02:00] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/ПК/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2020332046/Biomes/Europan Ridge/Objects/LevelWallEdge.png, size: 4098x512)
[03/14/2023 18:01:49] WARNING: Potential error in item variant "screwdriverdementonite": the base item "screwdriver" requires x2 "iron" to fabricate. The variant only overrides the required item, not the amount, resulting in a requirement of x2 "screwdriver". Specify the amount in the variant to fix this.
[03/14/2023 18:01:49] WARNING: Potential error in item variant "screwdriverhardened": the base item "screwdriver" requires x2 "iron" to fabricate. The variant only overrides the required item, not the amount, resulting in a requirement of x2 "screwdriver". Specify the amount in the variant to fix this.
[03/14/2023 18:01:46] Overriding an affliction or a buff with the identifier 'combatstimulant' using the file 'C:/Users/ПК/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[03/14/2023 18:01:46] Overriding an affliction or a buff with the identifier 'implacable' using the file 'C:/Users/ПК/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[03/14/2023 18:01:46] Overriding an affliction or a buff with the identifier 'concussion' using the file 'C:/Users/ПК/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[03/14/2023 18:01:46] Overriding an affliction or a buff with the identifier 'radiationsickness' using the file 'C:/Users/ПК/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[03/14/2023 18:01:46] Overriding an affliction or a buff with the identifier 'drunk' using the file 'C:/Users/ПК/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[03/14/2023 18:01:46] Overriding an affliction or a buff with the identifier 'invertcontrols' using the file 'C:/Users/ПК/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[03/14/2023 18:01:46] Overriding an affliction or a buff with the identifier 'chemwithdrawal' using the file 'C:/Users/ПК/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[03/14/2023 18:01:46] Overriding an affliction or a buff with the identifier 'chemaddiction' using the file 'C:/Users/ПК/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[03/14/2023 18:01:46] Overriding an affliction or a buff with the identifier 'opiatewithdrawal' using the file 'C:/Users/ПК/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[03/14/2023 18:01:46] Overriding an affliction or a buff with the identifier 'opiateoverdose' using the file 'C:/Users/ПК/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[03/14/2023 18:01:46] Overriding an affliction or a buff with the identifier 'opiateaddiction' using the file 'C:/Users/ПК/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[03/14/2023 18:01:46] Overriding an affliction or a buff with the identifier 'acidburn' using the file 'C:/Users/ПК/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[03/14/2023 18:01:46] Overriding an affliction or a buff with the identifier 'burn' using the file 'C:/Users/ПК/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[03/14/2023 18:01:46] Overriding an affliction or a buff with the identifier 'explosiondamage' using the file 'C:/Users/ПК/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[03/14/2023 18:01:46] Overriding an affliction or a buff with the identifier 'organdamage' using the file 'C:/Users/ПК/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[03/14/2023 18:01:46] Overriding an affliction or a buff with the identifier 'gunshotwound' using the file 'C:/Users/ПК/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[03/14/2023 18:01:46] Overriding an affliction or a buff with the identifier 'bitewounds' using the file 'C:/Users/ПК/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[03/14/2023 18:01:46] Overriding an affliction or a buff with the identifier 'lacerations' using the file 'C:/Users/ПК/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[03/14/2023 18:01:46] Overriding an affliction or a buff with the identifier 'blunttrauma' using the file 'C:/Users/ПК/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[03/14/2023 18:01:46] Overriding an affliction or a buff with the identifier 'internaldamage' using the file 'C:/Users/ПК/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[03/14/2023 18:01:46] Overriding an affliction or a buff with the identifier 'bleedingnonstop' using the file 'C:/Users/ПК/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[03/14/2023 18:01:46] Overriding an affliction or a buff with the identifier 'bleeding' using the file 'C:/Users/ПК/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[03/14/2023 18:01:46] Overriding an affliction or a buff with the identifier 'sufforinpoisoning' using the file 'C:/Users/ПК/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[03/14/2023 18:01:46] Overriding an affliction or a buff with the identifier 'cyanidepoisoning' using the file 'C:/Users/ПК/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[03/14/2023 18:01:46] Overriding an affliction or a buff with the identifier 'morbusinepoisoning' using the file 'C:/Users/ПК/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[03/14/2023 18:01:46] Overriding an affliction or a buff with the identifier 'bloodloss' using the file 'C:/Users/ПК/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[03/14/2023 18:01:46] Overriding an affliction or a buff with the identifier 'oxygenlow' using the file 'C:/Users/ПК/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[03/14/2023 18:01:43] Overriding an affliction or a buff with the identifier 'huskinfection' using the file 'C:/Users/ПК/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2085783214/Afflictions.xml'
[03/14/2023 18:01:38] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/ПК/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2831987252/Items/Herbs/contaminationv1.png, size: 129x128)
[03/14/2023 18:01:38] WARNING: Unrecognized element in affliction "cytokine" (Affliction)
[03/14/2023 18:01:38] WARNING: Unrecognized element in affliction "cytokine" (Affliction)
[03/14/2023 18:01:38] Overriding an affliction or a buff with the identifier 'watchersgaze' using the file 'C:/Users/ПК/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2831987252/Afflictions/VANAfflictions.xml'
[03/14/2023 18:01:36] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/ПК/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2518816103/Text/Barotraumatic.png, size: 1516x265)
[03/14/2023 18:00:47] Attempting to open ALC device "OpenAL Soft on Динамики (2- Redragon Gaming Headset)"
[03/14/2023 18:00:43] Logged in as Глиномес (SteamID STEAM_1:0:466588047)
```

**Comment by Regalis11** [comment] 2023-03-14 11:18
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11496

**Closed by Regalis11** 2023-03-14 11:18 UTC
