### ISSUE TITLE
[0.10.2.0] Issues that happens when you reach The End

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3297] opened 2020-07-04 00:47 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
- [x] Merchant's wallet doesn't reset. They'll still be poor if you sold them broke in the first playthrough.
- [x] Previously unlocked missions are still posted on every locations you picked them up for.
- [x] Outpost Events that plays as soon as you start the next round after "The End" overlaps with "Haven't we done all this before?" dialogue (Like the new blood talk event). Closing the dialogue ends the Outpost event.
- [x] Anything you did in "The End" level is not saved. Character Data and Submarine state,
- [x] Any subinventory you opened up overlays the ending cutscene.

**Version**
0.10.2.0

**Comment by Regalis11** [comment] 2020-07-06 14:15
Everything else should be fixed now, but I couldn't reproduce the last issue. Does the subinventory get displayed on top of the ending video, the credits, the "haven't we done all this before" text overlay, or all of them? Single player, multiplayer or both?

**Comment by Kaillera** [comment] 2020-07-06 14:18
![](https://media.discordapp.net/attachments/668819422919524352/728767178911776810/SPOILER_Capture.PNG)

**Comment by Rokvach** [comment] 2020-07-10 12:07
Should all the map markers and location progressions (natural formation -> research outpost) also reset after the ending?

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/aa63e09a-d4da-4efa-ae77-07bff382463f)

**Comment by Rokvach** [comment] 2020-07-10 12:17
All the issues has been fixed, working correctly. Closing.

**Closed by Rokvach** 2020-07-10 12:17 UTC
Labels: Bug, Code
