### ISSUE TITLE
Wire has wrong direction after copying

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#11464] opened 2023-03-06 08:57 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

the wire direction or whatever it's called can get messed up during copy-pasting. possibly related to selection/ entity order fun.

this makes making guide/educational submarines more difficult.

### Reproduction steps

1. place 2 components 
2. wire them 
3. select both, copy paste
4. edit the wires

example is done with a delay and a door

[Barotrauma_23-03-06--lFDE6AyVUx.webm](https://user-images.githubusercontent.com/5103517/223062403-8259801c-dceb-46c4-a334-bbfffe3e9951.webm)

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-03-06 09:05
Most likely related to (or a duplicate of) https://github.com/Regalis11/Barotrauma/issues/9274

**Comment by Regalis11** [comment] 2023-03-10 07:32
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b614b410f5d56f542b2bf69382649bf53cd5e33f

**Closed** 2023-05-10 11:54 UTC
Labels: Bug, Code
