### ISSUE TITLE
[unstable] Don't create server

### ISSUE THREAD

**Issue by funplay650** [Regalis11/Barotrauma#12259] opened 2023-07-01 14:46 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

rus man
Попытка создать сервер

### Reproduction steps

1.Создать сервер
2.выбрал настройки
3.Запуск сервера

### Bug prevalence

Happens regularly

### Version

Other

### -

version unstable

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Failed to start ChildServerRelay Process. File: DedicatedServer.exe, arguments: -name "Debilogame" -public True -playstyle SomethingDifferent -banafterwrongpassword False -karmaenabled False -maxplayers 16 -language "Russian" -password "1" -steamid 76561198204764701 -ownerkey 1439948857 -pipes 2676 6072
Failed to start server {An error occurred trying to start process 'DedicatedServer.exe' with working directory 'D:\SteamLibrary\steamapps\common\Barotrauma'. Отказано в доступе.}
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Barotrauma.Networking.ChildServerRelay.Start(ProcessStartInfo processInfo) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\ChildServerRelay.cs:line 32
   at Barotrauma.MainMenuScreen.StartServer() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\MainMenuScreen.cs:line 952
```

**Comment by Regalis11** [comment] 2023-07-03 08:36
Thank you for the report! This seems to be a duplicate of https://github.com/Regalis11/Barotrauma/issues/11489 (although in this case it's failing to access the server executable instead of the config file.

It should be possible to fix the issue as described here: https://github.com/Regalis11/Barotrauma/issues/11522#issuecomment-1471204963

**Closed by Regalis11** 2023-07-03 08:36 UTC
