### ISSUE TITLE
Woman selling alien pistol for 1k marks not checking if player has enough

### ISSUE THREAD

**Issue by Cosmitz** [Regalis11/Barotrauma#3443] opened 2020-07-31 15:19 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The event in which a  woman is selling an Alien Pistol + magazine for 1k marks does not check if the player has enough marks, she just tries to remove 1k and takes however much the player has if he's under 1k, but still hands him the pistol.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac). v0.10.4.0

**Additional information**
I had the marks upon loading station, but i traded and only had 800 or so when she approached.

**Comment by 3e849f2e5c** [comment] 2020-08-04 07:05
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3219

**Closed by 3e849f2e5c** 2020-08-04 07:05 UTC
