### ISSUE TITLE
Boxes floating in the Remora fabricator room

### ISSUE THREAD

**Issue by BigSweatyMen** [Regalis11/Barotrauma#9418] opened 2022-06-19 23:34 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When items (coil gun ammo, metal crate) were dropped on the ground in the Remora fabricator room in multiplayer, they disappeared/started glitching through the floor and ceiling. We just started with this ship and are still docked at a station.
![image](https://user-images.githubusercontent.com/107653064/174504423-18db0561-d4c7-4f0d-8c47-5b4aaeb49574.png)

### Reproduction steps

Kinda self explanatory, drop ammo boxes on the ground in that room in multiplayer, probably while still docked. 

### Bug prevalence

Happens regularly

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-06-20 13:09
I'm afraid I could not reproduce this:
![image](https://user-images.githubusercontent.com/14351070/174608870-2457dab3-41e2-465a-a44c-5f98c62cd950.png)

So I guess this requires some more specific circumstances to occur, but I couldn't figure out what that is. :/

**Comment by Regalis11** [comment] 2022-07-18 15:33
No known steps to repro, closing

**Closed by Regalis11** 2022-07-18 15:33 UTC
Labels: Bug, Need more info, Code
