### ISSUE TITLE
Prow hull pieces move/default to their original Y axis placement

### ISSUE THREAD

**Issue by Urso357** [Regalis11/Barotrauma#1740] opened 2019-07-04 05:27 UTC
- [X ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The prow of a ship with embeded coil arrays will move after firing said array. Seems to only happen in multiplayer after a first mission is completed.

**Steps To Reproduce**
I had a bit of trouble reproducing it at will, but it happened at least 10 times over the past few days.
Take this sub:
https://steamcommunity.com/sharedfiles/filedetails/?id=1787449535&searchtext=hammerhead
Run a campaign mission, use the coil discharge at the command station. Might take a second mission for it to happen.

**Version**
Running on a PC (Windows), version v9.0.7 

**Additional information**
This is how the prow will look like if the bug is successfully replicated:
https://media.discordapp.net/attachments/427654262453960724/596193097440952330/unknown.png?width=856&height=481

**Comment by Regalis11** [comment] 2019-07-12 10:45
Unfortunately I haven't found a way to reproduce this even after completing dozens of rounds on the Hammerhead. It seems that the scale of the front pieces reverts to the default value for some reason, but I don't see how it could be related to the coils.

**Comment by Urso357** [comment] 2019-07-15 06:00
I will look into it to see if it happens on another ship, so they randomly reset to prefab right?

**Comment by Regalis11** [comment] 2019-07-30 10:32
I think https://github.com/Regalis11/Barotrauma-development/commit/f856a19 (private repo) should fix this.

**Comment by Rokvach** [comment] 2019-08-02 10:13
This seems to be working correctly now. Closing.

**Closed by Rokvach** 2019-08-02 10:13 UTC
Labels: Bug, Code, Low prio, Need more info

**Comment by Urso357** [comment] 2019-08-02 23:14
Just had It happen, but not on test version.
One of my subs tail fin reset to default characteristics.

Em sex, 2 de ago de 2019 07:13, Roni Kovaniemi <notifications@github.com>
escreveu:
