### ISSUE TITLE
Dead crew coming back alive

### ISSUE THREAD

**Issue by mcastaneda82** [Regalis11/Barotrauma#3575] opened 2020-08-15 19:50 UTC
- Hi, yes: I have searched the issue tracker to check if the issue has already been reported and also asked around in the Discord general channel and no one seemed to have ran into my issue.

**Description**
After death during a mission, my crew are "back from the death" when entering a station.

**Steps To Reproduce**
Happened twice already, first with a single crew member, then with my whole crew except one member: to reproduce... get people killed, then head back to a station and see if it comes back to life.

**Version**
Windows 10, vanilla download from Steam a week ago.

**Additional information**
Mmm... I got video footage I intended for my youtube channel where you can see what I'm talking about, if interested.

**Comment by rico6822** [comment] 2020-08-15 21:18
> 
> Mmm... I got video footage I intended for my youtube channel where you can see what I'm talking about, if interested.
Why won't you just post it?

**Comment by mcastaneda82** [comment] 2020-08-15 22:14
> Why won't you just post it?

Here's one of them: https://www.youtube.com/watch?v=N5JYo4_Sb8M&t

You can skip to 47:54 in which the Captain is killed because of husk infection. (you can confirm at the very end of the video in the debriefing "died of interal injuries")

But once inside City of Moulin: https://www.youtube.com/watch?v=G3WikRGnw4c
you can see in the very beginning of the episode the Captain is alive again.

Still uploading the other video in which this same thing happens but with multiple crew at the same time. Will post links when done.

**Comment by Kaillera** [comment] 2020-08-17 10:09
I remember this bug. I can't find the ticket that I made about it anymore but it's when bots corpses respawn due to being taken out of the sub, they'll come back next round.

**Comment by Regalis11** [comment] 2020-08-19 09:19
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/fa503573fe3cc11c78b992a9dc08dfd85ec0c8de

**Comment by Rokvach** [comment] 2020-09-09 11:14
Tested, wasn't able to reproduce the issue. Seems to be working correctly, closing.

**Closed by Rokvach** 2020-09-09 11:14 UTC
Labels: Bug, Code
