### ISSUE TITLE
Game crashes after pressing the "New Game" button.

### ISSUE THREAD

**Issue by Cyborgcr** [Regalis11/Barotrauma#1732] opened 2019-07-02 15:36 UTC
In the main menu, right after (or after a short delay) a **NEW GAME** button is pressed, the game crashes. A massage then follows: 

_Oops! Barotrauma just crashed.
A crash report ("crashreport (x).log") was saved in the root folder of the game and sent to the developers._

This happened on both post-release patches, but not the original Steam release. I use Windows 10 as an operating system.
![Crash](https://user-images.githubusercontent.com/46865336/60526036-32d2a980-9cf8-11e9-9982-70d301fd1bb7.PNG)

**Comment by Regalis11** [comment] 2019-07-03 08:18
Could you please send the crash report?

**Comment by Cyborgcr** [comment] 2019-07-03 09:14
Here.
![The_report](https://user-images.githubusercontent.com/46865336/60579595-17b17980-9d8c-11e9-85d2-019967c54827.PNG)

**Comment by Regalis11** [comment] 2019-07-04 08:10
Looks like one of your submarine files is corrupted. We've fixed this issue for the next patch, but for now you should be able to work around it by deleting the "Submarines/Downloaded/Ocean Glider" submarine from the game folder.

**Comment by Regalis11** [comment] 2019-07-04 09:32
Duplicate of #1561

**Closed by Regalis11** 2019-07-04 09:32 UTC
Labels: Bug, Code, Crash
