### ISSUE TITLE
Depth Charge Shell going through the Map

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2740] opened 2020-04-29 21:18 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Was trying to anchor some hammerhead with my depth charges, but it turns out they fall through the map walls. Explosives shells will detonate on the wall and fall through afterward.
https://www.youtube.com/watch?v=69lZBkTxPBw

**Version**
0.9.9.1

**Comment by Regalis11** [comment] 2020-05-03 17:21
Seems to have been caused by the same bug as #2759, fixed in https://github.com/Regalis11/Barotrauma-development/commit/db212e4009ced96329f4e4e1c878f73c8520d520

**Comment by Rokvach** [comment] 2020-05-03 21:58
No issues, closing.

**Closed by Rokvach** 2020-05-03 21:58 UTC
Labels: Bug, Code
