### ISSUE TITLE
High pressure in ship's walls

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#769] opened 2018-09-06 03:44 UTC
There was water effect in the wall between two rooms and it killed me when i went into it.

**Comment by Baywatcher11** [comment] 2018-09-06 05:08
There seems to be water in doors and hatches as well.

**Comment by thegrb93** [comment] 2018-09-06 06:15
I've seen it in docking hatch, but not doors/hatches

**Comment by rico6822** [comment] 2018-09-06 12:09
![2h7id9](https://user-images.githubusercontent.com/41470757/45156436-7646af00-b1de-11e8-89bc-2cdea809b3f8.jpg)

**Comment by Regalis11** [comment] 2018-09-06 15:32
Do you remember which sub this happened in? Could be that the sub designer simply hadn't placed a hull there.

**Comment by thegrb93** [comment] 2018-09-06 16:26
It was one of the variants of Aegir and it was in-between the reactor room and the airlock room. Probably the designer's fault

**Comment by rico6822** [comment] 2018-09-06 19:34
> BlueTheKing reacted with confused emoji

It's an old meme parodying Gabe Newell to be developing a lot of original and very good video games, that however have tons of sometimes absurd glitches.

**Comment by juanjp600** [comment] 2018-09-06 23:35
@rico6822 Just gonna say this is not really the place for memes, let alone explanations of said memes.

**Comment by Regalis11** [comment] 2018-09-26 12:35
#827 is a duplicate of this, but it has more information about the problem so I'll close this one instead.

**Closed by Regalis11** 2018-09-26 12:35 UTC
Labels: Gameplay-related, bug
