### ISSUE TITLE
[0.1002.0] Can replay Outpost Event by Re-entering scumming.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3076] opened 2020-06-12 12:52 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
You can replay Outpost Event by Re-entering scumming.

**Version**
0.1002.0

**Additional information**
I think the best thing to do regarding with outpost events is to disable the event after it has played. Once the players reaches a new location, the previous location would regenerate a new random event at that outpost. Probably give each event an ID and log it into the save file that the event has already been played out.

**Comment by Regalis11** [comment] 2020-06-13 12:57
Duplicate of #3050

**Closed by Regalis11** 2020-06-13 12:57 UTC
