### ISSUE TITLE
Deconstructor Not Outputting Into Crates

### ISSUE THREAD

**Issue by gerakis** [Regalis11/Barotrauma#7797] opened 2021-12-16 08:43 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When deconstructing any item, if there is a crate in the deconstructor's output slots, the output will not put it into the crate like before. It just dumps it in any remaining slots or on the floor.

**Steps To Reproduce**
Put an empty crate into the deconstructor's output slots. Deconstruct an item. The product from the deconstruction will not go into the crate.

**Version**
v0.15.21.0 Windows 10 x64

**Additional information**
This was in multiplayer. This only started happening after the new update.

**Comment by Regalis11** [comment] 2021-12-16 11:19
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7699

**Closed by Regalis11** 2021-12-16 11:19 UTC
