### ISSUE TITLE
Custom depth charge launcher crashes when activated [Modded]

### ISSUE THREAD

**Issue by avocadros** [Regalis11/Barotrauma#7270] opened 2021-11-11 20:58 UTC
I have searched the issue tracker, and a similar issue has been reported, but was marked as "fixed" on Feb. 22 in https://github.com/Regalis11/Barotrauma/issues/5104

**Description**
I created a custom depth charge launcher and loader whose only difference from the regular launcher is that it launches flares instead of depth charges. Their code is completely identical other than the item used. When I load and fire the launcher, it crashes the game with an "Object reference not set to an instance of an object" error.

**Steps To Reproduce**
I placed down the custom loader and launcher in the sub editor, linked them, then wired a button to the launcher. Placing a flare in the loader and pressing the button produces the crash.

**Version**
I am using the latest stable build on a Windows 10 computer.

**Comment by Regalis11** [comment] 2021-11-12 08:39
Hello and thank you for the report!

I'm afraid I couldn't get this to crash the game. I tested it with the following configs (which should be identical to the normal depth charge loader and launcher, aside from flares being containable in the loader):

```
<Item name="depth charge loader 2" identifier="depthchargeloader2" tags="depthchargeammosource" category="Machine" linkable="true" allowedlinks="depthchargelauncher" scale="0.5">
  <Sprite texture="TurretsAndDepthCharges.png" depth="0.8" sourcerect="354,2,125,188" origin="0.5,0.5" />
  <ItemContainer hideitems="false" drawinventory="true" capacity="1" maxstacksize="1" itempos="62,-117" itemrotation="-90" canbeselected="true" msg="ItemMsgInteractSelect">
    <GuiFrame relativesize="0.2,0.25" anchor="Center" minsize="140,170" maxsize="280,280" style="ItemUI" />
    <Containable items="flare" />
  </ItemContainer>
</Item>
<Item name="depth charge tube 2" identifier="depthchargetube2" tags="depthchargelauncher" category="Machine" focusonselected="true" offsetonselected="700" linkable="true" allowedlinks="depthchargeammosource" scale="0.5">
  <Sprite texture="TurretsAndDepthCharges.png" depth="0.01" sourcerect="259,1,85,149" origin="0.5,0.5" />
  <Turret canbeselected="false" linkable="true" characterusable="false" barrelpos="42, 149" rotationlimits="90,90" powerconsumption="0.0" />
  <ConnectionPanel selectkey="Action" canbeselected="true" msg="ItemMsgRewireScrewdriver" hudpriority="10">
    <GuiFrame relativesize="0.2,0.32" minsize="400,350" maxsize="480,420" anchor="Center" style="ConnectionPanel" />
    <RequiredItem items="screwdriver" type="Equipped" />
    <input name="trigger_in" displayname="connection.turrettriggerin" />
  </ConnectionPanel>
</Item>
```

When I tried to trigger the launcher with a wired button, nothing happened: the game logic seems to ignore the flare completely because it doesn't have a Projectile component. 

Would it be possible to send us the crash report you got? That'd probably make it much easier for us to figure out what the problem is. Thanks and sorry for the inconvenience!

**Comment by avocadros** [comment] 2021-11-14 22:03
No problem. The crash report is attached. 
I'm kicking myself for not including this in the initial post - I did add a Projectile component to the flare to make it usable in the flare launcher. 
Perhaps it's something to do with LaunchRotation? It's linked to a field called "Nullable`1."
[crashreport (34).log](https://github.com/Regalis11/Barotrauma/files/7534775/crashreport.34.log)

**Comment by Regalis11** [comment] 2021-11-15 11:00
This seems to have been caused by the same issue as https://github.com/Regalis11/Barotrauma/issues/7246: projectiles without an Attack element in the xml would throw an exception when launched. Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/2481b392783e9ee15ad2eb7afcee33c8fec8ef62, but until the fix is out, it should be possible to work around the problem by adding an (empty) Attack element to the flare.

**Closed** 2021-11-15 11:00 UTC
Labels: Bug, Duplicate, Code, Crash, Modding

**Comment by avocadros** [comment] 2021-11-15 18:28
Weird! I never would have figured that out. Thanks for taking the time to work through this with me, though, it really is appreciated.
