### ISSUE TITLE
Attempt to take an event mission freezes gameplay

### ISSUE THREAD

**Issue by ghost** [Regalis11/Barotrauma#12313] opened 2023-07-09 16:04 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

An attempt to pick that dialogue option froze the gameplay.
Character can rotate left-right.
[Escape] menu and console can be opened (I opened the console manually, just in case).
Nothing else can be done.
I've exited the game through [Alt]+[F4] so the save is a squeaking-clean docking save ready to reproduce the problem (or gather evidence).
The only oddity I've spotted prior the issue is that previous visited outpost gave me only 1 (one) quest: clown personnel transport. I thought that outpost master must always give two generic quests - but I've either failed to find that NPC (no marker was visible) or bumped onto one more bug...
![20230709184317_1](https://github.com/Regalis11/Barotrauma/assets/81986452/d4b3f559-b94e-4510-86c1-dbb168138811)
Content of /home/%that-s-a-me%/.local/share/Daedalic Entertainment GmbH/Barotrauma + config file in attachment.
No issues were encountered during multiplayer.
No mods, nor modded submarines, neither CLI options used.
[btqfr.zip](https://github.com/Regalis11/Barotrauma/files/11995571/btqfr.zip)

### Reproduction steps

Load the save (made in singleplayer).
Rush to topmost quest giver.
2 (two) NPCs with event dialogue markings should spawn there side by side with generic quest giver.
Once all three NPCs would gonna stand on the very same spot, get all quests from generic quest giver.
Initiate the conversation with event NPC from screenshot.
See the game freeze.

### Bug prevalence

Just once

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Linux

**Comment by giists** [comment] 2023-07-12 10:43
Unfortunately I couldn't reproduce this. Even in the rare case where I managed to get the npcs on top of each other the events just triggered normally.

**Comment by NilanthAnimosus** [comment] 2023-09-08 07:44
Managed to reproduce this on 1.0.21.0 (windows singleplayer) using the save, Had to disablecrewai and teleport the NPC's whom had the missions to the room with the mission giver.

There is a delay before conversation starts when interacting with the others after the mission giver, which is when you can activate two conversations at once and appear to break the game:

![image](https://github.com/Regalis11/Barotrauma/assets/29177976/43b4a511-ebb3-49f7-ac6d-f957662354c2)

going to test if I can repro this in the current build a second time.

**Comment by Regalis11** [comment] 2023-09-11 13:13
Seems to have been caused by the same issue as https://github.com/Regalis11/Barotrauma/issues/12527, moving to QA

**Comment by Jasontti** [comment] 2023-09-12 10:54
Tested with and without the fix.
Using Nilanths steps i was able to reproduce this easily.
With fix applied issue went away. You can still activate multiple dialogues and the last one will interrupt the earlier, but earlier dialogue will come back after latter one is finished.
Closing ticket as fixed.

**Closed by Jasontti** 2023-09-12 10:54 UTC
Labels: Bug, Code
