### ISSUE TITLE
Server disconnect with console error

### ISSUE THREAD

**Issue by 80nph1r3** [Regalis11/Barotrauma#6386] opened 2021-07-31 09:25 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
One or few players disconnected from server and weren't able to reconnect without rehosting. 
**Steps To Reproduce**
Happened every time the submarine docked to or undocked from the station.

**Version**
0.14.6.0 Windows 10 21H1 19043.1110

**Additional information**
The console showed error about the world, generated on the client side not matching the world, generated on the server side. I also attached the log file.
[event_error_log_client_B-b-b-b-b-bonfire_1923.log](https://github.com/Regalis11/Barotrauma/files/6910950/event_error_log_client_B-b-b-b-b-bonfire_1923.log)

**Comment by 80nph1r3** [comment] 2021-07-31 20:42
![Screenshot_1](https://user-images.githubusercontent.com/71520620/127751994-482ca073-ebb3-4393-828a-27e6df321ac7.png)
![Screenshot_4](https://user-images.githubusercontent.com/71520620/127751995-5e8b0cec-159a-4a24-beb4-1e8eb77c150d.png)

**Comment by Regalis11** [comment] 2021-11-10 10:42
Duplicate of https://github.com/Regalis11/Barotrauma/issues/2723

**Closed by Regalis11** 2021-11-10 10:42 UTC
Labels: Bug, Code, Networking
