### ISSUE TITLE
NPCs get stuck on the stairs

### ISSUE THREAD

**Issue by KBJS17** [Regalis11/Barotrauma#13251] opened 2024-01-02 15:33 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Sometimes NPCs get stuck on the stairs in a kind of laboratory.
![20240102155920_1](https://github.com/Regalis11/Barotrauma/assets/101461013/c8477682-a5a5-4186-b4cc-56437df31d9d)
Even sometimes the outpost manager runs to these stairs after talking to him and stuck.

### Reproduction steps

1. Start a single-player campaign.
2. Go to Colony
3. Start talking with the outpost manager (or just go to these stairs and sometimes you may notice NPCs stuck there)
4. After getting the assignments, save the game and load the save
5. Go to the outpost manager and talk with him
6. Then he starts running to the stairs

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Single player

### Version

v1.2.7.0 (Winter Update hotfix)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2024-01-02 16:38
Duplicate of https://github.com/Regalis11/Barotrauma/issues/12888

**Closed by Regalis11** 2024-01-02 16:38 UTC
