### ISSUE TITLE
Unknown Issue, please help!

### ISSUE THREAD

**Issue by Abobus123457890** [Regalis11/Barotrauma#7967] opened 2021-12-31 18:28 UTC
Barotrauma seems to have crashed. Sorry for the inconvenience! 

0120CFF13F68A29ABC62BE1077A0F8E0

Game version 0.15.12.0 (ReleaseWindows, branch release, revision 575e12eab6)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: Russian
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.NetLobbyScreen
SteamManager initialized
Client (Round hadn't been started)

System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce GTX 750 Ti
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,7777778}
    GPU status: Normal

Exception: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Экземпляр устройства GPU приостановлен. Для определения соответствующего действия используйте GetDeviceRemovedReason.
 (SharpDX.SharpDXException)
Device removed reason: HRESULT = 0x887A0005
Target site: Void CheckError()
Stack trace: 
   at SharpDX.Result.CheckError()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 1017
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 511
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 60

Last debug messages:
[31.12.2021 21:27:29] Lobby created!
[31.12.2021 21:27:02] (Msg) SDR RelayNetworkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[31.12.2021 21:27:02] (Msg) Ping location: sto=52+5,sto2=61+6/52+5,ams=90+9/72+5,waw=99+9/73+5,lhr=92+9/77+5,fra=77+7/79+5,vie=84+8/83+5,par=94+9/87+5,mad=103+10/103+5,iad=152+15/160+5,sgp=260+26/238+20,gru=266+26
[31.12.2021 21:27:02] (Msg) Ping measurement completed
[31.12.2021 21:27:02] (Debug) Destroying relay 'bom#42 (155.133.233.99:27018)' because initial_ping_timeout
[31.12.2021 21:27:00] (Debug) Destroying relay 'bom#41 (155.133.233.99:27017)' because initial_ping_timeout
[31.12.2021 21:26:57] (Verbose) Communications with routing cluster 'seo' established.
[31.12.2021 21:26:57] (Verbose) Communications with routing cluster 'tyo' established.
[31.12.2021 21:26:57] (Verbose) Communications with routing cluster 'tyo1' established.
[31.12.2021 21:26:57] (Verbose) Communications with routing cluster 'syd' established.
[31.12.2021 21:26:57] (Verbose) Communications with routing cluster 'sgp' established.
[31.12.2021 21:26:57] (Verbose) Communications with routing cluster 'scl' established.
[31.12.2021 21:26:57] (Verbose) Communications with routing cluster 'lim' established.
[31.12.2021 21:26:57] (Verbose) Communications with routing cluster 'jnb' established.
[31.12.2021 21:26:57] (Verbose) Communications with routing cluster 'maa' established.
[31.12.2021 21:26:57] (Verbose) Communications with routing cluster 'sea' established.
[31.12.2021 21:26:57] (Verbose) Communications with routing cluster 'lax' established.
[31.12.2021 21:26:57] (Verbose) Communications with routing cluster 'eze' established.
[31.12.2021 21:26:57] (Verbose) Communications with routing cluster 'waw' established.
[31.12.2021 21:26:57] (Verbose) Communications with routing cluster 'vie' established.
[31.12.2021 21:26:57] (Verbose) Communications with routing cluster 'gru' established.
[31.12.2021 21:26:57] (Verbose) Communications with routing cluster 'sto2' established.
[31.12.2021 21:26:57] (Verbose) Communications with routing cluster 'sto' established.
[31.12.2021 21:26:57] (Verbose) Communications with routing cluster 'ord' established.
[31.12.2021 21:26:57] (Verbose) Communications with routing cluster 'hkg' established.
[31.12.2021 21:26:57] (Verbose) Communications with routing cluster 'dxb' established.
[31.12.2021 21:26:57] (Verbose) Communications with routing cluster 'mad' established.
[31.12.2021 21:26:57] (Verbose) Communications with routing cluster 'par' established.
[31.12.2021 21:26:57] (Verbose) Communications with routing cluster 'dfw' established.
[31.12.2021 21:26:57] (Verbose) Communications with routing cluster 'lhr' established.
[31.12.2021 21:26:57] (Verbose) Communications with routing cluster 'atl' established.
[31.12.2021 21:26:57] (Verbose) Communications with routing cluster 'iad' established.
[31.12.2021 21:26:57] (Verbose) Communications with routing cluster 'ams' established.

**Comment by Regalis11** [comment] 2022-01-03 08:09
Duplicate of https://github.com/Regalis11/Barotrauma/issues/1833

**Closed by Regalis11** 2022-01-03 08:09 UTC
