### ISSUE TITLE
[Factions] Coalition Outpost Layering Issues

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10994] opened 2023-01-21 01:56 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This will essentially be the same format as #10478 and #10931 but for Coalition outpost modules. 

![image](https://user-images.githubusercontent.com/105495756/213835845-e980dd62-91e8-45d6-ad70-91472c2df029.png)
_Figure 1. Vending Machine clips over the platform._

![image](https://user-images.githubusercontent.com/105495756/213835869-1aa4d1ba-1571-4f38-a147-75dced798999.png)
_Figure 2. The wheelchair (left), pillar (left), ladder (centre), and floor (right) all clip over the floor._

![image](https://user-images.githubusercontent.com/105495756/213835879-cc0c0fe6-643f-4ba4-887f-1b06b0688777.png)
_Figure 3. The showseed command for figure 2's outpost._

### Bug prevalence

Happens every now and then

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by IiroEnges** [comment] 2023-01-25 13:01
Figure 2 depicts medicalmodule_02, but the overlap is actually another module's top (which I can't determine based on the screenshot)

**Comment by Wheatley1002** [comment] 2023-01-25 13:41
> but the overlapping "floor" is actually another module's ceiling

I didn't even realise this due to the LOS shadow. That seems more of a generation issue than a layering one, had I noticed during the session I would've taken a freecam screenshot of the whole module so the conflict could be highlighted

**Comment by Regalis11** [comment] 2023-01-26 16:42
Tested, the layering issues seem to be fixed now. The issue in the medical module seems to be an outpost generation issue (another module is slightly overlapping the medical module), but I don't think there's enough information here to reproduce that one (we'd need to know the exact version this happened in, that seed doesn't seem to generate the same outpost in the recent versions).

 > I don't know how to enable the detailed extended showseed command (afaik it's not on the wiki but I've seen people display it)

I'm not aware of anything like that either. The showseed command should show everything needed to generate the level.

**Closed by Regalis11** 2023-01-26 16:42 UTC
Labels: Bug, Art, Low prio

**Comment by Wheatley1001** [comment] 2023-01-28 04:06
Found a pretty major issue with layering for the Coalition colonies. This staircase prevents players from walking past it from the right side. Even whilst holding "S" players are unable to walk past it. Additionally, climbing the staircase is quite awkward though I'm unsure if this is related to the layering issue.
![image](https://user-images.githubusercontent.com/105495756/215241182-cb13f7e9-5306-4da7-8afd-90653472103a.png)
