### ISSUE TITLE
[0.9.10.0] Multiplayer - Explosive Cargo, Volatile Compound N prevented rejoining?

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2876] opened 2020-05-22 15:08 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Had a player who disconnected and tried to rejoin the server after we had thrown out the Volatile Compound N back at the station and it exploded. He got this error message and was unable to rejoin until next round. Not sure if it was related.
![](https://cdn.discordapp.com/attachments/668819422919524352/713401474553479218/unknown.png)
![](https://cdn.discordapp.com/attachments/668819422919524352/713405711400304727/desync_error.jpg)
![](https://cdn.discordapp.com/attachments/668819422919524352/713406039533420654/end_of_round_error.jpg)

Another player get the excessive desync errors instead.

**Version**
<0.9.10.0 RC1

**Comment by Regalis11** [comment] 2020-05-22 15:48
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/dc660c1bc839511153faf5cca355236a5031f17b.

Steps to repro:
1. Start a campaign round with any cargo mission
2. Cause a disconnect somehow (for example "forcetimeout" command in debug builds)
3. Try to reconnect

This happened because the clients would create a list of the cargo items it spawns and check that it has the same number of items as the server. The problem was that the clients would never clear the list, so if you restarted the same mission instance, the old items would still be in the list and trigger this error.

**Comment by Rokvach** [comment] 2020-05-25 10:24
Every time I try and boot up a Cargo mission I get disconnected from the server at round start @Regalis11 

Server: Dedicated
Build: Debug
Branch: release
Mission type: Cargo (Works correctly on other mission types)
Seed: 3dLv0Ex2 (Doesn't seem to make a difference)

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/545c33ae-a264-42be-9649-8587dfc9ba88)

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/533fb233-8c22-4507-8b54-0574b6790422)

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/e4ef6962-ea4f-444f-af5e-8ba3cc9979ca)

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/081887bd-2b1c-4343-b6dd-fa1058fb10dd)

Client entity log:
[https://app.zenhub.com/files/93301055/9aa1d10f-aadd-4d11-a1c5-ef8244c2ec42/download](https://app.zenhub.com/files/93301055/9aa1d10f-aadd-4d11-a1c5-ef8244c2ec42/download)

Server entity log:
[https://app.zenhub.com/files/93301055/ba413b70-ad74-46e2-8308-7368884db407/download](https://app.zenhub.com/files/93301055/ba413b70-ad74-46e2-8308-7368884db407/download)

**Comment by Regalis11** [comment] 2020-05-25 10:39
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/29c0c2bd2739dc0df64d36aabafaca05d605db75

**Comment by Rokvach** [comment] 2020-05-25 10:46
Wasn't able to reproduce the issue using the steps above, working correctly. Closing.

**Closed by Rokvach** 2020-05-25 10:46 UTC
Labels: Bug, Code, High prio, Networking
