### ISSUE TITLE
[Bug] [Networking] Voice chat doesn't work when spectating

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1572] opened 2019-06-09 19:44 UTC
This is most likely a duplicate issue, but voice chat can't be heard while spectating a round. Very easy to reproduce. Couldn't find a duplicate so I posted this though.

**Comment by Regalis11** [comment] 2019-06-09 19:52
Duplicate of #1519

**Closed by Regalis11** 2019-06-09 19:52 UTC
