### ISSUE TITLE
Salfdamage from welders

### ISSUE THREAD

**Issue by G234i** [Regalis11/Barotrauma#110] opened 2017-12-09 11:53 UTC
As of v0.7.0.1 in multiplayer while swiming and welding parts of the ship the welder will inflict damage to the player (the damage id minimal but noticeable). This is probably because the flame hits parts of the body while swiming.

**Comment by Crystalwarrior** [comment] 2017-12-09 12:14
I thought this always happened.
Anyway I actually kinda like this, you have to orient yourself proper, especially in water.

**Comment by G234i** [comment] 2017-12-09 13:09
Well to be honest I will need some more testing before i can say for sure but it seems like even swiming correctly and trying to weld something under yourself still does damage regardless of body parts beeing or not in the way. Possibly a "rubberbanding" where the server thinks you are slightly displaced from the welder origin thus the it "welds" you?

**Comment by Crystalwarrior** [comment] 2017-12-09 13:21
Yeah must be the case,tbh this issue should be resolved for proper limb positions

**Comment by NilanthAnimosus** [comment] 2017-12-12 09:34
This doesn't tend to occur unless your skill is low, such as security guards and medics, so I always figured it was actually based off the failure to use such a tool.

I don't recall recall EVER hurting myself as a captain or mechanic, engineers are not really meant for plasma cutters though. I'll have to see if this is actually an issue while swimming with differences in skill just to re-check this since I cannot be 100% on that.

There is even code to skip adding limbs to prevent self-hitting based on the degree of success, so this appears to be intentional. - Can someone confirm this bug actually occurs with a high-mechanical skill class (mechanics, and captains)

**Comment by Regalis11** [comment] 2017-12-12 15:36
NilanthAnimosus is correct, characters with a construction level less than 20 can damage themselves with the welder (less than 30 in the case of plasma cutters). I'm closing this for now, but I'll reopen it if someone finds a way to reproduce this issue with characters that have the required skill level.

**Closed by Regalis11** 2017-12-12 15:36 UTC
Labels: bug
