### ISSUE TITLE
Crawler arms consistently break when flipping while swimming

### ISSUE THREAD

**Issue by Emanthealmighty** [Regalis11/Barotrauma#10824] opened 2022-12-26 16:36 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When a crawler (any character based on the crawler ragdoll) flips while swimming, the arms will break.

![image](https://user-images.githubusercontent.com/9964331/209568234-45fb1f86-1b8c-4fb1-9ff7-06334d58b32d.png)

### Reproduction steps

1. Go into the character editor
2. Select crawler
4. Start swimming
5. Turn to the opposite direction to flip, notice your arms breaking

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment] 2023-01-02 11:29
Caused by Regalis11/Barotrauma-development@89a6cf3.

**Comment by itchyOwl** [comment] 2023-01-02 13:56
Fixed in Regalis11/Barotrauma-development@fd55bc7.

On testing: may (but shouldn't) affect Defensebot or any other flipping characater that have limbs set to not flip.

**Comment by Rokvach** [comment] 2023-01-04 12:53
Tested, working correctly. Closing.

**Closed by Rokvach** 2023-01-04 12:53 UTC
Labels: Bug, Code
