### ISSUE TITLE
Error while reading a message from the server

### ISSUE THREAD

**Issue by Paragonid** [Regalis11/Barotrauma#1666] opened 2019-06-17 10:17 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The multiplayer game in campaign mode where I was connected to a host stopped (thew me into main menu) during the process on the boat with console error.

**Steps To Reproduce**
Unknown

**Version**
0.9.0.6 Windows

**Additional information**
crashreport_object.bin requested to be included
[crashreport_object.zip](https://github.com/Regalis11/Barotrauma/files/3296345/crashreport_object.zip)
![image](https://user-images.githubusercontent.com/881361/59597240-03218000-9102-11e9-83c2-b9ee260662d6.png)

**Comment by Regalis11** [comment] 2019-06-17 12:00
Most likely a duplicate of #1603 (not the same error message, but this can be caused by the same ID mismatch bug)

**Comment by Regalis11** [comment] 2019-09-18 12:17
I made a new issue report with some more information and details about these errors, lets try to compile information about the problem there from now on: #1815

**Closed by Regalis11** 2019-09-18 12:17 UTC
Labels: Bug, Code, High prio, Networking-related
