### ISSUE TITLE
Crashing periodically during multiplayer (MacOS)

### ISSUE THREAD

**Issue by Pinkbat5** [Regalis11/Barotrauma#5557] opened 2021-04-22 04:23 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

Game periodically crashes during multiplayer sessions over Steam, seemingly at random. Once I crash once or twice during a session, I'm unable to rejoin completely (game crashes every time the game begins to load when I attempt to rejoin the server)

[crashreport.txt](https://github.com/Regalis11/Barotrauma/files/6355459/crashreport.txt)

**Comment by Regalis11** [comment] 2021-04-22 08:59
Duplicate of https://github.com/Regalis11/Barotrauma/issues/4504

The issue should be fixed in the latest update that's coming out this week, sorry for the inconvenience!

**Closed by Regalis11** 2021-04-22 08:59 UTC
