### ISSUE TITLE
[UNSTABLE] Game crashes after exiting the sub editor(random)

### ISSUE THREAD

**Issue by AbyssBeast09** [Regalis11/Barotrauma#9135] opened 2022-05-14 11:50 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Exiting the editor can crash game
[crashreport (10).log](https://github.com/Regalis11/Barotrauma/files/8692854/crashreport.10.log)
[crashreport (9).log](https://github.com/Regalis11/Barotrauma/files/8692855/crashreport.9.log)
https://media.discordapp.net/attachments/668819422919524352/974998111762141204/unknown.png?width=832&height=676
 

### Reproduction steps

1. Open the sub editor
2. Try to exit(But it happens randomly)

### Bug prevalence

Happens every now and then

### Version

0.18.1.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment] 2022-05-16 08:21
Caused by Regalis11/Barotrauma-development@1922787. Fixed by reverting it.

**Comment by Regalis11** [comment] 2022-05-16 09:53
Fixed the start item loadout disappearance issue that https://github.com/Regalis11/Barotrauma-development/commit/1922787 addressed in another way that should prevent this issue from occurring. Now instead of forcing a save whenever you exit during the first round to ensure the start items persist, we always spawn the items when you reload into the 1st round (the same way it worked before).

**Comment by Rokvach** [comment] 2022-05-23 11:33
There hasn't been any sightings of this crash in the latest Unstable build, seems to be working correctly. Closing.

**Closed by Rokvach** 2022-05-23 11:33 UTC
Labels: Bug, Code, Crash
