### ISSUE TITLE
Time Frame setting broken

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#9826] opened 2022-09-03 22:19 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

time frame for AND component not working in either 0.18 nor 0.19, it can triggers true after the timeframe has elapsed

### Reproduction steps

1. test sub w/ and component setup
[and comp.zip](https://github.com/Regalis11/Barotrauma/files/9483468/and.comp.zip)

2. the periscopes are attached to an AND component w/ timeframe of 4s. pressing trigger on both periscopes further than 4s apart still turns on the light

3. the setup is replicated w/ buttons on the right

### Bug prevalence

Happens every time I play

### Version

0.19.3.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by mygamingaccount** [comment] 2022-09-04 00:35
To turn off a light, you must send a 0 signal onto its state input

From your test sub:

![image](https://user-images.githubusercontent.com/68995233/188292210-ad547e4d-292f-4cb5-858f-49c0bf7208d6.png)

**Comment by mygamingaccount** [comment] 2022-09-04 00:37
Tested "Timeframe" with AND, XOR, OR, and all is correct.

**Comment by mygamingaccount** [comment] 2022-09-04 00:38
Tested "Timeframe" with AND, XOR, OR, and they work correctly. The only issue is the tooltip explanation is wrong, but that is for another ticket.

**Comment by Tsunder** [comment] 2022-09-04 01:06
not trying to turn it off

the expectation is that the light _doesn't_ turn on / for the AND's output terminal to have no signal because the triggers are pressed > time frame.

**Comment by mygamingaccount** [comment] 2022-09-04 01:42
I'm unable to reproduce this.

Do you have the exact steps?

**Comment by mygamingaccount** [comment] 2022-09-04 02:08
The issue is only present when **False output** is unset

A component set up this way will receive a signal and zero the `timeSinceReceived` value
https://github.com/Regalis11/Barotrauma/blob/af4b63519bce52396333fc93f9e0ffec31ff6f9d/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Signal/BooleanOperatorComponent/BooleanOperatorComponent.cs#L103-L112


In its Update() phase, it will increment the `timeSinceReceived` exactly once, then promptly shut itself down becuase `falseOutput` is null or empty

https://github.com/Regalis11/Barotrauma/blob/af4b63519bce52396333fc93f9e0ffec31ff6f9d/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Signal/BooleanOperatorComponent/BooleanOperatorComponent.cs#L82-L98

The first signal will therefore not time out, and receiving the second signal will wake the component, which will stay active and transmit the True output for exactly `timeFrame - deltaTime` seconds

**Comment by Regalis11** [comment] 2022-09-04 16:25
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a47e82ab0bec4db112d2c0a67442bd81c3abf1e6

**Comment by Rokvach** [comment] 2022-09-28 09:38
Tested, working correctly. Closing.

**Closed by Rokvach** 2022-09-28 09:38 UTC
Labels: Bug, Code, Unstable
