### ISSUE TITLE
Makeshift Shelves no longer placeable

### ISSUE THREAD

**Issue by Koushakur** [Regalis11/Barotrauma#11767] opened 2023-04-07 20:10 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Since the 1.0 patch it is no longer possible to place Makeshift Shelves, not even as an assistant with the relevant talent. There are currently 0 placed shelves on the sub so it's not the new limit that stops it either.

(While I'm here I'd suggest making them not count as cargo space for cargo missions if that's the worry instead of the unusably low limit of 3.)

### Reproduction steps

1. Craft makeshift shelves
2. Try to place shelves
3. Receive message "SPECIAL TRAINING REQUIRED TO PLACE THIS ITEM." instead of shelf being placed

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-04-11 08:00
Thank you for the report!

I unfortunately could not find a way to reproduce the issue. Tested in both single player and multiplayer.


https://user-images.githubusercontent.com/14351070/231095383-25429bae-d167-4c61-b13f-2f3be18ee398.mp4

**Comment by Koushakur** [comment] 2023-04-11 10:36
Then I think it's relevant that I'm playing exclusively multiplayer and we're currently doing the campaign started before 1.0 came. It was said that pre-1.0 saves would still work but now I'm thinking it's the cause of this. I can't think of anything else of note that could affect their placeablity, just from one session to the next I simply couldn't place any due to this "special training" outta nowhere when we switched to Herja.

There are a couple people on Reddit that also have this issue so I know it's not just me at least: https://www.reddit.com/r/Barotrauma/comments/11rm8n0/makeshift_shelves/

**Comment by VoidEmpty** [comment] 2023-04-15 23:22
@Regalis11 I think this line is an issue:
https://github.com/Regalis11/Barotrauma/blob/f223f774b9a818ad3762b9ced711d52be4c3b5ff/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Holdable/Holdable.cs#L703

Only Assistants has this stat in Barotrauma\Content\Talents\Assistant\TalentsAssistant.xml:
![image](https://user-images.githubusercontent.com/6744603/232257294-7477b851-347a-492c-bf71-6c40aa393874.png)

For other roles it will be always zero:
https://github.com/Regalis11/Barotrauma/blob/f223f774b9a818ad3762b9ced711d52be4c3b5ff/Barotrauma/BarotraumaShared/SharedSource/Characters/CharacterInfo.cs#L1844

Thus you can't place crafted shelves (with help of bot-assistant talent) in multiplayer if none of players have Assistant role with this talent. It shouldn't work like this.

**Comment by Koushakur** [comment] 2023-04-16 12:27
I'd hazard the guess that that stat was not retroactively applied to assistants that already had the talent before it was added

**Comment by VoidEmpty** [comment] 2023-04-16 15:06
> I'd hazard the guess that that stat was not retroactively applied to assistants that already had the talent before it was added

Yes. This also explains why @Regalis11 couldn't reproduce this bug. 
I think that stat shouldn't be tied to some role or talent, as this creates more problems for players (crew with bot-assistant can't place shelves and there are no ways to control bots directly).

**Comment by 3e849f2e5c** [comment] 2023-04-17 10:09
Fixed in https://github.com/Regalis11/Barotrauma-development/pull/4119 PR, added "migration" system that adds the stat for older saves and made it so bots in multiplayer give the entire crew the ability to attach the items that they can

**Comment by Regalis11** [comment] 2023-04-18 09:15
Tested, no issues found. Closing.

**Closed by Regalis11** 2023-04-18 09:15 UTC
Labels: Bug, Code
