### ISSUE TITLE
Level equality check failed

### ISSUE THREAD

**Issue by Skyfire92** [Regalis11/Barotrauma#4010] opened 2020-10-05 17:15 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I bulid myself a sub with a shuttle attached.
I can buy it and finish 1 round with it.During the last round,I never undock the shuttle.
When I return to port,systerm never ask me if I wanna left the shuttle behind,then the error just occurred,and my save just gone borken.
After wat happened,I try to ues the same sub to begin a new save,it just doing the same error when I begining a new round with it.
I can use the sub during the solo campaign,things just always go wrong when I use it in a mutliplayer campaign.

**Steps To Reproduce**
Everytime I use the sub to begin a new campaign

**Version**
0.10.5.1

**Additional information**
[subfile.zip](https://github.com/Regalis11/Barotrauma/files/5328968/subfile.zip)
![1](https://user-images.githubusercontent.com/72407203/95110898-4bd6cf80-0771-11eb-82cd-cdd09a9284bf.png)
![2](https://user-images.githubusercontent.com/72407203/95110903-4da09300-0771-11eb-961c-2111fb678213.png)

**Comment by Regalis11** [comment] 2020-10-07 14:16
This seems to happen because Burdened MK5 includes another linked submarine (meaning that the game will load a total of 3 submarines: the main one, Burdened MK5, and "Test MK3" that's linked to the top docking port of Burdened). You should be able to work around the issue by removing "Test MK3" from "Burdened MK5".

The networking error when leaving Test MK3 behind is caused by https://trello.com/c/076rNmbm/318-level-equality-check-failed-error-due-to-undocking-attached-shuttle-and-leaving-it-behind, and should be fixed in the next patch.

**Closed** 2020-10-07 14:16 UTC
Labels: Bug, Code

**Comment by Regalis11** [comment] 2020-10-07 14:20
Marking as a duplicate of https://github.com/Regalis11/Barotrauma/issues/3330

**Comment by Skyfire92** [comment] 2020-10-07 19:14
Understood,thank you
