### ISSUE TITLE
Bot - Having issue reaching periscope in this sub, half the time.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#6985] opened 2021-10-21 13:14 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
There's this periscope in my sub that is problematic for the bots every other level. He insists on trying to reach it from directly underneath instead of climbing the ladder half the time.

![Capture](https://user-images.githubusercontent.com/5086682/138284851-9ce86acb-66a4-4ed0-ad04-d80b1d82a50d.PNG)

[Kail Terra.zip](https://github.com/Regalis11/Barotrauma/files/7389286/Kail.Terra.zip)

**Steps To Reproduce**
Assign bot to Drone's gun on Kail Terra.

**Version**
~0.15.9.0

**Comment by itchyOwl** [comment] 2023-01-26 13:57
Sorry for the late response! This ticket has been collecting dust in the backlog with the "low prio" tag on it. Finally had the time to check it out. However, I couldn't open the old sub anymore and I was too lazy to test it in an ancient build. So I tested it using the latest release version and the latest version of the sub. Can't see any issues: the bot pathed properly and manned the gun ![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/4dcb3d72-67cf-4c62-8a29-4436cb6e451f)

Is it working properly on you too or are there still some issues with it?

**Comment by itchyOwl** [comment] 2023-01-30 08:31
Even though I wasn't able to repro this, I might have found the cause of the issue. And if that's the case, it might be fixed in Regalis11/Barotrauma-development#3874 (PR).

**Closed** 2023-03-10 13:28 UTC
Labels: Bug, Needs testing, Code
