### ISSUE TITLE
Mudraptor + AI Crash

### ISSUE THREAD

**Issue by Lithosagym** [Regalis11/Barotrauma#2252] opened 2020-02-11 05:39 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
One crash I believe is due to when a Mudraptor targets a crew member, either when attacking a crew member or fleeing from one. The other crash seems to be from the response of an AI when dealing with either the Mudraptor itself or the leaks made by the Mudraptor.

**Steps To Reproduce**
Spawn a Mudraptor outside to create leaks in the hull and have a Mechanic/crew member with the "Fix Leaks" command  attempt to fix the leaks in hope to reproduce at least one of the two crashes.

**Version**
Windows
V. 0.9.705.0

**Additional information**
This is "Unstable - Mechanic + Mudraptor Crash" but with a bit more information and both types of crashes
[crashreport (4).log](https://github.com/Regalis11/Barotrauma/files/4184223/crashreport.4.log)
[crashreport (3).log](https://github.com/Regalis11/Barotrauma/files/4184224/crashreport.3.log)

**Comment by Regalis11** [comment] 2020-02-11 08:38
Haven't been able to find a way to reproduce this, but I added some safeguards and error logging for this in https://github.com/Regalis11/Barotrauma-development/commit/770a6d8f17b49a1e530384f2b14d55c793352306. If the error is caused by what I suspect it is, the item being dropped after the body has been removed, this shouldn't cause a crash anymore but log an error message.

**Comment by Regalis11** [comment] 2020-02-12 12:27
I think I may have found some more clues as to what's causing this. Suspecting that it's a side-effect of #2259.

1. Start a new single player campaign with no bots.
2. Spawn a couple of bots using the debug console.
3. End the round.
4. Start a new round. As a consequence of #2259, the bots should now have items in an invalid state in their inventory: seemingly appearing to be in the inventory, but actually being active somewhere in the world.
5. If those items get removed at this point, the bots will appear to still have the items inside their inventories even though they've actually been removed. And they tend to get removed within a few minutes, because they're is actually falling down out of the level, and at a certain point reach a point where the game automatically removes them (see Level.MaxEntityDepth). I still haven't figured out what exactly is causing the body of the item to be removed despite the body-field of the item not being set to null, but I'm pretty confident it's caused by those items in an invalid state that are sort-of in the character's inventory but not quite. The issue also seemed to start occurring after we changed the "spawn" command so it gives the bots their job items, and all of the reports we've gotten so far have been from single player, which are the exact conditions for getting that invalid item state issue to occur.

#2259 has been fixed now, so this shouldn't be happening anymore, but we should still investigate  what exactly happened to those invalid items that cause the body to be removed despite the item's body field not being null.

**Comment by Rokvach** [comment] 2021-01-05 14:19
I haven't heard of anything even closely relating to this, still an issue?

**Closed** 2021-01-13 13:29 UTC
Labels: Bug, Code, Low prio
