### ISSUE TITLE
[0.9.10.0] Bots can't Shutdown Reactor

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2825] opened 2020-05-14 01:02 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots can't Shutdown Reactor

**Version**
0.9.10.0

**Comment by Regalis11** [comment] 2020-05-14 07:21
Could not reproduce

**Comment by Kaillera** [comment] 2020-05-14 11:18
I can't get my bot to shutdown the reactor on Corsair

**Comment by Kaillera** [comment] 2020-05-14 11:34
https://www.youtube.com/watch?v=NlGSKsQeUgw

**Comment by itchyOwl** [comment] 2020-05-19 10:21
Fixed in Regalis11/Barotrauma-development@24c18df

**Comment by Rokvach** [comment] 2020-05-19 11:08
No issues, closing.

**Closed by Rokvach** 2020-05-19 11:08 UTC
Labels: Bug, Code
