### ISSUE TITLE
Game crash - Signal Component - Remove value and click other component

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#9629] opened 2022-07-23 20:05 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The game breaks down after editing the parameters of the `signal component`.

https://user-images.githubusercontent.com/93348499/180620870-cf4e4a28-1d09-4ce0-8203-b1f33f12c868.mp4

### Reproduction steps

Watch video or:
~~1. Start editor
2. Create two any signal component/ Example `signal checking component` or `component "And"`
3. Select one component and change output signal properties: 255.0.0.255
4. Close the properties, open properties again and change `.` to `,`. Should be 255,0,0,255
5. Сlick on the second component.~~

But it can be easier )):
1. Start editor
2. Create two `signal checking component`... or `And`, etc (as you wish)
3. Select one component and change output signal properties: Just delete the number 1
4. Сlick on the second component.

https://user-images.githubusercontent.com/93348499/180621144-4b026d8f-f6d3-40c4-a66e-1d0724711303.mp4

### Bug prevalence

Happens every time I play

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Tsunder** [comment] 2022-07-23 20:21
duplicate of #9512

**Comment by MaaiG** [comment] 2022-07-24 13:16
@Tsunder If it’s the same, I can come up a couple of differences ))

In addition, there:
> I haven’t found a consistent way to reproduce this, it happened with multiple components. Crash report below.

Here: I know exactly how to reproduce it ))

There the value is entered, and mine is removed ))

In general, it will not be worse ;)

**Comment by NilanthAnimosus** [comment] 2022-07-28 10:55
This is indeed the same issue as #9512 and is fixed for the next version of the game (Currently in the unstable build)

closing as this is a duplicate

**Closed by NilanthAnimosus** 2022-07-28 10:55 UTC
