### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by farukred** [Regalis11/Barotrauma#2403] opened 2020-03-07 09:50 UTC
Barotrauma Client crash report (generated on 3/7/2020 4:47:48 PM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

77C56A52AF2F5A2C199FAD8AD1880A82

Game version 0.9.7.1 (ReleaseMac, branch release, revision 6ec75fa2a)
Graphics mode: 1440x900 (BorderlessWindowed)
VSync ON
Selected content packages: None
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized

System info:
    Operating system: Unix 18.7.0.0 64 bit
    GPU name: 
    Display mode: {Width:1440 Height:900 Format:Color AspectRatio:1.6}
    GPU status: Normal

Exception: Loading was interrupted due to an error: Object reference not set to an instance of an object.
   at Barotrauma.GUI.Init(GameWindow window, IEnumerable`1 selectedContentPackages, GraphicsDevice graphicsDevice) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/GUI/GUI.cs:line 224
   at Barotrauma.GameMain.Load(Boolean isSeparateThread)+MoveNext() in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 421
   at Barotrauma.CoroutineManager.ExecuteCoroutineThread(CoroutineHandle handle) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 167 (System.Exception)
Target site: Void Update(Microsoft.Xna.Framework.GameTime)
Stack trace: 
   at Barotrauma.GameMain.Update(GameTime gameTime) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 749
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 654
   at Microsoft.Xna.Framework.Game.Tick() in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/SDL/SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 42

Last debug messages:
[3/7/2020 4:47:48 PM] Coroutine "Load" has failed
[3/7/2020 4:47:48 PM] Coroutine "Load" has thrown an exception {Object reference not set to an instance of an object.}
   at Barotrauma.GUI.Init(GameWindow window, IEnumerable`1 selectedContentPackages, GraphicsDevice graphicsDevice) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/GUI/GUI.cs:line 224
   at Barotrauma.GameMain.Load(Boolean isSeparateThread)+MoveNext() in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 421
   at Barotrauma.CoroutineManager.ExecuteCoroutineThread(CoroutineHandle handle) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 167
[3/7/2020 4:47:48 PM] No UI styles defined in the selected content package!
[3/7/2020 4:47:48 PM] Attempting to open ALC device "MacBook Pro Speakers"
[3/7/2020 4:47:46 PM] Loaded languages: English
[3/7/2020 4:47:46 PM] No text files available in any of the selected content packages. Attempting to find a vanilla English text file...
[3/7/2020 4:47:46 PM] Content package '/Users/faruk/Library/Application Support/Steam/steamapps/common/Barotrauma/barotrauma.app/Contents/MacOS/Data/ContentPackages/Vanilla 0.9.xml' not found.
[3/7/2020 4:47:46 PM] Loaded languages: English
[3/7/2020 4:47:46 PM] No text files available in any of the selected content packages. Attempting to find a vanilla English text file...
[3/7/2020 4:47:46 PM] Logged in as Largeredwolf (SteamID STEAM_1:1:241408462)

**Comment by Regalis11** [comment] 2020-03-09 10:26
Duplicate of #2401

**Closed by Regalis11** 2020-03-09 10:26 UTC
