### ISSUE TITLE
Game crashes/freezes

### ISSUE THREAD

**Issue by Astr0Jack** [Regalis11/Barotrauma#10812] opened 2022-12-24 14:46 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I have looked through different issues, and none seem to be exactly what is happening to the game
Shortly after the hotfix on December 20th my game crashes it happens roughly 5 seconds to 10 mins the game freezes and i get really slow framerate, roughly 1frame/30secs I checked task manager and the computer just gives up on the game
I checked the log and absolutely nothing shows up, no error messages or reasons why the game just freezes and crashes
![image](https://user-images.githubusercontent.com/121347120/209440174-42542123-61f8-49cb-9b64-c3b1a99edaf0.png)
updating windows 11 suppressed the error for about a day but it had returned 

### Reproduction steps

1. start the game
2. low framerate/freezing/crash

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Dedicated Server crash report (generated on 12/22/2022 21:33:38)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


Game version 0.20.16.1 (ReleaseWindows, branch release, revision 33a42adf77)
Language: English
Selected content packages: Vanilla, Wyvern
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.NetLobbyScreen
Server (Round hadn't been started)


System info:
    Operating system: Microsoft Windows NT 10.0.22621.0 64 bit


Exception: Pipe is broken. (System.IO.IOException)
Target site: Void WriteCore(System.ReadOnlySpan`1[System.Byte])
Stack trace: 
   at System.IO.Pipes.PipeStream.WriteCore(ReadOnlySpan`1 buffer)
   at Barotrauma.Networking.ChildServerRelay.<UpdateWrite>g__writeMsg|27_0(WriteStatus writeStatus, Byte[] msg) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 265
   at Barotrauma.Networking.ChildServerRelay.UpdateWrite() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 281
   at System.Threading.Thread.StartCallback()


Last debug messages:
   12/22/2022 21:33:38 - [12/22/2022 21:33:38]
  Saving banlist
   12/22/2022 21:33:38 - [12/22/2022 21:33:38]
  Saving banlist
   12/22/2022 21:33:20 - WARNING: Running slowly (57 updates/s)!
   12/22/2022 21:33:13 - [12/22/2022 21:33:13]
  Round ended.
   12/22/2022 21:33:12 - [12/22/2022 21:33:12]
  Ending the round...
   12/22/2022 21:33:12 - [12/22/2022 21:33:12]
  Client "Astr0jack" ended the round.
   12/22/2022 21:32:00 - [12/22/2022 21:32:00]
  Astr0jack equipped Screwdriver
   12/22/2022 21:31:41 - [12/22/2022 21:31:41]
  Astr0jack has gained the talent 'Logistics Expert'
   12/22/2022 21:30:26 - [12/22/2022 21:30:26]
  Kristeen Severance unequipped Screwdriver
   12/22/2022 21:30:00 - [12/22/2022 21:30:00]
  Hobert Gay unequipped Screwdriver
   12/22/2022 21:29:27 - [12/22/2022 21:29:27]
  Astr0jack picked up Welding Fuel Tank
   12/22/2022 21:29:25 - [12/22/2022 21:29:25]
  Astr0jack picked up Welding Fuel Tank
   12/22/2022 21:29:24 - [12/22/2022 21:29:24]
```

**Comment by vitrifiedglass** [comment] 2022-12-28 06:06
I also received this error, albeit on a mac and with a lightweight mod.

[servercrashreport (10).log](https://github.com/Regalis11/Barotrauma/files/10312442/servercrashreport.10.log)
[servercrashreport (9).log](https://github.com/Regalis11/Barotrauma/files/10312443/servercrashreport.9.log)

**Comment by Regalis11** [comment] 2023-01-09 16:43
Thank you for the report, and sorry for the late response!

We got [another report](https://github.com/regalis11/barotrauma/issues/10813) that seems like it could be related to this, or perhaps the exact same issue. Have either of you by any chance tried the unstable version of the game? We've done some changes to the save files there, and if you had switched to unstable and back, it could lead to extremely long error messages that can cause a freeze like this.

**Comment by vitrifiedglass** [comment] 2023-01-11 19:34
In my case at least, yes, we have switched between Unstable and then reverted to Stable. I wonder if some other issues we had might be related, such as missing purchased items.

**Comment by Regalis11** [comment] 2023-01-16 10:07
> I wonder if some other issues we had might be related, such as missing purchased items.

It could very well be the case. It's generally not recommended to use the same saves between Unstable and Stable - changes in Unstable might not always be compatible with the Stable version.

Closing as a duplicate of https://github.com/regalis11/barotrauma/issues/10813

**Closed by Regalis11** 2023-01-16 10:07 UTC
Labels: Bug, Need more info, Code, Crash
