### ISSUE TITLE
The game crashes when you turn on the fabricator

### ISSUE THREAD

**Issue by XuShuaiLiu** [Regalis11/Barotrauma#10134] opened 2022-10-21 19:12 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

The game crashed when I tried to open the console to make an item. I want to be able to make things normally
[crashreport (11).log](https://github.com/Regalis11/Barotrauma/files/9841824/crashreport.11.log)

### Reproduction steps

Game version 0.19.14.0 (ReleaseWindows, branch release, revision 0daf5b87bd)
Graphics mode: 3440x1440 (BorderlessWindowed)
VSync OFF
Language: Simplified Chinese
Selected content packages: Vanilla, [EA-HI]木卫二萌化计划, 奇迹之海武装, 剑齿鲑鱼号, 独眼巨人-利维坦, 顺丰航空, 顺丰航空1, T.S.M-日暮山工程, 【T.S.M】山河无恙 日月重光, 万年风雪, 松鼠快乐箱 [Insufficient Capacity], Lootbelt, [BOS]Backpack, [BOS]Wrecks, Swift 暴风雨燕, 更好的床铺, Beacons Extended, Stations from beyond, Wreck Locator 沉船定位器, Detectable Alien Materials 可探测的异星矿物！, 加特林激光, 深渊基因 Abyss Gene, 无限炮台弹药箱, 无限轨道炮
Level seed: Sidon Flexus
Loaded submarine: 顺丰航空1 (76C55054084BC2ED95CACBDC74621567)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 10/22/2022 03:00:20)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


0DC439F0B0CA5A5A6693500952309D61


Game version 0.19.14.0 (ReleaseWindows, branch release, revision 0daf5b87bd)
Graphics mode: 3440x1440 (BorderlessWindowed)
VSync OFF
Language: Simplified Chinese
Selected content packages: Vanilla, [EA-HI]木卫二萌化计划, 奇迹之海武装, 剑齿鲑鱼号, 独眼巨人-利维坦, 顺丰航空, 顺丰航空1, T.S.M-日暮山工程, 【T.S.M】山河无恙 日月重光, 万年风雪, 松鼠快乐箱 [Insufficient Capacity], Lootbelt, [BOS]Backpack, [BOS]Wrecks, Swift 暴风雨燕, 更好的床铺, Beacons Extended, Stations from beyond, Wreck Locator 沉船定位器, Detectable Alien Materials 可探测的异星矿物！, 加特林激光, 深渊基因 Abyss Gene, 无限炮台弹药箱, 无限轨道炮
Level seed: Sidon Flexus
Loaded submarine: 顺丰航空1 (76C55054084BC2ED95CACBDC74621567)
Selected screen: Barotrauma.GameScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.22000.0 64 bit
    GPU name: AMD Radeon RX 5700 XT
    Display mode: {Width:3440 Height:1440 Format:Color AspectRatio:2.3888888}
    GPU status: Normal


Exception: No ItemPrefab with identifier or name "tsm-m4mlmagazinee" (System.Exception)
Target site: Barotrauma.ItemPrefab get_ItemPrefab()
Stack trace: 
   at Barotrauma.FabricationRecipe.RequiredItemByIdentifier.get_ItemPrefab() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\ItemPrefab.cs:line 105
   at Barotrauma.FabricationRecipe.RequiredItemByIdentifier.get_ItemPrefabs() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\ItemPrefab.cs:line 110
   at Barotrauma.Items.Components.Fabricator.<>c__DisplayClass97_0.<CanBeFabricated>b__0(RequiredItem requiredItem) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Machines\Fabricator.cs:line 609
   at System.Linq.ImmutableArrayExtensions.All[T](ImmutableArray`1 immutableArray, Func`2 predicate)
   at Barotrauma.Items.Components.Fabricator.CanBeFabricated(FabricationRecipe fabricableItem, IReadOnlyDictionary`2 availableIngredients, Character character) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Machines\Fabricator.cs:line 606
   at Barotrauma.Items.Components.Fabricator.UpdateHUD(Character character, Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\Machines\Fabricator.cs:line 788
   at Barotrauma.Item.UpdateHUD(Camera cam, Character character, Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 1153
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 134
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 855
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58


Last debug messages:
[10/22/2022 03:00:02] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/LXSAN/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2809175631/Content/Uniform_new/SecurityOfficer8.png, size: 650x360)
[10/22/2022 03:00:02] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/LXSAN/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2809175631/Content/Uniform_new/SecurityOfficer7.png, size: 650x360)
[10/22/2022 02:59:56] Generating an outpost for the start of the level... (Location: Sidon Flexus, level type: Outpost)
[10/22/2022 02:59:56] Level identifier: outpostlevel
[10/22/2022 02:59:56] Creating hulls between docking ports failed. Could not find a hull next to the docking port.
[10/22/2022 02:59:55] Creating hulls between docking ports failed. Could not find a hull next to the docking port.
[10/22/2022 02:59:34] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/LXSAN/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2809175631/Content/EA-HI/teleportine.png, size: 67x71)
[10/22/2022 02:59:32] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/LXSAN/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2827262734/picture/枪械.png, size: 2103x2772)
[10/22/2022 02:59:30] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/LXSAN/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2809175631/Content/Uniform_new/SecurityOfficer8.png, size: 650x360)
[10/22/2022 02:59:30] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/LXSAN/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2827262734/picture/moonlight.png, size: 427x82)
[10/22/2022 02:59:30] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/LXSAN/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2809175631/Content/Uniform_new/SecurityOfficer7.png, size: 650x360)
[10/22/2022 02:59:28] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/LXSAN/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2599981985/Gatling Laser/Gatling Laser.png, size: 279x146)
[10/22/2022 02:59:22] Generating an outpost for the start of the level... (Location: Sidon Flexus, level type: Outpost)
[10/22/2022 02:59:22] Level identifier: outpostlevel
[10/22/2022 02:59:21] Creating hulls between docking ports failed. Could not find a hull next to the docking port.
[10/22/2022 02:59:21] Creating hulls between docking ports failed. Could not find a hull next to the docking port.
[10/22/2022 02:59:19] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/LXSAN/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2809175631/Content/items/Weapons/Katana.png, size: 372x234)
[10/22/2022 02:59:18] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/LXSAN/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2782970894/gfx/if_resource_box.png, size: 1195x520)
[10/22/2022 02:59:14] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/LXSAN/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2809175631/Content/items/Jobgear/Security/转轮式霰弹枪.png, size: 215x64)
[10/22/2022 02:58:03] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/LXSAN/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2827262734/picture/Particle_teleport.png, size: 1645x510)
[10/22/2022 02:58:03] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/LXSAN/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2827262734/picture/Artexplosion.png, size: 2629x2605)
[10/22/2022 02:58:02] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/LXSAN/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2827262734/picture/tsmcons.png, size: 281x91)
[10/22/2022 02:58:02] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/LXSAN/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2809175631/Content/Particles/Particle_teleport1.png, size: 1645x510)
[10/22/2022 02:58:02] Overriding an affliction or a buff with the identifier 'nausea' using the file 'C:/Users/LXSAN/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2809175631/Content/Afflictions.xml'
[10/22/2022 02:58:02] Overriding an affliction or a buff with the identifier 'concussion' using the file 'C:/Users/LXSAN/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2809175631/Content/Afflictions.xml'
[10/22/2022 02:57:43] Attempting to open ALC device "OpenAL Soft on 扬声器 (3- High Definition Audio Device)"
[10/22/2022 02:57:42] Logged in as lxsloveljx (SteamID STEAM_1:1:472998058)
```

**Comment by Regalis11** [comment] 2022-10-22 09:22
Thank you for the report! It seems that this is caused by one of the mods you have installed - one of them has a broken fabrication recipe that requires the item "tsm-m4mlmagazinee" as an ingredient, but it seems there's no such item (perhaps a typo, there should probably be just one 'e' at the end?).

I made this log an error message instead of crashing the game in https://github.com/Regalis11/Barotrauma-development/commit/2262c951144821188b96c387907934f8308b0e75. But for now, it should be possible to work around the issue by disabling the broken mod (if you know which one that is).

**Comment by NilanthAnimosus** [comment] 2022-10-25 11:06
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/1359aa355bc64bfeece9d4c4c807133affd8ff14, no issues found, closing.

works fine with fabricator's, and does not load the invalid recipe (so it will not show up in the fabricator list) however if you do this with a deconstructor you get a fairly long stack trace alongside a more human readable error, which perhaps could be cleaned up a bit with a few checks?

![image](https://user-images.githubusercontent.com/29177976/197756098-bae9a765-be10-46e9-8eb2-ff1f09386f29.png)

Otherwise, neither fabricators nor deconstructors with invalid item identifiers will crash the game.

**Comment by XuShuaiLiu** [comment] 2022-10-25 11:17
Thanks, it's really because of the MOD, the author has updated and fixed it

**Comment by Regalis11** [comment] 2022-10-25 11:25
@NilanthAnimosus addressed the deconstructor error message in https://github.com/Regalis11/Barotrauma-development/commit/c7941a780691795d9568881e53b6a6360bc495bd

**Comment by NilanthAnimosus** [comment] 2022-10-26 08:26
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/37a9cd3374b819cec4b459871755c392b1f29e34, no issues found, closing.

**Closed by NilanthAnimosus** 2022-10-26 08:26 UTC
Labels: Bug, Code, Crash, Modding
