### ISSUE TITLE
[0.12.0.2] Destructible Cave Walls outside of caves.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4978] opened 2021-02-04 14:50 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Destructible Cave Walls outside of caves.
[Multiplayer.zip](https://github.com/Regalis11/Barotrauma/files/5926474/Multiplayer.zip)
![Capture](https://user-images.githubusercontent.com/5086682/106909641-7a889680-66ce-11eb-9660-865d67e6069f.PNG)

**Version**
0.12.0.2

**Additional Informations**
Also the cave marker is off.
![Capture](https://user-images.githubusercontent.com/5086682/106909835-a73cae00-66ce-11eb-861b-26efdf256240.PNG)

**Comment by Regalis11** [comment] 2021-02-04 14:57
Caused by the same issues as #4956, fixed in Fixed in Regalis11/Barotrauma-development@a7137d4

**Comment by Rokvach** [comment] 2021-02-09 10:02
Should this also fix the existing save like the one included on the ticket or only new saves?

**Comment by Rokvach** [comment] 2021-02-24 15:56
Tested, haven't been able to reproduce this. Seems to be working correctly. Closing.

**Closed by Rokvach** 2021-02-24 15:56 UTC
Labels: Bug, Code
