### ISSUE TITLE
Humpback battery work in solo, but don't on servers

### ISSUE THREAD

**Issue by PoxmeLbE** [Regalis11/Barotrauma#2544] opened 2020-03-31 12:21 UTC
i'm first time wright bug report on english, sorry for my terrible russian aсcen

I don't know why but if i create the server and pick humpback, i can't dive on battery's. But is solo company it's works normal. help me. i love this sup so much!

**Comment by PoxmeLbE** [comment] 2020-03-31 14:48
up. I do it. it's work!
i think bug in Terminal "object", cos then i do this system with botton, it start work well.

**Comment by Regalis11** [comment] 2020-04-06 16:22
Duplicate of #2294

**Closed by Regalis11** 2020-04-06 16:22 UTC
Labels: Bug, Code
