### ISSUE TITLE
Radiation Sickness Bug and Mission Bug

### ISSUE THREAD

**Issue by Xahannist** [Regalis11/Barotrauma#2720] opened 2020-04-27 05:19 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The radiation sickness bug happened when the radiator blew up but I only had the burn affliction constantly on me and no display of the radiation sickness. Even after fully healing all the burn affected areas, the affliction would return and never displayed the radiation sickness affliction even with a doctor looking at it.
The mission bug happened when my crew was doing a "eliminate a crawler swarm" mission. We killed all but one crawler from the swarm and it fled. When the crew followed to the location of the last crawler, it did not show in the game even though the scanner showed it was suppose to be there.

**Steps To Reproduce**
Possibly do a swarm mission and kill all but one creature from the swarm. No clue on how to replicate the radiation sickness bug

**Version**
Version:  v0.9.9.0
Operating System: Windows

**Additional information**
We were using the "Into the Abyss" mod/

**Comment by Kaillera** [comment] 2020-04-27 10:26
Sounds like the volcano bug instead. Did the medic ever tried giving you antirad?

**Comment by Regalis11** [comment] 2020-07-13 12:52
Most likely a duplicate of https://github.com/Regalis11/Barotrauma/issues/2003

**Closed by Regalis11** 2020-07-13 12:52 UTC
Labels: Bug, Code
