### ISSUE TITLE
Loading up the game makes everything look very 'fuzzy' and screen in parts is black.

### ISSUE THREAD

**Issue by Andyshehu172** [Regalis11/Barotrauma#9323] opened 2022-06-11 23:48 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I was gifted the game recently by a friend and it appears that when I downloaded and load into the game, the screen goes black in some spots, but some areas are still in colour. It's really strange and I've gone through downloading new drivers, and restarting the game/reinstalling. When I join my friends game, it will be the same until I actually enter their world, and looks normal but as soon as we're done goes right back to looking 'fuzzy'. Have a look at the screenshot below and tell me what you think? I'm really confused and haven't a breeze what's going on. Thanks. 

![error](https://user-images.githubusercontent.com/107328404/173208450-7c87d9d0-33f1-490c-8e6e-2cff9c46a133.png)

### Bug prevalence

Happens every time I play

### Version

0.17.16.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-06-12 09:30
Duplicate of https://github.com/Regalis11/Barotrauma/issues/9213

**Closed by Regalis11** 2022-06-12 09:30 UTC
