### ISSUE TITLE
Make Stun Baton's Effect Being Delayed Between Multiple Targets Being Hit at Once- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#823] opened 2018-09-25 12:42 UTC
For example if 2 targets get hit at once by stun baton stun duration will last 7,5 seconds instead of 15. Battery cell will lose same amount of power as at single target hit.

**Comment by Regalis11** [comment] 2018-09-25 13:13
Duplicate of #814

**Closed by Regalis11** 2018-09-25 13:13 UTC
Labels: Gameplay-related, feature request
