### ISSUE TITLE
Crash when opening job selection in NetLobbyScreen

### ISSUE THREAD

**Issue by MajorMeltdown** [Regalis11/Barotrauma#3924] opened 2020-09-27 14:33 UTC
**Description**
i dont know, it just told me to come here and put the log in
**Steps To Reproduce**
see above

**Version**
Game version 0.10.5.1 (ReleaseWindows, branch release, revision 9e259b2148)

**Additional information**
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/5288454/crashreport.log)

this is the log, its very long

**Comment by Regalis11** [comment] 2020-09-28 12:02
Not sure how exactly this happened, but one potential explanation could be that the job preferences in config_player.xml were set to a variant that doesn't exist. For example, if you'd previously selected the 3rd variant of some job and then switched to a mod where there's only 2 variants available, clicking on the variant buttons would cause this. Can also be reproduced by opening config_player, finding the <jobpreferences> element and changing the "variant" value to something like 4.

Potentially fixed in https://github.com/Regalis11/Barotrauma-development/commit/10146c8865387c8dcb79c2240c2a457e8b37c0fc

**Comment by Rokvach** [comment] 2020-09-29 10:07
If the issue was caused by the different variant size, then this issue seems to be working correctly. Closing.

**Closed by Rokvach** 2020-09-29 10:07 UTC
Labels: Bug, Code, Crash
