### ISSUE TITLE
Russian texts not displayed correctly on Terminals when Monospace Font is ON + other text related issues.

### ISSUE THREAD

**Issue by Singularia** [Regalis11/Barotrauma#11633] opened 2023-03-22 02:09 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Russian localisation lines and manually typed texts do not display correctly in the Terminal when the `Monospace Font` flag is enabled. When the game localisation is switched back to English, text lines will display correctly.

Examples below:

<details>
<summary>Manually typed message on top + modded "welcome" message on the bottom.</summary>

`Monospace Font` flag is disabled.
![image](https://user-images.githubusercontent.com/62324831/226778794-feb53462-1394-48c0-a47f-ec249709929c.png)

`Monospace Font` flag is enabled.
![image](https://user-images.githubusercontent.com/62324831/226778842-5609c522-2970-4594-a40b-851497462caf.png)

Another modded "welcome" message, `Monospace Font` flag is Disabled.
![image](https://user-images.githubusercontent.com/62324831/226773670-4e7441c9-51fe-4ce3-9164-b2d796d91529.png)

Another modded "welcome" message, `Monospace Font` flag is Enabled.
![image](https://user-images.githubusercontent.com/62324831/226773720-d9f30eac-cda6-4ec1-b290-bc91ee3bd42c.png)
</details>

The same issue occurs when using vanilla localised text lines.

<details>
<summary>Vanilla `terminalwelcomemsg.kastrulldiary1` Welcome message</summary>

`Monospace Font` flag is Disabled.
![image](https://user-images.githubusercontent.com/62324831/226774120-9e368eda-d16b-4f3f-9ac4-531aecfbcb61.png)

`Monospace Font` flag is Enabled.
![image](https://user-images.githubusercontent.com/62324831/226774065-72cfb3fb-083e-4afc-96de-b9e6831c7bc9.png)
</details>

----------

### Reproduction steps

1. Using Sub-Editor place two Terminals on any sub of choice.
2. Terminal 1: In the Terminal's Welcome message use any existing vanilla text lines and enable `Monospace Font`.
3. Terminal 2: In the Terminal's Welcome message use any existing vanilla text lines and leave `Monospace Font` setting disabled.
4. In the Test mode (switching to English/Russian prior) observe difference in how text displays.

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Singularia** [comment] 2023-03-22 02:11
_As to not pollute issue tracker I'll add additional text-related issues that I noticed when tested the main point of this ticket._

Additionally, it appears that if you type any predefined line from localisation file in the Sonar Beacon's message box then it will show them correctly on Sonar, but not in the message window itself.

Examples below are three Sonar beacons with different messages.
<details>
<summary>Sonar Beacon without any changes</summary>

Message window (EN-RU)
![image](https://user-images.githubusercontent.com/62324831/226781522-c6945cab-5a2f-4e6a-b20f-39f2a5083fe1.png)
![image](https://user-images.githubusercontent.com/62324831/226780729-cd5653ef-7bb1-4b70-b9f1-0ec92fcdfc0d.png)

View from Sonar (EN-RU)
![image](https://user-images.githubusercontent.com/62324831/226781780-2407897d-90b5-4bb8-a6b8-08028f42f8df.png)
![image](https://user-images.githubusercontent.com/62324831/226780812-3bfe2a30-285d-4d16-ab6a-b9b4c0491680.png)

</details>

<details>
<summary>Sonar Beacon with modded localisation label</summary>

Message window (same line in the message window, regardless of language)
![image](https://user-images.githubusercontent.com/62324831/226780973-44577460-eea0-4640-b5ee-2ea4181578e7.png)

View from Sonar (EN-RU)
![image](https://user-images.githubusercontent.com/62324831/226781719-928201c3-7f25-40ab-ac3f-b3bcbdc858d1.png)
![image](https://user-images.githubusercontent.com/62324831/226780986-6495b6cc-fcec-4255-aecc-6e5dd511831f.png)

</details>

<details>
<summary>Sonar Beacon with vanilla localisation label</summary>

Message window (same line in the message window, regardless of language)
![image](https://user-images.githubusercontent.com/62324831/226781059-113ff6fd-42b1-4cdd-a0dd-2eda26af0658.png)

View from Sonar (EN-RU)
![image](https://user-images.githubusercontent.com/62324831/226781674-91cca1b9-fb71-40a4-a3d3-9b873518ccbd.png)
![image](https://user-images.githubusercontent.com/62324831/226781076-104b9b7c-4c14-42a4-8eec-6ba9e35720e1.png)

</details>

**Comment by Singularia** [comment] 2023-03-22 02:47
While adding localisation to some beacons from the `Beacons Extended` mod, i noticed that text is not localised if there are multiple lines pushed through the `Concatenation Component`.

Example:
Simple test scheme:
N.B. Both `Concatenation Components` have one space as a separator.
![image](https://user-images.githubusercontent.com/62324831/226786849-983a6116-d1b6-42d8-91ec-ed8b191e06f1.png)

Lines are:
[EN]
```xml
<label.shuttleloc>Trying to locate supply shuttle... Disantce:</label.shuttleloc>
<label.distaway>meters away</label.distaway>
```
[RU]
```xml
<label.shuttleloc>Поиск челнока снабжения... Расстояние:</label.shuttleloc>
<label.distaway>метров</label.distaway>
```

The end result should be:
[EN]
"Trying to locate supply shuttle... Disantce: 1914 meters away"
[RU]
"Поиск челнока снабжения... Расстояние: 1914 метров"

Instead, the end result is this:
![image](https://user-images.githubusercontent.com/62324831/226788085-2e21a809-85a6-43f7-abf8-267ca26d8d26.png)

**Comment by Regalis11** [comment] 2023-03-30 16:56
1st issue addressed in https://github.com/Regalis11/Barotrauma-development/commit/434d4aea96dd86a75fbcceef9525bf3b3a4f62c7

2nd in https://github.com/Regalis11/Barotrauma-development/commit/ea23d1a15944ba938a347da9b492673b88af3c80

3rd one is a duplicate of https://github.com/Regalis11/Barotrauma/issues/8004

**Comment by Rokvach** [comment] 2023-04-11 09:08
Tested, working correctly. Closing.

**Closed by Rokvach** 2023-04-11 09:08 UTC
Labels: Bug, Code, Localization
