### ISSUE TITLE
Character preview disappears while editing character

### ISSUE THREAD

**Issue by Orum** [Regalis11/Barotrauma#8292] opened 2022-02-15 06:37 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
While making changes to my characters appearance before the game starts, occasionally the preview of my character's face will either disappear entirely or show only the hair.  See [this example](https://cdn.discordapp.com/attachments/587647684794515468/943031789847449630/no_preview.webp).

**Steps To Reproduce**
Join a multiplayer lobby or host your own, and then adjust character appearance settings until the preview vanishes.  It doesn't happen instantly; I usually have to click random a few times before it disappears.  Using the sliders to adjust appearance seems to make it happen faster.

**Version**
Barotrauma v0.15.23.0 Linux

**Additional information**
Not sure if it's related but I have text scaling set well above 100%.

**Comment by Regalis11** [comment] 2022-02-15 12:17
I unfortunately haven't been able to reproduce this. I did encounter a similar issue in our private modding-refactor branch though https://github.com/Regalis11/Barotrauma-development/commit/fc31c19df5d83cd2bbc3654e3fd72487937e3e75, but that seems to be unrelated.

**Comment by Regalis11** [comment] 2022-03-28 14:24
No known steps to repro, closing

**Closed by Regalis11** 2022-03-28 14:24 UTC
Labels: Bug, Need more info, Code
