### ISSUE TITLE
Multiplayer game crashed to desktop for the host (Pipe is broken)

### ISSUE THREAD

**Issue by VelonacepsCalyxEggs** [Regalis11/Barotrauma#10758] opened 2022-12-18 09:33 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Well, I was just playing the campaign with my friends  (there were four of us and four bots.). We were salvaging a pirate that a swarm of husked crawlers just sunk. And suddenly the game froze without the application hang, and just closed to the desktop. 
I've found the server crash report file in the root folder. I'll attach it right here.
P.S
The additional content packages are just my submarines, they are not mods.

### Reproduction steps

I am not sure how and why this happened. The log is the only thing I can provide.

### Bug prevalence

Just once

### Version

0.20.15.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Dedicated Server crash report (generated on 12/18/2022 02:42:52)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


Game version 0.20.15.0 (ReleaseWindows, branch release, revision 0d1158d3aa)
Language: Russian
Selected content packages: Vanilla, Outskirts, The Nibbler
Level seed: Autonoe LineaStaldon Linea
Loaded submarine: Typhon2 (75ED4E51D8B1DE247FEAA11C24C054AE)
Selected screen: Barotrauma.GameScreen
Server (Round had started)


System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit


Exception: Pipe is broken. (System.IO.IOException)
Target site: Void WriteCore(System.ReadOnlySpan`1[System.Byte])
Stack trace: 
   at System.IO.Pipes.PipeStream.WriteCore(ReadOnlySpan`1 buffer)
   at Barotrauma.Networking.ChildServerRelay.<UpdateWrite>g__writeMsg|27_0(WriteStatus writeStatus, Byte[] msg) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 265
   at Barotrauma.Networking.ChildServerRelay.UpdateWrite() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 281
   at System.Threading.Thread.StartCallback()


Last debug messages:
   12/18/2022 02:42:52 - [12/18/2022 02:42:52]
  Saving banlist
   12/18/2022 02:42:51 - [12/18/2022 02:42:51]
  Bryce Sawyer unequipped Отвертка
   12/18/2022 02:42:48 - [12/18/2022 02:42:48]
  Капитан Свинорыл started repairing Кабельная коробка
   12/18/2022 02:42:47 - [12/18/2022 02:42:47]
  Bomjahed placed Топливный бак сварочного аппарата in Пояс инструментов (ID: 11274)
   12/18/2022 02:42:46 - [12/18/2022 02:42:46]
  Barney Chapman equipped Отвертка
   12/18/2022 02:42:45 - [12/18/2022 02:42:45]
  Bryce Sawyer equipped Отвертка
   12/18/2022 02:42:45 - [12/18/2022 02:42:45]
  Капитан Свинорыл equipped Отвертка
   12/18/2022 02:42:45 - [12/18/2022 02:42:45]
  Bomjahed picked up Сварочный аппарат
   12/18/2022 02:42:45 - [12/18/2022 02:42:45]
  Bomjahed removed Сварочный аппарат from Хозяйственный шкаф (ID: 4419)
   12/18/2022 02:42:45 - [12/18/2022 02:42:45]
  Bomjahed placed Шлем стрелка in Хозяйственный шкаф (ID: 4419)
   12/18/2022 02:42:42 - [12/18/2022 02:42:42]
  Bomjahed picked up Бинт
   12/18/2022 02:42:42 - [12/18/2022 02:42:42]
  DONT WORRY IM placed Гранатомет in Большой стальной шкаф (ID: 647)
   12/18/2022 02:42:40 - [12/18/2022 02:42:40]
  Капитан Свинорыл: Какой-то импульс на сонаре. Направление: 11 ч.!
   12/18/2022 02:42:32 - [12/18/2022 02:42:32]
  DONT WORRY IM picked up Гранатомет

P.S "Капитан Свинорыл" is just a special bot, that's why his name is translated. Bryce Sawyer is a bot aswell.
```

**Comment by Regalis11** [comment] 2023-01-04 12:07
Seems like a duplicate of https://github.com/regalis11/barotrauma/issues/9461

**Closed by Regalis11** 2023-01-04 12:07 UTC
