### ISSUE TITLE
My game does not start up.

### ISSUE THREAD

**Issue by Trebleaaa** [Regalis11/Barotrauma#997] opened 2019-01-19 00:17 UTC
So when i try to launch Barotrauma an error message pops up saying "The application was unable to start correctly (0xc00000e5) Click OK to close the application."

I was playing the game on Version v0.8.2.3 on Windows.

I have tried reinstalling the game. And i have tried rebooting computer. Also tried downloading it from a friend who's game works, Also tried launching other .exe files included in the main folder. But nothing has worked so far.

**Comment by etet2** [comment] 2019-01-23 18:07
send the crashreport here

**Comment by Mkxboi** [comment] 2019-01-29 01:58
The Same Problem Happens to me I am running on a all Monitor pc It's a dell And My game will also not start up and I have tried all the following

**Comment by FuzzyFreaks** [comment] 2019-06-01 11:28
My game has also been crashing on startup with no crash report generated. (game version v0.9.0.2)
First launch I got to the language select screen, chose English and it immediately crashed, subsequent attempts crash on startup.
Have tried reinstalling, rebooting PC, verifying files etc.
OS is Windows 10 home, version 1803.

Sorry if this is in the wrong place, I haven't used github before

**Comment by Regalis11** [comment] 2019-06-01 12:47
@FuzzyFreaks Sounds like that could be caused by some kind of issue in playing the splash screens at the start of the game (which appear after the language selection, and on subsequent launches immediately when the game starts). You could try disabling the splash screens by downloading this file and dropping it in the game's installation folder (replacing the existing file if there is one):
https://barotraumagame.com/files/config_player.xml

Sorry for the trouble, let me know if this doesn't help!

**Comment by FuzzyFreaks** [comment] 2019-06-01 12:54
Hi Joonas!

Sadly this hasn't worked, I did try setting splashscreens to "false"
previously too :(

Cheers,
Fuzzy

**Comment by Regalis11** [comment] 2019-06-01 13:06
Another thing worth trying is making sure you have the following libraries installed (which should be done automatically when installing from Steam, but it could be that something went wrong):

.NET Framework, version 4.5 or higher: https://dotnet.microsoft.com/download/dotnet-framework/net472

OpenAL: https://www.openal.org/downloads/OpenAL11CoreSDK.zip

**Comment by FuzzyFreaks** [comment] 2019-06-01 13:20
AHA!

It was OpenAL, which is not something I knew to check for :)
I have zero idea why it didn't auto install during my many attempts to
reinstall the game but that fixed it, THANK YOU!

**Comment by Rokvach** [comment] 2019-07-20 23:48
This issue has already been fixed and further solved, closing.

**Closed by Rokvach** 2019-07-20 23:48 UTC
Labels: Bug, Code
