### ISSUE TITLE
Crash on Startup, Haven't been able to launch game

### ISSUE THREAD

**Issue by BjornTheHorn** [Regalis11/Barotrauma#5501] opened 2021-04-11 19:43 UTC
Hi there, seems a lot of people have similar issues, but I haven't been able to find a solution to let me play the game as of yet. I would appreciate someone pointing me in the right direction to fix this as it looks like a fun game I would like to play.

Here is crashlog #7:

Barotrauma Client crash report (generated on 4/11/2021 2:41:28 PM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

32AA46FAB36BEE9386335D0F440A6AF3

Game version 0.12.0.3 (ReleaseWindows, branch release, revision ea245a2f34)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 6.3.9600.0 64 bit
    GPU name: NVIDIA GeForce GTX 970M
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.
 (SharpDX.SharpDXException)
Device removed reason: HRESULT = 0x887A0020
Target site: Void CheckError()
Stack trace: 
   at SharpDX.Result.CheckError()
   at SharpDX.DXGI.SwapChain.Present(Int32 syncInterval, PresentFlags flags)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 1010
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Present() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.cs:line 601
   at Microsoft.Xna.Framework.SdlGamePlatform.Present() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 245
   at Microsoft.Xna.Framework.Game.EndDraw() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 523
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 511
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59

Last debug messages:
[4/11/2021 2:41:28 PM] Attempting to open ALC device "OpenAL Soft on Speakers (Sound Blaster Recon3Di)"
[4/11/2021 2:41:27 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[4/11/2021 2:41:27 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[4/11/2021 2:41:26 PM] Logged in as Capt. Bjorn XXI (SteamID STEAM_1:0:66935277)

**Comment by Regalis11** [comment] 2021-04-12 11:29
We have an existing ticket about the same issue (https://github.com/Regalis11/Barotrauma/issues/1833), so I'll close this one.

Unfortunately this is a very generic error that can happen due to a lot of reasons, and unfortunately we haven't figured out a reliable way to fix it. It can however be caused by outdated GPU drivers, and some players have been able to get rid of it by updating the drivers, so I recommend giving that a shot 1st!

**Closed by Regalis11** 2021-04-12 11:29 UTC
