### ISSUE TITLE
Bot can't use multiple turrets and is bit of weird.

### ISSUE THREAD

**Issue by war3scv** [Regalis11/Barotrauma#8370] opened 2022-02-25 13:53 UTC
What I did after this confirmed by several other people, place a new coilgun work, add another coilgun——work, add delay——work, add a chaingun——bot still tracking the target but wouldn't fire , so it should be chaingun's problem remove it, still wouldn't fire. I also replace the periscope add and remove drone and shuttle change rotation limits and all those turret's configs seems have no affect on this, even there are only one coilgun remain connected to the periscope bot still wouldn't fire it.

also this seems not occurred reliably, a sub on workshop have multiple turrets(3 coilguns) working fine on creator side but exact same sub not working for me, this also happened to my another sub that have same arrangement.

all testing done in the full vanilla environment.
![T}8OJ~ 1HUO_TBD SS6BINL](https://user-images.githubusercontent.com/95470279/155726418-f6b2e622-7ee9-440e-98ed-d5b78fde9302.png)

 
[sub that buged.zip](https://github.com/Regalis11/Barotrauma/files/8141641/sub.that.buged.zip)

[sub that work(on my side at least).zip](https://github.com/Regalis11/Barotrauma/files/8141651/sub.that.work.on.my.side.at.least.zip)

**Comment by war3scv** [comment] 2022-02-25 14:02
[shuttle and drone.zip](https://github.com/Regalis11/Barotrauma/files/8141716/shuttle.and.drone.zip)
forgot upload buged sub's shuttle and drone.

**Comment by Regalis11** [comment] 2023-04-21 11:04
Finally managed to take a closer look at this.

![image](https://user-images.githubusercontent.com/14351070/233620114-8b59d4ea-aae9-45fd-920e-eb456907f788.png)

 That's a damn impressive sub! I'm afraid it's so complex though that I don't think I'm able to diagnose the issue. It has almost a hundred turrets, and the way they're controlled seems very complex, so I can't personally figure out how all of this is intended to work (or even how to operate it). I think I need a simpler test case and/or clearer steps to reproduce the bug to be able to figure out what the issue is.

@ubertpendragon 
The submarine you provided doesn't seem to be the correct one: it's not the same one included in your screenshot, and it only includes one drone with a turret.

I added a similar kind of "dual coilgun" to Dugong though in an attempt to diagnose the problem:
[Dugong_dualguns.zip](https://github.com/Regalis11/Barotrauma/files/11295124/Dugong_dualguns.zip)

It seems the bots are entirely capable of operating both of the coilguns, _provided they've been ordered to operate the correct one_.

**Comment by ubertpendragon** [comment] 2023-04-22 23:12
I tested the assembly again, it's a niche issue and as you said if the bot mans the proper coilgun it works fine

**Comment by Regalis11** [comment] 2023-06-30 11:26
No known steps to repro, closing

**Closed by Regalis11** 2023-06-30 11:26 UTC
Labels: Bug, Need more info, Code
