### ISSUE TITLE
Ending SteamP2P server process causes game to crash (Pipe is broken / readStream was disconnected unexpectedly)

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#13030] opened 2023-11-15 09:29 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://github.com/Regalis11/Barotrauma/assets/7299826/49a04938-9421-4746-a3f1-2e612d8420d0)

### Reproduction steps

Release:
1. Host a server ingame
2. Open up Task Manager
3. Expand Barotrauma
4. Right click Dedicated Server
5. End task
6. Crash

Debug: 
1. Host a server ingame
2. Close dedicated server console
3. Crash

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.2.1.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Crash 1 ===========================================================================================

Barotrauma Client crash report (generated on 11/15/2023 11:25:43)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

DA507834BF5F79FBABB99E770BBBC6C8

Game version 1.2.1.0 (ReleaseWindows, branch feature/winter-traitor-additions, revision f7d31aac08)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla (B7B803A), Lua For Barotrauma (C98A633), Dugong rotat (A20827F), test (E0EAD6A)
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.NetLobbyScreen
SteamManager initialized
Client (Round hadn't been started)

System info:
    Operating system: Microsoft Windows NT 10.0.22621.0 64 bit
    GPU name: NVIDIA GeForce RTX 4080
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Pipe is broken. (System.IO.IOException)
Target site: Void WriteCore(System.ReadOnlySpan`1[System.Byte])
Stack trace: 
   at System.IO.Pipes.PipeStream.WriteCore(ReadOnlySpan`1 buffer)
   at System.IO.Pipes.PipeStream.Write(ReadOnlySpan`1 buffer)
   at Barotrauma.Networking.ChildServerRelay.<UpdateWrite>g__writeMsg|44_0(WriteStatus writeStatus, Byte[] msg) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 250
   at Barotrauma.Networking.ChildServerRelay.UpdateWrite() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 267
   at System.Threading.Thread.StartCallback()

Last debug messages:
[11/15/2023 11:25:43] WARNING: Tried to restore enabled packages multiple times/without performing a backup
[11/15/2023 11:25:35] Lobby created!
[11/15/2023 11:25:05] Attempting to open ALC device "OpenAL Soft on Beyerdynamic dt 990 pro (2- Realtek USB Audio)"

Crash 2 ===========================================================================================

Barotrauma Client crash report (generated on 11/15/2023 11:25:42)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

DA507834BF5F79FBABB99E770BBBC6C8

Game version 1.2.1.0 (ReleaseWindows, branch feature/winter-traitor-additions, revision f7d31aac08)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla (B7B803A), Lua For Barotrauma (C98A633), Dugong rotat (A20827F), test (E0EAD6A)
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.NetLobbyScreen
SteamManager initialized
Client (Round hadn't been started)

System info:
    Operating system: Microsoft Windows NT 10.0.22621.0 64 bit
    GPU name: NVIDIA GeForce RTX 4080
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: readStream was disconnected unexpectedly (System.Exception)
Target site: Void CheckPipeConnected(System.String, System.IO.Pipes.AnonymousPipeServerStream)
Stack trace: 
   at Barotrauma.Networking.ChildServerRelay.CheckPipeConnected(String name, AnonymousPipeServerStream pipe) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 164
   at Barotrauma.Networking.ChildServerRelay.UpdateRead() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 175
   at System.Threading.Thread.StartCallback()

Last debug messages:
[11/15/2023 11:25:35] Lobby created!
[11/15/2023 11:25:05] Attempting to open ALC device "OpenAL Soft on Beyerdynamic dt 990 pro (2- Realtek USB Audio)"
```

**Comment by Regalis11** [comment] 2023-11-15 13:46
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7985

**Closed by Regalis11** 2023-11-15 13:46 UTC
Labels: Bug, Code
