### ISSUE TITLE
[Unstable 12.0] Ancient Weapon does not cut through Ruin walls

### ISSUE THREAD

**Issue by mrjpjr** [Regalis11/Barotrauma#4918] opened 2021-01-27 14:11 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Ancient Weapon does not cut through Ruin walls.

**Steps To Reproduce**
Use Ancient Weapon to cut through the wall of a Ruin
result: no effect

**Version**
v12.0.0, revision 5b4da6e87f

**Additional information**
https://streamable.com/w9af75

**Comment by Regalis11** [comment] 2021-01-27 16:37
I'm afraid I could not reproduce this. Does it happen every time? I wonder if it could've been an issue in that specific level.

![image](https://user-images.githubusercontent.com/14351070/106021122-24fc2a80-60cd-11eb-9bdb-742485238709.png)

**Comment by Kaillera** [comment] 2021-01-27 16:52
Happens rarely now and then.

**Comment by mrjpjr** [comment] 2021-01-27 18:21
It happens consistently for me, to the point where I have stopped using the ancient weapon altogether.

I just tried it (again) in my SP campaign:
https://streamable.com/qn9ncn

Here is my save file:
[SP Campaign_unstable 1202_.zip](https://github.com/Regalis11/Barotrauma/files/5882203/SP.Campaign_unstable.1202_.zip)

This is the map you'll be in:
![current map](https://user-images.githubusercontent.com/58775950/106035671-c45bf600-60aa-11eb-8545-b05eaaac41fa.jpg)
X is the starting location, the arrows show where the ruin is located.

**Comment by Regalis11** [comment] 2021-01-28 08:53
Thanks, managed to repro it now. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c27bef9

**Comment by Rokvach** [comment] 2021-01-28 09:59
Tested, wasn't able to reproduce the issue. Working correctly, closing.

**Closed by Rokvach** 2021-01-28 09:59 UTC
Labels: Bug, Code, Medium Prio
