### ISSUE TITLE
Stable - Submarine Editor - Item Assemblies do not retain the ID order of their objects

### ISSUE THREAD

**Issue by Ecchi-Ki-Senpai** [Regalis11/Barotrauma#5278] opened 2021-03-20 02:04 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Item assemblies do not retain the ID order of the initial group of objects. This is specifically problematic when turning logic circuits into assemblies because it's possible to run into some inconsistent behavior in the logic system. The same assembly can have multiple different behavior

**Steps To Reproduce**
1) Place 3 memory components and edit their output to be 1, 2 and 3 in the same order you placed them
2) Wire all of them to the same text display
3) Turn the 3 MEM and the text display into an assembly
4) Spawn the assembly about 10 more times
5) Go into test mode
6) Observe the first assembly always displaying 3 (that is normal and expected), and some of the other groups will have different values displayed (that is problematic).

**Version**
Windows - Stable 0.12.0.3

**Additional information**
It is required that component ID order remains the same to guarantee consistent behavior amongst copies of complex systems relying on update order

**Comment by Regalis11** [comment] 2021-03-22 09:21
Duplicate of https://github.com/Regalis11/Barotrauma/issues/1786

**Closed by Regalis11** 2021-03-22 09:21 UTC
