### ISSUE TITLE
Lag ever since last two updates with game appearance, and then Outpost updating.

### ISSUE THREAD

**Issue by GreatBlueMoon** [Regalis11/Barotrauma#9111] opened 2022-05-12 14:00 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

ever since the most recent updates, and people already see this is an issue, i've tried solutions left and right even though considering its on the games end for some of the playerbase.

the game, whenever more than 8 ai crewmates are involved in action, or lategame when you're dealing with the AI of hammersharks for example, in packs of many lategame, especially in singleplayer, the game tanks and you just cant do anything due to input lag.

the game, in its previous state, before the new outpost updates, and before the update before that, the game used to work just fine, and I and many others could actually play the game while being attacked or a hull is torn open, i've needed to resort pure reliance on AI and luck throughout the whole campaign so far because of these lag battles.

i won't argue about the new appearance of crewmates etc past these updates or anything regarding the look of the game now, but I do find it very important people are reminded and are aware of the performance dropping to such a degree.

(funnily enough though, i'm still somehow making it to the end of the campaign) its not totally unplayable, but you will have to rely on AI alot more, and hope the lag doesnt kill their actions.

### Reproduction steps

start a single player game

get +8-10 or more crewmates

go into a late game biome, either the third or fourth+ areas within each passing of a coalition check

the lag can happen when your approaching many spawns of enemies, so just look for enemies.

### Bug prevalence

Happens every time I play

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Not many error messages show up actually, just the performance tanks.

Last crash report is from 2021, no crashes.
```

**Comment by Regalis11** [comment] 2022-05-12 16:02
Duplicate of https://github.com/Regalis11/Barotrauma/issues/8961

**Closed by Regalis11** 2022-05-12 16:02 UTC
