### ISSUE TITLE
[0.9.707] PvP mission does not work

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2258] opened 2020-02-11 21:24 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When trying to start a PvP mission, it results in: (Pic by Juan)
![](https://cdn.discordapp.com/attachments/668819422919524352/676872110869839902/unknown.png)

**Version**
0.9.707

**Comment by Regalis11** [comment] 2020-02-11 21:36
Caused by the same bug as #2258, fixed in https://github.com/Regalis11/Barotrauma-development/commit/084f0b0a750067010178fb7073e3247e26282e09

**Comment by Rokvach** [comment] 2020-02-12 21:42
Cause of issue was reverted, waiting for a merge when done.

**Comment by Rokvach** [comment] 2020-02-28 11:21
Tested, couldn't reproduce so seems to be working. Closing.

**Closed by Rokvach** 2020-02-28 11:21 UTC
Labels: Bug, Code, Networking
