### ISSUE TITLE
Crash to desktop without a "Submit Report" dialog

### ISSUE THREAD

**Issue by fortellao** [Regalis11/Barotrauma#2433] opened 2020-03-13 21:11 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When playing multiplayer, the game crashes often, but no stacktrace, nor "submit report" is displayed after it. I suggest you to implement a top level exception handling to allow us to submit crash reports to you

**Steps To Reproduce**
Just play online for a while and you´ll notice that the CTDs are unhandled

**Version**
Windows 10 and Steam

**Additional information**
I have been experiencing issues with disconnections. It may be due to the somehow high latency, but my ping is always under 50ms anyway

**Comment by thegrb93** [comment] 2020-03-13 21:25
There's supposedly a crash report.txt generated in your Barotrauma folder. I know it worked in previous versions but haven't seen a crash yet so don't know if it still does.

**Comment by thegrb93** [comment] 2020-03-15 07:13
Can confirm I'm not getting crash reports anymore.

**Comment by Regalis11** [comment] 2020-03-15 13:00
This may have been caused by an exception thrown somewhere else than the main thread. If so, https://github.com/Regalis11/Barotrauma-development/commit/62629c8, should fix it as exceptions thrown in any thread are now handled properly.

**Comment by Rokvach** [comment] 2020-03-23 10:50
No issues, closing.

**Closed by Rokvach** 2020-03-23 10:50 UTC
Labels: Bug, Code, Crash
