### ISSUE TITLE
Conversation stuck on screen

### ISSUE THREAD

**Issue by GlockenGold** [Regalis11/Barotrauma#8031] opened 2022-01-13 21:42 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The conversation menu gets stuck with no option to close it.

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.
When talking to the person selling passage to the first of the deeper regions in the campaign, ending the conversation by saying "Don't give them anything.", then starting the conversation again and choosing the same option causes the conversation menu to get stuck on the screen.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).
v0.15.23.0

**Additional information**
In a multiplayer campaign, I am the host. Hosting through Steam.
![image](https://user-images.githubusercontent.com/3051527/149413409-2fd52a67-8263-4f4c-aa1d-3280c841ec4a.png)

**Comment by Regalis11** [comment] 2022-01-14 07:46
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7691

**Closed by Regalis11** 2022-01-14 07:46 UTC
