### ISSUE TITLE
"Clear ruin" mission sometimes fails even tho it indicates it's complete

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8600] opened 2022-03-24 02:15 UTC
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
sometimes you kill all the guardians and destroy all the pods, get the "mission complete" pop-up, but then you dock and the mission is failed

**Version**
0.17.3

**Comment by ekqvist** [comment] 2022-04-14 08:51
I tried reproducing the issue, but couldn't.

AFAIK, it shouldn't be possible for the Clear Ruins missions' state to "move backwards". Once it has been determined that all necessary items and characters have been destroyed/eliminated, the popup for the new mission state is displayed and the mission should rely on the state to determine if it is completed. The status of the items and characters isn't checked again when exiting the level.

On the code-side, only way I see that it should fail is if the main submarine isn't at the start/end when exiting the level, but that shouldn't be the case since you end the level by docking.

Does the issue still happen to you? Are there any specific steps to reproducing it?

**Comment by marpul358** [comment] 2022-05-09 22:08
I've had this now happen twice. Both times I got the pop-up display that said the mission was complete and then when exiting to the next area it was marked as failed.

On the last run I did notice something odd. I found one Fractal Guardian that was not marked on the sonar as a target. Which got me thinking that could there have been more than that of "unmarked targets" possibly? Also noticed that both the last Fractal Guardian that had the target tag on sonar was around 57 meters away from the Alien Ruin structure and the unmarked one was perhaps 30 meters away from any Alien Ruin structure.

**Comment by LePiromano** [comment] 2022-05-18 21:12
still happens in v0.18.1, got the mission complete pop-up and mission failed when i arrived at my destination, my theory is that the mission detects enemies other than fractal guardians, so maybe any random swarmer that spawned after the mission was complete makes it so the mission fails?

**Comment by ekqvist** [comment] 2022-06-09 08:42
Unfortunately, I have still been unable to reproduce this issue. The thing is that once the mission is displayed as completed, it means that all required targets have been eliminated/destroyed. Their state isn't checked again when the mission/level ends so it should be impossible for them to affect the mission in any way after the player has gotten the mission completion popup.

I attempted to address one possible cause for the issue in [08dead9](https://github.com/Regalis11/Barotrauma-development/commit/08dead92050ea99be6fdfd4cc4e25dbfc90d6adb). This commit should fix an issue where the mission could fail after being displayed completed when the player exits the level without the main sub being at the level end.

**Comment by Rokvach** [comment] 2022-06-13 09:15
So far there hasn't been any issues

**Comment by Rokvach** [comment] 2022-06-18 21:00
No encounters of clear ruin missions failing, closing ticket as this seems to be working correctly, if the issue still happens to come up this ticket can be reopened. Closing.

**Closed by Rokvach** 2022-06-18 21:00 UTC
Labels: Bug, Code
