### ISSUE TITLE
Text scaling above 100% causes issues with Health Scanner HUD

### ISSUE THREAD

**Issue by Orum** [Regalis11/Barotrauma#8291] opened 2022-02-15 06:25 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Increasing text scaling causes issues with text overlapping other text when the health scanner HUD is used.  See this [example image](https://cdn.discordapp.com/attachments/690270850926248127/943025704344367124/wtf.webp).

**Steps To Reproduce**
Increase text scaling in the options, go into a game, equip the health scanner HUD, and look at another person with multiple status effects.

**Version**
Barotrauma v0.15.23.0 Linux

**Comment by Regalis11** [comment] 2022-02-15 08:25
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a74ab6b104a87d8d0be9e4a209bda1534302f2d3

**Comment by Lithosagym** [comment] 2022-03-12 02:13
Tested, health scanner HUD text no longer overlaps when the text scaling is over 100%.
Unfortunately, the text still overlaps when _below_ 100% text scaling. (Appears noticeable at 75%-85%)
![image](https://user-images.githubusercontent.com/60911734/157999793-89193844-9a65-41ee-a7ad-02fa471967ff.png)

**Comment by Regalis11** [comment] 2022-03-22 16:59
Was caused by the text scale not being applied to fonts, but being taken into account in the positioning of these texts. Fixing https://github.com/Regalis11/Barotrauma/issues/8552 took care of this as well.

**Comment by Rokvach** [comment] 2022-03-24 10:14
Tested, working correctly. Closing.

**Closed by Rokvach** 2022-03-24 10:14 UTC
Labels: Bug, Code
