### ISSUE TITLE
Can't host multiple servers on single ip

### ISSUE THREAD

**Issue by scrumpi11** [Regalis11/Barotrauma#8877] opened 2022-04-21 08:06 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you try to host dedicated server, everything works correctly. But when you try to start a second server on the same ip but different port, the server starts but doesn't show up in the serverlist. I know that this problem has already been reported in #6412 , but it was almost a year ago. There are several big roleplay projects and we want to host not only rp but also missions or maybe campaign. The problem is that because of this stupid glitch we are forced to buy DIFFERENT hostings for each server, and pay more. It's very dumb and weird glitch, so I decided to report this problem again, and I hope you guys will fix it by the next hotfix.

**Steps To Reproduce**
Launch barotrauma
Launch server on 27015 27016 ports for example
See server appeared in serverlist
Launch another server on different ports
See second server NOT appeared in serverlist

**Version**
v0.17.12.0

**Additional information**
pls fix it, this problem will soon be a year old, and still not fixed. it pretty much slows down the creation of new large servers, like happy traitor, team zero, huskapocalypse, etc.

**Comment by Regalis11** [comment] 2022-04-21 08:28
Closing as a duplicate of https://github.com/Regalis11/Barotrauma/issues/6412

I'll bump the old ticket up in priority though so we get around to fixing this

**Closed by Regalis11** 2022-04-21 08:28 UTC
