### ISSUE TITLE
Slow in starting the game/loading a map, when set to Chinene language.

### ISSUE THREAD

**Issue by DogeTheBiologist** [Regalis11/Barotrauma#8367] opened 2022-02-25 10:41 UTC
- [checked] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When set to Chinese language, it takes extreme long time to start the game or to load a map. In some sircumstances, the game stops loading at 68% or 80%.

**Version**
0.16.6.1

**Notice**
This problem could be seen in several other languages but not English.

**Comment by zhu-rengong** [comment] 2022-02-25 11:14
I tried switching to other languages a few times: in Chinese and Japanese, the loading speed was very slow. But in English and French, it's fast. Hope these information will help devs to fix this bug.

**Comment by Regalis11** [comment] 2022-02-25 12:33
Duplicate of https://github.com/Regalis11/Barotrauma/issues/8365

**Comment by Regalis11** [comment] 2022-02-25 13:38
On a closer look, it seems that the store issue is unrelated to this. This one should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/13a508e though, we'll try to get this hotfixed soon!

**Comment by Rokvach** [comment] 2022-03-10 09:09
Tested, working correctly. Closing.

**Closed by Rokvach** 2022-03-10 09:09 UTC
Labels: Bug, Code, Performance, High prio
