### ISSUE TITLE
Startup crash - \Barotrauma\Data\ContentPackages\Vanilla 0.9.xml' not found.

### ISSUE THREAD

**Issue by sfl55** [Regalis11/Barotrauma#2743] opened 2020-04-30 06:26 UTC
I have searched the issue tracker to check if the issue has already been reported.

**Description**
Game screen starts up black with an error message. Clicking OK crashes the game and provides the following info. If the popup is not OK'd the logo sound plays, but the screen remains black and cannot be interacted with.

Barotrauma Client crash report (generated on 4/30/2020 12:13:30 AM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

To prevent further startup errors, installed mods will be disabled the next time you launch the game.

B88397013C2378C4A99C3E19DEBEE54F

Game version 0.9.9.0 (ReleaseWindows, branch release, revision 0534150c8)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync ON
Selected content packages: None
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.18362.0 64 bit
    GPU name: AMD Radeon (TM) RX 480
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Loading was interrupted due to an error. (Barotrauma.GameMain+LoadingException)
Target site: Void Update(Microsoft.Xna.Framework.GameTime)
Stack trace: 
   at Barotrauma.GameMain.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Barotrauma.Program.Main(String[] args)

InnerException: Object reference not set to an instance of an object.
Target site: Void Init(Microsoft.Xna.Framework.GameWindow, System.Collections.Generic.IEnumerable`1[Barotrauma.ContentPackage], Microsoft.Xna.Framework.Graphics.GraphicsDevice)
Stack trace: 
   at Barotrauma.GUI.Init(GameWindow window, IEnumerable`1 selectedContentPackages, GraphicsDevice graphicsDevice)
   at Barotrauma.GameMain.Load(Boolean isSeparateThread)+MoveNext()
   at Barotrauma.CoroutineManager.ExecuteCoroutineThread(CoroutineHandle handle)
Last debug messages:
[4/30/2020 12:13:30 AM] Coroutine "Load" has failed
[4/30/2020 12:13:30 AM] Coroutine "Load" has thrown an exception {Object reference not set to an instance of an object.}
   at Barotrauma.GUI.Init(GameWindow window, IEnumerable`1 selectedContentPackages, GraphicsDevice graphicsDevice)
   at Barotrauma.GameMain.Load(Boolean isSeparateThread)+MoveNext()
   at Barotrauma.CoroutineManager.ExecuteCoroutineThread(CoroutineHandle handle)
[4/30/2020 12:13:30 AM] No UI styles defined in the selected content package!
[4/30/2020 12:13:30 AM] Attempting to open ALC device "OpenAL Soft"
[4/30/2020 12:13:29 AM] Loaded languages: English
[4/30/2020 12:13:29 AM] No text files available in any of the selected content packages. Attempting to find a vanilla English text file...
[4/30/2020 12:13:29 AM] Content package 'D:\Program Files (x86)\Steam\steamapps\common\Barotrauma\Data\ContentPackages\Vanilla 0.9.xml' not found.
[4/30/2020 12:13:29 AM] Loaded languages: English
[4/30/2020 12:13:29 AM] No text files available in any of the selected content packages. Attempting to find a vanilla English text file...
[4/30/2020 12:13:29 AM] Logged in as XXXXX

**Steps To Reproduce**
Start game from Steam launcher

**Version**
System info in error

**Additional information**

**Comment by Regalis11** [comment] 2020-04-30 07:07
Duplicate of #2713

It seems you're missing the vanilla content package (Barotrauma\Data\ContentPackages\Vanilla 0.9.xml) for some reason. You should be able to fix this by right-clicking the game in your Steam library, going to Properties -> Local files and clicking "verify integrity of game files". Sorry for the trouble!

**Closed by Regalis11** 2020-04-30 07:07 UTC
