### ISSUE TITLE
Diving suit vanished mid-dive

### ISSUE THREAD

**Issue by gerakis** [Regalis11/Barotrauma#7897] opened 2021-12-21 21:52 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Somehow dive suit vanished mid dive. Not sure what caused it. Happened to many, many crew members several times throughout the mission. Pressure did not kill me instantly.

**Steps To Reproduce**
Dont know, went for as swim and several minutes in my suit vanished. I was inside ruins in multiplayer. This happened again as soon as I picked up my old stuff. 

According to other players if someone is wearing a suit while another player is crafting a diving suit, it will remove the first players suit. I dont know if this is true. Someone else was making dive suits at the time so it seems plausible. After they stopped making suits it stopped happening.

**Version**
v0.15.22.1 Windows

**Additional information**
This isnt cool man. This game is getting so buggy I can barely play it. This is very basic functionality that is no longer working.

https://youtu.be/EoSrvTH-8i4

**Comment by Regalis11** [comment] 2022-01-04 09:13
Duplicate of https://github.com/Regalis11/Barotrauma/issues/6403

**Closed by Regalis11** 2022-01-04 09:13 UTC
