### ISSUE TITLE
Items with multiple light components no longer render properly

### ISSUE THREAD

**Issue by Dallasv** [Regalis11/Barotrauma#12290] opened 2023-07-05 18:09 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I've been working on a sub for over a year now with its own modded content.  There are several items containing multiple light components in their XML files.  It appears that some time over the summer, an update was made which causes all objects with multiple light components to no longer render properly.  

There are two ways that the light rendering is no longer correct.  One is that black pixels formerly used in the style of an alpha channel gradient are now being rendered as black pixels instead of absence of light when an item has more than one light component.  The other issue is that settings for blink, pulse and flicker frequency are not being rendered properly on such objects.

This issue occurs both in the sub editor and in multiplayer games.

### Reproduction steps

Make an item with multiple lightcomponents where some of those components use a black background to determine light intensity.

### Bug prevalence

Happens every time I play

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-07-06 07:21
Thank you for the report! Would it be possible to send us the modded light so we can give it a test? I think the issue is probably something else than the item having multiple light components, as many vanilla items use those with no problems (e.g. reactor and junction boxes).

**Comment by Regalis11** [comment] 2023-08-21 08:39
No known steps to repro, closing

**Closed by Regalis11** 2023-08-21 08:39 UTC
Labels: Bug, Need more info, Modding

**Comment by Dallasv** [comment] 2023-08-21 17:04
The steps to reproduce are listed in my submission tho.

**Comment by Regalis11** [comment] 2023-08-22 07:22
Yes, but unfortunately we could not reproduce the issue. There are several items in the game with multiple light components that do not have this issue, so I think it most likely has something to do with how the custom item has been configured, and we'd need a copy of it to be able to diagnose this. Sorry for the inconvenience!
