### ISSUE TITLE
Having lobby issue

### ISSUE THREAD

**Issue by DetectiveKaktus** [Regalis11/Barotrauma#7445] opened 2021-11-22 15:23 UTC
- [Y] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Lobby issue when everybody cannot spawn if I host the server.
We can't spawn by becoming spectators. If we spawn, we have extra high ping (300+);

**Steps To Reproduce**
1. Host lobby with serious gamemode;
2. Join by yourself and your friend to reprocude it;
3. Start game in campaign;
4. Wait loading and you have not to spawn and become spectator mode OR spawn with high ping;

**Version**
Windows 10 64 bit, barotrauma v.0.15.13.0, revision 4e66dd7b5d

**Additional information**
Checking integrity of game files says that I lost 3 files sometimes. What files I cannot say.

Playing vanila barotrauma without any mods or like that.

It works only with my lobby

**Comment by Regalis11** [comment] 2021-11-22 15:45
Thank you for the report!

I'm not entirely sure I understand the problem correctly: do you mean that the players get placed as spectators even if they hadn't selected "play as spectator" in the server lobby, or that they sometimes do but sometimes spawn normally? How do you measure the ping or where do you see it? The ping should be practically 0 if you're hosting the server yourself, but otherwise a ping of 300 should only happen if the players are physically very far from you (e.g. in a different continent).

**Comment by DetectiveKaktus** [comment] 2021-11-22 15:49
> Thank you for the report!
> 
> I'm not entirely sure I understand the problem correctly: do you mean that the players get placed as spectators even if they hadn't selected "play as spectator" in the server lobby, or that they sometimes do but sometimes spawn normally? How do you measure the ping or where do you see it? The ping should be practically 0 if you're hosting the server yourself, but otherwise a ping of 300 should only happen if the players are physically very far from you (e.g. in a different continent).

Yes, I mean players get placed as spectatorts even they selected 'play as spectator'.

High ping cannot be cuz we are in one city.

**Comment by Regalis11** [comment] 2021-11-22 15:53
How do you see/measure the ping? It sounds strange that the ping would be different when you're spectating than when you're controlling a character, so I wonder if it could be a performance issue (= low FPS) as opposed to a problem with high ping.

**Comment by DetectiveKaktus** [comment] 2021-11-22 15:57
Wait a minute. There are 2 ways this issue can be.
The first way is spawning as spectator. In this issue ping is ok.
The second way is spawning as character. In this issue ping is not ok.

This is not performance issue. 6 month ago everything was ok I have good pc for barotrauma.

**Comment by Regalis11** [comment] 2021-11-22 15:59
How do you see/measure the ping?

**Comment by Regalis11** [comment] 2021-11-22 16:04
Thank you for the clarification! I'll do some debugging - it could be that there's something wrong with the ping readings in the tab menu.

**Comment by DetectiveKaktus** [comment] 2021-12-05 11:30
Now lobby doesnt host ever.

Game says to check servercrashreport.log in game folder but there is no file like it. 

https://media.discordapp.net/attachments/157565009726144513/917013873968689162/unknown.png?width=751&height=469

**Comment by Regalis11** [comment] 2022-04-20 17:43
Duplicate of https://github.com/Regalis11/Barotrauma/issues/4081

**Closed by Regalis11** 2022-04-20 17:43 UTC
Labels: Bug, Code, Networking
