### ISSUE TITLE
[Feature Request] [Polish] Tutorial should probably refer to keybinds when referencing what buttons to press in dialogue

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1436] opened 2019-04-26 01:51 UTC
Tutorials should tell players to use whatever button is set to "interact" when telling them how to interact with something, or when using any other button for any other purpose for that matter. ex: If your interaction button is set to "E", the medical tutorial dialogue still tells you to interact using (Mouse1), presumably because it was written with the new default keybinds in mind.

**Comment by Regalis11** [comment] 2019-04-30 07:55
I think this was caused by an incorrect keybind in the medical tutorial text (Use instead of Select). Should be fixed now.

**Closed** 2019-05-20 16:48 UTC
Labels: Bug, Code
