### ISSUE TITLE
[0.9.9.1] Game crashes when starting mission or training

### ISSUE THREAD

**Issue by evenbaro** [Regalis11/Barotrauma#2829] opened 2020-05-14 13:22 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Game crashes when starting a new game og training. 

**Steps To Reproduce**
Launching any of the training module will cause the game to crash.
Starting first mission will cause game to crash.

Barotrauma Client crash report (generated on 14.05.2020 14:16:02)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

023CCD07C102F6331CAD29D2EADB01E0

Game version 0.9.9.1 (ReleaseWindows, branch release, revision 1968ab79f)
Graphics mode: 1920x1080 (Fullscreen)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: nLoZLLtza
Loaded submarine: Dugong_Tutorial (E327F30A352B4F0D1A97A7F95059767F)
Selected screen: Barotrauma.GameScreen

System info:
    Operating system: Microsoft Windows NT 10.0.18362.0 64 bit
    GPU name: NVIDIA GeForce GTX 1060
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void UpdateWaterAmbience(Single, Single)
Stack trace: 
   at Barotrauma.SoundPlayer.UpdateWaterAmbience(Single ambienceVolume, Single deltaTime)
   at Barotrauma.SoundPlayer.Update(Single deltaTime)
   at Barotrauma.GameMain.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Barotrauma.Program.Main(String[] args)

Last debug messages:
[14.05.2020 14:15:41] Error after assigning ALC context: Invalid device. Disabling audio playback...
[14.05.2020 14:15:40] Attempting to open ALC device "OpenAL Soft"
[14.05.2020 14:15:40] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[14.05.2020 14:15:39] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean

**Comment by Regalis11** [comment] 2020-05-14 14:13
Duplicate of #2747 

It seems the game fails to open an audio device for some reason, and crashes when it tries to play the water ambience sounds. Do you have some kind of audio device (headset, speakers) connected? If not, connecting one should get rid of this error. But in any case, we need to also make sure the game doesn't crash even if there is no audio device present.

**Closed by Regalis11** 2020-05-14 14:13 UTC
