### ISSUE TITLE
[Factions] Turret can block hitscan type projectiles.

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#10640] opened 2022-12-02 05:39 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

It seems this only occur in unstable version/faction branch.
It is tested that non-hitscan type projectile are not blocked, but only hitscan type.

Picture in 0.19.14.0
![0 19_fine](https://user-images.githubusercontent.com/99462070/205222485-9ffa0b26-398c-4f49-8cbb-eafee38ebc37.png)

Pictures in faction branch
![0 20_bad](https://user-images.githubusercontent.com/99462070/205222572-4deeaad4-bb4f-4ad5-9fdb-46b26eb77903.png)
![0 20_bad_2](https://user-images.githubusercontent.com/99462070/205222585-eeb6339b-2526-4a22-99e5-1cb839e1dc51.png)

### Bug prevalence

Happens every time I play

### Version

0.20.9.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-12-04 11:53
Only seems to occur in the faction branch, caused by the changes in https://github.com/Regalis11/Barotrauma-development/commit/328d10dc7b6ae360928301fb3d6a64dafa5e7a31

**Comment by NilanthAnimosus** [comment] 2022-12-15 13:52
Tested against WIP-Fixes commit https://github.com/Regalis11/Barotrauma-development/commit/307f89d6fad8cb458206f814d5b108ae830bd564, no issues found, closing.

**Closed by NilanthAnimosus** 2022-12-15 13:52 UTC
Labels: Bug, Code
