### ISSUE TITLE
crach barotrauma

### ISSUE THREAD

**Issue by hamzagould36** [Regalis11/Barotrauma#2662] opened 2020-04-18 17:25 UTC
Barotrauma Client crash report (generated on 18/04/2020 18:09:22)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

5F2265FBBD6C5E538A99B1A8D98CAEB7

Game version 0.9.8.0 (ReleaseWindows, branch release, revision c227d35b6)
Graphics mode: 1600x900 (BorderlessWindowed)
VSync ON
Selected content packages: Vanilla 0.9
Level seed: KrytogorskAylesbury
Loaded submarine: Selkie (752533F1036AA51FD0EA2F800FEB43B5)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.17763.0 64 bit
    GPU name: Intel(R) HD Graphics 3000
    Display mode: {Width:1600 Height:900 Format:Color AspectRatio:1,7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Boolean IsOperatedByAnother(Barotrauma.Character, Barotrauma.Items.Components.ItemComponent, Barotrauma.Character ByRef)
Stack trace: 
   at Barotrauma.AIObjectiveOperateItem.IsOperatedByAnother(Character character, ItemComponent target, Character& operatingCharacter) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjectiveOperateItem.cs:line 85
   at Barotrauma.CrewManager.GetBestCharacterForOrder(Order order) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameSession\CrewManager.cs:line 2292
   at Barotrauma.CrewManager.<CreateOrderOptionNode>b__129_0(GUIButton _, Object userData) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameSession\CrewManager.cs:line 1982
   at Barotrauma.CrewManager.UpdateProjectSpecific(Single deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameSession\CrewManager.cs:line 1091
   at Barotrauma.CrewManager.Update(Single deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\GameSession\CrewManager.cs:line 62
   at Barotrauma.CampaignMode.Update(Single deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameModes\CampaignMode.cs:line 114
   at Barotrauma.SinglePlayerCampaign.Update(Single deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\SinglePlayerCampaign.cs:line 156
   at Barotrauma.GameSession.Update(Single deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 329
   at Barotrauma.GameScreen.Update(Double deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 124
   at Barotrauma.GameMain.Update(GameTime gameTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 882
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 57

Last debug messages:
[18/04/2020 18:07:54] OpenAL Soft on Microphone (Realtek High Definition Audio) 57
[18/04/2020 18:07:52] OpenAL Soft on Microphone (Realtek High Definition Audio) 57
[18/04/2020 18:07:34] OpenAL Soft on Microphone (Realtek High Definition Audio) 57
[18/04/2020 18:00:46] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[18/04/2020 18:00:46] Content package load order: Vanilla 0.9
[18/04/2020 18:00:37] Attempting to open ALC device "OpenAL Soft"
[18/04/2020 18:00:35] Pack de contenu E:\Games\SteamLibrary\steamapps\common\Barotrauma\Mods\Typhon Mk. III\filelist.xml introuvable.
[18/04/2020 18:00:35] Pack de contenu E:\Games\SteamLibrary\steamapps\common\Barotrauma\Mods\ALIEN - XENOMORPH\filelist.xml introuvable.
[18/04/2020 18:00:35] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[18/04/2020 18:00:35] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[18/04/2020 18:00:29] Logged in as hamzagould36 (SteamID STEAM_1:1:514271623)

**Comment by Regalis11** [comment] 2020-04-19 09:54
Duplicate of #2620

**Closed by Regalis11** 2020-04-19 09:54 UTC
