### ISSUE TITLE
unsudden crash (DXGI_ERROR_DEVICE_REMOVED)

### ISSUE THREAD

**Issue by createro1** [Regalis11/Barotrauma#13014] opened 2023-11-12 04:20 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

i was casually trading.

### Reproduction steps

nothing spesific

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 11/12/2023 07:13:34)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

The crash was caused by the DirectX error DeviceHung (HRESULT = 0x887A0006). This is a common DirectX error that can be related to various different issues, such as outdated drivers, RAM problems or an overclocked or otherwise overstressed GPU. There are several potential ways to fix the issue: ensuring your graphics drivers and DirectX installation are up-to-date, disabling overclocking and adjusting various GPU-specific settings. You may also be able to find potential solutions to the problem by using the error code DeviceHung (HRESULT = 0x887A0006) and your GPU manufacturer as search terms.

152BA3E19FDBF5D0CE7AEC3CB5E83BE4

Game version 1.1.19.3 (ReleaseWindows, branch release/traitor-update-hotfix-2, revision e92ea6f791)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: Turkish
Selected content packages: Vanilla (D6A9CBF)
Level seed: Pastonia26
Loaded submarine: Barsuk (E0C638DE838A1B642CB6E78A84BF3253)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.22631.0 64 bit
    GPU name: NVIDIA GeForce RTX 3060 Laptop GPU
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: GPU aygıt örneği askıya alınmış. Uygun eylemi belirlemek için GetDeviceRemovedReason komutunu kullanın.
 (SharpDX.SharpDXException)
Device removed reason: DeviceHung (HRESULT = 0x887A0006)
Target site: Void PlatformPresent()
Stack trace: 
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 1017
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[11/12/2023 07:13:01] Unlocked mission "Silah Teslimatı" in the connection from "Pastonia İstihkâmı" to "Sparti Linea Mesken Üssü".
[11/12/2023 07:12:59] Unlocked mission "Kazı Galen" in the connection from "Pastonia İstihkâmı" to "Sparti Linea Mesken Üssü".
[11/12/2023 07:12:57] Unlocked mission "Koalisyon Personeli Nakli" in the connection from "Pastonia İstihkâmı" to "Sparti Linea Mesken Üssü".
[11/12/2023 07:12:19] Generating an outpost for the start of the level... (Location: Pastonia İstihkâmı, level type: Outpost)
[11/12/2023 07:12:19] Level identifier: outpostlevel
[11/12/2023 07:12:10] Transitioning to Pastonia26 (current location: Sharpitor Linea Mesken Üssü, selected location: Pastonia İstihkâmı, leaving sub: Barsuk, at start: False, at end: True, transition type: ProgressToNextLocation)
[11/12/2023 06:45:56] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
[11/12/2023 06:45:53] Generating an outpost for the start of the level... (Location: Sharpitor Linea Mesken Üssü, level type: LocationConnection)
[11/12/2023 06:45:53] Generating an outpost for the end of the level... (Location: Pastonia İstihkâmı, level type: LocationConnection)
[11/12/2023 06:45:52] Level identifier: coldcavernsadvanced
[11/12/2023 06:45:44] Transitioning to Pastonia26Sharpitor Linea44 (current location: Sharpitor Linea Mesken Üssü, selected location: Pastonia İstihkâmı, leaving sub: Barsuk, at start: True, at end: False, transition type: LeaveLocation)
[11/12/2023 06:44:11] Unlocked mission "Mudraptörlerden kurtulmak" in the connection from "Sharpitor Linea Mesken Üssü" to "Pastonia İstihkâmı".
[11/12/2023 06:44:09] Unlocked mission "Kazı Galen" in the connection from "Sharpitor Linea Mesken Üssü" to "Pastonia İstihkâmı".
[11/12/2023 06:44:07] Unlocked mission "Koalisyon Personeli Nakli" in the connection from "Sharpitor Linea Mesken Üssü" to "Pastonia İstihkâmı".
[11/12/2023 06:40:43] Unlocked mission "Tarikatçı Nakli" in the connection from "Sharpitor Linea Mesken Üssü" to "Pastonia İstihkâmı".
[11/12/2023 06:39:15] Generating an outpost for the start of the level... (Location: Sharpitor Linea Mesken Üssü, level type: Outpost)
[11/12/2023 06:39:15] Level identifier: outpostlevel
[11/12/2023 06:39:06] Transitioning to Sharpitor Linea44 (current location: Wolstone, selected location: Sharpitor Linea Mesken Üssü, leaving sub: Barsuk, at start: False, at end: True, transition type: ProgressToNextLocation)
[11/12/2023 06:29:15] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
[11/12/2023 06:29:12] Generating an outpost for the start of the level... (Location: Wolstone, level type: LocationConnection)
[11/12/2023 06:29:12] Generating an outpost for the end of the level... (Location: Sharpitor Linea Mesken Üssü, level type: LocationConnection)
[11/12/2023 06:29:11] Level identifier: coldcavernsadvanced
[11/12/2023 06:29:02] Transitioning to Sharpitor Linea44Wolstone59 (current location: Wolstone, selected location: Sharpitor Linea Mesken Üssü, leaving sub: Barsuk, at start: True, at end: False, transition type: LeaveLocation)
[11/12/2023 06:27:25] Unlocked mission "Patlayıcı yük" in the connection from "Wolstone" to "Bramerton Mesken Üssü".
[11/12/2023 06:27:23] Unlocked mission "Mudraptörlerden kurtulmak" in the connection from "Wolstone" to "Sharpitor Linea Mesken Üssü".
[11/12/2023 06:27:21] Unlocked mission "Ayrılıkçı Nakli" in the connection from "Wolstone" to "Sharpitor Linea Mesken Üssü".
[11/12/2023 06:21:14] Unlocked mission "Kornanneye şükür" in the connection from "Wolstone" to "Bramerton Mesken Üssü".
[11/12/2023 06:20:54] Generating an outpost for the start of the level... (Location: Wolstone, level type: Outpost)
[11/12/2023 06:20:54] Level identifier: outpostlevel
[11/12/2023 06:20:46] Transitioning to Wolstone59 (current location: Astypalaea Linea, selected location: Wolstone, leaving sub: Barsuk, at start: False, at end: True, transition type: ProgressToNextLocation)
[11/12/2023 06:12:51] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
[11/12/2023 06:12:49] Generating an outpost for the end of the level... (Location: Wolstone, level type: LocationConnection)
[11/12/2023 06:12:48] Level identifier: coldcavernsadvanced
[11/12/2023 06:12:40] Transitioning to Wolstone59Astypalaea Linea88 (current location: Astypalaea Linea, selected location: Wolstone, leaving sub: Barsuk, at start: False, at end: True, transition type: ProgressToNextEmptyLocation)
[11/12/2023 05:52:03] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
[11/12/2023 05:51:16] Generating an outpost for the start of the level... (Location: Moulin Tesisi, level type: LocationConnection)
[11/12/2023 05:51:16] Level identifier: coldcavernsadvanced
[11/12/2023 05:45:29] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
[11/12/2023 05:45:20] Generating an outpost for the start of the level... (Location: Moulin Tesisi, level type: LocationConnection)
[11/12/2023 05:45:20] Level identifier: coldcavernsadvanced
[11/12/2023 05:25:05] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
[11/12/2023 05:24:36] Generating an outpost for the start of the level... (Location: Moulin Tesisi, level type: LocationConnection)
[11/12/2023 05:24:35] Level identifier: coldcavernsadvanced
[11/12/2023 05:24:08] Attempting to open ALC device "OpenAL Soft on ROG FUSION II 500 (Chat channel) (ROG FUSION II 500)"
[11/12/2023 05:24:03] Logged in as deleteduserv3.2 (SteamID STEAM_1:1:678512867)
```

**Comment by Regalis11** [comment] 2023-11-12 10:53
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10540

**Closed by Regalis11** 2023-11-12 10:53 UTC
