### ISSUE TITLE
In the multiplayer game on a camel sub, bots began to work worse than before the last patch.

### ISSUE THREAD

**Issue by pavel4win** [Regalis11/Barotrauma#12017] opened 2023-05-16 11:25 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Prior to the patch, they constantly got stuck on the forward stairs between the upper and middle decks.
But it was not so critical.
Now trying to climb these stairs and falling back to the middle deck bot completely freeze and ignore any orders.
In this case, in order for the bot to start obeying orders again, you have to completely reset the order queue and set it again.
Soon the bot gets stuck again in the same place and all over again.
In a single player campaign game, I did not notice such behavior of bots.
It became impossible to play with bots in a multiplayer game on a camel, please fix it.

### Reproduction steps

1. start multiplayer campaign with bots on camel sub
2. give orders to bot (repair devices, serve cannon, repair leaks)
3. when the path of the bot is through the front stairs bot freezes

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-05-16 12:46
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11984

**Closed by Regalis11** 2023-05-16 12:46 UTC
