### ISSUE TITLE
Can't switch submariens in multiplayer games

### ISSUE THREAD

**Issue by Wojtek0415** [Regalis11/Barotrauma#7895] opened 2021-12-21 19:18 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you play in a multiplayer game switching subs is not possible

**Steps To Reproduce**
Bought a submarine but could not switch in the terminal.

**Version**
v0.15.22.1 Windows

**Comment by MaaiG** [comment] 2021-12-22 12:18
- [x] Mega kill:
https://github.com/Regalis11/Barotrauma/issues/7862 | https://github.com/Regalis11/Barotrauma/issues/7873 | https://github.com/Regalis11/Barotrauma/issues/7874

**Comment by MaaiG** [comment] 2021-12-22 12:20
- [x] Mega kill 😉
https://github.com/Regalis11/Barotrauma/issues/7862 | https://github.com/Regalis11/Barotrauma/issues/7873 | https://github.com/Regalis11/Barotrauma/issues/7874

**Comment by Wojtek0415** [comment] 2021-12-22 12:27
Okay, my bad, should have looked more. Any news on when this could be fixed?

**Comment by MaaiG** [comment] 2021-12-22 12:31
I don’t know, but I think maybe next year...

**Comment by thomasheath1996** [comment] 2021-12-22 20:31
I've submitted a pull request for a potential fix to this bug. While you wait for the devs, you can bypass this by having more credits than the price of the sub you want to switch to and it should let you switch! :)

**Comment by Regalis11** [comment] 2021-12-29 12:26
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7862

**Closed by Regalis11** 2021-12-29 12:26 UTC
