### ISSUE TITLE
Freecamera problems

### ISSUE THREAD

**Issue by SenhorPatolino** [Regalis11/Barotrauma#2535] opened 2020-03-30 06:29 UTC
- [ X ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Freecamera works fine for most of time, but holding CTRL to move the camera slower makes it just freeze and keep shaking, it also happens when you are already moving the camera and hold CTRL.

**Version**
0.9.9.0 on Windows.

**Comment by Regalis11** [comment] 2020-03-30 10:29
I unfortunately wasn't able to reproduce this.

**Comment by SenhorPatolino** [comment] 2020-03-31 16:08
Go for subeditor, and keep moving the camera, if you hold CTRL to make it slower the camera keeps stuck in same place just shaking a bit

**Comment by Regalis11** [comment] 2020-04-07 08:40
Ah, I didn't test it in the sub editor, thanks for the clarification! I think this is intentional though, because combinations like Ctrl+A and Ctrl+S are used as hotkeys in the editor.

**Comment by Rokvach** [comment] 2020-04-07 09:00
I don't see why you would even use freecamera on the sub editor, well except if you are filming and want to slowly move around. But the Ctrl specific hotkeys takes a higher prio here. Not an issue so closing.

**Closed by Rokvach** 2020-04-07 09:00 UTC
Labels: Bug, Code
