### ISSUE TITLE
eye of europe

### ISSUE THREAD

**Issue by Matiz753** [Regalis11/Barotrauma#12795] opened 2023-10-13 10:28 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

when reset mission eye of europe there no items and no mission, cant get trouth big doors again

### Reproduction steps

return to lobby

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted using a dedicated server

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Failed to load sound file "Content/ContentPackages/ogg/Fabricator.ogg" (file not found). {Sound file "C:/Program Files (x86)/Steam/steamapps/common/Barotrauma/Content/ContentPackages/ogg/Fabricator.ogg" doesn't exist!}
   at Barotrauma.Sounds.SoundManager.LoadSound(String filename, Boolean stream) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sounds\SoundManager.cs:line 361
   at Barotrauma.RoundSound.Load(ContentXElement element, Boolean stream) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\RoundSound.cs:line 112
```

**Comment by Regalis11** [comment] 2023-10-13 11:16
Duplicate of https://github.com/Regalis11/Barotrauma/issues/12575

**Closed by Regalis11** 2023-10-13 11:16 UTC
