### ISSUE TITLE
crash on wrecked vessel mission

### ISSUE THREAD

**Issue by caydenberry** [Regalis11/Barotrauma#3932] opened 2020-09-28 00:02 UTC
Barotrauma Client crash report (generated on 9/27/2020 5:00:10 PM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

6F558E05A9FD96EA104348A23A5B582A

Game version 0.10.5.1 (ReleaseWindows, branch release, revision 9e259b2148)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: Onga LineaChandelle Crevasse
Loaded submarine: Dugong (825C59B62C2CFE7D6A4387319B5A83C9)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19041.0 64 bit
    GPU name: NVIDIA GeForce GTX 1070
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Collection was modified; enumeration operation may not execute. (System.InvalidOperationException)
Target site: Void ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
Stack trace: 
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Barotrauma.Items.Components.RepairTool.Repair(Vector2 rayStart, Vector2 rayEnd, Single deltaTime, Character user, Single degreeOfSuccess, List`1 ignoredBodies) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Holdable\RepairTool.cs:line 297
   at Barotrauma.Items.Components.RepairTool.Use(Single deltaTime, Character character) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Holdable\RepairTool.cs:line 244
   at Barotrauma.Item.Use(Single deltaTime, Character character, Limb targetLimb) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 2055
   at Barotrauma.Character.Control(Single deltaTime, Camera cam) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 1475
   at Barotrauma.Character.Update(Single deltaTime, Camera cam) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2409
   at Barotrauma.AICharacter.Update(Single deltaTime, Camera cam) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\AICharacter.cs:line 86
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2228
   at Barotrauma.GameScreen.Update(Double deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 179
   at Barotrauma.GameMain.Update(GameTime gameTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 921
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59

Last debug messages:
[9/27/2020 4:52:01 PM] Generating an outpost for the start of the level... (Location: Onga Linea Fortification, level type: LocationConnection)
[9/27/2020 4:52:00 PM] Generating an outpost for the end of the level... (Location: Chandelle Crevasse City, level type: LocationConnection)
[9/27/2020 4:50:39 PM] (Msg) RelayNetWorkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[9/27/2020 4:50:39 PM] (Msg) Ping location: lax=10+1,sea=148+14/34+1,eat=148+14/38+1,okc=231+23/49+1,ord=183+18/56+1,iad=214+21/72+1,atl=214+21/75+1,tyo1=144+14/128+1,fra=176+17/150+1,lhr=143+14/152+1,gru=179+17/189+1,sgp=202+20/215+1
[9/27/2020 4:50:39 PM] (Msg) Ping measurement completed
[9/27/2020 4:50:37 PM] (Verbose) Communications with routing cluster 'sto2' established.
[9/27/2020 4:50:37 PM] (Debug) Destroying relay 'sto2#27 (155.133.252.35:27041)' because initial_ping_timeout
[9/27/2020 4:50:35 PM] (Verbose) Communications with routing cluster 'sgp' established.
[9/27/2020 4:50:35 PM] (Verbose) Communications with routing cluster 'vie' established.
[9/27/2020 4:50:35 PM] (Verbose) Communications with routing cluster 'waw' established.
[9/27/2020 4:50:35 PM] (Verbose) Communications with routing cluster 'sto' established.
[9/27/2020 4:50:35 PM] (Verbose) Communications with routing cluster 'syd' established.
[9/27/2020 4:50:35 PM] (Verbose) Communications with routing cluster 'tyo' established.
[9/27/2020 4:50:35 PM] (Verbose) Communications with routing cluster 'tyo1' established.
[9/27/2020 4:50:35 PM] (Verbose) Communications with routing cluster 'maa' established.
[9/27/2020 4:50:35 PM] (Verbose) Communications with routing cluster 'jnb' established.
[9/27/2020 4:50:34 PM] (Verbose) Communications with routing cluster 'scl' established.
[9/27/2020 4:50:34 PM] (Verbose) Communications with routing cluster 'mad' established.
[9/27/2020 4:50:34 PM] (Verbose) Communications with routing cluster 'lux' established.
[9/27/2020 4:50:34 PM] (Verbose) Communications with routing cluster 'dxb' established.
[9/27/2020 4:50:34 PM] (Verbose) Communications with routing cluster 'par' established.
[9/27/2020 4:50:34 PM] (Verbose) Communications with routing cluster 'lhr' established.
[9/27/2020 4:50:34 PM] (Verbose) Communications with routing cluster 'lim' established.
[9/27/2020 4:50:34 PM] (Verbose) Communications with routing cluster 'sea' established.
[9/27/2020 4:50:34 PM] (Verbose) Communications with routing cluster 'bom' established.
[9/27/2020 4:50:34 PM] (Verbose) Communications with routing cluster 'ord' established.
[9/27/2020 4:50:34 PM] (Verbose) Communications with routing cluster 'gru' established.
[9/27/2020 4:50:34 PM] (Verbose) Communications with routing cluster 'okc' established.
[9/27/2020 4:50:34 PM] (Verbose) Communications with routing cluster 'hkg' established.
[9/27/2020 4:50:34 PM] (Verbose) Communications with routing cluster 'fra' established.
[9/27/2020 4:50:34 PM] (Verbose) Communications with routing cluster 'ams' established.
[9/27/2020 4:50:34 PM] (Msg) Relay lax#11 (162.254.195.70:27025) is going offline in 91 seconds
[9/27/2020 4:50:34 PM] (Verbose) Communications with routing cluster 'lax' established.
[9/27/2020 4:50:34 PM] (Verbose) Communications with routing cluster 'iad' established.
[9/27/2020 4:50:34 PM] (Verbose) Communications with routing cluster 'atl' established.
[9/27/2020 4:50:34 PM] (Verbose) Communications with routing cluster 'eat' established.
[9/27/2020 4:50:34 PM] (Msg) RelayNetWorkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[9/27/2020 4:50:34 PM] (Msg) Performing ping measurement
[9/27/2020 4:50:34 PM] (Msg) Got SDR network config.  Loaded revision 281 OK
[9/27/2020 4:50:34 PM] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[9/27/2020 4:50:26 PM] Attempting to open ALC device "OpenAL Soft on Speakers (Realtek High Definition Audio)"
[9/27/2020 4:50:25 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[9/27/2020 4:50:25 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[9/27/2020 4:50:23 PM] Logged in as ------ (SteamID STEAM_1:0:--------)

**Comment by Regalis11** [comment] 2020-09-28 07:25
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3896

**Closed by Regalis11** 2020-09-28 07:25 UTC
