### ISSUE TITLE
[Unstable] Electrical engineer Bot no longer handles the reactor without orders

### ISSUE THREAD

**Issue by dmeff** [Regalis11/Barotrauma#6042] opened 2021-06-11 21:09 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
It used to be that the electrical engineer bot would always take care of the reactor, even without having the order. Now it just stays idle.

**Steps To Reproduce**
Have an electrical engineer bot without orders

**Version**
Windows 10, unstable beta

**Additional information**

**Comment by ekqvist** [comment] 2021-06-14 09:41
Can't properly reproduce this. When leaving an outpost, the bots will power up the reactor first before starting to idle. And if you go and take out the fuel rod, they will replace it. There was an intentional change done to this that if a player operates the reactor then bots won't operate it unless ordered to do so. See #5134.

But if there is still an issue with this or I'm misunderstanding your issue, please let me know and I'll look into it further,

**Comment by itchyOwl** [comment] 2021-07-14 10:21
If the reactor is out of power, one of the bots should turn the reactor on, unless it was manually turned off by the player. If the reactor is on, the bot should go idle or continue doing other stuff when acting autonomously (no orders). If the bot is orderd to operate the reactor, it should keep overwatching it.

Can't reproduce any issues.

**Comment by ekqvist** [comment] 2021-07-26 13:41
Closing as no issues can be reproduced with the current information.

**Closed by ekqvist** 2021-07-26 13:41 UTC
Labels: Bug, Code, Need more info
