### ISSUE TITLE
[0.9.703] Issues that I can't really explain together or seperately all in one place

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2146] opened 2020-02-04 22:03 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

I'm going to change up the order here, it's better you should see for yourselves first before reading the description.

**Steps To Reproduce**
1. Load up multiplayer, killdisconnecttime very high, campaign on Berilia. Preferably with 2 or more people.
2. Bot Count to 12
3. Bot Spawn Mode to Fill
4. Buy 60 Steel, 40 Aluminum, 40 Oxygen Tanks, 36 Stabilozine, 1 Stun Baton, 1 Battery.
5. Find a "Killing a Matriarch" mission.

**Description**
So several things happen here...

1. Excessive Desync. I assume players get kicked due to the large amount of items created by the Auto Spawner on the mass amount of storage on the Berilia combined with the cargo that was bought. Juan and me were on Nil's server for this, and even with a high killdisconnecttime, I wasn't able to reconnect (Constantly getting kicked for desync). Not sure what was going on in @juanjp600's end. The round was ended with Juan leaving.

2. I came back after Juan left and started the round solo on Nil's server and was immediately kicked to the main menu to this:
![](https://cdn.discordapp.com/attachments/668819422919524352/674361483035017216/Capture.PNG)

3. The round ended, and I came back to start the round again to the same mission. This time I was able to spawn in and I was able to hear a hammerhead spawn in the sub, but I cannot see it even if I knew where it was. The sonar radar confirmed it in the sub. When I ended the round, I was able to see the hammerhead as the ending scrolls through the sub.
![](https://cdn.discordapp.com/attachments/668819422919524352/674358693739102228/Capture.PNG)
![](https://cdn.discordapp.com/attachments/668819422919524352/674359026074779659/Capture.PNG)

4. After restarting the round again, when I inspected all the cabinets, all the cargo I bought and the items that were supposed to spawn into the cabinets were completely missing. I've tested this by creating a new save with the same seed, and same mission, and same purchase on Nil's server. When I did spawned in, there was no cargo and item spawned.

**Version**
0.9.703

**Comment by NilanthAnimosus** [comment] 2020-02-04 22:24
Theres a good deal of information to help define these issues but I have yet to go through the chat enough to work out how to compile it to separate issues yet despite understanding a decent enough amount of it perhaps.

for 1, the disconnect reason was due to very old events, around 18-19 seconds. 903 total as the first "too high" message, the time difference and disconnection occured at event 904, presumably this event was the first of the actual round itself.

2 is completely unknown, other than the networking broke when receiving a message from the server, there really is no other info from my side as the host.

don't know about 3.

For 4, the round ended after a massive excessive desync kick because syncing 903 entity events at round start resulted in about an 18 second old event kick to the first event of the round.

it ended in failure (not vote end) under the guise of all clients are dead as there were no clients left, presumably this is different from voting to end as this was directly preceding the lack of any items.

I assume this resulted in the submarine to not save, but the auto item placer did not go off again, leaving every cabinet devoid of items, as well as perhaps the money to remain spent and lost as the store bought cargo would perhaps not have saved either.

**Comment by Kaillera** [comment] 2020-02-05 00:42
Just trying to start a campaign round on Aggressive Hammerhead mission on the same sub, same purchase, but the round after the first allowing all Berilia's spawner to spawn in.
![](https://user-images.githubusercontent.com/5086682/73800306-4bbba580-4786-11ea-9918-ecfd8ee2ed89.PNG)

**Comment by Regalis11** [comment] 2020-02-09 11:34
I think the "index was outside the bounds of the array" and "key was not present in the dictionary" errors may have been caused by the same issue that caused https://github.com/Regalis11/Barotrauma/issues/2189 (character health data taking up more than 255 bytes, preventing the clients from reading the rest of the message correctly).

The desync kick was probably caused by the round start taking too much time client-side, which should be fixed by https://github.com/Regalis11/Barotrauma-development/commit/3f50497bb4a720590b5b71a6553d364bc6c31064 once that's merged.

**Closed** 2020-02-25 12:22 UTC
Labels: Bug, Code, Networking, Waiting
