### ISSUE TITLE
[V0.1100.0.6] Beacon sonar GUI overlap

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#4316] opened 2020-11-14 23:41 UTC
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Cant activate the active sonar on the powered beacon station because the GUI elements are overlapping.

**Steps To Reproduce**
Open Sonar station - GUI overlaps. Check pic

**Version**
Win [V0.1100.0.6] , 1680x1050 resolution

![20201115002458_1](https://user-images.githubusercontent.com/3466193/99159265-44dd9e00-26db-11eb-8318-3763f9298ef3.jpg)

**Comment by CurePindal** [comment] 2020-11-14 23:47
Woops, Seems its related: https://github.com/Regalis11/Barotrauma/issues/4305

**Comment by Regalis11** [comment] 2020-11-15 11:10
Duplicate of https://github.com/Regalis11/Barotrauma/issues/4305

**Closed by Regalis11** 2020-11-15 11:10 UTC
