### ISSUE TITLE
The game crashed in the middle of the tutorial

### ISSUE THREAD

**Issue by Drowsiness1** [Regalis11/Barotrauma#2704] opened 2020-04-25 13:30 UTC
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/4533021/crashreport.log)
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/4533022/crashreport.2.log)

**Comment by Shadow-Of-Cat** [comment] 2020-04-25 13:49
Dude, check the graphic card, the game starts with intel card instead of discrete graphics card. My friend changed it in invidia settings, try to find tutorial how to do it on your laptop

**Comment by Regalis11** [comment] 2020-04-25 14:04
Duplicate of #1833

**Closed by Regalis11** 2020-04-25 14:04 UTC
