### ISSUE TITLE
Main Menu UI Issues

### ISSUE THREAD

**Issue by abyssalVisionary** [Regalis11/Barotrauma#9584] opened 2022-07-17 02:45 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

<img width="1440" alt="huh" src="https://user-images.githubusercontent.com/109446734/179381456-6cb86cbf-2971-4061-93c5-506167819484.png">
parts of main menu ui and artwork are cut off upon launching the game. moving the cursor to these regions of the screen also cause it to disappear. i have not attempted to click on the locations where the missing ui would be to see if the actual functional parts of the menu are still there. relevant to note that clicking on an option that is visible, such as the sub editor, and returning to the main menu afterwards will resolve the issue and show full main menu.

### Reproduction steps

1. Be on a MacOS Mojave computer
2. Launch Barotrauma by clicking desktop shortcut

### Bug prevalence

Happens every time I play

### Version

Other

### -

0.18.15.0

### Which operating system did you encounter this bug on?

MacOS

### Relevant error messages and crash reports

```shell
game does not produce error box, and the issue never results in a crash
```

**Comment by Regalis11** [comment] 2022-07-17 13:23
Duplicate of https://github.com/Regalis11/Barotrauma/issues/5597

**Closed by Regalis11** 2022-07-17 13:23 UTC
