### ISSUE TITLE
Not the correct model of the gun holder

### ISSUE THREAD

**Issue by KioraLi** [Regalis11/Barotrauma#10076] opened 2022-10-13 21:27 UTC
![20221013235717_1](https://user-images.githubusercontent.com/115744741/195713889-7c781687-87db-4647-967c-205a5867069b.jpg)
There is definitely a problem here.

**Comment by Regalis11** [comment] 2022-10-14 06:48
Duplicate of https://github.com/Regalis11/Barotrauma/issues/9986

**Closed by Regalis11** 2022-10-14 06:48 UTC
