### ISSUE TITLE
[0.1001.0] Possible to overvolt outpost from Sub's reactor

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2969] opened 2020-06-04 12:18 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Possible to overvolt outpost from Sub's reactor

**Version**
0.1001.0

**Comment by Regalis11** [comment] 2020-06-04 13:46
Duplicate of #2917

**Closed by Regalis11** 2020-06-04 13:46 UTC
