### ISSUE TITLE
打开加工台崩溃

### ISSUE THREAD

**Issue by crazy6363** [Regalis11/Barotrauma#11938] opened 2023-05-02 03:44 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

每次打开加工台就会报错

### Reproduction steps

每次打开加工台报错，直接闪退
[crashreport (7).log](https://github.com/Regalis11/Barotrauma/files/11369487/crashreport.7.log)

### Bug prevalence

Happens every time I play

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 05/02/2023 11:31:16)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

8BE661744288B03127E103F2FAFCC948

Game version 1.0.9.0 (ReleaseWindows, branch release/1.0-hotfix-2, revision 64dcc9f061)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: Simplified Chinese
Selected content packages: Vanilla, 无限燃料棒, 莱德的二次元贴图替换, Dont Open Debug Console On Errors, Wreck Locator 沉船定位器, Cs For Barotrauma, BetterHealthUI, Brighter Lights, Duffle Bag 2.0, Backpack & WaistBelt, 4x Stack 4倍堆叠上限, Lua For Barotrauma, MoreMissionsMod, 111, 222, 自用, Dugong++
Level seed: Hyldemoer34Malcam's Cauldron62
Loaded submarine: 自用2 (E58D755A5CB66C33D802C501F9F92E6E)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce RTX 3050 Laptop GPU
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Function does not accept floating point Not-a-Number values. (System.ArithmeticException)
Target site: Int32 Sign(Single)
Stack trace: 
   at System.Math.Sign(Single value)
   at Barotrauma.Items.Components.Fabricator.<RefreshAvailableIngredients>g__compare|113_0(Item item1, Item item2, Inventory inputInventory) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Machines\Fabricator.cs:line 788
   at Barotrauma.Items.Components.Fabricator.RefreshAvailableIngredients() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Machines\Fabricator.cs:line 719
   at Barotrauma.Items.Components.Fabricator.UpdateHUD(Character character, Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\Machines\Fabricator.cs:line 845
   at Barotrauma.Item.UpdateHUD(Camera cam, Character character, Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 1193
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 131
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 881
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[05/02/2023 11:30:10] Invalid stat type type "AttackMultiplier" in item (crowbar)
[05/02/2023 11:30:10] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[05/02/2023 11:30:10] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[05/02/2023 11:29:54] WARNING: Item greenpaint has multiple Holdable components (Holdable, Throwable).
[05/02/2023 11:29:54] WARNING: Item greenpaint has multiple Holdable components (Holdable, Throwable).
[05/02/2023 11:29:54] WARNING: Item greenpaint has multiple Holdable components (Holdable, Throwable).
[05/02/2023 11:29:54] WARNING: Item greenpaint has multiple Holdable components (Holdable, Throwable).
[05/02/2023 11:29:54] WARNING: Item whitepaint has multiple Holdable components (Holdable, Throwable).
[05/02/2023 11:29:54] WARNING: Item whitepaint has multiple Holdable components (Holdable, Throwable).
[05/02/2023 11:29:54] WARNING: Item bluepaint has multiple Holdable components (Holdable, Throwable).
[05/02/2023 11:29:54] WARNING: Item bluepaint has multiple Holdable components (Holdable, Throwable).
[05/02/2023 11:29:54] WARNING: Item blackpaint has multiple Holdable components (Holdable, Throwable).
[05/02/2023 11:29:54] WARNING: Item blackpaint has multiple Holdable components (Holdable, Throwable).
[05/02/2023 11:29:54] Invalid stat type type "AttackMultiplier" in item (crowbar)
[05/02/2023 11:29:54] Invalid stat type type "AttackMultiplier" in item (crowbar)
[05/02/2023 11:29:54] Invalid stat type type "AttackMultiplier" in item (crowbar)
[05/02/2023 11:29:53] WARNING: Potentially invalid damage modifier in "防弹头盔, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[05/02/2023 11:29:53] WARNING: Potentially invalid damage modifier in "防暴头盔, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[05/02/2023 11:29:53] WARNING: Potentially invalid damage modifier in "炮手头盔, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[05/02/2023 11:29:53] Invalid stat type type "AttackMultiplier" in item (crowbar)
[05/02/2023 11:29:53] Invalid stat type type "AttackMultiplier" in item (crowbar)
[05/02/2023 11:29:53] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[05/02/2023 11:29:53] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[05/02/2023 11:29:53] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[05/02/2023 11:29:53] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[05/02/2023 11:29:53] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[05/02/2023 11:29:50] Invalid stat type type "AttackMultiplier" in item (crowbar)
[05/02/2023 11:29:50] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[05/02/2023 11:29:50] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[05/02/2023 11:29:50] WARNING: Potentially invalid damage modifier in "防弹头盔, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[05/02/2023 11:29:50] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[05/02/2023 11:29:50] WARNING: Potentially invalid damage modifier in "防弹头盔, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[05/02/2023 11:29:50] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[05/02/2023 11:29:50] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[05/02/2023 11:29:50] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[05/02/2023 11:29:49] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[05/02/2023 11:29:49] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[05/02/2023 11:29:49] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[05/02/2023 11:29:49] WARNING: Potentially invalid damage modifier in "炮手头盔, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[05/02/2023 11:29:49] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[05/02/2023 11:29:49] WARNING: Potentially invalid damage modifier in "炮手头盔, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[05/02/2023 11:29:49] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[05/02/2023 11:29:49] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[05/02/2023 11:29:49] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[05/02/2023 11:29:49] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[05/02/2023 11:29:49] WARNING: Potentially invalid damage modifier in "炮手头盔, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[05/02/2023 11:29:49] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[05/02/2023 11:29:49] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[05/02/2023 11:29:49] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[05/02/2023 11:29:49] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[05/02/2023 11:29:49] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[05/02/2023 11:29:48] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[05/02/2023 11:29:48] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[05/02/2023 11:29:48] WARNING: Potentially invalid damage modifier in "防弹头盔, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[05/02/2023 11:29:48] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[05/02/2023 11:29:41] Generating an outpost for the end of the level... (Location: Malcam's Cauldron开采设施, level type: LocationConnection)
[05/02/2023 11:29:40] Generating an outpost for the start of the level... (Location: Hyldemoer研究设施, level type: LocationConnection)
[05/02/2023 11:29:37] WARNING: Failed to find a valid position far enough from the main path. Choosing the furthest possible position.
   at System.Environment.get_StackTrace()
   at Barotrauma.Level.FindPosAwayFromMainPath(Double minDistance, Boolean asCloseAsPossible, Nullable`1 limits) in C:\Users\joona\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\Level.cs:line 2246
   at Barotrauma.Level.GenerateCaves(Tunnel parentTunnel) in C:\Users\joona\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\Level.cs:line 1973
   at Barotrauma.Level.Generate(Boolean mirror, Location startLocation, Location endLocation) in C:\Users\joona\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\Level.cs:line 679
   at Barotrauma.Level.Generate(LevelData levelData, Boolean mirror, Location startLocation, Location endLocation, SubmarineInfo startOutpost, SubmarineInfo endOutpost) in C:\Users\joona\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\Level.cs:line 489
   at Barotrauma.GameSession.StartRound(LevelData levelData, Boolean mirrorLevel, SubmarineInfo startOutpost, SubmarineInfo endOutpost) in C:\Users\joona\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 464
   at Barotrauma.SinglePlayerCampaign.DoLoadInitialLevel(LevelData level, Boolean mirror)+MoveNext() in C:\Users\joona\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\SinglePlayerCampaign.cs:line 280
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in C:\Users\joona\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 198
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in C:\Users\joona\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 229
   at Barotrauma.CoroutineManager.Update(Boolean paused, Single deltaTime) in C:\Users\joona\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 272
   at Barotrauma.GameMain.Update(GameTime gameTime) in C:\Users\joona\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 742
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in C:\Users\joona\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
[05/02/2023 11:29:37] Level identifier: ridgebasic
[05/02/2023 11:29:31] Invalid stat type type "AttackMultiplier" in item (crowbar)
[05/02/2023 11:29:28] Invalid stat type type "AttackMultiplier" in item (autoshotgun)
[05/02/2023 11:29:28] Invalid stat type type "AttackMultiplier" in item (autoshotgun)
[05/02/2023 11:29:07] WARNING: Potential error in item variant "slipsuit": the item inherits the fabrication requirement of x1 "rubber"  from the base item "combatdivingsuit". If this is not intentional, you can use empty <RequiredItem /> elements in the item variant to remove any excess inherited fabrication requirements.
[05/02/2023 11:29:07] WARNING: Potential error in item variant "slipsuit": the item inherits the fabrication requirement of x1 "titaniumaluminiumalloy"  from the base item "combatdivingsuit". If this is not intentional, you can use empty <RequiredItem /> elements in the item variant to remove any excess inherited fabrication requirements.
[05/02/2023 11:29:07] WARNING: Error in "oxygenitetank"'s fabrication recipe: out condition is above 100% (10000).
[05/02/2023 11:29:07] WARNING: Potential error in item variant "slipsuit": the item inherits the fabrication requirement of x1 "rubber"  from the base item "combatdivingsuit". If this is not intentional, you can use empty <RequiredItem /> elements in the item variant to remove any excess inherited fabrication requirements.
[05/02/2023 11:29:07] WARNING: Potential error in item variant "slipsuit": the item inherits the fabrication requirement of x1 "titaniumaluminiumalloy"  from the base item "combatdivingsuit". If this is not intentional, you can use empty <RequiredItem /> elements in the item variant to remove any excess inherited fabrication requirements.
[05/02/2023 11:29:07] WARNING: Potential error in item variant "slipsuit": the item inherits the fabrication requirement of x1 "rubber"  from the base item "combatdivingsuit". If this is not intentional, you can use empty <RequiredItem /> elements in the item variant to remove any excess inherited fabrication requirements.
[05/02/2023 11:29:07] WARNING: Potential error in item variant "slipsuit": the item inherits the fabrication requirement of x1 "titaniumaluminiumalloy"  from the base item "combatdivingsuit". If this is not intentional, you can use empty <RequiredItem /> elements in the item variant to remove any excess inherited fabrication requirements.
[05/02/2023 11:29:06] WARNING: Error in "oxygenitetank"'s fabrication recipe: out condition is above 100% (10000).
[05/02/2023 11:29:06] WARNING: Potential error in item variant "slipsuit": the item inherits the fabrication requirement of x1 "rubber"  from the base item "combatdivingsuit". If this is not intentional, you can use empty <RequiredItem /> elements in the item variant to remove any excess inherited fabrication requirements.
[05/02/2023 11:29:06] WARNING: Potential error in item variant "slipsuit": the item inherits the fabrication requirement of x1 "titaniumaluminiumalloy"  from the base item "combatdivingsuit". If this is not intentional, you can use empty <RequiredItem /> elements in the item variant to remove any excess inherited fabrication requirements.
[05/02/2023 11:28:42] Attempting to open ALC device "OpenAL Soft on 扬声器 (Realtek(R) Audio)"
[05/02/2023 11:28:36] Logged in as Crazy63 (SteamID STEAM_1:1:450568511)
```

**Comment by Regalis11** [comment] 2023-05-02 06:40
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11817

**Closed by Regalis11** 2023-05-02 06:40 UTC
