### ISSUE TITLE
Multiplayer high ping, players time out after docking/ending a round/starting a round

### ISSUE THREAD

**Issue by Melolatius** [Regalis11/Barotrauma#5863] opened 2021-05-22 11:17 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
No matter who of my friends is hosting a game, we all (even the host) have high ping spikes. Sometimes they pop up at random, and sometimes they pop up when we are getting attacked by a large swarm of Crawlers or something similar happens. Is it because of a game error/bug or something like that, or is that a clientside issue?

If the sub docks at an outpost, the players sometimes have to rejoin because they receive a timeout. However, if we start a mission we received from an outpost dweller, they all always time out and have to rejoin.

**Steps To Reproduce**
Load up a private MP game
Start a campaign
Select a mission and undock
-(Players should time out here)
Travel through the level and dock at an outpost
-(Players should time out here)

**Version**
Windows 10
![grafik](https://user-images.githubusercontent.com/63376072/119224670-d0f3d680-baff-11eb-9eda-df43fc4b1809.png)

**Additional information**
Sometimes, this console message pops up
Coroutine "Barotrauma.Networking.GameClient+<StartGame>d__93" has failed
Does this have anything to do with the timing out?

**Comment by Regalis11** [comment] 2021-05-24 07:10
Duplicate of https://github.com/Regalis11/Barotrauma/issues/5791

**Closed by Regalis11** 2021-05-24 07:10 UTC
