### ISSUE TITLE
Corrupted saves

### ISSUE THREAD

**Issue by Bojovnikus** [Regalis11/Barotrauma#12229] opened 2023-06-26 07:30 UTC
Hello everyone, I encountered such a problem in Barotrauma. My friend and I played this wonderful game and the next time we docked with the station, the game crashed, therefore the save on which we played was damaged and we cannot start it. I honestly tried to solve the problem myself but could not, can you help somehow? I can throw off the save and the list of mods (if needed). And I apologize for my English, I wrote part of this appeal with the help of a translator. Thank you in advance!
![image](https://github.com/Regalis11/Barotrauma/assets/137762076/ed1084b3-9cf2-419f-982b-9c4a585cf3bd)

**Comment by Regalis11** [comment] 2023-06-26 09:06
Duplicate of https://github.com/Regalis11/Barotrauma/issues/12104

**Closed by Regalis11** 2023-06-26 09:06 UTC
