### ISSUE TITLE
Campaign Host - disconnection for all players between rounds

### ISSUE THREAD

**Issue by FollyR** [Regalis11/Barotrauma#5715] opened 2021-05-07 06:30 UTC
- [y] I have searched the issue tracker to check if the issue has already been reported.
_Found similar closed tickets but could not see a resolution for this specific problem._

**Description**
Every time I host a Campaign server and a round is completed (entering/leaving a station) it causes 100% of other players to disconnect. This happens every time, both in vanilla game and with mods, and doesn't seem to be effected by region of player.
Below is excerpt from latest campaign server log:
[New campaign - Sparkles_2021-05-07_1549 copy.txt](https://github.com/Regalis11/Barotrauma/files/6439418/New.campaign.-.Sparkles_2021-05-07_1549.copy.txt)

[5/7/2021 3:44:46 PM]
  Not Peter has died (Cause of death: Disconnected)
[5/7/2021 3:44:56 PM]
  DocMal has died (Cause of death: Disconnected)
[5/7/2021 3:44:56 PM]
  Angel has died (Cause of death: Disconnected)
[5/7/2021 3:44:56 PM]
  Spades has died (Cause of death: Disconnected)
[5/7/2021 3:44:56 PM]
  Kimberly has died (Cause of death: Disconnected)
[5/7/2021 3:44:56 PM]
  yupa has died (Cause of death: Disconnected)

**Steps To Reproduce**
Host a campaign server and complete a mission with another player in the server - player disconnection happens every time.

**Version**
Barotrauma v0.13.0.11
Mac OS Catalina v10.15.7

**Additional information**

**Comment by Regalis11** [comment] 2021-05-07 07:31
Most likely a duplicate of https://github.com/Regalis11/Barotrauma/issues/5702.

**Closed by Regalis11** 2021-05-07 07:31 UTC

**Comment by FollyR** [comment] 2021-05-07 07:34
Great, thanks Regalis. I'll keep an eye on referenced ticket.
