### ISSUE TITLE
Infinite Storage

### ISSUE THREAD

**Issue by aeondez** [Regalis11/Barotrauma#10737] opened 2022-12-16 17:53 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Makeshift Shelves can be stored inside storage crates and cabinets and cargo scooters.

Because you can put makeshift shelves inside cabinets, and fill those shelves with crates full of makeshift shelves, it allows for infinitely recursive storage. You can also fill a cargo scooter with makeshift shelves full of storage crates full of makeshift shelves ad infinitum, and functionally carry an infinite inventory.

### Reproduction steps

1. Craft Makeshift Shelves
2. Put Makeshift shelves inside something else (cabinets, crates, cargo scooter, but weirdly not the Exosuit)
3. Put a crate full of makeshift shelves inside makeshift shelves
4. Put those makeshift shelves inside a storage crate

### Bug prevalence

Happens every time I play

### Version

0.20.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-12-19 12:15
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/37777c5ab6ed23e6178fd1381915dca4647945c1

**Comment by itchyOwl** [comment] 2022-12-19 15:32
Tested, working.

**Comment by itchyOwl** [comment] 2022-12-19 15:48
Seems to work as intended: can't place makeshift shelves inside other containers anymore.

**Comment by NilanthAnimosus** [comment] 2022-12-20 09:37
Tested against bugfixes commit https://github.com/Regalis11/Barotrauma-development/commit/3f32dd2540c4790006ce65b83e648e1672c88071, no issues found, closing.

**Closed by NilanthAnimosus** 2022-12-20 09:37 UTC
Labels: Bug, Design
