### ISSUE TITLE
Repair window shows up when using periscope

### ISSUE THREAD

**Issue by iridescent-lightning** [Regalis11/Barotrauma#7817] opened 2021-12-17 05:49 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
After the new updates, if you make turrets repairable, the repair windows will show up when you use the periscope even if it is in full health.

**Steps To Reproduce**
1. Edit the railgun.xml and make railgun turret repairable.
2.  install the new railgun in game and use periscope.
3. You will see the repair window shows up.

**Version**
v0.15.21

**Comment by Regalis11** [comment] 2021-12-17 08:16
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7812

**Closed by Regalis11** 2021-12-17 08:16 UTC
Labels: Bug, Code, Modding
