### ISSUE TITLE
Incorrect display of submarine name when buying new sub and switching to it

### ISSUE THREAD

**Issue by Sailtor** [Regalis11/Barotrauma#13337] opened 2024-01-22 15:44 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When trying to buy a new submarine with switching to it the game shows "[submarinename]" instead if the actual name of the new sub:
![screen2](https://github.com/Regalis11/Barotrauma/assets/17296454/0e120352-c56d-4d28-b572-112340a68883)

This seems to happen with all the subs and only if you chose to buy and switch to the new sub. Buying sub without switching to it displays the name correctly:
![20240122182938_1](https://github.com/Regalis11/Barotrauma/assets/17296454/a01d57c4-277a-4657-a62d-2306c86a671f)

I don't know if it's a localization problem but if anything, it's the Russian version of the game.

### Reproduction steps

1. Switch the game to Russian localization
2. Start a singleplayer campaign
3. Go to submarine seller
4. Try to buy a new sub with switching to it

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2024-01-23 07:12
Duplicate of https://github.com/Regalis11/Barotrauma/issues/13268

**Closed by Regalis11** 2024-01-23 07:12 UTC
