### ISSUE TITLE
Barotrauma blog dont provide css with 403 code (forbiden) in Russian Federation

### ISSUE THREAD

**Issue by Muz1kash1** [Regalis11/Barotrauma#12852] opened 2023-10-20 10:25 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Trying to acess [https://barotraumagame.com/announcements/coming-next-week-treacherous-tides-update/](url) got back webpage without css, and when looked at logs its returning Failed to load resource: the server responded with a status of 403 ()

### Reproduction steps

1. Turn on any VPN service and connect to Russian IP
2. Go by this link [https://barotraumagame.com/announcements/coming-next-week-treacherous-tides-update/](url)

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Other

### -

Not about the game but about the site

### Version

Other

### Which operating system did you encounter this bug on?

Linux

### Relevant error messages and crash reports

```shell
I think this have some link whith OVHcloud provider but not entirely sure
```

**Comment by Regalis11** [comment] 2023-10-20 10:30
Duplicate of https://github.com/Regalis11/Barotrauma/issues/12830

**Closed by Regalis11** 2023-10-20 10:30 UTC
