### ISSUE TITLE
Occasional Invisible Impassable Wall between docking hatch of shuttle.

### ISSUE THREAD

**Issue by Cpt-RegalBeagle** [Regalis11/Barotrauma#5817] opened 2021-05-17 08:34 UTC
- [X ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When having a shuttle either docked or undocked to the main sub (occasionally) the shuttle will create an invisible barrier on the docking ports and will not allow players to pass for the rest of the mission. The issue is temporarily resolved again when transitioning to the next area. Ragdolling over the hatch will cause the game to glitch out as if the character is falling through the map.

**Steps To Reproduce**
I have not found the trigger for this yet. Testing on single player for an hour, I was not able to reproduce. I was also not able to reproduce in sub editor. On multiplayer, this will happen every few zones. Really hard to troubleshoot a problem that might not surface until the 6th mission into a campaign.

Download "Immortal X" Sub and play campaign, trying to use the shuttle as much as possible. It will happen......

**Version**
Vanilla, v0.13.3.11

**Additional information**
I have completely rewired the Shuttle. Repositioned hulls and gaps many times. Problem seems to only exist in the shuttle and not on the main sub's docking hatch.

**Comment by Regalis11** [comment] 2021-05-17 13:54
Thank you for the report. I'm afraid I could not get this to happen, even after travelling through several levels, repeatedly docking and undocking the shuttle and leaving it to a previous level and then recovering it. So I'm guessing it might only happen in some specific situation or after some specific actions, just couldn't figure out what those are.

If you happen to have a save file where this happen, sending that to us would help a lot in diagnosing this. Note that the save files need to be .zipped to attach them here, since GitHub doesn't support the .save file extension.

Sorry for the inconvenience!

**Comment by Cpt-RegalBeagle** [comment] 2021-05-17 15:59
It seems to happen more often when more than 1 player attempts to pass through the docking hatch at the same time. Again very difficult to reproduce. I have tried to reproduce this on my own and have failed.

The save file will likely not have the bug, when the level loads whatever is affecting the docking hatch is reset. This only seems to happen whilst in a zone and is reset in the next zone or when the game is reloaded.

**Comment by Leonidas-ai** [comment] 2021-05-24 13:50
He's not wrong. It's entirely random and has something to do with desync and timing on the docking port. Docking ports that work in the editor and single player flawlessly can become stuck with an invisible barrier between sort of like the gap failed to connect. I assume it's some issue with bad timing on generating the docking effect which locks something up in the process of connecting hulls. It resolves after a restart of the game and due to the random chance involved with client/server timing will be impossible to reproduce deterministically probably.

**Comment by Cpt-RegalBeagle** [comment] 2021-05-25 01:32
I'm still trying to replicate it..... Of course it doesn't happen now that I want it to!

**Comment by Regalis11** [comment] 2021-05-25 13:17
It seems one way this can happen is if the door is broken, fixed that one in https://github.com/Regalis11/Barotrauma-development/commit/2bcbb896c24afba1192bd145251d5e2f622e1e22

**Comment by Rokvach** [comment] 2021-05-28 11:06
Tested, wasn't able to reproduce the issue. Seems to be working correctly. closing.

**Closed by Rokvach** 2021-05-28 11:06 UTC
Labels: Bug, Code, Need more info, Needs testing
