### ISSUE TITLE
Cannot Connect to Any Server

### ISSUE THREAD

**Issue by ParalyzedTortoise** [Regalis11/Barotrauma#3909] opened 2020-09-25 19:21 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
While I can host my own server, and others can connect to it, I cannot join any other server either through steam, or the server browser, it simply states "Connecting..." for about 30 seconds, before stating "Unable to connect." When I attempt to direct connect using a specific Steam ID, I get this error: "Steam P2P connection could not be established. You have been disconnected from the server. Reconnecting..."

**Steps To Reproduce**
Considering other people can play the game just fine, I have no clue how this could be reproduced.

**Version**
The game version is v0.10.4.0. I am running on Windows 10.

**Additional information**
I have tried to fix the problem on my own in many ways, such as: verifying my game files, reinstalling the game, restarting my PC and creating exceptions for the game in both my firewall and antivirus.

**Comment by Kaillera** [comment] 2020-09-28 10:04
This can be caused by using non english characters name in your name.

**Comment by Regalis11** [comment] 2020-09-28 11:37
This could be caused by https://github.com/Regalis11/Barotrauma/issues/3939. Normally the game should give you an error popup explaining why you were unable to join, but there's a bug in the current version that prevents it from working correctly.

As Kaillera mentioned, you may be able to work around the issue by making sure the name in the "player name" field in the server browser doesn't contain any special symbols. Latin, Cyrillic, Japanese, Korean and Chinese symbols, numbers and common special symbols (dots, dashes, commas, brackets) are fine, but rare unicode symbols may prevent you from joining.

**Comment by Blu3wolf** [comment] 2020-09-29 13:46
I have this with one specific server. I only have Latin characters in my steam username though.

**Comment by Kaillera** [comment] 2020-09-29 16:42
> I have this with one specific server. I only have Latin characters in my steam username though.

Might be a ghost server.

**Comment by thegrb93** [comment] 2020-09-29 17:59
Ghost servers are annoying. There were 4 of them at a time stuck on the server browser forever.

**Comment by Regalis11** [comment] 2020-11-17 11:43
Hard to do much about this without further info, let's hope it was caused by #3939 and fixed with the latest update.

**Closed by Regalis11** 2020-11-17 11:43 UTC
Labels: Bug, Code, Need more info, Networking
