### ISSUE TITLE
[Bug][Mapgen][0.9.1.0]Check if map is playable first

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1707] opened 2019-06-25 04:43 UTC
![2019-06-24-233907_857x511_scrot](https://user-images.githubusercontent.com/47284081/60069695-81b98700-96d9-11e9-90c8-1d4275c6ebf0.png)
This is the result of a humorous start to a campaign round in which the outpost was in a position that started my ship submerged in a rock. The second I undocked, the ships collision (understandably) spazzed out and the ship shot up and got stuck in the ceiling.
A fix for this would obviously be in map generation and making sure the map is actually playable. A while back on twitter regalis mentioned some device he had that simulated a map generation and checked to see if a sub could go through. Wouldn't it be advantageous to just scrap a map and generate a new one if the current one failed a test like that?
I know new map generation is eventually planned, but while we wait for it it woud be nice to have stuff like this not happen with some sort of failsafe.

**Comment by Regalis11** [comment] 2019-06-25 13:04
Duplicate of #1681 

The game should make sure the map is playable, but it seems that the system is bugged. If you still happen to have the map seed (or even better, a save file) it would help a lot in diagnosing this issue.

**Closed by Regalis11** 2019-06-25 13:04 UTC

**Comment by hubismal** [comment] 2019-06-26 03:04
I DMed the .save file to you over discord since github restricts filetypes.
