### ISSUE TITLE
Lots of Downloaded Subs Significantly Hurts Memory Usage

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#4432] opened 2020-12-04 23:19 UTC
[Bug, Crash]
I'm surprised I didn't find this reported already as it's such a common and severe issue.
Having lots of subs in the Submarines/Downloaded/ directory significantly worsens memory usage for some reason. Mods take signficantly longer to enable, loading times are occasionally quadrupled, servers are unable to be hosted and crash on trying, disconnections are frequent because of loading inconsistencies, general framerate is worse. Initially I assumed this was because the game was loading lots of heavy custom thumbnails of subs into the sub selection screen for singleplayer, but the terrible performance persists throughout all screens of the game. On occasion, this was so severe that my system (with 11GB RAM) ran out of memory at times.

Deleting downloaded subs fixes this, obviously.

If this is a duplicate, sorry about that. I just really want to make sure this bug doesn't stay around for a long time.

**Comment by Regalis11** [comment] 2020-12-05 14:19
Thank you for the ticket! We've had reports about (what I suspect is) the same issue, but hadn't been able to reproduce it because I wasn't aware it only occurred when the submarines have been downloaded directly from a server, not with subs downloaded from the Workshop. Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/8e14b2b94cff6dc444ea6e72016b91baa06e0051

**Comment by Rokvach** [comment] 2021-01-18 09:43
Tested, didn't notice any issues with this, downloaded subs are being deleted just fine. Closing.

**Closed by Rokvach** 2021-01-18 09:43 UTC
Labels: Bug, Code, High prio
