### ISSUE TITLE
[Unstable] Selecting an entity from the entity menu in the Submarine Editor places the entity automatically

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#9727] opened 2022-08-19 17:31 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

**What actually happened:**
Entities are automatically placed after selecting them from the entity menu in the Submarine Editor.

**What I expected to happen:**
The entity should not be placed until the click after the entity is selected.

### Reproduction steps

1. Open the Submarine Editor.
2. Select any entity from the entity menu.
3. Close the entity menu.
4. Observe that the entity was automatically placed under the entity menu.

### Bug prevalence

Happens every time I play

### Version

Other

### -

Unstable 0.19.1.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-08-19 18:03
Duplicate of https://github.com/Regalis11/Barotrauma/issues/9725

**Closed by Regalis11** 2022-08-19 18:03 UTC
