### ISSUE TITLE
Purchasing lost shuttles causes the game to freeze/not responding

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#6175] opened 2021-06-25 12:40 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Game freezes after purchasing lost shuttles

**Steps To Reproduce**
Load this save: 
[17062021.zip](https://github.com/Regalis11/Barotrauma/files/6716127/17062021.zip)
You will hear the sound of shuttles docking and then the game will freeze with the music running in the background

This is after leaving an outpost. Two shuttles were lost in the previous mission, and I used the "Replace lost Shuttles" purchase

The game loads properly after editing the save to turn `purchasedlostshuttles="true"` into false
[17062021 FIXED.zip](https://github.com/Regalis11/Barotrauma/files/6716155/17062021.FIXED.zip)

I loaded the fixed save, purchased shuttles again, and this time it worked 

**Version**
0.14.6.0 stable

**Comment by Regalis11** [comment] 2021-07-08 07:54
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/cc8aca7e3d93bbb4b1195908ed3f16f7ba998239

**Comment by Rokvach** [comment] 2021-07-28 08:30
Tested, wasn't able to reproduce the issue, seems to be working correctly. Closing.

**Closed by Rokvach** 2021-07-28 08:30 UTC
Labels: Bug, Code
