### ISSUE TITLE
Game shutdown when leaving abandoned outpost

### ISSUE THREAD

**Issue by antlau2000** [Regalis11/Barotrauma#6422] opened 2021-08-13 17:53 UTC
I killed the bandit on the abandoned outpost and when I tried to go to the next location the game shutdown.

The crash report:
[crashreport (6).log](https://github.com/Regalis11/Barotrauma/files/6984314/crashreport.6.log)

Exception (from crash report):

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void .ctor(Barotrauma.Submarine)
Stack trace: 
   at Barotrauma.WreckAI..ctor(Submarine wreck) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Wreck\WreckAI.cs:line 20
   at Barotrauma.WreckAI.Create(Submarine wreck) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Wreck\WreckAI.cs:line 42
   at Barotrauma.Submarine.CreateWreckAI() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Submarine.cs:line 377
   at Barotrauma.Level.SpawnSubOnPath(String subName, ContentFile contentFile, SubmarineType type) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\Level.cs:line 3115
   at Barotrauma.Level.CreateWrecks() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\Level.cs:line 3366
   at Barotrauma.Level.Generate(Boolean mirror) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\Level.cs:line 1156
   at Barotrauma.Level.Generate(LevelData levelData, Boolean mirror, SubmarineInfo startOutpost, SubmarineInfo endOutpost) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\Level.cs:line 386
   at Barotrauma.GameSession.StartRound(LevelData levelData, Boolean mirrorLevel, SubmarineInfo startOutpost, SubmarineInfo endOutpost) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 398
   at Barotrauma.CampaignMode.<>c__DisplayClass26_0.<<SelectSummaryScreen>b__0>d.MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\CampaignMode.cs:line 265
--- End of stack trace from previous location where exception was thrown ---
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 962
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59

**Comment by Regalis11** [comment] 2021-08-16 07:33
Duplicate of https://github.com/Regalis11/Barotrauma/issues/6187

**Closed by Regalis11** 2021-08-16 07:33 UTC
Labels: Bug, Code, Crash
