### ISSUE TITLE
Fabricators don't stop looping the sound even after they're finished sometimes.

### ISSUE THREAD

**Issue by Crystalwarrior** [Regalis11/Barotrauma#60] opened 2017-12-02 17:41 UTC
This is especially annoying because the sound is 2d and it's heard across everywhere.

just... things fabricating. non-stop. even when you're outside the sub. absolutely ***maddening***

**Comment by Regalis11** [comment] 2017-12-02 20:52
I haven't been able to reproduce this specific bug (updating the position and volume of the sound seems to work fine and the sound stops when the fabricator finishes), but I've encountered similar bugs with other looping sounds. So I'm guessing this isn't specific to fabricators. It's most likely caused by audio sources getting messed up somehow - the item might have an incorrect source index and fail to stop/update the sound or some other audio source might be using the same index.

The entire sound playing logic (namely the SoundManager class) most likely needs some major refactoring to get rid of these bugs. The index-based logic in particular should be replaced with something less error-prone.

**Comment by Regalis11** [comment] 2018-04-17 11:57
I think this is fixed now by juan's audio rewrite (f50c37d)

**Closed by Regalis11** 2018-04-17 11:57 UTC
Labels: bug
