### ISSUE TITLE
[0.10.4]Missing item Alien Optical Module (event id 756, entity id 3668)

### ISSUE THREAD

**Issue by AngleOldPig** [Regalis11/Barotrauma#3446] opened 2020-07-31 17:10 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

In the server browser, when I click my friend's server, there is a dark "Vanilla 0.9" in the content packages box.

I join my friend's server and choose to be a fabricator mechanic.

When I click spectate and finish loading, I get kicked by server immediately.

The pop-up dialogue box says: 
- lost connection
- You have been kicked by server
- Reason: Missing item Alien Optical Module (event id 756, entity id 3668)

The only button is "OK". I click it, and I return the main menu。

**Steps To Reproduce**

I try to join my friend's game 5 times.

I repeat my operation as I write in Description each time.

And I get the same result each time.

**Version**

I am playing v0.10.4.0(ReleaseWindows, branch release, revision 20132d25fb)

I am using Windows 10.

**Additional information**

I am playing in Chinese(Sim) language.

And I am not good at English.

I try to translate my problem and hope I describe it well.

**Comment by mygamingaccount** [comment] 2020-07-31 22:58
Duplicate of #2382

**Comment by Regalis11** [comment] 2020-08-17 07:15
Duplicate of #2382

**Closed by Regalis11** 2020-08-17 07:15 UTC
