### ISSUE TITLE
[0.10.600] Dual Wielding Storage Container visually stacks on one hand

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3961] opened 2020-10-01 10:27 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When Dual Wielding Storage Container, they are both held on one hand visually. Should have one on both hands.

**Version**
0.10.600

**Comment by Regalis11** [comment] 2020-10-01 11:06
Could not reproduce.
![243sergdfg](https://user-images.githubusercontent.com/14351070/94801736-294e5a80-03ef-11eb-9150-6d2d620268cd.png)

Do you mean the incorrect render order (the container in the character's left hand being drawn in front of the character)?

**Comment by Kaillera** [comment] 2020-10-01 11:20
Huh.., there's a bug where both toolboxes are on one hand instead.

**Comment by Kaillera** [comment] 2020-10-01 11:22
Okay I found what it was:

1. Equip two storage containers.
2. Drop one of them.
3. Pick it back up.

The other storage container will float where the container would be when held by the character, but it wouldn't follow the character.

**Comment by Regalis11** [comment] 2020-10-04 13:21
I'm afraid I still couldn't repro this. Does it happen consistently? Did/does it happen in multiplayer, singleplayer or both?

**Comment by Kaillera** [comment] 2020-10-04 13:48
Was in MP.

**Comment by Kaillera** [comment] 2020-10-04 14:04
You know it might be due to the missing torso bug as well.

**Comment by Regalis11** [comment] 2020-10-07 09:48
Got another ticket about this with steps to repro (Regalis11/Barotrauma#4022), closing this one

**Closed by Regalis11** 2020-10-07 09:48 UTC
Labels: Bug, Code, Need more info
