### ISSUE TITLE
ClearTag action doesn't work

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#5542] opened 2021-04-18 14:51 UTC
**Description**
Using a cleartag action to clear a tag for events doesn't seem to be doing anything. Heres the setup:
![image](https://user-images.githubusercontent.com/59519434/115149804-0a9b7280-a066-11eb-95bf-673aac76208f.png)

Despite tag getting cleared, "tagged" player still receives the weapons experience:
![image](https://user-images.githubusercontent.com/59519434/115149841-29016e00-a066-11eb-8d60-6fffedd4a070.png)

**Steps To Reproduce**
-eventeditor
-tag a player, then remove the tag
-do action to the tag
-action happens to the tagged player, despite the tag getting cleared

**Version**
Unstable

**Additional information**
ClearTag is crucial for many custom events, please fix T_T

**Comment by 3e849f2e5c** [comment] 2021-04-18 17:11
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/55cd357b5694e86791e5b2becd17131655f6ce63

Happened because the tags are cached because some event actions retrieve them every game update and ClearTagAction wasn't clearing the cache, as a workaround you can clear the cache manually after using ClearTagAction by spawning an entity like an item which will trigger a cache clear.

**Comment by Udrakan** [comment] 2021-04-21 14:48
@3e849f2e5c I'm not sure about that workaround. I made event like on the pic and it still doesn't clear the tag:
![image](https://user-images.githubusercontent.com/59519434/115573812-5d249b00-a2c1-11eb-9c41-ede074e62b4c.png)

**Comment by 3e849f2e5c** [comment] 2021-04-22 19:46
Could not reproduce, the cache clear line gets hit properly when I tested with the same setup as in the picture
![](https://kosblue.com/e/kzjhkg.png)

[unnamed.zip](https://github.com/Regalis11/Barotrauma/files/6360862/unnamed.zip)

**Comment by Udrakan** [comment] 2021-04-22 20:20
I tried to use Crew criteria and start the event in a campaign environment, and still got this o_o
![image](https://user-images.githubusercontent.com/59519434/115779951-df43bb00-a3b8-11eb-9cf4-eb703c8e5c54.png)

**Comment by Udrakan** [comment] 2021-04-22 20:26
I think I found a lead! You used criteria:crew, I used criteria:player, so I tried each
![image](https://user-images.githubusercontent.com/59519434/115780695-c091f400-a3b9-11eb-947c-137216977aee.png)
And bingo, criteria:crew works as intended and criteria:player doesn't (it gives skillpoint to cleared tag!)

**Comment by Rokvach** [comment] 2021-04-30 08:53
Tested, working correctly, closing.

**Closed by Rokvach** 2021-04-30 08:53 UTC
Labels: Bug, Code
