### ISSUE TITLE
Game crashes regularly at the loading screen after selecting a mission

### ISSUE THREAD

**Issue by Unfairme** [Regalis11/Barotrauma#9699] opened 2022-08-12 16:45 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Every 2-4 missions the game crashes when it is in the loading screen. Mods(or the lack of) does not influence the crash. Location also does not influence the crash. I can play normally otherwise.

### Reproduction steps

The crash only happens at the loading screen after selecting a mission.
I only tested this at singleplayer.
It crashes also at full vanilla.

### Bug prevalence

Happens regularly

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 2022-08-12 16:08:49)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


116B6C514DB831BB68D5A8F96ACE87C4


Game version 0.18.15.1 (ReleaseWindows, branch hf, revision 91a05f31ff)
Graphics mode: 1366x768 (Fullscreen)
VSync ON
Language: English
Selected content packages: Vanilla, Meaningful Upgrades
Level seed: HullsbaneArgiope Linea
Loaded submarine: Typhon2 (3E432016DA07E4CC35F77E9BA5B88492)
Selected screen: Barotrauma.RoundSummaryScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.19043.0 64 bit
    GPU name: Intel(R) HD Graphics
    Display mode: {Width:1366 Height:768 Format:Color AspectRatio:1.7786459}
    GPU status: Normal


Exception: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.
 (SharpDX.SharpDXException)
Device removed reason: HRESULT = 0x887A0006
Target site: Void CheckError()
Stack trace: 
   at SharpDX.Result.CheckError()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 1017
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 511
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59


Last debug messages:
[2022-08-12 16:08:42] Level identifier: coldcavernsadvanced
[2022-08-12 16:08:19] Transitioning to HullsbaneArgiope Linea (current location: Hullsbane Habitation Outpost, selected location: Argiope Linea Habitation Outpost, leaving sub: Typhon2, at start: True, at end: False, transition type: LeaveLocation)
[2022-08-12 16:07:34] Generating an outpost for the start of the level... (Location: Hullsbane Habitation Outpost, level type: Outpost)
[2022-08-12 16:07:34] Level identifier: outpostlevel
[2022-08-12 15:33:55] Generating an outpost for the start of the level... (Location: Hullsbane Habitation Outpost, level type: Outpost)
[2022-08-12 15:33:55] Level identifier: outpostlevel
[2022-08-12 15:26:48] Unlocked mission "Getting rid of Mudraptors" in the location "Hullsbane Habitation Outpost".
[2022-08-12 15:26:46] Unlocked mission "Terminate a Swarm" in the location "Hullsbane Habitation Outpost".
[2022-08-12 15:26:44] Unlocked mission "Personnel Transport" in the location "Hullsbane Habitation Outpost".
[2022-08-12 15:25:18] Generating an outpost for the start of the level... (Location: Hullsbane Habitation Outpost, level type: Outpost)
[2022-08-12 15:25:18] Level identifier: outpostlevel
[2022-08-12 15:24:55] Transitioning to Hullsbane (current location: Asterius Linea, selected location: Hullsbane Habitation Outpost, leaving sub: Typhon2, at start: False, at end: True, transition type: ProgressToNextLocation)
[2022-08-12 14:50:06] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
[2022-08-12 14:49:29] Generating an outpost for the start of the level... (Location: Hullsbane Habitation Outpost, level type: LocationConnection)
[2022-08-12 14:49:25] Generating an outpost for the end of the level... (Location: Asterius Linea, level type: LocationConnection)
[2022-08-12 14:49:23] Level identifier: coldcavernsmaze
[2022-08-12 14:48:05] Attempting to open ALC device "OpenAL Soft on Headphones (2- High Definition Audio Device)"
[2022-08-12 14:48:00] Logged in as MASCAL (SteamID STEAM_1:1:99761292)
```

**Comment by Unfairme** [comment] 2022-08-13 05:18
I am using a workaround of saving and quitting to main menu then reloading everytime before I leave a station. This circumvents the crash.

**Comment by Regalis11** [comment] 2022-08-15 09:35
Duplicate of https://github.com/Regalis11/Barotrauma/issues/1833

**Closed by Regalis11** 2022-08-15 09:35 UTC
