### ISSUE TITLE
[0.15.16.0] Cargo Mission Priority Replacement

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#7551] opened 2021-11-29 22:25 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
So I have Explosive Cargo and Handle With Care mission available going one way. I am trying to get the most marks by selecting Handle With Care to fill up my shelves with those crates first, but if I select Explosive Cargo (which is at the top of the list), the cargo is prioritizing the crates with explosives. This means I'll make less if I try to get both missions.

**Steps To Reproduce**
1. Select Handle With Care first because it pays more
2. Select Explosive Cargo second

**Version**
~0.15.16.0

**Comment by Ek-Videogames** [comment] 2021-11-30 04:36
#7012 **#wontfix**

**Comment by Regalis11** [comment] 2021-11-30 08:48
@Ek-Videogames We didn't say we're not going to fix it, but it's a somewhat low-prio problem atm. And I wouldn't consider it a bug, but rather a missing feature .

**Comment by Regalis11** [comment] 2021-11-30 08:49
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7012

**Closed by Regalis11** 2021-11-30 08:48 UTC
