### ISSUE TITLE
Crash on applying graphics changes / Void OnItemLoadedProjSpecific()

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#7695] opened 2021-12-10 01:49 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I opened the settings, changed lighting resolution and I could see the effect underneath the menu, but when I clicked Apply the game crashed.

**Steps To Reproduce**
1. Play in co-op with mods?
2. Reduce lighting resolution to 0%?
3. Press Apply

**Version**
v0.15.13

**Additional information**
[crashreport (11).log](https://github.com/Regalis11/Barotrauma/files/7689526/crashreport.11.log)

**Comment by Regalis11** [comment] 2021-12-10 12:53
This seems to have been caused by an item with a ButtonTerminal component but no ItemContainer component, which there are none of in the vanilla game, so I'm pretty sure it's caused by one of the mods you have installed. Prevented this from crashing the game in https://github.com/Regalis11/Barotrauma-development/commit/1f8ee85aa104c8196280b436bffad2c071fc7174

**Comment by Krzeszny** [comment] 2021-12-10 12:59
> This seems to have been caused by an item with a ButtonTerminal component but no ItemContainer component, which there are none of in the vanilla game, so I'm pretty sure it's caused by one of the mods you have installed. Prevented this from crashing the game in [Regalis11/Barotrauma-development@1f8ee85](https://github.com/Regalis11/Barotrauma-development/commit/1f8ee85aa104c8196280b436bffad2c071fc7174)

The problem is there's no `ButtonTerminal` in my whole /Mods folder. Are you sure it's not the Apply button?

**Comment by Rokvach** [comment] 2022-02-08 12:37
There hasn't been any sightings of this happening in Unstable, seems to be working correctly. Closing.

**Closed by Rokvach** 2022-02-08 12:37 UTC
Labels: Bug, Code, Crash
