### ISSUE TITLE
Game locks up for 2-3 minutes when first opening the server browser.

### ISSUE THREAD

**Issue by Cogs16** [Regalis11/Barotrauma#8257] opened 2022-02-13 02:46 UTC
When I open the server browser after starting barotrauma the game freezes up for about 2-3 minutes. Windows will also sometimes declare the program as unresponsive.

OS Name	Microsoft Windows 10 Home
Version	10.0.19044 Build 19044
System Type	x64-based PC
Processor	Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz, 2801 Mhz, 4 Core(s), 8 Logical Processor(s)
1050 ti

**Comment by Regalis11** [comment] 2022-02-14 08:47
Duplicate of https://github.com/Regalis11/Barotrauma/issues/6511

**Closed by Regalis11** 2022-02-14 08:47 UTC
