### ISSUE TITLE
AI Captain will attempt to control the ship even when unassigned

### ISSUE THREAD

**Issue by Entelin** [Regalis11/Barotrauma#4698] opened 2021-01-11 00:44 UTC
- [ x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Campaign in singleplayer, piloting the ship from medic, the captain is not assigned to pilot. Occasionally the captain will flip autopilot back on despite me being at the helm. More importantly though whenever leaving the helm, the captain will override whatever you had set reverting to autopilot hold position.

While some classes behaving somewhat independently is fine (an engineer repairing a wall when set to repair mechanical), there are some troublesome repercussions regarding the captain. For example, during a ballast flora you want the tanks to empty, but since the captain will set autopilot, they will refill to half. So then you need to take care of the flora on the captain, if only to prevent him from doing that.

**Version**
Windows / Steam Stable

**Comment by itchyOwl** [comment] 2021-01-12 17:17
Can't repro.

The captain (or anyone) shouldn't override the steering if a player has set the autopilot destination. Neither should they take control of steering while a player is operating the nav terminal. Only if you leave the helm and the steering is set to manual should a bot take controls automatically and set the autopilot to "maintain position" to prevent the sub from crashing.

I'm not doubting that the issue won't happen, but I simply cannot reproduce it. So this one needs more testing and the steps: _when_ does it happen?

**Comment by Entelin** [comment] 2021-01-13 02:44
I only observed the autopilot switch getting flipped a couple times while I was at the helm with it off, so I don't know how to reproduce that one. However the main part of what I was talking about you are describing as the current behavior. Specifically I would expect that if I make a manual input in the navcon the ai would not switch to autopilot if it is not assigned to do anything. Which makes sense considering the ai has a command for hold position, which otherwise would be redundant since simply canceling an existing move command currently will cause the captain to hold position anyway.

For example, one might want to pin the ship against the ceiling with manual controls as is ideal when dealing with a ballast infestation, or simply letting the sub drift forwards briefly in an area you are reasonably sure is open. In those cases the capitan, even if unassigned to do anything, will flip the autopilot on causing the ballast tanks to level and the ship to come to a stop. It's extremely annoying, and often dangerous. Another example is if you are being chased and simply want the sub to keep going in a direction while jumping on the guns quick. Of course none of this is a problem if you are playing on the Capitan, but there can be a ton of crafting and growing that needs to be done, and if you have the Capitan autopiloting through an area, it's not ideal do actually be doing that on him. In my case I was using the medic for most random things, which also means his gunnery skill was much higher than the captains, and so on.

You CAN use the autopilot's hold location to pin against the ceiling by having it target a spot into the rock, but you can only do that if you are already there or near enough to be able to click on an appropriate destination. Particularly on a small ship the ballast flora is extremely fast and deadly, so often I would rather just slam my ship against an unseen ceiling and get to work on killing it rather than navigating to an appropriate spot. Ultimately I built a circuit in my ship to force this behavior, but from a stock perspective this ai behavior is really troublesome.

**Comment by itchyOwl** [comment] 2021-01-13 12:18
So the main issue is that if you are not controlling the captain and you leave the helm with manual steering deliberately enabled, a captain (bot) will take the controls? I don't think this is a strong enough argument to change the existing behavior, because it can prevent accidental crashes. In such edge cases, if you'd want the captain to do nothing, just give it another order (hold position should work). You could also control the captain manually. None of the other bots should automatically take the helm.

Any thoughts on this, @ezjamsen ? @Regalis11 ?

**Comment by Entelin** [comment] 2021-01-13 18:10
Just to be clear, I'm specifically talking about a captain which has no orders to do anything, should not do anything. A Capitan ordered to hold position, advance, or go back should do so, but if the player clicks on that order to temporarily deactivate it, or does not give the captain an order, then it should not put the ship in hold position. The current behavior effectively mandates the player play on the captain for any situation where you want the ship to keep a manual control input. Changing that behavior gives the players flexibility that they don't currently have.

**Comment by itchyOwl** [comment] 2021-04-15 10:12
Closing this as there's no issue here, and I don't think we should change the current behavior.

**Closed by itchyOwl** 2021-04-15 10:12 UTC
Labels: Bug, Code, Design, Medium Prio
