### ISSUE TITLE
Visual oddity with shotgun and scrap cannon when shooting at a door

### ISSUE THREAD

**Issue by PokkeTigrex** [Regalis11/Barotrauma#10548] opened 2022-11-25 19:40 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

For some reason in the faction branch, shooting a shotgun or scrap cannon at a door will not render most but one of the pellets, even at max particle count in settings. How one faces a door seems to affect it too, where shooting at a door facing left seems to consistently do it, while at the right, its somewhat inconsistent on how many pellets are visually lost. I was able to confirm that its just visual, all pellets still are technically there, and will render properly when hitting a body, or walls.

![Barotrauma_OeZAIA7MoT](https://user-images.githubusercontent.com/85914375/204048402-a326d95f-6680-4534-aa92-32b4cfba42b0.png)

### Reproduction steps

Shoot shotguns/scrap cannon at a door, more easier to see facing left for some reason.

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-11-28 14:10
I unfortunately couldn't find a way to reproduce this. Tested in both single player and multiplayer. This could potentially happen if there's already the maximum amount of particles present, and this build had the issue of water-reactant items constantly emitting particles when in a submerged container, so I wonder if that could've been the cause.

**Comment by Regalis11** [comment] 2023-01-13 12:50
No known steps to repro, closing

**Closed by Regalis11** 2023-01-13 12:50 UTC
Labels: Bug, Need more info, Code
