### ISSUE TITLE
The bug with the spawn of loot from the coalition

### ISSUE THREAD

**Issue by Frizit** [Regalis11/Barotrauma#11549] opened 2023-03-15 16:51 UTC
Of course, I'm not a developer, but I believe that enemy coalition submarines should at least have spacesuits. (I was playing a campaign for the separatists and noticed that there are no spacesuits on the coalition ships. and on 1 of them (which is an ambush boat) there was not a single thing (except those that appear from the crew))

**Comment by Regalis11** [comment] 2023-03-15 17:08
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11423

**Closed by Regalis11** 2023-03-15 17:08 UTC
