### ISSUE TITLE
The character editor doesn't allow to replace old characters. Add an option to do this in the editor.

### ISSUE THREAD

**Issue by etet2** [Regalis11/Barotrauma#1375] opened 2019-03-30 19:24 UTC
[crashreport (45).log](https://github.com/Regalis11/Barotrauma/files/3025860/crashreport.45.log)

**Comment by etet2** [comment] 2019-03-30 19:27
changed the title: after investigating it still outputs to content/characters which was sopoused to be fixed #1330 but does not seem to create main character file at all

**Comment by itchyOwl** [comment] 2019-04-12 07:25
Cannot reproduce this. I just created a "Hammerheed" and everything worked alright, as you see in the pictures below:
![Hammerheed1](https://user-images.githubusercontent.com/5370738/56019234-cbb2e380-5d0c-11e9-8eea-fcfe62fff6d5.png)
![Hammerheed2](https://user-images.githubusercontent.com/5370738/56019250-d2415b00-5d0c-11e9-8567-f3fc7cec07bd.png)
![Hammerheed3](https://user-images.githubusercontent.com/5370738/56019252-d2d9f180-5d0c-11e9-8578-073f13b611d6.png)

So, how did you encounter the issue? Looking at the crash report, it's evident that the character path in the content package config file is wrong ([30/03/2019 19:16:57] Error in content package "Barotrauma Erect" - file "Content/Characters/Gnome/Gnome.xml" not found.) But I can't figure out why is it so, because the wizard should now use the path defined in the text field when you first open it. Are you sure that you defined the path there and didn't use the default path which is in the Content folder (need to change that btw).

**Comment by itchyOwl** [comment] 2019-04-12 08:23
Ok, it seems that if the game fails to load the character config file and if you then try to create a new character with the same name, it will crash. Need to look into it. But it should work if you don't have an incorrect path when you start the game. If you do, it should show an error in the console when you start the game.

**Comment by itchyOwl** [comment] 2019-04-12 08:53
Managed to reproduce it. Seems to be related to old data not being cleared when creating multiple characters during the same session.

**Comment by itchyOwl** [comment] 2019-04-12 11:46
Should be fixed in the next patch. Was not related to the old data. The default folder was used just because there already was an existing character in the content package, but it was invalid. Now it should properly exit the wizard and tell that there is an existing character with the same name. Currently you have to remove it manually from the content package file. I'll add an option to replace the old file at some point. So let's keep this issue open for now.

**Closed** 2019-04-26 08:31 UTC
Labels: Code, Feature request
