### ISSUE TITLE
Small issues in server browser

### ISSUE THREAD

**Issue by wackypeanut** [Regalis11/Barotrauma#5087] opened 2021-02-16 16:07 UTC
I have searched the issue tracker to check if the issue has already been reported.

**Description**
1) Hide Incompatible checkbox has no functionality (does not hide incompatible servers)
2) Checkbox "modded" seems to work as "Modded-only", but if I want to browse only unmodded servers (which is more likely) I can't.
3) Hide offensive server names does not function too well... I tried adding my own words but seems if the word is not reproduced exactly (no extra letters) I can't avoid it. I would like to be able to filter out servers with Russian and Chinese characters, which I added to my list, but I was unable to get any results.

**Comment by Bertaz** [comment] 2021-02-17 11:04
2. is the same as #3652
3. Every word you put inside forbiddenwordlist gets filtered, even if it's inside another longer word. To filter all the servers with Russian and Chinese characters you would have to add every single character, separated by a newline, in the forbiddenwordlist.

**Comment by Regalis11** [comment] 2021-02-22 16:51
Fixed the 1st issue in https://github.com/Regalis11/Barotrauma-development/commit/f5382d9a1944b1a32b524153c5b4f3acba0bfef3.

The second is a duplicate of #3652 and the 3rd is not really a bug, and can be worked around by adding Cyrillic and Chinese symbols to the forbidden word list. The latter is of course difficult to do due to the sheer number of Chinese symbols, but could probably be done by adding some subset of the most common symbols.

**Comment by Rokvach** [comment] 2021-02-23 11:17
Tested, no issues. Closing.

**Closed by Rokvach** 2021-02-23 11:17 UTC
Labels: Bug, Code
