### ISSUE TITLE
[SP Campaign] Fresh new quests and infinite crates upon saving+loading in a station

### ISSUE THREAD

**Issue by Thirty-Percent** [Regalis11/Barotrauma#3955] opened 2020-09-30 14:56 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
- [x] In single player campaign, when docked at a station, saving and loading will remove any and all afflictions on crew.

- [ ] Additionally, quest NPCs will have fresh new quests if you had already accepted them before saving; using this, one is able to have one of each type of quest for each connected location, provided they repeat the process enough times.

- [ ] Also, not sure if that's intended: purchased items/crew/upgrades/subs will be available upon loading back, as if you had left the station. This may not seem like much but it means you can stock up on a lot of crates for storage by buying 1 cheap item, save+load, notice the new crate containing your item, rinse&repeat. I guess you could also do this by travelling without a mission and then redocking directly though.

**Steps To Reproduce**
Get an affliction on a crewmember, talk to the NPCs to get quests until none are left, buy any item, save and exit, load back

**Version**
0.10.5.1 (Windows)

**Additional information**
Sometimes quest givers will have their quest speech and then the quest description popup won't show up; this happens when that specific quest type for that specific location has already been accepted, therefore will happen everytime once all quest types for all locations have been accepted.

**Comment by alkaid7205** [comment] 2020-09-30 16:30
duplication of #3926

**Comment by Thirty-Percent** [comment] 2020-09-30 17:05
Oh, my bad on the duplicate, didn't search right I guess.
Other than that I doubt ~infinite storage and quests is intentional?

**Comment by Regalis11** [comment] 2021-11-29 19:14
Closing as a duplicate of https://github.com/regalis11/barotrauma/issues/3388

**Closed by Regalis11** 2021-11-29 19:14 UTC
Labels: Bug, Code, Medium Prio
