### ISSUE TITLE
Barotrauma electrical component selection crash

### ISSUE THREAD

**Issue by ME-13** [Regalis11/Barotrauma#9635] opened 2022-07-24 10:39 UTC
### Disclaimers

- [ ] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Hi
this bug happend several times while creating a sub (submarine editor):
while a electric componet is selected, clicking on an other component will crash my game. i already lost several hours of work due to this bug. is something wrong with the sub i´m building? i try to keep the ship vanilla, so the mods are mostly vanilla part-assembleys, allthou i´m not totaly shure abbout that.

anyways, here is the crash report:
thanks for looking into it.

Barotrauma Client crash report (generated on 24.07.2022 11:54:01)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

A3E1BD9914304826B1774DE813786E1D

Game version 0.18.15.0 (ReleaseWindows, branch release, revision a7b22109e9)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla, Torpedo CG - RC 1.0, Torpedo EMP - RC 1.0, Torpedo EMP 1.0, Torpedo FG - RC 1.0, Torpedo FG 1.0, Torpedo HE - RC 1.0, Torpedo HE 1.0, Torpedo parts, Terror Fish 1.1.3 fullguns 14, Terror Fish 1.1.3 fullguns, RailgunPocket, MixPocket, GunMarine 4.5, DepthchargePocket, BombControll, Bomb-Drone, Bomb, Freighter813, Drones, 1,2,bothSWITCH, DepthDrone, Laserdrone, CargoDrone, PvP Mine, Smoker [Vanilla], Toilet [Vanilla], Mining Laser [Vanilla], Sonar Weapon Aiming example, Countdown timer | Отсчитывающий таймер, Barotronics - Clocks and Timers, Crazy Ivan's FizzBuzz, 3-turret aimpoint, Europa Clock (outdated), MineTorpedo, Shower [Vanilla], Single/Dual Coilgun System with Enemy Detect + Auto Lights, clocks, 3TurretAimpoint, singel-dual coilgun, shower, Smoker, testmarine, turretRestriction, turretRestrictin, 3turrettimeswitch, Periscope Submarine Control, Periscope Controlled Sub, PeriscopeSubControll, periscopeSubControll2, Adaptive Overload Buffer, Fire Protection System, Advanced Countdown Timer
Level seed: no level loaded
Loaded submarine: Drones (4C63F73C6FB9D2C76FF45BD799C7BCF2)
Selected screen: Barotrauma.SubEditorScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce GTX 1660 SUPER
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,7777778}
    GPU status: Normal

Exception: Type provided must be an Enum. (Parameter 'enumType') (System.ArgumentException)
Target site: System.RuntimeType ValidateRuntimeType(System.Type)
Stack trace: 
   at System.Enum.ValidateRuntimeType(Type enumType)
   at System.Enum.TryParse(Type enumType, String value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at Barotrauma.SerializableEntityEditor.MultiSetProperties(SerializableProperty property, Object parentObject, Object value) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Serialization\SerializableEntityEditor.cs:line 1451
   at Barotrauma.SerializableEntityEditor.SetPropertyValue(SerializableProperty property, Object entity, Object value) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Serialization\SerializableEntityEditor.cs:line 1391
   at Barotrauma.SerializableEntityEditor.<>c__DisplayClass29_0.<CreateStringField>g__OnApply|3(GUITextBox textBox) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Serialization\SerializableEntityEditor.cs:line 707
   at Barotrauma.SerializableEntityEditor.<>c__DisplayClass29_0.<CreateStringField>b__1(GUITextBox textBox, Keys keys) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Serialization\SerializableEntityEditor.cs:line 691
   at Barotrauma.GUITextBox.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBox.cs:line 477
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1229
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 898
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59

Last debug messages:
[24.07.2022 11:14:42] Creating hulls between docking ports failed. Could not find a hull next to the docking port.
[24.07.2022 11:14:42] Creating hulls between docking ports failed. Could not find a hull next to the docking port.
[24.07.2022 10:27:31] Attempting to open ALC device "OpenAL Soft on Lautsprecher (High Definition Audio Device)"
[24.07.2022 10:27:27] Logged in as Darth Herasy (SteamID STEAM_1:0:24272097)

[crashreport (6).log](https://github.com/Regalis11/Barotrauma/files/9175596/crashreport.6.log)
[crashreport (7).log](https://github.com/Regalis11/Barotrauma/files/9175597/crashreport.7.log)
[crashreport (8).log](https://github.com/Regalis11/Barotrauma/files/9175598/crashreport.8.log)
[crashreport (9).log](https://github.com/Regalis11/Barotrauma/files/9175599/crashreport.9.log)
[crashreport (10).log](https://github.com/Regalis11/Barotrauma/files/9175600/crashreport.10.log)
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/9175601/crashreport.2.log)
[crashreport (3).log](https://github.com/Regalis11/Barotrauma/files/9175602/crashreport.3.log)
[crashreport (4).log](https://github.com/Regalis11/Barotrauma/files/9175603/crashreport.4.log)
[crashreport (5).log](https://github.com/Regalis11/Barotrauma/files/9175604/crashreport.5.log)

### Reproduction steps

1. open submarine editor
2. load sub  worktitle "drones"
3. select a electrical component like wifi, signal, memory (where the ones where it happend; don´t know if it is all or just these)
4. change some of it´s values like chanel, output, value
5. DON´T press enter or click anywhere
6. just click directly on the next wifi component where you want to set your channel (i guess kind of without saving it)
7. crash

[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/9175584/crashreport.2.log)
[crashreport (3).log](https://github.com/Regalis11/Barotrauma/files/9175586/crashreport.3.log)
[crashreport (4).log](https://github.com/Regalis11/Barotrauma/files/9175587/crashreport.4.log)
[crashreport (5).log](https://github.com/Regalis11/Barotrauma/files/9175588/crashreport.5.log)
[crashreport (6).log](https://github.com/Regalis11/Barotrauma/files/9175589/crashreport.6.log)
[crashreport (7).log](https://github.com/Regalis11/Barotrauma/files/9175590/crashreport.7.log)
[crashreport (8).log](https://github.com/Regalis11/Barotrauma/files/9175591/crashreport.8.log)
[crashreport (9).log](https://github.com/Regalis11/Barotrauma/files/9175592/crashreport.9.log)
[crashreport (10).log](https://github.com/Regalis11/Barotrauma/files/9175593/crashreport.10.log)

### Bug prevalence

Happens regularly

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 24.07.2022 11:54:01)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


A3E1BD9914304826B1774DE813786E1D


Game version 0.18.15.0 (ReleaseWindows, branch release, revision a7b22109e9)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla, Torpedo CG - RC 1.0, Torpedo EMP - RC 1.0, Torpedo EMP 1.0, Torpedo FG - RC 1.0, Torpedo FG 1.0, Torpedo HE - RC 1.0, Torpedo HE 1.0, Torpedo parts, Terror Fish 1.1.3 fullguns 14, Terror Fish 1.1.3 fullguns, RailgunPocket, MixPocket, GunMarine 4.5, DepthchargePocket, BombControll, Bomb-Drone, Bomb, Freighter813, Drones, 1,2,bothSWITCH, DepthDrone, Laserdrone, CargoDrone, PvP Mine, Smoker [Vanilla], Toilet [Vanilla], Mining Laser [Vanilla], Sonar Weapon Aiming example, Countdown timer | Отсчитывающий таймер, Barotronics - Clocks and Timers, Crazy Ivan's FizzBuzz, 3-turret aimpoint, Europa Clock (outdated), MineTorpedo, Shower [Vanilla], Single/Dual Coilgun System with Enemy Detect + Auto Lights, clocks, 3TurretAimpoint, singel-dual coilgun, shower, Smoker, testmarine, turretRestriction, turretRestrictin, 3turrettimeswitch, Periscope Submarine Control, Periscope Controlled Sub, PeriscopeSubControll, periscopeSubControll2, Adaptive Overload Buffer, Fire Protection System, Advanced Countdown Timer
Level seed: no level loaded
Loaded submarine: Drones (4C63F73C6FB9D2C76FF45BD799C7BCF2)
Selected screen: Barotrauma.SubEditorScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce GTX 1660 SUPER
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,7777778}
    GPU status: Normal


Exception: Type provided must be an Enum. (Parameter 'enumType') (System.ArgumentException)
Target site: System.RuntimeType ValidateRuntimeType(System.Type)
Stack trace: 
   at System.Enum.ValidateRuntimeType(Type enumType)
   at System.Enum.TryParse(Type enumType, String value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at Barotrauma.SerializableEntityEditor.MultiSetProperties(SerializableProperty property, Object parentObject, Object value) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Serialization\SerializableEntityEditor.cs:line 1451
   at Barotrauma.SerializableEntityEditor.SetPropertyValue(SerializableProperty property, Object entity, Object value) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Serialization\SerializableEntityEditor.cs:line 1391
   at Barotrauma.SerializableEntityEditor.<>c__DisplayClass29_0.<CreateStringField>g__OnApply|3(GUITextBox textBox) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Serialization\SerializableEntityEditor.cs:line 707
   at Barotrauma.SerializableEntityEditor.<>c__DisplayClass29_0.<CreateStringField>b__1(GUITextBox textBox, Keys keys) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Serialization\SerializableEntityEditor.cs:line 691
   at Barotrauma.GUITextBox.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBox.cs:line 477
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1229
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 898
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59


Last debug messages:
[24.07.2022 11:14:42] Creating hulls between docking ports failed. Could not find a hull next to the docking port.
[24.07.2022 11:14:42] Creating hulls between docking ports failed. Could not find a hull next to the docking port.
[24.07.2022 10:27:31] Attempting to open ALC device "OpenAL Soft on Lautsprecher (High Definition Audio Device)"
[24.07.2022 10:27:27] Logged in as Darth Herasy (SteamID STEAM_1:0:24272097)
```

**Comment by MaaiG** [comment] 2022-07-24 17:18
> is something wrong with the sub i´m building?

No! With this all right. 😉

>  i already lost several hours of work due to this bug. 

Yea! Quite a lot of victims 😉 [including me](https://github.com/Regalis11/Barotrauma/issues/9629)!

**Comment by pakvg85** [comment] 2022-07-24 17:59
> i already lost several hours of work due to this bug
Autosaves should be created each 5 minutes by default.
This issue is a duplicate of #9629 and will be fixed in the next bugfix, I believe.

**Comment by NilanthAnimosus** [comment] 2022-07-28 11:18
Closing as a Duplicate of #9512

This has actually been fixed in the current unstable, and is related to the issue listed above.

If you want you could swap to the unstable - make a copy of the folder (running the exe directly is fine and steam will still recognize it) and switch back to stable using one for sub editing and the other for general play (copying over the local mod's of your submarine files) as there should be no issues backporting submarines from 0.19.0.0 to 0.18.15.0.

Alternatively in the game folder (right click barotrauma in Steam -> Manage -> browse local files) you can open up the config_player.xml and change these values (you can search them with any text editor, make a copy first if your unsure about editing them directly):

```
maxautosaves="8"
autosaveintervalseconds="300"
```

finally in game when loading a submarine file the option to load an autosave is located at the top:
![image](https://user-images.githubusercontent.com/29177976/181492193-451de05f-925b-40cc-99e3-bbbdf53d73ba.png)

so you could say, set it to every 1 minute with 20 saves stored or something if that helps.

**Closed by NilanthAnimosus** 2022-07-28 11:18 UTC
