### ISSUE TITLE
[1.0] Trying to enter a clown crate when another player is inside the clown crate causes weird controller behaviour 

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11419] opened 2023-03-01 23:21 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Trying to enter a clown crate which has another player inside will cause the character's controls to experience odd behaviour. The camera will no longer follow the mouse's movement, the player will no longer be able to turn around or crouch, and the "End Round" button will vanish from the top right of the screen.

![image](https://user-images.githubusercontent.com/105495756/222281763-2ea692e4-5ca7-437e-a177-6167b7d41ad4.png)
_Figure 1. Player standing before the clown crate._

![image](https://user-images.githubusercontent.com/105495756/222281792-aba31979-0985-4e05-aab9-18022d14c57c.png)
_Figure 2. Player standing after trying to enter the clown crate (observe the missing "End Round" button from the top right)._

![image](https://user-images.githubusercontent.com/105495756/222281828-d4e9258d-9a72-4fa3-aa20-15f83b0fd25a.png)
_Figure 3. Camera panned towards the current position of the mouse (in the bottom left of the screen)._

![image](https://user-images.githubusercontent.com/105495756/222281838-1a0b1fe2-47cb-4675-9c6b-0dccd3ee6bbe.png)
_Figure 4. Camera being zoomed in near the character model despite mouse being on the other side of the screen._

### Bug prevalence

Happens every time I play

### Version

Other

### -

1.0.4.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-03-03 16:06
Seems to happen because the character selects the item (the same way you select a device, which disables the camera movement etc). Can be reproduce in single player too by putting a character in the box, disabling crew ai, and switching to another character.

**Comment by Regalis11** [comment] 2023-03-03 16:09
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/344a9b0bab443bb8efc2270c103edb66a99b6173

**Comment by Tsunder** [comment] 2023-03-03 18:36
how does the fix interact with the feature(?) of clicking a periscope that's in use by bots to make the bots leave the periscope?

**Comment by Regalis11** [comment] 2023-03-04 13:25
I wasn't aware that was a thing. And looking at how it works (= you get the similar weird behavior when you select one), I think it's probably an unintentional feature - but useful regardless, so I think I'll make that fix only apply to clown crates.

**Comment by Regalis11** [comment] 2023-03-06 09:20
Made the change only apply to clown crates in https://github.com/Regalis11/Barotrauma-development/commit/9926281c22d46679d3dbc7088cda0e98da49bdef

**Comment by Jasontti** [comment] 2023-05-26 08:54
Tested. Clown crate works now.
Occupied turrets have same behaviour with fading UI elements, camera follows mouse normally. Happens with host and client.

**Closed** 2023-05-26 13:40 UTC
Labels: Bug, Code
