### ISSUE TITLE
Secure Container cant be opened after mission

### ISSUE THREAD

**Issue by Zetabite** [Regalis11/Barotrauma#8611] opened 2022-03-24 23:17 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Secure containers can be opened during a round, no matter where the id card with the clearance level is. My character carried the ID card from a wrecked ship, which was needed to access the secure container on the wrecked ship, during that I placed my own id in the secure container. I was able to open the container of my ship for the duration of the round. Once I entered the harbour, i was unable to access our ships container.

**Steps To Reproduce**
1. Play Round
2. Place ID with clearance level for that container into container
3. Still having access to container
4. Enter Harbour
5. Loose access to container

**Version**
0.16.7.0 (Linux)

**Comment by Zetabite** [comment] 2022-03-27 07:00
Access is regained once going back into a round

**Comment by Regalis11** [comment] 2022-04-04 13:17
I'm afraid I could not reproduce this: after leaving the original ID card behind, I can no longer access the secure cabinets in the sub. Tested on a vanilla Dugong and the vanilla "Wreck1". I wonder if this could have something to do with the submarine you're using, or more specifically, the way the ID restrictions have been set up? Which sub and wreck this happened in?

**Comment by Zetabite** [comment] 2022-04-04 20:49
Tested on Barsuk, the wreck was a Krastull iirc. I also didnt use the "shipwreck id" but the normal "id card" iirc. Been about two weeks, so i hardly remember the wreck and ids used.

**Comment by Regalis11** [comment] 2022-05-02 08:52
No known steps to repro, closing

**Closed by Regalis11** 2022-05-02 08:52 UTC
Labels: Bug, Need more info, Code
