### ISSUE TITLE
Strange geometry in "Shell A Cap Horizontal Square"

### ISSUE THREAD

**Issue by Cherman0** [Regalis11/Barotrauma#9286] opened 2022-06-08 04:08 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

At exactly 0.6 scale, the "Shell A Cap Horizontal Square" has one map unit of unusual geometry on the left-hand side when mirrored on the X-Axis. It appears that at this scale, a pixel of the end of the cap is not reflected and remains in its original position.

### Reproduction steps

1. Enter submarine editor
2. Place a Shell A Cap Horizontal Square
3. Set its scale to 0.6
4. Reflect it on the X-Axis
5. The pixel line is visible on the left. This happens consistently, but only at this exact scale in my observations (floating point precision issue?)
![20220607235435_1](https://user-images.githubusercontent.com/99766513/172529495-ea7b1546-ba66-49db-9a53-acfc08eeaaae.jpg)

### Bug prevalence

Happens every time I play

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-06-08 05:54
Most likely related to https://github.com/Regalis11/Barotrauma/issues/8922

**Comment by Cherman0** [comment] 2022-06-08 07:14
Seems pretty likely, since that also is at .6 scale and is a pixel of unreflected texture. Seems that at exactly 0.6 scale objects whos textures go all the way to the edge of their bounding box have an issue being reflected. My solution in designing a sub was to just use 0.601 scale, since its basically indistinguishable but doesn't have this issue.

**Comment by Regalis11** [comment] 2022-06-08 07:51
Seemed to have been caused by the same bug as https://github.com/regalis11/barotrauma/issues/8922, should be fixed in Regalis11/Barotrauma#8922

**Closed by Regalis11** 2022-06-08 07:51 UTC
Labels: Bug, Code, Low prio
