### ISSUE TITLE
Coilgun consumes ammo at 2x expected rate

### ISSUE THREAD

**Issue by Doubleumc** [Regalis11/Barotrauma#2226] opened 2020-02-09 00:19 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
A coilgun ammunition box is supposed to fire 200 shots, both in it's description and in the config (100 condition, 0.5 per shot). However it only fires half that amount, 100 shots, before running dry.

This is consistent for all ammo types and all starting durabilities.

**Steps To Reproduce**
1. create a functional coilgun setup (periscope, supercapacitor, loader, coilgun)
1. insert a coilgun ammunition box into the loader
   1. (optional: set box to 1.0 condition for quicker test)
1. fire the coilgun and count the shots

The result will be half the expected number of shots, only 100 for a full box (or 1 shot at 1.0 condition) instead of 200 (2).

**Version**
Barotrauma v0.9.6.0
Windows 10

**Comment by EdusFF** [comment] 2020-04-29 09:31
Tested and wasn't able to reproduce, instead 1.0 condition allowed the coilgun to shoot twice as intended

**Comment by Rokvach** [comment] 2020-04-29 09:39
This was already fixed in another ticket couple months back, closing.

**Closed by Rokvach** 2020-04-29 09:39 UTC
Labels: Bug, Code
