### ISSUE TITLE
item grid snap offset wall submarine editor in game

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#12816] opened 2023-10-15 05:04 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

item placement grid snap in-game is offset from editor grid snap

sub editor placed items:
![image](https://github.com/Regalis11/Barotrauma/assets/5103517/8e6c2361-9863-4748-84c5-b2d25ca32a3f)

in-game placed items are about [8,8] offset (placed 2 items)
![image](https://github.com/Regalis11/Barotrauma/assets/5103517/ce12b8c8-ff84-4f80-bed5-ef8518e070a4)

### Reproduction steps

1. place items on wall in editor
2. place items on wall in game

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-10-15 14:36
Duplicate of https://github.com/Regalis11/Barotrauma/issues/12815 and https://github.com/Regalis11/Barotrauma/issues/12257

**Closed by Regalis11** 2023-10-15 14:36 UTC
