### ISSUE TITLE
outpost doctor UI breaks in every possible way

### ISSUE THREAD

**Issue by GenericGoose** [Regalis11/Barotrauma#8720] opened 2022-04-04 21:58 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
at random:
gives no response from the server error when selecting a guy
doesn't add the wound i clicked on to checkout
heal button does nothing
option to add a wound to checkout is greyed out
clicking a guy says please wait then doesnt show his wounds and selecting others doesnt do anything until you close the menu

every button press has about a 25% chance of breaking the UI, forcing you  to quit out of it

**Steps To Reproduce**
use the outpost medic

**Version**
0.16 stable

**Comment by cshingle** [comment] 2022-04-05 00:15
This is partly a duplicate of #8628, but my UI didn't fully lock up.

**Comment by Regalis11** [comment] 2022-06-06 18:19
No known steps to repro, closing

**Closed by Regalis11** 2022-06-06 18:19 UTC
Labels: Bug, Need more info, Code, Networking
