### ISSUE TITLE
Ping indicator in server browser rarely reflects the actual ingame ping

### ISSUE THREAD

**Issue by cl0ck-byte** [Regalis11/Barotrauma#13161] opened 2023-12-14 15:40 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

As the title says, ping indicator in server browser rarely reflects the actual ingame ping - very often it's underestimated by at least 100-300ms despite server browser stating for example 70ms ping.

### Reproduction steps

1. Open up Server Browser
2. Search up for any server, preferably one with supposed 70ms ping
3. Join the server and spectate current level
4. Depending on host, actual ping can be underestimated by at least 100-300ms

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens outside single player or multiplayer game modes (e.g. game launches on startup, something broken in the main menu)

### Version

v1.2.6.0 (Winter Update)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-12-14 16:21
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3985

There is unfortunately not much we can do about this due to how SteamP2P networking works. :/ They use intermediary servers to relay information between the clients and the server to bypass the need for port forwarding, which in some cases can result in a larger-than-expect ping when the data gets passed through some external server. There's no way in the Steam API to determine how the connection happens to get relayed, nor a way to determine the ping reliably beforehand.

**Closed by Regalis11** 2023-12-14 16:21 UTC
