### ISSUE TITLE
Azimuth and Kastrull has reactors with 10000 max output

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#5046] opened 2021-02-12 21:03 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Azimuth and Kastrull has reactors with 10000 max output.

**Version**
~0.12.0.2

**Comment by ignis05** [comment] 2021-02-13 12:05
Duplicate of #4871 ?

**Closed** 2021-02-13 14:08 UTC
