### ISSUE TITLE
[Factions] Events/Missions spawning on route to Anomaly 

### ISSUE THREAD

**Issue by StruggleDuck** [Regalis11/Barotrauma#11289] opened 2023-02-20 06:17 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While in the final area before the end ruins, a beacon station spawned in (which did not display on the mission map) as well as a notification that separatists had taken control of the area. 
![image-4](https://user-images.githubusercontent.com/92034548/220025748-f850b5d3-9907-4cd1-a9be-49bb65777d43.png)
![image-9](https://user-images.githubusercontent.com/92034548/220025757-c5c3c389-1fd9-46d6-9e3c-2e51dd3d889e.png)

### Reproduction steps

1. Travel to Anomaly
2. There is a chance that events/beacon stations can spawn

### Bug prevalence

Just once

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by StruggleDuck** [comment] 2023-02-20 06:19
Also worth noting is that nothing happened following the notification that separatists had taken control of the area. The only other time I got that notification, nothing happened as well. Not sure if this is intentional or is another seperate issue.

**Comment by Regalis11** [comment] 2023-02-20 09:11
> While in the final area before the end ruins, a beacon station spawned in

This is not a bug: that beacon station always spawns in this level.

There seems to be something wrong with that separatist attack though: they shouldn't ambush you unless you're near a separatist-controlled outpost.

**Comment by Regalis11** [comment] 2023-02-20 11:25
Looks like the ambush missions were allowed to trigger in any level, fixed in https://github.com/Regalis11/Barotrauma-development/commit/da2607a17bbdcd3e5713042e49c7b6085a287b80

**Closed** 2023-02-20 13:48 UTC
Labels: Bug, Code
