### ISSUE TITLE
Server process crashing when trying to host with SteamP2P

### ISSUE THREAD

**Issue by SenhorPatolino** [Regalis11/Barotrauma#2365] opened 2020-02-25 17:37 UTC
- [ X ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
 A similar report to Athenades report, except now in Unstable it says "server process crashed". It also mention of creating a server crash report but it is not on my folder.

**Steps To Reproduce**
Not sure how to reproduce it on people that are able to host, but i just simply try to host a server through menu and after 5-10 seconds it just says server process crashed

**Version**
0.9.6.0 just says "could not connect to server" and in 0.9.7.0 it says "server process crashed" and after this "could not connect to server".

**Additional information**
Im pretty sure its the same error that is making impossible to host in 0.9.6.0, but now it says the reason why.

**Comment by Regalis11** [comment] 2020-02-26 18:33
Duplicate of #1939

**Closed by Regalis11** 2020-02-26 18:33 UTC
Labels: Bug, Code, Need more info, Networking
