### ISSUE TITLE
Game broken because of cargo box assigning

### ISSUE THREAD

**Issue by Octopole** [Regalis11/Barotrauma#3696] opened 2020-09-03 12:03 UTC
**Description**
Game crashing issue in starting missin - loading sub phase. This bug won't happen just on vanilla version of game, but possible on mod that adding extra types of cargo box.

**Steps To Reproduce**
(This happenes in both singleplayer game and multiplayer one)
1. Pluging in any mod that provide extra type of cargo box, like EK: Armory which have about 5 new types (don't know the threshhold)
2. Buy a hell lot of things (don't know the threshhold either) which have different cargo box storage properties
3. Starting a misson (or just undock without any mission)
4. Game crashed during loading phase, its Irreversibly crush the save.

**Version**
0.10.4.0

**Additional information**
This is possibly triggered by failing to randomly assigning items in specific type of cargo box multi-processingly. This piece of code is in cargomanager.cs.  I tested this for about 10 times in both singleplayer game and multi-player mode, it is stably triggered.

**Comment by Regalis11** [comment] 2020-09-03 13:04
Possibly related (or a duplicate of) #3680.

Would it be possible for you to send us the save file, or any error logs (depending on the type of error, there may be a log file called "crashreport_object.log" in the game folder)? Does the game actually crash or just kick you back to the main menu with some error message? If the former, the crash report would be very helpful, if the latter, we'd need to know what the error message was. Thanks in advance and sorry for the inconvenience!

**Comment by Ek-Videogames** [comment] 2020-09-03 20:27
Btw, This bug seems to be caused by the combination of the known cargo-container mixup 
( When buying materials, chems, and explosives in large amounts, the items become jumbled into the wrong cargo-containers despite their CargoContainerIdentifer setting. Resulting in iron for instance getting spawned in the toxin cargo crates instead. )
- and the 0.10.4-0.10.5 current issue with unified crate tags.

**Comment by Regalis11** [comment] 2020-10-08 08:15
Could not reproduce with this info, closing at least for now

**Closed by Regalis11** 2020-10-08 08:15 UTC
Labels: Bug, Code, Need more info, Networking
