### ISSUE TITLE
Unlocking Makeshift Shelves and Portable Pump for bots is meaningless in multiplayer

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#11934] opened 2023-05-01 04:30 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Players can't place them without related talents(Let it Drain and Logistics System).
If there is a player who unlocks the talents, why do we need to unlock the talent for bots?
Unlock them for bots is useless since you can't switch to bots in multiplayer without using console commands or mods.

### Reproduction steps

1. Start a multiplayer campaign
2. Unlock related talent for a bot
3. Craft the items
4. You can't use them anyway. Why waste bot's talent point on them?

### Bug prevalence

Happens every time I play

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-05-01 13:12
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11767

**Closed by Regalis11** 2023-05-01 13:12 UTC
