### ISSUE TITLE
Medic bot will repeatedly try to heal the player even when at full health

### ISSUE THREAD

**Issue by Shadoris** [Regalis11/Barotrauma#5725] opened 2021-05-09 10:37 UTC
-I have searched the issue tracker to check if the issue has already been reported.

**Description**
Medic bot repeatedly grabs the player even when he is at full health, and just keeps hold of player character without giving him any medicine. I have noticed that it never happens to other bots. 

**Steps To Reproduce**
I made it happen a few times. The most effective way would be to let him heal you until you get opiate addiction, then he starts running after you and grabs you all the time. The important thing is to do something while he's healing you, if you stand in place while he's healing it mostly nothing happens. Bug appeared every single round when i was running and refilling coilgun ammo and he was trying to heal me mid-way while i was running.

**Version**
Windows 10, game ver. v0.13.3.11

**Additional information**
Keep on making the best game out there o7 You guys are the best

**Comment by B1G-FUNGUS** [comment] 2021-06-05 06:16
I have a very similar issue that seems to be related to this. Still, there are a couple key differences in the issue I was experiencing, so tell me if I should have made a separate ticket.

First, I'd like to mention that both of our issues are similar to https://github.com/Regalis11/Barotrauma/issues/4324, however that issue was closed a long time ago but this bug still pops up so I think it's worth reporting

**Description**
Anyways, my experience is that if medic bots are told to heal injured crew members at an outpost, they will find someone to heal and just grab onto them. They won't give any medicine, but they won't let go either. In my experience I was not at full health. The bots inventory is also empty, and the bot makes no attempt to gather medicine to heal the injured. (This may of also happened on a custom sub, but my memory is foggy so I'm not sure if the bot actually _did_ heal me.)

https://user-images.githubusercontent.com/80074584/120882039-13022b00-c58a-11eb-89f0-ac6d07642df1.mp4

**Steps To Reproduce**
When a medic bot is asked to heal injured people at an outpost, it will grab onto people and exhibit this behavior. I have only tested this in the single player campaign. I have not experienced this outside of the outpost levels.

**Comment by Regalis11** [comment] 2021-07-12 13:01
Fixed the 1st issue in https://github.com/Regalis11/Barotrauma-development/commit/63af274945f7038dbece12e2243703c490ddb5e5 and the 2nd in https://github.com/Regalis11/Barotrauma-development/commit/49b5ac8a9aef8526eca3cb2d2d69f3bbfe369bbe

**Comment by Rokvach** [comment] 2021-07-27 08:27
Tested, noticed that now if the medic runs out of medicine they will just follow the player/character who needs medical attention and keeps stating "Giving first aid to <name> in amidships!" even though they aren't actually doing anything but just following that character around. 

They will stop following once the character who needs medical attention has been fully healed, but will start to follow again once someone receives damage. 

My repro steps:
1. Use `giveaffliction "Internal damage" 5 name` until the medic runs out of medicine. (faster way would probably be to just remove all medical items from the sub)
2. Once medic runs out of medicine notice their behavior

**Comment by itchyOwl** [comment] 2021-08-02 10:35
Fixed the last issue in Regalis11/Barotrauma-development@61f00a2.

**Comment by Rokvach** [comment] 2021-08-02 10:54
Tested, working correctly. Closing.

**Closed by Rokvach** 2021-08-02 10:54 UTC
Labels: Bug, Code
