### ISSUE TITLE
[0.9.7.1] Coilgun bolts

### ISSUE THREAD

**Issue by rav2n** [Regalis11/Barotrauma#2394] opened 2020-03-05 10:15 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
After yesterday's update, I noticed that the point of appearance of the shells for the coilgun was shifted closer to the base of the gun. Because of this, a gun slightly recessed into the hull of a submarine begins to damage the hull itself when firing. Or is this exactly how it should work now?

**Steps To Reproduce**
Take advantage of the submarines to reproduce the situation: Svarog (clearly visible on the rear upper cannon), Khors (lower cannon).

**Version**
0.9.7.1

**Additional information**
![312](https://user-images.githubusercontent.com/29980468/75971502-ecff5e00-5ee2-11ea-8c30-48f5b4394a06.jpg)
![313](https://user-images.githubusercontent.com/29980468/75971508-eec92180-5ee2-11ea-8e8e-453b45ecd466.jpg)

**Comment by Regalis11** [comment] 2020-03-05 13:28
Duplicate of #2362

**Closed by Regalis11** 2020-03-05 13:28 UTC
