### ISSUE TITLE
Unable to link/de-link in Unstable sub editor

### ISSUE THREAD

**Issue by soledad630** [Regalis11/Barotrauma#10833] opened 2022-12-27 22:46 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Currently in unstable sub editor, linking feature (at least the part where holding down space is involved) doesn't work at all. After validating files, checking multiple subs, the issue persists. Discovered when waypoint cannot be linked, turns out everything that has a link utility doesn't function.

### Reproduction steps

1. Go into sub editor. Load up any sub (preferably one that has fabricators).
2. Test waypoint linking/unlinking, and test fabricator linking/unlinking.

### Bug prevalence

Happens every time I play

### Version

0.21.0.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-12-30 14:11
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10742

**Closed by Regalis11** 2022-12-30 14:11 UTC
