### ISSUE TITLE
Sub Editor - Thalamus items can still be selected even though visibility is OFF.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2806] opened 2020-05-11 15:31 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Sub Editor - Thalamus items can still be selected even though visibility is OFF.

**Version**
0.9.9.1

**Comment by Regalis11** [comment] 2020-05-12 08:27
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/973bd2efd9cff2d5fc29cd2f689b826daa245b47

**Comment by Rokvach** [comment] 2020-05-13 10:00
Wasn't able to reproduce, seems to be working correctly. Closing.

**Closed by Rokvach** 2020-05-13 10:00 UTC
Labels: Bug, Code
