### ISSUE TITLE
Nuking outpost caused crash.

### ISSUE THREAD

**Issue by AngelBirb** [Regalis11/Barotrauma#4584] opened 2020-12-25 05:59 UTC
**Description**
Me and one other player started a campaign and spawned in a Typhon with a few nuclear shells. I shot three of them into an outpost that we were docked on purpose and the game crashed.

**Steps To Reproduce**
Spawn in a Typhon Campaign and start with 10 Nuclear Shells and 3 Nuclear depth charges.
Shoot three of them at the outpost from docked state.
My game crashed about thirty seconds later while I was running through the sub

**Version**
v.0.10.0.9 Steam on Windows 10

**Additional information**
We purposefully wanted to see what would happen if we nuked the outpost. I assume it crashed because of all the stuff getting deleted/falling caused by the explosions, but I'm not sure. Was skeptical about even posting but I'll see if it helps.

z_g Ä>•Düßÿý
Index was outside the bounds of the array.
Message length: 1318 (164 bytes)
Read position: 1318
Header: ENTITY_POSITION
Previous header: ENTITY_POSITION
Previous object was 144 bits long (18 bytes)
 
   at Lidgren.Network.NetBitWriter.ReadByte(Byte[] fromBuffer, Int32 numberOfBits, Int32 readBitOffset) in <DEV>\Libraries\Lidgren.Network\NetBitWriter.cs:line 41
   at Lidgren.Network.NetBitWriter.ReadUInt32(Byte[] fromBuffer, Int32 numberOfBits, Int32 readBitOffset) in <DEV>\Libraries\Lidgren.Network\NetBitWriter.cs:line 295
   at Barotrauma.Networking.MsgReader.ReadRangedInteger(Byte[] buf, Int32& bitPos, Int32 min, Int32 max) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\Primitives\Message\Message.cs:line 355
   at Barotrauma.Networking.MsgReader.ReadRangedSingle(Byte[] buf, Int32& bitPos, Single min, Single max, Int32 bitCount) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\Primitives\Message\Message.cs:line 363
   at Barotrauma.Networking.ReadOnlyMessage.ReadRangedSingle(Single min, Single max, Int32 bitCount) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\Primitives\Message\Message.cs:line 713
   at Barotrauma.Character.ClientRead(ServerNetObject type, IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\CharacterNetworking.cs:line 241
   at Barotrauma.Networking.GameClient.ReadIngameUpdate(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2164
 
 - Bennie Larsen
 - Lola Simpson
 - AngelBirb
 - ShiverySoftness
 - NULL
 - NULL
 - NULL
 - Susy Marchi
Last console messages:
[12/25/2020 12:39:31 AM] ShiverySoftness
[12/25/2020 12:39:31 AM] AngelBirb
[12/25/2020 12:36:31 AM] Attempting to open ALC device "OpenAL Soft on SE32HY (NVIDIA High Definition Audio)"
[12/25/2020 12:36:27 AM] OpenAL Soft on Microphone (Steam Streaming Microphone) 54
[12/25/2020 12:36:27 AM] OpenAL Soft on Microphone (High Definition Audio Device) 56
[12/25/2020 12:31:50 AM] ShiverySoftness
[12/25/2020 12:31:50 AM] AngelBirb
[12/25/2020 12:19:04 AM] AngelBirb
[12/25/2020 12:19:04 AM] ShiverySoftness
[12/25/2020 12:18:58 AM] Task count: 0
[12/25/2020 12:18:53 AM] Generating an outpost for the start of the level... (Location: Uusi-Turcu, level type: Outpost)
[12/25/2020 12:15:03 AM] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/Indra.sub, size: 700x313)
[12/25/2020 12:14:08 AM] OpenAL Soft on Microphone (Steam Streaming Microphone) 54
[12/25/2020 12:14:08 AM] OpenAL Soft on Microphone (High Definition Audio Device) 56
[12/25/2020 12:14:04 AM] (Msg) SDR RelayNetworkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[12/25/2020 12:14:04 AM] (Msg) Ping location: iad=20+2,atl=39+3/33+2,ord=37+3,okc=60+6/54+3,eat=112+11/82+3,sea=99+9/83+3,lax=107+10/83+3,par=104+10/96+2,lhr=96+9,fra=109+10/106+2,gru=153+15/164+2,sgp=265+26/254+22
[12/25/2020 12:14:04 AM] (Msg) Ping measurement completed
[12/25/2020 12:14:02 AM] (Debug) Destroying relay 'sof#5 (139.45.193.10:27019)' because initial_ping_timeout
[12/25/2020 12:14:00 AM] (Debug) Destroying relay 'sof#4 (139.45.193.10:27018)' because initial_ping_timeout

**Comment by Regalis11** [comment] 2021-01-13 17:30
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3927

**Closed by Regalis11** 2021-01-13 17:30 UTC
Labels: Bug, Code, Networking
