### ISSUE TITLE
Bots stuck at repairing hulls and/or repairing broken hatches until the room is flooded

### ISSUE THREAD

**Issue by soledad630** [Regalis11/Barotrauma#6348] opened 2021-07-20 22:25 UTC
- [ yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Due to waypoint/height issue to certain hatches, bots cannot reach them to repair them or wield the hull around such points. It has been demostrated in Kastrull engine room but there's more places like in attachments.
![image](https://user-images.githubusercontent.com/86010664/126402948-52e849c9-1ba8-4d47-a29d-f622443076e0.png)

**Steps To Reproduce**
1. Select one of these ships
2. Set bots to repair leak and/or damaged systems
3. Cut/damage hull near said hatch and/or hatch from outside of the ship
4. Bots get stuck at the nearest waypoint on ground.

**Version**
0.14.6.0 windows.

**Additional information**
This might also be true to typhon 1 and 2's top docking hatch but i have yet to find the issue during gameplay since they never got really damaged.

**Comment by Regalis11** [comment] 2021-07-21 06:50
Duplicate of Regalis11/Barotrauma#6089 and Regalis11/Barotrauma#5587

**Closed by Regalis11** 2021-07-21 06:50 UTC
Labels: Bug, Code
