### ISSUE TITLE
Escort NPCs try to leave the ship nonstop in Singleplayer

### ISSUE THREAD

**Issue by SlenLen** [Regalis11/Barotrauma#13212] opened 2023-12-21 23:27 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Some of the NPCs in an escort mission will eventually stay in the airlock. When pulling them out they will just walk back into it again. When inside they walk into the door that leads outside, however they won't open it. When the door is openend they will try to swim outside and towards _somewhere,_ but will die shortly after as they never bother to equip a diving suit.
This makes entering/leaving the sub really difficult as you risk killing your escort target every time.

### Reproduction steps

1. Start a Singleplayer Campaign
2. Choose a escort mission (civilian transport, VIP transport, etc.)
3. One or more NPCs eventually walk into the airlock's exit door.

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Single player

### Version

v1.2.7.0 (Winter Update hotfix)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-12-22 09:18
Duplicate of https://github.com/Regalis11/Barotrauma/issues/13187

**Closed by Regalis11** 2023-12-22 09:18 UTC
