### ISSUE TITLE
Pirate subs in depths below 4000m will spawn with normal diving suits

### ISSUE THREAD

**Issue by Orchidthederg** [Regalis11/Barotrauma#7712] opened 2021-12-11 00:27 UTC
- [✓] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Upon accepting a Pirate Mission in an area that has a depth under 4000m, pirate ships will spawn with Mk 1 diving suits, causing them to die quickly upon a hull breach or leaving the sub.

**Steps To Reproduce**
Enter a level with a starting depth below 4000m, then attempt to flood the sub or lure out the pirates. They will die due to barotrauma if outside or in a flooded room due to insufficient diving suits.

**Version**
v0.15.13.0 (Windows, branch release)

**Additional information**
Issue also found here, but is still occurring: https://github.com/Regalis11/Barotrauma/issues/7272#issue-1051419631

**Comment by ZeWaka** [comment] 2021-12-11 00:53
Well yeah, that unstable version with the bugfix hasn't made it into a live version fix yet.
You reported with the exact same version number as the original issue.

**Comment by MaaiG** [comment] 2021-12-12 13:29
> Well yeah, that unstable version with the bugfix hasn't made it into a live version fix yet.

I was wondering when’s the next "live version"?

**Comment by Regalis11** [comment] 2021-12-13 14:06
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7272

> Just wondering when’s the next "live version"?

Very soon. :)

**Closed by Regalis11** 2021-12-13 14:06 UTC
