### ISSUE TITLE
Bots - Bots can't fix these walls on Orca, yet player easily can

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#3334] opened 2020-07-09 15:37 UTC
**Description**
These walls on Orca get broken often and bots have difficulty welding them.
-Red: The walls that bots have problem with
-Blue: Player can fix the walls easily while standing in blue spot, aiming up and welding
-Orange: Bots stand in these places and weld indefinetly (can be seen in clip 2)
![image](https://user-images.githubusercontent.com/59519434/87060187-82508d00-c20a-11ea-99f0-b0a670c15de7.png)
NOTE: Bots can fix these places if the command room is completely flooded!
**Steps To Reproduce**
-go to editor
-open Orca, test mode
-order bot to fix leaks
-cause explosion 200 200 200 200 on the airlock sloped walls
-observe bot behaviour

**Version**
Unstable

**Additional information**
Videoclips of both places:
Clip 1 (left wall):https://medal.tv/clips/28201559/d1337fTvfC6C
Clip 2 (right wall): https://medal.tv/clips/28201559/d1337dRYMNtR

I suspect other submarines will have plenty of similiar cases.

**Comment by itchyOwl** [comment] 2020-09-03 19:22
Cannot reproduce. It's normal that the bots don't always fix the walls entirely (there's a separate ticket about that). However, they should be able to fix any leaks in those walls.

There could be some pathfinding issues that are now fixed on the dev branch (See #3697) causing issues on those walls too.

**Comment by Rokvach** [comment] 2020-09-25 10:09
Tested with a single bot and the bot was able to fix both sides, but somehow had issues fully fixing the right side. 

The inner wall looks to be entirely intact but there's still water flowing in and the bot wasn't able to fix it (No idea how it can still be flooding  when the inner wall should be on the way of the flood, so this might not be a bot issue at all anymore.)
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/b7ff67e3-8028-4b96-89d0-43c06f7ca2f8)

**Comment by Rokvach** [comment] 2020-09-25 10:32
The above issue isn't really a AI issue but a issue on how the outerwall and hull is positioned (afaik). The initial issue has been fixed so I will be closing this ticket. Closing.

**Closed by Rokvach** 2020-09-25 10:32 UTC
Labels: Bug, Code, Needs testing
