### ISSUE TITLE
Potential memory leak

### ISSUE THREAD

**Issue by esirprus** [Regalis11/Barotrauma#9285] opened 2022-06-08 02:51 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

![image](https://user-images.githubusercontent.com/44423036/172518831-647409bc-8bf4-4e4f-941c-613797210d38.png)
see this no player in the game, but the server still have 4G occupied.
In fact, I have to restart the server everyday, or my server will shut down due to lack of memory.

### Reproduction steps

1.start a server, and play for a while.
2.disconnect from the server
3.monitor server memory changes

### Bug prevalence

Happens regularly

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment] 2022-06-08 05:45
What kind of mods are you using? A vanilla server should not use anywhere near that much memory.

**Comment by esirprus** [comment] 2022-06-08 05:48
[(delete the .zip)config_player.xml.zip](https://github.com/Regalis11/Barotrauma/files/8858632/delete.the.zip.config_player.xml.zip)
Using LuaCsforbarotrauma server

**Comment by esirprus** [comment] 2022-06-08 05:57
> A vanilla server should not use anywhere near that much memory.

I seem to be under the impression that vanilla servers do this too ...... I'm not sure.

**Comment by esirprus** [comment] 2022-06-08 05:58
![image](https://user-images.githubusercontent.com/44423036/172542500-9dbb4d2c-a99f-42ad-8015-ff230280873c.png)
@Regalis11  what about this server?
[(another)config_player.xml.zip](https://github.com/Regalis11/Barotrauma/files/8858697/another.config_player.xml.zip)

**Comment by esirprus** [comment] 2022-06-08 06:03
![image](https://user-images.githubusercontent.com/44423036/172543195-7ae41b24-5c66-46fc-9b82-4806f0fe7c49.png)


![image](https://user-images.githubusercontent.com/44423036/172543145-6ac21125-479d-4137-9d27-c9b4224b5180.png)

what about this server? @Regalis11

**Comment by esirprus** [comment] 2022-06-08 06:12
this small server just have some lua mods and sub mods, only 2776997644([BOS]Wrecks) and 2732209820([BOS]Beacons) are mods that change vanilla play.

**Comment by esirprus** [comment] 2022-06-08 08:09
I don't think the memory usage at the beginning of the server can explain problems.
You maybe need to play and keep the server on about 24h , then check the memory usage of the server when there is no one at the server.
some told me that maybe lua for barotrauma have memory leaks, NOT SURE.

**Comment by esirprus** [comment] 2022-06-08 16:43
another server's memory(8G) use are here, just use luaforbarotrauma, a lua mod and some sub mods
![0N5 L(KJ~HQ9BN29XN5UMU](https://user-images.githubusercontent.com/44423036/172670854-873f50cb-397a-4460-8a87-e34c59f1d8fb.png)
![@L~DXF15D~1Q((Q`YMUPQ)3](https://user-images.githubusercontent.com/44423036/172670994-44e22090-9512-45a7-9de2-54cf6de1d0de.png)
[(delete)config_player (2).xml.zip](https://github.com/Regalis11/Barotrauma/files/8863540/delete.config_player.2.xml.zip)

**Comment by esirprus** [comment] 2022-06-11 04:38
a test about vanilla server + Job Extend mod + some sub mod
![vanilla RAM use](https://user-images.githubusercontent.com/44423036/173172743-4f5b6ba0-fb91-4584-aee4-f0662dfc20c0.png)
s

**Comment by zhu-rengong** [comment] 2022-06-11 05:11
Also it happened to me. The server has to be restarted every time it runs for more than 24 hours, otherwise the memory will fill up and the game will become very laggy. I'm using LFB, not sure if it's caused by Vanilla.
The prerequisites for memory growth are: the server must be in a round-in-progress state.

**Comment by Regalis11** [comment] 2023-11-02 15:52
Possibly fixed in https://github.com/Regalis11/Barotrauma-development/commit/7b63d2f1470dcce23b3a5630f26069c7401623e2

Fixed a memory leak in GameSession. TopLeftButtonGroup subscribed to ResolutionChanged but didn't properly unsubscribe from it, keeping the whole GameSession instance alive (and a million other things it references).

**Comment by Rokvach** [comment] 2023-11-17 10:49
Tested with the memory leak fixes and compared memory usage with and without the fixes. Also tested that the "topLeftButtonGroup" resizes correctly on resolution changes. 

Couldn't find any issues, can be merged and closed. 

With memory leak fixes
==================================

Quickstart Berilia 100 wastesbasic

1.   Main menu - 995 MB    || Round loaded - 2 117 MB
2.   Main menu - 1 674 MB || Round loaded - 2 198 MB
3.   Main menu - 1 799 MB || Round loaded - 2 261 MB
4.   Main menu - 1 850 MB || Round loaded - 2 537 MB
5.   Main menu - 1 768 MB || Round loaded - 2 490 MB
6.   Main menu - 2 039 MB || Round loaded - 2 522 MB
7.   Main menu - 2 076 MB || Round loaded - 2 168 MB
8.   Main menu - 1 914 MB || Round loaded - 2 300 MB
9.   Main menu - 1 951 MB || Round loaded - 2 636 MB
10. Main menu - 2 215 MB || Round loaded - 2 350 MB

11. Main menu - 1 968 MB || Round loaded - 2 890 MB
12. Main menu - 2 415 MB || Round loaded - 2 425 MB
13. Main menu - 2 078 MB || Round loaded - 2 378 MB
14. Main menu - 2 066 MB || Round loaded - 2 396 MB
15. Main menu - 2 056 MB || Round loaded - 2 530 MB
16. Main menu - 2 172 MB || Round loaded - 2 996 MB
17. Main menu - 2 428 MB || Round loaded - 2 788 MB
18. Main menu - 2 375 MB || Round loaded - 2 924 MB
19. Main menu - 2 421 MB || Round loaded - 2 650 MB
20. Main menu - 2 604 MB || Round loaded - 2 707 MB

Without memory leak fixes
==================================

Quickstart Berilia 100 wastesbasic

1.   Main menu - 1 029 MB || Round loaded - 2 135 MB
2.   Main menu - 1 840 MB || Round loaded - 2 556 MB
3.   Main menu - 2 245 MB || Round loaded - 2 808 MB
4.   Main menu - 2 518 MB || Round loaded - 2 970 MB
5.   Main menu - 3 107 MB || Round loaded - 3 794 MB
6.   Main menu - 3 471 MB || Round loaded - 4 278 MB
7.   Main menu - 4 218 MB || Round loaded - 4 565 MB
8.   Main menu - 4 501 MB || Round loaded - 5 184 MB
9.   Main menu - 5 160 MB || Round loaded - 5 518 MB
10. Main menu - 5 541 MB || Round loaded - 5 562 MB

11. Main menu - 5 585 MB || Round loaded - 6 130 MB
12. Main menu - 6 054 MB || Round loaded - 6 231 MB
13. Main menu - 6 258 MB || Round loaded - 7 038 MB
14. Main menu - 6 951 MB || Round loaded - 6 963 MB
15. Main menu - 7 000 MB || Round loaded - 7 663 MB
16. Main menu - 7 610 MB || Round loaded - 8 247 MB
17. Main menu - 7 605 MB || Round loaded - 8 425 MB
18. Main menu - 8 407 MB || Round loaded - 8 702 MB
19. Main menu - 8 633 MB || Round loaded - 9 216 MB
20. Main menu - 9 106 MB || Round loaded - 9 924 MB

**Closed** 2023-11-17 10:50 UTC
Labels: Code, Performance, Modding
