### ISSUE TITLE
Burns do not automatically recover

### ISSUE THREAD

**Issue by kiauio** [Regalis11/Barotrauma#9882] opened 2022-09-15 17:36 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Burns should recover slowly

### Bug prevalence

Happens every time I play

### Version

0.19.5.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-09-18 16:14
Thank you for the report! I unfortunately couldn't reproduce the issue: the burns do seem to heal by themselves. The rate is very slow though (it takes about 13 seconds for the strength to go down by one), I wonder if it could be that you didn't wait long enough for it to go down?

**Comment by Regalis11** [comment] 2022-09-29 08:50
No known steps to repro, closing

**Closed by Regalis11** 2022-09-29 08:50 UTC
Labels: Bug, Need more info, Code
