### ISSUE TITLE
Fast ticking tools and weapon can potentially reduce or remove creature attack cooldowns.

### ISSUE THREAD

**Issue by PokkeTigrex** [Regalis11/Barotrauma#8345] opened 2022-02-23 00:42 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Encountered this issue while out in the ruins and dealing with swarm feeders, where using a plasma cutter on them when latched onto someone else seemingly makes them do massive damage through rapid hits to that character. I've heard from someone when discussing creatures doing very fast successive attacks that burn damage might have something to do with it, but because most fast ticking weapons and tools like welders, cutters and steam guns, and fire in general cause burn, its hard to tell if its just burn or how the damage that ticks fast causes it. I decided to quickly test with other creatures, and with the crawler, they seemed to attack fairly faster when being plasma cutted. I tried with mudraptors but because of the high knockback attacks, its harder to determine, unless maybe underwater?

**Steps To Reproduce**
Swarmfeeders are the easiest to reproduce with, what I did to reproduce is spawn a character and have them paralyzed and have them lay them outside on top the sub or some flat surface or enclosure that is flooded with diving suits. I spawned about 1-3 swarmfeeders and let them latch on to the paralyzed character. I used a plasma cutter on the swarmfeeders while they are latched and they seem to quickly do damage on the latched target as long as you keep attacking them with the cutter, or until they dislatch.

**Version**
0.16.6.0

**Comment by Regalis11** [comment] 2022-02-23 08:22
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7151

Thank you for the repro steps though, we haven't been able to reproduce this so far but I'll give it another test with swarm feeders.

**Closed by Regalis11** 2022-02-23 08:22 UTC

**Comment by PokkeTigrex** [comment] 2022-02-23 16:15
I've quickly tested it again with other creatures and its so much more noticeable while underwater, where they would have no cooldown and kill the target character in almost an instant.
