### ISSUE TITLE
Crashing when loading save

### ISSUE THREAD

**Issue by connorcot** [Regalis11/Barotrauma#6160] opened 2021-06-23 20:38 UTC
Every time I try and load my campaign save it crashes to desktop the game was completely fine and then I started another mission and it immediately crashed and I have not been able to load the save since but can still load other saves please let me know how I can fix this as i don't really want to have to restart my campaign again 

here's a crash log
[crashreport (10).log](https://github.com/Regalis11/Barotrauma/files/6704745/crashreport.10.log)

**Comment by connorcot** [comment] 2021-06-23 20:45
Also i have already tried reinstalling the game

**Comment by Regalis11** [comment] 2021-07-06 10:50
Thank you for the report, and sorry for the late reply - we've been having our summer vacations lately and haven't been able to respond to all the issue reports.

It's hard to say what exactly is causing this based on the crash report, but it appears an ice spire in the level is failing to generate correctly. Would it be possible to send us the save file? Note that that you need to .zip it first to attach it here, because GitHub doesn't support the .save file extension.

**Comment by connorcot** [comment] 2021-07-06 22:49
Yeah no problem here's the save file
[Broken World.zip](https://github.com/Regalis11/Barotrauma/files/6773151/Broken.World.zip)

**Comment by Regalis11** [comment] 2021-07-22 11:06
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/70467560eb5a477c3a30ea7e5b6e5c4a4ba4a845. Looks like this was caused by an ice spire generating on a very short level wall, which prevented the game from generating it's vertices properly.

**Comment by Rokvach** [comment] 2021-07-28 10:30
Tested, working correctly. Closing.

**Closed by Rokvach** 2021-07-28 10:30 UTC
Labels: Bug, Code, Crash
