### ISSUE TITLE
Small Pump does not require power

### ISSUE THREAD

**Issue by rytrasmi** [Regalis11/Barotrauma#2543] opened 2020-03-31 05:37 UTC
I have searched the issue tracker to check if the issue has already been reported.

Version: 0.9.7.1 (Window)

Reactor off, batteries drained to 0, and junction boxes say 0 power available.

Small pump is connected to power grid and its set state input is connected to a switch. It will still pump water out of the sub when switched on.

Sub is attached. Pump is at bottom right, in air lock. You can open and close the air lock to fill it with water and the pump will drain the water even with 0 power available.

[Dogfish.zip](https://github.com/Regalis11/Barotrauma/files/4406940/Dogfish.zip)

**Comment by Regalis11** [comment] 2020-03-31 08:02
The power consumption of the pump is set to 0, so this seems to be working as expected.

**Comment by rytrasmi** [comment] 2020-03-31 13:49
Sorry about that. I must have set it to 0 when testing. 

It still happens, though. The attached sub has it set to 60.0 and I can still drain water with 0 power in the sub.

[Dogfish.zip](https://github.com/Regalis11/Barotrauma/files/4409420/Dogfish.zip)

**Comment by Regalis11** [comment] 2020-04-01 09:14
I'm afraid I wasn't able to reproduce in the latest version (v0.9.8.0)

**Comment by rytrasmi** [comment] 2020-04-01 14:16
Yeah, I tested it on v0.9.8.0 just now, both multiplayer and single, and I can confirm it no longer happens. Recommend closing.

**Comment by Rokvach** [comment] 2020-04-02 09:04
Closing.

**Closed by Rokvach** 2020-04-02 09:04 UTC
Labels: Bug, Code
