### ISSUE TITLE
Barotrauma multiplayer problem

### ISSUE THREAD

**Issue by Kenshi69** [Regalis11/Barotrauma#7394] opened 2021-11-19 14:24 UTC
![unknown](https://user-images.githubusercontent.com/94696553/142638241-015a692f-62ea-4999-a956-77793a8f9167.png)

**Comment by Regalis11** [comment] 2021-11-21 14:06
Most likely a duplicate of https://github.com/Regalis11/Barotrauma/issues/7175: this can happen if receiving the campaign save file takes too long.

**Closed by Regalis11** 2021-11-21 14:06 UTC
