### ISSUE TITLE
AI Suffocating

### ISSUE THREAD

**Issue by Mercenary46** [Regalis11/Barotrauma#3437] opened 2020-07-31 02:32 UTC
- [There was an old report about something similar over 20 days ago ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Anytime the AI uses a diving suit for any reason, once they run out of oxygen in the tank they will not seek a replacement and just suffocate to death. Lost half of an eight man crew because of this.

**Steps To Reproduce**
Should be as simple as just playing with bots and having a situation arise where they need a suit. If they burn through the first oxygen tank they just decide they would rather die then waste more oxygen I guess.

**Version**
0.10.4.0

**Additional information**
This happened playing a two human coop in multiplayer campaign. Plenty of oxygen throughout the ship in supply cabinets and diving suit rooms. Ship used was the Kastrull.

**Comment by Regalis11** [comment] 2020-07-31 07:38
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3333

This is a known issue (https://trello.com/c/q15eG7cw/309-bots-may-suffocate-in-diving-suits), we're working on a fix for the next patch. Sorry for the inconvenience!

**Closed by Regalis11** 2020-07-31 07:38 UTC

**Comment by Mercenary46** [comment] 2020-07-31 13:46
Ah, I apologize. I searched under AI and oxygen and didn't see that one. Should have checked under bots as well. Thanks!
