### ISSUE TITLE
Hammerheads/the latcher knock me and my crew unconcious for an unplayable amount of time

### ISSUE THREAD

**Issue by Vagitarius** [Regalis11/Barotrauma#10688] opened 2022-12-08 17:30 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I just created this github account, but I haven't found anything about this issue on google or this website so here I am reporting a nearly game breaking bug that me and my friends are experiencing

for a while, we were using a barsuk, and everything was going great.  But when we started encountering hammerheads, we would randomly go unconcious when being taken of the left upper gun.   this would happen when water enters the sub and knocks you off the gun, or when we would get struck by large enemies

we would literally go unconcious for about 20 seconds, and we nearly drowned in 3 inches of water multiple times because of it

I have attached a few different instances of the glitch,  not sure if anyone else has experienced this, or maybe even this is intended gameplay, just want some input here 

excuse the swearing, the oceans of Europa had been stressing us out all day, and this glitch had been persistant

example 1 https://youtu.be/-wD5qE5c20o

example 2 https://youtu.be/kkk4bu61EnQ

example 3 https://www.youtube.com/watch?v=LNV2DpkmRZw

### Reproduction steps

will try to replicate later when my friends get on

### Bug prevalence

Happens regularly

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Vagitarius** [comment] 2022-12-08 18:40
I will endeavor to recreate and record more footage of this instance as well

**Comment by Regalis11** [comment] 2022-12-09 07:34
Thank you for the report! I'm fairly sure this is a duplicate of https://github.com/regalis11/barotrauma/issues/10371, and should be fixed in the next update

**Closed by Regalis11** 2022-12-09 07:34 UTC

**Comment by Vagitarius** [comment] 2022-12-09 10:44
ah I see! I didn't even think about it being connected to our clown perk, but as soon as we unlocked that, it started happening

thanks for the hard work!
