### ISSUE TITLE
[Unstable 0.9.703.0] Weird shadows on Humpback's railgun obscure view

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#2151] opened 2020-02-06 03:46 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
An incorrect shadow is obscuring view from Humpback's railgun periscope.
**Steps To Reproduce**
Start a level in humpback, use the railgun periscope, observe the bad shadow.

**Version**
0.9.703.0

**Additional information**
Same issue could be on other submarines as well, we just played on Humpback tonight.

**Comment by Kaillera** [comment] 2020-02-06 03:49
The humpback's railgun is embedded inbetween 2 brackets which obscures the LOS.

**Comment by Regalis11** [comment] 2020-02-06 08:12
I think this is by design to limit the range of the railgun, @danielasteljoki?

**Comment by danielasteljoki** [comment] 2020-02-06 09:28
I agree that it looks a bit weird. Adjusted the railgun a bit to get rid of incorrect-looking shadow.

**Comment by Rokvach** [comment] 2020-02-06 16:32
No issues here, closing.

**Closed by Rokvach** 2020-02-06 16:32 UTC
Labels: Design
