### ISSUE TITLE
Some xp talents seemingly don't give extra xp

### ISSUE THREAD

**Issue by mdigreg** [Regalis11/Barotrauma#10901] opened 2023-01-10 05:54 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

XP talents like Salvage Crew and Bounty Hunter are not giving members of my crew extra xp, unless they apply to the entire crew. We noticed all of us have the same xp but only some of us have bonus xp talents. 
Some things to note:
- The captain has Camaraderie, it could be that they don't stack, which sounds unintentional because why would you take any of these xp talents if the captain could just take Camaraderie?
     - We don't have different xp even when a crew member dies. This would mean Camaraderie doesn't trigger so even if it is 
     overriding talents like Wreck Salvage or Bounty Hunter normally those talents should then trigger, but there is no noticeable 
     difference in xp gain.
- The only crew member with more xp than the rest is an npc security officer with War Stories and Bootcamp
     - This could imply several things. It could mean none of the percentage increase talents (Salvage crew, Bounty Hunter, 
     Bootcamp) are working and only the flat bonus talents (War Stories) are working.
     - It could mean that Bootcamp and Camaraderie are working and not stacking with, thus overriding, the rest of the xp talents.
     - As previously stated, it could also be that the percentage increase talents apply to the entire crew, but the flat bonus xp 
     talent (War Stories) applies only to the person who has the talent which is why the security officer is a higher level.
I have no way of testing this on my end without starting several different campaigns so I hope you guys can figure it out.

### Reproduction steps

1. Start campaign
2. Take xp talents on several crew members and Camaraderie on the captain
3. Fulfill the bonus xp requirement on some talents (complete a wreck salvage for Salvage Crew)
4. Even if a crew member dies, there will be no xp difference among the crew

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by 3e849f2e5c** [comment] 2023-01-10 08:53
Duplicate of #10840

**Closed by 3e849f2e5c** 2023-01-10 08:53 UTC
