### ISSUE TITLE
Crash on loading (Collection was modified; enumeration operation may not execute.)

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#6112] opened 2021-06-18 10:35 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported but I'm not great in searching.
Related to #6111 ?

**Description**
Crash after launching the game due to updates of conflicting mods.

```
InnerException: Collection was modified; enumeration operation may not execute.
Target site: Void ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
```

**Steps To Reproduce**
Could not be reproduced.

**Version**
v0.14.6.0 Windows Steam

**Additional information**
```
Stack trace: 
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Barotrauma.GameSettings.get_AllEnabledPackages()+MoveNext() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSettings.cs:line 275
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Barotrauma.SoundPlayer.Init()+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sounds\SoundPlayer.cs:line 155
   at Barotrauma.GameMain.Load(Boolean isSeparateThread)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 526
   at Barotrauma.CoroutineManager.ExecuteCoroutineThread(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 173
Last debug messages:
[18/06/2021 12:26:33] Coroutine "Load" has failed
[18/06/2021 12:26:33] Overriding the wreck ai config with 'Mods/IntoTheAbyss/Content/Map/ita_thalamusai.xml'
[18/06/2021 12:26:32] Adding additional wreck ai config from file 'Mods/New Wrecks For Barotrauma/ThalamusAI.xml'
[18/06/2021 12:26:26] Coroutine "Load" has thrown an exception {Collection was modified; enumeration operation may not execute.}
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Barotrauma.GameSettings.get_AllEnabledPackages()+MoveNext() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSettings.cs:line 275
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Barotrauma.SoundPlayer.Init()+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sounds\SoundPlayer.cs:line 155
   at Barotrauma.GameMain.Load(Boolean isSeparateThread)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 526
   at Barotrauma.CoroutineManager.ExecuteCoroutineThread(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 173
[18/06/2021 12:26:24] Overriding all sounds with Mods/Sounds Of Europa/Sounds/sounds.xml
[18/06/2021 12:26:15] Overriding the ui styles with 'Mods/IntoTheAbyss/Content/ita_style.xml'
```
[crashreport (4).log](https://github.com/Regalis11/Barotrauma/files/6676428/crashreport.4.log)

**Comment by Konfuz** [comment] 2021-06-18 11:12
>     * I'm not great in searching.
>       Related to #6111 ?
Yes, this seems to be exactly the same issue I had in #6111

**Comment by Krzeszny** [comment] 2021-06-20 12:18
> > ```
> > * I'm not great in searching.
> >   Related to #6111 ?
> > ```
> 
> Yes, this seems to be exactly the same issue I had in #6111

The exception is different.

**Comment by Regalis11** [comment] 2021-07-08 13:11
Could not find a way to repro this, but did some changes to the method that should prevent this from happening any longer: https://github.com/Regalis11/Barotrauma-development/commit/7bae67c7576733ddadb9d0e5b9190fa2204340a1

**Comment by Rokvach** [comment] 2021-08-02 07:08
No known steps to reproduce, I will keep this open until the end of the Unstable testing period and see if anyone happens to encounter it.

**Comment by Rokvach** [comment] 2021-08-16 19:17
As there's no known steps to reproduce this and no encounters to this issue during the Unstable testing period, I will be closing this ticket. This ticket can be opened again if the issue resurfaces. Closing.

**Closed by Rokvach** 2021-08-16 19:17 UTC
Labels: Bug, Code, Crash
