### ISSUE TITLE
Only the latest chat message is displayed on collapsed chat window

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2199] opened 2020-02-07 18:38 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When multiple people are typing messages, only the latest message is displayed. This causes some of the messages to never show up, or show up for a split moment.

**Version**
~0.9.704

**Comment by Regalis11** [comment] 2020-02-08 13:16
I'd consider this a duplicate of #1896

**Closed by Regalis11** 2020-02-08 13:16 UTC
