### ISSUE TITLE
Fire takes huge chunks of health without any warning

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#2715] opened 2020-04-26 15:42 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Seems like fire is not calculating damage correctly

https://streamable.com/w505o1  -- The guy on the right is killed despite being no where near fire.
https://streamable.com/4x8cel  -- Killed by seemingly incorrect fire range.

**Steps To Reproduce**
Big fire in multiplayer game.

**Version**
All versions

**Comment by hubismal** [comment] 2020-04-26 17:00
This is a big issue that I always just attributed to desync, but is incredibly annoying and makes putting fires out much harder than it should be due to their astounding range. Seconding this.

**Comment by hubismal** [comment] 2020-05-05 02:04
I don't think this is networking related, start a relatively big fire in a single player game and notice how you get damaged through doors despite the fire being on the other side of the door.

**Comment by thegrb93** [comment] 2020-05-05 02:50
I think that much is normal.

What isn't normal is the rate of damage. In the video, that guy instantly dies despite being on the other side of a flooded room.

In the other video, you can see me take very little damage at first, then 5 seconds later I return with a fire extinguisher and nearly instantly die while meanwhile a guy below doesn't take any damage.

**Comment by Regalis11** [comment] 2020-05-05 07:00
I think this was caused by a combination of 2 issues:
- The damage done by the fire was not predicted client-side, but instead the clients waited for the server to send a health update before displaying the damage on the health bar.
- There was no upper limit to the damage range or damage by the fires, it just kept increasing as the size of the fire increases.

Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/a039cd286db86ba01abc683991f7b0678e229dec

**Comment by Rokvach** [comment] 2020-05-13 09:03
I think the smoke particles caused by the fire also does damage, as it still causes damage from a really far away from the actual fire, but the smoke does spread much further than the fire itself. @Regalis11

**Comment by Rokvach** [comment] 2020-05-13 09:53
Apparently the issue I highlighted above is intentional, the fire does cause damage further than the fire itself is visible, this damage is caused by the heat and smoke of the fire. 

Some nerfs will be implemented, especially by lowering the damage done by the fire when its behind a door/wall.

**Comment by Regalis11** [comment] 2020-05-13 13:26
Reduced the damage range and implemented taking doors/walls into account in https://github.com/Regalis11/Barotrauma-development/commit/655ef4fd07b621af7f885c3646736b2dc0757ab7

**Comment by Rokvach** [comment] 2020-05-18 00:57
Tested, seems a lot more fair now. Closing.

**Closed by Rokvach** 2020-05-18 00:57 UTC
Labels: Bug, Code, Networking

**Comment by thegrb93** [comment] 2020-08-08 05:43
I'm happy this is better, but you guys nerfed fire too hard. I just saw someone laying in a reactor inferno for 10 seconds survive with 50% health after being extinguished.
