### ISSUE TITLE
Barotrauma making servers?

### ISSUE THREAD

**Issue by tayyo1** [Regalis11/Barotrauma#555] opened 2018-08-01 12:50 UTC
Hello and i try to make serrvers with my friends to play with and it shows 0 players for everyone and it says:

Couldn't Connect to Server
Failed to establish connection - no response from host.

http://prntscr.com/kdcy2l
Help would be nice.
                                                                                                                                                       Thanks!

**Comment by NilanthAnimosus** [comment] 2018-08-01 13:07
have a read of: #518 and scroll down to a comment I made, it details some things you can try. essentially this is an issue of port forwarding and I left some steps on how to go about it there.

**Comment by Regalis11** [comment] 2018-08-02 07:52
Most likely a duplicate of #518. If port forwarding does not work, please let me know and I'll reopen this.

**Closed by Regalis11** 2018-08-02 07:52 UTC
Labels: Networking-related, bug, question
