### ISSUE TITLE
Barotrauma can't run due to the exception about "waterbump.png" is missing 

### ISSUE THREAD

**Issue by AlexFedotovComputing** [Regalis11/Barotrauma#11754] opened 2023-04-05 11:21 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Built by MS Visual Studio 2022 Community Edition, no erros, tests are passed, windows.

Cannot run game, getting immediate error
"Exception: Could not find file 'C:\Users\Alexander\Documents\GitHub\Barotrauma\Barotrauma\bin\ReleaseWindows\net6.0\Content\Effects\waterbump.png'. (System.IO.FileNotFoundException)"

And there is no any png files in this directory, only xnb.

Build is OK, 39 tests are OK.

### Reproduction steps

Just starting freshly built game. 

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 04/05/2023 14:14:00)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

9EECFB69A2A5FA30DD88706924256EE5

Game version 1.0.8.0 (ReleaseWindows, branch master, revision 5a3752a3b)
Graphics mode: 3840x2160 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: None
Level seed: no level loaded
Loaded submarine: None
Selected screen: None

System info:
    Operating system: Microsoft Windows NT 10.0.22000.0 64 bit
    GPU name: NVIDIA RTX A5500 Laptop GPU
    Display mode: {Width:3840 Height:2160 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Could not find file 'C:\Users\Alexander\Documents\GitHub\Barotrauma\Barotrauma\bin\ReleaseWindows\net6.0\Content\Effects\waterbump.png'. (System.IO.FileNotFoundException)
Target site: Microsoft.Win32.SafeHandles.SafeFileHandle CreateFile(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, System.IO.FileOptions)
Stack trace: 
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
   at Barotrauma.IO.File.Open(String path, FileMode mode, FileAccess access, Nullable`1 share) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SafeIO.cs:line 410
   at Barotrauma.IO.File.OpenRead(String path) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SafeIO.cs:line 415
   at Barotrauma.TextureLoader.FromFile(String path, Boolean compress, Boolean mipmap) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Utils\TextureLoader.cs:line 193
   at Barotrauma.WaterRenderer..ctor(GraphicsDevice graphicsDevice) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\Levels\WaterRenderer.cs:line 71
   at Barotrauma.GameMain.LoadContent() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 404
   at Microsoft.Xna.Framework.Game.Initialize() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 551
   at Barotrauma.GameMain.Initialize() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 372
   at Microsoft.Xna.Framework.Game.DoInitialize() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 678
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 381
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[04/05/2023 14:13:59] SteamManager initialization threw an exception {SteamApi_Init returned false. Steam isn't running, couldn't find Steam, AppId is ureleased, Don't own AppId.}
   at Steamworks.SteamClient.Init(UInt32 appid, Boolean asyncCallbacks) in <DEV>\Libraries\Facepunch.Steamworks\SteamClient.cs:line 28
   at Barotrauma.Steam.SteamManager.InitializeProjectSpecific() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Steam\SteamManager.cs:line 25
```

**Comment by Regalis11** [comment] 2023-04-05 11:54
Thank you for the report!

Did you [copy the Content directory from your copy of Barotrauma to the project folder](https://github.com/Regalis11/Barotrauma/blob/master/CONTRIBUTING.md#building-the-game)?

**Comment by Regalis11** [comment] 2023-04-05 15:02
Closing as a duplicate of https://github.com/Regalis11/Barotrauma/issues/9524, but please let us if the game still can't run after copying the content to the folder!

**Closed by Regalis11** 2023-04-05 15:02 UTC
Labels: Need more info
