### ISSUE TITLE
Crash to main menu while reading message from server

### ISSUE THREAD

**Issue by OverwatchVoice** [Regalis11/Barotrauma#2722] opened 2020-04-27 13:31 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Game froze, then terminated the connection. I was hosting the dedicated server I was playing on, and my friends didn't experience any issues, the server ran as normal afterwards, too.

**Crash log**
https://imgur.com/a/wrpcalq

**Steps To Reproduce**
Unknown

**Version**
0.9.9.0, Win10

**Comment by Regalis11** [comment] 2020-04-28 07:50
Most likely a duplicate of #2683. (Even though the error message is different, the same bug can cause this error as well)

**Closed by Regalis11** 2020-04-28 07:50 UTC
