### ISSUE TITLE
All seeing eye gave 3 extra talent points

### ISSUE THREAD

**Issue by dsr1231248D** [Regalis11/Barotrauma#7989] opened 2022-01-05 20:57 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**All-seeing eye Bug description**
After getting the 'All-seeing eye' tree, I gained 3 additional talent points. I did not notice at first, as they were being shown neither as an alert in the info tab nor next to the "Talent Points". Instead, when my character leveled up, I noticed that I couldn't confirm my talent selection until I've selected a total of 4 talents (and only then would the game consume my level up point and allow me to apply).

**Version**
Windows 11; game v0.15.22.1.

**Additional information**
No mods enabled, everything happens in Vanilla Baro.

**Attachments**
![20220105153300_1 - Copy](https://user-images.githubusercontent.com/17814596/148288095-8ce6145c-4d18-4eec-96f1-008cc792a17b.jpg)

**Comment by Regalis11** [comment] 2022-01-07 15:05
I couldn't find a way to repro this, but I suspect it was caused by the same issue as https://github.com/regalis11/barotrauma/issues/7975, and should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/e08b6a406386b7000b51b208179006b1037c627a

**Closed** 2022-01-13 14:32 UTC
Labels: Bug, Needs testing, Code
