### ISSUE TITLE
endworm 1shotted again non-nuclear shell

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#6026] opened 2021-06-10 14:09 UTC
- [yes ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
if 2shotting with empty common shells and 1shotting with nuclear shells wasn't enough to be an issue i have this now:
common railgun, common shell, common compound N into the first limb after the head, 1shot decapitated, died to blood loss 15 seconds later.

**Steps To Reproduce**
try to replicate what i did in the video attached

**Version**
unstable v0.1400.4.0 windows

**Additional information**
https://user-images.githubusercontent.com/55637865/121539688-43a7f180-c9dc-11eb-9d05-fdc74fcabfd4.mp4

**Comment by Krzeszny** [comment] 2021-06-30 09:18
I do believe that your report has been ignored.
Maybe it's because you didn't use capital letters and proper grammar?

**Comment by itchyOwl** [comment] 2021-07-06 15:29
It can happen but the likelihood for it is quite low. We could lower the chance for it. But it's difficult to solve these kind of issues without changing the system to use hit points instead of probabilities.

**Comment by itchyOwl** [comment] 2021-07-06 16:33
I was able to reproduce it with slightly different steps:
- set severanceprobabilitymodifier for all the joints for something ridiculous like 100 to make sure the joints always break when hit
- disable enemy ai
- spawn endworm
- control endworm and move it horizontally
- control a crew member and equip the railgun
- teleport the endworm so that you can hit the side
- might require a couple of attempts
![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/7c1a87ad-632c-4167-80c5-d1e3db1a77b8)
![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/a1c064a1-e841-4220-af91-357b4a1557f4)

So it was like I suspected before: you can shoot between the armor segments, which is not really intentional. I'll adjust the colliders a bit. Let's see if it helps.

**Comment by itchyOwl** [comment] 2021-07-06 16:37
Extra: I think we could try making the bleeding a bit less deterministic: less than 100% chance for all the lethal "bleedingnonstop" afflictions.

**Comment by LePiromano** [comment] 2021-07-28 21:59
shot at a fully armored endworm like 50 times with explosive and common shells in very open angles with 9999 severanceprobabilitymodifier, didn't split once, i think it's all good now :)

**Comment by Rokvach** [comment] 2021-07-29 06:02
Closing

**Closed by Rokvach** 2021-07-29 06:02 UTC
Labels: Bug, Code
