### ISSUE TITLE
Crashing on search 

### ISSUE THREAD

**Issue by JSE323** [Regalis11/Barotrauma#2705] opened 2020-04-25 15:16 UTC
- [] I have searched the issue tracker to check if the issue has already been reported.

**Description**

**Steps To Reproduce**
disable
[crashreport (7).log](https://github.com/Regalis11/Barotrauma/files/4533319/crashreport.7.log)
 sandbox or missions in the server search function than scan for servers 

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).
0.9.9 windows 64

**Additional information**

**Comment by Regalis11** [comment] 2020-04-25 15:21
Duplicate of #2567

This happens due when trying to filter servers in the server list based on game mode. We've got a hotfix coming for this issue soon, but for now it should be possible to work around it by not trying to filter the server list. Sorry for the trouble!

**Closed by Regalis11** 2020-04-25 15:21 UTC
