### ISSUE TITLE
NullReference exception when trying to dispose ModSender in Quit() method

### ISSUE THREAD

**Issue by evilfactory** [Regalis11/Barotrauma#11286] opened 2023-02-19 23:20 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If you have mod downloads disabled, a null reference exception will be thrown every time the server closes.

### Reproduction steps

1. Start a server
2. Disable AllowModDownloads
3. Close the server

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Linux

### Relevant error messages and crash reports

```shell
Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void Quit()
Stack trace: 
   at Barotrauma.Networking.GameServer.Quit() in <DEV>/Barotrauma/BarotraumaServer/ServerSource/Networking/GameServer.cs:line 3989
   at Barotrauma.GameMain.CloseServer() in <DEV>/Barotrauma/BarotraumaServer/ServerSource/GameMain.cs:line 293
   at Barotrauma.GameMain.Run() in <DEV>/Barotrauma/BarotraumaServer/ServerSource/GameMain.cs:line 411
   at Barotrauma.Program.Main(String[] args) in <DEV>/Barotrauma/BarotraumaServer/ServerSource/Program.cs:line 82
```

**Comment by Regalis11** [comment] 2023-02-20 09:03
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10955

**Closed by Regalis11** 2023-02-20 09:03 UTC
