### ISSUE TITLE
when i play with friend..

### ISSUE THREAD

**Issue by DavidChiu0418** [Regalis11/Barotrauma#8041] opened 2022-01-15 04:32 UTC
![This is an image](https://truth.bahamut.com.tw/s01/202201/85863c0f4cd112a30f8e54073b1e3f75.JPG)
![This is an image](https://cdn.discordapp.com/attachments/735772120537366562/931567747161272350/unknown.png)
what happen? 🤕

**Comment by Regalis11** [comment] 2022-01-19 15:19
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7896

**Closed by Regalis11** 2022-01-19 15:19 UTC
