### ISSUE TITLE
Station not works when docking shuttle.

### ISSUE THREAD

**Issue by WildlandHerald** [Regalis11/Barotrauma#6404] opened 2021-08-05 01:11 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Station not works when shuttle is docked in campaign mode. Expected to work properly and let us to deliver resources that we bring.

**Steps To Reproduce**
- Start the mission in campaign mode,
- lead the actual submarine out and try to dock the shuttle.
- It will prompt if you want to leave  your "normal" submarine, click "yes"
- Shuttle will gracefully dock into a station but there wilk be no NPC's and light.
- Station are looking like it's not loaded at all, you have access only to the part of it.

**Version**
v0.13.3.11 Windows 11/ My friend had Windows 10

**Additional information**
It was a long way, like 4+ hours to get the resources... we ran out of power supply in the end and tried to deliver them on shuttle. Yet it not works with station properly and the game says nothing about it.

**Comment by Regalis11** [comment] 2021-11-09 13:52
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3604

**Closed by Regalis11** 2021-11-09 13:52 UTC
