### ISSUE TITLE
[0.9.902] Bots - Wasting large amount of medicines to heal

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2587] opened 2020-04-09 10:52 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots are now healing themselves and everyone when they're idle or during heal injury order even if the damage suffered is low and not warranting the full effect of the medicine used. They go through morphines and bandages like crazy to heal off the failed skill checks from repairing.

**Version**
0.9.902

**Comment by itchyOwl** [comment] 2020-04-17 08:04
I guess this was caused by bots trying to heal without the proper skills. I changed it so that they let the medics fo the job when there are any around. If there are no medics, they still try to heal themselves, but I adjusted the priorities, so it should happen less eagerly.

**Comment by Rokvach** [comment] 2020-05-11 13:52
No issues, closing.

**Closed by Rokvach** 2020-05-11 13:52 UTC
Labels: Bug, Code

**Comment by hubismal** [comment] 2020-05-11 15:23
a little bit late to comment on this but i think what kaillera meant was that bots should really only use medicine when you have 40 internal damage or whatever, and they currently use it when you only have like 10. I haven't seen them do this recently though.
