### ISSUE TITLE
Kastull's lower aft docking port (hatch) is missing a gap

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#5305] opened 2021-03-25 11:03 UTC
**Description**
Its lower aft hatch in the docking port is missing a gap for the small hull, resulting in abnormal behaviour with how the water flows.

![spot](https://user-images.githubusercontent.com/72674994/112463022-b7067380-8d9c-11eb-8c7c-c0f6dd7b89f8.jpg)
![spothull](https://user-images.githubusercontent.com/72674994/112463056-bff74500-8d9c-11eb-92f6-f381ec2c4b5f.jpg)

Found in : V0.1300.0.2

**Comment by itchyOwl** [comment] 2021-03-26 12:06
Fixed in Regalis11/Barotrauma-development@6c38508.

**Comment by Rokvach** [comment] 2021-03-29 14:35
Hatch leading to Kastrull drone is closed by default
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/19889a01-d5bb-4fcd-916e-caf93e10deca)

Water renders on top of the hatch
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/a5995c80-0020-4e8a-8f80-6eae17a3adfa)

**Comment by itchyOwl** [comment] 2021-03-29 15:59
Fixed in Regalis11/Barotrauma-development@5461953. The issue was due to accidentally disconnected wirings, which was caused by a bug in the editor (see #5373).

**Comment by Rokvach** [comment] 2021-03-29 17:43
Tested, no issues. Closing.

**Closed by Rokvach** 2021-03-29 17:43 UTC
Labels: Bug, Design
