### ISSUE TITLE
Dancing coilguns

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#4342] opened 2020-11-18 20:28 UTC
- [ yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Wreck coilguns are "dancing" even if the wreck isn't a thalamus, i've also seen people getting the issue with their own submarines when aiming at a certain spot.
**Steps To Reproduce**
I found the issue in a dugong wreck, i yet have to see if it happens in all wrecks.
**Version**
V0.1100.0.7

**Additional information**
I haven't seen it happening to railguns yet.

**Comment by Xeavas** [comment] 2020-11-19 04:53
Able to replicate using provided setup.
For the example to replicate for right side, alternate between buttons 1 and 2 with some pause between presses, should be able to replicate after some time, this was found when testing the fix for #4270 , and I suspect the issue is caused by said fix.

[coildance.zip](https://github.com/Regalis11/Barotrauma/files/5564443/coildance.zip)

**Comment by juanjp600** [comment] 2020-11-19 11:00
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1585e74af3762e015ac58d17acd1fe7403ce9fdd

**Comment by Rokvach** [comment] 2020-11-20 11:13
Wasn't able to reproduce, looks to be working correctly. Closing.

**Closed by Rokvach** 2020-11-20 11:13 UTC
Labels: Bug, Code
