### ISSUE TITLE
Combining two half-bricks of UEX or other explosive causes explosion.

### ISSUE THREAD

**Issue by Quilan** [Regalis11/Barotrauma#4058] opened 2020-10-11 14:24 UTC
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Combining two half-used bricks of UEX (or other explosives) causes a violent explosion. This only appears to happen if the total condition of both bricks is 100 or less, so one brick is deleted. This also appears to disable the ESC menu if the character is killed in the blast.

**Steps To Reproduce**
1: Open the sub editor and load a functional sub.
2: Add a brick of UEX to the sub in an accessible location.
3: Set the brick's condition to 50 or less.
4: Copy and paste this brick, so there are two bricks next to each other.
5: Press the "test sub" button.
6: As a character, walk to the UEX and pick up both bricks.
7: With both bricks in inventory, drag one brick onto the other to combine them.

Expected: One brick of UEX remains in inventory with the combined condition of both bricks.
Actual: Explosion occurs. ESC menu is disabled if you die.

**Version**
v0.10.5.1 (ReleaseWindows, revision 9e159b2148)

**Additional information**
Also tested with C-4, IC-4, and Composition N; these all explode when combined as above.

Discovered using the mod EK Armory which produces half-bricks of UEX when disassembling explosive darts, but the bug occurs in vanilla with other mods disabled.

Speculation: Event which causes explosion when UEX is destroyed also triggers when combining two bricks and one is removed from the game (due to having zero condition).

Attached screenshots: Half-bricks of UEX in inventory; one dragged over the other; effects of releasing LMB.

![20201011151956_1](https://user-images.githubusercontent.com/1065204/95681030-86a79000-0bd5-11eb-983d-95cf2ce1b54c.jpg)
![20201011152005_1](https://user-images.githubusercontent.com/1065204/95681032-89a28080-0bd5-11eb-99fc-9050a326d883.jpg)
![20201011152009_1](https://user-images.githubusercontent.com/1065204/95681035-8c04da80-0bd5-11eb-9764-92863c39e647.jpg)

**Comment by Regalis11** [comment] 2020-10-12 07:01
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3966

**Closed by Regalis11** 2020-10-12 07:01 UTC
