### ISSUE TITLE
Monsters bite through (alien ruin) walls

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#5109] opened 2021-02-20 13:13 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported. 
It might something have to do with issue **#4724**

**Description**
I got bitten (first time infected, second time not infected) by Husk through a destructible (but not damaged) alien ruins wall. I was about one body width from the walls (not touching them) in both cases. This happened twice at the same location, in two different spots, once when I was above a horizontal wall, once when I was next to a vertical wall.

**Steps To Reproduce**
???
This is not always reproducible.

**Version**
v0.12.0.3 Windows 20H2

**Additional information**

**Comment by itchyOwl** [comment] 2021-02-26 09:55
I don't believe this issue is related to #4724. I think the same thing can occasionally happen with any monster when the limb for some reason goes through a collider that should block it.

**Comment by itchyOwl** [comment] 2021-02-26 10:04
Actually this might be another issue, because the attack is actually on the head and not the tentacle.

**Comment by Krzeszny** [comment] 2021-03-26 21:00
> Actually this might be another issue, because the attack is actually on the head and not the tentacle.

It's not just Husk. It's all monsters.

**Comment by Krzeszny** [comment] 2021-03-30 17:17
One more thing. This seems to be connected with the bug that you can press buttons and interact with things through the walls. I'm not sure if it's a mod thing.

**Comment by Regalis11** [comment] 2021-04-13 09:12
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1768ebb1c3422148364fb3cc85f935ba67ba35b5

**Comment by Rokvach** [comment] 2021-04-20 10:08
Tested, wasn't able to reproduce. Seems to be working correctly. Closing.

**Closed by Rokvach** 2021-04-20 10:08 UTC
Labels: Bug, Code, Medium Prio
