### ISSUE TITLE
Inspiring Tunes affliction doesn't group with positive afflictions

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10595] opened 2022-11-27 13:01 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Below are two different player affliction bars. In both instances, Inspiring Tunes is not grouped with the rest of the positive afflictions. This could be because the affliction is "temporary", however I've observed it to be a constant buff which might be an issue in itself. 

![image](https://user-images.githubusercontent.com/105495756/204136557-2aa9db65-8d1c-4dab-93ec-3f7cb6658d37.png)
_Figure 1. Player 1's afflictions_

![image](https://user-images.githubusercontent.com/105495756/204136570-6390449a-fcf1-4839-a836-98da063017d4.png)
![image](https://user-images.githubusercontent.com/105495756/204136573-b472ed1f-7edb-4fe4-b53f-2c9d16f46676.png)
_Figures 2 and 3. Player 2's afflictions_

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-11-27 14:41
Doesn't seem to be specific to the faction branch

**Comment by Regalis11** [comment] 2022-11-28 09:01
> This could be because the affliction is "temporary", however I've observed it to be a constant buff which might be an issue in itself.

Yep, I intentionally left it out from the "automatically hidden" afflictions considering it's a temporary affliction, but if it's not, that seems like a bug.

**Comment by JeroonBosch** [comment] 2022-11-28 11:58
Looked into this. Only issue I found in the XML was maxstrength being defined as 15 rather than 10 (the talent only gives it a strength of 10). I tried out the grouping of talent afflictions, but it seemed to behave a bit strangely in general, not just Inspiring Tunes.

Inspiring Tunes was already marked correctly as a buff though, so maybe @3e849f2e5c has a better idea what's going on.

**Comment by Regalis11** [comment] 2022-11-28 14:56
> This could be because the affliction is "temporary", however I've observed it to be a constant buff which might be an issue in itself.

I could not find a way to reproduce this, the affliction seems to disappear after 10 seconds as intended. Could be that someone was using the talent repeatedly, keeping the affliction active? In any case, I enabled hiding it in https://github.com/Regalis11/Barotrauma-development/commit/d753e6cedd0c800463f882ccfb01c502f18eb544

**Comment by NilanthAnimosus** [comment] 2022-12-13 13:04
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/c74b9de1ded83ed269a2a470b9a849e9eda8aeaf, no issues found, closing.

Notes: Saw some minor flickering when repeatedly applied, but is unlikely related to this issue (but could be a sign of something else to look into later)

**Closed by NilanthAnimosus** 2022-12-13 13:04 UTC
Labels: Bug, Code, Design, Unstable
