### ISSUE TITLE
Cultist and Zealot robes hood clips through Exosuit

### ISSUE THREAD

**Issue by Mikeykoala** [Regalis11/Barotrauma#11648] opened 2023-03-24 01:14 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

started campaign and used cheats to spawn a cultist robe, zealot robe, and exosuit, upon donning the exosuit, the hood of these two clothes will clip through the exosuit.
![20230323190956_1](https://user-images.githubusercontent.com/128762026/227399239-a4b313b7-e188-4a1b-8c45-f77fa72c0be8.jpg)
![20230323191011_1](https://user-images.githubusercontent.com/128762026/227399243-98eb1b19-70a7-4888-83d4-fea0cd122c85.jpg)

### Reproduction steps

simply equipping cultist robes or zealot robes and an exosuit should recreate the bug.

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Mikeykoala** [comment] 2023-03-24 01:16
I noticed this issue posted about diving suits, which look fine with the robes, but the hood clips through the exosuit still.

**Comment by Regalis11** [comment] 2023-03-27 00:47
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11404

**Closed by Regalis11** 2023-03-27 00:47 UTC
