### ISSUE TITLE
Kicked out with error when spectating campaign

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#3104] opened 2020-06-15 16:06 UTC
[crashreport_object.log](https://github.com/Regalis11/Barotrauma/files/4781465/crashreport_object.log)
dumptofile is broke so i hope you like reading sub 720p text
![2020-06-15-110454_460x157_scrot](https://user-images.githubusercontent.com/47284081/84680373-3571e300-aef8-11ea-8235-d853a33d6fb1.png)
![2020-06-15-110507_459x222_scrot](https://user-images.githubusercontent.com/47284081/84680374-360a7980-aef8-11ea-9a4d-6c5061d99126.png)
![2020-06-15-110518_458x225_scrot](https://user-images.githubusercontent.com/47284081/84680375-360a7980-aef8-11ea-92e9-f6e3c2fef670.png)

**Comment by Regalis11** [comment] 2020-06-15 16:40
Duplicate of #3019

**Closed by Regalis11** 2020-06-15 16:40 UTC
