### ISSUE TITLE
Not component not working properly

### ISSUE THREAD

**Issue by bbalint105** [Regalis11/Barotrauma#4280] opened 2020-11-11 14:32 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The NOT component should actually send a "1" signal on the input signal "" (empty), but it will only send one at the input "0".
This makes the "check if(/empty/)" action basically impossible.

**Version**
0.10.6.2

**Additional information**
Fixing this issue would widen the use of both the NOT component by much, so as the relay-component possibilities.

**Comment by nullmaton** [comment] 2020-11-11 17:03
To be fair, you can accomplish this with a Signal Check Component. Just leave the target signal field empty, and set output to 1, and false output to 0.

**Comment by bbalint105** [comment] 2020-11-11 19:04
Tried, not working. Only working with the false output, alis the "not (/empty/)".
Checked the source code, the component doesnt recieves an update with empty string or something that.

**Comment by Working-Joe** [comment] 2020-11-11 21:37
This is not a bug as far as I'm aware. Note that there is a difference between an empty signal ("") or _no_ signal. Practically the only way to send out an empty signal is out of a mem with no value set. otherwise usually leaving a field blank will send no signal, not even an empty signal.  

The not will send no output if it receives no signal. If it receives an empty signal ("") it will send an output, that being 0.  

It is also possible to detect no signal by the way. An OR sends an output regardless of whether it receives a signal, so if it receives no signal it will always send its false output.

**Comment by Working-Joe** [comment] 2020-11-11 21:45
That being said, the description of the component being "Sends a signal when the input is NOT receiving a signal" is therefore technically incorrect. A better description might be "Inverts signals received at its input".

**Comment by bbalint105** [comment] 2020-11-11 22:06
Fair, fair.
Still, if they could merge the "" and the no-signal, making it checkable as nullmaton said above, that would solve many problem of mine. I suppose, many peoples overall.

**Comment by bbalint105** [comment] 2020-11-11 22:08
Or for example in the case only at the NOT component, just adding an update signal.
So if it gets no-signal at the input it just sends 1 in case it was updated manually on another input.

**Comment by Working-Joe** [comment] 2020-11-11 22:58
If one were to merge "" and no-signal this would mean that all components would be sending empty strings all the time. This is not really good for performance and will certainly break lots of existing circuits. Adding an update signal is probably not ideal either, because in that case you'd get an extra input that is often not used and may lead to more confusion. Perhaps a "continuous output" tickbox like the regex component has would be a better choice, since this could simply be off by default to not break previous machines.

**Comment by bbalint105** [comment] 2020-11-12 09:46
I still think that input would be used more often than an asin component over all. And it would not even take that much effort.
And it doesnt overwrite the update thing of the NOT component, just adds an alternative way to update it, avoiding these...
Unpleasant "features".

**Comment by Regalis11** [comment] 2020-11-23 13:49
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/de74c06058ebea1a30d3b6562d9c182384d09efc: Added an option to make the component continuously output "1" when it's not receiving a signal, and made the component interpret empty signals (empty as in "") as "0".

**Comment by bbalint105** [comment] 2020-11-23 14:49
Hahaha, I have no idea how github works, may I close the issue now, or just keep it open?

**Comment by juanjp600** [comment] 2020-11-23 18:56
We typically keep issues open until they can be reviewed by QA.

**Comment by Xeavas** [comment] 2020-12-11 17:14
[0.1200.0.0] - No issues, working correctly 👍

**Comment by Rokvach** [comment] 2020-12-11 17:16
Closing

**Closed by Rokvach** 2020-12-11 17:16 UTC
Labels: Code
