### ISSUE TITLE
Thorianite Ore Drop Bug

### ISSUE THREAD

**Issue by TrulyRudly** [Regalis11/Barotrauma#5055] opened 2021-02-13 22:02 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported. A quick search yielded no results.

**Description**
I have taken two missions recently to mine Thorianite and on both occasions, I was able to pick up all but one of the Thorianite ore after detaching it from the cave wall. I select it with left click and it enters the stack in my hotbar (never exceeding 6) but one specific piece on both occasions would then, seconds later, fall out of my inventory. This would occur no matter how many times I attempted to pick it up, and it seemed to be specific to that particular piece of ore as on one of the two occasions, I found more ore and was able to mine and collect it successfully.

**Steps To Reproduce**
I don't know the exact cause, as I was simply mining Thorianite on mining missions, but it occurred on both of the missions I went on, so I imagine it is common enough to occur if you mine enough Thorianite.

**Version**
I am playing on Windows (steam specifically) and I am fully updated as of 2/13/21, the number in the bottom left of the main menu is v0.12.0.2

**Additional information**
I think I provided all the necessary context above, thanks for your time and for such an awesome game!

**Comment by Petrusion** [comment] 2021-02-22 19:10
I just had the same problem today and I can say it is not exclusive to Thorianite. I was mining Pyromorphite and 2 out of 10 pieces I had to mine were doing this exact same thing. We ended up failing because of this.

**Comment by Regalis11** [comment] 2021-04-01 11:29
This most likely happens when the item is picked up client-side but fails to be picked up server-side (for example due to a discrepancy in the character's position or the item's deattach state). This would enable the item's physics body client-side, but it's still disabled server-side, and the server doesn't try to correct the positions of items whose physics bodies are disabled.

This can be reproduced as follows:
1. Deattach a mineral with the plasma cutter but don't pick it up yet.
2. Switch to the sub editor and move the deattached item a bit.
3. Switch back to the game and try to pick up the item.

**Comment by Udrakan** [comment] 2021-04-11 13:11
We have mined 2 caves worth of minerals yesterday on steam P2P server without desync, but they weren't mission related. Maybe those cause the problem.

**Comment by Rokvach** [comment] 2021-04-14 22:22
Tested, working correctly. Closing.

**Closed by Rokvach** 2021-04-14 22:22 UTC
Labels: Bug, Code, Networking
