### ISSUE TITLE
Storage Container and water

### ISSUE THREAD

**Issue by nektototo** [Regalis11/Barotrauma#10086] opened 2022-10-15 13:23 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

every time i drop the Storage Container underwater it starts to fall quickly and falls behind the textures

### Reproduction steps

1.Start a multiplayer game
2.Grab the Storage Container and swim out of the sub
3.Just throw it away

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-10-16 09:08
Duplicate of https://github.com/Regalis11/Barotrauma/issues/9988. We unfortunately still haven't found a way to get this to happen, if you happen to have any more clues on the specific situation it occurs in, posting those in the existing ticket would help a lot in diagnosing this. Thank you and sorry for the inconvenience!

**Closed by Regalis11** 2022-10-16 09:08 UTC
