### ISSUE TITLE
Complete multiplayer campaign desync

### ISSUE THREAD

**Issue by TheNDGhost** [Regalis11/Barotrauma#4874] opened 2021-01-22 23:10 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.
- [x] This is similar but also worse than issue #4081

**Description**
During a MP campaign with 5 players, one player disconnected whilst we at station New Nanhui as he had to go. We selected to continue doing a Moloch extermination mission. When we loaded into the new round, I as the host, and our captain, spawned with all our items stripped and dropped at our feet. The other 2 players spawned in as spectator. This is similar to issue 4081, but we were not able to fix it. 

The sub was completely desynced. I put on my items as did the captain and we both just saw/heard the other person as if they were still stripped. I turned on the reactor, but the captain couldn't do anything because his side said there was no power. 

We attempted to exit and reload with all 4 crew from server lobby, same issue. Completely desynced and 2 players in spectator.
We attempted to exit to main menu and reload from there, same issue.
Next we attempted to dock into station to end the round, loaded into station still desynced, all our items on the floor, 2 players as spectator and ALL npcs were stripped of items as well.

I'll provide the save in the hopes it will help as this is a campaign ending bug.

**Version**
Windows 10 OS - game version Barotrauma v0.11.0.10 (ReleaseWindows, branch release, revision dc7157029e)

[Save.zip](https://github.com/Regalis11/Barotrauma/files/5859113/Save.zip)

**Comment by Regalis11** [comment] 2021-01-25 07:31
This seems to be a duplicate of https://github.com/Regalis11/Barotrauma/issues/4460, fix coming up in the next update and already included in the latest Unstable build.

I went ahead and fixed the save file so you can continue playing before the fix is out: 
[Save.zip](https://github.com/Regalis11/Barotrauma/files/5864877/Save.zip)

**Closed** 2021-01-25 07:31 UTC
Labels: Bug, Code, Duplicate
