### ISSUE TITLE
[Dev Version] Mic popup error doesn't go away when clicking "ok"

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#1271] opened 2019-03-13 01:56 UTC
I click host server, the mic error message shows up. I don't care, so I click "ok" to get rid of it. It doesn't go away. That's the bug, in all practicality.

**Comment by NilanthAnimosus** [comment] 2019-03-13 06:14
this sounds like a duplicate of #1262 perhaps? is this different in any specific way?

As a note, the host is still effectively a client, connecting to a second instance of barotrauma (the dedicated) locally.

**Comment by Regalis11** [comment] 2019-03-13 09:47
Duplicate of #1262

**Closed by Regalis11** 2019-03-13 09:47 UTC
