### ISSUE TITLE
Welder and cutter looks strange when using them in a area where there's a gap

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#5838] opened 2021-05-19 09:36 UTC
Noticed in dev but I believe this is a old issue

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/15f699f1-7c45-4b2e-8bfa-d092c9d0e1cf)
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/1b778f95-03f5-4d53-bd8d-36cf82baa365)

**Comment by Regalis11** [comment] 2021-05-19 09:38
Duplicate of https://github.com/regalis11/barotrauma/issues/4350

**Closed by Regalis11** 2021-05-19 09:38 UTC
Labels: Bug, Code
