### ISSUE TITLE
[Unstable] Breaking Mudraptor armor makes them disappear

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10337] opened 2022-11-12 00:45 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

https://user-images.githubusercontent.com/73229309/201448237-30158c0b-9473-43d9-91f3-6b7fb8fdd4e0.mp4

### Version

Faction/endgame test branch

**Comment by Regalis11** [comment] 2022-11-13 16:36
Couldn't find a way to reproduce this

**Comment by itchyOwl** [comment] 2022-11-16 11:44
Me neither. Neither single player nor mp. Which one was that? And can you repro it or was it just a single occasion?

**Comment by Regalis11** [comment] 2022-11-23 17:29
Was most likely caused by some broken talent that set the affliction resistance to 1.0f / 0.0f, which would cause the strength of the affliction to be NaN, which in turn would mess up the limb tinting logic and make the character invisible. See https://github.com/Regalis11/Barotrauma-development/commit/a35e6b39b98fa27ee236d6e8576aa075470b89c6

**Comment by NilanthAnimosus** [comment] 2022-12-08 10:39
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/24aad1892591b07abbfdda1680c759abec9ffe9e

I was unable to replicate the issue (with a variety and all talents), nor see anything strictly fixing it (such as the error being triggered to console in a debug build) so not sure if to close this ticket or not.

**Comment by Rokvach** [comment] 2023-01-02 10:58
There hasn't been any sightings of this or other issues relating to this, seems to be working correctly. closing.

**Closed by Rokvach** 2023-01-02 10:58 UTC
Labels: Bug, Need more info, Code, Unstable
