### ISSUE TITLE
Vannilla/Official Submarines Bug Discoveries Orca2/R-29

### ISSUE THREAD

**Issue by XallZall** [Regalis11/Barotrauma#8009] opened 2022-01-10 07:43 UTC
Just signed up to Github, first time using it so apologies if this has been already addressed in advance.

**Description**
I discovered a few AI/path finding related bugs that I wish to report on:

Orca2:
There is an issue with the flooding Alarm, once the submarine takes on flooding and triggers the flood alarm it fails to turn off and remains constantly active for the entire voyage. Its very annoying and currently one has to un-wire it.
![image](https://user-images.githubusercontent.com/97430807/148731700-4d351adf-2025-4e3d-80ce-767c20462388.png)
(Orca2 Command Room)

Either there is a issue with the OR Components or Water detectors where one of them remains constantly on, or a placement error of one of the water detectors where its constantly detects water for some reason.

I noticed this mainly when attacked from above, so either some water remains stuck in the top compartments, or since there is drain ducts it remains stuck below and is not pumped out properly or a detector or an OR component is not working properly.

R-29 Transport:
There is a path finding issue to the forward airlock if the Hatch there is damaged, the AI try to fix the Hatch and occasionally get stuck in the Cargo Bay, running against the wall which is closest to the Hatch.
![image](https://user-images.githubusercontent.com/97430807/148729950-ac9bd07d-a96b-41d4-95e4-1ada55095ea0.png)
(R-29 Forward Airlock)

Next, if the docking Hatch manages to get damaged, and if the room is not flooded, the AI needs to use a Wrench to fix the Hatch, but since the room is not flooded and the Hatch is to high from the ground level, they cannot reach it and just seem to stare at it.
![image](https://user-images.githubusercontent.com/97430807/148730304-6d2f90e3-c846-4f63-bf70-0498ab646741.png)
(R-29 Docking Port)

I make custom submarines myself and did actually run into this problem myself at some point, the issue is that the Player and the AI WILL FALL OFF a ladder if they attempt to repair anything.
I recommend doing a fix on this by allowing repairs to take place while being on a ladder so that one does not fall off it.

As I mentioned that I came across this issue myself, my fix was by having a slightly raised platform and giving that platform Waypoints so that the AI or Player can climb the ladder and if they fall they fall onto the platform and the repairs are not interrupted and thus can finish the repair and fix the hatch.
Below is a direct example of how I did it, so if the code within the game for whatever reason does not allow repairing while on a ladder the submarines that have hatches out of reach need to be retrofitted or giving a platform where they can continue repairs:

![image](https://user-images.githubusercontent.com/97430807/148729783-5c827e63-5469-4f97-b96a-5d0c5ad62e44.png)
(Custom Submarine, Basic Platform + Waypoints as a fix)

**Additional discoveries:**
With the latest updates the Bots do a a great job putting the Diving suits back when they are done using them rather than dropping them at random locations, I would request that they do the same with Diving Masks, allot of the time my crew end up all wearing diving masks, like indefinitely, its pretty annoying as all the diving masks are removed from their place (usually supply cabinets meant for cases of emergencies) and everyone is masked up forever with empty oxygen tanks to top it off.

Loving the game and updates otherwise, keep up the good work!

**Version: 
Latest Build: 0.15.22.1 / Steam / Windows 10**

**Comment by danielasteljoki** [comment] 2022-01-24 08:39
Orca2 flood alarm was caused by oxygen generator compartment. It's hull was placed so that a small amount of water remained. I couldn't get the flood alarm to sound constantly anymore so I assume adjusting the hull/pump fixed it.

R-29 issues were graciously fixed by rav2n and applied in fbb595a.

**Comment by Rokvach** [comment] 2022-01-27 12:31
Tested, no issues. Closing.

**Closed by Rokvach** 2022-01-27 12:31 UTC
Labels: Bug, Design, Unstable
