### ISSUE TITLE
Crash shortly after game start.

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#2305] opened 2020-02-14 21:16 UTC
I was minimized so I don't know what happened. Attached the log. Would attach the core, but it doesn't seem to create one anymore.

[crashreport (5).log](https://github.com/Regalis11/Barotrauma/files/4206855/crashreport.5.log)

**Comment by Regalis11** [comment] 2020-02-15 22:25
Duplicate of #2182

**Closed by Regalis11** 2020-02-15 22:25 UTC
