### ISSUE TITLE
Wreck salvage mission not a success when logbook is in crew inventory

### ISSUE THREAD

**Issue by Mezzokoko** [Regalis11/Barotrauma#3531] opened 2020-08-09 00:08 UTC
**Description**
Picking up the log book in a wreck salvage mission will trigger the "objective complete" notification, but if kept on a character's person until docking the station, it will still fail the mission. Either carrying it on a living crew member should count as a mission success, or the behavior should be reverted to having the objective be in a container on the ship, to clearly communicate to players when the objective condition is fulfilled.

**Version**
Barotrauma v0.10.4.0 (ReleaseWindows, branch release, revision 20132d25fb)

**Additional information**
https://www.twitch.tv/videos/704390018 (I backed the vod up incase it expires)

1:59:36 - picking up the logbook
2:06:27 - ending the mission with failure

[ServerLogs.zip](https://github.com/Regalis11/Barotrauma/files/5046583/ServerLogs.zip)

**Comment by Kaillera** [comment] 2020-08-09 00:54
From the video you can see the logbook was still in the wreck near the end.

**Comment by mygamingaccount** [comment] 2020-08-09 22:29
Accurate title: Wreck salvage logbook does not count as being inside the player's inventory if it is placed into a toolbox

**Comment by Regalis11** [comment] 2020-08-16 18:38
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3365

**Closed by Regalis11** 2020-08-16 18:38 UTC
Labels: Bug, Code
