### ISSUE TITLE
Sometimes when transferring items between inventory and container the item drops instead.

### ISSUE THREAD

**Issue by Momiro** [Regalis11/Barotrauma#558] opened 2018-08-01 15:54 UTC
The effect seems inconsistent but is more common when double clicking to transfer.

**Comment by thegrb93** [comment] 2018-08-01 16:34
This happens to me a lot too.

**Comment by rico6822** [comment] 2018-08-01 22:14
Basically:
If you put an item into non-mobile container or crafting device it drops on the ground. Sometimes you cannot even take it as it drops again.

**Comment by thegrb93** [comment] 2018-08-02 00:39
Reactor rods have this happen a lot as well.

**Comment by thegrb93** [comment] 2018-08-04 08:40
Still isn't fixed unfortunately

**Comment by thegrb93** [comment] 2018-08-04 08:47
In addition wiring is completely broken. Attempting to wire causes all wires to become unwired.

**Comment by thegrb93** [comment] 2018-09-11 04:06
Video:
https://www.dropbox.com/s/9bzjjcfsqda7xuh/2018-09-10%2022-47-33.flv

**Comment by thegrb93** [comment] 2018-09-12 15:11
Cool. I'll try it out once it's live.

**Comment by Regalis11** [comment] 2019-05-23 13:10
Another attempt to fix this: 5c06210. I'm pretty confident it's fixed now: we found out that it's easy to reproduce by moving items around in the inventory while inside a sub that's moving fast. Haven't been able to reproduce it anymore after 5c06210.

**Comment by Rokvach** [comment] 2019-05-23 18:40
I couldn't reproduce this with my previous method of testing the issue, so I can only assume that it is fixed now, closing.

**Closed by Rokvach** 2019-05-23 18:40 UTC
Labels: Bug, Code, Needs testing, Networking-related
