### ISSUE TITLE
Server Browser Content Package List

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#6124] opened 2021-06-19 20:58 UTC
![image](https://user-images.githubusercontent.com/47284081/122655312-ee3cb480-d140-11eb-99d6-c50afd5f234c.png)
This might as well be a bug because of how awful it is. The content package list is absolutely useless (especially on lower resolutions) when servers sometimes have around 15 mods turned on. Combined with the fact that the scrolling resolution is low (and seems to stay the same even when the list gets longer) means that scrolling down one unit skips like 3 content packages on larger lists (making a bunch of content packages unviewable on the list).

**Comment by Regalis11** [comment] 2021-07-05 10:31
Duplicate of https://github.com/Regalis11/Barotrauma/issues/5943

**Closed by Regalis11** 2021-07-05 10:31 UTC
