### ISSUE TITLE
Crash when starting Campaign in both single and multiplayer

### ISSUE THREAD

**Issue by kazimierz3000** [Regalis11/Barotrauma#1847] opened 2019-10-31 03:42 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
My game crashes immediately, or within a few seconds of loading the campaign in both single and multiplayer.  I can see the campaign menu and am sometimes able to use it for a few seconds prior to the crash.  My Windows 10 and GPU drivers are up to date, and I've reinstalled the game multiple times.

**Steps To Reproduce**
I'm able to reproduce the issue every single time I launch the campaign.

**Version**
v0.9.4.0 
Windows 10 1903

**Additional information**
Barotrauma Client crash report (generated on 10/29/2019 9:30:25 PM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

84DD5D9E1F73686017E1AF98E05E0122

Game version 0.9.4.0
Graphics mode: 3440x1440 (BorderlessWindowed)
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.NetLobbyScreen
SteamManager initialized
Client (Round hadn't been started)

System info:
    Operating system: Microsoft Windows NT 10.0.18362.0 64 bit
    GPU name: NVIDIA GeForce GTX 1080 Ti
    Display mode: {Width:3440 Height:1440 Format:Color AspectRatio:2.388889}
    GPU status: Normal

Exception: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.

Device removed reason: HRESULT = 0x887A0006
Target site: Void CheckError()
Stack trace: 
   at SharpDX.Result.CheckError()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent() in D:\Repos\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 1010
   at Microsoft.Xna.Framework.SdlGamePlatform.Present() in D:\Repos\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 245
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in D:\Repos\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in D:\Repos\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 511
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in D:\Repos\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in D:\Repos\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Barotrauma.Program.Main(String[] args) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\Program.cs:line 41

Last debug messages:
[10/29/2019 9:30:25 PM] Loading the preview image of the submarine "Dugong" failed. The file may be corrupted. {HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.
}
   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   at Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture() in D:\Repos\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\Texture2D.DirectX.cs:line 403
   at Microsoft.Xna.Framework.Graphics.Texture2D.PlatformSetData[T](Int32 level, T[] data, Int32 startIndex, Int32 elementCount) in D:\Repos\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\Texture2D.DirectX.cs:line 75
   at Microsoft.Xna.Framework.Graphics.Texture2D.SetData[T](T[] data) in D:\Repos\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\Texture2D.cs:line 205
   at Barotrauma.CrossThread.RequestExecutionOnMainThread(TaskDelegate deleg) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\Utils\CrossThread.cs:line 61
   at Barotrauma.TextureLoader.FromStream(Stream fileStream, Boolean preMultiplyAlpha, String path) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\Utils\TextureLoader.cs:line 102
   at Barotrauma.Submarine..ctor(String filePath, String hash, Boolean tryLoad) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\Map\Submarine.cs:line 422
[10/29/2019 9:29:43 PM] Successfully retrieved public IP: 108.6.31.57
[10/29/2019 9:29:43 PM] Lobby created!
[10/29/2019 9:29:13 PM] Received a disconnect message (ServerFull/)
[10/29/2019 9:29:07 PM] Received a disconnect message (ServerFull/)
[10/29/2019 9:29:02 PM] Received a disconnect message (ServerFull/)
[10/29/2019 9:28:56 PM] Received a disconnect message (ServerFull/)
[10/29/2019 9:28:51 PM] Received a disconnect message (ServerFull/)
[10/29/2019 9:28:45 PM] Received a disconnect message (ServerFull/)
[10/29/2019 9:28:39 PM] Received a disconnect message (ServerFull/)
[10/29/2019 9:28:34 PM] Received a disconnect message (ServerFull/)
[10/29/2019 9:28:28 PM] Received a disconnect message (ServerFull/)
[10/29/2019 9:28:23 PM] Received a disconnect message (ServerFull/)
[10/29/2019 9:28:17 PM] Received a disconnect message (ServerFull/)
[10/29/2019 9:28:02 PM] OpenAL Soft on Microphone (HD Pro Webcam C920) 46
[10/29/2019 9:28:02 PM] OpenAL Soft on Microphone (Realtek High Definition Audio) 57
[10/29/2019 9:27:55 PM] Received a disconnect message (ServerFull/)
[10/29/2019 9:27:50 PM] Received a disconnect message (ServerFull/)
[10/29/2019 9:27:44 PM] Received a disconnect message (ServerFull/)
[10/29/2019 9:26:47 PM] OpenAL Soft on Microphone (HD Pro Webcam C920) 46
[10/29/2019 9:26:47 PM] OpenAL Soft on Microphone (Realtek High Definition Audio) 57
[10/29/2019 9:26:23 PM] Logged in as Kazimierz3000 (SteamID STEAM_1:1:15035172)

**Comment by Regalis11** [comment] 2019-11-01 08:20
Duplicate of #1826

**Closed by Regalis11** 2019-11-01 08:20 UTC
