### ISSUE TITLE
Normal fabricators unoptimized?

### ISSUE THREAD

**Issue by adamkad1** [Regalis11/Barotrauma#6829] opened 2021-10-04 19:01 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Fabricator causes lag when linked to a locker/container, the more filled it is, the laggier it gets. Though it's fairly negligible with vanilla lockers (since they are kinda small), if you mod in a larger locker, it does get noticeable.  Medical fabricators don't however.  I filled a 200 slot container and linked medfab still didn't lag

**Steps To Reproduce**
Get a big container, preferably modded since  it isn't very noticeable with vanilla, link it to a normal fabricator
Fill it with stuff
Open fabricator 
LAG

**Version**
V0.14.9.1 (ReleaseWindows, branch release revision df0088ca33)

**Additional information**
I dunno what else

**Comment by Regalis11** [comment] 2021-10-05 06:55
Duplicate of https://github.com/Regalis11/Barotrauma/issues/6735

**Closed by Regalis11** 2021-10-05 06:55 UTC

**Comment by adamkad1** [comment] 2021-10-05 17:18
> Duplicate of #6735

How did i miss that
