### ISSUE TITLE
Outpost NPC that turned into HumanHusk still have their divine protection from damage

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3695] opened 2020-09-03 11:57 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Outpost NPC that turned into HumanHusk (When they infect each other from the husk event for instance) still have their divine protection from damage. Makes it hard to kill them since they don't bleed out. It's easy to farm weapon levels off each of them since they can take 300 damage before death, and you can keep attacking a limb that's already capped for more EXP.

**Version**
0.10.4 ~ 0.10.501

**Comment by Regalis11** [comment] 2020-09-03 13:52
Could not reproduce, they seem to take a normal amount of damage (which should be the case, since the humanhusk is technically a completely new character, and there should be no way for the health multiplier to carry over to it). By humanhusk do you mean the NPC after it gains the "stinger", or the actual hostile humanhusk creature that spawns when the NPC dies?

**Comment by EtiamNullam** [comment] 2020-09-04 13:00
All human-husk always heal bleeding quickly on its own, just like mudraptor but even stronger. Maybe they seemed more tanky because of body armor.

**Comment by Regalis11** [comment] 2020-10-20 09:20
No known steps to repro, closing

**Closed by Regalis11** 2020-10-20 09:20 UTC
Labels: Bug, Code, Need more info
