### ISSUE TITLE
Unknown Crash to me

### ISSUE THREAD

**Issue by Abobus123457890** [Regalis11/Barotrauma#7966] opened 2021-12-31 15:42 UTC
Barotrauma Client crash report (generated on 31.12.2021 18:38:05)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

0120CFF13F68A29ABC62BE1077A0F8E0

Game version 0.15.12.0 (ReleaseWindows, branch release, revision 575e12eab6)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.MainMenuScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce GTX 750 Ti
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,7777778}
    GPU status: Normal

Exception: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Экземпляр устройства GPU приостановлен. Для определения соответствующего действия используйте GetDeviceRemovedReason.
 (SharpDX.SharpDXException)
Device removed reason: HRESULT = 0x887A0005
Target site: Void CheckError()
Stack trace: 
   at SharpDX.Result.CheckError()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 1017
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 511
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 60

Last debug messages:
[31.12.2021 18:37:39] (Msg) SDR RelayNetworkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[31.12.2021 18:37:39] (Msg) Ping location: sto2=51+5,sto=54+5/51+5,ams=81+8/71+5,waw=97+9/72+5,fra=71+7/73+5,lhr=95+9/75+5,par=93+9/82+5,vie=89+8/83+5,mad=101+10/102+5,iad=174+17/157+7,sgp=246+24,gru=/327+27
[31.12.2021 18:37:39] (Msg) Ping measurement completed
[31.12.2021 18:37:39] (Debug) Destroying relay 'bom#41 (155.133.233.99:27017)' because initial_ping_timeout
[31.12.2021 18:37:39] (Debug) Destroying relay 'gru#402 (205.185.194.212:27060)' because initial_ping_timeout
[31.12.2021 18:37:36] (Debug) Destroying relay 'gru#176 (205.185.194.50:27041)' because initial_ping_timeout
[31.12.2021 18:37:36] (Debug) Destroying relay 'bom#37 (155.133.233.98:27051)' because initial_ping_timeout
[31.12.2021 18:37:34] (Verbose) Communications with routing cluster 'seo' established.
[31.12.2021 18:37:34] (Verbose) Communications with routing cluster 'tyo' established.
[31.12.2021 18:37:34] (Verbose) Communications with routing cluster 'tyo1' established.
[31.12.2021 18:37:34] (Verbose) Communications with routing cluster 'syd' established.
[31.12.2021 18:37:34] (Verbose) Communications with routing cluster 'sgp' established.
[31.12.2021 18:37:34] (Verbose) Communications with routing cluster 'scl' established.
[31.12.2021 18:37:34] (Verbose) Communications with routing cluster 'jnb' established.
[31.12.2021 18:37:34] (Verbose) Communications with routing cluster 'lim' established.
[31.12.2021 18:37:34] (Verbose) Communications with routing cluster 'maa' established.
[31.12.2021 18:37:34] (Verbose) Communications with routing cluster 'sea' established.
[31.12.2021 18:37:34] (Verbose) Communications with routing cluster 'eze' established.
[31.12.2021 18:37:34] (Verbose) Communications with routing cluster 'lax' established.
[31.12.2021 18:37:34] (Verbose) Communications with routing cluster 'waw' established.
[31.12.2021 18:37:34] (Verbose) Communications with routing cluster 'vie' established.
[31.12.2021 18:37:34] (Verbose) Communications with routing cluster 'hkg' established.
[31.12.2021 18:37:34] (Verbose) Communications with routing cluster 'ord' established.
[31.12.2021 18:37:34] (Verbose) Communications with routing cluster 'sto' established.
[31.12.2021 18:37:34] (Verbose) Communications with routing cluster 'sto2' established.
[31.12.2021 18:37:33] (Verbose) Communications with routing cluster 'dxb' established.
[31.12.2021 18:37:33] (Verbose) Communications with routing cluster 'mad' established.
[31.12.2021 18:37:33] (Verbose) Communications with routing cluster 'dfw' established.
[31.12.2021 18:37:33] (Verbose) Communications with routing cluster 'lhr' established.
[31.12.2021 18:37:33] (Verbose) Communications with routing cluster 'par' established.
[31.12.2021 18:37:33] (Verbose) Communications with routing cluster 'iad' established.
[31.12.2021 18:37:33] (Verbose) Communications with routing cluster 'atl' established.
[31.12.2021 18:37:33] (Verbose) Communications with routing cluster 'ams' established.
[31.12.2021 18:37:33] (Verbose) Communications with routing cluster 'fra' established.
[31.12.2021 18:37:33] (Msg) SDR RelayNetworkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[31.12.2021 18:37:33] (Msg) Performing ping measurement
[31.12.2021 18:37:33] (Msg) Got SDR network config.  Loaded revision 364 OK
[31.12.2021 18:37:33] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[31.12.2021 18:37:18] Attempting to open ALC device "OpenAL Soft on Headphones (High Definition Audio Device)"
[31.12.2021 18:37:17] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[31.12.2021 18:37:16] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[31.12.2021 18:37:14] Logged in as Hailrake (SteamID STEAM_1:1:438080810)

**Comment by Regalis11** [comment] 2022-01-03 08:09
Duplicate of https://github.com/Regalis11/Barotrauma/issues/1833

**Closed by Regalis11** 2022-01-03 08:09 UTC
Labels: Bug, Code, Crash
