### ISSUE TITLE
Putting the deep-sea suit back in place by bots

### ISSUE THREAD

**Issue by Cyrunn** [Regalis11/Barotrauma#8034] opened 2022-01-14 00:35 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I've noticed with a friend that sometimes bots when there is an accident fly to get suits and after finishing repairs and returning to normal they walk around in them until they run out of oxygen and then throw them on the ground. And they don't always carry them to their place, they just lie there until we pick them up ourselves.

**Steps To Reproduce**
I just think to set them up so that when the hull repairs are completed where there is no more water they bring them back to the rack instead of walking around in them until they finally lose their oxygen hah.

**Version**
v0.15.23.0 Windows 10

**Additional information**
In a multiplayer campaign, My friend is the host. Hosting through Steam.

**Comment by Regalis11** [comment] 2022-01-14 08:12
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7822

**Closed by Regalis11** 2022-01-14 08:12 UTC
