### ISSUE TITLE
[Unstable] Walls sending error messages on loading/copying

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#11646] opened 2023-03-23 20:53 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Some walls send error messages when loading or copy-pasting them

Load Camel in sub editor and try cloning those walls

![image](https://user-images.githubusercontent.com/73229309/227356574-0b169508-f8b7-4b3c-ab2a-8e1760787fe1.png)

![image](https://user-images.githubusercontent.com/73229309/227356528-e32d4053-af25-49c1-bca9-34b7f8fbe5a0.png)

### Version

Unstable (v1.1.3.0)

**Comment by Regalis11** [comment] 2023-03-27 00:59
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11520

**Closed by Regalis11** 2023-03-27 00:59 UTC
