### ISSUE TITLE
"Defense bot ammunition rounds" is in "Misc" category, not in "Weapon"

### ISSUE THREAD

**Issue by mygamingaccount** [Regalis11/Barotrauma#12273] opened 2023-07-02 23:01 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://github.com/Regalis11/Barotrauma/assets/68995233/20f0c570-0a1d-419a-a44c-1b834d2a0912)

### Reproduction steps

It has ammunition in its name so it is ammo, no?

### Bug prevalence

Happens every time I play

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment] 2023-07-03 07:44
Duplicate of https://github.com/Regalis11/Barotrauma/issues/12025

**Closed by Regalis11** 2023-07-03 07:44 UTC
