### ISSUE TITLE
Crash on left-clicking out of wiring panel while re-wiring existing wire

### ISSUE THREAD

**Issue by SkylerLLewis** [Regalis11/Barotrauma#4536] opened 2020-12-15 18:40 UTC
- [ X ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Crash on left-clicking out of wiring panel while re-wiring existing wire.

**Steps To Reproduce**
Wire two things together. Create a loose wire, either by deleting one wire or making it loose in the wiring panel. Double click on the wire, and wire it to something else. Then, left-click outside of the wiring panel.

**Version**
Linux, 0.11.0.9, revision c60afcc03b

**Additional information**
[crashreport (7).log](https://github.com/Regalis11/Barotrauma/files/5697859/crashreport.7.log)

**Comment by Regalis11** [comment] 2020-12-16 11:34
I wasn't able to reproduce the crash with these exact steps, but got it to occur by doing the following:
1. Connect a wire from an item to another. Make sure to add several nodes to the wire.
2. Create a loose wire by deleting one of the connected items or by disconnecting the wire in the connection panel.
3. Double-click on the node at the disconnected end of the wire to select the wire.
4. Right-click a couple of times to remove some of the nodes.
5. Connect the wire to another item.
6. Right-click outside the connection panel interface to deselect it.

Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c0a9b8c960d98f9753a2542031df9833620239f6

**Comment by Rokvach** [comment] 2020-12-18 11:59
Tested, wasn't able to reproduce the crash. Seems to be working correctly. Closing.

**Closed by Rokvach** 2020-12-18 11:59 UTC
Labels: Bug, Code, Crash
