### ISSUE TITLE
Canvas Crashes Constantly (Divide by Zero)

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#3811] opened 2020-09-11 21:54 UTC
[Crash]
On spraying paint, sometimes picking up the paint can, and generally doing anything that involves the canvas (even just transitioning or initializing levels) the game crashes. This is in sub editor test, and an outpost in SP campaign respectively. Seems unreported, and crashlog says something about dividing by zero so may have to do with how my machine handles numbers.
[crashreport (113).log](https://github.com/Regalis11/Barotrauma/files/5211627/crashreport.113.log)
[crashreport (114).log](https://github.com/Regalis11/Barotrauma/files/5211628/crashreport.114.log)

**Comment by Regalis11** [comment] 2020-09-13 14:54
This seems to happen when there are no grime sprites (= the sprites that are used to render paint and dirt on the walls) defined in the last loaded decal config file. Do some of the mods you're using add new types of decals or override the vanilla decal configs?

**Comment by Regalis11** [comment] 2020-09-13 15:16
If this was caused by a mod modifying the decals, https://github.com/Regalis11/Barotrauma-development/commit/076b0602d01b7218bdd9db988dce6c70c821ee16 should fix it.

**Comment by hubismal** [comment] 2020-09-14 17:06
my mod adds some extremely vulgar decals but I disabled it before loading up the editor. I assume it was still loaded into the game. it now works when i start the game with no mods enabled, so this was the problem, thanks.

**Comment by Rokvach** [comment] 2020-09-15 15:10
Confirmed working, closing.

**Closed by Rokvach** 2020-09-15 15:10 UTC
Labels: Bug, Code, Crash
