### ISSUE TITLE
Planter pots will light up in your hand, without a seed inside

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#11372] opened 2023-02-25 23:39 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Simply, as a small planter pot spawns, the light will be disabled as normal. However, if picked up and equipped, the light will enable as if a seed was put inside, though there wasnt and it can be placed as normal. The fact that it lights up just from holding it seems odd and unintentional. 
![image](https://user-images.githubusercontent.com/104232152/221384532-28d34a75-c107-4e47-8aaf-afafe7a8a350.png)
Also, as a side issue, the light coming from this is clearly overlapping over the characters hand holding it.

### Reproduction steps

1.Spawn in with a planter pot on the floor (Note that the light is off)
2.Pick it up and equip it, the light will turn on (Same behaviour as if a Seed was put inside)

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-02-26 10:34
Could not reproduce. 

https://user-images.githubusercontent.com/14351070/221405312-31e7367b-4019-4ba7-bb7c-a592f674d030.mp4

**Comment by Rehexr** [comment] 2023-02-26 15:40
It seems the issue was the fact that the planter must exist as the player loads in for example starting a test in the sub editor or transitioning level during a campaign. Those can then be picked up and will light up. Those which are made or spawned in in the same level will not light up in your hand until they get loaded in in a new level.

https://user-images.githubusercontent.com/104232152/221420575-9d92c502-c366-41fe-b323-7ea483880286.mp4

First one is one that was already on the sub as i loaded in, second one i spawned in

**Comment by Regalis11** [comment] 2023-03-08 15:25
Still no luck in reproducing this I'm afraid. :/ I think it might make a difference where and how you got the planter from. I tested adding them to the sub in the sub editor, and spawning them with console commands and then transitioning between levels, but neither worked.

https://user-images.githubusercontent.com/14351070/223754592-ff0e971d-ff35-4610-bc65-0e5cb5a73cbb.mp4

**Comment by Regalis11** [comment] 2023-03-16 08:51
No steps to repro, closing

**Closed by Regalis11** 2023-03-16 08:51 UTC
Labels: Bug, Need more info, Code
