### ISSUE TITLE
Ability to command bots

### ISSUE THREAD

**Issue by Fakyring** [Regalis11/Barotrauma#389] opened 2018-04-25 19:39 UTC
I suggest you to add an ability to command spawned human bots in multiplayer. Captain or the man who wears captain's clothes and/or has captain's id card (or add an item to rule them all) is the one person who is able to use this ability. Also captain can command players to do smt and this command would be displayed in the corner and add a bind for these fast commands (or use the default "x" button as in SP).

Commands are: power up the reactor, use railguns, fix leaks and etc.
And if it's possible: heal the crew (cpr)
Also in pvp mode that ability wouldn't be working

**Comment by Fakyring** [comment] 2018-04-26 09:44
That's cool. But when will the next update be published?

**Comment by Regalis11** [comment] 2018-04-27 12:42
I'm afraid I can't give you an ETA; it will still take a while before all the unfinished stuff in the dev branch is ready to be released, and there's a chance that a large part of it will be left for the Steam release. There will be minor updates before the Steam release though, but the command system overhaul most likely won't be included in them.

However, the dev branch is public and you may find [unofficial dev builds on the UTG forum](http://undertowgames.com/forum/viewtopic.php?f=18&t=8364) and the Discord channel if you want to give it a try.

**Comment by Regalis11** [comment] 2018-04-27 12:43
Duplicate of #24

**Closed by Regalis11** 2018-04-27 12:43 UTC
Labels: feature request
