### ISSUE TITLE
[Factions] Hammerhead Matriarch genes heal Chemical Withdrawal after taking heavy damage

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10494] opened 2022-11-20 23:14 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I was suffering from chemical withdrawal for an extended duration. One of my crewmates hit me over the head with a Heavy Wrench, taking half of my vitality down. My health bar started rapidly refilling, rubberbanding back down to the status is was at before, and then rapidly healing again. Once it had settled down, my chemical withdrawal had been completely healed. I had hammerhead matriarch x tiger thresher genes active (same character from #10309, same session too). This variable was the only one which could have caused the healing as nobody gave me medical attention to fix the damage.

### Reproduction steps

1. Have Hammerhead Matriarch genes equipped
2. Obtain a chemical addiction and suffer from withdrawal
3. Suffer large amounts of single instance damage (the Heavy Wrench was used)
4. Observe the genes healing the withdrawal affliction away with the other afflictions

### Bug prevalence

Happens every now and then

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-11-22 11:09
I unfortunately couldn't find a way to reproduce this. I wonder if it could've been caused by an autoinjector? The amount of vitality shouldn't affect how the hammerhead matriarch genes work, but an autoinjector might've been triggered by the vitality dropping below 50% if you had one enabled.

**Comment by Wheatley1001** [comment] 2022-11-22 13:41
I did have an autoinjector headset active. This was filled with morphine and did **not** trigger as a response to the damage, as the morphine was still in the slot after I had fully healed. Morphine also wouldn't be able to cure chemical withdrawal (which from memory I believe it was at -70 vitality in strength). 

This issue could be a symptom of the ongoing issue of #10309, as the same character discovered both bugs. During the next hosting session I'll swap out my genes with an identical copy to see if the previous fix to #10309 fixes this issue but for some reason didn't apply to the existing set of genes I'm using.

**Comment by Regalis11** [comment] 2023-01-13 12:50
No known steps to repro, closing

**Closed by Regalis11** 2023-01-13 12:50 UTC
Labels: Bug, Need more info, Code
