### ISSUE TITLE
Bots gets stuck on water waypoints

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2039] opened 2020-01-23 14:47 UTC
- [Yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When bots are outside of the submarine, they get stuck on particular blue waypoints. They will endlessly rotate their body on the node. This happens on all submarines, vanilla and custom.

**Steps To Reproduce**
Force a bot outside.

**Version**
0.9.7

**Additional information**
One example:
https://youtu.be/i8AayCJsHFM

**Comment by NilanthAnimosus** [comment] 2020-01-31 12:39
I was writing a separate issue report, but then noticed this. It is an issue with fixleaks and pathing but I will avoid duplicates.

**Description**
I had some AI on fix leaks, they must have determined a leak was external. a submarine that had damage to various areas of the hull sank and they got to work, pretty standard.

the submarine hit 3 separate chunks of ice however, clearly the AI perhaps does not like this. They swam in circles after swimming outside, not before dipping in and out of the hatch slightly on repeat.

the console would state "crew name: Cannot reach the target: Barotrauma.gap every so often, but not too much. they did have a path to the sub highlighted but sort of went nowhere as if spinning in circles around a point.

My crew exiting the submarine:
https://i.gyazo.com/d83fd6a9cbdf3e584d1e9b3ba73af5d8.mp4

my crew later fully exited, now my debug drawing is on because this is a curious thing to see:
https://i.gyazo.com/628d04c81587b5bd27d06c9cbb293db1.mp4

one of them got low on oxygen, and the order was to seek a diving suit (Presumably, an oxygen tank or diving mask), he swam really, really far away:
https://i.gyazo.com/a693245cd042655fea1ced6ccd1acd66.mp4

soon after, the second one gets low on oxygen, and begins to swim away from the sub.
![image](https://user-images.githubusercontent.com/29177976/73539389-33b1f200-4425-11ea-9085-15813465404b.png)

the first one did eventually swim back, latching onto a path node outside the sub to the left. only to then not enter, but swim in circles somewhere to the left.

I theorize, a now-repaired break in the engine section, may have been the cause...but there was many gaps all around the submarine at this point, but the first I saw that is now gone that I think may have caused them to swim, is highlighted around the green box.
![image](https://user-images.githubusercontent.com/29177976/73539594-a622d200-4425-11ea-95b0-7523d555d6c5.png)

the most interesting part of this though, is how the submarine landed before they started exiting.
![image](https://user-images.githubusercontent.com/29177976/73539637-c5216400-4425-11ea-8c2c-d3cd624abbf0.png)

the submarine was surrounded by moving ice level pieces it had sunk into after being attacked by a now long-dead (propellers are so mean) bone thresher.


**Steps To Reproduce**
Unknown.

**Version**
Unstable - 0.9.702.0 Debug windows, Client singleplayer (Not server). via quickstart.

**Additional information**

As a note, my debug build has the output for certain pathing and AI objective issues commented out due to AI spam in regular multiplayer hosting killing my dedicated servers visible output. not my brightest idea when I swapped to the client without server for UI and AI testing. so my console is rather lacking in potential data there.

**Comment by NilanthAnimosus** [comment] 2020-01-31 15:43
I may have found a solution to this problem, but I don't know if it should be a solution as my edit and continue decided to give up and break when I was going to test it. so visual studio can guess the value, but its no longer the actual value (but it does show me the actual value correctly after I pass the line of code debugging)

after much debugging of what I dont understand. I found a part where when they are swimming outside, they are once close enough to skip to the next node.

The below code originally was using simposition and not worldposition comparison for out of the submarine waypoints distances.
![image](https://user-images.githubusercontent.com/29177976/73546349-fb1a1480-4434-11ea-9dae-315fb80c2ffc.png)

![image](https://user-images.githubusercontent.com/29177976/73546399-138a2f00-4435-11ea-82f9-a39dcb00cf17.png)

Which generates the huge number comparison, such as being on top of the waypoint spinning in circles, while the distance comparison reads as (distance = 1674) vs (targetdistance of 0.6)

Once I changed it around..
![image](https://user-images.githubusercontent.com/29177976/73546464-30266700-4435-11ea-9489-29b624bfcaf6.png)
![image](https://user-images.githubusercontent.com/29177976/73546599-69f76d80-4435-11ea-8ad3-916f70e8268c.png)

These are, considerably more sane values than previously for being outside the submarine.

I see a theoretical -7 and -2 for instance being calculated. or a positive and a negative, as they swim in circles, I also messed with the target distance part of the code thinking that was an issue (It wasn't) so that might be messing it up.

Simply swapping them to world position caused problems with indoor swimming however breaking it, I found I had to keep the original simposition comparison, but when either hull is null, then I tried world position.

![image](https://user-images.githubusercontent.com/29177976/73552163-a334db00-443f-11ea-8b0e-e5d63e0b2c73.png)

This is as far of a solution as I could get, but there are problems between 2 waypoints where you hit just before a hull, there are 1-2 waypoints that have a large jump (30000+ distance) in worldposition, yet their not actually inside a hull. its like a 50/50 chance to get past the jump in coords if the char swims at a decent pace, or they get stuck.

AI swimming better under the new code:
https://i.gyazo.com/73f06814f76d93c96c4029e3915dd214.mp4

**Comment by itchyOwl** [comment] 2020-02-04 14:33
Fixed in Regalis11/Barotrauma-development@09f9b49 (private dev).

Once again: Thank you Nilanth for an excellent bug report that made it very easy to fix the issue. And thanks Kaillera for posting about the issue in the first place!

The issue was that the distance calculations used sim positions where we should have used world positions, because the character and the node can be in different submarines. The physics (in sim space) are not simulated in world space for performance reasons. This makes it a bit complex to use sim positions if it's possible that the entities are inside different submarines. And that's why bugs like this tend to happen.

![image](https://user-images.githubusercontent.com/5370738/73752030-df7e7900-4768-11ea-947c-0209163186ca.png)

As a side note, the formula for calculating the target distance could probably use tweaking (or rethinking) so that we could get rid of the cases where the character fails to reach a waypoint and therefore returns to it although having already passed by it. The cause for this bug was that I had changed these calculations.

**Comment by NilanthAnimosus** [comment] 2020-02-04 15:35
I did wonder why character and collider had different positions, but I ended up stopping there before I went mad. Hurray for a solution though maybe my mechanics wont suicide in the first round of me testing orders o7

**Comment by Rokvach** [comment] 2020-02-09 21:43
This seems to still be an issue, only difference is that now bots spins slower than previously. Moving to To Do.

**Comment by Rokvach** [comment] 2020-02-09 22:20
Bots aren't getting stuck on water waypoints anymore, but there are some other causes of bots getting stuck outside. Closing this ticket as the original issue has been fixed.

**Closed by Rokvach** 2020-02-09 22:20 UTC
Labels: Bug, Code
