### ISSUE TITLE
Input delay when using magic mouse

### ISSUE THREAD

**Issue by FChapeau** [Regalis11/Barotrauma#1832] opened 2019-10-16 16:44 UTC
- [✅] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When playing the game on Mac OS using a Magic Mouse 2, when clicking, I need to keep the button down for about half a second for my input to register

**Steps To Reproduce**
Click, anywhere, on anything, using a magic mouse on mac os.

**Version**
0.9.3.3

**Additional information**
Does not happen with the trackpad in my macbook pro 2018.

**Comment by someone972** [comment] 2021-11-01 21:29
For what it's worth, since this ticket has gone quiet, testing this on my MacBook with a Magic Mouse 2 did not show this behavior on v0.15.13.0. Is there any additional detail or re-testing that can be done by OP?

**Comment by Regalis11** [comment] 2023-03-10 12:26
We're cleaning up some low-prio/unreproducible/irrelevant/outdated tickets from the issue tracker, and this is one of the tickets we chose to axe. Might have been fixed since, or could be there was some problem at the user's end. Closing.

**Closed by Regalis11** 2023-03-10 12:26 UTC
Labels: Bug, Code, Mac only

**Comment by theBeaz** [comment] 2025-01-02 04:09
I am having this issue on a MacBook Pro, M3 Max, both with the touchpad and with a MX Anywhere 3S bluetooth mouse. Left click isn't registered immediately like on my Windows machine - instead I have to hold for almost 1 second then release for the click to be registered. This is on version 1.7.7.0.
