### ISSUE TITLE
Linux (Travel 68km left) Memory fills. 

### ISSUE THREAD

**Issue by JoneKone** [Regalis11/Barotrauma#5848] opened 2021-05-20 20:05 UTC
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Memory leak resulting from driving "on hosted server alone(read 1 player)" 68km right.

**Steps To Reproduce**
Get a shit that goes fast 200km/h then start traveling, end round and start another round. The memory has been filled (check htop/task manager)

(I cannot test windows) Read I won't test windows.

**Version**
v0.13.3.11 Linux

**Additional information**
https://steamcommunity.com/sharedfiles/filedetails/?id=2492830969

I restarted the round multiple times, only after third restart my memory was full enoufhg that it froze the game.

**Comment by Regalis11** [comment] 2021-05-21 11:33
I'm afraid I could not reproduce this, but as a potentional workaround I added some harder restrictions on how far outside the level the sub can travel. Now the force of the current starts to increase exponentially after a certain point, and there's a hard limit on how far the sub can travel.

https://github.com/Regalis11/Barotrauma-development/commit/c790bfbef2a3a34917bf18731f318006786c8a7f

**Comment by JoneKone** [comment] 2021-05-24 04:11
I tried to reproduce this and I couldn't. I'm now convinced that I over reacted and more than likely something else enveloped the memory. A false report.

**Comment by Rokvach** [comment] 2021-06-04 10:34
Tested, this isn't a possibility anymore and I didn't spot any issues. Closing.

**Closed by Rokvach** 2021-06-04 10:34 UTC
Labels: Bug, Code, Needs testing, Performance
