### ISSUE TITLE
Memory component UI does not update after being opened once

### ISSUE THREAD

**Issue by twfld** [Regalis11/Barotrauma#5053] opened 2021-02-13 16:53 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Memory component value in it's interface does not update after it has been opened once, but the actual value of the memory component can still be changed

**Steps To Reproduce**
- Place down a switch, a memory component, and a text display.
- Wire switch output to the memory component input, and the memory component output to the text display.
- Test the submarine, and open the memory component. You should see a value of 0 stored in it, as well as on the display.
- Flick the switch, and open the memory component again. It still displays a 0, even though the switch is outputting a value of 1 to it. The display displays the 1. Based on this, the memory component is storing the 1 as intended, but it displays the value it had when you first opened it's interface.

**Version**
v0.12.0.2 on Windows

**Comment by Working-Joe** [comment] 2021-02-17 12:54
This holds for all components, the value is updated after you open the UI of another component.

**Comment by Regalis11** [comment] 2021-07-19 09:06
Duplicate of https://github.com/Regalis11/Barotrauma/issues/5521

**Closed by Regalis11** 2021-07-19 09:06 UTC
Labels: Bug, Code, Low prio
