### ISSUE TITLE
After save/load in the colony new tasks appear and goods are delivered to the submarine in free containers

### ISSUE THREAD

**Issue by NikolayGus** [Regalis11/Barotrauma#7322] opened 2021-11-15 04:45 UTC
- [No] I have searched the issue tracker to check if the issue has already been reported.

**Description**
After save/load in the colony new additional tasks appear and purchased goods are delivered to the submarine. Product containers are free and can be recycled into steel. I propose to add one large immovable container directly to the colonies, all purchased goods are added to it and goods are delivered to the submarine manually by the player.

**Steps To Reproduce**
Save/Load

**Version**
Version 0.15.13.0. Windows 10.

**Additional information**

**Comment by Regalis11** [comment] 2021-11-15 08:23
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3388

**Closed by Regalis11** 2021-11-15 08:23 UTC
