### ISSUE TITLE
Game crash when docking to a station

### ISSUE THREAD

**Issue by Adz0511** [Regalis11/Barotrauma#4626] opened 2021-01-03 23:13 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In a single player campaign, upon completion of a mission and docking to the next station; my game crashed and corrupted the save file. I could not reload the save and doing so would then prevent me from loading any saved game until the game was restarted.

I could not find any record of a similar issue, so I asked for help in the discord. Using the decompression tool, I was advised that the issue may be that there were no connections to the current location. Moving the sub to the previous station fixed the issue immediately and I have had no further problems upon continuation of the game and docking at another station.
 
**Steps To Reproduce**
I'm afraid I don't know how to reproduce the bug, but have attached the faulty save file for reference along with the crash report.

**Version**
Version 0.11.0.10 - Windows 10

[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/5762431/crashreport.2.log)
[Into the Uncharted Depths.zip](https://github.com/Regalis11/Barotrauma/files/5762432/Into.the.Uncharted.Depths.zip)

**Comment by AngelBirb** [comment] 2021-01-04 02:34
I just had this same problem, and it corrupted my save too. I completed a "Killing a Hammerhead" Mission, and upon docking, my game immediately crashed as well.

**Comment by Adz0511** [comment] 2021-01-04 17:16
Perhaps try the same method that I did and see if it solves your problem?

You should be able to find the Save Decompressor here :https://github.com/Jlobblet/Barotrauma-Save-Decompressor

**Comment by Regalis11** [comment] 2021-01-13 17:36
Potential duplicate of #4581

**Comment by Rokvach** [comment] 2021-01-14 08:20
I didn't encounter any issues whilst loading the included save, seems to be working correctly. Closing.

**Closed by Rokvach** 2021-01-14 08:20 UTC
Labels: Bug, Code, Crash, Needs testing
