### ISSUE TITLE
Thalamus turret crashing game

### ISSUE THREAD

**Issue by HansKrieger** [Regalis11/Barotrauma#10577] opened 2022-11-26 20:30 UTC
[crashreport (9).log](https://github.com/Regalis11/Barotrauma/files/10096977/crashreport.9.log)
[crashreport (11).log](https://github.com/Regalis11/Barotrauma/files/10096979/crashreport.11.log)

The game crash when I get closer to the wreck and the thalamus turret moves.

Save game file: [Beta.zip](https://github.com/Regalis11/Barotrauma/files/10096981/Beta.zip)

**Comment by feru7** [comment] 2022-11-26 22:36
I think it is the same as here: https://github.com/Regalis11/Barotrauma/issues/10547

**Comment by Regalis11** [comment] 2022-11-27 11:18
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10547

**Closed by Regalis11** 2022-11-27 11:18 UTC
