### ISSUE TITLE
[Campaign Update] Unable to zoom on Character Editor

### ISSUE THREAD

**Issue by MrAsbestos** [Regalis11/Barotrauma#2952] opened 2020-06-03 06:06 UTC
- [✔ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Cannot zoom in the Character Editor Mode, you can at least move the camera with the mouse button click.

**Comment by Regalis11** [comment] 2020-06-03 06:52
Duplicate of #2940

**Closed by Regalis11** 2020-06-03 06:52 UTC
