### ISSUE TITLE
Husk Infection Bugs

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3673] opened 2020-08-31 14:55 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
1. There's no stinger stage for the human characters before turning completely.
2. humanhusk reduces husk infection above 49% when biting other humans (noticable in outpost events)
3. Multiplayer - Health Hud Scanner caps husk infection at 49%

**Version**
0.10.4

**Comment by itchyOwl** [comment] 2020-09-01 12:42
There seems to be something wrong with the affliction in multiplayer.

In single player it works as intended: at 50% you lose the ability to speak, at 75% the stinger comes from your mouth, and at 100% you'll collapse and turn into a husk.

I'm not sure if I understand the second point: the husk affliction is reduced when you bite as a human husk?

**Comment by itchyOwl** [comment] 2020-09-01 13:05
I think I found what causes it, looking into it.

**Comment by Kaillera** [comment] 2020-09-01 13:05
> There seems to be something wrong with the affliction in multiplayer.
> 
> In single player it works as intended: at 50% you lose the ability to speak, at 75% the stinger comes from your mouth, and at 100% you'll collapse and turn into a husk.
> 
> I'm not sure if I understand the second point: the husk affliction is reduced when you bite as a human husk?

Yeah you can see this especially in the husk outpost event when you help ride it out. Let 2 or 3 husked turned outpost NPC fight 1 outpost security guard. The number will reduce from whatever it was over 50% on the guard everytime the husk successfully bite the guard

**Comment by itchyOwl** [comment] 2020-09-01 14:46
Should be fixed in the next unstable, please give it a test. And thanks again for reporting :thumbsup:

**Comment by Kaillera** [comment] 2020-09-03 11:28
Working. Was able to use stinger at 75. Can view past 49% infection.

**Comment by Rokvach** [comment] 2020-09-03 13:36
Closing

**Closed by Rokvach** 2020-09-03 13:36 UTC
Labels: Bug, Code, Networking
