### ISSUE TITLE
[Factions] Crash after Thresher swarm attack during campaign

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10420] opened 2022-11-16 23:05 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

This has happened to both me and has been discussed on the discord. For some reason getting attacked by a swarm specifically during a campaign sometimes crashes your game entirely. (Crashreport attached)
[Uploading crashreport (21).log…]()

### Reproduction steps

1.Get a swarm mission or any kind of Thresher swarm during a campaign
2.Get the sub attacked by the swarm
3.???
4.Crash

### Bug prevalence

Happens every now and then

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-11-17 07:15
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10249

**Closed by Regalis11** 2022-11-17 07:15 UTC
