### ISSUE TITLE
Bug in the kastrull drone

### ISSUE THREAD

**Issue by leosf-afk** [Regalis11/Barotrauma#7305] opened 2021-11-14 06:49 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
when i drive the kastrull ship, the engineer go to kastrull drone and unlocks them

**Steps To Reproduce**
start a normal run, buy the kastrull, and watch the enginner behavior when you browse

**Version**
ver: 0.15.13.0- win 10

**Additional information**
before the update the engineer don't unloks the kastrull drone

**Comment by Regalis11** [comment] 2021-11-15 09:59
Duplicate of https://github.com/Regalis11/Barotrauma/issues/6928

**Closed by Regalis11** 2021-11-15 09:59 UTC
