### ISSUE TITLE
Inventory (loot) of creature Mudraptor is inside the AI node causing no inventory + many possible oversights in creature XMLs

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1274] opened 2019-03-13 02:47 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I initially heard mudraptor's have no inventory, upon checking the XMLs they appear to have an inventory, but it is inside the AI node instead of the Character node.

As a side note, it appears Moloch has an inventory, but not molochboss or molochbaby.

Additional side note, Crawler.xml and legacycrawler.xml have two AI nodes, and legacycrawler / legacymoloch have no decoy targetting priority unlike the other creature types.

**Version**
0.8.9.5 closed alpha

**Additional information to look at perhaps if one wants to dive into the creature XMLs**

Going over the character files I noticed these though their just as likely to be intentional, still making a note here if any of the below is of interest:

- [x] Carrier, Endworm has no "Sonar" target priority. Unlike hammerheads though carriers and endworms have a hearing value defined (?) **Fixed**

- [x] moloch can bleed, while moloch baby, boss and legacy moloch do not bleed. **New moloch variants now bleed, but we'll keep the legacy moloch the way it was**

- [ ] Charybdis, Coelanth, Hammerhead, Moloch, both tiger threshers and watchers can bleed yet do not have blood decals defined for them. **Added decals to threshers; the others don't need it because they can't get inside and cause decals on walls**

- [x] Husk has blood decals but cannot bleed yet humanhusk can bleed but has no defined blood decals.

- [x] Humans and Human Husks have locational damage vitality multipliers (IE. twice damage to head, half to arms), Husks do not. In fact not a single other creature in the game implements any of these for its limbs for weak spots or grazing hits. **Intentional, husks are basically empty diving suits with an alien parasite inside, so the head is not really a head**

- [x] Molochs have an "Isarmor="false" section on the blatter (Bladder?) limb for double damage taken, Mudraptors Chest increased damage zone (1.5x) does not utilize Isarmor="false" (not sure to the attributes usage), both have damage sound and no projectile deflection.

- [x] Baby molochs and moloch bosses have a Blatter (Bladder?), but only standard molochs have the damage multiplier.

- [x] Legacy moloch has the same vitality as a moloch boss. **Intentional, the new molochs have been balanced but we intend to keep the legacy variants untouched when possible**

- [x] Fractalguardian2 has one claw without a defined cooldown (Others have 8 seconds).

- [ ] Fractal guardians have no secondarycooldowns (Are these meant to limit multiple-limb attacks in rapid succession?)

- [ ] Hammerheads have 3 second cooldowns with 1 second secondary cooldowns across 5 limbs, with a 10 second primary attack limb. I've seen these creatures attack insanely fast when under fire near a sub, despite the attacks have targettype "Character" - Is there possibly a bug here with the Enemy fish AI or is secondary cooldown something else?

- [ ] Hammerhead attacks have a conditional inside the Attack tag for stun, but not inside the affliction, is this intended to block the internal damage too or only attack if a player is not stunned? the other attacks do not have a conditional for stun defined too.

- [x] Huskappendage and husks cause no internaldamage on hit, only bleeding afflictions and husk affliction.

- [ ] Charybdis, Coelanth, Endworm, both tiger threshers and watchers attacks have no defined cooldowns.

- [ ] Molochs, moloch bosses and Watchers cause 200 internal damage on hit, carriers only 100 (Survivable in diving suit as armor).

- [ ] A direct strike from an endworm is only a mere 30 internal damage.

- [ ] Boss equivalents deal the same damage (aka afflictions) yet different structure damages.

- [ ] Charybdis deal an insane 250 structure damage, an endworm is 500, Molochs are only 55/35/15 and watchers don't even get a defined structure damage. Crawlers deal 3 structure and mudraptors only 5 structure, unlikely to breach a hull unless its stationary while a charybdis is unstoppably powerful.

- [ ] Carrier's and Watchers have no defined structuredamage (Is internaldamage affliction also structure damage? why are there separate definitions? is this only literal force dealing damage?)

- [x] Husks use Blunt structure damage sounds (Not sure if this is meant to be slash or really blunt). **Does not matter because the attack doesn't do structure damage**

- [x] Fractal guardians do not have a severlimbprobability despite having what appears to be slash attacks.

- [x] Mantis and mudraptor define latchonto, but has only one attribute compared to crawlers with 12 attributes for the tag (Is this correctly configured?) **The attributes defined in the crawler config aren't needed for the mantis and mudraptor because they only attach to level walls, not the sub**

- [x] Fractal guardians and watcher still use attackpriorityrooms instead of target priority "room" (Not sure if intentional or different other than how it is written in XML from previous baro versions).

- [x] Carrier, Endworm, both fractal guardians and watcher have no "nasonov" target priority. **Intentional**

- [ ] Carrier, Charybdis, Coelanth, Endworm, fractal guardians, Humanhusk, Husk, legacy creatures, mantis, tiger thresher / thresher boss, watcher have no "provocative" target priority.

- [ ] Carrier, Charybdis, Coelanth, Endworm, Fractal guardians, humanhusk, husk, legacy creatures (Inc crawler), mantis, all molochs, all tiger threshers have no "light" target priority.

- [ ] Crawler has light priority "escape" (250 priority), legacy does not.
- [ ] Watcher has "light" target priority, but state is "None".

- [x] Legacy Molochs have more priority to attack humans than regular Molochs. **Intentional, the new molochs have been balanced but we intend to keep the legacy variants untouched when possible**

- [x] Watcher's have no "Stronger" / "Weaker" target priority.

- [x] Mudraptor/Mantis/Crawler have door target prioties, but not legacycrawler. **Intentional**

- [ ] Humanhusk does not have aggressiveboarding.

- [ ] Only both crawlers, mantis and mudraptor will ever flee from excessive damage using fleehealththreshold.

(Are these still used to prevent infighting for creatures? since I believe say, a baby moloch would have less combat strength to a boss moloch and a boss thresher classed as stronger to a regular one for other creatures perhaps)
- [x] All moloch types have identical combat strength of 1200.
- [x] All threshers, hammerhead and coelanth have combat strength of 400
- [x] all crawlers and husks have combat strength 100.

**Comment by itchyOwl** [comment] 2019-03-13 08:15
The inventory bug is now fixed. Also added aggressive boarding to humanhusk definition and changed the crawler behaviour.

The weak spots in Moloch's bladder and Mudraptor's chest should work, as well as the armors on them. I'm not quite sure how the locational damage multipliers work, but it's possible that they could be used for the same end.

Secondary cooldown is used between different attacks. The conditional regarding stun is indeed a conditional for the attack: it's used only when the target is NOT stunned.

Moloch variants and the legacy characters are not yet properly defined. Basically, only Crawler, Mudraptor, Hammerhead, Moloch, and Husk/Humanhusk should be up to date. All the others are not, because they will be remade or treated as legacy. Many things have changed, so there's no point in updating character files that will be remade anyway.

It's intentional that Hammerhead should not flee. She doesn't know the concept of fear ;)

**Comment by itchyOwl** [comment] 2019-03-13 08:34
Another one: it's by design that crawlers and mudraptors can't get in to the sub easily by breaking walls. Mudraptors should break through doors quite efficiently though.

**Comment by Rokvach** [comment] 2019-11-28 00:19
@itchyOwl Whats the current state of this issue?

**Comment by Regalis11** [comment] 2020-03-04 12:15
@itchyOwl Do you think we should close this? There's been so many changes to all of the monsters that I don't think most of these are relevant anymore.

**Comment by itchyOwl** [comment] 2020-03-09 14:25
Yeah I think so. Let me do it. I'll read it through once again and if there's any valid points left, I'll create new tickets or add personal notes about them.

**Closed** 2020-04-09 18:16 UTC
Labels: Bug, Code, Design
