### ISSUE TITLE
Crash when a mod contains wearables with no texture (NullReferenceException in SpriteRecorder.Command.FromTransform)

### ISSUE THREAD

**Issue by nagaisa** [Regalis11/Barotrauma#12247] opened 2023-06-28 21:12 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

at random i crash mid-game when playing on a spisfic server, it does not seam to happen anywhere but that server. it dose it complaty at random and affter it happens i also can't join back in till they enter lobby again

### Reproduction steps

1.join the server
2.able to play for a good bit
3.randomly crash mid round

### Bug prevalence

Happens every time I play

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
`Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Command FromTransform(Microsoft.Xna.Framework.Graphics.Texture2D, Microsoft.Xna.Framework.Vector2, Microsoft.Xna.Framework.Rectangle, Microsoft.Xna.Framework.Color, Single, Microsoft.Xna.Framework.Vector2, Microsoft.Xna.Framework.Vector2, Microsoft.Xna.Framework.Graphics.SpriteEffects, Single, Int32)
Stack trace: 
   at Barotrauma.SpriteRecorder.Command.FromTransform(Texture2D texture, Vector2 pos, Rectangle srcRect, Color color, Single rotation, Vector2 origin, Vector2 scale, SpriteEffects effects, Single depth, Int32 index) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Utils/SpriteRecorder.cs:line 45
   at Barotrauma.Limb.<ApplyAlphaClip>g__makeCommand|132_0(WearableSprite w, <>c__DisplayClass132_0& ) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Characters/Limb.cs:line 1193
   at Barotrauma.Limb.ApplyAlphaClip(SpriteBatch spriteBatch, WearableSprite wearable, WearableSprite alphaClipper, SpriteEffects spriteEffect) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Characters/Limb.cs:line 1253
   at Barotrauma.Limb.DrawWearable(WearableSprite wearable, Single depthStep, SpriteBatch spriteBatch, Color color, Single alpha, SpriteEffects spriteEffect) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Characters/Limb.cs:line 1272
   at Barotrauma.Limb.Draw(SpriteBatch spriteBatch, Camera cam, Nullable`1 overrideColor, Boolean disableDeformations) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Characters/Limb.cs:line 893
   at Barotrauma.Lights.LightManager.<RenderLightMap>g__DrawCharacters|66_2(SpriteBatch spriteBatch, Camera cam, Boolean drawDeformSprites) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Map/Lights/LightManager.cs:line 456
   at Barotrauma.Lights.LightManager.RenderLightMap(GraphicsDevice graphics, SpriteBatch spriteBatch, Camera cam, RenderTarget2D backgroundObstructor) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Map/Lights/LightManager.cs:line 434
   at Barotrauma.GameScreen.DrawMap(GraphicsDevice graphics, SpriteBatch spriteBatch, Double deltaTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Screens/GameScreen.cs:line 212
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Screens/GameScreen.cs:line 123
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 1002
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 58`
```

**Comment by Regalis11** [comment] 2023-06-29 08:43
Thank you for the report!

Based on the error message, it seems like some wearable item is set to clip other wearables (i.e. the way a diving helmet prevents hairs and hats from clipping through it), but has no texture defined. Most likely caused by some mod. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6136450276e56816445c09106b77393e735c56e8 (commit in our private repo).

**Comment by Jasontti** [comment] 2023-08-14 10:24
Tested by removing diving suits helmet sprite mapping.
No crashes in single, or multiplayer. Gives sprite not found error message now.
Closing ticket.

**Closed by Jasontti** 2023-08-14 10:24 UTC
Labels: Bug, Code, Modding
