### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Marutotheone** [Regalis11/Barotrauma#7950] opened 2021-12-29 14:53 UTC
Barotrauma Client crash report (generated on 29/12/2021 16:52:40)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

25F2DA9FCBD0323CBDF4FC2DA2092C7B

Game version 0.15.22.1 (ReleaseWindows, branch release, revision 898f64d2c0)
Graphics mode: 1366x768 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9, New Wrecks For Barotrauma, Backpacks, Meaningful Upgrades, Rucksack 2.0, Tail's Melee Weapons Pack, Meaningful CPR, [Rani] Katanas, V-2008
Level seed: MildaTopol
Loaded submarine: V-2008 (0FDE710FD7EB6246F1F70C7B7F07CBC2)
Selected screen: Barotrauma.RoundSummaryScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 6.1.7601 Service Pack 1 64 bit
    GPU name: Intel(R) HD Graphics 3000
    Display mode: {Width:1366 Height:768 Format:Color AspectRatio:1.7786459}
    GPU status: Normal

Exception: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown (SharpDX.SharpDXException)
Device removed reason: HRESULT = 0x887A0006
Target site: Void CheckError()
Stack trace: 
   at SharpDX.Result.CheckError()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 1017
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 511
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59

Last debug messages:
[29/12/2021 16:52:12] WARNING: Value in attribute "maxforce" is not formatted correctly
 at Mods\Meaningful Upgrades\UpgradeModules.xml @ '<UpgradeModule identifier="increaseenginemaxforce" maxlevel="10" categories="engines" increaseontooltip="12">'.
 It should be an integer with optionally a '+' or '-' at the front and/or '%' at the end.
The value has been assumed to be '0'.
[29/12/2021 16:52:12] WARNING: Value in attribute "maxforce" is not formatted correctly
 at Mods\Meaningful Upgrades\UpgradeModules.xml @ '<UpgradeModule identifier="increaseenginemaxforce" maxlevel="10" categories="engines" increaseontooltip="12">'.
 It should be an integer with optionally a '+' or '-' at the front and/or '%' at the end.
The value has been assumed to be '0'.
[29/12/2021 16:52:12] WARNING: Value in attribute "maxforce" is not formatted correctly
 at Mods\Meaningful Upgrades\UpgradeModules.xml @ '<UpgradeModule identifier="increaseenginemaxforce" maxlevel="10" categories="engines" increaseontooltip="12">'.
 It should be an integer with optionally a '+' or '-' at the front and/or '%' at the end.
The value has been assumed to be '0'.
[29/12/2021 16:52:12] WARNING: Value in attribute "maxforce" is not formatted correctly
 at Mods\Meaningful Upgrades\UpgradeModules.xml @ '<UpgradeModule identifier="increaseenginemaxforce" maxlevel="10" categories="engines" increaseontooltip="12">'.
 It should be an integer with optionally a '+' or '-' at the front and/or '%' at the end.
The value has been assumed to be '0'.
[29/12/2021 16:51:58] Transitioning to MildaTopol (current location: Topol Mining Claim, selected location: Milda, leaving sub: V-2008, at start: True, at end: False, transition type: LeaveLocation)
[29/12/2021 16:47:47] Unlocked mission "Destroy a Mudraptor nest" in the location "Topol Mining Claim".
[29/12/2021 16:47:45] Unlocked mission "Destroy a Tiger Thresher nest" in the location "Topol Mining Claim".
[29/12/2021 16:47:36] Unlocked mission "Praise the honkmother" in the location "Topol Mining Claim".
[29/12/2021 16:45:52] Generating an outpost for the start of the level... (Location: Topol Mining Claim, level type: Outpost)
[29/12/2021 16:45:44] WARNING: Value in attribute "maxforce" is not formatted correctly
 at Mods\Meaningful Upgrades\UpgradeModules.xml @ '<UpgradeModule identifier="increaseenginemaxforce" maxlevel="10" categories="engines" increaseontooltip="12">'.
 It should be an integer with optionally a '+' or '-' at the front and/or '%' at the end.
The value has been assumed to be '0'.
[29/12/2021 16:45:44] WARNING: Value in attribute "maxforce" is not formatted correctly
 at Mods\Meaningful Upgrades\UpgradeModules.xml @ '<UpgradeModule identifier="increaseenginemaxforce" maxlevel="10" categories="engines" increaseontooltip="12">'.
 It should be an integer with optionally a '+' or '-' at the front and/or '%' at the end.
The value has been assumed to be '0'.
[29/12/2021 16:45:44] WARNING: Value in attribute "maxforce" is not formatted correctly
 at Mods\Meaningful Upgrades\UpgradeModules.xml @ '<UpgradeModule identifier="increaseenginemaxforce" maxlevel="10" categories="engines" increaseontooltip="12">'.
 It should be an integer with optionally a '+' or '-' at the front and/or '%' at the end.
The value has been assumed to be '0'.
[29/12/2021 16:45:44] WARNING: Value in attribute "maxforce" is not formatted correctly
 at Mods\Meaningful Upgrades\UpgradeModules.xml @ '<UpgradeModule identifier="increaseenginemaxforce" maxlevel="10" categories="engines" increaseontooltip="12">'.
 It should be an integer with optionally a '+' or '-' at the front and/or '%' at the end.
The value has been assumed to be '0'.
[29/12/2021 16:45:00] Overriding the CPR settings with 'Mods/Meaningful CPR/Overwrite_Afflictions.xml'
[29/12/2021 16:44:56] Adding additional wreck ai config from file 'Mods/New Wrecks For Barotrauma/ThalamusAI.xml'
[29/12/2021 16:44:55] (Msg) SDR RelayNetworkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[29/12/2021 16:44:55] (Msg) Ping location: sto2=44+4,sto=45+4/44+4,waw=50+5,vie=55+5,ams=59+5,lhr=59+5,fra=71+7/66+5,par=/67+5,mad=93+9/86+5,iad=142+14/143+5,sgp=291+29/253+17,gru=307+30
[29/12/2021 16:44:55] (Msg) Ping measurement completed
[29/12/2021 16:44:55] (Debug) Destroying relay 'par#151 (185.25.182.68:27057)' because initial_ping_timeout
[29/12/2021 16:44:53] (Debug) Destroying relay 'par#118 (185.25.182.68:27024)' because initial_ping_timeout
[29/12/2021 16:44:51] (Verbose) Communications with routing cluster 'seo' established.
[29/12/2021 16:44:51] (Verbose) Communications with routing cluster 'tyo1' established.
[29/12/2021 16:44:50] (Verbose) Communications with routing cluster 'syd' established.
[29/12/2021 16:44:50] (Verbose) Communications with routing cluster 'tyo' established.
[29/12/2021 16:44:50] (Verbose) Communications with routing cluster 'sgp' established.
[29/12/2021 16:44:50] (Verbose) Communications with routing cluster 'maa' established.
[29/12/2021 16:44:50] (Verbose) Communications with routing cluster 'lim' established.
[29/12/2021 16:44:50] (Verbose) Communications with routing cluster 'scl' established.
[29/12/2021 16:44:50] (Verbose) Communications with routing cluster 'eze' established.
[29/12/2021 16:44:50] (Verbose) Communications with routing cluster 'hkg' established.
[29/12/2021 16:44:50] (Verbose) Communications with routing cluster 'jnb' established.
[29/12/2021 16:44:50] (Verbose) Communications with routing cluster 'bom' established.
[29/12/2021 16:44:50] (Verbose) Communications with routing cluster 'gru' established.
[29/12/2021 16:44:50] (Verbose) Communications with routing cluster 'vie' established.
[29/12/2021 16:44:50] (Verbose) Communications with routing cluster 'sea' established.
[29/12/2021 16:44:50] (Verbose) Communications with routing cluster 'lax' established.
[29/12/2021 16:44:50] (Verbose) Communications with routing cluster 'waw' established.
[29/12/2021 16:44:50] (Verbose) Communications with routing cluster 'sto' established.
[29/12/2021 16:44:50] (Verbose) Communications with routing cluster 'ord' established.
[29/12/2021 16:44:50] (Verbose) Communications with routing cluster 'sto2' established.
[29/12/2021 16:44:50] (Verbose) Communications with routing cluster 'dxb' established.
[29/12/2021 16:44:50] (Verbose) Communications with routing cluster 'dfw' established.
[29/12/2021 16:44:50] (Verbose) Communications with routing cluster 'mad' established.
[29/12/2021 16:44:50] (Verbose) Communications with routing cluster 'atl' established.
[29/12/2021 16:44:50] (Verbose) Communications with routing cluster 'iad' established.
[29/12/2021 16:44:50] (Verbose) Communications with routing cluster 'lhr' established.
[29/12/2021 16:44:50] (Warning) SteamNetworkingSockets lock held for 7.0ms.  (Performance warning.)  ServiceThread,RecvUDPPacket(x2)
This is usually a symptom of a general performance problem such as thread starvation.
[29/12/2021 16:44:50] (Verbose) Communications with routing cluster 'fra' established.
[29/12/2021 16:44:50] (Verbose) Communications with routing cluster 'ams' established.
[29/12/2021 16:44:50] (Msg) SDR RelayNetworkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[29/12/2021 16:44:50] (Msg) Performing ping measurement
[29/12/2021 16:44:50] (Msg) Got SDR network config.  Loaded revision 364 OK
[29/12/2021 16:44:50] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[29/12/2021 16:44:28] Attempting to open ALC device "OpenAL Soft on VoiceMeeter Input (VB-Audio VoiceMeeter VAIO)"
[29/12/2021 16:44:26] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[29/12/2021 16:44:25] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[29/12/2021 16:44:23] Logged in as Martiinnnni (SteamID STEAM_1:0:205375365)

**Comment by Regalis11** [comment] 2022-01-03 08:18
Duplicate of https://github.com/Regalis11/Barotrauma/issues/1833

**Closed by Regalis11** 2022-01-03 08:18 UTC
