### ISSUE TITLE
Storage containers/Held items disappearing after saving&quitting in solo

### ISSUE THREAD

**Issue by Orchidthederg** [Regalis11/Barotrauma#7891] opened 2021-12-21 05:30 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When playing in singleplayer campaign, if you select a bot to play as and have them pick up a two-handed item or item that takes up a hand slot, upon saving and quitting and reloading the game, the held item will have been deleted.

**Steps To Reproduce**
1.) Start campaign game
2.) Select bot character
3.) Pick up crate or storage container
4.) Save and Quit, rejoin
5.) Observe as possibly hours worth of collected items have disappeared.

**Version**
v0.15.22.1 (ReleaseWindows, branch release, revision 898f64d2c0)

**Additional information**
While unrelated to the bug report itself, I've been experiencing this bug for ages, and just now I lost over 9 unidentified genetic material, 7 physicorium bars, 8 fulgurium bars, and several more valuable materials. For the love of all that is holy, PLEASE fix this!!!

**Comment by Regalis11** [comment] 2022-01-04 09:56
Thank you for the report!

Unfortunately I wasn't able to reproduce the issue. I'm not sure if I followed the exact same steps, but here's what I did:
1. Started a new campaign and took control of the engineer
![image](https://user-images.githubusercontent.com/14351070/148041451-3b96ae42-a713-4494-94dc-8410b037dc2a.png)
2. Save and Quit to main menu
![image](https://user-images.githubusercontent.com/14351070/148041472-93ffc980-66ca-425a-b09b-3993e35ef4f0.png)
3. Loaded the save and took control of the engineer again
![image](https://user-images.githubusercontent.com/14351070/148041521-a411f850-b3f1-46d0-b0a9-c3efb7d1f56b.png)

Did it happen in an outpost level (I guess it must've had, since you can't save and quit during missions)? I wonder if it could be that the bot dropped the container/crate when you reloaded the campaign?

**Comment by Regalis11** [comment] 2022-02-15 17:40
No known steps to repro, closing

**Closed by Regalis11** 2022-02-15 17:40 UTC
Labels: Bug, Need more info, Code
