### ISSUE TITLE
[Unstable 0.10.4.0] Games crashes after loading the level

### ISSUE THREAD

**Issue by Lefttroll** [Regalis11/Barotrauma#3364] opened 2020-07-13 20:08 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Games crashes after loading the level

**Steps To Reproduce**
use save that i pinned to this issue and try to leave outpost

**Version**
Unstable 0.10.4.0 + Windows

**Additional information**
After random player joined to our server (8 players already) server crashed and then save was corrupted
[consoleOutput.txt](https://github.com/Regalis11/Barotrauma/files/4914829/consoleOutput.txt)
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/4914830/crashreport.2.log)
[Pls No Thalamus.zip](https://github.com/Regalis11/Barotrauma/files/4914832/Pls.No.Thalamus.zip)

**Comment by Kaillera** [comment] 2020-07-14 02:19
This was caused by a signal check component immediately redocking to the outpost after we left the outpost.

**Comment by Regalis11** [comment] 2020-07-14 07:35
Couldn't find steps to repro, but should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/2aa421a39c4b56e33bf90b8aa87f17dfaf378f8a

**Comment by Kaillera** [comment] 2020-07-14 08:45
Multiplayer. Just send a constant 1 set state to docking port.

**Comment by Rokvach** [comment] 2020-07-27 11:19
I was still able to reproduce this issue by using the save provided

1. Start a multiplayer campaign with the save
2. Leave outpost
3. The game doesn't crash but you get disconnected from the server with a error

I am unable to get access to the full error report as I can't access the console when a error prompt is open, and closing the prompts opens up the round summary which doesn't let me close it, so it soft locks my game to a point where I have to restart it.

Error prompt 1
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/4d768dbf-6bea-4302-b0b1-6069ed3773ee)

Error prompt 2
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/664ecf65-6276-4c58-bb22-31224aa4dc33)

Round summary which can't be closed
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/d13be618-c6f1-4dc6-a6db-89a617899376)

**Comment by Regalis11** [comment] 2020-07-28 15:54
Removing the high prio label since this only affects submarines that dock automatically, which aren't really playable in the campaign anymore (impossible to leave an outpost when the sub immediately redocks).

**Comment by Rokvach** [comment] 2020-07-28 20:05
I wasn't able to reproduce the issue anymore, now the sub just re-docks to the outpost right at the round start as it should be as it has been accidentally wired to do so. So working correctly. Closing.

**Closed by Rokvach** 2020-07-28 20:05 UTC
Labels: Bug, Code, Crash
