### ISSUE TITLE
Hash Mismatch When Updating Mod

### ISSUE THREAD

**Issue by evilfactory** [Regalis11/Barotrauma#11977] opened 2023-05-10 15:38 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Updating a mod seems to always cause a hash mismatch for the published version.
![Barotrauma_Mly7N4Rylg](https://github.com/Regalis11/Barotrauma/assets/36804725/fc84d8ed-08e4-49cf-ae33-e830f6411845)

This is the filelist.xml
```xml
<?xml version="1.0" encoding="utf-8"?>
<contentpackage name="Lua For Barotrauma" modversion="1.0.57" corepackage="False" steamworkshopid="2559634234" gameversion="1.0.13.1">
  <ServerExecutable file="%ModDir%/Binary/DedicatedServer.exe" />
</contentpackage>
```

### Reproduction steps

1. Update mod
2. Watch the published version have a hash mismatch

### Bug prevalence

Happens every time I play

### Version

v1.0.13.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-05-10 17:38
Which version did you publish the previous update in? There's been some changes to the MD5 hash calculations in the latest update to address https://github.com/regalis11/barotrauma/issues/11789 (more specifically, the mod version and the UgcId of the mod are included in the hash). Because this changes the hashes of every mod, we bumped up the "MinimumHashCompatibleVersion" to v1.0.11.0, meaning that the "expected hash" should now always get discarded in mods published prior to that update. Did you by any chance push any updates to the mod from the recent unstable versions?

**Comment by Regalis11** [comment] 2023-05-10 17:53
I also tested updating some of the mods I've published previously in the workshop, and couldn't get the error to occur. :/

**Comment by Regalis11** [comment] 2023-05-10 18:20
Thank you for the extra info! I was able to reproduce this at my end now too, and we're working on getting this hotfixed asap.

**Comment by Rokvach** [comment] 2023-05-11 08:34
Noticed that you have to update the mod twice in order to get the correct hash

1. Changed the version number of a mod I had previously published
2. Updated the mod
3. Hash mismatch error shown on the mod
4. Update the mod again
5. No issues on the mod

![image](https://github.com/Regalis11/Barotrauma/assets/7299826/41767780-0384-488b-aefa-df0f718ebf69)

**Comment by Rokvach** [comment] 2023-05-11 11:58
Tested, working correctly. Closing.

**Closed by Rokvach** 2023-05-11 11:58 UTC
Labels: Bug, Code, Severe, Modding
