### ISSUE TITLE
[0.10.600] Crash - Void set_Reverse(Boolean)

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3971] opened 2020-10-01 11:43 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
[servercrashreport.log](https://github.com/Regalis11/Barotrauma/files/5311661/servercrashreport.log)

**Steps To Reproduce**
Crew of 5 bots (Mech, Doc, Ass *3)
Started first mission of the Campaign: Salvage Wreck Mission
Parked behind Wreck
Crashed after a bit

**Version**
0.10.600

**Comment by Regalis11** [comment] 2020-10-01 11:44
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3964

**Closed by Regalis11** 2020-10-01 11:44 UTC
