### ISSUE TITLE
Issues with the "fight Intruders" Order for Bots on abandoned Outposts

### ISSUE THREAD

**Issue by Notmaximluenenstrass** [Regalis11/Barotrauma#11620] opened 2023-03-21 09:58 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When I was visiting an abandoned Outpost for the first time after 1.0 I noticed that my entire security force ran off into the husk infested hell hole (was the rescue Subra mission). After some experimenting with the order system, I noticed that bots with the fight Intruders order assault enemies that are on the outpost, which is strange because there already is a seperate order for assaulting enemies. My theory is that the bots view outposts as part of the submarine and try to defend the "submarine"
I have tried replicating this on a private server and bots with the "fight intruders" Order ran off into the outpost every single time

Issue is not game-breaking but anoying, as now i have to remember to revoke orders before going to abandoned outposts and if theres one thing im not good at, its remembering things i was supposed to do.

### Reproduction steps

1.Start campain or server
2.Go on an "abandoned outpost" mission (any will do)
3.give a bot the "fight intruders" order
4.Observe how they runup the ladder to the outpost and most likely die

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-03-22 02:02
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7750

**Closed by Regalis11** 2023-03-22 02:02 UTC
