### ISSUE TITLE
Make corpse bodybags a configuration setting for singleplayer and dedicated servers.

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#2097] opened 2020-01-31 12:12 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Tiny suggestion, saw a player wanting this as they wanted the corpses to pile up.

**Version**
0.9.702.0 unstable.

**Additional information**

seems relatively harmless, I would suggest a server setting but that excludes single player, so perhaps a config/settings menu value, as well as being a server option.

Then at the end of a round, you can convert any remaining corpses to body bags, while in game play keeping corpses beyond a limit. the function of keeping the items is kept, as well as the in game visual if the users hardware can handle the corpse count.

**Comment by Regalis11** [comment] 2020-02-20 10:36
Duplicate of #2309 (this is an older ticket but there's some more info in the newer one, so let's keep that one open instead)

**Closed by Regalis11** 2020-02-20 10:36 UTC
Labels: Code, Feature request
