### ISSUE TITLE
Items with editor-applied color & inventoryicon lose their settings between rounds if held in player inventory

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#2892] opened 2020-05-25 14:04 UTC
Version **- Current Stable**

Items which have had sprite color and inventory icon color settings applied in editor revert back to their prefab defaults when a new campaign round starts if the item is being held within' a character's inventory.

**Additional Information:**

I have not tested with many items, I just have noticed it has been happening to items during campaigns such as: toolboxes, harpoon guns, logic components

**Comment by Regalis11** [comment] 2020-05-25 14:37
Duplicate of #2799

**Closed by Regalis11** 2020-05-25 14:37 UTC
