### ISSUE TITLE
Solution for random disconnecting

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#524] opened 2018-07-24 17:21 UTC
This isn't a solution to prevent disconnecting, but it is something that'll help the people who already got disconnected.

If someone is disconnected, it display that their character had "fainted".

If the person rejoins, they can wake up as the character who fainted.

If not, after two minutes, they become brain dead.

This is because there are some servers where people often get desynced and have to rejoin and wait out the round till they respawn.

**Comment by Regalis11** [comment] 2018-07-24 17:22
Duplicate of #42. Still a good idea though and should definitely be implemented!

**Closed by Regalis11** 2018-07-24 17:22 UTC
Labels: duplicate
