### ISSUE TITLE
Motion detectors detection area don't flip properly in combat mode.

### ISSUE THREAD

**Issue by FamiliarBreakfast** [Regalis11/Barotrauma#1807] opened 2019-09-07 22:48 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.
### 
**Description**
When a submarine on the renegade side is spawned, the motion detector's detection area isn't flipped. This can cause a lot of issues with motion detector hatches, or anything that use off center motion detector radii.

### **Steps To Reproduce**
Start a combat mission for the renegade's side on a submarine with an off center detection area.

### **Version**
v0.9.2.2
**Neofetch output (clientside):**
`OS: Manjaro Linux x86_64 
Kernel: 4.19.62-1-MANJARO 
Uptime: 2 days, 2 mins 
Packages: 1397 (pacman), 9 (flatpak) 
Shell: zsh 5.7.1 
Resolution: 1920x1080, 1920x1080 
DE: KDE 
WM: KWin 
Theme: Breath [KDE], Adwaita [GTK2], Breath [GTK3] 
Icons: Papirus [KDE], Adwaita [GTK2], maia [GTK3] 
Terminal: yakuake 
Terminal Font: Noto Mono 10 
CPU: Intel i3-6100 (4) @ 3.700GHz 
GPU: NVIDIA GeForce GTX 950 
Memory: 3509MiB / 15983MiB `
**Neofetch output (serverside):**
`OS: Ubuntu 19.04 x86_64 
Host: KVM/QEMU (Standard PC (Q35 + ICH9, 2009) pc-q35-3.1) 
Kernel: 5.0.0-13-generic 
Uptime: 32 days, 22 hours, 54 mins 
Packages: 1235 (dpkg) 
Shell: bash 5.0.3 
Terminal: /dev/pts/0 
CPU: AMD EPYC 7501 32- (2) @ 1.999GHz 
GPU: Vendor 1234 Device 1111 
Memory: 488MiB / 3942MiB`

**Comment by rav2n** [comment] 2019-09-08 20:26
https://github.com/Regalis11/Barotrauma/issues/1805

**Comment by Regalis11** [comment] 2019-09-09 07:50
Yep, this has been fixed for upcoming patches. I'll keep this open for now so we don't get more reports about this until the issue is patched.

**Comment by Rokvach** [comment] 2019-09-23 21:56
Tested, this is working correctly. Closing.

**Closed by Rokvach** 2019-09-23 21:56 UTC
Labels: Bug, Code
