### ISSUE TITLE
Server issues (server is up even when not hosting)

### ISSUE THREAD

**Issue by Padex98** [Regalis11/Barotrauma#5727] opened 2021-05-09 21:19 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
no matter if I'm hosting a server or not, my server appears in the serverlist, with playercount locked to three people, with people getting a timeout error each time they try to join.
That server stays up even after restarting my game and/or computer. If i srtart hosting a server with a different name, it doesn't show up in the server list, and the bugged one persists, making it impossible for people to join without a direct connection.

**Steps To Reproduce**
I have no clue why this happens, so I don't know the steps to reproduce it

**Version**
0.13.3.11

**Additional information**
none

**Comment by Cogs16** [comment] 2021-05-09 21:34
same thing has happened for me

**Comment by Regalis11** [comment] 2021-05-11 13:33
Duplicate of https://github.com/Regalis11/Barotrauma/issues/4509

**Closed by Regalis11** 2021-05-11 13:33 UTC
