### ISSUE TITLE
Frequent client-only crashes mid-mission in multiplayer campaign

### ISSUE THREAD

**Issue by frederikmoellers** [Regalis11/Barotrauma#4439] opened 2020-12-06 02:29 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
We're experiencing rather frequent client crashes during rides in our multiplayer game. I have no idea what causes it as we don't seem to be performing anything out of the ordinary. It happens approximately once every 1.5 levels but that's a rough number (sometimes 2-3 times in the same level if we have to retry it that often, sometimes not at all). All players but the host are ejected with the error message below. The host stays in the game and can try to finish the level alone. If he does and the other players join in for the next round, they respawn regularly and can continue playing. 

**Steps To Reproduce**
I'd be glad to try and debug the issue further, but at the moment I have no idea how to reproduce it short of joining our game. Some have speculated that it has something to do with the moving icebergs as the issue has only come up recently and we have started seeing more of them at the same time due to the campaign progress.

**Version**
v0.10.6.2 on Windows 10 x64, revision d0702df35e

**Additional information**
The log file is attached. I have removed the player names for privacy purposes. The console in the main menu (which appears after the crash) also tells me to attach `crashreport_object.bin`, but I can't find that file. I assumed it's a typo, but I can look for it if you give me a pointer.
I can also try to provide the savegame if that helps.

`crashreport_object.log`:
```
ýÿÇ×%Eï¤ïB3¡ã
Index was outside the bounds of the array.
Message length: 2011 (251 bytes)
Read position: 2011
Header: ENTITY_POSITION
Previous header: ENTITY_POSITION
Previous object was 128 bits long (16 bytes)
 
   at Lidgren.Network.NetBitWriter.ReadByte(Byte[] fromBuffer, Int32 numberOfBits, Int32 readBitOffset) in <DEV>\Libraries\Lidgren.Network\NetBitWriter.cs:line 41
   at Lidgren.Network.NetBitWriter.ReadUInt32(Byte[] fromBuffer, Int32 numberOfBits, Int32 readBitOffset) in <DEV>\Libraries\Lidgren.Network\NetBitWriter.cs:line 295
   at Barotrauma.Networking.MsgReader.ReadRangedInteger(Byte[] buf, Int32& bitPos, Int32 min, Int32 max) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\Primitives\Message\Message.cs:line 355
   at Barotrauma.Networking.MsgReader.ReadRangedSingle(Byte[] buf, Int32& bitPos, Single min, Single max, Int32 bitCount) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\Primitives\Message\Message.cs:line 363
   at Barotrauma.Networking.ReadOnlyMessage.ReadRangedSingle(Single min, Single max, Int32 bitCount) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\Primitives\Message\Message.cs:line 713
   at Barotrauma.Character.ClientRead(ServerNetObject type, IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\CharacterNetworking.cs:line 253
   at Barotrauma.Networking.GameClient.ReadIngameUpdate(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2152
 
 - <Host>
 - <Player1>
 - <Player2>
 - <Me>
 - Tigerthresher
 - Crawler
 - Crawler
 - Crawler
 - Tigerthresher
 - Barotrauma.Submarine (Prospector, 37059)
 - Bonethresher
Last console messages:
[06/12/2020 02:14:15] <Me>
[06/12/2020 02:14:15] <Player2>
[06/12/2020 02:14:15] <Player1>
[06/12/2020 02:14:15] <Host>
[06/12/2020 02:14:15] <Player1>
[06/12/2020 02:14:15] <Host>
[06/12/2020 02:14:13] Task count: 0
[06/12/2020 02:13:58] <Player2>
[06/12/2020 02:13:58] <Player1>
[06/12/2020 02:13:58] <Host>
[06/12/2020 01:43:20] <Me>
[06/12/2020 01:43:20] <Player2>
[06/12/2020 01:43:20] <Player1>
[06/12/2020 01:43:20] <Host>
[06/12/2020 01:01:01] <Me>
[06/12/2020 01:01:01] <Player2>
[06/12/2020 01:01:01] <Player1>
[06/12/2020 01:01:01] <Host>
[06/12/2020 01:00:51] Task count: 0
```

In addition to that error message, the following appears in the console
![barotrauma_error](https://user-images.githubusercontent.com/6661317/101269804-dc7e5b80-3772-11eb-92ee-c3513515797d.png)

**Comment by Regalis11** [comment] 2020-12-07 09:02
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3019

**Closed by Regalis11** 2020-12-07 09:02 UTC
