### ISSUE TITLE
[crash] macos SoundManager.SetCategoryMuffle NullReferenceException

### ISSUE THREAD

**Issue by durandal** [Regalis11/Barotrauma#4510] opened 2020-12-13 07:49 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Consistent crashing every ~15 minutes in multiplayer with 4 other players, *maybe* my character consciousness state changing?  Didn't notice a pattern to it.  Crash was to desktop each time.

**Steps To Reproduce**
Ran into this crash 6 times in 3 hour play session didn't notice a specific event driving it.

**Version**
MacOS 10.15.7
Game version 0.11.0.9 (ReleaseMac, branch release, revision c60afcc03b)

**Additional information**
Maybe related to #4504 
[crashreport (13).log](https://github.com/Regalis11/Barotrauma/files/5684311/crashreport.13.log)

Saw this in debug ahead of the NRE

```
[12/12/2020 11:51:04 PM] Error while reading a message from server. {Failed to generate stream buffers: SoundChannel (VoIP (Dr. Dana Scully)), Invalid value}
```

**Comment by Regalis11** [comment] 2020-12-14 12:49
Duplicate of #4504

**Closed by Regalis11** 2020-12-14 12:49 UTC
Labels: Bug, Code, Crash
