### ISSUE TITLE
Music override mods work inconsistently

### ISSUE THREAD

**Issue by MaximMukhanov** [Regalis11/Barotrauma#12116] opened 2023-06-04 09:29 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I've installed a music mod called [SOFA'S MUSIC](https://steamcommunity.com/sharedfiles/filedetails/?id=2518767419) from Steam Workshop.

The sounds seemed to not get overridden by the mod at first, but after going in and out of Submarine Redactor music changed.

To further investigate I've installed another music mod [Music of The Abyss](https://steamcommunity.com/sharedfiles/filedetails/?id=2314354477) and the inconsistent behaviour presented itself there as well.

Further investigating music overrides seem to rather interchange between base game music and pick a track randomly from overrides and base sounds.

### Reproduction steps

1. Install any music mod
2. Launch the game
3. Set mod as active in mods tab
4. Try to go from menu to Submarine designer and back

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
No crash report or logs produced.
```

**Comment by MaximMukhanov** [comment] 2023-06-04 09:31
**Additional data after further testing**

Sound overrides seem to work just fine

**Comment by Regalis11** [comment] 2023-06-04 11:02
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10373

**Closed by Regalis11** 2023-06-04 11:02 UTC
