### ISSUE TITLE
Multiplayer - Enemies have no cooldown for attacks against players except the host

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#7151] opened 2021-11-02 21:06 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Every enemy in the game can attack players with no cooldown, dealing massive damage within a second. The host does not has this problem.

https://www.twitch.tv/darkrider664/v/1194076475?sr=a&t=8659s
https://www.twitch.tv/darkrider664/v/1194076475?sr=a&t=9511s
https://www.twitch.tv/darkrider664/v/1194076475?sr=a&t=9631s
https://www.twitch.tv/darkrider664/v/1194076475?sr=a&t=10217s
https://www.twitch.tv/darkrider664/v/1194076475?sr=a&t=17595s

**Steps To Reproduce**
???

**Version**
0.15.13.0

**Comment by Kaillera** [comment] 2021-11-02 21:22
Seems to be related with the host using PUCS (Morphine)+Auto Injecter (Opium)

**Comment by Kaillera** [comment] 2021-11-02 23:16
Or it could be after just sitting in the level long enough progressing very slowly.

**Comment by Regalis11** [comment] 2021-11-03 11:58
I'm afraid I couldn't find a way to reproduce this. :/ Tested with PUCS and the various combinations of talents + talent afflictions seen in the video, but no luck so far.

**Comment by Kaillera** [comment] 2021-11-03 13:43
We notice that the start of every level, the game plays out fine. Mid level the game starts to desync on new people and eventually slowly kick people out. That's when this starts causing all sorts of things like this.

**Comment by w4rum** [comment] 2021-11-10 19:41
I can confirm this bug, although in our case, it's happening to everyone, probably because we're running a dedicated server.

I'll try to record it next time it occurs and get a savegame. In our case, it was always:
- inside our submarine
- our submarine was flooded
- we were wearing PUCS
- the server was running for longer than two days

I'm not sure if these points contributed to triggering the bug as we don't really have much of a comparison. Yesterday, when only one of us was wearing a PUCS, we didn't encounter this issue, even inside our own flooded submarine and abandoned stations.

As said, I'll try to get you better info next time, and hopefully a way to reproduce this. For now, I can only confirm that we're seeing the same issue.

**Comment by Kaillera** [comment] 2021-11-18 19:49
Still happening in 0.15.15.0

It affects dedicated servers too.

**Comment by Krzeszny** [comment] 2021-12-06 14:31
To test it, I suggest joining a big server with many players and mods. The more mods there are, the bigger the desync, it appears.

**Comment by VitalyArtemiev** [comment] 2022-02-07 17:15
I've had this happen to me while being the host. Both times the server had been running for 2-3 hours, there were only two players including me. There were 4 mods enabled: [ENV] Beacons Extended, EK Utilities, EK Armory and Shipwrecks Extended. 
Both times I was mauled by raptors outside the submarine. The other player does not seem to have this problem in terms of getting hit quickly, but on his end the raptors "looked laggy" while mauling me. Other creatures aren't "laggy" for him. Game version is v0.15.23.0

**Comment by Regalis11** [comment] 2022-02-23 15:16
Hopefully fixed in https://github.com/Regalis11/Barotrauma-development/commit/b76f1a7dc84e48dfc22aa9126111498d6f4572a8 (managed to repro with the steps in https://github.com/Regalis11/Barotrauma/issues/8345)

**Comment by Rokvach** [comment] 2022-04-11 09:17
There hasn't been any sightings of this happening since the fix came out. Seems to be working correctly. Closing.

**Closed by Rokvach** 2022-04-11 09:17 UTC
Labels: Bug, Code
