### ISSUE TITLE
Humans in outpost ignore your behavior of killing them instantly

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#6558] opened 2021-09-03 17:35 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you kill humans instantly in outpost, they will ignore your behavior and your reputation will not change.
![bug2_compress](https://user-images.githubusercontent.com/73634685/132044765-59608ff1-eb23-4198-a886-9259095e046e.gif)

**Version**
0.14.9.0 Windows

**Comment by ekqvist** [comment] 2021-11-18 11:15
Unfortunately, I can't reproduce the issue. I increased the damage of revolver rounds so they will one-shot NPCs, but guards attacked me and other NPCs ran away when I killed someone. It's possible that the issue has already been fixed as a part of something else.

**Comment by itchyOwl** [comment] 2021-11-30 13:50
Possiby fixed -> moving to QA.

**Comment by Rokvach** [comment] 2021-12-09 10:47
I haven't seen any issues with this, seems to have been fixed at some point. Closing.

**Closed by Rokvach** 2021-12-09 10:47 UTC
Labels: Bug, Need more info, Needs testing, Code
