### ISSUE TITLE
Error while reading a message from the server. (Read error: please send us "networkerror_data.log"!)

### ISSUE THREAD

**Issue by Moltzy** [Regalis11/Barotrauma#8955] opened 2022-04-24 16:35 UTC
**Description**
I was trying to test mods after the new update and this error appeared telling me to send this file over to this link.
**Steps To Reproduce**
Modload order:
Attached config_player file
**Version**
Latest (Current) Version.
**Additional information**
I don't actually know if I have to send this error file since I am playing with mods but the console told me to so I will send it nonetheless
[networkerror_data.log](https://github.com/Regalis11/Barotrauma/files/8550089/networkerror_data.log)
[config_player - Copy.txt](https://github.com/Regalis11/Barotrauma/files/8550092/config_player.-.Copy.txt)
.

**Comment by Regalis11** [comment] 2022-10-09 17:08
Duplicate of https://github.com/Regalis11/Barotrauma/issues/1815

**Closed by Regalis11** 2022-10-09 17:08 UTC
