### ISSUE TITLE
Get stuck in lobby frequently between rounds

### ISSUE THREAD

**Issue by Millitron** [Regalis11/Barotrauma#6226] opened 2021-07-02 05:56 UTC
- [X ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I have frequently been getting stuck in the lobby between missions.  I hear everyone chatting like they're in-game, but they cannot hear me.  When stuck, I do not have a "Spectate" button, instead I have the ready to start checkbox,  Leaving the server and rejoining usually does not fix it.  Neither does restarting the game.  I have found verifying my game's integrity with Steam to be the only solution, but even that is not permanent.  Soon it will happen again, sometimes even the next round.

**Steps To Reproduce**
Seems to be campaign only.  Both custom and vanilla subs.  I think it happens to multiple people when it does, servers always seem to be missing more people than just me when I do finally get back in. 

**Version**
Version 0.14.6, Windows 8.1.  No idea what OS the servers' are running

**Additional information**

**Comment by Regalis11** [comment] 2021-07-05 08:35
Duplicate of https://github.com/Regalis11/Barotrauma/issues/5756

**Closed by Regalis11** 2021-07-05 08:35 UTC
