### ISSUE TITLE
Custom medical outpost modules can always generate on habitation outposts

### ISSUE THREAD

**Issue by UnhappyWithMyUsername** [Regalis11/Barotrauma#10779] opened 2022-12-20 19:44 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

When creating and saving medical outpost modules and setting them up to only generate on a custom outpost, they still generate on habitation outposts.

### Reproduction steps

1. Create a custom outpost location (Or use my mod Pirates Ahoy! on the workshop and skip to step 3.)
2. Create a medical outpost module and only allow it to generate on this new custom location
3. Play campaign or use leveleditor to generate default habitation outposts. Some will generate with the custom medical outpost module.

![image](https://user-images.githubusercontent.com/74098498/208752848-3e2b17a7-8bc9-488e-8c1e-54cb33b5c1ef.png)
![image](https://user-images.githubusercontent.com/74098498/208753076-0cd8f52a-5aa6-4181-8fbf-e2e671f5a1f2.png)

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-02-22 10:26
I was unable to reproduce this in the v1.0.2.0 build: has most likely been fixed by the changes we've done to the outpost generation logic.

**Comment by NilanthAnimosus** [comment] 2023-02-28 12:03
Tested against Release/1.1 commit https://github.com/Regalis11/Barotrauma-development/commit/7fced5fab4930f4f0a5af757a241740bad4081e3

At first I thought I couldn't repro this using the mod Pirates Ahoy! ([steam workshop link](https://steamcommunity.com/sharedfiles/filedetails/?id=2885238752&searchtext=pirates)), as the medical outpost module never generated in regular outposts in the level editor.

Changing to city type however, I managed to get this to occur. checking the settings of the module in question I don't think it should be attempting to spawn there so images and details attached:

location type: Outpostlevel
outpost parameters: City
Level seed: IkgJj9E8
submarine: Selkie
Module spawning incorrectly: PIRATEARMORY1

module has been set to location type "PirateOutpost" module type "ArmoryModule".

![image](https://user-images.githubusercontent.com/29177976/221849484-a1ff37b0-a885-457f-aed2-745dc064edbe.png)
![image](https://user-images.githubusercontent.com/29177976/221849509-f5fd74d5-1df1-48bb-9b5a-3b88a303c9f3.png)

**Comment by Regalis11** [comment] 2023-04-20 10:47
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/06367ca7706b39dcbfb877ba1042add33d9b6957

> The generator was allowed to choose a "wrong" kind of module (e.g. normal module in abandoned outpost or vice versa) if it couldn't find any valid place for the correct kind of module. Now if we can't find a valid place for a required module, we retry generating the whole outpost, the same way we do if the selected modules can't be placed without overlaps. Only on the last retry we resort to the wrong kinds of modules.

**Comment by Jasontti** [comment] 2023-07-18 11:51
Tested.
No issues found.
Closing ticket.

**Closed** 2023-07-21 12:44 UTC
Labels: Bug, Code, Modding
