### ISSUE TITLE
Changing light colors crashes client

### ISSUE THREAD

**Issue by m0unds** [Regalis11/Barotrauma#11713] opened 2023-04-02 05:03 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I was adjusting light colors in a stock submarine and it caused my client to crash.

### Reproduction steps

1. Start multiplayer campaign
2. Leave station
3. Edit light color with a screwdriver
4. Change light color and hit enter
5. Crash

### Bug prevalence

Happens regularly

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 04/01/2023 22:59:52)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

14984747362A6EE8B69319866DD5C730

Game version 1.0.8.0 (ReleaseWindows, branch release/1.0-hotfix, revision 08ecc207eb)
Graphics mode: 3840x1600 (Fullscreen)
VSync ON
Language: English
Selected content packages: Vanilla
Level seed: Skadi's Cauldron64Katreus Linea93
Loaded submarine: Dugong (41A1FA1DBA3DE1717309FD93AE6C3B07)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)

System info:
    Operating system: Microsoft Windows NT 10.0.22621.0 64 bit
    GPU name: NVIDIA GeForce RTX 4080
    Display mode: {Width:3840 Height:1600 Format:Color AspectRatio:2.4}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: System.Collections.Generic.IEnumerable`1[Barotrauma.GUITextBox] <ReceiveSpecialInput>g__GetAndSortTextBoxes|133_3(Barotrauma.GUIComponent)
Stack trace: 
   at Barotrauma.GUITextBox.<ReceiveSpecialInput>g__GetAndSortTextBoxes|133_3(GUIComponent parent) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBox.cs:line 801
   at Barotrauma.GUITextBox.<ReceiveSpecialInput>g__SelectNextTextBox|133_4(GUIListBox listBox) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBox.cs:line 804
   at Barotrauma.GUITextBox.ReceiveSpecialInput(Keys key) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBox.cs:line 792
   at EventInput.KeyboardDispatcher.EventInput_KeyDown(Object sender, KeyEventArgs e) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\EventInput\KeyboardDispatcher.cs:line 41
   at Microsoft.Xna.Framework.SdlGamePlatform.SdlRunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 150
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[04/01/2023 22:44:40] m0unds
[04/01/2023 22:44:40] Vilehydra
[04/01/2023 22:44:40] Jubstep
[04/01/2023 22:44:40] CupofFriedDAKKA
[04/01/2023 22:44:40] g1Guardian
[04/01/2023 22:26:20] Vilehydra
[04/01/2023 22:26:20] Jubstep
[04/01/2023 22:26:20] CupofFriedDAKKA
[04/01/2023 22:26:20] g1Guardian
[04/01/2023 22:26:19] Received STARTGAMEFINALIZE packet. Round init status: Started
[04/01/2023 22:26:19]  -16: QueryServerRules (GetServers, 逆天下潜会, 120.48.102.51), WaitingForActivation
[04/01/2023 22:26:19]  -15: QueryServerRules (GetServers, Foxtrot's test server, 47.93.188.231), WaitingForActivation
[04/01/2023 22:26:19]  -14: QueryServerRules (GetServers, Xiao, 180.76.101.236), WaitingForActivation
[04/01/2023 22:26:19]  -13: QueryServerRules (GetServers, 交流至少打字\麦克风|mod服|难度可能偏难, 43.139.216.169), WaitingForActivation
[04/01/2023 22:26:19]  -12: QueryServerRules (GetServers, 石村号, 124.222.174.253), WaitingForActivation
[04/01/2023 22:26:19]  -11: QueryServerRules (GetServers, 海底常沉号~纯净服~较流畅【qq群566368898】, 43.142.48.3), WaitingForActivation
[04/01/2023 22:26:19]  -10: QueryServerRules (GetServers, Das Boot In Europa, 8.130.52.134), WaitingForActivation
[04/01/2023 22:26:19]  -9: QueryServerRules (GetServers, 萌新互助战役QQ群588073889；模组包搜索合集：【�, 101.42.255.254), WaitingForActivation
[04/01/2023 22:26:19]  -8: QueryServerRules (GetServers, Pztao, 81.70.41.48), WaitingForActivation
[04/01/2023 22:26:19]  -7: QueryServerRules (GetServers, USS Untergang, 188.172.228.216), WaitingForActivation
[04/01/2023 22:26:19]  -6: QueryServerRules (GetServers, [DE/AT/CH] Gewuerzgurkenland, 91.2.221.38), WaitingForActivation
[04/01/2023 22:26:19]  -5: QueryServerRules (GetServers, [ESP] Barotrauma Hispano, 91.121.46.202), WaitingForActivation
[04/01/2023 22:26:19]  -4: QueryServerRules (GetServers, Taco Tuesdays, 162.235.195.229), WaitingForActivation
[04/01/2023 22:26:19]  -3: QueryServerRules (GetServers, SS Solitude. Liberate the Seperatists, 104.32.19.103), WaitingForActivation
[04/01/2023 22:26:19]  -2: QueryServerRules (GetServers, SubmarineStation13, 174.34.198.166), WaitingForActivation
[04/01/2023 22:26:19]  -1: QueryServerRules (GetServers, Boatso, 104.225.216.149), WaitingForActivation
[04/01/2023 22:26:19]  -0: LobbyQuery.RequestAsync (1), WaitingForActivation
[04/01/2023 22:26:19] Task count: 17
[04/01/2023 22:26:17] Generating an outpost for the end of the level... (Location: Katreus Linea Habitation Outpost, level type: LocationConnection)
[04/01/2023 22:26:17] Generating an outpost for the start of the level... (Location: Skadi's Cauldron Habitation Outpost, level type: LocationConnection)
[04/01/2023 22:26:17] Level identifier: coldcavernsadvanced
[04/01/2023 22:25:21] Attempting to open ALC device "OpenAL Soft on Realtek Digital Output (Realtek USB Audio)"
[04/01/2023 22:25:20] Logged in as m0unds (SteamID STEAM_1:1:3130270)
```

**Comment by m0unds** [comment] 2023-04-02 05:08
Pressing enter is the important part - clicking outside the RGB value area doesn't crash. Entering values and hitting enter does.

**Comment by Regalis11** [comment] 2023-04-02 15:45
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11563

**Closed by Regalis11** 2023-04-02 15:45 UTC
