### ISSUE TITLE
Pets are Intruders 

### ISSUE THREAD

**Issue by Greedy-Coffee** [Regalis11/Barotrauma#11514] opened 2023-03-14 14:39 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

NOTE: 
This happened in single player campaign on the Orca 2 submarine with 9 crew members(mine character included).
Version of game was the newest one, on 14.03.2023 just the day after Barotrauma 1.0 Update.

Description:
Firstly after I loaded my save file (wasn't playing on it for a long time) everything was normal, but after I connect to the outpost and game loaded it the bug happened, AI on Captain reported about intruders - orange boys in amount of 2. After that, well 3 SO under AI control rush to the Command Room (Where Orange Boys was at) and shoot both of boys down. I reload save file hoping this will fix the problem, but it's not happened even after 5 reloads. My guess is the problem about AI after the update of it in 1.0 Update. 

P.S 
For an example and kind of copying for this issue took another one by Benzin73 with a opposite problem(with a crew member killed by pet, while mine is a pet-killing by crew members. Pretty funny actually). Sorry and thanks, I guess?

### Reproduction steps

- Start a single player campaign
- Get a few extra crew members(i guess at least one needs to be SO - Security Officer)
- Then an egg and hatch it (maybe it happening only with Orange Boys, didn't test it)
Bug should appear after connection to the outpost or maybe even after the egg hatched. 

### Bug prevalence

Happens every time I play

### Version

v1.0.7.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-03-15 14:15
Could not reproduce
![image](https://user-images.githubusercontent.com/14351070/225336104-5ce631ee-30c2-4f54-a08c-3c6aecead6ae.png)

**Comment by Greedy-Coffee** [comment] 2023-03-15 17:25
That's strange, maybe something wrong with my save file?

I wanted to attach a rar file but video was too big, so I created a google drive folder and here is link for it:
[](https://drive.google.com/drive/folders/144G0E6BI_MBVkvPWeqi6YLt3CrnJE0XG?usp=share_link)

Oh and as could be see on video Orange boys are totally intruders now due to whatever room one of them in right now, have the Intruders Alert in it.

Don't mind 2 save files, one that's written on english is a copy and other is an original (Bug showed up in original save, I made copy just in case it won't happen on it).

**Comment by R4to0** [comment] 2023-04-06 03:48
Same issue here, went to a outpost with very low reputation and my pet is considered as hostile/enemy by the bots.

Single player campaign, game version 1.0.8.0, happens every time I play.

[1680752524.webm](https://user-images.githubusercontent.com/3608184/230267008-b3d8659b-867c-40e7-9c84-03ad62147bb9.webm)


Save file attached: [Save0.zip](https://github.com/Regalis11/Barotrauma/files/11166194/Save0.zip)

**Comment by Agent-Delta** [comment] 2023-04-06 18:39
I don't know if this info is helpful, but we had something very similar happen in a multiplayer campaign about a week ago. We had 2 defense bots on board, but nobody seemed to be reacting adversely to them in any way. However, while trying to test whether or not they would follow us properly, our captain dragged one outside the sub and one of our bot-manned turrets fired on him. Just to see what would happen I dragged the other defense bot outside and let it go; the same turret, manned by a bot crew member, immediately fired on and destroyed the defense bot. Unlike with R4to0, this happened while we were in the middle of a traversal round, not docked at an outpost.

I attempted to recreate this scenario in sandbox but it did not happen again.

**Comment by Crasher105** [comment] 2023-04-08 23:12
Also have issue with defense bots being treated as hostile when docking at a station with Hostile reputation. Crew members will flee/attack them despite the bots not attacking them or behaving any differently. Results in a lot of friendly fire and injuries due to the bots exploding.

**Comment by Rokvach** [comment] 2023-05-02 07:45
Tested,working correctly. Closing.

**Closed by Rokvach** 2023-05-02 07:45 UTC
Labels: Bug, Code
