### ISSUE TITLE
Husk Appendage limb depth issue

### ISSUE THREAD

**Issue by Emanthealmighty** [Regalis11/Barotrauma#4724] opened 2021-01-12 12:46 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

**The husk appendage does not "react" to other limbs belonging to its host as expected.**
Essentially, it is impossible to properly make the husk appendage properly appear behind certain limbs and in front of others, it seems like it can only either be in front of / behind the entire character the appendage is attached to.

Regardless of what limb the husk appendage is actually attached to, these are the three different results.
Only tested with the default human husk so far.

If the husk appendage has a limb depth higher than the head, it will appear behind every single one of the main ragdoll's limbs. 

If the husk appendage has an equal or lower depth than the head that's not 0.0, it will appear in front of every single one of the main ragdoll's limbs, except for those that have a limb depth of 0.0.

If the husk appendage has a depth of 0.0, then it will appear in front of every single one of the main ragdoll's limbs.

**Example**

The default husk appendage has a limb depth of 0.5 across the board, this means that it appears behind every single one of a human's limbs, because the lowest depth they have is 0.16 (the left hand). And up until this point, everything works properly.

If we want to make it appear BEHIND the head (0.1 depth), but in front of the left arm (0.15 depth), then that means we should give it a depth higher than 0.1 but lower than 0.15, however if we do that, **the appendage will still appear behind the head and the left arm**.

The moment we give the husk appendage a depth equal or lower than the human head limb depth (0.1), the appendage will appear in front of the head, but also in front of every one of the human's limbs, including those that have a lower depth than it, but excluding those that have a limb depth of 0 (the right hand); if we change its depth to 0, then it will appear in front of those too.

**Version**

Version: 0.11.0.10 - Public Branch. OS: Windows 10.

**Comment by itchyOwl** [comment] 2021-02-26 09:54
Tested and confirmed that there's something weird here. I thought it was just about using deformable sprites with normal sprites, but it's not.

However, with the vanilla husk appendage on human husks the issue is not big enough to notice. To my eyes this issue is only relevant if someone tries to make the appendage longer.

I changed the depth of the appendage to 0.11, which should be correct, but does not render correctly: Regalis11/Barotrauma-development@90e7543.

Also fixed the same issue with husks, where the fix works as it should: Regalis11/Barotrauma-development@32f7b7b.

**Comment by Emanthealmighty** [comment] 2021-09-03 18:12
As of v0.1500.1.0 (Unstable), this issue also affects the new mudraptor and spineling genes, because they use an husk affliction in order to attach new appendages to humans. The issue is considerably more noticeable while using mudraptor genes and laying down with your left arm going over your head.

![image](https://user-images.githubusercontent.com/9964331/132049261-cb6e6f6c-1811-4c85-96b8-734d74120220.png)

**Comment by Regalis11** [comment] 2021-11-25 09:27
Seems to have been caused by the same bug as https://github.com/regalis11/barotrauma/issues/6649, should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/dde5d8606086e9cd6e5106fc6272cab33fde0a99

**Comment by Rokvach** [comment] 2021-11-25 09:49
Yeah no issues here, closing.

**Closed by Rokvach** 2021-11-25 09:49 UTC
Labels: Bug, Code, Low prio
