### ISSUE TITLE
cannot create a item in fabricator (singleplayer)

### ISSUE THREAD

**Issue by Danil650** [Regalis11/Barotrauma#7801] opened 2021-12-16 14:22 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
when using the fabricator by two characters, after creating an item, it will not be possible to make it (the create button will not be active, but other items can be made)

**Steps To Reproduce**
I put a fuel rod on the creation
ordered the bot to wait
took control of the bot and began to improve the fabricator
switched to an electrician and began to create rods
after creating 7 rods, 8 did not want to be created

**Version**
0.15.21.0 , windows 10 x64

**Additional information**
![image](https://user-images.githubusercontent.com/32590763/146384361-d7f0af70-b3d4-4e4b-9ab1-dbcffbfba955.png)
it happens both in multiplayer and in singleplayer (if you leave the bot on the fabricator)
like that
![image](https://user-images.githubusercontent.com/32590763/146385546-3aa9939d-d2e4-4a72-8465-b57179d7501b.png)
this bug not fixing by restarting. The cause of this bug is most often fuel rods

**Comment by ekqvist** [comment] 2021-12-16 14:35
Based on the descriptions, this sounded like a likely duplicate of #7790 with clearer steps to reproduce. Could also be related to (or even a duplicate of) #7739, as noted on the earlier issue.

**Comment by Regalis11** [comment] 2021-12-16 15:47
I'm afraid I could not find a way to reproduce this. I'm not sure I understood the steps correctly though, is this accurate?
1. I start fabricating a fuel rod as an engineer
2. I order the engineer to wait
3. I switch to a mechanic and start tinkering the fabricator
4. I switch back to the engineer and continue creating rods

**Comment by gerakis** [comment] 2021-12-16 17:24
I saw this happen last night too. I also dont know whats causing it, but can confirm the bug exists. I simply could not make anything. Hitting the button to create an item did nothing.

**Comment by vasa228pupok** [comment] 2021-12-16 17:42
@Regalis11 

1 start fabricating a fuel rod as an engineer
2 order the **_mechanic_** to wait (this causes the mechanic to freeze on one action (tinkering))
3 switch to a mechanic and start tinkering the fabricator
4 switch back to the engineer and continue creating rods

I remembered one situation: the same bug, but in multiplayer, the button was not pressed. A friend told me that I was trying to **create** a rod (although in fact I wanted to **recharge** the rod). I hope this fact helps

**Comment by Regalis11** [comment] 2022-01-31 17:28
Hmm, I still haven't been able to find a way to reproduce this. :/ There were issues in syncing the fabricator in multiplayer that might've caused this (and should be fixed in the latest unstable), but does don't seem to be affecting single player, so this must be something else.

**Comment by vasa228pupok** [comment] 2022-02-01 05:46
@Regalis11 
I figured out how I did 
I clicked on the creation of the rod at the last second of its creation, and it broke the fabricator

**Comment by vasa228pupok** [comment] 2022-02-01 06:00
https://youtu.be/x0sE25QSO0Q

**Comment by Regalis11** [comment] 2022-02-01 10:34
Thank you for the extra info and video!

I'm sorry to say but we still couldn't get this to happen (both me and @ekqvist tried to replicate the steps in the video, but no luck). I suspect it takes some more specific circumstances to occur - maybe something related to the way you're juggling the items between the cabinet, your inventory, the storage container and the input slots (even though I couldn't get it to happen even by trying to do the exact same steps as in the video).

There's been some fixes to the fabricator in the latest unstable builds though, relating to the way it pulls items from containers in the player's inventory and linked cabinets, and it _could_ be that some of those fix this issue as well. So let's keep an eye out for this and see if it still occurs after the unstable build is released as a public patch.

**Comment by vasa228pupok** [comment] 2022-02-01 18:16
@Regalis11 
after conducting an experiment with cleaned items, it was found out that the game does not count the last uranium (this can still be seen during crafting, instead of dropping the stack, the fabricator moves to another stack. this can be seen in the video 0:25)
https://youtu.be/7xsUiFPzJPo
and also when crafting fertilizers, you can not use this "broken" uranium
![image](https://user-images.githubusercontent.com/32590763/152026404-3dbfbeb3-4578-49ee-aa44-8bfce7abb5e6.png)
so this error is not in the fabricator

**Closed** 2022-02-07 15:40 UTC
Labels: Bug, Need more info, Needs testing, Code
