### ISSUE TITLE
My game crush every game on others servers(

### ISSUE THREAD

**Issue by mshebatin** [Regalis11/Barotrauma#4523] opened 2020-12-14 19:51 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
YA odin raz zashol na server druga s modami, posli vkhoda v igru igra krashnulas', posle etogo ona stala krashit'sya pri kazhdom podklyuchenii k igre etogo druga Situatsiya povtoryayet'sya so vsemi

volume_up
183 / 5000
Результаты перевода
I once went to a friend's server with mods, after entering the game, the game crashed, after which it began to crash every time this friend connected to the game
The situation repeats with everyone

**Steps To Reproduce**

Mac

**Additional information**
[crashreport_object.log](https://github.com/Regalis11/Barotrauma/files/5691255/crashreport_object.log)
<img width="1280" alt="Снимок экрана 2020-12-14 в 22 23 10" src="https://user-images.githubusercontent.com/56454169/102128274-ad48a800-3e5e-11eb-8a23-776e43500a96.png">

**Comment by Regalis11** [comment] 2020-12-15 07:55
Duplicate of #4430

**Closed by Regalis11** 2020-12-15 07:55 UTC
