### ISSUE TITLE
Using explosive ammo causes karma losses due to hull damage

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#4416] opened 2020-11-30 22:02 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
On servers with karma enabled, players that use explosive ammo, for example in coilguns (and very likely using explosive weapons to fight monsters inside of the submarine), damage the hull ever so slightly but it makes them lose karma so much that they get kicked out of the server eventually.

**Steps To Reproduce**
Fire explosive ammunition inside the hull or at a monster next to the hull - especially with railguns and coilguns.

**Version**
v0.10.6.2 (Windows)

**Additional information**
-

**Comment by Regalis11** [comment] 2020-12-07 08:11
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/d5fc96ff8b435eafc4415535a247b8e929eb2768. There should be a cap to how much karma can decrease per second as a result of damage done to structures, but it wasn't working as intended, so for example launching a nuke close to the sub could cause a huge karma penalty. Now the karma decrease when damaging walls should be capped to 15 per second.

This however doesn't affect cases where you're doing small amounts of damage over time, for example when firing lots of explosive coilgun bolts. We may need some additional measures to deal with those, maybe by not reducing karma if a projectile that hit a monster does some collateral damage.

**Comment by Ek-Videogames** [comment] 2020-12-09 17:17
Hypothetically you should also be able to lose karma from piercing coilgun shots that bounce off enemies and end up falling back into the hull 🐛

**Comment by Krzeszny** [comment] 2020-12-09 19:51
I'd suggest making it so that if a shot causes damage to hull and a monster at the same time, no negative karma is induced.
However, if a shot causes damage to hull, a monster and a player (all 3 at the same time), karma works normally (like damage to players).

There's also the problem that cutting into the hull from outside causes lots of negative karma - a huge problem when a player get stuck inside the armor of a modded sub and needs to cut through the hull - this is when you swim through armor into more armor but can't swim out.

**Comment by Rokvach** [comment] 2021-01-19 20:55
Tested, working correctly. Closing.

**Closed by Rokvach** 2021-01-19 20:55 UTC
Labels: Bug, Code, Design
