### ISSUE TITLE
[Unstable] mildly appropriate position to repair reactor on Camel

### ISSUE THREAD

**Issue by DrinkFromTheCup** [Regalis11/Barotrauma#12392] opened 2023-07-23 16:16 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Check Engineer bot's position.
![Screenshot from 2023-07-23 15-39-03](https://github.com/Regalis11/Barotrauma/assets/81986452/ae29a9a8-a2d2-4c92-b66f-bc50f75befe1)
He's repairing Reactor - and looking badass while doing so.
Probably not a bug - but I think that it might be useful to bring this up for evaluation (and further reference).

### Reproduction steps

Park engineer bot with full complement of repair tools somewhere above Reactor in vanilla Camel. Somewhere to the left so diagonal ladder to Reactor will have higher priority for bot movement.
Break Reactor.
Issue an order to fix it to the engineer bot.
(with some unspecified chance) be amused.

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

Today's Unstable (v1.1.5.0)

### Which operating system did you encounter this bug on?

Linux

**Comment by itchyOwl** [comment] 2023-08-01 11:21
Could be addressed by repositioning the reactor or the ladder. I don't think the issue is serious enough for attempting any code level fix on it.

**Comment by JeroonBosch** [comment] 2023-08-01 11:43
I personally don't think it's an issue that really needs fixing. It doesn't cause any harm, it just looks funny (which imo is part of the ragdoll physics, it's always going to have funny moments and that's a good thing I think)

**Closed** 2023-08-01 11:44 UTC
Labels: wontfix, Design, Low prio
