### ISSUE TITLE
Sub Editor - History "Undo" does not restore wired connections

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#8129] opened 2022-01-30 15:28 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When restoring remote objects wired connections are not being restored.

**Steps To Reproduce**
https://user-images.githubusercontent.com/93348499/151706034-40fab61f-a0ee-4bd1-9227-ac6712bc7fbd.mp4

**Version**
v0.15.23.0, Vanilla 0.9 (Windows 10-x64).

**Additional information**
I don’t know why I didn’t write this earlier. If you accidentally remove an object, it can turn into a nightmare!
Not the worst case for an example:
![Image 002_18-35](https://user-images.githubusercontent.com/93348499/151706369-244c6ba5-9f68-48f1-b407-74b9820caf89.png)

**Comment by ekqvist** [comment] 2022-01-30 23:17
Duplicate of #5373

**Closed by ekqvist** 2022-01-30 23:17 UTC
