### ISSUE TITLE
[1.0] Game crashes when leaving the initial station (readStream was disconnected unexpectedly)

### ISSUE THREAD

**Issue by AzureNocte** [Regalis11/Barotrauma#11381] opened 2023-02-26 23:08 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In multiplayer, I select campaign mode, start with 3 AI and submarine Camel, everytime when I leave the initial station, the game freezes but the background music is still playing.

### Reproduction steps

1. start multiplayer campaign
2. select missions and destination and go in 
3. game freezes

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 02/26/2023 23:56:54)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

A350E5FBA1CD47197DDE4B6C9156D334

Game version 1.0.4.0 (ReleaseWindows, branch release/1.0, revision 335748c836)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync OFF
Language: Simplified Chinese
Selected content packages: Vanilla
Level seed: Androgeos Linea60Dolgovskoy80
Loaded submarine: Camel (8EF807BD13D48235B6ED5D55CA47D22E)
Selected screen: Barotrauma.RoundSummaryScreen
SteamManager initialized
Client (Round hadn't been started)

System info:
    Operating system: Microsoft Windows NT 10.0.22000.0 64 bit
    GPU name: NVIDIA GeForce RTX 3060 Laptop GPU
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: readStream was disconnected unexpectedly (System.Exception)
Target site: Void CheckPipeConnected(System.String, System.IO.Pipes.AnonymousPipeServerStream)
Stack trace: 
   at Barotrauma.Networking.ChildServerRelay.CheckPipeConnected(String name, AnonymousPipeServerStream pipe) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 164
   at Barotrauma.Networking.ChildServerRelay.UpdateRead() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 175
   at System.Threading.Thread.StartCallback()

Last debug messages:
[02/26/2023 23:51:12] Generating an outpost for the end of the level... (Location: Dolgovskoy前哨站, level type: LocationConnection)
[02/26/2023 23:51:11] Generating an outpost for the start of the level... (Location: Androgeos Linea居住前哨站, level type: LocationConnection)
[02/26/2023 23:51:11] Level identifier: coldcavernsadvanced
[02/26/2023 23:51:04] Azure Nocte
[02/26/2023 23:48:39] Server running slowly (58 updates/s)!
[02/26/2023 23:48:37] Azure Nocte
[02/26/2023 23:48:34] Received STARTGAMEFINALIZE packet. Round init status: Started
[02/26/2023 23:48:34] Task count: 0
[02/26/2023 23:48:34] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[02/26/2023 23:48:31] Generating an outpost for the start of the level... (Location: Androgeos Linea居住前哨站, level type: Outpost)
[02/26/2023 23:48:31] Level identifier: outpostlevel
[02/26/2023 23:47:25] Lobby created!
[02/26/2023 23:46:46] Attempting to open ALC device "OpenAL Soft on Speaker (Realtek(R) Audio)"
[02/26/2023 23:46:41] Logged in as Azure Nocte (SteamID STEAM_1:0:171865524)
```

**Comment by Regalis11** [comment] 2023-03-01 10:56
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7985. If you still have the save file available, posting that in the other ticket might help us diagnose this. Thank you and sorry for the inconvenience!

**Closed** 2023-03-01 11:03 UTC
Labels: Bug, Duplicate, Code, Crash
