### ISSUE TITLE
Modded - AI crew stuck attempting to load welding fuel into modded repairtools

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#5190] opened 2021-03-07 08:36 UTC
When given a modded repair tool that uses a non-weldingtank as its fuel item and then ordered to repair leaks, bots will become stuck trying to find the nearest welding fuel tank and continuing to pick it up and then fail to place it into the repair tool. Bots do seem to be able to correctly identify valid tools by their tags, but do not seem to take any consideration for any tool that does not have containment & item-requirement for anything other than welding fuel.

**Edit:**
There does not seem to be a 'universal' tag for repair tools either, or if there is bots do not recognize it when deciding where to find tools.

**Comment by Regalis11** [comment] 2021-04-13 07:52
You need to have the tag "weldingfuel" in the fuel item. Tested this with a custom item repair tool and it seems to be working as intended, moving to QA

**Comment by itchyOwl** [comment] 2021-04-14 08:23
The "universal" tag for welding tool is "weldingequipment". Use that for custom welding tools. And if you use a custom fuel, use "weldingfuel", like Regalis said.

Note that the "RepairTool" component is used for both welding tool and plasma cutter. It's not actually used for repairing anymore, like it used to be.

**Comment by Rokvach** [comment] 2021-04-14 22:21
Closing

**Closed by Rokvach** 2021-04-14 22:21 UTC
Labels: Bug, Code, Low prio, Modding, Needs testing

**Comment by Ek-Videogames** [comment] 2021-04-16 15:24
> You need to have the tag "weldingfuel" in the fuel item. Tested this with a custom item repair tool and it seems to be working as intended, moving to QA

However "weldingfuel" is not its own tag, it is just the same as the item ID used by welding fuel. The issue this presents is it allows bots (and players) to **put wrong fuel types into vanilla welding tool** . 
Due to ` <Containable items="weldingfuel,oxygensource" /> `

Ex.
![image](https://user-images.githubusercontent.com/55356135/115047067-2a843800-9ea6-11eb-9f34-a0a1e4069c6d.png)

**Comment by itchyOwl** [comment] 2021-04-19 10:06
> > You need to have the tag "weldingfuel" in the fuel item. Tested this with a custom item repair tool and it seems to be working as intended, moving to QA
> 
> However "weldingfuel" is not its own tag, it is just the same as the item ID used by welding fuel. The issue this presents is it allows bots (and players) to **put wrong fuel types into vanilla welding tool** .
> Due to `<Containable items="weldingfuel,oxygensource" />`
> 

That's not true: "weldingfuel" is tag used by referencing any kind of welding fuel. The identifier of the vanilla welding fuel tank is "weldingfueltank". It's possible that there's still references using identifiers where we should use tags in some placecs, but I don't see that's the case here:
![image](https://user-images.githubusercontent.com/5370738/115218639-6ff76e00-a10f-11eb-8e01-c9d47bd4d892.png)

However, if you are referring to #5527, it should now be fixed by separating "weldingfuel" and "weldingtoolfuel".
