### ISSUE TITLE
Reactor generating power for batteries even though the batteries are fully charged

### ISSUE THREAD

**Issue by Peternocode** [Regalis11/Barotrauma#6345] opened 2021-07-20 14:40 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I am in the submarine editor, on the "Hemulen" shuttle, I made a structure in which the reactor charges the batteries through the shield. The problem is that if the batteries are fully charged, the reactor will generate as much energy as set by the battery charging rate, but they are already charged. and the energy generated by the reactor goes nowhere, while the consumption is non-zero.

**Steps To Reproduce**
If you connect the reactor to the battery through one shield, then there are no problems. If the reactor is connected to the battery in series through two shields, then the problem will appear.

**Version**
v0.14.6.0(ReleaseWindows, branch release, revision 12d7084c07

**Additional information**
![Снимок экрана (407)](https://user-images.githubusercontent.com/87709257/126343562-76315326-ae62-4965-b22a-8c11dbd0b86b.png)
![Снимок экрана (408)](https://user-images.githubusercontent.com/87709257/126343573-d70450ce-b29a-45a4-a37f-25971f34e5d3.png)
![Снимок экрана (406)](https://user-images.githubusercontent.com/87709257/126343582-d784b35f-f1ec-4c8e-9a96-b8449e37fd49.png)
![Снимок экрана (405)](https://user-images.githubusercontent.com/87709257/126343593-2c6f107f-edb2-4b16-9199-8901ea7bf89c.png)
![Снимок экрана (410)](https://user-images.githubusercontent.com/87709257/126343605-d871f10c-44ef-457f-9c9d-a806c20c0477.png)
![Снимок экрана (409)](https://user-images.githubusercontent.com/87709257/126343616-db5d9f6b-fcef-42d2-b590-40e7bb2d4682.png)

**Comment by Regalis11** [comment] 2021-07-22 13:16
Duplicate of https://github.com/Regalis11/Barotrauma/issues/4880

**Closed by Regalis11** 2021-07-22 13:16 UTC
