### ISSUE TITLE
Gene harvester talent appears to work on pets, including the defense/defence bot

### ISSUE THREAD

**Issue by FourGreenFields** [Regalis11/Barotrauma#10837] opened 2022-12-28 16:52 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I grabbed my pets using a medic who had the gene harvester talent unlocked, and a piece of unidentified genetic materials appeared in its inventory. Later, I grabbed my defence bot, and a piece of unidentified genetic materials dropped to the ground.

Unsure whether it working on pets is intentional, but working on human-made robots very much seems like a bug.

### Reproduction steps

1. Start a test in the subeditor
2. Grant the "gene harvester" talent to self via console
3. Spawn a group of defence bots via console
4. Grab several of the bots, paying attention to dropping items

### Bug prevalence

Happens every now and then

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by JeroonBosch** [comment] 2023-01-03 12:32
Changed it to exclude machines now, but pets will still drop (as intended) genes

**Comment by Regalis11** [comment] 2023-01-12 09:37
Tested and couldn't find any issues, closing.

**Closed by Regalis11** 2023-01-12 09:37 UTC
Labels: Bug, Code, Design
