### ISSUE TITLE
Teleport bug with ruins

### ISSUE THREAD

**Issue by SimonTheSkink** [Regalis11/Barotrauma#7067] opened 2021-10-29 03:38 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Began to explore new ruins, got attacked by small red enemies inside the ruins, escaped with them on me, and teleported nearly a kilometer from my location the moment I exited the ruins. Found myself trapped in the middle of the ground unable to move on all sides.

**Steps To Reproduce**
I simply began to exit the ruins on a scooter, the small red enemies attached to me. The moment I went through the opening to the outside I teleported away a kilometer to the upper left of the map.

**Version**
0.15.12.0 Windows 10

**Additional information**
![20211028233612_1](https://user-images.githubusercontent.com/93362696/139371600-71c13244-2891-44b2-944a-1125b9112f49.jpg)

**Comment by SeagullTown** [comment] 2021-10-31 17:12
Just had this happen to me as well. had 2 jellyfish attached to me and when i swam outside the ruin i was teleported under the map.

**Comment by itchyOwl** [comment] 2021-11-01 12:45
So it's probably caused by the Swarmfeeders latching. I had similar issues while implementing the latching behavior, but I thought that I got it fixed. Apparently not entirely.

**Comment by Farranghoul** [comment] 2021-11-04 20:28
Had the same issue happen to me today. I'll go over the steps I went though; entered the alien ruins, found and recovered an alien trinket, scanned the first objective, picked up the scanner, continued exploration, attacked by swarmfeeders, fought them off as best I could, retreated to the entrance, exited the ruins, found myself teleported approximately 400 meters west from the submarine.

**Comment by itchyOwl** [comment] 2021-11-09 14:11
Fixed in Regalis11/Barotrauma-development@9a5687a.

**Comment by Lithosagym** [comment] 2021-11-18 15:36
Tested, swarm feeders no longer teleport you great distances when leaving a ruin of sub with them latched on, fixed.

**Comment by Rokvach** [comment] 2021-11-18 17:02
Closing.

**Closed by Rokvach** 2021-11-18 17:02 UTC
Labels: Bug, Code, High prio
