### ISSUE TITLE
Inventories not in sync

### ISSUE THREAD

**Issue by SaulApostle** [Regalis11/Barotrauma#1724] opened 2019-06-29 09:23 UTC
Different players see different contents in the same box
![C 5CF{Q8QN}2GYY3AH$MIVT](https://user-images.githubusercontent.com/11502419/60382207-817f0a00-9a92-11e9-84e8-569392c88058.png)
This is a transportation task. The real content of the box is nitroglycerin.

9.0.7

**Comment by Regalis11** [comment] 2020-01-26 17:13
Could have been caused by #2042, lets move this to Review/QA and close it if the issue no longer resurfaces

**Comment by Rokvach** [comment] 2020-02-07 20:51
Seems to be working, Closing.

**Closed by Rokvach** 2020-02-07 20:51 UTC
Labels: Bug, Code, High prio, Networking, Waiting
