### ISSUE TITLE
Crash on toggling off Sandbox filter in Server browser.

### ISSUE THREAD

**Issue by Varntex** [Regalis11/Barotrauma#2711] opened 2020-04-26 02:12 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When ticking off the sandbox option in the multiplayer browser, the game crashes.
 
**Steps To Reproduce**
Opening the server browser and toggling off the sandbox filter.

**Version**
Using Windows 10
Game version: 0.9.9.0, revision 0534150c8

**Additional information**
I have done no modding to the system, no changing of settings. All I have done is completed the training and played a tiny bit of the campaign.

**Crash Report:**

```
Barotrauma Client crash report (generated on 26.04.2020 04:01:12)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


B88397013C2378C4A99C3E19DEBEE54F


Game version 0.9.9.0 (ReleaseWindows, branch release, revision 0534150c8)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Selected content packages: Vanilla 0.9, New Content Package
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.ServerListScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.18363.0 64 bit
    GPU name: Intel(R) UHD Graphics 630
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,7777778}
    GPU status: Normal


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void FilterServers()
Stack trace: 
   at Barotrauma.ServerListScreen.FilterServers()
   at Barotrauma.ServerListScreen.<>c__DisplayClass70_0.<CreateUI>b__26(GUITickBox tickBox)
   at Barotrauma.GUITickBox.set_Selected(Boolean value)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime)
   at Barotrauma.GameMain.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Barotrauma.Program.Main(String[] args)


Last debug messages:
[26.04.2020 04:00:59] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[26.04.2020 04:00:59] Content package load order: Vanilla 0.9  |  New Content Package
[26.04.2020 04:00:59] Content package load order: Vanilla 0.9  |  New Content Package
[26.04.2020 04:00:57] Attempting to open ALC device "OpenAL Soft"
[26.04.2020 04:00:57] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[26.04.2020 04:00:56] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[26.04.2020 04:00:55] Logged in as ****** (SteamID STEAM_*******)

```

**Comment by Regalis11** [comment] 2020-04-26 08:05
Duplicate of #2677

This happens due when trying to filter servers in the server list based on game mode. We've got a hotfix coming for this issue soon, but for now it should be possible to work around it by not trying to filter the server list. Sorry for the trouble!

**Closed by Regalis11** 2020-04-26 08:05 UTC
