### ISSUE TITLE
Favorite servers list problem

### ISSUE THREAD

**Issue by Hegny** [Regalis11/Barotrauma#10142] opened 2022-10-23 09:31 UTC
If add a server to Favorite and restart Barotrauma server is listed as offline.
The server's endpoint in Data/favoriteservers.xml is changed from
`111.222.333.444:12345`
to
`[::ffff:111.222.333.444]:12345`
which makes not possible to connect to that server again.

It looks like all representation of IP addresses are like that (for example, command "clientlist" gives the same format of addresses and all log files too)

**Comment by Regalis11** [comment] 2022-10-24 09:12
I'm afraid I could not find a way to reproduce this. I tested favoriting a bunch of dedicated servers from the server list, and I don't seem to have any issues connecting into to any of them:

![image](https://user-images.githubusercontent.com/14351070/197491288-a2bd8a05-e57b-4cba-987c-23a13a804ef3.png)

**Comment by Hegny** [comment] 2022-10-24 18:31
> I'm afraid I could not find a way to reproduce this. I tested favoriting a bunch of dedicated servers from the server list, and I don't seem to have any issues connecting into to any of them:
> 
> ![image](https://user-images.githubusercontent.com/14351070/197491288-a2bd8a05-e57b-4cba-987c-23a13a804ef3.png)

It doesn't happen every time. I run 3 different dedicated servers and have 3-5 reports a day from players about that issue. I also can catch it from time to time. Here is an example of not working entry in favoriteservers.xml. I have added this server an hour ago.
![image](https://user-images.githubusercontent.com/22501679/197596851-97af54ae-582c-46fe-9e20-b7ce4bd3e91c.png)
Here is a screenshot of the results of clientlist command. Newly installed dedicated server, no mods
![image](https://user-images.githubusercontent.com/22501679/197598768-51988f2d-d9a5-40ff-94f0-ac2eca4aa546.png)

**Comment by Hegny** [comment] 2022-10-24 18:32
Sorry, I closed it by mistake

**Comment by Hegny** [comment] 2022-10-27 09:44
Sorry, I closed it by mistake

**Comment by Hegny** [comment] 2022-11-13 15:28
It looks like the server address is saved in favoriteservers.xml in IPv6 form making it not possible to connect by IPv4

**Comment by juanjp600** [comment] 2022-11-14 16:12
Potentially related to #9221

**Comment by Rokvach** [comment] 2023-01-05 13:23
PR was already merged but this still needs to be tested on Linux, so can't be closed yet.

**Comment by Rokvach** [comment] 2023-02-13 10:22
There hasn't been any mentioned issues relating to this and the patch has been out for a while now. Seems to be working correctly. Closing.

**Closed by Rokvach** 2023-02-13 10:22 UTC
Labels: Bug, Need more info, Code, Networking, Unstable
