### ISSUE TITLE
Problem with the lighting component

### ISSUE THREAD

**Issue by EgorKorolevskiy** [Regalis11/Barotrauma#11226] opened 2023-02-12 21:27 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When the color decreases (RGBA) (Namely A), the lighting component flickers and stops glowing. If you turn on the shadows of a component in the editor and move away from it, then it glows, or maybe it does not glow. When approaching closely, it does not glow at all. In previous versions everything worked as it should

When the shadows are turned off, the lighting component does not glow at all
![11](https://user-images.githubusercontent.com/106447016/218338125-3971e7c6-e20d-4590-b332-0466bb23596b.png)
![22](https://user-images.githubusercontent.com/106447016/218338126-8b2124d6-d6f7-4f7e-9e2f-bbf4bbac42a6.png)
![33](https://user-images.githubusercontent.com/106447016/218338127-ef8e455c-7aca-4d3f-b778-03f65b4da725.png)
![55](https://user-images.githubusercontent.com/106447016/218338129-d5cdb0cc-3ade-405e-bfd3-579de6430f3f.png)

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-02-13 07:38
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11175

**Closed by Regalis11** 2023-02-13 07:38 UTC
