### ISSUE TITLE
unable to load single player campaign due to error

### ISSUE THREAD

**Issue by DootyFrooty** [Regalis11/Barotrauma#13001] opened 2023-11-10 10:57 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Whenever I load my singleplayer campaign, after the "press any key to continue", doing so forces the game back to the main menu, and a debug console pops up with errors. Can start another campaign and save/load that without issues. First time I have ever had a bug/error in the game. I Don't use any mods. 
![Barotrauma Error](https://github.com/Regalis11/Barotrauma/assets/150436221/c1e3f91e-3fc4-48d0-b0f2-4357c6f584f8)

### Reproduction steps

Just bought the Berilia from the Shipyard and transferred all items to it. Used some time to clean it up and rewire the Reactor with a curitbox from my previous submarine, which worked fine. 
Did 3 missions: Scan ruin, Medical item transport and Praise the honkmother (not 100% which transport missions, but I think those are correct) 
After finishing up the quest, I docked at the next station, then the game crashed to the desktop, giving me an error message, which I didn't capture, because it closed shortly after.
When I loaded my game up again, I couldn't load up my singleplayer campaign 

[Epic Solo Campaign.zip](https://github.com/Regalis11/Barotrauma/files/13318415/Epic.Solo.Campaign.zip)

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Coroutine Barotrauma.SinglePlayerCampaign+<DoLoadInitialLevel>d__26 threw an exception: Specified argument was out of the range of valid values. (Parameter 'index')
   at System.Linq.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument)
   at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
   at Barotrauma.CircuitBoxWire.TryLoadFromXML(ContentXElement element, CircuitBox circuitBox) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CircuitBox\CircuitBoxWire.cs:line 51
   at Barotrauma.Items.Components.CircuitBox.LoadFromXML(ContentXElement loadElement) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Signal\CircuitBox.cs:line 167
   at Barotrauma.Items.Components.CircuitBox.TryInitializeNodes() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Signal\CircuitBox.cs:line 153
   at Barotrauma.Items.Components.CircuitBox.OnMapLoaded() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Signal\CircuitBox.cs:line 148
   at Barotrauma.Item.OnMapLoaded() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 4007
   at Barotrauma.MapEntity.MapLoaded(List`1 entities, Boolean updateHulls) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 814
   at Barotrauma.Submarine..ctor(SubmarineInfo info, Boolean showErrorMessages, Func`2 loadEntities, IdRemap linkedRemap) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Submarine.cs:line 1616
   at Barotrauma.GameSession.StartRound(LevelData levelData, Boolean mirrorLevel, SubmarineInfo startOutpost, SubmarineInfo endOutpost) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 433
   at Barotrauma.SinglePlayerCampaign.DoLoadInitialLevel(LevelData level, Boolean mirror)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\SinglePlayerCampaign.cs:line 269
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 214
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 236
```

**Comment by Regalis11** [comment] 2023-11-10 11:16
Duplicate of https://github.com/Regalis11/Barotrauma/issues/12999. Thank you for providing the save, this should make the issue much easier for us to diagnose! :)

**Closed** 2023-11-10 11:34 UTC
