### ISSUE TITLE
Healthbar isn't at the correct position for large resolutions

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3362] opened 2020-07-13 12:17 UTC
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/5c397d84-9764-4262-ace6-5f85f2e37191)

**Comment by Regalis11** [comment] 2020-07-13 12:33
Duplicate of https://github.com/Regalis11/Barotrauma-development/issues/1653

**Closed by Regalis11** 2020-07-13 12:33 UTC
Labels: Bug, Code, Low prio
