### ISSUE TITLE
Medic can get unlimited XP and Medical skill

### ISSUE THREAD

**Issue by BossCakes21** [Regalis11/Barotrauma#7560] opened 2021-12-01 01:52 UTC
While trying somethings i have come across a little funky thing with the "Advanced Splicing" talent, 

"Whenever you or another crewmember combines or refines Genetic Materials, gain 125 experience and a bonus of 5 to Medical.
This bonus is lost on death." 

If you get a two genes and combine them and then get another gene and try to combine it with the already combined gene, the genes will not combine and it will fail but you will get 250xp and 10 medical skill, and since the genes don't get lost you can do it forever.

This is still bad but when you get the "Combat Medic" talent and you have a high medical skill the game lags and becomes unplayable if it gets to high

thanks hope you fix this <3

**Comment by Regalis11** [comment] 2021-12-01 10:39
This has been partially addressed in the latest unstable version: Advanced Splicing can only increase your skill by a maximum of 100. 

> If you get a two genes and combine them and then get another gene and try to combine it with the already combined gene, the genes will not combine and it will fail but you will get 250xp and 10 medical skill, and since the genes don't get lost you can do it forever.

This is something that hasn't been addressed though, but I was unsure how to reproduce the problem. How can you combine the combined genes a second time? Combining two different types of genes should taint it and prevent it from being combined again, and based on a quick test this seemed to be working correctly (the button cannot be clicked if there's a combined material in the research station).

**Comment by Gravityowl** [comment] 2021-12-24 13:42
I was able to reproduce this by putting stabilozine in the output of a research station and then combining 2 different genes

**Comment by Regalis11** [comment] 2022-01-12 09:51
Closing as a duplicate of https://github.com/Regalis11/Barotrauma/issues/8001

**Closed by Regalis11** 2022-01-12 09:51 UTC
Labels: Bug, Code
