### ISSUE TITLE
Bots should put away the excess fuel rods that they took out of the reactor instead of keeping them

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4194] opened 2020-11-02 07:56 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Whenever bots takes out the excess fuel rods that the reactor was running on, they keep it on their inventory forever.

**Steps To Reproduce**
Put in 2~4 fuel rods into the reactor and run with it.
Have a bot operate the reactor or idle operate it.
Rods are now in their inventory.

**Version**
0.1100.0.1

**Comment by itchyOwl** [comment] 2020-11-06 17:33
Bots now drop the extra fuel rods on ground instead of taking them in their inventory. The bots that are in the idle state or ordered to clean up, should take care of placing the rods back in the containers, when there's time for it.

Implemented in Regalis11/Barotrauma-development@c9910f9.

**Comment by Xeavas** [comment] 2020-11-11 16:20
Working as intended 👍

**Comment by Rokvach** [comment] 2020-11-11 16:27
Closing.

**Closed by Rokvach** 2020-11-11 16:27 UTC
Labels: Code, Feature request
