### ISSUE TITLE
Crash - removing connections in eventeditor crashes the game

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#5541] opened 2021-04-18 13:30 UTC
**Description**
After trying to clear connections a crash happens
![image](https://user-images.githubusercontent.com/59519434/115147359-ef773580-a05a-11eb-889a-64f9680b3161.png)

**Steps To Reproduce**
-eventeditor
-place two nodes
-connect them
-clear connections from one of them

**Version**
Unstable

**Additional information**
crash: 
[crashreport (169).log](https://github.com/Regalis11/Barotrauma/files/6331345/crashreport.169.log)

**Comment by Udrakan** [comment] 2021-04-18 13:35
Edited: Seems removing any connections crashes the game for me

**Comment by 3e849f2e5c** [comment] 2021-04-18 17:13
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2bf2df5db24623a44503847decacd522c196f0ee

Was caused by the recent changes to TextManager

**Comment by Rokvach** [comment] 2021-04-19 13:04
Tested, wasn't able to reproduce. Seems to be working correctly, closing.

**Closed by Rokvach** 2021-04-19 13:04 UTC
Labels: Bug, Code, Crash
