### ISSUE TITLE
In- Sub Suffocation

### ISSUE THREAD

**Issue by KingkumaArt** [Regalis11/Barotrauma#3526] opened 2020-08-08 17:32 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If an AI crew member is wearing a diving suit inside a sub (say, to fix a leak), and runs out of oxygen, they will suffocate and die instead of refilling oxygen or taking the suit off, even if in an air-filled room.
**Steps To Reproduce**
Put crewmember in diving suit in an air filled sub and wait a few minutes.

**Version**
0.10.4.0 - Windows - Steam

**Additional information**
This might be intentional, but the number of times I've been in EVA only to have a crew member drop dead due to me not micromanaging them is getting quite annoying.

**Comment by 3e849f2e5c** [comment] 2020-08-10 10:41
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3333

**Closed by 3e849f2e5c** 2020-08-10 10:41 UTC
