### ISSUE TITLE
Strange particle related crash

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2830] opened 2020-05-14 16:26 UTC
[crashreport (70).log](https://github.com/Regalis11/Barotrauma/files/4629642/crashreport.70.log)
[crashreport (69).log](https://github.com/Regalis11/Barotrauma/files/4629643/crashreport.69.log)
Crash reports I got while playing my mod. Not entirely sure what caused this, going through all of my custom particles in the editor didn't lead to any crashes. 
First crash happened when the sub was just moving along in the water and I was standing still doing nothing.
Second crash happened when bots started attacking some monsters outside.

Edit: possibly may have to do with those new particles everything emits when shot? do I have to declare a new kind of gib particle in any character xmls?

**Comment by Regalis11** [comment] 2020-05-15 07:15
Have you done any changes to the particle prefabs? Looking at the line number, this could be explained by some particle not having any sprites defined in the xml.

**Comment by Regalis11** [comment] 2020-05-15 07:29
I added a warning if there are particles with no sprites, and prevented ParticleManager from instantiating particle prefabs without a sprite. So if it was an issue with the sprite configs, https://github.com/Regalis11/Barotrauma-development/commit/55142aa8c4fda963838e4b4a74134a9b9913324c should fix it

**Comment by Rokvach** [comment] 2020-05-25 17:23
With a lack of info on the cause and no clear way to reproduce this because of it, I will just have to assume that it is now correctly working and close this ticket. Closing.

**Closed by Rokvach** 2020-05-25 17:23 UTC
Labels: Bug, Code, Crash, Modding, Need more info
