### ISSUE TITLE
After the last hitscan projectile in the ranged weapon container is fired, other players cannot see the firing effect.

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#12511] opened 2023-08-17 09:58 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

As the title said.
![2023-08-17 17-54-13 00_00_06-00_00_08](https://github.com/Regalis11/Barotrauma/assets/73634685/7caba962-5163-4c9a-b5a8-c11c7412a7c7)
I didn't test whether it would also happen on non-hitscan projectiles

### Reproduction steps

1. Host a server and start a round
2. Spawn a security officer
3. Give him a rifle with just one bullet
4. Spawn a crawler nearby him
5. He will fires at the monster but you can't see any firing effects

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Other

### -

Multiplayer Hosted from in-game and hosted using a dedicated server

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by zhu-rengong** [comment] 2023-08-17 12:41
I find a workround that spawn a major projectile by the minor projectile launched by ranged weapon:
```xml
  <Item identifier="otfx_flintlockbullet" category="Weapon" tags="" hideinmenus="true">
    <InventoryIcon texture="%ModDir%/OTFX/Items/Weapons/ammo.png" sourcerect="192,384,64,64" origin="0.5,0.5" />
    <Sprite texture="Content/Items/Weapons/weapons_new.png" sourcerect="0,0,2,2" depth="0.55" origin="0.5,0.5" />
    <Body width="10" height="10" density="30" />
    <Projectile characterusable="false" launchimpulse="infinity">
      <StatusEffect type="OnNotContained" target="This" delay="3.0" stackable="false">
        <Remove />
      </StatusEffect>
      <StatusEffect type="OnUse" target="This" delay="0" hiddeningame="true">
        <SpawnItem identifier="otfx_flintlockbulletprojectile" spawnposition="This" count="1" aimspread="0" rotationtype="Collider" rotation="0" />
      </StatusEffect>
    </Projectile>
  </Item>
  <Item identifier="otfx_flintlockbulletprojectile" category="Weapon" tags="" noninteractable="false" hideinmenus="true">
    <InventoryIcon texture="%ModDir%/OTFX/Items/Weapons/ammo.png" sourcerect="192,384,64,64" origin="0.5,0.5" />
    <Sprite texture="Content/Items/Weapons/weapons_new.png" sourcerect="0,0,2,2" depth="0.55" origin="0.5,0.5" />
    <Body width="10" height="10" density="30" />
    <Projectile characterusable="false" hitscan="true" removeonhit="true">
      <Attack structuredamage="35" targetforce="30" itemdamage="35" severlimbsprobability="0.9" penetration="0.55">
        <Affliction identifier="gunshotwound" strength="80" />
        <Affliction identifier="otfx_hindered" strength="200" />
        <Affliction identifier="bleeding" strength="55" />
        <Affliction identifier="bloodloss" strength="5" />
        <Affliction identifier="stun" strength="1.5" />
      </Attack>
      <StatusEffect type="OnImpact" target="UseTarget">
        <ParticleEmitter particle="impactfirearm" particleamount="10" scalemin="1.4" scalemax="2.8" velocitymin="0" scalemultiplier="0.65,0.65" colormultiplier="255,200,200,80" />
      </StatusEffect>
      <StatusEffect type="OnImpact" target="UseTarget">
        <Conditional entitytype="eq Structure" />
        <Conditional hastag="eq door" />
        <ParticleEmitter particle="spark" copyentityangle="true" anglemin="-10" anglemax="10" particleamount="5" velocitymin="-10" velocitymax="-200" scalemin="0.5" scalemax="1" />
      </StatusEffect>
      <StatusEffect type="OnNotContained" target="This">
        <Remove />
      </StatusEffect>
    </Projectile>
  </Item>
```

**Comment by NilanthAnimosus** [comment] 2023-08-21 14:18
Tested against Release/traitor-update commit https://github.com/Regalis11/Barotrauma-development/commit/bfc61bdccee7567cee8afe3a0a471d562c2d1196

The issue is actually the hitscan bullets trajectory line (not the hit effects of the attack itself) not showing up to other clients if its the last round fired in a weapon. It will appear for the client firing the weapon, but the last round fired is invisible to other clients and no muzzle flash appears either (The flash in the gif provided above is actually the bullet striking the character, not the muzzle flash).

They do curiously see effects on where the bullet strikes at the endpoint however.

**Comment by Jasontti** [comment] 2023-08-28 13:45
Tested with clients or bots shooting different weapons.
No issues found.
Closing ticket.

**Closed by Jasontti** 2023-08-28 13:45 UTC
Labels: Bug, Code, Networking
