### ISSUE TITLE
Crash caused by Null value on Linux

### ISSUE THREAD

**Issue by TJesionowski** [Regalis11/Barotrauma#7920] opened 2021-12-24 05:52 UTC
I'm running the game through steam on Ubuntu Studio. Got this crash on startup, though it did not recur when I restarted the game. First time running the new version, go figure.

Anyways, as a developer this looks like the sort of crash log that could be useful, so I'm posting it here. NPCSet.cs line 32 looks maybe a bit long for a single line, but that's all I can gather, since I've no experience with C#.

I hope this is helpful.

```
Barotrauma Client crash report (generated on 12/23/2021 23:36:50)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


C9FC388B49896E300D598B4F97684B5F


Game version 0.15.22.1 (ReleaseLinux, branch release, revision c0b2b09396)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9, Stations from beyond, Dug, Baby Sub, D, ong
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized


System info:
    Operating system: Unix 5.11.0.43 64 bit
    GPU name: 
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: Value cannot be null. (Parameter 'source') (System.ArgumentNullException)
Target site: Void ThrowArgumentNullException(System.Linq.ExceptionArgument)
Stack trace: 
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Barotrauma.NPCSet.Get(String identifier, String npcidentifier) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Map/Outposts/NPCSet.cs:line 32
   at Barotrauma.OutpostGenerationParams..ctor(XElement element, String filePath) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Map/Outposts/OutpostGenerationParams.cs:line 137
   at Barotrauma.OutpostGenerationParams.LoadPresets() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Map/Outposts/OutpostGenerationParams.cs:line 229
   at Barotrauma.GameSettings.RefreshContentPackageItems(IEnumerable`1 files) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameSettings.cs:line 629
   at Barotrauma.GameSettings.EnableRegularPackage(ContentPackage contentPackage) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameSettings.cs:line 435
   at Barotrauma.Steam.SteamManager.<>c__DisplayClass41_0.<InstallWorkshopItem>b__2(Task task, ContentPackage cp) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Networking/SteamManager.cs:line 1123
   at Barotrauma.TaskPool.<>c__DisplayClass7_0`1.<Add>b__0(Task t, Object obj) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Utils/TaskPool.cs:line 65
   at Barotrauma.TaskPool.Update() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Utils/TaskPool.cs:line 77
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 971
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/SDL/SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 59


Last debug messages:
[12/23/2021 23:36:44] Attempting to open ALC device "Built-in Audio Analog Stereo"
[12/23/2021 23:36:43] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[12/23/2021 23:36:42] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[12/23/2021 23:36:41] Logged in as REDACTED (SteamID STEAM_1:1:111452715)
```

**Comment by Regalis11** [comment] 2021-12-29 15:45
Duplicate of https://github.com/Regalis11/Barotrauma/issues/6813

**Closed by Regalis11** 2021-12-29 15:45 UTC
