### ISSUE TITLE
[Unstable] No explosion animation with railgun shells

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2371] opened 2020-02-27 18:03 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When firing railgun shells with explosives in them, no explosion animation is played.

**Version**
~0.9.7.1

**Comment by Regalis11** [comment] 2020-03-01 14:14
I unfortunately wasn't able to reproduce this (tested in single player and multiplayer). Do you recall which explosives this happened with?

**Comment by Kaillera** [comment] 2020-03-01 15:12
All of the grenades.

**Comment by Regalis11** [comment] 2020-04-15 11:20
Could not reproduce in either single player or multiplayer. Moving to Review/QA.
![rggrenade](https://user-images.githubusercontent.com/14351070/79331655-33090200-7f24-11ea-80a9-e79ccf1d6fe2.png)

**Comment by Rokvach** [comment] 2020-04-15 12:02
Didn't the nuclear railgun have a similar issue of no explosion showing up around the patch this was reported in? I have a feeling that this was fixed at that point @Regalis11

**Comment by Regalis11** [comment] 2020-04-15 17:15
Yeah, that was https://github.com/Regalis11/Barotrauma-development/issues/1425

It only affected projectiles that hit a submarine, so if that's where this issue occurs, it should be fixed.

**Comment by Rokvach** [comment] 2020-04-17 03:53
Closing this as I really think that this has already been resolved.

**Closed by Rokvach** 2020-04-17 03:53 UTC
Labels: Bug, Code
