### ISSUE TITLE
[1.0] Mineral spawns seem to be misaligned 

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11347] opened 2023-02-24 02:47 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Some minerals appear to spawn misaligned with their surface. Below are two examples with their associated level seeds.

![image](https://user-images.githubusercontent.com/105495756/221053146-be4a7965-aad9-4dc6-88d4-b14903dafc42.png)
![image](https://user-images.githubusercontent.com/105495756/221053162-65021846-cc70-40ca-9bf0-4e6c25dcb5e8.png)
_Figures 1 and 2. Image showing Fulgurium Chunk deposits spawning upside down._

![image](https://user-images.githubusercontent.com/105495756/221053406-acf8dbd2-66bc-40a4-a786-1371df6c126e.png)
![image](https://user-images.githubusercontent.com/105495756/221053748-74acae1b-6be1-46fc-8b41-4b2eac378b2c.png)
_Figures 3 and 4. Image showing mineral deposits spawning with a northern alignment when it should be eastern (assuming the mineral itself is the anchor point)._

### Bug prevalence

Happens every now and then

### Version

Other

### -

1.0.3.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-02-24 09:38
Thank you for the report!

I'm afraid I could not find a way to reproduce this. If you happen to run into this again, a save file might help us diagnose the issue. I'm testing this in level editor, but could be that it doesn't happen there:

![image](https://user-images.githubusercontent.com/14351070/221144770-c9c5749e-0847-4621-8df6-0acbf5fa82b3.png)

**Comment by ubertpendragon** [comment] 2023-02-24 14:00
Affects minerals spawned by missions

![image](https://user-images.githubusercontent.com/73229309/221197124-28b277a3-9eec-4020-96cb-ec62d4e72a5b.png)

**Comment by Regalis11** [comment] 2023-02-27 11:46
Ah, looks like this only happens in multiplayer. I was able to repro it now, should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/61837c3599e7ef1179704d338a85a456c30c8a2f

**Comment by Xayrlen** [comment] 2023-03-14 00:38
Not only that, but they also sometimes spawn IN the walls. I managed to cut them, however, retrieving is not possible.

Happened on 1.0.7.0
![123](https://user-images.githubusercontent.com/86978521/224862754-faccc5d5-60c1-4ce5-947a-c10e4b3b654b.png)

**Comment by Rokvach** [comment] 2023-05-24 07:05
Tested, working correctly. Can be merged and closed.

**Closed** 2023-05-24 07:43 UTC
Labels: Bug, Code
