### ISSUE TITLE
Loading wrong number of rounds into a gun when trying to do a quick reload

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#8948] opened 2022-04-24 05:46 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Assume the weapon's spare capacity is `m`.
You have `n`(n>m) rounds for this weapon on hotbar slot `x`.
You have equipped the weapon.
Pressing the hotkey `x` or double-click the item on slot `x` results in the weapon being loaded with `n-m` rounds instead of full.

**Steps To Reproduce**
1.equip a revolver with 5 rounds loaded `m=6-5=1`
2.put `n=3` revolver rounds on hotbar slot `1`
3.press hotkey `1` or double-click the hotbar slot `1`
4.you will see the revolver is loaded with `2=n-m` rounds instead of 6 which it should.

**Version**
0.17.12.0 on Windows 10

**Additional information**
You can also reproduce this with a Riot Shotgun because its itemContainer is like the Revolver.

**Comment by Regalis11** [comment] 2022-05-31 07:54
Duplicate of https://github.com/regalis11/barotrauma/issues/8352

**Closed by Regalis11** 2022-05-31 07:54 UTC
Labels: Bug, Code
