### ISSUE TITLE
[0.1001.0] Upgrades are upgrading for no reason for free

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2980] opened 2020-06-05 12:57 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Whenever I purchase upgrades, some times the upgrades increases even more after undocking for free.

![Capture](https://user-images.githubusercontent.com/5086682/83878678-86205980-a70a-11ea-8fa8-59b35eb9bc4a.PNG)

**Version**
0.1001.0

**Comment by 3e849f2e5c** [comment] 2020-06-05 15:40
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1a07fc7a9a20c40cd6267624bfc247c865c3a6ed

Happened because I was accidentally adding current level (6) + new level (7) = 13 instead of current level (6) + pending level (1) = 7.

Steps to reproduce:
- Start a campaign and upgrade pump upgrade to level to level 6 or above
- Undock from the outpost and redock
- Purchase one pump level upgrade making it level 7
- Exit the outpost

**Comment by Rokvach** [comment] 2020-06-13 09:59
No reported cases of this happening in the latest Unstable, closing.

**Closed by Rokvach** 2020-06-13 09:59 UTC
Labels: Bug, Code
