### ISSUE TITLE
[0.1200.0.1 + Hex's HotFix?] P2P Crash when encountering small targets

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4676] opened 2021-01-08 20:29 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
My Steam P2P server crashed as we saw some small targets (crawlers or spinelings?) on our sonar. I could've sworn I have the hotfix dll from Hex. Not sure if commit 6af30e6 fixes this already or if it's a different problem all together.

[servercrashreport.log](https://github.com/Regalis11/Barotrauma/files/5789250/servercrashreport.log)

**Version**
0.1200.0.1 + Hotfix DLL?

**Comment by 3e849f2e5c** [comment] 2021-01-09 02:20
Duplicate of https://github.com/Regalis11/Barotrauma/issues/4561

You do not have the hotfix applied, the game version would show the branch as HEAD instead of dev if it was

**Closed by 3e849f2e5c** 2021-01-09 02:20 UTC
