### ISSUE TITLE
Index was outside the bounds of the array at Barotrauma.Networking.GameClient.ReadIngameUpdate

### ISSUE THREAD

**Issue by R4to0** [Regalis11/Barotrauma#8089] opened 2022-01-24 07:43 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

**Steps To Reproduce**
My friend died with husk infection, before that he dropped all the items, I killed its corpse as when it turned into husk, did all the task of fixing everything in the sub and to do the mission but at the end when I docked I got that error and my friend went to the main menu.

**Version**
Windows 10 64-bit with latest updates, game version stable v0.15.23.0
![image](https://user-images.githubusercontent.com/3608184/150740425-193653ec-0548-4bd4-80b8-e118e35ca425.png)

**Additional information**
Log attached
Console pictures attached (sorry didn't found where they got write to a file or a way to copy everything from it)
All mods being used by the host (me), in the same order as listed here: https://steamcommunity.com/sharedfiles/filedetails/?id=2669599008

[networkerror_data.log](https://github.com/Regalis11/Barotrauma/files/7923551/networkerror_data.log)
![image](https://user-images.githubusercontent.com/3608184/150740577-40085e6a-033b-453b-ba82-2934ac335a0c.png)

Host game console:
![image](https://user-images.githubusercontent.com/3608184/150740783-04d0c3c3-8530-4754-9eef-98bcc16841b7.png)
![image](https://user-images.githubusercontent.com/3608184/150740827-6a08df6f-e1f9-4d06-a6b9-f341a0ad00b1.png)
![image](https://user-images.githubusercontent.com/3608184/150740914-ab5884d1-5b1f-47af-8951-baaaccd0a996.png)

**Comment by Regalis11** [comment] 2022-01-31 11:20
I unfortunately haven't found a way to reproduce this, but based on the error message it seems that the game failed to find the sprite to display at the background of the campaign map for one of the biomes. This could potentially be caused by a bugged mod. I added a null check in https://github.com/Regalis11/Barotrauma-development/commit/0621ebdbe8570fee285024dce4b7ce45a53947e7 that should prevent crashing the game

**Comment by R4to0** [comment] 2022-01-31 21:53
Thanks for checking up! I believe this was being caused by one of the mods I have installed, most likely the **[Into the Abyss](https://steamcommunity.com/sharedfiles/filedetails/?id=2005463692)** which modifies all the outposts in the campaign.

Fortunately I didn't get any more of these crashes but I think I have a backup of a save that had the same happening. Will try once the fix goes to next update and let you know!

**Comment by R4to0** [comment] 2022-02-04 06:37
Found one of my broken saves with this issue, will test with the unstable branch once I get sometime. Not sure if you do testing with mods but I'll let the save here for anyone else to try in case I forget to test later.

[issue8089_save.zip](https://github.com/Regalis11/Barotrauma/files/8000677/issue8089_save.zip)

**Comment by Rokvach** [comment] 2022-02-09 22:05
This hasn't caused any issues to the vanilla gameplay, I think I'm just going to close it. We can always re-open this ticket if it still does happen once the patch is out. Closing.

**Closed by Rokvach** 2022-02-09 22:05 UTC
Labels: Bug, Code, Networking, Modding, Unstable
