### ISSUE TITLE
Updating a mod breaks its English description.

### ISSUE THREAD

**Issue by CaptainSqrBeard** [Regalis11/Barotrauma#12114] opened 2023-06-03 18:01 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

There is a feature in the steam workshop that allows use multiple languages for mod description. But in-game tools for publishing breaks it a little.

When you open publish window, description field tries to use language that uses your steam. But when you click on "Update" button - content of the description constantly overrides only English version, even if you didn't touch the description.

So if you're using non-English language in steam and there is description of the same language in your mod - it will override the English description on update.

### Reproduction steps

1. Use steam with interface language that is not English
2. Make a mod that has description with language that is same as your interface language
3. Update this mod
4. Now this description is also English description

### Bug prevalence

Happens regularly

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-06-04 10:45
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11105

**Closed by Regalis11** 2023-06-04 10:45 UTC
