### ISSUE TITLE
All players losing items upon dock (campaign)

### ISSUE THREAD

**Issue by Katoee** [Regalis11/Barotrauma#4781] opened 2021-01-15 20:47 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

_Description_
All items (Equipped gear and hotbar) Drop on the ground for all players in multiplayer server (6 people) upon loading back into the outpost. It repeated this with 3 missions once docked. Quitting and relogging worked to fix the issue the second time, giving all players their items as we loaded in. Although relogging has not fixed the issue since.

**_**Steps To Reproduce**_**
I could provide my save file, Otherwise i am not sure as it just occurs when we redock after finishing a campaign mission

_Version_
Latest 
(v0.11.0.10) Windows

**Comment by Omarox** [comment] 2021-01-16 09:14
We had the same where inventory would get empty after docking after a successful mission.
But not just that, players other than the captain did not spawn at all.

I could only fix this by decompressing an old save and copying the player inventories from that one into out current save.
So there might have been something wrong there that prevented people from being spawned.

**Comment by xrabohrok** [comment] 2021-01-16 17:29
This sounds similar to #4460 . It was happening then due to someone holding a log with too much text in it.

**Comment by Regalis11** [comment] 2021-01-18 08:16
Duplicate of https://github.com/Regalis11/Barotrauma/issues/4460

**Closed by Regalis11** 2021-01-18 08:16 UTC
Labels: Duplicate
