### ISSUE TITLE
Barotrauma Client crash report (generated on 06.08.2021 18:50:12)

### ISSUE THREAD

**Issue by un-hunt** [Regalis11/Barotrauma#6409] opened 2021-08-06 16:17 UTC
I played for some time on that save and everything was fine, then game crashed while generating a level. The save seems to be lost forever, as when trying to load it, this error appears in the console:

Coroutine Barotrauma.SinglePlayerCampaign+<DoLoadInitialLevel>d__16 threw an exception: Object reference not set to an instance of an object.
   at Barotrauma.WreckAI..ctor(Submarine wreck) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Wreck\WreckAI.cs:line 20
   at Barotrauma.WreckAI.Create(Submarine wreck) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Wreck\WreckAI.cs:line 42
   at Barotrauma.Submarine.CreateWreckAI() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Submarine.cs:line 377
   at Barotrauma.Level.SpawnSubOnPath(String subName, ContentFile contentFile, SubmarineType type) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\Level.cs:line 3115
   at Barotrauma.Level.CreateWrecks() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\Level.cs:line 3366
   at Barotrauma.Level.Generate(Boolean mirror) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\Level.cs:line 1156
   at Barotrauma.Level.Generate(LevelData levelData, Boolean mirror, SubmarineInfo startOutpost, SubmarineInfo endOutpost) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\Level.cs:line 386
   at Barotrauma.GameSession.StartRound(LevelData levelData, Boolean mirrorLevel, SubmarineInfo startOutpost, SubmarineInfo endOutpost) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 398
   at Barotrauma.SinglePlayerCampaign.DoLoadInitialLevel(LevelData level, Boolean mirror)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\SinglePlayerCampaign.cs:line 248
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 244

------------------------------- Also, all existing saves with the same mods become unplayable after trying to load this save.

Barotrauma seems to have crashed. Sorry for the inconvenience! 

EECA616DF2BA4F9511EEC52AB1F63877

Game version 0.14.6.0 (ReleaseWindows, branch release, revision 12d7084c07)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync ON
Language: Russian
Selected content packages: Vanilla 0.9, EK Armory, EK Gunnery, EK Utilities, Pelican Cases, Shipwrecks Extended, Deep Sea Alcohol, [ENV] Beacons Extended, Advanced Medicine, Meaningful Upgrades
Level seed: SaltholeButterdon Linea
Loaded submarine: Humpback (77F1740533BACAA02B883CC006ECF1C4)
Selected screen: Barotrauma.RoundSummaryScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19043.0 64 bit
    GPU name: NVIDIA GeForce RTX 2060
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1,7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void .ctor(Barotrauma.Submarine)
Stack trace: 
   at Barotrauma.WreckAI..ctor(Submarine wreck) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Wreck\WreckAI.cs:line 20
   at Barotrauma.WreckAI.Create(Submarine wreck) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Wreck\WreckAI.cs:line 42
   at Barotrauma.Submarine.CreateWreckAI() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Submarine.cs:line 377
   at Barotrauma.Level.SpawnSubOnPath(String subName, ContentFile contentFile, SubmarineType type) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\Level.cs:line 3115
   at Barotrauma.Level.CreateWrecks() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\Level.cs:line 3366
   at Barotrauma.Level.Generate(Boolean mirror) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\Level.cs:line 1156
   at Barotrauma.Level.Generate(LevelData levelData, Boolean mirror, SubmarineInfo startOutpost, SubmarineInfo endOutpost) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\Level.cs:line 386
   at Barotrauma.GameSession.StartRound(LevelData levelData, Boolean mirrorLevel, SubmarineInfo startOutpost, SubmarineInfo endOutpost) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 398
   at Barotrauma.CampaignMode.<>c__DisplayClass26_0.<<SelectSummaryScreen>b__0>d.MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\CampaignMode.cs:line 265
--- End of stack trace from previous location where exception was thrown ---
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 962
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59

Last debug messages:
[06.08.2021 18:50:09] Generating an outpost for the start of the level... (Location: Salthole, level type: LocationConnection)
[06.08.2021 18:49:59] Transitioning to SaltholeButterdon Linea (current location: Salthole, selected location: Butterdon Linea, leaving sub: Humpback, at start: True, at end: False, transition type: LeaveLocation)
[06.08.2021 18:48:04] Unlocked mission "Добыча артефакта" in the location "Salthole".
[06.08.2021 18:47:55] Unlocked mission "Уничтожить гнездо акульего тигра" in the location "Salthole".
[06.08.2021 18:47:53] Unlocked mission "Взрывной груз" in the location "Salthole".
[06.08.2021 18:47:50] Unlocked mission "Уничтожить гнездо ползуна" in the location "Salthole".
[06.08.2021 18:31:14] Generating an outpost for the start of the level... (Location: Salthole, level type: Outpost)
[06.08.2021 18:31:05] Transitioning to Salthole (current location: Vellamo's Crevasse, selected location: Salthole, leaving sub: Humpback, at start: False, at end: True, transition type: ProgressToNextLocation)
[06.08.2021 18:23:53] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: Mods/EK Utilities/Items/Tools/ekutility_placeableconsoles.png, size: 767x767)
[06.08.2021 18:23:25] OpenAL Soft on Линия (Sennheiser 3D G4ME1) 42
[06.08.2021 18:23:25] OpenAL Soft on Интерфейс SPDIF (Sennheiser 3D G4ME1) 52
[06.08.2021 18:23:25] OpenAL Soft on Микрофон (Sennheiser 3D G4ME1) 45
[06.08.2021 18:23:16] OpenAL Soft on Линия (Sennheiser 3D G4ME1) 42
[06.08.2021 18:23:16] OpenAL Soft on Интерфейс SPDIF (Sennheiser 3D G4ME1) 52
[06.08.2021 18:23:16] OpenAL Soft on Микрофон (Sennheiser 3D G4ME1) 45
[06.08.2021 18:10:14] Generating an outpost for the start of the level... (Location: Salthole, level type: LocationConnection)
[06.08.2021 18:10:13] Generating an outpost for the end of the level... (Location: Vellamo's Crevasse, level type: LocationConnection)
[06.08.2021 18:10:03] Transitioning to SaltholeVellamo's Crevasse (current location: Vellamo's Crevasse, selected location: Salthole, leaving sub: Humpback, at start: True, at end: False, transition type: LeaveLocation)
[06.08.2021 18:08:07] Unlocked mission "Добыча торианита" in the location "Vellamo's Crevasse".
[06.08.2021 18:08:04] Unlocked mission "Добыча артефакта" in the location "Vellamo's Crevasse".
[06.08.2021 18:08:01] Unlocked mission "Взрывной груз" in the location "Vellamo's Crevasse".
[06.08.2021 17:59:42] OpenAL Soft on Линия (Sennheiser 3D G4ME1) 42
[06.08.2021 17:59:42] OpenAL Soft on Интерфейс SPDIF (Sennheiser 3D G4ME1) 52
[06.08.2021 17:59:42] OpenAL Soft on Микрофон (Sennheiser 3D G4ME1) 45
[06.08.2021 17:55:03] Unlocked mission "Добыча артефакта" in the location "Vellamo's Crevasse".
[06.08.2021 17:54:26] Generating an outpost for the start of the level... (Location: Vellamo's Crevasse, level type: Outpost)
[06.08.2021 17:50:28] OpenAL Soft on Линия (Sennheiser 3D G4ME1) 42
[06.08.2021 17:50:28] OpenAL Soft on Интерфейс SPDIF (Sennheiser 3D G4ME1) 52
[06.08.2021 17:50:28] OpenAL Soft on Микрофон (Sennheiser 3D G4ME1) 45
[06.08.2021 17:50:16] OpenAL Soft on Линия (Sennheiser 3D G4ME1) 42
[06.08.2021 17:50:16] OpenAL Soft on Интерфейс SPDIF (Sennheiser 3D G4ME1) 52
[06.08.2021 17:50:16] OpenAL Soft on Микрофон (Sennheiser 3D G4ME1) 45
[06.08.2021 17:49:55] Overriding an affliction or a buff with the identifier 'opiateoverdose' using the file 'Mods/Advanced Medicine/Xml/Afflictions.xml'
[06.08.2021 17:49:55] Overriding an affliction or a buff with the identifier 'burn' using the file 'Mods/Advanced Medicine/Xml/Afflictions.xml'
[06.08.2021 17:49:55] Overriding an affliction or a buff with the identifier 'explosiondamage' using the file 'Mods/Advanced Medicine/Xml/Afflictions.xml'
[06.08.2021 17:49:55] Overriding an affliction or a buff with the identifier 'organdamage' using the file 'Mods/Advanced Medicine/Xml/Afflictions.xml'
[06.08.2021 17:49:55] Overriding an affliction or a buff with the identifier 'gunshotwound' using the file 'Mods/Advanced Medicine/Xml/Afflictions.xml'
[06.08.2021 17:49:55] Overriding an affliction or a buff with the identifier 'bitewounds' using the file 'Mods/Advanced Medicine/Xml/Afflictions.xml'
[06.08.2021 17:49:55] Overriding an affliction or a buff with the identifier 'lacerations' using the file 'Mods/Advanced Medicine/Xml/Afflictions.xml'
[06.08.2021 17:49:55] Overriding an affliction or a buff with the identifier 'blunttrauma' using the file 'Mods/Advanced Medicine/Xml/Afflictions.xml'
[06.08.2021 17:49:55] Overriding an affliction or a buff with the identifier 'internaldamage' using the file 'Mods/Advanced Medicine/Xml/Afflictions.xml'
[06.08.2021 17:49:55] Overriding an affliction or a buff with the identifier 'sufforinpoisoning' using the file 'Mods/Advanced Medicine/Xml/Afflictions.xml'
[06.08.2021 17:49:55] Overriding an affliction or a buff with the identifier 'cyanidepoisoning' using the file 'Mods/Advanced Medicine/Xml/Afflictions.xml'
[06.08.2021 17:49:55] Overriding an affliction or a buff with the identifier 'morbusinepoisoning' using the file 'Mods/Advanced Medicine/Xml/Afflictions.xml'
[06.08.2021 17:49:55] Overriding the CPR settings with 'Mods/Advanced Medicine/Xml/Afflictions.xml'
[06.08.2021 17:49:55] Overriding an affliction or a buff with the identifier 'bloodloss' using the file 'Mods/Advanced Medicine/Xml/Afflictions.xml'
[06.08.2021 17:49:55] Overriding an affliction or a buff with the identifier 'oxygenlow' using the file 'Mods/Advanced Medicine/Xml/Afflictions.xml'
[06.08.2021 17:49:54] Overriding an affliction or a buff with the identifier 'opiateoverdose' using the file 'Mods/Advanced Medicine/Xml/Afflictions.xml'
[06.08.2021 17:49:54] Overriding an affliction or a buff with the identifier 'burn' using the file 'Mods/Advanced Medicine/Xml/Afflictions.xml'
[06.08.2021 17:49:54] Overriding an affliction or a buff with the identifier 'explosiondamage' using the file 'Mods/Advanced Medicine/Xml/Afflictions.xml'
[06.08.2021 17:49:54] Overriding an affliction or a buff with the identifier 'organdamage' using the file 'Mods/Advanced Medicine/Xml/Afflictions.xml'
[06.08.2021 17:49:54] Overriding an affliction or a buff with the identifier 'gunshotwound' using the file 'Mods/Advanced Medicine/Xml/Afflictions.xml'
[06.08.2021 17:49:54] Overriding an affliction or a buff with the identifier 'bitewounds' using the file 'Mods/Advanced Medicine/Xml/Afflictions.xml'
[06.08.2021 17:49:54] Overriding an affliction or a buff with the identifier 'lacerations' using the file 'Mods/Advanced Medicine/Xml/Afflictions.xml'
[06.08.2021 17:49:54] Overriding an affliction or a buff with the identifier 'blunttrauma' using the file 'Mods/Advanced Medicine/Xml/Afflictions.xml'
[06.08.2021 17:49:54] Overriding an affliction or a buff with the identifier 'internaldamage' using the file 'Mods/Advanced Medicine/Xml/Afflictions.xml'
[06.08.2021 17:49:54] Overriding an affliction or a buff with the identifier 'sufforinpoisoning' using the file 'Mods/Advanced Medicine/Xml/Afflictions.xml'
[06.08.2021 17:49:54] Overriding an affliction or a buff with the identifier 'cyanidepoisoning' using the file 'Mods/Advanced Medicine/Xml/Afflictions.xml'
[06.08.2021 17:49:54] Overriding an affliction or a buff with the identifier 'morbusinepoisoning' using the file 'Mods/Advanced Medicine/Xml/Afflictions.xml'
[06.08.2021 17:49:54] Overriding the CPR settings with 'Mods/Advanced Medicine/Xml/Afflictions.xml'
[06.08.2021 17:49:54] Overriding an affliction or a buff with the identifier 'bloodloss' using the file 'Mods/Advanced Medicine/Xml/Afflictions.xml'
[06.08.2021 17:49:54] Overriding an affliction or a buff with the identifier 'oxygenlow' using the file 'Mods/Advanced Medicine/Xml/Afflictions.xml'
[06.08.2021 17:49:48] Overriding an affliction or a buff with the identifier 'opiateoverdose' using the file 'Mods/Advanced Medicine/Xml/Afflictions.xml'
[06.08.2021 17:49:48] Overriding an affliction or a buff with the identifier 'burn' using the file 'Mods/Advanced Medicine/Xml/Afflictions.xml'
[06.08.2021 17:49:48] Overriding an affliction or a buff with the identifier 'explosiondamage' using the file 'Mods/Advanced Medicine/Xml/Afflictions.xml'
[06.08.2021 17:49:48] Overriding an affliction or a buff with the identifier 'organdamage' using the file 'Mods/Advanced Medicine/Xml/Afflictions.xml'
[06.08.2021 17:49:48] Overriding an affliction or a buff with the identifier 'gunshotwound' using the file 'Mods/Advanced Medicine/Xml/Afflictions.xml'
[06.08.2021 17:49:48] Overriding an affliction or a buff with the identifier 'bitewounds' using the file 'Mods/Advanced Medicine/Xml/Afflictions.xml'
[06.08.2021 17:49:48] Overriding an affliction or a buff with the identifier 'lacerations' using the file 'Mods/Advanced Medicine/Xml/Afflictions.xml'
[06.08.2021 17:49:48] Overriding an affliction or a buff with the identifier 'blunttrauma' using the file 'Mods/Advanced Medicine/Xml/Afflictions.xml'
[06.08.2021 17:49:48] Overriding an affliction or a buff with the identifier 'internaldamage' using the file 'Mods/Advanced Medicine/Xml/Afflictions.xml'
[06.08.2021 17:49:48] Overriding an affliction or a buff with the identifier 'sufforinpoisoning' using the file 'Mods/Advanced Medicine/Xml/Afflictions.xml'
[06.08.2021 17:49:48] Overriding an affliction or a buff with the identifier 'cyanidepoisoning' using the file 'Mods/Advanced Medicine/Xml/Afflictions.xml'
[06.08.2021 17:49:48] Overriding an affliction or a buff with the identifier 'morbusinepoisoning' using the file 'Mods/Advanced Medicine/Xml/Afflictions.xml'
[06.08.2021 17:49:48] Overriding the CPR settings with 'Mods/Advanced Medicine/Xml/Afflictions.xml'
[06.08.2021 17:49:48] Overriding an affliction or a buff with the identifier 'bloodloss' using the file 'Mods/Advanced Medicine/Xml/Afflictions.xml'
[06.08.2021 17:49:48] Overriding an affliction or a buff with the identifier 'oxygenlow' using the file 'Mods/Advanced Medicine/Xml/Afflictions.xml'
[06.08.2021 17:49:46] OpenAL Soft on Линия (Sennheiser 3D G4ME1) 42
[06.08.2021 17:49:46] OpenAL Soft on Интерфейс SPDIF (Sennheiser 3D G4ME1) 52
[06.08.2021 17:49:46] OpenAL Soft on Микрофон (Sennheiser 3D G4ME1) 45
[06.08.2021 17:49:40] (Msg) SDR RelayNetworkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[06.08.2021 17:49:40] (Msg) Ping location: sto2=25+2,sto=26+2/25+2,fra=38+3,ams=46+4/45+2,waw=52+5/45+2,par=64+6/47+3,lhr=47+4,vie=54+5/50+3,mad=71+7/68+3,iad=134+13/123+3,sgp=305+30/228+19,gru=249+24
[06.08.2021 17:49:40] (Msg) Ping measurement completed
[06.08.2021 17:49:40] (Debug) Destroying relay 'sof#5 (139.45.193.10:27019)' because initial_ping_timeout
[06.08.2021 17:49:39] (Debug) Destroying relay 'eat#38 (155.133.235.18:27052)' because initial_ping_timeout
[06.08.2021 17:49:37] (Verbose) Communications with routing cluster 'sea' established.
[06.08.2021 17:49:37] (Debug) Destroying relay 'sof#1 (139.45.193.10:27015)' because initial_ping_timeout
[06.08.2021 17:49:37] (Debug) Destroying relay 'sea#75 (205.196.6.74:27051)' because initial_ping_timeout
[06.08.2021 17:49:37] (Debug) Destroying relay 'eat#69 (155.133.235.34:27045)' because initial_ping_timeout
[06.08.2021 17:49:36] (Verbose) Communications with routing cluster 'tyo1' established.
[06.08.2021 17:49:35] (Verbose) Communications with routing cluster 'syd' established.
[06.08.2021 17:49:35] (Verbose) Communications with routing cluster 'sgp' established.
[06.08.2021 17:49:35] (Verbose) Communications with routing cluster 'tyo' established.
[06.08.2021 17:49:35] (Verbose) Communications with routing cluster 'maa' established.
[06.08.2021 17:49:34] (Verbose) Communications with routing cluster 'scl' established.
[06.08.2021 17:49:34] (Verbose) Communications with routing cluster 'lim' established.
[06.08.2021 17:49:34] (Verbose) Communications with routing cluster 'bom' established.
[06.08.2021 17:49:34] (Verbose) Communications with routing cluster 'jnb' established.
[06.08.2021 17:49:34] (Verbose) Communications with routing cluster 'eze' established.
[06.08.2021 17:49:34] (Verbose) Communications with routing cluster 'lax' established.
[06.08.2021 17:49:34] (Verbose) Communications with routing cluster 'vie' established.
[06.08.2021 17:49:34] (Verbose) Communications with routing cluster 'waw' established.
[06.08.2021 17:49:34] (Verbose) Communications with routing cluster 'gru' established.
[06.08.2021 17:49:34] (Verbose) Communications with routing cluster 'ord' established.
[06.08.2021 17:49:34] (Verbose) Communications with routing cluster 'iad' established.
[06.08.2021 17:49:34] (Verbose) Communications with routing cluster 'sto' established.
[06.08.2021 17:49:34] (Verbose) Communications with routing cluster 'sto2' established.
[06.08.2021 17:49:34] (Verbose) Communications with routing cluster 'hkg' established.
[06.08.2021 17:49:34] (Verbose) Communications with routing cluster 'mad' established.
[06.08.2021 17:49:34] (Verbose) Communications with routing cluster 'dxb' established.
[06.08.2021 17:49:34] (Verbose) Communications with routing cluster 'par' established.
[06.08.2021 17:49:34] (Verbose) Communications with routing cluster 'dfw' established.
[06.08.2021 17:49:34] (Verbose) Communications with routing cluster 'lhr' established.
[06.08.2021 17:49:34] (Verbose) Communications with routing cluster 'atl' established.
[06.08.2021 17:49:34] (Verbose) Communications with routing cluster 'ams' established.
[06.08.2021 17:49:34] (Verbose) Communications with routing cluster 'fra' established.
[06.08.2021 17:49:34] (Msg) SDR RelayNetworkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[06.08.2021 17:49:34] (Msg) Performing ping measurement
[06.08.2021 17:49:34] (Msg) Got SDR network config.  Loaded revision 330 OK
[06.08.2021 17:49:34] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[06.08.2021 17:49:25] Attempting to open ALC device "OpenAL Soft on Динамики (Sennheiser 3D G4ME1)"
[06.08.2021 17:48:36] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[06.08.2021 17:48:35] Logged in as UNHUNT (SteamID STEAM_1:1:232878876)

**Comment by Regalis11** [comment] 2021-08-09 08:05
Duplicate of https://github.com/Regalis11/Barotrauma/issues/6187. In the current public version, there's a issue that causes this crash when a wreck contains thalamus organs that have been placed outside hulls. Before the fix is out, it should be possible to work around the issue by disabling the "Shipwrecks Extended" mod.

**Closed by Regalis11** 2021-08-09 08:05 UTC
