### ISSUE TITLE
Server crashes whenever I start it

### ISSUE THREAD

**Issue by abemaden** [Regalis11/Barotrauma#12620] opened 2023-09-05 14:21 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Game's been running pretty well, until nearing the halfway point in The Great Sea. Whenever I'd try to start the server, the server would 9/10 times crash before loading into the sub. In the rare occasion that I didn't crash, my friend, who I'm playing with, would crash. This happened suddenly, and we don't really know what to do because we essentially can't play on our save anymore.
Again, this happened suddenly, and with seemingly no correlation to anything, so I'm not sure how I can describe the reproduction steps? 

### Reproduction steps

1. load the save
2. observe how the server crashes

Here's the save.
[Me_save.zip](https://github.com/Regalis11/Barotrauma/files/12524663/Me_save.zip)

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

Unstable (v1.1.11.0)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Error while reading a message from server. 
Level equality check failed. The level generated at your end doesn't match the level generated by the server (client value FloatingIce: 5C4AC848, server value FloatingIce: 451E6683, level value count: 17, seed: Udaeus Linea67Tara89, sub: Orca2 (A58E635), mirrored: False). Round init status: WaitingForStartGameFinalize. Round start save ID: 4, last save id: 4, pending save id: 4.
   at Barotrauma.Networking.GameClient.ReadStartGameFinalize(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 942
   at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 747
   at Barotrauma.Networking.SteamP2POwnerPeer.HandleMessageForOwner(PeerPacketHeaders peerPacketHeaders, IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2POwnerPeer.cs:line 368
   at Barotrauma.Networking.SteamP2POwnerPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2POwnerPeer.cs:line 242
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 504
```

**Comment by Regalis11** [comment] 2023-09-06 07:05
Duplicate of https://github.com/Regalis11/Barotrauma/issues/12618

**Closed by Regalis11** 2023-09-06 07:05 UTC
