### ISSUE TITLE
Traitor Mode crashes from fatal error 100% of the time

### ISSUE THREAD

**Issue by DanJF** [Regalis11/Barotrauma#11601] opened 2023-03-19 15:54 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While hosting an online match of Barotrauma for 13 players, spectating as host, full server, traitors set to YES with default traitor times in the serversettings.xml, game will attempt to choose spectating host for assignment to traitor team and causes the server to crash from a fatal error.

Link to crash image, steam screenshot: https://steamuserimages-a.akamaihd.net/ugc/2057618192248680183/139379E5794ED0F562593317D76BEFE8755D17A2/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false

This happens even after unsubcribing from all custom subs/content on the workshop, uninstalling and reinstalling Baro, and running Traitor mode with completely default settings.

This is an ongoing bug which had not been resolved last time it was reported by another user: https://github.com/Regalis11/Barotrauma/issues/8896

### Reproduction steps

1. Choose "Host Server" from the main menu. Casual game mode setting, 13 players.
2. Set traitors to "YES". Does not matter whether or not bots are present.
3. Populate server with players to maximum capacity.
4. As host, choose to play as Spectator.
5. Launch the round.
6. When the timer triggers to select a traitor, game will attempt to select host/spectator for assignment to traitor team, and crash from fatal error.

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Barotrauma.LocalizedString get_StartMessageServerText()
Stack trace: 
   at Barotrauma.Traitor.Objective.get_StartMessageServerText() in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Traitors\Objective.cs:line 67
   at Barotrauma.Traitor.Greet(GameServer server, String codeWords, String codeResponse, MessageSender messageSender) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Traitors\Traitor.cs:line 33
   at Barotrauma.Traitor.TraitorMission.Start(GameServer server, TraitorManager traitorManager, CharacterTeamType team) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Traitors\TraitorMission.cs:line 229
   at Barotrauma.TraitorManager.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Traitors\TraitorManager.cs:line 176
   at Barotrauma.Networking.GameServer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Networking\GameServer.cs:line 384
   at Barotrauma.GameMain.Run() in <DEV>\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 329
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 78
```

**Comment by Regalis11** [comment] 2023-03-19 17:38
Thank you for the report! 

I was able to reproduce this now with these steps. It doesn't seem like the host gets selected as a traitor through; as I'd commented on the previous ticket, dead players or spectators can't get selected as the traitor. The problem was the way the server tried to construct a message to the host about the traitor mission starting, before the mission had been properly initialized and the traitor assigned.

Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7f8b18e02853ff99548fac430d3e52cb0f8a0bed

**Comment by DanJF** [comment] 2023-03-21 04:59
Fixed link goes to 404. :<

Either way though, thank you for your time and effort to examine a fix. Traitor mode has given me untold hours of countless fun and make friends around the world, and I'm grateful for any fix that can help us play together again!

**Comment by Regalis11** [comment] 2023-03-22 02:01
> Fixed link goes to 404. :<

That's a link to our private repository (just for our internal use) - the fix isn't publicly available just yet. But hopefully we can get it out soon. Sorry for the inconvenience!

**Comment by Rokvach** [comment] 2023-04-17 08:08
Tested, working correctly. Closing.

**Closed by Rokvach** 2023-04-17 08:08 UTC
Labels: Bug, Code, Crash
