### ISSUE TITLE
Problems with assigning orders to characters when they all have very similar skill levels

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4296] opened 2020-11-12 20:39 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When assigning orders to your crew if they all have very similar skill levels, the orders aren't necessarily given to characters that has no orders or idle, but the one that you've already given orders to.

**Steps To Reproduce**
1. Create New Campaign
2. Use Set Skill on your characters to have something like 100 Helm, 60 Weapons, 50 Electrical/Mechanical/Medical on all of them.
3. Assign orders like Fix Leaks and Fix Damaged Systems.

**Version**
~0.1100.0.5

**Comment by ekqvist** [comment] 2020-11-25 10:18
I believe this hasn't got anything to do with similar skill levels, but with the changes to the quick assignment logic a while back and how it doesn't prioritize idle characters anymore. This is essentially a duplicate of #4386 where I also included a bit more reasoning for the changes. I will close this one as a duplicate.

**Closed** 2020-11-25 10:19 UTC
Labels: Code, Duplicate
