### ISSUE TITLE
[Unstable] Oxygen Generators and Oxygen Shelves don't refill Oxygen Tanks

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11843] opened 2023-04-15 00:54 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This issue occurred on a P2P multiplayer server.

The oxygen generator doesn't refill oxygen tanks despite being powered. Oxygen shelves also do not refill oxygen tanks. There were early rounds near the start of the campaign where the oxygen generator would refill oxygen tanks, but as of recent sessions it doesn't work at all.

![image](https://user-images.githubusercontent.com/105495756/232173763-1ab23350-5466-4fbd-9738-72af23b03bf4.png)
_Figure 1. Oxygen generator not refilling oxygen tanks._

![image](https://user-images.githubusercontent.com/105495756/232173765-350e2190-a25d-45a9-bd45-5070b0095c4d.png)
_Figure 2. Oxygen shelves not refilling oxygen tanks._

![image](https://user-images.githubusercontent.com/105495756/232173776-b29fbd87-33c5-45a0-89ac-626b10d54717.png)
_Figure 3. Oxygen generator being wired and powered._

![image](https://user-images.githubusercontent.com/105495756/232173778-f48a91b9-9100-4c86-bdb0-72afd926ba43.png)
_Figure 4. Oxygen shelf being wired and powered._

### Reproduction steps

1. Have empty/low oxygen tanks
2. Put them in the oxygen generator or a wired oxygen shelf
3. Observe how they don't refill

### Bug prevalence

Happens every time I play

### Version

Unstable (v1.1.4.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-04-15 13:18
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11822

**Closed by Regalis11** 2023-04-15 13:18 UTC
