### ISSUE TITLE
Unable to re-join and spectate a server after playing barotrauma in two different computers

### ISSUE THREAD

**Issue by Sir-Crusher** [Regalis11/Barotrauma#11096] opened 2023-01-30 01:49 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

My steam and barotrauma clients are installed on an external hard drive. I had to stop playing on one computer and restarted the game on another. When I joined the server and attempted to spectate, the error happened

### Reproduction steps

1. leave game
2. open game on another pc
3. join server

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
There was an error initializing the round. {Mission equality check failed. Mission count doesn't match the server. Server: killspinelingswarm1, client: , game session: )}
   at Barotrauma.Networking.GameClient.ReadStartGameFinalize(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 891
   at Barotrauma.Networking.GameClient.StartGame(IReadMessage inc)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 1591
```

**Comment by Regalis11** [comment] 2023-01-30 17:02
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10497

**Closed by Regalis11** 2023-01-30 17:02 UTC

**Comment by Sir-Crusher** [comment] 2023-01-30 18:52
I forgot to mention in the issue that I joined the same server I had played in before. After registering the issue I managed to join again when the submarine docked on an outpost. The other players said my name appeared in the player list twice.
