### ISSUE TITLE
Crash when Tab list during Navigation

### ISSUE THREAD

**Issue by Valenwe** [Regalis11/Barotrauma#2753] opened 2020-05-01 17:47 UTC
Barotrauma Client crash report (generated on 01/05/2020 19:45:25)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

023CCD07C102F6331CAD29D2EADB01E0

Game version 0.9.9.1 (ReleaseWindows, branch release, revision 1968ab79f)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: RWEiZ6a5
Loaded submarine: NUCLEAR U-31 MK2 (F44672C8CD6EF3AAE42D29E6E9F58B9E)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)

System info:
    Operating system: Microsoft Windows NT 10.0.18363.0 64 bit
    GPU name: NVIDIA GeForce GTX 1650
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void CreateNameWithPermissionIcon(Barotrauma.Networking.Client, Barotrauma.GUILayoutGroup)
Stack trace: 
   at Barotrauma.TabMenu.CreateNameWithPermissionIcon(Client client, GUILayoutGroup paddedFrame)
   at Barotrauma.TabMenu.CreateMultiPlayerClientElement(Client client)
   at Barotrauma.TabMenu.CreateMultiPlayerList(Boolean refresh)
   at Barotrauma.TabMenu.CreateCrewListFrame(GUIFrame crewFrame)
   at Barotrauma.TabMenu.SelectInfoFrameTab(GUIButton button, Object userData)
   at Barotrauma.TabMenu..ctor()
   at Barotrauma.GameSession.ToggleTabMenu()
   at Barotrauma.GameSession.UpdateProjSpecific(Single deltaTime)
   at Barotrauma.GameScreen.Update(Double deltaTime)
   at Barotrauma.GameMain.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Barotrauma.Program.Main(String[] args)

Last debug messages:
[01/05/2020 19:43:20] Marcel le sociopathe
[01/05/2020 19:43:20] UnDo
[01/05/2020 19:43:20] Hammerheadspawn
[01/05/2020 19:43:20] Valenwe
[01/05/2020 19:43:07] Hammerheadspawn
[01/05/2020 19:40:46] Marcel le sociopathe
[01/05/2020 19:40:46] UnDo
[01/05/2020 19:40:46] Taran
[01/05/2020 19:40:46] Koba Timur
[01/05/2020 19:40:46] Valenwe
[01/05/2020 19:37:15] Marcel le sociopathe
[01/05/2020 19:37:15] UnDo
[01/05/2020 19:37:15] Taran
[01/05/2020 19:37:15] Koba Timur
[01/05/2020 19:37:15] Valenwe
[01/05/2020 19:30:57] Marcel le sociopathe
[01/05/2020 19:30:57] UnDo
[01/05/2020 19:30:57] Taran
[01/05/2020 19:30:57] Koba Timur
[01/05/2020 19:30:57] Valenwe
[01/05/2020 19:30:32] Marcel le sociopathe
[01/05/2020 19:30:32] UnDo
[01/05/2020 19:30:32] Taran
[01/05/2020 19:30:32] Koba Timur
[01/05/2020 19:30:32] Valenwe
[01/05/2020 19:29:54] Marcel le sociopathe
[01/05/2020 19:29:54] UnDo
[01/05/2020 19:29:54] Taran
[01/05/2020 19:29:54] Koba Timur
[01/05/2020 19:29:54] Valenwe
[01/05/2020 19:29:54] Marcel le sociopathe
[01/05/2020 19:29:54] UnDo
[01/05/2020 19:29:54] Taran
[01/05/2020 19:29:54] Koba Timur
[01/05/2020 19:29:54] Valenwe
[01/05/2020 19:25:46] Marcel le sociopathe
[01/05/2020 19:25:46] UnDo
[01/05/2020 19:25:46] Taran
[01/05/2020 19:25:46] Koba Timur
[01/05/2020 19:25:46] Valenwe
[01/05/2020 19:20:40] UnDo
[01/05/2020 19:20:40] Taran
[01/05/2020 19:20:40] Koba Timur
[01/05/2020 19:20:40] Valenwe
[01/05/2020 19:20:16] UnDo
[01/05/2020 19:20:16] Taran
[01/05/2020 19:20:16] Koba Timur
[01/05/2020 19:20:16] Valenwe
[01/05/2020 19:20:16] UnDo
[01/05/2020 19:20:16] Taran
[01/05/2020 19:20:16] Koba Timur
[01/05/2020 19:20:16] Valenwe
[01/05/2020 19:14:50] UnDo
[01/05/2020 19:14:50] Taran
[01/05/2020 19:14:50] Koba Timur
[01/05/2020 19:14:50] Valenwe
[01/05/2020 19:14:42] UnDo
[01/05/2020 19:14:42] Taran
[01/05/2020 19:14:42] Koba Timur
[01/05/2020 19:14:42] Valenwe
[01/05/2020 19:14:41] UnDo
[01/05/2020 19:14:41] Taran
[01/05/2020 19:14:41] Koba Timur
[01/05/2020 19:14:41] Valenwe
[01/05/2020 19:14:40] UnDo
[01/05/2020 19:14:40] Taran
[01/05/2020 19:14:40] Frenchie
[01/05/2020 19:14:40] Koba Timur
[01/05/2020 19:14:39] Valenwe
[01/05/2020 19:10:35] Taran
[01/05/2020 19:10:35] Frenchie
[01/05/2020 19:10:35] Koba Timur
[01/05/2020 19:10:35] Raddy
[01/05/2020 19:10:35] Valenwe
[01/05/2020 19:10:35] Taran
[01/05/2020 19:10:35] Frenchie
[01/05/2020 19:10:35] Koba Timur
[01/05/2020 19:10:35] Raddy
[01/05/2020 19:10:35] Valenwe
[01/05/2020 19:10:32] Taran
[01/05/2020 19:10:32] Frenchie
[01/05/2020 19:10:32] Koba Timur
[01/05/2020 19:10:32] Raddy
[01/05/2020 19:10:32] Valenwe
[01/05/2020 19:05:25] Taran
[01/05/2020 19:05:25] Frenchie
[01/05/2020 19:05:25] Koba Timur
[01/05/2020 19:05:25] Raddy
[01/05/2020 19:05:25] Valenwe
[01/05/2020 19:04:45] Taran
[01/05/2020 19:04:45] Frenchie
[01/05/2020 19:04:45] Koba Timur
[01/05/2020 19:04:45] Raddy
[01/05/2020 19:04:45] Valenwe
[01/05/2020 19:04:45] Taran
[01/05/2020 19:04:45] Frenchie
[01/05/2020 19:04:45] Koba Timur
[01/05/2020 19:04:45] Raddy
[01/05/2020 19:04:45] Valenwe
[01/05/2020 19:02:23] Taran
[01/05/2020 19:02:23] Frenchie
[01/05/2020 19:02:23] Koba Timur
[01/05/2020 19:02:23] Raddy
[01/05/2020 19:02:23] Valenwe
[01/05/2020 19:02:00] Taran
[01/05/2020 19:02:00] Frenchie
[01/05/2020 19:02:00] Koba Timur
[01/05/2020 19:02:00] Raddy
[01/05/2020 19:02:00] Valenwe
[01/05/2020 19:01:12] Taran
[01/05/2020 19:01:12] Frenchie
[01/05/2020 19:01:12] Koba Timur
[01/05/2020 19:01:12] Raddy
[01/05/2020 19:01:12] Valenwe
[01/05/2020 19:01:11] Taran
[01/05/2020 19:01:11] Frenchie
[01/05/2020 19:01:11] Koba Timur
[01/05/2020 19:01:11] Raddy
[01/05/2020 19:01:11] Valenwe
[01/05/2020 18:56:08] Taran
[01/05/2020 18:56:08] Frenchie
[01/05/2020 18:56:08] Koba Timur
[01/05/2020 18:56:08] Raddy
[01/05/2020 18:56:08] Valenwe
[01/05/2020 18:56:02] Taran
[01/05/2020 18:56:02] Frenchie
[01/05/2020 18:56:02] Koba Timur
[01/05/2020 18:56:02] Raddy
[01/05/2020 18:56:02] Valenwe
[01/05/2020 18:55:47] Taran
[01/05/2020 18:55:47] Frenchie
[01/05/2020 18:55:47] Koba Timur
[01/05/2020 18:55:47] Raddy
[01/05/2020 18:55:47] Valenwe
[01/05/2020 18:55:47] Taran
[01/05/2020 18:55:47] Frenchie
[01/05/2020 18:55:47] Koba Timur
[01/05/2020 18:55:47] Raddy
[01/05/2020 18:55:47] Valenwe
[01/05/2020 18:55:47] Taran
[01/05/2020 18:55:47] Frenchie
[01/05/2020 18:55:47] Koba Timur
[01/05/2020 18:55:47] Raddy
[01/05/2020 18:55:47] Valenwe
[01/05/2020 18:55:45] Taran
[01/05/2020 18:55:45] Frenchie
[01/05/2020 18:55:45] Koba Timur
[01/05/2020 18:55:45] Raddy
[01/05/2020 18:55:45] Valenwe
[01/05/2020 18:55:44] Taran
[01/05/2020 18:55:44] Frenchie
[01/05/2020 18:55:44] Koba Timur
[01/05/2020 18:55:44] Raddy
[01/05/2020 18:55:44] Valenwe
[01/05/2020 18:55:43] Taran
[01/05/2020 18:55:43] Frenchie
[01/05/2020 18:55:43] Koba Timur
[01/05/2020 18:55:43] Raddy
[01/05/2020 18:55:43] Valenwe
[01/05/2020 18:54:06] Taran
[01/05/2020 18:54:06] Frenchie
[01/05/2020 18:54:06] Koba Timur
[01/05/2020 18:54:06] Raddy
[01/05/2020 18:54:06] Valenwe
[01/05/2020 18:50:23] Taran
[01/05/2020 18:50:23] Frenchie
[01/05/2020 18:50:23] Koba Timur
[01/05/2020 18:50:23] Raddy
[01/05/2020 18:50:23] Valenwe
[01/05/2020 18:45:18] Frenchie
[01/05/2020 18:45:18] Koba Timur
[01/05/2020 18:45:18] Raddy
[01/05/2020 18:45:18] Valenwe
[01/05/2020 18:44:37] Frenchie
[01/05/2020 18:44:37] Koba Timur
[01/05/2020 18:44:37] Raddy
[01/05/2020 18:44:37] Valenwe
[01/05/2020 18:44:37] Frenchie
[01/05/2020 18:44:37] Koba Timur
[01/05/2020 18:44:37] Raddy
[01/05/2020 18:44:37] Valenwe
[01/05/2020 18:38:45] Frenchie
[01/05/2020 18:38:45] Koba Timur
[01/05/2020 18:38:45] Raddy
[01/05/2020 18:38:45] Valenwe
[01/05/2020 18:37:34] Frenchie
[01/05/2020 18:37:34] Koba Timur
[01/05/2020 18:37:34] Raddy
[01/05/2020 18:37:34] Valenwe
[01/05/2020 18:36:40] Frenchie
[01/05/2020 18:36:40] Koba Timur
[01/05/2020 18:36:40] Raddy
[01/05/2020 18:36:40] Valenwe
[01/05/2020 18:35:52] Frenchie
[01/05/2020 18:35:52] Koba Timur
[01/05/2020 18:35:52] Raddy
[01/05/2020 18:35:52] Valenwe
[01/05/2020 18:35:51] Frenchie
[01/05/2020 18:35:51] Koba Timur
[01/05/2020 18:35:51] Raddy
[01/05/2020 18:35:51] Valenwe
[01/05/2020 18:35:45] Frenchie
[01/05/2020 18:35:45] Koba Timur
[01/05/2020 18:35:45] Raddy
[01/05/2020 18:35:45] Valenwe
[01/05/2020 18:35:10] Frenchie
[01/05/2020 18:35:10] Koba Timur
[01/05/2020 18:35:10] Raddy
[01/05/2020 18:35:10] Valenwe
[01/05/2020 18:35:09] Frenchie
[01/05/2020 18:35:09] Koba Timur
[01/05/2020 18:35:09] Raddy
[01/05/2020 18:35:09] Valenwe
[01/05/2020 18:35:08] Frenchie
[01/05/2020 18:35:08] Koba Timur
[01/05/2020 18:35:08] Raddy
[01/05/2020 18:35:08] Valenwe
[01/05/2020 18:30:59] Lobby created!
[01/05/2020 18:30:40] Raddy
[01/05/2020 18:30:40] FR. Valenwe
[01/05/2020 18:30:39] Server command: endround
[01/05/2020 18:30:39] endround
[01/05/2020 18:28:19] Raddy
[01/05/2020 18:28:19] FR. Valenwe
[01/05/2020 18:28:19] Raddy
[01/05/2020 18:28:19] FR. Valenwe
[01/05/2020 18:27:54] Raddy
[01/05/2020 18:27:54] FR. Valenwe
[01/05/2020 18:27:47] Raddy
[01/05/2020 18:27:47] FR. Valenwe
[01/05/2020 18:27:38] Raddy
[01/05/2020 18:27:38] FR. Valenwe
[01/05/2020 18:27:38] Server command: revive Raddy
[01/05/2020 18:27:38] revive Raddy
[01/05/2020 18:27:34] Server command: enablecheats
[01/05/2020 18:27:34] enablecheats
[01/05/2020 18:27:31] Raddy
[01/05/2020 18:27:31] FR. Valenwe
[01/05/2020 18:27:31] Server command: revive Raddy
[01/05/2020 18:27:31] revive Raddy
[01/05/2020 18:27:30] Raddy
[01/05/2020 18:27:30] FR. Valenwe
[01/05/2020 18:27:30] Raddy
[01/05/2020 18:27:30] FR. Valenwe
[01/05/2020 18:26:42] Raddy
[01/05/2020 18:26:42] FR. Valenwe
[01/05/2020 18:26:39] Raddy
[01/05/2020 18:26:39] FR. Valenwe
[01/05/2020 18:26:06] Raddy
[01/05/2020 18:26:06] FR. Valenwe
[01/05/2020 18:26:05] Server command: endround
[01/05/2020 18:26:05] endround
[01/05/2020 18:26:03] Command "ends" not found.
[01/05/2020 18:26:03] Server command: ends
[01/05/2020 18:26:03] ends
[01/05/2020 18:23:42] Raddy
[01/05/2020 18:23:42] FR. Valenwe
[01/05/2020 18:23:11] Raddy
[01/05/2020 18:23:11] FR. Valenwe
[01/05/2020 18:23:10] Server command: spawn husk cursor
[01/05/2020 18:23:10] spawn husk cursor
[01/05/2020 18:23:09] Server command: spawn husk cursor
[01/05/2020 18:23:09] spawn husk cursor
[01/05/2020 18:23:09] Server command: spawn husk cursor
[01/05/2020 18:23:09] spawn husk cursor
[01/05/2020 18:23:08] Server command: spawn husk cursorspawn husk cursor
[01/05/2020 18:23:08] spawn husk cursorspawn husk cursor
[01/05/2020 18:23:07] Server command: spawn husk cursorspawn husk cursor
[01/05/2020 18:23:07] spawn husk cursorspawn husk cursor
[01/05/2020 18:23:06] Server command: spawn husk cursorspawn husk cursor
[01/05/2020 18:23:06] spawn husk cursorspawn husk cursor
[01/05/2020 18:23:06] Server command: spawn husk cursorspawn husk cursor
[01/05/2020 18:23:06] spawn husk cursorspawn husk cursor
[01/05/2020 18:23:05] Server command: spawn husk cursor
[01/05/2020 18:23:05] spawn husk cursor
[01/05/2020 18:23:05] Server command: spawn husk cursor
[01/05/2020 18:23:05] spawn husk cursor
[01/05/2020 18:23:05] Server command: spawn husk cursor
[01/05/2020 18:23:05] spawn husk cursor
[01/05/2020 18:23:04] Server command: spawn husk cursorspawn husk cursor
[01/05/2020 18:23:04] spawn husk cursorspawn husk cursor
[01/05/2020 18:23:01] Server command: spawn husk cursor
[01/05/2020 18:23:01] spawn husk cursor
[01/05/2020 18:23:01] Server command: spawn husk cursor
[01/05/2020 18:23:01] spawn husk cursor
[01/05/2020 18:23:01] Server command: spawn husk cursor
[01/05/2020 18:23:01] spawn husk cursor
[01/05/2020 18:23:00] Server command: spawn husk cursor
[01/05/2020 18:23:00] spawn husk cursor
[01/05/2020 18:23:00] Server command: spawn husk cursor
[01/05/2020 18:23:00] spawn husk cursor
[01/05/2020 18:23:00] Server command: spawn husk cursor
[01/05/2020 18:23:00] spawn husk cursor
[01/05/2020 18:22:59] Server command: spawn husk cursor
[01/05/2020 18:22:59] spawn husk cursor
[01/05/2020 18:22:59] Server command: spawn husk cursor
[01/05/2020 18:22:59] spawn husk cursor
[01/05/2020 18:22:59] Server command: spawn husk cursor
[01/05/2020 18:22:59] spawn husk cursor
[01/05/2020 18:22:59] Server command: spawn husk cursor

**Comment by Regalis11** [comment] 2020-05-11 08:14
Duplicate of #2699

**Closed by Regalis11** 2020-05-11 08:14 UTC
Labels: Bug, Code, Crash
