### ISSUE TITLE
Can't loot a creature by double-clicking the item from their inventory, only allows dragging and dropping

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#4024] opened 2020-10-07 14:24 UTC
Tried to loot a Mudraptor by double-clicking the loot, only received a inventory warning sound.

**Comment by Regalis11** [comment] 2020-10-08 11:59
Could not reproduce. What exactly were you trying to loot, and could it be the slots the items should've gone into were already taken?

**Comment by Rokvach** [comment] 2020-10-08 12:04
I was trying to loot a Mudraptor during sandbox multiplayer session, I was a engineer so only had the items from the toolbelt in my first 3 inventory slots.

**Comment by Regalis11** [comment] 2020-10-08 12:11
Couldn't repro in multiplayer either. Which item were you trying to loot?

**Comment by Rokvach** [comment] 2020-10-08 12:22
The Mudraptor only had a Hydroxyapatite, but I'm not sure if someone else also had the Mudraptor grabbed as multiple players can grab the same creature and there were 3 players surrounding the Mudraptor at the time.

**Comment by Regalis11** [comment] 2020-11-17 12:42
No known steps to repro, closing

**Closed by Regalis11** 2020-11-17 12:42 UTC
Labels: Bug, Code, Need more info
