### ISSUE TITLE
AI crew members can't climb ladder in Camel

### ISSUE THREAD

**Issue by MercFromStalker** [Regalis11/Barotrauma#12124] opened 2023-06-05 22:32 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Playing singleplayer campaign and noticed AI crew wouldn't man the guns. I noticed that the crew assigned to them would just crowd in the oxygen room next to the ladder going up to the command room.
![image](https://github.com/Regalis11/Barotrauma/assets/135668562/929b1b2a-387b-44b0-926e-77690ed99b15)

### Reproduction steps

Used the camel.

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by MercFromStalker** [comment] 2023-06-05 22:39
I think this may just be because the ladder is too far forward for the ai pathing.

**Comment by itchyOwl** [comment] 2023-06-06 09:20
Closing as duplicate of #11984. Should be fixed in the latest unstable and the upcoming update.

**Closed by itchyOwl** 2023-06-06 09:20 UTC
