### ISSUE TITLE
Nitroglycerin buying problem

### ISSUE THREAD

**Issue by Earthspiritio** [Regalis11/Barotrauma#10537] opened 2022-11-25 00:33 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When buying Nitroglycerin, the crate that it spawns in will expload once touching the ground due to falling from a height (issue may be just for the Camel but may also be the same for other ships).

### Reproduction steps

1. start a campaign
2. get a camel submarine
3. buy Nitroglycerin
4. go and do any mission
5. explosion (result)

### Bug prevalence

Happens every time I play

### Version

0.20.7.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-11-25 10:39
Most likely related to or a duplicate of https://github.com/Regalis11/Barotrauma/issues/10411

**Comment by Regalis11** [comment] 2022-11-25 11:29
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7f0feaef298e08cfdf82f067d12564dab55b39d9

**Comment by Rokvach** [comment] 2022-11-29 08:40
Tested, working correctly.  Closing.

**Closed by Rokvach** 2022-11-29 08:40 UTC
Labels: Bug, Code, Unstable
