### ISSUE TITLE
Npcs can be Interacted with Through Fabricators and Deconstructors

### ISSUE THREAD

**Issue by SoobGorl** [Regalis11/Barotrauma#6022] opened 2021-06-10 09:49 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When any interactable NPC (upgrader, sellers, etc) stands near a fabricator or deconstructor, they can still be interacted with through the machine's UI (this is primarily a problem in EngineeringModule_01 as the Upgrader NPC generally spawns in close proximity to the Fabs/Decons there).

![image](https://user-images.githubusercontent.com/72813628/121503259-e77aa880-c9ae-11eb-9523-8716be03667e.png)

**Steps To Reproduce**
1. Dock to an outpost and locate the Fabricators and Deconstructors in the Engineering Module
2. If a job/seller NPC is there + close to the fabs/decons interact with the machines and be prompted with the seller's menus.

**Version**
V0.14.4.0, Windows

**Comment by Regalis11** [comment] 2021-06-10 14:40
Related: https://github.com/Regalis11/Barotrauma/issues/4347

**Comment by Regalis11** [comment] 2021-06-10 15:54
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/402a5f9d9778d4bcfa230b3f7ec84cc8d7e82576.

Note for testing: I pushed this to dev because it could causing some side-effects (are there some situations where we do want to allow interaction with NPC through certain UI elements?), and so I don't think we should include it in the upcoming update.

**Comment by Rokvach** [comment] 2021-06-23 09:57
I was still able to interact with a NPC whilst using a deconstructor, but I did have to spam LMB quite a lot in order to do it, seems to happen when you click this area of the deconstuctor UI multiple times around where the NPC is standing. Maybe its the horizontal line that lets a click go through?

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/7e066b8f-ace0-44c5-88b7-f43893e3fb77)

For reference I had the NPC standing in this spot relative to the deconstructor
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/5bb2b264-cb1d-4844-b290-a62e56e48005)

**Comment by Rokvach** [comment] 2021-06-23 10:01
Moving to Misc

**Comment by Rokvach** [comment] 2021-06-23 10:03
I was also able to reproduce the same issue with the cabinet UI's found on this ticket https://github.com/Regalis11/Barotrauma/issues/4347 , I decided to close the other ticket as the issue feels identical.

**Comment by Regalis11** [comment] 2021-07-15 14:06
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/028c7c51306ee8ae897439285e80a28d20d0fd9c

> Happened because of 2 different issues:
> 1. The UI element the cursor is on is refreshed at the end of the frame, but checking whether the cursor is on an inventory was done on the fly. If the cursor moved away from an inventory slot over a UI element, there was a one frame delay before the cursor is registered being on the UI element.
> 2. GUI.MouseOn wasn't updated at all when the mouse was held, allowing it to be moved from the slot to the UI, and causing the click to go through when the mouse was released.

Here's an easy way to repro:
1. Hover the cursor over the inventory slots
2. Hold down LMB
3. Move the cursor away from the slot to a position where it'd highlight the character behind the UI
4. Release LMB

**Comment by Rokvach** [comment] 2021-08-04 08:22
Tested, working correctly. Closing.

**Closed by Rokvach** 2021-08-04 08:22 UTC
Labels: Bug, Code, Low prio
