### ISSUE TITLE
Hash error and cannot join the server.

### ISSUE THREAD

**Issue by esirprus** [Regalis11/Barotrauma#9212] opened 2022-05-26 10:51 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

when I tried to join the server...
![image](https://user-images.githubusercontent.com/44423036/170468511-e5a7c041-a466-4c30-b528-09e8084dbe30.png)
![image](https://user-images.githubusercontent.com/44423036/170468578-791ff014-dc46-45f9-80de-9d99a8a86d83.png)
and other player cannot join too.
server OS llinux, client OS Win10

### Reproduction steps

download this mod,
http://steamcommunity.com/sharedfiles/filedetails/?source=Facepunch.Steamworks&id=2776026770
and upload it to linux server, then host a server.
join the server, then the error happens, and other player cannot join too.

### Bug prevalence

Happens every time I play

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by esirprus** [comment] 2022-05-26 10:53
I know it seems like #8874, but this error make us cannot join the server, so maybe is a different issue?

**Comment by esirprus** [comment] 2022-05-26 11:02
Oh I see difference between dedicated server (linux) and player-hosted server (windows), see the two files:
![image](https://user-images.githubusercontent.com/44423036/170475545-268fb06d-bc63-4602-8a9c-8e664c608803.png)

**Comment by esirprus** [comment] 2022-05-29 14:52
@juanjp600 this seems happens on linux server, my friend also test this

**Comment by esirprus** [comment] 2022-05-29 14:58
Found another mod called New Wrecks For Barotrauma (With sellable wrecks) has this problem.

**Comment by esirprus** [comment] 2022-06-03 03:03
Even after these mods are updated I run into the same problem.

**Comment by esirprus** [comment] 2022-06-03 03:28
The same problem was encountered after simply combining these two mods into one.

**Comment by theCrius** [comment] 2022-06-04 17:45
The same happened for me on fresh install of Barotrauma + Lua for Barotrauma and the hash was about Neurotrauma.

Quick workaround is setting the hash to the one expected in the filelist.xml of the mod if you are sure that the mod is in good health.

I heard from the Discord that the next patch should fix this issue.

**Comment by Regalis11** [comment] 2022-06-05 16:56
Possible duplicate of https://github.com/Regalis11/Barotrauma/issues/8874? @juanjp600

**Comment by juanjp600** [comment] 2022-06-05 19:00
No, this is not a duplicate. It's a related but separate problem that needs a separate fix, will do next week.

**Comment by esirprus** [comment] 2022-06-19 05:42
@juanjp600 
![YR(IK@JR0UAG`87{H}A%G(A](https://user-images.githubusercontent.com/44423036/174467557-cc48a012-4e1a-4395-b4c8-0a89563822c9.png)
bad news, not fixed, this still happen :<

**Comment by Ek-Videogames** [comment] 2022-06-19 18:02
I've been pouring over file comparison for a bit and there are tons of little inconsistencies between host content files and ones installed from the workshop, it seems one possible factor they all have in common is non-item files (IE, Structures & Events).
I invite anyone to find an example to disprove this if you can, cause I'm all out of ideas.

**Comment by esirprus** [comment] 2022-06-20 05:43
> @juanjp600 ![YR(IK@JR0UAG`87{H}A%G(A](https://user-images.githubusercontent.com/44423036/174467557-cc48a012-4e1a-4395-b4c8-0a89563822c9.png) bad news, not fixed, this still happen :<

this error happens on my friend's linux server, but on my server is okay

**Comment by esirprus** [comment] 2022-06-21 02:09
It only happened on my friend's server, so we'd better leave the issue open for a while and see if anyone else has the same problem.

**Closed** 2022-08-17 12:18 UTC
Labels: Bug, Linux only, Code, Modding, Unstable
