### ISSUE TITLE
Oxygenite Shard is unlimited welding tool fuel source

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#4377] opened 2020-11-23 21:50 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Oxygenite shard is a valid "oxygensource" item, but is not explicitly mentioned for any condition changes in the welding tool xml.

as such, the welding tool can be used, and the oxygenite shard does NOT deplete.

making it ~~the victor~~ an unlimited ~~power~~ welding source.

**Steps To Reproduce**
1. put oxygenite shard inside welding tool
2. use welding tool infinitely
3. ??? 
4. Profit!

**Version**
0.10.6.2

**Comment by Rokvach** [comment] 2020-12-02 10:45
Tested, seems to explode now when used. Working as intended then. Closing.

**Closed by Rokvach** 2020-12-02 10:45 UTC
Labels: Bug, Design
