### ISSUE TITLE
Deletion of character while using Control command in multiplayer

### ISSUE THREAD

**Issue by StruggleDuck** [Regalis11/Barotrauma#11183] opened 2023-02-08 03:40 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

while controlling a bot using the control command in a multiplayer campaign, and then docking, the original player character was deleted. after making a new character, and finishing the round, the players inventory and traits were also reset. Not sure if related.

### Reproduction steps

1. Start multiplayer campaign on faction/endgame test version
2. use the control command to control a bot
3. end the round by docking your sub at a station
4. watch in horror as all of your hardwork is deleted out of existence

### Bug prevalence

Just once

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Lepestochek** [comment] 2023-02-08 05:13
Not factions specific, can confirm as it happened to me before on stable, probably because you were never meant to control bots in multiplayer sessions.

**Comment by Regalis11** [comment] 2023-02-08 08:04
I wouldn't necessarily consider this a bug. You keep the character you're controlling in the MP campaign, and if you use console commands to switch the character, you lose the original one.

**Comment by StruggleDuck** [comment] 2023-02-09 18:15
another issue I came across with this is that it can actually duplicate the bot that you were controlling, one that is a regular AI character, and the other is player controlled. I think maybe there should be some easier way for people with necessary permissions to control bots as if it was single player.

**Comment by itchyOwl** [comment] 2023-02-21 09:15
Closing this ticket, as it's working as intended. However if you have more info on this, please create a new ticket for it, because that sounds like a bug to me:

> another issue I came across with this is that it can actually duplicate the bot that you were controlling, one that is a regular AI character, and the other is player controlled

**Closed by itchyOwl** 2023-02-21 09:15 UTC
