### ISSUE TITLE
Lost money in the wallets of the crew

### ISSUE THREAD

**Issue by VulpesFerrilata4** [Regalis11/Barotrauma#9405] opened 2022-06-18 15:43 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When someone from the crew buys things with money from their wallet, the money seems to be taken from everyone. For exmple, a man had 100 marks, someone else bought ethanol for 80, and the first one has 80 marks missing, so he can't buy anything.  But they don't really disappear, i can see through TAB that the money has not disappeared from him, and i can even transfer it to the bank. 

### Reproduction steps

1. Start a multiplayer campaingn 
2. Give crew members personal money
3. Someone has to buy something with personal money
4. Everyone else will lose the same amount of money from their wallets

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by 3e849f2e5c** [comment] 2022-06-22 03:25
Could not repro in dev, the money seems to be correctly debited only from the one who purchased items
![](https://kosblue.com/e/wcqeur.png)

**Comment by Ryanator** [comment] 2022-06-27 03:35
Recreated the bug in a little more detail. From host perspective:
![20220626232236_1](https://user-images.githubusercontent.com/1358917/175854406-f27bc2d7-26f1-444c-94b9-5defca490651.jpg)
Before purchasing ethanol from a vending machine

![20220626232255_1](https://user-images.githubusercontent.com/1358917/175854427-b76ce936-7c94-49bc-afa7-94d591103c2a.jpg)
After purchasing alcohol. Bug seems not to be present, however...

![20220626232346_1](https://user-images.githubusercontent.com/1358917/175854593-9472279b-36b3-4006-a3ba-53703c1a3f6d.jpg)

This is what it looks like from the other player's perspective. Any change to the amount of money- such as making another purchase, withdrawing from the bank, ect, corrects the money amount to the correct amount. It is only a client-side bug and does not reflect actual money amounts. The bug is re-creatable when the other player makes a purchase on host end as well. Money also appears to be corrected on a save-reload.

**Comment by VulpesFerrilata4** [comment] 2022-06-27 03:47
Ryanator thanks for the material. Yes, this is a client side error. If the bug was only visual it would be ok, but the bug does prevent the player from making purchases. And fixing it every time is pretty tedious. Therefore, I really hope that the developers will find a way to cause this error in game and fix it. It's quite sad that my team can't take full advantage of the new mechanics.

**Comment by 3e849f2e5c** [comment] 2022-06-27 09:04
@Ryanator Thanks for clarifying this issue happens only with the vending machine. Was able to reproduce now.

Fixed in https://github.com/Regalis11/Barotrauma-development/commit/84c648c7c5b14e87e0db81b51d3c44e94aee637b

**Comment by NilanthAnimosus** [comment] 2022-07-05 10:36
Tested on release commit https://github.com/Regalis11/Barotrauma-development/commit/36e3a2755f5fc201a748a32b63cc93a8eb30d90a, Works correctly, closing.

Note: Tested in multiplayer with multiple clients using both main and wallet currencies on both vending machines and stores, everything synced fine.

**Closed by NilanthAnimosus** 2022-07-05 10:36 UTC
Labels: Bug, Code, Unstable
