### ISSUE TITLE
Shell A 34 Degree texture cracked

### ISSUE THREAD

**Issue by leowashington** [Regalis11/Barotrauma#10898] opened 2023-01-09 15:25 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://user-images.githubusercontent.com/80885178/211343885-ee732011-a564-44f0-a51a-ffa8a2d249a2.png)

The shell looks like this↑ Please fix it.

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-01-09 15:32
Thank you for the report!

I unfortunately could not reproduce the problem. This is how that wall piece looks at my end (the left one mirrored on both the x and y axis as in your screenshot, the right one unmodified). 
![image](https://user-images.githubusercontent.com/14351070/211345800-02bdd031-32aa-4b7f-94c7-5ba0649369e2.png)

**Comment by Regalis11** [comment] 2023-01-23 14:39
No known steps to repro, closing

**Closed by Regalis11** 2023-01-23 14:39 UTC
Labels: Bug, Need more info
