### ISSUE TITLE
searchlights and r-29 cargo bay light

### ISSUE THREAD

**Issue by the1eyedduck** [Regalis11/Barotrauma#4352] opened 2020-11-19 16:45 UTC
searchlights not draw light correctly
![searchlight editor](https://user-images.githubusercontent.com/74727878/99696207-06702680-2ac1-11eb-951e-66429dbcfd53.jpg)
![searchlight ingame](https://user-images.githubusercontent.com/74727878/99696225-0bcd7100-2ac1-11eb-9375-c214be349d64.jpg)
r-29 weird light behavior
![r-29 drawlight failed](https://user-images.githubusercontent.com/74727878/99696329-2bfd3000-2ac1-11eb-83af-25f52b1c6f72.jpg)
fix by select "wall with cables" piece and tap up arrow 1
![r-29 drawlight success](https://user-images.githubusercontent.com/74727878/99696413-3fa89680-2ac1-11eb-9f28-ecbf2eadbf52.jpg)
Edit: R-29 in 0.11.0.7 also missing platform in cargobay
![r-29 no platform](https://user-images.githubusercontent.com/74727878/99697464-57344f00-2ac2-11eb-8dba-f0bce704d3a2.jpg)

**Comment by Regalis11** [comment] 2020-11-20 09:23
Fixed the platform in https://github.com/Regalis11/Barotrauma-development/commit/9686ebf1cd2a104596cea0152613d2ad1dafd898.

I was unable to reproduce the searchlight issue though. Tested with a bunch of mirrored and rotated searchlights, but the light seemed to render correctly on all of those. Is this submarine available in the Workshop so we could give it a test? If not, would it be possible to send the sub file to us here (you need to zip the file to attach it to a post, since github doesn't support the submarine file format)?

**Comment by the1eyedduck** [comment] 2020-11-20 10:32
[Submarine.zip](https://github.com/Regalis11/Barotrauma/files/5572889/Submarine.zip)
also it seem to work fine in 0.10.6.2, only happen in 0.11.0.7

**Comment by Regalis11** [comment] 2020-11-20 13:35
Thanks! Looks like there was a commit in our private repository that appears to have fixed this https://github.com/Regalis11/Barotrauma-development/commit/4bd46cb, so that must be why I was no longer able to reproduce it. @3e849f2e5c I suppose this can be moved to QA?

**Comment by 3e849f2e5c** [comment] 2020-11-20 13:54
Wasn't aware that this change affected in-game as well since the rotation was only messed up when toggling lighting visibility in editor and turrets override the light component rotation after loading in but if it did I supposed it can be moved to QA.

**Comment by rav2n** [comment] 2020-12-08 16:34
This happens with all spotlights with a fixed beam position (maximum rotation angle is equal to minimum).

**Comment by Ek-Videogames** [comment] 2020-12-10 00:08
Hi, 
Just checking in to say that this is definitely still broken.
![image](https://user-images.githubusercontent.com/55356135/101704020-d5489d80-3a51-11eb-8e17-a7ac0a09fad3.png)

**Comment by Regalis11** [comment] 2020-12-10 10:33
@Ek-Videogames This fix didn't make it to v0.11.0.9, but will be included in a future update

**Comment by Xeavas** [comment] 2020-12-11 16:51
[0.1200.0.0] - Still an issue. (dechecked the draw behind sub checkbox for provided sub)

![lightflipissue](https://user-images.githubusercontent.com/72674994/101931087-ef31de00-3c13-11eb-8b8e-91b7e5d77cff.jpg)
![lightinverissue](https://user-images.githubusercontent.com/72674994/101931097-f1943800-3c13-11eb-9839-2958800f2f97.jpg)

Can confirm that it is happening if the min and max value for rotation limit is the same (ie min`10` max`10`)

**Comment by Rokvach** [comment] 2020-12-11 17:16
Moving back to todo

**Comment by 3e849f2e5c** [comment] 2021-01-07 10:20
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c6df3ef04658a09ea5e0465b20c38b9cb7dc348f

**Comment by Rokvach** [comment] 2021-01-11 13:26
Tested, didn't notice any further issues with this one. Closing.

**Closed by Rokvach** 2021-01-11 13:26 UTC
Labels: Bug, Code
