### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by Keef25** [Regalis11/Barotrauma#3757] opened 2020-09-07 15:18 UTC
After trying to get into a modded game and installing and uninstalling the mods, Barotrauma wanted me to restart and has been crashing ever since
Here's a crash log 

Barotrauma Client crash report (generated on 07/09/2020 16:08:47)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

EFAC70B2719BEBECDF0597D16251FCBE

Game version 0.10.4.0 (ReleaseWindows, branch release, revision 20132d25fb)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.17763.0 64 bit
    GPU name: Radeon RX 580 Series
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: One or more errors occurred. (Object reference not set to an instance of an object.) (System.AggregateException)
Target site: Void ThrowIfExceptional(Boolean)
Stack trace: 
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Barotrauma.GameMain.<>c__DisplayClass97_0.<Load>b__2(Task task) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 467
   at Barotrauma.TaskPool.<>c__DisplayClass5_0.<Add>b__0(Task t, Object obj) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Utils\TaskPool.cs:line 52
   at Barotrauma.TaskPool.Update() in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Utils\TaskPool.cs:line 69
   at Barotrauma.GameMain.Update(GameTime gameTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 999
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 654
   at Microsoft.Xna.Framework.Game.Tick() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59

InnerException: Object reference not set to an instance of an object.
Target site: Void Init()
Stack trace: 
   at Barotrauma.LocationType.Init() in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Map\Map\LocationType.cs:line 210
   at Barotrauma.GameSettings.RefreshContentPackageItems(IEnumerable`1 files) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\GameSettings.cs:line 439
   at Barotrauma.GameSettings.DeselectContentPackage(ContentPackage contentPackage) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\GameSettings.cs:line 345
   at Barotrauma.Steam.SteamManager.RemoveMods(Func`2 predicate, Boolean delete) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Networking\SteamManager.cs:line 1244
   at Barotrauma.Steam.SteamManager.AutoUpdateWorkshopItemsAsync() in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Networking\SteamManager.cs:line 1430
Last debug messages:
[07/09/2020 16:08:47] Error in  in location type Mine - could not find a job with the identifier "assistant".
[07/09/2020 16:08:47] Couldn't find a job prefab with the given identifier: assistant
[07/09/2020 16:08:47] Error in  in location type Mine - could not find a job with the identifier "mechanic".
[07/09/2020 16:08:47] Couldn't find a job prefab with the given identifier: mechanic
[07/09/2020 16:08:47] Error in  in location type Mine - could not find a job with the identifier "engineer".
[07/09/2020 16:08:47] Couldn't find a job prefab with the given identifier: engineer
[07/09/2020 16:08:47] Error in  in location type Research - could not find a job with the identifier "captain".
[07/09/2020 16:08:47] Couldn't find a job prefab with the given identifier: captain
[07/09/2020 16:08:47] Error in  in location type Research - could not find a job with the identifier "securityofficer".
[07/09/2020 16:08:47] Couldn't find a job prefab with the given identifier: securityofficer
[07/09/2020 16:08:47] Error in  in location type Research - could not find a job with the identifier "assistant".
[07/09/2020 16:08:47] Couldn't find a job prefab with the given identifier: assistant
[07/09/2020 16:08:47] Error in  in location type Research - could not find a job with the identifier "medicaldoctor".
[07/09/2020 16:08:47] Couldn't find a job prefab with the given identifier: medicaldoctor
[07/09/2020 16:08:47] Error in  in location type Research - could not find a job with the identifier "mechanic".
[07/09/2020 16:08:47] Couldn't find a job prefab with the given identifier: mechanic
[07/09/2020 16:08:47] Error in  in location type Research - could not find a job with the identifier "engineer".
[07/09/2020 16:08:47] Couldn't find a job prefab with the given identifier: engineer
[07/09/2020 16:08:47] Error in  in location type Military - could not find a job with the identifier "medicaldoctor".
[07/09/2020 16:08:47] Couldn't find a job prefab with the given identifier: medicaldoctor
[07/09/2020 16:08:47] Error in  in location type Military - could not find a job with the identifier "mechanic".
[07/09/2020 16:08:47] Couldn't find a job prefab with the given identifier: mechanic
[07/09/2020 16:08:47] Error in  in location type Military - could not find a job with the identifier "engineer".
[07/09/2020 16:08:47] Couldn't find a job prefab with the given identifier: engineer
[07/09/2020 16:08:47] Error in  in location type Military - could not find a job with the identifier "assistant".
[07/09/2020 16:08:47] Couldn't find a job prefab with the given identifier: assistant
[07/09/2020 16:08:47] Error in  in location type Military - could not find a job with the identifier "captain".
[07/09/2020 16:08:47] Couldn't find a job prefab with the given identifier: captain
[07/09/2020 16:08:47] Error in  in location type Military - could not find a job with the identifier "securityofficer".
[07/09/2020 16:08:47] Couldn't find a job prefab with the given identifier: securityofficer
[07/09/2020 16:08:47] Error in  in location type Outpost - could not find a job with the identifier "captain".
[07/09/2020 16:08:47] Couldn't find a job prefab with the given identifier: captain
[07/09/2020 16:08:47] Error in  in location type Outpost - could not find a job with the identifier "securityofficer".
[07/09/2020 16:08:47] Couldn't find a job prefab with the given identifier: securityofficer
[07/09/2020 16:08:47] Error in  in location type Outpost - could not find a job with the identifier "medicaldoctor".
[07/09/2020 16:08:47] Couldn't find a job prefab with the given identifier: medicaldoctor
[07/09/2020 16:08:47] Error in  in location type Outpost - could not find a job with the identifier "mechanic".
[07/09/2020 16:08:47] Couldn't find a job prefab with the given identifier: mechanic
[07/09/2020 16:08:47] Error in  in location type Outpost - could not find a job with the identifier "engineer".
[07/09/2020 16:08:47] Couldn't find a job prefab with the given identifier: engineer
[07/09/2020 16:08:47] Error in  in location type Outpost - could not find a job with the identifier "assistant".
[07/09/2020 16:08:47] Couldn't find a job prefab with the given identifier: assistant
[07/09/2020 16:08:47] Error in  in location type City - could not find a job with the identifier "captain".
[07/09/2020 16:08:47] Couldn't find a job prefab with the given identifier: captain
[07/09/2020 16:08:47] Error in  in location type City - could not find a job with the identifier "securityofficer".
[07/09/2020 16:08:47] Couldn't find a job prefab with the given identifier: securityofficer
[07/09/2020 16:08:47] Error in  in location type City - could not find a job with the identifier "medicaldoctor".
[07/09/2020 16:08:47] Couldn't find a job prefab with the given identifier: medicaldoctor
[07/09/2020 16:08:47] Error in  in location type City - could not find a job with the identifier "mechanic".
[07/09/2020 16:08:47] Couldn't find a job prefab with the given identifier: mechanic
[07/09/2020 16:08:47] Error in  in location type City - could not find a job with the identifier "engineer".
[07/09/2020 16:08:47] Couldn't find a job prefab with the given identifier: engineer
[07/09/2020 16:08:47] Error in  in location type City - could not find a job with the identifier "assistant".
[07/09/2020 16:08:47] Couldn't find a job prefab with the given identifier: assistant
[07/09/2020 16:08:46] Content package load order: Vanilla 0.9
[07/09/2020 16:08:43] Attempting to open ALC device "OpenAL Soft on Headset Earphone (2- CORSAIR HS70 Wireless Gaming Headset)"
[07/09/2020 16:08:42] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[07/09/2020 16:08:41] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean

**Comment by Regalis11** [comment] 2020-09-07 15:20
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3509

**Closed by Regalis11** 2020-09-07 15:20 UTC
