### ISSUE TITLE
[Factions/Endgame] Oxygen Tank Shelf Displaying Incorrect Number of Oxygen Tanks

### ISSUE THREAD

**Issue by StruggleDuck** [Regalis11/Barotrauma#11262] opened 2023-02-16 03:36 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Weird visual bug where oxygen tank shelf displays more than 3 oxygen tanks, with the extra tanks floating in the air.

![image2](https://user-images.githubusercontent.com/92034548/219261600-655ea865-5593-4b37-862d-be82b7494218.png)

![1](https://user-images.githubusercontent.com/92034548/219261611-df460f3f-e5db-480c-8bbd-ce02399c1dad.png)

### Reproduction steps

I am unsure what has caused the bug, but it occurred in multiplayer campaign. In this instance, the visual bug occurred only on one players side, but there was also a separate instance where the host could see the visual bug. Outside of that I have no idea what could have caused it. the only thing I can think of is that it might be from the AI crewmember set to refill oxygen tanks.

### Bug prevalence

Happens every now and then

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-02-16 09:56
Most likely a duplicate of https://github.com/Regalis11/Barotrauma/issues/11233

**Closed by Regalis11** 2023-02-16 09:56 UTC
