### ISSUE TITLE
[Unstable] Merchant stock doesn't go down, takes your money and doesn't spawn items

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#8653] opened 2022-03-29 18:36 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Can't buy items as non-host in MP from the merchant.
The merchant stock doesn't go down despite confirming the purchase
Buying is confirmed, but on round start nothing spawns.
The merchant still takes your money.

**Version**
Unstable V0.17.5.0

**Comment by ekqvist** [comment] 2022-03-30 07:20
I think the issues were caused by changes to the permissions made in Regalis11/Barotrauma-development@0764d87

**Comment by ekqvist** [comment] 2022-03-30 08:11
Fixed some issues with interface refreshing in Regalis11/Barotrauma-development@35a86ba

**Comment by ekqvist** [comment] 2022-03-31 08:52
Fixed issues with buying items in multiplayer campaign in Regalis11/Barotrauma-development@70250d3. The issues seemed to occur whenever you made more than one purchase, i.e. confirmed one purchase and tried to make another one.

**Comment by Rokvach** [comment] 2022-04-04 23:06
Tested, working correctly. Closing.

**Closed by Rokvach** 2022-04-04 23:06 UTC
Labels: Bug, Code, Networking
