### ISSUE TITLE
Unstable - Accepting mission leads to console red text and strange mission behaviour

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#3230] opened 2020-06-27 16:23 UTC
**Description**
I have accepted a mission in research outpost and this red text appeared
![image](https://user-images.githubusercontent.com/59519434/85926862-97402e80-b8a2-11ea-98e8-01235b7f7e8c.png)
I have talked only to 1 NPC. Text popup described a wreck mission, and yet crawler swarm is mentioned in console.
After that, I had many missions available to me to multiple outposts around. I have selected an artifact mission to Katreus Linea outpost, but it sent me to Skaani outpost with Explosive cargo mission. The red console error repeated it self frequently. (Explosive cargo mission can be seen at the end of the gif)
Gif:
![missions1](https://user-images.githubusercontent.com/59519434/85926971-3a914380-b8a3-11ea-94ab-ccee6a73bdc0.gif)

**Steps To Reproduce**
Missions behaved properly up to that point, no clue what caused this.

**Version**
Unstable
**Additional information**
Dedicated server, hosted on my PC, joined from the same pc. Playercount throughout the entire session: 1.
Save: [Maxing Rep 2.zip](https://github.com/Regalis11/Barotrauma/files/4840889/Maxing.Rep.2.zip)

**Comment by Regalis11** [comment] 2020-07-02 11:15
We unfortunately haven't found a way to reproduce this, so if anyone can figure out the steps to get this to happen, please let us know!

**Comment by Regalis11** [comment] 2020-07-03 08:15
I think I found what's causing this:
When generating the map, locations that are too close to some other location get removed, also removing the connection to that location. However, the connection would be kept in the remaining location's Connections list, even though it doesn't actually exist on the map.

The "non-existent" connection would not get saved though, so it wouldn't exist client-side because the client loads the map from the save instead of generating it, leading to this error. The error would also fix itself when quitting and reloading the campaign save.

Here's steps to repro:
1. Start a campaign with the seed Epqo6uWj
2. Travel to Molovsk Station (the only location you can travel to from the starting location)
3. Unlock some missions (may take a couple of tries to get one to be unlocked in the "non-existent" connections).

Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/ee3e644ade155add8adc21677bc263fb01d5d50e

**Comment by Rokvach** [comment] 2020-07-05 08:41
No encounters in 0.10.2.0 build, closing.

**Closed by Rokvach** 2020-07-05 08:41 UTC
Labels: Bug, Code, High prio, Networking
