### ISSUE TITLE
AIs on turrets shoot players

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#1565] opened 2019-06-08 23:41 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description** & **Steps To Reproduce**
AI bots on coilguns shoot at players. (Its a bit far-streched interpretation of "fire at will", hehe)
Noticed in SP, not yet tested in MP.

**Version**
9.0.4

It was considered fixed here: https://github.com/Regalis11/Barotrauma/issues/1102

**Comment by Regalis11** [comment] 2019-06-10 12:03
Haven't been able to reproduce this. Could it be that there was a monster nearby the character was trying to shoot?

**Comment by CurePindal** [comment] 2019-06-10 17:30
No, there havent been any monsters around. The bots definatly shot at me. Since the post I had this happen on two other instances.

**Comment by CurePindal** [comment] 2019-06-11 10:15
I tried a few runs to reproduced the issue - no dice so far. 

Rough guess: The bots might shoot at players after they already targeted mobs earlier (even if theres no mobs around any longer).  I couldnt test that condition so far.

**Comment by CurePindal** [comment] 2019-06-13 09:47
I could just reproduce the issue in singleplayer.
 
It seems that the Bots indeed only shoot the player if they had targeted something else before. 
So this doesnt happen when you start a mission and had no contact with any mobs before.

**Comment by Regalis11** [comment] 2019-09-19 09:10
Duplicate of #1816. Even though this is an older issue report, I think we close this one instead because the recent one includes more information about the issue.

**Closed by Regalis11** 2019-09-19 09:10 UTC
Labels: Bug, Code, Need more info
