### ISSUE TITLE
Attempting to remove an already removed character Error

### ISSUE THREAD

**Issue by JoneKone** [Regalis11/Barotrauma#9384] opened 2022-06-17 10:38 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Dedicated server, round was running zero players in. I joined the game and ended the round with a command, (endround)

spewed and error

### Reproduction steps

1. Somebody else starts a round,
2. leaves the game on.
3. admin joins game and uses endround command.

### Bug prevalence

Just once

### Version

0.18.11.0

### Which operating system did you encounter this bug on?

Linux

### Relevant error messages and crash reports

```shell
Attempting to remove an already removed character
       at System.Environment.get_StackTrace()
       at Barotrauma.Character.Remove() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Character.cs:line 4221
       at Barotrauma.SubEditorScreen.DeselectEditorSpecific() in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Screens/SubEditorScreen.cs:line 1568
       at Barotrauma.EditorScreen.Deselect() in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Screens/EditorScreen.cs:line 15
       at Barotrauma.Screen.Select() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Screens/Screen.cs:line 22
       at Barotrauma.NetLobbyScreen.Select() in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Screens/NetLobbyScreen.cs:line 1316
       at Barotrauma.Networking.GameClient.EndGame(String endMessage, List`1 traitorResults, TransitionType transitionType)+MoveNext() in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Networking/GameClient.cs:line 1909
       at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 196
       at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 227
       at Barotrauma.CoroutineManager.Update(Single unscaledDeltaTime, Single deltaTime) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 270
       at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 924
       at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 651
       at Microsoft.Xna.Framework.Game.Tick() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 504
       at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/SDL/SDLGamePlatform.cs:line 94
       at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 398
       at Microsoft.Xna.Framework.Game.Run() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 368
       at Barotrauma.Program.Main(String[] args) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 59
```

**Comment by Regalis11** [comment] 2022-06-20 10:02
I'm afraid I could not reproduce this. The stack trace seems to indicate you were in the sub editor when the round ended, is that correct?

**Comment by JoneKone** [comment] 2022-06-20 10:36
Negative, it was a dedicated server. Like I said.

**Comment by Regalis11** [comment] 2022-06-20 14:05
But this error is not from the server, but the client, right?

**Comment by JoneKone** [comment] 2022-06-20 17:19
I'm now less certain of it's origin as you have questioned it.. but I'm still almost 90% sure it's from the server.. I quest I have to check the logs..  Than god we have Console logs.. **mudder about logs and state of logs**

**Comment by JoneKone** [comment] 2022-06-20 17:38
Ok so I quest It was from the client... and perhaps I was in editor before I joined the server ran the command endround and it popped that out so maybe I missed it before I typed endround in console.

I'm now very confused As initially I was pretty sure the error came from the server, after I typed endround... Maybe I then pressed End round in the .. Ouh there is only Spectate button, I had to type endround.

I'm pretty confused.. right now and Cannot say anything by certain anymore... About this error message.

Logs showed nothing, so it had to come from the client side. And yes we save all console logs.

**Comment by NilanthAnimosus** [comment] 2022-08-18 16:18
I find this confusing as I was reading that stacktrace and noticed it goes from Networking.GameClient.EndGame, to NetLobbyScreen.Select, then Screen.Select, followed by EditorScreen.Deselect and finally SubEditorScreen.DeselectEditorSpecific?

Is it just my imagination, but this error actually does look like it originated from a server, but incomprehensibly tried to close a sub editor screen from a round end triggered by client networking code?

**Comment by Regalis11** [comment] 2022-09-01 09:12
> I am capable of getting the same error in a debug build by using the subeditor command as a connected client, then ending the round by console/another player. the error pretty much matches 1:1 exactly then.

I'm fairly certain this is what happened here: that's the only explanation I can think of for the game trying to deselect the sub editor screen. Since switching to the sub editor mid-round is not really something you should normally do, I think we can close this.

**Closed by Regalis11** 2022-09-01 09:12 UTC
Labels: Bug, Need more info, Code
