### ISSUE TITLE
"My Character" tab skill levels aren't updated when you level up skills until next round

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4998] opened 2021-02-06 00:44 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
"My Character" tab skill levels aren't updated when you level up skills until next round.

**Version**
~0.12.0.2

**Comment by Regalis11** [comment] 2021-02-08 09:18
Could not reproduce. Tested by doing the following:
1. Start a new sp campaign round
2. Check the weapons skill
3. Kill some crawlers until you gain a level
4. Check the weapons skill again

![image](https://user-images.githubusercontent.com/14351070/107199656-6068f400-69ff-11eb-8cc8-f43ba4bdb0dd.png)

**Comment by Kaillera** [comment] 2021-02-08 09:47
Wrong tab. Talking about the furthest right tab on the tab ui.

**Comment by Regalis11** [comment] 2021-02-08 10:36
Ah, should've read this a bit more carefully! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6515c8e8ae75601ecfe252aa40cde1e947698ed3

**Comment by Rokvach** [comment] 2021-02-09 09:27
Tested, working correctly. Closing.

**Closed by Rokvach** 2021-02-09 09:27 UTC
Labels: Bug, Code, Medium Prio
