### ISSUE TITLE
Crash Upon Approaching any Wreck

### ISSUE THREAD

**Issue by Alrigh-t** [Regalis11/Barotrauma#3928] opened 2020-09-27 19:58 UTC
- [x]  I have searched the issue tracker to check if the issue has already been reported.

**Description**
Over many attempts at a co-op campaign round with friend, cannot seem to get close enough to enter any wreck without getting the same crash report each time. At first I thought it was workshop wrecks causing the issue, as I did run into texture compression issues with some of them, so I got rid of any and all workshop wrecks. Thinking this would fix the problem we started another new campaign, ran across a vanilla wreck, and still crashed once we got to close.

(For refrence other mods in use during these attempts all caused no issue in previous campaigns we have played, `crash-free)`  

**Steps To Reproduce**
I personally don't think this is very widespread, given I couldn't find anything about it, but for us all you needed to do was approach a wreck in multiplayer campaign (No bots) But I doubt this will recreate the issue for most players. 

**Version**
0.10.5.1, Windows 10

**Additional information**
(https://github.com/Regalis11/Barotrauma/files/5288920/crashreport.8.log)

**Comment by ekqvist** [comment] 2020-09-27 20:04
Based on the crash report this seems like a duplicate of #3893. Another user with the same issue managed to avoid it by disabling the "GunLights" mod. Sorry for the inconvenience, I hope this helps until an update containing a fix is released!

**Closed** 2020-09-27 20:04 UTC
Labels: Bug, Code, Crash, Duplicate
