### ISSUE TITLE
(Unstable Version) Bots Will Leave The Submarine Crew Randomly

### ISSUE THREAD

**Issue by KermTheFerg** [Regalis11/Barotrauma#3373] opened 2020-07-16 03:14 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

When arriving at a station, all bots apart of my crew will leave without there being any reason too. 

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

Not any steps to reproduce just happens whenever arriving at a station or area.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

Happened within the unstable version of the game.

**Additional information**

At first, I didn't know if this happened due to attacking the bots because it happened directly after that but then other times bots left the crew without any reason why.

**Comment by CurePindal** [comment] 2020-07-16 20:29
#https://github.com/Regalis11/Barotrauma/issues/3346

**Comment by Regalis11** [comment] 2020-07-17 07:50
Duplicate of #3346

**Closed by Regalis11** 2020-07-17 07:50 UTC
