### ISSUE TITLE
Crash when disconnecting (Cannot access a closed pipe. (System.ObjectDisposedException))

### ISSUE THREAD

**Issue by gulepa** [Regalis11/Barotrauma#7344] opened 2021-11-17 05:07 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.
(I wouldn't even know how to search for the issue, since the crash notification told me to post the file here)

**Description**
Played a couple rounds as host;
went back to lobby;
clicked "disconect";
clicked "yes";
game crashed before getting back to the start screen.

**Steps To Reproduce**
No idea if it is reproducible, but the description above were the exact steps I took.

**Version**

This is just copy/pasted from the attached log:

Game version 0.15.13.0 (ReleaseWindows, branch release, revision 4e66dd7b5d)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.NetLobbyScreen
SteamManager initialized
Client (Round hadn't been started)

**Additional information**
Have never used mods except for 1 sub from steam workshop that I installed but never got to use. Log linked below:

[crashreport.log](https://github.com/Regalis11/Barotrauma/files/7551873/crashreport.log)

**Comment by Regalis11** [comment] 2022-02-07 08:17
Duplicate of https://github.com/Regalis11/Barotrauma/issues/5599

**Closed by Regalis11** 2022-02-07 08:17 UTC
Labels: Bug, Code, Crash, Networking
