### ISSUE TITLE
Artifact pick up and duplication bug

### ISSUE THREAD

**Issue by Skaboss21** [Regalis11/Barotrauma#2729] opened 2020-04-28 04:46 UTC
- [Y ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When myself and friends where paying on our own server we attempted a artifact mission. The Psychosis artifact started in the same place for all of us. However picking it up did not move it according to any other persons game. They could not see the artifacts as it was being held and moved by other players and their sonar reflected it was where they (the player) had last left it. In effect we each had a artifact that only we could see and track. The game did not recognize the artifacts we managed to get on the ship (we dropped a few) for the purpose of completing the mission.  

**Steps To Reproduce**
We did not seem to "do" anything ourselves to make this happen. The level seems to have generated it that way. Connection was at times unstable which may be a factor.

**Version**
Windows 10: 1909 game version: v0.9.9.0

**Comment by Regalis11** [comment] 2020-05-18 09:21
Potentially related to https://github.com/Regalis11/Barotrauma-development/commit/7c921f2a96c1853ef96817c8ab16dbcbd0571833

**Comment by Regalis11** [comment] 2020-07-09 11:11
Most likely caused by the same issue as https://github.com/Regalis11/Barotrauma/issues/3141, closing

**Closed by Regalis11** 2020-07-09 11:11 UTC
Labels: Bug, Code, Networking
