### ISSUE TITLE
PUCS sporadically does not play the low/zero oxygen alarm

### ISSUE THREAD

**Issue by rjavier441** [Regalis11/Barotrauma#9627] opened 2022-07-23 05:13 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

During playthrough of a Single player campaign, I've begun to notice times when the low/zero oxygen warning alarm fails to warn me of oxygen deprivation before the screen starts flaring and the "tunnel vision" effect occurs. The O2 low health status icon still shows, but the familiar tone that comes with it doesn't always ring. Not sure if this is related, but this tends to happen more often after a large lag spike in the game, and I've only noticed it since the v0.18.15.0 hotfix. 

### Reproduction steps

N/a, as the sporadic nature of the issue doesn't appear to be immediately reproducible.

### Bug prevalence

Happens every time I play

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by NilanthAnimosus** [comment] 2022-07-28 10:54
I am unable to reproduce this personally, gave it a quick try with a sky artifact in a submarine (PUCS is capable of drawing oxygen from a hull even if the tank is empty).

-the alarm will not play if there is air to breathe in the hull, it will immediately begin playing when their is insufficient air to breathe suddenly regardless of how long since you had an empty tank (or no tank) in the PUCS.

-I tried lowering my game to a near-unresponsive 5-8 FPS and the sound still played fine.

note: There is a max concurrent sound limit, it could be you somehow had too many sounds playing at once (Multiple turrets, fires, flooding sounds etc) that both the alarm is drowned out and misses a lot of sounds? but that would have to be an incredibly busy scene.

**Comment by Regalis11** [comment] 2022-08-17 09:33
No known steps to repro, closing

**Closed by Regalis11** 2022-08-17 09:33 UTC
Labels: Bug, Need more info
