### ISSUE TITLE
No way to prioritize space for 2+ cargo missions at once

### ISSUE THREAD

**Issue by DrinkFromTheCup** [Regalis11/Barotrauma#8265] opened 2022-02-13 13:06 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Now:
regardless of your choice of haul missions, first in list will take over ALL available space.
Need:
respect choosing order, (or prioritize more costy hauls, at least, - which might be easier to implement but worse for RP, we might not want to haul THAT load of explosives...).

**Steps To Reproduce**
Enter the outpost.
Get two haul missions with same destination yet different $ per crate. Make sure that your sub don't have enough shelf space to accept ALL crates from both missions.
During mission select, tick 2nd hauling mission in the list.
Then, tick 1st hauling mission in the list.

Expectation: as 2nd mission was ticked first AND was respected for mission screen update (note that 1st mission's proposed reward was reduced!), it's expected that on ticking 1st mission its crates would fill remaining space only (and provide the reward for these fillers only).

Reality: 1st mission takes over all available space while 2nd fills remaining space.

**Version**
Today's vanilla Unstable. Win10 x64 RU.

**Additional information**
Savegame: 
[Save 0.zip](https://github.com/Regalis11/Barotrauma/files/8055556/Save.0.zip)
Screenies:
![20220213155306_1](https://user-images.githubusercontent.com/81986452/153754432-b8fac3cc-86cf-43db-ae9e-93fb9a96be1c.jpg)
![20220213155311_1](https://user-images.githubusercontent.com/81986452/153754439-a4f37d8f-33a4-436c-8a28-df40ed7db045.jpg)
![20220213155316_1](https://user-images.githubusercontent.com/81986452/153754444-f389a23c-6290-4610-88a1-f379fbd14291.jpg)

**Comment by Regalis11** [comment] 2022-02-14 11:11
Thank you for the report! I agree that this is something we should address, but I'd consider this a feature request rather than a bug report, so I'll close the ticket.

Also a duplicate of https://github.com/Regalis11/Barotrauma/issues/7012

**Closed by Regalis11** 2022-02-14 11:11 UTC
