### ISSUE TITLE
Water current overpowering sub

### ISSUE THREAD

**Issue by baropoo** [Regalis11/Barotrauma#6094] opened 2021-06-17 06:59 UTC
The submarine cannot get past the water current at any angle or direction on spawn.

Windows.

I've read on another forum that this bug has been fixed by making water currents despawn, however, this is not the case for me.

![image](https://user-images.githubusercontent.com/86042452/122347371-dea34d00-cf41-11eb-9a93-a9622ed45f47.png)

**Comment by Krzeszny** [comment] 2021-07-06 10:33
It might be a feature. You're supposed to open the airlock or cut through the airlock or even add a button that opens it remotely.

**Comment by Regalis11** [comment] 2021-07-08 13:20
@Krzeszny This isn't an intentional feature, it should always be possible to get through the currents (even though it may sometimes require waiting a bit for them to die down). 

I gave this a test in a couple of levels in the Europan Ridge, but couldn't reproduce the issue: the currents seem to always quiet down after a minute of so of waiting. @baropoo do you recall which biome this happened in, or do you happen to have the save file still available so we could give it a test?

**Comment by Regalis11** [comment] 2021-11-23 09:33
No known steps to repro, closing

**Closed by Regalis11** 2021-11-23 09:33 UTC
Labels: Bug, Need more info, Code
