### ISSUE TITLE
Searchlights can't be seen by AI

### ISSUE THREAD

**Issue by BlackMoons** [Regalis11/Barotrauma#12970] opened 2023-11-05 00:14 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Testing using debugdraw and aitargets shows that active searchlights do not produce any blue 'visible' sphere around them.

Turret lights produce one, so I assume this is unintended behavior for search lights. 

### Reproduction steps

Sub editor, place a searchlight that is powered and on, enable debugdraw and aitargets

No blue 'visible' sphere around it. 

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by SomeRandomNoobKekeke** [comment] 2023-11-05 03:43
yep, there's no aitarget in searchlight item

**Comment by Regalis11** [comment] 2023-11-06 08:00
Duplicate of https://github.com/Regalis11/Barotrauma/issues/12265

**Closed by Regalis11** 2023-11-06 08:00 UTC
