### ISSUE TITLE
Can't create an entity event for Barotrauma.Hull - the ID of the entity has been freed.

### ISSUE THREAD

**Issue by guoguo909** [Regalis11/Barotrauma#8382] opened 2022-02-26 02:46 UTC
In the latest version of Windows, the custom submarine experienced severe up-and-down oscillations,  Can't create an entity event for Barotrauma.Hull - the ID of the entity has been freed.

**Comment by Regalis11** [comment] 2022-02-28 08:42
Thank you for the report!

Would it be possible to send us the full error message or the submarine file in question so we could give it a test ourselves?

**Comment by guoguo909** [comment] 2022-02-28 10:38
The situation disappeared after the latest update, but there are still other problems, such as severe shaking from the docking bay down, and bleeding  。How to send a file？

**Comment by Regalis11** [comment] 2022-02-28 11:46
You could attach it to your post here on GitHub: you will have to .zip it first though, since GitHub doesn't allow attaching files with the .sub file extension.

Thanks and sorry for the trouble!

**Comment by guoguo909** [comment] 2022-02-28 11:48
[1.zip](https://github.com/Regalis11/Barotrauma/files/8153057/1.zip)

**Comment by Regalis11** [comment] 2022-03-01 13:40
Thank you! I'm afraid I still couldn't reproduce the problem though. What exactly is shaking below the docking port - the whole sub? What do you mean by bleeding? Does this happen in some specific game mode or after doing something in specific?

**Comment by Regalis11** [comment] 2022-05-31 07:00
No known steps to repro, closing

**Closed by Regalis11** 2022-05-31 07:00 UTC
Labels: Bug, Need more info, Code, Networking
