### ISSUE TITLE
[Feature Request] Auto Restart after selecting new core package

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1416] opened 2019-04-11 04:21 UTC
Something like after selecting a new core package and clicking apply, a message saying "The game will now restart to apply the core package. [Cancel] [Continue]" as it is now a player can continue w/o restarting and run into a lot of errors.

**Comment by Regalis11** [comment] 2019-04-11 08:46
Duplicate of #1118

**Closed by Regalis11** 2019-04-11 08:46 UTC
