### ISSUE TITLE
StatusHUD Component doesn't account for non-user/turret line of sight

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#5682] opened 2021-05-02 16:14 UTC
[Bug, Modding]
The StatusHUD itemcomponent (the one the health scanner uses) bases the health information visibility depending on where the users' position is and not actually which characters the user can "actually" see (where the viewport is centered, like a turret or a camera). This normally makes sense because the scanner is on the player, but this doesn't work with turrets or cameras that could otherwise have healthhud components implemented into them.
![image](https://user-images.githubusercontent.com/47284081/116819540-fd02e400-ab5f-11eb-89f8-fdd45a8ab528.png)
Door Open, viewed through Health Scanning turret: Health info is visible
![image](https://user-images.githubusercontent.com/47284081/116819552-0b510000-ab60-11eb-8892-9413c0932d98.png)
Door Closed (Out of player character LOS), viewed through health scanning turret: Health info isn't visible
![image](https://user-images.githubusercontent.com/47284081/116819574-23288400-ab60-11eb-8ddf-193bcc0a98f5.png)
It would be great if there were an option to make the health scanners visibility check centered from wherever the viewport has been "transferred"or StatusHUD is, instead of just the player.

**Comment by Regalis11** [comment] 2021-05-14 13:33
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/9f68ea1be6468608d2d727e8da8077dcf4f92c3a

**Comment by Rokvach** [comment] 2021-06-04 11:58
This can be tested in Unstable

**Comment by Udrakan** [comment] 2021-06-05 23:38
Seems to NOT work as intended:
Turret has <StatusHUD />
1) Looking through turret at a person thats in my view: status is shown
2) Looking through turret at a person not in my view: status is NOT shown
![image](https://user-images.githubusercontent.com/59519434/120908081-4961a800-c667-11eb-9f47-da2c62a0f04e.png)

Modded turret: 
[UnstableTest.zip](https://github.com/Regalis11/Barotrauma/files/6603407/UnstableTest.zip)

Submarine from the pictures:
[StatusHUDtest.zip](https://github.com/Regalis11/Barotrauma/files/6603408/StatusHUDtest.zip)

STR:
-Activate mod UnstableTest
-Load submarine StatusHUDtest, testmode
-left periscope is interior, right periscope is for outside turret

**Comment by Rokvach** [comment] 2021-06-06 00:06
Moving to Misc

**Comment by Regalis11** [comment] 2021-06-07 12:54
Could not reproduce.
![image](https://user-images.githubusercontent.com/14351070/121019878-7ff30c00-c7a8-11eb-940f-1e6b58212ad3.png)

It seems to me the character might be outside the range of the StatusHUD (500px by default), maybe you should try increasing the range?

**Comment by Rokvach** [comment] 2021-08-04 08:27
No issues, closing.

**Closed by Rokvach** 2021-08-04 08:27 UTC
Labels: Code, Modding, Need more info
