### ISSUE TITLE
[0.10.4.0] Deleted unconnected wire crash

### ISSUE THREAD

**Issue by Coryf88** [Regalis11/Barotrauma#3740] opened 2020-09-06 17:46 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Crash when clicking outside of the connection panel, after deleting a dangling wire.

**Steps To Reproduce**
1. Open the submarine editor.
2. Place down two wire-able objects.
3. Wire them together.
4. Delete one of the objects.
5. Double click on the unconnected end of the wire.
6. Open the connection panel of the object.
7. Drag the connected wire outside of the connection panel.
8. Click outside of the connection panel.

**Version**
0.10.4.0
Windows

**Additional information**
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/5180039/crashreport.log)
https://youtu.be/rFapShCl8iU

**Comment by Regalis11** [comment] 2020-09-07 06:34
Couldn't reproduce this in the latest Unstable version, so this has probably been fixed as a side-effect of some of the other wiring-related fixes.

**Comment by Rokvach** [comment] 2020-09-07 08:36
Wasn't able to reproduce the crash, seems to have been already fixed. Closing

**Closed by Rokvach** 2020-09-07 08:36 UTC
Labels: Bug, Code, Crash
