### ISSUE TITLE
Probable Video Card Issue

### ISSUE THREAD

**Issue by nefariouskid** [Regalis11/Barotrauma#7870] opened 2021-12-20 02:49 UTC
Installed an nvidia NVS 310 graphics card. Before now was using onboard graphics, and Barotrauma worked but ran slow.  Now, Barotrauma always crashes and always at the same time - just as a map loads and gameplay begins.  All menus prior to that point work fine.  I have tried a few different video modes (bordered, fullscreen) and settings (different resolutions and slider settings), always the same result.

Windows 10.0.19044
Intel Core i5, 2.7GHz (4 logical)
12 GB RAM

Barotrauma Client crash report (generated on 12/18/2021 9:43:34 PM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

25F2DA9FCBD0323CBDF4FC2DA2092C7B

Game version 0.15.22.1 (ReleaseWindows, branch release, revision 898f64d2c0)
Graphics mode: 1920x1080 (Fullscreen)
VSync OFF
Language: English
Selected content packages: Vanilla 0.9, Huskmod, EK Utilities, EK Gunnery, EK Armory
Level seed: Novaya Moskva
Loaded submarine: Dugong (7B8BF1773561276CF75878F3D29CCA28)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA NVS 310
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.
 (SharpDX.SharpDXException)
Device removed reason: HRESULT = 0x887A0006
Target site: Void CheckError()
Stack trace: 
   at SharpDX.Result.CheckError()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 1017
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 511
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59

Last debug messages:
[12/18/2021 9:42:50 PM] Generating an outpost for the start of the level... (Location: Novaya Moskva Station, level type: Outpost)
[12/18/2021 9:37:11 PM] Overriding an affliction or a buff with the identifier 'huskinfection' using the file 'Mods/Huskmod/Afflictions.xml'
[12/18/2021 9:37:03 PM] (Msg) SDR RelayNetworkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[12/18/2021 9:37:03 PM] (Msg) Ping location: sea=20+2,lax=37+3/38+3,dfw=54+5,ord=63+6/67+2,atl=75+7/75+5,iad=84+8/87+2,tyo=120+12,tyo1=120+12,lim=152+15/138+3,fra=174+17/165+15,sgp=215+21/201+12,gru=201+20
[12/18/2021 9:37:03 PM] (Msg) Ping measurement completed
[12/18/2021 9:37:01 PM] (Verbose) Communications with routing cluster 'jnb' established.
[12/18/2021 9:37:01 PM] (Verbose) Communications with routing cluster 'sgp' established.
[12/18/2021 9:37:01 PM] (Verbose) Communications with routing cluster 'waw' established.
[12/18/2021 9:37:01 PM] (Verbose) Communications with routing cluster 'sto2' established.
[12/18/2021 9:37:01 PM] (Verbose) Communications with routing cluster 'vie' established.
[12/18/2021 9:37:01 PM] (Verbose) Communications with routing cluster 'syd' established.
[12/18/2021 9:37:01 PM] (Verbose) Communications with routing cluster 'sto' established.
[12/18/2021 9:37:01 PM] (Verbose) Communications with routing cluster 'seo' established.
[12/18/2021 9:37:01 PM] (Verbose) Communications with routing cluster 'maa' established.
[12/18/2021 9:37:00 PM] (Verbose) Communications with routing cluster 'tyo1' established.
[12/18/2021 9:37:00 PM] (Msg) Relay tyo#32 (155.133.239.19:27046) is going offline in 155 seconds
[12/18/2021 9:37:00 PM] (Verbose) Communications with routing cluster 'tyo' established.
[12/18/2021 9:37:00 PM] (Verbose) Communications with routing cluster 'dxb' established.
[12/18/2021 9:37:00 PM] (Verbose) Communications with routing cluster 'scl' established.
[12/18/2021 9:37:00 PM] (Verbose) Communications with routing cluster 'mad' established.
[12/18/2021 9:37:00 PM] (Verbose) Communications with routing cluster 'bom' established.
[12/18/2021 9:37:00 PM] (Verbose) Communications with routing cluster 'par' established.
[12/18/2021 9:37:00 PM] (Verbose) Communications with routing cluster 'lhr' established.
[12/18/2021 9:37:00 PM] (Verbose) Communications with routing cluster 'lim' established.
[12/18/2021 9:37:00 PM] (Verbose) Communications with routing cluster 'gru' established.
[12/18/2021 9:37:00 PM] (Verbose) Communications with routing cluster 'eze' established.
[12/18/2021 9:37:00 PM] (Verbose) Communications with routing cluster 'hkg' established.
[12/18/2021 9:37:00 PM] (Verbose) Communications with routing cluster 'fra' established.
[12/18/2021 9:37:00 PM] (Verbose) Communications with routing cluster 'ord' established.
[12/18/2021 9:37:00 PM] (Verbose) Communications with routing cluster 'ams' established.
[12/18/2021 9:37:00 PM] (Verbose) Communications with routing cluster 'lax' established.
[12/18/2021 9:37:00 PM] (Verbose) Communications with routing cluster 'sea' established.
[12/18/2021 9:37:00 PM] (Verbose) Communications with routing cluster 'iad' established.
[12/18/2021 9:37:00 PM] (Verbose) Communications with routing cluster 'atl' established.
[12/18/2021 9:37:00 PM] (Verbose) Communications with routing cluster 'dfw' established.
[12/18/2021 9:37:00 PM] (Msg) SDR RelayNetworkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[12/18/2021 9:37:00 PM] (Msg) Performing ping measurement
[12/18/2021 9:37:00 PM] (Msg) Got SDR network config.  Loaded revision 361 OK
[12/18/2021 9:37:00 PM] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[12/18/2021 9:36:41 PM] Attempting to open ALC device "OpenAL Soft on Speakers (High Definition Audio Device)"
[12/18/2021 9:36:40 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[12/18/2021 9:36:39 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[12/18/2021 9:36:38 PM] Logged in as NefariousKid (SteamID STEAM_1:1:161150344)

**Comment by Regalis11** [comment] 2021-12-20 10:38
Duplicate of https://github.com/Regalis11/Barotrauma/issues/1833

**Closed by Regalis11** 2021-12-20 10:38 UTC
