### ISSUE TITLE
Textboxes in custom interfaces clear when unfocused in multiplayer

### ISSUE THREAD

**Issue by Mannatwo** [Regalis11/Barotrauma#12508] opened 2023-08-16 09:21 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I am currently using the custom interfaces textbox functionality to store custom player-provided data for a mod I am making. It works perfectly in singleplayer, however, trying it out in multiplayer, the textbox seems to clear its field every time it is unfocused.

To check if this is also an issue with the base game, I disabled all mods, verified my gamefiles, and tried to use the item that I graciously borrowed the data from: The sonar beacon (that handheld one).
As it turns out, the same thing happens.
I remember it working fine not too long ago.

### Reproduction steps

1. Start a multiplayer game, the gamemode is not important
2. Enable cheats and spawn in a sonar beacon
3. Write something into the "Beacon signal" text field
4. Hit enter or unfocus the text field
5. The text you entered will be gone

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-08-16 09:36
Duplicate of https://github.com/Regalis11/Barotrauma/issues/12012 (the fix for that one is not included in the public version yet, just in the unstable branch)

**Closed by Regalis11** 2023-08-16 09:36 UTC

**Comment by Mannatwo** [comment] 2023-08-16 09:38
drat
the dreaded marked as duplicate
apologies
glad to hear its already fixed though
