### ISSUE TITLE
Blackmarket Genes skill not causing U.G.M. to appear in cities/research stations

### ISSUE THREAD

**Issue by DoubleWOMP** [Regalis11/Barotrauma#11236] opened 2023-02-13 02:13 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I just completed the Xenologist skill tree while playing the medical officer in a multiplayer campaign, and have noticed that since then, I have not been able to find any purchasable unidentified genetic material at cities or research stations. I took the blackmarket genes skill, and since then have checked every shop and vending machine in these stations when we dock, but I still haven't come across any extra genes. Maybe this is only unlikely to happen even after getting the skill, but I wasn't sure if anyone else had this problem.

### Bug prevalence

Happens regularly

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-02-13 07:34
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11189

**Closed by Regalis11** 2023-02-13 07:34 UTC
