### ISSUE TITLE
Bleeding Pierces Bloodloss Resistances

### ISSUE THREAD

**Issue by MrBubz03** [Regalis11/Barotrauma#10616] opened 2022-11-29 03:10 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Pretty straightforward, suffering bleeding builds up bloodloss in the **same rate** and **can't be slowed down by resistances**.

### Reproduction steps

Since the video file is more than 10MB, I'll leave a link to a video about the issue. **Turn the subtitles on** for more details.

https://www.youtube.com/watch?v=7Xa8bsueKFA

### Bug prevalence

Happens every time I play

### Version

Other

### -

All versions

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
-
```

**Comment by Regalis11** [comment] 2022-11-29 08:40
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10318, fixed in https://github.com/Regalis11/Barotrauma-development/commit/7b30fe3e2721667a09a82101ef4733a9f24afe38

**Closed by Regalis11** 2022-11-29 08:40 UTC
