### ISSUE TITLE
Server Crash During Thalmus Engagement

### ISSUE THREAD

**Issue by Ryanator** [Regalis11/Barotrauma#3903] opened 2020-09-25 06:03 UTC
Barotrauma Client crash report (generated on 9/25/2020 1:57:53 AM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

6F558E05A9FD96EA104348A23A5B582A

Game version 0.10.5.1 (ReleaseWindows, branch release, revision 9e259b2148)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9, Sweet Pea
Level seed: Sharpitor LineaDyfed
Loaded submarine: Typhon2 (DDA0B9397EF0BC9AE643AF36DBE0662B)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.18362.0 64 bit
    GPU name: NVIDIA GeForce GTX 1060 6GB
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Collection was modified; enumeration operation may not execute. (System.InvalidOperationException)
Target site: Void ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
Stack trace: 
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Barotrauma.Items.Components.RepairTool.Repair(Vector2 rayStart, Vector2 rayEnd, Single deltaTime, Character user, Single degreeOfSuccess, List`1 ignoredBodies) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Holdable\RepairTool.cs:line 297
   at Barotrauma.Items.Components.RepairTool.Use(Single deltaTime, Character character) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Holdable\RepairTool.cs:line 244
   at Barotrauma.Item.Use(Single deltaTime, Character character, Limb targetLimb) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 2055
   at Barotrauma.Character.Control(Single deltaTime, Camera cam) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 1475
   at Barotrauma.Character.Update(Single deltaTime, Camera cam) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2409
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2228
   at Barotrauma.GameScreen.Update(Double deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 179
   at Barotrauma.GameMain.Update(GameTime gameTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 921
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59

Last debug messages:
[9/25/2020 1:57:53 AM] WARNING: GameSession set to null while in the game screen
   at System.Environment.get_StackTrace()
   at Barotrauma.GameMain.set_GameSession(GameSession value) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 82
   at Barotrauma.Networking.GameClient.Disconnect() in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2605
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 666
   at Barotrauma.GameMain.Update(GameTime gameTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 948
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59
[9/25/2020 1:46:46 AM] Cheffy
[9/25/2020 1:46:46 AM] Captain Ryan
[9/25/2020 1:46:46 AM] CWO Aleksandr
[9/25/2020 1:46:46 AM] Elroy Jenkins
[9/25/2020 1:46:46 AM] Katherine
[9/25/2020 1:46:46 AM] Molten
[9/25/2020 1:46:46 AM] Jaden
[9/25/2020 1:21:22 AM] MacKenzie
[9/25/2020 1:21:22 AM] Jaden
[9/25/2020 1:21:22 AM] Molten
[9/25/2020 1:21:22 AM] Katherine
[9/25/2020 1:21:22 AM] Elroy Jenkins
[9/25/2020 1:21:22 AM] CWO Aleksandr
[9/25/2020 1:21:22 AM] Cheffy
[9/25/2020 1:21:22 AM] Captain Ryan
[9/25/2020 1:21:16 AM] Cheffy
[9/25/2020 1:21:16 AM] MacKenzie
[9/25/2020 1:21:16 AM] Captain Ryan
[9/25/2020 1:21:16 AM] CWO Aleksandr
[9/25/2020 1:21:16 AM] Elroy Jenkins
[9/25/2020 1:21:16 AM] Katherine
[9/25/2020 1:21:16 AM] Molten
[9/25/2020 1:21:16 AM] Jaden
[9/25/2020 1:21:15 AM] Cheffy
[9/25/2020 1:21:15 AM] MacKenzie
[9/25/2020 1:21:15 AM] Captain Ryan
[9/25/2020 1:21:15 AM] CWO Aleksandr
[9/25/2020 1:21:15 AM] Elroy Jenkins
[9/25/2020 1:21:15 AM] Katherine
[9/25/2020 1:21:15 AM] Molten
[9/25/2020 1:21:15 AM] Jaden
[9/25/2020 1:21:13 AM] Cheffy
[9/25/2020 1:21:13 AM] MacKenzie
[9/25/2020 1:21:13 AM] Captain Ryan
[9/25/2020 1:21:13 AM] CWO Aleksandr
[9/25/2020 1:21:13 AM] Elroy Jenkins
[9/25/2020 1:21:13 AM] Katherine
[9/25/2020 1:21:13 AM] Molten
[9/25/2020 1:21:13 AM] Jaden
[9/25/2020 1:21:13 AM] Cheffy
[9/25/2020 1:21:13 AM] MacKenzie
[9/25/2020 1:21:13 AM] Captain Ryan
[9/25/2020 1:21:13 AM] CWO Aleksandr
[9/25/2020 1:21:13 AM] Elroy Jenkins
[9/25/2020 1:21:13 AM] Katherine
[9/25/2020 1:21:13 AM] Molten
[9/25/2020 1:21:13 AM] Jaden
[9/25/2020 1:21:12 AM] MacKenzie
[9/25/2020 1:21:12 AM] CWO Aleksandr
[9/25/2020 1:21:12 AM] Elroy Jenkins
[9/25/2020 1:21:12 AM] Katherine
[9/25/2020 1:21:12 AM] Molten
[9/25/2020 1:21:12 AM] Jaden
[9/25/2020 1:21:12 AM] Cheffy
[9/25/2020 1:21:12 AM] Captain Ryan
[9/25/2020 1:21:09 AM] Task count: 0
[9/25/2020 1:21:06 AM] Generating an outpost for the end of the level... (Location: Dyfed, level type: LocationConnection)
[9/25/2020 1:21:05 AM] Generating an outpost for the start of the level... (Location: Sharpitor Linea Station, level type: LocationConnection)
[9/25/2020 1:20:55 AM] Cheffy
[9/25/2020 1:20:55 AM] MacKenzie
[9/25/2020 1:20:55 AM] Captain Ryan
[9/25/2020 1:20:55 AM] WO Aleksandr
[9/25/2020 1:20:55 AM] Elroy Jenkins
[9/25/2020 1:20:55 AM] Katherine
[9/25/2020 1:20:55 AM] Molten
[9/25/2020 1:20:55 AM] Jaden
[9/25/2020 1:20:55 AM] WARNING: Could not determine reputation change for faction "Children of the Honkmother" (faction was not present at the start of the round).
[9/25/2020 1:20:55 AM] WARNING: Could not determine reputation change for faction "The Church of Husk" (faction was not present at the start of the round).
[9/25/2020 1:20:55 AM] WARNING: Could not determine reputation change for faction "Jovian Separatists" (faction was not present at the start of the round).
[9/25/2020 1:20:55 AM] WARNING: Could not determine reputation change for faction "Europa Coalition" (faction was not present at the start of the round).
[9/25/2020 1:10:55 AM] Cheffy
[9/25/2020 1:10:55 AM] MacKenzie
[9/25/2020 1:10:55 AM] Captain Ryan
[9/25/2020 1:10:55 AM] WO Aleksandr
[9/25/2020 1:10:55 AM] Elroy Jenkins
[9/25/2020 1:10:55 AM] Katherine
[9/25/2020 1:10:55 AM] Molten
[9/25/2020 1:10:55 AM] Jaden
[9/25/2020 12:56:52 AM] Cheffy
[9/25/2020 12:56:52 AM] MacKenzie
[9/25/2020 12:56:52 AM] Captain Ryan
[9/25/2020 12:56:52 AM] WO Aleksandr
[9/25/2020 12:56:52 AM] Elroy Jenkins
[9/25/2020 12:56:52 AM] Katherine
[9/25/2020 12:56:52 AM] Giovanni
[9/25/2020 12:56:52 AM] Molten
[9/25/2020 12:56:52 AM] Jaden
[9/25/2020 12:56:46 AM] Cheffy
[9/25/2020 12:56:46 AM] MacKenzie
[9/25/2020 12:56:46 AM] Captain Ryan
[9/25/2020 12:56:46 AM] WO Aleksandr
[9/25/2020 12:56:46 AM] Elroy Jenkins
[9/25/2020 12:56:46 AM] Katherine
[9/25/2020 12:56:46 AM] Giovanni
[9/25/2020 12:56:46 AM] Molten
[9/25/2020 12:56:46 AM] Jaden
[9/25/2020 12:56:45 AM] Cheffy
[9/25/2020 12:56:45 AM] MacKenzie
[9/25/2020 12:56:45 AM] Captain Ryan
[9/25/2020 12:56:45 AM] WO Aleksandr
[9/25/2020 12:56:45 AM] Elroy Jenkins
[9/25/2020 12:56:45 AM] Katherine
[9/25/2020 12:56:45 AM] Giovanni
[9/25/2020 12:56:45 AM] Molten
[9/25/2020 12:56:45 AM] Jaden
[9/25/2020 12:56:45 AM] Cheffy
[9/25/2020 12:56:45 AM] MacKenzie
[9/25/2020 12:56:45 AM] Captain Ryan
[9/25/2020 12:56:45 AM] WO Aleksandr
[9/25/2020 12:56:45 AM] Elroy Jenkins
[9/25/2020 12:56:45 AM] Katherine
[9/25/2020 12:56:45 AM] Giovanni
[9/25/2020 12:56:45 AM] Molten
[9/25/2020 12:56:45 AM] Jaden
[9/25/2020 12:56:45 AM] Cheffy
[9/25/2020 12:56:45 AM] MacKenzie
[9/25/2020 12:56:45 AM] Captain Ryan
[9/25/2020 12:56:45 AM] WO Aleksandr
[9/25/2020 12:56:45 AM] Elroy Jenkins
[9/25/2020 12:56:45 AM] Katherine
[9/25/2020 12:56:45 AM] Giovanni
[9/25/2020 12:56:45 AM] Molten
[9/25/2020 12:56:45 AM] Jaden
[9/25/2020 12:56:44 AM] Cheffy
[9/25/2020 12:56:44 AM] MacKenzie
[9/25/2020 12:56:44 AM] Captain Ryan
[9/25/2020 12:56:44 AM] WO Aleksandr
[9/25/2020 12:56:44 AM] Elroy Jenkins
[9/25/2020 12:56:44 AM] Katherine
[9/25/2020 12:56:44 AM] Giovanni
[9/25/2020 12:56:44 AM] Molten
[9/25/2020 12:56:44 AM] Jaden
[9/25/2020 12:56:43 AM] Cheffy
[9/25/2020 12:56:43 AM] MacKenzie
[9/25/2020 12:56:43 AM] Captain Ryan
[9/25/2020 12:56:43 AM] WO Aleksandr
[9/25/2020 12:56:43 AM] Elroy Jenkins
[9/25/2020 12:56:43 AM] Katherine
[9/25/2020 12:56:43 AM] Giovanni
[9/25/2020 12:56:43 AM] Molten
[9/25/2020 12:56:43 AM] Jaden
[9/25/2020 12:56:42 AM] Cheffy
[9/25/2020 12:56:42 AM] MacKenzie
[9/25/2020 12:56:42 AM] Captain Ryan
[9/25/2020 12:56:42 AM] WO Aleksandr
[9/25/2020 12:56:42 AM] Elroy Jenkins
[9/25/2020 12:56:42 AM] Katherine
[9/25/2020 12:56:42 AM] Giovanni
[9/25/2020 12:56:42 AM] Molten
[9/25/2020 12:56:42 AM] Jaden
[9/25/2020 12:56:41 AM] Cheffy
[9/25/2020 12:56:41 AM] MacKenzie
[9/25/2020 12:56:41 AM] Captain Ryan
[9/25/2020 12:56:41 AM] Elroy Jenkins
[9/25/2020 12:56:41 AM] Katherine
[9/25/2020 12:56:41 AM] Giovanni
[9/25/2020 12:56:41 AM] Molten
[9/25/2020 12:56:41 AM] Jaden
[9/25/2020 12:56:40 AM] WO Aleksandr
[9/25/2020 12:56:39 AM] Task count: 0
[9/25/2020 12:56:38 AM] Generating an outpost for the start of the level... (Location: Sharpitor Linea Station, level type: Outpost)
[9/25/2020 12:53:02 AM] Mal P. Ractice
[9/25/2020 12:53:02 AM] Practi Cal Problems
[9/25/2020 12:53:02 AM] SC Ryan
[9/25/2020 12:53:02 AM] CWO Aleksandr
[9/25/2020 12:53:02 AM] Geoffery Jenkins
[9/25/2020 12:53:02 AM] pocl.v
[9/25/2020 12:53:02 AM] Giovanni
[9/25/2020 12:53:02 AM] Molten
[9/25/2020 12:53:02 AM] zirconzz
[9/25/2020 12:27:23 AM] Mal P. Ractice
[9/25/2020 12:27:23 AM] Practi Cal Problems
[9/25/2020 12:27:23 AM] SC Ryan
[9/25/2020 12:27:23 AM] CWO Aleksandr
[9/25/2020 12:27:23 AM] Geoffery Jenkins
[9/25/2020 12:27:23 AM] pocl.v
[9/25/2020 12:27:23 AM] Giovanni
[9/25/2020 12:27:23 AM] Molten
[9/25/2020 12:27:23 AM] zirconzz
[9/25/2020 12:27:15 AM] Mal P. Ractice
[9/25/2020 12:27:15 AM] Practi Cal Problems
[9/25/2020 12:27:15 AM] SC Ryan
[9/25/2020 12:27:15 AM] CWO Aleksandr
[9/25/2020 12:27:15 AM] Geoffery Jenkins
[9/25/2020 12:27:15 AM] pocl.v
[9/25/2020 12:27:15 AM] Giovanni
[9/25/2020 12:27:15 AM] Molten
[9/25/2020 12:27:15 AM] zirconzz
[9/25/2020 12:27:12 AM] Mal P. Ractice
[9/25/2020 12:27:12 AM] Practi Cal Problems
[9/25/2020 12:27:12 AM] SC Ryan
[9/25/2020 12:27:12 AM] CWO Aleksandr
[9/25/2020 12:27:12 AM] Geoffery Jenkins
[9/25/2020 12:27:12 AM] pocl.v
[9/25/2020 12:27:12 AM] Giovanni
[9/25/2020 12:27:12 AM] Molten
[9/25/2020 12:27:12 AM] zirconzz
[9/25/2020 12:27:09 AM] Mal P. Ractice
[9/25/2020 12:27:09 AM] Practi Cal Problems
[9/25/2020 12:27:09 AM] SC Ryan
[9/25/2020 12:27:09 AM] CWO Aleksandr
[9/25/2020 12:27:09 AM] Geoffery Jenkins
[9/25/2020 12:27:09 AM] pocl.v
[9/25/2020 12:27:09 AM] Giovanni
[9/25/2020 12:27:09 AM] Molten
[9/25/2020 12:27:09 AM] zirconzz
[9/25/2020 12:27:09 AM] Practi Cal Problems
[9/25/2020 12:27:09 AM] Geoffery Jenkins
[9/25/2020 12:27:09 AM] pocl.v
[9/25/2020 12:27:09 AM] Giovanni
[9/25/2020 12:27:09 AM] Molten
[9/25/2020 12:27:09 AM] zirconzz
[9/25/2020 12:27:09 AM] Mal P. Ractice
[9/25/2020 12:27:09 AM] SC Ryan
[9/25/2020 12:27:09 AM] CWO Aleksandr
[9/25/2020 12:27:06 AM] Task count: 0
[9/25/2020 12:27:04 AM] Generating an outpost for the end of the level... (Location: Berith Habitation Outpost, level type: LocationConnection)
[9/25/2020 12:22:53 AM] SC Ryan
[9/25/2020 12:22:53 AM] CWO Aleksandr
[9/25/2020 12:22:53 AM] Geoffery Jenkins
[9/25/2020 12:22:53 AM] Cheffy
[9/25/2020 12:22:53 AM] pocl.v
[9/25/2020 12:22:53 AM] Giovanni
[9/25/2020 12:22:53 AM] Molten
[9/25/2020 12:22:53 AM] Kate
[9/25/2020 12:22:53 AM] zirconzz
[9/24/2020 11:52:07 PM] SC Ryan
[9/24/2020 11:52:07 PM] CWO Aleksandr
[9/24/2020 11:52:07 PM] Geoffery Jenkins
[9/24/2020 11:52:07 PM] Cheffy
[9/24/2020 11:52:07 PM] pocl.v
[9/24/2020 11:52:07 PM] Giovanni
[9/24/2020 11:52:07 PM] Molten
[9/24/2020 11:52:07 PM] Kate
[9/24/2020 11:52:07 PM] zirconzz
[9/24/2020 11:33:39 PM] SC Ryan
[9/24/2020 11:33:39 PM] CWO Aleksandr
[9/24/2020 11:33:39 PM] Geoffery Jenkins
[9/24/2020 11:33:39 PM] Cheffy
[9/24/2020 11:33:39 PM] pocl.v
[9/24/2020 11:33:39 PM] Giovanni
[9/24/2020 11:33:39 PM] Molten
[9/24/2020 11:33:39 PM] Kate
[9/24/2020 11:33:39 PM] zirconzz
[9/24/2020 11:33:37 PM] SC Ryan
[9/24/2020 11:33:37 PM] CWO Aleksandr
[9/24/2020 11:33:37 PM] Geoffery Jenkins
[9/24/2020 11:33:37 PM] Cheffy
[9/24/2020 11:33:37 PM] pocl.v
[9/24/2020 11:33:37 PM] Giovanni
[9/24/2020 11:33:37 PM] Molten
[9/24/2020 11:33:37 PM] Kate
[9/24/2020 11:33:37 PM] zirconzz
[9/24/2020 11:33:37 PM] SC Ryan
[9/24/2020 11:33:37 PM] CWO Aleksandr
[9/24/2020 11:33:37 PM] Geoffery Jenkins
[9/24/2020 11:33:37 PM] Cheffy
[9/24/2020 11:33:37 PM] pocl.v
[9/24/2020 11:33:37 PM] Giovanni
[9/24/2020 11:33:37 PM] Molten
[9/24/2020 11:33:37 PM] Kate
[9/24/2020 11:33:37 PM] zirconzz
[9/24/2020 11:33:36 PM] SC Ryan
[9/24/2020 11:33:36 PM] CWO Aleksandr
[9/24/2020 11:33:36 PM] Geoffery Jenkins
[9/24/2020 11:33:36 PM] Cheffy
[9/24/2020 11:33:36 PM] pocl.v
[9/24/2020 11:33:36 PM] Giovanni
[9/24/2020 11:33:36 PM] Molten
[9/24/2020 11:33:36 PM] Kate
[9/24/2020 11:33:36 PM] zirconzz
[9/24/2020 11:33:36 PM] SC Ryan
[9/24/2020 11:33:36 PM] CWO Aleksandr
[9/24/2020 11:33:36 PM] Geoffery Jenkins
[9/24/2020 11:33:36 PM] Cheffy
[9/24/2020 11:33:36 PM] pocl.v
[9/24/2020 11:33:36 PM] Giovanni
[9/24/2020 11:33:36 PM] Molten
[9/24/2020 11:33:36 PM] Kate
[9/24/2020 11:33:36 PM] zirconzz
[9/24/2020 11:33:35 PM] SC Ryan
[9/24/2020 11:33:35 PM] CWO Aleksandr
[9/24/2020 11:33:35 PM] Geoffery Jenkins
[9/24/2020 11:33:35 PM] Cheffy
[9/24/2020 11:33:35 PM] pocl.v
[9/24/2020 11:33:35 PM] Giovanni
[9/24/2020 11:33:35 PM] Molten
[9/24/2020 11:33:35 PM] Kate
[9/24/2020 11:33:35 PM] zirconzz
[9/24/2020 11:33:31 PM] Task count: 0
[9/24/2020 11:33:28 PM] Generating an outpost for the end of the level... (Location: Zamoroska Habitation Outpost, level type: LocationConnection)
[9/24/2020 11:14:59 PM] Traitor Mir
[9/24/2020 11:14:59 PM] Ty
[9/24/2020 11:14:59 PM] katherine.v
[9/24/2020 11:14:59 PM] Molten
[9/24/2020 11:14:59 PM] Kate
[9/24/2020 11:14:59 PM] WO Aleksandr
[9/24/2020 11:14:59 PM] Elroy Jenkins
[9/24/2020 11:14:59 PM] zirconzz

**Comment by Regalis11** [comment] 2020-09-25 07:11
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3896, should be fixed for the next patch!

**Closed by Regalis11** 2020-09-25 07:11 UTC
