### ISSUE TITLE
Blackmarket genes doesnt work properly

### ISSUE THREAD

**Issue by XGabriel08X** [Regalis11/Barotrauma#10307] opened 2022-11-10 20:23 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If the game behaved correctly then the genes would not appear without that medical talent
![Screenshot (148)](https://user-images.githubusercontent.com/108592572/201198127-df13380d-310c-4ed1-9de3-b4efca4c38c2.png)

![Screenshot (150)](https://user-images.githubusercontent.com/108592572/201198159-6ef1390c-c8b8-4b3c-9d6f-5e1676a1578d.png)

### Reproduction steps

1. play game
2. go the a city
3. they will sell all types of genes withouth the medical talent ,,black market genes

### Bug prevalence

Happens every time I play

### Version

0.20.3.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by XGabriel08X** [comment] 2022-11-10 20:24
*2. go to a colony*

**Comment by Regalis11** [comment] 2022-11-11 08:16
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10247

**Closed by Regalis11** 2022-11-11 08:16 UTC
