### ISSUE TITLE
Make doors wait for a server response before telling the client it's open - Feature Request

### ISSUE THREAD

**Issue by Momiro** [Regalis11/Barotrauma#579] opened 2018-08-05 08:04 UTC
When opening doors while connected to any server, the door immediately opens, but sometimes closes right after, and even though there was enough time for the client player to pass through, they'll get rubberbanded back to their spot before the door opened. I suggest the door doesn't open for the client until the client has received a response from the server saying it's open.

**Comment by Regalis11** [comment] 2018-08-05 18:38
If we made the clients wait for a server response it would cause even more rubberbanding. The game uses client-side prediction for the character movement, meaning that the clients start processing movement inputs immediately and correct the position of the character if the predicted position doesn't correspond with the one sent by the server (if we didn't do this, there would always be a noticeable lag in character movements). The doors work the same way, the client opens the door immediately and corrects the state if the server doesn't verify that the door opened. If the clients didn't do this, opening a door would happen immediately after the input server-side, but with a small delay client-side, causing the client-side prediction to be always slightly off. But with the current system the rubberbanding only happens when the server denies the client from opening the door, for example due to the position of the character being slightly too far from the button server-side while the position predicted client-side is close enough.

**Comment by NilanthAnimosus** [comment] 2018-08-05 19:28
Just to add to this, there are some bugs caused by the prediction of door opening/closing. I will find myself able to pass through closed doors because client-side wire logic actually closes them when they should be open, generally making some submarines very irritating to play.

One of the common ones suffering this issue is the old SS Odessey submarines doors, they use far too much wire logic (every door is wired) with 2 mechanisms, one to open and one to 4-second override an auto-flooding door lock which denies opening. 

It is difficult to describe why this causes issues, but the usual servers I have played on I have found the doors essentially closed by wire logic when they are actually open server-side, which the delays in setting the door to the correct state doesn't actually work correctly.

**Comment by Regalis11** [comment] 2018-08-23 12:03
I believe the issue with SS Odyssey (and most likely other subs that had similar problems) is now fixed, but there might still be some cases where some convoluted relay/delay setup causes the same bug. I'll close this for now but will reopen if the problem reappears in some other sub.

**Closed by Regalis11** 2018-08-23 12:03 UTC
Labels: Networking-related
