### ISSUE TITLE
Unstable: Bots can't swap oxygen tanks if they can't find any safe hull to escape to

### ISSUE THREAD

**Issue by JarinArenos** [Regalis11/Barotrauma#3288] opened 2020-07-03 19:28 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In a complete flooding situation, AI crew members will die of oxygen deprivation after their first O2 tank runs out

**Steps To Reproduce**
Flood a submarine in single-player with AI onboard, either by enemy action or other hull breach.

**Version**
Windows 10, game version 0.10.2.0.

**Additional information**
Tested in vanilla Dugong sub in single player. O2 bottle storage beneath the diving suit cabinets were full. AI did not attempt to retrieve more oxygen.

**Comment by itchyOwl** [comment] 2020-07-06 12:45
The problem is not that the bots couldn't swap tanks. The cause for the issue is that they get stuck in the find safety loop in certain cases. I'm working on it on a separate branch, but I don't think we should merge the whole branch into the next update release just yet, as the changes require thorough testing.

Removing the high prio tag, as the issue only manifests when the bots can't find any safe hulls, so it's a bit of a corner case.

**Comment by itchyOwl** [comment] 2020-07-06 13:50
Should be fixed in Regalis11/Barotrauma-development@00b6de8.

**Comment by itchyOwl** [comment] 2020-07-06 14:03
Easy steps to repro:

- Use the "explosion" command to flood all the hulls
- In dev the bots should keep swimming headlessly with FINDSAFETY objective priority 100, without any subobjectives
- In human-ai the bots should try to get a diving suit (or die trying)

**Comment by Rokvach** [comment] 2020-07-07 22:21
Didn't notice any issues, closing.

**Closed by Rokvach** 2020-07-07 22:21 UTC
Labels: Bug, Code
