### ISSUE TITLE
Journeymen talent for the assistant isint applying the +20 to primary skill properly

### ISSUE THREAD

**Issue by Basil-basil-basil** [Regalis11/Barotrauma#11005] opened 2023-01-21 23:25 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I was melding around in the sub editor to see how much of a bonus the skill bonus and whether or not you could stack it with multiple assistants and came to the conclusion that it is not giving a plus 20 to the primary skill but a plus 10 for both the assistant and the receiver. I reloaded the sub in the editor and just only spawned in 1 assistant with journeymen and the bug still prevails even after multiple reloads. I have not tested this in normal game-play settings.

### Reproduction steps

1. Load into any default sub in the editor
2. Spawn an assistant and a security officer
3. Give experience to the assistant and unlock apprentice and choose security officer for your apprenticeship (DO NOT JUST GIVE YOURSELF THE TALENT WITH THE GIVE TALENT COMMAND IT DOESENT WORK)
4. unlock the talent journeymen 
5. check the security officers skills and it will show only a bonus of +10 to weapons 

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by JeroonBosch** [comment] 2023-01-23 12:42
Thanks for the report! Seems like a few numbers were off in the XML files

**Comment by BiffW** [comment] 2023-01-23 16:02
Duplicate of #10923

**Comment by ekqvist** [comment] 2023-01-24 14:18
Tested. Both the description and the skill boost seem to match at 10 now. Closing.

**Closed by ekqvist** 2023-01-24 14:18 UTC
Labels: Bug, Code, Design
