### ISSUE TITLE
[Factions] Hostage NPCs run away if you have negative reputation

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#11006] opened 2023-01-22 00:48 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If you rescue a faction abandoned outpost with negative reputation towards that faction, the hostages will run away from you if you don't explicitely assign them the "Follow" order. This can cause hostages to scatter around the station or get stuck in a room at the edge of your sub

Here we had -100 coalition rep, and rescued a coalition outpost

![image](https://user-images.githubusercontent.com/73229309/213895577-3cb8ba37-223a-4d11-9695-0a2415936560.png)

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-01-23 11:07
Seems to have been caused by the same bug as https://github.com/Regalis11/Barotrauma/issues/10995: if the outpost belonged to a faction originally, the NPCs would be considered part of that faction even after the outpost becomes abandoned. Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/9128862f80fc065cd9b72559131bd8b690851184

**Comment by JeroonBosch** [comment] 2023-01-31 10:33
Gave myself negative reputation with separatists in an abandoned outpost affiliated with separatists: the hostages still run away from the player if not explicitly ordered to follow.  Moving back

**Comment by JeroonBosch** [comment] 2023-01-31 11:49
Cannot reproduce faction-affiliated abandoned outpost after the fix, so closing

**Closed by JeroonBosch** 2023-01-31 11:49 UTC
Labels: Bug, Code
