### ISSUE TITLE
Human animation controller can only use the default anim of its species in game, not the one defined for it via mods.

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1120] opened 2019-02-11 21:49 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Mod creators cannot seem to get the human characters to use different animation parameter files in the game.

**Version**
Closed alpha 0.8.9.3

**Additional information**
This may not be accurate and I have tried to look for the reason below, and it could be it works correctly as I am not modifying the animations myself.

I went looking through the code on this quickly to see if I could discern a possible reason, noticed there are two functions for getting an animation file. They both use the species name and animation type, the latter used in the editor only includes the specific filename.

If your trying to replace an existing characters animations (IE. Human) using a mod, short of replacing the vanilla content asset in the content folder, it looks like it will always grab the first available animation file that has been loaded in the game using GetDefaultAnimParams in HumanWalkParams in the controller.

The filename is not provided, so it goes through GetAnimParams (the allAnimations dictionary) and goes off species for the first animation if finds - which is always going to be the vanilla content pack without a filename.

I don't think we can change the default species name for player characters currently or other humanoids/creatures, so the only way around this right now is perhaps to not load the vanilla content pack at all just to achieve an edit to a characters animations - There needs to be some method to be more explicit to which animation config to load in a character file.

Edit: After some more searching I noticed this which is used in the GetAnimParams methods, which seems fairly hardcoded to not check mod folders:
```csharp
public static string GetDefaultFolder(string speciesName) => $"Content/Characters/{speciesName.CapitaliseFirstInvariant()}/Animations/";
```

**Comment by NilanthAnimosus** [comment] 2019-02-12 00:00
After further looking into it, the simplest way to show this issue is the following codeblock.

Despite having it check using GetFolder (which in of itself i am not sure would pickup none-default content package contents of the same species name), the code completely skips whatever it is supplied once you reach "string.IsNullOrEmpty(fileName)" despite it maybe being specified in the GetFolder of the character file XML due to filename being empty out of the editor. I am not sure how its intended to be written logically, but I hope this is enough info.

```csharp
/// <summary>
        /// If the file name is left null, default file is selected. If fails, will select the default file. Note: Use the filename without the extensions, don't use the full path!
        /// If a custom folder is used, it's defined in the character info file.
        /// </summary>
        public static T GetAnimParams<T>(string speciesName, AnimationType animType, string fileName = null) where T : AnimationParams, new()
        {
            if (!allAnimations.TryGetValue(speciesName, out Dictionary<string, AnimationParams> anims))
            {
                anims = new Dictionary<string, AnimationParams>();
                allAnimations.Add(speciesName, anims);
            }
            if (fileName == null || !anims.TryGetValue(fileName, out AnimationParams anim))
            {
                string selectedFile = null;
                string folder = GetFolder(speciesName);
                if (Directory.Exists(folder))
                {
                    var files = Directory.GetFiles(folder);
                    if (files.None())
                    {
                        DebugConsole.ThrowError($"[AnimationParams] Could not find any animation files from the folder: {folder}. Using the default animation.");
                        selectedFile = GetDefaultFile(speciesName, animType);
                    }
                    var filteredFiles = FilterFilesByType(files, animType);
                    if (filteredFiles.None())
                    {
                        DebugConsole.ThrowError($"[AnimationParams] Could not find any animation files that match the animation type {animType} from the folder: {folder}. Using the default animation.");
                        selectedFile = GetDefaultFile(speciesName, animType);
                    }
                    else if (string.IsNullOrEmpty(fileName))
                    {
                        // Files found, but none specified.
                        selectedFile = GetDefaultFile(speciesName, animType);
                    }
                    else
                    {
                        selectedFile = filteredFiles.FirstOrDefault(f => Path.GetFileNameWithoutExtension(f).ToLowerInvariant() == fileName.ToLowerInvariant());
                        if (selectedFile == null)
                        {
                            DebugConsole.ThrowError($"[AnimationParams] Could not find an animation file that matches the name {fileName} and the animation type {animType}. Using the default animations.");
                            selectedFile = GetDefaultFile(speciesName, animType);
                        }
                    }
                }
                else
                {
                    DebugConsole.ThrowError($"[Animationparams] Invalid directory: {folder}. Using the default animation.");
                    selectedFile = GetDefaultFile(speciesName, animType);
                }
                if (selectedFile == null)
                {
                    throw new Exception("[AnimationParams] Selected file null!");
                }
                DebugConsole.Log($"[AnimationParams] Loading animations from {selectedFile}.");
                T a = new T();
                if (a.Load(selectedFile, speciesName))
                {
                    if (!anims.ContainsKey(a.Name))
                    {
                        anims.Add(a.Name, a);
                    }
                }
                else
                {
                    DebugConsole.ThrowError($"[AnimationParams] Failed to load an animation {a} at {selectedFile} of type {animType} for the character {speciesName}");
                }
                return a;
            }
            return (T)anim;
        }
```

**Comment by itchyOwl** [comment] 2019-02-12 08:27
You can create any number of animations. The files can be named anything, but currently only the default files are used in the game. So only the files named as "[Speciesname]Walk.xml" "[Speciesname]Run.xml" etc are used outside the editor.

In the editor you can edit the default animations or save them with another name. You can also load animations by name.

Note that editing the vanilla content is disabled for the release builds, because editing the animations would effectively create a mod, which would make you unable to play the vanilla version with other players. We probably need to add a switch that unlocks editing the vanilla content for editing.

The code block that you posted checks that if the filename is not provided or if the given animation is not found in the cache, it will create the animation param by loading it from file. It does not do this if the animation definition (param) is cached, because in that case it can simply return the cached definition. So it should work as is intended. Assigning custom animations is done like this: 

`character.AnimController.WalkParams = HumanWalkParams.GetAnimParams(character, fileName);`

The default folder is hardcoded, but it can be changed in the character config, by changing/adding the value of the "folder" attribute of the "animations" element. The code that looks for the custom path is this:

```
        protected static string GetFolder(string speciesName)
        {
            var folder = XMLExtensions.TryLoadXml(Character.GetConfigFile(speciesName))?.Root?.Element("animations")?.GetAttributeString("folder", string.Empty);
            if (string.IsNullOrEmpty(folder) || folder.ToLowerInvariant() == "default")
            {
                folder = GetDefaultFolder(speciesName);
            }
            return folder;
        }
```

I just tried creating a custom human animation and moving all human animations into a custom folder under mods. Then I assigned the (relative) path to the custom folder in the folder attribute like this:

` <animations folder="Mods/Test/Animations/"/>`

After that I put a break point into the code you provided and step through it. Everything seems to work allright. Have you tried that? If you haven't and you had issues, I'm curious how did you proceed?

**Comment by Regalis11** [comment] 2019-02-12 09:04
I think this is a problem with the content packages rather than the way animations are configured. Changing the human animations requires changes to the vanilla human configuration file, which in turn requires a completely new core content package because it's not possible to only replace one file in the vanilla package.

**Comment by NilanthAnimosus** [comment] 2019-02-12 09:24
I'll see if I can clear this up a little.

I have yet to try it personally and was seeing modders unable to get this working so I went over the code and followed the references for a few hours, I'll have to look at this further then and perhaps use a real test mod

I was going under the assumption however that not a single vanilla content file is modified, and it is 100% via mods and basing it off mod paths, I also had not used breakpoints given I did not have a mod to work with, but I could whip one up later to check.

I believe the above (Looking at it again) would just retrieve the first instance of "Human" from the character files (Instead of a second intended to replace it via a mod).

In my head though, I had assumed the following:
-Their is a folder defined, and it exists and has valid files.
-Filename is null, because it is in-game and not in-editor (References indicate this in the controllers)
-This should cause it to skip Files.None() and FilteredFiles.None() if statements as they would be found.

Finally we check if filename was null, it is indeed null in the intended case (IE. campaign/multiplayer). so we trigger GetDefaultFile(), which uses a hardcoded path of the vanilla content files only, which are not modified as they are actually in the mods directory using the correct default name format of the original anim files.

It may be its also impossible for a Mod to replace a vanilla XML entirely without effectively requiring to completely exclude the vanilla content pack, but the hard coded behaviour I believe would break the defined folders location even if it was a full content pack replacement intended to run without vanilla content packages loaded unless the content was placed in the vanilla folder.

To me it just looks like the code will always check the vanilla human xml over a modded one, but I'll have to test later to see if that is really not the case - I hadn't a mod to test this with but several modders were finding this to not seem to work

**Comment by Regalis11** [comment] 2019-02-12 11:49
> I believe the above (Looking at it again) would just retrieve the first instance of "Human" from the character files (Instead of a second intended to replace it via a mod).

Yes, that's intended behavior. At the moment it's not possible to selectively replace content from other content packages, so you need to disable the vanilla content package if you want to use another human config file (something we should probably change).

Anyway, I found an easy way to reproduce this: make a content package that replaces the vanilla humans and remove the vanilla human animation folder.

**Comment by ChikoEduardo** [comment] 2019-02-12 11:49
Well, I've been doing some tests and it seems this only affects the human xmls. I tried with both humans and husks and only the latter retained the changes.

**Comment by itchyOwl** [comment] 2019-02-12 14:20
You are right. The folder path was overridden by the default path. Should be fixed now.

**Closed by itchyOwl** 2019-02-12 14:20 UTC
Labels: bug, dev branch, need more info
