### ISSUE TITLE
Kastrull - Bots suffocating in Katrull Drone

### ISSUE THREAD

**Issue by Nanatu** [Regalis11/Barotrauma#4413] opened 2020-11-30 15:31 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots will go to repair the Kastrull Drone systems and end up suffocating.

**Steps To Reproduce**
-Wait for Kastrull Drone systems to degrade
-Set bots to Repair Damaged Systems
-Either watch the drone and wait or check chat for bot suffocating chat

**Version**
v0.10.6.2 (Windows.

**Additional information**
This happened recently when we added a bot to a ship with 3 bots and 4 Player crew. The bot that died was an older one with high electrical and mechanical (mid 50s in both). They went into the Kastrull drone to repair systems and suffocated despite wearing a mask. The mask was drained and we don't know how much O2 it had before they attempted repair.
It could have shocked itself unconscious with repairs and then suffocated, but looking back through the chat we didn't get any "Need Medical Attention..." cues until the suffocating sounds and the high repair skills didn't lend to that.
Could be a similar pathing as the issue with Kastrull Ballast tanks where the bot cannot get out.

**Comment by itchyOwl** [comment] 2021-02-01 10:15
So I guess they can't make their way out from there?

**Comment by Nanatu** [comment] 2021-02-01 14:37
It happens in the Kastrull's drone and it's ballast tanks. It seems like the pathing is ever so slightly off where they never fully leave the ballast.
But for the drone, they will stay in the drone till their mask runs out of O2 and they die.
I haven't watched it happen in the drone, so I don't know if it's a pathing issue exactly. But I have seen 3 Bots all in the ballasts moving up the ladder and then falling off before reaching the walkway.
If the ladders or nodes have been changed some, it could of fixed it, but I haven't checked/tested it in any way.

**Comment by itchyOwl** [comment] 2021-02-04 14:23
At least with the newly generated waypoints there doesn't seem to be any pathing issues. When the oxygen ran out the bots successfully escaped the drone and fetched masks.

However I was able to cause the bots to get confused when they ran out of oxygen, leading to suffocation. I think the same should happen also in the main sub, but a situation where all the rooms are out of oxygen and the bot with a mask that has no oxygen in it is quite rare. That issue should now be fixed in Regalis11/Barotrauma-development@209a331 and I think it could be the cause for the issues mentioned in this ticket too.

**Comment by Rokvach** [comment] 2021-02-24 15:53
Tested, wasn't able to reproduce, seems to be working correctly. Closing.

**Closed by Rokvach** 2021-02-24 15:53 UTC
Labels: Bug, Code, Medium Prio, Needs testing
