### ISSUE TITLE
Can't swap subs in multiplayer

### ISSUE THREAD

**Issue by barotraumaluke** [Regalis11/Barotrauma#8006] opened 2022-01-10 06:19 UTC
- [y ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Can't swap to pre-purchased submarines in multiplayer

**Steps To Reproduce**
-have any sub
-purchase any new sub (not purchase and switch)
-swap to new sub (fails)

OR

-have any sub
-purchase and switch to new sub
-swap to original sub (fails)

**Version**
0.15.22.1 Windows

**Additional information**
None

**Comment by Regalis11** [comment] 2022-01-10 08:25
Duplicate of #7862

**Closed by Regalis11** 2022-01-10 08:25 UTC

**Comment by barotraumaluke** [comment] 2022-01-10 08:48
how do i fix it?
________________________________

**Comment by Regalis11** [comment] 2022-01-10 13:52
The issue has been fixed in our private repository, but unfortunately the fix isn't out in the public version yet (although we're trying to push out a hotfix soon).

**Comment by barotraumaluke** [comment] 2022-01-12 13:15
thank you for your reply, i look forward to the next release. lovely game !
________________________________
