### ISSUE TITLE
Missions no longer appear in old campaign

### ISSUE THREAD

**Issue by VitalyArtemiev** [Regalis11/Barotrauma#9869] opened 2022-09-14 21:06 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I have a long-running multiplayer campaign, started in fall of 2021. After one of the last updates, there are no more quests in the outposts. I cannot pinpoint exactly which update broke it since we took a big break, but everything was fine in the first half of august.

Random events don't appear to generate either.
Quest markers which allow to open a passage to a new zone still appear.

Mods that we use: EK Armory, EK Utility, Shipwrecks Extended, Beacons Extended.

I've found at least one another report of this bug: https://www.reddit.com/r/Barotrauma/comments/w9sae4/help_i_have_no_more_quests/

If you can't fix this bug, but can provide some way to modify the save file to fix this for old campaigns, that would be cool too.

### Reproduction steps

(I cannot reproduce this since I'd need to downgrade the game to an old version, so I'll write assumed steps)
1. Start a multiplayer campaign with Among the Ancients update
2. Progressively update the game to the newest version
3. Enter a station 

### Bug prevalence

Just once

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-09-15 06:33
Thank you for the report! Would it be possible to send us the save file this happened in? It would most likely help us a lot in diagnosing the issue and we _might_ even be able to modify the save file in some way that gets rid of the issue. Note that you need to .zip the file to attach it here since doesn't allow attaching files with the .save file extension.

Thanks and sorry for the inconvenience!

**Comment by VitalyArtemiev** [comment] 2022-09-17 20:00
[save.zip](https://github.com/Regalis11/Barotrauma/files/9592523/save.zip)

Here's the save files. Thanks for your time.

**Comment by Regalis11** [comment] 2022-09-20 12:43
Thanks! I think I found the issue: it seems to have been caused by the changes we've done to the game's difficulty curve and the distribution of the events. The map in question still uses the old difficulty curve, and there are no suitable events available for the outpost in the new event sets. 

Here's a modified save file (with the difficulties of the levels adjusted to match the new event sets) that should fix the issue:
[save.zip](https://github.com/Regalis11/Barotrauma/files/9607657/save.zip)

**Comment by Regalis11** [comment] 2022-09-20 13:05
Adjusted the event distribution in https://github.com/Regalis11/Barotrauma-development/commit/acc0aa550784fd6633a098649ee34eb36d88f657 to make sure this doesn't happen again

**Comment by VitalyArtemiev** [comment] 2022-09-21 19:05
Is there a way for me to test this?

**Comment by Rokvach** [comment] 2022-09-28 10:02
Tested, working correctly. Closing.

**Closed by Rokvach** 2022-09-28 10:02 UTC
Labels: Bug, Code, Unstable

**Comment by wjamesbonner** [comment] 2022-12-10 23:21
Hello,
My campaign group is experiencing the same issue. A long-running campaign, and after the update, no more quests are available at any of the stations. Would it be possible to look at our save and see if it can be fixed the same way @VitalyArtemiev save was?
[Multiplayer.zip](https://github.com/Regalis11/Barotrauma/files/10201159/Multiplayer.zip)
Thanks for your time and great game!
