### ISSUE TITLE
Presonal status monitor CTD's on activation while EVA

### ISSUE THREAD

**Issue by DarthPointer** [Regalis11/Barotrauma#7406] opened 2021-11-19 22:13 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
A CTD happens on personal boat status monitor activation while performing EVA in docked scene.

**Steps To Reproduce**
0. Ocurred while docked at a station.
1. Get a personal status monitor device.
2. Leave your sub for an EVA.
3. Put the monitor in your hand - that instantly triggered the CTD.

**Version**
Game version 0.15.13.0 (ReleaseWindows, branch release, revision 4e66dd7b5d)
Operating system: Microsoft Windows NT 10.0.19043.0 64 bit

**Additional information**
The previous scene ended with docking, having a defeated pirate Humpback attached to us. My character was in the pirate boat that disappeared after docking. I'm aware of captured boats disappearing, but it might has played its role in further CTD in docked scene.

[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/7573201/crashreport.2.log)

**Comment by Regalis11** [comment] 2021-11-21 13:09
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7279

**Closed by Regalis11** 2021-11-21 13:09 UTC
