### ISSUE TITLE
[Dev]Afflictions inside afflictions causing issues with creatures.

### ISSUE THREAD

**Issue by ChikoEduardo** [Regalis11/Barotrauma#1309] opened 2019-03-19 15:53 UTC
I've noticed setting up afflictions like this turn creatures into murder machines. The best example in vanilla of an affliction that causes this "berzerk" behaviour is radiotoxin, since it also causes burn damage. Here are example videos:

https://cdn.discordapp.com/attachments/405014318892056577/557582414898003968/D5OW0dtkd1.mp4
https://cdn.discordapp.com/attachments/405014318892056577/557591688751742977/CmFTjIoyyK.mp4

This issue is kinda nice in shark-like creatures so maybe you guys could add a way to enable/disable this being regarded as attack damage in afflictions.

**Comment by Regalis11** [comment] 2019-03-19 16:06
I think this is a duplicate of #891

**Closed by Regalis11** 2019-03-19 16:06 UTC

**Comment by itchyOwl** [comment] 2019-03-20 11:55
Fixed in the dev.
