### ISSUE TITLE
Network errors cause clients to desync from their characters

### ISSUE THREAD

**Issue by CLASSlCS** [Regalis11/Barotrauma#8114] opened 2022-01-28 06:08 UTC
- [+] I have searched the issue tracker to check if the issue has already been reported.

_**Description**_
If you experience a disconnect from the host whilest loading into a mission/station/area/etc... upon rejoining your client can become desynced from your character, you are unable to control your character and are stuck in spectator mode. You cannot/will not respawn, you cannot be respawned. Note that it **MUST** be the **NEXT** mission, you won't experience this issue with the first mission you load into.

 Re-joining, reloading, etc... does not fix this issue. 

This issue can be fixed in-game if the host knows to run the command [setclientcharacter "client name" "character name"]

This issue only seems to occur when the host has a poor internet connection (cheap wifi or such) and isn't possible to reproduce with good/high speed connections or locally over local connections.

It's like your client is set in control of no character. Or maybe your character is set to be controlled by no client, or a client that isn't connected, or something broken, idk tbh it's all a bit beyond me.
_**Steps To Reproduce**_
1. Play in a online server where the host doesn't have great internet service
2. Receive disconnect whilest loading into **next** mission. (as shown below)
![20220128003641_1](https://user-images.githubusercontent.com/83607673/151494910-e2d7521a-8e7c-4376-94b5-997144c9b5d1.jpg)
3. Upon being booted back to lobby it will often be a broken lobby that shows no client names of those connected, and has no options to click or anything. (as shown below)
![97120678-35c48b00-16ef-11eb-8874-4300382e89c4](https://user-images.githubusercontent.com/83607673/151499687-4b01432b-c164-447a-8a4c-1cf2731cfb54.png)
4. Disconnect from the server. (or close and restart barotrauma, either will reproduce this if it's happening)
5. Rejoin the lobby and join back into the game
![20220128003708_1](https://user-images.githubusercontent.com/83607673/151495177-58525c21-0f5d-4b7d-a482-74de38123668.jpg)
6. Now normally what should happen is you regain control of your character, or spectate until you respawn (depending if your character is alive in-game or not)
7. However, what actually happens when you experience this bug is, despite your character being alive you do not regain control of them, you also do not respawn as them because your client is desync from your character. (note in the picture that it says I'm playing as spectator despite my character being alive, on the bottom left of screen, and it is also not respawning me)
![20220128003837_1](https://user-images.githubusercontent.com/83607673/151495427-e38158d5-b36a-49a6-9f29-4581ccf5d291.jpg)
8. You are now stuck like this until the host uses [setclientcharacter "client name" "character name"] or they shut down/restart the server.
_**Version**_
Barotrauma v0.15.23.0 ReleaseWindows
No mods, purely vanilla, have also verified game files successfully.

**Additional information**
This bug only seems to occur to specific hosts.
These hosts seem to usually have low-ish quality internet service that causes these network bugs.
For most hosts this bug doesn't occur.
However, when you find a host in which this bug does occur it occurs pretty much every round.
When this bug does occur it also usually occurs to seemingly every, or atleast almost every, client in the game.
This bug has been present in previous game versions, and is likely related to other bugs (I remember a similar one where clients were being set in control of incorrect characters, or other reports of disconnects causing broken lobbies, etc...)

**Comment by CLASSlCS** [comment] 2022-01-28 06:18
If any further information that I have not thought to provide may be helpful, please ask.

**Comment by Ek-Videogames** [comment] 2022-04-20 21:03
Confirming that at least 2 of the issues still happen on current public build:
 - losing control of your character after reconnecting
 - blank 'corrupted' lobby screen after reconnecting

**Comment by CLASSlCS** [comment] 2022-04-22 20:05
A bit more info I've come across since.

It seems it's not necessarily directly tied to network performance. I've noticed that savefile size also seems to play a role.
Both poor network performance and large savefile sizes seem to increase the chances of theses bugs occurring.

Speculation:
It seems to me like there's some sort of "handshake" between host and client when loading a new mission, where the host side has to find the client data of what character they control and what that character has and send it to the client (or something to that general effect). If this handshake can't be completed in time (likely due to filesizes or network performance) it causes an error that disconnects the client and leaves the character in-game without it being connected to a client. It seems the timeframe for the completion of this handshake is dependent on the loading of the level, which is why it disconnects at the time that the "generation an outpost for start of level" text appears in the F3 console.

**Comment by NilanthAnimosus** [comment] 2022-07-21 14:23
Tested against 0.19.0.0 - The issue appears to still exist. I can't reproduce it super reliably either.

what I have found though (which helps a lot to perhaps reproduce this) is to:

play on a campaign or mission or such using a dedicated server in debug mode.
join as a client and spawn in a campaign round
behind a level transition (To outpost in my case but any will do)
pause the server (I used the start of the servers GameServer.cs Update function)
wait long enough until the client gets a disconnecting timeout warning (Enough to force them to join the lobby)
Unpause the server so you don't completely lose the client, and they "Rejoin" after the server finishes loading.
Join via spectating from the lobby.

the character in the code appears to have character.ClientDisconnected set to false, which skips the code to give characters their control back.

![image](https://user-images.githubusercontent.com/29177976/180237736-bc76e3b3-89f2-4ddc-aa1e-06c5a8a02ee7.png)

I believe what may be occuring here is the server doesn't set the character as disconnected when they rejoin during/after the immediate point of level loading, they do have a filled in character.OwnerClientEndPoint so that was set correctly but control was never initially given somehow (Probably disconnecting before/during that but in a way that doesn't set the character to ClientDisconnected?)

**Comment by NilanthAnimosus** [comment] 2022-07-21 14:36
Ok so pausing the server at the start of gameserver.cs's update function so you see this on campaign (Adding a breakpoint the moment you see "Starting a round" so it pauses after loading at this point):

![image](https://user-images.githubusercontent.com/29177976/180240440-dfa6cf28-d96a-4f03-9bd9-ecaa71ab7c13.png)

Is an extremely reliable way to reproduce this (And waiting until you see the box on failing to connect for the clients loading screen, clicking "Close" on the objective area helps show this earlier it seems)

**Comment by NilanthAnimosus** [comment] 2022-09-06 10:47
Tested against networking-fixes-critical commit https://github.com/Regalis11/Barotrauma-development/commit/c8ecff6a236981bb5022e26e7dc86060b4288b02 (Which does contain related fixes), no issues found, closing.

Notes:

After all the other fixes in different areas related to active mods when rejoining/reconnecting as well as the above fixes, and being unable to replicate this any further, I believe most causes have likely been eliminated now and this issue is safe to close and if encountered again in unstable 0.19.13.0 onwards be reopened then.

**Closed by NilanthAnimosus** 2022-09-06 10:47 UTC
Labels: Bug, Code, Networking, Severe
