### ISSUE TITLE
Eventmanager: 'Distance' events don't spawn & Time events only spawn behind the sub.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#3447] opened 2020-07-31 17:47 UTC
**[v0.10.4-v0.10.5]**

### When traveling through a map in campaign, it seems 'Distance Traveled' events do not appear anywhere on the map once their distance is reached.
Using debug-draw : event manager info, I see events matching those in the code for events which trigger after completing a certain % distance on the map, "after 30% travelled". On reaching the point where this condition is satisfied, the event dissapears from the list. However disabling lighting and freecamming around the map shows no new events have spawned anywhere.
It seems events that are triggered by distance just don't appear to work.

### Time-events only spawning enemies behind the submarine.
So far I have only made it up to 30-40 level-difficulty since I have started these observations.
Using debug-draw this time to see when the time events will trigger I can see with freecam _(and the sub's own sonar)_
that groups of enemies are only appearing on the 'path nodes' behind the submarine rather than 50/50 forwards backwards.
I am not sure how this could be a fluke, as it is incredibly consistent.

**Comment by Regalis11** [comment] 2020-08-19 08:02
Fixed the 1st issue in https://github.com/Regalis11/Barotrauma-development/commit/cbde1cb27920f8256aeb4aef52126938b23f73ea. The problem was that nested event sets all triggered a separate event cooldown, causing there to be a significant delay between the parent event set triggering and the child events actually spawning the monsters.

2nd issue fixed in https://github.com/Regalis11/Barotrauma-development/commit/4f9da1d4a9c8ae8f70f34894052fbc1e11bd3469

**Comment by Rokvach** [comment] 2020-09-07 08:55
Confirmed working, closing.

**Closed by Rokvach** 2020-09-07 08:55 UTC
Labels: Bug, Code
