### ISSUE TITLE
Searchlight -  wrong direction of light

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#9356] opened 2022-06-15 20:58 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?
After upgrading from version 0.17.16.0 to version 0.18.11.0, the bottom `searchlights` shine in the wrong direction.

Inverted searchlights (for example 180 degrees) illuminate in the opposite direction.
https://user-images.githubusercontent.com/93348499/173927239-ec38c095-4038-4a2d-8596-a64611ea8548.mp4

### Reproduction steps

1. Sub editor
2. Create `searchlight`
3. Set rotation 180

https://user-images.githubusercontent.com/93348499/173927821-755724e8-3c72-4685-b021-8d6fade17f1e.mp4

### Bug prevalence

Happens every time I play

### Version

0.18.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-06-29 14:54
I'm afraid I could not reproduce this with the provided steps: setting the rotation to 180 seems to flip the light correctly.

**Comment by MaaiG** [comment] 2022-06-30 09:33
@Regalis11 
Now I didn’t get it either, but if you play with the mirror-Y and the 180 angle, it happens sometimes.
This is the sub file in which the lighting in the submarine editor is wrong: 
[__Test light.zip](https://github.com/Regalis11/Barotrauma/files/9018359/__Test.light.zip)

https://user-images.githubusercontent.com/93348499/176643709-35b58eea-b61b-4689-ad91-7962425f3b19.mp4

In any case, if you try to flip the searchlight with the help of the mirror-Y, there are strange things in its position relative to its body:

https://user-images.githubusercontent.com/93348499/176641832-befb6597-cb1d-4d22-89f6-3e9099c4f723.mp4

It turns out that to flip the searchlight correctly requires a certain sequence of actions.
The mirror-Y button does not work quite as expected.
- Change angle settings to 180 - Flips the body
- The mirror-Y button does not turn the body but changes the angle 180!

Apparently, sometimes the combination of these things leads to what is shown in the __Test.light.zip file.

**Comment by MaaiG** [comment] 2022-06-30 12:57
Ver 0.18.12.0
And yet every time you restart the submarine file in the editor, the light goes in the wrong direction!
1. Create `searchlight`
2. Rotate 180 degries
3. Save sub file
4. Reload your sub file
5. Enable lights
6. The light goes in the wrong direction

https://user-images.githubusercontent.com/93348499/176682476-bc88d7ae-5719-4933-b06f-38f8bfff8923.mp4

**Comment by NilanthAnimosus** [comment] 2022-07-22 14:26
Tested in 0.19.0.0

Changing the angle or rotation seems to work fine.

However, when I do any mirroring, the light will not immediately seem to update, facing usually the wrong direction. Looks sort of like it lags behind, but mirror X doesn't even seem to update it at all.

Uploading 2022-07-22_15-24-27.mp4…

**Comment by Regalis11** [comment] 2022-08-25 15:11
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5bb0a28799cbe034d99ee934e343df22d06f3562

**Closed** 2022-09-05 17:55 UTC
Labels: Bug, Code, Low prio, Unstable
