### ISSUE TITLE
Unstable sudden crash

### ISSUE THREAD

**Issue by TMWReborn** [Regalis11/Barotrauma#10167] opened 2022-10-27 17:55 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

started single player compaign on Barsuk, the spinelings attacked the ship i fired two lasergun shots and the game crashed. i don't know exactly why that happen, but il give the crash report bellow 

### Reproduction steps

no idea

### Bug prevalence

Just once

### Version

Other

### -

Public unstable

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 10/27/2022 20:41:42)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


CF121C94D13F01CFA90FC9F4FB013714


Game version 0.20.0.0 (UnstableWindows, branch dev, revision 69b079928e)
Graphics mode: 1280x800 (Windowed)
VSync OFF
Language: Russian
Selected content packages: Vanilla, 1)  BUHANKA (the loaf), 1) HammerHead, 1) KRAMKA, Unnamed, 2) Sharkon, Unnamed, 1) KAZAN, 1) Печка, KRUZHKA (the mug)
Level seed: Sarpedon LineaShinkonai
Loaded submarine: Barsuk (405497E77935CEA32ED77A5F1688939B)
Selected screen: Barotrauma.GameScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce GT 740
    Display mode: {Width:1280 Height:1024 Format:Color AspectRatio:1.25}
    GPU status: Normal


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void UpdateAttack(Single)
Stack trace: 
   at Barotrauma.EnemyAIController.UpdateAttack(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\EnemyAIController.cs:line 1890
   at Barotrauma.EnemyAIController.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\EnemyAIController.cs:line 441
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2917
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 192
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 859
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58


Last debug messages:
[10/27/2022 20:33:00] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
[10/27/2022 20:32:54] Generating an outpost for the end of the level... (Location: Shinkonai, level type: LocationConnection)
[10/27/2022 20:32:53] Level identifier: coldcavernsadvanced
[10/27/2022 20:32:42] Transitioning to Sarpedon LineaShinkonai (current location: Sarpedon Linea, selected location: Shinkonai, leaving sub: Barsuk, at start: False, at end: True, transition type: ProgressToNextEmptyLocation)
[10/27/2022 20:15:30] Generating an outpost for the start of the level... (Location: Аванпост Embla, level type: LocationConnection)
[10/27/2022 20:15:30] Level identifier: coldcavernsbasic
[10/27/2022 20:15:16] Transitioning to EmblaSarpedon Linea (current location: Аванпост Embla, selected location: Sarpedon Linea, leaving sub: Barsuk, at start: True, at end: False, transition type: LeaveLocation)
[10/27/2022 20:12:10] Unlocked mission "Пассажирские перевозки" in the connection from "Аванпост Embla" to "Аванпост Agenor Linea".
[10/27/2022 20:12:07] Unlocked mission "Уничтожение роя" in the connection from "Аванпост Embla" to "Balagtan".
[10/27/2022 20:12:05] Unlocked mission "Убийство большого ползуна" in the connection from "Аванпост Embla" to "Sarpedon Linea".
[10/27/2022 20:11:23] Generating an outpost for the start of the level... (Location: Аванпост Embla, level type: Outpost)
[10/27/2022 20:11:23] Level identifier: outpostlevel
[10/27/2022 20:11:11] Transitioning to Embla (current location: Аванпост Agenor Linea, selected location: Аванпост Embla, leaving sub: Barsuk, at start: False, at end: True, transition type: ProgressToNextLocation)
[10/27/2022 20:02:33] Generating an outpost for the end of the level... (Location: Аванпост Embla, level type: LocationConnection)
[10/27/2022 20:02:32] Generating an outpost for the start of the level... (Location: Аванпост Agenor Linea, level type: LocationConnection)
[10/27/2022 20:02:31] Level identifier: coldcavernsbasic
[10/27/2022 20:02:18] Transitioning to Agenor LineaEmbla (current location: Аванпост Agenor Linea, selected location: Аванпост Embla, leaving sub: Barsuk, at start: True, at end: False, transition type: LeaveLocation)
[10/27/2022 19:59:32] Unlocked mission "Не кантовать" in the connection from "Аванпост Agenor Linea" to "Аванпост Embla".
[10/27/2022 19:59:30] Unlocked mission "Пассажирские перевозки" in the connection from "Аванпост Agenor Linea" to "Аванпост Embla".
[10/27/2022 19:59:27] Unlocked mission "Уничтожение молотоглавов" in the connection from "Аванпост Agenor Linea" to "Аванпост Embla".
[10/27/2022 19:48:50] Generating an outpost for the start of the level... (Location: Аванпост Agenor Linea, level type: Outpost)
[10/27/2022 19:48:50] Level identifier: outpostlevel
[10/27/2022 19:46:04] Attempting to open ALC device "OpenAL Soft on Наушники (Realtek High Definition Audio)"
[10/27/2022 19:46:01] Logged in as TMWReborn (SteamID STEAM_1:1:448112132)
```

**Comment by RodimusPrime12** [comment] 2022-10-28 02:51
I ran into the same exact issue. I was 35min into a run when I got the error. Lost all progress and had to restart. Then I kept running into the issue again.

**Comment by 3e849f2e5c** [comment] 2022-10-28 04:01
Closing as duplicate of #10170 (even tho this was submitted first)

**Closed by 3e849f2e5c** 2022-10-28 04:01 UTC
