### ISSUE TITLE
"weird bug where i cant open any secure cabinets in game with my captain ID card"

### ISSUE THREAD

**Issue by Fachoj** [Regalis11/Barotrauma#13037] opened 2023-11-15 22:02 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Discord **stimshots:**
_"im having a weird bug where i cant open any secure cabinets in game with my captain ID card 
but when i open the ship in the sub editor i can open everything just fine
it seems i can open them fine on a new save too"_

### Reproduction steps

Discord **drbruhman:**
_"This means submarine spawnpoints have custom tags that define your id tags on respawn, and if you previously respawn on different sub or shuttle you don't save or inherit these id tags. 
This why sub-builders should choose jobid:(job indentifier) that you have in id by default. There also nameid:(character name), and if you making sub, you also can give access to specific crewmembers by name."_

So make id_[job indentifier] equal to jobid:[job indentifier] and works the same. proper fix looking on that fact this problem is applies on all subs.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### -

any below

### Which operating system did you encounter this bug on?

Windows

**Comment by Fachoj** [comment] 2023-11-15 22:08
and maybe there problem if enemy sub have same id required?

**Comment by BlackMoons** [comment] 2023-11-16 03:32
Maybe if your ID has the proper nameID as its owner, its tags should always be updated to the spawn point it spawns at, at the start of a round?

**Comment by Fachoj** [comment] 2023-11-16 07:58
uhh vanilla(and mostly all modded) respawn shuttles usualy dont have job specific spawnpoints with tags.
for example new security joins to team mid round on a shuttle, he walks into a arsenal and cant open safe locker.

**Comment by Regalis11** [comment] 2023-11-16 11:52
Most likely related to or a duplicate of https://github.com/Regalis11/Barotrauma/issues/12899

**Comment by BlackMoons** [comment] 2023-11-16 12:31
> > Maybe if your ID has the same nameID as its current owner, its tags should always be updated to the spawn point it spawns at, at the start of a round?
> 
> uhh vanilla(and mostly all modded) respawn shuttles usualy dont have job specific spawnpoints with tags. for example new security joins to team mid round on a shuttle, he walks into a arsenal and cant open safe locker.

Yea, you'd have to copy the tags from the spawnpoint they would use if they spawned on round start, not the shuttles spawnpoint.

**Comment by Regalis11** [comment] 2023-11-16 13:13
> Yea, you'd have to copy the tags from the spawnpoint they would use if they spawned on round start, not the shuttles spawnpoint.

This is how it works, the character gets the tags from the spawnpoint in the shuttle and the spawnpoint they would've spawned at in the main sub. Seems like something's bugged though, since that doesn't seem to be working correctly.

**Comment by Jasontti** [comment] 2023-11-22 09:39
Tested in: https://github.com/Regalis11/Barotrauma-development/commit/28d2361bf48d65da237d3a65b0a1e007007eb37e

Tested in MP.
Respawning now correctly assigns proper ID card.

No issues found
Closing ticket

**Closed by Jasontti** 2023-11-22 09:39 UTC
Labels: Bug, Code
