### ISSUE TITLE
Make engine aitarget range depend on it's settings

### ISSUE THREAD

**Issue by Waagher** [Regalis11/Barotrauma#2132] opened 2020-02-03 23:20 UTC
...Be that power used, max engine power or the current navigational terminal velocity input. Point being, the current fixed sound range of 10k, that appears as soon as the engine's velocity setting is different from 0, makes the passive and directional sonar play almost entirely useless. As of now the creatures will almost always immediately know where you are once you start moving, rendering all attempts at careful navigation pointless.

**Comment by Regalis11** [comment] 2020-02-04 09:22
Actually the sound range of the engine should be directly proportional to the velocity setting. Here's how it's calculated in Engine.cs:

`aiTarget.SoundRange = MathHelper.Lerp(aiTarget.MinSoundRange, aiTarget.MaxSoundRange, currForce.Length() / maxForce);`

It could be there's something wrong with the logic though, we need to give it a test and make sure it's working as intended.

**Comment by Kaillera** [comment] 2020-02-04 09:37
I've tested setting the engine thrust to 10% with debugdraw and toggleaotargets, and the circle that shows up for the engine is as large as the reactor if not bigger.

**Comment by NilanthAnimosus** [comment] 2020-02-04 15:47
correct me if I am wrong but - does .Length() actually get the value of the force or the length of the value in digits/string size?

**Comment by Regalis11** [comment] 2020-02-04 17:58
Length is just an instance method of the Vector2 class which returns the length of the vector, so I don't think that is the problem here.

**Comment by Regalis11** [comment] 2020-02-05 18:05
Found out what was causing this now: the sound range was actually 20x bigger than it should've been due to some ad-hoc multiplications in the force calculations that weren't taken into account in the sound range calculation. 

Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/4856a248b2510897e7ed3cc8febacdb48a26824d

**Comment by Rokvach** [comment] 2020-02-05 20:13
Tested, working correctly. Closing.

**Comment by itchyOwl** [comment] 2020-02-12 09:18
Doesn't work well now. Needs re-adjusting.

**Comment by Rokvach** [comment] 2020-02-12 20:22
Couldn't spot any issues on the creature behavior anymore, so seems to be working correctly. Closing.

**Closed by Rokvach** 2020-02-12 20:22 UTC
Labels: Code
