### ISSUE TITLE
Bot fill mode not working (unclear what fill mode actually does)

### ISSUE THREAD

**Issue by gerakis** [Regalis11/Barotrauma#9853] opened 2022-09-10 02:14 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When playing with bot fill mode enabled, new bots are not added beyond the very first station when the game is created. I would expect to see bots added as needed to make up the roster as players leave, and disappear as human players join, but this is not what happens. Not even on switching maps. I seem to be stuck with 0 bots forever. 

Its possible I'm misunderstanding what fill mode actually does. If there is a tooltip somewhere explaining it I'm not seeing it. If this is normal behavior please disregard this report.

### Reproduction steps

Start a multiplayer campaign with bot spawn mode set to normal and bot count set to 0
Later, use the F3 console to set bot spawn mode to fill and bot count to 6
Switch maps. Dock at a station, leave a station, whatever. It doesn't seem to matter.
You have zero bots forever unless you buy them.

### Bug prevalence

Happens every time I play

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by AndyPuettmann** [comment] 2022-09-10 10:35
Hello there,
yes, I guess there is a misunderstanding on how the bot fill mode works.

Its mostly useful in "mission" mode or other modes that have non-persistent round data.
So if you want to do a mission with 6 players (bots set to 6 and fill) and only 3 humans are there, the start of the mission would add 3 bots.

For campaigns, it works differently.
The setting is actually only processed when creating the save game.
On every subsequent load of the save game, the data from the savegame is taken.
Essentially, if the server would 'refill' the bots after every campaign hop, it would be adding free crew (worth 2000-4000mk per bot) on every station.

**Comment by gerakis** [comment] 2022-09-10 16:11
Thats true, but you get free crew anyway when people join the server. Also if you lost one on joining and gained one on leaving it should mostly balance out.

Trying to get a game going with only yourself is not ideal. Nobody wants to join an empty server and a crew of 1 cannot really run a submarine. Hiring bots with marks only to have them vanish as soon as the round fills up is a huge waste of money. If they dont vanish then players complain that bots are doing all the work. I would think my version of fill would be better than the current version.

**Comment by NilanthAnimosus** [comment] 2022-09-12 08:57
Bot fill mode was never intended for campaigns, their also not persistent if I recall.

I wouldn't even consider it balanced if you were getting free AI every round and even weirder to be removing them (purchased or not) as players joined the game.

I can see why this would be wanted, but don't think it should be a feature, either way this is more feature request and design than a bug as I think the feature is working as intended to give some bots at the start of the campaign for free. getting additional AI's should cost marks, and once their dead - their gone unlike players.

I don't think it'd be any more fun for players to have a cost or require a character purchased for them to play, but making the AI and their equipment free and continually refilling the server seems just as odd to me personally.

**Comment by Regalis11** [comment] 2022-09-12 10:23
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/9f34d880a1b09b017bdc088d53574a573cb7bda0

**Comment by NilanthAnimosus** [comment] 2022-10-23 21:17
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/9f34d880a1b09b017bdc088d53574a573cb7bda0.

the tooltips do not show on the arrows for selection Which I think is fine even though it is possible to never hover over the box, its still very likely to be noticed.

I feel the text for the campaign mode note could use an extra new line between it too to be noticed faster without reading the whole block.

![image](https://user-images.githubusercontent.com/29177976/197418663-6cb4841f-1282-404a-8596-5b84e1e57e38.png)

otherwise there is no real issues with this and it is pretty much how the spawn mode works by description too.

**Comment by Regalis11** [comment] 2022-10-24 10:01
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/1edeec21a389f9a20de9bae2ac5163e5c3b01d69

**Comment by NilanthAnimosus** [comment] 2022-10-24 12:30
Tested against botspawnmode-tooltips commit https://github.com/Regalis11/Barotrauma-development/commit/979088603b8d859d1807117251abcb4e0e47e7fb, no issues found, ready for merging.

**Closed** 2022-10-24 14:05 UTC
Labels: Feature request, Design
