### ISSUE TITLE
Tiny gap of high pressure with vertical docking port and dynamic hulls

### ISSUE THREAD

**Issue by Krisscut** [Regalis11/Barotrauma#5281] opened 2021-03-21 16:04 UTC
- [Yes ] I have searched the issue tracker to check if the issue has already been reported.

**Description**

Similar problem as this one https://github.com/Regalis11/Barotrauma/issues/5009, but this issue focus on the fact that the hull is generated but a small gap still remains and cause the character to ragdoll when going through the high pressure area.
It seems to also prevent the bots from going there.

**Steps To Reproduce**
Load the shared submarine, on the right side you can access the shuttle in its hangar bay.
When going through the docking port, the character often gets ragdolled. (not always).

**Version**
Windows, stable version . V0.12.0.3 

**Additional information**

Tiny gap visible here on the right side (left side of the hull seems fine):
![image](https://user-images.githubusercontent.com/8125922/111911756-1e53b900-8a67-11eb-8cc6-a763eab6e21f.png)

Hull on the shuttle side standalone.
![image](https://user-images.githubusercontent.com/8125922/111911777-2ca1d500-8a67-11eb-90e9-8748e70bd73d.png)

**Comment by Krisscut** [comment] 2021-03-21 16:06
Main submarine with shuttle attached, and shuttle (Hira) in standalone version.

[Submarines.zip](https://github.com/Regalis11/Barotrauma/files/6177826/Submarines.zip)

**Comment by Regalis11** [comment] 2021-03-22 16:37
Could no longer reproduce this in the latest unstable version, I think fixing https://github.com/Regalis11/Barotrauma/issues/5026 took care of this one as well.

**Comment by Rokvach** [comment] 2021-03-23 12:30
Tested, no issues. Closing.

**Comment by Krisscut** [comment] 2021-03-24 17:56
I tried on the last unstable 0.1300.0.2 and it still happen:
https://youtu.be/E6-AeEwO_YQ

**Comment by Krisscut** [comment] 2021-04-22 18:10
Hi !

Reproduced on last stable that released today, shouldn't we open the ticket again since it is not fixed ?

**Comment by Calyxman** [comment] 2021-04-26 11:18
I've encountered this many times.
Vertical and horizontal docking hatches do this.
They temporarily... teleport me out of the sub, for a split second, give me the water particles, along with High pressure, but then it fixes itself.

**Comment by Krisscut** [comment] 2021-04-26 11:33
Yes, to be honest it wouldn't be such an issue if the bots were able to go through.

In this case they refuse to follow you if you go on the other side of the docking port, so for maintenance of a shuttle etc it can be inconvenient.

**Comment by Regalis11** [comment] 2021-05-26 12:20
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/96a2a590c3992e311eb4a165495943deb0d4aa28.

Note for QA: I think it'd be good to test several subs and see if the hulls still generate correctly everywhere, particularly in custom subs with more exotic docking port configurations (same for #5009 which could be tested simultaneously with this).

**Comment by Rokvach** [comment] 2021-05-27 07:01
I went through around 10 custom subs with attached linked subs and didn't spot any issues. Seems to be working correctly, closing.

**Closed by Rokvach** 2021-05-27 07:01 UTC
Labels: Bug, Code
