### ISSUE TITLE
Layering issue in an outpost

### ISSUE THREAD

**Issue by TheActualRealBob** [Regalis11/Barotrauma#11895] opened 2023-04-23 08:25 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The Spraypaint and the Pictures/files on the wall in Topol city are experiencing a layering issue, Making their textures constantly go over and then under the other.

This is at the top of the stairs leading to the office of the City leader person

### Reproduction steps

1 : Go to Topol city.
2 : Walk up the Staircase on the right side.
3 : Repeat step 2 on the second staircase.
4 : Now walk up the stairs to the City lead's office area, And it should be seen at the spraypaint area.

### Bug prevalence

Just once

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-04-23 14:54
Thank you for the report!

I'm afraid there might not be enough information here for us to diagnose the issue. The outposts are randomly generated, so the name of the outpost doesn't help us finding where the issue is. Could you for example post a screenshot of the spot where this issue happens? Thanks and sorry for the inconvenience!

**Comment by HawkinsThe71st** [comment] 2023-04-23 18:04
Might be referring to this section in adminmodule_01_colony? The fliers and the poster both share the same sprite depth as the graffiti:
![image](https://user-images.githubusercontent.com/115734437/233856888-7ed0cad5-000f-4383-821b-5e55488f310a.png)
![image](https://user-images.githubusercontent.com/115734437/233856909-27a81150-be37-4af3-a4af-440c0ae8c2b1.png)
![image](https://user-images.githubusercontent.com/115734437/233856936-b5370a59-cd03-4f14-8863-c11b80fa50d8.png)

**Comment by Regalis11** [comment] 2023-04-24 14:02
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/35fedab9001eb5ac495d83d8b9d251b12e701b7f

**Comment by Rokvach** [comment] 2023-06-01 08:15
Tested, no issues. Closing.

**Closed by Rokvach** 2023-06-01 08:15 UTC
Labels: Bug, Design
