### ISSUE TITLE
Game Freeze

### ISSUE THREAD

**Issue by thedogs1** [Regalis11/Barotrauma#9029] opened 2022-05-01 02:51 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**

Exception: readStream was disconnected unexpectedly (System.Exception)
Target site: Void CheckPipeConnected(System.String, System.IO.Pipes.AnonymousPipeServerStream)
Stack trace: 
   at Barotrauma.Networking.ChildServerRelay.CheckPipeConnected(String name, AnonymousPipeServerStream pipe) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 138
   at Barotrauma.Networking.ChildServerRelay.UpdateRead() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 168
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()

Last debug messages:
[4/23/2022 10:14:16 PM] Lobby created!
[4/23/2022 10:13:29 PM] Attempting to open ALC device "OpenAL Soft on Headphones (3- Arctis 7 Game)" 
I keep getting this error when I try to join/start games
Uninstalling, verifying, does nothing and I don't know how to fix this issue

I cannot play this game anymore!! And haven't been able to for weeks

**Comment by Regalis11** [comment] 2022-05-02 07:43
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7985

**Closed by Regalis11** 2022-05-02 07:43 UTC

**Comment by thedogs1** [comment] 2022-05-08 23:31
This is not a duplicate of that above error as I can't even launch a single player game or multiplayer game. @Regalis11
