### ISSUE TITLE
Game Crash while in editor, game no longer starts.

### ISSUE THREAD

**Issue by Zombyourfaceoff** [Regalis11/Barotrauma#2221] opened 2020-02-08 18:03 UTC
Here is a bug where the game crashed while in editor and the game is now un-openable.
In order to close the game I have to close steam.

In addition, ( downloading stable and re downloading unstable does not fix the issue.)

Barotrauma Client crash report (generated on 2/8/2020 10:00:01 AM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

DF00E6BD46F56CD31DA53A25A96D2839

Game version 0.9.704.0 (UnstableWindows, branch dev, revision 99feac023)
Graphics mode: 2560x1080 (BorderlessWindowed)
VSync ON
Selected content packages: Vanilla 0.9, 3_Tigerfish_UCN, EK Coseus Mk-II, GreatLighting, LittleThunder, Nemo's Nautilus, Phryne, Serenity, SI Cobalt, EK_Scrapper_Mk-I, Enterprise B, Leviathan, Mining Station A, The Patchwork Minelayer, TRY3DENT III, TRYD3NT III
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 6.2.9200.0 64 bit
    GPU name: NVIDIA TITAN Xp
    Display mode: {Width:2560 Height:1080 Format:Color AspectRatio:2.3703704}
    GPU status: Normal

Exception: Collection was modified; enumeration operation may not execute.
Target site: Void ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
Stack trace: 
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Barotrauma.TextManager.LoadTextPacks(IEnumerable`1 selectedContentPackages) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\TextManager.cs:line 91
   at Barotrauma.GameSettings.LoadContentPackages(IEnumerable`1 contentPackagePaths) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\GameSettings.cs:line 1106
   at Barotrauma.GameSettings.ReloadContentPackages() in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\GameSettings.cs:line 1065
   at Barotrauma.GameMain.<>c.<Load>b__94_0() in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 421
   at Barotrauma.CrossThread.ProcessTasks() in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Utils\CrossThread.cs:line 38
   at Barotrauma.GameMain.Update(GameTime gameTime) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 662
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 654
   at Microsoft.Xna.Framework.Game.Tick() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 41

Last debug messages:
[2/8/2020 10:00:01 AM] Could not install 'TRYD3NT III' because there is already a mod installed at 'Mods\TRYD3NT III'.
[2/8/2020 10:00:01 AM] Content package load order: Vanilla 0.9  |  3_Tigerfish_UCN  |  EK Coseus Mk-II  |  GreatLighting  |  LittleThunder  |  Nemo's Nautilus  |  Phryne  |  Serenity  |  SI Cobalt  |  EK_Scrapper_Mk-I  |  Enterprise B  |  Leviathan  |  Mining Station A  |  The Patchwork Minelayer  |  TRY3DENT III  |  TRYD3NT III
[2/8/2020 10:00:01 AM] Content package load order: Vanilla 0.9  |  3_Tigerfish_UCN  |  EK Coseus Mk-II  |  GreatLighting  |  LittleThunder  |  Nemo's Nautilus  |  Phryne  |  Serenity  |  SI Cobalt  |  EK_Scrapper_Mk-I  |  Enterprise B  |  Leviathan  |  Mining Station A  |  The Patchwork Minelayer  |  TRY3DENT III  |  TRYD3NT III
[2/8/2020 9:59:59 AM] Attempting to open ALC device "OpenAL Soft"
[2/8/2020 9:59:59 AM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[2/8/2020 9:59:59 AM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[2/8/2020 9:59:58 AM] Logged in as Zomb (SteamID STEAM_1:1:77334902)

**Comment by Zombyourfaceoff** [comment] 2020-02-08 18:05
Here is another log to show the time/date of back to back errors.


Barotrauma Client crash report (generated on 2/8/2020 10:05:05 AM)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


DF00E6BD46F56CD31DA53A25A96D2839


Game version 0.9.704.0 (UnstableWindows, branch dev, revision 99feac023)
Graphics mode: 2560x1080 (BorderlessWindowed)
VSync ON
Selected content packages: Vanilla 0.9, 3_Tigerfish_UCN, EK Coseus Mk-II, GreatLighting, LittleThunder, Nemo's Nautilus, Phryne, Serenity, SI Cobalt, EK_Scrapper_Mk-I, Enterprise B, Leviathan, Mining Station A, The Patchwork Minelayer, TRY3DENT III, TRYD3NT III
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 6.2.9200.0 64 bit
    GPU name: NVIDIA TITAN Xp
    Display mode: {Width:2560 Height:1080 Format:Color AspectRatio:2.3703704}
    GPU status: Normal


Exception: Collection was modified; enumeration operation may not execute.
Target site: Void ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
Stack trace: 
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Barotrauma.TextManager.LoadTextPacks(IEnumerable`1 selectedContentPackages) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\TextManager.cs:line 91
   at Barotrauma.GameSettings.LoadContentPackages(IEnumerable`1 contentPackagePaths) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\GameSettings.cs:line 1106
   at Barotrauma.GameSettings.ReloadContentPackages() in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\GameSettings.cs:line 1065
   at Barotrauma.GameMain.<>c.<Load>b__94_0() in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 421
   at Barotrauma.CrossThread.ProcessTasks() in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Utils\CrossThread.cs:line 38
   at Barotrauma.GameMain.Update(GameTime gameTime) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 662
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 654
   at Microsoft.Xna.Framework.Game.Tick() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 41


Last debug messages:
[2/8/2020 10:05:05 AM] Could not install 'TRYD3NT III' because there is already a mod installed at 'Mods\TRYD3NT III'.
[2/8/2020 10:05:05 AM] Content package load order: Vanilla 0.9  |  3_Tigerfish_UCN  |  EK Coseus Mk-II  |  GreatLighting  |  LittleThunder  |  Nemo's Nautilus  |  Phryne  |  Serenity  |  SI Cobalt  |  EK_Scrapper_Mk-I  |  Enterprise B  |  Leviathan  |  Mining Station A  |  The Patchwork Minelayer  |  TRY3DENT III  |  TRYD3NT III
[2/8/2020 10:05:05 AM] Content package load order: Vanilla 0.9  |  3_Tigerfish_UCN  |  EK Coseus Mk-II  |  GreatLighting  |  LittleThunder  |  Nemo's Nautilus  |  Phryne  |  Serenity  |  SI Cobalt  |  EK_Scrapper_Mk-I  |  Enterprise B  |  Leviathan  |  Mining Station A  |  The Patchwork Minelayer  |  TRY3DENT III  |  TRYD3NT III
[2/8/2020 10:05:03 AM] Attempting to open ALC device "OpenAL Soft"
[2/8/2020 10:05:03 AM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[2/8/2020 10:05:03 AM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[2/8/2020 10:05:02 AM] Logged in as Zomb (SteamID STEAM_1:1:77334902)

**Comment by Regalis11** [comment] 2020-02-08 18:49
This seems to be somehow caused some workshop item getting autoupdated. We need to take a closer look into this and see what's causing it, but for now you should be able to work around the issue by disabling autoupdates by opening config_player.xml in the game folder, and changing the line `autoupdateworkshopitems="true"` to  `autoupdateworkshopitems="false"`.

Based on the debug messages, I would suspect "TRYD3NT III" is causing this error, so you might also want to try disabling that mod.

Sorry for the trouble!

**Comment by Regalis11** [comment] 2020-02-08 19:09
Potentially fixed in https://github.com/Regalis11/Barotrauma-development/commit/ac6b624eca0d978acd5f95a85d5eb6b29b366cee

**Comment by Rokvach** [comment] 2020-02-09 21:41
Couldn't think of a way to reproduce this, also asked community members for ideas but they were at a loss as well. I think it might be best to close this for now and re-open or reference this one if something similar comes up when the patch is out. Closing.

**Closed by Rokvach** 2020-02-09 21:41 UTC
Labels: Bug, Code, Crash
