### ISSUE TITLE
"Can't Reach Persicope" Issue on Typhon 1 still occurs in 1.0.9.0

### ISSUE THREAD

**Issue by Grenno9** [Regalis11/Barotrauma#11937] opened 2023-05-01 22:44 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Reported this issue several months ago but it is still occuring even after saying it was fixed in the 1090 update.

### Reproduction steps

1 load into typhon 1
2 attempt to get bot onto gun
3 bot says "Can't find periscope"

![20230501234404_1](https://user-images.githubusercontent.com/128343810/235544334-d09ebc32-54b8-4188-b18c-82980245ee5b.jpg)

### Bug prevalence

Happens every time I play

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-05-02 06:38
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11552. The changes don't automatically apply to old saves I'm afraid.

**Closed by Regalis11** 2023-05-02 06:38 UTC
