### ISSUE TITLE
[Sub editor] Items are lost when container is copypasted

### ISSUE THREAD

**Issue by So4ineg** [Regalis11/Barotrauma#4248] opened 2020-11-07 19:54 UTC
**Description**
When I try to copy a container with items in editor (doesnt matter, with copypast, using Ctrl button, or through subassembly), container gets copied empty, without any items. Thishappends with any containers - nuclear reactors, oxygen generators, handguns, tools, etc. Also happends with previously saved subassemblies.

**Steps To Reproduce**
Try copypasting any container in editor.

**Version**
0.10.6.2 Windows

**Comment by Xeavas** [comment] 2020-11-07 20:38
Duplicate of #4080 , Fixed in unstable version. 
Unfortunately the discovery and fix of said bug was late in the development process and thus didn't make it to the stable release in time.

**Closed** 2020-11-08 12:54 UTC
