### ISSUE TITLE
Subs without heavy hardpoints have railgun shell racks

### ISSUE THREAD

**Issue by Smau35** [Regalis11/Barotrauma#10209] opened 2022-11-02 14:49 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Azimuth, Dugong and Orca have railgun shell racks even if they dont have heavy hardpoints to mount a railgun on

Azimuth
![Screenshot 2022-11-02 at 16-45-08 unknown png (PNG-kuva 575 × 343 kuvapistettä)](https://user-images.githubusercontent.com/86321358/199520982-875fe2fe-86aa-4189-84b1-918b65f46f2d.png)

Dugong
![Screenshot 2022-11-02 at 16-45-52 unknown png (PNG-kuva 751 × 544 kuvapistettä)](https://user-images.githubusercontent.com/86321358/199521049-11de564c-31bf-4a61-a3ca-bbed7cfe3b7e.png)

Orca
![Screenshot 2022-11-02 at 16-46-03 unknown png (PNG-kuva 412 × 483 kuvapistettä)](https://user-images.githubusercontent.com/86321358/199521099-971d02e8-9014-4022-b312-adad23ba243c.png)

The railgun shell racks could be replaced with ammo shelves

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-11-02 15:09
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10029

**Closed by Regalis11** 2022-11-02 15:09 UTC
