### ISSUE TITLE
[Unstable] CharacterAbilityModifyResistance uses the wrong value for all talents

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10403] opened 2022-11-15 00:21 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Talents that apply resistances using `CharacterAbilityModifyResistance` do nothing

Talents that use CharacterAbilityGiveResistance however do work

Works (La Resistance, -35%):
`        <CharacterAbilityGiveResistance resistanceid="opiateaddiction" multiplier="0.65"/>`

Doesnt work (modified Easy Turtle with 99% resistance)
`        <CharacterAbilityModifyResistance resistanceid="damage" resistance="0.99"/>`

### Version

0.20.6.0 (Unstable)

**Comment by 3e849f2e5c** [comment] 2022-11-15 11:22
Was unable to reproduce, Easy Turtle resistance seems to be correctly applied when entering and exiting water

**Comment by ubertpendragon** [comment] 2022-11-15 11:56
Since I tested Easy Turtle with 0.99 instead of 0.20, I assumed it would give me 99% resistance but it actually gives me 1%

The values are inverted across all talents

**Comment by 3e849f2e5c** [comment] 2022-11-15 12:59
Fixed the inconsistencies in https://github.com/Regalis11/Barotrauma-development/commit/601ff0856f6b4c232c05f0d303d318397790cc83

**Comment by NilanthAnimosus** [comment] 2022-11-30 13:16
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/2b57faa07493e732f98261ead832ba904168f57b, no issues found, closing.

**Closed by NilanthAnimosus** 2022-11-30 13:16 UTC
Labels: Bug, Code, Unstable
