### ISSUE TITLE
[Unstable] Quest completion triggers multiple times/Reverts quest steps

### ISSUE THREAD

**Issue by GreaderOmega** [Regalis11/Barotrauma#10374] opened 2022-11-13 17:56 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I started a singleplayer campaign on the unstable branch and of the three Outpost Events I had so far, two had a bug appear at the end of them

The first one was the "Engineers Are Special" (According to the wiki) event where you help the engineering crew chief with fixing an engine. I succeeded the mission and got the relevant skill increase and reputation gain, but on hitting the 'e' key on the final message of the event, it gave me only a split-second before the event text box appeared again and gave me the final message again as well as the reward for completing the quest. This repeated several times as I began rapidly hitting 'e' to try and get out of the loop, which did happen but also resulted in me both getting a lot of free reputation as well as a Captain who has about 60 mechanical engineering in zone 1 already.

This happened again with the event where you get asked by the outpost manager to deal with a group of clowns that are on the station. That error persists through Retrys as well, so I was able to test it out. Pressing 'e' to talk to the event relevant NPCs on the first press makes the UI and quest icon disappear for a split-second but no text-box appear, pressing it a second time makes the event start. This only happens with event-relevant NPC, not outpost merchants. It replays the final message of the quest chain upon completing, then replays the second-to-last and last message, then repeating the final message and again the second-to-last message. After a few repeats it repeats from the third-to-last message once, then doing the second-to-last and last message loop again before going back yet another step, until for this event it goes back to the Outpost Manager asking you to talk to the clowns, which finally gets you unstuck from the text boxes but also allows you to talk to the clowns again, Talking to the clowns starts this process over, repeating until it reaches the part again where you are asked by the Outpost Manager to help with the clowns (though it will also repeat his final dialog line once). The event reward is also given each time the final message plays.

Testing out the alternative path of that event to tell the Outpost Manager that they are a harlequin-hater, it brings up the dialog option again to call them that, and pressing that option again closes the event box and actually finishes the quest (giving me the reputation reward for both times I select that option). My best guess as to what is happening is that somehow it reverts event steps back when completing them, and possibly the amount of steps reverted can increment.

As for the one event where I had this not happen, it was the event where you find a 'toolbox' lying around which has a bike horn in it. Since I did not want to take the reputation hit I selected to ignore it, This bug did not appear then, but that might be due to 'completing' the event on the first step.

### Reproduction steps

1. Start a singleplayer campaign on the current unstable build (as of the time of writing this)
2. Find an Outpost with an event that has multiple steps
3. Complete the event in any way which requires going through multiple pieces of dialog or choices

![2022-11-13 18_15_36-Barotrauma](https://user-images.githubusercontent.com/118125600/201536577-4bb1acbf-dcf6-448a-83e8-62276abfe0c8.png)
![2022-11-13 18_15_46-Barotrauma](https://user-images.githubusercontent.com/118125600/201536582-169991a1-5f42-4d8d-81c0-1f9f0bdff635.png)
![2022-11-13 18_15_59-Barotrauma](https://user-images.githubusercontent.com/118125600/201536688-a6ab27fa-7271-4357-ad36-950d062fcc35.png)
![2022-11-13 18_22_25-Barotrauma](https://user-images.githubusercontent.com/118125600/201536691-dd875cb4-ea80-4a53-aa6d-62e68237a6e0.png)
![2022-11-13 18_26_57-Barotrauma](https://user-images.githubusercontent.com/118125600/201536699-aef8c29b-7caa-4813-9068-47a5dbe3f7af.png)
![2022-11-13 18_28_55-Barotrauma](https://user-images.githubusercontent.com/118125600/201536701-abe300de-b60f-447b-9ef8-184fc7221261.png)

### Bug prevalence

Happens every time I play

### Version

0.20.5.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by GreaderOmega** [comment] 2022-11-13 18:10
I am sorry about writing a second post, I only just now thought to test if restarting the game would change anything. It does not, so I have attached my save file which should allow a easy way to test this out. Talking to the Outpost Manager should begin the clown event as well as the issues I have written about

[Unstable Testing.zip](https://github.com/Regalis11/Barotrauma/files/9997924/Unstable.Testing.zip)

**Comment by Regalis11** [comment] 2022-11-13 18:25
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10320

**Closed by Regalis11** 2022-11-13 18:25 UTC
