### ISSUE TITLE
The Autopilots Hold position makes submarine oscilate verticaly around the target location. Workaround* included.

### ISSUE THREAD

**Issue by Confodore** [Regalis11/Barotrauma#4857] opened 2021-01-21 17:40 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.
- #4578 Is probably one of the reasons this keeps happening

**Description**
Submarines set on autopilot - _Hold position_ and who are traveling vertical they don't seem to ever stop at their destination. 
Instead the autopilot continuously overshoots the target causing a positive feedback effect, making the sub bounce around and  oscillate around the target location. I have observed submarines bounce up to 10 meters up and down. Pumps are thus constantly wasting power, increasing maintenance. It also makes submarine is harder to enter/exit, gunning down enemies is harder, etc, ...

**Steps To Reproduce**
A test submarine has been attached but issue appears to manifest itself on most submarines.
On the included test submarine use the overhead buttons to select which of the 3 ballasts you wish to use. They have a _Neutral ballast level_ of roughly _0.75_ , _0.5_ and _0.25_ respectively. At ballast level 0.75 the bouncing doesn't seem to appear.
 [Navigation_Test.zip](https://github.com/Regalis11/Barotrauma/files/5850258/Navigation_Test.zip)
![01](https://user-images.githubusercontent.com/57303910/105371555-03023400-5c05-11eb-9287-bb16130c3a60.png)

1. Set autopilot to maintain position
2. Set the position directly above or below the submarine. (Targeting to the far left or right, will in fact stop the bouncing)
3. At this point any small overshoot should magnify itself becoming worse and worse, before reaching its maximum oscillation.
4. Submarine should be in a constant state of aggressively overshooting the target position. 

**Version**
Stable v0.11.0.10 Windows

**Additional information**
This issue has plagued our campaign for a long time now. As a result we have all sorts of speculations and workarounds. 

- To stop the ship from bouncing up and down, we disable our engine (so we don't move horizontal) and set a target to the far left or right on the sonar. This seems to "overpower" the "Y-target velocity" from the Navigation and stop the bouncing.
- Apparently having a submarine with high Neutral ballast level (ex. 0.75) fixes the issue. I suspect the reason is because the submarine is so slow that the autopilot has time to properly predict its movement.
- Using a divide component to halve the incoming signal to the pumps appears to stop the "positive feedback" effect. Bounces stop getting worse and start to diminish over time, eventually stopping the ship. This feature is included in the attached sub file as a switch labeled "A solution". Doing this to the signal also seems to help fix the issue #4578 

P.S.
Love the game! Keep up the good work!

**Comment by lifearoundfreaks** [comment] 2021-01-23 18:48
Not sure if I should insert my 5 cents in here but I spent a lot of time figuring out how to make the ballast behave smoothly and here's what I learned:

- First part of the problem, as you mentioned, is this issue: #4578
- Second part of the problem is the fact that autopilot's direction is not equal to the target velocity that it applies (ie y_velocity output). It is dependant on the helm skill of a character, who currently uses the console. If no-one currently uses it, it halves the target velocity and does that in a way that makes the previous issue even harder to control.
- Third part of the problem (and this is the main one) is the fact that pumps do not work instantly. But that's not all. When you use set_targetlevel, it adds its own delay so that pumps don't instantly switch from 0% power usage to 100% (which in turn quickly fries your JBs). So that oscillation mainly comes from the fact that your pumps can't keep up with the direction you autopilot chooses and constantly lag behind.

The things that I ended up doing:
- Adding more pump power per ballast volume so that ballast reaches desired level quicker.
- Not changing neutral ballast level in the control console and instead properly scaling y_level myself with logic components ([Here](https://github.com/Regalis11/Barotrauma/files/5860830/Hopper.zip) is my sub so that you can see what exactly I did).
- Having your neutral ballast close to 0.32 can help (same up and down speed). Alternatively, keeping it close to 0.5 helps the pumps to not get overwhelmed in one direction.

It will still oscillate a tiny bit in some cases but behaves much better.

**Comment by Regalis11** [comment] 2021-01-27 08:59
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bf5860fd93d5a17b1356f457e80ef49a389f8dff

**Comment by Rokvach** [comment] 2021-02-10 11:05
Tested, working correctly. Closing.

**Closed by Rokvach** 2021-02-10 11:05 UTC
Labels: Bug, Code, High prio
