### ISSUE TITLE
Pets spawn OUTSIDE the submarine/outposts in campaign

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#4528] opened 2020-12-14 23:55 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Pets sometimes spawn outside the submarine/outpost (see #4085, pets don't actually disappear)

**Steps To Reproduce**
It just happens

**Version**
 v0.11.0.9 Win10

**Additional information**
Orange boy happily swimming outside at the start of mission
![unknown](https://user-images.githubusercontent.com/73229309/102150149-2b617a80-3e70-11eb-8ae1-103f50caabaa.png)
Create pet spawn points?

**Comment by Regalis11** [comment] 2020-12-17 12:21
I'm afraid I wasn't able to reproduce this: the pet should spawn at a human spawnpoint and it seems to be working correctly. Does this happen consistently? I also wonder if it could have something to do with the sub you're using, is it available in the workshop so we could give it a test?

**Comment by ubertpendragon** [comment] 2020-12-17 13:02
It happened very consistently during my campaign. 

Sometimes the pet would spawn inside the submarine, sometimes it would spawn inside the main shuttle (which has spawn points), but in most cases it would simply spawn outside for no particular reason. Sometimes near the submarine, sometimes around the oupost

All 6 of my spawn points have designated classes and custom ID for permissions.

**Comment by Regalis11** [comment] 2020-12-18 10:29
I still wasn't able to reproduce this, but I added some extra measures in https://github.com/Regalis11/Barotrauma-development/commit/daf851d2dd6258c5a590697f464d5fc5e1435169 that might fix the issue.

Pets were supposed to spawn at the position of the owner, but that wasn't working correctly in the latest version. The game also sometimes spawned them inside drones/shuttles, and I suspect they ended up outside because the drones were not necessarily moved to their correct position at that point.

**Comment by Rokvach** [comment] 2021-01-11 08:58
There hasn't been any sightings of this happening since the fix, seems to be working correctly. Closing.

**Closed by Rokvach** 2021-01-11 08:58 UTC
Labels: Bug, Code
