### ISSUE TITLE
Doesnt let me in the game

### ISSUE THREAD

**Issue by johnperson5943** [Regalis11/Barotrauma#11665] opened 2023-03-26 23:08 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Whenever i join a multiplayer campaign, im stuck in the loading screen until i get a message saying its taking really long to load in. No matter how long i wait it never lets me in the game, so im just stuck in the lobby. I cant even spectate

### Reproduction steps

1. get yourself a brand new 893GB SSD
2. install barotrauma
3. join your friend's campaign, no mods.
4. start up the campaign, even a new one works!
5. look at the loading screen
6. look at the loading screen
7. look at the loading screen
8. press yes on the message

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Error while starting the round (did not receive STARTGAMEFINALIZE message from the server). Returning to lobby... 
and also
Coroutine ''MultiplayerCampaign.DoInitialCameraTransition'' has failed
```

**Comment by Regalis11** [comment] 2023-03-27 00:53
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11454

**Closed by Regalis11** 2023-03-27 00:53 UTC
