### ISSUE TITLE
Unable to start the game on a dedicated server.

### ISSUE THREAD

**Issue by ShoulinSS** [Regalis11/Barotrauma#8908] opened 2022-04-22 11:51 UTC
**Description**
When trying to start the game, the server console is filled with errors, and the game does not start.

**Steps To Reproduce**
Just start the mission on a dedicated server.

**Additional information**
Here are the errors that appear.

Error while loading component of the type Barotrauma.Items.Components.ConnectionPanel. {The given key 'None' was not present in the dictionary.}
   at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNotFoundException(Object key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
   at Barotrauma.TextManager.ContainsTag(Identifier tag) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Text\TextManager.cs:line 81
   at Barotrauma.Items.Components.Connection..ctor(ContentXElement element, ConnectionPanel connectionPanel, IdRemap idRemap) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Signal\Connection.cs:line 132
   at Barotrauma.Items.Components.ConnectionPanel..ctor(Item item, ContentXElement element) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Signal\ConnectionPanel.cs:line 77
   
Error while loading entity of the type Barotrauma.Item. {Object reference not set to an instance of an object.}
   at Barotrauma.Items.Components.PowerTransfer.RefreshConnections() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Power\PowerTransfer.cs:line 286
   at Barotrauma.Items.Components.PowerTransfer.OnItemLoaded() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Power\PowerTransfer.cs:line 392
   at Barotrauma.Items.Components.RelayComponent.OnItemLoaded() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Signal\RelayComponent.cs:line 110
   at Barotrauma.Item.Load(ContentXElement element, Submarine submarine, Boolean createNetworkEvent, IdRemap idRemap) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 3205
Error while loading component of the type Barotrauma.Items.Components.ConnectionPanel. {The given key 'None' was not present in the dictionary.}
   at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNotFoundException(Object key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
   at Barotrauma.TextManager.ContainsTag(Identifier tag) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Text\TextManager.cs:line 81
   at Barotrauma.Items.Components.Connection..ctor(ContentXElement element, ConnectionPanel connectionPanel, IdRemap idRemap) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Signal\Connection.cs:line 132
   at Barotrauma.Items.Components.ConnectionPanel..ctor(Item item, ContentXElement element) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Signal\ConnectionPanel.cs:line 77

**Comment by Regalis11** [comment] 2022-04-22 12:32
Duplicate of https://github.com/Regalis11/Barotrauma/issues/8880

It should be possible to work around this issue by changing the language in config_player.xml to "English" manually. Sorry for the inconvenience!

**Closed by Regalis11** 2022-04-22 12:32 UTC
