### ISSUE TITLE
Leftover empty folders on Steam Workshop

### ISSUE THREAD

**Issue by Malidictus** [Regalis11/Barotrauma#1800] opened 2019-09-01 17:18 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Every time I download one of my mods from the Steam Workshop, an empty folder tree is created, which is referenced nowhere in the filelist.xml file and I didn't make it.

**Steps To Reproduce**
I only know of one mod (mine) which causes this issue, and it's this one:

https://steamcommunity.com/sharedfiles/filedetails/?id=1836559722

Subscribing to the mod creates all of the proper files in their proper places. However, it also creates a Mods\Reinforced Doors\Mods\Reinforced Doors\Items\Door folder. I did not create this folder. It popped up on its own when I updated the v0.9.1.0 version of the mod with the v0.9.2.2. When first updating the mod, all files appeared under Mods\Reinforced Doors\Mods\Reinforced Doors where the game couldn't find them. I moved them manually back to Mods\Reinforced Doors and deleted the secondary Mods folder. I uploaded the mod without the secondary Mods folder, but it nevertheless reappears every time I redownlod the mod.

**Version**
Windows 7 Pro x64, v0.9.2.2

**Additional information**
I don't know why the double mods folder happens, I don't if this folder somehow got recorded to the Steam Workshop in a way I can't delete or if it's maybe part of how the mods structure is supposed to work. It does not, however, show up on any other mod, mine or other people's.

**Comment by Regalis11** [comment] 2019-09-01 19:51
I unfortunately wasn't able to reproduce this by subscribing to the mod and enabling it. The folder structure seems correct, without the extra subfolder. Could it be that the folder where Steam downloads the workshop items has gotten messed up for some reason? The game simply copies the files/folders from Steam's download folder as-is, and if you have those extra folders present there, they will always appear when you enable the mod. 

The download folder should be located in ~\Steam\steamapps\workshop\content\602960\1836559722, could you please check how the contents of that folder look and if the folder structure is correct there?

**Comment by Malidictus** [comment] 2019-09-01 20:19
Originally, I'd tried to delete the extra subfolder from the mod folder and it came back later. However, I followed your instructions and this time it hasn't come back. I unsubscribed from the mod and deleted its entire folder from the Workshop, quit Steam and resubscribed to it (just to be on the safe side). The mode came back without the extra folder in Workshop and was placed without the extra folder in Mods.

This seems like user error on my part, having trouble updating mods from 0.9.0.0 to 0.9.2.2's newer structure and leaving behind parasitic folders. Feel free to disregard and close the issue. My apologies.

**Comment by Regalis11** [comment] 2019-09-01 20:50
There's still a bunch of issues we need to look into in the Workshop logic (especially when updating mods that were made with an older version of the game), so it's entirely possible that it was caused by the game, not an user error. But in any case, I'm glad you managed to fix it! :) I'll close this issue for now, but I'll reopen it if the problem resurfaces or if we find a way to reproduce it.

**Closed by Regalis11** 2019-09-01 20:50 UTC
Labels: Bug, Code

**Comment by Malidictus** [comment] 2019-09-01 21:28
My gut feeling is this was an issue with 0.9.2.1 or 0.9.2.0. That's when I was uploading the offending version of the mod, and when the game moved my files as I've described. I wasn't able to fix it then and I hadn't tried since. I suspect you guys have managed to patch that since. I'll definitely keep an ear to the ground and post here again if I run into the same issue again.
