### ISSUE TITLE
barotrauma crashing on launch

### ISSUE THREAD

**Issue by cptprince12** [Regalis11/Barotrauma#3587] opened 2020-08-17 08:34 UTC
[crashreport (38).log](https://github.com/Regalis11/Barotrauma/files/5083062/crashreport.38.log)
every time i try to launch barotrauma the game keeps crashing and giving me this crash report

**Comment by Regalis11** [comment] 2020-08-17 10:13
This seems to be caused by some of the mods you're using: the game fails to find the job configs (assistant, engineer, mechanic, etc) from the mods you've installed. You might want to try uninstalling the mods and see if that helps.

But even if that takes care of the issue, we need to make sure invalid mods don't crash the game but display a more descriptive error message instead, so I'll keep this ticket open.

**Comment by Regalis11** [comment] 2020-09-15 09:56
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/1e60072fd46d4c5e05bc3ece164b07805ab4750e. The game now tries to load the location types from the vanilla content package if the selected packages don't contain any, and logs a more descriptive error message.

**Comment by Rokvach** [comment] 2020-09-21 10:05
No issues, closing.

**Closed by Rokvach** 2020-09-21 10:05 UTC
Labels: Bug, Code, Crash, Modding
