### ISSUE TITLE
 [Crash Report] AwesomeWelles #4258 - 13 Avril 2020 - Arround 19h00

### ISSUE THREAD

**Issue by Ant1V1RU5** [Regalis11/Barotrauma#2626] opened 2020-04-13 17:50 UTC
**Additionals infos**

The player AwesomeWelles#4258 (Discord) encoutered this same issue multiple time in a row. Here is the last crashlog he send us.

Edit : Adding a new crash report.

[crashreport_2.log](https://github.com/Regalis11/Barotrauma/files/4470905/crashreport_2.log)
[message (4).txt](https://github.com/Regalis11/Barotrauma/files/4471156/message.4.txt)

**Comment by Regalis11** [comment] 2020-04-14 07:55
Duplicate of #2533

**Closed by Regalis11** 2020-04-14 07:55 UTC
