### ISSUE TITLE
Bots get stuck when trying to repair Winterhalter damaged docking port

### ISSUE THREAD

**Issue by marpul358** [Regalis11/Barotrauma#9200] opened 2022-05-23 17:50 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Winterhalter docking port damage (and quite often the hull area around it) makes the bots get stuck at the ladder part. They climb like to the platform level then drop down and repeat. This is when the actual docking port is damaged and is even worse if it's completely destroyed and water is pouring down from it.

Attached image shows me standing on the platform and the bots that are stuck in the climb-drop-climb.

![barotrauma_winterhalter_003 - Copy](https://user-images.githubusercontent.com/95497673/169877821-b7a01f52-6485-43cd-939b-c4fb72fbcd6d.jpg)
.

### Reproduction steps

1. Play Winterhalter
2. Assign bots on repair duty
3. Damage the docking port (and area around it)
4. Make it worse by completely destroying the hatch so water starts pouring in

### Bug prevalence

Happens every time I play

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by ekqvist** [comment] 2022-05-24 06:42
Haven't tested what the issue is here but implementing repairing while on a ladder (#5587) might also help with this issue

**Comment by itchyOwl** [comment] 2022-05-27 12:50
Allowing to repair while on ladder should fix this particular issue, but there seems to be something wrong with the steering logic. Can also repro this by ordering a bot to follow and going on that platform. Looking into it.

**Comment by itchyOwl** [comment] 2022-05-27 14:08
Actually this can't really be fixed in the code. Adjusting the waypoints a bit helped: Regalis11/Barotrauma-development@bc916ea.

**Comment by Rokvach** [comment] 2022-06-06 02:32
Tested, working correctly. Closing.

**Closed by Rokvach** 2022-06-06 02:32 UTC
Labels: Bug
