### ISSUE TITLE
Some variable was null

### ISSUE THREAD

**Issue by rising-4ce** [Regalis11/Barotrauma#4134] opened 2020-10-25 21:02 UTC
- [V] I have searched the issue tracker to check if the issue has already been reported.

**Description**
After returning to the city, the server crashed. We swam 300 meters, picked up the artifact and came back to the city. There is screenshot with error:
![image](https://user-images.githubusercontent.com/54648977/97119008-81425d80-171e-11eb-9ae9-579e32444c6d.png)

**Version**
v0.10.5.1, brahch version, revision 9e259b2148. OS: Windows 10.

**Comment by Regalis11** [comment] 2020-10-26 07:26
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3819

**Closed by Regalis11** 2020-10-26 07:26 UTC
