### ISSUE TITLE
0.1000.0.0 (Unstable): Autofill does not work when switching to a new sub

### ISSUE THREAD

**Issue by mrjpjr** [Regalis11/Barotrauma#2934] opened 2020-05-30 11:36 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When buying and switching to a new sub, the sub is completely empty if it uses autofill

**Steps To Reproduce**
Buy a new sub (that uses autofill).
Start the round.
The sub is completely empty.

**Version**
0.1000.0.0 (Unstable) Windows.

**Additional information**
I think it is because the autofill check is triggered on the sub you start with.

**Comment by Regalis11** [comment] 2020-05-30 11:55
Duplicate of #2916

**Closed by Regalis11** 2020-05-30 11:55 UTC
