### ISSUE TITLE
SHELL A43 isnt rotated in status monitor

### ISSUE THREAD

**Issue by rdinit** [Regalis11/Barotrauma#13270] opened 2024-01-05 17:45 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![изображение](https://github.com/Regalis11/Barotrauma/assets/28570294/caa67f87-43af-413b-94bd-e75632d1b3e5)
![изображение](https://github.com/Regalis11/Barotrauma/assets/28570294/2aba57c0-f826-4497-8513-67876b19bdc2)

### Reproduction steps

1. Create any submarine with this part rotated by 90
2. start game and look in status monitor

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.7.0 (Winter Update hotfix)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2024-01-06 10:26
Duplicate of https://github.com/Regalis11/Barotrauma/issues/13065

**Closed by Regalis11** 2024-01-06 10:26 UTC
