### ISSUE TITLE
[Unstable 0.1003.0.0] Incorrect Character orientation when Reconnecting after Desync Disconnect

### ISSUE THREAD

**Issue by mrjpjr** [Regalis11/Barotrauma#3117] opened 2020-06-16 14:34 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
All characters except your own look like they are lying face down, when you jump back into the game after disconnecting due to desync.

**Steps To Reproduce**
Desync disconnect.
Rejoin the server and "Spectate" to jump back into your character
Other characters will be lying face down.

**Version**
Unstable 0.1003.0.0 revision 7b3c34c2a
Windows 10, 64 bit

**Additional information**
Disconnecting and reconnecting a second time seems to fix it.

Best to see it for yourself.
https://www.dropbox.com/s/xhypb7ottk894vn/Barotrauma%20Desync%20Reconnect%20Characters%20lying%20on%20the%20ground.mp4?dl=0

**Comment by Regalis11** [comment] 2020-06-17 15:15
While debugging #3069, I noticed that this can happen if the ragdoll ends up in an invalid state (very high velocity or a position somewhere way outside the level), in which case the game freezes the collider. I added some measures in https://github.com/Regalis11/Barotrauma-development/commit/2ab41c8df897370ce91f7bbfbb48d3f9baeb0816 to make that less likely to happen, let's see if this issue still resurfaces.

**Comment by Rokvach** [comment] 2020-06-20 21:53
This issue was noticed only briefly in 0.1004.0.0, tester desynced and couldn't see anyone on the server and when they rejoined the server they saw all the players laying on the floor, but it looks like it was only temporary, rather than permanent as it was on the previous build.

**Comment by Rokvach** [comment] 2020-06-27 12:18
No reported cases of this happening after the last report, I think if it is only temporary that you will see characters laying on the ground the issue isn't as bad, so I will be closing this.

**Comment by Rokvach** [comment] 2020-07-02 20:08
This just happened to me when I joined a server, I saw all the characters just laying on the floor. Reconnecting to the server fixed the issue. 

Video:
https://streamable.com/ot5icn

**Comment by Rokvach** [comment] 2020-07-05 11:12
Getting more reports of this happening 0.10.2.0, sometimes reconnecting doesn't fix it but instead when a round changes, for example on yesterdays case there were two players on a server experiencing this and as soon as the crew left the outpost players who had the issue didn't have it anymore.

**Comment by Regalis11** [comment] 2020-07-10 09:41
Still haven't been able to repro this, but I implemented to fixes for cases that could potentially cause this. Let's see if these make a difference:
https://github.com/Regalis11/Barotrauma-development/commit/20cbe92fdbcda95c72ef9e8d3cc738ac97209201
https://github.com/Regalis11/Barotrauma-development/commit/7da1debb6276f7046746f4f7c25642b088fa39b7

**Comment by Rokvach** [comment] 2020-09-05 07:47
Haven't seen any reports of this happening for a while now

**Comment by Kaillera** [comment] 2020-09-05 20:21
Can't really test the fix in MP due to sub position not synced to client this version.

**Comment by Rokvach** [comment] 2020-09-09 08:49
There hasn't been any sightings during Unstable testing so far, but there hasn't really been any disconnections either.

**Comment by Rokvach** [comment] 2020-09-10 09:14
No sightings since Unstable started, looks to be working correctly. Closing.

**Comment by EtiamNullam** [comment] 2020-09-22 15:35
Just encountered this bug again in 0.10.5.1 (stable) during a campaign. Its rare but it still happens.

**Comment by ekqvist** [comment] 2020-09-22 15:47
Reopened and moved back to to-do

**Comment by Rokvach** [comment] 2021-01-05 15:45
No sightings for a while now

**Comment by Kaillera** [comment] 2021-01-05 16:53
I have never seen this issue since.

**Closed** 2021-01-13 13:29 UTC
Labels: Bug, Code, Networking
