### ISSUE TITLE
[0.9.9.0] Crash - Boolean get_IsActive()

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2511] opened 2020-03-27 23:10 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
[crashreport (4).log](https://github.com/Regalis11/Barotrauma/files/4396258/crashreport.4.log)

**Version**
0.9.9.0

**Comment by Regalis11** [comment] 2020-03-29 16:39
Couldn't find a way to repro, but I'm suspecting this is caused by a race condition where the voip thread tries to capture audio when the game is exiting (potentially because of some other type of crash, not necessarily because the game was being exited manually).

If that was what caused this, should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/31a1f78932e4d9e98771e327dc04085072457b02

**Comment by Udrakan** [comment] 2020-03-31 16:51
I had this crash in SP campaign. Strange that voip would cause that in SP environmnet.

**Comment by Rokvach** [comment] 2020-04-07 11:09
There hasn't been any reported cases of this happening on the latest Unstable, closing for now.

**Closed by Rokvach** 2020-04-07 11:09 UTC
Labels: Bug, Code, Crash, Needs testing
