### ISSUE TITLE
Reactor - Lightcomponent "Alarm" is not rotated

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#9258] opened 2022-06-05 10:27 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Subeditor - Alarm lighting does not turn!
Video:
https://user-images.githubusercontent.com/93348499/172045962-ed0b16d7-d2ce-43d8-96e4-fb44565d7d50.mp4

### Reproduction steps

Look at the video or:
1. Start subeditor
2. Add reactor
3. Showlighting
4. Turn on the second lighting component (Alarm)
5. Turn the reactor

### Bug prevalence

Happens every time I play

### Version

0.17.16.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-06-05 12:02
This is caused by the same issue as https://github.com/Regalis11/Barotrauma/issues/9248 - only the first light component of the item was rotated when rotating it in the sub editor. Closing as a duplicate.

**Closed by Regalis11** 2022-06-05 12:02 UTC
