### ISSUE TITLE
Game crashes in multiplayer when making contact with enemies

### ISSUE THREAD

**Issue by zareoux** [Regalis11/Barotrauma#10432] opened 2022-11-18 03:10 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Tried to fight off enemies in submarine

### Reproduction steps

Started multiplayer mission
-Starting submarine was a mod sub

Made contact with group of enemies 

Moved through sub to fight off intruders

Game crashed

### Bug prevalence

Just once

### Version

0.20.6.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
The server has crashed: servercrashreport.log||
Object reference not set to an instance of an object. (NullReferenceException)    at Barotrauma.EnemyAIController.UpdateLimbAttack(Single deltaTime, Vector2 attackSimPos, IDamageable damageTarget, Single distance, Limb targetLimb) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\EnemyAIController.cs:line 2210
   at Barotrauma.EnemyAIController.UpdateAttack(Single deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\EnemyAIController.cs:line 1891
   at Barotrauma.EnemyAIController.Update(Single deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\EnemyAIController.cs:line 441
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2929
   at Barotrauma.GameScreen.Update(Double deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 195
   at Barotrauma.GameMain.Run() in E:\Barotrauma-development\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 325
   at Barotrauma.Program.Main(String[] args) in E:\Barotrauma-development\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 78
```

**Comment by Regalis11** [comment] 2022-11-18 07:31
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10249

**Closed by Regalis11** 2022-11-18 07:31 UTC
