### ISSUE TITLE
Able to "exit" Scaled up Doors and Hatches when closed

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2354] opened 2020-02-23 10:09 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you scale up doors and hatches, you can just exit through them despite being closed.
![Giffy](https://user-images.githubusercontent.com/5086682/75117296-35469280-563e-11ea-85bb-54b7f324114a.gif)

**Version**
~0.9.7

**Comment by FLundin** [comment] 2020-04-11 02:13
I been working on a large sub for weeks now and I finally got to the point where I was gonna test it and then I encounterd this  #2359 (I would have never expected that the hitbox would not scale with the sprite). I got 15 stairs and my floor height difference is higher than a door and Large Wall. All of  the stairs, even when you scale them up to jut 1.100 they become an impassable object. The reason i chose stairs before ladders were that you cant drag players in handcuffs up/down ladders if you need to escort them to the brig without knocking them unconscious and due to the size of sub I am making I thought i could take this liberty of using stairs as I normally aren't due to the subs size.
Of course I could continue working on it and use ladders instead until you fix it but it is slightly heard breaking to see that this issue is set to low prio. I can understand why, there is of course a lot of subs made on the workshop that isn't using stairs and many that is but used the fixed max height the stairs offer. But realizing this is on low prio have broken my inspiration never the less..

I am wondering if I can do anything to encurage perhaps this issue to be fixed for next release(or sooner)? https://trello.com/c/P7khpSRo
I can offer a spoiler of the sub I am making to share what you done this far to inspire me: https://cdn.discordapp.com/attachments/583998455916003341/698352967090438154/impossible.png
I got some really unique ideas and details in the build so I have blurred it (a lot). I was hoping myself to inspire some other creators with them but... that have to wait :( . I'll put the sub on ice for now (pun intended)

**Comment by Regalis11** [comment] 2020-04-14 14:04
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a4df6257d5261206a127dab46ed1321d4f258f67

**Comment by Rokvach** [comment] 2020-04-14 14:31
Didn't notice any issues, closing.

**Comment by FLundin** [comment] 2020-04-14 17:42
> Fixed in [Regalis11/Barotrauma-development@a4df625](https://github.com/Regalis11/Barotrauma-development/commit/a4df6257d5261206a127dab46ed1321d4f258f67)

yes!!!

**Comment by Kaillera** [comment] 2020-04-16 23:59
@Rokvach This ticket needs reopening. I am still able to exit through the giant door on my sub The Aeche (III).

**Version**
0.9.9.0

**Comment by Rokvach** [comment] 2020-04-17 03:08
Tested, I was able to go through windowed doors from the parts where there isn't any window. Reopening.

**Comment by Regalis11** [comment] 2020-04-17 07:52
@Rokvach Which branch did you test this on? It hasn't been merged to dev or release yet.

**Comment by Regalis11** [comment] 2020-04-17 07:57
Could not reproduce the issue, I think you were testing on an incorrect branch

**Comment by Rokvach** [comment] 2020-04-17 08:10
I must of just tested it in Unstable thinking that it made it to the build, checked on bugfixes again and its working as intended, closing again.

**Closed by Rokvach** 2020-04-17 08:10 UTC
Labels: Bug, Code, Low prio, Need more info

**Comment by FLundin** [comment] 2020-04-23 21:38
Im not too familiar with Github to know how to know what @a4df625 version number relates to in actual version numbers but the issue of #2359 did not get fixed with recent release. scaled up stairs are still solid collidable boxes and you cannot pass through them if you scale up a staircase.

**Comment by FLundin** [comment] 2020-04-26 17:00
https://cdn.discordapp.com/attachments/583998455916003341/704013825296564375/Desktop_2020.04.26_-_18.46.46.02.DVR_Muted.mp4

**Comment by thegrb93** [comment] 2020-04-26 17:16
@FLundin you have to make a new issue. They don't read closed ones.

**Comment by Regalis11** [comment] 2020-04-26 18:33
@FLundin Sorry but the fix has not been included in the public versions of the game yet.

I reopened #2359 because it seems to be a separate issue: the fix we did only applies to door colliders.

**Comment by FLundin** [comment] 2020-04-26 18:36
@Regalis11 Thank you for letting me know! <3
