### ISSUE TITLE
Conc separator not editable in game

### ISSUE THREAD

**Issue by Working-Joe** [Regalis11/Barotrauma#8569] opened 2022-03-22 09:49 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The `separator` field on the Conc component is not editable in game, but I don't see a reason why it shouldn't be editable like other component fields.

**Comment by Regalis11** [comment] 2022-03-22 16:53
Duplicate of https://github.com/regalis11/barotrauma/issues/8364, fixed in v0.17

**Closed by Regalis11** 2022-03-22 16:53 UTC
Labels: Bug, Code
