### ISSUE TITLE
[0.1100.0.7] Various problems with vanilla assemblies

### ISSUE THREAD

**Issue by Singularia** [Regalis11/Barotrauma#4362] opened 2020-11-20 16:29 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
There are multiple assemblies that have problems, such as visual misplacement of wires, wrong size and
or depth of some components.

**Steps To Reproduce**
Check parameters of shown (bellow) assemblies and\or try to spawn them in the editor

**Version**
0.1100.0.7; Windows 10 Pro x64

**Additional information**
**"Button door" has depth 0.010 instead of 0.510**
![image](https://user-images.githubusercontent.com/62324831/99822464-5cb79500-2ba7-11eb-92dc-82a78599623b.png)

**"Airlock Pump" spawns legacy pump instead of new one, also wrong size of a water detector (0.160 instead of 0.5)**
![image](https://user-images.githubusercontent.com/62324831/99822979-f121f780-2ba7-11eb-9e00-28469b073713.png)

**"AlienHorizontalAssembly1" is visible in the editor, but it shouldn't be as other alien assemblies**
![image](https://user-images.githubusercontent.com/62324831/99822937-e6fff900-2ba7-11eb-8cc1-a43e66b56e59.png)

**All items in "Large Diving Gear Cabinet" can't be picked up from the ground if dropped because flag "Can Be Picked" set to off**
![image](https://user-images.githubusercontent.com/62324831/99823604-b5d3f880-2ba8-11eb-9cd2-78a6a8446968.png)
![image](https://user-images.githubusercontent.com/62324831/99823810-f03d9580-2ba8-11eb-98ce-0838cb94091d.png)

**Comment by Singularia** [comment] 2020-11-27 10:32
Also i noticed that "Automated Docking Hatch" assembly creates unnecessary waypoint markers.
![image](https://user-images.githubusercontent.com/62324831/100439770-0d69eb00-30f8-11eb-8fd9-44e1c36a57d1.png)

**Comment by Regalis11** [comment] 2020-11-30 18:15
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/60db23791eb93a8dbda6302971b64a151af8344b

**Comment by Xeavas** [comment] 2020-12-11 18:01
[0.1200.0.0] - No issues for "button door" "airlock pump" and "automated docking hatch". AlienHorizontalAssembly1 is now properly hidden.

Original issue with diving cabinet is fixed, but due to inventory stacking, placing assembly and going into test mode will result in a bunch of items on the floor, exiting back into sub editor the items will be there too afterwards.

![c1](https://user-images.githubusercontent.com/72674994/101938128-d0384980-3c1d-11eb-8fa6-31d6e8274e47.jpg)
![c2](https://user-images.githubusercontent.com/72674994/101938132-d1697680-3c1d-11eb-858a-f64789ca41de.jpg)

**Comment by Rokvach** [comment] 2020-12-11 20:54
Moving back to todo

**Comment by Regalis11** [comment] 2020-12-15 11:40
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4952a277abc4ce0cc9431bfafeb012e2897e872e

**Comment by Rokvach** [comment] 2020-12-18 12:01
Tested, wasn't able to reproduce the issue. Looks to be working correctly. Closing.

**Closed by Rokvach** 2020-12-18 12:01 UTC
Labels: Bug, Design
