### ISSUE TITLE
Client crash: Object reference not set to an instance of an object [minimap]

### ISSUE THREAD

**Issue by jumble** [Regalis11/Barotrauma#7359] opened 2021-11-18 04:24 UTC
- [ X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Full crash to desktop upon loading into friends' server. Crash repeats every time I log in.

**Steps To Reproduce**
Unsure if this was the root cause, but swapped to a handheld status monitor quickly after operating a water scooter. Other than that, no idea :(

**Version**
Current Steam version

**Additional information**
```
Loaded submarine: Humpback (3A07AD80D2BA484CCE719246A976326F)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)


System info:
    Operating system: Microsoft Windows NT 10.0.18363.0 64 bit
    GPU name: NVIDIA GeForce GTX 1080 Ti
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void DrawHUDBack(Microsoft.Xna.Framework.Graphics.SpriteBatch, Barotrauma.GUICustomComponent)
Stack trace: 
   at Barotrauma.Items.Components.MiniMap.DrawHUDBack(SpriteBatch spriteBatch, GUICustomComponent container) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\Machines\MiniMap.cs:line 1091
   at Barotrauma.GUICustomComponent.Draw(SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUICustomComponent.cs:line 43
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Draw(Camera cam, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 333
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\GameScreen.cs:line 161
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 1057
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 60


Last debug messages: (player names/IDs replaced with xxx)
[11/17/2021 11:03:17 PM] xxx
[11/17/2021 11:03:17 PM] xxx
[11/17/2021 11:03:17 PM] xxx
[11/17/2021 11:03:17 PM] xxx
[11/17/2021 11:03:16 PM] xxx
[11/17/2021 11:03:16 PM] xxx
[11/17/2021 11:03:16 PM] xxx
[11/17/2021 11:03:14 PM] WARNING: Character count did not match expected character count in InitCharacters of EscortMission
[11/17/2021 11:03:12 PM] Task count: 0
[11/17/2021 11:03:08 PM] Generating an outpost for the end of the level... (Location: Sparti Linea, level type: LocationConnection)
[11/17/2021 11:03:07 PM] Generating an outpost for the start of the level... (Location: Seosu, level type: LocationConnection)
[11/17/2021 11:02:31 PM] (Msg) SDR RelayNetworkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[11/17/2021 11:02:31 PM] (Msg) Ping location: iad=11+1,atl=26+2/24+1,ord=26+2,dfw=47+4/47+2,lax=71+7/72+2,sea=82+8/74+2,par=91+9/87+1,lhr=91+9/95+1,fra=101+10/96+1,ams=102+10/98+1,gru=149+14/154+1,sgp=260+26/246+16
[11/17/2021 11:02:31 PM] (Msg) Ping measurement completed
[11/17/2021 11:02:29 PM] (Verbose) Communications with routing cluster 'sgp' established.
[11/17/2021 11:02:29 PM] (Verbose) Communications with routing cluster 'syd' established.
[11/17/2021 11:02:29 PM] (Verbose) Communications with routing cluster 'seo' established.
[11/17/2021 11:02:29 PM] (Verbose) Communications with routing cluster 'maa' established.
[11/17/2021 11:02:29 PM] (Verbose) Communications with routing cluster 'tyo1' established.
[11/17/2021 11:02:29 PM] (Verbose) Communications with routing cluster 'jnb' established.
[11/17/2021 11:02:29 PM] (Verbose) Communications with routing cluster 'tyo' established.
[11/17/2021 11:02:29 PM] (Verbose) Communications with routing cluster 'waw' established.
[11/17/2021 11:02:29 PM] (Verbose) Communications with routing cluster 'vie' established.
[11/17/2021 11:02:29 PM] (Verbose) Communications with routing cluster 'sto2' established.
[11/17/2021 11:02:29 PM] (Verbose) Communications with routing cluster 'sto' established.
[11/17/2021 11:02:29 PM] (Verbose) Communications with routing cluster 'dxb' established.
[11/17/2021 11:02:29 PM] (Verbose) Communications with routing cluster 'bom' established.
[11/17/2021 11:02:29 PM] (Verbose) Communications with routing cluster 'hkg' established.
[11/17/2021 11:02:29 PM] (Verbose) Communications with routing cluster 'scl' established.
[11/17/2021 11:02:29 PM] (Verbose) Communications with routing cluster 'lim' established.
[11/17/2021 11:02:29 PM] (Verbose) Communications with routing cluster 'mad' established.
[11/17/2021 11:02:29 PM] (Verbose) Communications with routing cluster 'sea' established.
[11/17/2021 11:02:29 PM] (Verbose) Communications with routing cluster 'par' established.
[11/17/2021 11:02:29 PM] (Verbose) Communications with routing cluster 'eze' established.
[11/17/2021 11:02:29 PM] (Verbose) Communications with routing cluster 'lhr' established.
[11/17/2021 11:02:29 PM] (Verbose) Communications with routing cluster 'lax' established.
[11/17/2021 11:02:29 PM] (Verbose) Communications with routing cluster 'gru' established.
[11/17/2021 11:02:29 PM] (Verbose) Communications with routing cluster 'ord' established.
[11/17/2021 11:02:29 PM] (Verbose) Communications with routing cluster 'fra' established.
[11/17/2021 11:02:29 PM] (Verbose) Communications with routing cluster 'ams' established.
[11/17/2021 11:02:29 PM] (Verbose) Communications with routing cluster 'dfw' established.
[11/17/2021 11:02:28 PM] (Verbose) Communications with routing cluster 'iad' established.
[11/17/2021 11:02:28 PM] (Verbose) Communications with routing cluster 'atl' established.
[11/17/2021 11:02:28 PM] (Msg) SDR RelayNetworkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[11/17/2021 11:02:28 PM] (Msg) Performing ping measurement
[11/17/2021 11:02:28 PM] (Msg) Got SDR network config.  Loaded revision 351 OK
[11/17/2021 11:02:28 PM] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[11/17/2021 11:02:22 PM] Attempting to open ALC device "OpenAL Soft on Focusrite USB (Focusrite USB Audio)"
[11/17/2021 11:02:21 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[11/17/2021 11:02:21 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[11/17/2021 11:02:20 PM] Logged in as xxx (SteamID STEAM_1:1:xxx)
```

**Comment by Regalis11** [comment] 2021-11-18 08:24
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7279

**Closed by Regalis11** 2021-11-18 08:24 UTC
Labels: Bug, Code, Crash
