### ISSUE TITLE
Server browser spam happening again.

### ISSUE THREAD

**Issue by Fentanyl1984** [Regalis11/Barotrauma#12086] opened 2023-05-27 19:22 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

dedicated server spamming in the server browser happening again, now on even bigger scale - its literally impossible to see any server, public servers are practically unplayable.
![Screenshot_105](https://github.com/Regalis11/Barotrauma/assets/123274797/223ae040-c0f7-4a34-a02c-46b53b64dcf2)

### Reproduction steps

-

### Bug prevalence

Happens every now and then

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-05-28 08:53
Duplicate of https://github.com/Regalis11/Barotrauma/issues/9768

**Closed by Regalis11** 2023-05-28 08:53 UTC
