### ISSUE TITLE
Decoy not working properly

### ISSUE THREAD

**Issue by PaladynMinak** [Regalis11/Barotrauma#6450] opened 2021-08-21 16:20 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Monsters ignore decoy before it's full duration, often just after few seconds.

**Steps To Reproduce**
Launch Depth Decoy Shell, spawn monsters and observe.

**Version**
v0.14.6.0 revision 12d7084c07 Windows 10 Pro

**Additional information**
I've tested it in editor and campaign, in configurations like 1 crawler, 1 spineling, 1 crawler and 1 spineling, 2 spinelings. I understand that decoy should attract monsters for its noise emitting duration. Or am I wrong? At first I thought spinelings exclusively ignore decoy after like 5 seconds, but later I discovered, that they can focus on it for much longer and if few monsters are present, each one goes away from it at different time. Common feature among all attempts was that always monsters were leaving decoy before it's full duration, based on it's noise still playing.

**Comment by Regalis11** [comment] 2021-08-23 10:25
I gave this a quick test and I'm not sure if there's actually anything wrong with the behavior. The decoy should attract monsters for the whole duration it's emitting noise, but that doesn't necessarily mean all the monsters will choose it as their primary target in all situations. Spinelings for instance are hostile to crawlers and the crawlers try to escape, and afaik it can be possible for the attack/escape state to "overpower" their desire to chase the decoy.

@itchyOwl maybe you could give this a test and see if it's working as intended since you know better how the targeting is intended to work?

**Comment by PaladynMinak** [comment] 2021-08-24 07:59
I'm not certain how this entire thing work, but I was researching files myself, to gain knowledge useful in creating own submarine concepts (e.g. I found and tested, that engines despite having large aitarget range, only 3 monsters in particular have set any reaction to them and it's "avoid" (4m radius from engine), so they're only escaping from that trigger, therefore contrary to popular belief, limiting thrust does nothing for attempts of stealthy passing). 
Crawler together with spineling was only one of many scenarios I tested. I observed, that's true that crawlers priority escaping from spinelings, if too close to them, over engaging decoy (on the other hand, decoy remained spineling's target, regardless of crawler's presence), but after escaped (20m), they went back to the decoy, too bad spineling was still near, what made loop such behavior, but it's irrelevant.

Anyway, after additional tests, with range net and actual timer measuring duration of decoy (oscillator pulse at 1 frequency to adder, which sum up value with memory, which is set to 0 by launching signal), I found that crawlers behavior is much more consistent, than I thought at first, but still, there are ones that, when in effective range of decoy (based on passed time (more context below)), are starting to attack sub.
Nonetheless spinelings are nightmare. I was spawning 10 spinelings at a time, about 10m from decoy and always about 7th second some of them starting to switch target to sub (or human inside, I don't know, but for whole situation it's irrelevant too, but technically it can matter), however some of them later were switching back to decoy, but there was always few staying on sub. I was testing with single spineling too and despite having double effective range from decoy (hearing 2), most of the time between 7-15th second it's switching to attack sub.

I made another test. I wanted to verify if "<AiTarget soundrange="15000"" from decoy would actually work up to 150m. 
It is, for monsters with hearing value 1. Spinelings (hearing 2) got attracted from even 300m and yes, charybdis (hearing 5) got attracted from 750m! So in fact decoy can be more harm than help, especially in closed environment, where it can pull to narrow passage such opponents like e.g. charybdis. I strongly suggest to reconsider this mechanic or at least make better explanation for players.
However full range is for like first second after launch (had to pause immediately after launch to spawn few monsters in such range) and then the range is diminishing with constant rate from 100% to none at the end of duration (sound can actually play like 3s after end of attract duration, because of sounds own duration and not being terminated with attract effect end).

Too be honest, I suspect "target tag="provocative"" to mess with decoy, because of what's the name suggest and from lack of other clues, but I don't really know how this target is supposed to work and how to test it, so I'm only guessing.

**Comment by itchyOwl** [comment] 2021-08-30 09:31
Some answers to @PaladynMinak :
- Decoys don't use the tag"provocative", which is used by underwaterscooters, divinggear, flares, flashlight etc.
- The monsters should reduce their targeting priority gradually when multiple of their kind are going for the same target. However, this behavior shouldn't apply to decoys.
- Decoys attract monsters, which can draw monsters from afar. True. I don't understand why this would go against the supposed behavior. Has it caused any issues, or were you just speculating? The abyss creatures won't target the decoy or any other target outside of abyss, unless they chase them from the abyss.
- The monsters won't normally target the engines, but the reactor, sonar, hulls (rooms), walls, and even the humans instead. The movement of creatures affects how visible they are, but 


![image](https://user-images.githubusercontent.com/5370738/131318111-8bcbe146-e9b8-459a-95a1-67dcdb67a953.png)

![image](https://user-images.githubusercontent.com/5370738/131318395-38d280f1-87db-42c3-ba96-6710604809b8.png)

**Comment by itchyOwl** [comment] 2021-08-30 09:36
But I'll it out and fix it if there's anything wrong.

**Comment by PaladynMinak** [comment] 2021-08-30 12:39
@itchyOwl Thank you for explanation.

Ad. 3. I thought of scenario where sub is using decoy to draw monsters' attention from it and escape from them. But with 30s duration for regular decoy and distances such as 300m or 750m, it would make monsters possible to be there, travel from afar to diminishing target, so before they even get close to decoy, which triggered their movement, they can encounter sub and already be outside of decoys range and even if not, decoy wont last long and they are pulled toward sub, what again, in narrow passages can be especially lethal. With my suggestion for better explanation, I wanted to let regular players, inside the game, know the such risks from using decoy, or what's more to my liking, reduce such risks.

About your screens - I understand that on first pic, biggest orange circle is sound from engine, smaller orange circle is sound from reactor, is that right? On second pic engine isn't working so have no sound range, but what red circle is for? And that ranges are for perception value of 1, so e.g. hammerhead would have it double for sound? Good you mentioned that movement is enlarging detection range. I checked it with full thrust, locked sub near charybdis' circle - nothing, then after unlocking sub - instant reaction. So not engine's thrust, but actual sub's speed is what matter? Then for faster subs, making some throttle could make sense.

About monsters behavior. With aitargests I have new observations. I made tests with 2 spinelings. With target 'avoid', monster can still follow sub. Sometimes both of them, when in engine range, are avoiding, till out of range, then they're back to idle, but sometimes, they ignore engine and keep attacking. Same with decoy.
![20210830142619_1](https://user-images.githubusercontent.com/58741172/131339770-607acf4b-44bb-4643-8ab2-1a3d8819c970.jpg)
![20210830143313_1](https://user-images.githubusercontent.com/58741172/131339776-a5b98765-6764-4245-b9c7-9b713387f920.jpg)
![20210830143343_1](https://user-images.githubusercontent.com/58741172/131339781-cbf2cb45-31d8-41ed-bfbc-25772ba8e350.jpg)

**Comment by MateusJK15** [comment] 2021-08-30 14:41
Maybe a bit off topic, but this is something i don't like about this game, there's no way to avoid combat, even if you move slowly trying to make less noise, monsters can still see you, even if there's no light source allowing them to see something. And even if they depended only on their hearing to detect you, the sonar display and the passive sonar detection range are too small to allow the player to detect enemies before being detected (even the big ones that displaces lots of water), so it's impossible for the player to detect a monster and try to pass by it while staying away from it's detection range, thus making passive sonar useless.

**Comment by itchyOwl** [comment] 2021-09-03 22:08
The red circle is the sound of the hull. The reactor and the engine make the hull emit sound, and most creatures also target hulls. So steering affects how audible the sub is. And the actual velocity affects how visible the walls/hulls are. 

I'm not sure I follow, but as the engine's perception range was quite large, the monsters probably targeted the engine, if they couldn't perceive anything more important. If they use avoid, they would use the react distance (unless you removed it), which would make it seem like they would try to avoid the engine, where as in the practice they would actually just idle around the sub.

I adjusted the perception ranges and the fade off durations for the decoy so that they should start less perceptible and last longer now. See Regalis11/Barotrauma-development@991fb31.

@MateusJK15, good that you mentioned that. In the past, the monsters instantly forgot their target if they lost it. Now they should try to find it again. Having the memory of a fish, shorter perception ranges didn't work at all, because monsters also used to always fall back after attacking. So they attacked, returned, and then would lose their target.

That shouldn't happen anymore, so shorter perception ranges are now possible. The wall ranges are actually not visible in that image. Those blue circles are irrelevant, since they stand for items that the monsters shouldn't target if they are inside submarine. I lowered the min wall and hull perception ranges from 2000 to 1000, and door set door ranges to 1000 (static), which looks like this (the visibility ranges of hulls and walls are normally disabled, because they clutter the debug view, as you can see).

Here's stationary Humpback with the new ranges:
![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/0397ace2-2bbe-4b43-b98b-8fad78550f6f)

Here's roughly half speed:
![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/159e2e45-37be-42ef-b427-dc85947cf172)

And here's full speed:
![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/0e99d29e-b7e3-4f0c-a754-951b93a8121f)

Passive sonar isn't useless because the sonar has a huge aural footprint, which attracts monsters, especially molochs that are blind and barely notice the sub otherwise (they can hear the reactor humming though):
![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/e57b5747-91b4-43c9-b24e-2be317157804)

I noticed that hull max sound range was clamped to 5000, which is why those red circles (that matter) were smaller than orange. I fixed that and I also adjusted the perception ranges of the engines and the reactor and changed some calculations. These changes are implemented in  Regalis11/Barotrauma-development@90795e2. Also adjusted the abyss monster perception ranges in Regalis11/Barotrauma-development@fd142bf, which might make the abyss monsters more interesting. Please give them a test and tell me if it's any better now. I didn't have much time for testing.

The final ranges I ended up might not be exactly as depicted above, but the images should give some insight to the new perception ranges. In overall moving faster should now create more noise, but staying stationary should make you less visible. The aim is to make stealthy approach possible.

**Comment by MateusJK15** [comment] 2021-09-03 23:21
Are these changes already in the game ?

**Comment by MateusJK15** [comment] 2021-09-03 23:29
Regarding the sonar interface, a bit more of zoom out would be nice.

**Comment by PaladynMinak** [comment] 2021-09-04 02:47
@itchyOwl 
I'll check soon.

Btw, as MateusJK15 already asked, I'm guessing that these changes are on unstable right now and are being implemented to standard game with larger patches?

Sorry, but I'm not any good with programing or game development and just started using github. I was just trying to make my own sub and to it be something pleasant, versatile and well thought, so I started gathering knowledge how the game works, what eventually brought me here. You mentioned "Regalis11/Barotrauma-development@90795e2", where should I look for it?

**Comment by PaladynMinak** [comment] 2021-09-05 04:50
So I've made few tests on unstable, with sub from previous screens (slightly modified, but same nav, engine and maybe 0,5m difference in size). Staying stationary made endworm target sub from ~150m. With 7km/h x velocity endworm targeted sub from ~330m, but with 53 km/h x velocity, he targeted sub, again, from ~330m, so I think something may not work as intended. To specify im using shuttle terminal, engine and shuttle walls, plus window top and vertical. I haven't modified any game files, just been reading some of them. 
Still, I don't know if should I look for mentioned changes on unstable version or where?

You said earlier


> * The monsters should reduce their targeting priority gradually when multiple of their kind are going for the same target. However, this behavior shouldn't apply to decoys.


Well I don't know what, but something is making avoid engine more important than focus decoy, for spinelings especially.
![20210905061018_1](https://user-images.githubusercontent.com/58741172/132115289-3437a1bc-6c85-44c5-aa99-001ce5630503.jpg)
![20210904231206_1](https://user-images.githubusercontent.com/58741172/132115411-7235491c-45ed-4d79-8f1d-78dace648721.jpg)


About abyss monsters, 30s decoy is too short to make enough distance, even on, comparing to vanilla, pretty fast shuttle (slightly above 50 km/h), even for just making minimal distance and stopping in place, to lower detectability of sub, which have lower noise than standard subs, so what about ones like them? Maybe 60s duration would be better, if it would be for ones like charybdis or endworm.

**Comment by itchyOwl** [comment] 2021-09-06 06:33
The changes are not yet in any release version. We'll do changes in the private development branch, which will then be used to build the next unstable version. The links I posted are only meant for us to track the changes. Unfortunately you can't see the commit here. (So it'll be in the next unstable (possibly the end of this week, but not certain).

About the decoys: the changes I made were to increase the fadeout time from 30 to 50 and to decrease the range from 15000 to 10000.

**Comment by itchyOwl** [comment] 2021-09-06 06:37
I think it's intentional that the sonar range is what it is (around 10000 pixels in max zoom). I don't feel that we should change it, and even if I did, it's not up to me to do that.

**Comment by itchyOwl** [comment] 2021-09-06 06:37
That picture about spinelings is good. I'll try to figure out what's happening there.

**Comment by itchyOwl** [comment] 2021-09-06 08:04
Hmm. I was able to repro a case where one spineling targeted a wall instead of the decoy when others went for the decoy. Wasn't the swarming thing, as I tried to disable that part of the code. Unfortunately, before I managed to trace it down, the decoy weared off. So I couldn't catch the cause for the behavior. And then I wasn't able to repro it anymore even though I tried a number of times. I suspect that there's some edge case there, but I don't think it happens too often to constitute a true issue. In general the decoys should attract most of the creatures anyway.

I unified the priorities for most monsters and thus increased the priority also for spinelings (200->500), which might help. Although I doubt it, because as we can see in your picture, the issue is not with the priorities. It's that one of the spinelings ignore the decoy for some reason.

![image](https://user-images.githubusercontent.com/5370738/132173300-7de21c83-fea7-4ba3-807e-630bd69e88d4.png)

![image](https://user-images.githubusercontent.com/5370738/132178882-9c2db051-9de5-4677-b70e-59e3e16ae00e.png)

**Comment by PaladynMinak** [comment] 2021-09-06 21:20
When next unstable comes I'll check it all out, I'll try with maybe few different subs, just in case and I'll try to figure steps to reproduce, if issue would still occur. With changes you applied it may be as you say, for currently released version I expect same results as before.

By the way, what does mean "Attack" in orange instead of red color? And those numbers in parentheses after target id?

**Comment by itchyOwl** [comment] 2021-09-07 09:58
The number in parentheses is the final  priority of the target, affected by distance and other dynamic parameters.

Attack in orange in that context means that the attack is on cooldown state. Orange is also used to show the wall targets, when the creature is targeting something inside the sub that gets blocked by the walls. In that case the creature attacks the walls instead of the actual target.

**Comment by PaladynMinak** [comment] 2021-09-13 10:15
So, I really like change in how detection works now, that if someone disable reactor and stay still, or go very slowly on batteries, can even pass charybdis from 30m. However I found that it's not velocity what determines detection range, but rather engine thrust, because I compared same sub with different engine power values. At around 10% thrust charybdis could target me from ~100m, but at 100% even from 400m. On default humpback, 10% thrust allows him achieve eventually 8km/h and 100% allows 28km/h. But when I quadrupled it's engine force, it could achieve around 20 km\h at 10% thrust and charybdis was detecting sub from same distance like when it was moving much slower on weaker engine.

I think that dynamic range should base on actual sub velocity compared to sub's size, with some caps maybe. So smaller subs and shuttles could go faster unnoticed and larger ones would be more noticeable the faster they go, regardless of their engines.

Returning to decoys, first I made tests with my own shuttle and there was issue, so I just added depth charge set to humpback, to check if it's specific to my creation. It's not.

Definitely monsters behavior is much better than before. The strange thing is, that when I was testing spinelings, one (even if there are 10 or if it's alone) almost always is switching to sub and later switching back to decoy, but only one. 

![20210913114225_1](https://user-images.githubusercontent.com/58741172/133064516-97698a42-03bc-44a6-b08b-5ca8b63d10de.jpg)
![20210913114233_1](https://user-images.githubusercontent.com/58741172/133064549-07d31b20-33e3-49ea-812e-372d87e42f8d.jpg)
![20210913114246_1](https://user-images.githubusercontent.com/58741172/133064654-a358b0fa-e9f6-4025-bc55-67f23fde2211.jpg)
![20210913114251_1](https://user-images.githubusercontent.com/58741172/133064676-f8a36614-cd06-4a8f-b4c8-a12c075424cb.jpg)

At some point I thought it may be specific to spinelings, but once when I spawned 10 crawlers, I've noticed 1 latched onto shell and stayed there pretty long, to eventually target back almost expired decoy, but it was pretty unique accident. 

![20210913113506_1](https://user-images.githubusercontent.com/58741172/133065888-a0db3d9d-f8bc-4036-9665-8876a0dc7868.jpg)

Another unique accident was, when I've seen 1 of 10 spinelings, instead of actually targeting sub, switched to idle, then to sub.

![20210913120402_1](https://user-images.githubusercontent.com/58741172/133065416-2a481336-4433-4122-82ff-9f27cdeb1036.jpg)
![20210913115308_1](https://user-images.githubusercontent.com/58741172/133065425-b2656ef7-9a2d-4168-88ed-6e2d531250c3.jpg)
![20210913120409_1](https://user-images.githubusercontent.com/58741172/133065440-df7eac15-3720-405a-8e43-26e858a73c11.jpg)

**Comment by itchyOwl** [comment] 2021-09-13 15:44
The velocity only affects how visible the sub is, engine thrust affects how much noise the sub makes. I changed the abyss monsters to have very good hearing and only average vision (in relative to their size). So maybe that explains it. And maybe there's still room for tweaking...

The decoy's ai target now fades completely away slightly after the noise has ended. The sound is technically speaking separate from the ai target's lifetime, but I think it now work ok, as it's pretty natural that the monsters keep the interest to the target for a few seconds even when it's gone mute.

But there's definitely some minor issue with the decoys still, because none of those spinelings should target the sub and ignore the decoy there. It's not a huge issue anyway, but maybe we'll find the cause of it eventually and fix it.

**Comment by Rokvach** [comment] 2021-10-17 00:06
I haven't seen any issues with the decoys, seems  to be fine. Closing.

**Closed by Rokvach** 2021-10-17 00:06 UTC
Labels: Bug, Needs testing, Code
