### ISSUE TITLE
Crowbars Don't Work When Action is Cancelled

### ISSUE THREAD

**Issue by Cory-Corrigodone** [Regalis11/Barotrauma#2638] opened 2020-04-16 17:35 UTC
- [✓] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Attempting to open a door with the crowbar and having the door open before the action has finished causes the crowbar to become unusable. 

**Steps To Reproduce**
Use the crowbar on a door and have someone open it, the crowbar will be unable to open any doors. Haven't tested if equipping a new crowbar fixes this. 

**Version**
~0.9.8.0

**Comment by Regalis11** [comment] 2020-04-17 12:24
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/64d1a903608b05c1e0957656067be07bc062953f

**Comment by kuzyxp** [comment] 2020-04-23 17:17
> 
> 
> Fixed in [Regalis11/Barotrauma-development@64d1a90](https://github.com/Regalis11/Barotrauma-development/commit/64d1a903608b05c1e0957656067be07bc062953f)

But why u dont close this issue?

**Comment by Rokvach** [comment] 2020-04-23 17:48
Still needs to be tested

**Comment by KuzyXD** [comment] 2020-04-24 02:39
@Rokvach if i test this issue and prove that. Then you will close that issue?

**Comment by KuzyXD** [comment] 2020-04-24 04:53
Did not work with button-to-open-door doors.

https://giphy.com/gifs/H67iX4lWPrdkCyXqXn

**Comment by Regalis11** [comment] 2020-04-24 09:14
@kuzyxp The fix has not been included in the public version yet.

The way we handle bugfixes is that we test them internally, and only when we've verified the fix is working, close the ticket and include the fix in the public versions. So let's keep this open for the time being!

**Comment by KuzyXD** [comment] 2020-04-24 11:23
@Regalis11 glad to read your answer. I in love with that game. And i know C# a little. How can i contribute?

- [✓] I already read your guide.

- [ ] How to identify what issue you already fixed?

**Comment by Regalis11** [comment] 2020-04-26 18:46
Thank you for the offer! We generally avoid including user-written pull requests or code in the game, because there's a (low but real) chance it could lead to legal complications. Even though our EULA states that if you submit code for us to use in the game, you're giving us the right to use that code as we see fit, we don't want to run into a situation where someone accuses us of taking advantage of their work.

If you do want to help though, something that can be very useful (and less of a legal minefield) is trying to help us diagnose bugs. There are tons of bug reports in the issue tracker that we either haven't had time to look into, or haven't been able to reproduce or fix yet, and if someone outside the dev team manages to find a way to reliably reproduce the issue or even spots a problem in the code, it can help us get it fixed much faster.

In general, you can tell that an issue hasn't been fixed yet if the issue report is still open and there are no comments about it being fixed.

**Comment by Rokvach** [comment] 2020-05-04 12:04
No issues, closing.

**Closed by Rokvach** 2020-05-04 12:04 UTC
Labels: Bug, Code
