### ISSUE TITLE
Npcs spawning without clothes (Turkish Player)

### ISSUE THREAD

**Issue by Varangianoi** [Regalis11/Barotrauma#9138] opened 2022-05-14 18:08 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Hello, I'm Turkish. Can you add this fix to the stable version? I don't want to switch to the unstable one, and all my friends are tired of seeing naked npcs and bandits...

I couldn't find any bug report about this, so I think it's okay for me to make this one.

![unknown](https://user-images.githubusercontent.com/75825361/168443355-8511f1c0-e8e8-48dc-a3af-ee28f8e361d2.png)

### Reproduction steps

1. Live in Turkey
2. Play Barotrauma

### Bug prevalence

Happens every time I play

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-05-16 05:51
Duplicate of https://github.com/Regalis11/Barotrauma/issues/8887

**Closed by Regalis11** 2022-05-16 05:51 UTC

**Comment by Varangianoi** [comment] 2022-05-22 20:22
Hello, I think it's important to fix this in the stable version rather than closing it. Other wise, Turkish players always have to play with naked NPCs and pirates in the stable one. The duplicate you linked was closed by another developer I guess.

https://github.com/Regalis11/Barotrauma/issues/8887
