### ISSUE TITLE
Exception when leaving station in MP, server browser overlays with summary panel

### ISSUE THREAD

**Issue by ralfbiedert** [Regalis11/Barotrauma#9031] opened 2022-05-01 15:14 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
With the latest patch the first time I've left a station I in MP receive an exception in coroutine `Barotrauma.Networking.GameClient+<StartGame>` that looks like so:

![Screenshot_5 - Copy](https://user-images.githubusercontent.com/301288/166152139-337e809e-363d-4b90-9a88-442dd70520f0.png)

Along with some `SteamAPICallCompleted` and `LobbyMatchList` entries. Interestingly it also overlays the Summary screen with parts of the server browser, and neither of the UI elements was clickable. The only input that worked was F3, which rendered the debug console behind the other panels. I ultimately had to Alt-F4 to leave the game.

**Update** - I just realized the server browser popped up, not the lobby, which is even weirder as I was hosting.

**Version**
`0.17.15.0`

**Comment by Ek-Videogames** [comment] 2022-05-01 17:46
Cleaned up the obscured error message somewhat. It ends with _"object reference not set to an instance of an object"_ 
which suggests this is not a duplicate of #8880 / #8971 / #8960 but a different issue

![image](https://user-images.githubusercontent.com/55356135/166157916-fc045944-e059-4362-9112-58f1c74ec470.png)

**Comment by Regalis11** [comment] 2022-05-02 09:12
Duplicate of https://github.com/Regalis11/Barotrauma/issues/9016

**Closed by Regalis11** 2022-05-02 09:12 UTC
Labels: Bug, Code, Networking
