### ISSUE TITLE
PUCS Drain oxygen when in a oxygenated room

### ISSUE THREAD

**Issue by Inrixia** [Regalis11/Barotrauma#7773] opened 2021-12-15 09:50 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
According to the [wiki ](https://barotraumagame.com/wiki/PUCS) `The PUCS will not drain oxygen while In an oxygenated room`. However when wearing one in a oxygenated room my O2 tank is still depleting.

**Steps To Reproduce**
Equip a PUCS diving suit, place a O2 tank in the suit, stand in a oxygenated room, the tank should lose O2.

**Version**
Window 10, v0.15.13.0, 4e66dd7b5d

**Comment by Regalis11** [comment] 2021-12-15 10:03
Duplicate of #7104

**Closed by Regalis11** 2021-12-15 10:03 UTC
