### ISSUE TITLE
Tigerthresher Crashes Game!

### ISSUE THREAD

**Issue by NoMoreRush** [Regalis11/Barotrauma#10399] opened 2022-11-14 22:35 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Large amound of tigertreshers among with bones attacing a submarine crashes the server almost without fail.

### Reproduction steps

1.Start/continue Multiplayer campaign
2.face a large Tigerthresher swarm
3.tigerthreshers have contact with the sub
4.session crash

### Bug prevalence

Happens every time I play

### Version

0.20.6.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
The server has crashed: servercrashreport (9).log||
Object reference not set to an instance of an object. (NullReferenceException)    at Barotrauma.EnemyAIController.UpdateLimbAttack(Single deltaTime, Vector2 attackSimPos, IDamageable damageTarget, Single distance, Limb targetLimb) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\EnemyAIController.cs:line 2147
   at Barotrauma.EnemyAIController.UpdateAttack(Single deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\EnemyAIController.cs:line 1891
   at Barotrauma.EnemyAIController.Update(Single deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\EnemyAIController.cs:line 441
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2929
   at Barotrauma.GameScreen.Update(Double deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 195
   at Barotrauma.GameMain.Run() in E:\Barotrauma-development\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 325
   at Barotrauma.Program.Main(String[] args) in E:\Barotrauma-development\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 78
```

**Comment by NoMoreRush** [comment] 2022-11-14 22:39
i know someone reported something similar but they did not have the crash report so here it is

**Comment by Regalis11** [comment] 2022-11-15 08:27
Duplicate of https://github.com/regalis11/barotrauma/issues/10249

**Closed by Regalis11** 2022-11-15 08:27 UTC
