### ISSUE TITLE
Can't save item assemblies

### ISSUE THREAD

**Issue by NicolaruS** [Regalis11/Barotrauma#2846] opened 2020-05-16 14:32 UTC
[0.9.10.0]unstable. When you create a drawing (assembly), the console opens with an error.

**Comment by NicolaruS** [comment] 2020-05-16 14:33
Even from one detail.

**Comment by Udrakan** [comment] 2020-05-16 16:36
![image](https://user-images.githubusercontent.com/59519434/82125131-22a6aa00-97a4-11ea-9889-c30f8208c19e.png)
 I got this error when trying to save an assembly.

**Comment by Udrakan** [comment] 2020-05-16 16:37
STR:
-go to sumbarine editor
-place anything
-try to save it as assembly
-error should popup and the assembly doesn't save

**Comment by Regalis11** [comment] 2020-05-17 13:25
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4c8b711290acdb8510fc3a7fd294eec4bfddf345

**Comment by Rokvach** [comment] 2020-05-17 22:47
Couldn't reproduce, working correctly. Closing.

**Closed by Rokvach** 2020-05-17 22:47 UTC
Labels: Bug, Code, High prio
