### ISSUE TITLE
New players cannot join when in port with missions selected

### ISSUE THREAD

**Issue by demiurgeQuantified** [Regalis11/Barotrauma#11469] opened 2023-03-07 19:21 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When in port, between selecting your missions and departing, when new players try to join they receive an error message and can't join.

### Reproduction steps

1. Start a multiplayer campaign
2. Arrive in a station
3. Select your next missions, but don't depart
4. New players will not be able to join

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Error while reading a message from server.
Mission equality check failed. Mission count doesn't match the server. Server: , client: killhammerhead, game session: killhammerhead)
```

**Comment by Regalis11** [comment] 2023-03-07 19:33
Duplicate of https://github.com/regalis11/barotrauma/issues/10497

**Closed by Regalis11** 2023-03-07 19:33 UTC
