### ISSUE TITLE
[0.9.7.1] Missing Entity

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2382] opened 2020-03-01 20:56 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Missing entity at the start of campaign round. Unable to rejoin.
[Serverlogs.zip](https://github.com/Regalis11/Barotrauma/files/4272426/Serverlogs.zip)

Go to Cadmus Linea Mining Claim with Killing a Matriarch mission.
[Barotrauma.zip](https://github.com/Regalis11/Barotrauma/files/4272431/Barotrauma.zip)

**Version**
0.9.7.1

**Comment by Regalis11** [comment] 2020-07-06 11:06
The previous 2 reports may have been caused by https://github.com/Regalis11/Barotrauma-development/commit/8261971 or https://github.com/Regalis11/Barotrauma-development/commit/a0e92cd77ff9c12e84e3bbab5207f63c56af86ec, let's see if those fixes make a difference

**Comment by Regalis11** [comment] 2020-07-15 14:05
Found yet another cause for this, that specific bug should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/a461a54fc4b306affae1a9ae126da49cbd54f340

Steps to repro:
1. Start a non-campaign round
2. Kill yourself and wait for a respawn (or use "respawnnow")
3. Make some holes in the shuttle walls
4. Leave the shuttle and wait for it to despawn
5. Do something that creates/removes entities, for example fire a ranged weapon

Moving to QA, let's wait for this to go out in a patch and see if we still get reports about this

**Comment by Kaillera** [comment] 2020-07-18 20:18
[crashreport_object.log](https://github.com/Regalis11/Barotrauma/files/4942414/crashreport_object.log)

ENTITY_POSITION, Index was outside the bounds of the array.

**Comment by Lefttroll** [comment] 2020-07-18 20:24
[crashreport_object.log](https://github.com/Regalis11/Barotrauma/files/4942419/crashreport_object.log)
while trying to start server with 8 players this will crash game

**Comment by Regalis11** [comment] 2020-09-03 12:16
Found yet another cause for these: Regalis11/Barotrauma#3680

Moving to QA backlog, let's see how long it takes before we run into this again...

**Comment by Rokvach** [comment] 2020-09-10 09:17
There hasn't yet been any sightings of reported cases since this issue has been fixed

**Comment by Kaillera** [comment] 2020-09-10 10:32
Actually I had it happened last night. Host loaded a 0.10.4 campaign into unstable and it happened some times in the level after we left the outpost

**Comment by Rokvach** [comment] 2020-09-10 10:38
I wouldn't ever trust a old save, there can be a lot of things that might be broken just because of it

**Comment by Kaillera** [comment] 2020-09-10 21:57
[Multiplayer.zip](https://github.com/Regalis11/Barotrauma/files/5204827/Multiplayer.zip)

Here's an entity issue for 0.10.504. There were 2/3 of us at the time of this save file and it was always kicking one of us out.

Take over Kaillera, Jade Harley, and/or Flamatter and load this save file.

**Comment by Regalis11** [comment] 2020-09-11 07:31
I'm afraid I couldn't repro the issue. Tested by taking over each of the characters, and also by converting them to bots. 

Also, the log file seems to imply this wasn't a "missing entity" error, the error message is "Index was out of range. Must be non-negative and less than the size of the collection" so I think it's related to https://github.com/Regalis11/Barotrauma/issues/3019.

**Comment by Kaillera** [comment] 2020-09-11 12:05
Not sure if it's a memory leak or something, because closing the entire server that was running for over 6 hours and then reloading the save stopped it from happening.

**Comment by Leonidas-ai** [comment] 2021-02-01 17:29
[crashreport_object (1).log](https://github.com/Regalis11/Barotrauma/files/5905572/crashreport_object.1.log)

**Comment by Rokvach** [comment] 2021-03-31 05:50
Now days I've mainly seen missing entity issues only on new added features in Unstable builds which then were fixed before the Stable build was made, so not fully sure if this is still required to be kept open

**Comment by Krzeszny** [comment] 2021-05-06 23:12
It kept happening to me when I was joining a server with my mods enabled, but it stopped when I disabled all my mods. It was about a missing mineral.

**Closed** 2021-08-17 12:29 UTC
Labels: Bug, Code, Networking, High prio, Waiting
