### ISSUE TITLE
moving blue pattern at top of screen

### ISSUE THREAD

**Issue by internet-person** [Regalis11/Barotrauma#8082] opened 2022-01-22 22:50 UTC
i have not seen any reports of this issue.

**Description**
when you can see water outside the sub from the inside the top few pixels turn blue in a nonstatic pattern.

i got another person to check and they also see the pattern, as such i dont think this is a computer specific issue.

the blue pattern moves along with the player camera, as such its nearly always moving.

it does not seem to happen when outside the submarine.

**Steps To Reproduce**
open editor, load kastrull, stand near cockpit class, move mouse a bit and look at the top few pixels of screen.

**Version**
0.15.23.0 windows 10

**Additional information**

it doesnt show up in pictures or video very well, but i got a fairly good picture.

![weird blue](https://user-images.githubusercontent.com/81054892/150657584-d000bd7a-1fad-4af1-b097-722e427ba97f.PNG)

**Comment by Regalis11** [comment] 2022-01-24 14:22
Duplicate of https://github.com/Regalis11/Barotrauma/issues/2837

**Closed by Regalis11** 2022-01-24 14:22 UTC
Labels: Bug, Code, Low prio
