### ISSUE TITLE
Crash starting game after editing and saving a submarine

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#2311] opened 2020-02-15 09:25 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
"I got a weird crash in unstable... I edited and saved a submarine and next time I try to run the game, it crashes"

```
Exception: An item with the same key has already been added. Key: Mods/BTE/Submarines/Bunyip II.sub (System.ArgumentException)
Target site: Void ThrowAddingDuplicateWithKeyArgumentException[T](T)
Stack trace: 
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Barotrauma.Md5Hash.LoadCache() in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Map\Md5Hash.cs:line 24
   at Barotrauma.GameMain..ctor(String[] args) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 196
   at Barotrauma.Program.Main(String[] args) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 40


Last debug messages:
[15-02-2020 0:17:05] Errors found in content package 'BTE'; some of its features may not work correctly.
[15-02-2020 0:17:05] Loaded languages: English
[15-02-2020 0:17:05] Errors found in content package "BTE": File "Mods/BTE/Submarines/Orca II.sub" not found.
```

My guess is somehow, two of the same submarine file exists - noting this is a windows machine it is rather unusual so I am making the assumption its in a mods folder or both downloaded and base directory of submarines Or its trying to hash / add its hash twice?.

**Steps To Reproduce**
Unknown.

**Version**
0.9.7.0 unstable latest build - windows client.

**Additional information**
Original crash report:
[crashreport_4.log](https://github.com/Regalis11/Barotrauma/files/4208266/crashreport_4.3.log)

**Comment by Rokvach** [comment] 2020-02-15 12:10
I was able to reproduce this,

- Create a copy of a vanilla sub
- Publish it to workshop
- Open submarine on editor and save it again
- Try to launch the game, crashes on startup until the submarine has been deleted

@Regalis11

**Comment by ChikoEduardo** [comment] 2020-02-15 14:27
I had no other copy of the submarine. It just happened after I edited it and saved then quit and tried to run the game. The submarine was in a submarine folder inside the mod.

**Comment by Regalis11** [comment] 2020-02-15 23:11
I may have found the cause for this. Related to #2277, there seem to be several flaws in the way the game caches the MD5 hashes of the files (meaning that it saves the calculated hashes into a file so it only has to recalculate the hash if the file has been changed).

The system doesn't seem to be working correctly in all cases at the moment, but until we release a fix, you may be able to work around the issue by going to the Data folder inside the game folder and deleting a file called "hashcache.txt".

**Comment by Rokvach** [comment] 2020-02-16 18:28
Tried to reproduce the issue by doing exactly what I did previously, couldn't get the game to crash and didn't notice any other issues while testing it.

**Comment by Rokvach** [comment] 2020-02-19 17:50
Tested, couldn't reproduce the issue anymore. Closing.

**Closed by Rokvach** 2020-02-19 17:50 UTC
Labels: Bug, Code, Crash, High prio
