### ISSUE TITLE
Can't join a server until a round ends (Received an update for an entity that does not exist (event id 1511, entity id 65280))

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#9092] opened 2022-05-08 21:25 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I kept trying to join a specific server and each time (5 tries) have been getting the same errors. 
I restarted the game 3 times, too.
I stopped crashing to main menu presumably after the round ended. I've been playing for half an hour and it's ok for now.

### Reproduction steps

1. Join a server
2. Click Spectate
3. ???
4. 
![wvF2CgVGfs](https://user-images.githubusercontent.com/10529134/167316530-695a224e-dfca-4ea3-8448-4bbfcb2e77f7.png)

Mods:
![Barotrauma_s9PB4xG5ga](https://user-images.githubusercontent.com/10529134/167315689-a9a9694f-3115-43b1-acd2-721a3e4f4f57.png)

![Barotrauma_d4O43qEvjX](https://user-images.githubusercontent.com/10529134/167316456-3ab55080-f842-49ea-86b5-eecbb584d368.png)
![Barotrauma_FbEau3HKa0](https://user-images.githubusercontent.com/10529134/167316458-5f256a57-d424-459d-ac73-09f68da44749.png)
![Barotrauma_SvkeNMeMuz](https://user-images.githubusercontent.com/10529134/167316461-a02d0ebb-ff1c-4c53-a613-e8f306a0e8c1.png)

### Bug prevalence

Happens every now and then

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports
All the 3 reports I had were exactly the same, only the minutes are different.
**Server log file**
https://drive.google.com/file/d/119aEKnjCE_92hpHw8j4k1qFYV1P9OsWd/view?usp=sharing

Example from the above log file:
```shell
 debug messages:
   5/8/2022 10:44:45 PM - Failed to read event 1292 for entity "Lever (ID: 4295)", id 4295  {Index was outside the bounds of the array.}
   at Lidgren.Network.NetBitWriter.ReadByte(Byte[] fromBuffer, Int32 numberOfBits, Int32 readBitOffset) in E:\Barotrauma-development\Libraries\Lidgren.Network\NetBitWriter.cs:line 41
   at Lidgren.Network.NetBitWriter.ReadUInt16(Byte[] fromBuffer, Int32 numberOfBits, Int32 readBitOffset) in E:\Barotrauma-development\Libraries\Lidgren.Network\NetBitWriter.cs:line 229
   at Barotrauma.Networking.MsgReader.ReadUInt16(Byte[] buf, Int32& bitPos)
   at Barotrauma.Items.Components.ConnectionPanel.ClientEventRead(IReadMessage msg, Single sendingTime)
   at Barotrauma.Item.ClientEventRead(IReadMessage msg, Single sendingTime)
   at Barotrauma.Networking.ClientEntityEventManager.Read(ServerNetObject type, IReadMessage msg, Single sendingTime, List`1 entities)
   5/8/2022 10:44:45 PM - Failed to read event 1291 for entity "Light Component (ID: 5990)", id 5990  {Index was outside the bounds of the array.}
   at Lidgren.Network.NetBitWriter.ReadByte(Byte[] fromBuffer, Int32 numberOfBits, Int32 readBitOffset) in E:\Barotrauma-development\Libraries\Lidgren.Network\NetBitWriter.cs:line 41
   at Lidgren.Network.NetBitWriter.ReadUInt16(Byte[] fromBuffer, Int32 numberOfBits, Int32 readBitOffset) in E:\Barotrauma-development\Libraries\Lidgren.Network\NetBitWriter.cs:line 229
   at Barotrauma.Networking.MsgReader.ReadUInt16(Byte[] buf, Int32& bitPos)
   at Barotrauma.Items.Components.ConnectionPanel.ClientEventRead(IReadMessage msg, Single sendingTime)
   at Barotrauma.Item.ClientEventRead(IReadMessage msg, Single sendingTime)
   at Barotrauma.Networking.ClientEntityEventManager.Read(ServerNetObject type, IReadMessage msg, Single sendingTime, List`1 entities)
   5/8/2022 10:44:45 PM - Failed to read event 1290 for entity "Wifi Component (ID: 2073)", id 2073  {Index was outside the bounds of the array.}
   at Lidgren.Network.NetBitWriter.ReadByte(Byte[] fromBuffer, Int32 numberOfBits, Int32 readBitOffset) in E:\Barotrauma-development\Libraries\Lidgren.Network\NetBitWriter.cs:line 41
   at Lidgren.Network.NetBitWriter.ReadUInt16(Byte[] fromBuffer, Int32 numberOfBits, Int32 readBitOffset) in E:\Barotrauma-development\Libraries\Lidgren.Network\NetBitWriter.cs:line 229
   at Barotrauma.Networking.MsgReader.ReadUInt16(Byte[] buf, Int32& bitPos)
   at Barotrauma.Items.Components.ConnectionPanel.ClientEventRead(IReadMessage msg, Single sendingTime)
   at Barotrauma.Item.ClientEventRead(IReadMessage msg, Single sendingTime)
   at Barotrauma.Networking.ClientEntityEventManager.Read(ServerNetObject type, IReadMessage msg, Single sendingTime, List`1 entities)
   5/8/2022 10:44:45 PM - Failed to read event 1270 for entity "Wifi Component (ID: 6480)", id 6480  {Index was outside the bounds of the array.}
   at Lidgren.Network.NetBitWriter.ReadByte(Byte[] fromBuffer, Int32 numberOfBits, Int32 readBitOffset) in E:\Barotrauma-development\Libraries\Lidgren.Network\NetBitWriter.cs:line 41
   at Lidgren.Network.NetBitWriter.ReadUInt16(Byte[] fromBuffer, Int32 numberOfBits, Int32 readBitOffset) in E:\Barotrauma-development\Libraries\Lidgren.Network\NetBitWriter.cs:line 229
   at Barotrauma.Networking.MsgReader.ReadUInt16(Byte[] buf, Int32& bitPos)
   at Barotrauma.Items.Components.ConnectionPanel.ClientEventRead(IReadMessage msg, Single sendingTime)
   at Barotrauma.Item.ClientEventRead(IReadMessage msg, Single sendingTime)
   at Barotrauma.Networking.ClientEntityEventManager.Read(ServerNetObject type, IReadMessage msg, Single sendingTime, List`1 entities)
```

**Comment by Regalis11** [comment] 2022-06-29 15:01
Most likely a duplicate of https://github.com/regalis11/barotrauma/issues/9332

**Closed by Regalis11** 2022-06-29 15:01 UTC
Labels: Bug, Code, Networking
