### ISSUE TITLE
npc crew killing themselves getting stuck in walls

### ISSUE THREAD

**Issue by zombiedragon8090** [Regalis11/Barotrauma#7277] opened 2021-11-12 16:31 UTC
somehow my crew get themselves stuck in walls of my sub and die and they kill themselves in the ballast I'm starting to hate this game it's only the mechanics that are doing this

**Comment by Regalis11** [comment] 2021-11-15 13:19
Thank you for the report!

Does this happen in some specific submarine(s)? I could imagine misplaced waypoints in some custom sub to cause issues like this - or does it happen in vanilla submarines as well? Do you know how exactly die (i.e. what's the cause of death listed in the round summary)? Sorry for the trouble, this does sound very frustrating and I hope we can get rid of the issue asap. :/

**Comment by zombiedragon8090** [comment] 2021-11-16 16:14
Remora sub drowning it started happening after upgrading my junction boxes
the mechanics al started to act abnormal

**Comment by Regalis11** [comment] 2022-01-10 13:03
No known steps to repro, closing

**Closed by Regalis11** 2022-01-10 13:03 UTC
Labels: Bug, Need more info, Code
