### ISSUE TITLE
constant set_color being ignored when lamp color is manually changed

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#11658] opened 2023-03-25 16:27 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

manually changing a lamp's color with screwdriver/interface will change the color, but if the light has a constant input into its set_color, the set_color is ignored.

it's expected that a constant set_color will override manual color change attempts

### Reproduction steps

1. wire a memory with value (i.e., 255,1,1,255) into a lamp
2. enter test mode
3. screwdriver and change the light color (i.e., 1,255,1,255)
4. light color is now the screwdriver's color
5. (change memory value to a new color and the light will change) 

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment] 2023-03-28 13:32
Unsure if this works as intended or is bugged.

**Comment by Tsunder** [comment] 2023-03-28 17:58
it is a constant hold when there's a constant signal for other set_ (doors, pumps, reactor, other components inputs) that overrides (if after one frame or something. opening doors held close plays a sound or something iirc), so for the behaviour of set_color to be "only sets on signal change" would be weird IMO

**Comment by Regalis11** [comment] 2023-03-30 05:03
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c1d6a974956a7eaf2384e47278e576a62f9505c1

> Fixed lights ignoring constant set_color signals if the color is changed manually. Happened because we only parsed and updated the color if the signal was different from the previously received one.

**Comment by Jasontti** [comment] 2023-05-26 06:57
Tested. Works.

**Closed** 2023-05-26 06:57 UTC
Labels: Bug, Code
