### ISSUE TITLE
Unable to link while holding the space and click with the mouse

### ISSUE THREAD

**Issue by hypnosundermoon** [Regalis11/Barotrauma#10849] opened 2023-01-01 13:32 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Submarine editor unable to link while holding the space and click with the mouth, from oxygen generator and a vent to turret and scope.

### Bug prevalence

Happens every time I play

### Version

0.21.0.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-01-02 08:38
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10742

**Closed by Regalis11** 2023-01-02 08:38 UTC
