### ISSUE TITLE
Sub Reset After Retry

### ISSUE THREAD

**Issue by DarwinsGhost** [Regalis11/Barotrauma#3554] opened 2020-08-13 01:14 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I was playing the single player campaign and had just bought the Humpback submarine. I clicked purchase and swap. I then started a mission in the new Humpback. During the mission, my captain died from pressure so I clicked retyr on the menu. When the game reloaded, I was now back in the Dugong, but all of the money used to buy the Humpback was gone. The game appears to think I am using the Humpback because at the Sub vendor, I can purchase a Dugong but not the Humpback

**Version**
Windows 10 - Steam version of game

**Comment by Regalis11** [comment] 2020-08-16 18:37
Duplicate of #3343

**Closed by Regalis11** 2020-08-16 18:37 UTC
Labels: Bug, Code

**Comment by DarwinsGhost** [comment] 2020-08-16 19:45
Hi again, I can now see this is a duplicate to #3343 but that issue also appears closed and unresolved...

**Comment by Regalis11** [comment] 2020-08-17 10:45
The fix is not yet included in the public Steam version, so I'm afraid you'll have to wait for the next patch. Sorry for the inconvenience!

**Comment by DarwinsGhost** [comment] 2020-08-17 20:58
> The fix is not yet included in the public Steam version, so I'm afraid you'll have to wait for the next patch. Sorry for the inconvenience!

Okay, thanks so much for the response!
