### ISSUE TITLE
Assembly Item Bug

### ISSUE THREAD

**Issue by Myrik25** [Regalis11/Barotrauma#13224] opened 2023-12-24 00:27 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

When using assemblies sometimes you get an wiring error that mixes up where everything is supposed to be
![Assembly Bug](https://github.com/Regalis11/Barotrauma/assets/43661529/45113b59-00d2-45f4-8c0a-d11027f031e3)

### Reproduction steps

![Assembly Bug](https://github.com/Regalis11/Barotrauma/assets/43661529/efb67502-eca4-4e06-911b-452f1ca71e78)
Whenever you try to add in certain assemblies from one sub to the next you get this error

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Other

### -

in the Submarine Editor

### Version

v1.2.7.0 (Winter Update hotfix)

### -

it was in the Submarine Editor while trying to make a sub

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
no text
```

**Comment by Regalis11** [comment] 2023-12-26 15:38
Duplicate of https://github.com/Regalis11/Barotrauma/issues/13216

**Closed by Regalis11** 2023-12-26 15:38 UTC
