### ISSUE TITLE
Missing item Custom Hatch

### ISSUE THREAD

**Issue by LuckyLuke980** [Regalis11/Barotrauma#8024] opened 2022-01-13 16:08 UTC
Playing multiplayer and having issues with item Custom Hatch. Hope the log files help
[event_error_log_server_Nebujoka_1902.log](https://github.com/Regalis11/Barotrauma/files/7864108/event_error_log_server_Nebujoka_1902.log)
[event_error_log_server_shrekstyle_1725.log](https://github.com/Regalis11/Barotrauma/files/7864117/event_error_log_server_shrekstyle_1725.log)
[event_error_log_server_Dhyrynus_1841.log](https://github.com/Regalis11/Barotrauma/files/7864120/event_error_log_server_Dhyrynus_1841.log)

**Comment by Oukido** [comment] 2022-01-13 16:19
This happened to us after leaving the outpost to start a mission.
I got the errormessage mentioned in the headline and lost connection. All clients on board were frozen and were unable to reconnect to their bodies but could only spectate.

It seems to be related to https://github.com/Regalis11/Barotrauma/issues/7866
[event_error_log_client_Nebujoka_1901.log](https://github.com/Regalis11/Barotrauma/files/7864223/event_error_log_client_Nebujoka_1901.log)

**Version**
![grafik](https://user-images.githubusercontent.com/83960267/148095670-caeac585-1a04-43ed-91b2-9b06d1046855.png)

**Comment by Regalis11** [comment] 2022-01-13 16:30
It seems the client didn't spawn the respawn shuttle for some reason, most likely a duplicate of https://github.com/Regalis11/Barotrauma/issues/7700 and should be fixed in the latest unstable version (v0.16.0.0) that we just released

**Comment by Rokvach** [comment] 2022-01-14 09:06
Closing in favor of the other ticket.

**Closed by Rokvach** 2022-01-14 09:06 UTC
Labels: Bug, Needs testing, Code, Networking
