### ISSUE TITLE
Iron helmet overlaps with diving suit

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10572] opened 2022-11-26 15:35 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Credit for this bug goes to Gears#8835.

The iron helmet peaks behind the diving suit mask as shown in the image below.

![image](https://user-images.githubusercontent.com/105495756/204096737-fe43a0ff-106d-4278-9abf-958f64efd920.png)

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-11-27 14:46
Doesn't seem to be specific to the faction branch

**Comment by JeroonBosch** [comment] 2022-11-28 13:09
Couldn't reproduce, but I found inconsistency in sprite depth, so set it to 0.6 (same as other helmets)

**Comment by NilanthAnimosus** [comment] 2022-12-13 11:25
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/c74b9de1ded83ed269a2a470b9a849e9eda8aeaf, no issues found

I gave this a thought (Not tested on faction/endgame branch currently) but the fixes in https://github.com/Regalis11/Barotrauma-development/commit/e7b50ce772e19812d695a009dc088146027c3e7f could be related here.

**Comment by Rokvach** [comment] 2023-01-02 11:58
Moved to the full-release pipeline so we remember to check the above

**Comment by Wheatley1001** [comment] 2023-01-21 04:16
Issue still persists in 100.15.0.0. I know there's no commit or fix linked here but thought I'd update this for any outsiders looking at this ticket wondering if anything is happening.
![image](https://user-images.githubusercontent.com/105495756/213842951-d9c155a8-5525-4653-bd3f-f88dcef59eca.png)

**Comment by JeroonBosch** [comment] 2023-01-23 08:51
> Doesn't seem to be specific to the faction branch

Does seem to be specific to faction branch actually

**Comment by JeroonBosch** [comment] 2023-01-23 10:43
Requires a coder to add new functionality: unequip too large helmets when equipping a diving suit (or other clothing that would interfere with this slot)

**Comment by Regalis11** [comment] 2023-01-25 15:07
Tested, could not find any issues. Closing.

**Comment by Wheatley1001** [comment] 2023-01-28 03:40
Issue returns in 100.17.0.0 with a twist!
![image](https://user-images.githubusercontent.com/105495756/215240376-8a6a3ad0-c20f-4e90-822a-ccf24c2951c3.png)

As you can see in the image, the Iron Helmet still shows whilst wearing a diving suit. Except only the top. This gives players a metallic halo.

**Comment by Regalis11** [comment] 2023-02-01 12:51
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/80346468c53de9bc68515c689b3aee5bfdb19e14

Tested, couldn't spot any issues. Closing.

**Closed by Regalis11** 2023-02-01 12:51 UTC
Labels: Bug, Art
