### ISSUE TITLE
Orca2 issues

### ISSUE THREAD

**Issue by feru7** [Regalis11/Barotrauma#7835] opened 2021-12-17 16:17 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
1. Wrong neutral ballast level. Neutral ballast level set to 0.5, should be 0.4598 according to the sub editor.
2. Gunnery compartment is marked as wet room.
3. Bots cannot enter/leave ship through docking hatch when docked.
4. Flood alarm sometimes keeps beeping despite no visible water anywhere (water level 0% on status monitor and no visible water on screen) anywhere in the sub.
5. [Quality of life] Small pump in lower airlock - default pumping rate set to 0, can only be changed while airlock has water in it AND all hatches are closed.

**Steps To Reproduce**
1. Try to drive straight ahead/hold position without autopilot. Sub will descent slowly.
2. Take a look at the status monitor/editor.
3. Make bots follow you when docked and enter/leave ship through docking hatch.
4. Play a mission and get some scratches in your hull.

**Version**
0.15.22.1, Windows 10

**Comment by gerakis** [comment] 2021-12-18 00:08
I have also only found a single hidden compartment; the one in the medbay. More would be nice. Something near the airlock especially. I need a place to stash my stolen goods.

Also why is there two top hatches? This is bizarre and confusing.

**Comment by feru7** [comment] 2021-12-18 15:09
Additionally, the top airlock pump is not connected to power. Default pumping rate is also set to 0 by default.

**Comment by feru7** [comment] 2021-12-18 16:51
Additionally, the small pump in engineering (next to oxygen generator) is not connected to power.

**Comment by Tsunder** [comment] 2021-12-19 01:22
Additionally:
1. there's virtually 0 external lights on the sub, rendering it completely dark ... excepting for
2. there's a lamp INSIDE the shell in the junction room, which lights both inside and outside of the sub
3. there's extremely little emergency lighting inside the sub, and what little there is is also extremely dim and small range, rendering the sub difficult to navigate when the power /lights JB is out
4. the batteries aren't set to recharge by default. Usually they're set to 50% recharge rate. (Also these batteries are completely default with no modifications to their stats!)

**Comment by MaaiG** [comment] 2021-12-20 20:27
> Also why is there two top hatches? This is bizarre and confusing.

I’m guessing docking port on the vanilla submarines aren’t designed to go outside ​into the abyss.
In addition, the second hatch is not-docking.

**Comment by MaaiG** [comment] 2021-12-20 21:08
> Also why is there two top hatches? This is bizarre and confusing.

The docking port on the vanilla submarines aren’t designed to go outside ​into the abyss.
In addition, the second hatch is not-docking.

**Comment by JarlshRels** [comment] 2021-12-29 22:04
Same here. The flood alarm is temporarily fixed by moving wire on the flashing alarm, but it does it the next time water comes in, so I move wire back. 
Same issue with bots not crossing when docked. 

Found there is lights switches in stowage and constructor rooms, a cool touch.

**Comment by danielasteljoki** [comment] 2022-01-04 13:51
Fixed most issues in 15c6a05 and ce332b4. I suspect powering the small pumps fixes flood alarm too, or at least I couldn't reproduce it anymore. 

Batteries' default stats and recharge state is intentional, as is dim emergency lighting.

Also, there are two hidden stashes in the sub. Seems like the other one is well hidden.

**Comment by itchyOwl** [comment] 2022-01-05 07:05
Fixed the waypoints near the docking port in Regalis11/Barotrauma-development@ceef7be.

**Comment by Rokvach** [comment] 2022-01-18 09:32
Tested, no issues. Closing.

**Closed by Rokvach** 2022-01-18 09:32 UTC
Labels: Bug, Design
