### ISSUE TITLE
Revived crew members despawn at end of round

### ISSUE THREAD

**Issue by Bertaz** [Regalis11/Barotrauma#5093] opened 2021-02-17 12:27 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.
Same as closed #2492

**Description**
When you revive a crew member it remains killed in the crew manager causing a despawn at end of round

**Steps To Reproduce**
- Kill yourself in singleplayer or kill a bot
- Use the `revive` command in the console
- Bot/player revived without any problem
- Status is `ok` in end of round recap
- After selecting close revived members despawn

**Version**
0.12.0.2
Windows

**Comment by lokkiser** [comment] 2021-07-14 22:33
I did some testing and found that killing no matter what (by command or damage) at station then save-load does not reproduces bug.

**Steps To Reproduce**
But if i do undock, `kill`, `revive`, dock, character is missing, though he is ok by summary. 
I believe that problem only happens with transition between locations, if you save game before, character saves.
**Version**
0.14.16.0
Windows

**Comment by VaelophisNyx** [comment] 2023-01-02 03:47
adding onto this quite late, it fully despawns their gear when this occurs, which can be incredibly frustrating

**Comment by Regalis11** [comment] 2023-03-08 18:14
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b71d6b117c6798cb68cac66a0a27f712ecdc2e95

**Comment by DROZD-01** [comment] 2023-04-23 02:18
Not sure how u fixed it, but in the latest steam build it is still there.

**Comment by Regalis11** [comment] 2023-04-25 18:55
The fix is not included in any public build yet

**Comment by DROZD-01** [comment] 2023-04-25 20:42
> The fix is not included in any public build yet

That's very unfortunate. Hopefully it will be in one soon.
Now it's been 2 years since the original report.

**Comment by AdamH-Daedalic** [comment] 2023-06-22 10:40
Tested this in multiple ways (before docking at stations, before launching missions etc) with a range of bots and methods of deaths, and none of the resurrected crewmembers despawned after changing locations as mentioned in previous comments. 

Closing as fixed

**Closed by AdamH-Daedalic** 2023-06-22 10:40 UTC
Labels: Bug, Code, Low prio

**Comment by VaelophisNyx** [comment] 2023-08-05 22:33
So this was marked as fixed, but a friend and I experienced a new case of it recently. A bot died via bloodloss to a thresher, was revived via command, and their body & gear were subsequently deleted at the end of the round in campaign, marked as mauled to death still.

**Comment by Rokvach** [comment] 2023-08-06 09:09
This fix isn't in the current public version of the game, coming in the next update.

**Comment by Minimaxind** [comment] 2025-02-06 21:07
The error is reproduced in our save when navigating to locations in the latest version of the game (multiplayer).
