### ISSUE TITLE
[Wallet] Salary percentages aren't saved/loaded in multiplayer campaign

### ISSUE THREAD

**Issue by ohotdog** [Regalis11/Barotrauma#9080] opened 2022-05-06 16:47 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Salary percentages aren't stored between multiplayer campaign sessions. We have to set the percentages again whenver we load the campaign. Also all marks end up in the bank. Playing with the same 3 players.

### Reproduction steps

1. Host multiplayer server
2. Start campaign with other players
3. Set salaries
4. Save and quit
5. Load campaign
6. Salaries set to 0 and marks are back in bank

### Bug prevalence

Happens every time I play

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-06-29 14:31
No known steps to repro (to my understanding @3e849f2e5c was unable to reproduce this), closing

**Closed by Regalis11** 2022-06-29 14:31 UTC
Labels: Bug, Need more info, Code
