### ISSUE TITLE
Different weapons sharing loader

### ISSUE THREAD

**Issue by FLundin** [Regalis11/Barotrauma#6215] opened 2021-06-29 21:53 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The ship upgrade UI does not deny/regulate if you are buying two different guns sharing loader and you can have different weapons still functioning with the same/wrong loader.

**Steps To Reproduce**
make a ship with two hardpoints, sharing loader, buy a different weapons for each hardpoint, shoot.

**Version**
0.14.6.0 w10

**Additional information**
I suggest that a check in the game check how many guns are linked to the same loader(s) and they all count as 1 hardpoint group. This would mean that the when changing weapon on one of them, all of them change as well. the price will be multiplied by the amount of weapons in each hardpoint group as well as a price for the loader. So if a sub have 1 harpoint with multiple loaders linked, then it will cost more to upgrade than a sub with 1 hardpoint + 1 loader. The same if a sub have multiple hardpoints linked to only 1 loader then it should be more expecive than 1 hardpoint + 1 loader aswell as not allowing different guns within that hardpoint group. This way, you can create a dynamic pricing system that will change the price when upgrading a hardpoint group, depeding on how many hardpoints and loaders are linked within it and it should be a flexible system adapting to many different combinations of configurations sub designers can come up with.

**Comment by Regalis11** [comment] 2021-07-06 10:34
Duplicate of https://github.com/regalis11/barotrauma/issues/6085

**Closed by Regalis11** 2021-07-06 10:34 UTC
Labels: Bug, Code, Feature request
