### ISSUE TITLE
Multiplayer campaign disconnect: PlayerName has reported an error: Received an update for an entity that doesn't exist (event id 683, entity id 36608).

### ISSUE THREAD

**Issue by CP44** [Regalis11/Barotrauma#4062] opened 2020-10-12 02:15 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.
Best match I found is closed #1767.

**Description & Steps To Reproduce**
Starting a session in campaign mode (which logs identified as "Mission: killcrawlerswarm2"), a player was kicked.  Then all players received F3 console errors that went on for a long time.  What follows is the initial part which was also found in the host's log files.  Logs and campaign files are included further below.

Starting a campaign mission,..
[2020/10/11 19:59:32]
  Captain Z has reported an error: Received an update for an entity that doesn't exist (event id 683, entity id 36608).
[2020/10/11 19:59:32]
  Captain Z has left the server. Reason: Kicked
Reason: Received an update for an entity that doesn't exist (event id 683, entity id 36608).

**Versions**
Windows 10 x64 hosting via full Barotrauma game, various Windows clients.
Players joined via Steam where this is current:
Game version 0.10.5.1 (ReleaseWindows, branch release, revision 9e259b2148)

**Additional information**
Host=Rah'Kalesh

Log files and campaign files collected
- Deeper_sea-crusade_2020-10-11_1959.txt
- event_error_log_server_Captain_Z_1159_PM.log
- Deepsea_Conquest.save
- Deepsea_Conquest_CharacterData.xml
[Deeper_sea-crusade_2020-10-11_1959.zip](https://github.com/Regalis11/Barotrauma/files/5362594/Deeper_sea-crusade_2020-10-11_1959.zip)

Let me know if any other info or files to collect for this or other issues would be helpful.

**Comment by CP44** [comment] 2020-10-12 03:13
Adding the sub, because that would be part of making our setup reproducable
[Inglia mk.II.sub.zip](https://github.com/Regalis11/Barotrauma/files/5362718/Inglia.mk.II.sub.zip)

**Comment by Regalis11** [comment] 2020-10-12 07:14
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3986

**Closed by Regalis11** 2020-10-12 07:14 UTC
