### ISSUE TITLE
Welding fuel and oxygen tanks don't explode when burning

### ISSUE THREAD

**Issue by DeinococcusR** [Regalis11/Barotrauma#4828] opened 2021-01-19 11:31 UTC
- [ x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I was not able to get welding fuel tanks and oxygen tanks to explode when attacking with a flamethrower or let 'em burn in a ablazed room of a custom sub of mine. It happened only in a certain hull segment. I talked with RainDreamer about the issue and we think that it might have to do with a long hull I have in that area of the ship.

I provided the ship below.

**Steps To Reproduce**
Play on the provided ship. Get the flamethrower from the secure steel cabinet or spawn one yourself. Take or spawn some welding fuel and/or oxygen tanks. Go to the central access passage/ the long corridor in the middle part of the ship(there is only one). Drop the tanks on the ground and use the flamer on them. 

If you need more info feel free to ask here or in Discord - modding

**Version**
v0.11.0.10 Windows 10

**Additional information**

My custom sub:
[Nebulon-B Frigate (Firebug).zip](https://github.com/Regalis11/Barotrauma/files/5835562/Nebulon-B.Frigate.Firebug.zip)

**Comment by Regalis11** [comment] 2021-01-19 17:12
Thank you for the report! Turns out this wasn't caused by the long corridor, but a bug in the fire damage logic that only occurred in very specific situations. Basically, if the method that damages items encountered an item that's in a fire proof hull, it would stop processing the rest of the damageable items. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/66562caf65f371548739cc227e0c8ffde93a7208

**Comment by Rokvach** [comment] 2021-01-20 16:37
Tested I wasn't able to make the welding fuel tanks to explode in fire, no issues with oxygen tanks

**Comment by Regalis11** [comment] 2021-01-21 14:15
Did you test this in dev or bugfixes?

**Comment by Rokvach** [comment] 2021-01-21 16:28
Most likely tested in dev, I guess it was fixed in bugfixes? Didn't think to check as everything's been pushed to dev lately

**Comment by Regalis11** [comment] 2021-01-22 08:01
Yeah, it's in bugfixes. Has been merged to dev now as well

**Comment by Rokvach** [comment] 2021-01-22 13:20
Tested, working correctly. Closing.

**Closed by Rokvach** 2021-01-22 13:20 UTC
Labels: Bug, Code, Medium Prio
