### ISSUE TITLE
Having connection lost problem when docked at the abandoned outpost.

### ISSUE THREAD

**Issue by rosenkavalier00** [Regalis11/Barotrauma#5734] opened 2021-05-10 14:26 UTC
My team is playing campaign mod.
One of our members has a connection problem when docked at the abandoned outpost.
The same problem repeatedly occurred at two different outposts.
When we docked, he can not complete the loading and get out to the lobby.
Other members don't have any problem and normally spawn at sub docked at the abandoned outpost.
Retrying, restarting and reinstalling game didn't work.
Below is the error message he got. (same message popped at two different abandoned outpost)

Error while starting the round (did not receive STARTGAMEFINALIZE message from the server). Stopping the round...
TimedOut
Coroutine "Barotrauma.Networking.GameClient+<StartGame>d__93" has failed

Please help us.

**Comment by Regalis11** [comment] 2021-05-10 14:51
Duplicate of https://github.com/Regalis11/Barotrauma/issues/4183

**Closed by Regalis11** 2021-05-10 14:51 UTC
