### ISSUE TITLE
Shots sometimes dont connect fully or the hitboxes of the ai's are broken

### ISSUE THREAD

**Issue by KrusteDE** [Regalis11/Barotrauma#12037] opened 2023-05-20 14:11 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Sometimes in a fight with creatures for example some shots you fire on them, doesnÄt hit them really. I just played in a online lobby private with a friend, and didnt tried it on a single player campaign. But i for example, tried once just to shot a mudrapter and he takes damage, but after a second the taken damage is resetted to his previous health bar. But in that time he bit or scratched me multiple times and not just once in this fight. Its not the only time it happenend. 

Link to sample Video (bc its to big to upload here):
https://imgur.com/lwxakgI

### Reproduction steps

1. Find a Mudraptor 
2. Get in Fight with him
3. Try to shot him

### Bug prevalence

Happens every now and then

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-05-20 14:39
Duplicate of https://github.com/Regalis11/Barotrauma/issues/9825

**Closed by Regalis11** 2023-05-20 14:39 UTC

**Comment by KrusteDE** [comment] 2023-05-20 19:07
thx couldnt find other treads under the points i searched before :)
