### ISSUE TITLE
Crash when enabling certain mods that don't contain any content supported by the vanilla game (EnabledPackages.ThrowIfDuplicates, input contains duplicate packages)

### ISSUE THREAD

**Issue by MapleWheels** [Regalis11/Barotrauma#11789] opened 2023-04-09 20:48 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I am making this issue on behalf of the other players in my group and more so to outline that in the event of this, the desirable behaviour should be to make a log entry and not load the Content Package twice instead of crashing to desktop.

Crash on joining a lobby due to the game trying to load "Lua for Barotrauma" Content Package twice. The issue will sometimes occur with other Content Packages as well. This issue is occurring with almost all players joining the lobby. Occurs across multiple people attempting to host.

These issues did not occur before the 1.0 update.

I've talked to EvilFactory about it and it seems that this is vanilla loading behaviour.

Troubleshooting Steps taken:
1. Steam Validation 
2. Clean Reinstallation.
3. Clearing Steam Download Cache.
4. Clearing Barotrauma Workshop Cache.

### Reproduction steps

1. Run the list of mods attached. 
2. Install Client-Side Lua.
3. Enable "CSharp Mods" from the Main Menu.
4. Attempt to connect to a host with said mod pack.

[thegamekeepsbreakingallthetime.txt](https://github.com/Regalis11/Barotrauma/files/11186279/thegamekeepsbreakingallthetime.txt)

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 04/09/2023 15:28:01)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

60489F18D6F11720E3077B8BD6E01760

Game version 1.0.8.0 (ReleaseWindows, branch master, revision cf88aa4c5d)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.ModDownloadScreen
SteamManager initialized
Client (Round hadn't been started)

System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: AMD Radeon RX 6800
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Input contains duplicate packages (System.InvalidOperationException)
Target site: Void ThrowIfDuplicates(System.Collections.Generic.IEnumerable`1[Barotrauma.ContentPackage])
Stack trace: 
   at Barotrauma.ContentPackageManager.EnabledPackages.ThrowIfDuplicates(IEnumerable`1 pkgs) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentPackageManager.cs:line 121
   at Barotrauma.ContentPackageManager.EnabledPackages.SetRegularEnumerable(IReadOnlyList`1 inNewRegular)+MoveNext() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentPackageManager.cs:line 84
   at Barotrauma.Extensions.IEnumerableExtensions.Consume[T](IEnumerable`1 enumerable) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Extensions\IEnumerableExtensions.cs:line 155
   at Barotrauma.ModDownloadScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\ModDownloadScreen.cs:line 353
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 891
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[04/09/2023 15:28:01] Enabling "Ssparky's Gunnery" (C:\Users\kylet\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\WorkshopMods\Installed\2895083880)
[04/09/2023 15:28:01] Enabling "BaroDrama V4.1" (C:\Users\kylet\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\WorkshopMods\Installed\2719602039)
[04/09/2023 15:28:01] Enabling "Enhanced Armaments" (TempMods_Download\Workshop_Enhanced Armaments_2764968387)
[04/09/2023 15:28:01] Enabling "Backpacks" (C:\Users\kylet\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\WorkshopMods\Installed\2613901395)
[04/09/2023 15:28:01] Enabling "Lua For Barotrauma" (C:\Users\kylet\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\WorkshopMods\Installed\2559634234)
[04/09/2023 15:28:01] Enabling "New Wrecks For Barotrauma (With sellable wrecks)" (TempMods_Download\Workshop_New Wrecks For Barotrauma (With sellable wrecks)_2184257427)
[04/09/2023 15:28:01] Enabling "Stations from beyond" (C:\Users\kylet\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\WorkshopMods\Installed\2585543390)
[04/09/2023 15:28:01] Enabling "DynamicEuropa" (C:\Users\kylet\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\WorkshopMods\Installed\2532991202)
[04/09/2023 15:28:01] Enabling "SFB with DE" (C:\Users\kylet\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\WorkshopMods\Installed\2907491279)
[04/09/2023 15:28:01] Enabling "Playable Mudraptor Job 3 (Electric Boogaloo) (WORKS IN 1.0 LAUNCH!!!)" (C:\Users\kylet\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\WorkshopMods\Installed\2871761155)
[04/09/2023 15:28:01] Enabling "Harlequin Job" (C:\Users\kylet\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\WorkshopMods\Installed\2942994485)
[04/09/2023 15:28:01] Enabling "Robo-Trauma" (C:\Users\kylet\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\WorkshopMods\Installed\2948488019)
[04/09/2023 15:28:01] Enabling "Lua For Barotrauma" (C:\Users\kylet\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\WorkshopMods\Installed\2559634234)
[04/09/2023 15:26:07] WARNING: Tried to restore enabled packages multiple times/without performing a backup
[04/09/2023 15:25:13] Attempting to open ALC device "OpenAL Soft on Headset Earphone (Corsair VOID ELITE Surround USB Adapter)"
[04/09/2023 15:25:09] Logged in as BQN (SteamID STEAM_1:1:50140504)
```

**Comment by Regalis11** [comment] 2023-04-11 15:05
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/eda9cf6aff251ec2f0eda59979e13ddf73c390b7

**Comment by Regalis11** [comment] 2023-04-11 15:46
Internal note for testing: you don't necessarily need any Lua mods to reproduce the issue, it can be reproduced with any mods that either have identical content, or only content whose MD5 hashes aren't calculated (like content of the type "Other").

**Comment by Regalis11** [comment] 2023-04-20 08:01
Seems to be a duplicate of https://github.com/regalis11/barotrauma/issues/11277

**Closed by Regalis11** 2023-04-20 08:01 UTC
Labels: Bug, Code, Crash, Modding
