### ISSUE TITLE
Trader UI scale has some collisions on high res screen

### ISSUE THREAD

**Issue by Ariloum** [Regalis11/Barotrauma#3473] opened 2020-08-03 09:12 UTC
[x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Trader UI scale seems wrong (100% scale, 3440x1440 resolution, windowed-borderless mode)
https://www.youtube.com/watch?v=Cza0LS4GmL8

**Steps To Reproduce**
that bug is always on

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).
0.10.4.0 20132d25fb (win 10 pro)

**Additional information**

**Comment by Regalis11** [comment] 2020-08-21 07:52
Attempted to fix this in https://github.com/Regalis11/Barotrauma-development/commit/e4600b124e14d598920c825187cc1a7c9f039d54. Needs to be tested, because I couldn't try it with a resolution higher than 1080p. If the issue is still present, a screenshot with debugdraw enabled while the cursor is on one of the non-clickable areas would be very helpful, because it should show which UI element has focus instead of the buttons.

**Comment by Rokvach** [comment] 2020-09-01 10:53
I think @EdusFF is the only one with a 4k monitor, haven't noticed any issues while using the UI with 1440p monitor

**Comment by Ariloum** [comment] 2020-09-03 22:38
I just checked and it's still bugged: https://youtu.be/FK-Q65FZpuI

**Comment by Rokvach** [comment] 2020-09-04 06:36
The fix isn't included in the public version of the game yet, can only be tested in the Unstable version of the next patch which is publicly accessible.

**Comment by Rokvach** [comment] 2020-09-08 09:30
Working correctly, closing.

**Closed by Rokvach** 2020-09-08 09:30 UTC
Labels: Bug, Code, Needs testing
