### ISSUE TITLE
[13.3.11] Console errors when opening Server browsers

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#5696] opened 2021-05-03 11:02 UTC
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Every time I open the server browser for the first time the client stalls for ~20-30secs+ and spams this into the console:

`Couldn't load xml document "Content/Characters/Swarmcrawler/Swarmcrawler.xml"! {Could not find a part of the path 'E:\Program Files\Steam\steamapps\common\Barotrauma\Content\Characters\Swarmcrawler\Swarmcrawler.xml'.}
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at Barotrauma.XMLExtensions.TryLoadXml(String filePath) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Serialization\XMLExtensions.cs:line 36

Error while calculating content package hash:  {Object reference not set to an instance of an object.}
   at Barotrauma.RagdollParams.GetFolder(XDocument doc, String filePath) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Params\Ragdoll\RagdollParams.cs:line 116
   at Barotrauma.ContentPackage.CalculateFileHash(ContentFile file) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\ContentPackage.cs:line 640
   at Barotrauma.ContentPackage.CalculateHash(Boolean logging) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\ContentPackage.cs:line 601

Couldn't load xml document "Content/Characters/Hammerhead_m/Hammerhead_m.xml"! {Could not find a part of the path 'E:\Program Files\Steam\steamapps\common\Barotrauma\Content\Characters\Hammerhead_m\Hammerhead_m.xml'.}
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at Barotrauma.XMLExtensions.TryLoadXml(String filePath) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Serialization\XMLExtensions.cs:line 36

Error while calculating content package hash:  {Object reference not set to an instance of an object.}
   at Barotrauma.RagdollParams.GetFolder(XDocument doc, String filePath) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Params\Ragdoll\RagdollParams.cs:line 116
   at Barotrauma.ContentPackage.CalculateFileHash(ContentFile file) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\ContentPackage.cs:line 640
   at Barotrauma.ContentPackage.CalculateHash(Boolean logging) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\ContentPackage.cs:line 601
Couldn't load xml document "Content/Characters/Moloch_m/Moloch_m.xml"! {Could not find a part of the path 'E:\Program Files\Steam\steamapps\common\Barotrauma\Content\Characters\Moloch_m\Moloch_m.xml'.}
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at Barotrauma.XMLExtensions.TryLoadXml(String filePath) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Serialization\XMLExtensions.cs:line 36`

Then follows a long list of SteamID related spam... probably the client hooking into my friends list? 

**Steps To Reproduce**
Start game
open server browser
voila.

**Version**
13.3.11, Win10, vanilla. Had this also in 12.x versions

**Comment by Regalis11** [comment] 2021-05-03 12:06
This seems to be related to https://github.com/Regalis11/Barotrauma/issues/5467: for some reason the game is trying to load the creature variant files from an incorrect file path. Are you using some kind of mods?

**Comment by CurePindal** [comment] 2021-05-03 12:31
Nope, the errors above happen when i start the game with no mods enabled.
And the issue shows up no matter if mods are loaded or not.

**Comment by Leonidas-ai** [comment] 2021-05-03 13:29
I've seen this exact error when loading a CORE content package which aren't in the normal mod area. Specifically the outdated SOMA mod. You may want to verify files or reinstall.

**Comment by CurePindal** [comment] 2021-05-03 15:16
> 
> 
> I've seen this exact error when loading a CORE content package which aren't in the normal mod area. 

No idea what a content package is thats not "in the normal area". Also no idea what "normal area"  means in this context.

But verify hasnt solved the issue before. And theres only the content package involved.

**Comment by CurePindal** [comment] 2021-05-03 15:34
Seems I found the cause.

I had an experiemental content package xml along the default Vanilla 0.9.xml in \Data\ContentPackages from last August and that had outdated mod references. However, it wasnt loaded.

Issue: Additional, unloaded xml in \Data\ContentPackages can cause console errors when opening the server browser. Seems opening the server browser tries to verfiy unloaded xmls from that path.

Expected: Additional xmls in \Data\ContentPackages  have no impact on the client when not loaded.

**Comment by Regalis11** [comment] 2021-05-04 17:45
Thanks for the extra info, I was able to reproduce this now! However, I do think the game should try to load the additional content packages even if they're not enabled: the game uses those to determine if you have the packages required by the server available, not whether they're currently enabled.

I changed the error message to a more descriptive one that actually tells what went wrong and how to fix it: https://github.com/Regalis11/Barotrauma-development/commit/9a1bde74f660664598bd108503767f4a453729f4

**Comment by Rokvach** [comment] 2021-05-05 07:29
Tested, no issues. Closing.

**Closed by Rokvach** 2021-05-05 07:29 UTC
Labels: Bug, Code
