### ISSUE TITLE
[Tester's Version] Ugly hull shadows

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#1366] opened 2019-03-29 03:39 UTC
These hull shadows are unappealing and quite frankly look messy and buggy. I suggest they be fixed up. Look in the circles I beautifully constructed in ms paint for examples I guess.

![ugly shit](https://user-images.githubusercontent.com/41457828/55207946-595ee100-51ed-11e9-8047-bf1f3598c889.PNG)

**Comment by Regalis11** [comment] 2019-04-02 09:46
Should be (mostly) fixed by 20b8797 and 43578f3. The "extra" shadows don't appear in spots where the ends of two walls meet anymore, but corner areas where a vertical wall meets a horizontal one still need some work.

**Comment by PicolasCage** [comment] 2019-04-07 16:03
![still poopy](https://user-images.githubusercontent.com/49355189/55686273-c0a43000-5967-11e9-9728-ec61f509999b.PNG)

Yeah I see the shadows were slightly fixed, but there's still a but more work to be done.

**Closed** 2019-06-02 16:33 UTC
Labels: Bug, Code

**Comment by hubismal** [comment] 2019-06-03 03:43
why was this closed without a word? The way the game occludes thing is still pretty sketchy imo.

**Comment by Regalis11** [comment] 2019-06-03 08:34
Because it's essentially a duplicate of #231
