### ISSUE TITLE
Game closed but menu music is still playing

### ISSUE THREAD

**Issue by TheSurvivor64** [Regalis11/Barotrauma#658] opened 2018-08-12 18:06 UTC
Whenever I play, I find myself in a situation where I have to press my windows button to tab out of the game. But doing this closes the game. And despite the game being closed, the music still plays, despite Barotrauma not showing up in my task manager. Sometimes it is in my task manager, but more often than not it is not in my task manager. I've had v0.8.1.5 and I had the problem. Now, in v0.8.1.12, I still have this problem! The update didn't fix it, and I feel like I'm the only person having this issue as I can't find something related to this on Google.

**Comment by Momiro** [comment] 2018-08-13 00:47
The game actually doesn't close when you tab or windows out, to fix this problem you need to start the game in borderless full screen or windowed mode

**Comment by Regalis11** [comment] 2018-08-13 07:57
Duplicate of #35

**Closed by Regalis11** 2018-08-13 07:57 UTC
Labels: duplicate
