### ISSUE TITLE
Memory Component Value field does not change to new signal_in value, even though it did, but still displays old value.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3410] opened 2020-07-23 23:46 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Memory Component Value field does not change to new signal_in value, even though it did, but still displays old value to players.

**Steps To Reproduce**
Singleplayer
Place down a Memory Component.
Enter any value, Example: "101".
Place down something that would modify like Signal Check outputting "202" to Memory Component when True.
Make the modifier component True to output to Memory Component.
Inspect Memory Component. It should still say "101", but it's actually outputting "202".

Inspect any components other than Memory Component, and then Reinspect the Memory Component. The value field should now show up as 202.

**Version**
~0.10.4.0

**Additional information**
So knowing this, I tried an experiment in multiplayer as well. Players are not synced to what the values on components have been changed to when changed by other components. I created my usual optimal auto reactor logic circuit on a multiplayer campaign.

I added 3 buttons that are wired to two signal checks of their own each which changes a text display that you can find around reactors usually that will display Uranium, Thorium, or Fulgurium. The second signal check changes the number on the logic to match the fuel type being used in the reactor for optimal usage.

Lets say Player A started a campaign and press Button 2 making the display read Thorium, and changes a Memory Component value to 1.0 and goes to the next level with a Reactor running on Thorium rod.
Player B joins in. Player B sees the display show Thorium and Memory Component value 1.0.
When Player A changes fuel rod to Uranium and then pushes Button 1, it should read Uranium and changes a Memory Component value to 0.8.
Player A will see the change to Display Uranium and Memory Component Value 0.8.
Player B will see still Thorium and Value 1.0.
Server side, everything is correct.
Client side, Player B will see power flickering because the value computation is incorrect on his side, but nothing actually breaks.

**Comment by Regalis11** [comment] 2020-07-27 08:39
Duplicate of https://github.com/Regalis11/Barotrauma/issues/2977

**Closed by Regalis11** 2020-07-27 08:39 UTC
