### ISSUE TITLE
Solo Campaign: Engineer's Electrician tree is fully unlocked from level one.

### ISSUE THREAD

**Issue by datorangebottle** [Regalis11/Barotrauma#10111] opened 2022-10-18 13:59 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I started a mission with some new engineers who had just leveled up, and they were able to pick All-seeing Eye without any of the prerequisite traits. The entire electrician tree was selectable.

I only noticed this the one time, but it could be more common.

![image](https://user-images.githubusercontent.com/46474741/196448988-a6e3b053-d814-434f-8f92-95a18c09bfbb.png)
Save attached.
[Save 0.zip](https://github.com/Regalis11/Barotrauma/files/9811111/Save.0.zip)

### Reproduction steps

1) level up an engineer.
2) start a mission.
3) open the character menu
4) notice that the electrician tree is fully unlocked from the start and that you can select any perk.
5) pick 'all-seeing eye' and get all the perks in the tree.

### Bug prevalence

Just once

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by datorangebottle** [comment] 2022-10-18 14:00
I hit retry and got an additional screenshot.
![image](https://user-images.githubusercontent.com/46474741/196451314-5048dbde-e2c1-44f2-ac77-eb84f22e651b.png)

**Comment by Regalis11** [comment] 2022-10-18 14:30
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10034

**Closed by Regalis11** 2022-10-18 14:30 UTC
