### ISSUE TITLE
NPCs weld doors while trying to fix the hull behind

### ISSUE THREAD

**Issue by Alriac** [Regalis11/Barotrauma#3978] opened 2020-10-01 22:51 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In single player campaign ,NPCs try to weld a hull portion that is behind a door, welding the door in the process and getting stuck.

**Steps To Reproduce**
1- Breach the hull right behind a door.
2- Have an NPC that is standing at the other side of the door fix hull breaches.
3- The NPC will start welding the hull without opening the door.
4- In some cases, the hull won't get welded, but the NPC will keep trying, welding the door in the process.
5- The door will stay welded.

**Version**
v0.10.5.1, Windows 10 Pro x64

**Additional information**
It happens very often but not always.

**Comment by Regalis11** [comment] 2020-10-04 09:51
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3911

**Closed by Regalis11** 2020-10-04 09:51 UTC
