### ISSUE TITLE
Bots - Able to clip through Docking Port (Vertical) gaps and completely vanishes (and dead)?

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2803] opened 2020-05-11 12:34 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I was going out to ruins and I was noticing my two bots were running back and forth between shuttle and submarine's port due to #2675. When I came back, I noticed I had less crew members on my sub. It was those two specifically. When I controlled their bodies, it doesn't even pan over to the bodies, but it clearly states the affliction of O2 Loss and High Pressure. My guess is that it may have something to do with simple physics again?

**Version**
0.9.9.1

**Comment by Kaillera** [comment] 2020-05-12 19:43
![Capture](https://user-images.githubusercontent.com/5086682/81738168-477ae480-9467-11ea-8e64-d68081956c9c.PNG)

**Comment by Regalis11** [comment] 2020-05-14 14:23
Might have been caused by simple physics. Bots shouldn't use simple physics in the latest Unstable build, so lets see if this reoccurs

**Comment by Kaillera** [comment] 2020-05-18 13:38
[0.9.1001.0] Have not seen this happened since.

**Comment by Rokvach** [comment] 2020-05-18 13:51
Closing

**Closed by Rokvach** 2020-05-18 13:51 UTC
Labels: Bug, Code, Needs testing
