### ISSUE TITLE
ConnectionPanel layouting produces strange artifacts with large number of connections

### ISSUE THREAD

**Issue by mizvekov** [Regalis11/Barotrauma#12490] opened 2023-08-11 10:14 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Adding a lot of connections to a ConnectionPanel leads to wrong layout on the panel GUI.

The issue gets progressively worse, where at 16 inputs/outputs you get some minor label clipping, but it's still otherwise quite usable, but at 32 it's quite unusable.

See example XMLs and resulting artifacts on a screenshot:

```XML
<ConnectionPanel selectkey="Action" canbeselected="true" msg="ItemMsgRewireScrewdriver" hudpriority="10">
      <GuiFrame relativesize="0.2,0.8" minsize="400,700" maxsize="480,840" anchor="Center" style="ConnectionPanel" />
      <RequiredItem items="screwdriver" type="Equipped" />
      <input name="signal_in1" displayname="connection.signalinx~[num]=1" />
      <input name="signal_in2" displayname="connection.signalinx~[num]=2" />
      <input name="signal_in3" displayname="connection.signalinx~[num]=3" />
      <input name="signal_in4" displayname="connection.signalinx~[num]=4" />
      <input name="signal_in5" displayname="connection.signalinx~[num]=5" />
      <input name="signal_in6" displayname="connection.signalinx~[num]=6" />
      <input name="signal_in7" displayname="connection.signalinx~[num]=7" />
      <input name="signal_in8" displayname="connection.signalinx~[num]=8" />
      <input name="signal_in9" displayname="connection.signalinx~[num]=9" />
      <input name="signal_in10" displayname="connection.signalinx~[num]=10" />
      <input name="signal_in11" displayname="connection.signalinx~[num]=11" />
      <input name="signal_in12" displayname="connection.signalinx~[num]=12" />
      <input name="signal_in13" displayname="connection.signalinx~[num]=13" />
      <input name="signal_in14" displayname="connection.signalinx~[num]=14" />
      <input name="signal_in15" displayname="connection.signalinx~[num]=15" />
      <input name="signal_in16" displayname="connection.signalinx~[num]=16" />
      <output name="signal_out1" displayname="connection.signaloutx~[num]=1" />
      <output name="signal_out2" displayname="connection.signaloutx~[num]=2" />
      <output name="signal_out3" displayname="connection.signaloutx~[num]=3" />
      <output name="signal_out4" displayname="connection.signaloutx~[num]=4" />
      <output name="signal_out5" displayname="connection.signaloutx~[num]=5" />
      <output name="signal_out6" displayname="connection.signaloutx~[num]=6" />
      <output name="signal_out7" displayname="connection.signaloutx~[num]=7" />
      <output name="signal_out8" displayname="connection.signaloutx~[num]=8" />
      <output name="signal_out9" displayname="connection.signaloutx~[num]=9" />
      <output name="signal_out10" displayname="connection.signaloutx~[num]=10" />
      <output name="signal_out11" displayname="connection.signaloutx~[num]=11" />
      <output name="signal_out12" displayname="connection.signaloutx~[num]=12" />
      <output name="signal_out13" displayname="connection.signaloutx~[num]=13" />
      <output name="signal_out14" displayname="connection.signaloutx~[num]=14" />
      <output name="signal_out15" displayname="connection.signaloutx~[num]=15" />
      <output name="signal_out16" displayname="connection.signaloutx~[num]=16" />
</ConnectionPanel>
```
![image](https://github.com/Regalis11/Barotrauma/assets/545007/c49ec632-9e6e-4a30-94c9-7353a999ab02)
---

```XML
    <ConnectionPanel selectkey="Action" canbeselected="true" msg="ItemMsgRewireScrewdriver" hudpriority="10">
      <GuiFrame relativesize="0.2,0.8" minsize="400,700" maxsize="480,840" anchor="Center" style="ConnectionPanel" />
      <RequiredItem items="screwdriver" type="Equipped" />
      <input name="signal_in1" displayname="connection.signalinx~[num]=1" />
      <input name="signal_in2" displayname="connection.signalinx~[num]=2" />
      <input name="signal_in3" displayname="connection.signalinx~[num]=3" />
      <input name="signal_in4" displayname="connection.signalinx~[num]=4" />
      <input name="signal_in5" displayname="connection.signalinx~[num]=5" />
      <input name="signal_in6" displayname="connection.signalinx~[num]=6" />
      <input name="signal_in7" displayname="connection.signalinx~[num]=7" />
      <input name="signal_in8" displayname="connection.signalinx~[num]=8" />
      <input name="signal_in9" displayname="connection.signalinx~[num]=9" />
      <input name="signal_in10" displayname="connection.signalinx~[num]=10" />
      <input name="signal_in11" displayname="connection.signalinx~[num]=11" />
      <input name="signal_in12" displayname="connection.signalinx~[num]=12" />
      <input name="signal_in13" displayname="connection.signalinx~[num]=13" />
      <input name="signal_in14" displayname="connection.signalinx~[num]=14" />
      <input name="signal_in15" displayname="connection.signalinx~[num]=15" />
      <input name="signal_in16" displayname="connection.signalinx~[num]=16" />
      <input name="signal_in17" displayname="connection.signalinx~[num]=17" />
      <input name="signal_in18" displayname="connection.signalinx~[num]=18" />
      <input name="signal_in19" displayname="connection.signalinx~[num]=19" />
      <input name="signal_in20" displayname="connection.signalinx~[num]=20" />
      <input name="signal_in21" displayname="connection.signalinx~[num]=21" />
      <input name="signal_in22" displayname="connection.signalinx~[num]=22" />
      <input name="signal_in23" displayname="connection.signalinx~[num]=23" />
      <input name="signal_in24" displayname="connection.signalinx~[num]=24" />
      <input name="signal_in25" displayname="connection.signalinx~[num]=25" />
      <input name="signal_in26" displayname="connection.signalinx~[num]=26" />
      <input name="signal_in27" displayname="connection.signalinx~[num]=27" />
      <input name="signal_in28" displayname="connection.signalinx~[num]=28" />
      <input name="signal_in29" displayname="connection.signalinx~[num]=29" />
      <input name="signal_in30" displayname="connection.signalinx~[num]=30" />
      <input name="signal_in31" displayname="connection.signalinx~[num]=31" />
      <input name="signal_in32" displayname="connection.signalinx~[num]=32" />

      <output name="signal_out1" displayname="connection.signaloutx~[num]=1" />
      <output name="signal_out2" displayname="connection.signaloutx~[num]=2" />
      <output name="signal_out3" displayname="connection.signaloutx~[num]=3" />
      <output name="signal_out4" displayname="connection.signaloutx~[num]=4" />
      <output name="signal_out5" displayname="connection.signaloutx~[num]=5" />
      <output name="signal_out6" displayname="connection.signaloutx~[num]=6" />
      <output name="signal_out7" displayname="connection.signaloutx~[num]=7" />
      <output name="signal_out8" displayname="connection.signaloutx~[num]=8" />
      <output name="signal_out9" displayname="connection.signaloutx~[num]=9" />
      <output name="signal_out10" displayname="connection.signaloutx~[num]=10" />
      <output name="signal_out11" displayname="connection.signaloutx~[num]=11" />
      <output name="signal_out12" displayname="connection.signaloutx~[num]=12" />
      <output name="signal_out13" displayname="connection.signaloutx~[num]=13" />
      <output name="signal_out14" displayname="connection.signaloutx~[num]=14" />
      <output name="signal_out15" displayname="connection.signaloutx~[num]=15" />
      <output name="signal_out16" displayname="connection.signaloutx~[num]=16" />
      <output name="signal_out17" displayname="connection.signaloutx~[num]=17" />
      <output name="signal_out18" displayname="connection.signaloutx~[num]=18" />
      <output name="signal_out19" displayname="connection.signaloutx~[num]=19" />
      <output name="signal_out20" displayname="connection.signaloutx~[num]=20" />
      <output name="signal_out21" displayname="connection.signaloutx~[num]=21" />
      <output name="signal_out22" displayname="connection.signaloutx~[num]=22" />
      <output name="signal_out23" displayname="connection.signaloutx~[num]=23" />
      <output name="signal_out24" displayname="connection.signaloutx~[num]=24" />
      <output name="signal_out25" displayname="connection.signaloutx~[num]=25" />
      <output name="signal_out26" displayname="connection.signaloutx~[num]=26" />
      <output name="signal_out27" displayname="connection.signaloutx~[num]=27" />
      <output name="signal_out28" displayname="connection.signaloutx~[num]=28" />
      <output name="signal_out29" displayname="connection.signaloutx~[num]=29" />
      <output name="signal_out30" displayname="connection.signaloutx~[num]=30" />
      <output name="signal_out31" displayname="connection.signaloutx~[num]=31" />
      <output name="signal_out32" displayname="connection.signaloutx~[num]=32" />
    </ConnectionPanel>
```
![Screenshot 2023-08-11 115332](https://github.com/Regalis11/Barotrauma/assets/545007/437562c5-dad8-4125-a8bc-18970da7c3e9)

### Reproduction steps

To reproduce this, see for example this mod, where it's currently at 16 input / output connections:
https://steamcommunity.com/sharedfiles/filedetails/?id=3018125421

Otherwise, to see the 32 connections case, edit the `MicroLua.xml` to add 16 more connections, as described at the bottom XML snippet.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by mizvekov** [comment] 2023-08-11 17:31
I made some headway on my own, and through some local patches, I am able to get a 32 connection panel working acceptably, without causing any significant difference in the behavior for Vanilla components.

The first problem that I found was the scaling problem for the connector sprite, making it look huge with relation to the label height and step size.

The sprite is scaled according to the GuiFrame width, relative to some magic 400 pixel number.
See `Client/ConnectionPanel.cs` : `public float Scale` definition for reference.
The size of the GuiFrame was getting adjusted too wide, a separate problem I am going to address next, but that increase in the connector size is not accounted for anywhere else, causing the overlap seen.

For the vanilla components, this scale tends to be around `[1.0, 1.2]`, but was going up to 2.8 for this example.

I made a simple change to eliminate that Scale, forcing it to 1.0:
```diff
diff --git a/Barotrauma/BarotraumaClient/ClientSource/Items/Components/Signal/ConnectionPanel.cs b/Barotrauma/BarotraumaClient/ClientSource/Items/Components/Signal/ConnectionPanel.cs
index d0c3dfda4..9757f2249 100644
--- a/Barotrauma/BarotraumaClient/ClientSource/Items/Components/Signal/ConnectionPanel.cs
+++ b/Barotrauma/BarotraumaClient/ClientSource/Items/Components/Signal/ConnectionPanel.cs
@@ -24,7 +24,7 @@ namespace Barotrauma.Items.Components

         public float Scale
         {
-            get { return GuiFrame.Rect.Width / 400.0f; }
+            get => 1.0F;
         }

         private Point originalMaxSize;
```
And that fixes the overlap, without significantly affecting anything else I have seen so far.

The second problem that I found is the reason why the window was getting too wide in the first place: 
the algorithm in `Client/Connection.cs/CheckConnectionLabelOverlap` for resizing the GuiFrame to account for a bad initial size estimate coming from the GuiFrame tag in the XML.

The algorithm will cause large skews in the aspect ratio from the initial estimate, by virtue of incrementing the size by 10 pixels in both dimensions, instead of trying to increase while preserving the ratio.

I didn't try to fix that at this point though, I just found a better size estimate and updated my XML accordingly:
```XML
<GuiFrame relativesize="0.2,0.8" minsize="480,1200" maxsize="520,1300" anchor="Center" style="ConnectionPanel" />
```

So this looks much better now, but one serious problem remains:
The layout seems skewed up, in a way where the first connectors on both input and output columns are clipped by the GuiFrame title bar. The first input is totally clipped out, unusable, and the first output connector is half-way clipped.

I "fixed" that by applying a fudge factor to the initial left/right positions, by approximately 35 pixels, which was already a magic number thrown around that file:
```diff
diff --git a/Barotrauma/BarotraumaClient/ClientSource/Items/Components/Signal/Connection.cs b/Barotrauma/BarotraumaClient/ClientSource/Items/Components/Signal/Connection.cs
index 35ed6a50a..58aff82f9 100644
--- a/Barotrauma/BarotraumaClient/ClientSource/Items/Components/Signal/Connection.cs
+++ b/Barotrauma/BarotraumaClient/ClientSource/Items/Components/Signal/Connection.cs
@@ -576,12 +578,12 @@ namespace Barotrauma.Items.Components

         private static Vector2 GetLeftPos(int x, int y, Vector2 scale)
         {
-            return new Vector2(x + 80 * scale.X, y + 60 * scale.Y);
+            return new Vector2(x + 80 * scale.X, y + 60 * scale.Y + 35.0F);
         }

         private static Vector2 GetRightPos(int x, int y, int width, Vector2 scale)
         {
-            return new Vector2(x + width - 80 * scale.X, y + 60 * scale.Y);
+            return new Vector2(x + width - 80 * scale.X, y + 60 * scale.Y + 35.0F);
         }

         private static int GetConnectorIntervalLeft(int height, Vector2 scale, ConnectionPanel panel)
```

Now the result looks quite decent:
![image](https://github.com/Regalis11/Barotrauma/assets/545007/5bf979e5-99e5-48f7-8929-c28ac34d4953)

The remaining issue is that for a window this tall, moving the window vertically is bugged and results in moving opposite to the mouse direction.
But I don't consider this a breaking bug for my needs.

**Comment by Regalis11** [comment] 2023-08-13 09:55
Duplicate of https://github.com/Regalis11/Barotrauma/issues/12180

**Comment by mizvekov** [comment] 2023-10-19 23:20
I just tested the v1.1.18.0 update with the supposed fix.

* The scaling issue on the connectors is fixed.
* The inverted mouse movement when moving tall windows is fixed.
* The labels are now aligned between left and right sides, this looks way better!

But the Y offset is not. Here is how it looks now:

![Bad](https://github.com/Regalis11/Barotrauma/assets/545007/ebaa9453-872b-4575-804f-06438d3f9109)

(excuse the weird gamma, but windows applied auto HDR and this affects the screenshots)

I can't try or test my own fix for this at the moment, as I can't match the results building the public repo locally.
It seems that even though the public repo release is tagged as v1.1.18.0, the behavior here is not matching the version shipped on steam yesterday.

Can you please reopen?

**Comment by Regalis11** [comment] 2023-10-20 06:16
Hmm, it could be we didn't test the issue with such a huge number of connections. :/

> It seems that even though the public repo release is tagged as v1.1.18.0, the behavior here is not matching the version shipped on steam yesterday.

Could you elaborate on this? The code in the public repo should match the Steam version, what kind of differences did you notice?

**Comment by mizvekov** [comment] 2023-10-20 06:56
Sure I can elaborate.

On the version built from the public git repo using VS 2022 17.8.0p4 I see very opposite results;

* The connector scaling is *NOT* fixed.
* The inverted mouse movement bug is *NOT* fixed.
* The Y offset looks OK.

![image](https://github.com/Regalis11/Barotrauma/assets/545007/5619d788-1dff-4da3-8359-3b90d445fafb)

This is testing on the same machine, with the same screen and resolution.

![image](https://github.com/Regalis11/Barotrauma/assets/545007/c079b17e-246a-471c-9fab-1fd5a868196c)

**Comment by mizvekov** [comment] 2023-10-20 07:06
This was all testing on Windows 11 machine.

I just tested the steam release on MacOS ARM64 machine, I see results identical to the ones I got building on windows from source.
So the odd one out is the Windows Steam release.

**Comment by Regalis11** [comment] 2023-10-20 07:31
I'm afraid I couldn't reproduce the issue.
![image](https://github.com/Regalis11/Barotrauma/assets/14351070/53f568f2-43e6-427a-9178-13fa36e19068)

If I'm not mistaken, you're using Cs for barotrauma and Lua for Barotrauma? Those override the entire game executable, and at least Cs For Barotrauma doesn't seem to have been updated in a while, so that might explain the issue.

**Comment by mizvekov** [comment] 2023-10-20 07:39
I took care to test on windows without those mods, I verified game integrity to ensure I was running vanilla client, and I checked that the LuaForBarotrauma marker is not present.

![image](https://github.com/Regalis11/Barotrauma/assets/545007/d1add3ab-eb85-47e2-a1b0-c1f52f32ab98)

I don't believe the screenshot you posted is the same repro as me, as you are only testing 16 connections, on a very different initial window size.

To make sure and save time, you can test with this mod: https://steamcommunity.com/sharedfiles/filedetails/?id=3018125421

You can fire it up without any additional mods. It will miss the main functionality, but you should still be able to test the exact same layout that I am.

Otherwise, XML for reference:

```XML
<?xml version="1.0" encoding="utf-8"?>
<Items>
  <Item name="" identifier="miz.microlua" category="Electrical" Tags="smallitem,logic" maxstacksize="8" cargocontaineridentifier="metalcrate" description="" scale="0.5" impactsoundtag="impact_metal_light" isshootable="true">
    <Price baseprice="100" minleveldifficulty="15">
      <Price storeidentifier="merchantoutpost" />
      <Price storeidentifier="merchantcity" sold="false"/>
      <Price storeidentifier="merchantresearch" multiplier="1.25" />
      <Price storeidentifier="merchantmilitary" />
      <Price storeidentifier="merchantmine" />
      <Price storeidentifier="merchantengineering" multiplier="0.9" />
    </Price>
    <PreferredContainer primary="engcab"/>
    <PreferredContainer secondary="wreckengcab,abandonedengcab,outpostengcab,beaconengcab" amount="1" spawnprobability="0.05" />
    <Deconstruct time="10">
      <Item identifier="plastic" />
      <Item identifier="copper" />
      <Item identifier="tin" />
    </Deconstruct>
    <Fabricate suitablefabricators="fabricator" requiredtime="10">
      <RequiredSkill identifier="electrical" level="20" />
      <RequiredItem identifier="fpgacircuit" />
      <RequiredItem identifier="tin" />
    </Fabricate>
    <InventoryIcon texture="MicroLua.Inv.png" sourcerect="0,0,63,57" origin="0.5,0.5" />
    <Sprite texture="MicroLua.Spr.png" depth="0.8" sourcerect="0,0,32,32" origin="0.5,0.5" canflipx="false" />
    <MicroLua canbeselected="true" />
    <Body width="31" height="25" density="15" />
    <Holdable selectkey="Select" pickkey="Use" slots="Any,RightHand,LeftHand" msg="ItemMsgDetachWrench" PickingTime="5.0" aimpos="85,-10" handle1="0,0" attachable="true" aimable="true">
      <RequiredItem items="wrench" type="Equipped" />
    </Holdable>
    <ConnectionPanel selectkey="Action" canbeselected="true" msg="ItemMsgRewireScrewdriver" hudpriority="10">
      <GuiFrame relativesize="0.2,0.8" minsize="480,1200" maxsize="520,1300" anchor="Center" style="ConnectionPanel" />
      <RequiredItem items="screwdriver" type="Equipped" />
      <input name="signal_in1" displayname="connection.signalinx~[num]=1" />
      <input name="signal_in2" displayname="connection.signalinx~[num]=2" />
      <input name="signal_in3" displayname="connection.signalinx~[num]=3" />
      <input name="signal_in4" displayname="connection.signalinx~[num]=4" />
      <input name="signal_in5" displayname="connection.signalinx~[num]=5" />
      <input name="signal_in6" displayname="connection.signalinx~[num]=6" />
      <input name="signal_in7" displayname="connection.signalinx~[num]=7" />
      <input name="signal_in8" displayname="connection.signalinx~[num]=8" />
      <input name="signal_in9" displayname="connection.signalinx~[num]=9" />
      <input name="signal_in10" displayname="connection.signalinx~[num]=10" />
      <input name="signal_in11" displayname="connection.signalinx~[num]=11" />
      <input name="signal_in12" displayname="connection.signalinx~[num]=12" />
      <input name="signal_in13" displayname="connection.signalinx~[num]=13" />
      <input name="signal_in14" displayname="connection.signalinx~[num]=14" />
      <input name="signal_in15" displayname="connection.signalinx~[num]=15" />
      <input name="signal_in16" displayname="connection.signalinx~[num]=16" />
      <input name="signal_in17" displayname="connection.signalinx~[num]=17" />
      <input name="signal_in18" displayname="connection.signalinx~[num]=18" />
      <input name="signal_in19" displayname="connection.signalinx~[num]=19" />
      <input name="signal_in20" displayname="connection.signalinx~[num]=20" />
      <input name="signal_in21" displayname="connection.signalinx~[num]=21" />
      <input name="signal_in22" displayname="connection.signalinx~[num]=22" />
      <input name="signal_in23" displayname="connection.signalinx~[num]=23" />
      <input name="signal_in24" displayname="connection.signalinx~[num]=24" />
      <input name="signal_in25" displayname="connection.signalinx~[num]=25" />
      <input name="signal_in26" displayname="connection.signalinx~[num]=26" />
      <input name="signal_in27" displayname="connection.signalinx~[num]=27" />
      <input name="signal_in28" displayname="connection.signalinx~[num]=28" />
      <input name="signal_in29" displayname="connection.signalinx~[num]=29" />
      <input name="signal_in30" displayname="connection.signalinx~[num]=30" />
      <input name="signal_in31" displayname="connection.signalinx~[num]=31" />
      <input name="signal_in32" displayname="connection.signalinx~[num]=32" />

      <output name="signal_out1" displayname="connection.signaloutx~[num]=1" />
      <output name="signal_out2" displayname="connection.signaloutx~[num]=2" />
      <output name="signal_out3" displayname="connection.signaloutx~[num]=3" />
      <output name="signal_out4" displayname="connection.signaloutx~[num]=4" />
      <output name="signal_out5" displayname="connection.signaloutx~[num]=5" />
      <output name="signal_out6" displayname="connection.signaloutx~[num]=6" />
      <output name="signal_out7" displayname="connection.signaloutx~[num]=7" />
      <output name="signal_out8" displayname="connection.signaloutx~[num]=8" />
      <output name="signal_out9" displayname="connection.signaloutx~[num]=9" />
      <output name="signal_out10" displayname="connection.signaloutx~[num]=10" />
      <output name="signal_out11" displayname="connection.signaloutx~[num]=11" />
      <output name="signal_out12" displayname="connection.signaloutx~[num]=12" />
      <output name="signal_out13" displayname="connection.signaloutx~[num]=13" />
      <output name="signal_out14" displayname="connection.signaloutx~[num]=14" />
      <output name="signal_out15" displayname="connection.signaloutx~[num]=15" />
      <output name="signal_out16" displayname="connection.signaloutx~[num]=16" />
      <output name="signal_out17" displayname="connection.signaloutx~[num]=17" />
      <output name="signal_out18" displayname="connection.signaloutx~[num]=18" />
      <output name="signal_out19" displayname="connection.signaloutx~[num]=19" />
      <output name="signal_out20" displayname="connection.signaloutx~[num]=20" />
      <output name="signal_out21" displayname="connection.signaloutx~[num]=21" />
      <output name="signal_out22" displayname="connection.signaloutx~[num]=22" />
      <output name="signal_out23" displayname="connection.signaloutx~[num]=23" />
      <output name="signal_out24" displayname="connection.signaloutx~[num]=24" />
      <output name="signal_out25" displayname="connection.signaloutx~[num]=25" />
      <output name="signal_out26" displayname="connection.signaloutx~[num]=26" />
      <output name="signal_out27" displayname="connection.signaloutx~[num]=27" />
      <output name="signal_out28" displayname="connection.signaloutx~[num]=28" />
      <output name="signal_out29" displayname="connection.signaloutx~[num]=29" />
      <output name="signal_out30" displayname="connection.signaloutx~[num]=30" />
      <output name="signal_out31" displayname="connection.signaloutx~[num]=31" />
      <output name="signal_out32" displayname="connection.signaloutx~[num]=32" />
    </ConnectionPanel>
  </Item>
</Items>
```

**Comment by mizvekov** [comment] 2023-10-25 13:20
Thanks for the tip!

By the way, I am still a bit stumped on the different behavior I got, between Windows Steam version, Windows built locally, and MacOS.
I got the new Windows Update on steam, 1.1.18.1, and the difference persists.
They are otherwise running on the same screen with the same physical monitor and same resolution.

Which behavior do you observe on your end?

**Comment by mizvekov** [comment] 2023-10-25 16:03
Also, regarding the inverted mouse movement bug, when moving that connection panel, which I see on MacOS and locally built Windows version, but not on Windows Steam release, is that fixed as well, or should I file a separate bug?

**Comment by Jasontti** [comment] 2024-01-15 15:03
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4582/commits/0a79b8149bb207a9c71b6350a4c3dfd67ab0ebf3

Recreated the connectionpanel with many connections.
Checked vanilla items with connectionpanel

No issues found
Closing ticket

**Closed by Jasontti** 2024-01-15 15:03 UTC
Labels: Bug, Code, Testing branch
