### ISSUE TITLE
[Unstable] Natural Abandoned Outposts never get their mission.

### ISSUE THREAD

**Issue by Llolpros** [Regalis11/Barotrauma#5536] opened 2021-04-17 08:42 UTC
Naturally spawned abandoned outposts never have a mission when you enter them, and they never become habited.
The only thing in these abandoned outposts is the loot.

Steps To Reproduce
Go to any abandoned outpost that naturally spawned on the map, not created from a nearby hunting grounds or other reason outposts may become abandoned.

I am using MacOS

Abandoned outposts that used to be regular outposts will have the mission and will become habited again when you complete them, this problem is only the ones that were always abandonedndoned when the map was generated

The save I am playing in:
[The Imperial Gold.save.zip](https://github.com/Regalis11/Barotrauma/files/6328869/The.Imperial.Gold.save.zip)

**Comment by Regalis11** [comment] 2021-04-17 13:46
Thank you for the report!

Normally the game should automatically select a mission for all of the naturally spawning abandoned outposts. I gave this a rest (saving and quitting a few times and completing a couple of the missions), and everything seemed to be working correctly. In this save there's no missions in any of them for some reason, and I'm not quite sure how that could've happened. It seems there was a mod called "No" enabled when the campaign was saved, I wonder if it modifies the location types or map generation in some way that could've caused it?

**Comment by Llolpros** [comment] 2021-04-17 17:12
Thats odd because I don't have any mods enabled or downloaded, could the problem be that since I had started this save in the regular version and switched it to unstable later on it disabled a couple of the things that should have been there?

**Comment by Regalis11** [comment] 2021-04-19 07:25
Ah, that's probably the cause. Thanks for the extra info, I'll do some more debugging!

**Comment by Llolpros** [comment] 2021-04-19 07:29
Im currently testing it, I made a new save but started it in unstable, im trying to speed run my way through the map to reach an abandoned outpost to see if the mission will be there or not, ill let you know how it goes when I reach one

**Comment by Regalis11** [comment] 2021-04-19 07:34
You can also use the console command "togglecampaignteleport" which allows you to teleport from location to another by double-clicking them on the campaign map. ;)

**Comment by Llolpros** [comment] 2021-04-19 07:45
I forgot about console commands, what's the button to pull up the window on Mac? The default is F3 and we don't have an F3 on Macs

**Comment by Regalis11** [comment] 2021-04-19 08:26
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b5b53cf1d081095c8dff7d60216a02de70c90ea2

**Comment by Rokvach** [comment] 2021-04-19 12:17
Tested, wasn't able to reproduce. Seems to be working correctly. Closing.

**Closed by Rokvach** 2021-04-19 12:17 UTC
Labels: Bug, Code, High prio
