### ISSUE TITLE
[0.9.9.0] Spams of "Attempted to access a potentially removed character..."

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2525] opened 2020-03-28 19:53 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When characters/creatures are dead, console floods with:

Attempted to access a potentially removed character. Character: (Any Previously Dead Characters), id: (Entity ID), removed: True. AnimController.Collider == null

**Version**
0.9.9.0

**Comment by Regalis11** [comment] 2020-04-03 09:01
Haven't been able to reproduce this, but we added some additional info to the error message that should help figuring out what's causing this.

**Comment by Regalis11** [comment] 2020-05-08 12:40
Haven't seen this occur since, lets close this and reopen if it resurfaces

**Comment by ekqvist** [comment] 2020-05-14 09:15
Just had this happen to me when I started a new campaign in the `feature/campaign-groundwork` branch

```
Attempted to access a potentially removed character. Character: Maira Aker, id: 1128, removed: True. AnimController.Collider == null
   at System.Environment.get_StackTrace()
   at Barotrauma.Character.get_SimPosition() in C:\Git Repos\Barotrauma\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 609
   at Barotrauma.Character.get_Position() in C:\Git Repos\Barotrauma\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 626
   at Barotrauma.Entity.get_WorldPosition() in C:\Git Repos\Barotrauma\Barotrauma\BarotraumaShared\SharedSource\Map\Entity.cs:line 95
   at Barotrauma.CameraTransition.Update(Submarine sub, Camera cam)+MoveNext() in C:\Git Repos\Barotrauma\Barotrauma\BarotraumaShared\SharedSource\CameraTransition.cs:line 90
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in C:\Git Repos\Barotrauma\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 211
   at Barotrauma.CoroutineManager.Update(Single unscaledDeltaTime, Single deltaTime) in C:\Git Repos\Barotrauma\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 253
   at Barotrauma.GameMain.Update(GameTime gameTime) in C:\Git Repos\Barotrauma\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 972
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in C:\Git Repos\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in C:\Git Repos\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in C:\Git Repos\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Git Repos\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in C:\Git Repos\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in C:\Git Repos\Barotrauma\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
```

**Comment by ekqvist** [comment] 2020-05-14 09:21
Correction: it was a quickstart game, not campaign

**Comment by Regalis11** [comment] 2020-05-14 11:06
Couldn't find a way to repro, but I added some checks in https://github.com/Regalis11/Barotrauma-development/commit/020fc34ecc06183f9da69ea95b8202b55230dbce that should prevent that from happening again

**Comment by ekqvist** [comment] 2020-05-14 12:49
Yeah, I've started a new campaign probably at least a 100 times over the few days and this was the only time it happened. So, I cannot really say what happened this specific time that caused this.

**Comment by Rokvach** [comment] 2020-05-19 21:56
There's no valid way to actually test this other than wait and see if anything comes from it, so better to just close it and re-open if something does come up.

**Comment by Kaillera** [comment] 2020-05-25 13:07
![Capture](https://user-images.githubusercontent.com/5086682/82815386-10450400-9e67-11ea-9697-022451578d13.PNG)

[0.9.10.0 RC1] Was seeing this in singleplayer campaign from a Berilia Thalamus Wreck

**Comment by Regalis11** [comment] 2020-05-25 13:36
This error should now only be showed once per character, so in most cases it should be possible to keep playing even if it occurs. The error message now also always includes the stack trace (not just in debug/unstable builds) which should make diagnosing this easier.

**Comment by Regalis11** [comment] 2020-06-18 08:32
Got one of these again:
![4567678456](https://user-images.githubusercontent.com/14351070/84997496-57b56c00-b157-11ea-85d9-4c32d65c7e72.png)

No clear steps to repro, but I was departing from an outpost and got this during the end transition.

**Comment by Rokvach** [comment] 2020-06-20 13:57
Noticed this one from a crash report a tester posted on Discord

```
[18-6-2020 18:43:05] Attempted to access a potentially removed character. Character: Neal Heuer, id: 480, removed: True. AnimController.Collider == null
   at System.Environment.get_StackTrace()
   at Barotrauma.Character.get_SimPosition() in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 660
   at Barotrauma.Character.get_Position() in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 677
   at Barotrauma.Entity.get_WorldPosition() in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Map\Entity.cs:line 102
   at Barotrauma.TriggerAction.Update(Single deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Events\EventActions\TriggerAction.cs:line 70
   at Barotrauma.ScriptedEvent.Update(Single deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Events\ScriptedEvent.cs:line 182
   at Barotrauma.EventManager.Update(Single deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Events\EventManager.cs:line 510
   at Barotrauma.GameSession.Update(Single deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 465
   at Barotrauma.GameScreen.Update(Double deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 133
   at Barotrauma.GameMain.Update(GameTime gameTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 958
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
```

**Comment by Rokvach** [comment] 2020-06-22 07:10
Managed to finally get one by myself when I was testing out the buying all submarines networking issue, no idea as to why it prompted but it was right when I loaded in to outpost from lobby.

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/77a5ec88-cba2-4a2c-89be-131048c28368)

**Comment by Regalis11** [comment] 2020-06-22 09:06
The above three errors seem to be caused by the same issue, should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/9f6b28b8910e1c75797ab3c0e79dfc9519d56701

**Comment by Regalis11** [comment] 2020-06-25 13:16
Another occurrence during internal v0.1005.0.0 testing session:

```
Tried to apply an attack to a removed character (Tigerthresher).
   at System.Environment.get_StackTrace()
   at Barotrauma.Character.ApplyAttack(Character attacker, Vector2 worldPosition, Attack attack, Single deltaTime, Boolean playSound, Limb targetLimb) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2779
   at Barotrauma.Attack.DoDamageToLimb(Character attacker, Limb targetLimb, Vector2 worldPosition, Single deltaTime, Boolean playSound) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\Attack.cs:line 459
   at Barotrauma.Items.Components.Projectile.HandleProjectileCollision(Fixture target, Vector2 collisionNormal, Vector2 velocity) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Projectile.cs:line 554
   at Barotrauma.Items.Components.Projectile.Update(Single deltaTime, Camera cam) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Projectile.cs:line 414
   at Barotrauma.Item.Update(Single deltaTime, Camera cam) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 1437
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 518
   at Barotrauma.GameScreen.Update(Double deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 234
   at Barotrauma.GameMain.Update(GameTime gameTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 959
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59
```

**Comment by Regalis11** [comment] 2020-06-25 17:12
The above error should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/6f3d7f37a3307c12cd7cb69df13ebc918d1e33c3

**Comment by Rokvach** [comment] 2020-09-01 08:18
There hasn't been any new sightings to this issue, closing as it seems to be working correctly now.

**Closed by Rokvach** 2020-09-01 08:18 UTC
Labels: Bug, Code
