### ISSUE TITLE
Bug regarding weapons xp in game.

### ISSUE THREAD

**Issue by MrTeco** [Regalis11/Barotrauma#2734] opened 2020-04-28 20:00 UTC
The explanation is simple: you get weapons xp over time when just holding a fire extinguisher.

**Comment by thegrb93** [comment] 2020-04-28 20:27
I don't what it is, but I do get random weapon level-ups too. Maybe its the ship's guns giving everyone xp?

**Comment by Regalis11** [comment] 2020-05-03 17:27
There was a bug that caused the turrets to give XP to the character who last operated it, even if the character was no longer manning the turret. So I'd guess it wasn't actually caused by the fire extinguisher. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1e07c58ed79df436cadcf6f61b39ddbda67a1bfd

**Comment by Rokvach** [comment] 2020-05-03 22:14
No issues, closing.

**Closed by Rokvach** 2020-05-03 22:14 UTC
Labels: Bug, Code
