### ISSUE TITLE
Linked Submarines - When docked to the main sub and depending on position of both ports in the two subs, the hull the ports create are not connected properly

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4638] opened 2021-01-04 22:19 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When linked submarines are docked to the main sub and depending on the positions of both ports in the two subs, the hull the ports create are not connected properly:

[Dandelion.zip](https://github.com/Regalis11/Barotrauma/files/5767031/Dandelion.zip)
![Capture](https://user-images.githubusercontent.com/5086682/103585320-ddf58d80-4eb0-11eb-9609-a87abc9dfbef.PNG)

Players can kill themselves by standing inbetween the hulls or even slip through the non-hull gap in between and get sucked out to their deaths below.

**Version**
~0.1200.0.1

**Additional Information**
So far my only fix to this issue from the sub editor side is to pull in the ports on both sides by 3 nudges inward into the subs.

**Comment by Regalis11** [comment] 2021-01-05 12:39
Duplicate of https://github.com/Regalis11/Barotrauma/issues/4580

**Closed by Regalis11** 2021-01-05 12:39 UTC
