### ISSUE TITLE
Rollback

### ISSUE THREAD

**Issue by Brubio27** [Regalis11/Barotrauma#8886] opened 2022-04-21 13:38 UTC
Good morning, any way to go back to the previous version, I currently have this version (0.16. 7.0.) and it does not work on my dedicated server, is this possible.
first of all, Thanks

**Comment by Regalis11** [comment] 2022-04-21 13:50
Duplicate of https://github.com/Regalis11/Barotrauma/issues/8883

**Closed by Regalis11** 2022-04-21 13:50 UTC
