### ISSUE TITLE
[Request] Change hotkey/Position for Cleanup Item order

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4297] opened 2020-11-12 20:44 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
A lot of us who have played Barotrauma before the last update had been pretty used to Fix Damaged Systems on Maintenance+2, but it was moved to Maintenance+3 with Cleanup Item taking the old position. I think that order should probably be in Root+5 or Maintenance+5.

**Version**
~0.1100.0.5

**Comment by itchyOwl** [comment] 2020-11-13 11:51
Done: Regalis11/Barotrauma-development@25f22b3.

The positioning was not intentional, as it comes from the order where the orders are defined in the xml file. So just an oversight, good that you brought this up :thumbsup:

**Comment by Xeavas** [comment] 2020-11-13 17:53
[0.1100.0.6] - Working as intended, no issues, 👍
![orderwheel](https://user-images.githubusercontent.com/72674994/99104569-1d73cc00-261c-11eb-8ce6-e9b49fe4e85e.jpg)

**Comment by Rokvach** [comment] 2020-11-13 18:54
Closing.

**Closed by Rokvach** 2020-11-13 18:54 UTC
