### ISSUE TITLE
Massive server desync caused by spinelings

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#5493] opened 2021-04-09 20:15 UTC
**Description**
After about 8 spinelings spawned and fought for about a minute on a steam P2P server, it froze. Heres a gif of what started hapenning:
![spinelag](https://user-images.githubusercontent.com/59519434/114235829-0ba31480-9981-11eb-9a06-69f6530088f2.gif)

**Steps To Reproduce**
-the same level from #5492 is where this spineling event hapenned, might be worth trying it there

**Version**
Unstable

**Comment by Rokvach** [comment] 2021-04-09 20:19
Recorded a video of this as well
https://www.youtube.com/watch?v=SqXh1GfF8IU

**Comment by Rokvach** [comment] 2021-04-09 21:08
This might be cause of the lack of code optimization in Unstable builds as I haven't seen anyone really complaining about it on release builds but it comes up very often during Unstable

**Comment by itchyOwl** [comment] 2021-04-15 22:10
Seems to be physics related issue caused by the spikes. Managed to catch it in profiler in a single player game.

**Comment by itchyOwl** [comment] 2021-04-16 00:01
Addressed in Regalis11/Barotrauma-development@28b78cd. I doubt it's an issue anymore.

But the actual root cause for it remains unsolved, and I suspect that something else could trigger it too, like harpoon spears stuck on characters.

**Comment by Rokvach** [comment] 2021-04-16 12:02
Tested in singleplayer and multiplayer, no matter how many spinelings I spawned it didn't dramatically affect my framerate. Working correctly, closing.

**Closed by Rokvach** 2021-04-16 12:02 UTC
Labels: Bug, Code, Performance
