### ISSUE TITLE
Crash when round starts

### ISSUE THREAD

**Issue by Matteusvega** [Regalis11/Barotrauma#9991] opened 2022-10-05 23:05 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I crash everytime the round starts, has happened everytime.

### Reproduction steps

1. Start a multiplayer campaign
2. Enter an outpost
3. Exit the outpost then the game crashes

### Bug prevalence

Happens every time I play

### Version

0.19.10.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 10/05/2022 19:52:59)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


F1A12F872659D6F7FA0B56528941E10C


Game version 0.19.10.0 (ReleaseWindows, branch release, revision 811fb37ab3)
Graphics mode: 1024x768 (Fullscreen)
VSync ON
Language: English
Selected content packages: Vanilla
Level seed: BrunhesZamoroska
Loaded submarine: Barsuk (E7CF000DE67EC3DF418A325CB6FBD052)
Selected screen: Barotrauma.RoundSummaryScreen
SteamManager initialized
Client (Round hadn't been started)


System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: Intel(R) HD Graphics
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: La instancia de dispositivo de GPU se ha suspendido. Use GetDeviceRemovedReason para averiguar cuál es la acción adecuada.
 (SharpDX.SharpDXException)
Device removed reason: HRESULT = 0x887A0006
Target site: Void PlatformPresent()
Stack trace: 
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 1017
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58


Last debug messages:
[10/05/2022 19:52:54] Level identifier: coldcavernsadvanced
[10/05/2022 19:52:45] Matteusvega
[10/05/2022 19:52:45] warudo
[10/05/2022 19:52:45] Burntalicious
[10/05/2022 19:52:45] zerna
[10/05/2022 19:52:45] BenDaLife
[10/05/2022 19:52:45] Matteusvega
[10/05/2022 19:52:45] warudo
[10/05/2022 19:52:45] Burntalicious
[10/05/2022 19:52:45] zerna
[10/05/2022 19:52:45] BenDaLife
[10/05/2022 19:52:44] Matteusvega
[10/05/2022 19:52:44] warudo
[10/05/2022 19:52:44] Burntalicious
[10/05/2022 19:52:44] zerna
[10/05/2022 19:52:44] BenDaLife
[10/05/2022 19:51:02] Matteusvega
[10/05/2022 19:51:02] warudo
[10/05/2022 19:51:02] Burntalicious
[10/05/2022 19:51:02] zerna
[10/05/2022 19:51:02] BenDaLife
[10/05/2022 19:45:53] Matteusvega
[10/05/2022 19:45:52] warudo
[10/05/2022 19:45:52] Burntalicious
[10/05/2022 19:45:52] zerna
[10/05/2022 19:45:51] BenDaLife
[10/05/2022 19:45:48] Received STARTGAMEFINALIZE packet. Round init status: Started
[10/05/2022 19:45:48]  -0: EstimateSteamLobbyPing (STEAM_1:0:534364857), WaitingForActivation
[10/05/2022 19:45:48] Task count: 1
[10/05/2022 19:45:48] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[10/05/2022 19:45:42] Generating an outpost for the start of the level... (Location: Zamoroska Outpost, level type: Outpost)
[10/05/2022 19:45:42] Level identifier: outpostlevel
[10/05/2022 19:45:28] warudo
[10/05/2022 19:45:28] Burntalicious
[10/05/2022 19:45:28] zerna
[10/05/2022 19:45:28] BenDaLife
[10/05/2022 19:45:28] warudo
[10/05/2022 19:45:28] Burntalicious
[10/05/2022 19:45:28] zerna
[10/05/2022 19:45:28] BenDaLife
[10/05/2022 19:45:27] warudo
[10/05/2022 19:45:27] Burntalicious
[10/05/2022 19:45:27] zerna
[10/05/2022 19:45:27] BenDaLife
[10/05/2022 19:45:27] warudo
[10/05/2022 19:45:27] Burntalicious
[10/05/2022 19:45:27] zerna
[10/05/2022 19:45:27] BenDaLife
[10/05/2022 19:40:52] warudo
[10/05/2022 19:40:52] Burntalicious
[10/05/2022 19:40:52] zerna
[10/05/2022 19:40:52] BenDaLife
[10/05/2022 19:40:50] Received STARTGAMEFINALIZE packet. Round init status: Started
[10/05/2022 19:40:46]  -0: EstimateSteamLobbyPing (STEAM_1:0:534364857), WaitingForActivation
[10/05/2022 19:40:46] Task count: 1
[10/05/2022 19:40:42] Generating an outpost for the start of the level... (Location: Zamoroska Outpost, level type: LocationConnection)
[10/05/2022 19:40:39] Generating an outpost for the end of the level... (Location: Sontu Outpost, level type: LocationConnection)
[10/05/2022 19:40:38] Level identifier: coldcavernsbasic
[10/05/2022 19:39:16] Attempting to open ALC device "OpenAL Soft on Auriculares (2- High Definition Audio Device)"
[10/05/2022 19:39:09] Logged in as Matteusvega (SteamID STEAM_1:1:424803471)
```

**Comment by Regalis11** [comment] 2022-10-06 07:33
Duplicate of https://github.com/Regalis11/Barotrauma/issues/1833. There are also some potential ways to fix the crash listed in the ticket, please take a look and see if any of those help! Sorry for the inconvenience.

**Closed by Regalis11** 2022-10-06 07:33 UTC
