### ISSUE TITLE
Pirate Supmarines have no dive suits, crew dies Instantly

### ISSUE THREAD

**Issue by Notmaximluenenstrass** [Regalis11/Barotrauma#11619] opened 2023-03-21 09:30 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The other day I was doing a kill a coalition submarine mission for the seperatists. It all went normal at first, The submarine (a dougong) spawnend, attacked my sub (a humbback) and sunk after a few coilgun shots. However when I boarded the downed sub, something was off. The crew was dead, crushed by water pressure, after inspecting the sub i realized that it had spawned completely without any diving suits. All of the lockers where also empty. I have tried replicating this bug through missions and it seems that coalition submarines sometimes spawn without equipment.

### Reproduction steps

1.Open a Server
2.Select Pirate Mission
3.Board enemy Submarine

### Bug prevalence

Happens every now and then

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Notmaximluenenstrass** [comment] 2023-03-21 18:11
Edit: This bug happens in campain everytime. Every single enemy sub spawned without dive suits, loot and even without ammo. Allthough I have only tested it with coalition subs in campain. Will test more.

**Comment by Regalis11** [comment] 2023-03-22 02:27
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11423

**Closed by Regalis11** 2023-03-22 02:27 UTC
