### ISSUE TITLE
The game is crashing right after I try to open it

### ISSUE THREAD

**Issue by Yunnero** [Regalis11/Barotrauma#7421] opened 2021-11-20 19:01 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When I start the game, it immediately crashes and appear a window where it is written "A crash report ('crashreport (6).log") was saved in the root folder of the game. The error was not sent to the developers because user statistics have been disabled, but if you'd like to help fix this bug, you may post it on Barotrauma's GitHub issue tracker: https://github.com/Regalis11/Barotrauma/issues/". When i click OK, the game closes and appear a crashreport.txt 

**Steps To Reproduce**
1- Click play on steam or opening the game by the .exe on game folder
2- The game crashes :D 

**Version**
I was playing the game yesterday and today the game do not open anymore. Its the last version of the game (idk where i can see the version number). 

My PC is a windows 10 64x bits
Processor: Intel(R) HD Graphics 630
RAM: 8GB
GPU: NVIDIA GeForce GTX 1050

**Additional information**
IWhere can i send the crashreport?

**Comment by Yunnero** [comment] 2021-11-20 19:05
Barotrauma Client crash report (generated on 20/11/2021 15:47:07)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


53369B525C73F08AF404DBAF116B0ADA


Game version 0.15.13.0 (ReleaseWindows, branch release, revision 4e66dd7b5d)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.19042.0 64 bit
    GPU name: NVIDIA GeForce GTX 1050
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,7777778}
    GPU status: Normal


Exception: HRESULT: [0x8876017C], Module: [Unknown], ApiCode: [Unknown/Unknown], Message: Unknown (SharpDX.SharpDXException)
Target site: Void CheckError()
Stack trace: 
   at SharpDX.Result.CheckError()
   at SharpDX.DXGI.SwapChain.Present(Int32 syncInterval, PresentFlags flags)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 1010
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Present() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.cs:line 601
   at Microsoft.Xna.Framework.SdlGamePlatform.Present() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 251
   at Microsoft.Xna.Framework.Game.EndDraw() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 523
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 511
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 61


Last debug messages:
[20/11/2021 15:47:07] Attempting to open ALC device "OpenAL Soft on Alto-falantes (Realtek High Definition Audio)"
[20/11/2021 15:47:06] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[20/11/2021 15:47:06] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[20/11/2021 15:47:03] Logged in as yunnerothegamer (SteamID STEAM_1:1:628653532)

**Comment by Regalis11** [comment] 2021-11-23 16:37
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7055

**Closed by Regalis11** 2021-11-23 16:37 UTC
