### ISSUE TITLE
Game crashes mid game

### ISSUE THREAD

**Issue by tuffboy13** [Regalis11/Barotrauma#2738] opened 2020-04-29 05:40 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

This has happened several times with no obvious pattern. It can happen within a couple of minutes of game play, or up to an hour. The time it takes to crash may be decreasing each time, but I'm not 100% sure.

Here's the crash report:

Barotrauma Client crash report (generated on 4/28/2020 10:24:55 PM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

B88397013C2378C4A99C3E19DEBEE54F

Game version 0.9.9.0 (ReleaseWindows, branch release, revision 0534150c8)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Selected content packages: Vanilla 0.9
Level seed: TaraSkaani
Loaded submarine: Dugong 2 (927D5BD0B58F6EF54289AAF7AA77E206)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)

System info:
    Operating system: Microsoft Windows NT 10.0.18362.0 64 bit
    GPU name: Intel(R) UHD Graphics 620
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.
 (SharpDX.SharpDXException)
Device removed reason: HRESULT = 0x887A0006
Target site: Void CheckError()
Stack trace: 
   at SharpDX.Result.CheckError()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent()
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Barotrauma.Program.Main(String[] args)

Last debug messages:
[4/28/2020 10:20:46 PM] tuffboy13
[4/28/2020 10:20:45 PM] Gravityowl
[4/28/2020 10:20:45 PM] Pumpkin.Spice
[4/28/2020 10:20:45 PM] dndy778
[4/28/2020 10:20:45 PM] bruh
[4/28/2020 10:20:45 PM] Zoomander
[4/28/2020 10:20:11 PM] Content package load order: Vanilla 0.9
[4/28/2020 10:18:38 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[4/28/2020 10:18:38 PM] Content package load order: Vanilla 0.9
[4/28/2020 10:18:37 PM] Content package load order: Vanilla 0.9
[4/28/2020 10:18:35 PM] Attempting to open ALC device "OpenAL Soft"
[4/28/2020 10:18:34 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[4/28/2020 10:18:34 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[4/28/2020 10:18:33 PM] Logged in as tuffboy13 (SteamID STEAM_1:0:76110618)

**Comment by Regalis11** [comment] 2020-04-29 07:23
Duplicate of #1833

**Closed by Regalis11** 2020-04-29 07:23 UTC
