### ISSUE TITLE
Adding unidentified genetic material to an identified genetic material of any type sets its condition to 100

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#6638] opened 2021-09-11 22:28 UTC
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Adding an unidentified genetic material (any of them) to any genetic material will set its "effectiveness" to their max.

**Steps To Reproduce**
Put an identified and an unidentified genetic material in the research station.

**Version**
0.15.2.0

**Comment by Regalis11** [comment] 2021-09-13 08:38
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ebf7271bdb5e069d5fd26a7ae641fc9236406c3c

**Comment by Rokvach** [comment] 2021-09-13 10:30
I get 100% genetic materials now when combining a unindentified genetic material with a stabilozine, when previously it only resulted in a ~15% genetic material

**Comment by Regalis11** [comment] 2021-09-13 10:50
That's not the case, the materials do spawn with the correct condition. The problem was that displaying the condition was disabled in https://github.com/Regalis11/Barotrauma-development/commit/dbb44837

**Comment by Rokvach** [comment] 2021-09-13 12:53
I was still able to reproduce the original issue

Repro steps:
1. Craft a genetic material
2. Place it on the research station with a unidentified genetic material
3. Notice that the research station shows that they are combinable
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/6175035c-b52c-491b-aa53-c0e80a9d99fd)
4. Combining them results in unidentified genetic material to be consumed and you are left with a 100% genetic material 
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/862e7e7c-0fe4-49e4-af56-94c1e10a4a02)

**Comment by Rokvach** [comment] 2021-09-13 12:57
Update it seems that it only happened with unidentified genetic materials that I had already saved in the submarine

**Comment by Rokvach** [comment] 2021-09-13 12:58
Tested, working correctly as I was just using a outdated unidentified genetic material to test it. Closing.

**Closed by Rokvach** 2021-09-13 12:58 UTC
Labels: Bug, Code
