### ISSUE TITLE
Bots taking all welding fuel tank stored in locker instead of 1 to replace empty tank

### ISSUE THREAD

**Issue by mrjpjr** [Regalis11/Barotrauma#10938] opened 2023-01-14 22:51 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Bots take all welding fuel tanks (including inside storage containers) stored in a Supply Cabinet, and drops them on the ground, until all tanks are taken out of storage.

Video of behaviour below.

### Reproduction steps

1. Give bot welding tool with empty tank
2. Place items in storage including welding fuel. Fill all slots
3. Create hole to repair

Result:
Bot will keep taking and dropping welding fuel tanks until there are no more tanks in storage. The tanks will be on the floor.

Items in the supply cabinet:
![supply cabinet itinerary](https://user-images.githubusercontent.com/58775950/212500223-c473b226-d7d5-4c18-bd5f-0030392ff8a9.jpg)
Items in the top right storage container in the supply cabinet:
![storage container inventory](https://user-images.githubusercontent.com/58775950/212500277-7d389777-40b0-41a3-9fc7-b3aa9c42e32c.jpg)

Video of Behaviour:
(Video is too big to directly upload)
https://streamable.com/qgwqzn

### Bug prevalence

Happens every time I play

### Version

0.21.1.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by TheMinerBoy** [comment] 2023-01-15 00:30
Related to issue #10916

**Comment by itchyOwl** [comment] 2023-01-16 07:18
I'd say this is a duplicate of #10916, but impossible to say without testing/reproing. Added "needs testing" label.

**Closed** 2023-01-17 13:12 UTC
Labels: Bug, Needs testing, Code
