### ISSUE TITLE
The game crashes at the start of the mission

### ISSUE THREAD

**Issue by Bosson56** [Regalis11/Barotrauma#2653] opened 2020-04-18 04:17 UTC
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/4496034/crashreport.2.log)
[crashreport (3).log](https://github.com/Regalis11/Barotrauma/files/4496035/crashreport.3.log)
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/4496036/crashreport.log)

**Comment by Regalis11** [comment] 2020-04-18 15:38
Duplicate of #2620

**Closed by Regalis11** 2020-04-18 15:38 UTC
Labels: Bug, Code, Crash
