### ISSUE TITLE
Consistent crashing (collection was modified in Character.LoadTalents)

### ISSUE THREAD

**Issue by DTank0** [Regalis11/Barotrauma#10296] opened 2022-11-09 06:24 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I have been unable to continue this mission for a while now because of crashes, but the crashes never seem to occur from the same trigger. Although a thing of note is that my maxed-out apprentice assistants keep having their skill trees reset, and they have roughly 20 extra talent points. Here are my crash reports:
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/9967976/crashreport.2.log)
[crashreport (3).log](https://github.com/Regalis11/Barotrauma/files/9967977/crashreport.3.log)
[crashreport (4).log](https://github.com/Regalis11/Barotrauma/files/9967978/crashreport.4.log)
[crashreport (5).log](https://github.com/Regalis11/Barotrauma/files/9967979/crashreport.5.log)
[crashreport (6).log](https://github.com/Regalis11/Barotrauma/files/9967980/crashreport.6.log)

### Bug prevalence

Happens every time I play

### Version

0.20.3.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-11-11 10:16
Looks like the issue is the Graduation Ceremony talent. Steps to repro:

1. Unlock graduation ceremony
2. Move between levels until you get the error

Seems to occur because Graduation Ceremony unlocks a random talent tree every time it's initialized, causing new talents to be unlocked while loading them.

**Comment by 3e849f2e5c** [comment] 2022-11-11 14:58
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b414a06fda1938ba273d4802dde4d8a8928b234a

**Comment by NilanthAnimosus** [comment] 2022-11-30 15:42
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/2b57faa07493e732f98261ead832ba904168f57b, no issues found, closing.

**Closed by NilanthAnimosus** 2022-11-30 15:42 UTC
Labels: Bug, Code, Crash, Severe, Unstable
