### ISSUE TITLE
[0.9.703] Performance Issues

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2150] opened 2020-02-06 01:40 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Steps To Reproduce**
Play campaign for a several rounds.

**Description**
I was playing on Nil's debug server with Udraken, and started seeing weird performance issues.

After playing for several rounds, I've started getting some freeze frame to which I chalked it up to the event manager spawning in stuff like in previous version, but I don't believed to be the case. Unless the event manager spawning in this version has gotten very rapid? After a while, the freezing happened more often, and started being longer. When the freezing stop I would see everything happen at super speed, trying to sync up everything that happened during the freeze. Eventually it got to the point it was freezing up for so long, I was kicked in between for timing out from the server. When I unfreezed and got back in the lobby, I still heard running water sound from a breach we were having. My entire Windows PC started freezing long with short intermittent chance to click on other apps. I tried it to make it to the task manager to close Barotrauma, but it was such a struggle, I decided to just force shutdown my PC and reboot.

Also the game apparently wiped my config entirely when I launched the game after a forced shutdown. All my settings are gone.

**Version**
0.9.703
Windows

**Comment by Udrakan** [comment] 2020-02-06 02:06
I'm having reliable freezes when I enter a diving suit

**Comment by Regalis11** [comment] 2020-02-06 08:10
Most of the performance issues in the latest unstable build seem to be caused by a heavily increased number of monster spawns (in the higher-difficulty levels there can be over a hundred monsters spawned at once). We've scaled those values back heavily, but there could still be some other issues that affect this.

**Comment by Regalis11** [comment] 2020-02-06 11:07
Another thing that was causing performance issues was that the game would create the editing HUD for any item in the inventory with editable properties, even if that item was not selected. So for example, if you had a diving suit and a headset equipped, it would keep swapping between the diving suit and headset editing HUD (even though those HUDs are never drawn).

That was fixed in https://github.com/Regalis11/Barotrauma-development/commit/c5bb538, but there could also be other causes for the performance problems in this build

**Comment by Rokvach** [comment] 2020-02-07 20:24
Tested, there hasn't been any sudden performance drops in the 704 unstable version. Closing.

**Closed by Rokvach** 2020-02-07 20:24 UTC
Labels: Bug, Code, Performance
