### ISSUE TITLE
[Unstable] Floating minerals on the abyss Island

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#12357] opened 2023-07-15 00:04 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://github.com/Regalis11/Barotrauma/assets/59519434/c32ffcbc-7b4c-4d04-80df-0b90d8b4d612)
![image](https://github.com/Regalis11/Barotrauma/assets/59519434/edf87c14-13bf-48ff-9f40-6b5bd106c676)

### Reproduction steps

seed on pic, Unstable

### Bug prevalence

Happens every time I play

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-07-15 15:46
Thank you for the report!

This seems to be the same issue as https://github.com/Regalis11/Barotrauma/issues/10559. I unfortunately still haven't been able to find a way to reproduce the issue. For some reason I can't get it to occur with these parameters either (or maybe I just can't find where these minerals are in the level).
![image](https://github.com/Regalis11/Barotrauma/assets/14351070/068b6f58-2a36-4cad-aaec-85ac004c1c1b)

If anyone has a save file where this occurs, it might help us diagnose the problem. It's starting to seem like this isn't reproducible in the level editor for some reason - none of the seeds provided in the older ticket seemed to cause these floating minerals to generate in the editor either. The exact location of the minerals might also help (you can see the coordinates of the camera in the top-left corner if you enable `debugdraw`). Thanks and sorry for the inconvenience!

**Comment by Udrakan** [comment] 2023-07-15 22:22
Ah good point. I should have included the coordinates. Next time

**Comment by Regalis11** [comment] 2023-09-18 11:35
No known steps to repro, closing

**Closed by Regalis11** 2023-09-18 11:35 UTC
Labels: Bug, Need more info, Code
