### ISSUE TITLE
game cannot connect

### ISSUE THREAD

**Issue by BrotherSnake** [Regalis11/Barotrauma#4158] opened 2020-10-29 20:16 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Whenever i try to join most servers, it says cannot connect. i have good internet, no mods installed, and the only time i really can play is after multiple attempts to get in. Also the game will crash lots of times. either when im trying to connect or just randomly mid game.

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
this has been happening for about a month so latest versions. 
**Additional information**
My steam is BrotherSnake incase you need to look at my account

**Comment by BrotherSnake** [comment] 2020-10-29 20:17
Also ive been playing this game since before it came out on steam and have not had any problems until recently

**Comment by BrotherSnake** [comment] 2020-11-03 01:18
Barotrauma Client crash report (generated on 10/7/2020 3:34:42 PM)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


6F558E05A9FD96EA104348A23A5B582A


Game version 0.10.5.1 (ReleaseWindows, branch release, revision 9e259b2148)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.ServerListScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.18362.0 64 bit
    GPU name: NVIDIA GeForce GTX 970
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Boolean <AddPackage>b__0(Barotrauma.ContentPackage)
Stack trace: 
   at Barotrauma.ContentPackage.<>c__DisplayClass82_0.<AddPackage>b__0(ContentPackage p) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\ContentPackage.cs:line 717
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Barotrauma.ContentPackage.AddPackage(ContentPackage newPackage) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\ContentPackage.cs:line 717
   at Barotrauma.Steam.SteamManager.<>c__DisplayClass41_0.<InstallWorkshopItem>b__2(Task task, ContentPackage cp) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Networking\SteamManager.cs:line 1069
   at Barotrauma.TaskPool.Update() in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Utils\TaskPool.cs:line 77
   at Barotrauma.GameMain.Update(GameTime gameTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 957
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59


Last debug messages:
[10/7/2020 3:34:40 PM] Couldn't load content package "C:/Program Files (x86)/Steam/steamapps/common/Barotrauma/Mods/Toolbox Expanded/filelist.xml"!
[10/7/2020 3:34:40 PM] Couldn't load xml document "C:/Program Files (x86)/Steam/steamapps/common/Barotrauma/Mods/Toolbox Expanded/filelist.xml"! {The process cannot access the file 'C:\Program Files (x86)\Steam\steamapps\common\Barotrauma\Mods\Toolbox Expanded\filelist.xml' because it is being used by another process.}
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at Barotrauma.XMLExtensions.TryLoadXml(String filePath) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Serialization\XMLExtensions.cs:line 36
[10/7/2020 3:34:36 PM] LobbyMatchList:  LobbiesMatching: 50
[10/7/2020 3:34:36 PM] LobbyMatchList:  LobbiesMatching: 50
[10/7/2020 3:34:36 PM] SteamAPICallCompleted:   AsyncCall: 8455538403131782748
   Callback: 510
 ParamCount: 4
[10/7/2020 3:33:57 PM] Attempting to reconnect...
[10/7/2020 3:33:57 PM] Received a disconnect message (SteamP2P connection failed: Timeout)
[10/7/2020 3:33:36 PM] Attempting to reconnect...
[10/7/2020 3:33:36 PM] Received a disconnect message (SteamP2P connection failed: Timeout)
[10/7/2020 3:33:20 PM] Attempting to reconnect...
[10/7/2020 3:33:20 PM] Received a disconnect message (SteamP2P connection failed: Timeout)
[10/7/2020 3:33:04 PM] Attempting to reconnect...
[10/7/2020 3:33:04 PM] Received a disconnect message (SteamP2P connection failed: Timeout)
[10/7/2020 3:32:20 PM] LobbyMatchList:  LobbiesMatching: 50
[10/7/2020 3:32:20 PM] LobbyMatchList:  LobbiesMatching: 50
[10/7/2020 3:32:20 PM] SteamAPICallCompleted:   AsyncCall: 10028388854922029801
   Callback: 510
 ParamCount: 4
[10/7/2020 3:32:20 PM] AvatarImageLoaded:    SteamID: 76561198042207493
     Image: 690
      Wide: 184
      Tall: 184
[10/7/2020 3:32:20 PM] SteamRelayNetworkStatus:                      Avail: Current
 PingMeasurementInProgress: 1
        AvailNetworkConfig: Current
             AvailAnyRelay: Current
                  DebugMsg: System.Byte[]
[10/7/2020 3:27:34 PM] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/[ATLAS] Tetrarch.sub, size: 600x338)
[10/7/2020 3:27:32 PM] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/U-II Seahorse Mk XL.sub, size: 1339x838)
[10/7/2020 3:27:31 PM] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/Svarog.sub, size: 700x313)
[10/7/2020 3:27:30 PM] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/Scarabidae Mk5e.sub, size: 1460x561)
[10/7/2020 3:27:29 PM] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/RUSALKA 1.sub, size: 1259x787)
[10/7/2020 3:27:28 PM] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/Phorcys.sub, size: 1750x1080)
[10/7/2020 3:27:26 PM] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/Indra.sub, size: 700x313)
[10/7/2020 3:27:26 PM] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/Hyperion.sub, size: 600x338)
[10/7/2020 3:27:25 PM] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/EK_Coseus_Mk-II.sub, size: 1641x947)
[10/7/2020 3:27:24 PM] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/Cyclops mk II.sub, size: 1748x901)
[10/7/2020 3:27:18 PM] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/Bottleneck.sub, size: 1440x534)
[10/7/2020 3:27:17 PM] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/Alkonost.sub, size: 700x313)
[10/7/2020 3:26:59 PM] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/[ATLAS] Tetrarch.sub, size: 600x338)
[10/7/2020 3:26:57 PM] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/U-II Seahorse Mk XL.sub, size: 1339x838)
[10/7/2020 3:26:49 PM] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/Svarog.sub, size: 700x313)
[10/7/2020 3:26:47 PM] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/Scarabidae Mk5e.sub, size: 1460x561)
[10/7/2020 3:26:46 PM] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/RUSALKA 1.sub, size: 1259x787)
[10/7/2020 3:26:45 PM] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/Phorcys.sub, size: 1750x1080)
[10/7/2020 3:26:42 PM] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/Indra.sub, size: 700x313)
[10/7/2020 3:26:42 PM] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/Hyperion.sub, size: 600x338)
[10/7/2020 3:26:41 PM] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/EK_Coseus_Mk-II.sub, size: 1641x947)
[10/7/2020 3:26:40 PM] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/Cyclops mk II.sub, size: 1748x901)
[10/7/2020 3:26:39 PM] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/Bottleneck.sub, size: 1440x534)
[10/7/2020 3:26:38 PM] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/Alkonost.sub, size: 700x313)
[10/7/2020 3:25:28 PM] LobbyMatchList:  LobbiesMatching: 50
[10/7/2020 3:25:28 PM] LobbyMatchList:  LobbiesMatching: 50
[10/7/2020 3:25:28 PM] SteamAPICallCompleted:   AsyncCall: 12373333280902617561
   Callback: 510
 ParamCount: 4
[10/7/2020 3:24:11 PM] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/[ATLAS] Tetrarch.sub, size: 600x338)
[10/7/2020 3:24:09 PM] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/U-II Seahorse Mk XL.sub, size: 1339x838)
[10/7/2020 3:24:07 PM] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/Svarog.sub, size: 700x313)
[10/7/2020 3:24:06 PM] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/Scarabidae Mk5e.sub, size: 1460x561)
[10/7/2020 3:24:05 PM] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/RUSALKA 1.sub, size: 1259x787)
[10/7/2020 3:24:03 PM] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/Phorcys.sub, size: 1750x1080)
[10/7/2020 3:24:00 PM] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/Indra.sub, size: 700x313)
[10/7/2020 3:24:00 PM] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/Hyperion.sub, size: 600x338)
[10/7/2020 3:23:59 PM] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/EK_Coseus_Mk-II.sub, size: 1641x947)
[10/7/2020 3:23:57 PM] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/Cyclops mk II.sub, size: 1748x901)
[10/7/2020 3:23:55 PM] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/Bottleneck.sub, size: 1440x534)
[10/7/2020 3:23:53 PM] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/Alkonost.sub, size: 700x313)
[10/7/2020 3:23:47 PM] (Msg) RelayNetWorkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[10/7/2020 3:23:47 PM] (Msg) Ping location: okc=25+2,atl=31+3,ord=54+5/41+2,iad=43+4,lax=50+5,sea=56+5,eat=65+6/61+5,lhr=116+11,par=120+12/120+4,fra=131+13/129+4,gru=160+16/162+3,sgp=235+23/232+5
[10/7/2020 3:23:47 PM] (Msg) Ping measurement completed
[10/7/2020 3:23:46 PM] (Verbose) Communications with routing cluster 'sea' established.
[10/7/2020 3:23:46 PM] (Debug) Destroying relay 'sea#111 (205.196.6.148:27033)' because initial_ping_timeout
[10/7/2020 3:23:44 PM] (Verbose) Communications with routing cluster 'sgp' established.
[10/7/2020 3:23:44 PM] (Verbose) Communications with routing cluster 'syd' established.
[10/7/2020 3:23:44 PM] (Verbose) Communications with routing cluster 'tyo1' established.
[10/7/2020 3:23:44 PM] (Verbose) Communications with routing cluster 'vie' established.
[10/7/2020 3:23:44 PM] (Verbose) Communications with routing cluster 'tyo' established.
[10/7/2020 3:23:44 PM] (Verbose) Communications with routing cluster 'maa' established.
[10/7/2020 3:23:44 PM] (Verbose) Communications with routing cluster 'waw' established.
[10/7/2020 3:23:44 PM] (Verbose) Communications with routing cluster 'sto' established.
[10/7/2020 3:23:44 PM] (Verbose) Communications with routing cluster 'sto2' established.
[10/7/2020 3:23:44 PM] (Verbose) Communications with routing cluster 'jnb' established.
[10/7/2020 3:23:44 PM] (Verbose) Communications with routing cluster 'bom' established.
[10/7/2020 3:23:44 PM] (Verbose) Communications with routing cluster 'scl' established.
[10/7/2020 3:23:44 PM] (Verbose) Communications with routing cluster 'mad' established.
[10/7/2020 3:23:44 PM] (Verbose) Communications with routing cluster 'dxb' established.
[10/7/2020 3:23:44 PM] (Verbose) Communications with routing cluster 'lux' established.
[10/7/2020 3:23:44 PM] (Verbose) Communications with routing cluster 'par' established.
[10/7/2020 3:23:44 PM] (Verbose) Communications with routing cluster 'lim' established.
[10/7/2020 3:23:44 PM] (Verbose) Communications with routing cluster 'lhr' established.
[10/7/2020 3:23:44 PM] (Verbose) Communications with routing cluster 'hkg' established.
[10/7/2020 3:23:44 PM] (Verbose) Communications with routing cluster 'ord' established.
[10/7/2020 3:23:44 PM] (Verbose) Communications with routing cluster 'gru' established.
[10/7/2020 3:23:44 PM] (Verbose) Communications with routing cluster 'lax' established.
[10/7/2020 3:23:44 PM] (Verbose) Communications with routing cluster 'fra' established.
[10/7/2020 3:23:44 PM] (Verbose) Communications with routing cluster 'okc' established.
[10/7/2020 3:23:44 PM] (Verbose) Communications with routing cluster 'ams' established.
[10/7/2020 3:23:43 PM] (Verbose) Communications with routing cluster 'eat' established.
[10/7/2020 3:23:43 PM] (Verbose) Communications with routing cluster 'iad' established.
[10/7/2020 3:23:43 PM] (Verbose) Communications with routing cluster 'atl' established.
[10/7/2020 3:23:43 PM] (Msg) RelayNetWorkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[10/7/2020 3:23:43 PM] (Msg) Performing ping measurement
[10/7/2020 3:23:43 PM] (Msg) Got SDR network config.  Loaded revision 282 OK
[10/7/2020 3:23:16 PM] Attempting to open ALC device "OpenAL Soft on Speakers (Realtek High Definition Audio)"
[10/7/2020 3:23:14 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[10/7/2020 3:23:13 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[10/7/2020 3:23:12 PM] Logged in as Brother Snake (SteamID STEAM_1:1:47845730)

**Comment by Regalis11** [comment] 2020-12-06 17:59
This seems to sometimes happen when there's a large number of submarines in the "Submarine/Downloaded/" folder, and based on the crash report it seems that could be the cause here. We've got another ticket about the issue with a bit more info https://github.com/Regalis11/Barotrauma/issues/4432, closing this one.

**Closed by Regalis11** 2020-12-06 17:59 UTC
Labels: Bug, Code
