### ISSUE TITLE
Crash report(unstable)

### ISSUE THREAD

**Issue by gazzy5** [Regalis11/Barotrauma#3266] opened 2020-07-01 19:06 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Arrived at outpost upon mission complete, docking lead to game crash

**Steps To Reproduce**
complete a salvage wreck mission and return to previous destination. 
**Version**
Unstable build v0.10

**Additional information**
[crashreport (19).log](https://github.com/Regalis11/Barotrauma/files/4859919/crashreport.19.log)

**Comment by EdusFF** [comment] 2020-07-07 10:22
Attempted the steps both on the current state of the repository and on the revision in the crashlog, and wasn't able to reproduce. Might be either something entirely different that just manifested after those steps due to chance or something to do with the mods used.

**Comment by gazzy5** [comment] 2020-07-10 19:32
i figured that it was a one in a million crash or mod related. thanks!

**Comment by Regalis11** [comment] 2020-08-18 13:13
Without known steps to repro I don't think there's much we can do about this. We haven't gotten any additional reports about this since either, so there's a chance it was fixed as a side-effect of some other change. Closing for now, let's reopen if the issue reappears.

**Closed by Regalis11** 2020-08-18 13:13 UTC
Labels: Bug, Code, Crash, Need more info
