### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by DragonCola** [Regalis11/Barotrauma#3617] opened 2020-08-23 03:20 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

Game crashed just after I completed the mission and it was loading the next station/city and was told to send it here.

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

I went from the starting point, to a wrecked sub to which I looted, then encountered a small swarm of crawlers which I ended up killing them all but accidentally colliding with a wall in the process. told crew to repair the leaks as I was docking with the station at the end to which the game said it crashed after showing that I completed the mission.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

Game version: 0.10.4.0
Windows 10 64 bit

**Additional information**

[crashreport.log](https://github.com/Regalis11/Barotrauma/files/5113447/crashreport.log)

**Comment by Regalis11** [comment] 2020-08-24 07:00
Duplicate of #3559

**Closed by Regalis11** 2020-08-24 07:00 UTC
