### ISSUE TITLE
Hunter Genes description has incorrect melee damage numbers

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#11017] opened 2023-01-23 05:50 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The description of the Hunter genes cites an increase of 20-100% to melee damage, however the actual value ranges from 75-150%.
![image](https://user-images.githubusercontent.com/37850646/213972713-200d4305-e715-447d-9559-908909c274e5.png)
![image](https://user-images.githubusercontent.com/37850646/213973271-83e339af-34c5-4a4e-8979-413580458996.png)

### Bug prevalence

Just once

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-01-23 11:19
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8bf3459602b567912652c42385c688fd7c39bf03

**Comment by Vykn** [comment] 2023-01-24 15:51
Tested in both stable and unstable, found the increasedmeleedamage_temporary working as expected; Crowbar deals 5 damage without the affliction, 12 with (rounded from 12.5)

It is possible that the wrench deals such low damage that an increase in damage is rounded away; it deals a base of 4 damage, which is halved by natural resistances of humans.

Of course, if the testing was on a different build, and something is working differently, then my testing isn't important, but the stattype="MeleeAttackMultiplier" seems to be working correctly.

**Comment by JeroonBosch** [comment] 2023-01-25 07:26
Hmm yea, tested with some exaggerated numbers and it does seem to work as intended after all. Closing

**Closed by JeroonBosch** 2023-01-25 07:26 UTC
Labels: Bug, Design
