### ISSUE TITLE
Can't open hatch while on ladder anymore

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#10021] opened 2022-10-08 03:22 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Pressing E on a hatch while climbing a ladder should open it.

My bindings are
Select: E
Use: Mouse1
Deselect: E

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Ek-Videogames** [comment] 2022-10-08 04:05
[Skill Issue.](https://github.com/Regalis11/Barotrauma/issues/9655) 

Temporary workaround:
- Stop holding W on the ladder.
- Click to open the door twice quickly.
`(The first input gets eaten by the ladder, but the second input goes through)`
- Quickly press W again before your character falls off the ladder.

**Comment by thegrb93** [comment] 2022-10-08 05:20
That's what I've found as a workaround as well. Pretty annoying

**Comment by Regalis11** [comment] 2022-10-09 11:13
> Skill issue

It's not a skill issue, it's caused by the key to deselect the ladders being bound to the same key as the key to select the hatch. In your report there was no information on this happening specifically on non-default keybinds, which was why we failed to reproduce the problem. But since these keybinds seem to be fairly common, I think we need to look into addressing it.

**Comment by Regalis11** [comment] 2022-10-09 14:50
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/07463e4b56d1063a75a3a6078684fc2b5f935d4f

**Comment by Rokvach** [comment] 2022-10-14 07:42
Tested, working correctly. Closing.

**Closed by Rokvach** 2022-10-14 07:42 UTC
Labels: Bug, Code
