### ISSUE TITLE
[13.0.11] Bots get stuck repairing upper airlocks

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#5579] opened 2021-04-23 12:48 UTC
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots get stuck when trying to repair e.g. upper airlocks that are reachable via ladder, like in the Humpback.

**Steps To Reproduce**
Damage upper airlock in the Humpback
Set bot to repair duty
Bot tries to reach the airlock but cant
Bot stays stuck locked to the repair task
(also verifyable in other subs with such a design)

Expected: Bots climbs up the ladder to the airlock and does the repair.

**Additional information**
Repairing in such situations is also problematic for players, because when you press E to repair the airlock you get kicked off from the ladder.
I found a "workaround" by keeping the move-upward button pressed when pressing E to access the airlock. 
Bots cant do that, so they fail at this duty?

**Comment by itchyOwl** [comment] 2021-04-23 19:02
It's a known issue. Repairing/rewiring etc while holding to a ladders is not currently possible, so bots can't do that either. I don't know about "teaching" them such workarounds. Maybe, if we can't/won't make it possible to interact with other items while holding the ladders. It requires a lot of refactoring and hence might take a while to get it done. Thanks for the report anyway!

**Comment by Regalis11** [comment] 2021-04-26 07:29
Closing as a duplicate of https://github.com/Regalis11/Barotrauma/issues/5587

**Comment by CurePindal** [comment] 2021-04-26 13:29
This isnt a duplicate - this is about bots getting stuck

Even then #5587 is the duplicate. I posted this 3 days ago already.

**Comment by thegrb93** [comment] 2021-04-26 20:49
I think they just prioritized the other one because it is the root cause of this one and is simpler to understand.

**Comment by itchyOwl** [comment] 2021-04-28 10:35
It's a wider issue. Although this one can actually be fixed just by adding some waypoints over the platform:
![image](https://user-images.githubusercontent.com/5370738/116389914-2b15ba80-a826-11eb-9d1f-a42e5e23d415.png)

Fixed in Regalis11/Barotrauma-development@7316109.

Reopening the ticket and moving it to QA.

**Comment by Rokvach** [comment] 2021-04-28 11:28
Working correctly, but the bots went to fix it at the very start of the round, there might be some debug values still in use

**Closed** 2021-04-28 11:29 UTC
Labels: Bug
