### ISSUE TITLE
issues with the fractal guardian's hook

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#6922] opened 2021-10-14 23:21 UTC
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
https://user-images.githubusercontent.com/55637865/137408146-06015baa-9a31-4586-bf03-f7ac3f3d3c0a.mp4

**Steps To Reproduce**
I have no consistent way of causing it, but it seems to happen more in high ping servers on multiplayer, tho, the video in the ticket was taken in singleplayer

**Version**
v0.15.7.0

**Comment by Rokvach** [comment] 2021-10-18 16:54
Tested, wasn't able to reproduce the issue, seems to be working correctly. Closing.

**Comment by itchyOwl** [comment] 2021-11-10 18:59
A work-around fix for the issue was to detach the attached projectiles before teleporting outside (Regalis11/Barotrauma-development@508ba09). I think it's related to #7067, where the latched creatures somehow resulted to an invalid position when the character was teleported in/out. The extra joints and attached bodies probably aren't completely in sync, because they are not teleported exactly at the same time when the character is. I tried to fix this, but as it didn't seem to fix it, I setteled for a workaround instead. For some reason going inside from outside works, so I decided to not drop the projectiles in that case. But if it still glitches, need to reconsider this.

**Comment by itchyOwl** [comment] 2021-11-11 08:32
Properly fixed in Regalis11/Barotrauma-development@5c2b51f. The issue was that for a one frame the projectile was not where the target was, because the target was teleported out and the projectile transform synced with it on the next frame.

**Comment by Lithosagym** [comment] 2021-11-18 15:35
Tested, getting hooked out of a sub or ruin no longer displays any strange properties, fixed.

**Comment by Rokvach** [comment] 2021-11-18 17:02
Closing

**Closed by Rokvach** 2021-11-18 17:02 UTC
Labels: Bug, Code
