### ISSUE TITLE
Object referance not set to an instance of an object 

### ISSUE THREAD

**Issue by locobro82** [Regalis11/Barotrauma#11706] opened 2023-04-01 17:02 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

When I load up the save, it zooms in like normal, then it crashes with the crash report below.

[crashreport (19).log](https://github.com/Regalis11/Barotrauma/files/11130120/crashreport.19.log)

### Reproduction steps

1. Start campaign
2. Crash

(It was working fine before, then crashed all of the sudden)

### Bug prevalence

Just once

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Crash report (generated on 04/01/2023 12:30:36)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

14984747362A6EE8B69319866DD5C730

Game version 1.0.8.0 (ReleaseWindows, branch release/1.0-hotfix, revision 08ecc207eb)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla, EK | Dockyard, EK | Utility, EK | Armory, Better Dive Suits, Lua For Barotrauma, Snoring Moloch, FirearmEdit, EK | Gunnery, Girls' Frontline Gun Pack, Shipwrecks Extended, Wreck Locator, Breaking Bad Guitar, BaroDrama V4.1, Harmonica Free Bird solo, Dont Open Debug Console On Errors, Improved Husks, Decorations, 24H Cinderella microphone, Have It Your Way, Start or something idk, 40k Dark Mechanicus + Loyal Skitari, 40k Inspired Grand Inquisitor Uniforms, Commander Uniform, Reinforced Captain Uniforms, Combat Medic Uniform, Epic accordion, Fart Honk, Berilia but stupid, 合金装备崛起复仇BGM MGRR music, M.O.N.K.E. power suit, Clown-O-Trauma - Children of the Honkmother, Dead Space Uniforms (IN PROGRESS), Dead Space - Clean Advanced Soldier Suit, Enhanced Armaments
Level seed: Topol54Thaw80
Loaded submarine: Herja (1910B784AA387D0E29AECA7759747C98)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce GTX 1060 6GB
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void DrawHUDFront(Microsoft.Xna.Framework.Graphics.SpriteBatch, Barotrauma.GUICustomComponent)
Stack trace: 
   at Barotrauma.Items.Components.MiniMap.DrawHUDFront(SpriteBatch spriteBatch, GUICustomComponent container) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\Machines\MiniMap.cs:line 732
   at Barotrauma.GUICustomComponent.Draw(SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUICustomComponent.cs:line 43
   at Barotrauma.GUI.Draw(Camera cam, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 273
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\GameScreen.cs:line 159
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 984
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[04/01/2023 12:30:24] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Jeremy O'Neal/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2428833422/AlienArm1.png, size: 102x102)
[04/01/2023 12:30:17] WARNING: Character "Latcher" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -Infinity to Infinity.
[04/01/2023 12:30:15] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Jeremy O'Neal/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2728238685/Weapons/Tavor X95/TavorX95.png, size: 147x48)
[04/01/2023 12:30:15] WARNING: Potentially invalid damage modifier in "Marine Helmet, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[04/01/2023 12:30:09] Generating an outpost for the end of the level... (Location: Thaw Institute of Astrobiology, level type: LocationConnection)
[04/01/2023 12:30:07] Generating an outpost for the start of the level... (Location: Topol Mining Facility, level type: LocationConnection)
[04/01/2023 12:30:02] Level identifier: plateaubasic
[04/01/2023 12:30:02] WARNING: Character "Latcher" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -Infinity to Infinity.
[04/01/2023 12:30:02] WARNING: Potentially invalid damage modifier in "Military Mk-I Hardsuit, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[04/01/2023 12:30:02] WARNING: Potentially invalid damage modifier in "Military Mk-I Hardsuit, Wearable". Could not find any afflictions with the identifier "contamination". Did you mean to use an affliction type instead?
[04/01/2023 12:30:02] WARNING: Potentially invalid damage modifier in "Military Mk-I Hardsuit, Wearable". Could not find any afflictions with the identifier "glowing". Did you mean to use an affliction type instead?
[04/01/2023 12:30:02] WARNING: Potentially invalid damage modifier in "Military Mk-I Hardsuit, Wearable". Could not find any afflictions with the identifier "exposure". Did you mean to use an affliction type instead?
[04/01/2023 12:30:02] WARNING: Potentially invalid damage modifier in "Military Mk-I Hardsuit, Wearable". Could not find any afflictions with the identifier "radiation". Did you mean to use an affliction type instead?
[04/01/2023 12:30:02] WARNING: Potentially invalid damage modifier in "Military Mk-I Hardsuit, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[04/01/2023 12:30:02] WARNING: Potentially invalid damage modifier in "Military Mk-I Hardsuit, Wearable". Could not find any afflictions with the identifier "contamination". Did you mean to use an affliction type instead?
[04/01/2023 12:30:02] WARNING: Potentially invalid damage modifier in "Military Mk-I Hardsuit, Wearable". Could not find any afflictions with the identifier "glowing". Did you mean to use an affliction type instead?
[04/01/2023 12:30:02] WARNING: Potentially invalid damage modifier in "Military Mk-I Hardsuit, Wearable". Could not find any afflictions with the identifier "exposure". Did you mean to use an affliction type instead?
[04/01/2023 12:30:02] WARNING: Potentially invalid damage modifier in "Military Mk-I Hardsuit, Wearable". Could not find any afflictions with the identifier "radiation". Did you mean to use an affliction type instead?
[04/01/2023 12:30:02] WARNING: Potentially invalid damage modifier in "Military Mk-I Hardsuit, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[04/01/2023 12:30:02] WARNING: Potentially invalid damage modifier in "Military Mk-I Hardsuit, Wearable". Could not find any afflictions with the identifier "contamination". Did you mean to use an affliction type instead?
[04/01/2023 12:30:02] WARNING: Potentially invalid damage modifier in "Military Mk-I Hardsuit, Wearable". Could not find any afflictions with the identifier "glowing". Did you mean to use an affliction type instead?
[04/01/2023 12:30:02] WARNING: Potentially invalid damage modifier in "Military Mk-I Hardsuit, Wearable". Could not find any afflictions with the identifier "exposure". Did you mean to use an affliction type instead?
[04/01/2023 12:30:02] WARNING: Potentially invalid damage modifier in "Military Mk-I Hardsuit, Wearable". Could not find any afflictions with the identifier "radiation". Did you mean to use an affliction type instead?
[04/01/2023 12:30:02] WARNING: Potentially invalid damage modifier in "Marine Helmet, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[04/01/2023 12:30:01] WARNING: Potentially invalid damage modifier in "Marine Helmet, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[04/01/2023 12:30:01] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Jeremy O'Neal/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2428833422/Bundle of fractal.png, size: 102x101)
[04/01/2023 12:30:00] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Jeremy O'Neal/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2728238685/Weapons/Remington 870/Remington870.png, size: 191x39)
[04/01/2023 12:30:00] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Jeremy O'Neal/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2728238685/Ammunition/Mags/Stanag30.png, size: 20x42)
[04/01/2023 12:30:00] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Jeremy O'Neal/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2428833422/AlienHelm1.png, size: 102x101)
[04/01/2023 12:30:00] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Jeremy O'Neal/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2428833422/AlienTorso1.png, size: 102x101)
[04/01/2023 12:30:00] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Jeremy O'Neal/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2428833422/Red fractal part.png, size: 100x99)
[04/01/2023 12:29:59] WARNING: Potentially invalid damage modifier in "Military Mk-I Hardsuit, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[04/01/2023 12:29:59] WARNING: Potentially invalid damage modifier in "Military Mk-I Hardsuit, Wearable". Could not find any afflictions with the identifier "contamination". Did you mean to use an affliction type instead?
[04/01/2023 12:29:59] WARNING: Potentially invalid damage modifier in "Military Mk-I Hardsuit, Wearable". Could not find any afflictions with the identifier "glowing". Did you mean to use an affliction type instead?
[04/01/2023 12:29:59] WARNING: Potentially invalid damage modifier in "Military Mk-I Hardsuit, Wearable". Could not find any afflictions with the identifier "exposure". Did you mean to use an affliction type instead?
[04/01/2023 12:29:59] WARNING: Potentially invalid damage modifier in "Military Mk-I Hardsuit, Wearable". Could not find any afflictions with the identifier "radiation". Did you mean to use an affliction type instead?
[04/01/2023 12:29:57] Error in the fabrication recipe for "Advanced Soldier RIG". Could not find the ingredient "Barotrauma.FabricationRecipe+RequiredItemByIdentifier (divingsuit2)".
[04/01/2023 12:29:51] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Jeremy O'Neal/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2728238685/Weapons/AR-15/AR15.png, size: 179x56)
[04/01/2023 12:29:46] WARNING: Character "Moloch_m" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -Infinity to Infinity.
[04/01/2023 12:29:45] WARNING: Character "Crawlerhusk" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -Infinity to Infinity.
[04/01/2023 12:29:45] WARNING: Character "Crawlerhusk" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -Infinity to Infinity.
[04/01/2023 12:28:28] Overriding an affliction or a buff with the identifier 'huskinfection' using the file 'C:/Users/Jeremy O'Neal/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2085783214/Afflictions.xml'
[04/01/2023 12:27:29] Attempting to open ALC device "OpenAL Soft on Speakers (3- HyperX Cloud Core Wireless)"
[04/01/2023 12:27:26] Logged in as loco (SteamID STEAM_1:0:54773175)
```

**Comment by Regalis11** [comment] 2023-04-02 15:42
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11225

**Closed by Regalis11** 2023-04-02 15:42 UTC
