### ISSUE TITLE
Crashing with a DXGI_ERROR_DEVICE_REMOVED error

### ISSUE THREAD

**Issue by Karafox09** [Regalis11/Barotrauma#1833] opened 2019-10-17 02:18 UTC
- [1 ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The bug crashes my all running programs, and disconnects my second non primary monitor. Fixing it requires a hard reset, and most programs run like garbage after. 

**Steps To Reproduce**
Launch game, after about 3-5 minutes it just kinda happens, in the menu, in-game doesn't seem to matter.

Every once in a blue moon I can get it to work, and then it runs great, and I have a lot of fun. But to be quite frank, I am not going to play it until this is resolved, as I am worried about what data corruption this could have on my PC.

OS: Windows 10 Pro v1903
Barotrauma V0.9.3.3

Crash 1)
Barotrauma Client crash report (generated on 10/15/2019 10:15:21 PM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

6DDA41BE119266555DD541279528B0D1

Game version 0.9.3.3
Graphics mode: 1920x1080 (BorderlessWindowed)
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.NetLobbyScreen
SteamManager initialized
Client (Round hadn't been started)

System info:
    Operating system: Microsoft Windows NT 6.2.9200.0 64 bit
    GPU name: Radeon RX Vega
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.777778}
    GPU status: Normal

Exception: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.

Target site: Void CheckError()
Stack trace: 
   at SharpDX.Result.CheckError()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent()
   at Microsoft.Xna.Framework.SdlGamePlatform.Present()
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Barotrauma.Program.Main(String[] args)

Last debug messages:
[10/15/2019 10:15:21 PM] Unknown SharpDX exception code (887A0005)
[10/15/2019 10:15:21 PM] SharpDX exception caught. (HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.
, 887A0005). Attempting to fix...
[10/15/2019 10:13:37 PM] OpenAL Soft on Microphone (Rocketfish HD Webcam Lite) 53
[10/15/2019 10:13:37 PM] OpenAL Soft on Headset Microphone (Razer Nari Ultimate - Chat) 62
[10/15/2019 10:12:23 PM] Logged in as Karafox (SteamID STEAM_1:0:21299156)

Crash Report 2)

Barotrauma Client crash report (generated on 10/16/2019 8:24:47 PM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

6DDA41BE119266555DD541279528B0D1

Game version 0.9.3.3
Graphics mode: 1600x900 (Windowed)
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.MainMenuScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 6.2.9200.0 64 bit
    GPU name: Radeon RX Vega
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.777778}
    GPU status: Normal

Exception: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.

Target site: Void CheckError()
Stack trace: 
   at SharpDX.Result.CheckError()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent()
   at Microsoft.Xna.Framework.SdlGamePlatform.Present()
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Barotrauma.Program.Main(String[] args)

Last debug messages:
[10/16/2019 8:24:47 PM] Unknown SharpDX exception code (887A0005)
[10/16/2019 8:24:47 PM] SharpDX exception caught. (HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.
, 887A0005). Attempting to fix...
[10/16/2019 8:21:42 PM] Logged in as Karafox (SteamID STEAM_1:0:21299156)

Crash Report 3

Barotrauma Client crash report (generated on 10/16/2019 8:37:34 PM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

6DDA41BE119266555DD541279528B0D1

Game version 0.9.3.3
Graphics mode: 1600x900 (Windowed)
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.NetLobbyScreen
SteamManager initialized
Client (Round hadn't been started)

System info:
    Operating system: Microsoft Windows NT 6.2.9200.0 64 bit
    GPU name: Radeon RX Vega
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.777778}
    GPU status: Normal

Exception: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.

Target site: Void CheckError()
Stack trace: 
   at SharpDX.Result.CheckError()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent()
   at Microsoft.Xna.Framework.SdlGamePlatform.Present()
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Barotrauma.Program.Main(String[] args)

Last debug messages:
[10/16/2019 8:37:34 PM] Unknown SharpDX exception code (887A0005)
[10/16/2019 8:37:34 PM] SharpDX exception caught. (HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.
, 887A0005). Attempting to fix...
[10/16/2019 8:35:12 PM] OpenAL Soft on Microphone (Rocketfish HD Webcam Lite) 53
[10/16/2019 8:35:12 PM] OpenAL Soft on Headset Microphone (Razer Nari Ultimate - Chat) 62
[10/16/2019 8:34:56 PM] Logged in as Karafox (SteamID STEAM_1:0:21299156)

Crash Report 4)

Barotrauma Client crash report (generated on 10/16/2019 8:43:31 PM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

6DDA41BE119266555DD541279528B0D1

Game version 0.9.3.3
Graphics mode: 1600x900 (Windowed)
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: Nemo's Nautilus (0D4FBE61DE35E37CD87DBE739F6E8A28)
Selected screen: Barotrauma.NetLobbyScreen
SteamManager initialized
Client (Round hadn't been started)

System info:
    Operating system: Microsoft Windows NT 6.2.9200.0 64 bit
    GPU name: Radeon RX Vega
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.777778}
    GPU status: Normal

Exception: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.

Target site: Void CheckError()
Stack trace: 
   at SharpDX.Result.CheckError()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent()
   at Microsoft.Xna.Framework.SdlGamePlatform.Present()
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Barotrauma.Program.Main(String[] args)

Last debug messages:
[10/16/2019 8:43:31 PM] Unknown SharpDX exception code (887A0005)
[10/16/2019 8:43:31 PM] SharpDX exception caught. (HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.
, 887A0005). Attempting to fix...
[10/16/2019 8:43:21 PM] Coroutine Barotrauma.Networking.GameClient+<StartGame>d__68 threw an exception: Object reference not set to an instance of an object.
   at Barotrauma.Networking.GameClient.<StartGame>d__68.MoveNext()
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle)
[10/16/2019 8:43:18 PM] Coroutine Barotrauma.Networking.GameClient+<StartGame>d__68 threw an exception: Object reference not set to an instance of an object.
   at Barotrauma.Networking.GameClient.<StartGame>d__68.MoveNext()
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle)
[10/16/2019 8:43:18 PM] Coroutine Barotrauma.Networking.GameClient+<StartGame>d__68 threw an exception: Object reference not set to an instance of an object.
   at Barotrauma.Networking.GameClient.<StartGame>d__68.MoveNext()
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle)
[10/16/2019 8:43:18 PM] Coroutine Barotrauma.Networking.GameClient+<StartGame>d__68 threw an exception: Object reference not set to an instance of an object.
   at Barotrauma.Networking.GameClient.<StartGame>d__68.MoveNext()
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle)
[10/16/2019 8:43:17 PM] Coroutine Barotrauma.Networking.GameClient+<StartGame>d__68 threw an exception: Object reference not set to an instance of an object.
   at Barotrauma.Networking.GameClient.<StartGame>d__68.MoveNext()
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle)
[10/16/2019 8:42:25 PM] Coroutine Barotrauma.Networking.GameClient+<StartGame>d__68 threw an exception: Exception of type 'System.OutOfMemoryException' was thrown.
   at Barotrauma.CrewManager.InitProjectSpecific()
   at Barotrauma.GameSession..ctor(Submarine submarine, String savePath, GameModePreset gameModePreset, MissionPrefab missionPrefab)
   at Barotrauma.Networking.GameClient.<StartGame>d__68.MoveNext()
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle)
[10/16/2019 8:40:06 PM] A bucket of cats, 76561198015320747
[10/16/2019 8:39:53 PM] Loading submarine "Submarines\Downloaded\Nemo's Nautilus.sub" failed! (There is an unclosed literal string. Line 1, position 453565.)
[10/16/2019 8:39:36 PM] Logged in as Karafox (SteamID STEAM_1:0:21299156)

**Comment by databasetd** [comment] 2019-10-17 21:12
This sounds like a hardware issue since your GPU is disconnecting. Generally this happens when you don't have the latest drivers, your GPU is overclocked, or it's overheating.

**Comment by Karafox09** [comment] 2019-10-18 20:10
Monitoring my GPU, it's running around ~50C tops (43C on no load).  I don't OC my GPU at all(doublechecked to confirm). And my drivers are up to date. AMD 19.10.1 at the time of posting. Could it be some kind of crosstalk or coding breaking GPU drivers? Maybe an instantaneous memory leak?

**Comment by Karafox09** [comment] 2019-10-18 22:54
"A quick google about your error message:DXGI_ERROR_DEVICE_REMOVED / 0x887A0005

https://msdn.microsoft.com/en-us/library/Bb173571(v=VS.85 :
The video card has been physically removed from the system, or a driver upgrade for the video card has occurred. The application should destroy and recreate the device. For help debugging the problem, call ID3D10Device::GetDeviceRemovedReason.aspx).

Seems very much like it has something to do with the game not liking your GPU drivers or being unable to deal with your GPU.I haven't been thoroughly reading other people's complaints but maybe it's possible that the general GPU support for Radeon is poor. That has unfortunately been the case for a lot of frameworks and games always. Can't really say for sure whether it's the DirectX, SharpDX or something they do with the game engine.

Edit: And the reason why other programs start crashing and the screen blinking is likely because Barotrauma tries to re-init your graphics card"

This is a response I got on other forums

**Comment by Jazzdogg** [comment] 2020-03-21 11:49
So I’m getting this error, running via an eGPU with a 5700XT. If I run in windowed mode it seems to run

**Comment by juanjp600** [comment] 2020-03-21 15:04
Copying exception info from #2478, since it includes the device removed reason (in this case, DXGI_ERROR_DEVICE_RESET)

```Exception: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.
 (SharpDX.SharpDXException)
Device removed reason: HRESULT = 0x887A0007
Target site: Void CheckError()
Stack trace: 
   at SharpDX.Result.CheckError()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 1017
   at Microsoft.Xna.Framework.Game.Tick() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 511
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 42```

**Comment by JJGYET** [comment] 2020-05-18 21:06
[crashreport (5).log](https://github.com/Regalis11/Barotrauma/files/4646702/crashreport.5.log)
[crashreport (4).log](https://github.com/Regalis11/Barotrauma/files/4646703/crashreport.4.log)
[crashreport (3).log](https://github.com/Regalis11/Barotrauma/files/4646704/crashreport.3.log)
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/4646705/crashreport.2.log)
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/4646706/crashreport.log)
[crashreport (8).log](https://github.com/Regalis11/Barotrauma/files/4646707/crashreport.8.log)
[crashreport (7).log](https://github.com/Regalis11/Barotrauma/files/4646708/crashreport.7.log)
[crashreport (6).log](https://github.com/Regalis11/Barotrauma/files/4646709/crashreport.6.log)

Having the same issues. 

Playing the first tutorial, going as fast as I can I only make it to the Transition between the Shuttle and the Sub before crashing with this error. Attaching all Crash reports. 

Tried with and without V-Sync. Tried lower settings. Still crashes. All Drivers and OS are up to date. 

I tried playing a solo campaign and also received the same crash, normally within 4 or 5 minutes of play.

**Comment by Regalis11** [comment] 2021-11-29 11:43
Copying a comment from another ticket, w/ some potential fixes for this:

This is unfortunately [a long-standing bug](https://github.com/Regalis11/Barotrauma/issues/1833) that we unfortunately haven't been able to fully fix. It's also a GPU-related problem that can be caused by a variety of reasons, which makes it even more difficult to diagnose. However, based on a google search with the error code (0x887a0020), there are a couple of things you should try:
- [Make sure your graphics drivers are up-to-date.](https://answers.ea.com/t5/Technical-Issues/ERROR-DXGI-DRIVER-INTERNAL-ERROR-NOT-FIXED/td-p/9745945)
- [Disable Image Sharpening in the Nvidia Control panel](https://answers.ea.com/t5/Technical-Issues/UNABLE-TO-LOAD-MENU/td-p/7449903)
- [Ensure your DirectX installation is up-to-date.](https://websetnet.net/how-to-fix-dxgi_error_device-hung-or-reset-messages-in-windows-11-10/)
- There's also some more things you could try here: https://websetnet.net/how-to-fix-dxgi_error_device-hung-or-reset-messages-in-windows-11-10/

**Comment by Jade-Harleyy** [comment] 2022-04-05 17:17
[crashreport (7).log](https://github.com/Regalis11/Barotrauma/files/8420462/crashreport.7.log)

Happened to me aswell, it also temporarily disabled the output to my headphones for some reason.
Windows Unstable v0.17.6.0 too btw.

**Comment by Noxurius** [comment] 2022-06-15 12:23
Hello I recently opened a topic with that kind of problem and since I have the lastest drivers and that I'm still having those crash I assume It's not "a duplicate of that topic" can someone help me please, I beg y'all 
Here's the lastest crash report I had
Barotrauma Client crash report (generated on 15/06/2022 14:18:39)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


1FC87F527F5494A2CD53453BD2215F18


Game version 0.17.16.0 (ReleaseWindows, branch release, revision 05309f303f)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla, Onyx Spear
Level seed: ErlangshenThe Bucket
Loaded submarine: Onyx Spear (06157A708918BFBBFC2A609B6EF49F82)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)


System info:
    Operating system: Microsoft Windows NT 10.0.19043.0 64 bit
    GPU name: NVIDIA GeForce GTX 1050
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,7777778}
    GPU status: Normal


Exception: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: L’instance de périphérique GPU a été suspendue. Utilisez GetDeviceRemovedReason pour déterminer l’action appropriée.
 (SharpDX.SharpDXException)
Device removed reason: HRESULT = 0x887A0006
Target site: Void CheckError()
Stack trace: 
   at SharpDX.Result.CheckError()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 1017
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 511
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59


Last debug messages:
[15/06/2022 14:18:00] Server running slowly (55 updates/s)!
[15/06/2022 14:17:50] Server running slowly (37 updates/s)!
[15/06/2022 14:16:58] Server running slowly (34 updates/s)!
[15/06/2022 14:16:46] Server running slowly (58 updates/s)!
[15/06/2022 14:15:56] Server running slowly (45 updates/s)!
[15/06/2022 14:15:45] Server running slowly (45 updates/s)!
[15/06/2022 14:14:53] Server running slowly (46 updates/s)!
[15/06/2022 14:14:43] Server running slowly (49 updates/s)!
[15/06/2022 14:13:22] Server running slowly (57 updates/s)!
[15/06/2022 14:13:12] Server running slowly (41 updates/s)!
[15/06/2022 14:12:00] Server running slowly (47 updates/s)!
[15/06/2022 14:11:50] Server running slowly (53 updates/s)!
[15/06/2022 14:10:07] WARNING: Received a potentially invalid ENTITY_POSITION message.Entity identifier does not match (server entity is coilgunbolt, client entity is railgunshell). Ignoring the message...
[15/06/2022 14:09:39] Server running slowly (56 updates/s)!
[15/06/2022 14:07:58] Server running slowly (58 updates/s)!
[15/06/2022 14:07:02] Noxurius
[15/06/2022 14:06:59] Received STARTGAMEFINALIZE packet. Round init status: Started
[15/06/2022 14:06:53] Task count: 0
[15/06/2022 14:06:53] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[15/06/2022 14:06:40] Generating an outpost for the end of the level... (Location: The Bucket Outpost, level type: LocationConnection)
[15/06/2022 14:06:38] Generating an outpost for the start of the level... (Location: Erlangshen Habitation Outpost, level type: LocationConnection)
[15/06/2022 14:06:23] Server running slowly (56 updates/s)!
[15/06/2022 14:06:14] Noxurius
[15/06/2022 14:06:13] WARNING: Could not determine reputation change for faction "Children of the Honkmother" (faction was not present at the start of the round).
[15/06/2022 14:06:13] WARNING: Could not determine reputation change for faction "The Church of Husk" (faction was not present at the start of the round).
[15/06/2022 14:06:13] WARNING: Could not determine reputation change for faction "Jovian Separatists" (faction was not present at the start of the round).
[15/06/2022 14:06:13] WARNING: Could not determine reputation change for faction "Europa Coalition" (faction was not present at the start of the round).
[15/06/2022 14:05:20] Server running slowly (56 updates/s)!
[15/06/2022 14:04:57] Noxurius
[15/06/2022 14:04:55] Server running slowly (55 updates/s)!
[15/06/2022 14:04:48] Received STARTGAMEFINALIZE packet. Round init status: Started
[15/06/2022 14:04:48]  -7: WaitForPingDataAsync (owner), RanToCompletion
[15/06/2022 14:04:48]  -6: WaitForPingDataAsync (owner), RanToCompletion
[15/06/2022 14:04:48]  -5: WaitForPingDataAsync (owner), RanToCompletion
[15/06/2022 14:04:48]  -4: WaitForPingDataAsync (owner), RanToCompletion
[15/06/2022 14:04:48]  -3: WaitForPingDataAsync (owner), RanToCompletion
[15/06/2022 14:04:48]  -2: WaitForPingDataAsync (owner), RanToCompletion
[15/06/2022 14:04:48]  -1: WaitForPingDataAsync (owner), RanToCompletion
[15/06/2022 14:04:48]  -0: WaitForPingDataAsync (owner), RanToCompletion
[15/06/2022 14:04:48] Task count: 8
[15/06/2022 14:04:48] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[15/06/2022 14:04:33] Generating an outpost for the start of the level... (Location: Erlangshen Habitation Outpost, level type: Outpost)
[15/06/2022 14:03:26] Lobby created!
[15/06/2022 14:01:47] Attempting to open ALC device "OpenAL Soft on Haut-parleur/Ecouteurs (Realtek High Definition Audio)"
[15/06/2022 14:01:38] Logged in as Noxurius (SteamID STEAM_1:0:67774949)

**Comment by Regalis11** [comment] 2022-11-08 14:41
[I added some more info](https://github.com/Regalis11/Barotrauma-development/commit/bac391b060630559170549a8e0bf734d06b5ca62) to the "barotrauma just crashed" message box and the crash reports when this error occurs. . The messages now include the human-readable error code (e.g. DXGI_ERROR_DEVICE_HUNG) and lists some potential causes for the error and ways to potentially fix it (outdated drivers or DirectX installation, overclocked GPU).

The issue is not fixed however - as mentioned this is an error that can happen due to tons of different reasons, some of which are outside our control (problems with the GPU or drivers). But hopefully the extra info in the error message will help at least some players get around the problem.

**Comment by Regalis11** [comment] 2022-11-25 10:16
I created a new ticket about this with some more information and potential ways to fix the issue: https://github.com/Regalis11/Barotrauma/issues/10540

**Closed by Regalis11** 2022-11-25 10:16 UTC
Labels: Bug, Code, Crash, Severe

**Comment by Noxurius** [comment] 2022-11-25 17:08
Thanks a lot I really appreciate the time you're spending on this 🙏

**Comment by alex17pat** [comment] 2023-12-12 11:14
I searched on every forum on internet and eventually end up fixing this by modifying the registry. 

https://thegeekpage.com/dxgi-error-device-removed/
