### ISSUE TITLE
Bots drop medicine while wearing PUCS

### ISSUE THREAD

**Issue by JaydenCallan** [Regalis11/Barotrauma#10039] opened 2022-10-09 23:39 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Whenever a bot reaches 0% oxygen wearing a PUCS suit, they swap oxygen tanks, dropping whatever item is in the medicine slot in the process.
It only works if they take an old tank out first, if their suit is empty the medicine does not drop.

### Reproduction steps

1. Start a singleplayer game (or multiplayer and hire a bot)
2. Put a PUCS suit on the bot with an oxygen tank and something in the medicine slot of the suit
3. Let the oxygen tank run out
4. Make sure the bot has another oxygen tank in their inventory
5. Medicine drops on the ground when they swap tanks

### Bug prevalence

Happens every now and then

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by ekqvist** [comment] 2022-12-02 11:27
Fixed in Regalis11/Barotrauma-development@b7684ad

**Comment by NilanthAnimosus** [comment] 2022-12-07 14:23
Tested against bugfixes commit https://github.com/Regalis11/Barotrauma-development/commit/14457d7dc22a5b12de8d84d2e57268378e1454d8, no issues found, closing.

**Closed by NilanthAnimosus** 2022-12-07 14:23 UTC
Labels: Bug, Code

**Comment by itchyOwl** [comment] 2023-01-12 14:47
The fix caused bots to try to contain multiple items where one should suffice. Created a ticket [here](#10916). The fix for it could affect this ticket, but based on testing and checking it with a breakpoint, this seems to be unaffected.

**Comment by ekqvist** [comment] 2023-01-13 09:41
I also tested this with the steps provided after the fix for #10916 and couldn't reproduce this. So, the new fix shouldn't have affected this.
