### ISSUE TITLE
Pets not eating

### ISSUE THREAD

**Issue by zelda0079** [Regalis11/Barotrauma#12020] opened 2023-05-17 03:31 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Pets don't eating

### Reproduction steps

1. Put saline to 2 egg to spawn 2 pet. ( I didn't test for 1 pet)
2. Put some saline to ground, the 2 pets are Peanut and Psilotoad.
3. Go to other room 1 minute.
4. They don't eat.

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by zelda0079** [comment] 2023-05-17 03:32
I also test pet food, they don't eat.

**Comment by Regalis11** [comment] 2023-05-17 06:57
Thank you for the report! Just to be sure, are the pets hungry (i.e. do you see the icon that looks like a hamburger next to them)? It's also worth nothing that Peanut doesn't move if it's being observed, so it won't eat if the Psilotoad is in the same room with it.

**Comment by Regalis11** [comment] 2023-05-17 08:26
Nvm, I was able to reproduce the issue myself too.

**Comment by Regalis11** [comment] 2023-05-17 08:27
Addressed in https://github.com/Regalis11/Barotrauma-development/pull/4239 (PR in our private repo)

**Comment by Rokvach** [comment] 2023-05-19 12:17
Tested, working correctly. Can be merged and closed.

**Closed** 2023-05-19 12:53 UTC
Labels: Bug, Code
