### ISSUE TITLE
ballist flora infected my save game

### ISSUE THREAD

**Issue by m0nk1111** [Regalis11/Barotrauma#9004] opened 2022-04-27 19:34 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Steps To Reproduce**
so i got this ballist flora infection, i didnt fix it when the infection started, but just went to the station, game got saved, and now this error shows up 
i restart client, load save game, error shows up at every station i dock
i tried killing the flora, remove water, plasma torch flora , but the cursor doenst see the ballast flora any more, like b4 when infection just started.
i tried flaming the whole area.. 

**Version**
Windows, latest steam

**Additional information**
Error while loading entity of the type Barotrauma.Hull. {Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')}
   at Barotrauma.MapCreatures.Behavior.BallastFloraBehavior.<LoadSave>g__LoadBranch|187_0(XElement branchElement, IdRemap idRemap) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Creatures\BallastFloraBehavior.cs:line 0
   at Barotrauma.MapCreatures.Behavior.BallastFloraBehavior.LoadSave(XElement element, IdRemap idRemap) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Creatures\BallastFloraBehavior.cs:line 432
   at Barotrauma.Hull.Load(ContentXElement element, Submarine submarine, IdRemap idRemap) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Hull.cs:line 1560

**Comment by cshingle** [comment] 2022-04-27 21:34
@m0nk1111 This issue is known and fixed in the unstable. You can switch to the unstable branch, wait for it to go to full release, or follow the workaround in this issue.
#8947

**Comment by Regalis11** [comment] 2022-04-28 07:23
Duplicate of https://github.com/Regalis11/Barotrauma/issues/8947

As @cshingle mentioned, this has been fixed in the unstable branch. The fix is also coming to the public version very soon, hopefully even later today. Sorry for the trouble!

**Closed by Regalis11** 2022-04-28 07:23 UTC
