### ISSUE TITLE
General issues with bots opening doors.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#7413] opened 2021-11-20 03:02 UTC
- Somehow I honestly couldn't find an exact ticket for this currently open, I guess its more of a general issue people talk about alot.

**Description of the Issue:**
Bots fail to open doors correctly for various reasons, instead getting stuck walking into them eternally.
This can happen for different reasons such as issues in hull alignment or node alignment, another bot slamming the door on them, bots trying to target items 'through' the other side of a door, or other unknown reasons.

Here a bot appears to be trying to 'skip' the door's node instead thinking that they are able to reach the node past it.
![image](https://user-images.githubusercontent.com/55356135/142711978-abbc2bd9-dfc4-4e87-b4b5-682a4eeaabba.png)

Alot of the time issues seem to happen even on vanilla submarines and on stations, but can be more common on custom submarines especially with complex shapes of hull-volumes I noticed. Obviously its up to each submaker their own to take some responsibility into optimization. However I think that with how often issues happen on official submarines or relatively-simple custom subs with autogenerated nodes it shows that there is still improvements needed to the robustness of the AI logic - particularly in these cases where they seem to be acting in a way that disregards the node-structure entirely.

**Also here's something else odd if anyone has any idea why this decided to happen.**
![image](https://user-images.githubusercontent.com/55356135/142712310-250e4562-5e46-4c35-878a-99badb454376.png)

**Comment by MaaiG** [comment] 2021-11-20 13:40
I found a similar problem!
A bot led outside the boat cannot return to it. The bot chooses not the outer point of the path.
- If we have one outer way point -  the bot chooses the fourth point.
- I f we have two - are the fourth way point.
- If we have five - are the first way point.
![Image 008](https://user-images.githubusercontent.com/93348499/142728463-ad51cac7-a397-4505-9db1-a72a49c0e6fe.png)

**Comment by Ek-Videogames** [comment] 2021-11-20 16:33
> The automated way points is a terrible evil )). Sometimes the paths are laid in such a way that it is difficult to immediately know what the problem is. Way point can overlap and be unrelated, etc. but this is not visible at first sight.

Yea, and even with basic hull shapes the autogeneration can still sometimes make strange errors like:
- Forgetting to link overlapping ladder nodes together, or
- Failing to put nodes on the center of doors & hatches, causing them to at as normal nodes instead.

Thought I think sub-editor issues would deserve a separate ticket their own.

**Comment by itchyOwl** [comment] 2021-11-29 15:46
I haven't been able to repro bots skipping nodes through doors, but it might be possible that the door was closed before the bot either automatically, by another player, or a bot. Automated systems should use a motion sensor to prevent this from happening, bots shouldn't do this since Regalis11/Barotrauma-developmetn@e8a33a1, but I'll try to repro it manually and think a way for them to get around it.

**Comment by itchyOwl** [comment] 2021-11-30 08:05
I tested closing a door before the bot when it was following me, but I couldn't get it stuck. It does keep walking towards the door for a few seconds, but manages to open the door eventually.

I'll move the ticket to QA for overall testing. If nothing is broken, let's close it, unless we get more information/steps about the issues.

**Comment by Rokvach** [comment] 2021-12-01 09:38
I've been able to quite reliably reproduce something similar to this

1. Start a new campaign with Kastrull
2. Make sure a bot is near the bottom diving suits but not inside the room
3. Order them to Prepare For Expedition
4. Notice that they can't open the door for some reason but instead just runs against the door

Tested in dev branch using a Release build and in this commit https://github.com/Regalis11/Barotrauma-development/commit/320522c88d8319529bd4da403aa5e6049fa8ba8b

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/6c30faf0-8e8c-4f67-b574-0ffe8716dc2d)

Another place you can see bots getting sometimes stuck on doors is within outposts, but in there it's momentary as there is so many bots on the outpost that someone will eventually come and open it if one of them fails to open, so a bit harder to record. But easy to try and repro is to start new campaigns until it happens on one of the outpost configurations and then just hitting retry.

**Comment by itchyOwl** [comment] 2021-12-01 10:23
Thanks, I'll try to repro that. However, the picture tells us that it's not an issue with doors or pathing: the bot is stuck at the goto objective, but does not have a proper path. That blue vector is a steering vector, meaning the steering is not properly resetted or the bot has fallen to the simpler steering method. There's a path of some other bot shown in the upper floor. I'll look into it nevertheless!

**Comment by itchyOwl** [comment] 2021-12-01 11:23
Can't repro.

**Comment by itchyOwl** [comment] 2021-12-01 12:39
Found some issues near the airlocks and with automated systems but I don't think they are causing the issue @Rokvach mentioned.

**Comment by itchyOwl** [comment] 2021-12-01 13:39
They also had some issues with doors with buttons.

Fixed the issue I could find in Regalis11/Barotrauma-development@02ee5e6.

**Comment by Rokvach** [comment] 2021-12-01 13:40
Seems to be less reliable than I thought, I am only able to get it to happen if the Mechanic spawns in the crafting room (Below ballasts) on Kastrull and before they venture away from that room. So retry until they spawn in that room or remove the engine room spawn entirely and order them then before they get to open any doors.

**Comment by itchyOwl** [comment] 2021-12-01 15:29
Managed to reproduce that and fixed in Regalis11/Barotrauma-development@ff9c66a. The issue was due to the latest optimizations in Regalis11/Barotrauma-development@320522c, so it's not found in the unstable. Good finding! Would have been shitty to ship a build with that nasty bug.

**Comment by Rokvach** [comment] 2021-12-02 10:06
The issues I've pointed out has at least been fixed, haven't yet run into any of the other door related issues so can't say for sure what their status is

**Comment by itchyOwl** [comment] 2021-12-03 16:18
There seems to be some issue still with the airlock doors.

**Comment by itchyOwl** [comment] 2021-12-03 16:42
Found out that the bots didn't operate Humpback's airlock doors properly. Fixed in Regalis11/Barotrauma-development@59ae7fd (bugfixes).

**Comment by Rokvach** [comment] 2022-01-20 10:18
I haven't spotted any further issues relating to this, seems to be working correctly now. Closing.

**Closed by Rokvach** 2022-01-20 10:18 UTC
Labels: Bug, Needs testing, Code
