### ISSUE TITLE
Crash at startup (DOTNET_SYSTEM_GLOBALIZATION_INVARIANT)

### ISSUE THREAD

**Issue by todorbg** [Regalis11/Barotrauma#9466] opened 2022-06-26 19:09 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Hello! I'm using Manjaro Linux, with the 5.15.41-1-MANJARO kernel. I downloaded and installed Barotrauma (completely fresh install, no mods), but at startup - it spewed out this error (shortened for readability).

```
[S_API] SteamAPI_Init(): Loaded '/home/todor/.local/share/Steam/linux64/steamclient.so' OK.
Setting breakpad minidump AppID = 602960
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198368160694 [API loaded no]
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   ... 
   (list of functions)
   ...
   at Barotrauma.Program.Main(System.String[])
zsh: IOT instruction (core dumped)  ./Barotrauma
```
Setting the DOTNET_SYSTEM_GLOBALIZATION_INVARIANT enviroment variable to 1 manually, fixed the issue for me, and I can play the game without issues now.
- **export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1**

Is this an issue with the code, or an issue with my setup? This does not happen with any other tools or games.

Pastebin of the full error: https://pastebin.com/K7stz8zM

Here are my default enviroment variables when running the game (the ones pertaining to "language" or "region")
```
LANG=en_US.UTF-8
LANGUAGE=
LC_ADDRESS=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_MONETARY=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_NUMERIC=en_US.UTF-8
LC_PAPER=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_TIME=en_US.UTF-8
```
### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?
Linux

**Comment by Regalis11** [comment] 2022-06-27 07:31
Duplicate of https://github.com/Regalis11/Barotrauma/issues/8858

**Closed by Regalis11** 2022-06-27 07:31 UTC
