### ISSUE TITLE
barotrauma glitch (April 20221)

### ISSUE THREAD

**Issue by mlgamez** [Regalis11/Barotrauma#5436] opened 2021-04-04 19:55 UTC
game crashes the moment i start
macbook air (m1, 2020)
chip = Apple M1
8 GB mem

macintosh hd mem left = 61.77 GB
[Archive.zip](https://github.com/Regalis11/Barotrauma/files/6255251/Archive.zip)

**Comment by Regalis11** [comment] 2021-04-06 07:18
Duplicate of https://github.com/Regalis11/Barotrauma/issues/4504

**Closed by Regalis11** 2021-04-06 07:18 UTC
