### ISSUE TITLE
Game crashes when I start a new game, crashreport is the same every time.

### ISSUE THREAD

**Issue by ProneStream8587** [Regalis11/Barotrauma#2750] opened 2020-05-01 17:10 UTC
Barotrauma Client crash report (generated on 5/1/2020 1:03:55 PM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

023CCD07C102F6331CAD29D2EADB01E0

Game version 0.9.9.1 (ReleaseWindows, branch release, revision 1968ab79f)
Graphics mode: 1680x1050 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: PastoniaSt. Musk
Loaded submarine: Dugong (B61EC80FF969CC05BEDC2C82D5BAED27)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.18362.0 64 bit
    GPU name: NVIDIA GeForce GTX 1080
    Display mode: {Width:1680 Height:1050 Format:Color AspectRatio:1.6}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void UpdateWaterAmbience(Single, Single)
Stack trace: 
   at Barotrauma.SoundPlayer.UpdateWaterAmbience(Single ambienceVolume, Single deltaTime)
   at Barotrauma.SoundPlayer.Update(Single deltaTime)
   at Barotrauma.GameMain.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Barotrauma.Program.Main(String[] args)

Last debug messages:
[5/1/2020 1:03:34 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[5/1/2020 1:03:34 PM] Content package load order: Vanilla 0.9
[5/1/2020 1:03:33 PM] Content package load order: Vanilla 0.9
[5/1/2020 1:03:32 PM] ALC device creation failed too many times!
[5/1/2020 1:03:32 PM] ALC device initialization attempt #3 failed: device is null
[5/1/2020 1:03:32 PM] ALC device initialization attempt #2 failed: device is null
[5/1/2020 1:03:32 PM] ALC device initialization attempt #1 failed: device is null
[5/1/2020 1:03:32 PM] Attempting to open ALC device "OpenAL Soft"
[5/1/2020 1:03:31 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[5/1/2020 1:03:31 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[5/1/2020 1:03:30 PM] Logged in as [REDACTED]

When it crashes it says something about the UpdateWaterAmbience, but it looks like there's a problem with the ALC device initialization. **How can I fix this?**

**Comment by Regalis11** [comment] 2020-05-03 11:30
Duplicate of #2747

It seems the game fails to open an audio device for some reason, and crashes when it tries to play the water ambience sounds. Do you have some kind of audio device (headset, speakers) connected? If not, connecting one should get rid of this error. But in any case, we need to also make sure the game doesn't crash even if there is no audio device present.

**Closed by Regalis11** 2020-05-03 11:30 UTC

**Comment by ProneStream8587** [comment] 2020-05-04 03:36
Thank you, the PC I was using lacks audio and that was the problem, connecting any of my available audio devices (headsets / bluetooth earbuds) fixed the problem.
