### ISSUE TITLE
Crash at startup (Access to the path is denied)

### ISSUE THREAD

**Issue by Spacenobody** [Regalis11/Barotrauma#7721] opened 2021-12-11 14:36 UTC
Barotrauma Client crash report (generated on 2021/12/11 下午 10:24:28)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

53369B525C73F08AF404DBAF116B0ADA

Game version 0.15.13.0 (ReleaseWindows, branch release, revision 4e66dd7b5d)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: Traditional Chinese
Selected content packages: Vanilla 0.9, Armageddon's Redemption, Nebulon-B Frigate, BTL Y-Wing, RZ-1 A-Wing, EDS-40KRetribution Class Mk4-2, Aegis, Cyclops Mk-II, Ulysses, Indra, Sweet Pea, Yangtze-31 1.0.0, CR90 Corellian Corvette, Star Destroyer
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.18363.0 64 bit
    GPU name: NVIDIA GeForce GTX 960M
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: One or more errors occurred. (Access to the path 'D:\Program Files (x86)\Steam\steamapps\common\Barotrauma\Mods\WarShell\.copying' is denied.) (System.AggregateException)
Target site: Void ThrowIfExceptional(Boolean)
Stack trace: 
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Barotrauma.GameMain.<>c.<Load>b__102_0(Task task) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 486
   at Barotrauma.TaskPool.<>c__DisplayClass6_0.<Add>b__0(Task t, Object obj) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\TaskPool.cs:line 60
   at Barotrauma.TaskPool.Update() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\TaskPool.cs:line 77
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 1014
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 61

InnerException: Access to the path 'D:\Program Files (x86)\Steam\steamapps\common\Barotrauma\Mods\WarShell\.copying' is denied.
Target site: Microsoft.Win32.SafeHandles.SafeFileHandle ValidateFileHandle(Microsoft.Win32.SafeHandles.SafeFileHandle)
Stack trace: 
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Barotrauma.Steam.SteamManager.CopyWorkShopItemAsync(Nullable`1 itemOrNull, ContentPackage contentPackage, String newContentPackagePath, String metaDataFilePath) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\SteamManager.cs:line 0
   at Barotrauma.Steam.SteamManager.AutoUpdateWorkshopItemsAsync() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\SteamManager.cs:line 1600
Last debug messages:
[2021/12/11 下午 10:24:21] Attempting to open ALC device "OpenAL Soft on 喇叭 (Conexant SmartAudio HD)"
[2021/12/11 下午 10:24:20] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[2021/12/11 下午 10:24:19] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[2021/12/11 下午 10:24:18] Logged in as Spacenobody (SteamID STEAM_1:1:22857179)

**Comment by Regalis11** [comment] 2022-04-20 17:55
Most likely a duplicate of https://github.com/Regalis11/Barotrauma/issues/3850

**Closed by Regalis11** 2022-04-20 17:55 UTC
Labels: Bug, Code, Crash
