### ISSUE TITLE
Here is 3 crash reports

### ISSUE THREAD

**Issue by pavel4win** [Regalis11/Barotrauma#11484] opened 2023-03-12 15:41 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

game crashes while starting

[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/10951313/crashreport.2.log)
[crashreport (3).log](https://github.com/Regalis11/Barotrauma/files/10951314/crashreport.3.log)
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/10951316/crashreport.log)

### Reproduction steps

Starts game

### Bug prevalence

Happens every now and then

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-03-12 15:55
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10540

**Closed by Regalis11** 2023-03-12 15:55 UTC
