### ISSUE TITLE
ı cant play >:(

### ISSUE THREAD

**Issue by IfromTurkey55** [Regalis11/Barotrauma#11558] opened 2023-03-16 11:49 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

ı open the map. and ı look on the station ıcon... and crashed

### Bug prevalence

Happens every time I play

### Version

v1.0.7.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 03/16/2023 14:39:21)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

71290F513E6B598EAA3CFF037A2EAB34

Game version 1.0.7.0 (ReleaseWindows, branch release/1.0, revision e1df60d5cc)
Graphics mode: 1680x1050 (Fullscreen)
VSync ON
Language: English
Selected content packages: Vanilla, More Better Pay (A Lot More Marks), EK | Armory, EK | Utility, Better Dive Suits, EK | Gunnery, [AA] Aquatic Arsenal - Lead Diver Job (WIP), XanMonsters Creature Pack, Improved Husks, Ultima Mortis (Warhammer 40k), Ultima Mortis Maximus (Warhammer 40k), PN-21 Colossus Mobile Station, [EMS] Prometheus Station, SCP Site 49 V 1.0 2023 RUS/ENG, [SuS] Traitor gamemode submarine pack!, Akstely, ADV Beacon Stations, Beacons Extended, [VH] The Iroh, Sweet Pea, Storage Icons, Ulysses 2.37, LONGBOW sub carrier, Harlech, Sort Container UI, Kasserine, More XP, Europa Express, Athena, Crab 1.2, CBS-74 Ptolemaios II, The Nibbler, Silver vulpes, S-191 Barracuda (Barsuk Refit), The Coffin, TR-44 "Blimp", IMC SLEDGE, JS Ragna MKIV, Trust full joe, Bob Semple Submersible Tank, 自用Dugong改, Tubarão, Pillbug, OX-17 v0.1, "Hopeye" Class Abyssal Biome Science Submarine, Physeter macrocephalus Black, OX-17 v0.2 EK, Rustbucket, The Donut, Cardeal, Mercury, Trieste, Ju87 G-1, VulpesZerda, 7th Fleet Felinis - Volitile, Icereaper- Mk1, LEGIONAR, USS William D. Porter, Norppa, Converted Armed Heavy Freighter “Casablanca”, [JP] PVP ships pack [PVP], IMC AEGIS, The Brizo, Barsupreme, Hurricane, patrolman, Herse AT-III, [RH] Tynler, Cyclopes-01, GAYGAY Submarine MK6, Narwhal, [Pulsar]U-017, dolphin, Smart Auto Door, Patcher-9000, Sunset SC-I, MUX9（暮春之雪）水下旅馆潜艇, [Pableqx] Dreadnought BR-3507 - EN/US & PT/BR, 天佑改 银河号  驱逐舰, 雾凇 重型科研船, 拓冰者级多用途潜艇 Glacier pathfinder class submarine, Kastrull 简单修改版, Beaumaris, 零镇静, 【TSM】Snoata '关外', 南十字座 CRUX 战列巡洋舰, 儒艮IV, 军团(Legion)  巨兽级战列舰, All The Talent Trees + Unlock Parallel Talents, Panzer-Ⅳ 四号坦克, 超时空要塞 VF25 弥赛亚, better Site 19 (SCP)., Site 19 (SCP), sokayım ışığına, T.I.T.A.N. Warsuit: AbyssWard, Weeb guitar, Combat Overhaul(TTK and weaponry rework), Submarine Weapon Sound Makeover, More Unique Weapons (v1.1) [EN/RU], NI | WEAPONARY 北方工业联合体*的武器拓展俱乐部, Armory Weapons (and some clown craftables), SCP Art, SCP Pelagic Anomalies -- R&D /Stage 1, [AGC] SCP, SCP Alarms, Unlock Parallel Talents (V.20), old talents+new talents merged talent trees (V1.0), Unlocked talent trees, Better XP Talents, All The Talent Trees, NT Surgery Plus, NT Surgery Plus CN Patch, Talent Point EXP, UwU — Restored Talent Items, Reworked Talent Trees, Unlimited EK Armory, Cheeki Breeki Accordion, ek utility+nt cybernetic bent metal patch, EK Mods Русский перевод, Unlimited EK Gunnery, Unlimited EK Utility, EK | Dockyard, EK Tazer Fix, Shreksophone, EuropaWaifu++ EK mods Patch, Unlimited Railgun EK Armory Pack, Unlimited Railgun EK Gunnery Pack, TaF - EK Pirates, MannaBuildables - EK | Gunnery - Loaders Patch, BaroCraftables, Heavy Crate From Backpacks, Craftable Ammunition Shelf, Duffle Bag 2.0, Backpack & WaistBelt, Backpack, [BOS]Backpack, ArtifactsBack, SOFA'S TOOLS, Unlimited Tool, More Level Content - 1.0 Update, AUG Tools revamp, Modding Toolkit, Unlimited Fuel Rod, EEBD Emergency Escape Breathing Device, Genes+ Revived and Expanded, ExtraStorage, MoreHeadgear, Better Human Damage, Larger Deconstructor, Stronger Bandits and Pirates NPC, Portable Storage, Explorer, Objectively the worst orca variant [T3], Shipwrecks Extended, [PESD] Timid Station, SOFA'S WRECKS, sokayım ışığına, “暮雨”(沉船）, Fallout Power Armor, Too Many Missions, Analyze Items, AUG Guns [Outdated], GunLights Remade, Minigun, APFSDS Railgun shells, Breaking Bad Guitar, Unlimited Railgun, Unlimited Gun Ammunition, Reworked Chaingun, 32x Stack, Stack Size 62x Lua, Balanced Stack 32x Lua, Lua Linker, Performance Fix, Codename HONK, Cs For Barotrauma, BetterFabricatorUI, Raptorial -X- 01 - Made for Mudraptors!, [ACE] The Old Clown, Lua For Barotrauma, Breakable Handcuffs, Toolbox Expanded, Improved XP Rates, Unlimited Ammunition Box, Unlimited Items, The Sculpture, RIBA Sticky Notes, Meaningful Upgrades [RUS add-on] - Urban Expanses, Meaningful Upgrades, Pockets For All, Ammo extended 2 (RUS/ENG/汉语), Highly Advanced Gene Splicer, Weapons+, Melee Weapons Pack, Let Me Choose !, useless 2.37, Super Hmg + Exosuit, Exosuit Upgrade, No Reaper's Tax, SaveMyStuff, Enhanced Armaments, Talent Enhancement[CN/EN/RU/FRN], BaroTraumatic Nightmare, Barotraumatic Monster Pack Test fixes, Barotraumatic Extended Monsters Fixes, Playable Mudraptor (Magenta Mix)
Level seed: Jokull
Loaded submarine: useless 2.37 (AC630A8EF5099E7809B5027E08BF5D29)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit
    GPU name: NVIDIA GeForce GT 635
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Boolean CanHaveCampaignInteraction(InteractionType)
Stack trace: 
   at Barotrauma.OutpostGenerationParams.CanHaveCampaignInteraction(InteractionType interactionType) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Outposts\OutpostGenerationParams.cs:line 331
   at Barotrauma.Location.<>c__DisplayClass164_0.<CanHaveCampaignInteraction>b__0(OutpostGenerationParams p) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Location.cs:line 1398
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Barotrauma.Location.CanHaveCampaignInteraction(InteractionType interactionType) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Location.cs:line 1396
   at Barotrauma.Location.CanHaveSubsForSale() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Location.cs:line 1377
   at Barotrauma.Map.CreateLocationInfoOverlay(Location location) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\Map\Map.cs:line 393
   at Barotrauma.Map.Update(CampaignMode campaign, Single deltaTime, GUICustomComponent mapContainer) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\Map\Map.cs:line 557
   at Barotrauma.CampaignUI.UpdateMap(Single deltaTime, GUICustomComponent mapContainer) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\CampaignUI.cs:line 179
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1247
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 906
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[03/16/2023 14:39:21] Could not find human prefab "outpostmanagercoalition" from "outpostnpcs1".
[03/16/2023 14:39:09] WARNING: Potentially invalid damage modifier in "Old Seadog Hat, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[03/16/2023 14:39:09] WARNING: Potentially invalid damage modifier in "Old Seadog Hat, Wearable". Could not find any afflictions of the type "lacerations". Did you mean to use an affliction identifier instead?
[03/16/2023 14:39:08] Failed to parse the string "15" to Vector2
[03/16/2023 14:39:08] Failed to parse the string "15" to Vector2
[03/16/2023 14:39:04] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/16/2023 14:39:04] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/16/2023 14:39:04] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/16/2023 14:39:04] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/16/2023 14:39:03] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/16/2023 14:39:03] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/16/2023 14:39:03] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/16/2023 14:39:03] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/16/2023 14:39:03] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/16/2023 14:39:03] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/16/2023 14:39:03] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/16/2023 14:39:03] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/16/2023 14:39:03] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/16/2023 14:39:03] Could not find human prefab "merchanthusk" from "outpostnpcs1".
[03/16/2023 14:39:03] Could not find human prefab "securitynpcseparatists" from "outpostnpcs1".
[03/16/2023 14:39:03] Could not find human prefab "securitynpcseparatists" from "outpostnpcs1".
[03/16/2023 14:39:03] Could not find human prefab "outpostmanagerseparatists" from "outpostnpcs1".
[03/16/2023 14:39:02] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/16/2023 14:38:59] Error in the fabrication recipe for "Mannitol plus". Could not find the ingredient "Barotrauma.FabricationRecipe+RequiredItemByIdentifier (mannitol)".
[03/16/2023 14:38:59] Error in the fabrication recipe for "Experimental treatment". Could not find the ingredient "Barotrauma.FabricationRecipe+RequiredItemByIdentifier (propofol)".
[03/16/2023 14:38:59] Error in the fabrication recipe for "Artificial brain". Could not find the ingredient "Barotrauma.FabricationRecipe+RequiredItemByIdentifier (mannitol)".
[03/16/2023 14:38:57] Error in item "Fabricator": There's not enough room in the input inventory for the ingredients of "Exploding Assault Rifle Magazine"!
[03/16/2023 14:38:57] Error in item "Fabricator": There's not enough room in the input inventory for the ingredients of "Unlimited Assault Rifle Magazine"!
[03/16/2023 14:38:57] Error in item "Fabricator": There's not enough room in the input inventory for the ingredients of "Unlimited Assault Rifle Magazine"!
[03/16/2023 14:38:56] Generating an outpost for the start of the level... (Location: Jokull Habitation Outpost, level type: Outpost)
[03/16/2023 14:38:56] Level identifier: outpostlevel
[03/16/2023 14:38:51] Error in item "Fabricator": There's not enough room in the input inventory for the ingredients of "Exploding Assault Rifle Magazine"!
[03/16/2023 14:38:51] Error in item "Fabricator": There's not enough room in the input inventory for the ingredients of "Unlimited Assault Rifle Magazine"!
[03/16/2023 14:38:51] Error in item "Fabricator": There's not enough room in the input inventory for the ingredients of "Unlimited Assault Rifle Magazine"!
[03/16/2023 14:38:48] Error in the fabrication recipe for "Mannitol plus". Could not find the ingredient "Barotrauma.FabricationRecipe+RequiredItemByIdentifier (mannitol)".
[03/16/2023 14:38:48] Error in the fabrication recipe for "Experimental treatment". Could not find the ingredient "Barotrauma.FabricationRecipe+RequiredItemByIdentifier (propofol)".
[03/16/2023 14:38:48] Error in the fabrication recipe for "Artificial brain". Could not find the ingredient "Barotrauma.FabricationRecipe+RequiredItemByIdentifier (mannitol)".
[03/16/2023 14:38:44] Error in StatusEffect config - item prefab with the identifier "smallcrawlereggfrendlytimmed" not found.
[03/16/2023 14:38:44] WARNING: Affliction "stima1" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[03/16/2023 14:38:44] WARNING: Affliction "stima1" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[03/16/2023 14:38:44] WARNING: Affliction "stima1" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[03/16/2023 14:38:44] WARNING: Affliction "stima1" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[03/16/2023 14:38:44] WARNING: Affliction "stima1" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[03/16/2023 14:38:44] WARNING: Affliction "stima1" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[03/16/2023 14:38:43] WARNING: Affliction "foolhardy1" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[03/16/2023 14:38:43] WARNING: Affliction "overjoyed" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[03/16/2023 14:38:42] WARNING: Affliction "fractallyenhanced" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[03/16/2023 14:38:42] WARNING: Affliction "expedition" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[03/16/2023 14:38:41] Couldn't create a hireable for the location: character prefab "hireableclown" not found in the NPC set "outpostnpcs1".
[03/16/2023 14:38:41] Could not find human prefab "hireableclown" from "outpostnpcs1".
[03/16/2023 14:38:41] Couldn't create a hireable for the location: character prefab "hireableseparatistmedicveteran" not found in the NPC set "outpostnpcs1".
[03/16/2023 14:38:41] Could not find human prefab "hireableseparatistmedicveteran" from "outpostnpcs1".
[03/16/2023 14:38:41] Couldn't create a hireable for the location: character prefab "hireableseparatistmechanicveteran" not found in the NPC set "outpostnpcs1".
[03/16/2023 14:38:41] Could not find human prefab "hireableseparatistmechanicveteran" from "outpostnpcs1".
[03/16/2023 14:38:41] Couldn't create a hireable for the location: character prefab "hireableseparatistengineerveteran" not found in the NPC set "outpostnpcs1".
[03/16/2023 14:38:41] Could not find human prefab "hireableseparatistengineerveteran" from "outpostnpcs1".
[03/16/2023 14:38:41] Couldn't create a hireable for the location: character prefab "hireableseparatistsecurityofficerveteran" not found in the NPC set "outpostnpcs1".
[03/16/2023 14:38:41] Could not find human prefab "hireableseparatistsecurityofficerveteran" from "outpostnpcs1".
[03/16/2023 14:38:41] Couldn't create a hireable for the location: character prefab "hireableseparatistmedic" not found in the NPC set "outpostnpcs1".
[03/16/2023 14:38:41] Could not find human prefab "hireableseparatistmedic" from "outpostnpcs1".
[03/16/2023 14:38:41] Couldn't create a hireable for the location: character prefab "hireableseparatistmechanic" not found in the NPC set "outpostnpcs1".
[03/16/2023 14:38:41] Could not find human prefab "hireableseparatistmechanic" from "outpostnpcs1".
[03/16/2023 14:38:41] Couldn't create a hireable for the location: character prefab "hireableseparatistengineer" not found in the NPC set "outpostnpcs1".
[03/16/2023 14:38:41] Could not find human prefab "hireableseparatistengineer" from "outpostnpcs1".
[03/16/2023 14:38:41] Couldn't create a hireable for the location: character prefab "hireableseparatistsecurityofficer" not found in the NPC set "outpostnpcs1".
[03/16/2023 14:38:41] Could not find human prefab "hireableseparatistsecurityofficer" from "outpostnpcs1".
[03/16/2023 14:35:04] WARNING: Potentially invalid damage modifier in "Old Seadog Hat, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[03/16/2023 14:35:04] WARNING: Potentially invalid damage modifier in "Old Seadog Hat, Wearable". Could not find any afflictions of the type "lacerations". Did you mean to use an affliction identifier instead?
[03/16/2023 14:35:04] Failed to parse the string "15" to Vector2
[03/16/2023 14:35:04] Failed to parse the string "15" to Vector2
[03/16/2023 14:35:00] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/16/2023 14:35:00] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/16/2023 14:35:00] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/16/2023 14:34:59] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/16/2023 14:34:59] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/16/2023 14:34:59] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/16/2023 14:34:59] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/16/2023 14:34:59] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/16/2023 14:34:59] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/16/2023 14:34:59] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/16/2023 14:34:59] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/16/2023 14:34:59] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/16/2023 14:34:59] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/16/2023 14:34:58] Could not find human prefab "merchanthusk" from "outpostnpcs1".
[03/16/2023 14:34:58] Could not find human prefab "securitynpcseparatists" from "outpostnpcs1".
[03/16/2023 14:34:58] Could not find human prefab "securitynpcseparatists" from "outpostnpcs1".
[03/16/2023 14:34:58] Could not find human prefab "outpostmanagerseparatists" from "outpostnpcs1".
[03/16/2023 14:34:58] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/16/2023 14:34:54] Error in the fabrication recipe for "Mannitol plus". Could not find the ingredient "Barotrauma.FabricationRecipe+RequiredItemByIdentifier (mannitol)".
[03/16/2023 14:34:54] Error in the fabrication recipe for "Experimental treatment". Could not find the ingredient "Barotrauma.FabricationRecipe+RequiredItemByIdentifier (propofol)".
[03/16/2023 14:34:54] Error in the fabrication recipe for "Artificial brain". Could not find the ingredient "Barotrauma.FabricationRecipe+RequiredItemByIdentifier (mannitol)".
[03/16/2023 14:34:53] Error in item "Fabricator": There's not enough room in the input inventory for the ingredients of "Exploding Assault Rifle Magazine"!
[03/16/2023 14:34:53] Error in item "Fabricator": There's not enough room in the input inventory for the ingredients of "Unlimited Assault Rifle Magazine"!
[03/16/2023 14:34:53] Error in item "Fabricator": There's not enough room in the input inventory for the ingredients of "Unlimited Assault Rifle Magazine"!
[03/16/2023 14:34:52] Generating an outpost for the start of the level... (Location: Jokull Habitation Outpost, level type: Outpost)
[03/16/2023 14:34:52] Level identifier: outpostlevel
[03/16/2023 14:34:47] Error in item "Fabricator": There's not enough room in the input inventory for the ingredients of "Exploding Assault Rifle Magazine"!
[03/16/2023 14:34:47] Error in item "Fabricator": There's not enough room in the input inventory for the ingredients of "Unlimited Assault Rifle Magazine"!
[03/16/2023 14:34:47] Error in item "Fabricator": There's not enough room in the input inventory for the ingredients of "Unlimited Assault Rifle Magazine"!
[03/16/2023 14:34:44] Error in the fabrication recipe for "Mannitol plus". Could not find the ingredient "Barotrauma.FabricationRecipe+RequiredItemByIdentifier (mannitol)".
[03/16/2023 14:34:44] Error in the fabrication recipe for "Experimental treatment". Could not find the ingredient "Barotrauma.FabricationRecipe+RequiredItemByIdentifier (propofol)".
[03/16/2023 14:34:44] Error in the fabrication recipe for "Artificial brain". Could not find the ingredient "Barotrauma.FabricationRecipe+RequiredItemByIdentifier (mannitol)".
[03/16/2023 14:34:40] Error in StatusEffect config - item prefab with the identifier "smallcrawlereggfrendlytimmed" not found.
[03/16/2023 14:34:40] WARNING: Affliction "stima1" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[03/16/2023 14:34:40] WARNING: Affliction "stima1" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[03/16/2023 14:34:40] WARNING: Affliction "stima1" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[03/16/2023 14:34:40] WARNING: Affliction "stima1" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[03/16/2023 14:34:40] WARNING: Affliction "stima1" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[03/16/2023 14:34:40] WARNING: Affliction "stima1" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[03/16/2023 14:34:39] WARNING: Affliction "foolhardy1" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[03/16/2023 14:34:39] WARNING: Affliction "overjoyed" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[03/16/2023 14:34:39] WARNING: Affliction "fractallyenhanced" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[03/16/2023 14:34:39] WARNING: Affliction "expedition" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[03/16/2023 14:34:38] Couldn't create a hireable for the location: character prefab "hireableclown" not found in the NPC set "outpostnpcs1".
[03/16/2023 14:34:38] Could not find human prefab "hireableclown" from "outpostnpcs1".
[03/16/2023 14:34:38] Couldn't create a hireable for the location: character prefab "hireableseparatistmedicveteran" not found in the NPC set "outpostnpcs1".
[03/16/2023 14:34:38] Could not find human prefab "hireableseparatistmedicveteran" from "outpostnpcs1".
[03/16/2023 14:34:38] Couldn't create a hireable for the location: character prefab "hireableseparatistmechanicveteran" not found in the NPC set "outpostnpcs1".
[03/16/2023 14:34:38] Could not find human prefab "hireableseparatistmechanicveteran" from "outpostnpcs1".
[03/16/2023 14:34:38] Couldn't create a hireable for the location: character prefab "hireableseparatistengineerveteran" not found in the NPC set "outpostnpcs1".
[03/16/2023 14:34:38] Could not find human prefab "hireableseparatistengineerveteran" from "outpostnpcs1".
[03/16/2023 14:34:38] Couldn't create a hireable for the location: character prefab "hireableseparatistsecurityofficerveteran" not found in the NPC set "outpostnpcs1".
[03/16/2023 14:34:38] Could not find human prefab "hireableseparatistsecurityofficerveteran" from "outpostnpcs1".
[03/16/2023 14:34:38] Couldn't create a hireable for the location: character prefab "hireableseparatistmedic" not found in the NPC set "outpostnpcs1".
[03/16/2023 14:34:38] Could not find human prefab "hireableseparatistmedic" from "outpostnpcs1".
[03/16/2023 14:34:38] Couldn't create a hireable for the location: character prefab "hireableseparatistmechanic" not found in the NPC set "outpostnpcs1".
[03/16/2023 14:34:38] Could not find human prefab "hireableseparatistmechanic" from "outpostnpcs1".
[03/16/2023 14:34:38] Couldn't create a hireable for the location: character prefab "hireableseparatistengineer" not found in the NPC set "outpostnpcs1".
[03/16/2023 14:34:38] Could not find human prefab "hireableseparatistengineer" from "outpostnpcs1".
[03/16/2023 14:34:38] Couldn't create a hireable for the location: character prefab "hireableseparatistsecurityofficer" not found in the NPC set "outpostnpcs1".
[03/16/2023 14:34:38] Could not find human prefab "hireableseparatistsecurityofficer" from "outpostnpcs1".
[03/16/2023 14:34:32] Attempted to access a potentially removed character. Character: Mckinley Hardy, id: 5466, removed: True. AnimController.Collider == null
```

**Comment by Regalis11** [comment] 2023-03-16 12:06
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11496

This seems to be caused by some mods that modify outposts. We've got a fix coming up for this soon, but for now it should be possible to work around the issue by disabling the mod. Sorry for the inconvenience!

**Closed by Regalis11** 2023-03-16 12:06 UTC
