### ISSUE TITLE
Extremely bad performance.

### ISSUE THREAD

**Issue by Jerrody** [Regalis11/Barotrauma#9196] opened 2022-05-22 18:12 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

VERY BAD PERFORMANCE.

When it happens at the map, I'm getting low FPS, even with low graphics preset.

My PC runs without problems: Elite Dangerous, Elden Ring, Squad, and Subnautica.

PC:
Intel Xeon 1220 V3
GTX 1650 SUPER 4GB
12GB RAM 1600

Installed on HDD.

### Reproduction steps

1. Play the game.

### Bug prevalence

Happens every time I play

### Version

0.17.15.0

### -

None

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
None
```

**Comment by Regalis11** [comment] 2022-05-23 06:59
Duplicate of https://github.com/Regalis11/Barotrauma/issues/8961

**Closed by Regalis11** 2022-05-23 06:59 UTC
