### ISSUE TITLE
Memory components have some race condition with lock state signal

### ISSUE THREAD

**Issue by Boolean-Buckeye** [Regalis11/Barotrauma#12274] opened 2023-07-03 01:02 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Many times now when making a circuit which otherwise works, I have encountered issues with the memory component lock state signal. For example, if the lock state goes to 0 at the exact same time a signal is sent, it seems to be entirely random whether the memory component will get the signal stored or not. Similarly, if the lock state is 0 most of the time and gets a pulse of 1, I have seen the stored value become 0 (even when there is NO possible way for the signal_in to have been 0).

### Reproduction steps

I have not succeeded in making simple circuits reproducing this issue, all I have is a few very complex systems where this bug completely annihilates any chance of them working correctly, this bug or group of bugs with the memory lock timing is the single thing holding back so many of my projects which otherwise work when isolating all the subparts of them. But I described basically the situations above, maybe someone else can come up with a clever way to reproduce these bugs with the memory lock state.

### Bug prevalence

Happens regularly

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment] 2023-07-03 07:42
Thank you for the report! I'm fairly certain this is a similar issue as https://github.com/Regalis11/Barotrauma/issues/6501: essentially, the order in which the signals are received affecting the behavior of the circuit. I think we are going to need a way to reproduce the issue to diagnose it, so if anyone figures out a way, please let us know! Thanks and sorry for the inconvenience.

**Comment by mygamingaccount** [comment] 2023-07-04 00:09
> it seems to be entirely random whether the memory component will get the signal stored or not

It depends on the order of the components
If the signal to both inputs comes from the same component, then it depends on the order of wires.

You can check the order of wires by placing them on the same pin as long as their colors are different.

Order depends on creation and not when you attach the component. Fabricate components in the wrong order and there will be propagation delay in your circuit.

**Comment by Boolean-Buckeye** [comment] 2023-07-04 02:46
> Thank you for the report! I'm fairly certain this is a similar issue as https://github.com/Regalis11/Barotrauma/issues/6501: essentially, the order in which the signals are received affecting the behavior of the circuit. I think we are going to need a way to reproduce the issue to diagnose it, so if anyone figures out a way, please let us know! Thanks and sorry for the inconvenience.

It looks to me like https://github.com/Regalis11/Barotrauma/blob/c67f6688fdf4dcffa224711a0d4f4181d9a1fad4/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Signal/Connection.cs#L316 is where all the signals to a component are received and processed, and based on what this person is saying:

> Order depends on creation and not when you attach the component. Fabricate components in the wrong order and there will be propagation delay in your circuit.

which I have not confirmed but sounds believable, it looks like probably the order of the creation of the components might affect the order that the signals are processed in this iterator loop because barotrauma has no logic for what order to process the signals in, they all just get this function called and the behavior for what order they are called in is completely undefined with regards to type of component causing the signal (maybe this shouldn't matter), type of signal (which pin) being received (this is important in my opinion), or which wire on the same input pin is gets the right away to dominate that input (maybe this is okay to be undefined).

Probably this iterator order under the hood is not consistent either because of the order of connection or the order of fabrication like the person above says. And so therefore this causes lots of different circuits to act in ways that people dont expect because there is no well defined order to what should happen and people make assumptions about what should happen. 

I think it would make sense to implement some type of priority value for all the signal lines and in this loop (or whatever loop if I am in the wrong place, im just skimming the codebase obviously since I dont work for undertow), figure out which input signal pins on a device have the highest priority and process those first, and that might solve a lot of issues people have. For example, in my opinion it is very logical to process the lock_state  signal on a memory component *before* the signal_in. And similarly, things like on a delay component it makes sense to process the set_delay before the signal_in, etc. 

Doing something like this might break existing circuits that got lucky with or are relying on the undefined behavior but at least going forward there would be some level of consistency that people can rely on.

**Comment by mygamingaccount** [comment] 2023-07-04 03:18
> Probably this iterator order under the hood is not consistent either because of the order of connection or the order of fabrication like the person above says. And so therefore this causes lots of different circuits to act in ways that people dont expect because there is no well defined order to what should happen and people make assumptions about what should happen.

It is internally consistent since the order is dependent on the ID of the circuit component. Saved circuits will be consistent.
Also, depending on how they were saved, two circuits that appear the same might have completely different outputs because of this.
For continuous signals it will never cause issues. When you have time sensitive signals then the order will make or break your circuit.
There is also no support for circuits with loops, you must select where you want to insert a delay using a memory component when there is a loop in your circuit.

Prioritizing is a silly bandaid for something that isn't a problem with 99% percent of the circuits. You have to remember that this is a cool video game with fantasy subs, not an industrial control system that needs a solver like the ones Matlab has.

**Comment by decsny** [comment] 2023-07-04 03:34
> Prioritizing is a silly bandaid for something that isn't a problem with 99% percent of the circuits. You have to remember that this is a cool video game with fantasy subs, not an industrial control system that needs a solver like the ones Matlab has.

I completely disagree with everything in this paragraph, what I am suggesting is not a fancy circuit simulator calculator, just a consistent behavior that the average player can expect. I certainly did not expect that the behavior of a circuit that looks exactly the same as another is dependent on the order of the fabrication of the components in the circuit because of some internal ID in the game code that isn't even exposed to me. What you're suggesting is terrible game design unless these IDs are exposed to the player and even then it still doesn't seem very friendly. You're saying to remember this is just a game - well I think what I'm suggesting is way better design *for a game* where the average player is not going to go and debug the source code to understand why the systems they are playing with in the game are so inexplicably and frustratingly inconsistent.

**Comment by Boolean-Buckeye** [comment] 2023-07-04 03:37
> Prioritizing is a silly bandaid for something that isn't a problem with 99% percent of the circuits. You have to remember that this is a cool video game with fantasy subs, not an industrial control system that needs a solver like the ones Matlab has.

I completely disagree with everything in this paragraph, what I am suggesting is not a fancy circuit simulator calculator, just a consistent behavior that the average player can expect. I certainly did not expect that the behavior of a circuit that looks exactly the same as another is dependent on the order of the fabrication of the components in the circuit because of some internal ID in the game code that isn't even exposed to me. What you're suggesting is terrible game design unless these IDs are exposed to the player and even then it still doesn't seem very friendly. You're saying to remember this is just a game - well I think what I'm suggesting is way better design *for a game* where the average player is not going to go and debug the source code to understand why the systems they are playing with in the game are so inexplicably and frustratingly inconsistent.

And it's not a bandaid, the main issue is literally that the circuits have different behavior where each input pin is processed in a different order that is not explained by the game or intended by the developers. The *formal* and *final* fix for this is to intentionally define the order that each input should be processed in.

**Comment by mygamingaccount** [comment] 2023-07-04 05:25
I think if you have a definitive idea of a system that without a doubt would improve intuitiveness without introducing too much complexity, you should present it in a form of a PR. The current system despite its flaws does actually work and it is most importantly simple from the programmer's standpoint.

I would go back to the original problem that sparked this report: what is the reason for needing a lock on the memory component, and can it not be solved by a simpler circuit which does not require time sensitive signals to be used?
These types of questions are very often discussed in the sub builders forum and usually it turns out that a much simpler solution exists than originally thought.

**Comment by Regalis11** [comment] 2023-07-04 16:49
Mygamingaccount's description of the behavior is correct: in some cases, the order in which the signals arrive can make a difference and the order in which signals are sent depends on the order in which items are created.

This can happen in basically 2 different situations:
1. If the circuit is very complex and the signal propagation doesn't get fully calculated during one frame.
2. If an input is receiving signals from two different sources during the same frame.

I would see the behavior in the 2nd situation as something that isn't necessarily a bug (as @Boolean-Buckeye mentioned, that _should_ lead to undefined behavior), but the 1st one is definitely a bug and not how it should work. A player should not need to know about the inner workings of the system or stuff like item IDs to diagnose a problem in a circuit. However, this has turned out to be quite a complex problem to solve, and so far we haven't come up with a feasible way to solve it (aside from redesigning the whole signal logic from the ground up and most likely breaking tons of custom circuits in the process). There was one [promising suggestion in the discussion](https://github.com/Regalis11/Barotrauma/discussions/5001) that we considered for a while, but it turned out it had various other problems that would've been possibly even worse than the issues with the current system. This issue also hasn't been that high on our priority list, since it seems to affect a very small portion of players building very specific kinds of complex circuits.

However, it could be that this specific issues is some edge case that could be solved in a more simple way. We would need to find a way to reproduce it though - if you have a submarine file where this occurs for example, sending that to us would help us a lot in diagnosing the problem. Sorry for the inconvenience!

**Comment by Regalis11** [comment] 2023-08-21 08:40
Insufficient information to diagnose the issue, closing

**Closed by Regalis11** 2023-08-21 08:40 UTC
Labels: Bug, Need more info, Code
