### ISSUE TITLE
No output on POWER/LOAD_VALUE_OUT on Junction Boxes when "Can Be Overloaded" is unchecked

### ISSUE THREAD

**Issue by Orum** [Regalis11/Barotrauma#8473] opened 2022-03-07 09:01 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When the "Can Be Overloaded" option on a Junction Box is unchecked, both the `POWER_VALUE_OUT` and `LOAD_VALUE_OUT` cease to function (produce only null output).

**Steps To Reproduce**
In the editor, add a new Junction Box in (or tweak an existing one) and uncheck "Can Be Overloaded" under "PowerTransfer".  Connect a wire between either the `POWER_VALUE_OUT` or `LOAD_VALUE_OUT` to a Text Display, and observe the null output.

**Version**
v0.16.7.0 Linux

**Additional information**
I do not believe this is related to #8386 for several reasons, but most importantly they got `0` instead of null.

**Comment by cshingle** [comment] 2022-03-08 22:31
I believe the issue is that [this line](https://github.com/Regalis11/Barotrauma/blob/dev/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Power/PowerTransfer.cs#L220) should be move under [this](https://github.com/Regalis11/Barotrauma/blob/dev/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Power/PowerTransfer.cs#L233).

I'll test this and create a PR is it resolves the issue.

**Comment by 3e849f2e5c** [comment] 2022-03-10 13:03
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0a75a869643789f4f1e339b9cb3713811a3e75ff

**Comment by Rokvach** [comment] 2022-04-11 11:43
Tested, working correctly. Closing.

**Closed by Rokvach** 2022-04-11 11:43 UTC
Labels: Bug, Code
