### ISSUE TITLE
When a new round start players who are in the lobby will automatically join and their inventory will be initialised.

### ISSUE THREAD

**Issue by esirprus** [Regalis11/Barotrauma#9536] opened 2022-07-06 14:19 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [x] My issue happened while using mods.

### What happened?

When a round is in progress and you are in the lobby, if you have previously created a character in this campaign, when the round end and a new round start you will automatically join, your equipment will change to initial and your character skills and level will remain the same.
A similar situation is when you click on continue and the other player‘s chat bar can see you've joined the game, but it doesn't show respawn in the top left corner yet. when the round end and a new round start, your inventory will also have a high probability of being initialized.

### Reproduction steps

1. Join a multiplayer campaign, ensure (1) you have previously created a character with some items in your inventory (2) a round is in progress (3)you are in the lobby
2. don't click continue, just wait and you will automatically join when the round is end and a new round is start
3. check your inventory and skills

About Bug prevalence: I think this can be triggered fairly consistently, but I have observed one exception, so not sure

### Bug prevalence

Happens regularly

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-07-06 14:46
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d8d80afdb405f211aa7b45ffe683cbccb5b20ad5

**Comment by esirprus** [comment] 2022-07-06 14:52
I think I need to shoot a video to showcase this, please open this issue for a while, thanks!

**Comment by esirprus** [comment] 2022-07-07 08:47
https://user-images.githubusercontent.com/44423036/177731891-e3aafac4-1a7d-4325-8247-9010a5c0b19f.mp4

reproduced the bug, but slightly different from the description, see video

**Comment by esirprus** [comment] 2022-07-07 08:50
@Regalis11  see this video, I as "loafer" just quit the campaign, and reconnect, when I am in lobby, my friend "连辰" dock the sub. This make my inventory be initialised.

**Comment by NilanthAnimosus** [comment] 2022-07-07 18:04
I assume "Inventory initialized" and "equipment to initial" means you have a default inventory for your mods (and lose all the items you had beforehand like picked up items and such) and reverting to the inventory you have when you first begin instead of what you last had.

Otherwise, I am not sure I understand the issue either, joining the game when a round starts is normal behavior.

**Comment by NilanthAnimosus** [comment] 2022-08-10 13:26
I can't find any commit(s) indicating this is fixed while it's inside the internal QA Backlog, I also cannot find said commit in the bugfixes PR or dev/bugfixes branches.

**Comment by Regalis11** [comment] 2022-08-19 10:33
@NilanthAnimosus I'm not completely sure, but I think I moved this to QA because as far as I can tell, there doesn't seem to be an issue here (joining the game when the round starts is intended behavior), and I thought QA could try to verify there's nothing off here.

**Comment by NilanthAnimosus** [comment] 2022-09-06 11:21
Tested against networking-fixes-critical commit https://github.com/Regalis11/Barotrauma-development/commit/c8ecff6a236981bb5022e26e7dc86060b4288b02

We replicated this successfully and found problems under these circumstances:

If two players are in a campaign (that has definitely saved both, IE. after a transition). one disconnects and reconnects to lobby waiting with their character loaded in game (Death by disconnection or still alive).

If the in game player does another level transition (IE. dock/undock from station) while the player in lobby has not hit spectate, next round the lobby player will lose all wallet money and items but not skills. Additionally the body (if killed by disconnect or alive) will not leave a duffel bag of items either, these items simply cease to exist.

the characters talents and skills will be retained. If they are in the lobby and not spectating/controlling character then their character dies, they correctly leave a duffel bag and take penalties to skills (As expected).

Assumedly due to issues with regaining character control when reconnecting under certain circumstances, one may assume this also was a trigger for item loss as its likely related to character control in general while the player is presently in the server.

**Comment by esirprus** [comment] 2022-09-06 11:32
Oh my, Hope this will be fixed!!!

**Comment by Regalis11** [comment] 2022-09-06 12:20
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/f6f6d88536afb55f97efe7638da019d1ff89b63d

**Comment by Regalis11** [comment] 2022-09-06 12:22
This seems like it could be a duplicate of https://github.com/Regalis11/Barotrauma/issues/7228, moving that to QA as well

**Comment by esirprus** [comment] 2022-09-06 12:31
Oh nice. I hadn't noticed this QA before, so it looks like it's a serious problem.
Then I want ask is this issue related? #9342

**Comment by Rokvach** [comment] 2022-09-15 10:44
Tested, the above mentioned issues has been fixed and is working correctly. Closing.

**Closed by Rokvach** 2022-09-15 10:44 UTC
Labels: Bug, Code, Networking, Unstable
