### ISSUE TITLE
A Few Changes in Docking Stuff- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#739] opened 2018-08-25 18:49 UTC
Docking Hatch:
* Upon docking a 100% hull's size water will spawn inside a hull between submarines.
* A tube will show up between submarines, explaining why passage between them won't flood plus players cannot use leaks anymore between submarines to go into other places.

Docking Port:
* Upon docking a 100% hull's size water will spawn inside a hull between submarines.
* A tube will show up between submarines, explaining why passage between them won't flood plus players cannot use leaks anymore between submarines to go into other places. This makes it possible to cross between submarines with no risk of falling into water below passage.

**Comment by rico6822** [comment] 2018-08-26 10:34
The water spawns, because it won't just magically disappear upon docking between submarines.

**Comment by thegrb93** [comment] 2018-08-26 11:41
You can't see inside the docking mechanism anyway so what is the point? Just pretend all that shit is already happening.

**Comment by rico6822** [comment] 2018-08-26 13:45
But you can still fall into water below you, when crossing docking ports. Placing a platform reduces risk.

**Comment by Regalis11** [comment] 2018-08-26 16:56
Duplicate of #547

**Closed by Regalis11** 2018-08-26 16:56 UTC
