### ISSUE TITLE
[Steam version] Game's resolution does not get affected by resolution settings, if you are in borderless windowed mode

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#1276] opened 2019-03-13 16:27 UTC
Resolution 640x400 in fullscreen mode
![20190313225801_1](https://user-images.githubusercontent.com/38168249/54295123-05e17600-45e5-11e9-8f14-dec006eabaeb.jpg)
Resolution 640x400 in borderless windowed mode
![20190313225746_1](https://user-images.githubusercontent.com/38168249/54295112-ffeb9500-45e4-11e9-8948-a4ef673ca655.jpg)

Restarting the game, after changing settings, did not have any effect.

Win 7
Monitor's original resolution is 1920x1080

**Comment by CommanderMark** [comment] 2019-03-14 03:20
Barotrauma purposefully disables this because as of Monogame 3.7 resizing in borderless fullscreen doesn't work. More specifically, it doesn't upscale the game's smaller resolution to fit the window. It's also the same reason resolution can't be changed in fullscreen on macOS.

[According to this guy this is the intended behavior and you're suppose to implemented upscaling yourself](https://github.com/MonoGame/MonoGame/issues/6308#issuecomment-385886594), though why this is the case and why prior to 3.7 it did upscale I have no clue.

With that said it should be possible to implement upscaling for borderless manually. I tried doing that a while back but wasn't able to get anywhere with it.

**Comment by Rokvach** [comment] 2019-07-20 23:01
There's been multiple improvements to this issue by now, I don't see a point keeping this open. Closing.

**Closed by Rokvach** 2019-07-20 23:01 UTC
Labels: Bug, Code
