### ISSUE TITLE
Fire and fire extinguisher

### ISSUE THREAD

**Issue by Chaos456456** [Regalis11/Barotrauma#274] opened 2018-02-22 21:02 UTC
#fire extingusher cant extinguish fire

**Comment by Billsofat** [comment] 2018-02-23 00:24
Try standing farther away from the fire. They seem to work for me if I do that.

**Comment by NilanthAnimosus** [comment] 2018-02-23 02:49
The fire extinguisher code in 0.8.0.1 only checks the start and end of the raycast (Not the inside).

Commit 45ea91a3711b1f8cc02be704012facd2ea02d0d9 on the command branch upgraded this to step through the raysize in 10% steps to collect any fires along the path of the raycast, Including some of this would improve the fires (I have tested this code myself)

However the code used there also brings in additional crashes, I had to add a try-catch around the repair tool code which improved the extinguisher due to bugs I can't explain which I will leave here:

Exception: Object reference not set to an instance of an object.
Target site: Void Repair(Microsoft.Xna.Framework.Vector2, Microsoft.Xna.Framework.Vector2, Single, Barotrauma.Character, Single, System.Collections.Generic.List`1[FarseerPhysics.Dynamics.Body])
Stack trace: 
   at Barotrauma.Items.Components.RepairTool.Repair(Vector2 rayStart, Vector2 rayEnd, Single deltaTime, Character user, Single degreeOfSuccess, List`1 ignoredBodies) in F:\Barotrauma\BT NilEdit\Barotrauma---Nilanths-Edits\Barotrauma\BarotraumaShared\Source\Items\Components\Holdable\RepairTool.cs:line 167

Line 167 = for (float x = 0.0f; x <= Submarine.LastPickedFraction; x += 0.1f)

For the modification code I used it in early (As I could not understand how/why object reference was not set given these were floats, I used a try-catch to prevent this in case this is included as a warning).

**Comment by Regalis11** [comment] 2018-02-23 22:01
They can fix fires, but the aiming logic is extremely inaccurate - you have to hit the "bounding box" at the base of the fire with an invisible ray that is cast from the position of the extinguisher. The fixes in the command branch should take care of this, I'll add them to the main branch for the next patch.

@NilanthAnimosus Are you sure that line number is correct? I don't see how that line could be causing null reference exceptions. I'm guessing/hoping the exceptions were actually caused by positions along the ray being outside hulls (which should be fixed in 4389a65).

**Comment by NilanthAnimosus** [comment] 2018-02-24 05:35
Honestly I couldn't work out why, but it was added to 0.7.0.1 code. and I had not added parts from commit https://github.com/Regalis11/Barotrauma/commit/4389a657a67b13b13d85c86a8a22fc433f830f49 so it could have been fixed, it would only occur once every 2-3 rounds, perhaps 7 rounds. it was random but I would often wind up with the crash. the line number I didn't trust either but in case I threw a try-catch around it despite it making very little sense for a float or a class.

I only mentioned it as a precaution when I had tried that specific part of code out for my server-side mod. sadly I hadn't done much testing on the command branch to see if it occurred there but felt it was worth mention.

**Closed** 2018-02-24 15:30 UTC
Labels: bug
