### ISSUE TITLE
White/black screen crash?

### ISSUE THREAD

**Issue by AmZeeeee** [Regalis11/Barotrauma#536] opened 2018-07-28 00:06 UTC
So, when I open up the game it takes about 20 seconds to 1 minute for the game to un-fullscreen, become mostly white and somewhat black as well as becoming unclosable and unadjustable. It becomes a background process in Task Manager, too. Can anyone help me with this?

**Comment by NilanthAnimosus** [comment] 2018-07-28 09:01
there are issues with monogame and fullscreen, does borderless fullscreen work better?

it should at least not appear as a background process then

**Comment by Regalis11** [comment] 2018-07-28 17:37
I believe this is related to (or a duplicate of) #35. Until that's fixed I recommend using borderless windowed instead of actual fullscreen.

**Closed** 2018-07-31 08:16 UTC
Labels: bug
