### ISSUE TITLE
[0.1200.0.1] Bots - Mission items in cargo crates are being cleaned up

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4570] opened 2020-12-19 21:04 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots are cleaning up Purchased/Cargo items in crates.

**Version**
0.1200.0.1

**Comment by ezjamsen** [comment] 2021-01-04 08:13
This is as intended, unless I misunderstand the issue.

**Comment by itchyOwl** [comment] 2021-01-04 10:08
It's intentional that the bots put purchased items in (the right?) places. What's the issue here? Is it not working right or just unexpected behavior?

**Comment by Kaillera** [comment] 2021-01-04 12:10
They also clean up the mission cargo, as in if you picked medical delivery, they'll put it in your medical cabinet and you won't be able to differentiate what's yours. Also seeing stuff like husk eggs, detonators, compound n, and other stuff show up in your cabinets will entice you to use them by accident.

**Comment by ezjamsen** [comment] 2021-01-04 12:14
Oops! that's a bug!

**Comment by ekqvist** [comment] 2021-01-04 13:03
There was also another report (#4628) of bots using the mission supplies in some cases, and I proposed that we could tag the mission supplies with "ignorebyai" when they are spawned which should make the bots ignore them unless specifically ordered otherwise. I used the same method with some items spawned for the outpost events which were being cleaned up by the outpost NPCs in some cases.

**Comment by itchyOwl** [comment] 2021-01-04 14:37
Fixed in Regalis11/Barotrauma-development@1721c53.

**Comment by Rokvach** [comment] 2021-01-11 09:54
Tested, working correctly. Closing.

**Closed by Rokvach** 2021-01-11 09:54 UTC
Labels: Bug, Code
