### ISSUE TITLE
Hunter, Mollusc and Skitter genes do not work

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#9718] opened 2022-08-16 10:20 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When a character with any of the "On Damage" type genes (Hunter, Mollusc, Skitter) take more than 5 damage, no affliction is given. 

Tested on all 3 gene types, with multiple different types of weapons, enemies, and tools. 

It was expected that while having Hunter genes at 100% for example, that upon taking damage the character would be given the "Increased Melee Damage (Temporary)" affliction at 100 strength

https://user-images.githubusercontent.com/37850646/184856275-cb8daf7d-f1bb-4fb2-a035-40ff35699ee8.mp4

### Reproduction steps

1. Give a character Hunter, Mollusc or Skitter genes of any strength
2. Strike them with a boarding axe or any other weapon that deals >5 damage
3. They will not gain any relevant affliction

### Bug prevalence

Happens regularly

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by NilanthAnimosus** [comment] 2022-08-18 18:09
Tested in 0.18.15.1 - I am also unable to get vigor or hyperactivity on a character to trigger when damaged by a boarding axe or SMG round.

through quickly checking the Character.DamageLimb method where OnDamaged status effects are applied - the status effect list was null (Instead of the expected list containing the genetic material status effects ?)

I believe this problem is possibly due to StatusEffect.HasRequiredAfflictions check, the comparison logic uses:
```
Any(a2 => a.Strength >= a2.strength && (a.Identifier == a2.affliction || a.Prefab.AfflictionType == a2.affliction))
```
where it is compared against the identifier, not compared against the type.

**Comment by Regalis11** [comment] 2022-08-19 08:44
Seems to have been caused by the same issue as https://github.com/Regalis11/Barotrauma/issues/9552, fixed in https://github.com/Regalis11/Barotrauma-development/commit/2240d25499cc8adb54db7ff33b2a9ead7a2fccbf

> where it is compared against the identifier, not compared against the type.

The affliction field of requiredAfflictions can be either an affliction identifier or an affliction type, so the comparison is correct.

**Comment by NilanthAnimosus** [comment] 2022-08-19 10:49
Tested in dev branch commit https://github.com/Regalis11/Barotrauma-development/commit/4cc9940f05664f53263ed21db7c9618c1b87ceb8

Works correctly as intended, will likely be in the next unstable build.

**Closed by NilanthAnimosus** 2022-08-19 10:49 UTC
Labels: Bug, Code, Unstable
