### ISSUE TITLE
Help Captain Event

### ISSUE THREAD

**Issue by ScorboGusya** [Regalis11/Barotrauma#10372] opened 2022-11-13 11:55 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I start new campaign in Unstable. And found event. Captain need a help with map. When i helped him event start over. Only when i go away from him this ends.
**Redacted:** This happens with any event

### Reproduction steps

1. Solo campaign 
2. Start campaign
3. Find captain what need help
4. Help him
5. Event repeat
6. I holding movement key to go away and skip this dialogue
7. When i go away on ~0.5m this ended
8. 89 helm but why cost?

### Bug prevalence

Happens regularly

### Version

0.20.5.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
I don't have any crashes. Don't find any error text.
```

**Comment by Regalis11** [comment] 2022-11-13 15:02
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10320

**Closed by Regalis11** 2022-11-13 15:02 UTC
