### ISSUE TITLE
[0.9.708] Multiplayer - Character Bobble Head when Swimming

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2293] opened 2020-02-13 19:52 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Characters are vigorously bobbing their head when swimming.

**Steps To Reproduce**
Go swimming, especially with a scooter.

**Version**
0.9.708

**Comment by mrjpjr** [comment] 2020-03-28 00:12
The head bobbing has returned.

Multiplayer Missions
Unstable 9.9.0 revision 4a9fd6d77

**Comment by Regalis11** [comment] 2020-04-01 14:58
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6ff1d282a495a59960643e01f6885b1d9df0ff24. 

Happened because the character collider's angular damping would get set to zero when the ragdoll is frozen. Freezing happens for example when the network connection is bad and the server doesn't receive inputs from the client in time, or if the client doesn't receive position data from the server in a while. An easy way to repro this is to play alone in the server, use freecam and wait for the character to get disabled, and then switch control back to the character.

**Comment by Rokvach** [comment] 2020-04-03 14:05
Couldn't reproduce, seems to be working. Closing.

**Closed by Rokvach** 2020-04-03 14:05 UTC
Labels: Bug, Code, Networking
