### ISSUE TITLE
Failed quest with selling husk eggs to suspicious person - Unable to talk to him again after switching characters

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#10051] opened 2022-10-10 17:12 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

You can't talk to the suspicious person asking to buy husk again if you switch crew members.

### Reproduction steps

Tell the suspicious character you might have husk eggs to sell him
Switch to another crew member (medic is the only one with access to the eggs)
Gather the eggs and return to sell them
Unable to talk to him again.

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-10-11 06:55
Duplicate of https://github.com/Regalis11/Barotrauma/issues/5010

**Closed by Regalis11** 2022-10-11 06:55 UTC
