### ISSUE TITLE
Massive, biblic levels of unplayable frames per second issues

### ISSUE THREAD

**Issue by MalricB** [Regalis11/Barotrauma#423] opened 2018-05-24 14:53 UTC
Hello! I've been playing Barotrauma for quite some time now, decided to take a break, and now that I've came back... it's hell. A fun hell sometimes, but now that I'm writing this and I need to vent for having an amazing role (captain, traitor, target = security guard) that was completely ruined by a TWO frames per second limit on a sinking submarine.
It's recently becoming more and more present, mostly when something explodes or water comes into the sub.
Is there any way to fix or somewhat alleviate this? Because two frames per second is just disgusting, It's like watching a picture slideshow of a man with alzheimers.
Sorry if this isn't meant to be posted here, I'm pretty frustrated and in a rush.
Windows 10 64 bits, Geforce 750 TI, 8 GB Ram, Ryzen 5 1400 ~3.2 GHz.
I love this game, but I wish I could play it without being hindered with this issue.

**Comment by ClasticM** [comment] 2018-05-26 02:40
My girlfriend had this same issue on her laptop. I think its a processing issues with some pcs

**Comment by Regalis11** [comment] 2018-09-10 14:00
Duplicate of #115

**Closed by Regalis11** 2018-09-10 14:00 UTC
Labels: Performance-related, bug
