### ISSUE TITLE
Barotrauma.Networking.GameClient.ReadIngameUpdate - crash to menu

### ISSUE THREAD

**Issue by tastesliketriangle** [Regalis11/Barotrauma#7087] opened 2021-10-30 03:13 UTC
joined a server, chose roles, clicked spectate. loading seemed to be almost finished when it crashed to menu, said to post this log file.

[networkerror_data.log](https://github.com/Regalis11/Barotrauma/files/7445735/networkerror_data.log)

**Comment by Regalis11** [comment] 2021-11-01 07:51
Duplicate of https://github.com/Regalis11/Barotrauma/issues/1815

**Closed by Regalis11** 2021-11-01 07:51 UTC
