### ISSUE TITLE
Exosuit Warning beep doesn't work when carrying Oxygen in it's storage space

### ISSUE THREAD

**Issue by bobingabout** [Regalis11/Barotrauma#11319] opened 2023-02-23 15:42 UTC
As the Title says, the low oxygen warning beeps on the Exosuit don't go off when you're carrying space oxygen in it's inventory.

In the ItemContainer definition add `targetslot="0"` to the warning lines.
Example
Change:
```XML
        <StatusEffect type="OnWearing" target="Contained">
          <RequiredItem items="oxygensource" type="Contained" />
          <Conditional condition="lt 5.0" />
          <Sound file="Content/Items/WarningBeepSlow.ogg" range="500" loop="true"/>
        </StatusEffect>
        <StatusEffect type="OnWearing" target="Contained" playsoundonrequireditemfailure="true">
          <RequiredItem items="oxygensource" type="Contained" matchonempty="true" />
          <Conditional condition="lte 0.0" />
          <Sound file="Content/Items/WarningBeep.ogg" range="500" loop="true"/>
        </StatusEffect>
```
to
```XML
        <StatusEffect type="OnWearing" target="Contained" targetslot="0">
          <RequiredItem items="oxygensource" type="Contained" />
          <Conditional condition="lt 5.0" />
          <Sound file="Content/Items/WarningBeepSlow.ogg" range="500" loop="true"/>
        </StatusEffect>
        <StatusEffect type="OnWearing" target="Contained" playsoundonrequireditemfailure="true" targetslot="0">
          <RequiredItem items="oxygensource" type="Contained" matchonempty="true" />
          <Conditional condition="lte 0.0" />
          <Sound file="Content/Items/WarningBeep.ogg" range="500" loop="true"/>
        </StatusEffect>
```

**Comment by Regalis11** [comment] 2023-02-23 16:10
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11076

**Closed by Regalis11** 2023-02-23 16:10 UTC
