### ISSUE TITLE
Exosuit buzzer beeps if there is an empty O2 tank in storage

### ISSUE THREAD

**Issue by mygamingaccount** [Regalis11/Barotrauma#11311] opened 2023-02-22 07:53 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Even if the O2 tank equipped for breathing is full, having an empty tank in its storage will cause the warning sound to play

### Reproduction steps

Put an O2 tank in a welder to get it to 0%
Put it in the exosuit storage
Have O2 in the exosuit

Get:
Beeping
Expect:
No beeping

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment] 2023-02-22 08:11
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11076

**Closed by Regalis11** 2023-02-22 08:11 UTC
Labels: Bug, Design
