### ISSUE TITLE
Unable to use crafting recipes with good, excellent or masterwork quality items

### ISSUE THREAD

**Issue by atlas-callisto** [Regalis11/Barotrauma#7732] opened 2021-12-12 01:38 UTC
Upon trying to craft items like the heavy power switch, which requires 4 cell batteries, or a tazer cartridge, you cannot complete the fabrication as it seems to not like excellent quality cell batteries when trying to craft. This also happens for the Oxygen Cell MK-II, where I cannot use good-quality oxygen tanks to craft them. They must be standard-quality oxygen tanks.

This can make it impossible to craft some items until you can find the standard version of it in a station for sale, which is really inconvenient. I'm assuming it's just an oversight when implementing the new quality system.

**Comment by Regalis11** [comment] 2021-12-12 12:04
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7191

**Closed by Regalis11** 2021-12-12 12:04 UTC
