### ISSUE TITLE
Shuttle teleports itself in the middle(?) of the submarine instead of disappearing/docking properly

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#4558] opened 2020-12-18 17:51 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you dock to an outpost in campaign, shuttles that were not docked to the submarine will teleport inside the submarine instead of either "disappearing" (abandonned shuttle) or spawning in their proper docking port.

**Steps To Reproduce**
1. Undock a shuttle near an outpost
2. Dock main submarine to outpost
3. Shuttle appears inside the submarine

**Version**
 v0.11.0.9 Win10

**Additional information**
![20201218171754_1](https://user-images.githubusercontent.com/73229309/102645000-0c116880-4162-11eb-80de-f9d26874bb83.jpg)

Had to use "teleportsub" to teleport away from the shuttle

**Comment by Regalis11** [comment] 2021-01-05 12:45
I'm afraid I could not reproduce this with any of the vanilla submarines. Is this custom sub available in the Workshop or could you post it here so we could try debugging it?

**Comment by ubertpendragon** [comment] 2021-01-05 14:04
My cursed submarine
https://steamcommunity.com/sharedfiles/filedetails/?id=2319699153

Quite hard to reproduce as it happened sporadically in multiplayer

I think it has to do with how the game tries to recover shuttles; if you move to a next area it teleports all nearby shuttles within a certain radius at their relative positions but for some reason they _sometimes_ teleport inside

**Comment by Rokvach** [comment] 2021-02-24 15:07
Haven't tested in a while but I used to be able to reproduce this quite easily by just 

1. Undock from outpost
2. Undock drone
3. Set drone to manual steering and point the needle towards the sub
4. Dock to the outpost
5. Shuttle/drone should be inside the sub

**Comment by Regalis11** [comment] 2021-03-10 16:20
I wasn't able to reproduce this. Could be that the recent changes to the docking / linked sub logic might've fixed this.

**Comment by Rokvach** [comment] 2021-03-15 06:25
Tested, I wasn't able to reproduce this with the method I was able to do it previously, seems to have been fixed at some point. Closing.

**Closed by Rokvach** 2021-03-15 06:25 UTC
Labels: Bug, Code, Medium Prio, Need more info, Needs testing
