### ISSUE TITLE
NPC crew not able to use turrets

### ISSUE THREAD

**Issue by SinisterSnaek** [Regalis11/Barotrauma#10434] opened 2022-11-18 17:30 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

After loading into a campaign save, where NPC crew is ordered to use turrets from the previous save, they will get on the guns, but will not fire any hostiles until the order is cancelled and given again.

### Reproduction steps

1. Start multiplayer campaign
2. Order NPC crewmates to use turrets
3. complete a mission (arrive at a station)
4. Leave the game and rejoin. (crew will still be ordered to use turrets)
5. Leave the station and find or spawn a hostile
The crew will be using turrets, but will not fire at the hostile

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by ekqvist** [comment] 2022-12-02 12:31
Hi! Unfortunately, I was unable to reproduce the issue. Even after giving the order, them shooting successfully, docking to a station, saving and quitting, continuing, and undocking, they successfully shoot at enemies with the same order.

You reported that this issue happens to you every time you play. Could you think of any additional steps you're taking for this to happen? Are you getting any error messages in the console while this happens or after reloading the campaign?

**Comment by Regalis11** [comment] 2023-02-16 08:58
No known steps to repro, closing

**Closed by Regalis11** 2023-02-16 08:58 UTC
Labels: Bug, Need more info, Code
