### ISSUE TITLE
beacon station hatch not targettable from outside

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5788] opened 2021-05-13 19:32 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
the exterior hatch on the beacon station is not targettable from outside when the hatch is closed, rather, the ladder gets aim priority over the hatch.
occurs with both 0% and 5% aim assist

expectation is to be able to select the hatch from outside the station

![image](https://user-images.githubusercontent.com/5103517/118176772-d6666800-b3ff-11eb-9c4f-9c24d4bd3b2c.png)

**Steps To Reproduce**
1. load beacon station 1 into sub editor
2. swim outside the beacon station
3. close the hatch
4. try to select the hatch for rewiring (sometimes the hatch is unwired)

**Version**
0.1400.0.0 unstable windows

**Additional information**
suggested fix is to move the hull down a grid snap
![image](https://user-images.githubusercontent.com/5103517/118177246-6ad0ca80-b400-11eb-91f2-7ca16cff3386.png)

**Comment by Ek-Videogames** [comment] 2021-05-14 06:16
This has been a known issue for a long time, to be specific this bug is the fact that - doors which border the connection between open-water and a hull volume get their hitbox all _fucky_ (not selectable at all - or very inconsistent hitbox) when trying to interact with them from outside the hull volume.

**Comment by Regalis11** [comment] 2021-05-17 16:10
@Ek-Videogames You were on the right track, but this turned out to be caused by a bug in the way the game checks whether there's something between the character and the item it's trying to interact with. Basically, it wouldn't correctly interpret the door's fixture (a part of the submarine's exterior collider) as the door itself, thinking there's a part of the submarine in the way.

There's also a couple of other inaccuracies in your description of the issue. The items' hitboxes have nothing to do with the way the game determines which item the cursor is focused on, and there's no object instancing involved in the way the game handles the submarine's interiors.

Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e6b763a7d8ead7992a8ba31562a90f91c9b23c93

**Comment by Rokvach** [comment] 2021-05-19 09:11
Tested, working correctly. closing.

**Closed by Rokvach** 2021-05-19 09:11 UTC
Labels: Bug, Code
