### ISSUE TITLE
Medicine Cabinet can no longer hold Storage Containers

### ISSUE THREAD

**Issue by AndyPuettmann** [Regalis11/Barotrauma#10185] opened 2022-10-29 09:10 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Before the last larger update, it was possible to put medical supplies inside storage containers inside the medicine cabinet.

Now it is no longer possible to put storage containers into medicine cabinets or toxin cabinets.
I didn't report earlier, as I assumed it was related to the storage-inside-storage bug.)

![image](https://user-images.githubusercontent.com/8194066/198823353-4b7b9669-0c24-44af-a9f8-52b1db168c43.png)

### Reproduction steps

1. Open editor
2. place 'medicine cabinet'
3. open medicine cabinet interface
4. try to put in a 'storage container'

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by AndyPuettmann** [comment] 2022-10-29 09:12
Side note:
It may be an intended change, but seeing the medicine cabinet is the standard linked storage for a medical fabricator, it will most likely limit the storage capabilities for most submarines - or even result in more normal cabinets being used and fading out the use of this specific cabinet on submarines.

**Comment by Regalis11** [comment] 2022-10-29 14:56
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10028

**Closed by Regalis11** 2022-10-29 14:56 UTC

**Comment by AndyPuettmann** [comment] 2022-10-30 19:11
Oh, I really need to also search for closed issues.
