### ISSUE TITLE
Two things

### ISSUE THREAD

**Issue by Snootleboops** [Regalis11/Barotrauma#10416] opened 2022-11-16 03:29 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

If too many treshers enter the submarine too quickly it crashes the game also the buff on creatures is absolute cancer, I got killed by 2 mudraptors in literally 5 seconds with armor that has 10% more damage resist then the exo sui, explain to me how the fuck I'm supposed to clear a nest of those fucks if they kill me before I get the chance to do shit

### Reproduction steps

Was already clear enough

### Bug prevalence

Happens every now and then

### Version

0.20.6.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-11-16 08:04
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10249

**Closed by Regalis11** 2022-11-16 08:04 UTC
