### ISSUE TITLE
[0.9.7.1] Switch not synchronized in multiplayer

### ISSUE THREAD

**Issue by Brain512** [Regalis11/Barotrauma#2427] opened 2020-03-12 17:59 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When a switch has its "isToggle" flag cleared pressing it will not get synchronized in multiplayer.

**Steps To Reproduce**
Place switch, place emergency light. Wire switch output to emergency light's toggle state. Clear "isToggle" flag from switch. Launch multiplayer with at least one other player. Press switch. Emergency light toggles its state for the player pressing the switch but not for the observing second player.

**Version**
0.9.7.1 Windows 10

**Additional information**
none

**Comment by Regalis11** [comment] 2020-03-12 19:19
Duplicate of #1821

**Closed by Regalis11** 2020-03-12 19:19 UTC
