### ISSUE TITLE
Items on Bandits at Beacon Stations are marked as stolen

### ISSUE THREAD

**Issue by SmugFruit** [Regalis11/Barotrauma#10200] opened 2022-10-31 15:23 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

During the campaign I depart from a station into a passageway with a deactivated beacon station.

The beacon station is inhabited by bandits yet everything on the bandits bodies are marked as stealing.

Upon returning to the station I had initially embarked from into the beacon station passage on a round trip, the items are marked as stolen for that outpost, despite originally coming from the beacon station bandits.

### Reproduction steps

1.start a campaign
2.head to a beacon station passageway
3.confirm it is a bandit variant
4.kill bandits inside 
5.observe loot and equipment on bandits is marked as stolen
6.additionally return to station after mission complete to observe items looted from those bandits are marked as stolen and cannot be sold.

### Bug prevalence

Happens every now and then

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-11-01 17:05
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6734d6693ef42bb89b5332bd7abaed80417db59b

**Comment by Rehexr** [comment] 2022-11-21 18:08
This isnt fixed in the current build, should probably need another fix

**Comment by Rokvach** [comment] 2022-11-23 13:01
Moving to Team1

**Comment by Regalis11** [comment] 2022-11-23 14:42
Couldn't reproduce. Did this happen with items you've stolen previously in the save?

**Comment by Regalis11** [comment] 2022-11-27 11:25
No known steps to repro, closing

**Closed by Regalis11** 2022-11-27 11:25 UTC
Labels: Bug, Need more info, Code, Unstable
