### ISSUE TITLE
Fix suggestion for Vertical Oscilation of submarines

### ISSUE THREAD

**Issue by faurana** [Regalis11/Barotrauma#5058] opened 2021-02-14 00:28 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.
https://github.com/Regalis11/Barotrauma/issues/4857 

**Description**
The Autopilot continually overshoots it's target destination while traveling in the vertical axis, which is caused by the mismatch of the range between the pump input (-50 to +50)and the Navigation terminal output (-100 to +100, not considering offets).

**Steps To Reproduce**
set any submarine to autopilot
tell it to mover above or below
watch oscilation

**Version**
0.12.0.2

**Additional information**
through some testing I concluded that using a 2nd order polynomial function to map the Navigation terminal output to the Pump target level input would allow me to have the offset neutral balast while maintaining full range access to the ballast levels. in testing it turns out this also completely eliminates the oscilations of the submarine.

while solving the polinomial for every possible range sounds intimidating at first, implementing this as a fixed aspect of the navigation terminal simplifies the math drastically, since the minimum and maximum navigation terminal as well as pump levels are already known, as well as the neutral nav terminal output. the effective only open variable is which point the neutral balast level, which the player inputs into the terminal.

with all that considered, solving a 2nd order polinomial ax²+bx+c= y 
P1(-100|-50) ---------------------->  10^4*a-100b+c=-50
P2(0| [neutral balast level] -0.5 ) ->       0a +0b +c = [neutral balast level]- 50
P3(100|50) ------------------------ >  10^4*a+100b+c= 50

simplifies into 
a = [0.5-(neutral balast level)]/100
b=0.5
c =  [(neutral balast level)-0.5]*100

which for a balast tank of 0.5 turns into a linear function, and for everything else forms a smooth transition acros the range of values, mostly mimicing the response behavior of the engine

the Linked videos demonstrate the lack of oscilation with such a system implemented throughout in-game logic components
https://youtu.be/vtIrnoQqFX4
https://youtu.be/_eI8ouJoxYo

as well as the sub file with labeled memory components
[Stinger v2 Balast Demo.zip](https://github.com/Regalis11/Barotrauma/files/5976749/Stinger.v2.Balast.Demo.zip)

**Comment by Regalis11** [comment] 2021-02-14 12:39
Duplicate of https://github.com/Regalis11/Barotrauma/issues/4578

**Closed by Regalis11** 2021-02-14 12:39 UTC
