### ISSUE TITLE
Can't use Bindkey for commands that needs seperation, spaces, and quotation?

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4894] opened 2021-01-25 14:04 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
For instance, using the follow command only binds setclientcharacter into the key but not the rest of it:

Bindkey Numpad0 setclientcharacter "Kaileris" "Kaileris"

Looking into config_player, even if I wanted to customize the bind a bit more, I can't use quotations for when there's a spacebar needed.

Keybind
      key="NumPad0"
      command="setclientcharacter"

**Version**
0.12.0.0

**Comment by 3e849f2e5c** [comment] 2021-01-26 10:20
You can wrap the entire command in quotes like `bindkey Numpad0 "setclientcharacter Kaileris Kaileris"`, I don't think there's a way to have nested quotes in the debug console but you could open up the config_player.xml for now and in the command write 
```XML
<Keybind
key="NumPad0"
command="setclientcharacter &quot;Kaileris&quot; &quot;Kaileris&quot;" />
```
Since `&quot;` gets translated to a `"` in XML

**Comment by Kaillera** [comment] 2021-01-27 21:46
Funny enough if you type

bindkey NumPad1 "setclientcharacter &quot;Kaileris&quot; &quot;Michele Gregory&quot;"

you get

```
    <Keybind
      key="NumPad1"
      command="setclientcharacter &amp;quot;Kaileris&amp;quot; &amp;quot;Michele Gregory&amp;quot;" />
```

**Comment by Regalis11** [comment] 2023-03-10 10:45
We're cleaning up some low-prio/unreproducible/irrelevant/outdated tickets from the issue tracker, and this is one of the tickets we chose to axe. This is possible to work around as described above. Closing.

**Closed by Regalis11** 2023-03-10 10:45 UTC
Labels: Bug, Code, Low prio
