### ISSUE TITLE
Game barely uses computer resources.

### ISSUE THREAD

**Issue by Skittlq** [Regalis11/Barotrauma#10696] opened 2022-12-12 10:38 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

My friend recently bought me this game, but I have noticed that the performance is really, REALLY bad, after looking through task manager, I found out that the game, and only THIS game is using nearly none of my CPU or GPU.

Currently it's using 1-15% of my CPU and only 2-25% of my GPU, giving me an average framerate of 10-20 FPS.

My laptop is running an AMD Ryzen 5 3550H and a GTX 1050 with 16GB of 2400 MHz DDR4 RAM.

I am 100% sure that the game isn't running off of my integrated graphics and even though my laptop specs aren't the best, it should definitely be able to run this.

### Reproduction steps

You can reproduce this by using my computer.

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-12-12 11:57
Thank you for the report!

A lot of the most performance-intensive parts of the game (physics, item updates) run in a single thread, so single-core performance tends to be the biggest bottleneck in running it - and AMD Ryzen 5 3550H is a relatively weak mobile processor that just barely meets the game's minimum system requirements. Regardless, an FPS as low as 10-20 sounds unusually low, so I think there is a lot more optimization work to be done. 

Closing as a duplicate of https://github.com/Regalis11/Barotrauma/issues/9396

**Closed by Regalis11** 2022-12-12 11:57 UTC
