### ISSUE TITLE
Character's appearance changes when saving and reloading

### ISSUE THREAD

**Issue by Konayper** [Regalis11/Barotrauma#3564] opened 2020-08-14 18:07 UTC
При игре в одиночную компанию возникает ошибка главного персонажа то есть капитана подлодки. При загрузке сохранения меняется его внешность если выйти и загрузить заново то она снова поменяется на прежнюю внешность и так каждый раз.

**Comment by rico6822** [comment] 2020-08-15 10:05
Translation:

**Change of appearance**

When playing in a singleplayer campaign, an error occurs of the main character, that is, the captain of the submarine. When loading a save, its appearance changes if you exit and reload it, then it will again change to its previous appearance and so every time.

This text is in Russian. I think Konayper trying to tell us that the captain keeps changing appearance every time the game is saved by quitting. It seems to keep switching between the last ones used according to him that are not the current ones used.

**Comment by Regalis11** [comment] 2020-08-20 08:14
Duplicate of #3522

**Closed by Regalis11** 2020-08-20 08:14 UTC
Labels: Bug, Code
