### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by JusticeWolfLeo** [Regalis11/Barotrauma#11684] opened 2023-03-28 01:35 UTC
Crash while trying to load campaign (or tutuorial, I tried).
[crashreport (3).log](https://github.com/Regalis11/Barotrauma/files/11084358/crashreport.3.log)

**Comment by JusticeWolfLeo** [comment] 2023-03-28 01:36
I updated drivers. Updated directx12, 11, idk what else to do.

**Comment by itchyOwl** [comment] 2023-03-28 14:32
Thanks for the report!

The crash log says that:

> The crash was caused by the DirectX error DeviceReset (HRESULT = 0x887A0007). This is a common DirectX error that can be related to various different issues, such as outdated drivers, RAM problems or an overclocked or otherwise overstressed GPU. There are several potential ways to fix the issue: ensuring your graphics drivers and DirectX installation are up-to-date, disabling overclocking and adjusting various GPU-specific settings. You may also be able to find potential solutions to the problem by using the error code DeviceReset (HRESULT = 0x887A0007) and your GPU manufacturer as search terms.

So it's most likely an issue with the hardware/drivers, and there's not much that we can do to help you. I'll keep the ticket open for now though.

**Comment by Regalis11** [comment] 2023-03-28 16:21
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10540

**Closed by Regalis11** 2023-03-28 16:21 UTC
Labels: wontfix, Crash
