### ISSUE TITLE
Server crash when someone turns into a humanhusk

### ISSUE THREAD

**Issue by mcbanekenney** [Regalis11/Barotrauma#9451] opened 2022-06-23 01:57 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Someone had been injected with husk eggs earlier, we apprehended the doctor and the person turned while we were away and talking about something else, crashing the server mid-sentence.

### Reproduction steps

1. Load into multiplayer game
2. Infect someone with husk eggs
3. After they turn, game should crash
No mods were installed that override humanhusk to my knowledge.

### Bug prevalence

Happens every now and then

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Object reference not set to an instance of an object.
Message length: 3304 (413 bytes)
Read position: 2760
Header: ENTITY_POSITION
Previous header: ENTITY_POSITION
Previous object was 192 bits long (24 bytes)
 
   at Barotrauma.Character.ClientReadPosition(IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\CharacterNetworking.cs:line 172
   at Barotrauma.Networking.GameClient.ReadIngameUpdate(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2300
 
 - Human
 - Human
 - Human
 - Human
 - Human
 - Human
 - Human
 - Human
 - Human
 - Human
 - Human
 - Humanhusk
Last console messages:
[6/22/2022 8:53:13 PM] Coroutine Barotrauma.Inventory+<SyncItemsAfterDelay>d__89 threw an exception: Object reference not set to an instance of an object.
   at Barotrauma.Items.Components.Wearable.Equip(Character character) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Wearable.cs:line 417
   at Barotrauma.Item.Equip(Character character) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 2759
   at Barotrauma.CharacterInventory.TryPutItem(Item item, Character user, IEnumerable`1 allowedSlots, Boolean createNetworkEvent, Boolean ignoreCondition) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\CharacterInventory.cs:line 389
   at Barotrauma.CharacterInventory.TryPutItem(Item item, Int32 index, Boolean allowSwapping, Boolean allowCombine, Character user, Boolean createNetworkEvent, Boolean ignoreCondition) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\CharacterInventory.cs:line 488
   at Barotrauma.Inventory.ApplyReceivedState() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Inventory.cs:line 1877
   at Barotrauma.Inventory.SyncItemsAfterDelay(UInt16 lastEventID)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Inventory.cs:line 1850
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 197
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 255
[6/22/2022 8:53:13 PM] Failed to read event 10052 for entity "EntitySpawner", id 65535  {[RagdollParams] Failed to load ragdoll Humanhusk Default Ragdoll from Content/Characters/Humanhusk/Ragdolls/HumanhuskDefaultRagdoll.xml for the character Humanhusk.}
   at Barotrauma.RagdollParams.GetRagdollParams[T](Identifier speciesName, String fileName) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Params\Ragdoll\RagdollParams.cs:line 190
   at Barotrauma.Character..ctor(CharacterPrefab prefab, Vector2 position, String seed, CharacterInfo characterInfo, UInt16 id, Boolean isRemotePlayer, RagdollParams ragdollParams) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 1248
   at Barotrauma.Character.Create(CharacterPrefab prefab, Vector2 position, String seed, CharacterInfo characterInfo, UInt16 id, Boolean isRemotePlayer, Boolean hasAi, Boolean createNetworkEvent, RagdollParams ragdoll) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 1090
   at Barotrauma.Character.Create(Identifier speciesName, Vector2 position, String seed, CharacterInfo characterInfo, UInt16 id, Boolean isRemotePlayer, Boolean hasAi, Boolean createNetworkEvent, RagdollParams ragdoll, Boolean throwErrorIfNotFound) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 1059
   at Barotrauma.Character.ReadSpawnData(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\CharacterNetworking.cs:line 517
   at Barotrauma.EntitySpawner.ClientEventRead(IReadMessage message, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\EntitySpawner.cs:line 65
   at Barotrauma.Networking.ClientEntityEventManager.Read(ServerNetObject type, IReadMessage msg, Single sendingTime, List`1 entities) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\NetEntityEvent\ClientEntityEventManager.cs:line 224
[6/22/2022 8:53:13 PM] Failed to spawn character Humanhusk {[RagdollParams] Failed to load ragdoll Humanhusk Default Ragdoll from Content/Characters/Humanhusk/Ragdolls/HumanhuskDefaultRagdoll.xml for the character Humanhusk.}
   at Barotrauma.RagdollParams.GetRagdollParams[T](Identifier speciesName, String fileName) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Params\Ragdoll\RagdollParams.cs:line 190
   at Barotrauma.Character..ctor(CharacterPrefab prefab, Vector2 position, String seed, CharacterInfo characterInfo, UInt16 id, Boolean isRemotePlayer, RagdollParams ragdollParams) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 1248
   at Barotrauma.Character.Create(CharacterPrefab prefab, Vector2 position, String seed, CharacterInfo characterInfo, UInt16 id, Boolean isRemotePlayer, Boolean hasAi, Boolean createNetworkEvent, RagdollParams ragdoll) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 1090
   at Barotrauma.Character.Create(Identifier speciesName, Vector2 position, String seed, CharacterInfo characterInfo, UInt16 id, Boolean isRemotePlayer, Boolean hasAi, Boolean createNetworkEvent, RagdollParams ragdoll, Boolean throwErrorIfNotFound) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 1059
   at Barotrauma.Character.ReadSpawnData(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\CharacterNetworking.cs:line 517
[6/22/2022 8:53:13 PM] Couldn't load xml document "Content/Characters/Humanhusk/Ragdolls/HumanhuskDefaultRagdoll.xml"! {Could not find a part of the path 'C:\Program Files (x86)\Steam\steamapps\common\Barotrauma\Content\Characters\Humanhusk\Ragdolls\HumanhuskDefaultRagdoll.xml'.}
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Barotrauma.IO.File.Open(String path, FileMode mode, FileAccess access, Nullable`1 share) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SafeIO.cs:line 383
   at Barotrauma.XMLExtensions.TryLoadXml(String filePath, Exception& exception) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Serialization\XMLExtensions.cs:line 110
[6/22/2022 8:53:13 PM] [RagdollParams] Invalid directory: Content/Characters/Humanhusk/Ragdolls/. Using the default ragdoll.
[6/22/2022 8:52:06 PM] Server command: spawnitem Handcuffs inventory
[6/22/2022 8:52:06 PM] spawnitem Handcuffs inventory
[6/22/2022 8:50:44 PM] Server command: spawnitem "Large Military First Aid Kit" inventory
[6/22/2022 8:50:44 PM] spawnitem "Large Military First Aid Kit" inventory
[6/22/2022 8:50:27 PM] Server command: spawnitem "Broad-spectrum Antibiotics" inventory
[6/22/2022 8:50:27 PM] spawnitem "Broad-spectrum Antibiotics" inventory
[6/22/2022 8:50:27 PM] Server command: spawnitem "Broad-spectrum Antibiotics" inventory
[6/22/2022 8:50:27 PM] spawnitem "Broad-spectrum Antibiotics" inventory
[6/22/2022 8:50:24 PM] Server command: spawnitem "Broad-spectrum Antibiotics" inventory
[6/22/2022 8:50:24 PM] spawnitem "Broad-spectrum Antibiotics" inventory
[6/22/2022 8:50:18 PM] Server command: spawnitem "Atropine Auto-Injector" inventory
[6/22/2022 8:50:18 PM] spawnitem "Atropine Auto-Injector" inventory
[6/22/2022 8:48:50 PM] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/mcban/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2764968387/Jobgear/renegadeplatecarrier.png, size: 683x264)
[6/22/2022 8:48:42 PM] Server command: heal "an epic noob"
```

**Comment by Regalis11** [comment] 2022-06-23 14:32
I'm afraid I could not reproduce this without mods, so I do suspect this was caused by one of the mods you have installed (possibly related to https://github.com/Regalis11/Barotrauma/issues/9411?).

And did the game actually crash to desktop or were you just kicked to the lobby / main menu?

**Comment by mcbanekenney** [comment] 2022-06-25 05:03
It went back to the main menu and produced the error. I'm not sure which mod could have caused this error since I only had 3 enabled at the time. 2 were made by me and add custom infections without overriding anything related to the vanilla husk or its infection, while the other was Enhanced Armaments. Could it be potentially caused by mods that I have installed but not enabled?

**Comment by Regalis11** [comment] 2022-11-08 15:30
No known steps to repro, closing

**Closed by Regalis11** 2022-11-08 15:30 UTC
Labels: Bug, Need more info, Code, Networking
