### ISSUE TITLE
Server doesn't generate a crash report if it runs out of memory, it does tell that it did generate one

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#4804] opened 2021-01-18 09:19 UTC
Encountered this whilst testing how many subs I can have installed and still play the game, I had 1000 subs installed and tried to host a server the server process just crashes at the start and didn't generate a crash report.

Repro steps:
1. Duplicate vanilla subs until you hit 1000 subs (Might differ based on how much memory you have)
2. Try and host a server
3. Server should crash right at the start before even entering the loading screen. Tells that a crash report was generated, but none can be found.

**Comment by someone972** [comment] 2021-01-18 23:02
Triaged this on my local system. Looks like it doesn't write a crash report because the process is getting killed by the client due to a read timeout. As a test, I changed the timespan miliseconds in ChildServerRelay::ReadIncomingMsgs from 100 to 1000 and verified that the server was able to start. Maybe there needs to be better logging in ChildServerRelay to log why it's shutting down the process, and maybe a better message to the user when this happens?

**Comment by Regalis11** [comment] 2021-06-08 14:14
I'm afraid I couldn't reproduce this: the server doesn't seem to crash, the process just gets killed by the client when ReadIncomingMsgs times out as someone972 pointed out. Even though that's something we should address, the problem isn't that the server doesn't generate a crash report, but the timing out. We have a never ticket about the issue so I'll close this one. https://github.com/Regalis11/Barotrauma/issues/5872

**Closed by Regalis11** 2021-06-08 14:14 UTC
Labels: Bug, Crash, Medium Prio
