### ISSUE TITLE
Game crash on round start (Multiplayer Combat mission)

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#284] opened 2018-02-25 19:28 UTC
Version 0.8.0.4 (Vanilla)

![image](http://puu.sh/zvvfd/cb528994f9.jpg)

I joined a second server after playing about 1-2 rounds on one, the server I joined appeared to have started  a combat mission which immediately crashed the moment i saw the popup for the following crash report:

Game version 0.8.0.4
Graphics mode: 1920x1080 (BorderlessWindowed)
Selected content package: Vanilla 0.8
Level seed: 91tmMd8J
Loaded submarine: Nehalennia (4017DD7177A4555445583C3CFDBE5A54)
Selected screen: Barotrauma.GameScreen
Client (Round had started)

System info:
    Operating system: Microsoft Windows NT 6.1.7601 Service Pack 1 64 bit
    GPU name: NVIDIA GeForce GTX 970
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object.
Target site: Void DisplaceCharacters(Microsoft.Xna.Framework.Vector2)
Stack trace: 
   at Barotrauma.SubmarineBody.DisplaceCharacters(Vector2 subTranslation) in E:\Barotrauma\Barotrauma\BarotraumaShared\Source\Map\SubmarineBody.cs:line 288
   at Barotrauma.SubmarineBody.Update(Single deltaTime) in E:\Barotrauma\Barotrauma\BarotraumaShared\Source\Map\SubmarineBody.cs:line 218
   at Barotrauma.Submarine.Update(Single deltaTime) in E:\Barotrauma\Barotrauma\BarotraumaShared\Source\Map\Submarine.cs:line 785
   at Barotrauma.GameScreen.Update(Double deltaTime) in E:\Barotrauma\Barotrauma\BarotraumaShared\Source\Screens\GameScreen.cs:line 129
   at Barotrauma.GameMain.Update(GameTime gameTime) in E:\Barotrauma\Barotrauma\BarotraumaClient\Source\GameMain.cs:line 414
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at MonoGame.Framework.WinFormsGameWindow.RunLoop()
   at MonoGame.Framework.WinFormsGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Barotrauma.Program.Main() in E:\Barotrauma\Barotrauma\BarotraumaClient\Source\Program.cs:line 41

Last debug messages:
   25/02/2018 19:21:37 - READING CHARACTER SPAWN DATA

**Comment by Regalis11** [comment] 2018-02-26 12:03
Seems to be caused by the Limbs-field being null (the same problem as #278)

**Comment by Regalis11** [comment] 2018-02-27 15:17
Closing this, as it appears to be the same one as #278

**Closed by Regalis11** 2018-02-27 15:17 UTC
Labels: bug
