### ISSUE TITLE
'Fight intruder' in abandoned outpost causes bots invade the outpost

### ISSUE THREAD

**Issue by Testingforfree** [Regalis11/Barotrauma#7750] opened 2021-12-13 14:10 UTC
Ordering a bot to 'fight intruder' in an outpost will cause it to leave the submarine an attack any hostile entities.

In an outpost it will run towards and attack new husks.

In an abandoned outpost, it will go rambo and attempt to kill all the bandits in the map.

Unsure if bug or as per design, but I expected 'fight intruder' to be limited to the sub. In the abandoned outpost, I am the intruder.

v0.15.13.0 
Windows

**Comment by Kaillera** [comment] 2021-12-14 01:30
I personally would like it if the bots don't immediately go from the sub to abandoned outpost with the Fight Intruders order.

**Comment by Cusuno** [comment] 2021-12-14 02:47
It is actually intended and was added soon after abandoned outposts were a thing from what I've seen in the past updates.
The purpose for this was to make guard bots more worthwhile to use, and give them a more unique task.

However, you're right. The "Fight Intruder" order doesn't make sense when you're infiltrating an abandoned outpost. While I appreciate the dev's attempts to incorporate this feature, I'd much rather prefer if this behavior was added for an alternate combat order.
Already lost too many guard bots because I forgot to dismiss them from the "Fight Intruder" order after loading in,

**Comment by Regalis11** [comment] 2021-12-14 09:48
Yep, this was actually intentional: the idea was to reuse that order as a way to get the bots to aid you in e.g. abandoned outposts. It is definitely misleading though and it's way too easy to make the bots accidentally attack the outpost, so it's something we should address.

**Comment by itchyOwl** [comment] 2022-01-04 07:49
Let's make it a separate contextual order instead.

**Comment by itchyOwl** [comment] 2022-01-04 08:09
Actually I think we might be able to tackle the issue without adding a new order: I tested disabling the invasion behavior, but accidentally implemented it so that the bots only target the enemies in an outpost when they too are inside the outpost. And I think it might work: the bots won't autonomously go invading outposts, but if you'll take them with you to an outpost and give the fight intruders order, they'll fight the enemies inside that sub instead of the main sub.

Implemented in Regalis11/Barotrauma-development@62c6b03. Let me know if it's still confusing.

**Comment by itchyOwl** [comment] 2022-01-04 08:11
If we make it another separate order, it should be available only when the sub is connected to an enemy sub.

**Comment by Regalis11** [comment] 2023-03-06 08:07
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bbf517d17993f6c7aada3dc126476f3fa1f5ea3d. Seems to have been caused by the changes done to address https://github.com/regalis11/barotrauma/issues/6044. Note for testing: make sure that issue didn't get reintroduced.

**Comment by Rokvach** [comment] 2023-04-14 10:35
Tested, working correctly. Closing.

**Closed by Rokvach** 2023-04-14 10:35 UTC
Labels: Bug, Code, Severe
