### ISSUE TITLE
Pump in/out  settings are not saved from editor

### ISSUE THREAD

**Issue by Psyduckdeluxe** [Regalis11/Barotrauma#10734] opened 2022-12-16 13:06 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Game will no longer save settings made to pumps in/out (pumping speed)  from editor to play mode.

### Reproduction steps

place pump in editor manual set it to -100.

Open test mode and pump will still be set to 0

### Bug prevalence

Happens every time I play

### Version

0.20.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-12-18 11:34
Thank you for the report!

I unfortunately could not find a way to reproduce this. The pump seems to retain the pumping speed set in the editor:

https://user-images.githubusercontent.com/14351070/208296052-8539e606-e7a4-4c05-aab1-e74016342bc1.mp4

Are you sure the pump isn't being controlled by some circuit? And you're not using any mods that might modify the pumps in some way?

**Comment by Psyduckdeluxe** [comment] 2022-12-19 10:30
Honestly i dont know i gave up trying to report anything here. i can still reproduce all these bugs and so can several people in sub builders discord.

**Comment by Regalis11** [comment] 2022-12-19 11:52
I don't doubt there is some kind of a bug here, it's just that I wasn't able to get it to happen at my end - so I must be doing something differently than you. If this is a problem that many people have run into in the sub builders Discord, I think it'd be even more important to fix. In any case, I appreciate the reports and hope we can fix the issue even if you can't think of any other possibly clues that might help us reproduce it!

**Comment by Regalis11** [comment] 2023-01-02 08:44
No known steps to repro (and based on an earlier Discord conversation, Psyduckdeluxe was also unable to reproduce the issue again). Closing

**Closed by Regalis11** 2023-01-02 08:44 UTC
Labels: Bug, Need more info, Code
