### ISSUE TITLE
"damagedbymeleeweapons" doesn't do anything?

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9527] opened 2022-07-04 14:26 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Some items like the Guardian Pod have the "damagedbymeleeweapons" property, but can't get hit by melee weapons

`<Item identifier="guardianpod" description="" texturescale="0.5,0.5" scale="0.5" category="Alien" Tags="alien,guardianshelter" damagedbyexplosions="true" damagedbyprojectiles="true" damagedbyrepairtools="true" damagedbymeleeweapons="true" health="500">
`

Same goes for Piezo Crystals

### Version

0.18.12.0

**Comment by Regalis11** [comment] 2022-07-04 14:54
Duplicate of https://github.com/Regalis11/Barotrauma/issues/9378

**Closed by Regalis11** 2022-07-04 14:54 UTC
