### ISSUE TITLE
Game Crash on Mechanic tutorial (1-st)

### ISSUE THREAD

**Issue by Athetos421** [Regalis11/Barotrauma#2716] opened 2020-04-26 15:47 UTC
It's happened 3 times already. I started up the Mechanic Tutorial, but as soon as I progress far enough to enter the sub, and walk a few spaces past the hatch (i also opened the locker if that changes anything), the game crashes with the following error code:

"Barotrauma Client crash report (generated on 26.04.2020 18:45:19)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

B88397013C2378C4A99C3E19DEBEE54F

Game version 0.9.9.0 (ReleaseWindows, branch release, revision 0534150c8)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Selected content packages: Vanilla 0.9
Level seed: nLoZLLtza
Loaded submarine: Dugong_Tutorial (E327F30A352B4F0D1A97A7F95059767F)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.18362.0 64 bit
    GPU name: Intel(R) HD Graphics 620
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,7777778}
    GPU status: Normal

Exception: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.
 (SharpDX.SharpDXException)
Device removed reason: HRESULT = 0x887A0006
Target site: Void CheckError()
Stack trace: 
   at SharpDX.Result.CheckError()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent()
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Barotrauma.Program.Main(String[] args)

Last debug messages:
[26.04.2020 18:41:22] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[26.04.2020 18:41:22] Content package load order: Vanilla 0.9
[26.04.2020 18:41:21] Content package load order: Vanilla 0.9
[26.04.2020 18:41:18] Attempting to open ALC device "OpenAL Soft"
[26.04.2020 18:41:17] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[26.04.2020 18:41:16] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[26.04.2020 18:41:15] Logged in as Athetos421 (SteamID STEAM_1:0:451835838)"

**Comment by Regalis11** [comment] 2020-04-26 17:49
Duplicate of #1833

**Closed by Regalis11** 2020-04-26 17:49 UTC
