### ISSUE TITLE
Mac user crashing over and over again

### ISSUE THREAD

**Issue by LightShade0** [Regalis11/Barotrauma#5017] opened 2021-02-09 11:53 UTC
**Description**
Me and my friends (about like 13 people) was playing the game with the in game voice chat, and me and my other friends who play on Mac platform crashes over and over again when the game starts.

**Steps To Reproduce**
It doesn't require any steps, the game will load and it will crash regardless. Even if I manage to reconnect I crash almost right away after trying to repair something.
**Version**
v0.11.0.10 Mac

Crash Report:

Exception: Failed to create OpenAL buffer for non-streamed sound: Invalid value (System.Exception)
Target site: Void InitializeALBuffers()
Stack trace: 
   at Barotrauma.Sounds.Sound.InitializeALBuffers() in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Sounds/Sound.cs:line 172
   at Barotrauma.Sounds.OggSound.InitializeALBuffers() in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Sounds/OggSound.cs:line 61
   at Barotrauma.Sounds.SoundManager.LoadSound(String filename, Boolean stream) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Sounds/SoundManager.cs:line 349
   at Barotrauma.Submarine.LoadRoundSound(XElement element, Boolean stream) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Map/Submarine.cs:line 133
   at Barotrauma.StatusEffect.InitProjSpecific(XElement element, String parentDebugName) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/StatusEffects/StatusEffect.cs:line 38
   at Barotrauma.StatusEffect..ctor(XElement element, String parentDebugName) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/StatusEffects/StatusEffect.cs:line 535
   at Barotrauma.StatusEffect.Load(XElement element, String parentDebugName) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/StatusEffects/StatusEffect.cs:line 272
   at Barotrauma.AfflictionPrefab.PeriodicEffect..ctor(XElement element, String parentDebugName) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Health/Afflictions/AfflictionPrefab.cs:line 200
   at Barotrauma.AfflictionPrefab..ctor(XElement element, String filePath, Type type) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Health/Afflictions/AfflictionPrefab.cs:line 587
   at Barotrauma.AfflictionPrefab.LoadFromFile(ContentFile file) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Health/Afflictions/AfflictionPrefab.cs:line 461
   at Barotrauma.AfflictionPrefab.LoadAll(IEnumerable`1 files) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Health/Afflictions/AfflictionPrefab.cs:line 344
   at Barotrauma.GameSettings.RefreshContentPackageItems(IEnumerable`1 files) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameSettings.cs:line 585
   at Barotrauma.GameSettings.SwapPackages(ContentPackage corePackage, List`1 regularPackages) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameSettings.cs:line 388
   at Barotrauma.GameSettings.RestoreBackupPackages() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameSettings.cs:line 398
   at Barotrauma.Networking.GameClient.OnDisconnect(Boolean disableReconnect) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Networking/GameClient.cs:line 1015
   at Barotrauma.Networking.SteamP2PClientPeer.Close(String msg, Boolean disableReconnect) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Networking/Primitives/Peers/SteamP2PClientPeer.cs:line 370
   at Barotrauma.Networking.GameClient.Disconnect() in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Networking/GameClient.cs:line 2587
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Networking/GameClient.cs:line 629
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 951
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/SDL/SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 59

Last debug messages:
[2/10/2021 3:18:46 AM] Error while reading a message from server. {Failed to generate stream buffers: SoundChannel (VoIP (Trumpster)), Invalid value}
   at Barotrauma.Sounds.SoundChannel..ctor(Sound sound, Single gain, Nullable`1 position, Single freqMult, Single near, Single far, String category, Boolean muffle) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Sounds/SoundChannel.cs:line 543
   at Barotrauma.Sounds.VoipSound..ctor(String name, SoundManager owner, VoipQueue q) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Sounds/VoipSound.cs:line 78
   at Barotrauma.Networking.VoipClient.Read(IReadMessage msg)
   at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Networking/GameClient.cs:line 768
   at Barotrauma.Networking.SteamP2PClientPeer.Update(Single deltaTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Networking/Primitives/Peers/SteamP2PClientPeer.cs:line 242
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Networking/GameClient.cs:line 614
[2/10/2021 3:18:45 AM] Fox Flyer
[2/10/2021 3:18:45 AM] Benjaminbash
[2/10/2021 3:18:45 AM] voorhis_dad
[2/10/2021 3:18:45 AM] Babu Selassie
[2/10/2021 3:18:45 AM] Direamic
[2/10/2021 3:18:45 AM] Trumpster
[2/10/2021 3:18:45 AM] joshualwood
[2/10/2021 3:18:42 AM] Fox Flyer
[2/10/2021 3:18:42 AM] Benjaminbash
[2/10/2021 3:18:42 AM] voorhis_dad
[2/10/2021 3:18:42 AM] Babu Selassie
[2/10/2021 3:18:41 AM] Direamic
[2/10/2021 3:18:41 AM] Trumpster
[2/10/2021 3:18:41 AM] joshualwood
[2/10/2021 3:18:41 AM] Failed to read event for entity "Stun Baton"! {Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')}
   at Barotrauma.Item.ClientRead(ServerNetObject type, IReadMessage msg, Single sendingTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Items/Item.cs:line 1133
   at Barotrauma.Networking.ClientEntityEventManager.Read(ServerNetObject type, IReadMessage msg, Single sendingTime, List`1 entities) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Networking/NetEntityEvent/ClientEntityEventManager.cs:line 239
[2/10/2021 3:18:41 AM] Error while loading entity of the type Barotrauma.Items.Components.MeleeWeapon. {Failed to create OpenAL buffer for non-streamed sound: Invalid value}
   at Barotrauma.Sounds.Sound.InitializeALBuffers() in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Sounds/Sound.cs:line 172
   at Barotrauma.Sounds.OggSound.InitializeALBuffers() in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Sounds/OggSound.cs:line 61
   at Barotrauma.Sounds.SoundManager.LoadSound(String filename, Boolean stream) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Sounds/SoundManager.cs:line 349
   at Barotrauma.Submarine.LoadRoundSound(XElement element, Boolean stream) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Map/Submarine.cs:line 133
   at Barotrauma.StatusEffect.InitProjSpecific(XElement element, String parentDebugName) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/StatusEffects/StatusEffect.cs:line 38
   at Barotrauma.StatusEffect..ctor(XElement element, String parentDebugName) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/StatusEffects/StatusEffect.cs:line 535
   at Barotrauma.StatusEffect.Load(XElement element, String parentDebugName) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/StatusEffects/StatusEffect.cs:line 272
   at Barotrauma.Items.Components.ItemComponent..ctor(Item item, XElement element) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Items/Components/ItemComponent.cs:line 309
   at Barotrauma.Items.Components.Pickable..ctor(Item item, XElement element) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Holdable/Pickable.cs:line 41
   at Barotrauma.Items.Components.Holdable..ctor(Item item, XElement element) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Holdable/Holdable.cs:line 139
   at Barotrauma.Items.Components.MeleeWeapon..ctor(Item item, XElement element) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Holdable/MeleeWeapon.cs:line 56
[2/10/2021 3:18:36 AM] Task count: 0
[2/10/2021 3:18:29 AM] Generating an outpost for the end of the level... (Location: Glaukos Linea Research Facility, level type: LocationConnection)
[2/10/2021 3:17:34 AM] LobbyMatchList:  LobbiesMatching: 50
[2/10/2021 3:17:34 AM] LobbyMatchList:  LobbiesMatching: 50
[2/10/2021 3:17:34 AM] SteamAPICallCompleted:   AsyncCall: 15559062354387747726
   Callback: 510
 ParamCount: 4
[2/10/2021 3:17:01 AM] (Msg) SDR RelayNetworkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[2/10/2021 3:17:01 AM] (Msg) Ping location: syd=51+5,sgp=115+11/116+11,hkg=156+15/145+11,maa=279+27/149+11,bom=305+30/165+11,dxb=417+41/192+11,tyo1=210+21/195+11,tyo=223+22/195+11,lax=198+19/199+19,iad=247+24,fra=331+33/333+24,gru=380+38/360+30
[2/10/2021 3:17:01 AM] (Msg) Ping measurement completed
[2/10/2021 3:16:59 AM] (Verbose) Communications with routing cluster 'sto2' established.
[2/10/2021 3:16:59 AM] (Debug) Destroying relay 'sto2#3 (155.133.252.35:27017)' because initial_ping_timeout
[2/10/2021 3:16:56 AM] (Debug) Destroying relay 'sto2#131 (155.133.252.38:27022)' because initial_ping_timeout
[2/10/2021 3:16:54 AM] (Verbose) Communications with routing cluster 'jnb' established.
[2/10/2021 3:16:54 AM] (Verbose) Communications with routing cluster 'mad' established.
[2/10/2021 3:16:54 AM] (Verbose) Communications with routing cluster 'iad' established.
[2/10/2021 3:16:54 AM] (Verbose) Communications with routing cluster 'lim' established.
[2/10/2021 3:16:54 AM] (Verbose) Communications with routing cluster 'waw' established.
[2/10/2021 3:16:54 AM] (Verbose) Communications with routing cluster 'lhr' established.
[2/10/2021 3:16:54 AM] (Verbose) Communications with routing cluster 'par' established.
[2/10/2021 3:16:54 AM] (Verbose) Communications with routing cluster 'scl' established.
[2/10/2021 3:16:54 AM] (Verbose) Communications with routing cluster 'maa' established.
[2/10/2021 3:16:54 AM] (Verbose) Communications with routing cluster 'sof' established.
[2/10/2021 3:16:54 AM] (Verbose) Communications with routing cluster 'sto' established.
[2/10/2021 3:16:54 AM] (Verbose) Communications with routing cluster 'vie' established.
[2/10/2021 3:16:54 AM] (Verbose) Communications with routing cluster 'dxb' established.
[2/10/2021 3:16:54 AM] (Verbose) Communications with routing cluster 'lux' established.
[2/10/2021 3:16:54 AM] (Verbose) Communications with routing cluster 'gru' established.
[2/10/2021 3:16:54 AM] (Verbose) Communications with routing cluster 'ord' established.
[2/10/2021 3:16:54 AM] (Verbose) Communications with routing cluster 'lax' established.
[2/10/2021 3:16:54 AM] (Verbose) Communications with routing cluster 'fra' established.
[2/10/2021 3:16:54 AM] (Verbose) Communications with routing cluster 'eze' established.
[2/10/2021 3:16:54 AM] (Verbose) Communications with routing cluster 'ams' established.
[2/10/2021 3:16:54 AM] (Verbose) Communications with routing cluster 'bom' established.
[2/10/2021 3:16:54 AM] (Verbose) Communications with routing cluster 'sea' established.
[2/10/2021 3:16:54 AM] (Verbose) Communications with routing cluster 'tyo' established.
[2/10/2021 3:16:54 AM] (Verbose) Communications with routing cluster 'tyo1' established.
[2/10/2021 3:16:54 AM] (Verbose) Communications with routing cluster 'atl' established.
[2/10/2021 3:16:54 AM] (Verbose) Communications with routing cluster 'dfw' established.
[2/10/2021 3:16:54 AM] (Verbose) Communications with routing cluster 'eat' established.
[2/10/2021 3:16:53 AM] (Verbose) Communications with routing cluster 'sgp' established.
[2/10/2021 3:16:53 AM] (Verbose) Communications with routing cluster 'hkg' established.
[2/10/2021 3:16:53 AM] (Verbose) Communications with routing cluster 'syd' established.
[2/10/2021 3:16:53 AM] (Msg) SDR RelayNetworkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[2/10/2021 3:16:53 AM] (Msg) Performing ping measurement
[2/10/2021 3:16:53 AM] (Msg) Got SDR network config.  Loaded revision 298 OK
[2/10/2021 3:16:53 AM] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[2/10/2021 3:16:45 AM] Attempting to open ALC device "Taiin's Airpods Pro"
[2/10/2021 3:16:43 AM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[2/10/2021 3:16:43 AM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[2/10/2021 3:16:41 AM] Logged in as LightShade (SteamID STEAM_1:1:212055318)

**Comment by Regalis11** [comment] 2021-02-10 06:56
Duplicate of https://github.com/Regalis11/Barotrauma/issues/4504

**Closed by Regalis11** 2021-02-10 06:56 UTC
