### ISSUE TITLE
Fix light/LOS artifacts

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#231] opened 2018-01-19 16:25 UTC
![lightartifact](https://user-images.githubusercontent.com/14351070/35160404-b351eb10-fd45-11e7-877b-06b5b385ec37.png)

The artifacts are especially noticeable when moving and the LOS artifacts make it possible to see through walls. I think this might be because of the way the penumbra of the light volume has been calculated as of 7a413aee? Still trying to wrap my head around that part of the code, but I the issue might be that it makes the penumbra area rectangular as opposed to triangular (the blue area in the pic vs the green area).

**Comment by juanjp600** [comment] 2018-01-19 17:09
The penumbra is calculated by taking the normal of the lines that connect to each vertex and pushing that vertex in that direction by a certain amount. This results in

**Comment by juanjp600** [comment] 2018-01-19 17:13
Didn't mean to close that , whoops.

**Comment by Regalis11** [comment] 2018-01-22 09:01
![asdfasdg](https://user-images.githubusercontent.com/14351070/35212572-469c7f38-ff63-11e7-9b5c-2d05ddfee16b.png)

Found a more major issue on a specific custom sub, see https://mega.nz/#!bMxBTJjY!aY4XSTVe8AK3pYAiLOsxCi0djO4vEknVMgY7USjMoV0

**Comment by CryIz** [comment] 2018-01-22 09:29
Я думал об этом Вы уже знали. Nehalenia изменил немного и там тоже самое было. Также консоль выдавала ошибки.
I thought You already knew. Nehalenia changed a bit and there was the same. The console gave the error.

**Comment by juanjp600** [comment] 2018-01-22 13:41
I found the cause for the second issue, it's because the wall structures are intersecting so the trimming logic I implemented gets confused. It tries really hard to make the vertices of the light volume match up with the ends of the segments, but since it can't reach either of them in this sub's corners, it just doesn't add a vertex at all. I'll write a fix for that shortly.

**Comment by juanjp600** [comment] 2018-01-22 20:17
https://github.com/Regalis11/Barotrauma/commit/7507d71f53f824285df2d9a873b7086ffe6608d1

Fixed the second issue, the faded light geometry artifacts still remain.

**Comment by Rokvach** [comment] 2019-07-20 23:27
The LOS and lighting has had allot of improvements since this was posted, I don't think there's a need for this to stay open. Closing.

**Closed by Rokvach** 2019-07-20 23:27 UTC
Labels: Bug, Code
