### ISSUE TITLE
I cant play barotrauma on windows 7

### ISSUE THREAD

**Issue by LOLESIN** [Regalis11/Barotrauma#367] opened 2018-04-13 15:06 UTC
[crashreport.txt](https://github.com/Regalis11/Barotrauma/files/1907890/crashreport.txt)
Ive got crash report. FIX THAT

**Comment by MoonEater916** [comment] 2018-04-14 08:57
Works fine for me and many others on windows 7. I think its probably something other than windows 7.

**Comment by HetNeSS** [comment] 2018-04-25 07:24
Win7x64, works fine too

**Comment by Regalis11** [comment] 2018-05-04 13:04
Duplicate of #391. Closing this one because the newer one has more detailed info.

**Closed by Regalis11** 2018-05-04 13:04 UTC
Labels: bug
