### ISSUE TITLE
[1.0] Light Switch glows red when button is green

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11228] opened 2023-02-13 00:17 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When the light switch is turned on, the green light produces a red glow. Images below for reference.

![image](https://user-images.githubusercontent.com/105495756/218345919-bc9b8b5e-93c2-41e9-a771-9e1006e20773.png)
_Figure 1. Light Switch turned off._

![image](https://user-images.githubusercontent.com/105495756/218345922-2fdd9da3-3860-4201-b019-c0a6a0e6c8d6.png)
_Figure 2. Light Switch turned on. Observe the red ring around it._

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-02-13 15:58
Thank you for the report!

I unfortunately could not reproduce this. Did you notice this issue on some specific switch on some submarine? I wonder if it could be an issue with a specific sub (the light color settings of the switch)?
![image](https://user-images.githubusercontent.com/14351070/218507814-71fb0a89-84da-4635-a088-cd85debeebda.png)

**Comment by Jade-Harleyy** [comment] 2023-02-13 16:46
Hello, @Regalis11.
In the image you provided, the bottom two switches have the red ring around the green light as was shown in the orginal bug report.
We believe the intended behavior to be for it to show the green light in the middle, while keeping the rest of the sprite the same grey color, no?

Behavior on stable (v0.21.6.0)
![image](https://user-images.githubusercontent.com/67431770/218518047-8c827caa-711e-4473-a4c8-19cb372adad4.png)

Behavior on faction-testing branch (v1.0.0.0)
![image](https://user-images.githubusercontent.com/67431770/218518951-9487f00f-2de2-454a-a586-d4f96ebc8785.png)

As you can see, the switch on the stable version has no red ring around the green light, however the switch on the faction-testing branch does have a red ring.

**Comment by Regalis11** [comment] 2023-02-13 17:18
You're right, it was just so subtle I couldn't at first notice it on my monitor. I thought the "glow" meant the much brighter area around the button in the original picture.

Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e1a262ac36f2ae48f808f824836da8e752d1830e

**Comment by Rokvach** [comment] 2023-02-14 15:15
Tested, no issues. Closing.

**Closed by Rokvach** 2023-02-14 15:15 UTC
Labels: Bug
