### ISSUE TITLE
Added quests when you reload game

### ISSUE THREAD

**Issue by gabepombo1** [Regalis11/Barotrauma#7760] opened 2021-12-14 11:36 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**

Go to server lobby after accepting quests. Then, enter the game and get quests. Previous quests and new quests will be available to choose from.

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

Latest. Windows 10.

**Additional information**

**Comment by Regalis11** [comment] 2021-12-14 11:56
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3388

**Closed by Regalis11** 2021-12-14 11:56 UTC
