### ISSUE TITLE
[0.9.10.0] HandIK NullReferenceException Server Crash.

### ISSUE THREAD

**Issue by naelstrof** [Regalis11/Barotrauma#3168] opened 2020-06-20 22:34 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
A bug that occasionally crashes our server during gameplay.
```
Barotrauma Dedicated Server crash report (generated on 6/20/2020 7:57:31 PM)


Barotrauma seems to have crashed. Sorry for the inconvenience!


Game version 0.9.10.0 (ReleaseLinux, branch release, revision 2876b0a66)
Language: English
Selected content packages: HumanReplacement, Vanilla 0.9, Shipwrecks Extended, TransparentDivingHelmet, Huskmod, XanMonsters, XanMonsters2, Grim's goodie bag
Level seed: Drumskinny LineaMoytura
Loaded submarine: NS Lumbago (E7947EA504118D0C06289104A51AF332)
Selected screen: Barotrauma.GameScreen
Server (Round had started)


System info:
    Operating system: Unix 4.19.91.1 64 bit


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void HandIK(Barotrauma.Limb, Microsoft.Xna.Framework.Vector2, Single)
Stack trace:
   at Barotrauma.HumanoidAnimController.HandIK(Limb hand, Vector2 pos, Single force) in /home/joonas/Barotrauma/Barotrauma/BarotraumaShared/SharedSource/Characters/Animation/HumanoidAnimController.cs:line 1831
   at Barotrauma.HumanoidAnimController.UpdateDying(Single deltaTime) in /home/joonas/Barotrauma/Barotrauma/BarotraumaShared/SharedSource/Characters/Animation/HumanoidAnimController.cs:line 1277
   at Barotrauma.HumanoidAnimController.UpdateAnim(Single deltaTime) in /home/joonas/Barotrauma/Barotrauma/BarotraumaShared/SharedSource/Characters/Animation/HumanoidAnimController.cs:line 348
   at Barotrauma.Character.UpdateAnimAll(Single deltaTime) in /home/joonas/Barotrauma/Barotrauma/BarotraumaShared/SharedSource/Characters/Character.cs:line 2051
   at Barotrauma.GameScreen.Update(Double deltaTime) in /home/joonas/Barotrauma/Barotrauma/BarotraumaShared/SharedSource/Screens/GameScreen.cs:line 235
   at Barotrauma.GameMain.Run() in /home/joonas/Barotrauma/Barotrauma/BarotraumaServer/ServerSource/GameMain.cs:line 346
   at Barotrauma.Program.Main(String[] args) in /home/joonas/Barotrauma/Barotrauma/BarotraumaServer/ServerSource/Program.cs:line 48


Last debug messages:
   6/20/2020 7:57:31 PM - [6/20/2020 7:57:31 PM]
  Saving banlist
   6/20/2020 7:57:31 PM - [6/20/2020 7:57:31 PM]
  Paralyser attacked by Grim. Lacerations: 15 Bleeding: 1
   6/20/2020 7:57:31 PM - [6/20/2020 7:57:31 PM]
  Paralyser attacked by Grim. Lacerations: 15 Bleeding: 1
   6/20/2020 7:57:31 PM - [6/20/2020 7:57:31 PM]
  Paralyser has died (Cause of death: Lacerations)
   6/20/2020 7:57:31 PM - [6/20/2020 7:57:31 PM]
  Mudraptor attacked by Grim. Lacerations: 15 Bleeding: 1
   6/20/2020 7:57:31 PM - [6/20/2020 7:57:31 PM]
  Grim launched Coilgun (projectile: Piercing Coilgun Bolt)
   6/20/2020 7:57:31 PM - [6/20/2020 7:57:31 PM]
  Paralyser attacked by Grim. Lacerations: 15 Bleeding: 1
   6/20/2020 7:57:31 PM - [6/20/2020 7:57:31 PM]
  Paralyser attacked by Grim. Lacerations: 15 Bleeding: 1
   6/20/2020 7:57:31 PM - [6/20/2020 7:57:31 PM]
  Paralyser attacked by Grim. Lacerations: 15 Bleeding: 1
   6/20/2020 7:57:31 PM - [6/20/2020 7:57:31 PM]
  Grim launched Coilgun (projectile: Piercing Coilgun Bolt)
   6/20/2020 7:57:30 PM - [6/20/2020 7:57:30 PM]
  Paralyser attacked by Grim. Lacerations: 15 Bleeding: 1
   6/20/2020 7:57:30 PM - [6/20/2020 7:57:30 PM]
  Paralyser attacked by Grim. Lacerations: 15 Bleeding: 1
   6/20/2020 7:57:30 PM - [6/20/2020 7:57:30 PM]
  Paralyser attacked by Grim. Lacerations: 15 Bleeding: 1
   6/20/2020 7:57:30 PM - [6/20/2020 7:57:30 PM]
  Grim launched Coilgun (projectile: Piercing Coilgun Bolt)
```

**Steps To Reproduce**
Seems to happen randomly, might be caused by our mods. We play with a few steamworks addons, and some private mods that we made to put our characters in the game. Let me know if you need them.

**Version**
Version 0.9.10.0, Linux Dedicated Server.

**Additional information**

Looking at the source, it seems like a ragdoll might be getting cleaned up as it's trying to update its animation.

**Comment by Regalis11** [comment] 2020-06-22 14:55
I suspect this happened when the dying character's hands/arms hand been severed. Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/3c9a75df, moving to Review/QA.

**Comment by Rokvach** [comment] 2020-06-23 05:30
There's no clear way to reproduce this issue, especially if its caused by a mod. I think its just better to close the ticket for now and re-open if something comes up later. Closing.

**Comment by itchyOwl** [comment] 2020-06-23 09:37
But shouldn't that commit be included in the 0.9.10.0? To reproduce the issue, we'd probably need the custom mods.

**Comment by naelstrof** [comment] 2020-06-23 20:24
Most of the mods can be found in this steam collection here: https://steamcommunity.com/sharedfiles/filedetails/?id=2127575896

The two custom ones can be found attached. 
[Mods.zip](https://github.com/Regalis11/Barotrauma/files/4821735/Mods.zip)

We've been getting the crashes before we started including custom mods, so the steam collection would probably be enough.

**Comment by naelstrof** [comment] 2020-06-23 21:34
I also have a snapshot of all those steamwork mods at the time of crash if needed.

**Comment by Regalis11** [comment] 2020-06-24 08:16
Nvm, reopening. Didn't notice that commit was included in 0.9.10.0, and since this crash report is from 0.9.10.0, it clearly didn't fix the issue.

**Comment by Regalis11** [comment] 2020-07-09 12:03
Added another null check in https://github.com/Regalis11/Barotrauma-development/commit/1d6c2ee2efa526c35fe4bb82928503411142367a, let's see if that helps

**Comment by naelstrof** [comment] 2020-07-09 12:54
Me and some friends have been playing for a few weeks with this commit here: https://github.com/naelstrof/Barotrauma/commit/a668505d944932a8e6113cc2270a4beaa97739a0
And haven't crashed from this error since.

**Comment by Rokvach** [comment] 2020-07-28 09:30
No issues, closing.

**Closed by Rokvach** 2020-07-28 09:30 UTC
Labels: Bug, Code, Crash
