### ISSUE TITLE
[0.10.4.0] EMP'd Battery provides power

### ISSUE THREAD

**Issue by Coryf88** [Regalis11/Barotrauma#3846] opened 2020-09-16 19:09 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Junction boxes still receive power from EMP'd stationary batteries.

**Steps To Reproduce**
1. Have a stationary battery connected to a Junction Box and the Junction Box connected to a power consumer.
2. EMP the stationary battery.
3. Notice the Junction Box is still receiving power and the power consumer is still working.

**Version**
0.10.4.0
Windows

**Additional information**
https://youtu.be/8UBhhysGtEw

**Comment by EtiamNullam** [comment] 2020-09-16 21:19
I can't reproduce that. EMP will drain all the stored energy and destroy the batteries.

How did you cause EMP? Grenade, artifact or grenade in railgun?

**Comment by Coryf88** [comment] 2020-09-16 22:19
EMP Grenade.

**Comment by EtiamNullam** [comment] 2020-09-16 23:39
Oh yea, you're right. I managed to reproduce it with this test bed I made: [battery-emp-test.zip](https://github.com/Regalis11/Barotrauma/files/5235400/battery-emp-test.zip)

**Comment by Regalis11** [comment] 2020-09-17 06:27
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3781, will be fixed in the next patch

**Closed by Regalis11** 2020-09-17 06:27 UTC
