### ISSUE TITLE
Can't add fertilizer

### ISSUE THREAD

**Issue by r-barnes** [Regalis11/Barotrauma#5680] opened 2021-05-02 06:00 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
* I would like to add fertilizer to a small planter box.
* I put the box on the floor.
* I put seeds in the box (this seems to only work intermittently, see below)
* I hold the fertilizer bottle in one hand
* I hover over the box. It says "[Left Mouse] Add Fertilizer"
* I click with the left mouse, but rather than fertilizer being added, my character picks up the planter box. (This same thing seems to happen most of the time when I try to add seeds.)

**Steps To Reproduce**
Seems to happen every time I try.

**Version**
Linux. Barotrauma 0.13.3.11

**Additional information**
N/A

**Comment by Regalis11** [comment] 2021-05-03 10:34
Internal note: might've been caused by https://github.com/Regalis11/Barotrauma-development/commit/9692dbb7b7aafa557172000368e55945f487f6cd

**Comment by r-barnes** [comment] 2021-05-06 06:33
So we figured out that equipping a planter in one hand and using Right-Click displays the placement grid. Once the planter is placed this way it's possible to add water and fertilizer and a plant sprouts. So I think there are potentially two issues here:

1. It's pretty unintuitive that we need to use right-click to place the planter and I don't remember seeing that documented anywhere. Previously we simply dropped the planter with the left mouse button and tried to interact with it.
2. We still can't add seeds to the planter, but a plant (raptor bane) began growing out of it anyway. Perhaps there were already seeds in the planter? If so, we don't see this indicated anywhere.

**Comment by 3e849f2e5c** [comment] 2021-05-19 15:42
Addressed the confusion by fixing #5695 

Issue wasn't about not being able to add fertilizer but the fact that you could drop the planter and plant a seed into it by drag and dropping which caused confusion.

Should this ticket still be kept up? @Rokvach

**Comment by Rokvach** [comment] 2021-05-20 06:13
I don't see the need to keep this open, closing.

**Closed by Rokvach** 2021-05-20 06:13 UTC
Labels: Bug, Code
