### ISSUE TITLE
Outpost generated an alien death box

### ISSUE THREAD

**Issue by MudraptorSeks** [Regalis11/Barotrauma#6905] opened 2021-10-12 17:10 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
There is a part of the alien ruins generated in an outpost. walking to the side will kill you
[https://ibb.co/1d5Wk7s](url)

**Steps To Reproduce**
I just found it in an outpost

**Version**
Windows 10, version 0.1500.6.0 unstable

**Additional information**
I couldn't find a level seed or anything so sorry about that

**Comment by Regalis11** [comment] 2021-10-13 07:18
Duplicate of https://github.com/Regalis11/Barotrauma/issues/6863

**Closed by Regalis11** 2021-10-13 07:18 UTC
