### ISSUE TITLE
permissionpresets.xml not working

### ISSUE THREAD

**Issue by Jav1k** [Regalis11/Barotrauma#6341] opened 2021-07-20 00:26 UTC
whatever is set inside this file has no effect on my dedicated server, neither with giverank nor promoting through the right-click context menu. it is always the vanilla presets, any changes need to be done manually for each person. maybe the file is read locally instead of from the server but i need to test that as i have no remote access to my server's console. i have a suspicion that it reads whatever the clients permissionpresets say.

**Comment by Regalis11** [comment] 2021-07-20 07:48
I'm afraid I could not reproduce this. Tested by doing the following:

1. Add a new permission preset to permissionpresets.xml on the server's end (I just copied the "Moderator" preset and renamed it as "Test")
2. Give the client permission to use the "giverank" command
3. Enter "giverank [client] Test"
4. The client was given the "Test" permissions

**Comment by Jav1k** [comment] 2021-07-22 00:19
![Capture22222](https://user-images.githubusercontent.com/31679325/126575388-4e37a5e1-6e7c-4d16-89c8-1ceb928123d5.JPG)

**Comment by Jlobblet** [comment] 2021-07-22 09:16
It appears your XML is malformed. See here:
![image](https://user-images.githubusercontent.com/37539527/126616152-56ebdb1e-5512-4c16-9cf3-d468126ae836.png)
the `Preset` tag has no closing tag. To close it, you must use `</Preset>`:
![image](https://user-images.githubusercontent.com/37539527/126616222-8d4dcdcd-4405-4f99-b447-a49436f43d9c.png)

**Closed** 2021-07-22 10:47 UTC
Labels: Bug, Code, Need more info, Networking
