### ISSUE TITLE
[0.9.703] Bots cannot climb Berillia's Top Left most ladder

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2184] opened 2020-02-06 21:30 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
A lot of time bots want to climb this ladder to repair this junction box in the Berilia. I think it's due to the lack of waypoints midway.
![](https://user-images.githubusercontent.com/5086682/73980250-da066780-48fd-11ea-9baa-95a00b65382c.PNG)

You may notice a waypoint on the junction that I artificially put there to see if that was an initial problem.

**Version**
0.9.703

**Comment by itchyOwl** [comment] 2020-04-13 09:39
There doesn't have to be a waypoint there. I cannot reproduce this in the latest unstable.

**Comment by Rokvach** [comment] 2020-04-13 17:09
I did a fast test on this using the contextual commands and I noticed that the bots struggles to get to the platform when using the ladder

Video (Ignore the background audio :D) @itchyOwl 
https://streamable.com/4l92oi

**Comment by itchyOwl** [comment] 2020-04-28 19:14
Fixed in Regalis11/Barotrauma-development@abd9f4a

**Comment by Rokvach** [comment] 2020-05-13 11:51
Wasn't able to reproduce it, working correctly. Closing.

**Closed by Rokvach** 2020-05-13 11:51 UTC
Labels: Bug, Code, Needs testing
