### ISSUE TITLE
Ship upgrade menu glitched if there are more than 6 hardpoints.

### ISSUE THREAD

**Issue by NiiloKH** [Regalis11/Barotrauma#9085] opened 2022-05-08 00:02 UTC
Adding guns to sub that has 7 hardpoints makes one of the them glitch out. The list only shows 6.

**Comment by Regalis11** [comment] 2022-05-09 07:22
I'm afraid I could not reproduce this
![image](https://user-images.githubusercontent.com/14351070/167359913-0dfe4a2a-ff9a-47d1-860d-f4f48dc240e6.png)

**Comment by Regalis11** [comment] 2022-06-10 10:21
No known steps to repro, closing

**Closed by Regalis11** 2022-06-10 10:21 UTC
Labels: Bug, Need more info, Code
