### ISSUE TITLE
[0.1004.0.0] Navigation Terminal still shows the docking interface, when Shuttle is docked

### ISSUE THREAD

**Issue by mrjpjr** [Regalis11/Barotrauma#3150] opened 2020-06-19 13:54 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
There is a docked shuttle, but the Navigation Terminal for both the main sub and the shuttle show the docking interface, as if the shuttle is not docked.

**Steps To Reproduce**
1) Create a shuttle and place docking ports/hatches in close proximity to each other 
(I have attached my shuttle for testing)
2) Dock the shuttle to a sub

Once docked, the docking interface in the Nav terminal still shows as if it is not docked.

**Version**
Unstable 0.1004.0.0, revision 5a89e70b4
Windows 10, 64 bit

**Additional information**
I believe this is caused by proximity of additional docking ports/hatches.

Main Sub Nav terminal pic:
https://cdn.discordapp.com/attachments/668819422919524352/723526546048024646/20200618222840_1.jpg
Shuttle Nav terminal pic:
https://cdn.discordapp.com/attachments/668819422919524352/723526607133868084/20200618223011_1.jpg

Shuttle pic: 
https://cdn.discordapp.com/attachments/668819422919524352/723526238995742750/20200618225525_1.jpg
Shuttle sub file:
[MC80A shuttle_0.52.sub.zip](https://github.com/Regalis11/Barotrauma/files/4804830/MC80A.shuttle_0.52.sub.zip)

**Comment by ekqvist** [comment] 2020-07-07 10:30
Thanks for the report! Unfortunately, I'm not able to reproduce the issue. I tried docking the shuttle to Dugong and both interfaces displayed "Undock" correctly after docking. I also tried to test the vertical docking port by docking the shuttle in place of the Remora drone, but the shuttle interface displayed "Undock" correctly again after docking.

Would it be possible for you to also provide the sub with which this happens? Or does the issue persist with all subs for you? What game mode were you playing? Is there any additional info you could give for reproducing this?

**Comment by mrjpjr** [comment] 2020-07-07 11:09
Here is the main sub file.
[MC80A Home One_1.53cu.sub.zip](https://github.com/Regalis11/Barotrauma/files/4884355/MC80A.Home.One_1.53cu.sub.zip)

As I indicated in Additional Information: I believe the issue has to do with the proximity of additional docking ports, so the issue won't show up with the Dugong or Remora, because they don't have docking ports/hatches that the shuttle's _other_ docking ports would be able to dock to nearby.

**Comment by ekqvist** [comment] 2020-07-07 11:13
Thanks for the clarification! I had a slight misunderstanding about it.

**Comment by ekqvist** [comment] 2020-07-08 10:22
Should be fixed in Regalis11/Barotrauma-development@a5fadcd. You were completely right about the cause of the issue. The docking mode shouldn't now be enabled anymore if the sub is docked to the target sub through another port.

**Comment by Rokvach** [comment] 2020-09-08 09:37
Working correctly, closing.

**Closed by Rokvach** 2020-09-08 09:37 UTC
Labels: Bug, Code
