### ISSUE TITLE
Shell corners producing shadows

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#4960] opened 2021-02-01 19:40 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Shell corners produce shadows that shoudn't exist. Previously reported in a ticket closed back in April 2019, but the bug still remains to this day #1366. Worth reopening?

**Steps To Reproduce**
Place down any curved Shell on a sub. The corners of the white selection box will produce a shadow when lit by a shadow-casting light.
![unknown](https://user-images.githubusercontent.com/73229309/106509162-878a6780-64cd-11eb-9579-fadde32c3fcc.png)
![unknown](https://user-images.githubusercontent.com/73229309/106509033-5b6ee680-64cd-11eb-8553-9a18c477120a.png)

**Comment by Regalis11** [comment] 2022-04-06 13:17
Duplicate of https://github.com/Regalis11/Barotrauma/issues/6000

**Closed by Regalis11** 2022-04-06 13:17 UTC
Labels: Bug, Code, Low prio
