### ISSUE TITLE
[0.15.19.0] Multiplayer - Unable to change Wifi Channels of Wifi Component

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#7689] opened 2021-12-09 21:05 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Unable to change Wifi Channels of Wifi Component in a round. Client side it shows the number changed, but it's still at 0 no matter what.

**Version**
0.15.19.0

**Additional information**

**Comment by Regalis11** [comment] 2021-12-10 11:43
How do you know the channel didn't change? I suspect it actually may have changed, but https://github.com/regalis11/barotrauma/issues/7683 is for some reason still preventing a headset from communicating with other wifi components.

**Comment by Kaillera** [comment] 2021-12-10 14:03
Everyone kept saying the channel remains 0 no matter what I changed it to.

**Comment by Kaillera** [comment] 2021-12-10 22:36
So I didn't get to see if it was still happening before editting my headset when I solo my MP campaign this morning, but I changed my team to Team 1 on my headset and I had another player (JP) confirmed the wifi channel was changing in 0.15.19.0.

**Comment by Regalis11** [comment] 2021-12-13 15:49
Seems to have been caused by the same issue as https://github.com/Regalis11/Barotrauma/issues/7683, fixed in https://github.com/Regalis11/Barotrauma-development/commit/ef747547ec0580808f7b1972f7720514cfd9088c. Steps to repro:

1. Host a server with "allow linking wifi to chat" enabled.
2. Join the server as a client without settings management permissions
3. Start a round: you should see that `set "LinkToChat" to "false"` message in the server log.
4. The client's headset should now be in this broken state.

**Comment by Rokvach** [comment] 2021-12-14 10:13
Tested, wasn't able to reproduce the issue anymore, working correctly. Closing.

**Closed by Rokvach** 2021-12-14 10:13 UTC
Labels: Bug, Code, Networking
