### ISSUE TITLE
Game not saving  after exiting to the game lobby and hitting the save and quit

### ISSUE THREAD

**Issue by Erars** [Regalis11/Barotrauma#4064] opened 2020-10-12 11:35 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The game does not get saved when exiting the game  and then clicking on "save and quit". I bought several sub upgrades, but they don't appear when loading the save file.  Also all items that were either fabricated or deconstructed does not seem to appear. 

**Steps To Reproduce**
In multiplayer, buy  the upgrades in the station,   hit exit to server lobby, then click  on the "save and quit" button.  The game does not save as expected upon loading back in.  

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**

**Comment by Regalis11** [comment] 2021-05-06 13:56
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/db7ab41 and https://github.com/Regalis11/Barotrauma-development/commit/70457bd

**Comment by Rokvach** [comment] 2021-05-26 08:27
Tested, the purchased upgrades aren't shown when you reload the campaign save without undocking from the outpost. 

Steps:
1. Start multiplayer campaign
2. Buy couple hull upgrades
3. Return to server lobby and hit Quit
4. Load up the save
5. Go check your upgrades and notice that it shows empty
6. Redock to the station, now the upgrades are shown correctly

At step 5, you can buy the upgrades you have already bought but it doesn't allow you to buy more upgrades than what you bought previously, so if you bought two hull upgrades you can only re-buy two hull upgrades even though you have money for more.

**Comment by Rokvach** [comment] 2021-05-26 08:44
Tested, only issue I came across was with the upgrades where I wrote the reproduction steps on the referenced ticket above ^, other than that everything does get saved properly. So this seems to be working correctly, closing.

**Closed by Rokvach** 2021-05-26 08:44 UTC
Labels: Bug, Code, Medium Prio, Networking
