### ISSUE TITLE
Game Crashes in Submarine Editor

### ISSUE THREAD

**Issue by Captain-Foxtrot** [Regalis11/Barotrauma#9436] opened 2022-06-21 02:02 UTC
### Disclaimers

- [ ] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Changing the 'target' option on a motion detector when having multiple selected will cause the game to crash. I should be able to edit the settings for several motion detectors simultaneously in the submarine editor.

I hope this is helpful.

### Reproduction steps

1. Enter the submarine editor.
2. Spawn in a few motion detectors.
3. Ctrl-click the detectors to select them all.
4. Scroll to the target option to change what the detector will search for.
5. Change this setting.
6. The game will crash every time this occurs.

### Bug prevalence

Happens every now and then

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Exception: Object of type 'System.String' cannot be converted to type 'Barotrauma.Items.Components.MotionSensor+TargetType'. (System.ArgumentException)
Target site: System.Object TryChangeType(System.Object, System.Reflection.Binder, System.Globalization.CultureInfo, Boolean)
Stack trace: 
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at Barotrauma.SerializableEntityEditor.MultiSetProperties(SerializableProperty property, Object parentObject, Object value) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Serialization\SerializableEntityEditor.cs:line 1444
   at Barotrauma.SerializableEntityEditor.SetPropertyValue(SerializableProperty property, Object entity, Object value) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Serialization\SerializableEntityEditor.cs:line 1348
   at Barotrauma.SerializableEntityEditor.<>c__DisplayClass28_0.<CreateEnumFlagField>b__0(GUIComponent selected, Object val) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Serialization\SerializableEntityEditor.cs:line 644
   at Barotrauma.GUIDropDown.<AddItem>b__64_0(GUITickBox tb) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIDropDown.cs:line 290
   at Barotrauma.GUITickBox.set_Selected(Boolean value) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITickBox.cs:line 39
   at Barotrauma.GUITickBox.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITickBox.cs:line 231
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1229
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 898
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59
```

**Comment by Regalis11** [comment] 2022-06-21 06:18
Duplicate of https://github.com/Regalis11/Barotrauma/issues/9401

**Closed by Regalis11** 2022-06-21 06:18 UTC
Labels: Bug, Duplicate, Code, Crash
