### ISSUE TITLE
Character loss on Rejoin (sometimes)

### ISSUE THREAD

**Issue by LeakingAmps** [Regalis11/Barotrauma#7513] opened 2021-11-27 04:36 UTC
- [Could not find an identical issue] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Rejoining servers has a chance to wipe your character and change your class

**Steps To Reproduce**
I have no idea. I was kicked for AFK and rejoined. When I rejoined, I was a Medic (I've been playing as Captain this whole game), and all my stuff was gone. Server lobby shows me as a medic in the save now. Several other players were also kicked for AFK, and did not have this issue on rejoin.

**Version**
Windows v0.15.13.0 Hotfix

**Additional information**
There are several issues on the tracker about loosing items on rejoin, but I could not find any where you lost your skill points and class as well.

There's a reddit thread about the same issue here: https://www.reddit.com/r/Barotrauma/comments/qjtou5/character_save_data_lost_on_rejoin/

**Comment by Regalis11** [comment] 2021-11-27 09:21
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7300

**Closed by Regalis11** 2021-11-27 09:21 UTC
