### ISSUE TITLE
help!

### ISSUE THREAD

**Issue by bugdead** [Regalis11/Barotrauma#8046] opened 2022-01-16 10:55 UTC
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/7876781/crashreport.2.log)

**Comment by Jade-Harleyy** [comment] 2022-01-16 14:48
Seems to be another case of #1833.

**Comment by Regalis11** [comment] 2022-01-17 07:28
Duplicate of #1833

**Closed by Regalis11** 2022-01-17 07:28 UTC
