### ISSUE TITLE
server errors when joining multiplayer missions

### ISSUE THREAD

**Issue by ImJustCorny** [Regalis11/Barotrauma#9551] opened 2022-07-10 14:34 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

hey guys new to barotrauma and want to play with some friends. having issues when I join a server it wont let me spawn or spectate, when i hit either of the buttons it greys out and leaves me at the pre mission start menu. ive been told it could be a firewall issue but my firewall is allowing permissions to baroutrauma. i uninstalled my 3rd party antivirus and also my vpn and still no luck. not sure if there is something else im missing. 

very rarely while joining a game i can actually play, there does not seem so be a reason as to why this occurs its fairly random. only happened twice out of 40 attempts so far. however at the end of those games while everyone gets returned to the menu i get stuck in the match and have to leave and manually rejoin. after attempting to rejoin i got this error in the images bellow:

![baro error](https://user-images.githubusercontent.com/109030307/178148431-cc6cf9bb-00ac-42b4-9034-6fbd180bfcb7.PNG)
![image_2022-07-11_001617510](https://user-images.githubusercontent.com/109030307/178148575-7c8ea658-10f6-4f32-91f2-97d882494e4c.png)

the other match i was able to join resulted in a crash at the end listed here:
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/9079240/crashreport.log)

if things were working correctly i should have been able to enter the game when the server started, instead soft locked at menu most of the time

i appreciate you taking the time to read this, appreciate any help i could get as i just want to be able to play the game as its a hell of a lot of fun :)

### Reproduction steps

unable to reliably discern why my game fails to boot into the server while it works fine for others

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
listed in 'what happened' section
```

**Comment by Regalis11** [comment] 2022-07-11 06:54
Duplicate of https://github.com/Regalis11/Barotrauma/issues/8953

**Closed by Regalis11** 2022-07-11 06:54 UTC
