### ISSUE TITLE
[Unstable] When starting a new round in multiplayer, player will shown to be playing as a different player

### ISSUE THREAD

**Issue by StruggleDuck** [Regalis11/Barotrauma#6898] opened 2021-10-12 13:23 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I have encountered this bug once myself, and have been told of a friend also experiencing this bug. Upon starting a new round, the game will incorrectly show a player to be controlling another players character. This will render the player unable to interact with things properly, and will only be solved upon leaving and rejoining the server.

**Steps To Reproduce**
Unsure on how to reproduce, as it has only happened to me once personally. It happened in a multiplayer server, where I was not the host.

**Version**
Latest version of the unstable branch

**Comment by Regalis11** [comment] 2021-11-16 13:07
This could be related to https://github.com/Regalis11/Barotrauma/issues/4798 - do you have any idea if your friend could've been playing from the same IP address (e.g. using the same WIFI) as the player whose character they appeared to be controlling?

**Comment by linax3-genuine** [comment] 2021-12-04 18:58
im playing 15.13 (the latest steam release) and i think this happened to me too.
i cant remember well, but i think there was an error message in the log before this happened, as i was not surprised when we got in the game, maybe it was bugged in the lobby too.
the host was making some forced(console?) (re)starts.
i and others were playing different(including left, i think) players.
we had nothing in common with the IPs. total strangers.
i left the server and i did not rejoin. cant say if that would fix something.

**Comment by Regalis11** [comment] 2022-01-10 20:20
Most likely a duplicate of https://github.com/Regalis11/Barotrauma/issues/6678

**Closed by Regalis11** 2022-01-10 20:20 UTC
Labels: Bug, Need more info, Code, Networking
