### ISSUE TITLE
Faction config break AI on outposts

### ISSUE THREAD

**Issue by Alpharius-30-milenium** [Regalis11/Barotrauma#12789] opened 2023-10-12 13:59 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

So, if you have any custom outpost type that you won't to have faction in, npcs on that outpost will not do anything to maintain station or fight back in case of boarding. This is also problem on abandoned outposts since bots are literally don't react on players' actions and not maintaining even critical systems/fixing hulls.

### Reproduction steps

1. Create custom location type
2. Set outpostteam="None"

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-10-12 14:38
Thank you for the report!

To me it seems like this is a duplicate of https://github.com/Regalis11/Barotrauma/issues/12790 - even though you made the ticket first I think we could close this one since the newer one has a bit more information.

**Closed by Regalis11** 2023-10-12 14:38 UTC
