### ISSUE TITLE
Question About Chance For Traitors

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1139] opened 2019-02-13 09:13 UTC
What is the percentage chance of traitors to show up on "maybe" setting? Will there be in the future a way to edit it by hosts of servers? Will players always have permission to know exact chance for traitors to show up?

**Comment by Regalis11** [comment] 2019-02-13 15:07
Duplicate of #637

**Closed by Regalis11** 2019-02-13 15:07 UTC
