### ISSUE TITLE
Faraday artifact no longer triggers its effect after triggering in Transport Case

### ISSUE THREAD

**Issue by Bryzz** [Regalis11/Barotrauma#8071] opened 2022-01-21 07:06 UTC
I have searched through issues and did not see this bug in the list.

**What's the issue?**

Faradays artifacts don't trigger their EMP effect anymore under specific circumstances. It seems to be disabled if it is stored inside a transport case and triggers its EMP effect while stored.

**What was the expected behavior?**

The Faraday artifact should resume its EMP bursts when taken away from its transport case after being stored for a short while.

**What are the steps to reproduce this bug?**

- find a faraday artifact
- put it inside an artifact transport case
- wait around 30 seconds for the faraday artifact to trigger its EMP blast
- take it away from the container

The artifact does not recover its ability to create EMP bursts when left outside its transport case in between campaign missions.

**Game version**

v0.15.23.0

**Operating system**

Windows 10 64 bits

**Comment by Regalis11** [comment] 2022-01-21 07:37
This seemed to have been caused by the issue reported in https://github.com/Regalis11/Barotrauma/issues/8049, fixed in https://github.com/Regalis11/Barotrauma-development/commit/d015258aa4636943950a478d71fcff268f855e3a

**Comment by Bryzz** [comment] 2022-01-21 11:27
I shall add that, upon further testing on my end, this does not seem to apply to other artifacts (to be confirmed)

**Comment by Rokvach** [comment] 2022-02-02 09:32
Tested, working correctly. Closing.

**Closed by Rokvach** 2022-02-02 09:32 UTC
Labels: Bug, Code
