### ISSUE TITLE
Hulls not Fixing after Paying

### ISSUE THREAD

**Issue by ApolloNuke** [Regalis11/Barotrauma#9586] opened 2022-07-17 12:43 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If you buy "fix all hulls" , it doesent fix them, and you are unable to fix them with a welding tool. Only after a restart of the save all hulls and breaches we´re fixed. This issue happend in multiplayer, hosted server in the campaign. Happens with and without mods.

### Reproduction steps

1. Start a multiplayer campaign
2. Damage the hulls 
3. dont fix them yourself OR let the bots fix them
4. dock to an outpost (or somewhere else)
5. buy "fix all hulls"
6. start a mission
7. and observe the hulls not being repaired

### Bug prevalence

Happens regularly

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-07-17 13:23
I'm afraid I couldn't reproduce this. Did you or someone else in the server by any chance use the "godmode_mainsub" command? That would prevent the walls from being repaired, since it (maybe somewhat intuitively) "locks" the health of the walls in place, preventing them from being either damaged or repaired.

**Comment by ApolloNuke** [comment] 2022-07-19 16:32
I didnt  use any console commands, and could try and reproduce it myself and record it if that would help?

**Comment by Regalis11** [comment] 2022-07-20 12:06
Thank you! I got this to happen now - I think the reason I couldn't repro it was that I did the damage and purchasing the repairs during the same round, without undocking and docking in between. Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/f2839a4f9c06d8506eb506c0f0518749499315df

**Comment by ApolloNuke** [comment] 2022-07-20 18:05
Haha thanks for the help :)

**Comment by Rokvach** [comment] 2022-08-23 13:10
Tested, working correctly. Closing

**Closed by Rokvach** 2022-08-23 13:10 UTC
Labels: Bug, Code, Networking, Unstable
