### ISSUE TITLE
Radio event broken

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#9497] opened 2022-06-30 22:45 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This doesn't progress the event and makes it stuck. I think multiple ppl at the same time opened it, as the event spawned right in the station airlock.
![image](https://user-images.githubusercontent.com/59519434/176790686-69d6db89-24eb-4b8b-b32f-b22938e63c9e.png)

### Bug prevalence

Just once

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-07-01 07:13
Potential duplicate of https://github.com/Regalis11/Barotrauma/issues/7691

**Comment by Regalis11** [comment] 2022-07-01 07:58
Found a simple way to repro this:
1. 2 clients on a server
2. Trigger the "shockjock" event
3. Select "Ignore" on the first prompt as Client 1
4. The conversation will get stuck on Client 2

Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/5a6854f0c481fd8a485f7786c30210564927081c

**Comment by NilanthAnimosus** [comment] 2022-07-26 16:23
Tested in 0.19.0.0 - works correctly, closing.

**Closed by NilanthAnimosus** 2022-07-26 16:23 UTC
Labels: Bug, Code, Unstable
