### ISSUE TITLE
MEM not working properly in certain pattern of circuit after duplicated

### ISSUE THREAD

**Issue by AbyssusTaotieh** [Regalis11/Barotrauma#7455] opened 2021-11-23 10:18 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Actually, I recommend taking a look at the picture first.
picture: https://imgur.com/AVvlNy7
I would describe this pattern of circuit first to make it clear. Oscillatory information to a relay's singnal-input1, the relay's singnal-output1 to a MEM, a pulse type oscillator to the relay's toggle-state, and the relay's state-out to a NOT, the NOT to the MEM's lock-state.
This could work well to make the MEM receive information periodically. However, if I copy it(1st), the MEM in the pasted circuit(2nd) becomes unable to be writtren. Futhermore, if I duplicate the bugged one, the MEM in the new one(3rd) becomes normal.

**Steps To Reproduce**
as above

**Version**
 v0.15.13.0 hotfix
 Windows 

**Additional information**
Precisely, the MEM is not unable to be writtten. Its "lock-state" just receives a permanent 0 signal from somewhere. If I use a button  linked to the MEM's "lock-state, it could still recieve information when I push the button.

**Comment by Regalis11** [comment] 2021-11-23 16:52
Related ticket: https://github.com/Regalis11/Barotrauma/issues/6501

**Comment by Regalis11** [comment] 2022-09-27 19:10
Closing as a duplicate of https://github.com/Regalis11/Barotrauma/issues/6501, this is very likely to be caused by the same underlying issue (item update order affecting the behavior of the circuit)

**Closed by Regalis11** 2022-09-27 19:10 UTC
Labels: Bug, Code
