### ISSUE TITLE
Bots - Waypoint Loop at Docking Port going from Shuttle to Sub.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2675] opened 2020-04-23 15:59 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots are looping on docking ports waypoints between Shuttle to Sub on my new Sub.
[Corsair.zip](https://github.com/Regalis11/Barotrauma/files/4523678/Corsair.zip)

**Steps To Reproduce**
Tell a bot to operate the reactor when they are in the Shuttle or near the docking port to the shuttle in the Submarine.

**Version**
0.9.9.0

**Additional information**
They seem to think there's a shortcut to the reactor right between the docking ports or something.

**Comment by Regalis11** [comment] 2020-04-24 10:19
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2013fda

**Comment by Rokvach** [comment] 2020-04-24 10:39
I wasn't able to reproduce the issue after the fix, nor saw any other behavior issues. Seems to be working correctly. Closing.

**Closed by Rokvach** 2020-04-24 10:39 UTC
Labels: Bug, Code
