### ISSUE TITLE
[0.9.8.0] AI Bots sometimes operate wrong periscope for railgun.

### ISSUE THREAD

**Issue by HalfdeadKiller** [Regalis11/Barotrauma#2652] opened 2020-04-18 00:31 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When I order an AI to operate the bottom right railgun, the AI hops onto the periscope for the Top Right railgun.

**Steps To Reproduce**
Download included submarine, ensure bots are turned on, tell any bot to operate either the Top or Bottom railgun. The bot will operate the wrong periscope. You can check which periscope goes to which gun, but the Left periscope should go to the Top Railgun, and the Right periscope should go to the Bottom Railgun.

**Version**
Barotrauma 0.9.8.0 - Windows 10

**Additional information**
I attempted fixing by deleting and replacing the periscopes, and then wiring the railguns to the relay that goes to the railgun first, and then the relay that goes to the camera/searchlight. This could be related to unconventional relay use, but I don't really know.
[Atlas - v1.7.sub.zip](https://github.com/Regalis11/Barotrauma/files/4495739/Atlas.-.v1.7.sub.zip)

**Comment by ekqvist** [comment] 2020-04-24 11:45
Thanks for the report! I've been doing some testing for the issue today. The issue is likely caused by how the orders and their targets work when the order target (i.e. the turret) uses a controller (i.e. the periscope) and how we find the controller in the code.

Basically, when you set the "Operate Weapons" order for a character, the order is given with the turret as the target, but it needs to find the controller for it. We find it by checking the wiring to find the periscope connected to the turret. On the linked sub, the code seems to return both of the periscopes used for the two railguns and then sets the incorrect one as the controller.

**Comment by ekqvist** [comment] 2020-04-29 11:15
Should be fixed now with Regalis11/Barotrauma-development@8f24246.

Thanks again for reporting the issue and for providing your custom sub which made it easy to test this!

**Comment by Rokvach** [comment] 2020-05-25 06:38
Working correctly, closing.

**Closed by Rokvach** 2020-05-25 06:38 UTC
Labels: Bug, Code
