### ISSUE TITLE
Engine sound level is maximal when voltage is low

### ISSUE THREAD

**Issue by mygamingaccount** [Regalis11/Barotrauma#11503] opened 2023-03-14 06:50 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The playback level of the engine sound when voltage is very low is 100% if the thrust is set to 100%

The aitarget level increases with thrust and I believe the in-game sound level should be indicative of the sound the aliens hear.

### Reproduction steps

`quickstart azimuth`

**Test version 1**
As soon as the nav terminal can be used set propulsion to full speed ahead

Outcome:
The engine roars at full volume

Expected:
the engine is only as loud as hard it is pushing

**Test version 2**
Vary the reactor turbine rate using manual control

Outcome:
the engine volume does not change

Expected:
The engine volume changes as the thrust changes due to voltage

Additionally, observe with `aitargets` the radius of the engine noise, it changes with voltage.

### Bug prevalence

Happens every time I play

### Version

v1.0.7.0

### Which operating system did you encounter this bug on?

Linux

**Comment by mygamingaccount** [comment] 2023-03-14 07:09
Hint:
#10845

**Comment by Regalis11** [comment] 2023-03-14 11:00
I'm afraid I could not reproduce the issue. The volume seems to scale linearly with the voltage, reaching 100% when past the minimum voltage.

**Comment by Regalis11** [comment] 2023-03-14 11:05
Your comment in the PR clarified the issue: I didn't realize the engine doesn't run at all when below the minimum voltage (meaning the volume was always 100% when the engine had enough power to run). Addressed in https://github.com/Regalis11/Barotrauma-development/commit/6d12596e02bd560888be8e924193f210fc5214ba

**Comment by mygamingaccount** [comment] 2023-03-14 11:53
A related issue was uncovered: whether the engine can be overvolted depends on MinVoltage instead of powerConsumption

An engine with MinVoltage = 0.0 should still benefit from overvoltage. It means it won't cut off.

An engine with powerConsumption = 0 is expected to work without any power and thus shouldn't check voltage, even though it can go above

**Comment by Jasontti** [comment] 2023-05-22 07:02
Tested. Engine sounds stop when not enough voltage is supplied.

**Closed** 2023-05-22 07:03 UTC
Labels: Bug

**Comment by mygamingaccount** [comment] 2023-06-05 01:14
> Tested. Engine sounds stop when not enough voltage is supplied.

Those are not the repro steps

**Comment by Jasontti** [comment] 2023-06-05 06:30
> Test version 1
> As soon as the nav terminal can be used set propulsion to full speed ahead
>
> Test version 2
> Vary the reactor turbine rate using manual control

Are there other test that should be considered?

**Comment by mygamingaccount** [comment] 2023-06-05 11:29
> Engine sounds stop when not enough voltage is supplied.

The engine volume should increase gradually as voltage increases.

Description of the issue: engine loudness is 100% when thrust is only minVoltage (e.g. 10%)
