### ISSUE TITLE
Discharge Coils/Arc Emitters interacting strangely with Shell Combo 1 1

### ISSUE THREAD

**Issue by Metallix203** [Regalis11/Barotrauma#12213] opened 2023-06-22 11:21 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Building a custom sub and encountered an issue with the discharge coil and the Shell Combo 1 1 piece. It appears Shell Combo 1 1 cannot conduct arcs to other Shell Combo 1 1 pieces. when placed in certain configurations Tested with discharge coil in submarine editor and ingame, and also with an Arc Emitter. 

I encountered more weirdness with the arcs and Shell Combo 1 1 but couldn't reproduce them. While the shell pieces placed on their own in the editor conduct on at least one of the pieces, neither of my two submarine shell pieces will conduct the arc. From certain angles Shell Combo 1 2 would also refuse to receive/transmit an arc, but worked fine at others. 

### Reproduction steps

1. Open the submarine editor
2. Place one Shell 1 1 piece
3. Place a second Shell 1 1 piece, mirrored on its Y axis
4. Move them so that they are touching, forming an arc
5. Place a discharge coil on on either of the shell pieces
6. Select the discharge coil and hold space to observe the arc not transmitting between the two pieces

### Bug prevalence

Happens regularly

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-06-24 10:29
Thank you for the report!

I unfortunately could not reproduce the issue, although I'm not entirely sure if I've set the pieces up correctly:
![image](https://github.com/Regalis11/Barotrauma/assets/14351070/d26f48be-735b-450c-95c5-956d3553b5ba)

Would it be possible to send us a screenshot of how you've placed the walls and the discharge coil? Or even better, the submarine file so we could give it a test directly? Thanks and sorry for the inconvenience!

**Comment by Metallix203** [comment] 2023-06-25 04:58
![20230624215611_1](https://github.com/Regalis11/Barotrauma/assets/44307501/a956e0d2-6cca-4410-9a95-4b7dda9e6b97)
[Jawbreaker.zip](https://github.com/Regalis11/Barotrauma/files/11858881/Jawbreaker.zip)
I've included a screenshot demonstrating the effect, and a copy of my submarine, hope that helps.

**Comment by Metallix203** [comment] 2023-06-25 05:01
My bad, hit the wrong comment submission button and accidentally closed the issue.. To add some context, copying out that portion of shell also acts strangely. The discharge effect will conduct to the top shell, but not the bottom, while the ship's discharge coil doesn't conduct to either piece. Here's an example of another effect I noticed with the shell combo pieces and not conducting arcs.
![20230624220014_1](https://github.com/Regalis11/Barotrauma/assets/44307501/4232348e-d9a4-4176-bfdd-1733d08a993d)

**Comment by Regalis11** [comment] 2023-06-25 12:25
Thank you, I was able to reproduce and hopefully fix the issue now. The issue had to do with how the game determines which walls are outside the sub - in this case, it incorrectly assumed these pieces were interior walls and didn't allow the discharge to travel across them.

Commits in our private repo:
https://github.com/Regalis11/Barotrauma-development/commit/2830e95fad9eb8bf340dbedb69d2b22abb13a01d
https://github.com/Regalis11/Barotrauma-development/commit/f1d9eee999ee0ae02a1c090b4c33276d5780722a

**Comment by giists** [comment] 2023-08-04 11:21
No issues found, closing.

**Closed by giists** 2023-08-04 11:21 UTC
Labels: Bug, Code
