### ISSUE TITLE
[Unstable] Swapping stack of oxygen tanks into diving suit deleting the stack.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#4858] opened 2021-01-21 20:09 UTC
(This is somewhat of a duplicate issue - but making a new ticket for it as the previous tickets about this have been closed a month ago.)

Trying to drag a stack of 8 oxygen tanks into the inventory of a diving suit with a partially depleted tank, the game does not seem to know where the other 7 tanks should go because the inventory slot that they were in has now been filled by the partial tank from the suit, so all the other tanks in the stack simply vanish.

8x tanks in hotbar , partial tank in suit -> one tank in suit , partial tank in hotbar , stack nowhere to be seen.

**Comment by Regalis11** [comment] 2021-01-22 09:56
I'm afraid I could not reproduce this: the 7 extra tanks are automatically moved to an empty slot, and if there's no empty slot, the tanks can't be swapped.

**Comment by Rokvach** [comment] 2021-01-26 10:06
Tested, wasn't able to reproduce, seems like this was fixed at some point. Closing.

**Closed by Rokvach** 2021-01-26 10:06 UTC
Labels: Bug, Code, Medium Prio, Need more info
