### ISSUE TITLE
Error - Failed To Copy The Incoming Uncompressed Buffer

### ISSUE THREAD

**Issue by bdcthe2nd** [Regalis11/Barotrauma#7360] opened 2021-11-18 05:15 UTC
![Screenshot 2021-11-17 222606](https://user-images.githubusercontent.com/82500926/142351584-1d45c757-f5ce-4947-a6c4-e93ddaa5d3a1.png)

![screenshot](https://user-images.githubusercontent.com/82500926/142351635-9d9f6591-902c-4f76-b34e-467c3300f55a.png)

**Description**
Can't join multiplayer. Have tested with different friends hosting. Same error. 
Sandbox mode works fine for some reason?
No workshop items are installed

**I HAVE TRIED THE FOLLOWING:  
Verifying game files multiple times 
Installing, restarting computer, then re-installing game from scratch multiple times
Uninstalling then reinstalling Steam
Disabled antivirus, controllers, peripherals removed**

**Version**
Current build. Windows 10.
![screenshot2](https://user-images.githubusercontent.com/82500926/142354126-53211f09-f04b-401d-8618-bf038810a66f.png)

**Comment by Regalis11** [comment] 2021-11-18 10:14
Duplicate of https://github.com/regalis11/barotrauma/issues/6608

**Closed by Regalis11** 2021-11-18 10:14 UTC
Labels: Bug, Code, Networking
