### ISSUE TITLE
[0.9.9.0]FilterServers null pointer

### ISSUE THREAD

**Issue by Manpapper** [Regalis11/Barotrauma#2677] opened 2020-04-23 17:01 UTC
Hi The game crash after deselecting some gamemode in server list

Barotrauma Client crash report (generated on 23/04/2020 18:57:05)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

B88397013C2378C4A99C3E19DEBEE54F

Game version 0.9.9.0 (ReleaseWindows, branch release, revision 0534150c8)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.ServerListScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.18362.0 64 bit
    GPU name: NVIDIA GeForce GTX TITAN X
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void FilterServers()
Stack trace: 
   at Barotrauma.ServerListScreen.FilterServers()
   at Barotrauma.ServerListScreen.<>c__DisplayClass70_0.<CreateUI>b__26(GUITickBox tickBox)
   at Barotrauma.GUITickBox.set_Selected(Boolean value)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime)
   at Barotrauma.GameMain.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Barotrauma.Program.Main(String[] args)

Last debug messages:
[23/04/2020 18:56:41] OpenAL Soft on Microphone (Rift Audio) 38
[23/04/2020 18:56:41] OpenAL Soft on Microphone (Logitech G933 Gaming Wireless Headset) 65
[23/04/2020 18:56:33] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[23/04/2020 18:56:33] Content package load order: Vanilla 0.9
[23/04/2020 18:56:33] Content package load order: Vanilla 0.9
[23/04/2020 18:56:31] Attempting to open ALC device "OpenAL Soft"
[23/04/2020 18:56:31] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[23/04/2020 18:56:30] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[23/04/2020 18:56:30] Logged in as Manpapper (SteamID STEAM_1:1:46775599)

**Comment by Rokvach** [comment] 2020-04-23 19:54
I was able to reproduce this, change to any other language than English and untick Sandbox from the server  filters in server browser.

**Comment by Regalis11** [comment] 2020-04-24 08:54
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bf2422ad092aaf480e737e2f73922a4dde33aceb

**Comment by Rokvach** [comment] 2020-04-24 08:56
I wasn't able to repro this after the fix, seems to be working correctly. Closing.

**Closed by Rokvach** 2020-04-24 08:56 UTC
Labels: Bug, Code, Crash
