### ISSUE TITLE
The hull/wall shrapnel damage is abnormal

### ISSUE THREAD

**Issue by kiauio** [Regalis11/Barotrauma#12875] opened 2023-10-21 09:25 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

https://github.com/Regalis11/Barotrauma/assets/113630423/1730a67d-a77b-499b-b668-a24bde5c855a

### Reproduction steps

The probability of triggering exists in any level of the hull.

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Single player

### Version

v1.1.18.1 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-10-21 10:19
Thank you for the report! Addressed in https://github.com/Regalis11/Barotrauma-development/commit/2d93eb5a482d65406e144f0fd4ecb1ffeceb008c (commit in our private repo)

**Comment by Jasontti** [comment] 2023-10-23 14:45
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4577/commits/a1a6a605af92c4ee7eb8132752df180b8666690d

Spawned a hammerhead and observed the effects.
Shrapnel is more contained now and doesn't have such cascading effects now.
Damage from it is still a threat, but manageable.

No issues found
Closing ticket

**Closed by Jasontti** 2023-10-23 14:45 UTC
Labels: Bug, Code, Balance

**Comment by kiauio** [comment] 2023-10-24 09:54
This is obviously abnormal.  A normal ship hull being destroyed would have obvious debris splashing, and the damage would not be so high, and it would only affect one room.  This even penetrated through a wall and directly attacked the people inside, and the damage was higher than being bitten directly by a monster.

**Comment by kiauio** [comment] 2023-10-24 09:58
I found that when the external armor covering the hull of the ship was destroyed, the debris would directly attack the people inside, and even penetrate through several rooms.

**Comment by Regalis11** [comment] 2023-10-24 10:42
> This is obviously abnormal

Yes, we agree, those comments above meant we did some fixes to it and Jasontti tested that the fixes worked as intended. We're hopefully getting this hotfixed later this week.
