### ISSUE TITLE
Custom IDs for spawnpoints on Wrecks don't work

### ISSUE THREAD

**Issue by rav2n** [Regalis11/Barotrauma#8098] opened 2022-01-25 14:37 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I'm one of the creators of the[ Shipwrecks Extended ](https://steamcommunity.com/sharedfiles/filedetails/?id=2095211492)mod, and a couple of patches ago, there were reports about the inability to open various safes on sunken submarines, which interferes with the completion of quests. Initially, I thought that this was our omission and double-checked all the work, but the bug continues to appear in multiplayer.

**Steps To Reproduce**
Using [Shipwrecks Extended](https://steamcommunity.com/sharedfiles/filedetails/?id=2095211492), try to open the safe on one of the wrecks provided by the mod.

**Version**
V 0.15.23.0

**Additional information**

**Comment by Ek-Videogames** [comment] 2022-01-25 21:30
Possibly caused by game behavior of 'instancing' wreck IDs on map generation to prevent one ID-card from working on all wrecks?

**Comment by Regalis11** [comment] 2022-01-26 14:27
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9dde726e2030261389da07d9b625c5896e138b6e

**Comment by Lithosagym** [comment] 2022-01-28 03:50
Tested, wreck IDs correctly work on custom wrecks, confirmed fixed.

**Comment by Rokvach** [comment] 2022-01-28 09:58
Closing

**Closed by Rokvach** 2022-01-28 09:58 UTC
Labels: Bug, Code, Unstable
