### ISSUE TITLE
crash when selling multiple stuff

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#11707] opened 2023-04-01 17:14 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

was on my campaign save which was from stable but moved to unstable, went to outpost merchant, sold some stuff from the submarine tab, game immediately crashed when i pressed the sell button.
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/11130133/crashreport.2.log)
i tested it again by selling one item but it didn't crash, then i tried selling two items and it did crash, i tested it again and it did the same thing.

### Reproduction steps

go to outpost, sell multiple stuff from the sub
if it no work try it on this save
[Greed Run.zip](https://github.com/Regalis11/Barotrauma/files/11130146/Greed.Run.zip)

### Bug prevalence

Happens every time I play

### Version

Unstable (v1.1.4.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-04-02 15:44
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11565

**Closed by Regalis11** 2023-04-02 15:44 UTC

**Comment by LePiromano** [comment] 2023-04-02 16:29
i'm fucking crying
