### ISSUE TITLE
All-Seeing eye bug

### ISSUE THREAD

**Issue by ChuisaTrain** [Regalis11/Barotrauma#8507] opened 2022-03-11 17:31 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Unable to upgrade talents point on Weapon Engineer skill tree after All Seeing Eye upgrade. I have read couple threads on Reddit and Steam discussion in regards to this issues and follow their fixes (keep playing up to 3-4 talent points) but to no avail. i used coalition medals to boost engineer level up faster to make up the free level from all seeing eye as quick as possible. Savefile bug  is attached below 
![Capture](https://user-images.githubusercontent.com/101419766/157917116-8fc97bb1-024d-42ab-b1bc-cff54f5464c0.PNG)
[Allseeingbug.zip](https://github.com/Regalis11/Barotrauma/files/8234063/Allseeingbug.zip)

**Version**
Latest Barotrauma version, Windows 10 Pro

**Comment by Regalis11** [comment] 2022-03-14 08:26
Duplicate of https://github.com/Regalis11/Barotrauma/issues/8128

**Closed by Regalis11** 2022-03-14 08:26 UTC
