### ISSUE TITLE
weird ui pop-up when grabbing a hatchling

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#6043] opened 2021-06-11 23:03 UTC
- [yea ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
grabbing a hatchling pops up a little bar on the top left of the screen

**Version**
v0.1400.4.0

**Additional information**
![image](https://user-images.githubusercontent.com/55637865/121756330-19dfef00-caf0-11eb-939d-006ede6eda61.png)

**Comment by Regalis11** [comment] 2021-06-14 06:59
Duplicate of https://github.com/Regalis11/Barotrauma/issues/6023

**Closed by Regalis11** 2021-06-14 06:59 UTC
