### ISSUE TITLE
Text Display - The color of the display suppresses the color of the text

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#7952] opened 2021-12-29 20:43 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

Cannot assign white text color (set_text_color) if the display color (set_color) is assigned.
The color of the display suppresses the color of the text

**Steps To Reproduce**
For example:
Display color - Red
Text color - White
![Image 001_23-33](https://user-images.githubusercontent.com/93348499/147701848-2c3c1fde-b91b-4cd0-a262-e568ed288394.png)

**Version**
v0.15.22.1, Vanilla 0.9 (Windows 10-x64).

**Additional information**
No.

**Comment by DuckY-Y** [comment] 2023-02-07 09:53
Also using other colours other than red and white does not work.

**Comment by Regalis11** [comment] 2023-03-10 10:46
We're cleaning up some low-prio/unreproducible/irrelevant/outdated tickets from the issue tracker, and this is one of the tickets we chose to axe. This is arguably not a bug: colored light tints the things around it. Closing.

**Closed by Regalis11** 2023-03-10 10:46 UTC
Labels: Bug, Code, Low prio
