### ISSUE TITLE
Crash on creating any server (index out of range in ScalableFont.DrawStringWithColors)

### ISSUE THREAD

**Issue by ProfTesla** [Regalis11/Barotrauma#7915] opened 2021-12-23 22:36 UTC
Game just crashes to dump/log whenever I try to start a new server.
It'll say connecting for about 3 seconds, the screen seems to change to something else and then instantly to the crash dialog.

[crashreport (5).log](https://github.com/Regalis11/Barotrauma/files/7771665/crashreport.5.log)

**Comment by Regalis11** [comment] 2022-01-03 09:35
I'm afraid I couldn't find a way to reproduce this, but I added a check in https://github.com/Regalis11/Barotrauma-development/commit/adf10168b6f9cb954b7673347ad7bd6eebfbb1a7 that should hopefully prevent the crash.

It seems the game is failing to render some colored chat message in the server lobby (most likely the "x has joined the server" that appears when the game connects to the server). I wonder if this could have something to do with your Steam username that's included in the message (maybe some special symbols in it)?

**Comment by Rokvach** [comment] 2022-01-27 11:09
There hasn't been any sightings of this happening in the Unstable since the fix released there, seems to be working correctly. Closing.

**Closed by Rokvach** 2022-01-27 11:09 UTC
Labels: Bug, Code, Crash, Unstable
