### ISSUE TITLE
Barotrauma on Linux (native) does not launch while using steam.

### ISSUE THREAD

**Issue by Meganium97** [Regalis11/Barotrauma#9027] opened 2022-04-30 21:52 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Barotrauma either does not launch or crashes instantly when I try to launch under steam
**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.
Try to launch the game via steam, normally
**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).
Latest as of 4/29/22. OS: Linux
**Additional information**
I can circumvent this issue using proton.

**Comment by B1G-FUNGUS** [comment] 2022-04-30 23:40
I have the same issue where Barotrauma will not launch. If I run Barotrauma through the command line I get:
```Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CompareInfo..cctor()
   at System.String.StartsWith(System.String, System.StringComparison)
   at Barotrauma.Steam.SteamManager.SteamIDStringToUInt64(System.String)
   at Barotrauma.Steam.SteamManager.SteamIDUInt64ToString(UInt64)
   at Barotrauma.Steam.SteamManager.InitializeProjectSpecific()
   at Barotrauma.Steam.SteamManager.Initialize()
   at Barotrauma.Program.Main(System.String[])
Aborted (core dumped)
```

I checked and I already have an ICU library installed as a dependency for steam, though I couldn't find any ICU library in my Barotrauma directory.
If it helps, I am using Arch Linux, and I get the same issue whether using steam, steam-native, or running Barotruama directly.

**Temporary Fix**
The game will launch after running `export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1` and then running the game in the command line.

**Comment by EgorIII** [comment] 2022-05-01 06:22
bump, i'm facing same issue, with same crash dump

**Comment by JoneKone** [comment] 2022-05-01 20:55
Works for Ubuntu 24.04

**Comment by Regalis11** [comment] 2022-05-02 07:42
Duplicate of https://github.com/Regalis11/Barotrauma/issues/8858

**Closed by Regalis11** 2022-05-02 07:42 UTC

**Comment by DanielKinsman** [comment] 2022-06-26 05:05
A good fix is to force "Steam Linux Runtime" in the compatibility settings. This would be a good thing to do on the dev side, so that it always starts in the steam linux runtime.
