### ISSUE TITLE
[0.9.703] Inconsistent Navigation Terminal UI position

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2162] opened 2020-02-06 11:45 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
So I have more than 1 navigation terminal in my submarine, and I've noticed they aren't drawn in the same spot.

This one kinda makes my neck hurt because I need to look more to the right as it isn't centered.
![](https://user-images.githubusercontent.com/5086682/73933982-98e56780-48ab-11ea-8e50-ee3c4e514501.PNG)

![](https://user-images.githubusercontent.com/5086682/73934305-2923ac80-48ac-11ea-9c27-6f771aea8e3f.PNG)

**Version**
0.9.703

**Comment by Rokvach** [comment] 2020-02-11 04:31
No issues, closing.

**Comment by itchyOwl** [comment] 2020-02-12 08:42
![image](https://user-images.githubusercontent.com/5370738/74317522-406b0a00-4d84-11ea-8938-901837b7c8b5.png)

Still happens occasionally with different resolutions. Not sure why it triggers only now and then.

**Comment by Rokvach** [comment] 2020-02-12 09:09
I suspect that it is caused because there isn't enough room between the chat and portrait areas so the nav terminal gets pushed out of the way. Need to see when the portrait area goes back to bottom right.

**Comment by Rokvach** [comment] 2020-02-12 11:35
Update: This issue can be reproduced in the captain tutorial regardless of resolution, the nav terminals position is off when you open it up while there isn't any power in the sub, only after you have ordered the engineer to turn on the reactor and waited for power to come online the sonar gets re-positioned to the correct position.

**Comment by Regalis11** [comment] 2020-02-12 13:09
Yeah, in @itchyOwl's pic the issue is that there's isn't enough space between the chat and the portrait to keep the UI at it's default position. You can see the areas the UI is not allowed to go inside with the command "hudlayoutdebugdraw".

**Comment by Rokvach** [comment] 2020-02-12 23:31
I think I found the issue, if you press the Navigation Terminal first the UI will be positioned wrong, only if you press the Status Monitor the UI gets corrected and after that no matter which one you press the UI will be correct. But I've only been able to reproduce this in the tutorial submarine.

**Comment by Rokvach** [comment] 2020-02-20 09:00
Noticed this yesterday on Humpback as well, if you click the nav terminal it shows the UI wrong but if you click the status monitor it shows it correctly and fixes the position

**Comment by itchyOwl** [comment] 2020-06-18 08:13
Related: #1832

**Closed** 2021-01-13 13:29 UTC
Labels: Bug, Code
