### ISSUE TITLE
Cannot start dedicated server on linux

### ISSUE THREAD

**Issue by esirprus** [Regalis11/Barotrauma#9993] opened 2022-10-06 02:13 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Just update the server, and then try to start, it will post an error:
 Starting btserver: Unable to start Server

### Reproduction steps

update the server, and then try to start

### Bug prevalence

Happens every time I play

### Version

0.19.10.0

### Which operating system did you encounter this bug on?

Linux

**Comment by esirprus** [comment] 2022-10-06 02:43
idk what should i provide to u, so tell me what i need to do, thank you!

**Comment by cshingle** [comment] 2022-10-06 03:50
Are you trying to run the server on your Desktop or a headless machine?
You could provide the console output so the devs have some idea what is going wrong. It should look something like this. I was able to join the server without any issues.
```
~/.steam/debian-installation/steamapps/common/Barotrauma$ ./DedicatedServer
Barotrauma Dedicated Server 0.19.10.0 (ReleaseLinux, branch release, revision 811fb37ab3)
Loading game settings
Loading MD5 hash cache
Initializing SteamManager
Initializing GameScreen
dlopen failed trying to load:
steamclient.so
with error:
steamclient.so: cannot open shared object file: No such file or directory
[S_API] SteamAPI_Init(): Loaded '/home/user/.steam/debian-installation/linux64/steamclient.so' OK.  (First tried local 'steamclient.so')
CAppInfoCacheReadFromDiskThread took 8 milliseconds to initialize
Setting breakpad minidump AppID = 602960
[S_API FAIL] Tried to access Steam interface SteamNetworkingUtils003 before SteamAPI_Init succeeded.
Selected sub: D-7 Dromedary                                                                                                   
Selected shuttle: Hemulen                                                                                                      [10/05/2022 22:41:45]
  Starting the server...                                                                                
[10/05/2022 22:41:45]
  Using Lidgren networking. Manual port forwarding may be required. If players cannot connect to the server, you may want to use the in-game hosting menu (which uses SteamP2P networking and does not require port forwarding).       
[10/05/2022 22:41:45]
  Server started                                                                                        
Message type 9806 wasn't declared, but we registered job CClientJobEnableOrDisableDownloads to handle it? 
```

It seems like the most common issue people run into is missing config files. The wiki has good info on those here
https://barotraumagame.com/wiki/Hosting_a_Dedicated_Server

**Comment by esirprus** [comment] 2022-10-06 08:24
> Are you trying to run the server on your Desktop or a headless machine? You could provide the console output so the devs have some idea what is going wrong. It should look something like this. I was able to join the server without any issues.
> 
> ```
> ~/.steam/debian-installation/steamapps/common/Barotrauma$ ./DedicatedServer
> Barotrauma Dedicated Server 0.19.10.0 (ReleaseLinux, branch release, revision 811fb37ab3)
> Loading game settings
> Loading MD5 hash cache
> Initializing SteamManager
> Initializing GameScreen
> dlopen failed trying to load:
> steamclient.so
> with error:
> steamclient.so: cannot open shared object file: No such file or directory
> [S_API] SteamAPI_Init(): Loaded '/home/user/.steam/debian-installation/linux64/steamclient.so' OK.  (First tried local 'steamclient.so')
> CAppInfoCacheReadFromDiskThread took 8 milliseconds to initialize
> Setting breakpad minidump AppID = 602960
> [S_API FAIL] Tried to access Steam interface SteamNetworkingUtils003 before SteamAPI_Init succeeded.
> Selected sub: D-7 Dromedary                                                                                                   
> Selected shuttle: Hemulen                                                                                                      [10/05/2022 22:41:45]
>   Starting the server...                                                                                
> [10/05/2022 22:41:45]
>   Using Lidgren networking. Manual port forwarding may be required. If players cannot connect to the server, you may want to use the in-game hosting menu (which uses SteamP2P networking and does not require port forwarding).       
> [10/05/2022 22:41:45]
>   Server started                                                                                        
> Message type 9806 wasn't declared, but we registered job CClientJobEnableOrDisableDownloads to handle it? 
> ```
> 
> It seems like the most common issue people run into is missing config files. The wiki has good info on those here https://barotraumagame.com/wiki/Hosting_a_Dedicated_Server

uh maybe no, i ran my server for a long time, and after this update, I cannot start my server ,it only says:
[btserver@esirp ~]$ ./btserver start
[ FAIL ] Starting btserver: Unable to start Server

**Comment by esirprus** [comment] 2022-10-06 08:24
> Are you trying to run the server on your Desktop or a headless machine? You could provide the console output so the devs have some idea what is going wrong. It should look something like this. I was able to join the server without any issues.
> 
> ```
> ~/.steam/debian-installation/steamapps/common/Barotrauma$ ./DedicatedServer
> Barotrauma Dedicated Server 0.19.10.0 (ReleaseLinux, branch release, revision 811fb37ab3)
> Loading game settings
> Loading MD5 hash cache
> Initializing SteamManager
> Initializing GameScreen
> dlopen failed trying to load:
> steamclient.so
> with error:
> steamclient.so: cannot open shared object file: No such file or directory
> [S_API] SteamAPI_Init(): Loaded '/home/user/.steam/debian-installation/linux64/steamclient.so' OK.  (First tried local 'steamclient.so')
> CAppInfoCacheReadFromDiskThread took 8 milliseconds to initialize
> Setting breakpad minidump AppID = 602960
> [S_API FAIL] Tried to access Steam interface SteamNetworkingUtils003 before SteamAPI_Init succeeded.
> Selected sub: D-7 Dromedary                                                                                                   
> Selected shuttle: Hemulen                                                                                                      [10/05/2022 22:41:45]
>   Starting the server...                                                                                
> [10/05/2022 22:41:45]
>   Using Lidgren networking. Manual port forwarding may be required. If players cannot connect to the server, you may want to use the in-game hosting menu (which uses SteamP2P networking and does not require port forwarding).       
> [10/05/2022 22:41:45]
>   Server started                                                                                        
> Message type 9806 wasn't declared, but we registered job CClientJobEnableOrDisableDownloads to handle it? 
> ```
> 
> It seems like the most common issue people run into is missing config files. The wiki has good info on those here https://barotraumagame.com/wiki/Hosting_a_Dedicated_Server

uh maybe no, i ran my server for a long time, and after this update, I cannot start my server ,it only says:
[btserver@esirp ~]$ ./btserver start
[ FAIL ] Starting btserver: Unable to start Server

**Comment by esirprus** [comment] 2022-10-06 09:22
the problem is server manager

**Comment by Regalis11** [comment] 2022-10-06 10:42
By server manager, do you mean some external service or software you're using to run the server?

**Comment by esirprus** [comment] 2022-10-06 10:49
> By server manager, do you mean some external service or software you're using to run the server?

linuxGSM

**Comment by Regalis11** [comment] 2022-10-09 16:51
Duplicate of https://github.com/Regalis11/Barotrauma/issues/9689

**Closed by Regalis11** 2022-10-09 16:51 UTC
