### ISSUE TITLE
Bots directed to steer are incapable of undocking the submarine

### ISSUE THREAD

**Issue by Flotilla-zz** [Regalis11/Barotrauma#1924] opened 2019-11-30 14:24 UTC
If a bot is directed to steer the submarine at the start of the game, they will man the helm but never undock the submarine to begin steering.

v0.9.5.1
Windows 10

**Comment by Regalis11** [comment] 2019-11-30 17:35
Thank you for the report! We've actually already fixed this in our private repository (https://github.com/Regalis11/Barotrauma-development/commit/d32d22e). The fix will unfortunately not make it to the next hotfix, but will be included in one of the future updates.

**Comment by hubismal** [comment] 2019-11-30 21:43
Also a duplicate of https://github.com/Regalis11/Barotrauma/issues/1781 for clarity

**Closed** 2019-12-12 09:20 UTC
Labels: Bug, Code
