### ISSUE TITLE
No Window?

### ISSUE THREAD

**Issue by PeanutCultist** [Regalis11/Barotrauma#357] opened 2018-04-07 05:38 UTC
When I tab out of the game, [v0.8.0.5] There is no window or icon for me to press to tab back into the game. I am then stuck with the audio playing until I restart my PC.
Please help.

**Comment by Regalis11** [comment] 2018-04-07 11:56
[This is an issue in MonoGame 3.6](https://github.com/MonoGame/MonoGame/issues/5105). It has apparently been fixed, but the new version of MonoGame has not been released yet so we'd have switch to the development version to fix this bug. Which is something we'll probably look into in the next updates, because there still seems to be no estimated release date for MonoGame 3.7. But until then you should be able to work around the bug by using borderless windowed or windowed mode instead of fullscreen.

**Comment by Regalis11** [comment] 2018-04-09 22:07
Duplicate of #35

**Closed by Regalis11** 2018-04-09 22:07 UTC
Labels: Windows only, bug
