### ISSUE TITLE
Game constantly crashing when starting. 

### ISSUE THREAD

**Issue by Ivybean1** [Regalis11/Barotrauma#9324] opened 2022-06-12 09:34 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

1. installed Barotrauma through Steam
2. Started game
3. Crashed. 
4. Reinstalled. 
5. started game. 
6. crashed. 
7. Verified files 
8. started game 
9. crashed
10. ran as administrator
11. started game 
12. crashed
13. run in borderless screen mode 
14. started game
15. crashed
No mods of any kind, just got the game for the first time. 
Made sure my drivers were up to date. 

### Reproduction steps

Attached is the latest crash file. 
[crashreport_8.log](https://github.com/Regalis11/Barotrauma/files/8885558/crashreport_8.log)

### Bug prevalence

Happens every time I play

### Version

0.17.16.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Attached is my system information 
https://media.discordapp.net/attachments/636873845579710474/985444110309675048/IMG_1990.jpg?width=493&height=657
```

**Comment by Regalis11** [comment] 2022-06-12 09:37
Duplicate of https://github.com/Regalis11/Barotrauma/issues/1833

**Closed by Regalis11** 2022-06-12 09:37 UTC
