### ISSUE TITLE
Alien Ruins spawning in the middle of the path

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#4529] opened 2020-12-15 00:06 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Alien Ruins spawning in the middle of the path

**Steps To Reproduce**
Happened in level seed: Pelorus LineaThe Bucket _(campaign level so can't see in editor)_

Look for "teleport submarine cursor" command in log:
[Fresh Prototype Submarine Campaign_2020-12-14_2037.txt](https://github.com/Regalis11/Barotrauma/files/5692288/Fresh.Prototype.Submarine.Campaign_2020-12-14_2037.txt)

**Version**
 v0.11.0.9 Win10

**Additional information**
![unknown](https://user-images.githubusercontent.com/73229309/102150294-84311300-3e70-11eb-8020-b090e8c6d773.png)

**Comment by Regalis11** [comment] 2021-01-07 14:28
Do you still happen to have this save file? Since the length of the connection between locations and the shape of the submarine affect the level generation, it's difficult for us to reproduce the issue with just the level seed.

**Comment by ubertpendragon** [comment] 2021-01-11 15:51
I don't have the file any more but it seems to happen quite regularly as you can see other players posting the same bug on Discord

(just today: https://discord.com/channels/103209684680323072/426913209602146315/798180375297523782)

**Comment by Regalis11** [comment] 2021-02-02 12:37
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a7137d44c2287a6b99a00750f6047b58fd2461bb

**Comment by Rokvach** [comment] 2021-02-24 15:56
Tested, haven't been able to reproduce this. Seems to be working correctly. Closing.

**Closed by Rokvach** 2021-02-24 15:56 UTC
Labels: Bug, Code
