### ISSUE TITLE
Unable to start campaign in multiplayer with dedicated server

### ISSUE THREAD

**Issue by KeithMaxwellZ** [Regalis11/Barotrauma#8965] opened 2022-04-25 09:54 UTC
- [-] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I was planning to play with my friend by hosting my server on a VPS. 
The server seemed to start successfully. However while I joined the server and tried to start a new campaign, it stuck at waiting for the campaign to start, and after a while, this window disappeared, but I'm still in the lobby. If I try to use startgame command manually in the console, it will display the following error:
Coroutine Barotrauma.Networking.GameServer+<StartGame>d__84 threw an exception: Object reference not set to an instance of an object.

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

Mentioned in the Description

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).
Windows, Barotrauma v0.17.12.0 (ReleaseWindows, branch release, revision 2971300777)

**Additional information**

Error message:
Coroutine Barotrauma.Networking.GameServer+<StartGame>d__84 threw an exception: Object reference not set to an instance of an object.
 at Barotrauma.Networking.GameServer.StartGame(SubmarineInfo selectedSub, SubmarineInfo selectedShuttle, GameModePreset selectedMode, CampaignSettings settings)+MoveNext() in <DEV>/Barotrauma/BarotraumaServer/ServerSource/Networking/GameServer.cs:line 2092
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 196
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 229

**Comment by KeithMaxwellZ** [comment] 2022-04-26 04:31
Some additional info:
So I tried to reinstall and run the server again and turned on the debug message logging. When I tried to start a new campaign I received the following exception. 

The server failed to read an incoming message. {System.Collections.Generic.KeyNotFoundException: The given key 'None' was not present in the dictionary.

Please check the attached file for a detailed log
[btserver-console-2022-04-26-04_04_12.log](https://github.com/Regalis11/Barotrauma/files/8559795/btserver-console-2022-04-26-04_04_12.log)

Then I tried to run the server on windows, and everything seemed to be working, and I could start the campaign with no error or exception.

**Comment by Regalis11** [comment] 2022-04-26 08:20
Duplicate of https://github.com/Regalis11/Barotrauma/issues/8880

**Closed by Regalis11** 2022-04-26 08:20 UTC
