### ISSUE TITLE
flesh spike game crash

### ISSUE THREAD

**Issue by itannnn** [Regalis11/Barotrauma#6325] opened 2021-07-16 08:50 UTC
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
this shouldnt happen in a normal game but it caught my eye this happend in a kastrull wreck when i was going to destroy it i swam next to the flesh spike and i saw the middle mouse thing that made the crash 

**Steps To Reproduce**
go to a thalamus and go next to one of the flesh spike sides while run swimming underwater like in the screen shot you will see "contextual orders" open it and click on operate weapons and your game will then crash also the game will only crash when u shoote operate weapons not others ( i reccoment simply putting a flesh spike in a submarine and testing it there since atleast 1 other human/bot needs to be alive)
![image](https://user-images.githubusercontent.com/87520540/125917408-216e7cd6-a7ef-47e0-baff-c9467f1d8bf6.png)
![image](https://user-images.githubusercontent.com/87520540/125919915-d353500a-5226-497e-bf0b-e86bcbd2c897.png)

**Version**
the version was 0.14.6.0 and on windows

**Additional information**
this bug wont happen a lot but it would be annoying for ur game to crash in a long campagin mission just because u saw something (like it happend to me).

**Comment by Regalis11** [comment] 2021-07-19 07:45
Duplicate of https://github.com/Regalis11/Barotrauma/issues/6167

**Closed by Regalis11** 2021-07-19 07:45 UTC
Labels: Bug, Code, Crash
