### ISSUE TITLE
Crash: Exception: Collection was modified; enumeration operation may not execute

### ISSUE THREAD

**Issue by GregariousJB** [Regalis11/Barotrauma#8603] opened 2022-03-24 04:03 UTC
- [ ✔] I have searched the issue tracker to check if the issue has already been reported.

```Barotrauma Client crash report (generated on 3/23/2022 11:45:19 PM)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


8659A3711F68C8000283D8B52F6D422B


Game version 0.16.7.0 (ReleaseWindows, branch release, revision aa4c852c2c)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla 0.9, [VH] The Iroh, Backpacks
Level seed: Yelland LineaCorick Linea
Loaded submarine: Winterhalter (02467D9E9157F61F9E333D8498E6D612)
Selected screen: Barotrauma.RoundSummaryScreen
SteamManager initialized
Client (Round hadn't been started)


System info:
    Operating system: Microsoft Windows NT 10.0.17763.0 64 bit
    GPU name: NVIDIA GeForce GTX 1070
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: Collection was modified; enumeration operation may not execute. (System.InvalidOperationException)
Target site: Void ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
Stack trace: 
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at Barotrauma.PrefabCollection`1.GetEnumerator()+MoveNext() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Prefabs\PrefabCollection.cs:line 214
   at Barotrauma.AfflictionPrefab.get_List()+MoveNext() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\Afflictions\AfflictionPrefab.cs:line 334
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at Barotrauma.Attack.ReloadAfflictions(XElement element) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Attack.cs:line 429
   at Barotrauma.Attack..ctor(XElement element, String parentDebugName) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Attack.cs:line 358
   at Barotrauma.LevelTrigger.LoadAttack(XElement element, String parentDebugName, Boolean triggerOnce, List`1 attacks) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\LevelObjects\LevelTrigger.cs:line 328
   at Barotrauma.LevelTrigger..ctor(XElement element, Vector2 position, Single rotation, Single scale, String parentDebugName) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\LevelObjects\LevelTrigger.cs:line 283
   at Barotrauma.LevelObject..ctor(LevelObjectPrefab prefab, Vector3 position, Single scale, Single rotation) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\LevelObjects\LevelObject.cs:line 133
   at Barotrauma.LevelObjectManager.PlaceObject(LevelObjectPrefab prefab, SpawnPosition spawnPosition, Level level, Cave parentCave) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\LevelObjects\LevelObjectManager.cs:line 302
   at Barotrauma.LevelObjectManager.PlaceObjects(Level level, Int32 amount) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\LevelObjects\LevelObjectManager.cs:line 173
   at Barotrauma.Level.Generate(Boolean mirror) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\Level.cs:line 1248
   at Barotrauma.Level.Generate(LevelData levelData, Boolean mirror, SubmarineInfo startOutpost, SubmarineInfo endOutpost) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\Level.cs:line 394
   at Barotrauma.GameSession.StartRound(LevelData levelData, Boolean mirrorLevel, SubmarineInfo startOutpost, SubmarineInfo endOutpost) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 407
   at Barotrauma.CampaignMode.<>c__DisplayClass26_0.<<SelectSummaryScreen>b__0>d.MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\CampaignMode.cs:line 264
--- End of stack trace from previous location where exception was thrown ---
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 966
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59


Last debug messages:
[3/23/2022 11:44:53 PM] Not attempting to reconnect (DisconnectReason doesn't allow reconnection).
[3/23/2022 11:44:53 PM] Received a disconnect message (SteamP2PTimeOut)
[3/23/2022 11:44:52 PM] Error in Attack (LevelTrigger in lavavent2) - Affliction prefab "burn" not found.
[3/23/2022 11:44:52 PM] Couldn't find the affliction with the identifier burn referenced in Content\Map\Biomes\Common\CommonLevelObjects.xml
[3/23/2022 11:44:52 PM] Error in Attack (LevelTrigger in blacksmoker1) - Affliction prefab "burn" not found.
[3/23/2022 11:44:52 PM] Couldn't find the affliction with the identifier burn referenced in Content\Map\Biomes\Common\CommonLevelObjects.xml
[3/23/2022 11:44:52 PM] Error in Attack (LevelTrigger in lavavent2) - Affliction prefab "burn" not found.
[3/23/2022 11:44:52 PM] Couldn't find the affliction with the identifier burn referenced in Content\Map\Biomes\Common\CommonLevelObjects.xml
[3/23/2022 11:44:52 PM] Error in Attack (LevelTrigger in lavavent2) - Affliction prefab "burn" not found.
[3/23/2022 11:44:52 PM] Couldn't find the affliction with the identifier burn referenced in Content\Map\Biomes\Common\CommonLevelObjects.xml
[3/23/2022 11:44:52 PM] Error in Attack (LevelTrigger in lavavent) - Affliction prefab "burn" not found.
[3/23/2022 11:44:52 PM] Couldn't find the affliction with the identifier burn referenced in Content\Map\Biomes\Common\CommonLevelObjects.xml
[3/23/2022 11:44:52 PM] Error in Attack (LevelTrigger in lavavent2) - Affliction prefab "burn" not found.
[3/23/2022 11:44:52 PM] Couldn't find the affliction with the identifier burn referenced in Content\Map\Biomes\Common\CommonLevelObjects.xml
[3/23/2022 11:44:50 PM] Generating an outpost for the end of the level... (Location: Corick Linea Fortification, level type: LocationConnection)
[3/23/2022 11:44:30 PM] Baili
[3/23/2022 11:44:30 PM] Drakorise
[3/23/2022 11:44:30 PM] KMeeks
[3/23/2022 11:44:30 PM] wormybirdfinger
[3/23/2022 11:44:30 PM] KitKat
[3/23/2022 11:44:30 PM] blobzillatag
[3/23/2022 11:44:30 PM] Gregarius
[3/23/2022 11:44:30 PM] campingsquid
[3/23/2022 11:44:30 PM] MM. Blank
[3/23/2022 11:44:30 PM] Reignswolf
[3/23/2022 11:42:36 PM] Baili
[3/23/2022 11:42:36 PM] Drakorise
[3/23/2022 11:42:36 PM] KMeeks
[3/23/2022 11:42:36 PM] wormybirdfinger
[3/23/2022 11:42:36 PM] KitKat
[3/23/2022 11:42:36 PM] blobzillatag
[3/23/2022 11:42:36 PM] Gregarius
[3/23/2022 11:42:36 PM] campingsquid
[3/23/2022 11:42:36 PM] MM. Blank
[3/23/2022 11:42:36 PM] Reignswolf
[3/23/2022 11:24:07 PM] EvilAsh
[3/23/2022 11:24:07 PM] Baili
[3/23/2022 11:24:07 PM] Drakorise
[3/23/2022 11:24:07 PM] KMeeks
[3/23/2022 11:24:07 PM] wormybirdfinger
[3/23/2022 11:24:07 PM] KitKat
[3/23/2022 11:24:07 PM] blobzillatag
[3/23/2022 11:24:07 PM] Gregarius
[3/23/2022 11:24:07 PM] campingsquid
[3/23/2022 11:24:07 PM] MM. Blank
[3/23/2022 11:24:07 PM] Reignswolf
[3/23/2022 11:21:06 PM] EvilAsh
[3/23/2022 11:21:06 PM] Baili
[3/23/2022 11:21:06 PM] Drakorise
[3/23/2022 11:21:06 PM] KMeeks
[3/23/2022 11:21:06 PM] wormybirdfinger
[3/23/2022 11:21:06 PM] KitKat
[3/23/2022 11:21:06 PM] blobzillatag
[3/23/2022 11:21:06 PM] Gregarius
[3/23/2022 11:21:06 PM] campingsquid
[3/23/2022 11:21:06 PM] MM. Blank
[3/23/2022 11:21:06 PM] Reignswolf
[3/23/2022 11:18:43 PM] EvilAsh
[3/23/2022 11:18:43 PM] Baili
[3/23/2022 11:18:43 PM] Drakorise
[3/23/2022 11:18:43 PM] KMeeks
[3/23/2022 11:18:43 PM] wormybirdfinger
[3/23/2022 11:18:43 PM] KitKat
[3/23/2022 11:18:43 PM] blobzillatag
[3/23/2022 11:18:43 PM] Gregarius
[3/23/2022 11:18:43 PM] campingsquid
[3/23/2022 11:18:43 PM] MM. Blank
[3/23/2022 11:18:43 PM] Reignswolf
[3/23/2022 10:57:48 PM] EvilAsh
[3/23/2022 10:57:48 PM] Baili
[3/23/2022 10:57:48 PM] Drakorise
[3/23/2022 10:57:48 PM] KMeeks
[3/23/2022 10:57:48 PM] wormybirdfinger
[3/23/2022 10:57:48 PM] KitKat
[3/23/2022 10:57:48 PM] blobzillatag
[3/23/2022 10:57:48 PM] Gregarius
[3/23/2022 10:57:48 PM] campingsquid
[3/23/2022 10:57:48 PM] MM. Blank
[3/23/2022 10:57:48 PM] Reignswolf
[3/23/2022 10:57:10 PM] EvilAsh
[3/23/2022 10:57:10 PM] Baili
[3/23/2022 10:57:10 PM] Drakorise
[3/23/2022 10:57:10 PM] KMeeks
[3/23/2022 10:57:10 PM] wormybirdfinger
[3/23/2022 10:57:10 PM] KitKat
[3/23/2022 10:57:10 PM] blobzillatag
[3/23/2022 10:57:10 PM] Gregarius
[3/23/2022 10:57:10 PM] campingsquid
[3/23/2022 10:57:10 PM] MM. Blank
[3/23/2022 10:57:10 PM] Reignswolf
[3/23/2022 10:55:43 PM] EvilAsh
[3/23/2022 10:55:43 PM] Baili
[3/23/2022 10:55:43 PM] Drakorise
[3/23/2022 10:55:43 PM] KMeeks
[3/23/2022 10:55:43 PM] wormybirdfinger
[3/23/2022 10:55:43 PM] KitKat
[3/23/2022 10:55:43 PM] blobzillatag
[3/23/2022 10:55:43 PM] Gregarius
[3/23/2022 10:55:43 PM] campingsquid
[3/23/2022 10:55:43 PM] MM. Blank
[3/23/2022 10:55:43 PM] Reignswolf
[3/23/2022 10:54:00 PM] Baili
[3/23/2022 10:54:00 PM] Drakorise
[3/23/2022 10:54:00 PM] KMeeks
[3/23/2022 10:54:00 PM] wormybirdfinger
[3/23/2022 10:54:00 PM] KitKat
[3/23/2022 10:54:00 PM] blobzillatag
[3/23/2022 10:54:00 PM] Gregarius
[3/23/2022 10:54:00 PM] campingsquid
[3/23/2022 10:54:00 PM] MM. Blank
[3/23/2022 10:54:00 PM] Reignswolf
[3/23/2022 10:52:51 PM] Baili
[3/23/2022 10:52:51 PM] Drakorise
[3/23/2022 10:52:51 PM] KMeeks
[3/23/2022 10:52:51 PM] wormybirdfinger
[3/23/2022 10:52:51 PM] KitKat
[3/23/2022 10:52:51 PM] blobzillatag
[3/23/2022 10:52:51 PM] Gregarius
[3/23/2022 10:52:51 PM] campingsquid
[3/23/2022 10:52:51 PM] MM. Blank
[3/23/2022 10:52:51 PM] Reignswolf
[3/23/2022 10:52:51 PM] Baili
[3/23/2022 10:52:51 PM] Drakorise
[3/23/2022 10:52:51 PM] KMeeks
[3/23/2022 10:52:51 PM] wormybirdfinger
[3/23/2022 10:52:51 PM] KitKat
[3/23/2022 10:52:51 PM] blobzillatag
[3/23/2022 10:52:51 PM] Gregarius
[3/23/2022 10:52:51 PM] campingsquid
[3/23/2022 10:52:51 PM] MM. Blank
[3/23/2022 10:52:51 PM] Reignswolf
[3/23/2022 10:52:16 PM] Baili
[3/23/2022 10:52:16 PM] Drakorise
[3/23/2022 10:52:16 PM] KMeeks
[3/23/2022 10:52:16 PM] wormybirdfinger
[3/23/2022 10:52:16 PM] KitKat
[3/23/2022 10:52:16 PM] blobzillatag
[3/23/2022 10:52:16 PM] Gregarius
[3/23/2022 10:52:16 PM] campingsquid
[3/23/2022 10:52:16 PM] MM. Blank
[3/23/2022 10:52:16 PM] Reignswolf
[3/23/2022 10:51:50 PM] Drakorise
[3/23/2022 10:51:50 PM] KMeeks
[3/23/2022 10:51:50 PM] wormybirdfinger
[3/23/2022 10:51:50 PM] KitKat
[3/23/2022 10:51:50 PM] blobzillatag
[3/23/2022 10:51:50 PM] Gregarius
[3/23/2022 10:51:50 PM] campingsquid
[3/23/2022 10:51:50 PM] MM. Blank
[3/23/2022 10:51:50 PM] Reignswolf
[3/23/2022 10:50:35 PM] Drakorise
[3/23/2022 10:50:35 PM] KMeeks
[3/23/2022 10:50:35 PM] wormybirdfinger
[3/23/2022 10:50:35 PM] KitKat
[3/23/2022 10:50:35 PM] blobzillatag
[3/23/2022 10:50:35 PM] Gregarius
[3/23/2022 10:50:35 PM] campingsquid
[3/23/2022 10:50:35 PM] MM. Blank
[3/23/2022 10:50:35 PM] Reignswolf
[3/23/2022 10:50:35 PM] Drakorise
[3/23/2022 10:50:35 PM] KMeeks
[3/23/2022 10:50:35 PM] wormybirdfinger
[3/23/2022 10:50:35 PM] KitKat
[3/23/2022 10:50:35 PM] blobzillatag
[3/23/2022 10:50:35 PM] Gregarius
[3/23/2022 10:50:35 PM] campingsquid
[3/23/2022 10:50:35 PM] MM. Blank
[3/23/2022 10:50:35 PM] Reignswolf
[3/23/2022 10:49:31 PM] Drakorise
[3/23/2022 10:49:31 PM] KMeeks
[3/23/2022 10:49:31 PM] wormybirdfinger
[3/23/2022 10:49:31 PM] KitKat
[3/23/2022 10:49:31 PM] blobzillatag
[3/23/2022 10:49:31 PM] Gregarius
[3/23/2022 10:49:31 PM] campingsquid
[3/23/2022 10:49:31 PM] MM. Blank
[3/23/2022 10:49:31 PM] Reignswolf
[3/23/2022 10:49:29 PM] KMeeks
[3/23/2022 10:49:29 PM] wormybirdfinger
[3/23/2022 10:49:29 PM] KitKat
[3/23/2022 10:49:29 PM] blobzillatag
[3/23/2022 10:49:29 PM] Gregarius
[3/23/2022 10:49:29 PM] campingsquid
[3/23/2022 10:49:29 PM] MM. Blank
[3/23/2022 10:49:29 PM] Reignswolf
[3/23/2022 10:49:02 PM] KMeeks
[3/23/2022 10:49:02 PM] wormybirdfinger
[3/23/2022 10:49:02 PM] KitKat
[3/23/2022 10:49:02 PM] blobzillatag
[3/23/2022 10:49:02 PM] Gregarius
[3/23/2022 10:49:02 PM] campingsquid
[3/23/2022 10:49:02 PM] MM. Blank
[3/23/2022 10:49:02 PM] Reignswolf
[3/23/2022 10:49:02 PM] KMeeks
[3/23/2022 10:49:02 PM] wormybirdfinger
[3/23/2022 10:49:02 PM] KitKat
[3/23/2022 10:49:02 PM] blobzillatag
[3/23/2022 10:49:02 PM] Gregarius
[3/23/2022 10:49:02 PM] campingsquid
[3/23/2022 10:49:02 PM] MM. Blank
[3/23/2022 10:49:02 PM] Reignswolf
[3/23/2022 10:48:44 PM] KMeeks
[3/23/2022 10:48:44 PM] wormybirdfinger
[3/23/2022 10:48:44 PM] KitKat
[3/23/2022 10:48:44 PM] blobzillatag
[3/23/2022 10:48:44 PM] Gregarius
[3/23/2022 10:48:44 PM] campingsquid
[3/23/2022 10:48:44 PM] MM. Blank
[3/23/2022 10:48:44 PM] Reignswolf
[3/23/2022 10:48:16 PM] KMeeks
[3/23/2022 10:48:16 PM] wormybirdfinger
[3/23/2022 10:48:16 PM] Drakorise
[3/23/2022 10:48:16 PM] KitKat
[3/23/2022 10:48:16 PM] blobzillatag
[3/23/2022 10:48:16 PM] Gregarius
[3/23/2022 10:48:16 PM] campingsquid
[3/23/2022 10:48:16 PM] MM. Blank
[3/23/2022 10:48:16 PM] Reignswolf
[3/23/2022 10:48:16 PM] Drakorise
[3/23/2022 10:48:16 PM] KitKat
[3/23/2022 10:48:16 PM] blobzillatag
[3/23/2022 10:48:16 PM] Gregarius
[3/23/2022 10:48:16 PM] campingsquid
[3/23/2022 10:48:15 PM] MM. Blank
[3/23/2022 10:48:15 PM] Reignswolf
[3/23/2022 10:48:15 PM] Received STARTGAMEFINALIZE packet. Round init status: Started
[3/23/2022 10:48:15 PM] Received STARTGAMEFINALIZE packet. Round init status: Started
[3/23/2022 10:48:15 PM] Received STARTGAMEFINALIZE packet. Round init status: Started
[3/23/2022 10:48:15 PM] Received STARTGAMEFINALIZE packet. Round init status: Started
[3/23/2022 10:48:15 PM] Received STARTGAMEFINALIZE packet. Round init status: Started
[3/23/2022 10:48:15 PM] Received STARTGAMEFINALIZE packet. Round init status: Started
[3/23/2022 10:48:15 PM] Received STARTGAMEFINALIZE packet. Round init status: Started
[3/23/2022 10:48:15 PM] Received STARTGAMEFINALIZE packet. Round init status: Started
[3/23/2022 10:48:15 PM] Received STARTGAMEFINALIZE packet. Round init status: Started
[3/23/2022 10:48:15 PM] Received STARTGAMEFINALIZE packet. Round init status: Started
[3/23/2022 10:48:12 PM] Task count: 0
[3/23/2022 10:48:12 PM] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[3/23/2022 10:47:52 PM] Generating an outpost for the start of the level... (Location: Yelland Linea, level type: LocationConnection)
[3/23/2022 10:46:27 PM] LobbyMatchList:  LobbiesMatching: 0
[3/23/2022 10:46:27 PM] LobbyMatchList:  LobbiesMatching: 0
[3/23/2022 10:46:27 PM] SteamAPICallCompleted:   AsyncCall: 9058026602051674764
   Callback: 510
 ParamCount: 4
[3/23/2022 10:46:26 PM] LobbyMatchList:  LobbiesMatching: 9
[3/23/2022 10:46:26 PM] LobbyMatchList:  LobbiesMatching: 9
[3/23/2022 10:46:26 PM] SteamAPICallCompleted:   AsyncCall: 9651747668893801475
   Callback: 510
 ParamCount: 4
[3/23/2022 10:46:26 PM] LobbyMatchList:  LobbiesMatching: 50
[3/23/2022 10:46:26 PM] LobbyMatchList:  LobbiesMatching: 50
[3/23/2022 10:46:26 PM] SteamAPICallCompleted:   AsyncCall: 3307965539666053317
   Callback: 510
 ParamCount: 4
[3/23/2022 10:46:26 PM] AvatarImageLoaded:    SteamID: 76561198058621677
     Image: 725
      Wide: 184
      Tall: 184
[3/23/2022 10:46:26 PM] SteamRelayNetworkStatus:                      Avail: Current
 PingMeasurementInProgress: 1
        AvailNetworkConfig: Current
             AvailAnyRelay: Current
                  DebugMsg: System.Byte[]
[3/23/2022 10:45:45 PM] Generating an outpost for the start of the level... (Location: Yelland Linea, level type: LocationConnection)
[3/23/2022 10:45:44 PM] Not attempting to reconnect (DisconnectReason doesn't allow reconnection).
[3/23/2022 10:45:44 PM] Received a disconnect message (SteamP2PTimeOut)
[3/23/2022 10:45:11 PM] blobzillatag
[3/23/2022 10:45:11 PM] wormybirdfinger
[3/23/2022 10:45:11 PM] campingsquid
[3/23/2022 10:45:11 PM] Drakorise
[3/23/2022 10:45:11 PM] KMeeks
[3/23/2022 10:45:11 PM] Miss Waffle Socks
[3/23/2022 10:45:11 PM] Gregarius
[3/23/2022 10:45:11 PM] MM. Blank
[3/23/2022 10:45:11 PM] KitKat
[3/23/2022 10:45:11 PM] Reignswolf
[3/23/2022 10:42:41 PM] blobzillatag
[3/23/2022 10:42:41 PM] wormybirdfinger
[3/23/2022 10:42:41 PM] campingsquid
[3/23/2022 10:42:41 PM] Drakorise
[3/23/2022 10:42:41 PM] KMeeks
[3/23/2022 10:42:41 PM] Miss Waffle Socks
[3/23/2022 10:42:41 PM] Gregarius
[3/23/2022 10:42:41 PM] MM. Blank
[3/23/2022 10:42:41 PM] KitKat
[3/23/2022 10:42:41 PM] Reignswolf
[3/23/2022 10:41:21 PM] wormybirdfinger
[3/23/2022 10:41:21 PM] campingsquid
[3/23/2022 10:41:21 PM] Drakorise
[3/23/2022 10:41:21 PM] KMeeks
[3/23/2022 10:41:21 PM] Miss Waffle Socks
[3/23/2022 10:41:21 PM] Gregarius
[3/23/2022 10:41:21 PM] MM. Blank
[3/23/2022 10:41:21 PM] KitKat
[3/23/2022 10:41:21 PM] Reignswolf
[3/23/2022 10:41:11 PM] wormybirdfinger
[3/23/2022 10:41:11 PM] campingsquid
[3/23/2022 10:41:11 PM] Drakorise
[3/23/2022 10:41:11 PM] KMeeks
[3/23/2022 10:41:11 PM] Miss Waffle Socks
[3/23/2022 10:41:11 PM] Gregarius
[3/23/2022 10:41:11 PM] MM. Blank
[3/23/2022 10:41:11 PM] KitKat
[3/23/2022 10:41:11 PM] Reignswolf
[3/23/2022 10:40:50 PM] campingsquid
[3/23/2022 10:40:50 PM] Drakorise
[3/23/2022 10:40:50 PM] KMeeks
[3/23/2022 10:40:50 PM] Miss Waffle Socks
[3/23/2022 10:40:50 PM] Gregarius
[3/23/2022 10:40:50 PM] MM. Blank
[3/23/2022 10:40:50 PM] KitKat
[3/23/2022 10:40:50 PM] Reignswolf
[3/23/2022 10:40:48 PM] campingsquid
[3/23/2022 10:40:48 PM] Drakorise
```

**Steps To Reproduce**
Nothing specific that I can articulate. It happened on the loading screen when we loaded into a new level.

Looks similar to #7363 , #6112, #4056, #3977, etc

**Comment by Regalis11** [comment] 2022-04-06 13:37
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7373

**Comment by Regalis11** [comment] 2022-04-06 13:39
On a closer look, this might be a different issue: it seems the game disconnected from the server while loading the round, while there's no indication of a disconnection in the other ticket

**Comment by Regalis11** [comment] 2022-04-06 14:37
I think this can be reproduced as follows:
1. Start a multiplayer campaign
2. Transition to a new level
3. Wait for the game to switch to the round summary screen (happens after the game view has faded out)
4. Use the `mainmenu `console command to switch to the main menu

The resulting error message (if there is any) can vary, because it depends on what exact point of the round start method the switching happens.

**Comment by Regalis11** [comment] 2022-04-06 14:37
Potentially fixed in https://github.com/Regalis11/Barotrauma-development/pull/3254

**Comment by Rokvach** [comment] 2022-04-27 08:46
The crash hasn't appeared in GA since we released the hotfix Unstable build to the community, previously the crash was seen fairly commonly. I also wasn't able to reproduce the issue with the provided steps, so working correctly. Closing.

**Closed by Rokvach** 2022-04-27 08:46 UTC
Labels: Bug, Code, Crash, Unstable
