### ISSUE TITLE
[Unstable v0.1400.7.0] Wires from Locked connection panels can't be removed (in editor)

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#6384] opened 2021-07-30 18:45 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
 Wires connected to Locked connection panels can't be removed by pulling them out in the sub editor
 
**Steps To Reproduce**
Wire two components
Set the connection panel to "Locked"
Go in wire mode
Try removing the wire by dragging it out of the panel
Wire hangs but won't be removed

**Comment by Regalis11** [comment] 2021-08-09 13:43
Seems to have been caused by the same issue as Regalis11/Barotrauma#6367, fixed in d8677b97

**Comment by Rokvach** [comment] 2021-08-10 08:05
Tested, working correctly. Closing.

**Closed by Rokvach** 2021-08-10 08:05 UTC
Labels: Bug, Code
