### ISSUE TITLE
Bots have problems with ladders on every shuttle

### ISSUE THREAD

**Issue by WhySmau** [Regalis11/Barotrauma#8212] opened 2022-02-08 17:38 UTC
**Description**
Bots cant climb up (Hemulen/Selkie/Venture) or down (Selkie/Venture) on the ladders of the shuttles because they are offset on all shuttles

![Näyttökuva (1005)](https://user-images.githubusercontent.com/86321358/153043912-57ab8af5-ae9c-467e-87ed-66883de54653.png)

![Näyttökuva (1006)](https://user-images.githubusercontent.com/86321358/153043927-20f0de09-8e47-4d4e-ad65-f0d3b6137af0.png)

![Näyttökuva (1007)](https://user-images.githubusercontent.com/86321358/153044036-6c29268c-758c-4b56-8acc-ba81126d502e.png)

v0.15.23.0

**Comment by Regalis11** [comment] 2022-02-09 08:39
Thank you for the report! Turns out this wasn't caused by the ladders being offset (they're close enough for the bots to move between them), but a pathfinding issue caused by the shuttle blocking the waypoints on the ladder.

Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e19290a878347934215080531617e235a4744f62

**Comment by Rokvach** [comment] 2022-02-10 16:12
Tested, working correctly. Closing.

**Closed by Rokvach** 2022-02-10 16:12 UTC
Labels: Bug, Code
