### ISSUE TITLE
Multiplayer - Submarine Walls that were completely destroyed and passable loses line of sight and passability when the next level loads.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#7591] opened 2021-12-03 15:31 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In multiplayer for example if you cut down the walls in a submarine like Remora (popular cutting spots are the walls in medbay and fab room), you can see across and pass through them just fine for the session you cut them. Once the next level or outpost load, the walls are still destroyed, but you can't see behind or walk through it anymore 

**Version**
~0.15.16.0

**Comment by Regalis11** [comment] 2021-12-07 13:35
I unfortunately couldn't reproduce this. Tested by cutting a hole in this spot in Humpback:
![image](https://user-images.githubusercontent.com/14351070/145038402-95294efc-f569-4945-bce4-5e3c03d55841.png)

After leaving the outpost, the hole is still there:
![image](https://user-images.githubusercontent.com/14351070/145038581-97f845b2-6d07-4e85-bbfe-3a86e6188177.png)

**Comment by Regalis11** [comment] 2021-12-07 13:38
Another test in Remora, still no luck :/
![image](https://user-images.githubusercontent.com/14351070/145039039-a9cb4875-95dc-4bf2-a556-d35c6a28f9ce.png)
![image](https://user-images.githubusercontent.com/14351070/145039230-00cff510-0d89-4129-95fe-5a56e615e47a.png)

**Comment by Regalis11** [comment] 2022-01-18 08:44
No known steps to repro, closing

**Closed by Regalis11** 2022-01-18 08:44 UTC
Labels: Bug, Need more info, Code, Networking
