### ISSUE TITLE
Dropping a metal crate makes world uninteractable

### ISSUE THREAD

**Issue by moxian** [Regalis11/Barotrauma#5665] opened 2021-04-30 18:02 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When i pick up a metal crate with items, and then drop it, i become unable to interact with anything in the world (open doors, open lockers, pick up items, screwdriver lamps etc). Switching to a different character (in single player) and back helps restore the game.

**Steps To Reproduce**
Can't provide anything more specific than the above description and the following video demonstrating the issue: <https://streamable.com/x9b2wc>. Upon save and reload the issue was no longer reproducible.

**Version**
0.13.3.11, Windows

**Comment by frijoles108** [comment] 2021-05-02 21:23
I have experienced same issue, in multiplayer campaign. I have to equip and then unequip a number of random items in my inventory to be able to interact again. Like OP, its when I handle crates. Difficult to reproduce issue.

**Comment by moxian** [comment] 2021-05-05 07:20
To add *a bit* more context for the unlikely case it's useful (and assuming my memory of the events is correct): the last thing i was doing before the bug occurred was moving items from a storage container (? the steel briefcase thingy) directly into the crate (have container in hand, have crate on the floor, drag and drop items from the grid into the crate).
I then dropped the storage container on the floor and picked up the crate. Got bugged.

**Comment by Regalis11** [comment] 2021-05-26 14:20
I think I managed to find the cause and fix this now (https://github.com/Regalis11/Barotrauma-development/commit/352939e6ac378214c9c3fbcf2b5842b36b8824f2).

I believe this happened because the reference to the item's highlighted inventory slot wasn't cleared when the item was dropped, and when the item's inventory was no longer visible, the inventory hover area was calculated incorrectly (encompassing the area from the inventory slot the item was in to the position where the itm's inventory had been dragged). See the pic: basically, the entire red area would be considered an inventory area that'd block highlighting items/characters behind it.

![image](https://user-images.githubusercontent.com/14351070/119676363-797aa100-be46-11eb-865c-4f5ec48ea733.png)

**Comment by Lithosagym** [comment] 2021-06-03 22:27
Tested, the issue of the containers making the area on it uninteractable confirmed fixed.

**Comment by Rokvach** [comment] 2021-06-04 01:04
Closing.

**Closed by Rokvach** 2021-06-04 01:04 UTC
Labels: Bug, Code
