### ISSUE TITLE
Unstable - Multiplayer Campaign showing duplicate Save (and problem when playing wrong one)

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2313] opened 2020-02-15 16:03 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
While playing an ongoing multiplayer campaign, when you check the Load Save tab, you will now see two duplicate Save. If you load the "fake" save and play it, your campaign progress will not be saved after you finished playing, as the save gets discarded or something.

**Steps To Reproduce**
Start a multiplayer campaign. Play one round. At the lobby, check the Load Save tab.

**Version**
~0.9.7R

**Additional Informations**
Characterdata.xml does save properly.

**Comment by Regalis11** [comment] 2020-04-22 11:40
Could not reproduce anymore in v0.9.9.0, seems to have been fixed somewhere along the way. Moving to Review/QA

**Comment by Rokvach** [comment] 2020-04-22 11:44
I do remember this issue, which most likely means that it has been fixed already. At least not present in current version. Closing.

**Closed by Rokvach** 2020-04-22 11:44 UTC
Labels: Bug, Code, Networking
