### ISSUE TITLE
Escort NPCs leaving the sub (passengers leaving Camel)

### ISSUE THREAD

**Issue by Fachoj** [Regalis11/Barotrauma#13187] opened 2023-12-18 07:43 UTC
Our round with 1 moloch hunt, 2 passangers groups and Mudraptor nest.
After restart of round behaviour of passangers dont change(they still very eager to leave sub).
If there a lot water in room where passanger is , they likely to run in airlock and leave.(i also added motion detector to dock port aka makeshift airlock, anyway passangers using both exits).
No mods. Winter update.

**Comment by Regalis11** [comment] 2023-12-18 09:36
Thank you for the report! Which submarine are you using and which escort mission is this?

**Comment by Fachoj** [comment] 2023-12-18 18:48
Separatists and usual one

**Comment by SomeRandomNoobKekeke** [comment] 2023-12-19 03:18
Also happened to me, but i couldn't reproduce and don't have save file
With separatists transport on orca 1
I was the only crewmember, i went mining for 1 min, ship was on autopilot, had power and no monsters was nearby
But when i returned they all was outside without suits

also there's some post on reddit with i guess same issue
https://www.reddit.com/r/Barotrauma/comments/18leyhs/why_do_my_passangers_leave_the_submarine/

**Comment by Fachoj** [comment] 2023-12-19 19:15
in first try we killed moloch - 1 passanger leave throgh upper makeshift airlock.
on second we killed moloch and land Camel on rocks - 2 passangers leaved sub throgh bottom airlock and was stopped by floor. Security(Player)- kicked them with stunbatons and taked they into sub with handcuffs. 
Passangers isnt tryed leave without suit-on(we removed suits and maked order to ignore items).

**Comment by Rokvach** [comment] 2024-01-09 09:38
Tested, working correctly. Can be merged and closed. 

Compared to the current stable build and noticed that instead of separatists just heading outside the sub as soon as they can and just swim away from the submarine, now they only end up outside if they are actively attacking a creature and follows that creature outside and even when they do happen to leave the sub they will swim back to the sub through the airlock. Only had this happen once during my tests and I think that only happened because a creature attacked the separatist bot and pushed them outside.

**Closed** 2024-01-09 10:02 UTC
Labels: Bug, Code
