### ISSUE TITLE
Wreckless logbook (failed to place a wreck in the level)

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5763] opened 2021-05-12 02:11 UTC
- [ yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The mission's logbook spawned on top of a level wall with no wreck, here's the save with the issue.
[wrecklesslogbook.zip](https://github.com/Regalis11/Barotrauma/files/6462959/wrecklesslogbook.zip)

**Version**
Unstable v0.1400.0.0

**Comment by Regalis11** [comment] 2021-05-14 08:28
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c7c78a713f1d40f873e9fa91069110b328e705b8

**Comment by Rokvach** [comment] 2021-05-26 08:00
Tested, wasn't able to reproduce, seems to be working correctly. Closing.

**Closed by Rokvach** 2021-05-26 08:00 UTC
Labels: Bug, Code

**Comment by LePiromano** [comment] 2021-06-17 12:51
happened again
[dietznutz.zip](https://github.com/Regalis11/Barotrauma/files/6670276/dietznutz.zip)
