### ISSUE TITLE
Logbook still does not keep their text

### ISSUE THREAD

**Issue by nandoffg** [Regalis11/Barotrauma#4240] opened 2020-11-06 20:37 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported. It has but the fix doesn't seem to be working.

**Description**
Apparently Logbooks still don't carry over the text on them when you finish a mission and follow throught the next one.

**Steps To Reproduce**
Create a Logbook item in the editor and place a built-in text of any sort that will appear to the player when they select the item. Save it in an assembly and place inside a container. When you first pick the submarine and load into it the text appears correctly in the item screen, when a character picks it up and selects it on their hotbar. But then, when you complete a mission and go to the next one, the text is gone. (Even if the item is in possesion of a character or stored in a container).

**Version**
0.10.6.2 - Windows

**Additional information**
I used this item to generate a set of instructions for a "coding system" for the terminal in my sub mod.
Would be nice to have the text built into the item to carry over through the next Missions.

**Comment by Xeavas** [comment] 2020-11-06 22:24
It's fixed in 0.1100.0.4

**Comment by Regalis11** [comment] 2020-11-07 09:25
Duplicate of https://github.com/Regalis11/Barotrauma/issues/4082

**Closed by Regalis11** 2020-11-07 09:25 UTC
