### ISSUE TITLE
Crash report (multiple crashes, multiple errors)

### ISSUE THREAD

**Issue by SomeKittens** [Regalis11/Barotrauma#10881] opened 2023-01-06 02:06 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Three attempts to play a campaign mission, all crashed but in slightly different ways.  First crash sent me back to the multiplayer server browser, restarted the server with the same file, crashed to Windows, restarted game, crashed to Windows.

All crashes happened early on in the mission (~5 minutes in, wasn't timing)

### Reproduction steps

1) Start mission
2) Enjoy yourself
3) Find disappointment as the server crashes
4) Find some mirth as your submarine crashed because `Pipe is broken`

### Bug prevalence

Happens regularly

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
# Crash 1


Barotrauma Client crash report (generated on 01/01/2023 20:29:13)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

B5C3AB2BBD7769A420A018E6898F0875

Game version 0.20.16.1 (ReleaseWindows, branch release, revision 33a42adf77)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla
Level seed: TopolPelagon Linea
Loaded submarine: Orca (27CC58EBCE892D1A235DD33C6219D381)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)

System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce GTX 1080
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: readStream was disconnected unexpectedly (System.Exception)
Target site: Void CheckPipeConnected(System.String, System.IO.Pipes.AnonymousPipeServerStream)
Stack trace: 
   at Barotrauma.Networking.ChildServerRelay.CheckPipeConnected(String name, AnonymousPipeServerStream pipe) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 164
   at Barotrauma.Networking.ChildServerRelay.UpdateRead() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 175
   at System.Threading.Thread.StartCallback()

Last debug messages:
[01/01/2023 20:14:10] ladybuglily
[01/01/2023 20:14:10] Teh_Bucket
[01/01/2023 20:14:10] M.D. Device
[01/01/2023 20:14:10] HTML5 Super Computer
[01/01/2023 20:14:10] MuchDev2018
[01/01/2023 20:13:56] ladybuglily
[01/01/2023 20:13:56] Teh_Bucket
[01/01/2023 20:13:56] M.D. Device
[01/01/2023 20:13:56] HTML5 Super Computer
[01/01/2023 20:13:56] MuchDev2018
[01/01/2023 20:13:54] ladybuglily
[01/01/2023 20:13:54] Teh_Bucket
[01/01/2023 20:13:54] M.D. Device
[01/01/2023 20:13:54] HTML5 Super Computer
[01/01/2023 20:13:54] MuchDev2018
[01/01/2023 20:13:41] Server running slowly (56 updates/s)!
[01/01/2023 20:13:40] ladybuglily
[01/01/2023 20:13:40] Teh_Bucket
[01/01/2023 20:13:40] M.D. Device
[01/01/2023 20:13:40] HTML5 Super Computer
[01/01/2023 20:13:40] MuchDev2018
[01/01/2023 20:13:38] ladybuglily
[01/01/2023 20:13:38] Teh_Bucket
[01/01/2023 20:13:38] M.D. Device
[01/01/2023 20:13:38] HTML5 Super Computer
[01/01/2023 20:13:38] MuchDev2018
[01/01/2023 20:13:37] Received STARTGAMEFINALIZE packet. Round init status: Started
[01/01/2023 20:13:34] Task count: 0
[01/01/2023 20:13:34] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[01/01/2023 20:13:31] Generating an outpost for the start of the level... (Location: Pelagon Linea Habitation Outpost, level type: LocationConnection)
[01/01/2023 20:13:31] Level identifier: ridgebasic
[01/01/2023 18:53:49] Server running slowly (57 updates/s)!
[01/01/2023 18:53:47] Teh_Bucket
[01/01/2023 18:53:47] M.D. Device
[01/01/2023 18:15:46] Server running slowly (57 updates/s)!
[01/01/2023 18:15:44] Teh_Bucket
[01/01/2023 18:15:44] M.D. Device
[01/01/2023 18:15:44] Teh_Bucket
[01/01/2023 18:15:44] M.D. Device
[01/01/2023 18:15:42] Received STARTGAMEFINALIZE packet. Round init status: Started
[01/01/2023 18:15:39] Task count: 0
[01/01/2023 18:15:39] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[01/01/2023 18:15:36] Generating an outpost for the start of the level... (Location: Pelagon Linea Habitation Outpost, level type: LocationConnection)
[01/01/2023 18:15:36] Level identifier: ridgebasic
[01/01/2023 18:14:19] Server running slowly (57 updates/s)!
[01/01/2023 18:14:09] Teh_Bucket
[01/01/2023 18:14:09] M.D. Device
[01/01/2023 17:19:56] Server running slowly (57 updates/s)!
[01/01/2023 17:19:54] Teh_Bucket
[01/01/2023 17:19:54] M.D. Device
[01/01/2023 17:19:54] Teh_Bucket
[01/01/2023 17:19:54] M.D. Device
[01/01/2023 17:19:52] Received STARTGAMEFINALIZE packet. Round init status: Started
[01/01/2023 17:19:49] Task count: 0
[01/01/2023 17:19:49] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[01/01/2023 17:19:46] Generating an outpost for the start of the level... (Location: Pelagon Linea Habitation Outpost, level type: LocationConnection)
[01/01/2023 17:19:46] Level identifier: ridgebasic
[01/01/2023 17:19:24] Server running slowly (57 updates/s)!
[01/01/2023 17:19:23] Teh_Bucket
[01/01/2023 17:19:23] M.D. Device
[01/01/2023 17:12:31] Teh_Bucket
[01/01/2023 17:12:31] M.D. Device
[01/01/2023 17:12:29] Server running slowly (57 updates/s)!
[01/01/2023 17:12:29] Received STARTGAMEFINALIZE packet. Round init status: Started
[01/01/2023 17:12:26] Task count: 0
[01/01/2023 17:12:26] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[01/01/2023 17:12:21] Could not find a suitable module for the location type LocationType (None). Module flag: Airlock.
[01/01/2023 17:12:21] Generating an outpost for the start of the level... (Location: Topol, level type: LocationConnection)
[01/01/2023 17:12:21] Level identifier: ridgebasic
[01/01/2023 17:12:14] Teh_Bucket
[01/01/2023 17:12:14] M.D. Device
[01/01/2023 17:12:13] Teh_Bucket
[01/01/2023 17:12:13] M.D. Device
[01/01/2023 16:54:55] Teh_Bucket
[01/01/2023 16:54:55] M.D. Device
[01/01/2023 16:54:53] Received STARTGAMEFINALIZE packet. Round init status: Started
[01/01/2023 16:54:53] Task count: 0
[01/01/2023 16:54:53] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[01/01/2023 16:54:51] Generating an outpost for the start of the level... (Location: Pelagon Linea Habitation Outpost, level type: Outpost)
[01/01/2023 16:54:51] Level identifier: outpostlevel
[01/01/2023 16:54:44] Teh_Bucket
[01/01/2023 16:54:44] M.D. Device
[01/01/2023 16:54:43] Teh_Bucket
[01/01/2023 16:54:43] M.D. Device
[01/01/2023 16:16:40] Teh_Bucket
[01/01/2023 16:16:40] M.D. Device
[01/01/2023 16:13:15] WARNING: Received a potentially invalid ENTITY_POSITION message.Entity identifier does not match (server entity is smallcrawleregg, client entity is coilgunbolt). Ignoring the message...
[01/01/2023 16:13:03] WARNING: Received a potentially invalid ENTITY_POSITION message.Entity identifier does not match (server entity is smallcrawleregg, client entity is coilgunbolt). Ignoring the message...
[01/01/2023 16:12:59] WARNING: Received a potentially invalid ENTITY_POSITION message.Entity identifier does not match (server entity is smallcrawleregg, client entity is coilgunbolt). Ignoring the message...
[01/01/2023 16:12:59] WARNING: Received a potentially invalid ENTITY_POSITION message.Entity identifier does not match (server entity is smallcrawleregg, client entity is coilgunbolt). Ignoring the message...
[01/01/2023 16:12:57] WARNING: Received a potentially invalid ENTITY_POSITION message.Entity identifier does not match (server entity is smallcrawleregg, client entity is coilgunbolt). Ignoring the message...
[01/01/2023 16:12:51] WARNING: Received a potentially invalid ENTITY_POSITION message.Entity identifier does not match (server entity is smallcrawleregg, client entity is coilgunbolt). Ignoring the message...
[01/01/2023 16:12:51] WARNING: Received a potentially invalid ENTITY_POSITION message.Entity identifier does not match (server entity is smallcrawleregg, client entity is coilgunbolt). Ignoring the message...
[01/01/2023 16:12:50] WARNING: Received a potentially invalid ENTITY_POSITION message.Entity identifier does not match (server entity is smallcrawleregg, client entity is coilgunbolt). Ignoring the message...
[01/01/2023 16:03:09] Server running slowly (57 updates/s)!
[01/01/2023 16:03:09] Crusty
[01/01/2023 16:03:09] Teh_Bucket
[01/01/2023 16:03:09] M.D. Device
[01/01/2023 16:03:09] Crusty
[01/01/2023 16:03:09] Teh_Bucket
[01/01/2023 16:03:09] M.D. Device
[01/01/2023 16:03:07] Received STARTGAMEFINALIZE packet. Round init status: Started
[01/01/2023 16:03:06] Received STARTGAMEFINALIZE packet. Round init status: Started
[01/01/2023 16:03:04] Task count: 0
[01/01/2023 16:03:04] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[01/01/2023 16:03:01] Generating an outpost for the end of the level... (Location: Pelagon Linea Habitation Outpost, level type: LocationConnection)
[01/01/2023 16:03:00] Generating an outpost for the start of the level... (Location: Gerra, level type: LocationConnection)
[01/01/2023 16:03:00] Level identifier: coldcavernstransition
[01/01/2023 16:02:54] Crusty
[01/01/2023 16:02:54] Teh_Bucket
[01/01/2023 16:02:54] M.D. Device
[01/01/2023 16:02:53] Crusty
[01/01/2023 16:02:53] Teh_Bucket
[01/01/2023 16:02:53] M.D. Device
[01/01/2023 16:02:52] Crusty
[01/01/2023 16:02:52] Teh_Bucket
[01/01/2023 16:02:52] M.D. Device
[01/01/2023 16:02:52] Server running slowly (56 updates/s)!
[01/01/2023 15:56:46] Crusty
[01/01/2023 15:56:46] Teh_Bucket
[01/01/2023 15:56:45] M.D. Device
[01/01/2023 15:56:43] Received STARTGAMEFINALIZE packet. Round init status: Started
[01/01/2023 15:56:43] Task count: 0
[01/01/2023 15:56:43] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[01/01/2023 15:56:40] Generating an outpost for the start of the level... (Location: Gerra, level type: Outpost)
[01/01/2023 15:56:40] Level identifier: outpostlevel
[01/01/2023 15:56:33] Crusty
[01/01/2023 15:56:33] Teh_Bucket
[01/01/2023 15:56:33] M.D. Device
[01/01/2023 15:56:33] Crusty
[01/01/2023 15:56:33] Teh_Bucket
[01/01/2023 15:56:33] M.D. Device
[01/01/2023 15:56:32] Crusty
[01/01/2023 15:56:32] Teh_Bucket
[01/01/2023 15:56:32] M.D. Device
[01/01/2023 15:44:11] Crusty
[01/01/2023 15:44:11] Teh_Bucket
[01/01/2023 15:44:11] M.D. Device
[01/01/2023 15:44:09] Crusty
[01/01/2023 15:44:09] Teh_Bucket
[01/01/2023 15:44:09] M.D. Device
[01/01/2023 15:44:09] Server running slowly (57 updates/s)!
[01/01/2023 15:44:07] Received STARTGAMEFINALIZE packet. Round init status: Started
[01/01/2023 15:44:05] Task count: 0
[01/01/2023 15:44:05] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[01/01/2023 15:44:01] Generating an outpost for the start of the level... (Location: Gerra, level type: LocationConnection)
[01/01/2023 15:44:00] Generating an outpost for the end of the level... (Location: Pelagon Linea Habitation Outpost, level type: LocationConnection)
[01/01/2023 15:44:00] Level identifier: coldcavernstransition
[01/01/2023 15:43:53] Crusty
[01/01/2023 15:43:53] Teh_Bucket
[01/01/2023 15:43:53] M.D. Device
[01/01/2023 15:43:53] Crusty
[01/01/2023 15:43:53] Teh_Bucket
[01/01/2023 15:43:53] M.D. Device
[01/01/2023 15:43:52] Crusty
[01/01/2023 15:43:52] Teh_Bucket
[01/01/2023 15:43:52] M.D. Device
[01/01/2023 15:38:28] Crusty
[01/01/2023 15:38:28] Teh_Bucket
[01/01/2023 15:38:28] M.D. Device
[01/01/2023 15:38:27] Crusty
[01/01/2023 15:38:27] Teh_Bucket
[01/01/2023 15:38:27] M.D. Device
[01/01/2023 15:38:26] Server running slowly (57 updates/s)!
[01/01/2023 15:38:24] Received STARTGAMEFINALIZE packet. Round init status: Started
[01/01/2023 15:38:24] Task count: 0
[01/01/2023 15:38:24] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[01/01/2023 15:38:20] Generating an outpost for the start of the level... (Location: Pelagon Linea Habitation Outpost, level type: Outpost)
[01/01/2023 15:38:20] Level identifier: outpostlevel
[01/01/2023 15:27:02] Lobby created!
[01/01/2023 15:26:00] Attempting to open ALC device "OpenAL Soft on Speakers (High Definition Audio Device)"
[01/01/2023 15:25:54] Logged in as SomeKittens (SteamID STEAM_1:0:19006556)
```

# Crash 2

```
Barotrauma Client crash report (generated on 01/05/2023 20:49:49)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

B5C3AB2BBD7769A420A018E6898F0875

Game version 0.20.16.1 (ReleaseWindows, branch release, revision 33a42adf77)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla
Level seed: DankCastalia Macula
Loaded submarine: Humpback (A3142F7B7254A3085A39D8215E4A7980)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)

System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce GTX 1080
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: readStream was disconnected unexpectedly (System.Exception)
Target site: Void CheckPipeConnected(System.String, System.IO.Pipes.AnonymousPipeServerStream)
Stack trace: 
   at Barotrauma.Networking.ChildServerRelay.CheckPipeConnected(String name, AnonymousPipeServerStream pipe) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 164
   at Barotrauma.Networking.ChildServerRelay.UpdateRead() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 175

Last debug messages:
[01/05/2023 20:41:37] Teh_Bucket
[01/05/2023 20:41:37] HTML5 Super Computer
[01/05/2023 20:41:37] M.D. Device
[01/05/2023 20:41:33] Server running slowly (54 updates/s)!
[01/05/2023 20:41:30] Teh_Bucket
[01/05/2023 20:41:30] HTML5 Super Computer
[01/05/2023 20:41:30] M.D. Device
[01/05/2023 20:41:30] Teh_Bucket
[01/05/2023 20:41:30] HTML5 Super Computer
[01/05/2023 20:41:28] M.D. Device
[01/05/2023 20:41:27] Received STARTGAMEFINALIZE packet. Round init status: Started
[01/05/2023 20:41:27] Received STARTGAMEFINALIZE packet. Round init status: Started
[01/05/2023 20:41:25]  -0: LobbyQuery.RequestAsync (1), WaitingForActivation
[01/05/2023 20:41:25] Task count: 1
[01/05/2023 20:41:25] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[01/05/2023 20:41:21] Generating an outpost for the end of the level... (Location: Castalia Macula Outpost, level type: LocationConnection)
[01/05/2023 20:41:20] Generating an outpost for the start of the level... (Location: Dank City, level type: LocationConnection)
[01/05/2023 20:41:20] Level identifier: ridgebasic
[01/05/2023 20:40:32] Lobby created!
[01/05/2023 20:39:57] WARNING: Tried to restore enabled packages multiple times/without performing a backup
[01/05/2023 20:39:57] Error while reading a message from server. 
Exception thrown while reading segment EntityEvent at position 16.
Inner exception: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at Barotrauma.Item.ClientEventRead(IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 1404
   at Barotrauma.Networking.ClientEntityEventManager.Read(ServerNetSegment type, IReadMessage msg, Single sendingTime, List`1 entities) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\NetEntityEvent\ClientEntityEventManager.cs:line 221
   at Barotrauma.Networking.GameClient.<>c__DisplayClass116_0.<ReadIngameUpdate>b__0(ServerNetSegment segment, IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2127
   at Barotrauma.Networking.SegmentTableReader`1.Read(IReadMessage msg, SegmentDataReader segmentDataReader, ExceptionHandler exceptionHandler) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SegmentTable.cs:line 302
[01/05/2023 20:33:36] Teh_Bucket
[01/05/2023 20:33:36] HTML5 Super Computer
[01/05/2023 20:33:36] M.D. Device
[01/05/2023 20:33:28] Teh_Bucket
[01/05/2023 20:33:28] HTML5 Super Computer
[01/05/2023 20:33:26] M.D. Device
[01/05/2023 20:33:25] Received STARTGAMEFINALIZE packet. Round init status: Started
[01/05/2023 20:33:25] Server running slowly (55 updates/s)!
[01/05/2023 20:33:22] Task count: 0
[01/05/2023 20:33:22] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[01/05/2023 20:33:16] Generating an outpost for the end of the level... (Location: Castalia Macula Outpost, level type: LocationConnection)
[01/05/2023 20:33:16] Generating an outpost for the start of the level... (Location: Dank City, level type: LocationConnection)
[01/05/2023 20:33:15] Level identifier: ridgebasic
[01/05/2023 20:33:15] Error while loading component of the type Barotrauma.Items.Components.ItemContainer. {Collection was modified; enumeration operation may not execute.}
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Barotrauma.GUICanvas.OnChildrenChanged(RectTransform _) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUICanvas.cs:line 47
   at Barotrauma.RectTransform.Load(XElement element, RectTransform parent, Anchor defaultAnchor) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\RectTransform.cs:line 420
   at Barotrauma.Items.Components.ItemComponent.ReloadGuiFrame() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\ItemComponent.cs:line 581
   at Barotrauma.Items.Components.ItemComponent.LoadElemProjSpecific(ContentXElement subElement) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\ItemComponent.cs:line 546
   at Barotrauma.Items.Components.ItemComponent..ctor(Item item, ContentXElement element) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\ItemComponent.cs:line 381
   at Barotrauma.Items.Components.ItemContainer..ctor(Item item, ContentXElement element) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\ItemContainer.cs:line 249
[01/05/2023 20:33:08] Teh_Bucket
[01/05/2023 20:33:08] HTML5 Super Computer
[01/05/2023 20:33:08] M.D. Device
[01/05/2023 20:33:06] Teh_Bucket
[01/05/2023 20:33:06] HTML5 Super Computer
[01/05/2023 20:33:06] M.D. Device
[01/05/2023 20:29:26] Teh_Bucket
[01/05/2023 20:29:26] HTML5 Super Computer
[01/05/2023 20:29:26] M.D. Device
[01/05/2023 20:26:32] M.D. Device
[01/05/2023 20:26:11] M.D. Device
[01/05/2023 20:26:10] M.D. Device
[01/05/2023 20:26:10] M.D. Device
[01/05/2023 20:26:10] M.D. Device
[01/05/2023 20:24:25] M.D. Device
[01/05/2023 20:23:29] M.D. Device
[01/05/2023 20:23:27] M.D. Device
[01/05/2023 20:23:27] M.D. Device
[01/05/2023 20:23:27] M.D. Device
[01/05/2023 20:23:24] M.D. Device
[01/05/2023 20:23:23] Server running slowly (58 updates/s)!
[01/05/2023 20:23:21] Received STARTGAMEFINALIZE packet. Round init status: Started
[01/05/2023 20:23:20] Task count: 0
[01/05/2023 20:23:20] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[01/05/2023 20:23:14] Generating an outpost for the start of the level... (Location: Dank City, level type: Outpost)
[01/05/2023 20:23:13] Level identifier: outpostlevel
[01/05/2023 20:16:50] Lobby created!
[01/05/2023 20:14:55] Attempting to open ALC device "OpenAL Soft on Speakers (High Definition Audio Device)"
[01/05/2023 20:14:53] Logged in as SomeKittens (SteamID STEAM_1:0:19006556)
```

# Crash 3

```
Barotrauma Client crash report (generated on 01/05/2023 20:53:12)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

B5C3AB2BBD7769A420A018E6898F0875

Game version 0.20.16.1 (ReleaseWindows, branch release, revision 33a42adf77)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla
Level seed: DankCastalia Macula
Loaded submarine: Humpback (A3142F7B7254A3085A39D8215E4A7980)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)

System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce GTX 1080
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Pipe is broken. (System.IO.IOException)
Target site: Void WriteCore(System.ReadOnlySpan`1[System.Byte])
Stack trace: 
   at System.IO.Pipes.PipeStream.WriteCore(ReadOnlySpan`1 buffer)
   at Barotrauma.Networking.ChildServerRelay.<UpdateWrite>g__writeMsg|44_0(WriteStatus writeStatus, Byte[] msg) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 265
   at Barotrauma.Networking.ChildServerRelay.UpdateWrite() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 281
   at System.Threading.Thread.StartCallback()

Last debug messages:
[01/05/2023 20:53:12] Exiting...
[01/05/2023 20:52:09] Teh_Bucket
[01/05/2023 20:52:09] HTML5 Super Computer
[01/05/2023 20:52:09] M.D. Device
[01/05/2023 20:52:08] Teh_Bucket
[01/05/2023 20:52:08] HTML5 Super Computer
[01/05/2023 20:52:08] M.D. Device
[01/05/2023 20:52:06] M.D. Device
[01/05/2023 20:52:05] Server running slowly (54 updates/s)!
[01/05/2023 20:52:04] Received STARTGAMEFINALIZE packet. Round init status: Started
[01/05/2023 20:52:01] Task count: 0
[01/05/2023 20:52:01] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[01/05/2023 20:51:55] Generating an outpost for the end of the level... (Location: Castalia Macula Outpost, level type: LocationConnection)
[01/05/2023 20:51:52] Generating an outpost for the start of the level... (Location: Dank City, level type: LocationConnection)
[01/05/2023 20:51:52] Level identifier: ridgebasic
[01/05/2023 20:50:59] Lobby created!
[01/05/2023 20:50:13] Attempting to open ALC device "OpenAL Soft on Speakers (High Definition Audio Device)"
[01/05/2023 20:50:11] Logged in as SomeKittens (SteamID STEAM_1:0:19006556)
```
```

**Comment by SomeKittens** [comment] 2023-01-06 02:07
Here's the save file:

[Barotrauma save.zip](https://github.com/Regalis11/Barotrauma/files/10356816/Barotrauma.save.zip)

**Comment by Wheatley1001** [comment] 2023-01-28 04:29
Had Crash 3 appear in 100.17.0.0. Here's my crash log:
```

Barotrauma Dedicated Server crash report (generated on 01/27/2023 23:14:52)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


Game version 100.17.0.0 (UnstableWindows, branch feature/fullrelease-testing, revision cb10ee63e3)
Language: English
Selected content packages: Vanilla, Fury, LETOHSS, Rex Malleus-Caput, SS HOTEL V.2, STVR, The Honked Mother, Typhon3, RVTS-Class, Sirens Violin, Sailor 4, The Schism, Mazara, Tadpole Trader, Medusa, [RH] Barrisk Campaign, [RH] Bivot Tier 3 Campaign
Level seed: Hadal Crevasse31Arid Troma47
Loaded submarine: Winterhalter (8DBD6E97C778C6852D65E6C9B3D889B3)
Selected screen: Barotrauma.GameScreen
Server (Round had started)


System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit


Exception: Pipe is broken. (System.IO.IOException)
Target site: Void WriteCore(System.ReadOnlySpan`1[System.Byte])
Stack trace: 
   at System.IO.Pipes.PipeStream.WriteCore(ReadOnlySpan`1 buffer)
   at Barotrauma.Networking.ChildServerRelay.<UpdateWrite>g__writeMsg|27_0(WriteStatus writeStatus, Byte[] msg) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 265
   at Barotrauma.Networking.ChildServerRelay.UpdateWrite() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 281
   at System.Threading.Thread.StartCallback()


Last debug messages:
   01/27/2023 23:14:52 - [01/27/2023 23:14:52]
  Saving banlist
   01/27/2023 23:14:52 - [01/27/2023 23:14:52]
  Hawkins threw Fixfoam Grenade
   01/27/2023 23:14:51 - [01/27/2023 23:14:51]
  Rehex placed Blue Wire in Supplies Cabinet (ID: 2075)
   01/27/2023 23:14:51 - [01/27/2023 23:14:51]
  Rehex placed Blue Wire in Supplies Cabinet (ID: 2075)
   01/27/2023 23:14:51 - [01/27/2023 23:14:51]
  Rehex placed Blue Wire in Supplies Cabinet (ID: 2075)
   01/27/2023 23:14:51 - [01/27/2023 23:14:51]
  Udrakan dropped Molotov Coctail
   01/27/2023 23:14:51 - [01/27/2023 23:14:51]
  Atobá Azul launched Pulse Laser (projectile: Pulse Laser Bolt)
   01/27/2023 23:14:51 - [01/27/2023 23:14:51]
  Mudraptor_veteran has died (Cause of death: Burn)
   01/27/2023 23:14:51 - [01/27/2023 23:14:51]
  Mudraptor_veteran attacked by Atobá Azul. Deep tissue injury: 40.0 Stun: 0.5
   01/27/2023 23:14:51 - [01/27/2023 23:14:51]
  hUbert picked up Abyss Diving Suit
   01/27/2023 23:14:51 - [01/27/2023 23:14:51]
  Hawkins equipped Fixfoam Grenade
   01/27/2023 23:14:50 - [01/27/2023 23:14:50]
  Atobá Azul launched Pulse Laser (projectile: Pulse Laser Bolt)
   01/27/2023 23:14:50 - [01/27/2023 23:14:50]
  Mudraptor_veteran attacked by Atobá Azul. Deep tissue injury: 22.0 Stun: 0.5
   01/27/2023 23:14:49 - [01/27/2023 23:14:49]
  bananaman attacked by Skyline_Robot. Deep tissue injury: 10.5 Burn: 10.5 Stun: 0.1
```

**Comment by Regalis11** [comment] 2023-02-01 19:03
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7985

**Closed by Regalis11** 2023-02-01 19:03 UTC
