### ISSUE TITLE
Core content package Error.

### ISSUE THREAD

**Issue by ChikoEduardo** [Regalis11/Barotrauma#1770] opened 2019-07-26 16:31 UTC
I couldn't find a report about this issue so I'm not sure if you guys know about it, but corepackage mods don't work in multiplayer and they also break vanilla even if they aren't activated, unless the mod or content package xml file is removed.

It appears the game gets confused about having 2 or more core packages and somehow mixes part of them or something.

**Comment by Regalis11** [comment] 2019-07-27 19:16
Did a bit of testing with BTE, and I found one issue: the modifications to the battery cells seem to be causing "entity not found" errors client-side. This happens because the Repairable-component creates network events during initialization, before the server creates the event that notifies the clients about the item being spawned. For now you could work around the issue by removing the Repairable-component from the batteries. 

I'm glad this came up, because the same issue could potentially be causing the same kind of errors in the vanilla game!

I haven't looked into the mod breaking vanilla yet, but will try to reproduce and fix it after I've resolved the other issue.

**Comment by ChikoEduardo** [comment] 2019-07-30 17:16
Oh ok, I'll remove that from the batteries. I initially added the Repairable-component in handheld batteries as a way for EMP blasts to drain them in legacy. It kinda makes sense for them to be affected as well.

**Comment by Rokvach** [comment] 2019-09-23 21:56
This shouldn't be an issue anymore also the upcoming modding improvements should make this even less of an issue with the ability to adjust the load ordering of mods. Closing.

**Closed by Rokvach** 2019-09-23 21:56 UTC
Labels: Bug, Code, Networking-related
