### ISSUE TITLE
[Bug] Unable to switch to Opaque LOS mode

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2123] opened 2020-02-03 07:20 UTC
opaque line of sight doesn't work, and instead uses transparent, at least for me. Platform is linux, build is the latest unstable.

**Comment by Regalis11** [comment] 2020-02-03 08:41
Doesn't seem to happen on Windows, so this seems to be a Linux (and maybe Mac) specific issue

**Comment by Regalis11** [comment] 2020-02-07 13:48
I unfortunately wasn't able to reproduce this, all of the LOS modes seem to work on Win and Linux

**Comment by Regalis11** [comment] 2020-03-04 11:53
No known steps to reproduce, closing this for now

**Closed by Regalis11** 2020-03-04 11:53 UTC
Labels: Bug, Code, Linux only, Need more info
