### ISSUE TITLE
[UNSTABLE] hull shrapnel causes stunlock with enemies that shouldn't be able to do so.

### ISSUE THREAD

**Issue by Hamburgian** [Regalis11/Barotrauma#12488] opened 2023-08-11 01:37 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I noticed this with problem with mudraptors mainly. whenever the mudraptor slams into the hull, the hull shrapnel does a lot more damage and stuns for a lot longer than it normally should. I've noticed this with large enemies such as with hammerheads molochs working as intended, but when this bugs and happens with fast attacking and sub-entering creatures, it becomes out of hand extremely easily. This issue only appears when hull shrapnel happens, not every time the hull is damaged

https://github.com/Regalis11/Barotrauma/assets/141864587/74b08cca-850c-474c-9a4a-547430c132c3

this clip shows a singular mudraptor derailing an entire mission due to crazy hull shrapnel damage and stun. 

https://github.com/Regalis11/Barotrauma/assets/141864587/aae2935c-0440-46f8-93bd-6bcd3756c00a

(the command i was using in this one was "fixhulls", which stopped the mudraptor from getting in the sub whilst still causing hull shrapnel to be caused)

This bug did not happen with crawlers, since they don't do enough hull damage to cause shrapnel, and threshers behave weirdly so it was difficult to see if they were affected by the bug too

### Reproduction steps

1. go into mission or campaign since it has a seafloor (with no LOS filter enabled for easier vision)
2. spawn mudraptor swarm (2-3)
3. go to edge of submarine (still inside)
4. spawn mudraptor outside of submarine next to the edge and side that you're on
5. watch as the hull shrapnel goes crazy on you

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

Unstable (v1.1.3.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment] 2023-08-11 06:39
Uncertain how severe the issue is, but pinning as high prio so that we don't ship it in the release.

**Comment by Regalis11** [comment] 2023-08-15 14:24
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e715b8563d2e6ffdf30f667f09986ca9d3a5078a

**Closed** 2023-09-01 08:46 UTC
Labels: Bug, Code, Severe
