### ISSUE TITLE
Game lags a ton in strenuous situations

### ISSUE THREAD

**Issue by Dathomerian554** [Regalis11/Barotrauma#12642] opened 2023-09-08 08:45 UTC
While playing the single player campaign mode, practically every time the ship gets flooded and creatures start coming in, the game goes to what feels like 3 FPS.  In other words, it can lag to the point that it is unplayable, and you basically have to restart the entire mission (hopefully avoiding that situation the next time).  Please fix this!

**Comment by Regalis11** [comment] 2023-09-08 09:47
Thank you for the report! We have an [existing ticket about general performance problems](https://github.com/Regalis11/Barotrauma/issues/9396), if you can provide any more information about the issue (such as a screenshot with the performance statistics overlay enabled), it would help us a lot in diagnosing the issue.

Closing as a duplicate of https://github.com/Regalis11/Barotrauma/issues/9396

**Closed by Regalis11** 2023-09-08 09:47 UTC
