### ISSUE TITLE
Bugs i encountered with new update "Urban Expanses"

### ISSUE THREAD

**Issue by Krisisis** [Regalis11/Barotrauma#8976] opened 2022-04-26 08:54 UTC
Seems like most issues are sync related. Some have been encountered in earlier versions.

I'm hosting public a server with wiring enabled, completely vanilla with default submarines (Humpback in this case). People sometimes unwire stuff (griefing or curiosity). Both the engine and pump got bugged near the end of a mission. Full health, wired properly, seemingly powered and working (-100% => 100% depending on input). Even if there is no water animation in the ballast tank and the pump at full pump out, people suffocate in it and are pushed towards the roof. (Looking hilarious though as somebody crazy frogged past me XD)
This bug happened twice and I had to restart my campaign. It seems to happen after somebody is unwiring/rewiring power to the pump/engine, sounds similar to the other issue " Sub can't move laterally #3624 ".

2nd bug is that usually after exiting a station, people get disconnected from the server and need to rejoin. Then they are forced to spectate until host goes to lobby or kicks the "imposter" so the real person can play. Also happened to other servers i joined. Similar to issue " Clients timeout the connection if loading takes more than 10 seconds #6253 "

3th bug 
Everybody, including me as host got kicked from the server, reason: "Recieved an update for an entity that doesn't exist (event id 36170, entity id 7537)". I Verified integrity of game files and needed to re download 3 files. While in a station I suddenly could open, but not walk through doors anymore. Turns out my ID-card got replaced with a bot id with "limited access to the sub".

4th issue
After doing some work on my submarine "pvp venture" from my workshop item "pvp shuttles" [ https://steamcommunity.com/sharedfiles/filedetails/?id=2789286337 ] and updating the workshop item I lost all of the changes I did. Seems like i couldn't update it at all. I also miss the add files button in case i want to add more submarines into the collection.

ps: everybody wants to drive the wheelchair and ask why they can't  XD

I'm using Windows 10 and those bugs started after installing the Urban Expanses update.

**Comment by Regalis11** [comment] 2022-04-26 09:15
Duplicate of https://github.com/regalis11/barotrauma/issues/8873, https://github.com/Regalis11/Barotrauma/issues/8899, https://github.com/Regalis11/Barotrauma/issues/8879

**Closed by Regalis11** 2022-04-26 09:15 UTC
