### ISSUE TITLE
Bots are unable to replace incompatible items in slots in favour of compatible items

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#4380] opened 2020-11-24 14:18 UTC
**Description**
They are unable to replace incompatible items with compatible items. 

Examples : 
1. Unable to swap the oxygen tank in welding tool in favour of welding fuel.
2. Unable to swap the welding fuel in diving suits in favour of oxygen tanks. (as for this they also tend to wear said suit and die due to being unable to swap welding fuel with oxygen.

**Steps To Reproduce**

- Use setup provided
- Load into sub editor test mode
- Place Mechanic's tool belt in the trash railgun shell and fire it (to get rid of tools with compatible items)
- Flood room with Engineer in it, to replicate for 2. and observe
- Order Mechanic to "Fix Leaks"
- To then test for 1. either use the provided plasma cutter to create small leaks or create large leaks with the button labeled "Breach Wall"

**Setup**
[AIswitchTest.zip](https://github.com/Regalis11/Barotrauma/files/5590406/AIswitchTest.zip)

**Version :** [0.11.0.8] (unstable)

**Comment by itchyOwl** [comment] 2021-03-25 14:18
Fixed (or rather implemented) in Regalis11/Barotrauma-development@c113463.

**Comment by itchyOwl** [comment] 2021-03-25 14:21
Btw, I didn't follow the provided steps, because it was easier to reproduce the issue just by 

a) equiping a bot with a diving suit containing a welding fuel tank and teleporting it in the sea, and 
b) adding a bot a welding tool containing an oxygen tank and ordering it to fix leaks

**Comment by Xeavas** [comment] 2021-04-02 10:47
[v0.1300.0.6] Unable to replicate, thanks for implementing it! 👍

**Comment by Rokvach** [comment] 2021-04-02 11:24
Closing

**Comment by ekqvist** [comment] 2021-04-03 12:11
Reopened unintentionally

**Closed by ekqvist** 2021-04-03 12:11 UTC
Labels: Bug, Code, Medium Prio
