### ISSUE TITLE
Game Crash when dead Raptor Bane plant is uprooted

### ISSUE THREAD

**Issue by Mon732** [Regalis11/Barotrauma#4414] opened 2020-11-30 19:03 UTC
**Description**
Friend uprooted a raptor bane plant and crashed me once and another friend twice. We were using the Orca sub, files were validated with no corruption found.

**Steps To Reproduce**
Uproot dead Raptor Bane.

**Version**
v0.10.6.2 on Windows 10 Professional 64bit

**Additional information**
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/5618157/crashreport.log)

**Comment by 3e849f2e5c** [comment] 2020-12-01 03:28
Duplicate of #4315

**Closed by 3e849f2e5c** 2020-12-01 03:28 UTC
