### ISSUE TITLE
Bought revolver rounds became ghosts (disappear?) [possibly mp only]

### ISSUE THREAD

**Issue by gnomesurf** [Regalis11/Barotrauma#11584] opened 2023-03-18 03:51 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [x] My issue happened while using mods.

### What happened?

I bought revolver rounds from an outpost, saved and quit, then reloaded and went on a mission.  Other stuff I bought showed up but some empty crates also showed up.  In the store it says I have the amount of revolver rounds I should have but they don't show up on the item finder.  Deconstructing the empty crates caused the revolver round count to go down.  This has happened multiple time when trying to buy revolver rounds.

### Reproduction steps

1. Start multiplayer campaign.
2. Buy revolver rounds.
3. Save and quit.
4. Load the campaign.
5. Start a mission.
[who.zip](https://github.com/Regalis11/Barotrauma/files/11007394/who.zip)
^^Save file

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-04-05 15:43
I'm afraid I could not reproduce the issue using the provided save file.

There are a total of 23 revolver rounds in the armory (6 in the secure steel cabinet and 17 in the windowed steel cabinet). These are all displayed on the item finder. The store also correctly shows that number. There also don't seem to be any revolver rounds available for sale in the outpost.
![image](https://user-images.githubusercontent.com/14351070/230133122-f41d538c-b020-48d9-a3bf-c2a8dc79292b.png)

**Comment by Regalis11** [comment] 2023-05-02 09:23
No known steps to repro, closing

**Closed by Regalis11** 2023-05-02 09:23 UTC
Labels: Bug, Need more info, Code
