### ISSUE TITLE
Z fighting or a strange texture in a city manager module

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#11462] opened 2023-03-06 01:00 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This plant appears to be z fighting
![image](https://user-images.githubusercontent.com/59519434/222997210-da2a797e-1821-4bca-8633-8c8b4dd9e569.png)

### Bug prevalence

Just once

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-03-06 07:34
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11428

**Closed by Regalis11** 2023-03-06 07:34 UTC
