### ISSUE TITLE
Maintain position marker unaligned when on different zooms

### ISSUE THREAD

**Issue by GoodDays13** [Regalis11/Barotrauma#12655] opened 2023-09-10 23:25 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When zoomed in, the maintain position marker shows as closer than it really is.

https://github.com/Regalis11/Barotrauma/assets/42877449/f27d6a52-7713-457c-b1d8-13113453e6bc

### Reproduction steps

1. start a round in any way.
2. set maintain position to somewhere relative to something else.
3. zoom in and notice that the indicator get's closer to the center of the sonar.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

Unstable (v1.1.10.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-09-11 08:22
Duplicate of https://github.com/Regalis11/Barotrauma/issues/12538

**Closed by Regalis11** 2023-09-11 08:22 UTC
Labels: Bug, Duplicate, Code
