### ISSUE TITLE
Characters sitting in chairs wrong

### ISSUE THREAD

**Issue by alphasierra59** [Regalis11/Barotrauma#9227] opened 2022-05-30 19:36 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Characters randomly decide to use chairs incorrectly 
![image](https://user-images.githubusercontent.com/17458293/171051347-c9a62c59-6858-43db-b959-3d82455d0a73.png)

### Reproduction steps

1. Sit in chair facing to the right

### Bug prevalence

Happens every time I play

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
See screenshot.
```

**Comment by Regalis11** [comment] 2022-05-31 09:16
I'm afraid I could not find a way to reproduce this. Does it happen in some specific sub or outpost? Multiplayer, single player or both?

**Comment by alphasierra59** [comment] 2022-05-31 18:57
This was in the editor. Initially the chair was part of an assembly. I
deleted and created a fresh chair, the issue persisted. I have also noticed
issues where the characters can sit with perfectly straight legs, but I
don't get that result frequently.

**Comment by alphasierra59** [comment] 2022-06-01 08:42
I tried loading the sub in multiplayer and it worked fine, so it's definitely a quirk in the editor.

**Comment by Regalis11** [comment] 2022-06-06 07:08
Duplicate of https://github.com/Regalis11/Barotrauma/issues/9097

**Closed by Regalis11** 2022-06-06 07:08 UTC
Labels: Bug, Need more info, Code, Low prio
