### ISSUE TITLE
My game wont stop crashing for no reasons

### ISSUE THREAD

**Issue by Noxurius** [Regalis11/Barotrauma#9338] opened 2022-06-14 18:45 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

My game crashes while I'm playing, whereas there's no mods and I've checked for missing files and I've uninstalled it and reinstalled it many times AND I've updated my graphic card drivers I don't know what to do please help me

I'll link the last crash report I had (the last one is the 14th)

### Reproduction steps

1.Start a game with or without people
2.Play for few minutes
3.Enjoy the crash

### Bug prevalence

Happens every time I play

### Version

0.17.16.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 14/06/2022 20:35:13)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


1FC87F527F5494A2CD53453BD2215F18


Game version 0.17.16.0 (ReleaseWindows, branch release, revision 05309f303f)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla, Onyx Spear
Level seed: BramertonWorm Cave
Loaded submarine: Onyx Spear (9C3D2CD734C4D9F42F8454EDCD7ADC2F)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)


System info:
    Operating system: Microsoft Windows NT 10.0.19043.0 64 bit
    GPU name: NVIDIA GeForce GTX 1050
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,7777778}
    GPU status: Normal


Exception: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: L’instance de périphérique GPU a été suspendue. Utilisez GetDeviceRemovedReason pour déterminer l’action appropriée.
 (SharpDX.SharpDXException)
Device removed reason: HRESULT = 0x887A0006
Target site: Void CheckError()
Stack trace: 
   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D11.Device.CreateBuffer(BufferDescription& descRef, Nullable`1 initialDataRef, Buffer bufferOut)
   at SharpDX.Direct3D11.Buffer..ctor(Device device, Int32 sizeInBytes, ResourceUsage usage, BindFlags bindFlags, CpuAccessFlags accessFlags, ResourceOptionFlags optionFlags, Int32 structureByteStride)
   at Microsoft.Xna.Framework.Graphics.VertexBuffer.GenerateIfRequired() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\Vertices\VertexBuffer.DirectX.cs:line 60
   at Barotrauma.Lights.LightSource.CalculateLightVertices(List`1 rayCastHits) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\Lights\LightSource.cs:line 1130
   at Barotrauma.Lights.LightSource.DrawLightVolume(SpriteBatch spriteBatch, BasicEffect lightEffect, Matrix transform) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\Lights\LightSource.cs:line 1318
   at Barotrauma.Lights.LightManager.RenderLightMap(GraphicsDevice graphics, SpriteBatch spriteBatch, Camera cam, RenderTarget2D backgroundObstructor) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\Lights\LightManager.cs:line 347
   at Barotrauma.GameScreen.DrawMap(GraphicsDevice graphics, SpriteBatch spriteBatch, Double deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\GameScreen.cs:line 203
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\GameScreen.cs:line 128
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 972
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 511
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59


Last debug messages:
[14/06/2022 20:33:43] La Béchamelle
[14/06/2022 20:33:43] Lieutenant Noxurius
[14/06/2022 20:33:24] La Béchamelle
[14/06/2022 20:33:24] Lieutenant Noxurius
[14/06/2022 20:33:23] Received STARTGAMEFINALIZE packet. Round init status: Started
[14/06/2022 20:33:21] Task count: 0
[14/06/2022 20:33:21] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[14/06/2022 20:33:15] Generating an outpost for the start of the level... (Location: Bramerton Outpost, level type: LocationConnection)
[14/06/2022 20:33:13] Generating an outpost for the end of the level... (Location: Worm Cave Outpost, level type: LocationConnection)
[14/06/2022 20:33:00] Server running slowly (55 updates/s)!
[14/06/2022 20:32:55] Lieutenant Noxurius
[14/06/2022 20:32:53] Lieutenant Noxurius
[14/06/2022 20:32:32] Lieutenant Noxurius
[14/06/2022 20:32:31] Lieutenant Noxurius
[14/06/2022 20:32:31] Lieutenant Noxurius
[14/06/2022 20:32:31] Lieutenant Noxurius
[14/06/2022 20:32:04] Lieutenant Noxurius
[14/06/2022 20:32:01] Server running slowly (57 updates/s)!
[14/06/2022 20:32:00] Received STARTGAMEFINALIZE packet. Round init status: Started
[14/06/2022 20:32:00]  -1: WaitForPingDataAsync (owner), RanToCompletion
[14/06/2022 20:32:00]  -0: WaitForPingDataAsync (owner), RanToCompletion
[14/06/2022 20:32:00] Task count: 2
[14/06/2022 20:32:00] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[14/06/2022 20:31:53] Generating an outpost for the start of the level... (Location: Worm Cave Outpost, level type: Outpost)
[14/06/2022 20:31:35] Server running slowly (54 updates/s)!
[14/06/2022 20:31:26] Lobby created!
[14/06/2022 20:30:21] Attempting to open ALC device "OpenAL Soft on Haut-parleur/Ecouteurs (Realtek High Definition Audio)"
[14/06/2022 20:30:19] Logged in as Noxurius (SteamID STEAM_1:0:67774949)
```

**Comment by Regalis11** [comment] 2022-06-15 06:38
Duplicate of https://github.com/Regalis11/Barotrauma/issues/1833

**Closed by Regalis11** 2022-06-15 06:38 UTC
