### ISSUE TITLE
Entity Battery Cell Missing

### ISSUE THREAD

**Issue by titlo3** [Regalis11/Barotrauma#1664] opened 2019-06-16 22:59 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

I'm hosting a BTE server, any time I start the match I get the error, missing entity battery cell. Tried uninstalling all mods. Deleting my baro root folder and reinstalling the game. But nothing is fixing it

**Steps To Reproduce**
Unsure how to reproduce this besides downloading BTE as that was the only thing I did before it started acting up

**Version**
Latest version to this date.

**Comment by Regalis11** [comment] 2019-06-17 09:09
Does this happen in all game modes or just the multiplayer campaign? If the latter, I think this is a duplicate of #1603

**Comment by titlo3** [comment] 2019-06-17 14:20
Its happening in all game modes. Campaign, sandbox, and mission. I thought it was an issue with my files at first but the files for the battery cell exist. So I dunno why it's happening

**Comment by Regalis11** [comment] 2019-06-17 16:13
That's bizarre. Just to be absolutely sure it isn't caused by some files gone awry, could you please try going to inside the game folder, deleting a file called "config_player.xml" (note that this resets your user settings: resolution, keybinds, language selection, etc) and then going to Steam, right clicking the game, and going to Properties -> Local files -> "Verify integrity of game files". After this it should be a completely clean install, and if the issue still persist, it's most likely a networking bug in the game itself.

**Closed** 2019-06-28 07:58 UTC
Labels: Bug, Code, Need more info, Networking-related
