### ISSUE TITLE
[Bug] [Graphical] Light culling doesn't account for light sprites

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2398] opened 2020-03-05 17:28 UTC
I swear to god I made this issue in the past but I can't seem to find it so sorry if this is a duplicate.

The game over-aggressively culls lights since it bases the culling range off of what seems to just be the "projected light" range. If something has a small light range but still has a light "sprite" (the "sprite" inside of lightcomponents that isn't shaded), the light sprite will stop rendering whenever the light range goes offscreen, even if the lightsprite itself is much bigger than the lightrange itself. This is very troublesome for items you want to have glow in the dark without emitting any actual "projected" light with a lightrange.
This is very evident in my glow in the dark biome where glowing vegetation will abruptly disappear as soon as it reaches the edge of the screen.

**Comment by Regalis11** [comment] 2020-03-31 08:11
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3e8a54388c106107f79fcd267697b25a360cb9a1

**Comment by hubismal** [comment] 2020-04-01 03:20
This is notably not fixed in 0.9.901, at least for levelobjects with lightsources.
If you download my mod Thalassophobia which uses a lot of lightsprites without any light range, you'll see pretty clearly the cutoff as you pan around the map in leveleditor.
![2020-03-31-221837_1011x564_scrot](https://user-images.githubusercontent.com/47284081/78095894-cb887980-739d-11ea-8122-f98416061226.png)

**Comment by Regalis11** [comment] 2020-04-03 09:43
Seemed to happen because the scale of the sprite was not taken into account. Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/6677ef01e0e0abc7b4afbadcdaae4f99a453174b

**Comment by hubismal** [comment] 2020-04-03 15:49
Culling has been made significantly worse now, at least on low resolutions. When the light goes offscreen even slightly it stops casting the light from the lightcomponent completely. Don't know how this happened.
This is what the lights *on* in the typhon2 look like for me.
![2020-04-03-104921_1001x552_scrot](https://user-images.githubusercontent.com/47284081/78379997-d52a0100-7598-11ea-92ff-c5f2f85893c9.png)

**Comment by Regalis11** [comment] 2020-04-06 08:15
Yeah you're right, it didn't take the actual range of the light into account. 3rd attempt to fix: https://github.com/Regalis11/Barotrauma-development/commit/c6bd2c3e

**Comment by Rokvach** [comment] 2020-04-09 21:37
Recorded some video of this issue, looks like the light area doesn't span the entirety of the sprite, so when moving downwards the light sprite vanishes before the sprite gets offscreen.

https://streamable.com/pqbiai

**Comment by Regalis11** [comment] 2020-04-13 10:53
Ah, I think I finally figured out the problem: the origin of the sprite wasn't taken into account in the culling logic. Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/d4c4c5c

**Comment by Rokvach** [comment] 2020-04-13 15:37
I wasn't able to reproduce the issue anymore, so seems to be working correctly. Closing.

**Closed by Rokvach** 2020-04-13 15:37 UTC
Labels: Bug, Code, Low prio
