### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by misgnosia** [Regalis11/Barotrauma#5651] opened 2021-04-29 20:17 UTC
- [ nope] I have searched the issue tracker to check if the issue has already been reported.

**Description**
game crashed and dialogue said post it here
**Steps To Reproduce**
Host a multiplayer game? Maybe fight a husk from a ruin that regenerates its whole health bar in about a second, I dumped a whole smg clip into it, half an alien pistol, and my crewmates fired 100% of their ordinance, and we still ended up kiting it over a railgun to kill it

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**
[crashreport (3).log](https://github.com/Regalis11/Barotrauma/files/6401341/crashreport.3.log)

**Comment by itchyOwl** [comment] 2021-05-03 08:15
Seems to be caused by a bug in the text selection. Couldn't repro it, but it shouldn't crash anymore:
Regalis11/Barotrauma-development@e0d8da3.

**Comment by Rokvach** [comment] 2021-05-25 08:25
There hasn't been any sightings of this during the Unstable period, seems to be working correctly. Closing.

**Closed by Rokvach** 2021-05-25 08:25 UTC
Labels: Bug, Code, Crash
