### ISSUE TITLE
[0.10.501] Multiplayer bricking Saves after several rounds of normal play

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3680] opened 2020-09-02 17:14 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Played a few rounds from the beginning with R-29. Bought [Kail Terra](https://steamcommunity.com/sharedfiles/filedetails/?id=2197390262). Made all the bots followed me with diving suits on them and myself. Went to next level with Killing A Moloch mission. Save is bricked to Entity Position.

[dump.txt](https://github.com/Regalis11/Barotrauma/files/5163770/dump.txt)
[crashreport_object.log](https://github.com/Regalis11/Barotrauma/files/5163771/crashreport_object.log)
[Multiplayer.zip](https://github.com/Regalis11/Barotrauma/files/5163772/Multiplayer.zip)

**Version**
0.10.501

**Comment by Regalis11** [comment] 2020-09-03 12:13
Wow, I'm glad you were able to provide us with this save. I manage to track down the bug and turns out it's something that could've been the cause to several other networking errors as well, including #1815, #2382, #2882 and #3019. 

The problem was that if a client received a position update for an entity that hasn't spawned at their end yet, and there's another entity that had the same ID as the newly spawned one, the client would assume it's for the old entity and read the message. 

For example, in this case the server spawned a (purchased?) diving suit with the ID 3771. There happened to be a decorative panel with that same ID in the sub, which gets assigned a new ID as soon as the suit spawns. The clients would receive a position update for the suit before they've spawned the suit themselves, so they'd think they've received an update for the decorative panel, and attempt to read an incorrect number of bytes from the message (causing the out of bounds error).

This could've caused other kinds of networking issues as well: if there had been further data in the message, the client would've attempted to read it incorrectly which could've caused all sorts of errors (invalid header, missing entity).

**Comment by Kaillera** [comment] 2020-09-03 12:29
Here's another save that bricked after several rounds of normal play on just one submarine in this version:

[Multiplayer.zip](https://github.com/Regalis11/Barotrauma/files/5168463/Multiplayer.zip)
[crashreport_object.log](https://github.com/Regalis11/Barotrauma/files/5168464/crashreport_object.log)
[event_error_log_client_Kaillera_1215 PM.log](https://github.com/Regalis11/Barotrauma/files/5168465/event_error_log_client_Kaillera_1215.PM.log)
[event_error_log_server_Kaillera_1215 PM.log](https://github.com/Regalis11/Barotrauma/files/5168466/event_error_log_server_Kaillera_1215.PM.log)

**Comment by Rokvach** [comment] 2020-09-10 09:11
There hasn't been any sightings of this happening since the fix, closing.

**Closed by Rokvach** 2020-09-10 09:11 UTC
Labels: Bug, Code, Networking
