### ISSUE TITLE
Use local voice by default missing from the UI

### ISSUE THREAD

**Issue by LilliPJs** [Regalis11/Barotrauma#9287] opened 2022-06-08 04:34 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The "Use Local Voice by Default" button is missing from the Audio & Voice chat tab in the settings menu, it was there prior to the Urban Expanses update and vanished after it.
![image](https://user-images.githubusercontent.com/36248447/172532374-900caf6a-9395-44ae-b275-79dcdb8365e9.png)

### Reproduction steps

1. Open game
2. Go to settings
3. Go to Audio & Voice chat tab
4. Missing "Use Local Voice by Default"

### Bug prevalence

Happens every time I play

### Version

Other

### -

0.17.16.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-06-08 05:40
Duplicate of https://github.com/Regalis11/Barotrauma/issues/9087

**Closed by Regalis11** 2022-06-08 05:40 UTC
