### ISSUE TITLE
[0.10.501] Using "Save and Quit" returns to the main menu with the ESC menu still up

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3700] opened 2020-09-03 13:12 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Using "Save and Quit" returns to the main menu with the ESC menu still up.

**Version**
0.10.501

**Comment by Regalis11** [comment] 2020-09-03 13:38
Could not reproduce. Do you mean returning to the main menu from a single player campaign round?

**Comment by Rokvach** [comment] 2020-09-03 13:41
I was able to reproduce this

Tested on dev branch, Release build

Repro steps:
1. Load up a singleplayer
2. When you load in to the Outpost, hit Esc and "Save and Quit"
3. Notice that the Esc menu is still open when you're on the main menu

Clicking the "Save and Quit" button again crashes the game

```
Barotrauma Client crash report (generated on 3.9.2020 16:39:39)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


871058C2E018D8B1F39C8978557170F3


Game version 0.10.501.0 (ReleaseWindows, branch dev, revision 864766630d)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.MainMenuScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.18362.0 64 bit
    GPU name: NVIDIA GeForce GTX 980 Ti
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1,7777778}
    GPU status: Normal


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void QuitToMainMenu(Boolean)
Stack trace: 
   at Barotrauma.GameMain.QuitToMainMenu(Boolean save) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 1085
   at Barotrauma.GUI.<>c.<TogglePauseMenu>b__181_7(GUIButton btn, Object userdata) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 2156
   at Barotrauma.GUIButton.Update(Single deltaTime) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 253
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1220
   at Barotrauma.GameMain.Update(GameTime gameTime) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 990
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in C:\Users\RoniK\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in C:\Users\RoniK\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in C:\Users\RoniK\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\RoniK\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in C:\Users\RoniK\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58


Last debug messages:
[3.9.2020 16:39:32] Debug draw mode disabled
[3.9.2020 16:39:32] debugdraw
[3.9.2020 16:39:25] Generating an outpost for the start of the level... (Location: Apep City, level type: Outpost)
[3.9.2020 16:38:48] Debug draw mode enabled
[3.9.2020 16:38:48] debugdraw
[3.9.2020 16:38:46] Steam achievements have been disabled during this play session.
[3.9.2020 16:38:46] Enabled cheat commands.
[3.9.2020 16:38:46] enablecheats
[3.9.2020 16:38:29] Generating an outpost for the start of the level... (Location: The Bucket, level type: Outpost)
[3.9.2020 16:38:22] (Msg) RelayNetWorkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[3.9.2020 16:38:22] (Msg) Ping location: sto=14+1,sto2=14+1,fra=40+4/33+1,ams=39+3/34+1,waw=49+4/34+1,lux=45+4/37+1,lhr=46+4/38+1,par=50+5/42+1,vie=51+5/45+1,iad=127+12/118+1,sgp=196+19/197+19,gru=253+25/262+1
[3.9.2020 16:38:22] (Msg) Ping measurement completed
[3.9.2020 16:38:20] (Debug) Destroying relay 'man#127 (155.133.253.34:27033)' because initial_ping_timeout
[3.9.2020 16:38:18] (Debug) Destroying relay 'man#82 (155.133.253.19:27042)' because initial_ping_timeout
[3.9.2020 16:38:15] (Debug) Destroying relay 'man#92 (155.133.253.19:27052)' because initial_ping_timeout
[3.9.2020 16:38:13] (Verbose) Communications with routing cluster 'sea' established.
[3.9.2020 16:38:12] (Verbose) Communications with routing cluster 'vie' established.
[3.9.2020 16:38:12] (Debug) Destroying relay 'vie#10 (146.66.155.34:27024)' because initial_ping_timeout
[3.9.2020 16:38:12] (Debug) Destroying relay 'sea#113 (205.196.6.148:27035)' because initial_ping_timeout
[3.9.2020 16:38:12] (Debug) Destroying relay 'man#19 (155.133.253.4:27033)' because initial_ping_timeout
[3.9.2020 16:38:10] (Verbose) Communications with routing cluster 'syd' established.
[3.9.2020 16:38:10] (Verbose) Communications with routing cluster 'tyo1' established.
[3.9.2020 16:38:10] (Verbose) Communications with routing cluster 'tyo' established.
[3.9.2020 16:38:10] (Verbose) Communications with routing cluster 'scl' established.
[3.9.2020 16:38:10] (Verbose) Communications with routing cluster 'sgp' established.
[3.9.2020 16:38:10] (Verbose) Communications with routing cluster 'lim' established.
[3.9.2020 16:38:10] (Verbose) Communications with routing cluster 'maa' established.
[3.9.2020 16:38:10] (Verbose) Communications with routing cluster 'okc' established.
[3.9.2020 16:38:10] (Verbose) Communications with routing cluster 'lax' established.
[3.9.2020 16:38:10] (Verbose) Communications with routing cluster 'gru' established.
[3.9.2020 16:38:10] (Verbose) Communications with routing cluster 'waw' established.
[3.9.2020 16:38:10] (Verbose) Communications with routing cluster 'ord' established.
[3.9.2020 16:38:10] (Verbose) Communications with routing cluster 'hkg' established.
[3.9.2020 16:38:10] (Verbose) Communications with routing cluster 'jnb' established.
[3.9.2020 16:38:10] (Verbose) Communications with routing cluster 'sto' established.
[3.9.2020 16:38:10] (Verbose) Communications with routing cluster 'sto2' established.
[3.9.2020 16:38:10] (Verbose) Communications with routing cluster 'eat' established.
[3.9.2020 16:38:10] (Verbose) Communications with routing cluster 'mad' established.
[3.9.2020 16:38:10] (Verbose) Communications with routing cluster 'bom' established.
[3.9.2020 16:38:10] (Verbose) Communications with routing cluster 'par' established.
[3.9.2020 16:38:10] (Verbose) Communications with routing cluster 'dxb' established.
[3.9.2020 16:38:10] (Verbose) Communications with routing cluster 'lux' established.
[3.9.2020 16:38:10] (Verbose) Communications with routing cluster 'lhr' established.
[3.9.2020 16:38:10] (Verbose) Communications with routing cluster 'atl' established.
[3.9.2020 16:38:10] (Verbose) Communications with routing cluster 'iad' established.
[3.9.2020 16:38:10] (Verbose) Communications with routing cluster 'fra' established.
[3.9.2020 16:38:10] (Verbose) Communications with routing cluster 'ams' established.
[3.9.2020 16:38:10] (Msg) RelayNetWorkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[3.9.2020 16:38:10] (Msg) Performing ping measurement
[3.9.2020 16:38:10] (Msg) Got SDR network config.  Loaded revision 281 OK
[3.9.2020 16:38:09] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[3.9.2020 16:38:06] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[3.9.2020 16:38:05] Content package load order: Vanilla 0.9
[3.9.2020 16:38:05] Error in content package "SecurityModule_02" - no content files defined.
[3.9.2020 16:38:05] Error in content package "Berilia_Wrecked" - no content files defined.
[3.9.2020 16:38:05] Content package load order: Vanilla 0.9
[3.9.2020 16:38:03] Attempting to open ALC device "OpenAL Soft on Kaiuttimet (Realtek High Definition Audio)"
[3.9.2020 16:38:02] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[3.9.2020 16:38:02] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[3.9.2020 16:38:01] Error in content package "SecurityModule_02" - no content files defined.
[3.9.2020 16:38:01] Error in content package "Berilia_Wrecked" - no content files defined.
```

**Comment by Regalis11** [comment] 2020-09-03 14:05
Ah, the problem was that I was testing this in a non-outpost level. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0dd6c0e05c0aa7bd4fe9fb13571dea1ffeffb601

**Comment by Rokvach** [comment] 2020-09-04 05:54
Tested, working correctly. Closing.

**Closed by Rokvach** 2020-09-04 05:54 UTC
Labels: Bug, Code
