### ISSUE TITLE
Batteries‘s White Port

### ISSUE THREAD

**Issue by SaulApostle** [Regalis11/Barotrauma#1721] opened 2019-06-28 20:53 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

I think batteries and reactor have only power_out for energy output.White Port Output Signal.but It also outputs power.Burn out the junction box.
Especially when charge rate out and set charge rate are connected.I think this is normal operation.but the batteries will provide power and reduce electricity to nothing.
Text Display usually power consumption is 0.If it is greater than 0, does it use the only signal port to get both electricity and signals?

![_YFY3BZY 06G_KX 60~JY M](https://user-images.githubusercontent.com/11502419/60369567-99b93f80-9a26-11e9-83b8-0f6c03cc1b35.png)

9.0.7

**Comment by Regalis11** [comment] 2019-07-09 10:19
The white ports should only output signals, no power. I tried reproducing the issue by connecting charge_rate_out to a lamp through a junction box, and it seemed to work as intended (no power went through, and the battery didn't lose any charge). Could you please share a screenshot (or even better, a sub file) of a setup where the problem appears?

**Comment by SaulApostle** [comment] 2019-07-09 13:37
[1st Star Destroyer.zip](https://github.com/Regalis11/Barotrauma/files/3373201/1st.Star.Destroyer.zip)

**Comment by Regalis11** [comment] 2019-07-23 11:02
Thank you, I was able to diagnose it now! Should be fixed for the next patch (https://github.com/Regalis11/Barotrauma-development/commit/2e8a58c2e0a8b654f3653584163458ef376e0986 in the private repo).

**Comment by Rokvach** [comment] 2019-08-08 21:35
Tested, working correctly. Closing.

**Closed by Rokvach** 2019-08-08 21:35 UTC
Labels: Bug, Code, Need more info
