### ISSUE TITLE
Low fps in shop

### ISSUE THREAD

**Issue by ShockedApple** [Regalis11/Barotrauma#8383] opened 2022-02-26 06:31 UTC
- [Y] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Whenever I interact with a trader on a station, my fps drops down to 10

**Steps To Reproduce**
Talk to a trader on any station

**Version**
v0.16.7.0

**Comment by SagaciousZed** [comment] 2022-02-27 22:08
I am also experiencing loss of performance with the Trade UI. Here is the output from showperf
Perf in a multiplayer game connected to a listen server:
![perf not trading](https://user-images.githubusercontent.com/1127211/155901898-df4c0ef9-e248-4334-8f9a-9f7385a21612.jpg)
Perf with trade open:
![perf while trading](https://user-images.githubusercontent.com/1127211/155901905-a322defd-cefa-41b4-b655-e25b6cf19e63.jpg)

**Comment by Regalis11** [comment] 2022-02-28 08:34
Duplicate of https://github.com/Regalis11/Barotrauma/issues/8365

**Closed by Regalis11** 2022-02-28 08:34 UTC
Labels: Bug, Code, Performance
