### ISSUE TITLE
Labels are slow and speed depends on the size of the label

### ISSUE THREAD

**Issue by BlackMoons** [Regalis11/Barotrauma#12923] opened 2023-10-25 23:44 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

So, After benchmarking a bunch of things and finding out that labels and text displays are particularly slow, I decided to try and test some more and came to the interesting conclusion: 

Label speed depends largely on the size of the label and amount of text contained. 

1000 small labels with the text: "H" = 11.1mS draw
1000 small labels (Same size as above) with the text: "Hello world" = 16.7mS draw (The entire performance budget for 60fps)
1000 very large labels (the size of 10 of the small labels) with the text: "H" = 51mS draw (19FPS)

While I doubt people are using 1000, I wouldn't put it past a lot of subs to contain a large number of labels (100+), with some of them being large text, and I honestly couldn't find anything else (outside of junction boxes/relays) that had such low performance during my tests of submarine components.

The draw speed also does not change with zoom, so I don't think its fill rate related. 

For a performance comparison, writing 'Hello world' using the icon letters 1000 times (10000 items) results in 10mS draw time, beating even the 'small label H only' time , despite 10x as many items being rendered. 

(Sadly, you can't rescale icon letters small enough to use for most labels, since the game limits you to 0.1 scale) 

I am wondering if you are rendering text to texture every frame? And if so, if you could save the result texture to memory for labels to save render time? (Maybe text displays too, since often text displays are static or only update color/text periodically when an event in the sub happens) 

### Reproduction steps

Start sub editor, start placing labels (place 10, copy paste that 10 times, copy paste that 10 times to create 1000 labels so you can observe a pronounced performance impact from them without it being lost in the noise)

observe 'Draw - avg' with 'showperf' increase if the labels are large. 

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.1.18.1 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Windows

**Comment by BlackMoons** [comment] 2023-10-26 19:51
Interestingly enough, it also seems to depend largely on the *scale* of the label. Lower scale = higher draw time.

**Comment by Regalis11** [comment] 2023-10-27 12:47
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/0dbd2a886cfc0d74225a7beab99028b2ed2b4b05

**Comment by BlackMoons** [comment] 2023-10-27 12:55
Neat, what was the fix?

**Comment by Regalis11** [comment] 2023-10-27 13:00
> Optimized the "label" item (see https://github.com/Regalis11/Barotrauma/issues/12923). It used an extremely small sprite that was also scaled down to 0.5, and due to DrawTiled drawing each tile separately, labels (especially large ones) were unnecessary heavy to render. I addressed that by giving it a much larger sprite so it doesn't need to be tiled that many times. Ideally we would optimize DrawTiled instead, but it's so damn complex and every time we've changed it something has broken, that I'd rather not touch it rn.

**Comment by BlackMoons** [comment] 2023-10-27 13:02
Thanks, that should help a lot (Especially since most people just assume it has a solid color background, I didn't even notice it had a texture until recently) 

DrawTiled will need to be fixed at some point as its so widely used, or at least figure out why batched sprites are redrawing(?) every frame instead of being reused(?)

**Comment by Regalis11** [comment] 2023-10-27 13:14
>DrawTiled will need to be fixed at some point as its so widely used, or at least figure out why batched sprites are redrawing(?) every frame instead of being reused(?)

I think you've probably misunderstood how SpriteBatches work: batching doesn't mean the rendered sprites are somehow reused between frames, a batch of draw operations is just sent to the GPU in "one go" but everything does still get re-rendered every frame (which is pretty much how rendering works in all games, everything is generally always rendered again every frame, save for some expensive things that can/should be pre-rendered).

**Comment by BlackMoons** [comment] 2023-10-27 13:18
Yea. I was assuming it was rendering to a render target to actually batch them for later, as I couldn't understand why it would have such poor performance otherwise.

Looks like it can batch multiple draw() calls (to be executed on texture change/calling end()), but doesn't seem to be when rendering tiled graphics? Any idea why that might be?

**Comment by BlackMoons** [comment] 2023-10-27 13:22
But from the performance, it seems to not be batching at all.

Like try just making a huge outpost wall in the sub editor, and set the scale to 0.1, just 1 object can drop FPS to single digits if it tiles enough. Its not batching at *all*

**Comment by Regalis11** [comment] 2023-10-27 13:25
I feel like you're still misunderstanding what batching means. It just sends all those draw calls to the GPU in one go, but a large number of draw calls is still expensive.

**Comment by BlackMoons** [comment] 2023-10-27 13:27
is the sprite batch being used for tiled objects being rendered with SpriteSortMode.Immediate?

**Comment by Regalis11** [comment] 2023-10-27 13:33
Yes it is, but:
1. With SpriteSortMode.Immediate, SpriteBatch doesn't batch the draw calls.
2. The labels or anything else in the submarine isn't rendered with SpriteSortMode.Immediate, so I don't think that's relevant here. 

To reiterate, the batching is not the problem here. DrawTiled batches the draw calls the exact same way as any other draw method, the problem is just the sheer number of draw calls.

**Comment by BlackMoons** [comment] 2023-10-27 13:37
Yea I am trying to figure out why DrawTiled seems to not be batching the draw calls into a single call with more geometry.

**Comment by Regalis11** [comment] 2023-10-27 13:42
Yes it is. It works the exact same way as the rest of the Draw methods. I think I'm probably not explaining it very clearly (mixing up "draw calls" and calls to Barotrauma's "Draw" methods). DrawTiled does batch the draw calls the same way as everything else, there's just so much to draw in this case that just constructing all the geometry takes a lot of time.

**Comment by BlackMoons** [comment] 2023-10-27 13:50
Looks like BacktoFront sort order may be a culprit. https://gamedev.stackexchange.com/questions/45429/improving-spritebatch-performance-for-tiles

https://gamedev.stackexchange.com/questions/45429/improving-spritebatch-performance-for-tiles

Also mentions its poor performance compared to deferred mode. 

Back to front executes a non stable sort on every tile that is submitted, separately and that may be why performance scales so poorly with large numbers of tiles/sprites. Also may lower draw call batching since its unstable, other sprites with the same depth may end up interleaved resulting in more draw calls due to texture swaps. 

How much of a performance gain would it need to be for you to refactor to make draw calls in Z order so deferred mode could be used? Since the Z depth of submarine components/etc never changes, it would completely eliminate the per-frame sorting.

**Comment by Regalis11** [comment] 2023-10-27 14:09
Honestly I don't think it's very useful to guess what the problem might be based on stack exchange posts. We (or anyone with access to the source code) can use a profiler to actually measure what the issue is. You are right that sorting the batch is one of the most expensive parts of the batching, but that's generally still not that expensive aside from more extreme situations like this one. I took a quick look at this, and in a "normal" situation (with just a vanilla Humpback on the screen), about 1.7% of CPU time was spent on the sorting.

> How much of a performance gain would it need to be for you to refactor to make draw calls in Z order so deferred mode could be used? Since the Z depth of submarine components/etc never changes, it would completely eliminate the per-frame sorting.

I doubt it'd give next to any performance benefits. Sorting the draw calls is not that expensive, and I'm fairly certain the overhead of making the draw calls in the "correct" order would have a comparable (if not even larger) overhead. It is not true that the Z depth can never change: there are plenty of exceptions to that, and all of those would need to be taken into account, and there's a chance then we'd end up with problems like "FPS drops to 5 when characters equip items repeatedly or this weird modded item attaches and detaches itself from a wall frequently".

So personally I feel it doesn't make sense to start doing these kinds of changes to the rendering logic. It feels backwards to me to add extra complexity to make the rendering logic able to handle the game doing something really stupid (like rendering a label out of 150,000 individual 1-pixel tiles), as opposed to making the game not do that stupid thing in the first place.

**Comment by BlackMoons** [comment] 2023-10-27 14:20
A vanilla humpback is 398 items, at nlogn sort that is an execution time of 1,034.

Many 3d party ships are in the 1000~6000 item range. My own ship is 3700 items, just under your own editors 'item warning limit.', so lets use that warning limit shall we?

At 3700 items, the execution time of nlogn is 13,202. 13 times more.

And then you have the actual world, stations, NPC's, every monster part and every tile of every one of those 3700 objects. 

Lets say 6000 after tiling, world map, monsters, NPC's, etc, you now have a sort execution time of 22,668, assuming 1000 corasponds to 1.7 of your CPU, that is now up to 37% CPU usage on sorting.

**Comment by Regalis11** [comment] 2023-10-27 14:31
Again, it's pointless to guess when you can actually measure it with a profiler. Those numbers are pretty much meaningless because
1. The number of items doesn't correspond to the number of entities that are rendered.
2. The time it takes to sort doesn't scale as `n log (n)` with the number of entities, because the list of entities isn't in a random order.
3. You're assuming the number of entities only increases the cost of the sorting, and nothing else, which is obviously not true.

I did the same test in an advanced save, in a colony with a total of 7800 items loaded, and the sorting now took 0.42% of CPU time:

![image](https://github.com/Regalis11/Barotrauma/assets/14351070/9a46afd1-b6fa-4100-8dac-a2f85736ffcd)

Blind guesses generally don't work for optimizations - you need to measure where the problem is, because it often isn't where you might expect it to be.

**Comment by BlackMoons** [comment] 2023-10-27 14:37
Thank you for checking and proving me wrong. Wish I could do more to improve the speed of barotrauma.

**Comment by Regalis11** [comment] 2023-10-27 14:41
If you're not afraid of delving a little deeper, it's fairly easy to launch the game with for example Visual Studio's profiler attached and actually see what's eating up performance in your mods and custom subs! :) I personally find profiling and optimization really interesting, often I find some curious thing that I'd never expected to be heavy to be causing performance problems, and I find it fun to figure out ways to make it perform faster.

**Comment by BlackMoons** [comment] 2023-10-27 14:52
FlushVertexArray calls are a result of texture switches while rendering. 

The fact backtofront uses an unstable sort isn't great, since it can mix up sprites with different texture ID's, even tiles of a single sprite.

What about adding some tiny, unnoticeable Z offset (<0.001) to sprites based on texture ID to help group sprites better after sorting? This would automatically make the sorting routine group sprites at the same z-depth by texture sheet for you.. More or less. At least it wouldn't cost anything to do and would be about 1 line of code? Something like, take the last 2 bytes of texture ID, convert to float, divide by 65,536,000 and add to z-depth? 

Id love to delve deeper but I am currently in the process of getting a new PC so I can run visual studio, so I can't till then..

**Comment by Regalis11** [comment] 2023-10-27 17:41
> What about adding some tiny, unnoticeable Z offset (<0.001) to sprites based on texture ID to help group sprites better after sorting? This would automatically make the sorting routine group sprites at the same z-depth by texture sheet for you.. More or less. At least it wouldn't cost anything to do and would be about 1 line of code? Something like, take the last 2 bytes of texture ID, convert to float, divide by 65,536,000 and add to z-depth?

We actually do something close to that already, the entities [are sorted based on the texture first](https://github.com/Regalis11/Barotrauma/blob/de4726b70ae651f3cfb8e7d7888948f4df180cad/Barotrauma/BarotraumaShared/SharedSource/Map/MapEntity.cs#L549) and added to the spritebatch in that order, so even though it's not used as a criteria in the "actual" sorting, the IntroSort tends to leave the draw calls with the same texture next to each other.

> At least it wouldn't cost anything to do and would be about 1 line of code? Something like, take the last 2 bytes of texture ID, convert to float, divide by 65,536,000 and add to z-depth?

This is not as trivial as it sounds, you're going to hit the limits of floating point precision if you try adding values that small to a float value between 0-1 (simply put, the float value is a handful of digits + a decimal separator at some arbitrary point, you can't store a value like 0.1000000000151). And we already use a similar approach to make certain sprites render in front of another one, so modifying the z depth like this would interfere with those sprites.

And again, I don't see the need to add any extra complexity to optimize a thing that's not really a major performance problem, when there are other, much more severe performance issues that could be addressed much more easily.

**Comment by BlackMoons** [comment] 2023-10-29 01:41
I noticed you use offsets already, I would hope most are >0.001 so sub designers can put things between them if needed. 

I know floating point has limits, but the goal of this change isn't perfection, its 'better ordered for less texture changes then it currently is', hence some collision would be OK.

**Comment by Regalis11** [comment] 2023-10-29 08:24
>but the goal of this change isn't perfection

The problem is that if you tried to add such small values to the depth, it wouldn't do anything because floating points can't store values with such precision. And if we used larger values, it'd start interfering with those other "depth modifications" we're using.

**Comment by BlackMoons** [comment] 2023-10-29 09:20
Floating point generally stores about 6~7 digits of precision, so with values of 0 to 1, they can store 0.000001 accurately, enough to encode about 1000 textures without offsetting it more then 0.001. 

And as the goal is just to get it sort slightly better, not make it perfect, false matches are acceptable, since right now its doing little to try and 'match' them as the z-sort is unstable, submission order doesn't matter as much as it could. I don't think its some 'wonder' optimization, just that it might eek out a few more % for very little effort by reducing texture switches (and hence draw calls)

**Comment by Rokvach** [comment] 2023-11-06 09:21
Tested, I'm able to measure quite a good performance difference when comparing with and without these changes. Working correctly. Can be merged and closed.

**Comment by BlackMoons** [comment] 2023-11-06 10:39
@Rokvach I assume you mean the changes Regalis mentioned?

**Comment by Rokvach** [comment] 2023-11-06 10:46
@BlackMoons Yes I compared the new code changes to the current Unstable build which doesn't have them

**Closed by Rokvach** 2023-11-06 10:47 UTC
Labels: Code, Performance
