### ISSUE TITLE
The Projectile's particle disappear when it spawned by weapons

### ISSUE THREAD

**Issue by MJJJJN11** [Regalis11/Barotrauma#13203] opened 2023-12-20 05:38 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

        <Item identifier="TestBullet" >
          <Projectile hitscan="true" removeonhit="true">
            <ParticleEmitter particle="tracerfirearm" particleamount="1" velocitymin="0" velocitymax="0" colormultiplier="255,200,200,175" scalemultiplier="1,1.2" />
          </Projectile>
        </Item>

        <Item identifier="TestGun" >
          <RangedWeapon >
            <StatusEffect type="OnUse" target="This" >
              <SpawnItem identifier="TestBullet" spawnposition="This" count="1" aimspread="0" rotationtype="Collider" rotation="0" />
            </StatusEffect>
          </RangedWeapon>
        </Item>

### Reproduction steps
If the projectile is **hitscan** ,it's particle will disappeared when it spawned by entitybody.

https://github.com/Regalis11/Barotrauma/assets/149501175/c3c324ba-096a-4175-82c7-dade71507923

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.6.0 (Winter Update)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-12-20 08:14
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10672

**Closed by Regalis11** 2023-12-20 08:14 UTC
