### ISSUE TITLE
Hull oxygen desync ( Possibly caused by electricity desync ? )

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#8344] opened 2022-02-22 19:01 UTC
Hull oxygen desync ( Possibly caused by electricity desync ? )

**Issue:**
In inconsistent cases, the oxygen level of the submarine hull itself seems to be susceptible to desync. An obvious tell for this among all cases of my own & those reported by other people is the oxygen levels on the status monitor rapidly jumping between 0 to 100 with no gradual transition.

The cause of this could be several things worth investigation.
- bug with the hull oxygen level calculation 
_( unlikely since nothing major was changed )_
- bug with oxygen generator
- bug with new electrical calculations?
_( Server getting into a state where it thinks the generator is unpowered despite being connected? )_
The symptoms of this feel very similar to #2489 , #2894 , but probably a new bug this time.

There is not really any easily reproducible method to this since desync behavior like this doesn't produce any logging information, and has happened across multiple servers and vanilla & workshop subs. Kind of just at the mercy of packet-loss as to weather or not you can reproduce this.

**Comment by Regalis11** [comment] 2022-06-06 18:20
Most likely caused by the same 2 bugs as https://github.com/Regalis11/Barotrauma/issues/9269

**Comment by Rokvach** [comment] 2022-08-23 10:29
This issues seems to already been fixed, closing as working correctly.

**Closed by Rokvach** 2022-08-23 10:29 UTC
Labels: Bug, Needs testing, Code, Networking, Unstable
