### ISSUE TITLE
Bots refuse to cleanup stuff from amogus update

### ISSUE THREAD

**Issue by Quartofel** [Regalis11/Barotrauma#7482] opened 2021-11-25 09:49 UTC
- [*] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots do not acknowledge existance of the following items (at least):
- dementite ammo
- depleted fuel ammo
- assault rifle mags
- explosive slugs
- handcannon rounds
- hardened tools
- dementite tools

**Steps To Reproduce**

1. Create a container.
2. Set proper containable restrictions.
3. Spawn/place any of the mentioned items.
4. Order any number of bots to cleanup the items.
5. Watch as they pretend the mess doesn't exist so they don't have to cleanup.
6. (optional) Throw the cheeky fuckers out of the airlock without a diving suit.

**Version**
Most up-to-date non-experimental Steam (Windows 10) version as of writing this issue.

**Additional information**
Pls fix. Also, I beg for more bearable container settings.

**Comment by Regalis11** [comment] 2021-11-25 09:51
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7188

**Closed by Regalis11** 2021-11-25 09:51 UTC
