### ISSUE TITLE
Infinite Missions

### ISSUE THREAD

**Issue by TheUltimate0** [Regalis11/Barotrauma#9687] opened 2022-08-07 20:02 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

At a station, talking to the person who gives you 3 missions to choose from, I saved and quit the game. When I came back, I had the option to select any of those 3 missions, but the person also had 3 more missions to give me. I save and quit a few more times, and sure enough, every time I reloaded I had more missions to get and could still choose any of the missions I'd already gotten. By saving and quitting the game, you can generate infinite missions to choose from. 

I think this might point to a broader issue of the RNG seed (or whatever is used for random items from shops, etc) changing every time you reload the game. For example, if I don't like any of the crew that I'm able to buy, then I can just reload the game and be offered a completely unique selection. Same with the other shops.

### Reproduction steps

1. Dock and arrive at a station or outpost
2. Go to the top and get the missions you can choose from
3. Save and quit the game
4. Load the game and repeat from step 2.

### Bug prevalence

Happens every time I play

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by TheUltimate0** [comment] 2022-08-07 20:26
It seems that if there's repeat missions they don't double-up. I think this bug might be more accurately "choose from every single mission that a station or outpost has to choose from by reloading until you have all of the options instead of only the 3 that it would normally give you from its set list".

**Comment by Regalis11** [comment] 2022-08-15 07:25
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3388

**Closed by Regalis11** 2022-08-15 07:25 UTC
