### ISSUE TITLE
Water behaves as solid object

### ISSUE THREAD

**Issue by satyaFawcett** [Regalis11/Barotrauma#8304] opened 2022-02-16 09:47 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Rising water inside the hull of my sub pushed me upwards like it was a solid object. It almost clipped me through the floor above. I spammed ragdoll and movement, and it eventually released. It happened twice for sure, and there was one other time where I was walking on the water, but it did not last long like the first 2 times.

**Steps To Reproduce**
No idea.

**Version**
Windows. version: unstable 0.16.3.9 I think, if not then 0.16.4.0

**Additional information**

**Comment by Regalis11** [comment] 2022-02-16 10:02
Duplicate of https://github.com/Regalis11/Barotrauma/issues/8293

**Closed by Regalis11** 2022-02-16 10:02 UTC
