### ISSUE TITLE
Barotrauma Alcohol Bug Report (Drunken Sailor talent not working)

### ISSUE THREAD

**Issue by TheEntityy** [Regalis11/Barotrauma#13016] opened 2023-11-12 15:17 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Having the Drunken Sailor skill on Captain does not negate the vitality decrease of Rum.

### Reproduction steps

1. Start a multiplayer campaign.
2. Choose Captain.
3. Obtain the Drunken Sailor skill.
4. Obtain and consume Rum.
5. Observe negative effects.

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-11-12 15:38
Duplicate of https://github.com/Regalis11/Barotrauma/issues/12916

**Closed by Regalis11** 2023-11-12 15:38 UTC
