### ISSUE TITLE
[0.10.4.0] Multiplayer Campaign - 200+ Enemies at around 30~36% difficulty in Europa Ridge

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3350] opened 2020-07-10 19:43 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Was playing multiplayer campaign and were travelling through Europa Ridge at 30~36% difficulty. Once we sunk to one wave of enemies, we could not recover from that point on. Even if we killed everything we saw, more would come. We had over 200 enemies of Threshers and Mudraptors before the game finally stopped spawning. I had to cheat and use killmonster several times because they just wouldn't stop coming. 

**Version**
0.10.4.0

**Additional information**
4-6 Players in an Orca.

**Comment by Rokvach** [comment] 2020-07-13 07:10
This was also sighted happening in 10% difficulty

**Comment by Regalis11** [comment] 2020-07-13 09:54
This seems to be caused by the way the events are configured: the timed events can spawn hundreds of enemies if the rounds last long enough.

**Comment by ezjamsen** [comment] 2020-07-14 14:06
Timed events are as intended, but the intensity limits were poorly defined for the higher difficulty sets, and the intensity calculations lowballed the seriousness of enemies outside the sub.

Increased sensitivity of the intensity system relating to enemies outside the hull, and then increased the maximum intensity thresholds for all events, particularly the timed events.

**Comment by Orb370** [comment] 2020-08-30 22:14
Hello, I wanted to leave feedback on this as well.

I have a crew of experienced seamen and we like to play the game semi-seriously. We've been cruising on the humpback at 50% difficulty for awhile now, and it's been a good balance. Easier early on, harder later on, but being balanced out by upgrades. However, once we reached The Aphotic Plateau things started sliding more into frustrating than fun. The waves take so long to kill (particularly skull threshers are just eating all our ammo), that more waves spawn once we finish the last one. It's a never ending assault by murderous fish. It's completely destroyed the pacing of the game I normally enjoy, which is moments of strong intensity followed by moments of calm.  It's just always flooding and fish.

There should be more time between waves if they contain tougher enemies. For reference the mission difficulties are just shy of 40% right now.

**Comment by Kaillera** [comment] 2020-08-31 00:34
Difficulty slider doesn't affect campaign. the maps has their own difficulty setting @Orb370. The 30~55% maps are already being tweaked for next version as it's quite brokenly too much currently.

**Comment by Kaillera** [comment] 2020-09-05 20:00
Was at 35% with a thalamus wreck literally hugging me (without causing problem to my sub). There was quite a lot of thresher/crawler/mudraptor being thrown at me, but definitely a lot less than 0.10.4 and varied than just bone threshers. I eventually cleared out the entire event list in about 10 minutes while defeating the thalamus and defending the sub.

Sadly I can't extract the entire event list that happened during these tests.

**Comment by Rokvach** [comment] 2020-09-07 08:50
Moved back to todo

**Comment by ezjamsen** [comment] 2020-09-16 06:41
Timer spawns will be fixed with a new system shortly.

**Comment by Rokvach** [comment] 2020-09-28 12:04
Closing.

**Closed by Rokvach** 2020-09-28 12:04 UTC
Labels: Bug, Design
