### ISSUE TITLE
Crash game on way

### ISSUE THREAD

**Issue by raker99** [Regalis11/Barotrauma#2717] opened 2020-04-26 16:48 UTC
Today game chrash about 10x. :( Everytime when I was on my way on second mission.

Barotrauma Client crash report (generated on 26.4.2020 18:39:24)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

B88397013C2378C4A99C3E19DEBEE54F

Game version 0.9.9.0 (ReleaseWindows, branch release, revision 0534150c8)
Graphics mode: 1920x1080 (Fullscreen)
VSync ON
Selected content packages: Vanilla 0.9, ALIEN - XENOMORPH, REALLYBIGMAP, Sweet Pea
Level seed: KogavostokOshan
Loaded submarine: Sweet Pea (B3B99D2827F32530324404A9FDE9EEDF)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.18363.0 64 bit
    GPU name: NVIDIA GeForce GTX 1050 Ti
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Boolean CheckValidity(Barotrauma.PhysicsBody)
Stack trace: 
   at Barotrauma.Ragdoll.CheckValidity(PhysicsBody body)
   at Barotrauma.Ragdoll.CheckValidity()
   at Barotrauma.Ragdoll.Update(Single deltaTime, Camera cam)
   at Barotrauma.Ragdoll.UpdateAll(Single deltaTime, Camera cam)
   at Barotrauma.GameScreen.Update(Double deltaTime)
   at Barotrauma.GameMain.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Barotrauma.Program.Main(String[] args)

Last debug messages:
[26.4.2020 18:36:55] Overriding all background creatures with 'Mods/REALLYBIGMAP/Map/RBM_BGFish.xml'
[26.4.2020 18:11:38] Overriding all ruin configuration parameters using the file Mods/REALLYBIGMAP/Map/RBM_Ruins.xml.
[26.4.2020 18:11:37] Overriding all background creatures with 'Mods/REALLYBIGMAP/Map/RBM_BGFish.xml'
[26.4.2020 18:09:16] Overriding all location types with 'Mods/REALLYBIGMAP/Map/RBM_LocationTypes.xml'
[26.4.2020 18:09:16] Overriding all level object prefabs with 'Mods/REALLYBIGMAP/Map/RBM_LevelObjectPrefabs.xml'
[26.4.2020 18:09:09] Overriding the level generation parameters and biomes with 'Mods/REALLYBIGMAP/Map/RBM_LevelGen.xml'
[26.4.2020 18:09:08] Overriding the map generation parameters with 'Mods/REALLYBIGMAP/Map/RBM_MapGen.xml'
[26.4.2020 18:09:02] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[26.4.2020 18:09:02] Content package load order: Vanilla 0.9  |  ALIEN - XENOMORPH  |  REALLYBIGMAP  |  Sweet Pea
[26.4.2020 18:09:02] Content package load order: Vanilla 0.9  |  ALIEN - XENOMORPH  |  REALLYBIGMAP  |  Sweet Pea
[26.4.2020 18:08:56] Attempting to open ALC device "OpenAL Soft"
[26.4.2020 18:08:55] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[26.4.2020 18:08:54] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[26.4.2020 18:08:51] Logged in as raker99svk (SteamID STEAM_1:1:31102683)

**Comment by Regalis11** [comment] 2020-04-26 18:07
Since we haven't encountered this error before or gotten any other reports about it, I suspect that it could be caused by some of the mods you have installed. We'll need to take a closer look into this and see if that's the case, but for now I think it might be worth a shot to try disabling the mods and see if the error goes away. Sorry for the trouble!

**Comment by Regalis11** [comment] 2020-05-11 08:30
Added some extra null checks and logging to help diagnose this. https://github.com/Regalis11/Barotrauma-development/commit/b47f3c0cf651a9975966e9aef2e7627bf44430ea

**Comment by Rokvach** [comment] 2020-05-16 11:57
I don't think there's a any clear way to fully test this, the issue shouldn't cause a crash anymore so I think its just better to close this ticket and see if it happens again. Closing.

**Closed by Rokvach** 2020-05-16 11:57 UTC
Labels: Bug, Code, Crash, Modding, Needs testing
