### ISSUE TITLE
Not displaying text when interacting with Culstist near beginning of game

### ISSUE THREAD

**Issue by BobbySpivey** [Regalis11/Barotrauma#11515] opened 2023-03-14 14:53 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I responded to the cultist in a way that I assume advances the quest and instead of giving me a response he displays this:
EventText.waytoascension1.o1.c1 

### Reproduction steps

Start campaign. 
Talk to cultist until he asks you about the Second Metamorphosis 
Respond with "Emerging from the cocoon of your human body." 
Get issue. 

![image](https://user-images.githubusercontent.com/18010820/225039717-03dc17c4-8355-4a7b-9556-75bd267bc300.png)

### Bug prevalence

Just once

### Version

v1.0.7.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-03-15 09:27
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11502

**Closed by Regalis11** 2023-03-15 09:27 UTC
