### ISSUE TITLE
Random bugs with alien ruins

### ISSUE THREAD

**Issue by Zangdorx** [Regalis11/Barotrauma#7201] opened 2021-11-07 05:27 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
1- Some areas in alien ruins can trap you. You can swim in, but you can't swim out by the same entrance, even though there is no wall or anything that should prevent you from leaving. Cutting through multiple other walls allowed us to escape.
2- Using the ruin scanner in alien ruins is counter-intuitive. Placing it near the scan target will sometimes start the scan, but sometimes it won't. Maybe the acceptable range for the scan should be greater, or closer to the scan mark, or there is a bug that makes it not work sometimes.
3- Scanning a ruin completely gave the "mission complete" notification, but on boarding at the correct station afterward, the mission was said to be not completed and did not give any rewards.

**Steps To Reproduce**
1- Explore many corners in many alien ruins. Probably hard to reproduce.
2- Try using the ruin scanner in a ruin scanning mission at the place of the scan mark. Sometimes, it may fail. It seems to fail more frequently with some people than with others.
3- Complete a ruin scanning mission, and dock at the destination station. The mission might be marked as a failure even if a notification had been received saying that the objective is complete.

**Version**
v0.15.13.0
Windows 10

**Additional information**
Playing without mods.

**Comment by ekqvist** [comment] 2021-11-08 16:08
Thanks for the report!

First, the only place where I could so far find an issue with a hole in the wall was in the module below.

![image](https://user-images.githubusercontent.com/16864465/140775986-0d305b0a-8dff-42a6-9c66-b8f68131be00.png)

There was an issue where the gap was actually only at the center of the hole so you couldn't go through the hole near the edges. If you had an issue with a different part of the ruins, it would help if you could attach a save from the level where this happened.

Second, the max distance where you'll start to see the scan target icon is about 15 meters and the scan range of the scanner is around 10 meters. So, it's possible you're slightly too far from the target when you attempt to start scanning it.

Third, the only way I could reproduce the issue of the mission failing was by leaving at least one of the scanners behind. Did you have all the three scanner items with you on your sub as you exited the level? It is currently a requirement for the mission to be completed. So, if any of the scanners were destroyed or left behind in the level, the mission will fail even if you have scanned all the targets.

**Comment by Zangdorx** [comment] 2021-11-13 19:39
First, we got stuck right there, in `Alien_MaintenanceTunnels1`, in the orange circle: 
![image](https://user-images.githubusercontent.com/44536943/141656765-b324d207-0337-46dc-8770-fc0a72ffa894.png)

Second, is the scan target appearing at a fixed point in space? If so, we tried placing the scanner right on top of it, and we moved it a lot in the general area around the target, without success. Are there other considerations for the scan? For instance, can a scanner be used multiple times?

Third, that's exactly what happened, indeed. We did not notice that it was a requirement to bring back the scanners, and we abandonned one that was stuck in a wall.

**Comment by ekqvist** [comment] 2021-11-15 11:08
1. Fixed getting stuck in the corner of the module in Regalis11/Barotrauma-development@217f6b3.
2. Yes, the scan target is a fixed point and the icons point to those positions. It is enough to place a scanner within an acceptable distance from that to start the scan. You should see the scan progress bar appear when you are close enough. One scanner can be used to scan all the targets if you wish.
3. Are you saying that you had (accidentally or purposefully) left behind a scanner you had attached to a wall? Or that you had attached a scanner to a wall but couldn't detach it?

**Comment by Zangdorx** [comment] 2021-11-15 13:39
2. We placed the scanner right on top of the marker, and moved it aroud a bit, without the scan beginning. We then called our friend from the submarine, which came and placed the scanner. It then began to scan. I don't understand why it did not work before with the information that you gave me. I'm mostly sure that we placed it really close from the marker.

3. We purposely left behind a scanner we had attached to a wall, because it had been placed inside a wall segment. We probably could have gotten it back if we used a plasma cutter to break the wall segment, but we misread the mission statement and did not know that we had to bring back the scanners. Therefore, we chose to let it there, and failed the mission.

**Comment by ekqvist** [comment] 2021-11-18 10:55
2. Unfortunately, I'm still unable to reproduce this issue. Not sure what the cause is. Is this something you have encountered multiple times?
3. This is somewhat of an issue with every item that can be attached to walls. They can be attached inside wall sections, but then you will be unable to interact with them. I have made a note of this to the development team to see if we can address this one way or another at some point.

**Comment by Rokvach** [comment] 2021-12-07 08:39
Tested, working correctly. Closing.

**Closed by Rokvach** 2021-12-07 08:39 UTC
Labels: Bug, Need more info, Needs testing, Code
