### ISSUE TITLE
Make Non-Idle Characters Consume Oxygen Faster- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1983] opened 2020-01-11 06:11 UTC
Barotrauma receives more features that would make the gameplay itself easier such as automatic machine guns. I believe it should be countered by things that make sense in real life to make the game itself look more impressive for how realistic it tries to be.

By oxygen consumptions I mean faster oxygen drain from rooms, oxygen and oxygenite tanks,

Examples:
- +10% more oxygen consumption while walking.
- +20% more oxygen consumption while crouching. Yes, crouching is tiring.
- +50% more oxygen consumption while walking and crouching at the same time.
- +15% more oxygen consumption while repairing or sabotaging a device.
- +20% more oxygen consumption while swimming (not just being in water).
- +10% more oxygen consumption while using underwater scooter underwater.
- +10% more oxygen consumption while being idle on the ladder.
- +25% more oxygen consumption while moving on a ladder.

I would also make characters under the effect of hyperzine consume oxygen 300% faster just so it won't be "overpowered" (OP in short) and give oxygen tanks greater capacity.

**Comment by hubismal** [comment] 2020-01-11 16:52
just a heads up i'm pretty sure this is a duplicate of another feature request

**Comment by Regalis11** [comment] 2020-01-13 10:21
Duplicate of #1929

**Closed by Regalis11** 2020-01-13 10:21 UTC
