### ISSUE TITLE
Can't buy new torrets for the submarine

### ISSUE THREAD

**Issue by Grifond** [Regalis11/Barotrauma#9410] opened 2022-06-18 21:58 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

We are using latin Spanish Language, and the problem happend when we want to buy a new torret for the submarine. The error says: "Failed to parse the string "COLOR GUI.GREEN" to Color" 
![Error mejorar submarino](https://user-images.githubusercontent.com/72765706/174458040-410b3adb-6e3a-4913-9b2e-38bef80f3546.png)
![Error mejorar submarino2](https://user-images.githubusercontent.com/72765706/174458077-4006113d-79e6-46de-88bc-da1cfde23613.png)

We find out that if we change the language to "English" the problem doesn't exists.

### Reproduction steps

1.Start multiplayer campanign (in Latin american spanish)
2.Try to upgrade the submarine adding torrets in a station

### Bug prevalence

Happens every now and then

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-06-19 10:12
Duplicate of https://github.com/Regalis11/Barotrauma/issues/9408

**Closed by Regalis11** 2022-06-19 10:12 UTC
