### ISSUE TITLE
The game crashes when i click server browser

### ISSUE THREAD

**Issue by forgen101** [Regalis11/Barotrauma#2223] opened 2020-02-08 19:44 UTC
**Description**
The game crashes in I click browse servers

**Version**
0.9.6.0 
**Additional information**
here are the crash logs
[crashreport (29).log](https://github.com/Regalis11/Barotrauma/files/4175052/crashreport.29.log)

**Comment by 0tar** [comment] 2020-02-08 19:51
I'm having the same issue. Every part of the game works except when I click on the server browser.

Crash log:
[crashreport (10).log](https://github.com/Regalis11/Barotrauma/files/4175062/crashreport.10.log)

**Comment by NewsKendus** [comment] 2020-02-22 06:05
Same issue, still happening. Have tried reinstalling normally, verifying cache, reinstalling by deleting everything and then downloading all new files, messing with firewall settings, disabling antivirus, etc.

Crash logs:
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/4238877/crashreport.log)
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/4238878/crashreport.2.log)

**Comment by Regalis11** [comment] 2020-02-24 13:03
Duplicate of #2325

**Closed by Regalis11** 2020-02-24 13:03 UTC
Labels: Bug, Code, Crash
