### ISSUE TITLE
Crash Report:   Void ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion

### ISSUE THREAD

**Issue by CharlesRAy** [Regalis11/Barotrauma#4056] opened 2020-10-11 01:54 UTC
Crash Report

If solved please message me with insight.
Please excuse my characters name.

System info:
    Operating system: Microsoft Windows NT 6.2.9200.0 64 bit

Exception: Collection was modified; enumeration operation may not execute. (System.InvalidOperationException)
Target site: Void ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
Stack trace: 
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Barotrauma.Items.Components.RepairTool.Repair(Vector2 rayStart, Vector2 rayEnd, Single deltaTime, Character user, Single degreeOfSuccess, List`1 ignoredBodies) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Holdable\RepairTool.cs:line 297
   at Barotrauma.Items.Components.RepairTool.Use(Single deltaTime, Character character) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Holdable\RepairTool.cs:line 149
   at Barotrauma.Item.Use(Single deltaTime, Character character, Limb targetLimb) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 2055
   at Barotrauma.AIObjectiveCombat.Attack(Single deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjectiveCombat.cs:line 888
   at Barotrauma.AIObjectiveCombat.Act(Single deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjectiveCombat.cs:line 220
   at Barotrauma.HumanAIController.Update(Single deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\HumanAIController.cs:line 232
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2228
   at Barotrauma.GameScreen.Update(Double deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 184
   at Barotrauma.GameMain.Run() in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 352
   at Barotrauma.Program.Main(String[] args) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 51

Last debug messages:
   10/10/2020 7:55:59 PM - [10/10/2020 7:55:59 PM]
  Saving banlist
   10/10/2020 7:55:59 PM - [10/10/2020 7:55:59 PM]
  Terminalcell has died (Cause of death: Burn)
   10/10/2020 7:55:58 PM - [10/10/2020 7:55:58 PM]
  Alvin Rios used Crowbar on Omari Lyons.
   10/10/2020 7:55:58 PM - [10/10/2020 7:55:58 PM]
  Randi Leonard: Do you really want to take that path?
   10/10/2020 7:55:57 PM - [10/10/2020 7:55:57 PM]
  Alvin Rios: I'm bleeding out!
   10/10/2020 7:55:55 PM - [10/10/2020 7:55:55 PM]
  Masako Bradley started repairing Battery
   10/10/2020 7:55:54 PM - [10/10/2020 7:55:54 PM]
  CuntFuck opened Custom Windowed Door
   10/10/2020 7:55:54 PM - [10/10/2020 7:55:54 PM]
  Lucas Buckley: Hull breach in gunnery compartment!
   10/10/2020 7:55:54 PM - [10/10/2020 7:55:54 PM]
  Lucas Buckley: Hostiles in gunnery compartment!
   10/10/2020 7:55:53 PM - [10/10/2020 7:55:53 PM]
  Terminalcell has died (Cause of death: Internal damage)
   10/10/2020 7:55:53 PM - [10/10/2020 7:55:53 PM]
  Lucas Buckley: Hostiles in gunnery compartment!
   10/10/2020 7:55:53 PM - [10/10/2020 7:55:53 PM]
  Omari Lyons: Repairing ballast tank a. A few more holes to go!
   10/10/2020 7:55:53 PM - [10/10/2020 7:55:53 PM]
  Outer wall repaired by Omari Lyons
   10/10/2020 7:55:53 PM - [10/10/2020 7:55:53 PM]
  Romeo Sunderland: One leak fixed in ballast tank a!

**Comment by Regalis11** [comment] 2020-10-12 07:09
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3896

**Closed by Regalis11** 2020-10-12 07:09 UTC
