### ISSUE TITLE
Watchers seem to spawn more than incredibly rarely

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#11603] opened 2023-03-19 23:18 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

So, ive noticed this. Over about 3 total playthroughs, ive met just as many Watchers during them all in total: 3. They seemingly just dont appear at all anymore and spawn just about as rarely as Hammerhead matriarchs if not even rarer. This makes their spawn rate either ridiculusly low, or somehow only appearing in incredibly specific situations. No clue what caused this, since watchers for a while werent that rare of an occurance a decent bit back since 1.0 but for a while now Watchers just seem like an anomaly, which is a shame

### Reproduction steps

1.Progress through campaigns
2.Count the number of times you encounter Watchers
3.Note that they are only very rarely occuring, probably too rarely frankly

### Bug prevalence

Happens regularly

### Version

Unstable (v1.1.3.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Rehexr** [comment] 2023-03-20 17:37
Very wierldy, now going on further, ive not had this issue in singleplayer. Is it perhaps for some reason only very rare in mp campaigns?

**Comment by itchyOwl** [comment] 2023-07-03 18:03
Can't repro, but there were some monster event sets in the aphotic plateau that were incorrectly configured. Yet Watchers seem to spawn normally at least in the great sea and the hydrothermal wastes. I doubt multiplayer game mode affects this, but moving to QA investigates.

**Comment by itchyOwl** [comment] 2023-07-03 18:04
There hasn't been any changes to the monster spawn events that could affect this since last september.

**Comment by itchyOwl** [comment] 2023-09-27 11:07
That shouldn't happen, because all the spawns can be triggered either by distance or the time. But it's possible that you just don't encounter the monsters even if they spawned.

**Comment by Regalis11** [comment] 2023-10-09 11:36
We unfortunately haven't been able to find a way to reproduce this, watchers seem to spawn normally during the multiplayer campaign (and don't seem that rare from the aphotic plateau onwards).

**Closed by Regalis11** 2023-10-09 11:36 UTC
Labels: Bug, Need more info, Needs testing, Design, Balance
