### ISSUE TITLE
You move faster while holding a diving suit with both hands

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#11881] opened 2023-04-21 08:24 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I held a diving suit which contained an oxygenite tank and my movement speed increased

### Reproduction steps

1. hold a diving suit with both hands
2. put an oxygenite tank in its inventory
3. your movement speed increases

### Bug prevalence

Just once

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-04-21 08:32
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11672

**Closed by Regalis11** 2023-04-21 08:32 UTC
