### ISSUE TITLE
Multiple crashes of Unstable

### ISSUE THREAD

**Issue by Bozhdynsky** [Regalis11/Barotrauma#4009] opened 2020-10-05 15:59 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Game crashed multiple times, usually around wrecks or upon killing an enemy near a wreck. Last time crash occured when exiting Dugong and venturing towards Dugong_wreck, crashing just when the wreck's conning tower was visible. Will try with all mods unchecked but none were in actual use.

**Steps To Reproduce**
Just cruising along. Did not crash a couple of times during very quick missions.

**Version**
0.10.600.0 (UnstableWindows, branch dev, revision 59762813db)

**Additional information**
[crashreport (12).log](https://github.com/Regalis11/Barotrauma/files/5328435/crashreport.12.log)
[crashreport (13).log](https://github.com/Regalis11/Barotrauma/files/5328436/crashreport.13.log)
[crashreport (14).log](https://github.com/Regalis11/Barotrauma/files/5328437/crashreport.14.log)
[crashreport (15).log](https://github.com/Regalis11/Barotrauma/files/5328438/crashreport.15.log)
[crashreport (16).log](https://github.com/Regalis11/Barotrauma/files/5328440/crashreport.16.log)
[crashreport (10).log](https://github.com/Regalis11/Barotrauma/files/5328441/crashreport.10.log)
[crashreport (11).log](https://github.com/Regalis11/Barotrauma/files/5328442/crashreport.11.log)

**Comment by Bozhdynsky** [comment] 2020-10-05 16:19
Another crash whilst circling around a wreck trying to bet rid of enemies. This time all mods unchecked but using an existing save.
[crashreport (17).log](https://github.com/Regalis11/Barotrauma/files/5328632/crashreport.17.log)

**Comment by someone972** [comment] 2020-10-05 16:50
All crash reports have the same Barotrauma.EnemyAIController.set_Reverse(Boolean value) NullReferenceException failure. Crash signature is the same as #3971 which was marked duplicate of #3964 which has since been fixed in their internal repo (hasn't made it's way to dev branch of the public yet it seems).

**Comment by Regalis11** [comment] 2020-10-06 06:53
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3964

**Closed by Regalis11** 2020-10-06 06:53 UTC
