### ISSUE TITLE
City Outpost is partially flooded

### ISSUE THREAD

**Issue by Conduit08** [Regalis11/Barotrauma#11588] opened 2023-03-18 19:53 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Upon reaching and spawning into a city outpost, the first floor was partially flooded. Outposts are supposed to be dry.

### Reproduction steps

1. Start a singleplayer campaign.
2. Navigate to a city outpost.
(Note: also try partially flooding the player's submarine and then reaching a city outpost.

### Bug prevalence

Happens regularly

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-03-18 20:04
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11433

**Closed by Regalis11** 2023-03-18 20:04 UTC
