### ISSUE TITLE
Misplaced shuttle after leaving outposts in Campaign

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#5026] opened 2021-02-10 23:34 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
After leaving an outpost in campaign, some shuttles will not be docked in the next area, despite being properly docked in the outpost. 

**Steps To Reproduce**
-Load this submarine in campaign:
[DOMA Prototype mk8.zip](https://github.com/Regalis11/Barotrauma/files/5962324/DOMA.Prototype.mk8.zip)
-Get **"Invalid docking port network event (can't dock to null)"** in console
-All shuttles are properly docked
-Move to the next area
-Shuttle on the top right is misplaced, not docked and stuck inside the sub

**Version**
v0.12.0.2 stable

**Additional information**
No matter how I changed the "Force docking direction" property, it's still undocked

https://user-images.githubusercontent.com/73229309/107586709-c2dd1280-6c00-11eb-9aaf-265c333ede77.mp4

Jittery shuttle:
https://user-images.githubusercontent.com/73229309/107586794-ed2ed000-6c00-11eb-97ef-68baabc9fc0f.mp4

**Comment by Regalis11** [comment] 2021-02-11 16:28
This seemed to happen because there's an automated circuit that undocks the sub, and the AND component that checks whether to undock hasn't received anything during the first frame it's updated, which leads to the shuttle being undocked immediately, before the physics engine has time to move the shuttle to the correct position. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1cd0921aba1a36313292d8cd0118974546011761

**Comment by ubertpendragon** [comment] 2021-02-11 19:01
Nice, I didn't think about the components since the railgun shuttle also uses the same auto-dock proximity circuit but doesn't have this issue

**Comment by Rokvach** [comment] 2021-02-15 09:27
Tested, wasn't able to reproduce the issue, seems to be working correctly. Closing.

**Closed by Rokvach** 2021-02-15 09:27 UTC
Labels: Bug, Code, Medium Prio
