### ISSUE TITLE
[Unstable] Cargo mission reward preview is incorrect in the mission selection screen/world map

### ISSUE THREAD

**Issue by TheMinerBoy** [Regalis11/Barotrauma#9930] opened 2022-09-25 05:52 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I got a cargo transport mission from an outpost manager at the city in the top left while using the Dugong submarine, and it said that it would give me 3,200mk (200mk X 16) for completing it in the mission selection screen. Obviously, this is wrong because the Dugong only has 8 cargo slots. This was confirmed when I actually started the round, at which point it told me that I would get only 1,600mk for completing the mission.
![Barotrauma 2022-09-25 10_11_31 AM](https://user-images.githubusercontent.com/81781733/192302924-215692a5-1361-4a2f-bd57-0e2a40e3bc14.png)

### Reproduction steps
1. Start a singleplayer campaign with the world seed specified below.
2. Get a cargo transport mission from the outpost manager at the city in the top left of the map before switching your submarine.

### Bug prevalence

Every time I play

### Version

0.19.6.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Map Seed: fLV4dqrF
```

**Comment by Regalis11** [comment] 2022-09-25 12:18
Thank you for the report!

I'm afraid I could not reproduce this: I tested a couple of different cargo missions, and they all seemed to display the reward correctly.
![image](https://user-images.githubusercontent.com/14351070/192142949-ae99dc0e-6a26-4ec8-ba74-4bb04b9f655d.png)

Did this happen in single player or multiplayer? Had you switched submarines at some point - I'm wondering if it might've calculated the reward for the previous sub for some reason?

**Comment by TheMinerBoy** [comment] 2022-09-25 16:17
This is very early-game in a singleplayer campaign, and I did not switch my submarine. I think the error was in the dialogue from the outpost manager or the preview immediately after the dialogue? I'll try to reproduce it and screenshot it if I can.

**Comment by TheMinerBoy** [comment] 2022-09-25 17:14
Yesss. I found the error in the mission selection screen. Same campaign save, same outpost, same submarine. The mission says 200mk X 16, but the dugong only has 8 cargo slots. I have a screenshot, but I don't know where to put it.

**Comment by TheMinerBoy** [comment] 2022-09-26 14:48
> Thank you for the report!
> 
> I'm afraid I could not reproduce this: I tested a couple of different cargo missions, and they all seemed to display the reward correctly. ![image](https://user-images.githubusercontent.com/14351070/192142949-ae99dc0e-6a26-4ec8-ba74-4bb04b9f655d.png)
> 
> Did this happen in single player or multiplayer? Had you switched submarines at some point - I'm wondering if it might've calculated the reward for the previous sub for some reason?

I updated the bug report with more information.

**Comment by Regalis11** [comment] 2022-09-27 12:22
Turns out the issue occurred when the sub was docked to a colony: the problem was that cargo containers in the outpost were counted as containers available for the cargo, and only colonies have cargo containers in them. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7834b2684db1b445aefce235faaed275e21e9a20

**Comment by Rokvach** [comment] 2022-09-30 06:10
Tested, working correctly. Closing.

**Closed by Rokvach** 2022-09-30 06:10 UTC
Labels: Bug, Code, Unstable
