### ISSUE TITLE
v0.1400.7.0 - Editor cannot delete ammo boxes in loaders and ammo shelves

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#6413] opened 2021-08-09 16:59 UTC
**Description**
In submarine editor 'box' type ammo such as chaingun, coilgun, and laser cannot be deleted from certain containers once they are placed. For example their respective loaders and the ammo shelf, leaving the only way to have an empty container or replace with a different ammo type to delete the container and place a new one. 

Perhaps something else in the GUI taking input priority? or the game is trying to equip the box into a nonexistent character's hands ?

**Expected Behavior**
Double-clicking to remove & right click to remove behavior consistent with other items in containers.

**Steps To Reproduce**
- Place ammo box in a loader or shelf
- Attempt to remove the ammo box by selecting container and double-clicking or right clicking the item in its slot.

![image](https://user-images.githubusercontent.com/55356135/128744847-aa590024-8bd5-40c5-acbf-3ac39d329d62.png)

- [x] Bienvenue corpofascists

**Comment by Regalis11** [comment] 2021-08-09 17:22
Duplicate of https://github.com/Regalis11/Barotrauma/issues/6367

**Closed by Regalis11** 2021-08-09 17:22 UTC

**Comment by Tsunder** [comment] 2021-08-10 22:50
> * [x]  Bienvenue corpofascists

@Ek-Videogames care to elaborate?
