### ISSUE TITLE
On docking, NPCs teleport to random parts of base and drop their diving suits

### ISSUE THREAD

**Issue by Wollus** [Regalis11/Barotrauma#4057] opened 2020-10-11 11:08 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If an NPC on my sub is wearing a diving suit when I dock, they get teleported to a random part of the base, then immediately drop their suits. This has resulted in my diving suits gradually disappearing from my sub.

**Steps To Reproduce**
* Get NPC to wear diving suit to fix a leak
* Dock with a base

**Version**
Latest as of cutting this ticket.

**Comment by Regalis11** [comment] 2020-10-12 10:21
Related to https://github.com/Regalis11/Barotrauma/issues/3956, we should give this a test in the current unstable and see if it still occurs

**Comment by Rokvach** [comment] 2020-10-15 08:24
This is still an issue. Moving back to todo.

Repro steps:
1. Undock from outpost
2. Ask bots to follow
3. Equip a diving suit and see that the bots equip one too
4. Dock back to the outpost
5. Bots will drop the diving suits inside the outpost

**Comment by itchyOwl** [comment] 2020-10-19 14:18
It's not strictly a bug. The bots behave as intended, although I didn't take this scenario into account. What should happen then? Should we a) prevent bots from dropping a diving suit when they are inside outposts or b) remove the diving suits automatically and place them in containers c) both d) something else? I can quickly fix this by doing a, but other options require a bit more work, so I'd like to have some design support here.

**Comment by itchyOwl** [comment] 2020-10-20 17:13
Items dropped by the bots in the outposts should teleport inside cargo bay on leaving. Implemented in Regalis11/Barotrauma-development@deb3010.

**Comment by Rokvach** [comment] 2020-10-23 09:33
I think we should revert the change where a bot keeps their diving suit equipped when entering a outpost with it on as that's just unnecessary resource usage, they will eventually drop the suit anyways when its out of oxygen so I would much rather see them drop the suit at the start and save oxygen rather than drop it when the oxygen is depleted as the end result is the same in both. 

Should player worn diving suits also be teleported? As its easy to forget to bring the diving suit back in to the sub and new players wouldn't know that they would need to do that.

**Comment by NyarlathotepZERO** [comment] 2020-10-24 04:10
> It's not strictly a bug. The bots behave as intended, although I didn't take this scenario into account. What should happen then? Should we a) prevent bots from dropping the diving suits when they are inside outposts or b) remove the diving suits automatically and place them in containers c) both d) something else? I can quickly fix this by doing a, but the other options require a bit more work, so I'd like to have some design support here.

I'd expect that the NPC should put the suit back from where they got it, if that was not possible, then either in the next nearest available locker or on the floor in front of the locker it was picked up from. no less than what I would hope (but not expect) from a player.

**Comment by itchyOwl** [comment] 2020-10-26 10:59
We could teleport the suits back to where they belong to, but that's a slightly more complex to implement. So I just used a simpler approach first, because I thought it's a marginal case anyway. I don't think bots should return the suits to the sub manually, as it takes time and is always a bit error prone. Ez suggested that we would automatically unequip the suits and teleport them back, but that could lead into issues if the player intentionally leaves the bots wearing the suits. So before implementing that, I would like to be sure that there can never be a case where it would be intentional.

**Comment by Rokvach** [comment] 2021-01-05 15:48
I think this is working fine now as it is, so bots spawn in with suits and when they drop them those dropped suits will be teleported to the submarine on the next round.

**Comment by itchyOwl** [comment] 2021-01-07 09:11
I think we can close this and create a new ticket if we want to change the behavior.

**Closed** 2021-01-13 13:29 UTC
Labels: Code, Design, Feature request
