### ISSUE TITLE
[Dev version] Uppercase letters turn into lowercase letters when editing properties of items in the sub editor

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#892] opened 2018-11-07 03:18 UTC
Which is a bit problematic, since some of the settings are case sensitive. Also, when editing description or owner of things like idcards, it makes the name of the owner begin with a lowercase letter.

**Comment by Regalis11** [comment] 2018-11-07 09:36
I wasn't able to reproduce this on anything else than the tag property, where this is intentional - the tags always converted to lower case to make them case-insensitive. Converting the job and owner names was not intentional though, and that should be now fixed.

If you know a way to reproduce the issue on some other property, please let me know!

**Comment by BillCombs** [comment] 2018-11-07 10:52
When editing spawnpoints you can make idcard tags have uppercase letters.
![wilson-pc-2018-nov-7-003](https://user-images.githubusercontent.com/38168249/48127081-75e99380-e2b5-11e8-82f0-81927284aae9.jpg)
But when changing the "picked required" setting of a button, it's converting uppercase letters into lowercase ones.
![wilson-pc-2018-nov-7-006](https://user-images.githubusercontent.com/38168249/48127082-76822a00-e2b5-11e8-8cae-358b5fc37f96.jpg)
It should either not convert the ones in the "picked required" or convert the ones in the settings of spawnpoints.

**Comment by Regalis11** [comment] 2018-11-07 11:22
Ah, thanks for pointing that out! The tags in spawnpoint should be converted to lower case because all tags are lower case.

**Closed** 2018-11-07 14:56 UTC
Labels: bug, dev branch
