### ISSUE TITLE
Random Crash 

### ISSUE THREAD

**Issue by JacekSchool** [Regalis11/Barotrauma#4843] opened 2021-01-20 23:49 UTC
**Description**
The game just crashed. A Cash message was shown and my current progress lost.

**Steps To Reproduce**
I was fighting a Moloch in the starter sub (completing a mission), 5 crew total (medic, pilot, mechanic-engineer, electric-engineer, assistant), all set to do tasks automatically. 
**Version**
0.11.0.10 (ReleaseWindows, branch release, revision dc7157029e)

**Additional information**
CRASH LOG:

Barotrauma Client crash report (generated on 20/01/2021 23:44:18)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

47BDC83F092CDFE5B755C0308161F31E

Game version 0.11.0.10 (ReleaseWindows, branch release, revision dc7157029e)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: KrytogorskAlkonost
Loaded submarine: Dugong (971434E627435B9DA342CA367BB8BD0B)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.18363.0 64 bit
    GPU name: Intel(R) UHD Graphics 630
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.
 (SharpDX.SharpDXException)
Device removed reason: HRESULT = 0x887A0006
Target site: Void CheckError()
Stack trace: 
   at SharpDX.Result.CheckError()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 1017
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 511
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59

Last debug messages:
[20/01/2021 23:28:04] Generating an outpost for the start of the level... (Location: Krytogorsk City, level type: LocationConnection)
[20/01/2021 23:28:03] Generating an outpost for the end of the level... (Location: Alkonost Research Facility, level type: LocationConnection)
[20/01/2021 23:27:51] Transitioning to KrytogorskAlkonost (current location: Alkonost Research Facility, selected location: Krytogorsk City, leaving sub: Dugong, at start: True, at end: False, transition type: LeaveLocation)
[20/01/2021 23:17:05] Generating an outpost for the start of the level... (Location: Alkonost Research Facility, level type: Outpost)
[20/01/2021 23:16:54] Transitioning to Alkonost (current location: Euphemus Linea, selected location: Alkonost Research Facility, leaving sub: Dugong, at start: False, at end: True, transition type: ProgressToNextLocation)
[20/01/2021 22:42:25] Generating an outpost for the end of the level... (Location: Alkonost Research Facility, level type: LocationConnection)
[20/01/2021 22:42:24] Generating an outpost for the start of the level... (Location: Euphemus Linea, level type: LocationConnection)
[20/01/2021 22:42:12] Transitioning to Euphemus LineaAlkonost (current location: Euphemus Linea, selected location: Alkonost Research Facility, leaving sub: Dugong, at start: True, at end: False, transition type: LeaveLocation)
[20/01/2021 22:31:14] Generating an outpost for the start of the level... (Location: Euphemus Linea, level type: Outpost)
[20/01/2021 22:31:03] Transitioning to Euphemus Linea (current location: The city of Pastonia, selected location: Euphemus Linea, leaving sub: Dugong, at start: False, at end: True, transition type: ProgressToNextLocation)
[20/01/2021 21:57:31] Generating an outpost for the end of the level... (Location: Euphemus Linea, level type: LocationConnection)
[20/01/2021 21:57:31] Generating an outpost for the start of the level... (Location: The city of Pastonia, level type: LocationConnection)
[20/01/2021 21:57:19] Transitioning to PastoniaEuphemus Linea (current location: The city of Pastonia, selected location: Euphemus Linea, leaving sub: Dugong, at start: True, at end: False, transition type: LeaveLocation)
[20/01/2021 21:43:42] Generating an outpost for the start of the level... (Location: The city of Pastonia, level type: Outpost)
[20/01/2021 21:43:31] Transitioning to Pastonia (current location: St. May, selected location: The city of Pastonia, leaving sub: Dugong, at start: False, at end: True, transition type: ProgressToNextLocation)
[20/01/2021 21:09:57] Generating an outpost for the end of the level... (Location: The city of Pastonia, level type: LocationConnection)
[20/01/2021 21:09:56] Generating an outpost for the start of the level... (Location: St. May, level type: LocationConnection)
[20/01/2021 21:09:43] Transitioning to St. MayPastonia (current location: St. May, selected location: The city of Pastonia, leaving sub: Dugong, at start: True, at end: False, transition type: LeaveLocation)
[20/01/2021 20:57:12] Generating an outpost for the start of the level... (Location: St. May, level type: Outpost)
[20/01/2021 20:56:43] (Msg) SDR RelayNetworkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[20/01/2021 20:56:43] (Msg) Ping location: lhr=15+1,ams=20+2/20+1,par=20+2,fra=24+2,lux=27+2/25+2,sto=30+3,sto2=42+4/30+3,mad=34+3,vie=42+4/37+2,iad=97+9/97+2,sgp=162+16/163+16,gru=235+23/240+2
[20/01/2021 20:56:43] (Msg) Ping measurement completed
[20/01/2021 20:56:42] (Debug) Destroying relay 'eze#72 (155.133.255.99:27040)' because initial_ping_timeout
[20/01/2021 20:56:39] (Debug) Destroying relay 'eze#170 (155.133.255.163:27046)' because initial_ping_timeout
[20/01/2021 20:56:36] (Debug) Destroying relay 'eze#129 (155.133.255.162:27051)' because initial_ping_timeout
[20/01/2021 20:56:34] (Debug) Destroying relay 'eze#37 (155.133.255.98:27051)' because initial_ping_timeout
[20/01/2021 20:56:32] (Verbose) Communications with routing cluster 'waw' established.
[20/01/2021 20:56:32] (Verbose) Communications with routing cluster 'syd' established.
[20/01/2021 20:56:32] (Verbose) Communications with routing cluster 'tyo1' established.
[20/01/2021 20:56:32] (Verbose) Communications with routing cluster 'tyo' established.
[20/01/2021 20:56:32] (Verbose) Communications with routing cluster 'scl' established.
[20/01/2021 20:56:31] (Verbose) Communications with routing cluster 'sgp' established.
[20/01/2021 20:56:31] (Verbose) Communications with routing cluster 'sea' established.
[20/01/2021 20:56:31] (Warning) SteamNetworkingSockets lock held for 5.6ms.  (Performance warning).  ServiceThread,RecvUDPPacket
[20/01/2021 20:56:31] (Verbose) Communications with routing cluster 'vie' established.
[20/01/2021 20:56:31] (Verbose) Communications with routing cluster 'lim' established.
[20/01/2021 20:56:31] (Verbose) Communications with routing cluster 'maa' established.
[20/01/2021 20:56:31] (Verbose) Communications with routing cluster 'jnb' established.
[20/01/2021 20:56:31] (Verbose) Communications with routing cluster 'hkg' established.
[20/01/2021 20:56:31] (Verbose) Communications with routing cluster 'gru' established.
[20/01/2021 20:56:31] (Verbose) Communications with routing cluster 'sof' established.
[20/01/2021 20:56:31] (Verbose) Communications with routing cluster 'sto2' established.
[20/01/2021 20:56:31] (Verbose) Communications with routing cluster 'lax' established.
[20/01/2021 20:56:31] (Verbose) Communications with routing cluster 'sto' established.
[20/01/2021 20:56:31] (Verbose) Communications with routing cluster 'okc' established.
[20/01/2021 20:56:31] (Verbose) Communications with routing cluster 'par' established.
[20/01/2021 20:56:31] (Verbose) Communications with routing cluster 'ord' established.
[20/01/2021 20:56:31] (Verbose) Communications with routing cluster 'iad' established.
[20/01/2021 20:56:31] (Verbose) Communications with routing cluster 'eat' established.
[20/01/2021 20:56:31] (Verbose) Communications with routing cluster 'dxb' established.
[20/01/2021 20:56:31] (Verbose) Communications with routing cluster 'bom' established.
[20/01/2021 20:56:31] (Verbose) Communications with routing cluster 'dfw' established.
[20/01/2021 20:56:31] (Verbose) Communications with routing cluster 'mad' established.
[20/01/2021 20:56:31] (Verbose) Communications with routing cluster 'lux' established.
[20/01/2021 20:56:31] (Verbose) Communications with routing cluster 'atl' established.
[20/01/2021 20:56:31] (Verbose) Communications with routing cluster 'lhr' established.
[20/01/2021 20:56:31] (Verbose) Communications with routing cluster 'fra' established.
[20/01/2021 20:56:31] (Verbose) Communications with routing cluster 'ams' established.
[20/01/2021 20:56:31] (Msg) SDR RelayNetworkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[20/01/2021 20:56:31] (Msg) Performing ping measurement
[20/01/2021 20:56:31] (Msg) Got SDR network config.  Loaded revision 292 OK
[20/01/2021 20:56:31] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[20/01/2021 20:56:17] Attempting to open ALC device "OpenAL Soft on Speakers (SteelSeries Arctis 1 Wireless)"
[20/01/2021 20:56:16] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[20/01/2021 20:56:16] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[20/01/2021 20:56:14] Logged in as Ballisticbat69 (SteamID STEAM_1:0:121239776)

**Comment by Regalis11** [comment] 2021-01-21 08:27
Duplicate of https://github.com/Regalis11/Barotrauma/issues/1833

**Closed by Regalis11** 2021-01-21 08:27 UTC
