### ISSUE TITLE
Infinite submarine download when multiplayer campaign starts

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3045] opened 2020-06-09 17:44 UTC
Tested on Unstable 0.1002.0.0

Only way to prevent the infinite downloads is to disconnect and rejoin the server.

**Comment by Regalis11** [comment] 2020-06-09 17:45
Duplicate of #2942. When this occurs, please enter "verboselogging" in the console and take a screenshot of the output

**Closed by Regalis11** 2020-06-09 17:45 UTC
Labels: Bug, Code
