### ISSUE TITLE
Error after rejoining to server

### ISSUE THREAD

**Issue by quantus** [Regalis11/Barotrauma#6324] opened 2021-07-15 21:32 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I got disconnected right after rejoining (clicking the spectate button on the lobby) the server. I had to rejoin the server due to being disconnected by #6184. After getting this error I didn't try rejoining again, so I don't know if the issue happens consistently. I'll add a comment to this issue if this happens the next time we continue the game.

**Steps To Reproduce**
Rejoin the server. Don't know more.

**Version**
Latest stable (0.14.0.6.0) on Windows.

**Additional information**
![error_message](https://user-images.githubusercontent.com/671419/125860254-70159e17-e93e-42f8-bce7-3ec315c140bb.png)
![random_errors](https://user-images.githubusercontent.com/671419/125860262-11ece45d-6d74-4343-92c7-642c60d1991b.png)

[networkerror_data.log](https://github.com/Regalis11/Barotrauma/files/6826305/networkerror_data.log)

**Comment by Regalis11** [comment] 2021-10-15 09:54
Duplicate of https://github.com/Regalis11/Barotrauma/issues/1815

**Closed by Regalis11** 2021-10-15 09:54 UTC
Labels: Bug, Code, Networking
