### ISSUE TITLE
Trying to open published mod instantly crashes the game

### ISSUE THREAD

**Issue by swatblack** [Regalis11/Barotrauma#11731] opened 2023-04-03 12:12 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I wanted to update a simple item mod that I published on the workshop, and after making the changes to my local version I clicked on my mod in the "Publish" section and instantly got a crash message:
![изображение](https://user-images.githubusercontent.com/129751071/229502909-973c4201-6235-4286-b980-b8329bca71e9.png)
This happens every time I try to click on it. I've got little clue as to what's going on, so here's a crashreport:
[crashreport (10).log](https://github.com/Regalis11/Barotrauma/files/11138061/crashreport.10.log)
The mod is tiny so I can send it over if you need.

### Reproduction steps

1. Start the game.
2. Go to the "Mods" tab.
3. Go to the "Publish" section.
4. Click on published mod.
5. Crash.

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-04-03 12:24
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11581

**Closed by Regalis11** 2023-04-03 12:24 UTC
