### ISSUE TITLE
When logging into the server browser, an error pops up

### ISSUE THREAD

**Issue by NifNafNuf** [Regalis11/Barotrauma#12224] opened 2023-06-25 12:34 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When logging into the server browser, the error "Oh! The Barotrauma just caused the crash" The error message is: "The crash report was saved in the root folder of the game. The error was not sent to the developers because user statistics were disabled, but if you want to help fix this error, you can post it on the Barotrauma website...". When you click Ok, a text file with the report appears: 

Barotrauma Client crash report (generated on 06/25/2023 18:06:09)
Barotrauma seems to have crashed. Sorry for the inconvenience! 
9F5E3061E92D485CB02263313B29506B
Game version 1.0.21.0 (ReleaseWindows, branch release/summer-patch-hotfix, revision adb80ccd6e)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: Russian
Selected content packages: Vanilla (65E9331)
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.MainMenuScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.22621.0 64 bit
    GPU name: AMD Radeon(TM) Vega 8 Graphics
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Access to the path 'D:\SteamLibrary\steamapps\common\Barotrauma\config_player.xml' is denied. (System.UnauthorizedAccessException)
Target site: Microsoft.Win32.SafeHandles.SafeFileHandle CreateFile(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, System.IO.FileOptions)
Stack trace: 
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.Xml.XmlWriterSettings.CreateWriter(String outputFileName)
   at System.Xml.XmlWriter.Create(String outputFileName, XmlWriterSettings settings)
   at System.Xml.Linq.XDocument.Save(String fileName, SaveOptions options)
   at Barotrauma.IO.SafeXML.SaveSafe(XDocument doc, String path, SaveOptions saveOptions, Boolean throwExceptions) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SafeIO.cs:line 116
   at Barotrauma.GameSettings.SaveCurrentConfig() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Settings\GameSettings.cs:line 643
   at Barotrauma.SettingsMenu.ApplyInstalledModChanges() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Settings\SettingsMenu.cs:line 821
   at Barotrauma.SettingsMenu.<CreateBottomButtons>b__44_1(GUIButton btn, Object obj) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Settings\SettingsMenu.cs:line 800
   at Barotrauma.GUIButton.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 263
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1247
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 909
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[06/25/2023 18:05:27] Попытка появления: human
[06/25/2023 18:03:56] Attempting to open ALC device "OpenAL Soft on Динамики (Realtek(R) Audio)"
[06/25/2023 18:03:28] Logged in as Neuron (SteamID STEAM_1:1:418464162)

### Reproduction steps

This error occurs when I click the server browser button and when I click apply in the settings

### Bug prevalence

Just once

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 06/25/2023 18:06:09)
Barotrauma seems to have crashed. Sorry for the inconvenience! 
9F5E3061E92D485CB02263313B29506B
Game version 1.0.21.0 (ReleaseWindows, branch release/summer-patch-hotfix, revision adb80ccd6e)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: Russian
Selected content packages: Vanilla (65E9331)
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.MainMenuScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.22621.0 64 bit
    GPU name: AMD Radeon(TM) Vega 8 Graphics
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Access to the path 'D:\SteamLibrary\steamapps\common\Barotrauma\config_player.xml' is denied. (System.UnauthorizedAccessException)
Target site: Microsoft.Win32.SafeHandles.SafeFileHandle CreateFile(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, System.IO.FileOptions)
Stack trace: 
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.Xml.XmlWriterSettings.CreateWriter(String outputFileName)
   at System.Xml.XmlWriter.Create(String outputFileName, XmlWriterSettings settings)
   at System.Xml.Linq.XDocument.Save(String fileName, SaveOptions options)
   at Barotrauma.IO.SafeXML.SaveSafe(XDocument doc, String path, SaveOptions saveOptions, Boolean throwExceptions) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SafeIO.cs:line 116
   at Barotrauma.GameSettings.SaveCurrentConfig() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Settings\GameSettings.cs:line 643
   at Barotrauma.SettingsMenu.ApplyInstalledModChanges() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Settings\SettingsMenu.cs:line 821
   at Barotrauma.SettingsMenu.<CreateBottomButtons>b__44_1(GUIButton btn, Object obj) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Settings\SettingsMenu.cs:line 800
   at Barotrauma.GUIButton.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 263
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1247
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 909
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[06/25/2023 18:05:27] Попытка появления: human
[06/25/2023 18:03:56] Attempting to open ALC device "OpenAL Soft on Динамики (Realtek(R) Audio)"
[06/25/2023 18:03:28] Logged in as Neuron (SteamID STEAM_1:1:418464162)
```

**Comment by Regalis11** [comment] 2023-06-26 06:47
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11489

**Closed by Regalis11** 2023-06-26 06:47 UTC
