### ISSUE TITLE
[Issue][Weapon] You can shoot yourself with the shotgun

### ISSUE THREAD

**Issue by Ant1V1RU5** [Regalis11/Barotrauma#2568] opened 2020-04-04 02:41 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The pump shotgun can directly damage the wielder when firing.

**Steps To Reproduce**
When on dry surface
Step 1 : Aiming low or directly at your feet (sometime the head work too)
Sted 2 : Fire while the end of the barrel is on your character sprite.

When swimming :
Step 1 : Aim at any part of your character limbs
Step 2 : Fire while the end of the barrel is on your character sprite

**Version**
Current 0.9.8.0 version on Windows 10 updated

**Additional information**
I open this ticket because i saw a lot of player (including myself) hitting themself with the shotgun, and as i don't think it is intended and because no other type of weapon has a similar issue.

**Comment by thegrb93** [comment] 2020-04-04 07:03
I think the grenade launcher just did this to me too. I shot horizontally but I ended up exploding myself.

**Comment by Ant1V1RU5** [comment] 2020-04-04 19:24
I just finished trying the grenade launcher, i tried all the direction and i can't blow myself up (in water of course). I suppose that what happen to you was your character aiming to a close surface while the game semi-ragdoled you (When the screen is shaking sometime the charachters aim low).

**Comment by Regalis11** [comment] 2020-04-06 08:20
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c958cccc

**Comment by Rokvach** [comment] 2020-04-06 08:25
The shotgun hitting the player when aiming at feet was intentional decision from design, its caused because of the spread @Regalis11

**Comment by Regalis11** [comment] 2020-04-06 11:59
Turns out it was a bug caused by an oversight when implementing the multithreaded physics that was mistaken as a feature.

**Comment by Ant1V1RU5** [comment] 2020-04-06 21:01
Oh i see. Thank you very much for giving us an explanation.

**Comment by Rokvach** [comment] 2020-04-07 11:07
No issues, closing.

**Closed by Rokvach** 2020-04-07 11:07 UTC
Labels: Bug, Code
