### ISSUE TITLE
Crash on picking up artifact from holder in ruin

### ISSUE THREAD

**Issue by LordFrith** [Regalis11/Barotrauma#2727] opened 2020-04-27 23:50 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
i had a mission to find an artifact in ruin. On trying to collect artifact from the artifact 
holder game crashed

**Steps To Reproduce**
as above, crash happened when clicking on the artifact holder

**Version**
0.9.9.1 (unstable) windows 10

**Additional information**
i was running a mod (REALLYBIGMAPbeta) which contains a custom ruinconfig.xml. only the overall size of the ruins is changed

[crashreport (23).log](https://github.com/Regalis11/Barotrauma/files/4542551/crashreport.23.log)

**Comment by Regalis11** [comment] 2020-04-28 11:00
Could not reproduce this, but I added some error checks in https://github.com/Regalis11/Barotrauma-development/commit/9887aabc439870a98825afa82aa108f81cba182e that should prevent this from crashing the game and create a more helpful error message when it occurs.

**Comment by Regalis11** [comment] 2020-07-09 11:11
Caused by the same issue as https://github.com/Regalis11/Barotrauma/issues/3141, closing

**Closed by Regalis11** 2020-07-09 11:11 UTC
Labels: Bug, Code, Crash, Needs testing
