### ISSUE TITLE
Conditional Comparison="And" busted on non-characters?

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#4817] opened 2021-01-18 22:18 UTC
[Question, Issue]
```xml
<StatusEffect type="Always" target="This" Comparison="And" stackable="false" checkconditionalalways="true" comparison="and" >
        <Sound file="Content/Items/Medical/Syringe.ogg" range="500" />
	<Conditional PhysicsBodyActive="true" />
        <Conditional Condition="lt 50" />
      </StatusEffect>
```
something like this doesn't seem to work the way you would expect in an item (if it's outside the inventory and less than 50 it makes this sound). I'm pretty sure this is a bug. The exact same syntax works on creatures (ie for things like the baby moloch). I think Comparison="and" is busted for items.

**Comment by Regalis11** [comment] 2021-01-19 17:20
Duplicate of https://github.com/Regalis11/Barotrauma/issues/4631

**Closed by Regalis11** 2021-01-19 17:20 UTC
