### ISSUE TITLE
Nav terminal can't dock when passing signals through circuit box

### ISSUE THREAD

**Issue by DownloadableContent5021** [Regalis11/Barotrauma#12832] opened 2023-10-18 03:08 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I tried to use the new circuit boxes to hold the logic components for docking the submarine to an outpost. Although the system correctly controls the custom hatch, it does not seem to connect the nav terminal to the docking hatch

<img width="1680" alt="in-game" src="https://github.com/Regalis11/Barotrauma/assets/148298589/9e1e1014-9d92-4a91-bb7f-f4f9d8a21d73">

I am 99% sure I've wired the system correctly.
<img width="1136" alt="docking circuit" src="https://github.com/Regalis11/Barotrauma/assets/148298589/b5f99f17-072b-47e4-bc17-c5308ce8f283">
<img width="1146" alt="AND component 1" src="https://github.com/Regalis11/Barotrauma/assets/148298589/ad3cd0cb-672a-495e-8254-52fcaa4a49e9">
<img width="1146" alt="AND component 0" src="https://github.com/Regalis11/Barotrauma/assets/148298589/6cad4fd0-1f31-420c-b4b5-b72ae4941d3f">
<img width="1156" alt="DELAY component" src="https://github.com/Regalis11/Barotrauma/assets/148298589/797f7ee5-8102-4440-990d-7cdd75f8e6cc">
<img width="1149" alt="NOT component" src="https://github.com/Regalis11/Barotrauma/assets/148298589/3d69c68a-5234-4cb7-8ff9-fa262d1163f4">
<img width="745" alt="docking hatch" src="https://github.com/Regalis11/Barotrauma/assets/148298589/4a58f8d3-2f65-4b99-b3bc-3c270d8fff4b">
<img width="1050" alt="citcuit box" src="https://github.com/Regalis11/Barotrauma/assets/148298589/84c8ada6-79dc-4f43-9149-5bd85cc40fc6">

### Reproduction steps

1. Copy logic components from "Automated Docking Hatch" into a circuit box, and connect the system to the docking hatch and navigation terminal.
2. Start a new campaign with this system.
3. Observe how the Docking button won't show when piloting the submarine near an outpost.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

Other

### -

Unstable (v1.1.17.0)

### Which operating system did you encounter this bug on?

MacOS

**Comment by Regalis11** [comment] 2023-10-18 07:31
Duplicate of https://github.com/Regalis11/Barotrauma/issues/12812

**Closed by Regalis11** 2023-10-18 07:31 UTC
