### ISSUE TITLE
[Bug] Battery-cells get loaded at Batteries even when no power available.

### ISSUE THREAD

**Issue by roidal** [Regalis11/Barotrauma#2041] opened 2020-01-24 08:56 UTC
As the title say: Battery-cells get loaded at Batteries even when no power available.

**Comment by Regalis11** [comment] 2020-01-24 09:41
Cannot reproduce in the latest dev version, seems to have been fixed somewhere along the line. Moving to Review/QA

**Comment by Rokvach** [comment] 2020-02-05 19:32
I was able to reproduce this in the dev branch

Steps:

- Start a singleplayer round
- Make sure engineer AI doesn't start the reactor, so set him on follow
- Start the reactor briefly (Toggle power on and tick the automatic on for couple seconds and then turn it off)
- Place a used Battery Cell inside a Battery, see that it starts recharging even tho the Battery doesn't show that it has any charge

Batteries can be recharged indefinitely (Tested by knocking bots unconscious with a stun baton and recharged the battery after it was depleted)

@Regalis11

**Comment by Regalis11** [comment] 2020-02-06 16:41
Thanks, was able to repro it now!

Looks like this is a bit trickier to solve than I though; if we want to use StatusEffects to do this, we'd need the conditional and the effects of the StatusEffect to target different items (conditional that checks the charge of the Battery, and property effects that change the condition of the contained batteries).

We could also do this by integrating the charging logic to PowerContainer directly, but I think the StatusEffect approach is more flexible and could be useful for other things as well in the future. Modifying the StatusEffect logic this close to the update is so risky though that I'd say lets leave this for later.

**Comment by Regalis11** [comment] 2020-02-22 13:54
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5088567

**Comment by Rokvach** [comment] 2020-02-24 11:18
Seems to be working if there is 0 charge on the battery, but seems like a battery cell doesn't use up the charge stored in the battery, so if there is 1 charge on the battery the battery cell can be charged infinitely without it using up the charge, so either the battery cell uses so little that it can't be noticed or there is a bug. @Regalis11

**Comment by Rokvach** [comment] 2020-02-27 10:45
Made a low prio ticket about the latest comment, closing this one as the issue has been resolved.

https://github.com/Regalis11/Barotrauma-development/issues/1472

**Closed by Rokvach** 2020-02-27 10:45 UTC
Labels: Bug, Code
