### ISSUE TITLE
Submarine file corrupted

### ISSUE THREAD

**Issue by Bowman9709** [Regalis11/Barotrauma#11852] opened 2023-04-16 03:20 UTC
When to save a sub when it said an item was very far away. Went to it and found a reactor that couldn't be deleted. So I closed the game and now it errors when trying to open the file.
[Chimera's Fang Refit.zip](https://github.com/Regalis11/Barotrauma/files/11241122/Chimera.s.Fang.Refit.zip)

**Comment by Regalis11** [comment] 2023-04-16 11:56
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10591

I removed the extra reactor that was causing the issue, here's a fixed version of the submarine file. Sorry for the inconvenience!
[Chimera's Fang Refit.zip](https://github.com/Regalis11/Barotrauma/files/11242172/Chimera.s.Fang.Refit.zip)

**Closed by Regalis11** 2023-04-16 11:56 UTC

**Comment by Bowman9709** [comment] 2023-04-16 20:41
Thank you very much, honestly I had figured it was just gone forever. Is there anything I can try to do to prevent this? Also any way I can attempt to fix it myself?

**Comment by Regalis11** [comment] 2023-04-17 11:56
> Is there anything I can try to do to prevent this? 

As mentioned in https://github.com/Regalis11/Barotrauma/issues/10591, we still haven't been able to figure out how exactly this happens, so I'm afraid I don't know if there's a way to prevent it from happening.

> Also any way I can attempt to fix it myself?

It might be a little tricky, but it can be done as follows:
1. Change the file extension of the sub file to .gz (they're actually gzipped archives)
2. Decompress the file
3. Open it in a text editor
4. Find the duplicate entity based on the ID included in the error message (e.g. by searching for ID="xxx")
5. Remove the duplicate entity
6. .gzip the file again, and change the file extension back to .sub
