### ISSUE TITLE
Crash after trying to start a mission

### ISSUE THREAD

**Issue by guillermohurtadodm** [Regalis11/Barotrauma#11377] opened 2023-02-26 01:27 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I was playing with some friends and when trying to start a new mission, it crashed, I have taken a screenshot of the error in the console
![image](https://user-images.githubusercontent.com/71341303/221387279-5e4c87ad-2b01-4b16-9f72-dfbae98d46b4.png)
Sorry I cant be more specific,

### Reproduction steps

1.Start campaign
2.reach two or three outposts
3.try to take the praise the honkmother
4.crash

### Bug prevalence

Just once

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-02-26 10:14
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10933

**Closed by Regalis11** 2023-02-26 10:14 UTC
