### ISSUE TITLE
Unstable - Can't mine minerals with plasma cutter

### ISSUE THREAD

**Issue by SamO2742** [Regalis11/Barotrauma#6707] opened 2021-09-20 17:55 UTC
- [✔] I have searched the issue tracker to check if the issue has already been reported.

No minerals can be mined, the progress bar on cutting minerals does not fill up.  Firing a plasma cutter at a mineral causes the progress bar to show up, but it never fills.  The mineral does not fall off after firing the cutter at the mineral for the expected ten seconds.

Try to mine any mineral with a plasma cutter.

Version: Unstable vo.1500.3.0 - Windows - revision f61a8e46a4

**Comment by ekqvist** [comment] 2021-09-21 06:37
Duplicate of #6680. Fixed in Regalis11/Barotrauma-development@bd0c789.

**Closed by ekqvist** 2021-09-21 06:37 UTC
