### ISSUE TITLE
Attached submarines spawn unattached

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9756] opened 2022-08-24 07:58 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I was trying to test the shipyard lost shuttle service and noticed that the Remora drone was missing when I loaded up Remora in singleplayer

In sub editor if you load up Remora and launch test mode you will notice that the Remora drone isn't attached to the main sub

### Reproduction steps

1. Turn Debugdraw on
2. Select Remora in New Game menu
3. Load into singleplayer
4. Notice that the Remora Drone is nowhere to be seen

1. Load Remora in sub editor
2. Launch test mode
3. Notice that the drone isn't attached

### Bug prevalence

Happens every time I play

### Version

Other

### -

Dev branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-08-24 08:18
Caused by the fix implemented for https://github.com/Regalis11/Barotrauma/issues/9730, closing this one

**Closed by Regalis11** 2022-08-24 08:18 UTC
