### ISSUE TITLE
[Unstable] Headset no longer works in multiplayer

### ISSUE THREAD

**Issue by Virtlink** [Regalis11/Barotrauma#9199] opened 2022-05-23 17:32 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In unstable, the headset no longer works. Visually, the headset does not have a battery slot, and the headset icon in the bottom right is red. Game-logic wise, orders do not arrive at distant crew or other players, and their messages appear 'distorted'.

### Reproduction steps

In our multiplayer campaign which we loaded from Stable into Unstable, try giving orders to far away players or bots. Also notice the headset icon in the bottom-right being red.

### Bug prevalence

Happens every time I play

### Version

0.18.3.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-05-24 07:53
The red icon is an oversight we [have an existing ticket about](https://github.com/Regalis11/Barotrauma/issues/9125). I could not reproduce the issue with the headsets though, they seem to be working fine even if I load a pre-0.18 save. Are you sure it was actually a matter of the headset not working, and that you weren't just out of range?

**Comment by Rokvach** [comment] 2022-05-30 07:42
I'm still unable to give orders to a crew member who is using a auto-injector headset while I'm using the default one.

**Comment by Regalis11** [comment] 2022-05-30 15:25
I gave this a test in the same save ("TheColdsBelow") but couldn't reproduce it. 
![image](https://user-images.githubusercontent.com/14351070/171022881-36ddfcd8-b699-4111-a935-fcf3426cbd9a.png)

Which save did you test this with and are you sure you haven't overwritten it in a v0.18 version (which would make the game consider it already-up-to-date, and not remove the battery restrictions from the headsets)?

**Comment by Regalis11** [comment] 2022-05-30 15:45
Apparently this was tested in a save done in 0.18, moving back to QA

**Comment by Rokvach** [comment] 2022-05-31 07:44
Tested, working correctly. Closing.

**Closed as completed by Rokvach** 2022-05-31 07:44 UTC
Labels: Bug, Code

**Comment by Virtlink** [comment] 2022-06-06 17:12
We just tried with the same save in 0.16.5.0 (059daaaafa) and the problem is still present. Now it seems I am completely unable to give orders (or remove orders), even when the subject is physically next to me. Removing and putting the headset back on doesn't help.
