### ISSUE TITLE
No prompt for handcuffing self when swapping with held item

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#4990] opened 2021-02-05 00:32 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Swapping the handcuff with held item on self does not prompt the warning as when directly selecting the handcuffs

![image](https://user-images.githubusercontent.com/5103517/106972728-6e78f500-671f-11eb-9671-fe20ef72da09.png)
![image](https://user-images.githubusercontent.com/5103517/106972742-73d63f80-671f-11eb-9619-d9981183da3d.png)

**Version**
0.11 stable

**Additional information**
Also, no way to put handcuffs into someone's hand slots if they don't already have something in their hands - hotbar must be used.

**Comment by Regalis11** [comment] 2021-02-23 09:58
>Also, no way to put handcuffs into someone's hand slots if they don't already have something in their hands - hotbar must be used.

I wasn't able to reproduce this, the equip button seems to be working as expected.

**Comment by EtiamNullam** [comment] 2021-03-31 15:33
> 
> 
> > Also, no way to put handcuffs into someone's hand slots if they don't already have something in their hands - hotbar must be used.
> 
> I wasn't able to reproduce this, the equip button seems to be working as expected.

Not a fan of that prompt. It led to some funny situations and forced new players to learn how inventory works. Anyway I think its not about equip button. When you drag handcuffs over your equipped item in your hands (when you're out of slots) or equipped item over handcuffs they will be equipped without prompt.

![image](https://user-images.githubusercontent.com/10875340/113170483-e3ac0680-9246-11eb-9cff-fc2c0a6e6c83.png)

Image should explain everything.

**Comment by Regalis11** [comment] 2023-03-10 12:27
We're cleaning up some low-prio/unreproducible/irrelevant/outdated tickets from the issue tracker, and this is one of the tickets we chose to axe. Closing.

**Closed by Regalis11** 2023-03-10 12:27 UTC
Labels: Code, Low prio
