### ISSUE TITLE
event_error_log_server_cess183_1159 PM.log

### ISSUE THREAD

**Issue by JoneKone** [Regalis11/Barotrauma#9523] opened 2022-07-04 12:19 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Dedicated Server error.
[event_error_log_server_cess183_1159 PM.log](https://github.com/Regalis11/Barotrauma/files/9039337/event_error_log_server_cess183_1159.PM.log)

### Bug prevalence

Just once

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment] 2022-07-04 14:12
Duplicate of https://github.com/Regalis11/Barotrauma/issues/6265

**Closed by Regalis11** 2022-07-04 14:12 UTC
