### ISSUE TITLE
AI won't fix leaks in the ship

### ISSUE THREAD

**Issue by Ryxex2** [Regalis11/Barotrauma#7101] opened 2021-10-31 00:38 UTC
- [y] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When the AI are told to fix leaks, very often they just run into walls, a door, or in place, and do absolutely nothing towards repairing the ship.

**Steps To Reproduce**
Have leaks in the ship and tell any AI to fix it. If it doesn't happen immediately, it will eventually.

**Version**
This just started recently with v0.15.12.0, and the OS I am using is Windows 10.

**Additional information**
It doesn't matter what role has the order, an assistant told to fix leaks will run into walls just the same as a mechanic.

**Comment by TimFragmagnet** [comment] 2021-10-31 00:54
I can confirm this as well, it appears to be a general reduction in pathfinding quality. I've seen AI run into the armory on the dugong and then rapidly run back and forth within it failing to find a path to anything else on the ship.

I've also seen AI try and repair things through walls on several subs.

I can also corroborate the situation where the AI will just stop moving all together and stand there doing nothing.

**Comment by Ryxex2** [comment] 2021-10-31 01:35
It appears to happen on all the ships. I've used the Berilia, Typhon, Dugong, Humpback, Kastrull, and Remora since the new update and the AI all do the same thing as mentioned before.

**Comment by itchyOwl** [comment] 2021-11-01 11:32
I think it was caused by the pathing changes in Regalis11/Barotrauma-development@b9af422. Reverted the problematic part in Regalis11/Barotrauma-development@93fbc06.

**Comment by Rokvach** [comment] 2021-11-01 19:37
I did notice a increase on bots mentioning that they can't reach a leak but they were fixing leaks just fine otherwise

**Comment by Rokvach** [comment] 2021-11-10 11:52
Haven't really noticed the above behavior since, seems to be working fine. Closing.

**Closed by Rokvach** 2021-11-10 11:52 UTC
Labels: Bug, Code
