### ISSUE TITLE
Teleport bug with ruins 2

### ISSUE THREAD

**Issue by andremaol** [Regalis11/Barotrauma#7676] opened 2021-12-08 15:30 UTC
So, I saw that it was alredy opened a thread about this bug, but it was alredy closed. This bug happened to me yesterday, 08/12/2021. It was precisely described in the first thread: I was evading the ruins with a scooter, I got attacked by a swarm of jellyfishes, and when I exited to the sea, I got teleported to nowhere. It sucked, cause I was playing with my brother and only him had a handheld sonar, so I was absolutely lost and eventually got dead.

Other odd thing that happened was that we had alredy scanned the three spots of that alien ruins, and luckly the three spots were scanned with my brother's scan and he survived, but when we delivered the mission, the game didn't recognized the scans and the mission failed. We've alredy done the "scan ruins" mission a couple of times, so it probably didn't fail for a mistake of ours.

**Comment by Regalis11** [comment] 2021-12-08 17:23
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7067.

The issue should be fixed in the current unstable build, but the fix isn't out in the public version yet.

**Closed by Regalis11** 2021-12-08 17:23 UTC
