### ISSUE TITLE
Mining Research mission materials are unreachable

### ISSUE THREAD

**Issue by TheMinerBoy** [Regalis11/Barotrauma#9941] opened 2022-09-25 19:04 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?
Case 1.
I got a mission to mine four pieces of Uranium at the mining outpost in the very top of the map, near the very left. While I was travelling from that place to the colony in the top left of the map, I moved above the "Uranium" marker on the sonar. However, there was no "Cave" marked on the map, and the Uranium was 200 metres underground. There was a nearby (unmarked obviously) cave a few hundred metres left of the marker with a very thin indestructible rock wall sealing off a passage that might have lead to the Uranium, but obviously I couldn't get through it. No other caves were nearby.

Case 2.
I got a mission to mine quartz from the colony in the top left of the map. While I was travelling from that place to the mining outpost in the very top of the map, I moved above the "Quartz" marker on the sonar. However there was no "Cave" marked on the map, and the Quartz was 144 metres underground.

### Reproduction steps

1. Get a mining research mission from the specified mining outpost going to the specified colony or from the colony to the specified mining oupost
2. Get lucky and hope it glitches out
3. Find the underground mineral marker with no "Cave" marker
![Barotrauma 2022-09-27 9_15_12 PM](https://user-images.githubusercontent.com/81781733/192686759-b8c1890a-334b-4c54-bc6f-7b0ec51261a7.png)

[Suspicious Quartz.zip](https://github.com/Regalis11/Barotrauma/files/9661437/Suspicious.Quartz.zip)

### Bug prevalence

Frequent

### Version

0.19.6.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Map Seed: fLV4dqrF
```

**Comment by TimFragmagnet** [comment] 2022-09-26 06:11
This bug is more prevalent than "just once"

I had 2 mining missions at the same time, both unreachable.

and several others also being unreachable on their own.

It looks like they're not spawning physically inside the terrain, but they're spawning inside little pockets within the terrain that have no entrance.

**Comment by Regalis11** [comment] 2022-09-26 07:30
Thank you for the report! Would it be possible to send us a save file where this occurs so we could give it a test?

**Comment by TheMinerBoy** [comment] 2022-09-26 14:47
> Thank you for the report! Would it be possible to send us a save file where this occurs so we could give it a test?

For some reason my emails get auto-returned?

**Comment by Regalis11** [comment] 2022-09-26 15:43
I did get the message, thank you! It's also possible to attach files directly here on GitHub, but you need to .zip them first because GitHub doesn't allow attaching files with the .save file extension.

**Comment by Regalis11** [comment] 2022-09-26 16:42
I'm afraid I could not reproduce this. In the provided save, the pyromorphite seems to spawn out in the open:
![image](https://user-images.githubusercontent.com/14351070/192333612-920f4f3f-96ef-448d-b913-7971df2bdf1d.png)

The mission in question seems to be an easy variant of the mineral missions, in which the minerals spawn right next to the main path instead of a cave.

**Comment by TheMinerBoy** [comment] 2022-09-26 19:27
Sorry, the round where I encountered the bug already ended. Obviously it failed. Is there an open pocket 200 m below that little rock shelf?

**Comment by TheMinerBoy** [comment] 2022-09-26 22:49
I'll try to reproduce this bug when I have time.

**Comment by TheMinerBoy** [comment] 2022-09-28 04:16
Alright, I updated the bug report with more information.

**Comment by Regalis11** [comment] 2022-09-28 07:46
Thank you, I think I found the issue now! Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/c130012e10af4cbcd0fdadc226da02e1fd2988dd

**Comment by TheMinerBoy** [comment] 2022-09-29 01:43
New problem: The bug fix seems to have broken the missions entirely. Some people have reported not being able to start single missions with the mining goal outside the campaign, and it definitely broke my existing campaign save (Suspicious Quartz). The error message says something like, "Can't find a suitable level wall to place resources."

**Comment by ekqvist** [comment] 2022-09-29 06:13
The issue was caused by a fix to another mineral mission related issue (Regalis11/Barotrauma-development#3581, ticket in the private repository). It should be fixed for the next Unstable. Apologies for the issues caused by this!

**Comment by NilanthAnimosus** [comment] 2022-09-30 11:52
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/00f795275d20e02a91cf05792d31934e9a358ffe, no issues found, closing.

**Closed by NilanthAnimosus** 2022-09-30 11:52 UTC
Labels: Bug, Code, Unstable
