### ISSUE TITLE
NPC Change Team Action doesn't work properly for enemy teams

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#6044] opened 2021-06-12 01:29 UTC
**Description**
When you change NPC's team to enemy, their nick properly changes to red colour, but they start fleeing from you, no matter their job, instead of attacking or fleeing.

**Steps To Reproduce**
-event editor
-spawn NPC
-change their team to for example 4
-observe their behaviour

**Version**
Unstable

**Comment by M61Dev** [comment] 2021-08-30 10:14
This seems to be caused by a block of logic in HumanAIController (line 238) that overrides any other AI functionality as long as a character is on a submarine with a different team id than its own. I'm not sure why this block of logic exists, as it has given me trouble as well, and I'm not sure whether to call this a bug or expected functionality.

**Comment by Regalis11** [comment] 2021-08-30 10:43
@M61Dev It happens because NPCs without a combat objective flee from hostiles, and NPCChangeTeamAction doesn't add a combat objective to the NPCs.

**Comment by M61Dev** [comment] 2021-08-30 11:39
It should still work for security NPCs as they have FightIntruders as an objective, but they never use the objective because of the logic block overriding them to defensive behavior.

**Comment by Regalis11** [comment] 2022-09-15 10:05
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/51376773c3813125b17e947fd5586b221901461b

**Comment by NilanthAnimosus** [comment] 2022-10-24 10:27
Tested against faction-outposts commit https://github.com/Regalis11/Barotrauma-development/commit/3dbdaa2082805f9ba0abcc98466638c1b54fc391

Tested against Bugfixes commit https://github.com/Regalis11/Barotrauma-development/commit/018de76cdb680129a05b8fa44e0bf363c30095af

Notes: Valid teams are "None, Team1, Team2 and FriendlyNPC", setting it to say, team 4 will likely set the team to "None" which has fairly unpredictable effects (Such as not fighting back properly) with combat actions / fight intruders automatic orders.

Additionally it will now throw an error message when an invalid team is used showing the correct ones for NPCChangeTeamAction.

No issues found, closing.

**Closed by NilanthAnimosus** 2022-10-24 10:27 UTC
Labels: Bug, Code, Modding
