### ISSUE TITLE
Husked players do not drop gene splicers upon death.

### ISSUE THREAD

**Issue by milochristiansen** [Regalis11/Barotrauma#11926] opened 2023-04-29 06:15 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

My character was husked, but wearing Zealot Robes, and then died. I respawned and returned, killed my old self (who was wandering around as a husk) and regeared. However, my advanced gene splicer was gone, and there was seemingly no way to recover it.

I was running a husk mod that allows husked players to speak if they have the gene, and I was running a mod that allows you to remove genes from a splicer without them breaking, however another player on the same server reported his advanced gene splicer disappeared in a similar manner before either mod was added (I remember it happening, and we just chalked it up to it falling some where and not being found, but twice is a pattern). The only gene I had installed at the time was a Hammerhead Matriarch gene, no husk gene (I had the robes, so no need).

### Reproduction steps

1. Install a gene mod
2. Get Husked.
3. Die.
4. Kill the husk.
5. No gene splicer exists on their body, probably because the inventory slot for it is inaccessible.

### Bug prevalence

Happens regularly

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by milochristiansen** [comment] 2023-04-29 06:26
Also, I worry about what happens when you dock with a husked dead player. Does all their stuff get deleted? I had a few things on my old body when we docked (nothing I cared about) and rather than become a bag, it just poofed. This may explain why a few of our players have reported the game deleting all their stuff in the past.

I don't remember the circumstances of these cases well enough to report a bug with any certainty though.

**Comment by Vykn** [comment] 2023-04-29 13:25
If a player dies and becomes a husk, most of their items will be placed into the HumanHusk's inventory. If the items aren't taken from it, it will despawn with all the items when a level transition occurs, essentially losing everything.

This includes if the HumanHusk is dead.

Maybe spawn duffle bags for humanhusks if a level transition occurs and the husk is dead? Or maybe any living creatures inside the submarine should remain on the submarine after a level transition. 

This doesn't happen very often, since respawning characters usually want their items back ASAP, but could happen. It doesn't really make sense if all of a character's possessions are on board the submarine (albeit inside a husk corpse) just magically disappear.

**Comment by milochristiansen** [comment] 2023-04-29 13:33
Would that also address the issue of not being able to loot the gene splicer from player husk bodies?

**Comment by Regalis11** [comment] 2023-05-02 07:05
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ff2acf3c1ed7320a30147e4c115f4f3a0260c79c

**Comment by Jasontti** [comment] 2023-08-10 05:50
Tested.
When husked player is incapacitated gene splicer was lootable with health menu, genetic material is lost by design.
Closing ticket.

**Comment by Regalis11** [comment] 2023-08-15 15:06
See https://github.com/Regalis11/Barotrauma-development/pull/4187/commits/49693c6167c5ab97cf08315768ca23f4ead0735c.

I did various fixes and changed the logic now so you can access bots' and incapacitated characters' health interface slots (but not those of living players!). We should check that's working as intended.

**Comment by Jasontti** [comment] 2023-08-16 08:39
Tested.
Could not access cuffed or stunned characters splicer, they need to be truly incapacitated.
No issues with huskification.
Bots slots were accessible always in SP and MP.

Finger cursor is visible where splicer slot would be.
No further issues were found.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdU1KIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6378b4e535a7b625c582de32e9ad07c40dbc79fe/image.png)

**Comment by Regalis11** [comment] 2023-08-16 09:48
Fixed in https://github.com/Regalis11/Barotrauma-development/pull/4187/commits/0cd405d8f324356f8d38b7395a304f66b00efe8f

**Comment by Jasontti** [comment] 2023-08-17 06:18
No issues found.
Closing ticket.

**Closed by Jasontti** 2023-08-17 06:18 UTC
Labels: Bug, Code, Low prio
