### ISSUE TITLE
[0.9.703] Using grenades causes disconnect on dedicated and steam P2P servers

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#2189] opened 2020-02-07 00:45 UTC
**Description**
When frag grenade + other type of grenade explodes on 1 bot or player, game crashes into main menu. Example: use EMP grenade on your self, then frag on your self ->crash.

**Steps To Reproduce**
-Start a dedicated or P2P server.
-Obtain frag grenade and any other type of grenade
-Use both grenades on your self or bots
-Crash into menu

**Version**
Unstable 0.9.703

**Additional information**
-it doesn't happen in singleplayer
-it doesn't happen with monsters
-it doesn't happen with corpses

Here is the bin file
[crashreport_object.zip](https://github.com/Regalis11/Barotrauma/files/4168465/crashreport_object.zip)

**Comment by Regalis11** [comment] 2020-02-07 09:54
Thank you, managed to diagnose and fix this now! The issue was that the server wrote the length of the health update using a single byte (so the maximum length was 255), but the grenades gave the character such a large number of different afflictions that the health data didn't fit into those 255 bytes. This would cause the length value to be written incorrectly, and the clients to read an incorrect amount of bytes from the message, which would mess up reading the rest of the message and cause the client to disconnect.

This may have caused the same error in other situations as well, so there's a chance this could fix the long-standing "invalid object header" error (see #1815).

Fixed in https://github.com/Regalis11/Barotrauma-development/commit/54ba34e463951c34d32307ce5b36bff56ee938d6

**Comment by Udrakan** [comment] 2020-02-07 15:38
That would be fantastic, happy to help.

**Comment by Rokvach** [comment] 2020-02-08 11:58
Tested, couldn't reproduce the issue anymore, so seems to be working correctly. Closing.

**Closed by Rokvach** 2020-02-08 11:58 UTC
Labels: Bug, Code, High prio, Networking
