### ISSUE TITLE
Repairing repairables as a husk crashes the game

### ISSUE THREAD

**Issue by mc-oofert** [Regalis11/Barotrauma#6316] opened 2021-07-15 16:59 UTC
[servercrashreport (8).log](https://github.com/Regalis11/Barotrauma/files/6825063/servercrashreport.8.log)

- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Getting experience from repairs appears to crash the game if playing as a husk.
Tested with: Reparing doors/hatches with a wrench,repairing junctions with a screwdriver

**Steps To Reproduce**
1. Control a husk
2. Wait for a junction to break down fully,repair with a screwdriver
3. Once you get experience from it the game crashes.

**Version**
0.14.6.0

**Comment by mc-oofert** [comment] 2021-07-15 17:06
this probably also applies to anything that can be repaired actually

**Comment by Regalis11** [comment] 2021-07-16 07:19
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7ff69eeeed40252472247f628759f484218ae543

**Comment by Rokvach** [comment] 2021-07-27 06:26
Tested, wasn't able to reproduce the issue, seems to be working correctly. Closing.

**Closed by Rokvach** 2021-07-27 06:26 UTC
Labels: Bug, Code, Crash
