### ISSUE TITLE
Crash on loading after mission ended prematurely

### ISSUE THREAD

**Issue by TheK0tYaRa** [Regalis11/Barotrauma#3667] opened 2020-08-31 12:11 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
got mining outpost resource delivery
delivered
no outpost
got a little out of the map
map stopped me with invisible walls
moved back and chose other location
loading with successful mission check
crash

**Steps To Reproduce**
i have no idea

**Version**
Game version 0.10.4.0 (ReleaseLinux, branch release, revision 965c31410a)

**Additional information**
https://pastebin.com/RzPjVP8F

**Comment by Regalis11** [comment] 2020-08-31 12:39
Duplicate of #3494

**Closed by Regalis11** 2020-08-31 12:39 UTC
