### ISSUE TITLE
Sub spawning outside game map

### ISSUE THREAD

**Issue by dmitrygrey** [Regalis11/Barotrauma#8005] opened 2022-01-09 18:55 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When I started a new mission my sub seems spawned outside game map. Everything is dark and no lights work. I can still walk in the sub and if I look in periscope it looks like the sub is inside a solid rock. I cannot go back or continue campaign and after every loading the issue is the same. This is end of my campaign till this is fixed. The sub is from plugin IROH. Cannot check with the other sub as cannot go back to station.

**Steps To Reproduce**
I have no idea. But probably if you start from the same station.

**Version**
Last version from Steam I'll attach image with main menu. I'm on Linux Ubuntu 21.10

**Additional information**
Critical bug.

![Screenshot from 2022-01-09 18-46-49](https://user-images.githubusercontent.com/8440999/148696492-87fc33c3-f9ec-4169-b6ec-66e891f8aa56.png)
![Screenshot from 2022-01-09 18-45-12](https://user-images.githubusercontent.com/8440999/148696496-464655ef-5031-4394-a94f-4fd9c4599cbc.png)
![Screenshot from 2022-01-09 18-38-54](https://user-images.githubusercontent.com/8440999/148696497-02445160-ee2a-4152-b408-9f19f24e5b9d.png)
![Screenshot from 2022-01-09 18-38-42](https://user-images.githubusercontent.com/8440999/148696498-94030ad8-adfe-4dee-b626-cbd556da8e4e.png)

**Comment by Regalis11** [comment] 2022-01-11 15:18
Thank you for the report!

Would it be possible to provide us the save file this occurs in? That'd make it much easier for us to diagnose this, since I don't think I've ever run into this before and I'm not sure how I could reproduce it either.

Also, if you don't mind not gaining Steam achievements during the course of this campaign, it would be possible to work around the issue using console commands: you could use the command `freecam` to move the camera inside the level, and then use the command `teleportsub cursor` to teleport it back inside the level.

In any case, I'm sorry for the inconvenience, I would definitely be frustrated to have my campaign end like this. :/

**Comment by n3tr4k** [comment] 2022-01-12 20:26
Here's my save https://drive.google.com/file/d/1-wNoRsXbHyvIS2iPhB8-uVwStfCI5yXb/view?usp=sharing

Also list of mods in case if important
![Screenshot from 2022-01-12 20-02-36](https://user-images.githubusercontent.com/8440999/149216397-a1671c53-ebe5-4a37-92a6-fd12224ad6e3.png)

**Comment by Regalis11** [comment] 2022-01-13 09:10
Thank you! It seems I needed to request access to the file, so I couldn't give it a test yet.

Btw, it's also possible to attach files here on GitHub: something to note though is that you need to .zip the save file first because GitHub doesn't allow attaching files with the .save file extension.

**Comment by dmitrygrey** [comment] 2022-01-13 19:02
[save.zip](https://github.com/Regalis11/Barotrauma/files/7865309/save.zip)

**Comment by Regalis11** [comment] 2022-01-14 11:22
Looks like this was caused by the same bug as https://github.com/Regalis11/Barotrauma/issues/7978, closing as a duplicate

**Closed by Regalis11** 2022-01-14 11:22 UTC
Labels: Bug, Code
