### ISSUE TITLE
crash on start

### ISSUE THREAD

**Issue by jospehman** [Regalis11/Barotrauma#4427] opened 2020-12-02 18:14 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

opened game, it crashed immediately on the loading system. another bug ive had recently is that i keep getting a pop up to delete a submarine which i already deleted. it says the submarine is corrupted and should be deleted, i press yes but it keeps coming up. could be related. anyway here is crash report.
[crashreport (3).log](https://github.com/Regalis11/Barotrauma/files/5631234/crashreport.3.log)

**Comment by Regalis11** [comment] 2020-12-03 08:34
Thank you for the report! This seems to be caused by a mod called "Speeder" that the game fails to load for some reason. Unsubscribing from the mod and deleting it should fix the issue. I added some extra checks in https://github.com/Regalis11/Barotrauma-development/commit/b328d50ce40278cc0e7f653e38de438f1f51a498 that should prevent this issue from crashing the game in the future, and instead just show an error message.

> another bug ive had recently is that i keep getting a pop up to delete a submarine which i already deleted. it says the submarine is corrupted and should be deleted

Is this your own custom submarine or a mod from the workshop? If the latter, you should uninstall the mod, not just the submarine file.

**Comment by jospehman** [comment] 2020-12-03 08:48
Both ' speeder ' and the other custom submarine were made by me.

**Comment by Rokvach** [comment] 2021-01-05 13:18
Can corfirm that this is working correctly in the latest Unstable, one of the testers had a issue of the game crashing at the start when launched only when he was playing on the Stable version, switching to Unstable the tester were able to launch the game normally. Only way he was able to fix it on the Stable side was to delete all of hes mods. 

So working correctly, closing.

**Closed by Rokvach** 2021-01-05 13:18 UTC
Labels: Bug, Code, Crash
