### ISSUE TITLE
Couldn't start game session, saved submarine is empty. The submarine file may barotrauma fix be corrupted. After a few hours of playing, we docked to the outpost and exited the game, and the next time we entered the game, we got this error. I can tell you which mods we use if necessary. sorry for my English, I use a translator.

### ISSUE THREAD

**Issue by HearyDM** [Regalis11/Barotrauma#13191] opened 2023-12-18 10:10 UTC
![изображение_2023-12-18_130217906](https://github.com/Regalis11/Barotrauma/assets/131370429/82cb1f9e-1176-4314-8e03-4ab2aaedfb45)

**Comment by Regalis11** [comment] 2023-12-18 10:49
Duplicate of https://github.com/Regalis11/Barotrauma/issues/12104

**Closed by Regalis11** 2023-12-18 10:49 UTC
