### ISSUE TITLE
[0.9.9.0] Bots - Ignoring Operate orders to go repair stuff

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2642] opened 2020-04-17 00:36 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots are getting off the navigation terminal, reactor, and periscopes to repair things. Usually these bots aren't engineers or mechanics, so they're getting themselves entirely killed.

**Version**
0.9.9.0

**Comment by Kaillera** [comment] 2020-05-03 14:21
The is becoming quite a big problem. When you get swarmed by a lot of enemies that can breach the sub, water will flow in and break down objects when rooms are flooded. The bots will keep trying to go repair them and letting go of the scopes, instead of shooting at the cause of the issues.

**Comment by itchyOwl** [comment] 2020-06-17 09:20
I cannot reproduce this anymore. Pretty sure that it was fixed by Regalis11/Barotrauma-development@1c9db66.

**Comment by Rokvach** [comment] 2020-06-17 11:33
I don't think this is a issue anymore, closing.

**Closed by Rokvach** 2020-06-17 11:33 UTC
Labels: Bug, Code
