### ISSUE TITLE
Skills resetting on multiplayer campaign round transition

### ISSUE THREAD

**Issue by zkxs** [Regalis11/Barotrauma#7791] opened 2021-12-16 01:35 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Skills are resetting for some, but not all, of my players on campaign round end. Just in case this helps, here's who's affected and who's not for my specific game.

| Player Job | Affected by bug? |
| --- | --- |
| Engineer, Host | Affected |
| Security Officer | Not Affected |
| Medic | Not Affected |
| Captain | Not Affected |
| Engineer | Affected |
| Mechanic | Affected |

**Steps To Reproduce**
- Level up a skill
- Dock at a station
- The round ends
- Observe that your skills are all reset to the baseline

**Version**
Windows v0.15.21.0

**Additional information**
This is on a custom sub with a no-delay docking port, just in case that matters.

**Comment by Regalis11** [comment] 2021-12-17 13:41
Potentially related to https://github.com/Regalis11/Barotrauma/issues/7755

**Comment by zkxs** [comment] 2021-12-18 17:25
I saw this issue again during a brand new campaign save created under Windows v0.15.22.1. Here is what I observed:
- Out of my 11 players, two were affected and had their skills reset at each round transition
- Unlike my initial report, this time the host (me) was not affected
- This appears to affect certain players and stick with them, resetting their skills every round, while other players are completely fine
- This time a medic and an assistant were affected and everyone else was fine, so my suspicious that this was somehow job related seem unfounded

The 0.15.22.1 save that was affected: [skill_reset_save.zip](https://github.com/Regalis11/Barotrauma/files/7739641/skill_reset_save.zip)

**Comment by thebuttsatisfier** [comment] 2021-12-19 18:15
Also confirming my crew's skills began resetting each time we docked approx 36 hours ago.

**Comment by shindouj** [comment] 2021-12-19 22:09
Can confirm. Happened during our playthrough today and affected only me (a Mechanic); my skills got reset after each docking and undocking.

**Comment by Regalis11** [comment] 2022-01-03 08:53
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7755

**Closed by Regalis11** 2022-01-03 08:53 UTC
Labels: Bug, Code, Networking
