### ISSUE TITLE
Reactor Signal Inputs and Power Max Output

### ISSUE THREAD

**Issue by Eskandaer** [Regalis11/Barotrauma#2800] opened 2020-05-11 00:22 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When normally controlling a reactor, 1 fuel rod only enables the Reactor to produce a percentage of its maximum power; ~85%, meaning there could be benefit to using 2 fuel rods at times.  When controlling a reactor with only signal wires, you can send 100% and 100% to reaction/turbine inputs to produce near maximum power on only 1 fuel rod.

**Steps To Reproduce**
Establish a normal grid with reactor with 1 fuel rod; setup signals to set_fissionrate and set_turbineoutput with input of "100".  Observe output; note the needle on fissionrate may also be unstable in the reactor interaction screen.

**Version**
Windows
Current stable release

**Additional information**

**Comment by Regalis11** [comment] 2020-05-11 11:22
Could not reproduce. The fission rate seems to be limited by the available fuel regardless if the fission rate is set manually or via external signals.

Here the fission rate is set to 100% using a signal from a memory component:
![4567234tsdreg](https://user-images.githubusercontent.com/14351070/81556356-dc5fde00-9392-11ea-8d50-3ffa9547b7ba.png)

**Comment by Eskandaer** [comment] 2020-05-11 17:04
I encountered this on my custom sub that has plenty of non-standard deviations so it is a bit complicated --   this is what I was seeing (the reactor has max output of 125kw and was achieving nearly that with one fuel rod)
![20200511124713_1](https://user-images.githubusercontent.com/24423118/81589135-3064c580-9387-11ea-87a0-58d6d8153d12.jpg)


To confirm, I replicated the issue on a simpler testing vessel:
Reactor with default 10,000kW max, connected to junction, connected to battery with a recharge rate to 10,000kW, mem with 100 value sent to both fission rate and turbine rate -- achieved 9,999kW with one fuel rod:
![20200511125648_1](https://user-images.githubusercontent.com/24423118/81589567-86d20400-9387-11ea-8720-f7d622a8cb56.jpg)

Testing vessel is attached;  reactor is one on the right
[Testing Vessel reactor #2800.zip](https://github.com/Regalis11/Barotrauma/files/4611017/Testing.Vessel.reactor.2800.zip)

**Comment by Eskandaer** [comment] 2020-05-11 17:07
Another note that I've noticed and can't explain:  the top photo has SCRAM light lit, and not sure why.  I don't think a signal was going to shutdown node, nor was it behaving as it was SCRAM.  In the second photo, it was giving Fuel Low light, though you can see the fuel rod is nearly full.  

Additionally, in the top photo, the sliders matched the signals going in to reactor and you couldn't manually change them as the signals locked it out (as intended);  in the bottom scenario, the sliders did not match the inputs and I could move the sliders (though it wouldn't override the signals).

**Comment by Regalis11** [comment] 2020-05-12 08:41
Thank you for the extra info! Looks like this already got fixed in our private repository when implementing a fix for another reactor bug (https://github.com/Regalis11/Barotrauma-development/commit/58c5293).

The SCRAM issue happened because the reactor was powered down, which should normally shut it down, but the signals were overriding the fission and turbine output rates and keeping the reactor running. Fixed that on in https://github.com/Regalis11/Barotrauma-development/commit/ca2ccfc

**Comment by Rokvach** [comment] 2020-05-13 09:57
No issues, closing.

**Closed by Rokvach** 2020-05-13 09:57 UTC
Labels: Bug, Code
