### ISSUE TITLE
Mic not working on Mac

### ISSUE THREAD

**Issue by jolson474** [Regalis11/Barotrauma#10764] opened 2022-12-19 02:02 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Updated to the new HolidayUpdate (Dec 14 - v0.20.15.0) and now mic does not work in game on a Mac (`12.6.2`).  Unfortunately, this affects all 3 users in my household on different Macs and we all just updated the game today.  Mic works fine in other applications (including Steam Voice Chat). Mic also works fine on the one windows machine in our house.

Verified the OS permission wasn't removed (see attachment)
<img width="353" alt="Screen Shot 2022-12-18 at 8 00 05 PM" src="https://user-images.githubusercontent.com/3170557/208333432-c548ae00-b65f-4149-ab6a-d50d0f3f7824.png">

The previous version worked great, and nothing on our machines has changed afaik (aside from updating Barotrauma). 

p.s. Thanks for making such a great game my family enjoys so much.  If there is other diagnostic data we can collect to assist, let me know. Thanks!

### Reproduction steps

1. Start game
2. Go to Settings and select Audio from left menu
3. Observe no mic output in the noice gate threshold 

Can also join a server and observe no mic at all in the lobby (in addition to no one being able to hear the Mac people)

### Bug prevalence

Happens every time I play

### Version

0.20.15.0

### Which operating system did you encounter this bug on?

MacOS

**Comment by Regalis11** [comment] 2022-12-19 11:20
Duplicate of https://github.com/Regalis11/Barotrauma/issues/5650

**Closed by Regalis11** 2022-12-19 11:20 UTC
