### ISSUE TITLE
Singleplayer Bug (Tutorial Outpost)

### ISSUE THREAD

**Issue by Zimbel13** [Regalis11/Barotrauma#10346] opened 2022-11-12 14:03 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

(unstable branch(Tutorial Outpost)) When playing singleplayer the new "Introduction" thing that tells you to get supplies keeps looping not allowing me to move/play.

### Reproduction steps

1.start singleplayer
2.progress through the text
3.it keeps looping

### Bug prevalence

Happens every time I play

### Version

0.20.5.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by finbotic** [comment] 2022-11-12 16:36
https://user-images.githubusercontent.com/118069182/201484464-d6119e07-5086-4cee-8a9a-6324b942a2ea.mp4

Hello, I assume I'm having the same bug as you, and i got some video of it.
It also gives you the supply check list again, and gives you 300 _more_ marks, every time you agree to getting the supplies.

**Comment by Regalis11** [comment] 2022-11-12 17:41
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10320

**Closed by Regalis11** 2022-11-12 17:41 UTC
