### ISSUE TITLE
[0.15.16.0] Bot returning to sub from outside while holding a crate is doing some twitchy thing with crate

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#7508] opened 2021-11-26 22:34 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![Twitchy](https://user-images.githubusercontent.com/5086682/143659141-03c01b86-a114-4042-be91-9e2edff70de8.gif)

**Steps To Reproduce**
1. Have a crew member outside with a diving suit and a crate.
2. Tell him to follow you (while you're inside the sub).

**Version**
0.15.16.0

**Comment by Regalis11** [comment] 2021-11-30 13:47
I'm afraid I couldn't reproduce this. Did it happen in multiplayer or singleplayer?
https://user-images.githubusercontent.com/14351070/144058691-9556322e-6a52-4e6a-9f56-27e6042479d0.mp4

**Comment by Kaillera** [comment] 2021-11-30 19:25
[Save.zip](https://github.com/Regalis11/Barotrauma/files/7628258/Save.zip)

So it's still happening on this save.

1) Control the Captain, put on a suit, and pick up a crate.
2) Exit the sub and gain some distance away from the sub.
3) Set the Captain to Wait
4) Use another character in the submarine and tell the Captain to Follow
5) He should be twitching the crate as he comes back into the sub.

**Comment by Regalis11** [comment] 2021-12-01 15:37
Thank you! I managed to fix this now (https://github.com/Regalis11/Barotrauma-development/commit/7a49bc6ca58c9311e233bd209c18f8a121e0eb0d). Turns out the problem was the underwater scooter: the bot was trying to equip it, which caused it to drop the crate and immediately pick it up again.

**Comment by Rokvach** [comment] 2021-12-09 10:52
Tested, working correctly. Closing.

**Closed by Rokvach** 2021-12-09 10:52 UTC
Labels: Bug, Code, Low prio
