### ISSUE TITLE
[Unstable] ? Subeditor: Selection drag acts strangely with selectable item UI.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#11933] opened 2023-04-30 23:04 UTC
- Build Unstable 1.0.12.0 Windows
(Possibly exists on the current stable, idk.)
- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### Description
The changed drag-selection behavior interacts weirdly with 'selectable UI' items like containers & terminals. This kind of feels 'janky' overall and not intended for sub editor UX.

### Reproduction steps
- Clicking on containers or terminals in sub editor
- Selection box gets stuck active until you click again or exit the UI
- The selection box can accidentally select stuff when it ends

![image](https://user-images.githubusercontent.com/55356135/235380126-c366ef7e-0f18-4e1c-963f-f2c88431cafe.png)

![image](https://user-images.githubusercontent.com/55356135/235380104-9dbcf168-2bd4-4358-b614-732b8feab9e7.png)

![image](https://user-images.githubusercontent.com/55356135/235380134-30374730-a5b7-4e96-8df5-7ec50bf736f4.png)

**Comment by Regalis11** [comment] 2023-05-02 07:53
Thank you for the report!

I unfortunately could not reproduce the issue. LMB doesn't seem to cause the items' interfaces to open, only E does. Are you using non-default keybinds by any chance?

**Comment by Jade-Harleyy** [comment] 2023-05-11 23:33
Hello, I am also having this same issue.

My keybinds are as follows:
![image](https://github.com/Regalis11/Barotrauma/assets/67431770/8905b1e0-f050-4600-8a8f-2c332b083be0)
![image](https://github.com/Regalis11/Barotrauma/assets/67431770/4e2ee0f3-4227-40a9-8a62-5a417623cae4)
![image](https://github.com/Regalis11/Barotrauma/assets/67431770/72ea87db-c0c7-4081-b2b6-0a292c0ec1b3)

Switching "Select" to `Left Mouse Button`, and "Use" to `E` makes it so that inventories in the Submarine Editor can be opened with E, however in-game they become openable with LMB.

**Comment by Jasontti** [comment] 2023-09-04 05:57
There seems to be some hard coded functionality on mouse left button that causes weird behavior.

If you change key layout to this:
![image](https://github.com/Regalis11/Barotrauma/assets/8488224/0510daf2-5ef4-41b7-ad93-61e81b221b8b)

E key for select just doesn't work in sub editor.

Drag selection starts when you open an object and selection stops when you click off the opened window.

https://github.com/Regalis11/Barotrauma/assets/8488224/a0c5772f-d983-44f6-8da7-ba63b36bef2b

**Comment by Regalis11** [comment] 2023-09-04 10:00
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a8078050395383c99cfd695557766dc28041b6b4 (commit in our private repo)

**Comment by Jasontti** [comment] 2023-11-02 11:55
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4441/commits/713bc4a03a6a2f89c252c5df1b7388c81550dca0

Used steps above
Tried different keybindings

No issues found
Closing ticket

**Closed by Jasontti** 2023-11-02 11:55 UTC
Labels: Bug, Code
