### ISSUE TITLE
Forbidden word list not checking descriptions

### ISSUE THREAD

**Issue by SquidingTin** [Regalis11/Barotrauma#10948] opened 2023-01-16 12:38 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I've searched for others with this issue, no one seems to have commented on this.

As the title says, if you try blocking words with the forbiddenwordlist.txt it wont hide servers like it should. though if the servers name has a forbidden word in it, then it will block it.

(Small issue)

### Reproduction steps

1. Enable hide forbidden words
2. See servers with horrible words

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by mygamingaccount** [comment] 2023-01-16 21:05
Why not extend it to mods too?

**Comment by Regalis11** [comment] 2023-01-17 13:37
> Why not extend it to mods too?

I am not sure if you're joking or not, but I don't think this'd be a good idea: the filter isn't foolproof, and can easily cause false positives, but that's not a huge issue with the server names because the host gets notified of the flagged word and can change the name accordingly if they want to. But if the filter applied to mods as well, and you wanted to play with a submarine called [Scunthorpe](https://en.wikipedia.org/wiki/Scunthorpe_problem) or a mod that adds shitake mushrooms as a gardening options, you'd be out of luck.

I think the same applies (although to a lesser extent) to the server descriptions: with a potentially much longer text like this, the risk of false positives is higher, and the false positives might be harder to work around. So I'm not entirely sure if we should actually take measures to address this.

**Comment by mygamingaccount** [comment] 2023-01-17 13:52
Don't know what word you can combine *Waifu* with that will make it less offensive

**Comment by SquidingTin** [comment] 2023-01-20 00:37
mods are to far clearly, but server descriptions should be something that looked into as i dont want to join servers where the description makes me have to look up swear words just to know what they mean

**Comment by Regalis11** [comment] 2023-03-10 10:41
We're cleaning up some low-prio/unreproducible/irrelevant/outdated tickets from the issue tracker, and this is one of the tickets we chose to axe. Closing.

**Closed by Regalis11** 2023-03-10 10:41 UTC
Labels: Design
