### ISSUE TITLE
Crashes To Desktop no Errors, Interacting with Wreck Corpses

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2850] opened 2020-05-17 01:01 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Crashed in Singleplayer something related to Wreck Corpses and their inventory or something.

Crash 1 - Was filling up a Wreck corpse on my sub that I found early-round with items I didn't need. Mid-round gave him more stuff up to one of his hand slot. When I was about to fill his last hand slot with Lithium, CTD.

Crash 2 - Was hauling a Wreck corpse with me inside a Kastrul Wreck. Gave him a Piercing Ammunition Box I found in Gunnery. He didn't had anything else in his inventory, While I was hauling him back in grabbed and dry state, I decided to chop him up with a diving knife to make his body lighter to carry. CTD on the second hit with Diving Knife.

**Version**
~0.9.1001.0

**Comment by Kaillera** [comment] 2020-05-17 01:12
Crash 3 - Playing the game in Singleplayer, found a wreck after about 15 minutes or so in. Went in and found a jobless corpse. Gave him an item. CTD.

**Comment by Regalis11** [comment] 2020-05-17 11:59
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4d3a703831ea8e4083580cdecc51a2578aafd440

**Comment by Rokvach** [comment] 2020-05-18 16:43
I couldn't reproduce any of the issues, everything working correctly. Closing.

**Closed by Rokvach** 2020-05-18 16:43 UTC
Labels: Bug, Code, Crash
