### ISSUE TITLE
[0.9.7.1] Multiplayer - Permanent Freeze

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2407] opened 2020-03-08 19:40 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When playing Barotrauma multiplayer, there may be a permanent freeze during gameplay on a client. Have to end process to restart.

May sometimes Crash to Desktop.

**Steps To Reproduce**
Unknown. Seems random during gameplay. Doesn't happen to everyone at once.

**Version**
0.9.7.1

**Comment by hubismal** [comment] 2020-03-10 05:16
Repeatedly experiencing this on a server after a certain amount of gameplay time. Most recently, someone commented, "Oh shit, hub left" before the game actually froze.

**Comment by hubismal** [comment] 2020-03-12 03:37
Apparently this doesn't just happen in campaign, multiplayer rounds have it too as I just experienced.

**Comment by Regalis11** [comment] 2020-03-23 09:23
Duplicate of #2307

**Closed by Regalis11** 2020-03-23 09:23 UTC
Labels: Bug, Code, Crash, Need more info
