### ISSUE TITLE
Crash in submarine editor when trying to edit loose vent tags

### ISSUE THREAD

**Issue by Zetabite** [Regalis11/Barotrauma#8659] opened 2022-03-30 02:56 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Game crashes in submarine editor, when trying to edit the tags of loose vent

**Steps To Reproduce**
1. Open submarine editor
2. Copy a loose vent
3. Go in loose vent settings
4. Begin removing letters from the tags (in my case i tried deleting hidden)
5. Observe crash

**Version**
0.16.7.0 Linux

**Files**
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/8376635/crashreport.log)

**Comment by Regalis11** [comment] 2022-03-30 07:16
I could not reproduce this with the steps provided, but got it to happen by doing the following:
1. Copy a loose vent (or any other item)
2. Select a structure and the vent
3. Begin removing letters from the vent's tags

Basically the issue had to do with editing the properties of some entity while you had also selected another entity that doesn't have those properties.

Fixed in https://github.com/Regalis11/Barotrauma-development/commit/632fdd418949fc49f47bf65e5b1fdd6893b032ad

**Comment by Rokvach** [comment] 2022-03-31 10:24
Tested, working correctly. Closing.

**Closed by Rokvach** 2022-03-31 10:24 UTC
Labels: Bug, Code, Crash
