### ISSUE TITLE
AI pathing bug when Drone is attached

### ISSUE THREAD

**Issue by SimonTheSkink** [Regalis11/Barotrauma#7128] opened 2021-11-01 22:39 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The AI responsible for making repairs and loading ammo for the Kastrull drone tend to bug out when it’s docked. This issue has only started to occur after the update came out. 

**Steps To Reproduce**
Dock Drone with Kastrull

**Version**
v. 0.15.12.0 Windows 10

**Additional information**

https://user-images.githubusercontent.com/93362696/139751445-0712256a-f22f-4026-8dea-61515e161238.MOV

Please see the attached video for more details.  While not seen here, the room directly above has a mechanic doing the exact same thing.

**Comment by Regalis11** [comment] 2021-11-02 09:26
Duplicate of https://github.com/Regalis11/Barotrauma/issues/5242

**Closed by Regalis11** 2021-11-02 09:26 UTC
