### ISSUE TITLE
Some Images on Barotrauma's Main Download Page Are Outdated- Community Related

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#723] opened 2018-08-21 10:18 UTC
Sonars are blue now, not green and job preference setup in multiplayer is no longer yellow, brown (other colours).

**Comment by BlueTheKing** [comment] 2018-08-21 10:35
Duplicate of #684

**Comment by Regalis11** [comment] 2018-08-21 10:35
Duplicate of #684

**Closed** 2018-08-21 10:35 UTC

**Comment by rico6822** [comment] 2018-08-21 10:50
Oh I forgot I already reported it before.
