### ISSUE TITLE
[Unstable 0.1005.0.0] Can't order a bot to do something if a player has already been ordered to do the same task

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3197] opened 2020-06-23 16:36 UTC
For example if you have a given a order for a player to man the guns, you wont be able to order a bot to man the guns as you would first need to clear the order set to the player.

This is especially annoying if you accidentally order a player to do something when you meant to order a bot to do it.

**Comment by ekqvist** [comment] 2020-06-24 09:33
I'm not sure what if I understand the issue entirely.

1. Assign a player to man a turret.
2. Assign a bot to man the same turret.
3. Bot will be manning the turret.

**Comment by ekqvist** [comment] 2020-06-30 09:19
@Rokvach Any comment on this?

**Comment by Rokvach** [comment] 2020-06-30 09:44
Will need to keep an eye on it, it seemed quite clear when it happened during a community play session. I can't remember if the order was correctly assigned to the bot but the bot just didn't follow the order through or if the order wasn't even applied to the bot.

**Comment by ekqvist** [comment] 2020-07-08 12:36
I will close this issue since there hasn't been another report of this and we don't have steps to reproduce the issue. It can be reopened if the issue resurfaces somehow.

**Closed by ekqvist** 2020-07-08 12:36 UTC
Labels: Code, Feature request, Need more info
