### ISSUE TITLE
Can't uproot plants in planter in front of fabricator/medical fabricator

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#5605] opened 2021-04-25 01:07 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Seems pressing e to try to remove a plant that is in front of a fabricator won't work and the uprooting is blocked by the fabricator

**Comment by Regalis11** [comment] 2021-04-26 08:50
I'm afraid I couldn't reproduce this. Uprooting is done with LMB by default, could the problem be that you were using the wrong key?
![image](https://user-images.githubusercontent.com/14351070/116055636-94aa9300-a685-11eb-8daa-f8ddcfd73cd7.png)

**Comment by thegrb93** [comment] 2021-04-26 22:31
Maybe it's just the plant hadn't fully grown to the point it was allowed to be uprooted. I wasn't aware before that you can't uproot a plant until its grown enough. Would be more convenient if you could.

**Comment by 3e849f2e5c** [comment] 2021-04-27 13:54
Made it so growing plants can be uprooted in https://github.com/Regalis11/Barotrauma-development/commit/9692dbb7b7aafa557172000368e55945f487f6cd

**Comment by Rokvach** [comment] 2021-05-03 06:30
Tested, working correctly, closing.

**Closed by Rokvach** 2021-05-03 06:30 UTC
Labels: Bug, Code
