### ISSUE TITLE
O2 alarm on suit doesn't go off when diving mask was worn when suit was put on.

### ISSUE THREAD

**Issue by someone972** [Regalis11/Barotrauma#4108] opened 2020-10-20 13:21 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Seems that low O2 alarm on diving suit does not trigger when a diving mask was being worn when the suit was put on.

**Steps To Reproduce**
1. Run a diving mask to empty O2.
2. While still wearing the empty mask, put on a diving suit. All is well
3. Take the diving mask off, and put it in your inventory
4. Swap the empty O2 tank from the diving mask into the diving suit. The O2 alarm does not go off.
5. Take the empty tank off the diving suit. O2 alarm will sound. Replace the empty tank onto the diving suit. The O2 alarm will go out.

**Version**
Windows 0.10.6.2, pre-release unstable.
Windows 0.10.5.1

**Additional information**
See the bug in action here: https://www.youtube.com/watch?v=dcTJrOlXoRo&feature=youtu.be

**Comment by someone972** [comment] 2020-10-20 13:33
Just tested this on v0.10.5.1 and it shows the same behavior, removed the [v0.10.6.2] tag from the title.

**Comment by EdusFF** [comment] 2020-10-22 10:15
Fixed in: https://github.com/Regalis11/Barotrauma-development/commit/d49657df6ee050f491d1d418a793622195da8d98

Was caused by just having an empty oxygen tank in your diving suit, probably not related to the mask usage

**Comment by Rokvach** [comment] 2020-10-26 08:34
Tested, working correctly. Closing.

**Closed by Rokvach** 2020-10-26 08:34 UTC
Labels: Bug, Code
