### ISSUE TITLE
Uploading mods return hash error

### ISSUE THREAD

**Issue by Diabolo48** [Regalis11/Barotrauma#11985] opened 2023-05-11 00:32 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [x] My issue happened while using mods.

### What happened?

I've been trying to upload a plethora of content I've done myself from scratch, and I'm not sure what's going wrong.
Here's a screenshot with two such examples:
![image](https://github.com/Regalis11/Barotrauma/assets/99146919/deeaab88-0acb-4b00-b8d8-7af5cc534f20)
Test room is available publicly on the Steam Workshop if you want to check for yourself, under username Diabololi.

I couldn't find anything about hash errors on mods you submitted yourself. The local versions work just fine, I can open them, edit them, no problemo. But anytime I try to upload them, they end up red and impossible to be activated.

I've tried disabling all my mods including local content packages, enabling just the content package I was uploading, enabling the only mod I used (EuropaWaifu without xpath), removed non-vanilla decorations from the sub, reinstalling the game, modifying the filelist.xml manually... And after all of that, I got only two uploads that did not end up as red names.

### Reproduction steps

1. Make a custom sub with a shuttle
2. Try to upload custom sub with its shuttle
3. Get a red name
4. Realise the content package had a lot of extra stuff that didn't belong
5. Branch out new content packages, separating everything neatly
6. Try to upload the sub again
7. Failure
8. Somehow the content package with just the shuttle made it through
9. I try to remove the shuttle from the sub
10. After a ton of renaming and such, the shuttleless sub goes through as not red
11. But it is named "Rasputin without shuttle", and I don't want that name in game
12. So I delete it and try to save it as just Rasputin
13. And now I only get red names and I don't know what I did the only two times I didn't get the bug
14. Try to modify xml files manually hoping for a miracle
15. Plunge into the Abyss in despair

### Bug prevalence

Happens every time I play

### Version

v1.0.13.1

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
I've included such occurence of the red name and "hash error" in the main post.
```

**Comment by Regalis11** [comment] 2023-05-11 05:26
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11977

**Closed by Regalis11** 2023-05-11 05:26 UTC

**Comment by Diabolo48** [comment] 2023-05-11 06:36
I literally just found this one on my own a few minutes ago, @Regalis11! I will try tinkering with the mod versions' a bit and update.

**Comment by Diabolo48** [comment] 2023-05-11 06:54
I was indeed able to fix the problem using the temporary fix given by LePrau. So yeah, closed for good! Thanks again.
