### ISSUE TITLE
Dirty Bomb is locked. 

### ISSUE THREAD

**Issue by CommTac** [Regalis11/Barotrauma#10852] opened 2023-01-01 20:00 UTC
Dirty Bomb can be seen in the fabricator but can't be crafted by the anyone, by the way the Castle  Doctrine that used to have the Dirty Bomb talent got removed from the skill tree, I was really curious about this did you guys removed it or just an accident?

**Comment by Regalis11** [comment] 2023-01-02 08:41
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10823

**Closed by Regalis11** 2023-01-02 08:41 UTC
