### ISSUE TITLE
Banning people after leaving with the menu designed for it crashes server

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#5280] opened 2021-03-21 06:25 UTC
![image](https://user-images.githubusercontent.com/47284081/111895924-d48ab480-8a0d-11eb-8318-23a816322e65.png)
tried to ban astroltor after they left. after choosing a ban duration and pressing ban, the server crashes.
If i had to guess from the message it probably happens because of the "Player was banned" chat message?
[consoleOutput.txt](https://github.com/Regalis11/Barotrauma/files/6176942/consoleOutput.txt)
jump to the end for the error
[networkerror_data.log](https://github.com/Regalis11/Barotrauma/files/6176945/networkerror_data.log)

**Comment by juanjp600** [comment] 2021-03-21 14:51
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/f84f34267a3f289a50cb1574a996a990f777de89

**Comment by Rokvach** [comment] 2021-03-29 13:22
Tested, couldn't reproduce. Closing.

**Closed by Rokvach** 2021-03-29 13:22 UTC
Labels: Bug, Code, Crash, High prio
