### ISSUE TITLE
Attribute "probability" was caculated during the duration when "duration" was in <StatusEffect>

### ISSUE THREAD

**Issue by NotAlwaysTrue** [Regalis11/Barotrauma#13282] opened 2024-01-08 12:12 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Add "probability" into Afflictions give in StatusEffect.
Any value but 0 and 1 works. Any float between 0 and 1(like 0.1 or 0.02) works as the same as 1, which means 100% chance to give the affliction.

Attribute "probability" and its Description are from [https://regalis11.github.io/BaroModDoc/Misc/StatusEffect.html](url)

### Reproduction steps

1.Define a item in your mod like this
```
<Item name="testmed" identifier="testmed" category="Medical" maxstacksize="32" maxstacksizecharacterinventory="8" cargocontaineridentifier="mediccrate" Tags="smallitem,chem,medical,syringe" description="" useinhealthinterface="true" scale="0.5" RequireAimToUse="false" impactsoundtag="impact_metal_light">
  <InventoryIcon texture="Content/Items/InventoryIconAtlas.png" sourcerect="256,448,64,64" origin="0.5,0.5" />
  <Sprite texture="Medicines.png" sourcerect="0,0,37,69" depth="0.6" origin="0.5,0.5" />
  <Body width="35" height="65" density="10.2" waterdragcoefficient="1" />
  <MeleeWeapon canBeCombined="true" removeOnCombined="true" slots="Any,RightHand,LeftHand" aimpos="40,5" handle1="0,0" holdangle="220" reload="1.0" msg="ItemMsgPickUpSelect" HitOnlyCharacters="true">
    <RequiredSkill identifier="medical" level="40" />
    <StatusEffect type="OnUse" target="This" Condition="-100.0" setvalue="true"/>
    <StatusEffect tags="medical" type="OnUse" target="UseTarget">
      <Affliction identifier="bleeding" amount="100" probability="0.1"/>
    </StatusEffect>
    <StatusEffect type="OnBroken" target="This">
      <Remove />
    </StatusEffect>
  </MeleeWeapon>
</Item>
``` 
2.Change 0.1 in `<Affliction identifier="bleeding" amount="100" probability="0.1"/>` to any float value between 0 and 1
3.Find 0.1 or any float not 0 works as 1

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.7.0 (Winter Update hotfix)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2024-01-08 15:48
Thank you for the report! It seems the issue here is that the item is set to damage `UseTarget`, which in this context refers to the character you're using the medicine on. That means it gets applied to all of the limbs, causing it to practically always damage at least one of the limbs. This should be possible to fix by changing the target to `Limb`.

**Comment by NotAlwaysTrue** [comment] 2024-01-09 10:32
> Thank you for the report! It seems the issue here is that the item is set to damage UseTarget, which in this context refers to the character you're using the medicine on. That means it gets applied to all of the limbs, causing it to practically always damage at least one of the limbs. This should be possible to fix by changing the target to Limb.

I just realised that I used the wrong affliction as my example. Sorry about the misleading. The "bleeding" should be replaced by "combatstimulant".
What I found was a non-limbspecific affliction was 100% applied if the value was not 0, which is very confusing. I ran 500 tests in my sub editor and find this. The same thing was found in multiplayer and single player.
Since I was running my game in Chinese(Simpified), is this causing the whole issue?

**Comment by Regalis11** [comment] 2024-01-09 13:26
Ah, thank you for the extra info. It does sound like there's something wrong here then if the affliction is non-limb-specific. I _think_ it should be possible to fix by making the affliction target one limb instead regardless.

**Comment by NotAlwaysTrue** [comment] 2024-01-10 09:26
> Ah, thank you for the extra info. It does sound like there's something wrong here then if the affliction is non-limb-specific. I _think_ it should be possible to fix by making the affliction target one limb instead regardless.

Yes. This does fix the problem. However some of the afflictions I want to apply is supposed to avoid apply these to specific limbs in order to provide a more direct hint.
Would you like to fix it in future updates?

**Comment by Regalis11** [comment] 2024-01-10 09:39
I could not actually reproduce the issue when I changed the affliction to "combatstimulant". The probability seems to work as expected in that case.

**Comment by NotAlwaysTrue** [comment] 2024-01-10 10:19
> I could not actually reproduce the issue when I changed the affliction to "combatstimulant". The probability seems to work as expected in that case.

I found the problem.
Codes in my public mod added "duration" in `<StatusEffect>` and this was not in my example code(I made the same fault once again...), which means the "probability" will get caculated again and again in the duration.
Tried adding Stackable="false" but doesn't work.

**Comment by NotAlwaysTrue** [comment] 2024-01-10 10:29
> I could not actually reproduce the issue when I changed the affliction to "combatstimulant". The probability seems to work as expected in that case.

I made the same thing again...I would check the example code next time.
My public mod has "duration" in `<StatusEffect>` and the probability  got caculated every seconds during the duration.
Added Stackable="false" but it seems not work. I cannot remove "duration" as well since I want these afflictions will hold for some time.

**Comment by Regalis11** [comment] 2024-01-10 11:51
I would not necessarily consider that a bug: the probability is evaluated when the status effect executes, and if the status effect executes every frame for some duration, it's evaluated every frame. It's hard to say how the issue could be worked around without knowing what exactly you're trying to do and how, but I'm fairly sure there should be ways around it. You could for example make the affliction have a duration if you want it to only stay active for some limited amount of time.

Since it seems there's probably no bug here, but something wrong with the way the effect is configured, I think I'll be closing the ticket. If you need help with how to set up the effect in a way that works, I recommend asking for help from [our Discord server](https://discord.com/invite/undertow). Or if it does still seem like there is a bug, please create a report with **the exact XML you're having trouble with** and a description of the problem. It's a waste of time for us to debug a piece of XML that there's no problem with, and then let us know later that it was not actually the up-to-date version of the XML, and that the problem is with some modifications you'd done to it later (which you have now done several times in multiple reports).

**Closed by Regalis11** 2024-01-10 11:51 UTC
Labels: Bug, Need more info, Code
