### ISSUE TITLE
CPU Bottlenecks from Single Threaded Utilization

### ISSUE THREAD

**Issue by MadDog443** [Regalis11/Barotrauma#6996] opened 2021-10-22 22:32 UTC
**Similar Issues**
#115 is quite similar but does not actually point out the biggest issue, it was a broad issue that can't ever be solved which lead to it being closed.

**Description**
Currently Barotrauma is extremely single threaded, this is leading to severe GPU bottlenecking which most modern CPU's cannot handle because they are designed to run a game on multiple threads to saturate a GPU. I think the best solution would to try and offload more stuff from the main thread, add some sort of culling method for simulated actions going on further away from the player that will not affect them till they are within view-distance.

**Steps To Reproduce**
This is reproducible by increasing screen resolution to 1440p or 4k on a 6core cpu clocked at 4ghz, the single core handling most of the game's processes will be overwhelmed and frames will start being dropped. This issue becomes worse with modding.

**Version**
0.14.9.0

**Additional information**
![image](https://user-images.githubusercontent.com/52639083/138529247-ce8e3d0e-1a14-48f8-be24-cca59c8c1f01.png)

**Comment by itchyOwl** [comment] 2021-11-01 13:18
It's true that the game runs heavily in one thread. The game logic usually (if not always) runs in a single thread, because multi-threaded code generally speaking needs to be written without referencing to the other threads. Game logic normally relies on a certain order, which is difficult/impossible to quarantee using several threads. In some games and engines isolated, heavy systems, like pathing, physics, procedural generation etc are sometimes multi-threaded. And that's a good thing.

Because all the characters in Barotrauma are dynamic physics objects, all the physics calculations and checks take relatively big amount of cpu time. It's an issue that we are aware of. And hence we already make use of multi-threading when it comes to physics. But multi-threading is not a silver bullet there: we also use culling, simplified physics, and disabling when characters are far. Alas, we can't disable things that are near/inside the sub, which is where the majority of performance impact comes from.

In Barotrauma we have a lot of items which have a lot of different components that continously keep updating. It's not something that we can change easily and I'm pretty sure we can't use multiple threads there.

Pathing is not multi-threaded, which might be an area worth looking into. But before doing that, we'd need to be able to point out that it would make a difference. To my knowledge all the pathing related performance issues have been caused by too frequent calls to find a new path. Those cases have been issues in the code that uses pathing. Not pathing itself. Multi-threading might make those issues less easy to spot, but it wouldn't actually solve them.

**Comment by MadDog443** [comment] 2021-11-02 06:14
Yeah, a lot of these issues are the exact same ones Space Station 13 ran into years ago, most of them I believe they are still stuck on.

**Comment by etomarat** [comment] 2021-11-08 02:13
This is System Requirement from steam page:
![image](https://user-images.githubusercontent.com/710389/140672877-cfa5c1d4-b948-4dd7-a86f-97aa551a9f1e.png).
I have AMD FX-8300 and NVIDIA GeForce GTX 1050 Ti (4gb), but i can't play even at 720p. FPS drops under 14. It doesn't matter singleplayer or multiplayer, vanilla or modded.
I see the same picture in Task Manager as MadDog443. 
Is there any way to solve this problem?

**Comment by itchyOwl** [comment] 2021-11-09 09:18
The CPU is certainly the bottle neck. I have i5 4670k and I can get a pretty solid 60-120 fps in release builds.

Does the fps drop occasionally and/or mostly in some context or is it constantly low? If there are "lag" spikes, those might be due to issues in the code that we can fix. In order to do that, we'd have to identifiy when and why that happens though. So the steps to reproduce the issue would be very helpful. If the performance in overall is poor, I don't see any other solution than upgrading your CPU, as there's no magic bullet to improve the performance of the game. The minimum requirements might need revisiting too. They seem pretty low to me.

**Comment by MadDog443** [comment] 2021-11-19 04:35
Yeah the main issue is how bound the game is to one core, I'll start documenting bad FPS causes.

**Comment by Regalis11** [comment] 2021-11-22 10:18
We're doing some cleaning on the repository and closing low-prio tickets we most likely won't be addressing at least for the game's full release.

This one is not that low prio, but it's a very broad issue that I don't think can ever be considered "fixed": like I mentioned in #115, optimization is a continuous process and offloading some work to separate branches is one of the options we have to improve the performance (perhaps once we've picked some of the more low-hanging fruits first).

**Closed by Regalis11** 2021-11-22 10:18 UTC
Labels: Code, Performance
