### ISSUE TITLE
Server description cuts off after line 22/23

### ISSUE THREAD

**Issue by TerraTheUnwise** [Regalis11/Barotrauma#9113] opened 2022-05-12 15:40 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I'm hosting a server called Subonized. And a good 90% of the players report not being able to see past line 22/23. I have no mods enabled. And it's a vanilla RP server. I honestly have no idea why this happens.

### Reproduction steps

1. Start a multiplayer server.
2. Join.
3. Not be able to see past line 22/23
4. Give the host a headache.

### Bug prevalence

Happens regularly

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by TerraPlanet** [comment] 2022-05-14 15:54
erm

**Comment by ekqvist** [comment] 2022-06-30 13:06
Not sure what the cause of this is, but it seems that the text is there, but the element just won't scroll enough.

**Comment by TerraPlanet** [comment] 2022-06-30 16:39
It's an anomaly for sure.

**Comment by Regalis11** [comment] 2023-05-26 14:11
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ab0c730b29588fa82c33019bc4675a599ac3d477

**Comment by Rokvach** [comment] 2023-06-01 09:39
Tested, working correctly. Closing.

**Closed by Rokvach** 2023-06-01 09:39 UTC
Labels: Bug, Code
