### ISSUE TITLE
Bodies despawning too fast

### ISSUE THREAD

**Issue by M3M3M31S73R** [Regalis11/Barotrauma#11750] opened 2023-04-04 22:45 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Bodies from monsters just despawn too fast. you don't have time to survive, fix the submarine, get your gear on and loot them before they're all despawned, especially spinelings, they despawn almost immediately 

Thank you for you time and awesome game 

### Reproduction steps

Its a general issue, but just recently the bodies just despawn too fast in general  

### Bug prevalence

Happens regularly

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-04-05 07:52
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11586

**Closed by Regalis11** 2023-04-05 07:52 UTC
