### ISSUE TITLE
cant run the game (crash)

### ISSUE THREAD

**Issue by WildSobhan** [Regalis11/Barotrauma#2793] opened 2020-05-08 14:53 UTC
Barotrauma Client crash report (generated on 5/8/2020 7:17:56 PM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

To prevent further startup errors, installed mods will be disabled the next time you launch the game.

023CCD07C102F6331CAD29D2EADB01E0

Game version 0.9.9.1 (ReleaseWindows, branch release, revision 1968ab79f)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: None
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.18362.0 64 bit
    GPU name: NVIDIA GeForce GTX 1050
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Loading was interrupted due to an error. (Barotrauma.GameMain+LoadingException)
Target site: Void Update(Microsoft.Xna.Framework.GameTime)
Stack trace: 
   at Barotrauma.GameMain.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Barotrauma.Program.Main(String[] args)

InnerException: Object reference not set to an instance of an object.
Target site: Void Init(Microsoft.Xna.Framework.GameWindow, System.Collections.Generic.IEnumerable`1[Barotrauma.ContentPackage], Microsoft.Xna.Framework.Graphics.GraphicsDevice)
Stack trace: 
   at Barotrauma.GUI.Init(GameWindow window, IEnumerable`1 selectedContentPackages, GraphicsDevice graphicsDevice)
   at Barotrauma.GameMain.Load(Boolean isSeparateThread)+MoveNext()
   at Barotrauma.CoroutineManager.ExecuteCoroutineThread(CoroutineHandle handle)
Last debug messages:
[5/8/2020 7:17:56 PM] Coroutine "Load" has failed
[5/8/2020 7:17:55 PM] Coroutine "Load" has thrown an exception {Object reference not set to an instance of an object.}
   at Barotrauma.GUI.Init(GameWindow window, IEnumerable`1 selectedContentPackages, GraphicsDevice graphicsDevice)
   at Barotrauma.GameMain.Load(Boolean isSeparateThread)+MoveNext()
   at Barotrauma.CoroutineManager.ExecuteCoroutineThread(CoroutineHandle handle)
[5/8/2020 7:17:55 PM] No UI styles defined in the selected content package!
[5/8/2020 7:17:55 PM] Attempting to open ALC device "OpenAL Soft"
[5/8/2020 7:17:54 PM] Loaded languages: English
[5/8/2020 7:17:54 PM] No text files available in any of the selected content packages. Attempting to find a vanilla English text file...
[5/8/2020 7:17:54 PM] Content package 'D:\Program Files (x86)\Steam\steamapps\common\Barotrauma\Data\ContentPackages\Vanilla 0.9.xml' not found.
[5/8/2020 7:17:54 PM] Loaded languages: English
[5/8/2020 7:17:53 PM] No text files available in any of the selected content packages. Attempting to find a vanilla English text file...
[5/8/2020 7:17:50 PM] Logged in as wild sobhan (SteamID STEAM_1:1:74547101)

this appears one i try to get in the game

**Comment by Regalis11** [comment] 2020-05-09 13:32
Duplicate of #2713

It seems you're missing the vanilla content package (Barotrauma\Data\ContentPackages\Vanilla 0.9.xml) for some reason. You should be able to fix this by right-clicking the game in your Steam library, going to Properties -> Local files and clicking "verify integrity of game files". Sorry for the trouble!

**Closed by Regalis11** 2020-05-09 13:32 UTC
