### ISSUE TITLE
[Issue/Bug] AI Doesn't fire weapons

### ISSUE THREAD

**Issue by MisterBlackCat** [Regalis11/Barotrauma#2695] opened 2020-04-24 22:35 UTC
- [Yes, I did ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The AI doesn't seem to fire any of the weapons they are assigned to regardless of their skill. Even characters with higher levels in weapons do not fire their guns. This is true for the coil gun (Not tested on railgun) 

**Steps To Reproduce**
Make a fresh and start your sub. Look for/spawn an enemy and assign an AI to the operate the weapon (Fire at will, of course) 

**Version**
0.9.9.0

**Comment by Xeraster** [comment] 2020-04-25 02:27
I tried to fix this by replacing "AIObjectiveCombat.cs" and then "AIObjectiveOperateItem.cs" in server but none of those ideas fixed it. Curiously, there are no debug messages outputted to the console when the ai fail to fire at a target.

**Comment by Regalis11** [comment] 2020-04-25 14:02
Duplicate of #946

**Closed by Regalis11** 2020-04-25 14:02 UTC
