### ISSUE TITLE
Bots get stuck on secure lockers in armory when cleaning up

### ISSUE THREAD

**Issue by dominik1106** [Regalis11/Barotrauma#8072] opened 2022-01-21 17:59 UTC
When Bots try to bring items to a container they don't have access to, they will stop and wait in front of the container.
I noticed this particularly whenever I bought SMG-Mags and would have 2 or 3 NPCs wiggling in front of the secure locker. Both on Dugong and  Typhon2.
This was a singleplayer campaign.

Ver. Stable v0.15.23.0 Windows

**Comment by ekqvist** [comment] 2022-02-03 15:45
Thanks for the report! However, I was unfortunately unable to reproduce the issue on either of the submarines. The bots don't seem to even attempt to clean up the SMG magazine as they don't have access to the container. I tried both having an SMG magazine on the floor and an SMG magazine inside a metal crate.

Is this something that happens to you regularly? If there are any additional steps you could provide that might help in diagnosing the issue, that could be helpful.

**Comment by itchyOwl** [comment] 2022-02-11 22:04
Seems to happen to me frequently in my campaign playthrough: the bots pickup newly bought shotgun shells in Orca2 and try to put them in the secure locker. Ignoring the locker fixes it, but it's still an issue.

Couldn't get the repro steps: doesn't seem to happen if I spawn shells and thell the bot to clean those up or if I buy them and tell them to clean up. But it does seem to happen in my current save, so I can take a look into it.

**Comment by itchyOwl** [comment] 2022-02-21 17:22
Fixed in Regalis11/Barotrauma-development@b0908de.

The bots attempted to put ammunition inside the weapons that were inside the secure locker.

Steps to repro:
- Start the game e.g. in Orca2
- Ensure that there's an empty shotgun in the secure locker
- Spawn/drop some shotgun shells on the floor
- Tell a bot to clean them up
- If you can't repro, try ignoring the closest locker

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/acb2c862-0570-47a2-a87c-c098f461c83e)

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/00a40526-6876-4126-9a70-29b0ded51544)

**Comment by itchyOwl** [comment] 2022-02-22 11:06
The commit above wasn't enough. There's a couple of related commits after that. But should now be fixed in any case.

**Comment by Rokvach** [comment] 2022-03-08 09:02
Tested, working correctly. Closing.

**Closed by Rokvach** 2022-03-08 09:02 UTC
Labels: Bug, Code
