### ISSUE TITLE
Inconvenient Ruins Spawning Blocks Level Progression

### ISSUE THREAD

**Issue by ZealanL** [Regalis11/Barotrauma#1104] opened 2019-02-08 23:54 UTC
**Description**
This bug happens when ruins generate directly in front of the level start. This has also been reported to happen every once in a while on my server, where ruin generation prevents level progression.

**Steps To Reproduce**
Reproduction of this issue would probably require a lot of generating and checking random maps but could be done.

**Version**
This is a level generation bug and should occur regardless of game version. Nevertheless, I will inform you that I am on Windows, and my server is on Linux.

**Evidence of glitch**
The attached image below happened when I was testing out my submarine in a singleplayer campaign, the ruins spawned directly in front of the level spawn.
![Ruins Blocking Level Progression](https://user-images.githubusercontent.com/36944229/52512463-bceb6b80-2bb9-11e9-8be6-19297df4cbac.png)

**Comment by Regalis11** [comment] 2019-02-09 14:32
Duplicate of #949

**Closed** 2019-02-09 14:32 UTC

**Comment by ZealanL** [comment] 2019-02-18 00:37
Oh, my apologies. I couldn't find any issues about this. Thx for fixing.
