### ISSUE TITLE
Plasma cutter unintended buff?

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8112] opened 2022-01-27 23:58 UTC
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Mostly making this ticket because i don't see any mention of a change like this being made, but the plasma cutter suddenly went from  barely doing damage to killing humans in seconds

**Version**
unstable v0.16.1.0

**Comment by Regalis11** [comment] 2022-01-28 07:53
This seemed to have been caused by the optimizations we did to status effects: the plasma cutters were doing damage to all the target's limbs, not just the one the cutter hits. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0d1a48001315f2eb49f8212fd309f90cc50f88d6

**Comment by Rokvach** [comment] 2022-02-01 15:11
Tested, working correctly. Closing.

**Closed by Rokvach** 2022-02-01 15:11 UTC
Labels: Bug, Code
