### ISSUE TITLE
flashlight effect remains when equipping a belt slot weapon with a flashlight attachment

### ISSUE THREAD

**Issue by OCDscavenger** [Regalis11/Barotrauma#12001] opened 2023-05-12 13:03 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When swapping a belt slot weapon with a flashlight attachment with another object already in the belt slot, the flashlight effect will not go away until the weapon is reequipped and unequipped again.

### Reproduction steps

1. start any game
2. spawn in a toolbelt, flashlight, and any weapon that goes in the belt slot.
3. wear toolbelt
4. attach flashlight to belt slot weapon
5. while holding belt slot weapon, drag the weapon icon over the tool belt in the belt slot to equip the weapon and hold the tool belt

effect might be recreatable with other toolbelt objects such as riot shields

### Bug prevalence

Happens every now and then

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-05-12 14:06
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11023

**Closed by Regalis11** 2023-05-12 14:06 UTC
