### ISSUE TITLE
User can resize a Label with without causing Label text to recenter

### ISSUE THREAD

**Issue by ssustrich** [Regalis11/Barotrauma#4515] opened 2020-12-14 06:52 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Item Label text does not recenter when Item Label width is changed

**Steps To Reproduce**
1) In Submarine Editor drop an item label on to the workspace
2) Drag the resize corner to 15x2 grid units
3) In the Label Item inspector set the text to: First Aide
4) Observer that text text First Aide is centered
5) Resize the Item Label by with the resizing corner to 10x2
6) Click on another placed item or the blue workspace itself
6) Observe that the text is still in the original position and that it extends off of the right side of the Item Label
7) In the Item Label inspector window change the text to: foo
8) Press tab to lose focus on the Text textField
9) Observe that the modified text is re-positioned to be in the center of the Item Label
v0.11.0.9 (ReleaseWindows, branch release, revision c60afcc03b)

**Version**
v0.11.0.9 (ReleaseWindows, branch release, revision c60afcc03b)

**Additional information**
![20201214073442_1](https://user-images.githubusercontent.com/28288/102049359-fe19bb80-3de0-11eb-9936-4dc6061b0b35.jpg)

**Comment by 3e849f2e5c** [comment] 2020-12-14 12:23
Duplicate of #4370

**Closed by 3e849f2e5c** 2020-12-14 12:23 UTC

**Comment by ssustrich** [comment] 2020-12-14 17:14
Sorry I swear I checked for Label and text and I didnt get a hit. I'm so sorrry.
