### ISSUE TITLE
[Bug] Kastrull – Pump in command-room never disables.

### ISSUE THREAD

**Issue by roidal** [Regalis11/Barotrauma#1973] opened 2020-01-07 21:39 UTC
After the command-room get flooded for the first time the pump doesn't disable anymore, since the sensor keeps sending "1" even if all water (reachable by the pump) was removed.

**Comment by ezjamsen** [comment] 2020-01-08 12:10
Could not reproduce, regardless, whole pump setup has been replaced with a simpler system.

**Comment by Rokvach** [comment] 2020-01-22 10:55
Tested, working correctly. Moving to Done.

**Closed** 2020-02-04 12:10 UTC
Labels: Bug, Design, Needs testing
