### ISSUE TITLE
Immediately Crashes on Battle everytime... (DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved)

### ISSUE THREAD

**Issue by Jurixon** [Regalis11/Barotrauma#1951] opened 2019-12-22 13:36 UTC
Immediately Crashes on Battle everytime... PLEASE HELP....

Crash Report... :
Barotrauma Client crash report (generated on 2019-12-22 14:22:26)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

82D5F98C9FFDE58E64CF140A88952446

Game version 0.9.6.0
Graphics mode: 1680x1050 (BorderlessWindowed)
Selected content packages: Vanilla 0.9
Level seed: VortaSontu
Loaded submarine: Orca (FD0D71CD29578A6D122AFD7EEB01EE91)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.18362.0 64 bit
    GPU name: AMD Radeon R9 200 Series
    Display mode: {Width:1680 Height:1050 Format:Color AspectRatio:1,6}
    GPU status: Normal

Exception: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Wystąpienie urządzenia GPU zostało zawieszone. Użyj obiektu GetDeviceRemovedReason, aby określić odpowiednią akcję.

Device removed reason: HRESULT = 0x887A0006
Target site: Void CheckError()
Stack trace: 
   w SharpDX.Result.CheckError()
   w Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent()
   w Microsoft.Xna.Framework.SdlGamePlatform.Present()
   w Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
   w Microsoft.Xna.Framework.Game.Tick()
   w Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   w Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   w Barotrauma.Program.Main(String[] args)

Last debug messages:
[2019-12-22 14:19:31] Logged in as Jurix (SteamID STEAM_1:0:28629205)

**Comment by Regalis11** [comment] 2020-01-20 15:49
We've been so far unable to reproduce this issue, but got one similar-looking report through the Steam forums: https://steamcommunity.com/app/602960/discussions/1/2659871169521148710/

In his case the error only occurred when VSync was off, meaning that the game is allowed to render at unrestricted FPS.

We added the option to restrict the framerate even when VSync is off to hopefully fix this in the next update: https://github.com/Regalis11/Barotrauma-development/commit/b081cb936387ff94a27ef5496939c87bceae31a8 (private repo). If you don't have VSync enabled, for now it might be worth a shot to enable it and see the issue disappears.

**Comment by Regalis11** [comment] 2020-01-20 20:04
Just noticed there was already another ticket about this, closing as a duplicate of #1826

**Closed by Regalis11** 2020-01-20 20:04 UTC
Labels: Bug, Code, Crash, High prio, Needs testing
