### ISSUE TITLE
[0.9.10.0] Harpoons hit detection is unreliable in Thalamus wrecks

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2827] opened 2020-05-14 12:24 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I was using Harpoon Gun in a Thalamus Wreck, and the hit detection is unreliable. My shots went through Leucocytes more than half the time. Not sure if it's related to shooting them through different hulls and doors.

**Version**
0.9.10.0

**Comment by Regalis11** [comment] 2020-05-14 16:04
Looks like non-raycast projectiles (like harpoons or 40mm grenades) still hit destroyed thalamus organs. If that was causing this, should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/c6abf9807c8cedb331ac9b20ef188de55ab983e4

**Comment by Rokvach** [comment] 2020-05-18 13:21
Wasn't able to reproduce the issue anymore, working correctly. Closing.

**Closed by Rokvach** 2020-05-18 13:21 UTC
Labels: Bug, Code
