### ISSUE TITLE
Multiple Captain Hognose's on redocking and starting mission again

### ISSUE THREAD

**Issue by DoopieWop** [Regalis11/Barotrauma#9796] opened 2022-08-30 22:20 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I encountered Captain Hognose on a colony and accepted his quest. I selected the mission to kill the Moping Jack and Captain Hognose appeared on my ship. However after I had already loaded the mission, I realized that I forgot to buy some items. I docked with the colony again, bought everything and went back. After selecting the same mission again, I had 2 Captain Hognose's on my ship. I assume you can get more and more for each time you dock and start the mission.

### Reproduction steps

1. Find Captain Hognose on a station and accept his quest.
2. Load the mission to kill the Moping Jack.
3. Dock back to the starting station.
4. Load the same mission again.
5. There will be multiple Captain Hognose's on your sub.

### Bug prevalence

Just once

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-08-31 11:03
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5721bfbab9722b62bd8d726f8b33188f4141e79c

**Comment by NilanthAnimosus** [comment] 2022-09-08 14:26
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/f60a2ad003be4fcf1fd3e7d6c675a3f0dbcce861.

noted a weird issue that I don't think should be caused by this, but two separate new campaigns caused it.

![image](https://user-images.githubusercontent.com/29177976/189147861-d7ae56bd-802b-4bf1-b930-4c67bc0d09f1.png)

when starting a new campaign in multiplayer then using triggerevent hognose (to get this event to show) - selecting the mission then starting a round It will spawn only one hognose, yet duplicate him in the crew orders. redocking and trying the mission again though does not spawn two captain hognose's (And only shows one in the crew orders list). The server player list shows only one of the captain too making it somewhat odd.

**Comment by Regalis11** [comment] 2022-09-09 06:39
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/135000890cb54463a043d457289af03d92df46d7

**Comment by NilanthAnimosus** [comment] 2022-09-19 09:12
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/68d02ff7ba62555e380a24ff29b99b8a05450339, no issues found, closing.

**Closed by NilanthAnimosus** 2022-09-19 09:12 UTC
Labels: Bug, Code, Unstable
