### ISSUE TITLE
I found the source of the performance issue.

### ISSUE THREAD

**Issue by enceos** [Regalis11/Barotrauma#11920] opened 2023-04-27 21:26 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

As the game progresses, the FPS slows down to a crawl.

### Reproduction steps

I started digging into the ways to improve the Barotrauma experience with my buddies after our sessions slowed down to a crawl of 8 FPS. I have a high-end rig, and there was definitely something not right about the way the game performed.

I did extensive testing and found that the main culprit is the loot stored on my sub. Ragdolls, textures, lights, geometry, all seem to play very little role in the performance drop. Even if a sub is gigantic, there's little impact as long as it has no items.

For some reason, the game gets overflown with mundane calculations about the items a sub has at any given moment. The more items you have, the worse the performance gets. Just a stack of resources lying in a locker somewhere already sucks up precious performance.

Some code is constantly pinging all the loot in the background without player request. This code needs to be revised.

My current workaround: Reduce the clutter and transfer all the surplus items by hand for storage on an older sub. The performance gain is tenfold.

(copied my report from steam, as I did not see any dev responses)

### Bug prevalence

Happens every time I play

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-04-28 06:25
Duplicate of https://github.com/Regalis11/Barotrauma/issues/9446

**Closed by Regalis11** 2023-04-28 06:25 UTC
