### ISSUE TITLE
Submarines are downloaded even if you have their package downloaded

### ISSUE THREAD

**Issue by evilfactory** [Regalis11/Barotrauma#9174] opened 2022-05-19 21:28 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

The game does indeed check if you already have the submarine, but it only does for enabled packages, the problem is that submarine packages are always disabled when you join a server, because they are multiplayer compatible, to solve this, it should instead look for all packages, not only enabled ones.

### Reproduction steps

1. Enable a submarine package in your settings, and start DedicatedServer.exe
2. Join the server
3. Watch you still downloading the submarine from the server, even though you already have the same exact submarine package

### Bug prevalence

Happens every time I play

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by JoneKone** [comment] 2022-05-19 21:31
I confirm on Linux

**Comment by NilanthAnimosus** [comment] 2022-08-03 10:48
Tested against sub-dl-fix branch commit https://github.com/Regalis11/Barotrauma-development/commit/24bad9a5b20f3783cf5f34daed74d06a1a8a9a3d

Doesn't seem to work or at least did not match the behavior I expected when testing. I had a workshop submarine and local submarine on the server not enabled on the client (as well as a random assortment of matching loaded submarines, mods etc in case) on the server.

the local mod submarine I had removed from the clients localmods to force a download. the workshop one was merely disabled. the client however still had to download the workshop submarine when it was selected in the server list as it was grayed out - instead of the client enabling the workshop package that contained the submarine it already had.

**Comment by Regalis11** [comment] 2022-08-17 13:39
I'm afraid I could not reproduce that, the client seemed to enable the mods with no issues.

Tested by installing and enabling the following mods (one local mod and 2 from the workshop):
![image](https://user-images.githubusercontent.com/14351070/185148332-4f23fe24-0adc-46b5-9bd7-ab4554c249e5.png)

Then I created a copy of the whole game folder and started up a server. I started another instance of the game, disabled all those mods, and was able to join the server without having to download anything.

**Comment by NilanthAnimosus** [comment] 2022-08-17 15:38
Tested against sub-dl-fix branch commit https://github.com/Regalis11/Barotrauma-development/commit/24bad9a5b20f3783cf5f34daed74d06a1a8a9a3d

Without re-ordering the mods, and performing the following test setup:
Server mods:
![image](https://user-images.githubusercontent.com/29177976/185179496-d021b97c-d529-4e61-b092-2542b4f4cc66.png)

Client Mods:
![image](https://user-images.githubusercontent.com/29177976/185179570-4d7394b0-fcff-4ed3-9d21-067a6e624577.png)

Unsubbed & disabled - the initiator
Still subbed & disabled - dandelion
Removed Local mod & disabled - Winterhalter Fab UI
Local mod & disabled (Identical file server and client) - Kastrull chair test.

first test, got a crash:
![image](https://user-images.githubusercontent.com/29177976/185180196-3123c6c3-1248-4655-8afa-e41fac57208a.png)
![image](https://user-images.githubusercontent.com/29177976/185180386-22966570-b219-434e-913e-6d38a2215ce5.png)

Realized my local mods did not match, despite loaded both sides and recognized as different (Client had some changes for another test). Note the client never started the game with the local mod that was removed loaded at any point, but this crash appears to be expecting it without having downloaded it due to said local mod missmatch.

Curiously, fixing this it worked as expected - loading in game without a ton of unrequired submarine downloads, enabling those in the list that the client had and not downloading submarines that are not selected. connecting with a sub file selected (that the client does not have) also downloads fine in lobby no issues there.

So although I couldn't reproduce it (and no longer have the combination of mods and file changes used that caused my initial observations) it seems I instead have found a crash bug now.

**Comment by Regalis11** [comment] 2022-08-18 08:48
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/005b6e301cedde210270c06326a5bcbe979b363b

**Comment by NilanthAnimosus** [comment] 2022-08-24 12:32
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/17a4e29619e49adc0a329be654296cf8f8ddc5d6

It no longer crashes when it has mods that require downloading while having none mandatory (IE. submarine) mods not enabled which the server has (even if the client is missing them or not). I also cannot find any crash or code issues.

However I noticed one thing about how all this works, although no submarines are downloaded unnecessarily anymore ones you have which match the server (IE. up to date workshop submarines and such) don't even try to be enabled instead preferring to download when selected inside the lobby.

This was tested with the sub DL branch merged into dev so its so fast I wouldn't even consider it much of an issue, but I do feel if the client has the same up to date submarine mods (matching hash and all) they could perhaps try to enable them on join.

**Comment by Regalis11** [comment] 2022-08-25 06:57
The fix has not been merged to dev yet, and needs to be tested in the `sub-dl-fix` branch. Moving back to QA.

**Comment by NilanthAnimosus** [comment] 2022-08-25 08:16
Retested against sub-dl-fix branch commit https://github.com/Regalis11/Barotrauma-development/commit/005b6e301cedde210270c06326a5bcbe979b363b (I previously tested the incorrect branch).

Found no issues with the same test I did prior involving a dozen workshop, none workshop mods, active and inactive and even reordered slightly. alongside 1 local mod with modified files between the server and client (as to force a mod d/l on top).

no unnecessary downloads occurred other than a deliberately miss matching local mod, and the client enabled all expected submarines that matched the servers submarines.
![image](https://user-images.githubusercontent.com/29177976/186612317-fb6a46b7-a3ef-4dbc-814d-fc16581486bc.png)


I did a second test where I modified a workshop submarine to be "Out of date" client side by having the server already running then while the client is not running modified the \Daedalic Entertainment GmbH\Barotrauma\WorkshopMods\Installed\ folder of a specific submarine (In my case EK Huxley MK-V submarine)
I changed:
```modversion="1.0.0" gameversion="0.14.6.0" installtime="1623978055"```
to:
```modversion="0.9.9" gameversion="0.13.6.0" installtime="978055"```

This made my client think it needs updating then joined the server. However I saw something unusual. Only the missmatching local mod I edited (to test for the crash fix) updated, no mention of submarines and its enabled in the list:
![image](https://user-images.githubusercontent.com/29177976/186611056-dae147bd-5b2c-4620-92a6-f5214db6827a.png)
Yet other workshop submarines are...not enabled? which should match the version?

There are even local submarine mods disabled in the submarine list, despite they are 1:1 matching between client and server which is just a copy of the build after enabling the mods.
![image](https://user-images.githubusercontent.com/29177976/186611172-08f1cf4b-2e4e-4bb2-aa58-f403d0167531.png)

My clients mods, submarines and load order:
![image](https://user-images.githubusercontent.com/29177976/186611524-a24431c9-03c1-4762-9e2b-bb2dc98ac0ad.png)
The servers mods, submarines and load order:
![image](https://user-images.githubusercontent.com/29177976/186611888-714b802a-19a3-40cd-8b27-b140ec7d547c.png)
(+ Kastrull chair test at the end)

I would finally like to add the EX_Huxley_Mk-V sub is not in my \Daedalic Entertainment GmbH\Barotrauma\temp folder, nor the games submarines/downloaded folder. perhaps it enabled as the content hash matches fine despite its file list details do not, but why are the other submarines not enabled?

**Comment by Regalis11** [comment] 2022-08-25 08:56
Hopefully fixed in https://github.com/Regalis11/Barotrauma-development/commit/9d0c6e1dc20056b79b34e4d549efa2cd61e39ac6

**Comment by NilanthAnimosus** [comment] 2022-09-09 08:19
Tested against sub-dl-fix commit https://github.com/Regalis11/Barotrauma-development/commit/9d0c6e1dc20056b79b34e4d549efa2cd61e39ac6.

This is before merging dev into the branch

enabled local/workshop submarines with a matching hash stay enabled now when joining a server.

just to get the current behavior down:

Submarines you do have but are not enabled (local or workshop) that are the same hash match will not be enabled when joining, instead downloading in game when selected from the list.

No unnecessary downloads occur on joining, only required packages with miss matches in hash.

**Comment by NilanthAnimosus** [comment] 2022-09-09 08:44
Tested against sub-dl-fix commit https://github.com/Regalis11/Barotrauma-development/commit/9e62d86b9d5b6a30fbf79aed7687325420b8e484

Post-merging has caused a new error and I am unable to join the server with the same test anymore:

![image](https://user-images.githubusercontent.com/29177976/189310005-dedb77d4-3e26-4185-9c71-a1df8df38832.png)

![image](https://user-images.githubusercontent.com/29177976/189309235-f7e85e9c-4d61-4d69-8a9e-f0ea905d876d.png)

**Comment by Regalis11** [comment] 2022-09-09 12:51
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/32604fd13563e04cff628dc924d7de57bff70d44 (also cherry-picked the fix to dev)

**Comment by NilanthAnimosus** [comment] 2022-09-13 09:02
Tested against sub-dl-fix commit https://github.com/Regalis11/Barotrauma-development/commit/9c174a1278f831468d6200e315667ae516269831

used the same setup I had previously used before, and got "Input contains duplicate packages":

```
Barotrauma.dll!Barotrauma.ContentPackageManager.EnabledPackages.ThrowIfDuplicates(System.Collections.Generic.IEnumerable<Barotrauma.ContentPackage> pkgs) Line 114
	at C:\Github_Sources\Barotrauma\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentPackageManager.cs(114)
Barotrauma.dll!Barotrauma.ContentPackageManager.EnabledPackages.SetRegularEnumerable(System.Collections.Generic.IReadOnlyList<Barotrauma.RegularPackage> inNewRegular) Line 81
	at C:\Github_Sources\Barotrauma\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentPackageManager.cs(81)
Barotrauma.dll!Barotrauma.Extensions.IEnumerableExtensions.Consume<Barotrauma.ContentPackageManager.LoadProgress>(System.Collections.Generic.IEnumerable<Barotrauma.ContentPackageManager.LoadProgress> enumerable) Line 149
	at C:\Github_Sources\Barotrauma\Barotrauma\BarotraumaShared\SharedSource\Extensions\IEnumerableExtensions.cs(149)
Barotrauma.dll!Barotrauma.ContentPackageManager.EnabledPackages.SetRegular(System.Collections.Generic.IReadOnlyList<Barotrauma.RegularPackage> newRegular) Line 75
	at C:\Github_Sources\Barotrauma\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentPackageManager.cs(75)
Barotrauma.dll!Barotrauma.ModDownloadScreen.Update(double deltaTime) Line 328
	at C:\Github_Sources\Barotrauma\Barotrauma\BarotraumaClient\ClientSource\Screens\ModDownloadScreen.cs(328)
Barotrauma.dll!Barotrauma.GameMain.Update(Microsoft.Xna.Framework.GameTime gameTime) Line 859
	at C:\Github_Sources\Barotrauma\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs(859)
MonoGame.Framework.Windows.NetStandard.dll!Microsoft.Xna.Framework.Game.DoUpdate(Microsoft.Xna.Framework.GameTime gameTime) Line 651
	at C:\Github_Sources\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs(651)
MonoGame.Framework.Windows.NetStandard.dll!Microsoft.Xna.Framework.Game.Tick() Line 500
	at C:\Github_Sources\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs(500)
MonoGame.Framework.Windows.NetStandard.dll!Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() Line 93
	at C:\Github_Sources\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs(93)
MonoGame.Framework.Windows.NetStandard.dll!Microsoft.Xna.Framework.Game.Run(Microsoft.Xna.Framework.GameRunBehavior runBehavior) Line 397
	at C:\Github_Sources\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs(397)
MonoGame.Framework.Windows.NetStandard.dll!Microsoft.Xna.Framework.Game.Run() Line 367
	at C:\Github_Sources\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs(367)
Barotrauma.dll!Barotrauma.Program.Main(string[] args) Line 58
	at C:\Github_Sources\Barotrauma\Barotrauma\BarotraumaClient\ClientSource\Program.cs(58)
```

Checking the code quickly, it attempted to load 20 packages, of which I noticed my local submarine mod "Barsuk turret scale test" was loaded twice. I believe this may be due to the client and server loading the same submarine mods while having a content mod to download as client as I noticed the client and server had a 1:1 mods match so it appears to have loaded much of it twice.

there was only 11 packages to actually load and 1 of those was to be downloaded by the mod download screen and another was up to date mod content, so 9 submarine files (*2) + the 2 content mods makes up those 20 packages.

**Comment by Regalis11** [comment] 2022-09-13 09:28
Hopefully fixed now https://github.com/Regalis11/Barotrauma-development/commit/98df11dbc256d35d755bb7449eac5e023f4a42cd

**Comment by NilanthAnimosus** [comment] 2022-09-14 09:04
Tested against sub-dl-fix commit https://github.com/Regalis11/Barotrauma-development/commit/98df11dbc256d35d755bb7449eac5e023f4a42cd, no issues found

Tried with mods needing updates, no mods at all. matching and mismatching mods and load orders.

I think this is ready for merging now.

**Comment by Regalis11** [comment] 2022-09-14 09:35
It seems this was just an UI issue: the client did enable the submarine mods, but didn't refresh the state of the lobby (making it seem like the client doesn't have those subs). Fixed in https://github.com/Regalis11/Barotrauma-development/commit/498e1ef0b6da3f6e9fbfbd556f749a9ec876e01e

**Comment by NilanthAnimosus** [comment] 2022-09-14 11:51
Tested against sub-dl-fix commit https://github.com/Regalis11/Barotrauma-development/commit/98df11dbc256d35d755bb7449eac5e023f4a42cd

fixes work well and no issues in my tests, I think this should be ready for merging now into dev.

**Comment by Regalis11** [comment] 2022-09-14 12:38
Pushed yet another fix https://github.com/Regalis11/Barotrauma-development/commit/e12562eeffedd30095b01ea0297941c004bc22fd

**Comment by NilanthAnimosus** [comment] 2022-09-15 13:38
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/d206ec490f7210e2731599fac655a232d893b804, no issues found, closing.

**Closed by NilanthAnimosus** 2022-09-15 13:38 UTC
Labels: Bug, Code, Modding, Unstable
