### ISSUE TITLE
[0.1000.0.0] Missing Preview Images for Owned Submarines

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2918] opened 2020-05-29 18:03 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Preview images for Owned Submarines are missing at the Delivery menu.

**Version**
0.1000.0.0

**Comment by Regalis11** [comment] 2020-06-01 13:43
Didn't check if this happens in single player as well, but in multiplayer the server doesn't save the submarine's preview images which would explain this. An easy way to solve this would be just to make the server save them, but I'm not sure if that's the best way to go because it'd make the save files significantly bigger (multiple pictures that can be several megabytes each).

**Comment by EdusFF** [comment] 2020-06-11 11:30
Did some fixes to submarine fetching in multiplayer and added a backup to look at the clients' saved submarines for an image. Let's see if this is enough to display images in most cases, backup might fail if there's a submarine with a duplicate name

**Comment by Rokvach** [comment] 2020-06-15 16:54
Apparently this is still an issue, moving back to to do.

**Comment by EdusFF** [comment] 2020-06-16 10:09
Let's see if this is still a problem after the submarine syncing is updated to match the needs of the multiplayer campaign

**Comment by Rokvach** [comment] 2020-07-02 09:04
I noticed this on singleplayer when I bought a custom sub the preview of my current sub vanished, but I wasn't able to reproduce it

**Comment by Rokvach** [comment] 2020-07-03 10:06
No issues, closing.

**Closed by Rokvach** 2020-07-03 10:06 UTC
Labels: Bug, Code
