### ISSUE TITLE
No button to exit stations without submarine docked

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2068] opened 2020-01-29 17:10 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Can't escape from stations after entering it via diving, or left behind.

**Version**
0.9.6~0.9.701

**Additional information**
If you were out of power and battery power, the only way to get fuel is to dive to the closest station and craft one to bring back. Without 2 players at minimum, one to stay outside with the hatch button, it'd be impossible to bring back via solo.

**Comment by Regalis11** [comment] 2020-01-31 12:49
Duplicate of #1784

**Closed by Regalis11** 2020-01-31 12:49 UTC
