### ISSUE TITLE
[0.9.1001.0] Invisible aliens

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2856] opened 2020-05-18 10:53 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Every few while when I am outside my submarine diving, I get attacked by invisible aliens. I can see them on the sonar, but not visually. It happens outside the submarine, including wrecks and ruins.

In one instance I opened a Ruin room up. Looking around with a flashlight, the room was completely clear but I heard husk noises. After lingering for a short moment, I got bitten by 3 husks that showed up on my screen suddenly next to me.

Another time I had a bone thresher in my submarine's blind spot, so I went out to fight it. I couldn't see it, but it was charging and biting on my character every few while. Never seen it, but it was killed by my submarine's engine shortly after.

**Version**
0.9.1000.0~9.9.1001.0

**Comment by Regalis11** [comment] 2020-05-18 11:17
Duplicate of #2767

**Closed by Regalis11** 2020-05-18 11:17 UTC
