### ISSUE TITLE
Sometimes Items Take Too Long to Make from a Fabricator and Appear to be Stuck

### ISSUE THREAD

**Issue by gerakis** [Regalis11/Barotrauma#7739] opened 2021-12-13 03:32 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Sometimes when making items from a fabricator items take much longer than their nameplate construction time and appear to be stuck. Other players can see this too on multiplayer and commented about it being stuck and broken. The other players were unable to cancel the build, but I still could.

I think it might have something to do with reaper's tax because ive only ever seen this bug with reaper's affecting me. Upon gaining skill points well beyond what should be required (even considering the reapers deduction) the bug goes away and you can make items at full speed again. Meaning if the skill check were 20, I have 25 skill and the reapers was -4, (for 21 total, which should be enough) I still could not make at full speed. If I kept raising my skill points till I was at skill 30 or something like that I could then make this at full speed. I dont know the exact numbers but I can tell you it didn't add up correctly.

**Steps To Reproduce**
Make items in game at a fabricator with reapers tax that you are close to the minimum skill check on. I noticed it when making plasma cutters, oxygen bottles, and slipsuits as a security guard. This was in multiplayer.

**Version**
v0.15.13.0 Windows 10 x64

**Additional information**
Here is a video of what it looks like in game. As you can see the timer just resets back to full after reaching the normal duration. While you cannot see it in the video, if I were to wait several minutes the cutters would have been successfully made.

https://youtu.be/n-OsbZtKXZc

**Comment by Ek-Videogames** [comment] 2021-12-14 04:23
Additional information: desync, it drops the trigger to finish fabrication, which causes the timer to instead continue incrementing indefinitely. This can be caused by a variety of things:
-
- Client starts fabrication but server fails to receive info from the client that the fabricator has started to begin with. 
`(Packet-loss, _time goblins_, mystery reasons -etc)`
- Server receives fabrication info from the client but corresponds to the wrong fabricated item for the given inputs so the server does not accept it as valid information.
- Fabricator appears to be powered on client's side `(due to a desynced battery or junction that is fine on client side but is actually broken)` so the server does not accept it as valid information.
- Fabricator appears to be working on client's side but has been destroyed on server's side, so the server's fabrication timer is not progressing at all while the client's is.
- Another client has begun fabricating an item, but the server has not sent you the information to show that fabricator is in use `(for any of the reasons listed above`) - the fabricator cannot start fabricating an item if it is already fabricating something else, so the server does not accept it as valid information.

**Comment by Regalis11** [comment] 2021-12-14 13:08
@Ek-Videogames Even though some of those guesses could explain this, but I think it sounds like you have some misconceptions about how the game's networking works. The clients send the information about turning on the fabricator as a network event, and if the server failed to receive it, it should lead to a desync kick. The same goes for notifying the clients about someone else turning on the fabricator. And what do you mean by the "trigger to finish fabrication"?

**Comment by Regalis11** [comment] 2021-12-14 13:24
Potentially fixed in https://github.com/Regalis11/Barotrauma-development/commit/7a32680b01ed7cb7134d4d7a626a6b5f8c0588e6

**Comment by Ek-Videogames** [comment] 2021-12-16 03:30
> @Ek-Videogames The clients send the information about turning on the fabricator as a network event, and if the server failed to receive it, it should lead to a desync kick. The same goes for notifying the clients about someone else turning on the fabricator. And what do you mean by the "trigger to finish fabrication"?

Well there seems to be unsolved bugs pertaining to the communication of fabrication state information from the server to client then, because there is still semi-regular occurrences of some players' fabricator GUI showing as not fabricating anything - while another person's client shows that it is fabricating - all the while neither of them getting kicked `( if that's the intended behavior in this situation, although that seems like a poor mode of failure )`. 

I sort of covered most of these scenarios in a 'blanket' ticket back around last winter, if the team thinks its warranted `(and it would appear some of these bugs still are happening)` I could start opening some follow-up tickets documenting if and when fabricator desync issues occur again in the current builds.

By `"Trigger to finish fabrication"` I just refer to the fabricator state in-netcode missing whatever-communication to tell the client that "the item has finished crafting", IE - stopping the fabrication timer, consuming the ingredients, and outputting finished product.

**Comment by Regalis11** [comment] 2022-01-04 13:25
We did some more changes to fabricator syncing in https://github.com/Regalis11/Barotrauma-development/commit/52c4d259d6738148e3fcff8bb8b1b4cea155c237 and https://github.com/Regalis11/Barotrauma-development/commit/b42349d7505fe7055cafa3d1460c9b988edd2c37, let's see if those get rid of the issue

**Closed** 2022-02-09 22:15 UTC
Labels: Bug, Needs testing, Code, Networking
