### ISSUE TITLE
[Feature Rq] [Modding] Make AfflictionName Conditionals Moddable

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2372] opened 2020-02-28 16:29 UTC
![2020-02-28-102720_734x99_scrot](https://user-images.githubusercontent.com/47284081/75566219-ef5e4580-5a14-11ea-81b2-1c653dc85725.png)
Currently Conditionals testing afflictions are hardcoded. It would be nice if they were instead based on what afflictions were actually loaded in from Afflictions.xml. This would allow very creative use of hidden "affliction flags" on players that could give them hidden afflictions that would let other statuseffects know what has happened to them and react accordingly.

**Comment by Regalis11** [comment] 2020-03-04 13:11
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3e1a06e2daf4111009ab12a8add4b709fb199ee1

**Comment by itchyOwl** [comment] 2020-03-05 11:32
There was no reason to use a hardcoded collection of strings there. Nobody knows/recalls why it was done in the first place. The code now uses AfflictionPrefabs, so it should be fully moddable.

**Comment by Regalis11** [comment] 2020-04-02 11:22
Tested by making the diving suit only provide oxygen when you've got the paralysis affliction
```
<StatusEffect type="OnWearing" target="Contained,Character" OxygenAvailable="1000.0" Condition="-0.3" comparison="Or">
   <Conditional paralysis="gt 1" />
   <RequiredItem items="oxygentank" type="Contained" />
</StatusEffect>
```

Seems to be working as intended, closing.

**Closed by Regalis11** 2020-04-02 11:22 UTC
Labels: Code, Feature request
