### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Gunnar1337** [Regalis11/Barotrauma#9582] opened 2022-07-16 21:55 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Last 3 days game crashes every time!

### Reproduction steps

Happens every time in submarine editor ,didn't test it in singleplayer or multiplayer.
I did try removing all mods , reinstall game , removed old files from installation folder , updated all drivers ,verifying integrity of game files game crashes all the time can't even put 2 components in sub editor without crash.
Sometimes i get crash report , but most times it just crash without any report.

### Bug prevalence

Happens every time I play

### Version

Other

### -

v0.18.15.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 7/16/2022 11:41:54 PM)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


A3E1BD9914304826B1774DE813786E1D


Game version 0.18.15.0 (ReleaseWindows, branch release, revision a7b22109e9)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla, Automatic Reactor Controller, (CRO)Ageis9
Level seed: no level loaded
Loaded submarine: (CRO)Ageis9 (0FC664304B4B184A92BB1814E775D55C)
Selected screen: Barotrauma.SubEditorScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.19043.0 64 bit
    GPU name: NVIDIA GeForce GTX 1060 6GB
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: Type provided must be an Enum. (Parameter 'enumType') (System.ArgumentException)
Target site: System.RuntimeType ValidateRuntimeType(System.Type)
Stack trace: 
   at System.Enum.ValidateRuntimeType(Type enumType)
   at System.Enum.TryParse(Type enumType, String value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at Barotrauma.SerializableEntityEditor.MultiSetProperties(SerializableProperty property, Object parentObject, Object value) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Serialization\SerializableEntityEditor.cs:line 1451
   at Barotrauma.SerializableEntityEditor.SetPropertyValue(SerializableProperty property, Object entity, Object value) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Serialization\SerializableEntityEditor.cs:line 1351
   at Barotrauma.SerializableEntityEditor.<>c__DisplayClass29_0.<CreateStringField>g__OnApply|3(GUITextBox textBox) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Serialization\SerializableEntityEditor.cs:line 707
   at Barotrauma.SerializableEntityEditor.<>c__DisplayClass29_0.<CreateStringField>b__1(GUITextBox textBox, Keys keys) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Serialization\SerializableEntityEditor.cs:line 691
   at Barotrauma.GUITextBox.Deselect() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBox.cs:line 385
   at Barotrauma.GUITextBox.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBox.cs:line 477
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1229
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 898
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59


Last debug messages:
[7/16/2022 11:41:00 PM] Attempting to open ALC device "OpenAL Soft on Speakers (Realtek(R) Audio)"
[7/16/2022 11:40:58 PM] Logged in as Py20m4n (SteamID STEAM_1:1:56889542)
```

**Comment by Regalis11** [comment] 2022-07-17 08:31
Duplicate of https://github.com/Regalis11/Barotrauma/issues/9512

**Closed by Regalis11** 2022-07-17 08:31 UTC
