### ISSUE TITLE
Pulse laser's bugs caused by non-standart sub building

### ISSUE THREAD

**Issue by Lepestochek** [Regalis11/Barotrauma#11176] opened 2023-02-07 09:22 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While I was testing my new sub in the sub editor, one of the shots from pulse laser appeared in mid-water and struck the sub from the inside, whilst also piercing through most of it, as showcased here:

https://user-images.githubusercontent.com/105408302/217200909-28ac6faf-efae-44e6-a2d3-8598845aeb49.mp4

The angle is somewhere between -165 and -160 it seems.
I did a quick test with a quickstart command and it looks like it works normally outside of editor? I have no idea, but still gonna submit the report, just in case.
The sub in question:
[pulse laser issue 07.02.zip](https://github.com/Regalis11/Barotrauma/files/10673371/pulse.laser.issue.07.02.zip)

### Reproduction steps

1. Mount a pulse laser on a sub (use provided)
2. Shoot roughly where the fin plate A is
3. Laser is misaligned and mirrored

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Lepestochek** [comment] 2023-02-07 09:27
Related to this #9557 and/or this #7326 ?

**Comment by Lepestochek** [comment] 2023-02-08 10:23
The original issue seems like not replicatable in single and multiplayer, however i've found some new ones, hope you dont mind me pouring them on in here

**Comment by Lepestochek** [comment] 2023-02-08 10:25
Submarine bow D, despite it's max health being set to 0 and is full of gaps, occasionally blocks shots from the pulse laser

https://user-images.githubusercontent.com/105408302/217503241-6607e0d7-7c3a-41c1-a8dd-57f243e8234b.mp4

While submarine bow D is not a decorative element and is actually a wall, it does behave buggy so i brought this out

**Comment by Lepestochek** [comment] 2023-02-08 10:30
When a pulse laser cannon fires it's shot inside another cannon's collision box(?) the shot is misaligned (this time tested on a hosted server), there is no invisible shuttles in the visible docking ports and this behaviour in not observed with a singular cannon on this exact ship

https://user-images.githubusercontent.com/105408302/217504647-6d56b025-ec9e-46a0-9af2-7b6853512b4f.mp4

**Comment by JeroonBosch** [comment] 2023-12-01 09:05
Also happened on the Orca 2 (empty hardpoint at the front was swapped for Pulse Laser). Only happened when firing in a very specific angle, hard to reproduce consistently.

**Comment by Jasontti** [comment] 2024-01-04 14:58
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4725/commits/c47d0e9e9126dca80030002d565e692055b27895

Tested with sub provided and with same steps
Orca 2 and and some other loose tests

No issues found
Closing ticket

**Closed by Jasontti** 2024-01-04 14:58 UTC
Labels: Bug, Code, Testing branch

**Comment by maschine34675** [comment] 2024-04-02 14:26
This still happens, i added a Pulse Laser to the prebuild Herja and at a specific angle the shots come out backwards, hitting crew & sub.
![20240402161913_2](https://github.com/FakeFishGames/Barotrauma/assets/163792852/8f6092fc-53dc-4962-a901-23870c0e0993)
![20240402161938_1](https://github.com/FakeFishGames/Barotrauma/assets/163792852/7483a1a3-c23a-439a-b869-bd63d7f3018f)

**Comment by Regalis11** [comment] 2024-04-02 15:08
I'm afraid the fix hasn't made it to the public version yet (it wasn't merged until January, and there have been no updates since then). Should be coming in the next update though! Sorry for the inconvenience.
