### ISSUE TITLE
Deep Diver Incorrect Crush Depth

### ISSUE THREAD

**Issue by Samsonite105** [Regalis11/Barotrauma#4968] opened 2021-02-03 08:38 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In a deep diver submarine, the submarine does not actually receive the 20% additional crush depth from the deep diver class. Even though the map says the submarine has the additional 20% crush depth from the deep diver class (giving us 4200 meters until crush depth), we experience the effects of crush depths as if we were a normal submarine at 3500 meters. 

**Steps To Reproduce**
Any deep diver class submarine below 3500 meters without any upgrades will begin to experience the effects of crush depth.

**Version**
Barotrauma v0.11.0.10 (ReleaseWindows, branch release, revision dc7157029e)

Disclaimer: We have edited the variables of mobs so that they are more aggressive towards the submarine. While I do not believe this affects this particular bug, I do find it worth mentioning.

**Additional information**
Example Video: https://www.youtube.com/watch?v=-pCIV0e7v74

**Comment by Xeavas** [comment] 2021-02-04 07:48
Refer to : #4910

**Comment by Regalis11** [comment] 2021-02-04 07:58
Duplicate of https://github.com/Regalis11/Barotrauma/issues/4910

**Closed by Regalis11** 2021-02-04 07:58 UTC
