### ISSUE TITLE
Bots - Can't fix "Shell behind Shell" leaks

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3697] opened 2020-09-03 12:23 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots can't fix leaks caused by shells behind another shell (especially tail fin and nose structures) from the outside of the submarine. They might be able to fix it when they're standing right next to the leak. Usually if they're in another hull, they don't know how to get to the leak.

Example Orca:
![Capture2](https://user-images.githubusercontent.com/5086682/92114343-a8377f80-edbe-11ea-978b-1c9e619d0928.PNG)

Example [Kail Terra](https://steamcommunity.com/sharedfiles/filedetails/?id=2197390262):
![Capture](https://user-images.githubusercontent.com/5086682/92114390-c0a79a00-edbe-11ea-8581-ff52c1863ff3.PNG)

**Version**
~0.10.501

**Comment by itchyOwl** [comment] 2020-09-03 16:41
Ok, now I can reproduce it: really need to go outside and carefully break only that part or the bot can reach the lower parts and coincidentally fix the outer shell too. The issue seems to be related to path finding. Thanks for the help!

**Comment by itchyOwl** [comment] 2020-09-03 18:18
Fixed in Regalis11/Barotrauma-development@3e6cb75

The cause for the issue was the visibility check in the node filter of the path finder. For the fix leak objective, we don't want to do that, since we can target leaks through walls.
![nopath.jpg](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/19378466-b9ea-4746-83c8-788d244598b4)

**Comment by Kaillera** [comment] 2020-09-05 20:35
Working in 0.10.502

**Comment by Rokvach** [comment] 2020-09-05 20:49
Closing.

**Closed by Rokvach** 2020-09-05 20:49 UTC
Labels: Bug, Code
