### ISSUE TITLE
Some bugs prevented me from connecting to the server to play

### ISSUE THREAD

**Issue by C02Kirin** [Regalis11/Barotrauma#6858] opened 2021-10-08 15:22 UTC
- [ √] I have searched the issue tracker to check if the issue has already been reported.
The same unresolved bug ： [there](https://github.com/Regalis11/Barotrauma/issues/4091)

**Description**
Today, I suddenly found that I couldn't join someone else's server, even though their pings were low. Every time I join the server, I always exit after a second or two and present the error report shown in the following image. I can even hear in-game voice before exiting. How can I solve this problem? I really want to play with my friends

**Version**
game : 0.14.9.0
Windows 10 
AMD Ryzen 7 4800HS with Radeon Graphics            2.90 GHz

**Additional information**
![image](https://user-images.githubusercontent.com/92170050/136581753-9ba51e30-7434-4457-a65a-d8ddebcbbcff.png)
![@K TS9O5~OXK~3`55KGN5OH](https://user-images.githubusercontent.com/92170050/136581832-a27b7d43-318b-4335-b064-acd1d8414f3c.png)

![) 0Y0KPB@G46Z}0EKI7SBE9](https://user-images.githubusercontent.com/92170050/136581843-b4c2e036-a470-44cf-a4e9-bee35935ad31.png)

**Comment by C02Kirin** [comment] 2021-10-08 16:09
Error while reading a message from server. {Source array was not long enough. Check the source index, length, and the array's lower bounds. (Parameter 'sourceArray')}
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length)
   at Barotrauma.Networking.ReadOnlyMessage..ctor(Byte[] inBuf, Boolean isCompressed, Int32 startPos, Int32 inLength, NetworkConnection sender) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\Primitives\Message\Message.cs:line 635
   at Barotrauma.Networking.SteamP2PClientPeer.OnP2PData(UInt64 steamId, Byte[] data, Int32 dataLength) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2PClientPeer.cs:line 153
   at Barotrauma.Networking.SteamP2PClientPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2PClientPeer.cs:line 197
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 632

**Comment by Regalis11** [comment] 2021-10-12 07:22
Thank you for the report! Unfortunately we still haven't been able to diagnose this issue, but I added some more info to the error message in https://github.com/Regalis11/Barotrauma-development/commit/501920495517ab48a4da37904b986e792b44c75f (commit in our private repo) to hopefully help us get to the bottom of this. I'll close the ticket since it seems to be a duplicate of https://github.com/Regalis11/Barotrauma/issues/4091

**Closed by Regalis11** 2021-10-12 07:22 UTC
Labels: Bug, Code, Networking
