### ISSUE TITLE
Pathfinding bug with bots on Azimuth Submarine if Custom Hatch Needs Repair (Also should custom hatch need repair? This seems like a bug within a bug)

### ISSUE THREAD

**Issue by gerakis** [Regalis11/Barotrauma#7547] opened 2021-11-29 20:55 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If the "custom hatch" needs repair on the Azimuth submarine then any bot with "Repair Damaged Systems" command will freak out trying to pathfind to it. They keep spamming the airlock over and over. I think this is because the custom hatch cannot be reached from the ground on this sub. This is wrench repair type damage, not plasma cutter damage just to be clear.

I'm not even sure how the hatch got damaged in the first place, so that might also be a bug. I haven't seen that happen on any other sub. I didn't do any weird wiring to it other than connect a few wires to "state out."

**Steps To Reproduce**
Somehow damage your custom hatch (I don't know how to do this, power surges or something?) and set at least one bot to the command "repair damaged systems." The bots will flip out and start spamming the airlock. After a while they give up, and then 5 minutes later they start trying again.

**Version**
v0.15.13.0 Windows 10 x64

**Additional information**
Here is a video to show what the bots do.
(https://youtu.be/O8QzdilQw_s)

**Comment by Regalis11** [comment] 2021-11-30 12:16
This is a known issue: since the bots can't repair while climbing a ladder, they'll fail to repair these hatches. Closing as a duplicate of https://github.com/Regalis11/Barotrauma/issues/5587

**Closed by Regalis11** 2021-11-30 12:16 UTC
