### ISSUE TITLE
[0.9.5.1] Pumps rapidly change target level in non-singular ballasts.

### ISSUE THREAD

**Issue by HalfdeadKiller** [Regalis11/Barotrauma#1906] opened 2019-11-24 18:30 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Pumps that are placed in a ballast, that is not one single hull rapdily change between -100 and 100, and other values in between.

**Steps To Reproduce**
Have a ballast with two hulls connected via a gap, with one being higher up than the other. It's easier shown than explained.
Isolated testing hasn't yielded many good results.

**Version**
Windows Barotrauma 0.9.5.1

**Additional information**
Included is a .zip of two sub files. One is isolation testing, which hasn't yielded the oddity one can see in the Cyclops MK-II - 4.0.

This is a link to a gif I made of the pump operation on the Cyclops MK-II - 4.0.
https://i.imgur.com/NI5drvQ.mp4

This particular issue may not be a bug, and may be a failure of proper sub building. Though I don't remember this being an issue on previous versions of the game.

**Comment by ChikoEduardo** [comment] 2019-11-24 18:57
Are you, by any chance, using relays for the signals and/or to power the pumps? This is happening in one of my subs after the latest update.

I mentioned it in another issue but I didn't go into detail: https://github.com/Regalis11/Barotrauma/issues/1904

**Comment by Regalis11** [comment] 2019-11-25 08:54
This seems to be caused by the changes in the power distribution logic. The large pumps are so fast that they can make the water level fluctuate very rapidly in small ballasts like this, but in this case the relays make the problem much more pronounced. Due to an issue in the power logic, the excess power the relay is receiving causes the pump to operate faster: for example, if the pump is drawing 100 kW from the relay and the relay is receiving 1000 kW from the grid, the pump will operate 10x faster.

**Comment by Regalis11** [comment] 2019-11-25 08:58
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/17e75f92172eba5071679f087df5e4a3dbd0d21b (private repo)

**Comment by danielasteljoki** [comment] 2019-12-10 09:07
Tested with different ballast and relay setups. Seems to be working.

**Comment by Rokvach** [comment] 2019-12-10 10:09
Moving to Done.

**Comment by HalfdeadKiller** [comment] 2019-12-11 00:37
@ChikoEduardo - I wasn't notified of all these updates. I do indeed have a relay powering the pumps, as I didn't have the space to fit another junction box.

**Closed** 2019-12-12 09:20 UTC
Labels: Bug, Code
