### ISSUE TITLE
Players Controlling Husks Cannot Operate or Break Doors and Hatches

### ISSUE THREAD

**Issue by Jlobblet** [Regalis11/Barotrauma#4498] opened 2020-12-12 00:50 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Husks controlled by a player cannot open doors. Can't occur in vanilla, but a decent number of servers like to allow dead players to control monsters.

**Steps To Reproduce**
1. Load a sub in the sub editor. Enter test mode.
2. `disablecrewai` to stop them fighting you.
3. `spawncharacter husk cursor`
4. `control husk`
5. Try to open a door or hatch as the husk.
6. Try to break a door open as the husk.

**Version**
Unstable v0.1200.0.0

**Comment by Kaillera** [comment] 2020-12-12 01:42
I thought husks can only operate wreck doors?

**Comment by Jlobblet** [comment] 2020-12-12 16:14
I just checked to be certain - husks can normal open doors and hatches on a submarine when controlled by the AI.

**Comment by itchyOwl** [comment] 2020-12-14 08:35
Not a bug.

**Comment by itchyOwl** [comment] 2020-12-14 11:41
Changed the behavior in Regalis11/Barotrauma-development@c257caf, which also addresses this issue.

**Comment by Rokvach** [comment] 2020-12-15 07:48
Tested, working correctly. Closing.

**Closed by Rokvach** 2020-12-15 07:48 UTC
Labels: Code
