### ISSUE TITLE
Outpost Manager was inaccessible, possibly due to an error in the outpost generation logic

### ISSUE THREAD

**Issue by Agent-Delta** [Regalis11/Barotrauma#11315] opened 2023-02-22 19:22 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

2 days ago (Feb. 20) I was playing with two friends on a private multiplayer campaign server (hosted on my end). We docked at an outpost (fairly certain it was the Research Center shown in picture) towards the end of the Europan Ridge. 

![20230222121224_1](https://user-images.githubusercontent.com/126107030/220734816-27b7f69f-8696-4149-9ac5-df18c433006b.jpg)

At first, nothing seemed wrong, but it quickly became apparent that the Outpost Manager was inaccessible due to a station generation error.

![20230220214305_1](https://user-images.githubusercontent.com/126107030/220731392-07d4d9cc-8eab-44bb-9e49-1c4d46e67460.jpg)
![20230220214321_1](https://user-images.githubusercontent.com/126107030/220731436-3a1b0009-a47d-425a-9e9e-f7949649b852.jpg)

The 3 white dots marking the Outpost Manager/mission-giver can be seen in both pictures, unreachable. The NPC Security Officer in the second picture was constantly trying to climb the ladder, but to no avail due to the strange ceiling. We ended up stopping for the night and returning the next day to see that the station had not fixed itself. However, using a Handheld Status Monitor, I was able to get a better picture of what had gone wrong.

![20230221205344_1](https://user-images.githubusercontent.com/126107030/220732836-2d7848f6-9dff-4763-949b-c9fa67fe44a9.jpg)

It seems the area where the HR and Outpost Managers usually spawn had been generated clipping into the ladder meant to go up to the medical/research area. As a result, the Outpost Manager and entire medical sector were both completely cut off from the rest of the station. Not exactly game-breaking but very frustrating as we could neither get new missions nor heal or buy medical supplies.

This is the only time we (my friends and I) have ever encountered a station bug like this.

NOTE: the only mod on the server is [this one](https://steamcommunity.com/sharedfiles/filedetails/?id=2910964157), for craftable/placeable ammunition shelves. Very unlikely to be interfering here but noted for transparency's sake.

### Reproduction steps

No idea how to reproduce this beyond provoking generation of a similar station (end of Europan Ridge, Research Center, etc).

### Bug prevalence

Just once

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Agent-Delta** [comment] 2023-02-22 19:32
Sorry if report is over-long

**Comment by itchyOwl** [comment] 2023-02-23 08:25
Hello, thanks for your report. It would help if we could test the save file you had. Could you post it here as zipped? Otherwise it can be very difficult to reproduce the issue and debug it.

**Comment by Regalis11** [comment] 2023-02-23 08:33
Potentially related to or a duplicate of https://github.com/Regalis11/Barotrauma/issues/10187

**Comment by Agent-Delta** [comment] 2023-02-23 16:48
[Outpost Generation Error Saves.zip](https://github.com/Regalis11/Barotrauma/files/10816071/Outpost.Generation.Error.Saves.zip)

Here are the save files. As explained in the original post, the problem area should be the research station shown in the first picture.
In this save, our crew is currently at the military outpost just below it.

**Comment by Regalis11** [comment] 2023-02-24 14:27
Thank you! I gave this a test in the latest dev build and the outpost seems to generate normally now, so I think this has been fixed by some of the fixes we've done to the outpost generator when implementing faction-specific outposts.

**Closed by Regalis11** 2023-02-24 14:28 UTC
Labels: Bug, Needs testing, Code
