### ISSUE TITLE
Keybinds don't seem to work on Arch Linux

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10614] opened 2022-11-28 22:32 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I want to preface this by saying I'm reporting this on behalf of another user (LatKmamak#5053 in the discord). My understanding of the issue is not 100% clear, so please excuse any problems that may arise from that. 

How I understand this user's issue is as follows:

You click on a key you want to change. Let's use the d key for moving right as an example.

You want to change d to y for some reason. You click d and then press y, changing the key bind. When you go to press Apply, nothing changes. 

They then went on to explain that "In the window (not os windows) I can see that I can to change on left or right mouse. BUT It isnot work too", which I interpret as meaning the key binds can be changed to the left or right mouse buttons but no other keyboard button.

I've included some quotes from this user below to describe the issue in their own words in the event that my explanation is insufficient. 

"When I enter the game, keyboard control is lost except for mouse control (I can watch, use objects, but I can't run). The back button doesn't help."
"I did some digging in the files and found config_player.xml which is responsible for the settings, but the reset button doesn't work anyway."
"The buttons responsible for movement are none and I cant to change there"
"the button "reset" button settings does not work (that is, I cannot assign the "d" button to go to the right, even if I write it in config_player.xml manually)"

"Sometimes, with the help of a reboot, I manage to regain control of the character, but this is an exception"

### Bug prevalence

Happens regularly

### Version

0.19.14.0

### -

Arch Linux

### Which operating system did you encounter this bug on?

Linux

**Comment by mygamingaccount** [comment] 2022-11-29 16:33
Great, second hand bug reports.

How would I go about reproducing this? I don't have any issues on Debian.

**Comment by Rehexr** [comment] 2022-12-01 17:41
I mean steam deck is arch linux based... works fine enough there, though that might just be nullified because the inputs are given via steam, not directly.

**Comment by Wheatley1001** [comment] 2022-12-01 23:32
> Great, second hand bug reports.
> 
> How would I go about reproducing this? I don't have any issues on Debian.

Absolutely no idea, Linux is the one OS I don't have. I heard someone say they had the same issue on MacOS but I was unable to reproduce it. It could be a UI issue or a bug with the code but I was struggling to understand the user.

**Comment by Regalis11** [comment] 2022-12-04 10:32
One of our programmers is actually developing the game on Arch Linux, so this doesn't seem like something that always happens on Arch. So we need more information to be able to reproduce this, closing.

**Closed by Regalis11** 2022-12-04 10:32 UTC
Labels: Bug, Need more info, Code
