### ISSUE TITLE
Kastrull misplaced inferior Hull

### ISSUE THREAD

**Issue by LuCKySoZ** [Regalis11/Barotrauma#3921] opened 2020-09-27 05:12 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Entire lowest deck does not take in water if shell is broken, hull is not properly touching the shell. We discovered when we were playing and 2 of us simply "dropped" into the water from a hole that was made.

**Steps To Reproduce**
Simply plasma cut any part of the inferior shell.

**Version**
Version 0.10.5.1 / Windows 10

**Additional information**
Gunnery/Armory and Reactor/battery/supercap seems to be working, though the shell part under Armory looks misaligned by 1 pixel row

**Comment by Regalis11** [comment] 2020-09-28 07:44
Seems to have been caused by the same bug as https://github.com/Regalis11/Barotrauma/issues/3885, fixed in https://github.com/Regalis11/Barotrauma-development/commit/bcb8f9c5a5d4f30f1d34a831cd284230111ff8f0

**Comment by Rokvach** [comment] 2020-09-28 08:46
No issues, closing.

**Closed by Rokvach** 2020-09-28 08:46 UTC
Labels: Bug, Code
