### ISSUE TITLE
Light texture not rotating with light emmiting components.

### ISSUE THREAD

**Issue by NiebieskieFrugo** [Regalis11/Barotrauma#3634] opened 2020-08-25 17:38 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Light textures that are applied to lamps and lights don't rotate with them, creating misaligned textures.

![unknown](https://user-images.githubusercontent.com/48123851/91208145-0bb01600-e70a-11ea-9793-9d287230ffc8.png)

**Steps To Reproduce**
Rotate any light in the sub editor, turn it on and look at it with lighting enabled.

**Version**
v0.10.4.0 (revision 20132d25fb) (Windows)

**Comment by hubismal** [comment] 2020-08-26 00:34
This is fixed in the next update, which you can preview by downloading the unstable branch.

**Comment by Regalis11** [comment] 2020-08-26 06:54
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3344

**Closed by Regalis11** 2020-08-26 06:54 UTC
