### ISSUE TITLE
Bots don't repair anything

### ISSUE THREAD

**Issue by pRobannoR** [Regalis11/Barotrauma#4224] opened 2020-11-05 19:12 UTC
**Description**
If you give orders in the warehouse / home, no bot repairs anything on the submarine

**Steps To Reproduce**
Just play normal campaigns, choose a mission to complete and then order the bots to repair something in camp

**Version**
v. 0.10.6.2.

**Comment by SoobGorl** [comment] 2020-11-05 19:45
The bots assume that you want to fix something in the station, which I think is possible in events or emergency situations..? But, a workaround for this is ordering them to follow you, and have them given the order when all bots are inside the submarine.

**Comment by pRobannoR** [comment] 2020-11-05 20:22
> 
> 
> The bots assume that you want to fix something in the station, which I think is possible in events or emergency situations..? But, a workaround for this is ordering them to follow you, and have them given the order when all bots are inside the submarine.

They also don't fix anything when you are docked and in the submarine!

**Comment by SoobGorl** [comment] 2020-11-06 13:18
> > They also don't fix anything when you are docked and in the submarine!
Are the bots _also_ in the submarine with you? 👀 It should work then..? I haven't seen any issues with this, but I do have some instances where bots just.. stop, so, I can see how some bugs can arise :)

**Comment by itchyOwl** [comment] 2020-11-06 17:07
Do you mean that the bots and you are inside an outpost and you expect them to fix things inside the main submarine, which is docked to the outpost? If that's the case, it's intentional: the bots are not allowed to go to repair things in a different sub than they are currently in. So if you take the bots with you from the main submarine to another submarine, they should only fix things inside that other submarine they are currently in.

If, however, the bots don't fix things when they are inside the main submarine, that's a bug. Would be easier to fix that if you could provide a screenshot in the "debugai" mode.

**Comment by Neko-LoverDisc** [comment] 2020-11-07 18:50
I've had this issue too. I've had bots in the main sub with me while docked, right next to me looking at the smoking engine and them telling me that there's nothing to repair

**Comment by Regalis11** [comment] 2020-11-09 18:50
This could be a bug, but another potential explanation could be that the devices appeared broken due to the psychosis affliction, even though they weren't actually broken.

**Comment by Neko-LoverDisc** [comment] 2020-11-09 18:52
I switched to a bot, equipped med scanner on the bot and scanned the captain. no psychosis

**Comment by itchyOwl** [comment] 2020-11-10 07:27
It would really help if someone could provide the steps to reproduce this issue.

**Comment by Neko-LoverDisc** [comment] 2020-11-11 14:28
I tested it a couple times, and I can't figure out exactly what causes it. Sometimes the AI will repair as normal (Like you said, calling them into the sub beforehand), and sometimes they'll be right next to the smoking engine saying there's nothing to repair. I don't know what else is influencing it, because it seems to happen completely at random regardless of anything I've noticed

**Comment by Regalis11** [comment] 2021-01-08 08:30
No known steps to repro, I wonder if we should close this?

**Comment by itchyOwl** [comment] 2021-01-08 13:19
Yep

**Closed** 2021-01-13 13:20 UTC
Labels: Bug, Code, Need more info, Needs testing
