### ISSUE TITLE
Please optimize the submarine downloading logic in multiplayer gaming

### ISSUE THREAD

**Issue by erertertet** [Regalis11/Barotrauma#9470] opened 2022-06-27 10:27 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Technically, this is not a bug, but it is really annoying me and my friends during multiplayer gaming. Basically, as far as I know, barotrauma would download every single submarine enabled on server client, including the ship that is customized on the server client. Whether the .sub file is changed or not, barotrauma would redownload the file. My suggestion is that if Barotrauma could check the hash sum before downloading .sub file. It would really save a lot of time given that the Steam P2P connection is not that stable and waiting for downloading the same file is really annoying.

### Reproduction steps

1. start multiplayer server
2. enable custom submarine
3. let client join the server
4. start champaign
5. wait for downloading submarine
6. stop the server
7. repeat step 1-6, the downloading would start again

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-06-27 10:46
Duplicate of https://github.com/Regalis11/Barotrauma/issues/9174

**Closed by Regalis11** 2022-06-27 10:46 UTC
