### ISSUE TITLE
Cannot pick up Logbook in a wreck mission. 

### ISSUE THREAD

**Issue by Mefavevo** [Regalis11/Barotrauma#12467] opened 2023-08-04 12:05 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

This error pops up whenever I take up any wreck mission and cannot pick up nor relocate the wreck Logbook from the container it spawns in. 

Could not find a spawpoint for SpawnAction (spawn location: BeaconStation (tag:beacon_bandti),skipping.

### Reproduction steps

1. Start Singleplayer Campaign 
2. Play "Salvaging a wreck" mission.
3. Try to retrieve logbook but can't. (Game does not crash in any way just that you cannot pick up the logbook.).

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Mefavevo** [comment] 2023-08-06 15:04
Update: Bug happens on random wrecks as well.

**Comment by AdamH-Daedalic** [comment] 2023-08-10 11:56
Tested on v1.0.21.0

I was unable to reproduce this issue, player was able to pick up and collect the logbook every time they were on a wreck salvage mission, no sign of any error in the console. Tested this with both naturally spawned mission and debug launched ones too. I'll keep checking for this whenever I come across these missions with other testing in the future

**Comment by itchyOwl** [comment] 2023-08-11 06:58
Moved to QA investigates for finding the repro steps (as it seems it doesn't always happen).

**Comment by AdamH-Daedalic** [comment] 2023-08-21 14:19
Tested on v1.0.21.0 again with the mods listed above installed.

Still unable to reproduce it even with the mods. I was able to pick up every log book in each of the wrecks, vanilla or modded versions. 

Setting back to More Info in the hopes something else can be figured out.

**Comment by Regalis11** [comment] 2023-12-17 13:56
No known steps to repro, closing

**Closed by Regalis11** 2023-12-17 13:56 UTC
Labels: Bug, Need more info, Code
