### ISSUE TITLE
0.1000.0.0 (Unstable): Outposts Can Generate Walls on Top of Hatches.

### ISSUE THREAD

**Issue by Jlobblet** [Regalis11/Barotrauma#2945] opened 2020-05-31 22:26 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Outposts are capable of either generating a horizontal wall on top of a hatch, or fail to remove the horizontal wall in that location. See attached:
![image](https://user-images.githubusercontent.com/37539527/83363991-b1671980-a395-11ea-9586-91590d354451.png)
Level seed: `Brunhes`. Savefile: [Save 11.zip](https://github.com/Regalis11/Barotrauma/files/4708587/Save.11.zip)

**Steps To Reproduce**
Appears to be random generation - sorry :(.

**Version**
Version 0.1000.0.0 (Unstable).
Windows 10 version 1903.

**Comment by Regalis11** [comment] 2020-06-01 07:21
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ed0aa6b40bba7c9db054690878b1e5c174235b39

**Comment by Rokvach** [comment] 2020-06-01 12:54
Tested, wasn't able to reproduce the issue by using the save, also went through a lot of different seeds on the outpost test mode and didn't see any similar issues. Closing.

**Comment by Regalis11** [comment] 2020-06-04 13:52
Seems to still happen sometimes: probably because the hallway overlap check is done just by casting a ray between the outposts. Need to take the size of the hallway into account as well.
![image (3)](https://user-images.githubusercontent.com/14351070/83765239-9b05da00-a683-11ea-8b77-2ffc29d882db.png)

[Save 294.zip](https://github.com/Regalis11/Barotrauma/files/4730457/Save.294.zip)

**Comment by Rokvach** [comment] 2020-06-13 10:00
Haven't noticed any weirdness for a while now, also none spotted on Unstable either, closing.

**Closed by Rokvach** 2020-06-13 10:00 UTC
Labels: Bug, Code
