### ISSUE TITLE
Inconsistent Coilgun ammo consumption

### ISSUE THREAD

**Issue by Confodore** [Regalis11/Barotrauma#1873] opened 2019-11-10 20:36 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

### **Description**
The standard "Coilgun ammo box" appears to be designed to provide **200** shots. When actually firing the coilgun, it seems to only shoot **67** bullets per box. Further testing shows that turrets with their **reload** parameter set to **0.0** yield **100** shoots per ammo box.

Since a ammo box is designed to reduce its condition by **0.5** on every use, the strange number of **67** shots seems to be the result of the box's condition being reduced **3 times**, while only shooting **one shell**. 
`100/(3 * 0.5) = 66.66    =>  rounded up to 67`

Turrets with a **reload** parameter of **0.0** trigger the onUse only **2 times** per shot. The result is **100** bullets per box
`100/(2 * 0.5) = 100`
 
### **Steps To Reproduce**

- Find any coilgun and count the number of shots fired per ammo box. Only 67 shots will be fired

- In the sub editor, give a turret a reload speed of 0.0 and repeat the test. Only 100 shots per box. (very hard to manually shoot/count)

OR:
I have made a custom **sub** and **mod** to test different configurations and to avoid tedious counting. The mod merely adds 2 new coilgun boxes with different _onUse_ condition status (-0.0 and -3.4) 
The mod also includes a wall with its health set to 1000. That way, every shot represents 1% structure damage when viewed thru the **debugdraw** command.

Test sub + mod:
[CoilgunTestSub.zip](https://github.com/Regalis11/Barotrauma/files/3828896/CoilgunTestSub.zip)

The sub uses a **oscillator component** to trigger the coilguns and has a **counter** to count the number of **sent** trigger signals. The number of **actual** shots fired can be seen by the structure's damage percentage.

![coilgun-sub-test](https://user-images.githubusercontent.com/57303910/68549480-97191e80-03f8-11ea-94f5-a2a6237a6980.jpg)

Another strange thing is that turrets with a reload of 0.0 (colored purple in the test sub), will shoot on **every trigger** signal, while turrets with a reload of more than 0.0 will shoot on **every second** trigger signal! This may explain why one is depleting ammo 2x faster, and the other 3x faster.

### **Version**
Observed in 0.9.4.0

### **Additional information**
On my test submarine, i have encountered instances of bullets passing the wall, and hitting the one behind it. Using the biggest ruin wall may prevent that, due to it being wider. Maybe it's wide enough to catch the bullet before it phases in-between frames? This may or may not be related to issue  #1796

**Comment by Regalis11** [comment] 2019-11-11 12:44
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/faccd8b37cd35729d1c65767160113fd442da8c9 (private repo)

**Comment by danielasteljoki** [comment] 2019-11-13 09:35
Tested with provided test sub and a vanilla sub. Coilgun with 0.3 reload gets 200 shots out of a single ammo box but a gun with 0.0 reload time only fired 191 times.

**Comment by Regalis11** [comment] 2019-11-25 14:29
Cannot reproduce in vanilla v0.9.5.1 any longer, moving back to review

**Comment by Rokvach** [comment] 2019-12-02 11:21
@danielasteljoki Do you have some time to take another look at this?

**Comment by danielasteljoki** [comment] 2019-12-02 12:34
Couldn't reproduce either, seems to be working correctly.

**Comment by Rokvach** [comment] 2019-12-02 12:59
Moving this to Done.

**Closed** 2019-12-12 09:19 UTC
Labels: Bug, Code, Needs testing
