### ISSUE TITLE
Alt-F4 while game is loading is considered a "crash"

### ISSUE THREAD

**Issue by GoodDays13** [Regalis11/Barotrauma#13330] opened 2024-01-21 02:42 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When I press alt f4 as the game is loading, it considers it a crash and also disables mods.
I am using Linux (Manjaro, KDE) on Wayland currently using the Steam native runtime.
![Screenshot_20240120_211713](https://github.com/Regalis11/Barotrauma/assets/42877449/89fb3d94-c1be-4a21-9651-cef1e73c6447)

Expected behavior: The game cancels loading cleanly and doesn't generate a crash report or turn off mods.
Interestingly, I have user statistics enabled, so maybe the setting hadn't been loaded by the game yet.

### Reproduction steps

1. Start the game
2. Press Alt-F4 before the loading gets to 100%
3. See the crash report message

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Happens outside single player or multiplayer game modes (e.g. game launches on startup, something broken in the main menu)

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Linux

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 01/20/2024 21:14:10)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

To prevent further startup errors, installed mods will be disabled the next time you launch the game.

4A84181A63989F8FC38A4421F7B9A6FC

Game version 1.2.8.0 (ReleaseLinux, branch release/winter-update-hotfix-2, revision b9f79cb182)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla (F748F32)
Level seed: no level loaded
Loaded submarine: None
Selected screen: None

System info:
    Operating system: Unix 6.6.10.1 64 bit
    Graphics device not set

Exception: Failed to set listener position: Invalid operation (System.Exception)
Target site: Void set_ListenerPosition(Microsoft.Xna.Framework.Vector3)
Stack trace: 
   at Barotrauma.Sounds.SoundManager.set_ListenerPosition(Vector3 value) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sounds\SoundManager.cs:line 56
   at Barotrauma.Camera.UpdateTransform(Boolean interpolate, Boolean updateListener) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Camera.cs:line 230
   at Barotrauma.Camera..ctor() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Camera.cs:line 151
   at Barotrauma.GameScreen..ctor(GraphicsDevice graphics) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\GameScreen.cs:line 32
   at Barotrauma.GameMain.Load() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 503
   at System.Threading.Thread.StartCallback()

Last debug messages:
[01/20/2024 21:14:10] WARNING: Error in GameAnalyticsManager.GetConsent: Could not get a Steam authentication ticket (not connected to Steam).
[01/20/2024 21:14:06] Exiting...
[01/20/2024 21:13:58] Attempting to open ALC device "Arctis Nova 7 Analog Stereo"
[01/20/2024 21:13:56] Logged in as Good_Days13 (SteamID STEAM_1:0:125606498)
```

```shell
Barotrauma Client crash report (generated on 01/20/2024 21:16:59)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

To prevent further startup errors, installed mods will be disabled the next time you launch the game.

4A84181A63989F8FC38A4421F7B9A6FC

Game version 1.2.8.0 (ReleaseLinux, branch release/winter-update-hotfix-2, revision b9f79cb182)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla (F748F32)
Level seed: no level loaded
Loaded submarine: None
Selected screen: None

System info:
    Operating system: Unix 6.6.10.1 64 bit
    Graphics device not set

Exception: Error while loading the core content package "Vanilla": Loading the preview image of the submarine "Azimuth" failed. The file may be corrupted. {PreviewImage texture returned null}
   at Barotrauma.SubmarineInfo.InitProjectSpecific() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\SubmarineInfo.cs:line 22 (System.Exception)
Target site: Void Load()
Stack trace: 
   at Barotrauma.GameMain.Load() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 476
   at System.Threading.Thread.StartCallback()

Last debug messages:
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] WARNING: The language English is no longer available. Switching to English...
[01/20/2024 21:16:59] Loading the preview image of the submarine "Azimuth" failed. The file may be corrupted. {PreviewImage texture returned null}
   at Barotrauma.SubmarineInfo.InitProjectSpecific() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\SubmarineInfo.cs:line 22
[01/20/2024 21:16:57] Exiting...
[01/20/2024 21:16:54] Attempting to open ALC device "Arctis Nova 7 Analog Stereo"
[01/20/2024 21:16:52] Logged in as Good_Days13 (SteamID STEAM_1:0:125606498)
```

**Comment by Regalis11** [comment] 2024-01-22 06:36
Duplicate of https://github.com/Regalis11/Barotrauma/issues/12564

**Closed by Regalis11** 2024-01-22 06:36 UTC
