### ISSUE TITLE
Game Mechanics - Character loses control over movement when traversing dynamic gaps on collision corners

### ISSUE THREAD

**Issue by Oukido** [Regalis11/Barotrauma#8060] opened 2022-01-19 09:52 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I have noticed this happening very often lately mostly on dynamic gaps of objects with collision like sub-shells and ruin-walls.
It happened basicly every single time I cut open a wall above alien_maintenancepassages2 with the swarmfeeders, but this is just an example of something I always do the same way and is not limited only to that room. (probably because of the tight holes you cut there)
It also happens alot with pirate vessels and wrecks. And once it happened at a ruins corner above an entrance that was not damaged at all.

I have also noticed strange movement bugs when skimming the shell surface of my sub but this one was very inconsistently, and happened only occasionly.

**Steps To Reproduce**
spawn a pirate dugong
lock movement to eliminate velocity influences
cut open the shell
try to swim in from outside traversing the corner of the shell
character loses movement control (WASD) (but mouse still works, like aiming around)
wait until character falls out of the dynamic gap and regains control

**Version**
![grafik](https://user-images.githubusercontent.com/83960267/150104659-df0f7dc2-7d56-4e51-a859-4012d2aa9178.png)

**Additional information**
tested and confirmed it in the medic department, besides the armory. I also unwired the duct to eliminate water streams

**Comment by Regalis11** [comment] 2022-01-19 10:11
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7176

**Closed by Regalis11** 2022-01-19 10:11 UTC
