### ISSUE TITLE
Text box for Sonar Label/Sonar Beacon clears itself on multiplayer.

### ISSUE THREAD

**Issue by Crazyjr20** [Regalis11/Barotrauma#12371] opened 2023-07-17 22:59 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Sonar beacon and in extension Sonar Label text boxes clear themselves after being typed into. This only appears to occur on multiplayer and as far as I remember only happened post 1.0. I first discovered this issue with a modded item using a sonar label and text box but then checked to see if it occurs on vanilla and it does still occur.
If the Sonar Beacon is active when you type, it will still display the label on the navigation terminal/handheld sonar correctly but will still clear the text box.
![sp](https://github.com/Regalis11/Barotrauma/assets/18705965/b74c263f-0f1d-4f64-895d-9c153793a3c9) In Singleplayer it works fine and displays the text in the text box without clearing it.
![mp](https://github.com/Regalis11/Barotrauma/assets/18705965/1660a56c-3f43-4e19-9040-a10b232aaec2) In Multiplayer the text is cleared.

https://github.com/Regalis11/Barotrauma/assets/18705965/567d8e2f-6975-4701-946b-87506f1e6547

### Reproduction steps

1. Start a multiplayer game, mission or campaign both have same result.
2. Acquire a Sonar Beacon.
3. Type into the text box.
4. Text will be cleared.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-07-18 16:20
Duplicate of https://github.com/Regalis11/Barotrauma/issues/12012 (the fix for that one is not included in the public version yet, just in the unstable branch)

**Closed by Regalis11** 2023-07-18 16:20 UTC
