### ISSUE TITLE
Barotrauma Status Monitor Visual Bug

### ISSUE THREAD

**Issue by Jewvile** [Regalis11/Barotrauma#13237] opened 2023-12-27 18:45 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Within Making a ship in the sub editor, I had a "Shell A 0 Degrees" Rotated at a angle of -4.4 degrees, for a certain area of my submarine, whilst this works fine for hull integrity, when looking within the status monitor, the hull snaps back to its original 0 degree position leaving a irregular looking ship on the status monitor

### Reproduction steps

1. Load / Create a Ship with a "Shell A 0 Degrees" rotated at some angle using the submarine editor
2 Place a status monitor with some power source on the submarine
3. Load into the submarine and open the status monitor
4. Look at the hull

Images Attached as a Example

![image_2023-12-27_184432276](https://github.com/Regalis11/Barotrauma/assets/155013724/131a1ded-ae7e-40a0-a0fd-75399efb952f)
![image_2023-12-27_184459001](https://github.com/Regalis11/Barotrauma/assets/155013724/5d6eb2b8-9518-46e2-b737-b746a5ffb2c8)

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Single player

### Version

v1.2.7.0 (Winter Update hotfix)

### Which operating system did you encounter this bug on?

Windows

**Comment by jcx1991911** [comment] 2023-12-27 21:05
it has been fixed in unstable version 1.2.8.0, just be patient for the next update

**Comment by Regalis11** [comment] 2023-12-30 14:39
Duplicate of https://github.com/Regalis11/Barotrauma/issues/13065

**Closed by Regalis11** 2023-12-30 14:39 UTC
