### ISSUE TITLE
Getting a gpu related error code when launching up my campaign world. 

### ISSUE THREAD

**Issue by Lunat1cX** [Regalis11/Barotrauma#10946] opened 2023-01-15 22:57 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

First time this happened, I was searching a wreck and it crashed while I was inside it. Second time, I just loaded into the same campaign save from the outpost and once I moved around, it crashed.
![image](https://user-images.githubusercontent.com/85198609/212571584-dda9f461-22eb-4012-8b75-301868492615.png)

### Bug prevalence

Just once

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
"This is a common DirectX error that can be related to various different issues, such as outdated drivers, RAM problems or an overclocked or otherwise overstressed GPU. There are several potential ways to fix the issue: ensuring your graphics drivers and DirectX installation are up-to-date, disabling overclocking and adjusting various GPU-specific settings. You may also be able to find potential solutions to the problem by using the error code DeviceHung (HRESULT = 0x887A0006) and your GPU manufacturer as search terms."

"Exception: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.
 (SharpDX.SharpDXException)
Device removed reason: DeviceHung (HRESULT = 0x887A0006)
Target site: Void PlatformPresent()
Stack trace: 
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 1017
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[01/15/2023 17:49:55] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
[01/15/2023 17:49:42] Generating an outpost for the end of the level... (Location: Thaw Habitation Outpost, level type: LocationConnection)
[01/15/2023 17:49:41] Generating an outpost for the start of the level... (Location: Brunhes Fortification, level type: LocationConnection)
[01/15/2023 17:49:40] Level identifier: ridgebasic
[01/15/2023 17:48:12] Attempting to open ALC device "OpenAL Soft on Speakers (Realtek(R) Audio)"
[01/15/2023 17:48:07] Logged in as †Lunat1c† (SteamID STEAM_1:1:462096233)"
```

**Comment by Regalis11** [comment] 2023-01-16 08:14
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10540

**Closed by Regalis11** 2023-01-16 08:14 UTC
