### ISSUE TITLE
Strange power behavior when using junctions in combination with relays

### ISSUE THREAD

**Issue by Plythios** [Regalis11/Barotrauma#5018] opened 2021-02-09 12:47 UTC
I changed many of my junctions into relays to reduce complexity and difficulty, but ever since then I've encountered odd problems with my power refusing to go out.

For instance, while running on batteries, they fall below a stored threshold, and then seem to begin generating power out of nowhere, regardless of whether the reactor is on or not. This didn't happen before I made this change, and I only switched out junctions for relays.

The lights make a flickering noise, despite them not going dim at all. My low Power stored circuit also trips, indicating the batteries near empty; Steering and other things are offline, but a lot of things are still powered? What's going on!

I've read a couple of other bug reports, apparently this has been an issue for a while?

Here's a video of this happening.
https://drive.google.com/file/d/1jmo0-RKN3mNHDrgHSELfZ0NUqx5MTsHs/view?usp=sharing

And here's some screenshots of my circuits and setup.

https://i.imgur.com/DpuGY6e.jpg
Junction box settings
https://i.imgur.com/h9QMhYe.jpg
Battery settings
https://i.imgur.com/6OTUvmg.jpg
The relay settings
https://i.imgur.com/cTdDGYa.jpg
Proof my lights do in fact drain power.

If you need any more info, let me know. Even happy to provide my sub save file if it suits.

EDIT: Reducing the recharge rate while in testing mode does let the batteries run out, but how are they pulling power out of the aether in the first place?

**Comment by Regalis11** [comment] 2021-02-10 06:57
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3238

**Closed by Regalis11** 2021-02-10 06:57 UTC
