### ISSUE TITLE
Removing an empty diving suit doesn't sync and causes random suffocation.

### ISSUE THREAD

**Issue by CommanderMark** [Regalis11/Barotrauma#1261] opened 2019-03-10 21:56 UTC
Seems like if I:
- Equip a diving suit...
- Remove its oxygen tank...
- And then take off the diving suit itself...

It'll sometimes not register that the suit is off and I inadvertently die due to oxygen deprivation.

Sometimes it eventually re-syncs and other times I seem to start suffocating out of nowhere causing death.

**Comment by VelonacepsCalyxEggs** [comment] 2019-03-10 21:57
hmm gonna test

**Comment by VelonacepsCalyxEggs** [comment] 2019-03-10 22:01
it didn't work for me. maybe there was no oxygen in the room?

**Comment by CommanderMark** [comment] 2019-03-10 22:14
It doesn't seem like that was the case since everyone around me wasn't suffocating without a mask/suit.

With that said I just tried running it in a local match and couldn't reproduce the issue. Might only happen when there's already an excessive amount of desync? I'll try testing this when I get into another proper match at a later date.

Could also be related [to this](https://github.com/Regalis11/Barotrauma/issues/1226#issuecomment-470957675).

**Comment by VelonacepsCalyxEggs** [comment] 2019-03-10 22:16
Oh, okay.

**Comment by Regalis11** [comment] 2019-03-12 15:56
This was caused by clients not creating a network event when they drop an item by dragging it out of a slot. Will be fixed in the next patch!

**Comment by Regalis11** [comment] 2019-03-18 22:00
Fixed in v0.8.9.6

**Closed by Regalis11** 2019-03-18 22:00 UTC
Labels: Networking-related, bug
