### ISSUE TITLE
Constant Crash

### ISSUE THREAD

**Issue by Anon-Linear** [Regalis11/Barotrauma#2685] opened 2020-04-24 07:43 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The game will suddenly crash mid-tutorial. There is nothing particular which triggers it, sort of just happening. 

**Steps To Reproduce**
I am not quite sure what triggers the crash, but when I try to run the game after about 5 minutes the game will crash. 

**Version**
 0.9.9.0 (ReleaseWindows, branch release, revision 0534150c8)

**Additional information**
I hope these can help
[crashreport (5).log](https://github.com/Regalis11/Barotrauma/files/4527409/crashreport.5.log)
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/4527410/crashreport.log)
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/4527411/crashreport.2.log)
[crashreport (3).log](https://github.com/Regalis11/Barotrauma/files/4527412/crashreport.3.log)
[crashreport (4).log](https://github.com/Regalis11/Barotrauma/files/4527413/crashreport.4.log)

**Comment by Regalis11** [comment] 2020-04-24 08:29
If the hardware info in the report is correct, you're using an integrated graphics card which probably doesn't meet the minimum requirements to run the game (I suspect it doesn't have enough video memory). We will be doing some memory optimization in future patches, but I'm afraid we cannot promise you will be able to play the game with such a low-end GPU.

This also seems to be a duplicate of #1833

**Closed by Regalis11** 2020-04-24 08:29 UTC
Labels: Bug, Code, Crash

**Comment by Anon-Linear** [comment] 2020-04-24 16:56
thank you
