### ISSUE TITLE
Error while reading a message from the server. Read error: Void ReadIngameUpdate

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#4927] opened 2021-01-28 20:43 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Crash to main menu during a mission.

**Steps To Reproduce**
-

**Version**
v0.11.0.10 Windows 20H2

**Additional information**
[crashreport_object.log](https://github.com/Regalis11/Barotrauma/files/5889871/crashreport_object.log)

**Comment by Regalis11** [comment] 2021-01-29 07:53
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3927. We've implemented a fix for the issue and currently testing it, there's a chance this gets fixed in the next update.

**Closed by Regalis11** 2021-01-29 07:53 UTC
