### ISSUE TITLE
Arc emitter consumes battery charge the same as with fulgurium cells

### ISSUE THREAD

**Issue by PokkeTigrex** [Regalis11/Barotrauma#10360] opened 2022-11-12 21:22 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Arc emitter both consumes 25% charge of both the battery cell and the fulgurium battery cell every shot.
![image](https://user-images.githubusercontent.com/85914375/201495033-897e7cd5-1c4e-4b31-85c8-9b68602beee4.png)

### Reproduction steps

Shoot the arc emitter with battery cell and fulgurium cell. Both will have 4 uses before becoming empty.

### Bug prevalence

Happens every time I play

### Version

0.20.5.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-11-13 11:47
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8ee6de17f56363d27ed46a8b51e2e7924d711d50

**Comment by Kaktar-1** [comment] 2022-11-14 12:54
> Fixed in [Regalis11/Barotrauma-development@8ee6de1](https://github.com/Regalis11/Barotrauma-development/commit/8ee6de17f56363d27ed46a8b51e2e7924d711d50)

The Scrap Cannon has the same problem too.

**Comment by Lithosagym** [comment] 2022-11-15 03:47
Tested, the Fulgurium Cells properly have double the charge than Battery Cells when used in the Arc Emitter. The Scrap Cannon, Stun Baton, Flashlight, Underwater Scooter, and Harpoon Coil-Rifle were also tested with Fulgurium Battery Cells, and all function as intended. Issue is fixed.

**Closed** 2022-11-16 18:05 UTC
Labels: Bug, Design, Unstable
