### ISSUE TITLE
Mission equality check failure after afk disconnect

### ISSUE THREAD

**Issue by Buschwichtel** [Regalis11/Barotrauma#10268] opened 2022-11-06 16:32 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While docked, I took a break and got kicked for afk. Upon returning, I was unable to rejoin the game from the lobby - the mission equality check failed. My teammates had accepted 3 new missions in the meantime.

Them embarking on a new mission allowed me to connect.

(#2723 looks similar, but unrelated)

### Reproduction steps

1. Dock after completing a mission
2. Get kicked for being afk while no missions are accepted
3. Host accepts new missions
4. Rejoin lobby
5. Attempt to spectate
=> Exception

### Bug prevalence

Happens every now and then

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
There was an error initializing the round. {Mission equality check failed. Mission count doesn't match the server (server: 0, client: 3)}
   at Barotrauma.Networking.GameClient.ReadStartGameFinalize(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 872
   at Barotrauma.Networking.GameClient.StartGame(IReadMessage inc)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 1547
```

**Comment by Regalis11** [comment] 2022-11-23 17:46
Closing as a duplicate of https://github.com/Regalis11/Barotrauma/issues/10497 (even though that ticket is more recent, there's more info in that one)

**Closed by Regalis11** 2022-11-23 17:46 UTC
