### ISSUE TITLE
Cannot start a campaign in multiplayer mode

### ISSUE THREAD

**Issue by igormusinov** [Regalis11/Barotrauma#1576] opened 2019-06-09 23:06 UTC
OS: WIndows Server 2016

![image](https://user-images.githubusercontent.com/11311889/59165442-4ab57400-8b24-11e9-9d2a-7e0e4170564a.png)

![image](https://user-images.githubusercontent.com/11311889/59165450-602a9e00-8b24-11e9-981a-aae769b2e90b.png)

**Comment by Regalis11** [comment] 2019-06-10 08:52
Duplicate of #1564

**Closed by Regalis11** 2019-06-10 08:52 UTC
