### ISSUE TITLE
UI Not Scaling Properly For Wiring

### ISSUE THREAD

**Issue by brand175** [Regalis11/Barotrauma#12221] opened 2023-06-24 04:24 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![Barotrauma Screenshot 2023 06 23 - 21 04 34 58](https://github.com/Regalis11/Barotrauma/assets/20964160/9aaf7795-4195-4a68-aa90-4e64628d3c24)

### Reproduction steps

1. Set resolution to 2160p

2. Use battery with screwdriver

### Bug prevalence

Happens every time I play

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
I don't know if https://github.com/Regalis11/Barotrauma/issues/12164
fixed this as 1080p doesn't have this issue
```

**Comment by Regalis11** [comment] 2023-06-24 09:35
Duplicate of https://github.com/Regalis11/Barotrauma/issues/12180

**Closed by Regalis11** 2023-06-24 09:35 UTC
