### ISSUE TITLE
[Factions] Clown Event is global

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11047] opened 2023-01-28 02:17 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### Key Information
Game mode: Campaign
Game type: Multiplayer
Campaign save version: Started in 100.13.0.0, issue occurred in version 100.15.0.0
Server type: Steam P2P

### Issue Report
Whilst inside the outpost, I was given text from one of the clown events. I hadn't interacted with any clown or NPC and the text was advancing on its own. I also asked others in the session if they received the text and had mixed results. Many players who did not get the text were not inside the outpost, so perhaps this is related? It could be a networking error though.

![image](https://user-images.githubusercontent.com/105495756/215236906-ef2dcd9d-616c-4618-a273-cba19dcd45db.png)

### Bug prevalence

Just once

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-01-28 12:03
Thank you for the report!

I gave this a quick test with 2 clients in the server and by directly triggering the pathofthebikehorn2 event with console commands, and couldn't reproduce the issue. So it seems it requires some more specific circumstances to occur. Need to do some more debugging.

**Comment by Regalis11** [comment] 2023-02-16 08:58
No known steps to repro, closing

**Closed by Regalis11** 2023-02-16 08:58 UTC
Labels: Bug, Need more info, Code
