### ISSUE TITLE
A player respawns, then server says missing something, causing all players kicked (MISSING ENTITY)

### ISSUE THREAD

**Issue by esirprus** [Regalis11/Barotrauma#8879] opened 2022-04-21 09:57 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
when a player respawn, then the server said missing something, cause everyone in server be kicked.
Player's name is retouched.

[2022/4/21 下午5:17:15]
  Respawning everyone in main sub.
[2022/4/21 下午5:17:15]
  Respawning playerB (58.212.74.21) as 安全官
[2022/4/21 下午5:17:15]
  playerA has reported an error: Received an update for an entity that doesn't exist (event id 17610, entity id 7957).
[2022/4/21 下午5:17:15]
  playerA已离开服务器 理由: Kicked
理由: Received an update for an entity that doesn't exist (event id 17610, entity id 7957).
[2022/4/21 下午5:17:15]
  playerA已经被踢出服务器 理由: Received an update for an entity that doesn't exist (event id 17610, entity id 7957).
[2022/4/21 下午5:17:15]
  playerB has reported an error: Received an update for an entity that doesn't exist (event id 17610, entity id 7957).
[2022/4/21 下午5:17:15]
  playerB已离开服务器 理由: Kicked
理由: Received an update for an entity that doesn't exist (event id 17610, entity id 7957).
[2022/4/21 下午5:17:15]
  playerB已经被踢出服务器 理由: Received an update for an entity that doesn't exist (event id 17610, entity id 7957).
[2022/4/21 下午5:17:15]
 playerC has reported an error: Received an update for an entity that doesn't exist (event id 17610, entity id 7957).
[2022/4/21 下午5:17:15]
 playerC已离开服务器 理由: Kicked
理由: Received an update for an entity that doesn't exist (event id 17610, entity id 7957).
[2022/4/21 下午5:17:15]
  playerC已经被踢出服务器 理由: Received an update for an entity that doesn't exist (event id 17610, entity id 7957).
[2022/4/21 下午5:17:15]
 playerD has reported an error: Received an update for an entity that doesn't exist (event id 17610, entity id 7957).
[2022/4/21 下午5:17:15]
 playerD已离开服务器 理由: Kicked
理由: Received an update for an entity that doesn't exist (event id 17610, entity id 7957).
[2022/4/21 下午5:17:15]
  playerD已经被踢出服务器 理由: Received an update for an entity that doesn't exist (event id 17610, entity id 7957).
[2022/4/21 下午5:17:15]
  playerE has reported an error: Received an update for an entity that doesn't exist (event id 17610, entity id 7957).
[2022/4/21 下午5:17:15]
  playerE已离开服务器 理由: Kicked
理由: Received an update for an entity that doesn't exist (event id 17610, entity id 7957).
[2022/4/21 下午5:17:15]
  playerE已经被踢出服务器 理由: Received an update for an entity that doesn't exist (event id 17610, entity id 7957).
[2022/4/21 下午5:17:15]
  playerF has reported an error: Received an update for an entity that doesn't exist (event id 17610, entity id 7957).
[2022/4/21 下午5:17:15]
  playerF已离开服务器 理由: Kicked
理由: Received an update for an entity that doesn't exist (event id 17610, entity id 7957).
[2022/4/21 下午5:17:15]
  playerF已经被踢出服务器 理由: Received an update for an entity that doesn't exist (event id 17610, entity id 7957).
[2022/4/21 下午5:17:17]
  Ending round (no living players left)
[2022/4/21 下午5:17:17]
  Ending the round...

**Steps To Reproduce**
Someone die and respawn, but MANY dedicatedserver report this.
**Version**
client v0.17.12.0 windows
server v0.17.12.0 linux

**Comment by Regalis11** [comment] 2022-04-21 09:59
Duplicate of https://github.com/Regalis11/Barotrauma/issues/6265

**Comment by esirprus** [comment] 2022-04-22 09:51
@Regalis11 hello, i think my issue shouldn't be closed, because it is unlike the previous issue, this happened on "respawn" EVERYTIME(at least on my server), "respawn" includes the respawning of their characters when a player joins the game, as well as the respawning of dead characters. The server will then throw any kind of error,like missing item, missing sub, missing character,  and i think #8900 and #8895 is same as my issue. you can see #8900 Immediately following the act of respawn, everyone was kicked off the server. If you need more error reports, I can provide them to you here.

**Comment by Regalis11** [comment] 2022-04-22 12:55
Thank you for the extra info. I do still suspect these are caused by the same underlying issue, but we could keep this open for some more time while we investigate it further. Something that might help us get to the bottom of this, is if you could find files called "event_error_log_client_[your name]_[date].log" and "event_error_log_server_[your name]_[date].log" in the ServerLogs folder and send them to us here. Those should include some more details on what exactly was missing and why. Thanks and sorry for the inconvenience!

**Comment by esirprus** [comment] 2022-04-22 13:35
thank you, I have packed the log files but unfortunately they seem to be out of order
[errors.zip](https://github.com/Regalis11/Barotrauma/files/8541430/errors.zip)
。

**Comment by Regalis11** [comment] 2022-04-25 09:38
Most likely caused by the same underlying issue as https://github.com/regalis11/barotrauma/issues/8963, should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/961ff37d1ece7a82f32c63536a4a2e5db2524db3

**Comment by Rokvach** [comment] 2022-04-25 14:56
Tested both in steamp2p and dedicated server and I wasn't able to reproduce this issue. Seems to be working correctly. Leaving the ticket open so we can see if there's any sightings once this ticket hits Unstable.

**Comment by Rokvach** [comment] 2022-04-27 07:59
This hasn't come up during community testing, working correctly. Closing.

**Closed by Rokvach** 2022-04-27 07:59 UTC
Labels: Bug, Code, Networking, High prio, Unstable
