### ISSUE TITLE
[0.17.12.0] Multiplayer - Missing Entity error kicks all players when a character that died and has respawned on the respawn shuttle

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#8900] opened 2022-04-22 03:11 UTC
Entity error kicks all players in multiplayer when a character that died and has respawned on the respawn shuttle. This causes the round to end instantaneously.

Also, the character data saves what has happened in that round when it ends due to that bug, instead of reverting to the state it was at the beginning of the round.

This has happened many times in Rokvach Official Test Server back in Unstable as well.

**Comment by Regalis11** [comment] 2022-04-22 07:26
I'm afraid I could not reproduce this. 
![image](https://user-images.githubusercontent.com/14351070/164627234-b97663fc-daf9-4fb1-b7fa-883a5c6c4de7.png)

Do you recall what error message was when this happened?

**Comment by Kaillera** [comment] 2022-04-22 07:58
Missing Entity

**Comment by Kaillera** [comment] 2022-04-22 08:01
[Multiplayer.zip](https://github.com/Regalis11/Barotrauma/files/8538393/Multiplayer.zip)
[ServerLogs.zip](https://github.com/Regalis11/Barotrauma/files/8538394/ServerLogs.zip)

**Comment by Regalis11** [comment] 2022-04-22 12:56
Duplicate of https://github.com/Regalis11/Barotrauma/issues/8879

**Closed by Regalis11** 2022-04-22 12:56 UTC
Labels: Bug, Code, Networking
