### ISSUE TITLE
In exosuit the empty oxygen tank warning bell rings, even when the tank is full

### ISSUE THREAD

**Issue by pavel4win** [Regalis11/Barotrauma#11244] opened 2023-02-14 10:00 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While in the exosuit, if I do not take out the empty oxygen tank from the exosuit inventory to the character's inventory, but shift the empty tank from tank intended place and replace it with a full tank. 
Then oxygen is supplied normally, but the warning bell of an empty tank continues to ring until I remove the empty tank from the exosuit's inventory to the character's inventory.

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-02-14 10:02
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11076

**Closed by Regalis11** 2023-02-14 10:02 UTC
