### ISSUE TITLE
NPCs in the city can't get through the trapdoor

### ISSUE THREAD

**Issue by CurvasProximos** [Regalis11/Barotrauma#11877] opened 2023-04-21 01:11 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The NPCs got stuck on the stairs because of which there was no one to refuel the reactor at the outpost and everyone almost died from lack of oxygen
the screenshot shows the same staircase with new victims
if you close the hatch, they fall and return to the true path
![image](https://user-images.githubusercontent.com/101333283/233516913-17a290f4-431f-414a-b5a6-b79de1bd1228.png)

### Reproduction steps

1) sailed to the city
2) I ran for a while (5 minutes)
3) I went to see why the reactor at the outpost turned off
4) saw a lot of people stuck on the same ladder

### Bug prevalence

Happens regularly

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-04-21 06:59
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10426

**Closed by Regalis11** 2023-04-21 06:59 UTC

**Comment by CurvasProximos** [comment] 2023-04-21 07:44
Sorry
