### ISSUE TITLE
[Unstable] Loading an Event Prefab in the Event Editor crashes the game

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#8576] opened 2022-03-22 22:22 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Loading any Event Prefab into the Event Editor crashed the game to desktop.

**Steps To Reproduce**
1. Open the event editor using the `editevents` command
2. Load an event prefab

**Version**
Windows Unstable v0.17.3.0

**Additional information**
[crashreport (5).log](https://github.com/Regalis11/Barotrauma/files/8328242/crashreport.5.log)

**Comment by ekqvist** [comment] 2022-04-06 10:28
Should be fixed in Regalis11/Barotrauma-development@697e4c5. Crash was caused by `Convert.ChangeType` not being able to change strings into Identifiers.

**Comment by Rokvach** [comment] 2022-04-07 09:14
Tested, working correctly. Closing.

**Closed by Rokvach** 2022-04-07 09:14 UTC
Labels: Bug, Code, Crash
