### ISSUE TITLE
Blocked vertical hatch in an outpost.

### ISSUE THREAD

**Issue by Mikolaj1900G** [Regalis11/Barotrauma#3867] opened 2020-09-21 09:29 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
While screwing around in singleplayer and playing with console commands one of the vertical hatches became completely impassable by either me or NPC's. You cannot use the ladder nor drop down while standing to go through it.

**Steps To Reproduce**
Not sure exactly what caused this but I:
-took control of an outpost NPC
-spawned a bunch of mudraptors
-spawned some explosions around the hatch in question
-the hatch while still being able to be closed or opened with a button becomes impassable in either state

**Version**
v0.10.5.1 (Windows)

**Additional information**
-
![hatch](https://user-images.githubusercontent.com/57800630/93751509-7e26ef80-fbfd-11ea-9a82-e057c0f4f072.png)

**Comment by Kaillera** [comment] 2020-09-21 11:27
This is usually an uncommon occurrence when hatches receives damage either from monster or explosions. Usually I find this happening on shuttles that was damaged when it was sent out and redocked to main submarines, and for some reason you can't enter the drone without ragdolling.

I had another case where I was bringing up lithium up to the outpost's airlock and one of my friend accidently opened the airlock doors and caused the lithium to explode as I was in there, and it prevented all the players from getting back into the main sub.

**Comment by Kaillera** [comment] 2020-09-21 11:37
Actually I was able to reproduce it and I think I have a theory on it. It's probably overlapping gaps caused by damaged shells that was damaged enough to create one.

https://youtu.be/_rzGzaq5VS4

**Comment by Regalis11** [comment] 2020-10-26 15:23
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/041990bfbd753185256e103122443c9fd5862746.

@Kaillera your theory was right: it was called by the gap's "collision blockers": invisible colliders that prevent the character from passing through the gap when there's something solid behind it. The blockers were so large that they sometimes prevented passing through nearby gaps as well, which is what happened here.

**Comment by Rokvach** [comment] 2020-10-27 10:18
Tested, working correctly. Closing.

**Closed by Rokvach** 2020-10-27 10:18 UTC
Labels: Bug, Code
