### ISSUE TITLE
[Bug?] [Feature Request?] Previously Uncovered Map Disappears

### ISSUE THREAD

**Issue by quexten** [Regalis11/Barotrauma#4059] opened 2020-10-11 18:01 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
As a preface this might actually be a Feature request if this is currently an intended game design mechanic.
When uncovering more squares on the map, and then going back, the visibility of these uncovered squares disappears. It would be nice to be able to travel back and still see the previously discovered area for possible long term destinations.

**Steps To Reproduce**
Travel forwards in the campaign to the second visible square, then travel backwards. The visibility will disappear.

**Version**
Operating systems are Linux (Client) and Windows (Host), the version is v0.10.5.1 (9e259b2148)

**Comment by Regalis11** [comment] 2020-10-12 08:19
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1ca0e38ad681c4507a42324348165d806adee612

**Comment by Rokvach** [comment] 2020-10-15 08:35
I wasn't able to reproduce the issue, seems to be working correctly. Closing.

**Closed by Rokvach** 2020-10-15 08:35 UTC
Labels: Bug, Code
