### ISSUE TITLE
[Unstable] Spineling genes not shooting spikes in hulls

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#12368] opened 2023-07-17 14:42 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Using spineling genes, attacking spawns spineling spikes outside of hulls, but not inside

### Reproduction steps

1. Equip spineling genes
2. Shoot spikes inside (no projectile)
3. Shoot spikes outside (it works)

### Bug prevalence

Happens every time I play

### Version

Unstable (v1.1.3.0)

**Comment by Jasontti** [comment] 2023-07-18 10:47
Happens in traitor-update branch also.

**Comment by Regalis11** [comment] 2023-07-18 13:41
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3079d1cdc836b2b1782593159baaf0f4fa48d312. Note for testing: the issue seemed to affect all projectiles spawned via status effects inside the sub. I'm not sure if there are others in the vanilla game besides the spineling spikes though.

The issue was caused by the changes in https://github.com/Regalis11/Barotrauma-development/commit/83625df6f095e1988ef1d6a9e60f68cf89fdd10c, so we should verify that issue hasn't reappeared.

**Comment by Rokvach** [comment] 2023-08-14 10:29
Tested, working correctly. can be merged and closed.

**Closed by Rokvach** 2023-08-14 10:29 UTC
Labels: Bug, Code
