### ISSUE TITLE
Error saving submarine after editing the save file manually

### ISSUE THREAD

**Issue by Rialelul** [Regalis11/Barotrauma#12821] opened 2023-10-15 15:20 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I played with mods and everything was fine, but at a certain point I wanted to edit the submarine without losing progress. I used the save decompressor. Pulled my submarine out of the save, created a mod from it, edited it in the editor's submenu, saved it, added the edited submarine back to the save, compiled the save, and the changes were successful, and I can even play, progress between check points is saved, but autosave stopped working, due to than it is impossible to save the progression after exiting the game. 

### Reproduction steps

1. Start a compaign
2. Play 1 mission
3. Quit the game
4. Decompress your save file
5. Make a mod with your submarine from the save
6. Do any changes in submarine with submarine editor and save it like a new submarine
7. Drop a new submarine in your decompress save folder
8. Make changes in gamesession.xml > line 2 > submarine="New submarine"; into <ownedsubmarines> write <sub name="new submarine" />
9. Compress save file
10. Lauch the save and dock/undock (go on mission/ go on outpost)
11. Get the error in console
12. Go in main menu
13. Launch the save and make sure nothing is saved

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Error saving submarine {Object reference not set to an instance of an object.}
   at Barotrauma.SubmarineInfo.SaveAs(String filePath, MemoryStream previewImage) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\SubmarineInfo.cs:line 574
   at Barotrauma.SaveUtil.SaveGame(String filePath) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SaveUtil.cs:line 106
```

**Comment by Regalis11** [comment] 2023-10-15 15:37
Thank you for the report! I suspect something may have gone wrong when editing the submarine or the save file, and the submarine element has gotten corrupted somehow. Even though we don't normally provide support for issues caused by 3rd-party software or things like manual save file editing, if you could send us the save file, I can take a look and see if I can find the issue.

Thanks and sorry for the inconvenience!

**Comment by Rialelul** [comment] 2023-10-15 22:14
> Thank you for the report! I suspect something may have gone wrong when editing the submarine or the save file, and the submarine element has gotten corrupted somehow. Even though we don't normally provide support for issues caused by 3rd-party software or things like manual save file editing, if you could send us the save file, I can take a look and see if I can find the issue.
> 
> Thanks and sorry for the inconvenience!

[try2023.zip](https://github.com/Regalis11/Barotrauma/files/12910794/try2023.zip)
[try2023backup.zip](https://github.com/Regalis11/Barotrauma/files/12910795/try2023backup.zip)

Thanks so much for answer! I really like the idea of gradually improving a particular submarine in minor aspects, so I resorted to such things. If you find a problem and give an answer on how to avoid similar problems in the future, it will be amazing! Ty!

**Comment by Rialelul** [comment] 2023-10-16 19:20
> > Thank you for the report! I suspect something may have gone wrong when editing the submarine or the save file, and the submarine element has gotten corrupted somehow. Even though we don't normally provide support for issues caused by 3rd-party software or things like manual save file editing, if you could send us the save file, I can take a look and see if I can find the issue.
> > Thanks and sorry for the inconvenience!
> 
> [try2023.zip](https://github.com/Regalis11/Barotrauma/files/12910794/try2023.zip) [try2023backup.zip](https://github.com/Regalis11/Barotrauma/files/12910795/try2023backup.zip)
> 
> Thanks so much for answer! I really like the idea of gradually improving a particular submarine in minor aspects, so I resorted to such things. If you find a problem and give an answer on how to avoid similar problems in the future, it will be amazing! Ty!

[Herja New.zip](https://github.com/Regalis11/Barotrauma/files/12920943/Herja.New.zip)

Hey, I don't know if this can help or not, but I added a mod that I created

**Comment by Regalis11** [comment] 2023-10-17 07:11
Thank you! I think I found the issue: it seems that the R-29 submarine file has been renamed as "R-291212.sub" for some reason. The game fails to load it properly, which leads to an error when trying to save the campaign again. Decompressing the save, renaming the file as "R-29.sub" and compressing it again should fix the issue.

**Comment by Regalis11** [comment] 2023-10-17 07:12
I implemented a sort of fix/workaround to this in https://github.com/Regalis11/Barotrauma-development/commit/9cd787b36d9ee4e60f594f2f778d28674573faa9 (commit in our private repo). Now the missing submarine file will cause a console error when loading the save, and the missing sub will just be removed from the save, so this kind of error shouldn't make the save unusable any longer.

**Comment by Rialelul** [comment] 2023-10-17 13:11
> I implemented a sort of fix/workaround to this in https://github.com/Regalis11/Barotrauma-development/commit/9cd787b36d9ee4e60f594f2f778d28674573faa9 (commit in our private repo). Now the missing submarine file will cause a console error when loading the save, and the missing sub will just be removed from the save, so this kind of error shouldn't make the save unusable any longer.

Hello! OMG! It really works! I have no idea how this file was renamed, given that I was interested in a completely different submarine. Extremely grateful for the help! <3

**Comment by Regalis11** [comment] 2023-10-17 13:29
I'm glad I was able to help. :) Thanks for taking the time to close this ticket, but we'll keep it open until we've tested that fix/workaround internally and verified it's working as intended.

**Comment by Rokvach** [comment] 2023-11-24 08:34
Tested with the provided save, the sub file is correctly removed from the save at the start and wont throw a second error when transitioning to a new level, also made sure that saving works correctly. Working correctly, can be merged and closed. 

The new error message which I received when loading up the save. 
Could not find the submarine "R-29" (C:\Users\username\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\temp\R-29.sub)! The save file may be corrupted. Removing the submarine from owned submarines...

**Closed** 2023-11-24 09:06 UTC
Labels: Bug, Code, Modding
