### ISSUE TITLE
Multiple nests spawning in the same cave

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10927] opened 2023-01-14 01:10 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://user-images.githubusercontent.com/73229309/212443358-126cc67c-962b-458b-94de-76d98aeef078.png)

In a round with Mudraptor + Thresher missions, both nests spawned in the same cave, causing both species to fight eachother
The level generated 3 caves in the level in total

Might be caused by the 3 mission limit

![image](https://user-images.githubusercontent.com/73229309/212443465-3823268e-d726-4da0-ba03-0c5b6a21f034.png)

### Bug prevalence

Just once

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-01-14 10:42
Duplicate of https://github.com/Regalis11/Barotrauma/issues/6142

**Closed by Regalis11** 2023-01-14 10:42 UTC
Labels: wontfix
