### ISSUE TITLE
[Factions] Abandoned Outposts make you lose reputation

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10995] opened 2023-01-21 02:13 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### Key Information
Game mode: Campaign
Game type: Multiplayer
Campaign save version: Started in 100.13.0.0, issue occurred in version 100.15.0.0
Server type: Steam P2P
### Issue Report
Possibly similar to #8989.

In an abandoned outpost mission (assassinate bandit leader), our crew consistently lost Coalition reputation whenever we attacked the bandits. This made our reputation go from unfriendly to outright hostile in a single mission, which was less than ideal. 

![image](https://user-images.githubusercontent.com/105495756/213837160-647a8443-2548-4a5c-bb37-8c233af9e3e1.png)
![image](https://user-images.githubusercontent.com/105495756/213837181-1f9db1ae-47dc-46d3-88a5-e8e817792754.png)

### Bug prevalence

Just once

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Wheatley1001** [comment] 2023-01-21 03:59
At the same time as this issue, many players were disconnected from the server and had the following error code: 
![image](https://user-images.githubusercontent.com/105495756/213842394-1defaae7-7a16-4d29-a1bc-914e881e0086.png)
I've looked around to see if this is a separate issue and I believe it's related to a ticket from two years ago but the error code wording is slightly altered. I'm unsure if these things are related or if they're two separate issues entirely.

**Comment by Dynamiteside** [comment] 2023-01-21 13:22
As far as im aware you loose reputation for damaging an outpost (yes even an abandoned one) so you probably accidentally made some holes with gunfire into the outpost or smth and that is why you lost reputation

**Comment by Regalis11** [comment] 2023-01-23 09:41
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9128862f80fc065cd9b72559131bd8b690851184

**Comment by JeroonBosch** [comment] 2023-01-31 11:49
Cannot reproduce faction-affiliated abandoned outpost after the fix, so closing

**Closed by JeroonBosch** 2023-01-31 11:49 UTC
Labels: Bug, Code, Severe
