### ISSUE TITLE
Multiplayer issue

### ISSUE THREAD

**Issue by Xyilusha22812** [Regalis11/Barotrauma#12095] opened 2023-05-29 13:53 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

In Multiplayer when we leave the dock station my game crashe's and i see this thing
![2023-05-29_21-36-18](https://github.com/Regalis11/Barotrauma/assets/134944358/cefa6cae-a73e-4c67-92f6-0fa13d7f3c83)

### Reproduction steps

1. Do lobby
2. Start game
3. choose mission leave station
4. Then boom the crash
5. 
![2023-05-29_21-36-18](https://github.com/Regalis11/Barotrauma/assets/134944358/93f48059-6633-4c0e-9e3c-adee687c9853)

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### -

no other

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 05/29/2023 21:28:22)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

The crash was caused by the DirectX error DeviceHung (HRESULT = 0x887A0006). This is a common DirectX error that can be related to various different issues, such as outdated drivers, RAM problems or an overclocked or otherwise overstressed GPU. There are several potential ways to fix the issue: ensuring your graphics drivers and DirectX installation are up-to-date, disabling overclocking and adjusting various GPU-specific settings. You may also be able to find potential solutions to the problem by using the error code DeviceHung (HRESULT = 0x887A0006) and your GPU manufacturer as search terms.

9336E644980627F155F3EC9C12F39BCC

Game version 1.0.13.2 (ReleaseWindows, branch release/1.0-patch-1-hotfix, revision 122a798c9a)
Graphics mode: 1024x768 (Windowed)
VSync OFF
Language: Russian
Selected content packages: Vanilla (E7A137B), Performance Fix (968FC30), Lua For Barotrauma (4F663F9), DynamicEuropa (1790E40), Unlimited Ammunition Box (888276A), Cs For Barotrauma (965D27D), MoreMissionsMod (B0D56C6), Unlock Parallel Talents (Updated for 1.0) (A19A458), Improved Husks (194B58E), Multiplayer Performance Fix (755B97B), BetterHealthUI (5C86226)
Level seed: Dagrun31Noctae69
Loaded submarine: Dugong (57AD692F394D61FF4764C93778F750F5)
Selected screen: Barotrauma.RoundSummaryScreen
SteamManager initialized
Client (Round hadn't been started)

System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: Intel(R) HD Graphics
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Экземпляр устройства GPU приостановлен. Для определения соответствующего действия используйте GetDeviceRemovedReason.
 (SharpDX.SharpDXException)
Device removed reason: DeviceHung (HRESULT = 0x887A0006)
Target site: Void PlatformPresent()
Stack trace: 
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 1017
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[05/29/2023 21:28:16] Level identifier: coldcavernsbasic
[05/29/2023 21:27:37] ballsdestroyer1987
[05/29/2023 21:27:37] Еврей
[05/29/2023 21:27:36] ballsdestroyer1987
[05/29/2023 21:27:36] Еврей
[05/29/2023 21:22:13] ballsdestroyer1987
[05/29/2023 21:22:12] Еврей
[05/29/2023 21:22:08] Received STARTGAMEFINALIZE packet. Round init status: Started
[05/29/2023 21:22:08] Task count: 0
[05/29/2023 21:22:08] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[05/29/2023 21:21:54] Generating an outpost for the start of the level... (Location: Dagrun, level type: Outpost)
[05/29/2023 21:21:54] Level identifier: outpostlevel
[05/29/2023 21:21:24] ballsdestroyer1987
[05/29/2023 21:21:24] Еврей
[05/29/2023 21:21:22] ballsdestroyer1987
[05/29/2023 21:21:22] Еврей
[05/29/2023 21:21:22] No messages defined for the location type change None -> UnderAttack
[05/29/2023 21:21:22] No messages defined for the location type change None -> Waypoint
[05/29/2023 21:18:17] ballsdestroyer1987
[05/29/2023 21:18:17] Еврей
[05/29/2023 21:18:17] ballsdestroyer1987
[05/29/2023 21:18:17] Еврей
[05/29/2023 21:17:46] ballsdestroyer1987
[05/29/2023 21:17:46] Еврей
[05/29/2023 21:17:43] ballsdestroyer1987
[05/29/2023 21:17:43] Еврей
[05/29/2023 21:17:41] ballsdestroyer1987
[05/29/2023 21:17:41] Еврей
[05/29/2023 21:17:41] ballsdestroyer1987
[05/29/2023 21:17:41] Еврей
[05/29/2023 21:14:24] ballsdestroyer1987
[05/29/2023 21:14:24] Еврей
[05/29/2023 21:14:24] ballsdestroyer1987
[05/29/2023 21:14:24] Еврей
[05/29/2023 21:13:23] ballsdestroyer1987
[05/29/2023 21:13:23] Еврей
[05/29/2023 21:13:19] ballsdestroyer1987
[05/29/2023 21:13:19] Еврей
[05/29/2023 21:13:18] ballsdestroyer1987
[05/29/2023 21:13:18] Еврей
[05/29/2023 21:13:18] ballsdestroyer1987
[05/29/2023 21:13:18] Еврей
[05/29/2023 20:47:50] ballsdestroyer1987
[05/29/2023 20:47:50] Еврей
[05/29/2023 20:47:44] ballsdestroyer1987
[05/29/2023 20:47:44] Еврей
[05/29/2023 20:47:41] Received STARTGAMEFINALIZE packet. Round init status: Started
[05/29/2023 20:47:39] Task count: 0
[05/29/2023 20:47:39] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[05/29/2023 20:47:32] Generating an outpost for the end of the level... (Location: Dagrun, level type: LocationConnection)
[05/29/2023 20:47:29] Generating an outpost for the start of the level... (Location: Аванпост Anid, level type: LocationConnection)
[05/29/2023 20:47:29] Level identifier: coldcavernsbasic
[05/29/2023 20:45:35] Еврей
[05/29/2023 20:45:07] Еврей
[05/29/2023 20:45:04] Received STARTGAMEFINALIZE packet. Round init status: Started
[05/29/2023 20:45:04] Received STARTGAMEFINALIZE packet. Round init status: Started
[05/29/2023 20:45:02] Task count: 0
[05/29/2023 20:45:01] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[05/29/2023 20:44:54] Generating an outpost for the end of the level... (Location: Dagrun, level type: LocationConnection)
[05/29/2023 20:44:50] Generating an outpost for the start of the level... (Location: Аванпост Anid, level type: LocationConnection)
[05/29/2023 20:44:50] Level identifier: coldcavernsbasic
[05/29/2023 20:43:55] Lobby created!
[05/29/2023 20:42:53] Error loading save file "C:\Users\User\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\Сохранение 9.save". The file may be corrupted.
[05/29/2023 20:42:53] Error decompressing C:\Users\User\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\Сохранение 9.save {The archive entry was compressed using an unsupported compression method.}
   at System.IO.Compression.Inflater.Inflate(FlushCode flushCode)
   at System.IO.Compression.Inflater.ReadInflateOutput(Byte* bufPtr, Int32 length, FlushCode flushCode, Int32& bytesRead)
   at System.IO.Compression.Inflater.ReadOutput(Byte* bufPtr, Int32 length, Int32& bytesRead)
   at System.IO.Compression.Inflater.InflateVerified(Byte* bufPtr, Int32 length)
   at System.IO.Compression.DeflateStream.CopyToStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.CopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestination()
   at System.IO.Compression.DeflateStream.CopyTo(Stream destination, Int32 bufferSize)
   at Barotrauma.SaveUtil.DecompressFileToStream(String fileName) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SaveUtil.cs:line 431
   at Barotrauma.SaveUtil.DecompressToDirectory(String sCompressedFile, String sDir, ProgressDelegate progress) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SaveUtil.cs:line 513
   at Barotrauma.SaveUtil.LoadGameSessionDoc(String filePath) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SaveUtil.cs:line 172
[05/29/2023 20:42:52] Error decompressing C:\Users\User\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\Сохранение 9.save {The archive entry was compressed using an unsupported compression method.}
   at System.IO.Compression.Inflater.Inflate(FlushCode flushCode)
   at System.IO.Compression.Inflater.ReadInflateOutput(Byte* bufPtr, Int32 length, FlushCode flushCode, Int32& bytesRead)
   at System.IO.Compression.Inflater.ReadOutput(Byte* bufPtr, Int32 length, Int32& bytesRead)
   at System.IO.Compression.Inflater.InflateVerified(Byte* bufPtr, Int32 length)
   at System.IO.Compression.DeflateStream.CopyToStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.CopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestination()
   at System.IO.Compression.DeflateStream.CopyTo(Stream destination, Int32 bufferSize)
   at Barotrauma.SaveUtil.DecompressFileToStream(String fileName) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SaveUtil.cs:line 431
   at Barotrauma.SaveUtil.DecompressToDirectory(String sCompressedFile, String sDir, ProgressDelegate progress) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SaveUtil.cs:line 513
   at Barotrauma.SaveUtil.LoadGameSessionDoc(String filePath) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SaveUtil.cs:line 172
[05/29/2023 20:42:47] Overriding an affliction or a buff with the identifier 'huskinfection' using the file 'C:/Users/User/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2085783214/Afflictions.xml'
[05/29/2023 20:41:45] Attempting to open ALC device "OpenAL Soft on Динамики (Realtek High Definition Audio)"
[05/29/2023 20:41:41] Logged in as Хуйлуша (SteamID STEAM_1:0:543433635)
```

**Comment by Regalis11** [comment] 2023-05-29 14:37
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10540

**Closed by Regalis11** 2023-05-29 14:37 UTC
