### ISSUE TITLE
The light of the lamps passes through the doors

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#9325] opened 2022-06-12 13:17 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The light of the lamps passes through the ~~walls~~ doors at certain values of the `range` and depends on the `scale` of the lamp!
Lamp 1:  https://user-images.githubusercontent.com/93348499/173234685-770184fc-9975-477d-9f65-75fb87deeed6.mp4 
Lamp 2: https://user-images.githubusercontent.com/93348499/173234717-49aa358f-c8c7-41aa-9a75-4bd384e2c38d.mp4
Start test: https://user-images.githubusercontent.com/93348499/173234775-88996882-f0a1-4a2f-8faf-dd572463b59d.mp4

 

### Reproduction steps

You can watch videos 1 and 2 (recommend ;)
or
1. Start editor
2. Create lamp and door
3. Change range and lamp scale

### Bug prevalence

Happens every time I play

### Version

0.17.16.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-06-12 15:10
I can't see the issue in the videos. Do you mean the light in the corner of the hull here?
![image](https://user-images.githubusercontent.com/14351070/173239618-619c7f9a-c765-4b57-b09f-b1205ad08bfe.png)

**Comment by MaaiG** [comment] 2022-06-12 16:18
>  the light in the corner of the hull here?

Yes! It is present at some range settings.

**Comment by Regalis11** [comment] 2023-03-10 10:41
We're cleaning up some low-prio/unreproducible/irrelevant/outdated tickets from the issue tracker, and this is one of the tickets we chose to axe. This is caused by the "blur" applied to the lighting, which is intended to both make the light look better and to allow light to bleed into walls slightly (otherwise the walls would just be almost solid black, making it impossible to see the sprite or the wall damage). While it could be possible to change the blur depending on the type of obstacle, I think this is such a minor issue I don't think it's worth the trouble. Closing.

**Closed by Regalis11** 2023-03-10 10:41 UTC
Labels: Bug, Code, Low prio
