### ISSUE TITLE
Crash During Mission

### ISSUE THREAD

**Issue by Minukelsus** [Regalis11/Barotrauma#9357] opened 2022-06-15 21:54 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This has only happened once so far. I was about 10 minutes into a mission then it suddenly crashed, giving a crash report. I didn't do anything out of the normal so I'm not sure what happened. Probably just a bug from the new update but I'm unsure.

### Reproduction steps

1. Play game as normal.
2. Eventually crash out of nowhere.

### Bug prevalence

Just once

### Version

Other

### -

0.18.11.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 15/06/2022 22:23:44)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


126A1EFE280FCB5E98C29D91D4C57FA1


Game version 0.18.11.0 (ReleaseWindows, branch release, revision 75c2f92d56)
Graphics mode: 1920x1080 (Fullscreen)
VSync ON
Language: English
Selected content packages: Vanilla
Level seed: New IapetusKrytogorsk
Loaded submarine: Barsuk (E2E891571395B60C2059BC9D09692B88)
Selected screen: Barotrauma.GameScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce GTX 970M
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.
 (SharpDX.SharpDXException)
Device removed reason: HRESULT = 0x887A0006
Target site: Void CheckError()
Stack trace: 
   at SharpDX.Result.CheckError()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 1017
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 511
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59


Last debug messages:
[15/06/2022 22:19:58] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
[15/06/2022 22:19:51] Generating an outpost for the start of the level... (Location: New Iapetus Station, level type: LocationConnection)
[15/06/2022 22:19:50] Generating an outpost for the end of the level... (Location: Krytogorsk Outpost, level type: LocationConnection)
[15/06/2022 22:19:50] Level identifier: coldcavernsadvanced
[15/06/2022 22:19:39] Transitioning to New IapetusKrytogorsk (current location: Krytogorsk Outpost, selected location: New Iapetus Station, leaving sub: Barsuk, at start: True, at end: False, transition type: LeaveLocation)
[15/06/2022 22:10:55] Unlocked mission "Killing Hammerheads" in the location "Krytogorsk Outpost".
[15/06/2022 22:10:52] Unlocked mission "Mining pyromorphite" in the location "Krytogorsk Outpost".
[15/06/2022 22:10:50] Unlocked mission "Personnel Transport" in the location "Krytogorsk Outpost".
[15/06/2022 22:10:46] Unlocked mission "Mining outpost material transport" in the location "Krytogorsk Outpost".
[15/06/2022 22:10:43] Unlocked mission "Destroy a Crawler nest" in the location "Krytogorsk Outpost".
[15/06/2022 22:10:41] Unlocked mission "Terminate a Swarm" in the location "Krytogorsk Outpost".
[15/06/2022 22:02:29] Generating an outpost for the start of the level... (Location: Krytogorsk Outpost, level type: Outpost)
[15/06/2022 22:02:29] Level identifier: outpostlevel
[15/06/2022 22:02:19] Transitioning to Krytogorsk (current location: Novaya Moskva Habitation Outpost, selected location: Krytogorsk Outpost, leaving sub: Barsuk, at start: False, at end: True, transition type: ProgressToNextLocation)
[15/06/2022 21:49:56] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
[15/06/2022 21:49:50] Generating an outpost for the start of the level... (Location: Krytogorsk Outpost, level type: LocationConnection)
[15/06/2022 21:49:48] Generating an outpost for the end of the level... (Location: Novaya Moskva Habitation Outpost, level type: LocationConnection)
[15/06/2022 21:49:48] Level identifier: coldcavernsadvanced
[15/06/2022 21:49:37] Transitioning to KrytogorskNovaya Moskva (current location: Novaya Moskva Habitation Outpost, selected location: Krytogorsk Outpost, leaving sub: Barsuk, at start: True, at end: False, transition type: LeaveLocation)
[15/06/2022 21:32:59] Unlocked mission "Terminate a Large Swarm" in the location "Novaya Moskva Habitation Outpost".
[15/06/2022 21:32:57] Unlocked mission "Chemical shipment" in the location "Novaya Moskva Habitation Outpost".
[15/06/2022 21:32:54] Unlocked mission "Killing a large Crawler" in the location "Novaya Moskva Habitation Outpost".
[15/06/2022 21:29:59] Generating an outpost for the start of the level... (Location: Novaya Moskva Habitation Outpost, level type: Outpost)
[15/06/2022 21:29:59] Level identifier: outpostlevel
[15/06/2022 21:29:49] Transitioning to Novaya Moskva (current location: Hyldemoer, selected location: Novaya Moskva Habitation Outpost, leaving sub: Barsuk, at start: False, at end: True, transition type: ProgressToNextLocation)
[15/06/2022 21:10:02] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
[15/06/2022 21:09:55] Could not find a suitable module for the location type LocationType (None). Module flag: Airlock.
[15/06/2022 21:09:54] Generating an outpost for the end of the level... (Location: Hyldemoer, level type: LocationConnection)
[15/06/2022 21:09:54] Level identifier: coldcavernsadvanced
[15/06/2022 21:09:44] Transitioning to Novaya MoskvaHyldemoer (current location: Hyldemoer, selected location: Novaya Moskva Habitation Outpost, leaving sub: Barsuk, at start: False, at end: True, transition type: ProgressToNextEmptyLocation)
[15/06/2022 20:55:43] Generating an outpost for the start of the level... (Location: Versas Outpost, level type: LocationConnection)
[15/06/2022 20:55:42] Level identifier: coldcavernsbasic
[15/06/2022 20:55:32] Transitioning to VersasHyldemoer (current location: Versas Outpost, selected location: Hyldemoer, leaving sub: Barsuk, at start: True, at end: False, transition type: LeaveLocation)
[15/06/2022 20:46:26] Unlocked mission "Chemical shipment" in the location "Versas Outpost".
[15/06/2022 20:46:23] Unlocked mission "Killing a large Crawler" in the location "Versas Outpost".
[15/06/2022 20:46:20] Unlocked mission "Personnel Transport" in the location "Versas Outpost".
[15/06/2022 20:42:26] Generating an outpost for the start of the level... (Location: Versas Outpost, level type: Outpost)
[15/06/2022 20:42:26] Level identifier: outpostlevel
[15/06/2022 19:58:22] Failed to load package "Dead Space" {Exception has been thrown by the target of an invocation.}
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at Barotrauma.SoundsFile.CreatePrefab(ContentXElement element) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentFile\SoundsFile.cs:line 23
   at Barotrauma.GenericPrefabFile`1.LoadFromXElement(ContentXElement parentElement, Boolean overriding) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentFile\GenericPrefabFile.cs:line 36
   at Barotrauma.GenericPrefabFile`1.LoadFromXElement(ContentXElement parentElement, Boolean overriding) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentFile\GenericPrefabFile.cs:line 49
   at Barotrauma.GenericPrefabFile`1.LoadFromXElement(ContentXElement parentElement, Boolean overriding) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentFile\GenericPrefabFile.cs:line 25
   at Barotrauma.ContentPackage.<>c__DisplayClass46_0.<<LoadPackageEnumerable>g__loadFiles|1>d.MoveNext() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentPackage\ContentPackage.cs:line 232

Inner exception: Sound file "Content/Sounds/UI/Click.ogg" doesn't exist!
   at Barotrauma.Sounds.SoundManager.LoadSound(ContentXElement element, Boolean stream, String overrideFilePath) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sounds\SoundManager.cs:line 384
   at Barotrauma.SoundPrefab..ctor(ContentXElement element, SoundsFile file, Boolean stream) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sounds\SoundPrefab.cs:line 194
   at Barotrauma.GUISound..ctor(ContentXElement element, SoundsFile file) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sounds\SoundPrefab.cs:line 265
[15/06/2022 19:58:00] Alc.CaptureOpenDevice attempt 2 failed: error code 40964
[15/06/2022 19:58:00] alcCaptureOpenDevice failed: exception thrown (Device init failed: 0x80004005)
[15/06/2022 19:58:00] WASAPI capture open failed: HRESULT 0x80004005 (1)
[15/06/2022 19:58:00] Alc.CaptureOpenDevice attempt 1 failed: error code 40964
[15/06/2022 19:58:00] alcCaptureOpenDevice failed: exception thrown (Device init failed: 0x80004005)
[15/06/2022 19:58:00] WASAPI capture open failed: HRESULT 0x80004005 (1)
[15/06/2022 19:56:52] WARNING: C:/Users/james/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/1985372388/Randomevents.xml: All root EventSets should have an identifier
[15/06/2022 19:56:52] WARNING: C:/Users/james/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/1985372388/Randomevents.xml: All root EventSets should have an identifier
[15/06/2022 19:56:52] WARNING: C:/Users/james/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/1985372388/Randomevents.xml: All root EventSets should have an identifier
[15/06/2022 19:56:52] WARNING: C:/Users/james/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/1985372388/Randomevents.xml: All root EventSets should have an identifier
[15/06/2022 19:56:52] WARNING: C:/Users/james/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/1985372388/Randomevents.xml: All root EventSets should have an identifier
[15/06/2022 19:56:52] WARNING: C:/Users/james/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/1985372388/Randomevents.xml: All root EventSets should have an identifier
[15/06/2022 19:56:52] WARNING: C:/Users/james/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/1985372388/Randomevents.xml: All root EventSets should have an identifier
[15/06/2022 19:56:52] WARNING: C:/Users/james/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/1985372388/Randomevents.xml: All root EventSets should have an identifier
[15/06/2022 19:56:07] Attempting to open ALC device "OpenAL Soft on Speakers (Sound Blaster Recon3Di)"
[15/06/2022 19:56:04] Logged in as Minukelsus (SteamID STEAM_1:0:58525697)
```

**Comment by Regalis11** [comment] 2022-06-16 06:08
Duplicate of https://github.com/Regalis11/Barotrauma/issues/1833

**Closed by Regalis11** 2022-06-16 06:08 UTC
