### ISSUE TITLE
Button wired to discharge coil will cause only client side visible shock.

### ISSUE THREAD

**Issue by HeatedWafflez** [Regalis11/Barotrauma#2324] opened 2020-02-17 12:48 UTC
**Description**
Pressing a button wired to the 'trigger in' on a discharge will cause the shock to only be visible client side.

**Steps To Reproduce**
Refer to above.

**Version**
0.9.7.0

**Additional information**
May also apply to toggle lights as well, and logic, though no concrete evidence.

**Comment by Udrakan** [comment] 2020-02-17 13:57
It's always been like this since release.

**Comment by Regalis11** [comment] 2020-04-15 11:12
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/406725ca0caeb3d683cbad578202f27ebd5fa7f5

**Comment by Rokvach** [comment] 2020-05-13 18:17
Confirmed working, closing.

**Closed by Rokvach** 2020-05-13 18:17 UTC
Labels: Bug, Code, Networking
