### ISSUE TITLE
[0.1300.0.0] Diving suit oxygen tank shelves do not refill oxygen tanks

### ISSUE THREAD

**Issue by anubis-barotrauma** [Regalis11/Barotrauma#5119] opened 2021-02-21 03:48 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Non-full oxygen tanks placed into diving suit oxygen tank shelves are not refilled. The diving suit locker itself works fine however.

**Steps To Reproduce**
Place a non-full oxygen tank into a powered oxygen tank shelf.

**Version**
v0.1300.0.0, unstable.

**Comment by Regalis11** [comment] 2021-02-22 08:56
I'm afraid I couldn't reproduce this, the tanks seem to be filling up as expected:
![image](https://user-images.githubusercontent.com/14351070/108685203-89f44600-74fc-11eb-9c22-660e6c0ee1c2.png)

**Comment by anubis-barotrauma** [comment] 2021-02-22 11:16
Upon connecting the shelves in Dugong as you demonstrated, they indeed do refill.

I think the problem is related to newly created oxygen tanks somehow - if you place a completely new diving suit locker assembly and connect it to power, then place a non-full oxygen tank from the newly placed diving suit, it does not refill. Placing an _old_ oxygen tank to a newly created shelf gets refilled as normal.

Please see the attachment for a test bench. When I equip the diving suit, then swap the 98% full oxygen tank in my suit with a full one from the shelf, it stays at 98% indefinitely.

[BugReportOxygenShelf.zip](https://github.com/Regalis11/Barotrauma/files/6021529/BugReportOxygenShelf.zip)

**Comment by Udrakan** [comment] 2021-02-22 16:39
It might be an issue with assembly items having their info not updated because it's defined in the assembly it self

**Comment by Udrakan** [comment] 2021-02-22 16:44
I have downloaded your .sub file, took one of the already existing O2 bottles in the O2 shelf, gave it 50% condition, then put it back. Then I spawned in a new O2 bottle, gave it 50% and put it in the shelf. In testing mode, both bottles are refilling correctly.

**Comment by anubis-barotrauma** [comment] 2021-02-22 18:30
Strange, could you test the one in the diving suit? Equip the suit, then swap your tank with a full one from the shelf. For me, they are not refilling. I am using the file I have attached. Verified the game files from Steam, still the same behavior.

![NoRefill](https://user-images.githubusercontent.com/78148238/108752438-812f5e80-7554-11eb-8e16-622d0a0e4e86.jpg)

**Comment by Regalis11** [comment] 2021-02-23 13:55
Thanks for the extra info, found the issue now. The shelves relied on the tanks having the tag "oxygentank" which they no longer do, so only tanks in existing subs would work. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3423a359af256440f8e6fe18731f39147a63477b

**Comment by Rokvach** [comment] 2021-02-24 08:49
Tested, no issues. Closing.

**Closed by Rokvach** 2021-02-24 08:49 UTC
Labels: Bug, Code
