### ISSUE TITLE
Game Crash when starting a sub

### ISSUE THREAD

**Issue by Allayen** [Regalis11/Barotrauma#6507] opened 2021-08-27 16:41 UTC
My game just crush when im trying to start a game with mission or without it. I put crash report here.

Barotrauma Client crash report (generated on 27.08.2021 18:17:57)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

0C78B5274CD035ACEBA01DC0F25E450F

Game version 0.14.9.0 (ReleaseWindows, branch feature/bugfixes, revision 6f88f3dc8c)
Graphics mode: 1024x768 (Fullscreen)
VSync ON
Language: Polish
Selected content packages: Vanilla 0.9
Level seed: DolgovskoyPastonia
Loaded submarine: Dugong (2C4F942B801D1DB70335ED8EF963668C)
Selected screen: Barotrauma.RoundSummaryScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19043.0 64 bit
    GPU name: Intel(R) HD Graphics 3000
    Display mode: {Width:1360 Height:768 Format:Color AspectRatio:1,7708334}
    GPU status: Normal

Exception: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Wystąpienie urządzenia GPU zostało zawieszone. Użyj obiektu GetDeviceRemovedReason, aby określić odpowiednią akcję.
 (SharpDX.SharpDXException)
Device removed reason: HRESULT = 0x887A0006
Target site: Void CheckError()
Stack trace: 
   at SharpDX.Result.CheckError()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 1017
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 511
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59

Last debug messages:
[27.08.2021 18:17:37] Transitioning to DolgovskoyPastonia (current location: Stacja Dolgovskoy, selected location: Stacja Pastonia, leaving sub: Dugong, at start: True, at end: False, transition type: LeaveLocation)
[27.08.2021 18:16:46] Generating an outpost for the start of the level... (Location: Stacja Dolgovskoy, level type: Outpost)
[27.08.2021 18:15:52] Generating an outpost for the start of the level... (Location: Stacja Newellstead, level type: LocationConnection)
[27.08.2021 18:15:09] (Msg) SDR RelayNetworkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[27.08.2021 18:15:09] (Msg) Ping location: waw=70+7,fra=79+7,vie=105+10/81+7,ams=104+10/86+7,par=86+8,sto=106+10/90+7,sto2=/91+7,lhr=93+9/93+7,mad=105+10/105+8,iad=175+17/163+8,sgp=323+32/260+20,gru=294+29/306+8
[27.08.2021 18:15:09] (Msg) Ping measurement completed
[27.08.2021 18:15:09] (Debug) Destroying relay 'sof#4 (139.45.193.10:27018)' because initial_ping_timeout
[27.08.2021 18:15:09] (Debug) Destroying relay 'sto2#127 (155.133.252.38:27018)' because initial_ping_timeout
[27.08.2021 18:15:09] (Debug) Destroying relay 'eat#50 (155.133.235.34:27026)' because initial_ping_timeout
[27.08.2021 18:15:07] (Debug) Destroying relay 'sto2#156 (155.133.252.38:27047)' because initial_ping_timeout
[27.08.2021 18:15:07] (Debug) Destroying relay 'sof#1 (139.45.193.10:27015)' because initial_ping_timeout
[27.08.2021 18:15:07] (Debug) Destroying relay 'eat#9 (155.133.235.18:27023)' because initial_ping_timeout
[27.08.2021 18:15:05] (Verbose) Communications with routing cluster 'tyo1' established.
[27.08.2021 18:15:05] (Verbose) Communications with routing cluster 'syd' established.
[27.08.2021 18:15:05] (Verbose) Communications with routing cluster 'tyo' established.
[27.08.2021 18:15:05] (Verbose) Communications with routing cluster 'sgp' established.
[27.08.2021 18:15:05] (Verbose) Communications with routing cluster 'waw' established.
[27.08.2021 18:15:05] (Verbose) Communications with routing cluster 'vie' established.
[27.08.2021 18:15:05] (Verbose) Communications with routing cluster 'scl' established.
[27.08.2021 18:15:05] (Verbose) Communications with routing cluster 'sea' established.
[27.08.2021 18:15:05] (Verbose) Communications with routing cluster 'sto' established.
[27.08.2021 18:15:05] (Verbose) Communications with routing cluster 'maa' established.
[27.08.2021 18:15:05] (Verbose) Communications with routing cluster 'ord' established.
[27.08.2021 18:15:05] (Verbose) Communications with routing cluster 'lim' established.
[27.08.2021 18:15:05] (Verbose) Communications with routing cluster 'par' established.
[27.08.2021 18:15:05] (Verbose) Communications with routing cluster 'hkg' established.
[27.08.2021 18:15:05] (Verbose) Communications with routing cluster 'mad' established.
[27.08.2021 18:15:05] (Verbose) Communications with routing cluster 'lax' established.
[27.08.2021 18:15:05] (Verbose) Communications with routing cluster 'jnb' established.
[27.08.2021 18:15:05] (Verbose) Communications with routing cluster 'gru' established.
[27.08.2021 18:15:05] (Verbose) Communications with routing cluster 'eze' established.
[27.08.2021 18:15:05] (Verbose) Communications with routing cluster 'lhr' established.
[27.08.2021 18:15:05] (Verbose) Communications with routing cluster 'iad' established.
[27.08.2021 18:15:04] (Verbose) Communications with routing cluster 'dxb' established.
[27.08.2021 18:15:04] (Verbose) Communications with routing cluster 'dfw' established.
[27.08.2021 18:15:04] (Verbose) Communications with routing cluster 'fra' established.
[27.08.2021 18:15:04] (Verbose) Communications with routing cluster 'bom' established.
[27.08.2021 18:15:04] (Verbose) Communications with routing cluster 'atl' established.
[27.08.2021 18:15:04] (Verbose) Communications with routing cluster 'ams' established.
[27.08.2021 18:15:04] (Msg) SDR RelayNetworkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[27.08.2021 18:15:04] (Msg) Performing ping measurement
[27.08.2021 18:15:04] (Msg) Got SDR network config.  Loaded revision 330 OK
[27.08.2021 18:15:04] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[27.08.2021 18:14:50] Attempting to open ALC device "OpenAL Soft on Głośniki (USB Audio Device)"
[27.08.2021 18:14:48] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[27.08.2021 18:14:48] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[27.08.2021 18:14:45] Logged in as Allayen (SteamID STEAM_1:0:437605734)

**Comment by Regalis11** [comment] 2021-08-30 08:08
Duplicate of https://github.com/Regalis11/Barotrauma/issues/1833

**Closed by Regalis11** 2021-08-30 08:08 UTC
Labels: Bug, Code, Crash
