### ISSUE TITLE
High memory usage #2

### ISSUE THREAD

**Issue by SenhorPatolino** [Regalis11/Barotrauma#2563] opened 2020-04-02 22:02 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Alright, i came back to this topic for some reasons, last time i said about the sub editor having high memory usage even empty, Regalis gave me a explanation and, sure that does make sense, but today i tried to open the dedicatedserver.exe and it went to 1GB of memory usage, but when i went to stable version it was only using 200MB, i remember someone also saying that unstable seems to have a lower perfomance, not sure about that because i didnt play multiplayer yet.

But i have some suggestions on what could be happening, maybe dedicated server works on unstable but doesnt work on stable, since i bought Barotrauma i have never been able to host a server through the menu without problems, i still was able after 2 or 3 tries, now im not even able to host a server, the dedicatedserver process crashes and was supposed to save a crash log (it doesnt), maybe in unstable now the dedicatedserver its working correctly and thats causing the 1GB usage, or, it may just be a problem with the audio engine or something like that, one of the devs mentioned problems with it causing perfomance problems.

Forgive any bad english or missunderstandings.

**Version**
0.9.9.0 on Windows

**Comment by Regalis11** [comment] 2020-04-03 06:58
>  today i tried to open the dedicatedserver.exe and it went to 1GB of memory usage, but when i went to stable version it was only using 200MB

I unfortunately wasn't able to reproduce this:
![w45tearf](https://user-images.githubusercontent.com/14351070/78332848-7319cd80-7591-11ea-98ff-26bfac5001de.png)

It seems to use a little above 200 MB even in unstable, and doesn't go above 300 MB even when I start a round.

>  since i bought Barotrauma i have never been able to host a server through the menu without problems, i still was able after 2 or 3 tries, now im not even able to host a server

As mentioned in the previous thread, I'm afraid you have so little memory that it's barely enough to run Barotrauma, so I think this issue could be caused by running out of memory when trying to start the server.

**Comment by SenhorPatolino** [comment] 2020-04-03 17:32
I agreed with you, im pretty sure thats why it crashes the process while trying to run with SteamP2P, but im really confused of what happened when i tried to run it on unstable, it really went to 1GB but when i runned with stable running it was like yours.

**Comment by SenhorPatolino** [comment] 2020-04-09 17:52
Ok came back to warn that it did again, this time im not sure if it would reach 1GB or not because i closed it before it reached, my memory was already being used, it reached 600MB and kept increasing, i closed after that

**Comment by Regalis11** [comment] 2020-04-28 07:25
Addressed by implementing DTX5 compression in the private repo.

**Closed by Regalis11** 2020-04-28 07:25 UTC
Labels: Code, Need more info, Needs testing, Performance
