### ISSUE TITLE
Audio crackling (especially on sonar pings)

### ISSUE THREAD

**Issue by Oninaig** [Regalis11/Barotrauma#11820] opened 2023-04-14 14:55 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When standing at the command console with active sonar enabled, every time the sonar pings go out the audio crackles horribly. I don't believe this was happening pre 1.0.

### Reproduction steps

1.) Start game
2.) Go to command console
3.) Active active sonar and stand next to the command console for a bit listening to each ping. Over time, the start of each ping will be accompanied with an audio crackle.

### Bug prevalence

Happens every time I play

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-04-15 13:12
Duplicate of https://github.com/Regalis11/Barotrauma/issues/5730

**Closed by Regalis11** 2023-04-15 13:12 UTC
