### ISSUE TITLE
Can't return from a natural formation location

### ISSUE THREAD

**Issue by LavaontheFloor** [Regalis11/Barotrauma#10131] opened 2022-10-21 12:41 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While traveling for a scanning mission in which we needed to deliver data to a Natural formation (Drool). Upon arriving we couldn't progress any further. Arriving at the formation prompted the map to select another location mission to travel to, but the Natural formation had only one connecting location (Set outpost) that we had just come from, and we had no mission at this location to select. Clicking start and reading players still didn't allow any kind of progression. Travelling back to the set outpost left an empty outpost and no map prompt.

### Reproduction steps

-Accept a delivery mission to a natural formation that has no other connecting travel routes.
-Have no missions for the location leaving from.
- Complete the mission (in our case a scanning data mission) and travel to the natural formation.
- Open map but be unable to progress with no missions to select at the only connected travel destination.

### Bug prevalence

Just once

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-10-21 13:05
Thank you for the report! I'm not entirely sure I understood this correctly, but to me it doesn't sound like this is a bug. If you travel to this kind of a "dead-end location", the only choice when you reach the end is to navigate back. And since missions can only be unlocked at outposts, you obviously won't have any missions available for the return trip.

I do agree that it's strange that the missions may ask you to deliver things or data to an uninhabited location, we have an existing ticket about that but still haven't gotten around to addressing it: https://github.com/Regalis11/Barotrauma/issues/7497

**Comment by LavaontheFloor** [comment] 2022-10-22 01:36
Thank you for following up. I'll try and explain a bit better the issue. 
I think our main issue if the things you said are normal is that clicking start didn't complete our mission and allow us to leave.

Upon reaching the location, we were prompted with the "SELECT A DESTINATION AND LEAVE THE PASSAGEWAY" button to pick the next location and leave, but opening the map has the connected Set Outpost selected with No missions but the bottom of the tab says "1/2 Mission" as if we have selected one.
Clicking start did nothing no matter what we did. Clicking any other location on the map, including the Natural formation we were at, didn't change the selection, so the only place to travel to was back to the Set Outpost we came from. Unfortunately when clicking start nothing happened and we couldn't progress the game to move on.

We tried travelling back to the Set Outpost without the start option working, as the marker is still on the radar as it is where we came from, but when we got there we couldn't select a location to move to next and the whole outpost was empty.

Reflecting on it I wonder if the "1/2 Missions" listed on the Set Outpost (Even with NO MISSIONS below the title) is due to the fact that the current mission isn't technically finished until you leave, preventing us from returning to the same location. I just checked the game again as I was afraid we had soft-locked our whole campaign but reloading put us back at the Set Outpost and allowed me to redock and cancel the mission. 

We did try and research similar issues and did read other posts but were unable to find any solution and ended up having to quit as we were stuck with no way to progress. (Other posts #3470 #5662)
I didn't take a photo of the Map when we were stuck and it was difficult for us to complete the mission so I cant provide that but I took a screenshot of the Map before we left for Drool (the Natural formation). The Map was similar when we got there but with the Set Outpost selected, nothing under "No Missions", "Missions 1/2" next to the start button and start not doing anything to let us leave.

![Natural Formation](https://user-images.githubusercontent.com/116359786/197310589-179cd002-335b-441d-bf38-ed135ff63098.png)

**Comment by nicholashartono** [comment] 2022-11-03 12:20
In my case, the stuck happened because I go from abandon outpost into natural formation which only have beacon mission, when I got to the destination I can't start any mission and can only go back naturaly which don't do anything 
![unknown](https://user-images.githubusercontent.com/24422825/199718760-71c97c66-019e-44bf-b2b8-56f52ec75b0c.png)

**Comment by Regalis11** [comment] 2022-11-04 06:42
@nicholashartono would it be possible to send us the save file here? Note that you need to .zip it first to attach it, because GitHub doesn't support the .save file extension. Thanks and sorry for the inconvenience!

**Comment by NicholasHartonoTvlk** [comment] 2022-11-05 02:34
> @nicholashartono would it be possible to send us the save file here? Note that you need to .zip it first to attach it, because GitHub doesn't support the .save file extension. Thanks and sorry for the inconvenience!

Sorry, unfortunately I can't give you the save file since I already restart and move to the other way (to colonized outpost so I can progress again) , but I think you can test the same scenario as the image. 
Thank you also great game, loved it!

**Comment by Regalis11** [comment] 2023-01-23 13:16
Seems to be caused by the same issue as https://github.com/regalis11/barotrauma/issues/10772, closing as a duplicate

**Closed by Regalis11** 2023-01-23 13:16 UTC
Labels: Bug, Need more info, Code
