### ISSUE TITLE
Turret and searchlight lights are defaulting to being On after level change

### ISSUE THREAD

**Issue by PanmanS** [Regalis11/Barotrauma#12930] opened 2023-10-27 09:00 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When you toggle lights off on any turret or searchlight in campaign or editor and then continue onto next level/go back from test to editor, lights will go back to being on. If I remember correctly it should be caused by turret itself reseting to standard settings.

### Reproduction steps

1. Start campaign (doesnt matter if SP or MP)
2. Turn off all gun lights via switching wire of cannon from `trigger_in` and put it on toggle_light, click fire while on periscope (easily done with bot) and then put wire back in place
3. Procede to next level
4. Lights now should be on again 

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.1.18.1 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-10-27 10:32
Duplicate of Regalis11/Barotrauma#10704

**Closed by Regalis11** 2023-10-27 10:32 UTC
