### ISSUE TITLE
Docking port creates misaligned hull when external solid walls or fins that gets in the way, which can cause characters to get spit out into open water

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#7849] opened 2021-12-18 20:48 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Docking port creates misaligned hull when external solid walls or fins that gets in the way, which can cause characters to get spit out into open water.

[Testey.zip](https://github.com/Regalis11/Barotrauma/files/7739930/Testey.zip)

Default linked state:
![Capture](https://user-images.githubusercontent.com/5086682/146655050-e8db326c-bbbd-4f26-ae2d-7ef398a52800.PNG)

After undocking and redocking:
![Capture1](https://user-images.githubusercontent.com/5086682/146655054-7e21fa85-72ee-437c-b1de-11089c17f93a.PNG)

In the end I had to replace the fins with non-solid ones to get rid of the problem:
[Testey2.zip](https://github.com/Regalis11/Barotrauma/files/7739949/Testey2.zip)

**Steps To Reproduce**
Create two submarines with docking ports that can still be within docking proximity with each other, but add enough solids walls or fins that would get in the way of being able to sit neatly on top of each other. Dock the submarines with and without external factors to observe docking  port behaviour.

**Version**
~0.15.22.1

**Comment by MaaiG** [comment] 2021-12-20 11:42
I don’t have a problem (Spawn - Undocked - Docked).
When I docked the game slows but removing the "Tile Fin F3" solves the problem IMHO.
**Spawn:**
![Image 001_14-30](https://user-images.githubusercontent.com/93348499/146762019-389cb98d-419a-44b3-ab4f-f1966844e993.png)

**Comment by Ek-Videogames** [comment] 2021-12-22 08:10
I had a similar issue but for me the cause seemed to be that the hatch leading outside was slightly too far from the docking port's position. Although there were also the 'squared' shell caps on either side of the door - which are known to have somewhat extended hitboxes which could be causing the collision problem.

**Comment by Regalis11** [comment] 2022-02-04 14:28
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8129562f8de486ca7dd737bafd03ee1f63dc46bf

**Comment by Rokvach** [comment] 2022-04-05 12:18
Tested, working correctlly. closing.

**Closed by Rokvach** 2022-04-05 12:18 UTC
Labels: Bug, Code

**Comment by MaaiG** [comment] 2022-07-02 12:22
0.18.12.0 - The problem exists!

https://user-images.githubusercontent.com/93348499/177000599-da18a995-4c41-4a16-bd69-91f9b564c852.mp4
