### ISSUE TITLE
Multiple NPCS can manage reactor at once if they don't have orders.

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5259] opened 2021-03-15 23:17 UTC
- [ yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If no NPC in your crew has the order to manage the reactor, and every NPC has nothing else to do, there's no limit of how many NPCs will try to manage the reactor by themselves. This causes multiple NPCs to load their own fuel rod in the reactor at the same time, sometimes causing it to overheat.
The issue doesn't seem to happen 100% of the times
**Steps To Reproduce**
Have a few npcs on board, make sure they don't have a task that distracts them from the reactor and that they don't have the "power on reactor" order.

**Version**
Unstable v0.1300.0.2 Windows
![image](https://user-images.githubusercontent.com/55637865/111233240-64260280-85cb-11eb-9874-9458b0362089.png)

**Comment by LePiromano** [comment] 2021-03-15 23:33
I found the cause, it's not that multiple NPCS use the reactor at once, the problem is that when one of the npcs stops using the reactor to load more fuel into it, the other NPC starts using it, and it also loads more fuel

**Comment by itchyOwl** [comment] 2021-03-17 14:28
Couldn't repro it, but I think you might be right there: multiple bots truly tried to operate the reactor at the same time but they aborted the objective when someone actually was operating the reactor. It's possible that this would lead to the issues described above.

Should be fixed in Regalis11/Barotrauma-development@9d54b94. It can still happen with multiple engineers. I'll look into that later.

**Comment by itchyOwl** [comment] 2021-03-18 12:55
Changed the logic in Regalis11/Barotrauma-development@fa1fc84. Should be fixed now.

**Comment by Rokvach** [comment] 2021-04-01 14:01
Multiple bots are just using the reactor now when they are in idle even if one of them are ordered to operate the reactor, when player uses the reactor you can see that almost all of them except the one which has the order starts to walk away from the reactor.

**Comment by Rokvach** [comment] 2021-04-01 14:23
Working correctly in singleplayer, but not in multiplayer

**Comment by itchyOwl** [comment] 2021-04-01 17:45
Possibly fixed now.

**Comment by itchyOwl** [comment] 2021-04-01 17:53
No there's still something weird going on in multiplayer.

**Comment by Rokvach** [comment] 2021-04-06 10:18
Tested, looks like this was partially fixed. The bots wont walk to the reactor autonomously at the start of the round anymore, but instead if you order them to do something like heal other players or fix leaks which allows them to go idle as that task isn't currently needed they will walk straight to the reactor and operate it.

**Comment by itchyOwl** [comment] 2021-04-06 10:41
Ok, I'll try to repro.

**Comment by itchyOwl** [comment] 2021-04-06 16:35
Fixed in Regalis11/Barotrauma-development@67ea0c5. The issue was also reproduceable in single player game.

**Comment by Rokvach** [comment] 2021-04-06 18:56
Wasn't able to reproduce anymore, working correctly. Closing.

**Closed by Rokvach** 2021-04-06 18:56 UTC
Labels: Bug, Code, Low prio
