### ISSUE TITLE
Autosaved submarine will no longer save

### ISSUE THREAD

**Issue by FlareFlo** [Regalis11/Barotrauma#9554] opened 2022-07-11 02:43 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

<img src="https://cdn.discordapp.com/attachments/640953199116812309/995878288138436699/unknown.png">
Most likely covers #9545 too.

If there is a specific location where a more elaborate crash report/trace is located I will go and fetch it too, just couldn't find something like it anywhere.

### Reproduction steps

1. Open ship editor
2. Create a new ship and save it
4. Leave to the main menu
5. Return to the editor and load the autosave
6. Upon saving (if changes are made to the ship or not) will throw an exception

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
ERROR
An error occurred while trying to save issue_test {Tried to overwrite
a submarine (issue_test) that's not in a local package!}
at Barotrauma.SubEditorScreen.SaveSubToFile(String name,
ContentPackage packageToSaveTo) in
<DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SubE
ditorScreen.cs:line O
at
Barotrauma.SubEditorScreen.<>c__DisplayClass123_O.<SaveSub>b_
_1() in
<DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SubE
ditorScreen.cs:line 1758
at
Barotrauma.SubEditorScreen.<>c__DisplayClass123_O.<SaveSub>g_
_ handleExceptionslO(Action action) in
<DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SubE
ditorScreen.cs:line 1721

The text above comes from OCR, the source image is here: https://cdn.discordapp.com/attachments/640953199116812309/995878288138436699/unknown.png
```

**Comment by Regalis11** [comment] 2022-07-11 06:53
Duplicate of https://github.com/Regalis11/Barotrauma/issues/9545

**Closed by Regalis11** 2022-07-11 06:53 UTC
