### ISSUE TITLE
Server crash while hosting server/failure to connect  

### ISSUE THREAD

**Issue by NOODLESwastaken** [Regalis11/Barotrauma#3943] opened 2020-09-29 07:38 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When i try to host a server from the mainmenu each time i start it it tells me that the server process has been closed unexpectedly and that a crash report named (servercrashreport.log) may have been generated in the game's root directory. but i cant find it.

**Steps To Reproduce**
I dont really know how this happens.

**Version**
Windows v0.10.5.1 (ReleaseWindows, branch release, revision 9e259b2148)
**Additional information**
Is persisting despite restarting the game
![изображение](https://user-images.githubusercontent.com/67264852/94527579-dbdfbb00-023f-11eb-975b-1cbcafff245f.png)

**Comment by Regalis11** [comment] 2020-10-05 12:19
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3666

**Closed by Regalis11** 2020-10-05 12:19 UTC
Labels: Bug, Code
