### ISSUE TITLE
Remora Deep Diver's blueprint pictures have ladder reversed

### ISSUE THREAD

**Issue by VictoriaSteger** [Regalis11/Barotrauma#8169] opened 2022-02-02 03:12 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The Remora's blueprint picture (what you see when using the Status Monitor to find items or look for electrical issues) has the ladder which leads to the nuclear reactor facing the wrong direction.  In the blueprint, it connects to the upper landing near the nuclear reactor and the lower landing near the edge of the hole down to the pumps.  In the actual submarine, it connects to the upper landing near the supplies cabinet and the lower landing near the medium steel cabinet.

**Steps To Reproduce**
In the Remora, go to any Status Monitor and check the item finder or electrical issues screens.

**Version**
Windows, v0.15.23.0

**Additional information**
Screenshots attached.

![remora_real](https://user-images.githubusercontent.com/55817767/152087507-344b03f3-34c4-416d-b0d7-56521a3c446e.png)
![remora_blueprint](https://user-images.githubusercontent.com/55817767/152087511-9949d3b1-d37c-42d2-ba96-01de27539f50.png)

**Comment by Regalis11** [comment] 2022-02-02 11:59
Duplicate of https://github.com/Regalis11/Barotrauma/issues/8029

**Closed by Regalis11** 2022-02-02 11:59 UTC
Labels: Bug
