### ISSUE TITLE
[0.9.704] Editor crashes when using character mode

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#2212] opened 2020-02-07 23:54 UTC
[crashreport (49).log](https://github.com/Regalis11/Barotrauma/files/4173481/crashreport.49.log)
**Description**
Editor crashes sometimes when submarine file is loaded and you switch from character mode to edit mode after grabbing an item.

**Steps To Reproduce**
-Open editor
-Load submarine
-Switch to character mode
-Grab an item
-Switch to Edit mode

Stein reproduced this differently
-Put steel crate in crate shelf in character mode
-Click character mode icon again

**Version**
0.9.704 Unstable

**Comment by Regalis11** [comment] 2020-02-08 10:44
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/659a5cc9081bfca5fc5b60c84c18f49ca39a386f

**Comment by Rokvach** [comment] 2020-02-08 10:56
Tested, couldn't reproduce. Working correctly. Closing.

**Closed by Rokvach** 2020-02-08 10:56 UTC
Labels: Bug, Code, Crash
