### ISSUE TITLE
Multiple Tutorials Instead of One- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#644] opened 2018-08-11 15:32 UTC
Almost 3 years ago on youtube Regalis have mentioned he would possibly make more tutorials, than one. This request makes tutorial button be renamed to "tutorials". Before player completes "Getting Started" tutorial he will always receive warning about "Getting Started" being incompleted and will be advice to pick "getting Started", before selecting other. Player can still select other tutorials regardless of completing "Getting Started"

Already existing tutorial- Getting Started

New Tutorials:

Salvaging an Artifact- Player will be tasked in a beefy equipped tutorial shuttle to salvage skyholder artifact. He will learn how to navigate outside submarine and how to explore ruins. At some point player will have to dock to a submarine spawned out of nowhere. The shape of submarine's docking corner is so fitting, that docking is much easier, than in case of other submarines.

Medical Doctor- Some crew members are unconscious or injured. At some point player will have to learn crafting feature to get calyxanide in order to cure people from traitor medic's husk eggs. Traitor medic commited suicide and became husk. Player will have to fight him in middle of chaos using harpoon gun. Action takes place on tutorial (vellamo similar) submarine, due to it's corridors allowing player to dodge husk's attacks.

**Comment by Regalis11** [comment] 2018-08-11 15:58
This is pretty much how I've planned for the tutorials to work. There are going to be multiple tutorials, one is a "quickstart" tutorial similar to the current one that only teaches the basics, and in addition there are several additional ones that go into more detail on specific game mechanics.

I've also been thinking of gamifying the tutorials a bit more: completing a tutorial could earn you a badge/certificate that others can see in the multiplayer mode. It wouldn't only be a way to encourage players to complete the tutorials, but also a way to get a rough idea of a players skill level - someone with a medical certificate, advanced electrical engineering certificate and an advanced navigation certificate is more likely to know their shit compared to someone with only a "basic training certificate".

In any case, I think this is a duplicate of #8, if you have any further ideas please post them there.

**Closed by Regalis11** 2018-08-11 15:58 UTC
Labels: Gameplay-related, feature request

**Comment by Momiro** [comment] 2018-08-12 22:58
I like the training certificate idea. I think perhaps it would be a good idea for certain servers to lock out access levels or jobs from players who haven't completed their training...
