### ISSUE TITLE
Wrong Job Experience

### ISSUE THREAD

**Issue by Darknessel1** [Regalis11/Barotrauma#3947] opened 2020-09-29 21:20 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If someone is doing a certain job (e.g. repairing a battery) and gets healed during this task (e.g. apply a bandage on a burn) the medic will get experience in the job that the patient is doing.

**Steps To Reproduce**
Have someone repair something. He needs to have some damage (burn on arm).
Apply a bandage on the burnt area

**Version**
0.10.5.1 (Windows)

**Comment by Regalis11** [comment] 2020-09-30 13:25
I was not able to reproduce this: the medic seems to only gain medical skill as intended.

**Comment by Regalis11** [comment] 2020-11-12 14:10
No known steps to repro, closing

**Closed by Regalis11** 2020-11-12 14:10 UTC
Labels: Bug, Code, Need more info
