### ISSUE TITLE
Game_Crashes_On_Start

### ISSUE THREAD

**Issue by Dougal37** [Regalis11/Barotrauma#5441] opened 2021-04-05 21:00 UTC
**Description**
Game crash screen appears as soon as started. crash report below.

Operating_System:Linux-x86_64;
Nvidia_Driver:384.130;

Appreciate any asisstance. Been looking forward to trying your game.

﻿Barotrauma Client crash report (generated on 04/05/2021 21:39:06)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

To prevent further startup errors, installed mods will be disabled the next time you launch the game.

10248F6A58089EF65BF64DE3EADC2230

Game version 0.12.0.3 (ReleaseLinux, branch release, revision ea245a2f34)
Graphics mode: 1280x720 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized

System info:
    Operating system: Unix 4.8.0.53 64 bit
    GPU name: 
    Display mode: {Width:1280 Height:720 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Loading was interrupted due to an error. (Barotrauma.GameMain+LoadingException)
Target site: Void Update(Microsoft.Xna.Framework.GameTime)
Stack trace: 
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 791
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 654
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/SDL/SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 59

InnerException: Unable to load shared library 'freetype6' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libfreetype6: cannot open shared object file: No such file or directory
Target site: SharpFont.Error FT_Init_FreeType(IntPtr ByRef)
Stack trace: 
   at SharpFont.FT.FT_Init_FreeType(IntPtr& alibrary)
   at SharpFont.Library..ctor() in <DEV>/Libraries/SharpFont/Source/SharpFontShared/Library.cs:line 77
   at Barotrauma.ScalableFont..ctor(String filename, UInt32 size, GraphicsDevice gd, Boolean dynamicLoading, Boolean isCJK) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Fonts/ScalableFont.cs:line 80
   at Barotrauma.GUIStyle.LoadFont(XElement element, GraphicsDevice graphicsDevice) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GUI/GUIStyle.cs:line 339
   at Barotrauma.GUIStyle..ctor(XElement element, GraphicsDevice graphicsDevice) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GUI/GUIStyle.cs:line 219
   at Barotrauma.GUI.Init(GameWindow window, IEnumerable`1 selectedContentPackages, GraphicsDevice graphicsDevice) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GUI/GUI.cs:line 253
   at Barotrauma.GameMain.Load(Boolean isSeparateThread)+MoveNext() in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 453
   at Barotrauma.CoroutineManager.ExecuteCoroutineThread(CoroutineHandle handle) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 173
Last debug messages:
[04/05/2021 21:39:06] Coroutine "Load" has failed
[04/05/2021 21:39:06] Coroutine "Load" has thrown an exception {Unable to load shared library 'freetype6' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libfreetype6: cannot open shared object file: No such file or directory}
   at SharpFont.FT.FT_Init_FreeType(IntPtr& alibrary)
   at SharpFont.Library..ctor() in <DEV>/Libraries/SharpFont/Source/SharpFontShared/Library.cs:line 77
   at Barotrauma.ScalableFont..ctor(String filename, UInt32 size, GraphicsDevice gd, Boolean dynamicLoading, Boolean isCJK) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Fonts/ScalableFont.cs:line 80
   at Barotrauma.GUIStyle.LoadFont(XElement element, GraphicsDevice graphicsDevice) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GUI/GUIStyle.cs:line 339
   at Barotrauma.GUIStyle..ctor(XElement element, GraphicsDevice graphicsDevice) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GUI/GUIStyle.cs:line 219
   at Barotrauma.GUI.Init(GameWindow window, IEnumerable`1 selectedContentPackages, GraphicsDevice graphicsDevice) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GUI/GUI.cs:line 253
   at Barotrauma.GameMain.Load(Boolean isSeparateThread)+MoveNext() in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 453
   at Barotrauma.CoroutineManager.ExecuteCoroutineThread(CoroutineHandle handle) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 173
[04/05/2021 21:39:06] Playing the splash screen "Content/SplashScreens/Splash_UTG.webm" failed. {Unable to load shared library 'webm_mem_playback_x64.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libwebm_mem_playback_x64.so: cannot open shared object file: No such file or directory}
   at Barotrauma.Media.Video.Internal.loadVideo(String filename)
   at Barotrauma.Media.Video..ctor(GraphicsDevice graphicsDevice, SoundManager soundManager, String filename) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Media/Video.cs:line 83
   at Barotrauma.Media.Video.Load(GraphicsDevice graphicsDevice, SoundManager soundManager, String filename) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Media/Video.cs:line 74
   at Barotrauma.LoadingScreen.DrawSplashScreen(SpriteBatch spriteBatch, GraphicsDevice graphics) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GUI/LoadingScreen.cs:line 330
[04/05/2021 21:39:06] Attempting to open ALC device "Built-in Audio Digital Stereo (IEC958)"
[04/05/2021 21:39:05] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[04/05/2021 21:39:04] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[04/05/2021 21:39:03] Logged in as Dougie37 (SteamID STEAM_1:0:37787483)

**Comment by Regalis11** [comment] 2021-04-06 07:19
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3225

**Closed by Regalis11** 2021-04-06 07:19 UTC
