### ISSUE TITLE
Can't read name of an item in linked container for fabricator

### ISSUE THREAD

**Issue by cola98765** [Regalis11/Barotrauma#5052] opened 2021-02-13 12:08 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When container is linked to fabricator and you click on the fabricator, items in the container will not focus (you can still move them, but will not say what they are, or what is inside eg. storage containers).
It also works vice versa. When you click on container, you can't focus on items in fabricator.

**Steps To Reproduce**
-Spawn fabricator and cabinet
-Link them and turn on "display side by side when linked"
-Put some items in to not see their name

**Version**
v12.0.2.0 (The Cave Update) on Windows

**Additional information**
Issue appears in proper game, during test run, and in editor.

**Comment by Regalis11** [comment] 2021-02-15 09:03
Seems to be caused by the same bug as Regalis11/Barotrauma#5008, closing as a duplicate

**Closed by Regalis11** 2021-02-15 09:03 UTC
