### ISSUE TITLE
ItemSpawnInfo.SpawnPositionType.ThisInventory Doesn't Work With Stacking

### ISSUE THREAD

**Issue by Jlobblet** [Regalis11/Barotrauma#5997] opened 2021-06-07 14:33 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When using a `StatusEffect` to spawn an item inside an item's inventory, the presence of an item will stop it working.
Test case: [StableTestMod.zip](https://github.com/Regalis11/Barotrauma/files/6609793/StableTestMod.zip)

**Steps To Reproduce**
1. Install test mod, `spawnitem "Example Revolver" inventory`.
2. Use the item. Note that a revolver round is successfully spawned.
3. Use the item again. Note that no revolver round is spawned.

**Version**
0.13.3.11 Windows 10

**Additional information**
Relevant code:
https://github.com/Regalis11/Barotrauma/blob/3f324b14e8d815955391a1ba97e119bbb1913a6f/Barotrauma/BarotraumaShared/SharedSource/StatusEffects/StatusEffect.cs#L1275-L1291
https://github.com/Regalis11/Barotrauma/blob/3f324b14e8d815955391a1ba97e119bbb1913a6f/Barotrauma/BarotraumaShared/SharedSource/Networking/EntitySpawner.cs#L59-L97
https://github.com/Regalis11/Barotrauma/blob/3f324b14e8d815955391a1ba97e119bbb1913a6f/Barotrauma/BarotraumaShared/SharedSource/Items/Inventory.cs#L57-L70

**Comment by Regalis11** [comment] 2021-06-07 14:55
Could not reproduce in the latest unstable version, seems to be fixed.

**Comment by Jlobblet** [comment] 2021-06-07 15:13
I can still reproduce it on Unstable 0.1400.3.0. Tried validating files and only configuration files were reacquired, and bug appears to still be present.

**Comment by Ek-Videogames** [comment] 2021-06-11 07:08
I believe this was already addressed - ala issue #4590 
but may have only been partially fixed or the bug re-introduced this unstable.

> Fixed in [Regalis11/Barotrauma-development@f6473bd](https://github.com/Regalis11/Barotrauma-development/commit/f6473bd3a3b071bd6e9bd37ed696b76138a58d90)

**Comment by Rokvach** [comment] 2021-06-23 06:57
Tested, the example revolver seems to only spawn in a single round, so this seems to be still bugged if the expectation is for the revolver to spawn in a new round each time you fire it? Not an issue if the round gets used when you fire a weapon and a new round gets replaced with the fired one, only if the expectation is for it to only spawn in new rounds and not "use" the existing ones. 

Moving to Misc.

**Comment by Regalis11** [comment] 2021-07-05 08:57
> Not an issue if the round gets used when you fire a weapon and a new round gets replaced with the fired one

Looking at the config, this seems to be the intended behavior. Closing

**Closed by Regalis11** 2021-07-05 08:57 UTC
Labels: Bug, Code, Modding
