### ISSUE TITLE
Players spawn in with wrong job, even if there is plenty of available room

### ISSUE THREAD

**Issue by ghHavick** [Regalis11/Barotrauma#7119] opened 2021-11-01 14:10 UTC
**Description**
After starting a campaign mission with an arbitrary amount of players with different jobs, even with plenty of room for the role chosen on a P2P connection, the job I have as my first and only preference is seemingly ignored, and I am instead given some other, perhaps random, role.

**Steps To Reproduce**
- Start a new Steam P2P hosted campaign
- Have one player's first priority job preference be captain
- All other players can have priorities set up in any order they like
- One player sets a single job preference
- Check if it matches in game

**Version**
Release v0.15.12.0 (Among the Ancients)
Windows

**Comment by Regalis11** [comment] 2021-11-01 14:22
Duplicate of https://github.com/Regalis11/Barotrauma/issues/6932

**Closed by Regalis11** 2021-11-01 14:22 UTC
