### ISSUE TITLE
"Mission equality check failed" as host after restarting round

### ISSUE THREAD

**Issue by zkxs** [Regalis11/Barotrauma#7834] opened 2021-12-17 15:54 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
1. I start a private multiplayer game for testing purposes. I am the only one in it.
2. I grab a random cargo mission and undock.
3. After the new round starts I go AFK for about 20 minutes, and come back dead with the round failed.
4. I hit the continue button and immediately crash back to the main menu with the error below:

```log
Error while reading a message from server. {Mission equality check failed. Mission count doesn't match the server (server: 0, client: 1)}
   at Barotrauma.Networking.GameClient.ReadStartGameFinalize(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 975
   at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 870
   at Barotrauma.Networking.SteamP2POwnerPeer.HandleDataMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2POwnerPeer.cs:line 0
   at Barotrauma.Networking.SteamP2POwnerPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2POwnerPeer.cs:line 227
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 641
```

What makes this bizarre is I was the host *and* the only player, so a desync is rather unexpected.

**Steps To Reproduce**
Unfortunately I cannot reproduce this, but I grabbed a stack trace from the one time it did happen.

**Version**
Windows v0.15.22.1

**Comment by Regalis11** [comment] 2022-01-03 15:17
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3819

**Closed by Regalis11** 2022-01-03 15:17 UTC
