### ISSUE TITLE
AI Gunners don't target ice spires

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#4451] opened 2020-12-09 21:11 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
AI gunners don't target ice spires.

**Steps To Reproduce**
set an AI on guns
Approach ice spire
collide with ice spire
sink and cry

**Version**
0.11.0.9

**Additional information**

**Comment by Regalis11** [comment] 2020-12-10 08:46
This is not a bug, just unimplemented.

**Comment by itchyOwl** [comment] 2020-12-11 16:28
Should they? And if they should, are there any restrictions/rules for it? Like shoot only when moving towards them? It could be a waste of ammunition, if the bots just always shot the spires.

**Comment by Tsunder** [comment] 2020-12-11 18:40
A human player on the guns would be told to shoot at the ice spires, so it would also be expected to have the AI shoot at it.

Otherwise, a player would have to travel/switch control to the bot and do it manually.

I think wasting a little ammunition would generally be preferred over hull breaches and a sinking sub.

Shoot at the ice spire until it's destroyed? Only shoot if it's close to the sub? (20m to coilgun?)

**Comment by Regalis11** [comment] 2020-12-15 17:09
I'm a bit on the fence about this: thinking about it from the perspective of realism, a bot should be able to shoot them, but there's the question of whether we want them to be something the bots automatically take care of without the player having to worry about them at all. Wasting ammo is also a good point, since it's usually possible to navigate around the spires without having to destroy them.

**Comment by ezjamsen** [comment] 2020-12-15 17:31
There's not a lot of significant negative consequences to allowing bots to shoot spires on sight, except for perhaps potentially making spires something the player never really sees or experiences because they're always shot out of the way before they ever need to be dealt with, but not all subs have forward mounted guns. I'd be inclined to let them shoot, perhaps with some prioritization so they prefer creatures to spires if offered both equally.

**Comment by itchyOwl** [comment] 2020-12-16 11:31
I'd say we should make bots shoot the sprites, but need to define the boundaries and rules for it. Prioritization is a good point too. So how about this: always shoot a spire if the sub is going roughly towards it, unless there's a monster to shoot at?

**Comment by ezjamsen** [comment] 2020-12-16 14:57
sounds right.

**Comment by Qlay** [comment] 2021-01-02 01:13
Maybe allow the Captain to call out targets/zones of interest on the command console, that bots can react too by shooting a few bursts in that general direction?
Bots are already pretty good behind the guns and allowing them to auto target and shoot ice will remove a lot of challenge and kinda make them moot.

**Comment by itchyOwl** [comment] 2021-01-18 15:54
Implemented in Regalis11/Barotrauma-development@e62f8a5.

**Comment by Rokvach** [comment] 2021-01-18 16:23
I think the shooting range could be higher when AI shoots the ice spires. 
I know that they wouldn't be able to see them in the periscope if the range was changed, but that's also how it goes with players too, they shoot at the direction captain tells them to. 

Tried to test how autopiloting a sub goes with bots on the guns, didn't make it the whole level with Dugong but that was only because Dugong doesn't have a front facing gun. But this is still a lot better than it was previously, so I don't think we need to do anything about this in the AI point of view, except maybe inform the player somehow that the ice spire is out of reach and the sub on autopilot can't continue. 
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/69df4b9e-fa7c-4620-af9a-7de4388f14ca)

**Comment by Rokvach** [comment] 2021-01-19 19:20
Working correctly, still needs some balancing but no actual issues found. Closing.

**Closed by Rokvach** 2021-01-19 19:20 UTC
Labels: Code, Feature request

**Comment by llamerr** [comment] 2022-05-25 12:56
I'm preparing to fight Hammerhead (or whatever it's called), assigning bot to railgun and... it wastes all ammo on Ice Spires. Nice job... Why there is no command for bots to "shoot on command"? So I can assign it to railgun, but it only stays there and does not shoot. So I can switch to bot and shoot whenever I want it without it wasting any ammunition?
