### ISSUE TITLE
Infinite husk eggs

### ISSUE THREAD

**Issue by Lefttroll** [Regalis11/Barotrauma#3516] opened 2020-08-06 11:49 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
You can replenish Husk Eggs durability with crafting Calyxanide and then deconstructing

**Steps To Reproduce**
Step 1: find used husk eggs and make sure you have ingridients for crafting Calyxanide
Step 2: Craft Calyxanide
Step 3: Deconstruct it
Step 4: ?????????
Step 5: PROFIT
**Version**
Windows, Game version 0.10.4.0 (ReleaseWindows, branch release, revision 20132d25fb)

**Additional information**
Originally was found by Fire_Cast#5343

**Comment by mygamingaccount** [comment] 2020-08-17 14:53
The problem is with the fabrication / deconstruction recipes.

Calyxanide takes 0.2 calyxeggs to make
Upon deconstruction it gives you 1.0 calyxeggs

**Comment by danielasteljoki** [comment] 2020-08-24 11:25
There were some issues with the deconstruct recipe, which caused deconstructed eggs to have the incorrect condition. Removed them altogether from the recipe in bd7afea.

**Comment by EtiamNullam** [comment] 2020-08-24 12:32
@danielasteljoki does that mean we won't be able to reclaim eggs back from calyxanide at all? That sounds like a big change and not very consistent considering we can extract poisons from most (all?) other antidotes.

**Comment by danielasteljoki** [comment] 2020-08-24 13:12
@EtiamNullam It does mean that. We thought it didn't make sense to be able to "re-construct" the eggs from calyxanide. It also makes it more difficult to acquire husk eggs and allows us to make calyxanide more common.

**Comment by Rokvach** [comment] 2020-08-31 05:45
No issues, closing.

**Closed by Rokvach** 2020-08-31 05:45 UTC
Labels: Bug, Design
