### ISSUE TITLE
Collider- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#776] opened 2018-09-07 14:13 UTC
Collider is an alternative kind of hull in barotrauma, that is to be put outside submarine in order to prevent some of it's exterior elements from going through rocks and other structures. Collider can be optionally set to prevent players and creatures from passing too. Collider is not considered to be submarines's hull, so it will always be filled with water, which's pressure will crush players and it won't determine submarine's submerging.

**Comment by Regalis11** [comment] 2018-09-07 15:10
Imo this is almost the same as #771, and I'd use the same arguments against implementing it.

I might be missing something here, but what is the problem you're trying to solve with this?

**Comment by rico6822** [comment] 2018-09-07 19:20
Collider in this thread works like hull, but for outside of submarine and does not affect descending. It's only purpose is to prevent background from going inside rocks, submarines or ruins.

**Comment by BlueTheKing** [comment] 2018-09-07 19:37
> It's only purpose is to prevent background from going inside rocks, submarines or ruins.

Don't use backgrounds on the outside of your sub if that's a problem or just use regular walls.

**Comment by Regalis11** [comment] 2018-09-07 19:38
Ok, so this is essentially a duplicate of #771. I do see the reasoning behind this, there could be a valid use for colliders on background walls on some subs, but still I feel like it would cause more problems than it solves.

**Closed by Regalis11** 2018-09-07 19:38 UTC
