### ISSUE TITLE
[Factions] Particle Start/Middle/End color doesn't work

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10839] opened 2022-12-29 19:33 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Particles have the option to use a 3 colors at the start, middle and end of their animation

For some reason, this stopped working in the factions build
It worked on stable, switched to factions then back to stable and still doesnt work despite relaunching the game multiple times and testing inside and outside subeditor.

![image](https://user-images.githubusercontent.com/73229309/210003626-3aa3e01f-ca09-49b3-859d-eb24b2f2ed04.png)

Live build

https://user-images.githubusercontent.com/73229309/210002141-8a57d80f-4b3b-4856-8a9a-541f2511b99c.mp4

Factions branch

https://user-images.githubusercontent.com/73229309/210002129-21c28312-aa79-4605-b1ce-0009ed6b8b77.mp4

**The bike horn I tested with (removed conditional)**

```xml
  <Item name="" identifier="bikehorn" category="Misc" tags="smallitem,hornitem" scale="0.5" cargocontaineridentifier="metalcrate" description="HONK">
    <PreferredContainer primary="crewcab" spawnprobability="0.05" notcampaign="true"/>
    <PreferredContainer secondary="wreckcrewcab,abandonedcrewcab" spawnprobability="0.05"/>
    <Price baseprice="1" canbespecial="false">
      <Price storeidentifier="merchantoutpost" minavailable="1"/>
      <Price storeidentifier="merchantcity" minavailable="1"/>
      <Price storeidentifier="merchantresearch" sold="false" />
      <Price storeidentifier="merchantmilitary" sold="false" />
      <Price storeidentifier="merchantmine" sold="false" />
    </Price>
    <InventoryIcon texture="Content/Items/InventoryIconAtlas.png" sourcerect="769,385,64,64" depth="0.55" origin="0.5,0.5" />
    <Sprite texture="Content/Items/Misc/Misc.png" sourcerect="101,45,53,22" depth="0.55" />
    <Body width="50" height="20" density="15" />
    <Holdable slots="Any,RightHand,LeftHand" aimpos="100,0" handle1="-15,-3" msg="ItemMsgPickUpSelect" />
    <StatusHUD drawhudwhenequipped="true" overlaycolor="0,0,0,255" range="3000" thermalgoggles="false" showdeadcharacters="false" showtexts="false"/>
    <RangedWeapon reload="2">
      <Sound file="Content/Items/Weapons/honk.ogg" type="OnUse" />
<!-- 	  honkolocation stuff -->
      <StatusEffect type="OnUse" target="This,Character" thermalgoggles="true" setvalue="true" duration="0.3">
		<ParticleEmitter particle="SonarFloraWave" AngleMax="360" ScaleMultiplier="5,5" ParticlesPerSecond="3" ColorMultiplier="255,255,255,255" StartColor="255,255,255,100" MiddleColor="255,255,255,255" EndColor="255,0,0,255" UseMiddleColor="True" />
<!-- 		<Conditional honkolocation="gt 0" /> -->
      </StatusEffect>
      <StatusEffect type="OnUse" target="This,Character" thermalgoggles="false" setvalue="true" delay="1.1"/>
    </RangedWeapon>
    <aitarget soundrange="1000" fadeouttime="5" />
    <Upgrade gameversion="0.10.0.0" scale="0.5" />
  </Item>


```

I tried using a modified sky artifact to generate particles, but the game disregards the color change

```xml
  <Item name="" identifier="skyholderartifact" category="Alien" Tags="alien,alienartifact" sonarsize="30" scale="0.5" impactsoundtag="impact_metal_heavy" allowsellingwhenbroken="true" hideconditionbar="true">
    <Sprite texture="Content/Items/Alien/AlienRuins_Items.png" depth="0.6" sourcerect="630,0,82,108" origin="0.5,0.5" />
    <Body radius="45" density="50" friction="0.95" />
    <Holdable slots="RightHand+LeftHand" holdpos="30,-15" handle1="0,10" handle2="0,-10" msg="ItemMsgPickUpSelect">
      <StatusEffect type="Always" target="This,Hull" oxygen="-50000.0">
        <Conditional hastag="neq artifactcontainer" targetcontainer="true" />
        <ParticleEmitter particle="skyholderfx2" anglemax="360" distancemin="100" distancemax="300" velocitymin="-700" velocitymax="-1200" particlespersecond="100" StartColor="0,0,255,100" MiddleColor="0,255,0,255" EndColor="255,0,0,255" UseMiddleColor="True" />
        <ParticleEmitter particle="skyholderfx" anglemax="360" particlespersecond="2" />
        <sound file="Content/Items/Alien/AlienArtifactLoop1.ogg" range="500.0" loop="true" />
      </StatusEffect>
    </Holdable>
  </Item>
```

### Version

Faction/endgame test branch

**Comment by Regalis11** [comment] 2022-12-30 13:58
I'm afraid I could not reproduce the issue. 

One problem I see in the XML is that the color is defined in the particle emitter. There are no properties StartColor, `MiddleColor`, `EndColor` or `UseMiddleColor` in the particle emitters - these are properties of the particle prefab itself. So these example XMLs don't seem to modify the color in either the live version of the faction branch, but modifying the properties of the particle prefab seems to work as expected in both.

**Comment by ubertpendragon** [comment] 2022-12-31 12:58
If you can't modify these properties in XML then the fact that I saw my modified particle in action despite not using a custom particle comes from `particleeditor`

If you modify a particle there even without saving the effect will still show up as modified in game

**Comment by Regalis11** [comment] 2023-01-09 09:55
No known steps to repro, closing

**Closed by Regalis11** 2023-01-09 09:55 UTC
Labels: Bug, Need more info
