### ISSUE TITLE
Spamming ragdoll key bind causes the collider to ascend.

### ISSUE THREAD

**Issue by CommanderMark** [Regalis11/Barotrauma#1278] opened 2019-03-14 19:13 UTC
Best way to reproduce this is to bind the ragdoll key to mousewheel and go nuts, though I've managed to replicate it with the spacebar if I spam fast enough. Seems to also let you clip through walls.

**Comment by Regalis11** [comment] 2019-03-14 22:03
Most likely caused by #904

**Comment by Regalis11** [comment] 2019-03-18 21:59
Fixed in v0.8.9.6

**Closed by Regalis11** 2019-03-18 21:59 UTC
Labels: bug
