### ISSUE TITLE
Unstable - Crash when picking up artifact from ruin holder

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#2542] opened 2020-03-31 01:43 UTC
**Description**
Title

**Steps To Reproduce**
I grabbed non-mission artifact from a holder in ruins
**Version**
Unstable, P2P hosted server
**Additional information**
Again, 2 crash logs
[crashreport (107).log](https://github.com/Regalis11/Barotrauma/files/4406258/crashreport.107.log)
[crashreport (108).log](https://github.com/Regalis11/Barotrauma/files/4406259/crashreport.108.log)

**Comment by Regalis11** [comment] 2020-03-31 07:27
Duplicate of #2511 and #2512

**Closed by Regalis11** 2020-03-31 07:27 UTC
Labels: Bug, Code, Crash
