### ISSUE TITLE
[Unstable 13.0.2] No tunnel/exit at the end of Natural Formation level

### ISSUE THREAD

**Issue by mrjpjr** [Regalis11/Barotrauma#5256] opened 2021-03-15 19:09 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
There is no tunnel or way to exit at the end of the Natural Formation I am currently at.

**Steps To Reproduce**
- Load save file
- Go to the end of the level
There will be no tunnel or way to exit

**Version**
Unstable 0.1300.0.2, revision f18186e1c6
Windows 10

**Additional information**

- save file: [Unstable 13.0.1 Malaco SP Campaign.save.zip](https://github.com/Regalis11/Barotrauma/files/6143845/Unstable.13.0.1.Malaco.SP.Campaign.save.zip)
- This SP campaign started in Unstable 13.0.1, so I wonder if it is becasue of the map gen changes between 0.1 and 0.2?

**Comment by Regalis11** [comment] 2021-03-16 08:52
I'm afraid I couldn't reproduce this. Is this the correct save file? It's saved in an outpost level, and I went through all of the adjacent connections leading to an empty location (Powys, Vorta, Autonoe Linea) but couldn't find the level where the issue occurs.

**Comment by mrjpjr** [comment] 2021-03-16 11:52
My apologies. I was not clear enough in my steps.

- Head to Powys
![20210316070652_1](https://user-images.githubusercontent.com/58775950/111302481-d7f6f800-8629-11eb-8c16-40e787c9960b.jpg)

- When you get to the end of that level, you will see this:
![20210316074541_1](https://user-images.githubusercontent.com/58775950/111304068-a67f2c00-862b-11eb-8207-69d1751406b4.jpg)
![20210316073035_1](https://user-images.githubusercontent.com/58775950/111302588-f957e400-8629-11eb-9572-f1985a80e1a5.jpg)

- There is no 'tunnel' through which to proceed as heading to the right takes you into hypercurrents and the other directions are a part of the level (as seen in the video linked below)
https://www.dropbox.com/s/qhc1njscwhp03i0/Barotrauma%202021-03-16%2007-24-43.mp4?dl=0

**Comment by Regalis11** [comment] 2021-03-17 09:15
Thank you! Fixed in the dev branch.

**Comment by Rokvach** [comment] 2021-03-25 07:08
Tested, no issues. Closing.

**Closed by Rokvach** 2021-03-25 07:08 UTC
Labels: Bug, Code
