### ISSUE TITLE
[Feedback] Berilia ballast pumps sucks Monstrously Bad.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2320] opened 2020-02-17 01:12 UTC
The ballast pumps sucks Monstrously Bad. The ballast pumps has a max flow of 100, which is equal to all the small pumps that are around the sub. I even went as far having the crew rewire the bilges to help with the affecting the ascent/descent.

The bottom engine room is also bad for Bots as well since there's lack of waypoint connection there.

**Version**
~0.9.7 - 630ff935f

**Comment by danielasteljoki** [comment] 2020-02-20 13:49
Pumps are slow mostly by design, a sub that size shouldn't handle very well. That being said, I buffed the pumps a little to make it hopefully less frustrating to operate. Connected the waypoints too (in dev repo).

**Comment by Rokvach** [comment] 2020-02-25 11:34
No issues, closing.

**Closed by Rokvach** 2020-02-25 11:34 UTC
Labels: Design
