### ISSUE TITLE
Oddities with the Nav Terminal and Relays, along with undocking.

### ISSUE THREAD

**Issue by HalfdeadKiller** [Regalis11/Barotrauma#1728] opened 2019-06-29 18:14 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
It's hard to describe. In the Cyclops 3.4 you can see that I have ballast pumps connected to a blue relay by the helm, but they never receive the velocity_y. In Challenger_pod you will also notice that undocking using the nav terminal doesn't correctly trigger the automated undocking circuit. But if you hook a button to the And gates, on the same signals of the nav terminal, and undock using the button, the circuit will funciton properly and shut the door first, then undock.

**Steps To Reproduce**
The description is pretty much the steps to reproduce I think.

**Version**
Barotrauma v0.9.0.7 Windows 10

**Additional information**
Submarines included in Zip.
[Example Submarines.zip](https://github.com/Regalis11/Barotrauma/files/3342176/Example.Submarines.zip)

**Comment by Regalis11** [comment] 2019-07-09 10:53
The relays don't work because they're broken (their condition is set to 0). Not sure how that has happened, maybe you set it to 0 by accident at some point when editing some of the other properties?

I couldn't reproduce the docking issue - the hatch closes before undocking.

**Comment by HalfdeadKiller** [comment] 2019-07-09 16:58
Yeah I must have made it 0 when wiring. The GUI bug where clicking on a component in wiring mode doesn't bring up that specific components GUI. Might have gotten stuff mixed up.

As far as the docking thing goes. It definitely doesn't work right in multiplayer. I've made a new test submarine that has a Nav Terminal and a Button tied to a default Automated Docking Hatch sub assembly. The Nav Terminal undock will flood the submarine, undock, and then close the door, while the button will close the door, and undock with zero leaks.

In singleplayer the circuit works as intended from the Nav Terminal.
[MP Docking Bug.zip](https://github.com/Regalis11/Barotrauma/files/3374055/MP.Docking.Bug.zip)

**Comment by HalfdeadKiller** [comment] 2019-07-09 17:02
This other post is more specific, but lacks my example submarine.
https://github.com/Regalis11/Barotrauma/issues/1743

**Comment by Regalis11** [comment] 2019-10-29 11:13
Fixed in v0.9.4.0

**Closed by Regalis11** 2019-10-29 11:13 UTC
Labels: Bug, Code, Need more info
