### ISSUE TITLE
Crew list when hiring does not sync correctly on reconnect

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#12633] opened 2023-09-07 10:42 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In looking into another issue, I noticed clients who rejoin a round do not sync correctly any hires purchased during that round from an outpost. the end round text will be incorrect (As well as the HR Manager not showing the new crew), No issues when going to the next round however.

This doesn't really impact the game in any harsh way or break sync and its likely rare for anyone to notice (Unless multiple players are all buying crew in the same round, after a reconnect).

### Reproduction steps

1. Start a multiplayer campaign with 2 clients
2. Have one client purchase any AI crew
3. Rejoin the server with another client
4. Find the second client did not sync the first clients purchase (They are gone from the list, but not in the round summary or HR manager crew list)

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted using a dedicated server

### Version

Other

### -

Release/traitor-update commit https://github.com/Regalis11/Barotrauma-development/commit/0cfff8807604f3fa690ee74dad4387cff4c7f9ce

### Which operating system did you encounter this bug on?

Windows

**Comment by Jasontti** [comment] 2024-01-19 15:49
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4486/commits/2b9311d6d70ade2ab5b064a1dae22490ba0da125

Used 2 clients on listen server
Bought and sold crew members
Joined and left before and after transactions
HR list is accurately syncronized
No issues when hiring, leaving outpost and then another client joining
Quick test in SP

No actual issues found

Only thing i noticed was "new crewmembers" dialog was shown twice to the host, once after hiring and second time when loading in to next round, but could not reproduce it.
![image](https://github.com/Regalis11/Barotrauma/assets/8488224/9ae931dc-b929-490e-a58b-381f11c6bc68)

Closing ticket

**Closed by Jasontti** 2024-01-19 15:49 UTC
Labels: Bug, Code, Networking
