### ISSUE TITLE
Game crashes when trying to host a multiplayer server

### ISSUE THREAD

**Issue by NonRidiculousAdjective** [Regalis11/Barotrauma#8330] opened 2022-02-20 14:42 UTC
- I have searched the issue tracker to check if the issue has already been reported.

**Description**
When I try to host a new game in multiplayer, It crashes. In my case, I set my game as roleplay and set the maximum of 4 players.

**Steps To Reproduce**
Host a server and set the game mode as roleplay and set a maximum of 4 players.

**Version**
Vanilla 0.9

**Additional information**
Here is the crash report: (although _Intel(R) HD Graphics 620_ is my integrated GPU, I actually use _Radeon(TM) R7 M465_)
```
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.MainMenuScreen
SteamManager initialized
Client (Round hadn't been started)


System info:
    Operating system: Microsoft Windows NT 10.0.18363.0 64 bit
    GPU name: Intel(R) HD Graphics 620
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: ChildServerRelay readTask did not run to completion: status was WaitingForActivation. (System.Exception)
Target site: Int32 ReadIncomingMsgs()
Stack trace: 
   at Barotrauma.Networking.ChildServerRelay.ReadIncomingMsgs() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 114
   at Barotrauma.Networking.ChildServerRelay.<UpdateRead>g__readBytes|27_0(Span`1 readTo) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 143
   at Barotrauma.Networking.ChildServerRelay.UpdateRead() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 154
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()


Last debug messages:
[20/02/2022 15:26:34] Exiting...
[20/02/2022 15:23:41] Attempting to open ALC device "OpenAL Soft on Speakers (Razer USB Sound Card)"
[20/02/2022 15:22:13] OpenAL Soft on Internal Microphone (Conexant ISST Audio) 56
[20/02/2022 15:22:13] OpenAL Soft on Microphone (Razer USB Sound Card) 48
[20/02/2022 15:20:47] (Msg) SDR RelayNetworkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[20/02/2022 15:20:47] (Msg) Ping location: vie=7+0,waw=41+4/17+0,fra=18+1/19+0,ams=24+2/23+1,par=26+2/28+0,lhr=37+3/29+2,sto=49+4/38+0,sto2=50+5/38+0,mad=46+4/46+2,iad=103+10/104+0,sgp=178+17/179+17,gru=212+21
[20/02/2022 15:20:47] (Msg) Ping measurement completed
[20/02/2022 15:20:46] (Verbose) Communications with routing cluster 'dfw' established.
[20/02/2022 15:20:46] (Debug) Destroying relay 'dfw#81 (155.133.253.39:27049)' because initial_ping_timeout
[20/02/2022 15:20:44] (Warning) SteamNetworkingSockets lock held for 5.3ms.  (Performance warning.)  ServiceThread,ThinkPingProbes,CreateServerDataForCluster(x11),SendUDPacket(x10),EnsureDataCenterRoutesValid
This is usually a symptom of a general performance problem such as thread starvation.
[20/02/2022 15:20:44] (Warning) SteamNetworkingSockets lock held for 5.8ms.  (Performance warning.)  ServiceThread,ThinkPingProbes,CreateServerDataForCluster(x11),SendUDPacket(x10),EnsureDataCenterRoutesValid
This is usually a symptom of a general performance problem such as thread starvation.
[20/02/2022 15:20:44] (Verbose) Communications with routing cluster 'seo' established.
[20/02/2022 15:20:44] (Verbose) Communications with routing cluster 'tyo1' established.
[20/02/2022 15:20:44] (Verbose) Communications with routing cluster 'syd' established.
[20/02/2022 15:20:44] (Verbose) Communications with routing cluster 'tyo' established.
[20/02/2022 15:20:44] (Verbose) Communications with routing cluster 'maa' established.
[20/02/2022 15:20:44] (Verbose) Communications with routing cluster 'sgp' established.
[20/02/2022 15:20:44] (Verbose) Communications with routing cluster 'bom' established.
[20/02/2022 15:20:43] (Verbose) Communications with routing cluster 'scl' established.
[20/02/2022 15:20:43] (Verbose) Communications with routing cluster 'lim' established.
[20/02/2022 15:20:43] (Verbose) Communications with routing cluster 'jnb' established.
[20/02/2022 15:20:43] (Verbose) Communications with routing cluster 'hkg' established.
[20/02/2022 15:20:43] (Verbose) Communications with routing cluster 'sea' established.
[20/02/2022 15:20:43] (Verbose) Communications with routing cluster 'lax' established.
[20/02/2022 15:20:43] (Verbose) Communications with routing cluster 'eze' established.
[20/02/2022 15:20:43] (Verbose) Communications with routing cluster 'waw' established.
[20/02/2022 15:20:43] (Verbose) Communications with routing cluster 'sto2' established.
[20/02/2022 15:20:43] (Verbose) Communications with routing cluster 'sto' established.
[20/02/2022 15:20:43] (Verbose) Communications with routing cluster 'ord' established.
[20/02/2022 15:20:43] (Verbose) Communications with routing cluster 'gru' established.
[20/02/2022 15:20:43] (Verbose) Communications with routing cluster 'vie' established.
[20/02/2022 15:20:43] (Verbose) Communications with routing cluster 'dxb' established.
[20/02/2022 15:20:43] (Verbose) Communications with routing cluster 'mad' established.
[20/02/2022 15:20:43] (Verbose) Communications with routing cluster 'lhr' established.
[20/02/2022 15:20:43] (Verbose) Communications with routing cluster 'par' established.
[20/02/2022 15:20:43] (Verbose) Communications with routing cluster 'iad' established.
[20/02/2022 15:20:43] (Verbose) Communications with routing cluster 'atl' established.
[20/02/2022 15:20:43] (Verbose) Communications with routing cluster 'fra' established.
[20/02/2022 15:20:43] (Verbose) Communications with routing cluster 'ams' established.
[20/02/2022 15:20:43] (Msg) SDR RelayNetworkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[20/02/2022 15:20:43] (Msg) Performing ping measurement
[20/02/2022 15:20:43] (Msg) Got SDR network config.  Loaded revision 372 OK
[20/02/2022 15:20:43] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[20/02/2022 15:19:35] Attempting to open ALC device "OpenAL Soft on Speakers (THX Spatial Audio)"
[20/02/2022 15:19:34] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[20/02/2022 15:19:33] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[20/02/2022 15:19:33] Logged in as NonRidiculousAdjective (SteamID STEAM_1:1:194217593)
```

**Comment by Regalis11** [comment] 2022-02-21 08:27
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7783

**Closed by Regalis11** 2022-02-21 08:27 UTC
Labels: Bug, Code, Crash
