### ISSUE TITLE
[0.9.7] Coilgun bolts aren't fired from the coilguns at certain angles

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2362] opened 2020-02-24 14:55 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When shooting a coilgun, sometimes certain angles at various rotations doesn't eject from the coilgun and you hear the hit noise of the bolt hitting the shell or glass, whatever is closer, but no damage to the structure. This doesn't happen in 0.9.6.

https://media.discordapp.net/attachments/668819422919524352/681514128950558753/Giffy.gif

Here's the coilgun position and surrounding wall from the gif.
![Capture](https://user-images.githubusercontent.com/5086682/75162864-3afab180-56ec-11ea-8822-935f5f3d49c4.PNG)

Here's another set:

![Untitled](https://user-images.githubusercontent.com/5086682/75163203-d55af500-56ec-11ea-8174-710a82f850f5.png)
![Capture](https://user-images.githubusercontent.com/5086682/75163206-d724b880-56ec-11ea-8f68-741f5a850f94.PNG)

**Version**
0.9.7

**Comment by Udrakan** [comment] 2020-02-24 19:07
Can confirm, happens on vanilla subs too
![image](https://user-images.githubusercontent.com/59519434/75182701-3ad8d100-5741-11ea-9bff-59d233f51a72.png)
Orca front gun, no shots are leaving the barell, hull impact sounds

**Comment by Regalis11** [comment] 2020-02-26 18:45
Caused by https://github.com/Regalis11/Barotrauma-development/issues/1425, need to improve the raycast logic to prevent this from happening

**Comment by Regalis11** [comment] 2020-02-27 17:56
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/041beb23052937f54647f45e0a65836f8f4ac670

**Comment by Rokvach** [comment] 2020-03-16 08:00
Tested, haven't noticed any issues. Closing.

**Closed by Rokvach** 2020-03-16 08:00 UTC
Labels: Bug, Code
