### ISSUE TITLE
[Unstable 0.17.4.0] Broken save file prevents you from hosting a multiplayer campaign (Pipe is broken)

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8626] opened 2022-03-26 08:28 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I was hosting a heavily modded (100+) server during Unstable testing and while trying to load a new campaign save the server crashed with "Pipe is broken" crash and a massive error prompt came up after that.

Restarted the server and whenever I selected campaign mode the lobby just broke. For players trying to join, it showed as if there were no players on the server, the lobby crewlist was also shown empty and whatever action I tried to do in the lobby didn't register.

The same kept happening regards to which build I was on (stable, unstable, dev) until I found out that removing the save we tried to load from the multiplayer saves folder fixed it.  

The lobby does work fine if you don't have campaign mode selected, but as soon as you select the mode the lobby stops functioning and you will receive a console error after some waiting. I also had the server close with a error when I waited even longer but I forgot to document that.

**To note:** I did start the multiplayer campaign while one of the joining players was still in the middle of downloading mods, so that might be the cause for the pipe is broken crash, but as of now this is just speculation. 

**Steps To Reproduce**
The cause of the "Pipe is broken" crash is unkown, but the following issue of not being able to play multiplayer campaign can be reproduced by dropping the broken save found below to the multiplayer saves folder. 

The warning + error looks like this when you try to create a new campaign save with the broken save present
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/d666ce46-008f-4cb6-b24d-41a983e80ecf)

**Version**
Unstable 0.17.4.0

**Additional information**

Broken save:
[https://app.zenhub.com/files/93301055/a9193d5b-15cd-4aa0-8bb6-8f17e7b2d65b/download](https://app.zenhub.com/files/93301055/a9193d5b-15cd-4aa0-8bb6-8f17e7b2d65b/download)

Server crash report:
[https://app.zenhub.com/files/93301055/3eee27b1-d93f-4afd-9a96-1c1fa423c2ac/download](https://app.zenhub.com/files/93301055/3eee27b1-d93f-4afd-9a96-1c1fa423c2ac/download)

Console output following that crash:
[https://app.zenhub.com/files/93301055/6ad1c5fd-b7ba-4e1f-9636-ada13ab1ceb0/download](https://app.zenhub.com/files/93301055/6ad1c5fd-b7ba-4e1f-9636-ada13ab1ceb0/download)

Console output from second server crash (crash report is identical):
[https://app.zenhub.com/files/93301055/ae1a4355-a3c5-41b3-9f67-ed81d3409a41/download](https://app.zenhub.com/files/93301055/ae1a4355-a3c5-41b3-9f67-ed81d3409a41/download)

**Comment by Regalis11** [comment] 2022-03-28 08:27
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/df1a13dff0e61bf5bc78e113f996159bd2034d73

**Comment by Regalis11** [comment] 2022-03-29 07:27
Duplicate of https://github.com/regalis11/barotrauma/issues/8487

**Closed by Regalis11** 2022-03-29 07:27 UTC
Labels: Bug, Code, Crash, Networking
