### ISSUE TITLE
Multiplayer - Specific players seems to be very likely to receive Missing Entity kicks at the start of round.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4309] opened 2020-11-13 22:07 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In Multiplayer, very specific players seems to be very likely to receive Missing Entity kicks at the start of campaign rounds.

**Version**
~0.1100.0.6

**Additional information**
I'm not sure if stuff like connection, hard drive/ssd, or some other sort influences this problem.

Throughout my stream, Gostak and The Baro Clown has a hard time joinining my game, but everyone else seems alright.
https://www.twitch.tv/videos/801699128

**Comment by Regalis11** [comment] 2020-11-16 14:09
Thank you for the report, but I'm afraid there's not much we can do with this info without any error logs/messages. Closing as a duplicate of https://github.com/Regalis11/Barotrauma/issues/2382

**Closed by Regalis11** 2020-11-16 14:09 UTC
Labels: Bug, Code, Networking
