### ISSUE TITLE
[Factions] You can dock with pirate submarines and use them in the campaign

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10656] opened 2022-12-03 01:16 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

At the end of the campaign session (new 100.8.0.0 one), we started messing around. One thing led to another, and we somehow found a way to make a pirate submarine your new vessel! This context is important because a lot of things happened at once when this bug triggered, so the reproduction steps may not be 100%.

![image](https://user-images.githubusercontent.com/105495756/205415096-d17d3ca5-2332-493a-a867-cb93014817b9.png)

Before the end screen triggered, the following events happened basically at the same time:

1) Two players were inside a respawn shuttle docking onto the Dugong (our original submarine)
2) The pirate submarine was actively docked to the mission end (the outpost docking hatch)
3) Myself and another player were blown up by a comically large number of depth charge shells

I'm not sure if part 1 or part 3 were the trigger for this bug, but I'm dead certain part 2 was what allowed us to progress with the pirate sub. I've included the most believed reproduction steps in the appropriate section.

### Reproduction steps

1) Dock pirate sub to outpost
2) Have a respawn shuttle active
3) Dock the respawn shuttle to the original sub
4) The game should kick you out to the end screen. You'll be docked at the outpost with your new pirate submarine!

### Bug prevalence

Just once

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-01-04 13:57
Thank you for the report!

I wasn't able to find a way to reproduce this, but I have a guess on what could've caused it, and implemented a fix in https://github.com/Regalis11/Barotrauma-development/commit/56d7c5af846a4ecec2b31f73c1de7f66687a4bb0.

Basically, the game required the "leaving sub" to be assigned to the same team as the first player in the crew, but if there were no players alive, it'd default to any type of sub. Now we default to the player team (Team1) instead.

**Comment by JeroonBosch** [comment] 2023-01-11 12:14
Couldn't reproduce with the following steps:
1. Start multiplayer campaign
2. Force pirate mission to start with an outpost on both ends (so the pirate vessel can be docked somewhere)
3. Dock the pirate submarine to the end outpost (console cmd to kill pirate crew, then taking over the vessel)
4. kill command on myself to force respawning in a drone. Respawnnow command
5. Docking the drone to the main sub, while the pirate sub is docked at the end outpost

No end screen triggered ... but I died? (this is on live branch, I'll see if things break on the potentially fixed branch)

**Comment by JeroonBosch** [comment] 2023-01-11 12:28
![image](https://user-images.githubusercontent.com/8641689/211806335-bde9bc21-c247-4d85-bcb1-74fcc3a5ecdb.png)
Got these console errors upon docking (both branches).. also probably unrelated, but when moving through the respawn shuttle's hatch into the main sub, the hatches broke and basically I teleported to the sub below. Didn't work nicely at all.

**Comment by NilanthAnimosus** [comment] 2023-08-17 11:55
Tested against Release/traitor-update commit https://github.com/Regalis11/Barotrauma-development/commit/6831bcc4584be3b415d5cff1a75a2fa6c203bc9a, no issues found.

Notes:
The UI will no longer show the buttons to access the map interface, inside of the next outpost in the level or the docked pirate submarine, One must get a submarine from the players team (which also does not include the respawn shuttle) close to the outpost before these options appear, which upon using even with a pirate submarine docked and closest to outpost will still use the player submarine, closing as this does not seem possible after the code changes.

Can always be reopened if somehow it occurs again - but if mods are used please include a list of mods (such as a modlist).

**Closed by NilanthAnimosus** 2023-08-17 11:55 UTC
Labels: Bug, Need more info, Needs testing, Code
