### ISSUE TITLE
[Factions] Diving Suit Locker sprite is sometimes wonky

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10600] opened 2022-11-27 13:26 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Let me preface this by stating this is an issue I've seen over the years being posted about in the Discord. I expected a ticket to have been made, but I couldn't find one (inb4 I didn't look hard enough and this gets closed as a dupe).

Sometimes, probably due to networking, diving suit locker sprites that contain a diving suit will show the coloured sprite in a wonky way. This issue does not appear to be connected to specific diving suit types.

![image](https://user-images.githubusercontent.com/105495756/204137670-d549a55d-f64f-4d01-898b-7987bc5e7ffa.png)

### Bug prevalence

Happens every now and then

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-11-27 14:33
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10580

**Closed by Regalis11** 2022-11-27 14:33 UTC
