### ISSUE TITLE
Displaying rotated walls on the status monitor

### ISSUE THREAD

**Issue by rav2n** [Regalis11/Barotrauma#13139] opened 2023-12-10 12:05 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

First of all, thank you so much for the new opportunity to rotate walls!

Now about the problem:
Minimap on the monitor doesn't take into account rotated or stretched wall textures, which sometimes makes it look very ugly.
This problem has existed for quite some time, but with the introduction of rotation it is now especially noticeable.

View of a rotated wall:
![image](https://github.com/Regalis11/Barotrauma/assets/29980468/3b6d3e73-c828-4331-ad81-6f57375aaf4a)

View of a wall with scaling texture (old method without rotation):
![image](https://github.com/Regalis11/Barotrauma/assets/29980468/9a9d041d-1619-4014-8f3a-de07e8967ed6)

### Reproduction steps

1. Rotate any wall or fin in the subeditor.
2. Look at the display of the minimap on the status monitor(especially noticeable in the item finder section).

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.5.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-12-10 12:08
Duplicate of https://github.com/Regalis11/Barotrauma/issues/13065

**Closed by Regalis11** 2023-12-10 12:08 UTC
