### ISSUE TITLE
Sub Save Duplicating

### ISSUE THREAD

**Issue by Pspritechologist** [Regalis11/Barotrauma#8123] opened 2022-01-30 06:27 UTC
Saving a sub in the sub editor will temporarily cause the sub file to duplicate in the load/save list. The two files are identical and update accordingly, but only go away after a restart.

 To reproduce, simply save a modified sub in the sub editor, and view the loading list.

This occurred in version v0.15.23.0, on a Windows 10 PC.

The bug is entirely visual as both listings update with each other, and vanish after a restart.

**Comment by Regalis11** [comment] 2022-01-31 10:12
I'm afraid I couldn't reproduce this.

I opened Dugong and saved a modified version of it:
![image](https://user-images.githubusercontent.com/14351070/151775312-e938f13a-407c-4d3e-8937-0461c853b90e.png)

And it only appears once in the list:
![image](https://user-images.githubusercontent.com/14351070/151775378-6e6dc07f-d880-439b-8dce-f2b3b2120010.png)

**Comment by Pspritechologist** [comment] 2022-02-01 21:40
Sorry, I should've clarified, you need to save *over* the file. Modify the Dugong_modified, save it over the Dugong_modified file, and there should now be two Dugon_modified files, both identical

**Comment by Pspritechologist** [comment] 2022-02-01 21:55
Hmm, my bad, I can't seem to cause it. Thought I had understood it better, but it seems it doesn't trigger every time. I'll keep an eye out for it, and when it happens I'll try to work out what causes it, when I do I'll either update here or make a new report.

**Comment by MaaiG** [comment] 2022-02-09 16:55
My two cents.
This happened before in the some previous game versions. When you removed the submarine - the second copy files appeared. The differences were in the path to the file (In the second case, instead of "/" used "\\".

**Comment by Pspritechologist** [comment] 2022-02-10 04:04
If we're adding two cents, I've been keeping an eye out, it may have something to do with enabling debubdraw

**Comment by MaaiG** [comment] 2022-02-10 09:40
**I was able to reproduce it!**
How to do it:
1. open sub
2. save sub (Watch save path: "\\" >>>"/")
3. save sub as new
4. save sub (Watch save path: "\\" >>>"/")
5. delete first sub
6. The name of the second submarine is duplicated!

https://user-images.githubusercontent.com/93348499/153379285-70f55747-ca27-4372-a852-91d40927568f.mp4

**Comment by MaaiG** [comment] 2022-02-12 11:45
> I'm afraid I couldn't reproduce this.

@Regalis11 After create "Dugong_Modified" you need to save your "Dugong_Modified" again and delete some other submarine. You will see that you now have two files "Dugong_Modified".

The name is duplicate because the `path separators` changes when you save a file again.
![Image 001_14-33](https://user-images.githubusercontent.com/93348499/153709891-7a4ee6d5-3d3a-4761-a6e4-fa3a0a0739e8.png)

I was able to reproduce it!
v0.15.23.0, Vanilla 0.9 (Windows 10-x64).
How to do it:
1. Open sub
2. Save sub (Watch save file path. Path separator "\\" >"/")
3. Save sub as new
4. Save sub (Watch save file path. Path separator "\\" >"/")
5. Delete first sub (Or any other file with path separator "\\")
6. The name of the second submarine (file with path separator "/") is duplicated!

https://user-images.githubusercontent.com/93348499/153587509-1d88c7b6-d320-4b9b-a992-e864afd05aec.mp4

P.S. 
> it may have something to do with enabling debubdraw

Apparently, [this is](https://web.archive.org/web/20100612035120/http://blogs.msdn.com/b/larryosterman/archive/2005/06/24/432386.aspx).

**Comment by MaaiG** [comment] 2022-05-20 12:35
v0.17.15 - works fine.

**Comment by Rokvach** [comment] 2022-06-06 01:37
Tested, no issues. Closing.

**Closed by Rokvach** 2022-06-06 01:37 UTC
Labels: Bug, Code
