### ISSUE TITLE
Ship Hum Causes Audio Popping

### ISSUE THREAD

**Issue by Pornetheus** [Regalis11/Barotrauma#8176] opened 2022-02-03 01:47 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.
Found only one report of this online and did not find a resolution besides downloading a sound mod. I have yet to see if that still works. Either way id rather use the original audio. Please help this time because I love me some Barotrauma. https://github.com/Regalis11/Barotrauma/issues/5730   link to the only similar report.
**Description**
A subtle pop that sounds off on either side of my headphones. Not constant, one at a time, spaced out. I'm not sure the specific term for this sound other than audio pop. 

**Steps To Reproduce**
. For example take the Humpback. Stand in the center of the command console so the hum is sounding equally balanced between your headphones. An audio pop will proceed to occur. moving to the left of the sound source will put these pops into your left headphone cup, and vice versa. Anywhere in the ship with this specific mechanical 'hum' produces the audio pops. Anywhere without this sound is fine.

**Version**
v0.15.28.0 Windows 10 Version

**Additional information**
At first I thought my headset was dying, it is a few years old at this point (Sennheiser Game One, or a version of it. Not top tier but good quality). But after trying multiple games and using a different mic to detect the audio bug, I realized it was definitely a in game issue. Having this audio bug right at the command console makes it pretty much impossible to ignore on single player. Any feedback would be appreciated!

**Comment by Regalis11** [comment] 2022-02-03 08:24
Duplicate of https://github.com/Regalis11/Barotrauma/issues/5730

**Closed by Regalis11** 2022-02-03 08:24 UTC
