### ISSUE TITLE
Blank sub file causing permeant file damage and inability to paly

### ISSUE THREAD

**Issue by hahaA10gobrrrt** [Regalis11/Barotrauma#12681] opened 2023-09-17 22:39 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Loading a server campaign file causes a console error and inability to load game.

to be noted: 
-we had an enemy sub attached via a lower docking hatch as we docked to our destination outpost
- I could not figure out how to view the .sub files (i can't open them/ don't know how)
- -not sure how to find backup files, doubt i have any
![Capture](https://github.com/Regalis11/Barotrauma/assets/78120467/a4a8fbe8-e92b-4da3-875f-32631d2e476d)

### Reproduction steps

1. Have corrupted .sub file
2. launch vanilla executable multiplayer server campaign
3. select "better campaign"
4. launch and cry as the error greets you

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
[09/17/2023 13:49:39]
  Starting the server...
[09/17/2023 13:49:39]
  Using SteamP2P networking.
[09/17/2023 13:49:39]
  Server started
[09/17/2023 13:49:39]
  [TM] waccoon has joined the server.
[09/17/2023 13:49:39]
  Saving client permissions
[09/17/2023 13:49:39]
  Saving client permissions
[09/17/2023 13:49:41]
  Gamemode changed to Campaign
[09/17/2023 13:50:17]
  Saving banlist
[09/17/2023 13:50:17]
  Shutting down the server...
```

**Comment by hahaA10gobrrrt** [comment] 2023-09-17 22:46
I have the corresponding autosaves so not sure if that will help

**Comment by Regalis11** [comment] 2023-09-18 07:17
Thank you for the report! We've gotten some reports about this previously too, but unfortunately haven't yet been able to figure out how to reproduce the issue. :/ If you have the submarine file and/or the save file, posting it [here in the existing ticket](https://github.com/Regalis11/Barotrauma/issues/12104) might help us get to the bottom of this. Thanks and sorry for the inconvenience! :/

Closing as a duplicate of https://github.com/Regalis11/Barotrauma/issues/12104

**Closed by Regalis11** 2023-09-18 07:17 UTC
