### ISSUE TITLE
Cargo scooter degrading items inside when in use

### ISSUE THREAD

**Issue by abemaden** [Regalis11/Barotrauma#12569] opened 2023-08-27 12:52 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When using the cargo scooter, any items inside will degrade the more the scooter is used. Items that has been degraded can't be used for crafting, and will not stack with each other. However, the degraded items can be combined to transfer the condition to other items. For example if we combine 2 galena, each with 95% condition, one would have 100% condition, and the other 90%.
We believe it's because the cargo scooter normally degrades the battery in the battery slot, but now for some unknown reason also degrades the other items in the scooter, although at a much slower rate than the battery. We encountered this bug in multiplayer, but it may very well happen in singleplayer as well.

![cargo](https://github.com/Regalis11/Barotrauma/assets/142632571/17e3c37e-c06b-42a9-bfed-083d2670adb7)

https://github.com/Regalis11/Barotrauma/assets/142632571/1f9544c1-9c0f-4b48-a1b5-cdf2e65c046c

### Reproduction steps

1.  Start a multiplayer campaign
2.  Acquire a cargo scooter
3.  Put a battery into the battery slot, and fill the cargo scooter with various items.
4.  Use the cargo scooter, and observe how all items will degrade.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

Unstable (v1.1.9.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by ubertpendragon** [comment] 2023-08-27 18:36
Caused by the new "aiming" light component #12270, needs to target the battery slot specifically when held

**Comment by Regalis11** [comment] 2023-08-28 07:21
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c5e22f9594ef5a572c890684fd89db67b6d75d97

**Comment by Jasontti** [comment] 2023-09-01 13:40
Tested.
No issues found.
Closing ticket.

**Closed by Jasontti** 2023-09-01 13:40 UTC
Labels: Bug, Design
