### ISSUE TITLE
1006: No contained sprite for railgun single shell loader

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#3254] opened 2020-07-01 01:15 UTC
railgun shells do not have a containedsprite for single shell loaders. looks like a slip up in the art unification.
![2020-06-30-201440_383x280_scrot](https://user-images.githubusercontent.com/47284081/86192101-5d736000-bb0e-11ea-8c86-034b248cc212.png)

**Comment by Regalis11** [comment] 2020-07-02 07:37
I wasn't able to reproduce this with unmodified loaders, but setting the sprite depth of the loader lower than the default value caused the shell to disappear, so I assume these 2 loaders have a non-default sprite depth. If that was the cause, https://github.com/Regalis11/Barotrauma-development/commit/779d47a954c7e6b1549e7b8d6990293fff8f826b should fix the issue

**Comment by Rokvach** [comment] 2020-07-03 12:13
No issues, closing.

**Closed by Rokvach** 2020-07-03 12:13 UTC
Labels: Bug, Code
