### ISSUE TITLE
Seemingly Random Crash Mid-Game

### ISSUE THREAD

**Issue by mrjpjr** [Regalis11/Barotrauma#2547] opened 2020-03-31 20:42 UTC
**Description**
Screen froze (for a very short time) then the game closed and generated 2 crash reports.

**Steps To Reproduce**
Not sure.
I was typing something, then pressed ESC before sending the message when the crash happened, but I just tried it again and it did not crash.

**Version**
Unstable 0.9.9.01.0 rev 42f5a82be
Windows 10

**Additional information**
Crash Logs
[crashreport (9).log](https://github.com/Regalis11/Barotrauma/files/4411474/crashreport.9.log)
[crashreport (8).log](https://github.com/Regalis11/Barotrauma/files/4411475/crashreport.8.log)

**Comment by ekqvist** [comment] 2020-04-01 08:48
Stack trace in _crashreport (9).log_ seems to be the same as in #2511, but the one in _crashreport (8).log_ is different

**Comment by Regalis11** [comment] 2020-04-01 08:55
Added a try-catch that should prevent the first exception from happening: https://github.com/Regalis11/Barotrauma-development/commit/554fcac99a700320f3c0a18cf4af842924c45394.

The latter is a duplicate of #1833

**Closed by Regalis11** 2020-04-01 08:55 UTC
Labels: Bug, Code, Crash, Duplicate
