### ISSUE TITLE
0.10.4 More bot suffocations

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#3402] opened 2020-07-20 22:03 UTC
- [x ] I have searched the issue tracker to check if the issue has already been reported.

related #https://github.com/Regalis11/Barotrauma/issues/3333

**Description**
Bots suffocate in diving suits when there is no empty suit locker to take it off and/or when the locker is not very close. (reproduction below)
Bots also use masks + diving suits at the same time to step into e.g. the humpback ballast tanks for repairs. (they love the diving suit to go into the ballast tank that has no breaches)
It seems bots are either unable, or unable in certain conditions, to get new oxy bottles from containers.  (seems to swap bottles they have in inventory).

**Steps To Reproduce**
Often players keep diving suits dropped next to their working places. I followed bots picking them up and not taking them off when the suit lockers are stocked. So far tested during normal duty, no combat, breaches, etc.

**Version**
0.10.4 SP and MP campaign. Windows

**Comment by Udrakan** [comment] 2020-07-25 22:14
The clips I provided had full lockers, I think you are right about this.
Would be nice if bots used diving masks if available, if room is below certain pressure level.

**Comment by Regalis11** [comment] 2020-07-27 08:09
Duplicate of #3333

**Closed by Regalis11** 2020-07-27 08:09 UTC
