### ISSUE TITLE
NPCs can not climb the stairs in the ship camel

### ISSUE THREAD

**Issue by S1FOoN** [Regalis11/Barotrauma#12097] opened 2023-05-29 14:34 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

NPCs can't climb the stairs normally.
The ship is a camel. The ladder down to the left of the sub control panel. NPCs try to climb and fall back down - endlessly. The ship is unchanged, standard.

It may not be a problem... I can't figure it out - as some NPCs go up without a problem.

### Reproduction steps

1. Start the company.
2. Need to purchase a camel.
3. the NPCs must be in the lower sections.
4. Give the command to repair mechanical/electrical devices.
5. The NPCs will try to climb the ladder and fall. And so on endlessly. No other activity will be done. (Or the second option, they do the rest and then get stuck at this point). I.e. They won't be able to fix the navigation terminal or the status screen :)
![example](https://github.com/Regalis11/Barotrauma/assets/134947429/820b1e6b-41d1-4105-bff9-6acec1e84769)

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
no system/game issues
```

**Comment by Regalis11** [comment] 2023-05-29 14:36
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11984

**Closed by Regalis11** 2023-05-29 14:36 UTC
