### ISSUE TITLE
Repeatable Bug Crashes Game In Sub Editor When Editing Values

### ISSUE THREAD

**Issue by AFlockofDogs** [Regalis11/Barotrauma#9673] opened 2022-08-02 23:28 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When using the submarine editor, if you change the value in the field of a submarine part, for example the text displayed in the "Text" field of a "Text Display" or the "Output Signal" of the "Signal Check Component", and then click directly on another part of the same type the game will immediately crash.

Testing determined that:

Clicking on another of the same part WILL crash the game. For example, clicking from a "Signal Check Component" to another "Signal Check Component", or from a "Text Display" to another "Text Display".

Clicking on a different type of part will NOT crash the game. For example, clicking from a "Text Display" to a "Signal Check Component".

The game will only crash if a value was changed. You can safely click between "Text Display" parts as long as you do not change a value.

It does not matter if the parts are identical, only if they have the same name, for example, changing the size or color of a "Text Display" before clicking between them will NOT prevent the crash.

Pressing enter before clicking between parts WILL prevent the crash. 

### Reproduction steps

1. Open the submarine editor.
2. Place two of the same kind of part, for example, two "Text Display" parts.
3. Enter any value in any field, for example, "I would like to crash now" in the "Text" field of one of the "Text Display" parts.
4. After entering the value, without hitting enter, click directly on the other part.
5. Game immediately crashes. 

### Bug prevalence

Happens regularly

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 8/2/2022 6:54:40 PM)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


A3E1BD9914304826B1774DE813786E1D


Game version 0.18.15.0 (ReleaseWindows, branch release, revision a7b22109e9)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla, Moza, Mini Moza, Darklight, Auto Supercapacitor, Darklight (Cargo Variant), Darklight Prime, Goliath, Elevator, Darklight Apex, Sunshine, Smart Duct, Improved Auto Hatch, Improved Auto Pump, Surge Protector
Level seed: no level loaded
Loaded submarine: Sunshine (6F64072B67720B674A7E3B896BEBC87A)
Selected screen: Barotrauma.SubEditorScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce GTX 970
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: Type provided must be an Enum. (Parameter 'enumType') (System.ArgumentException)
Target site: System.RuntimeType ValidateRuntimeType(System.Type)
Stack trace: 
   at System.Enum.ValidateRuntimeType(Type enumType)
   at System.Enum.TryParse(Type enumType, String value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at Barotrauma.SerializableEntityEditor.MultiSetProperties(SerializableProperty property, Object parentObject, Object value) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Serialization\SerializableEntityEditor.cs:line 1451
   at Barotrauma.SerializableEntityEditor.SetPropertyValue(SerializableProperty property, Object entity, Object value) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Serialization\SerializableEntityEditor.cs:line 1351
   at Barotrauma.SerializableEntityEditor.<>c__DisplayClass29_0.<CreateStringField>g__OnApply|3(GUITextBox textBox) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Serialization\SerializableEntityEditor.cs:line 707
   at Barotrauma.SerializableEntityEditor.<>c__DisplayClass29_0.<CreateStringField>b__1(GUITextBox textBox, Keys keys) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Serialization\SerializableEntityEditor.cs:line 691
   at Barotrauma.GUITextBox.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBox.cs:line 477
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1229
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 898
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59


Last debug messages:
[8/2/2022 6:47:05 PM] Attempting to open ALC device "OpenAL Soft on Speaker (Jabra Engage 65)"
[8/2/2022 6:47:03 PM] Logged in as A Flock of Dogs (SteamID STEAM_1:1:42657488)
```

**Comment by MaaiG** [comment] 2022-08-03 09:51
https://github.com/Regalis11/Barotrauma/issues/9512
https://github.com/Regalis11/Barotrauma/issues/9570
https://github.com/Regalis11/Barotrauma/issues/9576
https://github.com/Regalis11/Barotrauma/issues/9580
https://github.com/Regalis11/Barotrauma/issues/9588
https://github.com/Regalis11/Barotrauma/issues/9629
https://github.com/Regalis11/Barotrauma/issues/9635

Dev, just release the updated stable version at last 😬 Why torture people 👁️))

**Comment by Dynamoon** [comment] 2022-08-03 16:04
Hi! This is the Baro community manager and I don't usually talk here since it is the programmers' turf, not mine. However it's the summer holiday season in Finland and we're undermanned, so I thought I'd drop by!

The delay in fixing this is also due to said lack of manpower. We will release the fix as soon as we are able to put a build through quality assurance to be sure we don't break anything else in the process of fixing one thing. Unfortunately it will thus be a little while longer before we are able to make a public release, and we are really sorry for the inconvenience in the meantime.

This is not much of a progress report on the issue, but I hope it will at least clarify why a public release has not been made yet!

**Comment by Regalis11** [comment] 2022-08-04 10:31
Duplicate of https://github.com/Regalis11/Barotrauma/issues/9512

**Closed by Regalis11** 2022-08-04 10:31 UTC
