### ISSUE TITLE
Multiplayer - togglecampaignteleport does not work

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3726] opened 2020-09-04 19:39 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
togglecampaignteleport does not work in multiplayer. Server cannot find the command.

**Version**
~0.10.502

**Comment by Regalis11** [comment] 2020-09-06 16:28
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/700f3d0e58c31c5b698bef41e9ae017227f85a62

**Comment by Rokvach** [comment] 2020-09-07 08:39
Server host isn't permitted to use the command, tested on SteamP2P @Regalis11

**Comment by Regalis11** [comment] 2020-09-07 13:22
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/245f701b75e1443476265f8e6219dbb6f2d29ac6

**Comment by Rokvach** [comment] 2020-09-08 08:55
- [ ] When you teleport somewhere in the map your selected location doesn't update, but instead keeps it next to the location where you started teleporting

Repro steps:
1. Double click to a location to teleport to it
2. See that your camera focuses on the starting location and one of the destinations for that location are highlighted

- [ ] I'm unable to start a round after teleporting to a location, the start button doesn't appear to be doing anything when clicked.

**Comment by Regalis11** [comment] 2020-09-08 09:55
Could not reproduce either. The camera seems to move from the previous location to the newly selected one as intended, and the start button appears. Tested in the latest dev branch using SteamP2P, both as the server host and by joining a dedicated server as a normal client.

**Comment by Regalis11** [comment] 2020-09-08 10:35
Looks like the issue was only present in release builds, fixed in https://github.com/Regalis11/Barotrauma-development/commit/25c484cca508e86eaf3e71bd6907e733fccc60a5

**Comment by Rokvach** [comment] 2020-09-08 10:54
Tested, working correctly. Closing.

**Closed by Rokvach** 2020-09-08 10:54 UTC
Labels: Bug, Code, Networking
