### ISSUE TITLE
[Unstable 0.17.2.0] Creatures are spawned inside rock islands

### ISSUE THREAD

**Issue by mrjpjr** [Regalis11/Barotrauma#8554] opened 2022-03-18 20:37 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Creatures spawned inside an (unbreakable) rock in the map (see image below)

**Steps To Reproduce**

**Version**
Unstable 0.17.2.0
Windows

**Additional information**
![image](https://user-images.githubusercontent.com/58775950/159079653-5ca9bff3-34e7-4a0f-af35-5361b5abd31a.png)

**Comment by Regalis11** [comment] 2022-03-21 08:35
Duplicate of https://github.com/Regalis11/Barotrauma/issues/8244

**Closed by Regalis11** 2022-03-21 08:35 UTC
