### ISSUE TITLE
Enemy Submarine was not created. Submarine Info is likely not defined.

### ISSUE THREAD

**Issue by LieutenantCaki** [Regalis11/Barotrauma#10260] opened 2022-11-05 21:47 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

When i start mission: "Pirate Vessel" the game crashes and puts the following message (on the game console) "Enemy Submarine was not created. SubmarineInfo is likely not defined."

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-11-07 09:05
I'm afraid I could not reproduce this. I would suspect this is caused by some of the mods you have enabled - any idea if any of them might modify the missions or the pirate subs in some way?

**Comment by Regalis11** [comment] 2022-11-16 09:12
No known steps to repro, closing

**Closed by Regalis11** 2022-11-16 09:12 UTC
Labels: Bug, Need more info, Code, Modding
