### ISSUE TITLE
Outpost events sometimes fail to trigger in the single player campaign

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#9152] opened 2022-05-16 14:34 UTC
Seems that the issue is that the ScriptedEvent.cachedtargets only refreshes when the count of the players/bots changes, but not when you change the character in the single player campaign.

Can be reliably reproduced e.g. by triggering the event "propaganda" and then changing the character: you can trigger the event only if you change back to the character you were controlling when the event was triggered:

Version: v0.18.1.0 (dev: Regalis11/Barotrauma-development@2176bbc).

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/b147bbf2-e53f-47c8-aac0-15b3f9bff28e)

**Comment by Regalis11** [comment] 2022-05-17 07:15
Duplicate of https://github.com/Regalis11/Barotrauma/issues/8068

**Closed by Regalis11** 2022-05-17 07:15 UTC
Labels: Bug, Code
