### ISSUE TITLE
Some recipes are broken after cave update

### ISSUE THREAD

**Issue by cola98765** [Regalis11/Barotrauma#5051] opened 2021-02-13 11:37 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
You can have infinite Organic Fibre and Elastin by crafting Bandages/Plastisieal with new reduced cost and then deconstructing them.

Calyxanide now uses whole Calyx Eggs, making them stupidly expensive to craft.

**Steps To Reproduce**
Craft them I guess?

**Version**
v0.12.0.2 (The Cave Update) on Windows

**Additional information**
n/a

**Comment by Regalis11** [comment] 2021-02-14 12:41
Duplicate of https://github.com/Regalis11/Barotrauma/issues/5027

**Closed by Regalis11** 2021-02-14 12:41 UTC
