### ISSUE TITLE
Crew member disappears at next location if revived through console

### ISSUE THREAD

**Issue by Dimsim1** [Regalis11/Barotrauma#8624] opened 2022-03-26 01:10 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If a crew member is killed and then revived through the console, they will disappear when you go to the next location.

**Steps To Reproduce**
Kill crew member/members or have them die somehow. Revive them through the console, go to the next destination and they will be gone.
**Version**
v0.16.7 (Windows)

**Additional information**
In Singleplayer

**Comment by Regalis11** [comment] 2022-03-26 10:00
Duplicate of https://github.com/Regalis11/Barotrauma/issues/5093

**Closed by Regalis11** 2022-03-26 10:00 UTC
