### ISSUE TITLE
Roles Tutorial - Can access mechanics area and craft as any role

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#11959] opened 2023-05-05 11:42 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

You can enter the mechanics area of the tutorial as any other role, and use the deconstructor/fabricator to craft iron items (IE. diving knife, screwdriver).

Though not a huge issue, it might make sense to keep sections locked to their specific roles, though in my case I crafted an item and killed a patient as medic with it - its unlikely any player would do this so its more a low priority issue.

### Reproduction steps

1. Start roles tutorial as any other choice than mechanic (IE medic)
2. run to mechanics tutorial area and craft items

### Bug prevalence

Happens every now and then

### Version

Other

### -

1.0.13.0 (RC build / unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-05-07 12:29
Duplicate of https://github.com/Regalis11/Barotrauma-development/issues/4130

**Closed by Regalis11** 2023-05-07 12:29 UTC
Labels: Design, Low prio
