### ISSUE TITLE
Helm XP & Levels earned are not displayed in multiplayer campaign

### ISSUE THREAD

**Issue by WilliamRoyNelson** [Regalis11/Barotrauma#4189] opened 2020-11-01 22:39 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In Multiplayer Campaign mode, using the helm in manual mode does not show XP earned popups and skill increases do not appear. The level-up does seem to update after earning XP of another type.
XP works properly in single-player campaign, and in other multi-player modes.

**Steps To Reproduce**
Host Server
Select campaign game mode
Enter save name and press start
Select mission (no mission, any destination)
Enter helm console
Toggle manual steering (switch in up position)
Select propulsion vector on main navigation display.

What I expect to see:
periodic +10 XP notifications near the helm
very occasional "player name's helm skill has gone up to x"

Instead, no helm notifications.

I do see notifications for Electrical Engineering tasks and weapons tasks. Unsure about medical xp.

**Version**
Barotrauma v0.10.6.2 (ReleaseWindows, branch release, revision d0702df35e)

**Additional information**
XP works properly in single player campaign
XP works properly in multiplayer sandbox mode

**search tags**
helm xp
helm exp
helm experience
piloting xp
piloting exp
piloting experience

**Comment by Kaillera** [comment] 2020-11-01 22:43
They do, just you don't see the EXP/Level gain until you level up something else.

#3777

**Comment by WilliamRoyNelson** [comment] 2020-11-01 22:55
> They do, just you don't see the EXP/Level gain until you level up something else.
> 
> #3777

Oh, didn't see that issue when I searched. Let me verify!

**Comment by WilliamRoyNelson** [comment] 2020-11-01 23:23
Just verified, this seems to be a display/presentation issue. The XP seems to be earned, but it's not shown except after earning another type of XP.

**Comment by Regalis11** [comment] 2020-11-23 18:16
Duplicate of #3777

**Closed by Regalis11** 2020-11-23 18:16 UTC
Labels: Bug, Code, Networking
