### ISSUE TITLE
Berilia Sprite Scaling Glitch

### ISSUE THREAD

**Issue by RB-511** [Regalis11/Barotrauma#4687] opened 2021-01-09 06:44 UTC
- [Y] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The back hull plating of the Berilia is scaled improperly. The preview image shows it being correct, whereas in-game and in-editor it's scaled improperly.

**Version**
Windows, game v.0.11.0.10

![berilia1](https://user-images.githubusercontent.com/77186479/104085295-d5d08180-5213-11eb-8e19-9bb5ebb67b5a.PNG)
![berilia3](https://user-images.githubusercontent.com/77186479/104085297-d6691800-5213-11eb-9115-655bbfa036ea.PNG)
![berilia2](https://user-images.githubusercontent.com/77186479/104085296-d6691800-5213-11eb-8a6a-743f5b0b0a31.PNG)

**Comment by 3e849f2e5c** [comment] 2021-01-11 06:39
Duplicate of #4177

**Closed by 3e849f2e5c** 2021-01-11 06:39 UTC
