### ISSUE TITLE
Saving and quitting then re-entering campaign duplicates missions

### ISSUE THREAD

**Issue by Shadowtail117** [Regalis11/Barotrauma#7859] opened 2021-12-19 08:10 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you talk to people at an outpost to gain missions, then save and quit and re-enter the campaign, you will have the missions available to select from but the outpost people will have more missions for you to take on. This can be done indefinitely.

**Steps To Reproduce**
1. Acquire missions from an outpost.
2. Save and quit.
3. Reload the campaign.
4. You'll have the missions available to choose from when leaving, but you'll also have new missions to acquire.

**Version**
v0.15.21.0 (Windows).

**Additional information**
Tested for singleplayer campaign. Untested for multiplayer campaign.

**Comment by gerakis** [comment] 2021-12-19 18:03
I think this is not a bug. Its a bit like undocking and redocking at the same station. They consider it a separate visit.

**Comment by Shadowtail117** [comment] 2021-12-19 18:09
If that is the case then I think it's a rather serious balance issue, as you can keep doing this over and over, getting a ludicrous amount of available missions, until you get the one(s) that you want.

**Comment by gerakis** [comment] 2021-12-19 18:19
I think it also advances jovian radiation by one turn, so if you are playing it the default way this strategy wont work very well.

**Comment by aceryz** [comment] 2021-12-19 22:28
I'd say that's the real issue: ending a campaign session and picking it up later advances the radiation by a step. If you play a single round each time you load the campaign save, you basically have the radiation move twice as fast as intended.

**Comment by gerakis** [comment] 2021-12-19 22:48
It saves already as soon as you dock. You are supposed to leave without saving if you do that.

**Comment by Shadowtail117** [comment] 2021-12-19 22:55
Seems like it's an oversight to advance the round with every save then. Most people are trained to save and quit when they are done playing, that action shouldn't do anything.

**Comment by gerakis** [comment] 2021-12-19 23:03
Now you know why everyone just turns off Jovian radiation.

**Comment by Regalis11** [comment] 2021-12-20 10:42
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3388

**Closed by Regalis11** 2021-12-20 10:42 UTC
