### ISSUE TITLE
Item.WritePropertyChange not getting the correct property owner

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#10127] opened 2022-10-20 11:38 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

When I used LuaForBarotrauma to patch the server, I found that the Editable SerializableProperties of the 2nd LightComponent of the reactor were not successfully synchronized.

Reactor xml:
```xml
<Item name="" identifier="reactor1" tags="reactor" type="Reactor" scale="0.5" linkable="true" category="Machine" damagedbyexplosions="true" explosiondamagemultiplier="0.2">
    
    <!-- omission...... -->

    <LightComponent range="10.0" lightcolor="255,255,255,0" powerconsumption="0" IsOn="false" castshadows="false" allowingameediting="false">
      <Upgrade gameversion="0.9.600.0" lightcolor="255,255,255,0" />
      <IsActive targetitemcomponent="Reactor" temperature="gt 2" />
      <sprite texture="Content/Items/Reactor/reactor.png" depth="0.025" sourcerect="523,0,482,336" origin="0.5,0.45" alpha="1.0" />
    </LightComponent>

    <LightComponent range="10.0" lightcolor="255,255,255,0" powerconsumption="0" IsOn="false" castshadows="false" allowingameediting="false" blinkfrequency="1">
      <Upgrade gameversion="0.9.600.0" lightcolor="255,255,255,0" />
      <IsActive targetitemcomponent="Reactor" temperaturecritical="eq true" />
      <sprite texture="Content/Items/Reactor/reactor.png" depth="0.025" sourcerect="523,337,482,336" origin="0.5,0.45" alpha="1.0" />
    </LightComponent>
    
    <!-- omission...... -->

  </Item>
```

So I checked the source code, it seems like `Item.WritePropertyChange` will always only find the first component.

If this is not intentional, its code should looks like:
https://github.com/Regalis11/Barotrauma/compare/master...zhu-rengong:LuaCsForBarotrauma:fix_property_sync

But this fixed version doesn't iterate through Item's components to find properties in depth, because I don't know programming very well, so can only describe the issue in this way

### Bug prevalence

Happens every now and then

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-10-20 16:40
Thank you for the report! I'm afraid I'm not quite sure I understand what the issue is here. I gave a test at giving a light  two editable light components, a short-range and a long-range one, and editing them separately seems to work with no issues. 

> So I checked the source code, it seems like Item.WritePropertyChange will always only find the first component.

That doesn't actually seem to be the case. It doesn't find the component at all; that's not necessary, because we use the index of the property in the list of all the Item's properties.

`msg.WriteByte((byte)allProperties.FindIndex(p => p.property == property));`

Including the entity in ChangePropertyEventData, as you've done in your branch, isn't necessary either. The event itself knows which entity it's targeting, so there's no need to store another reference to it in the extra event-specific data.

**Comment by zhu-rengong** [comment] 2022-10-20 16:59
I don't think so? These two light components got the same `SerializableProperty` because they both get `SerializableProperties` from the cache based on their type:
```csharp
public static Dictionary<Identifier, SerializableProperty> GetProperties(object obj)
        {
            Type objType = obj.GetType();
            if (cachedProperties.ContainsKey(objType))
            {
                return cachedProperties[objType];
            }

            // omissions......

        }
```
I'm not exactly sure, but I don't know how you test. If `canbeselected` is set to true for two `LightComponent`, actually it will works fine with no issues for the client that modified it, but it is already asynchronous with the server and other clients.

**Comment by Regalis11** [comment] 2022-10-20 18:04
Ah, you're right! I only tested this with one client, so that must be why I didn't notice any issues. Thank you for the clarification, I'll take another look at this soon.

**Comment by Regalis11** [comment] 2022-10-21 04:49
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/84f51800d34740d5ad94355d0261063bde4a0add.

Note for internal testing: you can for example modify one of the lights to have 2 light components instead of one, and then check that changes to the light colors are replicated correctly when another client modifies them.

```
<Item name="" identifier="emergencylight" category="Electrical" Tags="smallitem,light" scale="0.5">
  <Upgrade gameversion="0.10.0.0" scale="*0.5" />
  <Sprite texture="signalcomp.png" sourcerect="0,960,96,16" depth="0.8" />
  <LightComponent lightcolor="0,255,0,255" range="250.0" IsOn="true" castshadows="true">
    <LightTexture texture="Content/Lights/pointlight_bounce.png" origin="0.5,0.5" />
    <sprite texture="Content/Items/Electricity/signalcomp.png" sourcerect="480,960,96,16" alpha="1.0" />
  </LightComponent>
  <LightComponent lightcolor="255,0,0,255" range="500.0" IsOn="true" castshadows="true">
    <LightTexture texture="Content/Lights/pointlight_bounce.png" origin="0.5,0.5" />
    <sprite texture="Content/Items/Electricity/signalcomp.png" sourcerect="480,960,96,16" alpha="1.0" />
  </LightComponent>
  <ConnectionPanel selectkey="Action" canbeselected="true" msg="ItemMsgRewireScrewdriver" hudpriority="10">
    <GuiFrame relativesize="0.2,0.32" minsize="400,350" maxsize="480,420" anchor="Center" style="ConnectionPanel" />
    <RequiredItem items="screwdriver" type="Equipped" />
    <input name="toggle" displayname="connection.togglestate" />
    <input name="set_state" displayname="connection.setstate" />
    <input name="set_color" displayname="connection.setcolor" />
  </ConnectionPanel>
</Item>
```

**Comment by NilanthAnimosus** [comment] 2022-12-01 12:30
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/2b57faa07493e732f98261ead832ba904168f57b, no issues found, closing.

**Closed by NilanthAnimosus** 2022-12-01 12:30 UTC
Labels: Bug, Code, Modding, Unstable
