### ISSUE TITLE
Broken passive sonar, possibly because of artifact

### ISSUE THREAD

**Issue by PaladynMinak** [Regalis11/Barotrauma#6449] opened 2021-08-21 14:57 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Approaching artifact breaks passive sonar, or so, more info below.

**Steps To Reproduce**
Go by boat to close proximity of nasonov artifact (possibly others), then make distance and observe walls on passive sonar, or rather their absence and absence of signatures from boat too.

**Version**
v0.14.6.0 revision 12d7084c07 Windows 10 Pro

**Additional information**
I was testing custom sub on campaign. After approaching nasonov artifact (not sure for others), which emits noise, so it's area is visible on passive sonar, makes that sonar can't see nothing but what's around that artifact. Active is ok, but both engine and reactor are making noise for passive to work, but after coming to that artifact, I couldn't see anything anymore on passive, but signatures made by that artifact. I've went ~300m away, back to starting station, then spent some time on pause (I think), searching here if such issue was already reported. Then I decided to research it more. I don't know when it happened, because I localized it then on freecamera and went straight to it, but when I was back there at artifact, this time passive sonar was working ok. I quit to menu and loaded same save. Found nasonov again in similar place and again it broke passive sonar. I wanted to test it on other artifacts, but when I reloaded save again, passive was still broken. I don't know what made it work properly at first time, but at second time I wasn't waiting for anything and at third time, I had broken passive from the start, tried waiting, but it brought nothing. Map seed is "UrKCGFQT". I've reloaded few more times with same effect and started new save, still with broken passive, but I've noticed I see signatures from passive, when in docking range to station, but only there, only in docking distance. Interestingly enough, after restarting the game and loading first said save, I had passive still broken. I'm done for now, maybe I'll do more tests later.

PS So I started another save and passive was still broken, then I decided to see it in editor, I've went on full thrust, and signatures came back, just like that. I got back to that save and it was working there too. I don't know if test in editor is related, but seems so.

**Comment by Regalis11** [comment] 2021-10-12 09:51
Thank you for the report! Unfortunately I was unable to reproduce this issue. The signatures inside the sub, and the sounds reflected from nearby walls seem to be visible even when there's an artifact nearby:
![image](https://user-images.githubusercontent.com/14351070/136933128-e04d902a-f5c9-417e-8fa9-f90591db5bf8.png)

The passive sonar seemed to also be working as expected after I moved away from the artifact:
![image](https://user-images.githubusercontent.com/14351070/136933476-5218c5b3-1002-4f9d-999c-0e6fbb723592.png)

I wonder if it could be that the custom submarine is just very silent, and that when it's moving slow the sounds of the engine aren't loud enough to reflect from nearby obstacles? As a tip, you can see the ranges of the sounds by entering the commands "toggleaitargets" and "debugdraw" in the debug console. The yellow circles around the devices indicate the range of the sounds, and if they're too small the reach the nearby walls, those walls won't be visible on the passive sonar.

**Comment by PaladynMinak** [comment] 2021-10-17 00:43
Sorry for the delay, I haven't much time lately. I'll do some tests and post feedback tomorrow.

**Comment by Regalis11** [comment] 2022-01-18 09:12
No known steps to repro, closing

**Closed by Regalis11** 2022-01-18 09:12 UTC
Labels: Bug, Need more info, Code
