### ISSUE TITLE
Mission Trigger Bugs for Kill Bandit Leader; bypassed somehow

### ISSUE THREAD

**Issue by Dopamin3** [Regalis11/Barotrauma#7578] opened 2021-12-02 15:24 UTC
I honestly don't know what the issue tracker is, or where to search it.

**Description**
Bug(s?)
Mission trigger for completion of Kill Bandit Leader quest at first abandoned station not triggered when all bandits eliminated. 
1. Mission listed as completed, but "Save and Quit" and re-entry bugs mission.
2. Mission Failed on station exit when all bandits were dead. No completion status listed on mission, attempted to do non-lethal acquisition of bandits and one seemed to die while off-screen in the hold of sub mysteriously, maybe by crew member. Did not trigger completion status on info mission tab.

**Steps To Reproduce**
1. Clear Bandits, Save and exit while still in station. Should bug mission.
2. Attempt to clear bandits again non-lethally, no completion trigger when cleared. 
3. Unsure if unconscious, non-lethal attempt at playthrough bugged it, as a Bandit died in the hold off-screen on the sub as I was clearing the rest of the station.

(I'm in an Orca, I have 7 crew members + Captain (8 people on the sub) as I just added Warner halfway through the first mission attempt.) 

**Version**
Current Steam Windows Version

**Comment by Regalis11** [comment] 2021-12-02 17:38
> I honestly don't know what the issue tracker is, or where to search it.

This is the issue tracker. :) You can search by typing in this field:
![image](https://user-images.githubusercontent.com/14351070/144474360-b90b7668-1bb8-4ada-859d-e636bd4abbc9.png)

**Comment by Regalis11** [comment] 2021-12-02 18:03
I gave this a quick test, but unfortunately couldn't get it to happen. After you saved, quit and reloaded the mission, did you still see the mission listed in the tab menu (or did you get the initial mission popup at the start of the round), or did it look like the mission wasn't active at all? Are you absolutely sure you found and killed the captain (who should be wearing a captain's uniform and body armor), and not just the "regular" bandits (who wear red outfits)?

**Comment by Dopamin3** [comment] 2021-12-02 22:31
Yes. I initially killed the bandit leader, then saved and reloaded, since
the quest was flagged as complete on info tab. I said hey, frick, I bet
given how stations work I'll have to redo the quest. Logged back in and
yeah, had to rekill all of them and tried to handcuff a guy to bring to
justice but he died.

Didn't get the victory trigger when they were cleared that second time, and
didn't get anything on station undock.

Had to quit game and then do it a third time.

**Comment by Dopamin3** [comment] 2021-12-02 22:32
Sorry saved and quit** then wondered if I broke the quest lol

**Comment by Dopamin3** [comment] 2021-12-02 23:37
If you guys need an IRL assistant I'm like an Arthur Dolittle; I'll slave
away honking a clown horn and ride a unicycle, make coffee and roll your
cigars or whatever.

My IRL eng/mech engineering/medicine/weapons/helm is actually decently high
as I was an engineering student, 20+ years in martial Arts, worked as
security, and I'm a gear head.

If you need a former-CEO turned intern lmk I have some free time each week
and I'd love to assist in anything regarding the barotrauma dev cycle. I'm
located in the USA so if it's Digitally, you could send spreadsheets you
need done or whatever.

I took some html courses on a postcode camp. Prob will get into programming
soon!


Lmk my discord is
SeroJ#3541
+1-657-2019467
+1-570-2809000

I LOVE YOUR ART


-Dru

**Comment by Regalis11** [comment] 2021-12-03 09:13
Thank you for your interest, but we're not hiring currently. :)

> So essentially when I logged back in the quest was still on the info tab
but now listed as incomplete. I believe that's intended?

It sort of is: the mission progress isn't saved if you save and quit mid-round. Although, this is kind of inconsistent with how things work in the "normal" non-outpost missions, in which you can't save and quit at all mid-round, so it's something we need to address.

As for the initial issue, I still couldn't figure out a way to reproduce it. :/ The only explanation I can think of is that the bandit leader was still alive (killing/arresting the rest of the bandits does nothing: the mission only cares about whether you killed the leader).

**Comment by Dopamin3** [comment] 2021-12-03 19:00
It might actually be something else. I have had the scan ruins mission also
not trigger as completed twice now as well.

**Comment by Dopamin3** [comment] 2021-12-03 19:01
I reformatted my pc and changed graphics drivers going to see if maybe it
was a weird bit flip on my computers end.

I'll let you know how it goes

**Comment by Dopamin3** [comment] 2021-12-04 22:34
Ok, third time. Fully scan alien ruins, get pop-up that ruins are scanned,
get to station and it shows failed for scan ruins.

**Comment by Dopamin3** [comment] 2021-12-06 17:58
I am bugtesting live on twitch... can direct you to various bugs as i
encounter them if you want? Scan ruins fails pretty consistently for me.

Also strange small things like i just died to husk parasite infection
randomly after mission completion of den clearage. No husks around, no
prior infection, no velyn eggs injection.. just sprouted the infection
randomly after a victory trigger.

**Comment by Regalis11** [comment] 2022-01-12 09:56
No known steps to repro, closing

**Closed by Regalis11** 2022-01-12 09:56 UTC
Labels: Bug, Need more info, Code
