### ISSUE TITLE
End level walls fail to block line of sight

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#11373] opened 2023-02-25 23:47 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The end level walls are supposed to be shadow-casting as well as blocking line of sight

![image](https://user-images.githubusercontent.com/73229309/221383023-e41068e2-681f-4127-8d89-2f8ceddd0ef1.png)

However in-game, they only partially do so:

![image](https://user-images.githubusercontent.com/73229309/221383031-1ef165d5-c0a6-4f80-bc12-e63616a28d5b.png)

You can see through the walls and past them, it also affects the Transparent setting.

-------

**IF FIXING THE LOS DOES NOT WORK FOR TECHNICAL REASONS:**

You can simulate some background chunks along the walls with biome parameters

This will hide the too obvious "naked" walls that make the end level seem to float in mid-air, it prevents gunners with maxed out periscopes to see beyond the walls

May require some fine-tuning, see the XML at the bottom with annotations

![image](https://user-images.githubusercontent.com/73229309/221385629-d95792d0-ff3d-43e3-8575-379aefc4d81d.png)

![image](https://user-images.githubusercontent.com/73229309/221385739-246801f2-927b-4262-abf4-ae8870157e1b.png)

![image](https://user-images.githubusercontent.com/73229309/221385663-a9b6e630-dbc9-4474-ab97-f4cd4ae940a3.png)

![image](https://user-images.githubusercontent.com/73229309/221385667-52d70b2d-440f-47aa-87e6-1d461f401796.png)

**EndBiome.xml**
Increased object limits for clusters to spawn, resized the level so the clusters spread around evenly on the mid level, changed outpost position to recenter the mid outpost. The added objects may or may not make the end level more performance heavy, but it should not matter too much without geometry. 
The changes to level size and outpost position do not seem to impact the final level from my lousy 2 AM tests, but if they do it may require creating two different biome settings for mid/final outposts

```xml
   <!-- the empty "outpost" levels in Jupiter -->
  
  <!-- increased level object limit -->
  <!-- increased width to allow clusters to spawn -->
  <!-- changed force outpost position to recenter the mid level -->
  <EndLocationOutpost
    identifier="endlocationoutpost"
    endbiome="true"
    biomes="endzone"
    Type="Outpost"
    Commonness="1"
    MinLevelDifficulty="0"
    MaxLevelDifficulty="100"
    AmbientLightColor="32,16,0,255"
    BackgroundTextureColor="153,102,51,255"
    BackgroundColor="153,102,51,255"
    WallColor="255,255,255,255"
    WaterParticleColor="255,153,153,102"
    StartPosition="0.1,0.5"
    EndPosition="0.9,0.5"
		
    ForceOutpostPosition="0.6,0.5"
    CreateHoleNextToEnd="False"
    CreateHoleToAbyss="False"
    NoLevelGeometry="True"

    LevelObjectAmount="5000"
    BackgroundCreatureAmount="0"

    MinWidth="150000"
    MaxWidth="150000"
    Height="50000"
    InitialDepthMin="300000"
    InitialDepthMax="300000"
    MinTunnelRadius="60000"
    SideTunnelCount="0,1"
    SideTunnelVariance="0.5"
    MinSideTunnelRadius="2000,6000"
    VoronoiSiteInterval="1500,9000"
    VoronoiSiteVariance="0,500"
    CellSubdivisionLength="500"
    CellRoundingAmount="0"
    CellIrregularity="0"
    MainPathNodeIntervalRange="30000,30000"
    MainPathVariance="0.1"
    CaveCount="0"
    ItemCount="0"
    ResourceIntervalRange="19200,38400"
    CaveResourceIntervalRange="9600,19200"
    ResourceClusterSizeRange="4,6"
    ResourceSpawnChance="0"
    CaveResourceSpawnChance="0.6"
    FloatingIceChunkCount="20"
    IslandCount="0"
    IceSpireCount="0"
    AbyssIslandCount="0"
    AbyssIslandSizeMin="4000,7000"
    AbyssIslandSizeMax="8000,10000"
    AbyssIslandCaveProbability="0.5"
    AbyssResourceClustersMin="10"
    AbyssResourceClustersMax="50"
    SeaFloorDepth="-100000"
    SeaFloorVariance="1000"
    MountainCountMin="0"
    MountainCountMax="0"
    MountainHeightMin="1000"
    MountainHeightMax="5000"
    RuinCount="0"
    MinWreckCount="0"
    MaxWreckCount="0"
    MinCorpseCount="0"
    MaxCorpseCount="5"
    ThalamusProbability="0"
    WreckHullFloodingChance="0.5"
    WreckFloodingHullMinWaterPercentage="0.1"
    WreckFloodingHullMaxWaterPercentage="1"
    BottomHoleProbability="1"
    WaterParticleScale="3"
    WaterParticleVelocity="-1000,0"
    WallTextureSize="512"
    WallEdgeTextureWidth="1000"
    FlashInterval="10,60"
    FlashColor="102,102,255,255"
    PlayNoiseLoopInOutpostLevel="True"
    WaterAmbienceVolume="0.05"
    WallEdgeExpandOutwardsAmount="256"
    WallEdgeExpandInwardsAmount="256">
    <WaterParticles
      texture="Content/Map/Biomes/EndBiome/BackgroundParticles.png" />
    <Wall
      texture="Content/Map/Biomes/HydrothermalWastes/LevelWall.png"
      premultiplyalpha="false" />
    <WallEdge
      texture="Content/Map/Biomes/HydrothermalWastes/LevelWallEdge.png" />
    <DestructibleWall
      texture="Content/Map/Biomes/DestructibleWall.png" />
    <DestructibleWallEdge
      texture="Content/Map/Biomes/DestructibleWallEdge.png" />
    <WallDestroyed
      texture="Content/Map/Biomes/DestroyedWall.png"
      premultiplyalpha="false" />
    <FlashSound
      file="Content/Sounds/Ambient/Thunder1.ogg" />
  </EndLocationOutpost>
```

**EndBiomeObjects.xml**
Very big chunks (too big?) with toned-down sprite color. Needs a minimum surface width to avoid clustering in the smaller more detailed areas

```xml

	<!-- chunks for end ruins -->
  <BackgroundChunks identifier="endbiomebackgroundchunks2" spawnpos="OutpostWall" minsurfacewidth="5000" minsize="2" maxsize="10" randomrotation="-180,180" commonness="0" depthrange="0,0" alignment="TopLeft, BottomRight" clusteringamount="0" clusteringgroup="0" alignwithsurface="False" swingamount="0" swingfrequency="0" scaleoscillation="0,0" scaleoscillationfrequency="0" sonardisruption="0" maxcount="10000000" randomoffset="100,100" spritecolor="50,50,50,255" >
    <overridecommonness leveltype="endzone" commonness="100" />
    <sprite texture="Content/Map/AlienRuins_CornerWebbing.png" sourcerect="497,358,533,519" depth="0.97" origin="0.5,0.5" />
    <sprite texture="Content/Map/AlienRuins_CornerWebbing.png" sourcerect="1043,334,585,610" depth="0.97" origin="0.5,0.5" />
    <sprite texture="Content/Map/AlienRuins_CornerWebbing.png" sourcerect="557,876,594,757" depth="0.97" origin="0.5,0.5" />
    <sprite texture="Content/Map/AlienRuins_CornerWebbing.png" sourcerect="1859,291,189,217" depth="0.97" origin="0.5,0.5" />
  </BackgroundChunks>
```

**Comment by Regalis11** [comment] 2023-02-26 10:16
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3366

**Closed by Regalis11** 2023-02-26 10:16 UTC
