### ISSUE TITLE
R-29 Big Rig "Custom Hatch" Out Of Reach

### ISSUE THREAD

**Issue by gerakis** [Regalis11/Barotrauma#7494] opened 2021-11-26 07:08 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I am trying to wire the upper docking hatch of my sub to auto shutdown my reactor to save power. Ive done this on different models of subs successfully. However, on the R-29 Big Rig sub the "custom hatch" (the one you can wire into) is too high off the floor to reach with a screwdriver while standing. If I climb the ladder I can access the wiring screen, but then my guy lets go of the ladder and I fall back out of range of the hatch, closing the wiring window. This seems all but unwireable in this condition. I have about a 1/3 of a second to do my wiring before falling out of range. Please lower the custom hatch enough so I can actually get to it.

**Steps To Reproduce**
Equip a screwdriver while playing, stand under the upper custom hatch (not the docking hatch, the CUSTOM hatch, there are two sprites) and try to access the hatch. You will find that you cannot. If you try to climb the ladder then you  will be able to reach it, but when you try to wire it you will let go of the ladder and fall out of range again.

**Version**
game version v0.15.13.0. Running Windows 10 x64.

**Additional information**

**Comment by Regalis11** [comment] 2021-11-26 08:14
Duplicate of https://github.com/Regalis11/Barotrauma/issues/5587

**Closed by Regalis11** 2021-11-26 08:14 UTC

**Comment by MaaiG** [comment] 2021-11-28 15:08
**gerakis**
Can’t connect to the R-29 docking airlock and fall down the stairs? Get water into the airlock and the stairs won’t be necessary.
