### ISSUE TITLE
[Unstable] Dead or alive failed and constantly repeated itself

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#12255] opened 2023-06-30 22:25 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Excuse the short story
So we were testing the traitor mode for a while today and i ended up as traitor, did a regular mission of crafting 8 handcuffs and did it sucessfully. The next round i got the "Dead or alive" mission. So i did the mission as usual, but managed to convince a crewmate to put on the needed items, even the "seen" part of the mission was sucessful. Issue is, it also failed at the same time, apparently me having been caught. Odd, but fine.
Now next round is things got really odd, first of all, the first issue:

After the "Dead or Alive" mission ends, the person with the card equipped on them will from then on have a blank name, instead of "Sootman" aslong as they keep the card equipped.

Now after the Dead or alive mission, i once again, after having failed it previously, got a traitor mission. That mission being: "Dead or Alive". 
So i did it again, same thing, person lived. Only this time, the state of being "seen" was never fulfilled, so i failed, again. So:

Recieved another traitor mission after failing it in the previous round (the exact same one)

And of course, the round after that, for the third time, after failing twice, i got another mission for "Dead or alive". And it happened exactly as previously, the victim fails to be recognized as "seen"

**Tdlr:I got "Dead or alive" 3 times in a row, it can also not be completed.**

Certainly an odd scenario

### Reproduction steps

Happened once, but heres the events
1.Recieve "Dead or Alive"
2.Do mission as asked
3.Get "caught" putting the evidence on them and fail the mission
4.From now on, repeatedly recieve "Dead or Alive" in following missions
5."Dead or Alive" cannot be completed anymore, vicitim never gets "seen" no matter what
(6.Look at a person wearing Sootmans card after the mission failed, their name will be blank in the round after)

### Bug prevalence

Just once

### Version

Other

### -

v1.1.2.0 (Unstable Traitors)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-07-03 08:34
Fixed the ID card in https://github.com/Regalis11/Barotrauma-development/commit/6d35d9971f7c3a87c64c882efb41971851cc89fa.

I could not find a way to get the event to repeat like that though, I think we'll need to do some more testing to find a way a reproduce that.

**Comment by Rehexr** [comment] 2023-07-05 20:52
So interesting development on this. The exact same thing happened to someone else this time round. 1 sucessful handcuff crafting mission, 3 times sootman mission in a row afterwards. Suppose that specific order is needed

**Comment by Jasontti** [comment] 2023-07-12 12:31
Tested.
deadoralive mission seems to be fixed* (One mystery case of not being able to discover evidence, could not be reproduced).
Closing for now.

**Closed by Jasontti** 2023-07-12 12:31 UTC
Labels: Bug, Need more info, Needs testing, Code
