### ISSUE TITLE
Game crashes once 100% loaded and an input is given

### ISSUE THREAD

**Issue by Wheatley1002** [Regalis11/Barotrauma#10813] opened 2022-12-24 18:15 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I am filing this report on behalf of HylianHeroine#2612. 

When I launch the game it loads to 100% then waits for me to give it an input to start the game and take me to the main menu. Instead, it shows the main menu background with the copyright info and game version on the bottom but no menu options. Just a blank background image. It will sit there like that forever until I try to click the mouse. At this point, it stops responding and I have no choice but to shut it down. Waiting for it to respond does nothing. 

I have tried uninstalling all mods, unsubscribing from the workshop, and deleting all workshop files and folders in the %appdata% folder. 

I have uninstalled and reinstalled the game multiple times on two separate storage drives but the game still crashes after an input at 100% loaded.

I have tried launching different betas to see which would work and which wouldn't and the unstable branch seems to launch and play fine while the current build and the faction test build both crash when I press a key at 100% loaded.

### Bug prevalence

Just once

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by HawkinsThe71st** [comment] 2023-01-09 07:48
Possibly related issue but I have noticed that attempting to launch the game in the current stable version (0.20.16.1) while there is a save created in the unstable version (0.21.0.0) in the saves folder results in the game freezing on the main menu.
Recently attempted to launch the game with an unstable save again and managed to not have the game close, game was running very slow with the debug console open with this error here:
[consoleOutput.txt](https://github.com/Regalis11/Barotrauma/files/10371345/consoleOutput.txt)

**Comment by Rokvach** [comment] 2023-01-18 14:57
Tested, I didn't notice any issues running Unstable saves in Stable, seems to be working correctly. Closing.

**Comment by NilanthAnimosus** [comment] 2023-01-19 12:56
Just going to attach what this original issue looks like in practice for future reference:

![image](https://user-images.githubusercontent.com/29177976/213447574-bd27b128-be18-4908-a6ad-26bff0d91e7d.png)

But it isn't strictly a crash as much as the menu not rendering or the game freezing after the loading screen.

It is worth noting this issue appeared around the time of Christmas (with the patches for workshop fixes and such) - troubleshooting included running the game without steam, validating game, removing the workshop installed folder, unsubscribing all mods with the above. temporary renaming of save folder directories (essentially removing them) and wiping the game folder. game entered this state on essentially a completely clean copy.

Did the same for the faction testing branch at that time but did launch unstable, however that crashed (without crash report, possibly froze?) on entering the server browser.

this issue is unrelated to the timestamp errors caused by datetime representation being in unstable (then switching branches back to stable) from around Christmas, which neither causes the game to freeze/crash and instead throws a console error if those files are left in.

**Comment by Wheatley1001** [comment] 2023-01-29 19:28
Howdy! This issue now happens to me :D Kinda ironic considering I posted this to help someone else with this issue, but here's my perspective. 

### Key Information
CURRENT STABLE - 0.20.16.1
BUILD LAST PLAYED - 100.17.0.0
There is **no** crash log produced.

### Issue Report
I wanted to play stable with friends who haven't seen the faction branch of the game. Upon changing my game from the faction branch onto the stable branch, the game hard crashes 100% of the time regardless of the situation. If the three intro screens are skipped, the game loads until 70% and then crashes. If the intro screens are not skipped, the game crashes on the third screen. Crashing causes an immediate closure of the game, booting me to the desktop. 

I have tried to validate files and Steam detected two missing files. Upon reacquiring them, the game now loads to 85% before repeating the same issue. Steam no longer recognises missing files and claims all files are valid.

I will be trying the workaround methods (deleting all of my save files and save folder), but I wanted to inform you all that this issue still persists.

**Comment by Regalis11** [comment] 2023-08-23 12:41
It seems this has been fixed since the ticket was created

**Closed by Regalis11** 2023-08-23 12:41 UTC
Labels: Bug, Need more info, Code, Crash
