### ISSUE TITLE
STARTGAMEFINALIZE error kicking specific VPN-using player to lobby, will not allow said player to spectate

### ISSUE THREAD

**Issue by tomacatx2** [Regalis11/Barotrauma#11936] opened 2023-05-01 16:53 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Launching a round with lots of spawn events (like Pirate rounds) kicks player who is using a VPN back to lobby, does not let them spectate, happens only for one player, despite other players in the same server using VPNs as well. Server isn't able to sync submarine list or lobby settings with the player (it shows up empty for them).  
Something to do with packet size exceeding a limit? I've been told that the packet used for syncing lobby settings and submarine list with a client is Extremely Large, and that it is probably being dropped in this case.

Error encountered on the players side : Error while starting the round (did not receive STARTGAMEFINALIZE message from the server) Returning to lobby...
On the host side the console just spams a lot of FAILED TO SEND MESSAGE TO [IP], PACKET DROPPED messages and some sort of weird list of Chinese IPs (Player in question is not in China), see attached images and server log pastebin.

Steps taken to remedy this issue : 
Full reinstall of game and server settings on both client and server (Didn't work)
Increasing MTU limit in the OS of both client and server to 5KB (Didn't work)
Turning off VPN (Worked)

Hosting on a dedicated server.

![err2](https://user-images.githubusercontent.com/36746617/235491580-233c732f-d613-4f1f-ac41-b19a47a4a6f8.png)
![err1](https://user-images.githubusercontent.com/36746617/235491583-c344c966-9f67-4ae9-a6ff-a0722e0b7b2c.png)

### Reproduction steps

1. Launch dedicated server.
2. Have the Player In Question join.
3. Launch a round, Pirate hunt rounds have 100% kick-back-to-lobby efficacy.
4. Player in Question : gets kicked back to lobby, whenever they click the Spectate button they get errors in the console. (Same ones as before)

### Bug prevalence

Happens regularly

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
https://pastebin.com/hRPygrpN
```

**Comment by Regalis11** [comment] 2023-05-02 06:39
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10098

**Closed by Regalis11** 2023-05-02 06:39 UTC
