### ISSUE TITLE
Items placed on the floor spawn if shuttle is spawned as main ship, but items don't spawn when the shuttle spawns as a respawn shuttle

### ISSUE THREAD

**Issue by GGSnipa** [Regalis11/Barotrauma#109] opened 2017-12-09 11:24 UTC
I first noticed it when the depth charge shells didn't spawn on my newly made respawn shuttle. I'm using Chiko's Barotrauma Extended mod if that changes anything.

**Comment by Regalis11** [comment] 2018-01-24 14:14
Duplicate of #234. I'll close this one and keep the newer issue because it describes the problem more accurately.

**Closed by Regalis11** 2018-01-24 14:14 UTC
Labels: bug
