### ISSUE TITLE
[Modding] Changing the turrets sound may silent them.

### ISSUE THREAD

**Issue by ghost** [Regalis11/Barotrauma#2865] opened 2020-05-19 22:15 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When a coilgun or a railgun are getting overrided via a mod changing their sounds (for instance RailgunLoop.ogg) they will randomly turn silent, with the expection of the firing sound wich is working perfectly fine.

**Steps To Reproduce**

**Step 1 :** Create a mod that change the Start or Stop or Loop sound of a coilgun/railgun

**Step 2 :** Activate the mod

**Step 3 :** Try the new guns sounds by moving the turrets in any directions.

**Note :** This issue is very inconsistent and may need multiple rounds restart before encountering it. It seems that the more guns there is on a submarine, the higher chance you have to stumb on it.

**Version**
Barotrauma release 0.9.9.1 - Windows 10 updated

**Additional information**

Sometimes, only one gun have all the sound while the others are silent.

**Comment by Regalis11** [comment] 2020-05-20 13:43
This could potentially be caused by a long start/stop sound. If there are too many sounds playing at the same time (16 to be exact), the game won't play any additional ones. You can see the currently playing audio channels by entering the command "debugdraw" and pressing Ctrl + S: if you could post a screenshot of that view when this bug occurs it would help us a lot in diagnosing it!

**Comment by Ant1V1RU5** [comment] 2020-05-20 14:17
Both Railguns + Coilguns sound length are 3 seconds, Start/Stop sounds are under 1 second.
Here is the screenshot you asked, it was on an unmodified Kastrull and no systems active (reactor and ventilation included).
![image](https://user-images.githubusercontent.com/62913364/82457069-4d9b4180-9ab5-11ea-8008-b755b6a98cd4.png)
In this example, the turrets were all silent, with the exception of the firing sound.

**Comment by Ant1V1RU5** [comment] 2020-05-20 14:23
Here are the sounds i used for the turrets :
[Turrets_Sounds.zip](https://github.com/Regalis11/Barotrauma/files/4657415/Turrets_Sounds.zip)

Here are the modded coilgun.xml and railgun.xml : 
[Coilgun + Railgun.zip](https://github.com/Regalis11/Barotrauma/files/4657428/Coilgun.%2B.Railgun.zip)

**Comment by Rokvach** [comment] 2022-04-27 09:46
Tested, working correctly. Closing.

**Closed by Rokvach** 2022-04-27 09:46 UTC
Labels: Bug, Code, Modding, Medium Prio
