### ISSUE TITLE
(System.UnauthorizedAccessException) causes game crash

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11522] opened 2023-03-14 16:07 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Upon downloading the new update, the game crashes pretty consistently. I'm filing a report on behalf of another user so I'm not intimate with the specifics. 

Exception: Access to the path 'D:\SteamLibrary\steamapps\common\Barotrauma\Content\Effects\waterbump.png' is denied. (System.UnauthorizedAccessException)    is the main error log, but there were other issues (you can find in the attached full error log) such as failing to load the config_player.xml file. 

### Bug prevalence

Happens regularly

### Version

v1.0.7.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 03/14/2023 22:05:00)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

71290F513E6B598EAA3CFF037A2EAB34

Game version 1.0.7.0 (ReleaseWindows, branch release/1.0, revision e1df60d5cc)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: None
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit
    GPU name: NVIDIA GeForce RTX 3070
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Access to the path 'D:\SteamLibrary\steamapps\common\Barotrauma\Content\Effects\waterbump.png' is denied. (System.UnauthorizedAccessException)
Target site: Microsoft.Win32.SafeHandles.SafeFileHandle CreateFile(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, System.IO.FileOptions)
Stack trace: 
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
   at Barotrauma.IO.File.Open(String path, FileMode mode, FileAccess access, Nullable`1 share) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SafeIO.cs:line 410
   at Barotrauma.IO.File.OpenRead(String path) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SafeIO.cs:line 415
   at Barotrauma.TextureLoader.FromFile(String path, Boolean compress, Boolean mipmap) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Utils\TextureLoader.cs:line 193
   at Barotrauma.WaterRenderer..ctor(GraphicsDevice graphicsDevice) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\Levels\WaterRenderer.cs:line 71
   at Barotrauma.GameMain.LoadContent() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 404
   at Microsoft.Xna.Framework.Game.Initialize() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 551
   at Barotrauma.GameMain.Initialize() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 372
   at Microsoft.Xna.Framework.Game.DoInitialize() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 678
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 381
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[03/14/2023 22:05:00] WARNING: Failed to load creature metrics from creature_metrics.xml!
[03/14/2023 22:05:00] Couldn't load xml document "creature_metrics.xml"! {Access to the path 'D:\SteamLibrary\steamapps\common\Barotrauma\creature_metrics.xml' is denied.}
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
   at Barotrauma.IO.File.Open(String path, FileMode mode, FileAccess access, Nullable`1 share) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SafeIO.cs:line 410
   at Barotrauma.XMLExtensions.TryLoadXml(String filePath, Exception& exception) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Serialization\XMLExtensions.cs:line 95
[03/14/2023 22:05:00] Couldn't load xml document "config_player.xml"! {Access to the path 'D:\SteamLibrary\steamapps\common\Barotrauma\config_player.xml' is denied.}
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
   at Barotrauma.IO.File.Open(String path, FileMode mode, FileAccess access, Nullable`1 share) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SafeIO.cs:line 410
   at Barotrauma.XMLExtensions.TryLoadXml(String filePath, Exception& exception) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Serialization\XMLExtensions.cs:line 95
[03/14/2023 22:04:59] Logged in as Meowbo (SteamID STEAM_1:1:432508239)
```

**Comment by Regalis11** [comment] 2023-03-15 16:35
No steps to repro, and potential duplicate of https://github.com/Regalis11/Barotrauma/issues/11489. Closing

**Closed by Regalis11** 2023-03-15 16:35 UTC

**Comment by Elpatov** [comment] 2023-03-16 02:52
We have indeed found a solution to this problem. You need to grant full access to the root folder of the game. Do this as follows:

Right-click on the folder E:\SteamLibrary\steamapps\common\Barotrauma <—;
Select the "Security" section - change permissions - Change
Check the box for "Full access" for your user (preferably for both the user and the administrator);
Wait for the settings to be applied and close this window;
Select the "Security" section - advanced;
Check the box at the bottom "Replace all entries ..." at the very bottom of the window that opens;
Remove the "Read-only" attribute for this folder
After that, you need to delete the file E:\SteamLibrary\steamapps\common\Barotrauma\config_player.xml .

Unsubscribe if it helped you.
