### ISSUE TITLE
Barotrauma audio input/mic frozen

### ISSUE THREAD

**Issue by CometVoid** [Regalis11/Barotrauma#9511] opened 2022-07-02 19:35 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Barotrauma's audio input freezes near instantaneously, making the in-game voice chat impossible to use.

On changing the audio input source and hitting apply, it will detect audio for less than a second normally, (or at least the noise gate threshold bar moves) and then immediately freeze again. This may be an incompatibility with Pipewire, as I have had similar issues with discord after switching from Pulseaudio (because it's now deprecated) to Pipewire. This may be an issue with easyeffects instead of pipewire (the replacement to pulseeffects)

I haven't tested if this bug prevails with pulseaudio, as I really don't want to deal with the annoyance that is removing pipewire and then re-installing pulseaudio

My distro is Pop!_OS

EDIT: Launching the game in proton experimental fixes this problem.

### Reproduction steps

1: open the game and try to speak

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Linux

**Comment by itchyOwl** [comment] 2023-02-21 10:10
Is this an issue in the game? Can we even fix it?

**Comment by Jasontti** [comment] 2023-06-15 10:54
Could not reproduce with pipewire 0.3.19, debian 11.
Tested with current dev build and stable from steam.

>EDIT: Launching the game in proton experimental fixes this problem.

Closing ticket

**Closed by Jasontti** 2023-06-15 10:54 UTC
Labels: Bug, Code
