### ISSUE TITLE
My game crashed when I clicked tab

### ISSUE THREAD

**Issue by FranchiThePingu** [Regalis11/Barotrauma#3728] opened 2020-09-04 23:16 UTC
[crashreport_object.log](https://github.com/Regalis11/Barotrauma/files/5177280/crashreport_object.log)

**Comment by Regalis11** [comment] 2020-09-05 09:42
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3517

**Closed by Regalis11** 2020-09-05 09:42 UTC
Labels: Bug, Code, Crash
