### ISSUE TITLE
[0.1200.0.0] Outposts - NPC going around stacking Oxygen Tanks like crazy in outposts.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4480] opened 2020-12-11 20:02 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I was in the crew quarter of an outpost and I noticed that NPC keeps going into it. I opened up the cabinets and notice they kept stacking oxygen tanks into them right at the start of the round.

**Version**
0.1200.0.0

**Comment by Kaillera** [comment] 2021-01-04 23:07
There also seems to be a strange diving suit spawning in outpost that the NPC just casually leaves on the floor.

**Comment by Rokvach** [comment] 2021-01-04 23:20
Diving suits as well as oxygen tanks were added all over the outpost as a measure to combat flooding

The loose oxygen tanks can be found in front of the diving suit lockers and the loose diving suits are just scattered around, either they were accidentally left there or it was just a extra measure to make sure that there's enough around. Especially there seems to be a lot of oxygen tanks everywhere.

**Comment by Regalis11** [comment] 2021-01-19 14:09
Could've been caused by https://github.com/Regalis11/Barotrauma/issues/4784

**Comment by Rokvach** [comment] 2021-01-19 14:33
Yes I think this was due to all the oxygen tanks laying on the floor and NPC's cleaning them up. Closing.

**Closed by Rokvach** 2021-01-19 14:33 UTC
Labels: Bug, Code
