### ISSUE TITLE
Explosive slug explodes in your hands

### ISSUE THREAD

**Issue by Abkim27** [Regalis11/Barotrauma#12415] opened 2023-07-25 11:44 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While i was outside of sub in sub editor, shooting explosive slug from riot shotgun into emptiness made it explode right beside me. It seems that it does not find a spot where it needs to explode, so it just explodes right where it was shot from.

https://github.com/Regalis11/Barotrauma/assets/100293037/cb672831-71e8-429c-91a2-dd9b34317ed9

### Reproduction steps

1.Load any shotgun with explosive slug shells.
2.Shoot into the void.

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Linux

**Comment by AdamH-Daedalic** [comment] 2023-07-31 10:54
Tested on v1.0.21.0 and also release/traitor-update

I'm only able to reproduce this in the sub editor when outside the sub, it doesn't seem to happen in singleplayer or multiplayer for me on either build. The explosion/shockwave appears to originate from the gun instead of the site of impact, which won't exist if fired into the abyss of the editor.

**Comment by Abkim27** [comment] 2023-07-31 11:05
> Tested on v1.0.21.0 and also release/traitor-update
> 
> I'm only able to reproduce this in the sub editor when outside the sub, it doesn't seem to happen in singleplayer or multiplayer for me on either build. The explosion/shockwave appears to originate from the gun instead of the site of

**Comment by Abkim27** [comment] 2023-07-31 11:05
⅞

**Comment by Abkim27** [comment] 2023-07-31 11:09
Sorry, tapped wrong button.
I did get it working on map before i opened issue, although i made it by shooting on start location into the direction of abyss, so it seems you need to have a **very** long distance shot.

**Comment by itchyOwl** [comment] 2023-08-02 06:33
I'll try to repro and debug it.

**Comment by itchyOwl** [comment] 2023-08-08 07:50
Fixed in Regalis11/Barotrauma-development@d0a8012. Just changed the status effect type from "OnUse" to "OnImpact". "OnUse" is triggered when the projectile is shot, not when the projectile hits, but it seems to have worked for hitscan projectiles because their position was set before triggering the status effects. Didn't debug why it only occured in subeditor, but I guess it's because normally the weapon would almost always hit something. It's possible that this issue originates from the status effect refactorings, where iirc triggering the "OnUse" was changed.

**Comment by Jasontti** [comment] 2023-08-18 07:43
Tested.
No issues found.
Closing ticket.

**Closed by Jasontti** 2023-08-18 07:43 UTC
Labels: Bug, Code
