### ISSUE TITLE
Server kick 

### ISSUE THREAD

**Issue by d3mever** [Regalis11/Barotrauma#2726] opened 2020-04-27 19:30 UTC
**All players kick out of the game when starting a new round**

**Steps To Reproduce**
That was happening in random time when company game round begins. Various сauses. (Not every start round)

**Version**
Windows 10 home, Barotrauma version: 0.9.9.0

**Text from logs**
 Game mode: Кампания (Company)
[27.04.2020 20:10:57]
  Submarine: [vanil] Aegir Mark VS Saburram
[27.04.2020 20:10:57]
  Level seed: RandkluftTara
[27.04.2020 20:10:57]
  Round started.
[27.04.2020 20:10:57]
  Иван Дружинников (6) has reported an error: Received an update for an entity that doesn't exist (event id 776, entity id 35272).
[27.04.2020 20:10:57]
  Иван Дружинников (6) покидает сервер. Причина: Kicked
Причина: Received an update for an entity that doesn't exist (event id 776, entity id 35272).
[27.04.2020 20:10:58]
  Игрок Иван Дружинников (6) исключен с сервера Причина: Received an update for an entity that doesn't exist (event id 776, entity id 35272).
[27.04.2020 20:10:58]
  Блэйк Гриффин (5) has reported an error: Missing entity Barotrauma.Level (event id 775, entity id 4164).
[27.04.2020 20:10:58]
  Блэйк Гриффин (5) покидает сервер. Причина: Kicked
Причина: Missing entity Barotrauma.Level (event id 775, entity id 4164).
[27.04.2020 20:10:58]
  Игрок Блэйк Гриффин (5) исключен с сервера Причина: Missing entity Barotrauma.Level (event id 775, entity id 4164).
[27.04.2020 20:10:58]
  Heinrich Mahler (18) has reported an error: Received an update for an entity that doesn't exist (event id 776, entity id 35277).
[27.04.2020 20:10:58]
  Heinrich Mahler (18) покидает сервер. Причина: Kicked
Причина: Received an update for an entity that doesn't exist (event id 776, entity id 35277).
[27.04.2020 20:10:58]
  Игрок Heinrich Mahler (18) исключен с сервера Причина: Received an update for an entity that doesn't exist (event id 776, entity id 35277).
[27.04.2020 20:10:58]
  Даня Бахич (99) has reported an error: Received an update for an entity that doesn't exist (event id 376, entity id 50920).
[27.04.2020 20:10:58]
  Даня Бахич (99) покидает сервер. Причина: Kicked
Причина: Received an update for an entity that doesn't exist (event id 376, entity id 50920).
[27.04.2020 20:10:58]
  Игрок Даня Бахич (99) исключен с сервера Причина: Received an update for an entity that doesn't exist (event id 376, entity id 50920).
[27.04.2020 20:10:58]
  Фауст Шлиттер (77) has reported an error: Missing entity Barotrauma.Level (event id 775, entity id 4164).

Starting a new round...
[25.04.2020 19:30:06]
  Game mode: Кампания
[25.04.2020 19:30:06]
  Submarine: [vanil] Aegir Mark VS Saburram
[25.04.2020 19:30:06]
  Level seed: TopolBramerton
[25.04.2020 19:30:06]
  Round started.
[25.04.2020 19:30:06]
  Иван Дружинников (6) has reported an error: Received an update for an entity that doesn't exist (event id 458, entity id 3843).
[25.04.2020 19:30:06]
  Иван Дружинников (6) покидает сервер. Причина: Kicked
Причина: Received an update for an entity that doesn't exist (event id 458, entity id 3843).
[25.04.2020 19:30:07]
  Игрок Иван Дружинников (6) исключен с сервера Причина: Received an update for an entity that doesn't exist (event id 458, entity id 3843).
[25.04.2020 19:30:07]
  Jan Nevel (1307) has reported an error: Missing entity Barotrauma.Hull (event id 502, entity id 2915).
[25.04.2020 19:30:07]
  Jan Nevel (1307) покидает сервер. Причина: Kicked
Причина: Missing entity Barotrauma.Hull (event id 502, entity id 2915).
[25.04.2020 19:30:07]
  Игрок Jan Nevel (1307) исключен с сервера Причина: Missing entity Barotrauma.Hull (event id 502, entity id 2915).

Other type kick causes (All players)
The whole game literally don't loads.
[event_error_log_client_Фёдор Сухов (3)_1530.log](https://github.com/Regalis11/Barotrauma/files/4541610/event_error_log_client_.3._1530.log)
[event_error_log_client_Фёдор Сухов (3)_1530.log](https://github.com/Regalis11/Barotrauma/files/4541558/event_error_log_client_.3._1530.log)
[event_error_log_client_Фёдор Сухов (3)_1610.log](https://github.com/Regalis11/Barotrauma/files/4541561/event_error_log_client_.3._1610.log)

Sorry, i plays Russian baro version and therefore logs also on Russian.

**Comment by Regalis11** [comment] 2020-04-28 07:49
Duplicate of #2683.

**Closed by Regalis11** 2020-04-28 07:49 UTC
