### ISSUE TITLE
Overriding exception: Failed to add a prefab / a prefab with the same identifier already exists; try overriding

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#7666] opened 2021-12-08 00:00 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
This exception happens when a mod that overrides another mod is loaded first. When the original mod tries to load, it not only (correctly) shows a hashing collision, but also an exception that shouldn't appear.
![Barotrauma_guuo9xhwuk](https://user-images.githubusercontent.com/10529134/145124349-bbb906b7-493c-42b1-8696-e5bfa83a0e02.png)
![Barotrauma_TF9mix0nhF](https://user-images.githubusercontent.com/10529134/145124355-d03a1772-c51f-4364-af01-4c76778472f7.png)

**Steps To Reproduce**
1. Have 2 mods: EK Utilities and Hazardous Reactors
https://steamcommunity.com/sharedfiles/filedetails/?id=1946765892
https://steamcommunity.com/sharedfiles/filedetails/?id=2547888957
2. Enable Hazard Reactors below EK Utilities
3. Enable EK Utility. This error will also show up when a campaign is loaded with EK Utilities above HR on the host's load order.

**Version**
v0.15.13

**Additional information**
It's a low/med-prio issue, **doesn't break anything** but the exception shouldn't keep appearing

**Comment by Regalis11** [comment] 2021-12-08 08:31
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7328

**Closed by Regalis11** 2021-12-08 08:31 UTC

**Comment by Krzeszny** [comment] 2021-12-08 12:24
> Duplicate of #7328

It is partially a duplicate but here I tried to stress the fact that the long exception shouldn't spam the console. An error, such as the hashing error is fine.

**Comment by Regalis11** [comment] 2021-12-08 17:19
In my opinion the exception should appear, because it explains what went wrong (= trying to add another prefab with the same identifier). I'd even argue that the hashing collision error isn't necessary, because the "duplicate" item is ignored, so the collision doesn't matter.
