### ISSUE TITLE
I found a bug where the pet attacked all friendly units

### ISSUE THREAD

**Issue by CSJ108** [Regalis11/Barotrauma#12011] opened 2023-05-15 15:00 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Hope pets and crew don't attack each other

### Reproduction steps

when I entered the abandoned outpost with the pet, after the pirates dealt damage to me, I brought the pet back to the sub, the pet would see all friendly units (including other pets) except the owner as enemies and attack them, and then was killed by my crew, petraptor and defensebot were the same. I have tried many times, the premise of this bug is that the pirate at the outpost attacks the owner of the pet, if the owner is not harmed, then everything will be fine after returning to the submarine with the pet, once the pirate has done damage to the owner, the pet will see friendly units as enemies as well. Another thing that is very uncomfortable is that when the enemy invade, when the pet attacks the enemy, it accidentally hurts the crew, the crew will also kill it, can you ask the crew not to attack it because of the pet's accidental injury?

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by CSJ108** [comment] 2023-05-15 15:15
The last sentence was misspoken，can you ask the crew not to attack it because of the pet's accidental friendly fire

**Comment by Regalis11** [comment] 2023-05-15 21:08
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11514

**Comment by CSJ108** [comment] 2023-05-20 17:22
https://github.com/Regalis11/Barotrauma/assets/103619340/6f3a44e2-1437-4f97-914f-16cb1aa54728

**Comment by Regalis11** [comment] 2023-05-27 13:38
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f8c110ee23c0a8c9f08bf84cea702183b34683be

**Comment by Rokvach** [comment] 2023-06-01 10:12
Tested, working correctly. Closing.

**Closed by Rokvach** 2023-06-01 10:12 UTC
Labels: Bug, Code
