### ISSUE TITLE
Game crashes in singleplayer or multiplayer. Started after recent update. 

### ISSUE THREAD

**Issue by gartanium** [Regalis11/Barotrauma#2747] opened 2020-05-01 01:47 UTC
Barotrauma Client crash report (generated on 4/30/2020 7:26:59 PM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

023CCD07C102F6331CAD29D2EADB01E0

Game version 0.9.9.1 (ReleaseWindows, branch release, revision 1968ab79f)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: HuyZfwNu
Loaded submarine: Azimuth (809F113A20172C801D4C18A2EE5B0A12)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)

System info:
    Operating system: Microsoft Windows NT 10.0.18362.0 64 bit
    GPU name: NVIDIA GeForce GTX 1050 Ti
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void UpdateWaterAmbience(Single, Single)
Stack trace: 
   at Barotrauma.SoundPlayer.UpdateWaterAmbience(Single ambienceVolume, Single deltaTime)
   at Barotrauma.SoundPlayer.Update(Single deltaTime)
   at Barotrauma.GameMain.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Barotrauma.Program.Main(String[] args)

Last debug messages:
[4/30/2020 7:26:49 PM] Lobby created!
[4/30/2020 7:26:35 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[4/30/2020 7:26:34 PM] Content package load order: Vanilla 0.9
[4/30/2020 7:26:34 PM] Content package load order: Vanilla 0.9
[4/30/2020 7:26:33 PM] ALC device creation failed too many times!
[4/30/2020 7:26:33 PM] ALC device initialization attempt #3 failed: device is null
[4/30/2020 7:26:33 PM] ALC device initialization attempt #2 failed: device is null
[4/30/2020 7:26:33 PM] ALC device initialization attempt #1 failed: device is null
[4/30/2020 7:26:33 PM] Attempting to open ALC device "OpenAL Soft"
[4/30/2020 7:26:32 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[4/30/2020 7:26:32 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[4/30/2020 7:26:30 PM] Logged in as hij (SteamID STEAM_1:1:26031582)

**Comment by Regalis11** [comment] 2020-05-03 11:30
It seems the game fails to open an audio device for some reason, and crashes when it tries to play the water ambience sounds. Do you have some kind of audio device (headset, speakers) connected? If not, connecting one should get rid of this error. But in any case, we need to also make sure the game doesn't crash even if there is no audio device present.

**Comment by Regalis11** [comment] 2020-05-03 11:51
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/54436c70941ae9bd069131bcc5678d8c1f6298a3

**Comment by Rokvach** [comment] 2020-05-03 22:20
I wasn't able to reproduce this, by removing/disabling all of my audio devices, so seems to be working correctly. Closing.

**Closed by Rokvach** 2020-05-03 22:20 UTC
Labels: Bug, Code, Crash
