### ISSUE TITLE
[dev] crash in character editor when creating a new character

### ISSUE THREAD

**Issue by etet2** [Regalis11/Barotrauma#1116] opened 2019-02-11 19:28 UTC
clicking next in ragdoll creation menu crashes the game. i'm pretty definate it is because limbs and joints need to be added first but i've tried multiple times and can't get it to work. it should tell you what's wrong instead of crashing

**Comment by itchyOwl** [comment] 2019-02-12 10:20
You should only need to define the Torso limb. But there was a couple of cases where the game could crash. One was that the texture path was invalid. Another was that the limb dimensions were invalid (smaller than 2). Should be fixed by commits 58467c8, 3c6ca1e, and 4802c4f respectively. You also gave me crash log, but that I cannot reproduce. To me, it seems that the game couldn't find the vanilla content, which is a required core package. Did you somehow manage to unselect or rename the vanilla content file?

**Comment by etet2** [comment] 2019-02-12 11:19
I was running my mod as core content package - Barotrauma erect. It is on workshop if you want to test it

**Closed** 2019-02-12 12:47 UTC
Labels: Crash, dev branch, need more info
