### ISSUE TITLE
Crash - Played a singleplayer level, and then docked at next outpost. Crashed on round summary.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3655] opened 2020-08-28 15:27 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/5142867/crashreport.2.log)

**Steps To Reproduce**

0. Had 10 Crew. 1 Captain/Medic/Security, 2 Engineers/Mechanics, 3 Assistants
1. Left an outpost with a Terminate Thresher Swarm mission.
2. Looted 3 artifacts from the sea floor. Thermal, Psychosis, Nasanov.
3. Looted a Hemulen Wreck with 4 corpses.
4. Defeated the Swarm of Threshers for the mission.
5. Reach the end of the level.
6. Docked to the outpost and get the Round Summary.
7. ??? Crashed.

**Version**
10.4.0

**Additional Informations**
Was able to load the save to the outpost just fine. No issues it seems.

**Comment by Kaillera** [comment] 2020-08-28 17:39
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/5143416/crashreport.log)

**Steps To Reproduce**

0. Had 12 Crew. 1 Medic, 2 Captain. 2 Engineers/Mechanics, 3 Assistants, 2 Security Officers
1. Left an outpost to go to another outpost.
2. ??? Crashed.

**Version**
10.4.0

**Additional Informations**
Was able to load the save to the outpost just fine. No issues it seems.

**Comment by Regalis11** [comment] 2020-08-31 06:51
Duplicate of #3494

**Closed by Regalis11** 2020-08-31 06:51 UTC
Labels: Bug, Code, Crash
