### ISSUE TITLE
Water detector not applying new 'Output' settings unless you press Enter

### ISSUE THREAD

**Issue by Lynkzz** [Regalis11/Barotrauma#1188] opened 2019-02-23 22:40 UTC
**Description**
When changing the TrueOutput orFalseOutput settings on a water detector it doesn't seem to apply them unless you specifically press Enter after changing it. The UI will show the new settings, even after you exit and enter it again, but it will not actually be applied (so if the water detector is set to sound an alarm when no water is present, if you change it to not sound an alarm when there's no water in this manner, the alarm will continue sounding even though the UI says it shouldn't - You need to re-click the field and press enter for it to apply).

**Steps To Reproduce**
- Open water detector UI
- Change any setting
- Do NOT press Enter
- Click on the text field for the other value
- Do whatever (exit out)
The first value's change will not apply because you didn't press Enter but the UI will show the change

**Version**
0.8.9.3 (Steam Closed Alpha)

**Additional information**
This happens often if you want to change multiple settings at a time (When you change the first one and then instead of pressing enter and exiting out of the UI you click on the other value, change it, then exit out).

**Comment by rico6822** [comment] 2019-02-23 23:01
By pressing enter you confirm the changes you want to make. This was made to prevent water detector from going crazy while your are changing values. This is not a bug.

**Comment by Lynkzz** [comment] 2019-02-23 23:03
Sure, but if you go to the next value and press Enter on that one the UI will show the first value's change as well (even when you exit out) even when it's not 'active.'

**Comment by Regalis11** [comment] 2019-05-22 10:58
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).

**Closed by Regalis11** 2019-05-22 10:58 UTC
Labels: Code, Feature request
