### ISSUE TITLE
Ragdoll NullReferenceException Crash

### ISSUE THREAD

**Issue by MKeremBirkan** [Regalis11/Barotrauma#6710] opened 2021-09-21 00:43 UTC
-  [yes] I have searched the issue tracker to check if the issue has already been reported.

I fount similar error about ragdoll is here (https://github.com/Regalis11/Barotrauma/issues/6627)

Me and two friends with only one game mode which is a ship ( https://steamcommunity.com/sharedfiles/filedetails/?id=2551865251&searchtext=Hephaestus ) . We were on ailien artifact base then my friend took a artifact from base and came back to ship. Later on, game was crashed. I think sever could not edit one ragdolls of a obcject then crashed, It happened one time and I added crash report on this post. We played many time with all mission , didnt happend before.

Regards. 
.

**Version**
Barotrauma Client crash report (generated on 16.09.2021 21:49:08)
Game version 0.14.9.1 
Microsoft Windows 10 - IS Version 19041.1237

[crashreport.log](https://github.com/Regalis11/Barotrauma/files/7199304/crashreport.log)

**Comment by Regalis11** [comment] 2021-09-21 07:12
Thank you for the report! This seems to have been caused by the same issue as https://github.com/Regalis11/Barotrauma/issues/6627, should be fixed in the next update.

**Closed by Regalis11** 2021-09-21 07:12 UTC
Labels: Bug, Code, Crash
