### ISSUE TITLE
Crashes during online campaign - Crash reports included.

### ISSUE THREAD

**Issue by snackbarxx** [Regalis11/Barotrauma#4267] opened 2020-11-09 23:45 UTC
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Crashing about 5-15 mins in to a campaign on a custom sub, with mods on.

**Steps To Reproduce**
Unsure, happened each time we left the dock and were in transit at the very beginning of the campaign, whilst heading to the first mission each time. Occured 4 times in total, over 2 seperate hosts. Tried turning off most mods that weren't required by the custom sub, to no avail. 

**Version**
0.10.6.2 - All 4 users on Windows 10.

**Additional information**
Crash happens simultaniously to everyone on the server. Crash report(s) attached. 
[crashreport (1).log](https://github.com/Regalis11/Barotrauma/files/5513869/crashreport.1.log)
[crashreport_2 (1).log](https://github.com/Regalis11/Barotrauma/files/5513870/crashreport_2.1.log)
[crashreport_3 (1).log](https://github.com/Regalis11/Barotrauma/files/5513871/crashreport_3.1.log)
[crashreport_3.log](https://github.com/Regalis11/Barotrauma/files/5513872/crashreport_3.log)
[crashreport_2.log](https://github.com/Regalis11/Barotrauma/files/5513873/crashreport_2.log)
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/5513874/crashreport.log)
[crashreport_4.log](https://github.com/Regalis11/Barotrauma/files/5513875/crashreport_4.log)

[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/5513863/crashreport.2.log)

**Comment by Regalis11** [comment] 2020-11-10 09:01
Duplicate of Regalis11/Barotrauma#4160

**Closed by Regalis11** 2020-11-10 09:01 UTC
