### ISSUE TITLE
Depending on resolution, some dialog options in events cant be clicked on.

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#6517] opened 2021-08-29 19:34 UTC
**Description**
Players cant select certain event conversation options (they dont highlight) on some resolutions. For 1080p I have to add an empty option below the lowest option available when modding the event, so that its clickable, but this doesn't work for 4K.
![image](https://user-images.githubusercontent.com/59519434/131263114-a86d371c-8920-4f1d-88a9-4a9e0ceaacf9.png)

**Steps To Reproduce**
-get [ITA](https://steamcommunity.com/sharedfiles/filedetails/?id=2005463692)
-play the game in 4k
-start campaign, it starts in city, go to one of the shops, interact with them and try to leave
-bottom option shouldn't be clickable, as the report on pic above says

**Version**
Stable

**Comment by Regalis11** [comment] 2023-09-02 08:23
Closing as a duplicate of https://github.com/Regalis11/Barotrauma/issues/12601. Even though this ticket is much older, the newer one has a bit more information.

**Closed by Regalis11** 2023-09-02 08:23 UTC
Labels: Bug, Code, Modding
