### ISSUE TITLE
ALL items dropped on the floor from ALL characters when loading outpost

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#4538] opened 2020-12-15 21:21 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When starting a round in an outpost, items drop from ALL characters, players and NPCs and remain on the floor

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
 v0.11.0.9 Win10

**Additional information**
![unknown](https://user-images.githubusercontent.com/73229309/102274200-c4050280-3f23-11eb-8acc-239873d8b9ce.png)
Clip: https://cdn.discordapp.com/attachments/587647684794515468/788515640314167326/Desktop_2020.12.15_-_18.02.11.03.DVR.mp4

**Comment by 3e849f2e5c** [comment] 2020-12-15 21:31
Duplicate of #4460

**Closed by 3e849f2e5c** 2020-12-15 21:31 UTC
