### ISSUE TITLE
[0.9.704] Unable to order Bots or send Reports in Multiplayer Campaign

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2205] opened 2020-02-07 21:31 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots were crossed out from recieving orders after playing one round in multiplayer campaign.
![](https://user-images.githubusercontent.com/5086682/74067429-44370f00-49c7-11ea-9d6c-9257ef528117.PNG)

Security guard was a player. When more players joined, they were crossed out as well. I wasn't able to send any breach/fire/hostile alert either. When I started a new save, I was able to report and send orders to bots again.

**Version**
0.9.704

This is the affected save:
[Barotrauma.zip](https://github.com/Regalis11/Barotrauma/files/4173088/Barotrauma.zip)

**Comment by Regalis11** [comment] 2020-02-08 20:15
The face is crossed out when the character is unable to hear you (outside radio/speaking range). I think in this case the issue is caused by mismatching team IDs - headsets that have a different team ID are unable to communicate with each other. 

I did a fix to headsets getting an incorrect team ID when the character is spawned using console commands (https://github.com/Regalis11/Barotrauma-development/commit/01898d9cdb5272287fba88b65365de9972664695). Not sure if that's what was happening here, need to test this more thoroughly.

**Comment by Regalis11** [comment] 2020-02-08 20:53
Found another issue: the headset's team ID was not saved, causing all of the headsets to reset to TeamID.None after the first round, which would prevent the players from communicating with new players/bots who weren't present on previous rounds.

**Comment by Kaillera** [comment] 2020-02-09 09:44
Thanks for telling us the problem. Last night we ended up trading headsets that existed on the sub with the ones on the bots by stunning them. Was funny watching Nilanth doing that every round, and them wanting to murder him for it.

**Comment by Rokvach** [comment] 2020-02-09 13:05
Tested, working correctly on campaign. Closing.

**Closed by Rokvach** 2020-02-09 13:05 UTC
Labels: Bug, Code
