### ISSUE TITLE
Husk gene doesn't work for player that left the game

### ISSUE THREAD

**Issue by uncommonnick** [Regalis11/Barotrauma#7075] opened 2021-10-29 15:31 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If a player has husk gene and decides to leave the game, his "husk protection" wears off, and he's body become husk. (What's more, that body doesn't leave body bag)

**Steps To Reproduce**
Use husk gene (our friend had 80% one), and leave the game.

**Version**
Win 10, Stable 
**Additional information**
We lost his whole inventory this way :/

**Comment by Regalis11** [comment] 2021-11-09 16:03
Looks like this didn't only apply to players who've left: any character with husk genes + husk infection would turn to a husk when they die. Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/d234453704fd2e1fb482985daa295e727c064389

**Comment by Lithosagym** [comment] 2021-11-26 06:35
Tested, characters with husk genes no longer turn into a husk when infected and are killed, confirmed fixed.

**Comment by Rokvach** [comment] 2021-11-26 07:45
Closing.

**Closed by Rokvach** 2021-11-26 07:45 UTC
Labels: Bug, Code
