### ISSUE TITLE
Getting d_93 Error on Campaign Mode

### ISSUE THREAD

**Issue by TNTman7878** [Regalis11/Barotrauma#5791] opened 2021-05-14 13:36 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

i was playing barotrauma today i docked to next stations then suddenly get this error
i tried to start again but still errors are happening

**Version**
v0.13.3.11 Windows
![20210514223223_1](https://user-images.githubusercontent.com/51579173/118278136-99d06480-b504-11eb-9a2d-b689f2848e84.jpg)

**SaveData**
[100tan__.zip](https://github.com/Regalis11/Barotrauma/files/6479104/100tan__.zip)

**Comment by Regalis11** [comment] 2021-05-14 13:46
Duplicate of https://github.com/Regalis11/Barotrauma/issues/4183

**Closed by Regalis11** 2021-05-14 13:46 UTC
