### ISSUE TITLE
Player keeps disconnecting due to not receiving an "old network event"

### ISSUE THREAD

**Issue by Schnorks23** [Regalis11/Barotrauma#7152] opened 2021-11-02 22:55 UTC
**Description**
Since the AtA update, one specific player out of our group of four keeps disconnecting every 5-10 minutes. The Serverlog mentions him not receiving an "old network event". (I will update this with the specific serverlog error message once we play again). His character ragdolls to the ground but stays alive until he reconnects.
Since we played a campaign form start to finish right before the AtA update and nothing on the server's side nor the player's side has changed, this seems to be related to the update.

**Steps To Reproduce**
Nothing specific. Set up a campaign server and play for a few minutes.

**Version**
v0.15.13.0 (Windows 10)

**Additional information**
This issue might be P2P-related since that specific player and me are having similar problems with other games using p2p (namely Tabletop Simulator), but since this did not happen before the AtA update there might be a way to fix it.

**Comment by JoneKone** [comment] 2021-11-03 08:38
I'm sorry to say this but he needs to get a proper internet. I had a friend who had 5G 600Mb/s connection .. had to switch to proper internet connection in the end.

**Comment by Fluffz** [comment] 2021-11-03 10:00
I am the friend with the disconnect issues. The internet is definitely not the problem, it is a symmetrical 1Gbit line and had my ping and package loss to google.com and facebook.com monitored during the whole playthrough with 0 package loss for ~2h of play with about ~5-6 disconnects in Barotrauma. The whole time of playing we also were on a discord call without any issues. Right before the disconnects there was always a large amount of rubber banding and I could tell that I will be out soon. 
The error message mentions something about SteamP2P and does not let me reconnect immediately, I had to restart Steam in order to get into the game again. If the last part would be otherwise and the game would just let me reconnect it would be less of an issue. 
We played the whole campaign before the AtA update without a single issue.

**Comment by Regalis11** [comment] 2021-11-03 12:10
Duplicate of https://github.com/Regalis11/Barotrauma/issues/6266

Something that might help us diagnose this is if you could enable some additional debug information and send us a screenshot: if you press F3 to open the debug console and enter the command "verboselogging", you should see what kind of network events the client is receiving from the server. I suspect something might be causing the server to send a very large number of events, which causes the client to fall behind and eventually get disconnected.

Thanks and sorry for the inconvenience!

**Closed by Regalis11** 2021-11-03 12:10 UTC
