### ISSUE TITLE
windows 7, game crash

### ISSUE THREAD

**Issue by Marutotheone** [Regalis11/Barotrauma#7936] opened 2021-12-25 06:17 UTC
Barotrauma Client crash report (generated on 25/12/2021 08:12:17)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

25F2DA9FCBD0323CBDF4FC2DA2092C7B

Game version 0.15.22.1 (ReleaseWindows, branch release, revision 898f64d2c0)
Graphics mode: 1366x768 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: Echion LineaXinzou
Loaded submarine: Humpback (47383194C26A37EE048767C99DEBFCC5)
Selected screen: Barotrauma.RoundSummaryScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 6.1.7601 Service Pack 1 64 bit
    GPU name: Intel(R) HD Graphics 3000
    Display mode: {Width:1366 Height:768 Format:Color AspectRatio:1.7786459}
    GPU status: Normal

Exception: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown (SharpDX.SharpDXException)
Device removed reason: HRESULT = 0x887A0006
Target site: Void CheckError()
Stack trace: 
   at SharpDX.Result.CheckError()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 1017
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 511
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59

Last debug messages:
[25/12/2021 08:11:32] Transitioning to Echion LineaXinzou (current location: Xinzou Station, selected location: Echion Linea, leaving sub: Humpback, at start: True, at end: False, transition type: LeaveLocation)
[25/12/2021 08:09:43] Unlocked mission "Killing a Moloch" in the location "Xinzou Station".
[25/12/2021 08:09:20] Unlocked mission "Killing a Hammerhead" in the location "Xinzou Station".
[25/12/2021 08:06:42] Generating an outpost for the start of the level... (Location: Xinzou Station, level type: Outpost)
[25/12/2021 08:04:40] (Msg) SDR RelayNetworkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[25/12/2021 08:04:40] (Msg) Ping location: sto2=20+2,sto=33+3/20+2,fra=33+3,ams=42+4/40+2,waw=42+4/41+2,par=58+5/42+3,lhr=42+4/44+2,vie=50+5/45+3,mad=77+7/62+3,iad=118+11/118+3,sgp=269+26/238+16,gru=245+24
[25/12/2021 08:04:40] (Msg) Ping measurement completed
[25/12/2021 08:04:37] (Verbose) Communications with routing cluster 'seo' established.
[25/12/2021 08:04:37] (Verbose) Communications with routing cluster 'tyo' established.
[25/12/2021 08:04:37] (Verbose) Communications with routing cluster 'tyo1' established.
[25/12/2021 08:04:37] (Verbose) Communications with routing cluster 'syd' established.
[25/12/2021 08:04:37] (Verbose) Communications with routing cluster 'sgp' established.
[25/12/2021 08:04:37] (Verbose) Communications with routing cluster 'maa' established.
[25/12/2021 08:04:37] (Verbose) Communications with routing cluster 'scl' established.
[25/12/2021 08:04:37] (Verbose) Communications with routing cluster 'lim' established.
[25/12/2021 08:04:37] (Verbose) Communications with routing cluster 'jnb' established.
[25/12/2021 08:04:37] (Verbose) Communications with routing cluster 'eze' established.
[25/12/2021 08:04:37] (Verbose) Communications with routing cluster 'hkg' established.
[25/12/2021 08:04:37] (Verbose) Communications with routing cluster 'sea' established.
[25/12/2021 08:04:37] (Verbose) Communications with routing cluster 'lax' established.
[25/12/2021 08:04:37] (Verbose) Communications with routing cluster 'bom' established.
[25/12/2021 08:04:37] (Verbose) Communications with routing cluster 'vie' established.
[25/12/2021 08:04:37] (Verbose) Communications with routing cluster 'gru' established.
[25/12/2021 08:04:37] (Verbose) Communications with routing cluster 'waw' established.
[25/12/2021 08:04:37] (Verbose) Communications with routing cluster 'sto' established.
[25/12/2021 08:04:37] (Verbose) Communications with routing cluster 'sto2' established.
[25/12/2021 08:04:37] (Verbose) Communications with routing cluster 'ord' established.
[25/12/2021 08:04:37] (Verbose) Communications with routing cluster 'mad' established.
[25/12/2021 08:04:37] (Verbose) Communications with routing cluster 'dxb' established.
[25/12/2021 08:04:37] (Verbose) Communications with routing cluster 'par' established.
[25/12/2021 08:04:37] (Verbose) Communications with routing cluster 'dfw' established.
[25/12/2021 08:04:37] (Verbose) Communications with routing cluster 'lhr' established.
[25/12/2021 08:04:37] (Verbose) Communications with routing cluster 'atl' established.
[25/12/2021 08:04:37] (Verbose) Communications with routing cluster 'iad' established.
[25/12/2021 08:04:37] (Verbose) Communications with routing cluster 'ams' established.
[25/12/2021 08:04:37] (Verbose) Communications with routing cluster 'fra' established.
[25/12/2021 08:04:37] (Msg) SDR RelayNetworkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[25/12/2021 08:04:37] (Msg) Performing ping measurement
[25/12/2021 08:04:37] (Msg) Got SDR network config.  Loaded revision 364 OK
[25/12/2021 08:04:37] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[25/12/2021 08:04:12] Attempting to open ALC device "OpenAL Soft on VoiceMeeter Input (VB-Audio VoiceMeeter VAIO)"
[25/12/2021 08:04:09] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[25/12/2021 08:04:08] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[25/12/2021 08:04:06] Logged in as Martiinnnni (SteamID STEAM_1:0:205375365)

- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**

**Comment by Ek-Videogames** [comment] 2021-12-25 21:28
Duplicate of issue #1833 ,
Current build of the game hates Nvidia GPUs for some reason.

**Closed** 2022-01-03 08:18 UTC
