### ISSUE TITLE
Multiplayer bug encountered (all players drop the game except host)

### ISSUE THREAD

**Issue by Vail90** [Regalis11/Barotrauma#3386] opened 2020-07-17 23:04 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
We we're doing a campaign mission and about 10 minutes in, we encoutered enemies at 100% hellish and the players in my servers all disconnected (we use a couple of mods, but we never encountered the issue before with all the mods installed
EK Armory/Utility (with Into the abyss patches), Into the Abyss, Gunlights, Realistic medicine, Hydroponic patched, Earth's forgotten arsenal

**Steps To Reproduce**
Install all the mods above, create a multiplayer campaign at 100% hellish difficulty and play for 5-20 mins.

**Version**
v0.9.10.0 Windows 10 Pro (we are all using win10pro)

**Additional information**
Usually happens after incountering a wave of ocean monsters
![BaroMPbug](https://user-images.githubusercontent.com/68448951/87837085-5f545780-c860-11ea-895c-b636d4f8d23e.png)

**Comment by Regalis11** [comment] 2020-07-27 09:31
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3019

**Closed by Regalis11** 2020-07-27 09:31 UTC
