### ISSUE TITLE
Sprite bleed in neon lights

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#9605] opened 2022-07-19 08:44 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

1. Neon Light Frame - Not a light source.
![Image 001_11-37](https://user-images.githubusercontent.com/93348499/179707767-64b1de69-8b12-4c96-85e4-da091d00c294.png)

2. Neon Light Planet - The texture along the edges has a parasitic color
![Image 001_11-34](https://user-images.githubusercontent.com/93348499/179707796-fb97af6a-dc19-4272-8291-4505ab8daf9c.png)

### Reproduction steps

1. Start Editor
2. Create `Neon Light Frame` and `Neon Light Planet`
3. Look.

### Bug prevalence

Happens every time I play

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-07-19 08:53
> Neon Light Frame - Not a light source.

Why's this a problem?

**Comment by MaaiG** [comment] 2022-07-19 09:43
@Regalis11 I thought it was supposed to glow! It's not?

**Comment by Regalis11** [comment] 2022-07-19 10:00
Ahh, it was intended to be a frame for attaching neon lights on. :)

**Comment by MaaiG** [comment] 2022-07-19 10:09
Oh, I see. ))

**Comment by Regalis11** [comment] 2022-08-15 10:27
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/95e18f1

**Comment by Rokvach** [comment] 2022-08-16 09:36
Tested, no issues. Closing.

**Closed by Rokvach** 2022-08-16 09:36 UTC
Labels: Bug, Art
