### ISSUE TITLE
The PUCS suit does not emit a sound warning when out of oxygen

### ISSUE THREAD

**Issue by Stefan-Zdravkovic-019** [Regalis11/Barotrauma#10682] opened 2022-12-07 16:05 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I have already found one of these issues submitted but closed, so I write it now myself to open up the discussion.

The PUCS when out of oxygen will not warn the player of it happening, this happened to me and friends through out our missions as we were underwater running out of O2 but not getting warned by the suit.
This happened on a friends server at first, and now I have tested it in single player by jumping into ballast full of water with the PUCS and no oxygen, and it still gave no audio warning, everything else shows as it should, but the audio warning does not exist.

### Reproduction steps

To reproduce this problem I just went into sub editor, spawned myself in a sub, spawned a PUCS and jumped into water with no oxygen supply and watched as my character slowly lost a bit of health without getting warned audibly.

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
There were no error messages in the console, I have enabled verboselogging in hopes of it giving some info but to no avail.
```

**Comment by Regalis11** [comment] 2022-12-07 17:29
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10109. The fix is not included in the public version yet

**Closed by Regalis11** 2022-12-07 17:29 UTC
