### ISSUE TITLE
Opening the console while (an event) conversation is active closes the conversation and the event

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#9154] opened 2022-05-17 08:59 UTC
![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/d2e06012-9e9c-4136-888f-e75b34398dde)

Steps to repro:
- triggerevent (e.g. "manandhisraptor1"
- find the conversation and trigger it
- press F3 to open the console

Version: 0.18.1.0 (Tested on feature/level-progression@026d2c5).

**Comment by ekqvist** [comment] 2022-05-17 10:56
There are also other issues (#5010) of events getting "canceled" when you switch characters or fall unconscious in the middle of a conversation. Not sure if they are related or separate issues.

**Comment by Regalis11** [comment] 2022-05-17 13:58
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1d181a831e4b08979eb363cd1c18a48442a7d054. This seems to have been caused by the changes done to address https://github.com/Regalis11/Barotrauma-development/issues/2036: the ConversationAction got interrupted when an input-blocking menu was opened. I think the original intention was to prevent the conversation from triggering when one is open, but not to interrupt it if it's already triggered.

**Comment by Rokvach** [comment] 2022-05-19 11:42
Tested, you can't change character when a dialog is up, you can complete the event while unconscious, opening f3 or pressing esc while dialog is open doesn't close it. Only way I was able to break the dialog was when I used commands to control another character in multiplayer, the dialog menu stayed open and I wasn't able to close it, but as this requires you to use commands I think its fine as is. 

Seems to be working correctly, closing.

**Closed by Rokvach** 2022-05-19 11:42 UTC
Labels: Bug, Code
