### ISSUE TITLE
Crash report - Happened during mp host loaded a mission while I was loading in to a city

### ISSUE THREAD

**Issue by Tha-lame-ass** [Regalis11/Barotrauma#3821] opened 2020-09-14 08:01 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Crash happened when I was loading in to a city and the host for the multiplayer already started leaving the city to go on a mission

**Steps To Reproduce**
Load up a mp session with one of the players having a slow computer/internet and have the host leave the town before all layers are loaded in.

**Version**
0.10.4.0 Windows 10

**Additional information**
Crash report below
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/5216950/crashreport.log)

**Comment by Regalis11** [comment] 2020-09-14 08:37
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3440. Will be fixed in the next patch, sorry for the inconvenience!

**Closed by Regalis11** 2020-09-14 08:37 UTC
Labels: Bug, Code, Crash
