### ISSUE TITLE
Transport missions going nowhere (lineas)

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#11132] opened 2023-02-02 17:52 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Cargo missions will sometimes ask you to deliver supplies into.... nowhere (it does state "construction materials" but there's no delivery point)

![image](https://user-images.githubusercontent.com/73229309/216400819-86496f12-89e2-417d-9a45-8cd082c7882e.png)

The same can happen to NPC transport I believe.

VIP transport to abandoned outpost:
![image](https://user-images.githubusercontent.com/73229309/216407714-e24a869a-a116-48d8-861a-e199d7e84970.png)

Arms delivery to abandoned outpost
![image](https://user-images.githubusercontent.com/73229309/216409255-381de9fe-a168-4f8e-abb2-b110003765c7.png)

Clown delivery to monster-infested outpost
![image](https://user-images.githubusercontent.com/73229309/216413693-aa40cd31-256c-4c21-964b-15dfcba99046.png)

Could make sense as seen in Dak's [More Level Content](https://steamcommunity.com/sharedfiles/filedetails/?id=2814493175) mod in the future
https://cdn.discordapp.com/attachments/900479225755222107/1034387237795790908/beacon_construction.mp4

### Bug prevalence

Just once

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-02-02 19:23
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7497

**Closed by Regalis11** 2023-02-02 19:23 UTC
