### ISSUE TITLE
occasional crashs in submarine editor

### ISSUE THREAD

**Issue by UsernameIsToLon** [Regalis11/Barotrauma#7884] opened 2021-12-20 20:41 UTC
- [ x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
While editing my old submarine the editor will crash from time to time.

**Crashreport**
Barotrauma Client crash report (generated on 20.12.2021 21:32:22)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

25F2DA9FCBD0323CBDF4FC2DA2092C7B

Game version 0.15.22.1 (ReleaseWindows, branch release, revision 898f64d2c0)
Graphics mode: 1920x1080 (Fullscreen)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: Darkwing (33170037AABFDDE31516E1760F42A7FA)
Selected screen: Barotrauma.SubEditorScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19042.0 64 bit
    GPU name: NVIDIA GeForce GTX 1060 6GB
    Display mode: {Width:3840 Height:2160 Format:Color AspectRatio:1,7777778}
    GPU status: Normal

Exception: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Die GPU-Geräteinstanz wurde angehalten. Verwenden Sie GetDeviceRemovedReason, um die erforderliche Aktion zu bestimmen.
 (SharpDX.SharpDXException)
Device removed reason: HRESULT = 0x887A0006
Target site: Void CheckError()
Stack trace: 
   at SharpDX.Result.CheckError()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 1017
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 511
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59

Last debug messages:
[20.12.2021 19:06:37] (Msg) SDR RelayNetworkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[20.12.2021 19:06:37] (Msg) Ping location: fra=18+1,ams=30+3/25+1,par=34+3/27+1,vie=30+3/30+1,sto2=31+3,sto=38+3/31+3,lhr=34+3/32+1,waw=33+3,mad=46+4,iad=106+10/103+1,sgp=188+18/189+18,gru=231+23
[20.12.2021 19:06:37] (Msg) Ping measurement completed
[20.12.2021 19:06:36] (Verbose) Communications with routing cluster 'iad' established.
[20.12.2021 19:06:35] (Verbose) Communications with routing cluster 'seo' established.
[20.12.2021 19:06:35] (Verbose) Communications with routing cluster 'syd' established.
[20.12.2021 19:06:35] (Verbose) Communications with routing cluster 'tyo' established.
[20.12.2021 19:06:35] (Verbose) Communications with routing cluster 'tyo1' established.
[20.12.2021 19:06:35] (Verbose) Communications with routing cluster 'sgp' established.
[20.12.2021 19:06:35] (Verbose) Communications with routing cluster 'maa' established.
[20.12.2021 19:06:35] (Verbose) Communications with routing cluster 'scl' established.
[20.12.2021 19:06:35] (Verbose) Communications with routing cluster 'jnb' established.
[20.12.2021 19:06:35] (Verbose) Communications with routing cluster 'lim' established.
[20.12.2021 19:06:35] (Verbose) Communications with routing cluster 'lax' established.
[20.12.2021 19:06:35] (Verbose) Communications with routing cluster 'sea' established.
[20.12.2021 19:06:35] (Verbose) Communications with routing cluster 'bom' established.
[20.12.2021 19:06:35] (Verbose) Communications with routing cluster 'eze' established.
[20.12.2021 19:06:35] (Verbose) Communications with routing cluster 'sto' established.
[20.12.2021 19:06:35] (Verbose) Communications with routing cluster 'waw' established.
[20.12.2021 19:06:35] (Verbose) Communications with routing cluster 'vie' established.
[20.12.2021 19:06:35] (Verbose) Communications with routing cluster 'sto2' established.
[20.12.2021 19:06:35] (Verbose) Communications with routing cluster 'gru' established.
[20.12.2021 19:06:35] (Verbose) Communications with routing cluster 'ord' established.
[20.12.2021 19:06:35] (Verbose) Communications with routing cluster 'hkg' established.
[20.12.2021 19:06:35] (Verbose) Communications with routing cluster 'dxb' established.
[20.12.2021 19:06:35] (Verbose) Communications with routing cluster 'dfw' established.
[20.12.2021 19:06:35] (Verbose) Communications with routing cluster 'mad' established.
[20.12.2021 19:06:35] (Verbose) Communications with routing cluster 'par' established.
[20.12.2021 19:06:35] (Verbose) Communications with routing cluster 'lhr' established.
[20.12.2021 19:06:35] (Verbose) Communications with routing cluster 'atl' established.
[20.12.2021 19:06:34] (Verbose) Communications with routing cluster 'fra' established.
[20.12.2021 19:06:34] (Verbose) Communications with routing cluster 'ams' established.
[20.12.2021 19:06:34] (Msg) SDR RelayNetworkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[20.12.2021 19:06:34] (Msg) Performing ping measurement
[20.12.2021 19:06:34] (Msg) Got SDR network config.  Loaded revision 363 OK
[20.12.2021 19:06:34] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[20.12.2021 19:06:19] Attempting to open ALC device "OpenAL Soft on Lautsprecher (Realtek High Definition Audio)"
[20.12.2021 19:06:18] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[20.12.2021 19:06:18] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[20.12.2021 19:06:16] Logged in as [xxxxxxxxxxxxxx]

**Version**
0.15.22.1 (ReleaseWindows, branch release, revision 898f64d2c0)

**Additional information**

**Comment by Regalis11** [comment] 2022-01-03 08:20
Duplicate of https://github.com/Regalis11/Barotrauma/issues/1833

**Closed by Regalis11** 2022-01-03 08:20 UTC
