### ISSUE TITLE
Bots use/waste medicines to treat minor injuries

### ISSUE THREAD

**Issue by GowardHoward** [Regalis11/Barotrauma#11477] opened 2023-03-10 11:38 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Bots use medicines from the box. And I can't stop them from doing so. Because of this, I constantly do not have medicines. They spend expensive medicines on the treatment of ordinary healthier 

### Bug prevalence

Just once

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-03-10 13:48
Thank you for the report!

Would it be possible to provide us some more information on the issue? I'm not entirely sure if this is an actual bug - the medic bots are supposed to use medicine when they need it to treat someone. 

What box do you mean? Have you tried ordering them to ignore the box, or putting them in somewhere the medic bot can't reach?

**Comment by Rehexr** [comment] 2023-03-10 13:59
Yeah i was about to say, might wanna try ordering to ignoring the container? Unless of course youre already doing that, which is where there would be an issue

**Comment by aeondez** [comment] 2023-03-11 17:51
Semi-related:

I was using the Winterhalter (which has a toxin cabinet that cannot be opened except by captain and medic) where we stash our morphine.

We had a ton of pomegrenade extract for bots to use (all the bots were assistants) and when one of them was given the order to do healing, she started chasing one of the human crew members around and injecting him with so much pomegrenade extract that he wound up with 50% health due to massive organ damage.

**Comment by aeondez** [comment] 2023-03-11 18:01
More on-topic:

Bots don't really have common sense, and are not very efficient with their medicine usage. Medicine is expensive and extremely important to ration carefully. Bots know what to use to heal a given condition, but it'd be nice if bots only tried to apply medicine if its effects are mostly or fully used. The current thresholds for bots deciding to give medicine feels too low.

For example, if a bot has a choice to use saline or blood pack for bloodloss, they won't try to use either until at least ~75% of the bloodloss effect of saline would be applied.

Just throwing out made-up numbers here to make the point:

If fentanyl heals 100 hp, don't let bots apply the fentanyl until the injured crewmember has less than 25 hp

If bandages heal 10 bleeding/burns, don't let the bots apply bandages until the injured crewmember has at least 8 bleeding/burns

**Comment by itchyOwl** [comment] 2023-05-04 12:05
Although I don't disagree about the main point: it would be good to make the bots use the medicines reasonable, I kind of disagree on the suggested approach: we shouldn't lower the thresholds of treating, because that would lead to bots not treating when you tell them to treat.

Can be a bit difficult to solve this without giving the player more control over it.

**Comment by Regalis11** [comment] 2023-05-04 15:35
Another thing to note is that there are two thresholds: one for health, and another for affliction strength. I.e. a character needs to be below certain health (75% by default, 90% if the bot has been explicitly ordered to treat others), and the afflictions themselves need to be above a certain thresholds for the bot to consider what to treat and how.

This is a pretty tricky problem to solve for several reasons:
- Meds can affect multiple afflictions, or cause other afflictions, which need to be taken into account when determining what's suitable
- We don't necessarily know in advance what the effect of a med will be: there can be randomness involved.
- If the patient has multiple limb-specific afflictions, it can be hard to judge what's worth treating (if there's tiny amount of damage on all limbs, each of which needs to be treated separately, it's bound to lead to some wasted meds)

> If fentanyl heals 100 hp, don't let bots apply the fentanyl until the injured crewmember has less than 25 hp
> If bandages heal 10 bleeding/burns, don't let the bots apply bandages until the injured crewmember has at least 8 bleeding/burns.

It's unfortunately not that simple, because that's not how the medical system works. Fentanyl doesn't heal any HP, it reduces certain afflictions which can result in an increase in HP (or not, if the character is for example about to overdose or suffering of oxygen deprivation).

**Comment by Regalis11** [comment] 2023-05-04 15:41
Now thinking about it, something that might help with the issue is improving how the bots judge the strength of an affliction on a specific limb. 

Now each limb is essentially handled separately: e.g. 5% internal damage on one limb is enough for a bot to consider it worth treating, which we can't easily increase, because it could mean the bot can have a nearly lethal amount of internal damage `in total`, spread across different limbs, before the bots start treating it. But if we took the damage on other limbs into account too, especially when the injury is treated with something that affects all limbs, we could safely bump that threshold much higher.

**Comment by Regalis11** [comment] 2023-05-05 06:47
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/154f8ef3b194633139d177baffb0aef03fb29001

```
Adjustments to make bots less eager to waste medicine for minor injuries:

- Increased afflictions' default treatment threshold from 5 to 10.
- Bots take afflictions in other limbs into account when determining whether an affliction is sever enough to treat. I.e. a 5% burn can be ignored, but 5% burns in all limbs can't.
- GetSuitableTreatments prefers less effective treatments for small injuries, meaning the bots will use e.g. opium or morphine for minor damage instead of always using the most powerful meds available.
```

**Comment by Rokvach** [comment] 2023-06-01 06:29
Tested, working correctly. Can be merged and closed.

**Closed** 2023-06-01 07:09 UTC
Labels: Code, Design
