### ISSUE TITLE
Game crashes when 

### ISSUE THREAD

**Issue by AtobaAzul** [Regalis11/Barotrauma#10951] opened 2023-01-17 13:24 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Game crashes regularly, after a few minutes in an outpost, I haven't been able to find what exactly is causing it.
Reproduced with and without mods loaded.

### Reproduction steps

1. Load save file:
[Unstable Catastrophe.zip](https://github.com/Regalis11/Barotrauma/files/10435363/Unstable.Catastrophe.zip)

2. Wait, time needed to wait may vary.

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Despite being a crash, I was unable to find a crash log, however, I have provided the save file in the reproduction steps.
```

**Comment by Regalis11** [comment] 2023-01-17 13:30
Most likely a duplicate of https://github.com/Regalis11/Barotrauma/issues/10902, as that's a frequent issue in the latest faction test build and crashes the game without a crash report.

**Closed by Regalis11** 2023-01-17 13:30 UTC
