### ISSUE TITLE
0.1002.0.0 (Unstable): Cannot Upgrade Sub After Swapping

### ISSUE THREAD

**Issue by Jlobblet** [Regalis11/Barotrauma#3041] opened 2020-06-09 17:22 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
After swapping from the starting submarine to another, you cannot purchase upgrades for it.

**Steps To Reproduce**
1. Start a new campaign.
2. Buy and switch to a new submarine.
3. Dock and undock.
4. Attempt to upgrade the submarine.

**Version**
Version 0.1002.0.0 (Unstable).
Windows 10 version 1903.

**Comment by Rokvach** [comment] 2020-06-09 17:28
This was noticed in multiplayer, should work in singleplayer

**Comment by 3e849f2e5c** [comment] 2020-06-10 08:56
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3b9ae945bed8fbb2d149f4f7dea23b314cc092f8, was caused because of recent networking changes to the submarine switching. Previously PendingSubmarineSwitch was not synced with the client and I use it to determine whether or not you can purchase upgrades and the networking changes made it so PendingSubmarineSwitch is synced but never cleared on the client's end preventing you from ever upgrading the submarine.

**Comment by Rokvach** [comment] 2020-06-15 05:30
Couldn't reproduce using steps above, seems to be working correctly. Closing.

**Closed by Rokvach** 2020-06-15 05:30 UTC
Labels: Bug, Code
