### ISSUE TITLE
Crash in AIObjectiveRepairItem.Act when a round starts in a heavily modded game

### ISSUE THREAD

**Issue by CUCU201** [Regalis11/Barotrauma#12109] opened 2023-06-02 05:43 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Entering a touring map game when the destination is a city will crash, and if the destination is a crossroads, it seems like no problem
![`95XW7%)0DXQR5XJ)B)}H2F](https://github.com/Regalis11/Barotrauma/assets/135304269/88ea5ff6-4951-4626-907a-befb53e75cca)

### Reproduction steps

Entering a touring map game when the destination is a city will crash, and if the destination is a crossroads, it seems like no problem
[crashreport (19).log](https://github.com/Regalis11/Barotrauma/files/11632211/crashreport.19.log)
[crashreport (19).log](https://github.com/Regalis11/Barotrauma/files/11632211/crashreport.19.log)

### Bug prevalence

Happens every now and then

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 06/02/2023 13:36:13)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

1F05303D4AB76BACE6EE576870D83561

Game version 1.0.13.2 (ReleaseWindows, branch master, revision 09c36a9213)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: Simplified Chinese
Selected content packages: Vanilla (E7A137B), Lua For Barotrauma (4F663F9), Cs For Barotrauma (965D27D), 先进装甲 (2F8EDB1), BetterHealthUI (5C86226), BetterFabricatorUI (9A068E8), Better Connection Panel UI (A17E57A), Performance Fix (3629CD4), Livelandr's Spawn Menu (B07A2FC), EuropaWar (C846D4E), 奇迹之海武装 (885CDFD), DynamicEuropa (1790E40), 外骨骼美化 (C07AE2B), [Beta 0.97]木卫二萌化计划 ver.BPSG (C20CA52), [BOS]Superman (F9FD1F5), [BOS]Wrecks (64DE267), Item Finder Count (50EAECC), Detectable Alien Materials 可探测的异星矿物！ (AB4F92D), Shinkai Musume (DF096FB), Sexier Walking (A0FEFCA), 天赋增强 - Talent Enhancement[CN-EN-RU-FRN] (199AAFF), anime sound【cloud】+Weapon sound (779AB20), 深渊基因 Abyss Gene (11288C1), Duffelbag Fix / 遺物袋補丁 (DEFB5C2), Better Exosuit with Platform 外骨骼优化和置物架 (82E5D66), Brighter Lights (14437B4), 万年风雪 (7280324), 升级的装备 (DC8BDF6), Storage Icons (CA9F78A), Item IO Framework (396BB3B), Material IO (57E6AC8), 次元箱-CiYuanToolbox (1F7E32F), 32x Stack (6262D38), 无限物品＆天赋增强兼容 (CA73DEB), 无限物品 (0B221E9), 无限轨道炮 (FEFCB83), 原版物品优化 (D2DE832), 黑暗装甲-DarkArmor (4D18ACF), 超级基因！ SuperGene！ (AC2C96C), 原版武器重做 (14EB3F4), Sort Container UI (6136523), 'Sirius'天狼星 (0A8DD53), Extended Upgrades (B1F2CEA), 高难狩猎 (D075F09), 剑核心就绪，靠近你的敌人！泰坦陨落2浪人剑 (20D1F4C), 大工具箱 big toolbox (AA2EF95), [SGM]初始6职业 (0976EBE), CA单人工具包/CASingleTools (5381DE2), CA型自注射智能耳机/CASelfInjectionSmartHeadset (9E7041B), Super Mining Sonar + oClockRadar [UPDATED] (70CCB30), 暗影巨擘-高瞻远瞩的节制 (0E458B4)
Level seed: Ino Linea261Alkonost242
Loaded submarine: 'Sirius'天狼星 (320ECE897AE829D756188851FE30CB94)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.22000.0 64 bit
    GPU name: NVIDIA GeForce RTX 3050 Laptop GPU
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: The given key 'Contained' was not present in the dictionary. (System.Collections.Generic.KeyNotFoundException)
Target site: Void ThrowKeyNotFoundException[T](T)
Stack trace: 
   at Barotrauma.AIObjectiveRepairItem.Act(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjectiveRepairItem.cs:line 149
   at Barotrauma.AIObjective.TryComplete(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjective.cs:line 179
   at Barotrauma.AIObjectiveManager.DoCurrentObjective(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjectiveManager.cs:line 337
   at Barotrauma.HumanAIController.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\HumanAIController.cs:line 473
   at Barotrauma.AICharacter.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AICharacter.cs:line 72
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 3056
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 185
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 891
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[06/02/2023 13:36:13] AEA: Cached
[06/02/2023 13:36:10] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
[06/02/2023 13:35:05] Error in StatusEffect (CA4型智能耳机) - Affliction prefab with the identifier or type "growthmod1" not found.
[06/02/2023 13:35:05] Error in StatusEffect (CA4型智能耳机) - Affliction prefab with the identifier or type "tapeworminfection" not found.
[06/02/2023 13:35:05] Error in StatusEffect (CA4型智能耳机) - Affliction prefab with the identifier or type "florainfection" not found.
[06/02/2023 13:35:05] Error in StatusEffect (CA4型智能耳机) - Affliction prefab with the identifier or type "cytokine" not found.
[06/02/2023 13:35:05] Error in StatusEffect (CA4型智能耳机) - Affliction prefab with the identifier "floraresistance" not found.
[06/02/2023 13:35:05] Error in StatusEffect (CA4型智能耳机) - Affliction prefab with the identifier or type "growthmod1" not found.
[06/02/2023 13:35:05] Error in StatusEffect (CA4型智能耳机) - Affliction prefab with the identifier or type "tapeworminfection" not found.
[06/02/2023 13:35:05] Error in StatusEffect (CA4型智能耳机) - Affliction prefab with the identifier or type "florainfection" not found.
[06/02/2023 13:35:05] Error in StatusEffect (CA4型智能耳机) - Affliction prefab with the identifier or type "cytokine" not found.
[06/02/2023 13:35:05] Error in StatusEffect (CA4型智能耳机) - Affliction prefab with the identifier "floraresistance" not found.
[06/02/2023 13:35:04] Error in StatusEffect (CA4型智能耳机) - Affliction prefab with the identifier or type "growthmod1" not found.
[06/02/2023 13:35:04] Error in StatusEffect (CA4型智能耳机) - Affliction prefab with the identifier or type "tapeworminfection" not found.
[06/02/2023 13:35:04] Error in StatusEffect (CA4型智能耳机) - Affliction prefab with the identifier or type "florainfection" not found.
[06/02/2023 13:35:04] Error in StatusEffect (CA4型智能耳机) - Affliction prefab with the identifier or type "cytokine" not found.
[06/02/2023 13:35:04] Error in StatusEffect (CA4型智能耳机) - Affliction prefab with the identifier "floraresistance" not found.
[06/02/2023 13:35:04] Error in StatusEffect (CA4型智能耳机) - Affliction prefab with the identifier or type "growthmod1" not found.
[06/02/2023 13:35:04] Error in StatusEffect (CA4型智能耳机) - Affliction prefab with the identifier or type "tapeworminfection" not found.
[06/02/2023 13:35:04] Error in StatusEffect (CA4型智能耳机) - Affliction prefab with the identifier or type "florainfection" not found.
[06/02/2023 13:35:04] Error in StatusEffect (CA4型智能耳机) - Affliction prefab with the identifier or type "cytokine" not found.
[06/02/2023 13:35:04] Error in StatusEffect (CA4型智能耳机) - Affliction prefab with the identifier "floraresistance" not found.
[06/02/2023 13:35:04] Error in StatusEffect (CA4型智能耳机) - Affliction prefab with the identifier or type "growthmod1" not found.
[06/02/2023 13:35:04] Error in StatusEffect (CA4型智能耳机) - Affliction prefab with the identifier or type "tapeworminfection" not found.
[06/02/2023 13:35:04] Error in StatusEffect (CA4型智能耳机) - Affliction prefab with the identifier or type "florainfection" not found.
[06/02/2023 13:35:04] Error in StatusEffect (CA4型智能耳机) - Affliction prefab with the identifier or type "cytokine" not found.
[06/02/2023 13:35:04] Error in StatusEffect (CA4型智能耳机) - Affliction prefab with the identifier "floraresistance" not found.
[06/02/2023 13:35:03] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/lxjzh/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2955833516/Content/items/Jobgear/CANanoToolGun.png, size: 718x343)
[06/02/2023 13:35:03] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/lxjzh/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2935181237/Content/items/Weapons/Katana.png, size: 372x234)
[06/02/2023 13:35:02] Error in StatusEffect (CA4型智能耳机) - Affliction prefab with the identifier or type "growthmod1" not found.
[06/02/2023 13:35:02] Error in StatusEffect (CA4型智能耳机) - Affliction prefab with the identifier or type "tapeworminfection" not found.
[06/02/2023 13:35:02] Error in StatusEffect (CA4型智能耳机) - Affliction prefab with the identifier or type "florainfection" not found.
[06/02/2023 13:35:02] Error in StatusEffect (CA4型智能耳机) - Affliction prefab with the identifier or type "cytokine" not found.
[06/02/2023 13:35:02] Error in StatusEffect (CA4型智能耳机) - Affliction prefab with the identifier "floraresistance" not found.
[06/02/2023 13:34:57] Sprite "Content/ContentPackages/Items/sonarBlip.png" not found!
[06/02/2023 13:34:57] Sprite "Content/ContentPackages/Items/sonarOverlay.png" not found!
[06/02/2023 13:34:57] Failed to load sound file "Content/ContentPackages/Items/Command/Sonar Ping - Navigation.ogg" (file not found). {Sound file "E:/SteamLibrary/steamapps/common/Barotrauma/Content/ContentPackages/Items/Command/Sonar Ping - Navigation.ogg" doesn't exist!}
   at Barotrauma.Sounds.SoundManager.LoadSound(String filename, Boolean stream) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sounds\SoundManager.cs:line 361
   at Barotrauma.RoundSound.Load(ContentXElement element, Boolean stream) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\RoundSound.cs:line 105
[06/02/2023 13:34:57] Failed to load sound file "Content/ContentPackages/Items/Command/Sonar Ping - Navigation.ogg" (file not found). {Sound file "E:/SteamLibrary/steamapps/common/Barotrauma/Content/ContentPackages/Items/Command/Sonar Ping - Navigation.ogg" doesn't exist!}
   at Barotrauma.Sounds.SoundManager.LoadSound(String filename, Boolean stream) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sounds\SoundManager.cs:line 361
   at Barotrauma.RoundSound.Load(ContentXElement element, Boolean stream) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\RoundSound.cs:line 105
[06/02/2023 13:34:57] Failed to load sound file "Content/ContentPackages/Items/Command/Sonar Ping - Navigation.ogg" (file not found). {Sound file "E:/SteamLibrary/steamapps/common/Barotrauma/Content/ContentPackages/Items/Command/Sonar Ping - Navigation.ogg" doesn't exist!}
   at Barotrauma.Sounds.SoundManager.LoadSound(String filename, Boolean stream) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sounds\SoundManager.cs:line 361
   at Barotrauma.RoundSound.Load(ContentXElement element, Boolean stream) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\RoundSound.cs:line 105
[06/02/2023 13:34:57] Failed to load sound file "Content/ContentPackages/Items/Command/Sonar Ping - Navigation.ogg" (file not found). {Sound file "E:/SteamLibrary/steamapps/common/Barotrauma/Content/ContentPackages/Items/Command/Sonar Ping - Navigation.ogg" doesn't exist!}
   at Barotrauma.Sounds.SoundManager.LoadSound(String filename, Boolean stream) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sounds\SoundManager.cs:line 361
   at Barotrauma.RoundSound.Load(ContentXElement element, Boolean stream) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\RoundSound.cs:line 105
[06/02/2023 13:34:55] Could not find a suitable module for the location type LocationType (Waypoint). Module flag: Airlock.
[06/02/2023 13:34:55] Generating an outpost for the end of the level... (Location: Alkonost路径点, level type: LocationConnection)
[06/02/2023 13:34:54] Level identifier: coldcavernsadvanced
[06/02/2023 13:34:53] Error in StatusEffect config - item prefab with the identifier "" not found.
[06/02/2023 13:34:53] Invalid item spawn in StatusEffect "亚哈之矛" - identifier not found in the element "<SpawnItem identifier="" spawnposition="sameinventory" count="1" />"
[06/02/2023 13:34:53] Error in StatusEffect config - item prefab with the identifier "" not found.
[06/02/2023 13:34:53] Invalid item spawn in StatusEffect "亚哈之矛" - identifier not found in the element "<SpawnItem identifier="" spawnposition="sameinventory" count="1" />"
[06/02/2023 13:34:53] Error in StatusEffect config - item prefab with the identifier "" not found.
[06/02/2023 13:34:53] Invalid item spawn in StatusEffect "亚哈之矛" - identifier not found in the element "<SpawnItem identifier="" spawnposition="sameinventory" count="1" />"
[06/02/2023 13:34:53] Error in StatusEffect config - item prefab with the identifier "" not found.
[06/02/2023 13:34:53] Invalid item spawn in StatusEffect "亚哈之矛" - identifier not found in the element "<SpawnItem identifier="" spawnposition="sameinventory" count="1" />"
[06/02/2023 13:34:53] Error in StatusEffect config - item prefab with the identifier "" not found.
[06/02/2023 13:34:53] Invalid item spawn in StatusEffect "亚哈之矛" - identifier not found in the element "<SpawnItem identifier="" spawnposition="sameinventory" count="1" />"
[06/02/2023 13:34:53] Error in StatusEffect config - item prefab with the identifier "" not found.
[06/02/2023 13:34:53] Invalid item spawn in StatusEffect "亚哈之矛" - identifier not found in the element "<SpawnItem identifier="" spawnposition="sameinventory" count="1" />"
[06/02/2023 13:34:53] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/lxjzh/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2827262734/picture/枪械.png, size: 2103x2772)
[06/02/2023 13:34:53] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/lxjzh/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2827262734/picture/矿物.png, size: 500x450)
[06/02/2023 13:34:52] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/lxjzh/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2935181237/Content/items/Jobgear/Security/bandolier.png, size: 154x256)
[06/02/2023 13:34:52] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/lxjzh/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2935181237/Content/items/Jobgear/Security/转轮式霰弹枪.png, size: 215x64)
[06/02/2023 13:34:49] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/lxjzh/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2962136866/蓝图.png, size: 1890x800)
[06/02/2023 13:34:49] [ItemFinderCount] MiniMap.CreateItemFrame patched
[06/02/2023 13:34:41] Error in stattype="rangedattackmultiplier"! "stattype="rangedattackmultiplier"" is not a valid StatTypes value
[06/02/2023 13:34:41] WARNING: Affliction "tsm_melee_defense_buff" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[06/02/2023 13:34:38]  - SortContainerUI.lua (Took 0.00408ms)
[06/02/2023 13:34:38] Sort Container UI 1.0.10
[06/02/2023 13:34:38]  - init.lua (Took 0.07331ms)
[06/02/2023 13:34:38] Storage Icons 0.10
[06/02/2023 13:34:38]  - init.lua (Took 0.01835ms)
[06/02/2023 13:34:38] Performance Fix 1.0.13
[06/02/2023 13:34:38]  - BetterConnectionPanelUI.lua (Took 0.04590ms)
[06/02/2023 13:34:38] Better Connection Panel UI 1.0.5
[06/02/2023 13:34:38]  - init.lua (Took 0.01120ms)
[06/02/2023 13:34:38] BetterFabricatorUI 1.0.9
[06/02/2023 13:34:38]  - SpawnMenu.lua (Took 4.98740ms)
[06/02/2023 13:34:33] Livelandr's Spawn Menu 2.4
[06/02/2023 13:34:33]  - init.lua (Took 0.00037ms)
[06/02/2023 13:34:33] Performance Fix 1.0.13
[06/02/2023 13:34:33]  - armor.lua (Took 0.00697ms)
[06/02/2023 13:34:33] 先进装甲 0.2.9.b
[06/02/2023 13:34:32] Using LuaSetup.lua from the content package.
[06/02/2023 13:34:32] [CL CS ERROR] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> HarmonyLib.HarmonyException: Patching exception in method System.Void Barotrauma.Items.Components.MiniMap::CreateItemFrame(Barotrauma.ItemPrefab prefab, Barotrauma.RectTransform parent)
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at System.Runtime.CompilerServices.RuntimeHelpers.CompileMethod(RuntimeMethodHandleInternal method)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeNETPlatform.GetMethodHandle(MethodBase method)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform.GetIdentifiable(MethodBase method)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeNETPlatform.GetIdentifiable(MethodBase method)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform.Pin(MethodBase method)
   at MonoMod.RuntimeDetour.DetourHelper.Pin[T](T method)
   at HarmonyLib.MethodPatcher.CreateReplacement(Dictionary`2& finalInstructions)
   at HarmonyLib.PatchFunctions.UpdateWrapper(MethodBase original, PatchInfo patchInfo)
   at HarmonyLib.PatchClassProcessor.ProcessPatchJob(Job job)
   --- End of inner exception stack trace ---
   at HarmonyLib.PatchClassProcessor.ReportException(Exception exception, MethodBase original)
   at HarmonyLib.PatchClassProcessor.Patch()
   at HarmonyLib.Harmony.<PatchAll>b__10_0(Type type)
   at HarmonyLib.CollectionExtensions.Do[T](IEnumerable`1 sequence, Action`1 action)
   at HarmonyLib.Harmony.PatchAll(Assembly assembly)
   at BaroMod_sjx.ItemBoxImpl..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at Barotrauma.LuaCsSetup.<>c.<Initialize>b__84_6(Type t) in B:\programming\c#\Barotrauma\Barotrauma\BarotraumaShared\SharedSource\LuaCs\LuaCsSetup.cs:line 446
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.LuaCsSetup.Initialize(Boolean forceEnableCs) in B:\programming\c#\Barotrauma\Barotrauma\BarotraumaShared\SharedSource\LuaCs\LuaCsSetup.cs:line 443
[06/02/2023 13:34:32] [ItemFinderCount] MiniMap.CreateItemFrame patched
[06/02/2023 13:34:32] [ItemFinderCount] MiniMap.CreateItemFrame patched
[06/02/2023 13:34:32] [ItemFinderCount] MiniMap.CreateItemFrame patched
[06/02/2023 13:34:30] Added Item Finder Count 1.0.3 to Cs compilation. (Assumed)
[06/02/2023 13:34:30] Added Item IO Framework 0.0.13 to Cs compilation. (Standard)
[06/02/2023 13:34:30] Added BetterHealthUI 1.0.10 to Cs compilation. (Forced)
[06/02/2023 13:34:30] Cs! Version 09c36a9213
[06/02/2023 13:34:30] Lua! Version 09c36a9213
[06/02/2023 13:30:42] WARNING: Potential error in item variant "slipsuit": the item inherits the fabrication requirement of x1 "rubber"  from the base item "combatdivingsuit". If this is not intentional, you can use empty <RequiredItem /> elements in the item variant to remove any excess inherited fabrication requirements.
[06/02/2023 13:30:42] WARNING: Potential error in item variant "slipsuit": the item inherits the fabrication requirement of x1 "titaniumaluminiumalloy"  from the base item "combatdivingsuit". If this is not intentional, you can use empty <RequiredItem /> elements in the item variant to remove any excess inherited fabrication requirements.
[06/02/2023 13:30:38] WARNING: Unrecognized element in affliction "生命线" (StatusEffect)
[06/02/2023 13:30:34] WARNING: Potential error in item variant "slipsuit": the item inherits the fabrication requirement of x1 "rubber"  from the base item "combatdivingsuit". If this is not intentional, you can use empty <RequiredItem /> elements in the item variant to remove any excess inherited fabrication requirements.
[06/02/2023 13:30:34] WARNING: Potential error in item variant "slipsuit": the item inherits the fabrication requirement of x1 "titaniumaluminiumalloy"  from the base item "combatdivingsuit". If this is not intentional, you can use empty <RequiredItem /> elements in the item variant to remove any excess inherited fabrication requirements.
[06/02/2023 13:30:34] WARNING: Potential error in item variant "slipsuit": the item inherits the fabrication requirement of x1 "rubber"  from the base item "combatdivingsuit". If this is not intentional, you can use empty <RequiredItem /> elements in the item variant to remove any excess inherited fabrication requirements.
[06/02/2023 13:30:34] WARNING: Potential error in item variant "slipsuit": the item inherits the fabrication requirement of x1 "titaniumaluminiumalloy"  from the base item "combatdivingsuit". If this is not intentional, you can use empty <RequiredItem /> elements in the item variant to remove any excess inherited fabrication requirements.
[06/02/2023 13:30:32] Overriding an affliction or a buff with the identifier 'lonewolf' using the file 'C:/Users/lxjzh/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2803561945/Talents/TalentAfflictions.xml'
[06/02/2023 13:30:32] Overriding an affliction or a buff with the identifier 'guarded' using the file 'C:/Users/lxjzh/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2803561945/Talents/TalentAfflictions.xml'
[06/02/2023 13:30:31] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/lxjzh/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2935181237/Content/Particles/Particle_teleport1.png, size: 1645x510)
[06/02/2023 13:30:31] Overriding an affliction or a buff with the identifier 'nausea' using the file 'C:/Users/lxjzh/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2935181237/Content/Afflictions.xml'
[06/02/2023 13:30:31] Overriding an affliction or a buff with the identifier 'concussion' using the file 'C:/Users/lxjzh/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2935181237/Content/Afflictions.xml'
[06/02/2023 13:30:30] WARNING: Potential error in item variant "slipsuit": the item inherits the fabrication requirement of x1 "rubber"  from the base item "combatdivingsuit". If this is not intentional, you can use empty <RequiredItem /> elements in the item variant to remove any excess inherited fabrication requirements.
[06/02/2023 13:30:30] WARNING: Potential error in item variant "slipsuit": the item inherits the fabrication requirement of x1 "titaniumaluminiumalloy"  from the base item "combatdivingsuit". If this is not intentional, you can use empty <RequiredItem /> elements in the item variant to remove any excess inherited fabrication requirements.
[06/02/2023 13:30:30] WARNING: Potential error in item variant "slipsuit": the item inherits the fabrication requirement of x1 "rubber"  from the base item "combatdivingsuit". If this is not intentional, you can use empty <RequiredItem /> elements in the item variant to remove any excess inherited fabrication requirements.
[06/02/2023 13:30:30] WARNING: Potential error in item variant "slipsuit": the item inherits the fabrication requirement of x1 "titaniumaluminiumalloy"  from the base item "combatdivingsuit". If this is not intentional, you can use empty <RequiredItem /> elements in the item variant to remove any excess inherited fabrication requirements.
[06/02/2023 13:30:25] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/lxjzh/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2532991202/UI/DE-IconsAtlas.png, size: 1365x1365)
[06/02/2023 13:30:24] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/lxjzh/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2827262734/picture/Artexplosion.png, size: 2629x2605)
[06/02/2023 13:30:23] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/lxjzh/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2827262734/picture/tsmcons.png, size: 281x91)
[06/02/2023 13:29:57] Attempting to open ALC device "OpenAL Soft on 扬声器 (Realtek(R) Audio)"
[06/02/2023 13:29:54] Logged in as LXXGING (SteamID STEAM_1:1:195114146)
```

**Comment by Regalis11** [comment] 2023-06-02 12:14
Thank you for the report!

Looking at the crash report, it seems the crash happens when a bot tries to repair things with a repair tool that doesn't require any fuel. I suspect it's some other mod than DynamicEuropa that's causing this, but on a quick look through the mod list, I can't say for sure which one it could be. 

In any case, I added a fix that should prevent this from crashing the game in the future (commit in our private repo: https://github.com/Regalis11/Barotrauma-development/commit/8c1f203de0289f94cc8b342b7bcdd5a004d7d574). Sorry for the inconvenience!

**Comment by Jasontti** [comment] 2023-06-08 05:46
Difficult to test.
Made working welding tool that didn't need fuel, at one point even didn't have inventory, but bots could not use it without fuel tank.
Removed `<RequiredItems items="oxygensource,weldingtoolfuel" type="Contained"`
Still got message `Cannot find an item with the following identifier or tag: weldingfuel`

**Comment by Regalis11** [comment] 2023-06-11 11:31
Could not reproduce. I removed the `<Requireitems>` element too, and the bots seem to have no issues using a welding tool without a fuel tank. Are you sure you were running the game with the correct xml files? I.e. that you had those changes in the xml files in the build folder when you started the game?

**Comment by Jasontti** [comment] 2023-06-14 06:05
Tested,
I get now `"Barotrauma.Items.Components.RepairTool" has no proper inventory` when weldingtool has no <RequiredItems> and no <ItemContainer>, could be user issue on my part.
All error are caught and no crashes experienced.

**Comment by markboss33** [comment] 2023-06-26 20:35
is says 404

**Comment by Regalis11** [comment] 2023-07-12 18:06
@markboss33 It's a link to our private repository, the fix is unfortunately not publicly available yet. Sorry for the inconvenience!

**Comment by Jasontti** [comment] 2023-07-21 09:21
Tested and no issues found.
Closing ticket.

**Closed by Jasontti** 2023-07-21 09:21 UTC
Labels: Bug, Code, Crash, Modding
