### ISSUE TITLE
crashreport（17）.log

### ISSUE THREAD

**Issue by judy3963** [Regalis11/Barotrauma#9255] opened 2022-06-04 03:40 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

出現
![image](https://user-images.githubusercontent.com/106855198/171979803-34bdaf59-d666-4dee-8b52-4a8aa98810b9.png)

Barotrauma Client crash report (generated on 2022/6/4 上午 11:34:24)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

1FC87F527F5494A2CD53453BD2215F18

Game version 0.17.16.0 (ReleaseWindows, branch release, revision 05309f303f)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: None
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce GTX 1050
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: HRESULT: [0x8876017C], Module: [Unknown], ApiCode: [Unknown/Unknown], Message: Unknown (SharpDX.SharpDXException)
Target site: Void CheckError()
Stack trace: 
   at SharpDX.Result.CheckError()
   at SharpDX.DXGI.SwapChain.Present(Int32 syncInterval, PresentFlags flags)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 1010
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Present() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.cs:line 601
   at Microsoft.Xna.Framework.SdlGamePlatform.Present() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 251
   at Microsoft.Xna.Framework.Game.EndDraw() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 523
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 511
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59

Last debug messages:
[2022/6/4 上午 11:34:24] Attempting to open ALC device "OpenAL Soft on Speakers (Realtek High Definition Audio)"
[2022/6/4 上午 11:34:21] Logged in as 朱朱 (SteamID STEAM_1:0:75609603)

### Reproduction steps

無法啟動遊戲 啟動就崩潰
對不起我不會英文 google翻譯沒辦法翻譯我的意思
辛苦了

### Bug prevalence

Happens every time I play

### Version

Other

### -

0.17.16.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 2022/6/4 上午 11:34:24)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


1FC87F527F5494A2CD53453BD2215F18


Game version 0.17.16.0 (ReleaseWindows, branch release, revision 05309f303f)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: None
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce GTX 1050
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: HRESULT: [0x8876017C], Module: [Unknown], ApiCode: [Unknown/Unknown], Message: Unknown (SharpDX.SharpDXException)
Target site: Void CheckError()
Stack trace: 
   at SharpDX.Result.CheckError()
   at SharpDX.DXGI.SwapChain.Present(Int32 syncInterval, PresentFlags flags)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 1010
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Present() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.cs:line 601
   at Microsoft.Xna.Framework.SdlGamePlatform.Present() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 251
   at Microsoft.Xna.Framework.Game.EndDraw() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 523
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 511
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59


Last debug messages:
[2022/6/4 上午 11:34:24] Attempting to open ALC device "OpenAL Soft on Speakers (Realtek High Definition Audio)"
[2022/6/4 上午 11:34:21] Logged in as 朱朱 (SteamID STEAM_1:0:75609603)
```

**Comment by Regalis11** [comment] 2022-06-05 12:02
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7055

**Closed by Regalis11** 2022-06-05 12:02 UTC

**Comment by judy3963** [comment] 2022-06-05 12:20
作者您好請問 這個問題有辦法解決嗎

Joonas Rikkonen ***@***.***> 於 2022年6月5日 週日 下午8:02寫道：
