### ISSUE TITLE
Unstable: Holding pets crashes the game

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#4524] opened 2020-12-14 21:17 UTC
- [yos ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
This happens even without nothing in the pet's inventory. This bug is very inconsistant, it only happened once to me and a friend.
**Steps To Reproduce**
Grab a pet after you hatch it, in my and my friend's situation we were on a multiplayer campaign.
**Version**
Unstable v0.1200.0.0, Windows.
[crashreport (8).log](https://github.com/Regalis11/Barotrauma/files/5691617/crashreport.8.log)

**Comment by Regalis11** [comment] 2020-12-15 07:56
Duplicate of https://github.com/Regalis11/Barotrauma/issues/4513

**Closed by Regalis11** 2020-12-15 07:56 UTC
Labels: Bug, Code, Crash, Duplicate
