### ISSUE TITLE
Discharge Coils broken after update(Video Example included)

### ISSUE THREAD

**Issue by Ericqs2** [Regalis11/Barotrauma#10750] opened 2022-12-17 18:13 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

1-**Range variable is not being accounted** (Defined by "ElectricalDischarger>Range" on editor) - It was accounted before.
Discharge effect only works near hulls, no matter the range variable. 

2-**"Bolts" are not tracking targets** , rendering them only as cosmetic effects.  - They tracked before.
Reducing effectiveness + Increasing particle load.

Media
_Test Assembly:_
_7 Discharge coils at different distances._ (Discharge duration=0.02;Reload Time:0) **All located to the RIGHT side** of the screen

**Before Update:** Notice how the bolts tracked the targets + Range 
https://share-me.video/video/NfLyLjRcST7PIlsJeJX6qEMlaNhW9P8IruFHqZ7NQnqATCZzLsLs26Ax23R70fsd

**After Update:** Notice how even with the coils on the RIGHT side , the effect is only applied near the hull
https://share-me.video/video/3ufpkGmDJPsdSqLLYBKLRQ0JtxHOVINIjF3htGZgnpVyX8Hd6YY6jIS1sdKl8spm

### Reproduction steps

1. Open Editor
2. Make an assembly with multiple Discharge coils
3. No matter the range, reload, discharge duration - Just place them anywhere near your targets and make them able to fire.
4. Note that the bolt effect applies first to the hull, then to the targets. 
  - Does not consider RANGE variable.
  - Does not track targets.

### Bug prevalence

Happens every time I play

### Version

0.20.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Ericqs2** [comment] 2022-12-17 18:34
Exact assembly image: 
https://ibb.co/Jm3W1yy

**Comment by Regalis11** [comment] 2022-12-18 09:29
Thank you for the report!

I'm afraid I could not reproduce the issue. Would it be possible to share this submarine file with us? What's the range set to?

**Comment by Psyduckdeluxe** [comment] 2022-12-19 10:34
I can reproduce this and i dont need anything special to do it.
Just  place anything with particle effects and result. But since you cant reproduce it. Its likely a dependency thats broken. is my guess.

**Comment by Regalis11** [comment] 2022-12-19 11:18
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ca3ad074626af5ef3eb53154d837e1294bf9bc99

**Comment by itchyOwl** [comment] 2022-12-19 16:58
Not quite sure about this one. There's certainly a difference in the visual effect, but also the targets not touched with the visual effect seem to take damage. I used three coils with range 1000 and duration 10. Before the three remained unharmed. After the fix all took damage. But there's certain error margin with the test setting too. Also left a comment about the code.

Before the fix:
![image](https://user-images.githubusercontent.com/5370738/208474212-4b4e96d4-8959-4b0f-9fa2-a812a6ccea6b.png)

After the fix:
![image](https://user-images.githubusercontent.com/5370738/208475941-1d7ea3df-f102-438c-a36a-170030bfa251.png)

**Comment by Ericqs2** [comment] 2022-12-19 23:22
> Thank you for the report!
> 
> I'm afraid I could not reproduce the issue, the range parameter seems to be working as intended. I also could not open the videos linked here: the site is throwing an ERR_CONNECTION_REFUSED error. Would it be possible to share this submarine file with us? What's the range set to?
> 
> EDIT: nevermind, I was able to watch the video now! It does seem there's something strange going on here, I need to give this a proper test with the EDCs placed further from the submarine like this.

Sorry for the late response
DischargeCoil range was set to 4500
Sub link in the Workshop:
https://steamcommunity.com/sharedfiles/filedetails/?id=2894465283  - There should be 2 subs in the pack, the normal and the "(t.)"TEST version. An Yellow Periscope will give you access to the DischargeCoils.

Thanks for the help!

**Closed** 2023-01-16 08:38 UTC
Labels: Bug, Code
