### ISSUE TITLE
If NPC's get hurt inside a outpost they turn to rescue state and try to find medicine even if the damage is really low

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#2970] opened 2020-06-04 12:18 UTC
Tested on commit https://github.com/Regalis11/Barotrauma-development/commit/cf1eb76b67f31b885f799dc22a1c19154f5e74e3

This is partially caused by the same issue as bots are too eager to use up all the medicine even if they have received really small damage

NPC's can drop from ladders and get hurt which sets them to rescue state and they are stuck on that state as they can't complete it as there isn't any medical items in the outpost

Hardy even hurt yet panicking and running in circles. 
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/0edf2df5-6540-45d4-a6d2-98fb8fbf3caa)

All three of them are hurt because they dropped from this ladder
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/6b1cdc1c-efa3-4eb3-8ba9-2eed6b9bc476)

Debug view
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/24ba12cb-7481-4c84-9edc-244016f02b0e)

**Comment by Regalis11** [comment] 2020-06-08 06:13
Duplicate of #2927

**Closed by Regalis11** 2020-06-08 06:13 UTC
Labels: Bug, Code
