### ISSUE TITLE
Crashing when joining Multiplayer Lobby

### ISSUE THREAD

**Issue by M3M3M31S73R** [Regalis11/Barotrauma#11862] opened 2023-04-17 15:47 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

My friend just can't join my lobby, but if he hosts we're all able to join. My third friend is able to join both of us without issues 

### Reproduction steps

1. Host Multiplayer game 
2. Invite my friend 
3. His game crashes

### Bug prevalence

Happens every time I play

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
https://cdn.discordapp.com/attachments/815667720472231957/1097547748217196665/image.png
```

**Comment by Regalis11** [comment] 2023-04-17 17:26
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11789

**Closed as not planned by Regalis11** 2023-04-17 17:26 UTC
Labels: Bug, Duplicate, Code, Modding
