### ISSUE TITLE
Assault rifle able to fire with an empty magazine

### ISSUE THREAD

**Issue by Kapitan-Sladek** [Regalis11/Barotrauma#11874] opened 2023-04-20 08:55 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The assault rifle is able to continue shooting even after the magazine runs out, altough no bullets are fired, only the muzzle flash and sound.

### Reproduction steps

Happens every time I shoot continuously until the mag runs out, and it also happens when I try shooting again after stopping.

### Bug prevalence

Happens every time I play

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-04-20 09:09
Thank you for the report!

I'm afraid I could not reproduce the issue. Are you using some kind of mods? Did the issue occur in single player or multiplayer?

**Comment by Kapitan-Sladek** [comment] 2023-04-20 09:35
We're playing in multiplayer, I'm the host, server is not dedicated. I only have a mod that replaces guitar music, and it's only subscribed, not activated in the campaign. I'm gonna record a vid and attach it as soon as I can.

**Comment by Regalis11** [comment] 2023-06-10 09:48
No known steps to repro, closing

**Closed by Regalis11** 2023-06-10 09:48 UTC
Labels: Bug, Need more info, Code
