### ISSUE TITLE
0.10.4.0: OutpostConfig fails to acknowledge custom NPCsets

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#3387] opened 2020-07-18 05:34 UTC
[Modding, Bug]
custom NPCsets simply do not seem to work when specified as part of the natural "residents" of an outpostconfig (the ones that spawn naturally). just take a look:
![2020-07-18-003400_472x152_scrot](https://user-images.githubusercontent.com/47284081/87845608-79a52a00-c88e-11ea-965d-ff611c8da2f7.png)
![2020-07-18-003433_765x393_scrot](https://user-images.githubusercontent.com/47284081/87845609-7ad65700-c88e-11ea-9b93-6b0814ee9c54.png)

**Comment by hubismal** [comment] 2020-07-18 19:08
imo this is kind of high prio because from what i can tell a pretty important content type is unusable (NPCsets)

**Comment by Udrakan** [comment] 2020-07-25 22:21
I'd really appreciate being able to mod custom inhabitants. Guess we've gotta wait a bit.

**Comment by Regalis11** [comment] 2020-07-27 11:37
I was unable to reproduce this with the following config files:

OutpostGenerationParams.xml:
```
<?xml version="1.0" encoding="utf-8"?>
<override>
  <OutpostConfig
    identifier="outpost"
    totalmodulecount="6" minhallwaylength="0">
    <modulecount flag="Airlock" count="1"/>
    <modulecount flag="EngineeringModule" count="1"/>
    <modulecount flag="AdminModule" count="1"/>
    <modulecount flag="CrewModule" count="1"/>

    <npcs>
      <npc from="thal_generalnpcs" identifier="uesbeggar"/>
    </npcs>
    
  </OutpostConfig>
</override>
```

Npcs.xml:
```
<?xml version="1.0" encoding="utf-8"?>
<npcsets>
  <npcset identifier="thal_generalnpcs">
    <npc identifier="uesbeggar" job="captain" commonness="1" spawnpointtags="admin" behavior="Passive" preferredoutpostmoduletypes="admin,adminmodule">
      <ItemSet commonness="1">
        <Item identifier="idcard" equip="true"/>
        <Item identifier="captainscap1" equip="true"/>
        <Item identifier="captainsuniform1" equip="true"/>
        <Item identifier="revolver" equip="false">
          <Item identifier="revolverround"/>
          <Item identifier="revolverround"/>
          <Item identifier="revolverround"/>
        </Item>
        <Item identifier="captainspipe" equip="false"/>
        <Item identifier="divingmask">
          <Item identifier="oxygentank" />
        </Item> 
      </ItemSet>
    </npc>
  </npcset>
</npcsets>
```

Could you post your outpost config file in case the issue has something to do with how you're overriding the generation parameters?

**Comment by hubismal** [comment] 2020-07-29 01:13
I will get back to you with more information.

**Comment by Regalis11** [comment] 2020-08-31 12:04
I'm afraid we can't do much about this without further information, closing at least for now

**Closed by Regalis11** 2020-08-31 12:04 UTC
Labels: Bug, Code, Modding, Need more info

**Comment by hubismal** [comment] 2020-11-22 01:29
For the record this was apparently fixed.
