### ISSUE TITLE
Bots hoard fuel rods.

### ISSUE THREAD

**Issue by Momiro** [Regalis11/Barotrauma#4145] opened 2020-10-28 10:45 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots will take fuel rods from storage and hold them.

**Steps To Reproduce**
Play a game with bots, I usually have mine on guns, and they will sometimes shout "Cannot reach the reactor!"
Later, upon finding the bot dead after an invasion, and on multiple other instances, their inventory is full of fuel rods from the inventory, which had been noticed missing before discovering this bug.

**Version**
Current steam stable version, on windows.

**Comment by OverwatchVoice** [comment] 2020-10-28 19:30
Real players hoard fuel rods, bots are supposed to emulate players.
I see no problem here /s

**Comment by thegrb93** [comment] 2020-10-28 20:16
I like when players flush them down the toilet.

**Comment by itchyOwl** [comment] 2020-11-10 14:00
I guess it happens because the bots can't get to the reactor for some reason. For example some hull in the path is flooding. So it's more an oversight than a bug. I think the bots could just drop the fuel rods when they can't get to the reactor. The cleanup objective should then take care of putting the rods back where they belong to.

**Comment by itchyOwl** [comment] 2020-11-11 13:35
Implemented in Regalis11/Barotrauma-development@a891e15

**Comment by itchyOwl** [comment] 2020-11-11 13:37
Another reason for bots hoarding fuel rods could be that they take the extra rods from the reactor. See #4194. That too should now be fixed.

**Comment by Xeavas** [comment] 2020-11-11 17:49
[0.1100.0.5] - Unable to replicate 👍

Using this setup, locking the engineer in while they take the fuel rods, flooding the middle room (and sometimes the reactor room), opening door with lever. 

Bots correctly drop rods when trying to do other objectives (ie find safety)

**Comment by itchyOwl** [comment] 2020-11-11 19:05
There was an issue caused by the abovementioned commit, which in turn is fixed in Regalis11/Barotrauma-development@00f2b0c.

**Comment by Rokvach** [comment] 2020-11-11 21:25
Tested the latest fix, working correctly. Closing.

**Closed by Rokvach** 2020-11-11 21:25 UTC
Labels: Code
