### ISSUE TITLE
Powering transducer through relay causes intermitten signal lost issue

### ISSUE THREAD

**Issue by JimmySlickD** [Regalis11/Barotrauma#8841] opened 2022-04-18 15:34 UTC
- [ x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Wiring wifi connected tranducer with power through a relay causes random "No Signal" warning to appear, and the tranduser image will be very random. 
 
**Steps To Reproduce**
Shuttle battery (power out) -> relay (power in/out) -> Tranduser (power in)

**Version**
Current 0.16.7.0, win 11, intel 12700k, 2080ti

**Additional information**
Say you want to shut down the tranduser when drone is shut down, this will not be possible with a relay power using its on/off state.

**Comment by Regalis11** [comment] 2022-04-20 07:23
I'm afraid I couldn't reproduce the issue. Tested with this modified version of Selkie:
[Selkie.zip](https://github.com/Regalis11/Barotrauma/files/8519257/Selkie.zip)
 
I wonder if this could have something to do with the way you've set up the devices, maybe the transducer draws too much power for the battery to handle reliably, or maybe the range of the wifi components isn't long enough...?

**Comment by JimmySlickD** [comment] 2022-04-20 08:48
the relay had 3000 max, wifi had 80k range, own channel - tested with 5 different channels, tranduser power reduced to 20kw. powered the relay by main sub grid - even worse signal

**Comment by JimmySlickD** [comment] 2022-04-20 08:54
![image](https://user-images.githubusercontent.com/38655363/164190145-9b1ceb73-0be3-468c-8570-a06b9bb8b306.png)
[RiftbackDrone #8841.zip](https://github.com/Regalis11/Barotrauma/files/8519903/RiftbackDrone.8841.zip)
this version is powered by relay - steps: click on button on shuttle terminal to turn on drone - undock

**Comment by Regalis11** [comment] 2022-04-20 09:31
Thank you for the report! This seems to have been fixed by the power logic fixes we've been doing for the next update (which is currently testable in the unstable branch and will be publicly released soon).

**Closed by Regalis11** 2022-04-20 09:31 UTC
Labels: Bug, Code
