### ISSUE TITLE
another crash

### ISSUE THREAD

**Issue by sonicmaster155** [Regalis11/Barotrauma#5056] opened 2021-02-13 22:06 UTC
[servercrashreport (3).log](https://github.com/Regalis11/Barotrauma/files/5976609/servercrashreport.3.log)
[servercrashreport (4).log](https://github.com/Regalis11/Barotrauma/files/5976610/servercrashreport.4.log)

- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**

**Comment by Regalis11** [comment] 2021-02-14 12:46
Duplicate of https://github.com/Regalis11/Barotrauma/issues/5054

**Closed by Regalis11** 2021-02-14 12:46 UTC
