### ISSUE TITLE
Campaign - Spectators are spawned in on the next level

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4600] opened 2020-12-29 19:59 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Despite opting to be a spectator in the server lobby, you will be spawned in the level after the one you're spectating in.

I would also like a toggle to opt out of being a spectator when I feel like I am actually ready to spawn in on the next round, probably in the Tab menu.

**Version**
~0.1200.0.1HF

**Comment by subarotrauma** [comment] 2020-12-30 15:00
Above the character edit area is a checkmark for "spectator" this makes sure your not a player. You probably used the bottom spectate button before doing that.

**Comment by Kaillera** [comment] 2020-12-30 15:13
> Above the character edit area is a checkmark for "spectator" this makes sure your not a player. You probably used the bottom spectate button before doing that.

I was talking about that toggle to begin with.

**Comment by subarotrauma** [comment] 2020-12-30 18:07
Alright, I guess it's a bug then

**Comment by Rokvach** [comment] 2022-04-16 19:20
I did notice if you toggle spectate and then untoggle it and join a already running round, you do spawn in as a spectator and once the next round starts you spawn in as your character.

**Comment by Regalis11** [comment] 2022-04-21 10:46
I couldn't entirely reproduce that. The client does spawn as a spectator (which is normal ofc, as they have no character yet), but the respawn countdown starts as soon as they join and the client respawns as normal. Are you sure that it wasn't a matter of the respawn not triggering for some reason (not enough players to respawn, disabled respawns...?)

**Comment by Regalis11** [comment] 2022-06-06 18:25
No known steps to repro, closing

**Closed by Regalis11** 2022-06-06 18:25 UTC
Labels: Bug, Need more info, Code, Networking, Medium Prio

**Comment by frostcrystal** [comment] 2022-06-12 02:37
Got this bug today, here are my repro steps:

1) Entered a campaign I had previously played in, role was Captain, there were also three other players (non-Captain) and one NPC.
2) Check "Spectator" on the top right in the character creation menu
3) Spectate.

After one level when a mission was completed, I would always spawn in. Usually I would die since I wasn't really watching.

I eventually quit to the lobby (so I could listen if not watch) and found that even when I was in the lobby I would still get automatically spawned in whenever the ship docked after finishing a mission.
