### ISSUE TITLE
Branch sprite mismatch of Ballast Flora

### ISSUE THREAD

**Issue by iridescent-lightning** [Regalis11/Barotrauma#11952] opened 2023-05-03 13:12 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

<BranchSprite type="VerticalLane" sourcerect="256,0,64,64"/
<BranchSprite type="HorizontalLane" sourcerect="320,0,64,64"/
![Untitled](https://user-images.githubusercontent.com/94741028/235926004-6c9a9f03-ab5d-41b7-942f-b46d98b8ff92.png)

### Reproduction steps

Check your xmls and sprites.

### Bug prevalence

Happens every time I play

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-05-03 13:17
Thank you for the report! I'm not quite sure I see the issue, could you elaborate what the problem is here?

**Comment by iridescent-lightning** [comment] 2023-05-03 13:42
The vertical branch should be the vertical  looking. If you look the sprite according to the xml, you will find that the <BranchSprite type="VerticalLane" sourcerect="256,0,64,64"/ actually points to a horizontal looking sprite. (Same issue on the reverse)

**Comment by Regalis11** [comment] 2023-10-24 07:52
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/6900e33298729cf6f3556a333d4873284d061d8f

**Closed** 2024-01-16 11:42 UTC
Labels: Bug, Low prio, Testing branch
