### ISSUE TITLE
Error while reading a message / Exception thrown while reading segment (Tried to read too much data from segment)

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#11975] opened 2023-05-09 22:21 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I have no additional information. I don't remember how it happened, to be honest.

### Reproduction steps

Unknown

### Bug prevalence

Just once

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Error while reading a message from server. 
Exception thrown while reading segment EntityPosition at position 1288. Previous segments: Segment { Identifier = SyncIds, Pointer = 32 }, Segment { Identifier = EntityPosition, Pointer = 185 }, Segment { Identifier = EntityPosition, Pointer = 376 }, Segment { Identifier = EntityPosition, Pointer = 560 }, Segment { Identifier = EntityPosition, Pointer = 736 }, Segment { Identifier = EntityPosition, Pointer = 920 }, Segment { Identifier = EntityPosition, Pointer = 1104 }
Inner exception: Tried to read too much data from segment.
   at Barotrauma.Networking.SegmentTableReader`1.SegmentReadMsg.Check() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SegmentTable.cs:line 162
   at Barotrauma.Networking.SegmentTableReader`1.SegmentReadMsg.ReadSingle() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SegmentTable.cs:line 195
   at Barotrauma.Character.ClientReadPosition(IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\CharacterNetworking.cs:line 263
   at Barotrauma.Networking.GameClient.<>c__DisplayClass116_0.<ReadIngameUpdate>b__0(ServerNetSegment segment, IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2122
   at Barotrauma.Networking.SegmentTableReader`1.Read(IReadMessage msg, SegmentDataReader segmentDataReader, ExceptionHandler exceptionHandler) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SegmentTable.cs:line 296
```

**Comment by NilanthAnimosus** [comment] 2023-05-30 09:01
Closing due to not enough information to reproduce.

If you can provide more information and see this again (such as mods used, maybe a save file to replicate the same conditions) would allow us to look into this properly.

**Closed by NilanthAnimosus** 2023-05-30 09:01 UTC
Labels: Bug, Need more info, Code, Networking
