### ISSUE TITLE
Bug debug termal

### ISSUE THREAD

**Issue by Cusssy** [Regalis11/Barotrauma#9546] opened 2022-07-08 23:22 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When i talk with the NPC shipyard, the debug terminal opens, spitting the error "Failed to parse the string "COLOR GUI.GREEN" to Color" and cannot be closed, making it impossible to apply any enhancements to the submarine
![image](https://user-images.githubusercontent.com/71029516/178081262-15e85ada-613b-4539-a900-95373aab3486.png)

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Ek-Videogames** [comment] 2022-07-09 04:33
Spanish moment - duplicate of #9408 / #8914 
just the current build is really far behind

**Comment by Regalis11** [comment] 2022-07-09 10:10
Duplicate of https://github.com/Regalis11/Barotrauma/issues/9408

**Closed by Regalis11** 2022-07-09 10:10 UTC
