### ISSUE TITLE
Infinite Loop Wiring Crash

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5080] opened 2021-02-15 17:20 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Wiring components into an infinite feedback loop crashes the game.
Example: Memory (value: 1) -> Round1 -> Round2 -> Round1

**Steps To Reproduce**
wire an infinite signal loop using round components

**Version**
0.12.0.2

**Additional information**
lol

**Comment by Working-Joe** [comment] 2021-02-15 17:45
Oh lol. This holds for all components that send their signal in the `ReceiveSignal` method rather than in `Update`. Round, trig, exp, not, signal checks comps and the likes will all crash this way. 

Pretty sure the problem lies with the SendSignal coroutine:

https://github.com/Regalis11/Barotrauma/blob/f433a7ba10f6a6f1d33ba5229fbe936d8e7161f4/Barotrauma/BarotraumaShared/SharedSource/Items/Item.cs#L1876-L1898

This function continues signals that take more than 10 steps for a next round using a coroutine.

Now the problem is that the affected component can process multiple signals *per frame*. So each new signal send into one of these loops starts a new looping signal that is kept running indefinitely. With a mem adding one of these signals per frame, things get out of hand quickly. (Not to give any ideas, but if you'd add two wires from round 1 to round 2 it'd scale exponentially and you get to a crash even faster).

A hotfix might be just removing this coroutine temporarily, although it may break a few circuits. At least throw a warning in the console to notify people that a signal in their circuit has been eaten.

An actual good fix, however, may be quite a bit harder as just moving the `SendSignal` function from the `ReceiveSignal` to the `Update` function for the affected components will break many, many more circuits. (especially those dealing with WiFi)

The devs would somehow have to find a different way of detecting loops that prevents multiple signals from looping in the same few components.

**Comment by Regalis11** [comment] 2021-02-16 14:01
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7b50cb703410cad209707787cb5fcda8cd41c3c2 by interrupting the signal if it starts to loop through the same items.

**Comment by Xeavas** [comment] 2021-03-28 10:41
[v0.1300.0.3] - Unable to replicate 👍

**Comment by Rokvach** [comment] 2021-03-28 11:23
Closing

**Closed by Rokvach** 2021-03-28 11:23 UTC
Labels: Bug, Code, Medium Prio
