### ISSUE TITLE
Harpoons/items visible in containers sometimes go tilted/rotated

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10580] opened 2022-11-27 00:07 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While a tad inconsistent, theres plenty of cases with harpoons being put into harpoon guns, with the sprite being tilted, well and occasionally for other things, like dive suits. This isnt exactly a new issue, though it is continuous to the factions branch. Seems to happen when the item is picked up while its tilted, usually in water, leaving it to keep the same angle.
![image](https://user-images.githubusercontent.com/104232152/204113468-24f7423c-df24-412e-ba46-90974e063222.png)

### Reproduction steps

1.Try to pick up an item while its tilted/slanted, for example a harpoon
2.Insert said harpoon, or item, into a container, where its visible
3.Look at that goofy thing
(Sadly, as relatively common as this happens, ive had a hard time to repeat it consistently)

### Bug prevalence

Happens every now and then

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment] 2022-12-05 11:46
I can only assume that I was able to reproduce this, I dropped a diving suit from a ladder and it rotated on the ground and then I picked it up and placed in the diving locker, there wasn't any rotation. So seems to be working correctly, closing.

**Comment by Regalis11** [comment] 2022-12-25 12:12
Does not seem to be fixed https://github.com/Regalis11/Barotrauma/issues/10807, reopening

**Comment by Rokvach** [comment] 2023-01-18 14:48
Tested, wasn't able to repro no matter how many times I tried with the steps, working correctly. Closing.

**Comment by Rehexr** [comment] 2023-02-11 23:07
Not fixed in new build, sadly, same issues popped up once more
![image](https://user-images.githubusercontent.com/104232152/218284885-a3f8bf88-6fdc-4e61-b46d-7d48a850399b.png)

**Comment by Rehexr** [comment] 2023-02-17 22:03
![image](https://user-images.githubusercontent.com/104232152/219802296-fbaf9713-6202-460e-8bbf-6d551b4b2308.png)

again, no clue how to replicate, still an issue though

**Comment by Regalis11** [comment] 2023-04-25 14:17
Yet another attempt to address this: https://github.com/Regalis11/Barotrauma-development/commit/64134e5ddb6d6d8be836ab268b837d8c7796486b

> Still haven't been able to repro the issue reliably. I think it might've happened when the rotationOffset of the item (offset used to smooth out the item's visual rotation when correcting the rotation in MP)  is non-zero when it's put in a container.

**Comment by Jasontti** [comment] 2023-07-17 06:59
Tested.
Dropped held and suit character was wearing many times. Seems to be fixed.
Closing.

**Closed** 2023-07-18 10:50 UTC
Labels: Bug, Need more info, Code
