### ISSUE TITLE
[Code] Error Message

### ISSUE THREAD

**Issue by MrTeco** [Regalis11/Barotrauma#2426] opened 2020-03-12 15:04 UTC
I get this message when starting a server, I know it's my fault but it doesn't tell me where I messed up in the code.
![image](https://user-images.githubusercontent.com/59005337/76535388-0f612080-647b-11ea-879c-e00363af07e0.png)

**Comment by Regalis11** [comment] 2020-03-12 17:10
It seems something went wrong when loading the content packages: this crash seems to be caused by trying to check the list of content packages when no content packages have been loaded. 

I'm assuming you're using some core content package mod? Do you get a more informative error message when using the mod in the normal game (client executable)?

**Comment by MrTeco** [comment] 2020-03-12 18:43
I am not using content packages as this is a dedicated server which I compiled with your source code, doesn't make sense.

**Comment by Regalis11** [comment] 2020-03-12 19:25
Oh, I see. In that case you could try doing a small change to the code to prevent the server from crashing while writing the crash report. You can do that by going to Barotrauma/BarotraumaServer/ServerSource/Program.cs, and changing the line
`sb.AppendLine("Selected content packages: " + (!GameMain.SelectedPackages.Any() ? "None" : string.Join(", ", GameMain.SelectedPackages.Select(c => c.Name))));`
to
```
if (GameMain.SelectedPackages != null)
{
    sb.AppendLine("Selected content packages: " + (!GameMain.SelectedPackages.Any() ? "None" : string.Join(", ", GameMain.SelectedPackages.Select(c => c.Name))));
}
```

That should let you see the actual error that's causing the crash. Sorry for the inconvenience!

**Comment by MrTeco** [comment] 2020-03-13 13:33
Let me see...

**Comment by MrTeco** [comment] 2020-03-13 23:58
[servercrashreport (10).log](https://github.com/Regalis11/Barotrauma/files/4332029/servercrashreport.10.log)
Is the Github release missing "text packs"?
I am confused

**Comment by Regalis11** [comment] 2020-03-15 11:20
The content folder (including the text files that are causing this exception) is not included in the public repository. As mentioned in the contributing instructions (https://github.com/Regalis11/Barotrauma/blob/master/CONTRIBUTING.md), you need to copy the Content folder from your Steam copy of Barotrauma to the repository folder before you can use the source code.

**Comment by Regalis11** [comment] 2020-03-15 14:12
Added a more descriptive error message when the Content folder is not present: https://github.com/Regalis11/Barotrauma-development/commit/032311e05b08ddee193e7f8671d07c16f694097b

**Comment by Rokvach** [comment] 2020-03-15 14:41
No issues, closing.

**Closed by Rokvach** 2020-03-15 14:41 UTC
Labels: Code, Crash, Modding

**Comment by MrTeco** [comment] 2020-03-16 13:03
Thanks
