### ISSUE TITLE
Problem with server

### ISSUE THREAD

**Issue by Viktop39** [Regalis11/Barotrauma#7986] opened 2022-01-05 10:30 UTC
**Description**
When I create a server, the game crashes and the following error appears: A crash report("crashreport().log") was saved in the root folder of the game. The error was not sent to the developers because user statistics have been disabled, but if you'd like to helt fix this bug, you may post it on Barotrauma's GitHub ussue tracker

**Version**
The error occurred in the game version 0.15.22.1.A version of the Windows operating system

**Additional information**
Barotrauma Client crash report (generated on 05.01.2022 12:49:54)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

25F2DA9FCBD0323CBDF4FC2DA2092C7B

Game version 0.15.22.1 (ReleaseWindows, branch release, revision 898f64d2c0)
Graphics mode: 1024x768 (Fullscreen)
VSync OFF
Language: Russian
Selected content packages: Vanilla 0.9, Europan Nattereri, гигахрущевка 0.0.3, Clown crawler (fix), Peptinus
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.MainMenuScreen
SteamManager initialized
Client (Round hadn't been started)

System info:
    Operating system: Microsoft Windows NT 6.3.9600.0 64 bit
    GPU name: Intel(R) HD Graphics
    Display mode: {Width:1366 Height:768 Format:Color AspectRatio:1,7786459}
    GPU status: Normal

Exception: ChildServerRelay readTask did not run to completion: status was WaitingForActivation. (System.Exception)
Target site: Int32 ReadIncomingMsgs()
Stack trace: 
   at Barotrauma.Networking.ChildServerRelay.ReadIncomingMsgs() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 114
   at Barotrauma.Networking.ChildServerRelay.<UpdateRead>g__readBytes|27_0(Span`1 readTo) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 143
   at Barotrauma.Networking.ChildServerRelay.UpdateRead() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 154
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()

Last debug messages:
[05.01.2022 12:49:53] Exiting...
[05.01.2022 12:48:30] OpenAL Soft on Микрофон (2- Устройство с поддержкой High Definition Audio) 74
[05.01.2022 12:47:43] OpenAL Soft on Микрофон (2- Устройство с поддержкой High Definition Audio) 74
[05.01.2022 12:42:39] (Warning) SteamNetworkingSockets lock held for 22.6ms.  (Performance warning.)  ServiceThread,BInternalGetPingLocation,EnsureDataCenterRoutesValid(x2),ThinkPingProbes,CreateServerDataForCluster(x4)
This is usually a symptom of a general performance problem such as thread starvation.
[05.01.2022 12:42:39] (Msg) SDR RelayNetworkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[05.01.2022 12:42:39] (Msg) Ping location: sto=76+7,sto2=77+7/76+7,fra=90+9,ams=100+10/96+7,waw=119+11/97+7,par=121+12/99+9,lhr=105+10/101+7,vie=106+10/102+9,mad=129+12/120+9,iad=191+19/175+9,sgp=342+34/287+25,gru=293+29
[05.01.2022 12:42:39] (Msg) Ping measurement completed
[05.01.2022 12:42:37] (Verbose) Communications with routing cluster 'iad' established.
[05.01.2022 12:42:37] (Debug) Destroying relay 'iad#78 (162.254.192.69:27016)' because initial_ping_timeout
[05.01.2022 12:42:35] (Verbose) Communications with routing cluster 'seo' established.
[05.01.2022 12:42:35] (Verbose) Communications with routing cluster 'tyo1' established.
[05.01.2022 12:42:35] (Verbose) Communications with routing cluster 'tyo' established.
[05.01.2022 12:42:35] (Verbose) Communications with routing cluster 'syd' established.
[05.01.2022 12:42:35] (Verbose) Communications with routing cluster 'sgp' established.
[05.01.2022 12:42:35] (Verbose) Communications with routing cluster 'eze' established.
[05.01.2022 12:42:35] (Verbose) Communications with routing cluster 'scl' established.
[05.01.2022 12:42:35] (Verbose) Communications with routing cluster 'hkg' established.
[05.01.2022 12:42:35] (Verbose) Communications with routing cluster 'waw' established.
[05.01.2022 12:42:35] (Verbose) Communications with routing cluster 'lim' established.
[05.01.2022 12:42:35] (Verbose) Communications with routing cluster 'gru' established.
[05.01.2022 12:42:35] (Verbose) Communications with routing cluster 'vie' established.
[05.01.2022 12:42:35] (Verbose) Communications with routing cluster 'sea' established.
[05.01.2022 12:42:35] (Verbose) Communications with routing cluster 'bom' established.
[05.01.2022 12:42:35] (Verbose) Communications with routing cluster 'maa' established.
[05.01.2022 12:42:35] (Verbose) Communications with routing cluster 'jnb' established.
[05.01.2022 12:42:35] (Verbose) Communications with routing cluster 'sto2' established.
[05.01.2022 12:42:35] (Verbose) Communications with routing cluster 'sto' established.
[05.01.2022 12:42:35] (Verbose) Communications with routing cluster 'ord' established.
[05.01.2022 12:42:35] (Verbose) Communications with routing cluster 'lax' established.
[05.01.2022 12:42:35] (Verbose) Communications with routing cluster 'dxb' established.
[05.01.2022 12:42:35] (Verbose) Communications with routing cluster 'dfw' established.
[05.01.2022 12:42:35] (Verbose) Communications with routing cluster 'atl' established.
[05.01.2022 12:42:35] (Verbose) Communications with routing cluster 'ams' established.
[05.01.2022 12:42:35] (Verbose) Communications with routing cluster 'par' established.
[05.01.2022 12:42:35] (Verbose) Communications with routing cluster 'mad' established.
[05.01.2022 12:42:35] (Verbose) Communications with routing cluster 'lhr' established.
[05.01.2022 12:42:35] (Verbose) Communications with routing cluster 'fra' established.
[05.01.2022 12:42:35] (Warning) SteamNetworkingSockets lock held for 1000.6ms.  (Performance warning.)  ServiceThread,CSDRHTTPRequest::Think,OnNetworkConfigFetchCompleted,SetNetworkConfig,CreateSharedClusterData,BeginFetchNetworkConfig,ThinkPingProbes(x2),CreateServerDataForCluster(x20),RelayServer::New(x20),OpenRawUDPSocketInternal(x20),SendUDPacket(x20)
This is usually a symptom of a general performance problem such as thread starvation.
[05.01.2022 12:42:35] (Msg) SDR RelayNetworkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[05.01.2022 12:42:35] (Msg) Performing ping measurement
[05.01.2022 12:42:34] (Msg) Got SDR network config.  Loaded revision 365 OK
[05.01.2022 12:42:34] (Warning) SteamNetworkingSockets lock held for 58.0ms.  (Performance warning.)  HTTPRequestCompleted_t
This is usually a symptom of a general performance problem such as thread starvation.
[05.01.2022 12:42:34] (Warning) Waited 1162.6ms for SteamNetworkingSockets lock [HTTPRequestCompleted_t]
[05.01.2022 12:42:34] (Warning) SteamNetworkingSockets lock held for 1951.1ms.  (Performance warning.)  ServiceThread,ThinkPingProbes,EnsureDataCenterRoutesValid
This is usually a symptom of a general performance problem such as thread starvation.
[05.01.2022 12:42:10] Ошибка подключения к главному серверу { System.Net.WebException: An error occurred while sending the request. The response ended prematurely.
 ---> System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at RestSharp.Http.GetRawResponseAsync(IAsyncResult result, Action`1 callback)
   at RestSharp.Http.ResponseCallback(IAsyncResult result, Action`1 callback) }
[05.01.2022 12:39:58] Attempting to open ALC device "OpenAL Soft on Динамики (2- Устройство с поддержкой High Definition Audio)"
[05.01.2022 12:39:49] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[05.01.2022 12:39:46] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[05.01.2022 12:39:41] Logged in as VikTop39 (SteamID STEAM_1:0:506151162)

**Comment by Regalis11** [comment] 2022-01-05 12:52
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7783

**Closed by Regalis11** 2022-01-05 12:52 UTC
