### ISSUE TITLE
Coalition submarine during pirate mission has no item at all

### ISSUE THREAD

**Issue by AzureNocte** [Regalis11/Barotrauma#11656] opened 2023-03-25 15:49 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

when doing separatist pirate mission to ambush a coalition submarine, it occurs that the coalition sub has no item in all containers, un like the opposite separatist ones.

![20230324175837_1](https://user-images.githubusercontent.com/44329789/227727527-03828924-1aed-431f-83ee-87bb47908052.jpg)
![20230324175842_1](https://user-images.githubusercontent.com/44329789/227727529-0a0342b9-de21-49e7-8de8-5d6e1411b11c.jpg)
![20230324175855_1](https://user-images.githubusercontent.com/44329789/227727532-1d37acc2-5b51-4093-aa17-c049fc02b445.jpg)

I was using lua mod, moveable and sellable wrecks and pirates sub mod, i dont know if these have a effect on this issus.

### Reproduction steps

1.start campaign.
2.at separatist outpost, pick pirate mission which requires to defeat a coalition sub.
3.during mission it will found that no item in coalition sub.

### Bug prevalence

Happens regularly

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-03-27 00:49
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11423

**Closed by Regalis11** 2023-03-27 00:49 UTC
