### ISSUE TITLE
Crafting items with half ingredients causes whole stack of that ingredient to become half if in linked cabinet

### ISSUE THREAD

**Issue by drunken-dwarf** [Regalis11/Barotrauma#12945] opened 2023-10-30 09:40 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Crafting an item that uses only parts of an ingredient will cause other instances of that ingredient, if stored in linked storage (like a cabinet), to also become used by that amount.
It should, however, just have used/damaged the one instance that was pulled into the fabricator, like it did prior to the Treacherous Tides update.

This does not affect vanilla as there are no recipes with partial ingredients (as far as I am aware), but it is a game breaking bug for any mod that does have them as it effectively deletes items.

In my tests I used the mod Hungry Europans, but any recipe with a partial ingredient that is stackable works.

Thanks to Ed_Blue_430#5511 on Discord for explaining it well and making me aware that it is not caused by a mod, ending a wild goose chase.

### Reproduction steps

1. Install mod that has recipes with partial ingredients (Like Hungry Europans or Neurotrauma)
2. Load up sub editor
3. Set up and/or access crafting station with a linked cabinet
4. Place ingredient(s) in **cabinet**
5. Choose recipe which only uses a part of the ingredient(s) placed inside the cabinet
    With Hungry Europans I used "Raw Crawler Meat Patty" in Cutting Board (uses 5% of item "Salt")
    With Neurotrauma I used "Empty Blood Pack" in Medical Fabricator (uses 50% of item "Plastic")
6. Start crafting
7. Open cabinet and observe whole stack of ingredient to be used/damaged, just like a stack of welding fuel would after a fire

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.1.18.1 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment] 2023-10-30 09:56
Duplicate of https://github.com/Regalis11/Barotrauma/issues/12855

**Closed by Regalis11** 2023-10-30 09:56 UTC

**Comment by drunken-dwarf** [comment] 2023-10-30 10:15
My mistake, I must have used improper keywords during my search.
Thank you!
