### ISSUE TITLE
Text Display not showing with reduced font sizes

### ISSUE THREAD

**Issue by marbel9** [Regalis11/Barotrauma#12134] opened 2023-06-08 08:24 UTC
Hello, I'm having the same issue on 1.0.13 that was reported [here ]( https://github.com/Regalis11/Barotrauma/issues/11572) for 1.0.8.

(multiplayer)

[Save/sub here](https://drive.google.com/drive/folders/1XKcWzxnSr1tw3ZmvaBQZJrS3q8Zh8U0-?usp=sharing)

![image](https://github.com/Regalis11/Barotrauma/assets/67078075/43ae6d85-0522-431d-89da-46f547514601)

![image](https://github.com/Regalis11/Barotrauma/assets/67078075/dfdf4e71-be47-4076-b64b-675c069a3886)

@Rokvach @Regalis11

**Comment by Regalis11** [comment] 2023-06-08 09:37
Thank you for the report! The fix is not yet out in the public build, but it should be coming in the next patch. Closing as a duplicate of https://github.com/Regalis11/Barotrauma/issues/11572

**Closed by Regalis11** 2023-06-08 09:37 UTC
