### ISSUE TITLE
Frame drop and crash

### ISSUE THREAD

**Issue by DifferentLevelDan** [Regalis11/Barotrauma#164] opened 2017-12-15 18:49 UTC
After some barotraumatic events, FPS started dipping (To about 5FPS when looking at the sub) on my server (client). Other connected clients reported the FPS drop aswell. I had heard that teleporting bodies away can help alleviate some of those issues, so I slowly started teleporting old player bodies far to the left (Still in-bounds of the map)

When I attempted to teleport scout, the server immediately crashed with a nullref.

I notice the top of the call stack is the same as #159 (May be related) but did not ultimately follow the PhysicsBody.Enabled path.

[crashreport.txt](https://github.com/Regalis11/Barotrauma/files/1563636/crashreport.txt)

**Comment by Regalis11** [comment] 2018-07-05 13:16
My guess is that the crash was caused by the entity removal bug that was fixed in ceaba2f.

**Closed** 2018-08-07 10:32 UTC
Labels: bug
