### ISSUE TITLE
Error logs from MP steam hosted match

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#5451] opened 2021-04-07 16:10 UTC
**Description**
A couple disconnections due to entity errors
[event_error_log_server_UwU_1504.log](https://github.com/Regalis11/Barotrauma/files/6273015/event_error_log_server_UwU_1504.log)
[event_error_log_server_Solbusaur_1423.log](https://github.com/Regalis11/Barotrauma/files/6273090/event_error_log_server_Solbusaur_1423.log)
[event_error_log_server_Solbusaur_1435.log](https://github.com/Regalis11/Barotrauma/files/6273091/event_error_log_server_Solbusaur_1435.log)

**Version**
Unstable

**Comment by Rokvach** [comment] 2021-04-07 16:15
Can I get the Solbusaur one which matches this one? 

[event_error_log_client_Solbusaur_1435.log](https://github.com/Regalis11/Barotrauma/files/6273041/event_error_log_client_Solbusaur_1435.log)

**Comment by Udrakan** [comment] 2021-04-07 16:23
Edited

**Comment by Regalis11** [comment] 2021-04-08 11:47
I think this was caused by the recent changes to the way attaching items is synced. Can be reproduced as follows:
1. Spawn a holdable item that's not attachable (for example, Mutated Raptor Bane which seemed to cause the error in this case)
2. Desync the item's position client-side. Can be done with the new debug-only command "bumpitem" or by moving the item mid-round in the sub editor.
3. Try to pick up the item
4. The actual networking error caused by this can vary, because it causes the client read the data for the item incorrectly, messing up the rest of the message

**Comment by Rokvach** [comment] 2021-04-08 13:40
Tested, wasn't able to reproduce the issue with the above steps, will keep this ticket open  for the next Unstable just to test in a bit broader audience.

**Comment by Rokvach** [comment] 2021-04-09 20:49
No entity issues were spotted on the latest Unstable build, this seems to have been fixed as they were quite common in the previous one. Closing.

**Closed by Rokvach** 2021-04-09 20:49 UTC
Labels: Bug, Code, High prio, Networking
