### ISSUE TITLE
[1.0] Alien Ruins generation issues

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11348] opened 2023-02-24 03:06 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

There are a number of issues with Alien Ruins generating in 1.0 builds of the game. I have detailed the three critical problems below.

### Floating Alien Ruins

Alien Ruins in nearly every case spawn within a cave or hidden section within the wall. This floating Alien Ruins leads me to believe this is unintended behaviour based on previous ruin generation patterns.

![image](https://user-images.githubusercontent.com/105495756/221020759-bada5581-7a9e-4fbf-b7ad-e19dd89c6e09.png)
_Figure 1. Image of floating Alien Ruins._

![image](https://user-images.githubusercontent.com/105495756/221020851-4f99faa7-e8bc-494a-97fc-d8173d5e35d0.png)
_Figure 2. Debugdraw version of Figure 1._

![image](https://user-images.githubusercontent.com/105495756/221020827-f3e91e6d-dacd-47a6-850f-dec933fd0bf9.png)
_Figure 3. Image of misc debug menu I managed to pull up. I'm unsure if any of this information is relevant or important but wanted to include it in case it is._

![image](https://user-images.githubusercontent.com/105495756/221020800-8d120b12-de7a-4d3b-addf-0f5f890fdb2a.png)
_Figure 4. Level seed._

**Floating text from above ruin spawn**

This issue occurred within the same ruin pictured above. I'm unsure if the issues are caused by each other, or if they're independent from each other.

![image](https://user-images.githubusercontent.com/105495756/221033514-14e0bfba-685b-4306-a797-7baef5af21ff.png)
_Figure 5. Instance of floating alien text, circled for visibility._

![image](https://user-images.githubusercontent.com/105495756/221033575-1faa6aed-edd7-49a1-85c2-442b9971c3db.png)
_Figure 6. Instance of floating alien text, circled for visibility._

### Alien Ruins generating right next to the level start

On several occasions, Alien Ruins have generated directly next to the starting docking hatch. This makes the task of searching for the ruins incredibly trivial, as they are quite literally a stone's throw away. This also means no creature encounters can slow down or make the journey difficult; once the ruin is cleared from the start, the level now acts like a natural formation without any missions since you've already cleared the missions.

![image](https://user-images.githubusercontent.com/105495756/221021030-5177ad5f-7afc-4775-adad-11f65d60d223.png)
_Figure 7. Navigation Terminal's perspective after immediately loading into the level._

![image](https://user-images.githubusercontent.com/105495756/221020994-d2de9ad1-6498-4676-ae8f-67c0ec6d9f42.png)
_Figure 8. An image showing the Alien Ruins and starting docking hatch in the same screen._

![image](https://user-images.githubusercontent.com/105495756/221021036-3df62f42-449f-4dca-9c01-800315053346.png)
_Figure 9. Level seed._

### Bug prevalence

Happens regularly

### Version

Other

### -

1.0.2.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-02-24 09:24
Thank you for the report! 

I'm not entirely sure I understand the 1st issue. I'm probably misunderstanding something, since this seems similar to the issue of [floating outposts](https://github.com/Regalis11/Barotrauma/issues/10650) which I can't reproduce (or understand?) either. What exactly do you mean by floating? That the ruin isn't touching level walls? That it's not inside level walls? The way I see it, they _should_ float, as in not spawn touching or inside level walls. If they in some cases don't, that's a bug, and can cause parts of the ruin to be impossible to access.

**Comment by Regalis11** [comment] 2023-02-24 09:35
I also could not find those floating texts anywhere, but I'm not sure if I'm looking for it in the right place, or if it doesn't happen in the level editor where I was testing this:
![image](https://user-images.githubusercontent.com/14351070/221144031-97077749-17c1-471a-8b5b-1dc7c08f3699.png)
(Brightness and contrast increased to make it easier to see)

**Comment by ubertpendragon** [comment] 2023-02-24 13:06
> I'm not entirely sure I understand the 1st issue

We assume that ruins are supposed to spawn in their own little cave, but most of the time will spawn "floating" in open water, and often close to outposts.
I've generated 20 levels and ruins mostly spawn outside of a cavity.

![image](https://user-images.githubusercontent.com/73229309/221184882-5b2ecb93-365a-41bf-880d-47e9cb6d3d54.png)

Ruins "cavity", but also right next to outpost
![image](https://user-images.githubusercontent.com/73229309/221185946-bab4159c-ef9f-41f7-9210-c22aea5e54d3.png)

**Comment by Regalis11** [comment] 2023-02-24 15:19
>We assume that ruins are supposed to spawn in their own little cave, but most of the time will spawn "floating" in open water, and often close to outposts.

They are not, they just spawn a certain minimum distance away from the main path, which can be a cavity inside walls or open water if the chosen position happens to be e.g. below the main path in a level with no floor.

**Comment by Regalis11** [comment] 2023-03-08 14:09
No steps to repro, closing

**Closed by Regalis11** 2023-03-08 14:09 UTC
Labels: Bug, Need more info, Code
