### ISSUE TITLE
Some items can no longer be hidden while still having their light sprite visible

### ISSUE THREAD

**Issue by Orum** [Regalis11/Barotrauma#11108] opened 2023-01-31 16:04 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Previously (i.e. before today's patch) it was possible to completely hide the sprite of a light by setting its alpha to 0, but still have the light function.  Numerous subs, of my own design as well as others', relied on this functionality for decoration or indication.

With today's patch, if the sprite is hidden by setting the alpha to 0, the light component will not appear either, making the appearance of the sprite mandatory for the light to function.

### Reproduction steps

1. Load a sub in the sub editor or make a new sub.
2. Place a large black (set the color of the sprite to 0,0,0,255) label in the sub.
3. Add in two light component lights on top of the label, near each other but not on top of one another.
4. Set the range of both lights to '5', and check the 'Is On' box for both lights.
5. Set the alpha of the sprite color to 0 on **one** of the lights, and leave the other at the default (255).
6. Test the sub from the editor.  Note how only one of the two lights' lighting appears in the current version.
7. Compare this with the lighting behavior in game with older versions of Barotrauma (i.e. one before today's patch).

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Linux

**Comment by SeaverBeaver** [comment] 2023-01-31 17:11
Yikes, this is a dealbreaker for many subs. Does setting the sprites alpha to 1 fix this problem?

**Comment by Regalis11** [comment] 2023-01-31 17:40
Thank you for the report! This seems to have happened as a side-effect of the fix implemented for https://github.com/Regalis11/Barotrauma/issues/10900.

To be more exact, the light itself works, it's the additive "light sprite" that becomes invisible. This is why the issue is only noticeable if you set the range to something like 5, making the actual light emitted by the component too low-range to see. The issue also doesn't seem to affect all light sources.

In any case, I'm looking into this, hopefully we can get it fixed soon. Sorry for the inconvenience!

**Comment by Regalis11** [comment] 2023-02-01 09:14
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/eebcaf0c0a1393af362ce906328b08cd437722f1

**Comment by Rokvach** [comment] 2023-02-03 09:17
Tested, working correctly. Closing.

**Closed by Rokvach** 2023-02-03 09:17 UTC
Labels: Bug, Code

**Comment by Orum** [comment] 2023-03-06 08:58
I know this is 'fixed' in unstable now, but after playing around with the stable (i.e. 'bugged') behavior, I actually found it pretty useful.  Namely, it allows you to "mask" lights using dark objects, and then have only the lighter areas of the objects glow.

For example, here's an illuminated green arrow display I made used to point to a waypoint that users can set: 
![gps](https://user-images.githubusercontent.com/547467/223061758-afa533f0-5676-475e-bb31-e4bb53f370fa.png)

...or an electrical sign that flickers as it's illuminated by an invisible light: 
![sign](https://user-images.githubusercontent.com/547467/223063011-82befa45-ee00-4b24-bc98-56ef2a8aa40b.png)

In hindsight, I guess I wish I'd never requested the fix, though someone else probably would have anyway.  That said, will there be any way to replicate this current 'buggy' behavior once the next update launches, so these sort of effects are still possible?

**Comment by Regalis11** [comment] 2023-03-06 18:26
It probably isn't possible with any vanilla lighting item, but it should be possible to replicate it with a custom item. Specifically, LightComponents now have a property called `AlphaBlend` which causes the light sprite to be drawn using alpha blending, in addition to the multiplicative blending. It defaults to true, and is set to true on most vanilla lights (excluding e.g. things like reactor lights, whose sprites include dark areas), but could be set to false on a custom item.
