### ISSUE TITLE
[Unstable V0.12.0.0] Hitbox issue, attacking through doors.

### ISSUE THREAD

**Issue by Marutzo** [Regalis11/Barotrauma#4535] opened 2020-12-15 13:20 UTC
- [ X ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I am able to attack and especially stun baton things through closed doors, and Husks are able to bite / infect with their appendage from a fair distance away, also through closed doors.

**Steps To Reproduce**
Have a Husk on one side of a closed door and aggressive towards you, then stand on the other side gradually getting closer to the door until you get hit by it.

Do the same with a stun baton, it can attack from quite a distance away if the Husk (or any creature actually) is very close to the door, the hitbox from the stun baton should be able to just reach beyond the door and stun the target.

**Version**
Unstable V0.12.0.0 on Windows 10

**Additional information**
Reference picture showing how far the baton can reach through doors (victim on other side was successfully stunned)
![baton_distance_reference](https://user-images.githubusercontent.com/69410159/102220090-a2365c00-3ee0-11eb-882e-29db76ab5094.png)

**Comment by Regalis11** [comment] 2020-12-18 12:39
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2ef13eaad7574778cc04fd1d73ae0379462b1cca

**Comment by Rokvach** [comment] 2021-01-05 09:38
Human husks can still attack through doors

They can attack really far it seems like

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/775bd92a-1d0f-4649-b379-6cc14f2bec51)

**Comment by Regalis11** [comment] 2021-01-05 12:34
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bb8ce2c4b2b6ef4b2d505b74420304f72a6b9d8d

**Comment by Rokvach** [comment] 2021-01-05 12:52
Wasn't able to reproduce the issue anymore, I was able to hit mudraptor at times but that was mainly because their limbs peaked through the door at times which I was able to land a hit on, but none of the creatures were able to attack me through the doors. I think this is good enough so working correctly. Closing.

**Closed by Rokvach** 2021-01-05 12:52 UTC
Labels: Bug, Code
