### ISSUE TITLE
No longer able to make Masterwork Fuel Rods or Batteries with level 100 Electrical skill and relevant talents

### ISSUE THREAD

**Issue by atlas-callisto** [Regalis11/Barotrauma#7856] opened 2021-12-19 02:46 UTC
- [x] I could not find any recent issues regarding this. This seems to be as of the latest update.

**Description**
Previously before death, I was able to craft Masterwork quality fuel rods when my skills were maxed out, however now I can only craft excellent quality fuel rods with all skills at level 100 and with my talent tree fully complete. 

**Steps To Reproduce**
Have Masterwork fuel rods be available, die/respawn causing skills to reset, while still having all your talents. Move to the fabricator, create any fuel rod, all appear to give excellent quality, both before and after fabricating one is complete. Masterwork was available before, but I lost my skills due to death and now having retrieved those skills, I no longer can create them at that quality. _I would guess it's my Remote Monitor skill for engineer not reapplying after death perhaps._ This is also the exact same process with batteries minus the recycling of course.

**Version**
0.15.22.1 (Windows 10, Steam, PC)

**Additional information**
This was previously possible until my death. Yes, **I do have the Remote Monitor  & Electrochemist skill enabled** so that fuel rods are one higher in quality and batteries are 1 higher in quality. My skill tree is fully complete. Recycling will also still give only excellent quality fuel rods in return.

**Comment by Kaillera** [comment] 2021-12-19 15:40
You need the talent to go from excellent to masterwork.

**Comment by Regalis11** [comment] 2022-01-04 11:32
I'm afraid I couldn't find a way to reproduce this. :/ Tested by doing the following:

1. Unlocked all the talents and gained enough skills to reach 100, at this point I can fabricate masterwork rods:
![image](https://user-images.githubusercontent.com/14351070/148052839-0bdc8a6f-3497-401b-b3f7-b4b561128368.png)

2. Killed the character and respawned. Can no longer fabricate masterwork rods as expected:
![image](https://user-images.githubusercontent.com/14351070/148052969-09df7853-d58c-4531-b30f-80424839c51f.png)

3. Leveled up to reach 100 again, I can fabricate masterwork rods again:
![image](https://user-images.githubusercontent.com/14351070/148053035-5d6a598b-4829-4f74-94b7-1fcd19a6b62c.png)

**Comment by atlas-callisto** [comment] 2022-01-04 11:37
So, one thing I did forget to mention, I wasn't exactly killed, but I left a lobby mid-game and came back much later to find I died. I then respawned with my skills being reset, to which I leveled them up again with books. All my talents were still there.

**Comment by Regalis11** [comment] 2022-01-04 12:14
Thank you for the clarification! I'll give it another test.

**Comment by Regalis11** [comment] 2022-01-04 13:21
Hmm, still no luck. :/ Something I noticed though is that the info on the status monitor doesn't automatically refresh after you've gained the skills, but reselecting the fuel rod on the fabricator makes the "masterwork quality" text appear. But I suppose that wasn't the problem in this case?

**Comment by atlas-callisto** [comment] 2022-01-04 13:25
Unfortunately not, after going ahead and making the fuel rod anyway, I still got the excellent quality one, not the Masterwork one, so the fabricator is showing me what it is going to give me.

**Comment by atlas-callisto** [comment] 2022-01-04 13:25
And again, same case with Batteries too.

**Comment by mattikan** [comment] 2022-02-02 19:33
Hello, noticed the same problem in a multiplayer campaign game today. Died foolishly in a session a couple days ago, respawned, finished the trip and ended the session for that night. Loaded the save today, and while I still have over 100 skill in Electrical Engineering, fuel rods I fabricate end up as Excellent, not Masterwork, even though I have the relevant quality-boosting talent, too.
Also suffering from the bug related to All-Seeing Eye in the same save - after picking that talent, I can't finish the leftmost talent tree even though I have a couple talent points free. No idea if it's relevant, but.
Would the save file of the campaign maybe help in reproducing this bug?

**Comment by atlas-callisto** [comment] 2022-02-02 23:00
So it seems it's not just me that got unlucky with this. It appears to have happened to you too... Well at least we know it *is* an issue know. Unfortunately, @Regalis11 wasn't able to reproduce the bug.

**Comment by Regalis11** [comment] 2022-02-11 11:07
Sorry for the late response!

@mattikan Yes, the campaign save (and the CharacterData file that should be located in the same folder) would most likely help us diagnose this! I have a feeling it could have something to do with the All-Seeing Eye issue, perhaps some kind of a discrepancy in which talents are unlocked server-side and client-side.

**Comment by Regalis11** [comment] 2022-02-22 13:56
Possibly caused by https://github.com/Regalis11/Barotrauma/issues/8128, moving to QA

**Comment by Rokvach** [comment] 2022-03-07 13:31
Tested, working correctly. Closing.

**Closed by Rokvach** 2022-03-07 13:31 UTC
Labels: Bug, Code
