### ISSUE TITLE
Wrecked oxygen Tank shelves have incomplete UI

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#11478] opened 2023-03-10 12:32 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

For my report 101, i present: Its a pretty simple ui issue where specifically wrecked oxygen tank shelves do not have the icon for canisters on every slot, only the first, thats all.
![image](https://user-images.githubusercontent.com/104232152/224316929-337205d4-7e2f-4dbc-810a-6e48089e532c.png)

### Reproduction steps

1.Open the Ui of a Wrecked oxygen tank shelf

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-03-10 13:50
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11239, has been addressed in https://github.com/Regalis11/Barotrauma-development/pull/3991/commits/9b68aa1415dd28276549ac3989bf656da3dec06f

**Closed by Regalis11** 2023-03-10 13:50 UTC
