### ISSUE TITLE
Dedicated Server - Client crash when launching sub from outpost

### ISSUE THREAD

**Issue by RobVice** [Regalis11/Barotrauma#6445] opened 2021-08-19 18:50 UTC
Client: Kubuntu 20.04
Server: Windows Server 2008 R2

Campaign starts fine, joins fine. When launching the sub (with or without mission), client immediately crashes, without the "transition" screen. Server seems to keep running, but ends the round with a bunch of errors. Completely vanilla reinstall of dedi server tried repeatedly.

Single player works fine, and also hosting a multiplayer session with others from the (Linux) client works fine.

No mods used, no custom subs used.

Crash log from Linux client:

Barotrauma Client crash report (generated on 08/19/2021 11:41:26)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

F99B9BA9D21FF6BB59D1E8FA34F1F668

Game version 0.14.6.0 (ReleaseLinux, branch release, revision 12d7084c07)
Graphics mode: 3840x2160 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: Erlangshen
Loaded submarine: Azimuth (47E4B8E52BF8546C5FB5154A50F7E43A)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)

System info:
    Operating system: Unix 5.11.0.25 64 bit
    GPU name: 
    Display mode: {Width:3840 Height:2160 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: TransitionType GetAvailableTransition(Barotrauma.LevelData ByRef, Barotrauma.Submarine ByRef)
Stack trace: 
   at Barotrauma.CampaignMode.GetAvailableTransition(LevelData& nextLevel, Submarine& leavingSub) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameSession/GameModes/CampaignMode.cs:line 382
   at Barotrauma.CampaignMode.Draw(SpriteBatch spriteBatch) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GameSession/GameModes/CampaignMode.cs:line 115
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Screens/GameScreen.cs:line 99
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 1038
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/SDL/SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 58

Last debug messages:
[08/19/2021 11:40:45] Robert
[08/19/2021 11:40:41] Task count: 0
[08/19/2021 11:40:37] Generating an outpost for the start of the level... (Location: Erlangshen City, level type: Outpost)
[08/19/2021 11:39:54] LobbyMatchList:  LobbiesMatching: 0
[08/19/2021 11:39:53] LobbyMatchList:  LobbiesMatching: 0
[08/19/2021 11:39:53] SteamAPICallCompleted:   AsyncCall: 3294441931519315728
   Callback: 510
 ParamCount: 4
[08/19/2021 11:39:53] LobbyMatchList:  LobbiesMatching: 9
[08/19/2021 11:39:53] LobbyMatchList:  LobbiesMatching: 9
[08/19/2021 11:39:53] SteamAPICallCompleted:   AsyncCall: 15580618118864400376
   Callback: 510
 ParamCount: 4
[08/19/2021 11:39:53] LobbyMatchList:  LobbiesMatching: 50
[08/19/2021 11:39:53] LobbyMatchList:  LobbiesMatching: 50
[08/19/2021 11:39:53] SteamAPICallCompleted:   AsyncCall: 773927667674893777
   Callback: 510
 ParamCount: 4
[08/19/2021 11:39:42] (Msg) SDR RelayNetworkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[08/19/2021 11:39:42] (Msg) Ping location: lax=27+2,sea=36+3,eat=/36+3,dfw=54+5,atl=64+6,ord=67+6,iad=82+8/77+6,tyo=126+12,tyo1=127+12/126+12,fra=167+16/162+6,sgp=187+18/188+18,gru=195+19/195+6
[08/19/2021 11:39:42] (Msg) Ping measurement completed
[08/19/2021 11:39:42] (Debug) Destroying relay 'eat#10 (155.133.235.18:27024)' because initial_ping_timeout
[08/19/2021 11:39:42] (Debug) Destroying relay 'sof#3 (139.45.193.10:27017)' because initial_ping_timeout
[08/19/2021 11:39:39] (Debug) Destroying relay 'eat#65 (155.133.235.34:27041)' because initial_ping_timeout
[08/19/2021 11:39:39] (Debug) Destroying relay 'sof#4 (139.45.193.10:27018)' because initial_ping_timeout
[08/19/2021 11:39:37] (Verbose) Communications with routing cluster 'jnb' established.
[08/19/2021 11:39:37] (Verbose) Communications with routing cluster 'dxb' established.
[08/19/2021 11:39:37] (Verbose) Communications with routing cluster 'bom' established.
[08/19/2021 11:39:37] (Verbose) Communications with routing cluster 'gru' established.
[08/19/2021 11:39:37] (Verbose) Communications with routing cluster 'hkg' established.
[08/19/2021 11:39:37] (Verbose) Communications with routing cluster 'eze' established.
[08/19/2021 11:39:37] (Verbose) Communications with routing cluster 'fra' established.
[08/19/2021 11:39:37] (Verbose) Communications with routing cluster 'maa' established.
[08/19/2021 11:39:37] (Verbose) Communications with routing cluster 'mad' established.
[08/19/2021 11:39:37] (Verbose) Communications with routing cluster 'iad' established.
[08/19/2021 11:39:37] (Verbose) Communications with routing cluster 'par' established.
[08/19/2021 11:39:37] (Verbose) Communications with routing cluster 'ams' established.
[08/19/2021 11:39:37] (Verbose) Communications with routing cluster 'scl' established.
[08/19/2021 11:39:37] (Verbose) Communications with routing cluster 'lhr' established.
[08/19/2021 11:39:37] (Verbose) Communications with routing cluster 'dfw' established.
[08/19/2021 11:39:37] (Verbose) Communications with routing cluster 'lim' established.
[08/19/2021 11:39:37] (Verbose) Communications with routing cluster 'waw' established.
[08/19/2021 11:39:37] (Verbose) Communications with routing cluster 'vie' established.
[08/19/2021 11:39:37] (Verbose) Communications with routing cluster 'sgp' established.
[08/19/2021 11:39:37] (Verbose) Communications with routing cluster 'sto2' established.
[08/19/2021 11:39:36] (Verbose) Communications with routing cluster 'sto' established.
[08/19/2021 11:39:36] (Verbose) Communications with routing cluster 'ord' established.
[08/19/2021 11:39:36] (Verbose) Communications with routing cluster 'syd' established.
[08/19/2021 11:39:36] (Verbose) Communications with routing cluster 'atl' established.
[08/19/2021 11:39:36] (Verbose) Communications with routing cluster 'sea' established.
[08/19/2021 11:39:36] (Msg) Relay lax#164 (162.254.195.88:27040) is going offline in 513 seconds
[08/19/2021 11:39:36] (Verbose) Communications with routing cluster 'lax' established.
[08/19/2021 11:39:36] (Verbose) Communications with routing cluster 'tyo1' established.
[08/19/2021 11:39:36] (Verbose) Communications with routing cluster 'tyo' established.
[08/19/2021 11:39:36] (Msg) SDR RelayNetworkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[08/19/2021 11:39:36] (Msg) Performing ping measurement
[08/19/2021 11:39:36] (Msg) Got SDR network config.  Loaded revision 330 OK
[08/19/2021 11:39:36] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[08/19/2021 11:39:24] Attempting to open ALC device "ALSA Default"
[08/19/2021 11:39:23] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[08/19/2021 11:39:23] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[08/19/2021 11:39:21] Logged in as [Robert] (SteamID STEAM_1:1:23505859)

**Comment by RobVice** [comment] 2021-08-25 14:12
A couple quick updates, then this can either be merged or removed.

I tested with every combination of client/server I could:

1. Windows 7/2008/10 client on Windows 7/2008/10 server
2. Linux client on Windows 7/2008/10 server
3. Windows 7/2008/10 client on Linux server
4. Linux client on Linux server

Still same issue. Then I while I dug through the existing issues here, I stumbled on to [this bug](https://github.com/Regalis11/Barotrauma/issues/4144) and for giggles I gave myself perms from the dedi console, and BAM, I was able to launch the sub without it crashing. It appears you cannot have a dedi multiplayer campaign without someone in the lobby who has perms - I didn't test granular permissions to see exactly what is required, I just gave "All" perms. I also tested removing the perms, and it crashed again.

**Comment by Regalis11** [comment] 2021-08-31 14:04
I'm afraid I couldn't reproduce this in either the latest version (v0.14.9.0) or the version the crash report was generated in (v0.14.6.0). 

Are you still running into this issue in the latest version, and if so, would it be possible to send us the crash report?

Sorry for the trouble!

**Comment by Regalis11** [comment] 2021-11-19 09:12
No known steps to repro, closing

**Closed by Regalis11** 2021-11-19 09:12 UTC
Labels: Bug, Need more info, Code, Crash
