### ISSUE TITLE
Electrical Discharge Coil (EDC) Power Draw Issues

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#10347] opened 2022-11-12 14:34 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Discharge Coils draw power weirdly and differently in these situations:
1. Supercapacitor output < Coil consumption -> Massive amounts of charge drawn from capacitor, coil never discharges.
2. Supercapacitor output = Coil consumption -> Normal? amounts of charge drawn from capacitor, coil discharges properly.
3. Supercapacitor output > Coil consumption -> Same as situation 2, but slightly more charge is drawn.

**Test Submarine:** [DischargeCoilTest.zip](https://github.com/Regalis11/Barotrauma/files/9995165/DischargeCoilTest.zip)

### Reproduction steps

1. Open test sub in the sub editor (saved as an Outpost).
2. Go into testing mode.
3. Press the 3 buttons on the submarine.
4. Observe how each supercapacitor's charge value differs.

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-05-22 07:36
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/05a586d3e5d0dcf69a20bfc526c8f860dc9b6e8c

**Comment by AdamH-Daedalic** [comment] 2023-06-12 12:35
Tested against https://github.com/Regalis11/Barotrauma-development/pull/4266.

When testing this fix across the vanilla submarines, it seems that the EDC will not discharge if the supercapacitor output is anything less than 60x the EDC power consumption. The testfile provided showcases this issue, with the centre EDC setup being with equal values of output and consumption, which should cause the EDC to discharge, however it does not, and only drain power from the superconductor.

**Comment by Regalis11** [comment] 2023-06-12 15:49
Took a look at this, and even though unintuitive, that behavior seems to be intentional. The power output value is measured in "units" per second, but the EDC needs an "instantaneous" one-frame power surge, and since the game runs at a fixed rate of 60 ticks per second, that means the power output value configured for the supercapacitor needs to be at least 60 times the power consumption of the EDC.

I also tested a similar setup with a coilgun, and it seems the same "x60 rule" applies, and probably always has, applied there. It's also worth noting that the default maximum output of a supercapacitor is 20,000,000, so a player shouldn't run into this problem unless they're doing something very unusual with the supercapacitors.

So I think we could consider that a feature, not a bug. :)

**Closed** 2023-06-13 14:30 UTC
Labels: Bug, Code
