### ISSUE TITLE
QoL and wiring feature requests + Various minor bugs

### ISSUE THREAD

**Issue by HyperB1** [Regalis11/Barotrauma#12580] opened 2023-08-29 11:30 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

## BUGS:

1. Lighting sprites broken on various items. Prevalence: The bug has been present since 1.0
_Image 1 - bugged_
![20230622212013_1](https://github.com/Regalis11/Barotrauma/assets/137433177/49952a2a-79e3-4a7d-9731-9bb96adc4179)
_Image 2 - as it should be_
![20230622211944_1](https://github.com/Regalis11/Barotrauma/assets/137433177/9f067fb5-fec3-4d29-bc67-932614c4a9f8)
The problem lies in the fact that the light is not rendered as light, but rather as a texture, which perceives absence of colour as blackness, and not the actual absence of light. And besides, It is a little bit misaligned.

2. Character falls down during interaction with various stationary items' UI (opening wiring panel does not trigger this bug) without pressing any keys after sitting on a chair/lying on a bed. Even clipping through objects when falling sometimes. Prevalence: Happens almost every time
![20230827222436_1](https://github.com/Regalis11/Barotrauma/assets/137433177/d40fde72-7aad-45ed-a737-daf2cfc44f61)
_Reproduction steps:_
- _Start a multiplayer mission_
- _Find a bed to lay on or a chair to sit in, then do it._
- _Get up from the chair/bed_
- _Right after you stand up from the chair/bed try to interact with installations on the spot (Trying to interact with things far away from the bed/chair causes the bug to not appear.)_
- _Watch your character instantly ragdoll_

## FEATURE REQUESTS

1. Set_Expression connector for the RegEx find component.

2. Set_False_Output connector for the Signal check component.

3. Max_Power_Out connector for the reactor (because trying to automatically set the reactor's Max power output when it changes by calculating it can make it very unprecise sometimes).

4. Setting the battery charge rate by components (automatically) changes the charge rate in increments of 5 rather than 10 to avoid significant power spikes and fluctuations.

5. Connector that outputs the amount of objects detected in the range of the motion detector.

6. Option to change the max string length of the Terminal in the sub editor. (Currently max string length of the Terminal sits at 200 characters by default and cannot be changed)

7. Vent output multiplier (When trying to implement it myself I encountered a ton of bugs with this one, this feature may be difficult to code).

### Reproduction steps

_**Reproduction steps are already listed above**_

## Bug №1
The bug can be observed at any instant in the game. It is particularly noticeable on the Workbench lamp item

## Bug №2
- Start a multiplayer mission
- Find a bed to lay on or a chair to sit in, then do it.
- Get up from the chair/bed
- Right after you stand up from the chair/bed try to interact with installations on the spot (Trying to interact with things far away from the bed/chair causes the bug to not appear.)
- Watch your character instantly ragdoll

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-08-29 14:07
Thank you for the report!

The issue tracker is intended for bug reports, feature requests should be posted in the [Discussions](https://github.com/Regalis11/Barotrauma/discussions).

But to comment on the bugs mentioned here:

1. The light has actually been intentionally configured like that in this case. Rendering it both additively and using alpha blending makes it stand out more than just rendering it additively.

2. I unfortunately wasn't able to reproduce the issue with the beds and chairs. Selecting a device while sitting in a chair or laying in a bed doesn't seem to cause any issues at my end, so I suppose the bug requires some more specific circumstances to occur:

https://github.com/Regalis11/Barotrauma/assets/14351070/fdfc02b2-4be2-4045-9cb1-a5e5e4547379

**Comment by HyperB1** [comment] 2023-08-30 17:05
Thank you very much for your answer. I apologise for the misunderstanding.
_Correction:_ In order for the bug to occur you need to interact with the installation right **after** you get up from a chair or a bed

**Comment by Regalis11** [comment] 2023-09-25 11:31
Potentially related ticket: https://github.com/Regalis11/Barotrauma/issues/10393

**Comment by Jasontti** [comment] 2023-10-02 07:17
Tested.
Ragdolling bug is easily reproducible in 1.0.21.0 stable, with steps above or other way around in https://github.com/Regalis11/Barotrauma/issues/10393 SP or MP
![image](https://github.com/Regalis11/Barotrauma/assets/8488224/168a5e17-8288-4724-96a5-ae48dcdf4c05)

Could not reproduce in 1.1.14.0 [devbuild](https://github.com/Regalis11/Barotrauma-development/commit/2590e20b300831fa575c7dcfff9f4c35757a3dbc) anymore.
New interacting with devices animation interrupts sitting down animation, so that it doesn't happen.

Closing ticket

**Closed by Jasontti** 2023-10-02 07:17 UTC
Labels: Bug, Need more info, Code
