### ISSUE TITLE
Cannot dock or enter levels in singleplayer campaign

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5387] opened 2021-03-30 16:09 UTC
- [yes ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
An error pops out when you try to dock to an outpost or enter a natural formation the "Intended" way, but if you try to enter the outpost by driving to it, and entering, this won't happen and no error will pop out.
You can also evade the error on natural formations by not using the first map that pops out, but instead pressing the "enter (name)" button manually
(Sometimes the workarounds i added don't work, depending on the level)

**Version**
v.0.1300.0.4

**Additional information**
I don't know if this is save specific or not so i will attach a save file where the error is happening.
[FUNKING.zip](https://github.com/Regalis11/Barotrauma/files/6230440/FUNKING.zip)

**Comment by Regalis11** [comment] 2021-03-31 07:55
I wasn't able to reproduce this by docking to the outpost, but entering the natural formation displayed the same error as in https://github.com/Regalis11/Barotrauma/issues/5390. If that was the error you got, this should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/bd952549f4a352c73f4a595ab451dace2809d021

**Comment by Rokvach** [comment] 2021-03-31 22:32
Tested, wasn't able to reproduce. Seems to be working correctly. Closing.

**Closed by Rokvach** 2021-03-31 22:32 UTC
Labels: Bug, Code, High prio
