### ISSUE TITLE
[AI] AI doesn't navigate to a point from which it has LoS on a hull breach

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#6460] opened 2021-08-23 10:33 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
As you can see here, AI won't repair the breach because another piece of hull is blocking it.
AI doesn't have line of sight on the breach.
[https://youtu.be/n6t5M78Lsag](https://youtu.be/n6t5M78Lsag)

**Steps To Reproduce**
AI can repair it from the ladder, so it's not always reproducible.

**Version**
v0.14.6.0

**Comment by itchyOwl** [comment] 2021-09-03 07:37
Unlike for many other objectives, for fixing leaks we don't require the target to be visible to the character, because it often isn't. And the welding torch can repair through walls.

That's a custom submarine, apparently based on Humpback. I couldn't reproduce the issue on Humpback. We had a similar issue on it, where the bots were unable to repair the upper hatch. Adding a couple of waypoints fixed the issue, so that the bots can use the platform to stand on (in the next update, the generator should create them for you automatically). When I try to repro the issue on Humpback, the bots use those waypoints and the platform, which helps them to fix any leaks there too.
![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/e64ceb8a-6f90-4ba6-adac-a1799c4f680a)

Closing the ticket, as it's unreproducable. Please test adding the waypoints and if it doesn't fix the issue, report back and link the submarine file here, so I can take a look.

**Closed by itchyOwl** 2021-09-03 07:37 UTC
Labels: Bug, Code
