### ISSUE TITLE
Bots not changing ammo

### ISSUE THREAD

**Issue by Bozhdynsky** [Regalis11/Barotrauma#4040] opened 2020-10-08 18:02 UTC
**Description**
Sometimes bots will not change ammo and will stand there with an empty box in hand and still by a periscope. This one is a custom sub but I had the same experience in a Dugong under 0.10.600. (From the screenshot the guy i'm controlling did exactly the same thing as the bot next to him.) Armoury was stocked with spare ammo. I think each time this bug materialised was around the Watcher encounter, but not sure.

**Steps To Reproduce**
Empty some ammo boxes.

**Version**
v0.10.601.0 (Unstable)

**Additional information**
![20201008194239_1](https://user-images.githubusercontent.com/72402600/95496309-ebc67000-09a0-11eb-801d-25f8a21327f2.jpg)

**Comment by Kaillera** [comment] 2020-10-08 21:20
I can confirm I'm seeing the same problem in my game.

**Comment by itchyOwl** [comment] 2020-10-16 17:42
It would help greatly if you could reproduce the issue with some steps. From the description, I can collect that it might be related to Watcher and happens at least in Dugong. Does it happen always or just sometimes? Is there any specific things you do or encounter in the game before it happens?

**Comment by Bozhdynsky** [comment] 2020-10-16 18:04
Hi, all I remember is that Watcher takes a bit of an ammo to bring down. So when encountered, and when ammo runs low, bots will not change to new boxes. They seem to be stuck mid-way. They stand there with an empty box in hand and still peer through the scope. The sub does not matter, as the screenshot above is from a custom sub.

**Comment by itchyOwl** [comment] 2020-11-09 14:26
Fixed in Regalis11/Barotrauma-development@e5e2f69.

I'm pretty sure that tickets #3808 #4106 #4044 are all about the same issue: the bots failed to make the difference between empty and non-empty items. This was the case with fuel rods and I'm pretty sure that it's the same thing with the coilgun ammo too. It's basically the same code, so fixing one should fix the other.

Steps to repro:
1) Make the fuel rods/ammo boxes empty (easy in the sub editor)
2) Insert the empty item in the reactor/turret loader
3) Order a bot to operate the item
4) See how the bot gets stuck in the "Get Item" state. In a debug build the console floods "Removing SUBobjective get item of contain item, because it is completed"

So basically a part of the code told the bot to use only items that have some juice in them, but another part of the code the bots were told that empty items are good enough (just because the default value was 0 and not 1).

**Comment by Xeavas** [comment] 2020-11-11 16:23
[0.1100.0.5] - Unable to replicate 👍

**Comment by Rokvach** [comment] 2020-11-11 16:28
Closing.

**Closed by Rokvach** 2020-11-11 16:28 UTC
Labels: Bug, Code
