### ISSUE TITLE
Crashes during mechanic training 

### ISSUE THREAD

**Issue by evenbaro** [Regalis11/Barotrauma#2807] opened 2020-05-11 16:17 UTC
Barotrauma Client crash report (generated on 11.05.2020 17:07:54)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

023CCD07C102F6331CAD29D2EADB01E0

Game version 0.9.9.1 (ReleaseWindows, branch release, revision 1968ab79f)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: nLoZLLtza
Loaded submarine: Dugong_Tutorial (E327F30A352B4F0D1A97A7F95059767F)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.18362.0 64 bit
    GPU name: Intel(R) UHD Graphics 630
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,7777778}
    GPU status: Normal

Exception: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: GPU-enhetsforekomsten er blitt avbrutt. Bruk GetDeviceRemovedReason for å avgjøre hvilken handling som er nødvendig.
 (SharpDX.SharpDXException)
Device removed reason: HRESULT = 0x887A0006
Target site: Void CheckError()
Stack trace: 
   at SharpDX.Result.CheckError()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent()
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Barotrauma.Program.Main(String[] args)

Last debug messages:
[11.05.2020 16:56:47] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[11.05.2020 16:56:47] Content package load order: Vanilla 0.9
[11.05.2020 16:56:47] Content package load order: Vanilla 0.9
[11.05.2020 16:56:45] Attempting to open ALC device "OpenAL Soft"
[11.05.2020 16:56:44] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[11.05.2020 16:56:44] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean

**Comment by Miffsky66** [comment] 2020-05-11 19:04
I have had the same problem.

**Comment by Regalis11** [comment] 2020-05-12 07:49
If the hardware info in the report is correct, you're using an integrated graphics card which probably doesn't meet the minimum requirements to run the game (I suspect it doesn't have enough video memory). We will be doing some memory optimization in future patches, but I'm afraid we cannot promise you will be able to play the game with such a low-end GPU.

This also seems to be a duplicate of #1833

**Closed by Regalis11** 2020-05-12 07:49 UTC

**Comment by evenbaro** [comment] 2020-05-12 08:43
@Regalis11 

I dont think it is low-end: 

MSI GS65 Stealth Thin 8RE-051US (GTX 1060) Laptop 
Processor. Intel Core i7-8750H.
Graphics adapter. NVIDIA GeForce GTX 1060 Mobile - 6144 MB, Core: 1404 - 1670 MHz, Memory: 8000 MHz, GDDR5, 23.21.13.9094 - nVIDIA ForceWare 390.94.
Memory. 16384 MB.

**Comment by evenbaro** [comment] 2020-05-12 12:41
Barotrauma Client crash report (generated on 12.05.2020 13:39:50)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


023CCD07C102F6331CAD29D2EADB01E0


Game version 0.9.9.1 (ReleaseWindows, branch release, revision 1968ab79f)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: nLoZLLtza
Loaded submarine: Dugong_Tutorial (E327F30A352B4F0D1A97A7F95059767F)
Selected screen: Barotrauma.GameScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.18362.0 64 bit
    GPU name: Intel(R) UHD Graphics 630
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,7777778}
    GPU status: Normal


Exception: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: GPU-enhetsforekomsten er blitt avbrutt. Bruk GetDeviceRemovedReason for å avgjøre hvilken handling som er nødvendig.
 (SharpDX.SharpDXException)
Device removed reason: HRESULT = 0x887A0006
Target site: Void CheckError()
Stack trace: 
   at SharpDX.Result.CheckError()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent()
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Barotrauma.Program.Main(String[] args)


Last debug messages:
[12.05.2020 13:24:24] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[12.05.2020 13:24:24] Content package load order: Vanilla 0.9
[12.05.2020 13:24:24] Content package load order: Vanilla 0.9
[12.05.2020 13:24:22] Attempting to open ALC device "OpenAL Soft"
[12.05.2020 13:24:21] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[12.05.2020 13:24:21] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean

**Comment by Regalis11** [comment] 2020-05-12 14:16
Thank you for the clarification! The crash report listed the GPU as "Intel(R) UHD Graphics 630" so I assumed you were using an integrated GPU. It may be that the "DXGI_ERROR_DEVICE_REMOVED" error caused the game to fall back from your proper GPU to the integrated one.

I'll still keep this ticket closed though as it's the same error message as in #1833. I'm sorry for not being able to offer you any help or workarounds to this issue at the moment, we're looking into it and trying to get it sorted out for the next patch.

**Comment by evenbaro** [comment] 2020-05-12 16:01
Barotrauma Client crash report (generated on 12.05.2020 16:59:28)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


023CCD07C102F6331CAD29D2EADB01E0


Game version 0.9.9.1 (ReleaseWindows, branch release, revision 1968ab79f)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: nLoZLLtza
Loaded submarine: Dugong_Tutorial (E327F30A352B4F0D1A97A7F95059767F)
Selected screen: Barotrauma.GameScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.18362.0 64 bit
    GPU name: Intel(R) UHD Graphics 630
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,7777778}
    GPU status: Normal


Exception: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: GPU-enhetsforekomsten er blitt avbrutt. Bruk GetDeviceRemovedReason for å avgjøre hvilken handling som er nødvendig.
 (SharpDX.SharpDXException)
Device removed reason: HRESULT = 0x887A0006
Target site: Void CheckError()
Stack trace: 
   at SharpDX.Result.CheckError()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent()
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Barotrauma.Program.Main(String[] args)


Last debug messages:
[12.05.2020 14:27:16] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[12.05.2020 14:27:16] Content package load order: Vanilla 0.9
[12.05.2020 14:27:16] Content package load order: Vanilla 0.9
[12.05.2020 14:27:14] Attempting to open ALC device "OpenAL Soft"
[12.05.2020 14:27:14] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[12.05.2020 14:27:14] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean

**Comment by evenbaro** [comment] 2020-05-14 13:24
@Regalis11 So I found a fix for the problem. I used "Nvidia Control panel" to force my computer to use the dedicated graphic card, instead of Integrated GPU. 

Played throug all the trainings without issues.

However, now I cant even start a game without the game crashing. See report #2829
