### ISSUE TITLE
Door cant be interacted in test mode on sub editor

### ISSUE THREAD

**Issue by SenhorPatolino** [Regalis11/Barotrauma#2591] opened 2020-04-09 17:57 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Can't destroy with plasma cutter, can't open, can't interact with E, not even the UI appear.

**Version**
0.9.9.0 Unstable on Windows.

**Comment by Regalis11** [comment] 2020-04-14 13:44
Unfortunately we were not able to reproduce this. Did it happen in some specific sub, or does it happen consistently in all subs?

**Comment by SenhorPatolino** [comment] 2020-04-14 19:49
It happened in a specific sub, i'll test if it happens in another sub

**Comment by Regalis11** [comment] 2020-04-20 07:57
We still haven't found a way to repro this (might've been some issue in the sub or something we've inadvertently fixed in the newer builds). Closing for now, but we can reopen the ticket if the issue resurfaces.

**Closed by Regalis11** 2020-04-20 07:57 UTC
Labels: Bug, Code, Need more info
