### ISSUE TITLE
Camel bad AI pathing bug and fix...

### ISSUE THREAD

**Issue by unites** [Regalis11/Barotrauma#12133] opened 2023-06-08 00:22 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The Camel has bad AI pathing in it's default .sub file.  AI  crew gest stuck on ladder and become un-usable. 

### Reproduction steps

Take a crew of AI out to sea in the Camel, take on water and have them do their thing.  Try to fix leaks and use the Turrets.  They will get stuck coming up the ladder from mid ship to command. 

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
This can all be fixed if you adjust the AI path.  Dev's should do this in a future patch...
https://i.imgur.com/NxSUIgT.png
The above image shows the problem, it just needs to be shifted in line with the ladder.  The node or point ID is 334 I believe
```

**Comment by itchyOwl** [comment] 2023-06-08 07:36
Closing as a duplicate of #11984, which is included in the upcoming patch (and live in unstable) Adjusting that waypoint helps, but shouldn't be required after the pathing fixes. Sorry for the inconvience, but the navigation issues on ladders has turned out to be a bit of wormcan to fix. Hence, the logic was heavily refactred. Hopefully the issues are gone now. However, there can still be issues due to incorrect waypoint positioning. If you encounter any issues, please report them here. Thank you.

**Closed by itchyOwl** 2023-06-08 07:36 UTC
Labels: Duplicate
