### ISSUE TITLE
[Unstable] Server Browser menu crash

### ISSUE THREAD

**Issue by evilfactory** [Regalis11/Barotrauma#9729] opened 2022-08-19 17:54 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Opening the Server Browser seems to cause a crash.

### Reproduction steps

Open the Server Browser via the main menu

### Bug prevalence

Happens every time I play

### Version

Other

### -

v0.19.1.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 19/08/2022 14:50:06)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


97539E10A99B17CB3CB1294FADA2E8AE


Game version 0.19.1.0 (UnstableWindows, branch dev, revision 445f6a88d6)
Graphics mode: 1280x1024 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla, Lua For Barotrauma, LuaExamples
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.ServerListScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: AMD Radeon(TM) Vega 8 Graphics
    Display mode: {Width:1280 Height:1024 Format:Color AspectRatio:1,25}
    GPU status: Normal


Exception: The attempted operation is not supported for the type of object referenced. (System.Net.Sockets.SocketException)
Target site: Int64 get_Address()
Stack trace: 
   at System.Net.IPAddress.get_Address()
   at Steamworks.Utility.IpToInt32(IPAddress ipAddress) in <DEV>\Libraries\Facepunch.Steamworks\Utility\Utility.cs:line 39
   at Steamworks.SteamMatchmakingPingResponse.HQueryPing(IPAddress ip, Int32 port) in <DEV>\Libraries\Facepunch.Steamworks\Steamworks.NET\SteamMatchmakingResponses.cs:line 88
   at Barotrauma.Networking.ServerInfo.QueryLiveInfo(Action`1 onServerRulesReceived, Action`1 onQueryDone) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\ServerInfo.cs:line 441
   at Barotrauma.ServerListScreen.UpdateInfoQueries() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\ServerListScreen.cs:line 1103
   at Barotrauma.ServerListScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\ServerListScreen.cs:line 993
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 853
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59


Last debug messages:
[19/08/2022 14:50:05] SteamRelayNetworkStatus:                      Avail: Current
 PingMeasurementInProgress: 1
        AvailNetworkConfig: Current
             AvailAnyRelay: Current
                  DebugMsg: System.Byte[]
[19/08/2022 14:48:35] freecam
[19/08/2022 14:48:05] spawnitem "Frag Grenade" inventory 4
[19/08/2022 14:47:01] spawnitem "Frag Grenade" inventory 4
[19/08/2022 14:45:49] fixhulls
[19/08/2022 14:45:48] fixitems
[19/08/2022 14:45:44] revive
[19/08/2022 14:45:03] revive
[19/08/2022 14:44:25] Disabled godmode on Lelah Bonham
[19/08/2022 14:44:25] godmode
[19/08/2022 14:42:59] fixitems
[19/08/2022 14:41:13] revive
[19/08/2022 14:41:11] Enabled godmode on Lelah Bonham
[19/08/2022 14:41:11] godmode
[19/08/2022 14:37:11] spawnitem screwdriver inventory
[19/08/2022 14:37:10] spawnitem screwdriver inventory
[19/08/2022 14:36:32] teleport
[19/08/2022 14:36:31] teleport
[19/08/2022 14:32:24] spawnitem "Fuel Rod" inventory
[19/08/2022 14:26:36] freecam
[19/08/2022 14:26:14] freecam
[19/08/2022 14:26:13] Lighting enabled
[19/08/2022 14:26:13] lighting
[19/08/2022 14:26:12] Lighting disabled
[19/08/2022 14:26:12] lighting
[19/08/2022 14:24:08] revive
[19/08/2022 14:24:07] teleport
[19/08/2022 14:24:05] teleport
[19/08/2022 14:24:03] revive
[19/08/2022 14:24:01] fixhulls
[19/08/2022 14:24:00] fixitems
[19/08/2022 14:23:59] revive
[19/08/2022 14:23:56] teleport
[19/08/2022 14:23:55] Lighting disabled
[19/08/2022 14:23:55] lighting
[19/08/2022 14:23:52] teleport
[19/08/2022 14:23:50] teleport
[19/08/2022 14:23:48] teleport
[19/08/2022 14:23:46] teleport
[19/08/2022 14:23:45] teleport
[19/08/2022 14:17:58] spawn crawler cursor
[19/08/2022 14:17:57] spawn crawler cursor
[19/08/2022 14:17:57] spawn crawler cursor
[19/08/2022 14:17:57] spawn crawler cursor
[19/08/2022 14:17:57] spawn crawler cursor
[19/08/2022 14:17:57] spawn crawler cursor
[19/08/2022 14:17:56] spawn crawler cursor
[19/08/2022 14:17:56] spawn crawler cursor
[19/08/2022 14:17:56] spawn crawler cursor
[19/08/2022 14:17:56] spawn crawler cursor
[19/08/2022 14:17:56] spawn crawler cursor
[19/08/2022 14:17:55] spawn crawler cursor
[19/08/2022 14:17:55] spawn crawler cursor
[19/08/2022 14:17:55] spawn crawler cursor
[19/08/2022 14:17:55] spawn crawler cursor
[19/08/2022 14:17:55] spawn crawler cursor
[19/08/2022 14:14:50] spawn Hammerhead cursor
[19/08/2022 14:14:37] spawn crawler cursor
[19/08/2022 14:14:21] spawn crawler cursor
[19/08/2022 14:10:40] WARNING: Tried to restore enabled packages multiple times/without performing a backup
[19/08/2022 14:10:40] WARNING: Tried to restore enabled packages multiple times/without performing a backup
[19/08/2022 14:10:09] Server command: teleport
[19/08/2022 14:10:09] teleport
[19/08/2022 14:10:08] Server command: teleport
[19/08/2022 14:10:08] teleport
[19/08/2022 14:10:08] Server command: teleport
[19/08/2022 14:10:08] teleport
[19/08/2022 14:10:07] Server command: teleport
[19/08/2022 14:10:07] teleport
[19/08/2022 14:10:07] Server command: teleport
[19/08/2022 14:10:07] teleport
[19/08/2022 14:10:06] Server command: teleport
[19/08/2022 14:10:06] teleport
[19/08/2022 14:10:06] Server command: teleport
[19/08/2022 14:10:06] teleport
[19/08/2022 14:10:06] Server command: teleport
[19/08/2022 14:10:06] teleport
[19/08/2022 14:10:02] Server command: teleport
[19/08/2022 14:10:02] teleport
[19/08/2022 14:10:01] Server command: teleport
[19/08/2022 14:10:01] teleport
[19/08/2022 14:09:58] Server command: teleport
[19/08/2022 14:09:58] teleport
[19/08/2022 14:09:57] Server command: teleport
[19/08/2022 14:09:57] teleport
[19/08/2022 14:09:57] Server command: teleport
[19/08/2022 14:09:57] teleport
[19/08/2022 14:09:56] Server command: teleport
[19/08/2022 14:09:56] teleport
[19/08/2022 14:09:56] Server command: teleport
[19/08/2022 14:09:56] teleport
[19/08/2022 14:09:55] Server command: teleport
[19/08/2022 14:09:55] teleport
[19/08/2022 14:09:55] Server command: teleport
[19/08/2022 14:09:55] teleport
[19/08/2022 14:09:54] Server command: teleport
[19/08/2022 14:09:54] teleport
[19/08/2022 14:09:53] Server command: teleport
[19/08/2022 14:09:53] teleport
[19/08/2022 14:09:51] Server command: teleport
[19/08/2022 14:09:51] teleport
[19/08/2022 14:09:50] Server command: teleport
[19/08/2022 14:09:50] teleport
[19/08/2022 14:09:28] Server command: teleport
[19/08/2022 14:09:28] teleport
[19/08/2022 14:09:28] Server command: teleport
[19/08/2022 14:09:28] teleport
[19/08/2022 14:09:27] Server command: teleport
[19/08/2022 14:09:27] teleport
[19/08/2022 14:09:27] Server command: teleport
[19/08/2022 14:09:27] teleport
[19/08/2022 14:09:27] Server command: teleport
[19/08/2022 14:09:27] teleport
[19/08/2022 14:09:26] Server command: teleport
[19/08/2022 14:09:26] teleport
[19/08/2022 14:09:26] Server command: teleport
[19/08/2022 14:09:26] teleport
[19/08/2022 14:09:26] Server command: teleport
[19/08/2022 14:09:26] teleport
[19/08/2022 14:09:25] Server command: teleport
[19/08/2022 14:09:25] teleport
[19/08/2022 14:09:25] Server command: teleport
[19/08/2022 14:09:25] teleport
[19/08/2022 14:09:25] Server command: teleport
[19/08/2022 14:09:25] teleport
[19/08/2022 14:09:25] Server command: teleport
[19/08/2022 14:09:25] teleport
[19/08/2022 14:09:24] Server command: teleport
[19/08/2022 14:09:24] teleport
[19/08/2022 14:09:24] Server command: teleport
[19/08/2022 14:09:24] teleport
[19/08/2022 14:09:24] Server command: teleport
[19/08/2022 14:09:24] teleport
[19/08/2022 14:09:24] Server command: teleport
[19/08/2022 14:09:24] teleport
[19/08/2022 14:09:23] Server command: teleport
[19/08/2022 14:09:23] teleport
[19/08/2022 14:09:23] Server command: teleport
[19/08/2022 14:09:23] teleport
[19/08/2022 14:09:23] Server command: teleport
[19/08/2022 14:09:23] teleport
[19/08/2022 14:09:22] Server command: teleport
[19/08/2022 14:09:22] teleport
[19/08/2022 14:09:22] Server command: teleport
[19/08/2022 14:09:22] teleport
[19/08/2022 14:09:22] Server command: teleport
[19/08/2022 14:09:22] teleport
[19/08/2022 14:09:22] Server command: teleport
[19/08/2022 14:09:22] teleport
[19/08/2022 14:09:21] Server command: teleport
[19/08/2022 14:09:21] teleport
[19/08/2022 14:09:21] Server command: teleport
[19/08/2022 14:09:21] teleport
[19/08/2022 14:09:21] Server command: teleport
[19/08/2022 14:09:21] teleport
[19/08/2022 14:09:20] Server command: teleport
[19/08/2022 14:09:20] teleport
[19/08/2022 14:09:20] Server command: teleport
[19/08/2022 14:09:20] teleport
[19/08/2022 14:09:20] Server command: teleport
[19/08/2022 14:09:20] teleport
[19/08/2022 14:09:20] Server command: teleport
[19/08/2022 14:09:20] teleport
[19/08/2022 14:09:19] Server command: teleport
[19/08/2022 14:09:19] teleport
[19/08/2022 14:09:19] Server command: teleport
[19/08/2022 14:09:19] teleport
[19/08/2022 14:09:19] Server command: teleport
[19/08/2022 14:09:19] teleport
[19/08/2022 14:09:18] Server command: teleport
[19/08/2022 14:09:18] teleport
[19/08/2022 14:09:18] Server command: teleport
[19/08/2022 14:09:18] teleport
[19/08/2022 14:09:17] Server command: teleport
[19/08/2022 14:09:17] teleport
[19/08/2022 14:09:16] Server command: fixhulls
[19/08/2022 14:09:16] fixhulls
[19/08/2022 14:09:15] Server command: fixitems
[19/08/2022 14:09:15] fixitems
[19/08/2022 14:09:01] Server command: spawnitem "Compound N" inventory
[19/08/2022 14:09:01] spawnitem "Compound N" inventory
[19/08/2022 14:09:01] Server command: spawnitem "Compound N" inventory
[19/08/2022 14:09:01] spawnitem "Compound N" inventory
[19/08/2022 14:09:01] Server command: spawnitem "Compound N" inventory
[19/08/2022 14:09:01] spawnitem "Compound N" inventory
[19/08/2022 14:09:01] Server command: spawnitem "Compound N" inventory
[19/08/2022 14:09:01] spawnitem "Compound N" inventory
[19/08/2022 14:08:56] Server command: fixhulls
[19/08/2022 14:08:56] fixhulls
[19/08/2022 14:08:55] Server command: fixitems
[19/08/2022 14:08:55] fixitems
[19/08/2022 14:08:49] Desmond Sutton
[19/08/2022 14:08:49] Server command: revive
[19/08/2022 14:08:49] revive
[19/08/2022 14:08:35] Server command: spawnitem "Frag Grenade" inventory 8
[19/08/2022 14:08:35] spawnitem "Frag Grenade" inventory 8
[19/08/2022 14:08:33] Performance statistics disabled
[19/08/2022 14:08:33] showperf
[19/08/2022 14:08:32] Performance statistics enabled
[19/08/2022 14:08:32] showperf
[19/08/2022 14:08:31] Server command: spawnitem "Frag Grenade" inventory
[19/08/2022 14:08:31] spawnitem "Frag Grenade" inventory
[19/08/2022 14:08:26] Server command: enablecheats
[19/08/2022 14:08:26] enablecheats
[19/08/2022 14:08:26] Server running slowly (58 updates/s)!
[19/08/2022 14:07:44] Server command: teleport
[19/08/2022 14:07:44] teleport
[19/08/2022 14:07:43] Server command: teleport
[19/08/2022 14:07:43] teleport
[19/08/2022 14:07:42] Server command: teleport
[19/08/2022 14:07:42] teleport
[19/08/2022 14:07:42] Server command: teleport
[19/08/2022 14:07:42] teleport
[19/08/2022 14:07:41] Server command: teleport
[19/08/2022 14:07:41] teleport
[19/08/2022 14:07:41] Server command: teleport
[19/08/2022 14:07:41] teleport
[19/08/2022 14:07:40] Server command: teleport
[19/08/2022 14:07:40] teleport
[19/08/2022 14:07:29] Server command: teleport
[19/08/2022 14:07:29] teleport
[19/08/2022 14:07:28] Server command: teleport
[19/08/2022 14:07:28] teleport
[19/08/2022 14:07:28] Server command: teleport
[19/08/2022 14:07:28] teleport
[19/08/2022 14:07:27] Server command: teleport
[19/08/2022 14:07:27] teleport
[19/08/2022 14:07:27] Server command: teleport
[19/08/2022 14:07:27] teleport
[19/08/2022 14:07:26] Server command: teleport
[19/08/2022 14:07:26] teleport
[19/08/2022 14:07:26] Server command: teleport
[19/08/2022 14:07:26] teleport
[19/08/2022 14:07:25] Server command: teleport
[19/08/2022 14:07:25] teleport
[19/08/2022 14:07:25] Server command: teleport
[19/08/2022 14:07:25] teleport
[19/08/2022 14:07:24] Server command: teleport
[19/08/2022 14:07:24] teleport
[19/08/2022 14:07:24] Server command: teleport
[19/08/2022 14:07:24] teleport
[19/08/2022 14:07:21] Server command: enablecheats
[19/08/2022 14:07:21] enablecheats
[19/08/2022 14:06:57] Desmond Sutton
[19/08/2022 14:06:57] Server running slowly (57 updates/s)!
[19/08/2022 14:06:53] Received STARTGAMEFINALIZE packet. Round init status: Started
[19/08/2022 14:06:53]  -3: WaitForPingDataAsync (owner), RanToCompletion
[19/08/2022 14:06:53]  -2: WaitForPingDataAsync (owner), RanToCompletion
[19/08/2022 14:06:53]  -1: WaitForPingDataAsync (owner), RanToCompletion
[19/08/2022 14:06:53]  -0: WaitForPingDataAsync (owner), RanToCompletion
[19/08/2022 14:06:53] Task count: 4
[19/08/2022 14:06:53] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[19/08/2022 14:06:48] Generating an outpost for the start of the level... (Location: Dolgovskoy Outpost, level type: Outpost)
[19/08/2022 14:06:47] Level identifier: outpostlevel
[19/08/2022 14:04:57] Lobby created!
[19/08/2022 14:03:13] Error in <ServerInfo ServerName="Galilean Servers | Traitor Mod v2.2" ServerMessage="Discord Server:https://discord.gg/nrpB4DeVYU&#xD;&#xA;&#xA;WE HAVE MIDROUND JOIN! Jump right into the action, no more waiting 30 minutes in spectator for the round to end.&#xA;&#xA;Rule 0: Use Common Sense&#xA;&#xD;&#xA;Rule 1: No griefing.&#xD;&#xD;&#xA;Rule 1.2: Captains and Security cannot punish Crew members/Clowns unless they are disobeying achievable, reasonable orders or they are a clear threat(explosives, weapons, poisons, and ect) or have a good reason. Security is ALWAYS loyal to Captain! Captain and Security can NOT join a mutiny.&#xD;&#xA;Rule 1.3: You may fight back if is in self defence the only exceptions to this is the use of husk eggs and explosives.&#xD;&#xA;Rule 1.4: You can use explosive to dispatch enemies as long as you kill more enemies then innocent crew.&#xD;&#xA;Rule 1.5: Metagaming is not allowed.&#xD;&#xA;Rule 1.6: Death squad/Red Squad members cannot kill each other.&#xD;&#xA;&#xD;&#xA;Rule 2: Mutiny needs at least 3 Members to declare.&#xD;&#xA;Rule 2.1: Mutiny needs to be announced in the local (!!text!!) chat before any hostile action.&#xD;&#xA;&#xD;&#xA;Rule 3.1: When killing a suspected traitorous crewmember then any method to kill them is allowed except husk eggs (Traitors and clowns are exempt from this rule)&#xD;&#xA;Rule 3.2: Clowns are to be treated as normal crew members unless they type the !clown command (in local !!text!! chat), then can be KOS'd on sight&#xD;&#xA;Rule 3.3: If you craft a clown diving mask whilst being a clown, you must wear your clown diving mask&#xD;&#xA;&#xD;&#xD;&#xA;Rule 4: Players behaving in a toxic manner will result kick or ban. Please be considerate of what you say to other players and how you choose to speak.&#xA;Rule 4.1: Going clown multiple times in a relatively short amount of time is toxic&#xD;&#xA;Rule 4.2: No racism, Slurs, Talks of religion, Sexual harrassment, or Politics.&#xD;&#xA;&#xD;&#xA;Rule 5: Admins/Moderators are able to issue orders that you must comply. Failing to do so may result a kick or ban." IP="89.58.45.48" Port="27025" QueryPort="" GameMode="mission" GameVersion="0.18.15.0" MaxPlayers="18" PlayStyle="Casual" UsingWhiteList="False" TraitorsEnabled="Yes" SubSelectionMode="Vote" ModeSelectionMode="Manual" VoipEnabled="False" HasPassword="False" />!  {Input string was not in a correct format.}
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at Barotrauma.XMLExtensions.GetAttributeInt(XElement element, String name, Int32 defaultValue) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Serialization\XMLExtensions.cs:line 337
[19/08/2022 14:03:13] Error in <ServerInfo ServerName="AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ServerMessage="aaaaaaaaaaa" IP="173.178.147.50" Port="27015" QueryPort="" GameMode="" GameVersion="0.18.12.0" MaxPlayers="10" PlayStyle="Casual" UsingWhiteList="False" TraitorsEnabled="No" SubSelectionMode="Manual" ModeSelectionMode="Manual" VoipEnabled="False" KarmaEnabled="False" FriendlyFireEnabled="False" HasPassword="True" />!  {Input string was not in a correct format.}
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at Barotrauma.XMLExtensions.GetAttributeInt(XElement element, String name, Int32 defaultValue) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Serialization\XMLExtensions.cs:line 337
[19/08/2022 14:03:13] Error in <ServerInfo ServerName="dsd server 1" ServerMessage="" IP="189.82.159.168" Port="27017" QueryPort="" GameMode="sandbox" GameVersion="0.18.12.0" MaxPlayers="10" PlayStyle="Casual" UsingWhiteList="True" TraitorsEnabled="No" SubSelectionMode="Manual" ModeSelectionMode="Manual" VoipEnabled="True" KarmaEnabled="True" FriendlyFireEnabled="True" HasPassword="False" />!  {Input string was not in a correct format.}
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at Barotrauma.XMLExtensions.GetAttributeInt(XElement element, String name, Int32 defaultValue) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Serialization\XMLExtensions.cs:line 337
[19/08/2022 14:02:33] Attempting to open ALC device "OpenAL Soft on Alto-falantes (Realtek High Definition Audio)"
[19/08/2022 14:02:31] Logged in as Evil Factory (SteamID STEAM_1:1:53859811)
```

**Comment by Regalis11** [comment] 2022-08-22 14:20
Most likely related to (or even caused by) https://github.com/regalis11/barotrauma/issues/9726

**Comment by evilfactory** [comment] 2022-09-02 18:30
Crash still happens in unstable v0.19.3.0

**Comment by NilanthAnimosus** [comment] 2022-09-05 10:43
Looked into this, appears the entry in your favoriteservers.xml where IP="localhost" is causing issues (which dates back from 0.15.13.0) when added to my own favorites. noticing that entry managed to somehow supply IpToInt32 with an address of {::1}.

```
<ServerInfo ServerName="Server" ServerMessage="" IP="localhost" Port="27015" QueryPort="27016" GameMode="" GameVersion="0.15.13.0" MaxPlayers="0" HasPassword="False" />
```
its a bit odd how its saved with a max players of 0, no listed gamemode etc.

when loading the entry, it puts together an endpointStr of "localhost:27015" in ServerInfo.cs FromXElement(XElement element)

However the Endpoint.Parse on line 344 outputs {[::1]:27015} and appears to fail to parse "localhost" to 127.0.0.1 or other IP.

**Comment by Regalis11** [comment] 2022-09-08 07:55
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/aed1c6b3cd75800af999c9cd254d2f35061647b8

**Comment by NilanthAnimosus** [comment] 2022-09-08 11:22
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/f60a2ad003be4fcf1fd3e7d6c675a3f0dbcce861

Although it no longer crashes, it doesn't seem to show any of my old favorites I tried to test with (or at least list them) offline or not. I tried removing all entries I thought could have issues and still nothing.

I then added a new entry from the serverlist, which appeared in the favorites list until I backed out and went back into the server browser then it wouldn't list it again.

**Comment by Regalis11** [comment] 2022-09-08 12:22
This seems to happen due to the FilterServers method filtering out the servers (thinking their "owner hasn't been verified"). That method and the owner verification logic have been completely rewritten in [feature/serverlist-cleanup](https://github.com/Regalis11/Barotrauma-development/tree/feature/serverlist-cleanup), and the issue doesn't seem to occur there, so let's wait until that branch is merged.

**Comment by NilanthAnimosus** [comment] 2022-09-19 10:28
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/e08ae5ae1f52f831c2483183a21f2086fa9fa051, no issues found, closing.

**Closed by NilanthAnimosus** 2022-09-19 10:28 UTC
Labels: Bug, Code, Crash, Networking, Unstable
