### ISSUE TITLE
[0.10.0 RC1] My first level had no Monster Events. Level had Scripted Events.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3258] opened 2020-07-01 04:02 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
So I bought some wire components, departed from my first outpost to receive the crates, docked to the outpost again, set up my wire components that I bought, and then departed to the Handle With Care mission. I drove half way through the level and visit the wreck, and I hadn't encountered any monster. Decided to check the event manager, and it's filled with Scripted Events (There were scripted event zone far bottom left of the level)

[Save.zip](https://github.com/Regalis11/Barotrauma/files/4855584/Save.zip)

![Capture](https://user-images.githubusercontent.com/5086682/86201623-0da49100-bb2e-11ea-8410-5c33b87a0c16.PNG)

**Version**
0.10.0 RC1

**Comment by Udrakan** [comment] 2020-07-01 11:37
Same thing happened to me with 2 levels in a campaign. 1 single crawler spawned near the end of the 2nd level.

**Comment by Regalis11** [comment] 2020-07-01 17:07
This seems to have been caused by 2 separate issues:
1. The events from the outpost level would carry over to this one. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/24b44fea8be67e394a3d47781755e48f18e6b51f
2. Levels with a difficulty of 2% or less would have no monster spawns at all, fixed in https://github.com/Regalis11/Barotrauma-development/commit/57ff98ea1477005e157318e9b4e816653b598a10

**Comment by Rokvach** [comment] 2020-07-02 12:34
No issues, closing.

**Closed by Rokvach** 2020-07-02 12:34 UTC
Labels: Bug, Code
