### ISSUE TITLE
Please make disconnected players not stunned until they are dead

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#2686] opened 2020-04-24 07:52 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

1. Players get confused why someone drops dead and feel the impulse to start CPR on them
2. Players rob the stunned player of all their belongings including ID, especially if captain/medic/security
3. I've even seen players kill the stunned player for fun by placing welding fuel mask on them

With how often players get kicked due to glitches, this feature is the worst.

**Comment by Regalis11** [comment] 2020-05-03 14:55
Duplicate of #2421

**Closed by Regalis11** 2020-05-03 14:55 UTC
Labels: Duplicate
