### ISSUE TITLE
(Unstable) Crash: System.NullReferenceException , in Sub Editor, on clicking already placed Platform

### ISSUE THREAD

**Issue by DrinkFromTheCup** [Regalis11/Barotrauma#8217] opened 2022-02-09 13:28 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
A platform which I placed quite a time ago (but still within this editing session) reacted with a crash on attempt to select it...

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void DrawSelecting(Microsoft.Xna.Framework.Graphics.SpriteBatch, Barotrauma.Camera)

**Steps To Reproduce**
Steps I took:
1. Load the game.
2. Open Sub Editor.
3. Start making a new submarine.
4. Place Platform.
5. FIddle with editor some more.
6. Click Platform
7. CRASH

**Version**
Today's Unstable

**Additional information**
(might be important) The only in-game setting I changed DURING sub edit was disabling both Fish Eye and Chromatic Aberration effects.

Crash report + sub's autosave + config files:
[Barotrauma.zip](https://github.com/Regalis11/Barotrauma/files/8033058/Barotrauma.zip)
(assuming that it made it into autosave) the Platform which crashed me is at top left corner: I've just adjusted Reactor's positioning (+ underlying Shell piece + nearest door from the left) and decided to continue aligning counter-clockwise.

**Comment by Regalis11** [comment] 2022-02-09 13:45
Duplicate of https://github.com/Regalis11/Barotrauma/issues/8160

**Closed by Regalis11** 2022-02-09 13:45 UTC
