### ISSUE TITLE
Lightsprites don't blink with cast light

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2765] opened 2020-05-03 19:21 UTC
Very straightforward issue. The light that lightcomponents have that turn on when they are on and off when they are off don't properly blink when the light has a valid blinkinterval. this can be seen most easily by going into the game, disabling lighting, and looking at a lamp or something set to blink. The lightsprite will show up when the lamp is provided power and will disappear when the lamp isn't, but it will not blink with the light correctly. It will just stay on.

**Comment by Regalis11** [comment] 2020-07-13 18:01
I wasn't able to reproduce this. Tested it by setting the blink frequency of a bunch of lamps and junction box lights to 1, and they all seem to blink normally.

I'm not sure if I'm misunderstanding the issue or if something has changed since you wrote the report, but how can you test this when the lighting is disabled? The light sprites or lights don't seem to be visible at all when lighting is disabled, as expected.

**Comment by Regalis11** [comment] 2020-08-25 09:52
No known steps to repro, closing

**Closed by Regalis11** 2020-08-25 09:52 UTC
Labels: Bug, Code, Need more info
