### ISSUE TITLE
Shuttle Fin B texture has a small piece unconnected to main texture

### ISSUE THREAD

**Issue by fr45** [Regalis11/Barotrauma#8922] opened 2022-04-22 21:26 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Shuttle Fin B texture has a small line unconnected to it.
See attached image for details.

**Steps To Reproduce**
Open submarine editor, place Shuttle Fin B, observe.

**Version**
0.17.12.0 Win10 x64

**Additional information**
![image](https://user-images.githubusercontent.com/1794500/164792970-e474c5cc-238f-4851-96b8-50d992b3dc08.png)

**Comment by Regalis11** [comment] 2022-04-27 15:59
I'm afraid I could not reproduce this. Are you using some kind of mods?
![image](https://user-images.githubusercontent.com/14351070/165561278-91249474-0b12-46fe-894e-e224459e48e6.png)

**Comment by fr45** [comment] 2022-04-27 23:09
Scale 0.600
For example, this shuttle:
https://steamcommunity.com/sharedfiles/filedetails/?id=1892506214

**Comment by Regalis11** [comment] 2022-06-08 07:51
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/270aa65e6bffdf77b31dfe31574fa43ddbc81ca8

**Comment by Rokvach** [comment] 2022-06-09 10:43
Tested, working correctly. Closing.

**Comment by Regalis11** [comment] 2022-07-18 10:13
Should be fixed properly now https://github.com/Regalis11/Barotrauma-development/commit/118e675c69b93724e1c4b6d61d02180c6e2c9307

**Comment by NilanthAnimosus** [comment] 2022-07-21 03:43
Tested on 0.19.0.0, working correctly, closing.

Note: I tried with known problem parts, submarines that had problems before when the previous fixes did not work, and even re-scaled and mirror'd entire submarines and couldn't spot any issues anymore.

**Closed by NilanthAnimosus** 2022-07-21 03:43 UTC
Labels: Bug, Code, Low prio, Unstable
