### ISSUE TITLE
Fentanyl deconstructs into Pomegrenade Fruit

### ISSUE THREAD

**Issue by Aktheon** [Regalis11/Barotrauma#3897] opened 2020-09-24 06:34 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
After last patch, decontructing Fentanyl result in 2x Pomegrenade Fruits

**Steps To Reproduce**
Deconstruct Fentanyl

**Version**
10.5.1

**Additional information**
None

**Comment by Regalis11** [comment] 2020-09-24 07:28
I wasn't able to reproduce this: fentanyl seems to deconstruct to ethanol, adrenaline and morphine as intended. Could it be that the pomegrenades ended up in the deconstructor from somewhere else?
![567fdgh](https://user-images.githubusercontent.com/14351070/94114172-a5292f80-fe50-11ea-952e-f7228430c1ff.png)

**Comment by Aktheon** [comment] 2020-09-24 08:05
yes. Fentanyl and pomerange extract lie next to each other and have same icons, hard to differ those.
Fentanyl decontruction is ok

**Comment by Regalis11** [comment] 2020-09-24 12:56
I see, in that case this is a duplicate of https://github.com/Regalis11/Barotrauma/issues/3858. Unfortunately the fix didn't make it to this release, but will be included in the next patch!

**Closed by Regalis11** 2020-09-24 12:56 UTC
Labels: Bug, Code, Need more info
