### ISSUE TITLE
Keybinds stop working

### ISSUE THREAD

**Issue by Earthspiritio** [Regalis11/Barotrauma#10533] opened 2022-11-24 22:47 UTC
### Disclaimers

- [x] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Keybinds for switching character and equipping items stopped working

### Reproduction steps

1. Start a game
2. play the game for awhile
3. switch characters every once and awhile
4. keybinds may stop working (except for movement)

### Bug prevalence

Happens every now and then

### Version

0.20.7.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-11-25 07:34
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10453

**Closed by Regalis11** 2022-11-25 07:34 UTC
