### ISSUE TITLE
Activate out on door can't be used to toggle its state. 

### ISSUE THREAD

**Issue by BlackMoons** [Regalis11/Barotrauma#12880] opened 2023-10-21 19:20 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Tried using activate out to make a door lock circuit today. Didn't work...

So I tried the simplest circuit, 'toggle while clicked' unchecked,'activate out' to signal check input, signal check output to toggle state on door, target signal 1, true output 1, false output 0

The door would open, but refuses to close when clicked a 2nd time. 

Attaching a regular button to the doors toggle state, and it works fine.

Activate out to a relays toggle state, also seems to toggle the relay just fine (relay state out to light component to check)

Activate out to delay gate to toggle state, results in... the door not opening at all and just shaking 1 second after being clicked?

Delay gate out to *another* doors toggle state, lets the 2nd door open/close just fine, but the door that made the signal refuses to move. 

Seems like a door refuses to work properly with its own activate out signal? 

### Reproduction steps

In sub editor, make a door operated by a circuit from its own activate out, with 'toggle when clicked' disabled. 

Door does not open/close as expected when logic output is run to 'toggle state' 

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.1.18.1 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Windows

**Comment by mygamingaccount** [comment] 2023-10-24 07:52
In a general sense, signals emitted by items can not be used to control them. I think this is to prevent some issues that could arise from loops.

You can use a logic component to make this work: wire the door `activate_out` signal to an OR component, then back to the toggle input.

**Comment by mygamingaccount** [comment] 2023-10-24 07:57
Confirmed

"Toggle Cooldown" prevents the door from being actuated

**Comment by mygamingaccount** [comment] 2023-10-24 08:45
Reproduced without mods

**Comment by Regalis11** [comment] 2023-10-24 10:14
I'm fairly sure this applies to every item, items can't send signals to themselves (IIRC this was to prevent infinite signal loops). I think we might need to change that though, because there are definitely situations where it can be useful.

**Comment by mygamingaccount** [comment] 2023-10-24 11:22
@Regalis11 
When an `activate_out` goes to an OR component, back to the door, the sender is no longer the door but the component. In this case the door should trigger.

Cooldown prevents two different users triggering the door. One user can trigger it many times within the cooldown period.

The door does not trigger because it is in Cooldown:
-It was triggered by the player (but not really)
-It was triggered by the signal.

**Comment by BlackMoons** [comment] 2023-10-24 20:02
Maybe unrelated, But iv also seen bots walk up to regular doors in the latest update, and it does the 'shutter' shake when the bot first goes to use it, then they open it up correctly a 1/2 second later.

**Comment by BlackMoons** [comment] 2023-10-24 20:03
>The door does not trigger because it is in Cooldown:

Except the door still won't open even if you have a 1 second delay gate between the activate out and toggle state. It will wait 1 second then shutter.

**Comment by BlackMoons** [comment] 2023-10-24 20:30
> I'm fairly sure this applies to every item, items can't send signals to themselves (IIRC this was to prevent infinite signal loops). I think we might need to change that though, because there are definitely situations where it can be useful.

Maybe activate_out should be given its own 'fake' ID, since if it feeds back into a doors toggle state/etc, it won't stimulate activate_out again? (Id hope active out is only triggered by clicking the door)

PS: I really love the fact that simple circuits like Add->memory->back to adder lets you create an increment/de-increment circuit without worrying about infinite loops or per-frame signal propagation (ie: Factorio logic). The infinite loop breaking system is a well implemented feature.

**Comment by mygamingaccount** [comment] 2023-10-24 22:20
> > The door does not trigger because it is in Cooldown:
> 
> Except the door still won't open even if you have a 1 second delay gate between the activate out and toggle state. It will wait 1 second then shudder.

Default cooldown is 3 seconds
Set cooldown to 0 and the circuit will work.

**Comment by mygamingaccount** [comment] 2023-10-24 22:52
Solution seems simple enough: when the door doesn't toggle when clicked, don't start the toggle cooldown.

**Comment by BlackMoons** [comment] 2023-10-24 23:11
Ah, I tried setting the delay gate to 4 seconds and it worked.

Also using OR gate with toggle cooldown set to 0 works.

Weirdly enough... Uh, a door with 1 toggle cooldown.. Can be spam clicked as fast as you want and will respond to every click. Doesn't seem cooldown applys to manual activations at all. (Does it apply to bot activation?)



Might I recommend then the fix should be: if toggle when clicked is unchecked, clicking should not trigger 'cooldown'. (Only actual changes in state should trigger cooldown) 

Also, is it intended that cooldown not apply to manually open/closing the door? 

Applying a solid 1 value to toggle state just causes it to open slowly while making multiple open/closing noises. Shouldn't cooldown prevent it from having its state changed? A cooldown of 2 seconds and 0 seconds seems to work the exact same in this case. (door opens slowly but never closes, occasionally makes sad door noises)

Applying a switch to set state and toggling it like a madman, also shows no diff between 0 and 2 second cooldown doors. 

What does cooldown do besides apparently mess with activate out->toggle state working?

**Comment by mygamingaccount** [comment] 2023-10-24 23:14
>Weirdly enough... Uh, a door with 1 toggle cooldown.. Can be spam clicked as fast as you want and will respond to every click. Doesn't seem cooldown applys to manual activations at all. (Does it apply to bot activation?)

Cooldown prevents _other_ senders from interacting while _you_ interact. You can interact as often as you want.

**Comment by BlackMoons** [comment] 2023-10-24 23:22
> Cooldown prevents _other_ senders from interacting while _you_ interact. You can interact as often as you want.

That uh, Explains a few things, I assumed it would be cooldown from any interaction/state change.

**Comment by Regalis11** [comment] 2023-10-25 07:42
Yep, you're right: it was the cooldown. Addressed in https://github.com/Regalis11/Barotrauma-development/commit/d5436cc97c9037813f761b2b482cc28f8960e01a by not activating the cooldown if the door is not set to toggle when clicked, as mygamingaccount suggested.

**Comment by BlackMoons** [comment] 2023-10-25 19:54
Cool, Thanks.

**Comment by Rokvach** [comment] 2023-10-26 00:50
We still need to test this so can't close it yet, re-opening.

**Comment by BlackMoons** [comment] 2023-10-26 01:12
Opps. My bad. I'll just let you guys manage it then.

**Comment by deltanedas** [comment] 2023-10-27 10:43
activate_out -> relay signal -> toggle_state should be enough to test it not setting cooldown

**Comment by mygamingaccount** [comment] 2023-10-27 13:22
Through a relay the sender information will not be changed, it remains the door. That will prevent it working because of the loop rule: inputs throw away signals sent by themselves. At least they used to.
@Regalis11: something to consider.

**Comment by deltanedas** [comment] 2023-10-27 16:40
or component then

**Closed** 2023-11-24 15:10 UTC
Labels: Bug, Code
