### ISSUE TITLE
[0.9.9.0] Repairing hurts too much

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2530] opened 2020-03-28 23:52 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Repairing hurts too much, especially fixing junction boxes when they're on. Even bots are dying out like flies.

Mechanic and Engineers fails too often repairing their respective items.

**Version**
0.9.9.0

**Additional information**
Wiring/Unwiring items are especially painful. You lose more than half your life. This makes very situational subs like ones that you have to hook up everything manually too deadly. Wiring features to items are also too deadly.

I usually create:
-Light indicators for reactor temperatures.
-Preventing set state signals from being sent to small pumps in docking ports turned into airlocks when port hatch is opened to prevent the pump from working needlessly.
-Adding signals to navigation terminals that doesn't have particular signal buttons wired.
-Reduce signals from engine to prevent bad captains overvolting power grid.
-Rewiring pumps for Thermal Artifacts.
-Reroute battery power for fabrication and deconstruction.

I can't really do any of these now without dying or wasting lots of meds.

**Comment by Kaillera** [comment] 2020-03-29 00:02
I don't think fresh engineers and mechanic should fail to repair over 10% of the times initially. I also feel like other jobs shouldn't fail over 33% of the time initially.

**Comment by ezjamsen** [comment] 2020-03-29 13:20
The issue seems to be with networking. Working as intended in SP

**Comment by Regalis11** [comment] 2020-03-29 13:42
No it isn't, it seems to be working the same in MP and SP. The repair requirements are very high (causing even mechanics to very often fail with repairs), as is the damage caused by failed repairs.

**Comment by ezjamsen** [comment] 2020-03-29 15:05
Retuned. I could swear that there was different severity of injury in multiplayer than during testing in singleplayer.

**Comment by Rokvach** [comment] 2020-03-31 20:00
No issues, closing.

**Closed by Rokvach** 2020-03-31 20:00 UTC
Labels: Bug, Design, Feature request
