### ISSUE TITLE
Giving multiple of the same orders seems to always just target the same bot, rather than pick a new bot if the same order is given

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#4386] opened 2020-11-25 08:47 UTC
Branch: dev
Build: Release
Commit: https://github.com/Regalis11/Barotrauma-development/commit/f387262b23c3d1429bd3eb0347f75c21448fc112

Noticed this while testing the bot distribution of purchased items ticket. I bought a lot of items and tried to contextually order bots to clean up the crates giving a order per crate. But each time I did this it juts picked the same bot rather than pick a bot which didn't already have a order. 

Same happens non-contextually as well if you just click the cleaning order multiple times it just keeps picking the same bot. 

This issue isn't only noticeable with the new cleaning order but seems to affect all orders.

**Comment by ekqvist** [comment] 2020-11-25 10:07
I removed the Bug label as this isn't really a bug. This has been a topic of discussion today on the QA channel on Slack. I'll try to summarize this a bit below.

I believe this is caused by intentional changes to the quick assignment (or automatic assignment) logic a while back. The logic doesn't prioritize idle characters first anymore.

The reasoning for the change was that the old behavior made it more cumbersome to assign a new order to a character with an existing order because it would require the extra step of manually assigning that order to that person. This change was made to shift that extra step to the situations where you want to assign the same order to multiple people, so you do the manual assigning now in those situations.

The old behavior could also lead to an incompetent person being assigned to a task when more suitable characters have been ordered to do something else.

I believe #4296 is related and also a report of the behavior being changed.

**Comment by ezjamsen** [comment] 2020-12-01 13:03
Not a bug for the above reasons, but let's investigate how this can be improved overall a little later.

**Closed** 2020-12-01 13:02 UTC
Labels: Code, Design
