### ISSUE TITLE
[Unstable] Crashlog on 9 player campaign match

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#2464] opened 2020-03-18 22:17 UTC
**Description**
Game crashed with this error log. **After that I couldn't get into server due to missing entity error.**
![image](https://user-images.githubusercontent.com/59519434/77012555-734d8280-696e-11ea-96a1-f61061498a89.png)

**Steps To Reproduce**
It can be quite reliably reproduced by buying many items in campaign on steam P2P
[crashreport (101).log](https://github.com/Regalis11/Barotrauma/files/4351632/crashreport.101.log)

**Version**
Unstable version, steam P2P hosted match, 9 players on Kastrull, bought a lot of supplies - thats where the crashes started for people.

**Additional information**

**Comment by Regalis11** [comment] 2020-03-29 17:59
Duplicate of #2464 (closing this one because the new ticket has more info)

**Closed by Regalis11** 2020-03-29 17:59 UTC
Labels: Bug, Code, Crash, Networking
