### ISSUE TITLE
Attempting to launch a Depthcharge crashes the game

### ISSUE THREAD

**Issue by cshingle** [Regalis11/Barotrauma#10617] opened 2022-11-29 03:42 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Clicking a button wired to the Depthcharge launcher crashes the game. I was working on updating mods for unstable so I initially thought it was a mod issue.

### Reproduction steps

1. Disable all mods
2. Verify file integrity via steam to ensure that I didn't accidentally modify the xml
3. Load up a stock sub such as the Orca2
4. Run go to the upper deck and launch a depthcharge
5. crash

### Bug prevalence

Happens every time I play

### Version

0.20.8.0 (Unstable)

### Which operating system did you encounter this bug on?

Linux

### Relevant error messages and crash reports

```shell
﻿Barotrauma Client crash report (generated on 11/28/2022 21:33:44)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

7C2CA151F03264D0421CEA704831A656

Game version 0.20.8.0 (UnstableLinux, branch dev, revision 1d40fd4ca0)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla
Level seed: no level loaded
Loaded submarine: Orca2 (B2055A151D519D591D5638783C42431C)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Unix 5.15.0.53 64 bit
    GPU name: 
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Boolean TryLaunch(Single, Barotrauma.Character, Boolean)
Stack trace: 
   at Barotrauma.Items.Components.Turret.TryLaunch(Single deltaTime, Character character, Boolean ignorePower) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Turret.cs:line 647
   at Barotrauma.Items.Components.Turret.ReceiveSignal(Signal signal, Connection connection) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Turret.cs:line 1676
   at Barotrauma.Items.Components.Connection.SendSignal(Signal signal) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Signal\Connection.cs:line 302
   at Barotrauma.Item.SendSignal(Signal signal, Connection connection) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 2472
   at Barotrauma.Item.SendSignal(Signal signal, String connectionName) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 2414
   at Barotrauma.Items.Components.Controller.Pick(Character picker) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Machines\Controller.cs:line 410
   at Barotrauma.Item.TryInteract(Character user, Boolean ignoreRequiredItems, Boolean forceSelectKey, Boolean forceUseKey) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 2599
   at Barotrauma.Character.DoInteractionUpdate(Single deltaTime, Vector2 mouseSimPos) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2885
   at Barotrauma.Character.ControlLocalPlayer(Single deltaTime, Camera cam, Boolean moveCam) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\Character.cs:line 381
   at Barotrauma.Character.UpdateControlled(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\Character.cs:line 419
   at Barotrauma.Character.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 3109
   at Barotrauma.AICharacter.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AICharacter.cs:line 72
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2969
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 192
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 863
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[11/28/2022 21:32:14] Attempting to open ALC device "Starship/Matisse HD Audio Controller Analog Stereo"
[11/28/2022 21:32:13] Logged in as zig158 (SteamID STEAM_1:1:39219991)
```

**Comment by Regalis11** [comment] 2022-11-29 08:28
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10547

**Closed by Regalis11** 2022-11-29 08:28 UTC
