### ISSUE TITLE
Random crash after submarine being attacked by monster (EnemyAIController.UpdateLimbAttack)

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#10382] opened 2022-11-14 12:46 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

This has happened twice.
Both happened when my submarine gets attacked by tigerthresher + bonethresher swarm and game crashes.
Not sure if other monsters causes crash too.
I did use some mods but none is relevant to monsters.
The submarine is a slightly modified humpback, nothing special.
Only "Extended Upgrades" makes some value changes to the max level you can upgrade your sub.

[crashreport (96).log](https://github.com/Regalis11/Barotrauma/files/10002813/crashreport.96.log)
[crashreport (97).log](https://github.com/Regalis11/Barotrauma/files/10002814/crashreport.97.log)

### Reproduction steps

I've tried reproducing same scene in sub editor with and without mods, but couldn't reproduce this crash.
Not sure if this works.
1. start a campaign
2. meet with tigerthresher + bonethresher group
3. let them attack your submarine

### Bug prevalence

Happens every now and then

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2022-11-15 08:31
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10249

**Closed by Regalis11** 2022-11-15 08:31 UTC
Labels: Bug, Code, Crash
