### ISSUE TITLE
Item scaling threshold issue.

### ISSUE THREAD

**Issue by ChikoEduardo** [Regalis11/Barotrauma#1763] opened 2019-07-21 13:52 UTC
It seems the scaling of items have a threshold of some kind now, something that wasn't there before. I don't know if it's a bug or working as intended but I decided to report it anyways.

Here's an example image:
https://cdn.discordapp.com/attachments/426913209602146315/602493405930455053/Image25.png
The first poster is the size the item is supposed to be and the second one of the size it gets when placed in the world.

**Comment by Regalis11** [comment] 2019-07-22 10:00
Could you please send the xml for the item? I haven't been able to reproduce this problem with any of the vanilla items.

**Comment by ChikoEduardo** [comment] 2019-07-23 14:08
Here:
https://www.dropbox.com/s/dipw3b22ab1dq3x/Misc.rar?dl=0

It's the ingame documents. I also attached one of the png files.

**Comment by Regalis11** [comment] 2019-07-25 07:58
Thanks! Looks like the problem is that the scale is clamped above 0.1, and these items have a way smaller scale. I'll set the limit lower for the next update, but I would still recommend making the sprites smaller so you won't have to scale them down so heavily. Using such enormous textures for an item that's scaled down to about 25x35 pixels not only takes up unnecessary memory, but also makes them look worse. The actual viewable document/poster could still have a larger texture, and be defined as a custom style for the GUIFrame of an empty ItemComponent instead of using sonar components that do nothing.

**Comment by Regalis11** [comment] 2019-07-25 08:00
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1c201f4117542968347d2a0e630db0f160ab67c2 (private repo)

**Comment by ChikoEduardo** [comment] 2019-07-26 16:14
Well, I kinda wanted to avoid making a separated png for documents but I guess it's better to do so for the unnecessary memory thing.
Also, I'll try that gui thing. I used the sonar thing coz I couldn't come up with another way to implement ingame docs. :p

**Comment by Rokvach** [comment] 2019-08-02 10:11
Tested, this is working correctly. Closing.

**Closed by Rokvach** 2019-08-02 10:11 UTC
Labels: Bug, Code
