### ISSUE TITLE
[Bug] Handheld sonar's "onUse" causes battery to drain quickly upon pressing left-click

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#2561] opened 2020-04-02 04:47 UTC
### Issue:

When active, the handheld sonar's 'onUse' statusEffect seems to stack onto itself, draining the battery extremely quickly whenever mouse1 is pressed.

**Steps to reproduce:**

Equip a handheld sonar with battery
Enable active sonar
Hold mouse1 as if 'using' an item (like lighting flares for instance)

**Comment by Regalis11** [comment] 2020-04-02 08:02
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6282635

**Comment by Rokvach** [comment] 2020-04-02 11:55
Couldn't reproduce, seems to be working. Closing.

**Closed by Rokvach** 2020-04-02 11:55 UTC
Labels: Bug, Code

**Comment by Ek-Videogames** [comment] 2020-05-22 00:42
(Reminder need to reopen this, unless it has been again-fixed since we talked in discord)
