### ISSUE TITLE
[0.9.1001.0] Psychosis Broken Device State does not recover when affliction is gone

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2860] opened 2020-05-18 17:24 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Psychosis Broken Device State does not recover when affliction is gone

**Version**
0.9.1001.0

**Comment by Regalis11** [comment] 2020-05-18 17:25
Duplicate of #2824

**Comment by Regalis11** [comment] 2020-05-18 17:41
Nvm, not a duplicate, although I thought I already fixed this in https://github.com/Regalis11/Barotrauma-development/commit/f3cac70104a3bc3a53edb70f3f3540c2f5e51491. Will take another look

**Comment by Regalis11** [comment] 2020-05-18 18:19
Attempt 2: https://github.com/Regalis11/Barotrauma-development/commit/78a348b2c8bf3ffd0e02a1d7d3c5f27dbbe452e6

**Comment by Rokvach** [comment] 2020-05-19 02:29
Tested, working correctly. Closing.

**Closed by Rokvach** 2020-05-19 02:29 UTC
Labels: Bug, Code
