### ISSUE TITLE
Unstable - Wreck missions are broken in numerous ways

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#3125] opened 2020-06-17 22:09 UTC
**Description**
-log book shows this error when trying to equip it
![image](https://user-images.githubusercontent.com/59519434/84955384-826fd800-b0f7-11ea-8f0d-be7dcdde66ab.png)
-log book that shows this error causes another error after docking to outpost
![image](https://user-images.githubusercontent.com/59519434/84955462-9b788900-b0f7-11ea-8c33-7ba73c9a02ed.png)
-after that, it can be equipped and read
![image](https://user-images.githubusercontent.com/59519434/84955484-a7fce180-b0f7-11ea-9c7b-4d4c18a97f2a.png)

-some wreck missions show the log book above level, and the logbook isnt in the level's wreck
![image](https://user-images.githubusercontent.com/59519434/84956381-5d7c6480-b0f9-11ea-895a-dc51f446e325.png)

**Steps To Reproduce**
Some wreck missions work normally (except logbooks not recognised in inventory)
Some wreck mission log books are corrupted like this.
I did not place the logbook in any container after looting it. It went straight into hotbar slot and stayed there.
Everything was in singleplayer campaign mode.

**Version**
Unstable

**Comment by Regalis11** [comment] 2020-06-18 06:14
Duplicate of #2744

**Closed by Regalis11** 2020-06-18 06:14 UTC
