### ISSUE TITLE
no monsters in multiplayer

### ISSUE THREAD

**Issue by SaulApostle** [Regalis11/Barotrauma#1684] opened 2019-06-21 13:26 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.

There are no monsters in multiplayer campaign , and there are no monsters in mission mode transport missions.

**Version**
9.0.6

**Comment by hubismal** [comment] 2019-06-22 21:52
How far are you from the center of the circle? The  way the game works right now is that there are few to no monsters on the outside of the map, while on the inside, monsters are everywhere.

**Comment by SaulApostle** [comment] 2019-06-23 03:52
Comparing MP with SP

**Comment by Regalis11** [comment] 2019-06-24 16:03
Should be fixed in 76d4d55. I believe the problem was caused by a bug in the spawn position logic that caused it to discard perfectly valid spawn positions when there were floating ice chunks in the level, which sometimes caused monsters to spawn very far from the sub (e.g. at the opposite side of the level or somewhere below it).

**Closed by Regalis11** 2019-06-24 16:03 UTC

**Comment by SaulApostle** [comment] 2019-06-28 13:03
9.0.7 no fix at all

**Comment by SaulApostle** [comment] 2019-06-29 15:22
9.0.7 

No successful repair
When I play multiplayer on my own, it seems normal. When I play with a friend, there are three levels in a row and none of them has a monster.
