### ISSUE TITLE
Map generation Issue

### ISSUE THREAD

**Issue by Caithloki** [Regalis11/Barotrauma#4422] opened 2020-12-01 14:45 UTC
SlqKfRDC is the seed of the save. The dolgovskoy station is the bugged out map

[Save_43 - Copy.save.docx](https://github.com/Regalis11/Barotrauma/files/5623278/Save_43.-.Copy.save.docx)

Switched from stable build to unstable build well in the map, causing the end station to generate in the wall with only the option to drive around the whole map too it.

![image](https://user-images.githubusercontent.com/12504812/100755168-43da8b00-33c2-11eb-904e-312bb175d431.png)

**Comment by Regalis11** [comment] 2020-12-02 07:29
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/10d4c887e95be04c0b51e40530404cd20d495796

**Comment by Rokvach** [comment] 2020-12-17 09:52
Tested, I wasn't able to reproduce the issue with the provided save. Seems to be working correctly. Closing.

**Closed by Rokvach** 2020-12-17 09:52 UTC
Labels: Bug, Code
