### ISSUE TITLE
Multiplayer Crash when spectating.

### ISSUE THREAD

**Issue by S3rine** [Regalis11/Barotrauma#11040] opened 2023-01-27 02:35 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Game Crashed when I was trying to spectate the multiplayer game.

### Reproduction steps

1. join a multiplayer campaign
2. Click Spectate

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 01/26/2023 21:26:33)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

B5C3AB2BBD7769A420A018E6898F0875

Game version 0.20.16.1 (ReleaseWindows, branch release, revision 33a42adf77)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla, EK | Armory, EK | Utility, Improved Husks, Shipwrecks Extended, XanMonsters Creature Pack, XanMonsters Volume 2 Creature Pack, XanRobots, T.I.T.A.N. power suit V2, Beacons Extended, EK | Gunnery, Pet Mudraptor -  Holiday Update Hotfix, BaroTraumatic, Lua For Barotrauma, Barotraumatic Other Creature fixes, Gene Splicer+ [New Genes], CatGene, Undersea Horrors, Fortunate Worm, BaroDrama V4.0, Barotraumatic New Creatures, Neurotrauma, NT Surgery Plus, MoreMissionsMod, NT Pharmacy, Let Them All In, Extract It!, SOFA'S CREATURES
Level seed: MolovskMehen Linea
Loaded submarine: Orca (C32E812D54D681C98757564E0727BB32)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)

System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit
    GPU name: NVIDIA GeForce GTX 1080 Ti
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: A read lock may not be acquired with the write lock held in this mode. (System.Threading.LockRecursionException)
Target site: Boolean TryEnterReadLockCore(TimeoutTracker)
Stack trace: 
   at System.Threading.ReaderWriterLockSlim.TryEnterReadLockCore(TimeoutTracker timeout)
   at Barotrauma.PrefabSelector`1.get_ActivePrefab() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Prefabs\PrefabSelector.cs:line 29
   at Barotrauma.PrefabCollection`1.get_Item(Identifier identifier) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Prefabs\PrefabCollection.cs:line 238
   at Barotrauma.CharacterInfo.get_Prefab() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\CharacterInfo.cs:line 213
   at Barotrauma.WearableSprite.ParsePath(Boolean parseSpritePath) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Wearable.cs:line 171
   at Barotrauma.WearableSprite.Init(Character picker) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Wearable.cs:line 200
   at Barotrauma.Items.Components.Wearable.Equip(Character character) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Wearable.cs:line 418
   at Barotrauma.Item.Equip(Character character) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 2891
   at Barotrauma.CharacterInventory.TryPutItem(Item item, Character user, IEnumerable`1 allowedSlots, Boolean createNetworkEvent, Boolean ignoreCondition) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\CharacterInventory.cs:line 392
   at Barotrauma.CharacterInventory.TryPutItem(Item item, Int32 index, Boolean allowSwapping, Boolean allowCombine, Character user, Boolean createNetworkEvent, Boolean ignoreCondition) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\CharacterInventory.cs:line 491
   at Barotrauma.Inventory.ApplyReceivedState() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Inventory.cs:line 1954
   at Barotrauma.Character.Remove() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 4483
   at Barotrauma.Character.RemoveByPrefab(CharacterPrefab prefab) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 3476
   at Barotrauma.CharacterPrefab.Dispose() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\CharacterPrefab.cs:line 17
   at Barotrauma.PrefabSelector`1.RemoveInternal(T prefab) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Prefabs\PrefabSelector.cs:line 136
   at Barotrauma.PrefabSelector`1.RemoveByFile(ContentFile file, Action`1 callback) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Prefabs\PrefabSelector.cs:line 57
   at Barotrauma.PrefabCollection`1.RemoveByFile(ContentFile file) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Prefabs\PrefabCollection.cs:line 413
   at Barotrauma.CharacterFile.UnloadFile() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentFile\CharacterFile.cs:line 38
   at Barotrauma.ContentPackage.<>c.<UnloadContent>b__53_0(ContentFile f) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentPackage\ContentPackage.cs:line 327
   at Barotrauma.Extensions.IEnumerableExtensions.ForEach[T](IEnumerable`1 source, Action`1 action) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Extensions\IEnumerableExtensions.cs:line 140
   at Barotrauma.ContentPackage.UnloadContent() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentPackage\ContentPackage.cs:line 327
   at Barotrauma.ContentPackageManager.EnabledPackages.<>c.<SetRegularEnumerable>b__15_3(RegularPackage r) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentPackageManager.cs:line 90
   at Barotrauma.Extensions.IEnumerableExtensions.ForEach[T](IEnumerable`1 source, Action`1 action) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Extensions\IEnumerableExtensions.cs:line 140
   at Barotrauma.ContentPackageManager.EnabledPackages.SetRegularEnumerable(IReadOnlyList`1 inNewRegular)+MoveNext() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentPackageManager.cs:line 90
   at Barotrauma.Extensions.IEnumerableExtensions.Consume[T](IEnumerable`1 enumerable) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Extensions\IEnumerableExtensions.cs:line 149
   at Barotrauma.ContentPackageManager.EnabledPackages.SetRegular(IReadOnlyList`1 newRegular) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentPackageManager.cs:line 76
   at Barotrauma.ContentPackageManager.EnabledPackages.Restore() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentPackageManager.cs:line 229
   at Barotrauma.Networking.GameClient.OnClientPeerDisconnect(PeerDisconnectPacket disconnectPacket) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 989
   at Barotrauma.Networking.SteamP2PClientPeer.Close(PeerDisconnectPacket peerDisconnectPacket) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2PClientPeer.cs:line 352
   at Barotrauma.Networking.GameClient.Quit() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2579
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 514
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 887
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[01/26/2023 21:26:32] Error while reading a message from server. 
Exception thrown while reading segment EntityEventInitial at position 16.
Inner exception: Tried to read too much data from segment.
   at Barotrauma.Networking.SegmentTableReader`1.SegmentReadMsg.Check() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SegmentTable.cs:line 168
   at Barotrauma.Networking.SegmentTableReader`1.SegmentReadMsg.ReadUInt16() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SegmentTable.cs:line 189
   at Barotrauma.Items.Components.ConnectionPanel.ClientEventRead(IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\Signal\ConnectionPanel.cs:line 169
   at Barotrauma.Item.ClientEventRead(IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 1362
   at Barotrauma.Networking.ClientEntityEventManager.Read(ServerNetSegment type, IReadMessage msg, Single sendingTime, List`1 entities) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\NetEntityEvent\ClientEntityEventManager.cs:line 221
   at Barotrauma.Networking.GameClient.<>c__DisplayClass116_0.<ReadIngameUpdate>b__0(ServerNetSegment segment, IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2127
   at Barotrauma.Networking.SegmentTableReader`1.Read(IReadMessage msg, SegmentDataReader segmentDataReader, ExceptionHandler exceptionHandler) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SegmentTable.cs:line 302
[01/26/2023 21:26:31] Desmoes
[01/26/2023 21:26:30] Ectoplasm
[01/26/2023 21:26:30] DrPepperMan
[01/26/2023 21:26:30] Invalid stat type type "AttackSpeedMultiplier" in item (ek_hatchet)
[01/26/2023 21:26:30] Invalid stat type type "AttackSpeedMultiplier" in item (ek_captains_sabre)
[01/26/2023 21:26:30] Arctic
[01/26/2023 21:26:30] Evanbubba
[01/26/2023 21:26:30] WARNING: Potentially invalid damage modifier in "Marine Helmet, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[01/26/2023 21:26:30] Invalid stat type type "AttackSpeedMultiplier" in item (ek_hatchet)
[01/26/2023 21:26:30] WARNING: Potentially invalid damage modifier in "Marine Helmet, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[01/26/2023 21:26:29] Received STARTGAMEFINALIZE packet. Round init status: Started
[01/26/2023 21:26:28]  -0: EstimateSteamLobbyPing (STEAM_1:1:102371901), WaitingForActivation
[01/26/2023 21:26:28] Task count: 1
[01/26/2023 21:26:26] Generating an outpost for the end of the level... (Location: Mehen Linea Outpost, level type: LocationConnection)
[01/26/2023 21:26:25] Generating an outpost for the start of the level... (Location: Molovsk Outpost, level type: LocationConnection)
[01/26/2023 21:26:24] Level identifier: coldcavernstransition
[01/26/2023 21:26:20] Invalid stat type type "AttackSpeedMultiplier" in item (ek_tonfa)
[01/26/2023 21:26:20] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2726528805/Items/Statin.png, size: 37x69)
[01/26/2023 21:26:11] Overriding an affliction or a buff with the identifier 'combatstimulant' using the file 'C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/26/2023 21:26:11] Overriding an affliction or a buff with the identifier 'implacable' using the file 'C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/26/2023 21:26:11] Overriding an affliction or a buff with the identifier 'concussion' using the file 'C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/26/2023 21:26:11] Overriding an affliction or a buff with the identifier 'radiationsickness' using the file 'C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/26/2023 21:26:11] Overriding an affliction or a buff with the identifier 'drunk' using the file 'C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/26/2023 21:26:11] Overriding an affliction or a buff with the identifier 'invertcontrols' using the file 'C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/26/2023 21:26:11] Overriding an affliction or a buff with the identifier 'chemwithdrawal' using the file 'C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/26/2023 21:26:11] Overriding an affliction or a buff with the identifier 'chemaddiction' using the file 'C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/26/2023 21:26:11] Overriding an affliction or a buff with the identifier 'opiatewithdrawal' using the file 'C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/26/2023 21:26:11] Overriding an affliction or a buff with the identifier 'opiateoverdose' using the file 'C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/26/2023 21:26:11] Overriding an affliction or a buff with the identifier 'opiateaddiction' using the file 'C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/26/2023 21:26:11] Overriding an affliction or a buff with the identifier 'acidburn' using the file 'C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/26/2023 21:26:11] Overriding an affliction or a buff with the identifier 'burn' using the file 'C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/26/2023 21:26:11] Overriding an affliction or a buff with the identifier 'explosiondamage' using the file 'C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/26/2023 21:26:11] Overriding an affliction or a buff with the identifier 'organdamage' using the file 'C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/26/2023 21:26:11] Overriding an affliction or a buff with the identifier 'gunshotwound' using the file 'C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/26/2023 21:26:11] Overriding an affliction or a buff with the identifier 'bitewounds' using the file 'C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/26/2023 21:26:11] Overriding an affliction or a buff with the identifier 'lacerations' using the file 'C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/26/2023 21:26:11] Overriding an affliction or a buff with the identifier 'blunttrauma' using the file 'C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/26/2023 21:26:11] Overriding an affliction or a buff with the identifier 'internaldamage' using the file 'C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/26/2023 21:26:11] Overriding an affliction or a buff with the identifier 'bleedingnonstop' using the file 'C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/26/2023 21:26:11] Overriding an affliction or a buff with the identifier 'bleeding' using the file 'C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/26/2023 21:26:11] Overriding an affliction or a buff with the identifier 'sufforinpoisoning' using the file 'C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/26/2023 21:26:11] Overriding an affliction or a buff with the identifier 'cyanidepoisoning' using the file 'C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/26/2023 21:26:11] Overriding an affliction or a buff with the identifier 'morbusinepoisoning' using the file 'C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/26/2023 21:26:11] Overriding an affliction or a buff with the identifier 'bloodloss' using the file 'C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/26/2023 21:26:11] Overriding an affliction or a buff with the identifier 'oxygenlow' using the file 'C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/26/2023 21:26:11] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2726528805/Items/Medical/contaminationv1.png, size: 129x128)
[01/26/2023 21:26:11] WARNING: Unrecognized element in affliction "cytokine" (Affliction)
[01/26/2023 21:26:11] WARNING: Unrecognized element in affliction "cytokine" (Affliction)
[01/26/2023 21:26:11] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2518816103/Text/Barotraumatic.png, size: 1516x265)
[01/26/2023 21:26:10] WARNING: C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2127575896/Xan2events.xml: All root EventSets should have an identifier
[01/26/2023 21:26:10] WARNING: C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2127575896/Xan2events.xml: All root EventSets should have an identifier
[01/26/2023 21:26:10] WARNING: C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2127575896/Xan2events.xml: All root EventSets should have an identifier
[01/26/2023 21:26:10] WARNING: C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2127575896/Xan2events.xml: All root EventSets should have an identifier
[01/26/2023 21:26:10] WARNING: C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2127575896/Xan2events.xml: All root EventSets should have an identifier
[01/26/2023 21:26:10] WARNING: C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2127575896/Xan2events.xml: All root EventSets should have an identifier
[01/26/2023 21:26:10] WARNING: C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2127575896/Xan2events.xml: All root EventSets should have an identifier
[01/26/2023 21:26:10] WARNING: C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2127575896/Xan2events.xml: All root EventSets should have an identifier
[01/26/2023 21:26:10] WARNING: C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2127575896/Xan2events.xml: All root EventSets should have an identifier
[01/26/2023 21:26:10] WARNING: C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2127575896/Xan2events.xml: All root EventSets should have an identifier
[01/26/2023 21:26:10] WARNING: C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2127575896/Xan2events.xml: All root EventSets should have an identifier
[01/26/2023 21:26:10] WARNING: C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2127575896/Xan2events.xml: All root EventSets should have an identifier
[01/26/2023 21:26:10] WARNING: C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2108010462/Xanevents.xml: All root EventSets should have an identifier
[01/26/2023 21:26:10] WARNING: C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2108010462/Xanevents.xml: All root EventSets should have an identifier
[01/26/2023 21:26:10] WARNING: C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2108010462/Xanevents.xml: All root EventSets should have an identifier
[01/26/2023 21:26:10] WARNING: C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2108010462/Xanevents.xml: All root EventSets should have an identifier
[01/26/2023 21:26:10] WARNING: C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2108010462/Xanevents.xml: All root EventSets should have an identifier
[01/26/2023 21:26:10] WARNING: C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2108010462/Xanevents.xml: All root EventSets should have an identifier
[01/26/2023 21:26:10] WARNING: C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2108010462/Xanevents.xml: All root EventSets should have an identifier
[01/26/2023 21:26:10] WARNING: C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2108010462/Xanevents.xml: All root EventSets should have an identifier
[01/26/2023 21:26:10] WARNING: C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2108010462/Xanevents.xml: All root EventSets should have an identifier
[01/26/2023 21:26:10] WARNING: C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2108010462/Xanevents.xml: All root EventSets should have an identifier
[01/26/2023 21:26:10] WARNING: C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2108010462/Xanevents.xml: All root EventSets should have an identifier
[01/26/2023 21:26:10] WARNING: C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2108010462/Xanevents.xml: All root EventSets should have an identifier
[01/26/2023 21:26:09] Overriding an affliction or a buff with the identifier 'huskinfection' using the file 'C:/Users/Oscar/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2085783214/Afflictions.xml'
[01/26/2023 21:25:24] Attempting to open ALC device "OpenAL Soft on Speakers (Razer Audio Controller - Game)"
[01/26/2023 21:25:22] Logged in as Serine (SteamID STEAM_1:0:417820731)
```

**Comment by Regalis11** [comment] 2023-01-27 08:00
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10872

**Closed by Regalis11** 2023-01-27 08:00 UTC
