### ISSUE TITLE
Wifi and Headsets in MP and SP

### ISSUE THREAD

**Issue by bavarianblacksmith** [Regalis11/Barotrauma#2885] opened 2020-05-23 23:26 UTC
- [ X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In SP, headsets will send signals to wifi components whenever the player types something into chat. However, the player cannot receive messages/signals from a terminal (through wifi channel) even if all components have "linked to chat" enabled.

In MP, headsets can receive messages from a terminal (through wifi channel), but cannot send any messages.

**Steps To Reproduce**
Wifi in -> Terminal -> Wifi out ---> Headset
All components "linked to chat" and minimum length of message (or whatever the specific setting name is) at "0.0"

**Version**
v0.9.9.1 Windows 10

**Additional information**
Seems like at least sending messages should work in MP. I like that your headset can be in your immediate inventory and still relay messages to the player's chat. That's a very convenient feature.

**Comment by Regalis11** [comment] 2020-05-24 13:54
Duplicate of #2703

**Closed by Regalis11** 2020-05-24 13:54 UTC
