### ISSUE TITLE
The charge bar of the supercapicapator doesn't rotate when the supercapicapator is rotated.

### ISSUE THREAD

**Issue by HW12345** [Regalis11/Barotrauma#8301] opened 2022-02-16 02:45 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The charge bar of the supercapicapator doesn't rotate when the supercapicapator is rotated.
https://jays.host/pev/0b2fa053.png

**Steps To Reproduce**
Charge the supercapicapator and rotate it in the editor.

**Version**
Windows, version 0.15. 23.0 (not sure about the version, its the latest non-unstable version)

**Additional information**
It may be caused by a mod but I'm not very sure.

**Comment by HW12345** [comment] 2022-02-16 02:48
image link https://jays.host/pev/0b2fa053.png

**Comment by Regalis11** [comment] 2022-02-16 08:15
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3199

**Closed by Regalis11** 2022-02-16 08:15 UTC
