### ISSUE TITLE
False number for "on ship" count when buying items at a Station/Colony

### ISSUE THREAD

**Issue by VermilionCosmos** [Regalis11/Barotrauma#8831] opened 2022-04-16 23:18 UTC
**Description**
Supply count when docked has issues when counting total owned stock of an item.

**Steps To Reproduce**
Have item in container on ship, look at buy menu to purchase more of that item. It will say an amount that is on the ship. Then without buying anything go and take that item and put it in your inventory and check the buy menu again. The amount "on the ship" will double (or go up depending on how much you took). It seems to be double counting items that are moved to the player inventory.

**Version**
Windows 10.  Build ID: 8276043

**Additional information**
Mainly causes an issue when coordinating with the captain who is purchasing items and it gives false information.

**Comment by ekqvist** [comment] 2022-11-17 09:32
Hi! Apologies for the very late reply to your issue.

Unfortunately, I have been unable to reproduce the issue you reported. I tried reproducing the issue in both singleplayer and multiplayer with no success. The "owned" amount seems to stay the same even after picking up the items from the container.

Is this an issue you're still having trouble with? If so, would there be any other steps you could provide that would help in reproducing the issue?

**Comment by Regalis11** [comment] 2023-01-04 11:06
No known steps to repro, closing

**Closed by Regalis11** 2023-01-04 11:06 UTC
Labels: Bug, Need more info, Code
