### ISSUE TITLE
bricked multiplayer campaign save

### ISSUE THREAD

**Issue by justanmeemman** [Regalis11/Barotrauma#7737] opened 2021-12-12 23:49 UTC
**Description**
left a mission after completing a outpost next mission point tried to load and the spat a error of 
"error while starting round did not receive start game finalize"

when we first tried to boot up the save it would kick us out with the start game finalize 
second attempt we verified files and loaded in this time it loaded in but all crew were gone and anyone besides host trying to load got a error of
"co routine barotrauma.networking.gameclient {startgame} D_93 failed"

**Version**
V0.15.13.0 release windows rev 4e66dd7b5d

**Additional information**
also corrupted about 3 of our files after this. steam replaced them correctly 
gonna include the saves if anyone wants to take a look and learn anything useful from the
[campaign saves(bricked).zip](https://github.com/Regalis11/Barotrauma/files/7700111/campaign.saves.bricked.zip)
m

**Comment by Regalis11** [comment] 2021-12-13 16:48
This could potentially be caused by https://github.com/Regalis11/Barotrauma/issues/7175. The fact that the host didn't get the error would also make sense, because the host is the only one who doesn't need to receive the save file from the server.

I gave this a test in the latest unstable version and was able to load the save with no issues. The fix will be released to the public version soon, but for the time being, it might be possible to work around the problem by switching to the [unstable version](https://barotraumagame.com/announcements/barotrauma-tester-version-made-public/). Sorry for the inconvenience!

**Closed by Regalis11** 2021-12-13 16:48 UTC
Labels: Bug, Code
