### ISSUE TITLE
Flashlight effect stays active when switching places of heavy weapons in belt and hand slots

### ISSUE THREAD

**Issue by Smrtonosan** [Regalis11/Barotrauma#12369] opened 2023-07-17 21:24 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If you use two heavy weapons, that can be carried only in the belt slot and hands, switching from one to the other will cause the flashlight effect to stay active, works if one or both have flashlights.

### Reproduction steps

1. Open Sub Editor.
2. Load camel.
3. Place two heavy weapons, for an example two Assault Rifles and two flashlights with batteries into a locker.
4. Playtest submarine.
5. Put flashlights, with batteries, into the heavy weapons.
6. Take one heavy weapon into hands, put the other one into the belt slot.
7. Switch from one weapon to the other by pressing the green bar above the heavy weapon, or by pulling one's icon into the other.
![20230717231919_1](https://github.com/Regalis11/Barotrauma/assets/104994469/c1aecdc0-8950-4018-9bf6-665ad035f912)
_Only the rapid fissile accelerator has a flashlight._

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by giists** [comment] 2023-07-18 10:20
Already fixed, closing.

**Closed by giists** 2023-07-18 10:20 UTC

**Comment by Regalis11** [comment] 2023-07-18 10:23
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11023
