### ISSUE TITLE
AI and fighting the wrong invaders

### ISSUE THREAD

**Issue by irishspring269** [Regalis11/Barotrauma#11536] opened 2023-03-15 04:47 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While i was transporting cultists to another base i had one of my ai crew members on fight intruders and while one of the cultists where reparing the ship he died and when i switched to my medic to see how it happen it turns out he was shot by my AI who was on fight invaders im geussing because he hurt someone with a blow torch.Could you please fix this for the future?

### Reproduction steps

put AI on fight intruders and let passengers repair the ship

### Bug prevalence

Just once

### Version

v1.0.7.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
there were none
```

**Comment by Regalis11** [comment] 2023-03-15 09:27
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7750

**Closed by Regalis11** 2023-03-15 09:27 UTC
