### ISSUE TITLE
Detaching a Circuit Box and Transitioning to Next Level Index Out of Range Permacrash

### ISSUE THREAD

**Issue by RealLordzombieboy** [Regalis11/Barotrauma#12999] opened 2023-11-10 03:42 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

We switched ships from Dungong to Azimuth in a multiplayer self-hosted server of two people and 3 bots. My friend had made one Circuit box for a contraption for the reactor, and we had another spare. He took it off the wall and grabbed the spare to get ready for the transfer to the new ship (transfer items was enabled), then the game crashed and continues to crash every time we try and reopen the save. This occurs when trying to open the world without any other players in the lobby.

### Reproduction steps

1. Open a save pre-treacherous tides update.
2. Place a circuit box filled with components in the Dungon ship.
3. Put second circuit box in a crate on the ship's floor.
4. Buy Azimuth ship.
5. Take the circuit box off the wall and keep it in the player's inventory.
6. Enable transfer items and switch to Azimuth ship.
7. Transfer from station to the next area.
8. Game crash.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 11/09/2023 22:16:49)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

152BA3E19FDBF5D0CE7AEC3CB5E83BE4

Game version 1.1.19.3 (ReleaseWindows, branch release/traitor-update-hotfix-2, revision e92ea6f791)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla (D6A9CBF)
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.RoundSummaryScreen
SteamManager initialized
Client (Round hadn't been started)

System info:
    Operating system: Microsoft Windows NT 10.0.22621.0 64 bit
    GPU name: NVIDIA GeForce RTX 3050 Laptop GPU
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') (System.ArgumentOutOfRangeException)
Target site: Void ThrowArgumentOutOfRange_IndexException()
Stack trace: 
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
   at Barotrauma.ItemSlotIndexPair.FindItemInContainer(ItemContainer container) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CircuitBox\ItemSlotIndexPair.cs:line 42
   at Barotrauma.CircuitBoxComponent.TryLoadFromXML(ContentXElement element, CircuitBox circuitBox) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CircuitBox\CircuitBoxComponent.cs:line 46
   at Barotrauma.Items.Components.CircuitBox.LoadFromXML(ContentXElement loadElement) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Signal\CircuitBox.cs:line 164
   at Barotrauma.Items.Components.CircuitBox.TryInitializeNodes() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Signal\CircuitBox.cs:line 155
   at Barotrauma.Items.Components.CircuitBox.OnMapLoaded() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Signal\CircuitBox.cs:line 148
   at Barotrauma.Item.OnMapLoaded() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 4007
   at Barotrauma.MapEntity.MapLoaded(List`1 entities, Boolean updateHulls) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 814
   at Barotrauma.Submarine..ctor(SubmarineInfo info, Boolean showErrorMessages, Func`2 loadEntities, IdRemap linkedRemap) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Submarine.cs:line 1616
   at Barotrauma.GameSession.StartRound(LevelData levelData, Boolean mirrorLevel, SubmarineInfo startOutpost, SubmarineInfo endOutpost) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 433
   at Barotrauma.CampaignMode.<>c__DisplayClass32_0.<<SelectSummaryScreen>b__0>d.MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\CampaignMode.cs:line 298
--- End of stack trace from previous location ---
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 851
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[11/09/2023 22:16:44] Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
   at Barotrauma.ItemSlotIndexPair.FindItemInContainer(ItemContainer container) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CircuitBox\ItemSlotIndexPair.cs:line 42
   at Barotrauma.CircuitBoxComponent.TryLoadFromXML(ContentXElement element, CircuitBox circuitBox) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CircuitBox\CircuitBoxComponent.cs:line 46
   at Barotrauma.Items.Components.CircuitBox.LoadFromXML(ContentXElement loadElement) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Signal\CircuitBox.cs:line 164
   at Barotrauma.Items.Components.CircuitBox.TryInitializeNodes() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Signal\CircuitBox.cs:line 155
   at Barotrauma.Items.Components.CircuitBox.OnMapLoaded() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Signal\CircuitBox.cs:line 148
   at Barotrauma.Item.OnMapLoaded() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 4007
   at Barotrauma.MapEntity.MapLoaded(List`1 entities, Boolean updateHulls) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 814
   at Barotrauma.Submarine..ctor(SubmarineInfo info, Boolean showErrorMessages, Func`2 loadEntities, IdRemap linkedRemap) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Submarine.cs:line 1616
   at Barotrauma.GameSession.StartRound(LevelData levelData, Boolean mirrorLevel, SubmarineInfo startOutpost, SubmarineInfo endOutpost) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 433
   at Barotrauma.Networking.GameServer.StartGame(SubmarineInfo selectedSub, SubmarineInfo selectedShuttle, GameModePreset selectedMode, CampaignSettings settings)+MoveNext() in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Networking\GameServer.cs:line 2292
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 214
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 236
[11/09/2023 22:16:41] Server running slowly (51 updates/s)!
[11/09/2023 22:16:39] Ranford's Undying Spirit
[11/09/2023 22:16:39] Tyson Micheal Petrov
[11/09/2023 22:16:38] Ranford's Undying Spirit
[11/09/2023 22:16:38] Tyson Micheal Petrov
[11/09/2023 22:16:37] Ranford's Undying Spirit
[11/09/2023 22:16:37] Tyson Micheal Petrov
[11/09/2023 21:54:42] Ranford's Undying Spirit
[11/09/2023 21:54:42] Tyson Micheal Petrov
[11/09/2023 21:54:39] Ranford's Undying Spirit
[11/09/2023 21:54:39] Tyson Micheal Petrov
[11/09/2023 21:54:38] Received STARTGAMEFINALIZE packet. Round init status: Started
[11/09/2023 21:54:38] Task count: 0
[11/09/2023 21:54:38] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[11/09/2023 21:54:33] Generating an outpost for the start of the level... (Location: Kimju Institute of Astrobiology, level type: Outpost)
[11/09/2023 21:54:33] Level identifier: ridgeoutpost
[11/09/2023 21:54:24] Ranford's Undying Spirit
[11/09/2023 21:54:24] Tyson Micheal Petrov
[11/09/2023 21:54:23] Ranford's Undying Spirit
[11/09/2023 21:54:23] Tyson Micheal Petrov
[11/09/2023 21:54:23] Ranford's Undying Spirit
[11/09/2023 21:54:23] Tyson Micheal Petrov
[11/09/2023 21:54:14] WARNING: Received a potentially invalid ENTITY_POSITION message.Entity identifier does not match (server entity is chaingunboltshredder, client entity is coilgunboltpiercing). Ignoring the message...
[11/09/2023 21:52:40] WARNING: Received a potentially invalid ENTITY_POSITION message.Entity identifier does not match (server entity is chaingunboltshredder, client entity is coilgunbolt). Ignoring the message...
[11/09/2023 21:40:43] Server running slowly (56 updates/s)!
[11/09/2023 21:40:37] Ranford's Undying Spirit
[11/09/2023 21:40:37] Tyson Micheal Petrov
[11/09/2023 21:40:35] Ranford's Undying Spirit
[11/09/2023 21:40:35] Tyson Micheal Petrov
[11/09/2023 21:40:35] Received STARTGAMEFINALIZE packet. Round init status: Started
[11/09/2023 21:40:34] Task count: 0
[11/09/2023 21:40:34] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[11/09/2023 21:40:32] Generating an outpost for the end of the level... (Location: Kimju Institute of Astrobiology, level type: LocationConnection)
[11/09/2023 21:40:32] Generating an outpost for the start of the level... (Location: Phocis Flexus Mining Facility, level type: LocationConnection)
[11/09/2023 21:40:32] Level identifier: ridgebasic
[11/09/2023 21:40:22] Server running slowly (56 updates/s)!
[11/09/2023 21:40:13] Ranford's Undying Spirit
[11/09/2023 21:40:13] Tyson Micheal Petrov
[11/09/2023 21:36:51] Server running slowly (56 updates/s)!
[11/09/2023 21:36:45] Ranford's Undying Spirit
[11/09/2023 21:36:45] Tyson Micheal Petrov
[11/09/2023 21:36:43] Ranford's Undying Spirit
[11/09/2023 21:36:43] Tyson Micheal Petrov
[11/09/2023 21:36:43] Received STARTGAMEFINALIZE packet. Round init status: Started
[11/09/2023 21:36:42] Task count: 0
[11/09/2023 21:36:42] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[11/09/2023 21:36:40] Generating an outpost for the end of the level... (Location: Kimju Institute of Astrobiology, level type: LocationConnection)
[11/09/2023 21:36:40] Generating an outpost for the start of the level... (Location: Phocis Flexus Mining Facility, level type: LocationConnection)
[11/09/2023 21:36:40] Level identifier: ridgebasic
[11/09/2023 21:36:29] Server running slowly (57 updates/s)!
[11/09/2023 21:36:22] Ranford's Undying Spirit
[11/09/2023 21:36:22] Tyson Micheal Petrov
[11/09/2023 21:31:26] Server running slowly (54 updates/s)!
[11/09/2023 21:31:24] Ranford's Undying Spirit
[11/09/2023 21:31:24] Tyson Micheal Petrov
[11/09/2023 21:31:22] Ranford's Undying Spirit
[11/09/2023 21:31:22] Tyson Micheal Petrov
[11/09/2023 21:31:21] Received STARTGAMEFINALIZE packet. Round init status: Started
[11/09/2023 21:31:19] Task count: 0
[11/09/2023 21:31:19] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[11/09/2023 21:31:17] Generating an outpost for the end of the level... (Location: Kimju Institute of Astrobiology, level type: LocationConnection)
[11/09/2023 21:31:16] Generating an outpost for the start of the level... (Location: Phocis Flexus Mining Facility, level type: LocationConnection)
[11/09/2023 21:31:16] Level identifier: ridgebasic
[11/09/2023 21:28:34] Lobby created!
```

**Comment by Regalis11** [comment] 2023-11-10 08:18
Thank you for the report!

I gave this a test, trying to follow the steps exactly, but unfortunately I couldn't get the crash to occur. Would it be possible to send us the save file in case it could give us some extra clues? Note that you need to .zip it first because github doesn't allow attaching files with the .save file extension. Thanks and sorry for the inconvenience!

**Comment by RealLordzombieboy** [comment] 2023-11-10 14:32
Of course! Here's the zip. I'll try to replicate it in a different world soon and write the exact steps I took if that's needed.
[Last Men Standing.zip](https://github.com/Regalis11/Barotrauma/files/13320385/Last.Men.Standing.zip)

**Comment by juanjp600** [comment] 2023-11-14 20:04
I believe I have managed to narrow down the repro steps somewhat, here's what I found:
- Start a brand new singleplayer campaign (these steps probably also work for multiplayer but this is easier)
- Go into an outpost with a submarine salesman
- Spawn a circuit box and some FPGA circuits in the player's inventory
- Place the circuit box, add any component and attach a wire from an input pin and to output pin
- Take the circuit box off the wall
- Spawn a metal crate
- Place the circuit box in the metal crate and drop the crate inside of the submarine
- Use the money command to give yourself some big number
- Purchase and switch to a new submarine, making sure that the "Transfer items" checkbox is ticked
- Leave the outpost

Here's a way to get the error with a pre-existing circuit box:
- Have a circuit box in a player's inventory
- Enter an outpost
- Put the player's circuit box inside of a metal crate and drop the crate inside of the submarine
- Switch submarine, making sure to transfer items
- Leave the outpost

It seems like the issue is in transferring circuit boxes that didn't exist in the last saved instance of the current submarine.

**Comment by 3e849f2e5c** [comment] 2023-11-27 11:34
Followed Juan's steps and wasn't able to repro

**Comment by Jasontti** [comment] 2023-11-29 12:08
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4707/commits/2178f42da9734cc9c49168d80315cdd4d8dbe37a

Tried the repro steps
Tested with known corrupting saves
Tested old corrupting steps
Placed CB in attached shuttles and switched subs and back again, with inventory and without

No issues found
Closing ticket

**Closed by Jasontti** 2023-11-29 12:08 UTC
Labels: Bug, Code, Crash, Severe
