### ISSUE TITLE
[0.9.10.0] Bots forgotten how to take tools out of their toolbox to handle tasks

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2818] opened 2020-05-13 19:09 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots forgotten how to take tools out of their toolbox to handle tasks. I had a fresh Mechanic struggling to fix a leak, but my engineer who was free found a welding tool and fixed the leak instead. The engineer struggles to repair things because his wrench and screwdrivers are left in the toolbox.

**Version**
0.9.10.0

**Comment by Regalis11** [comment] 2020-05-14 08:41
Could not reproduce

**Comment by Kaillera** [comment] 2020-05-14 10:33
Hmm I can't repro the wrench screwdriver anymore either

**Comment by Kaillera** [comment] 2020-05-18 13:38
[0.9.1001.0] Haven't had any issues since.

**Comment by Rokvach** [comment] 2020-05-18 13:51
Closing

**Closed by Rokvach** 2020-05-18 13:51 UTC
Labels: Bug, Code
