### ISSUE TITLE
Bots get stuck on this ladder (city outpost, EngineeringModule_02_Colony)

### ISSUE THREAD

**Issue by coffeemakesme** [Regalis11/Barotrauma#10426] opened 2022-11-17 18:21 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

https://user-images.githubusercontent.com/83150595/202524419-a9b6796d-d51a-4e7f-8b1d-c71fc9fb84b4.mp4

![image](https://user-images.githubusercontent.com/83150595/202524582-dfed0c21-6174-4f4f-a2f6-6adc70cd4458.png)

[Save 1.zip](https://github.com/Regalis11/Barotrauma/files/10034448/Save.1.zip)

### Reproduction steps

walk left until you reach this module,

wait like 15 minutes, some of them get stuck; the top npc got stuck going down, the bottom npc was trying to go up

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment] 2023-01-23 09:12
Hmm, it's difficult to repro the issue without knowing the exact version of the build, because the layout of the outposts can change. It would help, if you could give the exact version of the build you were playing with.

**Comment by itchyOwl** [comment] 2023-01-26 15:30
Nvm, they seem to get stuck on the ladder regardless of the module structure. Looking into it.

**Comment by itchyOwl** [comment] 2023-01-27 08:12
The waypoints on the module (EngineeringModule_02_Colony) seems to be broken: ![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/75442f62-6aed-465f-9060-505ae75f1b6e). Regenerated (the generator doesn't seem to like the module) and manually adjusted in Regalis11/Barotrauma-development@ef59792 (wip-fixes-january). Also checked the other colony modules, found and fixed some issues in ResidentalModule_01_Colony. Others seemed to be fine.

On testing: check that a bot can follow you to where it should be able to get.

**Comment by NilanthAnimosus** [comment] 2023-02-06 14:24
Tested against Fix/wip-fixes-january commit https://github.com/Regalis11/Barotrauma-development/commit/a1f14c233cf50eb6f5b632d68103db2483f6f4ab, no issues found, closing.

**Comment by itchyOwl** [comment] 2023-02-23 19:27
Seems to not been fixed, reopening: ![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/334c8d1f-8ef1-4844-85e5-820c56063231)

**Comment by itchyOwl** [comment] 2023-02-23 19:33
As a clarification: the bots don't always get stuck there, but one way to repro it reliably(?) is to make a bot follow you, and go down that ladder. The bot should get stuck near the hatch, at least for a while. Doesn't get stuck when going up. Curiously there's two npcs stuck there at different points of the ladder, and they seem to be permanently stuck there. Can't spot anything wrong with the waypoints, so have to debug it.

**Comment by itchyOwl** [comment] 2023-02-24 10:52
Possibly related (Barsuk):
![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/c3c78adb-e9c8-43d5-a8c7-e9b975c8a217)

**Comment by itchyOwl** [comment] 2023-02-27 08:15
Also here: ![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/0daabb66-3a43-42f2-935d-ec3deee297a7)

**Comment by itchyOwl** [comment] 2023-02-27 08:16
And here (this is easy to repro by making the bot to follow you): ![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/63accec7-4019-4cf7-9c4d-1ab52c66dff5)

**Comment by itchyOwl** [comment] 2023-02-28 12:39
Also occasionally here (Herja connected to an outpost):![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/aa49de10-a0ed-462f-88d4-2c48ad730fb6)

**Comment by itchyOwl** [comment] 2023-04-14 17:14
There's a couple of fixes to this, but the most specific is Regalis11/Barotrauma-development@bce236b180dae39b91f576de25eae329fd5ce99b, which fixes a waypoint link in the ladders mentioned in the original post.

Can be reproduced in this save: [https://app.zenhub.com/files/93301055/c7d2b18d-f64d-4f35-8678-9a6519119236/download](https://app.zenhub.com/files/93301055/c7d2b18d-f64d-4f35-8678-9a6519119236/download)

Should be fixed in this save: [https://app.zenhub.com/files/93301055/1561a703-6767-404d-a1c8-05355a327efa/download](https://app.zenhub.com/files/93301055/1561a703-6767-404d-a1c8-05355a327efa/download)

**Comment by Rokvach** [comment] 2023-04-26 08:38
Tested, working correctly. Closing.

**Closed by Rokvach** 2023-04-26 08:38 UTC
Labels: Bug
