### ISSUE TITLE
Linux server critical bug: kicking players for missing entities

### ISSUE THREAD

**Issue by Panzergrenadier** [Regalis11/Barotrauma#964] opened 2018-12-06 13:14 UTC
Everyone on server getting kicked for random missing entity or just desync. It hapens right after the game start. Same bug for smaller/larger submarines.

Some system info:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"
4-core CPU
8GB RAM
Barotrauma v0.8.2.2

Another bug: target creatures don't spawn in "Monster" mission sometimes. Linux-only bug.

![kick reason](https://user-images.githubusercontent.com/23261711/49586340-79933780-f993-11e8-96a4-c6aef8f172f7.png)

**Comment by Regalis11** [comment] 2018-12-06 14:47
Duplicate of #848

**Closed by Regalis11** 2018-12-06 14:47 UTC
Labels: Linux only, bug
