### ISSUE TITLE
Fractal Guardian sometimes Invisble after breaking its pod

### ISSUE THREAD

**Issue by Notmaximluenenstrass** [Regalis11/Barotrauma#11635] opened 2023-03-22 09:41 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The other day I was doing a clear ruin mission. At first all went normal, found a Fractal Guardian, shot it until it retreated to the nearest pod. I followed it and deactivated the pod, however the guardian did not apear as usual. I could hear it, I could certanly feel it as it dragged me around. However I could not see it. This made fighting the thing extremely difficult as i had to track it down by the red shimmer coming from its eye and then axe it to death. Whats even more strange, is that after I returned to the room the corpse just suddenly appeared.

Luckily this happened to me only ones in campain and rarely on a private server.

### Reproduction steps

1.Start campain or Server
2.Go on any Ruin mission, preferably clear ruin because of the amount of guardians
3.Hurt a guardian and follow it to its pod
4.Open its pod with alien trinklet
5.Observe

### Bug prevalence

Happens every now and then

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment] 2023-03-28 12:19
Possibly mp only?

**Comment by Notmaximluenenstrass** [comment] 2023-03-28 12:48
No I was on Singleplayer when I first encountered the bug.

**Comment by NilanthAnimosus** [comment] 2023-05-30 10:13
Thanks for the report!

Tested on 1.0.13.2 - couldn't reproduce the mentioned issues.

In single player only the tail hides (And reappears after breaking the pod or it finishes healing), on multiplayer it fails to hide any limbs, and always comes out fully visible.

Both methods of breaking the pod (via trinket and via damage) were used, and neither on each guardian type were they invisible.

**Comment by Regalis11** [comment] 2023-08-23 11:56
No known steps to repro, closing

**Closed by Regalis11** 2023-08-23 11:56 UTC
Labels: Bug, Need more info, Code
