### ISSUE TITLE
crash while being attacked by terminal cells ('collection was modified' in Explosion.RangedStructureDamage)

### ISSUE THREAD

**Issue by Aluriak** [Regalis11/Barotrauma#12222] opened 2023-06-24 07:08 UTC
[save.zip](https://github.com/Regalis11/Barotrauma/files/11855825/save.zip)
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While being attacked by exploding red blobs, at some point (after few waves of them) the game crashes.

Happened twice, exactly at the same spot (just above a dereclict, during red blobs attack)

Please find attached two reports obtained yesterday and today.

I don't use any mod.

### Reproduction steps

I will try to upload my save. To reproduce the bug, just go to the dereclict around 400m away the starting outpost and fight against red blobs. (it's the first time i encounter them, so i don't know how to fight them efficiently).

### Bug prevalence

Happens every time I play

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Linux

### Relevant error messages and crash reports

```shell
﻿Barotrauma Client crash report (generated on 06/23/2023 15:19:51)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

057E2149B622BA1BCD1B40F5FC8DEA50

Game version 1.0.21.0 (ReleaseLinux, branch release/summer-patch-hotfix, revision adb80ccd6e)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: French
Selected content packages: Vanilla (65E9331)
Level seed: Thaw64Kermario Fossa107
Loaded submarine: Azimuth (189F4A53F6B5DDC09DFC0CE898902B57)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Unix 6.1.31.2 64 bit
    GPU name: 
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Collection was modified; enumeration operation may not execute. (System.InvalidOperationException)
Target site: Void ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
Stack trace: 
   at Barotrauma.Explosion.RangedStructureDamage(Vector2 worldPosition, Single worldRange, Single damage, Single levelWallDamage, Character attacker, IEnumerable`1 ignoredSubmarines, Boolean emitWallDamageParticles) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Explosion.cs:line 649
   at Barotrauma.Explosion.Explode(Vector2 worldPosition, Entity damageSource, Character attacker) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Explosion.cs:line 252
   at Barotrauma.StatusEffect.Apply(Single deltaTime, Entity entity, IReadOnlyList`1 targets, Nullable`1 worldPosition) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\StatusEffects\StatusEffect.cs:line 1652
   at Barotrauma.StatusEffect.Apply(ActionType type, Single deltaTime, Entity entity, ISerializableEntity target, Nullable`1 worldPosition) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\StatusEffects\StatusEffect.cs:line 1383
   at Barotrauma.Character.ApplyStatusEffects(ActionType actionType, Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 4355
   at Barotrauma.Character.Kill(CauseOfDeathType causeOfDeath, Affliction causeOfDeathAffliction, Boolean isNetworkMessage, Boolean log) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 4455
   at Barotrauma.CharacterHealth.Kill() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\CharacterHealth.cs:line 1019
   at Barotrauma.CharacterHealth.AddLimbAffliction(LimbHealth limbHealth, Affliction newAffliction, Boolean allowStacking) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\CharacterHealth.cs:line 768
   at Barotrauma.CharacterHealth.AddLimbAffliction(Limb limb, Affliction newAffliction, Boolean allowStacking) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\CharacterHealth.cs:line 700
   at Barotrauma.CharacterHealth.ApplyDamage(Limb hitLimb, AttackResult attackResult, Boolean allowStacking) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\CharacterHealth.cs:line 591
   at Barotrauma.Character.DamageLimb(Vector2 worldPosition, Limb hitLimb, IEnumerable`1 afflictions, Single stun, Boolean playSound, Single attackImpulse, Character attacker, Single damageMultiplier, Boolean allowStacking, Single penetration, Boolean shouldImplode) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 4164
   at Barotrauma.Character.AddDamage(Vector2 worldPosition, IEnumerable`1 afflictions, Single stun, Boolean playSound, Single attackImpulse, Limb& hitLimb, Character attacker, Single damageMultiplier) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 4057
   at Barotrauma.Explosion.DamageCharacters(Vector2 worldPosition, Attack attack, Single force, Entity damageSource, Character attacker) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Explosion.cs:line 517
   at Barotrauma.Explosion.Explode(Vector2 worldPosition, Entity damageSource, Character attacker) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Explosion.cs:line 366
   at Barotrauma.Structure.CreateWallDamageExplosion(Gap gap, Character attacker) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Structure.cs:line 1281
   at Barotrauma.Structure.SetDamage(Int32 sectionIndex, Single damage, Character attacker, Boolean createNetworkEvent, Boolean isNetworkEvent, Boolean createExplosionEffect) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Structure.cs:line 1089
   at Barotrauma.Structure.AddDamage(Int32 sectionIndex, Single damage, Character attacker, Boolean emitParticles) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Structure.cs:line 948
   at Barotrauma.Explosion.RangedStructureDamage(Vector2 worldPosition, Single worldRange, Single damage, Single levelWallDamage, Character attacker, IEnumerable`1 ignoredSubmarines, Boolean emitWallDamageParticles) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Explosion.cs:line 616
   at Barotrauma.Explosion.Explode(Vector2 worldPosition, Entity damageSource, Character attacker) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Explosion.cs:line 252
   at Barotrauma.StatusEffect.Apply(Single deltaTime, Entity entity, IReadOnlyList`1 targets, Nullable`1 worldPosition) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\StatusEffects\StatusEffect.cs:line 1652
   at Barotrauma.StatusEffect.Apply(ActionType type, Single deltaTime, Entity entity, ISerializableEntity target, Nullable`1 worldPosition) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\StatusEffects\StatusEffect.cs:line 1383
   at Barotrauma.Character.ApplyStatusEffects(ActionType actionType, Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 4355
   at Barotrauma.Character.Kill(CauseOfDeathType causeOfDeath, Affliction causeOfDeathAffliction, Boolean isNetworkMessage, Boolean log) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 4455
   at Barotrauma.CharacterHealth.Kill() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\CharacterHealth.cs:line 1019
   at Barotrauma.CharacterHealth.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\CharacterHealth.cs:line 871
   at Barotrauma.Character.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 3166
   at Barotrauma.AICharacter.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AICharacter.cs:line 76
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 3015
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 186
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 884
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[06/23/2023 14:58:10] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: saferoom), skipping.
[06/23/2023 14:58:10] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
[06/23/2023 14:57:47] Generating an outpost for the start of the level... (Location: Concession minière Thaw, level type: LocationConnection)
[06/23/2023 14:57:43] Generating an outpost for the end of the level... (Location: Institut d'astrobiologie Kermario Fossa, level type: LocationConnection)
[06/23/2023 14:57:39] Level identifier: ridgebasic
[06/23/2023 14:57:11] Transitioning to Thaw64Kermario Fossa107 (current location: Institut d'astrobiologie Kermario Fossa, selected location: Concession minière Thaw, leaving sub: Azimuth, at start: True, at end: False, transition type: LeaveLocation)
[06/23/2023 14:44:06] Unlocked mission "Transport d'adeptes" in the connection from "Institut d'astrobiologie Kermario Fossa" to "Concession minière Thaw".
[06/23/2023 14:42:07] Unlocked mission "Vaisseau séparatiste" in the connection from "Institut d'astrobiologie Kermario Fossa" to "Concession minière Thaw".
[06/23/2023 14:42:04] Unlocked mission "Extraction de : Thorianite" in the connection from "Institut d'astrobiologie Kermario Fossa" to "Concession minière Thaw".
[06/23/2023 14:42:01] Unlocked mission "Extraction de minéraux" in the connection from "Institut d'astrobiologie Kermario Fossa" to "Concession minière Thaw".
[06/23/2023 14:41:58] Unlocked mission "Destruction d'un nid de raptor fangeux" in the connection from "Institut d'astrobiologie Kermario Fossa" to "Installation de recherche Soggoth Crevasse".
[06/23/2023 14:37:05] Generating an outpost for the start of the level... (Location: Institut d'astrobiologie Kermario Fossa, level type: Outpost)
[06/23/2023 14:37:05] Level identifier: ridgeoutpost
[06/23/2023 14:36:08] Attempting to open ALC device "Built-in Audio Analog Stereo"
[06/23/2023 14:36:02] Logged in as lucas (SteamID STEAM_1:0:32733291)


_________________________________________________


﻿Barotrauma Client crash report (generated on 06/24/2023 08:55:53)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

057E2149B622BA1BCD1B40F5FC8DEA50

Game version 1.0.21.0 (ReleaseLinux, branch release/summer-patch-hotfix, revision adb80ccd6e)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: French
Selected content packages: Vanilla (65E9331)
Level seed: Thaw64Kermario Fossa107
Loaded submarine: Azimuth (102BD54859F2FEFF362F96D0DD29A21D)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Unix 6.1.31.2 64 bit
    GPU name: 
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Collection was modified; enumeration operation may not execute. (System.InvalidOperationException)
Target site: Void ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
Stack trace: 
   at Barotrauma.Explosion.RangedStructureDamage(Vector2 worldPosition, Single worldRange, Single damage, Single levelWallDamage, Character attacker, IEnumerable`1 ignoredSubmarines, Boolean emitWallDamageParticles) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Explosion.cs:line 649
   at Barotrauma.Explosion.Explode(Vector2 worldPosition, Entity damageSource, Character attacker) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Explosion.cs:line 252
   at Barotrauma.StatusEffect.Apply(Single deltaTime, Entity entity, IReadOnlyList`1 targets, Nullable`1 worldPosition) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\StatusEffects\StatusEffect.cs:line 1652
   at Barotrauma.StatusEffect.Apply(ActionType type, Single deltaTime, Entity entity, ISerializableEntity target, Nullable`1 worldPosition) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\StatusEffects\StatusEffect.cs:line 1383
   at Barotrauma.Character.ApplyStatusEffects(ActionType actionType, Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 4355
   at Barotrauma.Character.Kill(CauseOfDeathType causeOfDeath, Affliction causeOfDeathAffliction, Boolean isNetworkMessage, Boolean log) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 4455
   at Barotrauma.CharacterHealth.Kill() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\CharacterHealth.cs:line 1019
   at Barotrauma.CharacterHealth.AddLimbAffliction(LimbHealth limbHealth, Affliction newAffliction, Boolean allowStacking) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\CharacterHealth.cs:line 768
   at Barotrauma.CharacterHealth.AddLimbAffliction(Limb limb, Affliction newAffliction, Boolean allowStacking) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\CharacterHealth.cs:line 700
   at Barotrauma.CharacterHealth.ApplyDamage(Limb hitLimb, AttackResult attackResult, Boolean allowStacking) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\CharacterHealth.cs:line 591
   at Barotrauma.Character.DamageLimb(Vector2 worldPosition, Limb hitLimb, IEnumerable`1 afflictions, Single stun, Boolean playSound, Single attackImpulse, Character attacker, Single damageMultiplier, Boolean allowStacking, Single penetration, Boolean shouldImplode) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 4164
   at Barotrauma.Character.AddDamage(Vector2 worldPosition, IEnumerable`1 afflictions, Single stun, Boolean playSound, Single attackImpulse, Limb& hitLimb, Character attacker, Single damageMultiplier) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 4057
   at Barotrauma.Explosion.DamageCharacters(Vector2 worldPosition, Attack attack, Single force, Entity damageSource, Character attacker) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Explosion.cs:line 517
   at Barotrauma.Explosion.Explode(Vector2 worldPosition, Entity damageSource, Character attacker) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Explosion.cs:line 366
   at Barotrauma.Structure.CreateWallDamageExplosion(Gap gap, Character attacker) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Structure.cs:line 1281
   at Barotrauma.Structure.SetDamage(Int32 sectionIndex, Single damage, Character attacker, Boolean createNetworkEvent, Boolean isNetworkEvent, Boolean createExplosionEffect) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Structure.cs:line 1089
   at Barotrauma.Structure.AddDamage(Int32 sectionIndex, Single damage, Character attacker, Boolean emitParticles) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Structure.cs:line 948
   at Barotrauma.Explosion.RangedStructureDamage(Vector2 worldPosition, Single worldRange, Single damage, Single levelWallDamage, Character attacker, IEnumerable`1 ignoredSubmarines, Boolean emitWallDamageParticles) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Explosion.cs:line 616
   at Barotrauma.Explosion.Explode(Vector2 worldPosition, Entity damageSource, Character attacker) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Explosion.cs:line 252
   at Barotrauma.StatusEffect.Apply(Single deltaTime, Entity entity, IReadOnlyList`1 targets, Nullable`1 worldPosition) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\StatusEffects\StatusEffect.cs:line 1652
   at Barotrauma.StatusEffect.Apply(ActionType type, Single deltaTime, Entity entity, ISerializableEntity target, Nullable`1 worldPosition) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\StatusEffects\StatusEffect.cs:line 1383
   at Barotrauma.Character.ApplyStatusEffects(ActionType actionType, Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 4355
   at Barotrauma.Character.Kill(CauseOfDeathType causeOfDeath, Affliction causeOfDeathAffliction, Boolean isNetworkMessage, Boolean log) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 4455
   at Barotrauma.CharacterHealth.Kill() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\CharacterHealth.cs:line 1019
   at Barotrauma.CharacterHealth.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\CharacterHealth.cs:line 871
   at Barotrauma.Character.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 3166
   at Barotrauma.AICharacter.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AICharacter.cs:line 76
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 3015
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 186
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 884
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[06/24/2023 08:36:43] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: saferoom), skipping.
[06/24/2023 08:36:43] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
[06/24/2023 08:36:23] Generating an outpost for the start of the level... (Location: Concession minière Thaw, level type: LocationConnection)
[06/24/2023 08:36:22] Generating an outpost for the end of the level... (Location: Institut d'astrobiologie Kermario Fossa, level type: LocationConnection)
[06/24/2023 08:36:21] Level identifier: ridgebasic
[06/24/2023 08:34:52] Attempting to open ALC device "Built-in Audio Analog Stereo"
[06/24/2023 08:34:43] Logged in as lucas (SteamID STEAM_1:0:32733291)
```

**Comment by Regalis11** [comment] 2023-06-25 11:57
Thank you for the report! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0099481d50a5062bfb804c9cc8eb86571ec38ce4 (commit in our private repo).

> Fixed "collection was modified" exception in Explosion.RangedStructureDamage. If structure damage triggered an explosion that caused more structure damage, we'd end up modifying the `damagedStructureList` while enumerating it. Could happen e.g. when wall damage explosion kills a terminal cell, which explodes and causes more wall damage.

**Comment by Aluriak** [comment] 2023-06-25 12:53
Thank YOU for fixing that bug !

Should i expect that bugfix to arrive soon on my steam installation ?

**Comment by Regalis11** [comment] 2023-06-26 06:45
> Should i expect that bugfix to arrive soon on my steam installation ?

Not yet, we'll still need to review and test it internally until it's ready to be included in the next release, and I unfortunately can't give you an ETA on when the next update/patch is going to go out yet.

**Comment by Aluriak** [comment] 2023-06-26 15:25
No problem, i will avoid that area for the moment. Thank you !

**Comment by Regalis11** [comment] 2023-06-27 11:28
Thank you for taking the time to close the ticket, but we'll keep it open until we've tested the fix internally and verified it's working as intended. :)

**Closed** 2023-06-30 08:42 UTC
Labels: Bug, Code, Crash, Severe
