### ISSUE TITLE
About the new pet

### ISSUE THREAD

**Issue by EgggWang** [Regalis11/Barotrauma#11638] opened 2023-03-22 19:37 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In hostile locations, the ai is treated as an enemy by the new pet
[1.zip](https://github.com/Regalis11/Barotrauma/files/11043996/1.zip)

### Reproduction steps

[1.zip](https://github.com/Regalis11/Barotrauma/files/11044039/1.zip)
Arrive at a hostile site， This is my save

### Bug prevalence

Just once

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-03-22 22:08
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11514

**Closed by Regalis11** 2023-03-22 22:08 UTC
