### ISSUE TITLE
Same IP, Different Ports, Server not Listed

### ISSUE THREAD

**Issue by Verazon** [Regalis11/Barotrauma#8464] opened 2022-03-06 19:13 UTC
Server List does not show 2 servers which are hosted from the same IP

I started 2 servers one for players to play and a second one for testing from a dedicated host.
The IP is the same as the server box but the Port and Query Port is differentiates from Server 1 and 2 completely.
lets say Server 1 is Port:27015 Query:27016
The server works and shows.
I turn on Server 2 with the following Port:27017 Query:27018

it shows for a brief moment but I cannot see them both at the same time, even if I favourite them both.
and if I am on Server 2 and I invite someone through Steam Chat to join, they will connect to Server 1.

**Comment by Regalis11** [comment] 2022-03-14 08:39
Duplicate of https://github.com/Regalis11/Barotrauma/issues/6412

**Closed by Regalis11** 2022-03-14 08:39 UTC
