### ISSUE TITLE
NPC Crew members can take off locked items

### ISSUE THREAD

**Issue by SquidingTin** [Regalis11/Barotrauma#12130] opened 2023-06-07 01:49 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

As the title says, if you changed off of a NPC that has a diving suit with the tag `nonplayerteaminteractable="True"`  it somehow takes it off, even though your not meant to be able to do that.

### Reproduction steps

1. Make diving suit with the tag `nonplayerteaminteractable="True"`
2. Make NPC wear it
3. Results

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment] 2023-06-07 15:34
I'm not sure I understand the issue here. The "NonPlayerTeamInteractable" attribute is meant to define that only characters _not_ in the player team can interact with the item. In other words: only NPCs (not bots in the player crew) and the monsters can interact with the item. In the vanilla content we've at least used it with some alien items, like the Fractalguardian's weapons, and on the outpost reactors.

In case you meant that bots can use the items when they shouldn't, I gave it a quick test with the following steps:

- Opened Humpback in the sub editor
- Disabled "Auto Fill" for all the diving suit lockers
- Placed one diving suit and enabled  "Non Player Team Interactable"
- Tried flooding the sub and by telling a bot to prepare for an expedition.
- Neither me nor the bots could interact with the item, as intended.

![image](https://github.com/Regalis11/Barotrauma/assets/5370738/64d19808-f82e-4d4b-8e90-965fc125fc61)
![image](https://github.com/Regalis11/Barotrauma/assets/5370738/f8a257b8-c5b7-4255-832b-f6146b6cfc8f)
![image](https://github.com/Regalis11/Barotrauma/assets/5370738/6076328f-0c89-4fe4-b67c-e4569984b301)

**Comment by Regalis11** [comment] 2023-07-10 11:41
No known steps to repro, closing

**Closed by Regalis11** 2023-07-10 11:41 UTC
Labels: Need more info
