### ISSUE TITLE
101th crash so far through 45+ hours of gameplay.  [BUG]

### ISSUE THREAD

**Issue by VenipedeGaming** [Regalis11/Barotrauma#2775] opened 2020-05-05 23:54 UTC
- [ ] I have searched the issue tracker to check if the issue has already been reported.
Sorry, sorry, its just that there's so many crash reports to go through and I cant tell if all 101 of them have been reported or not. I haven't searched through  #at all and I'm a bit desperate, sorry.

**Description**
So far I've had 101 crashes, and I can't seem to figure out what the issue is. I have a folder of all of my crashes

**Steps To Reproduce**
Unsure how to reproduce all 101 crashes, they seem to occur randomly, sometimes I can play just fine, other times I seem to be crashing almost 2 times per hour, giving me only 30 minutes to enjoy the game.

**Version**
v0.9.9.0 of Barotrauma, and I am running the game on Windows 10.

**Additional information**
I've tried reinstalling 2 times, and verifying the game files 4 times. I'm not sure if its  mods though, and could use help to confirm whether or not it is the case. I have my graphics drivers up to date as well.

[crashreport (100).log](https://github.com/Regalis11/Barotrauma/files/4584205/crashreport.100.log)
[crashreport (101).log](https://github.com/Regalis11/Barotrauma/files/4584206/crashreport.101.log)
[crashreport (102).log](https://github.com/Regalis11/Barotrauma/files/4584207/crashreport.102.log)
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/4584208/crashreport.log)
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/4584209/crashreport.2.log)
[crashreport (3).log](https://github.com/Regalis11/Barotrauma/files/4584210/crashreport.3.log)
[crashreport (4).log](https://github.com/Regalis11/Barotrauma/files/4584211/crashreport.4.log)
[crashreport (5).log](https://github.com/Regalis11/Barotrauma/files/4584212/crashreport.5.log)
[crashreport (6).log](https://github.com/Regalis11/Barotrauma/files/4584213/crashreport.6.log)
[crashreport (7).log](https://github.com/Regalis11/Barotrauma/files/4584214/crashreport.7.log)
[crashreport (8).log](https://github.com/Regalis11/Barotrauma/files/4584215/crashreport.8.log)
[crashreport (9).log](https://github.com/Regalis11/Barotrauma/files/4584216/crashreport.9.log)
[crashreport (10).log](https://github.com/Regalis11/Barotrauma/files/4584217/crashreport.10.log)
[crashreport (11).log](https://github.com/Regalis11/Barotrauma/files/4584218/crashreport.11.log)
[crashreport (12).log](https://github.com/Regalis11/Barotrauma/files/4584219/crashreport.12.log)
[crashreport (13).log](https://github.com/Regalis11/Barotrauma/files/4584220/crashreport.13.log)
[crashreport (14).log](https://github.com/Regalis11/Barotrauma/files/4584221/crashreport.14.log)
[crashreport (15).log](https://github.com/Regalis11/Barotrauma/files/4584222/crashreport.15.log)
[crashreport (16).log](https://github.com/Regalis11/Barotrauma/files/4584223/crashreport.16.log)
[crashreport (17).log](https://github.com/Regalis11/Barotrauma/files/4584224/crashreport.17.log)
[crashreport (18).log](https://github.com/Regalis11/Barotrauma/files/4584225/crashreport.18.log)
[crashreport (19).log](https://github.com/Regalis11/Barotrauma/files/4584226/crashreport.19.log)
[crashreport (20).log](https://github.com/Regalis11/Barotrauma/files/4584227/crashreport.20.log)
[crashreport (21).log](https://github.com/Regalis11/Barotrauma/files/4584228/crashreport.21.log)
[crashreport (22).log](https://github.com/Regalis11/Barotrauma/files/4584229/crashreport.22.log)
[crashreport (23).log](https://github.com/Regalis11/Barotrauma/files/4584230/crashreport.23.log)
[crashreport (24).log](https://github.com/Regalis11/Barotrauma/files/4584231/crashreport.24.log)
[crashreport (25).log](https://github.com/Regalis11/Barotrauma/files/4584232/crashreport.25.log)
[crashreport (26).log](https://github.com/Regalis11/Barotrauma/files/4584233/crashreport.26.log)
[crashreport (27).log](https://github.com/Regalis11/Barotrauma/files/4584234/crashreport.27.log)
[crashreport (28).log](https://github.com/Regalis11/Barotrauma/files/4584235/crashreport.28.log)
[crashreport (29).log](https://github.com/Regalis11/Barotrauma/files/4584236/crashreport.29.log)
[crashreport (30).log](https://github.com/Regalis11/Barotrauma/files/4584237/crashreport.30.log)
[crashreport (31).log](https://github.com/Regalis11/Barotrauma/files/4584238/crashreport.31.log)
[crashreport (32).log](https://github.com/Regalis11/Barotrauma/files/4584239/crashreport.32.log)
[crashreport (33).log](https://github.com/Regalis11/Barotrauma/files/4584240/crashreport.33.log)
[crashreport (34).log](https://github.com/Regalis11/Barotrauma/files/4584241/crashreport.34.log)
[crashreport (35).log](https://github.com/Regalis11/Barotrauma/files/4584242/crashreport.35.log)
[crashreport (36).log](https://github.com/Regalis11/Barotrauma/files/4584243/crashreport.36.log)
[crashreport (37).log](https://github.com/Regalis11/Barotrauma/files/4584244/crashreport.37.log)
[crashreport (38).log](https://github.com/Regalis11/Barotrauma/files/4584245/crashreport.38.log)
[crashreport (39).log](https://github.com/Regalis11/Barotrauma/files/4584246/crashreport.39.log)
[crashreport (40).log](https://github.com/Regalis11/Barotrauma/files/4584247/crashreport.40.log)
[crashreport (41).log](https://github.com/Regalis11/Barotrauma/files/4584249/crashreport.41.log)
[crashreport (42).log](https://github.com/Regalis11/Barotrauma/files/4584250/crashreport.42.log)
[crashreport (43).log](https://github.com/Regalis11/Barotrauma/files/4584251/crashreport.43.log)
[crashreport (44).log](https://github.com/Regalis11/Barotrauma/files/4584252/crashreport.44.log)
[crashreport (45).log](https://github.com/Regalis11/Barotrauma/files/4584253/crashreport.45.log)
[crashreport (46).log](https://github.com/Regalis11/Barotrauma/files/4584254/crashreport.46.log)
[crashreport (47).log](https://github.com/Regalis11/Barotrauma/files/4584255/crashreport.47.log)
[crashreport (48).log](https://github.com/Regalis11/Barotrauma/files/4584256/crashreport.48.log)
[crashreport (49).log](https://github.com/Regalis11/Barotrauma/files/4584257/crashreport.49.log)
[crashreport (50).log](https://github.com/Regalis11/Barotrauma/files/4584258/crashreport.50.log)
[crashreport (51).log](https://github.com/Regalis11/Barotrauma/files/4584259/crashreport.51.log)
[crashreport (52).log](https://github.com/Regalis11/Barotrauma/files/4584260/crashreport.52.log)
[crashreport (53).log](https://github.com/Regalis11/Barotrauma/files/4584261/crashreport.53.log)
[crashreport (54).log](https://github.com/Regalis11/Barotrauma/files/4584262/crashreport.54.log)
[crashreport (55).log](https://github.com/Regalis11/Barotrauma/files/4584263/crashreport.55.log)
[crashreport (56).log](https://github.com/Regalis11/Barotrauma/files/4584264/crashreport.56.log)
[crashreport (57).log](https://github.com/Regalis11/Barotrauma/files/4584265/crashreport.57.log)
[crashreport (58).log](https://github.com/Regalis11/Barotrauma/files/4584266/crashreport.58.log)
[crashreport (59).log](https://github.com/Regalis11/Barotrauma/files/4584267/crashreport.59.log)
[crashreport (60).log](https://github.com/Regalis11/Barotrauma/files/4584268/crashreport.60.log)
[crashreport (61).log](https://github.com/Regalis11/Barotrauma/files/4584269/crashreport.61.log)
[crashreport (62).log](https://github.com/Regalis11/Barotrauma/files/4584270/crashreport.62.log)
[crashreport (63).log](https://github.com/Regalis11/Barotrauma/files/4584271/crashreport.63.log)
[crashreport (64).log](https://github.com/Regalis11/Barotrauma/files/4584272/crashreport.64.log)
[crashreport (65).log](https://github.com/Regalis11/Barotrauma/files/4584273/crashreport.65.log)
[crashreport (66).log](https://github.com/Regalis11/Barotrauma/files/4584274/crashreport.66.log)
[crashreport (67).log](https://github.com/Regalis11/Barotrauma/files/4584275/crashreport.67.log)
[crashreport (68).log](https://github.com/Regalis11/Barotrauma/files/4584276/crashreport.68.log)
[crashreport (69).log](https://github.com/Regalis11/Barotrauma/files/4584277/crashreport.69.log)
[crashreport (70).log](https://github.com/Regalis11/Barotrauma/files/4584278/crashreport.70.log)
[crashreport (71).log](https://github.com/Regalis11/Barotrauma/files/4584279/crashreport.71.log)
[crashreport (72).log](https://github.com/Regalis11/Barotrauma/files/4584280/crashreport.72.log)
[crashreport (73).log](https://github.com/Regalis11/Barotrauma/files/4584281/crashreport.73.log)
[crashreport (74).log](https://github.com/Regalis11/Barotrauma/files/4584282/crashreport.74.log)
[crashreport (75).log](https://github.com/Regalis11/Barotrauma/files/4584283/crashreport.75.log)
[crashreport (76).log](https://github.com/Regalis11/Barotrauma/files/4584284/crashreport.76.log)
[crashreport (77).log](https://github.com/Regalis11/Barotrauma/files/4584285/crashreport.77.log)
[crashreport (78).log](https://github.com/Regalis11/Barotrauma/files/4584286/crashreport.78.log)
[crashreport (79).log](https://github.com/Regalis11/Barotrauma/files/4584287/crashreport.79.log)
[crashreport (80).log](https://github.com/Regalis11/Barotrauma/files/4584288/crashreport.80.log)
[crashreport (81).log](https://github.com/Regalis11/Barotrauma/files/4584289/crashreport.81.log)
[crashreport (82).log](https://github.com/Regalis11/Barotrauma/files/4584290/crashreport.82.log)
[crashreport (83).log](https://github.com/Regalis11/Barotrauma/files/4584291/crashreport.83.log)
[crashreport (84).log](https://github.com/Regalis11/Barotrauma/files/4584292/crashreport.84.log)
[crashreport (85).log](https://github.com/Regalis11/Barotrauma/files/4584293/crashreport.85.log)
[crashreport (86).log](https://github.com/Regalis11/Barotrauma/files/4584294/crashreport.86.log)
[crashreport (87).log](https://github.com/Regalis11/Barotrauma/files/4584295/crashreport.87.log)
[crashreport (88).log](https://github.com/Regalis11/Barotrauma/files/4584296/crashreport.88.log)
[crashreport (89).log](https://github.com/Regalis11/Barotrauma/files/4584297/crashreport.89.log)
[crashreport (90).log](https://github.com/Regalis11/Barotrauma/files/4584298/crashreport.90.log)
[crashreport (91).log](https://github.com/Regalis11/Barotrauma/files/4584299/crashreport.91.log)
[crashreport (92).log](https://github.com/Regalis11/Barotrauma/files/4584300/crashreport.92.log)
[crashreport (93).log](https://github.com/Regalis11/Barotrauma/files/4584301/crashreport.93.log)
[crashreport (94).log](https://github.com/Regalis11/Barotrauma/files/4584302/crashreport.94.log)
[crashreport (95).log](https://github.com/Regalis11/Barotrauma/files/4584303/crashreport.95.log)
[crashreport (96).log](https://github.com/Regalis11/Barotrauma/files/4584304/crashreport.96.log)
[crashreport (97).log](https://github.com/Regalis11/Barotrauma/files/4584305/crashreport.97.log)
[crashreport (98).log](https://github.com/Regalis11/Barotrauma/files/4584306/crashreport.98.log)
[crashreport (99).log](https://github.com/Regalis11/Barotrauma/files/4584307/crashreport.99.log)

**Comment by thegrb93** [comment] 2020-05-06 00:09
99% sure it's your intel graphics. Your PC is not fit for gaming. My game doesn't crash at all.

**Comment by VenipedeGaming** [comment] 2020-05-06 00:25
> 99% sure it's your intel graphics. Your PC is not fit for gaming. My game doesn't crash at all.

What can  I do about  it? I'm capable of running other games perfectly fine that are most likely more intense, Rising Storm 2, Garry's Mod, and Total War: Shogun 2 to name a few with few or no issues at all. My computer is an Inspiron 15 7000 Gaming for epic gaming.

**Comment by thegrb93** [comment] 2020-05-06 00:57
Maybe you need to install nvidia drivers? The specs say that that machine should have a GTX 1050.

**Comment by VenipedeGaming** [comment] 2020-05-06 01:15
> Maybe you need to install nvidia drivers? The specs say that that machine should have a GTX 1050.

I uh, really don't know how to do so.

**Comment by thegrb93** [comment] 2020-05-06 01:38
Might want to google that then. It's pretty easy to do.

**Comment by Regalis11** [comment] 2020-05-06 06:56
Duplicate of #1833 

But yeah, this does sounds like it could be a driver issue. Based on the crash report, the game is running on an integrated GPU, even though your machine should have a GTX 1050 which should be powerful enough to run the game.

**Closed by Regalis11** 2020-05-06 06:56 UTC
