### ISSUE TITLE
[0.10.503] Railgun Turret not aligned to the base

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3764] opened 2020-09-07 20:56 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Railgun turret not aligned to the base
![Capture](https://user-images.githubusercontent.com/5086682/92416352-0b147800-f12b-11ea-9784-3e6d2e273d8a.PNG)

**Version**
0.10.503

**Comment by EtiamNullam** [comment] 2020-09-08 02:30
Use `Base Rotation` under `TURRET` for rotating turrets rather than `Rotation` that is common for every object.

**Comment by Kaillera** [comment] 2020-09-08 07:49
This was literally a default railgun

**Comment by Regalis11** [comment] 2020-09-08 08:17
@EtiamNullam The base rotation property has been removed in the Unstable version, the turrets are rotated with the Rotation property instead.

In any case, I was not able to reproduce this. Tested by adding a bunch of railguns to a sub, setting them to various different rotations, then saving and reloading the sub.

**Comment by Kaillera** [comment] 2020-09-08 08:44
Was a default railgun from 0.10.4

**Comment by EtiamNullam** [comment] 2020-09-08 12:39
Saved various rotation configurations of railgun (including default) on sub in 0.10.4.0. After launching it in 0.10.503.0 all of them were aligned correctly.

**Comment by Kaillera** [comment] 2020-09-08 17:49
I found what it is. It's not aligned when the scale is is below 0.500

**Comment by 3e849f2e5c** [comment] 2020-11-12 11:53
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/64d5e6b0f3b6f58e98cb8eafa6c7ad4b16bc6017

**Comment by Xeavas** [comment] 2020-11-13 17:25
[0.1100.0.6] - Can't replicate 👍 
Tested by placing railguns of various sizes < 0.5 scale then saving and reloading.
![railguntest](https://user-images.githubusercontent.com/72674994/99101912-41cda980-2618-11eb-9575-6dd33fd80e5c.jpg)

**Comment by Rokvach** [comment] 2020-11-13 17:26
Closing.

**Closed by Rokvach** 2020-11-13 17:26 UTC
Labels: Bug, Code
