### ISSUE TITLE
Crash report: TabMenu

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#3517] opened 2020-08-06 21:45 UTC
Void ReadIngameUpdate(Barotrauma.Networking.IReadMessage)

**Version**
v0.10.4.0 rev 20132d25fb Windows 10

**Additional information**
I think I clicked an object when the game crashed to the menu.
[crashreport_object.log](https://github.com/Regalis11/Barotrauma/files/5038172/crashreport_object.log)

**Comment by mygamingaccount** [comment] 2020-08-10 15:52
Is this the one where it crashes when you press <TAB>?

**Comment by Regalis11** [comment] 2020-08-19 10:44
Couldn't find a way to repro this, but I suspect it happened when trying to add a line to the connection/disconnection log before the UI element of the log had been instantiated. If that was the cause, https://github.com/Regalis11/Barotrauma-development/commit/fcfc3ef5a64b83283b8f38652b995793ea68e75a should fix the issue.

**Comment by Rokvach** [comment] 2020-09-08 09:54
Didn't notice any issues while using the tab menu during multiplayer, not sure if thats enough to test this but as there is no clear way to test this issue thats the best I've got, closing the ticket we can re-open it if the issue comes back. Closing.

**Closed by Rokvach** 2020-09-08 09:54 UTC
Labels: Bug, Code, Crash
