### ISSUE TITLE
Sub Editor - Crash after shuttle copy

### ISSUE THREAD

**Issue by KB0MB4** [Regalis11/Barotrauma#3917] opened 2020-09-26 22:15 UTC
**Description**
Crash after shuttle copy.

**Steps To Reproduce**
Load the sub file in editor, deleate the upper shuttle, ctrl+lmb the lower shuttle instead or it and it crashes.

**Version**
Game version 0.10.5.1 (ReleaseWindows, branch release, revision 9e259b2148)
Microsoft Windows NT 10.0.19041.0 64 bit

**Additional information**
[crashreport (7).log](https://github.com/Regalis11/Barotrauma/files/5287395/crashreport.7.log)

**Comment by Regalis11** [comment] 2020-09-28 12:59
I'm afraid I wasn't able to reproduce this with the steps provided, but based on the crash report I suspect what happened was that you tried to clone a linked submarine that you don't own the submarine file for.

Steps to repro:
1. Load some submarine file that includes linked submarines
2. Delete the linked submarine file
3. Try to clone one of the linked submarines

If that was the cause, it should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/9b77921481ccb5634e911fb1f7f380b4d5cd09df

**Comment by Rokvach** [comment] 2020-09-29 08:57
No issues, closing.

**Closed by Rokvach** 2020-09-29 08:57 UTC
Labels: Bug, Code, Crash
