### ISSUE TITLE
Can't Start A Game

### ISSUE THREAD

**Issue by NaMea31** [Regalis11/Barotrauma#8952] opened 2022-04-24 11:25 UTC
**Description**
When I (or my friend) host a game and try to start it it loads for a bit and sends us back to the menu and the console says

Error while starting the round (did not receive STARTGAMEFINALIZE message from the server). Stopping the round..
Timed Out
Coroutine "Barotrauma.Networking.GameClient+<StartGame>d__95" has failed.

Can somebody please help?

It started happening on Urban Expanses update.

![barotrauma](https://user-images.githubusercontent.com/104304385/164974112-225de02b-13ae-47a9-afeb-d0a00e314680.png)

**Comment by Regalis11** [comment] 2022-04-25 07:11
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7896

**Closed by Regalis11** 2022-04-25 07:11 UTC
