### ISSUE TITLE
Game crashes after leaving outpost/station.

### ISSUE THREAD

**Issue by Amog0** [Regalis11/Barotrauma#11090] opened 2023-01-29 18:31 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Essentially, after trading. Selecting missions and finally leaving the dock (in a metaphorical way, in reality i just stare at a loading screen) the game suddenly crashes, this happens to me with and without mods.

It might be a GPU error, since i run this game on an old laptop. Or something else because i remember quite clearly my first 150 hours running clean, and i already had the issue of having a corrupted file just crashing the game on the start.

I am aware i am using Lua, but as stated previously it crashes anyway with or without mods.

Strangely, it only happens when leaving stations/cities. This doesn't happen on Linea's

### Bug prevalence

Happens regularly

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 01/29/2023 19:18:19)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

The crash was caused by the DirectX error DeviceRemoved (HRESULT = 0x887A0005). This is a common DirectX error that can be related to various different issues, such as outdated drivers, RAM problems or an overclocked or otherwise overstressed GPU. There are several potential ways to fix the issue: ensuring your graphics drivers and DirectX installation are up-to-date, disabling overclocking and adjusting various GPU-specific settings. You may also be able to find potential solutions to the problem by using the error code DeviceRemoved (HRESULT = 0x887A0005) and your GPU manufacturer as search terms.

B1E3E2D3D6E9C339D6CB342EC5799AD4

Game version 0.20.16.1 (ReleaseWindows, branch master, revision 5807900556)
Graphics mode: 1366x768 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla, [AP] Belfast, [AP] Kleber, [AP] Centurio, Super Plague Rat, Bronze Age, LEGIONAR, Wellerman, Golden mice, The Deep Manatee, Wyvern, Shiftless, Fat Fish, ATK-89 "Sardine", Cast Iron, The Plague Rat, [AP] Curie, [AP] Sakala, [AP] Bohr, [AP] Skua, [AP] Kleber B4, [AP] Taiidan, [AP] Cormoran, [AP] Meteor, [AP] Catran, [AP] Bomut, [AP] Warden, [AP] Comet, [AP] Tanit, [AP] Ochakov, Hazardous Reactors, [AP] Salut11, EK | Utility, Lua For Barotrauma, Backpacks, [AP] Sever, Indra, Wreck Corpses, Saber Personal Protection Revived ( + Deeper Diving), Saber Armaments Revived, Mechno's & Duke's Maddened Black Sea Armory, Better Exosuit with Platform 外骨骼优化和置物架, Inglia, [AP] Tabrat М2, [AP] Brusilov, [AP] Tarbatagai, Performance Fix
Level seed: GuthlaugHarmonia Linea
Loaded submarine: Indra (39D4634D8FF5145B0FA608DB596E1037)
Selected screen: Barotrauma.RoundSummaryScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: Intel(R) HD Graphics 3000
    Display mode: {Width:1366 Height:768 Format:Color AspectRatio:1.7786459}
    GPU status: Normal

Exception: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.
 (SharpDX.SharpDXException)
Device removed reason: DeviceRemoved (HRESULT = 0x887A0005)
Target site: Void PlatformPresent()
Stack trace: 
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 1017
   at Microsoft.Xna.Framework.Game.Tick() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args)

Last debug messages:
[01/29/2023 19:18:17] Level identifier: coldcavernsbasic
[01/29/2023 19:17:12] Transitioning to GuthlaugHarmonia Linea (current location: Guthlaug Mine, selected location: Harmonia Linea Mine, leaving sub: Indra, at start: True, at end: False, transition type: LeaveLocation)
[01/29/2023 19:11:43] WARNING: Failed to unlock a mission with the tag "escortcommoners": all available missions have already been unlocked.
[01/29/2023 19:11:41] Unlocked mission "Mining Uranium Ore" in the connection from "Guthlaug Mine" to "Harmonia Linea Mine".
[01/29/2023 19:11:39] Unlocked mission "Terminate a Swarm" in the connection from "Guthlaug Mine" to "Topol Fortification".
[01/29/2023 19:10:28] Generating an outpost for the start of the level... (Location: Guthlaug Mine, level type: Outpost)
[01/29/2023 19:10:28] Level identifier: outpostlevel
[01/29/2023 19:10:10]  - init.lua (Took 0.19457ms)
[01/29/2023 19:10:10] Performance Fix 1.0.11
[01/29/2023 19:10:10]  - init.lua (Took 0.00977ms)
[01/29/2023 19:10:10] Performance Fix 1.0.11
[01/29/2023 19:10:10]  - HazardousReactor_hostside.lua (Took 0.01802ms)
[01/29/2023 19:10:10]  - HazardousReactor_bothside.lua (Took 0.06251ms)
[01/29/2023 19:10:10] Hazardous Reactors 1.0.39
[01/29/2023 19:10:08] Using LuaSetup.lua from the content package.
[01/29/2023 19:10:07] Lua! Version 5807900556
[01/29/2023 19:09:58] Stopping Lua...
[01/29/2023 19:09:47] Unlocked mission "Mining outpost material transport" in the connection from "Guthlaug Mine" to "Harmonia Linea Mine".
[01/29/2023 19:09:44] Unlocked mission "Personnel Transport" in the connection from "Guthlaug Mine" to "Harmonia Linea Mine".
[01/29/2023 19:09:43] Unlocked mission "Killing a large Crawler" in the connection from "Guthlaug Mine" to "Harmonia Linea Mine".
[01/29/2023 19:08:37] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/HP/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/1946765892/Items/Tools/ekutility_placeableconsoles.png, size: 767x767)
[01/29/2023 19:06:54] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/HP/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2830528928/armoricons.png, size: 416x133)
[01/29/2023 19:05:24] Generating an outpost for the start of the level... (Location: Guthlaug Mine, level type: Outpost)
[01/29/2023 19:05:23] Level identifier: outpostlevel
[01/29/2023 19:04:29] Transitioning to Guthlaug (current location: Kury Habitation Outpost, selected location: Guthlaug Mine, leaving sub: Indra, at start: False, at end: True, transition type: ProgressToNextLocation)
[01/29/2023 18:56:51] Generating an outpost for the end of the level... (Location: Guthlaug Mine, level type: LocationConnection)
[01/29/2023 18:56:49] Generating an outpost for the start of the level... (Location: Kury Habitation Outpost, level type: LocationConnection)
[01/29/2023 18:56:49] Level identifier: coldcavernsbasic
[01/29/2023 18:53:07] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/HP/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2830528928/Jobgear/MiscJobGear.png, size: 1024x411)
[01/29/2023 18:53:07] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/HP/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2613901395/Icons/Toolbox.png, size: 240x174)
[01/29/2023 18:53:07] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/HP/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2613901395/Icons/Heavy.png, size: 240x174)
[01/29/2023 18:52:55] Generating an outpost for the end of the level... (Location: Guthlaug Mine, level type: LocationConnection)
[01/29/2023 18:52:48] Generating an outpost for the start of the level... (Location: Kury Habitation Outpost, level type: LocationConnection)
[01/29/2023 18:52:47] Level identifier: coldcavernsbasic
[01/29/2023 18:51:52] Transitioning to KuryGuthlaug (current location: Kury Habitation Outpost, selected location: Guthlaug Mine, leaving sub: Indra, at start: True, at end: False, transition type: LeaveLocation)
[01/29/2023 18:51:35] Unlocked mission "Personnel Transport" in the connection from "Kury Habitation Outpost" to "Guthlaug Mine".
[01/29/2023 18:51:33] Unlocked mission "Killing a large Crawler" in the connection from "Kury Habitation Outpost" to "Guthlaug Mine".
[01/29/2023 18:51:31] Unlocked mission "Mining outpost material transport" in the connection from "Kury Habitation Outpost" to "Guthlaug Mine".
[01/29/2023 18:49:54] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/HP/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2613901395/Techno-Backpack/Techno-Backpack.png, size: 237x201)
[01/29/2023 18:47:22] Generating an outpost for the start of the level... (Location: Kury Habitation Outpost, level type: Outpost)
[01/29/2023 18:47:22] Level identifier: outpostlevel
[01/29/2023 18:47:04]  - init.lua (Took 0.05220ms)
[01/29/2023 18:47:04] Performance Fix 1.0.11
[01/29/2023 18:47:04]  - init.lua (Took 0.00081ms)
[01/29/2023 18:47:04] Performance Fix 1.0.11
[01/29/2023 18:47:04]  - HazardousReactor_hostside.lua (Took 0.01184ms)
[01/29/2023 18:47:04]  - HazardousReactor_bothside.lua (Took 0.05591ms)
[01/29/2023 18:47:04] Hazardous Reactors 1.0.39
[01/29/2023 18:47:03] Using LuaSetup.lua from the content package.
[01/29/2023 18:47:02] Lua! Version 5807900556
[01/29/2023 18:43:39] Stopping Lua...
[01/29/2023 18:43:23] Unlocked mission "Mining outpost material transport" in the connection from "Binnsmouth" to "Alphesiboea Linea".
[01/29/2023 18:40:41] Loading a pre-selected outpost for the start of the level...
[01/29/2023 18:40:41] Level identifier: outpostlevel
[01/29/2023 18:39:59]  - init.lua (Took 0.30522ms)
[01/29/2023 18:39:59] Performance Fix 1.0.11
[01/29/2023 18:39:59]  - init.lua (Took 0.02029ms)
[01/29/2023 18:39:59] Performance Fix 1.0.11
[01/29/2023 18:39:59]  - HazardousReactor_hostside.lua (Took 0.04626ms)
[01/29/2023 18:39:59]  - HazardousReactor_bothside.lua (Took 0.04894ms)
[01/29/2023 18:39:59] Hazardous Reactors 1.0.39
[01/29/2023 18:39:52] Using LuaSetup.lua from the content package.
[01/29/2023 18:39:50] Lua! Version 5807900556
[01/29/2023 18:38:05] Overriding an affliction or a buff with the identifier 'nausea' using the file 'C:/Users/HP/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2547888957/Content/Items/Medical/Afflictions.xml'
[01/29/2023 18:38:05] Overriding an affliction or a buff with the identifier 'radiationsickness' using the file 'C:/Users/HP/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2547888957/Content/Items/Medical/Afflictions.xml'
[01/29/2023 18:30:59] Attempting to open ALC device "OpenAL Soft on Głośniki (2- High Definition Audio Device)"
[01/29/2023 18:30:08] Logged in as ____ (SteamID _____)
(Name and ID blurted out for privacy)
```

**Comment by Regalis11** [comment] 2023-01-30 08:10
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10540

**Closed by Regalis11** 2023-01-30 08:10 UTC
