### ISSUE TITLE
Corrupted save file (singleplayer)

### ISSUE THREAD

**Issue by C-nux** [Regalis11/Barotrauma#4544] opened 2020-12-16 16:48 UTC
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
After finishing a mission, the game crashed when docking. The save file is left corrupted without any backup file. The error message I get on the console if I try to load it is:
"Failed to generate a wall (not enough vertices)."
Could not find a way to copy the text from the console, but if you tell me how, I can paste the entire error message here

**Steps To Reproduce**
I finished a "Terminate a Crawler Swarm" mission, similar to [https://github.com/Regalis11/Barotrauma/issues/3459](url).
After failing few times to load the save, I checked the game files with steam, fixing one file (but don't know which one).

**Version**
v0.11.0.10 on Linux

**Additional information**
I can upload the save if that helps you.

**Comment by Regalis11** [comment] 2020-12-17 13:41
Thank you for the report! The save file would be really helpful: based on the error message I'd guess it's some rare level generation bug where some wall doesn't generate properly, which would be hard to fix without a level seed or a save file where the issue occurs.

You can attach to save file in a github post by zipping it first (since github doesn't allow attaching the .save files directly). Thank you in advance, and sorry for the inconvenience!

**Comment by C-nux** [comment] 2020-12-17 14:16
Thank you for the reply. I attached the save file and the custom submarine I used.

[savegame.zip](https://github.com/Regalis11/Barotrauma/files/5709956/savegame.zip)
[submarine.zip](https://github.com/Regalis11/Barotrauma/files/5709957/submarine.zip)

**Comment by Regalis11** [comment] 2020-12-18 09:25
Thank you, I think I figured out the problem now! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0665c3f54e8dc1d350643659ae40246cd8fd3e6c, coming up in the next unstable version.

I also edited the save file to change the level seed that was causing this error, you should be able to continue playing the save by replacing it with this one:
[Speichern.zip](https://github.com/Regalis11/Barotrauma/files/5714795/Speichern.zip)

**Comment by Rokvach** [comment] 2020-12-18 10:24
Tested, wasn't able to reproduce the issue, seems to be working correctly. Closing.

**Closed by Rokvach** 2020-12-18 10:24 UTC
Labels: Bug, Code
