### ISSUE TITLE
Problems with achievement "Insurgency"

### ISSUE THREAD

**Issue by MrRaymanViy** [Regalis11/Barotrauma#13056] opened 2023-11-18 17:59 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If the conditions for obtaining the "insurgency" achievement are met, the achievement itself does not count towards steam.

### Reproduction steps

1. Play Multiplayer.
2. Get traitor
3. Finish the Traitor task
4. Complete the Round

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-11-19 12:37
Duplicate of https://github.com/Regalis11/Barotrauma/issues/13053

**Closed by Regalis11** 2023-11-19 12:37 UTC
